### ISSUE TITLE
Need to have InferredFromUsage style configuration/platform property groups defined in the SDK props 

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/sdk#1001]
The InferredFromUsage configs need to be removed from the props once all of the insertions in VS are in place.

**Comment by livarcocc** [comment]
I am not sure what this is and how it relates to the SDK.

@RaulPerez1 I am going to close this issue, but if you can provide more details, we can easily re-activate.

**Comment by nguerrera** [comment]
We've already removed the code here: https://github.com/dotnet/sdk/commit/38cd3bdfa3c7ed47c533b9ecc98e0310ea126282#diff-7eff410a9a7fafbb40f5405239e45623L130

**Comment by nguerrera** [comment]
No, that only removed a duplicate copy of the code. 

This bug tracks removing the following, which was only supposed to be necessary for a period of time during VS 15.3 development where not all components with configuration-related changes were inserted with the needed fixes to not have it.

https://github.com/dotnet/sdk/blob/83ba345017d368c80e2d24090a2507a0f4627001/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L121-L123
