### ISSUE TITLE
DependencyModel.CompilationLibrary.ResolveReferencePaths() fails after "dotnet restore --packages"

### ISSUE THREAD

**Issue by mikeharder** [dotnet/sdk#1002]
If a project has been restored with "dotnet restore --packages", then `DependencyModel.CompilationLibrary.ResolveReferencePaths()` will fail unless the `NUGET_PACKAGES` environment variable is set.

Here are steps to reproduce.  It should be possible to create a significantly minimized repro, but I was unable to do so.

1. VM with clean Win10
2. Install SQL Server 2016 SP1 Express Edition
 a. http://download.microsoft.com/download/B/F/2/BF2EDBB8-004D-47F3-AA2B-FEA897591599/SQLServer2016-SSEI-Expr.exe
 b. Install Type: Basic
3. Add LocalDB to SQLEXPRESS
 a. Run SQLServer2016-SSEI-Expr.exe again
 b. Click "New SQL Server stand-alone installation or add features to an existing installation"
 c. Installation Type: Add features to an existing instance "SQLEXPRESS"
 d. Select "LocalDB"
4. Install .NET Core SDK
 a. https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe
5. `git clone https://github.com/aspnet/benchmarks`
6. `cd benchmarks`
7. `git checkout ea3c953d47bac8887505186688497d14f725cc94`
 a. Known good commit
8. `cd src\Benchmarks`
9. `dotnet restore --packages ..\..\packages`
10. `dotnet build -c Release -f netcoreapp1.1`
 a. Ignore warning about "detached HEAD mode"
11. `dotnet bin\Release\netcoreapp1.1\Benchmarks.dll --scenarios MvcDbFortunesEf --loglevel error`
12. Browse to http://locahost:5000/mvc/fortunes/ef

```
System.InvalidOperationException: Can not find compilation library location for package 'dapper'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
```

13. `set NUGET_PACKAGES=..\..\packages`
14. `dotnet bin\Release\netcoreapp1.1\Benchmarks.dll --scenarios MvcDbFortunesEf --loglevel error`
15. App works correctly

**Comment by eerhardt** [comment]
Assigning to @ramarag to fix along with https://github.com/dotnet/core-setup/issues/624, which is basically the same issue.

See https://github.com/dotnet/core-setup/issues/624#issuecomment-288245699 for the high-level strategy to fix these issues.

**Comment by ramarag** [comment]
This should be fixed now
