### ISSUE TITLE
CLI and SDK repos should be rationalized/rebranded

### ISSUE THREAD

**Issue by leecow** [dotnet/sdk#1004]
Currently the SDK repo seems to represent only msbuild tasks and templates whereas the CLI repo covers all engineering, building and releasing of what is the actual .NET Core SDK. This creates a great deal of confusion both internal and external. The repo that builds the SDK should more obviously be "the SDK".

This is a part of an examination and clean up of our repos discussed in [core-setup #1707](https://github.com/dotnet/core-setup/issues/1707)

/cc @richlander @Petermarcu @livarcocc

**Comment by nguerrera** [comment]
I agree this is confusing. How about dotnet/cli -> dotnet/coresdk, dotnet/sdk -> dotnet/coretasks?

Will GitHub forward links from the old repo names if we rename?

**Comment by richlander** [comment]
Yes, GitHub will forward links. We have done it in the past. For example, dotnet/docs used to be dotnet/core-docs.

My only concern is the scope. As we discussed in person, our repos seems to have a way of being broader than just .NET Core. The docs repo is a good example of this.

We could go with "core-sdk" and "tasks". This would enable us to build an SDK that is fundamentally the .NET Core SDK but that can operate on tasks and targets that are broader than just .NET Core.

**Comment by nguerrera** [comment]
The plan is still for sdk to merge with CLI, and tracked elsewhere.
