### ISSUE TITLE
dotnet build ignores -f option in some cases

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/sdk#10060]
Please see the attached project
[build-framework-test.zip](https://github.com/dotnet/cli/files/2772232/build-framework-test.zip)

## Steps to reproduce
1) Create a new class library
2) Create another class library, make it dependent on the first one
3) Replace TargetFramework with TargetFrameworks (e.g. `<TargetFrameworks>netcoreapp3.0;net452</TargetFrameworks>`)
4) Try to build solution against only one framework:
`dotnet build -f netcoreapp3.0  .\build-framework-test.sln`

## Expected  behavior
First library is built against specified framework

## Actual behavior
First library is built against all frameworks
`  ClassLibrary1 -> C:\work\projects\tests\build-framework-test\ClassLibrary1\bin\Debug\netcoreapp3.0\ClassLibrary1.dll`
  `ClassLibrary1 -> C:\work\projects\tests\build-framework-test\ClassLibrary1\bin\Debug\net452\ClassLibrary1.dll`
  `ClassLibrary2 -> C:\work\projects\tests\build-framework-test\build-framework-test\bin\Debug\netcoreapp3.0\ClassLibrary2.dll`

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010124
 Commit:    41a73b60f2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010124\

Host (useful for support):
  Version: 3.0.0-preview1-26919-02
  Commit:  9ea8c26816

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009616 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010124 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19067-0383 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-26829-8 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27316-4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-26919-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27316-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by MiYanni** [comment]
Old bug triage: Does no repro on latest SDK. Please reopen if there is still a problem.
