### ISSUE TITLE
VS2017 Not Copying Satellite Assemblies to Proper Output Location

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1006]
_From @thefringeninja on March 16, 2017 17:21_

I've been porting a project over to the new .csproj format. This project has a dependency on `FluentValidation`, which uses satellite assemblies. In VS2015, on compilation, these would be placed in their correct subfolders. VS2017 places all the satellite assemblies in the root build output folder. Since they all have the same filename, only one remains.

Minimal repro project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="5.5.0" />
  </ItemGroup>

</Project>
```

_Copied from original issue: Microsoft/msbuild#1877_

**Comment by nguerrera** [comment]
_From @cdmihai on March 16, 2017 18:11_

@srivatsn This looks like an SDK issue, right?

**Comment by nguerrera** [comment]
_From @thefringeninja on March 17, 2017 14:0_

Never mind. The issue was that I was running `dotnet build` not `dotnet publish`.

**Comment by nguerrera** [comment]
_From @thefringeninja on March 17, 2017 14:27_

Spoke too soon! VS2017 and Rider will use `dotnet build`. Why does it behave differently than `dotnet publish`?

**Comment by nguerrera** [comment]
_From @AndyGerlicher on March 17, 2017 17:56_

@livarcocc can  you comment on this please?

**Comment by nguerrera** [comment]
_From @livarcocc on March 17, 2017 22:36_

@dsplaisted @nguerrera can you guys comment?

**Comment by nguerrera** [comment]
Looks like a bug in CopyLocalLockFileAssemblies handling of satellites. I'll move this to SDK and investigate. 

@thefringeninja Thanks for the report.

**Comment by AArnott** [comment]
Per #1132 this only repros for me when the project defines the `TargetFrameworks` property.

**Comment by nguerrera** [comment]
@AArnott Thanks. I missed that subtlety in #1132. Strangely, the repro steps here for the same symptom show `TargetFramework` not `TargetFrameworks`. We'll have to look a both cases to be sure.

**Comment by onovotny** [comment]
Probably the same issue I just filed here https://github.com/NuGet/Home/issues/5164

Repros with Humanizer. Steps in linked bug

**Comment by karelz** [comment]
@nguerrera we believed this is release blocker. Do you agree?
Or is there some workaround @onovotny didn't find?

**Comment by nguerrera** [comment]
I agree. I have not looked for a workaround. I plan to fix this soon.

**Comment by karelz** [comment]
Awesome, thanks a lot!

**Comment by nguerrera** [comment]
PR #1224 is out to fix this

**Comment by nguerrera** [comment]
Fixed by #1224

**Comment by PatoMickey** [comment]
Any news on this issue? The problem stills to occur.

**Comment by pharring** [comment]
[Just making a note for search engines to pick up the following error messages.]
If you see the following error while running unit tests in VSTS:

> Warning: Test Run deployment issue: an error occurred while getting satellite assemblies for deployment item
> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex

then it may be caused by this issue. The workaround at #1124 should fix it.
