### ISSUE TITLE
Cannot build a supported target when an unsupported target exists in `<TargetFrameworks>`

### ISSUE THREAD

**Issue by firelizzard18** [dotnet/sdk#10064]
## Steps to reproduce

1. On Windows, install .NET Core 2.0 SDK and .NET Framework 4.7 SDK
2. `dotnet new console -o test`
3. `cd test`
4. In `test.csproj`, replace `<TargetFramework>...` with `<TargetFrameworks>net47;netcoreapp3.0</TargetFrameworks>`
5. `dotnet build -f net47`

## Expected  behavior

The CLI builds and runs the project using the specified target framework. The fact that there are other valid target frameworks is ignored.

## Actual behavior

```
Microsoft (R) Build Engine version 15.6.84.34536 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.1.104\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\Source\temp\build-test\build-test.csproj]

The build failed. Please fix the build errors and run again.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by dsplaisted** [comment]
The reason this happens is we still run restore for all the target frameworks, even if you are only building for one.  I don't think we should change this, as that's what lets NoOp restore work.  This will also probably be less of an issue for the .NET 5 SDK, as it will automatically bring in the .NET Framework targeting pack packages as necessary, so on non-Windows machines you won't run into this for projects targeted between .NET Framework and .NET Core.
