### ISSUE TITLE
Building VSSDK projects with the new project system

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1008]
_From @twsouthwick on January 10, 2017 17:36_

I have a project with a few libraries that is currently building with the new project system and we want to add a VS extension to it. However, it doesn't seem to run any of the SDK targets. I've created a repro here: https://github.com/twsouthwick/vs17sdk. It builds fine, but no package is created. Is there a way to support this or is it not expected to work at the moment?

_Copied from original issue: dotnet/roslyn-project-system#1121_

**Comment by davkean** [comment]
@mavasani Were you running into the same thing in the SDK repo?

**Comment by davkean** [comment]
_From @srivatsn on January 30, 2017 17:4_

I don't see why it wouldn't work. I've converted some VSIX projects in this repo to use the SDK and it seems to work fine. Can you do a msbuild /pp on this project and check if the VSSDK targets are getting pulled in?

**Comment by davkean** [comment]
_From @twsouthwick on January 30, 2017 18:19_

@Srivatsn Can you point me at one? When I run the `msbuild /pp` command it looks like the targets are being included. The issue seems to be in the `CreateMenuPkgDef` target.

```
4>Target CreateMenuPkgDef:
4>  Skipping target "CreateMenuPkgDef" because it has no outputs.
```

**Comment by davkean** [comment]
_From @srivatsn on January 30, 2017 18:36_

https://github.com/srivatsn/roslyn-project-system/tree/dogfood is the branch. The VSIX projects (ProjectsystemSetup for eg) include some repo-specific targets and I added the SDK attribute there.

**Comment by davkean** [comment]
_From @twsouthwick on January 30, 2017 18:51_

Looks like those projects are still including some items that are not required in the new version, such as the namespace, ToolsVersion="12.0", project guids, etc. Will that make a difference?

**Comment by twsouthwick** [comment]
This seems to be working now on RTM and can't repro the issue I was seeing.

**Comment by davkean** [comment]
Thanks for the followup.
