### ISSUE TITLE
Build error after changing .csproj for .NET core, goes away after git clean -xdf

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1009]
_From @KirillOsenkov on February 8, 2017 19:8_

Repro:
1. git clone https://github.com/KirillOsenkov/MSBuildStructuredLog
2. git checkout 22cbbbc084ac5ccffadc4e35d4561e18621782e3
3. nuget restore
4. msbuild <-- this is important
5. Open MSBuildStructuredLog.sln in VS 2017 RC4 (or newer)
6. Make sure it builds from the IDE (F6)
7. Unload StructuredLogger project and edit the .csproj
8. Replace the .csproj contents with this: https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/d3e5742cbc1c7bfc914acaee594aa09b6da92202/src/StructuredLogger/StructuredLogger.csproj
9. Reload the project
10. Build (you can even Clean/Rebuild)

Expected: build succeeded
Actual: build error: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute	StructuredLogger(netstandard1.5)	C:\MSBuildStructuredLog\src\StructuredLogger\obj\Debug\net46\StructuredLogger.AssemblyInfo.cs	18	Active
```

This is fixed only by BOTH closing VS and doing git clean -xdf.

If you don't close VS and do git clean -xdf, you get 39 errors.
If you close VS and don't git clean -xdf, you still get the 1 error above.

_Copied from original issue: dotnet/roslyn-project-system#1496_

**Comment by davkean** [comment]
_From @srivatsn on February 8, 2017 19:54_

I suspect the assemblyinfo file generated by project.json is called differently from the one generated by the SDK and that causes both files to be around until you do a git clean -xdf?

**Comment by davkean** [comment]
_From @KirillOsenkov on February 8, 2017 21:1_

Does the SDK generate an assembly info file? Where can I find out more about this? I've only seen one file in the repo (in obj) (the other might go to TEMP?)

Also how do I investigate what got passed to Csc? Somehow the log output from inner builds doesn't make it into the logger...

**Comment by davkean** [comment]
_From @srivatsn on February 8, 2017 21:5_

Yes see here - https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets

I'm not aware of issues with loggers - the inner build is just a msbuild invocation - do the loggers need to passed through specifically?

**Comment by davkean** [comment]
_From @KirillOsenkov on February 8, 2017 22:51_

No, it was a problem on my end. Everything is fine.

So the real problem in this bug is that the error (although legit - since both NerdBank.GitVersioning and the SDK are generating the AssemblyTitle attribute) doesn't go away after I fix it unless I git clean and restart VS.

**Comment by davkean** [comment]
_From @srivatsn on February 9, 2017 21:15_

> doesn't go away after I fix it 

How are you fixing it? By turning off assembly info generation? Are you saying that when that's turned off the temp file from obj is not getting deleted?

**Comment by davkean** [comment]
_From @KirillOsenkov on February 10, 2017 0:45_

Sorry I got super confused by a similar bug yesterday. Please ignore my comment about NerdBank.GitVersioning. 

The repro steps above still seem to constitute a problem though...

**Comment by davkean** [comment]
Trying to understand the issue, is the bug that you've turned off assembly generation - and we're still picking up the AssemblyInfo until you git clean?

**Comment by livarcocc** [comment]
@KirillOsenkov can you answer @davkean's question above? What exactly is the issue that you are facing here?

**Comment by KirillOsenkov** [comment]
I've tried to repro in VS 2017 Update 1 and it no longer reproes. Closing.
