### ISSUE TITLE
No way to override resolution behaviour for floating versions in PackageReference

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/sdk#1011]
Given a `PackageReference` with a floating version that accepts pre-releases, e.g. `2.3-*`, then `dotnet restore` will always pick the oldest pre-release version. This is contrary to the description of [floating versions in NuGet for project.json](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions) (as linked to from the [`PackageReference` docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#floating-versions)).

Is there an msbuild switch to work around this bug?

**Comment by dsplaisted** [comment]
@emgarten

This sounds like it might be a NuGet bug, and I don't think there's anyway of changing this behavior.

It might be that the version number is not specified in a way NuGet likes.  2.3.0-* might work better (though you may not want to restrict the patch version).

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4859
