### ISSUE TITLE
Add `dotnet tool update --all` option

### ISSUE THREAD

**Issue by fredrikhr** [dotnet/sdk#10130]
## Request

When multiple tools are installed, either globally or locally, it becomes hard to keep track of which tools are outdated and which are not, and updating all outdated tools is time-consuming and boring copy-paste work, since the package id of each installed package needs to be provided to the `dotnet tool update` command.

I propose to add the `--all` (alias: `-a`) option to the `dotnet tool update` command. This option would simply run `dotnet tool list` internally and use the results obtained from that command to get the package ids that are installed. Then the `dotnet tool update` command could be called with each of these package ids.

## Background

Updating all installed programs is very usual operation for package maintance application to do. `apt upgrade` on Debian/Ubuntu, `npm upgrade` for NPM, etc.

I have encountered the same problem in Python, however, there one can (semi-)easily write a Windows CMD `FOR` command that uses the `pip list --outdated --format=freeze` command.

Currently, the only way to update all packages installed with `dotnet tool` is to parse the output of `dotnet tool list`. That means I now have to write a PowerShell script that ignores the first two lines (the header and header-splitter) and parses the package id from the start of the line to the first whitespace. Yes, it's doable, but it would be much more convenient to have a command that just does all that for you. Also, adding an option in the actual executable means that `dotnet` can use it's own data representation of the information on the installed packages, and thus does not have to be subject to changes in the output format, invalid characters when printed to the console, and all that stuff.

## Environment data

`dotnet --info` output:
``` txt
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.1 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.2.100-preview1-009349 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview1-35029 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview1-35029 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview-26820-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by lindexi** [comment]
I write a tool that can update all dotnet tool

## Installation

```
dotnet tool install --global dotnetCampus.UpdateAllDotNetTools 
```

## Usage

```
dotnet updatealltools
```

[dotnet-campus/dotnetCampus.UpdateAllDotNetTools: The dotnet tool that can update all dotnet tools](https://github.com/dotnet-campus/dotnetCampus.UpdateAllDotNetTools )

**Comment by vilinski** [comment]
the same as F# script: https://github.com/vilinski/fsharp-scripts/blob/master/toolupdate.fsx

    dotnet fsi toolupdate.fsx

no installations needed

**Comment by breiter** [comment]
You can also do this on linux and Mac by piping the <PACKAGE_ID> list from the output of `dotnet tool list --global` to `dotnet tool update --global`

```sh
#!/bin/sh

# list global tools installed
# select tool <PACKAGE_ID>
# execute `dotnet tool update --global <PACKAGE_ID>`

dotnet tool list --global | awk 'NR > 2 {print $1}' | xargs -L1 dotnet tool update --global
```

**Comment by void-type** [comment]
Here's a PowerShell script that I added to my app repos. It updates local tools to a specific framework version.

``` powershell
# upgradeTools.ps1

$json = Get-Content ../.config/dotnet-tools.json |
  ConvertFrom-Json

$json.tools.psobject.Properties.Name |
  ForEach-Object { dotnet tool update $_ --framework netcoreapp3.1 }
```

**Comment by fredrikhr** [comment]
I am considering to write myself a tool that uses the techniques shown above, but also uses Nuget to determine whether a tool actually is out of date. You might have noticed that `dotnet tool update` always re-installs (even if the the tool in question is up-to-date)

**Comment by tebeco** [comment]
well the idea of this issue i  0 custom scripts ;)
it should be first built in to be useable on CI / DevBox

* It should be part of `dotnet tool` it self
* no third part script/tool to request a tool (dotnet) to update a tool (that should hurt people just to read this sentence ^^) 
  I mean i love contributions/ open source / etc .... but this is not suitable for CI / Team project to add that kind of layer complexity. I wonder what it would take to bring contribution to the CLI itself so that literally everyone benefits of it from the very moment you have `dotnet`
* works for global tool if `--global`
* works for local tool (manifest) if `--local`
* install should be seem less if already installed and just update
* it should support something like `--all` if no name provided

**Comment by SimonCropp** [comment]
i would also like to see an optional parameter that, before doing the update, would close any tool that is currently running

**Comment by adamralph** [comment]
I'd like to just _know_ which tools are outdated first, before deciding to take any action. Is that possible?

**Comment by tebeco** [comment]
> i would also like to see an optional parameter that, before doing the update, would close any tool that is currently running

Look like you should create another issue

**Comment by steveoams** [comment]
i use this on my linux boxes
```bash
dotnet tool list -g | awk '{ print $1 }' | tail +3 | xargs -I % sh -c 'dotnet tool update -g %;'
```

**Comment by tebeco** [comment]
It looks more and more obvious that native support is very much welcomed with all custom script over and over :D
https://github.com/dotnet/sdk/issues/10130#issuecomment-645593134

**Comment by alexanderkyte** [comment]
Would love to see movement on this. Without it, any documentation for how to use dotnet has to include OS-dependent steps around upgrading.

**Comment by petersladek** [comment]
I am totally puzzled why this haven't been implemented yet...

**Comment by maxkoshevoi** [comment]
Great feature! Does this issue accepts PRs, or is it not approved yet?

**Comment by tebeco** [comment]
I’m tempted to think that it will not be implemented if it’s not submitted from the community

**Comment by tebeco** [comment]
hello @KathleenDollard I just happen to see that @wli3 will likely not work on this feature anymore.

#3115 clearly state `DotNetCliToolReference` is dead, which is fine for me.
But we'd love to have a way to get a user experience similary to that, especially when it comes to updating the tooling version.

As we can see from the thread, no one really want a manual Json Parsing + a Loop over tool to force the update.
On top of that, it would be `shell` specific and not XPlat, which make more sense to get that from the CLI itself

**Comment by tebeco** [comment]
yes, but that's good only from github user point of view, which is not what the full dotnet echo system uses.

you probably still want `dotnet tool update --all` anyway to run that locally for example

**Comment by ofcoursedude** [comment]
Any news here?

**Comment by eduarddejong** [comment]
I was just looking for this exact same thing too ...

**Comment by kapsiR** [comment]
> I am considering to write myself a tool that uses the techniques shown above, but also uses Nuget to determine whether a tool actually is out of date. You might have noticed that `dotnet tool update` always re-installs (even if the the tool in question is up-to-date)
> 
> But I still feel that this functionality should be built-in! Including a `--outdated` option.

[I've created a script](https://gist.github.com/kapsiR/e7064babbef8dc4ac84a627717d54e5a), that checks NuGet before it tries to update anything:
```ps1
foreach ($toolInfoRow in $(dotnet tool list -g | Select-Object -Skip 2)) 
{
    $toolInfo = $toolInfoRow.Split(" ", [StringSplitOptions]::RemoveEmptyEntries)
    $toolName = $toolInfo[0]
    $toolVersion = $toolInfo[1].Trim()

    # Fetch version from NuGet
    $nugetInfo = (dotnet tool search --take 1 $toolName | Select-Object -Skip 2)
    $nugetVersion = $nugetInfo.Split(" ", [StringSplitOptions]::RemoveEmptyEntries)[1].Trim()

    if ($nugetVersion -ne $toolVersion)
    {
        Write-Host "dotnet tool update -g $toolName"
        dotnet tool update -g $toolName
    }
    else
    {
        Write-Host "Skip $toolName (no updates available)"
    }
}
```

But yes, I'd prefer a built-in solution too!

**Comment by silverf1re** [comment]
going on year 4 of this request for something pretty fundamental....

**Comment by PhilParisot** [comment]
Any updates on this?

**Comment by abelbraaksma** [comment]
@vilinski your "update all tools" script seems to have gone, or moved. The wayback machine doesn't have a copy. Do you happen to still have the `fsx` script somewhere? Would be awesome to keep it around ;).

See: https://github.com/dotnet/sdk/issues/10130#issuecomment-645021700

**Comment by abelbraaksma** [comment]
@wli3 what's the status? Still in the backlog? Can it be prioritized?

Re your comment: https://github.com/dotnet/sdk/issues/10130#issuecomment-569566206

**Comment by baronfel** [comment]
@abelbraaksma Wil and Kathleen don't work on the CLI anymore.  I've labeled this issue appropriately to fit our current scheme and we'll take a look. We've done some core tools enhancements for 8.0.100, but this wasn't part of that batch.

**Comment by vilinski** [comment]
@abelbraaksma no, it's still here on place
here is a full content of it:

<details>
  <summary>Click for see it</summary>

```
open System
open System.Diagnostics

let split (separator : char) (s : string) =
    s.Split(separator, StringSplitOptions.RemoveEmptyEntries)
let lines = split '\n'
let words = split ' '

let dotnet args =
    printfn "dotnet %s" args
    use p = new Process(
                StartInfo =
                    ProcessStartInfo(
                                FileName = "dotnet",
                                Arguments = args,
                                RedirectStandardOutput = true,
                                UseShellExecute = false)
                                )
    p.Start() |> ignore
    p.StandardOutput.ReadToEnd()

let parse output =
    output
    |> lines
    |> Array.skipWhile (fun s -> s.StartsWith "---" |> not)
    |> Array.skip 1
    |> Array.map (words >> Array.head)

let update tool =
    sprintf "tool update -g %s" tool
    |> dotnet
    |> printfn "%s"

"tool list -g"
|> dotnet
|> parse
|> Seq.iter update
```

</details>

**Comment by ahmet-cetinkaya** [comment]
You can add the following function to your Powershell `$Profile` file.
```powershell
function dotnet-tools-update {
    param (
        [switch]$global
    )

    try {
        # List dotnet tools
        if ($global) {
            $tools = dotnet tool list --global | Select-String "^\S+" | ForEach-Object { $_.Matches[0].Value }
        } else {
            $tools = dotnet tool list | Select-String "^\S+" | ForEach-Object { $_.Matches[0].Value }
        }

        if ($tools) {
            Write-Host "Updating..."
            foreach ($tool in $tools) {
                # Update dotnet tools
                try {
                    if ($global) {
                        dotnet tool update -g $tool -v diag
                    } else {
                        dotnet tool update $tool -v diag
                    }
                }
                catch {
                    Write-Host "Failed to update $($tool): $_"
                }
            }
            Write-Host "Update completed."
        }
        else {
            Write-Host "No dotnet tools to update found."
        }
    }
    catch {
        Write-Host "An error occurred: $_"
    }
}
```

**Comment by danmoseley** [comment]
Given the number of thumbs ups I'm surprised this hasn't attracted a PR 🙂

**Comment by ceztko** [comment]
I think that one approach that hasn't been properly suggested (@tebeco hinted about it, but doesn't mention it explicitly) is actually copying the semantics of npm [`package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json), where you can use semantic versioning [wildcards](https://stackoverflow.com/a/25861938/213871), and then a separate [`package-lock.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json) is created with the actual versions that will be used. In this way, you don't need an `--all` switch for the update command: the update can be granular as much as the user really want, and the command touches a `dotnet-tools-lock.json`, not `dotnet-tools.json`. Unfortunately this approach would be breaking, unless new commands with the new semantics are introduced and the older ones that modify `dotnet-tools.json` directly are deprecated.

**Comment by tebeco** [comment]
good things that the tool manifest is already versioned so that breaking change would only be OptIn then

**Comment by ceztko** [comment]
> good things that the tool manifest is already versioned so that breaking change would only be OptIn then

Correct. Consider mine was just a suggestion and I have no idea what direction MS will take. The only comment I can make is that having an `--all` switch in `dotnet tool update` doesn't look that big improvement and that npm `package.json` approach looks like a more elegant (and sophisticated) solution.

**Comment by marcpopMSFT** [comment]
Marking complete in 8.0.4xx
