### ISSUE TITLE
Clean up setting DOTNET_SKIP_FIRST_TIME_EXPERIENCE in script

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#10195]
after https://github.com/dotnet/cli/issues/10364 this flag is no longer honored. We should remove it in our build script across CLI, SDK, toolset, core-sdk

**Comment by bruno-garcia** [comment]
> There are a couple of instances in dotnet/sdk, dotnet/toolset and core-sdk for us to clean up.

`dotnet/toolset` seems to have joined this monorepo and `core-sdk` is not installer. I opened two PRs to cover those (see above). 👍
