### ISSUE TITLE
[dotnet-cache] cache command should respect PackageTargetFallback element

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1022]
Repro: https://github.com/JunTaoLuo/DotnetCache/tree/c4d1413da5a8cc512184f701f2b9284485d2e203/Fallback

Without respecting this element, during dotnet cache, the following error will be seen at restore:
```
C:\Users\johluo.REDMOND\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005448\NuGet.targets(97,5): error : Package Microsoft.AspNet.WebApi.Client 5.2.2 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNet.WebApi.Client 5.2.2 supports: [C:\Users\johluo.REDMOND\AppData\Local\Temp\kz4jgjn1.iz4\Microsoft.AspNetCore.Mvc.WebApiCompatShim_1.2.0-preview1-24008\Package.csproj]
C:\Users\johluo.REDMOND\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005448\NuGet.targets(97,5): error :   - net45 (.NETFramework,Version=v4.5) [C:\Users\johluo.REDMOND\AppData\Local\Temp\kz4jgjn1.iz4\Microsoft.AspNetCore.Mvc.WebApiCompatShim_1.2.0-preview1-24008\Package.csproj]
C:\Users\johluo.REDMOND\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005448\NuGet.targets(97,5): error :   - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81) [C:\Users\johluo.REDMOND\AppData\Local\Temp\kz4jgjn1.iz4\Microsoft.AspNetCore.Mvc.WebApiCompatShim_1.2.0-preview1-24008\Package.csproj]
C:\Users\johluo.REDMOND\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005448\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v2.0. 

```

cc @eerhardt

**Comment by JunTaoLuo** [comment]
Any ETA on this @eerhardt ?

**Comment by ramarag** [comment]
i am looking into this, there are some crossgen issues will reply when i learn more

**Comment by ramarag** [comment]
The crossgen issue i am hitting is as follows:

```
E:\temp\cache\packages\runtime.win7-x64.microsoft.netcore.app\2.0.0-beta-001776-00\tools\crossgen.exe -readytorun -in E:\temp\cache\packages\microsoft.net.http\2.2.22\lib\portable-net40+sl4+win8+wp71+wpa81\System.Net.Http.Primitives.dll -out E:\temp\cache\usedir\Microsoft.AspNetCore.Mvc.WebApiCompatShim_1.2.0-preview1-24008\runtimopt\System.Net.Http.Primitives.dll -jitpath E:\temp\cache\packages\runtime.win7-x64.microsoft.netcore.app\2.0.0-beta-001776-00\runtimes\win7-x64\native\clrjit.dll -platform_assemblies_paths E:\temp\cache\usedir\Microsoft.AspNetCore.Mvc.WebApiCompatShim_1.2.0-preview1-24008\runtimeref;E:\temp\cache\usedir\Optimize\netcoreapp;
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0                                                                                                                                                                                                                                   Copyright (c) Microsoft Corporation.  All rights reserved.
Error: Could not load file or assembly 'System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Error compiling E:\temp\cache\packages\microsoft.net.http\2.2.22\lib\portable-net40+sl4+win8+wp71+wpa81\System.Net.Http.Primitives.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
Error: compilation failed for "E:\temp\cache\packages\microsoft.net.http\2.2.22\lib\portable-net40+sl4+win8+wp71+wpa81\System.Net.Http.Primitives.dll" (0x80131621)
```

@weshaggard System.Net.Http.Primitives.dll listed above is PCL correct ? How are we expecting the PCL libs to get their runtime closure ? like the one from above: ```System.Net, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes```

cc @gkhanna79

**Comment by weshaggard** [comment]
2 questions

1. Any idea why Microsoft.NET.Http is part of this cache? We should be using System.Net.Http.
2. For older PCL profiles we don't currently have all the shims for those. This is actually the first request I've seen for them. We planning to add them though.

**Comment by ramarag** [comment]
It was brought in as a transitive closure of Microsoft.AspNetCore.Mvc.WebApiCompatShim/1.2.0-preview1-24137

```

      "Microsoft.AspNetCore.Mvc.WebApiCompatShim/1.2.0-preview1-24137": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNet.WebApi.Client": "5.2.2",
          "Microsoft.AspNetCore.Mvc.Core": "1.2.0-preview1-24137",
          "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.2.0-preview1-24137",
          "Microsoft.AspNetCore.WebUtilities": "1.2.0-preview1-24137",
          "NETStandard.Library": "1.6.1",
          "System.Runtime.Serialization.Xml": "4.3.0",
          "System.Xml.XmlSerializer": "4.3.0"
        },
...
".NETCoreApp,Version=v2.0": {
      "Microsoft.AspNet.WebApi.Client/5.2.2": {
        "type": "package",
        "dependencies": {
          "Microsoft.Net.Http": "2.2.22",
          "Newtonsoft.Json": "6.0.4"
        },
```

**Comment by gkhanna79** [comment]
@weshaggard From what @ramarag and @eerhardt described in an offline discussion, this is happening when compiling PCLs that are packaged in a nuget package but do not carry their dependencies, either within the same package or in a dependent package.

What is our story for consuming PCL/Desktop artifacts for 2.0?

**Comment by gkhanna79** [comment]
@JunTaoLuo Is this PCL expected to be part of the Antares/ASP.NET cache? If so, was this compiled before this _cache_ feature?

**Comment by weshaggard** [comment]
I don't know how this ever worked on .NET Core, as we didn't ever have a System.Net shim that would resolve that dependency.  Also in general we discourage usage of Microsoft.Net.Http package for core and instead folks should use System.Net.Http.

That aside we do plan on having a number of these shims in .NET Core 2.0, in fact they were added with https://github.com/dotnet/corefx/pull/17620, but I wouldn't rely on that we should definitely question whether or not Microsoft.Net.Http should be in the Asp.Net package cache when we don't want folks using it.

**Comment by gkhanna79** [comment]
Thanks @weshaggard. 

> I don't know how this ever worked on .NET Core, as we didn't ever have a System.Net shim that would resolve that dependency

@JunTaoLuo An app using such artifacts will only work as long as they use API in such components that do not rely on the missing dependencies. Thus, during JIT time, such an app _may_ work.

However, for crossgen, we need to have complete dependencies in place before crossgen can be attempted as it is a precompilation of the entire assembly and not specific methods.

**Comment by JunTaoLuo** [comment]
We have included M.A.Mvc.WebApiCompatShim when we built our package cache previously I'll look into how it was built and share what I find.

**Comment by JunTaoLuo** [comment]
We used to build this package in our package cache. We cross-gen our dll but not the PCL dependency. We had a list of explicit exclusions for the dlls of the PCL dependencies. I'm wondering if there should be a feature for this or maybe even default to skip cross-gen for PCL dependencies.

Note that I'm no longer blocked on this issue since we decided to not ship this package anymore.
