### ISSUE TITLE
Intermediate app config file runs in to long path issues on Windows

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#1028]
The file path for the intermediate app.config file is `<_GenerateBindingRedirectsIntermediateAppConfig>$(IntermediateOutputPath)$(MSBuildProjectFile).$(TargetFileName).config</_GenerateBindingRedirectsIntermediateAppConfig>` which ends up looking like `OrgName.ProductName.ProjectName.FeatureName.Test.csproj.OrgName.ProductName.ProjectName.FeatureName.Test.dll.config

which makes it easy for it to run in to long path issues on Windows. The CLI's SDK creates the file just fine, but VS 2017 had issues creating the file. Once created, removing the file (via `git clean` or `Remove-Item`) does not remove the file because it's too long.

**Comment by rainersigwald** [comment]
This could be changed for just the SDK, but the best place to fix it would be in MSBuild's common targets, where this is tracked by https://github.com/Microsoft/msbuild/issues/1786.

**Comment by pranavkm** [comment]
👍 I'll close this since it's already being tracked
