### ISSUE TITLE
Implement an option for restore/build/publish commands that disable build servers.

### ISSUE THREAD

**Issue by peterhuene** [dotnet/sdk#10288]
## Steps to reproduce

See discussion on https://github.com/dotnet/cli/issues/9481.

1) `dotnet new console`
2) `dotnet build`

## Expected  behavior

There should be an option to `dotnet build` (and other building commands) to disable the use of the various build servers (Roslyn, MSBuild node reuse, Razor).

## Actual behavior

Users have to pass a plethora of undiscoverable properties and options to fully disable the use of the build servers, which might be helpful for CI scenarios.

## Environment data

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by matkoch** [comment]
@peterhuene what's the status of this?

**Comment by peterhuene** [comment]
Hi @matkoch.  I left Microsoft over a year ago, so I haven't worked on this at all.

@dsplaisted might know if this is being tracked at all (I'm guessing not).

**Comment by matkoch** [comment]
@dsplaisted any news?

**Comment by dsplaisted** [comment]
Looks like this would be pretty easy to do.  From the linked issue, here's what we'd need to set:

```
Use -p:UseRazorBuildServer=false to disable the Razor (rzc) server.

Use -p:UseSharedCompilation=false to disable the Roslyn (vbcscompiler) server.

For MSBuild, pass /nodeReuse:false on the command line to disable node re-use.
```

**Comment by matkoch** [comment]
@dsplaisted that's what we already discussed in https://github.com/dotnet/sdk/issues/9499#issuecomment-397044453 ... I'm asking when this could be addressed. It's quite a while already, and it's vital for CI use cases.

**Comment by matkoch** [comment]
`pretty easy to do` => hasn't happened in almost 3 years :)

**Comment by dsplaisted** [comment]
I've marked this for the team to review, so we will be evaluating the priority soon.

In the meantime, you should be able to get the same result by combining the three options: `-p:UseRazorBuildServer=false -p:UseSharedCompilation=false /nodeReuse:false`
