### ISSUE TITLE
Migrating a VS 2015 solution to VS 2017 does not stick

### ISSUE THREAD

**Issue by weshaggard** [dotnet/sdk#1030]
@andre-artus commented on [Wed Mar 22 2017](https://github.com/dotnet/coreclr/issues/10389)

I have migrated a solution with .NET Core projects from 2015 to 2017, seems to work. Can build, run, publish, all the good things. 

But, when I close the solution and try to reopen it I get a "needs migration" message on the projects and the projects do not load. When this happened at first I thought maybe something went wrong so I reverted to the old state and did everything again. I'm still having the issue. I cannot work like this constantly reverting and re-migrating.

**Comment by livarcocc** [comment]
@333fred Should this go to project-system?

**Comment by 333fred** [comment]
This issue was moved to dotnet/roslyn-project-system#1824
