### ISSUE TITLE
Add solution folder argument to dotnet-sln show-folders  (show solution folders)

### ISSUE THREAD

**Issue by LightVolk** [dotnet/sdk#10308]
Feature request:

If possible, can this fucntionality be added: list of solution folders?
Use case:

1. List of solution folders (dotnet sln show folders)
2. Add new project under on of this solution folder.  (dotnet sln add project)

It must be related to PR: [https://github.com/dotnet/cli/pull/11000](url)

**Comment by glihm** [comment]
Do agree with that... for those working on linux, the FS is not showing any solution folders. It would be very helpful!
