### ISSUE TITLE
Restore doesn't set configuration for P2P references

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#1034]
**Problem description**

I have a ProjectReference to a .csproj with a specific configuration (specified by setting `<SetConfiguration>Configuration=config</SetConfiguration>` under the ProjectReference element). When the referenced project has already been restored in the correct configuration, I can build the consuming project correctly (using the specified configuration of the child project). However, restoring the consuming project tries to restore the child project with the default configuration. This is problematic when the dependencies differ between configurations.

**Repro**
- [restore_configuration.tar.gz](https://github.com/dotnet/sdk/files/862974/restore_configuration.tar.gz)
- `cd app`
- `dotnet restore`

**Expected behavior**
Restoring `app.csproj` should cause Newtonsoft.Json to be restored for `lib.csproj`.

**Actual behavior**
The configuration doesn't get set on the P2P reference during restore (even though it does during build), causing the package to be missing.

**Environment info**

`dotnet --info`:
```
.NET Command Line Tools (2.0.0-preview1-005448)

Product Information:
 Version:            2.0.0-preview1-005448
 Commit SHA-1 hash:  f8c3c4a030

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/2.0.0-preview1-005448/
```

**Comment by sbomer** [comment]
It looks like the restore targets already try to set the child project configuration. For example:

```
 <Target Name="_GenerateRestoreProjectPathWalk" DependsOnTargets="_GenerateRestoreProjectPathItems;_GetRestoreTargetFrameworksAsItems" Returns="@(_RestoreProjectPathItems)" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Walk project references  -->
    <MSBuild Projects="@(_CurrentRestoreProjectPathItems)" Targets="_GenerateRestoreProjectPathWalk" ContinueOnError="$(RestoreContinueOnError)" Properties="TargetFramework=%(_RestoreTargetFrameworkItems.Identity);                   %(_MSBuildProjectReferenceExistent.SetConfiguration);                   %(_MSBuildProjectReferenceExistent.SetPlatform);                   $(_GenerateRestoreGraphProjectEntryInputProperties)" RemoveProperties="%(_MSBuildProjectReferenceExistent.GlobalPropertiesToRemove)">
      <Output TaskParameter="TargetOutputs" ItemName="_GenerateRestoreProjectPathWalkOutputs" />
    </MSBuild>
    <!-- Include the current project in the result -->
    <ItemGroup>
      <_GenerateRestoreProjectPathWalkOutputs Include="$(MSBuildProjectFullPath)" />
    </ItemGroup>
    <!-- Remove duplicates -->
    <RemoveDuplicates Inputs="@(_GenerateRestoreProjectPathWalkOutputs)">
      <Output TaskParameter="Filtered" ItemName="_RestoreProjectPathItems" />
    </RemoveDuplicates>
  </Target>
```

This sets the configuration to `%(_MSBuildProjectReferenceExistent.SetConfiguration);`.

The problem appears to be that the `AssignProjectConfiguration` target doesn't run during restore, so `@(ProjectReferenceWithConfiguration)` doesn't get set, and thus neither do `@(_MSBuildProjectReference)` or `@(_MSBuildProjectReferenceExistent)`.

I think the solution is to have `AssignProjectConfiguration` run as part of the restore target.

**Comment by livarcocc** [comment]
The restore target is defined by NuGet, therefore I am moving this bug there.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4873

**Comment by sbomer** [comment]
Thanks!
