### ISSUE TITLE
dotnet publish should default to release mode

### ISSUE THREAD

**Issue by benaadams** [dotnet/sdk#10357]
Currently it defaults to debug (bad for performance of deployed sites, libraries put on nuget, and apps)

While this is obvious when using `dotnet publish` without parameters as it puts it in a Debug folder; it is not obvious when using an output setting as it is put in the output directory without an obvious `Debug` moniker

**Comment by benaadams** [comment]
Can this be done for 5.0?

**Comment by benaadams** [comment]
>  but happy to explore this for 5.

@nguerrera  @KathleenDollard any news?

**Comment by forki** [comment]
Thanks for still pushing them to do the right thing Ben

**Comment by benaadams** [comment]
Recent example of someone having performance issues from not publishing in release mode https://github.com/dotnet/sdk/issues/12834

**Comment by nguerrera** [comment]
@benaadams Sorry, I don’t work on this project or .NET anymore. It’s been five months since I’ve left so I don’t know if there’s been any development on this.

**Comment by richlander** [comment]
We're going to take another (and hopefully final) run at resolving this for .NET 6.0.

**Comment by forki** [comment]
Lol

**Comment by tmds** [comment]
```xml
<Project>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
  </PropertyGroup>
</Project>
```

I guess there is no way to set this conditionally based on the target because there is no property that describes the targets that are being built/requested?

**Comment by EskeRahn** [comment]
A little late to the party, but one could say that the issue here is semantics causing confusion.
With "publish" one sort of intuitively expect that it is actually about publishing. And not about producing code for debugging.

But taking a step backwards this also should match msbuild.

Perhaps the clean way would be to always have a default release path as well as the default debug path, and to define two _new_ keywords for compiling to debug and to release. And have "publish" deprecated but mirroring the debug for backwards compatibility. Perhaps simply something like todebug and torelease?
And if people have multiple configuration profiles obviously allow us to pick a specific one by name

**Comment by richlander** [comment]
FYI: https://github.com/dotnet/sdk/issues/23551

**Comment by dsplaisted** [comment]
We think that we can do this for projects that target .NET 8 or higher, by setting the `PublishRelease` property to true (if not already set) in the .NET SDK targets if the project targets .NET 8 or higher.

**Comment by winstxnhdw** [comment]
> This is not as simple as it might seem.
> 
> `dotnet publish` doesn't explicitly set the configuration to Debug. It just does what msbuild /t:Publish does without a /p:Configuration=X argument. That is not necessarily debug: try it with a Directory.Build.props like this:
> 
> ```
> <Project>
>   <PropertyGroup>
>     <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
>   </PropertyGroup>
> </Project>
> ```
> 
> Further note that configurations can be arbitrarily customized. There might not even be one called Release in the project. Forcing /p:Configuration=Release by default is most definitely a breaking change. It might not even work. Or it might override to a less efficient configuration than a custom configuration that is not named Release and made to be the default in project code like above. And even when it works, it will certainly break cases where people are relying on getting Debug in the case where they have not passed an explicit configuration.
> 
> Microsoft.NET.Sdk chooses Debug by default here:
> 
> https://github.com/dotnet/sdk/blob/ef7932d094d8cf6bfd567e3de0f852a3abda9fe0/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L23
> 
> This applies to more than publish, and like so many other things in those props, it maps to what got spelled out in File -> New in classic projects. Breaking with that ancient tradition will likely have other unintended consequences.

Should be

```xml
<Project>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' Debug">Release</Configuration>
  </PropertyGroup>
</Project>
```

dotnet DOES set configuration to "Debug" on default.

**Comment by dsplaisted** [comment]
This is done and can be closed, right @nagilson?

**Comment by nagilson** [comment]
That's correct. We've changed the default to `Release` for 8.0+ TFMS: https://github.com/dotnet/sdk/pull/29155 ( as well as for `pack`.)

Was waiting for the release so there were no more 🥅  ;)
