### ISSUE TITLE
ComposeCache tests should target netcoreapp2.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1036]
All of our [ComposeCache tests](https://github.com/dotnet/sdk/blob/master/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToCacheAProjectWithDependencies.cs) all use netcoreapp1.0, but that TFM isn't supported by the cache feature, since the 1.x host doesn't know how to load assemblies from the cache.

We should move all our tests to test the product like our customers are going to use it, which means targeting netcoreapp2.0.

**Comment by ramarag** [comment]
Also ensure end to end feature runs properly by removing the TODOS in : 
https://github.com/dotnet/sdk/blob/517b4d57c3e08cad4a92a2d87bb5e1aadefc1c46/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs#L153
https://github.com/dotnet/sdk/blob/517b4d57c3e08cad4a92a2d87bb5e1aadefc1c46/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs#L192

**Comment by ramarag** [comment]
I have upgraded the store tests as part of https://github.com/dotnet/sdk/pull/1297

Outstanding items
1. please follow up on https://github.com/dotnet/sdk/pull/1297#discussion_r120199823
2. Complete the TODOS in
a. https://github.com/dotnet/sdk/blob/34537c97d69a4bab6c817ad5390a8adeb7e79b23/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs#L161
b. https://github.com/dotnet/sdk/blob/34537c97d69a4bab6c817ad5390a8adeb7e79b23/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs#L200

**Comment by eerhardt** [comment]
This work is now complete with #1363.
