### ISSUE TITLE
Feature request: Add ability to build solution filter

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/sdk#10409]
In VS2019 we are able to create solution filters of file type *.slnf. It would be great if we could build these file types at the command line (i.e. `dotnet build [solution].slnf`).

I can see this as beneficial in CI workflows where only the selected projects need to be built. I could just use SLN files, but then I would ditch SLNF files as I don't want to maintain two solutions.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.700
 Commit:    c2ef055a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.700\

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

**Comment by GearedToWar** [comment]
I see that it now working.

\>dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015203
 Commit:    b1dcd32553

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015203\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

**Comment by ilelann** [comment]
This works indeed. What does not work though is to combine this with --no-dependencies flag. Idea would be to accept dependencies that are in the slnf, and skip others.

**Comment by MisinformedDNA** [comment]
I'm going to close this one, but feel free to create a new issue.

**Comment by voroninp** [comment]
Hm.. It looks like `dotnet restore` still restores projects which are filtered out.

**Comment by baronfel** [comment]
@voroninp can you raise a separate issue for that over on Nuget/Home? The nuget team  owns all of the restore behavior.
