### ISSUE TITLE
Dotnet restore doesnt stop when is interrupted by user

### ISSUE THREAD

**Issue by enricosada** [dotnet/sdk#1040]
repro

```
dotnet restore
^C
dotnet restore
```

expected:

first command start restore
the `CTRL-C` interrupt the restore, and give back control to prompt
second command start restore again (like first one was never done)

actual:

after interrupted, is like restore continue in background, is not possibile to stop it, mess with current command window.
and next `dotnet restore` need to wait for previous to finish.

note i tried to write hey after i interrupted the command, and control was back to prompt

![image](https://cloud.githubusercontent.com/assets/147243/24260719/162ff946-0ff5-11e7-932c-510f0a941a4d.png)

**Comment by enricosada** [comment]
I opened there because i think is not a dotnet/cli issue (all other command are ok).
So i think are the restore targets in sdk.

But i'll close and move, if there is a better repo (directly nuget/home ?).

**Comment by livarcocc** [comment]
Yes, I think we should start with Nuget/Home for this.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5064
