### ISSUE TITLE
Disabling first run welcome message?

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/sdk#10411]
Is there a good way to completely disable the first time user notice when installing a new version of the SDK? Looking at the code, it seems that it can only be done by creating the appropriate [`dotnetFirstTimeUseSentinel`](https://github.com/dotnet/cli/blob/143a75dcacfbcc3665d9bbfa54d14217ce3e0ab3/src/Microsoft.DotNet.Configurer/FirstTimeUseNoticeSentinel.cs#L13) file.

There should be an easier way to disable this, like setting an environment variable maybe. 
I work a lot with nightly builds of the sdk across multiple machines, so the message is a minor source of annoyance for me.

**Comment by MiYanni** [comment]
Is this a dup of https://github.com/dotnet/sdk/issues/3828? And is resolved by https://github.com/dotnet/cli/pull/13275?

**Comment by jetersen** [comment]
Solved by:

```
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
```

**Comment by nagilson** [comment]
Closing as the work has been done to fix this.
