### ISSUE TITLE
RemoveDepsFileConflicts errors when using .NET Core 2.0 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#1043]
Not sure if this is the right place but I get this when building a .NET Core 2.0 test in VS 2017

```
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: The "RemoveDepsFileConflicts" task failed unexpectedly.
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: File name: 'Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.RemoveDepsFileConflicts.Execute()
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: 
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: WRN: Assembly binding logging is turned OFF.
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: Note: There is some performance penalty associated with assembly bind failure logging.
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
3>C:\Users\dfowler\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25121-01\build\Microsoft.Packaging.Tools.targets(89,5): error MSB4018:
3>Done building project "Microsoft.AspNetCore.Server.KestrelTests.csproj" -- FAILED.
========== Build: 2 succeeded or up-to-date, 1 failed, 0 skipped ==========

```

/cc @ericstj @eerhardt

**Comment by eerhardt** [comment]
This error is the same as https://github.com/dotnet/standard/issues/197

They should be fixed by https://github.com/dotnet/sdk/issues/974

**Comment by kichalla** [comment]
@eerhardt Are there any workarounds?

cc @pranavkm @rynowak

**Comment by eerhardt** [comment]
Not any good workarounds that I know of... maybe @ericstj would know of some?

There may be a way to inject a Target in your build that ensures this assembly is loaded, but I haven't tried.

Another workaround is to use VS Code ;).

**Comment by ericstj** [comment]
Just copy the Microsoft.Extensions.DependencyModel.dll from the SDK folder into microsoft.packaging.tools.

EG:
```
copy F:\cli\sdk\2.0.0-preview1-005645\Sdks\Microsoft.NET.Sdk\tools\netcoreapp1.0\Microsoft.Extensions.DependencyModel.dll C:\Users\ericstj\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25115-01\build\
copy F:\cli\sdk\2.0.0-preview1-005645\Sdks\Microsoft.NET.Sdk\tools\net46\Microsoft.Extensions.DependencyModel.dll C:\Users\ericstj\.nuget\packages\microsoft.packaging.tools\1.0.0-beta-25115-01\build\desktop\
```

**Comment by kichalla** [comment]
Thanks! @ericstj It works for me.

**Comment by livarcocc** [comment]
@dsplaisted He is working on moving this tasks over to the SDK.

**Comment by LinqBeast** [comment]
I get passed this error with this solution, but now I get:

System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0

So, tried the same with this file, but now get:


Error	MSB4018	The "RemoveDepsFileConflicts" task failed unexpectedly.
System.FormatException: Unexpected character encountered, excepted '{' at line 0 position 0 path 
   at Microsoft.Extensions.DependencyModel.JsonTextReaderExtensions.CheckStartObject(JsonTextReader

**Comment by davidfowl** [comment]
@dsplaisted When is this getting fixed? I'm hitting it everyday, it's pretty disruptive. Yes, I know what the workaround is and I hate having to apply it to every new version of the SDK and package that I get.

**Comment by dsplaisted** [comment]
@davidfowl The PR is in progress here: https://github.com/dotnet/sdk/pull/1052

I expect to finish it up tonight and have it merged tomorrow.  After that the updated SDK will need to be inserted into the CLI and VS to make it easy to consume the fixed version.

**Comment by moozzyk** [comment]
This is very annoying. It happens to me literally every other build... https://developercommunity.visualstudio.com/content/problem/39252/random-removedepsfileconflicts-task-failed-unexpec.html

**Comment by eerhardt** [comment]
@ericstj made a fix for this in dotnet/standard yesterday.  It made its way to dotnet/core-setup this morning.  Once a new build of core-setup is out, using the new Microsoft.NETCore.App version should no longer run into this issue.

**Comment by davidfowl** [comment]
We just saved Microsoft millions of dollars in dev time 😄

**Comment by eerhardt** [comment]
Too bad we haven't had a dotnet/core-setup build in 2 days because of the OSX networking problem.

**Comment by ericstj** [comment]
ditto on corefx.

**Comment by livarcocc** [comment]
Build are passing again since yesterday. Eagerly waiting a core-setup build.

**Comment by livarcocc** [comment]
This should be fixed now. Re-activate if this still an issue.
