### ISSUE TITLE
PrepublishScript and CopyToPublishDirectory does not play well together?

### ISSUE THREAD

**Issue by schmitch** [dotnet/sdk#1044]
Actually we generate two files `bundled.min.css` and `site.min.js` via bundleconfig:
```
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>

  <ItemGroup>
    <Content Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

However when we do a `dotnet publish -o `pwd`/build` the files are missing.
However calling it a second time, they will actually be there. Is there a missing piece? (we use `Project Sdk="Microsoft.NET.Sdk.Web"`) 

It looks like either that they are called in the wrong order or I miss something. (edit we migrated via VS2017 and with the old project.json it just worked?)

**Comment by dsplaisted** [comment]
See here for a workaround: https://github.com/aspnet/websdk/issues/114#issuecomment-280076533

We have a PR to fix this: https://github.com/aspnet/websdk/pull/159

Thanks!

**Comment by livarcocc** [comment]
This is being tracked in the websdk. Closing.
