### ISSUE TITLE
Unnecessary assets are getting put in the `dotnet cache` output folder

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1045]
## Steps to reproduce
Invoke `dotnet cache` on this project:

```
<Project Sdk="Microsoft.NET.Sdk">
   <ItemGroup>
     <PackageReference Include="NuGet.Common" Version="4.0.0" />
   </ItemGroup>
 </Project>
```

## Expected  behavior
Since `NuGet.Common` doesn't have any other references outside of the shared framework, it should be the only package in the cache.

## Actual behavior
On Windows I get:

![image](https://cloud.githubusercontent.com/assets/8291187/24307250/63e3b7a8-1091-11e7-82fa-b7d4aca41aa8.png)

in my cache.

On OSX I get:

![image](https://cloud.githubusercontent.com/assets/8291187/24307425/1732aac6-1092-11e7-8bc7-934033f48b47.png)

These `runtime` packages are unnecessary since they come from the shared framework. We should not be putting these packages/assets in the cache folder.

**Comment by ramarag** [comment]
Right now i am not doing dependency conflict resolution for unmanaged files as the managed resolution is itself kind of hacky see https://github.com/dotnet/sdk/blob/91ff2017b3ac427ea13f7f5f5ad66d93a7ddba82/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets#L255

There are at max going to be the 5 or 6 that ships with pre netstandard2.0  fx libraries on non-windows

It should get fixed when and if we do package level dependency conflict resolution in 
https://github.com/dotnet/sdk/issues/1023
