### ISSUE TITLE
The install scripts rely on a failure to download as a normal procedure

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/sdk#10450]
The install scripts rely on a failure to download as a normal procedure.

The 'primary' blob storage location is tried
    if the download fails
The 'legacy' blob storage location is tried

This can be confusing to users as they see an 'error' in a successful process.

**Proposal:**
1. Maintain a hint path table with presedential ordering
2. Perform a 'lookup' first before trying a download [retry]
3. If found, then download [retry]
4. if not found, error-out with all the paths attempted.

**Comment by donJoseLuis** [comment]
@bozturkMSFT please take a look, may be a dup of the 2nd attempt 404 issue.  in that case, let's preserve John's proposal.

**Comment by bozturkMSFT** [comment]
Tracked in https://github.com/dotnet/sdk/issues/10975.
Closing this one.
