### ISSUE TITLE
.NET Core SDK should generate appropriate RID graphs in an app's .deps.json file

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1046]
See https://github.com/dotnet/core-setup/issues/1846

In applications that run on the shared framework, the app will have native assets for all the runtimes that are necessary. For example, if you reference SQLite, you get the following in your publish directory:
![image](https://cloud.githubusercontent.com/assets/8291187/24316545/c8645ab8-10bc-11e7-9774-63c0de36a9a0.png)

However, the problem is the host only knows how to resolve these assets using the RID graph that is contained in the shared framework's .deps.json file. So if a new RID came along, like `LinuxEric`, and I tried to run an app using SQLite, the host wouldn't know that `LinuxEric` should map to the `linux` RID. Thus the asset wouldn't get selected and my app would fail.

Once the host is able to consume a RID graph from an app's .deps.json, the SDK should be generating the RID graph using any `runtime.json` files from referenced NuGet packages.  And maybe we should allow the actual app's .csproj to have its own `runtime.json` file that gets merged in as well.  That way a developer could make their app work without needing a NuGet package with a `runtime.json`.

/cc @Petermarcu @gkhanna79 @ericstj @weshaggard

**Comment by gkhanna79** [comment]
See comment at https://github.com/dotnet/core-setup/issues/1846#issuecomment-289166580

**Comment by natemcmaster** [comment]
@nguerrera @dsplaisted what do you think about doing this for 3.0? I ran across a new scenario in which this would be useful: self-contained apps that do dynamic assembly loading of components with rid-specific dependencies. See https://github.com/dotnet/designs/pull/47 and https://github.com/natemcmaster/DotNetCorePlugins/issues/14
