### ISSUE TITLE
0 byte deps file created in some cases

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#1049]
I'm not sure what causes it but it happened when running tests over and over. At some point I get an error about not being able to parse a deps file and this happens:

![image](https://cloud.githubusercontent.com/assets/95136/24321205/32439bbe-1104-11e7-8846-13f483a1521c.png)

It might have something to do with https://github.com/dotnet/sdk/issues/1043

**Comment by nguerrera** [comment]
Assuming this has been fixed along with the fix for #1043. Re-open if you see it again.
