### ISSUE TITLE
dotnet build failed exit code

### ISSUE THREAD

**Issue by ivanparvaresh** [dotnet/sdk#10515]
## Steps to reproduce
When `dotnet build` fails with error, it doesn't return `-1` exit code and also it prints out Build succeeded`.
in previous  version when one of projects failed to build all build process was failing. 

## Expected  behavior
When one or more project fails to build, it should return `-1` exit code.

## Actual behavior
When one or more project fails to build, it returns success exit code.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mlockett42** [comment]
I have just been having the same prob building from the official Microsoft docker images

mcr.microsoft.com/dotnet/core/sdk:3.0-bionic

Fails in the same way as @ivanparvaresh mentions. Specifically I am trying to use -warnaserror to raise and error when code has warnings in a bitbucket pipeline

Pulling the docker image mcr.microsoft.com/dotnet/core/sdk:3.1-bionic fixes the problem. Appears solved in Dotnet Core 3.1

**Comment by fabasoad** [comment]
I have the same behavior. Reproduces on MacOS and Ubuntu.
1. Ubuntu: `dotnet --info`
```bash
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /opt/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/sdk/5.0.100-preview.6.20318.15/

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  5.0.100-preview.6.20318.15 [/opt/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [/opt/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [/opt/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
2. MacOS: `dotnet --info`
```bash
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /Users/runner/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/sdk/5.0.100-preview.6.20318.15/

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  5.0.100-preview.6.20318.15 [/Users/runner/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [/Users/runner/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [/Users/runner/hostedtoolcache/dncs/5.0.100-preview.6.20318.15/x64/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
More details here:
https://github.com/fabasoad/ghacu/actions/runs/164599396

> In link above step "Build" wasn't failed (but had to).

**Comment by am11** [comment]
@fabasoad, this is because `build.ps1` is not exiting with the return value of `dotnet build` command, so the execution environment is unaware of the failure. Try setting `$ErrorActionPreference = "Stop"` or returning the exit code of dotnet command (`$?`) explicitlyy.

**Comment by fabasoad** [comment]
@am11 you're right. Thanks for pointing me. I ran `dotnet build` directly without `build.ps1` and exit code works as expected. So need to change `build.ps1` script properly.

**Comment by jepperaskdk** [comment]
Should this be closed? When are negative exit-codes expected, and is there any evidence that `dotnet build` returned a wrong exit-code?
