### ISSUE TITLE
Support for creating a mini publish on build

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/sdk#1054]
When running Visual Studio projects against the local IIS web server, the users web application (ie. dotnet.exe) runs under the app pool identity account of the w3wp.exe process, not the visual studio user. This means the application does not have access to packages in the users .nuget folder.  To work around this I added an after build target which gathers the list of nuget packages and copies them to the output folder – see PR https://github.com/aspnet/websdk/pull/168

The change (shown below) leverages the RunResolvePublishAssemblies to get the set of Nuget packager (with metadata on how to copy them) and is conditioned on property which is (currently) only set when building in VS and the user has chosen to run against the IIS web server. This seems to work fine (clean could use some optimization…) but I have a couple of concerns:

1.	This is fragile in that it depends on a target which presumably may change in the future
2.	The ability to create a mini-deployment like this seems like it should be in the core sdk targets rather than as a web only feature.  I would have more confidence that it wouldn’t be broken if this was natively supported.  

  
  <Target Name="CopyAssembliesToOutput" AfterTargets="Build" DependsOnTargets="RunResolvePublishAssemblies" Condition="'$(CreateLocalDeployment)' == 'true'">
    <Copy SourceFiles="@(ResolvedAssembliesToPublish)" DestinationFiles="$(TargetDir)%(ResolvedAssembliesToPublish.DestinationSubPath)" SkipUnchangedFiles="true" />
  </Target>

  
  <Target Name="CleanCopiedAssemblies" AfterTargets="Clean" DependsOnTargets="RunResolvePublishAssemblies">
    <Delete Files="$(TargetDir)%(ResolvedAssembliesToPublish.DestinationSubPath)" ContinueOnError="true" />
  </Target>

**Comment by dasMulli** [comment]
There's also a built-in functionality to copy NuGet dlls into the output folder:
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

**Comment by livarcocc** [comment]
@BillHiebert re-activate this issue if CopyLocalLockFileAssemblies is not enough for you and let us know what else is missing.

I guess you can just set that in the Web SDK instead of having a special target.

**Comment by ericstj** [comment]
I just looked at this (as part of https://github.com/dotnet/sdk/issues/1103) and I agree with this assessment:  CopyLocalLockFileAssemblies should do the right thing.

**Comment by nguerrera** [comment]
I've run in to issues where I don't have the control I want over CopyLocalLockFileAssemblies vs publish, but I think that's adequately tracked by https://github.com/dotnet/sdk/issues/933
