### ISSUE TITLE
Deadlock on Linux build machine

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/sdk#10563]
## Description

I run within my Yocto build three `dotnet publish` commands roughly at the same time. Usually those finish within 10s of seconds, but since yesterday, the commands have not finished for several hours. This has not happened before.

## Expected  behavior

No deadlock. The build should finish as always

## Actual behavior

I'm now sitting on a little over 100 PIDs associated with the dotnet process (`ps -efL | grep dotnet`)
There are several groups of similar invocations:
- About 14 processes are `…/2.2.401/MSBuild.dll … /nodeReuse:true`. Given the environment data below, I have double-checked that this is not a typo. I only have two SDKs (2.2.402, 3.0.100), and the 2.2.401 SDK isn't present in my file system anymore.
- About 45 processes are `dotnet publish -c Release …`, about 15 for each of the three root publish commands
- About 33 processes are `dotnet exec …/3.0.100/MSBuild.dll … -target:Restore …` for two of the root publish commands.
- About 17 processes are `dotnet exec …/3.0.100/MSBuild.dll … -target:Publish …` for the other root publish command.

I have attached strace to all the PIDs simultaneously (-p … -p … -p …) and the result is this:
[the-trace.gz](https://github.com/dotnet/cli/files/3754358/the-trace.gz)

I can keep the build machine as-is for the next few days to run more tests as requested. The Azure DevOps build doesn't have a timeout.

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tragetaschen** [comment]
Once more today. This time with consistent 3.1.101 dotnet processes

**Comment by FatTigerWang** [comment]
This problem also occurs when I use the .NET 5 SDK. Note that this occurs during the automated compilation phase and seems to be a concurrent build problem. This is not a problem with the .NET 5 SDK, because I am on .NET Core 3. .x SDK also encountered this problem

command : `dotnet publish PROJECT_PATH --configuration Release -nowarn:CS1591 --output target`
output:
```txt
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
```

**Comment by FatTigerWang** [comment]
I made a repository to restore [this problem](https://github.com/FatTigerWang/dotnet-restore-deadlock-demo)

**Comment by FatTigerWang** [comment]
@dsplaisted

**Comment by FatTigerWang** [comment]
Through `ps -aux | grep restore` I found that it seems to be stuck at this step

`dotnet exec /usr/share/dotnet/sdk/5.0.302/MSBuild.dll -maxcpucount -verbosity:m -nologo -target:Restore RestoreTest/RestoreTest.csproj -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr /share/dotnet/sdk/5.0.302/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/5.0.302/dotnet.dll`

**Comment by dsplaisted** [comment]
@nkolev92 @zkat Are multiple concurrent restore operations on the same projects expected to work?

**Comment by zkat** [comment]
NuGet is not designed to have multiple concurrent restore operations on the same projects, no. It's designed to optimize for whole-solution restores and doesn't really have safeguards against this kind of thing.

**Comment by zivkan** [comment]
You can use `-p:RestoreRecursive=false`, which should mitigate the problem, unless your build scripts cause the same project to be restored more than once concurrently.  But this is going to be much slower than having a solution file with all your projects and just restoring that solution file instead, since all project references are going to be evaluated by nuget multiple times (once per process), rather than once per solution restore.

**Comment by marcpopMSFT** [comment]
Thanks for the repro.  This is not something that is supported today.  Building and even restoring the same project from different dotnet instances at the same time are going to collide in unexpected ways.
