### ISSUE TITLE
Microsoft.NET.publish.targets does not respect property PublishableProject

### ISSUE THREAD

**Issue by mariusGundersen** [dotnet/sdk#1059]
In [`Microsoft.Common.CurrentVersion.targets`](https://github.com/Microsoft/msbuild/blob/2634f05a660b14c64ae4e924d900dd200d5032e7/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4971) there is a `Publish` target that checks the property `PublishableProject` and determines if the current project should be published or not. Unfortunately [`Microsoft.NET.publish.targets`](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Publish.targets#L37) overrides this and does not check the property.

This means that there is no way to prevent a project from being published. Note that the NuGet targets have an [`IsPackable`](https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target) property that can be set in the project to prevent it from producing a nuget package. It would be great to either use the `PublishableProject` or `IsPublishable` to have the same control when publishing.

**Comment by eerhardt** [comment]
For completeness, can you give a concrete example of when you would want to set this property to false?

**Comment by mariusGundersen** [comment]
What I wish to be able to do is run 

```
dotnet publish mySolution.sln
```

And get only the projects that I have marked as publishable to be published. This way the build script can be very simple, since it can be roughly this:

```
dotnet clean mySolution.sln
dotnet restore mySolution.sln
dotnet build mySolution.sln
dotnet pack mySolution.sln
dotnet publish mySolution.sln
dotnet nuget push **/bin/**/*.nupkg
myCustomDeploy **/bin/**/publish
```

This is obviously a simplification, but not by much. Having the publishability be declaratively stated in the project rather than specified in the build script makes the build script simpler.

**Comment by eerhardt** [comment]
Sounds good to me. Thanks for the explanation.

**Comment by livarcocc** [comment]
Closing this issue since we took a PR to fix it already.

Thanks for the PR again @mariusGundersen

**Comment by StefanBertels** [comment]
I have a solution with a class library project having `TargetFrameworks` (multiple) defined. If I call `dotnet publish` (without any parameters) for my solution (containing e.g. a netcoreapp3.1 console app and this library project) it fails even if I define `<IsPublishable>false</IsPublishable>` in the class library's csproj.

Everything else seems to work. If I change `TargetFrameworks` to `TargetFramework` the error is gone -- therefore my guess is that `IsPublishable` property gets checked too late.

My `dotnet.exe --version` shows 3.1.100.
