### ISSUE TITLE
How to get referenced FrameworkReference of a .NET Core classlib (dll) programmatically?

### ISSUE THREAD

**Issue by eriawan** [dotnet/sdk#10605]
Hi folks,

I apologize if this question has been asked before.

## Background

Since .NET Core 3.0, we could have multiple FrameworkReference in the project file (vbproj, csproj, fsproj). For example:

https://github.com/eriawan/netcore-fsharp-sample/blob/2535996eb50fa9208cc6ceb1888cfeb0b47ac8e7/src/netcore3.1/FSWindowsDesktop/FSWindowsDesktop.fsproj#L1-L11

This will render the project in VS 2019 16.3.x/16.4.x as this:

![image](https://user-images.githubusercontent.com/8773147/73535971-6d035580-4457-11ea-8e04-cb1ebdeab750.png)

## Question

Ok, is there a way to deduce or get the list of referenced FrameworkReferences of a class library programmatically?
Because I need this to analyze and calculate the references in terms of FrameworkReference, instead of referenced assembly.

**Comment by nguerrera** [comment]
We need more context on what kind of program you are writing. Do you want the app to resolve its own references at runtime or are you passively analyzing another app?

**Comment by eriawan** [comment]
Both of the capabilities would be nice to have, but I think having the capability to analyze loaded assembly would be better.
Because I need to analyze loaded DLLs for referenced FrameworkReference(s).

**Comment by eriawan** [comment]
@nguerrera 
Is there any updates on reviewing this issue? Basically I want to my app to analyze and resolve its own references at runtime.

Please confirm.

**Comment by nguerrera** [comment]
I'm sorry that I didn't see your response all those months ago. I no longer work on this project so maybe someone else on the team can help you. cc @dsplaisted

**Comment by dsplaisted** [comment]
If you're just looking at a .dll, then this information won't be present.  If you create a NuGet package for a library, the framework references should be listed in the NuGet package (in its .nuspec).

If you are looking at an app, then you can look at the runtimeconfig.json file.  However, there are multiple frameworks referenced, then it will omit the reference to `Microsoft.NETCore.App`: https://github.com/dotnet/sdk/blob/dfd68fcb2fc7aaa8681dd3f160f08a465ee53218/src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs#L206-L215

**Comment by eriawan** [comment]
@dsplaisted 

Great! Thanks a lot!
This is what I'm looking for! 🙂 
I'm going to close this 👍
