### ISSUE TITLE
Publish test PublishItemsOutputGroupTests.GroupPopulatedCorrectlyWithSingleFile was disabled for Ubuntu due to unresolved test issue

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/sdk#10610]
When creating this test it would consistently fail the Ubuntu check in gates due to an unresolved test issue, so we marked it CoreMSBuildAndWindowsOnly.  We don't loose meaningful test coverage here because the tested scenario is only valid on Windows platforms anyway, but I'm still tracking the test issue in case it affects other tests as well.  Here's the details:

In order to verify the contents of an output group I add a custom build target to the test project that copies all items in the output group to a folder under the test directory (Example: \TestPublishOutputGroup\TestOutput). You can see how this is done here: 

https://github.com/dotnet/sdk/blob/9e18c1c22e2cd5c2d0a1cc3a5dc3459e6f2390a6/src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs#L306 

Normally this works fine when running in the Ubuntu flavor, the two other tests do the same thing and pass. But for some reason in this one test when we go to verify the contents of this folder (using DirectoryInfo.Should().HaveFile()) we get an exception:

_Expected File "TestPublishOutputGroup" cannot be found in directory "/datadisks/disk1/workspace/work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/TestOutput"._

However, all other logging I've added to the test shows that this folder does indeed exist. I tried simply creating the directory before the build starts and verifying it exists using Directory.Exists, which reported true even though the exception still happens later on. I've also had the test output a diagnostic MSBuild log and confirmed it's creating the directory and placing items in it. From a sample log (where the directory was not explicitly created before the build):

_Task "Copy" (TaskId:101)
Task Parameter:
SourceFiles=
/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/obj/Debug/netcoreapp3.0/win-x86/TestPublishOutputGroup.pdb
CopyToPublishDirectory=PreserveNewest
ExcludeFromSingleFile=true
IsKeyOutput=
OutputGroup=PublishItemsOutputGroup
RelativePath=TestPublishOutputGroup.pdb
TargetPath=TestPublishOutputGroup.pdb
/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/bin/Debug/netcoreapp3.0/win-x86/publish/TestPublishOutputGroup.exe
IsKeyOutput=true
OutputGroup=PublishItemsOutputGroup
RelativePath=TestPublishOutputGroup.exe
TargetPath=TestPublishOutputGroup.exe (TaskId:101)
Task Parameter:DestinationFolder=/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/TestOutput (TaskId:101)
Copying file from "/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/obj/Debug/netcoreapp3.0/win-x86/TestPublishOutputGroup.pdb" to "/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/TestOutput/TestPublishOutputGroup.pdb". (TaskId:101)
Copying file from "/datadisks/disk1/workspace/_work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/bin/Debug/netcoreapp3.0/win-x86/publish/TestPublishOutputGroup.exe" to "/datadisks/disk1/workspace/work/11/s/artifacts/tmp/Debug/GroupPopulate---C21094DA/TestPublishOutputGroup/TestOutput/TestPublishOutputGroup.exe". (TaskId:101)
Done executing task "Copy". (TaskId:101)_

As you can see, MSBuild explicitly mentions copying files to this directory, and the copy task passes. So it's not clear to me why this exception is happening. This is why I've marked this test CoreMSBuildAndWindowsOnlyFact. It should also be noted that the PublishItemsOutputGroup was created for use by the Visual Studio Installer Projects extension, which only runs on Windows platforms anyway.

**Comment by swaroop-sridhar** [comment]
Fixed by https://github.com/dotnet/sdk/commit/03642eb6f4eecebbf63ae9934cf7e0f3cb04f70e
