### ISSUE TITLE
dotnet-install -Channel 3.1 -Runtime aspnetcore fail

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#10631]
AspNetCore's 'latest.version' is like this:
3.1.1
a1388f194c30cb21b36b75982962cb5e35954e4e

Runtime's is like this:
a1388f194c30cb21b36b75982962cb5e35954e4e
3.1.1

dotnet-install assumes the last line is the version: https://github.com/dotnet/sdk/blob/0e105528b3b5fa3d9c509a336fdafd92e464f764/scripts/obtain/dotnet-install.ps1#L180-L189

**Comment by wli3** [comment]
@wtgodbe

**Comment by wtgodbe** [comment]
I fixed this up manually. https://github.com/dotnet/sdk/issues/10636 tracks improving dotnet-install to avoid this going forward
