### ISSUE TITLE
dotnet-cache error : More than one file found for coreclr

### ISSUE THREAD

**Issue by rynowak** [dotnet/sdk#1063]
I'm getting a new error trying to run `dotnet cache` 

```D:\k\JitBench\.dotnet\sdk\2.0.0-preview1-005685\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.CrossGen.targets(45,5): error : More than one file found for coreclr [D:\k\JitBench\src\MusicStore\MusicStore.csproj]```

My command-line looks like:
```
dotnet cache -e .\MusicStore.csproj --framework-version 2.0.0-beta-001846-00 -f netcoreapp2.0 -r win7-x64 -c Release  -o ..\..\.cache
```

You can find the project file at https://github.com/aspnet/JitBench/tree/dev/src/MusicStore.

`dotnet --version` prints `2.0.0-preview1-005685`

----

Basically what I'm trying to accomplish is to replace our custom crossgen scripts with use of the cache. See [readme](https://github.com/aspnet/JitBench/blob/dev/README.md) for more details.

**Comment by eerhardt** [comment]
@rynowak - this is caused by https://github.com/dotnet/core-setup/issues/1884.  @chcosta is working on a fix now.

**Comment by eerhardt** [comment]
You can work around this for now by using an earlier `--framework-version`.  `2.0.0-beta-001834-00` or earlier will work.

**Comment by rynowak** [comment]
I'm still seeing this issue with 0834

```
dotnet cache -e .\MusicStore.csproj -f netcoreapp2.0 -c Release -o ..\..\.cache -r win7-x64 --framework-version 2.0.0-beta-001834-00
```

**Comment by livarcocc** [comment]
Will there be any action on this issue on the SDK side or is the fix entirely on core-setup?

**Comment by eerhardt** [comment]
This is now fixed with NETCore.App version 1887
