### ISSUE TITLE
Publishing with `win-x64` RID doesn't include runtime-specific Nuget libraries

### ISSUE THREAD

**Issue by nxtn** [dotnet/sdk#10665]
## Steps to reproduce

Reference a Nuget package with runtime-specific libraries.

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="2.0.0" />
  </ItemGroup>

</Project>
```

- `dotnet publish`

```
\publish
  \runtimes
    \win7-x64
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    \win7-x86
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    \win10-x64
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    \win10-x86
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    ...
  ...
```

- `dotnet publish -r win10-x64`

```
\publish
  \Microsoft.Management.Infrastructure.dll
  ...
```

- `dotnet publish -r win-x64`

No library from the Nuget package is copied to */publish* directory.

## Expected behavior

- `dotnet publish -r win-x64`

```
\publish
  \runtimes
    \win7-x64
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    \win10-x64
      \lib\netstandard1.6\Microsoft.Management.Infrastructure.dll
      ...
    ...
  ...
```

## Actual behavior

`dotnet publish -r win-x64` succeeds, but the produced program will definitely crash.

> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

## Environment data

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
```

**Comment by davedx** [comment]
I think we have the same issue with SqlClient dll's and dotnet publish. I actually made an issue on their repo but it probably should be here too.
https://github.com/dotnet/SqlClient/issues/445

I made a reproduction repo for the issue here: https://github.com/davedx/sqlclient-repro

**Comment by richlander** [comment]
I just tried to repro this with the .NET 6 SDK. This is what I see. Does that resolve the issue?

```console
root@a1e6b08d8845:/app# dotnet publish -r win10-x64
root@a1e6b08d8845:/app# find bin/Debug/net6.0/win10-x64/publish/ | grep Microsoft.Man
bin/Debug/net6.0/win10-x64/publish/Microsoft.Management.Infrastructure.Native.dll
bin/Debug/net6.0/win10-x64/publish/Microsoft.Management.Infrastructure.dll
bin/Debug/net6.0/win10-x64/publish/Microsoft.Management.Infrastructure.Native.Unmanaged.dll
root@a1e6b08d8845:/app# 
```

**Comment by PatrickKunz** [comment]
I publish with the following command on my Apple arm computer with dotNet arm installed:

dotnet publish -c Release --runtime win-x64  --no-self-contained

I wasn't able to make it work on a Windows x64 system.

**Comment by nxtn** [comment]
It is recommended to use portable RIDs, such as `win-x64`, instead of version-specific RIDs, such as `win10-x64`, since .NET 8.

For more information, see [Using RIDs](https://learn.microsoft.com/dotnet/core/rid-catalog#using-rids) and [.NET SDK uses a smaller RID graph](https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph).

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
  </ItemGroup>

</Project>
```

- `dotnet publish`

```
\publish
  \runtimes
    \win-x64
      \lib\netstandard1.6\microsoft.management.infrastructure.dll
      ...
    \win-x86
      \lib\netstandard1.6\microsoft.management.infrastructure.dll
      ...
    ...
  ...
```

- `dotnet publish -r win-x64`

```
\publish
  \Microsoft.Management.Infrastructure.dll
  ...
```

- `dotnet publish -r win10-x64 -p:UseRidGraph=true`

```
\publish
  \Microsoft.Management.Infrastructure.dll
  ...
```
