### ISSUE TITLE
Package content files are missing from VS solution explorer until project is reloaded

### ISSUE THREAD

**Issue by jainaashish** [dotnet/sdk#1068]
1. Create a .net core library and add a content file (a simple txt file with CopyToOutputDirectory set to PreserveNewest)
2. Pack this library and create a NuGet package out of it.
3. Install this nupkg on a .net core console app.

Expected:
Txt file is added into project and shown in Solution Explorer.

Actual:
Txt file isn't available in solution explorer until you reload the project.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/project-system#1934
