### ISSUE TITLE
Surprising template version of 3.1.3

### ISSUE THREAD

**Issue by omajid** [dotnet/sdk#10697]
Over in https://github.com/dotnet/sdk/issues/10435, @livarcocc explained:

> The runtime version is used because [the template version] depicts which runtime it targets and it revs based on the runtime.

> [At 3.0 GA, the template version will be] 3.0.0, matching the runtime that it targets.

But I just realized that the .NET Core SDK 3.1.102 release has a template version of `3.1.3`, which doesn't match the runtime version of `3.1.2`:

```
$ tar tf ~/downloads/dotnet-sdk-3.1.102-linux-x64.tar.gz | grep templates | head -2
./templates/
./templates/3.1.3/
```
Is this intentional?

**Comment by crummel** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
These can have arbitrary version numbers as long as the first and second part match the tfm. We had to bump by one to fix a setup issue. Cc @wli3

**Comment by omajid** [comment]
Thanks for the clarification!
