### ISSUE TITLE
Unable to build WPF WindowsDesktop SDK project targeting NET472

### ISSUE THREAD

**Issue by wasabii** [dotnet/sdk#10704]
The following began after updating to 3.1.101.

Receiving the following error trying to compile a NET472 target using the WindowsDesktop SDK. It would appear the path being built to Program Files is incorrect. The `%29`'s in there are URL escaping, not appropriate to appear on file paths.

`
The "Microsoft.Build.Tasks.Windows.MarkupCompilePass1" task could not be loaded from the assembly C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\net472\PresentationBuildTasks.dll. Could not load file or assembly 'file:///C:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\net472\PresentationBuildTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Systemware.ContentCloud.Windows.Launch	C:\Program Files (x86)\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets	225	
`

I tracked this down to the path being used in `Microsoft.WinFx.props` file delivered in SDK 3.1.101. However, I'm not sure what the issue is here. It just seems to use System.IO.Path.GetFullPath on `MSBuildThisFileDirectory`. I don't know why %29s would originate from that.

Anyways, I set `_PresentationBuildTasksAssembly` to the proper hard coded fully qualified path in my project file, and now it builds fine.

**Comment by brcaswell** [comment]
hmm.. an escaped Path and potentially the file protocol are unexpected, right?   

apart from that, is the dotnet sdk installed in "Program Files (x86)" on your system? and not `Program Files"? 

Is your system x64? 

Is your project building to "Any CPU" platform or specifying one?

---

I'm also curious, what does `$(ProgramW6432)` return:  "Program Files", "Program Files (x86)", "Program Files %28x86%29", or empty on your machine?

Also, How did you track down the targets? you determined it from source or you use a program like [GitHub - MSBuildStructuredLog](https://github.com/KirillOsenkov/MSBuildStructuredLog)?

**Comment by wasabii** [comment]
The file protocol makes sense, since that's part of the normal exception for assembly missing. It's the other path, with the back slashes, that you shouldn't see escaping in.

I just read the targets file in the SDK dir.

System is x64. But visual studio is 32bit msbuild, so that's expected.

Not specifying any other platform.

**Comment by brcaswell** [comment]
issue relates to https://github.com/dotnet/wpf/issues/2415
and should be fixed with SDK 3.1.3 https://github.com/dotnet/wpf/pull/2487 it seems

**Comment by wasabii** [comment]
Yup. That's it.
