### ISSUE TITLE
dotnet sln add extremely slow when adding multiple projects

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/sdk#10719]
Doing a simple glob add of say 10 projects causes `dotnet sln add` to take around 10~ seconds.

**Comment by marcpopMSFT** [comment]
Old bug triage. Tried with .NET 8 preview 5 with 100 projects all in peer directories (so not a significantly deep query).
PS: dotnet sln add (ls -r **/*.csproj) --> ~7 seconds
Git Bash: dotnet sln add **/*.csproj --> ~10 seconds

Given this, I'm closing out this old bug as likely the issue has been resolved as 100 in <10 seconds seems reasonable to me.

**Comment by sahin52** [comment]
Why do you think it is reasonable? Reading the sln file as xml, writing it back takes less than 1 second. I wrote a workaround for this problem, and now it takes 0.1 second. I think `dotnet sln add` might as well be that fast.

Adding 25 projects with `dotnet sln add` command took 4 seconds, the workaround of adding the projects by string modification is 0.1 second.
