### ISSUE TITLE
dotnet store is optimizing assemblies multiple times

### ISSUE THREAD

**Issue by rynowak** [dotnet/sdk#1072]
dotnet cache is generating native images for all transitive dependencies for all assemblies in its output set. From the logs, it appears that it's not reusing any intermediate results - so commonly-depended-upon assemblies are compiled many times.

I've attached a log that I generated from aspnet/JitBench. Search for `Microsoft.AspNetCore.Authentication.dll generated successfully` and you'll see it show up multiple times.

`dotnet --version` outputs `2.0.0-preview1-005694` 

#### Repro

To repro this checkout `dev` and do:
```
.\Dotnet-Install.ps1 -SharedRuntime -InstallDir .dotnet -Channel master -Architecture x64
.\Dotnet-Install.ps1 -InstallDir .dotnet -Channel master -Architecture x64

cd src\MusicStore

dotnet restore

dotnet cache -e .\MusicStore.csproj -c Release -f netcoreapp2.0 -r win7-x64 -o .cache
```

[out.txt](https://github.com/dotnet/sdk/files/891795/out.txt)

**Comment by rynowak** [comment]
Interestingly enough, I'm seeing multiple distinct version numbers in the artifact.xml the packages. This project is using `1.2.0-preview1-*` for the ASP.NET dependencies. Is this supported?

**Comment by ramarag** [comment]
race conditions are possible as each package and its closure are restored separately.
However if one closure is copied to the staging area then subsequent crossgen of those assemblies will not be performed.

One perf optimization you could do is list the common dependency before their consumers in the MusicStore.csproj, this will likely prevent the duplication.

**Comment by nguerrera** [comment]
Looking at changing the behavior to not restore each package individually. See https://github.com/dotnet/sdk/issues/1211#issuecomment-495393012

**Comment by nguerrera** [comment]
I believe some portion of this is a duplicate of #1211 and another portion is a duplicate of #1682. The former is postponed to 5.0, while the latter should be fixed. Closing as such.
