### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007001F running any dotnet cli command on macOS

### ISSUE THREAD

**Issue by igalnassi** [dotnet/sdk#10737]
I am running the most current version of macOS - Catalina 10.15.3 (19D76).

I have installed .Net Core in the past and it did run properly at one point. Before I upgraded to the latest version of Catalina, I wanted to create a new application and immediately saw that any command that I run (i.e. dotnet xxx) is failing with the same issue except the few below. Although --info does run, it throws the error in the first line as well (% is the zsh command line):

```
% dotnet --info
Failed to create CoreCLR, HRESULT: 0x8007001F

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```
% dotnet --list-sdks
3.1.102 [/usr/local/share/dotnet/sdk]
```

```
% dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

Any other dotnet command including dotnet -h is failing with the below errors:

```
dotnet -h
Failed to create CoreCLR, HRESULT: 0x8007001F
```

I tried doing rm -rf to the installation directory /usr/local/share/dotnet, re-downloaded the installer and reinstalled the latest version (https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.102-macos-x64-installer) with no luck.

I have also tried installing the latest stable version of sdk 3.0 (https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.103-macos-x64-installer)

**UPDATE**: I restarted my machine and seems to be working fine.

**Comment by igalnassi** [comment]
Restart seems to fix the issue. I haven't had a reoccurrence after working with it some more. Closing the issue.

**Comment by brianuol** [comment]
FYI I've found a full blow restart is a bit much for this - just exit bash by typing exit before closing the terminal window.

**Comment by wbuck** [comment]
For me I had to restart my laptop in order to clear this error...

**Comment by keerthi-subramanian** [comment]
For me, found the problem that I did not have the same version of dotnet SDKs used in the repository. Installed them and it works fine. Usually the SDK version is specified in the `global.json` file but some repository have sub projects that use a different version as well. so had to do a grep on major.minor version to get all the required SDK version. E.g., `grep -r 3.1.101`
