### ISSUE TITLE
.NET Core SDK 3.1.200-preview-015002 does not have 2.1.16 or 3.0.3 patch.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#10736]
Use [D16.5](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/3b50fa70fb741f6f139e596f86f8f04c9814f3bf/b71c96b2-0d5d-e8af-3d30-8f3c690b62c5%3bchannels/internal/Preview/bootstrappers/fixed/Enterprise/vs_Enterprise.exe) [29827.131] (SDK 3.1.200-eview-015002 with 2.1.16 and 3.0.3 runtime inserted)

**Repro Steps:**

1.	dotnet new global.json
2.	edit global.json, check the SDK version is " 3.1.200-preview-015002"
3.	mkdir test
4.	cd test
5.	dotnet new console
6.	edit test.csproj and set TargetFramework from netcoreapp3.1 to netcoreapp3.0
7.	dotnet publish -r win10-x64
8.	check the contents of bin\Debug\netcoreapp3.0\win10-x64\publish, search for “Microsoft.NETCore.App/”

**Expected:** That version is 3.0.3.

**Actual:** The version is 3.0.2.

Note: 
1. Using SDK  3.1.200-eview-015002, retarget app to netcoreapp2.1 and look for the version for “Microsoft.NETCore.App” is 2.1.15, not 2.1.16.
         2. Using SDK  3.1.200-eview-015002, retarget app to netcoreapp3.1 and look for the version for “Microsoft.NETCore.App” is 3.1.2.

**dotnet --info**:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-015002
 Commit:    b3dae24c3b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-015002\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wli3** [comment]
3.1.200-servicing-015009 should have the fix
