### ISSUE TITLE
Link "Learn more" on the first page of .Net 5.0.100-preview.1.20128.16 setup wizard, returns not match.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#10742]
**Repro Steps:**
1.	Open the .Net 5.0.100-preview.1.20128.16 installation package
2.	Click the "Learn more" link

**Expected:** It will shows Web page about .Net 5.0

**Actual:** It link to https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0.md
![image](https://user-images.githubusercontent.com/57380211/75669733-7da52680-5cb6-11ea-8caa-fe07cd6ec501.png)

**Comment by sfoslund** [comment]
Fixed by dotnet/core-sdk#6779
