### ISSUE TITLE
Support net5.0

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#10756]
This item tracks the required work for supporting `net5.0`. This issue doesn't track supporting the OS part of the TargetFramework, i.e. `net5.0-ios`.

Critical path: NuGet --> SDK --> Template

Work Items:
- [x] NuGet - Understanding net5.0 as ".NETCoreApp" TargetFrameworkIdentifier (TFI)
Tracking issue: https://github.com/nuget/home/issues/9089
Changeset: https://github.com/NuGet/NuGet.Client/commit/162e23520da60ead3868b48b097731b1e405a5e4, Assignee: @rrelyea
- [x] SDK - Understanding net5.0 as ".NETCoreApp" TFI
Changeset: https://github.com/dotnet/sdk/commit/0f5fc4b4138351f14a8555f466b443240a6bc601
Assignee: @dsplaisted
- [ ] Templating - Change the default TFM to net5.0
Assignee: @ViktorHofer 
  - [x] test templates: https://github.com/dotnet/test-templates/pull/83
  - [x] nunit3 template: https://github.com/nunit/dotnet-new-nunit/pull/39
  - [x] lib & console: https://github.com/dotnet/templating/pull/2310
  - [x] web templates: https://github.com/dotnet/aspnetcore/pull/19860
  - [x] windowsdesktop templates: https://github.com/dotnet/windowsdesktop/pull/800, https://github.com/dotnet/winforms/pull/3344, https://github.com/dotnet/wpf/pull/3042
  - [ ] VS templates: https://github.com/dotnet/templates/pull/365
- [x] React to TFM change in installers (runtime, windowsdesktop, aspnetcore), @ViktorHofer
- [x] Scouting the net5.0 change, @ViktorHofer @dsplaisted @rrelyea

**Comment by benaadams** [comment]
Add `#define` for `NET5_0`? https://github.com/dotnet/sdk/issues/11409

**Comment by dsplaisted** [comment]
> Add `#define` for `NET5_0`? #11409

See https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#preprocessor-symbols, as well as #11236 and #11635

**Comment by benaadams** [comment]
Should it also include `NETCOREAPP5_0` or it will make everything using that against the previews go weird and aspnet CI etc start failing

**Comment by dougbu** [comment]
Oops, meant to unassign myself since my part is done

**Comment by ViktorHofer** [comment]
Closing as the tracked work is completed.
