### ISSUE TITLE
Microsoft.NET.Sdk package produced from official build bundling outdated NuGet

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/sdk#10759]
According to BAR, the most recent build from dotnet/sdk should include a build from NuGet/NuGet.Client at 
NuGet/NuGet.Client@64f2febf7d1de8b0228eca5afed97a96c5a30bba, however, by downloading the package from the build at https://dev.azure.com/dnceng/internal/_build/results?buildId=543706 and inspecting the versions of NuGet in the Microsoft.NET.Sdk package, it looks like it bundles a copy of NuGet from commit NuGet/NuGet.Client@cb402b5a3340ab5b2605ecc72de7f70aaac95344.

My guess would be that the bug is because in `eng/Versions.props` the line that Darc updates

https://github.com/dotnet/sdk/blob/1f2a4a110e356808d721358ce358de4f88923795/eng/Versions.props#L21

is overridden by 
https://github.com/dotnet/sdk/blob/1f2a4a110e356808d721358ce358de4f88923795/eng/Versions.props#L43-L57

and as a result, the NuGet version is pinned to an older version. This is blocking dotnet/runtime from uptaking a NuGet fix to prevent spurious CI failures.

cc: @ViktorHofer

**Comment by dwilsonbst** [comment]
Hello, is there any ETA for this? Running into the original issue fixed on the nuget side.

**Comment by ViktorHofer** [comment]
This was fixed with https://github.com/dotnet/sdk/pull/10760
