### ISSUE TITLE
.NET Core projects build with empty FrameworkDisplayName

### ISSUE THREAD

**Issue by reflectronic** [dotnet/sdk#10774]
`TargetFrameworkAttribute.FrameworkDisplayName` appears to not be set properly in .NET Core projects.
```cs
using System;
using System.Reflection;
using System.Runtime.Versioning;

class Program
{
    static void Main(string[] args)
    {
        var str = Assembly.GetExecutingAssembly().GetCustomAttribute<TargetFrameworkAttribute>().FrameworkDisplayName;
        Console.WriteLine($"\"{str}\": {str.Length}");
    }
}
```

When targeting .NET Core 3.1:
```
"": 0
```

When targeting .NET 4.8:
```
".NET Framework 4.8": 18
```

**Comment by AraHaan** [comment]
This seems to still be the case, could it be that the .NET SDK does forgets to set it for .NET Core projects perhaps?

**Comment by KalleOlaviNiemitalo** [comment]
The _SetTargetFrameworkMonikerAttribute task would apparently read it from the TargetFrameworkMonikerDisplayName property: <https://github.com/dotnet/msbuild/blob/c9eb9dd64e9a2e8a433900a1a626d65a2bce4428/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L332-L341>

The GetReferenceAssemblyPaths target in Microsoft.Common.CurrentVersion.targets would set the property from the TargetFrameworkMonikerDisplayName output parameter of the GetReferenceAssemblyPaths task: <https://github.com/dotnet/msbuild/blob/c9eb9dd64e9a2e8a433900a1a626d65a2bce4428/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1226>

However, the GetReferenceAssemblyPaths target is overridden in Microsoft.NET.DisableStandardFrameworkResolution.targets and does nothing: <https://github.com/dotnet/sdk/blob/2c798cbf6bf259ce49d94d91bc665a95d42d7a7f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DisableStandardFrameworkResolution.targets#L14>

Does the missing FrameworkDisplayName cause any problems?

It seems you can just set the TargetFrameworkMonikerDisplayName property in the project (and delete any stale `obj/*/*/*.AssemblyAttributes.cs`) if you really need it. Would ".NET 6.0" be a correct format?

**Comment by AraHaan** [comment]
I was wanting it set to ``.NET 6.0`` or ``.NET 6`` for it 😄 But yes perhaps that file is the true cause of this.

And yes it causes issues for me where I would expect it set in all .NET versions due to .NET Framework also having it set before for years. Likewise I know of people who depend on it being set properly to a non-empty string in the metadata because at runtime they use it to check if everything targets a specific framework when loaded (some people use reflection loading to check this I think) then if it's not set to an expected value they unload it and skip it.

**Comment by KalleOlaviNiemitalo** [comment]
> at runtime they use it to check if everything targets a specific framework when loaded

I'd think TargetFrameworkAttribute.FrameworkName suffices for that purpose.

**Comment by AraHaan** [comment]
Ah I see the reason for this: https://github.com/dotnet/sdk/blob/22c4860dcb2cf6b123dd641cc4a87a50380759d5/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L33

**Comment by AraHaan** [comment]
Ah I see the issue, for this the default *could* be changed for .NET Core to the following:

```cs
<DisableStandardFrameworkResolution>false</DisableStandardFrameworkResolution>
<TargetFrameworkRootPath Condition="'$(TargetFrameworkRootPath)' == ''">$(DOTNET_ROOT)/shared/$(TargetFrameworkIdentifier)/$(TargetFrameworkRuntimeVersion)</TargetFrameworkRootPath>
```
Where ``$(TargetFrameworkRuntimeVersion)`` is the version of the .NET Core framework used by the KnownFrameworkReference node in the SDK for that specific version.

**Comment by dsplaisted** [comment]
@terrajobst @baronfel @mhutch Do you think we should try to set the FrameworkDisplayName on the automatically generated TargetFrameworkAttribute for .NET Core projects?

**Comment by borgdylan** [comment]
I have also experienced this issue. Can anything be done or should I just give up all hope?

**Comment by AraHaan** [comment]
I guess 1n option is to manually parse it ourselves:

```xml
<FrameworkDisplayName Condition="'$(TargetFramework)' == 'net5.0' OR '$(TargetFramework)' == 'netcoreapp5.0'">.NET 5.0</FrameworkDisplayName>
<FrameworkDisplayName Condition="'$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'netcoreapp6.0'">.NET 6.0</FrameworkDisplayName>
<FrameworkDisplayName Condition="'$(TargetFramework)' == 'net7.0' OR '$(TargetFramework)' == 'netcoreapp7.0'">.NET 7.0</FrameworkDisplayName>
```
The reason for the ``OR``'s here is that even with the shortened ``netX.Y`` TFM's the longer ``netcoreappX.Y`` version of them is still valid (and mean the same thing).
