### ISSUE TITLE
Breakpoints do not work properly when debugging tests

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/sdk#10783]
## Steps to reproduce:
Sorry that these repro steps involve a ton of extra code. I tried to pare it down to really basic stuff (like dotnet new xunit) but after spending like 2 hours on it I couldn't get it to repro in those cases.

1. `git clone git@github.com:dotnet/aspnetcore-tooling.git`
1. `.\restore.ps1`
1. `.\build.cmd`
1. `. .\activate.ps1`
1. `.\startvs.ps1 src\Razor\Razor.sln`
1. Set a breakpoint in any of the tests of `DefaultRazorHoverInfoServiceTest.cs`.
1. Open the test explorer and Debug the test you have a breakpoint in.
1. Observe that you get this screen 
![BreakMode](https://user-images.githubusercontent.com/14987221/76127950-f27aa800-5fb7-11ea-8d47-79c43d4dfb90.PNG)

## Expected results;
The expected result is that the breakpoint is hit normally, with callstacks and local variables being visible.

## Extra info
Of note here is that the problem can be avoided by changing the TargetFramework to net472 (from netcoreapp5.0).

CC @NTaylorMullen and @ajaybhargavb who I talked about this with.

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/vstest#2394
