### ISSUE TITLE
Change default location of Exec files

### ISSUE THREAD

**Issue by danielbecroft** [dotnet/sdk#10802]
When an `<Exec />` command is used in the `csproj` file, a temporary file is generated in the users %LOCALAPPDATA% folder with the filename:

`%LOCALAPPDATA%\Temp\tmp1423b2926a6342b7b437fa1f148b3963.exec.cmd`

Unfortunately, in an enterprise environment where paths are whitelisted in order to be able to execute, this path is not ideal. It could be whitelisted to `tmp*.exec.cmd`, but that could be insecure.

Is it possible, or could it be possible, to change where this file is generated?

**Comment by rainersigwald** [comment]
This issue was moved to microsoft/msbuild#5168
