### ISSUE TITLE
SDK picking wrong path for project output

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1081]
At the core of [dotnet/roslyn](https://github.com/dotnet/roslyn) there are two projects:

- CodeAnalysis.csproj
- CSharpCodeAnalysis.csproj (which references CodeAnalysis.csproj)

Been working on converting them to the new SDK and both will be targeting netstandard1.3 projects.  But I'm unable to build because the SDK is picking the wrong output path for CodeAnalysis.csproj and hence can't create the reference element for CSharpCodeAnalysis

``` cmd
  CodeAnalysis -> E:\code\roslyn\Binaries\Debug\Dlls\CodeAnalysis\Microsoft.CodeAnalysis.dll
CSC : error CS0006: Metadata file 'E:\code\roslyn\Binaries\Debug\Microsoft.CodeAnalysis.dll' could not be found [E:\code\roslyn\src\Compilers\CSharp\Portable\CSh arpCodeAnalysis.csproj]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project
info for 'E:\code\roslyn\src\Compilers\Core\Portable\CodeAnalysis.csproj'. This can indicate a missing project reference. [E:\code\roslyn\src\Compilers\CSharp\Cs cCore\CscCore.csproj]
``` 

Notice that CodeAnalysis when emitting has an extra "Dlls" directory in the output.  This is missing when CSharpCodeAnalysis tries to consume it. 

The reference is straight forward: 

``` xml
    <ProjectReference Include="..\..\Core\Portable\CodeAnalysis.csproj">
      <Project>{1EE8CAD3-55F9-4D91-96B2-084641DA9A6C}</Project>
      <Name>CodeAnalysis</Name>
    </ProjectReference>
``` 

Repro Steps:

1. Clone https://github.com/jaredpar/roslyn
1. Sync to branch repo-ps2
1. Run `msbuild /t:Restore Compilers.sln`
1. Run `msbuild /v:m /m src\Compilers\CSharp\CscCore\CscCore.csproj`

**Comment by dsplaisted** [comment]
@jaredpar Is this fixed by now?  I helped you with something similar today.

**Comment by jaredpar** [comment]
Ive since found a way to work around this. Cant remember the details though :(

**Comment by livarcocc** [comment]
Seems like this has been figured out and that @dsplaisted managed to help you out. Closing. Re-activate or comment if that's not the case.
