### ISSUE TITLE
NetCoreApp 1.1 includes unwanted packages

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1082]
It appears that targeting NetStandard 1.3 is including unexpected assemblies.  In particular Microsoft.CodeAnalysis.  This is a part of compile and runtime (should be neither).  

How can I remove this package from the set of packages considered for the build?  Having it their is completely breaking the restore / build experience in roslyn.

**Comment by livarcocc** [comment]
Is this when you target it as a TFM?

@weshaggard @ericstj @terrajobst can you help on why these packages are part of netstandard1.3?

**Comment by ericstj** [comment]
They are not part of the NETStandard.Library package closure so they aren't coming from us.

@jaredpar is your project somehow referencing these packages via PackageReference or transitively through a project reference or some other PackageReference?  Your assets file in the obj folder should show you how they were brought in.

/cc @dsplaisted

**Comment by livarcocc** [comment]
@jaredpar can you answer @ericstj questions above?

The CLI has a Microsoft.Common.CurrentVersion.targets that has this in it:

```
  <PropertyGroup>
    <CodeAnalysisTargets Condition="'$(CodeAnalysisTargets)'==''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CodeAnalysis\Microsoft.CodeAnalysis.targets</CodeAnalysisTargets>
  </PropertyGroup>
```

I wonder if that is bringing it in. I would expect not, but I don't have a VS installation right now to verify.

**Comment by jaredpar** [comment]
Was able to reproduce the problem this morning and @ericstj came by to help me dig into it.  It appears to be a bug in NuGet.  

The problem boils down to the following:

- Project CSharpCodeAnalysis 
    - Produces the assembly Microsoft.CodeAnalysis.CSharp
    - Does **not** set the MSBuild property `$(Version)` or `$(PackageVersion)` 
- Project DeployCoreClrTestRuntime
   - Is a NetCore 1.1 app
   - Has a project reference to CSharpCodeAnalysis 

During restore it appears that NuGet is attempting to promote the project reference to Microsoft.CodeAnalysis.CSharp to a package reference.  This is evident in the assets file:

``` json
    "Microsoft.CodeAnalysis.CSharp/1.0.0": {
      "type": "project",
      "path": "../../Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj",
      "msbuildProject": "../../Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj"
    },
```

The version 1.0.0 is being chosen because it is the default if neither `$(Version)` or `$(PackageVersion)` is specified.  Context is here:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L452

@ericstj believes this behavior is likely a remnant of the old project to package promotion code.  Either way though this seems like a bug.  There is is a single package reference to Microsoft.CodeAnalysis.CSharp, indirectly from NetCoreApp, yet I'm getting downgrade warnings.  

CC @emgarten for the NuGet side of this.

**Comment by emgarten** [comment]
@jaredpar what is the expectation here? should this be using the package instead of the project? Or are you expecting it to be completely absent?

I'm not fully clear on how this is going from a Project to a PackageReference here, this looks like a normal Project in the assets file.

**Comment by ericstj** [comment]
Justin, here's what's happening.
(Project) > Microsoft.NETCore.App (Package) > CodeAnalysis/1.3.0 (Package)
(Project) > CodeAnalysis (Project)

NuGet assumes that the CodeAnalysis (Project) is version `1.0.0` since it doesn't set any other projects.

NuGet then complains about a downgrade of CodeAnalysis from 1.3.0 to 1.0.0.

My expectation is that NuGet wouldn't even see these things as the same thing since it no longer implements Package->Project replacement.  My expectation is that it would just ignore the coincidental overlap and let MSBuild do whatever it wants to do with the *potentially* overlapping projectreference and package reference.

**Comment by emgarten** [comment]
@ericstj thanks, that makes sense!

NuGet shouldn't display downgrade warnings between different types (package/project). This looks like a bug in NuGet.

**Comment by dsplaisted** [comment]
> My expectation is that NuGet wouldn't even see these things as the same thing since it no longer implements Package->Project replacement.

It does support this now to a degree.  If you have a ProjectReference (direct or transitive), it will override any PackageReference to something with the same package ID.  So it won't automatically resolve packages to projects, but if you add a project reference you can replace a NuGet package with the source code for your build.

**Comment by jaredpar** [comment]
@emgarten 

> NuGet shouldn't display downgrade warnings between different types (package/project). This looks like a bug in NuGet.

Is there a bug tracking this in NuGet or should we file a new one?

**Comment by emgarten** [comment]
@jaredpar it looks like https://github.com/NuGet/Home/issues/4620 covers this, we can close this issue in favor of that one.

**Comment by ericstj** [comment]
> So it won't automatically resolve packages to projects, but if you add a project reference you can replace a NuGet package with the source code for your build.

I think this behavior needs to be explicit.  Now that we have MSBuild's rich metadata system I think we should use it.  I can't even count the number of times I've helped folks who "accidentally" used this feature.

**Comment by nguerrera** [comment]
Nuget/home#4620 is fixed
