### ISSUE TITLE
Recent builds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1083]
Where can I find recent builds of the SDK tools?  In particular the targets, MSBuild tasks, etc ....  Basically everything which needs to be available when `$(MSBuildSDKsPath)` is overriden. 

Presently I'm getting blocked very hard by #752.  No way to make progress unless I can get a new build of the SDK to work around this problem.

**Comment by natidea** [comment]
Packages for each build are uploaded to https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NET.Sdk

**Comment by jaredpar** [comment]
@natidea how is that NuGet intended to be consumed by end developers seeking to override the SDK?  I tried setting `$(MSBuildSDKsPath)` as suggested in other threads.  That failed though because the layout seemingly expected by the code does not match the layout of the NuGet package:

Repo:

1. Unzip everything to `e:\temp\sdk`
1. `set MSBuildSDKsPath=e:\temp\sdk\build`
1. Build my project and get the following errors

``` 
E:\code\roslyn\src\Test\PdbUtilities\PdbUtilities.csproj(5,3): error MSB4019: The imported project "e:\temp\sdk\build\Microsoft.NET.Sdk\Sdk\Sdk.props" was not fo und. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
E:\code\roslyn\src\Compilers\Core\Portable\CodeAnalysis.csproj(5,3): error MSB4019: The imported project "e:\temp\sdk\build\Microsoft.NET.Sdk\Sdk\Sdk.props" was
not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
``` 

Same error was repeated many times.

**Comment by natidea** [comment]
Try changing step 2 to:
`set MSBuildSDKsPath=e:\temp\sdk`

**Comment by jaredpar** [comment]
@natidea same basic error.  The code appears to be looking for targets under the following structure: `$(MSBuildSDKsPath)\\Microsoft.NET.Sdk\Sdk\`

**Comment by natidea** [comment]
Looks like it is expecting `$(MSBuildSDKsPath)` to mirror `%VSINSTALLDIR%\MSBuild\Sdks`
and unzip the package into `$(MSBuildSDKsPath)\Microsoft.NET.Sdk\`

**Comment by jaredpar** [comment]
After digging through the MSBuild source code I figured out the trick here.  The path for Sdk.props / Sdk.targets is the combination of the following values:

1. `$(MSBuildSDKsPath)`
1. Value inside the Sdk attribute of `<Import Project="Sdk.props" Sdk="..." />`
1. The string `"Sdk"`

Hence to get this to work do the following:

1. Unpack the NuGet to `e:\temp\sdk`
1. `set MSBuildSDKsPath=e:\temp`
1. Set the SDK attribute to "SDK"

**Comment by jaredpar** [comment]
@natidea unzip isn't really a long term option here.  There really needs to be a solution which allows us to conssume the SDK updates via the installed NuGet package.  This is how every other tool works and adding extra steps unnecessarily complicates the build. 

I think the current solution is work able though.  Our build already has MSBuild properties which represent versions of NuGet packages that we consume.  Hence I can simply structure our core props file with the following

``` xml
<MSBuildSDKsPath>$(NugetPackagerRoot)\Microsoft.Net.Sdk)</MSBuildSDKsPath>
```

Then individual project files can contain the following:

``` xml
<Import Project="Sdk.props" Sdk="$(MicrosoftNetSdkVersion)" />
```

In this case `$(MicrosoftNetSdkVersion)` will correspond to the version number of the NuGet package.  Hence it combined it will expand out to `$(MSBuildSDKsPath)\$(MicrosoftNetSdkVersion)\Sdk` which has the porps / targets.  As long as the NuGet remains otherwise self contained it will function.

**Comment by jaredpar** [comment]
Been playing with this for an hour now and it seems to be doing the trick.  Going to keep this open until I can get a full build complete.  Will close when I get that far.

**Comment by livarcocc** [comment]
The plan for 2.0 is for the user to update the NETCore.SDK together with the CLI. If you want a new version of the SDK, find what version of the CLI carries it (and really, you shouldn't be thinking about these two as two different versions, just reason about what version of the CLI you want), install that and, if necessary, set it in the global.json so that it gets picked up.

MSBuild itself has plans to develop an acquisition story for SDKs, potentially, using NuGet. But that's post 2.0.

Other than that @jaredpar, while at the very beginning of things we intended for these SDKs to be consumed as NuPkgs, we shipped 15.0 with this idea set aside. Given that, the fact that these are available as NuPkgs is simply a reflection of that time and the fact that it is a convenient way to share code across repos. Not that it currently is intend to be consumed as such.

**Comment by jaredpar** [comment]
> The plan for 2.0 is for the user to update the NETCore.SDK together with the CLI. If you want a new version of the SDK, find what version of the CLI carries it ... install that 

That is a non-starter for the Roslyn repo.  Forcing installation to get new builds, and bug fixes means that it's forcing dependencies to all of our consumers: in house developers, OSS contributors, Microbuild, bulid from source, etc ...  This is an enormous step backwards.

We're able to fully build the world today without any installation. Doing it now, just for this MSBuild task only is a huge step backwards.  There is no other tool that requires this.  We should meet and discuss if this is the intended course. 

> The plan for 2.0 is for the user to update the NETCore.SDK together with the CLI

The CLI can't, and likely won't, ever able to fully build the Roslyn repo due to the reliance of CoreCLR.  Why should we have to install the full CLI, which we can't use, to get just the SDK componets?

**Comment by dsplaisted** [comment]
> Why should we have to install the full CLI, which we can't use, to get just the SDK components?

Because the CLI is easier to install and for us to release than Visual Studio, which is how updates to the SDK are currently delivered.

The CLI in general doesn't need to be "installed", in the CLI and SDK repos (and probably others) we use the dotnet-install scripts to download and unzip a CLI to use locally.  We should make sure we [support pointing the SDK resolver at a downloaded CLI](https://github.com/dotnet/cli/issues/6112#issuecomment-293441162) too.

**Comment by jaredpar** [comment]
> Because the CLI is easier to install and for us to release than Visual Studio, which is how updates to the SDK are currently delivered.

Why does Visual Studio need to be updated here?  This is an MSBuild issue.  

Build tools need to be thought of separately from Visual Studio.  This is feedback we get contantly from customers who don't want to install VS on build servers.

**Comment by dsplaisted** [comment]
> Why does Visual Studio need to be updated here? This is an MSBuild issue.

That's how we shipped VS 2017 RTM.  Originally the SDK was a NuGet package but we ran into issues with that so shipping as part of VS was what we were able to deliver in the timeframe.

We agree that build tools should be installable separately from VS, and shipping the SDK as part of the CLI helps enable that.

**Comment by jaredpar** [comment]
> We agree that build tools should be installable separately from VS, and shipping the SDK as part of the CLI helps enable that.

Only if CLI is an acceptable build environment.  That's not the case for roslyn.  Eventually one day it may be.  But for the foreseeable future it won't be.  That means SDK still has no rapid ship story for environments like ours. 

@livarcocc mentioned that it may be possible to download CLI, then have MSBuild pick up SDK bits from there.  If so that could work as a rapid ship story

**Comment by dsplaisted** [comment]
> it may be possible to download CLI, then have MSBuild pick up SDK bits from there

Yes, that's what I'm saying.  I've added a note that [we should support this](https://github.com/dotnet/cli/issues/6112#issuecomment-293441162) to the appropriate work item.
