### ISSUE TITLE
Mapping project.json imports to new SDK

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1084]
Working on porting some PCL csproj + project.json to the new SDK project file format.  There is a particular "frameworks" pattern that I can't figure out how to port over correctly:

``` json
  "frameworks": {
    "netstandard1.3": {
      "imports": "portable-net452"
    }
``` 

How can I port the "imports" line in particular to the new SDK format?  Can't seem to find any documentation on that.

**Comment by livarcocc** [comment]
Is this what you are referring to:

```
<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.3' ">$(PackageTargetFallback);portable-net452</PackageTargetFallback>
```

**Comment by jaredpar** [comment]
Yes that is the trick.  Is that documented anywhere?

**Comment by dasMulli** [comment]
been using this: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj#imports

**Comment by jaredpar** [comment]
@dasMulli thanks.  That has the reference I was looking for.
