### ISSUE TITLE
Restoring only accounts for depnedency project's nuget dependencies

### ISSUE THREAD

**Issue by am11** [dotnet/sdk#1085]
Consider `A.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>

</Project>
```

is referenced by `B.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="System.Spatial" Version="5.8.2" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include=".\A.csproj" />
  </ItemGroup>

</Project>
```

▶️  Both csprojs are in same directory
*(in my real scenario, they are in same folder and by the virtue of glob pattern, compiling different code files)*

Running `dotnet restore --packages packages B.csproj` results in *only* restoring `newtonsoft.json` in `./packages` directory.

If I remove this part:

```csproj
  <ItemGroup>
      <ProjectReference Include=".\A.csproj" />
  </ItemGroup>
```

then it successfully restores `system.spatial` package from `B.csproj` (but naturally not newtonsoft.json).

> What happens in VS2017

It shows the good old yellow exclamation sign for System.Spatial packages under B.csproj's Dependencies > NuGet node. In old csproj format, it used to mean that "check if the assembly exists at HintPath", but what does that mean in new csproj format where there is no HintPath? Hovering over yellow triangle with exclamation does not yield any information. It took some time to figure out the self-contained steps to repro.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4995
