### ISSUE TITLE
With .Net 5 preview2 installed, the default TargetFramework is "netcoreapp5.0" when creating a Console/Winforms/Wpf project.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#10880]
**Steps to reproduced:**

1. Install SDK 5.0.100-preview.2.20163.4(runtime-5.0.0-preview.2.20160.6).
2. Using CLI, create a Console project.

**Expected Result**
The default target framework is "net5.0".

**Actual Result:**
The default target framework is "netcoreapp5.0" rather than "net5.0"
![image](https://user-images.githubusercontent.com/57380211/76831333-1c5a8700-6862-11ea-9392-505f8f036d94.png)
Note: When retargeting it 5.0 in tfm dropdown list, it will show “net5.0” in the .csproj file.

dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20163.4
 Commit:    b5bccca3f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.2.20163.4\

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.2.20163.4 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.2.20160.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
@donJoseLuis looks like an issue with templates?

**Comment by donJoseLuis** [comment]
@sfoslund thanks for the heads up.
@grinrag can you please take a look & determine if this belongs to the templating repo OR winforms templates?

**Comment by grinrag** [comment]
@sfoslund @donJoseLuis in the templating engine repo, the problem has been fixed already in this [commit](https://github.com/dotnet/templating/commit/a81c58fe2ed74bae89d8984da572fc2e735c192d#diff-9df21fdf0f650f558a7fe79739221839) 

Current template feeds for the Console Application in `release/5-preview2` branch, could be found [here](https://github.com/dotnet/templating/tree/master/template_feed/Microsoft.DotNet.Common.ProjectTemplates.5.0/content/ConsoleApplication-CSharp), the version is correct `net5.0`

**Comment by sfoslund** [comment]
Great, thanks for the heads up. Closing this as fixed.
