### ISSUE TITLE
.NET 5.0 Preview 1 CLI: Template names truncated in console

### ISSUE THREAD

**Issue by Deadpikle** [dotnet/sdk#10885]
### Development environment

* VS 16.4.6
* `5.0.100-preview.1.20155.7` SDK installed

### Description

Running `dotnet new --list` in the console truncates template names when the console is not very wide. This also happens when running a `Process` regardless of the console size. This can make template names unreadable/indistinguishable from one another.

"Wide" console:

```
PS C:\Users\user> dotnet new --list
Templates                                         Short Name               Language          Tags
--------------------------------------------      -------------------      ------------      -------------------
Console Application                               console                  [C#], F#, VB      Common/Console
```

"Skinny" console (will vary based on width)/running in a `Process`:

```
PS C:\Users\user> dotnet new --list
Te...      Short Name               Language          Tags

-----      -------------------      ------------      -------------------
Co...      console                  [C#], F#, VB      Common/Console 
Cl...      classlib                 [C#], F#, VB      Common/Library 
WP...      wpf                      [C#], VB          Common/WPF     
WP...      wpflib                   [C#], VB          Common/WPF
```

### Reproducible Code

https://github.com/Deadpikle/DotnetProcessTesting

I added a flag at the top of `Main` to easily test with a hidden console window and without to see the behavior.

### Expected Behavior

At the very least, if I'm running `dotnet new --list` in a `Process`, the data should never be truncated. I would personally like the template names to never be truncated so that data can always be read, but that may just be me. 😅 

#### Other note

_I wasn't sure if this belonged here or in https://github.com/dotnet/templating. Apologies if this is the wrong repo._

**Comment by sfoslund** [comment]
I don't think that we'll want to change this behavior. There isn't going to be a perfect solution to displaying this information on a small console, no matter what something will be cut off.

**Comment by Deadpikle** [comment]
Hi! Thank you for your time and response.

I'd like to suggest that this is less of a problem with showing information on a small console (we all know wrapping text is a bear to put up with sometimes) and more of a problem of information being left out and not being recoverable without re-running the command. For instance, if I run a console command of any kind and get wrapping text (e.g. `ls -al`) that makes things hard to read, I can just make my console bigger. With `dotnet new`, this is not the case -- the info is gone completely. Furthermore, only the template name column data is truncated; the other columns wrap properly, so I am wondering why the template name column is being treated in a special way. 

`dotnet new --list` on .NET Core 3 does not exhibit this behavior, so this has changed sometime between .NET Core 3 and .NET 5. No other `dotnet` command (e.g. `dotnet new nugetconfig --help`, `dotnet sln [sln name] list`, `dotnet tool list -g`) that I can find exhibits this behavior, either. All other commands wrap text properly and do not truncate text. `dotnet sln [sln name] list`, `dotnet tool list -g` both use similar table formatting to `dotnet new`, yet do not truncate data.

Another simple way to see this not working as expected is to run `dotnet new | cat` on a bash shell (macOS) -- there's no reason the data should be truncated since the raw data is piped into another command, yet no matter the size of my console, the full template names are not available. Of course, there's no reason someone would be piping that data into `cat`, but users could be piping the data into any number of other commands or processes that makes use of the command output.

Some examples where this behavior could be inhibiting to use of `dotnet new`:

* Running `dotnet new --list` in a script (or in any sub-process, as exhibited by my initial report) that parses the output and makes use of it for the user or for whatever purpose
* Any terminal user who runs a command and sees that "whoops, my console was too small and now I have to re-run my command to even begin to read the output" (instead of just increasing the size of their console)

I'd like to suggest that, at the very least, a command line option for no data/template name truncation be added to support the above use cases, the first of which I am using for one of my .NET projects.

Thanks again for your time. Please let me know if I should post this to the [templating repository](https://github.com/dotnet/templating) instead for discussion there.

**Comment by Deadpikle** [comment]
After some more digging, I found that this is currently intentional behavior (see https://github.com/dotnet/templating/pull/2270, https://github.com/dotnet/templating/issues/361). I didn't find these PRs when researching this earlier. Thus, this is an issue with the templating repo and not the SDK repo. (Specifically, running `dotnet new` in a subprocess being truncated is caused by this line: https://github.com/dotnet/templating/blob/master/src/Microsoft.TemplateEngine.Utils/EngineEnvironmentSettings.cs#L105)

I apologize for posting this in the wrong place. I will close this and re-post with more context for discussion in the templating repo.

**Comment by sfoslund** [comment]
@Deadpikle sounds good, thanks for all your work and investment on this issue.
