### ISSUE TITLE
dotnet cache fails with error Unable to find resolved path for 'coreclr' on OSX

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1089]
I'm running dotnet-cache with the following command
```
dotnet cache -e Microsoft.AspNetCore.All.csproj -f netcoreapp2.0 -r osx-x64 -o .out --framework-version 2.0.0-preview1-001913-00 --working-dir .work
```
and I see the error:
```
/Users/jtluo/.dotnet/sdk/2.0.0-preview1-005724/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.CrossGen.targets(49,5): error : Unable to find resolved path for 'coreclr'. [/Users/jtluo/Documents/workspace/juntaoluo/MetaPackages/src/Microsoft.AspNetCore.All/Microsoft.AspNetCore.All.csproj
```

Similar commands work on Ubuntu and Windows so I'm not sure what's the problem here.

dotnet version: 2.0.0-preview1-005724
shared framework: 2.0.0-preview1-001913-00

cc @eerhardt @ramarag @gkhanna79

**Comment by eerhardt** [comment]
`-r osx-x64`, we don't support this RID yet.  We don't have core-setup building portable OSX yet.

Please use `-r osx.10.12-x64` instead.

**Comment by JunTaoLuo** [comment]
When will `osx-x64` be added?

**Comment by eerhardt** [comment]
@gkhanna79 is working on it now.  https://github.com/dotnet/core-setup/pull/1965
