### ISSUE TITLE
Solution build succeeds even though project build fails

### ISSUE THREAD

**Issue by oliverhanappi** [dotnet/sdk#10895]
**Description**

Building a solution with `dotnet build` sometimes succeeds even though some projects are failing.

**Steps to reproduce**

* Download [Repro.zip](https://github.com/dotnet/sdk/files/4348370/Repro.zip)
* Extract the contents to a folder
* Start a command prompt in that folder
* Run `dotnet build`

The output is as follows, dotnet build exists with exit code 0.

```
C:\Temp\Repro> dotnet build
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 132,62 ms for C:\Temp\Repro\Project1\Project1.csproj.
  Restore completed in 132,62 ms for C:\Temp\Repro\Project2\Project2.csproj.
  Project2 -> C:\Temp\Repro\Project2\bin\Debug\netcoreapp3.1\Project2.dll
C:\Temp\Repro\Project2\Project2.csproj(8,5): error : Fail
  Project1 -> C:\Temp\Repro\Project1\bin\Debug\netcoreapp3.1\Project1.dll

Build succeeded.

C:\Temp\Repro\Project2\Project2.csproj(8,5): error : Fail
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.26
```

If you run `dotnet build Project2\Project2.csproj`, the build fails correctly.

```
C:\Temp\Repro> dotnet build Project2\Project2.csproj
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 40,25 ms for C:\Temp\Repro\Project2\Project2.csproj.
  Project2 -> C:\Temp\Repro\Project2\bin\Debug\netcoreapp3.1\Project2.dll
C:\Temp\Repro\Project2\Project2.csproj(8,5): error : Fail

Build FAILED.

C:\Temp\Repro\Project2\Project2.csproj(8,5): error : Fail
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.91
```

**Hints**

The order of projects in the solution file matters. If Project2.csproj would be placed first, building the solution would fail.

This issue has been reproduced with .NET Core SDK 3.1.200.

**Comment by sfoslund** [comment]
This looks like a symptom of microsoft/msbuild#4294. Closing this issue in favor of that one.
