### ISSUE TITLE
No checksum is produced

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#10892]
Due to https://github.com/dotnet/arcade/pull/4827

and Target name conflicts. We need to move to arcade checksum

**Comment by sfoslund** [comment]
It looks like @mmitche was working on [moving us to arcade checksums](https://dev.azure.com/dnceng/internal/_git/dotnet-installer/commit/bbec23f976c896dbcb1ae8e63a165d9b967510cf?refName=refs%2Fheads%2Fgenerate-checksums-using-new-arcade-task) a few weeks ago, is that change ready to check in?

**Comment by mmitche** [comment]
https://github.com/dotnet/installer/pull/6993

**Comment by sfoslund** [comment]
Fixed by dotnet/installer#6993
