### ISSUE TITLE
Problem like common error NETSDK1099:

### ISSUE THREAD

**Issue by SourceSkyBoxer** [dotnet/sdk#10909]
Hello everyone, 

I am very disappointed because I have to use DotNet 3.1 but it shows always crazy like not support for single executable. That is really dreadfully.
![image](https://user-images.githubusercontent.com/57066679/77018467-e3173980-697d-11ea-9a5c-460e722db7f1.png)
Why do i should understand hard?

I have tried to type like simple:
"dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true

// EDIT:
For csproj file
like this:
add 2 lines 
And save it than try:
dotnet publish -c Release -r linux-x64
result: Nor errors. Successfully! But I don't understand why do they not use "-p:PublishSingleFile -p:PublishTrimmed" than it throws error like I have shown about common error.

I can't expect that. I have yesterday successfully. Now it happens.
I am using Ubuntu 18.04.4, dotnet 3.1.2x and dotnet 5 preview 1.... 

Thanks!

**Comment by wli3** [comment]
This issue was moved to dotnet/runtime#34712

**Comment by SourceSkyBoxer** [comment]
Ok I will check out. If you have proof to resolve of problem. Thank you for notification! I will check later.

**Comment by swaroop-sridhar** [comment]
@SourceSkyBoxer are you trying to publish a library as a single file? 
That's not supported. 

`PublishSingleFile=true` requires 
* `targetframework=` `netcoreapp3.0` or `netcoreapp3.1`, 
* `OutputType=Exe`
* `UseApppHost=true`

**Comment by KutuluMike** [comment]
What is the right way to use this when building a multi-project solution? I have one netstandard project and one netcoreapp3.1 project in the solution, and I'm building in an Azure CI pipeline. How can I tell the dotnet publish task to only apply the property to the project where it's allowed?

**Comment by swaroop-sridhar** [comment]
KutuluMike you can add the `<PublishSingleFile>true</PublishSingleFile>` property to only the netcoreapp3.1 EXE project file.
