### ISSUE TITLE
Regression in 3.1.200 for dotnet test -t

### ISSUE THREAD

**Issue by mareklinka** [dotnet/sdk#10926]
Hello all. I seem to have stumbled upon a rather weird possible regression after I migrated from SDK 3.1.102 to 3.1.200.

**Context**
A few days ago I forked the VSCode extension [formulahendry/vscode-dotnet-test-explorer](https://github.com/formulahendry/vscode-dotnet-test-explorer) and started playing around with bringing it up to speed for Core SDK 3.1 and doing some other changes. For testing my changes, I was using the solution I work on at my job.

The extension first discovers possible test projects in a VSCode workspace and then executes `dotnet test -t -v=q [project]` against one project at a time. It waits until the execution terminates and reads the stdout in order to retrieve the list of tests. This list is further processed and displayed etc.

While I was using the SDK 3.1.102, everything was working perfectly here. The command produced the list of tests every time without issues. However, after I updated to SDK 3.1.200, this started failing in more than 50% of executions (but not always).

**The issue**
In SDK 3.1.200, the `dotnet test -t -v=q [project path]` terminates but it looks like the stdout is not properly flushed. The extension reads the stdout and only  gets as far as
```
Test run for [pathToDll](.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
```
And that's it. No tests are listed in the stdout (even though they are there, of course). If I run the same command from the command line, the output is complete (with tests), but there is an observable pause between outputting `The following Tests are available:` and the actual list of tests.

To verify the regression theory, I introduced a global.json and used it to fix a specific SDK version for the solution in question. The results are consistent - 3.1.102 works every time, 3.1.200 fails more often then not.

Since the problem does not manifest every time, it feels like a possible race condition to me. If the `dotnet` process terminates too quickly, the stdout isn't flushed completely and whatever is in the buffer gets lost. But it's really just a theory.

**The problematic code**
``` ts
function executeDotnetTest(testDirectoryPath: string, dotnetTestOptions: string): Promise<string> {
    return new Promise((resolve, reject) => {
        Logger.Log(`Executing dotnet test -t -v=q in ${testDirectoryPath}`);

        let buffer = "";

        const p = cp.spawn("dotnet", ["test", "-t", "-v=q" ], { cwd: testDirectoryPath });
        p.stdout.on("data", (data) => buffer += data.toString());
        p.on("close", (code) => {
            if (code !== 0) {
                Logger.LogError(`Error while executing dotnet test -t -v=q`, code);

                reject();
            }

            Logger.Log(buffer);

            resolve(buffer);
        });
    });
}
```
Now I'm not the greatest with Node.js but this should work and does work when using the older SDK. It spawns a new process with the necessary parameters, hooks to the stdout to build a buffer, then, when the process closes all its IO streams, logs the buffer and resolves the promise.

More details: the projects in question use xUnit for testing framework, but it also reproduces with MSTest.

**Question**
Can someone please try and clarify what's going on here? Or possibly offer a workaround?

**Comment by mareklinka** [comment]
Ok, after digging more deeply into what is happening here, I managed to dig up this. Each of the failed `dotnet` executions end up with the following error:

```
Error while executing dotnet test -t -v=q - Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Failed to load the dll from [c:\Users\marek\AppData\Roaming\Code\User\globalStorage\ms-vsliveshare.vsliveshare\dotnet-3.1.1\host\fxr\3.1.1\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\marek\AppData\Roaming\Code\User\globalStorage\ms-vsliveshare.vsliveshare\dotnet-3.1.1\host\fxr\3.1.1\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

This looks like VS Code's Live Share extension is getting in the way for some reason. It packs it's own runtime? And that runtime is still 3.1.1xx, which is causing issues. Would there be a way to bypass this interference?

**Comment by franck-schmidlin** [comment]
I've hit a similar issue which I was only able to resolve by removing the live share extension :-(

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2392
