### ISSUE TITLE
Resource designer files generated are incompatible with netstandard

### ISSUE THREAD

**Issue by emgarten** [dotnet/sdk#1092]
Resource designer files generated are incompatible with netstandard if a desktop framework is included first in the ``TargetFrameworks`` list.

### Steps
1. Create a new netstandard library with VS 2017
1. Add a resource file to the project
1. Change ``$(TargetFramework)=netstandard1.3`` to ``$(TargetFrameworks)=net45;netstandard1.3``
1. Right click on the resource file and select ``Run Custom Tool``
1. Rebuild

### Expected
The project will build

### Actual 
The project fails to build with an error about being unable to find the ``Assembly`` property.

### Observation

When a desktop framework is first in the list of target frameworks the designer file is generated incorrectly for netstandard.

``.GetTypeInfo()`` is missing from the designer file:

```global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary12.Resource1", typeof(Resource1).Assembly);```

Using netstandard only you would get:

```global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary12.Resource1", typeof(Resource1).GetTypeInfo().Assembly);```

### Workaround
Using ``$(TargetFrameworks)=netstandard1.3;net45`` instead of ``$(TargetFrameworks)=net45;netstandard1.3`` generates the correct file.

**Comment by livarcocc** [comment]
@srivatsn Is this done by the project system?

**Comment by phatcher** [comment]
Managed to make this work by introducing the extension attribute and a minor shim - posted here for reference...

```
namespace System.Runtime.CompilerServices
{
#if NET20
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Method)]
    internal sealed class ExtensionAttribute : Attribute { }
#endif
}
```
and
```
namespace System.Reflection
{
#if NET20 || NET35
    internal static class TypeExtensions
    {
        public static Type GetTypeInfo(this Type type)
        {
            return type;
        }
    }
#endif
}
```
Won't work for all scenarios but at least allows the resource files to compile

**Comment by livarcocc** [comment]
@Pilchie is this a project system issue?

**Comment by Pilchie** [comment]
It's a general problem.  Most of VS is still completely unaware of the concept of multi-targeting, and the default VS APIs just return the first TFM as the TFM of the project.

In this case, I think the resx designer uses the "Design Time Assembly Resolution" to look at what things resolve in the project.

**Comment by Pilchie** [comment]
project-system is probably the best place.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/project-system#3366
