### ISSUE TITLE
Cannot debug Service Fabric service from Visual Studio: Could not execute because the specified command or file was not found

### ISSUE THREAD

**Issue by abatishchev** [dotnet/sdk#10928]
I'm having a Service Fabric service which is a .NET Core 3.1 DLL:

```xml
<EntryPoint>
  <ExeHost IsExternalExecutable="true">
    <Program>dotnet</Program>
    <Arguments>ResourceProviderService.dll</Arguments>
    <WorkingFolder>CodePackage</WorkingFolder>
    <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="1024" />
  </ExeHost>
</EntryPoint>
```

I can:

- Run it as `ResourceProviderService.exe`
- Run it as `dotnet.exe ResourceProviderService.dll`
- Debug it from VS as console app
- Deploy it from VS to local cluster (right click -> Publish)
- Deploy it from VS to remote cluster

I cannot:

Debug it from VS by pressing F5 as Service Fabric application project. Getting an error at C:\SfDevCluster\Data\_App\_Node_0\ResourceProviderApplicationType_App1\log:

>Could not execute because the specified command or file was not found.Possible reasons for this include:
	  * You misspelled a built-in dotnet command.
	  * You intended to execute a .NET Core program, but dotnet-ResourceProviderService.dll does not exist.
	  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

VS Debug window logs:

>The program '[22268] dotnet.exe' has exited with code 1 (0x1).

Service Fabric ETW logs:

>MainEntryPoint:EntryPointDescription { EntryPointType = ExeExecutable = ExeEntryPointDescription { IsExternalExecutable = true, Program = dotnet, Arguments = Microsoft.Eds.Cdp.ResourceProviderService.dll, WorkingFolder = CodePackage, PeriodicIntervalInSeconds = 0 ConsoleRedirectionEnabled = true ConsoleRedirectionFileRetentionCount = 5 ConsoleRedirectionFileMaxSizeInKb = 1024 }} terminated with exitcode 1. CodePackageInstanceIdentifier { ServicePackageInstanceId = ResourceProviderServiceApplicationType_App89:ResourceProviderServicePkg@89761155-9f27-4761-bbb1-c432bf117f03@30cbbfd5-d15a-40ed-bcbd-b964f3790a11, CodePackageName = Code }:132291256667167161

Because I'm having **Application Debug Mode = Refresh Application** (selected by default):

![image](https://user-images.githubusercontent.com/351644/77132310-3213ac00-6a1c-11ea-9d19-0dcbabf83447.png)

This mode creates **symlinks** from my solution to c:\SfDevCluster:

![image](https://user-images.githubusercontent.com/351644/77132945-8455cc80-6a1e-11ea-8945-9175e94d24b1.png)

Service Fabric Tools window logs:

```
ApplicationName        : fabric:/ResourceProviderServiceApplication
ApplicationTypeName    : ResourceProviderServiceApplicationType
ApplicationTypeVersion : 1.0.0
ApplicationParameters  : { "ResourceProviderService_ASPNETCORE_ENVIRONMENT" = "Development";
                         "_WFDebugParams_" = "[{
"CodePackageName":"Code",
"CodePackageLinkFolder":"D:\\Projects\\ResourceProvider\\src\\ResourceProviderService\\drop\\Debug\\ResourceProviderService\\netcoreapp3.1",
"ConfigPackageName":"Config",
"ConfigPackageLinkFolder":"D:\\Projects\\ResourceProvider\\src\\ResourceProviderService\\PackageRoot\\Config","
DataPackageName":null,
"DataPackageLinkFolder":null,
"LockFile":"D:\\Projects\\ResourceProvider\\drop\\Debug\\ResourceProviderService\\netcoreapp3.1\\_VS_ServiceFabric_lock.txt",
"WorkingFolder":"D:\\ResourceProviderProject\\src\\ResourceProviderService",
"ServiceManifestName":"ResourceProviderServicePkg",
"EntryPointType":"Main",
"DebugExePath":null,
"DebugArguments":null,
"DebugParametersFile":"D:\\Projects\\ResourceProvider\\src\\ResourceProviderService\\drop\\Debug\\ResourceProviderService\\netcoreapp3.1\\_VS_ServiceFabric_debug.txt"
}]"; }

Create application succeeded.

Finished executing script 'Publish-NewServiceFabricApplication'.
Time elapsed: 00:00:01.6155897
Started executing script 'Get-ServiceFabricApplicationStatus'.
powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command "[void](Connect-ServiceFabricCluster); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Get-ServiceFabricApplicationStatus -ApplicationName 'fabric:/ResourceProviderServiceApplication' -ErrorAction Stop"
The application has started.
Service Status:
fabric:/ResourceProviderServiceApplication/ResourceProviderService is ready.
```

As soon as I change **Application Debug Mode = Remove Application**:

![image](https://user-images.githubusercontent.com/351644/77132502-f6c5ad00-6a1c-11ea-83a2-ba40d50062a4.png)

It works just fine.

#### .NET Core:

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

#### Visual Studio:

```
Microsoft Visual Studio Enterprise 2019
Version 16.5.0
VisualStudio.16.Release/16.5.0+29911.84
Microsoft .NET Framework Version 4.8.03752

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio
```

#### Service Fabric:

```
7.0.466.9590
4.0.466.9590
```

/cc @masnider @dbreshears

**Comment by ravipal** [comment]
It is a known bug RDBug 15360555 with Framework Dependent Deployment and the current workaround is to not use Refresh Mode. 

In "Aplication Refresh" debug mode, the code package is created with symblink folder that points to the source code's bin location. When the service is started using "dotnet Stateless.dll", dotnet was not able to locate the Stateless.dll and hence the service failed to start. To debug set the environment variable "COREHOST_TRACE=1" in service manifest and redirect the output to a log file and the log file will have 
--- Executing in muxer mode...
Using the provided arguments to determine the application to execute.
Application 'Stateless1.dll' does not exist.

**Comment by wli3** [comment]
Close per email: "I don’t believe this is related to dotnet and it is something to do with how Service Fabric locates the assembly file."
