### ISSUE TITLE
With .Net 5 preview2 installed, the default TargetFramework is net5.0 when creating a class library project.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#10930]
**Steps to reproduced:**

Install SDK 5.0.100-preview.2.20169.1(runtime-5.0.0-preview.2.20160.6).
Using CLI, create a class library project.

**Expected Result**
The default target framework is "netstandard2.0".

**Actual Result:**
The default target framework is "net5.0" rather than "netstandard2.0".
![image](https://user-images.githubusercontent.com/57380211/77143755-0564a080-6abf-11ea-8eea-2c4041716407.png)

Note: For dotnet new classlib "-f" option, the default target framework for the project is netstandard2.0.
![image](https://user-images.githubusercontent.com/57380211/77144005-b66b3b00-6abf-11ea-90c0-b2fe8ef6ab05.png)

Dotnet –info:
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.2.20169.1
 Commit:    0d8d4288ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.2.20169.1\

Host (useful for support):
  Version: 5.0.0-preview.2.20160.6
  Commit:  d12f79a4d1

.NET Core SDKs installed:
  5.0.100-preview.2.20169.1 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ViktorHofer** [comment]
The default target framework for libs in net5.0 and going forward is net5.0.

**Comment by yunwei00q** [comment]
Classlibs defaulting to net5.0 through CLI for .NET SDK 5.0.100-preview.2.20175.2
![image](https://user-images.githubusercontent.com/57380211/77743743-7d007580-7053-11ea-8f61-299010d94969.png)
