### ISSUE TITLE
Error - Changes committed to remote repository but deployment to website failed. ; error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.

### ISSUE THREAD

**Issue by evavargas** [dotnet/sdk#10939]
Issue Type: Bug

the enviroment path for dotnet is: C: \ Program Files \ dotnet \ and there is not another enviroment var configured for dotnet neither sdk installed ... I don't know why take the disc D if no there relation.
I dont know if the problem is with azure, with dotnet, or what.
Is possible install the same SDK in both Disks?
Help me please.

------------------------- Whit file global.json configured to sdk 3.0.103:
C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>dotnet --info
SDK de .NET Core (reflejando cualquier global.json):
Version: 3.0.103
Commit: b7ef045669

Entorno de tiempo de ejecución:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.0.103\

Host (useful for support):
Version: 3.0.3
Commit: c03f2fe626

.NET Core SDKs installed:
3.0.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

-------------------------WhitOUT the file global.json configured to sdk 3.0.103:
C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>dotnet --info
SDK de .NET Core (reflejando cualquier global.json):
Version: 3.0.103
Commit: b7ef045669

Entorno de tiempo de ejecución:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.0.103\

Host (useful for support):
Version: 3.0.3
Commit: c03f2fe626

.NET Core SDKs installed:
3.0.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

---------------------------------- Try to deploy in Azure
C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git init
Reinitialized existing Git repository in C:/Users/EVA MARIA/Documents/kyt/knowyourteam/Knowurteam.API/.git/

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git add .

C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git commit -m "try to deploy"
[master 43ecbd2] try to deploy
2 files changed, 6 deletions(-)
delete mode 100644 global.json
delete mode 100644 nota.txt

---------------------------- PUSH to Azure THE PROBLEM
C:\Users\EVA MARIA\Documents\kyt\knowyourteam\Knowurteam.API>git push azure master
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 225 bytes | 225.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '43ecbd2852'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
remote: D:\Program Files (x86)\dotnet\sdk\2.2.109\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0. Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [D:\home\site\repository\Knowurteam.API.csproj]
remote: Failed exitCode=1, command=dotnet restore "D:\home\site\repository\Knowurteam.API.csproj"
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://knowurteam.scm.azurewebsites.net:443/knowurteam.git
c66523f..43ecbd2 master -> master

Directorio de D:\

10/03/2020 18:45

Documentos
11/03/2020 17:04 215 get user Inicial.txt
12/03/2020 14:21 IMAGENES
16/03/2020 23:28 javascript
15/02/2020 14:22 Mama
14/03/2020 15:11 pyclases
22/10/2019 11:24 Reserbar
1 archivos 215 bytes
6 dirs 20.542.353.408 bytes libres

VS Code version: Code 1.43.1 (fe22a96, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

**Comment by wli3** [comment]
There is no netcore 3.0 SDK installed on the azure machine. You need to configure your remote machine to have net core 3.0 SDK installed.
