### ISSUE TITLE
With .Net 5 preview2 installed, the default TargetFramework is netcoreapp5.0 when creating Winforms/Wpf project.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#10931]
**Steps to reproduced:**

Install SDK 5.0.100-preview.2.20169.1(runtime-5.0.0-preview.2.20160.6).
Using CLI, create a Wpf project.

**Expected Result**
The default target framework is "net5.0".

**Actual Result:**
The default target framework is "netcoreapp5.0" rather than "net5.0".
![image](https://user-images.githubusercontent.com/57380211/77144679-7d33ca80-6ac1-11ea-91c7-02baef7c0b01.png)

Dotnet –info:
.NET Core SDK (reflecting any global.json):
Version: 5.0.100-preview.2.20169.1
Commit: 0d8d4288ac

Runtime Environment:
OS Name: Windows
OS Version: 10.0.18362
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-preview.2.20169.1\

Host (useful for support):
Version: 5.0.0-preview.2.20160.6
Commit: d12f79a4d1

.NET Core SDKs installed:
5.0.100-preview.2.20169.1 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by ViktorHofer** [comment]
This is expected, the Windows Desktop templates weren't updated for preview2.

**Comment by yunwei00q** [comment]
Repro on .NET 5 Preview 3, is the Windows Desktop templates updated for preview3?

**Comment by wli3** [comment]
It is net5.0 now in master
