### ISSUE TITLE
Cannot run/build/publish applications that are "inside" a WSL directory using dotnet.exe from Windows

### ISSUE THREAD

**Issue by zsr2531** [dotnet/sdk#10936]
Repro steps:

1. Create any project from WSL in a directory like `~/`
2. Try to build it using `dotnet.exe` you have in your Windows installation.
3. It will try to parse the path as a hostname and because it contains `wsl$`, it will recognize it as an invalid URI and refuse to do anything with the project.

(example path that I tried it with:
`\\wsl$\Ubuntu-18.04\home\user1\HelloWorld\HelloWorld.csproj`)

**Comment by wli3** [comment]
We do not support running Windows executable in a Linux environment today. Move to backlog

**Comment by wli3** [comment]
I don't think is a scenario we would support anytime soon, Close this for now. You can create a new feature request if you think otherwise.
