### ISSUE TITLE
Handle the Aliases compile item metadata for PackageReference

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#10947]
SDK side of https://github.com/NuGet/Home/issues/4989. 

Design at https://github.com/NuGet/Home/blob/dev/designs/PackageReference-Extern-Alias.md.

As part of LockFileItem for compile items, the SDK needs to pass through the aliases property to the compiler.

**Comment by wli3** [comment]
@nkolev92 when that needed? looks like there is not much work from SDK, is that true? Would you drive testing?

**Comment by nkolev92** [comment]
There's not much work yeah. 

Whenever possible, 3.1.400 would be nice given we'd need to coordinate 4 changes.

**Comment by nkolev92** [comment]
Fixed by https://github.com/dotnet/sdk/pull/11451
