### ISSUE TITLE
dotnet test does not use the correct .NET Framework runtime - report false test failures

### ISSUE THREAD

**Issue by TalAloni** [dotnet/sdk#10956]
I have created a minimal xUnit test project demonstrating the problem (the test project use the SDK-style csproj, and target **net472**).
VSTest.Console works as expected.
when running the test with **dotnet test**, it will throw the following exception:
System.ArgumentException : The specified value is not valid in the 'SslProtocolType' enumeration.
**This exception is not thrown by .NET Framework 4.7.2**

dotnet SDK version: 3.1.200
Test Execution Command Line Tool Version 16.5.0

Project demonstrating the problem:
[https://github.com/TalAloni/dotnettest-xunit](https://github.com/TalAloni/dotnettest-xunit)

**Comment by TalAloni** [comment]
Update: This problem does not reproduce with MS Test v2, seems to be limited to xUnit

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2391
