### ISSUE TITLE
Using the LD LIBRARY PATH to load local libraries does not work on Linux

### ISSUE THREAD

**Issue by sunliusi** [dotnet/sdk#10957]
I need to use the local library for cross-platform. Local libraries have different implementations and Put them in different folders. 

it work fine in windows just like this:
Environment.SetEnvironmentVariable("PATH", path + ";" + Environment.GetEnvironmentVariable("PATH"));

it's not working in linux just like this:
Environment.SetEnvironmentVariable("LD_LIBRARY_PATH", dir + ":" + Environment.GetEnvironmentVariable("LD_LIBRARY_PATH"));

**Comment by sunliusi** [comment]
NativeLibrary doesn't work either. There are two local libraries, one dependent on the other. This works only if the local library has no dependencies.

var path = Path.Combine(assemblyDirectory, "unix", "test.so");
 var p = NativeLibrary.Load(path);
if (p == IntPtr.Zero)
 {
           throw new ApplicationException("load assembly fail:" + path);
}

 ---> System.DllNotFoundException: Unable to load shared library '/home/sunliusi/ctptest/unix/ftdc2c_ctp.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ./testaa.so: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)

**Comment by SourceSkyBoxer** [comment]
Hello, 
I will tell you example with NativeLibrary()
 ```
       /*
         *  Valid library name for Linux of X11, Extensions, OpenGL and Vulkan
         */
        private const string libX11 = "libX11.so.6";
        private const string libXrender = "libXrender.so.0";
        private static IntPtr handle;

        static XLib()
        {
            // Important instance of TryGetExport()
            handle = NativeLibrary.Load(libX11, typeof(MyClass).Assembly, 0);
        }

        /*
         *  Display *XOpenDisplay(char *displayname);
         */
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate IntPtr _XOpenDisplay(string displayname);
        public static Display XOpenDisplay(string displayname)
        {
            _XOpenDisplay opendisplay_delegate;
            if (NativeLibrary.TryGetExport(handle, "XOpenDisplay", out IntPtr opendisplay))
            {
                opendisplay_delegate = Marshal.GetDelegateForFunctionPointer<_XOpenDisplay>(opendisplay);
            }
            else
            {
                opendisplay_delegate = (string name) => { throw new NotImplementedException("Error: XOpenDisplay not found."); };
            }

            return new Display(opendisplay_delegate(displayname));
        }
```
If you want FullPath like this.
You should use "AppDomain.CurrentDomain.BaseDirectory"
like this:
```
            ...
            string rootdir = AppDomain.CurrentDomain.BaseDirectory;
            handle = NativeLibrary.Load(Path.Combine(rootdir, "unix", "sofile.so"), typeof(YourClass).Assembly, 0);
            ...
```

You should create delegate with UnmanagedFunctionPointer
```
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate IntPtr _XOpenDisplay(string displayname);
```
Than you can try as public method if you try out.
```
        public static Display XOpenDisplay(string displayname)
        {
            _XOpenDisplay opendisplay_delegate;
            if (NativeLibrary.TryGetExport(handle, "XOpenDisplay", out IntPtr opendisplay))
            {
                opendisplay_delegate = Marshal.GetDelegateForFunctionPointer<_XOpenDisplay>(opendisplay);
            }
            else
            {
                opendisplay_delegate = (string name) => { throw new NotImplementedException("Error: XOpenDisplay not found."); };
            }

            return new Display(opendisplay_delegate(displayname));
        }
```

Just it is small example of my made.

I hope my solution helps you as well.

**Comment by sunliusi** [comment]
Thanks @SourceSkyBoxer  for such a detailed explanation.

Follow the example above:
`// multiple so files
            string[] sofiles =
            {
                "file1.so", "file2.so"
            };
            string rootdir = AppDomain.CurrentDomain.BaseDirectory;
            foreach (string sofile in sofiles)
            {
                handle = NativeLibrary.Load(Path.Combine(rootdir, "unix", sofile));
            }` 

The problem is that NativeLibrary.Load will fail when file2.so references file1.so.

If you put file2.so and file1.so in the root directory, there is no problem

**Comment by sunliusi** [comment]
System.DllNotFoundException: Unable to load shared library '.../unix/file2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ./file1.so: cannot open shared object file: No such file or directory

**Comment by wli3** [comment]
This issue was moved to dotnet/runtime#34711

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2390
