### ISSUE TITLE
With .Net 5 Preview, failed to run tool dotnetsay on Mac due to command not found

### ISSUE THREAD

**Issue by yuki233** [dotnet/sdk#10986]
Repro steps-
1. On Mac OS 10.15, install SDK 5.0.100-preview.2.20169.1 & Runtime 2.1.17
2. Run below commands
dotnet tool install -g doTNetsay
dotnet tool list -g
dotnetsay

Actual Result-
Failed to run tool dotnetsay on Mac due to command not found
![image](https://user-images.githubusercontent.com/1578239/77511200-86e77480-6eab-11ea-9709-173545a28f4d.png)

Note-
1. This issue is not repro on Windows 10 and Ubuntu 16.04
2. This issue is not repro with User-built global tool.
3.  This issue is also repro on .Net 5 Preveiw1

**Comment by memark** [comment]
@yuki233 I'll try to reproduce. Where can I find preview 2?

I ran in to a similar issue earlier due to zsh path handling. Try invoking the tool directly with
`~/.dotnet/tools/dotnetsay`

If that works, try the following to confirm
`path+=~/.dotnet/tools`
`dotnetsay`

**Comment by yuki233** [comment]
@memark  This issue is also reproduced with .Net 5.0 Preview 1

Run ~/.dotnet/tools/dotnetsay, dotnetsay works fine
![image](https://user-images.githubusercontent.com/1578239/77603891-2ceabb80-6f4c-11ea-9199-663af1209274.png)

Run below command, dotnetsay works fine
path+=~/.dotnet/tools
dotnetsay
![image](https://user-images.githubusercontent.com/1578239/77603919-370cba00-6f4c-11ea-8199-e15929233b8d.png)

**Comment by memark** [comment]
Then the issue appears to be with zsh. (If you switch to bash, you will probably find that it works.)

From what I can tell this is what happens:
The file `/etc/paths.d/dotnet-cli-tools` is read when the shell spawns, and added to $PATH.
However, it doesn't get resolved and stays as `~/...`. This doesn't work in `zsh`, but does work in `bash`.

When manually adding `~/.dotnet/tools` to $PATH, it gets resolved immediately and ends up as e.g. `/Users/memark/.dotnet/tools` in $PATH, which works in both shells.

So the issue appears to be with `/etc/paths.d/dotnet-cli-tools`.

I also tried replacing the file contents with `$HOME/.dotnet/tools`, but that gives the same problem.

**Comment by dsplaisted** [comment]
@wli3 This looks to be a path expansion issue when setting the path to the tools folder in zsh: https://github.com/dotnet/sdk/issues/10986#issuecomment-604300530

**Comment by wli3** [comment]
If your default shell zsh?

We do have an experience to guide zsh user to add path to `.zprofile` https://github.com/dotnet/cli/pull/11926 when detect the user is using zsh

at the same time:

> Mac don’t have a good solution to put user path for all user (/USERNAME/home/.dotnet/tools is different for different user). We currently adding literal ~/.dotnet/tools for all users. And that works for bash. But it no longer works for zsh.
> 
> At the same time, directly adding new lines to .zprofile is not “idiomatic” for unix. So we can only use existing fallback experience. (bash will have the same experience is you install it via tar.gz).
> 
> I find there are 3 ways you can detect the application is running on zsh. (a)$SHELL (b)$ZSH_NAME and use (c)ps -p $$
> 
> Only (a) can work in a dotnet program. If you run Console.WriteLine(Environment.GetEnvironmentVariable("ZSH_NAME", EnvironmentVariableTarget.Process)); you will get nothing, even when echo $ZSH_NAME can give you the value in the same session. I don’t know why at this moment. (c) won’t work since $$ is “the current process”. It can only work for scripts. However, the downside of $SHELL is, it will only give you the default shell. That means if you run zsh on top of bash, we will not detect that. I verified in macOS 10.15 VM if it has $SHELL set. (after running chsh -s /bin/zsh)

More info in https://github.com/dotnet/sdk/issues/9415

**Comment by memark** [comment]
@wli3, thank you! Seems this has been known for some time. Apparently both @yuki233 and missed the message on modifying our paths. I would suggest giving https://github.com/dotnet/sdk/issues/3992, which addresses the visibility issue, some love.

**Comment by wli3** [comment]
I will consider the issue resolved. If you have more ask please create a more specific issue.
