### ISSUE TITLE
netstandard AssemblyVersion in .csproj file is generating version 0.0.0.0

### ISSUE THREAD

**Issue by weshaggard** [dotnet/sdk#1099]
@JoshClose commented on [Fri Apr 07 2017](https://github.com/dotnet/corefx/issues/18068)

I have a netstandard1.3 project and I have this in the `.csproj` file `<AssemblyVersion>3.0.0.0</AssemblyVersion>`. The version that is set on the generated assembly using `msbuild /t:pack` is `0.0.0.0`. If I put this `[assembly: AssemblyVersion( "3.0.0.0" )]` in the `AssemblyInfo.cs` file, it works fine.

Is this expected behavior or am I doing something wrong?

**Comment by nguerrera** [comment]
@JoshClose The fact that you can put that assembly version in source without getting a duplicate attribute error suggests that assembly info (or at least assembly version) generation has been disabled. Did this project come from a project.json migration when the attribute had previously been supplied in source? In that case, it would have been disabled for you to allow a succesful migration. Can you share the full project that repros this issue?

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper

**Comment by nguerrera** [comment]
https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvHelper.csproj#L24

GenerateAssemblyVersionAttiribute has been set to false. This is therefore the expected behavior. Remove that and the manual source application of the attribute and it will work as you want.

**Comment by JoshClose** [comment]
This is caused from migrating from a `.csproj` file?
