### ISSUE TITLE
Add retry to install script for most of the error

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#11001]
we use `curl --retry 10` but that is not enough for failure like "curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received."

**Comment by jaredpar** [comment]
Is there an ETA for when this is going to be updated? Presently this is causing a 13% failure rate for jobs inside of dotnet/runtime. Most recent data:

Data from today

|Build|Kind|Timeline Record|
|---|---|---|
|[583388](https://dev.azure.com/dnceng/public/_build/results?buildId=583388)|PR https://github.com/dotnet/runtime/pull/34297|Build product|
|[583335](https://dev.azure.com/dnceng/public/_build/results?buildId=583335)|PR https://github.com/dotnet/runtime/pull/33553|Build CoreCLR Runtime|
|[583335](https://dev.azure.com/dnceng/public/_build/results?buildId=583335)|PR https://github.com/dotnet/runtime/pull/33553|Build CoreCLR Runtime|
|[583331](https://dev.azure.com/dnceng/public/_build/results?buildId=583331)|Rolling|Restore|
|[583239](https://dev.azure.com/dnceng/public/_build/results?buildId=583239)|Rolling|Restore|
|[583233](https://dev.azure.com/dnceng/public/_build/results?buildId=583233)|PR https://github.com/dotnet/runtime/pull/33553|Build CoreCLR Runtime|
|[582153](https://dev.azure.com/dnceng/public/_build/results?buildId=582153)|Rolling|Build managed test components|
|[582358](https://dev.azure.com/dnceng/public/_build/results?buildId=582358)|PR https://github.com/dotnet/runtime/pull/33604|Build CoreCLR Runtime|
|[581971](https://dev.azure.com/dnceng/public/_build/results?buildId=581971)|PR https://github.com/dotnet/runtime/pull/33108|Build CoreCLR Runtime|
|[580817](https://dev.azure.com/dnceng/public/_build/results?buildId=580817)|PR https://github.com/dotnet/runtime/pull/34314|Build CoreCLR Runtime|
|[581803](https://dev.azure.com/dnceng/public/_build/results?buildId=581803)|Rolling|Override CoreCLR from live drop|
|[581493](https://dev.azure.com/dnceng/public/_build/results?buildId=581493)|PR https://github.com/dotnet/runtime/pull/34125|Build product|
|[581523](https://dev.azure.com/dnceng/public/_build/results?buildId=581523)|Rolling|Override CoreCLR from live drop|

Evaluated 100 builds
Impacted 12 bulids
Impacted 13 jobs

> runfo search-timeline -d runtime -c 100 -pr -v "Failed to install dotnet" -m

**Comment by wli3** [comment]
@DonJoseLuis

**Comment by donJoseLuis** [comment]
@jaredpar we took over the script and are on the case.  We'll offer updates here.  I appreciate your summary of the issue's impact.

**Comment by donJoseLuis** [comment]
@grinrag is preparing a PR with added resiliency.
