### ISSUE TITLE
Don't include operating system info from TargetFramework in runtimeconfig.json `tfm`

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11010]
Per discussion in dotnet/runtime#34033, we will probably want to update how we write the `tfm` value in runtimeconfig.json so that it excludes the operating system and version information which may be in the `TargetFramework`.

**Comment by wli3** [comment]
Should be blocked by nuget understanding `net5.0-ios14`

**Comment by wli3** [comment]
Once https://github.com/NuGet/NuGet.Client/pull/3339/files flow to sdk. We can work on that
