### ISSUE TITLE
Object is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Foxtrek64** [dotnet/sdk#11021]
I hope this is the right place for this issue. I couldn't decide between here and Roslyn.

I have a NetStandard 1.4 project. After adding a reference to `System.Activities`, I received the following error in VS:

`The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b775c561934e089'.`

It is worth noting that removing the reference to `System.Activities` resolves this issue, but this is a non-answer seeing as this project creates activities for WF.

Things I have tried (in no particular order):

1. Add a reference in the csproj to mscorlib, both with and without a HintPath
2. Cross-target net4.6.1 and netstandard1.4 (in both orders)
3. Delete obj and bin folders, rebuild
4. Delete obj and bin folders, `dotnet restore`
5. Rebuild by itself
6. Clean and rebuild
7. `dotnet restore` by itself.
8. Delete the project and rebuild it

When building on the command line, I get the same results. When I have a hint path to the mscorlib reference assembly for 4.6.1, building on the command line spits out 531 errors, starting with how several types exist both in `mscorlib` and `System.Runtime`. This behavior is reflected in VS.

When I remove the HintPath, I get a warning that it could not locate the mscorlib assembly and I get error messages stating that that I need to add a reference. Removing the reference entirely removes the warning but I get the same set of errors.

I've been fighting this issue for a couple of days now and I've honestly tried everything I can think of, including consulting with others in the C# Discord to no avail.

**Comment by Foxtrek64** [comment]
Found my solution. `System.Activities`, or any ref assemblies for that matter, are not available to netstandard. I'm splitting off the files that rely on `System.Activities` into a new project now.

**Comment by 333fred** [comment]
To be clear, it's not _any_ ref assemblies. It's ref assemblies that do not target your target framework. The `System.Activities` ref assembly is for the .NET Framework, not .NET Standard, and thus cannot be referenced from a .NET Standard project.
