### ISSUE TITLE
SDK 3.1.20x: MSBuild problem with external classes accessed via reflection

### ISSUE THREAD

**Issue by danielpalme** [dotnet/sdk#11043]
Starting with SDK 3.1.200 I experienced the following MSBuild issue:

When you instantiate classes within a MSBuild task from an external assembly via reflection those types don't behave as expected.  
The issue only appears via MSBuild.

Here's a sample project: [MSBuildTaskDemo.zip](https://github.com/dotnet/sdk/files/4399590/MSBuildTaskDemo.zip)

Just execute `run.bat` to reproduce the issue.

If you change `global.json` to an older SDK version, everything works as expected: 
```json
{
  "sdk": {
    "version": "3.1.100"
  }
}
```

**Comment by dsplaisted** [comment]
@rainersigwald Does this sound like an AssemblyLoadContext issue?

**Comment by marcpopMSFT** [comment]
Closing old issues, please reactivate if this is still a problem.

**Comment by dsplaisted** [comment]
This still repros.  I'm not sure if tasks are supposed to be using `Assembly.LoadFrom` (which is probably related to the load failure) or if there's somethnig better to do.
