### ISSUE TITLE
RESX strongly typed labels not available until after project reloaded 

### ISSUE THREAD

**Issue by agrothe** [dotnet/sdk#1104]
Issue: In order to use strongly typed resource labels, I have to unload/reload my project in order to get access to newly created strings.

Reproduce:

1. Visual Studio 2017 -> New Project -> .NET Core -> Class Library(.NET Core)
2. Target Framework is .NETCoreApp 1.1
3. Add a resource file and add a new string resource named TestMessage.
4. Right click resource file -> run custom tool and any combination of clean, build, rebuild
4. In the default Class1, typing `Resource1.TestMessage` is invalid.
5. Unload/Reload project
6. In Class1, `Resource1.TestMessage` is now valid.
7. Rinse, repeat

Unsure if related to:
#94

**Comment by livarcocc** [comment]
This issue was moved to dotnet/project-system#1948
