### ISSUE TITLE
Why Visual Studio 2017 modifies csproj file while adding files/folders?

### ISSUE THREAD

**Issue by SirwanAfifi** [dotnet/sdk#1105]
I'm using Visual Studio Community 2017 - Version 15.1 (26403.0), whenever I build the project newly added files or folders will be added to to `.csproj` file as some item groups:
```

<ItemGroup>
    <Folder Include="Views\Shared\Components\MyComponent\Edit\" />
     .....
</ItemGroup>
```

Is this modification necessary? Why they should be there? How to prevent Visual Studio to add these tags?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/project-system#1949
