### ISSUE TITLE
Question: How to remove a package's assembly from a build?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sdk#1106]
Hi

I have a weird situation. My project depends on two packages that contain slightly different versions of the same assembly which is causing build conflicts because of duplicate types. I'd like to remove the assembly from one of the packages from the build to solve the conflicts. How do I do that using MSBuild?

I attempted to use the target below but because the assemblies have the same name they were both removed. How do I pick the one to remove by the NuGet package name?

```
  <Target Name="WorkAroundPackageAndProjectReferenceConflict" BeforeTargets="ResolveLockFileReferences">
    <ItemGroup>
      <ResolvedCompileFileDefinitions Remove="@(ResolvedCompileFileDefinitions)" Condition="'%(ResolvedCompileFileDefinitions.FileName)' == 'MyAssemblyFileName'" />
    </ItemGroup>
  </Target>
```

**Comment by davidfowl** [comment]
There's probably metadata on the item though I don't know if that's preserved all the way down to the assembly. Did you run `msbuild /v:diag` to see what all of the properties are?

**Comment by nguerrera** [comment]
I think the conflict resolution we did for netstandard2.0 would just fix this by picking the assembly with the higher version (assuming that's what you want). Does this repro with VS 15.3 Preview1 and https://www.microsoft.com/net/core/preview#windowscmd ?

cc @ericstj @dsplaisted

**Comment by livarcocc** [comment]
I am going to close this for now as ConflictResolution should address this.

if this still reproing, please let us know.
