### ISSUE TITLE
All implicit dependencies provided by sdk, assemblies etc should have IsImplicitlyDefined=True metadata

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/sdk#1107]
If they don't project system does not know that dependency is implicit and can not  restrict certain scenarios like removal for example - they can not be removed.  See issue https://github.com/dotnet/project-system/issues/1250 for more context.

**Comment by livarcocc** [comment]
Reading the linked project-system bug, it does not seem like this issue is needed anymore (nor even comprehensive to treat the bug). So, I am going to close it. If I got this wrong, just comment and I can re-activate it.
