### ISSUE TITLE
Building against .NET Framework 4.5 from VB embeds the runtime

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1108]
VB is embedding the runtime by default when building against .NET Framework (see https://msdn.microsoft.com/en-us/library/bb531259.aspx):

```
1>    C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Roslyn\vbc.exe /noconfig /optionstrict:custom /nostdlib /errorreport:prompt /platform:AnyCPU /rootnamespace:ConsoleApp275 /sdkpath:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" /preferreduilang:en-US /highentropyva+ /vbruntime* /define:"CONFIG=\"Debug\",DEBUG=-1,TRACE=-1,PLATFORM=\"AnyCPU\"" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll","C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll","C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll","C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Drawing.dll","C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.IO.Compression.FileSystem.dll","C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NE
```

I'm not sure when or where we should be embedding it - but for compatibility it's shouldn't be doing for .NET Framework.

**Comment by livarcocc** [comment]
This is where we add it: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.VisualBasic.props#L15.

Is this something that we could safely remove now or should we wait for a major version release, as this would qualify as a breaking change?

cc @nguerrera @dsplaisted

**Comment by nguerrera** [comment]
Goes all the way back to https://github.com/dotnet/sdk/commit/24516577eed218c4fe35f736ab14751a164fd231 (a little tricky to follow renames on GitHub)

@srivatsn Do youy recall why this is Embed by default? Is it required for .NET Core?
