### ISSUE TITLE
Could not load type 'System.IO.Compression.ZipFile' from assembly on docker raspberry pi when publish with Trimmed 

### ISSUE THREAD

**Issue by mwkldeveloper** [dotnet/sdk#11096]
.net Core 3.1.3
**Describe the bug**
Below code can be run on window
But on docker with raspberry pi publish with /p:PublishTrimmed=true, have error:

> Could not load type 'System.IO.Compression.ZipFile' from assembly

**To Reproduce**
Create a WebProject and Use below code then publish with /p:PublishTrimmed=true

```
[HttpGet("logs")]
     public ActionResult GetLog()
     {
         string startPath = @"./data/logs";
         string zipPath = @"./tmp/logs.zip";
         try
         {
             ZipFile.CreateFromDirectory(startPath, zipPath);
             var data = System.IO.File.ReadAllBytes(zipPath);
             var content = new System.IO.MemoryStream(data);
             const string contentType = "application/zip";
             var fileName = $"logs-{DateTime.Now.ToString("yyyyMMddhhmmss")}.zip";
             return File(content, contentType, fileName);
         }
         finally
         {
             System.IO.File.Delete(zipPath);
         }
     }

```

**Comment by dsplaisted** [comment]
@swaroop-sridhar @jeffschwMSFT Could one of you triage this?  It looks like an issue with PublishTrimmed and web apps on raspberry Pi.

**Comment by swaroop-sridhar** [comment]
@sbomer can you please take a look at this issue? Thanks.
CC:

**Comment by leung85** [comment]
> @swaroop-sridhar @jeffschwMSFT Could one of you triage this? It looks like an issue with PublishTrimmed and web apps on raspberry Pi.

Yes if not trimmed ,it works normal.

**Comment by stonstad** [comment]
I'm seeing this behavior with /p:PublishSingleFile=true --self-contained true as well.  Is there a work-around if I am determined to ship as a single file?

**Comment by vitek-karas** [comment]
@stonstad - are you trimming the application? If not, can you share some kind of a repro or some other way for us to try to get to the root of the problem.

**Comment by stonstad** [comment]
Hi Vitek.  Thanks for reaching out.  It turns out the problem was caused by an assembly being moved during an update process.  This is resolved, thank you!

________________________________
