### ISSUE TITLE
DeterministicSourcePaths doesn't take NuGet source packages into account

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sdk#11105]
**Version Used**: 5.0p1

**Steps to Reproduce**:

1. Create a class library
2. Add a package reference to xunit.assert.source
3. `ContinuousIntegrationBuild`

**Expected Behavior**:
A source root should be created for the NuGet source package and the path to the source normalized/deterministic. 

**Actual Behavior**:
The source paths for the source package point to the NuGet directory and are not deterministic.

Possible solution:
NuGet has a variable for its package root. We can add a SourceRoot for that and that'd cover all source packages under that root:

```xml
  <ItemGroup>
    <SourceRoot Include="$(NuGetPackageRoot)" Condition="'$(NuGetPackageRoot)' != ''" />
  </ItemGroup>
```

**Comment by dsplaisted** [comment]
We think we can do this by including the following in the generated NuGet .props files:

```xml
<ItemGroup>
  <SourceRoot Include="$(NuGetPackageFolders)" />
</ItemGroup>
```

**Comment by clairernovotny** [comment]
Moved to https://github.com/NuGet/Home/issues/9431
