### ISSUE TITLE
PreserveCompilationContext not working with netcoreapp2.0

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/sdk#1111]
I have
```<PreserveCompilationContext>true</PreserveCompilationContext>```
in my csproj, when I compile for .netcoreapp1.1 everything works fine, but if I try netcoreapp2.0 it doesn't seem to work.
I get an exception:
Can not find compilation library location for package 'microsoft.netcore.app''

originally posted:
https://github.com/dotnet/coreclr/issues/10849

**Comment by danwalmsley** [comment]
This is my csproj

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-preview1-001915-00</RuntimeFrameworkVersion>
    <OutputTypeEx>exe</OutputTypeEx>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RuntimeIdentifiers>win7-x64;ubuntu.14.04-x64;debian.8-x64;osx.10.12-x64</RuntimeIdentifiers>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <PackageTargetFallback>$(PackageTargetFallback);netstandard1.3;net40</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by danwalmsley** [comment]
This is the effected project:

https://github.com/VitalElement/AvalonStudio/tree/dotnet-debugging

**Comment by livarcocc** [comment]
Can you try with the latest Cli/SDK? Also, on the latest CLI, you don't need to specify the RuntimeFrameworkVersion anymore, that's implicitly updated to the runtime the CLI is using.

I believe I saw some comments about this being a problem with CoreCLR that was fixed in Version 1919 of the Runtime. The latest CLI carries 1960.

**Comment by Liriel** [comment]
How do I determine the CLi version?
`dotnet --version` gives: **2.0.0-preview1-005753**

**Comment by livarcocc** [comment]
@mlorbetske @Eilon can you guys help in the web case?

**Comment by Eilon** [comment]
This looks like the issue @mlorbetske saw recently but didn't repro with newer builds.

@pakrym took a look at this but I don't think we knew what caused it.

Ultimately we kind of ignored this because the issue went away...

**Comment by mlorbetske** [comment]
@Eilon the issue has not gone away. This seems to work with shared framework builds 1919, 1957 and 1967 but not 1913, 1915, 1951 or 1961. If you have one of the working ones, you can work around this by adding <RuntimeFrameworkVersion>{the full version number of the shared framework}</RuntimeFrameworkVersion> to the project file for the time being.

**Comment by pakrym** [comment]
I was able to repro this time. It's https://github.com/dotnet/core-setup/issues/624 and getting fixed in https://github.com/dotnet/core-setup/pull/2039 . DependencyModel don't know about `additionalProbingPaths` in `.runtimeconfig.dev.json` and `microsoft.netcore.app` is inside `NuGetFallbackFolder` that is not checked by it.

**Comment by eerhardt** [comment]
Note that fallback folders weren't used by default until https://github.com/dotnet/cli/pull/6209 was checked in.  Now they are used by the "first run"/"offline" experience in the command line.

**Comment by danwalmsley** [comment]
@livarcocc regarding not needing to specify <RuntimeFrameworkVersion> any more, this seems to be true when I build it from command line, but not when using VS2017, when I take it out I get errors like this:

```
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error : Unexpected dependency 'Microsoft.NETCore.App' with no version number.
```

any way to make vs use the new cli?

**Comment by livarcocc** [comment]
@danwalmsley Not yet. We are working on making updating the CLI also update some of the bits in VS. Meanwhile, is this working for you now with the latest CLI?

**Comment by livarcocc** [comment]
I believe we got this working again now. Please re-activate if you still hit it.
