### ISSUE TITLE
Relative paths using dotnet build and WebPublishMethod fail

### ISSUE THREAD

**Issue by Ascathor** [dotnet/sdk#11124]
Hello everyone, 

following background.
I'm building and deploying a dotnet 3.1.201 application using dotnet cli to an Azure WebApp.

The following file is my pubxml, which is obviously omitted:
```
<?xml version="1.0" encoding="utf-8"?>
  <!--
   This file is used by the publish/package process of your Web project. You can customize the behavior of this process
   by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121.
  -->
  <Project ToolsVerion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
      <WebPublishMethod>MSDeploy</WebPublishMethod>
      <LastUsedBuildConfiguration />
      <LastUsedPlatform>Any CPU</LastUsedPlatform>
      <SiteUrlToLaunchAfterPublish />
      <LaunchSiteAfterPublish>False</LaunchSiteAfterPublish>
      <ExcludeApp_Data>False</ExcludeApp_Data>
      <TargetFramework>netcoreapp3.1</TargetFramework>
      <ProjectGuid>a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6</ProjectGuid>
      <SelfContained>false</SelfContained>
      <_IsPortable>true</_IsPortable>
      <MSDeployServiceURL>https://foo.bar:443</MSDeployServiceURL>
      <DeployIisAppPath>foo.bar</DeployIisAppPath>
      <RemoteSitePhysicalPath />
      <SkipExtraFilesOnServer>False</SkipExtraFilesOnServer>
      <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
      <EnableMSDeployBackup>True</EnableMSDeployBackup>
      <AllowUntrustedCertificate>True</AllowUntrustedCertificate>
      <UserName>$foo.bar</UserName>
      <CreatePackageOnPublish>true</CreatePackageOnPublish>
      <_DestinationType>AzureWebSite</_DestinationType>
    </PropertyGroup>
  </Project>
```

This file is saved in folder:
(project root)\src\Project.Subproject\Properties\PublishProfiles\Release

Taking this into account, please consider the following:
This command does NOT work:
```
PS> dotnet build ".\src\Project.Subproject\Project.Subproject.csproj" -c Release /p:WebPublishMethod="MSDeploy" /p:DeployOnBuild=True /p:PublishProfile="Release" /p:Password="(password)"
```
Error: Please provide MSDeployServiceURL.

The following command WORKS:
```
PS> dotnet build ".\src\Project.Subproject\Project.Subproject.csproj" -c Release /p:WebPublishMethod="MSDeploy" /p:DeployOnBuild=True /p:PublishProfile="src\Project.Subproject\Properties\PublishProfiles\Release.pubxml" /p:Password="(password)"
```

If I, for some reason, remove /p:WebPublishMethod="MSDeploy", it works, too.
```
dotnet build ".\src\Project.Subproject\Project.Subproject.csproj" -c Release /p:DeployOnBuild=True 
/p:DeployTarget=MSDeployPublish /p:PublishProfile="Release" /p:Password="(password)"
```

I was able to verify this with a different .pubxml file that does not require Azure, but deploys onto a local test IIS. 

Having used --verbosity diag to further analyse, it seems it can not load up the Release.pubxml as soon as I provide WebPublishMethod. Granted, it does not deploy after build. Using DeployTarget however works fine, even if I can not use it to deploy into Azure.

Is this intended behavior or a bug ?
If you require more informations, please state so.
  
```
  PS > dotnet --info
  OS Name:     Windows
  OS Version:  6.3.9600
  OS Platform: Window
  RID:         win81-x64
  Base Path:   C:\Program Files\dotnet\sdk\3.1.201\
```

Kind regards

EDIT: Changed the "remove webpublishmethod" cmd, it's a bit different.

**Comment by dsplaisted** [comment]
@vijayrkn Could you triage this issue?

**Comment by vijayrkn** [comment]
If you see the documentation here - https://github.com/aspnet/websdk#msdeploy-package, you don't have to pass the WebPublishMethod when you have a profile. The below command should work

> dotnet build ".\src\Project.Subproject\Project.Subproject.csproj" -c Release /p:DeployOnBuild=True /p:PublishProfile="Release" /p:Password="(password)"

If you don't have any profiles, you can still publish using msdeploy by passing the WebPublishMethod instead of profile. This will assume that you don't have a profile & publish process will create and use a default profile on your behalf. 

> dotnet build ".\src\Project.Subproject\Project.Subproject.csproj" -c Release /p:DeployOnBuild=True /p:WebPublishMethod="MSDeploy" /p:MSDeployServiceURL=<msdeployUrl> /p:DeployIisAppPath=<IISSiteName> /p:Password="(password)"


Let me know if you run into any issue with the above.

**Comment by Ascathor** [comment]
Hello, I haven't been able to get back at you about this. I'd close it down for now and return once I have more to provide on this. Thank you @vijayrkn for the feedback!

Kind regards.
