### ISSUE TITLE
Cannot transitively reference a csproj+project.json

### ISSUE THREAD

**Issue by gulbanana** [dotnet/sdk#1112]
## Steps to reproduce
1. Clone https://github.com/gulbanana/repro-transitive-projectjson
2. `dotnet build`
3. error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

The bug also occurs when building in Visual Studio.

**Comment by gulbanana** [comment]
I've verified that the problem also happens when building with full-framework commandline MSBuild (version 15.1.1012.6693)

**Comment by livarcocc** [comment]
@AndyGerlicher @rainersigwald can you guys help take a look?

@gulbanana please note that this will not work through `dotnet build`, as the CLI does not support old style csproj files.

**Comment by rainersigwald** [comment]
I don't see this with `msbuild /t:restore && msbuild` in that repo. Can you share a diagnostic log? What file is allegedly invalid, and what are its contents?

**Comment by gulbanana** [comment]
Oh wow, i had unpushed commits in my local copy of the repo.. sorry, it should reproduce now!

Here's the output of `msbuld /t:restore && msbuild /v:diag`: https://gist.github.com/gulbanana/40d54c41f83a73bfc7aa6ad8c68ffef5

The content of the project.json file which is claimed to be invalid:
```
{
  "runtimes": {
    "win": {}
  },

  "frameworks": {
    "net461": {}
  },

  "dependencies": {
    "Newtonsoft.Json": "9.0.1"
  }
}
```

My guess is that the MSB4025 error indicates it's trying to load the project.json as an *msbuild* project file, which of course won't work.

**Comment by rainersigwald** [comment]
With that I'm now able to reproduce this, thanks.

You're right--the SDK includes transitive project references as `ProjectReferences`, which are then built with the `<MSBuild>` task, which then errors because in this case, the reference is a path to the `project.json` file, rather than the `%(ResolvedPath)`, which is the path to the `.csproj`. See [11821-11833](https://gist.github.com/gulbanana/40d54c41f83a73bfc7aa6ad8c68ffef5#file-output-txt-L11821-L11833) in your log.

I'll move this issue to the SDK repo.

**Comment by emgarten** [comment]
This looks like the same issue as https://github.com/dotnet/sdk/issues/922

The error there is:
```
3>E:\dotnetsdkerror\ClassLibrary1\project.json(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
3>Done building project "project.json" -- FAILED.
```

The workaround for this is to reference the project directly instead of getting it as a transitive project reference.

**Comment by gulbanana** [comment]
That workaround works (around) for me.

**Comment by livarcocc** [comment]
Let's track it though #922.
