### ISSUE TITLE
`.exe` file for OutputType=Exe should not be flow with ProjectReference

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#11131]
# Issue Title
`.exe` file for project with `OutputType=Exe` should not be flow with ProjectReference

### Reproduce Step
netcoreapp3.1 or 5.0preview is needed
1. `dotnet new console -n c1`
2. `dotnet new console -n c2`
3. `dotnet add c1 reference c2`
4. `dotnet build c1`

### Expected
`c2.exe` should not be included in the output of `c1`, only `c2.dll` is needed.
Or `c2.deps.json`(and maybe also `c2.runtimeconfig.json`) should be included to make `c2.exe` really executable.

### Actual
`c2.exe` is included. But it can not be executed without an `c2.deps.json` and is useless(assembly reference only need the dll files, I didn't see any usage for the `.exe` file)

**Comment by dsplaisted** [comment]
See also #1675
