### ISSUE TITLE
Why WinExe (win-x64) app publishing is host OS dependent

### ISSUE THREAD

**Issue by sergey-tihon** [dotnet/sdk#11162]
Why `dotnet publish -r win-x64 -c release /p:PublishSingleFile=true` produce different exe files on `Windows` and `macOS`?

It is strange that behavior of `dotnet publish` depends on my host OS and does not allow me to use my working machine (MacBook) to publish app for Windows users. Also I cannot publish app from Linux CI machine.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1197905/78507376-52679880-7788-11ea-8c4a-8dea6eb8190f.png">

WinExe application published on macOS:
1. smaller than the same exe generated on Windows
1. does not have application icon
1. start as console application

Here is the repo with hello world Avalonia application https://github.com/sergey-tihon/avalonia-win-exe

uses latest sdk
```json
{
  "sdk": {
    "version": "3.1.201"
  }
}
```
project file targets `netcoreapp3.1` with output type `WinExe`
```xml
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
```

both generated `exe` files are committed in [result-exe](https://github.com/sergey-tihon/avalonia-win-exe/tree/master/result-exe) folder

on the first screen you see the difference in size and application icon, here is the difference in application start. Application exe generated on `macOS` start console window first and only then show the window (this does not happened for exe published on Windows)

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/1197905/78507616-c9516100-7789-11ea-91ce-88a5ed5e8547.png">

Original issue https://github.com/AvaloniaUI/Avalonia/issues/3723

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/3828
Currently HostModel uses Win32 API to update resources. Need to implement this functionality in managed code.

CC: @wli3
