### ISSUE TITLE
install-dotnet-preview.sh is installing .NET 5 preview1 instead of preview2

### ISSUE THREAD

**Issue by vcsjones** [dotnet/sdk#11185]
I am attempting to install .NET Core 5 preview 2 with `install-dotnet-preview.sh` using the instructions [over here][1].

When I get to this step, `curl -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh`, that completely successfully, but I note that the downloaded script seems like it is trying to install preview1:

![image](https://user-images.githubusercontent.com/361677/78677593-ec792f00-78b5-11ea-8555-a36a15ce240d.png)

This is on Ubuntu 19.10 x64. Preview1 is already installed.

[1]: https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.2-install-instructions.md

**Comment by mairaw** [comment]
@grinrag can you look at this issue?

**Comment by carlossanlop** [comment]
Also @rbhanda, the creator of the document. Can you take a look?

**Comment by vcsjones** [comment]
I think the problem is that the script that https://aka.ms/install-dotnet-preview points to is out of date. If you download it and look inside, you see on like 33:

```sh
PREVIEW_NUMBER="1"
```

**Comment by mairaw** [comment]
@leecow you're the owner of that aka.ms link

**Comment by rbhanda** [comment]
It seems the script didn’t download correctly. Try to remove the file and download the file again. We will update the script so this doesn’t happen in future.

**Comment by vcsjones** [comment]
Looks good now, thank you. Please close this if you don't want to use this issue to track any additional work.

**Comment by mairaw** [comment]
Good to close @rbhanda? Or is there any additional work you need to track here?

**Comment by rbhanda** [comment]
> Good to close @rbhanda? Or is there any additional work you need to track here?

This issue is related to caching. I have updated the file parameters and this should be resolved now

**Comment by rbhanda** [comment]
I also updated the [instructions for installing .NET 5](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.2-install-instructions.md)
