### ISSUE TITLE
https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1 stops working in our Windows CI

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/sdk#11191]
The PowerShell repo [has been using](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L1636) the `dotnet-install.ps1` script from `https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1` for a long time, but today the script [stoped working in our Windows CI](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=49643&view=logs&j=69ceb723-764d-5bc2-ea34-985f6795a822&t=77efb26f-5f9c-5dce-57de-0fa87c932ed4), which is **running on win2016** (the `dotnet-install.ps1` is invoked from Windows PowerShell `powershell.exe`):
```
D:\a\1\s\tools\dotnet-install.ps1 : Exception setting "SecurityProtocol": "The requested security protocol is not supported."
```
This is caused by this line in `dotnet-install.ps1`:
```
# Default Tls protocol for .NET Framework 4.5 does not allow for Tls1.2.
[System.Net.ServicePointManager]::SecurityProtocol += [System.Net.SecurityProtocolType]::Tls12;
```
However, the weird part is, I don't find this line in the [`dotnet-install.ps1`](https://github.com/dotnet/sdk/blob/master/scripts/obtain/dotnet-install.ps1) in this repository. Does the `https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1` come from this repository? If not, which repository is it hosted?

**Comment by rjmholt** [comment]
```powershell
iwr https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1 -Verbose -OutFile 1.ps1
iwr https://raw.githubusercontent.com/dotnet/sdk/master/scripts/obtain/dotnet-install.ps1 -Verbose -OutFile 2.ps1
diff (Get-Content .\1.ps1) (Get-Content .\2.ps1)
```

```output
InputObject SideIndicator
----------- -------------
    return  =>
    return  =>
    return  =>
    exit 0  <=
    exit 0  <=
    exit 0  <=
exit 0      <=
```

Which looks like it's just https://github.com/dotnet/sdk/commit/78d9adc9ea1d0f4634e29e7e07d0ecdf62e5dbce (i.e. the script we use is just a slightly older version).

The script explicitly says it doesn't use `Invoke-WebRequest` because of NanoServer (instead using HttpClient directly). Is it possible we just need to add a TLS setting to it?

**Comment by daxian-dbw** [comment]
Interesting, the script file pointed by `https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1` was updated after this issue was filed and the line of script that caused the problem was removed:
```
PS:52> Compare-Object (Get-Content ./dotnet-install.ps1) (Get-Content ./dotnet-install-2.ps1)

InputObject                                                                                     SideIndicator
-----------                                                                                     -------------
# Default Tls protocol for .NET Framework 4.5 does not allow for Tls1.2.                        <=
[System.Net.ServicePointManager]::SecurityProtocol += [System.Net.SecurityProtocolType]::Tls12; <=
                                                                                                <=
```
Now the `dotnet-install.ps1` script works fine, and the `Bootstrap` step in our Windows CI are now passing: https://dev.azure.com/powershell/PowerShell/_build/results?buildId=49659&view=logs&j=41e18e79-2a23-52e6-c262-c4a7a16b9152&t=f57bcd1b-854b-5e3c-3ef0-5a862ff44810

Given that, I'm closing this issue.
