### ISSUE TITLE
*.runtimeconfig.json not copied to out put dir when project referenced

### ISSUE THREAD

**Issue by kirsan31** [dotnet/sdk#11207]
**Visual Studio Version**: 16.5.2

**Summary**:
When reference one .net core `exe` project (for example WinForm) from other, after build, files:  `dll`, `exe `, `pdb` and **`App.config`** (if present) are copied to out put directory of main project, but `*.runtimeconfig.json` is not copied. So, running this `exe` lead to very confusing error:
![Snipaste_2020-04-07_18-23-08](https://user-images.githubusercontent.com/17767561/78687501-e490ad80-78fc-11ea-8df1-b4d8afad6fbb.png)

**Steps to Reproduce**:

1. Create solution with WinForm core project.

2.  Add to solution 2-d WinForm core project.

3.  Reference one from another.

4. Try run (`Process.Start`) referenced `exe` from main project.

![Snipaste_2020-04-07_18-19-18](https://user-images.githubusercontent.com/17767561/78688278-c4152300-78fd-11ea-8aee-9d3816f71dca.png)

**Minimal repro:**
[Reftest.zip](https://github.com/dotnet/project-system/files/4445524/Reftest.zip)

**Expected Behavior**: All necessary files from referenced project must be copied.

**Actual Behavior**: `*.runtimeconfig.json` not copied.

**User Impact**: you can not run referenced `exe` file from main project.

**Comment by urosjovanovic** [comment]
Any updates on this issue?
Is there a workaround at least?

It also happens when you add a project reference to a net core console app from asp.net core service, *runtimeconfig.json for the console app is not copied to the output of asp.net core app which leads to this error:

> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.

When trying to run the console app.

**Comment by kirsan31** [comment]
This is not minor issue, this is regression from .net framework.
cc @dsplaisted sorry for cc you, I selected most active committer :confused:

**Comment by dsplaisted** [comment]
This is the same as #1675.  You can find a workaround in that issue.
