### ISSUE TITLE
With .Net 5 preview3 installed, the folders by the build procedure contains .net core.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#11217]
### Steps to reproduced:

Install SDK 5.0.100-preview.3.20208.17(runtime-5.0.0-preview.3.20206.14).
Using CLI, create a .net 5 project. 
Dotnet build

### Expected Result
Dotnet build with .net info only.

### Actual Result:
The folders by the build procedure contains .net core 
![image](https://user-images.githubusercontent.com/57380211/78955416-cc45ac00-7b11-11ea-8974-4f35714cb60d.png)

Dotnet –info:
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20208.17
 Commit:    f5e7d53b35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.3.20208.17\

Host (useful for support):
  Version: 5.0.0-preview.3.20206.14
  Commit:  3cda531877

.NET SDKs installed:
  5.0.100-preview.3.20208.17 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.3.20207.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20206.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20206.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
Fixed by #11304 and https://github.com/microsoft/msbuild/pull/5286

**Comment by yunwei00q** [comment]
Not repro on SDK 5.0.100-preview.5.20264.10(runtime-5.0.0-preview.6.20264.1)
![image](https://user-images.githubusercontent.com/57380211/82039766-135a2a80-96d8-11ea-9a3e-d6f333736dc8.png)
