### ISSUE TITLE
Create MSBuild SDK Resolver for workloads

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11228]
Detailed spec is here: https://github.com/dotnet/designs/blob/master/accepted/2020/workloads/workload-resolvers.md.  Basics are:

- [ ] Create MSBuild SDK resolver for workloads
  - [ ] Find specified workload via manifest and resolve to it, or return MissingWorkloadPack item
  - [ ] Implement WorkloadAutoImportPropsLocator pseudo-SDK

**Comment by wli3** [comment]
while i am blocked on Windows desktop. Let me see if I can create a dummy workload for test. And how our testing strategy in general for this work

**Comment by dsplaisted** [comment]
Completed, follow-up work is tracked in #13849
