### ISSUE TITLE
Support workloads in Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11229]
Detailed spec is here: dotnet/designs#104. Basics are:

  - Set WorkloadManifestRoot property
  - Import workload manifest targets from WorkloadManifestRoot
  - Add target to generate build error if there are any MissingWorkloadPack items
  - Import workload .props files

**Comment by wli3** [comment]
@dsplaisted  This task is your demo right?

**Comment by dsplaisted** [comment]
Yes, my demo included this (not that it was ready for check-in).

**Comment by dsplaisted** [comment]
Completed, follow-up work is tracked in #13849
