### ISSUE TITLE
Self-contained apps can use the Mono VM (and AOT) on desktop operating systems

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11227]
This means having the option of using Mono for self-contained apps (ie console apps) targeting Windows, Mac, and Linux.

Dependent on a MONO runtime pack.  This work is to allow SDK users to target this runtime pack via the CLI.

**Comment by wli3** [comment]
@mhutch do you know if this is still needed?

**Comment by dsplaisted** [comment]
#11824 added the core support for this.  What would be needed now is to have KnownRuntimePack items for Mono, and then UI (probably a property and possibly a command line option) that opts in to those runtime packs by setting the label on the implicit FrameworkReference.
