### ISSUE TITLE
Automatically define preprocessor symbols for target platforms

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11236]
Spec is here: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#preprocessor-symbols

Note that this includes defining preprocessor symbols for the target platform, as well as defining preprocessor symbols for previous versions of .NET and the OS

**Comment by dsplaisted** [comment]
@sfoslund Here's a piece of the .NET 5 work that I think you could pick up and implement now, if you are looking for something.

We don't yet parse the `TargetPlatformIdentifier` or `TargetPlatformVersion` out of the `TargetFramework`, but the preprocessor symbol logic shouldn't care, and you can just set the target platform properties directly in tests.

**Comment by sfoslund** [comment]
#11635 implements target platform and NET backwards compatible preprocessor symbols. Outstanding work: adding backwards compatibility for target platforms.
