### ISSUE TITLE
Support providing OS APIs from targeted platform

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11234]
When a project targets iOS or Android, the operating system API projections should be available to the project at compile time.

This should be via an implicit `FrameworkReference` added by the corresponding SDK workload.  The workload should also probably be in charge of carrying the corresponding `KnownFrameworkReference` information.

In the .NET SDK, we will probably have to update the framework reference resolution to understand the target platform information.  IE a `KnownFrameworkReference` for `net5.0` should be available in a project targeting `net5.0-ios`, but not vice versa.

Additionally, we need to update the SDK to download runtime packs based on the `RuntimeIdentifiers` property (plural).  This is so that a device app can specify multiple architectures that the produced package should support.  (EDIT: Turns out this is already supported.  See #11637)

**Comment by wli3** [comment]
blocked by ios and android provide a work in progress workload -- we need to sync with Xamiarn for when we can have a "good enough" implementation to try. And how to try -- just dropping file might be good enough

**Comment by wli3** [comment]
This works is mostly on workload owner right?

**Comment by steveisok** [comment]
@dsplaisted To make sure I understand, you're suggesting that, for example, the iOS SDK (the optional workload) would be responsible for including both its `KnownFrameworkReference` for Xamarin.iOS.Sdk AND the one for the underlying mono runtime?

**Comment by dsplaisted** [comment]
@steveisok Based on dotnet/installer#7034, it sounds like the Mono runtime for the base framework might be defined in the core SDK, not in the workloads.  I think it would work either way though.

**Comment by steveisok** [comment]
Yes, it's defined in the core SDK right now.  I wasn't sure as a result of this issue that would shift.  And if it's still in the core sdk, then there would need to be a way to pluck the right runtime pack where there's > 1 for the rid. 

For example: A project with `net5.0-macos` would need to ultimately load the `Microsoft.NETCore.App.Runtime.Mono.osx-x64` runtime pack.

**Comment by wli3** [comment]
For 5.0 we will only do that for windows

**Comment by wli3** [comment]
And windows part is done. We should move this to 6.0. Although pending https://github.com/dotnet/sdk/pull/12202 to get net5.0-windows working

**Comment by marcpopMSFT** [comment]
There may be additional needed .net 6 when we integrate with Xamarin.
