### ISSUE TITLE
Update Microsoft.NET.Sdk TargetFramework parsing to understand OS name and versions

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11231]
The parsing in Microsoft.NET.TargetFrameworkInference.targets needs to be updated to parse the `TargetPlatformIdentifier` and `TargetPlatformVersion` from the `TargetFramework`.

The existing parsing implementation (which uses string manipulation) should be replaced with calls to [new MSBuild Intrinsic functions](https://github.com/microsoft/msbuild/issues/5171) which will call the NuGet parsing APIs.

[.NET 5 TargetFramework spec](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md)

**Comment by wli3** [comment]
depend on https://github.com/microsoft/msbuild/issues/5171
