### ISSUE TITLE
Fail build if an unsupported or unknown operating system is specified in TargetFramework

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11232]
If the `TargetFramework` is something like `net5.0-mycustomos`, we should fail the build with an error that we don't know what `mycustomos` is.

Suggested logic:

- Platform-specific targets (usually in workloads) will set `TargetPlatformSupported` to true if the `TargetPlatformIdentifier` is set to something they recognize and support
- Base SDK will generate an error message if `TargetPlatformIdentifier` is non-empty and `TargetPlatformSupported` is not true

If a workload supports a given target platform, it should be responsible for generating error messages if the target platform version specified is one it doesn't support (or doesn't support in combination with the target framework version).

**Comment by Nirmal4G** [comment]
I'll go with allowing the optional workloads to understand the custom Frameworks and Platforms.

**Comment by Nirmal4G** [comment]
We should be allowing the optional workloads to understand the custom Frameworks and Platforms. That gives us the opportunity to experiment without modifying NuGet.
