### ISSUE TITLE
Generate target platform assembly attributes

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11239]
If the `TargetPlatformIdentifier` is set, the .NET SDK should generate assembly attributes for the target platform version, as well as the OSMinimumVersion.  See this spec: https://github.com/dotnet/designs/blob/master/accepted/2020/minimum-os-version/minimum-os-version.md

We can also include in this setting the `MinimumOSPlatform` to the `TargetPlatformVersion` if it's not otherwise defined.

**Comment by wli3** [comment]
Partially blocked by https://github.com/dotnet/runtime/issues/33331

I can write most of the code. But no to merge it

**Comment by wli3** [comment]
Rename to `MinimumOSPlatform` instead of `MinimumPlatformVersion`

**Comment by wli3** [comment]
Being blocked by https://github.com/dotnet/installer/pull/7943

Review is done just need the runtime type to flow in
