### ISSUE TITLE
Update link provided in build error due to missing ref packs to specific troubleshooting page

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#11243]
See dotnet/docs#17265

When build fails due to a missing ref pack, the error message printed links to [this documentation page](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies), which provides no specific details for solving this issue, especially on non-Windows platforms.

Suggest we link to a new docs page that helps troubleshoot this specific issue, detailing how to use the new ref assembly NuGet packages.

**Comment by marcpopMSFT** [comment]
We believe this has been fixed as we automatically handle this now and many of the error messages have been cleaned up since.
