### ISSUE TITLE
Producing an MSBuild task package

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#1125]
Can we get better support for projects designed to produce MSBuild tasks? 

**Pain points**
 - packing. You _can_ get a task assembly and files into the package, but requires deep understanding of how to alter the default layout of the package in csproj.
   - TargetFrameworks. A package that only has task assemblies/targets is compiled for net46 and netcoreapp1.0, but the _package_ itself can be compatible with any project, regardless of its TFM.
 - task references. When loading a task assembly, MSBuild does not use the NuGet cache to find dependencies. This means we have to package assemblies to sit side-by-side on disk so task loading works.
 - tasks with native dependencies. Never been able to make this work.

**Workarounds**
Task assembly projects end up looking like this
```xml
  <PropertyGroup>
    <!--
      The netstandard1.0 and net45 TFMs don't actually compile tasks.
      Only here so the generated nuspec includes the TFM so it appears as "compatible" on NuGet.org
      and in VS NuGet GUI.

      netstandard1.6 => loaded on dotnet.exe
      net46 => loaded on MSBuild.exe
    -->
    <TargetFrameworks>netstandard1.6;net46;netstandard1.0;net45</TargetFrameworks>
    <!-- Be quiet NuGet. I don't want assemblies in lib/ and yes I'm sure this is right. -->
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <!-- forces SDK to copy dependencies into build output to make packing easier -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
  </PropertyGroup>

  <ItemGroup>
    <!-- ensure nuspec doesn't contain any package references as we bundle their assemblies in our package -->
    <PackageReference Update="@(PackageReference)" PrivateAssets="All" />
  </ItemGroup>

  <!-- 
    Copy dependencies into the tools/$(TargetFramework)/ package folders.
    MSBuild does not resolve task runtime dependencies from PackageReference
  -->
  <Target Name="PackTaskDependencies" BeforeTargets="GenerateNuspec">
    <!--
    The include needs to happen after output has been copied to build output folder
    but before NuGet generates a nuspec.
    -->
    <ItemGroup>
      <_PackageFiles Include="bin\$(Configuration)\*\Newtonsoft.Json.dll;bin\$(Configuration)\*\NUglify.dll">
        <PackagePath>tools\%(RecursiveDir)</PackagePath>
        <Visible>false</Visible>
        <BuildAction>Content</BuildAction>
      </_PackageFiles>
    </ItemGroup>
  </Target>
```

Some MSBuild task projects in the wild:

[madskristensen/BundlerMinifier](https://github.com/madskristensen/BundlerMinifier/blob/b07009fb7915459e4698550e34e18223db210c7b/src/BundlerMinifier/BundlerMinifier.csproj)
[aspnet/BuildTools](https://github.com/aspnet/BuildTools/blob/dev/src/Internal.AspNetCore.Sdk.Tasks/Internal.AspNetCore.Sdk.Tasks.csproj)
[natemcmaster/Yarn.MSBuild](https://github.com/natemcmaster/Yarn.MSBuild/blob/89371fb77e314c1a6463a37b3023fd207faed180/src/Yarn.MSBuild/Yarn.MSBuild.csproj)

**Comment by livarcocc** [comment]
cc @emgarten @rohit21agrawal

**Comment by rohit21agrawal** [comment]
we already added some extension points that should make this easier : https://github.com/NuGet/NuGet.Client/pull/1255

We can't make a generic Task package type since all packages would differ widely. Do you have any concrete suggestions on what you would like to see that would make it easier for you to create task packages?

**Comment by natemcmaster** [comment]
In a world of unlimited resources, I'd love to see this:
```xml
<Project Sdk="Microsoft.Build.Task">
</Project>
```

Microsoft.NET.Sdk is geared towards runtime packages, not MSBuild task packages. Packages designed to carry MSBuild tasks are fundamentally different from packages that only carry runtime bits.

**Comment by natemcmaster** [comment]
@rohit21agrawal if you're looking for short-term fixes to the pack task...

One of the problems today is that package authors have to choose between nuspec and csproj=>nuspec generation. Keeping csproj and nuspec aligned is difficult, esp. for users new to MSbuild. Wrangling MSBuild to make csproj=>nuspec generation work right is difficult, even for advanced MSBuild users. I had to read NuGet's source code to figure some of this out.

Anything you can do to make nuspec + csproj easier would help with this ask.

One idea:
Make all msbuild properties available in nuspec. Currently you have to manually marshal these via `<NuspecProperties>`
```xml
<package>
  <metadata>
    <id>${MSBuild.PackageId}</id>
    <version>${MSBuild.PackageVersion}</version>
  </metadata>
</package>
```

**Comment by rohit21agrawal** [comment]
@natemcmaster instead of making csproj + nuspec easier, i'd like to understand more about what we can do to make the need for nuspec go away. 
what are some of the things that you can't achieve via csproj currently and for which you absolutely do need the nuspec?

**Comment by natemcmaster** [comment]
@rohit21agrawal 

- Packing the output of multiple projects. Example: [Microsoft.EntityFrameworkCore.Tools.nuspec](https://github.com/aspnet/EntityFramework/blob/bc1909bc3b24b2cd0a2635c0a657cf6787837e20/src/EFCore.Tools/EFCore.Tools.nuspec)
- "Fat packages". i.e. I want a nupkg with the output of "dotnet publish". Example: [NuGetPackageVerifier.nuspec](https://github.com/aspnet/BuildTools/blob/598f84df8512cd2d394256f4aebb922356dc1713/src/NuGetPackageVerifier/NuGetPackageVerifier.nuspec)
- `<summary>`. cref https://github.com/NuGet/Home/issues/4587.
- Explicitly defining the `<dependencies>` section. 
   - Example: I want my MSBuild task package to say `<dependencies><group targetFramework="Any"></group></dependencies>`, but nuspec generation always uses `<TargetFrameworks>` which is set to the target frameworks for which the task assembly compiles. In this case, `<TargetFrameworks>` does not accurately represent which frameworks the _package_ is compatible with.

**Comment by conniey** [comment]
I think this issue overlaps with: https://github.com/Microsoft/msbuild/issues/1756

**Comment by livarcocc** [comment]
Given that this conversation is happening around pack, I am moving this issue over to NuGet. Please, re-activate or file new issues for specific asks for the SDK to support this.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5063
