### ISSUE TITLE
PDB story for dotnet store 

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1126]
What is the story regarding symbols for `dotnet store`? What do we need to do to make sure the PDBs match the DLLs cross-gen'ed by `dotnet store`? I believe there is an option like `/CreatePDB` on crossgen.exe which may be relevant here.

cc @Eilon @ramarag @gkhanna79 @eerhardt

**Comment by gkhanna79** [comment]
ReadyToRun images already contain IL to Native offset mapping details. As along as there is IL PDB available, then Source->Native mapping will exist and no additional PDB needs to be generated. Did you generate them in the past (for Antares)?

/CreatePDB is used for Profiling. Is that your intent?

**Comment by JunTaoLuo** [comment]
So PDBs will work with the DLLs after cross-gen? I think that is all we need here. I'll give this a try and if that's the case, I don't think there's any required work here.

**Comment by gkhanna79** [comment]
The only difference between what used to happen for Antares and now is that store command generates the R2R images with the complete closure. If you did anything additional than that for antares, let us.

Otherwise, with IL PDBs, this should be sufficient.

**Comment by nguerrera** [comment]
> I think that is all we need here. I'll give this a try and if that's the case, I don't think there's any required work here.

Closing because we think there is no work required. @JunTaoLuo Have you given it a try? Feel free to reopen if it does not work for you.

**Comment by eerhardt** [comment]
In an offline discussion we decided this is required for profiling, and profiling is an important scenario.  There is work to be done here - we need to give an option to generate the PDBs when running `dotnet store`.  I'm working on this.

**Comment by nguerrera** [comment]
Is this fixed by #1156?

**Comment by eerhardt** [comment]
It was mostly implemented by that, but there are some things left:

1. adding CLI options to 'dotnet store'
2. defaulting symbols to "on" (they are off by default for preview1)
3. some of the MSBuild property names are going to change given new perspectives.

**Comment by eerhardt** [comment]
This work is now complete.  Closing.
