### ISSUE TITLE
Upgrading .NET Core SDK from 3.1.103 to 3.1.200 breaks code coverage collection

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#11274]
[This upgrade](https://github.com/microsoft/VSSDK-Analyzers/commit/257dbaf2ef66498cb1b1e7b07b742b7fd9075dd2) from .NET Core SDK 3.1.100 to 3.1.201 [broke our code coverage collection](https://dev.azure.com/azure-public/vside/_build/results?buildId=8637&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e17bc6ea-ce1d-53b5-abd4-e6afca33044d&l=17) during a test run, resulting in a nearly empty `coverage.cobertura.xml` file which [broke our CI build](https://dev.azure.com/azure-public/vside/_build/results?buildId=8637&view=logs&j=e02667c5-cdd5-5f90-d500-64ad42240816&t=d3a37d3f-ac13-5043-e05b-5f3f4a690563), (fortunately) drawing our attention to the regression.

> d:\a\_temp\.nuget\packages\coverlet.msbuild\2.6.3\build\coverlet.msbuild.targets(7,5): warning : [coverlet] Unable to instrument module: d:\a\1\s\bin\Microsoft.VisualStudio.SDK.Analyzers.Tests\Release\net472\Microsoft.VisualStudio.SDK.Analyzers.CodeFixes.dll because : The type initializer for 'Coverlet.Core.Instrumentation.NetstandardAwareAssemblyResolver' threw an exception. [d:\a\1\s\src\Microsoft.VisualStudio.SDK.Analyzers.Tests\Microsoft.VisualStudio.SDK.Analyzers.Tests.csproj]
         d:\a\_temp\.nuget\packages\coverlet.msbuild\2.6.3\build\coverlet.msbuild.targets(7,5): warning : [coverlet] Unable to instrument module: d:\a\1\s\bin\Microsoft.VisualStudio.SDK.Analyzers.Tests\Release\net472\Microsoft.VisualStudio.SDK.Analyzers.dll because : The type initializer for 'Coverlet.Core.Instrumentation.NetstandardAwareAssemblyResolver' threw an exception. [d:\a\1\s\src\Microsoft.VisualStudio.SDK.Analyzers.Tests\Microsoft.VisualStudio.SDK.Analyzers.Tests.csproj]

[Later updating](https://github.com/microsoft/VSSDK-Analyzers/pull/117/files#diff-7b5b82479cb19b29061e0fae461930e1L12-R12) the `coverlet.msbuild` package reference we have from 2.6.3 to 2.8.1 allowed us to keep the .NET Core SDK version upgrade.

But should .NET Core SDK upgrades break folks? I pin my SDKs with global.json to avoid issues like this happening unpredictably, but for folks who float to whatever the latest SDK is that's installed on a machine, issues like this would create fire drills.

**Comment by rainersigwald** [comment]
Thanks for reporting. This is very likely a result of adding `AssemblyLoadContext` isolation to tasks in MSBuild 16.5 (https://github.com/microsoft/msbuild/pull/4916). I added this to the list of known issues in https://github.com/microsoft/msbuild/issues/5202.

See also #10878.

**Comment by AArnott** [comment]
Thanks. That ALC isolation sounds like a _very_ good change, and worth a breaking SDK update.
I'm still an advocate for pinning SDK versions though of course. Because I *want* changes like this to be permissible, but I also don't want customers builds to break on a schedule that is unpredictable to them.
