### ISSUE TITLE
How to dotnet publish RID to the current OS (closest matching RID)

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/sdk#11282]
How to dotnet publish RID to the current OS (closest matching RID)?

It would be very helpful for having people run native builds without knowing the rids of their os/project

So say my project file contains `<RuntimeIdentifiers>win-x64;osx-x64;linux-x64</RuntimeIdentifiers>` and I run this on OSX, having a cli switch to pick osx-x64 automatically would be very helpful. Does it perhaps already exist?

**Comment by wli3** [comment]
We don't have an out-of-box  way to do that. You can reference [this](https://github.com/dotnet/installer/blob/7464d9bca4a2f25d1f832f9ef51ed288d4b0201e/src/core-sdk-tasks/GetCurrentRuntimeInformation.cs#L11) task. And set RuntimeIdentifier to the current RID
