### ISSUE TITLE
GenerateDepsFile::TrimRuntimeLibraries is removing path, hashPath and other extra information

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1130]
In the conflict resolution code for generating the .deps.json, we are losing critical information:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs#L209-L217

We aren't copying the `path`, `hashPath`, and `runtimeStoreManifestName` fields across to the new RuntimeLibrary.

See https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/RuntimeLibrary.cs#L61-L72 for all the information that needs to be flown.

This also applies to the CompilationLibrary: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs#L252-L258.  It is losing `path` and `hashPath`.

**Comment by gkhanna79** [comment]
@ramarag PTAL.

**Comment by gkhanna79** [comment]
Assigning to @eerhardt who is looking into fixing this already.

**Comment by eerhardt** [comment]
This issue is blocking ASP.NET MVC on Linux.  See https://github.com/dotnet/core-setup/issues/2113.
