### ISSUE TITLE
PublishSingleFile is not deterministic

### ISSUE THREAD

**Issue by nioncode** [dotnet/sdk#11311]
When publishing an application with `PublishSingleFile=true` two times, the resulting binaries are not byte-for-byte identical. When doing a publish without `PublishSingleFile`, the output is completely identical.

When piping the resulting .exe through a hexdump, there is only a single place where the single-file binaries differ, so I assume this is some kind of build identifier.

Can we make the builds deterministic when using `PublishSingleFile=true`? This would ensure that build outputs between different machines can be correctly compared / cached, etc.

Steps to reproduce:
```
dotnet new console
dotnet publish -o publish -p:PlatformTarget=x86 -r win-x86
dotnet publish -o publish2 -p:PlatformTarget=x86 -r win-x86
diff -rq publish*
--> good, no changes

dotnet publish -o single-publish -p:PublishSingleFile=true -p:PlatformTarget=x86 -r win-x86
dotnet publish -o single-publish2 -p:PublishSingleFile=true -p:PlatformTarget=x86 -r win-x86
diff -rq single* 
--> Files single-publish/demo.exe and single-publish2/demo.exe differ


xxd single-publish/*.exe > hex1.txt
xxd single-publish2/*.exe > hex2.txt
diff hex*.txt
3840344,3840345c3840344,3840345
< 03a99570: 0000 0000 00e0 0000 000c 676e 6b72 6e6f  ..........gnkrno
< 03a99580: 6162 2e66 766a 0014 0200 0000 0000 0012  ab.fvj..........
---
> 03a99570: 0000 0000 00e0 0000 000c 7264 6972 316c  ..........rdir1l
> 03a99580: 6830 2e76 346e 0014 0200 0000 0000 0012  h0.v4n..........
```

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/3601
