### ISSUE TITLE
error NU1100: Unable to resolve 'luisgen (>= 0.0.0)'

### ISSUE THREAD

**Issue by TylerOdenthal** [dotnet/sdk#11325]
I have been struggling with this problem for a couple weeks and can't seem to find a solution.

Related to this: https://github.com/microsoft/BotFramework-Composer/issues/2690

I am able to deploy my chatbot from Composer using .LG, but when dotnet requires LUISgen for my .LU files. Everything hits the fan...

```
C:\Users\Tyler\Desktop\ChatWorks>dotnet tool install -g LUISGen
error NU1100: Unable to resolve 'luisgen (>= 0.0.0)' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'luisgen (>= 0.0.0)' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'luisgen' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

```

**Comment by schmoli** [comment]
ever figure this out? just started having similar issue with all tools on a fresh install of windows, still diagnosing.

**Comment by schmoli** [comment]
fixed my issue just now, fresh box with minimal installs, dotnet does NOT install nuget by default, so I had to install that first. Note that I used chocolatey to install and that also didn't work as it gave me an empty %appdata/nuget/nuget.config so I had to edit that and install the nuget soruce, then dotnet-tool install started working just fine.
```
<configuration>
    <packageSources>
        <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```
