### ISSUE TITLE
Workload work with template

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#11326]
Templates today are selected by runtime band. -- the highest template within a runtime band will be selected and move to "hive". And then another complicated logic will pick what to use when user type `dotnet new`. -- This is very different than what we want for workload

Specifically:
1. Workload is bind by sdk version band. If you install Xamarin 5.1.100, and 5.1.200, they should be used by 5.1.1xx and 5.1.2xx separately. In current template design, the highest will be used regardless.
2. Won't work with platform opt-in (iOS new version) mechanism 
3. When uninstall a workload, the template should go with it.

--------------------------------

And I don't feel positive we can get this done within 5.0 timeframe considering we don't have someone understanding template engine through and through. And this is a very fundamental change.

The fallback might be
1. ask the user install Xamarin template from the internet
2. SDK carry all templates from all workload. They use may be able to create a project from the template, but they may not be able to run
3. [mostly hack] CLI take over/create several _dotnet new_ command and use a different code path instead of template engine.

**Comment by wli3** [comment]
From @phenning:

We should be able to add another location for the template engine to scan for templates when it initializes the hive for picking up the unbanned templates.

The difficult thing here is the rescan mechanism for when workloads change. We need to make sure that this location gets rescanned and any new templates packs are installed, as well as removing any that are no longer present. Most of the data needed for this should be available via API.

We also must be careful to not simply reinitialize the hive here as we don't want to remove any templates that the customer had installed via dotnet -i.

**Comment by wli3** [comment]
So far we think the fallbacks not acceptable

**Comment by wli3** [comment]
For VS. Since there is a concept of a provider which can run any C# code to find and filter templates. The implementation is relatively quick once we have the “read manifest and then select pack” logic.

However for the command line there is no much feature. We want to add new logic for template engine to rescan (currently only scan once every new SDK via sentinel mechanism). The rescan could be triggered by a Willow file indicating some VS installation is changed. Also, when a workload is uninstalled. We need to use unmount logic and trigger another rescan to keep templates availability in sync. We also need to by aware, rescan will remove all custom installed (via dotnet new -i ) templates. So we also need to find a way to record that and reinstall them.

**Comment by wli3** [comment]
The interface between SDK and the template engine are:
- Return a list of installed template package id and package version (instead of list of installed workload). SDK will read the manifest file, scan the disk.
- Return a list of installed template packages location.

The library should be a C# library, and SDK msbuild tasks should depend on it. So, we don’t need to share msbuild props and targets with template engine somehow. How to share it between 2 repos is TBD.

At the same time, we should consider making this shared library public and have a more generalized interface.
SDK(Will) will provide a mock library once the interface is decided to help development.  

Do you think a signature like the following is good enough?
```c#
namespace Proposal1
{
    public interface ITemplatesResolver
    {
        IEnumerable<TemplateResolverResult> Resolve();
    }

    public sealed class TemplateResolverResult
    {
        public string PackageId { get; }
        public string PackageVersion { get; }
        public string FullPathToPackageContainingDirectory { get; }
    }
}
```

**Comment by donJoseLuis** [comment]
@grinrag , removing you as an assignee, since you're tracking this work in the templating repo.
