### ISSUE TITLE
Infer WinExe output type as appropriate

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11398]
If a project file specifies an `OutputType` of `Exe`, we should automatically change it to `WinExe` if any of the following are true:

- `TargetPlatformIdentifier` is `windows` (which will be the case if the `TargetFramework` is `net5.0-windows`
- `UseWindowsForms` or `UseWPF` is true (this will cover projects that target .NET Core 3.x and thus don't have the `TargetPlatformIdentifier` set to `Windows`

**Comment by Nirmal4G** [comment]
What If I want the console subsystem with the above cases? will there be an opt-out?

**Comment by wjk** [comment]
I am writing an otherwise-100% console-based app that shows WPF-based UI in one certain circumstance. Having WPF imply WinExe would break my project's intended use-case. If I can workaround this by moving all the WPF stuff into a DLL, that's fine by me.
