### ISSUE TITLE
Microsoft.NETFramework.ReferenceAssemblies is not marked as PrivateAssets=All

### ISSUE THREAD

**Issue by andrew-boyarshin** [dotnet/sdk#11407]
I've spent some time fine-tuning SharpGen.Runtime dependency graph and there is one unexpected public dependency for 4.7.1.
![NuGet Package Explorer](https://user-images.githubusercontent.com/3063662/80175653-616f9700-8620-11ea-80a5-5bce2ebfa2de.png)

[Design spec](https://github.com/dotnet/designs/blob/master/accepted/2020/targeting-packs/targeting-packs.md) mentiones that:
> The reference assembly packages should not show up as dependencies of "normal" packages. Thus, the reference assembly packages should set developmentDependency to true in it's metadata. Likewise, when the .NET SDK automatically references the reference assembly metapackage, it should use PrivateAssets="All".

But the implementation in #10981 omitted the last part.

**Comment by andrew-boyarshin** [comment]
Cross-referencing [my SharpGen draft PR](https://github.com/SharpGenTools/SharpGenTools/pull/161).

**Comment by andrew-boyarshin** [comment]
By the way, `AutomaticallyUseReferenceAssemblyPackages` doesn't check if it is already set, so I can't override it from `Directory.Build.props` (it is imported from `Microsoft.Common.props`, before .NET SDK props).

**Comment by andrew-boyarshin** [comment]
cc @terrajobst @dsplaisted @sfoslund

**Comment by dsplaisted** [comment]
Argh, I'm annoyed that I missed this :-)

@sfoslund, I think this should be a quick fix, can you go ahead and fix it?

**Comment by sfoslund** [comment]
@dsplaisted yup, already on it. PR here: #11491
