### ISSUE TITLE
Require minimum Powershell version in dotnet-install.ps1?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/sdk#11400]
See https://github.com/dotnet/runtime/issues/35301 -- it seems 5.1 can fail cryptically. According to https://github.com/PowerShell/PowerShell/issues/12442 this is out of support.

If we want dotnet-install.ps1 to be as helpful as possible (since it's our front door for many people) perhaps it should ensure that the Powershell version installed is new enough.  At the moment, that seems to be 6.2 : https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7 . (If that's the case, then we can also update our own [build requirements](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md) which currently say 3.0.)

Conversely however on my Windows 10 machine, I see I have 5.1, and dotnet-install.ps1 appears to work. Perhaps the issue this user encountered is obscure, and we should continue to plow ahead no matter the Powershell version.

**Comment by fMichaleczek** [comment]
@danmosemsft 
Windows PowerShell is like .net 4, it's still supported by the Windows Team but the advice is to move to PowerShell Core like you want people move to .net core.
 
PowerShell 7 is a LTS version (based on LTS .netcore 3.1), the PS team has remove the "core" word with this version, his compatibility with Windows is better than 6.x

**Comment by danmosemsft** [comment]
I see. The customer having the issue in this case had 5.1, but I guess there's no value in saying "4.0 is OK, not 5.1, 6.1+ is also OK" .. this can probably be closed then.

**Comment by fMichaleczek** [comment]
I read [your document](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md), and analyze a little the situation.

At the moment, you support 8 versions : PS3.0, 4.0, 5.0, 5.1, 6.0, 6.1, 6.2 and 7.0 ( 4 versions are deep inside the OS (WinPS), the other are sideloaded (PSCore). ) 
PS : there is also a different 5.1 version inside each different build of Windows 10 (like net4)

People who have a dirty OS system have more chance to have issue on WinPS than PSCore which is side loaded.

So support only 1 or 2 versions (LTS + Last if exists) across all Windows versions could be a better opportunities for your support and it gives you the possibility to be supported on github by the PowerShell Team.

The cost is to update your documentation and maybe a very little universal PowerShell script who install PowerShell 7.0.

In my opinion dotnet should bear these children :-)

**Comment by danmosemsft** [comment]
Thanks. That doc  is merely for building the repo: is not a big deal. It is not clear there is anything useful for SDK here. I will close.
