### ISSUE TITLE
Question: Should it be `NETCOREAPP5_0` or `NET5_0`?

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#11409]
With the release of .NET 5 preview 3, the TFM has changed from `netcoreapp5.0` to `net5.0`. However, the Define Constant for the TFM is still `NETCOREAPP5_0` rather than `NET5_0`.

Is this intentional (e.g. for back-compat), something that hasn't been done yet but is planned, or a bug because it should have been done as part of preview 3 and missed?

_Sorry if this is the wrong repo, I wasn't sure if this was an SDK thing or a compiler thing. I had a look in runtime, sdk and roslyn and couldn't seem to find anything about this topic._

**Comment by martincostello** [comment]
Any update here? Seems to still be the case with preview 4.

**Comment by martincostello** [comment]
Related to https://github.com/dotnet/sdk/issues/10756?

**Comment by dsplaisted** [comment]
It will be `NET5_0`, with `NETCOREAPP` still defined for backwards compatibility. The spec for this is here: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#preprocessor-symbols

We have a PR in progress for it here: https://github.com/dotnet/sdk/pull/11635

**Comment by benaadams** [comment]
net5.0
* NETCOREAPP, NETCOREAPP3_1 (for backwards compatibility)
* NET, NET5_0

Shouldn't it also include NETCOREAPP5_0 so as not to regress everything using stuff in preview (including aspnet)

**Comment by dsplaisted** [comment]
> Shouldn't it also include NETCOREAPP5_0 so as not to regress everything using stuff in preview (including aspnet)

I think we don't want to define `NETCOREAPP5_0` in the final release, so we would need to drop support for it sometime.  It might be a good idea to have a preview where both `NET5_0` and `NETCOREAPP5_0` are defined to give folks a wider window to update their projects, but I would guess most people using `NETCOREAPP5_0` wouldn't get the message and would end up getting broken when we remove it anyway.

Thoughts?

/cc @terrajobst

**Comment by martincostello** [comment]
Looks like the change from `NETCOREAPP5_0` to `NET5_0` happened in preview 7.
