### ISSUE TITLE
Cannot run dotnet test on solution filter files (slnf)

### ISSUE THREAD

**Issue by roji** [dotnet/sdk#11417]
While it is possible to run dotnet test on solution files (.sln), doing so on solution filter files fails (.slnf).

.NET Core SDK (5.0.100-preview.2.20176.6)

**Comment by Happypig375** [comment]
From https://github.com/dotnet/sdk/issues/10409, it appears that this is working as of .NET SDK 3.1.401.

**Comment by MisinformedDNA** [comment]
Works for me.

> ❯ dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   6.0.402
>  Commit:    6862418796

**Comment by baronfel** [comment]
Going to close this out with two confirmed reports. Please let us know if anyone experiences a regression here.
