### ISSUE TITLE
self-contained published exe's do not get strong name signed

### ISSUE THREAD

**Issue by novinc** [dotnet/sdk#11428]
I'm running into a problem with strong name signing. I have a netcore 3.1 application where I need all the assemblies to have a strong name.
I have included the following in my csproj:
```
<SignAssembly>true</SignAssembly>
<DelaySign>false</DelaySign>
<AssemblyOriginatorKeyFile>sgKey.snk</AssemblyOriginatorKeyFile>
```

I run the publish command:
```
dotnet publish myproj.csproj -o myoutpath -c Release --self-contained -r win7-x64
```

Inside the myoutpath folder there are two assemblies (that I care about here):
1. The cross platform dll that can be invoked with dotnet myproj.dll
2. The platform specific (win7-x64) self-contained exe (myproj.exe)

Checking these two assemblies with the sn tool I can see that the dll has a valid strong name, but the exe does not.

When delay sign is false and the key is the public private pair I get
Assembly 'myproj.dll' is valid
myproj.exe does not represent a strongly named assembly

And when delay sign is true and the key i give is just the public key I get
myproj.dll is a delay-signed or test-signed assembly
myproj.exe does not represent a strongly named assembly

In both cases the dll is successfully getting a strong name but the exe is not.

I would expect the exe would get a strong name / delay signed just as the dll.

**Comment by novinc** [comment]
Adding the contributors to as this is where exe host is generated from the dlls: https://github.com/dotnet/runtime/blob/master/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
@swaroop-sridhar @wli3

**Comment by swaroop-sridhar** [comment]
@novinc "myproj.exe" is not an assembly, it is a native binary.
