### ISSUE TITLE
Port NuGet.Build.Tasks.Console in a 3.1.xxx branch

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#11420]
Port https://github.com/dotnet/sdk/pull/10794 to a 3.1.xxx branch. 

This is a huge win performance wise for customers and I think it'll nice if they don't have to wait till 5.x to try it out. 

cc @dsplaisted @jeffkl @ViktorHofer @rainersigwald 

The risk of the change is low because this feature is behind a feature flag.

See https://github.com/NuGet/Home/issues/8791 for more info.

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/10794/files 3 files need to port?

**Comment by ViktorHofer** [comment]
Yes. Is there a policy regarding which nuget version to use in servicing branches?

**Comment by nkolev92** [comment]
3.1.400 is not really a servicing branch. 
It's what will ship with VS 2019.7. 

NuGet right now pushes updates to the 3.1.400 and 5.0 releases, so the chnage for 3.1.400 shouldn't require a version change.

**Comment by wli3** [comment]
PRs in 
https://github.com/dotnet/cli/pull/13374
https://github.com/dotnet/toolset/pull/4583

Wait for 5/26 for the branch to open

**Comment by ViktorHofer** [comment]
Do we already have shiproom approval?

**Comment by dsplaisted** [comment]
@ViktorHofer This isn't going into a servicing release, it is going into a regular feature release, so we don't need shiproom approval.

**Comment by wli3** [comment]
all merged
