### ISSUE TITLE
Generate MVC project from dotnet console (2.0)

### ISSUE THREAD

**Issue by purehaTime** [dotnet/sdk#1143]
I generated new mvc project from dotnet console (version 2.0.0-preview1-005783) : dotnet new mvc
After restoring I try to build default project, but I gave error:

> Program.cs(20,6): error CS1061: 'IWebHostBuilder' does not contain a definition for 'ConfigureConfiguration' and no extension method 'ConfigureConfiguration' accepting a first argument of type 'IWebHostBuilder' could be found (are you missing a using directive or an assembly reference?) [F:\Code\Test\web\web.csproj]

I just replaced "ConfigureConfiguration" to "ConfigureAppConfiguration" (check msdn) and all works, but I was confused

**Comment by livarcocc** [comment]
Please, pick up the latest CLI and re-activate if you still hit any issues.

We fixed this in latest.
