### ISSUE TITLE
dotnet pack doesn't find assembly dll if windows locale is non US

### ISSUE THREAD

**Issue by milung** [dotnet/sdk#11442]
Generating nuget package does not work on my windows 10 system witn .NET Core SDK 3.1.201 if the system regional settings is the local one (Slovak for region settings) In the such case, I am getting error: 

```
$ dotnet pack
C:\Program Files\dotnet\sdk\3.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5019: File not found
```

After changing to US regional settings in windows settings and restarting powershell session, the result is as expected. Changing back to the slovak regional settings leads to the same error. 

Similar issue when running dotnet nuget publish - in this case the package file cannot be found. 

**Reproducing:** 

- os Win10, with slovak for the regional setting
- create project with `dotnet new classlib`
- add package name /author into the csproj
- have regional settings in non US (Slovak)
- run dotnet pack

**Workaround**

Set the regional setting to English(USA) in windows 10

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#9561
