### ISSUE TITLE
`MSB4018: The "GenerateDepsFile" task failed unexpectedly.` in recently daily builds<- Could not load file or assembly "System.Threading.Tasks.Extensions, Version = 4.2.0.0"

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#11460]
That error happens when try to use recently daily builds of dotnet-sdk 5.0.* with msbuild.exe(net472) from VS2019 16.6 preview4(msbuild 16.6.0-preview-20208-15+2f58c1427)
Not working version of dotnet-sdk: 5.0.100-preview.5.20227.13/ 5.0.100-preview.4.20227.14(both daily builds from https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries)
Last working version: 5.0.100-preview.3.20216.6(release from https://dotnet.microsoft.com/download/dotnet/5.0)

```cs
error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly "System.Threading.Tasks.Extensions, Version = 4.2.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51" or one of its dependencies. The system can not find the file specified.
File name: "System.Threading.Tasks.Extensions, Version = 4.2.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51"
    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write (DependencyContext context, Stream stream)
    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile (String depsFilePath)
    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore ()
    at Microsoft.NET.Build.Tasks.TaskBase.Execute ()
    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute ()
    at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask> d__26.MoveNext ()
```

#### Step
1. dotnet new console;
2. dotnet clean;
3. dotnet restore;
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe"

If you run step 4 again without clean, the error is not shown, but still lead to an broken `xxx.deps.json`. And you can see the same error when build in VS.

**Comment by wli3** [comment]
`DependencyContextWriter` should have retry

**Comment by wli3** [comment]
Issue moved to [dotnet/runtime #36350](https://github.com/dotnet/runtime/issues/36350) via [**ZenHub**](https://www.zenhub.com/)
