### ISSUE TITLE
Copy 'contentFiles' from NuGet packages to build and publish output folders

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#115]
We need to copy "contentFile" assets from referenced NuGet packages to the build and publish output folders.

Depends on #70.

**Comment by eerhardt** [comment]
@emgarten @rrelyea - Will the `dotnet/sdk` still need to do any work for contentFiles after https://github.com/NuGet/Home/issues/3683 is fixed?  

If `contentFiles` show up in the project just like regular files on disk, I don't think we will need to do anything special.

**Comment by piotrpMSFT** [comment]
@natidea would be great to get an ETA on this as well. @jgoshi is blocked in moving CLI repo onto SDK due to this.

**Comment by natidea** [comment]
@piotrpMSFT I had held off doing this because NuGet handling of content files may address this. @emgarten is that the case?

**Comment by natemcmaster** [comment]
👀  I'm looking to move a few aspnet repos to use the SDK, but we need this to work first.

**Comment by natidea** [comment]
@emgarten says this will be addressed as part of NuGet changes aimed for RC.

**Comment by natemcmaster** [comment]
@emgarten is there an item on nuget/home tracking this? This bug is blocking work to upgrade ASP.NET Core to this new sdk.

**Comment by rrelyea** [comment]
https://github.com/NuGet/Home/issues/3683 covers this. Currently pushed to RC.2

**Comment by natemcmaster** [comment]
Thanks @rrelyea

**Comment by rrelyea** [comment]
rc2 will work, i'm assuming.
