### ISSUE TITLE
With implicit package target fallback to net461, dotnet add package fails

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#1150]
Running `dotnet add package NewtonSoft.Json --version 9.0.1 --framework netcoreapp2.0` to a project like below fails with package imcompatible with specified framework if we have a PTF to net461.

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
```

**Comment by dsplaisted** [comment]
I'm not sure if this is still an issue, I removed a workaround for this in https://github.com/dotnet/cli/pull/8919
