### ISSUE TITLE
.NET Core SDK 3.1.xxx's dependency on VS 2019

### ISSUE THREAD

**Issue by kaki1027** [dotnet/sdk#11516]
Hello Experts,

After I have upgraded my machine that had
  .NET Core SDK 2.1.xxx
and
  VS 2017
... to have .NET Core 3.1.103, my project can no longer build.  

Yes, I've read that .NET Core 3.1.103 is NOT compatible with VS 2017.
But from what I understand I should be able to build projects on non-Windows platforms such as Linux where VS is NOT at all available.

What/Which .NET Core SDK's functionality "requires" VS 2019 to be installed on a machine?
Is it possible to use .NET Core 3.1.103 for project builds without having to install VS 2019 on my machine?

NOTE: All I'm calling are "dotnet build" and "dotnet restore" commands.

Thank you in advance!

**Comment by kaki1027** [comment]
The error that I'm seeing on my machine which has .NET Core SDK 3.1.103 but without VS 2019 is the following:

MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): error : The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0. [C:\......\my.csproj]

On another developer's machine with VS 2019, no such error is seen.

NOTE: The build environment on both machines have a global.json that contains :
{
  "sdk": {
    "version": "3.1.103"
  }
}

Why can't .NET Core SDK 3.1.103 be able to target "netstandard2.0" on a machine that does not have VS 2019 installed but able to do so on a machine that has VS 2019 installed?  Or is / are there other factors at play here (that is NOT related to VS 2019)?

**Comment by rainersigwald** [comment]
> MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.

This looks like output from `nuget.exe`. Are you using that to restore? Can you instead use `dotnet restore`?

**Comment by kaki1027** [comment]
Based on what I read, it seemed like nuget.exe restore and donet restore pretty much did the same thing.....  

Why does nuget.exe restore end up having the BUILD of the product depend on VS 2019 where as using dotnet.exe restored does not?

**Comment by rainersigwald** [comment]
`nuget.exe` uses MSBuild from a Visual Studio installation to extract information from the projects to be restored. `dotnet restore` basically runs `dotnet msbuild -target:Restore`, which uses the MSBuild that's built into the .NET Core SDK.

**Comment by kaki1027** [comment]
Thanks for the explanation!
