### ISSUE TITLE
RID win-x64 no longer publishes exe when used in RuntimeIdentifiers

### ISSUE THREAD

**Issue by mrlife** [dotnet/sdk#11555]
It looks like `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` will produce an `exe`, but `<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>` does not, though it used to.

Did something change? I can provide repro project.

Ref: https://github.com/dotnet/aspnetcore/issues/21402#issuecomment-623491070

**Comment by mrlife** [comment]
Do you know of another workaround in the meantime?

Right now, I must remember to comment out

```<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>```

and uncomment

```<RuntimeIdentifier>win-x64</RuntimeIdentifier>```

before each publish.

**Comment by mrlife** [comment]
@marcpopMSFT I don't mind submitting a PR to fix this, but I can't find the file in the repo. If I can do anything to help fix this, please let me know.

**Comment by marcpopMSFT** [comment]
Can you provide the repro project?

**Comment by mrlife** [comment]
@marcpopMSFT Here is the repro. It's a fresh project with only the following lines from the first issue comment added to the csproj. The second line is added for testing purposes.

```
<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
<!--<RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
```

[RidTest.zip](https://github.com/dotnet/sdk/files/5792673/RidTest.zip)

**Comment by marcpopMSFT** [comment]
I ran "dotnet new console", added that line to the .csproj file, and the tried both dotnet build and dotnet publish.  Both commands generated .exe files in the bin\debug\net5.0 and net5.0\publish folders respectively.  I did this with .NET SDK 5.0.101.  Are you using a different sdk or different template?

**Comment by mrlife** [comment]
@marcpopMSFT Doing the same does not create the .exe file for me on macOS; this is in the linked issue but not explicitly stated in this issue. I'm guessing this is why the console project doesn't create an exe for me. I'm on the same 5.0.101 SDK.

Were you able to try out the repro?

**Comment by marcpopMSFT** [comment]
Ahh, you're on MacOS. Please try setting UseAppHost=true.  A change was made specifically for MacOS to set this value to false.  See more here: https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues#apphost-is-disabled-by-default

**Comment by mrlife** [comment]
@marcpopMSFT Thanks for pointing that out; I hadn't noticed that in any of the posted changelogs. I'm still not seeing an .exe file when using this in the .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseAppHost>true</UseAppHost>
    <RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by marcpopMSFT** [comment]
I don't have a Mac set up to see if UseAppHost is working so I've asked @wli3 to take a look when he has a minute.

**Comment by wli3** [comment]
![image](https://user-images.githubusercontent.com/6993335/108307659-0553a180-7163-11eb-930e-4208f46dac52.png)

**Comment by wli3** [comment]
The problem is you need to have `<OutputType>Exe</OutputType>`. Or it will be considered a library. And a library will only have dlls.

**Comment by mrlife** [comment]
@wli3 Thank you for getting back to me. I added the following, but publishing does not create a file with an `exe` extension. The `testrid` in your screenshot is like what I get as well, but it's not a Windows `exe` file.

```
<UseAppHost>true</UseAppHost>
<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
<OutputType>Exe</OutputType>
```

**Comment by wli3** [comment]
I see, you want a windows exe not a mac executable file. `<DefaultAppHostRuntimeIdentifier>win-x64</DefaultAppHostRuntimeIdentifier>` would change that

**Comment by mrlife** [comment]
@wli3 Thank you, that was it.

Here's the full list for posterity:

```
<UseAppHost>true</UseAppHost>
<DefaultAppHostRuntimeIdentifier>win-x64</DefaultAppHostRuntimeIdentifier>
<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
```
