### ISSUE TITLE
Unable to find package Microsoft.NETCore.App with version (>= 3.1.0)

### ISSUE THREAD

**Issue by sorin-bolos** [dotnet/sdk#11554]
I have .NET Core SDK 3.1.200 installed on my local machine.
I create a Asp.Net Core app (using Visual Studio) targeting `netcoreapp3.1`. I test it and it works fine.
But when I commit it to CI the build fails to get the nuget package:
```
##[error]The nuget command failed with exit code(1) and error(NU1102: Unable to find package Microsoft.NETCore.App with version (>= 3.1.0)
  - Found 81 version(s) in MyGet [ Nearest version: 3.0.0-preview8-28405-07 ]
  - Found 73 version(s) in NuGet [ Nearest version: 2.2.8 ]
```

.NET Core 3.1 was released in December 2019 so why is the package not on nuget?
What am I missing?

**Comment by 610th** [comment]
Looks like this is related to what I'm experiencing. https://github.com/dotnet/sdk/issues/11576

**Comment by marcpopMSFT** [comment]
Do you know what version of the sdk is installed on the CI machine?

**Comment by sorin-bolos** [comment]
The CI agents did not have any sdk installed. Fixed it by adding 
```
- task: UseDotNet@2	
  displayName: 'Use .Net Core sdk 3.1.x'	
  inputs:	
    version: 3.1.x	
```
in the .yaml file.

But the error message is confusing.
