### ISSUE TITLE
Provide WinRT APIs for projects targeting Windows

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11556]
Projects targeting Windows (for example via a `TargetFramework` of `net5.0-windows10.0.18362`) should automatically have access to WinRT APIs available in the targeted version of Windows.

This is basically the same as #11234, but for Windows.  The Windows SDK team should create targeting packs and runtime packs for the WinRT APIs, and the SDK should reference them as appropriate.

For Windows, the `KnownFrameworkReference` items and the implicit `FrameworkReference` would go in the WindowsDesktop targets files.

Related work:

- [ ] Create "AnyCPU" targeting/runtime packs for each version of Windows we will support targeting (possible list: 17763, 18362, 19041)
- [ ] Update .NET SDK to consume targeting / runtime packs as appropriate for specified target platform (via the `TargetPlatformIdentifier` and `TargetPlatformVersion` properties, which will usually be parsed out from the `TargetFramework`)
- [ ] Update .NET SDK to set default `TargetPlatformVersion` for Windows to 7.0: #11233
- [ ] Update .NET SDK to error out appropriately if `TargetPlatformIdentifier` is Windows and `TargetPlatformVersion` is not recognized
- [ ] Investigate benefits of using crossgen for CSWinRT assets.  https://github.com/microsoft/CsWinRT/issues/317 Depending on the results of this:
  - [ ] Create separate runtime packs for each architecture with crossgen'd versions of CSWinRT assets
  - [ ] Update .NET SDK to consume these runtime packs
- [ ] Decorate WinRT APIs with attributes to support adaptive code analysis via the Roslyn analyzer - [Proposed attributes for annotations](https://github.com/dotnet/designs/blob/master/accepted/2020/minimum-os-version/minimum-os-version.md)

**Comment by jkoritzinsky** [comment]
cc: @AdamBraden, @MikeHillberg
