### ISSUE TITLE
Use SingleFileHost for self-contained single-file apps

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/sdk#11567]
There are two main tasks that need to be done for self-contained single-file publish scenario:

## Use `singlefilehost`
* @VSadov's [PR](https://github.com/dotnet/runtime/pull/35368)  adds `singlefilehost` to the `microsoft.netcore.app.host.*` packages.
* [ResolveAppHosts](https://github.com/dotnet/sdk/blob/611fcdd2ce0b29abae9967ca8e425db1a4def176/src/Tasks/Microsoft.NET.Build.Tasks/ResolveAppHosts.cs#L58-L64) will resolve `singlefilehost` to the same package as `apphost`, `ijwhost`, and `comhost`.
* When publishing for self-contained single-file apps, the [CreateAppHost task]( https://github.com/dotnet/sdk/blob/36ef8b2aa8e5d579c921704bdab69a7407936889/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L427) will be invoked with the singlefilehost path as its `AppHostSourcePath`. This will generate an app using `singlefilehost`.
* This may not work very well for a sequence such below. However, I think fixing this case is not crucial, because the `--no-build` already has [similar concerns](https://github.com/dotnet/sdk/issues/10608) for self-contained vs framework-dependent publish.

```
    dotnet build -r win-x64 
    dotnet publish --no-build -r win-x64 /p:PublishSingleFile=true.
```

## Trim the native components of the runtime:
* Certain files in `microsoft.netcore.app.runtime.*` package are no longer necessary to be published for single-file apps.
* For example, `hostfxr` and `hostpolicy` are not necessary since they are statically linked with `singlefilehost`. Later `coreclr`, `clrjit` will also be linked with the `singlefilehost`, and they are also not necessary. Certain other files such as `createdump` are excluded from the publish as a matter of policy decision. 
* This exclusion is different from `ExcludeFromSingleFile`
    * In this case, the files, the excluded files are not published at all (neither in the bundle nor in the publish directory beside the single-file bundle).
    * Files marked `ExcludeFromSingleFile` are copied to publish directory alongside the single-file app.
* The plan to realize this exclusion of runtime components is:
    * The `RuntimeList.xml` in `microsoft.netcore.app.runtime.*` package will contain special meta-data identifying that the file is not necessary for single-file scenario
`<File FileVersion="0.0.0.0" Path="runtimes/linux-x64/native/createdump" Type="Native" DropFromSingleFile="true"/>`
    * The  [`ResolveRuntimePackAssets` task](https://github.com/dotnet/sdk/blame/611fcdd2ce0b29abae9967ca8e425db1a4def176/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L92) will transfer this annotation as (`DropFromSingleFile`) meta-data on the asset.
  * The Single-file [publish targets](https://github.com/dotnet/sdk/blob/611fcdd2ce0b29abae9967ca8e425db1a4def176/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L938-L941) will use this meta-data to drop these files, and not publish them in the single-file app.

**Comment by swaroop-sridhar** [comment]
CC: @dsplaisted  @wli3 @VSadov

**Comment by wli3** [comment]
```
dotnet build -r win-x64 
dotnet publish --no-build -r win-x64 /p:PublishSingleFile=true.
```
Should work. The package should be restored by the first build

The plan looks good to me @dsplaisted what do you think?

**Comment by dsplaisted** [comment]
Yes, [looks good](https://github.com/dotnet/runtime/issues/32823#issuecomment-624311763)
