### ISSUE TITLE
On Ubuntu 16.04, it will take a while when restore a 2.1 or 2.2 web project with SDK 3.1.300+runtime 2.1&2.2

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#11577]
**Repro Steps:**
1. On Ubuntu16.04, install SDK 3.1.300 and Runtime 2.1.18 & 2.2.10
2. Install web template for  2.1 and 2.2
    dotnet new -i microsoft.dotnet.web.projecttemplates.2.1::2.1.18
    dotnet new -i microsoft.dotnet.web.projecttemplates.2.2::2.2.10
3. Create a web project targeting 2.1 or 2.2
4. Try to build or restore it

**Expected Result:**
2.1 or 2.2 web project works well.

**Actual Result:**
It take a while when restore this 2.1 or 2.2 web project
_$ dotnet new mvc -f netcoreapp2.1
The template "ASP.NET Core Web App (Model-View-Controller)" was created succesully.
This template contains technologies from parties other than Microsoft, see htt://aka.ms/aspnetcore-template-3pn-210 for details.
Processing post-creation actions...
Running 'dotnet restore' on /home/nicole/mymvc21/mymvc21.csproj...
  Determining projects to restore...
  Restored /home/nicole/mymvc21/mymvc21.csproj (**in 3.38 min**).
Restore succeeded._

**Dotnet info**
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by vdanche** [comment]
Not repro on runtime 2.1.19 and 2.2.11, hence close it.
