### ISSUE TITLE
Can't make a shared-framework targeted package without a reference to NETCore.App

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#1159]
Repro:

1. Create a netcoreapp1.1 default exe project.
2. Add `<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>`
3. Add references (System.Runtime, etc) as necessary to get it to compile.
4. Publish.

The `runtimeconfig.json` is now empty instead of the expected `netcoreapp1.1`. There should be some way to manually specify the target runtime framework without referencing the NETCore.App package.

**Comment by livarcocc** [comment]
What are the reasons for this? What is the scenario you are trying to enable by doing something like this?

**Comment by tmat** [comment]
@agocke Can we close this?

**Comment by agocke** [comment]
Yeah, I think this either works now, or is no longer relevant.
