### ISSUE TITLE
Unable to run self-contained webapi template

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#1160]
# Details
Publishing a self-contained app using the webapi template produces an app that does not run.
I found out that this is because the publish output gets filtered by `/home/sven/.dotnet/NuGetFallbackFolder/microsoft.aspnetcore.all/2.0.0-preview1-24647/build/manifest.linux-x64.xml`.

This breaks the ability to run a supposedly self-contained app locally (this used to work). I wasn't sure whether to file the issue in the sdk repo or in an aspnet repo, so feel free to move it.

/cc @ramarag

# Repro steps
- `dotnet new webapi`
- `dotnet restore -r ubuntu.16.04-x64`
- `dotnet publish -r ubuntu.16.04-x64`
- `cd bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish`
- `chmod +x webapi`
- `./webapi`

# Expected behavior
The app runs.

# Actual behavior
```
Error: assembly specified in the dependencies manifest was not found probably due to missing runtime store associated with manifest.linux-x64.xml -- package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.0-preview1-24647', path: 'lib/netstandard1.3/Microsoft.AspNetCore.Antiforgery.dll'
```

# Environment information
```
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1
```

**Comment by eerhardt** [comment]
I've tested this scenario with both the [.NET Core 2.0 Preview 1](https://www.microsoft.com/net/core/preview) and with the [latest preview 2 build](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-dev-win-x64.latest.zip).  Both ran as expected.

We may have had a bug either in the SDK or in the webapi template at the time.  When an app is published as self-contained, it should never use the store.  All of the dependencies should be contained in the publish folder. This is the behavior I'm seeing in both builds.

Closing.
