### ISSUE TITLE
Major floating versions causing errors when restoring

### ISSUE THREAD

**Issue by mrahhal** [dotnet/sdk#1161]
```xml
<PackageReference Include="Foo" Version="*" />
```

`dotnet restore` fails with the following error:

```
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'Foo' for '.NETFramework,Version=v4.6.1'. [...]
```

In some other cases, it's giving me:

```
error: Package 'Foo' is incompatible with 'all' frameworks in project '...'
```

However, if I specify the exact version, or a version like "1.0.0-*' it works. Note that both the referenced project and the source project are targeting "net461".

Looking into the source code of parsing those floating versions, I don't think this is a nuget issue. Tried Minor and Patch floating versions and also didn't work.

**Comment by livarcocc** [comment]
@mrahhal what do you mean by referenced project? Are you building a nupkg for the referenced project, putting it in a place configured in your NuGet.Config and referencing it?

Or is it simply a project that you have in your source tree? If that's the case, you need to reference it with a ProjectReference. Also, any chance this reference already exists in some feed and when you use * it gets rolled to a higher version that does not happen to support net461?

**Comment by mrahhal** [comment]
The referenced project (I'm calling "Foo") is a nuget package I'm publishing in a private myget feed. I checked the public nuget feed for the existence of a package by the same name but there isn't (the name is long and unique anyway).

Tried referencing it from a scratch new project just to make sure and the same problem occurred. Maybe Nuget/Home#5127 is related?

**Comment by bsmayer** [comment]
+1

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5161
