### ISSUE TITLE
dotnet store creates manifest that does not match the actual store produced if referencing an assembly contained in the shared framework but with a different version.

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1162]
The problem seems to be a manifest that includes newer versions of assemblies that exist in the runtime. 

I have created a minimum repro at https://github.com/JunTaoLuo/DotnetStoreSharedFrameworkPackage.

For example, the manifest (csproj) includes a reference to Microsoft.Win32.Registry: 4.4.0-preview2-25228-02 which is different from the one inside shared framework 2.0.0-preview1-002101-00. After running the command `dotnet store --manifest .\DotnetStoreSharedFrameworkPackage.csproj -f netcoreapp2.0 -r win-x64 -o .out -w .work --framework-version 2.0.0-preview1-002061-00`. The manifest produced (.out\x64\netcoreapp2.0\artifacts.xml) contains the entry `<Package Id="Microsoft.Win32.Registry"  Version ="4.4.0-preview2-25228-02"/>` However the store itself is empty does not contain Microsoft.Win32.Registry.dll

The result of this mismatch between the store and the output manifest (artifacts.xml) means when we publish and trim the publish packages with the output manifest, the expected version of Microsoft.Win32.Registry is removed from the publish output. On the target machine where the store is installed, the app cannot load the expected version of Microsoft.Win32.Registry and the app crashes at runtime.

We will need to either include the version of the assembly in the cross-gen output or remove it from the output manifest.

cc @ramarag @eerhardt @gkhanna79

**Comment by JunTaoLuo** [comment]
Environment information:
```
C:\gh\tp\DotnetStoreSharedFrameworkPackage [master ≡ +5 ~0 -0 ~]> dotnet --info
.NET Command Line Tools (2.0.0-preview1-005899)

Product Information:
 Version:            2.0.0-preview1-005899
 Commit SHA-1 hash:  ea746bd0dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\johluo\.dotnet\x64\sdk\2.0.0-preview1-005899\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```

**Comment by eerhardt** [comment]
It looks like Microsoft.Win32.Registry is contained in the Shared Framework, and has a separate NuGet package outside of Microsoft.NETCore.App.

@ericstj @weshaggard - I thought the assemblies in the Shared Framework were no longer going to be in separate nuget packages?  Isn't this the issue with 1.0 and 1.1 where having a reference to a higher version now pulls you out of the shared framework?

/cc @Petermarcu

**Comment by weshaggard** [comment]
> I thought the assemblies in the Shared Framework were no longer going to be in separate nuget packages?

Some of them do still have individual packages in cases where they carry assets for supporting more then just .NET Core. That is the case for Registry as we have assets that support desktop and other places.

**Comment by ramarag** [comment]
This is related to https://github.com/dotnet/sdk/issues/1023

@weshaggard @dsplaisted is the package level conflict resolution logic available in sdk when assemblies conflict with M.N.App

**Comment by ramarag** [comment]
@JunTaoLuo there is a workaround, there is a catch you should not refer to any library that is built against pre 2.0 FX

you can pass ```/p:SkipRemovingSystemFiles=true```, this will not assume the FX assemblies have precedence over the explicitly defined  packages

**Comment by eerhardt** [comment]
I spoke with @JunTaoLuo last night.  My understanding is that this issue should not be blocking.  ASP.NET should not be using `preview2` libraries in their `preview1` runtime store.

@JunTaoLuo @Eilon - please correct me if I'm wrong.  And if so, please explain how this issue is blocking.

**Comment by eerhardt** [comment]
@ramarag - maybe the right thing to do here is to also trim the `Microsoft.NETCore.App` packages from the output `artifacts.xml` manifest file.  That way we aren't "lying" in the file saying that `Microsoft.Win32.Regstry` was put in the runtime store, when it really wasn't.

**Comment by kichalla** [comment]
cc @mikeharder

**Comment by mikeharder** [comment]
@eerhardt : We will remove the `preview2` packages from our `preview1` feeds and test this again.  We're not sure yet if this will unblock.

**Comment by JunTaoLuo** [comment]
To update, this issue is blocking ASP.NET and it's not only because of `preview2` libraries in `preview1`. For preview1, we needed a fix in SqlClient in `4.4.0-preview1-25301-03` this version is newer than the one in the shared framework version `2.0.0-preview1-002101-00`. This version mismatch means we cannot load the correct version of `Microsoft.Win32.Regstry`. Wondering if we can get a newer build of the shared framework with the updated SqlClient. However, in general the mismatch between the manifest and what's actually in the store is a problem.

**Comment by JunTaoLuo** [comment]
Will try again with the latest shared runtime 2.0.0-preview1-002106-00, this might let us work around the problem by aligning packages.

**Comment by DamianEdwards** [comment]
@JunTaoLuo is there something for us to try again here?

**Comment by JunTaoLuo** [comment]
Will need to test @ramarag's fix once it goes in.
