### ISSUE TITLE
Segmentation fault (core dumped) - NetCore 3.0

### ISSUE THREAD

**Issue by eloraiby** [dotnet/sdk#11639]
After updating to 3.0.1 on Linux Mint:

When running `dotnet new console -n cs-hello`
I get :
`Segmentation fault (core dumped) `

info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19
 OS Platform: Linux
 RID:         linuxmint.19-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Removing `DOTNET_CLI_TELEMETRY_OPTOUT=1` fixes the problem.
Consequently, putting back `DOTNET_CLI_TELEMETRY_OPTOUT=1` after first run won't cause the problem to re-occur again.

**Comment by g14wx** [comment]
Same problem, but when I create a new project with rider its get created.

**Comment by Wowo10** [comment]
Same here on fresh Manjaro.

**Comment by Wowo10** [comment]
Oh I have figured it out. Don`t use snap version - just install via pacman.
`sudo snap remove dotnet-sdk`
`sudo pacman -S dotnet-sdk`

**Comment by GoodPie** [comment]
@Wowo10 Using the snap version also resulted in seg fault. Using the pacman implementation resolved the issue for me although it's not in the documentation

**Comment by mertturkmenoglu** [comment]
Removing snap package and installing it via `apt-get` worked for me.
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2104-

**Comment by davidljuba15031979** [comment]
> Oh I have figured it out. Don't use snap version - just install via pacman.
> `sudo snap remove dotnet-sdk`
> `sudo pacman -S dotnet-sdk`

For Ubuntu 21.04 used `apt`:

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2104-

**Comment by janvorli** [comment]
This was a snap issue, closing.
