### ISSUE TITLE
Delay resolution of TargetManifestFileList until Publish

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1164]
Currently the `TargetManifestFileList` is resolved as a global item group [here]( https://github.com/dotnet/sdk/blob/39102ec214514363c6af4cd9d599a35aceb8c745/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Publish.targets#L32-L34). 

It would be convenient for us if this resolution was delayed until the `Publish` target so that we can specify `TargetManifestFiles` in our own target before `Publish` where we can insert logic to decide which manifest(s) to include.

**Comment by eerhardt** [comment]
This was actually solved with #1245 sort of unconsciously.

There is a new target `_ParseTargetManifestFiles` that turns `TargetManifestFileList` into `@(RuntimeStorePackages)` items.  So if you run a target before `Publish` to insert the files to `$(TargetManifestFileList)`, it will now pick it up correctly.

Closing as fixed.

**Comment by natemcmaster** [comment]
@eerhardt will #1245 make it into preview2?

**Comment by eerhardt** [comment]
Yes it is already in preview2.  I just verified this fix is in the SDK `2.0.0-preview2-006191`.

**Comment by natemcmaster** [comment]
Thanks :)
