### ISSUE TITLE
Cannot update global.json since 3.x (global.json VS update in place ?)

### ISSUE THREAD

**Issue by tebeco** [dotnet/sdk#11648]
Hello everyone,

Since 3.x the `dotnet sdk` shipped as an `msi` on windows is supposed to do some sort of "update in place"
It seems that running `dotnet` is still looking for the SDK pointed at by the `global.json` even this it's the same Major/Minor/Feature band

Here is a weird scenario:
* Install SDK msi `3.1.201`
* `mkdir foo; cd foo;`
* `dotnet new globaljson --sdk-version 3.1.201`
* install SDK msi `3.1.202`
* `dotnet new globaljson --sdk-version 3.1.201 --force` <== FAIL
* `dotnet --info` <== FAIL

As you can see, moving out of the folder (no more `global.json`), make it work again
==> this means that there's no way to actually "Update" the SDK version anymore, it have to be delete and re-created
NOTE: this would be a bigger issue if your `global.json` looked like this:
https://github.com/dotnet/aspnetcore/blob/master/global.json
(because that would be a manual edit of the file here)

![image](https://user-images.githubusercontent.com/2266487/81936401-82f5ea00-95f2-11ea-8558-e01ea2631e7f.png)
![image](https://user-images.githubusercontent.com/2266487/81936600-d49e7480-95f2-11ea-9ac7-da6702bb6c47.png)

**Comment by sfoslund** [comment]
With .NET Core 3.X we have begun uninstalling previous patches (the last two numbers in the version) on update. Here, 3.1.201 is a lower patch of 3.1.202 so it is uninstalled, so this behavior is expected.

**Comment by tebeco** [comment]
so this is intended that a compliant SDK installed make `dotnet` crash ?

**Comment by sfoslund** [comment]
Yes, it is expected, this is the same behavior as if you were to specify any version that doesn't exist on the machine in a global.json. If the SDK cannot be resolved then no commands will work, including global.json related commands.

**Comment by tebeco** [comment]
so we should get rid of global.json if it does not support anymore patch update ?

**Comment by sfoslund** [comment]
The logic global.json uses for selecting a SDK and falling back if the specified SDK cannot be found can be configured using the `rollForward` option, see the docs [here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward).
