### ISSUE TITLE
Cannot build dotnet/roslyn: "It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier."

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/sdk#1165]
I've `git -clean xdf` 'd my enlistment, gotten latest, and now I can't build because of this error:

```
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. [C:\src\roslyn-internal\Open\src\Test\DeployCoreClrTestRuntime\DeployCoreClrTestRuntime.csproj]
```

**Comment by nguerrera** [comment]
If the project has SelfContained=true and RuntimeIdentifier is empty, this error is expected. If it's working in some environments, it is likely because those environments have an older SDK.

**Comment by nguerrera** [comment]
This was fixed on the roslyn build side. The older version of the SDK had no concept of SelfContained so it was ignored (like any other random variable). The usage was in fact incorrect for versions that had this concept as reported by the error.
