### ISSUE TITLE
Add notification for new .NET versions via the CLI

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#11667]
I just noticed the following experience with PowerShell. We should consider adding something to the .NET CLI (not necessarily for every verb) that does the same thing. At the very least, with `dotnet --info`.

![image](https://user-images.githubusercontent.com/2608468/82079974-9a87ae00-9698-11ea-94a2-484f17672138.png)

**Comment by SteveL-MSFT** [comment]
Take a look at https://github.com/PowerShell/PowerShell-RFC/blob/master/5-Final/RFC0052-Notification-On-Version-Update.md for some design considerations we made in PowerShell.  Many may not apply to .NET CLI.

**Comment by sfoslund** [comment]
We have a similar feature planned for .NET 6 being tracked here: https://github.com/dotnet/sdk/issues/14958
