### ISSUE TITLE
.NET Core 2.0 restore imports .NET Framework targets from packages

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#1166]
The implicit PackageTargetFallback in Microsoft.NET.Sdk.BeforeCommon.targets causes .NET Framework targets to be imported into .NET Core 2.0 projects.

### Repro
Run dotnet restore on this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.linux" Version="1.1.4" />
  </ItemGroup>

</Project>
```
SQLitePCLRaw.lib.e_sqlite3.linux contains a file in `build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets`

### Expected

`build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets` should not be imported.

### Actual

`build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets` is imported because PackageTargetFallback is set to include net461.

Implicit PackageTargetFallback was added in https://github.com/dotnet/sdk/pull/1133

cc @livarcocc @JunTaoLuo @ericsink

**Comment by JunTaoLuo** [comment]
Can we clarify how we plan to fix this?

cc @livarcocc @Eilon @DamianEdwards

**Comment by muratg** [comment]
@livarcocc Any ideas what the plan for this one is?  One outcome of this is https://github.com/aspnet/Microsoft.Data.Sqlite/issues/360.  (Unwanted files in your publish folder when trimming)

**Comment by livarcocc** [comment]
@rrelyea @dsplaisted I was under the impression that NuGet was going to do some work to try soft-fallback. I wasn't aware of anything else required from the SDK for this. At least, from the last meeting I attend on this topic.

**Comment by anangaur** [comment]
@livarcocc even with the soft-fallback (now called ATF=AssetsTargetFallBack), the original problem will persist. i.e. `build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets` will be imported because AssetsTargetFallback is set to include net461. This is because there is n NS2 compatible TFM found in this package and hence the net461 target fallback would bring in the above targets file.

@rrelyea @emgarten to comment more on this.

**Comment by dsplaisted** [comment]
@anangaur I think ATF should fix this if correctly implemented.  It shouldn't look at whether there are specifically any TFMs compatible with NS2 in the package, it should look at whether there are any compatible assets in the package at all for NS2.  The files under the runtimes folder of this package are compatible/applicable to NS2.

**Comment by anangaur** [comment]
@dsplaisted `SQLitePCLRaw.lib.e_sqlite3.linux` has no ref or lib asset groups(folders) but only build. And in this case, the package gets installed and with ATF, the `build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets` will be pull in to the project.

The behavior would be as highlighted ([Full spec](https://github.com/NuGet/Home/wiki/Enable-.NET-Core-2.0-projects-to-work-with-.NET-Framework-4.6.1-compatible-packages)):
![image](https://cloud.githubusercontent.com/assets/14800916/26771672/fe245018-4974-11e7-86ce-fd84a22c1897.png)

cc @emgarten

**Comment by DamianEdwards** [comment]
@davidfowl

**Comment by livarcocc** [comment]
@natemcmaster Having an implicit ATF to net461 is the current POR for 2.0. I am going to close this issue. If there is anything else that we can address, please, re-activate the issue.
