### ISSUE TITLE
How to get a project to build if a referenced project changed on a custom target?

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/sdk#11676]
Not sure if this is the best place to ask this, but I'm currently working on an SDK target for a [C# to JS compiler](https://github.com/theolivenbaum/h5) - and hitting an issue I can't figure out how to get a project to build if one of its related project dependencies changed.

The [target](https://github.com/theolivenbaum/h5/blob/master/H5/H5.Build.Target/Sdk/Sdk.targets) is partially based on [Microsoft.NET.NoTargets](https://github.com/microsoft/MSBuildSdks/tree/master/src/NoTargets) and [Microsoft.NET.Sdk](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L164) targets.

What I'm seeing is this:

1. **Project A** references **Project B**
1. change one file on **Project B**
1. Trigger build on Visual Studio for **Project A**.
1. **Project B** is built ✔,  but **Project A** is not ❌

I can see that the target is triggered, but as it doesn't identify that a dependency changed, it does nothing. And I cannot find out what is the  correct way this is implemented on the existing [Microsoft.NET.Sdk](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L164) target.

Any suggestions or examples I could look into for how to achieve this?

**Comment by sfoslund** [comment]
@theolivenbaum it looks like your linked issue has been closed, is this still relevant?

**Comment by theolivenbaum** [comment]
Hi @sfoslund , no can close here, managed to figure out how to change the target to accomplish it!
