### ISSUE TITLE
"ResolvePackageDependencies" task failed unexpected

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1170]
_From @MiaomiaoHuangfu on April 21, 2017 10:18_

- Copy the file \\scratch2\scratch\jinuj\TestSceanrio\MultiTargetting.zip to the machine and extract it;
- double click the .sln file, auto restore completed with 4 errors:
 ![restorewitherros](https://cloud.githubusercontent.com/assets/22901391/25273319/e18461de-26bd-11e7-9d27-22b9fe73ea0f.png)

- Close the solution and reopen it, restore completed but still with 2 errors:
The "ResolvePackageDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
![restorewitherros2](https://cloud.githubusercontent.com/assets/22901391/25273393/34b375ac-26be-11e7-9325-2caa65b17c82.png)

Expected result: restore completed with no errors or warnings.

Test on d15prerel.26420.02;
OS: windows 10 X64

_Copied from original issue: dotnet/project-system#2044_

**Comment by nguerrera** [comment]
From the screenshot, it looks like CoreCL project is referencing an old version of Microsoft.NET.Sdk as a PackageReference. I don't have access to the zip right now to confirm, though.

If I'm right, the project needs to be updated to import the Sdk via `<Project Sdk="Microsoft.NET.Sdk">`...

**Comment by nguerrera** [comment]
I've confirmed that the projects have PackageReferences to pre-RTM package version of the SDK. They need to be migrated to the `<Project Sdk="Microsoft.NET.Sdk"` syntax.
