### ISSUE TITLE
Resx Files not added/picked up in the context of a packaged .Net Core 3.1 project 

### ISSUE THREAD

**Issue by vibkumar** [dotnet/sdk#11704]
Not sure if this is the right path for the issue, but please help redirect if it's not!

I have a .net core 3.1 project with resx files that I added for localization. On app start, I do something like:
            CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("fr-FR");
            CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("fr-FR");
            CultureInfo.CurrentUICulture = new CultureInfo("fr-FR");
            Strings.Culture = new CultureInfo("fr-FR");

When I run the wpf app project this works (and it picks up the fr resources that I have). 

However, if I run this from the context of a packaging project, the language always defaults to the default one I have. I noticed that in the *deps.json file for the packaging project located at WAP\bin\x64\Debug\AppX\LocalizationSample\LocalizationSample.deps.json **is missing this entry:**

"resources": {
          "fr-FR/LocalizationSample.resources.dll": {
            "locale": "fr-FR"
          }

But the *deps.json for the wpf app project located at LocalizationSample\LocalizationSample\bin\Debug\netcoreapp3.1 **has this entry**. This missing entry is what seems to be causing this issue. What do I need to change so the packaging project knows to add this?

I've attached a sample of what I've tried.
[LocalizationSample.zip](https://github.com/dotnet/sdk/files/4653916/LocalizationSample.zip)

**Comment by marcpopMSFT** [comment]
I believe this is specific to appx tooling so I've filed an internal bug on them.  Once I get confirmation, I'll close this bug out and let you know.

**Comment by marcpopMSFT** [comment]
Got confirmation from the appx team and there is now an internal bug tracking this issue.  Thanks for reporting it.

**Comment by rkops-bd** [comment]
Any idea when this bug will be fixed?
