### ISSUE TITLE
With .Net 5 preview5 installed, the default TargetFramework is netcoreapp5.0 when creating Winforms/Wpf project.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#11706]
**Steps to reproduced:**
Install SDK 5.0.100-preview.5.20268.9(runtime-5.0.0-preview.5.20263.12) from https://github.com/dotnet/installer/tree/master.
Using CLI, create a Wpf project.

**Expected Result**
The default target framework is "net5.0".

**Actual Result:**
The default target framework is "netcoreapp5.0" rather than "net5.0".
![image](https://user-images.githubusercontent.com/65637796/82404385-bffb2a00-9a93-11ea-915a-918115133717.png)

Dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20268.9
 Commit:    449ce4b3e7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\dotnet\x64\sdk\5.0.100-preview.5.20268.9\

Host (useful for support):
  Version: 5.0.0-preview.5.20263.12
  Commit:  c39954c069

.NET SDKs installed:
  5.0.100-preview.5.20268.9 [D:\dotnet\x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.5.20265.8 [D:\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20263.12 [D:\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20263.1 [D:\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by donJoseLuis** [comment]
@grinrag we should move this to the templating repo
