### ISSUE TITLE
Dotnet publish for Alpine failing with PublishReadyToRun=true    

### ISSUE THREAD

**Issue by Lonli-Lokli** [dotnet/sdk#11750]
1. Create empty .Net Core 3.1 WebApi application
2. Run
` dotnet publish  -c Release  -o ./output  -r alpine-x64  /p:PublishReadyToRun=true   
`

Exception happens:
```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 149.86 ms for /Users/lonli-lokli/RiderProjects/AlpinePublishTest/AlpinePublishTest/AlpinePublishTest.csproj.
  AlpinePublishTest -> /Users/lonli-lokli/RiderProjects/AlpinePublishTest/AlpinePublishTest/bin/Release/netcoreapp3.1/alpine-x64/AlpinePublishTest.dll
/usr/local/share/dotnet/sdk/3.1.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(270,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [/Users/lonli-lokli/RiderProjects/AlpinePublishTest/AlpinePublishTest/AlpinePublishTest.csproj]
```

**Comment by joeloff** [comment]
You're building on Windows and targeting alpine-x64? There are some combinations that are unsupported.

**Comment by Lonli-Lokli** [comment]
@joeloff I'm building on MacOS and targeting alpine-x64.
Is there any documentation what set of options are supported per OS?

**Comment by joeloff** [comment]
There isn't a specific list in 3.1. From what I can tell, it only supports x86, x64, arm, and arm64. The platform and architecture are split out from the [RID](https://github.com/dotnet/sdk/blob/a99cb0ac6abb55577041c096a75ff7008a807994/src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs#L362), so you're good on architecture. What's seems to be blocking is that there's a second check to ensure the [host and target platforms match](https://github.com/dotnet/sdk/blob/a99cb0ac6abb55577041c096a75ff7008a807994/src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs#L96), which wouldn't be the case for alpine and MacOS

It looks like crossgen effectively allows you to target a different architecture, but it must be the same platform.

**Comment by Lonli-Lokli** [comment]
@joeloff thanks for the explanation, closing.
