### ISSUE TITLE
dotnet pack takes dependencies from other .csproj file!

### ISSUE THREAD

**Issue by joelharkes** [dotnet/sdk#1177]
I have an an repo like this

```
\src
-\RestClient
--\Models\..
--\Api\..
--\Client\..
--\RestClient.csproj
--\RestClient.Models.csproj
\solution.sln
```

My RestClient.Models.csproj consists of:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Model\*.cs" />
  </ItemGroup>
</Project>
```

Now when i run `dotnet pack -c Release`. But in the .nupkg their are now dependencies that i register in the `RestClient.csproj`, instead of having no dependencies!

in Nuget Package Explorer:
![image](https://cloud.githubusercontent.com/assets/2960938/25697966/54695458-30bd-11e7-96eb-9fafad8be9ab.png)

## Expected result

I Expect to have no nuget package dependencies!

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5165
