### ISSUE TITLE
PublishSingleFile Failure Must Specify Host Binary

### ISSUE THREAD

**Issue by classifieds-dev** [dotnet/sdk#11782]
Hello, I'm working on a .NET 3.1 serverless application and am hoping to significantly reduce the size of the program uploaded to aws lambda using PublishSingleFile. I have been successful in using all the other optimization features such as;  publish ready to run and trimming. However, when publish single file is enabled on both my local host (run time identifier = osx.10.13-x64) and remote gitlab build machine (run time identifier = linux-x64) the following error occurs in both scenarios when publishing.

/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [/Users/toddzmijewski/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018: System.ArgumentException: Invalid input specification: Must specify the host binary [/Users/toddzmijewski/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [/Users/username/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [/Users/usernamei/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/username/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/username/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]
/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/usernamei/Projects/Classifieds/src/Classifieds.Chat/Classifieds.Chat.csproj]

I managed to track down this issue which seems like it might be semi-related.

https://github.com/dotnet/runtime/issues/3739

Here is my project file.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerComposeProjectPath>../../docker-compose.dcproj</DockerComposeProjectPath>
    <UserSecretsId>a7034702-8808-492e-ac99-2cb8f6de5986</UserSecretsId>
    <!-- <RuntimeIdentifier>linux-x64</RuntimeIdentifier> -->
    <RuntimeIdentifier>osx.10.13-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <AWSProjectType>Lambda</AWSProjectType>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="CassandraCSharpDriver" Version="3.14.0" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.3" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="AWSSDK.ApiGatewayManagementApi" Version="3.3.101.103" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Classifieds.Shared\Models\ChatMessage.cs;..\Classifieds.Shared\Models\ChatConnection.cs;..\Classifieds.Shared\Models\ChatConversation.cs;..\Classifieds.Shared\Models\PublicUserProfile.cs;;..\Classifieds.Shared\Services\AuthApi.cs;">
        <Link>_Inlined\Classifieds.Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Remove="bootstrap" />
  </ItemGroup>
  <ItemGroup>
    <None Include="AmazonRootCA1.pem" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Mappings\" />
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bootstrap">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```
This is the build command which I'm running.

dotnet publish src/Classifieds.Chat/Classifieds.Chat.csproj --self-contained true --runtime osx.10.13-x64  -p:AssemblyName=bootstrap;PublishReadyToRunShowWarning=true

**Comment by swaroop-sridhar** [comment]
> Hello, I'm working on a .NET 3.1 serverless application and am hoping to significantly reduce the size of the program uploaded to aws lambda using PublishSingleFile.

Also `PublishSingleFile` doesn't reduce size, it just packages various files into one. 
`PublishTrimmed` attempts to reduce size by eliminating unnecessary IL.
`PublishReadyToRun` will typically increase the size because of native code compilation.

**Comment by agocke** [comment]
No repro, so not actionable at the moment

**Comment by eduherminio** [comment]
@swaroop-sridhar @agocke I'm facing the same issue:
```
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018: System.ArgumentException: Invalid input specification: Must specify the host binary [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(898,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\temp\Lynx\src\Lynx.Cli\Lynx.Cli.csproj]
```

I can provide a repro:

```bash
git clone https://github.com/lynx-chess/Lynx
cd Lynx/src/Lynx.Cli
git checkout native-aot
dotnet publish -c Release /p:PublishSingleFile=true --runtime win-x64 --self-contained
```

Happy to have this one reopened, or just create a separated one to track it.

**Comment by agocke** [comment]
@eduherminio It looks like you're trying to use single-file with NativeAOT, is that correct? That should be unnecessary. NativeAOT always publishes a single-file.

**Comment by eduherminio** [comment]
I see, that's why.
Yeah, without single-file it just works (and produces a single file, as you mention).
It _probably_ shouldn't break though, but I leave that up to you if you consider that's worth having a dedicated issue 😃 
Thanks @agocke!
