### ISSUE TITLE
Cannot publish .NET core project with dependency to C++/CLI .NET core project

### ISSUE THREAD

**Issue by przole** [dotnet/sdk#11780]
I have solution with two simple projects:

- C# .NET Core Console App
- .NET Core C++/CLI library with Runtime Support (/clr:netcore)

Console app has CLI lib as project dependency.

If I try to publish console app:

dotnet publish -r win-x86 -c release

I get error LibCLI.vcxproj(29,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found.

**Comment by dsplaisted** [comment]
I believe you have to use full MSBuild instead of `dotnet` if you want to build a C++ project.  So probably you want to run something like this to publish:

```
msbuild /restore /t:Publish /p:RuntimeIdentifier=win-x86 /p:Configuration=release
```
