### ISSUE TITLE
add Pack=false on implicit framework references in sdk for projects targeting net framework

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#1179]
NuGet just checked in a feature to start packing framework assemblies https://github.com/NuGet/NuGet.Client/pull/1361 (written down as frameworkAssemblyReferences in the nuspec of the resulting nupkg) . It allows one to override this behavior by specifying Pack=false on a Reference to prevent it from being packed.

Sdk targets should mark all the implicit references with Pack=false so they don't get packed by default.

**Comment by natemcmaster** [comment]
Question about expected behavior: will this also filter implicit framework references added from PackageReference?

e.g.:
System.Collections/4.3.0 contains
```xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
```

If I am making a project that references this, should these also be hoisted to my nuspec if my project looks like this?
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
   <ItemGroup>
    <PackageReference Include="System.Collections" Version="4.3.0" />
  </ItemGroup>
</Project>
```

**Comment by davidfowl** [comment]
> If I am making a project that references this, should these also be hoisted to my nuspec if my project looks like this?

No, it shouldn't be hoisted. Nothing gets transitively hoisted like this on pack in nuget. Framework assemblies aren't special.

**Comment by natemcmaster** [comment]
> Transitive hosting happens at consumption time, not pack time.

Ok. This feature may need more work then. I'm currently seeing these references being hoisted into the nuspec.

**Comment by livarcocc** [comment]
I believe this work needs to happen in NuGet though. What this work was tracking was explicitly marking the implicit framework references that the SDK added as Pack=false.

@rohit21agrawal can you take a look?

**Comment by natemcmaster** [comment]
Using dotnet.exe 2.0.0-preview2-006453

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  	<PackageReference Include="System.IO.Compression" Version="4.3.0" />
  	<Reference Include="System.Web" />
  </ItemGroup>
</Project>
```
**Expected nuspec**
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>testlib</id>
    <version>1.0.0</version>
    <authors>testlib</authors>
    <owners>testlib</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="System.IO.Compression" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Web" targetFramework=".NETFramework4.6.1" />
    </frameworkAssemblies>
  </metadata>
</package>
```
**Actual**
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>testlib</id>
    <version>1.0.0</version>
    <authors>testlib</authors>
    <owners>testlib</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="System.IO.Compression" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.6.1" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.6.1" />
      <frameworkAssembly assemblyName="System.Web" targetFramework=".NETFramework4.6.1" />
    </frameworkAssemblies>
  </metadata>
</package>
```

**Comment by rohit21agrawal** [comment]
@livarcocc doesn't look like this is a pack issue, because Pack=false metadata is not being set on mscorlib adn system.web . here is a full diag log from a repro project.

CC: @dsplaisted 

[out.txt](https://github.com/dotnet/sdk/files/1078600/out.txt)

**Comment by davidfowl** [comment]
This is a pretty big regression though. It will also break on older project systems if ever any facades are added as framework assemblies.

**Comment by nguerrera** [comment]
@rohit21agrawal Yes. The issue is probably that we don't apply Pack=false when adding References for framework assemblies added via nuget here: https://github.com/dotnet/sdk/blob/53926511aff4f67456c1ddf99179e6c7280d33c9/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L421

**Comment by nguerrera** [comment]
I can fix it.

**Comment by nguerrera** [comment]
@wli3 will actually be picking this up.
