### ISSUE TITLE
Force SDK locale to English

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/sdk#11836]
Apparently the SDK for .NET 5 has been localized. I'm sure it's great for some people, but I don't want this. I want the SDK to "speak" English, not French.

My Windows language is English, with French regional settings (for date and number format, etc.)
(in other words, CurrentUICulture is English, CurrentCulture is French)

How do I force the SDK to use English?

**Comment by thomaslevesque** [comment]
Any news on this?

For now, renaming the "fr" folder in `%PROGRAMFILES%/dotnet/sdk/{version}` seems to do the trick, but it feels like a hack...

**Comment by dasMulli** [comment]
You should be able to set the `DOTNET_CLI_UI_LANGUAGE` environment variable to a different language.

**Comment by dasMulli** [comment]
Do note that the SDK has been localized for a long time (1.0?), that override was added around the 2.0 timeframe i believe.
So it would be more interesting why it never was localized on your system to begin with..

**Comment by thomaslevesque** [comment]
Thanks @dasMulli!

> So it would be more interesting why it never was localized on your system to begin with..

I was wondering the same thing. I noticed the localization folders in previous versions of the SDK, but I never had to do anything to override the language before. Maybe the heuristics for selecting the default language have changed in 5.0?

**Comment by thomaslevesque** [comment]
I'll close this issue, since there's a [documented](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables) solution

**Comment by thomaslevesque** [comment]
OK, I think I know what the problem is. It's not a problem with the CLI, but with .NET itself.

Consider the following code:
```csharp
static void Main(string[] args)
{
    Console.WriteLine($"Culture:\t{CultureInfo.CurrentCulture}");
    Console.WriteLine($"UI Culture:\t{CultureInfo.CurrentUICulture}");
}
```

If I build and run it in .NET Core 3.1, the output is this:
```
Culture:        fr-FR
UI Culture:     en-US
```
(which is what I expect based on my system settings)

If I build and run it in .NET 5.0, the output is this:
```
Culture:        fr-FR
UI Culture:     fr-FR
```
It looks like .NET 5.0 only considers my regional settings, not my UI language.

**Comment by thomaslevesque** [comment]
https://github.com/dotnet/runtime/issues/37146

**Comment by thomaslevesque** [comment]
It's fixed in preview 5
