### ISSUE TITLE
With .Net 5 preview5 installed in German OS, the welcome texts about using .net5.0 for the first time contain “.Net core” in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#11844]
**Repro Steps:**
1.	Install .net preview5 SDK(5.0.100-preview.5.20272.9) on German OS.
2.	Run “dotnet new console” in CLI.
3.	Welcome texts about using .net5.0 for the first time will be displayed and then check if the contents contain “.Net core”

**Expected result:**
The contents should not contain “.Net core”.

**Actual result:**
“.Net Core” instead of “.Net” is displayed in the contents.

EN(Not repro):
![image](https://user-images.githubusercontent.com/65637796/82972195-02c68000-a007-11ea-95a3-ccc895b2761e.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/82970755-a6159600-a003-11ea-972e-cc4d940e049a.png)

Dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20272.9
 Commit:    ac9984b120

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20272.9\

Host (useful for support):
  Version: 5.0.0-preview.5.20268.11
  Commit:  201841eea7

.NET SDKs installed:
  5.0.100-preview.5.20272.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.5.20272.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20268.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.5.20271.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by donJoseLuis** [comment]
@marcpopMSFT, @KathleenDollard, can you please help us find the proper repository backlog for this issue? The issue is independent of the dotnet new command

**Comment by marcpopMSFT** [comment]
@richaverma1 I believe you are tracking the naming bugs in .net core 5.  Do you know where to route this?

**Comment by richaverma1** [comment]
@marcpopMSFT , I am not sure of the correct repo either. Adding @sfoslund who worked on this naming bug in ENU and @wli3

**Comment by wli3** [comment]
there is a delay between english to translation. You can see all the xlf files still show ".NET core". The loc pass will happen later this month

**Comment by vdanche** [comment]
> For SC, It does not repro as it shows as EN.
> ![image](https://user-images.githubusercontent.com/65637796/82970951-22a87480-a004-11ea-9e12-733b6d95a397.png)
> For TK and JP, will update it when we test next time

Repro on JP

**Comment by vdanche** [comment]
> > For SC, It does not repro as it shows as EN.
> > ![image](https://user-images.githubusercontent.com/65637796/82970951-22a87480-a004-11ea-9e12-733b6d95a397.png)
> > For TK and JP, will update it when we test next time
> 
> Repro on JP
> ![image](https://user-images.githubusercontent.com/65637796/83494381-c43e3300-a4e8-11ea-9a7f-a7601ad669b0.png)

Repro on TK
![image](https://user-images.githubusercontent.com/65637796/84870745-4403fa00-b0b2-11ea-9b3c-c6fcb00631d5.png)

**Comment by vdanche** [comment]
Verify it on VS 16.8 preview 5 + NET 5 RTM SDK from https://github.com/dotnet/installer and it has been fixed.
refer to attachment for details
[#2386_DE SC TR JP_Fixed.zip](https://github.com/dotnet/sdk/files/5390232/2386_DE.SC.TR.JP_Fixed.zip)
