### ISSUE TITLE
With .Net 5 preview5 installed in German OS, the texts contain “.Net core” when building the project via CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#11843]
**Repro Steps:**
1.	Install .net preview5 SDK(5.0.100-preview.5.20272.9) on German OS
2.	Run “dotnet new console” in CLI to create the project.
3.	Run “dotnet build” to build the project via CLI.
4.	Observe the texts displaying when building the project.

**Expected result:**
The texts should not contain “.Net core”.

**Actual result:**
“.Net Core” instead of “.Net” is displayed.

EN(Not repro):
![image](https://user-images.githubusercontent.com/65637796/82972036-ad8a6e80-a006-11ea-956e-8ae41bc08743.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/82971909-6b612d00-a006-11ea-8659-8d919363a69e.png)

Dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20272.9
 Commit:    ac9984b120

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20272.9\

Host (useful for support):
  Version: 5.0.0-preview.5.20268.11
  Commit:  201841eea7

.NET SDKs installed:
  5.0.100-preview.5.20272.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.5.20272.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20268.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.5.20271.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by donJoseLuis** [comment]
@marcpopMSFT & @wli3 , can you guys please take a look?  The symptoms are not related to the templating engine.

**Comment by wli3** [comment]
We will delay between English to all the translations. We will have a round of loc pass later

**Comment by vdanche** [comment]
> For SC, it does not repro as it shows as EN.
> ![image](https://user-images.githubusercontent.com/65637796/82972078-c3982f00-a006-11ea-8aff-e8ddbc90d3e3.png)
> For TK and JP, will update it when we test next time

Repro on JP:
![image](https://user-images.githubusercontent.com/65637796/83484527-b59b5000-a4d7-11ea-8882-2cb26245665d.png)

**Comment by vdanche** [comment]
Verify it on VS 16.8 preview 5 + NET 5 RTM SDK from https://github.com/dotnet/installer and it has been fixed.
refer to attachment for details
[#2387_Fixed.zip](https://github.com/dotnet/sdk/files/5390228/2387_Fixed.zip)
