### ISSUE TITLE
Repeated invocations of dotnet-install.sh will fill TMP directory 

### ISSUE THREAD

**Issue by MattGal** [dotnet/sdk#11858]
See https://github.com/dotnet/sdk/blob/master/scripts/obtain/dotnet-install.sh#L822 

We had all the test machines run out of disk space overnight from just running too many tests.  (in the case I investigated it was about 900 tests on one machine leading to 21 GB of SDKs in the TMP folder).

Thoughts on how to fix: 
- At a minimum, when the job is done successfully the `zip_path` file should be deleted if it exists regardless of content
- Could consider also a more distinct temp file name and cleaning up someDistinctDotNettyName.* in TMP every time.

**Comment by sfoslund** [comment]
This issue was moved to dotnet/install-scripts#45
