### ISSUE TITLE
RuntimeHostConfigurationOptions are not propagated to ILLink task

### ISSUE THREAD

**Issue by marek-safar** [dotnet/sdk#11869]
According to https://github.com/dotnet/designs/blob/master/accepted/2020/feature-switch.md#generate-the-right-input-for-the-linker-in-sdk all names/values from RuntimeHostConfigurationOption with Link == true metadata will be passed to the ILLink task. That's still not the case and none of the values is propagated to the task

@sbomer @vitek-karas

**Comment by vitek-karas** [comment]
Duplicate of #11868
