### ISSUE TITLE
Need to click Uninstall 3 times to actually uninstall .NET Core SDK

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1187]
I've got a tonne of previous versions of .NET SDK installed on my machine (I have no idea why, do we not uninstall these on uninstall of VS?).

It takes 3 clicks of an "uninstall" button to uninstall them:

1. Search for "Apps & Features" in start menu and open it
2. Find Microsoft .NET Core [version] SDK
3. Click Uninstall
![image](https://cloud.githubusercontent.com/assets/1103906/25787817/0f3b7bf8-33e8-11e7-9b53-0d13a6e7ea0b.png)

4. Click Uninstall on the prompt from Window
![image](https://cloud.githubusercontent.com/assets/1103906/25787820/18910aa6-33e8-11e7-8e85-850ebd6bf61c.png)

5. Click Uninstall again 
![image](https://cloud.githubusercontent.com/assets/1103906/25787830/203912f8-33e8-11e7-87cb-5b898b9fe9c8.png)

Why is that last uninstall needed? I've already clicked Uninstall, it should immediately uninstall after 4.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/cli#6695

**Comment by davkean** [comment]
Not sure why I filed this in SDk...
