### ISSUE TITLE
Question: dotnet restore algorithm

### ISSUE THREAD

**Issue by marcino239** [dotnet/sdk#11894]
I am looking to update bazel build rules for dotnet and was wondering if you could point me to dotnet/sdk code which performs restore and conflict resolution.  The specific question I have is say dotnet sdk is version 3.1.1, then there is package Microsoft.EntityframeworkCore in version 3.1.3, how does restore target choose version of for example Microsoft.Extensions.DependencyInjection.Abstractions.dll ?

Thanks!
Marcino239

**Comment by sfoslund** [comment]
Our conflict resolution code lives here: https://github.com/dotnet/sdk/tree/master/src/Tasks/Common/ConflictResolution.

For investigating a specific scenario, I would recommend generating a [binlog](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md), which can give you a better idea of which targets are being called.

**Comment by marcino239** [comment]
Thanks vm!
