### ISSUE TITLE
How to sign the exe created during `dotnet tool install`

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/sdk#11991]
Company requires all the executables running on machine must be signed. I find it hard to achieve this as `dotnet tool install` createx a `.exe` when installing the tool.

Our current CI/CD pipeline is like:
1. `dotnet pack` to generate a `.nupkg` with `app.dll` included in it, and `<PackAsTool>true</PackAsTool>`.
2. Code sign all the EXE/DLL within the `.nupkg`.
3. `dotnet tool install` this package to the server machine.

Finally, we find the third stage generates an unsigned `app.exe` in dotnet global tools folder, then it violates the security requirements.

Is there any guidance on how to make this EXE signed? What I can think of is to generate this EXE in `dotnet build`.  `dotnet tool install` can copy it but not generate it.

**Comment by marcpopMSFT** [comment]
@wli3 can you find the documentation for this and point the customer there?

**Comment by wli3** [comment]
You can reference this doc https://github.com/dotnet/sdk/blob/master/documentation/general/signing-global-tool-packages.md
