### ISSUE TITLE
Implicit includes of resource files should include appropriate metadata

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1199]
Adding a .resx file to an SDK project using Visual Studio results in the following added to the project file:

```xml
  <ItemGroup>
    <Compile Update="Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
```

Ideally, nothing would be added to the project file when you add a .resx to the project.  We may be able to do this in the SDK just by setting the appropriate metadata on the implicit `EmbeddedResource` items and the `Compile` items for `.Designer.cs` files.

**Comment by wli3** [comment]
It need a way to link each other, by convention? I am thinking start from blah.resx, and look for in @(Compile), if there is a file matches blah.Designer.cs then "link" them.

**Comment by dsplaisted** [comment]
Related #1441

**Comment by wli3** [comment]
(Some what related https://github.com/Microsoft/VSProjectSystem/issues/169 https://github.com/dotnet/project-system/issues/1467#issuecomment-327064967)

**Comment by davkean** [comment]
I've done some research on what some of this metadata is used for:

- **LastGenOutput**: 
   - Used by legacy project system to delete the file when generation fails or when the generator is removed. 
   - Used by legacy project system as the document to populate the error list when generator fails. Not needed if we auto-gen the file in obj.
- **DesignTime**: 
    - Used by legacy project system to determine when it's a TempPE input, which is a file that used for WinForms designer so that it has "access" to the types in the project (for binding, etc I think). Not needed at the moment but we'll probably need to revisit when we bring up WinForms.
- **AutoGen**: 
    - Used by legacy project system and extensions to avoid manipulating these files in rename, copy and other manipulations because we're touching their "parent" which already affects it. Don't need if we generate in obj.
- **DependentUpon**:
    - Used to group the file under the specified parent. Don't need if we generate in obj.

Conclusion, we can remove all metadata from the designer file.

**Comment by wli3** [comment]
@dsplaisted @davkean sorry for the long delay. Conclude from David's research, can we close this issue?

**Comment by davkean** [comment]
We never removed the metadata, so the bug is still relevant. We should move to project system.

**Comment by dsplaisted** [comment]
This issue was moved to dotnet/project-system#3764
