### ISSUE TITLE
Package version for ObjectGraphDataAnnotationsValidator 

### ISSUE THREAD

**Issue by boukenka** [dotnet/sdk#12001]
Hello,

I use the ObjectGraphDataAnnotationsValidator to validate some fields in an EditForm
in a Web Assembly ASP.NET Core project
I noticed that the current version of the NuGet package is 3.2.0-rc1.20223.4.
Is this normal? Or should I use another package?

**Comment by marcpopMSFT** [comment]
@rrelyea want me to move this to the nuget repo for ya'll to take a look?

**Comment by boukenka** [comment]
@marcpopMSFT  Thanks for the answer. But I do not really understand your question. I have created an issue about it in dotnet/aspnetcore [https://github.com/dotnet/aspnetcore/issues/23289](url)

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/23289.
