### ISSUE TITLE
project property SupportsDeployOnBuild is not true on ASP .Net core project with Core 2.0 installed

### ISSUE THREAD

**Issue by ravipal** [dotnet/sdk#1203]
Service fabric ASP .Net Core web application targeting the full framework doesn't deploy when Core 2.0 is installed. The project uses a custom target to package the application and the code depends on the project property SupportsDeployOnBuild, which is not true. If Core 2.0 is uninstalled, the property SupportsDeployOnBuild value is true and the package works fine.

Repro steps
1. On VS 2017, install the component 'Service Fabric Tools'
2. Install the dependent components 'Service Fabric Runtime and SDK' from http://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK 
3. Open VS and create a new Service Fabric application new->project->web->service fabric. Select 'Stateless ASP .Net Core'. select Empty web app.
4. Right click on the application project and select package, This will succeed.
5. Now install core 2.0 and package the same application, now it will fail.

**Comment by nguerrera** [comment]
@mlorbetske

**Comment by mlorbetske** [comment]
@vijayrkn any ideas?

**Comment by vijayrkn** [comment]
if websdk is used, then it should get set.
https://github.com/aspnet/websdk/blob/dev/src/Publish/Microsoft.NET.Sdk.Publish.Targets/netstandard1.0/Microsoft.NET.Sdk.Publish.targets#L21 

I can check.

**Comment by nguerrera** [comment]
This issue was moved to aspnet/websdk#206

**Comment by ravipal** [comment]
The project is using websdk as shown below
\<Project Sdk="Microsoft.NET.Sdk.Web"\>
