### ISSUE TITLE
Missing default NoWarn settings when NoWarn is defined in Directory.Build.props

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#1205]
_From @AArnott on May 10, 2017 20:18_

Building in a 15.2 VS Developer Prompt works fine, but when building in a 15.3 Preview prompt, I get lots of errors like this:

```
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.IO' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'StreamJsonRpc' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
CSC : error CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Diagnostics.TraceSource' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [F:\git\DevCore\src\clr\tests\TestService\TestService.csproj]
```

### Repro steps

```
git clone https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/DevCore
cd devcore
cd src\clr
msbuild /t:restore
msbuild
```

If you get other errors, you might run the "init" script in the root of the repo and try to build again.

MSBuild that is broken: 15.3.118.39484
MSBuild that works: 15.1.1012.6693

_Copied from original issue: Microsoft/msbuild#2088_

**Comment by rainersigwald** [comment]
_From @AndyGerlicher on May 10, 2017 23:4_

Is this a compiler error? Or is the input somehow changing after you upgrade to 15.3?

**Comment by rainersigwald** [comment]
_From @AArnott on May 11, 2017 2:28_

The input is not changing. I have one enlistment and two VS command windows open. One works, one doesn't.

**Comment by rainersigwald** [comment]
_From @AArnott on May 11, 2017 2:47_

Good point about it being a compiler error. The differences between the compiler command line are essentially this (in addition to the different path to csc.exe):

```diff
- /nowarn:1701,1702,1705,CS1591
+ /nowarn:CS1591
```

CS1701 is an error in the build output, so the fact that it's no longer being suppressed seems to be what's breaking it. In fact I tried executing the exact same (broken) command line in both VS dev windows and it failed. So it appears to be a breaking change made in msbuild .targets, presumably(?) those owned by Roslyn?

**UPDATED**: this comment was updated with the correct diff and analysis after I realized my first diff was of the wrong command line.

**Comment by rainersigwald** [comment]
_From @AArnott on May 11, 2017 2:48_

This issue was moved to dotnet/roslyn#19425

**Comment by rainersigwald** [comment]
_From @AArnott on May 12, 2017 15:2_

Roslyn closed their issue as an msbuild or .targets change.

**Comment by rainersigwald** [comment]
@AArnott Your repro steps appear useless outside of your team; I'm getting 401 Unauthorized on `https://devdiv.pkgs.visualstudio.com/DefaultCollection/_
packaging/VSIDE-RealSigned-Release/nuget/v3/index.json` as a NuGet restore source.

**Comment by rainersigwald** [comment]
I have updated the title to reflect the real bug here. @AArnott has this is a `Directory.Build.props`:

```
src\Directory.Build.props:    <NoWarn Condition=" $(MSBuildProjectName.Contains('Test')) ">$(NoWarn);CS1591</NoWarn>
src\Directory.Build.props:    <NoWarn>$(NoWarn);CS1591</NoWarn>
```

When this intersects with https://github.com/dotnet/sdk/blob/16b2d88ed0f936734bdf042359de55bd4015591d/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.CSharp.props#L17, it means that the default NoWarn of `1701;1702;1705` is not used, causing this error.

Note that the `Directory.Build.props` settings were getting overwritten before the change to the 2.0 SDK.

**Comment by AArnott** [comment]
@rainersigwald Thanks for the diagnosis. I suspect you're right.
As for my repro steps, anyone at MSFT should be able to pull packages from that feed, but only nuget.exe 4.0 (or VS) can get the access tokens necessary for it (MSBuild and dotnet cannot). Once you have pulled packages once, MSBuild and dotnet can do it after that, so long as the tokens are valid.

**Comment by nguerrera** [comment]
I'm going to close this as by-design. We deliberately changed our props to never overwrite user settings that came earlier. I think whacking user NoWarn (as before) was worse than the current behavior. 

You should just add 1701;1702 to your Directory.Build.props as well when you hit this.

I have filed dotnet/roslyn#19640 in support of simply removing these (IMHO, obsolete) warnings from the compiler altogether. 

I also filed #1232 to remove 1705 from our list as it;s actually an error (so NoWarn of it is useless) and perfectly valid.

If those get through, then we can remove the offending line in our default CSharp props. If not, I think we're stuck with the annoyance in this Directory.Build.props case.
