### ISSUE TITLE
app.config gets overwritten

### ISSUE THREAD

**Issue by Eilon** [dotnet/sdk#1206]
_From @vankampenp on May 9, 2017 11:46_

When including an app.config file in a project, it gets included in the `<PROJECTNAME>.exe.config` with every deployment. 
When reading the app.config file using `ConfigurationManager.AppSettings` in a referred .Net Framework library, it reads the app.config included in the `<PROJECTNAME>.exe.config`, not from the separately distributed file.

So it seems impossible to have different files per site, as the current app.config content is overwritten.

I have specified Build Action: None, and Do Not Copy. The file itself is not copied , but still included in the exe.config on distribution.

_Copied from original issue: aspnet/Mvc#6245_

**Comment by nguerrera** [comment]
@vankampenp This is how app.config is supposed to work and how it has always worked. I don't understand why you want a build of projectname.csproj to not propagate projectname's app.config to projectname.exe.config in the output directory.

**Comment by vankampenp** [comment]
Hi Nick, thanks for the response.
My point is that config files are situational, so you want to be able to deploy a different config in dev, staging and production, and in my case a different one in different production locations. For example to use different databases. If it gets overwritten in deployment, you can only have the same app.config everywhere. The appsettings.json configuration file works that way, it is deployed when it is not there, but not overwritten when redeployed/

I have now found a workaround, I have found a way to have static access to appsettings.json configuration parameters from the .NET Framework code, so I will use that.

Thanks, Pieter
