### ISSUE TITLE
Trigger a build warning when targeting an out of support SDK

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#12060]
Customers today could be targeting older .net core versions in their builds and not know.  Perhaps they aren't even using that version.

We should help them out with a warning message that points them to our support documentation: https://aka.ms/dotnetcoresupport

To determine what's in support, it's probably better to download and access releases.json so we don't have to release a new build just to have this warning start showing up.

**Comment by AraHaan** [comment]
Additionally why not just somehow have the sdk self update instead then warn them that the sdk was self updated to be sure to update their global.json files?

**Comment by joeloff** [comment]
I think both the SDK and the target runtime needs to be checked. E.g. it's possible to use the 3.0 toolset and target an application against 2.0.

**Comment by marcpopMSFT** [comment]
@joeloff any updates on your thoughts on how to asynchronously download and cache the releases.json data that you can share with @timheuer who was asking about it?

**Comment by joeloff** [comment]
During the build or in general?
