### ISSUE TITLE
dotnet list package --outdated --interactive Requests Login For Each Dependency

### ISSUE THREAD

**Issue by JohnnyWombwell** [dotnet/sdk#12077]
While projects will restore (after logging in using the `--interactive` flag), when attempting to list packages from an Azure DevOps source with `dotnet list package --outdated`, I again receive an auth failure with the suggestion to use the `--interactive` flag (there appears to be a warning for each dependency) - as follows:
```
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
error: Response status code does not indicate success: 401 (Unauthorized).
```
When running with the `--interactive` flag I am repeatedly prompted to login - if I persevere, it appears that I have to login for each dependency in the project (this also generates a PAT for each) and after this the `list package --outdated` command succeeds.

I am seeing this on dotnet 3.1.202 and 3.1.101 (on WSL and Windows resp.).

Can any light be shed on this? :)

**Comment by sfoslund** [comment]
@wli3 do we own this area or should this issue be moved?

**Comment by wli3** [comment]
@nkolev92 this should be in Azure Devops layer. Do you know who/where they track the issues?

**Comment by nkolev92** [comment]
Try https://github.com/microsoft/artifacts-credprovider

**Comment by sfoslund** [comment]
This issue was moved to microsoft/artifacts-credprovider#198
