### ISSUE TITLE
Using pack on an executable project

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/sdk#1207]
Is there a way to use the `pack` target to generate a nupkg for tools? That is, on a project with an executable, call `msbuild /t:pack` and have it generate the nupkg and include all the files necessary to run?

**Comment by livarcocc** [comment]
Absolutely, we do that ourselves, here is an example of a csproj that does that: https://github.com/dotnet/cli/blob/master/TestAssets/TestPackages/dotnet-portable/dotnet-portable.csproj.

And you can just invoke dotnet pack on the project (or msbuild pack).
