### ISSUE TITLE
Add warnings when publishing for single-file that uses extraction

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/sdk#12095]
In .net5, single-file apps bundle only assemblies and dotnet config files by default. 
In this configuration, the app doesn't extract any files to disk at startup.

However, the following properties can be set to include additional content in the single-file, but may cause extraction at startup:
* IncludeNativeLibrariesInSingleFile 
* IncludeAllContentInSingleFile 
* IncludeSymbolsInSingleFile 

During publish, issue a warning about extraction to disk when using these options.

**Comment by sbomer** [comment]
Closing in favor of https://github.com/dotnet/sdk/issues/12363
