### ISSUE TITLE
Targeting pack "path" is in consistent

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12098]
In Microsoft.NETCore.App.Ref FrameworkList.xml 

```xml
<File Type="Managed" Path="ref/netcoreapp5.0/Microsoft.CSharp.dll" AssemblyName="Microsoft.CSharp" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="5.0.0.0" FileVersion="5.0.20.25106" />
```

In Microsoft.AspNetCore.App.Ref
```xml
  <File Type="Managed" Path="Microsoft.AspNetCore.Antiforgery.dll" AssemblyName="Microsoft.AspNetCore.Antiforgery" PublicKeyToken="adb9793829ddae60" AssemblyVersion="3.1.0.0" FileVersion="3.100.320.12812" />
```

One starts with "ref/netcoreapp5.0/" one does not. We need to pick one.

**Comment by wli3** [comment]
@dsplaisted which one do you prefer? I think it should be the first one?

**Comment by dsplaisted** [comment]
Looking at the code, it looks like `ResolveTargetingPackAssets` doesn't actually use the `Path` attribute.  It just uses the `AssemblyName` and convention to find the folder.

I think we should still put `Path` in the file and it should be the path relative to the root of the targeting pack, so with the current layout it would start with "ref/net5.0" or "ref/netcoreapp5.0".

**Comment by wli3** [comment]
Ya, but I need to use Path for the new cswinrt pack. I tried to use Path for everything, and it failed due to this issue.

So I will file a bug on aspnet (and other targeting pack producers having this problem)

**Comment by dsplaisted** [comment]
Can you use Path if the file exists there, and if not fall back to the existing logic?

**Comment by wli3** [comment]
@dsplaisted i'll condition to use Path only for the new type of pack. But we should switch to use Path for all when call targeting pack is corrected

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L252
