### ISSUE TITLE
Type exposed using `InternalsVisibleTo` is not available when using `5.0.100-preview.6.20314.3` SDK 

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/sdk#12093]
PowerShell has a dependency on `Microsoft.Management.Infrastructure.dll` which has an internal type `CimMofDeserializer`. It has `System.Management.Automation` in the list of `InternalsVisibleTo`. 

When trying to build `System.Management.Automation` we see the following errors:

```
D:\PSGit\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(323,17): error CS0122: 'CimMofDeserializer' is inaccessible due to its protection level [D:\PSGit\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PSGit\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(324,17): error CS0122: 'CimMofDeserializer' is inaccessible due to its protection level [D:\PSGit\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PSGit\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(327,31): error CS0122: 'CimMofDeserializer' is inaccessible due to its protection level [D:\PSGit\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PSGit\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(335,31): error CS0122: 'CimMofDeserializer' is inaccessible due to its protection level [D:\PSGit\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\PSGit\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(335,129): error CS0122: 'MofDeserializerSchemaValidationOption' is inaccessible due to its protection level [D:\PSGit\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
```

This only happens when we upgrade the SDK version from `5.0.100-preview.5.20279.10` to `5.0.100-preview.6.20314.3`

Repro steps:

1. Clone repository https://github.com/PowerShell/PowerShell.git
1. Update the global.json file to have `5.0.100-preview.6.20314.3`
1. In PowerShell (on Windows), `Import-Module build.psm1`
1. `Start-PSBootstrap` to install the Preview 6 SDK
1. Start-PSBuild -Clean

**Comment by marcpopMSFT** [comment]
@dsplaisted @wli3 Any ideas on what we might have changed here?

**Comment by richlander** [comment]
This is either Roslyn or CoreCLR. I assume the former. This is a low-level error. I don't think msbuild, for example, participates in these checks. 

@jaredpar

**Comment by jaredpar** [comment]
@adityapatwardhan is there a way to generate binary logs when building PowerShell? Basically an argument I can specify that will cause `-binaryLog` to be passed to any msbuild invocations?

@richlander 

> I don't think msbuild, for example, participates in these checks.

It doesn't participate in the checks but msbuild / sdk can participate in whether they're properly emitted into the binaries. That would impact the ability of the checks to succeed. Easiest way to rule that out is get ahold of the DLL that defines `CimMofDeserializer` and check the actual `InternalsVisibleTo` entries

**Comment by adityapatwardhan** [comment]
The assembly comes from here: https://www.nuget.org/packages/Microsoft.Management.Infrastructure.Runtime.Win/2.0.0

**Comment by adityapatwardhan** [comment]
@jaredpar we use `dotnet publish` to build, is there a way to specify `-binarylog`?

**Comment by dsplaisted** [comment]
@adityapatwardhan Yes, `dotnet publish` takes standard MSBuild command line options.  So just add `-binaryLog`.

**Comment by adityapatwardhan** [comment]
Attaching the binlog. 
[ps.zip](https://github.com/dotnet/sdk/files/4795765/ps.zip)

**Comment by jaredpar** [comment]
This looks like an SDK bug. I was able to get the binary logs building on my machine and it appears that when building `System.Management.Automation` as a dependency of `Microsoft.Powershell.GraphicalHost` the wrong `<AssemblyName>` gets passed down. Observe here. 

![image](https://user-images.githubusercontent.com/146967/84968048-6dc91b00-b0ca-11ea-8580-9b21932d0f66.png)

Basically when building `System.Management.Automation` the compiler is passed the name `Microsoft.PowerShell.GraphicalHost`. Hence the compiler correctly rejects the IVT access because it's illegal. Looks like the `<AssemblyName>` is getting messed up somewhere in this pipeline.

You can also just build `System.Management.Automation` directly and note that it builds just fine. The name flows correctly there.

Note: this appears to be during the WPF temp project generation. Not sure if that's relevant or not.

**Comment by richlander** [comment]
Could be related: https://github.com/dotnet/sdk/pull/11805

**Comment by ryalanms** [comment]
https://github.com/dotnet/sdk/commit/9b2e596dd61776a4c05d6faa388513ab85d4175d#diff-a623537ebee239407a19ac49d9cdc9a3R875

One solution is to the _BlockWinMDsOnUnsupportedTFMs target to after CoreCompile.  This preserves the existing target order and fixes the break.

``xml
 <Target Name="_BlockWinMDsOnUnsupportedTFMs"
          AfterTargets="PreBuildEvent"
          DependsOnTargets="ResolveReferences"
``

**Comment by jkoritzinsky** [comment]
@ryalanms's suggestion works perfectly. I'll put up a PR with that change targeting preview 6.

**Comment by marcpopMSFT** [comment]
Jeremy's changed resolved this.
