### ISSUE TITLE
dotnet store for multiple RIDs

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#1210]
We currently build stores and pass in a single runtime identifier to select native assets to place in the store. This works for us for now where our dependencies all contain one RID that's sufficient for each platform but this may change in the future. 

For example, we currently create the store with the RID win-x64 consolidated RID and it just happens that libuv and sqlitepclraw both have native assets with those RIDs. However, it could be possible in the future that we have a dependency that contains native assets for all of win-x64, win7-x64, win8-x64, win10-x64 and we would like to collect all of these assets in one store for windows x64 instead of a store for each RID. Ideally we would want to make the --runtime argument of dotnet store take in multiple arguments to facilitate this. Would this be possible?

cc @gkhanna79 @eerhardt @ramarag

**Comment by gkhanna79** [comment]
It is definitely possible but we should consider it when we have a real scenario for this. This is a nice to have for 2.0.

**Comment by nguerrera** [comment]
We are only making minimal investment in dotnet store moving forward.
