### ISSUE TITLE
Clean up and refactoring ProcessFrameworkReferences

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12117]
https://github.com/dotnet/sdk/pull/11824

There are some clean up need to make for above PR. ProcessFrameworkReferences need to have more unit test. And the methods in ProcessFrameworkReferences is too long.

**Comment by sfoslund** [comment]
#12199 fixes a bug from the original PR and cleans up comments. Leaving this issue open to track refactoring the task as a whole, which is long and convoluted.
