### ISSUE TITLE
'Microsoft.Net.Sdk' specified could not be found.  

### ISSUE THREAD

**Issue by kmukesh2008** [dotnet/sdk#12118]
I am new in WPF core. I just clone this project. While opening project I am getting below error.

Although I cross checked the vs2019 feature like .Net core cross platform  development installed 

'Microsoft.Net.Sdk' specified could not be found.  D:\Code\Downloaded\GitCore\eng\WpfArcadeSdk\tools\ExtendedAssemblyInfo.targets

**Comment by marcpopMSFT** [comment]
@kmukesh2008 Can you run dotnet --list-sdks?
