### ISSUE TITLE
InvalidOperationException: Cannot find compilation library location for package 'xxx'

### ISSUE THREAD

**Issue by lucabriguglia** [dotnet/sdk#1213]
I see this error when adding an application part:

`applicationPartManager.ApplicationParts.Add(new AssemblyPart(assembly));`

I have updated Microsoft.Extensions.DependencyModel to v2.0.0-preview1-002111.

> InvalidOperationException: Cannot find compilation library location for package 'xxx'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart+<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
System.Linq.Enumerable+<SelectManyIterator>d__159.MoveNext()
Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, MetadataReferenceFeature feature)
Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
System.Threading.LazyInitializer.EnsureInitializedCore<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(string compilationContent, string assemblyName)
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, string compilationContent)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(string relativePath, string normalizedPath, Func<RelativeFileInfo, CompilationResult> compile)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(string relativePath, Func<RelativeFileInfo, CompilationResult> compile)
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(string relativePath)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet<IChangeToken> expirationTokens, string relativePath, bool isMainPage)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, string pageName, bool isMainPage)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeResultAsync>d__30.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResultFilterAsync>d__28.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__5.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by livarcocc** [comment]
What version of the CLI are you using? Can you share the output of dotnet --info?

**Comment by lucabriguglia** [comment]
@livarcocc I was using 1.0.4 but I fixed it and now it's targeting the correct one but I'm still seeing the error.

![capture](https://cloud.githubusercontent.com/assets/8679253/26123429/c53164aa-3a72-11e7-85ac-7a5f8a8c3ac3.PNG)

**Comment by livarcocc** [comment]
@eerhardt Can this be another instance of the ref assembly not being found in the store?

**Comment by eerhardt** [comment]
I'm not sure.  I'd need to repro it and debug it.  What is `xxx`?  Is that in your .deps.json file?  Can you attach the .deps.json file?  Also, did you publish your app? Or is this during `dotnet run` or F5 in VS?

**Comment by lucabriguglia** [comment]
xxx is Weapsy.Apps.Text ([Weapsy.Apps.Text.deps.zip](https://github.com/dotnet/sdk/files/1008689/Weapsy.Apps.Text.deps.zip)) which an extension of my CMS (https://github.com/Weapsy/Weapsy - branch VS2017)

The exception is thrown during dotnet run.

**Comment by eerhardt** [comment]
So after doing some investigation on your scenario, you are trying to load an assembly (extension) that doesn't exist in your app's bin folder.  Instead it exists in a separate sub-folder of your app (Apps\Weapsy.Apps.Text).

Has this scenario ever worked?  I don't think it could have ever worked in ASP.NET 1.0-2.0.  @pakrym and I have had conversations about this scenario, but we've never explicitly made it work.  See https://github.com/dotnet/core-setup/issues/625, this scenario isn't explicitly a .NET Core 2.0 scenario.  We have made an API where ASP.NET can enable this scenario themselves.  @pakrym - thoughts?

**Comment by pakrym** [comment]
@lucabriguglia did this ever work? @pranavkm  can clarify it but I don't think MVC supports loading from libraries outside application dependency closure.

**Comment by pranavkm** [comment]
Not out of the box. @sebastienros might have some guidance for this based on Orchard.

**Comment by lucabriguglia** [comment]
@eerhardt @pakrym it was working before and I saw other open source applications doing the same.

**Comment by eerhardt** [comment]
Before what?  What changed when this stopped working?  Can you point me to a SHA in your repo?

**Comment by lucabriguglia** [comment]
@eerhardt before updating to VS2017.
You can clone the master branch and run it in VS2015.

**Comment by eerhardt** [comment]
So I compared the difference between VS 2015 and VS 2017.  The change that happened is that in VS 2017 the Weapsy.Apps.Text project is using the NET.Sdk.Web SDK, which defaults PreserveCompilationContext to true.  In the VS 2015 branch, this project's project.json doesn't have this option set to true.  The fix was to set the property to false, which means the DependencyModel won't try to load the assembly as a "compilation library" anymore.  This aligns with the VS 2015 behavior.

I've created a PR to fix it:  https://github.com/Weapsy/Weapsy/pull/30.

Closing this issue since this is now resolved.

**Comment by lucabriguglia** [comment]
Thanks a lot @eerhardt!

**Comment by lucabriguglia** [comment]
@eerhardt @pakrym are you surprised that it works then? :-)

**Comment by eerhardt** [comment]
> are you surprised that it works then?

No, not after the realization that PreserveCompilationContext was set to false before.  When PreserveCompilationContext is false, then the DependencyModel won't try to load the assembly it was trying to load.  That's why it works.  When it is set to true, the assembly will try to be loaded, but it won't be able to be found since it is in a place where DependencyModel doesn't know to look.

**Comment by garnastics** [comment]
I'm having a similar issue with a different DLL, this one from SpreadSheetGear - "InvalidOperationException: Cannot find compilation library location for package 'SpreadsheetGear2012.Core'".  Will the PR referenced earlier only resolve the issue for the Weapsy DLL, or is it more of a universal fix?

**Comment by eerhardt** [comment]
> Will the PR referenced earlier only resolve the issue for the Weapsy DLL, or is it more of a universal fix?

The PR above was only for the Weapsy project.  The issue was moving from VS 2015 and project.json => VS 2017 and .csproj, the `PreserveCompilationContext` property was changed from `false` in the project.json to `true` in the .csproj, causing the error.

@garnastics - if you want to open a new issue with full repro steps, I can take a look.

**Comment by garnastics** [comment]
I may open an issue.  In the meantime, is it an option for me to set the PreserveComplicationContext myself to see if that resolves the issue?  My project doesn't have a project.json file - it does have a package.json.  Don't know if I can set it in the latter.

**Comment by eerhardt** [comment]
What version of VS are you using?

If your project is an ASP.NET MVC project, you will need `PreserveCompilationContext=true`.  But if it isn't an MVC project, you can try setting the property to false in your .csproj to see.

**Comment by garnastics** [comment]
I'm using VS2017 Community Edition.  It's an MVC app and my project targets .NET Core 2.0.

**Comment by garnastics** [comment]
I went ahead and opened a separate issue.

**Comment by wstaelens** [comment]
https://github.com/aspnet/AspNetCore/issues/2126
