### ISSUE TITLE
dotnet run --no-build does not work when the `platform` environment variable is set

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#12159]
@vincentkam commented on [Tue Jun 23 2020](https://github.com/dotnet/runtime/issues/38274)

### Description
If the environment variable `platform` is set in Powershell, `dotnet run --no-build` errors out with the following message like so:

```
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run  --no-build
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
A minimal repro can be created like so:
```
PS C:\Users\Vincent\scratch> dotnet new console -n "dotnet-platform-env-var-test"
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on dotnet-platform-env-var-test\dotnet-platform-env-var-test.csproj...
  Determining projects to restore...
  Restored C:\Users\Vincent\scratch\dotnet-platform-env-var-test\dotnet-platform-env-var-test.csproj (in 89 ms).

Restore succeeded.

PS C:\Users\Vincent\scratch> cd .\dotnet-platform-env-var-test\
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> $env:platform=""
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run
Hello World!
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> $env:platform="foo"
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run --no-build
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

The work around of course, is to simply unset the environment variable. However, it would be nice to be able to specify the platform without needing to set/unset an environment variable. For example, `dotnet build` sort of supports this via: 
`dotnet build /p:Platform="Any CPU"`
By passing the argument above, `dotnet build` ignores the `platform` environment variable when building.

### Configuration
I've seen this behavior using the following `dotnet` versions:
`5.0.100-preview.3.20216.6` 
`3.1.201` 

The same behavior occurs on Windows 10 and Windows Server 2016.

---

@Dotnet-GitSync-Bot commented on [Tue Jun 23 2020](https://github.com/dotnet/runtime/issues/38274#issuecomment-648229862)

I couldn't figure out the best area label to add to this issue. Please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

---

@jeffschwMSFT commented on [Tue Jun 23 2020](https://github.com/dotnet/runtime/issues/38274#issuecomment-648458702)

@marcpopMSFT is this a CLI issue?

**Comment by marcpopMSFT** [comment]
@jeffschwMSFT Moved it over to the sdk repo.  That environment variable will override all other values and that's kind of how MSBuild was designed so getting an easier workaround is not in the cards. We'll check if the original scenario works with a valid platform value.

**Comment by joeloff** [comment]
The following should work

* ```dotnet build```
* ```set platform=foo```
* ```dotnet build``` this will produce binaries under bin\foo\Debug.
* ```dotnet run --no-build``` this should run.

In your example, you've essentially produced a platform agnostic build, but then when you ran the application, you're telling dontet it has to use a binary for a specific platform, which was never produced.
