### ISSUE TITLE
Publish task needs to take target manifest into consideration when copying refs to output when PreserveCompilationContext is true

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#1216]
When running `dotnet publish` in an ASP.NET Core 2.0 project (created from `dotnet new`), with `<PreserveCompilationContext>true</PreserveCompilationContext>` in the project file, the `refs` directory in the output folder ends up containing every assembly in the graph of the `Microsoft.AspNetCore.All` meta-package, despite the fact that they're also in the runtime store, as specified by the target manifest passed to `dotnet publish` by way of the package's targets.

The publish task needs to be updated to exclude assemblies that are present in the supplied target manifest, as they'll be available on the target server. In effect, it needs to trim those from `refs`, just like it does from publish output.

@pakrym @JunTaoLuo @davidfowl @livarcocc

**Comment by JunTaoLuo** [comment]
Note that to reproduce this from a default project, `MvcRazorCompileOnPublish` must be set to false. See repro at https://github.com/JunTaoLuo/PreserveCompilationContextRefs

**Comment by DamianEdwards** [comment]
Right. Repros more easily with an empty web project.

**Comment by eerhardt** [comment]
This isn't just as straight forward as excluding those assets from the `refs` folder in all cases.  The runtime store only has the runtime assemblies in it.  If a package has separate `compile` assets from the `runtime` assets, then the `compile` assets still need to be copied to the `refs` folder, even though the `runtime` assets are in the runtime store.

Examples of this scenario that exists today are `system.data.sqlclient` and `System.Text.Encoding.CodePages`:

NuGet package:
![image](https://cloud.githubusercontent.com/assets/8291187/26176494/f66428d8-3b1b-11e7-9087-137c9bb82791.png)

Runtime store:
![image](https://cloud.githubusercontent.com/assets/8291187/26176526/0f46cc84-3b1c-11e7-9ef2-dc12b146f17a.png)

**Comment by eerhardt** [comment]
Fixed with #1245
