### ISSUE TITLE
GenerateDepsFile task sometimes fails: "Property with the same name already exists on object"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#1219]
We're seeing an issue in the latest SDK when compiling https://github.com/aspnet/EntityFramework. It doesn't repro everytime, but when it does, 

1. MSBuild issues an error about the GenerateDepsFile task failing on one project
2. MSBuild then hangs indefinitely 

Here is the error message:
```
The "GenerateDepsFile" task failed unexpectedly.\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]                    
System.ArgumentException: Can not add property Microsoft.CSharp to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.\r [C:\dev\aspnet
\EntityFramework\src\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]                                                                  
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFCore.Specification.Tests.
csproj]                                                                                                                                             
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFC
ore.Specification.Tests.csproj]                                                                                                                     
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFCore
.Specification.Tests.csproj]                                                                                                                        
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests
\EFCore.Specification.Tests.csproj]                                                                                                                 
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests
\EFCore.Specification.Tests.csproj]                                                                                                                 
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]           
   at Newtonsoft.Json.Linq.JObject..ctor(Object content)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]            
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.AddDependencies(JObject libraryObject, IEnumerable`1 dependencies)\r [C:\dev\aspnet\EntityFramework\
src\EFCore.Specification.Tests\EFCore.Specification.Tests.csproj]                                                                                   
   at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTargetLibrary(Library library)\r [C:\dev\aspnet\EntityFramework\src\EFCore.Specification.Tests\
EFCore.Specification.Tests.csproj]                                                                                                        
```

**Repro steps**
`git clone https://github.com/aspnet/EntityFramework && cd EntityFramework`
`dotnet restore`
`dotnet msbuild "/t:clean;build" /m /fl`

**Details**
Windows 10 x64
dotnet 2.0.0-preview2-006071

I have process dumps and can share them with anyone who wants to investigate more. Here's the hung MSBuild process and its node process

<img src="https://cloud.githubusercontent.com/assets/2696087/26118849/30088f40-3a20-11e7-9f68-bf961175264c.png" width="600" />

**Comment by nguerrera** [comment]
How often does it repro? Trying to decide if it's worth trying to repro or go straight to the dumps that you have.

**Comment by natemcmaster** [comment]
It might have something to do with Microsoft.CSharp. @kichalla ran into this earlier today when trying to convert https://github.com/aspnet/JsonPatch to netstandard2.0. It may offer a clue, and might be easier to reproduce

From @kichalla 
> I am running into an issue when converting JsonPatch repo. The test project in this repo uses 'dynamic' and Microsoft.CSharp assembly is required for this. This assembly is part of netcoreapp2.0 but for net461 I am explicitly adding a reference to the Microsoft.CSharp 4.3.0 version...however when i do that i get the following error: error MSB4018: The "GenerateDepsFile" task failed unexpectedly. error MSB4018: System.ArgumentException: Can not add property Microsoft.CSharp to Newtonsoft.Json.Linq.JObject.

**Comment by kichalla** [comment]
I have created a PR for the JsonPatch repo https://github.com/aspnet/JsonPatch/pull/81 ...this branch actually fails to compile with the above error that @natemcmaster mentions above...you can try to clone the JsonPatch repo and checkout the branch to try a build at your end to repro...

**Comment by kichalla** [comment]
Here is the error: https://ci.appveyor.com/project/aspnetci/jsonpatch/build/1.0.229#L174

**Comment by DamianEdwards** [comment]
Is this the same as https://github.com/dotnet/sdk/issues/1289?

**Comment by MattGertz** [comment]
@livarcocc Can you confirm & follow back with ETA?

**Comment by kichalla** [comment]
Just FYI...I am not longer hitting this issue and was able to move to netstandard2.0

**Comment by rynowak** [comment]
I have just started hitting this issue by adding 
```
    <PackageReference Include="System.ValueTuple" Version="$(CoreFxVersion)" />
```

to https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/Microsoft.AspNetCore.Razor.Language.csproj

If I change it to 
```
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)'=='.NETFramework' AND '$(OutputType)'=='library'">
    <PackageReference Include="System.ValueTuple" Version="$(CoreFxVersion)" />
  </ItemGroup>
```

Then everything seems fine.

**Comment by nguerrera** [comment]
This is the same as #1289
