### ISSUE TITLE
The 'Publish' target is not supported without specifying a target framework when IsPublishable set to false

### ISSUE THREAD

**Issue by tocsoft** [dotnet/sdk#12196]
calling `dotnet publish` on a solution file that contains projects with multiple target frameworks (`<TargetFrameworks>X;T<TargetFrameworks>`) returns the error `The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application.` even on projects explicitly marked with `<IsPublishable>false</IsPublishable>`.

As with the standard single target publish pipeline I would expect the publish call to be ignored.

should just need `Condition="'$(IsPublishable)' == false"` adding to this target
https://github.com/dotnet/sdk/blob/3704d0ae1e75166204f2ea154c37ca89097dc97d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CrossTargeting.targets#L26-L28

like exists in the standard  Microsoft.NET.Publish.targets target https://github.com/dotnet/sdk/blob/3704d0ae1e75166204f2ea154c37ca89097dc97d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L63-L65

will probably want <IsPublishable Condition="'$(IsPublishable)'==''">true</IsPublishable>` adding to a property group too to be consistent

**Comment by dsplaisted** [comment]
@sfoslund Can you take a look at this?  It looks like a pretty simple fix, but be aware that `IsPublishable` defaults to true in a targets file that probably isn't imported in the outer build of multi-targeted projects, so we'll probably also need to set it to a default value in one of the crosstargeting targets files.

**Comment by sfoslund** [comment]
Fixed in 5.0.2xx by #15402
