### ISSUE TITLE
Implicit package reference to NETStandard.Library.NETFramework

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#1220]
Are there plans to add automatically reference the NETStandard.Library.NETFramework package?

.NET Framework projects referencing a .NET Standard 2.0 library but missing a PackageReference to NETStandard.Library.NETFramework will fail at runtime with:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at TestApp.Program.Main(String[] args)
```

Original issue: https://github.com/dotnet/standard/issues/328. Per conversation there, @weshaggard indicated there was a plan to automatically reference NETStandard.Library.NETFramework when required and that work was tracked by https://github.com/dotnet/sdk/issues/992. 992 is closed, however, and doesn't actually appear to have fixed this issue in preview1 or latest nightly builds of the SDK. I couldn't find another issue tracking this work.

**Comment by weshaggard** [comment]
@livarcocc @dsplaisted @terrajobst @ericstj Can you guys comment on the plans to automatically reference NETStandard.Library.NETFramework? It is my understanding that we will have an implicit reference to it from the SDK tools at least.

**Comment by livarcocc** [comment]
@terrajobst who was driving this.

**Comment by moozzyk** [comment]
+1 for this. I was investigating an issue with a WPF app referencing SignalR Client (which targets netstandard1.3) and without a reference to NETStandard.Library.Network I could not build my app. The error is very hard to grok:
```
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Cannot resolve dependency to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.' 

```

**Comment by dsplaisted** [comment]
We're going to ship this support as part of MSBuild instead of an external NuGet package.  #1267 tracks this
