### ISSUE TITLE
Provide more immediate feedback when an ASP.NET Core app is running

### ISSUE THREAD

**Issue by leahtmsft** [dotnet/sdk#12227]
When you create a new ASP.NET Core app in the command line and run it with `dotnet run`, it can take a few seconds before any feedback is provided to the user (sometimes much longer if it's the first run). In user studies, we saw first-time .NET users get confused about whether the app is running when there initially isn't any output. Consider providing more immediate feedback that the app is building and running. Also, consider improving the app startup performance.

Repro steps: 

1. `dotnet new webapp -o WebApp1`
1. `cd WebApp1`
1. `dotnet run`

Expected: 
Near immediate feedback that the app is building and running

Actual: 
It takes anywhere between 3-30 seconds before any output is displayed.

![U9uyxcCa2W](https://user-images.githubusercontent.com/63820050/85081041-b42c8180-b17f-11ea-9f08-8282a1ded9c0.gif)

**Comment by KathleenDollard** [comment]
[A Twitter conversation indicated that people feel strongly on all sides of this question](https://twitter.com/KathleenDollard/status/1278677579600281603?s=20)

Proposal: Add verbosity to launchSettings.json and display the corresponding verbosity.
Usage: ASP.NET templates will include verbosity:minimal in their templates so new projects have feedback and existing projects are not affected

## Add dotnet run profile to launchSettings.json

```
...
"dotnetRunSettings": {
      "verbosity": "quiet"
}
...
```

Valid options are the standard MSBuild options: quiet, minimal, normal, detailed and diagnostic. Abbreviations will not be supported. 

It is not an error if the entry is not present. In that case, "quiet" will be inferred for backwards compatibility. 

It is not an error if the entry is not present. In that case, "quiet" will be inferred. 

## Outputting info

### verbosity: quiet, no entry, or misspelled entry

Nothing will be output. This is the same behavior as today

### verbosity: minimal 

The single world "Building..." 

```
> dotnet run
Building...
```

### verbosity: normal, detailed or diagnostic

Output with timing:

```
> dotnet run
05:56:37.34: Project build started \
05:56:40.04: Project build completed in 2.7s
05:56:40.31: App is launching
```

If the output with timing means we lose the feature, just do the minimal output.

**Comment by wli3** [comment]
@KathleenDollard @marcpopMSFT I dig the code a bit and realize the majority of the work will be changes in the launchSettings model to add in this property. It should be more on @vijayrkn 's team. Vijay is it possible for your team to get it in net5.0?

**Comment by vijayrkn** [comment]
@wli3 - This is not in our current list of deliverables for .NET 5.0/Fe timeframe. I can get a work-item added to our list but I don't think we will be able to pick it up any time soon because of the other deliverables. 

Adding @timheuer to help with the prioritization for this against our other deliverables.

**Comment by KathleenDollard** [comment]
@vijayrkn This came up with a usability issue that @danroth27 and @DamianEdwards illustrated in relation to Blazor which has a serious impact on new users. Adding them for context with prioritization.

**Comment by marcpopMSFT** [comment]
#12581 has this work and it looks like it's based on dotnetRunMessages being true in the launch settings which is slightly different than the original proposal.  @KathleenDollard

**Comment by RehanSaeed** [comment]
Is there any documentation around what the new `dotnetRunMessages` setting actually does?

**Comment by lonix1** [comment]
There is an explanation for `dotnetRunMessages` on [StackOverflow](https://stackoverflow.com/questions/65923063/purpose-of-dotnetrunmessages-in-launchsettings-json).
