### ISSUE TITLE
How to run a .net core app globally

### ISSUE THREAD

**Issue by Legends** [dotnet/sdk#12267]
My system `path` env varaible is too large, otherwise I'd put it there.
How to do that, wihtout `cd`-ing to the deployment folder?

I tried:
`dotnet tool install -g myConsoleTool --add-source=./nupkg`

cmd.exe: `myConsoleTool `

> Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\appsettings.json'.

The `appsettings.json` file is in the `bin `folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Create a .NET Core console application using Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by wli3** [comment]
@Legends you need to make sure the logic of resolving `appsettings.json` take the account of the folder being copied. A good solution is to start from the dll location and the find the `appsettings.json` in the same folder as the dll.

To run tools without putting it in the path, you can try --tool-path option (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#description)

**Comment by Legends** [comment]
Resolving is not a problem, but when I install it globally, this is what I get:

`dotnet tool install -g gitrepo --add-source=./nupkg`

![image](https://user-images.githubusercontent.com/966368/86055844-b7b3e880-ba5c-11ea-9c2e-dfee9b89ada0.png)

It's a win32 exe, I guess

**Comment by wli3** [comment]
@Legends  the content is in .store folder. So what is the issue? If finding the `appsettings.json` is not the problem

**Comment by Legends** [comment]
I resolve the appsettings.json file like this:

Something wrong with my resolution?

```
 var configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                                                  .AddJsonFile("appsettings.json", false, true)
                                                  .AddUserSecrets<UserSecrets>()
                                                  .AddEnvironmentVariables()
                                                  .Build();
```

![image](https://user-images.githubusercontent.com/966368/86058185-c7353080-ba60-11ea-8fd5-9ae7c96ce09b.png)

**Comment by wli3** [comment]
`Directory.GetCurrentDirectory()` will give you the `current working directly`. It is related to your shell.
You can start from `System.Reflection.Assembly.GetAssembly(typeof(THETYPE)).Location;`

**Comment by Legends** [comment]
Ok, I was confused, because I couldn't see any dependent files next to the `gitrepo.exe`.
Thanks for your support!
