### ISSUE TITLE
error MSB4181: The "PackTask" task returned false but did not log an error.

### ISSUE THREAD

**Issue by aggieben** [dotnet/sdk#12292]
Using the 5.0.0-preview.5.20279.10 SDK on Windows 10, the tooling fails to pack a nupkg for the project located here: https://github.com/aggieben/ConstrainedTypes (`master` branch).

I used the following command:
`dotnet pack -o pkg ConstrainedTypes.fsproj -v diag`.  The error message reported is:
```
"C:\Users\Ben\proj\oss\constrainedtypes\src\ConstrainedTypes\ConstrainedTypes.fsproj" (pack target) (1:7) ->
                   (GenerateNuspec target) ->
                     C:\Program Files\dotnet\sdk\5.0.100-preview.5.20279.10\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error MSB4181: The "PackTask" task returned false but did not log an error. [C:\Users\Ben\proj\oss\constrainedtypes\src\ConstrainedTypes\ConstrainedTypes.fsproj]
```

The exact same command works just fine with SDK version 3.1.300.

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#9786
