### ISSUE TITLE
Running tests with coverage + signed assembly + Directory.Build.props fail on NET5 preview6

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/sdk#12309]
Found with the SDK 5.0.100-preview.6.20318.15
Repro in [this solution](https://github.com/dotnet/sdk/files/4859509/Issue.zip)

Basicaly the solution has 1 class library project, 1 test project. 
The class library has a string name. 
The test project reference the class library.
There is a `Directory.Build.props` file in the src folder.

When running the command `dotnet test -c Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings`, the following error is raised:
`Could not load file or assembly 'ClassLibrary1, Version=1.6.1.0, Culture=neutral, PublicKeyToken=7ef232d6ee17cdab' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`

No issue with SDK 3.1.300

**Comment by marcpopMSFT** [comment]
Closing as this was reported against a preview. Reactivate if it's still an issue in .net 7.
