### ISSUE TITLE
GenerateDepsFile doesn't include file or assembly version for Project references

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#12301]
Create an app with a reference to another project.  Build.  Examine deps file.

Expect: file of referenced project includes file and assembly version.
Actual: versions are missing.

Compare to.  Raw file reference to output TargetPath of the project.  This will include the file and assembly versions.

This hinders a fix for https://github.com/dotnet/runtime/issues/698

**Comment by ericstj** [comment]
Suspect bug is here: https://github.com/dotnet/sdk/blob/b4f6e751571e1be233ca2344181fc3a9efbb4245/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L524-L530

**Comment by ericstj** [comment]
I was able to workaround this by setting the `ReferenceSourceTarget` metadata on the `ProjectReference` to be something other than `ProjectReference`.  This tricks the `GenerateDepsFile` task into treating it as raw file reference instead of a ProjectReference and avoids the bug.

**Comment by baronfel** [comment]
@ericstj we just merged a fix for this in 8.0.4xx, at long last!
