### ISSUE TITLE
launchSettings.json is copied to the output directory in latest 5.x preview

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#12313]
Using CLI/SDK version 5.0.100-preview.6.20318.15 (public preview.6), the `Properties/launchSettings.json` file is now being copied to the output directory when building the project. This was not the case in 3.x

It seems the file now has the `CopyToOutputFolder` property set to `PreserveNewest`. This also causes things like VS FastUpToDate to reevaluate the status of this file on every build invocation.

I think previously no files in the `Properties` directory would ever be copied to the output directory.

Possibly related to https://github.com/dotnet/sdk/commit/fc3c0cc3d41776ed47e98e8c633124944b77802a?

@vijayrkn

**Comment by DamianEdwards** [comment]
OK my bad, this is happening in 3.x SDKs too. Seems it was done as part of the changes to make `dotnet build` produce more output. However it results in things like `launchSettings.json` being included in the set of files to evaluate when determining if a project's output is up to date.

Perhaps known files like this that we know can't effect build output should be explicitly excluded from such evaluation. Is there an existing MSBuild attribute we can apply to it that would exclude it?

@drewnoakes @rainersigwald

**Comment by DamianEdwards** [comment]
Also worth nothing the behavior is different between the various SDKs, e.g. if I add a `Properties/launchSettings.json` file to a new console app project, it doesn't get copied to the output folder. It's the blobs we're adding in the Razor, Web, Worker, etc. SDKs that ends up causing this.

**Comment by drewnoakes** [comment]
> It seems the file now has the CopyToOutputFolder property set to PreserveNewest. This also causes things like VS FastUpToDate to reevaluate the status of this file on every build invocation.

The overhead of this will be minimal unless the source file changes. However it would mean that changing launch profile settings then launching the debugger would kick off a build.

There's currently no metadata that excludes items from the fast up-to-date check. We could add something. I don't know if that's the right call here though.

**Comment by DamianEdwards** [comment]
> The overhead of this will be minimal unless the source file changes. However it would mean that changing launch profile settings then launching the debugger would kick off a build.

You're right, that the above seems to be the more important detail. If we simply changed the includes to not copy `launchSettings.json` to output, would it also solve that problem (assuming it's a `None` item)?

**Comment by drewnoakes** [comment]
Yes, `None` items are ignored by the fast up-to-date check.

**Comment by DamianEdwards** [comment]
OK, so @vijayrkn is making `launchSettings.json` a `None` item type in the wheelhouse of the Web SDK or Worker SDK teams? Or both? They both utilize this file AFAICT.

**Comment by vijayrkn** [comment]
Ack on this. We have a few other glob changes that we are planning to make in websdk. will make sure that covers updating the glob for launchSettings to None (for both web & worker). 

@abpiskunov - Can you take care of this along with your other changes to the glob?

**Comment by vijayrkn** [comment]
Fixed.
