### ISSUE TITLE
global.json rollForward not working when only prerelease versions installed?

### ISSUE THREAD

**Issue by zivkan** [dotnet/sdk#12335]
On my machine I have Visual Studio 2019 Preview installed, and I've also installed a .NET 5 SDK preview. `dotnet --list-sdks` tells me:

```text
3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]
```

I have the following `global.json`

```json
{
  "sdk": {
    "version": "3.1.100",
    "allowPrerelease": true,
    "rollForward": "latestPatch"
  }
}
```

I would expect `dotnet --version` to tell me `3.1.400-preview-015178`, but instead I get this error message:
```text
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [3.1.100] from [C:\src\test\missingSource\global.json] was not found.
      Install the [3.1.100] .NET SDK or update [C:\src\test\missingSource\global.json] with an installed .NET SDK:
        3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
        5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]
```

If I've done something wrong, it's really not clear to me what.

**Comment by marcpopMSFT** [comment]
The rollForward flag is only supported within the same feature band.  In this case, if you had another version of 3.1.1xx installed it would roll forward or if you had specified 3.1.400 it should roll forward to the preview version.  See the details here about feature band: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward
