### ISSUE TITLE
Phase out MULTI_LEVEL_LOOKUP

### ISSUE THREAD

**Issue by alexperovich** [dotnet/sdk#12353]
## Steps to reproduce
* install dotnet sdk 2.0.5 from the msi
* xCopy deploy SDK version 2.0.0 and shared framework version 1.1.2 using dotnet-install.ps1
* run a 1.1.2 portable application using the xCopy dotnet cli

## Expected  behavior
Application runs fine

## Actual behavior
Host exits with error:
```
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.1.2'.
```

## Environment data
global `dotnet --info`
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

xCopy `dotnet --info`
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\a\_work\_tool\dncs\2.0.0\x64\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
COREHOST_TRACE log: [log.txt](https://github.com/dotnet/core-setup/files/1644625/log.txt)

**Comment by ForNeVeR** [comment]
A general proposal to solve this problem is being discussed in #15537.

**Comment by aaronla-ms** [comment]
> The multi-level lookup is a required feature for the development of the ASP.NET repos

I mean, maybe those repos could manually opt in to multi_level_lookup if they desire it. For folks that are engineering at larger scale, it's just not practical do support 100s of developers with different combination of tools installed in their C:\Program Files.

**Comment by richlander** [comment]
Resolved with https://github.com/dotnet/runtime/pull/67022
