### ISSUE TITLE
Single-file: Consider better names for options that extract files to disk

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/sdk#12363]
The following non-default optional settings for publishing single-file apps cause the host to extract certain files to disk at run-time.

[`IncludeNativeBinariesInSingleFile`
 `IncludeAllContentInSingleFile`
`IncludeSymbolsInSingleFile`](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design.md#optional-settings)

These property names suggest the benefit (bundling more files) but not the cost (extraction).
Consider  renaming these options to suggest that content will be extracted.

This work is in lieu of, and probably better than  https://github.com/dotnet/sdk/issues/12095

@samsp-msft  can you please take a look into this? 

CC: @agocke  @vitek-karas

**Comment by sbomer** [comment]
Copying the names discussed in email @vitek-karas @samsp-msft:
- IncludeNativeBinariesForSelfExtract
- IncludeAllContentForSelfExtract
- IncludeSymbolsForSelfExtract

If we are happy with this naming, should I take this issue @samsp-msft?

**Comment by agocke** [comment]
I really like these names, LGTM

**Comment by agocke** [comment]
Ah, one question on the design: It's mentioned that `IncludeAllContent` and `IncludeSymbols` are both for back-compat. What scenario is IncludeSymbols for? It just seems overall worse than embedded PDBs, so I'd like to drop it if possible.

**Comment by vitek-karas** [comment]
The problem with embedded PDBs is that it's a per-assembly choice. So if my app consumes a binary dependency (for example NuGet package) which chose not to include PDBs as embedded, there's nothing I can do about it. Well to be precise we could do something about it, but we don't have that solution yet (for example I can see the linker being able to embed PDBs for everything if asked). My understanding of this option is to be able to handle cases like these.

But I could be wrong...

**Comment by vitek-karas** [comment]
In that sense it's actually similar to `IncludeAllContext` - ideally the app would have everything it needs as embedded resources in the assemblies and then there's no need for self-extract (other than native dependencies obviously), then again it's unrealistic to expect everybody to do that anytime soon.

**Comment by agocke** [comment]
Got it. FWIW, I think we have a wide variety of ways to deal with third-party symbols in most scenarios, including symbol servers and symbol nuget packages, but I can see how this doesn't necessarily address all problems.

I'm fine with keeping the feature, but in general it seems like the symbol story for .NET has become very complicated and if we were looking at this for the first time I'd consider dropping these smaller scenarios in favor of simplicty.

**Comment by vitek-karas** [comment]
I agree with you that one. Maybe we just drop that and keep only the `IncludeNativeLibs` and `IncludeAllContent`. That said I've seen quite a few people who wanted the source/line info in their exceptions even from the "production" environment (typically users machines). That is really only doable if the pdbs are available on the machine itself - symbol servers and so on don't help that much. So maybe there's merit to have this feature (assuming it actually works this way - which we probably didn't verify yet).

**Comment by agocke** [comment]
> quite a few people who wanted the source/line info in their exceptions

Agreed, but even from third-party libraries? I'm sure there are some, but it seems less common.

**Comment by sbomer** [comment]
I just noticed that the existing option is actually IncludeNative**Libraries**InSingleFile, not IncludeNative**Binaries**InSingleFile. Any preference between those? I'll stick with Libraries by default.

**Comment by agocke** [comment]
`Libraries` sounds fine to me

**Comment by agocke** [comment]
@sbomer I think this is ready for a PR when you get a chance.
