### ISSUE TITLE
With .Net 5 preview5 installed in DE/TK/JP OS, the output contains ".Net core"after running “dotnet --info” in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#12395]
1.Install .net5 SDK 5.0.100-preview.7.20357.4.
2.Run "dotnet --info" in CLI and then then check if the contents contain “.Net core”

**Expected result:**
The contents should not contain “.Net core”.

**Actual result:**
“.Net Core” instead of “.Net” is displayed in the contents.

EN(not repro)
![EN](https://user-images.githubusercontent.com/65637796/87020709-d0639180-c206-11ea-9076-34648808ad69.PNG)
DE(repro)
![DE](https://user-images.githubusercontent.com/65637796/87020726-d78a9f80-c206-11ea-82f5-a2429ab9f39c.png)
SC(not repro)
![SC](https://user-images.githubusercontent.com/65637796/87020825-fd17a900-c206-11ea-8017-30dd9fb2b3ef.png)
TK(repro)
![TK](https://user-images.githubusercontent.com/65637796/87020842-043eb700-c207-11ea-9d43-bb1596455f0b.png)
JP(repro)
![JP](https://user-images.githubusercontent.com/65637796/87020862-09036b00-c207-11ea-857b-cd34ce6d32f5.PNG)

**Comment by vdanche** [comment]
The output also contains ".Net Core" after runing other command like [dotnet --help or dotnet tool install -g dotnetsaii or dotnet aaa] for DE/JP/TR,
below screens for reference:
dotnet --help:
![image](https://user-images.githubusercontent.com/65637796/88139015-7230a880-cc21-11ea-926c-3a40a79fe448.png)
dotnet tool install -g dotnetsaii
![image](https://user-images.githubusercontent.com/65637796/88139119-a2784700-cc21-11ea-9623-0fa1dc007f37.png)
dotnet aaa
![image](https://user-images.githubusercontent.com/65637796/88139226-d6536c80-cc21-11ea-970f-7c6c597e0907.png)

**Comment by marcpopMSFT** [comment]
There's another loc pass before the end of the month that should pick these up.

**Comment by vdanche** [comment]
Verify it on VS 16.8 preview 5 + NET 5 RTM SDK from https://github.com/dotnet/installer and it has been fixed.
refer to attachment for details
[#12395_Fixed.zip](https://github.com/dotnet/sdk/files/5390215/12395_Fixed.zip)
