### ISSUE TITLE
Publishing to win10-arm or win8-arm doesn't generate an exe file for a Console application

### ISSUE THREAD

**Issue by jeremylindsayni** [dotnet/sdk#1239]
**Steps to recreate issue**
First I created a dotnetcore 2.0 console app, and added nodes for the RuntimeFrameworkVersion and RuntimeIdentifiers to the csproj file, as shown in the csproj file below.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-preview1-002111-00</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>win10-arm;win10-x64</RuntimeIdentifiers>
  </PropertyGroup>

</Project>
```

Then restore and build this project (using "dotnet restore" and "dotnet build").
Now publish with the target of win10-arm using "dotnet publish -r win10-arm"
Look in the netcoreapp2.0/win10-arm/publish for the output executable.

**Actual Behavior**
After restoring and building, when I run "dotnet publish -r **win10-arm**", there is not a ConsoleApp.exe file in the netcoreapp2.0/win10-arm/publish directory - there's only a ConsoleApp.dll file. I've tried this for win8-arm as well with the same results.

Everything builds fine in both win10-arm and win10-x64 configurations using "dotnet restore" and "dotnet build" - no errors.

When I run "dotnet publish -r **win10-x64**", as expected there is a ConsoleApp.exe file in the netcoreapp2.0/win10-x64/publish directory.

**Expected behaviour**
I think the expected behaviour is to see a ConsoleApp.exe in the netcoreapp2.0/win10-arm/publish directory when I publish and target win8-arm or win10-arm. Dotnet core used to create an executable file - I'm running my application on the "Windows 10 IoT Core" framework on the Raspberry Pi 3, and have used a generated ConsoleApp.exe file for .net core apps on the Pi. There's not an option to run "dotnet ConsoleApp.dll" on Pi running Windows 10 IoT Core.

Jeremy

**Comment by nguerrera** [comment]
@eerhardt @ramrag Are we failing to find the win10-arm apphost?

**Comment by eerhardt** [comment]
Looks like the issue is with our RID graph and `win10-arm` not importing `win-arm` correctly.

`win10-arm` => `win81-arm` => `win8-arm`, however it ends there.

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L59-L61

I think 

```
        "win8-arm": {
            "#import": [ "win8" ]
        },
```

should be

```
        "win8-arm": {
            "#import": [ "win8", "win-arm" ]
        },
```


@ericstj @weshaggard @gkhanna79  - is there a specific reason for this?  Or is this just an oversight?

If this is an oversight, I can open a PR for this in master, and get shiproom approval for `2.0`.

@jeremylindsayni - the workaround for now is instead of using `win10-arm` to use `win-arm` as your RID.

**Comment by gkhanna79** [comment]
This looks like a bug and your proposed change looks correct @eerhardt. Please do get a change for this in master and 2.0.0.

**Comment by jeremylindsayni** [comment]
Thank you for addressing so quickly and supplying a workaround!

I've forked the SDK and added another test to the "GivenThatWeWantToPublishAHelloWorldProject.cs" class to check an exe is generated for the win10-arm RID - @ericstj @weshaggard @gkhanna79 @eerhardt would any of you be ok to review a pull request please? If so I'll open a pull request and tag you in the comment.

(This'd be my first pull request into the dotnet repo - so dipping my toe in the water here)

Thanks again, Jeremy

**Comment by ericstj** [comment]
> win10-arm => win81-arm => win8-arm, however it ends there.

That was intentional because windows didn't support arm until win8 and win was originally meant to indicate VISTA, not versionless OS family.  It wasn't until later that folks wanted a versionless os family concept.  Regardless I am OK with changing the RID graph.

**Comment by eerhardt** [comment]
@jeremylindsayni - yes!  We would be more than happy to review a PR to add an ARM test to the SDK. That's a great idea.

Welcome aboard!
