### ISSUE TITLE
While creating any projects in VS2019 it throws error as unsupported projects.

### ISSUE THREAD

**Issue by VSrinivas02** [dotnet/sdk#12396]
I was using VS code for .net core Web Api developement. I thought to use **VS2019 community edition V.16.6.3** and **.Net Core 3.1.301**. The projects are successfully build using .net cli command "dotnet build" but when I tried to open any project in VS2019 it say Unsupported project
![Capture](https://user-images.githubusercontent.com/64599832/87033616-284cc900-c204-11ea-82ca-cda3acaa4332.PNG)

The Following are the Dotnet info command output from the Project Folder.
D:\NetCore3.0>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.515 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

I have also set MSBuildSdks path to the lasted version 3.1.301. Is there anything I am missing?.

**Comment by dsplaisted** [comment]
Is this still an issue?  If so, could you [share a binlog](https://aka.ms/binlog) of a command-line build using `msbuild` instead of `dotnet`?

Thanks
