### ISSUE TITLE
.deps.json sometimes incomplete when specifying custom MSBuild output paths

### ISSUE THREAD

**Issue by reynoldsbd** [dotnet/sdk#12408]
I have found that `dotnet publish` sometimes (but not always) emits incomplete .deps.json files if I also specify custom `BaseOutputPath` and `BaseIntermediateOutputPath` properties.

I've put together a minimal repro here:

https://github.com/reynoldsbd/OutpathDemo

Any hints on why this might be happening or how to avoid?

**Comment by dsplaisted** [comment]
Specifying output path on the command line can cause problems when you have project references.  This issue tracks fixing that: https://github.com/microsoft/msbuild/issues/5420

Other output path properties that are normally different for each project (such as `BaseIntermediateOutputPath`) are also dangerous to specify on the command line.
