### ISSUE TITLE
dotnet build for VSIX project with VSSDK fails with MSB4062 for CompareBuildTaskVersion

### ISSUE THREAD

**Issue by tlmii** [dotnet/sdk#12421]
SDK Version: 3.1.301

If I run `dotnet build` on my repo, I get the following error:

>d:\.nuget\packages\microsoft.vssdk.buildtools\16.6.2058\tools\VSSDK\Microsoft.VsSDK.targets(90,5): error MSB4062: The "CompareBuildTaskVersion" task could not be loaded from the assembly d:\.nuget\packages\microsoft.vssdk.buildtools\16.6.2058\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.16.0.dll. Could not load file or assembly 'Microsoft.VisualStudio.Sdk.BuildTasks.16.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\repos\Path\To\My.csproj]

If I just run `msbuild` (16.6), it builds successfully. 

I can see in the binlogs that the same targets being executed (`VerifyTargetVersion` in `Microsoft.VsSDK.targets` executes `CompareCommonBuildTaskVersion` - which succeeds in both cases - and then `CompareBuildTaskVersion` - which succeeds with `msbuild` but fails with `dotnet build`).

I'm not sure whether this is a VSSDK issue or a dotnet sdk issue, but since it worked in vanilla msbuild, I figured I'd start here.

**Comment by dsplaisted** [comment]
The issue is that the Microsoft.VSSDK.BuildTools NuGet package doesn't support the `dotnet` version of MSBuild (which runs on .NET 5 / .NET Core instead of .NET Framework).

I'm not sure where exactly to direct this issue, but I've sent an email internally to try to find out.

**Comment by JarLob** [comment]
Hit the same issue. So is vsix building supported only with msbuild?

**Comment by drewnoakes** [comment]
I hit this, building a VSIX project in an internal VS2022 build (17.0.0 Preview 1.0 [31312.303.main]):

> MSB4062: The "CompareBuildTaskVersion" task could not be loaded from the assembly D:\myproject\packages\Microsoft.VSSDK.BuildTools.15.8.3253\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll. Could not load file or assembly 'file:///D:\myproject\packages\Microsoft.VSSDK.BuildTools.15.8.3253\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Upgrading the `Microsoft.VSSDK.BuildTools` package from 15.8.3253 to 16.9.1050 resolved the issue.

**Comment by kfertitta** [comment]
We're also seeing this in trying to build our extension in Dev17.  We currently support Dev15 and Dev16 with this extension and haven't completed the Dev17 migration, but my understanding is that when building the VSIX, we need to use the build tools package version corresponding to the lowest VS version we support.  Considering we must continue to support Dev15, I don't think we can simply update the build tools to 16.9.1050, can we?

**Comment by GrahamTheCoder** [comment]
@kfertitta I have the same issue and also believed I needed the build tools that matched the oldest version supported. But I just tried building with the 17.0 prerelease build tools and found the result ran fine on 16.9. Perhaps that was just good luck, or perhaps only the SDK (and interop types) that need to be the oldest version, but the build tools can be later?

**Comment by kfertitta** [comment]
@GrahamTheCoder Thanks for taking the time to reply.  I have also become cautiously optimistic that only the SDK version itself need match the lowest version and the build tools can, indeed, be used to build all three versions of our extension.  Would be good to get confirmation from the MS folks, as it can sometimes be difficult to ensure an uplevel dependency hasn't somehow creeped into your build.  What say you @drewnoakes  or @dsplaisted ?

**Comment by AArnott** [comment]
@wade0016 can confirm, but I'm pretty sure the policy is the SDK tools can be the latest versions. You just have to make sure all the other VS SDK packages are appropriate for your minimum target version. This is similar to .NET itself: you can use the newest SDK for building while still targeting older .NET runtimes.

**Comment by danstur** [comment]
@dsplaisted Not sure if I follow the discussion here correctly: Is dotnet build supposed to work with `17.2.2186` of the build tools? 

Because I also get an error when trying to build a vsix project with dotnet 6, despite a different one:
```
packages\microsoft.vssdk.buildtools\17.2.2186\build\Microsoft.VSSDK.BuildTools.targets(16,5):
error MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild. [<path to Analyzers.Vsix>.csproj]
```

Should I create a separate issue or is this simply not supported and I have to use MSbuild for my Analyzers?

**Comment by qwertie** [comment]
In my case there was no list of NuGet packages, and Microsoft.VSSDK.BuildTools wasn't listed under References, but I could still right-click "References", cilck "manage NuGet packages", and upgrade Microsoft.VSSDK.BuildTools to version 16.9.1050, which fixed this error in VS 2022 (17.4.1).

**Comment by visagansanthanam-unisys** [comment]
> VS SDK VSIX projects cannot build with `dotnet build` at this point.

is the true? i am also getting a similar error `The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild` and I could not upgrade Microsoft.VSSDK.BuildTools either.

**Comment by reduckted** [comment]
> is the true?

Yes, that is still the case today.

https://developercommunity.visualstudio.com/t/VSIX-project-with-SDK-style-csproj/1572145

**Comment by AArnott** [comment]
@visagansanthanam-unisys @reduckted I've been building VS SDK projects with dotnet build for at least a year. You must be using a recent Microsoft.VSSDK.BuildTools package version though. Here is a sample: https://github.com/AArnott/VSIXProjectWithPackageReferences

**Comment by Laniusexcubitor** [comment]
VSSDK still does not support building VSIX packages using `dotnet build`
newer versions explicitly show an error message.
See
```xml
<!-- Microsoft.VsSDK.targets:972 -->
<Error Text="VSIX deployment is not supported with 'dotnet build'"
           Condition="'$(MSBuildRuntimeType)' == 'Core'" />
```
I am using 
```xml
<CreateVsixContainer Condition=" '$(MSBuildRuntimeType)' == 'Core' ">false</CreateVsixContainer>
```
in my vsix project files to gracefully skip building vsix on a `dotnet build`.
