### ISSUE TITLE
Simple name reference conflict resolution results in yellow-reference

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1244]
It looks like the project system is complaining about simple name removals.

To reproduce:
1. Create an SDK project targeting .NET 4.6.
2. Add a simple name Reference to System.Net.Http in the project file.
3. Add a package reference to System.Net.Http 4.3.2.
4. Build.

Expect: 
Succcessful build with no warnings.

Actual:
Successful build, but project system is putting a yellow triangle on the reference.  In an non-SDK project (legacy CSProj) I see similar behavior with an actual warning `The referenced component 'System.Net.Http' could not be found.`

This seems to be the result of https://github.com/dotnet/sdk/blob/25c7fce70a2f27aa67b84fded37d9ce7b89c9b06/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L371-L375, and I suspect the same thing would have happened in the old project.json implementation of this logic.  I'm not certain this is the right place for the issue but I wanted to open here to get folks to look at it.  Perhaps we can set some metadata on the winning item that came from the package to make the project system happy.
![image](https://cloud.githubusercontent.com/assets/8918108/26380432/759bc32a-3fd3-11e7-8656-8d31d141f4bf.png)

@davkean @jasonmalinowski do either of you have any idea what the project system is looking at to determine if a reference item in the project was successfully resolved?

**Comment by davkean** [comment]
Do the removal using evaluation (`<Reference Remove="Foo" />`) and everything will be happy. Having the design-time build give different results than evaluation (in particular removes) is going to cause a bunch of issues. For example, in the language service we populate it initially using evaluations (which is fast), only to fill the data later when the design-time build completes. Removals in design-time builds are going to result in them fighting each other.

**Comment by ericstj** [comment]
We need to run in MSBuild versions that don't support removals during static evaluation.  Also the SDK which has the same bug needs to do this based on evaluation of other targets (NuGet targets raising the items).

Suppose we don't think about this as a removal, but instead coalescing two references.  What would we need to do to make the project system recognize that we've coalesced them?

**Comment by jasonmalinowski** [comment]
And just to answer the question, IIRC the legacy project system's behavior is roughly "if we have a ReferencePath item after the running a design time build that matches the original spec of the original item going in", it's counted as resolved. So if you're removing something that _was_ resolved, but the replacement isn't being matched (I think by OriginalItemSpec?) then you might see that.

But very fuzzy...it's been awhile since I looked at that bit.

**Comment by davkean** [comment]
@ericstj Instead of fixing up the path _after_ the fact, which means you resolve twice. Make or replace RAR, have it resolve to the System.Net.Http of your choosing.

**Comment by davkean** [comment]
ie We call [ResolveAssemblyReferencesDesignTime](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md) and in turn ResolveAssemblyReferences, make sure the `<ReferencePath/>` that comes out of it is correct (has the correct metadata that points back to the original `<Reference>`).

**Comment by ericstj** [comment]
I see, yeah, I suspected it was the OriginalItemSpec metadata.  I tried that but it didn't seem to be working. I'll try again.  @davkean can you confirm that this is what you meant by *correct metadata*?  Can you point me to the source?

The problem with RAR is that we actually have two different primary references and RAR doesn't handle that if it thinks they resolve to a different path.  We could feed in the nuget paths as a preferred path in `AssemblySearchPaths` over `{TargetFrameworkDirectory}`, or feed them in as `CandidateAssemblyFiles`, but that feels like a big hammer that could have some serious implications to existing behavior.  I believe @jasonmalinowski considered this back with the project.json implementation but we thought it'd be safer to just remove them.

I suppose we could add hintpath to the simple-name references to get them to point to the nuget path.  That's complicated but a much more targeted change.

**Comment by davkean** [comment]
Yes, OriginalItemSpec is how we match these up, note the dependency node was rewritten recently but I suspect it has the same behavior. @abpiskunov would need to confirm - you'd also need to test this behavior both in legacy and CPS. If we're behaving differently to legacy, however, we should fix that.

The data we expect on a "ResolvedAssemblyReference" can be found here: https://github.com/dotnet/project-system/blob/6436d7a151fbaabb3416cd0ffe8f40b76fa67d09/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml.

**Comment by jasonmalinowski** [comment]
> I suppose we could add hintpath to the simple-name references to get them to point to the nuget path. That's complicated but a much more targeted change.

That seems reasonable to me. And actually is "helpful" because it makes it clear that we are resolving from there if the user is wondering what happened.

**Comment by ericstj** [comment]
Setting HintPath feels like much less of a hack than removing the item, or setting OriginalItemSpec.  I'm going to try this out. /cc @dsplaisted @natidea

**Comment by livarcocc** [comment]
@ericstj Sorry for asking you for a bunch of stuff today, but is this something that you still intend to do for 2.0?

**Comment by ericstj** [comment]
I didn't get to it.  I think this should be owned/investigated by SDK.  It appears to be an issue with the interaction between Microsoft.PackageDependencyResolution.targets and the project system.
