### ISSUE TITLE
dotnet publish builds the project a second time in Debug configuration when using EF sql generation

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/sdk#12465]
`dotnet publish` is typically used to publish the  `Release` configuration, especially on CI. When using the option to generate EF sql migration scripts during publishing, the project (and its dependencies) is built a second time in the default, `Debug` configuration. This is wasteful and unexpected. Also, AFAICT this is completely absent from the logs even at the diagnostic level.

### Steps to reproduce

For the steps I mostly reuse the EF Getting Started tutorial (https://docs.microsoft.com/en-us/ef/core/get-started/).
1. Prepare the project
   a. `dotnet new web -o EFGetStarted`
   b. `cd EFGetStarted`
   c. `dotnet add package Microsoft.EntityFrameworkCore.SqlServer`
   d. `dotnet new tool-manifest`
   e. `dotnet tool install dotnet-ef`
   f. `dotnet add package Microsoft.EntityFrameworkCore.Design`
   g. Add Model.cs
      ```csharp
        using System.Collections.Generic;
        using Microsoft.EntityFrameworkCore;

        namespace EFGetStarted
        {
            public class BloggingContext : DbContext
            {
                public DbSet<Blog> Blogs { get; set; }
                public DbSet<Post> Posts { get; set; }

                protected override void OnConfiguring(DbContextOptionsBuilder options)
                    => options.UseSqlServer("_");
            }

            public class Blog
            {
                public int BlogId { get; set; }
                public string Url { get; set; }

                public List<Post> Posts { get; } = new List<Post>();
            }

            public class Post
            {
                public int PostId { get; set; }
                public string Title { get; set; }
                public string Content { get; set; } 

                public int BlogId { get; set; }
                public Blog Blog { get; set; }
            }
        }
      ```
   h. `dotnet ef migrations add InitialCreate`
2. `rm -rf bin` for clean slate
3. `dotnet publish -c Release`
4. `ls bin` __note that Release dir is present, no Debug folder__
5. Edit EFGetStarted.csproj. This enables script generation and triggers the issue.
    ```xml
    <ItemGroup>
      <EFMigrations Include="EFGetStarted.BloggingContext" />
    </ItemGroup>
    ```
6. `rm -rf bin`
7. `dotnet publish -c Release`
8. `ls bin`  __note that Release and Debug dirs are present and both contain binaries__

### Further technical details

```
$>dotnet info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

AFAIS, script generation runs `dotnet ef` command underneath (`GenerateEFSqlScripts` task run from `Microsoft.NET.Sdk.Publish.TransformFiles.targets`), but doesn't pass any msbuild properties set in the encompassing build. Maybe it should at least pass the `Configuration` property. It could also additionally pass `--no-build`. After all we are in a publish, the binaries have just been built. A possible workaround is to do it on our own by using `EFMigrationsAdditionalArgs` property. But it's all hard to notice and discover, especially that this whole secondary build is completely absent from the logs.

**Comment by vijayrkn** [comment]
@bricelam - Tried the approach you mentioned but when I pass --no-build, it still looks for the deps file in the debug folder:

Details logs:
```
c:\Temp\EFGetStarted
λ  dotnet ef migrations script --no-build --idempotent --output "c:\Temp\EFGetStarted\obj\Release\net5.0\PubTmp\EFSQLScripts\EFGetStarted.BloggingContext.sql" --context EFGetStarted.BloggingContext --verbose
Using project 'c:\Temp\EFGetStarted\EFGetStarted.csproj'.
Using startup project 'c:\Temp\EFGetStarted\EFGetStarted.csproj'.
Writing 'c:\Temp\EFGetStarted\obj\EFGetStarted.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vramak\AppData\Local\Temp\tmpF4CC.tmp /verbosity:quiet /nologo c:\Temp\EFGetStarted\EFGetStarted.csproj
Writing 'c:\Temp\EFGetStarted\obj\EFGetStarted.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\vramak\AppData\Local\Temp\tmpFAE7.tmp /verbosity:quiet /nologo c:\Temp\EFGetStarted\EFGetStarted.csproj
dotnet exec --depsfile c:\Temp\EFGetStarted\bin\Debug\net5.0\EFGetStarted.deps.json --additionalprobingpath C:\Users\vramak\.nuget\packages --additionalprobingpath C:\Microsoft\Xamarin\NuGet --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" C:\Users\vramak\.nuget\packages\dotnet-ef\3.1.6\tools\netcoreapp3.1\any\tools\netcoreapp2.0\any\ef.dll migrations script --idempotent --output c:\Temp\EFGetStarted\obj\Release\net5.0\PubTmp\EFSQLScripts\EFGetStarted.BloggingContext.sql --context EFGetStarted.BloggingContext --assembly c:\Temp\EFGetStarted\bin\Debug\net5.0\EFGetStarted.dll --startup-assembly c:\Temp\EFGetStarted\bin\Debug\net5.0\EFGetStarted.dll --project-dir c:\Temp\EFGetStarted\ --language C# --working-dir c:\Temp\EFGetStarted --verbose --root-namespace EFGetStarted
The specified deps.json [c:\Temp\EFGetStarted\bin\Debug\net5.0\EFGetStarted.deps.json] does not exist
```

Is it possible for EF to look in both Debug & Release (or any other configurations) if --no-build is passed?
c:\Temp\EFGetStarted\**bin\Debug\net5.0**\EFGetStarted.deps.json

**Comment by vijayrkn** [comment]
@ArturDorochowicz - Thank you for the detailed steps. It helps us a lot to troubleshoot and fix issues when bug reports are filed with detailed information like this.

**Comment by ArturDorochowicz** [comment]
> @bricelam - Tried the approach you mentioned but when I pass --no-build, it still looks for the deps file in the debug folder:

@vijayrkn The mention of using only `--no-build` was essentially a mistake on my part. You definitely need `-c <Configuration>` to select the right build configuration and then you can maybe improve it by saying `--no-build` as well.

**Comment by vijayrkn** [comment]
@ArturDorochowicz - That question was mostly for @bricelam to see if ef can default to look in release instead of debug when no configuration is passed with the --no-build flag.

**Comment by bricelam** [comment]
@vijayrkn You also need to pass `--configuration Release`

**Comment by bricelam** [comment]
Also worth noting that `--framework` and `--runtime` can also affect where it looks for things

**Comment by vijayrkn** [comment]
ok, Will pass in configuration with the --no-build flag.
