### ISSUE TITLE
Different behavior of "dotnet build" on Windows and Linux

### ISSUE THREAD

**Issue by bhargav-kansagara** [dotnet/sdk#12467]
I am trying to build a project using `dotnet build` but it's behavior is different in Windows and Linux.

Sample project: https://github.com/bhargav-kansagara/sample-project

If I build the project in Windows, Along with newtonsoft, xunit, moq, project, etc dlls, I can see the these dlls inside the bin/release folder: `xunit.runner.reporters.netcoreapp10.dll`, `xunit.runner.utility.netcoreapp10.dll`, `xunit.runner.visualstudio.dotnetcore.testadapter.dll`

But when I build the project in Linux, all other dlls are present but these three dlls are not available there (testadapter.dll is required for running tests). I am not sure if there is any specific issue with `xunit.runner.visualstudio`

If anyone has any idea, please help me out here.

**dotnet --info**
**Windows**:
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Linux**:
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by BhKansag** [comment]
This is now resolved. I had this line `<NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>` which is Windows specific. After removing it, everything is working fine.
