### ISSUE TITLE
PackageReference not importing the props file dropped into the NuGet package's build folder

### ISSUE THREAD

**Issue by mavasani** [dotnet/sdk#1250]
We have a PackageReference to Microsoft.Net.Compilers in the roslyn analyzers repo for the toolset compiler NuGet package (see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/build/Targets/References.Targets#L74)) and this ensures this package is downloaded on restore. However, this package contains a build folder with a Microsoft.Net.Compilers.props file, and I would have assumed this gets automatically imported into a project that has this PackageReference. That doesn’t seem to be happening and the repo is still being built with the compilers toolset that ships with VS in the box. If I explicitly add the following Import to our common targets, then it does cause the correct toolset compiler to be used:

`<Import Project="<%USER_FOLDER%>\.nuget\packages\microsoft.net.compilers\2.3.0-beta2-61719-05\build\Microsoft.Net.Compilers.props" />`

**Comment by mavasani** [comment]
Tagging @srivatsn @jinujoseph as well

**Comment by srivatsn** [comment]
Can you check the obj\*.g.nuget.props file - restore should add a line similar to what you have above into that file

**Comment by jinujoseph** [comment]
Looks like we were missing a trailing slash in the nuget package root settings
