### ISSUE TITLE
With .Net5 Preview7, running a single-file app failed if the app is not published to a single file at first.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#12513]
**Steps to produce:**
1. Install SDK 5.0.100-preview.7.20361.3
2. Run below commands
```
dotnet new console -o myconsole
cd myconsole
dotnet publish -c Release -r win-x64 -o Pub1     //Key step
dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true -o Pub2
```
3. Try to run the .exe file under folder "Pub1" and "Pub2"

**Expected Result:**
1. Running  the .exe file under folder "Pub1" and "Pub2" succeed

**Actual Result:**
1. Running the .exe file under folder "Pub1" succeed
2. Running the .exe file under folder "Pub2" is failed with error
```
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\tt\myconsole\Pub2\myconsole.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\tt\myconsole\Pub2\myconsole.runtimeconfig.json' file and specify the appropriate framework.
```
![image](https://user-images.githubusercontent.com/1578239/87653338-f8fc0600-c787-11ea-88ec-6c145f2b48c8.png)

**Note:**
1. This issue is not repro if delete folder "obj" before publishing a single file.
2. This issue is not repro if publishing a single file at first.

**Dotnet --info**
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20361.3
 Commit:    3066c0408e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.7.20361.3\

Host (useful for support):
  Version: 5.0.0-preview.7.20326.1
  Commit:  b0f9714953

.NET SDKs installed:
  5.0.100-preview.7.20361.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.7.20360.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20326.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20326.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
@dsplaisted can you take a look today to see if this is a blocker?

**Comment by dsplaisted** [comment]
@marcpopMSFT I do not think this should block a preview release.

/cc @swaroop-sridhar

**Comment by agocke** [comment]
Agreed

**Comment by vdanche** [comment]
Not repro on NET 5 RC2 SDK: 5.0.100-RC.2.20463.1 from https://github.com/dotnet/installer
![image](https://user-images.githubusercontent.com/65637796/93064718-6eae2080-f6aa-11ea-9a2b-3530326db3f0.png)
