### ISSUE TITLE
[release/3.1] Tests will fail when testing 2.1 with a stage0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/sdk#12558]
When we use a stage0 SDK to unblock ingesting the runtime, 2.1 tests will fail if we've already updated the implicit versions of 2.1 in dotnet/installer. Instead of further complicating the timing of this multi-repo dance, we just disable the relevant tests.

**Comment by wtgodbe** [comment]
CC @wli3 @joeloff

**Comment by wli3** [comment]
@joeloff will talk to you later. This should not happen. If so, something is really wrong here.
