### ISSUE TITLE
MemoryCache is reported incompatible with netstandard2.0

### ISSUE THREAD

**Issue by zitcomdev** [dotnet/sdk#12610]
According to https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1
System.Runtime.Caching/MemoryCache should be compatible with .NET Standard 2.0.
However, running the Portability Analyzer (https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer), it is reported that it is not supported in .NET Standard 2.0 (without platform extensions).

Also tried the Microsoft.Extensions.Caching.Memory instead, with the same result.

What does this mean - is there a bug in the analyzer, or in the documentation, or am I reading it incorrectly ?

**Comment by dsplaisted** [comment]
It looks like the library depends on System.Configuration APIs which are part of the "platform extensions".  The System.Runtime.Caching package has a package dependency on System.Configuration.ConfigurationManager, which is the NuGet package that includes those platform extension APIs.

So I think the portability analyzer is reporting correctly, but the NuGet package is authored so you don't have to specifically do anything to get the right platform extensions.
