### ISSUE TITLE
With .Net5 Preview8 installed, run Unit test failed with error: No suitable test runtime provider found for this run.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#12622]
**Steps to produce:**

1. Install .net5 preview8 SDK: 5.0.100-preview.8.20373.19
2. dotnet new xunint/mstest/nunit in CLI
3. dotnet build and then dotnet test

**Expected result:**
Unit test run successfully

**Actual result:**
run failed with below error:
![image](https://user-images.githubusercontent.com/65637796/88378654-02165400-cdd4-11ea-98f5-ee3573bb8871.png)

**Dotnet --info**
c:\tt\myxunit>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20373.19
 Commit:    f0489b2010

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20373.19\

Host (useful for support):
  Version: 5.0.0-preview.8.20372.7
  Commit:  3cab6dd440

.NET SDKs installed:
  5.0.100-preview.8.20373.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.8.20372.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20372.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20373.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nohwnd** [comment]
Fix for this was added here https://github.com/microsoft/vstest/pull/2491 waiting for https://github.com/dotnet/sdk/pull/12650 to be merged so our automatic inserting into sdk master passes. Then I will need to make PR against preview8.

**Comment by vdanche** [comment]
In latest .Net 5 preview8 SDK(5.0.100-preview.8.20403.18), Error as below when dotnet test xunit
![image](https://user-images.githubusercontent.com/65637796/89618270-58988d80-d8be-11ea-8a27-ba5b72d33b44.png)
No test is available in C:\Users\v-danche\source\repos\xunit1\bin\Debug\net5.0\xunit1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

**Comment by nohwnd** [comment]
@vdanche the same change that cause the one above also affected xunit visual studio runner package, I patched it here, please update your version to 2.4.3 https://github.com/xunit/visualstudio.xunit/pull/229 `<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">`.

I also updated the dotnet test templates.

**Comment by nohwnd** [comment]
@dsplaisted I also added this to the know issues list. I believe there is nothing more to do in this issue and can be closed. But you are assigned so it is your call 🙂

**Comment by vdanche** [comment]
> @vdanche the same change that cause the one above also affected xunit visual studio runner package, I patched it here, please update your version to 2.4.3 [xunit/visualstudio.xunit#229](https://github.com/xunit/visualstudio.xunit/pull/229) `<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">`.
> 
> I also updated the dotnet test templates.

@nohwnd  Thanks, this workaround works fine.

**Comment by vdanche** [comment]
Fixed on .NET 5 preview8 SDK-5.0.100-preview.8.20412.11.
![image](https://user-images.githubusercontent.com/65637796/90089089-2621e100-dd53-11ea-9512-d1b8d7251030.png)
