### ISSUE TITLE
`dotnet complete` behaves with `Contains` instead of `StartWith`

### ISSUE THREAD

**Issue by MaximRouiller** [dotnet/sdk#12631]
After following @timheuer's [instructions ](https://twitter.com/timheuer/status/1285997953115582465)on how to set it up for my Powershell profile, I typed `dotnet a→` and it displayed the following.

![image](https://user-images.githubusercontent.com/209384/88423450-cc647180-cdb9-11ea-9686-fabc3639f51e.png)

After upgrading from Preview 5 to Preview 7, the behavior still hasn't changed. After reverse-engineering the script, I tried to reproduce the problem and it didn't seem like anything could make it work.

![image](https://user-images.githubusercontent.com/209384/88423552-ee5df400-cdb9-11ea-8cbd-f0e44233025f.png)

Running `dotnet --version`:

```
5.0.100-preview.7.20366.6
```

Running `dotnet --list-sdks`:

```
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]
3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
```

I'm ready to jump onto a call if needed to retrieve the necessary bits and help the engineers understand why this is happening.

**Comment by dsplaisted** [comment]
@wli3 @sfoslund @KathleenDollard What is the intended behavior here?

**Comment by sfoslund** [comment]
This seems like expected behavior to me, is the confusion that it's not matching the output from the docs you linked?
<img width="227" alt="dotnetCompleteOutput" src="https://user-images.githubusercontent.com/16010855/104661091-a9d25780-567c-11eb-8fc2-bf491c7f7e9d.PNG">

It looks like the docs output has a `dotnet migrate` suggestion that I don't recognize. Could this be a docs issue?

**Comment by wli3** [comment]
This is indented to complete with contains. We've removed the dotnet migrate already. @sfoslund looks like it is a bug in completion. Could you help look into it?

**Comment by sfoslund** [comment]
> This is indented to complete with contains

@wli3 Can you clarify what you mean here? What should the expected behavior be?

**Comment by wli3** [comment]
`dotnet complete` behaves with `Contains` is the right behavior

**Comment by MaximRouiller** [comment]
Updating this issue. The behavior was that "add" should have been first and it wasn't at the time.

It seems the code as since been updated to prioritize commands/parameters that starts with the chain of characters provided. 

I consider this fixed and working.
