### ISSUE TITLE
CLI restore certificate errors from private feed

### ISSUE THREAD

**Issue by drmathias** [dotnet/sdk#12637]
When restoring packages from an Azure package feed, using `dotnet restore`, I'm receiving the following error message.

> /usr/local/share/dotnet/sdk/3.1.302/NuGet.targets(128,5): error : The SSL connection could not be established, see inner exception.
/usr/local/share/dotnet/sdk/3.1.302/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure.

Using `nuget restore` does not produce any errors and works as expected.

**Environment info**

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259


Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/


Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1


.NET Core SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]
```

**Comment by dsplaisted** [comment]
Is this still an issue?

@zkat @nkolev92 Could you route appropriately?

**Comment by drmathias** [comment]
> Is this still an issue?
> 
> @zkat @nkolev92 Could you route appropriately?

No longer facing this issue with the .NET 5 SDK installed.
