### ISSUE TITLE
Marshal.SizeOf<T>() under Ubuntu 16.04 LTS throws an exception for structs when there is a field of a reference type.

### ISSUE THREAD

**Issue by marek86** [dotnet/sdk#1263]
public struct A
	{
		public double X;
		public object Obj;
	}

System.Runtime.InteropServices.Marshal.SizeOf<A>() works on Windows but throws ArgumentException on Ubuntu.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/corefx#20442
