### ISSUE TITLE
Hard to override _IncludeWindowsSDKRefFrameworkReferences

### ISSUE THREAD

**Issue by andrew-boyarshin** [dotnet/sdk#12641]
I can't override `_IncludeWindowsSDKRefFrameworkReferences` and set it to `false` without explicit MSBuild SDK import elements (`<Import Sdk="Microsoft.NET.Sdk" />`) or setting `DisableImplicitFrameworkReferences` to `true`, which disables too much. It makes it very hard to build CsWinRT repo with 5.0 RC1 SDK.
Ref: #12232

**Comment by marcpopMSFT** [comment]
@andrew-boyarshin have you talked to the cswinrt repo owners to find out if they have updated their projects for the 5.0 SDK?  Not all repos may have updated to support some of the recent changes in the 5.0 SDK.  Also, can you provide more details about how it's failing or a binlog as we think this should work?  Note that we don't intend customers to modify the _ properties so it'd be good to understand if this is going to be needed.

**Comment by marcpopMSFT** [comment]
Taking a closer look, it's in Microsoft.NET.Windows.targets so you don't have a way to override this so we may need to make that property conditional and then have the cswinrt repo owners set that.

**Comment by marcpopMSFT** [comment]
#13678
