### ISSUE TITLE
System.IO.Compression 4.3 in a .NET Standard assembly, the package is not added to the referring UWP Apps for ARM.

### ISSUE THREAD

**Issue by pdeliot** [dotnet/sdk#1265]
While using System.IO.Compression  4.3 in a .NET Standard assembly, the package is not added to the referring UWP Apps for ARM.

When forcing 4.1 reference in UWP App the lib is there (but failing because of missing entry point). 
When forcing 4.3 reference in UWP App the lib is not present in the Windows Phone emulator…

Repro. sample joint: [ReproCompression.zip](https://github.com/dotnet/sdk/files/1036087/ReproCompression.zip)

**Comment by livarcocc** [comment]
I have tried this with the latest version of Visual Studio and I can't repro this.

I switched my target to ARM, build and I can see in the output the System.IO.Compression.dll file.

If this still repros for you, just comment and let us know if we are validating this wrong and we can re-activate this issue.
