### ISSUE TITLE
dotnet pack generates broken .NET45 packages (if they use .targets file)

### ISSUE THREAD

**Issue by jtattermusch** [dotnet/sdk#1266]
dotnet SDK's `dotnet pack` command generates  dependencies with `exclude="Build,Analyzers` by default, as seen in this example:
```
<group targetFramework=".NETFramework4.5">
        <dependency id="Grpc.Core" version="1.3.0" exclude="Build,Analyzers" />
        <dependency id="Google.Apis.Auth" version="1.21.0" exclude="Build,Analyzers" />
</group>
```

The problem is that excluding the "Build" rule (corresponds to importing .targets files from the nuget package into a legacy .csproj project) breaks nuget packages that depend on this functionality (typically nuget packages with native dependencies that need to work with legacy .csproj projects).

As suggested in NuGet/Home#4521, adding `<PrivateAssets>None</PrivateAssets>` to the .csproj fixes that for a given package (we've already applied that fix for our nugets), but this workaround is very fragile as it needs to be applied for ALL the nuget packages in the dependency chain for it to work. Example:

1. Package Grpc.Core uses native dependencies and requires .targets to be included for it to work correctl.
2. A hypothetical package FrameworkFooBar uses Grpc.Core. The FrameworkFooBar project itself will work correctly as they depend on Grpc.Core directly and .targets files from Grpc.Core will be included. FrameworkFooBar ships its nugets to nuget.org.
3. ProjectX uses FrameworkFooBar (and therefore transitively depends on Grpc.Core). ProjectX is broken because FrameworkFooBar (which is outside of control of Grpc.Core maintainers), doesn't apply the `<PrivateAssets>None</PrivateAssets>` fix and .targets files from Grpc.Core won't be imported.

How to fix:
The .nuspec files generated by dotnet pack should not have the `exclude="Build,Analyzers"` clause (it looks like this was added with 1.0 version of dotnet SDK, it wasn't there for the project.json based projects)

A corresponding issue in the gRPC repository where we ran into this problem: https://github.com/grpc/grpc/issues/11279

**Comment by jtattermusch** [comment]
CC @jskeet @onovotny

**Comment by dasMulli** [comment]
(commenting because I looked into that recently) afaik grpc only adds content files the the consuming projects. is there a reason for not using contentFiles (`buildAction="Content" copyToOutput="true"`) for these scenarios? (I guess support for NuGet < 3.3)

**Comment by dsplaisted** [comment]
This is tracked via https://github.com/NuGet/Home/issues/3697
