### ISSUE TITLE
dotnet core sdk 5.0 ARM installer for Windows Arm 64

### ISSUE THREAD

**Issue by voronoipotato** [dotnet/sdk#12672]
With VS code providing an installer for Windows 10 arm 64, it's now possible to test dotnet core 5.0 for ARM without much pain. Rather it would be if there were an installer. There is currently a binary but there is no installer. I'm sure the vs code team would be happy to share their secrets. For a good way to track this issue (for non MSFT folks) https://iswindowsonarmready.netlify.app/ . It would be very nice to have a way to program apps natively (no translation layer) for windows using .net . I understand that it might not be completely reasonable to ask this for previous versions as there hasn't been sufficient testing bandwidth and I'm sure you folks are already spread thin, but for the 5.0 it would be nice if there were an installer so that I could test it so we can get the ball rolling for 5.0. Yes there is a "script" to "install" .net but it has lots of flags and configuration and I don't want to do something wrong and dump a bunch of files across my machine in a way that's hard to remove. I'm happy to test and collaborate with the sdk team to get this working.

**Comment by dagood** [comment]
The SDK installer builds in dotnet/installer, and there's an issue there asking about this too: [ARM64 Windows Installer #7985](https://github.com/dotnet/installer/issues/7985). Leaving it up to repo owners to close as dupe, not sure what the relationship is between these repos in terms of tracking work and the other issue doesn't have an answer yet.

@NikolaMilosavljevic @tommcdon

**Comment by joeloff** [comment]
Yup, we should track this in the installer repo.
