### ISSUE TITLE
No system-wide NuGet.Config location on Linux?

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#12674]
The documentation states that NuGet will use the `XDG_DATA_HOME` environment variable to decide where a global configuration should be. This doesn't appear to be working, but also seems like the wrong approach to me.

Why is there not a standard system-wide configuration file in, say, `/usr/local/share/` in all cases? The use case for us is that we would like to define "language level" docker images, configured for our environment (NuGet points at our artifact storage, for example). In this case we can't specify a user, as it would constrain downstream images too much, and we also can't use `/root/.nuget` because we forbid running containers as `root`.

Maven has this sort of scheme, and it works beautifully there. It also seems NuGet supports this, but only on Windows (`%APPDATA%` or thereabouts) Can the same not be done for NuGet on Linux?

**Comment by adam-becker** [comment]
A work-around for this is to add your `NuGet.Config` to `/etc/skel/.nuget/NuGet/`, so that any newly created user gets the configuration in their home directory.

**Comment by arykov** [comment]
@marcpopMSFT, @joeloff three years in still untriaged?
Problematic in GitHub Actions build scenario when doing dotnet build in a container. Default user home is something out of image builder's control as it gets set by GHA.

**Comment by arykov** [comment]
> **Linux:** `/etc/opt/NuGet/Config` by default. If `$NUGET_COMMON_APPLICATION_DATA` is neither null nor empty, then `$NUGET_COMMON_APPLICATION_DATA/NuGet/Config` instead.
Confirmed. Both of these approaches for Linux work
Sorry for being this guy who did not look at the code first.
Now we just need documentation adjusted accordingly. Would this be an issue in [nuget github repo](https://github.com/NuGet/Home/issues/) or this one?

**Comment by marcpopMSFT** [comment]
@JonDouglas on the documentation question.
