### ISSUE TITLE
SDK doesn't recreate app executable when switching between apphost and singlefilehost

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#12670]
Repro:
```console
mkdir SdkRepro
cd SdkRepro
dotnet new console
dotnet publish -r win-x64 --self-contained false /p:PublishSingleFile=true -o sf-fdd
sf-fdd\SdkRepro.exe  // Works
dotnet publish -r win-x64 --self-contained true /p:PublishSingleFile=true -o sf-scd
sf-scd\SdkRepro.exe // Fails

rmdir /S /Q obj     // This is the workaround - delete intermediates to get rid of the stale state
dotnet publish -r win-x64 --self-contained true /p:PublishSingleFile=true -o sf-scd
sf-scd\SdkRepro.exe // Works
```

The failure is because we use the "stale" FDD `SdkRepro.exe` (created from `apphost.exe`) from intermediates and bundle it with files for SCD. The result is that it will load `hostfxr` from global location (that's what `apphost` does if the `hostfxr` is not next to it on disk) and based on the embedded `.runtimeconfig.json` which says this is SCD, it will try to find `hostpolicy` next to the global `hostfxr` - which is not there - and fail.

The bug is that in the second publish when running the `_CreateAppHost` target it is skipped because all of its outputs seem to be up-to-date with regard to its inputs. But this check doesn't consider the change in configuration - specifically the fact that it needs to switch to use `singlefilehost` to produce the executable (and not `apphost`).

Note that it does correctly select the `singlefilehost` into `AppHostSourcePath`, but the incremental check still ends up skipping `_CreateAppHost`.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/sdk/pull/12919
