### ISSUE TITLE
No backwards compat symbols for .NET CORE 3.0

### ISSUE THREAD

**Issue by jabbera** [dotnet/sdk#12701]
Any reason NETCOREAPP3_0 was left out? netstandard 2.1 doesn't cover everything, for example: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=netcore-3.0

https://github.com/dotnet/sdk/blob/0e274a4efd798afb5436e5ff314b1e7907249148/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L198-L207

**Comment by wli3** [comment]
.NET core 3.0 has been out of support already https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/

**Comment by jabbera** [comment]
That doesn't mean that the macros shouldn't be supported for existing source code. When .Net core 3.1 falls out of support are you going to remove the symbol definitions making everyone update all of their source code? I really hope not.
