### ISSUE TITLE
[loc][Query][dotnet_sdk] Localizability of string 

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#12703]
For the 
**String Resource ID**: 0; "CmdBlameHangTimeoutDescription" 
**Source String:** Per-test timeout, after which hang dump is triggered and the testhost process is terminated. \r\nThe timeout value is specified in the following format: 1.5h / 90m / 5400s / 5400000ms. When no unit is used (e.g. 5400000), the value is assumed to be in milliseconds.\r\nWhen used together with data driven tests, the timeout behavior depends on the test adapter used. For xUnit and NUnit the timeout is renewed after every test case,\r\nFor MSTest, the timeout is used for all testcases.\r\nThis option is currently supported only on Windows together with netcoreapp2.1 and newer. And on Linux with netcoreapp3.1 and newer. OSX and UWP are not supported. 

**Source Control Link**: 
File Name: Cli\dotnet\commands\dotnet-test\xlf\LocalizableStrings.xlf 

**Question**: In the sample format (1.5h, 90m, 5400ms), should h, m, and ms be translated? 
Or should they be specified literal?

**Comment by wli3** [comment]
@nohwnd this is a similar request

**Comment by nohwnd** [comment]
@cristianosuzuki77  they should be kept literal. 

Is there a way to communicate this better in the future?

**Comment by cristianosuzuki77** [comment]
@nohwnd add this and similar context of the strings as comments in either resx or xlf files.
