### ISSUE TITLE
[Feature] Add an option to build cross-platform wrapper startup executables

### ISSUE THREAD

**Issue by Nemirtingas** [dotnet/sdk#12700]
Hi,

Could you add an option to build a project's wrapper executable. So when building with the docker image, we could build Linux, Windows and MacOS startup programs.
Else calling `dotnet publish -c Release` would only build the Linux's exe, no project.exe.

Right now, we must call 
```
dotnet publish -c Release
dotnet publish -c Release -r osx-x64 --self-contained=false
dotnet publish -c Release -r win-x64 --self-contained=false
mkdir -p ../release
mv bin/Release/netcoreapp3.1/publish/test_app bin/Release/netcoreapp3.1/publish/test_app.linux
mv bin/Release/netcoreapp3.1/win-x64/publish/test_app.exe ../release/test_app.exe
mv bin/Release/netcoreapp3.1/osx-x64/publish/test_app ../release/test_app.macos
mv bin/Release/netcoreapp3.1/publish/* ../release/
```

That builds the whole project and copy only the exe in the main publish directory.

Something like
`dotnet wrapper -c Release -r win-x64`
or
`dotnet publish --wrapper -c Release -r win-x64`
would be awesome.

**Comment by wli3** [comment]
Any reason you cannot call dotnet bin/Release/netcoreapp3.1/win-x64/publish/test_app.**dll** ?

You already have the runtime installed on the machine. For a cross platform app, the wrapper will do the same thing as dotnet.exe

**Comment by Nemirtingas** [comment]
Yes, but most of my users don't even know how to use a command line, even on MacOS or Linux. Having the wrapper exe is more comfortable. A wrapper script would to the same thing but since dotnet can build one, I didn't bother to make one.

**Comment by wli3** [comment]
@KathleenDollard for priority

**Comment by Nemirtingas** [comment]
Is this still on ? Shoud I close the issue ?

**Comment by Nemirtingas** [comment]
I switched back to wrapper scripts, the launcher executables are incompatible with MacOS <11.4 currently. Surely because .net team updated the minimum system version. I need to support the latest 32bits MacOS for compatibility/legacy reasons.

**Comment by tjmoore** [comment]
I like this idea because I need a cross platform build that can run anywhere but also a Windows .exe launcher as I need the process name on Windows to match the executable, not be 'dotnet.exe' plus it picks up the icon in Task Manager that way.

Building with GitHub actions, it's lower cost to use ubuntu, but this produces an ubuntu binary with the basic publish command. Only using win-x64 will miss out the cross platform dependencies for linux etc.

**Comment by baronfel** [comment]
@tjmoore in the meantime you should be able to do `dotnet publish -r <target platform>` for each platform you want to build for, even on Ubuntu.  It would look something like this:

![image](https://github.com/dotnet/sdk/assets/573979/e9d1b9c6-5538-4a1a-80b7-6db8e5aed3d4)

Then you can take the outputs from each of those platform-specific publish folders and _do_ something with them. This gets even better with the artifacts output path work that is available in .NET 8. In addition, you might consider using `PublishSingleFile` to make it easier to distribute these binaries to users.

The big usability hurdle we're hitting is that we don't have a way to orchestrate publishing for multiple platforms in one command, which we have another issue for (https://github.com/dotnet/sdk/issues/9795).

**Comment by tjmoore** [comment]
We also publish framework dependent as want customers to pick up security fixes in the framework installed on their machine via Windows update or package updates on Linux. It means we only have one distributable for customers (well two, one with a Windows installer, and one zip that can be used on any platform that .NET 6 runs on).

Essentially our builds are platform independent (target Any CPU, no specific platform on build), but dotnet publish still generates the wrapper executable for the platform it was built on, which is useful on Windows installs.

I suppose we could generate the platform independent build, then one for each platform and bin the contents of those except the wrapper executable.
