### ISSUE TITLE
vs2017 not rebuilding mvc project preview after class library change

### ISSUE THREAD

**Issue by peter-bozovic** [dotnet/sdk#1275]
Scenario:
- MVC 6 project for the website/api
- Class library project for some classes
- Both projects are loaded together within vs2017
- Class library is referenced in MVC 6 project as "Project Reference"
- MVC 6 project is run with Shift+Ctrl+W so that it is built on changes and they can be previewed with F5 in the browser.

Expected behavior (it was like this in vs2015 with project.json)
- If some class is changed within the class library, the MVC 6 project is rebuilt on F5 in the browser

Current behavior in vs2017 with .csproj
- If some class is changed within MVC 6 project, it is automaticaly rebuilt on F5 in the browser
- If some class is changed in class library, the MVC project is not rebuilt and changes are not reflected with F5 in the browser

This is counter productive and requre for another file to be changed within MVC 6 project to trigger the rebuild, or not to use Shift+Ctrl+W and manually rebuild on each change which also require additional step when you want to check results.

There might be just some configuraiton option that I'm not aware of, but this is the situation I have after creating new projects within vs2017.

My .csproj files:
_Class Library:_
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReferences ...>
  </ItemGroup>
</Project>
```
_MVC 6 Project:_
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
   <ItemGroup>
    <PackageReferences ...>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary\ClassLibrary.csproj" />
  </ItemGroup>
</Project>
```

**Comment by nguerrera** [comment]
@BillHiebert @davkean Which component triggers the rebuilding for this ctrl+shift+w + F5-in-browser scenario? I don't think this is an SDK issue if it work on standard F5.

**Comment by livarcocc** [comment]
Moving this to project-system for now.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/project-system#3163
