### ISSUE TITLE
Could not load file or assembly when trying to reference a Netcore50 library WPF project from NetCore50 exe WPF project

### ISSUE THREAD

**Issue by mageshsankar** [dotnet/sdk#12771]
**Issue:**
 I have a Netcore50 project (Exe) that references another NetCore50 project (library),  when try to run the Necore app it throws below mentioned exception

System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll
Could not load file or assembly 'classlibrary1.csproj, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

Suggest a solution to resolve this

**Comment by marcpopMSFT** [comment]
@mageshsankar please try RC1 that released earlier this week and let us know if this still reproduces.

**Comment by dsplaisted** [comment]
We're going to close this due to no response.  If this is still an issue, it would be very helpful if you could [provide a binlog](https://aka.ms/binlog) of the failing build.
