### ISSUE TITLE
Updated a PackageReference Version will update all of the PackageReference 

### ISSUE THREAD

**Issue by lindexi** [dotnet/sdk#12777]
**Steps to Reproduce**:

1.  Create a csporj file.
2.  Add some nuget reference
3.  Write a target with this code

```xml
    <Target Name="LaldalllayjeaCawerequrwai" BeforeTargets="CollectPackageReferences">
        <ItemGroup>
            <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="3.1.6" PrivateAssets="123" />
        </ItemGroup>
    </Target>
```

https://github.com/lindexi/lindexi_gd/tree/f49aa0c35c3161ed19af5a1670ae9ad8a1f679c2/DealayhuneaWheluyearfair

**Expected Behavior**:

We only update the Version of `Microsoft.Extensions.Logging.Abstractions` package

**Actual Behavior**:

We update all the package version

The Demo: https://github.com/lindexi/lindexi_gd/tree/f49aa0c35c3161ed19af5a1670ae9ad8a1f679c2/DealayhuneaWheluyearfair

**Comment by dagood** [comment]
Yeah, the `Update` attribute actually does nothing inside a `Target`, so that metadata change applies to all items. 🙁 You can use a `Condition` instead. More details here: https://github.com/dotnet/msbuild/issues/2835.

**Comment by lindexi** [comment]
@dagood Thank you

**Comment by sfoslund** [comment]
@lindexi it sounds like your question has been answered, but feel free to reopen this issue if not. Thanks!
