### ISSUE TITLE
dotnet pack "silently" fails when a bad -p argument is provided

### ISSUE THREAD

**Issue by PureKrome** [dotnet/sdk#12792]
Hi 👋🏻 

When I pass a bad/invalid `-p` argument to `dotnet pack` I get no error message or anything. I would have expected a bit more info to suggest that I was the idiot and need to fix up the command.

### Example / current behaviour:

`dotnet pack <some sln or csproj> -c RELEASE -p:/Version=1.0.0`

Nothing happens, no error message, nothing. Notice the INCORRECT `-p` argument? it _should be_ `-p:Version=1.0.0`

If i add "diagnostic" logging .. I get ONE line only -> that it tried to execute msbuild.dll to run this command:

`dotnet pack <some sln or csproj> -c RELEASE -p:/Version=1.0.0 -v diag`

e.g.

```
PS C:\Projects\Personal\Foo> dotnet pack .\src\Foo\Foo.csproj -c RELEASE -p:/Version=1.0.0 -v diag
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.1.302\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.302\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.302\dotnet.dll -maxcpucount -property:Configuration=RELEASE -p:/Version=1.0.0 -restore -target:pack -verbosity:m -verbosity:diag .\src\Foo\Foo.csproj
PS C:\Projects\Personal\Foo>
```

### Expected Behavior

I would like to see a better error message to help it easier to diagnose my mistake

e.g.

```
PS C:\> dotnet pack -c RELEASE -p:/Version=1.0.0
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

ERROR: An invalid property/parameter "/Version" was passed to MSBuild. 

PS C:\>
```

### Further info:

```
dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

```

**Comment by sfoslund** [comment]
Thanks for filing an issue, `-p` is actually not invalid. This is the switch for passing msbuild properties for all `dotnet` commands, see the [examples section of the docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#examples).

**Comment by PureKrome** [comment]
Hi @sfoslund thanks for the reply! 🎉 

> -p is actually not invalid

um .. a double negative .. so i'm guessing you mean: `-p` is a valid argument? (apologies if I've misunderstood)

I was saying that `-p` is ok .. it's just the NEXT part I got wrong:

I did `-p:/Version` with a bad `/` in there. when i do `-p:Version` it works.

Now, in the docs, it is saying `-p:PackageVersion`. (so i'm not sure why `Version` worked .. maybe backwards compat?)

So even if i gave the wrong MS Build property, I was hoping to get _better UX feedback_. That is what is the core of this issue. the FEEDBACK to the end user.

thoughts @sfoslund ?

**Comment by sfoslund** [comment]
I see, the problem is that any string is a valid MSBuild property. You can define your own MSBuild properties with this switch and we have no way of knowing if they are actually used in the build process or not (by our code or by your own custom targets).
