### ISSUE TITLE
Winform should not support netcoreapp3.0

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12799]
![image](https://user-images.githubusercontent.com/6993335/89492935-ae0e5680-d767-11ea-8f2f-4e49dd82d6f1.png)

**Comment by wli3** [comment]
@marcpopMSFT we should fix this before GA too.

**Comment by wli3** [comment]
Need to search for what is defining `SupportedNETCoreAppTargetFramework`

**Comment by dsplaisted** [comment]
This happens in the WindowsDesktop .props / .targets: https://github.com/dotnet/wpf/blob/master/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props#L131-L135

**Comment by wli3** [comment]
This issue was moved to dotnet/wpf#3532
