### ISSUE TITLE
Question about 2 IL commands (blt.s vs ble.s) (.NET Core 3.1)

### ISSUE THREAD

**Issue by Sin333** [dotnet/sdk#12835]
Hi dear developers. I have question about optimization cycle and argument validation in my projects.
Example: 
`       

        for(int i = 10; i<-1;i--) //Optimize cycle? (i=0 -> i < -1)
        {
            Console.WriteLine(i);
        }
        for(int i = 10; i<=0;i--) //Non optimize cycle? (i=0 -> i <0 || i==0)
        {
            Console.WriteLine(i);
        }
`
It's two identical cycles but validation iterator use various validation. After compile project in 'Release' first use blt.s (Branch to target if less than, short form.) and second use ble.s (Branch to target if less than or equal to, short form.).

I think first cycle is faster, but try get correct information about this information. How I can get information what is it faster or identical?

ILCodeURL: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHAZgAJ9KBhSgb1MpeqpwBZKBZACgEpGzViID0ogPIAHGGjBoAXnEoBjAJ4qMcAPzCRLAGYB7BLzQA7GJTSUAvJQIAGANzWAPAFoCztB4+C9fSYSfVDqAgBOM35nQJEAXzjWcQA5I3NKIxk5RWV1TR0kwxMzS2s7Bxd3Wxdff0oioRCwkRxI6Njm0MSuyh74oA==

**Comment by huoyaoyuan** [comment]
You should have mistyped the conditions. They should be `>-1` and `>=0`, or the 2 loops will be nops. 

After splitting them into 2 methods and switch to view JIT asm output in [sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgMwAEu5AwuQN7HlOUVYAs5AsngBQCU9Rs2EB6EQHkADjACWYGQC845AMYBPFQBs4AfiHCmAMwD2CHjIB2McjPIBecngAMAbhsA+ALR4XMz54F9AwYiAzDKPABOcz4XIOEAXyCk0OYySg5OHH4gkPDyMQA5YwtyY2k5RWV1LV145hMzS2tbB2c3GXc7Vz8A8nqmPPy0qJi41LCUxOIEoA=), the 2 loops gives identical instructions. So there will be no difference between them.

Finally, this question belongs to **runtime** repo, not this repo.

**Comment by Sin333** [comment]
Thanks u so much 👍
