### ISSUE TITLE
Publish error from VS 2019 to Azure

### ISSUE THREAD

**Issue by AniaBerthelot** [dotnet/sdk#12836]
Environnement :
- VS = Microsoft Visual Studio Community 2019 16.8.0 Preview 1.0
- .NET SDK 5.0.100-preview.7.20366.6
- Windows 10 family edition
- Azure cloud account

Goal :
- Publish my Blazor hosted (ASP Server) to Azure Cloud

Issue :
- I tried to publish my app via VS as self contained app to Azure and got this error : https://cdn.discordapp.com/attachments/663803973119115264/741749650817679450/unknown.png

Tests :
- I tried to build the app with debug mode it worked
- I tried to publish a FRESH Blaror wasm hosted .net 5.0 and got the same error
- I tried to publish ulterior (LTS) version and worked like a charm!

Conclusion :
- it's an issue of the latest preview version

**Comment by marcpopMSFT** [comment]
@AniaBerthelot Can you try this again with 16.8 preview 3 which contains .net 5 RC1 that we released earlier this week?

**Comment by marcpopMSFT** [comment]
Please reactivate if you can still reproduce this with RC1
