### ISSUE TITLE
Standalone installer for Net Core SDK "3.1.400" ?

### ISSUE THREAD

**Issue by abbotware** [dotnet/sdk#12848]
I updated visual studio to 16.7 and it removed my SDK 3.1.300

Blindly removing SDK's is probably a bad practice (but that's a separate issue). I manually set the SDK via **global.json** to ensure the build server and development environment use the same tool chain so this was unexpected...  none of my solutions were openable until i upgraded the SDK in the global.json

I looked to install the 3.1.400 SDK on build agents, but I can't find it anywhere?  

The latest SDK on https://dotnet.microsoft.com/download/ is only **3.1.302**  

How can one install just the Dot Net Core SDK 3.1.400 on a build agent?

**Comment by mphelt** [comment]
@abbotware if you are using windows build agent than installing [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) should install 3.1.400 for you.

I've run into related problem - https://github.com/dotnet/core/blob/master/release-notes/releases-index.json - also lists 3.1.302 as the latest one. This affects my Azure DevOps task - [Use .NET Core](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops), as for Version set to 3.1.* it doesn't resolve to 3.1.400, but 3.1.302.

**Comment by abbotware** [comment]
@mphelt - Thanks  - I have Linux (x64/arm) build agents too though, so I need the zipped binaries that are normally produced with each SDK build.    For now I just installed 3.1.300 / 302  on my development machine since this version is already on my build agents.

**Comment by wli3** [comment]
The latest patch of VS carries 3.1.401 and you can download 3.1.401 SDK in https://dotnet.microsoft.com/download/dotnet-core/3.1
