### ISSUE TITLE
Can't reference project targeting net5.0-windows from another project with same TargetFramework

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#12856]
Any project-to-project reference where both projects have a `TargetFramework` of `net5.0-windows` will fail:

> C:\Program Files\dotnet\sdk\5.0.100-preview.8.20406.14\Microsoft.Common.CurrentVersion.targets(1656,5): error : Project '..\wpflib\wpflib.csproj' targets 'net5.0-windows'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v5.0'. [c:\git\repro\net5.0-windows\wpf\wpf.csproj]

This is because the `CurrentProjectTargetFramework` passed to the `GetReferenceNearestTargetFrameworkTask` task is the `ReferringTargetFrameworkForProjectReferences` property, which doesn't include the platform information (ie it's `.NETCoreApp,Version=v5.0`).

Here's where the task is being called:

https://github.com/dotnet/msbuild/blob/e8c17c128ed847d4acd278b42a02df9621bd1652/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1656-L1662

Here's the source for the task: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/GetReferenceNearestTargetFrameworkTask.cs

The following seems to work as a workaround:

```xml
<ReferringTargetFrameworkForProjectReferences>$(TargetFramework)</ReferringTargetFrameworkForProjectReferences>
```

@nkolev92 @zkat

**Comment by wli3** [comment]
o	Add workaround to preview 8 SDK. 
o	NuGet to update GetReferenceNearestTargetFrameworkTask to take CurrentProjectTargetPlatformMoniker
o	Update MSBuild to pass in TPM to GetReferenceNearestTargetFrameworkTask
o	Fix inferring TargetPlatformVersion for inner builds
	Need work on SDK-side of project reference protocol to do inner builds to get TFM/TPM as necessary, include both TFM and TPM in project metadata that it returns
	Update GetReferenceNearestTargetFrameworkTask to consume target platform information

**Comment by marcpopMSFT** [comment]
We believe this should now be resolved.

**Comment by olowk** [comment]
I just downloaded the NET 5.0 official release, but I have the same problem as above. that I can't reference a net5.0-windows app from a net5.0. This is a blocking issue because I have to revert back now to .NET core 3.1 untill is fixed.

**Comment by wli3** [comment]
@olowk these are different issues. #12856 is about 2 net5.0-windows projects. You case, net5.0 cannot reference net5.0-windows is by design, since net5.0-windows is more specific. Referencing a net5.0-windows project means the net5.0 project now has a windows dependency, and it is no longer cross-platform, therefor it is not allowed or the project need to change from net5.0 to net5.0-windows.
