### ISSUE TITLE
Add .NET 4.6.1 support for .NET Standard 2.0 to SDK repo

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1286]
This includes targets and tasks to:

- Add references (facades and polyfills) if necessary (netstandard.dll is in the dependency graph)
  - [ ] Don't include `netstandard2.0` libraries when `nestandard.dll` is not in the closure. (necessary performance fast-path to not bloat hello-world).
- Resolve conflicts

This is a piece of the work required for #1267, which tracks the overall work.

**Comment by ericstj** [comment]
Fixed with https://github.com/dotnet/sdk/pull/1279
