### ISSUE TITLE
Add support for 'PublishIISAssets' flag that will suppress the generation/merging/copying of the web.config file and the ancm dll

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/sdk#12902]
Support the new DisableIIS msbuild property. 

When the property is set, suppress the generation/merging/copying of the web.config file and the ancm dll

`dotnet publish /p:DisableIIS:true`

**Comment by vijayrkn** [comment]
1.	This property will be honored for all publish cases and not just single file publish correct?
[vramak]To unblock, will honor the  new property (DisableIIS) only for the single file publish scenario which is the scenario that triggered this conversation. We can change this behavior later if needed.

2.	Do we want to default the property to true for all non-Windows RID? If so, any impact on the blazor-wasm RID?
[vramak]Won’t change any default behavior until we have confirmation that this won’t break other cases.

**Comment by Pilchie** [comment]
Ideally, names are in the positive, not the negative.  Maybe `PublishIISAssets` instead of `DisableIIS`?

**Comment by DamianEdwards** [comment]
Potential names:
- DisableIIS
- PublishIIS (in same vein as PublishSingleFile, PublishTrimmed, etc.)
- RemoveIISOutput (clear on what it does but not when)

**Comment by Pilchie** [comment]
`IncludeIISSupport` (too many I's and S's)

**Comment by DamianEdwards** [comment]
Given this will only apply during publish I kind of like sticking with the already-established "Publish" prefix.

`PublishIISAssets` is my favorite thus far.

**Comment by vijayrkn** [comment]
+1 on `PublishIISAssets`

**Comment by vijayrkn** [comment]
I have a PR out for this. Went with `PublishIISAssets`. Let me know if anyone has additional opinions on the msbuild property.
