### ISSUE TITLE
Cannot build netcore 3.1 C++/CLI due to cannot resolve 3.1 IJW host

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12911]
@Ninds commented on [Sun Aug 09 2020](https://github.com/dotnet/msbuild/issues/5637)

HI

### Issue Description
When building C++/CLI dll targeting .NET Core 3.1 with msbuild of VS 16.7 we have the following error \:
```
"C:\WorkSpace\Project1\Project1\Project1.vcxproj" (default target) (1) ->
(_GetIjwHostPaths target) ->
  C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(585,5)
: error NETSDK1114: Unable to find a .NET Core IJW host. The .NET Core IJW host is only available on .NET Core 3.1 or h
igher when targeting Windows. [C:\WorkSpace\Project1\Project1\Project1.vcxproj]

    0 Warning(s)
    1 Error(s)
```
This error did not occur in the last 16.7 preview.

#### Environment
```
$ dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
```
$ dotnet --list-sdks
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.400 [C:\Program Files\dotnet\sdk]
5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
```
```
C:\WorkSpace\Project1\Project1>msbuild -version
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.37604
```
[Reproducing Project File](https://gist.github.com/Ninds/7db8f055d8127bf0ebf50631d3b1dda8)

Targeting .NET 4.7.2 is ok 
Targeting .NET 5      is ok
Targeting .NET Core 3.1  is **NOT** ok

---

@Ninds commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-671571790)

Even switching off __use of previews of the .NET Core SDK__  doesn't fix the problem.

![preview](https://user-images.githubusercontent.com/5892035/89827470-8cd6ad00-db4f-11ea-9e7b-93d2f5ac835e.jpg)

```
1>C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(585,5): error NETSDK1114: Unable to find a .NET Core IJW host. The .NET Core IJW host is only available on .NET Core 3.1 or higher when targeting Windows.
```

---

@stic commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-672992631)

Same here, unable to target netcoreapp3.1 with .net core 5.0 preview installed.
I've tried to do some investigation (i.e. figure out how .net core targets are resolved during build), but even verbose build log doesn't explain much - suggestion, whilst providing fix it might be worth to improve build logging too. Cleaned everything cached internally under .vs, build outputs etc. By the way it's with VS16.7.1 (haven't tried 16.8 behaviour yet)

Workaround for now - remove preview 🤕 

---

@Forgind commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-673138334)

At face value, this sounds like a "we expected .NET Core __ but got .NET __" type problem, fixed by teaching it that it should work with .NET 5, too. I had some difficulty with reproducing the problem, though. Here's what I tried:
I created a new vcxproj and replaced its content with the project you provided.
I used MSBuild 16.7.0.37604 (full framework) to build the project, but that worked (not too surprising)
I used Core MSBuild 16.7.0.36003 to try to build the project and reset VCTargetsPath to point to the relevant folder, but it still failed for an unrelated reason—failing to find Platform.props. What did I do wrong?

Also, given that the error message is NETSDK1114, I have a feeling this is a dotnet/sdk problem. Is that correct, @wli3/@dsplaisted?

---

@dsplaisted commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-673150741)

It's probably an issue with dotnet/sdk, though it's hard to say.  A [binlog](https://aka.ms/binlog) would be helpful to investigate this.

---

@Ninds commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-673279028)

I suspected MSBuild only because all other things being equal under the last VS 16.7 preview everything worked.
Specifically, building for target .NET Core 3.1 with .NET 5 preview 7 installed.  If .NET 5 preview 7 is not installed there is no issue observed.  
When VS 16.7 Preview was being used and .NET Core 3.1 & .NET 5 preview were installed and everything was working, the only change that was then made was to upgrade VS to 16.7 Release for msbuild to exhibit the error.

The binlog file is attached.

[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/5067344/msbuild.binlog.zip)

Thanks

---

@Ninds commented on [Wed Aug 12 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-673285860)

Having uninstalled .NET 5 Preview 7 I attach also the msbuild binlog of a successful build  :
[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/5067400/msbuild.binlog.zip)

Is it still possible to download the last VS 16.7 preview ?

---

@wli3 commented on [Thu Aug 13 2020](https://github.com/dotnet/msbuild/issues/5637#issuecomment-673611771)

Assign it to me. I'll look into it.

**Comment by wli3** [comment]
@Ninds C++/CLI is a VS feature. A mix of net5.0-preview and a lower version of VS cannot fully support it. The scenario you mentioned will be supported in VS16.8. In the meanwhile, you cannot use **preview** SDK for C++/CLI.

**Comment by dsplaisted** [comment]
This is failing because the expected apphost pack is not installed because of a mismatch between the expected version from the 5.0 preview SDK and the 3.1 SDK that installs that pack.  The 5.0 preview SDK is looking for version 3.1.2 at C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\3.1.2.  The 3.1 SDK is probably installing a newer version of that pack.

**Comment by Ninds** [comment]
@wli3 
> C++/CLI is a VS feature. A mix of net5.0-preview and a lower version of VS cannot fully support it. The scenario you mentioned will be supported in VS16.8. In the meanwhile, you cannot use **preview** SDK for C++/CLI.

Hi. I am unclear by what you mean by "lower" version.  The mix of C++/CLI & .NET 5 Preview 7  was already supported in a 16.7 Preview so  doesn't that imply that 16.7 is a "high enough" version ? 

@dsplaisted 
>The 5.0 preview SDK is looking for version 3.1.2 at C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\3.1.2. The 3.1 SDK is probably installing a newer version of that pack.

Hi. I can try downgrading my .NET Core 3.1 install and see if the issue goes way. If it is the case that the .NET 5 Preview has a hardcoded dependency on a very specific version of .NET Core 3.1, would that be an oversight or by design ?

Thanks for investigating.

**Comment by Ninds** [comment]
@dsplaisted

Just installed .NET Core 3.1.2 and the problem when away. You were on the money !
Thanks very  much. It's a workaround I can live with.

**Comment by dsplaisted** [comment]
> Hi. I can try downgrading my .NET Core 3.1 install and see if the issue goes way. If it is the case that the .NET 5 Preview has a hardcoded dependency on a very specific version of .NET Core 3.1, would that be an oversight or by design ?

It's a side effect of the fact that VC++ projects don't support restoring NuGet PackageReferences.  In C# projects, we download the apphost pack during restore if necessary.  In VC++, it will only work if the apphost pack is already installed, until VC++ supports PackageReference.

**Comment by wli3** [comment]
Turned out 16.8 preview also cannot work.

**Comment by wli3** [comment]
@dsplaisted if we keep implicit version be in sync with VS that should work for the SDK come with VS. Once people install a different version of VS, it will out of sync again. Since VS will carry the highest runtime apphost by the time, and SDK's apphost pack version will also be the highest. But once we manually install a higher version SDK, it will ask for a even higher apphost pack, and due to no support for package restore, there is no place to find it.

Given the history of keep hacking around "C++/CLI does not support nuget restore". Do you think we can special casing C++/CLI's ResolveApphost, and just pick whatever is highest in `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\3.1.x` ?
