### ISSUE TITLE
Duplicate item detection fails to identify duplicates differing by '/' vs '\'

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#1292]
I've a asp.net core project targeted at netcoreapp1.1 which can build success offline with dotnet-cli V1.04 but met the error via travis,the error is as follows:
```
error : Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file
```
I develop the project on Visual Studio 2017 Enterprise(V15.2),you may want to see the build [here](https://travis-ci.org/WeihanLi/AccountingApp/builds/238645845),and I can build the project via dotnet-cli with dotnet-cli V1.04 successfully.

**Comment by WeihanLi** [comment]
I removed my js lib from project file and add it to my bower.json config,finally it build successfully.

**Comment by WeihanLi** [comment]
The  error is not a bug or something??

**Comment by nguerrera** [comment]
The error wouldn't be a bug if there truly were duplicate content items. Can you share the project file as it was when things failed and the exact change you made to get things working?

**Comment by WeihanLi** [comment]
Yeah.I can build it successfully on windows but not via travis on Ubantu,I'm thinking maybe there's a difference on the sdk between windows and other *unix systems.
- [the first commit on the project file](https://github.com/WeihanLi/AccountingApp/blob/f1f3e08604a8dcdccf4a6ae1e3a33dc9afee0403/AccountingApp/AccountingApp.csproj)
- [the second commit](https://github.com/WeihanLi/AccountingApp/blob/b3008242209766b601f9046906c317e6d32fdee1/AccountingApp/AccountingApp.csproj)

**Comment by nguerrera** [comment]
Are you sure you have the same version of the SDK on both machines. Can you do dotnet --info on the machine where build is succeeding? I would expect the error you're seeing in CI everywhere.

**Comment by nguerrera** [comment]
Another possibility: is there a Directory.Build.props or Directory.Build.targets above the csproj on the Windows machine but not in the repo?

**Comment by WeihanLi** [comment]
[ci build error](https://travis-ci.org/WeihanLi/AccountingApp/builds/238645845)
[ci build info](https://travis-ci.org/WeihanLi/AccountingApp/builds/238732498)

**Comment by nguerrera** [comment]
The error is correct. There project has content items that duplicate the implicit content items. What is dotnet --info on the local windows machine? The fact that it passes there is the real oddity.

**Comment by WeihanLi** [comment]
Both travis and my local windows are using dotnet V1.04

- ![travis dotnet info](https://travis-ci.org/WeihanLi/AccountingApp/builds/238732498#L601)
-

**Comment by nguerrera** [comment]
OK. I can repro the (incorrect) successful build on Windows of https://github.com/WeihanLi/AccountingApp/blob/f1f3e08604a8dcdccf4a6ae1e3a33dc9afee0403/AccountingApp/AccountingApp.csproj 

It appears that differing slashes in the implicit globbed items is defeating the duplicate content detection:

```
wwwroot/lib\layer\layer.js
    CopyToPublishDirectory = PreserveNewest
    OriginalItemSpec = wwwroot/lib\layer\layer.js
    TargetPath = wwwroot/lib\layer\layer.js


wwwroot\lib\layer\layer.js
    OriginalItemSpec = wwwroot\lib\layer\layer.js
    TargetPath = wwwroot\lib\layer\layer.js
```

@dsplaisted

**Comment by nguerrera** [comment]
Changing the title to reflect the true problem. The error you see on Ubuntu is correct and the fix you made is correct. The bug is that the error doesn't trigger on Windows as it should due to different spelling between items representing the same files.

**Comment by WeihanLi** [comment]
Ok,thanks.By the way,copy and paste files in vs may cause project file different like mine
