### ISSUE TITLE
Include .NET 4.6.1 support for .NET Standard 2.0 in Mono's MSBuild

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1294]
In dotnet/sdk#1267, we're adding tasks, targets, and assemblies to be referenced (facades and polyfills) to support .NET Standard 2.0 in .NET 4.6.1.

These assets should also ship with the Mono version of MSBuild.

cc @akoeplinger

**Comment by dsplaisted** [comment]
@akoeplinger @mhutch The tasks and targets have been added to the SDK repo with PR #1279.  We are going to consume them in the CLI via the Microsoft.NET.Build.Extensions package (currently version 2.0.0-preview2-20170606-4) which is published to the dotnet-core MyGet feed.  You may want to also use this package to get these tasks and targets into Mono MSBuild.

**Comment by akoeplinger** [comment]
@radical could you please take a look ^ and add them to our msbuild fork?

**Comment by radical** [comment]
Added to `xplat-master` and PR for 15.3 is open https://github.com/mono/msbuild/pull/16 .

**Comment by nguerrera** [comment]
Fixed by mono/msbuild#16
