### ISSUE TITLE
error : The local source '/home/gysun/myNuGetServer' doesn't exist. 

### ISSUE THREAD

**Issue by sunny868** [dotnet/sdk#12960]
## Details about Problem

NuGet Version: 5.5.0.6382
.NET Core SDK (3.0.101)
OS version (ubuntu-16.04):

## Detailed repro steps so we can see the same problem
1. nuget sources Add -Name "MyServer" -Source /home/gysun/myNugetServer
2. nuget add new_package.1.0.0.nupkg -source /home/gysun/myNugetServer
3. git clone https://github.com/dotnet/corefx.git ;cd corefx
4. vim NuGet.config and add 

`
           <add key="MyServer" value="/home/gysun/myNuGetServer" /> 
`
5. then run 
          ./build.sh --configuration Debug --arch arm64 /p:DisableCrossgen=true /p:PortableBuild=true /p:SkipTests=true
    then error is :
      /corefx/.dotnet/sdk/3.0.100/NuGet.targets(123,5): error : The local source '/home/gysun/myNuGetServer' doesn't exist. [/corefx/external/runtime/runtime.depproj]

so , I don`t know to add a local souce to NuGet.config. I want get a help ,thank you very much!

**Comment by dagood** [comment]
I don't quite understand your repro steps. `git clone https://github.com/dotnet/corefx.git` is a mostly empty directory, and why is the CoreFX repo involved? Why are you using that particular build command? Could you make a repro with a simpler project, a `dotnet new console` for example?

That all said, you have a case mismatch in your path that might be causing you some problems:

> nuget sources Add -Name "MyServer" -Source /home/gysun/my`Nuget`Server

> \<add key="MyServer" value="/home/gysun/my`NuGet`Server" /\>

**Comment by sunny868** [comment]
Thank you .
Actually. I`m building corefx for Arch MIPS using "./build.sh --arch mips64". But that need  runtime.linux-mips64.microsoft.netcore.*nupkg, I have builded these package sucessfully in coresetup,but can`t upload to nuget.org, so I want to make a Local NuGet package feeds for these runtime.linux-mips64.*.nupkg 、Microsoft.NETCore.DotNetAppHost.*.nupkg and so on.

> I don't quite understand your repro steps. `git clone https://github.com/dotnet/corefx.git` is a mostly empty directory (no nuget.config, no build command), and why is the CoreFX repo involved? Why are you using that particular build command? Could you make a repro with a simpler project, a `dotnet new console` for example?
> 
> That all said, you have a case mismatch in your path that might be causing you some problems:
> 
> > nuget add new_package.1.0.0.nupkg -source /home/gysun/my`Nuget`Server
> 
> > <add key="MyServer" value="/home/gysun/my`NuGet`Server" />

Thank you .
Actually. I`m building corefx for Arch MIPS using "./build.sh --arch mips64". But that need  runtime.linux-mips64.microsoft.netcore.*nupkg, I have builded these package sucessfully in coresetup,but can`t upload to nuget.org, so I want to make a Local NuGet package feeds for these runtime.linux-mips64.*.nupkg 、Microsoft.NETCore.DotNetAppHost.*.nupkg and so on.

**Comment by sunny868** [comment]
Thank you very much. The problem was located and solved
