### ISSUE TITLE
presence of sdk 1.0.4 breaks existing 1.0.0-preview2-003121 projects

### ISSUE THREAD

**Issue by kentatcap** [dotnet/sdk#1301]
If SDK 1.0.4 (possibly even 1.0.3) exists in c:\program files\dotnet\sdk, restore packages and build in VS 2015 IDE will fail, but command line dotnet restore/dotnet build will work; error below.

C:\Program Files\dotnet\dotnet.exe restore "<solution path>\.vs\restore.dg"
<solution path>\.vs\restore.dg(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

global.json shows sdk version as 1.0.0-preview2-003131

removed/renamed 1.0.4 directory and VS 2015 IDE works again

It all started when I installed VS 2017, which I assume installed dotnet SDK 1.0.4.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5344
