### ISSUE TITLE
vsdbg memory leak

### ISSUE THREAD

**Issue by Zetanova** [dotnet/sdk#13065]
Visual Studio is using the binary `vsdbg` to attach the debug session inside a container.

A long running debug session with few thousand debug output lines,
`vsdbg` will consume an high amount of memory.
The memory grow is linear and reaches >800MB.

A workaround would be to detach and attach Visual Studio to the running debug session.

This issue i experience already in 2019 and it is persistent in the current versions:
Visual Studio 2019 16.6.5
mcr.microsoft.com/dotnet/core/sdk:3.1
mcr.microsoft.com/dotnet/core/aspnet:3.1
win10 2004, wsl2 docker 2.3.0.4

**Comment by Zetanova** [comment]
I had now a long debug session over 2-3 days.

There after 2-4 days the user-debug output stopped and only 
`The thread 0xXX has exited with code 0 (0x0).`
got printed out over view houres.

I detached visiual studio from the debug session and `vsdbg` inside the container got closed.
The container fall from 870MB memory usage to 160MB.

After i attached a new debug session to the container, 
user-debug output got generated and the app tried to reconnect and made worked/responded.

It is most likely a thread starvation inside the container from `vsdbg`

**Comment by Zetanova** [comment]
Issue persist in:
Visual Studio 2019 16.9.1
mcr.microsoft.com/dotnet/sdk:5.0
mcr.microsoft.com/dotnet/aspnet:5.0
win10 2004, wsl2 docker 20.10.5
docker-compose **3.7**

**Comment by gregg-miskelly** [comment]
Hello, my team owns vsdbg. I was able to track down the issue you were running into, and I have a fix. Hopefully we should have it out soon...

**Comment by gregg-miskelly** [comment]
A new vsdbg has been released with this issue fixed. I don't have access rights to close this issue.

**Comment by Zetanova** [comment]
thx, I will close the issue then.
