### ISSUE TITLE
Reenable static graph tests

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#13081]
See original PR comment: https://github.com/dotnet/sdk/pull/13078#issuecomment-679312551

Reenable the static graph tests `It_cleans_the_project_successfully_with_static_graph_and_isolation` and `It_builds_the_project_successfully_with_static_graph_and_isolation`.

**Comment by sfoslund** [comment]
@dsplaisted were you going to take this?

**Comment by dsplaisted** [comment]
Yes, but I need help, probably from @rainersigwald or @cdmihai, to understand how to fix the issue.

**Comment by dsplaisted** [comment]
Static graph appears to have been broken by https://github.com/dotnet/msbuild/pull/5657, though we don't yet understand why.

**Comment by sfoslund** [comment]
The master MSBuild insertion https://github.com/dotnet/sdk/pull/13077 is also failing due to static graph issues, but I am not disabling them there since master is not on a time crunch. Once this is fixed in 5.0.1xx we will need to port the fix to that PR.

**Comment by cdmihai** [comment]
@jeffkl and I root caused the issue:

- https://github.com/dotnet/msbuild/pull/5657 changes the runtime graph (this is the callgraph that emerges as vanilla msbuild does its JIT top down descent) and makes it different from the inferred static graph. Up until now, an outer build only called into its inner builds when it was a top level entry point project. When the outerbuild was not a root, it never called in its innerbuilds (instead the projects referring to the outer build called its inner builds). After this PR an outer build always calls its innerbuilds with GetTargetFrameworksWithPlatformForSingleTargetFramework, regardless if it’s a root node or not. This breaks an assumption that static graph makes about how outer builds interact with inner builds.
- Execution timeline:
  - The undeclared inner builds get scheduled to run before the static graph schedules its own ProjectInstances for those same innerbuilds.
  - When static graph schedules its own project instances for those inner builds they conflict in the BuildManager’s ConfigCache with the project instances from the undeclared inner builds
  - This conflict incorrectly triggers a project instance conflict resolution strategy that was put there as a workaround for a CPS-MSBuild bug.
 - The resolution strategy adds a global property containing a GUID into the static graph’s project instances
 - This GUID eventually causes a cache miss which triggers the /isolate error
- Things that contribute to this:
  - Projects calling into themselves with different global properties are exempt from /isolate constraints. Had this not been the case, /isolate would have failed earlier with a more relevant error message

Next steps:
-	Re-enable the sdk tests without /isolate. /graph should find hard errors that will definitely break CloudBuild. Without /isolate, small runtime deviations may accumulate, which at some point may or may not break Cloudbuild. So for now it’s okay to only leave /graph
-	Figure out a fix

**Comment by cdmihai** [comment]
#13171 reenables graph tests bug keeps isolation checks disabled.

**Comment by marcpopMSFT** [comment]
The tests are currently running.
