### ISSUE TITLE
NuGet package downgrades occurring due to “nearest wins”, are errors by default   

### ISSUE THREAD

**Issue by anangaur** [dotnet/sdk#1310]
https://github.com/NuGet/Home/issues/4895: NET Core 2.0: Register all warnings/errors to assets file (including PackageTargetFallback)
NuGet spec: https://github.com/NuGet/Home/wiki/Improved-NuGet-warnings
List of errors and warnings: https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings

Downgrade warning is [NU1605](https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings#nu1605) 
@rrelyea & @emgarten  to confirm if this is the only one or if there are others to be elevated as errors by default.

Post NuGet work, the SDK needs to insert the right properties to .NET Core 2.0 and .NET Standard 2.0 projects to mark NU1605 (and others if applicable) as error. This property should be visible to the end-user when he/she goes to the Project->Properties->Build. He should be able to revert the warning from being an error to a regular warning.

**Comment by livarcocc** [comment]
This has been implemented.
