### ISSUE TITLE
netstandard.dll is not added to net461-SDK project when referencing ns2.0 library via ProjectReference

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1311]
This is a bug in the intial work for https://github.com/dotnet/sdk/issues/1267.

For SDK projects I schedule `ImplicitlyExpandNETStandardFacades` after `ResolveLockFileReferences`.

I need to run `ImplicitlyExpandNETStandardFacades` before conflict resolution because conflict resolution may remove items from packages based on these additions.

I need to run `ImplicitlyExpandNETStandardFacades` after `ResolveProjectReferences` because project references may depend on netstandard.dll.

In SDK projects this is problematic because they schedule conflict resolution as part of [ResolvePackageDependenciesForBuild](https://github.com/dotnet/sdk/blob/67fd3a133eb052fe396377b09b291cf32cd88212/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L108-L129) which runs `BeforeTargets="AssignProjectConfiguration"`.  `AssignProjectConfiguration` is a dependency of  `ResolveProjectReferences`.  So the current SDK task sequencing makes it impossible to run `ImplicitlyExpandNETStandardFacades` both after `ResolveProjectReferences` and before conflict resolution.

I don't believe conflict resolution is required to run before `AssignProjectConfiguration`, I suspect it was merely placed there out of convenience in https://github.com/dotnet/sdk/commit/09c45a6f50cee8bb496a73ff440648e4561c7e75.

I propose we move `_HandlePackageFileConflicts` out of `ResolvePackageDependenciesForBuildDependsOn` and place it in [ResolveAssemblyReferencesDependsOn](https://github.com/dotnet/sdk/blob/67fd3a133eb052fe396377b09b291cf32cd88212/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L62).

I also propose we expose its DependsOnTargets property value so that folks who need to add references can do so safely and ensure they run before conflict resolution.

/cc @dsplaisted @eerhardt @nguerrera

**Comment by eerhardt** [comment]
nit discussion:

> I also propose we expose its DependsOnTargets property value so that folks who need to add references can do so safely and ensure they run before conflict resolution.

The guidance from @davkean and @rainersigwald was to not use DependsOnTargets properties for new targets, but instead use the built-in BeforeTargets/AfterTargets mechanisms for extensiblity.  See https://github.com/dotnet/sdk/pull/579 for more discussion on the topic.

**Comment by ericstj** [comment]
Ok, I'll see if I can achieve the correct scheduling without exposing depends on.  It feels like there are cases where you still need to use dependson because both before and after act as a `every` where dependson acts like `all`.

**Comment by ericstj** [comment]
Here is a summary of my findings:
- SDK projects run `ResolveProjectReferences` *after* resolving NuGet packages.
- Non-SDK projects using PackageReference or project.json run `ResolveProjectReferences` *before* resolving NuGet packages.  In fact ResolveProjectReferences is an explicit dependency of resolving NuGet packages.  Likely a remnant of https://github.com/NuGet/NuGet.BuildTasks/commit/e4ca77e00e1a016733a178a9408dccd61c0534f7 which was later removed with https://github.com/NuGet/NuGet.BuildTasks/commit/057af5b6ff9521551cf6dcee5cd737993a943472.
