### ISSUE TITLE
Building Netstandard 2.0 class library fails if dependency includes System.Net.HttpClient

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#1313]
With 15.3 preview 1, building a `netstandard2.0` class lib that has a dependency on a package including `system.net.httpclient` 4.3.2, I get build errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'HttpClient' exists in both 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	ClassLibrary8	C:\dev\ClassLibrary8\ClassLibrary8\obj\Debug\netstandard2.0\RefitStubs.g.cs	39	Active
Error	CS0433	The type 'HttpClient' exists in both 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	ClassLibrary8	C:\dev\ClassLibrary8\ClassLibrary8\obj\Debug\netstandard2.0\RefitStubs.g.cs	40	Active
Error	CS0433	The type 'HttpClient' exists in both 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	ClassLibrary8	C:\dev\ClassLibrary8\ClassLibrary8\obj\Debug\netstandard2.0\RefitStubs.g.cs	42	Active

```
[ClassLibrary8.zip](https://github.com/dotnet/sdk/files/1057914/ClassLibrary8.zip)

You can also see the solution explorer doing something silly:
![1](https://user-images.githubusercontent.com/1427284/26878375-3f774268-4b5b-11e7-93be-ed268609a347.png)

**Comment by livarcocc** [comment]
@ericstj @dsplaisted Conflict resolution issue?

**Comment by ericstj** [comment]
I believe this is a known issue: https://github.com/dotnet/standard/issues/372.

@onovotny can you update to the latest NETStandard.Library package from dotnet-core feed and see if it repros?

**Comment by onovotny** [comment]
@ericstj will that work with my preview 1 tooling?

**Comment by ericstj** [comment]
Yep, it should.

**Comment by onovotny** [comment]
Okay, that worked, closing this as a dup then.

**Comment by weitzhandler** [comment]
@ericstj 

I'm having the same issue, but in a NetStandard 1.4 assembly.
Adding the line you referenced above:

>`<NETStandardImplicitPackageVersion>2.0.0-preview2-25401-01</NETStandardImplicitPackageVersion>`

into the _csproj_ file didn't remove the error, but that's probably because I didn't know what to replace `2.0.0-preview2-25401-01` with.

**Comment by ericstj** [comment]
@weitzhandler open a new issue with a full description of your issue, including the version of the SDK/VS that you are using.

**Comment by weitzhandler** [comment]
@ericstj #1463
