### ISSUE TITLE
Cannot build WinUI sample in preview 8

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#13135]
https://github.com/microsoft/WinUI-3-Demos/tree/master/DemoBuildCs

**Comment by huoyaoyuan** [comment]
Symptoms from a project which was good for Preview 7:

When not changed, VS claims that cannot locate platform SDK, and refuses to load the project. 
If specify `net5.0-windows` or `<TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>`, it will be recognized as UAP.

Version used: SDK 5.0.100-preview8, VS 16.8P2.1

**Comment by huoyaoyuan** [comment]
Additional:

My project (should be very close to the sample) cannot build under VS16.8+SDK P7. SDK P8 rejects VS16.7. The only working combination is VS16.7+SDK P7.

**Comment by huoyaoyuan** [comment]
Update at RC1:
Able to load and restore the project after changing TFM to `net5.0-windows10.0.18362`. WinUI targets contains a condition-less `<TargetFrameworkIdentifier>UAP`</TargetFrameworkIdentifier>`, which causes build failure. Maybe SDK side work is done and changes are required at WinUI side?

**Comment by wli3** [comment]
Yes. We are working on to remove the UAP targetplatformidentifier cc @Scottj1s

**Comment by wli3** [comment]
Resolved and tested in WinUI

**Comment by KC-Belgium** [comment]
Hi, so we need to wait for an update in WinUI3?

**Comment by wli3** [comment]
@Scottj1s do you know?

**Comment by KC-Belgium** [comment]
> @Scottj1s do you know?

Still no update on this?

**Comment by huoyaoyuan** [comment]
According their roadmap, WinUI 3 Preview 3 is planned in November,  around the time of .NET 5 RTM (I think it should be Nov 10).

**Comment by jeffrosenthal** [comment]
Just download and installed VS 16.8 preview and WinUI Project Templates.vsix Tried to create a WinUI desktop application and got this error.
Ideas?

**Comment by huoyaoyuan** [comment]
Currently there should be no way to get WinUI worked under 16.8. The only working version is VS16.7 + .NET 5 Preview 5~7.

**Comment by jamescarter-le** [comment]
+1 Still an issue, looking to move away from UWP into .NET 5 ASAP.

**Comment by KC-Belgium** [comment]
Winui3 preview 3 was released this week, after installation everthing is working fine now.
