### ISSUE TITLE
Darwin build legs are often flaky

### ISSUE THREAD

**Issue by mmitche** [dotnet/sdk#13136]
The Darwin build legs in 5.0 are fairly flaky and time-out quite a bit. This could be because of a real hang, or perhaps just test time:

Examples:
- https://dev.azure.com/dnceng/public/_build/results?buildId=788485&view=logs&j=7f92ee92-d616-5b83-8b8f-b48bdd4f3b4f
- https://dev.azure.com/dnceng/public/_build/results?buildId=788481&view=logs&j=60adcdc4-a9f0-5668-20f7-b72181c68fb2

**Comment by mmitche** [comment]
I've retained both these examples.

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/sdk/pull/13338, #13350 tracking reenabling
