### ISSUE TITLE
msbuild /t:Restore on sln with a Microsoft.NET.Sdk.Web project.

### ISSUE THREAD

**Issue by dazinator** [dotnet/sdk#1314]
In my vs2017 solution, I have multiple csproj files, most of them use `Microsoft.NET.Sdk` but the web site uses `Microsoft.NET.Sdk.Web`.

When I do an `msbuild /t:Restore` on the solution file, only the projects consuming `Microsoft.NET.Sdk` are restored, the website project consuming `Microsoft.NET.Sdk.Web` appears to be ignored. There is no warning about this, I just couldn't see the project listed anywhere in the build output. This then results in an msbuild /t:Build on the sln failing, as that does attempt to build the project, but it's dependencies were not restored.

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5372
