### ISSUE TITLE
An error message appeared when building the core project after changed the Target Framework from .NET Core 3.1 to .NET 5.0

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/sdk#13179]
**Visual Studio Version**:
Dev16 16.8.0 Preview 3.0 [30424.195.main]

**More info:**
1. This is a regression, which can reproduce on 16.8.0 Preview 3.0 [30424.173.main], can't reproduce on Dev 16.8.0 Preview 3.0 [30424.160.main].
2. The issue also can reproduce on WPF(Core) project, can't reproduce on console(core) project.
3. The issue can't reproduce when building & running the core project by using command line.

**Steps to Reproduce**:
1. Create a winforms core project, and check the default Target Framework in the property page.
2. Build the winforms core project.
3. Change the Target Framework from .NET Core 3.1 to .NET 5.0 in the property page.
4. Build the winforms core project. again.

**Expected Behavior**:
After steps4, the winforms core project build successfully with no error.

**Actual Behavior**:
An error message appeared when building the core project after changed the Target Framework from .NET Core 3.1 to .NET 5,0.
![Exception](https://user-images.githubusercontent.com/38325459/91138587-ae07d380-e6e1-11ea-8df0-08f74a3ca2e9.PNG)
![CoreNewIssue](https://user-images.githubusercontent.com/38325459/91138625-b102c400-e6e1-11ea-974e-ca8a1c2ceeab.gif)

**Comment by KlausLoeffelmann** [comment]
@dsplaisted: Are there any updates or known workarounds?
@KathleenDollard: FYI for the impacted VB work.

**Comment by dsplaisted** [comment]
#13093 was merged on Friday and should be in the latest RC1 SDK builds (e.g. https://aka.ms/dotnet/net5/rc1/Sdk/dotnet-sdk-win-x64.exe).  I believe that will fix this bug.

**Comment by Zheng-Li01** [comment]
@dsplaisted, yes, for now the Winforms core project can build successfully when  changing the Target Framework to 5.0 after installed the latest .NET 5.0.100-rc.1.20430.3 from https://aka.ms/dotnet/net5/rc1/Sdk/dotnet-sdk-win-x64.exe.
![GitHubIssue](https://user-images.githubusercontent.com/38325459/91691439-354dbf00-eb9a-11ea-8e01-e8825321b222.PNG)

**Comment by Zheng-Li01** [comment]
For now, the wiforms core project build failed after installed the latest .NET 5.0.100-rc2.20458.12 from https://github.com/dotnet/core-sdk, see below reproduce GIF.
![CoreIssue](https://user-images.githubusercontent.com/38325459/92563651-789ae280-f2aa-11ea-8209-3a4b6e002880.gif)

**Workaround.**
`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">  to <Project Sdk="Microsoft.NET.Sdk">;
<TargetFramework>net5.0</TargetFramework> to <TargetFramework>net5.0-windows</TargetFramework>.`

**Comment by dsplaisted** [comment]
This is the expected behavior currently.

@melytc @jjmew Is there an issue tracking the work to automatically add `-windows` to the `TargetFramework` when retargeting a WPF or Windows Forms app from .NET Core 3.x to .NET 5.0?

**Comment by melytc** [comment]
@dsplaisted I just created one in our repo: https://github.com/dotnet/project-system/issues/6601

**Comment by marcpopMSFT** [comment]
The work to automatically add -windows shipped in 16.10 so resolving this as I also didn't reproduce the issue.
