### ISSUE TITLE
Publishing blazorwasm template project is broken with the latest SDK

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#13190]
### Describe the bug
New Blazor WASM template projects don't work after publish.

### To Reproduce
1. Install 5.0.100-rc.1.20427.6 SDK from https://github.com/dotnet/installer#installers-and-binaries
2. `dotnet new blazorwasm`
3. `dotnet publish -c Release`
4. Try to run the published app

### Expected results
The app loads correctly

### Actual results
The app sits at:

![image](https://user-images.githubusercontent.com/8291187/91473397-6f4b5800-e85e-11ea-9530-30f0f8c4ca7d.png)

### Further technical details
Looking at the output of the publish directory, it appears non of the ASP.NET assemblies are being published:

![image](https://user-images.githubusercontent.com/8291187/91473469-89853600-e85e-11ea-81c5-bad32e2b304f.png)

cc @pranavkm @mkArtakMSFT @SteveSandersonMS

**Comment by dsplaisted** [comment]
I've added a commit to #13093 which should fix this issue.

**Comment by eerhardt** [comment]
@dsplaisted @pranavkm -
How can we test this scenario to ensure this kind of regression doesn't occur in the future? I'm surprised it was only caught by a developer trying it manually.

**Comment by dsplaisted** [comment]
As part of fixing the bug, I added a test that covers the failing case (targeting .NET 5 with a PackageReference with PrivateAssets=All).

We could also add a test to dotnet/installer that creates a Blazor app and makes sure it builds correctly.  We have similar tests for various other templates, though I think we just check whether they successfully build, which wouldn't have caught this.

**Comment by pranavkm** [comment]
@eerhardt typically these sort of cross-integration testing is performed by our  CTI team. They help verify the matrix of latest VS \ SDK etc. I'm a little surprised they haven't seen this issue as yet since it affects both standalone as well as hosted publishing both of which we have coverage for.

@ajaybhargavb in case you might know where they're at with testing this.

**Comment by dsplaisted** [comment]
@pranavkm It's possible it hasn't been caught because a version of the SDK with the issue hasn't been inserted into VS.

**Comment by pranavkm** [comment]
Most of these tests usually start off by installing a nightly build of the installer.

**Comment by ajaybhargavb** [comment]
> @ajaybhargavb in case you might know where they're at with testing this.

Can you provide the earliest SDK version that has this issue? I'll look into why they may have missed this.
