### ISSUE TITLE
--self-contained value is not validated by the CLI

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#13196]
It seems that the value of the `--self-contained` command line parameter is not validated by the CLI.

Using 5.0.100-rc.1.20427.4:
```console
dotnet new console
dotnet publish -r win-x64 --self-contained jupiter

..\5.0.100-rc.1.20427.4\sdk\5.0.100-rc.1.20427.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(68,33): error MSB4030: "jupiter" is an invalid value for the "SelfContained" parameter of the "ProcessFrameworkReferences" task. The "SelfContained" parameter is of type "System.Boolean".
```

While the error does say that the value is not a boolean, it talks about `ProcessFrameworkReferences` task and its parameter, not about the command line option. Note that this is really easy to get wrong because of how the CLI parsing works. The command line help says:

```console
  --self-contained                      Publish the .NET runtime with your application so the runtime doesn't need to be installed on the target machine.
```

So it seems that --self-contained doesn't take any value. In reality the value is optional, but the CLI parser only recognizes things starting with `-` as non-values. So for example the below command line which looks perfectly valid fails:

```console
dotnet publish -r win-x64 --self-contained /p:PublishSingleFile=true

..\5.0.100-rc.1.20427.4\sdk\5.0.100-rc.1.20427.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(68,33): error MSB4030: "/p:PublishSingleFile=true" is an invalid value for the "SelfContained" parameter of the "ProcessFrameworkReferences" task. The "SelfContained" parameter is of type "System.Boolean".
```

**Comment by am11** [comment]
This issue and #3164 are fixed in .NET 6 (master branch), as a (positive) side-effect of switching to command-line-api. :)
Tested with `6.0.100-alpha.1.20571.4`.

**Comment by AntonLapounov** [comment]
Closing as fixed according to https://github.com/dotnet/sdk/issues/13196#issuecomment-732361316.
