### ISSUE TITLE
Use 4 part version numbers for Windows 10 TargetPlatformVersion

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#13266]
When targeting Windows, when the `TargetPlatformVersion` is 10.0 or later, we should normalize to a 4-part `TargetPlatformVersion`

TargetFramework | TargetPlatformVersion
------- | --------
net5.0-windows | 7.0
net5.0-windows10.0.18362 | 10.0.18362.0
net5.0-windows10.0.18362.0 | 10.0.18362.0

We should also support parsing the `TargetPlatformIdentifier` from the `TargetFramework` even if `TargetPlatformVersion` is explicitly specified:

```xml
<TargetFramework>net5.0-windows</TargetFramework>
<TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
```

In this case, the `TargetPlatformIdentifier` should be set to `Windows`.  Right now it's not set due to the "And" in the following condition: https://github.com/dotnet/sdk/blob/a5422e3369a0b8b2bbc97c757b825c7f941e6efa/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L63

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/sdk/pull/13272
