### ISSUE TITLE
Backport .NET Core 3.1 SDK upgrade behavior to 2.1

### ISSUE THREAD

**Issue by nakarnam** [dotnet/sdk#13343]
For .NET Core 3.1, .NET Core SDK patch updates within a feature band behave as upgrades. The latest servicing update will remove all previous patch updates in the same feature band upon successful installation for e.g. SDK version 3.1.102 will replace 3.1.101 and 3.1.100, 3.2.204 will replace 3.1.200 through 3.1.203, etc. 

This issue is to track the effort to backport this behavior to .NET Core 2.1 SDK patch upgrades within a feature band as we prepare to offer [.NET Core updates via the Microsoft Update platform](https://github.com/dotnet/core/issues/5013). SDK updates outside of a feature band are installed side by side.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/27079
