### ISSUE TITLE
Increase F# test coverage

### ISSUE THREAD

**Issue by enricosada** [dotnet/sdk#1334]
Adding this to track adding f# testing to test suite.

Like:

- duplicate the test suite assets projects, like [TestAssets/TestProjects/CrossTargeting](https://github.com/dotnet/sdk/blob/master/TestAssets/TestProjects/CrossTargeting), and run tests both with csproj and fsproj.
- add docs about:
  - f# vs c# difference for projects, so is easier for dev to add new tests
  - who to add for help?

/cc @cartermp @KevinRansom @dsyme

**Comment by cartermp** [comment]
👍 Thanks a bunch, @enricosada.

> f# vs c# difference for projects, so is easier for dev to add new tests

Do you think the main issue (if there were to be any) would be in how to multitarget with F# code?  I imagine any changes that need doing, if they're only scoped to changing project files, should be basically the same as C#.  I'm happy to help with any documentation on this front.

**Comment by nguerrera** [comment]
We should be selective about what assets we duplicate, balancing coverage vs. maintenance and test run-time. We also need to add VB coverage and need to be mindful about the costs of doing testing x3. 

The priority for having coverage in all languages should be on basic end-to-end scenario tests. Cross-targeting is indeed a good example of that.

On the other hand, individual regression tests for very specific issues can remain in one language. Ideally, we'd use a mix of C#, VB, and F# for those without writing and running echo one 3 times.

**Comment by enricosada** [comment]
Ihmo is also possible to rerun the same test suite for each lang  + some e2e for mixed scenario who run always.
Test suite run cost is minimized, if done only on CI, and helps (for F# and VB somewhat because anyway is roslyn and same targets) to not be second class on test suite, who may find errors or not. 
the subtle differences are subtle, regression tests helps only after the fact.

- avoid assets duplication: can be done renaming the `csproj` -> `fsproj` . And `<Compile Include="Program.fs" Condition=" '$(Language)' = 'F#' "/>`. Same for VB maybe (who doesnt need the `Compile` item either). Or using a specific import
- avoid test duplication: use an env var. `SDK_TEST_SUITE_LANG` and then inside `GetAssets` will use that if set, otherwise c# => tests written just once, as language agnostic.
- test run time: run for other lang only on ci server (or using just `set SDK_TEST_SUITE_LANG=F# && msbuild /t:Test` locally, if needed)

**Comment by dsyme** [comment]
Linking https://github.com/Microsoft/visualfsharp/pull/3215 which indicates the need to increase F# test coverage

**Comment by dsyme** [comment]
@nguerrera @enricosada  TBH I'd be pretty comfortable with an initial duplication of the TestAssets/TestProjects/CrossTargeting test suite to make sure we flush out corner-case problems

**Comment by enricosada** [comment]
i'll send some tomorrow.
@dsyme any specific end 2 end scenario to test? just the flow is ok (create a lib, create an app, add the lib, add a package, etc..)

**Comment by livarcocc** [comment]
We have F# coverage in the CLI side already. Given that this repo will be merged with the CLI soon, I am going to close this issue.
