### ISSUE TITLE
"Ensure you have included 'Xxx' in your project" message can be misleading in out-of-date restore case

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1337]
```
Assets file 'C:\Git\NetCoreProjectReference\classlib_netstandard20\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure you have included 'netstandard2.0' in the TargetFrameworks for your project.
```

This should mention the possibility that restore is out-of-date.  

Our errors should not assume that restore is always automatic. It's not in several cases:

* passing --no-restore to `dotnet`
* using `msbuild` instead of `dotnet`
* disabling auto-restore in IDE

So the error isn't always that the project file doesn't have the TargetFramework(s) or RuntimeIdentifier(s), it could also be that the project hasn't been restored since those changed.

**Comment by livarcocc** [comment]
This seems like an easy one.
