### ISSUE TITLE
dotnet global tool can not run in UOS system

### ISSUE THREAD

**Issue by lindexi** [dotnet/sdk#13399]
### Description

The UOS system is a Linux system. See https://en.wikipedia.org/wiki/Unity_Operating_System

The dotnet global tool can not run in UOS system.

### Configuration

System: UOS system ( debian 10 x64)

### Other information

![](https://user-images.githubusercontent.com/16054566/92238384-b800b200-eeeb-11ea-93f4-87c3e89d134d.png)

**Comment by marcpopMSFT** [comment]
I would try this again today as there have been improvements in the .net tools path setting. If you still hit this, I'd recommend finding where the tools get installed to globally and adding that to the path as we try to enable default environments to find tools by doing that on other OSes.

**Comment by lindexi** [comment]
Thank you @marcpopMSFT

**Comment by MyNine** [comment]
> Thank you @marcpopMSFT

how do you solve this problem, i have the same problem
请问你如何解决这个问题的

**Comment by marcpopMSFT** [comment]
Per above, we try to configure your path at install time of the SDK to include the tools path. On some OS configs and some install types, that is not done for you. When you install a global tool, an app host (.exe on windows and executable on not) gets created in a user folder. Add that to your path to get unblocked.
