### ISSUE TITLE
Improve perf of creating modified apphost

### ISSUE THREAD

**Issue by steveharter** [dotnet/sdk#1339]
When the modified apphost file is created for standalone apps, it first is a copy of the original apphost file and then the entire contents are replaced instead of just the specific section(s) necessary. This is inefficient; the file size is currently around 77K.

The code should be changed to use a stream approach and just replace the specific sections that actually change (only the hash values change).

This was prioritized due to changes in https://github.com/dotnet/sdk/pull/1338.

**Comment by nguerrera** [comment]
We also read the whole file in to a managed byte array, which shouldn't be necessary.
