### ISSUE TITLE
[5.0.100-rc.1.20453.7] Asp.net apps fail : Could not load file or assembly 'System.IO.Pipelines

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/sdk#13397]
**Application Name:** Asp.net Apps
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.1.20453.7
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1194104](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1194104)

**Repro steps:**
Launch asp.net applications with following steps by example:
1.  create a new blazor app
     dotnet new blazorserver
2. build the run the app

**Findings :**
When we install 5.0.100-rc.1.20453.7 SDK, 
System.IO.Pipelines.dll is located inside C:\Program Files\dotnet\sdk\5.0.100-rc.1.20453.7, and version is 3.1
See attachment : dllinfo.png
On previous SDKs, it was located at C:\Program Files\dotnet\shared, and version  was 5.0.
![image](https://user-images.githubusercontent.com/49379637/92245523-5acc1880-ee79-11ea-8ad5-00c6de0b27bf.png)

**Error :**

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
`

CC @dotnet-actwx-bot

**Comment by marcpopMSFT** [comment]
@dsplaisted can you take a quick look on impact as this is in the RC1 candidate.

**Comment by marcpopMSFT** [comment]
@jiangzeng01, this does not reproduce for me using the VS val insertion build (which is a slightly different version of the SDK). C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0-rc.1.20451.14.  Can you test with that SDK or that VAL build?

**Comment by csyszf** [comment]
Similar issue happened on SDK with version 6.0.100-alpha.1.20455.1:

By the first time I check the SDK folder:
the `System.IO.Pipelines.dll` is missing from both `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-alpha.1.20453.28\ref\net5.0` and `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-alpha.1.20453.28`

and the content of `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-alpha.1.20453.28\data\FrameworkList` has no element about `System.IO.Pipelines.dll`

**After I add the PackageReference of `System.IO.Pipelines` in my project implicitly, the application works without errors**

BTW I guess the easier way to find whether a SDK-Included dll is missing is go to VS and check Project -> Dependencies -> Frameworks -> Microsoft.NETCore.App -> System.IO.Pipelines

FYI @marcpopMSFT, this issue does not happened on 5.0.100-rc.1.20454.5

**Comment by jiangzeng01** [comment]
@marcpopMSFT This bug does not happened on 5.0.100-rc.1.20454.5 which is latest daily build, So close.
