### ISSUE TITLE
No way to add ref/lib split assets to deps files outside a nuget package

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1340]
I tried setting Reference (Private=false) and ReferenceCopyLocalPaths, same as what NuGet does, and noticed that the runtime assembly in ReferenceCopyLocalPaths was not added to the deps file.

I checked the inputs to GenerateDepsFile and there doesn't appear to be one for runtime-only dependencies.

/cc @eerhardt 

Here's the sample I was trying to make work:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Windows">
      <HintPath>C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Windows.winmd</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- reference these so that they are downloaded, but exclude all assets so that we can reference manually  -->
  <PropertyGroup>
    <UapRefPackage>Microsoft.Private.CoreFx.UAP</UapRefPackage>
    <UapLibPackage>runtime.win10-x64.Microsoft.Private.CoreFx.UAP</UapLibPackage>
    <PrivateUAPVersion>4.4.0-preview2-25405-01</PrivateUAPVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(UapRefPackage)" Version="$(PrivateUAPVersion)" ExcludeAssets="all" />
    <PackageReference Include="$(UapLibPackage)" Version="$(PrivateUAPVersion)" ExcludeAssets="all" />
    <!-- manually reference the WinRT assemblies -->
    <Reference Include="$(NuGetPackageRoot)$(UapRefPackage)\$(PrivateUAPVersion)\ref\uap10.1\System.Runtime.WindowsRuntime.dll" Private="false" />
    <ReferenceCopyLocalPaths Include="$(NuGetPackageRoot)$(UapLibPackage)\$(PrivateUAPVersion)\runtimes\win10-x64\lib\uap10.1\System.Runtime.WindowsRuntime.dll" />
  </ItemGroup>
</Project>
```
This is a bit of a hack, but I could imagine folks trying to do similar stuff.

**Comment by ericstj** [comment]
To try to workaround this I added a target after compile but before GenerateBuildDependencyFile to try to add the runtime assembly to ReferencePath and I got the error 
```
F:\cli\latest\sdk\2.1.0-preview1-006329\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(102,5): error MSB4018: System.ArgumentException: Can not add property System.Runtime.WindowsRuntime to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.\r [F:\winRtSample\DotnetCoreWinrt.csproj]
```
This is because my reference-only assembly was being passed in _ReferenceAssemblies.

In the end I worked around this as follows:
```
  <Target Name="AddWindowsRuntimeToDeps" BeforeTargets="GenerateBuildDependencyFile" >
    <!-- this is a hack to get our runtime assembly added to deps file
         https://github.com/dotnet/sdk/issues/1340 -->
    <ItemGroup>
      <ReferencePath Remove="@(ReferencePath)" Condition="'%(FileName)' == 'System.Runtime.WindowsRuntime'" />
      <_ReferenceAssemblies Remove="@(_ReferenceAssemblies)" Condition="'%(FileName)' == 'System.Runtime.WindowsRuntime'" />
      <ReferencePath Include="@(ReferenceCopyLocalPaths)"
                     Condition="'%(FileName)' == 'System.Runtime.WindowsRuntime'"
                     CopyLocal="True"
                     ReferenceSourceTarget="ResolveAssemblyReference" />
    </ItemGroup>
```

**Comment by davkean** [comment]
We talked about this at standup, basically you would get most features for free if you just produced the same FileDefinitions instead of references as the NuGet asset raising task. Which would also make the grouping under the right SDK node work correctly.

**Comment by ericstj** [comment]
That appears to make compile work, but not run.  GenerateDepsFile doesn't read the items to determine what to put in the deps file from packages, it just flows what NuGet put in there and "ExcludeAll" removed everything NuGet put in there.

Regardless, I'm not necessarily looking for a more elegant way to filter this NuGet package (although that is somewhat interesting).  I'm looking for how we'd enable someone outside of a package having a different ref vs lib asset and having that work with the deps file.

**Comment by rainersigwald** [comment]
This scenario might also play together with reference assemblies, which have a "compile-time" assembly distinct from the "run-time" assembly. I didn't closely inspect the deps file when doing testing while lighting that up.

cc @jcouv

**Comment by nguerrera** [comment]
> GenerateDepsFile doesn't read the items

This  should not be surprising.  The assets file items are not designed to be something you can mutate and expect everything in the system to respect your mutation. The items are actually a perf-hazard and build should move in the opposite direction of not using them as an intermediate representation of the assets file during build.

Regardless, any feature involving contributing things to compilation/deployment/configuration should be done without coupling to nuget/assets.json. Suppose I have the same requirement as ericstj, but my assets are not in any nupkg at all.

**Comment by ericstj** [comment]
Just a mechanical suggestion here, but designate some item as potentially contributing runtime libraries to the application.  That could be `ReferenceCopyLocalPaths`, `Content`, `None`, etc.  Whatever it be, look at that, potentially filter out all the stuff that might overlap with items from packages, and write it to the deps file.  Alternatively just get rid of the "must be in the deps file" requirement from the host and let the build copy it to the app and be loaded from the app directory.  /cc @gkhanna79

**Comment by gkhanna79** [comment]
> Suppose I have the same requirement as ericstj, but my assets are not in any nupkg at all.

You use AssemblyLoadContext to manage dynamic loads.

**Comment by ericstj** [comment]
This isn't anything dynamic and there is no reason to use AssemblyLoadContext.  It's known at build time that this is a runtime dependency of the application.  Is it a hard requirement that it show up in the deps file even if it doesn't have any other useful metadata to put there (package Id, version)?

**Comment by gkhanna79** [comment]
My response was for Nick's question.

For your scenario, where a reference is known to be at build time to be part of the app, my understanding was that there was a way to refer to such artifacts such that they would be part of app.deps.json. @eerhardt should chime on that aspect.

**Comment by nguerrera** [comment]
My question was rhetorical, to illustrate that the solution here should not require faking up standard nuget assets where there are none.

**Comment by eerhardt** [comment]
> my understanding was that there was a way to refer to such artifacts such that they would be part of app.deps.json. @eerhardt should chime on that aspect.

The current implementation only allows for referring to the artifact as both the ref and lib assembly.  We look at CopyLocal `@(ReferencePath)` that don't come from NuGet (See https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs#L49-L52).

Like @ericstj says, there isn't a way to split and say "this is the compile-time asset" and "this is the runtime asset".

Note - when fixing this, we need some way to wire these together. Is matching on the file name good enough?

**Comment by ericstj** [comment]
Any reason why they need to be correlated?  I think things would work fine if they had different IDs.

**Comment by ericstj** [comment]
It could also be interesting to expose runtime items that had runtimeTargets, which is a bit of an extension of this behavior.

**Comment by eerhardt** [comment]
> Any reason why they need to be correlated? I think things would work fine if they had different IDs.

At first I thought we had to, so they would be in the same library in the .deps.json file.  For example:

```JSON
      "Microsoft.AspNetCore.Authentication.Core/2.0.0-preview2-25327": {
        "dependencies": {
          "Microsoft.AspNetCore.Authentication.Abstractions": "2.0.0-preview2-25327",
          "Microsoft.AspNetCore.Http": "2.0.0-preview2-25327",
          "Microsoft.AspNetCore.Http.Extensions": "2.0.0-preview2-25327"
        },
        "runtime": {
          "lib/netstandard2.0/Microsoft.AspNetCore.Authentication.Core.dll": {}
        },
        "compile": {
          "lib/netstandard2.0/Microsoft.AspNetCore.Authentication.Core.dll": {}
        }
      },
```

But the DependencyModel actually acts a bit weird here.  The runtime and compilation libraries are separate in the DependencyContext object when in memory:  See https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L196-L197, but then it wires them together based on library name when writing to disk:
https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContextWriter.cs#L130-L136.

So I guess we won't need it, it will just happen if the runtime and compilation libraries are created with the same name.

**Comment by ericstj** [comment]
Yeah, so long as there is no collision on asset type it seems OK to merge.  I guess if there was a collision the same sort of collision would exist at compile/publish time.
