### ISSUE TITLE
NU related error in VS does not contain any framework information

### ISSUE THREAD

**Issue by mishra14** [dotnet/sdk#1341]
Consider the following project - 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.1;net461</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.1'">
    <PackageReference Include="newtonsoft.json" Version="10.0.0" NoWarn="NU1603" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net461'">
    <PackageReference Include="newtonsoft.json" Version="10.0.0" />
  </ItemGroup>
</Project>
```

On restore NuGet generates error for net461 related rids. BUt VS does not contain any information related to that - 

![capture](https://user-images.githubusercontent.com/10507120/27111108-bb6bb8f2-5062-11e7-8ee5-f657739a31ca.PNG)

NuGet generates the following error into the assets file - 

```
  "logs": [
    {
      "code": "NU1603",
      "level": "Error",
      "message": "CPSRefConsoleApp depends on Newtonsoft.Json (>= 10.0.0) but Newtonsoft.Json 10.0.0 was not found. An approximate best match of Newtonsoft.Json 10.0.1 was resolved.",
      "libraryId": "Newtonsoft.Json",
      "targetGraphs": [
        ".NETFramework,Version=v4.6.1",
        ".NETFramework,Version=v4.6.1/win7-x86"
      ]
    }
  ]
```

@natidea : what is the expectation here? Did we miss something?

**Comment by mishra14** [comment]
cc: @natidea @emgarten

**Comment by natidea** [comment]
The target framework is reflected in VS by putting a warning in the solution explorer.

![image](https://user-images.githubusercontent.com/7732033/27147395-7cffbb7e-50f1-11e7-915f-8275b545adde.png)

In this case, there should be a warning under the .NET Framework node, but not under the .NETCoreApp node. (However I don't think I have the version of NuGet with `nowarn` implemented). Do you see this filtering happening in the solution explorer?

**Comment by natidea** [comment]
I've upgraded to a version of NuGet with NoWarn and now I see the warning under the net461 node, but not under the netcoreapp node.

![image](https://user-images.githubusercontent.com/7732033/27300124-727ef21e-54e3-11e7-8bd2-4b50b89f7a99.png)
