### ISSUE TITLE
Generate TargetPlatformAttribute, and use TargetPlatformMinVersion for SupportedOSPlatformAttribute

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#13453]
We should update how we are generating the assembly-level platform attributes:

- We should generate a `TargetPlatformAttribute` with a value of `$(TargetPlatformIdentifier)$(TargetPlatformVersion)`
- The `SupportedOSPlatformAttribute` should use the `TargetPlatformMinVersion` value, ie `$(TargetPlatformIdentifier)$(TargetPlatformMinVersion)`
  - Currently this goes through the `SupportedOSPlatform` property (which defaults to `TargetPlatformVersion`, which is incorrect).  However, we should probably just remove this property, to avoid confusion with `SupportedPlatform`.

@wli3 @terrajobst

**Comment by wli3** [comment]
I renamed the property TargetPlatformVersion to SupportedOSPlatform while the attribute name is changed. I don't know Windows used TargetPlatformVersion for a while. Then the rename to SupportedOSPlatformAttribute is weird.

@mhutch is it ok to have the attribute mismatch the msbuild property?

@dsplaisted could you drive the discussion and the code change? The test infra and the code are mostly there. It should be trivial to tweak it once we get a conclusion.

**Comment by wli3** [comment]
The [spec](https://github.com/dotnet/designs/blob/master/accepted/2020/minimum-os-version/minimum-os-version.md) is very out of date  and it does not mention `TargetPlatformAttribute`. @mhutch please update it

**Comment by dsplaisted** [comment]
Update: Use `SupportedOSPlatformVersion` property.  Default value (on Windows) should be `TargetPlatformAttribute`
