### ISSUE TITLE
Pinned SDK version below 1.0.4 seems broken in 15.3

### ISSUE THREAD

**Issue by srivatsn** [dotnet/sdk#1348]
_From @onovotny on June 15, 2017 15:40_

Here's the scenario: 

Web project that has a global.json with a pinned SDK version. 

Executing an msbuild /pp yields some interesting results for where the SDK's are imported:

If the SDK version is 1.0.0-1.0.3 is:
The import of the Web SDK is from: 
`C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props`

But then the .NET Sdk is from: 
`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props`

If the SDK version is 1.0.4, both SDK's come from the `C:\Program Files\dotnet\sdk\1.0.4\Sdks\` directory.

Seems like if `1.0.4` is the min version of the SDK that will work correctly with 15.3, then if VS sees an older pinned version, it should use the upgrade wizard functionality to bump the min SDK version to 1.0.4 so things don't act strangely for users unexpectedly.

_Copied from original issue: dotnet/project-system#2450_

**Comment by srivatsn** [comment]
Tagging @nguerrera @livarcocc

**Comment by srivatsn** [comment]
Since the 1.0.0 web SDK imports the Web.ProjectSystem.SDK using MSBuildSdksPath and that's not in VS anymore, web projects are fairly broken.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/cli#6887

**Comment by nguerrera** [comment]
This is one of the aspects of https://github.com/dotnet/cli/issues/6585 that was postponed.

Specifically, this part of the proposal:

> Add a manifest file next to the resolver that indicates a global minimum sdk version to the resolver and use the greater version of the global minimum and the import-specific minimum. (See #6555.)

A cheap fix for 15.3 would be to have an implicit global minimum of 1.0.4 always. There is no version < 1.0.4 that can be resolved safely from anything that would ever use the resolver, and that cannot change without a time machine. Mind you, actually declaring 1.0.4 in a manifest file and using it is not all that expensive, so we should probably just do it.
