### ISSUE TITLE
SupportedOSPlatform assembly attributes are not getting generated for version less platform name

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/sdk#13494]
### SupportedOSPlatform assembly attributes are not getting generated for version less platform name

In https://github.com/dotnet/runtime/issues/39989#issuecomment-665197220 we decided to rename MinimumOSPlatformAttribute into RemovedInOSPlatformAttribute and support version less platform name.  We had renamed the attribute with https://github.com/dotnet/sdk/pull/12775 but the version less attribute name support is missing

 ```xml
<PropertyGroup>
   <TargetFramework>net5.0-windows</TargetFramework>
</PropertyGroup>
```
Only works when adding a valid version
```xml
<PropertyGroup>
   <TargetFramework>net5.0-windows7.0</TargetFramework>
</PropertyGroup>
```
CC @adamsitnik @jeffhandley @terrajobst @wli3

**Comment by terrajobst** [comment]
@marcpopMSFT the fix needs to go into RC2. Can we prioritize this?

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/sdk/pull/13507
