### ISSUE TITLE
Disabling "IntelliCode suggestions based on recent edits"

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/sdk#13509]
Those suggestions are really annoying and so far completely irrelevant. I tried disabling them in 

    Tools|Options|Intellicode|General|Suggestions|C#=Disabled

They no longer show in the code, but remain in the error list as messages. However, there is absolutely no way to ignore and remove them from the messages list! It was normally done using the lightbulb that no longer shows. I can hide the messages, but it will pollute that list indefinitely, which isn't an interesting option.

Any better way?

**Comment by mysteryx93** [comment]
Ah. Rebooting Visual Studio clears the list.

So this is just a minor bug. Disabling suggestions should clear the messages.

**Comment by markw-t** [comment]
Sorry you found the suggestions not useful. I wanted to add:

1. As you've discovered you can globally disable them
2. If a particular suggesiton is not useful you can turn it off using the "ignore suggestions like this" menu option (see the [docs](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-suggestions) for a screenshot showing this)
3. We're making some improvements in the next release that will remove a number of false positives with better filtering of items that might cause issues. I'd love to figure out if we have caught the bad suggestions that you have. If you see bad suggestions please report them using [VS report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) so we can check.

Thanks!

**Comment by sfoslund** [comment]
It sounds like this issue have been resolved, please feel free to reopen if you have further questions. Thanks!
