### ISSUE TITLE
Preprocessor symbol 'NET' should be automatically defined when building for .NET 5 or higher

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#13511]
Relevant portion from [the spec](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#preprocessor-symbols):

* We continue to define `NETCOREAPP` for backwards compatibility with existing `#if` code.
* Moving forward we'll use `NET` as the versionless symbol (for .NET Framework we used `NETFRAMEWORK`, so no conflict there).
* We'll follow the rule-based creation in SDK-style projects which takes the friendly TFM name without the OS flavor, makes it upper-case and replaces special characters with an underscore.
* For OS flavors we'll do the same, i.e. create versionless as well as version specific symbols.

**Comment by sfoslund** [comment]
@terrajobst is there a repro for a scenario where you're not seeing these symbols produced? They should have been added with https://github.com/dotnet/sdk/pull/11635 and https://github.com/dotnet/sdk/pull/12124.

**Comment by marcpopMSFT** [comment]
That's on me as I swear I tested it and it didn't work but I tried it again now and see NET is defined so I think this can be closed.

**Comment by marcpopMSFT** [comment]
BTW, confirmed working in RC1

**Comment by sfoslund** [comment]
Closing per Marc's comment

**Comment by Maxyeah** [comment]
What about the "OS flavored" preprocessors like NET6_0_WINDOWS. I don´t get these to work. When will these implemented?
