### ISSUE TITLE
Managing versions of Package and DotNetCliTool references with external tools

### ISSUE THREAD

**Issue by alfonsogarciacaro** [dotnet/sdk#1354]
Related: https://github.com/fsprojects/Paket/issues/2343

This is a follow-up of a conversation we had today with @dsplaisted about an issue with [Fable Compiler](https://github.com/fable-compiler/Fable), an F# to JS compiler. Fable is now distributed as a DotNetCliTool (`dotnet-fable`) so it can be invoked by users through the command line. However, there's also a `Fable.Core` package which is referenced by users normally as other Nuget dependencies. The versions of these two packages must be in sync, because changes in Fable.Core affect the dotnet-fable compiler CLI tool and vice versa. Fable projects use [Paket](https://github.com/fsprojects/Paket) to manage Nuget dependencies, but Paket cannot handle yet DotNetCliToolReferences (see issue linked above) so we don't have a way to make sure dotnet-fable is the same version as Fable.Core unless we manually pin the versions both in paket.dependencies and the .fsproj file.

@dsplaisted suggested to use an MSBuild property to specify the dotnet-fable version like:

```xml
<DotNetCliToolReference Include="dotnet-fable" Version="$(FableVersion)" />
```

This way we could put a `<PROJECT_NAME>.fsproj.fableversion.props` file in the `obj` folder with something like:

```xml
<Project>
  <PropertyGroup>
    <FableVersion>1.1.0</FableVersion>
  </PropertyGroup>
</Project>
```

The problem is the `obj` folder is not created until `dotnet restore` is run so we have a chicken-and-egg situation here. @dsplaisted mentioned about an intermediate folder with a similar convention that dotnet SDK will also use from now on to import properties. Is this the way to go? How exactly can this folder be used?

Thanks a lot for your help in advance!

cc @forki @enricosada

**Comment by enricosada** [comment]
@alfonsogarciacaro dont use `obj`.
use a `Directory.Build.props` file at root level. is automatically imported (lib `obj`) , ref https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0

**Comment by forki** [comment]
If I understand correctly the problem would also go away if paket could add DotNetCliToolReference programmatically at dotnet restore time, right? Then we could manage DotNetCliToolReference exactly like PackageReferences via Paket.dependencies

**Comment by livarcocc** [comment]
Directory.Build.props should solve the problem.

The idea of keeping the tool and the package reference in sync or maybe using a single one to indicate both has come up before but is not in the plans for a particular release yet.

As such, I am going to close this issue.
