### ISSUE TITLE
Building with Output type "Exe" puts AutoMagically Generated files after the existing files list.   Building with Output type "Library" puts them before

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/sdk#1355]
When Building an F# library the sdk adds automagically generated files before the specified source files when building as Exe.  And after when building as "Library.

Note the order of Program.fs and .NETCoreApp,Version=v2.0.AssemblyAttributes.fs.

OutputType  = Library
````
         --target:library
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         Program.fs
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
````

OutputType  = Exe
````
         --target:exe
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
         Program.fs
````

**Comment by dsplaisted** [comment]
That is weird, but does it have any affect?

Sent from my Windows 10 phone

From: Kevin Ransom (msft)
Sent: Sunday, June 18, 2017 12:09 AM
To: dotnet/sdk
Cc: Subscribed
Subject: [dotnet/sdk] Building with Output type "Exe" puts AutoMagicallyGenerated files before the existing files list. Building with Output type"Library" puts them after (#1355)

When Building an F# library the sdk adds automagically generated files before the specified source files when building as Exe. And after when building as "Library.
Note the order of Program.fs and .NETCoreApp,Version=v2.0.AssemblyAttributes.fs.
OutputType = Library
         --target:library
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         Program.fs
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
OutputType = Exe
         --target:exe
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
         Program.fs

**Comment by livarcocc** [comment]
@dsplaisted is this us or is this globbing in MSBuild?

**Comment by dsplaisted** [comment]
It turns out that this is the FSharp targets: https://github.com/fsharp/fsharp/blob/fb2f8aa2a7c01d00f703d1ab050bbf3a852f02a9/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L395-L396

```xml
<ItemGroup>
    <CompileBefore Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND ('$(OutputType)' == 'Exe' OR '$(OutputType)' == 'WinExe')"/>
    <CompileAfter Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND '$(OutputType)' != 'Exe' AND '$(OutputType)' != 'WinExe'"/>
</ItemGroup>
```

@KevinRansom

**Comment by dsplaisted** [comment]
This issue was moved to fsharp/fsharp#813

**Comment by KevinRansom** [comment]
This was fixed in our targets many moons ago.  Nothing to see here :-)
