### ISSUE TITLE
Generated AssemblyInfo files don't have an autogenerated header

### ISSUE THREAD

**Issue by bencyoung** [dotnet/sdk#1356]
I'm using StyleCop.Analyzers and it's pulling in the generated AssemblyInfo file and then complaining that it doesn't have the right header...

obj\Debug\netstandard2.0\....ProjectTemplate.AssemblyInfo.cs(1,1): error SA1636: The file header copyright text must match the copyright text from the settings. [F:\...\Template\....ProjectTemplate.csproj]

**Comment by bencyoung** [comment]
The problem seems to be intermittent. It happens in Code and on the command line but somehow not in VS

**Comment by dasMulli** [comment]
This is already filed at https://github.com/Microsoft/msbuild/issues/1925 and a PR already exists (https://github.com/Microsoft/msbuild/pull/2207)

**Comment by bencyoung** [comment]
Thanks!
