### ISSUE TITLE
dotnet test will hang on Windows if RedirectStandardOutput is set to true

### ISSUE THREAD

**Issue by huiren-jiang** [dotnet/sdk#13569]
As tested on Windows, if I launch the `dotnet test` command by C# `Process` and set `RedirectStandardOutput` to true, the dotnet process will start but never end. Monitoring the event `OutputDataReceived` will also get no output. If I set `RedirectStandardOutput` to false, everything works as expected.

Also, the same issue could not be reproduced if I run on Linux.

Should this be an issue, or I miss anything?

**Comment by marcpopMSFT** [comment]
@dotnet/dotnet-test-templates-admin for triage

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/vstest#2572
