### ISSUE TITLE
Dotnet test fails in docker ENTRYPOINT when using ARG Configuration=Release.

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/sdk#13568]
Hear me out...

`dotnet new xunit`

## Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS sdk
ARG Configuration=Release
WORKDIR /tests
COPY . .
RUN dotnet restore
RUN dotnet build --no-restore
ENTRYPOINT ["dotnet", "test", "--no-build"]
```

- `docker build --tag docker-dotnet-test-arg .`
- `docker run -it --rm docker-dotnet-test-arg`

## ERROR:

```
❯ docker run -it --rm docker-dotnet-test-arg:latest
Test run for /tests/bin/Debug/netcoreapp3.1/DockerDotnetTest2.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The argument /tests/bin/Debug/netcoreapp3.1/DockerDotnetTest2.dll is invalid. Please use the /help option to check the list of valid arguments.
/usr/share/dotnet/sdk/3.1.402/Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [/tests/DockerDotnetTest2.csproj]
```

Now comment out `ARG Configuration=Release`, build and run the container again. I spent all day doing guess, test and retry to figure this out. I would love some help as to why this happens and how I can fix it.

Note: You can see in the above Dockerfile snippet I am not using the ARG just to simplify the example, but you would commonly use it like so: `RUN dotnet build --configuration $Configuration --no-restore`

**Comment by marcpopMSFT** [comment]
@dotnet/dotnet-test-templates-admin for triage

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/vstest#2573
