### ISSUE TITLE
VB Target #Constants don't work as Expexcted

### ISSUE THREAD

**Issue by paul1956** [dotnet/sdk#13567]
Currently #If NET5_0 also means \#NETCOREAPP3_1. In the example below only want VBMsgBox when it's Core 3.1, not Framework or NET5_0 but it doesn't work that way. Below is TRUE for NET5_0.
```
#If NETCOREAPP3_1 Then
Imports VBMsgBox
#End If
```

```
#If Not NET5_0 Then
'  4.x code would be here but how to I get the case above
#Else
   .
   'Here goes the .NET5-only code, about about .NET 6.0?
   .
```

**Comment by dsplaisted** [comment]
I think this is the same issue we're discussing in #13377.  I don't think it's VB-specific.

I think this is the way you would write this:

```
#If Not NET5_0 Then
'  . NET Core 3.x code
#Else
   .
   ' Code for .NET 5 and higher goes here
   .
```

Generally the code for .NET 5 should also work on higher versions.  If .NET 6 comes out and you want different code for it, then you would do something like this (I'm not sure of the exact VB syntax here):

```
#If Not NET5_0 Then
'  . NET Core 3.x code
#Else If Not NET6_0 Then
` Code for .NET 5 goes here
#Else
   .
   ' Code for .NET 6 and higher goes here
   .
```

You could also reverse the ordering if you prefer:

```
#If NET6_0 Then
   .
   ' Code for .NET 6 and higher goes here
   .
#Else If NET5_0 Then
    ` Code for .NET 5 goes here
#Else If NETCOREAPP
'  . NET Core 3.x code would be here
```

**Comment by paul1956** [comment]
Your example leaves out Framework 4.x. VB Framework 4.x and Core 5 and later have VB runtime support 3.X lacks. and there are other difference in Application Model. But 3.x later have a more complete Core Runtime for example additional features like Tuple GetHashCode and functionality on String Contains and Replace for StringComparison. 4.x is sometimes a superset of Core and sometimes not wrt 3.x. I do think your logic may help but the logic will be ugly.

**Comment by marcpopMSFT** [comment]
@paul1956 Per #13377 we're going to revert that change and targeting 5.0 will no longer define NETCOREAPP3_1.  Will that solve your issue and I can close this?  This will go out in RC2.

**Comment by paul1956** [comment]
@marcpopMSFT Yes that solves my issue for 3.1/5.0 and works the way people expect.
