### ISSUE TITLE
net core sdk needs to surface warnings and errors from assets file for legacy package reference projects

### ISSUE THREAD

**Issue by mishra14** [dotnet/sdk#1357]
Related cps/package ref work: https://github.com/dotnet/sdk/pull/1228

We should have feature parity for legacy package reference as well.

Also, if this is the right place for it: we should trigger a design time build for legacy package ref as well.

cc: @natidea @srivatsn

**Comment by srivatsn** [comment]
The build task for legacy projects lives here - https://github.com/NuGet/NuGet.BuildTasks. I think the way we probably want to handle this is to move projects using packagereference to the new build task. Moving this issue to the project system repo.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2465
