### ISSUE TITLE
.NET 5.0 RC1 - "dotnet build" succeeds to build but "dotnet test" fails to build the same exact SLN

### ISSUE THREAD

**Issue by pedramrezaei** [dotnet/sdk#13584]
Repro:

1- Clone this repo: https://github.com/cloudtoid/interprocess
2- Run `dotnet build src/Interprocess.sln` and it succeeds.
3- Run `dotnet test src/Interprocess.sln` and it fails to build.

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2570
