### ISSUE TITLE
error CS2012: Cannot open '<filename>' for writing, because used by another process

### ISSUE THREAD

**Issue by attilah** [dotnet/sdk#1359]
Our Orleans.PlatformServices.dll is a multi targeted project and we're building it for Orleans.csproj as bootstrapping the code generator. We had a similar issue with 1.x tooling, but then it was working. We moved to .Net Core 2 Preview 1 tooling and the error surfaced again.

It seems very similar to: https://github.com/dotnet/sdk/issues/739

Failed builds on CI can be found here: https://ci.dot.net/job/dotnet_orleans/job/master/job/netstandard-win-bvt_prtest/384/

We call the bootstrapping MSBuild here: https://github.com/dotnet/orleans/blob/master/vNext/src/Orleans/Orleans.csproj#L82

This is the proj file begin called: https://github.com/dotnet/orleans/blob/master/vNext/src/ClientGenerator/BootstrapCodegen.proj

**Comment by nguerrera** [comment]
@attilah Those links are no longer available. Does this repro for you locally? Can you provide the full repro steps? Failing that, can you enable the /bl argument (see msbuildlog.com) and send us the resulting .binlog for a failed build?

**Comment by nguerrera** [comment]
@attilah  Do your errors always involve writing to an intermediate xml file. If so, use GenerateDocumentationFile=true instead of DocumentationFile=obj\MyProjectName.xml. Otherwise, multi-targeted builds will write to the same location for different TargetFrameworks in parallel.

**Comment by nguerrera** [comment]
See #1599

**Comment by livarcocc** [comment]
Closing as we haven't had activity here and need better repro steps.
