### ISSUE TITLE
Add Support for non-Windows TargetPlatformIdentifiers

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#13593]
Currently we throw an error not supported error while using non-windows TargetPlatformIdentifiers. The only string we can use is Windows

is there a plan to support others in 5.0 ?

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L111

cc @ericstj

**Comment by ericstj** [comment]
It looks like we could set ‘TargetPlatformSupported’ ourselves off we define the behavior for it.

**Comment by wli3** [comment]
Yes. We will support more like ios in 6.0
@dsplaisted double check. We expect people to set TargetPlatformSupported to true in workload SDKs right?

**Comment by dsplaisted** [comment]
> Yes. We will support more like ios in 6.0
> @dsplaisted double check. We expect people to set TargetPlatformSupported to true in workload SDKs right?

Yes, correct.
