### ISSUE TITLE
Restore failing for projects with tfms netcoreapp3.0;netcoreapp3.0-Windows

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#13592]
```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;netcoreapp3.1-Windows</TargetFrameworks>
  </PropertyGroup>
</Project>
```
fails during restore while
```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net5.0-Windows</TargetFrameworks>
  </PropertyGroup>
</Project>
```
builds fine 

The error in the first case 
```
Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\NuGet.targets(130,5): error : Invalid restore input. Duplicate frameworks found: 'netcoreapp3.1, netcoreapp3.1'. Input files: C:\git\scratch\rc2\rc2.csproj. [C:\git\scratch\rc2\rc2.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.68
```

is this by design ?

cc @ericstj

**Comment by ericstj** [comment]
Interesting.  Not sure. I would have expected a more friendly error message, or NuGet to tolerate duplicate entries that use the same nuget assets.  @dsplaisted @nkolev92

**Comment by nkolev92** [comment]
NuGet can't tolerate duplicates at this point.
It's really the only leftover for the aliases work: https://github.com/NuGet/Home/issues/5154. 

Note that this behavior has been the same for the existence of PackageReference.

**Comment by ViktorHofer** [comment]
Even though `netcoreapp3.1-Windows` is a valid target framework, I believe NuGet handles this case differently (as it assumes the suffix is the `TargetFrameworkProfile` part) and restores differently. I discussed this with @jeffkl back when we enabled static graph restore in dotnet/runtime. That's the reason why we are still stripping the suffix during restore.

**Comment by nkolev92** [comment]
> Even though netcoreapp3.1-Windows is a valid target framework, I believe NuGet handles this case differently (as it assumes the suffix is the TargetFrameworkProfile part) and restores differently.

That was the whole TargetFramework as alias problem. NuGet and the SDK both were parsing the TargetFramework element but it wasn't supposed to be. 
To enable .NET 5 TFMs, NuGet & SDK switched to combining `TargetFrameworkMoniker` & `TargetPlatformMoniker` to infer the true pivot framework.

Now to preserve the consistent behavior for customers (ie simple project files), the TargetFramework property is parsed if `TargetPlatformMoniker` and `TargetFrameworkMoniker` are not set. That's being done in the SDK.
As far as NuGet & SDK go, there's no such thing as a platform specific .NETCoreApp 3.x, so the SDK ends up generating the same TargetFrameworkMoniker + TargetPlatformMoniker.

**Comment by ViktorHofer** [comment]
Thanks @nkolev92, that's very valuable information.

**Comment by wli3** [comment]
Looks like we don't need to take any action. Closing

**Comment by ericstj** [comment]
Actually NuGet didn’t treat it as a profile.   Either NuGet or SDK treated as if the suffix didn’t exist and NuGet failed with this duplicate error. Is that really the behavior we want when folks get this wrong?  Maybe SDK should tell folks the windows suffix isn’t understood on netcoreapp3.1 same as it would if you used an unknown suffix?

**Comment by dsplaisted** [comment]
It looks like what's going on is that NuGet interprets the `-windows` in `netcoreapp3.1-windows` as the profile.  However, the SDK doesn't support targeting profiles, so it doesn't ever parse that out into the `TargetFrameworkProfile` property.  So `netcoreapp3.1-windows` ends up parsing into the same thing as `netcoreapp3.1`.

**Comment by wli3** [comment]
Let me know if we need to have a better error message (if it is possible at all). Then reopen the issue
