### ISSUE TITLE
Consider automatic package restore prior to build (if needed)

### ISSUE THREAD

**Issue by michaldudak** [dotnet/sdk#1361]
Currently building an application using SDK is a two-step process. You have to restore packages, then run `dotnet build`. It happened to me at least few times that the packages were not restored prior to build, what resulted in all kinds of confusing build errors (such as "Unexpected dependency 'Microsoft.NETCore.App' with no version number.").

Could you consider changing `dotnet build` to detect if packages are missing and restore them if necessary? Alternatively, perhaps create another command that would restore and build?

**Comment by dsplaisted** [comment]
This will be part of the 2.0 tools.  See https://github.com/dotnet/cli/issues/6105.

Thanks!
