### ISSUE TITLE
Warning on cross-targeting WPF app using Microsoft.NET.Sdk.WindowsDesktop

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#13618]
Create a netcoreapp3.1 WPF application.  Make it also target net5.0.
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
```

Expect: build clean

Actual: warning:
```
warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Microsoft.NET.Sdk can be used instead.
```

This warning only applies to net5.0, changing the SDK will cause this project to fail to build on netcoreapp3.1.  Introduced in https://github.com/dotnet/sdk/pull/12386 cc @sfoslund @dsplaisted

**Comment by dsplaisted** [comment]
This is fixed by #13441 (which also lets you use Microsoft.NET.Sdk for .NET Core 3.x WPF projects)
