### ISSUE TITLE
Restore infers a `Windows7.0` platform when `UseWpf` is true

### ISSUE THREAD

**Issue by zkat** [dotnet/sdk#13614]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): msbuild.exe

MSBuild version: 16.8.0-preview-20452-03+5dee11854

dotnet.exe --version (if appropriate): 5.0.100-rc.1.20454.5

OS version (i.e. win10 v1607 (14393.321)): win10

## Detailed repro steps so we can see the same problem

1. `dotnet new wpflib`

2. Edit the csproj to change `TargetFramework` to `TargetFrameworks` and add `net5.0` to the list alongside `net5.0-windows`

3. msbuild /restore

### Expected

Restore succeeds as normal.

### Actual

![image](https://user-images.githubusercontent.com/17535/93246855-3c500200-f742-11ea-86c8-30b85dce0562.png)

/cc @dsplaisted @sfoslund

**Comment by dsplaisted** [comment]
I think this will be fixed in RC2, in the sense that restore will succeed but you'll get an error from the `net5.0` inner build that says you need to add `-windows`.

**Comment by wli3** [comment]
@dsplaisted which commit fixed it? We just need to verify that?

**Comment by dsplaisted** [comment]
It's the "removing target platform workaround" part of #13168

**Comment by wli3** [comment]
The error is "The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so." now, which is expected. Closing
