### ISSUE TITLE
publish --manifest doesn't work for self-contained apps

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1362]
We are unable to use the runtime store feature for self-contained apps.

### Repro steps

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
  </ItemGroup>
</Project>
```

`dotnet publish --manifest SomeManifestFile.xml`
execute the published app

#### Expected results

This should either:

1. Execute the app correctly
2. Provide me with an error message on what I did wrong

#### Actual results

Publish succeeds, but running the app fails with:

```
An assembly specified in the application dependencies manifest (NewtonSoftDependentProject.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '9.0.1'
    path: 'lib/netstandard1.0/Newtonsoft.Json.dll'

  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    artifact.xml
```
### Analysis

The host will only resolve assemblies from the runtime store if the runtimeconfig.json `tfm` property is set correctly.  See https://github.com/dotnet/core-setup/blob/cf17c248207bf7994e2de2b806d591f6ca55eb12/src/corehost/cli/args.cpp#L33-L37.

But, the runtimeconfig.json `tfm` property is only written for "FrameworkDependent" apps, see https://github.com/dotnet/sdk/blob/09c2a6bd8e2c0ec1524361d3a560a1ef961e4367/src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs#L102.

We should decide whether this scenario is supposed to be supported or not.  On one hand, having a `self-contained` app that is dependent on an external runtime store seems wrong.  On the other hand, if things are set up correctly there is no reason why it wouldn't work - so why limit users?

After speaking with @gkhanna79, we decided that by definition a "self-contained" app should have everything it needs.  So we think this case should be an error.

@steveharter
/cc @livarcocc @nguerrera

**Comment by nguerrera** [comment]
We are only making minimal investements in dotnet store.
