### ISSUE TITLE
SDK does not consider projects targeting net472 to be using windows

### ISSUE THREAD

**Issue by jmarolf** [dotnet/sdk#13623]
SDK used: `5.0.100-rc.2.20465.5`

Consider this project: [Roslyn.Services.Test.Utilities.csproj](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/TestUtilities/Roslyn.Services.Test.Utilities.csproj)

- uses `"Microsoft.NET.Sdk.WindowsDesktop"`
- targets `net472`
- sets `<UseWpf>true</UseWpf>`

Based on these conditions here:
https://github.com/dotnet/sdk/blob/d9ca8cdceabd2a1edf644e2fc94c4b343b081dd8/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L366-L371

The following error will always be produced:

```
Error	NETSDK1136	The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.
```

**Comment by marcpopMSFT** [comment]
@sfoslund Can you take a look? It doesn't repro for me on a simple WPF I created in the CLI.  Not sure if I'm missing some part of the repro.

**Comment by sfoslund** [comment]
I'm not able to repro with a simple project targeting net472 or the repro project you linked to (using the latest build, 5.0.100-rc.2.20471.7). If you can provide a repro please reopen, otherwise I'm going to close this, thanks!
