### ISSUE TITLE
Will CLI support .NET MAUI projects that target Linux?

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/sdk#13644]
Will we able to create and build .NET MAUI projects that target Linux with CLI?

**Comment by marcpopMSFT** [comment]
You can find more information on MAUI in the MAUI repo.  Please check out the [FAQ](https://github.com/dotnet/maui/wiki/FAQs) and if you have questions, ask them [here](https://github.com/dotnet/maui/discussions).  There are a few threads on the Linux topic already.  Thanks.
