### ISSUE TITLE
Unable to satisfy conflicting requests (recursive problem ? )

### ISSUE THREAD

**Issue by philippe-lavoie** [dotnet/sdk#1365]
With the latest VS2017 update 3 preview code (installed on July 20th) I'm seeing this when doing a dotnet restore  (I'm seeing other stuff when doing nuget restore)

      Unable to satisfy conflicting requests for 'System.Runtime.Handles': System.Runtime.Handles (>= 4.3.0) (via package/System.Diagnostics.Process 4.3.0), System.Runtime.Handles (>=
 4.0.1) (via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.
FileSystem 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.Compression 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem 4.3.0), System.Runt
ime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Security.Cryptography.Algorithms 4.3.0), System.Runtim
e.Handles (>= 4.3.0) (via package/System.Security.Cryptography.Encoding 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Security.Cryptography.X509Certificates 4.3.0), Sy
stem.Runtime.Handles (>= 4.3.0) (via package/System.Text.Encoding.CodePages 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.Compression 4.3.0), System.Runtime.Handles
 (>= 4.3.0) (via package/System.IO.FileSystem 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via pack
age/System.Security.Cryptography.Algorithms 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Security.Cryptography.Encoding 4.3.0), System.Runtime.Handles (>= 4.3.0) (via
 package/System.Security.Cryptography.X509Certificates 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Text.Encoding.CodePages 4.3.0), System.Runtime.Handles (>= 4.0.1)
(via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.Security.Principal.Windows 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/Syste
m.Threading.ThreadPool 4.3.0), System.Runtime.Handles (>= 4.0.1) (via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>= 4.0.1) (via package/System.Net.NameResolution 4.0
.0), System.Runtime.Handles (>= 4.0.1) (via package/System.Net.Security 4.0.0), System.Runtime.Handles (>= 4.0.1) (via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>=
4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem.Watcher 4.3.0), System.Runtime.Handles (>= 4.3.0) (via p
ackage/Microsoft.Win32.Registry 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Security.Principal.Windows 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.
IO.FileSystem 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem.Watcher 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem 4.3.0), S
ystem.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem.Watcher 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.IO.FileSystem.Watcher 4.3.0), System.Runtime.H
andles (>= 4.0.1) (via package/System.Net.Primitives 4.0.11), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.0.1) (
via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.0.1) (via package/System.IO
.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.0.1) (via package/System.IO.FileSystem 4.0.1), S
ystem.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runti
me.Handles (>= 4.0.1) (via package/System.IO.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0)
 (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via packa
ge/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.0.1) (via package/System.I
O.FileSystem 4.0.1), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropService
s 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), S
ystem.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runti
me.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles
(>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0)
(via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via packag
e/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Ru
ntime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.Inter
opServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices
4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), Sys
tem.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime
.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>
= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (v
ia package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/
System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runt
ime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.Interop
Services 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.
3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), Syste
m.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.H
andles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>=
4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via
 package/System.Runtime.InteropServices 4.3.0), System.Runtime.Handles (>= 4.3.0) (via package/System.Runtime.InteropServices 4.3.0)

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5467
