### ISSUE TITLE
How to determine that given `.dll` was build for an OS-specific TFM?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/sdk#13668]
Hello everyone!

To tell the long story short, to make OS-specific monikers like `net5.0-windows` work with BenchmarkDotnet I need to detect (preferably using reflection) that given `.dll` is using an OS-specific moniker. (more details https://github.com/dotnet/BenchmarkDotNet/issues/1535)

Is it somehow possible?

Repro:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>
</Project>
```

ILSpy gives me:

![obraz](https://user-images.githubusercontent.com/6011991/93449270-d647b400-f8d4-11ea-9321-5a1291917c15.png)

No information indicates that it's windows-specific.

cc @wli3 @buyaa-n

**Comment by buyaa-n** [comment]
Sounds like you can use `SupportedOSPlatformAttribute` injected from MSBuild, but as you know it will be having platform name concatenated with version. Also, there was a bug that version less TFM like `net5.0-windows` was not injecting the attribute, which is fixed recently, [see how version mappings work](https://github.com/dotnet/sdk/pull/13507#issuecomment-692405455) with the fix

But there might any other attribute better suit for your need cc @sfoslund

**Comment by sfoslund** [comment]
@dsplaisted is currently adding a TargetPlatform attribute in this PR:https://github.com/dotnet/sdk/pull/13672. This is probably what you'll want to use.

**Comment by adamsitnik** [comment]
@buyaa-n @sfoslund thank you both for your input! I am going to close this issue and wait until #13672 gets into SDK
