### ISSUE TITLE
XAML build targets produce randomly named empty directories

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#1367]
The temporary project XAML creates has the OutDir set to a random directory name. Microsoft.Common.CurrentVersion.targets creates a directory doe such OutDir, which pollutes the output.

```xml
<MakeDir Directories="$(OutDir);$(IntermediateOutputPath);@(DocFileItem->'%(RelativeDir)');@(CreateDirectory)" ContinueOnError="True"/>
```

A workaround is to clear the OutDir in a custom .targets file:

```xml
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.tmp_proj'">
    <OutDir/>
  </PropertyGroup>
```

**Comment by tannergooding** [comment]
I still think we need to log an internal bug against the XAML targets here, as they are not part of the SDK and are what is causing the issue.

**Comment by nguerrera** [comment]
Or at least on msbuild where the target that actually creates OutDir live? Why would we want to fix this only for SDK-based projects?
