### ISSUE TITLE
[loc][query] assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#13680]
Filename | Cli\dotnet\commands\dotnet-test\xlf\LocalizableStrings.xlf
-- | --
Question | We left 'NAME="VALUE"' in Eng because it is Cmd variable according to resource id.Please check if it's OK.

**Comment by wli3** [comment]
@nohwnd could you see if this is ok? Files under dotnet-test belong to your team

**Comment by nohwnd** [comment]
Yes it is okay. Thanks.
