### ISSUE TITLE
VS2017 Update breaks my dotnet CLI tool: The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#1370]
_From @AArnott on June 26, 2017 5:18_

I haven't changed my dotnet CLI tool project in a significant way, but it stopped working on old machines when built with newer builds of VS 2017.

A build made a while back on [this commit](https://github.com/AArnott/CodeGeneration.Roslyn/commit/fce1c8ba1eff248ad34329fee843ecf19b423b37) works. But recently I build [this commit](https://github.com/AArnott/CodeGeneration.Roslyn/commit/b787bd1369df4405640bf05b920605e1ec4878b1) and suddenly an Ubuntu 14 machine can't run my dotnet CLI tool, giving this error:

```
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.1
      1.0.4
  - Alternatively, install the framework version '1.0.5'.
```

I found that between the two releases, the `dotnet-codegen.runtimeconfig.json` file had changed in a subtle, yet evidently significant way. The new one requires 1.0.5:

```json
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.5"
    }
  }
}
```

Whereas the old release required 1.0.4.

My dotnet CLI tool [project file](https://github.com/AArnott/CodeGeneration.Roslyn/blob/806e2e697e6c250cdb0b9e87e8b9ab11b41f4c96/src/CodeGeneration.Roslyn.Tool/CodeGeneration.Roslyn.Tool.csproj) has not changed between these two commits. And it specified a target framework of `netcoreapp1.0`. 

The only thing I can guess is that AppVeyor is now using agents with newer versions of VS2017, and somewhere along the line the dotnet SDK decided to automatically target a newer version of CoreCLR such that what I build no longer works on Ubuntu machines with dotnet CLI 1.0.1 installed (e.g. Travis CI). This is causing build breaks in projects that I'm trying to update to the latest build of my dotnet CLI tool.

How can I force my project to target 1.0.4 again?
Why the automatic, implicit upgrade in requirements for my tool?
How would I install 1.0.5 if I wanted to do that?

_Copied from original issue: dotnet/coreclr#12447_

**Comment by AArnott** [comment]
This looks very similar to https://github.com/dotnet/sdk/issues/983, which is closed (but evidently not accepted, since it would seem that would have prevented this problem).

**Comment by AArnott** [comment]
I found I can workaround the problem with https://github.com/AArnott/CodeGeneration.Roslyn/commit/a1359b864bd8215dbc8d65b437d998977cca2f16. Is that by design then, that without this optional reference, the actual CoreCLR runtime required after building can vary from computer to computer?

**Comment by dsplaisted** [comment]
You probably want to use the RuntimeFrameworkVersion instead of the PackageReference.

Going forward, we don't intend to roll forward like this for framework dependent apps. Self contained apps would roll forward but wouldn't break like this because they'd carry the updated framework with them.

**Comment by AArnott** [comment]
Thanks, @dsplaisted. Where is `RuntimeFrameworkVersion` documented? A quick Bing search doesn't turn up any modern docs. 
Also, can you tell me how I would install 1.0.5 on an Ubuntu machine?

**Comment by livarcocc** [comment]
@AArnott, I am not sure where it is documented. As for installing that runtime in the machine, you can find instructions here: https://www.microsoft.com/net/core#linuxubuntu. I believe the package would be something like dotnet-runtime-1.0.5. @leecow to confirm.

@mairaw for documentation.

@AArnott I am going to close the issue for now, if there is anything else you need, please, re-activate and let us know.

**Comment by AArnott** [comment]
> Self contained apps would roll forward but wouldn't break like this because they'd carry the updated framework with them.

Hmmm... Except it violates reproducibility of builds. And updates to .NET has been known to break stuff, so I suppose the same may be true for CoreCLR. Rolling forward may be an OK default behavior within servicing releases as long as the paranoid consumers can lock in a version.

**Comment by dasMulli** [comment]
>A quick Bing search doesn't turn up any modern docs.

I hate to be bashing Bing but a google search quickly tells me this is documented (vaguely) at in the main csproj reference: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#recommendations

The design for the version binding in 2+ is discussed and documented at https://github.com/dotnet/designs/issues/3

**Comment by leecow** [comment]
@AArnott , @livarcocc - If you have already followed the steps at https://www.microsoft.com/net/core#linuxubuntu, installed the SDK and just need the 1.0.5 shared framework then:

`sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.0.5`

Package names get much nicer with 2.0.
