### ISSUE TITLE
Multi targets project build success on Windows but failed on travis-ci

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#1371]
I developed a project target on .netstandard1.6 and net45,I can build it successfully on my local windows and appveyor,but when I built via travis-ci,I met the error as follows:

```
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. 

To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. 

Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. 

Therefore your assembly may not be correctly targeted for the framework you intend. [/home/travis/build/WeihanLi/MvcSimplePager/MvcSimplePager/MvcSimplePager.csproj]
```

- [travis-ci build log](https://travis-ci.org/WeihanLi/MvcSimplePager/builds/247033577)
- [appveyor build log](https://ci.appveyor.com/project/WeihanLi/mvcsimplepager)

**Comment by livarcocc** [comment]
You must have the net45 targeting pack installed locally and in appveyor but not in the travis-ci machine.

A targeting pack is required to build net45.

Please, re-activate if you verify that you have it installed and it is still failing.

**Comment by livarcocc** [comment]
Bt the way, we don't support full framework cross-plat, that only works in Windows.

**Comment by WeihanLi** [comment]
I have install the latest mono,but it still did not work,is there any way to install net45 packages on linux?

**Comment by WeihanLi** [comment]
Any solution for build multi targets project (including .netframework target) on linux??

**Comment by WeihanLi** [comment]
Thanks @dsplaisted @livarcocc

**Comment by dasMulli** [comment]
fyi I've summed up the current ways to build for net* on linux at https://stackoverflow.com/questions/44770702/build-nuget-package-on-linux-that-targets-net-framework/44773795#44773795
