### ISSUE TITLE
Published NET 5.0 single file win-x86 WPF app contains extra files and fails to run

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/sdk#13731]
**SDK Build:** 5.0.100-rc.1.20452.10
**VS Build:**   16.8 Preview 4 (Main 30521.17)

**Repro Steps:**

1. Create new .NET Core WPF app
2. Set platform to Release|x86
3. Open project properties, change target from 3.1 to 5.0 (Note: Does not repro if I leave it at 3.1)
4. Publish -> Create new folder profile with options Release|x86, Self Contained, win-x86, Produce single file
5. Publish

**Issues:**

1. Inspect publish folder, where you expect there to just be an exe and pdb, instead:

clrcompression.dll            719,224
clrjit.dll                    1,113,976
coreclr.dll                   4,224,376
D3DCompiler_47_cor3.dll       3,714,200
mscordaccore.dll              982,888
PenImc_cor3.dll               141,176
PresentationNative_cor3.dll   940,920
vcruntime140_cor3.dll         83,744
WpfApp96.exe                  123,033,807
WpfApp96.pdb                  13,108
wpfgfx_cor3.dll               1,926,008

2. Copy the contents of the publish folder to a machine without the runtime installed, it fails with this exception in event viewer:

Application: WpfApp96.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Threading.Dispatcher' threw an exception.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName()
   at System.Reflection.RuntimeModule.get_Name()
   at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls)
   at System.Windows.Threading.Dispatcher..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at System.Windows.Threading.DispatcherObject..ctor()
   at System.Windows.Application..ctor()
   at WpfApp96.App..ctor()
   at WpfApp96.App.Main()

**Comment by marcpopMSFT** [comment]
@wli3 mind taking a look and routing as appropriate?

**Comment by wli3** [comment]
@agocke @swaroop-sridhar

**Comment by agocke** [comment]
The app should run OK as of RC2, but single-file publish in .NET 5 on Windows cannot bundle native libraries, so you will still have the listed files. If you want to embed the native assets and extract them to a temp directory at runtime, you can pass `/p:IncludeNativeLibrariesForSelfExtract=true`
