### ISSUE TITLE
No the ".NET 6.0" item appeared in the dropdown list of "Target framework" after installed the latest .NET 6.0

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/sdk#13742]
**Version info:**
Latest .NET 6.0.100-alpha.1.20420.20

**More info:**
The issue also can reproduce on WPF Core, Console Core etc. types project.

**Minimal Reproduction Scenario**

1. Install the latest .NET 6.0 from https://github.com/dotnet/installer.
2. Create a .NET Core winforms project.
3. Check the .NET 6.0 build number in the Control panel.
4. Check the .NET 6.0 build number under ..\dotnet\sdk & ..\dotnet\shared\Microsoft.AspNetCore.App etc. folders.
5. Check the items in the dropdown list of "Target framework" in Application property page.

**Expected Behavior**
The ".NET 6.0" item appeared in the dropdown list of "Target framework" after installed the latest .NET 6.0

**Current Behavior**
After steps3, the build is .NET SDK 6.0.100-alpha.1.20420.20 in the control panel.
After steps4. the build number is 6.0.100-alpha.1.20420.20 under ..\dotnet\sdk folder, however the build number still is 5.0.0-rc1 under ..\dotnet\shared\Microsoft.AspNetCore.App etc. folders.
After step5, No ".NET 6.0" item appeared in the dropdown list of "Target framework".
![CoreSdkIssue1](https://user-images.githubusercontent.com/38325459/90872046-9ae9c080-e3ce-11ea-98d2-3de078defc43.gif)

**Comment by davkean** [comment]
This comes from the SDK, in particular, `SupportedTargetFramework` items. Moving to the SDK.
