### ISSUE TITLE
outputpath is appended with netcoreapp2.0

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/sdk#1376]
In my .csproj I have
      `<OutputPath>$(SolutionDir)\Output\bin\$(Platform)\$(Configuration)\</OutputPath>`

but viewing it in visual studio it appends netcoreapp2.0\ to the resultant path.

**Comment by nguerrera** [comment]
You can set <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath> to turn this off.
