### ISSUE TITLE
How to turn off platform inference?

### ISSUE THREAD

**Issue by MikhailArkhipov** [dotnet/sdk#1381]
When building WiX project (which is x86), .NET Core dependencies are getting built as x86 despite the fact they are specify platform as AnyCPU. This is wrong - bitness of setup project has nothing to do with assemblies it packages.

Also, in another case, there may be 32-bit executable using agnostic class library and IL executable using same binaries. If common binary is built as dependency of the x86 executable, it fails to load on 64-bit machine for another executable that happens to run as x64.

Perhaps there is a way to turn off derivation of platform? I need assemblies built _exactly_ as specified in their projects, not by platform of an executable (or setup) that depends on them.

Workaround I guess is to separate setup into its own solution so it won't be building dependencies as x86.

**Comment by livarcocc** [comment]
@nguerrera another inference issue for RIDs.
