### ISSUE TITLE
Tool pack outputs to aliased path in nupkg

### ISSUE THREAD

**Issue by zkat** [dotnet/sdk#13843]
When packing a tool that uses NuGet aliases, the nupkg itself should put its output files under the concrete framework shortname, rather than the alias. This was fixed in other NuGet packaging scenarios for https://github.com/NuGet/Home/issues/10020, but packing tool projects is still affected, and I'm told this is not under NuGet's control, so I'm filing a bug here.

## Repro

1. `dotnet new console -n baz`
2. `cd baz`
3. Replace .csproj contents with the text below
4. `dotnet pack`
5. extract the .nupkg in the `nupkg` dir
6. look in the `tools` directory

### csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net50-windows</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>hello</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>
</Project>
```

## Expected

`tools/net5.0-windows7.0/any/...`

## Actual

`tools/net50-windows/any/...`

## Sample project

You can just extract this one and run `dotnet pack` on it.

[baz.zip](https://github.com/dotnet/sdk/files/5285339/baz.zip)

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/13924
