### ISSUE TITLE
dotnet build solution with old ASP.NET Web project fails

### ISSUE THREAD

**Issue by geirsagberg** [dotnet/sdk#1385]
I have a solution that consists of both an ASP.NET Core 2.0 web project and an ASP.NET MVC 5 web project. When building from VS2017 15.3 Preview 2 everything works, but when I run `dotnet build`, I get the following error:

```
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

What am I doing wrong? Is it not possible to build "old" web projects with `dotnet`? I thought `dotnet` just used MSBuild internally; should I instead use MSBuild directly?

**Comment by geirsagberg** [comment]
If I instead use `msbuild.exe` directly from `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin`, it works, so now I just have to get the preview build tools installed on my build server, and I'm good to go.

**Comment by ManfredLange** [comment]
In case someone runs into this and using msbuild instead of dotent is not an option perhaps Alistair Crabtree's [workaround](https://alastaircrabtree.com/microsoft-webapplication-targets-was-not-found-again/) is a viable alternative.
