### ISSUE TITLE
dotnet tool installl does not work when I have multiple nuget sources

### ISSUE THREAD

**Issue by mturczyn** [dotnet/sdk#13881]
I have couple of nuget sources on my PC besides default one, nuget.org (https://api.nuget.org/v3/index.json).

When I try to install dotnet counters, it shows only error after couple of seconds.

When I disable all other nuget sources except nuget.org, I can install the tool successfully.

Ideally, it should try to use source by source until it completes. On the other hand, there can be multiple sources for a package, so it would be ideally to be warned about it and be able to specify source as parameter to command, eg.:

dotnet tool install someTool --source nuget.org

**Comment by marcpopMSFT** [comment]
Does it work if you use --ignore-failed-sources?

**Comment by mturczyn** [comment]
@marcpopMSFT  I just ried to reproduce the issue, but now it seems to be working correctly.

Of course, it also works with your suggestion.

**Comment by marcpopMSFT** [comment]
Thanks for confirming. I'll close this issue for now but if it comes back and the suggested flag doesn't help, please feel free to reopen the issue.

**Comment by mturczyn** [comment]
@marcpopMSFT  I again stumbled upon this. This time I had other nuget sources set and active, but address pointing to that required VPN turned on. Without turning on VPN, I reporduced the issue.

But, it works with extra parameter "--ignore-failed-sources" as you suggested.
