### ISSUE TITLE
[net5] dotnet test output total time elapsed in all threads

### ISSUE THREAD

**Issue by dtopuzov** [dotnet/sdk#13892]
Output of test run with `5.0.100-rc.1.20452.10`:
```
Passed!  - Failed:     0, Passed:   433, Skipped:     5, Total:   438, Duration: 9 m 44 s - Blazor.Playground.Tests.dll (net5.0)
```
Those `9 m 44 s` are the total time of all threads, actually, tests were executed in ~3min.

dotnet sdk `3.1.401` shows the real elapsed time (not the sum of all treads).
I prefer the old behavior.

**Comment by marcpopMSFT** [comment]
@nohwnd for visibility

**Comment by nohwnd** [comment]
Moved here https://github.com/microsoft/vstest/issues/2585 this issue can be closed.
