### ISSUE TITLE
PublishSingleFile alter dlls as part of PostBuildEvent before compressing the single .exe

### ISSUE THREAD

**Issue by lastlink** [dotnet/sdk#13894]
### Description
* I'm trying to alter the dll's before they get compressed into the single .exe file in the publish folder. The **main goal** is to **obfuscate** and **protect** my dlls. However, when I review the dlls after running the final .exe and locating the decompressed dlls in the temp folder I find them not obfuscated. I don't know if the compressed stage holds the dll's in memory or grabs them from another location
  * `dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true  /p:rId=lwin-x64`
  * see example issue in https://github.com/obfuscar/obfuscar/issues/301
  * also https://stackoverflow.com/a/61890921/2875452 is helpful in finding the temp folder
* I was able to do custom build targets by runtime identifier by using a property or custom variable, after the build finishes in the log I then run obfuscator that obfuscates the files into an output folder. then after that I copy those files back into the original folder hoping that the single file compres grabs the overwritten obfuscated files. However, upon review they are **not obfuscated**.

### paste from the issue

* setup
`dotnet tool install Obfuscar.GlobalTool --tool-path tools --version 2.2.18`

**.csproj** post build 
```xml
<PropertyGroup>
    <rId Condition="$(rId) == ''">win-x64</rId>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="$(ConfigurationName) == Release">
    <Exec Command="if '$(rId)' == 'win-x64' ..\tools\obfuscar.console ..\obfuscar-win-x64.xml&#xD;&#xA;if '$(rId)' == 'linux-arm' ..\tools\obfuscar.console ..\obfuscar-linux-arm.xml&#xD;&#xA;copy "$(TargetDir)ReadyForDeployment\main.dll" "$(TargetDir)main.dll" /y" />
  </Target>
```

obfuscar example file **obfuscar-win-x64**
```xml
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\bin\Release\netcoreapp3.1\win-x64" />
  <!-- <Var name="OutPath" value="$(InPath)" /> -->
  <Var name="OutPath" value="$(InPath)\ReadyForDeployment" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Module file="$(InPath)\main.dll" />
</Obfuscator>
```

* publish cmds
```sh
dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
dotnet publish -c Release -r linux-arm -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true /p:rId=linux-arm 
```

**Comment by lastlink** [comment]
* figured it out, you have to copy the results to the correct place in the obj folder. This folder may need to be deleted before each publish, b/c publish won't work the 2nd time after obfuscating

**Comment by marcpopMSFT** [comment]
Closing since you figured out a resolution.
