### ISSUE TITLE
warning MSB3277 is uninformative by default

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/sdk#1391]
The text of warning MSB3277 ("Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.") lacks helpful details like package name, and version number. Is there a reason not to put that information into the text of this message rather than hiding it in the Detailed message?

**Comment by rainersigwald** [comment]
This is tracked as https://github.com/Microsoft/msbuild/issues/608.
