### ISSUE TITLE
Warning for warning NU5128 when packastool with targetframework alias

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#13928]
Given
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>targetframeworkAlias</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'targetframeworkAlias' ">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v3.1</TargetFrameworkVersion>
    <TargetFrameworkMoniker>.NETCoreApp,Version=v3.1</TargetFrameworkMoniker>
  </PropertyGroup>

</Project>

```

run dotnet pack. There will be an extra necessary warning:
```
C:\work\sdk3\artifacts\bin\redist\Debug\dotnet\sdk\5.0.100-dev\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [C:\work\temp\nugetalias\nugetalias.csproj]
C:\work\sdk3\artifacts\bin\redist\Debug\dotnet\sdk\5.0.100-dev\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: - Add lib or ref assemblies for the netcoreapp3.1 target framework [C:\work\temp\nugetalias\nugetalias.csproj]
```

**Comment by wli3** [comment]
Still have the issue after https://github.com/dotnet/sdk/pull/13924 fix

**Comment by wli3** [comment]
@nkolev92 I don't think it is a blocking issue. But any idea about the cause?

**Comment by marcpopMSFT** [comment]
@nkolev92 should this go to NuGet?

**Comment by nkolev92** [comment]
@wli3 
Can you post the content of the package when you run it with and without an alias? 

When did this warning start happening?

**Comment by wli3** [comment]
[nugetalias.1.0.0-with-alias.zip](https://github.com/dotnet/sdk/files/5308396/nugetalias.1.0.0-with-alias.zip)
[nugetalias.1.0.0.without-alias.zip](https://github.com/dotnet/sdk/files/5308398/nugetalias.1.0.0.without-alias.zip)

changed the nupkg suffix to zip since github does not allow me to upload that

**Comment by wli3** [comment]
![image](https://user-images.githubusercontent.com/6993335/94743003-7f59ca00-032b-11eb-802e-47caf6f4e904.png)

interesting. Everything else is the same

**Comment by nkolev92** [comment]
Is `SuppressDependenciesWhenPacking` being set anywhere, or it just NuGet doing something different?

**Comment by wli3** [comment]
It should be set no matter alias or not. But even when i use `dotnet pack /p:SuppressDependenciesWhenPacking=true` the error still shows

**Comment by nkolev92** [comment]
The existence of the dependencies element is what is causing the warning to appear. 

Is the alias the only difference between the projects? 
If that's the case, I think we should mvoe it to NuGet so we can investigate further.

**Comment by wli3** [comment]
Yes the only different is <TargetFramework>targetframeworkAlias</TargetFramework> vs <TargetFramework>netcoreapp3.1</TargetFramework>

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#10097
