### ISSUE TITLE
[regression since 15.2] net core sdk project auto restore does not pop up error list for restore errors

### ISSUE THREAD

**Issue by mishra14** [dotnet/sdk#1392]
Original bug: https://github.com/NuGet/Home/issues/5509

Moving this here since NuGet is no longer populating the error list for net core sdk projects and it seems more reasonable for the sdk target to pop up the error list.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS 

NuGet version (x.x.x.xxx): 4.3.0.4250

VS version (if appropriate): d15prerel/26627.3006

Worked before? If so, with which NuGet version: 4.2.0.2457 in VS 15.2

## Detailed repro steps so we can see the same problem

1. File New Project -> Net standard class library.

2. Change target framework to netstandard1.4.

3. Close Error list and output windows if open.

4. Edit csproj to add the following - 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="1.1.3" />
  </ItemGroup>
```

...

### Expected 

The error list should be displayed as in 15.2 - 
![editcsprojin15 2](https://user-images.githubusercontent.com/10507120/27712654-da7edd4c-5cdc-11e7-9a1c-94f89204288c.PNG)

### Actual 

No error list is displayed - 
![editcsprojin15 3](https://user-images.githubusercontent.com/10507120/27712664-e677a34a-5cdc-11e7-844b-e1decf4dfa2a.PNG)

**Comment by mishra14** [comment]
@natidea @srivatsn

**Comment by srivatsn** [comment]
This issue was moved to dotnet/project-system#2574

**Comment by srivatsn** [comment]
The SDK doesn't know about VS and can't pop up the error list. Something in VS has to do this. Moving to the project system repo
