### ISSUE TITLE
ResolveReferences inconsistencies

### ISSUE THREAD

**Issue by mhutch** [dotnet/sdk#1393]
I have a net461 console project using non-SDK tooling that references a netstandard1.4 library project that uses SDK tooling.

If I build the solution, then call `ResolveReferences` on the console project, the `ImplicitlyExpandDesignTimeFacades` target detects that the referenced netstandard project references System.Runtime, and injects all the net461 facades.

However, if I clean the solution, then call `ResolveReferences` again, `ImplicitlyExpandDesignTimeFacades` does _not_ detect the System.Runtime reference, as the referenced project has not yet been built and there is no assembly to inspect.

However, if I do the same thing with a PCL instead of netstandard, `ResolveReferences` works correctly regardless of whether the project has been built or not.

This is because [the logic for injecting the facades](https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Tasks/Microsoft.NETFramework.CurrentVersion.targets#L95) checks whether any of the project references have a `TargetPlatformIdentifier` value of `Portable`. This is true for PCL projects, not NOT for netstandard. For netstandard projects, the value is `Windows`, which is clearly incorrect.

**Comment by livarcocc** [comment]
@rainersigwald Is this something that we need to update in msbuild?

**Comment by rainersigwald** [comment]
I don't think it can be fixed in MSBuild alone. RAR can't do its magic if the file(s) it wants to inspect don't exist because they haven't been built yet, so we need to get metadata from the referenced project. But we'd need to think through the implications of changing `TargetPlatformIdentifier` -- should it be `portable` for netstandard projects? Should we invent a new value `netstandard` and alter the check?

**Comment by mhutch** [comment]
Here is a test case: https://bugzilla.xamarin.com/show_bug.cgi?id=55734. This bug was filed against VSMac but the issue is reproducible in VS 15.3 Preview 3.

As you would expect, the line in Main.cs referred to by the bug is squiggled when the project is first opened. If you build the project then close and reopen it, the line is not squiggled.

**Comment by rainersigwald** [comment]
Another possible approach: inject a target that runs after RAR and before `ImplicitlyExpandDesignTimeFacades` and flips `DependsOnSystemRuntime` to true based on metadata from #1407.
