### ISSUE TITLE
dotnet test should fail when it can't find any tests

### ISSUE THREAD

**Issue by omajid** [dotnet/sdk#13942]
At various times, `dotnet test` seems to run into an issue where it can't identify any tests. When that happens, `dotnet test` exits with a 0 exit code. Everything interprets 0 as success. That tells the user (and any automated systems) that everything is working, even though no tests were found which should actually be an error.

This happened in [.NET 5 Preview 8](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md#preview-8-1):

>    Running xUnit tests fails to discover tests in with message No test is available in <assembly> Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.. To solve this update your xunit.runner.visualstudio package to version 2.4.3. This version is used in dotnet new templates, but existing projects targetting, or updating to net5.0 need to be updated manually.

I tried migrating to .NET 5 Preview 8and all my tests "passed", because the tests couldn't be found at all.

Would it be possible to make `dotnet test` fail with an non-zero exit code when tests can't be found? This makes it easier for developers to catch issues in their CI instead of incorrectly assuming that all tests are passing. When I see that tests fail, I can take steps to find the error and apply the workarounds.

**Comment by omajid** [comment]
cc @tmds @aslicerh

**Comment by omajid** [comment]
We ran into this issue during a previous release too: https://github.com/microsoft/vstest/issues/2079. This also had the bug that `dotnet test` was not actually working but returning with a 0 exit code fooling CI into thinking that everything was working correctly.

**Comment by tmds** [comment]
A zero exit code MUST mean success for `dotnet test`.

I feel like clicking the ':+1:'-button a hundred times.

cc @KathleenDollard

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2590
