### ISSUE TITLE
Unable to Create a BluetoothLEAdvertisementFilter with BluetoothLEAdvertisement ServiceUuids

### ISSUE THREAD

**Issue by michaelerice-github** [dotnet/sdk#13940]
Using nuget pkg "Microsoft.Windows.SDK.Contracts", version "10.0.19041.1"

When you try to create a BluetoothLEAdvertisement to use within a BluetoothLEAdvertisementFilter, the ServiceUuids property is read only:

			var bluetoothLEAdvertisementWatcher= new BluetoothLEAdvertisementWatcher
			{
				ScanningMode = BluetoothLEScanningMode.Active,

			};

			var bluetoothLEAdvertisement = new BluetoothLEAdvertisement
			{
				ServiceUuids = new Guid[] { GattServiceUuids.BloodPressure }, // read-only
			};

			var bluetoothLEAdvertisementFilter = new BluetoothLEAdvertisementFilter
			{
				Advertisement = bluetoothLEAdvertisement
			};

			bluetoothLEAdvertisementWatcher.AdvertisementFilter = bluetoothLEAdvertisementFilter;

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/CsWinRT#496
