### ISSUE TITLE
Adding a KnownFrameworkReference for net6.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#13950]
Currently the sdk doesnt know about net6.0 tfm. Is there any timeline on when we can expect that change ?

cc @ericstj @ViktorHofer

**Comment by ViktorHofer** [comment]
cc @dsplaisted

**Comment by ViktorHofer** [comment]
cc @marcpopMSFT

**Comment by marcpopMSFT** [comment]
I expect there to be a move to 6.0 effort for all dotnet repos once 5.0 locks down and ships so maybe in a month. Many upstream repos are still 5.0 branded and we'll need to coordinate.

**Comment by marek-safar** [comment]
@marcpopMSFT what does remain to be done here? We are working on .NET6 P1 and this is blocking the upgrade from 5.0 targets.

**Comment by marcpopMSFT** [comment]
@dsplaisted started the work to prep master for 6.0.  You can see the PR here to update a bunch of the packages and templates accordingly: https://github.com/dotnet/installer/pull/8914
