### ISSUE TITLE
dotnet publish should not include static libraries

### ISSUE THREAD

**Issue by 0xced** [dotnet/sdk#13985]
On macOS (and maybe also on Linux, I have not tried) five static libraries end up in the publish directory when publishing an executable with `dotnet publish -c Release -r osx-x64` (reproducible with a hello world console app):

* libSystem.IO.Compression.Native.a
* libSystem.Native.a
* libSystem.Net.Security.Native.a
* libSystem.Security.Cryptography.Native.Apple.a
* libSystem.Security.Cryptography.Native.OpenSsl.a

Those are not required at runtime (only dynamic libraries are used) and should not be included in the publish directory.

As a workaround I have added this in my csproj file:

```xml
<Target Name="RemoveStaticLibraries" AfterTargets="ResolveRuntimePackAssets">
  <ItemGroup>
    <RuntimePackAsset Remove="@(RuntimePackAsset)" Condition="'%(Extension)' == '.a'" />
    <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Extension)' == '.a'" />
  </ItemGroup>
</Target>
```

Ideally this workaround should not be needed and the SDK should be responsible for **not** publishing the static library files.

Technical details (gathered by analyzing the binary build log with [MSBuild Log Viewer](https://msbuildlog.com), reading and grepping source code in dotnet repositories):

* The static library files are copied into the publish directory because they are part of the output of the [`ResolveRuntimePackAssets`](https://github.com/dotnet/sdk/blob/552e4b93eec289aa4c2c8f96a11b5a85edfecbf9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L82-L89) MSBuild task.
* The `ResolveRuntimePackAssets` MSBuild task reads a `RuntimeList.xml` file, apparently from the [Microsoft.NETCore.App.Runtime.osx-x64](https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.osx-x64/) NuGet package in the `data` directory.
* The `RuntimeList.xml` file seems to be created by the [`GenerateRuntimeListFile`](https://github.com/dotnet/runtime/blob/f1e131a4bef5bd5373a3dab65523851b54a94306/src/libraries/pretest.proj#L118-L135) target (dotnet/runtime repository).
* The `GenerateRuntimeListFile` target calls the [`CreateFrameworkListFile`](https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/src/CreateFrameworkListFile.cs#L13) MSBuild task (dotnet/arcade repository) to create the `RuntimeList.xml` file.

I *think* that what should be fixed is the [`RuntimePackNativeFile`](https://github.com/dotnet/runtime/blob/f1e131a4bef5bd5373a3dab65523851b54a94306/src/libraries/pretest.proj#L96-L99) item. It includes everything `$(MicrosoftNetCoreAppRuntimePackNativeDir)*.*` but should probably exclude `.a` files. I'll let someone at Microsoft more exerienced than me confirm my intuition though.

**Comment by sfoslund** [comment]
I assume this repros with all versions of the SDK, correct? My instinct is that we likely don't want to change this behavior, but do you have any thoughts @wli3?

**Comment by wli3** [comment]
@jeffschwMSFT could you help us route to the right person to answer the question? If these files are not runtime asset, they should only be include in targeting pack instead of runtime pack.

**Comment by jeffschwMSFT** [comment]
We removed these in .NET 5 RC2.  What version is this for?

cc @vitek-karas

**Comment by 0xced** [comment]
> We removed these in .NET 5 RC2.

Oh that's great. Could you please show me how you did it? I.e. point me at the exact commit that removed them? I was probably looking at the wrong branch  during my investigations. Or I did not properly understand how everything is packaged together.

> What version is this for?

Sorry I forgot to mention. I have observed that static libraries end up in the publish directory with both 3.1.402 and 5.0.100-rc.1.20452.10 SDKs.

**Comment by vitek-karas** [comment]
We fixed this in master branch https://github.com/dotnet/runtime/pull/41966, but the port to RC2 was rejected by triage: https://github.com/dotnet/runtime/pull/41986.
So AFAIK we will ship 5.0 still with these files included in self-contained apps.

**Comment by 0xced** [comment]
Thanks for the clarification, Vitek. Don't you think that the `.a` files should not even end up in the `RuntimeList.xml` file as I described in my original post, though?

**Comment by jeffschwMSFT** [comment]
Oh man, I thought that we took that change.  You are right we could not safely remove them so late.

**Comment by vitek-karas** [comment]
@0xced sorry I don't remember the details anymore. I agree they should not be mentioned anywhere in the runtime pack, but I don't know if my "fix" actually fixes the runtime list.

**Comment by akoeplinger** [comment]
I can confirm that the files no longer show up in RuntimeList.xml after the fix.
