### ISSUE TITLE
dotnet uses the wrong NuGet.config file on Mac

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/sdk#1398]
The [documented location](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) for a `NuGet.config` file is `%APPDATA%\NuGet\NuGet.Config`. On Windows, this config is used by both Visual Studio and `dotnet`.

On Mac, this config (which resolves to `~/.config/NuGet/NuGet.config`) is used by Visual Studio for Mac, but `dotnet` uses (and indeed, modifies to have a `CliFallbackFolder` entry) `~/.nuget/NuGet/NuGet.config`.

This is very confusing when you add a source in Visual Studio for Mac and expect it to function in `dotnet`.

Since this inconsistency is not documented anywhere I can find, I must assume it's just a bug. Would be awesome to have this fixed for 2.0 final!

**Comment by livarcocc** [comment]
The SDK is no longer modifying your NuGet.Config. So, this issue is fixed. However, when we were doing that, we were using Nuget itself to determine where to write configuration. If anything, I would say that VS for MAC is the inconsistent one here.

**Comment by sandyarmstrong** [comment]
@livarcocc I don't understand how this issue is fixed. `dotnet` is using the wrong config file on Mac. Is there documentation I'm missing that indicates this is intentional? It should not be getting anything from `~/.nuget`.

**Comment by livarcocc** [comment]
@emgarten @rrelyea HOME/.nuget is the NuGet folder for non-windows distros. Has been since 1.0 of .NET Core.

**Comment by sandyarmstrong** [comment]
@livarcocc okay, I see that NuGet is defining it differently for .NET Core than all other NuGet clients on non-Windows distros (see https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L45-L48 and the `IS_CORECLR` determination in how `GetFolderPath` is implemented).

I don't think anybody benefits from this inconsistency, though. I will open a bug about this with NuGet if you think that's more appropriate.

**Comment by livarcocc** [comment]
I think that's the right place for us to have a productive conversation. File an issue at nuget/home. Please, tag me when you do, so that I can follow it.

**Comment by sandyarmstrong** [comment]
Filed https://github.com/NuGet/Home/issues/5555.
