### ISSUE TITLE
Path to dotnet.exe

### ISSUE THREAD

**Issue by agr** [dotnet/sdk#13988]
Is there a way to figure out where `dotnet.exe` resides if it is not available through the `PATH` environment variable on Windows? Assuming it is somewhere besides `C:\Program Files\dotnet\dotnet.exe`.

**Comment by sfoslund** [comment]
If you are able to run dotnet commands, `dotnet --info` gives you file location information. Otherwise, you will have to use normal file search methods.

**Comment by agr** [comment]
If I am able to run `dotnet --info`, it means that it is somewhere in the `PATH`, not my case. After digging a bit more into it, it seems the only way is to actually search for it, indeed. I hoped for something like `vswhere`.
