### ISSUE TITLE
Daily SDKs for 6.0 runtime seem to have 5.0-rc2 runtime since ~mid September

### ISSUE THREAD

**Issue by kouvel** [dotnet/sdk#14007]
I’m seeing that for the latest SDK builds available here from the master branch: https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries
The most recent ones have a 6.0 SDK but a 5.0-rc2 NetCore and AspNetCore runtime, even though the column says it’s a 6.0 runtime.

The last daily SDKs that I had downloaded had a 6.0 runtime from Sep 10 from the master branch.
Has there been a change in how those builds are produced?
Where can I find the latest SDKs with runtime bits from master?

Separate question:
I tried the download link for some recently older SDKs but it looks like they are not available anymore. Is there a list somewhere of recent SDKs that are available to download?

**Comment by kouvel** [comment]
For context I'm looking for a baseline SDK build that I can use with patching for perf-testing 6.0 bits

**Comment by sfoslund** [comment]
Runtime versions are in the process of being updated through dependency flow. It looks like [this PR ](https://github.com/dotnet/installer/pull/8725)is carrying the 6.0 runtime, so once that is green and merged it will produce a build with the 6.0 runtime.

**Comment by kouvel** [comment]
Seems to be fixed after that PR, thanks!
