### ISSUE TITLE
[loc][query] Assistance with ambiguity

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#14004]
String Resource ID | 0; "CREATEPROVIDERLIST_ImportPublishDatabaseSettingNotFound"
-- | --
Source String | Publish Database Setting Source Verification Error: The publish profile specified '{1} ({2})' for '{0}' does not have a corresponding connection string in '{3}'. Because of this publishing has been blocked. If this was intended you can disable this check by specifying the value of "True" for the MSBuild property "IgnoreDatabaseSettingOutOfSync." If this was not intended, open the Publish dialog in Visual Studio with this profile to correct the discrepancy. For more information visit http://go.microsoft.com/fwlink/?LinkId=241526
Subtenant | dotnet_sdk
Source Control Link |  
Filename | WebSdk\Publish\Tasks\Properties\xlf\Resources.xlf
Question | We understood the first part as follows: Error when verifying the source for the setting to publish the database. Please confirm or advise. Similar strings: 0; "CREATEPROVIDERLIST_ImportValidationSourceNotFound" 0; "CREATEPROVIDERLIST_InvalidPublishDatabaseSetting" 0; "CREATEPROVIDERLIST_OutofSyncWithSourcePublishDatabaseSetting"

**Comment by wli3** [comment]
@vijayrkn could you answer this question?

**Comment by vijayrkn** [comment]
> Question	We understood the first part as follows: Error when verifying the source for the setting to publish the database. Please confirm or advise. Similar strings: 0; "CREATEPROVIDERLIST_ImportValidationSourceNotFound" 0; "CREATEPROVIDERLIST_InvalidPublishDatabaseSetting" 0; "CREATEPROVIDERLIST_OutofSyncWithSourcePublishDatabaseSetting"

I checked the code and this is not currently being used in the code. This can be left non-localized.
