### ISSUE TITLE
[loc][query] Assistance with placeholders

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#14003]
String Resource ID | 0; "PublishLocalizedString_MsBuildPropertySettingValue"
-- | --
Source String | $({0}) is {1}
Subtenant | dotnet_sdk
Source Control Link |  
Filename | WebSdk\Publish\Tasks\Properties\xlf\Resources.xlf
Question | What do the placeholders stand for here? Please explain.

**Comment by wli3** [comment]
@vijayrkn could you answer this question?

**Comment by vijayrkn** [comment]
> PublishLocalizedString_MsBuildPropertySettingValue

0 is the name of the msbuild property and 1 is the value of the msbuild property
