### ISSUE TITLE
dotnet test results are overridden if using html logger and result-directory switch is used

### ISSUE THREAD

**Issue by ckittelmann** [dotnet/sdk#14015]
I have a solution with 14 test projects.
For our new CI server I want to execute the unit tests by script and get the html reports that I can save in an artifact repository.

The script executes the tests with following command:
`dotnet test -c Release -l html --results-directory:"TestResults"`

Doing this creates a different amout of result files everytime I execute the script.
I analysed the console output and found out that the result file of one project can override the result files of another project.

I attached the console output to this issue. Just search for "TestResult_ckittelmann_LAP-0008-17_20201007_115719.html" and you will find it twice
[dotnet-test.log](https://github.com/dotnet/sdk/files/5340240/dotnet-test.log)

This behaviour only applies to the html logger, the trx logger will create a filename with attached number in brackets if it already exists

I'm using SDK 3.1.402

**Comment by nohwnd** [comment]
We have fixed overwriting trx files net5 SDK. There is no plan to port it back to 3.1.
