### ISSUE TITLE
Application Manifest File does not build correctly

### ISSUE THREAD

**Issue by tarekgh** [dotnet/sdk#1401]
@vsccarl commented on [Thu Jul 06 2017](https://github.com/dotnet/corefx/issues/21954)

In a .NET Core project, add an Application Manifest File to the project and build the solution. An error of `CS1926	Error opening Win32 manifest file c:\app1.manifest -- Could not find file 'c:\app1.manifest'.` 

In .NET Framework projects, adding this file works and builds without any modification.

---

@Petermarcu commented on [Fri Jul 07 2017](https://github.com/dotnet/corefx/issues/21954#issuecomment-313609939)

@livarcocc @davkean which repo should this get moved to? Its not a corefx issue.

**Comment by hcoona** [comment]
Any progress?

**Comment by tarekgh** [comment]
@davkean @nguerrera could you please assign this issue to who can help? or move it to msbuild repo if you think it belongs to there? Thanks.

**Comment by davkean** [comment]
I think this was fixed by: https://github.com/dotnet/project-system/pull/2808, which will be in 15.5 Preview when it is released. The workaround @hcoona is to manually edit the path to the app.manifest in the project file itself.

**Comment by hcoona** [comment]
Thanks. I get it built with the workaround.
