### ISSUE TITLE
Add support for non-string assembly attributes

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/sdk#1402]
There should be a way to generate non-string assembly attributes.
For example,
```xml
  <ItemGroup>
    <AssemblyAttribute Include="System.CLSCompliant">
      <_Parameter1>true</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
```
generates
```csharp
[assembly: System.CLSCompliant("true")]
```
which produces an error, because the parameter must be a boolean.

* Are there any workarounds so that I can produce a correct attribute with msbuild today?
* Would you take a PR to fix this?
* If this is not the correct place to raise this issue, I'm sorry, but in the entirety of searchable internet, this repo is the closest to dealing with assembly attributes.

**Comment by dasMulli** [comment]
On Slack, a few ppl asked how to set `ComVisibleAttribute` using an `<AssemblyAttribute>` item for `net*` projects.

**Comment by rainersigwald** [comment]
This issue was moved to Microsoft/msbuild#2281
