### ISSUE TITLE
Deleting a template folder cause a "dotnet new" error

### ISSUE THREAD

**Issue by mhollebecq** [dotnet/sdk#14033]
If we create a template with `dotnet new -i [FolderName]` and then delete the folder, some option of `dotnet new` like "-u" or "--help" are blocked.

Of course we expect an error if we try to use the deleted template, but maybe we can be allowed to list template with "-u" or display the help

**Comment by wli3** [comment]
Issue moved to [dotnet/templating #2631](https://github.com/dotnet/templating/issues/2631) via [**ZenHub**](https://www.zenhub.com/)
