### ISSUE TITLE
MSB4094 when using net5.0-windows10.0.xxxx

### ISSUE THREAD

**Issue by adirh3** [dotnet/sdk#14035]
Getting MSB4094 when using target framework `net5.0-windows10.0.xxxx` on empty project. (I've seen similar issues, but they used some nuget that caused it)

I am using .NET5 RC2

To repro - 

`dotnet new console`

Change csproj - 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041</TargetFramework>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

`dotnet publish -c Relase -r win10-x64`

Error:
```
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20480.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,28): error MSB4094: "C:\Users\adirh\.nuget\packages\microsoft.windows.
sdk.net.ref\10.0.19041.6-preview\lib\Microsoft.Windows.SDK.NET.dll;C:\Users\adirh\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.6-preview\lib\Microsoft.Windows.SDK.NET.dll"
is an invalid value for the "CompilationEntry" parameter of the "RunReadyToRunCompiler" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskI
tem". [C:\Users\adirh\RiderProjects\Win10Publish\Win10Publish.csproj]
```

Thanks

**Comment by wli3** [comment]
Thank you, it is fixed by https://github.com/dotnet/sdk/pull/13904 recently

**Comment by adirh3** [comment]
Thanks you.

**Comment by adirh3** [comment]
@wli3 Should it be fixed with the latest RC2 release from here - 
https://github.com/dotnet/installer

Because I still have the same issue with version `5.0.100-rc.2.20480.7`

**Comment by adirh3** [comment]
Seems to be fixed in RTM, sorry for the confusion (thought RC2 was considered 5.0.1xx as well)
