### ISSUE TITLE
Allow runtime packs to be resolved from the packs folder

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#14044]
For targeting packs, the SDK first checks if they are in the dotnet packs folder.  If they are it uses them from there, otherwise it generates a `PackageDownload` item so that they will be downloaded to the packages folder as part of NuGet restore.

Currently, we don't check for runtime packs in the packs folder.  This is because we haven't shipped any with the .NET SDK, as they are only used for self-contained apps and there are many different runtime packs for different RuntimeIdentifiers which represent different OS/architecture combinations.

For .NET 6, iOS and Android apps will need runtime packs, and the set of target RuntimeIdentifiers will be more limited.  So they would like to deliver runtime packs as part of their optional SDK workloads.

This means we should update the SDK runtime pack resolution logic to first look in the dotnet packs folder and resolve from there if possible, before generating a `PackageDownload` item to download the runtime pack if necessary.

**Comment by dagood** [comment]
Sweet! Will this be implemented generally enough to let us start shipping source-built runtime packs? https://github.com/dotnet/source-build/issues/1215

/cc @omajid @tmds

**Comment by steveisok** [comment]
@dsplaisted Do you still anticipate being able to roll this out for 6?

**Comment by jonathanpeppers** [comment]
I don't think iOS/Android/Maui workloads would be able to work offline without this?

**Comment by steveisok** [comment]
> I don't think iOS/Android/Maui workloads would be able to work offline without this?

From what I've seen, they would not.

**Comment by dsplaisted** [comment]
Yes, we're still planning to do this for .NET 6.

**Comment by wli3** [comment]
note from workload meeting: This is a rather easy change. At the same time, not having the feature in not end of the world (use library pack with waste disk space). We should pick up this task after –architecture os work,
