### ISSUE TITLE
Microsoft.TargetingPack.NETFramework.v4.5.1 not covering System.Xml (contains System.XML.dll - case issue?)

### ISSUE THREAD

**Issue by kierenj** [dotnet/sdk#1406]
Hi, I'm trying to cross-compile a NuGet package for netstandard1.6 and net451 on Linux (debian).

I have this deal which has been working fine:

```xml
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net451' ">
    <DefineConstants>$(DefineConstants);WINDOWS_IS_STILL_KINDA_COOL</DefineConstants>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <FrameworkPathOverride>$(NuGetPackageFolders)microsoft.targetingpack.netframework.v4.5.1\1.0.1\lib\net451\</FrameworkPathOverride>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net451' ">
    <PackageReference Include="Microsoft.TargetingPack.NETFramework.v4.5.1" Version="1.0.1" ExcludeAssets="All" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="1.0.2" />
    <Reference Include="System" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.ComponentModel" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Xml" />
  </ItemGroup>
```

However, I get this build warning:

```
/opt/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

It's only since I've then gone on to use `System.Xml` classes that I do now get compilation errors.

Sneaking a look inside `Microsoft.TargetingPack.NETFramework.v4.5.1`, I see there's a `System.XML.dll`, and not a `System.Xml.dll`.  Could that be the cause?  Anything else I can try?

**Comment by dsplaisted** [comment]
It looks like the casing of this reference assembly changed between .NET 4.5.2 and .NET 4.6.

To resolve your issue, I'd suggest either retargeting to .NET 4.6 or higher, or changing your reference to match the casing in the package you are using, ie:

```xml
<Reference Include="System.XML" />
```

**Comment by kierenj** [comment]
Ok, thanks - but the build does work without issue on Windows.  Is that difference in behavior expected?

**Comment by dsplaisted** [comment]
Yes, Windows doesn't (generally) use a case sensitive file system.  I think the file name case was incorrect in .NET 4.5.2 and before, but it didn't lead to any issues on Windows.

**Comment by livarcocc** [comment]
@kierenj Did @dsplaisted suggestion fix the issue for you? If so, I would like to close this issue. I don't believe we will re-spin the package due to this.

**Comment by kierenj** [comment]
Apologies, I missed this response, I'll check it out with the next CI server push and report back asap

**Comment by kierenj** [comment]
@livarcocc @dsplaisted - Very strangely, I get the same warnings.  I've double-checked and the project file definitely contains:

```c#
<Reference Include="System.XML" />
```

However, for that project, and indeed 2 other projects (I hadn't noticed before) which *don't even reference System.Xml*, I get warnings:

```
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/XXX/YYY/src/XXX.YYYCore/XXX.YYYCore.csproj]
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3243: No way to resolve conflict between "System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Xml". Choosing "System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily. [/home/travis/build/XXX/YYY/src/XXX.YYYCore/XXX.YYYCore.csproj]
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/XXX/YYY/src/XXX.YYY.AzureCore/XXX.YYY.AzureCore.csproj]
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/XXX/YYY/src/XXX.YYY.Azure.Queues/XXX.YYY.Azure.Queues.csproj]
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/XXX/YYY/src/XXX.YYY.Email/XXX.YYY.Email.csproj]
```

I worked around the need to actually use System.Xml, but kept the reference in (as System.XML) for the main project for this issue.  The others are build for net451, but only reference System, then either System.IO or System.Runtime.

**Comment by livarcocc** [comment]
Given that this was a change to .NET Framework and that there is a workaround, I am going to close this issue. If I got this wrong, let me know and I can re-activate.

**Comment by kierenj** [comment]
@livarcocc I don't quite understand - what's the workaround?  I still get the same warnings?

**Comment by livarcocc** [comment]
adding @weshaggard and @joperezr are you guys aware of changes to System.XML in .net framework?

**Comment by weshaggard** [comment]
There isn't much we can really do to fix this warning, as we do not service targeting packs especially not for unsupported scenarios like yours. I assume you realize that using the Microsoft.TargetingPack.NETFramework.v4.5.1 package is an unsupported scenario, while it may work those packages are intended for usage in our build infrastructure only. There are issues filed to provide a first class supported scenario for this but we haven't yet funded that work.

**Comment by kierenj** [comment]
Oh ok - no I wasnt aware. Is xplat building for windows on linux not an officially supported thing? Of course I can live with warnings, but good to have an idea of the landscape

**Comment by weshaggard** [comment]
xplat building for .NET Framework is not an officially supported thing. We hope to make it supported in the future.
