### ISSUE TITLE
Cannot target uap10.0 apps with new TargetFrameworks syntax

### ISSUE THREAD

**Issue by mqudsi** [dotnet/sdk#1408]
Forgive me if this is already formally bugged somewhere, but while I've seen lots of references to uap10 targeting issues, I didn't come across an issues that specifically addressed `<targetframeworks>` support.

While in general the documentation for `TargetFrameworks` and the new .csproj format seems to be, shall we say, on the skimpier side; I'm unable to devise whether or not - in theory - targeting UAP10.0 should work in a multi-targeted csproj.

I know UWP/UAP support is a bit of a thorn in the side of the dotnet sdk and corefx teams, but it's very unclear as to how exactly it fits in to the picture.

A .NET library created with `<TargetFrameworks>netstandard1.3</TargetFrameworks>` can be consumed by a "legacy" UWP/UAP10 project, but there does not seem to be a way of creating a multi-targeted .NET library that includes a dependency on UWP.

Either UWP is a framework target, in which case `<TargetFrameworks>uap10.0</TargetFrameworks>` should work, or UWP is a .NET Standard target w/ access to Windows-specific and platform-specific libraries (which is what is most-heavily implied in the .NET Standard documentation). However, functionally that does not seem to be the case since a .NET Standard library (`<TargetFrameworks>netstandard1.3</TargetFrameworks>`) cannot install `microsoft.netcore.universalwindowsplatform` as a dependency.

We're left in a limbo state where it seems projects targeting UAP/UWP must use the legacy csproj format, because they're neither full-fledged framework targets nor do they have .NET Standard-compliant libraries.

**Comment by WinInsider** [comment]
UWP project can use new csproj format... see [here](UA-.NETStandardLibrary/SampleApplications/SDK/Opc.Ua.Server/Opc.Ua.Server.csproj )

**Comment by nickrandolph** [comment]
Any feedback on this? This is causing issues building multi-targetted class libraries where VS reports that the target framework is incorrect. Doesn't seem to matter whether you specify uap10.0 or uap10.0.XXXX

**Comment by livarcocc** [comment]
RIght now, the MSBuildSdkExtras is the only way to make this work, as suggested above. This is not natively supported in the SDK.

**Comment by mqudsi** [comment]
@livarcocc is there an intention to support it in the future, or has that not been decided?

**Comment by madelson** [comment]
Why is this closed? Has it been decided that this will never be supported?

**Comment by rolfik** [comment]
Is the official support planned and when should we expect it?

**Comment by gsantopaolo** [comment]
@dsplaisted  do you know if there is any plan to support uap in TargetFrameworks?

**Comment by livarcocc** [comment]
No plans at the moment to support this.

**Comment by MelbourneDeveloper** [comment]
@livarcocc what is hapening with this? Why won't it be supported?

**Comment by weitzhandler** [comment]
Very frustrating issue!

**Comment by MelbourneDeveloper** [comment]
@weitzhandler tell me about it! I've had to separately target UWP throughout [my library](https://github.com/MelbourneDeveloper/Device.Net). This should be fixed when .NET 5 is rolled out to all the platforms but there is no telling when that will happen.

**Comment by dsplaisted** [comment]
As noted up thread, there is an SDK you can use which helps with this: https://github.com/novotnyllc/MSBuildSdkExtras

**Comment by MelbourneDeveloper** [comment]
@dsplaisted I've tried using that and got nowhere

**Comment by weitzhandler** [comment]
UWP is among the best engineered technologies from Microsoft, yet is on the bottom of its priority list. What a shame.

**Comment by nickrandolph** [comment]
@MelbourneDeveloper UWP is definitely supported in multi-targeting, which from what I can tell is what you're trying to do with your library. What's not supported for UWP, Android, iOS, macOS is the new style sdk project for the head projects (ie the runnable application). This will of course need to be fixed in Maui timeframe (18mths or so).

**Comment by MelbourneDeveloper** [comment]
@nickrandolph are you able to point me to a sample csproj that targets both .NET Standard and UWP?

**Comment by nickrandolph** [comment]
yep sure - https://github.com/MvvmCross/MvvmCross/blob/23819a3ce1c3846c9d0307f935a18ef4657f51eb/MvvmCross/MvvmCross.csproj#L3
Also, I have a walk through for setting it up on a class library for use with Uno here:
https://nicksnettravels.builttoroam.com/uno-crossplatform-template

**Comment by MelbourneDeveloper** [comment]
@nickrandolph brilliant. Thanks.
