### ISSUE TITLE
Update host in SDK for compatibility with newer versions of Windows

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#14085]
We discovered that the .NET apphost is using a Windows API incorrectly and is broken on newer versions of Windows. We need fix this in supported SDK versions.

* [x] 3.1 SDK
* [x] 5.0 SDK
* [x] 6.0 SDK

Do we need to fix this for 2.1?

**Comment by vitek-karas** [comment]
2.1 didn't have the functionality is affected by the OS change - so the fix doesn't apply to that release. The functionality was first added in https://github.com/dotnet/sdk/commit/dcacdc04bae4a5f1cbca0976ea843d0911d13049#diff-463aa1b2b9760faacbd3769f02e36df8 and first "Shipped" in 3.0.100-preview.

**Comment by vitek-karas** [comment]
6.0 has been fixed in https://github.com/dotnet/runtime/pull/42444
5.0 has been fixed in https://github.com/dotnet/runtime/pull/43058
3.1 is pending triage https://github.com/dotnet/core-setup/pull/9092

**Comment by vitek-karas** [comment]
3.1 has been fixed in https://github.com/dotnet/core-setup/pull/9092
