### ISSUE TITLE
When consuming a .NET Standard 1.6 library from .NET Framework 4.6.1, the app is missing facades

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#1410]
## Repro Steps

1. Create a .NET Standard class library
2. Retarget to 1.6
3. Create a .NET Framework 4.6.1 console app
4. Add a reference to the class library
5. Add this statement to `Main`: `Console.WriteLine(new Class1());`
6. Run the console app

## Expected Results

Console app loads and prints `ClassLibrary.Class1`.

## Actual Results

You get this error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

It seems the problem is that no `System.Runtime` facade is copied to the output folder. Adding `<DependsOnNETStandard>True</DependsOnNETStandard>` to the console project solves the problem.

@dsplaisted

**Comment by terrajobst** [comment]
@dsplaisted mentioned that this might be related to #1410.

However, after installing the [latest nightly](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-win-x64.exe) it still doesn't work. Am I not testing the right bits or this is the bug somewhere else?

**Comment by weshaggard** [comment]
I'm seeing the same issue in my dogfooding.

**Comment by dsplaisted** [comment]
I took a look at this and it turns out that #1387 didn't get inserted into VS.  So you will see this issue if using full Framework MSBuild.  The fix will be inserted together with #1407 (which is currently in process).

**Comment by livarcocc** [comment]
We have merged the new MSBuild extensions into VS. This issue should be resolved in the latest VS. Please, re-activate if this still reproes.

**Comment by terrajobst** [comment]
Confirmed, no longer repros for me. Thanks!
