### ISSUE TITLE
 Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25513-02)

### ISSUE THREAD

**Issue by cartermp** [dotnet/sdk#1413]
1. Install CLI here: https://github.com/dotnet/cli/tree/release/2.0.0
2. `dotnet new sln`
3. `dotnet new console -lang F# -o FSConsole`

Expected: restores successfully.
Actual:

![fsharp-core-new-fail](https://user-images.githubusercontent.com/6309070/28224573-84325686-6884-11e7-9be0-16b28c8e3b32.PNG)

4. `dotnet new console -o CSConsole`

Expected: restores successfully.
Actual:

![csharp-core-new-fail](https://user-images.githubusercontent.com/6309070/28224768-318185be-6885-11e7-9804-a9292f214477.PNG)

Manual restore fails as well.

```
> dotnet --version
2.0.0-preview3-006764
```

Not sure if this is the right place to file it or not.

**Comment by nguerrera** [comment]
It's painful, but this will happen until release whenever you use a daily build that isn't "coherent". This causes the package versions in the offline feed to not match the implicit package versions that are referenced. Whenever you are using an "incoherent" build, you need to add this feed to a NuGet.config:

``` xml
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> in it and this should work.
```

See also  "Latest coherent build"  in https://github.com/dotnet/cli/blob/release/2.0.0/README.md. Currently it is 2.0.0-preview3-006692, which is before 2.0.0-preview3-006764 in repro above.
