### ISSUE TITLE
Build error after upgrading Blazor Wasm project to .Net 5 RC2

### ISSUE THREAD

**Issue by bancroftway** [dotnet/sdk#14154]
I have a Blazor Wasm project that I had already upgraded to .Net 5 RC1, and which was successfully building on local dev environment, as well as in our CI build pipeline.

However, after upgrading the project today to .Net 5 RC2, I am getting this build error:

`C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(934,5): error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target. [C:\Projects\DPlan\DPlan.Server.Infrastructure\DPlan.Server.Infrastructure.csproj]`

Here is the full output of command "dotnet build C:\Projects\DPlan\DPlan.Server\DPlan_Server.csproj -c Release -v q"
```
Microsoft (R) Build Engine version 16.8.0-preview-20475-05+aed5e7ed0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(934,5): error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target. [C:\Projects\DPlan\DPlan.Server.Infrastructure\DPlan.Server.Infrastructure.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(934,5): error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target. [C:\Projects\DPlan\DPlan.Server.Infrastructure\DPlan.Server.Infrastructure.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.05
```

In order to fix the above issue, I set a reference to nuget package "Microsoft.Windows.CsWinRT" in the DPlan.Server.Infrastructure.csproj file, which allows me to **build successfully from Visual Studio 2019 16.8.0 Preview 4.0**,  but building using "dotnet build" fails. However, if I remove the reference to ""Microsoft.Windows.CsWinRT" from this project, I cannot build from Visual Studio, nor "dotnet build".

Here is the entire contents of the project file DPlan.Server.Infrastructure.csproj
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>DPlan.Server.Infrastructure</AssemblyName>
    <RootNamespace>DPlan.Server.Infrastructure</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="3.1.1" />
    <PackageReference Include="EFCore.BulkExtensions" Version="3.2.4" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.15" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.7.15" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" Version="5.0.0-rc.2.20475.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.0-rc.2.20475.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0-rc.2.20475.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0-rc.2.20475.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="5.0.0-rc.2.20478.4" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.20.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DPlan.Server.AppLogic\DPlan.Server.AppLogic.csproj" />
  </ItemGroup>

</Project>
```

Please advise. Thanks

**Comment by mkArtakMSFT** [comment]
@dsplaisted do you know what may cause this? Thanks

**Comment by dsplaisted** [comment]
It looks like you're hitting this breaking change in .NET 5: [Built-in support for WinRT is removed from .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/interop#built-in-support-for-winrt-is-removed-from-net)

However, it also seems like the WASM project is trying to reference WinRT APIs, which I don't think would ever work.  Perhaps it is referencing a project that uses WinRT APIs in some cases but they weren't actually being called in the WASM app.  Is there a project or NuGet package you're using which is supposed to use WinRT?

If you can [share a binlog](http://aka.ms/binlog), that would also help investigate.

**Comment by bancroftway** [comment]
@dsplaisted @mkArtakMSFT  This issue got resolved this morning, after I upgraded the nuget package Microsoft.Windows.CsWinRT from 0.8 to 0.9. Thank you so much!
