### ISSUE TITLE
dotnet sdk 2.0 degrades shared projects experience in VS

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#1415]
**Before upgrading from 1.0.1 to 2.0**
Clone https://github.com/dotnet/symreader-converter
Sync to commit 98c41bf14a75994269df842b314c8a32d8e4aa3b.

Run ```restore.cmd``` and open SymReaderConverter.sln in VS.
![image](https://user-images.githubusercontent.com/41759/28233427-a7a3a684-68ab-11e7-9e2b-78cd517a7230.png)

**After upgrade**
Sync to PR https://github.com/dotnet/symreader-converter/pull/67.
Run ```git clean -xfd```, ```restore.cmd```, and open SymReaderConverter.sln in VS.

![image](https://user-images.githubusercontent.com/41759/28233531-568c6c80-68ac-11e7-87e2-ec39d68035c1.png)

Notice all the linked files that shouldn't be displayed in the project.

**Comment by tmat** [comment]
@nguerrera fyi

**Comment by nguerrera** [comment]
@dsplaisted

**Comment by nguerrera** [comment]
Looks like interference with https://github.com/dotnet/sdk/pull/1246

Does setting property SetLinkMetadataAutomatically to false work around it?

**Comment by dsplaisted** [comment]
Fixed with #1432
