### ISSUE TITLE
How to install/use CrossGen to optimize .NET Core Library as part of ci/cd?

### ISSUE THREAD

**Issue by ppittle** [dotnet/sdk#14169]
I am attempting to pre-jit/Ahead-Of-Time (AOT) compile a .NET Core 5 _Library_ to a Native Image using the CrossGen utility as [described here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/crossgen.md) to improve start up time.

However the instructions for [Getting CrossGen](https://github.com/dotnet/coreclr/blob/master/Documentation/building/crossgen.md) are vague:

> If you install CoreCLR using a NuGet package, you can find CrossGen in the tools folder of the NuGet package.

**How do I install CrossGen via NuGet?**

### What I've tried so far:

1. Create a build script that writes `deleteme.csproj` to disk and has a `<PackageReference Include="Microsoft.NETCore.App.Runtime.win-x64" Version="3.1.6" />`

2. Run `dotnet restore deleteme.csproj`.  This will download the Crossgen nuget package to local cache.

3. I can now run `~/.nuget/packages/microsoft.netcore.app.runtime.win-x64\3.1.6\tools\crossgen.exe`

**_NOTE:_** I know I can use the **ReadyToRun** feature for Self-Contained Deployment executable (as [described here](https://codetherapist.com/blog/netconf-netcore3-crossgen/)) HOWEVER I need to optimize a Class Library, so ReadyToRun doesn't work. 

### Problem

1. The [Nuget package has a big warning](https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-x64/3.1.6):
 
> Internal implementation package not meant for direct consumption. Please do not reference directly. 
2. Installation like this seems incorrect. I'd expect CrossGen to be installed as a [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) rather than needing to create a dummy project and run `dotnet restore` in order to download a copy of a nuget package in cache.

**Is there a correct way to pre-jit a .NET Core 5 _Library_ during a ci/cd build?**

**Comment by sandreenko** [comment]
Hi @ppittle, I believe if you add `<PublishReadyToRun>true</PublishReadyToRun>` property to your `csproj` file then SDK will automatically crossgen it, or, in Visual Studio you can choose it during publish steps:
![image](https://user-images.githubusercontent.com/22642771/101740556-d5f72900-3a7d-11eb-8d6a-9b43bb08d903.png)

However, I would ask @mangod9 about it.

**Comment by ppittle** [comment]
@sandreenko will this work on libraries?  I've seen `<PublishReadyToRun>true</PublishReadyToRun>` modify the binary for an executable, but when I tried it on  class library I couldn't see any changes to my built dll.

Did anything change with .net 5?

**Comment by dasMulli** [comment]
Class libraries shouldn't be crossgen'd as the very concept of cross-gening is specific to a runtime (..version) and target runtime identifier (e.g. win-x86 vs linux-arm64) so `PublishReadyToRun` is only supported when publishing an executable project for a specific runtime identifier.

**Comment by ppittle** [comment]
@dasMulli thanks for the clarification, I understand the vast majority of cases it wouldn't be necessary to AOT a library; any executable consumer of said library would AOT towards a specific runtime.  And trying to pre-jit a class library means you couldn't perform optimizations like tree-shaking.

However, I was looking at a plugin based design where class libraries would be discovered at run-time.  If I knew the platform ahead of time, or could provide separate builds for each supported runtime, then I could optimize the plugin code.  

We've completed the project so I can't take this much further, but thought I'd share the use case with you.

**Comment by mangod9** [comment]
R2R should work on libraries, for context all the .net libraries are crossgened themselves. Note that if R2R code is determined to be invalid for the platform, then the runtime should fall back to JITing. In .net 6 with crossgen2 we will also support a composite mode where apps can we published with all app+library code included in a single composite image.

**Comment by AntonLapounov** [comment]
`<PublishReadyToRun>true</PublishReadyToRun>` does work for libraries when targeting `netcoreapp3.1`, `net5.0`, and the upcoming `net6.0` framework.  If you run the following commands in an empty directory:
```cmd
dotnet new classlib
dotnet publish -p:PublishReadyToRun=True -c Release -r win-x64 -v:n
```
you will see the `crossgen.exe` command line. The `r2rdump.exe` utility can be used to see generated native code placed into the managed DLL.
