### ISSUE TITLE
How to adequately test multi-targeting netstandard libraries?

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#1416]
I have several class libraries that I ship on nuget.org that build with .NET SDK multi-targeting so I can support multiple .netstandard versions as well as several desktop framework versions. Even PCL or two in some cases.

How can I adequately test all these? I currently have a test project that also multitargets, but there's no way for me to test the netstandard1.0 build of my library on .NET Framework, for example, because the test project will use a build of the library that targets something more specific to net452, which is the minimum the VS test framework supports.

In one case I actually want to test the same library (that targets net45) under two configurations. Right now I'm faking it up by having the test project target net451 and net452 and switch a configuration file during the build for just one of them. But that technique doesn't work when I want to test a netstandard1.0 library under two configurations running on netcoreapp1.0.

I wish there were a way to use the `TargetFrameworks` MSBuild property with my own dimension added, sort of like this:

```xml
<TargetFrameworks>netcoreapp1.0*a;netcoreapp1.0*b;net45*a;net45*b;net46</TargetFrameworks>
```

Is there any thought on this?

**Comment by srivatsn** [comment]
Most of the project system allows for this. Currently only NuGet doesn't treat the targetframeworks as an alias (https://github.com/NuGet/Home/issues/5154). See https://github.com/dotnet/project-system/issues/1938#issuecomment-294324016 for more discussion on this.

**Comment by kdahltx** [comment]
I'm having the same issue. I have an extension library that is multi-targeted and it is being used by another library I'm creating that is also multi-targeted.

I can only install the multi-targeted extension library to a project that is targeting a specific platform but can't install it to another project that is multi-targeted.

**Comment by livarcocc** [comment]
Yeah, let's track it at #1561
