### ISSUE TITLE
UWP application cannot reference a multitarget netstandard library 

### ISSUE THREAD

**Issue by chrisdunelm** [dotnet/sdk#1418]
Very similar to #707.

Using VS2017 community 15.2 (26430.15) on Windows 10 Anniversary Edition.

A solution with a UWP application referencing a multi-targeted netstandard library produces the error on UWP project build: The target "GetPackagingOutputs" does not exist in the project. 

Steps to reproduce:
1. Create a new .NETStandard Class Library in a new solution.
2. Create a new Blank Universal Windows  app in the same project. Target/Minimum version: Anniversary Edition, Build 14393.
3. Edit the .NETStandard Class Library .csproj file to use `<TargetFrameworks>`, rather than `<TargetFramework>`. So the only `PropertyGroup` within the csproj now contains: `<TargetFrameworks>netstandard1.4</TargetFrameworks>`
4. Add a reference from the UWP application to the NETStandard library.
5. Rebuild the UWP application. It shows the error: The target "GetPackagingOutputs" does not exist in the project.

**Comment by chrisdunelm** [comment]
Just tried this on VS2017 community 15.3 preview 4.0; but with exactly the same result.

**Comment by tgjones** [comment]
The workaround described [here](https://github.com/dotnet/sdk/pull/908#issuecomment-288526468) appears to "fix" this issue, until the underlying bug is resolved.

**Comment by chrisdunelm** [comment]
Thanks, this workaround worked :)
