### ISSUE TITLE
Runtime Package Store

### ISSUE THREAD

**Issue by bleroy** [dotnet/sdk#14201]
# Runtime Package Store

Starting with .NET Core 2.0, it's possible to package and deploy applications against a known set of packages that exist on the target environment. The benefits in doing so are smaller deployments, lower disk space usage, and in some cases improved startup performance.

This feature is implemented by a runtime package store, which is a location on disk where packages are stored, and that the runtime can find, access, and use. That location is a *store* directory, next to the `dotnet` host. Under this directory, there are subdirectories for target frameworks, under which the package store follows a NuGet layout.

The second part of the implementation is a "target manifest", which is a list of packages that compose a runtime package store, and that developers can target when publishing their application. The target manifest is typically provided by the owner of the targeted production environment.

The feature is also used implicitly by ASP.NET applications: the set of packages composing the ASP.NET Web framework is installed as part of the setup packages authored by Microsoft. When publishing an ASP.NET application, the published application is trimmed to only include the application's packages, and not the framework's packages.

## Goals

- Smaller deployments
- Lower disk space usage
- Faster startup times

## Publishing an application against a target manifest

If you have a target manifest file on disk, you can specify it when publishing your app with the [`dotnet publish`](../tools/dotnet-publish.md) command:

```
dotnet publish --manifest path/to/the/target-manifest.xml
```

The resulting published application should only be deployed to an environment that has the packages described in the target manifest. Failing to do so would result in the application not starting.

It's possible to specify multiple target manifests when publishing an application. The application will then be trimmed for the union of packages specified in those target manifests.

## Specifying a target manifest in the project file

Instead of specifying a target manifest in a [`dotnet publish`](../tools/dotnet-publish.md) command, it's possible to specify the manifest or manifests to use in the project file as a semicolon-separated list of paths under a `TargetManifestFiles` tag.

```xml
<PropertyGroup>
  <TargetManifestFiles>path/to/the/target-manifest.xml</TargetManifestFiles>
</PropertyGroup>
```

This should only be done when the target environment for the application is well-known.

A different case would be an open-source project: the users of the project will likely deploy to a variety of different production environments, which may have different sets of packages pre-installed. Maintainers of the project can't make assumptions about the target manifest, and users should instead rely on the `--manifest` option of [`dotnet publish`](../tools/dotnet-publish.md) instead.

## ASP.NET implicit store

The default ASP.NET targets included with the `Microsoft.AspNetCore.All` meta-package include target manifests. As a consequence, `dotnet publish` of an ASP.NET application when it references this package will result in a published application that contains only the application and its assets, and not ASP.NET itself.

When an ASP.NET published application gets deployed, one should make sure that the target environment has ASP.NET installed, as the presence of .NET Core alone will not be sufficient.

If the application needs to be published to such an environment that doesn't include ASP.NET, it is possible to opt out of the implicit store by specifying a `PublishWithAspNetCoreTargetManifest` flag set to false in the project file, as you can see in the following example.

```xml
  <PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>
```

The ASP.NET runtime package store will be installed as part of the SDK packages distributed by Microsoft, and will also be available as a separate download so that any deployment environment can be prepared to receive published ASP.NET applications.

## Preparing a runtime environment

The administrator of a runtime environment can optimize for certain types of applications by building a runtime package store and the corresponding target manifest.

The first step is to create an XML file that describes the packages that must compose the runtime package store. The format of this file is compatible with the `csproj` format. Here's an example of such a file that adds `Newtonsoft.Json` and `System.Runtime.Serialization.Primitives` to the package store:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.1.1" />
  </ItemGroup>
</Project>
```

The runtime package store can then be provisioned by running a `dotnet store --manifest [target-manifest.xml] --runtime [runtime id] --framework [target framework]` command. Multiple file paths can be passed to a single [`dotnet store`](../tools/dotnet-store.md) command.

The output of the command is a package store under the `.dotnet/store` subdirectory of the user profile, unless a specific location has been specified using the `--output` option. The root directory of the store contains a target manifest `artifact.xml` file, that can be made available to be downloaded by application authors who want to target this store when publishing.

## Feedback

Please share your feedback.

**Comment by AraHaan** [comment]
> This feature was implemented in .NET Core 2.0. We have moved to a new scheme called "frameworks" that needs to be documented as part of .NET Core 3.0.

While that may be true, not everyone needs to put all of their packages into a custom framework (or well should).

While some might want to, others might instead want to use ``dotnet store`` for large packages that are not from Microsoft.

However, what if the packages already ship assemblies for runtime that are already crossgen2'd?

**Comment by richlander** [comment]
@Rick-Anderson -- good question but there isn't a real replacement for `store` to document. We never invested in that.

@AraHaan -- I sympathize. We haven't built a good replacement for `store`. 

Packages with R2R content should work and interact with servicing w/o issue. R2R has the same compatibility contract as IL. Perhaps I misunderstand the question.

**Comment by AraHaan** [comment]
Basically what I mean is as follows:

- Framework has System.Text.Json v6.0.5 (.NET 5 servicing release)
- Package 1 has System.Text.Json package dependency version v4.7.2
- Package 2 has System.Text.Json package dependency version v6.0.3

Which version would win in this case?

**Comment by richlander** [comment]
Ah, I see. We'd want 6.0.5 to be used.

It's possible that workloads could be extended to provide the deployment aspect for the assemblies. Today, the SDK knows about all the workloads (they are hard-coded). That's not a great long-term design. It blocks a number of scenarios.

Could you describe your scenario? That would help.

**Comment by AraHaan** [comment]
Sure, imagine you depend on nuget packages like Microsoft.Extensions.Hosting (or a package that brings in Microsoft.Extensions.Hosting and has a similar amount of packages it pulls in) which brings in a ton of nuget packages (some of which are needless because they are in the framework as well), as such one might want to offload those assemblies into an separate runtime and ref pack (perhaps make it into an custom workload locally) so that way their build output directories do not end up being 100+ MB in just package dependencies.

I might be exaggerating a little with the 100+ MB since the most on my projects is about 30 MB in just package binaries that gets copied, however some projects have it much worse than mine.

**Comment by richlander** [comment]
Totally get it. I meant higher level. If you can share, what is it that you are building where you experience these challenges?

**Comment by AraHaan** [comment]
A Discord bot.

**Comment by richlander** [comment]
Got it. Does this run on a server or a user machine? I assume the size would be less relevant on a server but perhaps I'm wrong.

I'm asking for detail so I can use this information to help motivate investing in this scenario. It's not that we haven't talked about. We have. It's a significant project, so we want to ensure there is enough need for it and (more importantly) we know which scenarios to target. We can also move getting more details on your project to email  if you'd like.

**Comment by AraHaan** [comment]
It's on my user machine that runs an local instance of SQL Server 2019 on Windows 11.

**Comment by richlander** [comment]
OK. I hear you saying your app is a good example of demonstrating this need, not that your users are specifically suffering from it currently. It would be great if we could get access to the source so that we could check this out for ourselves.
