### ISSUE TITLE
Update Analyzer with Code Fix template

### ISSUE THREAD

**Issue by Pzixel** [dotnet/sdk#1424]
I'm playing with Roslyn and wanted to create my first analyzer. It works fine, however, when I try to update NuGet packages in analyzer project I get an error because analyzer is supporting .net4.5 only while `Microsoft.CodeAnalysis.Common` 2.* doesn't. When I tried to migrate project manually to .net4.6 or .netstandard I encountered with several problems because I don't understand all switches and custom project sections in generated project and I only get multiple errors, and when I fix ones others comes. Here is #44 and #510 that are helpful in implementing it and it's a step in the same direction. I think that new `Update Analyzer with Code Fix` template must be a .netstandard project referencing packages 2.*. 

P.S. If here is a workaround how to perform such a transformation manually after project got generated it would be really helpful.

**Comment by livarcocc** [comment]
@tmat @jinujoseph what is the right repo for this issue?

**Comment by jinujoseph** [comment]
should be under https://github.com/dotnet/roslyn 
cc/ @jmarolf

**Comment by livarcocc** [comment]
This issue was moved to dotnet/roslyn#21012
