### ISSUE TITLE
dotnet test hangs/not same results when run multiple times

### ISSUE THREAD

**Issue by amolf-se** [dotnet/sdk#14244]
We noticed in our TeamCity that the ported unit tests from .NET Framework to .NET Core did not run properly. The test were started after compilation with the --no-build option. The test hung and the test process was terminated by the system. After removing the --no-build option one of the projects passed, but does not report the same amount of tests when run multiple times.
Another project continues to fail, with or without this option.
The solution consist of 100 projects, so sharing is not an option, I don't have a minimum set that demonstrates this behaviour.

**Comment by dsplaisted** [comment]
I think we probably need more information to try to figure out what's going on.  If you can [share a binlog](https://aka.ms/binlog) of the failure, that could help.

@nohwnd Any ideas?

**Comment by amolf-se** [comment]
Hi,



I created a binlog, and the result can be downloaded with the following link (for 7days). The command was:  dotnet test -bl --configuration Release

I hopr this clarifys some issues.



Groeten,



Marco









https://wetransfer.com/downloads/70b0dacd699adfd4ad97cc94184576ac20201109072252/135502e651ff9364bccdb02703a776b320201109072314/567f36



ing. Marco Konijnenburg | Head Software Engineering group
 AMOLF & ARCNL
Science Park 104, 1098XG Amsterdam, The Netherlands
P.O. Box 41883, 1009DB Amsterdam, The Netherlands
T. +31-20-7547100
http://www.amolf.nl | http://www.arcnl.nl


-----Original message-----

**Comment by nohwnd** [comment]
> After removing the --no-build option one of the projects passed, but does not report the same amount of tests when run multiple times.

Are you able to repro that locally using `dotnet test <path to the csproj that passes>`? Did all the tests in the project pass and it simply reports different counts of passed tests?

**Comment by amolf-se** [comment]
Hi,



Currently I cannot reproduce the same errors. On the commandline most times the test work. When run from teamcity they usually end with a timeout. I don't see the difference in starting the tests. The incorrect number of tests might have been due to miscalculation, there are over 10k of tests, in  about a dozen test libraries. Although there is a a total per library, there is not a total of all tests over all test in the solution displayed after running.





Groeten,





Marco



ing. Marco Konijnenburg | Head Software Engineering group
 AMOLF & ARCNL
Science Park 104, 1098XG Amsterdam, The Netherlands
P.O. Box 41883, 1009DB Amsterdam, The Netherlands
T. +31-20-7547100
http://www.amolf.nl | http://www.arcnl.nl


-----Original message-----
