### ISSUE TITLE
dotnetcli Release Index Version Mismatch on 5.0.0-rc.2 for aspnetcore-runtime

### ISSUE THREAD

**Issue by tonycoelho** [dotnet/sdk#14266]
@leecow @marcpopMSFT https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json has a bug where the latest-runtime is 5.0.0-rc.2.20475.**5**, but for aspnetcore-runtime it shows 5.0.0-rc.2.20475.**17**. See the json snippet below:

```
{
  "channel-version": "5.0",
  "latest-release": "5.0.0-rc.2",
  "latest-release-date": "2020-10-13",
  "latest-runtime": "5.0.0-rc.2.20475.5",
  "latest-sdk": "5.0.100-rc.2.20479.15",
  "support-phase": "rc",
  "lifecycle-policy": "https://www.microsoft.com/net/support/policy",
  "releases": [
    {
      "release-date": "2020-10-13",
      "release-version": "5.0.0-rc.2",
      "security": false,
      "release-notes": "https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.2.md",
      "runtime": {
        "version": "5.0.0-rc.2.20475.5",
        "version-display": "5.0.0-rc.2"
      },
      "aspnetcore-runtime": {
        "version": "5.0.0-rc.2.20475.17",
        "version-display": "5.0.0-rc.2",
        "version-aspnetcoremodule": [
          "15.0.20270.0"
        ]
      }
    }
  ]
}
```

**Comment by marcpopMSFT** [comment]
The core runtime and aspnet runtime come from different repos and so they have different final build numbers as they build separately. I just checked the final build for rc2 and can confirm that aspnet was the .17 version and the core runtime was .5 so these numbers appear to be correct from what I can tell.

**Comment by tonycoelho** [comment]
@marcpopMSFT I would still consider this a bug on the schema because the header value "latest-runtime" is 5.0.0-rc.2.20475.5. There is no header value for "latest-aspnetcore-runtime". In other versions of the manifest i.e. 3.1, the releases "version" matches the header "latest-runtime" whereas on rc.2 only the runtime version matches and not the aspnetcore-runtime version.
