### ISSUE TITLE
build.sh is broken

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#14263]
`build.sh` fails when trying to install .NET Core 1.0.5:

```
$  ./build.sh 
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-runtime-1.0.5-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.5/dotnet-runtime-1.0.5-linux-x64.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core Runtime` with version = 1.0.5
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

**Comment by sfoslund** [comment]
We use the build.sh script in our CI builds which are working fine, so this must be a configuration issue with your machine. It looks like you're missing some dependencies (`dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.`), I would recommend addressing those issues and seeing if that fixes it.

**Comment by tmds** [comment]
>  It looks like you're missing some dependencies

This is a known issue with the install script, it's a warning that may be ignored, see dotnet/install-scripts#6.

> We use the build.sh script in our CI builds which are working fine

What arguments are used in the CI build that make the script work?

**Comment by omajid** [comment]
And installing dependencies doesn't help: https://github.com/dotnet/sdk/issues/14992

**Comment by hangingman** [comment]
OK, I came here because of failure building dotnet cli
