### ISSUE TITLE
NuGet error codes hyperlink

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#1426]
The NuGet errors hyperlink currently goes to:
```
https://msdn.microsoft.com/en-us/library/dd831853(v=vs.140).aspx?appId=Dev15IDEF1&l=EN-US&k=k(NU1603)&rd=true
```
which ends going to a VS 2015 msdn page in the end. 

![warnings](https://user-images.githubusercontent.com/2878341/28383649-bd0cda8a-6c76-11e7-9c33-e85e78719b55.png)

One option is to make this on par with the CSC errors and search on bing. 

For example CS1002 goes to:
```
https://www.bing.com/search?q=CS1002+C%23+%3b+expected&form=VSHELP&redir=5
```
@natidea @mishra14 @anangaur

**Comment by anangaur** [comment]
I like the idea of using the bing url searching for each warning/error code. This has 2 benefits:

1. We do not need to bind it to any fixed URL of a FWD link and hence no maintenance issues going forward if the documentation pages move
2. Users may not be just interested in official warnings/errors definition but general use-cases, workarounds from the community like stackoverflow that can help them.

The documentation of these warnings is in progress and once more and more people go to these pages and is indexed by Bing, the page can start showing up in the search results.

**Comment by anangaur** [comment]
Adding to the above, I also feel this should be fixed for 15.3 RTW

**Comment by srivatsn** [comment]
Doing this will require a CPS change since CPS reports the error to the error list and crafts the URL. Please file an internal bug against CPS.

**Comment by livarcocc** [comment]
Is there work here on the SDK side?

**Comment by srivatsn** [comment]
Depends on how CPS implement it but i'd say close this out and if anything's needed it'll likely be about setting some property or another.
