### ISSUE TITLE
when rebuild a new winformsApp by using targetFramework .Net5.0, it shows error that is showed in comment below.

### ISSUE THREAD

**Issue by liyanligt** [dotnet/sdk#14279]
when rebuild a new winformsApp by using targetFramework .Net5.0, it shows error that "	NETSDK1136	The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.	WindowsFormsApp1	C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets".
When I changed the targetFramework to .Net3.1, the error disappeared.

The infomation of sdk and runtime is below:
Visual Studio support
Visual Studio 2019 (v16.8, Preview 4)
Included runtimes
.NET Runtime 5.0.0-rc.2.20475.5
ASP.NET Core Runtime 5.0.0-rc.2.20475.5
.NET Desktop Runtime 5.0.0-rc.2.20475.5

Do you have found this qustion ? and  how to solve this problem? Thank you very much!

**Comment by dbulic** [comment]
See https://developercommunity.visualstudio.com/content/problem/1218104/cannot-compile-wpf-applications-targeting-net-5.html

**Comment by wli3** [comment]
+1 on @dbulic 's like. And the error message is correct. Just follow the error message's instruction.

**Comment by liyanligt** [comment]
Thank you very much , it has been solved by changing targetframework to net5.0-windows。
![image](https://user-images.githubusercontent.com/53420736/97260311-a686b700-1857-11eb-907a-7686dcc43b17.png)
https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

**Comment by peterdrier** [comment]
> Thank you very much , it has been solved by changing targetframework to net5.0-windows。

This isn't actually a solution, as you're fundamentally changing the target of the application to Windows Only.  If you are trying to do cross platform work, it still doesn't work.

**Comment by AraHaan** [comment]
> 
> 
> > Thank you very much , it has been solved by changing targetframework to net5.0-windows。
> 
> This isn't actually a solution, as you're fundamentally changing the target of the application to Windows Only. If you are trying to do cross platform work, it still doesn't work.

I also got a case where I make a copy of a library with usage of windows forms and a copy without by optionally defining ``WITH_WINFORMS`` and have also changed mine recently to support .net 5 by doing the following:

1. adding net5.0 AND net5.0-windows
2. having all of the gui stuff as a common props files that gets imported and controlled by an ``UseGUIFramework`` control switch that only references the sdk for winforms/wpf or if targeting .net framework the reference to the .net framework dll file.
3. adding this to the csproj file ``UseGUIFramework Condition="'$(TargetFramework)' != 'net5.0'">true</UseGUIFramework>``
4. adding a check for if it is .NET 5+ that it would exclude those TFMs if they do not end with ``-windows``.

And then now it compiles as then the .net 5 version would not define ``WITH_WINFORMS``.
