### ISSUE TITLE
Testing multitargeted assemblies

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#1427]
Many test runners (like xunit) have suggested multitargeting your test assemblies to test on multiple frameworks. But VS does not let you actually run tests on the framework of your choice, which makes testing very difficult, if not impossible.

This will eventually affect every compiler test, so please treat this as an issue affecting every Roslyn compiler dev.

**Comment by nguerrera** [comment]
This is tracked by https://github.com/Microsoft/vstest/issues/624

There's nothing needed in this repo to make VS do as command line runners do and let you pick a target framework or run against all target frameworrks.

**Comment by tannergooding** [comment]
@nguerrera, I think there is still some benefit in having a 'target netstandard', 'publish against * framework' functionality in the CLI and in the SDK.

Even if VSTest ends up supporting multi-targeting, that doesn't negate the fact that we are building and publishing the project twice, when it really only needs to be built once and published twice.

**Comment by nguerrera** [comment]
@tannergooding 100% agree, but it's a different feature than what is requested here. It is also being tracked. Let me chase down the bug numbers....
