### ISSUE TITLE
Turn Nullable on for new projects

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#14272]
We want to set `<Nullable>Enabled</Nullable>` for new projects.

We probably don't want to infer this as part of the TFM and instead make it part of the project template. Otherwise retargeting becomes a major hurdle.

**Comment by samsp-msft** [comment]
@cartermp - who is the dev for this?

**Comment by cartermp** [comment]
Nobody yet, but it's trivial to do the work to change the templates. The issue is more if everything else - libraries, app frameworks, etc. - can handle it being on by default for new projects.

**Comment by terrajobst** [comment]
@KathleenDollard AFAIK this is completed now, right>
