### ISSUE TITLE
dotnet restore on a VM breaks my internet connection and fails with errors

### ISSUE THREAD

**Issue by Loreno10** [dotnet/sdk#14290]
I have a Windows 10 as a host and a Pop! OS 20.04 installed using Hyper-V (enhanced session enabled, if that matters).

In the VM I have installed dotnet-sdk-3.1 and https://github.com/microsoft/artifacts-credprovider (since my dotnet project uses private NuGet feeds).

I have a .NET Core project inside of the Pop! OS VM. I'm trying to restore the dependencies using `dotnet restore`. As soon as I invoke that command, my internet connection breaks (both in the VM and the host). 
The `dotnet restore` itself throws lots of errors like this one:

> The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: Connection reset by peer.

Sometimes there are also timeouts.

When I do `dotnet restore --interactive` the only difference is that initially I am asked to perform DEVICE authentication in the browser by providing some code. After that the same issue happens.

The only thing that helps in that situation is to stop the `dotnet restore` process and to turn off and turn back on my wi-fi connection (in the host). Only that restores my internet connection.

I tried the same steps multiple times:

1. Run `ping 8.8.8.8` in one terminal window (on Pop! OS)
2. Run `dotnet restore` in the other terminal window (on Pop! OS)

Around 2 seconds after I do the second step, ping from the first terminal stops receiving responses.

What could be wrong? My VM uses the "Default Switch" of Hyper-V. I did not do any special network setup. It's just a fresh installation of Pop! OS 20.04.

The same project resolved completely fine on my host and on an Ubuntu VM.

**Comment by marcpopMSFT** [comment]
@zkat @nkolev92 something ya'll have seen in NuGet?  Seems like it wouldn't likely be a CLI issue as NuGet would be handling any network calls.

**Comment by nkolev92** [comment]
I've seen reports of this nature before, but we've rarely managed to get to the bottom of it, since it usually is a configuration problem.

https://github.com/NuGet/Home/issues/10057 is the closest recent thing. 

@Loreno10 Can you try `--disable-parallel-processing`? 
https://github.com/NuGet/Home/issues/9020 is docker and has a different failure message, but that might give us a hint about what's going on.

**Comment by marcpopMSFT** [comment]
This issue was moved to NuGet/Home#10292
