### ISSUE TITLE
Support a 'PublishFrameworks' property so that code can be compiled once and published for multiple runtimes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/sdk#1429]
Imagine you have a library that targets netstandard. Today, if you want to create a test project for this library and you want to run those tests against 2 or more runtimes, you have to multi-target.

However, multi-targeting in this scenario is inefficient, as it requires the code to be compiled twice when it could otherwise be compiled once.

We should expose a 'Publish Frameworks' property that allows you to take the code that was compiled for a given framework and publish it against multiple target runtimes (thereby reducing this down to just copying dependencies).

So, for example:

Product Code: TargetFramework=netstandard2.0
Test Code: TargetFramework=netstandard2.0, PublishFrameworks=net461;netcoreapp2.0

Product code is compiled once, producing a netstandard2.0 library
Test code is compiled once, producing a netstandard2.0 library
Test code is published twice, copying the netstandard2.0 output in both cases and creating a net461 deployment and a netcoreapp2.0 deployment

Restore on the Test Code project should restore packages for all three frameworks

**Comment by tannergooding** [comment]
FYI. @nguerrera

**Comment by srivatsn** [comment]
This will be needed for https://github.com/Microsoft/vstest/issues/926#issuecomment-314607661
