### ISSUE TITLE
How  to solve the error ：NETSDK1136

### ISSUE THREAD

**Issue by liyanligt** [dotnet/sdk#14297]
The infomation of error is below:
The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets

Could you help me? Thank you very much, and best wishes for you!

**Comment by liyanligt** [comment]
See https://developercommunity.visualstudio.com/content/problem/1218104/cannot-compile-wpf-applications-targeting-net-5.html

**Comment by peterdrier** [comment]
> See https://developercommunity.visualstudio.com/content/problem/1218104/cannot-compile-wpf-applications-targeting-net-5.html

That link states fixed, yet I'm still having the problem in 16.8.4..

**Comment by rostacik** [comment]
https://stackoverflow.com/questions/64786573/need-help-migrating-winform-to-net-5 - would **<TargetFramework>net5.0-windows</TargetFramework>** do the job? worked for me.

**Comment by peterdrier** [comment]
Yes but no..  -windows breaks the VS WSDL connector which only works in net5.0..    Switching back and forth got me through it though.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/110943242-f503a080-8375-11eb-89ff-7a50e7501df5.png)

**Comment by nitan2001** [comment]
It works with 
<TargetFramework>net5.0-windows</TargetFramework>

**Comment by nitan2001** [comment]
It works with 
\<TargetFramework\>net5.0-windows\</TargetFramework\>

**Comment by Camilozam** [comment]
For example if one is developing for deploying on Linux the project file may include <TargetFramework>net5.0</TargetFramework>

But if developing for a Windows environment the project file may include
<TargetFramework>net5.0-windows</TargetFramework>

So if one is aiming for net5.0 but using a library targeting net5.0-windows this error would show up.

**Comment by IAbstract** [comment]
Are we just pretending the last comment does not exist?

I've a WPF project references a domain project with non-Windows objects - models, view-models, etc. VS 2022 complains that the domain project must reference `-windows` in the target framework. Why? It's not targeting Windows.

I cannot even run unit tests on view models and other domain objects because the testing project complains that it must target `-windows`.

**Comment by TomSyk** [comment]
In project file (.csproj) you have to definition OutputType (for example  <OutputType>Library</OutputType>). If not you got the error

**Comment by Ken-Andre** [comment]
> For example if one is developing for deploying on Linux the project file may include net5.0
> 
> But if developing for a Windows environment the project file may include net5.0-windows
> 
> So if one is aiming for net5.0 but using a library targeting net5.0-windows this error would show up.

so how can we do if we use both system to do a project?
