### ISSUE TITLE
Project with 0 NuGets: "Assets file 'path_to_prj\obj\wappublish\win-x64\project.assets.json' not found. Run a NuGet package restore to generate this file"

### ISSUE THREAD

**Issue by ccornici** [dotnet/sdk#14314]
Simply follow `demo.mp4` in this repo (open project -> Publish -> error)

**This prevents package publishing**

https://github.com/ccornici/dotnet_build_failure_msix

![bug](https://user-images.githubusercontent.com/15718751/97069069-a96e7700-15cd-11eb-852a-5fc3cfa23937.gif)

So I ended up fiddling with this for hours and I got it to generate an wappublish for x86, then copy it outside the folder, then got it to generate (by modifying build targets) a wappublish for x64 (with missing x86, obviously), and then copied back the x86 manually, then built again. Here's the new error, delightful:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "prj_path\bin\x86\Release\netcoreapp3.1\win-x86\prj.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	Packaging	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2085`

**Comment by ccornici** [comment]
I copied the build targets from my actual project which fails......and now the the test project above works.......

What I added to the csproj is:

```	
<PropertyGroup>
     <-- existing stuff -->
    <Platforms>x64;x86</Platforms>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```


Again, this is copy pasted from the almost identical main project, which still consistently fails to build....and now with this in the test project, the test project builds...same nugets, same build targets.....so confusing

**Comment by ccornici** [comment]
OK, so I copied all the files over from my min project to the test project above, until they looked 99% identical, then I saw that the main project had a difference in the .sln, which was that Debug an dRelease, x86 and x64, were set to Any CPU, instead of being set to x86 and x64 respectively. This, and the above PropertyGroup changes, we're what I did to fix it....

**Comment by sefinek** [comment]
# Example

## csproj
https://github.com/sefinek/Sefinek-Blocklists-App/blob/main/SefinekBlocklists/Sefinek%20Blocklists%20App.csproj

## sln
https://github.com/sefinek/Sefinek-Blocklists-App/blob/main/SefinekBlocklists.sln
