### ISSUE TITLE
PublishSingleFile alter deps.json or contents as part of PostBuildEvent before compressing the single .exe

### ISSUE THREAD

**Issue by lastlink** [dotnet/sdk#14327]
This is a follow up on https://github.com/dotnet/sdk/issues/13894
* i've determined that you can override a the console dll through the `\obj\Release\netcoreapp3.1\win-x64\targetdll` and referenced internal projects through `referencedproject\bin\Release\netcoreapp3.1\win-x64\targetdll` in a postbuild step in the csproj that is called before trimming and generating the single .exe
* however, this seems to be the only thing you can override
* I have found a tool that allows me to merge my dlls and it generates a new deps.json file after merging. if I call `dotnet merged.dll` then the project works properly, however I use this new merged dll inside of the postbuild b/c the **deps.json** needs to be overwritten before generating the singleapp
* tried to override the single app **deps.json** in the obj and bin folder and it still uses the generated original one.
* I've been verifying this after runnign the dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true /p:rId=win-x64
* opening the exe in the publish folder and verifying the contents in `C:\Users\%USERNAME%\AppData\local\Temp\.net`

## Code

project.csproj
```xml
<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="$(ConfigurationName) == Release AND $(rId) != ''">
    <Exec Condition="$(OS) == Windows_NT" Command="set TargetName=$(TargetName)&#xD;&#xA;set rId=$(rId)&#xD;&#xA;set TargetDir=$(TargetDir)&#xD;&#xA;..\scripts\build.cmd" />
    <Exec Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' OR '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'" Command="export TargetName=$(TargetName)&#xD;&#xA;export rId=$(rId)&#xD;&#xA;export TargetDir=$(TargetDir)&#xD;&#xA;bash ../scripts/build.sh" />
  </Target>
```

build.cmd
```cmd
copy "..\Release\pre\publish\%TargetName%.dll" ".\obj\Release\netcoreapp3.1\%rId%\%TargetName%.dll" /y
copy "..\Release\pre\publish\%TargetName%.deps.json" ".\bin\Release\netcoreapp3.1\%rId%\%TargetName%.deps.json" /y
copy "..\Release\pre\publish\%TargetName%.deps.json" ".\obj\Release\netcoreapp3.1\%rId%\%TargetName%.deps.json" /y

echo ":::end post build:::"
```

**Comment by lastlink** [comment]
As far as I can tell I need to tweak my build targets to use `IntermediateDepsFilePath` or `PublishDepsFilePath`

**Comment by lastlink** [comment]
One thought I had was to build my combined dll and reference the merged dll directly, then maybe the sdk build would use that alterned final dll.

**Comment by marcpopMSFT** [comment]
Closing as the linked issue indicated you had solved your set of issues. Please reactivate if there is still something you need help with.
