### ISSUE TITLE
.Net Standard 2.1 support with UWP

### ISSUE THREAD

**Issue by amitagrawalhyd** [dotnet/sdk#14320]
We have a UWP application where we are planning to use Microsoft.Data.SqlClient with "Column Encryption Setting=enabled" option. But unfortunately in .Net Standard 2.0 "Column Encryption Setting=enabled" option is not supported and .Net Standard 2.1 which works fine with "Column Encryption Setting=enabled" option is not supported to any of the UWP version.

**Comment by joeloff** [comment]
This issue was moved to dotnet/SqlClient#791
