### ISSUE TITLE
The UWP API Package.InstalledLocation.Path takes too much time on Windows 10.19041.572

### ISSUE THREAD

**Issue by mingtong** [dotnet/sdk#14335]
OS version: 2004,
build number: 19041.572

When I call this API on one of the mentioned Windows 10, it takes about 4~5 seconds.
But it doesn't reproduce on my own Windows 10(same build same version).

Any one have ran into this issue?

**Comment by sfoslund** [comment]
This issue was moved to microsoft/Windows-universal-samples#1258
