### ISSUE TITLE
dotnet restore hangs indefinitely

### ISSUE THREAD

**Issue by emgarten** [dotnet/sdk#1434]
_From @davkean on July 10, 2017 23:58_

_From @richlander on July 3, 2017 20:57_

See:

- https://github.com/dotnet/core/issues/711#issuecomment-312688873
- https://github.com/dotnet/core/issues/711#issuecomment-312708156

/cc @rrelyea

_Copied from original issue: dotnet/core#724_

_Copied from original issue: NuGet/Home#5583_

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @MathiasKowoll on July 3, 2017 22:45_

I looked that while having many libs in the folder wwwroot\lib dotnet restore takes a while to restore the files, If I remove that folder it restores immediately.

This happens with al dotnet commands. CLI and Visual Studio 2017 Preview 3

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @dsyme on July 4, 2017 22:22_

I put a full process dump of a hung dotnet.exe here: https://1drv.ms/u/s!Aq5gXOPBI5HdiroRLPy1hDY3yK80kQ

```
C:\GitHub\misc>dotnet --version
2.0.0-preview2-006497
```

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @dsyme on July 4, 2017 23:5_

I eventually realised that I had a very large number of files in the subdirectories under the ``c:\misc`` in which I was running "dotnet".  The c:\misc directory itself contained just the results of a ``dotnet new``. The subdirectories included Git repos and much more - 20,000 files and 1.6GB

Now, it's my belief that the presence of these files shouldn't have caused problems for a simple ``dotnet restore`` but it seems they did.

I tried to procmon.exe the activity of dotnet.exe but the trace was large.  The screenshot below showed that it is indeed accessing all the subdirectories,  In this case, it seemed like the thing just never terminated, I don't know what it was doing though o all those blocked threads

![capture](https://user-images.githubusercontent.com/7204669/27844140-7e416f12-6115-11e7-82b8-73867b574ed0.PNG)

Anyway, I think the bug here is that running ``dotnet.exe`` in a folder containing 1GB of misc files in subdirectories either takes a very long time or simply doesn't terminate

Now I know that I can get on with the rest of my work :)

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @Petermarcu on July 7, 2017 7:43_

@rrelyea should this get moved to the nuget repo to get tracked?

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @Lanayx on July 7, 2017 9:1_

I got the same issue. For me the problem was that new _dotnet restore_ (from dotnet-sdk-2.0.0-preview2-006497-win-x64) ignores disabledPackageSources configuration in NuGet.Config, and I had some of them unreachable. Removing these sources helped.

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @richlander on July 7, 2017 13:53_

@Petermarcu I was going to make @ https://github.com/NuGet/NuGet.Client but issues are not enabled.

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @Petermarcu on July 7, 2017 15:24_

@richlander you make it on the nuget/home repo

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @forki on July 7, 2017 18:0_

Same issue here: https://github.com/fable-compiler/Fable/issues/1042

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @rrelyea on July 7, 2017 18:22_

Working on creating NuGet/home issues ... will link when created. 
Update: Actually, I lied...let's drill into these 2 issues a bit first...

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @rrelyea on July 7, 2017 18:24_

@dsyme  - in dotnet cli v1 previews, we used to walk all the sub directories. I had thought we changed that when we switched to make restore recursive (across project references) by defeault. do you have the same problem if you do a "dotnet restore --no-dependencies" in that same directory?

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @rrelyea on July 7, 2017 18:25_

@MathiasKowoll - can you please give me repro steps for your problem (full details), and how you avoided it.

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @rrelyea on July 7, 2017 18:34_

@forki - I am unable to repro.
after you have done dotnet new, a restore should have already been completed. 
when you do a build, it will also do a restore, if it deems that one is necessary.
Can you please file an issue in NuGet/Home about the issue you are seeing, with repro steps (including setup steps if necessary?

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @MathiasKowoll on July 7, 2017 18:49_

@rrelyea create mvc app with individual authentication.

replace bower.sjon with the following.

{
  "name": "ItsomaxCms",
  "private": true,
  "dependencies": {
    "jquery": "^3.2.1",
    "jquery-ui": "1.12.1",
    "bootstrap": "^3.3.7",
    "font-awesome": "4.3.0",
    "jquery-validation": "1.16.0",
    "jquery-validation-unobtrusive": "3.2.6",
    "datatables.net": "^1.10.15",
    "datatables.net-bs": "^2.1.1",
    "datatables.net-buttons": "^1.3.1",
    "datatables.net-buttons-bs": "^1.3.1",
    "datatables.net-fixedheader": "^3.1.2",
    "datatables.net-fixedheader-bs": "^3.1.2",
    "datatables.net-keytable": "^2.2.1",
    "datatables.net-responsive": "^2.1.1",
    "datatables.net-responsive-bs": "^2.1.1",
    "datatables.net-scroller": "^1.4.2",
    "datatables.net-scroller-bs": "^1.4.2",
    "pdfmake": "^0.1.29",
    "echarts": "^3.6.1",
    "smartwizard": "latest",
    "fastclick": "latest",
    "nprogress": "latest",
    "ionicons": "latest",
    "slim-scroll": "latest",
    "icheck": "latest",
    "switchery": "latest",
    "bootstrap-table": "latest",
    "tableExport.jquery.plugin": "latest",
    "x-editable": "latest"
  },
  "resolutions": {
    "jspdf": "1.1.239 || 1.3.2"
  }
}

make bower install

run dotnet restore.

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @forki on July 7, 2017 18:51_

@rrelyea thanks for looking into this. I notified the original author of the issue. We have multiple people reporting this on the fable gitter chat. I assume it's related to node_modules and dotnet restore iterating long time over it

**Comment by emgarten** [comment]
_From @davkean on July 10, 2017 23:58_

_From @forki on July 7, 2017 19:24_

Seems that things worked with preview1 see https://github.com/fable-compiler/Fable/issues/1042

**Comment by emgarten** [comment]
_From @forki on July 11, 2017 6:0_

I don't think it's nuget issue since we also see slow behavior in dotnet build.

**Comment by emgarten** [comment]
_From @mikkeljohnsen on July 11, 2017 19:34_

If I install "kendo-ui-core" through bower "dotnet build" will hang indefinitely.

If I delete "wwwroot/lib/kendo-ui-core/" it will build again.

Please fix this ASAP, so we can get on with development.

**Comment by emgarten** [comment]
_From @mishra14 on July 11, 2017 19:40_

Tagging @emgarten for restore visibility.

@forki @mikkeljohnsen : Are you seeing an indefinite hang in  `dotnet restore`  as well?

**Comment by emgarten** [comment]
_From @mikkeljohnsen on July 11, 2017 20:16_

@mishra14  dotnet restore is not indefinitely but takes about 5 minutes.
and dotnet build is also not indefinitely from the command line it takes about 5 minutes as well.
(did not wait that long before)

**Comment by emgarten** [comment]
_From @forki on July 11, 2017 20:20_

The same is happening on azure now. This issue spreads.https://github.com/dotnet/core/issues/724#issuecomment-314487750

**Comment by emgarten** [comment]
This appears to be an issue with msbuild file globbing in the project on dotnet CLI. MSBuild in desktop does not have this issue. I also don't see any changes to the SDK around the props including these.

Using the bower.json file above here are the numbers I am getting:

| Scenario | Time |
| -------- | ----- |
| dotnet msbuild /t:clean | 56s |
| dotnet build --no-restore | 60s |
| dotnet restore | 167s |
| dotnet restore /p:EnableDefaultItems=false | 2s |
| (desktop) msbuild /t:restore | 3s |

Restore appears to make the existing problem worse, there may be a target that is changing properties and causing things to be evaluated additional times. I'll take a look at what can be improved there. The main issue appears to be the time globbing takes, the project should not take this long to evaluate just to return the project and package references that restore needs.

### Workaround

`dotnet restore /p:EnableDefaultItems=false`

*EnableDefaultItems=false* will disable globbing for project directory files during restore.

**Comment by emgarten** [comment]
_From @mikkeljohnsen on July 13, 2017 18:25_

EnableDefaultItems=false. Will also disable all items in VS (Mac). So not really useful.

And VS (Mac 7.1 build 1281) Still hangs on "Run" (Build)

**Comment by emgarten** [comment]
@mikkeljohnsen `EnableDefaultItems=false` should only be used with restore where the items are not needed. For build you will of course still need them, there you can run with `--no-restore` to speed things up.

**Comment by emgarten** [comment]
_From @forki on July 13, 2017 18:34_

@emgarten is there a fix to see on the horizon?

**Comment by emgarten** [comment]
@forki not yet, it is still being investigated. I'll keep you posted.

**Comment by emgarten** [comment]
_From @mikkeljohnsen on July 13, 2017 19:56_

@emgarten "dotnet build --no-restore" still takes more than 1 minute for a simple project with kendo-ui-core installed. And from VS (Mac) it is not able to compile at all.

Hope there will be a fix very soon. Because only solution is to downgrade to preview1

**Comment by emgarten** [comment]
_From @dsplaisted on July 18, 2017 23:35_

I think I've figured out what is causing this, and you should be able to workaround it for now by setting the `SetLinkMetadataAutomatically` property to `false` in your projects.

**Comment by emgarten** [comment]
@dsplaisted is there an issue tracking the work needed for this? Is it going to be on the SDK side?

**Comment by emgarten** [comment]
_From @mikkeljohnsen on July 19, 2017 10:23_

@dsplaisted Thanks that works.

**Comment by livarcocc** [comment]
We took a fix today in MSBuild to address this.

**Comment by rainersigwald** [comment]
^ specifically, https://github.com/Microsoft/msbuild/pull/2326.

**Comment by mishra14** [comment]
Should this be closed then?

**Comment by livarcocc** [comment]
Yes. Closing.

**Comment by joshudson** [comment]
@livarcocc : It appears your fix didn't make it to the cross-platform version of msbuild; the problem still exists on non-Windows build architectures the moment the <RuntimeIdentifiers> tag is added to the project file.

**Comment by rainersigwald** [comment]
@joshudson Can you please file a new issue at https://github.com/Microsoft/msbuild/issues/new with details on how to reproduce your problem? The fix for this old bug applied equally to all OSes.

**Comment by joshudson** [comment]
@livarcocc : Well that was spooky. The problem doesn't exist today. I wonder if the nuget servers were sick yesterday.
