### ISSUE TITLE
[loc] Please lock the resource, so it is not localized.

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#14362]
Regarding this issue: https://github.com/dotnet/sdk/issues/14001
Please lock the resource using the xlif "<note>" to add the dev comment "{Locked}". Eg "<note>{Locked}</note>

**Comment by sfoslund** [comment]
@vijayrkn this looks like a websdk issue

**Comment by vijayrkn** [comment]
@sfoslund - Yes, I will take care of this. Thanks!
