### ISSUE TITLE
How to resolve NU1202: Package Microsoft.Xaml.Behaviors.Wpf 1.1.19 is not compatible with net50-windows (.NETFramework,Version=v5.0,Profile=windows). Package Microsoft.Xaml.Behaviors.Wpf 1.1.19 supports:

### ISSUE THREAD

**Issue by mageshsankar** [dotnet/sdk#14371]
After installing the latest preview, we noticed our WPF apps targeting net50-windows will not compile. We tried to create a new project from scratch and hit the same issue. The simple project file is defined below:

```
<PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```
Cannot restore Microsoft.Xaml.Behaviors.Wpf 1.1.19 package

**Comment by Abdullah0820** [comment]
> After installing the latest preview, we noticed our WPF apps targeting net50-windows will not compile. We tried to create a new project from scratch and hit the same issue. The simple project file is defined below:
> 
> 
> 
> ```
> 
> <PropertyGroup>
> 
>     <OutputType>library</OutputType>
> 
>     <TargetFramework>net5.0-windows</TargetFramework>
> 
>     <UseWindowsForms>true</UseWindowsForms>
> 
>     <UseWPF>true</UseWPF>
> 
>     <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
> 
>   </PropertyGroup>
> 
> ```
> 
> Cannot restore Microsoft.Xaml.Behaviors.Wpf 1.1.19 package

**Comment by mageshsankar** [comment]
Hi @marcpopMSFT 

Any update on this.

Thanks

**Comment by marcpopMSFT** [comment]
We'll be discussing in triage tomorrow but I suspect that the Behaviors package being referenced needs to be updated to target 5.0

**Comment by mageshsankar** [comment]
Okay waiting for your suggestion

Thanks

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/XamlBehaviorsWpf#80
