### ISSUE TITLE
Sdk should use $(ProjectAssetsFile) always, never reset it, and never assume it is named project.assets.json

### ISSUE THREAD

**Issue by tannergooding** [dotnet/sdk#1438]
Currently the `project.assets.json` for a project is defaulted to be `$(BaseIntermediateOutputPath)\project.assets.json` (where `$(BaseIntermediateOutputPath)` defaults to `obj`).

This makes it such that two projects can no longer exist in the same folder by default (and will also cause conflicts if the user unwittingly updates `$(BaseIntermediateOutputPath)` to be shared across all projects in the solution, as can be done with `$(BaseOutputPath)`, rather than ensuring that it remains unique per-project).

I propose that the `project.assets.json` file be updated to include either `MSBuildProjectName` or `AssemblyName` (in other places in the SDK, `AssemblyName` seems to be the preferred prefix) by default or for a switch to be added to easily enable this functionality.

**Comment by nguerrera** [comment]
This is tracked by https://github.com/NuGet/Home/issues/4463

But there may be SDK fallout: 

* There's hard-coding of projects.assets.json in the `dotnet store` feature implementation:

Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.ComposeStore.targets
282:      <ProjectAssetsFile>$(BaseIntermediateOutputPath)\project.assets.json</ProjectAssetsFile>

Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.CrossGen.targets
213:      <_CrossProjAssetsFile>$([System.IO.Path]::Combine($(_CrossProjFileDir),  project.assets.json))</_CrossProjAssetsFile>
```

* We need to make sure that this happens after nuget has chosen the default ProjectAssetsFile path:
```
Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets
28:    <ProjectAssetsFile Condition="'$(ProjectAssetsFile)' == ''">$(BaseIntermediateOutputPath)/project.assets.json</ProjectAssetsFile>
```

2. There

**Comment by nguerrera** [comment]
See also https://github.com/dotnet/project-system/issues/1437 

I think we're going to need to coordinate between all 3 repos to get this fixed.

**Comment by livarcocc** [comment]
@dsplaisted should we close this issue now?
