### ISSUE TITLE
Add method to publish without application host

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/sdk#14396]
I'm working on building .NET Core for a non standard platform (linux-armel). It has a runtime id, but the dotnet team does not upload an apphost for linux-armel to nuget. This means that `dotnet publish -r linux-armel --no-self-contained` does not work, as an app host is still required for that. It would be very helpful for onboarding alternate RID's if there was an option to publish without an apphost. I understand that this would require calling `dotnet myapp` to run, but thats fine with me. I just want to be able to publish without the runtime but with the proper native libraries for 3rd party nuget packages for my platform.

**Comment by wli3** [comment]
You can set msbuild property `UseAppHost` to `false` to disable output of apphost

**Comment by ThadHouse** [comment]
Awesome, that works. Thank you!
