### ISSUE TITLE
ILLink warnings tests should include the version of the runtime libraries in its output

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#14417]
As seen in https://github.com/dotnet/installer/pull/8966 it's actually pretty tricky to figure out which version of the runtime/framework assemblies are used when running the [ILLink_verify_analysis_warnings_hello_world_app](https://github.com/dotnet/sdk/blob/0ae5136153da2d364288be1d9cdd4804d8279adf/src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs#L288) test. For the test it should be pretty easy to print out the exact version of one of the assemblies from the framework (CoreLib would be best).

**Comment by sbomer** [comment]
While doing this, we should double-check that the test is running against the correct TFM. It requests `net5.0`, but based on https://github.com/dotnet/sdk/pull/14338#issuecomment-725007437 I think it has been running against `net6.0` bits. I would suggest updating the test to run against `net6.0` (intentionally :)).
