### ISSUE TITLE
The SDK should provide default 'DependentUpon' metadata for some well known combinations.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/sdk#1441]
For some sets of files (such as `*.resx` and the corresponding `*.designer.cs` file), it is common practice to add `DependentUpon` metadata to the item so that they appear nested in the solution explorer view.

MSBuild does not currently provide any built-in syntax to define these types of dependencies, but such support is suggested here: https://github.com/Microsoft/msbuild/issues/2346

In the meantime, the SDK can still provide default item metadata using syntax similar to the following:
```xml
<Compile Update="**\*.Designer.cs" DependentUpon="$([System.IO.Path]::ChangeExtension($([System.IO.Path]::GetFileNameWithoutExtension(%(Identity))), '.resx'))" />
```

I propose that this should be done for `*.resx`/`*.designer.cs` initially, but we should also consider whether extending it to other common patterns is a good idea (`*.xaml` and `*.designer.cs`, `*.css` and `*.min.css`, `*.js` and `*.min.js`, `Strings.xlf` and `Strings.*.xlf`, etc...).

As with the default globbing support, this default metadata should likely be conditioned behind a property.

Additionally, as per this comment https://github.com/Microsoft/msbuild/issues/2346#issuecomment-317098334, MSBuild does not distinguish between 'Empty' and 'Absent' metadata, so it may be worthwhile to condition the setting of this metadata to only if it is already empty.

**Comment by tannergooding** [comment]
FYI. @Srivatsn, @sharwell

**Comment by sharwell** [comment]
I also added it for RESX files for satellite assemblies:

```xml
<EmbeddedResource Update="**\*.??-??.resx" DependentUpon="$([System.IO.Path]::ChangeExtension($([System.IO.Path]::GetFileNameWithoutExtension(%(Identity))), '.resx'))" />
```

It's possible that a line needs to be added for `??` in addition to my use of `??-??` here, but someone else would need to determine that.

**Comment by nguerrera** [comment]
VS will now group files by convention without DependentUpon being set. We don't want to do this sort of magic in evaluation because it is expensive. It is also difficult to get right

> It's possible that a line needs to be added for ?? in addition to my use of ??-?? here, but someone else would need to determine that.

Just for the record, there are cultures that match neither of these. For example, we use `zh-Hans` and `zh-Hant` in most of our products. `CultureInfo.GetCultures(CultureTypes.AllCultures).Where(c => c.ToString().Length > 5).Count()` is 196 on my system.
