### ISSUE TITLE
PublishReadyToRun=true removes digital signature from some .dlls

### ISSUE THREAD

**Issue by gc-deniszmitrichenko** [dotnet/sdk#14438]
* .NET Version: 

5.0.100-rc.2.20479.15

**Problem description:**

When I run "dotnet publish" command with "-p:PublishReadyToRun=true" option some dlls becomes without digital signature.
The full command look like this:
```
dotnet publish MainSolution.sln --configuration Release --runtime win-x86 --output PublishFolder -p:PublishReadyToRun=true --self-contained true
```
As a result I can see that properties of Microsoft.Data.Sqlite.dll file doesn't have "Digital Signatures" tab:
![Microsoft Data Sqlite dll Unsigned](https://user-images.githubusercontent.com/61823719/98253604-4b0da500-1f8c-11eb-885d-16e63685c87a.png)

The simple build in Release configuration and/or publishing without specified "-p:PublishReadyToRun=true" option produces signed Microsoft.Data.Sqlite.dll:
![Microsoft Data Sqlite dll Signed](https://user-images.githubusercontent.com/61823719/98253681-68427380-1f8c-11eb-88ff-ec29d1b87ba8.png)

**Expected behavior:**
dotnet publish command with specified "-p:PublishReadyToRun=true" doesn't remove digital signature from dll.

**Minimal repro:**
1. Publish attached app
[WindowsFormsApp1.zip](https://github.com/dotnet/sdk/files/5494977/WindowsFormsApp1.zip)
with
```
dotnet publish MainSolution.sln --configuration Release --runtime win-x86 --output PublishFolder -p:PublishReadyToRun=true --self-contained true
```
command.

2. Check properties tab of Microsoft.Data.Sqlite.dll file in the PublishFolder.

**Additional questions:**
1. Is it ok if we sign Microsoft dlls with our digital signature?
At least until the issue will be resolved?
I asked about it because some antivirus/firewall software (e.g. Norton by NortonLifeLock Inc./Symantec) removes unsigned dll after starting our apps.

**Comment by wli3** [comment]
@agocke

**Comment by gix** [comment]
Since ReadyToRun modifies the assemblies, signatures become invalid, so this is to be expected (just like the ngen'ed assemblies in the GAC are not signed).

Any assemblies coming from a runtime pack (NETCore.App, AspNetCore, …) have their metadata set to `IsTrimmable=false` and are excluded though, so you only see this for some assemblies.

**Comment by agocke** [comment]
Yes, any binaries which do not have R2R already applied will be modified, so their signatures will be changed. Applying your own signature is perfectly fine and recommended if signatures are required for your environment

**Comment by tapika** [comment]
Why this ticket is open then ? If it's acceptable solution just to re-sign given dll, I guess this qualifies as the solution to the problem. Or is there something that is planned to be improved ?
