### ISSUE TITLE
"Can not find compilation library location: <library pkg>" on Azure appservice

### ISSUE THREAD

**Issue by Plasma** [dotnet/sdk#1445]
Hi,

I've been experiencing this problem when deploying to Azure AppService:

```
InvalidOperationException: Can not find compilation library location for package: 3rdPartyLib.dll
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart+<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
System.Linq.Enumerable+<SelectManyIterator>d__16.MoveNext()
Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, MetadataReferenceFeature feature)
Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
System.Threading.LazyInitializer.EnsureInitializedCore<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(string compilationContent, string assemblyName)
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, string compilationContent)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(string relativePath, string normalizedPath, Func<RelativeFileInfo, CompilationResult> compile)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
...
```

This happens when attempting to navigate to the first MVC Razor view on Azure appservice.

I'm able to browse locally without any issues even if I do a "dotnet publish" and run the executable.

I've made all the assembles .NET Framework 4.6 targeted because .NET Core/Std does not have everything I need.

I've looked around GitHub/SO for many complaints about this problem and unfortunately have not found a workable solution.

Why would this be breaking on Azure but not local? I thought "dotnet publish" was supposed to make all deployments the same, regardless of location.

If I manually upload my own "dotnet publish" of the build to Azure appservice it works successfully - so they're doing something "different", but I don't know what.

Does anyone have any ideas?

Thanks,
Andrew

**Comment by Plasma** [comment]
I am able to fix this on Azure appservice if I look in my webapp.deps.json file on the deployment, and remove all references to the "3rdPartyLib.dll" file. Restarting the app after this fixes it. I notice there are zero references to this assembly, which I do use, in the .deps.json file on my local "dotnet publish".

So Azure build is adding this (?) to the deployment process and thus is breaking it? How? How can that be stopped? So confusing.

**Comment by livarcocc** [comment]
@balachir @vijayrkn @mlorbetske can you guys take a look?

**Comment by livarcocc** [comment]
@Plasma also, please indicate what version of the CLI you are using.

**Comment by vijayrkn** [comment]
@Plasma - Also, can you please clarify the following?

1. What publish mechanism are you using to publish to App Service (VS/VSTS/Git/?)
2. Is "3rdPartyLib.dll" the actual name of the dll or is it a masked name? 
3. Do you have reference to this dll locally and it is not showing up in the local deps file but only shows up in the Azure deps file?
(from your previous comment >>I notice there are zero references to this assembly, which I do use, in the .deps.json file on my local "dotnet publish".)
4. Can you try turning off razor pre-compilation in your local csproj and see if it publishes fine?
5. And as Livar already asked, Please provide the version of cli used locally.

**Comment by Plasma** [comment]
Thank you for the replies.

1. dotnet --version says: 1.0.3
2. Masked name
3. Correct. I added it as an assembly to my web project locally, and when compiling/dotnet publish there is no mention of it in the .deps file. If I remove this library from the deps file that appears on Azure AppService's published copy of my code, then everything works. Its only showing up on Azure's deps file.
4. How can I do this? Thank you

**Comment by Plasma** [comment]
If I publish via Visual Studio to AppService it also works.

**Comment by Plasma** [comment]
Any suggestions what I can be looking at? How do things get elected to be in this deps file? Is it based on something finding the source code of the assembly, or in the csproj, or ... ? I'm at a loss, thank you.

**Comment by livarcocc** [comment]
I am going to move this to websdk, since dotnet publish seems to work.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#288
