### ISSUE TITLE
Dotnet publish command generates invalid assembly name for linux.

### ISSUE THREAD

**Issue by drwigglechin** [dotnet/sdk#1446]
-  Create application has a period in the assembly name.
    -  Test.ConsoleApp

-  In csproj file set the following in under a property group tag.
    -  <AssemblyName>Test.ConsoleApp</AssemblyName>
    -  <RuntimeIdentifiers>win7-x64;win10-x64;ubuntu.16.04-x64;centos.7-x64</RuntimeIdentifiers>

-  Use dotnet publish command to build a release version for a linux OS.
    -  dotnet publish -c Release -r centos.7-x64

The bin\Release folder will contain a file named 'Test.ConsoleApp.ConsoleApp'. This will not work in linux until you rename the file to 'Test.ConsoleApp'.

**Comment by livarcocc** [comment]
Which version of the SDK are you using? We have fixed this bug already, I believe for preview3. If you are using the latest from release/2.0.0 and this still repros, please, re-activate.

**Comment by drwigglechin** [comment]
Thanks for the info. I'm currently running preview 2.
