### ISSUE TITLE
PublishSingleFile=true does not result in a true single-file publish

### ISSUE THREAD

**Issue by Nihlus** [dotnet/sdk#14489]
# General

.NET SDK Version: 5.0.100

When publishing a single-file, self-contained .NET 5 executable, the resulting published files are not a true single-file output. Rather, the native assemblies (clrcompression.dll, clrjit.dll, etc) are placed next to the published executable, and must be copied along with it for it to properly run. This runs against the concept of a single-file publication, where this should not be needed - nor was it needed in .NET Core 3.1.

To reproduce, 

1. `dotnet new console`
2. `dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true`
3. `ls bin/Release/net5.0/win-x64/publish/`

Observe the results. The native binaries that are published into this directory also include any native binaries that come from nuget packages, or part of the build.

**Comment by motowilliams** [comment]
Add a `-p:IncludeNativeLibrariesForSelfExtract=true` to your cli parameters and you end up with a single exe and single pdb file.

Per https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience / Self-Contained Publish / Single-file publish Windows with Extraction

**Comment by Nihlus** [comment]
Thanks, that worked. It should probably be made a bit more obvious.

**Comment by svdHero** [comment]
I came here, because I had exactly the same problem and did not know what was going on. Maybe @motowilliams's link should somehow be added to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish. Certainly, the `IncludeNativeLibrariesForSelfExtract` option should be mentioned there.

**Comment by Webreaper** [comment]
I'm trying to figure this out for a Blazor Server app. I raised the issue [here](https://github.com/dotnet/aspnetcore/issues/28349#issuecomment-738129161) but they directed me to the dotnet SDK tracker. I've tried adding the `InlcudeNativeLibrariesForSelfExtract` flag and it does reduce the list of files that don't get packed into the single-file extractor.  But there's still content being missed out - I get multiple files and the wwwroot folder not included.
```
Damselfly.Core.pdb
Damselfly.Web
Damselfly.Web.Views.pdb
Damselfly.Web.pdb
appsettings.Development.json
appsettings.json
libSkiaSharp.dylib
wwwroot
```

**Comment by Webreaper** [comment]
Any updates on this? It's quite messy and inconvenient that it's not possible to create a single-file deployment for a Blazor app.

**Comment by adrianord** [comment]
@Webreaper To help you out a little bit, the pdb files are not needed for the application to function, they are purely used for debugging. If you want to include them in the published binary you'll need to add `<DebugType>embedded</DebugType>` to all the csproj files included in the build.

The wwwroot folder is a bit more tricky as they are static resources. What you'll need to do is add them as an EmbeddedResource in the csproj like this
```xml
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>
```
then use the `Microsoft.Extensions.FileProviders.Embedded` package to access the files in your code. The way you do it is going to be different for your specific set up, but for a SPA it'd look something like this
```csharp
var provider = new ManifestEmbeddedFileProvider(Assembly.GetAssembly(type: typeof(Startup)), "wwwroot");
app.UseSpaStaticFiles(new StaticFileOptions
{
    FileProvider = provider,
    RequestPath = "",
});
```

As for the `dylib` file, I'm pretty sure `/p:IncludeNativeLibrariesForSelfExtract=true
` was supposed to take care of that. I'm still looking for a solution to that as well. Which is how I stumbled upon this ticket.

**Comment by Webreaper** [comment]
@adrianord Thanks. Adding the files as a static resource and accessing them via code doesn't work, because some of these are css and JS files. Sure, I could add routes in my code and load them from disk, but that slightly circumvents the point of using ASP.Net's wwwroot folder. ;)

What I really want is the single-file publish to take into account the fact that there's non-code files, and include them in the compressed archive that makes the single-file published artifact. The same goes for the dylib files. The point is that if .Net purports to support a single-file self-extracting executable publish/deployment, then it should handle all files, not just the binaries.

**Comment by adrianord** [comment]
@Webreaper I've been using the embedded resources with css and js files just fine, not sure about your set up.

As a work around until this issue is fixed, you can use `IncludeAllContentForSelfExtract` in place of `IncludeNativeLibrariesForSelfExtract` for Mac publishes. From my experience this is specifically affecting `osx-x64`.
This is the approach I'm taking for now. For your use case you might just want `IncludeAllContentForSelfExtract` in general, though.

**Comment by vitek-karas** [comment]
@Webreaper - if you want self-extracting functionality even for non-code assets, then `IncludeAllContentForSelfExtract` is a solution. It will basically bundle everything and extract everything on start.

The intent of single-file was definitely not to solve "self-extract everything" - it can be used like that, but it has performance drawbacks. The main goal of single-file is to embed all code into the executable. Currently we can do this with the runtime and managed assemblies without extraction. Native libraries are really hard and so we leave them next to the executable - if you want them bundled, use the `IncludeNativeLibrariesForSelfExtract` and only the native libraries will be extracted.

@adrianord If there's a problem where dylibs are not bundled when they should be - can you please open a separate issue for this ideally with some repro and so on?

**Comment by vitek-karas** [comment]
The original issue about the fact that docs don't have a good way to learn about the additional properties - as far as I can tell this has been fixed as the publish doc now refers to https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md for details about the single-file feature. I'm going to close this issue then.

**Comment by douglasg14b** [comment]
2025 and the guidance in this thread and that doc do not appear to work.

SingleFIle does not produce a single file any longer

One of... 20+ issues like this unfortunately

**Comment by vitek-karas** [comment]
@douglasg14b The official docs at https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview seem to describe this well - it clearly states, that native libraries are not bundled by default and options how to do that.

Do you observe different behavior?
