### ISSUE TITLE
Is there a mechanism to control the AssemblyFileVersion independently from AssemblyVersion in MsBuild?

### ISSUE THREAD

**Issue by fir3pho3nixx** [dotnet/sdk#1450]
Hi

We are trying to save consumer frameworks and users the hassle of having to add assembly binding redirects when they upgrade minor/patch versions of Castle Core used as transitive dependencies. The issue where we are exploring this is [here](https://github.com/castleproject/Core/issues/288).

In summary this is what we landed on: 

>@stakx -> This line in Microsoft.NET.GenerateAssemblyInfo.targets suggests that it might be possible to add a `<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>` to the .csproj, then define that attribute manually. I haven't tried it myself, though. (If that doesn't work, then try the much coarser-grained `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`. I've used this before and it works, but it means you might then have to keep certain attributes in Castle.Core.csproj and AssemblyInfo.cs in sync manually.)

Is there a tidy way we can achieve this without adding an AssemblyInfo.cs?

Thanks

**Comment by stakx** [comment]
@fir3pho3nixx, the XML tag names are missing in the above quote. Should include `<GenerateAssemblyVersionAttribute/>` and `<GenerateAssemblyInfo/>`. ;-)

**Comment by stakx** [comment]
(@fir3pho3nixx, the first one is still missing / not rendered, too.)

**Comment by fir3pho3nixx** [comment]
@stakx - Sorry my head is else where ...

**Comment by stakx** [comment]
No worries, just thought I'd let you know.

**Comment by dasMulli** [comment]
You can set the properties `AssemblyVersion` (=> `AssemblyVersionAttribute`) and `FileVersion` (=> `AssemblyFileVersionAttribute`) in the project file to control the value of each generated attribute.

So a sample project file could contain for example:

```xml
<PropertyGroup>
  <!-- Set VersionPrefix instead of Version to allow a suffix to be added by CI builds -->
  <VersionPrefix>1.2.3</VersionPrefix>
  <AssemblyVersion>1.2.0</AssemblyVersion>
  <FileVersion>$(VersionPrefix)</FileVersion>
</PropertyGroup>
```

**Comment by fir3pho3nixx** [comment]
@dasMulli - Many thanks :)

**Comment by abatishchev** [comment]
Is it possible to disable the generation only of some parameters (those winch control versions) since a separate AssemblyInfo.cs is generated as part of my build? So I'm either turning off the generation of all attributes (those which control names) or I have only versions and rest are blank.

**Comment by dasMulli** [comment]
Yes each attribute can be controlled individually by setting
```xml
<PropertyGroup>
  <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
</PropertyGroup>
```

The pattern is `Generate{AttributeName}Attribute`, if you don't mind reading msbuild code the full list is [here](https://github.com/dotnet/sdk/blob/2df7f13c8c25e36e3620b62a420bc6b733e5bbb4/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L65-L99).

**Comment by abatishchev** [comment]
Awesome, thanks!
