### ISSUE TITLE
Whioch UWP version will support with .Net Standard 2.1 and by when?

### ISSUE THREAD

**Issue by amitagrawalhyd** [dotnet/sdk#14520]
With .Net Standard 2.1 we are still waiting for the support with Universal Windows Platform, which is still showing TBD at following link "https://docs.microsoft.com/en-us/dotnet/standard/net-standard". We need your help on the same to know by when we can see .Net Standard 2.1 will start supporting UWP or which version of UWP (e.g.: 10.0.16299 +).

We have kept one of our critical requirement on hold for this and may need your attention on this

**Comment by joeloff** [comment]
Hi

I talked to a few folks and they all suggested to look at https://github.com/microsoft/ProjectReunion This is the next step for UWP and was mentioned during the .NET 5.0 announcement.

I would suggest posting your question on the Project Reunion site.

Jacques
