### ISSUE TITLE
GetFileDependsOnNETStandard holds handles to assemblies after it returns

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#1453]
I believe this is the root cause of https://github.com/NuGet/Home/issues/5609.

I've been looking at this with @mishra14. 

It appears that [GetFileDependsOnNETStandard](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.netstandard.cs#L14), introduced to support .NET Standard 2.0 in VS 15.3, holds locks on files longer than it should.

It [appears](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.net46.cs#L130) to close the handle to the files it's inspecting, but we can observe through the debugger that they don't get closed immediately--stepping over that line and running a `handle.exe` search shows the handle still open.

When `devenv.exe` is started from an environment with `set ImplicitlyExpandNETStandardFacades=false`, project creation succeeds. That property [disables calling `GetDependsOnNETStandard`](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L24).

**Comment by rainersigwald** [comment]
@livarcocc This manifests as a bizarre regression in non-.NET Core projects and I think the NuGet team would like to see it fixed for 15.3.

@ericstj This is up your alley. Do you know what would be causing this code to preserve a handle? (It doesn't last forever; if you wait a few minutes `procexp` no longer shows the handle.

**Comment by ericstj** [comment]
Is this .NET core or .NET desktop?

**Comment by rainersigwald** [comment]
The net46 version of the task running on desktop (from inside VS).

**Comment by ericstj** [comment]
I see.  I suspect we're missing this:
https://github.com/Microsoft/msbuild/blob/cc5661488dba7c2a25ad1555fee08a9237a2414b/src/Tasks/AssemblyDependency/AssemblyInformation.cs#L500-L503

**Comment by rainersigwald** [comment]
I find that theory very convincing!

**Comment by livarcocc** [comment]
I see that @ericstj has fixed this issue already. As such I am going to close it. If that's not the case, just comment and we can re-activate.
