### ISSUE TITLE
Unexpected behavior with code built targeting net5.0 in release (optimized) configuration. 

### ISSUE THREAD

**Issue by dale-personal** [dotnet/sdk#14535]
Here is a repo which reproduces the issue:

https://github.com/dale-personal/net5-issue

The code in question functions as expected for a number of iterations, then starts producing unexpected results.

**Comment by sfoslund** [comment]
@dale-personal can you please give more detail on what the unexpected results are?

**Comment by dale-personal** [comment]
Sure,  I've created a repo which reproduces the issue:
https://github.com/dale-personal/net5-issue/blob/main/test.cs

In the test provided, given enough loop iterations, the behavior of this line changes
if (_default != null && _default.Value.HasValue) return _default.Value.Value;

_default.Value.HasValue is false, while at the same time _default.Value.Value = "test"

**Comment by sfoslund** [comment]
This issue was moved to dotnet/runtime#44895
