### ISSUE TITLE
is there a way to ignore NETSDK1136 ?

### ISSUE THREAD

**Issue by 0x53A** [dotnet/sdk#14554]
We have an ASP.NET Core application which references some legacy (.net framework 4.0) dlls.  
These dlls have a reference to winforms, but it will never actually be used at runtime.

After updating to net5, we get an error ``NETSDK1136``: 

```
 The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.
```

The message is true, we do reference a dll which references WinForms. But that reference is benign and never called at runtime.

Is there a way to suppress this error?

I found the [location where it is emitted, but not way to disable it](https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L353-L364).

----------

Additional info:

I tried to change the tfm to net5.0-windows to shut the sdk up, but now it won't run on linux:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' was not found.
  - No frameworks were found.
```

So this seems to be a hard blocker for us.

I guess I could try to manually edit the generated runtimeconfig.json and remove Microsoft.WindowsDesktop.App ...

----------

Edit2: editing runtimeconfig.json seems to have worked, but I haven't tested it in depth yet

**Comment by 0x53A** [comment]
Another workaround seems to be

```xml
  <Target BeforeTargets="_CheckForTransitiveWindowsDesktopDependencies" Name="_FixStupidSdkError_NETSDK1136">
    <ItemGroup>
      <TransitiveFrameworkReference Remove="Microsoft.WindowsDesktop.App" />
      <TransitiveFrameworkReference Remove="Microsoft.WindowsDesktop.App.WPF" />
      <TransitiveFrameworkReference Remove="Microsoft.WindowsDesktop.App.WindowsForms" />
    </ItemGroup>
  </Target>
```

With this, I could change my TFM back to ``net5``.

But again, this is a somewhat ugly workaround, please make NETSDK1136 opt-out.

**Comment by wli3** [comment]
If you need to run on both windows and linux. We suggest to multitarget net5.0-windows and net5.0. And use preprocessor to guard API specific usage https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework.

Suppress NETSDK1136 if possible is also a bad workload, since it is only few scenario types are not used in runtime.

**Comment by 0x53A** [comment]
I misunderstood the cause of this NETSDK1136.

But it still doesn't seem right.


If I add the NuGet package https://www.nuget.org/packages/Fable.Localization.Tool/ then it triggers.
But the package only references Newtonsoft.Json, not anything winforms.

![image](https://user-images.githubusercontent.com/4236651/99661055-941d2900-2a63-11eb-9298-ca41973de918.png)

This is easily reproducible with this project file (and you have to add an empty ``Loc.txt`` file to the project):

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Localization.Tool" Version="0.0.802 " />
    <FableLocalizedText Include="Loc.txt" SourceOutputFilePath="Loc.fs" ResourceOutputFilePath="Loc.resx" JsOutputFilePath="Loc.js" SourceVisibility="Public" />
  </ItemGroup>

</Project>
```
