### ISSUE TITLE
NTSDK1061 publish error: The project was restored using Microsoft.NETCore.App version 2.2.8, but with current settings, version 2.2.0 would be used instead.

### ISSUE THREAD

**Issue by vOrdonezGit** [dotnet/sdk#14557]
Hi guys,

After upgrade VS 2019 to Version16.8.1, i'm not able to publish my project into Azure App Service. Before that, i dont have any issues.

The error i get:

NETSDK1061: The project was restored using Microsoft.NETCore.App version 2.2.8, but with current settings, version 2.2.0 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.

I tried some tips from similar questions, but it doesnt't work for me. 

I think it's related to SDK 5.0

Any way to fix this? Thanks in advance.

Some environment info:

![image](https://user-images.githubusercontent.com/74531434/99228406-dc7ee180-27ec-11eb-8b52-3cad989ccca4.png)

**Comment by wli3** [comment]
Maybe you faced something similar to https://github.com/dotnet/sdk/issues/2682?

**Comment by vOrdonezGit** [comment]
Thanks for your reply.

> Maybe you faced something similar to #2682?

I tried all the tips: changing the .csproj, adding RuntimeFrameworkVersion, adding TargetLatestRuntimePatch...

I'm trying to install VS into another computer, just in case..

**Comment by vOrdonezGit** [comment]
Solved! 

Following #2682 instruction adding this line to my .csproj

`<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`

But, as we say in my country, _devil is in little details_, I had to add it into ALL the projects of the solution, not only, even it has no relation with the one i want to publish...

Thanks!
