### ISSUE TITLE
Google server authorization problem

### ISSUE THREAD

**Issue by Fridey13** [dotnet/sdk#14601]
When i use external sign in on local server all working is good, but after my app run on server it's doesn't working.

![image](https://user-images.githubusercontent.com/49733644/99573621-013aab00-29df-11eb-8d8b-7e3b2f6fb32c.png)
This is how it work in localhost.

But in server this working not a same

![image](https://user-images.githubusercontent.com/49733644/99573922-62fb1500-29df-11eb-9deb-f752ec177cb6.png)

and ending:

![image](https://user-images.githubusercontent.com/49733644/99573990-79a16c00-29df-11eb-896c-7df8c4bc02a2.png)

Why it's working different?

P.S. sorry for my bad language skills

P.S.S if you need more information write me here or on my email
shrifttogod@gmail.com

**Comment by vitek-karas** [comment]
Is this question somehow related to .NET?
This repo is about .NET SDK, so problems with authentication to a web server are not really the right topic here.
