### ISSUE TITLE
How is the AppHost (shim .exe) platform (x86/x64) chosen for an AnyCpu project?

### ISSUE THREAD

**Issue by vuplea** [dotnet/sdk#14602]
I seem to obtain an x64 `AppHost` for `AnyCpu` projects with `<OutputType>Exe</OutputType>`.

Is there a way to generate x86 `AppHost` without having the assembly x86 too (but leave it as `AnyCpu`)?

**Comment by vitek-karas** [comment]
You can specify `<RuntimeIdentifier>win-x86</RuntimeIdentifier>` and `<SelfContained>false</SelfContained>` (assuming this is on windows), or `-r win-x86 --self-contained false` on the command-line.

*Specifying the runtime identifier also sets self-contained to true, so it needs to be explicitly disabled if you want the default build output to be the same*

The AppHost cannot be AnyCpu - it's a native executable, and I think the default is to pick the bitness of the dotnet SDK building it (but I could be wrong).

**Comment by vuplea** [comment]
Thanks a lot for the response.
Unfortunately the suggestion does not seem work; the assembly is x86 (like when using `<PlatformTarget>x86</PlatformTarget>`), not AnyCpu:

MyApp.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0-windows</TargetFramework>
        <RuntimeIdentifier>win-x86</RuntimeIdentifier>
        <SelfContained>false</SelfContained>
    </PropertyGroup>
</Project>
```

MyApp.Tests.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0-windows</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\MyApp\MyApp.csproj" />
    </ItemGroup>
</Project>
```
MyAppTests.cs
```
    class MyAppTests
    {
        static void Main() => _ = new MyApp(); // type from MyApp.csproj
    }
```

Running `MyApp.Tests.exe` results in
```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
File name: 'MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at MyApp.Tests.MyAppTests.Main()
```

**Comment by vitek-karas** [comment]
So you want a platform independent managed code, x86 app.exe for it, but then run the tests in x64?

@wli3 @dsplaisted would you know if there's logic which sets the platform for managed compilation based on the RID? Or - is there a way to build for win-x86 but still keep the assemblies `AnyCpu`?

**Comment by vuplea** [comment]
Indeed.
We want to have an x86 AppHost because it works on Windows x86 too, but the code is platform independent.
We will change the test runner so that it runs on x86.

But I think it would be nice to be able to have the assembly as AnyCpu, as it is more flexible.

**Comment by vitek-karas** [comment]
Please don't take this as questioning your usage, I'm just curious about the scenarios where having the assembly AnyCpu would be helpful. My view is that:
* Running it via the apphost will always runt he bitness it was built for...
* Running tests - technically shouldn't matter what bitness, so matching the bitness of the apphost makes sense (also it would be testing the real-world case better)
* Running the app via "dotnet app.dll" is the only scenario where it would matter - but why would I do it if I have the apphost?

As a side note, you can build/publish the app for multiple RIDs and that way get two different apphosts. If there's a need to have both 32bit and 64bit version.

**Comment by dsplaisted** [comment]
Yes, you can use the `AppHostRuntimeIdentifier` to choose which AppHost you get without changing the RuntimeIdentifier for the app.

**Comment by vuplea** [comment]
@dsplaisted Indeed `AppHostRuntimeIdentifier` does work as desired, thanks! I will close the issue.

@vitek-karas the full story is that we are in the process of migrating from .NET Framework, and we have a lot of exe projects.
* Regarding tests, it would be better in theory to run them on x86, as you mentioned.
* There are a couple of ProjectReferences to exe projects. Referencing them from AnyCpu projects would be wrong if them themselves were not AnyCpu, and we might actually want x64 AppHosts for some of them at some point.
We could have removed these references; this was more of a question and not a blocking issue.

Thank you very much!
