### ISSUE TITLE
Parameter to not emit "runtime" key-value in deps.json

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/sdk#1460]
Hi
I have a dotnet 2.0 netcoreapp2.0 test project. I am using `msbuild15` to build the project from command line. When I run `dotnet vstest` on the generated dll, I get :

```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed to initialize client proxy: could not connect to test process.
```

If I remove all `runtime` key-value pairs from `deps.json` file, dotnet vstest works.

I have a separate project where I build using `dotnet cli` commands like `dotnet build`. `dotnet vstest` also runs fine on that project. Replacing dll from failing project to this project also works.

So, Is passing a flag to dotnet-sdk to not emit `runtime` information a right solution ?

Relevant path of csproj file :
```
<PropertyGroup>
    <Description>A.B tests</Description>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <Authors>Microsoft</Authors>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DefineConstants>$(DefineConstants);DotNetCoreClr</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>A.B</AssemblyName>
    <PackageId>A.B</PackageId>
    <PackageTargetFallback>$(PackageTargetFallback)</PackageTargetFallback>
    <DebugType>full</DebugType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
```

and `dotnet --info` :
```
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\dotnet\sdk\2.0.0-preview2-005905\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25310-02
  Build    : bcec8851461ac42af06ba783b85cc5d6e44447f1
```

`runtime` keys that I remove are like following for each of the assembly :
```
"runtime": {
          "lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll": {}
        }
```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1380

**Comment by cltshivash** [comment]
@ashishnegi Below are the steps i tried to repro the issue.

VS Installation: VS 2017 15.5.4

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

1. - Created a dotNet core unit test project
2. - Ran dotnet restore from cmdline
3. - Ran dotnet vstest from <UT Project location>\bin\debug\\netcoreapp2.0 folder
4. - Ran dotnet test from the <UT project location>

The tests execute fine without having to change anything in deps.json. Please do check if the issue repros on the latest VS update and if so kindly provide repro steps/project.
