### ISSUE TITLE
[android] .NET 6 usage of $(_GetChildProjectCopyToPublishDirectoryItems)

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#14619]
Context: https://github.com/xamarin/xamarin-android/pull/5308

Android can't support the `@(Content)` build action because of the way Android apps remain compressed when they are installed on disk.

So for example, if you did:
```xml
<Content Include="Foo.txt" CopyToOutputDirectory="PreserveNewest" />
```

We can't possibly put this in a location where `File.OpenRead ("Foo.txt")` would work when the app is running on Android. Developers instead would use `@(AndroidAsset)` and use [Android APIs](https://docs.microsoft.com/xamarin/android/app-fundamentals/resources-in-android/android-assets) to access a `Stream` of the file. We emit a build warning in any Android project using `@(Content)`.

All that to say, we are setting`$(_GetChildProjectCopyToPublishDirectoryItems)` to `false` for Android projects. Should this property be renamed so it is public? Drop the underscore?

**Comment by joeloff** [comment]
Does it matter if child projects a non-Android? Sounds like it either needs to be public or special cased to default to false for Android, but then the next platform will eventually come along. I'll take this up in triage.

**Comment by marcpopMSFT** [comment]
@dsplaisted This property has been around forever.  Any concern just swapping it to public?  There's minimal usage on GH and people aren't supposed to be setting private properties.

**Comment by dsplaisted** [comment]
If no one seems to be using it, then it would be fine to remove the underscore.

I'm not sure about the broader scenario.  What happens when an Android project references a library (or a NuGet package) that includes Content items?

Also how does this interact with using Build instead of Publish?

**Comment by jonathanpeppers** [comment]
If you add a NuGet package with content items, you would get a build warning -- and the files don't make it inside the app. NuGet library authors have the option add `AndroidAsset` or `AndroidResource` items, and those will get passed along and included in the app.

This property seems specific to Publish, so if that target gets reworked -- eventually, we might not need to set this property anymore?

**Comment by marcpopMSFT** [comment]
Triage:  You're welcome to just use the property as is.  We don't think it's worth changing at this time and it's ok for you to use this property (with the warning that we aren't as careful when making changes to internal properties)

**Comment by marcpopMSFT** [comment]
Closing per above as I think you have the path forward.
