### ISSUE TITLE
__TransitiveProjectDefinitions.ResolvedPath is incorrect

### ISSUE THREAD

**Issue by kingerja** [dotnet/sdk#1462]
ResolvedPath should be (C:\projects\cbt-core\src\CBT.Core\CBT.Core.csproj)

                   __TransitiveProjectDefinitions
                       CBT.Core/1.0.0
                           Name = CBT.Core
                           Type = project
                           Version = 1.0.0
                           Path = ../CBT.Core/CBT.Core.csproj
                           ResolvedPath = C:\projects\cbt-core\src\CBT.Core.UnitTests\CBT.Core\CBT.Core.csproj

Repro steps:
See attached zip.
Run: msbuild /flp:Verbosity=Diagnostic src\CBT.Core.UnitTests\CBT.Core.UnitTests.csproj
Look in msbuild.log for CBT.Core/1.0.0

Potential fix. (but I didn't try any other scenarios.)
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageDependencies.cs
Change line from:
return Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Path.GetFullPath(ProjectAssetsFile)), path));
To:
return Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Path.GetFullPath(ProjectPath)), path));

[TransitiveProjectDefinitions.zip](https://github.com/dotnet/sdk/files/1181495/TransitiveProjectDefinitions.zip)

**Comment by livarcocc** [comment]
This has been fixed now.
