### ISSUE TITLE
Visual studio doesn't support .netcore sdk 3.1

### ISSUE THREAD

**Issue by vgavrilov-dil** [dotnet/sdk#14623]
**Visual Studio Version**:
Microsoft Visual Studio Professional 2019
Version 16.8.2

**Summary**:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	ClassLibrary1	C:\Program Files (x86)\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

**Steps to Reproduce**:

1. Create a new project 'Class Library' and select .net core 3.1

2.  Build the solution

3. Observe the message 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	ClassLibrary1	C:\Program Files (x86)\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

**Expected Behavior**:
Project should build and Target Framework should be netcore 3.1

**Actual Behavior**:
Project doesnt build, no netcore 3.1 avilable in Target Framework

**User Impact**:

Pretty nasty

**Comment by davkean** [comment]
Moving to the SDK. What VS versions do you have installed?

**Comment by vladimirs1969** [comment]
I faced the same issue with VS Prof 2019 6.18.2. 
This release doesn't support .Net Core at all. In my case I do not receive any error message (verbosity is Diagnostic). There is only build status: 'failed'.

**Comment by vgavrilov-dil** [comment]
> ?

MS Visual Studio Professional 2019. version 16.8.2

**Comment by vgavrilov-dil** [comment]
> Moving to the SDK. What VS versions do you have installed?
MS Visual Studio Professional 2019. version 16.8.2

**Comment by marcpopMSFT** [comment]
Closing old bug as 3.1 is now out of support.
