### ISSUE TITLE
"dotnet publish" is missing dependency files

### ISSUE THREAD

**Issue by RobotGizmo** [dotnet/sdk#14621]
Using .NET 5 and "dotnet publish" the resulting published folder is missing most of the required dependency files. This is the command I'm using:

`dotnet publish "MyProject.csproj" --configuration "Release" --runtime "win-x64" --self-contained true --output "C:\PublishFolder" -p:PublishReadyToRun=true -p:PublishSingleFile=false -p:PublishTrimmed=false`

To repro this issue create a new .NET 5 WinForms project (this issue will probably happen with other .NET 5 project types too) and add a reference to the NuGet package "System.Management.Automation". If you publish this project and compare the bin\release folder with the published folder you can see that it's missing most of the DLLs required by the NuGet package. There are no errors or warnings during the publish, it only fails at runtime when methods from this NuGet package are invoked.

If I leave out the "runtime" and "self-contained" parameters and publish requiring .NET to be installed on the server this works perfectly. It seems that doing a self-contained deploy omits the required dependency files. Thanks for looking into this! 😃

**Comment by aasim** [comment]
I have a similar issue. I am publishing using .NET v6.0.400, and my dependencies don't seem to be loading either.

I do use assembly scanning to search for dependencies in the same path as the executable, maybe that is the issue. However, I did note that it is also failing on finding 'MonoPosixHelper'. The documentation doesn't help, and the same was working before for net core 3.1

**Comment by JasonDWilson** [comment]
I ran into this issue when I moved a project reference to a nuget package.  Now the resulting exe can't find the dll from the package

**Comment by baronfel** [comment]
If anyone could provide sample code or include an https://aka.ms/binlog it would help us triage this request.

**Comment by marcpopMSFT** [comment]
Does this still repro when targeting .net 6 or .net 7 as there have been a lot of improvements in this space or can you provide a binlog? If it does repro, please reactivate and provide the binlog.
