### ISSUE TITLE
Failed to run dotnet if temp directory is full

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#14631]
## Steps to reproduce
1. Fill the entire temp folder.
I used this code.
	```csharp
	System.Console.WriteLine("Hello World!"); // This line causes error no. 2
	while(true)
	{
	    System.IO.Path.GetTempFileName();
	}
	```
2. Run `dotnet run` command in the project folder (I ran in the same folder as the code above).

## Expected behavior
Project builds and runs (Code above should throw `System.IO.IOException`).

## Actual behavior
I reproduced this several times and got different errors:
1. `Failed to create CoreCLR, HRESULT: 0x80004005`
2. `The "Csc" task failed unexpectedly.` [Full log](https://pastebin.com/w4cdq19j)
3. `/usr/share/dotnet/sdk/5.0.100/Roslyn/Microsoft.CSharp.Core.targets(71,5): error : Failed to create CoreCLR, HRESULT: 0x80004005 [/home/drakonter/Programming/Test/Test.csproj]`  
This error only occurred when I deleted the `obj` directory from the project directory.
## Environment data
> dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

> uname -a
```
Linux LenovoY520 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux
```

**Comment by marcpopMSFT** [comment]
Old issue triage, we don't plan to improve the error experience for a full temp directory experience as we do use the temp directory for a few items.
