### ISSUE TITLE
"The type x exists in both y and z" in System.Net.Http

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/sdk#1463]
Hi,

I created a .NET Standard 1.4 assembly.
Once I add the package [`Microsoft.AspNet.WebApi.Client`](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/5.2.3) (5.2.3), all types in `System.Net.Http` (e.g. `HttpClient`), report a compile error saying:

>`The type 'HttpClient' exists in both 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

I'm on Visual Studio 2017 (15.2-26430.16).

**Comment by ericstj** [comment]
This is because the `Microsoft.AspNet.WebApi.Client` package uses the old `Microsoft.Net.Http` package, rather than the `System.Net.Http` package.  You can workaround this by adding `<PackageReference Include="Microsoft.Net.Http" Version="2.2.29" ExcludeAssets="All" />` to your CSProj.

Incidentally this will be fixed by the conflict resolution that was added to the .NET SDK in 2.0 and you won't require that workaround after updating the latest dotnet SDK.

@pranavkm or @DamianEdwards might be able to comment if there is a newer/better version of `Microsoft.AspNet.WebApi.Client` that works well with `netstandard` projects.

**Comment by pranavkm** [comment]
@dougbu should be able to consume if we're fixing the package reference in the planned 5.2.4 release. FYI @Eilon if this helps in the scheduling of the release.

**Comment by pranavkm** [comment]
Spoke to @dougbu offline and it looks like for `netstandard1.x` we've removed the reference to `Microsoft.Net.Http` (See https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client). We're using https://github.com/aspnet/Mvc/issues/5822 to track consuming the new package from Mvc. You could use that to keep track of the status of the 5.2.4 release.

**Comment by weitzhandler** [comment]
@ericstj 
>This is because the Microsoft.AspNet.WebApi.Client package uses the old Microsoft.Net.Http package, rather than the System.Net.Http package. You can workaround this by adding <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" ExcludeAssets="All" /> to your CSProj.

This solved the issue.
I'd be glad to remove that line when possible, hopefully this is going to happen in 5.2.4.

@pranavkm 
>https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client

Should I rather use this feed instead of the above solution?

<hr/>

Anyway, I got my UWP running now, but I get `PlatformNotSupported` exceptions at runtime, where should I post issue about this? It's a XF (2.3.4.247) project.

**Comment by pranavkm** [comment]
@weitzhandler - the packages on the nightly feeds aren't fully vetted and fall outside of our support policies. If you're comfortable with this, feel free to consume it. If the other solution works as well, I'd encourage you to reference it.

**Comment by weitzhandler** [comment]
@pranavkm done, thank you!

[Here](https://forums.xamarin.com/discussion/100529/net-standard-uwp-platformnotsupported-exception)'s another problem I'm facing since moving to std. Hopefully you can take a look.

**Comment by dilkekurt** [comment]
> This is because the `Microsoft.AspNet.WebApi.Client` package uses the old `Microsoft.Net.Http` package, rather than the `System.Net.Http` package. You can workaround this by adding `<PackageReference Include="Microsoft.Net.Http" Version="2.2.29" ExcludeAssets="All" />` to your CSProj.
> 
> Incidentally this will be fixed by the conflict resolution that was added to the .NET SDK in 2.0 and you won't require that workaround after updating the latest dotnet SDK.
> 
> @pranavkm or @DamianEdwards might be able to comment if there is a newer/better version of `Microsoft.AspNet.WebApi.Client` that works well with `netstandard` projects.

Dear sir,
I know this post is from 2017 and it is closed for a long time. But, I am currently having the same problem and couldn't apply your solution. Where should I add the line you said exactly?

I am attaching the error I get:

<img width="1511" alt="error" src="https://user-images.githubusercontent.com/83077009/231401079-f79d1ada-ae35-47c0-8de7-c79342b5775c.PNG">
