### ISSUE TITLE
cannot call on other dotnet exe with project reference not working.

### ISSUE THREAD

**Issue by Belpaire** [dotnet/sdk#14635]
NET Core Version: 3.1.403
Windows version: version 1809
Does the bug reproduce also in WPF for .NET Framework 4.8?: No
Problem description:
I have a project structure like:

---|-wpfappProjectA
|
|-wpfappProjectB
With ProjectA having a Projectreference to projectB.
Debugging or running either app individually works. However when I want to run the wpfappProjectB.exe from ProjectA, it will complain of a missing runtime. This seems to be that alhtough projectB.exe is in the same folder, it does not contain the wpfappProjectB.runtimeconfig.dev.json or the wpfappProjectB.runtimeconfig.json files. If I copy these files I can run projectB from projectA. I am personally not quite sure whether this repository is where I should file the issue, so if needed you can redirect me. At first I thought it was wpf specific, but it seems like it is more of a generic dotnet thing(which is why the name of the reproducing repro is called that way.).

Expected behavior:
I'd expect that I can call an exe from another exe if I have a projectreference to it (namely, the runtime.json files are also copied).
Minimal repro:
https://github.com/Belpaire/wpfdotnetproblemreproduce edit: all you need to reproduce is to run wpfapp1 from visualstudio.

**Comment by marcpopMSFT** [comment]
I think this was fixed by this PR https://github.com/dotnet/sdk/issues/1675.  Please reactivate if not.
