### ISSUE TITLE
Microsoft.AspNetCore.Hosting.WindowsServices 5.0.0 is not compatible with net50-windows10.0.19041.0

### ISSUE THREAD

**Issue by mingtong** [dotnet/sdk#14645]
NU1202: Package Microsoft.AspNetCore.Hosting.WindowsServices 5.0.0 is not compatible with net50-windows10.0.19041.0 (.NETFramework,Version=v5.0,Profile=windows10.0.19041.0). Package Microsoft.AspNetCore.Hosting.WindowsServices 5.0.0 supports: net50 (.NETFramework,Version=v5.0)

It doesn't make sense.
I set TFM to net5.0-windows10.0.19041.0
ref
<PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="5.0.0" />

Env.
Windows Server 2012 R2
Windows SDK: windows10.0.19041.0
VS 2019.16.8

**Comment by mingtong** [comment]
Please take a look, I am blocked.

**Comment by mingtong** [comment]
I update the nuget.exe to latest version,  then it works

**Comment by marcpopMSFT** [comment]
Sounds like this was resolved by updating NuGet.  The changes to the TFM to support the new TargetPlatform model required a new version of NuGet to work correctly so that fixing your issue makes sense to me.
