### ISSUE TITLE
Don't warn out of support when building libraries

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/sdk#14653]
Warning applications that they are targeting a version of .NET that's out of support makes total sense.
I hope the ecosystem continues to move forward and folks continue to adopt new versions as they come out.

But when building a library, I' want to target the lowest TFM I need to get the API I require. For an _ASP.NET Core 3_ integration, that relies on the runtime store, that's `netcoreapp3.0`. Getting a warning to upgrade to `netcoreapp3.1` here is the only reason for me to do it. I don't believe though that dropping support to paying customers that for whatever reason are on a unsupported version of .NET is in the best interest of the company behind the library. 

Example:

``` /usr/local/share/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/bruno/git/sentry-dotnet/src/Sentry.AspNetCore.Grpc/Sentry.AspNetCore.Grpc.csproj]
```

If for some reason the warning will stay, is there a reason to silence it? `<NoWarn` didn't seem to work.

**Comment by sfoslund** [comment]
You can disable the NETSDK1138 error by setting `CheckEolTargetFramework` to false in your project file. Please feel free to reopen this issue if that property doesn't solve your problem, thanks!

**Comment by bruno-garcia** [comment]
Forgot to update this issue with that. I've been using it and works great:

https://github.com/getsentry/sentry-dotnet/blob/81e3a69e70147ae1122c3c2a1268760136f5406a/Directory.Build.props#L13-L18
