### ISSUE TITLE
project.assets.json file is missing dependencies for Project References when restored.

### ISSUE THREAD

**Issue by sourabhkrishna** [dotnet/sdk#14688]
When building a .net461 project from VS 2019 Latest - performs a successful build and projects.assets.json file has all project references with dependencies listed.
"XX.Credentials.Domain/1.0.0": {
"type": "project",
**"dependencies": {
"XX.Access.DataAccess": "1.0.0",
"XX.Credentials.Formats": "1.0.0"
},**
"compile": {
"bin/placeholder/XX.Credentials.Domain.dll": {}
},
"runtime": {
"bin/placeholder/XX.Credentials.Domain.dll": {}
}
},

When building the same project via Azure Pipelines -> nuget install (v5.8) -> nuget restore -> ms build (v16.8) -> the project.assets.json file misses the project dependencies , hence build failed with assembly missing issues.
"XX.Credentials.Domain/1.0.0": {
"type": "project",
"compile": {
"bin/placeholder/XX.Credentials.Domain.dll": {}
},
"runtime": {
"bin/placeholder/XX.Credentials.Domain.dll": {}
}
},

**Comment by marcpopMSFT** [comment]
Old bug triage. Can you still reproduce this when using msbuild /restore instead of nuget restore as we recommend running restore through msbuild or dotnet.

CC @JonDouglas @nkolev92

**Comment by marcpopMSFT** [comment]
Without a response, we cannot investigate further. Please reply if this is still happening and the suggested workaround above does not work.
