### ISSUE TITLE
`dotnet restore` of solution with .NET 5 SDK requires a package not required by the .NET Core 3.1 SDK

### ISSUE THREAD

**Issue by Zastai** [dotnet/sdk#14689]
We have a locked-down package feed containing only packages approved for use.

I have a solution containing a number of "plain" C# projects (using `Microsoft.NET.Sdk`; some class libraries, one unit test project, one console executable).
`TargetFrameworks` is set to `net472;netcoreapp2.1;netcoreapp3.1`.

With the .NET Core SDK (3.1.404), `dotnet restore` works fine, as does building.

With the .NET 5 SDK (5.0.100), `dotnet restore` fails; `error NU1101: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): SourceName` is reported for every project.

I did see this on Windows, but it seems to have gone away there; however, it is still present on Linux (debian bullseye/sid).

I can reproduce by simply using `dotnet new classlib -f netcoreapp3.1` (with a suitable restrictive nuget.config in effect); that runs an initial restore, which fails with the same error.

(Side note: that `dotnet new` also reports that updated templates are available (3.1.0 -> 5.0.0); that feels bogus as well.)

**Comment by Zastai** [comment]
Looking at https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref it seems a 3.1.10 version of `Microsoft.AspNetCore.App.Ref` was published at about the same time as `5.0.0`.
However, the restore wants exact version 3.1.8.

Could it be that the .NET 5 SDK ships with the 3.1.10 package bundled, but still tries to use a 3.1.8 reference?

**Comment by Zastai** [comment]
Incidentally, is there anything that shows these internal dependencies?

`dotnet list package --include-transitive` does not.

This makes it harder than it should be to set up a curated NuGet package feed.

**Comment by dasMulli** [comment]
Did you by any chance override the used NuGet feeds? (nuget.config or msbuild properties)

The 3.1.* SDKs should carry the reference packs for 3.1 out of the box but other ones should try to download https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/3.1.0

**Comment by Zastai** [comment]
Yes, this is with a locked down nuget.config.

With the Core 3.1 SDK (by specifying 3.1.404 in global.json), everything's fine (because all relevant dependencies are in our company-approved feed).

With the NET 5 SDK, it wants Microsoft.AspNetCore.App.Ref/3.1.8 (exactly). I would not expect the same application with the same target to have an extra dependency just because a newer SDK is in use.

**Comment by marcpopMSFT** [comment]
There is now a flag for disabling this behavior. See more details: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#disabletransitiveframeworkreferencedownloads
