### ISSUE TITLE
[Question] How to get past 'manifest definition does not match the assembly reference' error for .NET Core app?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/sdk#1468]
This is a copy of [this question](https://stackoverflow.com/q/45474152/4077294) on StackOverflow. For convenience, I'll post the content here as well. Please feel free to move this issue to a more appropriate repo if necessary, I wasn't really sure where to ask.

---

I'm trying to use a .NET Core app with a custom build of `System.Collections.Immutable`, which has a different version than the stock build included in `Microsoft.NETCore.App`. The way I'm currently doing this is:

    // Restore packages
    dotnet restore -r win10-x64

    // Publish a self-contained app with all dependencies sitting in the same directory
    dotnet publish -r win10-x64

    cd bin\Debug\netcoreapp1.1\win10-x64\publish

    // Overwrite the System.Collections.Immutable.dll from dotnet publish with my custom build...

    // Run the app!
    ./DotnetLab

If do this without replacing the `System.Collections.Immutable` DLL, the app successfully runs.

If I replace `System.Collections.Immutable`, I get the following error when I run the app:

    Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       at Program.Main(String[] args)

I've done some research and it appears that this can be remedied with something called "binding redirects". I have found lots of answers on SO that tell me how to create an XML config file to setup binding redirects for .NET Framework apps, however I have no idea how to enable them for .NET Core apps.

I have also come across [this answer](https://stackoverflow.com/a/42806831/4077294) that supposedly describes how to enable binding redirects in a .NET Core app, but I copied-and-pasted the lines into my csproj file and still got the error.

**Comment by dsplaisted** [comment]
.NET Core doesn't use binding redirects. However, the assembly version of the runtime dll needs to be at least as high as the version that was used at compilation.  Set the assembly version of the custom build of immutable collections to at least 4.2.1.0 and out will probably work.

**Comment by jamesqo** [comment]
@dsplaisted Thanks for your response. Unfortunately it didn't solve my problem since I can't control the assembly version (that's controlled by the build process at corefx), but I managed to figure out the problem anyway.

**Comment by darraghjones** [comment]
@dsplaisted 

> ... the assembly version of the runtime dll needs to be at least as high as the version that was used at compilation. 

Why do you say this? Is this documented some where? Thanks.

**Comment by steveharter** [comment]
@darraghjones I don't believe the assembly-to-assembly binding rules are documented for .NET Core.

FWIW the actual code to compare is located in [assemblybinder.cpp](https://github.com/dotnet/coreclr/blob/3fca50a36e62a7433d7601d805d38de6baee7951/src/binder/assemblybinder.cpp#L71
)
