### ISSUE TITLE
targeting windows desktop for FX and net5.0-windows requires different SDK

### ISSUE THREAD

**Issue by odhanson** [dotnet/sdk#14716]
Prior to net5, we used Microsoft.NET.Sdk.WindowsDesktop to target windows apps.
when switching to net5.0-windows, we get a warning that WindowsDesktop is no longer needed. But if we target netfx, we still need to use Microsoft.NET.Sdk.WindowsDesktop.

This makes it hard to multitarget using the TargetFramworks property.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;net5.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
```

Adding ```<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>``` will resolve this, but its not easily discoverable.

IMO, we should set ImportWindowsDesktopTargets by default to true, when the target framework is NETFX and UseWindowsForms or UseWPF is true.

**Comment by clairernovotny** [comment]
I just hit this as well. What was the reasoning not to include this as `true` by default? It appears to work when set.

**Comment by eriawan** [comment]
@odhanson 

Try this: use FrameworkReference to add references to .NET Windows Desktop SDK for TFM of .NET Framework 4.7.2.

For example (using your csproj and I updated a bit):

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;net5.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472'">
    <FrameworkReference>Microsoft.WindowsDesktop.App</<FrameworkReference>
  </ItemGroup>
</Project>
```
Note the addition of `FrameworkReference` inside ItemGroup with conditional targetframework. This is to ensure that the additional FrameworkReference is added for target framework of .NET Framework 4.7.2  (the condition of `net472` only).

Please let me know if it works or not.

**Comment by mjrousos** [comment]
This impacts people using the try-convert tool to move to the new csproj file format, too. Try-convert has an option to adopt the SDK-style project but leave the target framework unchanged. The tool will change the project file to use the Microsoft.NET.Sdk and `<UseWPF>` or `<UseWindowsForms>` as appropriate, but if the user opts to stay on a net4* target framework, the project will fail to load due to this.

**Comment by marcpopMSFT** [comment]
Was fixed by https://github.com/dotnet/sdk/pull/15213
