### ISSUE TITLE
dotnet restore hangs indefinitely, spinning CPU

### ISSUE THREAD

**Issue by kierenj** [dotnet/sdk#1473]
Hi - this just started today.  Let me know what further info I can give to diagnose.

`dotnet restore -v diag` gives the following, no error messages:

https://gist.github.com/kierenj/4b4c3c0faf36716ef7971b37824bb776

I then have 4 `dotnet` processes running, each taking 12% CPU, and no network activity that I can see.

`dotnet --version` : `2.0.0-preview2-006497`

**Comment by kierenj** [comment]
My project is stalled until I can work out what to try next here - is there anything I can do to diagnose/debug?  It's a complete hang, repeatable and consistent.  Maybe there are some debug symbols around so I can attach/break and try to share a stack trace?

**Comment by kierenj** [comment]
I just stumbled across https://github.com/dotnet/sdk/issues/1434.  I do indeed have a nested `node_modules` hiding away.

The issue was closed, which is good, but I'd like to see if this is expected.. I used `<SetLinkMetadataAutomatically>false</SetLinkMetadataAutomatically>`, however it still takes a fairly long time (22 seconds) before the restore actually starts - then reports "Restore completed in 37.04ms".  So I guess the time reporting is off too, by around 590%.

Would *this* delay be remedied by the fix?  In what form would the fix materialise - the next 2.0.0 preview?  If I may ask, is there a date in mind for this?

**Comment by dasMulli** [comment]
are you using any myget feeds? I've seen similar behaviour when using some myget feeds with a lot of prerelease versions (dotnet-core) from a location with a bad connection to myget.. but that only was for the first restore using that feed.

**Comment by kierenj** [comment]
I am - 2 or 3 in fact.  I did remedy this completely by moving my client code to a different folder structure.  Do you mean that it might be a combination of the two things - a big subfolder structure, plus some myget feeds?

**Comment by dasMulli** [comment]
Maybe - however you can do `dotnet restore /clp:PerformanceSummary` to get a time summary of the tasks and targets. if none show high numbers, you can assume it's the directory scanning..

**Comment by kierenj** [comment]
With the metadata project property set to false, here's the output:

```
  Restoring packages for C:\git\kierenj\redscope\server\redscope.csproj...
  Generating MSBuild file C:\git\kierenj\redscope\server\obj\redscope.csproj.nuget.g.props.
  Restore completed in 4.84 sec for C:\git\kierenj\redscope\server\redscope.csproj.

Project Evaluation Performance Summary:
    21447 ms  C:\git\kierenj\redscope\server\redscope.csproj   3 calls

Project Performance Summary:
    26429 ms  C:\git\kierenj\redscope\server\redscope.csproj   6 calls
              19301 ms  Restore                                    1 calls
               7083 ms  _GenerateRestoreProjectPathWalk            1 calls
                  2 ms  _GenerateRestoreProjectPathItemsPerFramework   1 calls
                 33 ms  _GenerateRestoreGraphProjectEntry          1 calls
                  6 ms  _GenerateProjectRestoreGraph               1 calls
                  4 ms  _GenerateProjectRestoreGraphPerFramework   1 calls

Target Performance Summary:
        0 ms  _GenerateRestoreGraphProjectEntry          1 calls
        0 ms  _GenerateProjectRestoreGraph               1 calls
        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls
        0 ms  _GetRestoreTargetFrameworksAsItems         1 calls
        0 ms  _GetRestoreSettingsOverrides               1 calls
        0 ms  CheckForImplicitPackageReferenceOverridesBeforeRestore   2 calls
        0 ms  _GetRestoreProjectStyle                    2 calls
        0 ms  _GetProjectJsonPath                        2 calls
        0 ms  _GenerateRestoreProjectPathWalk            1 calls
        0 ms  _GenerateRestoreSpecs                      1 calls
        1 ms  _GenerateRestoreProjectSpec                1 calls
        2 ms  _GenerateRestoreProjectPathItemsPerFramework   1 calls
        4 ms  _GenerateProjectRestoreGraphPerFramework   1 calls
        5 ms  _GenerateRestoreDependencies               1 calls
        7 ms  _GetRestoreTargetFrameworksOutput          1 calls
        8 ms  _GenerateDotnetCliToolReferenceSpecs       1 calls
        8 ms  _LoadRestoreGraphEntryPoints               1 calls
       24 ms  _FilterRestoreGraphProjectInputItems       1 calls
       25 ms  _GetRestoreSettings                        1 calls
       42 ms  _GenerateRestoreGraph                      1 calls
     5040 ms  Restore                                    1 calls
     7075 ms  _GenerateRestoreProjectPathItems           1 calls
    14182 ms  _GetAllRestoreProjectPathItems             1 calls

Task Performance Summary:
        0 ms  Message                                    3 calls
        0 ms  GetRestoreProjectReferencesTask            1 calls
        2 ms  ConvertToAbsolutePath                      2 calls
        3 ms  GetRestoreProjectFrameworks                1 calls
        3 ms  GetRestorePackageReferencesTask            1 calls
        4 ms  RemoveDuplicates                           5 calls
        8 ms  GetRestoreDotnetCliToolsTask               1 calls
       25 ms  GetRestoreSettingsTask                     1 calls
     5040 ms  RestoreTask                                1 calls
    21302 ms  MsBuild                                    6 calls
```

I don't know if that gives new information or not - let me know if there's anything else I can provide that's helpful

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5828
