### ISSUE TITLE
question: abort a thread

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#14748]
hi

I used threads in my .net 4 program.
I'now converted it to .net 5.0 but the methods Abort(), Suspend() and Interrupt() applied on a thread all throw an exception telling they are 'not supported on this platform'

How do you terminate a thread completely in .net 5.0 when you can't use any of those  3 methods?

thx
Jessica

**Comment by davidfowl** [comment]
Cooperatively using a volatile bool

**Comment by ancientmagicwizard** [comment]
Hi

I'm a beginner in programming.
If 'thread' is my created thread variable and the thread is also started and running, can you give me a small code example of what you mean?

**Comment by davidfowl** [comment]
What is your thread doing? Show me a sample of the code and I might be able to help.

**Comment by ancientmagicwizard** [comment]
My thread runs a windows form created by win forms designer to'use as splash screen.

The thread runs a method that does just  1 line:

Application.Run(new SplashScreenForm());

I want to terminate the thread at a specific code line in my program but as you read, I can't use Abort() in .net 5
In .net 4 I just called Abort() and the thread was killed and the windows form also removed from the screen.

**Comment by ancientmagicwizard** [comment]
Are you going to help or do I have to wait until you sucked all your microshit friends dick?
