### ISSUE TITLE
The type or namespace name 'Fakes' does not exist in the namespace 'System' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by tuphamminh** [dotnet/sdk#14757]
I got this issue when porting the Unit Test Project from .NET Framework to .NET core 3.1.
I do not understand what caused the issue. 
![image](https://user-images.githubusercontent.com/75245248/100588294-45ee0c80-3324-11eb-9571-734085554f4d.png)

Could you please solve it if have any?
I used VS Studio 2019 , v16.8.2

**Comment by agwanyaseen** [comment]
This solution might be weired, but have you tried 
**using System.fakes**
**using System.Xml.Linqfakes**

**Comment by muskankhedia** [comment]
I also face the same issue with the System Package, though it works well for System.Net and System.ServiceProcess Package.
![image](https://user-images.githubusercontent.com/36980003/219571321-f9894367-5bc0-4baa-b38e-a6e339047ea6.png)

**Comment by marcpopMSFT** [comment]
Old issue triage: @jfleisher @ocalles do ya'll own fakes and where can I route this issue?  I assume it's not reproing anymore since this was 3.1 but wanting to route it to the right place.

**Comment by marcpopMSFT** [comment]
No response. Closing. Please ping if this is still an issue.
