### ISSUE TITLE
GenerateBundle failure during Folder Publish of .NET 5.0 app with MongoDB.Driver.Core pkg

### ISSUE THREAD

**Issue by sujitnayak** [dotnet/sdk#14776]
Repro steps:
1. Install VS 16.8 which installs .NET 5.0 SDK.
2. In VS, go to Publish window and create a Folder profile with Single File = true and Self Contain = false.
3. Publish the app with this Folder Profile.
4. Publish fails due with GenerateBundle task failing with error about multiple entries with same bundle path:

C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1016,5): error MSB4018: The "GenerateBundle" task failed unexpectedly.
System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath
   at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)
   at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Users\sujitn\source\repos\ConsoleApp6\ConsoleApp6\ConsoleApp6.csproj]

**Comment by sujitnayak** [comment]
Files being bundle (with duplicates):

FilesToBundle
    C:\Users\sujitn\source\repos\ConsoleApp6\ConsoleApp6\obj\Debug\net5.0\win-x86\apphost.exe
        CopyToPublishDirectory = Always
        IsKeyOutput = True
        RelativePath = ConsoleApp6.exe
        TargetPath = ConsoleApp6.exe
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\snappy32.dll
        CopyToPublishDirectory = PreserveNewest
        RelativePath = snappy32.dll
        TargetPath = snappy32.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\snappy64.dll
        CopyToPublishDirectory = PreserveNewest
        RelativePath = snappy64.dll
        TargetPath = snappy64.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\libzstd.dll
        CopyToPublishDirectory = PreserveNewest
        RelativePath = libzstd.dll
        TargetPath = libzstd.dll
    obj\Debug\net5.0\win-x86\ConsoleApp6.dll
        CopyToPublishDirectory = PreserveNewest
        RelativePath = ConsoleApp6.dll
    C:\Users\sujitn\source\repos\ConsoleApp6\ConsoleApp6\bin\Debug\net5.0\win-x86\ConsoleApp6.deps.json
        CopyToPublishDirectory = PreserveNewest
        RelativePath = ConsoleApp6.deps.json
    C:\Users\sujitn\source\repos\ConsoleApp6\ConsoleApp6\bin\Debug\net5.0\win-x86\ConsoleApp6.runtimeconfig.json
        CopyToPublishDirectory = PreserveNewest
        RelativePath = ConsoleApp6.runtimeconfig.json
    C:\Users\sujitn\.nuget\packages\dnsclient\1.3.1\lib\netstandard2.1\DnsClient.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = DnsClient.dll
        NuGetPackageId = DnsClient
        NuGetPackageVersion = 1.3.1
        PathInPackage = lib/netstandard2.1/DnsClient.dll
        RelativePath = DnsClient.dll
    C:\Users\sujitn\.nuget\packages\mongodb.bson\2.11.4\lib\netstandard2.0\MongoDB.Bson.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = MongoDB.Bson.dll
        NuGetPackageId = MongoDB.Bson
        NuGetPackageVersion = 2.11.4
        PathInPackage = lib/netstandard2.0/MongoDB.Bson.dll
        RelativePath = MongoDB.Bson.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\lib\netstandard2.0\MongoDB.Driver.Core.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = MongoDB.Driver.Core.dll
        NuGetPackageId = MongoDB.Driver.Core
        NuGetPackageVersion = 2.11.4
        PathInPackage = lib/netstandard2.0/MongoDB.Driver.Core.dll
        RelativePath = MongoDB.Driver.Core.dll
    C:\Users\sujitn\.nuget\packages\mongodb.libmongocrypt\1.0.0\lib\netstandard1.5\MongoDB.Libmongocrypt.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = MongoDB.Libmongocrypt.dll
        NuGetPackageId = MongoDB.Libmongocrypt
        NuGetPackageVersion = 1.0.0
        PathInPackage = lib/netstandard1.5/MongoDB.Libmongocrypt.dll
        RelativePath = MongoDB.Libmongocrypt.dll
    C:\Users\sujitn\.nuget\packages\newtonsoft.json\12.0.3\lib\netstandard2.0\Newtonsoft.Json.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = Newtonsoft.Json.dll
        NuGetPackageId = Newtonsoft.Json
        NuGetPackageVersion = 12.0.3
        PathInPackage = lib/netstandard2.0/Newtonsoft.Json.dll
        RelativePath = Newtonsoft.Json.dll
    C:\Users\sujitn\.nuget\packages\sharpcompress\0.23.0\lib\netstandard2.0\SharpCompress.dll
        AssetType = runtime
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = SharpCompress.dll
        NuGetPackageId = SharpCompress
        NuGetPackageVersion = 0.23.0
        PathInPackage = lib/netstandard2.0/SharpCompress.dll
        RelativePath = SharpCompress.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\libzstd.dll
        AssetType = native
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = libzstd.dll
        NuGetPackageId = MongoDB.Driver.Core
        NuGetPackageVersion = 2.11.4
        PathInPackage = runtimes/win/native/libzstd.dll
        RelativePath = libzstd.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\snappy32.dll
        AssetType = native
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = snappy32.dll
        NuGetPackageId = MongoDB.Driver.Core
        NuGetPackageVersion = 2.11.4
        PathInPackage = runtimes/win/native/snappy32.dll
        RelativePath = snappy32.dll
    C:\Users\sujitn\.nuget\packages\mongodb.driver.core\2.11.4\runtimes\win\native\snappy64.dll
        AssetType = native
        CopyLocal = true
        CopyToPublishDirectory = PreserveNewest
        DestinationSubPath = snappy64.dll
        NuGetPackageId = MongoDB.Driver.Core
        NuGetPackageVersion = 2.11.4
        PathInPackage = runtimes/win/native/snappy64.dll
        RelativePath = snappy64.dll

**Comment by agocke** [comment]
This looks by design. References with duplicate names aren't supported for single-file publishing.

**Comment by xiaoyuvax** [comment]
Same problem:https://github.com/dotnet/core/issues/5615
what does "the duplicated names" refer to?
how or where can i check for duplicate names?

**Comment by sujitnayak** [comment]
The list of files that are going into the Single-File Bundle needs be unique. If for any reason, the same file is getting added into the bundle more that 1 time, you will get this specific error. This was a limitation in 5.X SDK. Using 6.X SDK should not have this issue as it filters out duplicate files references.
