### ISSUE TITLE
dotnet publish does not copy all files

### ISSUE THREAD

**Issue by sanchobear** [dotnet/sdk#1477]
# Repro:
- VSTS Teambuild  Web Project Sdk="Microsoft.NET.Sdk.Web"
- dotnet restore
- dotnet publish
# Expected behavior:
Published wwwroot folder should contain dirs/files aquired during prepublish bower install and dotnet bundle steps
# Actual behavior:
Published wwwroot (a/project/wwwroot) folder contains only dirs/files from tfs get, while the source folder (s/project/wwwroot) contains the aquired files
# Environment:
$dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by livarcocc** [comment]
Moving this to the WebSDK for them to have a look at it first.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#290
