### ISSUE TITLE
Building sdk project fails when run as Local System account

### ISSUE THREAD

**Issue by alexperovich** [dotnet/sdk#1482]
## To Reproduce

Use PsExec to run cmd.exe as the local system account and run the following in an empty folder:

```
dotnet new lib
nuget restore *.csproj
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
```

## Expected Behavior
Builds fine

## Actual Behavior
Many errors about missing types

Running `dotnet restore` and `dotnet build` doesn't cause this issue.
These problems don't occur when running as a different account than Local System

**Comment by livarcocc** [comment]
You don't say which version of the SDK this happened. I just tried with the latest version of VS and the latest version of the CLI and could not repro it.

Going to close it. If you can still repro it in the circumstances I described above, please, re-activate.
