### ISSUE TITLE
[Localization] Question about placeholder

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#14832]
String Resource ID | 0; "ResponseFileNotFound"
-- | --
Source String | Response file not found '{0}'
Filename | Cli\dotnet\CommandLineValidation\xlf\LocalizableStrings.xlf
Question | does '{0}' refer to some location and the whole sentenc mean"Response file not found in '{0}'"?

**Comment by cristianosuzuki77** [comment]
vcq 343755

**Comment by crsuzukimsft** [comment]
@wli3 Could you please triage?

**Comment by wli3** [comment]
Sorry for the delay. '{0}' refers to the location of the response file. If the user want to use response file `c:\myfile.rsp`, but that file does not really exist. It will cause error "Response file not found 'c:\myfile.rsp'"
