### ISSUE TITLE
It would be useful to have option for not generating TargetPlatformAttribute / SupportedOSPlatformAttribute

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/sdk#14836]
Runtime repo no longer removing the platform from the TargetFramework string for net5.0 and above, this causes SupportedOSPlatformAttribute & TargetPlatformAttributes added by SDK for targeted platform in AssemblyInfo.cs file. This is useful for the Platform compat analyzer evaluate call site attributes. But there is some edge cases where we wouldn't like to generate the attributes and it would be great if SDK provide such option [see more info](https://github.com/dotnet/runtime/pull/45504#discussion_r535739860)  

Related to https://github.com/dotnet/runtime/issues/44257, https://github.com/dotnet/sdk/issues/13453

cc @jeffhandley @ViktorHofer @Anipik  @dsplaisted @sfoslund

**Comment by marcpopMSFT** [comment]
@buyaa-n @jeffhandley I assume you've worked around this at this point and we can just leave this on the backlog as lower priority. Please confirm.

**Comment by jeffhandley** [comment]
This still causes some frustration for us in `dotnet/runtime`, but we've indeed worked around it. If there are any reports from external customers, that would be a good signal to increase the priority.
