### ISSUE TITLE
Provide an SDK download under a free software license

### ISSUE THREAD

**Issue by JonasT** [dotnet/sdk#1485]
The current only available download for a recent .NET Core SDK ( https://www.microsoft.com/net/core/preview#linuxfedora ) seems to be under a very bogus, very lengthy license forbidding a huge bunch of things, including:

- disassembling / analyzing the software
- working around any sort of technical limitations (??? what)
- using the software for commercial software hosting services (this one is even weirder!)
- **rent, lease or lend the software**

If I got this right from the internet, .NET Core binaries are independent through static compilation and hence **include parts of the SDK under the above license** which would make all those things forbidden for any .NET Core program.

That seems pretty problematic. As a solution, I suggest provide a fully packaged SDK under a truly free license. (e.g. what's wrong with the MIT license that is already used for the actual source code?)

**Comment by livarcocc** [comment]
We are under the MIT license and that shows in the license.txt file in the root of the repo.

**Comment by JonasT** [comment]
@livarcocc yes, but the .NET Core SDK as provided here https://www.microsoft.com/net/core/preview#linuxfedora isn't, and that's what everyone uses, right?

Is there an alternate SDK download that people can just install which is MIT licensed as you claim? Should all Linux distributions just build their own packages and duplicate the effort if they want free packages?

Visual Studio Code has the same issue by the way. (and misleads about it, the website claims it's "free" right above a download button to a non-free version, in the common open-source community use of the word) Why can't you provide a proper prebuilt version for the open-source variant?

**Comment by livarcocc** [comment]
@JonasT where are you seeing this licensing information on the website above. Can you point me to it? It may help me figuring out a better pointer to you. I just don't want to point you to a different location and realize I missed the licensing notice there as well.

Also, github.com/dotnet/cli has builds for the SDK.

Master has nightlies, but we have branches for all our releases, for instance, the latest one available came out of the release/2.1 branch.

**Comment by livarcocc** [comment]
Also, https://www.microsoft.com/net/download/linux.

**Comment by JonasT** [comment]
@livarcocc I just checked again and it seems I was either mistaken when originally filing this, or it has been changed (the ticket is a bit old by now) and you're right, it only says MIT everywhere :smile:

As a note though, https://www.microsoft.com/net/download/linux specifically doesn't have any obvious link to the licensing at all before downloading, that might be worth fixing. However, I just tested the Windows installer and it states very clearly that it's MIT licensed, so that's awesome!

Sorry for the misguided answer, it seems all is fine

**Comment by svick** [comment]
> As a note though, https://www.microsoft.com/net/download/linux specifically doesn't have any obvious link to the licensing at all before downloading, that might be worth fixing.

Why? As far as I can tell, that's not a common thing to do among open source projects. For example, I checked [Firefox](https://www.mozilla.org/en-US/firefox/) and [LibreOffice](https://www.libreoffice.org/download/download/) and they don't mention their license prominently on their download pages.

**Comment by JonasT** [comment]
@svick it's not that important for Windows installers, but for .rpm it's not that trivial to see what license it is *before* installing it, so it's just a common courtesy to tell beforehand.

For firefox, click Legal (at the very bottom) > Downloadable Software Notices for Firefox. States it's MPL.

LibreOffice: the very bottom kinda hints at it with "This does not include the source code of LibreOffice, which is licensed under the Mozilla Public License v2.0."

Visual Studio Code also shows it, actually directly below the download button.

Usually, you'd expect to be able to find that information somewhere on the website, even if not super prominent. E.g. a mention in the "Terms of Service" section would be enough. Right now, the .NET site only has a very generic section on "Notice Specific to Software Available on this Website" there which doesn't mention the actual license of it.

**Comment by livarcocc** [comment]
cc @leecow for any potential website changes.

**Comment by leecow** [comment]
Thanks for the feedback @JonasT - will have a look and figure out where this might be presented.
