### ISSUE TITLE
[Linux-only] aspnetcore publish can produce 2 web.configs

### ISSUE THREAD

**Issue by scott-the-programmer** [dotnet/sdk#14853]
# Description

Asp net core projects being published on linux have the possibility to publish 2 disjoint web.config files. This happens when the project references `Web.config`. It appears that the publish task ignores this file, resulting in both `Web.config` and `web.config` in the publish directory.

e.g.
![image](https://user-images.githubusercontent.com/19235440/101271131-16884580-37e5-11eb-8488-4e9961834a2b.png)

Web.config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.web>
    </system.web>
</configuration>
```

web.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\dotnet-linux-publish-example.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
<configuration>
```

Note this behavior is not observed on Windows or OSX

# Downstream affects

Due to this behavior, any configuration in `Web.config` will not be available in `web.config`. Following that - if the published artifacts are deployed (say to azure app services), i've noticed that `web.config` is discarded, resulting in a corrupt deployment

# How to reproduce

This can be reproduced by publishing an example web api project in the .net 5.0 sdk docker container

https://github.com/scott-the-programmer/dotnet-linux-publish-example

```bash
docker build . -t example
docker run -it example bash
```

observe that there are 2 web.configs in the publish dir

**Comment by scott-the-programmer** [comment]
From the looks of it - i think the problem stems from `TransformWebConfig` 

```c#
            Log.LogMessage(MessageImportance.Low, $"Configuring the following project for use with IIS: '{PublishDir}'");

            XDocument webConfigXml = null;

            // Initialize the publish web.config file with project web.config content if present. Else, clean the existing web.config in the
            // publish folder to make sure we have a consistent web.config update experience.
            string projectWebConfigPath = null;
            if (!string.IsNullOrEmpty(ProjectFullPath))
            {
                projectWebConfigPath = Path.Combine(Path.GetDirectoryName(ProjectFullPath), "web.config");
            }

            string publishWebConfigPath = Path.Combine(PublishDir, "web.config");
            publishWebConfigPath = Path.GetFullPath(publishWebConfigPath);

            if (File.Exists(publishWebConfigPath))
            {...
```

I'm happy to pick this issue up when i find sometime!

**Comment by joeloff** [comment]
FYI @vijayrkn

**Comment by mcetkovsky** [comment]
Might be related to https://github.com/dotnet/sdk/issues/14886
