### ISSUE TITLE
Blazor WASM publish on IIS => memory access out of bounds, Error loading ICU asset

### ISSUE THREAD

**Issue by denscho** [dotnet/sdk#14868]
Since the last Visual Studio Preview update to 16.9.0 Preview 1.0 I get the following error from the IIS-Server in our local network:
![image](https://user-images.githubusercontent.com/66822070/101404696-47e13e00-38d7-11eb-9a63-2bb7ee2b66c5.png)
On my local machine everything works fine with the IIS Express integrated in Visual Studio. But when I publish the blazor.server project to the IIS-Server in our network I get this message when I try to access the page. So it doesn't start at all

When I jump to the rows mentioned in the message I get the following code snipets
![image](https://user-images.githubusercontent.com/66822070/101404738-592a4a80-38d7-11eb-836d-32e93cee6735.png)
![image](https://user-images.githubusercontent.com/66822070/101404749-5cbdd180-38d7-11eb-8602-46cb8b874368.png)

I tried to access the webpage directly on the server using "localhost" or "127.0.0.1" and it works without any problems. If I try to access the page from the same browser-instance using the IP-Address "192.168.50.3" I get the same error as from remote clients. Any hints on what I could do (or check) would be much appreciated :-)

**Comment by sfoslund** [comment]
This issue was moved to dotnet/aspnetcore#28639
