### ISSUE TITLE
How do i set the cipherspec preference for .NET Core applications on Linux

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/sdk#14881]
On Windows i can set the cipherspec preference by editing Windows group policy. How do i set the same on Linux?

**Comment by sfoslund** [comment]
@wli3 do you know where we should direct this question?

**Comment by ramsubbaraoc** [comment]
@wli3 @sfoslund Please can you assign this to someone.It is just a query on how to set the cipherspec preference order on Linux. I tried using openssl command and it didn't help. Please can you tell me on how to set the cipherspec preference order for .NET Core applications. On windows it is straight forward i.e editing the windows group policy. 

Thanks

**Comment by ramsubbaraoc** [comment]
@GrabYourPitchforks Please can you suggest on this. Thank you

**Comment by wli3** [comment]
@blowdart ?

**Comment by blowdart** [comment]
@bartonjs

**Comment by ramsubbaraoc** [comment]
Any suggestions on this. Thank you

**Comment by GrabYourPitchforks** [comment]
.NET respects the system-wide OpenSSL configuration. See https://docs.microsoft.com/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux for more information and for an example of what the configuration file looks like.

/cc @krwq for further info.

**Comment by krwq** [comment]
For global settings you do it per link above. If you want to do it for TLS session then use:
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.ciphersuitespolicy?view=net-5.0#System_Net_Security_SslClientAuthenticationOptions_CipherSuitesPolicy

For HttpClient you will need to use it with https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=net-5.0

**Comment by wli3** [comment]
Thanks all. Closing this issue since the question is answered.

**Comment by ramsubbaraoc** [comment]
Thanks all.
