### ISSUE TITLE
Unable to find installed framework when using x64 runtime

### ISSUE THREAD

**Issue by chaoticsoftware** [dotnet/sdk#14891]
I started getting the following error in my Azure pipeline, when running `dotnet test` in the Win2019 image. The same thing runs in the Win2016 image:

> Testhost process exited with error: The specified framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       [PROJECT-PATH]\bin\release\netcoreapp3.1\win7-x64\shared\Microsoft.AspNetCore.App
>   - Alternatively, install the framework version '3.1.0'.
> . Please check the diagnostic logs for more information.
> 
> Test Run Aborted.

The thing is that as far as I can tell the runtime is installed.

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.402
>  Commit:    9b5de826fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.402\
> 
> Host (useful for support):
>   Version: 5.0.0
>   Commit:  cf258a14b7
> 
> .NET SDKs installed:
>   3.1.100 [C:\Program Files\dotnet\sdk]
>   3.1.402 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

I can also repro the same thing locally:
> dotnet tool restore
> dotnet restore -v:m -r win7-x64
> dotnet build -c release --no-restore --nologo -r win7-x64 -v:m -ds -p:Version=20.12.8.2
> dotnet test --no-restore --no-build -c release --runtime win7-x64

Interestingly, if I omit the runtime specification, or if I use `win7` instead, it will work just fine. I can also provide the host trace, in case it's helpful.

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2677
