### ISSUE TITLE
In .NET 6 Android projects, <ResolvePackageAssets/> returns linux native libraries

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#14908]
For example, a .NET 6 Android app adding:
```
<PackageReference Include="akavache" Version="6.0.30"/>
```
This package brings in a lot of dependencies, and eventually this native library:
```
C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so
```

When I review the [.binlog](https://github.com/dotnet/sdk/files/5667662/msbuild.zip), I see:
```
Task ResolvePackageAssets
...
OutputItems
    NativeCopyLocalItems
        C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so
            AssetType = native
            CopyLocal = true
            DestinationSubPath = libe_sqlite3.so
            NuGetPackageId = SQLitePCLRaw.lib.e_sqlite3.linux
            NuGetPackageVersion = 1.1.11
            PathInPackage = runtimes/linux-arm64/native/libe_sqlite3.so
```
I think `linux` native libraries are being brought in, even though the `$(RuntimeIdentifier)` was `android.21-arm64` in this example. I can see where the Windows and OSX native libraries were excluded.

We currently have this workaround, which I would like to remove, thanks!

https://github.com/xamarin/xamarin-android/blob/97190b6cc56ef81be82bab48737155089a16f500/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1874-L1878

**Comment by akoeplinger** [comment]
I think this is because linux is a parent of android in the RID graph: https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtimeGroups.props#L22-L23

/cc @marek-safar

**Comment by jonathanpeppers** [comment]
I changed `dotnet\sdk\6.0.100-alpha.1.20562.2\RuntimeIdentifierGraph.json` locally, and it fixed the problem.

Updated several lines such as:
```diff
    "android": {
      "#import": [
-        "linux"
+        "unix"
      ]
    },
    "android-arm": {
      "#import": [
        "android",
-        "linux-arm"
+       "unix-arm"
      ]
    },
```

I can send a PR based on what I see in https://github.com/dotnet/runtime/pull/45442; it looks straightforward.

Let me know if someone else beats me to it, thanks.

**Comment by wli3** [comment]
The issue is tracking here https://github.com/xamarin/xamarin-android/pull/5386
