### ISSUE TITLE
Pack targets are no longer being overridden on adding a package reference to NuGet.Build.Tasks.Pack nupkg

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#1491]
[out.txt](https://github.com/dotnet/sdk/files/1226157/out.txt)
Repro steps:
dotnet new classlib
Add a package reference to NuGet.Build.Tasks.Pack nupkg 4.4.0-preview1-4422 ([nuget-build feed on myget](https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Build.Tasks.Pack/4.4.0-preview1-4422))
dotnet pack (using dotnet 2.0 RTM)

The pack targets that are shipped with dotnet sdk 2.0 end up being used instead of the ones from the nupkg.

attached a diag log from packing the csproj (you can search for the resolved value of the property NuGetBuildTasksPackTargets)

CC: @nguerrera @dsplaisted

**Comment by rohit21agrawal** [comment]
ping...

**Comment by rainersigwald** [comment]
I think this is just what I fixed in #1526 (it seems to work on my machine with that patched).
