### ISSUE TITLE
No warnings generated for netstandard1.0 project referencing a net461 project

### ISSUE THREAD

**Issue by mishra14** [dotnet/sdk#1492]
Ported from https://github.com/NuGet/Home/issues/5503

reported by @natidea

Original text -
I’m observing that netstandard1.0 projects that reference net461 do not generate any compatibility warnings. Similarly, netstandard1.6 referencing net45 projects does not generate any warnings. (Not sure which of those combinations is supposed to be invalid looking at https://docs.microsoft.com/en-us/dotnet/standard/net-standard )

Seems to repro with VS Preview 3 (d15rel.26621.2) with CLI Preview installed (2.0.0-preview3-006546)

**Comment by livarcocc** [comment]
Commented on the origignal nuget issue, but commenting here as well:

@mishra14 How is this something that the SDK should do? The compatibility matrix between TFM lives entirely in NuGet and is checked during restore. How will the SDK even know what is or isn't compatible without looking at the project.assets.json?

I don't believe we want to start duplicating the compatibility matrix. Can you help me understand how/why you feel this should happen in the SDK?
