### ISSUE TITLE
Common property logic (like Directory.Build.props, but more flexible)

### ISSUE THREAD

**Issue by vuplea** [dotnet/sdk#14931]
It would be nice to be able to be able to apply some properties automatically for our projects.

Directory.Build.props lets us define common properties, but without any access to project specifics, which would enable conditional properties.

Example of needs:
* The dotnet/sdk repo itself is able to do this, at least for [IsTestProject](https://github.com/dotnet/sdk/blob/master/Directory.Build.props#L22). I am guessing it accomplishes this though `Arcade.Sdk`? I've found no way to do this through `NET.Sdk`.

* We would like to disable `AppendTargetFrameworkToOutputPath`, but only for a particular `TargetFramework`. We've found a workaround for this: If we use `TargetFrameworks` instead of `TargetFramework`, probably because of how `CrossTargeting` works, we have access to `TargetFramework` in `Directory.Build.props` (doesn't sound too solid).

* Most of our projects output to a common `OutputPath`. We define `OutputPath` in every such `csproj` as of now, because some projects must have a way to opt-out (e.g. if they have `IsTestProject == true`, or our theoretical own `UseCommonOutput != true`).

I don't exactly have an idea of how such a feature would look like.
The bare minimum, i.e. `<Import Project="$(CustomBeforeSdkTargets)" Condition="'$(CustomBeforeSdkTargets)' != ''">` somewhere early in `Sdk.targets` would be good for us, though obviously this is a narrow-visioned suggestion.

Note: I will also mention the obvious workaround to have the `Import` element above at the end of each `csproj`.

**Comment by vuplea** [comment]
Thanks, @tmds. Forgot to mention the obvious `Directory.Build.targets`. We already use it, but for properties/items it is hit and miss:  we use it for `PackageReference`, `Compile` and `DefineConstants`, but for `OutputPath`and `AppendTargetFrameworkToOutputPath` it does not work. This is beacuse `Sdk.targets` and `Microsoft.Common.targets` derive properties evaluated before `Directory.Build.targets'. So I'm guessing it's kindof unofficial to use it for properties/items (rather than targets), even though a lot of projects do this.

**Comment by dsplaisted** [comment]
You may be able to use the `BeforeTargetFrameworkInferenceTargets` property for this.  It is imported rather early in the .targets evaluation if it is set.  You can set the property in your Directory.Build.props file.

**Comment by vuplea** [comment]
Thanks again, @dsplaisted! We will use the mentioned hook in Directory.Build.props (like in the [runtime](https://github.com/dotnet/runtime/blob/75c0b990ce249d6c37adfa4037ef3ba5b280085c/src/libraries/Directory.Build.props#L14) project).

It is really useful yet slightly obscure 🌝
