### ISSUE TITLE
VS2017 15.3.0 Preview 7.1 shows error when referencing netstandard2.0 library, but it compiles

### ISSUE THREAD

**Issue by andrecarlucci** [dotnet/sdk#1493]
Hi guys,

I'm using VS2017 15.3.0 Preview 7.1.
File -> New Project -> Asp.Net Core Web App using Asp.Net Core 2.0
File -> New Project -> Class Library, netstandard 2.0

Add Library reference to Web App and try to use it.

**Visual Studio shows me the class usage as an error, although it compiles and runs just fine.**  Error List is empty, nothing on output window too.

Referencing a netstandard 2.0 from another netstandard 2.0 works and no warning error is shown.
I also disabled resharper just in case.

Any thoughts?

![image](https://user-images.githubusercontent.com/66689/29337719-c4fcaf86-81e8-11e7-9efe-ca68be853136.png)

**Comment by DaniilSokolyuk** [comment]
I have same problem if in net461 reference projects netstandard2.0;net461

**Comment by davidfowl** [comment]
Looks like a resharper issue? Does it happen without resharper?

**Comment by DaniilSokolyuk** [comment]
@davidfowl Thank you, its helped me

**Comment by andrecarlucci** [comment]
Hi @davidfowl 

Yes! I had disabled resharper only here:

![image](https://user-images.githubusercontent.com/66689/29362736-80ab7a44-8263-11e7-9f41-eaf4e86c6ca9.png)

It seems that **you also have to suspend it in Visual Studio options** make it stop for sure:

![image](https://user-images.githubusercontent.com/66689/29362811-cbd90bee-8263-11e7-910e-e0d46617f22a.png)

Once again, thanks a lot.
