### ISSUE TITLE
Reconsider implementation of _BlockWinMDsOnUnsupportedTFMs target

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/sdk#14942]
With the removal of WinRT support from .NET 5, the .NET SDK added the target _BlockWinMDsOnUnsupportedTFMs to ensure that winmd references were no longer passed to the C# compiler when targeting .NET 5+.  At the time this target was implemented, it was too late in the product cycle to address this in the C# compiler itself.  Unfortunately, there are many scenarios where a winmd reference can sneak into a project, causing a build break and presenting the sometimes misleading message:
NETSDK1130: Referencing a Windows Metadata component directly when targeting {0} is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.

I recommend modifying the target to instead:

- Ignore and remove winmd references during compilation, to prevent use of WinRT types that will fail at runtime.  
- Issue a warning (not an error) that winmd references are no longer supported, possibly mentioning cswinrt if build errors do occur.

```
    <Target Name="_BlockWinMDsOnUnsupportedTFMs"
            AfterTargets="PreBuildEvent"
            DependsOnTargets="ResolveReferences"
            Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), '5.0'))">
        <!--Winmdobj generation is never supported-->
        <NETSdkError Condition="'$(OutputType)' == 'winmdobj'"
          ResourceName="WinMDObjNotSupportedOnTargetFramework"
          FormatArguments="$(TargetFrameworkMoniker)" />
        <!--Winmd references should be removed, rather than failing the build-->
        <Warning Condition="'%(ReferencePath.Extension)' == '.winmd'"
            Text="Windows Metadata component references are ignored when targeting $(TargetFrameworkMoniker)."/>
        <ItemGroup>
            <WinMDReferencePath Include="@(ReferencePath)" Condition="'%(ReferencePath.Extension)' == '.winmd'" />
            <ReferencePath Remove="@(WinMDReferencePath)"/>
        </ItemGroup>
    </Target>

```

**Comment by Scottj1s** [comment]
see also:
https://github.com/microsoft/CsWinRT/issues/628
https://github.com/dotnet/sdk/issues/14267

**Comment by clairernovotny** [comment]
WebView2 is breaking for me on RSS Bandit on 16.8 / 5.0.100 but working with 16.9 / 5.0.200-preview locally. 

I'm using the latest WebView2 nuget package in a WinForms app.... I think the error is wrong since it does work locally. It seems to be incorrectly detecting something here.

**Comment by angelazhangmsft** [comment]
Proposed solution: When checking for the NETSDK1130 error, only generate the error for WinMD references which don’t have Implementation metadata.  If there are any WinMD files with Implementation metadata, then remove them from the ReferencePath item so that they aren’t passed to the C# compiler.  Also, the filename and/or path of the WinMD file should probably be displayed as part of the error message.

@dsplaisted Do we move this issue from Discussion into a 5.0.x milestone?

cc @AdamBraden

**Comment by marcpopMSFT** [comment]
@dsplaisted , since you made a lot of changes a couple months ago to improve this blockage, can we now close this issue?

**Comment by dsplaisted** [comment]
Yes, I think we can close this.
