### ISSUE TITLE
The target framework for Winforms VB .Net Core app is displayed '.Net 5.0 ' when creating app with choosing '.Net 6.0 (Preview)' 

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/sdk#14943]
**Visual Studio Version**:
16.9.0 Preview 3.0 [30810.175.main]

**Steps to Reproduce**:
1. Check the preview feature "Show all .Net Core templates in the New project dialog(required restart)" in VS: Tools->Options->Environment->Preview Features, re-start VS
2. Launch VS, create a Winforms .Net Core VB application with choosing Target Framework: '.Net 6.0 (Preview)'
3. Go to app's Properties ->Application page, to check Target Framework value

**Expected Behavior**:
It displays .Net 6.0 for Target Framework in app's Properties ->Application page
**Actual Behavior**:
It displays .Net 5.0, and it's same as .vbproject file: net5.0-windows
![image](https://user-images.githubusercontent.com/26474449/101887865-6184cd00-3bd8-11eb-87f0-86411b079ac8.png)

**Comment by marcpopMSFT** [comment]
16.9 will only be shipping with 5.0 support. Do you have an SDK build from master that installed 6.0 templates in it?

**Comment by Olina-Zhang** [comment]
> 16.9 will only be shipping with 5.0 support. Do you have an SDK build from master that installed 6.0 templates in it?
Yes, installed .Net 6.0 SDK build from master branch. In addition, this issue cannot repro Winforms .Net Core C# application.

**Comment by John-Qiao** [comment]
This issue still occurs in the latest Dev17 17.0.0 Preview 3.0 [31513.351.main], when creating a .NET 6.0 VB Winforms project, there will be a popup dialog: "To run this application, you must install .NET Core.  The framework ‘Microsoft.WindowsDesktop.App’, version 5.0.0 was not found.  Would you like to download it now?". As I selected .NET 6.0 framework when creating project, so I clicked No to close this dialog, but the form designer cannot be opened successfully, I think I need to change the project's framework to .NET 6.0. But after I changed the framework version to .NET 6.0 in project's Properties page manually, I still cannot open the form designer, and received the "Timed out while connecting to named pipe" message, please check below gif file:
![TestResult](https://user-images.githubusercontent.com/45864985/125746422-fffd8535-2312-4ee1-ba65-e0c55e7112da.gif)

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest Dev17 build: 17.0.0 Preview 4.0 [31623.283.main], it doesn't repro now. Closing this issue now.
![VB_Winforms_6 0](https://user-images.githubusercontent.com/26474449/130565403-85a8742e-6538-4c81-b266-969c1927e73f.gif)
