### ISSUE TITLE
*.deps.json missing some project dependencies

### ISSUE THREAD

**Issue by jeffason** [dotnet/sdk#14946]
Hello.  I am working on a .NET5 library that has many dependencies on other .NET5 projects.  I am seeing an issue where the project's `.deps.json` file doesn't contain all of the project dependencies that exist in the .csproj.  I am using dotnet-sdk-5.0.100 on Windows 10 and this build environment:

![image](https://user-images.githubusercontent.com/3349419/101955267-1f9d5c00-3bc3-11eb-91a7-b6900d7ed726.png)

**Comment by dsplaisted** [comment]
Hi @jeffason,

Is it possible for you to [share a binlog](https://aka.ms/binlog) of your project's build, as well as the deps.json it's generating?

What problem is the fact that all the dependencies aren't listed causing?  Does the app fail to run correctly, or are you trying to inspect the deps file yourself to find its dependencies, or what?

Thanks!

**Comment by jeffason** [comment]
Attached the .binlog and .deps.json - [deps.json.issue.zip](https://github.com/dotnet/sdk/files/5690943/deps.json.issue.zip)

The .deps.json is used by https://github.com/AaronRobinsonMSFT/DNNE and I'm running into an error where my dependencies are failing to load.  I reviewed the contents of .deps.json myself and noticed some dependencies not listed (`BFDeferredSim` for example)

**Comment by jeffason** [comment]
Cross-linking issue I opened in the other repo - https://github.com/AaronRobinsonMSFT/DNNE/issues/56

**Comment by AaronRobinsonMSFT** [comment]
@dsplaisted Please let me know if this is something that DNNE is causing to happen. I wouldn't think it is doing anything during the `.deps.json` generation phase of the build but could be mistaken.

**Comment by dsplaisted** [comment]
@jeffason Can you generate a binlog from the command line and share it?  The one you shared doesn't include the project file contents or any MSBuild items (probably because it was collected from within VS, and that extension has limitations), so it's not very helpful.

**Comment by jeffason** [comment]
[@dsplaisted yessir. see attached. weird that building from commandline yielded different results and less entries in the `.deps.json`
[GameSimDepsandBinlog.zip](https://github.com/dotnet/sdk/files/5712014/GameSimDepsandBinlog.zip)

**Comment by dsplaisted** [comment]
@jeffason How are SimulationExports.dll and SimulationCore.dll copied to the output folder?  I don't see any reference to them at all in the GameSim binlog.  That explains why they aren't in the deps file- they aren't referenced at all.

**Comment by jeffason** [comment]
@dsplaisted sorry for the confusion, I didn't have the exact assembly names correct in my original post.  The example assembly names in the OP should have been GameSim.dll and BFCore.dll.  Here's a screenshot showing GameSim's project dependencies which I would expect to be reflected in the `.deps.json`

**Comment by dsplaisted** [comment]
@jeffason Can you also attach the NuGet assets file (in `obj\project.assets.json`) for the GameSim project?

**Comment by jeffason** [comment]
@dsplaisted yessir - 
[project.assets.json.zip](https://github.com/dotnet/sdk/files/5718000/project.assets.json.zip)

**Comment by dsplaisted** [comment]
@jeffason That looks like the project.assets.json from the BFCore project.  I'm looking for the GameSim one.

**Comment by jeffason** [comment]
@dsplaisted  - hmm... grabbed that one form the GameSim/obj dir but I found this other file - let me know if it contains the info you are looking for - 
[GameSim.csproj.nuget.dgspec.json.zip](https://github.com/dotnet/sdk/files/5718035/GameSim.csproj.nuget.dgspec.json.zip)

**Comment by dsplaisted** [comment]
I see.  The problem is that you have multiple project files in the same directory.  That is not currently supported.  The assets files collide with each other.

@nkolev92 @zkat Is this documented anywhere, or is there an issue tracking fixing it (I remember discussions about having the assets file include the project name).

**Comment by nkolev92** [comment]
Yep, https://github.com/NuGet/Home/issues/4463. 

I think it's technically possible right now, there's just some potential gotchas that need analyzed.

**Comment by jeffason** [comment]
@dsplaisted @nkolev92 thanks for the link.  The workaround mentioned in NuGet/Home#4463 of supplying the `Directory.Build.Props` seems to have resolved the missing dependencies in my `GameSim.deps.json` file so I believe this issue can be closed

**Comment by dsplaisted** [comment]
I'm glad we were able to figure this out.
