### ISSUE TITLE
SDK users can find out if their SDK/runtimes have updates available

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#14958]
- [ ] Dotnet command for checking for updates similar to the data in --info
- [ ] Parse releases.json to determine newest supported release in each feature band
- [ ] Design needed: How do we handle if newer feature band vs. minor version?

Spec: https://github.com/dotnet/sdk/issues/15021

**Comment by sfoslund** [comment]
Depends on https://github.com/dotnet/runtime/issues/46128

**Comment by sfoslund** [comment]
Implemented in #16141
