### ISSUE TITLE
dotnet rid build produces standalone executable with wrong name

### ISSUE THREAD

**Issue by Andrew-MSFT** [dotnet/sdk#1495]
I have a project that should be producing an output file of VS.Web but when I dotnet build with a RID it produces VS.Web.Web. The .proj file and FileListAbsolute.txt are attached, I can share the full repro project if needed.

[VS.Web.csproj.txt](https://github.com/dotnet/sdk/files/1226723/VS.Web.csproj.txt)
[VS.Web.csproj.FileListAbsolute.txt](https://github.com/dotnet/sdk/files/1226726/VS.Web.csproj.FileListAbsolute.txt)

**Comment by livarcocc** [comment]
We have fixed this in our master branch.
