### ISSUE TITLE
How to build SDK?

### ISSUE THREAD

**Issue by Maniues** [dotnet/sdk#14966]
Hello
How Can I build SDK in Linux?
./build.sh want to install pre-compiled wersion with dotnet-install

**Comment by huoyaoyuan** [comment]
build.sh uses last version to compile the latest version. It's suitable for majority of people.

If you want to compile everything from source, please access dotnet/source-build repo.

**Comment by marcpopMSFT** [comment]
Old issue triage: Looks like this question was answered.
