### ISSUE TITLE
"Cannot find compilation library location for package" when referencing a DLL directly.

### ISSUE THREAD

**Issue by mattvperry** [dotnet/sdk#1500]
Here is the symptom I am seeing:
![image](https://user-images.githubusercontent.com/393869/29381497-693d443a-8297-11e7-9dec-5659c1783532.png)

I had seen a number of similar issues across Asp.net core and Dotnet sdk repos but they all seem to say that this was fixed here: dotnet/core-setup#2039 but this does not seem to be the case when doing a direct DLL reference and running locally through visual studio.

Also, razor pre-compilation fails here as well. However, if you turn off pre-compilation and publish the app then it works.

I have attached a repro project here as well. All I did was create a new MVC template web app through VS 2017 15.3 and reference a DLL.

[Repro.zip](https://github.com/dotnet/sdk/files/1229288/Repro.zip)

**Comment by mattvperry** [comment]
After further investigation, the root cause of this seems to be this change here: https://github.com/dotnet/sdk/commit/e64e26cbd927148a140b8aa94920e051d8f8898e

The generated deps files now list direct DLL references with the type "reference." The `DependencyModel` project's `AppBaseCompilationAssemblyResolver` couldn't handle deps with type "reference." My PR should fix that.

**Comment by pranavkm** [comment]
This a dup of https://github.com/dotnet/core-setup/issues/2981. Closing since this since it's is already being tracked for the 2.0.1 milestone.
