### ISSUE TITLE
Unable to read Tasks or Parallel Stacks with net5.0-windows* TFM

### ISSUE THREAD

**Issue by trympet** [dotnet/sdk#15055]
**Description:**
I am unable to see Parallel Stacks or Task information in Visual Studio when targetting a windows-specific TFM.

The Tasks pane is blank, while the Parallel Stacks pane shows the following error: `Viewing Task information for .NET Core 2.1/2.2 is not supported for live processes. You can either re-target a newer version of the runtime, or save a minidump and view task information for your application.`

**Expected behavior:**
Task information and Parallel Stacks works the same as it did in .NET Core 3.
![image](https://user-images.githubusercontent.com/23460729/102799565-02327400-43b3-11eb-8eae-2ba6668d6772.png)

**Actual behavior:**
No Task information or Parallel Stacks information is shown. 
![image](https://user-images.githubusercontent.com/23460729/102799602-09f21880-43b3-11eb-9e6a-edd836df5bd6.png)

**Repro steps:**
1. Create a new .NET Core 3 WPF project.
2. Create a task in `MainWindow.xaml.cs`.
3. Break while the task is running.
4. Open `Debug -> Windows -> Parallel Stacks` in Visual Studio.
5. Open the `.csproj` file and change the `TargetFramework` attribute to `net5.0-windows`.

**Repro example**
Example `.csproj`:
``` xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RootNamespace>wpf_test</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
</Project>
```

Example `MainWindow.xaml.cs`:
``` csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        Test();
        Debug.Assert(false);
    }

    public async Task Test()
    {
        await Task.Delay(50000);
    }
}
```

**Environment:**
.NET SDK: 5.0.101
Runtime: 5.0.1
Visual Studio: 16.8.3

**Comment by Dimension4** [comment]
Also happens for `net5.0` target in asp.net core.

**Comment by trympet** [comment]
Issue seems to be related to Visual Studio, and should be fixed in the next servicing release.

https://developercommunity2.visualstudio.com/t/Unable-to-view-Task-or-parallel-stacks-i/1293379
