### ISSUE TITLE
Update NETCoreAppMaximumVersion to be based on BundledNETCoreAppTargetFrameworkVersion

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1512]
Normally, the `NETCoreAppMaximumVersion` property should be based on the `BundledNETCoreAppTargetFrameworkVersion` property.  However, we currently want to support targeting .NET Core 2.1 even though we haven't managed to insert it into the 2.1 CLI yet, so in #1511 I've hard-coded the max version to 2.1.  Once we bundle a 2.1 version of .NET Core in the CLI, we should revert back to the way this property was set before.

**Comment by livarcocc** [comment]
This is being done now.

**Comment by weshaggard** [comment]
@livarcocc as best I can tell we are still hard-coding the max version. Is that going to remain the POR? I'm curious if there has been any more thought about allowing folks to target higher versions of netcoreapp on older versions of the SDK? I'm not entirely sure why this check exists as in my mental model I think of it just like multi-targeting in the .NET Framework and folks can target whatever version they want.

**Comment by livarcocc** [comment]
We guarantee backwards compatibility in the SDK, but not forward compatibility. This ensures that.

**Comment by weshaggard** [comment]
So for folks that need to use an older sdk but a newer framework is the recommendation to set NETCoreAppMaximumVersion  in their project file like https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility/tests/Microsoft.Windows.Compatibility.Validation.csproj#L5?

**Comment by livarcocc** [comment]
I do not believe there is such a recommendation. The recommendation there is to pick up the latest SDK, which is what the error message says when you don't have that set.

The new framework many times has requirements for the tooling that makes it incompatible with an older SDK and that's really an unsupported scenario.

**Comment by weshaggard** [comment]
There are scenarios we we cannot necessary pick-up a newer SDK. 

>The new framework many times has requirements for the tooling that makes it incompatible with an older SDK and that's really an unsupported scenario.

I'd like to better understand that because from a framework prospective that should just work.
