### ISSUE TITLE
Referencing netcoreapp in a netstandard project

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1513]
_From @aateeque on August 17, 2017 19:43_

Hi
I am porting over a net452 & asp.net app over to netstandard & dotnet core. I have a situation where I need to refence my asp dotnet core app which is `<TargetFramework>netcoreapp2.0</TargetFramework>` in my testing project which is `<TargetFramework>netstandard2.0</TargetFramework>`. When I do a `ProjectReference` I get:

```
Project XXX is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project XXX supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
```

Is this sort of thing possible (don't see why not?) 

_Copied from original issue: dotnet/project-system#2721_

**Comment by davkean** [comment]
tag @nguerrera @dsplaisted

**Comment by nguerrera** [comment]
It is not supported. There are APi you can call in netcoreapp that aren't in netstandard. If a project claims to be netstandard then it can only consume other projects that are compatible with netstandard. The natural case is the reverse: shared code at the bottom is netstandard and consumed by more platform specific (netcoreapp, net, xamarin) code at the top.

Now there is an escape hatch for package references where you can set AssetTargetFallback to consume assets which are technically incompatible. You'd get a warning in that case and things might not work at runtime. You can suppress that warning if you know the library is actually compatible enough for your scenario.

However, there is not currently an equivalent escape hatch for project references. The thinking with package references is that you have only a binary in hand and so you might have no choice but to break the rules if it so happens that something you don't control is actually compatible and just not designated as such. However, for projects in your own solution, there's generally a better solution by changing your design. 

Can you give more details about why you need this project that is testing a .net core app to target .net standard? 

Cc @terrajobst

**Comment by aateeque** [comment]
@nguerrera that makes sense, thanks for explanation. What should tests lib for netcoreapp target?

**Comment by nguerrera** [comment]
They should target netcoreapp too. I think I understand the confusion. You can have libraries that target netcoreapp, not just applications. The 'app' in the name is misleading.

**Comment by aateeque** [comment]
@nguerrera spot on!! It is that netcoreapp bit which led to confusion. Thanks!!! 
One more thing, can WPF csproj files be converted to the new csproj format?
