### ISSUE TITLE
Tag v5.0.101-servicing.20601.7 does not build: unable to load source 'darc-pub-dotnet-runtime-b02e13ab'

### ISSUE THREAD

**Issue by dagood** [dotnet/sdk#15131]
From `v5.0.101-servicing.20601.7` (which I assume is what produced `5.0.101` since it's the only tag with `5.0.101` in it):

```
./build.sh --restore --build --pack
...
--------------------------------------------------------------------------------------
/work/artifacts/toolset/restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-b02e13ab/nuget/v3/index.json.
/work/artifacts/toolset/restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-b02e13ab/nuget/v3/index.json.
Build failed (exit code '1').
```

https://github.com/dotnet/sdk/blob/d5eb2b9c5a4e51be4b26781958785d8817e25b04/NuGet.config#L9-L11

When I go to https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=darc-pub-dotnet-runtime-b02e13ab to check up on the feed, I see this:

> ![image](https://user-images.githubusercontent.com/12819531/103385134-c5efc980-4abe-11eb-8f20-bdef901a5f27.png)

---

@dotnet/dnceng are you able to restore the feed? Or is the tag supposed to be buildable a different way?

**Comment by riarenas** [comment]
Aren't all the packages in that feed available in nuget.org? I see that they have all been deleted, so even bringing back the feed is won't be enough.

**Comment by dagood** [comment]
> Aren't all the packages in that feed available in nuget.org?

I don't know what packages were in the feed. However, only "shipping" packages go to nuget.org, and I don't know if all of the packages in that feed are "shipping".

It does look like manually removing the feed from the nuget.config lets the build pass. But this is not a nice workaround. Isn't there `disabledPackageSources` infra to handle this and let tags be buildable? Or is that not done yet?

**Comment by riarenas** [comment]
Actually, it might be just enough to bring it back so that nuget doesn't crash when trying to find it.

@mmitche any ideas on how the feed got deleted? We stopped auto-deleting feeds a while ago

**Comment by riarenas** [comment]
We have infrastructure to add entries to disabledPackageSources when dependency updates happen after a package has been released publicly, but if a tag was set on a commit that already had the feed in its nuget.config, then that won't help.

**Comment by riarenas** [comment]
I restored the feed. I'm not sure how it got deleted in the first place. I'm not aware of any automation that deletes feeds right now.

**Comment by dagood** [comment]
> We have infrastructure to add entries to disabledPackageSources when dependency updates happen after a package has been released publicly, but if a tag was set on a commit that already had the feed in its nuget.config, then that won't help.

I'm referring to the proactive disable feature from here, specifically how it needs to make sure it happens before the tag so the tag ends up buildable by the public: https://github.com/dotnet/arcade/issues/5890.

(But if this feed deletion was really unintentional and should never happen, there's no problem here.)

**Comment by riarenas** [comment]
@mattgal should be able to comment on the disabledPackageSources bit.

**Comment by mmitche** [comment]
> Actually, it might be just enough to bring it back so that nuget doesn't crash when trying to find it.
> 
> @mmitche any ideas on how the feed got deleted? We stopped auto-deleting feeds a while ago

Mayhaps just by mistake. I deleted a few feeds that got created unintentionally so that may have been it.

**Comment by mmitche** [comment]
>It does look like manually removing the feed from the nuget.config lets the build pass. But this is not a nice workaround. Isn't there disabledPackageSources infra to handle this and let tags be buildable? Or is that not done yet?

The disabled package sources only disables the feeds that would be inaccessible for external users. It doesn't disabled -pub because that would make the shas unbuildable (without modifications) on devs machines during the release cycle.

**Comment by riarenas** [comment]
>The disabled package sources only disables the feeds that would be inaccessible for external users. It doesn't disabled -pub because that would make the shas unbuildable (without modifications) on devs machines during the release cycle.

That's the part I was missing about disabled sources. Thanks, that makes sense.

**Comment by dagood** [comment]
> The disabled package sources only disables the feeds that would be inaccessible for external users.

If we were deleting them intentionally, this would apply (or rather, we'd want some better infra that works at *any* point in time rather than only for a certain group of users vs. another).

But since it isn't intentional to delete these, yeah, no need. Closing as resolved. Thanks to both of you for looking into this.
