### ISSUE TITLE
[Dotnet CLI] Add upgrade command

### ISSUE THREAD

**Issue by redradist** [dotnet/sdk#15137]
Dotnet CLI has one missed command - `upgrade`

Such tools like `deno` (JavaScript/TypeScript runtime), `conan` (C++ package manager) ...

It is more convenient than downloading and installing `dotnet` manually

I think we need to have the same command in `dotnet`:
```console
dotnet upgrade
```

**Comment by marcpopMSFT** [comment]
We'll track this proposal through this issue: https://github.com/dotnet/sdk/issues/14960. We're starting to look into this space.
