### ISSUE TITLE
dotnet test netcoreapp2.0 - imported project was not found

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sdk#1514]
I got an error when I updated from SDK 1.0.4 to SDK 2.0.0.

I build a solution with msbuild and then run some tests on .NET Core with dotnet. SDK 1.0.4 on netcoreapp1.1 did this without issue. SDK 2.0.0 is erroring when running the tests.

Command:

    dotnet test Newtonsoft.Json.Tests.csproj -f netcoreapp2.0 -c Release --no-build

Result:

> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0
> \Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the
> file exists on disk. [C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
> C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests [dotnetcore2 ≡]>

There is no reason that portable files should be imported. The command is specifying that tests should be run for an already built netcoreapp2.0 test project

Source code changes to use .NET Core 2.0 - https://github.com/JamesNK/Newtonsoft.Json/commit/5c2695e8397ab7aada2d23be9a37d44598448b39

**Comment by rainersigwald** [comment]
I added `/fileloggerparameters:verbosity=diagnostic` to that command line and looked at the resultant `msbuild.log` to get more context. The error context is:

```
"s:\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.csproj" (Restore target) (1) ->
"s:\Newtonsoft.Json\Src\Newtonsoft.Json\Newtonsoft.Json.csproj" (_GenerateRestoreGraphProjectEntry target) (2:74) ->
"s:\Newtonsoft.Json\Src\Newtonsoft.Json\Newtonsoft.Json.csproj" (_GetRestoreSettingsPerFramework target) (2:81) ->
    C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.0\Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [s:\Newtonsoft.Json\Src\Newtonsoft.Json\Newtonsoft.Json.csproj]
```

This is happening during the implicit restore phase; I get the same error but **adding `--no-restore` to the command line gets past it.**

That should be implicit: https://github.com/dotnet/cli/issues/7472.

**Comment by rainersigwald** [comment]
The actual failure is coming from the Newtonsoft.Json project, which overrides `$(LanguageTargets)` to point to the Portable targets:

https://github.com/JamesNK/Newtonsoft.Json/blob/5c2695e8397ab7aada2d23be9a37d44598448b39/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L75

You could possibly condition the nonstandard TFs on `'$(MSBuildRuntimeType)' == 'Full'" to keep `dotnet restore` from seeing them and failing to traverse into their inner builds.

**Comment by JamesNK** [comment]
--no-restore works for me. Thanks

You guys can fix the flag in the bug you raised.
