### ISSUE TITLE
No reference to .net framework in trying to build a vs2015 csproj

### ISSUE THREAD

**Issue by aateeque** [dotnet/sdk#1515]
Hi
I have a vs2015 csproj which has a `<OutputType>WinExe</OutputType>`  & `ToolsVersion="14.0"`. When I try to build this in vs2017 I get:
```
Your project is not referencing the ".NETFramework,Version=v4.5.2" framework. Add a reference to ".NETFramework,Version=v4.5.2" in the "frameworks" section of your project.json, and then re-run NuGet restore.
```

What is this about? I don't have a `project.json` for this project; but I have tried that recommendation there to no avail. Oddly, I have another similar project (similar in its `TargetFrameworkVersion` but `<OutputType>Library</OutputType>`) that the first one references which builds. Is there some oddity in how vs2015 csproj is built in vs2017 that I am missing? I thought 2015 csproj was fully compatible in 2017...

**Comment by aateeque** [comment]
I have been able to fix this issue. The referenced project I mentioned there I thought was referenced but wasn't. So adding the reference fixed the problem - but as you can see the error message is wrong - __and wrong in a hair pulling unhelpful way__. This seems like a bug which has surfaced this error

**Comment by livarcocc** [comment]
SDK based projects are not supported in VS 2015, so I imagine this is a old style csproj. As such, this is not really an issue we can address. If you can still repro this, maybe try filling an issue under dotnet/project-system.
