### ISSUE TITLE
Compile WinExe without Microsoft.WindowsDesktop.App framework reference

### ISSUE THREAD

**Issue by Chicken-Bones** [dotnet/sdk#15155]
I have a portable NETCore.App application which launches a gui via native library. If I compile with `<OutputType>Exe<OutputType/>` then everything works well, but I get unwanted console window when using the apphost exe on windows. If I compile as `WinExe` then console disappears, but framework reference to `Microsoft.WindowsDesktop.App` is included breaking portability to other platforms. I can manually change target framework in `runtimeconfig.json` and get it to run on OSX/Linux, but the unwanted framework reference makes development difficult.

Similar to #4447 

Is there an msbuild trick I can use to change this behaviour? Or maybe a postbuild command I can use on the generated apphost exe to disable the console in the exe header as workaround?

**Comment by dsplaisted** [comment]
If I create a console app and change the OutputType from Exe to WinExe, I don't get a FrameworkReference to Microsoft.WindowsDesktop.App.  Something else is probably bringing that in, perhaps you are targeting `net5.0-windows`, or you are referencing NuGet packages that depend on the WindowsDesktop framework.

If you can [share a binlog](https://aka.ms/binlog) then we could investigate further.

**Comment by Chicken-Bones** [comment]
I can no longer replicate this. Sorry for taking your time.
