### ISSUE TITLE
Can I compile a Netcore App using 1.0.4 runtime if both 1.0.4 and 1.0.5 installed?

### ISSUE THREAD

**Issue by hongdai** [dotnet/sdk#1516]
I have both 1.0.4 and 1.0.5 runtime installed. I would like to compile to an 1.0.4 App. Is it possible?

I have tried to specify Sdk version explicitly to "1.0.3", but it still picks up 1.0.5 Microsft.NETCore.App.
`<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="1.0.3">`

**Comment by terrajobst** [comment]
What are you trying to achieve? The TFM is what control whether you can run on 1.0, 1.1, or 2.0. You generally cannot require a patch level.

**Comment by hongdai** [comment]
I would like to compile it to "1.0.3", so the tool can run in any runtime that >= 1.0.3. If I compile it using "1.0.5", it will not be able to run on a machine only has "1.0.3".

**Comment by dasMulli** [comment]
`<RuntimeFrameworkVersion>1.0.3</RuntimeFrameworkVersion>` (property) should do the trick

**Comment by hongdai** [comment]
@dasMulli that worked. Thanks!

**Comment by hongdai** [comment]
@dasMulli

**Comment by hongdai** [comment]
@dasMulli One more important question, is RuntimeFrameworkVersion officially supported? This will help us make the decision if we should use it in our product.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@terrajobst To answer your question about what I need to achieve:
1) I have a tool that need to run in either 1.0.4 and 1.0.5. The reason is I do not want to force customers to install 1.0.5 if they only have 1.0.4 installed. This is true for VS2017 15.0 and 15.1 customers.
2) To achieve 1),  I can only compile it in 1.0.4. However, there are other tools need 1.0.5 runtime on our build machines. i.e. our build machine has both 1.0.4 and 1.0.5 installed. In order to compile in 1.0.4, I need to be able to specify sdk version for compile time.

**Comment by dasMulli** [comment]
At least it is documented at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

Personally, I would worry more about support for old versions of the runtime and VS versions..

In 2.0.0, all "portable" projects automatically target the `.0` patch version so you won't have these problems in 2.0.*

**Comment by hongdai** [comment]
@dasMulli Thanks for the link! If it is documented, then it should be supported.

As for supporting older versions, this is a business decision our team made.
