### ISSUE TITLE
Activity's SetParentId() API doesn't set parent span id as told to

### ISSUE THREAD

**Issue by lupengamzn** [dotnet/sdk#15175]
Hey guys,

Currently the runtime provides [SetParentId()](https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L477) API to override the parent id and trace id of the `activity`. We noticed that if we're calling this API to a root activity, which has no parent span id, and set the parent span id (the second parameter) as `default`, its [parent span id](https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L490) will eventually be [converted](https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1766) to `0000000000000000`, instead of `default` or `null` as we expected. In this case, is it better for this API to keep consistence with what it's told to be set and is it more reasonable for a root activity to have a `null` parent span id after applying this API? 

Would you consider updating the current [code](https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L490) similar as the following to fit this case? 

```
public Activity SetParentId(ActivityTraceId traceId, ActivitySpanId spanId, ActivityTraceFlags activityTraceFlags = ActivityTraceFlags.None)
{
      if (Parent != null)
      {
            NotifyError(new InvalidOperationException(SR.SetParentIdOnActivityWithParent));
      }
      else if (ParentId != null || _parentSpanId != null)
      {
            NotifyError(new InvalidOperationException(SR.ParentIdAlreadySet));
      }
      else
      {
            _traceId = traceId.ToHexString();     // The child will share the parent's traceId.
            _parentSpanId = spanId == default ? null : spanId.ToHexString(); // line of change
            ActivityTraceFlags = activityTraceFlags;
       }
       return this;
 }
```

Many thanks

**Comment by cijothomas** [comment]
Please open this in the https://github.com/dotnet/runtime/issues

**Comment by lupengamzn** [comment]
Thanks @cijothomas , closing this and reopened as https://github.com/dotnet/runtime/issues/46706
