### ISSUE TITLE
[Loc] Translation assistance

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/sdk#15174]
String Resource ID | 0; "CurrentRuntimeOptionDescription"
-- | --
Source String | Use current runtime as the target runtime.
Filename | Cli\dotnet\commands\dotnet-store\xlf\LocalizableStrings.xlf
Question | what does the placeholder of {1} refer to?

**Comment by wli3** [comment]
I don't see a `{1}` in the source string _Use current runtime as the target runtime._ The source string is wrong?

**Comment by cristianosuzuki77** [comment]
This is
