### ISSUE TITLE
WindowsDesktop MSBuild SDK should not be required for WPF projects targeting .NET Framework

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#15194]
**Repro**

- Create a new .NET 5 WPF project
- Change `TargetFramework` to `net472`
- Build

**Expected**

Build is successful

**Actual**

Lots of compilation failures such as:

> error CS0246: The type or namespace name 'ThemeInfoAttribute' could not be found (are you missing a using directive or an assembly reference?)

** Fix**

Probably we need to add an additional statement to set `ImportWindowsDesktopTargets` to true if `TargetFrameworkIdentifier` is `.NETFramework` and either `UseWpf` or `UseWindowsForms` are set to true, here:

https://github.com/dotnet/sdk/blob/4af0917340b1bf4ca8bdbb2affbf83d87ff839c9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L76-L82

Related: https://github.com/dotnet/sdk/pull/13441

**Comment by sfoslund** [comment]
Fixed in 5.0.2xx by #15213
