### ISSUE TITLE
Windows desktop apps can't be run on 6.0.100-alpha.1.21056.10

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/sdk#15198]
**.NET Core Version:**
.NET SDK 6.0.100-alpha.1.21056.10.

**More info**
1. This is a regression, it can't reproduce .NET SDK 6.0.100-alpha.1.21054.4.
2. The issue can reproduce on WPF/Winforms Application, they can be built successfully, but failed to run, and Designer cannot be opened.
3. The issue can’t reproduce on Console Application, it can be build and run successfully.
4. When create .NET Core winform project with CLI, the app can be built successfully, but it can’t be run successfully, there’s below  DesignToolsServer.exe dialog box pops up.
![image](https://user-images.githubusercontent.com/56664234/103851976-f13d6e80-50e5-11eb-9c91-104017da0906.png)

**Minimal repro:**
1. Installed the latest .NET SDK 6.0 from: https://github.com/dotnet/core-sdk.
2. Create .NET Core winforms project targets  .NET 5.0(Current).
3. Right click on the project Properties and target to .NET 6.0 and save all project.

**Actual behavior:**
There’s an DesignToolsServer.exe dialog box pops up.
![image](https://user-images.githubusercontent.com/56664234/103852365-ad973480-50e6-11eb-8c23-e73b0410c025.png)

 Click "No" on DesignToolsServer.exe dialog box , the following error pops up.
![image](https://user-images.githubusercontent.com/56664234/103852381-b7209c80-50e6-11eb-8a74-be9a12e2da9c.png)

When opening Form1.Design, it does not open, the following error pops up.
![image](https://user-images.githubusercontent.com/56664234/103852391-bd167d80-50e6-11eb-85b4-b4859d8dcb0d.png)
![CoreWinformsApp_Target6 0](https://user-images.githubusercontent.com/56664234/103852438-d61f2e80-50e6-11eb-8d9c-f7a45ab1c7a7.gif)

**Expected behavior:**
There are no DesignToolsServer.exe dialog box and error box pops up, the Form1.Design can be open successfully.
![createCoreAppExpected](https://user-images.githubusercontent.com/56664234/103852474-e800d180-50e6-11eb-8a12-0ad9df9ff964.gif)

**Comment by RussKie** [comment]
@jkoritzinsky could any of your recent work in dotnet/windowsdesktop have caused this?

**Comment by jkoritzinsky** [comment]
Theoretically it could be possible. I don't know enough about the path that's throwing up the dialog or failing to find the runtime. There could be some implicit dependency that I didn't know about.

I'll take a look tomorrow.

**Comment by jkoritzinsky** [comment]
It looks like while my PR was stuck in review limbo, there was a change in the SDK to how the runtimeconfig is written out. I'll take a look at how to produce the right runtimeconfig.

**Comment by jkoritzinsky** [comment]
I have a PR into dotnet/arcade that fixes the infra for this case. Once it's merged, I'll update dotnet/windowsdesktop manually.

**Comment by jkoritzinsky** [comment]
Update into dotnet/windowsdesktop is open at https://github.com/dotnet/windowsdesktop/pull/1332

**Comment by RussKie** [comment]
Thank you, merged

**Comment by Ashley-Li** [comment]
Verified this issue with .NET SDK 6.0.100-alpha.1.21060.2 build ,this issue has been fixed that there are no DesignToolsServer.exe dialog box and error box pops up, the Form1.Design can be open and run successfully.
![Re-Test](https://user-images.githubusercontent.com/56664234/104155515-59f85400-5422-11eb-9ece-631f9af1c4a7.gif)
