### ISSUE TITLE
Remove dotnet.myget feeds 

### ISSUE THREAD

**Issue by mmitche** [dotnet/sdk#15209]
There is still some usage of dotnet.myget.org feeds in some tests and docs. The tests are likely to break when dotnet.myget.org gets turned off.

**Comment by sfoslund** [comment]
Fixed by:
https://github.com/dotnet/sdk/pull/15267
https://github.com/dotnet/sdk/pull/15266
https://github.com/dotnet/toolset/pull/5075
https://github.com/dotnet/toolset/pull/5079
https://github.com/dotnet/installer/pull/9397
