### ISSUE TITLE
Investigate performance issues and explore solutions regarding CLI-related inner-loop scenarios

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#15218]
As part of the [.NET 6 Epic regarding inner-loop performance](https://github.com/dotnet/msbuild/issues/5876), performance opportunities as they pertain to the .NET CLI (excluding MSBuild) need to be identified, investigated, and solutions implemented.

@stephentoub @brianrob

**Comment by marcpopMSFT** [comment]
We've moved on from inner loop investigations so closing for now.
