### ISSUE TITLE
Support customized Activity trace id generation

### ISSUE THREAD

**Issue by lupengamzn** [dotnet/sdk#15216]
Hey,

So the .NET runtime provides APIs to generate `Activity`, which can be adopted and processed as trace context and eventually emitted to multiple backend vendors by OpenTelemetry .NET SDK for the purpose of tracing. Currently .NET runtime only allows an activity's trace id to be [randomly generated](https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1666) and there is no public API available to override it. While for some backend vendors, trace context with a non-random customized trace id is more preferred. For instance, AWS X-Ray backend will only process trace context with a trace id containing a timestamp. In this case, is it possible for the runtime to support customized activity trace id, like adding API similar as `Activity.SetTraceId()`? 

Previous discussion: https://github.com/open-telemetry/opentelemetry-specification/issues/896

Many thanks

**Comment by cijothomas** [comment]
Please open this in the https://github.com/dotnet/runtime/issues repo.

**Comment by lupengamzn** [comment]
Thanks @cijothomas , closing this and reopened in https://github.com/dotnet/runtime/issues/46704
