### ISSUE TITLE
Reason for runtimeconfig.dev.json in build output since .NET Core 3?

### ISSUE THREAD

**Issue by vuplea** [dotnet/sdk#15210]
An `OutputType=Exe` project build will create a `runtimeconfig.dev.json` which adds probing paths:
```
    "additionalProbingPaths": [
      "C:\\Users\\radu.oancea\\.dotnet\\store\\|arch|\\|tfm|",
      "C:\\Users\\radu.oancea\\.nuget\\packages"
    ]
```
[Since all the dependencies should be near the `AppHost`](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md#description), and the runtime probes in its directory first (e.g. I've used `dotnet store` first on my dependencies, but it still loaded them from the build folder), does `runtimeconfig.dev.json` have an effect?

**Comment by joeloff** [comment]
The configuration files isn't just for probing. It's intended to include other configuration options for your application. Probing paths are just one item that can be configured. The additional probing paths are likely a no-op.

Did you add an probing paths in your .csproj, e.g.

```<AdditionalProbingPath Include="$(USERPROFILE)\.nuget\packages" />```

**Comment by vuplea** [comment]
Thanks, @joeloff .
The above shown `additionalProbingPaths` are the default ones i.e. `dotnet new console & dotnet build`.

I wanted to make sure that the file has no effect by default.
* We do not plan to use `CopyLocalLockFileAssemblies=false` for developer builds as it had no discernible effect in build time when tested.
* We are planning to deploy build (not publish) output since it seems easier for us (at the moment 🌝). Deploying `runtimeconfig.dev.json` does not make sense so we will remove them though.
* We might even remove them post-build. If somehow (e.g. through a faulty PostBuild target we configure) we corrupt the build, it would be better to fail on missing assemblies in output.

**Comment by richlander** [comment]
From the [.NET Core 3.0 blog post](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/#dotnet-build-now-copies-dependencies):

```
dotnet build now copies NuGet dependencies for your application from the NuGet cache to your build output folder during the build operation. Until this release,those dependencies were only copied as part of dotnet publish. This change allows you to xcopy your build output to different machines.

There are some operations, like linking and razor page publishing that require publishing.
```

My understanding (which is also the rationale for the issue title) is that this product change significantly reduces or completely removes the need for this file. If that is the case, it would be great to no longer have it. We should have as few build artifacts as possible.

@vitek-karas?

**Comment by vitek-karas** [comment]
@richlander I completely agree - see https://github.com/dotnet/sdk/issues/16818 - we're trying to remove it now.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/17014
