### ISSUE TITLE
With .NET 6 SDK,  Data collector 'Blame' message display when dotnet test for unit test project

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#15228]
Repro steps:
Install .NET 6 SDK(6.0.100-alpha.1.21057.10) from https://github.com/dotnet/installer
Create unit test project(e.g dotnet new xunit) in CLI and modify *cproj file to update tfm from net5.0 to net6.0
dotnet build and dotnet test

Expected Result
dotnet test successfully

Actual Result:
dotnet test successfully, but some other message displays as below
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
![image](https://user-images.githubusercontent.com/65637796/103992997-df37fa80-51cf-11eb-9b2c-cf3bae133bef.png)

Note:
repro on xunit/nunit/mstest
Dotnet --info:
.NET SDK (reflecting any global.json):
Version: 6.0.100-alpha.1.21057.10
Commit: 87c80e2837

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19042
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21057.10\

Host (useful for support):
Version: 6.0.0-alpha.1.21057.2
Commit: 81b9558199

.NET SDKs installed:
6.0.100-alpha.1.21057.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-alpha.1.21057.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-alpha.1.21057.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-alpha.1.21056.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
@nohwnd this looks like it might be a test issue

**Comment by nohwnd** [comment]
This is caused by the rewrite to the new parsing library, there are now default values specified for hang dump and crash dump parameters which force the Blame collector to be always active. The message is then coming from the Blame collector letting you know that all test finished running. 

In the linked PR I remove those values, but there are failures unrelated to the change. Could you have a look there please?

**Comment by vdanche** [comment]
Checked on NET 6.0 SDK(6.0.100-alpha.1.21063.28) the issue has been fixed on xunit/nunit/mstest.
![image](https://user-images.githubusercontent.com/65637796/104573629-10ad3c00-5690-11eb-946a-a10a53ca21d2.png)

**Comment by nohwnd** [comment]
Perfect, I was going to check today but you beat me to it :)
