### ISSUE TITLE
.NET 6: The "CreateAppHost" task failed unexpectedly.

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sdk#15225]
Error when building.

```
error MSB4018: The "CreateAppHost" task failed unexpectedly.
error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
error MSB4018: File name: 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
error MSB4018: The Zone of the assembly that failed was:
error MSB4018: MyComputer
error MSB4018:    at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath)
error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2()
error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func)
error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom)
error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
error MSB4018: 
error MSB4018:
```

VS: 2019 16.9 Preview 2
.NET SDK: 6.0.100-alpha.1.21057.4

**Comment by JamesNK** [comment]
![image](https://user-images.githubusercontent.com/303201/103987353-3a2e1980-51f1-11eb-871c-9010b0d5cc9a.png)

**Comment by rseanhall** [comment]
I am also seeing this with .NET SDK 6.0.100-alpha.1.21059.3.

**Comment by ryalanms** [comment]
I'm also seeing this.  Builds succeed with the .NET Core CLI, but fail with VS/msbuild.

>"C:\wpftests\wpftests.csproj" (default target) (1) ->
(_CreateAppHost target) ->
  C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21068.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5):
 error MSB4018: The "CreateAppHost" task failed unexpectedly. [C:\wpftests\wpftests.csproj

/cc @dotnet/wpf-developers

**Comment by marcpopMSFT** [comment]
@richaverma1 Has your test team run into this with preview 3?

**Comment by richaverma1** [comment]
@marcpopMSFT no we didn't see this error but we have been testing against 16.9 Preview 4 and not Preview 2.

**Comment by JamesNK** [comment]
I updated VS to preview 3 and I still see this

```
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: The "CreateAppHost" task failed unexpectedly.
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: File name: 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: The Zone of the assembly that failed was:
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: MyComputer
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath)
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2()
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func)
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom)
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: 
18>C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:

```

**Comment by ericstj** [comment]
@mmitche I believe that this is due to SDK consuming an unsigned build of runtime.  I checked in an installed SDK and found all these files are unsigned: `C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.27\Sdks\Microsoft.NET.Sdk\tools\net472`

Now most of these are "Open Source Signed" AKA "Public Signed" AKA "Fake Signed".  Meaning they don't have signatures but lie to say they do and desktop permits the load.  Unsafe is different because it is built from IL using ILASM which doesn't support signing this way: https://github.com/dotnet/runtime/issues/42250.

The workaround here is to disable strong name validation for b03f5f7f11d50a3a, or even just Unsafe. EG:
```
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\sn" -Vr System.Runtime.CompilerServices.Unsafe,b03f5f7f11d50a3a
"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn" -Vr System.Runtime.CompilerServices.Unsafe,b03f5f7f11d50a3a
```

**Comment by rseanhall** [comment]
@ericstj Are you aware that even though https://github.com/dotnet/runtime/issues/42250 is open, it is locked to non-collaborators (i.e. non-Microsoft employees)?

**Comment by ericstj** [comment]
@rseanhall I unlocked it.  Looks like that happened because the bot locked it when it was closed but didn't unlock when it was reopened.  I'll follow up with the bot owner on that behavior.

**Comment by marcpopMSFT** [comment]
@ericstj , do we expect customers to disable strong name verification for daily builds that will be unsigned or can this particular error be resolved in the runtime?  If it requires customer modifications, we'll want to document it here: https://github.com/dotnet/installer/issues/9384

**Comment by ericstj** [comment]
I think we can drive a fix into runtime within a couple weeks.  It's not a simple switch to flip, so it may make sense to document the workaround.  The command I shared above is sufficient and only disables validation for this assembly.

**Comment by ericstj** [comment]
@marcpopMSFT looks like we got to this sooner than I thought: https://github.com/dotnet/runtime/pull/47489

This will be in the main codebase (not preview1 branch).  I don't expect preview1 to be an issue, since it should be full-signed (right @mmitche?)

**Comment by marcpopMSFT** [comment]
@ericstj Official release builds will be signed which includes preview 1.  It's only the day to day builds that are problematic.

**Comment by ericstj** [comment]
Sounds good, you can close this once you pick up the above linked runtime change.

**Comment by Ceten** [comment]
A colleague and I got the same error running .net 5.0 on Visual Studio 16.8.4 (different projects). For us it was caused by the virus scanner blocking access to tmp files being generated during build. Workaround was to add an exception to the virus scanner, after that the projects built without issues.

**Comment by weltkante** [comment]
> For us it was caused by the virus scanner blocking access to tmp files being generated during build.

Its a different error message though, just the stack trace is the same.

The [workaround](https://github.com/dotnet/sdk/issues/15225#issuecomment-766996282) fixes the problem when trying to run the WinForms `main` branch in the Visual Studio debugger so I don't think this is antivirus related.

**Comment by ericstj** [comment]
Correct.  It would also be a different exception message.

The antivirus scenario is interesting and could be treated as a separate bug. Build tasks should avoid ever copying, closing a handle, then reopening for write. Doing so makes them vulnerable to this sort of antivirus interference. They should always do all writing while holding the original handle that created the file.  Would you mind opening a separate issue with the exception message for the AV case in dotnet/runtime? @vitek-karas @agocke

**Comment by ericstj** [comment]
Here's the issue on the AV scanner problem: https://github.com/dotnet/runtime/issues/3832

**Comment by svetovid** [comment]
![image](https://user-images.githubusercontent.com/9212389/107332956-18a4a400-6ab5-11eb-9e37-5063ff4d78de.png)
SDK from master branch works.

**Comment by PylotLight** [comment]
I am also getting this issue. 
New WinUI 3 Preview 4 project with VS19 P5
`The "CreateAppHost" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)`

**Comment by ericstj** [comment]
@PylotLight update to either the shipping build of the .NET SDK as @svetovid mentions above, or a newer nightly build.  If you're still seeing it, then share your dotnet SDK version here.

**Comment by PylotLight** [comment]
@ericstj I found what I think is the latest build from this page: https://github.com/dotnet/installer#installers-and-binaries
dotnet-sdk-6.0.100-preview.3.21123.4-win-x64
Getting different errors now at least ;p

**Comment by ericstj** [comment]
Closing as this issue with unsigned binary in daily builds is now resolved.

**Comment by Webreaper** [comment]
I've just got this with .Net 6 preview 7, running with Visual Studio for Mac v8.10.

**Comment by rohanaceres** [comment]
What fixed for me was deleting all `bin` and `out` folder.

This was caused by using VSCode as admin. Apparently after I build solution with VSCode as admin, some gets messed up resulting with this issue.

**Comment by phenry9999** [comment]
I'm experiencing this now, unfortunately deleting all bin and obj didn't work. :<

**Comment by enmanuel93** [comment]
I created a global.json file in my solution folder and specified my SDK version as follows example: 
{
  "sdk": {
    "version": "7.0.100"
  }
}

it worked for me.

**Comment by Webreaper** [comment]
This issue should be closed as dotnet 6 is well out of support.
