### ISSUE TITLE
Ability to dogfood nupkg via PackageReference

### ISSUE THREAD

**Issue by am11** [dotnet/sdk#1525]
In addition to #1151 (swapping package reference with sources when available available), would be cool if we can also easily dogfood our `.nupkg` produced by `dotnet pack` which can be used in the integration / packaging tests, for instance.

```xml
  <!-- packaging test project -->
  <ItemGroup>
    <PackageReference Include="$(SolutionDir)/bin/$(Configuration)/MyLib.1.0.0.nupkg" />
  </ItemGroup>
```

Here `PackageReference` task will first figure out if `Include` value is a local path then don't hit the server, then if it's nupkg or nuspec file, run install package task on it.

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5826
