### ISSUE TITLE
Installation procedure is illegal according to GDPR

### ISSUE THREAD

**Issue by geira** [dotnet/sdk#15261]
During installation, personal data such as hashed MAC addresses are sent to Microsoft before informing the user. This is illegal according to the GDPR which requires prior, active consent (opt-in). Instead you only offer passive consent (opt-out) after the damage has been done. To opt out totally, one has to set an envvar before installation, but you do not inform the user about this until after the installation, which is another breach of the GDPR ("personal data must be processed in a lawful and transparent manner").

This is the EU GDPR requirements:

At the time of collecting their data, people must be informed clearly about at least:

- who your company/organisation is (your contact details, and those of your DPO if any);
- why your company/organisation will be using their personal data (purposes);
- the categories of personal data concerned;
- the legal justification for processing their data;
- for how long the data will be kept;
- who else might receive it;
- whether their personal data will be transferred to a recipient outside the EU;
- that they have a right to a copy of the data (right to access personal data) and other basic rights in the field of data protection (see complete list of rights);
- their right to lodge a complaint with a Data Protection Authority (DPA);
- their right to withdraw consent at any time;
- where applicable, the existence of automated decision-making and the logic involved, including the consequences thereof.

<https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/principles-gdpr/what-information-must-be-given-individuals-whose-data-collected_en>

When consent is required to process personal data, for that consent to be valid the following conditions must be met:

- it must be freely given;
- it must be informed;
- it must be given for a specific purpose;
- all the reasons for the processing must be clearly stated;
- it is explicit and given via a positive act (for example an electronic tick-box that the individual has to explicitly check online or a signature on a form);
- it uses clear and plain language and is clearly visible;
- it is possible to withdraw consent and that fact is explained (for example an unsubscribe link at the end of an electronic newsletter email).

For consent to be freely given the individual must have a free choice and must be able to refuse or withdraw consent without being at a disadvantage. Consent isn’t freely given if, for example, there is a clear imbalance between the individual and the business/organisation (for example employer/employee relationship) or when a business/organisation requires individuals to consent to the processing of unnecessary personal data as a pre-condition to fulfil a contract or service.

For consent to be informed, the individual must receive at least the following information:

- the identity of the organisation processing data;
- the purposes for which the data is being processed;
- the type of data that will be processed;
- the possibility to withdraw the given consent (for example, an unsubscribe link at the end of an email)
- where applicable the fact that the data will be used for solely automated-based decision-making, including profiling;
- if the consent is related to an international transfer, the possible risks of data transfers to third countries which are not subject of a Commission adequacy decision and where there are no appropriate safeguards.

Remember: where someone consents to the processing of their personal data, you can only process the data for the purposes for which consent was given.

<https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/legal-grounds-processing-data/grounds-processing/when-consent-valid_en>

As can be seen above, the sending of MAC addresses during installation is neither transparent nor has the necessary consent from the user. I therefore ask that any transmission of analytics data is disabled until the user has the possibility of stating his/her preference in a yes/no prompt (which must default to no according to GDPR).

**Comment by geira** [comment]
The Irish Data Protection Commision (which is Google's chosen authority for GDPR purposes) just published a report on cookies and related technologies, which states the matter quite clearly:

> "The cookies most internet users are aware of are typically browser, or http, cookies.
> However, other types of cookies and tracking technologies include local storage objects
> (LSOs) or ‘flash’ cookies, software development kits (SDKs), pixel trackers (or pixel gifs),
> ‘like’ buttons and social sharing tools, and device fingerprinting technologies. The law on
> cookies generally applies to all of these tools."

> "Do analytics cookies require consent?
> Yes. Analytics cookies are used as a measuring tool for websites, including to provide
> information on the number of unique visitors and the pages they browse during their
> visits."

> "Consent
> The ePrivacy Regulations require that you obtain consent in order to gain any access to
> information stored in the terminal equipment of a subscriber or user, or to store any
> information on the person’s device. This means you must get consent to store or set
> cookies, regardless of whether the cookies or other tracking technologies you are using
> contain personal data."

<https://www.dataprotection.ie/sites/default/files/uploads/2020-04/Guidance%20note%20on%20cookies%20and%20other%20tracking%20technologies.pdf>

**Comment by KathleenDollard** [comment]
Thank you for reaching out. We understand your concern, and have a product update in progress for supported products. We are targeting completion over the next two months. This update will provide a telemetry data collection notice and opt out instructions sooner, during the install experience and prior to data collection. We use industry best practices and have technical and organizational measures in place to protect personal data and to meet GDPR obligations. If you’d like to learn more, you can find additional details in the Microsoft Privacy Statement.
