### ISSUE TITLE
Unable to load the service index for source https://powershell.myget.org/F/powershell-core/api/v3/index.json - Feed does not exist.

### ISSUE THREAD

**Issue by satya-rajesh** [dotnet/sdk#15276]
/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Unable to load the service index for source https://powershell.myget.org/F/powershell-core/api/v3/index.json. [/usr/src/photon/BUILD/PowerShell-7.0.3/src/powershell-unix/powershell-unix.csproj]
/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/usr/src/photon/BUILD/PowerShell-7.0.3/src/powershell-unix/powershell-unix.csproj]
error: Bad exit status from /var/tmp/rpm-tmp.x28ccJ (%build)

While accessing the url: https://powershell.myget.org/F/powershell-core/api/v3/index.json, it throws "Feed does not exist."

**Comment by joeloff** [comment]
A number of MyGet feeds have been removed. @clairernovotny was this one of them or would this be owned by a different org?

**Comment by clairernovotny** [comment]
I don't know anything about a PowerShell MyGet instance, only about the dotnet one, sorry.

**Comment by joeloff** [comment]
@satya-rajesh the SDK doesn't own the myget feed you're trying to access. and it appears to no longer exist. Your best bet would be to reach out to Powershell owners who likely removed the feed or perhaps reach out to MyGet to confirm.
