### ISSUE TITLE
Can no longer reference netstandard1.5 and netstandard1.6 using 1.x SDK

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1527]
Starting a separate GitHub thread on this...

See https://github.com/dotnet/sdk/issues/1488 and https://developercommunity.visualstudio.com/content/problem/93342/cant-downgrade-to-lower-net-core-sdk.html

cc @xenry @eerhardt @ericstj @dsplaisted @neman @jeffpapp @dasMulli

**Comment by nguerrera** [comment]
@jeffpapp

**Comment by nguerrera** [comment]
This was a deliberate change in https://github.com/dotnet/sdk/pull/1461, but:

* It was discovered late that 1.5+ refs instead of 2.0+ refs were impacted and we opted to change the error message to account for the reality.
* I don't recall discussion about the LTS consequences of requiring the 2.0 SDK where the 1.x SDK used to work.

**Comment by nguerrera** [comment]
@xenry wrote:

> I started hitting the same issue as @TomGroeneboer (and as it seems many others) after updating to 15.3 and installing the .net core 2.0 sdk:
> The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher. Please install version 2.0 or higher of the .NET Core SDK

@xenry You should not have received this error with the .NET Core 2.0 SDK installed unless you have a global.json specifying a 1.x version. Do you have that?


> Now I have done everything short of downgrading VS to 15.2 - uninstalled all net core sdks that I had and installed again only sdk 1.0.4, added the <DependsOnNETStandard>true</DependsOnNETStandard> > property, but still I cannot get rid of that error. I am trying to build a simple net462 project that references netstandard 1.5 project.

The component that is triggering the error (Microsoft.NET.Build.Extensions) is picked up by VS separately from the .NET Core SDK. Installing only old version of the .NET Core SDK will not impact this error.

To turn this code path off, you would want `<DependsOnNETStandard>false</DependsOnNETStandard>` not true, but that can cause other issues. Using the 2.0 SDK as the error message indicates would be preferable.

**Comment by xenry** [comment]
@nguerrera, thanks for taking care of this issue. 

> @xenry You should not have received this error with the .NET Core 2.0 SDK installed unless you have a global.json specifying a 1.x version. Do you have that?

yes, I have the global.json specifying 1.0.4. After the build errors started, I deleted the global.json which fixed the build. But then the YSOD showed up (asp web api 2, net462) and I had to do the binding redirects in web.config. And then when everything was working for me (and my changes to global.json and web.config were committed) continuous integration started complaining, because we don't have yet the new build tools and net core sdk on the build server.
As you can imagine we have to stop this avalanche and revert. I will try with `<DependsOnNETStandard>false</DependsOnNETStandard>`, thanks.

**Comment by ericstj** [comment]
><DependsOnNETStandard>false</DependsOnNETStandard> not true, but that can cause other issues. Using the 2.0 SDK as the error message indicates would be preferable.

If you disable the added references by setting this to false, and you have a new NuGet then you will fail at runtime per https://github.com/dotnet/sdk/issues/1386

**Comment by xenry** [comment]
thanks @nguerrera, it seems that `<DependsOnNETStandard>false</DependsOnNETStandard>` works in our case for now.

**Comment by livarcocc** [comment]
This was a conscious decision we had to make and we can't really roll it back. Given that it seems there is a work around and that using the 2.0 SDK solves the problem as well, I am going to close this issue.
