### ISSUE TITLE
NUGET Documentation Xml file no more restored

### ISSUE THREAD

**Issue by MonDeveloper** [dotnet/sdk#1531]
I'm not sure I'm posting the issue in the right repo, please help me.

My issue is quite simple, if I create a new project using VS2017 using the "old" csproj when I add a package reference to any nuget package (take the "microsoft.aspnetcore.mvc.core" package as example, but it's not relevant, the issue is always present with any packages) after building the project I can find into my output folder both **Microsoft.AspNetCore.Mvc.Core.dll** and **Microsoft.AspNetCore.Mvc.Core.xml** (together with my dll)

If I migrate the csproj to the "Microsoft.dotnet.sdk", this behaviour changes and I'm no more able to get the XML into my output folder.

It doesn't matter the framework of the project, it's all about the "old" or "new" csproj format, I think it's correlated to the tool used to restore.

I read a lot in deep the nuget spec documentation and making some tricks now i'm able to produce my own nuget packages including the Documentation XML as Content (ye, I dislike it too but it's the only way I found out) and doing this way, when I reference that package the xml file is added into the project as link, unfotunately it is not copied into the output folder and it is not possible to mark as "Copy Always" because doing this way it adds into the csproj its full path which contains the version :-(
And, even if this technique could work, it could be applied to my own packages, not for all the existing ones.

Please, point me in the right direction to address this problem, I really need to have the XML contained into the nuget package in the output folder of my main project.

**Comment by wli3** [comment]
Hi @MonDeveloper  I believe your problem is the same as issue https://github.com/NuGet/Home/issues/3891 . Unfortunately, it has not been resolved. There are some walkaround in the thread that you can try. Please reopen this issue if otherwise.
