### ISSUE TITLE
Option to use the latest available patch version for the runtime framework for self-contained publishing

### ISSUE THREAD

**Issue by czdietrich** [dotnet/sdk#15326]
**Description**

When a .NET Core app is published as self-contained build, the publish mechanism will automatically opt-in to use the latest runtime framework patch version by setting `TargetLatestRuntimePatch` to `true`. This option uses information provided by the used .NET Core SDK to determine what patch version should be used. (e.g. for .NET Core SDK 3.1.404 the information is stored here: C:\Program Files\dotnet\sdk\3.1.404\Microsoft.NETCoreSdk.BundledVersions.props) 
This means that different .NET Core SDKs will use different patch versions when publishing an app.

Since the .NET Core SDKs are installed in-place since 3.1 and usually updated by Visual Studio or recently also by [Microsoft Update](https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/#in-place-install-for-monthly-servicing-updates), it is hard to coordinate that all machines have always the same .NET Core SDK installed at a given time. This leads to the problem that different machines might produce different output when publishing.

**Scenario**

Our build-agents produce nightly installers for the current development stage, so it is possible that a new build could use older runtime DLLs, when the SDK is not yet updated, which would result in a DLL-version-downgrade, which is usually a problem for installers.

**Workarounds**

We could pin a specific .NET Core SDK using the `global.json` by disabling the roll-forward policy. This will most probably produce a lot of unwanted trouble each time the SDK is updated, so this is not really a good option.

Currently we set `RuntimeFrameworkVersion` to a specific patch version, which works independently from the used .NET Core SDK, but this leads also to some manual work, since it needs to be updated every time a new runtime framework version is released, since we always want the latest security patches on our customer's systems.

**Question**

Is it possible to use the latest "online available" runtime framework DLLs when publishing a .NET Core app?

_Runtime framework DLLs seem to be also restored by NuGet (e.g. microsoft.netcore.app.runtime.win-x64), so it might be easy to actually restore the latest version_

**Comment by dsplaisted** [comment]
There's not currently a way to check for the latest version of the runtime available without updating the SDK.  We have this issue tracking something like that: #11226

That said, I think it's probably a good idea to figure out how to have a consistent build environment on your CI machines, ie apply updates (from VS, MS Update, or wherever) to all of them consistently.
