### ISSUE TITLE
[6.0.100-alpha.1.21064.27 ] dotnet watch test command missing

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/sdk#15348]
**Application Name:**  dotnet watch
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-alpha.1.21064.27
**DevDiv bug:** [https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1266497](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1266497)

 **Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-alpha.1.21064.27: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.101 : Pass
3). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300  Pass

 **Repo Machine Environment Info:**
  C:\h\w\AA5A0904\p>dotnet --info 
  .NET SDK (reflecting any global.json):
  Version:   6.0.100-alpha.1.21064.27
  Commit:    4239e5cd10
 
**Runtime Environment:**
  OS Name:     Windows
  OS Version:  10.0.17763
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21064.27\
 
**Host (useful for support):**
   Version: 6.0.0-alpha.1.21063.13
   Commit:  6ded57b3d2
 
 **.NET SDKs installed:**
   6.0.100-alpha.1.21064.27 [C:\Program Files\dotnet\sdk]
 
**.NET runtimes installed:**
   Microsoft.AspNetCore.App 6.0.0-alpha.1.21063.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
   Microsoft.NETCore.App 6.0.0-alpha.1.21063.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
   Microsoft.WindowsDesktop.App 6.0.0-alpha.1.21062.4 

**Repro steps:**
1) Create a unit test project with dotnet new mstest
2) run this command  : dotnet watch test

**Expected Result:**
it should run test, when you make change in the test method, it should update test result

**Actual Result:**
MSBUILD : error MSB1009: Project file does not exist.
Switch: watch

**Findings:**
It looks like dotnet watch test command is removed, but is not clear how to start tests with dotnet watch in this SDK. Help command doesn't give information, when we run dotnet watch, it doesn't start tests, it is not same as dotnet watch test

@dotnet-actwx-bot 
@dotnet/compat

**Comment by marcpopMSFT** [comment]
We expect this to get fixed by https://github.com/dotnet/sdk/pull/15362

**Comment by jiangzeng01** [comment]
Verified with 6.0.100-preview.1.21074.2, so close
