### ISSUE TITLE
[6.0.100-alpha.1.21064.27] dotnet tool fake template build failed with error MSB1009: Project file does not exist

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/sdk#15350]
**Application Name:** GlobalToolsNETCore21Part01
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-alpha.1.21064.27
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1266536](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1266536)

**Repro steps:**
1.Open cmd.exe from %windir%\System32 
2. Input install command:  dotnet tool install -g fake-cli --version 5.19.1 
3. Press keyboard “Enter”.
4. Input “cd %APP_CLIENT_ROOT%” and press keyboard ‘Enter’.
5. Create a file folder via command: md FakeTest, then input command: cd FakeTest  
6. Install Fake Template via command: "dotnet new -i fake-template::5.18.3"  and press keyboard “Enter”.
7. Input command: dotnet new fake and press keyboard “Enter”.
8. Input Y in the command window, and then press “Enter” with keyboard. 
9. Input command:  .\fake.cmd build 

**Expected Result:**
It will run successfully.

**Actual Result:**
Get exception: MSBUILD : error MSB1009: Project file does not exist.

**Findings:**
We compared the working scenario, there are the same files exists in the FakeTest folder, both of them are don’t have .csproj file exists.

@dotnet-actwx-bot

**Comment by sfoslund** [comment]
This is another instance of the issue in https://github.com/dotnet/sdk/issues/15349, I'll close this and track the bug there.

**Comment by jiangzeng01** [comment]
Verified as fixed with 6.0.100-preview.1.21074.2
