### ISSUE TITLE
Mixing netcoreapp TF and packages silently produces bad executables

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1536]
Consider the following scenario. Create a simple EXE project and ensure the following two elements are set

``` xml
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="2.0.0" />
  </ItemGroup>
```

This project will restore, build and publish without any error. Yet when exe is run the following error is produced:

``` txt
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

Agree this is a completely invalid configuration. However it's also one that's fairly easy to get into when you are migrating a 1.X project to the 2.0 SDK. There is no guidance here that anything was done incorrectly and the error produced by the EXE is not productive. 

I would expect that a error is produced somewhere in the restore or publish steps.

**Comment by nguerrera** [comment]
@ericstj Why does Microsoft.NETCore.App package install to netcoreapp1.0 TFMs? Shouldn't it be incompatible?

**Comment by ericstj** [comment]
We have always made the package backwards compatible with the older TFMs.  It's something we were explicitly requested to do in 1.1.  We copy the old dependencies in a separate dependency group.  I do think the SDK handled this before /cc @dsplaisted @eerhardt

**Comment by nguerrera** [comment]
I don't get the use case for this with the netcoreapp package. NetStandard.Library, I got. 

IIRC, we use the package version to control runtime config and other stuff because TFM isn't enough, and even RuntimeFramework version is allowed to have -* versioning. 

I'm not sure what we can do other than throw an error, but then what is the point of it being installable? What scenarios that prompted asking for it to be installable would break if we override that and make it work? Or, in other words, how is this project expected to behave if this is not an error?

**Comment by eerhardt** [comment]
I just tried this with the 2.0.0 RTM version, and it worked for me:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="2.0.0" />
  </ItemGroup>
</Project>
```

```
>dotnet run
C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(199,5): warning : A PackageReference for 'Microsoft.NETCore.App' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [F:\DotNetTest\MixTest\MixTest.csproj]
Hello World!
```

@jaredpar - is there something else I'm missing?  Were you using an old `dotnet.exe` host and not the 2.0 host?

**Comment by eerhardt** [comment]
I published as stand-alone, and then I got the error:

```
>dotnet publish -r win7-x64
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(199,5): warning : A PackageReference for 'Microsoft.NETCore.App' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [F:\DotNetTest\MixTest\MixTest.csproj]
  MixTest -> F:\DotNetTest\MixTest\bin\Debug\netcoreapp1.1\win7-x64\MixTest.dll
  MixTest -> F:\DotNetTest\MixTest\bin\Debug\netcoreapp1.1\win7-x64\publish\

>bin\Debug\netcoreapp1.1\win7-x64\publish\MixTest.exe
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/issues/1541 has discussion of scenario where compatibility with older tfm from package is required and link to issue requiring this trend be continued in 2.1.

So the true expectation here is that this produces a working standalone 1.1 app, correct?
