### ISSUE TITLE
Generate errors for assembly version conflicts for Microsoft.Windows.SDK.NET

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#15370]
The Windows CSWinRT API targeting packs are going to be updating regularly. This means that libraries compiled with newer versions of the .NET SDK will have an assembly reference to higher versions of Microsoft.Windows.SDK.NET.dll. If a project that is using an older version of the .NET SDK consumes an updated library (ie via a NuGet package), then there will be an MSB3277 warning from ResolveAssemblyReferences, and a FileLoadException at runtime. (Depending on how types are shared, the build may also fail with a CS1705 compiler error.)

Instead of a build warning and a runtime failure, this should fail at build time with a message saying that a dependency depends on a newer version of Microsoft.Windows.SDK.NET, and suggesting updating the .NET SDK.  It is now possible for us to implement since MSBuild implemented https://github.com/dotnet/msbuild/pull/5990.

**Comment by sfoslund** [comment]
Fixed in 5.0.2xx by #15430
