### ISSUE TITLE
Multitarget net48 problem

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/sdk#15396]
I have a large solution with many projects. 
If I multitarget net5.0;net5.0-windows for all of them but if I multitarget also net48 all but 1 of the assemblies compile. 

When building the following CA1000 error appears: 
![image](https://user-images.githubusercontent.com/9577365/105067170-bc370180-5a7f-11eb-8d0b-b7561087512b.png)

Not sure what to do! 

It should be noted that the project that failes has netfw references/(thirdparty) that works both during compile time and runtime for net5.0-windows.

**Comment by clairernovotny** [comment]
Dup of https://github.com/dotnet/sdk/issues/15291

**Comment by JensNordenbro** [comment]
Hi @clairernovotny; is it really a "Dup" ? , the exception/error message is not the same as in #15291 although both are about multi targeting.

**Comment by clairernovotny** [comment]
The underlying cause the issue with ResolvePackageDependencies, appears to be the same at first glance.

**Comment by dsplaisted** [comment]
Yes, please try this again once VS 15.9 releases.  If you still have issues then let us know and we can re-open.

**Comment by JensNordenbro** [comment]
@dsplaisted   Do you mean 16.9? - I am running 16.8.x non-preview ver on this computer... 

Will it arrive in preview earlier ?

**Comment by dsplaisted** [comment]
Oops, yes I mean 16.9.  It looks like it should be in the next preview release of 16.9 (Preview 4).
