### ISSUE TITLE
Enable Source Link, Generators, and custom props/targets to work with WPF in 5.x

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sdk#15395]
There were two issues fixed in WPF for 6.0 that were just back-ported to 5.0.2/5.0.3 behind an opt-in flag. It's opt-in with WPF as they can't differentiate between runtime and SDK.

The SDK (5.0.200/300) needs to enable this property by default so PackageReferences and custom BaseIntermediateOutputPath fully work in WPF. This will unblock Generators, Source Link, and any other NuGet package that contains custom props/targets in it.

`IncludePackageReferencesDuringMarkupCompilation` should be set to true by the SDK if undefined by the user code.

These are the PR's to 5.0 servicing containing the fixes we want to enable in the SDK
https://github.com/dotnet/wpf/pull/4009
https://github.com/dotnet/wpf/pull/3846

This will resolve the following issues:
https://github.com/dotnet/wpf/issues/810
https://github.com/dotnet/wpf/issues/3404
https://github.com/dotnet/wpf/issues/1718

Likely this one too: https://github.com/dotnet/wpf/issues/366

**Comment by clairernovotny** [comment]
@tmat @jaredpar

**Comment by jaredpar** [comment]
@marcpopMSFT wanted to make sure that you saw this issue. This impacts some division goals around Terrapin and we're really hoping we can get it in for 16.9. The work should be small, just setting a few defaults in WPF projects. But time is getting short in 16.9 so wanted to make sure this hadn't slipped below your radar.

**Comment by sfoslund** [comment]
Fixed in 5.0.2xx by https://github.com/dotnet/sdk/pull/15465
