### ISSUE TITLE
Error CS5001  Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by OWAProjects** [dotnet/sdk#1540]
I've just updated Visual studios which apparently updates the .Net core SDK however my existing project and any new console application I create from scratch results in the error:

`Error CS5001  Program does not contain a static 'Main' method suitable for an entry point`

I have no idea why this is or how to fix it and wouldn't expect it to happen from a Visual Studios prompted update. Any suggestions?

**Comment by nguerrera** [comment]
Strange. This means that the source file containing the Main method was somehow not passed to the compiler. 

Does  `msbuild /t:restore && msbuild /bl` work` from VS Developer Command prompt?

If not, can you share the msbuild.binlog that the above command will output?

**Comment by JosKrause** [comment]
@OWAProjects in my particular case it was a matter of changing the `private` into a `public` on the **Main** method.

**Comment by livarcocc** [comment]
Given that we haven't gotten a repro for this and haven't had activity here in a while, I am closing this issue.

@OWAProjects if this still happens to you, please provide us with a repro or with logs, by running `dotnet build /bl` and sharing with us the msbuild.binlog file and we can re-activate this issue.
