### ISSUE TITLE
With .NET 6 SDK, Create xunit/mstest failed in CLI if not specify tfm

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#15412]
Repro steps:
Install .NET 6 SDK(6.0.100-alpha.1.21069.22) from https://github.com/dotnet/installer
Run "dotnet new xunit" or "dotnet new mstest" in CLI

Expected Result
xunit/mstest should be created successfully

Actual Result:
Created failed
![image](https://user-images.githubusercontent.com/65637796/105138141-73d71c80-5b2f-11eb-9680-387011c0afee.png)

Note:
Not repro on nunit(dotnet new nunit)
if run "donet new xunit -f net6.0", project can be created successfully

**Comment by dsplaisted** [comment]
@nohwnd Have the mstest and xunit templates been updated to target .NET 6?

**Comment by vdanche** [comment]
The issue has been fixed on NET 6SDK: 6.0.100-alpha.1.21070.34(runtime-6.0.0-alpha.1.21070.2) and the the mstest and xunit templates been updated to target .NET 6.
![image](https://user-images.githubusercontent.com/65637796/105331158-1960bd80-5c0e-11eb-8fd0-1736fb64176d.png)

**Comment by nohwnd** [comment]
https://github.com/dotnet/test-templates/pull/118 This is the fix PR. We got the templates updated via PR, and the priority was not set correctly. As you noticed it is already merged, and it propagated to installer yesterday.
