### ISSUE TITLE
Be a better citizen on Windows (don't pollute %USERPROFILE%).

### ISSUE THREAD

**Issue by MicahZoltu** [dotnet/sdk#1543]
I just installed .NET Core SDK onto a Windows 10 Pro (Fall Creators Update) machine.  As a side effect, it appears to have created a folder in `%USERPROFILE%` named `.dotnet`.  On Windows, applications should not be writing configuration data to `%USERPROFILE%` and instead should be writing it to `%APPDATA%\<vendor>\<product>`.  In this case that would be `%APPDATA%\Microsoft\dotnet`.

Not only does the `.` prefix on folders cause problems in Windows (explorer will not allow you to name a folder starting with a `.`), but it also pollutes what is supposed to be a user-facing folder with configuration data that is _not_ user facing.  In general, the only things that should be put into `%USERPROFILE%` are things the user has explicitly put there via a save dialog.  Any files automatically created by an application should go into `%APPDATA%\<vendor>\<product>`.

As a side note, is there a way I can override this setting while waiting for this issue to be resolved?  The files in this folder appear to not be intended for human consumption, and I really try to keep my `%USERPROFILE%` directory uncluttered with garbage from various things I have installed on my computer.

**Comment by livarcocc** [comment]
Let's track this issue at https://github.com/dotnet/cli/issues/7569.

**Comment by MicahZoltu** [comment]
I'm hesitant to combine these two issues because the other is asking for to make the path customizable while this one is asking to change the _default_ location.  I believe that getting the default changed is more important than making it customizable because right now the default is not following proper Windows standards/recommendations.

**Comment by livarcocc** [comment]
I would suggest that you comment there. That's the more appropriate repo for this change. The CLI is the one that is using the userprofile location.

**Comment by Neme12** [comment]
> Let's track this issue at https://github.com/dotnet/cli/issues/7569.

That issue was closed, but that one only tracked being able to change the location, not changing the default. This is not a dupe of that :/

**Comment by Neme12** [comment]
Oh there's another issue for this, although in a different repo: https://github.com/dotnet/templating/issues/852
