### ISSUE TITLE
OR_GREATER symbols for NETSTANDARD: difference between design and implementation

### ISSUE THREAD

**Issue by ufcpp** [dotnet/sdk#15470]
There are NETSTANDARDX_X_OR_GREATER symbols in [the design document](https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md#doc-changes) but they are [not implemented](https://github.com/dotnet/sdk/blob/c2aad5bc5973301107271a31cbbcb77fa423113e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L232) so far. Which is correct? The doc should be modified?

**Comment by marcpopMSFT** [comment]
@sfoslund I believe you only implemented these for NETCOREAPP and NET, correct?  @terrajobst did you want these added for our other frameworks?

**Comment by sfoslund** [comment]
Yes, I only implemented the frameworks in the design section of that doc: https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md#design

**Comment by ufcpp** [comment]
Oh, sure. .NET Standard is not in [the design section](https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md#design).

However, it is in [the doc changes section](https://github.com/dotnet/designs/blob/be793b557255c9ed1276ecdd23119b64f45453bf/accepted/2020/or-greater-defines/or-greater-defines.md#doc-changes):

![image](https://user-images.githubusercontent.com/3760955/106217558-d360b680-6218-11eb-81ae-863c66e6ca0b.png)

**Comment by sfoslund** [comment]
@terrajobst can we get some guidance on the intention of the spec?

**Comment by terrajobst** [comment]
Sorry, I must have missed that in the PR :-(

Yes, the intent is to handle .NET Framework, .NET Core, and .NET Standard.

**Comment by sfoslund** [comment]
Thanks for the clarification, I'll add .NET standard symbols for 5.0.3xx.

**Comment by sfoslund** [comment]
Fixed in 5.0.3xx by #15660
