### ISSUE TITLE
Multitargeting WPF requires Microsoft.NET.Sdk.WindowsDesktop

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/sdk#15475]
Assume the following project: 
![image](https://user-images.githubusercontent.com/9577365/105637425-cd13b880-5e6d-11eb-96a0-7a744a0debab.png)

The following error occures: 
![image](https://user-images.githubusercontent.com/9577365/105637449-e452a600-5e6d-11eb-887a-482048b0d11d.png)

Removing the net48 moniker and the error dissappears, however I would like to be able to build for net48 still. 

Re-enabling both targets; I look into the assembly references: 

![image](https://user-images.githubusercontent.com/9577365/105637513-3398d680-5e6e-11eb-9686-736d9f241315.png)

=> No Wpf assemblies available for net48. 

Changing to use the old Sdk="Microsoft.NET.Sdk.WindowsDesktop": 

![image](https://user-images.githubusercontent.com/9577365/105637574-8e323280-5e6e-11eb-9599-aa6d32db2b2a.png)

Gives: 

![image](https://user-images.githubusercontent.com/9577365/105637546-6e9b0a00-5e6e-11eb-9990-1a1c70145b70.png) 
... and it all builds. 

This is reproduced on two computers. 
One with 
3.1.405 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]

another with 5.0.2xx preview.

**Comment by RussKie** [comment]
This is by design. The platform moniker was added in .NET 5.0, so all previous versions must opt in to the WindowsDesktop SDK explicitly.

**Comment by marcpopMSFT** [comment]
Actually, we went ahead and automatically import WindowsDesktop targets when multi-targeting to framework.  This will be available starting in 5.0.2xx-preview 4 in a couple of weeks: https://github.com/dotnet/sdk/pull/15213

**Comment by JensNordenbro** [comment]
Sounds good!
