### ISSUE TITLE
A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist

### ISSUE THREAD

**Issue by rodrigofbm** [dotnet/sdk#15476]
I was facing this error on Fedora 33, so I went back to 32 and the error persists.

```
  Verificando         : aspnetcore-runtime-3.1-3.1.11-1.fc32.x86_64                                     1/10 
  Verificando         : aspnetcore-targeting-pack-3.1-3.1.11-1.fc32.x86_64                              2/10 
  Verificando         : dotnet-apphost-pack-3.1-3.1.11-1.fc32.x86_64                                    3/10 
  Verificando         : dotnet-hostfxr-3.1-3.1.11-1.fc32.x86_64                                         4/10 
  Verificando         : dotnet-runtime-3.1-3.1.11-1.fc32.x86_64                                         5/10 
  Verificando         : dotnet-targeting-pack-3.1-3.1.11-1.fc32.x86_64                                  6/10 
  Verificando         : netstandard-targeting-pack-2.1-3.1.111-1.fc32.x86_64                            7/10 
  Verificando         : lttng-ust-2.11.0-4.fc32.x86_64                                                  8/10 
  Verificando         : dotnet-host-5.0.2-1.x86_64                                                      9/10 
  Verificando         : dotnet-sdk-3.1-3.1.405-1.x86_64                                                10/10 

Instalados:
  aspnetcore-runtime-3.1-3.1.11-1.fc32.x86_64       aspnetcore-targeting-pack-3.1-3.1.11-1.fc32.x86_64       
  dotnet-apphost-pack-3.1-3.1.11-1.fc32.x86_64      dotnet-host-5.0.2-1.x86_64                               
  dotnet-hostfxr-3.1-3.1.11-1.fc32.x86_64           dotnet-runtime-3.1-3.1.11-1.fc32.x86_64                  
  dotnet-sdk-3.1-3.1.405-1.x86_64                   dotnet-targeting-pack-3.1-3.1.11-1.fc32.x86_64           
  lttng-ust-2.11.0-4.fc32.x86_64                    netstandard-targeting-pack-2.1-3.1.111-1.fc32.x86_64     

Concluído!
[rtorres@localhost ~]$ dotnet --info
**A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist**
```

**Comment by dagood** [comment]
This is an instance of https://github.com/dotnet/docs/issues/18347: you have some mixed packages from the Microsoft build of .NET and the Fedora build of .NET (built from source). They install to different locations, so they don't work nicely together and give you this "does not exist" error.

This package is from Fedora: `dotnet-hostfxr-3.1-3.1.11-1.fc32.x86_64`
This package is from Microsoft: `dotnet-host-5.0.2-1.x86_64` (no `fc32`)

The easiest way to resolve this is to remove the Microsoft package repository configuration from your machine and remove + install the .NET packages again, to get all the packages from Fedora.

(I'm not familiar off the top of my head what the best commands are to do that--it might also depend on how you set up the Microsoft repo on your machine. Let us know if you need more help here.)

**Comment by rodrigofbm** [comment]
@dagood thank you bro

**Comment by dagood** [comment]
No problem, glad that helped. 🙂

**Comment by skarning** [comment]
So I was really stuck on this issue and  I tried the solutions in this thread multiple times but it did not work.

Turns out the issue was that even tough i removed all the ppa's from microsoft using the software & updates feature in ubuntu there was still a microsfot ppa left that you can only see when you list them with this command:
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/

If there are still any microsoft sources left then just remove them for that file.

**Comment by paulonev** [comment]
Used this [paragraph](https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#my-linux-distribution-provides-net-packages-and-i-want-to-use-them) from microsoft documentation and the problem had gone!
