### ISSUE TITLE
net48 requires explicit references to framework assemblies

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/sdk#15480]
When building a project for net48 target we had to explicitly add assemblies that we did not have to do for net5. 
It expect that symmetry applies or that this is documented (maybe it is?!) 
This subset of a csproj comes from a multitargeting application: 

![image](https://user-images.githubusercontent.com/9577365/105705228-3815cb80-5f10-11eb-8d8c-59d20a0092f7.png)

**Comment by sfoslund** [comment]
What is your goal, are you referencing these assemblies in your code? If so, you probably want to use nuget packages instead of direct references to the dlls

**Comment by JensNordenbro** [comment]
My goal is to port an application from net48 to net5 while at the same time keeping the net48 targeting until net5 is done and the net48 generation is phased out. 

I have a theory the problem can be thirdparty assembly references that not yet has not moved to net core. 
These references however are perfectly fine for a smaller subset of the application. It not only compiles but also works fine on both net48 (no wonder) and net5 (more of a wonder). 

**This problem only occurs on WPF targeting assemblies.** 

I would have expected this to be problematic for net5 but it is the net48 that complains... 

I will validate my claims on monday when I can study the sources.

**Comment by JensNordenbro** [comment]
also these explicitly refered net48 assemblies are part of net48 and as such should not have to be specified..

**Comment by JensNordenbro** [comment]
basically symmetry is expected and this have a "random" touch to it.

**Comment by sfoslund** [comment]
@wli3 is this expected for net framework or is something off here?

**Comment by wli3** [comment]
This is expected. Some API will not be available in core https://github.com/dotnet/core/issues/838. The goal of net5 is not 100% compatible with net48. If you need to maintain both net48, and net5.0, you need to use the common set of APIs (like netstandard2.0) with help of nuget package (some API available in net48 are shipped separately as nuget packages). Or you need to compile conditionally.

**Comment by JensNordenbro** [comment]
But the apis are available in both net5 and net48...

**Comment by wli3** [comment]
@JensNordenbro could you give me an API example

**Comment by JensNordenbro** [comment]
I will try; huge project though... all i have is the dll:s mentioned. 

Also I will try to upgrade to net6-preview1. 

I wil get back to you!

**Comment by JensNordenbro** [comment]
We will go with the NuGet route for now regarding the extra references. 
If this works this detail will not matter in the long run...
