### ISSUE TITLE
NetStandardImplicitPackageVersion ignored for .NET Framework

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#1550]
_From @AlexanderSher on August 27, 2017 3:21_

## Details about Problem

NuGet product used: VS UI
NuGet version: 4.3.0
VS version: 15.3.1
OS version: Windows 10.0.15063

## Detailed repro steps so we can see the same problem
1. Create empty .net standard project.
2. Change target frameworks to <TargetFrameworks>net46;netstandard1.6</TargetFrameworks>
3. Add reference to any package that requires .NETStandard.Library, for example: Microsoft.Extensions.FileSystemGlobbing version 1.1.1
4. Add `<NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>`
5. Build

**Actual**: project.assets.json specifies "NETStandard.Library/1.6.1" as a dependency for ".NETFramework,Version=v4.6" target but "NETStandard.Library/2.0.0" for ".NETStandard,Version=v1.6" target.
**Expected**: All targets should have "NETStandard.Library/2.0.0" dependency

### Sample Project
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net46;netstandard1.6</TargetFrameworks>
    <NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="1.1.1" />
  </ItemGroup>
</Project>
```
No content required.

_Copied from original issue: NuGet/Home#5809_

**Comment by rohit21agrawal** [comment]
_From @dasMulli on August 27, 2017 10:28_

This is by design: `NetStandardImplicitPackageVersion` only sets the version of `NETStandard.Library` for target frameworks that the SDK implicitly adds a package to `NETStandard.Library` for. This is only used for the `netstandard*` target frameworks since it requires the tooling to reference a version of `NETStandard.Library` to get the compile time references. Since there is no implicit ("automatic") reference to `NETStandard.Library` for `net*` projects, this property has no effect. Since `Microsoft.Extensions.FileSystemGlobbing/1.1.1` depends on `NETStandard.Library/1.6.1` and there is no explicit package reference to `NETStandard.Library/2.0.0`, `1.6.1` will be used.

Why do you want to use `2.0.0`? You can always explicitly reference the version to upgrade the transitive dependency:

```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />
  </ItemGroup>
```

**Comment by rohit21agrawal** [comment]
_From @AlexanderSher on August 27, 2017 14:20_

Well, this is not what suggested in documentation, which says that one should never have an explicit reference to the `NetStandard.Library` and use `<NetStandardImplicitPackageVersion>`:
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj
https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj

And I actually surprised that users should add conditional item groups to achieve equal output for different frameworks. It isn't quite "standard".

**Comment by rohit21agrawal** [comment]
_From @dasMulli on August 27, 2017 14:48_

Ouch I see.. well the bullet points in that section of the docs are specific to .net core (`RuntimeFrameworkVersion`) and .net standard (`NetStandardImplicitPackageVersion`) and have nothing to do with .net framework, but it really doesn't say that very clearly..

**Comment by rohit21agrawal** [comment]
_From @dasMulli on August 27, 2017 14:59_

@AlexanderSher I've opened a PR to the document to clarify which target frameworks the respective properties apply to https://github.com/dotnet/docs/pull/3006

**Comment by livarcocc** [comment]
Closing as the documentation has since been patched.
