### ISSUE TITLE
Figure out relationship between Directory.Build.targets and workloads

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#15505]
Currently, it's not possible to set a property in Directory.Build.targets which enables a .NET SDK workload.  We should figure out what to do here - something will have to change (and we'll have to accept some sort of breaking change) in order to make Windows Forms / WPF support a .NET SDK workload, which we want to do eventually.

This is a tracking issue for now, we plan to put up a design on dotnet/designs for discussion.  Related PRs:

https://github.com/dotnet/sdk/pull/14393
https://github.com/dotnet/sdk/pull/15449

**Comment by marcpopMSFT** [comment]
Note that if we do add additional automatically imported targets, we'll want to double check performance impact.  A quick check indicated that disabling the directory.build.props and directory.build.targets imports could save on the order of milliseconds so probably fine.

**Comment by marcpopMSFT** [comment]
No longer needed as workloads worked around this for now.
