### ISSUE TITLE
[ 6.0.100-preview.1.21077.11] dotnet hash -h displays help for dotnet SDK not for dotnet hash

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/sdk#15541]
**Application Name:**  dotnet hash global tool app
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:**  6.0.100-preview.1.21077.11
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1271105](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1271105)

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.1.21077.11: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.102: Pass

**Repro steps**
1) Install app : 
dotnet tool install TheBlueSky.DotNet.Tools.SwiftHash --global
2) Run : dotnet hash -h

**Expected Result:**
It should display help menu for dotnet hash global tool app

**Actual Result:**
It displays help menu for dotnet SDK, same as dotnet -h

**More Examples**
```
dotnet hash -h               Displays dotnet SDK help menu
dotnet hash -?               Displays dotnet SDK help menu
dotnet hash --help        Displays dotnet SDK help menu
dotnet hash -help         OK
dotnet-hash -h              OK
```

@dotnet-actwx-bot  @dotnet/compat

**Comment by jiangzeng01** [comment]
@sfoslund We tested with latest .NET 6 Preview 1 build: 6.0.100-preview.1.21103.13, the issue is still happening.
Can you check?

**Comment by sfoslund** [comment]
@jiangzeng01 I checked this fix into our master branch, so it is not available in preview 1 builds. I double checked and it does not repro with master build `6.0.100-preview.1.21103.11`. The fix will be in preview 2.

**Comment by jiangzeng01** [comment]
@sfoslund We tried with latest master daily build, your fix for "-h" work fine, but we think this issue is not only related to ‘-h’, it will repro whenever the following ‘sdk-options’ conflicts with global tool app’s options. 
```
sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET SDK version in use.
```

**Another example about global tool option conflict with sdk option:**
**Repro steps:**
1. Install a global tool app, for example dotnet-ignore :
2. dotnet tool install –g dotnet-ignore
3. run this command : dotnet ignore --version

**Expected Result:**
it should show dotnet ignore tool version

**Actual Result:**
It shows dotnet sdk version.

**Our trying:**
```
C:\WINDOWS\system32>dotnet ignore --version
6.0.100-preview.1.21104.9

C:\WINDOWS\system32>dotnet-ignore --version
1.0.6

C:\WINDOWS\system32>dotnet --version
6.0.100-preview.1.21104.9
```

**Findings:**
This issue happens not only for "-h" or "--version", if any global tool has the same options like "-d" or "--info" with sdk-option, then it will also conflict.

**Comment by jiangzeng01** [comment]
Verified with master branch build: 6.0.100-preview.2.21119.3
