### ISSUE TITLE
Unable to debug unit tests

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/sdk#15542]
In this [commit](https://github.com/dotnet/winforms/pull/4483) and after when starting the unit-test in debug mode, the studio freezes and the unit-test does not start. In normal mode, unit-tests run and work correctly. The application also support debugging, the problem is with unit tests.
![debug-issue](https://user-images.githubusercontent.com/23376742/106139999-3dc51880-617f-11eb-8b01-9e62b5eef661.png)

**Comment by hoyosjs** [comment]
This was an issue in the runtime. It will be fixed once 6.0.0-preview.2.21079.11 or greater flows into the repo.

**Comment by sfoslund** [comment]
Closing per @hoyosjs's comment that this has been fixed in the runtime.
