### ISSUE TITLE
AssemblyInfo generation results in less NuGet package info

### ISSUE THREAD

**Issue by luigiberrettini** [dotnet/sdk#1555]
With the help of [GenerateAssemblyInfo](https://github.com/dotnet/sdk/blob/979eed136b786b6e2d77f567eb5a368952982740/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets) assembly information is generated starting from tags in the project file.

Unfortunately, when using the `MsBuild pack` target, the generated NuGet package contains less information  with respect to the one created using `NuGet pack` and a `.nuspec` file:
1. in the **Package metadata** section, `Summary` is not supported by the project file and missing
2. in the **Package metadata** section, `Owners` is not supported by the project file and is set to the value of `Authors`
3. in the **Package contents\assembly information** section, only `Full Name` and `Strong Name` are present, whereas all `Assembly*` attributes are missing

It would be great if you could clarify if when creating NuGet packages with VS 2017+ and .NET core 2+:
 - `.nuspec` files are not to be used because they are going to be the deprecated way
 - `dotnet pack` or `msbuild /t:pack` should be used and the above (missing) information will be restored in future versions or will never be supported

Thanks!

**Comment by nguerrera** [comment]
@rohit21agrawal

**Comment by luigiberrettini** [comment]
Sorry do you have any update?

I just want to understand if:
- it is by design
- assembly info should all be there and you are investigating
- this issue is not in the backlog since it has low priority and you haven't analyzed it yet

Thanks!

**Comment by dasMulli** [comment]
Looks like NuGet's [`Pack` task](https://github.com/NuGet/NuGet.Client/blob/f60f2643c30886ce6b072ba7e05bca3c15be87ff/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L204-L246) would need to implement these properties in order to pass them to the `PackageBuilder`

**Comment by rohit21agrawal** [comment]
There is no plan to support Owners and Summary in dotnet pack or msbuild /t:pack

**Comment by luigiberrettini** [comment]
I am not asking for new features: it is really disappointing that .NET core is proposed as the future, but new tools, **at version 2.0 RTM**, have less features than the old ones.

I will try sticking to using NuGet and nuspec files until there is no feature parity with .NET full framework:
 - all `Assembly*` attributes, the most important ones, are missing
 - if the new version of a NuGet package has to be published, with support for both .NET classic and .NET core, people will see a change on NuGet (in case of different owners and authors) and DLL info

**Comment by luigiberrettini** [comment]
Closing since NuGet Package Explorer was updated and it seems that the less important differences are not going to be fixed by anyone.
