### ISSUE TITLE
Dotnet test `--blame-hang-dump-type` does not seem to have effect.

### ISSUE THREAD

**Issue by TimonPost** [dotnet/sdk#15555]
When I run `--blame-hang-dump-type none`, the Microsoft docs specify:

_"It should be full, mini, or none. When none is specified, test host is terminated on timeout, but no dump is collected."_ 

## My Command
```
dotnet test .\Faultify.Benchmark.NUnit\Faultify.Benchmark.NUnit.csproj --blame-hang-timeout 2000 --blame-hang-dump-type none

OR

dotnet test .\Faultify.Benchmark.XUnit\Faultify.Benchmark.XUnit.csproj --blame-hang-timeout 2000 --blame-hang-dump-type none
```

## Result
When the test timesout it generates:
![image](https://user-images.githubusercontent.com/19969910/106247145-698fdf00-620f-11eb-99d2-83d4b35e41e3.png)

```
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: The specified inactivity time of 2 seconds has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: Dumping 33252 - testhost.

**Attachments:**
  XXX\bin\Debug\netcoreapp3.1\test-duplication-3\TestResults\583a5b3b-981c-414d-92dc-316891a31e19\Sequence_d4e9a65520c549d7a5381b7db58ff94a.xml
  XXX\bin\Debug\netcoreapp3.1\test-duplication-3\TestResults\583a5b3b-981c-414d-92dc-316891a31e19\testhost_33252_20210129T085444_hangdump.dmp
```
## Version
.NET SDK (5.0.101)
Microsoft.NET.Test.Sdk 16.9.0-preview-20210127-04
Projects are dotnet core 3.1

NUnit 3.13.0
XUnit3TestAdapter 4.0.0-beta.1

XUnit 2.4.1
xunit.runner.visualstudio 2.4.3

## Replicate
The following zip contains both a NUnit and XUnit project that contains a timeout test. When running the commands in the `README.txt` you will see it generates a `TestResults` while the argument `--blame-hang-dump-type none` is provided.

[Replication.zip](https://github.com/dotnet/sdk/files/5892536/Replication.zip)

## Question
How can I disable this dump, am I doing something wrong here?

**Comment by nohwnd** [comment]
You are right this is a bug. I planned the None option, but apparently never implemented it. So it ignores the option and instead does a full dump. Adding code to just kill the process when the dump type for Hang is None. But it will take a while to get released, and will be in net6.0 only most likely. 

I don't have a workaround for this. You can only set the value to Mini to mitigate the impact of creating the process dump.
