### ISSUE TITLE
'PackageVersion' is reset to '1.0.0'

### ISSUE THREAD

**Issue by iSazonov** [dotnet/sdk#1557]
In [PowerShell Core repo](https://github.com/PowerShell/PowerShell/pull/4182) we have explicitly assign 'PackageVersion' because there is a issue: in debug file, we can see that 'PackageVersion' is correctly assigned as 'Version' in 'NuGet.targets' but then immediately redefined as '1.0.0'.

**Comment by nguerrera** [comment]
@iSazonov Can you provide a simple repro demonstrating the issue? By immediately redefined, do you mean also in NuGet.targets? 

cc @rohit21agrawal

**Comment by iSazonov** [comment]
>Can you provide a simple repro demonstrating the issue? 

On next Monday I'll try to make it.

> By immediately redefined, do you mean also in NuGet.targets?

Yes, in log file I see that just after the task complete 'PackageVersion' is assigned to '1.0.0'

**Comment by iSazonov** [comment]
[TestBuild.zip](https://github.com/dotnet/sdk/files/1286899/TestBuild.zip)

I attach a file with simple repo.
If we uncomment line `<PackageVersion>$(PSCoreBuildVersion)</PackageVersion>` we get package with right version.

**Comment by nguerrera** [comment]
The problem is that Version is being set in a target. During static evaluation before any targets are run, a default value of Version = 1.0.0 is picked and that flows to PackageVersion also during static evaluation. If you change either of these after evaluation in a target, there is no magic way for this to impact both properties. This isn't a bug, but we 

This comment is inaccurate:
``` xml
  <!--
            We have explicitly assign 'PackageVersion'
            because there is a bug: 'PackageVersion' is correctly assigned as 'Version' in 'NuGet.targets'
            but then immediately redefined as '1.0.0'.
```

It should be something like this:
``` xml
<--
We have explicitly assign 'PackageVersion' here because we're changing the Version in a target. Before any targets have run, during static evaluation, 'Version' will have defaulted to '1.0.0' and PackageVersion will have defaulted to 'Version'. So we must update both 'Version' and 'PackageVersion' here.
--->
 
This can't be 'fixed' as there's no way to make PackageVersion a dynamic property that automatically changes when Version changes dynamically in a target.

**Comment by iSazonov** [comment]
@nguerrera Thanks for clarify. 
I was hoping that SDK could be changed to eliminate this problem, maybe moving the properties in a target to benefit from conditional execution.
