### ISSUE TITLE
dotnet store exiting with code 33

### ISSUE THREAD

**Issue by jameswoodley** [dotnet/sdk#15590]
When running `dotnet store -m PackageManifest.xml -f netcoreapp3.1 -r linux-x64 --output ./store` I get an error
```
Error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  Error compiling /home/wooderz/.nuget/packages/amazon.lambda.aspnetcoreserver/5.3.0/lib/netcoreapp3.1/Amazon.Lambda.AspNetCoreServer.dll: Could not find or load a specific file. (0x80131621)
  Native image /tmp/qjzash35.qtm/Amazon.Lambda.AspNetCoreServer_5.3.0/runtimopt/Amazon.Lambda.ApplicationLoadBalancerEvents.dll generated successfully.
  Error: compilation failed for "/home/wooderz/.nuget/packages/amazon.lambda.aspnetcoreserver/5.3.0/lib/netcoreapp3.1/Amazon.Lambda.AspNetCoreServer.dll" (0x80131621)
/usr/share/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(148,5): error MSB3073: The command "/tmp/qjzash35.qtm/Optimize/netcoreapp/crossgen -nologo -readytorun -in "/home/wooderz/.nuget/packages/amazon.lambda.aspnetcoreserver/5.3.0/lib/netcoreapp3.1/Amazon.Lambda.AspNetCoreServer.dll" -out "/tmp/qjzash35.qtm/Amazon.Lambda.AspNetCoreServer_5.3.0/runtimopt/Amazon.Lambda.AspNetCoreServer.dll" -jitpath "/home/wooderz/.nuget/packages/microsoft.netcore.app.runtime.linux-x64/3.1.11/runtimes/linux-x64/native/libclrjit.so" -platform_assemblies_paths "/tmp/qjzash35.qtm/Amazon.Lambda.AspNetCoreServer_5.3.0/runtimeref:/tmp/qjzash35.qtm/Optimize/netcoreapp"" exited with code 33. [/home/wooderz/Development/Luminescence/Api/PackageManifest.xml]
```

If I skip optimization it seems to work, but the point is I'm trying to build a pre-jitted store, so skipping optimization is not a resolution here.

I've tried to search what code 33 is, but with no luck.

**Comment by marcpopMSFT** [comment]
@agocke crossgen related.  Where should we route these?

**Comment by agocke** [comment]
@mangod9 Thoughts?

**Comment by mangod9** [comment]
moving runtime repo with `label:area-ReadyToRun-coreclr` should be the right categorization for this, though we will need more context on how store calls into crossgen

**Comment by jameswoodley** [comment]
Morning, to give a little more context, I went through my dependency tree and a few of the MS packages were no longer supporting netcoreapp3.1 - I went through and downgraded them so they still supported and this started working. Seems either cross-gen can't go across frameworks, or there were breaking changes in some of the MS packages

**Comment by mangod9** [comment]
Ok, thanks for the update. Is it ok to close this for now?

**Comment by jameswoodley** [comment]
I guess.. I can't imagine I'll be the only one to come across this, but I suppose the packages do use semver so a breaking change was to be expected.

Have closed
