### ISSUE TITLE
How can you test multiple netstandard targets?

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1561]
_From @JamesNK on April 6, 2017 21:21_

In Json.NET I have a netstandard1.0 and 1.3 targets. I want to test them individually.

My test project has a netcoreapp1.1 target that depends on the library and automatically pulls in netstandard1.3, allowing me to test that target.

How can I then test the netstandard1.0 target of Json.NET from the same test csproj?

_Copied from original issue: dotnet/project-system#1938_

**Comment by davkean** [comment]
_From @srivatsn on April 7, 2017 7:23_

This issue was moved to Microsoft/vstest#697

**Comment by davkean** [comment]
_From @JamesNK on April 7, 2017 8:7_

Slow your roll before throwing it over the fence, this involves the project system.

Some barriers off the top of my head:

- If I want to test netstandard1.0 and 1.3 I can't have two netcoreapp1.1 targets in the test project?
- Also how do I explicitly tell the test project which target from a dependency to use? I want to explicitly say that this test target to use netstandard1.0 target of Json.NET, not a target of my library considered the best match.

**Comment by davkean** [comment]
_From @Nirmal4G on April 15, 2017 18:48_

Me too, I have the same problem. I was using generated assemblies manually, but there must be a better way to do this, If so then how do I do this?

**Comment by davkean** [comment]
_From @srivatsn on April 15, 2017 23:36_

@JamesNK missed seeing your last comment - you're right. I misread your question and this does involve work between project system and the SDK. Some of this support is already there. For your second bullet, you can set metadata on the ProjectReference to force msbuild to pick a particular TFM instead of it making a decision based on compatibility.

As for having two netcoreapp1.1 targets, you don't want it to be just `netcoreapp1.1;netcoreapp1.1` because then you can't distinguish between them in the project file for conditions. So ideally you'd want something like this to make this work:

```xml
  <PropertyGroup>    
    <TargetFrameworks>testingnetstandard1.0;testingnetstandard1.3</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'testingnetstandard1.0'">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v1.1</TargetFrameworkVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'testingnetstandard1.3'">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v1.1</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'testingnetstandard1.0'">
    <ProjectReference Include="..\ClassLibrary4\ClassLibrary4.csproj">
      <SetTargetFramework>TargetFramework=netstandard1.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'testingnetstandard1.3'">
    <ProjectReference Include="..\ClassLibrary4\ClassLibrary4.csproj">
      <SetTargetFramework>TargetFramework=netstandard1.3</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
```

This doesn't work today though because NuGet uses the TargetFramework property to restore instead of the TargetFrameworkMoniker property which is the canonical name that everything in VS uses. #615 tracks fixing that issue. Once that's fixed the above snippet should work.  For now you can make the test project target netcoreapp1.1;netcoreapp1.0 and have the two conditional project references and I verified that works.

**Comment by davkean** [comment]
_From @srivatsn on April 15, 2017 23:41_

@nguerrera @dsplaisted - why does the syntax for SetTargetFramework require name=value? I first tried just `<SetTargetFramework>netstandard1.0</SetTargetFramework>` and that fails because we are passing this value directly as the `Properties` argument to the `MSBuild` task. Shouldn't we be passing TargetFramework=<SetTargetFramework's Value>?

Also /cc @emgarten and @dotnet/vstest

**Comment by davkean** [comment]
_From @nguerrera on April 17, 2017 17:30_

`%(SetTargetFramework) `is what normally comes back from the GetTargetFrameworkProperties and we allow you to pick your own set of properties and not runt the target. It is similar to %(SetConfiguration) and %(SetPlatform) which are key=value sets and they are chosen by AssignProjectConfigurations target.  The ability to honor existing metadata was a late change in v1.0 an escape hatch. I considered friendlier syntax, but figured we could design that separately and use a better name after v1. I think the friendlier syntax for this should be  `<Project Include="x.csproj" TargetFramework="net45" />`. 

I think that reads nicest, but would there be a possible conflict with the `<TargetFramework>` sniffing of project system selector?

**Comment by livarcocc** [comment]
@nguerrera is this issue now tracking the new syntax to set the TFM for a project reference? Or is it tracking something else?

**Comment by Nirmal4G** [comment]
Is the related issue #1416 tracking this?
