### ISSUE TITLE
With .NET 6 SDK, Create mstest in CLI ,the template name Contains “Core”

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#15612]
Repro steps:
Install .NET 6 SDK6.0.100-preview.1.21081.5(6.0.0-preview.1.21079.7) from https://github.com/dotnet/installer--Release/6.0.1xx-preview1 branch
Run "dotnet new mstest"  in CLI .

Expected Result:
mstest should be created successfully and template name not contains "Core"

 

Actual Result:
mstest created successfully but template name contains "Core"
![image](https://user-images.githubusercontent.com/65637796/106572127-02598e00-6573-11eb-83da-d9536e81258a.png)

 

Note:
1.this issue not report with nunit/xunit

**Comment by pavelhorak** [comment]
@Sanan07 can you take care of this? You need to remove "Core" from .NET 6 templates in https://github.com/dotnet/test-templates

**Comment by Sanan07** [comment]
I will fix it. Issue exists in xUnit/NUnit as well but for other languages. To see it you need to change VS language in settings, so I will fix for all test templates.

**Comment by vdanche** [comment]
Fixed on 6.0.100-preview.3.21123.4(runtime-6.0.0-preview.2.21118.6)
![image](https://user-images.githubusercontent.com/65637796/108973094-f159f380-76be-11eb-837c-56eb839cfa53.png)
