### ISSUE TITLE
dotnet build run into 429 and ignore Retry-After Header

### ISSUE THREAD

**Issue by fotto1** [dotnet/sdk#15619]
We using for our project docker image mcr.microsoft.com/dotnet/core/sdk:3.1 with digest mcr.microsoft.com/dotnet/core/sdk@sha256:0fece15a102530aa2dad9d247bc0d05db6790917696377fc56a8465604ef1aff to run dotnet cli.

Our nuget packages are stored on an gitlab package manager version 13.8

After there are to many http request nuget receives 429 following RFC6585 with Retry-After Header in Response like described in https://tools.ietf.org/html/rfc6585#section-4

Instead of do a retry later `dotnet build` continue with download next packages and exit with 1 after third download fails with 429

```logs
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://SERVER_URL/api/v4/projects/PROJECT_ID/packages/nuget/download/microsoft.extensions.configuration.binder/index.json'.
  Response status code does not indicate success: 429 (Too Many Requests).
  Retrying 'FindPackagesByIdAsync' for source 'https://SERVER_URL/api/v4/projects/PROJECT_ID/packages/nuget/download/microsoft.extensions.configuration.binder/index.json'.
  Response status code does not indicate success: 429 (Too Many Requests).
  Retrying 'FindPackagesByIdAsync' for source 'https://SERVER_URL/api/v4/projects/PROJECT_ID/packages/nuget/download/microsoft.extensions.configuration.environmentvariables/index.json'.
  Response status code does not indicate success: 429 (Too Many Requests).
```

Can you please check how 429 is handled in `dotnet build` in case nuget is configured

**Comment by marcpopMSFT** [comment]
This issue was moved to NuGet/Home#10558
