### ISSUE TITLE
Error "the current SDK package for .NET does not support the target object .NET Core 6.0"

### ISSUE THREAD

**Issue by it19862** [dotnet/sdk#15610]
**Error:** 
_the current SDK package for .NET does not support the target object .NET Core 6.0. Select .NET Core 5.0 or earlier, or use the version of the .NET SDK that supports .NET Core 6.0._

**Question:** How to fix the error?

![2021-02-02_09-58-45](https://user-images.githubusercontent.com/18245828/106564008-b50ef980-653d-11eb-9c64-23c306a4de1c.png)

**Comment by marcpopMSFT** [comment]
What version of VS are you using?  What version of the .NET SDK are you using (run `dotnet --info`)?  What TargetFramework does your project target?  From the error, it looks like you're targeting net6.0 in your project but using an older SDK in VS (do you have preview SDKs enabled in the VS Tools->Options menu)?

**Comment by marcpopMSFT** [comment]
Closing for no reply.  Reopen if this is still an issue.

**Comment by StingyJack** [comment]
@marcpopMSFT - I think I am getting the same message. I cloned the repo and opened the solution and tried to build the Cli.Sln.Internal project 

I get a sea of errors that are almost all like this...
```
NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	Microsoft.DotNet.Cli.Sln.Internal	C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141	
```
VS 16.9.2  and I dont have NET6.0 installed AFAIK. 
![image](https://user-images.githubusercontent.com/15381181/112773996-35b21980-9006-11eb-9919-03bebc6289a8.png)

The only thing I've installed that was a preview was VS 16.10. 
I tried running `dotnet build sdk.sln` and it also fails.  I only have this issue with this repo, all my other stuff works fine.
![image](https://user-images.githubusercontent.com/15381181/112773840-9856e580-9005-11eb-87d6-c69d2980784f.png)

**Comment by marcpopMSFT** [comment]
Do you have any projects in the solution that are targeting net6.0?  From the error, it looks like you're using the net 5 sdk but something in the solution is targeting net6.

**Comment by StingyJack** [comment]
I cloned _this repo_ and opened it in VS and tried to build one of the projects.

None of the projects were changed.

**Comment by marcpopMSFT** [comment]
Oh, the sdk repo itself?  We target 6.0 and so you'll need to build from the command line once to pull down the correct 6.0 SDK. You'll also have to enable preview SDKs under Environment -> Preview Features in Tools->Options in VS. I'll get the developer guide instructions updated to include the preview feature checkbox step as that's missing.

Instructions.
https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md#run-tests-in-visual-studio

**Comment by fandrei** [comment]
@marcpopMSFT I'm having the same problem when trying to build this repo from the command line. The .NET 6 preview is installed and I can create and build simple projects in VS using it. 
```
The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0
```
Version info:
```
dotnet.exe --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by fandrei** [comment]
PS it seems that this was happening due to the MSBuildSDKsPath environment variable that was pointing to `C:\Program Files\dotnet\sdk\5.0.200\Sdks`
When I removed this variable, this project builds successfully. However, I'm not sure that this removal doesn't break something else in a different place.

**Comment by f2calv** [comment]
Also if you have a `global.json` and have explicitly disabled preview releases at some point in the past and forgotten :)
```json
{
    "sdk": {
        "allowPrerelease": true
    }
}
```

**Comment by ozanyasindogan** [comment]
Hi, I targeted .net 6 with a .net 5 blazor wasm project. It compiled all well but when I try to publish "server" project to docker registry, I get the same error mentioned here. My dotnet --info:
`.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

Below is my Docker output:

`#15 [build  7/10] RUN dotnet restore "TTWasm/TTWasm.Server/TTWasm.Server.csproj"
#15 sha256:61f8ba16d824a1fc3c1188ba2bc52866759301551c62455645f6bab45489b32a
#15 1.127   Determining projects to restore...
#15 1.544 /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/src/TTWasm/TTWasm.Client/TTWasm.Client.csproj]
#15 1.544 /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/src/TTWasm/TTWasm.Server/TTWasm.Server.csproj]
#15 1.544 /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/src/TTWasm/TTWasm.Shared/TTWasm.Shared.csproj]
#15 ERROR: executor failed running [/bin/sh -c dotnet restore "TTWasm/TTWasm.Server/TTWasm.Server.csproj"]: exit code: 1
------
 > [build  7/10] RUN dotnet restore "TTWasm/TTWasm.Server/TTWasm.Server.csproj":
------
executor failed running [/bin/sh -c dotnet restore "TTWasm/TTWasm.Server/TTWasm.Server.csproj"]: exit code: 1
4>Build failed. Check the Output window for more details.
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========`

You can see that 3 projects built succesfully, they work without an issue but when I try to publish, it somehow hooks .net5 sdk
