### ISSUE TITLE
RootNamespace isn't sanitized

### ISSUE THREAD

**Issue by bricelam** [dotnet/sdk#1564]
*From @pranavkm on July 19, 2017 22:24*

1. Create a directory with a hyphen e.g. `ef-test`
2. cd `ef-test`. `dotnet new mvc -au Individual`
3. Run the `dbcontext scaffold ` command

Expected:
The root namespaces generated by scaffold sanitizes the project's root namespace like `dotnet new` does i.e. `namespace ef_test`

Actual:
The generated code includes `namespace ef-test` which fails to compile.

*Copied from original issue: aspnet/EntityFrameworkCore#9216*

**Comment by bricelam** [comment]
We just get the value of the `RootNamespace` MSBuild property. The SDK should probably sanitize this.

**Comment by livarcocc** [comment]
Seems reasonable, today, we just set it to the project name:
``
    <RootNamespace Condition=" '$(RootNamespace)' == '' ">$(MSBuildProjectName)</RootNamespace>
``

**Comment by bricelam** [comment]
We had another case reported where the directory name contained **spaces**.
