### ISSUE TITLE
dot add command seems to be ignoring the --source parameter

### ISSUE THREAD

**Issue by francisminu** [dotnet/sdk#15665]
Hi
I am trying to use below command in my .NET Framework 5.0 project:
'**dotnet add C:\........\TestProject.csproj package Test.Models --source C:\myfolder\testpackages\nupkgs**'

I am giving a local folder path as the source. This used to work until .NET core 3.1, but doesn't seem to be working now.

When I run this command, it does not look for the package in the local folder that I have specified, rather goes to the nexus repositories that I have configured as my package sources (before, via Visual Studio).

Meanwhile, if I manually add the Local package source via Visual Studio and then run the above command, it installs the specified package from the local folder.

Could you please let me know if there is something I am missing or doing incorrectly.

Thanks in Advance!

**Comment by sfoslund** [comment]
@francisminu what version of the SDK are you using? Can you provide the results of `dotnet --info`?

**Comment by francisminu** [comment]
Please find below the screenshot:
![image](https://user-images.githubusercontent.com/14043523/107284161-f6fadc80-6a22-11eb-84c4-66e6f560f52c.png)

Please let me know if you need any more information.

**Comment by sfoslund** [comment]
FYI @dominoFire

**Comment by francisminu** [comment]
Hi @dominoFire 
Could you please take a look as this is causing major issues in our case as we have a custom cli that was created to automate various processes and this is one of the steps which if not succeeded, doesn't serve the purpose of the CLI.

Thanks in advance!

**Comment by satishviswanathan** [comment]
I'm also facing the same issue. Any help on this is appreciated.

**Comment by dominoFire** [comment]
@francisminu @satishviswanathan Did you run restore before adding your package? When using `--source` parameter, it only uses that source to lookup and restore the package to add. It might be necessary to restore packages before adding the new package from local source.

I tested the command in 5.0.103 and found no issues. 

Could you please try your command with dotnet SDK 5.0.103 ?

If the error persists, could you please paste output with `NUGET_SHOW_STACK` environment variable set to `true`? See PowerShell command below:

```powershell
$env:NUGET_SHOW_STACK = 'true'
$basePkg = 'C:\basePackages\'
dotnet add C:\path\to\project\sample.csproj package BasePackage --source $basePkg --prerelease
```

Successful command should look like this (edited):

```text
  Determining projects to restore...
  Writing C:\Users\feaguila\AppData\Local\Temp\tmpEFD3.tmp
info : Adding PackageReference for package 'BasePackage' into project 'C:\path\to\sample\sample.csproj'.
info : Restoring packages for C:\path\to\sample\sample.csproj...
info : Package 'BasePackage' is compatible with all the specified frameworks in project 'C:\path\to\sample\sample.csproj'.
info : PackageReference for package 'BasePackage' version '1.0.2-requireTrueAndLicenseEmpty' added to file 'C:\path\to\sample\sample.csproj'.
info : Committing restore...
info : Generating MSBuild file C:\path\to\sample\obj\sample.csproj.nuget.g.props.
info : Generating MSBuild file C:\path\to\sample\obj\sample.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: C:\path\to\sample\obj\project.assets.json
log  : Restored C:\path\to\sample\sample.csproj (in 503 ms).
```

**Comment by francisminu** [comment]
`C:\Program Files\RabbitMQ Server\rabbitmq_server-3.6.10\sbin>dotnet add C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj package Receiving.Models --source C:\Project\SynapseModernization\2020\openapi-spec\models\csharp\Receiving.Models\nupkgs --prerelease
  Determining projects to restore...
  Writing C:\Users\mfrancis\AppData\Local\Temp\tmp6638.tmp
info : Adding PackageReference for package 'Receiving.Models' into project 'C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/receiving.models/index.json
info :   **CACHE http://repomanager.test.consul:9090/repository/test-group-nuget/FindPackagesById()?id='Receiving.Models'&semVerLevel=2.0.0**
info :   GET https://www.myget.org/F/opentelemetry/api/v3/registration1/receiving.models/index.json
info :   CACHE https://nexusabc/repository/test-nuget/FindPackagesById()?id='Receiving.Models'&semVerLevel=2.0.0
info :   **NotFound https://api.nuget.org/v3/registration5-gz-semver2/receiving.models/index.json 327ms**
info :   **NotFound https://www.myget.org/F/opentelemetry/api/v3/registration1/receiving.models/index.json 564ms**
info :   CACHE https://www.myget.org/F/opentelemetry/api/v2/FindPackagesById()?id='Receiving.Models'&semVerLevel=2.0.0
info : Restoring packages for C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj...
info : Package 'Receiving.Models' is compatible with all the specified frameworks in project 'C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj'.
info : PackageReference for package 'Receiving.Models' version '0.4.0' updated in file 'C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj'.
info : Committing restore...
info : Assets file has not changed. Skipping assets file writing. Path: C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\obj\project.assets.json
log  : Restored C:\Project\SynapseModernization\2020\wms-api\services\Receiving\src\Receiving.Api\Receiving.Api.csproj (in 1.81 sec).`
SHown above is the result I get when I run even with 5.0.103.
If you notice, it is actually looking for the package in some nexus repos that I have added via VIsual Studio as my package source, but not looking in the local folder. (mentioned in **BOLD** above)

**Comment by francisminu** [comment]
Hi @dominoFire 
I have been trying this again and it doesn't seem to work. I am getting the below error:
![image](https://user-images.githubusercontent.com/14043523/112506522-d9c46800-8d5b-11eb-901b-9ccae30f9274.png)

This is the command I am trying
dotnet add C:\Projects\wms-api\services\Shipping\src\Shipping.Api\Shipping.Api.csproj package Carriers.Models --source C:\\Projects\\openapi-spec\\models\\csharp\\Carriers.Models\\nupkgs\ --prerelease
It does not look in the above location I have mentioned, but only in the locations I have set as package sources.
I tried setting this local path as the package source via Visual Studio and still its not picking up
