### ISSUE TITLE
invoking dotnet in any way leaks .NET Host process instances that never terminate.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/sdk#15679]
Whenever I use ``dotnet`` in any way whether it is ``dotnet build``, ``dotnet restore``, ``dotnet run`` etc it seems to me when I look inside of task manager (after the process terminates) that it does not terminate the .NET Host processes too to free up the chance that msbuild tasks are in fact locked by it and so then when you try to rebuild, the build would then fail due to the leaked .NET Host process instance from the previous build.

I think this is a bug somewhere because I think ``dotnet`` should be responsible for cleaning up the ``.NET Host`` process('s) as well too when building after the build is complete.

**Comment by wli3** [comment]
This is by design. We have few build servers running after the build is done to have better performance. Like Roslyn and msbuild reusable node. You can use https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build-server command to shutdown them.

**Comment by AraHaan** [comment]
@wli3 why not use environment variables to opt out of the build server entirely?

**Comment by wli3** [comment]
@AraHaan this comment could you help you https://github.com/dotnet/sdk/issues/10288#issuecomment-770528616
