### ISSUE TITLE
Cannot run dotnet tool from folder containing multiple project files.

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/sdk#15697]
Reported at https://github.com/dotnet/format/issues/921

**Steps to reproduce:**
```
dotnet tool install -g dotnet-format
dotnet new console -o project-folder
cd project-folder
cp project-folder.csproj project-to-format.csproj
dotnet format project-to-format.csproj
```

**Expected outcome:**
dotnet-format is invoked and applies formatting to the project-to-format.csproj.

**Actual outcome:**
dotnet CLI prints the following error 'Specify which project file to use because this 'C:\project-folder' contains more than one project file.'

**Comment by marcpopMSFT** [comment]
Chet checked this earlier today and determine it was not still an issue so closing.
