### ISSUE TITLE
Explicit restore for self-contained app behaves differently than implicit restore

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#1570]
## Steps to reproduce
1. mkdir ExplicitRestore
1. cd ExplicitRestore
1. dotnet new console --no-restore
1. dotnet restore -r debian.8-x64
Inspect the obj/project.assets.json to see what version of Microsoft.NETCore.App is used - Microsoft.NETCore.App/2.0.0

1. mkdir ImplicitRestore
1. cd ImplicitRestore
1. dotnet new console --no-restore
1. dotnet build -r debian.8-x64
The build step fails - notice the version of Microsoft.NETCore.App being used - 
'''
/ImplicitRestore/ImplicitRestore.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.1)
/ImplicitRestore/ImplicitRestore.csproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 2.0.0 ]
'''

## Expected  behavior
I was expecting the two scenarios to behave the same.  Specifically I would expect them to be using the same version of Microsoft.NETCore.App - 2.0.1

## Actual behavior
Explicit restore uses Microsoft.NETCore.App 2.0.0 while the implicit restore uses 2.0.1.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.1-servicing-006955)

Product Information:
 Version:            2.0.1-servicing-006955
 Commit SHA-1 hash:  6734510020

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.1-servicing-006955/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.1
  Build    : 5eb2f9bd659ad2161a8e035ac4bccd8f892caa0a
```

**Comment by MichaelSimons** [comment]
This behavior appears to stem from 
https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L96
and
https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.RuntimeIdentifierInference.targets#L108

The explicit restore flow isn't considered 'self-contained' because the `RuntimeIdentifiers` property is used vs `RuntimeIdentifier`.  As a result the `ImplicitRuntimeFrameworkVersionForSelfContainedNetCoreApp2_0` is used whereas it is used in the implicit flow.

**Comment by MichaelSimons** [comment]
cc @livarcocc & @nguerrera

**Comment by nguerrera** [comment]
NOTE: We are opting not to bump implicit versions for self contained apps until we address this. 

cc @richlander @KathleenDollard

This should no longer repro with the steps above when https://github.com/dotnet/cli/pull/7632 is merged. Should we keep this open to track design changes to this or file something new?

**Comment by dknippel** [comment]
so is this issue resolved with a newer .NET Core SDK?  I downloaded the "latest" which installs as 2.1.300 - Preview (x64).  However, I am not able to publish anything when I set a runtime id of **debian.8-x86** or **debian-x86**.  Am I missing something on my dev box or is running a self-contained .NET Core app on a 32-bit Linux box (Debian Jessie) not supported?

**Comment by livarcocc** [comment]
32bit linux is not supported.

**Comment by dknippel** [comment]
ah, ic.  thanks for the update :-D

**Comment by dsplaisted** [comment]
This will be addressed by https://github.com/dotnet/cli/pull/8919.

You will get different versions of Microsoft.NETCore.App depending on whether your app is self-contained or not.  An error will be generated if there's a mismatch in the version selected between restore and build or publish.  The full design is here: https://github.com/dotnet/designs/pull/36
