### ISSUE TITLE
dotnet build with Microsoft.NETFramework.ReferenceAssemblies can't find 'Microsoft.VisualBasic.dll'

### ISSUE THREAD

**Issue by daveMueller** [dotnet/sdk#15712]
Hello,

I'm currently trying to build a Visual Basic project with target framework v4.7.2 via ```dotnet build``` on linux. As far as I know this should be possible when using the package ```Microsoft.NETFramework.ReferenceAssemblies``` as described [here](https://github.com/microsoft/dotnet/tree/master/releases/reference-assemblies#classic-style-project).
Nevertheless the build job is failing with ```vbc : error BC2017: could not find library 'Microsoft.VisualBasic.dll'```. I can't figure out what I'm doing wrong. The nuget package definitely contains the dll but the build on linux somehow doesn't find it.

To be precise, this is the PR where I'm facing this issue ([https://github.com/coverlet-coverage/coverlet/pull/1073](https://github.com/coverlet-coverage/coverlet/pull/1073)). I'm thankful for any help.

**Comment by marcpopMSFT** [comment]
We remember vaguely fixing something around VB a while back related to this. Please try again and let us know if it's still an issue. Not sure if building with the framework reference assemblies is supported on linux and we can dig into that if it's still an issue.
