### ISSUE TITLE
System.Xaml not found in .NET 5.0

### ISSUE THREAD

**Issue by tames307** [dotnet/sdk#15728]
I'm attempting to migrate some .NET Framework 4.7.2 projects to .NET 5.0 but it appears that System.Xaml is missing.  The projects will be use on multiple platforms so it must be net5.0 and not net5.0-windows.

I raised this issue on the Developer Community site and they redirected me here, even though the issue has nothing to do with WPF... they insist that XAML must be a WPF related thing.  I am merely using XAML to define an object graph, outside of the codebase, of a non-WPF object model.

Where can I find System.Xaml for .NET 5.0?

**Comment by marcpopMSFT** [comment]
Old issue triage:  @terrajobst @ericstj is this something that's even supported? System.xaml comes from the WD runtime so I wouldn't expect it to be available outside of windows and outside -windows targeting. Is there a separate nuget package they could use?

**Comment by ericstj** [comment]
Right there's no NuGet package for System.Xaml, nor cross-platform build.  See https://github.com/dotnet/wpf/issues/46
