### ISSUE TITLE
[ARM32]With .NET 6 Preview1, running application failed with error required library libhostfxr.so could not be found.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#15757]
Repro steps:
1. Prepare Ubuntu20.04 or Alpine 3.1.13 container on arm 32 
2. Install .NET 6 Preview1 with arm installer
3. New a console app and try to run it

Expected Result:
1. App could be run successfully

Actual Result:
1. Running app failed with error required library libhostfxr.so could not be found.

```
root@9873cb4531bb:~/c1# dotnet run
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/root/c1/bin/Debug/net6.0/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
```

```
Dotnet --info
root@9873cb4531bb:~/mytest# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.1.21106.4
 Commit:    d575ffd0dc

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-arm
 Base Path:   /root/mytest/sdk/6.0.100-preview.1.21106.4/

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  6.0.100-preview.1.21106.4 [/root/mytest/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [/root/mytest/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [/root/mytest/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by dsplaisted** [comment]
@tommcdon Can you find someone to investigate this ARM32 issue?

**Comment by tommcdon** [comment]
@agocke

**Comment by agocke** [comment]
@sbomer Could you take a look? I'm not sure where we found an ARM32 machine last time

**Comment by sbomer** [comment]
The app works on ARM32 if you manually set `DOTNET_ROOT`. The issue is that the `dotnet run` command is setting the wrong env var on non-64bit linux:
https://github.com/dotnet/sdk/blob/8ab6678895ae6991bbf6114ec5c4a67a4395e0a0/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L259

The host uses `DOTNET_ROOT` for everything but wow64:
https://github.com/dotnet/runtime/blob/4c79d45edd899133cf6d36dc9b4de122ceca72cf/src/native/corehost/hostmisc/utils.cpp#L353-L358

**Comment by sbomer** [comment]
I confirmed that this also repros in .NET 5.

**Comment by WenJunJi01** [comment]
Not repro with .NET 6 RC2 SDK: 6.0.100-rc.2.21458.9(runtime-6.0.0-rc.2.21457.6) from https://github.com/dotnet/installer

**Comment by returnlog** [comment]
.NET 5.0.402 still this error. Any solutions, please?
