### ISSUE TITLE
DuplicatePublishOutputFiles error should show what is duplicated

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#15751]
Task CheckForDuplicateItemMetadata should show what is duplicated. So we can save time for the user of the investigation

**Comment by sfoslund** [comment]
@wli3 the task already does output the duplicated files: 
<img width="740" alt="DupItemMetadata" src="https://user-images.githubusercontent.com/16010855/107398455-7b497000-6ab4-11eb-8327-8cbd82a944ad.PNG">

Then the resulting error is: 
error NETSDK1148: Found multiple publish output files with the same relative path: C:\Users\user\.nuget\packages\microsoft.netcore.app.runtime.win-x86\6.0.0-preview.1.21102.12\runtimes\win-x86\native\API-MS-Win-core-xstate-l2-1-0.dll, C:\Users\user\.nuget\packages\runtime.win7-x86.microsoft.netcore.windows.apisets\1.0.1\runtimes\win7-x86\native\api-ms-win-core-xstate-l2-1-0.dll.

**Comment by wli3** [comment]
Hmm. Looks like the bug reporter did not include everything. Sorry about that.
