### ISSUE TITLE
Problem publishing project to folder 

### ISSUE THREAD

**Issue by seb999** [dotnet/sdk#1576]
I try to publish my project using VS2017 15.3 and cannot get the Views published as well.

To explicitly tell VS to add the views I added the following code in the .csproj file:

 `  <ItemGroup>
    <Content Include="Views\**\*" CopyToOutputDirectory="Always" />
  </ItemGroup>`

I get a publishing error:

Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Views\Activity\ActivityDetail.cshtml'; 'Views\Activity\Index.cshtml'; 'Views\Admin\Index.cshtml'; 'Views\Awp\Index.cshtml'; 'Views\BudgetTransfer\Basket.cshtml'; 'Views\BudgetTransfer\Index.cshtml'; 'Views\DashboardLogs\Index.cshtml'; 'Views\Dashboard\Index.cshtml'; 'Views\Home\About.cshtml'; 
etc......................

My last try was to skip VS and type dotnet publish from a command windows.
This time I get an empty Views folder.

Here is my complete .csproj
`
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Views\**\*" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreCompat.System.Drawing.v2" Version="5.2.0-preview1-r131" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Serilog" Version="2.5.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.ColoredConsole" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServerCore" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ECDC.MVC.DATA\ECDC.MVC.DATA.csproj" />
  </ItemGroup>
`

**Comment by pranavkm** [comment]
Mvc Precompilation typically disables publishing views since they are already precompiled. You can continue publishing views, by 

(a) turning off precompilation `<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>`
(b) keeping precompilation on and continuing to publish views `<MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>`

See https://github.com/aspnet/MvcPrecompilation#options for more details.

**Comment by seb999** [comment]
Thanks, I didn't realize about this pre-compiled views. Actually now that you mention that, I managed to publish a project on a Amazon EC2 server. It works well.

So something is wrong at work when I publish my project on a Windows 2012 server. If I copy/paste the Views folder then it works fine. It should also works with pre-compile Views.

**Comment by pranavkm** [comment]
Could you file a bug in https://github.com/aspnet/MvcPrecompilation with some details about your project? Seems odd that it works in one case and not the not the other.

**Comment by seb999** [comment]
Hey Pranav, problem solved. I installed the Windows Server Hosting (x86/x64) runtime package instead of the Windows (x64) Installer package.
Thanks for your contribution. It was really helpfull to identity the problem here.
