### ISSUE TITLE
[sdk 6.0.100-preview.1.21107.2-win-x64] dotnet tool fail due to argument passed to the tool.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/sdk#15767]
The cli tries to parse the '-v' argument that is passed to the tool, previously the cli ignored this argument.
```
25>System.InvalidOperationException: Cannot parse argument 'Release' as expected type Microsoft.DotNet.Cli.VerbosityOptions.
25>   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
25>   at System.CommandLine.Parsing.OptionResultExtensions.GetValueOrDefault[T](OptionResult optionResult)
25>   at System.CommandLine.Parsing.ParseResult.ValueForOption[T](String alias)
25>   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
25>   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
25>   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
25>   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
25>   at Microsoft.DotNet.Cli.Program.Main(String[] args)
25>C:\dev\Opal\CKSetup\CKSetup.csproj(12,5): error MSB3073: The command "dotnet cksetup run CKSetup.xml -v Release --logFile LastRun.log" exited with code 1.
```
I believe this is a regression from .NET 5.

**Comment by dsplaisted** [comment]
@sfoslund This looks like an issue with the new command line parser

**Comment by GlebChili** [comment]
It seems like I've also encountered an issue with `dotnet tool` argument parsing: #15961.
Sorry in advance if my assumption that the issues are related is wrong.

**Comment by sfoslund** [comment]
> C:\dev\Opal\CKSetup\CKSetup.csproj(12,5): error MSB3073: The command "dotnet cksetup run CKSetup.xml -v Release --logFile LastRun.log" exited with code 1.

@Kuinox I believe this is a problem with the way you're attempting to run the tool, if the tool has been installed globally and does not have the `dotnet-` prefix in the name you don't have to specify `dotnet` before your command. "cksetup run CKSetup.xml -v Release --logFile LastRun.log" seems to work fine for me.

**Comment by Kuinox** [comment]
Mhhh, the command effectively looks weird, but I did hit this issue only after upgrading to a .NET 6 CI build.  
This command is probably working in .NET 5.

**Comment by Kuinox** [comment]
Ok, this is a bit special.
This is both a global tool and a local tool.  
There is a dotnet-tools.json in this project that specifies a version for this project.
And you can call a local tool with `dotnet toolName`.

**Comment by sfoslund** [comment]
Oh I see, it's not reproducing for me when run globally but it does locally. It does seem to be a parser issue, I'll look into this.
