### ISSUE TITLE
.NET 5.0+ shouldn't have "Core" suffix in error messages

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/sdk#15813]
See 

![image](https://user-images.githubusercontent.com/31348972/107652368-2d399580-6c89-11eb-87da-65a30f4a7c1d.png)

## Actual behavior

> NETSDK1045: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0.

## Expected behavior

> NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/14449
