### ISSUE TITLE
Q: check public API changes as part of the build

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#15812]
Some of the dotnet repos check for public API changes as part of the build.

I haven't tried figuring out how it works.

Is this tooling available, and can it be used for C# library projects?

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
This is accomplished via [ApiCompat](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat) which is used in the runtime libraries build. @safern is working on productizing ApiCompat: https://github.com/dotnet/designs/pull/177

**Comment by tmds** [comment]
Thanks @ViktorHofer !
