### ISSUE TITLE
`dotnet watch run` supports applying code changes to a running app via Hot Reload

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#15849]
### User Story
As a user, when using `dotnet watch run` during a development session, I want compatible code changes applied to my running application via the Hot Reload mechanism, so that I can see their impact as quick as possible without losing the current application state.

### Considerations
- This capability should apply at a fundamental level to all project/application types (i.e. workloads) supported by the CLI
- Specific workloads should be prioritized to ensure their experience with Hot Reload can be optimized as necessary:
  - ASP.NET Core & Blazor Server (P0)
  - Blazor WebAssembly (P0)
  - *Note other workload type optimizations including MAUI are still TBD*
- This capability should be supported as appropriate on the following operating systems, runtimes, and platforms:
  - Windows (x86, x64)
  - macOS (x64, ARM64)
  - Linux (x64, ARM64)
  - Core CLR/Mono/WebAssembly (workload dependent)
- The various runtimes in play (Core CLR, Mono, WebAssembly) will each support the concept of Hot Reload but may differ in regard to which code changes are supported, the underlying mechanism used to apply the changes, etc. The experience should be tailored as appropriate for this to ensure a good user experience.

**Comment by pirunxi** [comment]
Hot Reload is used in develop environment cucrrrently,but we eagerly need a resolusion for  hot reloading to fix bugs of game server apps in production enviroment. Will it support this forture?

**Comment by DamianEdwards** [comment]
@pirunxi this feature is specifically scoped to development-time scenarios only. Patching fixes into running applications in production scenarios may be possible today via custom use of the `AssemblyLoadContext` API but this scenario would be better discussed/logged in the dotnet/runtime repo.

**Comment by pranavkm** [comment]
@DamianEdwards closing this, since an initial version of this feature is done and shipping as part of 6.0-preview3.
