### ISSUE TITLE
Change the default for all SDK-based projects (including Web SDK) to include DebugSymbols in the project file for Release builds

### ISSUE THREAD

**Issue by tzwlai** [dotnet/sdk#1588]
DebugSymbols translates to "debug+ optimize+", which disables variable removal but leave other kinds of IL optimizations enabled.

**Comment by livarcocc** [comment]
@tmat can you comment on this?

**Comment by livarcocc** [comment]
@nguerrera can you take a look and see if this is straight forward?

**Comment by nguerrera** [comment]
It is straight-forward. If @jaredpar gives me the go-ahead, I'll submit a PR.

**Comment by jaredpar** [comment]
This seems like it is asking for us to use `/debug+` for release builds by default. Is that correct? 

If so we definitely should not do this. The resulting binaries are demonstrably less efficient.

**Comment by nguerrera** [comment]
The proposal is  `/debug+ /optimize+`, which I understand to match debugFriendly=true here:

https://github.com/dotnet/roslyn/blob/4d2a51a32803e9c5bb49187b765a9d983b843db8/src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs#L24-L45

Am I reading the code right? If so, the assertion on that long offline thread is that skipping those optimizations makes the IL bigger but doesn't degrade the native code gen. Is that wrong?

**Comment by livarcocc** [comment]
I believe this change ended up being made in the Web SDK. Is this still needed for the SDK? If not, I would like to close this issue.

**Comment by tzwlai** [comment]
Thanks for checking.  We don't need this anymore.  Please go ahead and close this issue.
