### ISSUE TITLE
Determine trimming defaults for different application types

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#15906]
For .NET 6.0 we need to determine what configuration we offer and recommend for trimming, as well as the default setting for different application types.

The settings we need to determine are:

- [x] Is trimming `copyused` or `link` by default? (https://github.com/dotnet/sdk/issues/15905)
- [x] When are trim warnings enabled by default?
  - [x] Full application trimming for Xamarin?
  - [x] Blazor?
  - [x] Whenever `link` trimming is enabled?
  - [x] Whenever trimming is enabled at all?
 - [x] Are any of the previous settings contingent on new features, e.g. a better UX for library trim analysis?
 - [x] Should the Visual Studio UI be treated differently from `/p:PublishTrimmed=true`?

**Comment by agocke** [comment]
cc @vitek-karas @sbomer @eerhardt

**Comment by eerhardt** [comment]
FYI @samsp-msft
