### ISSUE TITLE
Net core compilation fails with files generated during prebuild tasks

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1593]
_From @EPinci on September 18, 2017 22:32_

Hello,

I have a .Net Core project with a prebuild task that generate a class file (.cs) needed during the actual compilation. Since this class is generated on a per build basis, it is also excluded from source control so is that is absent on repository clones.

Problem is that:
- during the first attempt the build fails not finding that class although the pre build task generated it successfully.
- Following builds run fine.
- Deleting the file, show the first build problem again.

I tried explicitly including the class file in the project but the behavior is reversed for now I get a "Duplicate 'Compile' items were included." error in the "following" builds.

**Now this breaks CI/CD scenarios**: in a case I fail on build, in the other I fail on publishing.
This behavior does not happen on full framework project that do not have default globs enabled.

Looks like the dotnet build command enumerates the files to build before the pre build task and not after. Is this a bug?
Is there a way to allow this scenario without disabling globs?

Thank you.

_Copied from original issue: dotnet/project-system#2839_

**Comment by davkean** [comment]
Globs (*.cs) are calculated during evaluation time, in particular during lazy item evaluation. The phases in a build look like this:

1. Evaluation
      1.1 Properties
      1.2 ItemDefinitionGroup
      1.3 Items
      1.3.1 Lazy Items
      1.4 UsingTasks (conditions)
      1.5 Targets (conditions)

2. Targets

You are generating the file during Targets in a location that expects to be picked up a phase earlier. Generating files during targets is allowed, they should be just generated in a location that isn't picked up by globs, ie intermediates, and must be explicitly included in the project. This is exactly what we do with the generated Assemblyinfo.cs, XAML, and other generated files.

**Comment by sharwell** [comment]
@EPinci If you can include a copy of your project file and/or .props/.targets modifications used to implement your code generation step, we can provide additional guidance. The main item to ensure for now is the generated files are placed under the intermediate output directory, which by default has a form similar to **obj\\Debug\\netstandard1.3**.

**Comment by EPinci** [comment]
Hey!

My project file (netstandard2.0 library) is actually very minimal: a bunch of package and project references, the pre build task as follows:
  `<Target Name="PreBuild" BeforeTargets="PreBuildEvent">`
    `<Exec Command="CALL $(SolutionDir)gitversioninfo.bat [bunchofparameters]" />`
  `</Target>`
And the explicit inclusion of the generated class.

With @davkean comment I was able to sort out the problem: I basically moved my generated class out of the project directory and explictly included.

Now the only weird thing is that the prebuild task is fired also when running a dotnet publish, thing that I did not expect. Can you comment on why this is happening and if there a way to control it?

Thank you! :)

**Comment by davkean** [comment]
@EPinci As per https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#designing-targets-for-use-in-design-time-builds, if you are producing source files you must run during the design-time build. Your BeforeTargets should be "Compile".

As to why PreBuild runs during publish, I'm not sure - I would file a different item for that.

**Comment by dasMulli** [comment]
For targets that generate code files, I found the sdk's assembly info generation logic and comment very useful:

https://github.com/dotnet/sdk/blob/a42a32034c94ebb145985ffeaaf73cd7f4d50396/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets#L39-L49

There is an issue about separating build and publish at https://github.com/dotnet/cli/issues/5331

**Comment by livarcocc** [comment]
It seems the issue here has been addressed. The right way to generate code and include it in your project.

Also, as @dasMulli noticed, we have a bug tracking adding the --no-build flag back to the publish command.

**Comment by voxon2** [comment]
I was not able to understand how to use the comments in this issue to include my build time generated sources files in the compile phase. (maybe someone can clarify)

I was able to get a working solution by using the solution described here: 

https://stackoverflow.com/questions/44818730/is-there-a-net-core-cli-pre-before-build-task

**Comment by itaibh** [comment]
I wasn't able to understand what's the correct way to generate files by scripts also. I'd welcome any clarification.
I used @voxon2 solution and it worked, but I'd rather do it correctly.
