### ISSUE TITLE
[Workloads] Consider making the manifest version to be a Semver

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#15942]
The spec expects the manifest version to be the same value as the NuGet that the package the manifest is transported in. Since NuGet supports semantic versioning (v2), it would follow that the manifest version field should also allow this. Currently it only allows for integer values.

**Comment by lewing** [comment]
I think this is fixed in https://github.com/dotnet/sdk/pull/16746

**Comment by sfoslund** [comment]
Yes, this should be fixed, closing.
