### ISSUE TITLE
Call to `dotnet --version` slower in .NET 6 Preview 1

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/sdk#15950]
There seems to have been a regression in the call to `dotnet --version` from .NET 5 to .NET 6. While not scientific, here are 6 runs on each SDK version. I am using [Spaceship prompt](https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/dotnet.zsh) and it is noticeable in my terminal experience.

## .NET 6 (6.0.100-preview.1.21103.13)

```
dotnet --version  0.14s user 0.07s system 94% cpu 0.229 total
dotnet --version  0.15s user 0.07s system 105% cpu 0.203 total
dotnet --version  0.14s user 0.07s system 104% cpu 0.201 total
dotnet --version  0.15s user 0.07s system 105% cpu 0.209 total
dotnet --version  0.14s user 0.07s system 105% cpu 0.198 total
dotnet --version  0.15s user 0.07s system 98% cpu 0.224 total
```

## .NET 5

```
dotnet --version  0.08s user 0.05s system 115% cpu 0.117 total
dotnet --version  0.09s user 0.05s system 115% cpu 0.122 total
dotnet --version  0.08s user 0.05s system 114% cpu 0.118 total
dotnet --version  0.08s user 0.05s system 114% cpu 0.119 total
dotnet --version  0.08s user 0.05s system 115% cpu 0.114 total
dotnet --version  0.09s user 0.05s system 114% cpu 0.121 total
```

**Comment by sfoslund** [comment]
Thanks for filing an issue. This is a known issue with preview 1, it should be significantly improved with preview 2 (fixed by https://github.com/dotnet/sdk/pull/15499). Please feel free to reopen if the problem continues past preview 1.
