### ISSUE TITLE
VS 2017 multi-targeting conditional build

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/sdk#1597]
VS 2017 (15.3.5) build does not work correctly with new csproj that have conditional `<TargetFrameworks>` tag. Example [ConsoleSample.zip](https://github.com/dotnet/sdk/files/1319216/ConsoleSample.zip):
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net461</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<Configurations>Debug;Release;Publish</Configurations>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Publish'">
		<TargetFrameworks>net461;netcoreapp2.0;netstandard2.0;net35</TargetFrameworks>
	</PropertyGroup>
</Project>
```
**Steps to reproduce:** build the project in VS as debug, switch the build configuration to Publish and try to build it again.

**Expected behavior:** builds without errors.

**Actual behavior:** build fails with following error message:
```
Assets file ...\ConsoleSample\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
```
**Reason:** the `obj\project.assets.json` contains only
```
  "targets": {
    ".NETFramework,Version=v4.6.1": {},
    ".NETFramework,Version=v4.6.1/win7-x86": {}
  },
```
Solution clean and deletion of bin/obj folders does not help, the build keeps failing. Console build
```
msbuild ConsoleSample.csproj /p:Configuration=Publish /t:Restore;Build
```
fails with same error.

The issue is a huge blocker for us as it prevents us from migration to the new project system. 
Currently we use custom msbuild scripts for multitargeting builds and it doesn't work well, as there is no VS support.

Any viable workarounds are welcome.

**Comment by ig-sinicyn** [comment]
Up? I'm really interested in solution.

**Comment by dasMulli** [comment]
Looks similar to https://github.com/NuGet/Home/issues/4996 - configuration changes don’t cause NuGet to restore for that configuration within VS

**Comment by livarcocc** [comment]
Closing as this has been addressed in the new project system: https://github.com/dotnet/project-system/issues/1542.
