### ISSUE TITLE
GenerateDocumentationFile=true breaks DebugSymbolsProjectOutputGroup in VB projects

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1598]
Get the following when trying to replace `<DocumentationFile>Foo.xml</DocumentationFile>` with `<GenerateDocumentionFile>true</GenerateDocumentationFile>`.

```
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(5458,44): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "D:\Src\roslyn\Binaries\Obj\BasicEditorFeatures\Debug\D:\Src\roslyn\Binaries\Obj\BasicEditorFeatures\Debug\Microsoft.CodeAnalysis.VisualBasic.EditorFeatures.xml". The given path's format is not supported. [D:\Src\roslyn\src\EditorFeatures\VisualBasic\BasicEditorFeatures.vbproj]
```

The issue is that VB targets do not expect DocumentationFile to include the IntermediateOutputPath like C# targets, so GenerateDocumentationFile needs to behave differently for VB than C#.

**Comment by dasMulli** [comment]
Does this happen with "standard" sdk-based libraries as well or just in the roslyn solution? Tried to repro with an empty vb lib but debug and documentation output groups look kinda fine..

**Comment by nguerrera** [comment]
Hmm, I only saw it in Roslyn and assumed from code inspection that it generalized...

**Comment by dasMulli** [comment]
Ah no the documentation output group really is broken, the debut output group looks fine.

```
 testlib -> /Users/martin/tmp/testlib/bin/Release/netstandard2.0/testlib.dll
  DebugSymbolsProjectOutputGroupOutput: /Users/martin/tmp/testlib/obj/Release/netstandard2.0/testlib.pdb
  DocumentationProjectOutputGroupOutput: /Users/martin/tmp/testlib/obj/Release/netstandard2.0/obj/Release/netstandard2.0/testlib.xml
```
