### ISSUE TITLE
dotnet restore exit code reports success when actually failed

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/sdk#16031]
Repro is simple. Try to restore a package that doesnt exist:

```
aaronla@aaronla-rabbit:MyRepo$ dotnet restore
X:\MyRepo\dirs.proj : error : Unable to find package Microsoft.Build.Traversal with version (= 2.999.1)
X:\MyRepo\dirs.proj : error :   - Found 24 version(s) in MyCustomFeedOne [ Nearest version: 3.0.0 ]
X:\MyRepo\dirs.proj : error :   - Found 0 version(s) in MyCustomFeedTwo

aaronla@aaronla-rabbit:MyRepo$ echo %ERRORLEVEL%
0
```

expected: %ERRORLEVEL%==1

**Comment by aaronla-ms** [comment]
Additional repro details:
- OS: Windows 10 20H2 (OS Build 19042.802)
- dotnetsdk version: 3.1.406 (as reported by `dotnet --version`)
- all versions of dotnetsdk installed:
    ```
aaronla@aaronla-rabbit:MyRepo$ dotnet --list-sdks
1.1.14 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.514 [C:\Program Files\dotnet\sdk]
2.1.518 [C:\Program Files\dotnet\sdk]
2.1.521 [C:\Program Files\dotnet\sdk]
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.406 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
```

**Comment by wli3** [comment]
@Forgind @BenVillalobos @cdmihai Is nuget restore also part of "msbuild by design" return value is always 0?

**Comment by Forgind** [comment]
I don't think so. There are several references online to NuGet restore returning 1 like:
https://github.com/microsoft/azure-pipelines-tasks/issues/2747

It might be more subtle, though, like NuGet restore only returns 0 if everything is proper, even if it can't find the file, and 1 if there's an error that prevented it from finishing its search.

**Comment by aaronla-ms** [comment]
@Forgind this appears to be a problem with sdk references specifically. I confirmed that a PackageReference to non-existent package correctly results in exit code 1, but the same package referenced via Sdk results in an incorrect result of exit code 0

**Comment by aaronla-ms** [comment]
posted full self contained repro on the parallel thread, https://github.com/NuGet/Home/issues/10606

**Comment by aaronla-ms** [comment]
Recommend closing as dup of https://github.com/dotnet/msbuild/issues/6281

**Comment by Forgind** [comment]
16.10 preview 3 for MSBuild. I'm not sure which version exactly that corresponds to.

And I think you're right that it should be closed.
