### ISSUE TITLE
ResolveNuGetPackageAssets allocates 3.7% of solution-wide design-time build

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1605]
This is literally turning text -> text, can we do this without NewtonSoft.Json? Otherwise, try the lower level reader API that JSON.NET has?
![image](https://user-images.githubusercontent.com/1103906/30861318-ab9065ec-a30d-11e7-98ce-04584375a089.png)

**Comment by davkean** [comment]
Some of this allocations is due to reading line annotations - turn that off via JsonLoadSettings.LineInfoHandling.

**Comment by nguerrera** [comment]
This is the version of package resolution for non-SDK projects. cc @Pilchie Does this go in project-system or nuget?

**Comment by Pilchie** [comment]
project-system has tended to make the changes, but the code lives at https://github.com/NuGet/NuGet.BuildTasks/.

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#6755
