### ISSUE TITLE
CPS out of sync with Restore with larger solutions that haven't turned on LSL (lightweight solution restore)

### ISSUE THREAD

**Issue by mishra14** [dotnet/sdk#1607]
_From @rrelyea on January 17, 2017 20:12_

From @Srivatsn
please investigate to understand if this should be rc3 or rtm issue?
Opening Projectsystem.sln from https://github.com/srivatsn/roslyn-project-system/tree/dogfood/src

Show these errors in the package manager window:

Error occurred while restoring NuGet packages: The operation failed as details for project ProjectSystemDogfoodSetup could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed.TestServices.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project MSBuild could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Composition could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:05.8245080
========== Finished ==========

                

_Copied from original issue: NuGet/Home#4307_

**Comment by mishra14** [comment]
_From @rrelyea on January 24, 2017 18:32_

Will have to live with this, as it doesn't block the user. Need better fix for large projects.
People should use LSL for large solutions...and it will work better

**Comment by mishra14** [comment]
_From @rrelyea on February 8, 2017 21:38_

@dtivel was investigating #4474, got the customer solution, and ran into this same problem.

**Comment by mishra14** [comment]
_From @rrelyea on February 16, 2017 19:35_

Pulling back to 4.0rtm -- may consider fix...depending how much the fix for #4617 (statusbar logging, output loggging and warning/error logging) improves things.

**Comment by mishra14** [comment]
_From @rrelyea on February 17, 2017 1:50_

@jainaashish  - not sure we are taking, but please investigate RTM options on this one.

**Comment by mishra14** [comment]
_From @jainaashish on February 21, 2017 19:33_

Proposed solution:
Delay auto restore until we are expecting some nominations for .net core projects. This delay won’t be indefinite and would be capped by 10 secs so even after 10 secs delay, we still haven’t got all the nominations, we’ll continue with auto restore which will fails with the current error. During this delay UI won’t be freeze so user will still be able to carry out any other operation in VS. And this delay will also be in form of 2 secs so every 2 secs it will check if it has all the nominations then it will continue without further delay.

Also, note this delay will not impact other cases where either we already got all the nominations or there isn’t any .net core based project in solution. These scenarios will continue to work as is and will have no performance overhead because of this change.

**Comment by mishra14** [comment]
_From @davkean on February 23, 2017 3:55_

Hey, coordinate with us on this: https://github.com/dotnet/roslyn-project-system/issues/1600. We're nominating too late as it is.

**Comment by mishra14** [comment]
_From @jainaashish on February 23, 2017 18:19_

@davkean are you targeting your issue for RTM? since this is impacting auto restore performance big time so we need to get something done for RTM.

**Comment by mishra14** [comment]
_From @DoRonMotter on February 24, 2017 19:6_

Not expecting a NuGet change for RTM at this point, and will solve perf issues with improved logging.  @davkean ping back if you need a follow on change from NuGet for this for RTM.

**Comment by mishra14** [comment]
_From @jainaashish on March 13, 2017 18:50_

one more internal vsts bug# 387758

**Comment by mishra14** [comment]
_From @wizarrc on March 16, 2017 17:44_

I'm not sure if this is the same root bug, but I am having an error display while loading Package Management Console (PMC) prompt `PM>` when the solution is still loading. I receive the error 'The operation failed as details for project _insert project name_ could not be loaded.' preventing the prompt from displaying. I can work around it by closing the PMC window, restart vs and load the solution, wait for all projects to load, and open the PMC window again. Error occurs on VS 2017 RTM version up to date as of today with 'Lightweight solutions load for all solutions' checked or not.

**Update:** Also error is not affected by changing the solution setting 'Lightweight Load' to default, enabled, or disable. Originally set to default. Just discovered the setting after I posted.

**Comment by mishra14** [comment]
_From @rrelyea on June 28, 2017 0:49_

Out of time for 4.3

**Comment by mishra14** [comment]
_From @jainaashish on August 22, 2017 17:16_

This is still happening for some of the solutions where all the projects are not nominated even after delaying until 10 secs so re-opening this again. We'll coordinate with Project System to fix it with proper design.

**Comment by mishra14** [comment]
_From @jainaashish on August 31, 2017 17:31_

Bringing this into 4.4 we have to get the right design in place to fix it once and for all. It impacts other scenarios as well like Test Explorer not able to discover tests on solution load since project is being nominated late.

**Comment by mishra14** [comment]
Moving this over from NuGet.

cc: @rrelyea @jainaashish @emgarten @davkean

**Comment by livarcocc** [comment]
@mishra14 did you mean to move this bug to dotnet/projectsystem?

**Comment by mishra14** [comment]
@livarcocc This issue is specifically for nomination synchronization, which is net core only scenario. Why do you feel it should be moved to dotnet/projectsystem?

**Comment by emgarten** [comment]
@mishra14 nominations are sent by the project system. I believe there is an issue for this already there.

**Comment by mikeharder** [comment]
@livarcocc, @emgarten: What is the latest on this issue?  It's still impacting our large solutions in the latest builds of VS and CLI.

**Comment by livarcocc** [comment]
@Pilchie Should I move this to the project system? This seems like a nomination synchronization problem.

**Comment by jainaashish** [comment]
Here is corresponding Project-system bug# https://github.com/dotnet/project-system/issues/1600

**Comment by davkean** [comment]
We can dup this against: https://github.com/dotnet/project-system/issues/1600.

**Comment by davkean** [comment]
@mikeharder Can you help me understand what you mean by "impacting"? These errors can ignored in most cases - do you think it's the cause of other issues?

**Comment by mikeharder** [comment]
By "impact" I just mean it's still happening.  Even if the warnings can be ignored it's a bad customer experience.  If the warnings have no other impact maybe we should just stop showing them?

**Comment by davkean** [comment]
Don't disagree on the bad customer experience, just trying to prioritize wanted to make sure there wasn't more information that would have moved this forward.

**Comment by mikeharder** [comment]
@davkean: When this error message is printed, does it mean part of the restore failed so the customer needs to restore again to fix things?  Or did everything restore successfully despite the error?

**Comment by davkean** [comment]
Restore will successfully finish despite the error.

**Comment by mikeharder** [comment]
Then would an easy fix be to just suppress the error?

**Comment by jainaashish** [comment]
There will be multiple instance of restores (one for each nomination) and the last restore will successfully finish. It wouldn't be that easy to suppress these errors since then you need to know that there will be a next restore.

**Comment by davkean** [comment]
NuGet would need to know that we had a pending design-time that when finished would result in us in nominating, agreed not a quick easy fix - other than removing the error completely and not notifying when there is a real issue. But in that case, agreed not sure what the user can do about this error anyway?
