### ISSUE TITLE
NETStandard.Library 2.0.2 should be picked up in SDK servicing

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1608]
/cc @livarcocc @dsplaisted

**Comment by livarcocc** [comment]
@ericstj what version of the SDK should carry that? What is the official release date for the package?

**Comment by ericstj** [comment]
Probably next available?  @leecow or others running .NET Core shiproom should be able to help coordinate.

**Comment by dsplaisted** [comment]
This issue was moved to dotnet/cli#8956
