### ISSUE TITLE
Passing program arguments with dotnet run fails with the option -d (6.0.100-preview.1.21103.13)

### ISSUE THREAD

**Issue by christiannagel** [dotnet/sdk#16120]
Passing command line arguments to the application with  **dotnet run** doesn't show an argument passed if the argument **-d** is passed.

Application with top-level statements:
```csharp
System.Console.WriteLine($"length: {args.Length}");
```

Project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
```

Running the application with

`dotnet run -- -a`

is as expected. Using 

`dotnet run -- -d`

give this argument count: 0.

The issue happens when this SDK is used (on Windows):
6.0.100-preview.1.21103.13

Creating a `global.json` file and set the version number to 5.0.103, the program runs as expected.

I'm running Windows 10, build 21322.1000

**Comment by christiannagel** [comment]
Just verified - the bug is still active with the SDK build 6.0.100-preview.2.21155.3. 
The issue occurs only when passing "-d", all other arguments are as expected.

**Comment by christiannagel** [comment]
Using preview 3, this bug seems to be fixed. Now you can pass the option *-d* to the program arguments again.

**Comment by natemcmaster** [comment]
One of my users is reporting this problem still with preview4. https://github.com/natemcmaster/dotnet-serve/issues/89

It appears to me to be a regression since .NET 5. The CLI is eating up the `-d` parameter before calling subcommands.

## Before: with .NET 5 and before
`dotnet serve -d ./folder` worked just fine.

## Now: .NET 6 preview 4
The "dotnet" command removes the `-d` arg so the subcommand receives `serve ./folder`.

**Comment by christiannagel** [comment]
The issue is back with preview 4, it was ok with preview 3. Preview 5 has the issue as well.

**Comment by gingters** [comment]
@joeloff I also can reproduce this bug. You should change 'for consideration' to bug.

**Comment by marcpopMSFT** [comment]
@sfoslund I wonder if this is a command line parsing issue.

**Comment by sfoslund** [comment]
Yup, thanks, simple fix out here: https://github.com/dotnet/sdk/pull/19086
