### ISSUE TITLE
`dotnet watch` not equals `dotnet watch run` for asp.net core settings

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#16133]
From the asp.net core 6.0 preview 1 release blog(<https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/#whats-new-in-asp-net-core-in-net-6-preview-1>), I got the message that:

> dotnet watch now does dotnet watch run by default

But it seemed not working for me

![image](https://user-images.githubusercontent.com/7604648/109583075-402de000-7b3a-11eb-8138-37263a25ec1e.png)

project file content:

![image](https://user-images.githubusercontent.com/7604648/109583106-4f149280-7b3a-11eb-909d-5f7275efb319.png)

dotnet versions:

![image](https://user-images.githubusercontent.com/7604648/109463410-eb3d8b80-7a9f-11eb-9b7a-6c6f1c55c3e9.png)

**Comment by pranavkm** [comment]
@WeihanLi this issue was fixed as part of the 6.0-preview2 release. If you still think you're seeing this issue with a newer SDK, please file a new issue and we'd be happy to investigate.
