### ISSUE TITLE
Add ability for `dotnet watch` to work with solutions

### ISSUE THREAD

**Issue by GeeWee** [dotnet/sdk#16134]
I have a multi-project solution.
Changing functionality often includes changing files in multiple projects.
I can run `dotnet test` and `dotnet build` in the root solution directory to test or build all projects, but I am unable to do the same thing with `watch` as that requires a project.
If you could run `dotnet watch test` in a solution directory, the developer experience for multi-project solutions would be much more pleasant.

**Proposal**: Allow `dotnet watch test` and `dotnet watch build` to work in solution directories. It can simply run a separate `dotnet watch build/test` command for each project referenced.

I think it might make sense to disallow `dotnet watch run` in solution directories (just like you can't do it without watch) as it might not make sense to run multiple projects in the same terminal.

**Comment by pranavkm** [comment]
Thanks for the issue report. At this point, this is not a feature we're considering implementing in dotnet-watch.
