### ISSUE TITLE
Tip: Using a custom crossgen for dotnet store

### ISSUE THREAD

**Issue by vkvenkat** [dotnet/sdk#1614]
I was looking for a way to force `dotnet store` to use a custom crossgen (say, available at `D:\coreclr\bin\Product\Windows_NT.x64.Release`) to generate native images, rather than the default version that gets pulled. Looks like the crossgen used here gets pulled from the NuGet cache. The solution for my problem was to just over-write the crossgen executable at `C:\Users\Varun\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.1.0-preview2-25616-02\tools`. 

Thanks @eerhardt and @JosephTremoulet for the solution.

**Comment by livarcocc** [comment]
We don't have plans to support this at the moment.
