### ISSUE TITLE
Error NETSDK1064 Package Microsoft.EntityFrameworkCore.Analyzers, version 3.1.2 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.

### ISSUE THREAD

**Issue by KeithT** [dotnet/sdk#16160]
Since logging in as a different windows user (server 2019) and opening .Net Core API 3.1 project created by the original user am unable to build or run in debug in VS2019 with the error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1064	Package Microsoft.EntityFrameworkCore.Analyzers, version 3.1.2 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.	"projectname" C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Have tried deleting .obj directory, removing packages and restoring them with no luck.

Thanks in advance for any help.

**Comment by KeithT** [comment]
Solved this, in case it helps anyone else, it was due to the new windows user account not having access write access to the project directory.

**Comment by vidhan4you** [comment]
> Solved this, in case it helps anyone else, it was due to the new windows user account not having access write access to the project directory.

this resolved issues for us.

**Comment by AsianWizard99** [comment]
I getting same error message please expalin in detail how you solve it ?!
