### ISSUE TITLE
Package is not compatible with netcoreapp2.0

### ISSUE THREAD

**Issue by Kayak58** [dotnet/sdk#1617]
I have created new ASP.NET Core 2.0 Web Application, Web API, and successfully installed several 'old' nuget packages. But when trying to install our own package, I got this error

Restoring packages for C:\Dev\WebApplication1.csproj...
Installing Trace 1.4.0.
Package Trace 1.4.0 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package eBoks.Trace 1.4.0 supports: net35 (.NETFramework,Version=v3.5)
Package eBoks.Trace 1.4.0 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x64. Package eBoks.Trace 1.4.0 supports: net35 (.NETFramework,Version=v3.5)
Package restore failed. Rolling back package changes for 'WebApplication1'.

After carefully comparing working and not working packages, I found the difference in the file structure.

In the .nuspec file for Trace we include one assembly:

        <file src="trace\bin\trace.dll" target="lib\net35\trace\trace.dll" />

The problem is the target path. The following works

        <file src="trace\bin\trace.dll" target="lib\net35\trace.dll" />

This problem only occurs with Asp.Net Core 2.0 - the Trace package installs without error in .NET full framework applications.

I cannot judge if the target path is wrong and we have been lucky so far. Or if this is a bug in Asp.Net Core 2.0 / nuget. But in any case, the error message is very misleading.

**Comment by dasMulli** [comment]
Looks similar to https://github.com/NuGet/Home/issues/4259

The second part of the lib directory isn't something that nuget can work with.. (locale, platform, RID - not sure what NuGet expects here), but if there isn't a dll in `lib\net35`, it will fail the compatibility check..

**Comment by Kayak58** [comment]
@Martin that was what I suspected, but I still think the error message is misleading. And also it is strange that it is only a problem in an asp.net<http://asp.net> core project - but not in a .net framework project.


Den 29. sep. 2017 kl. 16.59 skrev Martin Andreas Ullrich <notifications@github.com<mailto:notifications@github.com>>:


Looks similar to NuGet/Home#4259<https://github.com/NuGet/Home/issues/4259>

The second part of the lib directory isn't something that nuget can work with.. (locale, platform, RID - not sure what NuGet expects here), but if there isn't a dll in lib\net35, it will fail the compatibility check..

**Comment by livarcocc** [comment]
The NuGet issue seems to have been fixed and the error message comes from them during restore. As such I am going to close the issue here. If this is still a problem comment and we can follow up.

@dasMulli once again, thanks for the help here. Appreciate it.
