### ISSUE TITLE
dotnet run and other commands taking a long time to do anything

### ISSUE THREAD

**Issue by kevinkoenig** [dotnet/sdk#16194]
[See this Link](https://www.screencast.com/t/sI6v4vGt36y)
executing any dotnet command takes for ever to start.  See link.  If I run dotnet outside my project directory it executes quickly

**Comment by kevinkoenig** [comment]
any update on this issue.  Since i posted it I have completely reinstalled my machine, rechecked out the software from source control and i am still getting the same problem.

**Comment by sfoslund** [comment]
Thanks for filing an issue, what version are you using? Can you provide the output of `dotnet --info`?

**Comment by kevinkoenig** [comment]
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.1.21103.13
 Commit:    b8a03527b2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21327
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
kevin.koenig@DESKTOP-194S92R  D:                                                                             [20:08]
❯

**Comment by kevinkoenig** [comment]
also i just reinstalled my entire machine from scratch.  Still an issue.

**Comment by sfoslund** [comment]
This is a known issue with 6.0 preview 1, can you update to a later version?

**Comment by kevinkoenig** [comment]
yes do i need to go to nightly builds?  what version should I use?

**Comment by kevinkoenig** [comment]
I just installed preview 2 and the issue is resolved
