### ISSUE TITLE
ServiceInterop DLL Not Found

### ISSUE THREAD

**Issue by jackbond** [dotnet/sdk#1619]
I've tried a million things and can't get the Microsoft.Azure.DocumentDB.Core Nuget to work in a solution. I've created an absolutely minimal solution which recreates the problem. Can someone please tell me what I am missing? Thank you. 
[repro.zip](https://github.com/dotnet/sdk/files/1346743/repro.zip)

**Comment by livarcocc** [comment]
I haven't tried with net47 because I don't have a windows machine available at the moment, however, I just changed your project to target netcoreapp2.0 and it worked for me.

Is this still happening to you? I will try this out tomorrow on Windows.
