### ISSUE TITLE
100ms Regression in Dotnet Build of Console Hello World

### ISSUE THREAD

**Issue by brianrob** [dotnet/sdk#16217]
When building the console template, there is a 100ms regression between baseline build 6.0.100-preview.3.21124.9 and regression build 6.0.100-preview.3.21126.14.

This appears to come from NuGet restore:

Baseline: 

| Event Name | Time MSec | Process Name | DURATION__MSEC | targetName |
-- | -- | -- | -- | --
| Microsoft-Build/Target/Stop | 5,051.093 | dotnet (19480) | 178.735 | Restore |

Regression:

| Event Name | Time MSec | Process Name | DURATION__MSEC | targetName |
-- | -- | -- | -- | --
| Microsoft-Build/Target/Stop | 2,806.855 | dotnet (13060) | 272.201 | Restore |

I can share traces offline.

**Comment by brianrob** [comment]
cc: @DamianEdwards

**Comment by brianrob** [comment]
@JonDouglas, @nkolev92, can you help get eyes on this?

**Comment by nkolev92** [comment]
Let's sync-up offline. 
We haven't made too many changes in the recent previews, so that looks unexpected.
