### ISSUE TITLE
bug: x64 and x86 dotnet don't see each other

### ISSUE THREAD

**Issue by arsinclair** [dotnet/sdk#16234]
I am trying to set-up a CI for building/publishing and then hosting a Blazor app on the same Windows machine. So to build/publish it I need a .NET SDK, and to host it on IIS I also need .NET Hosting Bundle (to have _AspNetCoreModuleV2_ in the IIS). I want the CI to be able to install missing .NET bundles, so before the deployment I need to check if there are any already installed. I am using a `dotnet --list-sdks` and `dotnet --list-runtimes` commands. It turns out, if I first install .NET SDK and then .NET Hosting Bundle, then the output of `dotnet --list-sdks` disappears, and vice versa in reverse order. Experimentally, I have found out that this happens, because .NET Hosting bundle is installed in the Program Files (x86) directory, opposed to .NET SDK, so there are two **dotnet.exe** files, one in Program Files and another one is in Program Files (x86). If I run the x86 version of dotnet.exe, it is unable to see installed x64 components, and if I use the one from Program Files folder, it doesn't see the x86 components. It seems like a bug to me.

Reproduction Steps (powershell)

1. Install .NET SDK (https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.200/dotnet-sdk-5.0.200-win-x64.exe)
2. Restart Powershell Window (so new PATH variables are picked up)
3. Run `dotnet --list-sdks`. Output: `5.0.200 [C:\Program Files\dotnet\sdk]`.
4. Run `dotnet --list-runtimes`. Output: <empty>
5. Run `(Get-Command dotnet).Path`. Output: `C:\Program Files\dotnet\dotnet.exe`.
6. Install .NET Hosting Bundle (https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.3-windows-hosting-bundle-installer)
7. Restart Powershell Window (so new PATH variables are picked up)
8. Run `dotnet --list-sdks`. Output: <empty>
9. Run `dotnet --list-runtimes`. Output: 
```
Microsoft.AspNetCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```
10. Run `(Get-Command dotnet).Path`. Output: `C:\Program Files (x86)\dotnet\dotnet.exe`.

**Comment by marcpopMSFT** [comment]
We actually intentionally try to keep the x86 and x64 SDK and runtime hives completely separate with no knowledge of the other one.  The hosting bundle isn't even designed to work with the SDK as it's meant just for running applications.
