### ISSUE TITLE
SolutionDir is not resolved during dotnet restore

### ISSUE THREAD

**Issue by bradphelan** [dotnet/sdk#1623]
See the following repository that can reproduce the error

https://github.com/bradphelan/msbuildbug

first reported at

https://stackoverflow.com/questions/46526428/msbuild-solutiondir-resolves-incorrectly-to-c-when-running-msbuild-tresto

**Comment by livarcocc** [comment]
I believe this is an issue with the generated metaproj for the solution. I will move it to MSBuild for now.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#2743
