### ISSUE TITLE
Feature Request: support for nuget package consumption in framework-less projects

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/sdk#16244]
## Details about Problem

Detailed in issue https://github.com/dotnet/msbuild/issues/6210

Presently, nuget client errors out during `dotnet restore` if a user's project does not specify either TargetFramework or TargetFrameworks. E.g. if I'm building a nuget package that contains only build scripts or tools, so has no dependency on any dotnet framework version.

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):
dotnet 3.1.406
dotnet 6.0.100-preview.1.21103.13

Product version: 

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

Detailed in issue https://github.com/dotnet/msbuild/issues/6210

### Verbose Logs

N/A

**Comment by dsplaisted** [comment]
I think this is a better fit for the NuGet repo, so we can close this one in lieu of NuGet/home#10640
