### ISSUE TITLE
It_retries_on_failure_to_create_apphost still failing on Unix

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#16252]
from https://github.com/dotnet/sdk/pull/16230
It seems that this test case is consistently failing on several different builds (https://dev.azure.com/dnceng/public/_build/results?buildId=1027812&view=results, https://dev.azure.com/dnceng/public/_build/results?buildId=1027778&view=results, https://dev.azure.com/dnceng/public/_build/results?buildId=1028077&view=results) with the following exception:

```
�[31;1m    Microsoft.NET.Build.Tests.AppHostTests.It_retries_on_failure_to_create_apphost [FAIL]
�[m�[37m      Expected command to fail but it did not.
�[m�[37m      File Name: /tmp/helix/working/B9820A2B/p/d/dotnet
�[m�[37m      Arguments: msbuild /t:Build /private/tmp/helix/working/B9820A2B/w/A3C00909/e/testExecutionDirectory/It_retries_on---EA39C758/RetryAppHost/RetryAppHost.csproj /restore /clp:NoSummary /p:CopyRetryCount=1 /p:CopyRetryDelayMilliseconds=0
�[m�[37m      Exit Code: 0
�[m�[37m      StdOut:
�[m�[37m      Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
�[m�[37m      Copyright (C) Microsoft Corporation. All rights reserved.
�[m�[37m      
�[m�[37m        Determining projects to restore...
�[m�[37m        All projects are up-to-date for restore.
�[m�[37m        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
�[m�[37m      /tmp/helix/working/B9820A2B/p/d/sdk/6.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(522,5): warning NETSDK1113: Failed to create apphost (attempt 1 out of 2): The process cannot access the file '/private/tmp/helix/working/B9820A2B/w/A3C00909/e/testExecutionDirectory/It_retries_on---EA39C758/RetryAppHost/obj/Debug/net5.0/apphost' because it is being used by another process. [/private/tmp/helix/working/B9820A2B/w/A3C00909/e/testExecutionDirectory/It_retries_on---EA39C758/RetryAppHost/RetryAppHost.csproj]
�[m�[37m        RetryAppHost -> /private/tmp/helix/working/B9820A2B/w/A3C00909/e/testExecutionDirectory/It_retries_on---EA39C758/RetryAppHost/bin/Debug/net5.0/RetryAppHost.dll
```

It seems to be consistently failing now on Unix (both Ubuntu and macOS).

As for the problem - I cannot see it from code inspection. The first attempt is failing, the warning is expected. The second attempt is apparently succeeding, as if it failed, it seems the MSBuild task would fail, and dump stack, and the build will fail, as the test is expecting. Why would it succeed though since the output is still locked? I will set up a machine.

**Comment by danmoseley** [comment]
It reproduces easily on Ubuntu 20.04
`~/git/sdk/src/Tests/Microsoft.NET.Build.Tests$ ../../../.dotnet/dotnet test --filter It_retries_on_failure_to_create_apphost`

**Comment by marcpopMSFT** [comment]
@sfoslund mind taking a look as part of domestic cat?
