### ISSUE TITLE
Enable tests for .NET 4.7.1 and 4.7.2

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1625]
.NET 4.7.1 hasn't been released yet.  I'm adding tests for some 4.7.1 scenarios in #1336, but can't enable them for CI until we can have the targeting pack installed.

Once there is a targeting pack for .NET 4.7.1 available, we should update the CI machines to install it and enable the tests for targeting .NET 4.7.1

EDIT: Let's also use this item to track enabling tests for .NET 4.7.2, which will be added with #2250

**Comment by livarcocc** [comment]
I believe these are now enabled.
