### ISSUE TITLE
Support for performance improvement effort

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/sdk#16250]
We are adding 5 timing values to our telemetry for .NET Cli commands. Because this is in support of telemetry commitments for 6.0 we are adding these values in the 5.0.202 servicing release to ensure adequate time to respond to what we learn. Five new values will be recorded on certain existing telemetry events, with no other changes in telemetry: 

|First appears in| Description of data|
|-|-|
| 5.0.202 |   Elapsed time from process start until entering the CLI program's main method, measuring host and runtime startup |
| 5.0.202| Elapsed time for the step that adds .NET Tools to the path on first run |
| 5.0.202| Elapsed time to display first time use notice on first run|
| 5.0.202| Elapsed time for generating ASP.NET Certificate on first run|
| 5.0.202|Elapsed time to parse the CLI input |

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/16330
