### ISSUE TITLE
Workload command line structure

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#16267]
https://github.com/dotnet/sdk/pull/16262 is an initial stub to unblock parallel work thread. However, there are many pending works. The following does not include functionality (they current just print out stub messages)

- [x] Doc link for `dotnet workload` command
- [x] All loc string are not review or even properly authored
- [x] Remove unused loc string
- [ ] Parser tests
- [x] nuget has a `--no-cache` option. That will get confused with our cache to store downloaded nupkgs

**Comment by wli3** [comment]
list and search


list for what is installed on the machine
search for all availbae

list workload id 

search has workload id (workload and pack relation maybe later. Scenario workload vs not )




install <WORKLOADs>
uninstall <WORKLOADs>
update (take nothing)
list           Display workloads installed.
search           Display workloads available.
[search partial search/nothing]

restore??   <solution or project name> Install workloads required for the project.
(reference build)

**Comment by sfoslund** [comment]
I added the docs link a few weeks ago and I think we have adequate test coverage, @wli3 is there anything in particular we have left to do here?

**Comment by sfoslund** [comment]
I think we have enough CLI coverage included in the workload commands that we don't need separate parser tests. Closing this out
