### ISSUE TITLE
Generating app.config for DLL pre SDK

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1626]
This question concerns projects using the old MSBuild format / SDK. But still thought the question was best asked here. Please redirect if there is a more appropriate place. 

Want to auto generate an app.config file for a number of DLL projects. Mainly to get the correct binding redirects to allow the DLLs to be loaded by xunit. 

In a new SDK project I can accomplish this by adding the following to my project file. 

``` xml
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ForceGenerationOfBindingRedirects>true</ForceGenerationOfBindingRedirects>
```

The old SDK doesnt seem to recognize the `ForceGenerationOfBindingRedirects` property though and hence wont generate the app.config because the project is not an exe or winexe. 

How can I make this work here? The binding redirects are easy to mess up when they are hand coded.

**Comment by livarcocc** [comment]
Hey @jaredpar have you figured this out?
