### ISSUE TITLE
`dotnet list package --vulnerable` crashes 

### ISSUE THREAD

**Issue by johnkors** [dotnet/sdk#16279]
Two scenarios that crash the `dotnet list package --vulnerable` command:

1. If you use multiple feeds, and only is able to connect to _one_ of them.
2. If running it on a solution containing a a mix of new SDK style and older (non-SDK style csproj).

SDK version: 5.0.200

I assume atleast it should rather gracefully handle 2 here.

**Comment by JonDouglas** [comment]
@johnkors or @marcpopMSFT you can move this over to https://github.com/NuGet/Home/issues as we own this experience.

**Comment by marcpopMSFT** [comment]
@JonDouglas To reduce triage costs on the SDK (as there are now 8 other teams with code in the SDK repo), we've implemented area labels to tag for other teams.  See all items labeled for Area-NuGet.

**Comment by JonDouglas** [comment]
Cool, we'll take a look regularly then!
