### ISSUE TITLE
Publishing to linux and then osx produces wrong binary

### ISSUE THREAD

**Issue by xPaw** [dotnet/sdk#16282]
I have this code on CI:
https://github.com/SteamDatabase/ValveResourceFormat/blob/4be17a78cf6e2c5cb49823a5ff6c8c3ac3427221/appveyor.yml#L12-L13

It publishes a linux runtime binary, and then a osx one. The problem there is that it copies linux binary into osx folder.

Deleting `obj` folder between the commands fixes the issue.

Repro locally:
```bash
git clone https://github.com/SteamDatabase/ValveResourceFormat
cd ValveResourceFormat
dotnet publish --configuration Release -p:PublishSingleFile=true --runtime linux-x64 Decompiler\Decompiler.csproj
dotnet publish --configuration Release -p:PublishSingleFile=true --runtime osx-x64 Decompiler\Decompiler.csproj

file Decompiler/bin/Release/osx-x64/publish/Decompiler
Decompiler/bin/Release/osx-x64/publish/Decompiler:  ELF 64-bit LSB shared object, x86-64
```

It should be a `Mach-O 64-bit` binary. Seems like the bug is in `obj` folder being shared when publishing to different runtimes.

Tested on dotnet 5.0.104

**Comment by marcpopMSFT** [comment]
I see you have AppendRuntimeIdentifierToOutputPath set to false in your directory.build.props which is likely affecting the obj folder as well.  Try setting that to true and see if the issue goes away.

**Comment by xPaw** [comment]
That does appear to solve this issue.

But still, it smells like a bug to me.

**Comment by marcpopMSFT** [comment]
That value will affect whether we share the same obj folder. Certainly we could do more to try to detect and clean but for performance sake, we don't clean the obj or even output folder of extra files if your configuration leads to using the same exact folders and we don't have plans to change that at this time.
