### ISSUE TITLE
Update SDK tests to supported TFM's

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#16292]
Many tests target out of support TFM's and few target the latest TFM.

eg
```
      (_CheckForEolTargetFrameworks target) -> 
        C:\h\w\95ED08C8\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp1.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\h\w\95ED08C8\t\dotnetSdkTests\kviqdfge.mx1\It_packs_nond---BFC73927\NetStandardAndNetCoreApp\NetStandardAndNetCoreApp.csproj]
```
```
        [RequiresSpecificFrameworkFact("netcoreapp1.1")]
        public void IfAToolHasNotBeenRestoredForNetCoreApp2_0ItFallsBackToNetCoreApp1_x()
```
```
 334          [InlineData("Major", "netcoreapp3.0", true)]
  335:         [InlineData("Major", "netcoreapp2.0", true)]
```

Random examples pasted above from searching the SDK tree. I assume there will need to be a few cases of obsolete TFM's since customers will try to build projects containing them, but almost all our tests should be testing supported combinations.

**Comment by marcpopMSFT** [comment]
First step is in this PR. https://github.com/dotnet/sdk/pull/19708  Adding a note here to remove DisableImplicitNamespaceImports once it's no longer needed.

**Comment by marcpopMSFT** [comment]
Completed for all TestProjects (or close enough). Dynamic project files are next.

**Comment by marcpopMSFT** [comment]
@v-wuzhai I wanted to check in here. You've done a lot of PRs and I've noticed you've moved on to RIDs. Are there any remaining items to fix for the target framework or are we close enough to call it done? We don't need to be 100% as long as most are updated.

**Comment by v-wuzhai** [comment]
@marcpopMSFT All the files in the TestProjects and Test folders have been updated which include TFM's and RID's, except for the PRs of #26821、#25479 and #22784 which are not been merged.

**Comment by marcpopMSFT** [comment]
Since the vast majority of PRs are now in. I'll close this as we clean up the last few.
