### ISSUE TITLE
The runtime of 6.0 preview 2 still exists after upgrading SDK from 6.0 preview 2 to 6.0 preview 3.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/sdk#16303]
Repro steps:
1. Install the release SDK 6.0.100-preview.2.21155.3
2. Install SDK 6.0 preview 3 from master branch of https://github.com/dotnet/installer

Expected Result:
The SDK 6.0 preview 2 shouldn't be installed any more.

Actual Result;
The runtime of 6.0 preview 2 still exists.
![image](https://user-images.githubusercontent.com/65638819/110743484-10d24e00-8273-11eb-8fef-4c47c496c595.png)

dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21160.15
 Commit:    a28ceebdcd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21160.15\

Host (useful for support):
  Version: 6.0.0-preview.3.21157.6
  Commit:  acbbb50549

.NET SDKs installed:
  6.0.100-preview.3.21160.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.3.21158.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21157.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21127.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
@dleeapho looks like it's the runtime package in particular (whereas the sdk and aspnet correctly upgrade) so routing your way to have someone take a look.

**Comment by marcpopMSFT** [comment]
Per email, this was not repro so closing.
