### ISSUE TITLE
Release labels are missing for 2.0.0 (others?)

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1631]
See https://github.com/dotnet/sdk/releases

Note that it appears incomplete / out-of-date.

/cc @livarcocc @nguerrera

**Comment by livarcocc** [comment]
Hey @ericstj, why do we need release tags for this repo? Given that it is not visible to external customers directly?

cc @leecow as we may need to update the tictoc to add this to the list of tags to be created.

**Comment by ericstj** [comment]
I was trying to figure out what commit was tied to RTM and couldn't, so from that perspective I think its necessary.

**Comment by nguerrera** [comment]
We can reverse engineer the hashes from the Product version in the version resource:
 
![image](https://user-images.githubusercontent.com/75470/31252887-8fe9fae4-a9d7-11e7-870b-70453e33a192.png)

**Comment by leecow** [comment]
Yeah, I hadn't been tracking the SDK repo at all but can add it to the list of release tasks.

**Comment by livarcocc** [comment]
I have re-created the tags for 2.0.2 all the way to 2.1.4 and pushed them. I did my best to find the right commits.

**Comment by ericstj** [comment]
Thanks Livar.
