### ISSUE TITLE
SingleFile Bundling should deduplicate path conflicts

### ISSUE THREAD

**Issue by daz10000** [dotnet/sdk#16311]
### Description

A recent package update to a third party library broke a project we have that compiled to a single file executable.  The error message was the dreaded `Error MSB4018: The "GenerateBundle" task failed unexpectedly` , `Found multiple entries with the same BundleRelativePath` error.    

Using the [nice features released in net6 preview](https://github.com/dotnet/runtime/pull/48336)  I was able to narrow the file collision down to these two entries - the xml file that's part of the FSharp.Core library.    Frustratingly in this case, an upstream problem causes the `FSharp.Core.dll` library to be included twice and as of release `5.0.1` for that library, they added an xml file that is now copied twice into the final binary.  It doesn't affect multi file distributions  - presumably just copes over, but for single file it stops with this error (as of net6) and a more cryptic error without the paths in net5 and earlier.

```
System.ArgumentException: Invalid input specification: Found entries 
'C:\xxxxx\.nuget\packages\fsharp.core\5.0.1\contentFiles\any\netstandard2.0\FSharp.Core.xml', 
'C:\xxxxx\.nuget\packages\fsharp.core\5.0.1\contentFiles\any\netstandard2.0\FSharp.Core.xml' with the same BundleRelativePath 'FSharp.Core.xml
```
 
I have a attached a tiny project below that reproduces the setup.   The duplication comes from one project referring to another (both F#) projects,  and using the paket package manager which manages the msbuild instructions.  I honestly can't tell why there are two copies but it's non-trivial to prevent unfortunately, so it's not an option to reconfigure the project (I tried for many hours).

I would expect the bundler to deduplicate the source /target paths like the one above and conclude there is no collision.  Obviously attempting to bundle two different libraries into the same output file would be bad but this is not the case.

### Configuration

* "5.0.200 (also happens on all later net6 versions up to nightly release)
* Windows
* x64
* Appears to be a general issue with the platform
* F# application (for what it's worth)

### Regression?

In this case, it is not a net runtime issue that caused the problem but a library change.  Unfortunately this scenario is common enough to be a major headache.  Others [had reported the same problem with the triggering library](https://github.com/dotnet/fsharp/issues/11111) by the time I diagnosed the root cause.   Short term the library can be altered but it would be strongly preferable for the bundler to simply dedup the list before deciding if there are collisions

### Other information

Same reproduction.

[Playground.zip](https://github.com/dotnet/runtime/files/6120033/Playground.zip)

[FSharp library causing the issue]((https://github.com/dotnet/fsharp/issues/11111)

**Comment by daz10000** [comment]
I tend to agree that the root cause is the sdk offering the FSharp.Core.dll package twice and there being an xml file inside with copying instructions so there's a duplicate.   While narrowing this down,  I read a lot of tickets from folks dealing with bundling conflicts and I would say that a majority of them are due to strange project configurations and usually harmless in the sense that it was the same thing added twice. In most cases it was blocking for the projects ( it was extremely painful till the latest net6 update to even identify the offending file, and often tricky to work around - we have to pin library versions and hope that somebody fixes the packaging problem),  so it would definitely be nice to have an option to move forward when the duplication is harmless but I do agree that long-term the solution is to make the packaging resolution bullet-proof. I suspect there are still quite a lot of ways this can happen just from searching for this exact string in a search engine "GenerateBundle task failed  unexpectedly" I get over 500 entries.

**Comment by vitek-karas** [comment]
@agocke - something to consider. It would resolve lot of customer issues if we were to ignore exact duplicates in the bundler - or maybe issue a warning but continue when this happens. Non-duplicate collisions should still fail in my opinion, as in that case we're potentially overwriting one file with another with potentially different content.

**Comment by gcaughey** [comment]
> @agocke - something to consider. It would resolve lot of customer issues if we were to ignore exact duplicates in the bundler - or maybe issue a warning but continue when this happens. Non-duplicate collisions should still fail in my opinion, as in that case we're potentially overwriting one file with another with potentially different content.

I'd certainly prefer a warning in all cases since the differences might not matter. I'd want to be able to test and choose.

**Comment by agocke** [comment]
Dedup seems reasonable to me, where duplicate means identical path with an ordinal comparison. Allowing any other conflicts seems like a recipe for disaster.

**Comment by gcaughey** [comment]
> Dedup seems reasonable to me, where duplicate means identical path with an ordinal comparison. Allowing any other conflicts seems like a recipe for disaster.

If everything works when you don't package single-file, then isn't it getting automatically deduped at some point into the publish folder anyway? And if it works packaged single-file with deduping, then I'm not seeing a disaster here. Or make the choice optional like with trimming.

**Comment by vitek-karas** [comment]
Non-single-file is basically also broken, but in a different way. It silently overwrites the files in the output. So if there are two different sources for the same output file, the actual file in the output is pretty much randomly picked from the two. The bundler just made this visible. This is obviously not a concern if it's the same file being copied twice (just perf), which is what the proposal is here - change bundler to allow that case as well.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/runtime/pull/50476 changes the bundler such that it allows exact duplicates. So far that has been the reason for the failures we've seen. The larger issue of potentially getting non-exact duplicates is still there - and is tracked by https://github.com/dotnet/sdk/issues/16576 (since it affects not just the bundler, but any publish in theory).

**Comment by sfoslund** [comment]
Closing this per https://github.com/dotnet/sdk/issues/16576#issuecomment-815316382
