### ISSUE TITLE
Help columns are not distributed in a nice way

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/sdk#16312]
Repro:

```
dotnet build -h
```

Produces:
![image](https://user-images.githubusercontent.com/5844318/110804535-1dd04c80-8235-11eb-952a-3bc86887b842.png)

`--verbosity` makes this look awful. 

I know this is a fix to System.CommandLine, but I hope we can contribute this fix back to that repo. 

Suggest it looks at the width of the options and moves them to the end of the description if longer than a certain amount. Or just always move to the end of the description. 

Also, I though we were going to get wrapping here. Let's check if we can easily access the System.CommandLine smarts on wrapping. 

@jonsequitur

**Comment by sfoslund** [comment]
@jonsequitur do I remember correctly that you mentioned there were some help enhancements being worked on? Are they relevant to this issue?
