### ISSUE TITLE
VS2017: Why "Assets file doesn't have a target for" says about 4.0 framework?

### ISSUE THREAD

**Issue by sm-g** [dotnet/sdk#1633]
I had `<Project ToolsVersion="14.0"`-like test project. I want to use EF Core (InMemory), but because of this I need to add binding redirects, so NUnit stops working... (https://github.com/aspnet/EntityFrameworkCore/issues/9046) So I try to convert it to `<Project Sdk="Microsoft.NET.Sdk">`-project. I already have such test project in solution (working). I create same structure of csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
   ...

```

remove AssemblyInfo.cs, rmdir bin/obj, restart VS, dotnet restore, but cannot build that new project:

```
Assets file doesn't have a target for '.NETFramework,Version=v4.0/win7-x64'. Ensure that restore has run and that you have included 'net40' in the TargetFrameworks for your project. You may also need to include 'win7-x64' in your project's RuntimeIdentifiers.
```
(that right, assets file is all about 4.6.1).

"Properties" in project context menu also show in Target framework "4".

**Comment by MisinformedDNA** [comment]
Did you ever figure this out? I'm getting this error with a much shorter CSPROJ as well.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.2.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="7.2.1" />
  </ItemGroup>

</Project>
```

**Comment by livarcocc** [comment]
@MisinformedDNA I just tried your project above and could not repro this issue. I used 2.1.300-preview1, which our latest preview for .NET Core 2.1.

I created a console application and then replaced my csproj with yours above. Can you try that out and let us know if that still repros?

@sm-g any chance you can provide us with more detailed repro steps? A small repo on github that repros the issue would be perfect, if possible at all.

**Comment by sm-g** [comment]
@livarcocc https://github.com/sm-g/EFCoreInMemorySample/tree/master/Sdk1633

VS 15.6.0

dotnet --info
```
Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by MisinformedDNA** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.2.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="7.2.1" />
  </ItemGroup>

</Project>
```

- Open above project
- Build project
- Change TargetFramework to net461
- Build project
- Error occurs

Workaround: Close and re-open VS.

**Comment by livarcocc** [comment]
I wonder if this is some up-to-date check preventing restore from running when the TFM changes.

cc @Pilchie and @rrelyea to comment on that possibility.

**Comment by Pilchie** [comment]
The project system should be nominating a restore when TFM changes.  Can you run VS with the environment variable `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED` set to `1`, and copy the logging from the new output window pane the project-system creates?
