### ISSUE TITLE
Export output of dotnet list package to a consumable file

### ISSUE THREAD

**Issue by fleed** [dotnet/sdk#16374]
Is it possible to export the output of the `dotnet list package` command to a consumable file (e.g.: json, xml, csv)?
I cannot find anything with the help `-h`.

I can use a workaround (e.g. **Out-File** in PowerShell), but I should still parse the result.

Use case: produce the list of packages used as part of CI/CD pipeline.

**Comment by KalleOlaviNiemitalo** [comment]
https://github.com/NuGet/Home/issues/7752 is a similar issue in the NuGet repo.
