### ISSUE TITLE
$(Configuration) ignored for OutputPath specified in Directory.Build.props

### ISSUE THREAD

**Issue by AlgoryxMartinT** [dotnet/sdk#16390]
## Issue summary

It seems the `$(Configuration)` property is ignored when it is present in `OutputPath` in `Directory.Build.props` and the project is built from the solution file.

## In-depth description
I have a project that looks like this:

```
📦MyLibrary
 ┣ 📜Directory.Build.props
 ┣ 📜MyProject.csproj
 ┗ 📜MySolution.sln
```

where the files look like this:

**Directory.Build.props**
```xml
<Project>
  <PropertyGroup>
    <OutputPath>build-output/$(Configuration)</OutputPath>
  </PropertyGroup>
</Project>
```

**MyProject.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**MySolution.sln**
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31025.194
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyProject", "MyProject.csproj", "{363815D0-BD72-4FE7-894C-9ADA006AB466}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Release|x64 = Release|x64
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{363815D0-BD72-4FE7-894C-9ADA006AB466}.Debug|x64.ActiveCfg = Debug|x64
		{363815D0-BD72-4FE7-894C-9ADA006AB466}.Debug|x64.Build.0 = Debug|x64
		{363815D0-BD72-4FE7-894C-9ADA006AB466}.Release|x64.ActiveCfg = Release|x64
		{363815D0-BD72-4FE7-894C-9ADA006AB466}.Release|x64.Build.0 = Release|x64
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {F1F4077E-1F0B-405B-BE9E-370123B382AF}
	EndGlobalSection
EndGlobal
```

When I build this project, there is inconsistent behavior if I build it with `dotnet build MySolution.sln` and `dotnet build MyProject.csproj`. The build output looks like this:

**Expected**
| Command                       | Output path                             |
|-------------------------------|-----------------------------------------|
| dotnet build MySolution.sln   | build-output\Debug\net5.0\MyProject.dll |
| dotnet build MyProject.csproj | build-output\Debug\net5.0\MyProject.dll       |

**Actual**
| Command                       | Output path                             |
|-------------------------------|-----------------------------------------|
| dotnet build MySolution.sln   | build-output\Debug\net5.0\MyProject.dll |
| dotnet build MyProject.csproj | build-output\net5.0\MyProject.dll       |

Moving the `OutputPath` property to the `csproj` file instead of `Directory.Build.props` gives the expected result.

**Comment by marcpopMSFT** [comment]
Directory.Build.props gets loaded first before the main project file even so Configuration hasn't been set yet when the D.B.props file is processed. If you do dotnet build -c debug where you specify the configuration explicitly, that should set the value in time to be honored.
