### ISSUE TITLE
SDK change to skip registry checks in Microsoft.CodeAnalysis.targets for netcore/netstandard projects

### ISSUE THREAD

**Issue by mavasani** [dotnet/sdk#1641]
`CodeAnalysisSkipRegistryChecks` is the new property added to Microsoft.CodeAnalysis.targets in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/88928?_a=files to address design time build performance hit in https://github.com/dotnet/roslyn/issues/22110. SDK targets for netcore/netstandard projects need to set this property to true to avoid performance hit from these registry lookups.

**Comment by mavasani** [comment]
Tagging @jinujoseph @davkean @Pilchie @livarcocc

**Comment by livarcocc** [comment]
Is there a reason why we need to set this in the SDK directly? Couldn't the analyzers props/targets identify a project as being netcoreapp/netstandard and turn it OFF itself?

**Comment by mavasani** [comment]
No longer needed now - we have decided to remove the underlying registry search in this targets file.
