### ISSUE TITLE
Suspicious code found inside the ResolvePackageAssets task

### ISSUE THREAD

**Issue by 0xced** [dotnet/sdk#16447]
While investigating what files are copied into the publish directory, I ended up down the rabbit hole reading the source code of the `ResolvePackageAssets` task. There, I stumbled on [three lines](https://github.com/dotnet/sdk/blob/14707360491225abea19a7c00f5b1ac17696659e/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs#L1426-L1429) which seem very suspicious:

```c#
// publishPackageExclusions is a HashSet<string>
if (publishPackageExclusions.Contains(library.Name))
{
    publishPackageExclusions.Add(library.Name);
}
```

Testing if a set contains an element to add it in that set doesn't make sense. Most probably the `Contains` test was meant to be performed on another collection. Maybe it is the result of a bad merge? 

/cc @nguerrera @dsplaisted

**Comment by dsplaisted** [comment]
Uh yeah, that does seem wrong :-)

**Comment by KalleOlaviNiemitalo** [comment]
Relevant diff at <https://github.com/dotnet/sdk/pull/3348/commits/ad4c5402cc33e657d49e4b0d60db5c56bdafba4e?diff=split&w=1#diff-d095ccf81757e280c34c04844d41b02c99840136f14ac7eaf29a15619255bf0fR1383-R1386>.

It used to check `if (excludeFromOutputPackageIds.Contains(library.Name))` instead, and `excludeFromOutputPackageIds` was renamed to `excludeFromPublishPackageIds` in that commit, so perhaps it should be checking `if (excludeFromPublishPackageIds.Contains(library.Name))` now.
