### ISSUE TITLE
`dotnet publish` Targets Different Frameworks when Publishing Multiple Projects

### ISSUE THREAD

**Issue by Afanyiyu** [dotnet/sdk#16450]
# Summary

Run `dotnet publish` for two different projects in one solution, and published artifacts targeted different frameworks (`5.0.0` and `5.0.4`). This causes the program to fail to start.

# Detail

Repo: [Ruminoid/Toolbox](https://github.com/Ruminoid/Toolbox/tree/v0.2.0) / Tag: [v0.2.0](https://github.com/Ruminoid/Toolbox/tree/v0.2.0)

My build process ([Build.cs](https://github.com/Ruminoid/Toolbox/blob/v0.2.0/build/Build.cs)) triggers `dotnet publish` for each project in the solution, and sets self-contained publishing ([L125](https://github.com/Ruminoid/Toolbox/blob/v0.2.0/build/Build.cs#L125)) for the two executables [rmbox](https://github.com/Ruminoid/Toolbox/blob/v0.2.0/src/rmbox/rmbox.csproj) and [rmbox-shell](https://github.com/Ruminoid/Toolbox/blob/v0.2.0/src/rmbox-shell/rmbox-shell.csproj). The CI log shows that [rmbox (log)](https://github.com/Ruminoid/Toolbox/runs/2155848159?check_suite_focus=true#step:5:123) and the [rmbox-shell (log)](https://github.com/Ruminoid/Toolbox/runs/2155848159?check_suite_focus=true#step:5:142) calls `dotnet publish` using the same parameters, but the result executables targeted different frameworks (`5.0.0` and `5.0.4`) in `runtimeconfig.json`.

In published artifacts in the [CI Build for v0.2.0](https://github.com/Ruminoid/Toolbox/actions/runs/671067911):

**rmbox.runtimeconfig.json:**

```json
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "5.0.0"
    }
  }
}
```

**rmbox-shell.runtimeconfig.json:**

```json
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "5.0.4"
      }
    ]
  }
}
```

As a result, the dependencies (e.g. `coreclr.dll`) (version `5.0.421.11614`) of `rmbox-shell` replaces the dependencies for `rmbox` and cause it to rollback to find the framework installed on the computer, and finally fails to start.

It's weird that if I runs the `nuke Publish` command (which execute [Build.cs](https://github.com/Ruminoid/Toolbox/blob/v0.2.0/build/Build.cs)) on my computer, the `rmbox-shell.runtimeconfig.json` is the same as `rmbox.runtimeconfig.json`, both are targeting version `5.0.0`. So I think this may be a bug caused by `dotnet/sdk` or the GitHub Actions.

## Here are a few reasons I think this is a failure caused by `dotnet/sdk` or GitHub Actions

- I runs the publish command on my computer and found that the two executables both work properly.

- This problem has been there since [v0.1.6](https://github.com/Ruminoid/Toolbox/tree/v0.1.6). The [CI Build for v0.1.6](https://github.com/Ruminoid/Toolbox/actions/runs/651411033) uses the .NET SDK version `5.0.201` ([log](https://github.com/Ruminoid/Toolbox/runs/2106591876?check_suite_focus=true#step:3:9)) with the bug existing while the [CI Build for v0.1.5](https://github.com/Ruminoid/Toolbox/actions/runs/636099694) uses the .NET SDK version `5.0.103` ([log](https://github.com/Ruminoid/Toolbox/runs/2067578639?check_suite_focus=true#step:3:9)) with the program working properly.

**Comment by Afanyiyu** [comment]
Update: I add a [actions/setup-dotnet](https://github.com/actions/setup-dotnet) step in my GitHub CI config to block the `5.0.201` SDK and force build to use `5.0.103`. The two apps are both working properly ([Build #68](https://github.com/Ruminoid/Toolbox/actions/runs/672387973)).

But I think the `dotnet publish` artifact using the same command line on one computer should target the same framework, whatever the SDK version is. As a temporary solution, I can now build the project by forcing to specify the SDK version, but I hope there will be a better way to solve this problem in the future.

**Comment by Afanyiyu** [comment]
Update: The solution above still have problems on MacOS computers so I found [this issue](https://github.com/actions/setup-dotnet/issues/157) to solve this. According to this issue, a better solution now is to add a `global.json` file using `dotnet new globaljson --sdk-version "<sdk version>"`. I [add the file](https://github.com/Ruminoid/Toolbox/commit/c58c76fcbda075100c29da1a8c263b934215a001) and it now [builds properly](https://github.com/Ruminoid/Toolbox/actions/runs/678638224).

**Comment by Afanyiyu** [comment]
Update: Setting `"version": "5.0.103"` also caused this problem.

**Comment by dsplaisted** [comment]
I'm not sure what would be causing this.  Is it possible to get a [binlog](https://aka.ms/binlog) of the build that seems to be using the wrong runtime version (5.0.0)?

**Comment by Afanyiyu** [comment]
Solved. I'll write down the cause of the problem and the solution here for latecomers.

---

## Cause

[NETSDK1150](https://docs.microsoft.com/dotnet/core/compatibility/sdk/5.0/referencing-executable-generates-error)

Just use

```sh
dotnet publish src/rmbox-shell/ --configuration Release --runtime osx-x64
```

will get

```
/Users/runner/.dotnet/sdk/5.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(993,5):
error NETSDK1150: The referenced project '../rmbox/rmbox.csproj' is a non self-contained executable.
A non self-contained executable cannot be referenced by a self-contained executable.
[/Users/runner/work/Toolbox/Toolbox/src/rmbox-shell/rmbox-shell.csproj]
```

See [CI#171](https://github.com/Ruminoid/Toolbox/runs/3456552046).

Use `.NET SDK 5.0.101` won't get this error because [this error was introduced in .NET SDK 5.0.300](https://docs.microsoft.com/dotnet/core/compatibility/sdk/5.0/referencing-executable-generates-error#version-introduced).

Let's take a look at the current project structure. `rmbox-shell` references `rmbox` which is also an executable. If `rmbox` is not published as a self-contained executable, it cannot be executed directly while it can be depended by `rmbox-shell`. This is exactly the situation I mentioned above, `rmbox` failed to run, but `rmbox-shell` runs normally. **This is a by-design behavior, not a bug.**

But such behavior does lack a specific description. And then, in `.NET SDK 5.0.300`, they added `NETSDK1150` and `NETSDK1151` to alert of this behavior.

And next are several solutions to this problem.

## Solution 1: Add `--self-contained true` parameter

**Status: Unavailable**

This cause anoher **bug of .NET SDK**. The `--self-contained` parameter cannot be used with `--runtime`.

See #10566, #10902 and #18116.

## Solution 2: Use `--use-current-runtime` parameter

**Status: Requires .NET 6.0**

See #14093 and #14293.

## Solution 3: Modify project files manually using build script

**Available** and here's my code.

```cs
new[]
    {
        SourceDirectory / "rmbox/rmbox.csproj",
        SourceDirectory / "rmbox-shell/rmbox-shell.csproj"
    }
    .ForEach(x =>
        File.WriteAllText(
            x,
            File.ReadAllText(x)
                .Replace(
                    "<!-- RMBOX_BUILD_PROPS -->",
                    $"<RuntimeIdentifier>{Runtime}</RuntimeIdentifier><SelfContained>true</SelfContained>")));
```

See [Build.cs](https://github.com/Ruminoid/Toolbox/blob/v0.5.5/build/Build.cs#L96-L112) and commit [fd6a5a5](https://github.com/Ruminoid/Toolbox/commit/fd6a5a57f63e9842250f690380ec211137d69ca1).

[CI of v0.5.5](https://github.com/Ruminoid/Toolbox/actions/runs/1186930677) uses this fix and now build successfully.
