### ISSUE TITLE
Improve NuGet package download API

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#16470]
Improve NuGet package download API added in https://github.com/dotnet/sdk/pull/16443 with the following:

- [x] Multiple feeds support (nuget.config)
- [x] Authentication
- [x] Signing verification
- [x] Proper error handling 
- [ ] Cancelation token (optional)
- [x] --disable-paralle
- [x]  --no-cache
- [x] --ignore-failed-sources

**Comment by wli3** [comment]
Many are closed via https://github.com/dotnet/sdk/pull/16846
