### ISSUE TITLE
VS mac update/installer - .NET SDK integration

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#16484]
- [x] Design [spec](https://microsoft-my.sharepoint.com/:w:/p/wul/EQq7eaqvdChBoN7ucln0H_UBRICzaZcC1IS5CroKOotUgA?e=ujCicM)
- [x] Dummy implementation so VS mac update/installer does not need to integration until the very end
  - [x] dotnet workload install
  - [x] dotnet workload update within a feature band
  - [x] dotnet workload update while crossing band update
  - [x] dotnet workload list (dotnet workload list --machine-readable --target-sdk-version 6.0.200)
- [x] Real implementation so VS mac update/installer does not need to integration until the very end
  - [x] dotnet workload install
  - [x] dotnet workload update within a feature band
  - [x] dotnet workload update while crossing band update
  - [x] dotnet workload list (dotnet workload list --machine-readable --target-sdk-version 6.0.200)
- [x] Collaborate with @GouriKumari to finish the implementation on VS mac updater and installer
- [x] Proper command implementation specific to VSMac install flow
  - [x] _machineReadableOption FromCacheOption validation
- [x] Testing

**Comment by marcpopMSFT** [comment]
Testing is ongoing but closing out as all known functional work is complete.
