### ISSUE TITLE
Add iOS, Android, and macCatalyst into SupportedPlatform with the correct scope

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/sdk#16488]
The Platform Compatibility Analyzer uses the MSBuild `SupportedPlatform` item to determine which platforms are included for platform compatibility checks. The default set of platforms included by the SDK previously included `iOS`, `Android`, and `macCatalyst`, but we found this to be too disruptive. Tools such as aspnetcore and the SDK itself encountered build warnings when `iOS` annotations were added to APIs such as `Process.Start`, surfacing that adding these annotations should be considered a breaking change. To mitigate that disruption, we've removed `iOS`, `Android`, and `macCatalyst` from the default set, but we need to find an appropriate way to include those platforms for scenarios where it makes sense--such as cross-platform class libraries.

**Comment by terrajobst** [comment]
I think here is the behavior we want:

* For projects representing general purpose libraries, we usually want newly supported platforms to be included by default. Yes, this might mean that the same code can generate more diagnostics later, but we believe that is the desired behavior to help library authors to ensure that their libraries are portable across all the platforms .NET runs on.
* We don't want false positives.
    - Newly added platforms that aren't widely used and have limited API support (such WASM) shouldn't be included by default because it's creating noise that prevents library developers to focus on what's important.
    - It's extremely unlikely that console apps, web sites or cloud services will run on iOS, Android or macCatalyst. We should exclude platforms from certain projects when they don't make sense.

I believe we should:

* Add iOS, Android, and macCatalyst if the `OutputType` is `Library` or `Module`.
* Ensure that web projects do not add them (not sure if an ASP.NET project is considered a console app or a library)

**Comment by jeffhandley** [comment]
> * For projects representing general purpose libraries, we usually want newly supported platforms to be included by default. Yes, this might mean that the same code can generate more diagnostics later...

This sounds similar to the `AnalysisLevel` concept. :thinking:

**Comment by marcpopMSFT** [comment]
Old issue triage, closing as it looks like it might have happened on the runtime side though unclear. Jeff can reopen if this is still something they are pursuing.
