### ISSUE TITLE
[SDK 6.0.100-preview.2.21155.3] the single exe of 'dotnet publish' cause error 'api-ms-win-core-winrt-l1-1-0.dll is missing'

### ISSUE THREAD

**Issue by wangyugui** [dotnet/sdk#16499]
[SDK 6.0.100-preview.2.21155.3] the single exe of 'dotnet publish' cause error 'api-ms-win-core-winrt-l1-1-0.dll is missing'

os:windows 7
dotnet sdk: SDK 6.0.100-preview.2.21155.3
download as Binaries, not as Installers

```
set DOTNET_ROOT=D:\hpc-bio\dotnet\dotnet-sdk-6.0
%DOTNET_ROOT%\dotnet build -c Release AppNet60.csproj

%DOTNET_ROOT%\dotnet publish -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:PublishTrimmed=true /p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishReadyToRunShowWarnings=true --framework net6.0-windows  -r win7-x64 AppNet60.csproj
```

the api-ms-win-core-winrt-l1-1-0.dll is not found in D:\hpc-bio\dotnet\dotnet-sdk-6.0 too.

as a compare, .net sdk v5.0.4 works well.

**Comment by wangyugui** [comment]
Api-ms-win-core-winrt-l1-1-0.dll was first developed on 08/01/2012 in the Windows 8 Operating System for Windows 8. 
https://www.exefiles.com/en/dll/api-ms-win-core-winrt-l1-1-0-dll/

so this is a win7 support problem

**Comment by wangyugui** [comment]
still happen in 6.0.100-preview.5.21302.13

**Comment by puyebu** [comment]
I have the same problem in 6.0.0-preview.6.21352.12 on Windows 7.

**Comment by dsplaisted** [comment]
@agocke @vitek-karas Can you take a look at / triage this?

**Comment by agocke** [comment]
Single-file is not supported on Windows 7. I'll add a line in the docs for this.

**Comment by agocke** [comment]
Also blocking off in the SDK for explicit win7 targeting: https://github.com/dotnet/sdk/pull/19439

**Comment by vmas** [comment]
Api-ms-win-core-winrt-l1-1-0.dll and other dependencies are provided by the [runtime.win7-x86.Microsoft.NETCore.Windows.ApiSets](https://www.nuget.org/packages/runtime.win7-x86.Microsoft.NETCore.Windows.ApiSets/) package. Single-file works fine on Windows 7 SP1.

**Comment by wangyugui** [comment]
@vitek-karas  thanks.

The exe file of win81-x64 publish works well on win7 x64 with the dll files of runtime.win7-x64.microsoft.netcore.windows.apisets.1.0.1.nupkg\runtimes\win7-x64\native .

**Comment by Pyrdacor** [comment]
Is it possible to use the "old publish" with NET6? I really need self-contained single-file executables on Win7 and I also need the most recent C# version. So this is a huge problem. I don't care if the files are extracted or not but I need to be able to create such file with NET6/C#10 support.
