### ISSUE TITLE
With .NET 6 preview 3 SDK installed, run failed for .NET 6 winforms/wpf. 

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#16508]
Repro steps:
Install .NET 6 SDK(6.0.100-preview.3.21173.9) from master branch of  https://github.com/dotnet/installer 
run dotnet new winforms or dotnet new wpf in CLI
dotnet build and run

Expected Result
dotnet run successfully

Actual Result:
Below error occurred
![image](https://user-images.githubusercontent.com/65637796/112413507-4ab75000-8d5b-11eb-9a3d-678c9ec42399.png)

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21173.9
 Commit:    e627233d2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21173.9\

Host (useful for support):
  Version: 6.0.0-preview.3.21167.1
  Commit:  0f64b267ac

.NET SDKs installed:
  6.0.100-preview.3.21173.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.3.21172.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21167.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21172.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by dandanmu** [comment]
Note repro on Main/31130.334(16.10 preview 2) + 6.0.100-preview.3.21180.8(runtime-6.0.0-preview.3.21179.3)

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/installer/issues/10013
