### ISSUE TITLE
With net6.0 preview 3, reductant *.dylib files  are generated when publish single file with RID(osx-x64) 

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#16511]
Repro steps:
Install .NET 6 SDK(6.0.100-preview.3.21173.9) from master branch of https://github.com/dotnet/installer
run dotnet new console in cmd.
Publish single file with below command
dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

Expected Result
Will only generate generate the single-file app and *.pdb file.

Actual Result:
Reductant *.dylib files are generated
![image](https://user-images.githubusercontent.com/65637796/112439374-fffdfe00-8d83-11eb-8fcf-8c5d79f151d0.png)

dotnet --info

.NET SDK (reflecting any global.json):
Version: 6.0.100-preview.3.21173.9
Commit: e627233d2d

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19042
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-preview.3.21173.9\

Host (useful for support):
Version: 6.0.0-preview.3.21167.1
Commit: 0f64b267ac

.NET SDKs installed:
6.0.100-preview.3.21173.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-preview.3.21172.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-preview.3.21167.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.3.21172.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by adrianord** [comment]
I'm having the same issue with .net 5

```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/aordonez/.dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.205 [/home/aordonez/.dotnet/sdk]
  5.0.301 [/home/aordonez/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/home/aordonez/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/home/aordonez/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/home/aordonez/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/home/aordonez/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by dsplaisted** [comment]
This appears to have been fixed in more recent previews of .NET 6.  Let us know if you still encounter this.
