### ISSUE TITLE
Make "dotnet list package" also list packages referenced as MSBuild project SDKs

### ISSUE THREAD

**Issue by zkat** [dotnet/sdk#16523]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @KalleOlaviNiemitalo.

---

_From @KalleOlaviNiemitalo on Friday, March 19, 2021 7:08:00 AM_

## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: .NET SDK 5.0.201

Worked before? If so, with which NuGet version: AFAIK, no

## Repro steps and/or sample project

demo.msbuildproj references [Microsoft.Build.NoTargets/2.0.1](https://www.nuget.org/packages/Microsoft.Build.NoTargets/2.0.1) as an [MSBuild project SDK](<https://docs.microsoft.com/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017#how-project-sdks-are-resolved>):

```XML
<Project Sdk="Microsoft.Build.NoTargets/2.0.1">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="docfx.console" Version="2.56.6" ExcludeAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

</Project>
```

Run the command `dotnet list demo.msbuildproj package`.  Output:

```
Project 'demo' has the following package references
   [netstandard2.0]:
   Top-level Package             Requested   Resolved
   > docfx.console               2.56.6      2.56.6
   > NETStandard.Library   (A)   [2.0.3, )   2.0.3

(A) : Auto-referenced package.
```

I'd like to see `Microsoft.Build.NoTargets 2.0.1` included in the output, for license audit purposes.

### Verbose Logs

Adding `--verbosity diag` does not change the output.

**Comment by zkat** [comment]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @heng-liu.

---

_From @heng-liu on Monday, March 22, 2021 10:55:00 PM_

My understanding is, [MSBuild project SDKs](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019) is a different concept from PackageReferrence, although project SDKs is also a package.
For now, dotnet list package command only works with the PackageReferrence property in msbuild file but not Sdks property.

**Comment by zkat** [comment]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @KalleOlaviNiemitalo.

---

_From @KalleOlaviNiemitalo on Tuesday, March 23, 2021 2:47:45 AM_

@heng-liu do you mean I should file this feature request at dotnet/msbuild instead?

**Comment by zkat** [comment]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @heng-liu.

---

_From @heng-liu on Tuesday, March 23, 2021 4:40:26 AM_

Hi @KalleOlaviNiemitalo , actually we own the `dotnet list package` command. 
Although NuGet has integrated into MSBuild,  we don't read `Sdk ` property for this command. 
I'm not sure how much effort do we need to implement getting 'Sdk' property in this command.

May I know why do you propose for this feature? Thanks.

**Comment by zkat** [comment]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @KalleOlaviNiemitalo.

---

_From @KalleOlaviNiemitalo on Tuesday, March 23, 2021 5:04:16 AM_

I'd have a build agent list the SDKs and other packages used by a project, and then automatically verify that those packages are approved by the enterprise and that their license terms have not changed. It would also be interesting to know if the SDK version has been declared as vulnerable.

If this is difficult to implement in "dotnet list package", then an alternative might be to define an environment variable that points to a file, and make the NuGet MSBuild SDK resolver read the environment variable and append the name and resolved version of each SDK to that file.

**Comment by zkat** [comment]
---
**Issue moved from NuGet/Home#10669**
- Please respond to @JonDouglas.

---

_From @JonDouglas on Tuesday, March 23, 2021 2:22:41 PM_

@KalleOlaviNiemitalo You might be requesting a different type of list feature here. Maybe you can open a discussion on https://github.com/dotnet/sdk or https://github.com/dotnet/msbuild. I'd start with dotnet/sdk as they own the overall CLI experience & may have ideas as to where this makes most sense for custom SDKs. 

Perhaps something like a `dotnet list project` or similar?

**Comment by tamasvajk** [comment]
A nuget package can [define](https://docs.microsoft.com/en-us/nuget/reference/nuspec#framework-reference-groups) `frameworkReferences`, as far as I see those are also "MSBuild project SDKs". Is there a way to query those through the CLI? (`dotnet list package` doesn't return them.)

**Comment by tamasvajk** [comment]
Just for future reference, I came across `dotnet msbuild -preprocess:full.csproj`, and was hoping that I can run `dotnet list package` on it to see the output, but the preprocessing output doesn't build. :-(

**Comment by JonDouglas** [comment]
Perhaps an API exists? I'm not really familiar with the MSBuild portions of the CLI, but it suggests this might already be available?

https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tasks/Microsoft.NET.Build.Tasks/CollectSDKReferencesDesignTime.cs#L22

I believe this mostly becomes a MSBuild question of if NuGet can consume that API or is sufficient enough for `dotnet list package` to display project SDKs or not. Does it belong in that command or should it be it's own standalone is another question.

https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#how-project-sdks-are-resolved

**Comment by KalleOlaviNiemitalo** [comment]
I had originally filed this feature request as <https://github.com/NuGet/Home/issues/10669>, but that was then copied to this <https://github.com/dotnet/sdk/issues/16523>, closed, and locked. Now that you're saying the feature request belongs to the NuGet repository after all, can you please unlock and reopen <https://github.com/NuGet/Home/issues/10669>?
