### ISSUE TITLE
Workload unzip nupkg should preserve executable permission for user level on unix

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#16566]
If there is an executable in the workload payload. We need to be able to let it **run** without sudo (not install, install require sudo is expected) after installed on the machine.

PackageExtractor would perverse the executable permission. However, if the user want to install to  /usr/share/local/dotnet/. The _dotnet workload install_ command need to run in _sudo_. However, the executable permission would only be for root instead of the **user**. As a result, the user cannot **run** the program without **sudo**. 

work around in shell
_so right now I use NuGet's PackageExtractor class to unpack to var temp = Path.GetTempPath() and then I do a Process.Start("/bin/zsh", $"-c 'sudo mkdir -p \"{destination}\" && sudo cp -pPR \"{temp}\" \"{destination}\"'");_

**Comment by mhutch** [comment]
It looks like NuGet doesn't preserve the permissions, it just makes all the files executable by [hardcoding all file permissions to chmod 766](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/NuGetExtractionFileIO.cs#L51) i.e. everyone can read/write and owner can execute.

Allowing everyone to write the files is clearly a security problem, and it would be a bad experience on multiuser machines if only the user who ran the installer could run .NET SDK executables.

I imagine what we actually want is to have the files owned by root and use something like 755 i.e. owner can write, everyone can read and execute. Ideally we would also only set the execute bit for actual executables.

**Comment by wli3** [comment]
dotnet/sdk#16894
