### ISSUE TITLE
dotnet new --install does not return an Error Code on exit

### ISSUE THREAD

**Issue by doron-nathan-epstein** [dotnet/sdk#16637]
I am currently building some automation around the .NET CLI using PowerShell and some other bits. 

Within my domain, we require authentication to retrieve packages from our AzDO package feed (uses a PAT Token under the hood to authenticate). If these credentials are not provided, or are invalid, the CLI correctly shows a 401 Unauthorized error. However, there is no Error Code on the exit of the CLI, which means I have no data to respond to.

![image](https://user-images.githubusercontent.com/6659033/113108846-b854f780-9205-11eb-991d-f3cba419acfa.png)

I have gone through the [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new) but there are no additional arguments to use.

Is this the intended behaviour of the CLI?

**Comment by wli3** [comment]
You need https://github.com/microsoft/artifacts-credprovider

SDK should be neutral for the package feed provider, so we did not include Azure devops specific help

**Comment by vlada-shubina** [comment]
@doron-nathan-epstein we are aware of the issue of invalid (zero) exit code in case installation fails. We have fixed it for .NET 6 and it will be available in SDK .NET 6 Preview 4. Thanks
