### ISSUE TITLE
Regression in 15.5p1: Portable0.0 is skipped

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#1666]
I have an SDK project that the `MSBuild.Sdk.Extras` to build a legacy PCL target. This works in 15.4 but fails in 15.5 preview 1.

In the IDE in 15.4, I see this:

![image](https://user-images.githubusercontent.com/1427284/31748017-3c8bca6e-b43e-11e7-95a1-533476d1a1bf.png)

In 15.5 p1 I see this:

![image](https://user-images.githubusercontent.com/1427284/31748043-63688352-b43e-11e7-8354-d5b0d9068d27.png)
Note that the `Portable0.0` entry representing `portable-net4+sl5+wp8+win8+wpa81` is missing.

This is a blocker.

Building in the IDE in 15.5 p1 also yields the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The TargetFramework value 'portable-net4+sl5+wp8+win8+wpa81' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	crypto	C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	96	
```
This is incorrect as the TFI and TFV is set by the MSBuild.Sdk.Extras package.

Repro is https://github.com/onovotny/bc-csharp/tree/e55eb138bf5492769ec1cf2212b49f223e377145
Open the BouncyCastle.sln

/cc @nguerrera

**Comment by livarcocc** [comment]
@dsplaisted and @nguerrera can one of you take a look at this?

**Comment by nguerrera** [comment]
Looking

**Comment by nguerrera** [comment]
@davkean @emgarten I believe this is either a project system or nuget issue. There are no SDK changes between 15.4 and 15.5 preview 1 and things work as before on the command line. Something is either causing the project to get evaluated without the MSBuildSdkExtras targets setting TFI and TFV, but only in the IDE. Moving to project system for next look.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/project-system#2910
