### ISSUE TITLE
_OR_GREATER defines should also work in .NET Standard

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#16699]
With #14798 we added support for `_OR_GREATER` defines for the TFM. The [spec](https://github.com/dotnet/designs/blob/main/accepted/2020/or-greater-defines/or-greater-defines.md#goals) said it should apply to .NET Core, .NET 5 (and higher), .NET Framework, **and .NET Standard**.

However, it seems the PR didn't add support for .NET Standard. Can we add this?

/cc @sfoslund @dsplaisted 

**Edit** It appears this works in the .NET 6 SDK but doesn't work in .NET 5 SDK 5.0.200.

**Comment by sfoslund** [comment]
@terrajobst we noticed this in February and added it to 5.0.300: https://github.com/dotnet/sdk/pull/15660

**Comment by terrajobst** [comment]
Awesome, looks like it has been taken care of then.
