### ISSUE TITLE
global.json blocks me from seeing the version of dotnet

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1673]
Experimenting with a new version of dotnet CLI on my Mac today. After installing when running restore I get the following error:

``` txt
The specified SDK version [2.0.0] from global.json [/Users/jaredpar/code/roslyn/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Okay. Probably need to update my global.json. Lets try running `-?` or `-help` to see what version this dotnet thinks it is 

``` cmd
>dotnet -?
The specified SDK version [2.0.0] from global.json [/Users/jaredpar/code/roslyn/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Feel like I should be able to see the version of dotnet, no matter what the value is in global.json. In particular so I can update the value in global.json.

**Comment by livarcocc** [comment]
I believe we can augment this error message to display the different versions of the SDK we found (if any). I will move this issue to core-setup, since this will have to be implemented in the host.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3344
