### ISSUE TITLE
sdk:5.0 latest tag fails to restore project targeting netcoreapp3.1

### ISSUE THREAD

**Issue by kennygea** [dotnet/sdk#16765]
### Describe the Bug

Since the release of the newest dotnet sdk tag, `5.0.202`, our projects have been failing to restore projects that are targeted at `netcoreapp3.1`

Error:
```
--------------------------------------------------------------------------------------
12:38:37  Determining projects to restore...
12:39:03  MyApp.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-x64 with version (= 3.1.14)
12:39:03  MyApp.csproj : error NU1102:   - Found 45 version(s) in nuget.org [ Nearest version: 5.0.0-preview.1.20120.5 ] 
12:39:03  MyApp : error NU1102:   - Found 0 version(s) in Rev.com myget
```

csproj
```
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
  </PropertyGroup>
```

Reverting back to explicit `sdk:5.0.201` tag fixes this behavior

### Steps to Reproduce

Using latest docker tag `sdk:5.0`, `sdk:5.0-latest`, `sdk-5.0.202`, try to restore a project targeted at netcoreapp3.1

**Comment by mthalman** [comment]
This isn't Docker-specific.  I can repro this by installing 5.0.202 on my local machine, create a .NET project targeting .NET Core 3.1 and build.  Gives me this error:

![image](https://user-images.githubusercontent.com/15789599/113775634-a2a46e00-96ee-11eb-9c6b-fb986e466ce9.png)

cc @marcpopMSFT

**Comment by marcpopMSFT** [comment]
Same as https://github.com/dotnet/sdk/issues/16758. We released 5.0.202 early to unblock a Linux scenario but we needed to have pushed the 3.1 packages to nuget at the same time. I'm working with @rbhanda to get those packages published to unblock this.

**Comment by rbhanda** [comment]
We have published 3.1.14 nuget packages. Please let us know if this issue is resolved.

**Comment by mthalman** [comment]
> We have published 3.1.14 nuget packages. Please let us know if this issue is resolved.

I see it resolved with my local VS build scenario.

**Comment by ChaosEngine** [comment]
Yes, docker build succeeds now. Thank you.

**Comment by judep90** [comment]
Can confirm fix

**Comment by richlander** [comment]
We'll close this in the morning if we don't hear any other reports.

**Comment by kennygea** [comment]
Issue is fixed on my end. Thanks for the quick update!
