### ISSUE TITLE
Support conflict resolution for `@(Analyzer)`s

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#16772]
Related to https://github.com/dotnet/designs/pull/181

Regardless of how we ultimately decide to ship inbox source-generators / analyzers we will need to be able to conflict resolve between inbox components and those delivered in NuGet packages.  This should happen after items are raised from nuget packages, after frameworks are resolved (in case we do add support for framework-specific generators/analyzers), after any SDK adds them, and before compile.

This is needed for .NET 6.0 to accommodate components adding source generators which ship in both nuget packages and inbox.

cc @dsplaisted

**Comment by dsplaisted** [comment]
@marcpopMSFT 

Relatedly (and I'm not sure if there's an issue filed for it), we'll need to resolve analyzers from targeting packs.

**Comment by ericstj** [comment]
> Relatedly (and I'm not sure if there's an issue filed for it), we'll need to resolve analyzers from targeting packs.

This one is still TBD.  I'm hoping to have a discussion to close on that once folks are back in the office next week.

**Comment by ericstj** [comment]
Just wanted to let you know that this is still needed and something we're very soon going to run into regardless of where we put the generators inbox.  Can we start working on this?  I'm happy to collaborate.

**Comment by ericstj** [comment]
> That one is still TBD. I'm hoping to have a discussion to close on that once folks are back in the office next week.

We've decided that we wish to enable this option, and given the similarity of these I'll group them in a single issue.  Draft PR that implements this is here: https://github.com/dotnet/sdk/pull/18501

**Comment by ericstj** [comment]
Fixed in #18501
