### ISSUE TITLE
build.cmd script didn't create dotnet installation to artifacts\tmp\Debug\dotnet on Windows

### ISSUE THREAD

**Issue by kartheekp-ms** [dotnet/sdk#16785]
Reference: https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md

- Clone https://github.com/dotnet/sdk repo.
- Executed `build.cmd` from the root repository.
- The build script **didn't** output `dotnet` installation to `artifacts\tmp\Debug\dotnet` folder. 

I tried above steps on 2 machines and observed the same behavior.

``` log
Directory of c:\repos\sdk\artifacts\tmp\Debug

04/07/2021  08:30 PM    <DIR>          .
04/07/2021  08:30 PM    <DIR>          ..
04/07/2021  08:30 PM    <DIR>          .dotnet
04/07/2021  08:25 PM               363 Directory.Build.props
04/07/2021  08:25 PM               367 Directory.Build.targets
04/07/2021  08:25 PM             1,182 NuGet.config
04/07/2021  08:30 PM    <DIR>          testpackages
               3 File(s)          1,912 bytes
               4 Dir(s)  590,032,470,016 bytes free
```

**Comment by kartheekp-ms** [comment]
I created a new Windows VM and tried above steps but no luck :(

**Comment by kartheekp-ms** [comment]
I searched for `dotnet.exe` in my repo root directory which yielded following results.

- sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App\1.0.5\dotnet.exe
- sdk\.dotnet\shared\Microsoft.NETCore.App\1.0.5\dotnet.exe
- sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App\1.1.2\dotnet.exe
- sdk\.dotnet\shared\Microsoft.NETCore.App\1.1.2\dotnet.exe
- sdk\artifacts\bin\redist\Debug\dotnet\dotnet.exe
- sdk\.dotnet\dotnet.exe

`dotnet.exe` was not generated in the location specified in the developer guide.

**Comment by sfoslund** [comment]
Thanks for pointing this out, the path should be updated to `sdk\artifacts\bin\redist\Debug\dotnet\dotnet.exe`, I'll make a PR.
