### ISSUE TITLE
SDK 5.0.202 breaks running projects targeted netcoreapp3.1 on Linux/Debian

### ISSUE THREAD

**Issue by padtm** [dotnet/sdk#16791]
Akin to #16758 and #16765, when running a project with `<TargetLatestRuntimePatch>` set to `true`, e.g.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <!-- <RuntimeFrameworkVersion>3.1.13</RuntimeFrameworkVersion> -->
  </PropertyGroup>
  ...
</Project>
```

Will yield the following when doing `dotnet run`:

    It was not possible to find any compatible framework version
    The framework 'Microsoft.AspNetCore.App', version '3.1.14' was not found.
      - The following frameworks were found:
          2.1.26 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
          2.2.8 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
          3.1.13 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
          5.0.5 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    
    You can resolve the problem by installing the specified framework and/or SDK.
    
    The specified framework can be found at:
      - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.14&arch=x64&rid=debian.10-x64
  
Commenting out the `<TargetLatestRuntimePatch>` OR pinning the runtime version by uncommenting the `<RuntimeFrameworkVersion>` will let it run successfully.

I tracked it down to be the `/usr/share/dotnet/sdk/5.0.202/Microsoft.NETCoreSdk.BundledVersions.props` file (line 216 in my case), that stated `LatestRuntimeFrameworkVersion="3.1.14"`, while the latest available 3.1 runtimes (and package version for `dotnet-runtime-3.1` and `aspnetcore-runtime-3.1`) are `3.1.13` as of the time of writing.

So there's clearly a mismatch here.

**Comment by marcpopMSFT** [comment]
We released 5.0.202 early but didn't include the 3.1 packages.  3.1.14 has now released so this should be resolved.
