### ISSUE TITLE
.NET SDK 5.0.202 - selects 3.1.14 framework for netcoreapp3.1 apps when TargetLatestRuntimePatch=true

### ISSUE THREAD

**Issue by chrisdMSFT** [dotnet/sdk#16795]
After moving form 5.0.201 to 5.0.202 our netcore3.1 x64 apps started having the "The framework 'Microsoft.NETCore.App', version '3.1.14' was not found." error, which we confirmed was set in the runtime config.

I was able to boil down the repro to three simple steps.

## Install 5.0.202 (install 5.0.201 to see it work)
```
> dotnet new console
```

## Set the Framework to netcoreapp3.1 and to Platform to x64:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>repro_1</RootNamespace>
    <Platform>x64</Platform>
  </PropertyGroup>
</Project>
```
## Build and run (repro):
```
G:\repro-1>dotnet run
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.14' was not found.
  - The following frameworks were found:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.14&arch=x64&rid=win10-x64
```

**Comment by chrisdern** [comment]
Seems like pushing the 3.1.14 to the nuget feed [#16758 ] fixed the build but has some edge cases when setting an explicit platform.

**Comment by marcpopMSFT** [comment]
The runtime config for you lists 3.1.14 explicitly?  Can you collect and send me an https://aka.ms/binlog?  I tried your repro on a machine with just 5.0.202 and got the runtime set to 3.1.0 as expected. I'm wondering if you have a directory.build.props on your machine affecting your build potentially.
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    }

**Comment by chrisdMSFT** [comment]
So my repro methodology was incorrect. I think I found the real problem (which seems very related)

`<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`

Repro with binlog attached. (go.cmd)

[repro-1.zip](https://github.com/dotnet/sdk/files/6280596/repro-1.zip)

**Comment by sfoslund** [comment]
> I think I found the real problem

Has this issue been fixed then? If not, is it possible you have a nuget.config file that does not contain nuget.org that could be causing the issue?

**Comment by chrisdMSFT** [comment]
Awesome! So we point to an internal ADO feed, which upstreams nuget.org (best I can  tell).

![image](https://user-images.githubusercontent.com/73906532/114747383-a135ff80-9d05-11eb-84ac-1746918e72d7.png)

I can try again and see if its updated now.

**Comment by chrisdMSFT** [comment]
I have confirmed it is now fixed.
