### ISSUE TITLE
[Windows ARM64]The description display incorrectly on 3.1.408 SDK installation UI.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/sdk#16805]
Repro steps:
1.	Download and Double-click dotnet-sdk-3.1.408-win-arm64.exe on windows ARM64 machine.
2.	The description should be displayed well on installation UI and when installation is done, check UI displayed.
 
Actual Result
The description display incorrectly on installation UI.
![image](https://user-images.githubusercontent.com/65638819/114119329-014f2f00-991d-11eb-9c52-423965cca026.png)
".NET" should be displayed as ".NET Core"  and  Should not display about dotnet5 link, should display about net core 3.1 link
![image](https://user-images.githubusercontent.com/65638819/114120388-f72e3000-991e-11eb-8398-cd6378e7a661.png)

**Comment by marcpopMSFT** [comment]
Fixed in internal PR.
