### ISSUE TITLE
Set proper exit code on `dotnet list package --vulnerable` to enable usage in CI pipelines

### ISSUE THREAD

**Issue by rajbos** [dotnet/sdk#16852]
Running `dotnet list package --vulnerable` does not use the exit code to indicate issues. I'd think vulnerable packages with medium / high severity would at least be returned with an exitcode <> 0. 

## Usage example:
I want to include this command in our CI pipeline to enable a shift left mentality and warn us earlier about possible vulnerabilities. Currently the only option I see is parsing the result for something like ` has the following vulnerable packages`.

Alternatively I can image adding a parameter to return either a number of vulnerable packages (that we can then test to larger then 0) or a json object we can parse the right way to look for the numbers per severity.

I've been searching the source code but could not find where to look for the exit code setup 😁 .

**Comment by thefringeninja** [comment]
We're currently using `dotnet-retire` in our build pipeline. The author is no longer maintaining the list of vulnerable packages and instead suggests we use this (RetireNet/dotnet-retire#75). However, as `dotnet list packages --vulnerable` returns `0` when it finds vulnerable packages, this doesn't really work in CI without hacks.

@rajbos this feature was added in dotnet/sdk#13318. It looks like this is just being forwarded to NuGet.

**Comment by omajid** [comment]
Comparing this with npm, `npm audit` sets an appropriate exit code if it finds vulnerable packages with a certain class of vulnerabilities: https://docs.npmjs.com/cli/v8/commands/npm-audit#exit-code

**Comment by PSanetra** [comment]
This was quite unexpected. We will now check the output for `has the following vulnerable packages`, but fingers crossed that this output does not change in future versions. :crossed_fingers:

**Comment by omeryesil** [comment]
This is really disappointing, I can't really recall but there was another dotnet call that really doesn't work well with DevOps scripts. In today's world the automation capability must be a first class citizen.

@PSanetra , about covering multiple projects,  we can check `has the following vulnerable packages` instead of `has no vulnerable packages`. If there is any vulnerabilities found in a solution we will catch it..

**Comment by PSanetra** [comment]
@omeryesil The problem with checking for `has the following vulnerable packages` is that our script may break silently if the phrase changes with a new dotnet version.

**Comment by omeryesil** [comment]
> 

@PSanetra  totally agree with you, but i think it is the only way at the moment unless we use another tool like sonarqube, synk, etc..

**Comment by mrjoops** [comment]
Hi,

As a workaround, I use these lines to make my (linux-based) CI work:
```
dotnet list package --vulnerable --include-transitive | tee vulnerable.out
test `grep -cm 1 'has the following vulnerable packages' vulnerable.out` = 0
```
So yes, it may break with future dotnet versions but since I'm very optimistic, I hope dotnet will implement a correct return code so my added line will never be executed 😉.

**Comment by aortiz-msft** [comment]
@JonDouglas - This sounds related to the "nuget audit" command that you are thinking of.

**Comment by JonDouglas** [comment]
Hi all,

I wrote a proposal for this sometime last year I published a couple months ago. If this would fill the gap, please upvote or comment appropriately

https://github.com/NuGet/Home/pull/11549

Thanks!

**Comment by Evertvdw** [comment]
To add to this discussion, I found this issue and adopted @mrjoops answer a bit. The echo parts are specific for Azure pipelines, but it might be helpful to others:

```bash
dotnet restore
dotnet list package --vulnerable --include-transitive | tee vulnerable.out
vulnCritical=`grep -o -i 'Critical' vulnerable.out | wc -l`
vulnHigh=`grep -o -i 'High' vulnerable.out | wc -l`
vulnModerate=`grep -o -i 'Moderate' vulnerable.out | wc -l`
vulnLow=`grep -o -i 'Low' vulnerable.out | wc -l`
vulnTotal=`grep -o -i 'Critical\|High\|Moderate\|Low' vulnerable.out | wc -l`
if [[ $vulnTotal != 0 ]]; then
  echo "##vso[task.logissue type=error;]There are vulnarabilities found: Critical($vulnCritical) - High($vulnHigh) - Moderate($vulnModerate) - Low($vulnLow)"
  echo "##vso[task.complete result=Failed;]Text"
fi
```

**Comment by vernou** [comment]
Why this issue is closed? In GitHub, I see only "This issue was closed." without detail.

**Comment by jvmap** [comment]
@Evertvdw Thanks for sharing. I found this quite useful, as for some reason Azure DevOps still does not support email notifications for new security alerts. I guess they expect you to scroll through all your repositories every day, as if you have nothing better to do?

I modified your script slightly:
```
dotnet restore
dotnet list package --vulnerable --include-transitive | tee vulnerable.out
vulnCritical=`grep -o -i -w 'Critical' vulnerable.out | wc -l`
vulnHigh=`grep -o -i -w 'High' vulnerable.out | wc -l`
vulnModerate=`grep -o -i -w 'Moderate' vulnerable.out | wc -l`
vulnLow=`grep -o -i -w 'Low' vulnerable.out | wc -l`
vulnTotal=`grep -o -i -w 'Critical\|High\|Moderate\|Low' vulnerable.out | wc -l`
if [[ $vulnTotal != 0 ]]; then
  echo "##vso[task.logissue type=error;]There are vulnarabilities found: Critical($vulnCritical) - High($vulnHigh) - Moderate($vulnModerate) - Low($vulnLow)"
  echo "##vso[task.complete result=Failed;]Text"
fi
```
The addition of `-w` for the `grep` commands greatly reduces the chance of false-positives being generated.
Maybe `-i` should be removed as well.
