### ISSUE TITLE
Microsoft.CSharp package restored with SDK 2.0.0, but not 2.1.1

### ISSUE THREAD

**Issue by jcouv** [dotnet/sdk#1686]
Repro:
1. Enlist to Roslyn repo on Linux (for this I used Docker and `docker run -it ubuntu bash`, then installed git with `apt-get update`, `apt-get install git`, then `git clone https://github.com/dotnet/roslyn.git`)
3. From a clean repo (`git clean -xdf`), select an SDK with configuration in `build/Targets/Tools.props` and `global.json`. We'll use "2.0.0" and "2.1.1-preview-007094".
4. Obtain dotnet by installing [pre-requisites](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x) (`apt-get install libunwind8 liblttng-ust0 libcurl3 libssl1.0.0 libuuid1  zlib1g libicu55 curl`) then `./build/scripts/obtain_dotnet.sh`, then update your PATH with `PATH=$PATH:./Binaries/dotnet-cli/`
5. Restore with `./build/scripts/restore.sh`
6. Check the `/root/.nuget/packages/microsoft.csharp/4.3.0/ref/netstandard1.0/Microsoft.CSharp.dll` (`ls /root/.nuget/packages/microsoft.csharp/4.3.0/ref/netstandard1.0/Microsoft.CSharp.dll`)

When using SDK 2.0.0, the file is present.
When using SDK 2.1.1, the file is absent (it is only found in the fallback nuget folder).

For context, the reason for this is that some Roslyn tests need those ref assemblies in the test output folder, as they will be used when the test needs to make a compilation referencing those ref assemblies. This makes me wonder if we should consider the same "ref capture" mechanism that is used by ASP.Net Core.

**Comment by nguerrera** [comment]
@livarcocc

**Comment by livarcocc** [comment]
@emgarten any ideas why this packaged would be copied for 2.0 at all? It is present in the archive and the fallback folder.

When I tried a simple project referencing Microsoft.CSharp directly and restore passing --packages, I do not get this package in the packages folder, even for 2.0.0.

This should never have worked for 2.0, so, if the package is not showing up in the packages folder for 2.1.1, I would say that now we are doing the right thing.

**Comment by livarcocc** [comment]
I see that DisableImplicitNuGetFallbackFolder is now set in Roslyn and with it the package is present in the packages folder, as expect.

Given that the 2.1.1 behavior is the correct one, I am going to go ahead and close this issue.

**Comment by jcouv** [comment]
@livarcocc The reason I'd filed this issue is because this change of behavior was unexpected. Did you understand what caused the change?
Is there an issue tracking the root cause, so that we can remove the DisableImplicitNuGetFallbackFolder workaround from Roslyn? 
Or are you saying the current behavior is by-design and the previous behavior was incorrect?

**Comment by livarcocc** [comment]
This is exactly what I am saying. This is expected. This is the correct behavior from NuGet.

When using the --packages parameter, NuGet will not copy packages that are present in the NuGetFallbackFolder, which is the case here. 2.1.1 has the correct behavior.

If you want to restore and copy packages from that location, you need to disable the fallback folder, which is what you are doing.
