### ISSUE TITLE
Given data/UnixFilePermissions.xml in pack nupkg, when extract package, nuget package extractor can set executable permission according to the file

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#16894]
We need to define data/UnixFilePermissions.xml format. And make sure when elevated in root. _User_ should have the permission to execute too. (755)

**Comment by wli3** [comment]
Proposed file format @jonathanpeppers @dsplaisted what do you think?

```xml
<FileList>
  <File Path="tools/Darwin/mono" Permission="755"/>
  <File Path="tools/Darwin/other" Permission="755"/>
</FileList>
```

**Comment by dsplaisted** [comment]
LGTM

**Comment by jonathanpeppers** [comment]
Yes, I think this will work, thanks. @rolfbjarne any opinions?

**Comment by rolfbjarne** [comment]
LGTM

**Comment by directhex** [comment]
Was this closed by https://github.com/dotnet/sdk/pull/18241 ?
