### ISSUE TITLE
Docker run command throws an error - "It was not possible to find any compatible framework version The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.   - No frameworks were found."

### ISSUE THREAD

**Issue by tharishk** [dotnet/sdk#16904]
Hello All, 
I have created a sample .NETCORE web API, and I'm trying to deploy to docker, 
I get errors "
**It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=debian.10-x64**
" 

could some one help on how to resolve this. as I m trying to learn Docker

Below screenshot of docker file and error from Visual Studio
Docker File content
![image](https://user-images.githubusercontent.com/11506633/114718690-dbc68900-9d53-11eb-9775-7eefb58027e3.png)

list of runtimes Installed in my machine.

![image](https://user-images.githubusercontent.com/11506633/114718962-2942f600-9d54-11eb-80af-3b334213847f.png)

**Comment by tharishk** [comment]
Can someone guide me on the query please

**Comment by marcpopMSFT** [comment]
@dleeapho any guidance on docker?

**Comment by tharishk** [comment]
marcpopMSFT, I have resolved the error, I have Installed  the 5.0.2 and 5.0.5 version runtime and SDK, I have Installed  5.0.0 version SDK and runtime it worked...
