### ISSUE TITLE
Support signing assemblies in a single-file bundle

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#16939]
Problem: Many users split their build such that they build on one machine, then perform post-build steps, like signing, on another machine. Single-file publishing currently uses the project publishing itself to create a bundle, meaning that there is no way to split the bundling across multiple machines, with the bundling machine using output from another process.

The only way to support this scenario seems to be to allow bundling to operate without rebuilding, using files that have already been created and copied. The other question is how to get the appropriate binaries in the first place, given that the output of a standard publish is not the same as the output used for bundling. There seem to be two obvious approaches here:

1.  Support "delay bundling" where we gather all the files we would use for single-file bundling, but output them to a directory instead of bundling
 2.  Support unbundling, so users could bundle as a single file, but later extract all the files, perform arbitrary post-processing, then rebundle.

Right now I think (2) is both more flexible and cheaper to implement, but I could be persuaded otherwise.

My proposed UX is:

~We add a new verb:~

Edit: new verb seems too permanent right now. An MSBuild target is probably sufficient.

**Comment by agocke** [comment]
@vitek-karas @VSadov for technical design

@samsp-msft for user scenario + UX

**Comment by VSadov** [comment]
This was resolved in https://github.com/dotnet/sdk/pull/18794
