### ISSUE TITLE
dotnet restore --interactive broken

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/sdk#16930]
How to test anger management of your developers:

1. Use Azure DevOps
2. Use NuGet feed from Azure DevPoops
3. Enable password expiry for users
4. Add NuGet package from private Azure DevPoops feed
5. User has to authenticate via `dotnet restore --interactive`
6. Works for a while until password expires
7. Now `dotnet restore` fails with a `401`
8. User tries to run `dotnet restore --interactive` again but instead of initiating auth process keeps getting `401`
9. User gets angry and punches a hole into the wall
10. User comes to GitHub and files issue with the hope that all of this bullshit will work for once in a while

**Comment by marcpopMSFT** [comment]
This issue was moved to microsoft/artifacts-credprovider#245
