### ISSUE TITLE
How to prevent all pdb and xmldoc files into public directory?

### ISSUE THREAD

**Issue by ahdung** [dotnet/sdk#16986]
A asp.net core 5.0 project, referenced anothor project(call B). when publish finished, the `public` folder has `B.pdb` and `B.xml`, `DebugType=None` seems only work for main project. please help.

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/sdk/issues/16975

**Comment by wli3** [comment]
close as duplication of https://github.com/dotnet/sdk/issues/16975
