### ISSUE TITLE
dotnet pack doesn't build when "Generate NuGet Pkg on Build"

### ISSUE THREAD

**Issue by robertmuehsig** [dotnet/sdk#1698]
The documentation tells me that "dotnet pack" should build the project (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x) 

Unfortunatly this behaviour is missing if I enable the "create nuget package on build":

![image](https://user-images.githubusercontent.com/756703/32148454-975bd2b0-bcf7-11e7-8b36-f08b26a20f63.png)

When I now execute dotnet pack, it fails:
![image](https://user-images.githubusercontent.com/756703/32148461-a740318a-bcf7-11e7-90e0-6f8e36c66f66.png)

Repo steps:

* Create a new .NET Core Lib
* Enable "Generate NuGet Package on build"
* run "dotnet pack" inside the lib folder

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#6118
