### ISSUE TITLE
 Add an option that allows the caller to explicitly point to the CLR to use for dotnet store

### ISSUE THREAD

**Issue by noahfalk** [dotnet/sdk#1699]
## Repro:

git clone https://github.com/JitBench
Follow the instructions in the README

## Observed behavior:

In step 3 while running AspNet-GenerateStore.ps1, dotnet store will be invoked that ultimately runs crossgen with coreclr and clrjit.dll loaded from the global NuGet cache. 

## Expected behavior:

dotnet store will resolve coreclr and clrjit the same way that dotnet run would, by using the coreclr/clrjit dlls that are present in the privately installed dotnet directory

## Environment

dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\github\JitBench\.dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

## Comments

The JITBench repo is attempting to provide a testing ground for coreclr and JIT changes that will affect the performance of both running code and generated images. However because of the unexpected resolution path of these binaries developers were only observing their changes at runtime, not at image generation time. Unless there is a particular reason I've missed to resolve the binaries differently, I think users would find the behavior far more intuitive and consistent if the resolution policies matched.

**Comment by nguerrera** [comment]
@eerhardt

**Comment by eerhardt** [comment]
A couple of comments:

1. You can run `dotnet store` for a runtime version that isn't installed in the `dotnet` folder.  For example, you only have `2.0.0` installed, and you `dotnet store` for `2.0.1` (and vice versa).  The idea here is to decouple the version of the runtime that the SDK runs on from the version of the runtime that your app/store/etc wants to use.
So a workflow could be:  download the .NET Core SDK and run `dotnet store --framework-version 2.0.1`, and it doesn't matter which .NET Core SDK you downloaded, you will always crossgen for 2.0.1.
2. For a self-contained app, the coreclr/clrjit binaries that are in the NuGet cache are used instead of the ones in the shared framework.
3. For a given version, the binaries in the shared framework will be identical to the ones in the NuGet cache with the same version.

**Comment by noahfalk** [comment]
Thanks @eerhardt its fair to say my expectations of the scenario were a bit off and I'm happy you've corrected it. In fact on further thinking I don't think dotnet run was the right comparison to make. In this scenario coreclr and clrjit represent the backend of a compiler. I think there is a fairly good comparison to Roslyn that can be made. When executing dotnet build we must select a version of Roslyn to use to compile C# code to IL. If you were compiling an ASP.NET app, the app would also reference Roslyn binaries so that they can be invoked at runtime. I'm guessing (and maybe you'll say I'm wrong ; ) that if I install the 2.0 SDK and then build an ASP.NET app targeting netcoreapp1.0:
- dotnet build uses the 2.0 version of Roslyn from the SDK to compile the C# source
- The app's NuGet dependencies chain back to the 1.0 version of Roslyn that will be used as the deployed runtime binary

However whether or not you decide such changes are appropriate/comparable... my more narrowly scoped request is to please provide a way so that our devs can make dotnet store use the version of coreclr/clrjit we want to test without having to modify our NuGet caches. Predicting how a given app will resolve through the NuGet cache is tricky, overwriting files in that cache can quickly leave the whole machine in a bad state if you forget to revert the changes, and modifying global machine state plays havoc on automated testing. For other parts of the test scenario we already overwrite the files in a private dotnet directory so the most convenient option would be if dotnet store used those same binaries with no extra steps. However if it takes extra environment variables, arguments to dotnet store, or file copies to non-global locations we could do those too.

Thanks!

**Comment by eerhardt** [comment]
OK, I'm understanding your scenario a bit more.  Adding an option that allows the caller to explicitly point to the CLR to use, makes sense to me.  That can be added.

FYI - even in your Roslyn compiler example above, there are scenarios where you can use the compiler coming from NuGet by referencing a new version of the `Microsoft.Net.Compilers` package.

**Comment by nguerrera** [comment]
We will only be investing in dotnet store so I am closing this.
