### ISSUE TITLE
workload manifest insertion authoring

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#17020]
SDK insert to VS should not have workload manifest
workload manifest insertion should be done by the workload author
However, standalone installer should chain manifest msis with SDK

**Comment by wli3** [comment]
@sfoslund you haven't done any insertion related work right?

**Comment by sfoslund** [comment]
> you haven't done any insertion related work right?

No, I haven't.

**Comment by marcpopMSFT** [comment]
This has been done for the baseline manifest package but we need a separate msi for each manifest.

**Comment by marcpopMSFT** [comment]
That work is tracked by #17789
