### ISSUE TITLE
After 6.0 Preview 4 SDK installed, the runtime version shows 6.0 Preview 5

### ISSUE THREAD

**Issue by v-lawu** [dotnet/sdk#17032]
Repro steps:
1. Install .NET 6.0 Preview 4 from Release/6.0.1XX-preview4 (6.0.x Runtime) branch in [installer](https://github.com/dotnet/installer).

After the installation complete, the SDK version shows 6.0 Preview 4, but other version shows '6.0 Preview 5'.

**ACTUAL**
![image](https://user-images.githubusercontent.com/12129698/115364151-ae675880-a1f5-11eb-88f6-7966d82eec01.png)

**Comment by marcpopMSFT** [comment]
Not all dotnet repos rebrand for the next release at the same time so you can get mismatches depending on the order they change.  Try again in a day or two.
