### ISSUE TITLE
[Area-CLI] dotnet add package with no version put version="*"

### ISSUE THREAD

**Issue by romaluca** [dotnet/sdk#17031]
Hi i' m using Directory.Packages.props for manage version of packages.
I have created also a script for create projects dinamically
For every project i add nuget packages. ex:
`dotnet  add project.csproj package --no-restore Newtonsoft.Json`

The problem this command generates:
<PackageReference Include="Newtonsoft.Json" Version="*" />
in csproj and the compilation generates this error:

> NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Newtonsoft.Json;

How can i do to generate the package without version attribute like this?
`<PackageReference Include="Newtonsoft.Json" />`

Thanks!

**Comment by romaluca** [comment]
Area-CLI

**Comment by decriptor** [comment]
I'm running into this issue as well. It'd be nice if it didn't add `Version="*"`. In my use case,
* Create a new simple console app
* Add a nuget package
* Run some tests
