### ISSUE TITLE
[Identity] SignInManager.PasswordSignInAsync always returns false to the RequiresTwoFactor property

### ISSUE THREAD

**Issue by abryzgin** [dotnet/sdk#17039]
Hello! After upgrading the project from core 3.1 to core 5, SignInManager.PasswordSignInAsync after successful authentication always returns false to the RequiresTwoFactor property, although the TwoFactorEnabled field in the database is true, EmailConfirmed - true. The only exception is the first authentication after registering a new user. During the first authentication after registering a new user, RequiresTwoFactor is still true and the system sends the code, but the second and subsequent times are always false.

**Further technical details**

- dot net sdk 5.0.202

**Comment by thohng** [comment]
Hi @abryzgin , for this API `SignInManager` class issues/questions should go on repository https://github.com/dotnet/aspnetcore

1. `SignInManager.PasswordSignInAsync` always required next step on 2FA if username and password are matched. You can see the source code here
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L363
and here
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L339-L341

2. In case dont have 2FA implemented yet, can workaround as this sample code:
```
var user = await signInManager.UserManager.FindByNameAsync(userName);
if (user == null)
{
    return SignInResult.Failed;
}
var attempt = await signInManager.CheckPasswordSignInAsync(user, password, lockoutOnFailure); // lockoutOnFailure=true, locked user if failed attempt reach 5 times
if (attempt.Succeeded)
{
    await signInManager.SignInAsync(user, isPersistent);   // isPersistent: remember me
}
return attempt;
```

Reference:
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/LockoutOptions.cs#L28
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L375-L411
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L202-L203

**Comment by thohng** [comment]
Furthermore, `TwoFactorEnabled` in DB should be `false` in case:
- you not implement 2FA
- Or user never success register 2FA before.

**Comment by abryzgin** [comment]
Thanks, opened an issue in the repository https://github.com/dotnet/aspnetcore
