### ISSUE TITLE
"console" template is missing

### ISSUE THREAD

**Issue by Raijinz** [dotnet/sdk#17097]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: macos

This is my first issue in GitHub, so I will try to cover the problem as much as I could.

I installed .NET Core SDK 3.1, as the tutorial says, and "dotnet" command works fine.
Until I enter "dotnet new console", and it says "Couldn't find an installed template that matches the input, searching online...", my hunch is that the template might be missing, so I run "dotnet new --list" and here it is:

Templates                                 Short Name      Language      Tags
ASP.NET Core with Angular                 angular         [C#]          Web/MVC/SPA
ASP.NET Core with React.js                react           [C#]          Web/MVC/SPA
ASP.NET Core with React.js and Redux      reactredux      [C#]          Web/MVC/SPA

When I try to install the "console" template, this error pops up:
/Users/raijin/.templateengine/dotnetcli/v3.1.201/scratch/restore.csproj : warning NU1603: Console 1.0.4 depends on Newtonsoft.Json (>= 12.0.0) but Newtonsoft.Json 12.0.0 was not found. An approximate best match of Newtonsoft.Json 12.0.1 was resolved.
/Users/raijin/.templateengine/dotnetcli/v3.1.201/scratch/restore.csproj : error NU1202: Package Console 1.0.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Console 1.0.4 supports: net46 (.NETFramework,Version=v4.6)
  Restore failed in 2.4 sec for /Users/raijin/.templateengine/dotnetcli/v3.1.201/scratch/restore.csproj.

I don't use Visual Studio 2019 for Mac. I only use Visual Studio Code (Version 1.44.2) with C# Extension, so I didn't think it would be a cause.

What should I do next?

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
Is this still an issue in 3.1.408 which is the newest version of the 3.1 SDK?  I'm going to go ahead and close this as it's nearly a year old so I'm going to assume it was an issue with a specific version of the SDK.
