### ISSUE TITLE
Wrong chinese translation for NETSDK1125

### ISSUE THREAD

**Issue by NateScarlet** [dotnet/sdk#17100]
https://github.com/dotnet/sdk/blob/fc40b651322a2ffa0c4c4a4e3e9c6d00cbebbd5f/src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf#L166-L167

the translate result means 'Only publishing to a single-file is supported for netcoreapp target'

it should be '仅 netcoreapp 目标支持发布到单个文件。'

**Comment by marcpopMSFT** [comment]
@wli3 @cristianosuzuki77 Can we hand edit the loc file or do we have to go through the loc process for one-offs like this?

**Comment by wli3** [comment]
no. @cristianosuzuki77 need to update their database, or it will be override back the next loc pass. And that's the only thing needed

**Comment by cristianosuzuki77** [comment]
Internal ticket created. Once the feedback is accepted by translators, the translation will come in a future PR and not via this ticket.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/commit/cb5e0c9c7522c539d4d49775b14f22a77e29091c
