### ISSUE TITLE
dotnet pack doesn't honor AppendTargetFrameworkToOutputPath in package structure

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/sdk#1717]
[This project](https://github.com/FakeItEasy/FakeItEasy/blob/8f649f313f8afaa35871475ca00ae94a55db91ec/src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj) used to produce the following package structure with the 1.0.4 SDK:

![image](https://user-images.githubusercontent.com/1864281/32543775-d0b3abc4-c476-11e7-9690-d58de230462d.png)

But with the 2.0.2 SDK, it produces this instead:

![image](https://user-images.githubusercontent.com/1864281/32543798-e903c2a4-c476-11e7-9cd2-df7916c9f368.png)

It looks like the `AppendTargetFrameworkToOutputPath` property is ignored by `dotnet pack`.

Is this change intentional? Is there a workaround?

**Comment by thomaslevesque** [comment]
Apparently, including the TFM in the path is [hard-coded](https://github.com/NuGet/NuGet.Client/blob/eb6fe311289908d5e1fe6f644030c704be2bc15c/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L142) and can't be disabled...

For the project I mentioned, it generates an analyzer packages that installs correctly in SDK-style projects, but not in classic csproj (the analyzer is not referenced).

**Comment by livarcocc** [comment]
@emgarten Is this something that NuGet relies on the SDK for or is NuGet doing its own path calculation for the folder under pack?

**Comment by emgarten** [comment]
I'm not completely sure if NuGet appends the TFM to $(BuildOutputTargetFolder) here, or how this is getting added. 

//cc @rohit21agrawal for pack

**Comment by thomaslevesque** [comment]
> I'm not completely sure if NuGet appends the TFM to $(BuildOutputTargetFolder) here, or how this is getting added.

From the [code I linked to](https://github.com/NuGet/NuGet.Client/blob/eb6fe311289908d5e1fe6f644030c704be2bc15c/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L142), it seems pretty clear that it does ;)

**Comment by livarcocc** [comment]
I agree with @thomaslevesque. It seems NuGet is the one that is doing this and not honoring the Append property.

**Comment by blairconrad** [comment]
> It seems NuGet is the one that is doing this and not honoring the Append property.

Does this mean that the issue should move to NuGet/NuGet.Client?

**Comment by emgarten** [comment]
This issue was moved to NuGet/Home#6184
