### ISSUE TITLE
SatelliteResourceLanguages doesn't filter resources from WindowsDesktop sdk on build

### ISSUE THREAD

**Issue by gulbanana** [dotnet/sdk#17184]
When using a RuntimeIdentifier to build standalone with UseWpf, the build output contains many folders like cs/, de/ etc - about 200 .resources.dll files total.

**Comment by marcpopMSFT** [comment]
@joeloff This check should be an or equal: https://github.com/dotnet/sdk/blob/d528d91e59e4e80161b16739964293e97bf0f9e4/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L129

@gulbanana We will filter as long as you have two or more listed so if you want none, you should do this:
`<SatelliteResourceLanguages>en;en</SatelliteResourceLanguages>`

**Comment by gulbanana** [comment]
great, thanks for the workaround
