### ISSUE TITLE
PrivateAsset PackageReferences causing framework dependencies to be dropped from the publish operation

### ISSUE THREAD

**Issue by jackj-msft** [dotnet/sdk#17218]
**Steps to Repro**
1. Create a new .NET Core 3.1 console application.
2. Publish a self-contained application.
3. This will result in version 4.7.1 of `System.Runtime.CompilerServices.Unsafe` to appear in the publish directory
4. Add the NuGet reference 
```csharp
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0">
    <PrivateAssets>All</PrivateAssets>
</PackageReference>
```
5. Repeat step number 2 and publish another self-contained application

_Expected_
6. Version 4.7.1 of `System.Runtime.CompilerServices.Unsafe` exists in the publish directory.

_Actual_
6. `System.Runtime.CompilerServices.Unsafe` is missing from the publish directory.

**Comment by wli3** [comment]
PrivateAssets should only control what compiler sees. It should not affect the output of the build. @nkolev92 any idea on this issue?

**Comment by nkolev92** [comment]
> It should not affect the output of the build. @nkolev92 any idea on this issue?

I think the publish flows looks at PrivateAssets incorrectly. Unfortunately changing that right now is a breaking change. 

I was able to find this dup issue on sdk side, https://github.com/dotnet/sdk/issues/1019

**Comment by jackj-msft** [comment]
Is the workaround for now to not have "PrivateAssets" in our projects?
Is this due to be fixed in the .NET 6 time frame?

**Comment by dsplaisted** [comment]
The workaround is to also specify `Publish="true"`, for example:

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.9.0">
    <PrivateAssets>All</PrivateAssets>
    <Publish>true</Publish>
</PackageReference>
```

More details here: https://github.com/dotnet/sdk/issues/1019#issuecomment-302560769
