### ISSUE TITLE
Better delete operation to avoid garbage

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#17237]
More context https://github.com/dotnet/sdk/pull/17233#issue-624647878

I believe it is anti virus want to scan files. If we need to delete as part of the roll back. The right thing should be retry with move to temp directory first (now I think we will still need temp directory in the dotnet/ folder, the alternative is to leave locked file in place and it would confuse the resolver). Use move instead of delete since it will either be successful or fail as a whole. And then delete it in the temp directory.

**Comment by sfoslund** [comment]
@wli3 I think this was fixed when we switched to using the $TEMP dir for extracting packages. Is there anything else here that is still outstanding or can this be closed?

**Comment by sfoslund** [comment]
Closing as I believe this was fixed, feel free to reopen if not.
