### ISSUE TITLE
ComboBox throws a StackOverflowException when an item is selected

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/sdk#1727]
I got the same error as this person on StackOverflow:

https://stackoverflow.com/questions/47228336/uwp-xaml-combobox-throws-a-stackoverflowexception-when-an-item-is-selected

If you select an item from the ComboBox when it is databound to the value field, it creates a deadlock and running off the stack.  This doesn't appear to be an issue with any of the other controls, including ones that use the same binding code like toggle button.

**Comment by livarcocc** [comment]
This is not a .net core project nor a .net core issue. Unfortunately, I am not sure where this issue should move to. If this is happening to you in VS, I would just suggesting submitting a feedback item for it.
