### ISSUE TITLE
Compiling Mvc's functional tests with 2.2 SDK targeting netcoreapp2.1 is compiled with PlatformTarget x64

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#1729]
The title is super specific because I wasn't able to reproduce this with a smaller sample. 

I’ve been working on updating AspNetCore’s repositories to use the 2.2 SDK and the 2.1 runtime. For the latter, I’ve been attempting to add the netcoreapp2.1 as a cross-compile target to our test projects. Xunit’s test discovery for one of these updated project’s test started failing with a BadImageFormatException. Digging in to the logs \ outputs revealed the following differences between the netcoreapp2.0 and 2.1 binaries:

a)	The 2.1 binary has Architecture x86 as opposed to 2.0 binary which has AnyCPU (64-bit preferred)
b)	The SDK compiles the 2.1 binary with a PlatformTarget of x86 versus an empty PlatformTarget on netcoreapp2.0

| netcoreapp2.1 | netcoreapp2.0 |
|---------------|---------------|
|  ![2 1](https://user-images.githubusercontent.com/174281/32748742-03d52e98-c872-11e7-8f3c-548a54d81f51.jpg)  | ![netcoreapp20](https://user-images.githubusercontent.com/174281/32748817-36683e72-c872-11e7-8f28-7f9e7f693f0a.jpg)| 

Here’s the csproj in question: https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj#L9

Specifying a PlatformTarget fixes the test discovery issue, but I’m just trying to figure out what might cause this difference. Of the two places I saw this, the common feature was that it was a `netcoreapp2.1` project referencing another `netcoreapp2.1` project

**Comment by livarcocc** [comment]
@nguerrera another one for RID inference. Can you take a look?

**Comment by pranavkm** [comment]
Sorry, I forgot to close this issue. I investigated this further and turns out this is an issue with our build \ test infrastructure.

**Comment by livarcocc** [comment]
@pranavkm thanks for letting us know. Appreciate it.
