### ISSUE TITLE
[ARM64]With NET6 preview4 SDK installed, sometimes run F# UT app failed with unhandled exception.

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/sdk#17307]
Affected Mac:
Mac OS: Big Sur(11.3) - Apple M1 chip
.NET 6 arm64: 6.0.100-preview.4.21227.10(runtime 6.0.0-preview.4.21222.10)

Steps to reproduce:
1.Install .NET arm64 SDK 6.0.100-preview.4.21227.10(runtime 6.0.0-preview.4.21222.10)
2.dotnet new F# xunit or mstest or nunit
3.dotnet build
4.dotnet test

Expected result:
Should run successfully.

Actual result:
Sometimes run with unhandled exception.
![image](https://user-images.githubusercontent.com/46206739/116661938-bb3f3580-a9c7-11eb-9026-f8e0db142d69.png)

Note:
Sometimes not repro. For example, run dotnet test 5 times will reproduce once.

**Comment by marcpopMSFT** [comment]
@nohwnd @dotnet/dotnet-test-templates-admin FYI, not sure if test or fsharp issue and seems bad.

**Comment by nohwnd** [comment]
It looks very generic, I don't see any dotnet test specific types, so it might be both.

**Comment by Jiangpeng14** [comment]
We verified this issue with ARM64 sdk 6.0.100-preview.6.21328.10, it doesn't repro.

**Comment by nohwnd** [comment]
Perfect.
