### ISSUE TITLE
Sdk resolver does not honor --configfile; and fails silently

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/sdk#17319]
When performing `dotnet restore` using the --configfile argument, the nuget Sdk resolver does not honor the --configfile setting. 

This results in two problems:
 
1. restore fails to restore the SDKs in question.
2. the restore exist with a success exit code, when it should not.

This issue is tracking the first problem.

# Repro steps

1. create the files described below in "Reference files"
2. install the dotnetsdk as described in global.json
3. from shell, run `dotnet restore --configfile custom_nuget.config && dotnet build --no-restore`

**Expected**

Project restores and builds successfully, producing no output

**Actual**

Project fails to restore, silently exiting with exit code zero and no console output. The subsequent build then fails with the following errors:

```
aaronla@aaronla-rabbit:repro_sdk$ dotnet restore --configfile custom_nuget.config

aaronla@aaronla-rabbit:repro_sdk$ echo %ERRORLEVEL%
0

aaronla@aaronla-rabbit:repro_sdk$ dotnet build --no-restore
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\scratch\repro_sdk\my.csproj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.

Build FAILED.

C:\scratch\repro_sdk\my.csproj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
```

# Reference files

```
aaronla@aaronla-rabbit:repro_sdk$ powershell "ls * | % { echo ''; echo ('// '+ $_.Name); cat $_ }"

// custom_nuget.config
<configuration>
  <config>
    <add key="repositoryPath" value="packages_custom" />
    <add key="globalPackagesFolder" value="packages_custom" />
  </config>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>

// global.json
{
    "sdk": {
        "version": "5.0.202"
    },
    "msbuild-sdks": {
        "Microsoft.Build.NoTargets": "2.0.1"
    }
}

// my.csproj
<Project Sdk="Microsoft.Build.Traversal">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>

// nuget.config
<configuration>
  <config>
    <add key="repositoryPath" value="packages" />
    <add key="globalPackagesFolder" value="packages" />
  </config>
  <packageSources>
    <clear />
    <add key="badfeed" value="Z:\badfeed" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by aaronla-ms** [comment]
@rainersigwald Heya, this is the issue we were discussing the other day about config files.

**Comment by erdembayar** [comment]
@aaronla-ms 
Could you be able to share sample repro project? I was unable to repro my local.
If you provide repro sample then I can investigate end to end.

**Comment by aaronla-ms** [comment]
@erdembayar sure thing. https://github.com/aaronla-ms/bug-repros/tree/main/repro-configfile

**Comment by erdembayar** [comment]
@aaronla-ms 
I can repro this.  Could you be able to create issue in https://github.com/NuGet/Home/issues/new? Somehow I can't transfer this to our retro.

**Comment by aaronla-ms** [comment]
@erdembayar Sure thing. I copied the issue over to that project.

**Comment by erdembayar** [comment]
@aaronla-ms 
Please put link for new issue here and better to close this one as duplicate.

**Comment by aaronla-ms** [comment]
reopened as https://github.com/NuGet/Home/issues/10886
