### ISSUE TITLE
HighEntropyVA not set by default for 64-bit .net core apps

### ISSUE THREAD

**Issue by michaelcfanning** [dotnet/sdk#1735]
1. Create default .net core console app
2. Set configuration to x64, compile

result: high entropy va bit not set in PE.

Adding relevant MSBUILD property with correct value to the project resolves the issue. So the problem appears to be that our default property settings need to be corrected.

    <HighEntropyVA>true</HighEntropyVA>

**Comment by livarcocc** [comment]
I don't think we set this property anymore on the SDK itself.

This may be set by MSbuild itself actually.

**Comment by livarcocc** [comment]
Discussed this with @rainersigwald. Moving it to MSBuild.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#2912
