### ISSUE TITLE
[Package Validation] Integrate the new option of single Left and multiple rights into package validation

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#17369]
https://github.com/dotnet/sdk/pull/17295 adds the new optimisations to reduce the number of api comparisions and speeding up the entire package validation.

cc @safern , @ViktorHofer @ericstj

**Comment by safern** [comment]
This was done in: https://github.com/dotnet/sdk/commit/e21d539d0e71ad397884aca82926ca7d01d177a3
