### ISSUE TITLE
[Package Validation] Localize all the error messages and diagnostics

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#17366]
There are few error messages that still need to be localized

cc @safern @ViktorHofer @ericstj

**Comment by ericstj** [comment]
Make sure this includes all error messages in targets files as well.  Those can be localized using the custom task approach similar to what the SDK does.

**Comment by ericstj** [comment]
Furthermore, we can avoid this entirely if we push the error/warning cases into the task instead of targets.  This should be the first priority if possible as it avoids the complexity of an additional task.
