### ISSUE TITLE
[ApiCompat] Add assembly version check between different assets.

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#17365]
The assembly version should be same across different runtimes for the same tfm. The compile time and runtime assets should have the same version

cc @safern @ViktorHofer @ericstj

**Comment by ViktorHofer** [comment]
FYI, while working on removing harvested assets I had to exclude validation for this in a package. I believe every validation would need a switch to turn it off or some of its features.

**Comment by safern** [comment]
Yes, I think this should be opt-out or just like all errors that customers can baseline.

**Comment by ViktorHofer** [comment]
Probably both :) I shouldn't need to baseline those if I don't care about this kind of validation. We are missing opt-out switches for the other validators as well. Let's make sure to always have an option to opt-out of specific ones.

**Comment by safern** [comment]
> Let's make sure to always have an option to opt-out of specific ones.

Yes that is the plan; Some rules will be opt-in and some opt-out, some will be just be errors can customers baseline, the last ones will be rules we think are important, so we don't want those to be opt-out.

**Comment by safern** [comment]
This was fixed by: #18709
