### ISSUE TITLE
Be able to output result a file in json when running dotnet list package

### ISSUE THREAD

**Issue by bschaatsbergen** [dotnet/sdk#17374]
When running `dotnet list package` it would be preferable to have a parameter to output the results to a file in order to post process the results.

I would be ok with making a pull request if others are interested in this.

**Comment by zahycs** [comment]
This can be very handy, especially after introducing packages vulnerability check using  `--vulnerable` argument. it could be very useful in pipelines

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#10837
