### ISSUE TITLE
Reference assemblies are incorrectly being marked as references

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#1739]
Seems like the opposite of #1738 

I'm working on updating AspNetCore's repositories to use the 2.2 SDK. With the 2.0.0 SDK, when attempting to publish a Mvc application (https://github.com/aspnet/MvcPrecompilation/blob/dev/testapps/RazorPagesApp/RazorPagesApp.csproj for reference) for `net461`, `Microsoft.Win32.Primitives` (among others) is recorded as a `referenceassembly` in the deps file:

```js
"Microsoft.Win32.Primitives/4.0.3.0": {
  "type": "referenceassembly",
  "serviceable": false,
  "sha512": ""
},
```

With 2.2.0-preview1-007522 SDK, it ends up in the deps file as a `reference`:
```js
"Microsoft.Win32.Primitives/4.0.3.0": {
  "type": "reference",
  "serviceable": false,
  "sha512": ""
},
```

This in turn causes view compilation to fail, with 
```C#
Cannot find compilation library location for package 'Microsoft.Win32.Primitives'
     at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
     at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
     at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
```

**Comment by pranavkm** [comment]
cc @eerhardt \ @dsplaisted could you recommend any workarounds for this?

**Comment by weshaggard** [comment]
@joperezr could you please have a look?

**Comment by joperezr** [comment]
Sure I can take a look. @pranavkm do you have a fork of the repo with your changes so I can try take a look at a repro?

**Comment by pranavkm** [comment]
@joperezr here's a simpler repro - https://github.com/pranavkm/repro1739/tree/master/app. Running `dotnet run` and navigating to the site root (http://locallhost:5000) should print the exception from DependencyContext.

**Comment by joperezr** [comment]
ok, great I'm taking a look

**Comment by joperezr** [comment]
I am able to repro the problem, but I'm not too familiar with the task that generates the deps file. Task seems to be `GenerateDepsFile` which lives on the sdk task library. @dsplaisted do you know what might be going on with it? Was there a recent change that maked the referenceassemblies be flagged as type reference now?

**Comment by livarcocc** [comment]
@pranavkm is this still reproing for you? I just tried this using the latest CLI from master and dotnet run and open the page worked as expected using your repro repo above.

**Comment by pranavkm** [comment]
We've been using 2.1.0-preview1\preview2 sdks for a while now and I haven't seen this issue reproduce.
