### ISSUE TITLE
`dotnet workload install` should normalize pack directory name to lower case 

### ISSUE THREAD

**Issue by grendello** [dotnet/sdk#17438]
dotnet workload install should normalize pack directory name to lower case

Original issue:
----------------------------

I discovered that even though the Xamarin.Android templates package (named `Microsoft.Android.Templates.11.0.200-ci.main.216.nupkg`) was installed in `dotnet/template-packs`, it wasn't considered by `dotnet new`. After running dotnet under `strace`, I found that it checks for the presence of the following packages in `template-packs` (apparently hardcoded?):

```
$ grep template-packs dotnet.log.381805 | grep lstat
lstat("dotnet/template-packs/microsoft.macos.templates.11.1.100-preview.3.1379.nupkg", 0x7f6864ce3350) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.macos.templates.11.1.100-preview.3.1379.nupkg", 0x7f6864ce33d0) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.android.templates.11.0.200-ci.main.216.nupkg", 0x7f6864ce3350) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.android.templates.11.0.200-ci.main.216.nupkg", 0x7f6864ce33d0) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.ios.templates.14.4.100-preview.3.1326.nupkg", 0x7f6864ce3350) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.ios.templates.14.4.100-preview.3.1326.nupkg", 0x7f6864ce33d0) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.maccatalyst.templates.14.3.100-preview.3.471.nupkg", 0x7f6864ce3350) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.maccatalyst.templates.14.3.100-preview.3.471.nupkg", 0x7f6864ce33d0) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.tvos.templates.14.3.100-preview.3.1379.nupkg", 0x7f6864ce3350) = -1 ENOENT (No such file or directory)
lstat("dotnet/template-packs/microsoft.tvos.templates.14.3.100-preview.3.1379.nupkg", 0x7f6864ce33d0) = -1 ENOENT (No such file or directory)
```

Copying our package to the `dotnet/templates/` directory or renaming it to all lower case in `dotnet/template-packs` made `dotnet new` show the templates defined there.

I think for the best cross-platform support, `dotnet new` should perform a case-insensitive check for the presence of template packages.

**Comment by mhutch** [comment]
The name-on-disk is lowercased to match what NuGet does with `~/.nuget/.packages`. It's expected that whatever installs the template pack will do the same transformation.

**Comment by DavidKarlas** [comment]
@dsplaisted @wli3 Is it OK if I close this issue? Do you want to open new one for `dotnet workload install`?

**Comment by wli3** [comment]
@DavidKarlas let me just rename this issue

**Comment by mhutch** [comment]
FWIW I'm not dead set on the lowercasing. If folks have strong opinions otherwise we could consider preserving original case. But either way there should be a consistent policy so that the casing of the paths returned from the manifest reader always matches the casing of the paths installed on disk.

**Comment by dsplaisted** [comment]
Maybe it was `maui-check`?

**Comment by sfoslund** [comment]
It sounds like the issue was in temporary code and shouldn't repro with the real workload installer then. Is there any action needed here?

**Comment by wli3** [comment]
If it is a temporary issue, we can close.

**Comment by grendello** [comment]
> It sounds like the issue was in temporary code and shouldn't repro with the real workload installer then. Is there any action needed here?

I think there's a need to fix this. While I noticed it using temporary code, anyone can grab a template pack from the Internet and put it in the `template-packs` folder without changing its name case. That will result in the templates not being visible.
