### ISSUE TITLE
GenerateRuntimeConfigurationFiles error when updating to preview.5.21253.6

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/sdk#17453]
I'm seeing the following build error when using SDK version [`6.0.100-preview.5.21253.6`](https://dev.azure.com/dnceng/internal/_build/results?buildId=1119161&view=results) or newer:

> .dotnet\sdk\6.0.100-preview.5.21253.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(255,5): error NETSDK1048: 'AdditionalProbingPaths' were specified for GenerateRuntimeConfigurationFiles, but are being skipped because 'RuntimeConfigDevPath' is empty.

The error is not present with [`6.0.100-preview.5.21253.4`](https://dev.azure.com/dnceng/internal/_build/results?buildId=1118972&view=results).

Judging from the error message and time of the SDK builds, I assume this has to do with #17014?

Is there something we have to update in our repo to work around this issue?

(For reference, we're hitting this in microsoft/reverse-proxy#972 when trying to move to net6.0 targets)

**Comment by MihaZupan** [comment]
I suppose this might be a dupe of #17388

**Comment by marcpopMSFT** [comment]
Correct, should be a duplicate and will be fixed by https://github.com/dotnet/sdk/pull/17491
