### ISSUE TITLE
CLI's --list-runtimes doesn't work well with UTF-8 characters

### ISSUE THREAD

**Issue by daniv-msft** [dotnet/sdk#17451]
Hello,

My product relies on the .NET CLI for some operations, and specifically parses the output of the "dotnet --list-runtimes" command.
This doesn't work well however whenever a runtime is present on a path containing UTF-8 characters, as the CLI seem to convert these characters to something else:
![image](https://user-images.githubusercontent.com/48293037/117188984-813cad80-ad92-11eb-94c1-9ff8790a575d.png)

.NET CLI version: 5.0.202

**Comment by marcpopMSFT** [comment]
@jonsequitur @sfoslund Would this in system command line or on the sdk side?

**Comment by sfoslund** [comment]
`--list-runtimes`, `--list-sdks`, and `--info` come from the runtime, so I expect the fix would be on their side.
