### ISSUE TITLE
Workload list should show update available

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#17484]
For command line, just show if there is any workload available is enough.

But for --machine-readable, we need to surface all workload manifest level and also have the description piped out

**Comment by wli3** [comment]
also need to allow --sdk-version parameter, so VSMac could get cross version band update. Need to handle failure case if a newer version manifest file cannot be read by the older version of SDK.

**Comment by davidortinau** [comment]
I would also like to see current version and pending upgrade available version. Basically an equiv to this:

![image](https://user-images.githubusercontent.com/41873/125476032-a140b403-2545-466c-9acf-496feb5db782.png)
