### ISSUE TITLE
Errors running build.cmd 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1752]
When running build.cmd on my machine i see the following errors many times during the test phase:

>C:\Users\jaredpar\code\sdk\bin\Debug\Tests\PCL_Project_reference_compat_TestID_netstandard1.0_Profile259\Referencer\Dependency\Dependency.csproj(46,3): error MSB4019: The imported project "C:\MSBuild\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [C:\Users\jaredpar\code\sdk\build\build.proj]

The structure of the error indicates it's trying to resolve target files for a 4.5 portable project. Yet the fact the error quotes `c:\MSBuild` throws me off a bit as that is not the installation location of MSBuild. 

Is there some pre-req I'm missing?

**Comment by livarcocc** [comment]
@johnbeisner can you comment?

**Comment by johnbeisner** [comment]
The path to 'Microsoft.Portable.CSharp.targets' is indeed suspect. It should look something like this: "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets"

It appears as if the environmental variable: "VSINSTALLDIR" is not set - are you running the SDK build in a Visual Studio Developer command shell?

**Comment by livarcocc** [comment]
I am closing this issue since builds seem to be stable now. If this is still happening, let us know.
