### ISSUE TITLE
dotnet test --filter should escape parenthesis () when filtering with test case name containing parenthesis () 

### ISSUE THREAD

**Issue by 0vineet-kumar0** [dotnet/sdk#17520]
dotnet test accepts a --filter option 
https://github.com/dotnet/cli/blob/release/3.1.4xx/src/dotnet/commands/dotnet-test/TestCommandParser.cs#L35

As per the documentation at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details

--filter <EXPRESSION>
You can enclose expressions in parenthesis when using conditional operators

However when trying to run a test cases filtering by name which contains  parenthesis () we get an error:

Eg: 
`dotnet test --filter "DisplayName=Some Test Name (Test-One)"`
or
`dotnet test --filter DisplayName="Some Test Name (Test-One)"`
or
`dotnet test --filter DisplayName="Some Test Name %28Test-One%29"`

Error Message:
`[xUnit.net 00:00:01.07] TestProjectName: Exception filtering tests: Incorrect format for TestCaseFilter Error: Invalid Condition 'Test-One'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

Seems the data within parenthesis () in parsed as expression , there is no way to escape parenthesis.

The test method I am trying to run is generated by Specflow looks something like below:

```
[Xunit.SkippableFactAttribute(DisplayName="Some Test Name (Test-One)")]
[Xunit.TraitAttribute("FeatureTitle", "Some Test Feature")]
[Xunit.TraitAttribute("Description", "Some Test Name (Test-One)")]
[Xunit.TraitAttribute("Category", "TCID:11111")]
public virtual void SomeTestNameTestOne_Out()
{
//Test method Steps
}
```

**Comment by Haplois** [comment]
@0vineet-kumar0, `dotnet test -filter` property already supports escaping. You can filter your test using:

```powershell
dotnet test --filter 'DisplayName="Some Test Name \(Test-One\)"'
```

**Comment by 0vineet-kumar0** [comment]
@Haplois  Escape seems to work for something like this 
`dotnet test --filter FullyQualifiedName\!~IntegrationTests` as per documentation at https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit

**However I tried what you suggested and it still fails, as mentioned this seems specifically for parenthesis ()**
`dotnet test --filter 'DisplayName="Some Test Name \(Test-One\)"'`

I got following error on trying your suggestion:
No test matches the given testcase filter \`'DisplayName=Some Test Name \\(Test-One\\)'\`

I can run the test using contains filter 
 `dotnet test --filter DisplayName~"Some Test Name"`
or
I can run the test on removing the parenthesis from the title of my test and execute 
`dotnet test --filter DisplayName="Some Test Name Test-One"`

There seems to be issue with comma ',' and possibly other special characters

**Comment by Haplois** [comment]
@0vineet-kumar0, I have [this][1] repro. 

`dotnet test --filter 'DisplayName="Some Test Name \(Test-One\)"'` results in only one test being run instead of two, as you can see below. Could please share a repro with us?

```console
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  dotnet-filter-escaping -> ~\bin\Debug\net6.0\dotnet-filter-escaping.dll
Test run for ~\bin\Debug\net6.0\dotnet-filter-escaping.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210331-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - dotnet-filter-escaping.dll (net6.0)
```

[1]: https://github.com/dotnet/sdk/files/6501326/dotnet-filter-escaping.zip

**Comment by 0vineet-kumar0** [comment]
@Haplois  Thanks for trying this out, I'm on .net core 3.1 , will update my project to .Net 5 and update the results soon

**Comment by nohwnd** [comment]
@0vineet-kumar0 Hello, were you able to validate this? :)
