### ISSUE TITLE
Assets file 'E:\****\obj\project.assets.json' doesn't have a target for '.NETPortable,Version=v4.0,Profile=Profile111'. Ensure that restore has run and that you have included 'portable40-net45+win8+wpa81' in the TargetFrameworks for your project.

### ISSUE THREAD

**Issue by Lily721** [dotnet/sdk#1759]
Hi guys,

When I use multi target framework in my project like following:

`<TargetFrameworks>netstandard1.1;net45</TargetFrameworks><TargetFrameworkProfile>Profile111</TargetFrameworkProfile>` 

And following is why I need TargetFrameworkProfile in my .csproj:

`<Import Project="$(MSBuildExtensionsPath)\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" />`

I faced upper problem, I thought I was right when I see this article [https://docs.microsoft.com/en-us/nuget/schema/target-frameworks],

Profile111 | .NETFramework 4.5 | portable-net45+win8+wpa81 | netstandard1.1

I've being working on this a whole day, didn't find any solution yet, does anyone know what's the problem? Thanks a lot.

**Comment by livarcocc** [comment]
PCLs are not supported in the command line and the new csproj style.

Why do you need to target it directly? I isn't netstandard1.1 enough for you?

**Comment by dasMulli** [comment]
@Lily721 with some manual project file editing you could get an "sdk-style" project to build for portable profiles as well as .net standard.
A good working example is Newtonsoft.Json (see [Newtonsoft.Json.csproj](https://github.com/JamesNK/Newtonsoft.Json/blob/60f66d9c96c7dfff90fcbf06c08103822cafc9dc/Src/Newtonsoft.Json/Newtonsoft.Json.csproj)).

Based on it, you could be able to build a library targeting the PCL profile on windows provided that the necessary components are installed.

However the PCL profile you want to use (111) is already equivalent to .NET Standard 1.1 so if you create a new .NET Standard library (either in VS or via `dotnet new lib`), your library can still be referenced everywhere this profile used to work before.

---

For reference, a csproj building a slice for this PCL profile in addition to .NET Framework 4.5 and .NET Standard 1.1 could look like
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.1;net45;portable-net45+win8+wpa81</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'portable-net45+win8+wpa81'">
    <TargetFrameworkIdentifier>.NETPortable</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile111</TargetFrameworkProfile>
    <NugetTargetMoniker>.NETPortable,Version=v0.0,Profile=Profile111</NugetTargetMoniker>
    <LanguageTargets>$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets</LanguageTargets>
  </PropertyGroup>
</Project>
```

**Comment by Lily721** [comment]
Hi livoorcooc/dasMulli,

I'm developing an app in Xamarin, and I want to execute a target before compilation, so I made following changes in .csproj to fulfill it:
`  <Import Project="$(MSBuildExtensionsPath)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" />
  <Import Project="..\..\..\..\My.targets" />`

and My.targets looks like below:
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <CoreCompileDependsOn>
      Gen;$(CoreCompileDependsOn)
    </CoreCompileDependsOn>
  </PropertyGroup>
  <UsingTask ...../>
  <UsingTask ...../>
</Project>`

All of these work well when I use .NetFramework 4.5, because PCLs and get correct address of Microsoft.Portable.CSharp.targets. But when I improve my project from .Framework 4.5 to .Net Standard 1.1, I faced up with a problem, that is Microsoft.Portable.CSharp.targets can not be imported as before, so that's why I need Multi-Framework, but it still looks ungainly. Do you have any better way to solve this?

**Comment by livarcocc** [comment]
When you move to netstandard1.1, why do you need to keep importing the Portable.CSharp.targets? netstandard1.1 does not need it, so, just remove it.

**Comment by Lily721** [comment]
My.targets can not run when I remove Microsoft.Portable.CSharp.targets, I guess may be they are relevant.

**Comment by livarcocc** [comment]
Can you tell us more about `my target can not run`? What do you see? An error? Nothing happens?

Can you do a build using `dotnet build /bl` and share the generated bin log with us?

Also, could you share the whole content of your csproj?

**Comment by Lily721** [comment]
I believe netstanard1.1 already covered Profile111, and it seems like there's no need to import Portable.CSharp.targets again in the new format of netstandard1.1 .csproj, I thought I just need import my custom target as usual, then it should work, but, actually, It doesn't. BTW, my msbuild target is build base on FrameWork 4.5, and please check this [article](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) , When I run netstandard 1.1 project, no UserTask was fired, I don't know what's going on, why my UserTask can not be started?
