### ISSUE TITLE
Assets file 'X' doesn't have a target for '.NETFramework,Version=v3.5,Profile=Unity Full v3.5'

### ISSUE THREAD

**Issue by Bert-Proesmans** [dotnet/sdk#1760]
Hi,
I have a csproj file which targets both netstandard1.0 and net3.5 (unity profile), found [here](https://pastebin.com/R1eJKXQw). The project always compiled successfully until i updated Visual Studio 2017 (now i'm on 15.4.4, but it happened since 2 updates before) but can't exactly remember which version i was on (and the sdk version packaged with it) when i noticed the build failing. 
Nowadays building throws an error and no output is produced (no object files nor binaries). **NOT using the Unity profile allows a successful build.**

Other than updating visual studio my setup didn't change. Old style projects targetting net3.5 (unity profile) still build without error.

I hope someone can help me, i have no clue how to fix this.
Below is an image of the project file within visual studio with the error message.
![afbeelding](https://user-images.githubusercontent.com/2027877/32991733-94b32388-cd41-11e7-884b-f4d57588a649.png)

Bert

**Comment by Bert-Proesmans** [comment]
If that's correct then the actual question would be: what's the rol of Visual Studio in this scenario. I will file an issue with them for information, because their build delegation system could be the problem here?

**Comment by livarcocc** [comment]
Visual Studio will invoke MSBuild using our props/targets that support netstandard. However, if you are targeting net35, you should continue using the old style csproj files.

**Comment by emgarten** [comment]
NuGet issues tracking unity support:
https://github.com/NuGet/Home/issues/5460
https://github.com/NuGet/Home/issues/2146

**Comment by Bert-Proesmans** [comment]
@emgarten Thanks for the references. I'm not fully convinced about the relation of the linked issues to this one; i wouldn't have been able to guess this issue is caused by NuGet, but i'm not gonna contradict you guys.
Will my setup as-is work again when NuGet receives firstclass Unity support? Will there be other implications i need to be aware of?

**Comment by Bert-Proesmans** [comment]
Closing because of old age
