### ISSUE TITLE
dotnet pack produces a package with copyToOutput not applied

### ISSUE THREAD

**Issue by melanchall** [dotnet/sdk#17662]
I have a small sample solution: [DualLibClassLibrary.zip](https://github.com/dotnet/sdk/files/6493577/DualLibClassLibrary.zip).

The structure of the solution:

```
├ DualLibClassLibrary
·  ├ native
·  ·  ├ test.dll
·  ·  └ test.dylib
·  ├ Class.cs
·  └ DualLibClassLibrary.csproj
└ DualLibClassLibrary.sln
```

As you can see I have following lines in csproj:

```xml
<ItemGroup>
  <Content Include="native\*">
    <Pack>true</Pack>
    <PackageCopyToOutput>true</PackageCopyToOutput>
    <PackageFlatten>true</PackageFlatten>
    <PackagePath>contentFiles;content</PackagePath>
  </Content>
</ItemGroup>
```

When I run `dotnet pack` I'll get a package with following metadata:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>DualLibClassLibrary</id>
    <version>1.0.0</version>
    <authors>melanchall</authors>
    <owners></owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Dual-lib class library</description>
    <copyright>Copyright © Melanchall 2021</copyright>
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
    <contentFiles>
      <files include="test.dll" buildAction="Content" copyToOutput="true" flatten="true" />
      <files include="test.dylib" buildAction="Content" copyToOutput="true" flatten="true" />
    </contentFiles>
  </metadata>
</package>
```

So there are `copyToOutput="true"` attributes on the files.

Now we create a small .NET Framework console application: [ConsoleAppFramework.zip](https://github.com/dotnet/sdk/files/6493719/ConsoleAppFramework.zip).

The structure of the solution:

```
├ ConsoleAppFramework
·  ├ Properties
·  ·  └ AssemblyInfo.cs
·  ├ App.config
·  ├ ConsoleAppFramework.csproj
·  └ Program.cs
└ ConsoleAppFramework.sln
```

Now if we install the `DualLibClassLibrary` package into the project, we'll get following project structure:

![image](https://user-images.githubusercontent.com/26361185/118488604-93203800-b724-11eb-8a3e-8c478c13eba8.png)

So we have `test.dll` and `test.dylib` in the solution. Looks good, **BUT** let's take a look at the csproj:

```xml
<ItemGroup>
  <None Include="App.config" />
  <None Include="packages.config" />
  <None Include="test.dylib" />
</ItemGroup>
<ItemGroup>
  <Content Include="test.dll" />
</ItemGroup>
```

Hmm... `test.dylib` added as `None`, `test.dll` added as `Content` and.. no one item has `CopyToOutputDirectory` set. If we build the project, we obviously won't get libraries copied to output directory.

Maybe I do something wrong? Looks strange and absolutely unexpectedly.

I found on the Internet this issue: https://github.com/NuGet/Home/issues/6404. There is a comment there:

> The way content files are copied is that NuGet writes them in the props file and then later the build task picks them up.

But after `dotnet pack` I don't see any `.props` file so it looks like a bug of `dotnet pack`.

**Comment by melanchall** [comment]
@wli3 Any news?

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#10906
