### ISSUE TITLE
Missing packages for Ubuntu 21.04 aarch64/arm64

### ISSUE THREAD

**Issue by eSPiYa** [dotnet/sdk#17683]
I'm running a 64-bit Ubuntu Server 21.04 on my Raspberry pi 4
and here is the content of /etc/apt/sources.list.d/microsoft-prod.list
`deb [arch=arm64] https://packages.microsoft.com/ubuntu/21.04/prod hirsute main
`
I removed the amd64 and armhf in the architectures list.

If I try to install the dotnet 5.0 SDK using this command `sudo apt-get install -y dotnet-sdk-5.0`, what I get is this:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package dotnet-sdk-5.0
> E: Couldn't find any package by glob 'dotnet-sdk-5.0'
> E: Couldn't find any package by regex 'dotnet-sdk-5.0'

Is it me or it is just Ubuntu arm64 is not yet supported? Thanks!

**Comment by marcpopMSFT** [comment]
@rbhanda When should we expect the 21.04 packages?

**Comment by rbhanda** [comment]
I believe these are updated now. @leecow fyi

**Comment by dagood** [comment]
Isn't arm64 acquisition from https://packages.microsoft.com (for any distro) waiting on https://github.com/dotnet/runtime/issues/3298?

**Comment by rbhanda** [comment]
Ah yes, I mis-read the title. These packages aren’t available yet.

**Comment by eSPiYa** [comment]
> Ah yes, I mis-read the title. These packages aren’t available yet.

Any idea when this will be available? Thanks!

**Comment by alexgubanow** [comment]
@rbhanda issue still presented, no packages for arm64

**Comment by AestheticalZ** [comment]
This would be a great addition to the package repos, installing/updating .NET on a raspberry pi is really annoying without the package manager.
