### ISSUE TITLE
Invalid parameter order when adding a project to sln using `dotnet sln add` should be validated

### ISSUE THREAD

**Issue by eriawan** [dotnet/sdk#17686]
## General Information
The `dotnet sln add` should respect the order of parameter passed. If the order of the passed parameters are incorrect or invalid, it should display error and the command should not be executed successfully.
Current `dotnet sln add` executed successfully when invalid order of parameters are passed.

Based on the current help from `dotnet sln add -h` the parameters are ordered using this syntax:
`dotnet sln <SLN_FILE> add [options] <PROJECT_PATH>`
taken from:
```
D:\samplenet50>dotnet sln add -h
Usage: dotnet sln <SLN_FILE> add [options] <PROJECT_PATH>

Arguments:
  <SLN_FILE>       The solution file to operate on. If not specified, the command will search the current directory for one.
  <PROJECT_PATH>   The paths to the projects to add to the solution.

Options:
  --in-root               Place project in root of the solution, rather than creating a solution folder.
  -s, --solution-folder   The destination solution folder path to add the projects to.
  -h, --help              Show command line help.
```

## SDK versions used

- [x] 3.1 SDK: 3.1.403
- [x] 5.0 SDK: 5.0.103, 5.0202, 5.0.203

## Operating system

- Windows 10 1909
- Windows 10 2004
- Ubuntu 20 on WSL

## Steps to reproduce

The steps are:

1. Create new sln using `dotnet new sln`, example: `dotnet new sln Solution50`
2. Create any kind of new project. For example: `dotnet new mstest -n UnitTest01`
3. Add the created new project into the previously created sln above, with invalid order of the parameters passed. Example: `dotnet sln add Solution50.sln UnitTest01\UnitTest01.csproj`

Expected result:
The project should not be added and it should display error with meaningful error message.

Actual result:
The project added into the solution, but it still display error message.
```
Invalid project `D:\samplenet50\Solution50.sln`. The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.  D:\samplenet50\Solution50.sln.
Project `UnitTest01\UnitTest01.csproj` added to the solution.
```

Sample:

![image](https://user-images.githubusercontent.com/8773147/118630863-21fe8480-b7f9-11eb-86be-ec6323193e7a.png)

**Comment by DavidKarlas** [comment]
I transferred issue to dotnet/sdk because `dotnet sln` lives there.

**Comment by eriawan** [comment]
@DavidKarlas 

Thanks!

**Comment by eriawan** [comment]
@marcpopMSFT 

Ok, looks like this is related to `dotnet-sln` tool, CMIIW.
Looking at the CODEOWNERS, there is no known owner for `src/Cli/dotnet/commands/dotnet-sln`. So who should I mention for assessing this issue?

cc @dotnet/dotnet-cli

**Comment by eriawan** [comment]
@dotnet/dotnet-cli 

is there someone available to review this issue? hopefully there should be an update at least confirmation that it's being reviewed.
It's been 2 days without any further update...
