### ISSUE TITLE
dotnet run don't copy files marked as CopyToOutputDirectory=Always to output on Azure Pipelines hosted agents

### ISSUE THREAD

**Issue by melanchall** [dotnet/sdk#17706]
I have a test pipeline on hosted agents: [ConsoleApp-Win-Core-BothFiles-net5](https://dev.azure.com/Melanchall/DryWetMIDI/_build?definitionId=41&_a=summary). Pipeline does following steps:

1. downloads dll file from another pipeline
2. downloads dylib file from another pipeline
3. creates console app via `dotnet new console  -n ConsoleApp`
4. copies dll and dylib files into `ConsoleApp` folder placing them near csproj file:

    ```powershell
    Copy-Item test.dylib -Destination ConsoleApp
    Copy-Item test.dll -Destination ConsoleApp
    ```
5. sets csproj file content:

    ```powershell
    $content = @"
    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
      </PropertyGroup>
    
      <ItemGroup>
        <None Update="test.dll">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="test.dylib">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
      </ItemGroup>
    
    </Project>
    "@
    
    Set-Content -Path ConsoleApp/ConsoleApp.csproj -Value $content
    ```

    so we have `<CopyToOutputDirectory>Always</CopyToOutputDirectory>` here.
6. sets Program.cs content:

    ```powershell
    $content = @"
    using System;
    using System.Globalization;
    using System.Runtime.InteropServices;
    using System.Threading;
    
    namespace ConsoleNetFramework
    {
        class Program
        {
            [DllImport("test")]
            public static extern int Foo();
    
            static void Main(string[] args)
            {
                var result = Foo();
                Console.WriteLine($"Result = {result}");
            }
        }
    }
    "@
    
    Set-Content -Path ConsoleApp/Program.cs -Value $content
    ```

7. runs app via `.NET Core` task (`dotnet run --project ConsoleApp/ConsoleApp.csproj`)

And here we get the error:

```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'test' or one of its dependencies: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at ConsoleNetFramework.Program.Foo()
   at ConsoleNetFramework.Program.Main(String[] args) in D:\a\1\s\ConsoleApp\Program.cs:line 15
```

I found that this is due to files were not copied to output directory.

So I added additional step that prints all dll and dylib files:

```
----                -------------         ------ ----                                                                  
-a----        5/19/2021   2:42 PM           5120 ConsoleApp.dll                                                        


    Directory: D:\a\1\s\ConsoleApp\bin\Debug\net5.0


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        5/19/2021   2:42 PM           4608 ConsoleApp.dll                                                        


    Directory: D:\a\1\s\ConsoleApp\obj\Debug\net5.0\ref


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        5/19/2021   2:42 PM           5120 ConsoleApp.dll                                                        


    Directory: D:\a\1\s\ConsoleApp\obj\Debug\net5.0


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        5/19/2021   2:42 PM           4608 ConsoleApp.dll                                                        


    Directory: D:\a\1\s\ConsoleApp


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        5/19/2021   2:41 PM                test.dll                                                              
d-----        5/19/2021   2:41 PM                test.dylib                                                            


Finishing: Print all dll and dylib files
Row 7. Clickable

Row 2. Clickable

Row 2. Clickable

Row 2. Clickable

Task disabled

Task enabled

Row 2. Clickable
```

For some reason I see only dll and dylib near csproj that I added on fourth step. So my question is why files were not copied to output directory (`D:\a\1\s\ConsoleApp\obj\Debug\net5.0`)?

When I do all these steps locally on my computer, all works fine.

**Comment by marcpopMSFT** [comment]
I'd recommend doing a dotnet build /bl to create an https://aka.ms/binlog. You can then look through the binlog to see if the copy step is being triggered. I wonder if the files aren't there when the build happens but are copied later perhaps or something else that might be in the binlog.

**Comment by melanchall** [comment]
Your [online bin log reader](https://live.msbuildlog.com/) can't read logs created by `dotnet build` from Microsoft-hosted agents building .NET5 project:

> System.NotSupportedException: Unsupported log file format. Latest supported version is 12, the log file has version 13. at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream, Func\`3 progressFunc) at Microsoft.Build.Logging.StructuredLogger.BinaryLog.ReadBuild(Stream stream, Byte[] projectImportsArchive, Func`3 progressFunc) at StructuredLogViewerWASM.Shared.NavMenu.LoadBinlog(MemoryStream memoryStream) at StructuredLogViewerWASM.Shared.NavMenu.ReadFile(IFileListEntry[] files)

Funny :)

But offline reader works. But I can't understand content of the log, so I attach it here: [out.binlog.zip](https://github.com/dotnet/sdk/files/6552796/out.binlog.zip).

To make sure I've done all properly, I printed content of the csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <None Update="test64.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="test64.dylib">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>
</Project>
```

Files are placed near csproj:

```
    Directory: D:\a\1\s\ConsoleApp

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        5/27/2021   9:27 AM                test64.dll                                                            
d-----        5/27/2021   9:27 AM                test64.dylib                                                          
-a----        5/27/2021   9:27 AM            418 ConsoleApp.csproj                                                     
-a----        5/27/2021   9:27 AM            404 Program.cs  
```

But after build test64.dll/dylib are missed in the output:

```
    Directory: D:\a\1\s\ConsoleApp\bin\Debug\net5.0

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        5/27/2021   9:27 AM            422 ConsoleApp.deps.json                                                  
-a----        5/27/2021   9:27 AM           4608 ConsoleApp.dll                                                        
-a----        5/27/2021   9:27 AM         127488 ConsoleApp.exe                                                        
-a----        5/27/2021   9:27 AM           9724 ConsoleApp.pdb                                                        
-a----        5/27/2021   9:27 AM            258 ConsoleApp.runtimeconfig.dev.json                                     
-a----        5/27/2021   9:27 AM            147 ConsoleApp.runtimeconfig.json 
```

**Comment by melanchall** [comment]
@marcpopMSFT Any news?

**Comment by marcpopMSFT** [comment]
Sorry, your binlog doesn't list those files at allbut if I try to reproduce the structure of the csproj, I correctly see the files getting copied in the binlog.  I'm really unsure as why it's failing remotely. Can you try running dotnet build and then dotnet run?  Try changing the items and adding them to a target so you can see if the target is getting run?

@KirillOsenkov do you have the source for the live log viewer and are you able to update to open newer binlogs?  Looks like it hasn't been updated for more recent binlogs.

**Comment by KirillOsenkov** [comment]
yes I’ll get that updated soonish

**Comment by KirillOsenkov** [comment]
I've updated https://live.msbuildlog.com to support the latest file format.

**Comment by KirillOsenkov** [comment]
@melanchall try changing `<None Update` to `<None Include` in your .csproj.

**Comment by KirillOsenkov** [comment]
From what I can see, the test64.dll and test64.dylib are not present in the project directory at the time the build runs. Your step that prints the directory contents - does it run before you build the project?

**Comment by KirillOsenkov** [comment]
You can add this at the end of your .csproj:

```xml
  <ItemGroup>
    <AllFiles Include="**\*" />
  </ItemGroup>
```

and then in the binlog viewer, search for `$additem AllFiles` - it will snapshot the directory contents at evaluation time as MSBuild sees it.

**Comment by KirillOsenkov** [comment]
You can also search the binlog viewer for `$additem None` to investigate which items are included as `None` by default.

**Comment by KirillOsenkov** [comment]
The SDK is working as designed as far as I can see.

**Comment by melanchall** [comment]
@marcpopMSFT @KirillOsenkov Thanks for your reply!

It was actually my fault indeed. When I changed `<None Update` to `<None Include` and added `dotnet build` prior `dotnet run`, I got this error:

> ##[error]C:\Program Files\dotnet\sdk\5.0.300\Microsoft.Common.CurrentVersion.targets(4995,5): Error MSB3025: The source file "D:\a\1\s\ConsoleApp\test64.dll" is actually a directory.  The "Copy" task does not support copying directories.

I create `test64.dll` and `test64.dylib` within another pipelines and publish them as artifacts with same names. I didn't think that when I download artifact from pipeline, it gets downloaded as folder and not a single file packed to artifact.

So I actually downloaded folders `test64.dll` and `test64.dylib` and tried to copy them :) When I changed copying script to this:

```powershell
Copy-Item test64.dylib/test64.dylib -Destination ConsoleApp
Copy-Item test64.dll/test64.dll -Destination ConsoleApp
```

both `dotnet build` and `dotnet run` worked great.

Thank you again for your help! I feel myself stupid now :)

By the way, search by `$additem AllFiles` don't work in live viewer:

![image](https://user-images.githubusercontent.com/26361185/121305214-88be1c00-c927-11eb-9e61-1e8a0b6c339f.png)

although it present in log:

![image](https://user-images.githubusercontent.com/26361185/121305252-95427480-c927-11eb-961e-d630b19d4292.png)

**Comment by melanchall** [comment]
Maybe it would be useful to check for item type in `dotnet run` too, not only in `dotnet build`? And for `Update` attribute, not only for `Include`.

**Comment by KirillOsenkov** [comment]
No, the way it works is None items are automatically created for files, not directories. This is the reason you didn’t see the None items and Update didn’t do anything. When you changed to Include, you forced including the directory, so the Copy task failed.

I’ll take a look at the online viewer failure.

**Comment by BinarySpike** [comment]
I'm not sure why but Azure Pipeline's is having an issue with the below configuration:
```
<ItemGroup>
  <Content Include="dist\**">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <PackageCopyToOutput>true</PackageCopyToOutput>
  </Content>
</ItemGroup>

<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
  <Exec Command="yarn build" />
</Target>
```

The files created by "yarn build" are not seen by the Content-Include statement above.  I had to remove the PreBuild task and add it as a separate Pipeline task before the DotNetCli task.

I discovered this by manually creating a dist folder with a "dist" file (due to GIT limitations) and it seems the `yarn build` deleted that file and the build agent complained because it couldn't find it.

I do not get this functionality locally or when running `dotnet publish ...` on the build agent server manually from command prompt.

**Comment by BinarySpike** [comment]
I'm nearly positive this is what I should have put so azure pipelines identifies the files properly:
```
<Target Name="Yarn" BeforeTargets="ComputeFilesToPublish">
  <Exec Command="yarn"></Exec>
  <Exec Command="yarn build"></Exec>
</Target>

**Comment by kodfodrasz** [comment]
[💣 1 ERROR] fish ❯ dotnet tool list
Package Id      Version      Commands      Manifest
---------------------------------------------------


ggergely@zenit in …/otp-car-bond-checker on 🌱 email via .NET v8.0.108 🎯 net8.0
fish ❯ dotnet tool list -g
Package Id      Version      Commands
-------------------------------------
fantomas        6.3.15       fantomas

ggergely@zenit in …/otp-car-bond-checker on 🌱 email via .NET v8.0.108 🎯 net8.0
fish ❯ dotnet tool run fantomas
Cannot find a tool in the manifest file that has a command named 'fantomas'.
