### ISSUE TITLE
[ DOTNET SDK]Satellite assemblies from PackageReference not copying to bin folder in .NET SDK  3.0.11 

### ISSUE THREAD

**Issue by divyapurwar** [dotnet/sdk#17744]
Describe the bug
I have been using .net sdk 3.0.11 in my project. During Azure build it is not copying the dll's into the bin folder of artifact instead it is copying it to root folder.

Expected behavior
It should copy all the dll's into bin folder.

Actual behavior (include Exception or Stack Trace)
As you can see from the below logs, It is first copying the files into root folder, then creating a zip artifact after that it is copying .dll into bin folder. In the deployment it uses the zip artifact and find no dll's in there.

GenerateProjectArtifacts:
Creating directory "d:\dbs\el\143e\target\distrib\Release\x64\abc..\abc\bin".
Zipping directory "d:\dbs\el\143e\target\distrib\Release\x64\abc" to "d:\dbs\el\143e\target\distrib\Release\x64\abcArtifacts\bin\abc.zip".
_FunctionsPostBuildCopyFiles:
Copying file from "d:\dbs\el\143e\target\distrib\Release\x64\abc\Azure.Core.dll" to "d:\dbs\el\143e\target\distrib\Release\x64\abc\bin\Azure.Core.dll".
_FunctionsPostBuildCopyFiles:
Copying file from "d:\dbs\el\143e\target\distrib\Release\x64\abc\Azure.Identity.dll" to "d:\dbs\el\143e\target\distrib\Release\x64\abc\bin\Azure.Identity.dll".

To Reproduce
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
Create a new project which uses latest .NetSDK 3.0.11
Build it.
Please check drops from the URL and check projectartifact. There is no dlls in the bin folder of the artifact.

Environment:
Name and version of the Library package used: [.Net SDK 3.0.11]

when I reverted the SDK to 3.0.3 it is working fine.

**Comment by marcpopMSFT** [comment]
I believe you're talking about the Azure Functions SDK and so this issue should be reopened here: https://github.com/Azure/Azure-Functions.
