### ISSUE TITLE
Break Microsoft.DotNet.PackageValidation into two packages

### ISSUE THREAD

**Issue by joperezr** [dotnet/sdk#17758]
While discussing the design of the PackageValidation package, it was suggested by @rainersigwald that ideally we should have our package split up into two:
 1. One SDK package that will only contain the logic that needs to be consumed as an SDK (which in our case, it includes the logic that enables us to use PackageDownload to restore the baseline package for our validation).
 2. A second package that has everything else, and which is referenced by package no. 1.

The advantage of doing this, is that MSBuild (and VS) will be able to perform the initial evaluation faster, as MSBuild will initially only need to restore package no. 1, and then restore the remaining no. 2 package during the restore pass of the project.

**Comment by joperezr** [comment]
cc: @ericstj @Anipik

**Comment by ericstj** [comment]
> The advantage of doing this, is that MSBuild (and VS) will be able to perform the initial evaluation faster, as MSBuild will initially only need to restore package no. 1, and then restore the remaining no. 2 package during the restore pass of the project.

I wonder in practice how much this would make a difference in practice?  It seems like the .NET SDK itself could take this approach since most of the targets and tasks within it aren't needed for the initial restore.  cc @terrajobst @dsplaisted

**Comment by rainersigwald** [comment]
The .NET SDK itself is a special snowflake; it is resolved by `Microsoft.DotNet.MSBuildSdkResolver` (which uses `hostfxr` to find a .NET installation) rather than by `Microsoft.Build.NuGetSdkResolver` which does network access. As a result, it doesn't need the split.

**Comment by dsplaisted** [comment]
Rather than creating a separate SDK and telling developers to add a reference to that SDK in their project, could you just skip the SDK and tell the developers to put something like the following in their project?

```xml
<PackageDownload Include="$(PackageId)"
                       Version="[$(PackageValidationBaselineVersion)]" />
```

For getting the baseline version, I think the best approach would be to see if NuGet can add wildcard support for `PackageDownload` items.  Then all the network calls would be handled by NuGet during restore.

**Comment by joperezr** [comment]
We support that as well, in fact we even allow you to instead pass in the path on disk where you have already restored the previous package so that we use that in our validation. The idea of us downloading it for you was a convenience aspect that would also facilitate the onboarding process as it would really only require adding the dependency to the sdk.

**Comment by Anipik** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
> The advantage of doing this, is that MSBuild (and VS) will be able to perform the initial evaluation faster, as MSBuild will initially only need to restore package no. 1, and then restore the remaining no. 2 package during the restore pass of the project.

What's the advantage in doing this? Breaking the package into two means that we would restore one more package (during the msbuild sdk resolver). What would we gain (except a few lines of less evaluation) by splitting the package apart?

**Comment by ViktorHofer** [comment]
> For getting the baseline version, I think the best approach would be to see if NuGet can add wildcard support for PackageDownload items. Then all the network calls would be handled by NuGet during restore.

100% agreed but after talking to @nkolev92 it didn't sound like this is on their radar.

**Comment by safern** [comment]
@Anipik @joperezr I believe now that we've made this package part of the SDK, we no longer need this. Please re-open if I'm wrong.
