### ISSUE TITLE
SolutionDir variable not resolved during post build event

### ISSUE THREAD

**Issue by twenzel** [dotnet/sdk#1777]
This issue is similar to #677.

The `$(SolutionDir)` variable will not be resolved when using post build event and dotnet cli.
It works using VS2017.

```xml
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(SolutionDir)License\xy.xml&quot; $(TargetDir)" />
  </Target>
```

The `$(TargetDir)` variable will be resolved correctly.

**Comment by livarcocc** [comment]
In the particular case of SolutionDir, I don't think this is set in the SDK, but rather by MSBuild.

@rainersigwald can you comment on this?

**Comment by rainersigwald** [comment]
How are you invoking the build using `dotnet`? MSBuild can only set `$(SolutionDir)` when you start the build at the solution level.

**Comment by livarcocc** [comment]
Closing since we haven't had activity here in nearly a month. If you can answer the question above, we can re-activate this issue.
