### ISSUE TITLE
Running Restore and Build on clean project in one invocation produces invalid deps

### ISSUE THREAD

**Issue by pakrym** [dotnet/sdk#1779]
Repro:
1. `dotnet new web`
2. `rm obj -rec -force`
3. `dotnet msbuild /t:"Restore;Build"`

Expected:

`.deps.json` file is trimmed
```
      "System.ComponentModel/4.3.0": {
        "dependencies": {
          "System.Runtime": "4.3.0"
        }
      },
```

Actual:

```
      "System.ComponentModel/4.3.0": {
        "dependencies": {
          "System.Runtime": "4.3.0"
        },
        "runtime": {
          "lib/netstandard1.3/System.ComponentModel.dll": {}
        }
      },
```

**Comment by livarcocc** [comment]
@emgarten can you take a first look?

**Comment by emgarten** [comment]
`dotnet msbuild /t:"Restore;Build"`  this isn't supported, restore and build need to be done in different steps, or use `/Restore`  (unless msbuild started doing this automatically)

Is the project.assets.json file correct for System.ComponentModel/4.3.0?

**Comment by pakrym** [comment]
I suspect the problem is with the point where NuGets `.props` file is included, because removing only it is enough to repro the issue. `assets.json` looks fine.

**Comment by livarcocc** [comment]
Why can't you pass /restore when using dotnet msbuild? That should solve your problem and is exactly what we do when invoking dotnet build.

I am not sure what is the scenario or the fix that you are looking for here. Can you help me understand that?

**Comment by pakrym** [comment]
We'll change to pass `/Restore`, it just wasn't obvious that we have to do it.

**Comment by emgarten** [comment]
It's a common pain point unfortunately. But if the cause is the props file not getting picked up then it is due to running both targets together, when that happens msbuild doesn't check for the new files since it has already evaluated the imports.

**Comment by pakrym** [comment]
@emgarten, can we add a diagnostic into Restore task that would error out if it's used with other targets?

**Comment by dasMulli** [comment]
https://github.com/Microsoft/msbuild/issues/2677 suggests `Restore` should return a `RestoreResult` item indicating whether a new clean evaluation is actually required or not, maybe this result could also be used for some form of diagnostic check if the current state is probably faulty?

**Comment by emgarten** [comment]
We're working on returning the restore status, that is still in progress.

Failing if this happens would be great, but as far as I know there isn't a way to do this. It seems like MSBuild would need to check this.

**Comment by livarcocc** [comment]
Ok, I am closing this issue in the SDK side as this is being work by NuGet to return the RestoreResult and if possible, the subsequent change will have to happen in MSBuild.
