### ISSUE TITLE
FastUpToDate always complains not up to date

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/sdk#1787]
`MyProject.runtimeconfig.json` won't change if not modifying the target framework, and `FastUpToDate` says it's an output and wrote earlier than input.
By the way, the build log uses UTC time. Consider to print local time please.

**Comment by tannergooding** [comment]
For the first issue, do you have a simple repro that would assist in us validating/debugging this?

The second issue (build log using UTC time) would be a request for https://github.com/microsoft/msbuild

**Comment by huoyaoyuan** [comment]
I can repro it with a clean project on my computer:
Version: VS 15.4.5, .NET Core SDK 2.0.3

1. Create a new .NET Core 2.0 console project using VS.
2. Build it for the first time.
3. Press Ctrl+Shift+B again. It's reported as newest correctly.
4. Modify `Program.cs`. For example, just add `//` at the end of any line.
5. Build. Obvioursly a rebuild happens.
6. Press Ctrl+Shift+B again. Now the issue happens: FastUpToDate says not newest.

**Comment by tannergooding** [comment]
@huoyaoyuan, this is with the fast up to date check that the Project System is doing. MSBuild is correctly detecting all of the targets as up-to-date itself.


The MSBuild log shows
```
1>  Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the input files.
```

While the Fast Up to Date log shows
```
1>FastUpToDate: Latest write timestamp on input is 12/2/2017 10:58:12 PM on 'D:\Users\tagoo\source\repos\ConsoleApp2\ConsoleApp2\Program.cs'. (ConsoleApp2)
1>FastUpToDate: Earliest write timestamp on output is 12/2/2017 10:54:46 PM on 'D:\Users\tagoo\source\repos\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp2.0\ConsoleApp2.runtimeconfig.json'. (ConsoleApp2)
1>FastUpToDate: Project is not up to date. (ConsoleApp2)
```

I believe the bug should be moved to dotnet/project-system. FYI. @dotnet/project-system

**Comment by Pilchie** [comment]
This issue was moved to dotnet/project-system#3018
