### ISSUE TITLE
dotnet tool install failed because one of the nuget source is not available

### ISSUE THREAD

**Issue by chucklu** [dotnet/sdk#17875]
Hi team,
    I have 5 nuget source configured in C:\Users\username\AppData\Roaming\NuGet\NuGet.Config. Only one of them is not available, but why it will block the install?
    The nuget works fine with the configuration, it will skip the not available nuget source, and find the correct package.
     I expect the dotnet toll install will skip the not available nuget source, and try the sources one by one to find the package.
     Currently I just remove the bad source to make it work.
> C:\WINDOWS\system32>dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI --interactive
>   Determining projects to restore...
>   Retrying 'FindPackagesByIdAsyncCore' for source 'source/nuget/FindPackagesById()?id='specflow.plus.livingdoc.cli'&semVerLevel=2.0.0'.
>   Response status code does not indicate success: 503 (Service Unavailable).
>   Retrying 'FindPackagesByIdAsyncCore' for source 'source/FindPackagesById()?id='specflow.plus.livingdoc.cli'&semVerLevel=2.0.0'.
>   Response status code does not indicate success: 503 (Service Unavailable).
> C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : Failed to retrieve information about 'specflow.plus.livingdoc.cli' from remote source 'source/FindPackagesById()?id='specflow.plus.livingdoc.cli'&semVerLevel=2.0.0'. [C:\Users\clu\AppData\Local\Temp\3cnozzmh.zrl\restore.csproj]
> C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error :   Response status code does not indicate success: 503 (Service Unavailable). [C:\Users\clu\AppData\Local\Temp\3cnozzmh.zrl\restore.csproj]

**Comment by marcpopMSFT** [comment]
This was from NuGet design.  You can use the flag --ignore-failed-sources to get past this.

**Comment by chucklu** [comment]
@marcpopMSFT  Thanks,  but why don't you consider make it as the default option? One source failed should not block the others, this should be a better option.

> --ignore-failed-sources
> 
> Treat package source failures as warnings.

**Comment by marcpopMSFT** [comment]
I believe it was designed to match the existing NuGet behavior but I don't have the full history being that. @wli3 might know if there is a reason not to ignore failed sources by default.

**Comment by wli3** [comment]
https://github.com/NuGet/Home/issues/7035

tools command follows the same behavior as NuGet restore.

**Comment by chucklu** [comment]
@wli3  Thanks, I found the reason why I felt it's weird.
 

> All feeds have to be accessible in PackageReference for a restore to happen. This is by design as having different sources available can lead to drastically different resolution graphs.

Previously  I did not use the package reference. It seems the nuget would behave differently between PackageReference and packages.config. I mostly use the packages.config to add nuget reference, and it worked fine before. The PackageReference has different behavior.

**Comment by poojakatte** [comment]
> @marcpopMSFT Thanks, but why don't you consider make it as the default option? One source failed should not block the others, this should be a better option.
> 
> > --ignore-failed-sources
> > Treat package source failures as warnings.

thanks this worked for me!

**Comment by marcpopMSFT** [comment]
Adding @JonDouglas @aortiz-msft as we're matching the default nuget option. It'd be ideal if nuget itself changed the default behavior rather than me trying to chase down each place we call nuget and decide if it should change or not.
