### ISSUE TITLE
Failed to load the dll from [C:\Program Files (x86)\****\hostfxr.dll], HRESULT: 0x800700C1 The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\***\hostfxr.dll failed

### ISSUE THREAD

**Issue by robinNode** [dotnet/sdk#17872]
Hi,
Our application is build on .net 5 and our server is just upgraded to the latest version Windows 10 Enterprise 21H1. 
when i install our app on server. it can not be started. the following error comes out. 
Only the thing i found the 21H1 is not listed in .net5 supported OS list. does this mean it's not support or?
https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#supported-releases

If i run the dotnet-install.ps1 it will install .net core 3.* for me.
https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1

Description: **A .NET application failed.**
Application: SolutionBuilder.Service.exe
Path: C:\Program Files (x86)\***App.exe
Message: Failed to load the dll from [C:\Program Files (x86)\***\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\**\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

Platform:

**Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎5/‎21/‎2021
OS build	19043.985
Experience	Windows Feature Experience Pack 120.2212.2020.0**

PS C:\Users\**\Downloads> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 **OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\**

**Host (useful for support):
  Version: 3.1.15
  Commit:  dc339bd0fb**

.NET Core SDKs installed:
  3.1.409 [C:\Users\**\AppData\Local\Microsoft\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Users\**\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Users\**\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Users\**\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by robinNode** [comment]
I just uninstalled all sdks and only install the sdk which i needed and it works now. is it due to Host version? but i already installed the v5.0.3 sdk, why this setting did not get updated?


Host (useful for support):
Version: 3.1.15
Commit: dc339bd0fb

**Comment by marcpopMSFT** [comment]
@vitek-karas to take a look. Did you launch the app with dotnet.exe?  From the error, it's trying to find the x86 host so did you try installing the x86 runtime?

**Comment by vitek-karas** [comment]
If I had to guess - the app is starting as a 64bit process (if you run it via `dotnet app.dll` that would typically do it) but it's trying to load 32bit runtime (not sure why, it should not do that unless it's been told via env. variables for example).

* `dotnet info` in this case will only report 64bit runtimes/sdks. If you have 32bit runtimes/sdks installed, you would have to run the `dotnet.exe info` from the 32bit location to get information about those runtimes.
* Check the architecture of the app you're trying to run. If it's an .exe check that, if you run it through `dotnet app.dll`, which `dotnet.exe` is it using?
* You can enable detailed startup tracing. Set environment variables `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=host.txt` and then run the app in that environment. It will produce `host.txt` which will have detailed information of what was tried and why. If you want to share this file with us, please be aware that it may contain things like local paths, environment variables and potentially other information specific to the machine/user/app being run.

The error code 0x800700C1 basically means architecture mismatch - 64bit process trying to load 32bit binary (or vice versa).

**Comment by robinNode** [comment]
> 
> 
> @vitek-karas to take a look. Did you launch the app with dotnet.exe? From the error, it's trying to find the x86 host so did you try installing the x86 runtime?

No, it's an asp.net core web app and we run it as a service. 
there are few versions of the runtime being installed. because we are using .net core since 2.0

The problem is solved with uninstall all runtime and just install which is needed.
but i just want to know

**Comment by vitek-karas** [comment]
That info is the version of the host you're running, in this case the `hostfxr` version. It should be the latest available version on the machine - per architecture. It's important to know which architecture you're running when getting that info. On typical Windows there can be two architectures, x86 and x64. They live in different places (`C:\Program Files` for x64, and `C:\Program Files(x86)` for x86). The `dotnet` is currently only aware of the architecture it's running on. So if you run the `x64` dotnet it will report the version of the x64 host which might be different from the x86 host version.

So in this case I would pay attention to:
* Which `dotnet.exe` you're using to run `dotnet --info` and similar
* How do you run your app as a service - what is the process hosting the service - the bitness of it (x86 or x64)
* Which runtimes do you have installed in x86 and which for x64.

**Comment by robinNode** [comment]
As I mentioned above, I installed .net5 SDK. but the host is still in 3.1.15.

Host (useful for support):
Version: 3.1.15
Commit: dc339bd0fb

**Comment by vitek-karas** [comment]
Please pay attention to architectures. On Windows there can be two separate installations of .NET Core - the 32bit and 64bit one. They can have different versions available (the installers we provide are all architecture specific, so only install one architecture).

* What is the architecture of the process with the problem (x86 or x64)
* Try to run `C:\Program Files\dotnet\dotnet.exe --info` and `C:\Program Files (x86)\dotnet\dotnet.exe --info`. These will likely provide different lists of installed versions.

**Comment by DavoudEshtehari** [comment]
Link to a workaround: https://github.com/dotnet/sdk/issues/18325#issuecomment-1325856913

**Comment by Flithor** [comment]
For anyone else who arrived here: try deleting the release folder and re-release, sometimes it's just a nasty file version check bug.
(your publish folder contains some wrong runtime files but tools think they need not update)
