### ISSUE TITLE
Error FS1108: The type 'Object' is required here and is unavailable

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/sdk#1788]
If I pull the latest [Giraffe source code](https://github.com/dustinmoris/Giraffe/tree/develop) on Windows it builds totally fine, but when I pull the same code on macOS I am getting the following error:

```
error FS1108: The type 'Object' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

### Reproduction steps:

1. Pull repo
2. Run `./build.sh`

(If you don't have PowerShell installed on macOS then open ./build.sh and run the `export ...` command and then build `Giraffe.fsproj` by directly running `dotnet build ./src/giraffe/giraffe.fsproj`)

### Workaround:

I can fix this error by adding the following to the `Giraffe.fsproj` file:

```
<ItemGroup>
  <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
</ItemGroup>
```

... but I don't understand why I have to do this on macOS. Shouldn't it work the same on both environments?

I tried googling this issue and didn't really find anything which could explain the issue or what is going on. Is anyone able to shed some light on this please? Thank you!

### EDIT:

I shall mention that this project targets `net461` as well as `netstandard2.0`, but I don't think that this is the problem, because I have two other projects which also target both frameworks and they build fine on macOS without any additional references.

e.g.:
```
<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>
```

**Comment by JonCanning** [comment]
`<ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System.Runtime" />
  </ItemGroup>`

**Comment by dustinmoris** [comment]
@JonCanning Will give this a try when I am back on the macOS machine. I was able to "fix" this by [adding the netstandard reference only when on Unix and net461](https://github.com/dustinmoris/Giraffe/blob/develop/src/Giraffe/Giraffe.fsproj#L52-L54), but are you saying that adding a reference for System.Runtime is the only thing required?

**Comment by JonCanning** [comment]
It's worked for me so far

https://github.com/TinyBlueRobots/Hornbill/blob/master/src/Hornbill/Hornbill.fsproj

**Comment by livarcocc** [comment]
Seems like this has been resolved. Closing this issue. If that's not the case, just comment and I can re-activate it.
