### ISSUE TITLE
Bad CA1416(target platform) warning during XamlPreCompile

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/sdk#17890]
### Issue Description
After upgrading to VS(MSBuild) 16.10, false positive warnings are provided by built-in analyzer CA1416 claiming that calling Windows-only api, even the project has `windows` in its target framework and platform.

### Steps to Reproduce
* Create a WinUI 3 class library.
* Add something with xaml, e.g. a UserControl.
* Access some WinUI/WinRT code in csharp code behind. For example, touching `_ = DependencyProperty.UnsetValue;`.

### Expected Behavior
No warnings.

### Actual Behavior
Warning CA1416.

### Analysis
This is a side effect of https://github.com/dotnet/roslyn/issues/46300 and https://github.com/dotnet/msbuild/pull/6096 . CA1416 requires SDK generated `SupportedOSPlatformAttribute` to work correctly. However, `XamlPreCompile` is invoked before `CoreGenerateAssemblyInfo`, which is responsible for generating `SupportedOSPlatformAttribute`.

### Versions & Configurations
Visual Studio 16.10.0

### Attach a binlog

[binlog.zip](https://github.com/dotnet/msbuild/files/6540812/binlog.zip)

**Comment by BenVillalobos** [comment]
MSBuild Team Triage: Since CoreGenerateAssemblyInfo is defined in the SDK, we can't depend on it from common.targets. Can we safely add a `BeforeTargets=XamlPreCompile`?

**Comment by huoyaoyuan** [comment]
The compile process of WPF is quite different than WinUI. There may be little thing to compare with.

**Comment by RealTommyKlein** [comment]
Hi, I'm on the WinUI 3 team, and we're getting reports of this on VS 16.10.  @huoyaoyuan is correct (thanks!) - is it possible to move these targets to run before `$(CoreCompileDependsOn)`, which contains the `XamlPreCompile` target?  That way we're guaranteed to have this metadata before any CSC invocations.

**Comment by jlaanstra** [comment]
Is a possible solution to always set SkipAnalyzers to true for the XamlPreCompile target?
