### ISSUE TITLE
The links provided in the following two build error messages lead to the bing homepage instead of information about the problem

### ISSUE THREAD

**Issue by mesakomarevich** [dotnet/sdk#17900]
https://github.com/dotnet/sdk/blob/c26c3eec745d5350cf3d0bd6657553c0c7f1ec80/src/Tasks/Common/Resources/Strings.resx#L623-L626

https://github.com/dotnet/sdk/blob/c26c3eec745d5350cf3d0bd6657553c0c7f1ec80/src/Tasks/Common/Resources/Strings.resx#L701-L704

I'm not sure where the NETSDK1130 error should be pointing to (as I am not currently dealing with it), but I think the NETSDK1149 error should probably be pointing to something like [this](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance).

**Comment by marcpopMSFT** [comment]
@tdykstra It doesn't look like those two pages even exist.  Did you want to create the pages and I can update the aka.ms link or should we just remove the link from the error message?

**Comment by tdykstra** [comment]
I can create the pages -- I just need to know what we want to say about error cause and resolution in them. Do you know where I could find that information?

**Comment by mesakomarevich** [comment]
@tdykstra [this](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance) link seems to have all of the relevant information that someone would need in order to address NETSDK1149, as that link was the exact page that I used to resolve this issue in the project I was working on.

**Comment by marcpopMSFT** [comment]
@dsplaisted can probably put together some content for netsdk1130 if you want to use the link Mesa provided for 1149.

**Comment by tdykstra** [comment]
I'm creating a page for 1149, but I suggest we just use that for F1 and change the aka link to point directly to https://docs.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-enhance

**Comment by dsplaisted** [comment]
@angelazhangmsft to weigh in on the doc pages for these and where the links should point.

**Comment by angelazhangmsft** [comment]
@tdykstra I added comments to the docs PR for NETSDK1149. I created aka.ms links for NETSDK1130 and NETSDK1149 to this page: https://docs.microsoft.com/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed

That page should be more accurate as these errors can arise when consuming 3rd party WinRT components as well (not just calling WinRT APIs).

**Comment by marcpopMSFT** [comment]
Looks like the two aka.ms links in the original description of this issue now take you to a helpful doc page. Thanks for the help. I'm going to close this issue but feel free to reactivate if we think more is needed.
