### ISSUE TITLE
[dotnet sdk 6.0 - preview 4] dotnet pack --no-dependencies isn't supported anymore?

### ISSUE THREAD

**Issue by KubaOczko** [dotnet/sdk#17915]
With the latest dotnet sdk (6.0 - preview 4), the [--no-dependencies](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack) option ends with error: 
`MSBUILD : error MSB1001: Unknown switch.
Switch: --no-dependencies`

Is that an unknown breaking change or just a regullar issue?

Thanks

**Comment by marcpopMSFT** [comment]
@sfoslund did our move to system command line lose this option? I don't see it in the help output though do see it in our documentation (and don't recall a PR to remove it).

**Comment by sfoslund** [comment]
That error doesn't appear to be coming from the parser but rom MSBuild itself. @KubaOczko can you provide the full command you're using?

**Comment by KubaOczko** [comment]
@sfoslund Sure, here is the original command:
`dotnet pack ClassLibrary1.csproj -o .\nuget\ -c Release --no-dependencies --no-build`

I've tried it without any extra parameters, but no luck, the error is still the same:

```
Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: --no-dependencies

For switch syntax, type "MSBuild -help"

```

**Comment by sfoslund** [comment]
I'm able to repro this with `dotnet pack --no-dependencies` on a console app with 6.0 previews but not 5.0. It looks like with 5.0 this option is being translated into `-property:RestoreRecursive=false` whereas in 6.0 it's being passed directly to msbuild, which gets confused. 

@kartheekp-ms @heng-liu have there been any changes to the pack command on your end?
