### ISSUE TITLE
[ApiCompatibility] Add a new rule to detect breaking changes on updating contract of abstract classes/ interfaces

### ISSUE THREAD

**Issue by utpilla** [dotnet/sdk#17928]
Add a new rule to detect breaking changes when:

-  a new `abstract` method is added to  an already released `abstract` class
-  a new member is added to an already release `Interface`

**Comment by Anipik** [comment]
cc @safern @ericstj

**Comment by ericstj** [comment]
Agree with this.  I believe @safern had a number of rules we wanted to implement which were already in API Compat.  We just have the bare minimum implemented in package validation at the moment.

**Comment by safern** [comment]
Yes. I need to capture that list on issues. This was one of the guys I had on that list. Thank you for opening the issue.

**Comment by safern** [comment]
> a new member is added to an already release Interface

We should consider default interface implementations as a new member with a default implementation is not breaking. However we should explore how can we detect if it provided a default implementation and if that should be the default behavior, or if there should be a setting in API Compat that the user can set.
