### ISSUE TITLE
In VS 2019 16.11.0 Preview 1 and the WeatherTwentyOne sample fails to build iOS Simulator using paired macOS machine

### ISSUE THREAD

**Issue by hypermoose** [dotnet/sdk#17927]
Here is the error:

2>Could not execute because the specified command or file was not found.
2>Possible reasons for this include:
2>  * You misspelled a built-in dotnet command.
2>  * You intended to execute a .NET program, but dotnet-sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.ILLink.Tasks/build/../tools/net5.0/illink.dll does not exist.
2>  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.5.100-preview.4.638\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(354,3): error MSB6006: "dotnet" exited with code 1.
2>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

**Comment by wli3** [comment]
This issue was moved to xamarin/xamarin-macios#11808
