### ISSUE TITLE
VS 16.10 build regression - MSB4023: Cannot evaluate the item metadata "%(FullPath)".

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/sdk#17938]
Encountered with the WinUI build, moving from VS 16.8 to VS 16.10:

C:\a\1\s\.buildtools\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(624,5): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "C:\a\1\s\controls\test\MUXControlsTestApp\TAEF.Desktop\bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png;bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png;bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png". Path: C:\a\1\s\controls\test\MUXControlsTestApp\TAEF.Desktop\bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png;bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png;bin\Release\win10-x86\publish\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\a\1\s\controls\test\MUXControlsTestApp\TAEF.Desktop\MUXControlsTestApp.TAEF.Desktop.Package.wapproj] 

Appears to be related to this:
https://github.com/dotnet/sdk/commit/ba1bce0e0c437f0e0305eb12534f9e37ff1c6b5f

**Comment by sibille** [comment]
Not sure if this is the same issue, but we are seeing something similar on our build pipeline for WPF apps (.net core 3.1) with XamlIsland and MSIX packaging project (https://github.com/microsoft/WindowsTemplateStudio/issues/4323)

**Comment by rainersigwald** [comment]
@wli3 asked me a question offline that indicates he's looking into this.

**Comment by wli3** [comment]
@Scottj1s this error debug only there are duplicated relativepath which should not happen. So there is still a problem upstream.

**Comment by sibille** [comment]
@wli3 is there an ETA for this?

**Comment by wli3** [comment]
I should get this merge next week. And we will wait for the next servicing to show up

https://github.com/dotnet/sdk/pull/18052
