### ISSUE TITLE
[Package-Validation]Add support of package validation on system having sdk version less than net6.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#17936]
One of our customers were trying to use Microsoft.Dotnet.PackageValidation package without having .net 6.0 sdk installed.
This lead to failures where the tool was not able to find the depedencies like system.runtime.

This is because currently we ship only net6.0 and net472 assemblies.
I suggest to move net6.0 -> netcoreapp3.1 which  is out LTS

cc @ericstj @ViktorHofer @safern @joperezr

**Comment by joperezr** [comment]
Good catch, netcoreapp3.1 sounds good to me too. Ideally if there is already precedence for other tools in the sdk, we should just match the TFMs they multitarget for. 

BTW, probably also worth it to move net472 -> net461, in case folks are running on older versions of windows.

**Comment by ericstj** [comment]
I'd prefer not targeting older .NETFrameworks if we can avoid it.  I believe VS 2019 (dev 16) required net472, and this was targeted by MSBuild: https://github.com/dotnet/msbuild/commit/e22a46fe13333fb0cbe94e2b9ab33c0a705c8a72

I don't think we need to run in things older that VS 2019.
