### ISSUE TITLE
Where is the SDK 2.1.2 installer? (VS 15.5 includes it)

### ISSUE THREAD

**Issue by nil4** [dotnet/sdk#1799]
Upgrading Visual Studio 2017 to [version 15.5](https://blogs.msdn.microsoft.com/visualstudio/2017/12/04/visual-studio-2017-version-15-5-visual-studio-for-mac-released/) brings SDK version 2.1.2:

```cmd
> dotnet --version
2.1.2

> dotnet --info
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 [..snip..]
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

To upgrade build agents to the same SDK version, I searched [.NET Downloads](https://www.microsoft.com/net/download/windows) and [.NET Core downloads archive](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md), and the latest available version is 2.0.3, with SDK 2.0.3. 

Where is the SDK v2.1.2 installer?

**Comment by livarcocc** [comment]
cc @leecoward

**Comment by leecow** [comment]
We haven't released the 2.1.2 SDK outside of Visual Studio yet so will need to make that happen.

**Comment by nil4** [comment]
@leecow Yes, that is clear. What kind of timeline are we looking at? See also https://github.com/dotnet/cli/issues/8177

While the gears spin to make it happen, I have two suggestions.

1\. Update [this page](https://www.microsoft.com/net/download/windows) to amend the existing:

> #### .NET Core SDK
> Cross-platform .NET implementation. The smallest download to build .NET apps, using command line tools and any editor.

with a helpful footnote:
> \* *latest version only available with Microsoft Visual Studio on Microsoft Windows.*

2\. On a machine with VS 15.5 installed, find the 64-bit installer in the MSI Package Cache, e.g. at: `C:\ProgramData\Package Cache\{9651d4f8-e761-4b9b-ac03-6c2685f1f225}\dotnet-sdk-2.1.2-win-x64.exe`. Other platforms, refer to footnote above.

**Comment by nil4** [comment]
See also https://github.com/dotnet/core/issues/1131

**Comment by nil4** [comment]
Resolved as per https://github.com/dotnet/core/issues/1131#issuecomment-350411983
