### ISSUE TITLE
Adapt MSBuild logger to a NuGet logger

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#18]
When loading a LockFile, the API takes a NuGet.Common.ILogger.  In order to get good logging information from NuGet, we should implement a NuGet logger that can write to the MSBuild logger in our tasks that need to load a LockFile.

See the TODO in the LockFileCache class added in https://github.com/dotnet/sdk/pull/8.

**Comment by dsplaisted** [comment]
@emgarten What kind of errors / warnings could `LockFileUtilities.GetLockFile` log?  Should we be forwarding those as MSBuild errors and warnings when we call this method in an MSBuild task?

**Comment by emgarten** [comment]
Yes, they should be displayed to the user in the rare case something is logged there. NuGet logs an error if the file cannot be opened or the file is invalid.

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/sdk/pull/2083.
