### ISSUE TITLE
`dotnet pack` product broken .nupkg with the latest daily build(2.2.0-preview1)

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#1801]
Test with dotnet sdk `2.2.0-preview1-007736`/7622/7460, Windows 10 x64(17064).
And `2.1.1` in VS15.5preview5 works well.

# Step:
1. Install the latest daily build of sdk
2. `dotnet new classlib`
3. `dotnet pack`
4. Open the output .nupkg with `NuGet Package Explorer` or some zip manager( and try unpack it), and get an error.
5. Found the `.nuspec` file in the `nupkg` has wrong CRC(but the packed data is right)

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6267

**Comment by livarcocc** [comment]
Turns out that this is potentially an issue in the framework. Moving it to corefx.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/corefx#25803
