### ISSUE TITLE
Double prompted on first restore of project making use of SDK nuget packages

### ISSUE THREAD

**Issue by erinlah-ms** [dotnet/sdk#18037]
Reporting a bug where it appears I get prompted _twice_ for credentials the first time I restore our repo on a new machine. The issue only happens on repos where we've made use of the Microsoft.Build.Traversal sdk and other nuget-based SDKs, leading me to suspect that 

This  is a poor user experience. restore should only prompt for credentials once.

Repro:

1. On a new machine, install git, dotnetsdk 5.0.300, and azure devops credential supplyer.
2. Check out a repo with a traversal dirs and a private ADO artifacts nuget feed. Example provided below
3. dotnet restore dirs.proj

[Expected]
Get prompted once for credentials.

[Actual]
Get prompted twice for credentials.

Example output (Some elements censored)

```batch
aaronla@aaronla-x:CoreFramework$ dotnet restore dirs.proj --interactive
    [CredentialProvider]DeviceFlow: https://msazure.pkgs.visualstudio.com/One/_packaging/XXXXX/nuget/v3/index.json
    [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.

    **********************************************************************

    [CredentialProvider]DeviceFlow: https://msazure.pkgs.visualstudio.com/One/_packaging/XXXXX/nuget/v3/index.json
    [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code YYYYYYYYY to authenticate.

    **********************************************************************

...
```

Example repo:

https://msazure.visualstudio.com/One/_git/CoreFramework?path=%2F&version=GBdev%2Faaronla%2Fnew-image&_a=contents (MSFT FTE only)

**Comment by erdembayar** [comment]
@aaronla-ms 
Do you still experience this issue? If yes, could you be able to provide repro project/solution to investigate?

**Comment by aaronla-ms** [comment]
Yes, still experience this issue. It's intermittent though, seems to happen whenever my token expires. It seems to have been happening ever since we adopted a few Sdk style packages, but that's just a guess at the cause. We also use traversal targets (aka "dirs.proj") in our repo.

If you contact me internally on teams, I can point you at the internal repo in question.
