### ISSUE TITLE
Workloads vanished after update error

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#18076]
Recording this now from memory as I haven't had a chance to go back and try to reproduce this.

1. Install preview 4
2. elevate
3. using the program files install, dotnet workload install a few worklods
4. upgrade to preview 5
5. start an unelevated command prompt
6. dotnet workload list

C:\test\bug>dotnet workload list
Workload Id
microsoft-ios-sdk-full
microsoft-maccatalyst-sdk-full
microsoft-macos-sdk-full
microsoft-tvos-sdk-full

7. dotnet workload update (at this point I forgot to add the ADO Xamarin path to the NuGet.config file)

<snipped>
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: microsoft.net.workload.mono.toolchain.manifest-6.0.100 is not found in NuGet feeds https://www.nuget.org/api/v2/, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\",.
Installing pack Microsoft.iOS.Sdk version 14.5.100-preview.5.881...
Workload installation failed, rolling back installed packs...
Installation roll back failed: Access to the path 'C:\Program Files\dotnet\metadata\workloads\6.0.100\InstalledWorkloads\microsoft-ios-sdk-full' is denied.
Rolling back pack Microsoft.iOS.Sdk installation...
System.AggregateException: One or more errors occurred. (microsoft.ios.sdk::14.5.100-preview.5.881 is not found in NuGet feeds https://www.nuget.org/api/v2/;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\",)
<snipped>

8. dotnet workload list (no workloads found)

At this point, running update from an elevated command prompt didn't find any workloads to udpate.

**Comment by sfoslund** [comment]
Just repro'ed this, it looks like update removed the workload install records `dotnet\metadata\workloads\6.0.100\InstalledWorkloads\*`, this is a bug in the workload update rollback logic, I'll put a PR out to fix in main
