### ISSUE TITLE
[Loc] Assistance with translations

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/sdk#18082]

**Comment by crsuzukimsft** [comment]
Please clarify what will be the placeholder content in this case: "Successfully uninstalled workload(s): {0}"
File: /src/Cli/dotnet/commands/dotnet-workload/uninstall/xlf/LocalizableStrings.xlf
Resource ID: UninstallSucceeded

**Comment by sfoslund** [comment]
The '{0}' will be populated by a list of workload ids (which do not need to be localized). For example: `Successfully uninstalled workload(s): microsoft-ios-sdk-full microsoft-android-sdk-full`

**Comment by crsuzukimsft** [comment]
Thank you.
