### ISSUE TITLE
PrivateAssets="All" can be defeated by ResolveAssemblyReferences

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1808]
## Repro 
* SDK project A - net46 - copy-local project reference to B 
* SDK project B - net46 - package reference to C with PrivateAssets="All"
* B must actually use C.dll so that C.dll end up in B.dll's assembly refs

[ConsoleApp13.zip](https://github.com/dotnet/sdk/files/1543752/ConsoleApp13.zip) has this structure with A=ConsoleApp13, B=ClassLibrary1, and C=Microsoft.Build.

Due to privateassets="all" in B, A sees nothing about C in its project.assets.json, but when the project reference is resolved by RAR, it finds B's dependency on C in the closure walk and marks C to be copied from B's directory (since B is also going to be copied).

https://github.com/Microsoft/msbuild/pull/2759 actually disables this dependency search for nuget packages that are already resolved as primary references, but in the case of private assets of a project reference, there is no such primary reference to cause it to be disabled, so it would not fix this.

NOTE: This is cross-cutting. RAR is behaving by design here, so we need to gain enough control to prevent it from copying C somehow. This might mean we need more info in A's project.assets.json from nuget and/or require more knobs from MSBuild.

cc @DustinCampbell @jaredpar @cdmihai @emgarten

**Comment by cdmihai** [comment]
> but in the case of private assets of a project reference, there is no such primary reference to cause it to be disabled, so it would not fix this.

How can project references have transitive references with private assets that do not come from nuget via PackageReference? All the PackageReference dependencies with private assets would get fixed by Microsoft/msbuild#2759 right? In this example, C will be an externally resolved primary item to RAR, so it wouldn't be search next to B.

**Comment by nguerrera** [comment]
> In this example, C will be an externally resolved primary item to RAR,

No, in this example, there is nothing about C that is in the assets file or passed to RAR because the PrivateAssets="All" on B means "do not flow this asset to my consumers transitively".
