### ISSUE TITLE
[Question] How to convert Old WebForms csproj to the new csproj format?

### ISSUE THREAD

**Issue by ifle** [dotnet/sdk#1811]
How to convert Old WebForms csproj to the new csproj format? 
Is it possible?

**Comment by ifle** [comment]
1. Readable 
2. No more changes when we add or remove a file in a folder, allows works in VSCode
3. No git conflicts in merge
4. All files included in subdirectories using ** symbol
5. More easy nuget package management

**Comment by livarcocc** [comment]
We don't really have guidance on this.

.NET Core support libraries, console apps and asp.net core applications. It is very likely that you could get web forms working on the new csproj format, but it likely would not work with the .NET Core SDK. You would need full framework msbuild to work with your project.

As such, I am going to close the issue for now. If there is anything else, just comment and we can re-activate the issue.
