### ISSUE TITLE
Question about `DOTNETSDK_WORKLOAD_PACK_ROOTS`

### ISSUE THREAD

**Issue by radical** [dotnet/sdk#18139]
Shouldn't this be splitting `DOTNETSDK_WORKLOAD_PACK_ROOTS ` on `Path.PathSeparatorChar`?

https://github.com/dotnet/sdk/blob/6ad032c33749f1331535745cf32c64ef3ebfe0e0/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs#L39

**Comment by marcpopMSFT** [comment]
We believe this was fixed with an older PR already.
