### ISSUE TITLE
Improve compilation symbols when multi-targeting

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/sdk#1813]
The SDK defines a bunch of compilation symbols when multi-targeting.

For example, when targeting .NET Standard 1.3, developers can use `#if NETSTANDARD1_3` to conditionally use APIs that are available with that target framework.

However, when multi-targeting across different versions, developers have to use multiple of these. For example:

```
#if NETSTANDARD1_3 || NETSTANDARD1_6 || NETSTANDARD2_0
```

It would be nice to have more inclusive compilation symbols, so that a developer could, for example, use:

```
#if NETSTANDARD1_3_OR_GREATER
```

This would be defined when targeting .NET Standard 1.3, 1.4, 1.5, 1.6. 2.0, 2.1, etc., but not when targeting .NET Standard 1.0, 1.1, 1.2, or .NET Framework, Xamarin, .NET Core etc.

Doing so would decrease the friction when introducing a newer platform (e.g. .NET Standard 3.0 one day) to a multi-targeting library that aims to keep backwards compatibility for older runtimes, but also taking advantage of newer APIs where they are available.

Inspired by https://github.com/dotnet/csharplang/issues/1182

**Comment by dasMulli** [comment]
Also saw this on SO once: https://stackoverflow.com/questions/44208788/conditionally-compiling-for-a-minimum-version-of-net/44209523#44209523

At the moment this needs to be done through a custom target like

```xml
<Target Name="AddNetStdMinDefine" 
        BeforeTargets="CoreCompile"
        Condition="('$(TargetFrameworkIdentifier)' == '.NETStandard' and '$(TargetFrameworkVersion.Substring(1))' &gt;= '1.4')">
   <PropertyGroup>
     <DefineConstants>$(DefineConstants);IS_MIN_NETSTANDARD1_4</DefineConstants>
   </PropertyGroup>
</Target>
```

**Comment by yaakov-h** [comment]
This was added a few years ago:

https://learn.microsoft.com/en-us/dotnet/standard/frameworks#preprocessor-symbols
