### ISSUE TITLE
Remove interdependency between crossgen and store targets

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#1814]
The crossgen targets (in Microsoft.NET.CrossGen.targets) should be decoupled from the store targets (in Microsoft.NET.ComposeStore.targets) to allow them to be used independently. I came across this while trying to reuse crossgen targets in https://github.com/mono/linker/pull/192 to enable a crossgen step in the publish pipeline. I was able to reuse the targets that restore crossgen with some [workarounds](https://github.com/mono/linker/pull/192/files#diff-acb0851d1c12d340de503c4a2429c4f0R76), but not those that actually run crossgen.

Specifically, in the following dependency graph (I've outlined the crossgen-related targets), the following dependencies should be removed or replaced with targets not related to the store:
- _RestoreCrossgen -> PrepforRestoreForComposeStore
- _RunOptimizer -> _ComputeResolvedFilesToStoreTypes

There are also some implicit data dependencies between crossgen and store targets, which cause crossgen-related targets to break if they are called as dependencies of external targets (instead of as dependencies of ComposeStore). Here are the ones I've noticed:
- _RestoreCrossgen depends on _TFM, which is set by PrepareForComposeStore, requiring this [workaround](https://github.com/mono/linker/pull/192/files#diff-acb0851d1c12d340de503c4a2429c4f0R81).
- _GetCrossgenProps depends on ComposeWorkingDir, which is computed by PrepareForComposeStore, requiring this [workaround](https://github.com/mono/linker/pull/192/files#diff-acb0851d1c12d340de503c4a2429c4f0R92).

![img_20171130_110834](https://user-images.githubusercontent.com/787361/33902203-265b5032-df29-11e7-9129-799cbe13bee0.jpg)

**Comment by livarcocc** [comment]
This issue seems to be about supporting crossgen in build/publish. As such, let's use dotnet/cli#1437 to track that. I have closed other crossgen issues against that one before.
