### ISSUE TITLE
Windows update breaks dotnet sdk

### ISSUE THREAD

**Issue by KoakiMiku** [dotnet/sdk#18163]
Windows update breaks dotnet sdk... 😭

![image](https://user-images.githubusercontent.com/34326561/121282827-bb0e5000-c90c-11eb-92a2-0e966c0a3563.png)
![image](https://user-images.githubusercontent.com/34326561/121282936-e729d100-c90c-11eb-989c-05614386526d.png)
![image](https://user-images.githubusercontent.com/34326561/121282962-f1e46600-c90c-11eb-8024-d5062894d492.png)

**Comment by wli3** [comment]
@KoakiMiku "dotnet" on you PATH is x86 architecture. Note in the screen shot, all runtimes are in program files (x86). While the windows update is on program files.

This blog post might give you more context https://weblog.west-wind.com/posts/2019/Apr/20/Adventures-in-NET-SDK-Installation-SDKs-not-Showing-Up
