### ISSUE TITLE
Question: could we install global tools without SDK installed

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#18168]
Sometimes we wanna use `dotnet-dump` global tool to produce dump for analysis, for now, if we try to install a global tool without SDK installed, we would get an error like follows:

![image](https://user-images.githubusercontent.com/7604648/121310292-ccb81d80-c935-11eb-93eb-f94a8b07926a.png)

Wondering that if we could install global tools without SDK installed

**Comment by wli3** [comment]
You could reference https://github.com/dotnet/sdk/blob/main/documentation/general/tool-nuget-package-format.md

The tool package is wrapping around a framework-dependent application. If you have the required runtime, you can download the tool nupkg, unzip it and run the application inside.
