### ISSUE TITLE
Project references with ReferenceOutputAssembly=false still get runtimeconfig and deps.json files from referenced projects

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#18207]
In #14488, we fixed project references to Exe projects to copy the runtimeconfig.json and deps.json files to the referencing project.

However, for ProjectReferences with ReferenceOutputAssembly=false, the .exe itself is not copied but now the associated json files are getting copied.

Ideally we shouldn't copy these json files to the referencing project in this case.

**Comment by dsplaisted** [comment]
Actually, the .exe (renamed AppHost) is also copied from the referenced project if it targets .NET Core 3 or higher.

**Comment by dsplaisted** [comment]
Looks like the solution / workaround here is to set `Private` to `false` on the `ProjectReference`.  That will prevent "copy to output directory items" from the referenced project from being copied.

**Comment by marcpopMSFT** [comment]
Sounds like a workaround for this was found so closing for now.
