### ISSUE TITLE
[Package-Validation] Features need to be in PackageValidation with their target timeline.

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#18203]
List of features that we should try to get in MVP. Also listing the features we need to consume it more broadly in runtime repo.

- [x] Granular suppression (preview 6) ([In PR](https://github.com/dotnet/sdk/pull/18185))
- [x] Assembly Version Check (preview 6) (runtime)
- [x] Improving on how we display the errors https://github.com/microsoft/dotnet-blog/pull/640#discussion_r648764049 (Preview 6) (https://github.com/dotnet/sdk/issues/17495)
- [ ] Better support \ warnings when types have been forwarded (preview 6) (runtime)
- [ ] A Minimal set of api compat rules (preview 7)
- [ ] an option to pass dependencies for api compat (preview 7)
- [ ] Assemblies dependency validation (TBD)
- [x] Add DisablePackageBaselineValidation boolean flag (runtime)
- [ ] add support to donot run validation for out of support tfms
- [ ] add support for having correct package dependencies for compatible frameworks. https://github.com/dotnet/runtime/issues/52982#issuecomment-844427474

cc @ericstj @safern @joperezr @ViktorHofer

**Comment by joperezr** [comment]
> Assemblies dependency validation 

@Anipik can you ellaborate a bit what this means? Is it validating that compatible frameworks don't remove package dependencies like we do in dotnet/runtime? Or is this to validate that dependencies themselves get validated for assembly version?

**Comment by Anipik** [comment]
> @Anipik can you ellaborate a bit what this means? Is it validating that compatible frameworks don't remove package dependencies like we do in dotnet/runtime? Or is this to validate that dependencies themselves get validated for assembly version?


its more like the former i.e. Is it validating that compatible frameworks don't remove package dependencies like we do in dotnet/runtime

It will include we dont drop any dependencies between package versions which could break some people on upgrade.

**Comment by ericstj** [comment]
cc @terrajobst

**Comment by marcpopMSFT** [comment]
@mmitche is all the package validation tooling done? Can this be closed assuming no more work is planned?

**Comment by mmitche** [comment]
I do not know of existing package package that goes beyond icon validation and dependency validation. No new work is planned AFAIK.

**Comment by marcpopMSFT** [comment]
closing as no new work is planning
