### ISSUE TITLE
Is it safe to delete older .NET runtimes?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/sdk#18248]
![image](https://user-images.githubusercontent.com/4510984/121776897-e53c6800-cbc1-11eb-9f1b-eeb86d5ac437.png)

But why I only found 5.0.4 installer?

![image](https://user-images.githubusercontent.com/4510984/121776911-00a77300-cbc2-11eb-9e2b-ae01ae6dd5ca.png)

**Comment by joeloff** [comment]
Those were likely installed by Visual Studio and won't show up in Add/Remove Programs

**Comment by marcpopMSFT** [comment]
Generally you shouldn't delete the folders but rather uninstall through ARP or VS.
