### ISSUE TITLE
/ignoreprojectextensions:.dcproj not working

### ISSUE THREAD

**Issue by kurtisane** [dotnet/sdk#18259]
Hi everybody,
I've been using "dotnet restore /ignoreprojectextensions:.dcproj" in my .Net Core 3.1 projects before. Now I wanted to try this with .Net 5.0. The following dockerfile allows me to reuse the restore stage even during development and this increases buildtime by a lot. This either seems to be removed from the CLI or I'm missing something here. 

The following error is returned : error MSB3202: The project file "/src/docker-compose.dcproj" was not found.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS dotnet-prep
COPY . ./src/
RUN mkdir ./proj && cd ./src && \
  find . -type f -a \( -iname "*.sln" -o -iname "*.csproj" -o -iname "*.dcproj" \) \
    -exec cp --parents "{}" ../proj/ \;
    
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS dotnet-restore
WORKDIR /src
COPY --from=dotnet-prep ./proj .
RUN dotnet restore /ignoreprojectextensions:.dcproj

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS dotnet-publish
COPY --from=dotnet-restore ./root/.nuget ./root/.nuget
COPY --from=dotnet-restore ./src ./src/
COPY --from=dotnet-prep ./src ./src/
RUN dotnet publish "/src/Some/RRMBackend.Some.Api/RRMBackend.Some.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=dotnet-publish /app/publish .
ENTRYPOINT ["dotnet", "RRMBackend.Some.Api.dll"]

**Comment by KalleOlaviNiemitalo** [comment]
I guess you have to use `-ignoreprojectextensions:.dcproj` starting with a hyphen, to prevent `dotnet` from treating the option as a path.

**Comment by marcpopMSFT** [comment]
Closing as no replies since the suggested workaround. Let us know if this is still an issue.
