### ISSUE TITLE
Odd CS0006 error when using Microsoft.Extensions.Logging with multi-targeting

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/sdk#18269]
Error:

```
CS0006	Metadata file 'C:\Users\Kévin Chalet\.nuget\packages\microsoft.extensions.logging\5.0.0\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll' could not be found.
```

Repro:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0-preview.4.21253.7" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
  </ItemGroup>

</Project>
```

.NET SDK version: 6.0.100-preview.4.21255.9

Related discussion: https://twitter.com/kevin_chalet/status/1397568404458983426.

**Comment by safern** [comment]
cc: @dsplaisted @marcpopMSFT

**Comment by dsplaisted** [comment]
I think this is the same issue: #18148

It's true that the SDK is inferring the analyzers, but that's not something we want to do!  A lot of the issues with the current behavior are discussed here: https://github.com/NuGet/Home/issues/6279

We'd like for NuGet to write the analyzers that should be used to the assets file, so we don't have to have our own hacky conventions for analyzers in the SDK tasks.

**Comment by safern** [comment]
> I think this is the same issue: #18148

Yes this is a dupe. I will close this issue.
