### ISSUE TITLE
Build/Compilaion fails after 15.5.2 update to Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by badyalsk** [dotnet/sdk#1828]
Hi,
I'm not able to build my existing projects in .Net 4.0.  I tried new project but getting the same error while building/compiling project.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "TargetFrameworkDirectories" parameter is not supported by the "ResolvePackageFileConflicts" task. Verify the parameter exists on the task, and it is a settable public instance property.

I tried cleaning build, Build, Rebuild project but getting the same error. I'm stuck with VS update.

**Comment by badyalsk** [comment]
To fix this to above chaos, I have to repair Visual Studio 2017

**Comment by livarcocc** [comment]
Did the repair fix the problem for you?

@dsplaisted any idea how this could happen?

**Comment by badyalsk** [comment]
Yes, it fixed.

**Comment by livarcocc** [comment]
Going to close this issue as it has been a while and it seems that repairing the installation fixed it.
