### ISSUE TITLE
FYI: Nuget updates for .NET 6 Preview 5 (!) appear in Visual Studio Preview nuget manager when it's not released yet

### ISSUE THREAD

**Issue by JeepNL** [dotnet/sdk#18288]
FYI: Updates for .NET 6 Preview 5 (!) appear in Visual Studio Preview nuget manager when it's not released yet

![Screenshot 2021-06-16 105319](https://user-images.githubusercontent.com/39458532/122189600-59605f80-ce91-11eb-89ed-1b2fbe1ab468.jpg)

![Screenshot 2021-06-16 105605](https://user-images.githubusercontent.com/39458532/122189748-7bf27880-ce91-11eb-9a7e-edabd7df9703.jpg)

Link: https://github.com/dotnet/core/blob/main/release-notes/6.0/README.md

**Comment by Fabi** [comment]
Maybe they just forgot the official release with the new VS preview :D 
Many repos already have a Preview 5 version fixed for a few days 🤔
