### ISSUE TITLE
Razor target could be simplified to avoid escaping error

### ISSUE THREAD

**Issue by Forgind** [dotnet/sdk#18293]
https://github.com/dotnet/msbuild/issues/6203 reports an MSBuild (possibly unfixable) bug with escaping a quote. This can be worked around in the Razor targets (Microsoft.NET.Sdk.Razor.StaticWebAssets.targets) by simplifying the condition to `...StartsWith('wwwroot')...`

![image](https://user-images.githubusercontent.com/12969783/122245328-7e95a380-ce7a-11eb-896a-eccc1195bd91.png)

**Comment by marcpopMSFT** [comment]
@javiercn this code appears to be in the 5.0 static web assets target so probably isn't an issue anymore. Can we just resolve assuming the static web assets targets have changed enough that this is likely not an issue anymore?

**Comment by marcpopMSFT** [comment]
No response so closing for now. Please reactivate if we should take action.
