### ISSUE TITLE
The library hostfxr.dll was found, but loading it from [..] failed

### ISSUE THREAD

**Issue by ccornici** [dotnet/sdk#18325]
```
Description: A .NET Core application failed.
Application: myapp.exe
Path: C:\Program Files\WindowsApps\myapp\myapp.exe
Message: Failed to load the dll from [C:\Program Files\WindowsApps\myapp\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\WindowsApps\myapp\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

This is a WPF .NET Core 3.1 app packaged as MSIX or AppX or whatever name it has nowadays.

This happens randomly.
By that I mean it randomly started to happen.

Then I deleted the bin and obj folders from my projects and republished the bundle, then installed the test app with PowerShell, and it ran properly.

Then I made a new package and it doesn't work again.
Deleted bin/obj and republished and still doesn't work. Repeated 3 times and still doesn't work....

The hostfxr.dll file exists at the location which it complains about.

I also installed the app on a different machine and same error...

```
$ dotnet --version
5.0.301
```

**Comment by ccornici** [comment]
![image](https://user-images.githubusercontent.com/15718751/122456854-4e4f2180-cfae-11eb-927a-55cf31acc3b9.png)
This is from the Properties of the dll at the path mentioned in the error

**Comment by Silver-Fang** [comment]
Same error with WPF .Net 6 in MSIX

**Comment by DavoudEshtehari** [comment]
Same issue with .NET SDK 7.0 x86 on Windows 10.
```
Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\7.0.0\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\7.0.0\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

**Comment by DavoudEshtehari** [comment]
This is obviously an SDK installer problem. I leave the following notes for who has the similar issue.

To verify if it's an architecture conflict, I used a fresh Win 10 VM and installed the [.NET 7.0 SDK win-x86](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.100-windows-x86-installer), which works fine without any issue.
In addition, on my machine with the reported issue, I installed the same .NET SDK through PowerShell using [dotnet-install](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) script, which can be used as a workaround:

``` PowerShell
> Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1

> .\dotnet-install.ps1 -Channel 7.0 -Architecture x86 -InstallDir "C:\x86\"
```

**Comment by Corbie-42** [comment]
I have the same issue when running `dotnet test` from the terminal. In my tests, I start a my ASP .NET Core 7.0 application with `Process.Start` and the process terminates with the abovementioned error (exit code `-2147450750`).

From Visual Studio 2022 my tests run fine, but I cannot run them from the terminal.

**Comment by marcpopMSFT** [comment]
Old issue triage: Closing out as this was likely a point in time installation issue. It could be related to https://aka.ms/dotnet/x86path given the comment from 2022. Please let us know if this is still happening.
