### ISSUE TITLE
Workload installation failing

### ISSUE THREAD

**Issue by timheuer** [dotnet/sdk#18326]
Trying to install a workload and getting an exception

Running: `dotnet workload install microsoft-net-sdk-blazorwebassembly-aot`

```
Failed to update the advertising manifest microsoft.net.workload.android: microsoft.net.workload.android.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Failed to update the advertising manifest microsoft.net.workload.blazorwebassembly: microsoft.net.workload.blazorwebassembly.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Failed to update the advertising manifest microsoft.net.workload.ios: microsoft.net.workload.ios.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Failed to update the advertising manifest microsoft.net.workload.maccatalyst: microsoft.net.workload.maccatalyst.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Failed to update the advertising manifest microsoft.net.workload.macos: microsoft.net.workload.macos.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Failed to update the advertising manifest microsoft.net.workload.tvos: microsoft.net.workload.tvos.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, D:\source\repos\DumbNugetLib\DumbNugetLib\bin\Debug",.
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.4.21253.7...
Workload installation failed, rolling back installed packs...
Rolling back pack Microsoft.NET.Runtime.MonoAOTCompiler.Task installation...
```

dotnet-info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b
```

**Comment by tomrus88** [comment]
Also have issues with workloads in .NET 6 Preview 5, but error is different
Running `dotnet workload update` results in following error:

> Updated advertising manifest microsoft.net.sdk.android.
> Updated advertising manifest microsoft.net.sdk.ios.
> Updated advertising manifest microsoft.net.sdk.maccatalyst.
> Updated advertising manifest microsoft.net.sdk.macos.
> Updated advertising manifest microsoft.net.sdk.tvos.
> Updated advertising manifest microsoft.net.workload.mono.toolchain.
> Garbage collecting for SDK feature bands ...
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\metadata\workloads\InstalledPacks\v1'.
>    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) in System.IO.FileSystem.dll:token 0x6000214+0x46
>    at System.IO.Enumeration.FileSystemEnumerator`1.Init() in System.IO.FileSystem.dll:token 0x6000212+0x92
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) in System.IO.FileSystem.dll:token 0x60001d2+0x2c
>    at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x60001e8+0x14
>    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x600009d+0x6e
>    at System.IO.Directory.GetDirectories(String path) in System.IO.FileSystem.dll:token 0x6000095+0x0
>    at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.GarbageCollectInstalledWorkloadPacks() in dotnet.dll:token 0x60001b5+0x60
>    at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UpdateWorkloads(Boolean includePreviews) in dotnet.dll:token 0x6000156+0xb1
>    at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute() in dotnet.dll:token 0x6000154+0x131
>    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x60008ca+0x5e
>    at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args) in dotnet.dll:token 0x6000146+0x6
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x6000933+0x2e8
>    at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x6000931+0x6f

**Comment by rajeshaz09** [comment]
Delete **C:\Program Files\dotnet\metadata\workloads** folder and install once again.

**Comment by pkanavos** [comment]
Perhaps it's because Preview 4 manifests are still on the machine? The error mentions Preview 4: 
```
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.4.21253.7
```

I run into workload issues as well, described in issue [18350](https://github.com/dotnet/sdk/issues/18350). Looks like the manifest folder names in `/usr/local/share/dotnet/sdk-manifests` changed between Preview 4 and Preview 5. Installing Preview 5 placed duplicate manifests into different folders instead of overwriting the existing ones.

I deleted the older manifest folders just to get `dotnet new` working again. 

I risked running `dotnet workload install microsoft-net-sdk-blazorwebassembly-aot` (`sudo dotnet ...` on a Mac) and the operation worked :

```
❯ sudo dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
Password:

Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Installing workload manifest microsoft.net.sdk.tvos version 14.5.100-preview.5.894.
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.5.28.
Installing workload manifest microsoft.net.sdk.macos version 11.3.100-preview.5.894.
Installing workload manifest microsoft.net.sdk.maccatalyst version 14.5.100-preview.5.894.
Installing workload manifest microsoft.net.sdk.ios version 14.5.100-preview.5.894.
Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 6.0.0-preview.5.21301.5...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 6.0.0-preview.5.21301.5...
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.5.21301.5...
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.5.21301.5...
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.5.21301.5...
Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.5.21301.5...
Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 6.0.0-preview.5.21301.5...
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 6.0.0-preview.5.21301.5...
Installing pack Microsoft.NET.Runtime.Emscripten.Node version 6.0.0-preview.5.21281.1...
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Node version 6.0.0-preview.5.21281.1...
Installing pack Microsoft.NET.Runtime.Emscripten.Python version 6.0.0-preview.5.21281.1...
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Python version 6.0.0-preview.5.21281.1...
Installing pack Microsoft.NET.Runtime.Emscripten.Sdk version 6.0.0-preview.5.21281.1...
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Sdk version 6.0.0-preview.5.21281.1...
Garbage collecting for SDK feature bands 6.0.100...

Successfully installed workload(s) microsoft-net-sdk-blazorwebassembly-aot.
```
No new manifest folders appeared. It looks like new folders were added in `/usr/local/share/dotnet/packs`

**Comment by sfoslund** [comment]
@timheuer was this the entire output? Is this issue reproing reliably? Are you using an elevated command prompt? It seems like it isn't able to download any nuget packages, do you an abnormal nuget setup?

**Comment by timheuer** [comment]
@sfoslund yes this was entire output -- I worked through this with @dsplaisted and we were able to get past this (manually deleting folders)

**Comment by sfoslund** [comment]
> we were able to get past this (manually deleting folders)

Were there any action items from that discussion or are we good to close this then?

**Comment by dsplaisted** [comment]
We can close this.  We discovered that maui-check for Preview 4 may have left some files in the old manifest folders, which means that they wouldn't be deleted when upgrading to preview 5.  The latest version of maui-check should delete them.  I updated the known issues: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#preview-5

**Comment by jkears** [comment]
Not sure if this is related, but was attempt to update workload .... 

> Workload update failed: One or more errors occurred. (Version 8.0.21 of package microsoft.maui.graphics.win2d.winui.desktop.msi.x64 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://nwnuget.azurewebsites.net/nuget;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json".)
