### ISSUE TITLE
Invalid TrimEnd function usage in Microsoft.NET.TargetFrameworkInference.targets#L51

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#1833]
https://github.com/dotnet/sdk/blob/7fc8f64b89f5a69bb8043bae814b314b6ce6841f/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.TargetFrameworkInference.targets#L51

`$(TargetFramework.TrimEnd('.0123456789'))`

MSBuild Expander doesn't like this TrimEnd

**Comment by KirillOsenkov** [comment]
Hmm, how does this work? It seems to work fine. Does MSBuild convert this to a char array?

**Comment by KirillOsenkov** [comment]
From `net461` it returns `net`.

**Comment by KirillOsenkov** [comment]
Ah, never mind, turns out MSBuild does coercion from string to char[] here:
https://github.com/Microsoft/msbuild/blob/5213af78d17613417e5b715e7f83100dc1574ad6/src/Build/Evaluation/Expander.cs#L3638

This is by design then.

@nguerrera Could you please confirm that the line in the SDK targets does what you expect? From `net461` to `net`? If so, please close this issue.

Thanks!

**Comment by KirillOsenkov** [comment]
I'm going to close this as it's most likely by design.

**Comment by nguerrera** [comment]
Yes, it is by design. We want the part of the target framework before the first dot or digit.
