### ISSUE TITLE
Warning CS0105 - The using directive for 'System' appeared previously in this namespace - C# 10 and .NET 6.0

### ISSUE THREAD

**Issue by anuraj** [dotnet/sdk#18345]
I created a console app in .NET 6.0 with C# 10 features. I moved all the namespace using statements to `imports.cs` file. 

```
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
```

I removed all the namespace using statements from `Program.cs` file. 

```
namespace ConsoleApp49
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

And when I am compiling the app with `dotnet build` command I am getting two warnings.

`warning CS0105: The using directive for 'System' appeared previously in this namespace`

Screenshot

![image](https://user-images.githubusercontent.com/276411/122498963-abc68b00-d00d-11eb-96b3-05a6134a940a.png)

Here is the Project file.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>
```

**Comment by PathogenDavid** [comment]
Earlier this week LDM [made the decision](https://github.com/dotnet/csharplang/blob/70fc3eb70379d5618ca9d2ae2dc897e02b92b678/meetings/2021/LDM-2021-06-21.md#email-decision-duplicate-global-using-warnings) to remove duplicate using warnings caused by global using statements, so this issue should resolve its self by the final release of C# 10.

**Comment by marcpopMSFT** [comment]
Old issue triage: Per the comment above, the final release of c# 10 should have resolved this so closing out. Please ping if it's still an issue.
