### ISSUE TITLE
Workload installation failed: Workload not found

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sdk#18343]
```
dotnet workload install microsoft-android-sdk-full

Workload installation failed, rolling back installed packs...
Installation roll back failed: Workload not found
Workload installation failed: Workload not found
```

**Comment by sfoslund** [comment]
@Varorbc can you provide the version of the SDK that you're seeing this with (`dotnet --info`) as well as the content of the `dotnet\sdk-manifests\6.0.100` dir?

**Comment by Varorbc** [comment]
@sfoslund 
![image](https://user-images.githubusercontent.com/5714438/122844547-7b942a80-d334-11eb-8f16-87fa816f695c.png)
![image](https://user-images.githubusercontent.com/5714438/122844556-83ec6580-d334-11eb-9d9f-0b191e8aa099.png)

**Comment by sfoslund** [comment]
The issue appears to be that you don't have the sdk-manifests dir installed. How did you install this SDK? Did it come with VS17 preview 1?

**Comment by Varorbc** [comment]
Maybe I deleted it by mistake.
Why does the directory not exist and prompt that the workload cannot be found? Can the tool add a directory when the directory does not exist?

**Comment by Varorbc** [comment]
I reinstalled vs 17, and found that the sdk disappeared and the directory did not appear
![image](https://user-images.githubusercontent.com/5714438/123020861-908cbe80-d405-11eb-9ec8-a7ab636143f5.png)
![image](https://user-images.githubusercontent.com/5714438/123020885-9c788080-d405-11eb-9ee1-5bda8f4678f7.png)
![image](https://user-images.githubusercontent.com/5714438/123020909-a7331580-d405-11eb-80bf-b04664556a4b.png)

**Comment by sfoslund** [comment]
This is a known issue with dev17: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#1-missing-workload-manifests-in-visual-studio-17-preview-1, can you please install a standalone version or preview 5 to work around this? Thanks!

**Comment by Varorbc** [comment]
thanks
