### ISSUE TITLE
Allow all configProperties in csproj

### ISSUE THREAD

**Issue by kasper3** [dotnet/sdk#1835]
runtimeOptions->configProperties are allowed in csproj: https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#runtimeoptions

There is a new option introduced for invariant globalization:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md#enabling-the-invariant-mode

Allowing this to be set in proj files as `<InvariantGlobalization>true</InvariantGlobalization>` will make it consistent with rest of the set.

For such future properties and if it is safe, can there be an automatic key pattern mapping that will transform any `<namespace>.<type>.<feature>.<property>` in runtimeconfig.json under configProperties to `<feature><property><type>` and `<namespace>.<type>.<feature>` to `<feature><type>` in camel-casing in project files?

**Comment by dasMulli** [comment]
In theory, this should already work though 

```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="Key.Path.For.Prop" Value="theValue" />
</ItemGroup>
```

To allow setting it via a single property, the configuration option would need to be wired up to a convenience property [like the others](https://github.com/dotnet/sdk/blob/720882a6c3b237855f07f4214d91091c667078f5/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L195-L215).

**Comment by kasper3** [comment]
Thanks, sent the PR to update doc. Would make lives bit easier if the convenience properties are programmatically generated.

**Comment by livarcocc** [comment]
Seems like the issue has been addressed by @dasMulli. @dasMulli thank you once again. I am going to close this issue. If there is something else that needs to be addressed, please comment and I can re-activate it.
