### ISSUE TITLE
dotnet test on windows uses an x86 test host

### ISSUE THREAD

**Issue by odalet** [dotnet/sdk#18353]
Environment:

* .NET SDK 5.0.202
* Windows 10 x64
* .NET Standard 2.0 assembly
* Tested by a .NET Framework 4.7.2 unit test assembly
* Using MSTest 2.1.2 and Microsoft.NET.Test.Sdk 16.9.4 nugets

Repro:

A simple lib exposes this method:

```csharp
public static string GetBitness() => IntPtr.Size == 8 ? "x64" : "x86";
```

The unit test looks like this:

```csharp
[TestMethod]
public void GetBitness_call_should_return_x64()
{
    var bitness = Lib.GetBitness();
    Assert.AreEqual("x64", bitness, $"Expected x64, but got {bitness}");
}
```

Now, build and test:

```powershell
dotnet build test.sln --configuration Release
dotnet test test.sln --configuration Release --no-build
```

* Expected outcome: the test succeeds
* Actual: `Échec de Assert.AreEqual. Attendu : <x64>, Réel : <x86>. Expected x64, but got x86`

----

* How comes `dotnet test` does not default to running its x64 test host (I've browsed through older issues that stated that eveyrting 'dotnet' was always using the bitness of the installed framework and my .NET Core/5 frameworks are all installed using the x64 build)?
* I've tried to add `<Platform>x64</Platform>` and even `<Prefer32Bit>false</Prefer32Bit>` to my test project to no avail
* I ended having my test pass by adding `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` in the test csproj. This did the trick, but I really wonder why `dotnet test` wouldn't default to an x64 host process!

**Comment by nohwnd** [comment]
This is on .NET Framework 4.7.2 in there we prefer x86 to be compatible with the behavior in VS (but for .NET Framework only). You can force the execution to be x64 by `/platform:x64`.

**Comment by odalet** [comment]
@nohwnd and to anybody experiencing the same issue:

* If testing a `csproj` with `dotnet test`, the syntax should be: 

```powershell
> dotnet test foo.csproj -property:Platform=x64
```

This passes the Platform=x64 property to MSBuild and, this way, the project is rebuilt with the x64 bit set in the assembly. 

However, this does not work when dotnet testing a solution that's only made of `Any CPU projects`...

* If testing a solution, the incantation is: 
 
```powershell
> dotnet test foo.sln -- RunConfiguration.TargetPlatform=x64
``` 

This way, one can pass any setting supported by the `.runsettings` format. This is all explained [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test) and I checked it works.

> NB: the latter also works for csproj and it has the additional benefi not to rebuild the test project (it simply selects an x64 runner). So I think this will be my preferred way of testing x64-dependent code.

**Comment by nohwnd** [comment]
Thanks for the overview. This is yet another place where it shows that dotnet test + csproj / sln and dotnet test + dll are two different commands smashed into one.
