### ISSUE TITLE
Value parsing

### ISSUE THREAD

**Issue by matkoch** [dotnet/sdk#1836]
The invocation:

```
C:\xxx\dotnet.exe publish C:\code\xxx.csproj --configuration Debug --framework netstandard2.0 --force --no-dependencies --self-contained /p:AssemblyVersion=0.1.0.0 /p:FileVersion=0.1.436 /p:InformationalVersion=0.1.436+Branch.master.Sha.45bedb36a75756fad
```

Fails with:

> C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(130,23): error MSB4030: "/p:AssemblyVersion=0.1.0.0" is an invalid value for the "IsSelfContained" parameter of the "GenerateDepsFile" task. The "IsSelfContained" parameter is of type "System.Boolean".

When I change the framework to `net461`, everything works fine. Seems that parsing of additional msbuild properties is not working properly.

**Comment by livarcocc** [comment]
If you are passing anything after --self-contained, you need to pass true or false. Otherwise the parser thinks that /p:AssemblyVersion... is the self-contained value being passed in.

Also, netstandard2.0 is not a valid value for an app. netstandard is a library tfm, which may indicate why it works if you pass net461.

**Comment by matkoch** [comment]
> If you are passing anything after --self-contained, you need to pass true or false. Otherwise the parser thinks that /p:AssemblyVersion... is the self-contained value being passed in.

I understand, but that's the issue here. Either it should fail for both, or for none.

> Also, netstandard2.0 is not a valid value for an app. netstandard is a library tfm, which may indicate why it works if you pass net461.

Not sure about this. The project defines `net461` and `netstandard2.0` as target frameworks. It's a library, not an app. From https://docs.microsoft.com/en-us/dotnet/standard/frameworks I understand, that I can pass `netstandard2.0` as value for `--framework`. Or am I wrong?

**Comment by livarcocc** [comment]
if it is a library, there is no point in making it self-contained. That's an application concept.
