### ISSUE TITLE
[Pack] Error “MSB1001: Unknown switch” occurs when running command “dotnet pack --runtime win10-x64” following the example on the “dotnet pack” page

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#18369]
@v-luzh commented on [Fri, 18 Jun 2021 09:29:49 GMT](https://github.com/NuGet/Home/issues/10955)
## Details about Problem
VS Version: Main\31417.287
NuGet Version: Dev\6.0.0.123
OS Version: Windows-10-Enterprise-21H1
Dotnet SDK: 6.0.100-preview.5.21302.13
## Repro steps
1.	Launch VS and create a new C# Class Library (.NET 6.0).
2.	Open the Developer Command Prompt and cd to the project path.
3.	Run “dotnet pack --runtime win10-x64” following the example on the [dotnet pack](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x) page.
## Expected
Runing command “dotnet pack --runtime win10-x64” should be successful.
## Actual
Error “MSB1001: Unknown switch” occurs when running command “dotnet pack --runtime win10-x64” as below screenshots.
![image](https://user-images.githubusercontent.com/20632625/122538047-c2de9a80-d058-11eb-83e6-e16d3ae02609.png)
## Note: 
1.We didn’t find any switch: --runtime after running the command “MSBuild -help”.
2.It didn't repro on D16.8\30420.98 with implicit NuGet 5.8.0.6776 with .NET SDK 5.0.100-preview.8.20417.9.

**Comment by nkolev92** [comment]
Something seems to have changed with the parsing. 

Note that this works in `5.0.300` but fails in `6.0 previews`

**Comment by nkolev92** [comment]
I looked at https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs vs https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs and it seems like the implicit command parsing has changed. 

Our test team found it as they were following the documentation.

**Comment by marcpopMSFT** [comment]
@sfoslund system command line fallout perhaps?

**Comment by sfoslund** [comment]
Looks like I missed that the command was being created with restore options: https://github.com/dotnet/sdk/blob/release/5.0.3xx/src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs#L15. Should be a one line change to fix like this: https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs#L39, I'll make the change.
