### ISSUE TITLE
Workload update error

### ISSUE THREAD

**Issue by tomrus88** [dotnet/sdk#18383]
I have issues with workloads in .NET 6 SDK Preview 5. Running `dotnet workload update` command results in following error:
```
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Garbage collecting for SDK feature bands ...
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\metadata\workloads\InstalledPacks\v1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) in System.IO.FileSystem.dll:token 0x6000214+0x46
   at System.IO.Enumeration.FileSystemEnumerator`1.Init() in System.IO.FileSystem.dll:token 0x6000212+0x92
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) in System.IO.FileSystem.dll:token 0x60001d2+0x2c
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x60001e8+0x14
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x600009d+0x6e
   at System.IO.Directory.GetDirectories(String path) in System.IO.FileSystem.dll:token 0x6000095+0x0
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.GarbageCollectInstalledWorkloadPacks() in dotnet.dll:token 0x60001b5+0x60
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UpdateWorkloads(Boolean includePreviews) in dotnet.dll:token 0x6000156+0xb1
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute() in dotnet.dll:token 0x6000154+0x131
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x60008ca+0x5e
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args) in dotnet.dll:token 0x6000146+0x6
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x6000933+0x2e8
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x6000931+0x6f
```

**Comment by AraHaan** [comment]
I also come across another preview 5 Sdk bug as well whenever I invoke ``dotnet build`` on my machine after a fresh install.
```
warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: microsoft-tvos-sdk-full
```

Updating it to Preview 6 and 7 fixes it however it's not public and so when I go into CI builds it fails because the setup-dotnet github action only can find Preview 5 as the "latest" in the 6.0 feed it goes from on the install script.

I am not sure how the repositories like dotnet/winforms for example used the install script to rig preview 6 or 7 to download and install.

**Comment by AraHaan** [comment]
> I have issues with workloads in .NET 6 SDK Preview 5. Running `dotnet workload update` command results in following error:
> 
> ```
> Updated advertising manifest microsoft.net.sdk.android.
> Updated advertising manifest microsoft.net.sdk.ios.
> Updated advertising manifest microsoft.net.sdk.maccatalyst.
> Updated advertising manifest microsoft.net.sdk.macos.
> Updated advertising manifest microsoft.net.sdk.tvos.
> Updated advertising manifest microsoft.net.workload.mono.toolchain.
> Garbage collecting for SDK feature bands ...
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\metadata\workloads\InstalledPacks\v1'.
>    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) in System.IO.FileSystem.dll:token 0x6000214+0x46
>    at System.IO.Enumeration.FileSystemEnumerator`1.Init() in System.IO.FileSystem.dll:token 0x6000212+0x92
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) in System.IO.FileSystem.dll:token 0x60001d2+0x2c
>    at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x60001e8+0x14
>    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x600009d+0x6e
>    at System.IO.Directory.GetDirectories(String path) in System.IO.FileSystem.dll:token 0x6000095+0x0
>    at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.GarbageCollectInstalledWorkloadPacks() in dotnet.dll:token 0x60001b5+0x60
>    at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UpdateWorkloads(Boolean includePreviews) in dotnet.dll:token 0x6000156+0xb1
>    at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute() in dotnet.dll:token 0x6000154+0x131
>    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x60008ca+0x5e
>    at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args) in dotnet.dll:token 0x6000146+0x6
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x6000933+0x2e8
>    at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x6000931+0x6f
> ```

I tried that command in the preview 6 and 7 sdk and it did not throw any exceptions. Perhaps it was fixed in those previews that can be installed manually from the readme from the dotnet/installer repository.

**Comment by sfoslund** [comment]
@tomrus88 based on the error it looks like you don't have any workloads installed before you run update, is that correct?

**Comment by AraHaan** [comment]
> @tomrus88 based on the error it looks like you don't have any workloads installed before you run update, is that correct? I'm not able to repro this with the latest main builds, do you have any further repro steps?

oh ironic, I had workloads installed too before I updated from p4 -> p7 on my mac and ran the update command and somehow it instead just deleted them so now they do not show up at all in future invokes of the command.

**Comment by sfoslund** [comment]
Hmm, I haven't heard of that specific issue before but in general we don't guarantee compat across preview versions, so it's best practice to uninstall the older preview/ workloads before installing the new versions.

**Comment by tomrus88** [comment]
> @tomrus88 based on the error it looks like you don't have any workloads installed before you run update, is that correct? I'm not able to repro this with the latest main builds, do you have any further repro steps?

I've never installed any of them myself, so unless they are pre installed I guess I don't have any installed.

**Comment by sfoslund** [comment]
Yes, that means you have no workloads installed then. You can install workloads first using the `dotnet workload install` command, then when you update you shouldn't get this issue. That being said, we obviously don't want errors on a no-op workload update so I'll look into fixing this error :)

**Comment by sfoslund** [comment]
Just checked and this has been fixed in preview 6 and later by this PR: https://github.com/dotnet/sdk/pull/17933. I'll close this issue, but feel free to reopen if you have further questions, thanks.
