### ISSUE TITLE
[Feature] Ignore failed sources by default when installing new tool

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/sdk#18402]
I'm not the first to file a ticket of this nature, but I think I'm the first to explicitly ask that this be added as a feature and not reporting it as a possible bug (seen [here](https://github.com/dotnet/sdk/issues/16215) and [here](https://github.com/dotnet/sdk/issues/14547)) 

When installing a tool using `dotnet update` or `dotnet install`, if you have a private NuGet source configured, it will fail with:

``` 
Tool 'whatever` failed to update due to the following:
The tool package could not be restored.
Tool 'whatever' failed to install.
```

It includes some suggestions on resolving the issue under it. Missing from those instructions is a line to simply add `--ignore-failed-sources` to the arguments.

**I write this ticket to ask that this flag be set to true by default instead of having to be explicitly added.** Throw an error like this if the same tool is found in more than one source, but if the very first check is a private NuGet feed (our company Azure DevOps artifacts feed in my case), of course it's not going to find the publicly available tool, but it should keep looking through the sources until it does (as it does with said flag).

Given that installing a NuGet package looks through all the sources by default without failing at the first failed lookup, it strikes me as odd that dotnet tool installs don't behave the same way.

Thank you for your time and consideration.

**Comment by marcpopMSFT** [comment]
@JonDouglas We are matching the defaults that nuget has. Is there a reason NuGet doesn't default to exclude failed sources?  Is there a reason we shouldn't?

CC @KathleenDollard
