### ISSUE TITLE
Running dotnet CLI command causes dotnet process to stay alive

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#18410]
The `dotnet.exe` process stays running after running certain CLI commands.  I've tried the `new` and `tool install` commands and they both cause this behavior.  This is a regression in 6.0 Preview 6 that occurred between builds 6.0.100-preview.6.21316.11 and 6.0.100-preview.6.21320.7.

## Repro

1. Install https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.6.21320.7/dotnet-sdk-6.0.100-preview.6.21320.7-win-x64.exe

2. In a PowerShell console:

```powershell
> dotnet new console

The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\mthalman\test\test.csproj...
  Determining projects to restore...
  Restored C:\Users\mthalman\test\test.csproj (in 92 ms).
Restore succeeded.  

> ps -Name dotnet

NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
------    -----      -----     ------      --  -- -----------
    50    49.64      77.48       2.16   17088   1 dotnet    
```

**Comment by mthalman** [comment]
cc @marcpopMSFT

**Comment by richlander** [comment]
Perhaps this is the build server? Does calling `shutdown` on it (naturally) kill the process?

https://docs.microsoft.com/dotnet/core/tools/dotnet-build-server

**Comment by mthalman** [comment]
> Perhaps this is the build server? Does calling `shutdown` on it (naturally) kill the process?

Yes, that looks like it could be it.

```console
> dotnet build-server shutdown
Shutting down MSBuild server...
Shutting down VB/C# compiler server...
VB/C# compiler server shut down successfully.

> ps -Name dotnet
Get-Process: Cannot find a process with the name "dotnet". Verify the process name and call the cmdlet again.
```

**Comment by richlander** [comment]
Perhaps we should ship an apphost for this binary to make this obvious?

Ideally (I think), the SDK would have the following architecture for its unique long-lived processes:

- Apps (like this one) have their own apphost (for UX reasons like this).
- Apps are single file/composite w/rt their unique dependencies.
- All shared dependencies in the SDK are in a shared SDK location (possibly compiled composite). This requires a new runtime and/or host feature.
- The SDK contains no "framework" binaries.

**Comment by mthalman** [comment]
I can no longer repro this.
