### ISSUE TITLE
'dotnet run -- args' requires 'args' to exist

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/sdk#18437]
### Description

Repro:

* Install .NET 6 Preview 6 on a Mac.
* Install the Mac Catalyst workload: `sudo dotnet workload install microsoft-maccatalyst-sdk-full`
* Clone https://github.com/dotnet/maui-samples (hash: bb264d046139f6635ed066157c44b99010b8d1dd)
* Build & run HelloMacCatalyst:

```shell
$ cd HelloMacCatalyst
$ dotnet build
$ dotnet run --no-build -- helloworld
The file /Users/rolf/work/net6-mobile-samples/HelloMacCatalyst/helloworld does not exist.
```

Note that the error does not come from the Mac Catalyst test app, which is never executed. In fact you can delete everything, and try again without building, and you get the same error (now it'll also complain that the Mac Catalyst app doesn't exist, which makes sense):

```shell
git clean -xfd
$ dotnet run --no-build -- helloworld
The files /Users/rolf/work/net6-mobile-samples/HelloMacCatalyst/bin\Debug/net6.0-maccatalyst/maccatalyst-x64/HelloMacCatalyst.app and /Users/rolf/work/net6-mobile-samples/HelloMacCatalyst/helloworld do not exist.
```

**Comment by KathleenDollard** [comment]
What is the name of the application that is built? 
If you just type `dotnet run` or `dotnet run -- helloworld` does it work? 
Is `helloworld` an argument to the application you're trying to run?

**Comment by rolfbjarne** [comment]
> What is the name of the application that is built?

HelloMacCatalyst

This is the source code: https://github.com/dotnet/maui-samples/tree/main/HelloMacCatalyst

> If you just type `dotnet run` or `dotnet run -- helloworld` does it work?

`dotnet run` works

`dotnet run -- helloworld`  does not (same error)

> Is `helloworld` an argument to the application you're trying to run?

Yes.

Note that we set `RunCommand` and `RunArguments`: https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets#L5-L8

although I don't see how that would make the actual user arguments verified as valid paths (which they obviously don't have to be)

**Comment by sfoslund** [comment]
I'm looking into this issue. So far, I've confirmed that this does not repro with a simple console app so this appears to be something specific to the maui sample app

> dotnet run --no-build -- helloworld
Hello World! helloworld

Source:
>using System;
namespace tmp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World! " + args[0]);
        }
    }
}

**Comment by sfoslund** [comment]
@rolfbjarne I've reproed and investigated more and I believe that this is a result of setting the RunCommand and RunArguments in the file you linked. I've experimented with the simple console app I used above by adding:
`<PropertyGroup> <RunArguments>$(OutputPath)/$(AssemblyName).app</RunArguments> </PropertyGroup>`
to the project file and it ends up mangling the arguments in a similar way:

> dotnet run --no-build hello
Hello World! /tmp.app

I'm not sure exactly how the RunCommand and RunArguments properties are supposed to interact with command line arguments to the run command, but maybe @rainersigwald can comment.

**Comment by rainersigwald** [comment]
`RunCommand` and `RunArguments` are SDK/CLI concepts, not part of core MSBuild. It looks like they're here, which appends more or less as I expected:

https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L238-L250

**Comment by rainersigwald** [comment]
I'm pretty sure the error is coming from macOS's `open`:

```sh-session
❯ open a b c
The files /Users/raines/temp/a, /Users/raines/temp/b, and /Users/raines/temp/c do not exist.
```

**Comment by rolfbjarne** [comment]
🤦 

Sorry I didn't figure this out myself.
