### ISSUE TITLE
Workload install copying across mounts error

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#18450]
The files on disk workload install needs to copy files into both the user's home (advertising manifests) and the dotnet directory (packs, installed manifests). This can cause problems with those are under different mounts, for example, the default user home on linux is `/home/...` and you could potentially install dotnet to `/mnt/...`. This is problematic because install uses one temp directory and has to be able to copy from that temp directory into both the home and dotnet directories. When the mounts for these locations conflict we run into a `Invalid cross-device link.` error (https://github.com/dotnet/runtime/issues/31149). 

Repro: Workload install using WSL

Error output:
> /mnt/c/code/tmp2$ ./dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Failed to update the advertising manifest microsoft.net.sdk.maui: microsoft.net.sdk.maui.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.5.28.
Workload installation failed, rolling back installed packs...
Installing workload manifest microsoft.net.sdk.android version 11.0.200-ci.main.256.
Installation roll back failed: Failed to install manifest microsoft.net.sdk.android version 11.0.200-ci.main.256: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 30.0.100-preview.5.28: Invalid cross-device link.

**Comment by sfoslund** [comment]
@wli3 @joeloff are you aware of any alternatives to Directory.Move that don't have problems copying between mounts? If not, I think we'll need to implement logic to use temp directories located on the mount we plan on copying to, which might be complicated.

**Comment by radical** [comment]
I ran into this too on https://github.com/dotnet/runtime/pull/54451 . And switched to using copying individual files with `FileInfo.CopyTo`, and worked fine.

**Comment by lewing** [comment]
Workloads on linux appear to be very broken due to this with a very recent SDK I get

```
dotnet workload install microsoft-net-sdk-blazorwebassembly-aot

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.macos: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.maui: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.ios: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.android: Invalid cross-device link.
Failed to update the advertising manifest microsoft.net.sdk.tvos: Invalid cross-device link.
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.7.21321.15...
Workload installation failed, rolling back installed packs...
Rolling back pack Microsoft.NET.Runtime.WebAssembly.Sdk installation...
Workload installation failed: Invalid cross-device link
install
  Install a workload.

Usage:
  dotnet [options] workload install [<WORKLOAD_ID>...]

Arguments:
  <WORKLOAD_ID>  The NuGet Package Id of the workload to install.

Options:
  --sdk-version <VERSION>                                                  The version of the SDK.
  --configfile <FILE>                                                      The NuGet configuration file to use.
  --add-source <SOURCE>                                                    Add an additional NuGet package source to use during installation.
  --skip-manifest-update                                                   Skip updating the workload manifests.
  --from-cache <from-cache>                                                Complete the operation from cache (offline).
  --download-to-cache <download-to-cache>                                  Download packages needed to install a workload to a folder which can be used for offline installation.
  --include-previews                                                       Allow prerelease workload manifests.
  --temp-dir <temp-dir>                                                    Configure the temporary directory used for this command (must be secure).
  --disable-parallel                                                       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources                                                  Treat package source failures as warnings.
  --no-cache                                                               Do not cache packages and http requests.
  --interactive                                                            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -v, --verbosity <d|detailed|diag|diagnostic|m|minimal|n|normal|q|quiet>  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  -?, -h, --help                                                           Show help and usage information
```

**Comment by sfoslund** [comment]
Yes, I think this was all a result of https://github.com/dotnet/sdk/pull/17860/files, where we changed to using the machine's default temp location, which on linux is often on a different mount from the dotnet install location. I'll get a PR out to fix this today but in the meantime it can be worked around by using the `--temp-dir` option and specifying a temp location within the same mount as the dotnet installation.

**Comment by jonathanpeppers** [comment]
Saw this on Windows, might be related: https://github.com/dotnet/sdk/issues/18516
