### ISSUE TITLE
dotnet restore: Slow restore performance

### ISSUE THREAD

**Issue by stefan-hartmann-lgs** [dotnet/sdk#18467]
With `nuget.exe` it was possible to set `NUGET_CERT_REVOCATION_MODE` to `offline`

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode-481

This environment variable seems to not have an effect on `dotnet restore`.

Is there any possibility to turn off those revocation checks for `dotnet restore`.

As our CI is running in network with very limited network access, restoring NuGet dependencies is dramatically slowed down by this missing configuration possibility.

**Comment by marcpopMSFT** [comment]
@JonDouglas

**Comment by erdembayar** [comment]
@stefan-hartmann-lgs 
Could you be able to provide `dotnet --info` details? 

@dtivel @heng-liu 
I believe currently cert verification can't be disabled on Win OS, right?

**Comment by stefan-hartmann-lgs** [comment]
@erdembayar sure! It is simply the version provideddotnet SDK docker image:

```
sudo docker run -it mcr.microsoft.com/dotnet/sdk:3.1
root@f74d6b449026:/# dotnet --version
3.1.412
root@f74d6b449026:/# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.412
 Commit:    751fd182ef

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.412/

Host (useful for support):
  Version: 3.1.18
  Commit:  5d3919d34e

.NET Core SDKs installed:
  3.1.412 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by dtivel** [comment]
Signed package verification was not enabled on Linux until .NET SDK 5., so revocation checks related to NuGet signed package verification cannot be the reason for slow performance under .NET Core SDK 3.1.  `NUGET_CERT_REVOCATION_MODE` won't have any effect under .NET Core SDK 3.1.

As a side note, NuGet signed package verification was temporarily disabled by default on Linux with [.NET SDK 5.0.202](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.5/5.0.5.md).

If this is indeed a problem experienced with .NET Core SDK 3.1, then retitle/reword this issue as slow restore performance; signed package verification and revocation checks are unrelated.

**Comment by stefan-hartmann-lgs** [comment]
After another round of verification I can say that my originally reported problem is really not the problem.

The root cause of the problem was the NuGet default source "nuget.org" and is only specific to our environment.

Sorry for inconvenience - closed!

**Comment by stefan-hartmann-lgs** [comment]
> Signed package verification was not enabled on Linux until .NET SDK 5., so revocation checks related to NuGet signed package verification cannot be the reason for slow performance under .NET Core SDK 3.1. `NUGET_CERT_REVOCATION_MODE` won't have any effect under .NET Core SDK 3.1.
> 
> As a side note, NuGet signed package verification was temporarily disabled by default on Linux with [.NET SDK 5.0.202](https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.5/5.0.5.md).
> 
> If this is indeed a problem experienced with .NET Core SDK 3.1, then retitle/reword this issue as slow restore performance; signed package verification and revocation checks are unrelated.

Hi everyone,

Unfortunately I need to re-open this issue. Since you stated that revocation checks have been disabled by default on Linux, I think this behaviour has changed now and they are enabled with the latest version right?

(I could not find anything in the release notes)

`dotnet info` output:

`.NET SDK (reflecting any global.json):
    Version:   6.0.400
    Commit:    7771abd614
   
Runtime Environment:
    OS Name:     debian
    OS Version:  11
    OS Platform: Linux
    RID:         debian.11-x64
    Base Path:   /usr/share/dotnet/sdk/6.0.400/
   
global.json file:
     Not found
   
Host:
    Version:      6.0.8
    Architecture: x64
    Commit:       55fb7ef977
   
.NET SDKs installed:
    6.0.400 [/usr/share/dotnet/sdk]
 
.NET runtimes installed:
     Microsoft.AspNetCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
     Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]`

**Comment by stefan-hartmann-lgs** [comment]
I think closing this issue was an error, as I was able to a reply here in the past and it really does affect the `dotnet` cmd and not the `nuget` cmd.

**Comment by stefan-hartmann-lgs** [comment]
cheers => https://github.com/NuGet/Home/discussions/12028
