### ISSUE TITLE
PublishTrimmed for WinForms must warn during build

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#18474]
Currently the SDK will issue a warning when publishing an app which has `PublishTrimmed=true` and is a WinForms app.
But setting `PublishTrimmed=true` in the project file applies feature switch changes to the app even when building with `dotnet build` and some of the feature switches will cause the app to break.

Repro:
* `dotnet new console`
* Add `PublishTrimmed=true` to the `.csproj`
* Add a text box, this can be done by changing the `Form1.Designer.cs` to look like this:
```C#
        private void InitializeComponent()
        {
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(223, 105);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(100, 23);
            this.textBox1.TabIndex = 0;

            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.textBox1);
            this.Text = "Form1";
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TextBox textBox1;
```
* `dotnet run`

Observe that there are no warnings reported.
The app starts but immediately fails with exception that Built-in COM support is disabled.

**Comment by vitek-karas** [comment]
Same thing happens for WPF. Create a new WPF app, add a TextBox and try to build/run with PublishTrimmed=true. In this case the app doesn't even start (no window is shown), immediately fails due to disabled COM.

**Comment by agocke** [comment]
I think we can move that code to src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.props and that should do it. We'll also need tests

**Comment by vitek-karas** [comment]
If we keep `PublishTrimmed=true` as the only trigger then I agree.
I think it might be good to also react to Built-in COM support disabled directly - since we know it breaks both WinForms and WPF - regardless of trimming. In which case we should somehow coordinate the messages (since trimming will likely be the most common case to get there).
