### ISSUE TITLE
dotnet publish hangs on Linux build

### ISSUE THREAD

**Issue by narasamdya** [dotnet/sdk#18484]
**Command**: `dotnet msbuild -p:Configuration=Release`

I saw a bunch of  hanging `dotnet publish`: `ps -ef | grap dotnet`
```
imnarasa 15139 15135  0 12:34 pts/2    00:00:02 dotnet publish --no-build --configuration Release --self-contained --output /home/imnarasa/Work/AnyBuild/distrib/Release/BazelAnyBuildAdapter/
imnarasa 15185 15139  0 12:34 pts/2    00:00:02 dotnet exec /usr/share/dotnet/sdk/5.0.301/MSBuild.dll -maxcpucount -verbosity:m -target:Publish -property:NoBuild=true -property:Configuration=Release -property:SelfContained=true -property:PublishDir=/home/imnarasa/Work/AnyBuild/distrib/Release/BazelAnyBuildAdapter/ -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll
imnarasa 15207 15206  0 12:34 pts/2    00:00:02 dotnet publish --no-build --configuration Release --self-contained --output /home/imnarasa/Work/AnyBuild/distrib/Release/Deployer/
imnarasa 15250 15207  0 12:34 pts/2    00:00:02 dotnet exec /usr/share/dotnet/sdk/5.0.301/MSBuild.dll -maxcpucount -verbosity:m -target:Publish -property:NoBuild=true -property:Configuration=Release -property:SelfContained=true -property:PublishDir=/home/imnarasa/Work/AnyBuild/distrib/Release/Deployer/ -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll
imnarasa 15371 15370  0 12:34 pts/2    00:00:01 dotnet publish --nologo --no-build --configuration Release --self-contained --output /home/imnarasa/Work/AnyBuild/distrib/Release/PerfTestTool/
imnarasa 15394 15371  0 12:34 pts/2    00:00:02 dotnet exec /usr/share/dotnet/sdk/5.0.301/MSBuild.dll -maxcpucount -verbosity:m -target:Publish -nologo -property:NoBuild=true -property:Configuration=Release -property:SelfContained=true -property:PublishDir=/home/imnarasa/Work/AnyBuild/distrib/Release/PerfTestTool/ -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/5.0.301/dotnet.dll
```

**Remedies**
The remedies that work so far are

`dotnet msbuild -p:Configuration=Release -m:1` <-- slows down builds a lot
or
`MSBUILDDISABLENODEREUSE=1 dotnet msbuild -p:Configuration=Release`

**MSBuild spec**
An example of how `dotnet publish` is invoked in the .csproj is as follows:
```xml
<Target Name="PostBuildPublish" AfterTargets="PostBuildEvent" Inputs="$(OutputPath)TestBuildTool.exe" Outputs="$(DistribDir)TestBuildTool.exe">
    <Exec Command="dotnet publish --no-build --configuration $(Configuration) --self-contained --output $(DistribDir)" />
 </Target>
```

**OS**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**DotNet**
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    cc8c0abb32

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.410 [/usr/share/dotnet/sdk]
  5.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by rainersigwald** [comment]
This hang is likely the same one as dotnet/installer#10804 and should be resolved in .NET SDK 5.0.400 and .NET SDK 6.0.100 (previews).
