### ISSUE TITLE
 Workload not found

### ISSUE THREAD

**Issue by Vision-Zhang** [dotnet/sdk#18534]
* When I excuted dotnet workload install microsoft-net-sdk-blazorwebassembly-aot, It shows the following：  
  >  Updated advertising manifest microsoft.net.sdk.android.
    Updated advertising manifest microsoft.net.sdk.ios.
    Updated advertising manifest microsoft.net.sdk.maccatalyst.
    Updated advertising manifest microsoft.net.sdk.macos.
    Updated advertising manifest microsoft.net.sdk.tvos.
    Workload installation failed, rolling back installed packs...
   Installation roll back failed: Workload not found
   Workload installation failed: Workload not found
* My Sdk info is:
> .NET SDK (反映任何 global.json):
   Version:   6.0.100-preview.5.21302.13
  Commit:    d6380bcae7

>  运行时环境:
  OS Name:     Windows
  OS Version:  10.0.19043
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

> Host (useful for support):
    Version: 6.0.0-preview.5.21301.5
    Commit:  ec3e0b276b

> .NET SDKs installed:
    2.1.524 [C:\Program Files\dotnet\sdk]
   5.0.301 [C:\Program Files\dotnet\sdk]
   6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
   6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> To install additional .NET runtimes or SDKs:
    https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
Hi @Vision-Zhang, it looks like you have both the preview 4 and preview 5 SDKs installed. There are some known compatibility issues between these versions, can you try uninstalling the preview 4 SDK and trying again? If you installed the preview 5 SDK via Visual Studio 17 preview 1, you will also have you install a standalone copy of the preview 5 SDK.

**Comment by marcpopMSFT** [comment]
Please try this again with the latest preview after uninstalling per Sarah's comment.
