### ISSUE TITLE
Option for dotnet cli run command to run project executable in the project's output folder

### ISSUE THREAD

**Issue by bradykelly** [dotnet/sdk#18563]
Currently the command `dotnet run` runs a project with the main project directory as the active directory, not the output folder of the project.

Applications often depend on source files being copied to the output directory, and when the project is run with the don't CLI, this causes an error because file(s) cannot be found.

I suggest adding an option to the run command to make the CLI run the project from its output directory.

**Comment by danger7373** [comment]
```

```

**Comment by sfoslund** [comment]
Please check out the docs for the run command, specifically the second half of the description: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run#description.  If you want to execute the content of the output folder (ie the resulting .dll file) you can do so with `dotnet foo.dll`.
