### ISSUE TITLE
[Package-Validation] Work required for the package validation to be on by default in sdk

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#18582]
List of features that needs to done for the sdk to be part of sdk
- [x] dependency analysis (not adding extra dependencies, using sdk dependencies version)
- [ ] Performance analysis (None of the common pathways are effected, numbers on the pack task)

Related issue https://github.com/dotnet/sdk/issues/18203

cc @ericstj @ViktorHofer @safern

**Comment by safern** [comment]
Super seeded by: https://github.com/dotnet/sdk/issues/23910
