### ISSUE TITLE
[Package-Validation] Add support for not reporting errors for tfms which are out of support.

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#18583]
With out new policies, we will drop the tfms which are out of support from the packages. We dont want package validation to report these errors while running the validation against the previous version of the package.
There will be opt-in flag available to still validate out of support tfms because not all packages will follow the dotnet policies.

cc @safern @ViktorHofer @ericstj

**Comment by safern** [comment]
Super seeded by: https://github.com/dotnet/sdk/issues/22901
