### ISSUE TITLE
High Precision Timer

### ISSUE THREAD

**Issue by aehomay** [dotnet/sdk#18602]
To my best knowledge, we don`t have a high precision timer (in micro/nano-second) in .NET, and was wondering if this is still the same with .NET 5.0 and Core?

**Comment by sfoslund** [comment]
@brianrob can you comment here? I'm not aware of any.

**Comment by brianrob** [comment]
`System.Diagnostics.Stopwatch` is probably the highest precision timer in the framework.  On Windows, it is based on `QueryPerformanceCounter`, which can certainly provide microsecond granularity.  See https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps#low-level-hardware-clock-characteristics for more details.

**Comment by deeprobin** [comment]
You could build a high precision timer on x86 with `rdtsc` instructions.

But I have read that especially on newer hardware this instruction is not always accurate either.
For this feature, however, the `dotnet/runtime` repository would probably be more suitable. 

@tarekgh I think you are the best person to talk to about time. Can you say something about it?

**Comment by tarekgh** [comment]
@brianrob is correct here. You may review [Acquiring high-resolution time stamps](https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps) which still a correct information.
