### ISSUE TITLE
`dotnet <cmd>` without argument doesn't display help text

### ISSUE THREAD

**Issue by ZeroErrors** [dotnet/sdk#18603]
Executing commands such as any of
- `dotnet sln`
- `dotnet add`
- `dotnet remove`
- `dotnet list`
- `dotnet sdk`
- `dotnet workload`

Will simply print the following message without displaying the help text.
```
Required command was not provided.

```

I tested this on both `main` (https://github.com/dotnet/sdk/commit/2c011f2aa7a91a386430233d5797452ca0821ed3) and the latest preview release `6.0.100-preview.5.21302.13` and both have this same problem.
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7
```

This bug is a regression of:
- `dotnet <cmd>` https://github.com/dotnet/cli/pull/6506
- `dotnet add` https://github.com/dotnet/sdk/issues/7558
- `dotnet sln` https://github.com/dotnet/sdk/issues/7559
- `dotnet sln` https://github.com/dotnet/sdk/issues/7775

**Comment by marcpopMSFT** [comment]
@sfoslund , this is a change of behavior from 5.0 SDKs and appears to be related to the the system commandline adoption
