### ISSUE TITLE
Unable to create android class library in .net 6

### ISSUE THREAD

**Issue by musictopia2** [dotnet/sdk#18600]
![problem3](https://user-images.githubusercontent.com/39104606/123736124-6b5cdd80-d855-11eb-9912-995e5b259da1.png)

Whenever I try to create an android class library in .net 6, what you see in the screenshot is what happens.   Happens even if I have no code.  I would suggest that if it becomes impossible to create class libraries in android in .net 6, to remove.  Otherwise, there would be lots of disappointed people if the templates appear but never works.

**Comment by sfoslund** [comment]
@musictopia2, based on the screenshot it appears you're editing a simple library by changing the TFM to net6.0-android, is that correct? Android tooling is part of an optional workload with .NET 6, so there are a few extra steps to get started. First you have to install with android workload with the command `dotnet workload install microsoft-android-sdk-full` in an elevated command prompt. This will get all the necessary tools installed to your machine, and from there I would reccomend using `dotnet new android` to create a project, as the templates will have all the basics laid out for you whereas if you edit an existing class library you'll potentially have more steps to configure it for android.
