### ISSUE TITLE
.NET daily fails to install MAUI workload

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/sdk#18628]
1. Install https://aka.ms/dotnet/6.0/daily/dotnet-sdk-osx-x64.pkg
2. `sudo dotnet workload install maui`

```bash
~: sudo dotnet workload install maui
Password:

Failed to update the advertising manifest microsoft.net.sdk.maui: microsoft.net.sdk.maui.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Installing workload manifest microsoft.net.sdk.tvos version 14.5.100-preview.5.894.
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.5.28.
Installing workload manifest microsoft.net.sdk.maui version 6.0.100-preview.6.919+sha.109ce5194-azdo.4926252.
Workload installation failed, rolling back installed packs...
Installing workload manifest microsoft.net.sdk.tvos version 14.5.100-ci.main.723.
Installation roll back failed: Failed to install manifest microsoft.net.sdk.tvos version 14.5.100-ci.main.723: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.maui version 6.0.100-preview.6.919+sha.109ce5194-azdo.4926252: microsoft.net.sdk.maui.manifest-6.0.100::6.0.100-preview.6.919 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..
```

The underlying issue seems to be that the daily workloads are not published to nuget.org. Is there a mechanism missing to bring this information along for daily builds of .NET SDK?

@mhutch @jonathanpeppers

**Comment by marcpopMSFT** [comment]
@lutzroeder Daily workloads are published to ADO. Add the following to your nuget.config file:
<add key="maui" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />

I don't think we have plans for any better support for daily builds at the time though we should document that somewhere.

**Comment by marcpopMSFT** [comment]
Added those details to the installer readme: https://github.com/dotnet/installer#installers-and-binaries

**Comment by DamienDoumer** [comment]
I came across this error, and when I tried re-running "dotnet workload install maui" I got this error.
Please which nuget.config should be updated ? 

System.Exception: Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.RefreshWorkloadManifests() in Microsoft.DotNet.TemplateLocator.dll:token 0x600006f+0x17c
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver..ctor(IWorkloadManifestProvider manifestProvider, String[] dotnetRootPaths, String[] currentRuntimeIdentifiers) in Microsoft.DotNet.TemplateLocator.dll:token 0x600006e+0x31
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion) in Microsoft.DotNet.TemplateLocator.dll:token 0x600006b+0x8a
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userHome, String tempDirPath, String version) in dotnet.dll:token 0x6000200+0x17f
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_0(ParseResult appliedOption) in dotnet.dll:token 0x6000152+0x0
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x6000926+0x44
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args) in dotnet.dll:token 0x6000150+0x6
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x600098f+0x2e8
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x600098d+0x6f

**Comment by prapsan** [comment]
@DamienDoumer I've fixed the error by deleting 

`  "depends-on": {
    "Microsoft.NET.Workload.Emscripten": "6.x.x"
  },`


from C:\Program Files\dotnet\sdk-manifests\6.x.x\microsoft.net.workload.mono.toolchain\WorkloadManifest.json

**Comment by marcpopMSFT** [comment]
@lewing Did you previously install a workload with an earlier preview?  There was a lot of churn in the workloads since preview 4 and we're seeing some compat issues.

**Comment by DamienDoumer** [comment]
@prapsan  please any info where to find this json manifest file ?
@marcpopMSFT  I installed the latest workloads earlier, and the installation hanged with the error described by the author of this issue. Then when I retried, I had the error I described above

**Comment by prapsan** [comment]
@DamienDoumer It's here (on Windows) -> C:\Program Files\dotnet\sdk-manifests\6.x.x\microsoft.net.workload.mono.toolchain\WorkloadManifest.json

**Comment by DamienDoumer** [comment]
@prapsan thanks

**Comment by marcpopMSFT** [comment]
@lewing for visibility as you shouldn't require hand modifying workload manifests unless you've ended up in some weird state with an out of sync set of workloads (which can happen if you install .net 6 preview 7 and then VS 2022 preview 2 for example).

**Comment by lewing** [comment]
cc @dsplaisted

**Comment by tvkit** [comment]
> WorkloadManifest.json

 Also removed the _wasm-tools_ workload since it referenced _emscripten_.

@prapsan Good find and thanks for sharing.

**Comment by lewing** [comment]
cc @steveisok
