### ISSUE TITLE
F# default project template

### ISSUE THREAD

**Issue by thomasd3** [dotnet/sdk#18647]
Right now, when starting a blank F# project, we get this:

```
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System

// Define a function to construct a message to print
let from whom =
    sprintf "from %s" whom

[<EntryPoint>]
let main argv =
    let message = from "F#" // Call the function
    printfn "Hello world %s" message
    0 // return an integer exit code
```

Which is not useful, but also get annoying the 50th time you see it. Would it be possible to have a more succinct template, something like this:

```
[<EntryPoint>]
let main argv =
    0
```

and that's it?

**Comment by kasperk81** [comment]
https://github.com/dotnet/templating/pull/1880#issuecomment-489071813 (suggestion was ignored previously)

**Comment by marcpopMSFT** [comment]
Old issue triage: Per linked templating issue, this is likely fixed now.
