### ISSUE TITLE
Stop putting unnecessary support package binaries in extensions nupkg

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#1865]
See https://github.com/dotnet/sdk/pull/1860#discussion_r162458901

The CLI doesn't use these assemblies (it picks up the support package directlty) and we're wasting space and time putting them in the .nupkg. Also, with nupkg signing, we have to keep exclusions up-to-date based on the contents of the support package that are out of our control.

**Comment by livarcocc** [comment]
@nguerrera I thought you were making a PR already.

**Comment by livarcocc** [comment]
This seems like a dup of https://github.com/dotnet/sdk/issues/1324.

**Comment by nguerrera** [comment]
Duplicate of #1324
