### ISSUE TITLE
PackageValidation task cannot find nuget package due to version normalization

### ISSUE THREAD

**Issue by smkanadl** [dotnet/sdk#18660]
I tried the new SDK feature following the example at https://devblogs.microsoft.com/dotnet/package-validation/#validation-against-baseline-package-version.

I am getting an error from the task complaining the nuget package has not been found:
`Error MSB4018 The "Microsoft.DotNet.PackageValidation.ValidatePackage" task failed unexpectedly.
System.IO.InvalidDataException: The file is not a valid nupkg. File path: bin\Debug\*******.2.0.0.0.nupkg ---> System.IO.FileNotFoundException: Could not find file 'bin\Debug\********.2.0.0.0.nupkg'.`

If I look into the `bin\Debug` folder I see the nuget package file, but it has a normalized version of `2.0.0` although I explicitly set `<PackageVersion>2.0.0.0</PackageVersion>`.

If change the PackageVersion to either `2.0.0` or `2.0.0.1` it works as expected.

**Comment by Anipik** [comment]
@smkanadl can you provide a repro or a binlog ?

**Comment by smkanadl** [comment]
@Anipik sure: https://github.com/smkanadl/PackageValidation

In the `csproj` you can switch between `<PackageVersion>14.0.0.0</PackageVersion>`and `<PackageVersion>14.0.0</PackageVersion>`.

The first one will not work whereas the latter one will (correctly) fail with some validation warnings.

**Comment by cdonnellytx** [comment]
A similar discrepancy in NuGet package filename also occurs if you are using "full" semantic versioning  (e.g. `PackageVersion=1.2.3-alpha.1+2`).  The package file generated (at least in Windows, by MSBuild) appears to be `bin\Debug\1.2.3-alpha.1.nupkg`, not including the `+`.

I dug into the SDK targets for dotnet (5.0.301, win-x64) and it looks like the first entry in `@(NuGetPackOutput)` is what is desired, with target `_GetOutputItemsFromPack` being responsible for what is altering the expected filename.

(I discovered this by using the [GitVersion.MsBuild](https://www.nuget.org/packages/GitVersion.MsBuild/) task; the trick is to have unstaged changes out where the currently committed HEAD is not on a tag.)

**Comment by ViktorHofer** [comment]
Thanks for reporting @smkanadl. I just submitted [a PR](https://github.com/dotnet/sdk/pull/27181) that will fix this by using a similar approach as what @cdonnellytx shared.
