### ISSUE TITLE
Fail to install workload "microsoft-net-sdk-blazorwebassembly-aot" 

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/sdk#18661]
**Steps**:
1. Install latest Dev17.0 Preview2 from main branch.
2. Install .NET SDK 6.0 Preview 6 : build 6.0.100-preview.6.21328.10 from [Pipelines - Run 20210628.3-6.0.100-preview.6.21328.10-95778 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1210635&view=artifacts&type=publishedArtifacts).
3. Add feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.6.21328.10-shipping/nuget/v3/index.json.
4. Run "dotnet workload install microsoft-net-sdk-blazorwebassembly-aot" as administrator.

**ACTUAL**
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: The file is not a valid nupkg. File path: C:\Users\v-wajian\AppData\Local\Temp\dotnet-sdk-advertising-temp\microsoft.net.workload.mono.toolchain.manifest-6.0.100\6.0.0-preview.6.21325.12\microsoft.net.workload.mono.toolchain.manifest-6.0.100.6.0.0-preview.6.21325.12.nupkg.
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.6.21325.12...
Workload installation failed, rolling back installed packs...
Rolling back pack Microsoft.NET.Runtime.WebAssembly.Sdk installation...
Workload installation failed: The file is not a valid nupkg. File path: C:\Users\v-wajian\AppData\Local\Temp\dotnet-sdk-advertising-temp\microsoft.net.runtime.webassembly.sdk\6.0.0-preview.6.21325.12\microsoft.net.runtime.webassembly.sdk.6.0.0-preview.6.21325.12.nupkg
![image](https://user-images.githubusercontent.com/35762055/124095612-6b92ee00-da8c-11eb-9aa8-799e8300e1a5.png)

**Full Error Text**
![image](https://user-images.githubusercontent.com/8246794/124131315-4c508c80-da9d-11eb-9cc0-9d1892f6a332.png)

**Comment by steveisok** [comment]
"The file is not a valid nupkg" appears for every single manifest the sdk tries to update.  Pure speculation, but did something go wrong with the signing?

**Comment by Andy-Win** [comment]
Using the latest .NET 6.0 SDK(6.0.100-preview.6.21355.2) and new feed-https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.6.21355.2-shipping-1/nuget/v3/index.json. I can't repro this issue any more.

**Comment by marcpopMSFT** [comment]
Fixed with https://github.com/dotnet/sdk/pull/18701 and has been ported to main.
