### ISSUE TITLE
ApplicationPartAttribute not generated for WinExe project

### ISSUE THREAD

**Issue by hillin** [dotnet/sdk#18662]
If the `OutputType` of an mvc project is set to `WinExe` (rather than `Exe`), `ApplicationPartAttribute` won't be generated for this assembly (in the `obj\<configuration>\<tfm>\<project-name>.MvcApplicationPartsAssemblyInfo.cs` file). As a result, application parts won't work properly.

This behavior is hard coded in the [Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets](https://github.com/dotnet/sdk/blob/38f45aa11a55259b7f3ad4f2934be65c20eaf44e/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets#L20) file. Is there any reason to restrict an mvc app only to be hosted in an Exe assembly? For some reason we really want to host it in a WinExe.

As a workaround we can force `GenerateMvcApplicationPartsAssemblyAttributes` in the .csproj file:

```xml
<GenerateMvcApplicationPartsAssemblyAttributes>True</GenerateMvcApplicationPartsAssemblyAttributes>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This feature is specific to MVC and we don't plan to expand its scope to other areas.
