### ISSUE TITLE
[API Compat] Add MSBuild task to run API Compat standalone

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#18677]
We should add the MSBuild Task to the `Microsoft.DotNet.Compatibility` package.

I have a prototype here which includes targets and props, it also accepts c# source as an input for the left hand side of the comparison: https://github.com/safern/apicompat/tree/main/src/Microsoft.DotNet.ApiCompatibility.Tasks

cc: @ericst @terrajobst @Anipik

**Comment by ViktorHofer** [comment]
As mentioned in https://github.com/dotnet/sdk/issues/23631, it would be great if the new ApiCompat task would support passing in implementation assemblies instead or in addition to implementation directories. The legacy ApiCompat tooling doesn't support that.

**Comment by safern** [comment]
We should prioritize this for .NET 7 so that dotnet/runtime can start its migration to the new API Compat once the rules gap vs the old tooling is filled.
