### ISSUE TITLE
[Package Validation] Baseline package validation should run with references

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#18676]
Currently we are running API Compat without references, causing typeforwards to not be resolved or some other rules might be limited by this.

cc: @ericstj @Anipik

**Comment by Anipik** [comment]
@safern do we have that support available in api compat ?

**Comment by safern** [comment]
> @safern do we have that support available in api compat ?

Yes we do. You just specify, `resolveAssemblyReferences` to true when creating the `AssemblySymbolLoader`: https://github.com/dotnet/sdk/blob/faf81a525654c706d1fdcc36fce228f24df959ab/src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs#L30

And then you can specify search directories for the loader to find references on:
https://github.com/dotnet/sdk/blob/faf81a525654c706d1fdcc36fce228f24df959ab/src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs#L43

https://github.com/dotnet/sdk/blob/faf81a525654c706d1fdcc36fce228f24df959ab/src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs#L50

**Comment by ericstj** [comment]
My suggestion in the past was just to use the current set of references as an approximation.  It's not perfect and it can miss breaking changes in the references, but those are not really the things under test.

Fetching the real references for a past packages *correctly* would require a whole separate restore + resolve references as an isolated project.  I don't see this as a practical tradeoff we'd make for the common case.  I think we should permit it at the task level if someone wanted to do this themselves (for instance by having a separate project and writing some targets) but in the default case I think we can just get by using existing references as an approximation.
