### ISSUE TITLE
[API Compat] Add rule to make sure virtual modifier is not removed

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#18682]
This rule checks that a member should be virtual on both the implementation and in the contract when the member is overridable:

1. Is virtual.
2. Is not sealed.
3. Type is not sealed.

This rule should support StrictMode and make sure both sides are virtual when in strict mode.

cc: @ericstj @Anipik

**Comment by smasher164** [comment]
Make sure to update docs repo after #25734 goes in.
