### ISSUE TITLE
Should the SDK include Microsoft.Build.Utilities.v4.0?

### ISSUE THREAD

**Issue by bencyoung** [dotnet/sdk#1870]
I'm trying to use Fody.Costura in my project but it's failing with: 

```
C:\Users\Ben.Young\.nuget\packages\costura.fody\1.6.2\build\dotnet\Costura.Fody.targets(14,5): error MSB4062: The "Costura.Tasks.FilterReferenceCopyLocalPaths" task could not be loaded from the assembly C:\Users\Ben.Young\.nuget\packages\costura.fody\1.6.2\build\dotnet\..\..\\Costura.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0
```

The dll is in my framework folder but dotnet doesn't seem to find it. Using MSBuild or VS to build the solution works. 

Is it expected that using dotnet from the command line should work with targets that use these utilities?

**Comment by livarcocc** [comment]
@rainersigwald can you comment?

**Comment by rainersigwald** [comment]
MSBuild on .NET Core does not support tasks built against MSBuild 4.0.  https://github.com/Microsoft/msbuild/issues/2111 has some hints for build task authors who wish to produce a task compatible with MSBuild 4.0 on full .NET Framework, MSBuild 15 on full .NET Framework, and MSBuild on .NET Core.
