### ISSUE TITLE
`dotnet publish` does not copy some dependencies

### ISSUE THREAD

**Issue by CCRcmcpe** [dotnet/sdk#18735]
`dotnet --version`: 5.0.301
1. My solution contains a console project (C) and a library project (L).
2. C references L.
3. The nuget references of C intersects with the nuget references of L.

I made several attempts:

1. Run `dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true` on C, the single exe raised System.IO.FileNotFoundException: Could not load file or assembly "Serilog.Sinks.File", which Serilog.Sinks.File is L's reference.

2. Removed `-p:PublishSingleFile=true` parameter, the output program raised the same exception, and Serilog.Sinks.File.dll is missing in the output folder.

3. Removed `-r win-x64 --self-contained false`, just leaving the `-c Release` parameter. Strangely enough, the result is still the same as above!

4. Use `build` instead, run `dotnet build -c Release -r win-x64`. The output has a lot of files, strangely, coreclr.dll can be seen. Is this intended? Isn't this the result that should only appear when `dotnet publish -c Release -r win-x64 --self-contained true`? Maybe I could open another issue.

5. Run `dotnet build -c Release`. The output works as intended, but what I want is `publish`.

After all, the `publish` command cannot work anyhow at all.

May related to:
https://github.com/dotnet/sdk/issues/11489,
https://github.com/dotnet/sdk/issues/16487 as in 4.

**Comment by CCRcmcpe** [comment]
I removed
```xml
<PackageReference Include="GitInfo" Version="2.1.2">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
from C then `publish` works properly. Don't know why.
Considering this problem maybe caused by a third-party library, I will close this issue.

**Comment by diegosasw** [comment]
This is interesting. Could you let me know more about those assets configuration?
I am having a similar one https://github.com/dotnet/sdk/issues/21716 where the `dotnet publish` seems to publish all what I need (including a `Newtonsoft.Json.dll`) but when running the app within the publish output folder I get a file not found exception complaining about that `Newtonsoft.Json` assembly. When running the app, without publishing it, with a `dotnet run` I don't get that exception. So there's definitely something different in `dotnet publish` result which I don't yet know what.

**Comment by diegosasw** [comment]
Never mind, my problem was with a version conflict after all
