### ISSUE TITLE
`dotnet workload install  xxxx --print-download-link-only` should not require elevated permissions

### ISSUE THREAD

**Issue by nosami** [dotnet/sdk#18738]
```
➜ jasonimison@Jasons-iMac  ~/src/vsmac git:(dev/nosami/updater-dotnet-workload) dotnet --version
6.0.100-preview.7.21356.1
➜ jasonimison@Jasons-iMac  ~/src/vsmac git:(dev/nosami/updater-dotnet-workload) dotnet workload install maui-ios --print-download-link-only 
Inadequate permissions to access, please elevate to run this command.
install

```

This command doesn't actually install anything, it just prints the location of any nupkgs that are needed, so it shouldn't require elevated permissions. The command works without elevation in 6.0 preview 5

This is a problem for the VSMac updater as it downloads the packages in the background without user intervention and only the actual installation prompts for elevation. This is a blocker for VSMac integration.

**Comment by nosami** [comment]
Same applies to `dotnet workload update --print-download-link-only`

**Comment by dsplaisted** [comment]
@sfoslund @wli3

**Comment by wli3** [comment]
Might be the temp dir change. Use a non root  `--temp-dir` location might work

**Comment by sfoslund** [comment]
This error is coming earlier in the install, I added it recently, should be easy to fix: https://github.com/dotnet/sdk/pull/18078/files#diff-30590c656d6aa0fc5b561cb5ef14bd838f7ade7aa2e7c008cda0aa2cf4f79c5aR39
