### ISSUE TITLE
System.Exception : Workload not found

### ISSUE THREAD

**Issue by vinayiscool** [dotnet/sdk#18758]
![image](https://user-images.githubusercontent.com/78460365/124736892-11cf6f80-df35-11eb-850e-431286e41c9a.png)

Steps : Installed AOT with .NET 6 Preview 4 using VS2019
Now installed .NET 6 Preview 5 using VS2022 Prev1, also uninstalled .NET6 Preview 4
And as per blog https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-5/, we need to update workload.
so trying dotnet workload update command and facing above attached error.

Also tried dotnet workload install microsoft-net-sdk-blazorwebassembly-aot but it seems already installed, see below image.

![image](https://user-images.githubusercontent.com/78460365/124737595-b8b40b80-df35-11eb-9041-a3e0cc05c8a6.png)

**Comment by marcpopMSFT** [comment]
Old issue triage: there have been a lot of improvements to workloads in the past two years. Please ping if this is still a problem.
