### ISSUE TITLE
Naming of the properties that control implicit namespaces included by the SDK

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#18839]
Follow up to the conversation started in https://github.com/dotnet/sdk/pull/18459#discussion_r664925999.

We don't like the underscore in the naming of the properties that control the list of implicit imports. For example, we have the name `<DisableImplicitNamespaceImports_Web>`. However, we also need to ensure that these options are very specific and unlikely to collide with other properties. 

FYI @mhutch @DamianEdwards @davidfowl

**Comment by pranavkm** [comment]
Closing this since it's been shipped. 👋🏽 @JunTaoLuo!
