### ISSUE TITLE
Architecture and OS targeting improvements for .NET 6

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#18832]
https://github.com/dotnet/designs/blob/d248ad68b41866eba17e80225a08518b8202ddf6/accepted/2021/architecture-targeting.md#net-6

For the shorthand RID, the proposal is to go with --arch and -a and --os (no need for a short form of os). 

### .NET 6

The following changes should be included in .NET 6, motivated by the x64 emulation scenario. They are all additive and non-breaking.

- [x]  Enable shorthand RID syntax. Add to the following verbs (priority order): -- https://github.com/dotnet/sdk/pull/18889
   - `build`
   - `publish`
   - `tool install`
   - `test`
   - `run`
   - `watch run`
   - `watch test`
- [x] Enable shorthand RID syntax for `tool install` (separate PR from other verbs)-- #19370
- [x]  Do NOT enable the `-r` RID syntax on these same verbs. Doing so would cause a breaking change in .NET 7, which seems like a unforgivable mistake.-- No-op
- [x] Enable implicit RID where there is one known choice:
   - The macOS Arm64 SDK should treat pre .NET 6 versions as X64 by default.-- Fixed by https://github.com/dotnet/sdk/pull/18216
   - The Windows Arm64 SDK should treat pre .NET 5 versions as X64 by default.-- https://github.com/dotnet/sdk/pull/19052
- [x]  Parity syntax between `dotnet build` and `dotnet publish` for pivoting between self-contained and framework-dependent modalities, for example:-- https://github.com/dotnet/sdk/pull/18837
   - `dotnet build -r win-x64 --self-contained`
   - `dotnet build -r win-x64 --self-contained true`
   - `dotnet build -r win-x64 --self-contained false`
   - `dotnet build -r win-x64 --no-self-contained`
- [x]  Add warning when using `-r` without a `--self-contained` or `--no-self-contained`. The warning is for .NET 6+ apps only.-- https://github.com/dotnet/sdk/pull/18837
- [x] Add a warning when using `-r` with either `--os` or `--arch`-- https://github.com/dotnet/sdk/pull/18889

The addition of the shorthand RID syntax and the parity syntax between `build` and `publish` will provide a satisfactory set of gestures to enable migration with .NET 6 to a non-breaking syntax with respect to .NET 7. In particular, users need to migrate any uses of `-r` to always be accompanied by one of the `--self-contained` or `--no-self-contained` switches.

**Comment by sfoslund** [comment]
> Do NOT enable the -r RID syntax on these same verbs. Doing so would cause a breaking change in .NET 7, which seems like a unforgivable mistake.

@richlander can you clarify here? Most of those verbs already have the `-r rid` syntax, so you want to remove that? Or just avoid adding it to new commands?

**Comment by wli3** [comment]
Common on https://github.com/dotnet/sdk/pull/18889#issuecomment-885852732

I don't think tools work will improve the experience at all

**Comment by sfoslund** [comment]
All tasks finished and merged, closing this issue...

**Comment by richlander** [comment]
Thanks! How can I test the latest behavior? Try a nightly build?

**Comment by sfoslund** [comment]
Yup, pick up a nightly build in a few hours, once it's flowed: https://github.com/dotnet/installer#installers-and-binaries
