### ISSUE TITLE
Building is broken in 7.21360.1 and later builds.

### ISSUE THREAD

**Issue by L00pZBreak3r** [dotnet/sdk#18920]
The feature 'global using directive' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

**Comment by JunTaoLuo** [comment]
Can you share you project file? I'm curious what combination of the SDKs and TFMs is causing this. 

FYI, there are more details on how to resolve issues in https://github.com/dotnet/docs/issues/25066.

**Comment by L00pZBreak3r** [comment]
The error changed. Now it's
_Assets file '<project_path>\obj\project.assets.json' not found. Run a NuGet package restore to generate this file._

Net SDK 7.21360.1 and higher.
