### ISSUE TITLE
[Loc]the output about help description in CLI are unlocalized on locale OS. 

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#18934]
1. Install net 6 preview 7 SDK[6.0.100-preview.7.21364.30(runtime:6.0.0-preview.7.21360.10)] from https://github.com/dotnet/installer
2. Install it on locale OS(e.g DE/SC).
2.  Create empty directory
3.  Copy the following and create file called dotnet-tools.json
 
{
    "version": 1,
    "isRoot": true,
    "tools": {
        "t-rex": {
            "version": "1.0.53",
            "commands": ["t-rex"]
        },
        "dotnetsay": {
            "version": "2.1.4",
            "commands": ["dotnetsay"]
        }
    }
}
 
4. cd to the directory with manifest file
Run  dotnet tool run t-rex -- -h to check if strings are all localized.
Run dotnet build --help to check if strings are all localized.

Actual Result: Some strings are unlocalized
SC:
![image](https://user-images.githubusercontent.com/65637796/125760603-63d1614f-f6d9-4f3a-8871-4ec91da0bc02.png)
![image](https://user-images.githubusercontent.com/65637796/125760689-633b0b86-7266-4490-894b-91d21fe19ebe.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/125761853-02baa6ed-b588-4966-a765-6dfeded9023f.png)
![image](https://user-images.githubusercontent.com/65637796/125761986-93f62151-43ad-4a84-a5f8-631060659821.png)

**Comment by wli3** [comment]
The new loc pass is done

**Comment by vdanche** [comment]
Still repro on local OS on the latest RC2-6.0.100-rc.2.21478.25(runtime-6.0.0-rc.2.21474.18).
E.g JP
![image](https://user-images.githubusercontent.com/65637796/135421792-c2f49480-c955-46ac-9716-328b150503d4.png)
![image](https://user-images.githubusercontent.com/65637796/135421835-c01082cd-bfcb-49e5-9ad1-68b22cffccaf.png)
