### ISSUE TITLE
`dotnet list package --outdated` lists up to date packages on `.Net 6.0.100-preview.7.21364.30`

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/sdk#18942]
For a project that has any nuget packages installed, `dotnet list package --outdated` lists all the packages as updatable, reporting the same version as both the currently installed and the newest one. On .Net 5 packages which were on the latest version weren't listed, which I assume is the correct behaviour. For a project without any nuget packages, the output correctly says that no updates are available.

Reproduction:
```
dotnet new xunit -o Test
cd Test
dotnet restore
dotnet list package --outdated
```

Expected output:
```
> coverlet.collector             3.0.2    3.0.2        3.0.3
> Microsoft.NET.Test.Sdk         16.9.4   16.9.4       16.10.0
```

Actual output:
```
> coverlet.collector             3.0.2    3.0.2        3.0.3
> Microsoft.NET.Test.Sdk         16.9.4   16.9.4       16.10.0
> xunit                          2.4.1    2.4.1        2.4.1
> xunit.runner.visualstudio      2.4.3    2.4.3        2.4.3
```

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#11139
