### ISSUE TITLE
Modifying the project file doesn't regenerate deps file

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#1896]
Repro:
1. Create a .net core project.
2. Build and run.
3. Add a Reference item to a binary.
4. F5.

Expect:
Reference gets copied to output directory *and* appears in deps file.

Actual:
Reference gets copied to output directory but does not appear in deps file.

**Comment by livarcocc** [comment]
I know this one is older, but we will track this change through @nguerrera's issue here: https://github.com/dotnet/sdk/issues/1942.

**Comment by nguerrera** [comment]
This weakens my argument that I only found it through code inspection.
