### ISSUE TITLE
May I change the default template for console app?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/sdk#18960]
In particular,
https://github.com/dotnet/sdk/tree/main/src/Assets/TestProjects/HelloWorld
https://github.com/dotnet/sdk/tree/main/src/Assets/TestProjects/HelloWorldFS

using top-level statements. And then remove `using System;` with .NET 6 released. What do you think?

**Comment by WhiteBlackGoose** [comment]
@marcpopMSFT hey, eh, so any info on it yet? 😅

**Comment by marcpopMSFT** [comment]
I'm not sure I understand the request.  The above items you linked to are test assets.  The template for console lives here and has already been updated for top level statement and usings: https://github.com/dotnet/templating/blob/871b9c01c808915a0825226987bb40bfa2d7ed8e/template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ConsoleApplication-CSharp/Program.cs

**Comment by WhiteBlackGoose** [comment]
Oh, thanks then, I guess
