### ISSUE TITLE
Clean up `<DOTNET ROOT>/metadata/temp/` in case process crashed

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#18993]

**Comment by wli3** [comment]
Other than uninstall scenario, why we need to worry about a temp folder not being cleaned up? Will admin/VS install(where we care about clean up nicely) use <DOTNET ROOT>/metadata/temp/ at all?

**Comment by marcpopMSFT** [comment]
This should have been moved to user's temp folder which the OS should maintain.
