### ISSUE TITLE
Crossgen2 nuget package is not pulled when dotnet restore is done

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/sdk#18999]
When the csproj file has `<PublishReadyToRun Condition=" '$(Configuration)' != 'Debug' ">true</PublishReadyToRun>` and `dotnet restore -r win7-x64` is executed, the `microsoft.netcore.app.crossgen2.win-x64.nupkg` package is not pulled. It is pulled only when a `dotnet publish -r win7-x64 -c Release`  is executed. 

In our existing build logic, we do a two step build: 
1. `dotnet restore -r win7-x64`
2. `dotnet publish -r win7-x64 -c Release --no-restore`

Due to the `--no-restore` switch the crossgen2 package is not pulled and causes a build failure with a message:

```
<...>\Appdata\Local\Microsoft\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(297,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [D:\PSGit\TestApp\TestApp.csproj]
```

Expectation is that the two step build process should continue to work and `dotnet restore` should pull the crossgen2 package if PublishReady2Run is present in the csproj.

**Comment by mangod9** [comment]
Since restore doesnt support -c on the commandline using `/p:Configuration=Release` would the way to pass configuration to restore so crossgen2 package would be downloaded as `PublishReadyToRun` will evaluate to `true`

**Comment by dsplaisted** [comment]
Yes, I think you will have to specify the Release configuration for the restore operation (with `-p:Configuration=Release`) in order for this to work.

@KathleenDollard Are we or should we be planning to add a `-c|--configuration` parameter to `dotnet restore`?

@agocke @vitek-karas FYI

**Comment by tmds** [comment]
@dsplaisted these steps work with .NET 5 SDK and fail with .NET 6 SDK:
```
dotnet new console -o console
cd console
dotnet restore -r linux-x64
dotnet publish --self-contained false --no-restore -r linux-x64 /p:PublishReadyToRun=true
```
.NET 6 gives an error:
```
.../sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(293,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [/tmp/console/console.csproj]
```

Is this breaking change intentional?

How should the commands be changed so they work with the .NET 6 SDK?

**Comment by mangod9** [comment]
@tmds yeah it would required passing the R2R flag to restore as well, or force restore the cg2 package on publish. @AntonLapounov .

**Comment by tmds** [comment]
@mangod9 thanks, adding `/p:PublishReadyToRun=true` to `dotnet restore` works.
