### ISSUE TITLE
Adjust sdk with global using

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#19021]
Task name conflicts and `<LangVersion>Preview</LangVersion>` in directory.build.prop does not seem to work

![image](https://user-images.githubusercontent.com/6993335/126201188-d8ec31d7-732d-4e06-83f7-6f2a355da407.png)

**Comment by dsplaisted** [comment]
Does it build from the command line (using `dotnet`)?  Have you updated to the latest build of Visual Studio?

The C# compiler was updated so that it would not generate errors if there were the same namespaces between global and local usings.

**Comment by wli3** [comment]
@dsplaisted via commandline does work. I updated the issue description. It is still a big yak.

**Comment by pranavkm** [comment]
Closing as this has since been resolved.
