### ISSUE TITLE
After installing .NET 6.0 Preview 7, the version information of ASP.NET Core Runtime is incorrectly displayed.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/sdk#19022]
**Repro Steps**
1. Download .NET 6 SDK(6.0.100-preview.7.21368.2) from Release/6.0.1XX-preview7 column in [https://github.com/dotnet/installer](url)
2. Double click the .exe file go to install wizard.
3. After the installation is successful, the version information of ASP.NET Core Runtime is incorrectly displayed.

**Actual Result**
![image](https://user-images.githubusercontent.com/71361488/126104361-ce3a21f0-5b0b-48f3-8164-1849d07f6aa1.png)

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/19036
