### ISSUE TITLE
unable to pack nuget using dotnet pack --no-build command.

### ISSUE THREAD

**Issue by Bab95** [dotnet/sdk#19044]
**Version Used**: 5.0.205

**Steps to Reproduce**:
I have a custom packing mechanism defined for a master project which is suppose to include the other reference dll when it should pack.
1.build the project first using command dotnet build -c Release SolutionFile.sln
2. Now try to generate the nuget file from it. using the following command
dotnet pack --no-restore --no-build -c Release MainProject\MainProject.csproj /p:Version="<build_version>"  

**Expected Behavior**: nuget package should be generated.

**Actual Behavior**:  got following error : 
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(118,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked.
and no package was generated.

**Comment by dsplaisted** [comment]
Would you be able to supply a [binlog](https://aka.ms/binlog) or a repro of the failed pack operation?

Is there any particular reason you want to use the `--no-build` and `--no-restore` parameters to `dotnet pack`?

**Comment by WeihanLi** [comment]
6.0 SDK has the same issue

**Comment by Bab95** [comment]
@dsplaisted  yes we were using strong signing for the dll's and that step comes between build and pack. Anyways i have found the solution for this.
