### ISSUE TITLE
Running `dotnet workload install` sometimes installs newer workload versions with no way back

### ISSUE THREAD

**Issue by danroth27** [dotnet/sdk#19077]
If I run `dotnet workload install` for a specific workload it will first update the workload manifests to newer versions. This is sometimes problematic for me. For example, I installed a build of .NET 6 Preview 7 and then tried to install the WebAssembly build tools workload, which then ended up installing an RC1 version of the workload, which isn't what I wanted to test. I know that I can pass `--skip-manifest-update`, but the current experience feels like it's going to be a pit of failure. Once the workload manifest has been updated there is no clear way back if the newer version doesn't work for you. As far as I can tell, the best I can do is uninstall the workload and then manually delete the sdk-manifests folder and run a repair on my .NET SDK installation. I never want to manually mess around with the dotnet installation folder.

@KathleenDollard

**Comment by sfoslund** [comment]
We've implemented a rollback feature (https://github.com/dotnet/sdk/pull/18654) that will allow us to provide users a way to rollback to older manifests in the case of an issue with new releases. We have a backlog item to expand this feature to allow users to rollback to previous manifests on their own, but that will almost definitely not make .NET 6. 

@marcpopMSFT we've discussed expanding the rollback feature but I can't find the corresponding issue, do you know if it exists/ where it is?

**Comment by mhutch** [comment]
Currently there is a chance this can happen with previews, as an out of date preview can pull in workloads intended for a the current preview, which may depend on changes/additions in the newer preview. It should not happen in stable builds, as an SDK can only install workload updates from within its version band, and these kinds of changes should not happen within an SDK band.

Perhaps we can use a similar banding behavior for previews in future?

**Comment by danroth27** [comment]
Another case that could end up being problematic is if we ship a workload update that has a bad bug or regression.

At the same time, the current workload behavior is very similar to auto update functionality in many apps, which is pretty convenient.

**Comment by sfoslund** [comment]
> Another case that could end up being problematic is if we ship a workload update that has a bad bug or regression.

This is exactly the scenario the rollback feature will be used for. When this happens we'll be able to provide a rollback definition to users that will allow them to get their manifests back to a working state

**Comment by marcpopMSFT** [comment]
closing as we have rollback files now if absolutely necessary though it's not well documented.
