### ISSUE TITLE
Feature Request: Build .NET core .exe file in tiny output folder

### ISSUE THREAD

**Issue by davidmatson** [dotnet/sdk#1907]
(Hopefully this is the right place to make a feature request; if not, please feel free to redirect.)

I have a number of existing .NET Framework exes for tiny command-line utilities. I'd like to switch to .NET Core, but there are two key pieces I'd like to keep:
1. Building an exe that can be run directly, rather than going through dotnet run.
2. Building to an output folder that is small (does not contain 200+ files).

I suspect the best way to approach this would be to have a deployment type that's a slightly different mix between the existing FDD and SCD. It could be viewed as "SCD-lite" - build the same runtime-specific exe, but don't copy the framework binaries over. At runtime, the framework binaries would need to be in the path in order for the exe to run successfully. (Or even better, it would also check known locations such as C:\Program Files\dotnet\store.) It could also be viewed as "FDD + exe", where the output file set is basically the same as what FDD does today, and, like FDD, it depends on framework binaries which exist elsewhere, but it includes an exe wrapper so that it can be run directly from the command line (without the need to go through dotnet run).

Let me know if I've articulated this request clearly, and whether this idea seems feasible.

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/6237.

cc @steveharter on this one as well.
