### ISSUE TITLE
Provide a way to list installed workloads and their versions

### ISSUE THREAD

**Issue by danroth27** [dotnet/sdk#19076]
It looks like `dotnet workload list` shows you the list of available workloads to install, but how do you see which workloads are actually installed already? I'd also like to see the versions of the installed workloads.

**Comment by marcpopMSFT** [comment]
Let's discuss in the next workload meeting. As a reminder, list is the workloads you already installed and search will give you those you can install.

**Comment by marcpopMSFT** [comment]
List shows you the workloads you have installed but we don't today include the version. Try out `dotnet workload update --print-rollback` as our closest experience to this but we're not prepared to make that widely visible.
