### ISSUE TITLE
Checksum mismatch upon downloading package- packages-microsoft-prod.deb on ubuntu 20.04

### ISSUE THREAD

**Issue by bitsdance** [dotnet/sdk#19109]
Hello, 
All of a sudden the checksum of the package "packages-microsoft-prod.deb" is failing on ubuntu 20.04. We discounted the issued as we thought there might be mirror sync in the background, but It's been happening over 2 days now. 

**Environment:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Steps to reproduce -**
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get update -y

**output:**

_wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb_

--2021-07-21 12:42:44--  https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)...
40.114.136.21
Connecting to packages.microsoft.com (packages.microsoft.com)|40.114.136.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3124 (3.1K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb                          100%[===================================================================================================================>]   3.05K  --.-KB/s    in 0s

2021-07-21 12:42:44 (608 MB/s) - ‘packages-microsoft-prod.deb’ saved [3124/3124]

**dpkg -i packages-microsoft-prod.deb**
(Reading database ... 31897 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-debian10.1) over (1.0-debian10.1) ...
Setting up packages-microsoft-prod (1.0-debian10.1) ..

 **apt-get update -y**

**E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-armhf/Packages.bz2  File has unexpected size (14648 != 14446). Mirror sync in progress? [IP: 40.114.136.21 443]**
   Hashes of expected file:
    - Filesize:14446 [weak]
    - SHA512:dcde6b0120201ffd3ce98ccc67a941c82206af4c9f6edacb21dececab859d151b6b05ab9f59c1c7a0215912eccb319a632c26580371f84dfb723f6cfb64ab807
    - SHA256:8123690a1cfd7380c63554906b4bba25fc83142a3bc22c387ebc739f1427e1a5
    - SHA1:f134ba1077765a3c3f1e84dc50f36cfb319eaa05 [weak]
    - MD5Sum:9dd887b5872fbb823fc0ba1aae7eb306 [weak]
   Release file created at: Tue, 20 Jul 2021 21:47:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by zmj** [comment]
Also observing this issue

**Comment by sfoslund** [comment]
@mmitche can your team take a look at this or does someone else manage checksums?

**Comment by mmitche** [comment]
I think @MichaelSimons @dseefeld might be the first people to talk to for this.

**Comment by bitsdance** [comment]
Thank you all for your help. The issue got resolved this Morning.
