### ISSUE TITLE
Inconsistency between VS publish and dotnet CLI publish:  Could not load file or assembly 'System.IO.FileSystem, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definiti    on does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by GapiSla** [dotnet/sdk#1911]
Getting below exception on ubuntu 16.04 when trying to run ASP.NET Core MVC project (dotnet core 2.0 version). VS version 15.5.4. Runtime on ubuntu 2.1.3. However published package using CLI command works fine.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definiti    on does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by livarcocc** [comment]
Can you confirm that you are selecting the RID when publishing through VS? On VS, that needs to be set explicitly through settings in the publish profile.

cc @vijayrkn

**Comment by livarcocc** [comment]
Closing this issue since we haven't had activity here in a while. Will re-activate once I get an answer to my questions above.
