### ISSUE TITLE
Blazor WebAssembly AOT workload does not install on Windows 11 ARM64

### ISSUE THREAD

**Issue by mgrman** [dotnet/sdk#19126]
Hello,

I tried to install Blazor AOT workload on my Surface Pro X. Using following command:
`dotnet workload install microsoft-net-sdk-blazorwebassembly-aot`

which throws the following error:
`Workload with id microsoft-net-sdk-blazorwebassembly-aot is not supported on this platform.`

I am on latest Insider preview of Windows 11 and have `dotnet-sdk-6.0.100-preview.6.21355.2-win-arm64` installed.

I cannot find any documentation saying it is not supported, maui workload installed without a problem.
Is this supposed to work? Or am I missing some info about platform incompatibility?
Thank you.

**Comment by marcpopMSFT** [comment]
@lewing Any ideas here?

**Comment by lewing** [comment]
The workload is correctly reporting that we don't currently support win-arm64 platforms in the preview.  We're looking at what would be required to add support now.

**Comment by mgrman** [comment]
@lewing thank you for the info. Is this support planned to be added by release?

**Comment by realivanjx** [comment]
is linux arm64 support also planned? thanks.

**Comment by lewing** [comment]
cc @marek-safar @steveisok

**Comment by marcpopMSFT** [comment]
This should be resolved in 6.0.405 and 7.0.102 for windows.
