### ISSUE TITLE
First and second builds have different results. Why?

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#19140]
I am building https://github.com/jellyfin/jellyfin . It get very different results on first and second builds when building this repo. Why is that?

https://gist.github.com/richlander/8cdb09c79ed5dd032495165947f3e4f9

**Comment by danmoseley** [comment]
For the warnings only appearing first build - at least in the past, style warnings only appeared once I think, to reduce noise. That may still be the case.

Don't know about the can't copy file error, but sometimes it's a missing project reference (I didn't really look). A binlog from both builds would be needed.

**Comment by richlander** [comment]
If that's the case, that explains it. I was trying to understand the behavior I was seeing with a project I'm playing with but with I'm unfamiliar. Would be good to get clarity on this.

**Comment by richlander** [comment]
I can see from the behavior of the build that you are right. Closing.

**Comment by richlander** [comment]
The past project I worked on had warnings as errors enabled, which has a different dynamic (obviously).
