### ISSUE TITLE
Dotnet test doesn't run separate TargetFrameworks in parallel

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#19147]
### Issue Description

Attempting to run multiple unit tests in parallel for a test project with multiple target frameworks. However, there is no way to do this out of the box. The DispatchToInnerBuildsWithVSTestTarget target in Microsoft.Common.CrossTargeting.targets\ImportAfter\Microsoft.TestPlatform.CrossTargeting.targets that recursively calls VSTest does _not_ set the BuildInParallel option on the MSBuild task. Exerpt from version 5.0.302 of the sdk:

```
  <Target Name="DispatchToInnerBuildsWithVSTestTarget" Returns="@(InnerOutput)">
    <ItemGroup>
      <_TargetFramework Include="$(TargetFrameworks)" />
    </ItemGroup>
    <MSBuild Projects="$(MSBuildProjectFile)"
             Condition="'$(TargetFrameworks)' != '' "
             Targets="$(InnerVSTestTargets)"
             Properties="TargetFramework=%(_TargetFramework.Identity);VSTestNoBuild=true"
             ContinueOnError="ErrorAndContinue">
      <Output ItemName="InnerOutput" TaskParameter="TargetOutputs" />
    </MSBuild>
  </Target>
```

### Steps to Reproduce

1. Create a new mstest project, e.g. `dotnet new mstest`
2. enable multiple target frameworks for the test, with `<TargetFrameworks>net462;netcoreapp2.1;net5.0</TargetFrameworks>`
3. run `dotnet test` or `dotnet msbuild /restore /t:VSTest /p:TestInParallel=true`

Expected

Tests for each targetframework run in parallel, as long as the user selects the appropriate command line option or configuration.

Actual

Tests never run in parallel.

### Versions & Configurations

```
aaronla@aaronla-rabbit:PowerPlatform$ dotnet --version
5.0.302

aaronla@aaronla-rabbit:PowerPlatform$ dotnet msbuild --nologo --version
16.10.2.30804
```

**Comment by AR-May** [comment]
Seems like target "DispatchToInnerBuildsWithVSTestTarget" lives in this repo. Please, take a look.
cc @nohwnd

**Comment by aaronla-ms** [comment]
I should clarify, I understand the desire for test to run serially by default. The request is for an option to enable running in parallel. 

When we manually made this change in our repo, we saw an additional 45% speedup in test execution times.

**Comment by wli3** [comment]
@nohwnd could you look into this?

**Comment by 0xced** [comment]
I'd love to see this issue addressed. Currently, I'm running tests in parallel across different target frameworks by passing the built dlls + the `--parallel` option to `dotnet test` instead of the sln or csproj file (so that `--parallel` is forwarded to `vstest`).

For example:
```
dotnet test test\Serilog.Settings.Configuration.Tests\bin\Release\*\Serilog.Settings.Configuration.Tests.dll --parallel
```

This has the drawback of not reporting the correct target framework in the test summary, as explained by @nohwnd in https://github.com/microsoft/vstest/issues/2037#issuecomment-720549173.

It would be much better if we could do this instead and get correct target framework in the test summary:
```
dotnet test test\Serilog.Settings.Configuration.Tests --parallel --configuration Release
```

**Comment by nohwnd** [comment]
When using dotnet test + sln (or csproj) you can specify /maxcpucount:100 and that will tell msbuild to run in parallel on max of 100 nodes. In that setup we are starting 1 vstest.console and 1 testhost per project in your solution. 

The other path through dotnet test is when dlls are specified, this will send all those dlls to vstest.console and runs them in the same instance of vstest.console + 1 testhost per dll. I see myself explaining that the TFM reported is always the same, but I don't recall why.. :/

The third path where you would specify sln and get all the dlls and 1 instance of vstest.console does not exist. So even if we would tall vstesttask to run tests in parallel, it would still run 1 instance of vstest.console per project. Same as with maxcpucount.

**Comment by nohwnd** [comment]
^^^ I can retrospectively see that I missed your point @0xced , sorry.

**Comment by 0xced** [comment]
Can we please get some clarifications?

1. Does it mean that `dotnet test MyTests.csproj --parallel` will run tests of different target frameworks in parallel as described in my post above?
2. Will this ship as part of the [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) (17.10.0) package?

**Comment by nohwnd** [comment]
1. This is the new default for net9.0, you can opt-out back to the already parallel execution by `-p:TestTfmsInParallel=false`, this will run projects in parallel, but not their tfms. 

new 

mstest1.csproj net8
mstest1.csproj net8
mstest1.csproj net8

**Comment by nohwnd** [comment]
I am not fan of the --parallel flag, because there already is parallelism by default when you run with projects/solutions. So  --parallel would mean, parallel as before + parallel tfms. And not using --parallel would still mean parallel.

**Comment by 0xced** [comment]
Thanks for the clarification.

> We can backport to net8, ideally using the same flag, but letting it disabled by default.

That would be neat. 😀

> I am not fan of the --parallel flag, because there already is parallelism by default when you run with projects/solutions.

Good point, having all the projects/tfms run in parallel by default with the possibility to disable with a flag makes sense.
