### ISSUE TITLE
[dotnet-sdk-6.0.100-rc.1.21370.2] Blazor Server App project template missing css files in browser when using "dotnet run"  to launch

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/sdk#19187]
**OS**: Windows 10 Version 21H1
**OS Build**: 19043.1110
**.NET SDK**: dotnet-sdk-6.0.100-rc.1.21370.2
**.NET Info on test machine:**
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21370.2
 Commit:    64c36e46ff

**Runtime Environment:**
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21370.2\

**Host (useful for support):**
  Version: 6.0.0-rc.1.21369.2
  Commit:  f7e4c26181

**.NET SDKs installed:**
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21370.2 [C:\Program Files\dotnet\sdk]

**.NET runtimes installed:**
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21367.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21369.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21367.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Verification Scenarios:**
dotnet-sdk-6.0.100-preview.6.21351.1: Pass
dotnet-sdk-6.0.100-preview.7.21320.2: Partially Fail
dotnet-sdk-6.0.100-preview.7.21372.11: Fail
dotnet-sdk-6.0.100-rc.1.21370.2: Fail

**Reproduce Steps:**
1. Open a command line prompt window.
2. Run "dotnet new blazorserver -o BlazorApp" to create a default Blazor Server app.
3. Run "cd BlazorApp" navigate to project folder.
4. Run "dotnet run" to launch the app.
5. Open Edge browser to access https://localhost:5001 or http://localhost:5000

**Expected Result**:
The page should display well with the style (icon and Text). 
![Expected Result](https://user-images.githubusercontent.com/83067197/126745164-e2452cb0-78e7-41f8-bd8d-59838e169aa0.png)

**Actual Result**:
When running with dotnet-sdk-6.0.100-preview.7.21320.2, the text content display well but the icons are not displayed. it seems some style files are missing. 
![Actual Result](https://user-images.githubusercontent.com/83067197/126745222-4553eef2-3dbe-458e-9e08-5011582c1c6e.png)
When running with dotnet-sdk-6.0.100-preview.7.21372.11 and dotnet-sdk-6.0.100-rc.1.21370.2, it seems some style files are missing.
![Actual Result2](https://user-images.githubusercontent.com/83067197/126745350-905187d9-4c5b-4f1b-b4c7-dfd902aef550.png)

**Findings:**
1.  Tested with default ASP.NET Core web application, it works fine. This issue only occurs with Blazor Server App.
2.  Tried with Edge and Firefox, both of them has the same issue, so it should not related to compatibility issue with browser.
3.  If use "dotnet publish" command to publish the app, then launch the exe, it will display normally in browser.
4.  Compare the app's folder structure that generated with dotnet-sdk-6.0.100-rc.1.21370.2 and dotnet-sdk-6.0.100-preview.6.21351.1, below highlighted folder and files are the different part between these two projects.
![Findings](https://user-images.githubusercontent.com/83067197/126745479-eac4c434-bf22-4b79-bd8e-e6627cc34d60.PNG)

**Errors from Developer Tools in Browser:**
BlazorApp1.styles.css:1 Failed to load resource: the server responded with a status of 404 ()

@dotnet-actwx-bot @dotnet/compat

**Comment by mkArtakMSFT** [comment]
@javiercn , can you please take a look at this? Thanks!

**Comment by Junjun-zhao** [comment]
Verified with dotnet-sdk-6.0.100-preview.7.21375.4, it is works fine now. All icons and page format are normally. Will update the status again after we get the rc1 fixed build and verify it.

**Comment by mkArtakMSFT** [comment]
This is now fixed.
