### ISSUE TITLE
Get process ID of a .NET Core process through .NET CLI

### ISSUE THREAD

**Issue by sk-shahnawaz** [dotnet/sdk#19193]
I want to know the PID of the .NET Core process initiated by running the command `dotnet run` from within the source directory. How to achieve that?

**Comment by workgroupengineering** [comment]
I think this is a useful feature. It could be used like this:
``` bash
dotnet run | dotnet stack report
```

**Comment by Shahnawaz-QI** [comment]
`dotnet-stack ps` is giving the required result.
