### ISSUE TITLE
dotnet workload list returns an empty list 

### ISSUE THREAD

**Issue by TheCakeMonster** [dotnet/sdk#19192]
I installed Visual Studio 2022 preview 2, including the "Mobile Development with .NET" workload, to try out MAUI using .NET 6 preview 6 - which is shipped with VS2022 preview 2.

I ran "dotnet new maui" at the command prompt, and an error indicated that the template was unknown. That suggested that the maui workload wasn't installed, which made sense as it is still in preview. No problem so far.

I started a command prompt and ran "dotnet workload list" - it returned an empty list - this suggested that no workloads were available. 

This was unexpected behaviour. I don't think the .NET MAUI workload was installed, based on the fact that the template was not available. As a result, I would have expected "dotnet workload list" to return a list of available workloads, including MAUI - but it didn't.

I ran "dotnet workload install maui-desktop" and this showed an error indicating that elevation of privileges was required. I had run the command prompt without running as administrator. Aha, so maybe that was the problem.

I started a new command prompt with elevated privileges and ran "dotnet workload install maui-desktop" and this time the installation worked.

The main reason for raising this issue is to help anyone who gets an empty list when running "dotnet workload list". I couldn't find anyone saying that they had seen this and what to do about it if it happened. My suspicion is that it needs to be run at a command prompt with elevated privileges, but I have seen nobody say that, and it doesn't tell you that itself when you run it. Maybe this should be a warning emitted by the "dotnet workload list" command, if it is true?

I hope, at the least, that the existence of this issue helps other people who encounter this behaviour, even if no fix is considered necessary.

**Comment by igoventura** [comment]
Have You seen this docs? [](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install)

**Comment by TheCakeMonster** [comment]
@igoventura I hadn't seen that particular page, it's true. That one didn't help my understanding specifically, but it did lead me to the closesly associated page on "dotnet workload list" that has highlighted the error of my ways!

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-list

"dotnet workload list" is supposed to list the _installed_ workloads, not the _available_ workloads. It was supposed to be empty in my case. What I should have been doing was "dotnet workload search" to find a list of all of the available workloads. That's my mistake.

I think this happened because David Ortinau's blog post suggests using "dotnet workload list" and the screenshot shows it returning a list of workloads. That must be because he already had the workloads installed before writing the blog post.

https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-6/

@davidortinau Updating that blog post may be worthwhile so that nobody else falls into the same trap as me.

This issue should probably be closed. I think we can put this down to operator error on my part, although it was triggered by a slightly misleading introductory blog post.

@igoventura As an aside, the page you linked to doesn't seem to match my experience. It says that the install command doesn't need evelation on Windows. However, when I tried it from a non-elevated command prompt, I got an error message saying that it needed to be elevated, and the install failed. Either this has changed between previews 6 and 7, or the documentation is wrong.

**Comment by TheCakeMonster** [comment]
@igoventura Thanks for the help, by the way!

Do you know if the elevation requirement has changed between previews 6 and 7? If it hasn't changed then I should either leave this open, or close it and create another one to get the docs checked/corrected, or to work out why they don't match my experience.

**Comment by marcpopMSFT** [comment]
@TheCakeMonster the documentation is a little ahead of the product. The elevation requirement on windows should go away with RC1. It's in preview 7 but off by default currently as we need the backing msi packages to be done as eventually, the CLI will elevate for you and install MSIs that match the same MSIs that VS will install (that way the two share).  The documentation was written as the final release documentation so didn't take into account.  You can see we have a known issue listed for [preview 4](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#preview-4) which is still true for preview 7.

@KathleenDollard for feedback on list vs. search as you are not the first person to get those two swapped.

**Comment by TheCakeMonster** [comment]
@marcpopMSFT Thanks for the information on the elevation requirements, that makes sense. Good to know that the documentation is correct for the product as it will be released.

@KathleenDollard I'm wondering if enhancing the output of "dotnet workload list" would solve the problem for people. Here are two (hopefully small) changes to the output that might help developers:

1. Before the list is output, include the words "Installed workloads" so that it is clear what the list is detailing.
2. After the output, include a short hint stating that "dotnet workload search" can be used to find additional workloads to install

This approach of telling the user what they might want to do next, similar to the HATEOAS approach recommended in REST APIs, might be a good way of helping developers discover the way the tools are intended to work - hopefully with minimal additional development effort.

**Comment by marcpopMSFT** [comment]
I like this suggestion.  @sfoslund can you talk to Kathleen on the wording and if she's ok with it, add info ahead of the list that these are "installed workloads" and the mention of search after. I think that would go a long way to solving the confusion between the two.

**Comment by sfoslund** [comment]
Sure, talked to Kathleen and put out a PR: https://github.com/dotnet/sdk/pull/19503
