### ISSUE TITLE
[Package-Validation] Provide confirmation  that the package validation has run successfully

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#19214]
A couple of folks have asked if there is a way to check if the package validation has run successfully. 
 Currently we dont do anything if the package validation run successfully.

cc @safern @ericstj @ViktorHofer

**Comment by ViktorHofer** [comment]
Yes please. I spent too much time believing that PackageValidation crashed but instead actually ran successfully. Also this helps when looking through logs in CI. I would assume that a short message should be sufficient.

**Comment by safern** [comment]
> Yes please. I spent too much time believing that PackageValidation crashed but instead actually ran successfully

That is also because we found out that the header that shows in the binlogs or verbose output stating that API Compat failed is always created. I'm fixing that in my PR to add support to run with references.

**Comment by ViktorHofer** [comment]
I think we should log a message with low/medium verbosity so that the message doesn't show up in normal msbuild executions (which run with minimal verbosity) but is still part of more verbose logs and binlogs.

**Comment by z7f010** [comment]
https://login.microsoftonline.com/common/oauth2/authorize?client_id=499b84ac-1321-427f-aa17-267ca6975798&site_id=501454&response_mode=form_post&response_type=code+id_token&redirect_uri=https%3A%2F%2Fapp.vssps.visualstudio.com%2F_signedin&nonce=882fea5d-7749-4818-8129-a525394a4aef&state=realm%3Daex.dev.azure.com%26reply_to%3Dhttps%253A%252F%252Faex.dev.azure.com%252Fsignup%253FacquisitionId%253D2e30aa71-4971-4f1e-9c5b-4a0e67e4cb46%2526campaign%253Dacom~azure~devops~services~main~hero%2526githubsi%253Dtrue%2526WebUserId%253Db304fbaa50e5423cb0ad786b2c0f8eb0%2526acquisitionType%253DbyDefault%26ht%3D3%26mkt%3Dar-SA%26nonce%3D882fea5d-7749-4818-8129-a525394a4aef&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&cid=882fea5d-7749-4818-8129-a525394a4aef&wsucxt=1&githubsi=true&msaoauth2=true&mkt=ar-SA
