### ISSUE TITLE
Switch CLI language with a dotnet option

### ISSUE THREAD

**Issue by ncarandini** [dotnet/sdk#19246]
Sometimes, expecially when reporting an issue or writing a blog post in a foreign language, it can be usefull to switch CLI to a non-system language.

Currently  the dotnet CLI on Windows don't use the DOTNET_CLI_UI_LANGUAGE environment variable anymore and the workaround is to rename the folder of the system language in the dotnet SDK  folder (located on "dotnet-install-directory\sdk\sdk-version"). For example, renaming `it` to `it-off` if the system language is Italian. Please note that renaming is better than deleting, as we can revert to the system language simply restoring the folder name (i.e. `it-off` to `it`).

This is tedious and error prone, and I'd like to use a dotnet option  to set it , like `dotnet --lang-en --help` or `dotnet --lang-es --help` or `dotnet --lang-jp --help`.

Would it be feasible?

**Comment by dsplaisted** [comment]
Are you saying `DOTNET_CLI_UI_LANGUAGE` has stopped working?

I think that environment variable affects the output that comes directly from the .NET CLI, but doesn't affect messages from other things such as MSBuild or the compilers.  Could that be what you are seeing?

**Comment by marcpopMSFT** [comment]
Seems to work in preview 7 (set the value to "es")
![image](https://user-images.githubusercontent.com/12663534/129974754-1067ef71-3c9b-47bb-8371-571a6585a2d8.png)

**Comment by ncarandini** [comment]
Glad it works again, I've just tried and I can confirm.
