### ISSUE TITLE
Dotnet CLI does not work properly in VS 22 Terminal?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/sdk#19251]
I made a test (blank) app targeting net6.0.
1. It works great with dotnet CLI from cmd or powershell.
2. It also works great when I run it from VS via GUI (F5 / Ctrl + F5).

However, if I open VS' terminal, I get this:
![image](https://user-images.githubusercontent.com/31178401/126903300-18d433f8-a927-44b1-b3d3-77db17dd42be.png)

I have `6.0.100-preview.6.21355.2` installed. What could be the reason?

(sorry if it's a wrong repo for this report. If so, tell me where to send it instead)

**Comment by dsplaisted** [comment]
@DamianEdwards I think you linked to a VS feedback issue about this previously, do you know where that is?

**Comment by DamianEdwards** [comment]
@dsplaisted not sure, it doesn't show up in the "My feedback" list and I can't locate anything in email, Teams, etc. I do remember talking about this issue somewhere though. Will keep looking.

**Comment by marcpopMSFT** [comment]
https://developercommunity.visualstudio.com/t/NET-dotnet-tools-dont-work-from-the-/1456366

**Comment by marcpopMSFT** [comment]
Looks like VS is setting DOTNET_ROOT to the local copy of dotnet that doesn't include the aspnet runtime. We need to reach out to the VS folks as that should NOT be set for the terminal and see what other scenarios the VS environment is passed on to.

**Comment by marcpopMSFT** [comment]
This was fixed in preview4.
