### ISSUE TITLE
GenerateDocumentationFile doesn't run if imported from another target

### ISSUE THREAD

**Issue by steevcoco** [dotnet/sdk#1936]
Hello! :bowtie:

If I define GenerateDocumentationFile in an imported .targets file, then the project does not build the doc file.

With a simple imported .targets file like this:

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <GenerateDocumentationFile>true</GenerateDocumentationFile>
        </PropertyGroup>
    </Project>

And a simple project like this:

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <TargetFramework>netstandard2.0</TargetFramework>
        </PropertyGroup>
        <Import Project="..\..\..\Build\Sc.CommonLibraryConfiguration.targets" />
    </Project>

The documentation file is not built. ...

**Comment by dasMulli** [comment]
I'm unable to reproduce this, at least on the 2.1.4 SDK. Which SDK version are you using? (`dotnet --version`)

Note that the `Sdk=""` is only meant to be used in the main csproj, not the imported targets - at least, each sdk shall only be used once. (technically, the sdk attribute results in `<Import>` statements at the beginning and end of the project that uses it and a different position may have effects on the build). But that should not matter for this specific sample, it only generates multiple import warnings.

**Comment by steevcoco** [comment]
Sorry: I didn't copy and paste everything in the example. The project is netstandard2.0. Here are the complete files:

Build\Sc.CommonMetaData.targets

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <Authors>AUTHORS</Authors>
            <Company>COMPANY</Company>
            <Copyright>Copyright © 2015-2018 COPYRIGHT, USA</Copyright>
        </PropertyGroup>
    </Project>

Build\Sc.CommonConfiguration.targets

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <LangVersion>latest</LangVersion>
            <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
            <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
        </PropertyGroup>
    </Project>

Build\Sc.CommonLibraryConfiguration.targets

    <Project Sdk="Microsoft.NET.Sdk">
        <Import Project="Sc.CommonMetaData.targets" />
        <Import Project="Sc.CommonConfiguration.targets" />
        <PropertyGroup>
            <GenerateDocumentationFile>true</GenerateDocumentationFile>
        </PropertyGroup>
    </Project>

And the project:

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <TargetFramework>netstandard2.0</TargetFramework>
        </PropertyGroup>
        <Import Project="..\..\..\Build\Sc.CommonLibraryConfiguration.targets" />
    </Project>

**Comment by dasMulli** [comment]
Oh. remove the `Sdk=".."` attribute from everywhere but the main csproj.

**Comment by steevcoco** [comment]
Yes, OK! Sorry. That explains why I was getting "sdk.props cannot be imported again" in the build output!

Thanks!
