### ISSUE TITLE
net6.0 is not backward compatible with older version of netcoreapps

### ISSUE THREAD

**Issue by Swetha312** [dotnet/sdk#19374]
My sample application was built on .netcore3.0
 My csproj has the TargetFramework defined- <TargetFramework>netcoreapp3.0</TargetFramework>

I get **NETSDK1005** when I tried to publish the project in docker (mcr.microsoft.com/dotnet/sdk:6.0). 
Used the below command to publish the project,

`dotnet publish "C:\Sample\AspNetCoreMvc.csproj" -c Release -o "C:\Sample\test" -r win10-x64 /p:TargetFramework=net6.0`

I get the below error,

```
C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResoluti
on.targets(246,5): error NETSDK1005: Assets file 'C:\Sample\obj\project.assets.json' doesn't have a target for 'net6.0'. Ensure that restore has run and that you have include
d 'net6.0' in the TargetFrameworks for your project. [C:Sample\AspNetCoreMvc.csproj]
```

**This issue happens only with net 6.0.** 

I can publish the same project in sdk 5.0 fine (mcr.microsoft.com/dotnet/sdk:5.0)
`dotnet publish "C:\Sample\AspNetCoreMvc.csproj" -c Release -o "C:\Sample\test" -r win10-x64 /p:TargetFramework=net5.0` - This works totally fine.

**Comment by sfoslund** [comment]
This is expected. There are always things changed between major versions of .NET so retargeting your app from .NET 3 to any other version is not necessarily expected to work and may require user changes.

In general, I would recommend not specifying a target framework on the command line (... /p:TargetFramework=net6.0). If you would like to upgrade, you should do so by editing the project file then fixing any errors that are created by retargeting.

**Comment by superbonaci** [comment]
Related:
https://github.com/PowerShell/PowerShell/issues/16731
