### ISSUE TITLE
SingleFile Publish Win10-x64  failed to work  (.net 5 )

### ISSUE THREAD

**Issue by cnmade** [dotnet/sdk#19377]
I just upgrade my project from .net core 3.1 to latest .net 5. 
My project url : [https://github.com/cnmade/bsmi-shi](https://github.com/cnmade/bsmi-shi)

The SingleFile publish not working as .net core 3.1. 
After it complete publish. the exe file faild to start , it auto exit.

But if we do not choose SingleFile publish, it works.

###  What Expect:

SingleFile publish works well as non SingleFile publish

The good.
![image](https://user-images.githubusercontent.com/278153/127419943-3b5ba192-f5e0-4733-a5e2-fef3da56d4b2.png)

The not work

![image](https://user-images.githubusercontent.com/278153/127419916-1be1a387-93df-46bf-8d7d-87c47dc7bb75.png)

### Actually

The non SingleFile publish works.

The SingleFile publish can not execute , The output exe file will always failed to execute.

### How to reproduce.

1. Git clone the source code [https://github.com/cnmade/bsmi-shi](https://github.com/cnmade/bsmi-shi)
2. Try a non singleFile publish, The output exe file will success to execute.
3. Then try a SingleFile publish, you will find the output exe file failed to execute.

For compare, Downgrade to .net core 3.1

Both SingleFile publish , Non SingleFile publish works well the same , No any problem.

The document i reference was : https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#publish-a-single-file-app---visual-studio 

Can you please have a look?

[due to the github upload limit file size, i can not upload the file )
![image](https://user-images.githubusercontent.com/278153/127420678-6fcd1122-59d9-4330-8d68-6153d41c3e99.png)

**Comment by sfoslund** [comment]
@cnmade can you please provide the error that the single file app exits with as well as a binlog (https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) from publishing single file?

**Comment by cnmade** [comment]
I generated all the bin log, and now i upload it.
[Uploading all-binlog.zip…]()

**Comment by cnmade** [comment]
Hello, if any progress, thanks for let me know, I am really concern on it .

**Comment by sfoslund** [comment]
@cnmade it looks like the binlog failed to upload, can you try again? And can you also provide the error that you're seeing?

**Comment by cnmade** [comment]
```
0:000> g
ModLoad: 00007ffa`70010000 00007ffa`7003e000   C:\Windows\System32\IMM32.DLL
ModLoad: 00007ffa`15200000 00007ffa`15700000   D:\workspace\netroby\bsmi-shi\bin\Release\net5.0-windows\publish\coreclr.dll
ModLoad: 00007ffa`6fde0000 00007ffa`6ff36000   C:\Windows\System32\ole32.dll
ModLoad: 00007ffa`6ff40000 00007ffa`70004000   C:\Windows\System32\OLEAUT32.dll
(5ba8.2664): Unknown exception - code 04242420 (first chance)
ModLoad: 00007ffa`175f0000 00007ffa`1772b000   D:\workspace\netroby\bsmi-shi\bin\Release\net5.0-windows\publish\clrjit.dll
ModLoad: 00007ffa`6ab60000 00007ffa`6abfc000   C:\Windows\system32\uxtheme.dll
ModLoad: 00007ffa`540e0000 00007ffa`543e9000   C:\Windows\SYSTEM32\dwrite.dll
ModLoad: 00007ffa`6d360000 00007ffa`6d386000   C:\Windows\System32\BCrypt.dll
ModLoad: 00007ffa`174c0000 00007ffa`175ee000   D:\workspace\netroby\bsmi-shi\bin\Release\net5.0-windows\publish\PresentationNative_cor3.dll
ModLoad: 00007ffa`6b0b0000 00007ffa`6b0de000   C:\Windows\system32\dwmapi.dll
ModLoad: 00007ffa`6d7a0000 00007ffa`6d983000   C:\Windows\System32\CRYPT32.dll
ModLoad: 00007ffa`6c840000 00007ffa`6c852000   C:\Windows\System32\MSASN1.dll
ModLoad: 00007ffa`706c0000 00007ffa`7082b000   C:\Windows\System32\MSCTF.dll
ModLoad: 00007ffa`571c0000 00007ffa`57396000   C:\Windows\SYSTEM32\urlmon.dll
ModLoad: 00007ffa`60880000 00007ffa`608a6000   C:\Windows\SYSTEM32\srvcli.dll
ModLoad: 00007ffa`57bc0000 00007ffa`57e69000   C:\Windows\SYSTEM32\iertutil.dll
ModLoad: 00007ffa`6bec0000 00007ffa`6bece000   C:\Windows\SYSTEM32\netutils.dll
ModLoad: 00007ffa`6c260000 00007ffa`6c26c000   C:\Windows\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffa`15010000 00007ffa`151f4000   D:\workspace\netroby\bsmi-shi\bin\Release\net5.0-windows\publish\wpfgfx_cor3.dll
ModLoad: 00007ffa`14bb0000 00007ffa`1500c000   D:\workspace\netroby\bsmi-shi\bin\Release\net5.0-windows\publish\D3DCompiler_47_cor3.dll
ModLoad: 00007ffa`66900000 00007ffa`66ab8000   C:\Windows\SYSTEM32\WindowsCodecs.dll
ModLoad: 00007ffa`66380000 00007ffa`6651e000   C:\Windows\SYSTEM32\d3d9.dll
ModLoad: 00007ffa`65030000 00007ffa`6511e000   C:\Windows\System32\DriverStore\FileRepository\nvblwi.inf_amd64_25ca1e5037bff3ef\nvldumdx.dll
ModLoad: 00007ffa`65c20000 00007ffa`65c2a000   C:\Windows\SYSTEM32\VERSION.dll
ModLoad: 00007ffa`642e0000 00007ffa`6430f000   C:\Windows\system32\cryptnet.dll
ModLoad: 00007ffa`6c960000 00007ffa`6c9b9000   C:\Windows\System32\WINTRUST.DLL
ModLoad: 00007ffa`6f500000 00007ffa`6f51d000   C:\Windows\System32\imagehlp.dll
ModLoad: 00007ffa`6bc20000 00007ffa`6bc53000   C:\Windows\system32\rsaenh.dll
ModLoad: 00007ffa`06130000 00007ffa`0755f000   C:\Windows\System32\DriverStore\FileRepository\nvblwi.inf_amd64_25ca1e5037bff3ef\nvd3dumx_cfg.dll
ModLoad: 00007ffa`69310000 00007ffa`69334000   C:\Windows\SYSTEM32\WINMM.dll
ModLoad: 00007ffa`692e0000 00007ffa`6930d000   C:\Windows\SYSTEM32\winmmbase.dll
ModLoad: 00000233`7e5e0000 00000233`7e60d000   C:\Windows\SYSTEM32\WINMMBASE.dll
ModLoad: 00000233`7e610000 00000233`7e63d000   C:\Windows\SYSTEM32\winmmbase.dll
ModLoad: 00007ffa`2d460000 00007ffa`2f99e000   C:\Windows\SYSTEM32\igdumdim64.dll
ModLoad: 00007ffa`6f520000 00007ffa`6f996000   C:\Windows\System32\SETUPAPI.dll
(5ba8.2664): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
00000000`001bbc80 ??              ???
```

**Comment by cnmade** [comment]
I gave up to try resolve the problem, i back to dotnet 3.1. it works.
