### ISSUE TITLE
With .NET 6.0 Preview 7, I can't install Blazor WebAssembly AOT workload

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/sdk#19378]
**Repro Steps:**
1. Install latest Dev17.0 Preview3(Include SDK6.0.100-preview.7.21377.35) from PR :[Pull Request 338890: Insert .NET Core SDK 6.0.100-preview.7.21376.15 into VS main](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/338890)
2. Add feeds: 
https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21377.35-shipping-3/nuget/v3/index.json
https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json

3. Open commandline as administrator, run below command to install AOT workload, but failed.
    _dotnet workload install wasm-tools_
4. Run below command to install the workload and skip the advertising manifests, failed again.
   _dotnet workload install wasm-tools --skip-manifest-update_

**ACTUAL:**
![Untitled1](https://user-images.githubusercontent.com/35762055/127432987-38663ea9-4ada-4829-864b-e8e069a4a452.png)

![image](https://user-images.githubusercontent.com/35762055/127432898-6104738c-ca2b-47e3-ac16-c6cedf4d954b.png)

**Comment by lewing** [comment]
you will need to use https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21377.35-shipping-4/nuget/v3/index.json as the feed.

**Comment by marcpopMSFT** [comment]
See Larry's comment.  The unsigned files were pushed to the -3 feed by mistake.
