### ISSUE TITLE
ImplicitNamespaceImports generated codefile generates an invalid import if you try to import as an alias.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/sdk#19446]
Let's say for example I try to import these:

```xml
<Import Include="System" />
<Import Include="System.Collections.Generic" />
<Import Include="System.CommandLine" />
<Import Include="System.CommandLine.Help" />
<Import Include="System.CommandLine.Invocation" />
<Import Include="System.CommandLine.IO" />
<Import Include="System.Globalization" />
<Import Include="System.IO" />
<Import Include="System.Linq" />
<Import Include="System.Reflection" />
<Import Include="System.Text" />
<Import Include="System.Threading.Tasks" />
<Import Include="Elskom.Generic.Libs" />
<Import Include="Microsoft.Diagnostics.NETCore.Client" />
<Import Include="newsmakeResources = Elskom.Generic.Libs.Properties" />
```

The resulting generated ``<project name>.ImplicitNamespaceImports.cs`` file will contain:

```cs
// <autogenerated />
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.CommandLine;
global using global::System.CommandLine.Help;
global using global::System.CommandLine.Invocation;
global using global::System.CommandLine.IO;
global using global::System.Globalization;
global using global::System.Reflection;
global using global::System.Text;
global using global::Elskom.Generic.Libs;
global using global::Microsoft.Diagnostics.NETCore.Client;
global using global::newsmakeResources = Elskom.Generic.Libs.Properties;
```

Which results in: ``<project name>/obj/Debug/net6.0/<project name>.ImplicitNamespaceImports.cs(18,40): error CS1525: Invalid expression term '='``

I feel like whereever in the .NET SDK that generates that file that it should actully explicitly look for things like ``=``, ``static``, etc *before* it tries to insert ``global::`` then insert it *after* it finds ``static`` and/or ``=`` so that way the compilation would work.

My .NET SDK version currently is: ``6.0.100-rc.1.21366.58``.

**Comment by AraHaan** [comment]
Bug seems to be here: https://github.com/dotnet/sdk/blob/85943958e5a01d6bbd39a947aec2a4a37b8ba7cf/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateImplicitNamespaceImports.targets#L43-L47

**Comment by AraHaan** [comment]
The only way I can think of to this this problem is to actually move this into either an inline C# code task in the SDK (you guys probably have a policy against that) or move it to one of the Build Task projects that builds an dll so it can properly be fixed and have it assign to ``_ImportFileLine`` so that way the rest of the ``Target`` would work without issues.

**Comment by AraHaan** [comment]
Welp I tried on the PR and it seems no mater what I do something in the tests decides to fail.

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://github.com/dotnet/sdk/issues/19521>, it should be:

```XML
<Using Include="Elskom.Generic.Libs.Properties" Alias="newsmakeResources"/>
```

However, <https://github.com/dotnet/sdk/pull/19599> has not been merged yet.

**Comment by AraHaan** [comment]
So basically I should be doing ``<Using`` instead of ``<Import Include="..."``? Now what about static usings?

**Comment by KalleOlaviNiemitalo** [comment]
For C# projects yes, use `<Using>` rather than `<Import>`, after <https://github.com/dotnet/sdk/pull/19599> is merged.

**Comment by AraHaan** [comment]
But when will the daily builds ship with #19599 after it gets merged? On my Repositories and locally I use the daily builds from the .NET install scripts.

**Comment by wli3** [comment]
@JunTaoLuo could you look into this?

**Comment by DamianEdwards** [comment]
@wli3 @JunTaoLuo doesn't wort at Microsoft anymore.

@AraHaan the change to support `<Using />` has been merged and is now available in daily builds of the SDK. As such I'm closing this issue. If you have any other problems please log a new issue.
