### ISSUE TITLE
Using the PackageValidation OOB package results in FileNotFoundExceptions

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#19472]
```
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018: The "Microsoft.DotNet.PackageValidation.ValidatePackage" task failed unexpectedly. [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Packaging, Version=6.0.0.165, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018: File name: 'NuGet.Packaging, Version=6.0.0.165, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018:    at Microsoft.DotNet.PackageValidation.ValidatePackage.ExecuteCore() [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 38 [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018:    at Microsoft.DotNet.PackageValidation.ValidatePackage.Execute() in /_/src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs:line 44 [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x60015fc+0x3e [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-rc.1.21402.3\build\Microsoft.NET.Compatibility.Common.targets(23,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x600147b+0x804 [C:\git\runtime3\src\libraries\System.Net.Http.Json\src\System.Net.Http.Json.csproj]
```

I assume this is because the package doesn't carry along the NuGet and MSBuild dependencies.

cc @Anipik @safern @ericstj

**Comment by ViktorHofer** [comment]
This is kind of blocking as I would like to update to the newest build of the PackageValidation package in dotnet/runtime.

**Comment by ericstj** [comment]
Looks to me like that version of NuGet is revving rather quickly: https://github.com/dotnet/sdk/commit/a7afb3ced183c935a00567d012f054f82c0443b5

So perhaps the version in the SDK would be OK but because the task is building against a newer version it's not sufficient.  Should we use a lower version of NuGet when compiling the task so that we can run in older SDKs?  Same goes for Roslyn.

**Comment by safern** [comment]
Yes we need to pin the Nuget version as we did for Roslyn and check we are depending on an old enough Roslyn to run on at least on a Preview 5 SDK.

**Comment by Anipik** [comment]
> This is kind of blocking as I would like to update to the newest build of the PackageValidation package in dotnet/runtime.

we will have to add the <PackageDownload> to the repo as well because those have been removed from the package. This should go away when we start consuming the rc1 sdk.

**Comment by safern** [comment]
What do you mean? This ship with the SDK so we can just pin them to whatever version the Preview5 SDK used for example and then this would work even on older SDKs.

**Comment by Anipik** [comment]
we will need to pin the versions here https://github.com/dotnet/sdk/blob/main/src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj#L18
the validation check would be something like this 
https://github.com/dotnet/sdk/blob/main/src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs#L81

**Comment by Anipik** [comment]
> we will have to add the to the repo as well because those have been removed from the package. This should go away when we start consuming the rc1 sdk.

i missed the ```packageDownload```. we will need to this to runtime repo to use the package without using the rc1 version and 
having the baseline file. (This is a sidenote.)
```
  <ItemGroup Condition="'$(EnablePackageValidation)' == 'true' and '$(DisablePackageBaselineValidation)' != 'true' and '$(PackageValidationBaselinePath)' == '' and '$(PackageValidationBaselineVersion)' != ''">
    <PackageDownload Include="$([MSBuild]::ValueOrDefault('$(PackageValidationBaselineName)', '$(PackageId)'))" Version="[$(PackageValidationBaselineVersion)]" />
  </ItemGroup>

```

**Comment by ViktorHofer** [comment]
> i missed the packageDownload. we will need to this to runtime repo to use the package without using the rc1 version and

Already handled that in my PR: https://github.com/dotnet/runtime/pull/56712/commits/a98f2f7280cd3aa1fc90fcbf8002f7112b637913#diff-bde310e498052e67ae73f9f1014b3ee8e067170b61c410b6b3e180fb79ed7278R24-R26

**Comment by ericstj** [comment]
Hmm, I just checked and it looks like .NETFramework MSBuild doesn't carry NuGet binaries inside it like .NETCore does.  I don't think we can rely on it being provided for us.  Perhaps we should put the NuGet binaries in the package so that we can ensure they are present and not have to go looking for them via a resolve handler.
