### ISSUE TITLE
Static Web Assets no longer packs files generated during build

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/sdk#19474]
This looks like a regression versus the previous implementation of SWA. Files generated during the build (at least in the following case) don't get included in the nupkg unless they were already on disk before `dotnet pack` was run. This breaks the publishing of a couple of my packages.

Repro example:

 * Clone https://github.com/SteveSandersonMS/presentation-2020-01-NdcBlazorComponentLibraries
 * Edit `demo\src\BlazorChartist\BlazorChartist.csproj` to set the `TargetFramework` to `net6.0`
 * Make sure you're using .NET Core 6 RC1 (I'm using `6.0.100-rc.1.21401.2`) - check with `dotnet --version`
 * `cd demo\src\BlazorChartist`
 * `dotnet pack -c Release`
 * Check the contents of `demo\artifacts\Demo.BlazorChartist.0.1.0-dev.nupkg`

Expected:

 * Contains the generated static web asset `staticwebassets\BlazorChartist.js`

Actual:

 * It does not

Note that if you run `dotnet pack -c Release` again, then it *will* contain the asset. The bug is that it doesn't on the first build, which will generally break CI systems.

To verify this is a regression versus the previous SWA implementation, you can do the same as above, but use .NET Core 6.0 preview 6 (for example), and it will behave correctly.

cc @javiercn

**Comment by SteveSandersonMS** [comment]
Looks like what I should have been doing all along is this: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#typescript-integration

That definitely wasn't obvious to me when creating this sample back at the end of 2019, but I'm also not sure how we could make this sort of requirement more discoverable. Could SWA fail the build if new assets are added after `ResolveCurrentProjectStaticWebAssetsInputsDependsOn`? Maybe, I don't know, but it's only worth doing that if we think this is going to be a common mistake.

It's unfortunate that the new SWA implementation happens to do things in a different order than the old one but again, it's not clear that we really could avoid making changes to ordering that were not intended to be guaranteed in the first place.

**Comment by javiercn** [comment]
ResolveStaticWebAssetsInputs is a better place to hook yourself on to. There was a significant difference in the previous version between `ResolveStaticWebAssetsInputs` and `ResolveCurrentProjectStaticWebAssetsInputs`, however it became meaningless in StaticWebAssetsV2

**Comment by javiercn** [comment]
There is no docs label in the repo, and we haven't really invested in documenting this area, if you think we should, then I would recommend we file an issue on the asp.net core repo to specifically track what we want to document.

**Comment by SteveSandersonMS** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/34976

**Comment by javiercn** [comment]
Going to close this one in favor of that one.

**Comment by johanskoldekrans** [comment]
This is still an issue that has reappeared in Net 6 RC1. I have no staticwebassets-folder in my nugets after upgrading to rc1.

**Comment by SteveSandersonMS** [comment]
@johanskoldekrans I believe @javiercn is about to file an issue specifically tracking that we need to provide some clearer docs and guidance about how to handle this scenario when upgrading to .NET 6 (as per https://github.com/dotnet/aspnetcore/issues/36880#issuecomment-925980451). In the meantime you might want to check out how I solved it at https://github.com/aspnet/AspLabs/pull/382/files

**Comment by johanskoldekrans** [comment]
@SteveSandersonMS Thank you! I have been looking everywhere for something like this.
