### ISSUE TITLE
Static Web Assets incompatibility when targeting netstandard2.0

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/sdk#19475]
This seems to be a change in behavior with the new SWA which is breaking the publishing of one of my packages. This is similar to https://github.com/dotnet/sdk/issues/19474 but the failure mode is different. This situation is triggered when targeting `netstandard2.0`, whereas #19474 is triggered when targeting `net6.0`.

Repro example:

 * Clone https://github.com/SteveSandersonMS/presentation-2020-01-NdcBlazorComponentLibraries
 * Unlike [#19474](https://github.com/dotnet/sdk/issues/19474), do not change the target framework. Leave it as `netstandard2.0`.
 * Make sure you're using .NET Core 6 RC1 (I'm using `6.0.100-rc.1.21401.2`) - check with `dotnet --version`
 * `cd demo\src\BlazorChartist`
 * `dotnet pack -c Release`

Expected:

 * It should succeed

Actual:

```
Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets(436,5): error : Static web asset 'c:\path\demo\src\BlazorChartist\wwwroot\chartist.css' has invalid source type ''.
```

This error goes away if the target framework is changed to `net6.0`, or if you use an earlier preview of .NET Core 6 such as preview 6, or .NET Core 5.

As far as I know, it should be legal to target `netstandard2.0` and doing so shouldn't impose new requirements on the metadata associated with static web assets. Please correct me if that's wrong!

cc @javiercn

**Comment by javiercn** [comment]
This is going away in RC1

**Comment by javiercn** [comment]
60d659cb3ff8a78eb4b106bed5be81e142ff0c09
