### ISSUE TITLE
dotnet workload install maui Microsoft.Android.Sdk.BundleTool fail

### ISSUE THREAD

**Issue by mwbinderholz** [dotnet/sdk#19479]
Hello,

i tried to follow the installation guide on https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation

But i am stuck on dotnet workload install maui.
I already tried dotnet workload install maui-android.
Additionally with --verbosity or --include-previews.

But i am still getting only the following error message:
--
Installing pack Microsoft.Android.Sdk version 30.0.100-preview.6.62...
Writing workload pack installation record for Microsoft.Android.Sdk version 30.0.100-preview.6.62...
Installing pack Microsoft.Android.Sdk.BundleTool version 30.0.100-preview.6.62...
Workload installation failed, rolling back installed packs...

Workload installation failed: Downloading microsoft.android.sdk.bundletool version 30.0.100-preview.6.62 failed

--

Everything else works. I already deleted this bundletool from dotnet/sdk-manifests/6.0.100/microsoft.net.sdk.android/WorkloadManifest.json

Then everything runs through smoothly, even the maui-check.

Google tells me nothing other then installing bundletool myself?

I could not find any log files, which indicate this problem.

For further questions I am available tomorrow.

Kind regards.

**Comment by marcpopMSFT** [comment]
CC @Redth for visibility.

I would recommend against deleting the manifests as that can leave you in a bad state. Was there any more to the error that would indicate why this failed?

**Comment by mwbinderholz** [comment]
Thank you for your answer @marcpopMSFT .

CC @Redth 

There were no further information in the powershell.

I can provide screenshots of the current state of my android sdk, because I also followed this guide to set up my emulator
https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
![image](https://user-images.githubusercontent.com/88394046/128302387-9f084f0e-8845-4d1c-bb3e-3340f1994241.png)
![image](https://user-images.githubusercontent.com/88394046/128302437-250f2584-c169-4f11-aa4f-e3700bea2c2d.png)
![image](https://user-images.githubusercontent.com/88394046/128302493-c0a40c28-6cfb-4590-b446-dd077e5cd009.png)
![image](https://user-images.githubusercontent.com/88394046/128302507-5654f676-a750-4b0a-b516-b1b800450fe6.png)
![image](https://user-images.githubusercontent.com/88394046/128302563-d23954a4-05ff-43ea-b8d3-5dc878da4b33.png)

I am currently using Windows 10 Pro Version 10.0.17134 Build 17134
Visual Studio 2022 Preview 64-bit Version 17.0.0 Preview 2.1
Mirosoft :NET Framewok Version 4.8.03761

I could remember I installed .Net 6 beforehand. But I don't know how anymore, if that matters.

Thank you for your help.

**Comment by mwbinderholz** [comment]
I just tried to deinstall everything and installing again, and the problem still pops up.
Additionally now the maui-check doesn't work anymore

Powershell:
--
 C:\WINDOWS\system32> maui-check
      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

¤ .NET MAUI Check v0.7.1.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
» Synchronizing configuration...
× This version of the tool is incompatible with installing an older version of .NET 6

Press enter to exit...

--

my dotnet sdk check

C:\WINDOWS\system32> dotnet sdk check
.NET SDKs:
Version                        Status
------------------------------------------
6.0.100-preview.6.21355.2      Up to date.

.NET Runtimes:
Name                              Version                       Status
---------------------------------------------------------------------------
Microsoft.NETCore.App             5.0.8                         Up to date.
Microsoft.NETCore.App             6.0.0-preview.6.21352.12      Up to date.
Microsoft.WindowsDesktop.App      6.0.0-preview.6.21353.1       Up to date.
Microsoft.AspNetCore.App          6.0.0-preview.6.21355.2       Up to date.


The latest versions of .NET can be installed from https://aka.ms/dotnet-core-download. For more information about .NET lifecycles, see https://aka.ms/dotnet-core-support.

**Comment by next-autumn** [comment]
same issue

**Comment by mwbinderholz** [comment]
With the new visual studio 2022 installer it is possible to install Maui without using powershell
