### ISSUE TITLE
[Package Validation] Link to diagnostics ID docs page in suppression files

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#19515]
Today in PR reviews you need a decoder to understand what's in the file.  We should include a comment, or description about what the codes mean.  If we're concerned with file size we could have a "legend" of IDs in the file.  This doesn't need to be treated as relevant to the suppression, but could help when folks review these.  https://github.com/dotnet/runtime/pull/56712/files#r681889176

**Comment by ViktorHofer** [comment]
@smasher164 you might want to pick this one up as it fits nicely into the "Adopt APICompat in dotnet/runtime story". Besides the two options that Eric mentioned we could also just add a link to the docs page that enumerates and explains the diagnostic ids.
