### ISSUE TITLE
More options for @(Import) and C# 10 global usings?

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#19535]
Context: https://github.com/xamarin/xamarin-android/pull/6118

We have an issue in .NET 6 Android applications, where every Android app has a method like:
```csharp
protected override void OnCreate(Bundle? savedInstanceState)
```

We don't want to include `<Import Include="Android.OS" />`, because `Android.OS.Environment` would conflict with `System.Environment`. Developers would likely use `System.Environment`, so we don't want to cause an issue there.

So our plan is to add the global using:
```csharp
global using Bundle = global::Android.OS.Bundle;
```

Unfortunately, it's not possible to use the `@(Import)` item group to do this, because it always prefixes `global::`:

https://github.com/dotnet/sdk/blob/86946f52cd012cefd811b25287a8da034bf082a3/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateImplicitNamespaceImports.targets#L46

What we did for now is generate our own C# file for this one line.

This seems OK, but is it worth adding some support to `@(Import)` so you could do something like:

```xml
<Import Include="Bundle = global::Android.OS.Bundle" />
```

Maybe the dotnet/sdk could simply skip the `global::` prefix if the string contains it?

**Comment by JunTaoLuo** [comment]
@DamianEdwards who's the area owner. I don't think this is a feature we're looking to add at the moment since it's explicitly only designed for namespace imports and not aliases.

**Comment by DamianEdwards** [comment]
@JunTaoLuo actually I listed that as one of the things to do as part of the feedback in #19521. As part of renaming `<Import />` to `<Using />` and `<DisableImplicitNamespaceImports>` to `<ImplicitUsings>` it becomes more natural and event expected to support this.

**Comment by DamianEdwards** [comment]
Closing this as the request feature is covered in #19521. Once that's done you'll be able to do:
``` csproj
<Using Include="Android.OS.Bundle" Alias="Bundle" />
```
