### ISSUE TITLE
Require individual languages opt-in to Hot Reload

### ISSUE THREAD

**Issue by tmeschter** [dotnet/sdk#19608]
Right now the SDK adds the "SupportsHotReload" project capability to every project targeting .NET 6.0 or above:

https://github.com/dotnet/sdk/blob/e10860e628714df3a2b55af7c6a4967ab85a4b84/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L1129-L1132

This puts the burden on languages that do not currently support Hot Reload to know they need to opt out. It would be better to let each individual language opt-in to Hot Reload by adding this project capability in their individual .targets.

**Comment by DamianEdwards** [comment]
@pranavkm
