### ISSUE TITLE
PackageValidation uses the wrong roslyn when the Microsoft.Net.Compilers.Toolset is used

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#19615]
PackageValidation uses the `RoslynTargetsPath` property which always points to the compiler in the SDK. When using the toolset package, [the CSharpCoreTargetsPath and VisualBasicCoreTargetsPath properties are overwritten](https://github.com/dotnet/roslyn/blob/06495a2bf3813e13cff59d2cdf30c24c99966d8e/src/NuGet/Microsoft.Net.Compilers.Toolset/build/Microsoft.Net.Compilers.Toolset.props#L10-L11) but never the `RoslynTargetsPath`.

Also, as the CodeAnalysis task assembly is bundled with the toolset package, does this logic need to run at all when using the Microsoft.Net.Compilers.Toolset package? https://github.com/dotnet/sdk/blob/a6e14e80ca216d6a394387a628f0e3abbadd6f28/src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs#L78-L92

**Comment by ViktorHofer** [comment]
cc @Anipik @safern

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by Anipik** [comment]
> CodeAnalysis task assembly is bundled with the toolset package, does this logic need to run at all when using the Microsoft.Net.Compilers.Toolset package?

the codeAnalysis is not loaded before the package validation task is run even while consuming it through the package.
