### ISSUE TITLE
net 6.0 throws NETSDK1005 error during build/publish via cmd as it does not accept the property "TargetFramework(s)"

### ISSUE THREAD

**Issue by Swetha312** [dotnet/sdk#19628]
**_https://github.com/dotnet/sdk/issues/19487 - Could not re-open this issue So I'm creating a new one._** 

Below is the my csproj file,
```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
```

and running the below command fails,
`dotnet publish "MY_TEST_APP_CSPROJ_PATH" -c Release -o "RELEASE_PROJ_PATH" -r win10-x64 /p:TargetFramework=net6.0`

But, I can run the below command fine,
`dotnet publish "MY_TEST_APP_CSPROJ_PATH" -c Release -o "RELEASE_PROJ_PATH" -r win10-x64 /p:TargetFramework=net5.0`

To be clear, I can build totally fine with net 5.0, it fails only with net 6.0.

_Note: As a workaround, I updated csproj to accept the variable (TF)
`<TargetFramework>$(TF)</TargetFramework>`
and running the below command works,
`dotnet publish "MY_TEST_APP_CSPROJ_PATH" -c Release -o "RELEASE_PROJ_PATH" -r win10-x64 /p:TF=net6.0`_

**Comment by iskiselev** [comment]
Can #19487 be reopened and this been closed to discuss it in one place?

**Comment by marcpopMSFT** [comment]
Old bug triage: tracked in the other bug.
