### ISSUE TITLE
latest.version metadata file is not updated

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#19634]
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/main/latest.version still returns 

```
789b3b05e88efadc383017d52005423356b472f8
6.0.100-preview.6.21276.12
```

I would expect it to be preview7 or rc1 by now.

**Comment by kalikin** [comment]
This may be the reason why [install script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) still downloading preview6 SDK with `-Channel 6.0` option. 
With added `-Runtime dotnet` it downloads preview7 runtime as expected.

**Comment by sebastienros** [comment]
@leecow @rbhanda I believe that this is a manual operation (checked previous identical issues).
Who needs to be notified? It's breaking the aspnet benchmarks since it's relying on this file to install the latest sdk, and lots of components ask for langversion 10 now.

**Comment by rbhanda** [comment]
I have updated https://dotnetcli.blob.core.windows.net/dotnet/Sdk/main/latest.version to reflect .NET 6 Preview 7 release
