### ISSUE TITLE
Global tools shim signing is lost when tool is updated

### ISSUE THREAD

**Issue by Redth** [dotnet/sdk#19663]
### Description

Fix global tools shim signing is lost when tool is updated

### Customer Impact

After running a tool update, if the shim (the exe to start up .net tool) is signed, it would lose its signature.

### Regression?

No, it is an bug since the packaged shim feature is created. The packaged shim is applied only during install not in update.

### Risk

Low

Need to port to

- [ ] 3.1.4xx https://github.com/dotnet/cli/pull/13781
- [ ] 3.1.1xx  https://github.com/dotnet/cli/pull/13782
- [ ] 5.0.2xx https://github.com/dotnet/sdk/pull/20389
- [ ] 5.0.3xx https://github.com/dotnet/sdk/pull/20390
- [ ] 5.0.4xx https://github.com/dotnet/sdk/pull/20391

Original:
-----------------------------

I have added authenticode signing to the shim and assemblies in maui-check:
https://github.com/Redth/dotnet-maui-check/blob/main/MauiCheck/MauiCheck.csproj#L98-L104

When the tool is initially installed via: `dotnet tool install -g redth.net.maui.check` the shim that gets installed to `%USERPROFILE%\.dotnet\tools\maui-check.exe` has the digital signature.

However, if a new version is installed or the same version is reinstalled via `dotnet tool update -g redth.net.maui.check`, that shim file no longer contains the signature.

The shims in the extracted package (ie:  `%USERPROFILE%\.dotnet\tools\.store\redth.net.maui.check\0.7.3\redth.net.maui.check\0.7.3\tools\net5.0\any\shims\win-x64\maui-check.exe`) do still contain the signature as expected.

Somehow the shim that gets copied in an update is different or modified vs the one that is originally used from the clean install.

Since this tool runs elevated, the untrusted publisher prompt shows up for the updated tool instead of showing the trusted publisher info as it does on a clean install.

**Comment by acraven** [comment]
I've just encountered the same problem, I need to perform an `uninstall` and `install` rather than `update` to replicate the clean install @Redth mentioned.
