### ISSUE TITLE
Generate multiple variants of an assembly using same TargetFramework

### ISSUE THREAD

**Issue by xen2** [dotnet/sdk#1966]
Note: not sure if this fits here, nuget or msbuild...

We ship a game engine which has some compile-time difference between platforms (iOS vs Linux vs Windows) and graphics API (OpenGL vs Windows, which have separate PackageDependencies).

Note that only few of those packages are platform/graphics-API specific.
i.e., we might have Engine (cross-platform) which depends on Graphics (one per graphics-API) which depends on IO (one per platform).

Until now we had one folder per "runtime", i.e. `Windows\D3D`, `Windows\OpenGL`, `Linux\OpenGL`, etc. (note: graphics API independent files are directly in `Windows` and `Linux`).
Then we have lot of ".targets magic" to deal with that. Ideally we would like to move away from that and use new csproj system and targets and publish the game engine as proper nuget packages that can be easily referenced.

I see different options but each have some drawbacks or not possible due to how it currently works:

(1) Keep something similar to what we had: use `$(Platform)` to use a different runtime folder during assembly resolution.
However, it doesn't play nice with nuget restore since `Platform` is not passed to it, and it generates a single `project.json` in `obj` folder rather than in `obj\$(platform)` that contains everything (I tried overriding `ProjectAssetsFile` but it works only with MSBuild, not NuGet/VS as it seems to compute intermediate output path on its own).
Also, it wouldn't be able to handle different dependencies per runtime.

(2) Make platform specific packages, i.e. `Engine.D3D` and `Engine.OpenGL`.
However, any "neutral" lib depending on them need might need a fake `Engine` neutral package, and force the top-level app to add the real one it needs. This would be quite manual/cumbersome for user.

(3) Use cross targeting. However we are limited by the concept of runtime which can't collide nor be customized: we would need TargetFramework that looks like `net461+win+d3d` and `net461+win+opengl` and `net461+linux+d3d` and allow them to fallback to `net461` in package resolution if nothing else exists?
This would play nice with nuget and current infrastructure.

(4) In the meantime, I suppose our only option is to still provide custom targets inside platform-specific packages to not use default folders and instead collect platform-specific assemblies (i.e. `lib\net461\win-d3d\*.dll` instead of `lib\net461\*.dll`) This is similar to the ".targets magic" we were doing so far, but at least in proper NuGet packages and automatically setup by `build\MyPackage.targets`.

Option (3) sounds like the best approach but would need some modification to pass additional info on top of `TargetFramework` and do some changes to NuGet & SDK targets. Would you be open to accepting such changes?

Any help/hint or alternative ideas appreciated, thanks!

**Comment by livarcocc** [comment]
@emgarten who might have some ideas on how to organize the nupkgs in this case.

**Comment by xen2** [comment]
I also noticed packages such as https://www.nuget.org/packages/runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl/
Maybe I could reuse this "runtime" system, seems to match closely what I want to do (for C# rather than C++ though).
