### ISSUE TITLE
Workload commands failing after installing VS2022 Preview 3 and .NET 6 Preview 7

### ISSUE THREAD

**Issue by efonsecab** [dotnet/sdk#19671]
### Describe the bug
After installing .NET 6 and Visual Studio 2022 Preview 3, I tried to install the MAUI workloads, using both maui-check and dotnet workload install.

maui-check fails while trying to repair workloads

### To Reproduce
Install Visual Studio 2020 Preview 3
Try to install the MAUI workloads.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/3481899/129095524-27f0592e-340c-4b58-8525-c32967ea32da.png)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by MarkStega** [comment]
There is a workaround:

1) Delete C:\Program Files\dotnet\metadata\workloads folder
2) Go to CMD (Admin)
3) run "dotnet workload install maui"

**Comment by marcpopMSFT** [comment]
@Redth for the maui check failure. We have a lot of compat issues between versions of the workloads so this is likely related.  Clearly out the metadata folder will remove all historical install data and clean things up.

**Comment by marcpopMSFT** [comment]
Any problems with preview 4? If not, I'll resolve this as maui check is not going to be the recommended path forward.
