### ISSUE TITLE
referenced package in .NET is not copied if the OutputType is not “Exe”

### ISSUE THREAD

**Issue by persiandeveloper** [dotnet/sdk#19698]
I have a .netstandard (V2.0) project (called X) that has dependency on Newtonsoft.Json (V 13.0.1) through package reference.

There is a .net 5.0 library project (Called B) that references X. When I build the project "B", in bin folder I can see the X.dll but the "Newtonsoft.Json" dll file is not copied.

If I add "Exe" to project B, it will copy "Newtonsoft.Json" dll to bin folder.

`<OutputType>Exe</OutputType>
`
How can I make the simple library project (B) to have X and its dependencies?

**Comment by KalleOlaviNiemitalo** [comment]
Set the [CopyLocalLockFileAssemblies](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies) property.

**Comment by dsplaisted** [comment]
Yes, `CopyLocalLockFileAssemblies` is the way to do this.

**Comment by persiandeveloper** [comment]
Does it work when I want to make it as nuget package ? Does it copy the ""Newtonsoft.Json" to the target project ?
