### ISSUE TITLE
Solution build running for 18 min. after upgrade to Visual Studio 2022 17.0.0 Preview 3.0 and SDK 6.0.100-preview.7.21379.14

### ISSUE THREAD

**Issue by p-bojkowski** [dotnet/sdk#19695]
Hi!

after I upgrading from Visual Studio 17.0.0 Preview 2 and SDK 6.0.100-preview.6 to
Visual Studio 2022 17.0.0 Preview 3.0 and SDK 6.0.100-preview.7.21379.14 -
the build takes now on my solution 18 min.!

Before the upgrade it takes only 35 sec.
How to check what is going on?
How to enable logging to see what now take so much more time?

Maybe related to this issue too: https://github.com/dotnet/roslyn-analyzers/issues/5369

**Comment by marcpopMSFT** [comment]
@ladipro seen any other reports like this?

**Comment by ladipro** [comment]
@marcpopMSFT I'm not aware of build perf regressing in Preview3.

@p-bojkowski please check [these instructions](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) on how to create a detailed binary build log. If you want us to take a look, please [open a Visual Studio feedback ticket](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio) and attach the binlog file. [Here](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md) is more information on binlogs in case you'd like to first investigate yourself.

**Comment by ladipro** [comment]
@p-bojkowski OK to close this issue or would you like us to help investigate. Thank you.
