### ISSUE TITLE
[StaticWebAssets] Tweak the settings when invoking referenced projects

### ISSUE THREAD

**Issue by javiercn** [dotnet/sdk#19704]
Through integrating static web assets in Maui we've discovered that we need some Tweaks to the project references. When we capture the project references and merge them in a StaticWebAssetConfiguration item, we need to ensure we capture the right set of properties from the associated project reference to ensure later on we invoke them in the same way we did to collect the references originally.

This for example mean capturing thins like UndefineProperties and so on to apply them appropriately in the subsequent calls.

**Comment by dsplaisted** [comment]
Looks like this was fixed with #19720?
