### ISSUE TITLE
.NET SDK 6 Preview 7 generated file `ImplicitNamespaceImports.cs` contains error CS8773

### ISSUE THREAD

**Issue by andschwa** [dotnet/sdk#19702]
Good morning,

I just tracked down a CI failure to a .NET SDK update. With `dotnet v6.0.100-preview.7.21379.14` our whole build is [failing](https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=84470&view=logs&j=f07d69e4-3e72-53cd-6968-8728b0ae8cd2&t=56b36b60-eec0-5478-0768-cbdbadd5d8f5&l=654) with the repeated error:

```
...obj\Debug\net6.0\PowerShellEditorServices.Test.ImplicitNamespaceImports.cs(2,1):
error CS8773: Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater.
```

This error did not show up [last night](https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=84434&view=logs&j=f07d69e4-3e72-53cd-6968-8728b0ae8cd2&t=56b36b60-eec0-5478-0768-cbdbadd5d8f5&l=307), with the same build on the same code, but using `dotnet v6.0.100-preview.6.21355.2`. The big difference seeming to be Preview 6 to Preview 7.

I looked at #19446, but we do not (as far as I can find) use any `<Import Include=...>` statements in any of our `.csproj` files.

We are explicitly using [language version 9.0](https://github.com/PowerShell/PowerShellEditorServices/blob/e83c3fea1359993024de2f44d0e6b419639df79b/PowerShellEditorServices.Common.props#L7), so I will update us to 10.0 to work around this, but it seems like there may be an underlying and unintended change between the two previews?

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/sdk/pull/19599> already changed the feature to opt-in so the file will not be generated unless you set the `ImplicitUsings` property or define `Using` items. But this was merged after 6.0 preview 7. If you do not intend to use implicit usings in PowerShell, I suggest disabling them with `DisableImplicitNamespaceImports` until you can update to a version where they are disabled by default.

**Comment by andschwa** [comment]
Is the issue that Preview 7 opted everyone in, and the opt-out by default wasn't merged in time to fix that for Preview 7?

**Comment by davidfowl** [comment]
It’s changed in rc1 not preview 7

**Comment by AArnott** [comment]
I just hit this when upgrading a project from the 5.0 SDK to 6.0.100-preview.7.21379.14.
My project explicitly sets `LangVersion` to 9. IMO the SDK shouldn't generate files that require C# 10 without confirming that the LangVersion is at least set to that level.

**Comment by andschwa** [comment]
Yup, and I'm already looking to revert my language version back to 9.0 because I didn't realize that 10.0 would force all devs to update the SDK on their box to Preview 7 :/

**Comment by davidfowl** [comment]
It'll be fixed in rc1 builds. For now you can disable the feature.

**Comment by andschwa** [comment]
Oh, here's the information I needed, for those that come looking:

- https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/implicit-namespaces
- https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#disableimplicitnamespaceimports

**Comment by davidfowl** [comment]
More information on the latest changes https://github.com/dotnet/sdk/issues/19521
