### ISSUE TITLE
dotnet pack version suffix is not respected

### ISSUE THREAD

**Issue by vadi2** [dotnet/sdk#19713]
Neither `dotnet pack --version-suffix rc` nor `dotnet pack /property:VersionSuffix=rc` is working to give the package a suffix.

The output for either command is:

```
  Successfully created package '/home/runner/work/Hammer/Hammer/nupkg/Hammer.0.0.3.nupkg'.
```

This is with 5.0.400.

**Comment by dsplaisted** [comment]
The `VersionSuffix` will only work if the `Version` is not set.

Are you setting `Version` to `0.0.3` in this case?  Probably you want to set `VersionPrefix` instead, and then I think it will work like you want.

**Comment by vadi2** [comment]
Yep I am... why would I want a prefix instead of a suffix though? I'd like `0.0.3-rc`.

**Comment by KalleOlaviNiemitalo** [comment]
@vadi2, I think @dsplaisted meant you should set `VersionPrefix=0.0.3` and `VersionSuffix=rc`, and not set `Version`. Then Microsoft.NET.DefaultAssemblyInfo.targets would set `Version=0.0.3-rc`.

<https://github.com/dotnet/sdk/blob/1f6482d1ed33083dadea53c0336091fb65652513/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultAssemblyInfo.targets#L14-L18>

**Comment by dasMulli** [comment]
> why would I want a prefix instead of a suffix though

In https://github.com/dotnet/sdk/issues/1131 the unfortunate naming was discussed with the outcome (https://github.com/dotnet/sdk/issues/1131#issuecomment-297455098):
> I'm just not seeing a compelling enough reason to make a breaking change here and I don't see a non-breaking proposal that adds enough value. I'm closing this because I think the status quo is the least bad option we have.

**Comment by vadi2** [comment]
Unfortunate situation to be in - I'd like to see the docs improved to reflect this. It looks like such an amazing, easy to use option at first.

**Comment by dsplaisted** [comment]
@tdykstra Could you file a doc issue to add (or improve) documentation of the `Version`, `VersionPrefix`, and `VersionSuffix` properties?  See #1131 for discussion of the behavior.

**Comment by vadi2** [comment]
Sure done, I filed it against the root of the issue which is the `--version-suffix` argument: https://github.com/dotnet/docs/issues/25742.
