### ISSUE TITLE
.NET Core 2.1 framework option available in 15.5 TFM

### ISSUE THREAD

**Issue by vsccarl** [dotnet/sdk#1975]
After installing .NET Core 2.1 on VS 15.5, the option to select it in the project properties page becomes available. Building the project does not seem to produce any errors.

**Comment by dasMulli** [comment]
to be sure, you installed a 2.1.300-… preview version of the sdk? (`dotnet --version`)

if so, you should create a `global.json` file in the solution's directory (or in a a directory above the source files you are working with) pinning the version of the sdk to be used to a non-preview one:

```json
{
    "sdk": {
        "version": "2.1.4"
    }
}
```

**Comment by livarcocc** [comment]
This is for now, by design. We are discussing other alternatives to keep VS more "inline" with the SDK version that it shipped with, but no firm plans yet.

Meanwhile, I am going to close this issue.
