### ISSUE TITLE
BlazorAOT workload installation not working 

### ISSUE THREAD

**Issue by ar0311** [dotnet/sdk#19798]
Installed 6.0-preview6 via install-dotnet-preview.sh

ubuntu:~$ sudo dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
Workload with id microsoft-net-sdk-blazorwebassembly-aot is not recognized.
install
  Install a workload.

Usage:
  dotnet [options] workload install [<WORKLOAD_ID>...]

Arguments:
  <WORKLOAD_ID>  The NuGet Package Id of the workload to install.

**Comment by joeloff** [comment]
@ar0311 Can you confirm that you have workload manifest files present in your SDK? Those define the workload IDs that the install command would recognize. They should be under a folder named sdk-manifests in your dotnet installation

**Comment by ar0311** [comment]
adam@ubuntu:/usr/share/dotnet$ ls
default.profraw  host         metadata  sdk     templates
dotnet           LICENSE.txt  packs     shared  ThirdPartyNotices.txt

that's all thats in the dotnet directory

**Comment by joeloff** [comment]
Thanks @ar0311 The manifest files is the primary driver behind workload commands as it defines both the packs used to compose a workload, but also the dependencies between different workloads. I've got an Ubuntu setup with 20.04 and see if I can repro this.

**Comment by realivanjx** [comment]
this works fine inside docker container from image `mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7-focal-amd64`

**Comment by ar0311** [comment]
> this works fine inside docker container from image `mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7-focal-amd64` with `python3` installed

That's probably because it's installed using the binary archive in the container, not the deb?

**Comment by ar0311** [comment]
> Thanks, I checked the .deb file from preview7 and it too is missing the manifest files. The only work-around would be to pull them from the tar.gz and copy them in or switch to using the tar ball for the installation until we can fix this.

Can confirm copying the sdk-manifests folder from tar.gz to dotnet folder created by preview deb work around allowed me to sucessfully install wasm-tools workload and use it.

**Comment by joeloff** [comment]
Awesome, we're working on getting the .deb fixed

**Comment by marcpopMSFT** [comment]
Old workload install bug. Should be working now.
