### ISSUE TITLE
Ensure <Using /> declarations from in-box SDKs are conditioned on C#

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#19793]
The new `<Using />` item type is explicitly intended to only be used in C# projects. The [code generation targets](https://github.com/dotnet/sdk/blob/f2cc77b60cdc2a4e8b393adf7b855b478ad79671/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L1131) and [core global usings items](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L27) are already conditioned on C# but we should ensure that the higher-level SDKs (e.g. Web, Worker, WindowsDesktop, etc.) also condition any using item types they bring in by C# too.

- Current Web props: https://github.com/dotnet/sdk/blob/main/src/WebSdk/Web/Sdk/Sdk.props#L61
- Current Worker props: https://github.com/dotnet/sdk/blob/main/src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props#L41
- Current BlazorWasm props: https://github.com/dotnet/sdk/blob/main/src/BlazorWasmSdk/Sdk/Sdk.props#L23
- Current WinForms props: https://github.com/dotnet/winforms/blob/main/pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.Sdk.WindowsDesktop.WindowsForms.props#L15
- Current WPF props: https://github.com/dotnet/wpf/blob/main/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.props#L5

**Comment by mhutch** [comment]
To be absolutely explicit, is this the behavior (and pattern) we expect all the workload targets to follow?

```xml
<ItemGroup Condition="'$(Language)' == 'C#' And ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable')">
```

Should we have the SDK targets compute a property to centralize this logic? For example, if the SDK targets did this:

```xml
<PropertyGroup>
  <_CSharpImplicitUsings
      Condition="'$(Language)' == 'C#' And ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' =='enable')"
  >
  true
  </_CSharpImplicitUsings>
</PropertyGroup>
```

Then workload targets could do this:

```xml
<ItemGroup Condition="'$(_CSharpImplicitUsings)' == 'true')">
```

**Comment by DamianEdwards** [comment]
@mhutch that satisfies the desired specificity I think, so sure 😃

**Comment by RussKie** [comment]
WPF props: https://github.com/dotnet/wpf/blob/main/packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.props
