### ISSUE TITLE
After install 6.0 Preview 7 on Mac OS, install workload maui using command line failed.

### ISSUE THREAD

**Issue by lemon0213** [dotnet/sdk#19822]
**Platform**
- [ ] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
1.	Clean MacOS Big Sur machine.
2.	Install 6.0 Preview 7 from [https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.7-macos-x64-installer](https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.7-macos-x64-installer).
3.	Execute “sudo dotnet workload install maui” from command line.

**Actual Result**
Workload install failed.
![image](https://user-images.githubusercontent.com/66412274/129878605-2a45e632-09ab-4b03-a57c-93ca78730307.png)

**Error Log**
[workload install failed.log](https://github.com/aspnet/AspNetCore-ManualTests/files/7006301/workload.install.failed.log)

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/21102
