### ISSUE TITLE
WPF/Winforms fails to run.

### ISSUE THREAD

**Issue by haiyanliu2** [dotnet/sdk#19871]
Environment: Version 17.0.0 Preview 4.0 [31618.318.main]+ NET 6 SDK: 6.0.100-rc.1.21418.40
Repro steps:
1.dotnet new wpf -o  Mywpf
2.cd Mywpf
3.dotnet build
4.dotnet run
Expected
The project run successfully.

Actual
No response.
![image](https://user-images.githubusercontent.com/87641893/130039301-eb9a3b57-52b7-4cdf-8532-a962078cb6e2.png)
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21418.40
 Commit:    4bef385e31

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22443
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21418.40\

Host (useful for support):
  Version: 6.0.0-rc.1.21418.9
  Commit:  2a28e2f015

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21418.40 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21418.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21418.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21418.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ryalanms** [comment]
WinForms and WPF are both failing with PlatformNotSupportedExceptions in different runtime assemblies (System.Windows.Extensions and System.Drawing.Common). 

@ViktorHofer @mmitche :  Could WindowsDesktop be picking up the wrong dependency versions?

**Comment by mmitche** [comment]
I think https://github.com/dotnet/windowsdesktop/blob/release/6.0-rc1/eng/Version.Details.xml#L4 needs a CPD. Will fix,.

**Comment by mmitche** [comment]
Fixed now.

**Comment by vdanche** [comment]
Fixed on 6.0.100-rc.1.21424.1(runtime-6.0.0-rc.1.21423.9)
