### ISSUE TITLE
Xunit output from dotnet test truncated

### ISSUE THREAD

**Issue by bab5470** [dotnet/sdk#19883]
When running `dotnet test` on our .net core application to run xunit tests we're seeing some exceptions but they're being truncated in the output which makes it impossible to troubleshoot the problem.

Here's an example:

```
 Failed RepliesService.Tests.IntergrationTests.GraphQlIntegrationTests.GraphQlRequests_ReturnExpectedResults(queryName: "GetRepliesByItemId", queryBody: "{\n                     repliesByItemId(itemId:456"...) [24 ms]
```

We're running this on CentOS 8.4 and .Net Core information is as follows:

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /home/jenkins/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/home/jenkins/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I've tried a variety of things to get more output:
dotnet test --verbosity d[etailed] 
dotnet test --verbosity diag[nostic]
dotnet test --logger "console;verbosity=detailed" 
dotnet test --logger "trx;LogFileName=TestResults.trx"

The first three create are FAR too verbose. I can't make heads or tails of the output - it's just a mess to try to parse. 
The last doesn't seem to have any information that I can see. 

There has to be a way to get untruncated errors.

Thanks
Brad

**Comment by nohwnd** [comment]
Hello, this is correct. Your method name is too long for the formatter. We don't want to print the whole method name into the console, because the parameters can contain a ton of data, as in your example. This would pollute your log when test succeeds. 

If you have hard time diagnosing the failure you should focus on including the relevant information into the assertion failure / exception. This can be done, by taking advantage of the `because` field in FluentAssertions. Or maybe by using their BeEquivalentTo functionality which is excellent at comparing objects and their subsets. Exceptions are printed fully:

```cs
// file UnitTest1.cs
namespace xunit7;

public class UnitTest1
{
    [Theory]
    [InlineData("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris elementum mauris vitae tortor. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Nulla pulvinar eleifend sem. Integer vulputate sem a nibh rutrum consequat. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Curabitur sagittis hendrerit ante. Vivamus porttitor turpis ac leo. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Aliquam erat volutpat. Aliquam ornare wisi eu metus. Phasellus rhoncus. Integer vulputate sem a nibh rutrum consequat.")]
    public void Test1(string name)
    {
        throw new Exception(name);
    }
}
```
![image](https://user-images.githubusercontent.com/5735905/151961757-626c993f-ebb0-4b18-89f6-2f5a1cb47018.png)

**Comment by DialLuesebrink** [comment]
Could the Formatter be made an extendable feature? The problem with writing your info in the assertion message is that if you run into something like an AccessViolation you are out of luck.
