### ISSUE TITLE
`dotnet new android` attempts to restore Microsoft.AspNetCore.App.Runtime.linux-arm64

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#19891]
If you install .NET 6 RC1 and the Android workload, we are now using `**FromWorkload**` so a `NuGet.config` should no longer be needed when building Android projects.

Unfortunately, you get a different error now when testing this:
```
error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-arm64 with version (= 6.0.0-rc.1.21417.2)
```

Build log: [msbuild.zip](https://github.com/dotnet/sdk/files/7016700/msbuild.zip)

I found I could workaround the problem with:
```xml
<Target Name="_RemoveLinuxFrameworkReferences"
    AfterTargets="ProcessFrameworkReferences">
  <ItemGroup>
    <_ProblematicRIDs Include="linux-arm;linux-arm64;linux-x86;linux-x64" />
    <PackageDownload Remove="Microsoft.AspNetCore.App.Runtime.%(_ProblematicRIDs.Identity)" />
    <PackageDownload Remove="Microsoft.NETCore.App.Host.%(_ProblematicRIDs.Identity)" />
  </ItemGroup>
</Target>
```
I will probably put this workaround in the Android workload *for now*.

This is probably related to the RID graph. I tried making an adjustment to the RID graph in the past, but they wouldn't accept this change:

https://github.com/dotnet/runtime/pull/45927

**Comment by jonathanpeppers** [comment]
Oh, this did come up before: https://github.com/dotnet/sdk/issues/11289

**Comment by marcpopMSFT** [comment]
@jonathanpeppers closing to be tracked by newer discussions we have going on. If this is still a separate issue, feel free to reactivate.

**Comment by jonathanpeppers** [comment]
I think this is fixed, but I'll try removing this target to be sure:

https://github.com/xamarin/xamarin-android/blob/5efda9d6923bb2478a2efb2e17104791a169ec1f/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets#L17-L24
