### ISSUE TITLE
Regression in .NET SDK 5.0.400: Can no longer publish WinForms/WPF app for win-arm64 (NETSDK1082)

### ISSUE THREAD

**Issue by kpreisser** [dotnet/sdk#19991]
Hi,
after upgrading to .NET SDK **5.0.400**, we can no longer publish a `net5.0` WPF or WinForms app for `win-arm64`. However, this works correctly using SDK **5.0.303** (for .NET 5.0.9) and SDK 5.0.302 (for .NET 5.0.8).

To reproduce:
- Install .NET SDK 5.0.400 for Windows x64 on Windows 10 x64.
- Run `dotnet new wpf`
- Run `dotnet publish -f net5.0-windows -r win-arm64`

**Actual result:**
```
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\Admin\Desktop\test-wpf\test-wpf.csproj (in 81 ms).
C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(415,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win-arm64'. [C:\Users\Admin\Desktop\test-wpf\test-wpf.csproj]
```

However, if you publish for `win-x64`, the publish is successful.

Thank you!

**Comment by ryank425** [comment]
https://github.com/dotnet/sdk/issues/15972

Will be fixed in next Net 5 401 sdk
