### ISSUE TITLE
[Loc]With .NET 6 rc1 installed on locale OS, all strings are unlocalized when runing "dotnet workload..." in CLI.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/sdk#19993]
Install .NET 6 RC1 with .NET SDK zip in a clean local machine.

Actual Result:
All strings are not localized.

TK
e.g.
![image](https://user-images.githubusercontent.com/65638819/130424307-20367786-dade-4695-b8a2-82148e6b918e.png)

![image](https://user-images.githubusercontent.com/65638819/130423264-4f3b0acc-cf61-4fec-9df8-f58306e2a02a.png)

dotnet --info
.NET SDK (varsa global.json dosyasını yansıtır):
 Version:   6.0.100-rc.1.21422.7
 Commit:    aa6d5ccdec

Çalışma Zamanı Ortamı:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\v-damu\Downloads\dotnet-sdk-6.0.100-rc.1.21422.7-win-x64\sdk\6.0.100-rc.1.21422.7\

Host (useful for support):
  Version: 6.0.0-rc.1.21421.1
  Commit:  0ab239d537

.NET SDKs installed:
  6.0.100-rc.1.21422.7 [C:\Users\v-damu\Downloads\dotnet-sdk-6.0.100-rc.1.21422.7-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21421.3 [C:\Users\v-damu\Downloads\dotnet-sdk-6.0.100-rc.1.21422.7-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21421.1 [C:\Users\v-damu\Downloads\dotnet-sdk-6.0.100-rc.1.21422.7-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21420.5 [C:\Users\v-damu\Downloads\dotnet-sdk-6.0.100-rc.1.21422.7-win-x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ryank425** [comment]
I don't think most of strings you see were ever translated in xlf files. 

For ex, looking at Korean version - sdk/src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf (https://github.com/dotnet/sdk/blob/de6bcd49c3593911391465c18d51a94ca3062960/src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf)

I barely see any messages get translated.

```

<trans-unit id="AdManifestUpdated">
  <source>Updated advertising manifest {0}.</source>
  <target state="new">Updated advertising manifest {0}.</target>
  <note />
</trans-unit>

```
 ```
<trans-unit id="InstallingWorkloadManifest">
  <source>Installing workload manifest {0} version {1}.</source>
  <target state="new">Installing workload manifest {0} version {1}.</target>
  <note />
</trans-unit>
```




Interestingly, looking at the file, I didn't realize that some translated messages are more descriptive than original English ones.

```
<trans-unit id="CommandDescription">
  <source>Install a workload.</source>
  <target state="needs-review-translation">전역 또는 로컬 도구를 설치합니다. 로컬 도구는 매니페스트에 추가되고 복원됩니다.</target>
  <note />
</trans-unit>
```

Korean content from `<target state="needs-review-translation">` translates to **"Install a global or local workload. Local workloads are added to manifests and restored".**

**Comment by KalleOlaviNiemitalo** [comment]
The more verbose Korean translation seems to have been copied from here: <https://github.com/dotnet/sdk/blob/2638bbaf17e44e2106adcafc8f492fe062c54d01/src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf#L56>

I suppose somebody will update the translation to match the shorter source string, and change `state="needs-review-translation"` to `state="translated"` at that time.

**Comment by wli3** [comment]
Thank you for your post. We haven't started the localization process for 6.0 branches yet. It would be done in few months

**Comment by vdanche** [comment]
Still repro on local OS on the latest RC2-6.0.100-rc.2.21478.25(runtime-6.0.0-rc.2.21474.18).
e.g DE
![image](https://user-images.githubusercontent.com/65637796/135419654-e43fdfdd-7945-4a98-aa1a-a3f7908e105f.png)
