### ISSUE TITLE
Static Web Assets build error with .net 6 preview 7

### ISSUE THREAD

**Issue by ErikApption** [dotnet/sdk#20008]
.NET 6 preview 7 did break our open source AElemental library static web assets. This issue seems similar (or possibly identical?) to #19475 but the class library that fails is targeting .NET 5. It looks like this issue is fixed in the new RC1 build but not sure how to move forward with current version.

``
1>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets(436,5): error : Static web asset 'C:\code\elemental-blazor\Elemental\wwwroot\css\elemental.min.css' has invalid source type ''.
1>Done building project "Elemental.csproj" -- FAILED.
``

Repro:
1. pull https://github.com/apption-oscode/elemental-blazor/tree/develop
2. Use .net SDK 6.0.100-preview.7.21379.14
2. Build solution in visual studio

Build did work with .net 6 preview 6 but breaks with .net 6 preview 7.

**Comment by javiercn** [comment]
@ErikApption thanks for contacting us.

As you mentioned, this should be fixed in RC1 builds, you can try a nightly build from dotnet/installers to validate or unblock yourself. If you run into issue with an RC1 build, let us know

**Comment by ErikApption** [comment]
@javiercn same error with 6.0.100-rc.1.21458.32
