### ISSUE TITLE
Project specifying <Platforms> element cannot be referenced from agnostic project

### ISSUE THREAD

**Issue by KevinH-MS** [dotnet/sdk#2005]
See:  https://github.com/KevinH-MS/platformsbug

I have a lib project with:
```<Platforms>x64</Platforms>```

and a test project that does not specify any platforms (that references the lib).

When I compile, I get:
```
2>CSC : error CS0006: Metadata file 'C:\Users\kevinh\Source\Repos\x64\CoreLib\bin\x64\Release\net461\CoreLib.dll' could not be found
2>Done building project "CoreTests.csproj" -- FAILED.
```

If I add ```<Platforms>x64<Platforms>``` to the test project, I don't get the compile error, but other things in VS break (like test explorer).  If I change everything to singular ```<Platform>``` everything seems to work as expected.

**Comment by karkatic** [comment]
in addition, test coverage finds 0 coverage still, even with the workarounds

**Comment by livarcocc** [comment]
@KevinH-MS this seems like a problem in VS. I just tried dotnet test on the test project in your repro repo and one tests was executed and passed.

@Pilchie could this be an issue in the project system?

**Comment by Pilchie** [comment]
@davkean any ideas here?
