### ISSUE TITLE
Consecutive installs should report installed workload

### ISSUE THREAD

**Issue by joeloff** [dotnet/sdk#20085]
Install the same workload twice,

1. ```dotnet workload install wasm-tools```
2. ```dotnet workload install wasm-tools```

After the second command it tells you that the workload was installed. The typical behavior for installers would be to prompt for repair/uninstall, or we could simply detect the workload record and inform the user that it's already installed and no-op.

If files were simply copied again, then the behavior sounds similar to a repair. For MSI based installs there would be no effect, but the message is still confusing because it made no changes to the system.

**Comment by sfoslund** [comment]
Fixed by #22557
