### ISSUE TITLE
Create packages with multiple RuntimeIdentifiers cross-platform build

### ISSUE THREAD

**Issue by xen2** [dotnet/sdk#2009]
Using `<TargetFrameworks>` results in multiple builds and is properly supported by NuGet pack (`lib/<tfm>`) and Visual Studio.

However, `<RuntimeIdentifiers>` doesn't seem to have much impact except for package consumption.
I was expecting to also be able to create such NuGet packages, with `runtimes/<runtime>/lib/<tfm>` folders.

For the use case, I would like to develop a library that support this kind of combination of TFM/Runtime identifiers:
- monoandroid50 (no runtime identifier)
- net461 (windows)
- net461 (unix)
- net461 (macos)
- xamarinios10
- uap10.0

Note that runtime identifiers are different for each TFM.

Is the only choice to develop custom cross-targeting targets myself, or will it be supported in nuget/dotnet/vs at some point?

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6633
