### ISSUE TITLE
Test project templates

### ISSUE THREAD

**Issue by codito** [dotnet/sdk#201]
(This issue is a discussion follow up to the [initial PR for test templates](https://github.com/dotnet/sdk/pull/188)).

Following are the requirements for the test template:
1. Emit `runtimeconfig.*.json` on build. This is required for the `dotnet vstest` and `dotnet test3` commands to setup the `--additionalProbingPath` for dotnet exec so that nuget references are resolved.
2. Allow P2P reference to all user projects (both class libraries and console apps).
3. Allow publish of the test project. This will allow user to run tests in a machine which doesn't have a source code enlistment e.g. a CDP flow, where tests are run in a Release Definition (usually acceptance tests on a Unix or Windows machine with her product installed)
4. Test project shouldn't include a program entry point. The entry point is always the testhost which comes from the test platform (see `Microsoft.TestPlatform.TestHost` nuget package).

If we choose a `Console App` based project template, (4) may need work.
If we choose a `Class Library` based project template, (4) is met, but 1,3 may need work.

**Notes**
(1) was supported with a special check in older project model (see [Microsoft.Dotnet.ProjectModel](https://github.com/dotnet/cli/blob/1278e9d6bf35500e9672fe3f53125df1d08717d8/src/Microsoft.DotNet.ProjectModel/Project.cs#L130)).
(4) was supported with `emitEntryPoint: false` in project.json.

**Comment by srivatsn** [comment]
This is done.
