### ISSUE TITLE
Run multiple test assemblies in parallel with dotnet test and NUnit

### ISSUE THREAD

**Issue by drauch** [dotnet/sdk#20115]
We want to run multiple assemblies in parallel with `dotnet test` and NUnit 3.x. This is no problem using the nunit-console runner, however, in .NET 5 you are supposed to use `dotnet test` instead which does not seem to have the possiblity to run the given assemblies in parallel.

Note: we _don't_ want to run the tests within one assembly in parallel, we want to run multiple assemblies that are given to `dotnet test` in parallel.

Best regards,
D.R.

**Comment by nohwnd** [comment]
@drauch there is --parallel option, but I see it is missing from the help. 

```
dotnet test C:\t\nunit-parallel\nunit1\bin\Debug\net6.0\nunit1.dll C:\t\nunit-parallel\nunit2\bin\Debug\net6.0\nunit2.dll --parallel
```

And also `--logger:"console;verbosity=detailed"` to see easier how tests are executing, but it will mix the output.
