### ISSUE TITLE
'Microsoft.AspNetCore.App', version '5.0.0' was not found

### ISSUE THREAD

**Issue by k2tomasz** [dotnet/sdk#20116]
When running dotnet run from PowerShell in VS 2022 I am getting an error (blow). This does not happen when run from VS 2019 or standalone terminal.

❯ dotnet run
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64

❯ dotnet --list-sdks
3.1.412 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

**Comment by marcpopMSFT** [comment]
I believe this was a known issue in the terminal a few months ago when it was incorrectly setting the environment for a local copy of the runtime rather than using the globally installed ones. I believe this is fixed now.
