### ISSUE TITLE
SDK 3.1 builds C#9 code in a way leading to bugs

### ISSUE THREAD

**Issue by bessgeor** [dotnet/sdk#20119]
Consider the following scenario:

netcoreapp3.1 TFM csproj with langversion 9

IsExternalInit written by hand as in [this article](https://btburnett.com/csharp/2020/12/11/csharp-9-records-and-init-only-setters-without-dotnet5.html) (because 3.1 FCL does not offer it)

also, Newtonsoft.Json 12.0.3 is installed.

Given the code
```csharp
public record Something(
  [property: JsonProperty("nameOverride")]
  string Whatever
);

public static class Program {
  static void Main() {
    var smth = new Something("propValue");

    Console.WriteLine(JsonConvert.SerializeObject(smth));
  }
}
```

we'll get different outputs based on which SDK we are using to build the sample.

Using 3.1.412:  `{"Whatever":"propValue"}`
Using 5.0.300: `{"nameOverride":"propValue"}`

The latter is expected in the both cases

**Comment by nagilson** [comment]
@marcpopMSFT shall we move this to c# lang?

**Comment by marcpopMSFT** [comment]
Given this is in the 3.1 SDK which is out of support, I'd probably just close unless it repros in a newer SDK.

**Comment by nagilson** [comment]
Ya, I'm guessing this was an intentional breaking change in c#9 but I couldn't find it. @bessgeor please file a new issue if you are still facing trouble with this, if this is from a language breaking change perspective file here https://github.com/dotnet/csharplang
