### ISSUE TITLE
Workload installer needs to be aware of x64-retargeted packs

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#20139]
As part of the x64-on-ARM64 work we'll install x64 to a subdirectory on ARM64 machines.  This will result in workloads being installed to a new location.

We need to represent this location with it's own path in the registry.

The proposal is to make all pack registration architecture specific.  @joeloff identified the following places in the runtime we'll need to change:
https://github.com/dotnet/sdk/blob/2fae3ba11d0ae610419a5dc98bdd9244b0bf1a2f/src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/RegistryWorkloadInstallationRecordRepository.cs#L29
https://github.com/dotnet/sdk/blob/2fae3ba11d0ae610419a5dc98bdd9244b0bf1a2f/src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs#L117 

We don't think we need to modify https://github.com/dotnet/installer/blob/main/src/finalizer/finalizer.cpp

@joeloff - should we modify the runtime code to look in both locations, ignoring arch-neutral and using arch-specific if it exists?    That'll let it light up once we get the installer work done.  Alternatively does it need to always handle both?

**Comment by joeloff** [comment]
Fixed in https://github.com/dotnet/sdk/pull/20248 for RC1
