### ISSUE TITLE
New warning about preview SDK is logged a lot in large solution

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2018]
When I build https://github.com/mikeharder/dotnet-cli-perf/tree/master/scenarios/web/large/core, I get spammed with the message.

NETSdkMessage even manages to take up 74 ms.

cc @livarcocc

**Comment by livarcocc** [comment]
Can you think of a better location (target dependency) to put this message on? Maybe we should do it only for build?

**Comment by nguerrera** [comment]
I think the ideal behavior is once per build invocation, not even once per project. I think we're now getting it once per (project, tfm), which is way too much.

@rainersigwald Is there a good pattern for logging a message once per build invocation? I'm thinking maybe something that caches whether it's been logged with the build engine and appropriate lifetime, but that seems heavy-handed.

**Comment by nguerrera** [comment]
(Even that probably wouldn't work with parallel nodes, right?)

**Comment by rainersigwald** [comment]
In a single process you could use [`RegisterTaskObject`](https://github.com/Microsoft/msbuild/blob/bf2f8a4e91195d049060b253d9d47ace4cc62017/src/Framework/IBuildEngine4.cs#L38-L66)/`GetRegisteredTaskObject` to keep track of whether you've already logged the message, but I don't think there's a nice easy way to get the same behavior across nodes.

**Comment by nguerrera** [comment]
Once per node is a lot better than what we have now. Maybe we should start with that.

**Comment by rainersigwald** [comment]
Another option: implement the target as a p2p instead:

```xml
  <Target Name="_CheckForNETCoreSdkIsPreview"
          BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
    <MSBuild Condition=" '$(_NETCoreSdkIsPreview)' == 'true' "
             Project="$(MSBuildThisFileDirectory)\PreviewSdkWarning.proj"
             RemoveProperties="TargetFramework;Configuration" />
  </Target>
```

```xml
<Project>
  <Target Name="_CheckForNETCoreSdkIsPreview">
    <NETSdkMessage
                   Importance="High"
                   ResourceName="UsingPreviewSdkWarning" />
  </Target>
</Project>
```

Doing that BeforeTargets _CheckForInvalidConfigurationAndPlatform is a bit sketchy, though.

(came up when talking to @AndyGerlicher about something else)

**Comment by nguerrera** [comment]
Interesting. I'm worried about the overhead of that, but we could measure.
