### ISSUE TITLE
Crash after publishing .net5 console app having C++/CLI dependency 

### ISSUE THREAD

**Issue by hichem001** [dotnet/sdk#20231]
Hi,
I have .net5 console app that has as dependency C++/CLI .net5 managed wrapper to unmanaged C++ dll. Every things works fine: the exe is generated and I can execute it without any issue. 
But I have seen that some files are also generated besides to my exe app: a dll (with the same name as my exe) and other .json files that contains dependencies. When I take the exe alone, it doesn't work, it requires the dll and the runtimeconfig.json file to be on the same location. I want to avoid that and not share these files with my exe (note that for me it doesn't matter to share .net5 C++/CLI wrapper and the unmanged dll), so one of the solution that I found is to use the publish command.
When I tried to publish the project, the generated exe is crashing on the first call to unmanged code. The generated exe has a bigger size than the one generated before publishing: seems like it embeds the C++/CLI .net5 wrapper.
 
Following my publish command:

`msbuild myprojectfile..csproj /t:publish /p:Configuration=Release /p:TargetFramework=net5.0-windows /p:SelfContained=False /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=True`

So here are my questions:
1- Is it possible in my case to avoid having these files (dll with the same name as my exe and json file) on the same location to get my exe works?
2- If yes, using the publish command, is it the right way to do that? Did I use it correctly?
3- Is there another better way to do it?

**Comment by hichem001** [comment]
hello @marcpopMSFT,
This issue is open for 17 days without any comment or reaction. Publishing .net5 app having C++/CLI net5 managed wrapper to C++ dll, is that supported or not? If yes, how to do it the right way? because I'm still having the crash on the first call to unmanaged code.

**Comment by marcpopMSFT** [comment]
Sorry about that. I was on vacation and we don't have a process for assigning out triage while I'm away.  Will can provide feedback here.

**Comment by wli3** [comment]
Sorry for the delay. PublishSingleFile is not supported for C++/CLI
