### ISSUE TITLE
File.cs.cshtml cannot become EmbeddedResource

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#2024]
_From @abpiskunov on March 2, 2018 6:17_

1. Create a new core Web app
2. in File Explorer find some cshtml page (Error.cshtml and rename it to Error.cs.cshtml.
3. In VS change type of Error.cs.cshtml to EmbeddedResource (notice it will be removed from Content in csproj)
4. Build
5. Open assembly manifest and see - no embedded resources
6. When rename file to Error.cshtml , build, assembly manifest does contain EmbeddedResource.

See this issue opened by customer originally : https://github.com/aspnet/Tooling/issues/1066#issuecomment-369131680 

_Copied from original issue: dotnet/project-system#3336_

**Comment by davkean** [comment]
This would be a build issue, no?

**Comment by davkean** [comment]
_From @nguerrera on March 2, 2018 20:38_

Could be sdk or msbuild. Feel free to move to sdk for next look.

**Comment by davkean** [comment]
_From @dsplaisted on March 2, 2018 20:40_

I want to take a look at this, but I suspect it is CPS not understanding how to modify the project to change the item type given the default globs that the project has.

**Comment by davkean** [comment]
_From @abpiskunov on March 2, 2018 21:56_

we have a vs feedback bug associated with that 574198. Who should i assign to? Who is doing first investigation here?

**Comment by davkean** [comment]
_From @abpiskunov on March 5, 2018 20:7_

Ok i am assigning the bug to Daniel first. Please route it further if it is not yours.

**Comment by dsplaisted** [comment]
This issue was moved to Microsoft/msbuild#3064
