### ISSUE TITLE
"dotnet test --blame-crash" swallows first test assembly

### ISSUE THREAD

**Issue by pjc50** [dotnet/sdk#20241]
The documentation at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test claims it takes no arguments, but in fact it discards the first test assembly.

This doesn't happen if you use it with a solution, but we're specifying test assemblies because that's considerably faster; the real use case has a much longer command line and it took me a while to realise why some of my tests were missing.

> C:\Users\pclay\foo>dotnet test --blame-crash UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> No test source files were specified.
> 
> C:\Users\pclay\foo>dotnet test --blame-crash dummyarg UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.

This also doesn't happen if any other valid argument is present after --blame-crash:

> C:\Users\pclay\foo>dotnet test --blame-crash --logger:nunit;LogFilePath=nunit-result.xml UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.

Version:

C:\Users\pclay\foo>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

**Comment by nohwnd** [comment]
This is a bug in the argument parser that assumes that the parameter has an argument, so it consumes it, and it is lost from the argument array: https://github.com/dotnet/sdk/blob/29cce14411cdde13c0023bb05447da5819f45e7e/src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs#L61

**Comment by Evangelink** [comment]
Working on the fix, I have noticed that the behavior is similar for all blame arguments and also for the `--nologo` (e.g. `dotnet test --nologo .\bin\Debug\netcoreapp3.1\MyProject.Tests.dll` fails with `The argument --nologo:.\bin\Debug\netcoreapp3.1\MyProject.Tests.dll is invalid. Please use the /help option to check the list of valid arguments.`).
