### ISSUE TITLE
Add dependency on Microsoft.Deployment.DotNet.Releases and add darc subscirption

### ISSUE THREAD

**Issue by lbussell** [dotnet/sdk#20262]
The .NET SDK depends on Microsoft.Deployment.DotNet.Releases (from https://github.com/dotnet/deployment-tools), but it isn't listed in `eng/Version.Details.xml`.

A [darc subscription](https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#updating-dependencies-in-your-local-repository) also needs to be added so that this repo's dependency on deployment-tools can be automatically updated.

**Comment by MichaelSimons** [comment]
This is blocked on https://github.com/dotnet/sdk/issues/20262.

**Comment by marcpopMSFT** [comment]
I believe this is flowing now.
