### ISSUE TITLE
Improve command-line help for `dotnet workload uninstall`

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20284]
The help for `dotnet workload uninstall` currently includes the following:

```
Description:
  Uninstall one or more workloads.

Usage:
  dotnet [options] workload uninstall [<WORKLOAD_ID>...]

Arguments:
  <WORKLOAD_ID>  The NuGet package ID of the workload to install.
```

We should not describe the `WORKLOAD_ID` argument as a NuGet package ID.  I'd suggest something like this:

> The ID of the workload to install.  You can list available workload IDs by running `dotnet workload search`

**Comment by sfoslund** [comment]
@dsplaisted looks like this was already fixed, you must have been using an old version: https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-workload/uninstall/LocalizableStrings.resx#L124
