### ISSUE TITLE
`--no-cache` option to `dotnet workload install` doesn't seem to ignore all caches

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20286]
I was bug bashing on workload installation, and installed and uninstalled the wasm-tools workload.  I wanted to test installing a workload from a cache folder created with `--download-to-cache`.  However, I wanted to make sure that it was only getting the installers from the cache I created and not from NuGet feeds or other locations that it had previously saved the nupkgs or MSIs.  So I created a NuGet.config that cleared all package sources, and ran `dotnet workload install wasm-tools --configfile nuget.config --skip-manifest-update --no-cache`, to verify that it would fail.

However, that command successfully installed the workload, so it must have been getting the packs from somewhere they had been saved previously.  I was expecting that the `--no-cache` parameter would prevent this.

**Comment by marcpopMSFT** [comment]
This feature is hidden now. We'll reopen if we bring it back.
