### ISSUE TITLE
Improve command-line help for `dotnet workload install` `--download-to-cache`

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20283]
From the `dotnet workload install` help:

```
--download-to-cache <download-to-cache>  Download packages needed to install a workload to a folder that can be used for offline installation.
```

The parameter value should be displayed as `<cache-folder>` or similar instead of `<download-to-cache>`.

`--from-cache` should similarly be updated.

**Comment by sfoslund** [comment]
Fixed by #20387
