### ISSUE TITLE
Workload garbage collection failure when installing maui workload a second time (MSI based install)

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20309]
When installing the maui workload (with an MSI-based SDK install), I got the following warning at the end:

> Warning: Workload garbage collection failed with error: 'Microsoft.iOS.Ref' is not a valid version string. (Parameter 'value').

I did a lot of installation and uninstallation while bug bashing, so I don't have exact repro steps.  But I think what I did included the following:

- `dotnet workload install maui --skip-manifest-update`
- `dotnet workload uninstall maui`
- `dotnet workload install maui` - This failed due to a missing package, because I forgot to specify `--skip-manifest-update`
- `dotnet workload install maui --skip-manifest-update`

Attached are the logs.

[workloadlogs.zip](https://github.com/dotnet/sdk/files/7072071/workloadlogs.zip)

**Comment by dsplaisted** [comment]
Running `dotnet workload repair` gave me this (after repairing the MSI packages):

> Warning: Workload garbage collection failed with error: 'Microsoft.iOS.Ref' is not a valid version string. (Parameter 'value').
>
> Successfully repaired workloads: maui
>
> Unhandled exception. System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WaitForPipeDrain()
   at Microsoft.DotNet.Installer.Windows.InstallMessageDispatcher.Send(InstallRequestMessage message)
   at Microsoft.DotNet.Installer.Windows.InstallMessageDispatcher.SendShutdownRequest()
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.Shutdown()
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.OnProcessExit(Object sender, EventArgs e)
   at System.AppContext.OnProcessExit()

**Comment by joeloff** [comment]
This is likely related to https://github.com/dotnet/sdk/pull/20248. There's a corresponding change in Arcade, so until we have packs built with that, pulling the workload records is likely going to be the cause of the version warning

**Comment by marcpopMSFT** [comment]
We believe this is fixed.
