### ISSUE TITLE
Downloading workload packs to cache should support specifying a different RuntimeIdentifier

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20307]
Using `dotnet workload install --download-to-cache` can be used to create a folder that can be used to install a workload on a computer without access to the feeds with workload packages.  It should be possible to do this for computers that do not match the current computer's OS and processor architecture.  So we should add the ability to specify a RuntimeIdentifier for the target system when downloading workload packs to a cache.

**Comment by marcpopMSFT** [comment]
This feature is hidden now. We'll reopen if we bring it back.
