### ISSUE TITLE
Downloading workload packs to cache folder should not re-download packages which are already in that folder

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20308]
When creating a cached workload pack folder with `dotnet workload install --download-to-cache`, you may want to add packs for a new workload (or a [new RuntimeIdentifier](https://github.com/dotnet/sdk/issues/20307)) to an existing cache folder.  Currently it appears that all required packages are downloaded even if they are already in the cache folder.  We should skip the unnecessary downloads if the packs are already in the cache folder.

**Comment by marcpopMSFT** [comment]
This feature is hidden now. We'll reopen if we bring it back.
