### ISSUE TITLE
Reenable TestPreviewFeatures test

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#20325]
TestPreviewFeatures disabled in https://github.com/dotnet/sdk/pull/20212 due to TFM update, the test needs to be updated to account for net7.0.

**Comment by sfoslund** [comment]
@pgovind assigning you as you added the test originally.

**Comment by pgovind** [comment]
I don't fully understand the sdk changes in #20212. The `TestPreviewFeatures` unit test runs a `dotnet new console` command to create a test project and parses the resulting .csproj to get the latest TFM. It seems like the changes in #20212 are still returning `net6.0` for the latest TFM. 

1. Is this the expected behavior? Or should I be seeing net7.0 for the TFM?
2. I'm assuming this is because Roslyn has not been updated yet? If that's the case, is there a better way to write this unit test? I assumed that Roslyn would be updated first, followed by the sdk, so the LangVersion checks in the unit test would always pass. My assumption seems to be wrong.

@dsplaisted @wli3

**Comment by sfoslund** [comment]
Our main branch is still in flux right now so it's definitely possible that we've missed a place where we need to update to net7.0. For question 1, yes, we expect the TFM to be net7.0 now, we'll have to investigate if that isn't the case.

**Comment by dsplaisted** [comment]
`dotnet new console` is based on the project templates, which will update to .NET 7.0 some time after we get targeting .NET 7 to work.  So tests that use them will eventually switch to .NET 7, but it won't be immediately when we retarget the branch to support .NET 7.

**Comment by sfoslund** [comment]
@dsplaisted this test uses the WithTargetFramework method to set the tfm to what it calculates to be the latest value. I'm wondering if it's picking up net6.0 from here: https://github.com/dotnet/sdk/blob/deebf2f4af88d4e6b84a3daa9ebe55de5eb18b52/Directory.Build.props#L11, looking into this now...

**Comment by dsplaisted** [comment]
It calculates the latest TargetFramework value by running `dotnet new console`, so it's dependent on the template being updated:

https://github.com/dotnet/sdk/blob/6f97e734f8b057cbc14f3be69ac6dd714428f408/src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs#L375-L397

**Comment by sfoslund** [comment]
Ahh okay, makes sense

**Comment by pgovind** [comment]
> So tests that use them will eventually switch to .NET 7, but it won't be immediately when we retarget the branch to support .NET 7.

So what do you suggest we do here? We could just wait for a few weeks till everything starts targeting .NET 7 to re-enable the test, but we would need to do this exercise every release :/

**Comment by dsplaisted** [comment]
It sounds like the test is still targeting .NET 6.0.  In that case why is it failing?

If we have to wait for Roslyn targets to be updated, then I think we might need to deal with this manually each release, unless Roslyn targets update before the project template does.

**Comment by pgovind** [comment]
> It sounds like the test is still targeting .NET 6.0. In that case why is it failing?

This line in the test fails:
```csharp
                if (targetFramework == LatestTargetFramework)
                {
                    Assert.Equal("Preview", langVersion); // This assert fails
                    Assert.True(contains);
                }
```

If the TFM was net7.0, I'd expect the LangVersion to be "Preview" and the assert to pass. Instead, until Roslyn gets updated, I think we will see a TFM of net6.0 and LangVersion 10.0.
