### ISSUE TITLE
Build issues hundreds of spam messages about "You are working with a preview version of the .NET Core SDK."

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2032]
**Repro**

clone https://github.com/aspnet/Mvc
Install latest CLI (2.1.300-preview2-008322)
dotnet build Mvc.sln

**Result**

🤢 

![image](https://user-images.githubusercontent.com/2696087/37227919-a72d42a2-2393-11e8-8bf0-e83799995ab9.png)

@livarcocc @nguerrera

**Comment by natemcmaster** [comment]
Can we safely assume that if there is a "global.json" version, that we already know we are using a preview version of the SDK?

**Comment by nguerrera** [comment]
This is down to 1 message per msbuild node but change hasn't flowed from dotnet/sdk yet

**Comment by nguerrera** [comment]
Mostly duplicate of dotnet/sdk#2018.

Taking global.json into account is interesting but not trivial in current architecture.

**Comment by natemcmaster** [comment]
Ok, let's close as dupe of dotnet/sdk#2018 since it seems you've already fixed the hundreds of warning issue. I'll open a separate one for skipping the message altogether when it's not really helpful.

**Comment by natemcmaster** [comment]
https://github.com/dotnet/sdk/issues/2033
