### ISSUE TITLE
Hide `--sdk-version` parameter to workload commands

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20357]
The `--sdk-version` parameter to workload commands is intended for VS for Mac to use in order to download workloads before a new version of the .NET SDK is installed.

It isn't intended to be used from the command line, and it doesn't work for MSI-based installs.  So we should hide it from the list of options displayed in help.

@tdykstra We should also remove this from the documentation

**Comment by sfoslund** [comment]
Fixed by #20387
