### ISSUE TITLE
S.R.TypeExtensions not deployed for net461 application

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#2035]
Have a situation where System.Reflection.TypeExtensions is not being deployed. Here is the project setup that we have:

- CSharpCompilerTestUtilites: targets netstandard1.3 and uses System.Reflection.TypeExtensions
- CSharpCompilerEmitTests: targets net461 + netcoreapp2.0, references CSharpCompilerTestUtilities

The net461 output of CSharpCompilerEmitTests does not contain System.Reflection.TypeExtensions. That is necessary to run and hence some of our unit tests fail. 

To repro:

- Clone https://github.com/jaredpar/roslyn
- Switch to branch repro/deploy-type-extensions
- `powershell build/scripts/build.ps1 -build -restore` 
- Check the contents of `Binaries\Debug\UnitTests\CSharpCompilerEmitTests\net461` 

Note: In our build `DisableImplicitFrameworkReferences` is `false` by default and we have a tendancy to use explicit package references (hold over from the project.json days). It's possible this is contributing here but I'm unable to track this down.

**Comment by nguerrera** [comment]
@jaredpar, this fell off my radar. Are you still seeing this? Did you workaround it?

**Comment by nguerrera** [comment]
Looking now.

**Comment by nguerrera** [comment]
I see the linked commit with the direct ref workaround now.

**Comment by nguerrera** [comment]
OK, here's what's happening:

* There are 2 levels of indirection from CSharpCompilerEmitTest to the PackageReference to S.R.TypeExtensions:

1. [CSharpCompilerEmitTest (net46;netcoreapp2.0) -> CSharpCompilerTestUtilities (netstandard1.3)](https://github.com/jaredpar/roslyn/blob/6130e78f19d83a3987b721e6bd646b9ea8e2068d/src/Compilers/CSharp/Test/Emit/CSharpCompilerEmitTest.csproj#L21)
2. [CSharpCompilerTestUtilities (netstandard1.3) -> TestUtilities (netstandard1.3;net46;netcoreapp2.0)](https://github.com/jaredpar/roslyn/blob/6130e78f19d83a3987b721e6bd646b9ea8e2068d/src/Compilers/Test/Utilities/CSharp/CSharpCompilerTestUtilities.csproj#L21)

* The package reference to S.R.TypeExtensions (two levels away) is [conditioned on TargFramework=netstandard1.3](https://github.com/jaredpar/roslyn/blob/6130e78f19d83a3987b721e6bd646b9ea8e2068d/src/Test/Utilities/Portable/TestUtilities.csproj#L103-L104)

This condition effectively flows through the P2P graph as packages flow transitively. So CSharpCompilerEmitTest (net46) gets TestUtilities (net46) package references, and not TestUtilities (netstandard1.3) package references.

It's confusing in this edge case, but the system is behaving as designed and I think it is the right design. As I try to think about how to specify different behavior that would make this case work, my brain is exploding and I think we'd only end up making things more complicated.

IMHO, the best fix on your side would be to remove that condition from from the package reference. I don't see why it's necessary and it is what is preventing the indirect net46 consumers from getting the package reference to flow as needed.

**Comment by jaredpar** [comment]
@nguerrera in your explanation you list CSHarpCompilerEmit as net46 when it is actually net461. Does that impact your analysis?

**Comment by nguerrera** [comment]
It does not.

**Comment by nguerrera** [comment]
I've edited my analysis. I misread $(RoslynPortableTargetFrameworks)

**Comment by nguerrera** [comment]
The intermediate project tripped me up too. It's very confusing.

**Comment by jaredpar** [comment]
Thanks for the explanation!
