### ISSUE TITLE
Consider update the Microsoft.TestPlatform bundled in sdk?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#2036]
## Steps to reproduce
`dotnet test`

## Expected  behavior
The version of vstest include in dotnet sdk should follow an more recent version in it's channel when released(preview or stable)

## Actual behavior
The verion of dotnet sdk include MSBuild `15.7` and NuGet `15.7` but
`Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01`
While there is 3 preview and 2 stable version after that.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008321
 Commit:    4c2b07023a
...
```

**Comment by livarcocc** [comment]
The insertions happen while the development cycle progresses. The VS Test team hasn't inserted for 15.7 yet, therefore there has not been matching insertions into the CLI.

Thanks for pointing it out though.
