### ISSUE TITLE
Global tool installation should not use local NuGet.config

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/sdk#20396]
We are building a [global tool](https://github.com/dotnet/upgrade-assistant) that people often get error messages like the following:

```
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\NuGet.targets(131,5): error : Fehler beim Abrufen von Informationen zu "upgrade-assistant" aus der Remotequelle "....". [C:\Users\kugle\AppData\Local\Temp\vwazqmm3.4yh\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\NuGet.targets(131,5): error : Response status code does not indicate success: 401 (Unauthorized). [C:\Users\kugle\AppData\Local\Temp\vwazqmm3.4yh\restore.csproj]
```

Often, this seems to be because the local directory's NuGet.config is being used. Since this is a global tool installation, it seems like it should not be looking at the local directory. Issues like updates wouldn't work well later on if done from a different directory.

Is this expected behavior? Would it be better to skip any local NuGet.config during a global tool install (still honoring of course for local tools installation)?

**Comment by marcpopMSFT** [comment]
Old bug triage: dotnet defers to nuget and then nuget uses the nuget.config from your current working directory and working up. There is not different behavior for local tool installs.
