### ISSUE TITLE
dotnet pack fails when PackAsTool is true and project has ProjectReference's

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2047]
**Repro**
Create a console app project with a ProjectReference to a class library.
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClassLib1\ClassLib1.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackAsTool>true</PackAsTool>
  </PropertyGroup>

</Project>
```
`dotnet pack`

**Expected**
Creates a tool package with  ClassLib1.dll bundled inside

**Actual**
dotnet pack fails with this error
```
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error : Could not find a part of the path 'C:\Users\nmcmaster\AppData\Local\Temp\ClassLib1\bin\Debug\netcoreapp2.1\publish'. [C:\Users\nmcmaster\AppData\Local\Temp\test2\test2.csproj]
```

cc @wli3 @peterhuene @KathleenDollard

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/2007

**Comment by natemcmaster** [comment]
@wli3 do you know which version of the CLI first contained this fix? @bricelam reported running into this recently, but we are using a very recent build of the CLI.

**Comment by wli3** [comment]
Unfortunately the change has not been flowed to CLI. I'll create a PR for it. And let you know when there is a good build

**Comment by natemcmaster** [comment]
Thanks.

**Comment by wli3** [comment]
@natemcmaster 2.1.300-preview2-008367 above (the latest master) has that change. https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by natemcmaster** [comment]
Thanks. @bricelam the latest KoreBuild should have this SDK now
