### ISSUE TITLE
Localization of "description" field of manifest file

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#20497]
Short term:

- [x] Come up with a manifest format to put localization
- [x] Make manifest reader being able to read them and display it according to the language https://github.com/dotnet/sdk/issues/20922
- [x] Do one off translation and hard code the translation (send to translator pending translation)

Long term:

- [ ] Edit xlf task to make loc system back end being able to convert and consume loc result
- [ ] Work with workload author teams to set up loc process, especially teams that don't use Arcade

**Comment by sfoslund** [comment]
Updated tags and milestones since 6.0.1xx work is finished, this issue can not be used to track the long term items above

**Comment by marcpopMSFT** [comment]
I've confirmed that this works for the CLI. We don't expect customers to be working directly with workloads in VS. @Redth if ya'll want to localize your description, you can do so like wasm-tools did: https://github.com/dotnet/runtime/tree/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/localize
