### ISSUE TITLE
After upgrade from net6 preview 7 to rc1, build project which is created with net6 preview 7 with error "C:\Users\v-danche\RC1\before\myconsole\Program.cs(2,1): error CS0103: The name 'Console' does not exist in the current context [C:\Users\v-danche\RC1\before\myconsole\myconsole.csproj]"

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#20509]
Environment:
Windows10
Repro steps
1.Install net6 preview 7 SDK(https://dotnet.microsoft.com/download/dotnet/6.0).
2. Run dotnet new console -o myconsole to create console app.
3. Install the latest net6 rc1--6.0.100-rc.1.21430.44(runtime-6.0.0-rc.1.21430.11) to upgrade.
   dotnet build "myconsole" project
We got below error
![image](https://user-images.githubusercontent.com/65637796/131770313-043cb29e-0a45-4cc1-8db3-38f0729679a4.png)

Note: we can build successfully with below workarounds.
**Workaround1**
Add  `<ImplicitUsings>enable</ImplicitUsings>` to myconsole.csproj file
![image](https://user-images.githubusercontent.com/65637796/131770481-5e4ee154-c1d8-4828-9b72-e98530385ef2.png)

or
**Workaround2**
Use the old template in program.cs
![image](https://user-images.githubusercontent.com/65637796/131770722-480ca477-9a33-486d-a1ae-085d475237c9.png)

**Comment by KalleOlaviNiemitalo** [comment]
I think this is by design because implicit usings were disabled by default per <https://github.com/dotnet/sdk/issues/19521>, after having been enabled by default in 6.0 preview 7 only. If you were upgrading from 5.0.\* or 6.0 preview 6, the problem would not occur.

**Comment by vdanche** [comment]
close it by design
