### ISSUE TITLE
Protect strong name key changes in ApiCompat / package validation

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#20593]
For System.Composition* packages we accidentally changed the strong name key in 5.0 and just reverted that: https://github.com/dotnet/runtime/pull/45756. We should add validation to prevent such mistakes in the future.

**Comment by ericstj** [comment]
I believe this is already handled by the new APICompat: https://github.com/dotnet/sdk/blob/cf2fd1e514c393cb12e745ab488b6478320fc232/src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs#L13
