### ISSUE TITLE
Hide `--download-to-cache` and `--from-cache` parameters for workload install and update

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#20642]
The `--download-to-cache` and `--from-cache` parameters to `dotnet workload install` and `dotnet workload update` are currently mainly for consumption by the VS for Mac installer.  They currently don't work too well for manual usage (see #20285, #20307 and #20308).

Until we can improve the experience, we should hide these parameters.

**Comment by sfoslund** [comment]
Fixed by #20646
