### ISSUE TITLE
Workload installation creates inaccessible folders when running as standard user

### ISSUE THREAD

**Issue by reflectronic** [dotnet/sdk#20691]
1. Create a Windows user account as standard user.
2. In that user account, run `dotnet workload install maui` from an elevated command prompt.
3. Run `dotnet new`.

Output:
```
The 'dotnet new' command creates a .NET project based on a template.

Common templates are:
Access to the path 'C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.ios\WorkloadManifest.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in System.Private.CoreLib.dll:token 0x6000126+0xa1
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6000125+0x6
...
```

In this instance, `C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.ios\` is not accessible to the standard user account. This causes all sorts of problems, the least of which is `dotnet new` not working. For example, trying to build a .NET MAUI project from Visual Studio results in the build failing with another permissions-related error:
```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk\6.0.0-preview.7.21377.19\Sdk\Sdk.props' is denied.
``` 
Again, in this instance, `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk\6.0.0-preview.7.21377.19\` is not accessible to the standard user account.

---

The account on my machine that I use to do everyday things is a standard user account. This makes it quite frustrating to do anything with workloads, as I have to go through and edit the permissions on each one of these directories to allow myself access. I would appreciate if the workload installer could set the ACLs on these folders to allow Read and Execute access for all users.

**Comment by marcpopMSFT** [comment]
In RC1, we're switching to elevating (with UAC) and installing workloads via msi so that should correctly handle the ACLs for these folders going forward.
