### ISSUE TITLE
[dotnet-sdk-6.0.100-rc.2.21456.8]The output content is empty when starting the global tool application dotnet-format

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/sdk#20694]
**Application Name**: dotnet-format (global tool app)
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: 6.0.100-rc.2.21454.3

**Verify Scenarios:**
1). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21456.8: Fail
2). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21454.3: Fail
3). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.1.21451.16: Pass

**Repro steps:**
1) Install app with this command : dotnet tool install -g dotnet-format
2) On CMD, go to any project directory that has .sln or csproj file
3) Run this command : dotnet format

**Expected Result:**
It should format the files and show the result message.

Formatting code files in workspace 'C:\AppCompat\applications\DotNETCoreConsole\DotNETCoreConsole\DotNETCoreConsole.csproj'.
  Format complete in 16864ms.

**Actual Result:**
No result message.

**Findings :**
"dotnet-format" command works as expected, "dotnet format" worked on previous SDKs, in this SDK, there is difference.

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Is there any update for this bug?

**Comment by Junjun-zhao** [comment]
@joeloff  Do you have any update for this bug? We are in validation window of RC2, could you please confirm whether it is a blocker for RC2?

**Comment by joeloff** [comment]
If the output is missing, but the command still does what's expected I don't think this should block the release.

**Comment by Junjun-zhao** [comment]
@joeloff Do you have any update for this bug?  We still repro this issue in the latest .NET 7 build.

**Comment by Junjun-zhao** [comment]
@joeloff  Is there any update for this bug? we still repro this with build dotnet-sdk-7.0.100-preview.3.22179.4

**Comment by Junjun-zhao** [comment]
@ joeloff This is a bug reproduced from .NET 6.0. Now it still reproduces on the latest 6.0, 7.0 servicing releases and 8.0 release. 
It was still labeled as "untriaged".  Do you have any update for issue? Will it be considering fixing it in the plan or won't fix?

**Comment by marcpopMSFT** [comment]
Dotnet format is included with the SDK now and so doesn't have to be installed separately. Does running it directly after SDK install work? CC @sharwell @arkalyanms as the owners of dotnet-format as this would be a question for them.

**Comment by Junjun-zhao** [comment]
> Dotnet format is included with the SDK now and so doesn't have to be installed separately. Does running it directly after SDK install work? 

Before 6.0 RC2, dotnet format was a separate global tool package. We need to install it through "dotnet tool install -g dotnet-format". The "dotnet format" command performs the expected operations and has output. After 6.0 RC2, "dotnet format" is integrated into the SDK, the "dotnet format" command performs the expected operation but no output. Please help confirm whether it is expected.

![image](https://github.com/dotnet/sdk/assets/83067197/4651689f-58d3-419b-9d1d-1015426c807e)

**Comment by marcpopMSFT** [comment]
Whether format should include an output is a question for the owners in @sharwell and @arkalyanms

**Comment by Junjun-zhao** [comment]
@sharwell @arkalyanms  Could you please check this issue and let us know if this is expected? Thanks

> Whether dotnet format should include an output?
Before 6.0 RC2, dotnet format was a separate global tool package. We need to install it through "dotnet tool install -g dotnet-format". The "dotnet format" command performs the expected operations and has output. After 6.0 RC2, "dotnet format" is integrated into the SDK, the "dotnet format" command performs the expected operation but no output.

**Comment by Junjun-zhao** [comment]
No response from dotnet-format area owners despite several pings and haven’t seen any customer reports regarding this even though this issue was first found in the AppCompat lab with .NET 6 in 2021. Hence closing this issue.
