### ISSUE TITLE
NET6_0_OR_GREATER not defined in net6.0 project built with VS2019

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#20700]
After dotnet/sdk#19562, when building a .NET 6 project from Visual Studio/MSBuild 16.11, the `NET6_0_OR_GREATER` symbol is not defined at compile time.

This is happening because this condition evaluates to `false`:

https://github.com/dotnet/sdk/blob/91f97649c49f5c4db43be4092dc688356ee677c8/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props#L26-L27

That causes the constant-generator to skip it:

https://github.com/dotnet/sdk/blob/91f97649c49f5c4db43be4092dc688356ee677c8/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L210-L225

**Comment by mfkl** [comment]
Can repro with VS2022 17.0.2.

**Comment by marcpopMSFT** [comment]
Old bug triage: since this config isn't supported, I think we're ok with the defines not being set. You'll get the same behavior with each VS version right before a new .NET release.
