### ISSUE TITLE
ReadyToRun publishing fails in 6.0 due to NETSDK1095

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#20701]
When attempting to publish a .NET project with R2R, it fails with the following error: `/usr/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(293,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [/app/app.csproj]`

This is a regression from 5.0.

The conditions in which this occur require that a `dotnet restore` command be run before executing `dotnet publish` and executing publish w/o a restore.  This can be easily demonstrated in a Docker environment with the following example Dockerfile:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64 AS build
WORKDIR /app

RUN dotnet new console
RUN dotnet restore -r linux-x64
RUN dotnet publish -c release -o /out -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
```

If you were to remove the `--no-restore` option from the last line, the publish would succeed.

In comparison, this Dockerfile using 5.0 can be built successfully:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-amd64 AS build
WORKDIR /app

RUN dotnet new console
RUN dotnet restore -r linux-x64
RUN dotnet publish -c release -o /out -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
```

It is essentially the same as the 6.0 Dockerfile but instead uses the 5.0 SDK.

The issue is also not limited to Linux. It can be reproduced in Windows environments as this Dockerfile demonstrates:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-20H2 AS build
WORKDIR /app

RUN dotnet new console
RUN dotnet restore -r win-x64
RUN dotnet publish -c release -o /out -r win-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
```

Attempting to build this Dockerfile will produce the same error: `C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(293,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [C:\app\app.csproj]`

**Comment by mthalman** [comment]
cc @marcpopMSFT

**Comment by mthalman** [comment]
cc @dsplaisted

**Comment by dsplaisted** [comment]
This looks similar to #18999.  It looks like `PublishReadyToRun` doesn't work well when `dotnet restore` and then a build / publish with `--no-restore`.

@agocke

**Comment by agocke** [comment]
I don't think anything works properly if options change between restore/build/publish. As far as I know, there is no expectation that any operation will work if the options are changed between steps.

I think this is By Design.

**Comment by dsplaisted** [comment]
It looks like this broke in .NET 6 though, probably because now `PublishReadyToRun` changes which packages are downloaded, when it didn't before.

I don't know if running restore separately from build is a commonly needed scenario, or if people are just doing so because that was the pattern in .NET Core 1.0 before we added implicit restore.

In either case, people seem to be hitting this so I think we need to document it as a breaking change.

**Comment by mthalman** [comment]
> I don't know if running restore separately from build is a commonly needed scenario, or if people are just doing so because that was the pattern in .NET Core 1.0 before we added implicit restore.

It's very common in Docker build scenarios because it takes advantages of Docker's layer caching feature.  By running a separate restore command, that image layer can be cached.  So as long as you don't modify the files that were copied in prior to that command, typically the csproj files and any NuGet-related config, then you don't have to execute the restore again when you make actual code changes.  This is the pattern that is used in the generated Dockerfiles from VS, for example, and also the pattern we demonstrate in our official sample Dockerfiles ([example](https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile)).

**Comment by agocke** [comment]
@mangod9 For R2R changes here -- I'm not familiar if the packaging requirements changed.

**Comment by mangod9** [comment]
since cg2 is now a separate package `PublishReadyToRun` needs to be passed to restore:

`RUN dotnet restore -r linux-x64 /p:PublishReadyToRun=true`

**Comment by mthalman** [comment]
Thanks.  I have confirmed that setting PublishReadyToRun on the restore command does resolve the issue.  I agree with @dsplaisted that this should be documented as a breaking change.

**Comment by AntonLapounov** [comment]
In the described scenario `_crossgen2Tool.PackagePath` is an empty string and not `null`, so the check below passes:
https://github.com/dotnet/sdk/blob/347c64c2cd5853c48efabf3fcc109bf6819e0d50/src%2FTasks%2FMicrosoft.NET.Build.Tasks%2FResolveReadyToRunCompilers.cs#L136-L140

I think we should use `string.IsNullOrEmpty(_crossgen2Tool.PackagePath)` instead and update the `NETSDK1094` error message to cover the `--no-restore` scenario.

**Comment by AntonLapounov** [comment]
We have improved the error message with words "When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true."

**Comment by DRAirey1** [comment]
Your updated error message is useless. How, exactly, so we set this flag to true? I tried setting in the publishing profiles, I tried setting in the .waproj. Nothing seems to work.

**Comment by baronfel** [comment]
You can set MSBuild properties in a number of ways:

* directly on the command line command: `-p PublishReadyToRun=true`
* in the project file directly: `<PropertyGroup><PublishReadyToRun>true</PublishReadyToRun></PropertyGroup>`
* in a file that is looked up by MSBuild by convention, like [Directory.Build.props](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022#directorybuildprops-and-directorybuildtargets)

Any of those should work.
