### ISSUE TITLE
Known workloads show workloads which are not intended for public consumption

### ISSUE THREAD

**Issue by marek-safar** [dotnet/sdk#20709]
When workloads operation fails the error message is displayed which lists known workloads. It includes workloads that are "internal" and should probably not be included because they are blocked when used.

Here is the current list
```
Known workloads: tvos android android-aot maui maui-mobile maui-desktop maui-core maui-android maui-maccatalyst maui-ios maui-windows macos microsoft-net-sdk-emscripten maccatalyst ios wasm-tools microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos microsoft-net-runtime-mono-tooling
```

**Comment by marcpopMSFT** [comment]
@marek-safar can you include the full error and repro steps as we're curious how you got into the state of failing workloads? This is an unlocalized error as it's not expected to be hit (hence why we weren't cleaning up the list).

**Comment by marek-safar** [comment]
I got it from about 4 different workload commands. For example

```
sudo dotnet workload update

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maui.
Workload installation failed. Rolling back installed packs...
Workload update failed: Workload not found: microsoft-ios-sdk-full. Known workloads: tvos android android-aot maui maui-mobile maui-desktop maui-core maui-android maui-maccatalyst maui-ios maui-windows macos microsoft-net-sdk-emscripten maccatalyst ios wasm-tools microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos microsoft-net-runtime-mono-tooling
```

**Comment by sfoslund** [comment]
@marek-safar this error indicates that something is probably broken in your current installation. What version of the SDK do you have installed and did you have any other previews installed previously? What workloads do you have installed? What is the content of out sdk-manifests dir and your metadata dir?

**Comment by marek-safar** [comment]
After fresh .NET installation, I did `sudo dotnet workload update`.

I don't think the issue is primarily about my installation being broken. It's one example that leads to incorrect information given to users by showing workloads names that are not intended for public reference.

**Comment by sfoslund** [comment]
I can't repro this behavior with a fresh install, and the error message you posted above indicates that the installation is not fresh (`Workload not found: microsoft-ios-sdk-full.` means that there's a workload record for that workload on the machine). In fact, that seems to be the old workload id from prev 4/5, which has changed in more recent previews. As a result, unless we can repro this with the newer versions, I think it's a cross-preview compatibility bug. 

> I don't think the issue is primarily about my installation being broken. It's one example that leads to incorrect information given to users by showing workloads names that are not intended for public reference.

This error is meant to be internal and we don't expect there to be a situation in the wild where it shows up, hence why it's showing internal workload ids and it's not localized. Obviously some of our expectations were broken in this case and the error was shown to the user, but since it seems to be a cross-preview compatibility issue I don't think it's a problem.

**Comment by sfoslund** [comment]
@marek-safar I'm going to go ahead and close this, since it seems to be a cross-preview conflict which we won't see in real releases. If you're able to repro with a clean install, feel free to reopen, thanks!
