### ISSUE TITLE
Implicitly define compilation constants for target framework without a specific version

### ISSUE THREAD

**Issue by david-driscoll** [dotnet/sdk#2072]
I was talking to @dsplaisted (iirc) and someone else at summit and this was one scenario that I felt was missing from the current SDK.

It may make sense to also have a general compilation constant that is just the Target Framework Identifier without the version.  Of course this won't work for all cases of the compilation constants (ie, missing API's between versions) but there are places where .NET Desktop differs greatly from .NET Core, and being able to codify that across versions would be helpful.

When multi-targeting, you times have to make code that targets a specific framework (or standard). If you shift your target forward or backward, and go from say `<TargetFrameworks>netstandard1.3;net45</TargetFrameworks>` to `<TargetFrameworks>netstandard2.0;net471</TargetFrameworks>` any of your pre-existing conditional compilation bits will have to be updated from `NETSTANDARD1_3`/`NET45` to ``NETSTANDARD2_0/`NET471`.

so...
* `NETSTANDARD1_0`, `NETSTANDARD1_3`, `NETSTANDARD2_0`, `...` -> `NETSTANDARD`
* `NET45`, `NET461`, `NET471`, `...` -> `NETFRAMEWORK`
* `NETCOREAPP1_0`, `NETCOREAPP2_0` -> `NETCOREAPP`

**Comment by dsplaisted** [comment]
@david-driscoll Are you planning on submitting a PR for this? 😀

**Comment by david-driscoll** [comment]
@dsplaisted jsut did. 🎉 🎈 🎉

**Comment by david-driscoll** [comment]
In fact going through the unit tests this would also affect other frameworks like adding a `XAMARINIOS`, `XAMARINANDROID` and more.

cc @onovotny this might have a positive (or negative? 🤷‍♂️) effect on https://github.com/onovotny/MSBuildSdkExtras

**Comment by onovotny** [comment]
Today the extras builds on what the SDK does....so if the SDK adds this, it just adds more things to the projects. It also includes the native targets, so on android, it includes the symbols like `__ANDROID__` that Xamarin has had for years.

I don't think this has any negative effect on the extras, just adds more define options.
