### ISSUE TITLE
dotnet publish PublishProfile does not work

### ISSUE THREAD

**Issue by mrlife** [dotnet/sdk#20798]
This is the command I run in the project directory:

```
dotnet publish -p:PublishProfile=publish-profile
```

The `publish-profile.pubxml` was created by VS for Mac and is in `Properties/PublishProfiles`

Here is the .pubxml:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <EnvironmentName>Staging</EnvironmentName>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>AnyCPU</LastUsedPlatform>
    <publishUrl>/Volumes/remote-server-path-to-folder</publishUrl>
    <DeleteExistingFiles>true</DeleteExistingFiles>
    <TargetFramework>net5.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <_IsPortable>true</_IsPortable>
  </PropertyGroup>
</Project>
```

These are the .NET SDKs installed:

> 3.1.409 [/usr/local/share/dotnet/sdk]
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.6.21355.2 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

refs https://github.com/dotnet/sdk/issues/12870#issuecomment-915441183 https://github.com/dotnet/docs/issues/19961#issuecomment-915441951

**Comment by mrlife** [comment]
cc @adegeo @vijayrkn @fuglede

**Comment by vijayrkn** [comment]
Looks related to this issue - https://github.com/dotnet/aspnetcore/issues/35134#issuecomment-897237914

Can you try adding PublishDir also to the pubxml and see if it fixes the issue?

**Comment by mrlife** [comment]
@vijayrkn That works, thank you!
