### ISSUE TITLE
After upgrade from net6 rc1 to rc2, the setup failed.

### ISSUE THREAD

**Issue by haiyanliu2** [dotnet/sdk#20834]
Environment:Windows7
Repro steps
1.Install the latest net6 rc1 SDK--6.0.100-rc.1.21458.32
2. Install the latest net6 rc2--6.0.100-rc.2.21458.9(runtime-6.0.0-rc.2.21457.6) from https://github.com/dotnet/installer to upgrade.

Expected
the setup successful.

Actual
the setup failed.
![image](https://user-images.githubusercontent.com/87641893/132636497-5cfeddb6-1c41-45c8-b77c-2bc1912d24cc.png)
dotnet --info
.NET SDK (reflecting any global.json):
Version: 6.0.100-rc.1.21458.32
Commit: d7c22323c4
Runtime Environment:
OS Name: Windows
OS Version: 6.1.7601
OS Platform: Windows
RID: win7-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\
Host (useful for support):
Version: 6.0.0-rc.1.21451.13
Commit: d7619cd4b1
.NET SDKs installed:
6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\M
icrosoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Micr
osoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\share
d\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
@haiyanliu2 can you open the log file (either from the link in the installer or finding the right log in your %temp% folder) and determine what product it says is already installed.

CC @joeloff

**Comment by joeloff** [comment]
That looks like the bundle itself that's not upgrading properly since we don't upgrade the installers.

The versions are a bit close. It could be that it's not differentiating on the RC1/RC2 values when generating the bundles upgrade GUID.

**Comment by joeloff** [comment]
Oh I see what's going on here. The RC2 build is older than the RC1. For installers, semver has no meaning because those cannot be converted to a 32-bit number. You have 21458.32 (RC1) which is newer than 21458.9 (RC2). The build numbers will be converted to 4 part (major.minor.build.revision) versions and that's where the problem comes in. You need at least 21458.33 (RC2) or higher build to upgrade

**Comment by vdanche** [comment]
Upgrade from the latest net6 rc1 SDK--6.0.100-rc.1.21458.32 to 6.0.100-rc.2.21459.15(runtime-6.0.0-rc.2.21457.6), succeed

**Comment by joeloff** [comment]
Great to hear!
