### ISSUE TITLE
After Install 6.0 RC1 on Mac OS, install wasm-tools workload via Terminal met an error "Workload installation failed".

### ISSUE THREAD

**Issue by lemon0213** [dotnet/sdk#20833]
**Azure DevOps work item:**
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1395599

**REPRO MACHINE**: MacOS Catalina (10.15)
**REPRO Configuration**: 

+ SDK 6.0 RC1

**.NET Core SDK:** 6.0.100-rc.1.21457.2 

**.NET Core Runtime:** 6.0.0-rc.1.21451.13

**INSTALL STEPS**

1. Install .NET 6.0 RC1 from [Pipelines - Run 20210907.1-6.0.100-rc.1.21457.2-107179,105318 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdev.azure.com%2fdnceng%2finternal%2f_build%2fresults?buildId%3D1346554%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=04%7c01%7cv-qushi%40microsoft.com%7c2ff456977df04cad832b08d9727d4d35%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637666704874836490%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=KOSpIL2o7ZCSYn31Kpc5%2Bhom3u2w640WcW8uEC%2fzuzY%3D&reserved=0)
2. Add feed to ~/.nuget/NuGet/NuGet.Config
Feed using: 
https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21457.2-shipping/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json
![image](https://user-images.githubusercontent.com/66412274/132633332-86ec5674-4704-48cb-a72a-0144a052acb6.png)

**REPRO STEPS**
After 6.0 RC1 install completed, install wasm-tools workload via Terminal using ` sudo dotnet workload install wasm-tools --skip-manifest-update `

**ACTUAL**
Install wasm-tools workload met an error "Workload installation failed: microsoft.net.runtime.webassembly.sdk::6.0.0-rc.1.21451.13 is not found in NuGet feeds https://api.nuget.org/v3/index.json"
![image](https://user-images.githubusercontent.com/66412274/132633202-2e777d81-71a2-4d68-9496-cd73b9572346.png)

**EXPECTED**
Wasm-tools workloads can successfully installed.

**Comment by Serena01** [comment]
This issue could reproduce on the linux with RC1, e.g. CentOS

**Comment by wli3** [comment]
I cannot repro on my machine. Could you try that again? Maybe feed is not update-to-date? Try adding --no-cache 

`sudo dotnet workload install wasm-tools --skip-manifest-update --no-cache -s https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21457.2-shipping/nuget/v3/index.json -s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json -s https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json`

![image](https://user-images.githubusercontent.com/6993335/132755727-588b00a0-3079-4e16-982f-83877acaa0e4.png)

**Comment by lemon0213** [comment]
Update INSTALL STEPS, add feed to ~/.nuget/NuGet/NuGet.Config we will meet this issue.

**Comment by lemon0213** [comment]
Using below command can install successfully. 
_sudo dotnet workload install wasm-tools --skip-manifest-update --no-cache -s https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.1.21457.2-shipping/nuget/v3/index.json -s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json -s https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json_

**Comment by wli3** [comment]
fixed in https://github.com/dotnet/sdk/pull/20930
