### ISSUE TITLE
windows arm64 dotnet SDK fails to publish self-contained

### ISSUE THREAD

**Issue by guide2wsl** [dotnet/sdk#20840]
### Describe the bug
The dotnet CLI on a Windows ARM64 machine cannot publish a self-contained application

### To Reproduce
On a Windows ARM64 device (e.g. Surface Pro X):
1. Download https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.7-windows-arm64-binaries
2. Create a new application:
```powershell
dotnet new console
```
3. Attempt to publish it:
```powershell
dotnet publish -r win-arm64 --self-contained /p:PublishSingleFile=true
# results in: error NU1100: Unable to resolve 'Microsoft.NETCore.App.Runtime.win-arm64 (= 6.0.0-preview.7.21377.19)' for 'net6.0'.
```

It's worth noting within WSL2, the Linux ARM64 dotnet 6 SDK Preview does not have this problem i.e. ARM64 Linux can successfully cross compile for the same target runtime, win-arm64, so this bug appears to be specifically for the Windows ARM64 version of the dotnet 6 SDK.  More details below:

### Exceptions (if any)
```
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Users\guide2wsl\Documents\Programming\first\first.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Runtime.win-arm64 (= 6.0.0-preview.7.21377.19)' for 'net6.0'.
C:\Users\guide2wsl\Documents\Programming\first\first.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Runtime.win-arm64 (= 6.0.0-preview.7.21378.9)' for 'net6.0'.
C:\Users\guide2wsl\Documents\Programming\first\first.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Runtime.win-arm64 (= 6.0.0-preview.7.21378.6)' for 'net6.0'.
  Failed to restore C:\Users\guide2wsl\Documents\Programming\first\first.csproj (in 167 ms).
```

### Further technical details
Edition	Windows 11 Home
Version	21H2
OS build	22000.176

```powershell
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Users\guide2wsl\Applications\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Users\guide2wsl\Applications\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Users\guide2wsl\Applications\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Users\guide2wsl\Applications\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Users\guide2wsl\Applications\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Please investigate, thanks!

**Comment by marcpopMSFT** [comment]
Can you check if you have nuget.org configured in your nuget configuration as I see that version of the package is available: https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-arm64/6.0.0-preview.7.21377.19

**Comment by guide2wsl** [comment]
I think you're on the right track.  Within Linux, once I run the dotnet publish command, the directory ~/.nuget and file ~/.nuget/NuGet/NuGet.Config is automatically created with the following content:

```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

On Windows, according to the .\obj\project.assets.json file, the equivalent directory is `C:\Users\guide2wsl\.nuget` however the difference is this directory does not exist, therefore was not created automatically.

On Linux, this "just works" :)

So I would think the Windows dotnet publish command should have consistent behaviour with the Linux flavour.

I also confirmed this issue applies to both ARM and x64, Windows 10 or 11, so it's more a Windows vs Linux issue.

**Comment by guide2wsl** [comment]
Windows:
```powershell
> dotnet nuget list source
No sources found.
```

Linux:
```bash
$ dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
```

**Comment by guide2wsl** [comment]
Check this out under Linux:
```bash
guide2wsl@spx:~$ rm -R ~/.nuget
guide2wsl@spx:~$ file ~/.nuget
/home/guide2wsl/.nuget: cannot open `/home/guide2wsl/.nuget' (No such file or directory)
guide2wsl@spx:~$ dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
guide2wsl@spx:~$ file ~/.nuget
/home/guide2wsl/.nuget: directory
```

So on Linux, dotnet definitely makes nuget.org a source by default if you have none configured.

**Comment by guide2wsl** [comment]
I can no longer reproduce with 6.0.0-rc.1.21451.13, so this has been fixed at some point, or not sure if nuget was updated outside the SDK:
```powershell
dotnet nuget --version
NuGet Command Line
6.0.0.230
```

Marking issue as resolved.

**Comment by guide2wsl** [comment]
I spoke too soon, I can still reproduce with the .NET 6 rc1 SDK.  It turns out on Windows when you run:
```powershell
dotnet nuget add source -n nuget.org https://api.nuget.org/v3/index.json
```

More than just:
$HOME\\.nuget is modified

so wiping that directory alone on Windows wasn't enough to confirm this was resolved.

**Comment by scottmwyant** [comment]
I think I'm seeing the same thing on win-x64.  Just installed .NET 6.0 this morning.  I've never done .NET development on this machine before.  Don't have Visual Studio.  Working with CLI and VS Code.

Using `<PublishSingleFile>true</PublishSingleFile>` in my csproj turns the error on and off for me.  Set to `true` and it asks for a runtime, so I run `dotnet publish -r win-x64` and get the NU1100 errors.  Use `<PublishSingleFile>false</PublishSingleFile>` and it works.

**Output of dotnet --info:**

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
