### ISSUE TITLE
dotnet watch verbose started does not show arguments

### ISSUE THREAD

**Issue by olivercoad** [dotnet/sdk#20843]
### Describe the bug
When running dotnet watch with verbose, the process runner outputs a line when it's started a process.
It's meant to include the arguments but since #16741 it's empty `''`.

### To Reproduce
`dotnet watch run -c Debug`

Expected:
```
watch : Started 'C:\Program Files\dotnet\dotnet.exe' 'run -c Debug' with process id 35500
```

Actual:
```
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 35500
```

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc
```

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/sdk/pull/20844
