### ISSUE TITLE
Multilayer Directory.Build.props results in CS0105

### ISSUE THREAD

**Issue by garcipat** [dotnet/sdk#20854]
Hi

Im trying to use the new implicit usings together with the Directory.Build.Props file that I put at the same level as the solution file.
I have two DirectoryBuild.props to be exact. One for a module and one for all the solution:

For the module:
```xml
<Project>	
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<Product>Mylibrary</Product>
	</PropertyGroup>	
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../../'))" />
</Project>
```

and for the solution one:

```xml
<Project>	
	<PropertyGroup>
		<Company>MyCompany</Company>
		<Authors>MyTeam</Authors>
		<NeutralLanguage>English</NeutralLanguage>
	</PropertyGroup>

	<ItemGroup>
		<Import Include="System" />
		<Import Include="System.Text" />
		<Import Include="System.Linq" />
	</ItemGroup>
</Project>
```

and Im getting the Warnings from the generated files in the obj folder:
"CS0105: The using directive for 'System' appeared prevoiusly in this namespace"

Even when commenting the Import lines, I'm getting this error.
But I switched to net5.0 and LangVersion 9.0 and there the problem doesnt apear.

There seems to be a problem with using multiple Directory.Build.props files and net6.0

**Comment by garcipat** [comment]
Is this connected to this issue [Warning CS0105 - The using directive for 'System' appeared previously in this namespace - C# 10 and .NET 6.0](https://github.com/dotnet/sdk/issues/18345)?

**Comment by marcpopMSFT** [comment]
Old bug triage: We believe this may be fixed. If it's still an issue, please provide a repro project or https://aka.ms/binlog of the failures. Thanks.
