### ISSUE TITLE
Support URL's in workload update's --from-rollback-file parameter

### ISSUE THREAD

**Issue by Redth** [dotnet/sdk#20879]
Creating a rollback json file manually is not intuitive, and there is no easy/automated way to create this file otherwise.

If we added support for URL's for the `--from-rollback-file` parameter for `dotnet workload update` we could provide rollback files as part of .NET MAUI builds for example, and use a link to direct to a rollback file.  We would probably do this as part of MAUI's build pipeline, or repo, so that the rollback file always exists for a given branch's configuration/output (ie: `main` would have a rollback with all the workload versions from the latest builds in our main branch).

**Comment by Redth** [comment]
//cc @dsplaisted @wli3

**Comment by sfoslund** [comment]
Fixed in RC2 by #20991

**Comment by dsplaisted** [comment]
Thanks a bunch Sarah and thanks @Redth for filing the issue!

🎉🎈🎉🎈
