### ISSUE TITLE
With .NET 6 RC2 SDK zip installed, maui workload update failed in CLI.

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#20889]
Environment: 6.0.100-rc.2.21460.1(runtime-6.0.0-rc.2.21458.16)

Repro steps:
1. Set up clean machine with .NET 6 RC2 SDK zip installation from https://github.com/dotnet/installer 
2. Run _dotnet workload install maui --skip-manifest-update --source  "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json"_ in CLI
3. Succeed install without warning or error
4. Run dotnet workload update 

Expected:
maui workload should update succeed without warning or error 

Actual:
maui workload update failed in CLI.
![image](https://user-images.githubusercontent.com/87680983/132832087-f60b856d-766c-4c30-915e-8315db9659a6.png)

Dotnet info:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21460.1
 Commit:    41cdf7a4b2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\v-danche\Downloads\dotnet-sdk-6.0.100-rc.2.21460.1-win-x64\sdk\6.0.100-rc.2.21460.1\

Host (useful for support):
  Version: 6.0.0-rc.2.21458.16
  Commit:  4cf387b5af

.NET SDKs installed:
  6.0.100-rc.2.21460.1 [C:\Users\v-danche\Downloads\dotnet-sdk-6.0.100-rc.2.21460.1-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21459.34 [C:\Users\v-danche\Downloads\dotnet-sdk-6.0.100-rc.2.21460.1-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21458.16 [C:\Users\v-danche\Downloads\dotnet-sdk-6.0.100-rc.2.21460.1-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21459.9 [C:\Users\v-danche\Downloads\dotnet-sdk-6.0.100-rc.2.21460.1-win-x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
Fixed by #20898

**Comment by WenJunJi01** [comment]
Fixed on 6.0.100-rc.2.21460.37(runtime-6.0.0-rc.2.21460.8)
