### ISSUE TITLE
Blazor-wasm/Linux: getting two publish directories named `Publish`, and `publish`

### ISSUE THREAD

**Issue by radical** [dotnet/sdk#20923]
Using the changes from https://github.com/dotnet/sdk/pull/20742 with sdk `6.0.100-rc.2.21459.15`, I found that building with `$(DeployOnBuild)=true` on Linux, it ends up with two publish dirs - `Publish`, and `publish`.

Looking at the logs, the former is coming from `$(PublishUrl)`, and the latter from `$(PublishDir)`(which gets that from `$(PublishDirName)='publish'`).

To reproduce:
1. Use the updated targets file from dotnet#20742
2. build a template blazorwasm project with `dotnet build -p:DeployOnBuild=true`

Without the changes from dotnet#20742, we get `Publish`.

cc @javiercn @TanayParikh @vijayrkn @dsplaisted

**Comment by vijayrkn** [comment]
This is a good bug. I haven't looked at it in detail but my guess is it is from here - https://github.com/dotnet/sdk/blob/main/src/WebSdk/Publish/Targets/PublishProfiles/Default.pubxml#L9

This needs to be `publish` instead of `Publish`.

**Comment by vijayrkn** [comment]
Should be a simple enough fix.

**Comment by vijayrkn** [comment]
To have a consistent experience between the 2 properties, resolving this issue will also help - https://github.com/dotnet/sdk/issues/20931
