### ISSUE TITLE
Do not assume specific location of dotnet CLI

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#2098]
The tests currently assume dotnet CLI is installed in `$(RepoRoot)/.dotnet`:

https://github.com/dotnet/sdk/blob/master/src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs#L119

Instead the tests should use `DOTNET_INSTALL_DIR` environment variable to locate dotnet CLI.

In future we might want to change this to `DOTNET_ROOT`, once it's implemented.

**Comment by livarcocc** [comment]
@dsplaisted could you pick this up? Both @tannergooding and @johnbeisner are going to be out next week and besides them, you were the latest to touch this infra.

@tmat how could we get a heads up on this kind of change with more antecedence?

**Comment by tmat** [comment]
@livarcocc Sorry about the urgency. I just learned today about the timeline. I'll see if we can establish better communication channel with the source build folks. 
This particular change should be trivial, but there will be more significant changes coming. I'm still working on source build support in the toolset and onboarding SymReader and SymReader-Portable. Then I'll have better idea what needs to be done in other repos.

**Comment by nguerrera** [comment]
Which branch needs to be source built so soon?

**Comment by tmat** [comment]
release/2.1.3xx

**Comment by dsplaisted** [comment]
@livarcocc Yes I can do this

**Comment by tmat** [comment]
@dsplaisted I have tried to fix this in cli-migrate repo like so:
https://github.com/dotnet/cli-migrate/pull/68/commits/52d9d600ca6aad966aa8de683c79e1553bec9ab4#diff-c78a48da239810b60ba0266a3b13366a

The tests fail though for some reason.
