### ISSUE TITLE
High CPU usage from dotnet CLI with 6.0-RC1 builds

### ISSUE THREAD

**Issue by kerams** [dotnet/sdk#21028]
### Describe the bug
Watching an F# application on RC 1 fully saturates a CPU thread (~8% on an 8/16 core processor).
On Preview 7 the watch overhead is essentially nonexistent, so this seems like a recent regression.

### To Reproduce
Create an F# console application targetting .NET 6, running on the RC 1 runtime.

```fsharp
[<EntryPoint>]
let main argv =
    printfn "yup"
    System.Threading.Thread.Sleep -1
    0
```

Then do `dotnet watch` and observe the CPU usage in task manager.

![Taskmgr_lKlYsbwXIJ](https://user-images.githubusercontent.com/5063478/133335181-4ec1fc9a-703d-484f-b65f-cb415149aeef.png)

### Further technical details
VS 2022 Preview 4
<details>
  <summary>dotnet --info</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by Cisien** [comment]
I'm seeing this issue as well running `dotnet watch run --launch-profile BlazeBin-Browser` against https://github.com/cisien/BlazeBin (scoped to the Server project's directory)

Opting out of telemetry does not solve the issue for me either.

**Comment by kerams** [comment]
Tested on RC2, fixed by https://github.com/dotnet/sdk/pull/21085.
