### ISSUE TITLE
Unexpected NU5104 reported

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/sdk#2103]
**Version Used**:
2.1.200-preview-007474
`C:\Program Files\dotnet\sdk\2.1.200-preview-007474\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5104`

**Symptom**:
All of my projects are preview and have prefix in their versions, but packing target claims they cannot dependent on preview packages.

**Reproduction**:
https://github.com/amatukaze/HeavenlyWind.Infrastructure/tree/38fff7c6cae4bcdf53b708696e1006f24e49e361

**About Installation**:
I've installed both stable and preview version of visual studio, and no SDK manually installed. .NET Core workload only installed with stable version. Not sure why the build uses a preview version of SDK. And I want to use stable version for production builds.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6759

**Comment by huoyaoyuan** [comment]
And what's about sdk installation and choice? It seems installed by preview version of VS.

**Comment by livarcocc** [comment]
VS brings with it the latest version of the SDK that's is compatible with it. The SDK itself is backwards compatible and capable of building projects with TFMs that came before its version. In this case, this is a bug, which I believe may have been addressed by NuGet already on its latest version. But I will let the NuGet folks comment on it.
