### ISSUE TITLE
Release metadata for 6.0.0-rc.1 has wrong release date set

### ISSUE THREAD

**Issue by Zastai** [dotnet/sdk#21054]
The [https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json][metadata] for the 6.0 SDKs has been updated to include the first RC release.

However, while the global `latest-release-date` is set correctly (`2021-09-14`), the entry for the `6.0.0-rc.1` release specifies `release date` as `2021-11-25`.

It's mostly harmless, but it's likely also an easy fix.

**Comment by sfoslund** [comment]
@KathleenDollard @leecow do you know who owns the releases.json data?

**Comment by sfoslund** [comment]
@joeloff do you happen to know who owns the releases.json data?

**Comment by joeloff** [comment]
@sfoslund I believe that's @rbhanda. Adding @leecow too

**Comment by kalaskarsanket** [comment]
@joeloff  @sfoslund This issue is now fixed.

**Comment by sfoslund** [comment]
Thanks! Closing this issue.
