### ISSUE TITLE
PublishReadyToRun uses outdated references from previous builds

### ISSUE THREAD

**Issue by uecasm** [dotnet/sdk#21072]
### Describe the bug
When performing a publish with PublishReadyToRun enabled, it publishes using files in the `obj\...\R2R` directory even if these are outdated.  And these files are not cleaned on Clean/Rebuild.

### To Reproduce
1. Clone https://github.com/vcsjones/AzureSignTool/ and checkout sha a67eca560bf95cd765579721f2787189c75e96ae
2. `dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true src\AzureSignTool\AzureSignTool.csproj`
3. Run the resulting published app; it includes Microsoft.Extensions.Logging 3.1.5 and it works without issues.
4. Checkout sha 65aa1111d961933a91806c5d4630dd6ab44369b2 (current master at time of writing).
5. Build and publish again.
6. Run the resulting published app; it fails because it wants Microsoft.Extensions.Logging 3.1.18 but it only found 3.1.5.
7. Observe that despite the other directories containing 3.1.18 as expected, the R2R directory still contains 3.1.5.
8. No combination of Clean/Rebuild Solution fixes this; the only workaround appears to be to delete the R2R folders manually.

### Exceptions (if any)
```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.18.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by AntonLapounov** [comment]
I think this has been fixed by #25126.

**Comment by uecasm** [comment]
Which version of the SDK is that fix included in?

**Comment by AntonLapounov** [comment]
.NET 7 preview 5 and we are considering backporting it to .NET 6.

**Comment by AntonLapounov** [comment]
The fix is backported to the next release of .NET 6 by #26046.  Thank you for reporting this.
