### ISSUE TITLE
Implicit using issue with multiple level `Directory.Build.props`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#21073]
When I use the implicit using with multiple level `Directory.Build.props` in my project, it seemed not to work as expected,
project structure, there's a commit for reproducing the issue: <https://github.com/WeihanLi/dotnet-httpie/tree/0ee81bd3bcafa07391392340eaa01726ee8ff75c>

![image](https://user-images.githubusercontent.com/7604648/133702848-d1557864-ff05-4668-83b7-d94e8a2d319f.png)

The global using file generated is as follows:

``` c#
// <auto-generated/>
global using global::FluentAssertions;
global using global::HTTPie;
global using global::HTTPie.Implement;
global using global::HTTPie.Middleware;
global using global::HTTPie.Models;
global using global::HTTPie.Utilities;
global using global::Xunit;
```

The `System`/`System.Threading.Task` included by the SDK had not been included, while when I remove the `Directory.Build.props` in the `tests` folder, the generated global usings file is:

```c#
// <auto-generated/>
global using global::HTTPie;
global using global::HTTPie.Implement;
global using global::HTTPie.Middleware;
global using global::HTTPie.Models;
global using global::HTTPie.Utilities;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::WeihanLi.Common;
global using global::WeihanLi.Common.Helpers;
global using global::WeihanLi.Extensions;
```

And the `Directory.Build.props` file in the `tests` folder has content as below:

``` xml
<Project>
    <ItemGroup>
        <Using Include="FluentAssertions"/>
        <Using Include="Xunit"/>
    </ItemGroup>
</Project>
```

_Originally posted by @WeihanLi in https://github.com/dotnet/core/issues/6688#issuecomment-921340956_

**Comment by KalleOlaviNiemitalo** [comment]
The Directory.Build.props in the inner directory needs to import the file in the outer directory, if you want both to affect the same project.  See [Use case: multi-level merging|https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#use-case-multi-level-merging].

**Comment by WeihanLi** [comment]
I think it may be a bug because the SDK implicit usings are not generated when I use more than one `Directory.Build.props`

**Comment by KalleOlaviNiemitalo** [comment]
You have `<ImplicitUsings>enable</ImplicitUsings>` in the outer Directory.Build.props but not in tests/Directory.Build.props, which does not import the other one.

**Comment by WeihanLi** [comment]
Got it
