### ISSUE TITLE
dotnet publish self-contained fail to find runtime identifier in command line when using web sdk

### ISSUE THREAD

**Issue by timmydo** [dotnet/sdk#21116]
### Describe the bug

ms build project files aren't able to determine the runtimeidentifier passed on the command line to dotnet publish when the project files in question use the web sdk.

Microsoft.NET.RuntimeIdentifierInference.targets(126,5): error NETSDK1031: It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier. You must either specify a RuntimeIdentifier or set SelfContained to false.

additionally, `dotnet publish --help` and `https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish` don't agree on the argument ordering. The former shows options first and the latter shows options after the project file.

### To Reproduce
run `dotnet publish -c release -r win-x64 --self-contained true` 

changing `<Project Sdk="Microsoft.NET.Sdk.Web">` to `<Project Sdk="Microsoft.NET.Sdk">` in the projects in question seems to fix the issue.

Contact me directly for a repro on an internal git repo.

### Further technical details
```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d
```

**Comment by sfoslund** [comment]
@timmydo can you give some more repro instructions here? What does your project look like? What version(s) of the SDK does this repro with?

**Comment by marcpopMSFT** [comment]
@vijayrkn seems to only repro with the web sdk and not the main sdk.

**Comment by vijayrkn** [comment]
@timmydo - Can you please share the binlog by passing `/bl` to the build?

**Comment by vijayrkn** [comment]
Closing due to the lack of additional information required to troubleshoot the issue.
