### ISSUE TITLE
.NET CLI: dotnet command output formatting

### ISSUE THREAD

**Issue by guardrex** [dotnet/sdk#21142]
### Feature request

[Forgive me if this has been asked and answered ... issues on 'output format(ing)' are hard to discover here.]

For a short period from RC1 to GA, I work from the CLI. Sometimes, working with a sample results in **_wall of text_** compiler output. For example, new NRT notices are a bit hard on the 👁️😵. The app that generated the following output had ~60 of these back-to-back ...

<img width="474" alt="Capture" src="https://user-images.githubusercontent.com/1622880/133888323-664458d6-42ad-420c-b200-64d1866240bf.PNG">

This is potentially a broader ask tho than just eyeball'in some console warnings. Would it be useful to have output formats in JSON, YML, text, table, etc. for the `dotnet` command? Maybe not, as I don't see issues asking. At least consider the simplest case tho ... an old green dinosaur with failing eyesight looking at a lot of build warnings/errors in the console.

### Describe the solution you'd like

A feature option for the `dotnet` command that will ...

* At a minimum, place one blank line between lines of console output.
* At most, multiple compiler output formats: preset template, custom template, JSON, YML, text, table, etc.

Just to compare a simple preset (or custom) template approach to the earlier image, consider the improvement for my aging 👴👓 eyesight to look at something like the following ...

<img width="482" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/133888217-3b1a83bf-c816-4525-aa75-a9f1630e551d.PNG">

**Comment by baronfel** [comment]
There is some prior art here - many popular CLI applications allow for setting a preference for what output format should be used for commands, notably cloud CLIs for Azure, AWS, and Google Cloud. We don't currently have a consistent mechanism for this in the .NET CLI, but we should develop a consistent strategy for this and apply it uniformly.

**Comment by baronfel** [comment]
Going to close this with the availability of the MSBuild TerminalLogger. Try it out with `-tl` and send feedback to dotnet/msbuild!
