### ISSUE TITLE
Cannot build project with PackAsTool=true and GeneratePackageOnBuild=true 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2114]
**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```
`dotnet build`

**Expected**
Build the project *and* produce a nupkg.

**Actual**
`dotnet build` fails

> C:\Program Files\dotnet\sdk\2.1.300-preview2-008523\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(326,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "_WalkEachTargetPerFramework". [C:\dev\natemcmaster\tmp\tmp.csproj]

**Comment by wli3** [comment]
Circular is here 
```
 If GeneratePackageOnBuild=true is set. It will depend on pack
   +-----------------------------------------------------+
   |                                                     |
   |                                                     |
   |                                                     |
   |                                                     |
   |                                                     |
   +                                                     v
build  <-----------+ Publish  <-------------+ Pack(PackAsTool=true)

```

**Comment by wli3** [comment]
but publish do need build to happen before hand. __PreventProjectReferencesFromBuilding_ or _NoBuild_ has similar issue to pollute global variable

**Comment by wli3** [comment]
strange, if I take a dependency "by hand" like the prototype pack tool project. There is no circular error https://github.com/wli3/testpack00

**Comment by wli3** [comment]
And if you set <TargetFramework>netcoreapp2.1</TargetFramework> to <TargetFrameworks>netcoreapp2.1</TargetFrameworks> it is fine

**Comment by wli3** [comment]
Relate https://github.com/NuGet/NuGet.Client/pull/1148

**Comment by wli3** [comment]
The timing of load <NoBuild>true</NoBuild> is wrong. NuGet already set this flag. However, due to timing, it is not honored by Publish<-PackTool

**Comment by wli3** [comment]
reopen, and regressed due to https://github.com/NuGet/NuGet.Client/pull/2822

Thinking a solution...

cc @nkolev92 @peterhuene

**Comment by wli3** [comment]
close, prefer new bug

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/issues/3253
