### ISSUE TITLE
dotnet test is too noisy

### ISSUE THREAD

**Issue by qubitz** [dotnet/sdk#21150]
When running ```dotnet test``` on my projects I have only ever cared if the build compiled, the expected tests ran, and the results of the tests. With the current default output, this information is mixed with irrelevant information. Example below. In my attempt to reduce output I used ```--verbosity minimal```, but realized that the default verbosity level is "minimal". 

I'd like to have "minimal" only show the tests that ran and their results. In other words, the line that is normally partly green and nothing else. Build results are not wanted unless the build failed. With this new verbosity level, current "minimal" output would be renamed to "normal", "normal" into "detailed", and "diagnostic", which is crazy btw, can just stay crazy. 

![image](https://user-images.githubusercontent.com/15070724/133912569-11b0b570-9acb-4fb7-9ff3-21aeab028121.png)

As to what the default verbosity level should be, I'm only one voice. Appending ```-v m``` is small price to pay if the new "minimal" is not chosen to be the default.

PS This cli has been a huge success. Thanks for the hard work.

**Comment by nohwnd** [comment]
Thanks for your issue, but we don't plan to change the current output or offer customizations to the way we log the build and run.
