### ISSUE TITLE
Microsoft.DotNet.PackageValidation missing for .NET 6 RC1

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#21167]
### Describe the bug

I noticed that an rc.1 version of `Microsoft.DotNet.PackageValidation` for .NET 6 is not available from [NuGet.org](https://www.nuget.org/packages/Microsoft.DotNet.PackageValidation).

Is this an oversight, or intentional?

**Comment by joeloff** [comment]
I believe this now ships as Microsoft.DotNet.Compatibility

https://www.nuget.org/packages/Microsoft.DotNet.Compatibility/1.0.0-rc.1.21458.71

**Comment by ericstj** [comment]
Additionally, you don't need a PackageReference at all if you are using the 6.0 SDK.  It is built in and you can just set a property.

**Comment by martincostello** [comment]
Good to know, thanks!
