### ISSUE TITLE
Target Multi-TFM net461 and netcoreapp2.1, restore failed.

### ISSUE THREAD

**Issue by Xiu-Li** [dotnet/sdk#2119]
**## Repro Steps:**
1. In CLI/VS create a new C# .net core console app.
2. Change frameworks to `<TargetFrameworks>net461;netcoreapp2.1</TargetFrameworks>`.
3. Restore failed with the errors as below:
![image](https://user-images.githubusercontent.com/24784908/38466661-23e6b976-3b5f-11e8-959f-64b45ffa9b0b.png)
5. After adding dotnet-core package source: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json , restore still failed with the errors as below:
![image](https://user-images.githubusercontent.com/24784908/38466678-80b1a710-3b5f-11e8-9f26-a5bf57ae0166.png)

**## Test Environment:**
D15.6/27428.200 + CLI/SDK [2.1.300-preview2-008530](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180406-05/final/assets/Sdk/2.1.300-preview2-008530/dotnet-sdk-2.1.300-preview2-008530-win-x64.exe)
or D15.7/27604.00 + CLI/SDK [2.1.300-preview2-008530](https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180406-05/final/assets/Sdk/2.1.300-preview2-008530/dotnet-sdk-2.1.300-preview2-008530-win-x64.exe)
dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  1.1.8 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


```

**Comment by livarcocc** [comment]
@weshaggard @mmitche this eems like a downgrade in the Microsoft.NetCore.App graph itself. can you take a look?

**Comment by weshaggard** [comment]
I'm taking a look.

**Comment by richaverma1** [comment]
@weshaggard, this is a blocking issue for 2.1 Preview 2, please keep me informed of the status so that I can report accordingly.

**Comment by weshaggard** [comment]
This is caused because the runtime package isn't published.

**Comment by weshaggard** [comment]
This is because the publishing failed in the morning. @mmitche is going to be republishing and once that happens I believe this should be resolved.

**Comment by Petermarcu** [comment]
Perhaps this issue should track the fact that there is a restore of the runtime happening at all. I don't see why that should be happening.

**Comment by weshaggard** [comment]
Yes that is an interesting issue that I just asked in email about.

**Comment by mmitche** [comment]
The publishing has completed.
