### ISSUE TITLE
Building an app with PreserveCompilationContext=true causes files from the shared runtime to be copied to bin\refs directory

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#2121]
This is a regression (?) in 2.1.0-preview2 sdk. Repro steps:

1) Acquire preview1 Sdk - https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1
2) `dotnet new mvc`
3) `dotnet build`

Examine the bin\Debug\netcoreapp2.1 directory and notice all it has is the app's binaries.

4) Clean the bin directory and run `dotnet build` using the preview2 Sdk (I used `2.1.300-preview2-008367`)

The bin directory has a refs directory that contains 300+ files from shared runtimes.

**Comment by pranavkm** [comment]
`_CopyReferenceOnlyAssembliesForBuild` uses `_ReferenceAssemblies` as input for files to copy. Between preview1 and preview2, `NuGetSourceType` is no longer being set [which causes](https://github.com/dotnet/sdk/blob/935ac5fde8d917b1de3b18d038232f15527572aa/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L367-L370) package and runtime refs files to get copied to the bin directory.

| Preview1 | Preview2 
| ----------| ----------- 
| ![image](https://user-images.githubusercontent.com/174281/38513145-258a3428-3be2-11e8-969d-34068bbf60e5.png) | ![image](https://user-images.githubusercontent.com/174281/38513209-54f9721e-3be2-11e8-887c-2be3f93074b6.png)

**Comment by livarcocc** [comment]
@nguerrera caused by your changes?

**Comment by nguerrera** [comment]
Yes. I will fix this.

**Comment by pranavkm** [comment]
Is there a CLI available that contains this fix? Just like to verify this fixes Mvc scenarios e2e.

**Comment by nguerrera** [comment]
@pranavkm I don't think so unless there are already RC prodcon builds happening: cc @mmitche.

**Comment by mmitche** [comment]
There are, but nothing through CLI yet.
