### ISSUE TITLE
Library Packs for Optional Workloads do not have `.msi.<arch>` packages

### ISSUE THREAD

**Issue by Redth** [dotnet/sdk#21227]
After installing a dotnet SDK through VS2022 Windows installer, the workload installation assumes it should use `msi` based pack installs going forward.

Unfortunately we recently observed that it expects to also have `.msi.<arch>` nupkg's available for `library-pack` items in the workload.

So, installing a newer 6.0.101-preview.9 based MAUI build fails on packages such as `Microsoft.AspNetCore.Authorization.Msi.x64` since no package actually exists.

Current workaround is to remove the `C:\Program Files\dotnet\metadata\workloads\6.0.100\installertype\msi` file and retry the install so that the workload uses non-msi based pack installation.

**Comment by mattleibow** [comment]
This is affecting all things that are dependencies. For example, Maui depends on ASP.NET and that depends on System.IO.Pipelines. In the end all things end up as msi packs.

**Comment by marcpopMSFT** [comment]
Per offline conversation, you'll revert the change for library packs and Daniel will investigate how best to design and make bundled library packs likely in 6.0.2xx.

**Comment by marcpopMSFT** [comment]
I believe that this is covered by workload pack groups.
