### ISSUE TITLE
Add a switch to control publishing files to the refs directory - PreserveCompilationReferences

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#2122]
Related issues - https://github.com/dotnet/sdk/issues/2092, https://github.com/dotnet/sdk/issues/2121

`PreserveCompilationContext` is used in two places today 

1. To determine if compilation content goes in the deps file 
2. If reference assemblies need to be copied to the `bin\refs` and `publish\refs` directories.

Prior to 2.1.0, the Web Sdk always set `PreserveCompilationContext=true`. This resulted in increased deployment sizes even when the app did not require these files due to design time compilation of views. In 2.1.0-preview2, we tried conditionally setting this value in the WebSdk based on the presence of Razor files. This broke Mvc's runtime capabilities which relies on being able to inspect the deps file to query dependencies. There's more information about it here - https://github.com/dotnet/sdk/issues/2092#issue-309192033.

What we care about, is the ability to suppress publishing the refs directory for most applications. In lieu of solving https://github.com/dotnet/sdk/issues/2092, which seems like a much more involved issue, it would be easier if we could have a different switch (suggestion `PreserveCompilationReferences`) that is used to determine if the refs directory gets emitted. Here are the two places we'd use this switch in lieu of  `PreserveCompilationContext`:

* https://github.com/dotnet/sdk/blob/6945e3694c918eea4c8c4fb6217e1485b179994b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PreserveCompilationContext.targets#L45-L46
* https://github.com/dotnet/sdk/blob/6945e3694c918eea4c8c4fb6217e1485b179994b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PreserveCompilationContext.targets#L84-L85

The Web.Sdk \ Razor.Sdk would be responsible for setting the default value of this property as also initializing it if the user explicitly specified `PreserveCompilationContext` in their project files.

**Comment by pranavkm** [comment]
cc @eerhardt \ @livarcocc \ @DamianEdwards \ @rynowak 

We'd like to get this considered for 2.1.0 rc. Let me know if you'd like to set up an offline discussion for this.

**Comment by normj** [comment]
Any progress on this? For us we want to keep the publish package size small so we are always setting `PreserveCompilationContext` to `false` but this breaks some customer scenarios.

**Comment by lmolotii** [comment]
Guys, do we have any progress on this issue?

**Comment by nguerrera** [comment]
See https://github.com/dotnet/cli/issues/10502#issuecomment-452408306

We should do this now. cc @dsplaisted

**Comment by rynowak** [comment]
This would be super nice to have built-in. We do our own workaround for this in Razor, and it would be better if we could just set a property default value 👍
