### ISSUE TITLE
With .NET 6.0 RC2(6.0.100-rc.2.21469.5) SDK, I can't install Blazor WebAssembly AOT workload. 

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/sdk#21261]
### Describe the bug
This issue may be caused by the [Feed](https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.2.21469.5-shipping/nuget/v3/index.json), is the Feed signed?
![image](https://user-images.githubusercontent.com/35762055/134304430-2cbaf3e0-bb86-464c-b21a-750728ce5ead.png)
```
Workload installation failed: One or more errors occurred. (Failed to validate package signing.

Verifying Microsoft.NET.Runtime.WebAssembly.Sdk.Msi.x64.6.0.0-rc.2.21468.3

Signature type: Author
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA256 hash: AA12DA22A49BCE7D5C1AE64CC1F3D892F150DA76140F210ABD2CBFFCA2C18A27
  Valid from: 9/29/2020 5:00:00 PM to 10/5/2023 5:00:00 AM

error: NU3008: The package integrity check failed. The package has changed since it was signed. Try clearing the local http-cache and run nuget operation again.

Package signature validation failed.
```

### To Reproduce
1. Install latest Dev17.0 Preview 5([main-31721.352](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=5233624&view=results)).
1. Install .NET 6.0 RC2 SDK from: [Pipelines - Run 20210919.1-6.0.100-rc.2.21469.5-109627 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1371489&view=artifacts&pathAsName=false&type=publishedArtifacts)

1. Add feeds: https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.2.21469.5-shipping/nuget/v3/index.json

1. Open commandline as administrator, run below command to install AOT workload, but failed.
`dotnet workload install wasm-tools`

1. Run below command to install the workload and skip the advertising manifests, failed again.
`dotnet workload install wasm-tools --skip-manifest-update`

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/35762055/134304665-3a2daca4-2182-4fb2-85a5-78f9e7ede4fd.png)

### Further technical details
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/35762055/134305076-7112a995-342a-4ed9-9266-76cefe72673a.png)

**Comment by mmitche** [comment]
Can you clear out the cache and ensure that you don't have the "dotnet6" feed in your nuget.config file too?

**Comment by wli3** [comment]
run `dotnet nuget locals all --clear`

**Comment by Andy-Win** [comment]
@mmitche , @wli3 
The only feed I used is "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-rc.2.21469.5-shipping/nuget/v3/index.json"
After running the command "dotnet nuget locals all --clear" to clear the cache, I still can’t install the wasm-tools workload.
![image](https://user-images.githubusercontent.com/35762055/134654595-6cffbdf0-bcdf-4cac-a045-41476a18b30f.png)

**Comment by mmitche** [comment]
Can you verify `dotnet nuget list source` from your project? Otherwise this looks like maybe a product bug?

**Comment by Andy-Win** [comment]
@mmitche , Using the new SDK([6.0.100-rc.2.21473.26](https://dev.azure.com/dnceng/internal/_build/results?buildId=1381847&view=results)) and new [feed](https://pkgs.dev.azure.com/dnceng/_packaging/6.0.100-rc.2.21473.26-shipping/nuget/v3/index.json), I am still able to reproduces this issue.
Here is the output of `dotnet nuget list source`
![image](https://user-images.githubusercontent.com/35762055/134849634-3bc9a6bc-00b7-4222-84f3-97d398f70135.png)

**Comment by mmitche** [comment]
Manually downloading and verifying the package shows a valid signature, so maybe something else is going on. @joeloff can you take a look?

**Comment by joeloff** [comment]
@Andy-Win There should be some logs from the workload installation command in your %temp% folder. Especially if you still have the original when you saw the problem. It may help to shed some light on the issue. The console output was a bit odd because it appears to have tried to download the package 3 times

**Comment by Andy-Win** [comment]
@mmitche ,@joeloff, using the latest 6.0 RC2 SDK(6.0.100-rc.2.21476.4), and corresponding [feed](https://pkgs.dev.azure.com/dnceng/_packaging/6.0.100-rc.2.21476.4-shipping/nuget/v3/index.json), I can install the wasm-tools successfully now.

**Comment by Andy-Win** [comment]
Close this issue as fixed
