### ISSUE TITLE
Recently daily preview(2.1.300-preview3-008433/008443) hangs when build multi TargetFrameworks project?

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#2129]
Tested with `2.1.300-preview3-008433/008443`(Windows x64), and `2.1.300-preview3-008414`(Windows x64) works well.
`dotnet new classlib`, and modify to multi TargetFrameworks, then `dotnet build`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.6;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```
The build will stop after extra 300s, and failed with no error message.

**Comment by rainersigwald** [comment]
This sounds an awful lot like https://github.com/Microsoft/msbuild/issues/3142. Were you installing the builds via the MSI, or otherwise using a path with a space?

**Comment by yyjdelete** [comment]
@rainersigwald 
Maybe via MSI(dotnet-sdk-latest-win-x64.exe), and installed to `C:\Program Files\dotnet` which contains a space.

**Comment by livarcocc** [comment]
Can you try a copy of the SDK that is installed in a location without any spaces (acquire it through a zip) and see if this repros?

**Comment by yyjdelete** [comment]
1. Make a copy with no `space` works for me.
2. After a successful build with `step 1`, the one with space also works, even with new project or clean.
3. `dotnet restore` didn't failed for me before `step 1`, only the build after the first `TargetFramework` hangs(the first TargetFramework build successful)

**Comment by livarcocc** [comment]
@rainersigwald does it still sound like microsoft/msbuild#3142?

**Comment by rainersigwald** [comment]
Ok, that's confirmation that this is that MSBuild bug. Your step 2 will only work for 15 minutes after a successful build or restore from the no-space path.

**Comment by livarcocc** [comment]
Closing this one then in favor of the msbuild issue.
