### ISSUE TITLE
NuGet Credential Provider Plugin Fails to Start

### ISSUE THREAD

**Issue by reynoldsbd** [dotnet/sdk#21320]
### Describe the bug

NuGet credential provider fails to initialize if two .NET projects are being built concurrently.

Appears to be caused by a race condition where both concurrent MSBuild instances attempt to open the same log file for plugin logs. The winner of the race successfully opens the file and starts the plugin; the loser fails to start the plugin, and the overall build fails because NuGet packages cannot be restored.

So far my team has only observed this happening within Azure DevOps Pipelines builds, and only over the past 2 weeks or so. I'm confident that nothing in our build has changed; we have been building .NET projects concurrently for years. But I'm not sure whether this is an issues in the .NET SDK's MSBuild targets or in the cred provider plugin itself, so please feel free to redirect me as appropriate

### To Reproduce

Definitely not easy to repro. You have to get "lucky" and start two separate .NET builds within a short time of each other. Haven't been able to reproduce locally, but this happens in our CI builds dozens of times per day.

### Exceptions (if any)

Full output from `dotnet publish`:

```
  Determining projects to restore...
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Problem starting the plugin 'C:\Users\cloudtest\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Problem starting the plugin 'C:\Users\cloudtest\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error :   The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
  Retrying 'FindPackagesByIdAsync' for source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Failed to retrieve information about '<PACKAGE>' from remote source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\a\_work\1\s\Path\To\MyProj.csproj]
```

### Further technical details

Happening in an Azure DevOps Pipeline using .NET SDK 5.0.401.

No IDE, our builds are command-line driven.

**Comment by brbero** [comment]
Hi @joeloff - we continue to see this failure periodically.  Is there any update or plan to address it?

**Comment by brbero** [comment]
Ping @joeloff & @marcpopMSFT

**Comment by joeloff** [comment]
This looks like a NuGet issue. Any NuGet operations from the SDK is just shelled out to NuGet directly AFAIK. @nkolev92 @zivkan are you aware of any issues in the credential provider? From the error above it appears parallel dotnet instances are trying to access the same log file

**Comment by joeloff** [comment]
@brbero forgot to ask, have you seen this only on the SDK you mentioned?

**Comment by reynoldsbd** [comment]
(I'm on the same team as Brent)

We are still observing this in .NET 5.0.404

**Comment by nkolev92** [comment]
@reynoldsbd 

Are you enabling the logging yourself with `NUGET_PLUGIN_ENABLE_LOG`?

The file name is calculated with respect to the time with Ticks precision, `DateTime.UtcNow.Ticks:x`, https://github.com/NuGet/NuGet.Client/blob/ea8de1fff4ad05b24d36b2d8197678aeda24e490/src/NuGet.Core/NuGet.Protocol/Plugins/Logging/PluginLogger.cs#L107. 

It's pretty crazy that the timing is that close.  We cab always add something random to allow for the logs to be differentiated. 

Maybe process id?

**Comment by reynoldsbd** [comment]
Hi @nkolev92!

Yes, we do enable logging.

And yes, the timing is very close! It only happens during a small fraction of our CI builds. I guess in that sort of environment, our build scheduler is a lot more deterministic than on a local workstation.

I'm going to go ahead and close this issue in favor of NuGet/Home#11517. Thanks @joeloff for routing us to the right team!
