### ISSUE TITLE
[Package-Validation] Add flag to run the package baseline validation in a strict mode.

### ISSUE THREAD

**Issue by Anipik** [dotnet/sdk#21333]
Currently we run the baseline validation with non-strict mode.  We should provide a flag for running the baseline package validation in strict mode as well.

This will allow developers to run some api compat rules eg will allow to maintain a consistent assembly version across different package versions.

**Comment by ViktorHofer** [comment]
Closing as a dup of https://github.com/dotnet/sdk/issues/25302 which has more information.
