### ISSUE TITLE
[Breaking change] For `dotnet test`, switch `-a` to alias `--arch` instead of `--test-adapter-path`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#21389]
Check it out ...

```bash
rich@MacBook-Air-M1-2020 tests % dotnet test --help | grep -- -a
  -a, --test-adapter-path <ADAPTER_PATH>  The path to the custom adapters to 
  --blame-crash-collect-always            Enables collecting crash dump on 
  <blame-crash-collect-always>            expected as well as unexpected 
  --arch <arch>                           The target architecture.
rich@MacBook-Air-M1-2020 tests % dotnet run --help | grep -- -a
  -a, --arch <arch>                    The target architecture.
```

Sure would be nice to make `-a` the same everywhere. I doubt that the current usage of `-a` is common.

This is similar to https://github.com/dotnet/sdk/issues/21952.

- https://grep.app/search?q=dotnet%20test%20-a
- https://grep.app/search?q=dotnet%20test%20--test-adapter-path

**Comment by sfoslund** [comment]
@nohwnd for the dotnet test team

**Comment by nohwnd** [comment]
If we are breaking this, that we should probably consider using -r for --runtime, instead of --results-directory. And also check if there are more conflicts with dotnet test.
