### ISSUE TITLE
CS4014 warning reported even though async call is waited.

### ISSUE THREAD

**Issue by bempelise** [dotnet/sdk#21430]
Environment:
Replicated on `.NET 3.1.413` and `.NET 5`

I have the following simpified situation that yields CS4014:

```
class Program
{
    static void Main(string[] args)
    {
        Task.Run(() => Launch());
    }

    static async Task Launch()
    {
        bool canLaunch = false;
        while (true)
        {
            if (canLaunch)
            {
                Task.Run(async () => await MyAsync());
            }
            else
            {
                await Task.Delay(100);
            }
            
        }
    }

    static async Task MyAsync()
    {
        await Task.Delay(100);
    }
}
```

In the above, the line
`Task.Run(async () => await MyAsync());`
yields warning CS4014.

The warning can be fixed if the `Launch()` function is changed to be non async.

I am not sure if nested async calls are supposed to have this behaviour but I think that the warning is raised in error as the task is clearly being waited for.

**Comment by KalleOlaviNiemitalo** [comment]
Launch() does not await the task that Task.Run returns. [SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAVgNwFgBQUBMDEDsWA3lnOfgGwIAscAsgIYCWAdgBRIwDaAunIwBOAcwDOASjIVSmCnISUAdACUArh3bi4AXgB8cADKN1AYwAWm8RlkUAvlinkk1KAA4Fh463ObHcGfIUAEYA9iEANnAmjKxGpmY6cABmjOGiAKbWgeQA7mbM4elw7AAugqrpkjaBAdlyzEnF0bFe5lV1crUd8lAAnAoq6pzumjr6fQwAngCCopPellndcPbVHelp6X51XctO/VBKACIbjJPsiDAwVtvZq3u35Pd2DmvOCO6HU7PzJr5ruzkE0OihO4TOFyuNzWq1sQA)

**Comment by bempelise** [comment]
Yes you are right I am closing this.
