### ISSUE TITLE
Unable to compile my .net core app using build

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/sdk#21498]
Hi

I am running build retail -amd64 on my repo and I want to compile a .net core app and mention this logic in a dirs.proj file.

Here is my current logic but I don't see this target being touched when I run the above command(Default target is "Build")

```
<Target Name="Build">
         <ItemGroup>
            <Compile Include="WindowsAuditSetting\Program.cs" />
            <Compile Include="WindowsAuditSetting\SetACLNative.csproj" />
         </ItemGroup>
</Target>
```

Here is the .csproj of the project
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <runtimeidentifier>win-x64</runtimeidentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="1.0.0-alpha-29408-02" />

    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
  </ItemGroup>
    
</Project>
```

Here is the error I am facing

error MSB4041: The default XML namespace of the project must be the MSBuild
XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to
 the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. [C:\ASM-AzSecP
ack\src\ScriptPackage\ScriptPackage.proj]

Not sure, what needs to be done to pick the project and compile it using build retail -amd64

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by KalleOlaviNiemitalo** [comment]
Might `build retail -amd64` be using something older than [MSBuild 15](<https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2019> "What's New in MSBuild 15 - MSBuild | Microsoft Docs")? If so, I doubt it's going to work with the current .NET SDK or even be able to find the SDK files. You may be able to work around this by making the `build` utility run the [Exec task](https://docs.microsoft.com/visualstudio/msbuild/exec-task?view=vs-2019) and invoke the newer version of MSBuild that way.

**Comment by KalleOlaviNiemitalo** [comment]
The `build` utility you are using -- is it a Microsoft internal tool? There used to be such a thing in Windows Driver Kit before Windows 8 ([Using Visual Studio or MSBuild to build a driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/building-a-driver)) but it was based on NMAKE rather than MSBuild.

**Comment by ssarin3194** [comment]
Yes, it is a mS internal tool..

**Comment by ssarin3194** [comment]
@dsplaisted  can you help me with this :)

**Comment by dsplaisted** [comment]
You'll have to talk to people who are familiar with the `build` tool you are using.  I don't know anything about it.

It does sound like the problem may be that your build environment is using a very old version of MSBuild.

**Comment by ssarin3194** [comment]
we are using msbuild itself.

**Comment by dsplaisted** [comment]
What version of MSBuild are you using?

Sharing a [binlog](aka.ms/binlog) would be the way to help us investigate what's going wrong.  You may want to do that internally though as the binlog contains a whole bunch of information about your build and your machine environment.

**Comment by ssarin3194** [comment]
The app was compiled using vs 2019, and the msbuild version is 16.11. However, I am unable to hit the target to even generate the binlog. I am able to compile it using "msbuild <name>.csproj" but not just running build on the repo...

**Comment by dsplaisted** [comment]
It sounds like the build script in your repo is not calling the right version of MSBuild.

That's not really something we can help you with, you need to look at how the build infrastructure in your repo is set up or talk to people who can help you with that.

**Comment by ssarin3194** [comment]
If I run msbuild on the csproj file, I get the error 

MSB4041: The default XML namespace of the project must be the
MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/
msbuild/2003" to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003
format.

**Comment by dsplaisted** [comment]
What is the path to MSBuild that you are using?  What is the exact command line?

What is the result if you run `msbuild /version` (with the same MSBuild that you are trying to use to build the project).

**Comment by ssarin3194** [comment]
msbuild /version
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Yes, if i use this version, 14.0 to build the project using msbuild I get this error--



C:\repos\ASM-AzSecPack>msbuild src\WindowsAuditSetting\SetACLNative.csproj
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/29/2021 8:57:21 AM.
Project "C:\repos\ASM-AzSecPack\src\WindowsAuditSetting\SetACLNative.csproj" on node 1 (default targets).
C:\repos\ASM-AzSecPack\src\WindowsAuditSetting\SetACLNative.csproj(2,1): error MSB4041: The default XML namespace of th
e project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="h
ttp://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the o
ld 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
Done Building Project "C:\repos\ASM-AzSecPack\src\WindowsAuditSetting\SetACLNative.csproj" (default targets) -- FAILED.


Build FAILED.

"C:\repos\ASM-AzSecPack\src\WindowsAuditSetting\SetACLNative.csproj" (default target) (1) ->
  C:\repos\ASM-AzSecPack\src\WindowsAuditSetting\SetACLNative.csproj(2,1): error MSB4041: The default XML namespace of
the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns=
"http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the
 old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.20

It mighht be since this is a .net core proj compiled in vs2019?

**Comment by ssarin3194** [comment]
Yes where msbuild doesn't work..

But.

C:\repos\ASM-AzSecPack>powershell -command gcm msbuild

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     msbuild.cmd                                        0.0.0.0    C:\CxCache\MsBuild.Corext.14.0.23107.8\Path\msbuild.cmd

**Comment by ssarin3194** [comment]
What version of msbuild will work for my .net sdk project?

**Comment by ssarin3194** [comment]
When I run init.cmd , the msbuild version is 14.0.23, how do I resolve this to use 15+?

**Comment by dsplaisted** [comment]
The version of MSBuild you need depends on what version of .NET you're targeting, but ideally you should be using something recent like 16.10 or 16.11.

It looks like you're using CoreXT.  You probably need to update to a newer MSBuild package in CoreXT, and you may also need a package for the .NET SDK.

@rainersigwald Do you have any pointers to information about how to build .NET SDK projects in CoreXT?

**Comment by ssarin3194** [comment]
Yes, I agree, I need a newer MSBuild package in CoreXT.

**Comment by rainersigwald** [comment]
This is a Microsoft-internal problem. Let's move it to a Microsoft-internal forum.
