### ISSUE TITLE
Command line build fails but works in Visual Studio

### ISSUE THREAD

**Issue by adrianm64** [dotnet/sdk#21715]
I'm trying to add a packagereference via a nuget package but can't get it to work from command line.

I.e. it builds and runs fine from within Visual Studio but fails when using "dotnet build"

The .props file looks like this:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <PackageReference Include="System.ServiceModel.Http" Version="4.6.0" />
    </ItemGroup>
</Project>
```

If the above is in `Directory.Build.props` it works fine but if it is in a .props files supplied via a nuget package, "build" folder, the command line build fails with:

>error CS1069: The type name 'BasicHttpBinding' could not be found in the namespace 'System.ServiceModel'. This type
>has been forwarded to assembly 'System.ServiceModel.Http, Version=4.6.0.0, Culture=neutral, >PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

(I also get the same error if running Publish inside VS2022)

I added msbuild logging and even if I don't understand a lot of it I can clearly see that `/reference:C:\...\System.ServiceModel.Http.dll` is not included in the csc.exe command when running from the command line (but is when running in VS2022). 
I assume this means the compiler is fine and the problem is in msbuild/csproj.

Things I have tried:
* Restarted Visual Studio and computer
* Clear nuget cache
* Different versions of the System.ServiceModel.Http package
* Different sdk:s 3.1, 5.0, 6.0RC1

### To Reproduce
Attached is a small test project and a nuget package.
[TestProps.zip](https://github.com/dotnet/sdk/files/7277032/TestProps.zip)

Unpack the zip. Enter the TestProps folder
    dotnet add package PackageReferenceProps -s ..
    dotnet build (fails)
    ren _Directory.Build.props Directory.Build.props
    dotnet build (succeeds)

### Further technical details
> dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment

:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps NuGet does not look at PackageReference items within files of NuGet packages when it restores the packages. Can you use a NuGet package dependency instead?

**Comment by adrianm64** [comment]
> Perhaps NuGet does not look at PackageReference items within files of NuGet packages when it restores the packages. Can you use a NuGet package dependency instead?

NuGet is not involved here. The package downloads fine. It is the SDK/msbuild which doesn't pass the assembly reference to the compiler when building from the command line (but do when building in Visual Studio).

Unfortunately I can't use a package dependency.

Complicated reason, the dependencies need different asset filter settings than parent so they must be added as top-level PackageReference. If this scenario is not supported I can always go for 2 packages instead.
