### ISSUE TITLE
Failure in `dotnet add package` prints weird help message

### ISSUE THREAD

**Issue by MeikTranel** [dotnet/sdk#21770]
### Describe the bug
When `dotnet add package` fails the help message contains a usage breakdown with a weird construct - see the following excerpt:

```
...
error: There are no versions available for the package 'Newtonsoft.Jsonsfdsfsdf'.


Usage: NuGet.CommandLine.XPlat.dll package add [options]

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.

...
```
looks like somewhere `dotnet` was mixed up with `NuGet.CommandLine.XPlat.dll`

### To Reproduce

1. `dotnet new classlib`
2. type `dotnet add package Newtonsoft.Json`
3. drop your dinner over the keyboard
4. actually type `dotnet add package Newtonsoft.Jsonfdgdfgdfg`
5. hit enter and observe

### Further technical details
`dotnet --version`: 6.0.100-rc.1.21463.6
<details>
<summary>dotnet --info</summary>

PS C:\Users\trane\OneDrive\Desktop\testsubmods> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22471
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by marcpopMSFT** [comment]
@sfoslund would this come from our CLI code or the add package code? Shout out to step 3 of the repro steps.

**Comment by sfoslund** [comment]
> would this come from our CLI code or the add package code?

Our CLI code mostly just passes arguments along to nuget, so this shouldn't be from out CLI code.

**Comment by MeikTranel** [comment]
Fixed the Repro steps in the original issue - @marcpopMSFT correctly fixed the `package add` || `add package` mixup but forgot to change it in the actually entered command. This is important because the issue does not show up when simply entering the false order of commands but only when nuget is actually called to resolve a package but that package does not exist.
