### ISSUE TITLE
Support workloads installed via Visual Studio from CLI `dotnet workload` commands

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#21811]
We'd like (at a minimum) the following commands to have visibility into the workloads that were installed by Visual Studio and handle them appropriately.

- `dotnet workload update`
- `dotnet workload list`

Right now the CLI can't see which workloads were installed via VS.  We could:

- Read VS catalog (expensive and not recommended)
- Look at installed packs and infer installed workloads based on that
- Have VS write workload installation records that the CLI can read (probably via a custom MSI that is only installed by VS)

**Comment by dsplaisted** [comment]
#24005 fixed this for `dotnet workload list`

For `dotnet workload update`, we want to get the list of workloads installed by VS before running the update, and then install the new versions of those workloads after updating the manifests.  This will fix the issue where workload update can update manifests and break workloads that were installed by Visual Studio.

**Comment by dsplaisted** [comment]
Update: We want to try to do this in the next feature release, to fix the following:

- Install VS with workload
- Updated workload is released
- Run `dotnet workload update` from command-line
- Workload is no longer installed (and templates don't show up, for example)

This is because `dotnet workload update` will update the workload manifests, but it doesn't see the workloads installed by Visual Studio, so it doesn't install the corresponding packs.

We've already addressed this for `dotnet workload list` so applying the same logic to `dotnet workload update` should not be too hard.

**Comment by baronfel** [comment]
We should also update `dotnet workload uninstall` to have an error message specifically for when a user uninstalles a VS-managed workload with no CLI install manifest. In this case, we should tell the user that they need to uninstall the workload via the VS Installer, and that the CLI command they run had no effect.

**Comment by marcpopMSFT** [comment]
Besides the update command, we'll want to keep an eye out for any other command that results in updated manifests (I'm thinking of install and restore) as anything that updates manifests should update all installed workloads rather than letting them fail.

**Comment by nagilson** [comment]
Should we close this now that everything here is done, or are there more interactions we'd like to support?

We havent added the uninstall message @baronfel mentioned eariler yet I think.

**Comment by baronfel** [comment]
@nagilson let me extract that to a separate issue real quick then we can close this one.

**Comment by nagilson** [comment]
Thank you!
