### ISSUE TITLE
react template fails out of the box with 5.0.401

### ISSUE THREAD

**Issue by sbatten** [dotnet/sdk#21949]
### Describe the bug
With the latest stable tooling, creating a new project with the react template fails with an error of incompatible nuget package.

### To Reproduce

1. Install latest tooling
2. run `dotnet new react -o projName`
🐛 => Unable to resolve 'Microsoft.AspNetCore.SpaServices.Extensions (>= 5.0.10)' for 'net5.0'

This issue repros on a Windows 11 box, but not a macOS device.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by sbatten** [comment]
Turns out this was the solution https://github.com/dotnet/aspnetcore/issues/21920#issuecomment-629738708, but the error does not make it clear that I need to add a source. It feels like it found a package with the wrong target. Also, its very strange that I need to add this source with an out of the box template. 

Especially since I don't see any mention of that here https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-5.0&tabs=netcore-cli

**Comment by marcpopMSFT** [comment]
Catching up on old issues. The default nuget restore experience with dotnet will hit nuget.org. Some customers end up in a situation where their local nuget config doesn't which misses some packages we require for default experiences.  Did you recall getting a specific error code?  The nuget documentation covers this scenario for NU1102: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1102
