### ISSUE TITLE
dotnet pack doesn't include xmlserializer assembly

### ISSUE THREAD

**Issue by Styxxy** [dotnet/sdk#2202]
When forcing assembly to generate XmlSerializer assembly,when packing the project, this XmlSerializer assembly is not included in the nupkg.

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
    <GenerateSerializationAssemblies>On</GenerateSerializationAssemblies>
    <SGenUseProxyTypes>false</SGenUseProxyTypes>
  </PropertyGroup>

</Project>
```

command `dotnet pack myproject.csproj` generates following nuspec (in the obj folder):
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>myproject</id>
    <version>1.0.0</version>
    <authors>myproject</authors>
    <owners>myproject</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.7" />
    </dependencies>
  </metadata>
  <files>
    <file src="c:\users\styxxy\Source\Repos\myproject\myproject\bin\Debug\net47\myproject.dll" target="lib\net47\myproject.dll" />
  </files>
</package>
```

I would expect the XmlSerializer assembly to be included as well.

**Comment by livarcocc** [comment]
@rohit21agrawal can you take a first look here and let us know if the SDK is missing passing something down to pack?

**Comment by Styxxy** [comment]
I created for now nuspec files, though it isn't ideal. Sample nuspec:

```xml
<package>
  <metadata>
    <!-- include all of necessary tags -->
    <references>
      <reference file="myproject.dll" />
    </references>
  </metadata>
  <files>
    <file src="bin\$config$\net47\myproject.dll" target="lib\net47" />
    <file src="bin\$config$\net47\myproject.XmlSerializers.dll" target="lib\net47" />
  </files>
</package>
```
(Typed on my phone.)

Initially I found a workaround by adding a custom target before the _GetProjectFiles target and adding the XmlSerializers assembly, but I encountered the _problem_ when installing the package in a legacy project, that the XmlSerializers asembly is also added as a reference (default nuget adds all DLL's in the package as a reference, except *.resources.dll files).

**Comment by Styxxy** [comment]
Doesn't matter whether using ("old") way or new way (using nuget package).

```xml
<!-- "old" way -->
  <PropertyGroup>
    <GenerateSerializationAssemblies>On</GenerateSerializationAssemblies>
    <SGenUseProxyTypes>false</SGenUseProxyTypes>
</PropertyGroup>

<!-- "new" way (see: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator ) -->
<ItemGroup>
  <PackageReference Include="Microsoft.XmlSerializer.Generator" Version="1.0.0" />
  <DotNetCliToolReference Include="Microsoft.XmlSerializer.Generator" Version="1.0.0" />
</ItemGroup>
```

**Comment by rohit21agrawal** [comment]
This is currently not supported, we will consider this feature ask for a future release.
@Styxxy  you don't need to revert to a nuspec. You can use these extension points/targets to add the serializer assembly to your package:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificbuildoutput

@livarcocc please feel free to move this issue to nuget.

**Comment by Styxxy** [comment]
@rohit21agrawal 
That does partially the trick. When installing into a project that uses packages.config, the XmlSerializer assembly is still referenced though (not that it breaks anything, it isn't nice though).

```xml
<PropertyGroup>
  <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetMyPackageFiles</TargetsForTfmSpecificBuildOutput>
</PropertyGroup>

<Target Name="GetMyPackageFiles">
  <ItemGroup>
    <BuildOutputInPackage Include="$(OutputPath)$(AssemblyName).XmlSerializers.dll" />
  </ItemGroup>
</Target>
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6890
