### ISSUE TITLE
Packing a .NET Core Exe shouldn't include package dependency on Microsoft.NETCore.App

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2204]
Today, if you pack an Exe project that targets netcoreapp2.0 or higher, the resulting package has a dependency on Microsoft.NETCore.App.  If you pack a library, you don't get the dependency in the package.

I think the dependency is included for Exes to support project tools.  However, we would like to reconsider this default.

See https://github.com/Microsoft/msbuild/issues/3228 where it's causing issues with prodcon and MSBuild.

**Comment by Petermarcu** [comment]
Correct, nothing should have an explicit reference to netcoreapp's package. That should be the default and we should tell people that need it that they should add the reference even though nobody should need to.

**Comment by dsplaisted** [comment]
@wli3, would you like to pick this up?  The implicit reference to Microsoft.NETCore.App should have PrivateAssets=All [unless the PackageType property is set to DotnetCliTool](https://github.com/dotnet/sdk/issues/2364#issuecomment-400380323).

@KathleenDollard We should communicate this as a breaking change for DotnetCliTools that don't set the PackageType property.  Given the prevalence of issues that would be fixed by the change and the fact that there is a workaround (set the property) for the breaking change, I think it's worth doing.

**Comment by wli3** [comment]
@dsplaisted will this cause the similar problem of testing global tools -- Microsoft.NETCore.App won't flow to the other project? Although I don't think so, that project should have its own Microsoft.NETCore.App

**Comment by dsplaisted** [comment]
If anything, I think this could fix issues testing global tools.  We may have fixed it in another way already for that case though.

**Comment by Tadimsky** [comment]
@dsplaisted Is the recommended workaround for now (until 2.2 is ready to install on our CI machines) to do the set it as PrivateAssets?

**Comment by Tadimsky** [comment]
Looks like it doesn't work to set `PrivateAssets="All"`:
```
9>C:\Users\joschm\Intentional\services\src\Tests\ContentServiceFrontend.Tests\ContentServiceFrontend.Tests.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.1.2 to 2.1.0. Reference the package directly from the project to select a different version. 
9>C:\Users\joschm\Intentional\services\src\Tests\ContentServiceFrontend.Tests\ContentServiceFrontend.Tests.csproj : error NU1605:  ContentServiceFrontend.Tests -> ContentServiceFrontend -> Microsoft.NETCore.App (>= 2.1.2) 
9>C:\Users\joschm\Intentional\services\src\Tests\ContentServiceFrontend.Tests\ContentServiceFrontend.Tests.csproj : error NU1605:  ContentServiceFrontend.Tests -> Microsoft.NETCore.App (>= 2.1.0)
```

Any ideas?
