### ISSUE TITLE
Task GenerateAssemblyInfo should not run in the WPF temporary project

### ISSUE THREAD

**Issue by jviau** [dotnet/sdk#2206]
Currently `GenerateAssemblyInfo` runs during WPF markup compilation. This breaks incremental build and pollutes the obj directory with many `{hash}.AssemblyInfo.cs` files. Instead, the following should happen:

1) Make `GenerateAssemblyInfo` run before `MarkupCompilePass1`
2) Do not run `GenerateAssemblyInfo` inside the WPF temporary project.
3) Re-include the original `AssemblyInfo.cs` generated from the original project in the WPF temporary project.
  * Currently, `$(GeneratedAssemblyInfoFile)` is calculated using `$(MSBuildProjectName)`, this obviously will not work. It may need to change to use `$(AssemblyName)`

**Comment by livarcocc** [comment]
Is this using the new SDK style project? We don't currently support WPF projects in it.
