### ISSUE TITLE
PublishReadyToRunComposite and PublishReadyToRunUseCrossgen2 fails

### ISSUE THREAD

**Issue by ocalvo** [dotnet/sdk#22067]
### Describe the bug
When using this publishing profile:
```
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Platform>arm64</Platform>
    <RuntimeIdentifier>win10-arm64</RuntimeIdentifier>
    <PublishDir>bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\</PublishDir>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>False</PublishSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <PublishReadyToRunUseCrossgen2>True</PublishReadyToRunUseCrossgen2>
    <PublishReadyToRunComposite>True</PublishReadyToRunComposite>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
```
Build fails with:
```
C:\Program Files\dotnet\sdk\5.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(316,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target p
latform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [C:\src\WinUI-Samples\Samples\AllSamples\MyApp\MyApp.csproj]
```

### To Reproduce

1. Remove these comments: 
1.1. [arm64](https://github.com/microsoft/WinUI-Samples/blob/main/Samples/AllSamples/MyApp/Properties/PublishProfiles/win10-arm64.pubxml#L14)
1.2. [x64](https://github.com/microsoft/WinUI-Samples/blob/main/Samples/AllSamples/MyApp/Properties/PublishProfiles/win10-x64.pubxml#L14)
1.3. [x86](https://github.com/microsoft/WinUI-Samples/blob/main/Samples/AllSamples/MyApp/Properties/PublishProfiles/win10-x86.pubxml#L14)
2. Execute [build](https://github.com/microsoft/WinUI-Samples/blob/main/build.ps1)

### Further technical details
- Include the output of `dotnet --info` : `5.0.402`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `16.11.4`
- Attached bin log [wap.Release.zip](https://github.com/dotnet/sdk/files/7349597/wap.Release.zip)

**Comment by AntonLapounov** [comment]
The error message has been improved in #24324.
