### ISSUE TITLE
repeat sdks, runtimes list 

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sdk#22118]
### Describe the bug
![image](https://user-images.githubusercontent.com/5714438/137653383-5c2dea74-21b9-4a0d-bb32-c3002738c9a3.png)

**Comment by KalleOlaviNiemitalo** [comment]
This looks similar to <https://github.com/dotnet/runtime/issues/59833>.

**Comment by Varorbc** [comment]
Duplicate of dotnet/runtime#59833
