### ISSUE TITLE
Manually change Framework in runtimeconfig.json?

### ISSUE THREAD

**Issue by Alovchin91** [dotnet/sdk#22128]
Hi, I'm working on upgrading our legacy Windows app to .NET 5.

In our legacy architecture, we used to have WinForms and WPF in many assemblies. At the same time, we had a headless version of our app that was running the same assemblies but detouring the UI code in runtime. That worked well on Linux under Mono.

In .NET 5, I see that as soon as I enable WPF and/or WinForms for the project, its target Framework changes to `Microsoft.WindowsDesktop.App`. With this, the app cannot be run on Linux.

However, if I manually change the Framework in runtimeconfig.json to `Microsoft.NETCore.App`, the app loads and our detour code seems to work as it did before.

I wonder if there's an official/supported way to implement this scenario?

Thanks!

**Comment by vitek-karas** [comment]
I completely understand that rewriting the app is not a good option.

I could see this being added as some kind of expert level feature. We just don't have any such functionality available now in the SDK.

**Comment by Alovchin91** [comment]
@vitek-karas  Thank you for the response!

What are our options outside the SDK? I can manually change the `runtimeconfig.json`, but then we'll try to load metadata for some assemblies, for example `System.Windows.Forms`. This assembly existed on Mono, and we know not to load it in runtime.

What are our steps? Copy the assembly from WindowsDesktop SDK? 🤔

**Comment by kasperk81** [comment]
there is `<DisableWinExeOutputInference>true</DisableWinExeOutputInference>` and other similar properties which you can try setting in .csproj along with `<UseWpf>true</UseWpf>` to control behavior in certain way. i _think_ this should work, but can't say for sure, since there are no repro steps..

**Comment by Alovchin91** [comment]
@kasperk81  Thanks for the suggestion, but I believe this is a different story...

@vitek-karas Maybe a more appropriate question would be: will there be a new Mono release that would be able to run .NET 6 assemblies?

**Comment by kasperk81** [comment]
or you can make a sample and push to a github repo, so we all understand what error you are running into..

**Comment by vitek-karas** [comment]
> Maybe a more appropriate question would be: will there be a new Mono release that would be able to run .NET 6 assemblies?

I'm not aware of a release which would look like mono did in the past. I could be wrong (@lambdageek  probably knows more details on release of the mono runtime). That said, I don't think it would deliver what you're asking for. Mono is now just a different runtime implementation (just like CoreCLR) which is more suited for some specific form factors. Both runtimes share the same base libraries.

If the goal is to be able to run .NET Framework assemblies with WPF/WinForms code in them on .NET 6, this is not a runtime problem, it's a problem of assemblies available in the framework. .NET 6 does provide these outside of Windows.

**Comment by Alovchin91** [comment]
> If the goal is to be able to run .NET Framework assemblies with WPF/WinForms code in them on .NET 6, this is not a runtime problem, it's a problem of assemblies available in the framework. .NET 6 does provide these outside of Windows.

I would say that the goal is to be able to read Type metadata from WinForms and (probably) WPF assemblies on OS other than Windows. We can migrate to .NET 6, and we don't actually _run_ WinForms/WPF code on non-Windows OS, but we gather Type metadata, and the assemblies indeed _contain_ WinForms/WPF code.

**Comment by vitek-karas** [comment]
You're right, but as mentioned above the SDK/runtime should not make that distinction as it can't know if the code will be executed or not.

What we did for some other libraries/API is to provide a "not implemented" versions of the libraries for non-Windows. The APIs are available everywhere, but typically throw `PlatformNotSupported` exception when called on non-Windows (for example). But this effort was scoped mostly to the `netstandard2.0` API set and maybe a small number of other APIs. It was not applied to WPF/WinForms as there are comparatively very few use cases for that. Adding something like that would solve the problem you have. That said, I don't think we're going to do that as the need for this is comparatively very low.

For WinForms the runtime would be OK to load these assemblies even on Linux for metadata just fine - so for that it's basically a SDK/packaging blocker. If you somehow made the app to include the WinForms assemblies even on Linux, the code would load just fine (it would obviously not run).

For WPF it's more complicated as some assemblies are C++/CLI and those won't load on non-Windows at all - even just for metadata.

**Comment by Alovchin91** [comment]
Thanks! That's probably a way forward for us indeed 🙂 

One more question: What will happen if we generate `ref` assemblies, say, using JB’s [refasmer](https://github.com/JetBrains/Refasmer)?

**Comment by KalleOlaviNiemitalo** [comment]
The C# compiler supports [PublicSign](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-options/security#publicsign) for adding a fake strong-name signature without needing the private key. However, if you generate the assembly in some other way, then you cannot use C# compiler options. [AL (Assembly Linker) task](https://docs.microsoft.com/en-us/visualstudio/msbuild/al-assembly-linker-task?view=vs-2019) does not appear to have a similar option, but perhaps you can first use the `DelaySign` parameter to place the public key into the assembly, and then tweak the flags in the header somehow.

If .NET Runtime detects that you have a reference assembly and refuses to load it for execution, the mock option of refasmer might fix that problem.

**Comment by vitek-karas** [comment]
Runtime will not allow loading assemblies which have the `ReferenceAssemblyAttribute` on them. It seems that refasmer adds this, but maybe there are ways to tell it not to do that. In that case it "might" work. But I would not bet on it. JIT may still try to actually inline the method, even if it's never called in execution. If the tool could generate an empty method body (or throw method body), that should work then.

**Comment by KalleOlaviNiemitalo** [comment]
In refasmer, [MockupMethodBody.cs](https://github.com/JetBrains/Refasmer/blob/ad16c5fe807e2f850332fe265389c736e784b1d3/src/Refasmer/Importer/MockupMethodBody.cs) generates a method body that throws NotImplementedException. That should be fine.

**Comment by Alovchin91** [comment]
Thanks a lot! I'm gonna try this workaround 👍

**Comment by sfoslund** [comment]
@Alovchin91 it sounds like you found a workaround, is that working for you? Are there any further issues here or should I close this out?

**Comment by Alovchin91** [comment]
@sfoslund  Hi, sorry for the late reply. Yes, I'd say we've found a workaround. We have to manually patch `runtimeconfig.json` and `deps.json` to include dependency on mocked System.Windows.Forms.dll, but that should work for us for now.

Please feel free to close this issue. I'll reopen it shall I need further assistance 🙂 Thank you!

**Comment by AraHaan** [comment]
What if you needed to manually have the project use the runtimeconfig.json file manually created because the SDK incorrectly list the wrong framework last which is a problem because that runtimeconfig.json is itself part of another framework which then gets used in a project which results in the the host (fxr) to incorrectly look for hostpolicy in the wrong framework? I tried to work around it myself by adding the NETCore.App framework last manually to no success as the runtimeconfig.json file still generates with it listed first instead of last.
