### ISSUE TITLE
'libhostpolicy.so' required to execute the application was not found

### ISSUE THREAD

**Issue by emanueleleoni** [dotnet/sdk#2214]
I created an MVC .Net Core 1.1 application. It works on windows and I'd like to run in my raspberry py too.
But It doesn't work.

## Environment:
1. VS17 enterprise
2. Mvc .net core 1.1
3. Raspberry pi with Debian 9.4
4. Repo on github

## Expected behavior
After publishing in windows for linux-arm I have pull my repo into raspberry, but when 
I run 
`dotnet  myapp.dll`
I have the error:
_A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in [path]_

## Actual behavior
It doesn't work and I don't know how to solve

**Comment by nguerrera** [comment]
`linux-arm` is not supported by .NET Core 1.1 and unfortunately, the detection of invalid unsupported RIDs in 1.x is not there: https://github.com/dotnet/sdk/issues/1464

I suggest moving to .NET Core 2.0 for Raspberry Pi.  See https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md
