### ISSUE TITLE
Add additional details on the workload version in dotnet workload --list

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#22148]
### Is your feature request related to a problem? Please describe.
Customers want to know the version of what they have installed. Unfortunately, multiple packs live within a single workload and even that is tied to a manifest version as the workload itself doesn't have a version.  Likely needs PM guidance.  Should this be a separate parameter? Is manifest version enough?  Should it list out the version of every pack installed related to that workload?

Hypothesis: The manifest version is enough as that's used for rollback updates.

### Describe the solution you'd like
Add a column that shows the manifest version when adding an additional parameter to the list command (--verbosity).  Could include pack versions on verbosity diagnostics but that may not be a priority.

**Comment by baronfel** [comment]
Counter-proposal: make this `dotnet workload --info`, and emit a structured representation of installed workloads, workload install type (MSI or File-based), key workload locations, manifest versions, etc.

Reasoning:
We need most/all of this information for issue triage, and so having a simple gesture to get all of this information easily would help smooth the triage process.

**Comment by davidortinau** [comment]
@baronfel @marcpopMSFT now that .NET MAUI is GA, the "what version am I on" has only gotten louder. Are we on track for the 6.0.4xx milestone?

**Comment by marcpopMSFT** [comment]
Assigning to Noah to take a look. I think including at least the manifest version (example 32.0.415 if I installed [android](https://www.nuget.org/packages/Microsoft.NET.Sdk.Android.Manifest-6.0.300)) in list at a minimum. Chet may have some ideas of how to add this to the --info details as well but it should be in both, not one or the other (and we don't need to block one on the other).

I don't know whether to include the manifest feature band but that might be useful too (like 6.0.300 for Android in my example above).
