### ISSUE TITLE
[Loc]With net6 RTM SDK installed on locale OS, overtranslate issue occurs when runing "dotnet publish -r win-x64" in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#22166]
Install NET6 RTM SDK: 6.0.100-rtm.21515.2 on locale OS e.g ZH-CN
dotnet new console -o myconsole
dotnet publish -r win-x64

Expected Result:
Strings localized well

Actual Result:
Overtranslate issue happens

SC:
![image](https://user-images.githubusercontent.com/65637796/137872021-6fd55983-c96a-4bc7-8ebb-1118456fc4e1.png)

EN:
![image](https://user-images.githubusercontent.com/65637796/137876835-6497d8d7-f200-4dcc-9bbb-62f85900dd52.png)

DE（not repro）
![image](https://user-images.githubusercontent.com/65637796/137877997-d0966283-44c3-49fe-9583-421bfe2aaf92.png)

Note:
Strings '--runtime' '--self-contained' '--no-self-contained'' should not be localized

For other locale language, please help to check synchronously。

**Comment by richaverma1** [comment]
Adding @jonfortescue for Marc's question.

**Comment by vdanche** [comment]
The issue has been fixed on NET7 RC 2 SDK on SC
![image](https://user-images.githubusercontent.com/65637796/191706440-1b8d41ad-7392-41d1-9c96-33c3bcf5783a.png)
