### ISSUE TITLE
Request for Ubuntu 21.10 apt repo

### ISSUE THREAD

**Issue by akdor1154** [dotnet/sdk#22232]
Hey guys, any change you could publish packages for Ubuntu 21.10? Latest at list config (https://packages.microsoft.com/config/ubuntu/) and apt repos themselves (https://packages.microsoft.com/ubuntu/) are 21.04 :(

(for the record, the 21.04 packages install and run fine)

**Comment by ptrkbmn** [comment]
The documentation was already updated. My guess is that it won't take long until the Ubuntu 21.10 packages are available.

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2110-

**Comment by ptrkbmn** [comment]
Technically I was wrong. But the Ubuntu 21.10 packages are finally available now.

https://packages.microsoft.com/config/ubuntu/21.10/packages-microsoft-prod.deb
