### ISSUE TITLE
Cannot update dotnet workload maui on mac

### ISSUE THREAD

**Issue by juanlao** [dotnet/sdk#22267]
### Describe the bug
Cannot update dotnet workload maui on mac.

### To Reproduce

1. Remove previous versions of previews by deleting /usr/local/share/dotnet/ 
2. Install the .NET 6 release: https://dotnet.microsoft.com/download/dotnet/6.0
3. Run sudo dotnet workload install maui
4. Run dotnet workload list
5. A message indicating "Updates are available for the following workload(s): maui. Run 'dotnet workload update' to get the lates
6. Run sudo dotnet workload update
7. See a message: "Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation ."
8. "Successfully updated workload(s): maui." appears
9. Run again dotnet workload list
10. The same message indicating "Updates are available...." appears

### Further technical details
- Include the output of `dotnet --info`
- .NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.2.21505.57/

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  6.0.100-rc.2.21505.57 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by sfoslund** [comment]
Ping @juanlao are you still seeing this issue?

**Comment by juanlao** [comment]
Hi!
Nope, i cleaned all the old previews versions and seems now it is all working well!
Thanks!
