### ISSUE TITLE
[2.1-rc1] dotnet clean fails when obj folder is missing

### ISSUE THREAD

**Issue by mariusGundersen** [dotnet/sdk#2226]
**How to reproduce**
* Run `dotnet new classlib` in an empty folder
* Delete the obj folder
* Run `dotnet clean`

**What happens**
* Clean fails
* obj folder is created with empty folders

**What should happen**
* Nothing, project is already clean

This is an issue on our CI server, where we run `dotnet clean` as the first step of every build, and then run `dotnet restore` as the second step. It now fails on the initial build, when it clones the repo and there is no obj folder.

**Comment by livarcocc** [comment]
What version of the SDK is this reproing with? What error message are you seeing? I tried this and clean succeeds, though it does re-create the obj folder structure, it is all empty and without any files.

**Comment by gcelet** [comment]
I can repro this problem with these steps:

```powershell
PS F:\dotnet-sdk-issue-2226> dotnet --version
2.1.300-rc1-008673
PS F:\dotnet-sdk-issue-2226> dotnet new classlib
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj...
  Restoring packages for F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj...
  Generating MSBuild file F:\dotnet-sdk-issue-2226\obj\dotnet-sdk-issue-2226.csproj.nuget.g.props.
  Generating MSBuild file F:\dotnet-sdk-issue-2226\obj\dotnet-sdk-issue-2226.csproj.nuget.g.targets.
  Restore completed in 167,79 ms for F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj.

Restore succeeded.

PS F:\dotnet-sdk-issue-2226> rmdir obj

Confirm
The item at F:\dotnet-sdk-issue-2226\obj has children and the Recurse parameter was not specified. If you continue, all children will be removed with the item. Are you
sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
PS F:\dotnet-sdk-issue-2226> dotnet clean
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 08/05/2018 18:33:36.
     1>Project "F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj" on node 1 (Clean target(s)).
     1>_CheckForNETCoreSdkIsPreview:
         You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
       CoreClean:
         Creating directory "obj\Debug\netstandard2.0\".
     1>C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(197,5): error : Assets file 'F:\dotnet-sdk-issue-2226\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj]
     1>Done Building Project "F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj" (Clean target(s)) -- FAILED.

Build FAILED.

       "F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj" (Clean target) (1) ->
       (ResolvePackageAssets target) ->
         C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(197,5): error : Assets file 'F:\dotnet-sdk-issue-2226\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [F:\dotnet-sdk-issue-2226\dotnet-sdk-issue-2226.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.40
PS F:\dotnet-sdk-issue-2226>
```

**Comment by livarcocc** [comment]
You are right, I was trying with preview2. This seems like a regression in RC1. @nguerrera can you take a look?

**Comment by gcelet** [comment]
i confirm these use to work with sdk 2.1 preview2 but i uninstalled it these morning because i installed rc1.
for the moment i use a global.json with pinned sdk to 2,1.105: it's work with this sdk too.

**Comment by nguerrera** [comment]
Looks like this is the source of the regression:

https://github.com/dotnet/sdk/pull/2010/files#diff-726c4af93875efa855c29e94f7c0b33eR126

**Comment by nguerrera** [comment]
^cc @dsplaisted 

Basically, we used to condition package resolution on the existence of the assets file and that's why we got away with doing package resolution on clean. It is really unfortunate that package resolution happens on clean at all. @peterhuene did some work to make it not output assets log messages on clean. It would be better to not run it all during clean, but that's not trivial.

1. Clean needs to run AssignProjectConfiguration to Clean project references with the correct configuration.
2. ResolvePackageDependenciesBeforeBuild needs to run before AssignProjectConfiguration so that it can create transitive project references from the assets file.

Now, we don't actually need transitive project references to clean. We still get a clean closure by cleaning only our direct references and letting them clean theirs recursively.

**Comment by Petermarcu** [comment]
@nguerrera blocking RTM?

**Comment by nguerrera** [comment]
@Petermarcu TBD I suppose, but it is a regression and pretty bad. I'm doing some validation and will send to ship room this afternoon for the call.

**Comment by gcelet** [comment]
thanks for this quick fix: waiting the next release to test it.
great work @nguerrera
