### ISSUE TITLE
Port dotnet/sdk SourceBuild patches from dotnet/installer

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#22281]
In order to get OmniSharp working with a source-built .NET SDK, we need to build Microsoft.NET.Build.Tasks for netfx. However, we have some code that explicitly removes these assemblies from building for netfx:

https://github.com/dotnet/sdk/blob/7bffe252efd9993b46096d18d7346566bd31ea20/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj#L15-L16

https://github.com/dotnet/sdk/blob/7bffe252efd9993b46096d18d7346566bd31ea20/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj#L18-L19

This causes OmniSharp to not work with a 6.0 source-built SDK.

In order to work around this for source-build, we are [introducing a patch for `6.0.0`](https://github.com/dotnet/installer/pull/12497). We should port these patches into the dotnet/sdk repo proper.

**Comment by marcpopMSFT** [comment]
@MichaelSimons is this done now and can be closed?

**Comment by marcpopMSFT** [comment]
@MichaelSimons?

**Comment by MichaelSimons** [comment]
Yes - done.
