### ISSUE TITLE
Dotnet core stream resources does not work when built using dotnet, but works using msbuild 

### ISSUE THREAD

**Issue by amrmahdi** [dotnet/sdk#2231]
A project with embedded stream resources works fine when built using msbuild. But if build using dotnet build, it produces the following exception 

```console
Unhandled Exception: System.InvalidOperationException: Resource 'Silence' was not a Stream - call GetObject instead.
   at System.Resources.ResourceManager.GetStream(String name, CultureInfo culture)
   at dotnetcore.resources.Program.Main(String[] args) in E:\dotnetcore.resources\Program.cs:line 13
```

### MSBuild (works)
1. msbuild
2. dotnet run

### dotnet (does not work)
1. dotnet run

### dotnet version
2.1.300-preview2-00853

I've noticed that when using MSBuild, **Al.exe** is used to generate the satellite assemblies, which maybe why it works when building using MSBuild.

[dotnet.resources.zip](https://github.com/dotnet/sdk/files/1990751/dotnet.resources.zip)

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#3310
