### ISSUE TITLE
dotnet SDK discovery accepts empty folders as valid SDKs

### ISSUE THREAD

**Issue by g-gar** [dotnet/sdk#22322]
### Describe the bug
Having an empty folder with the highest version number under `dotnet/sdk/` folder triggers the cli to find a `dotnet.dll` inside given folder. This results in the message `Found .NET SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\x.x.x\dotnet.dll]` being shown when trying to execute any dotnet command.

Found after running the Visual Studio 2022 preview version uninstal tool.

### To Reproduce
Just create an empty folder with name `x.0.0` where `x` is `1 + previous higher version present`, under `C:\Program Files\dotnet\sdk\` (x=7, as of october 2021).

### Exceptions (if any)
 * `Found .NET SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\x.x.x\dotnet.dll]`

### Further technical details
- Applies to all platforms.

**Comment by marcpopMSFT** [comment]
@vitek-karas This is on the runtime host side I believe.

**Comment by vitek-karas** [comment]
This is similar to https://github.com/dotnet/runtime/issues/48180 but for SDKs.

The main question is: This should really only happen if there's a problem with installers. Should the runtime compensate for it?

**Comment by DotNetSparky** [comment]
This happened to one machine today after uninstalling 6.0.  Deleting the empty folder fixed it.  I've found relying on directories to be successfully deleted is... hard... (anti-virus and such seem to sometimes keep a lock just a moment too long preventing the deletes sometimes, at least that's my "theory" 🙃) -- I definitely think it would be a good idea to ignore the folder if it's empty and not error.

**Comment by steveharter** [comment]
The "found .NET SDK..." also occurred to me; there was a remaining "Roslyn" folder in a 6.0.100 SDK folder but nothing else. Not sure how it ended up in this state, although it could have been related to updating Visual Studio since that is the only action I recall.

**Comment by Thealexbarney** [comment]
I've also hit this issue a few times. In my case I was setting the SDK version from global.json while running from a local SDK installed via the `dotnet-install` script. The global install had a leftover SDK folder of the version that was specified in the global.json file. Because of that it was trying to use the global install instead of the local install, resulting in the error.
