### ISSUE TITLE
Port PackageValidation flaky build failure fixes to 6.0

### ISSUE THREAD

**Issue by dagood** [dotnet/sdk#22353]
* https://github.com/dotnet/runtime/pull/60847
* https://github.com/dotnet/sdk/pull/22277

This would help source-build reliability in particular (https://github.com/dotnet/source-build/issues/2501) and allow removing this workaround:

* https://github.com/dotnet/runtime/pull/60881

**Comment by ericstj** [comment]
@safern @dagood can this be closed, or have these not yet been ported to 6.0?  Adjusting to 6.0.2xx

**Comment by dagood** [comment]
Seems like it can be closed. @lbussell @MichaelSimons correct me if I'm wrong.

**Comment by ericstj** [comment]
FWIW I don't see @safern's fixes in 6.0 codebase.

**Comment by dagood** [comment]
Ah, yep, I must have misread some PRs.

**Comment by joperezr** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/66635
