### ISSUE TITLE
Workloads should be able to control the relative import order of .props and .targets

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#22358]
Right now the order that the WorkloadManifest.targets and AutoImport.props files are imported is not defined.  However, workloads may need to have dependencies on what the evaluation import ordering of these files are.

An example of this is that the Maui workloads will probably want to remove implicit usings that are added by the iOS and Android workloads (since they all define `Button`, for example).

So we should probably define what the import order is by default (ie alphabetical), and add a way to allow the workload manifests to specify that something should be evaluated after something else.

**Comment by marcpopMSFT** [comment]
@Redth do you know if this is still something that Maui needs investigation on?

**Comment by Redth** [comment]
@mattleibow or @jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
@mhutch might remember the details, but I think this was a problem about trying to control the order of implicit global usings in workloads. It might allow for a better general design for these. This is probably a .NET 7 or future task.

**Comment by dsplaisted** [comment]
Fixed with https://github.com/dotnet/sdk/pull/28627
