### ISSUE TITLE
[Feature Request] Nuget package links in `dotnet list package --outdated`

### ISSUE THREAD

**Issue by lonix1** [dotnet/sdk#22366]
### Is your feature request related to a problem? Please describe.
The [command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package#description) `dotnet list package --outdated` shows something like this:

````
The following sources were used:
   https://api.nuget.org/v3/index.json

Project `Foo` has the following updates to its packages
   Top-level Package      Requested   Resolved   Latest
   > Microsoft.ML         1.4.0       1.4.0      1.5.0-preview
````

This is not friendly. It would be helpful to include a link to the nuget repository.

### Describe the solution you'd like
Another column with a link to the nuget repo. For example:
````
The following sources were used:
   https://api.nuget.org/v3/index.json

Project `Foo` has the following updates to its packages
   Top-level Package      Requested   Resolved   Latest          Link
   > Microsoft.ML         1.4.0       1.4.0      1.5.0-preview   https://www.nuget.org/packages/Microsoft.ML
````

In many cases this is run in a terminal and we could click the link to go to that page and read the release notes, or if they don't exist, to then click to the github repo and read the release notes.

### Additional context
no

**Comment by lonix1** [comment]
@erdembayar Is https://github.com/NuGet/Home/issues/7752 the proper issue for this?

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://github.com/NuGet/Home/issues/7752#issuecomment-824842843> and <https://github.com/NuGet/Home/issues/7752#issuecomment-1029290671>, adding new columns to the human-readable output is out of scope for that issue.

**Comment by lonix1** [comment]
@KalleOlaviNiemitalo Thanks, then I'll have to make a new issue there.
