### ISSUE TITLE
BUG: FileVersion, ProductVerison is missing for Wrapper-Exe in .net 6 RC2

### ISSUE THREAD

**Issue by Scordo** [dotnet/sdk#22396]
Hi together, 

I've created a console app with .net 6 rc2 and published it for win-x64 with the following options 
- IncludeNativeLibrariesForSelfExtract=true
- PublishTrimmed=true
- PublishSingleFile=true
- --self-contained

The generated wrapper-exe does not contain a FileVersion or a ProductVersion.
The same thing in .net 5 emits both correctly.

We have an existing app which checks these information at rubntime and now crashes in .net 6.
Seems like a bug to me

Thanks!
Scordo

**Comment by eerhardt** [comment]
cc @agocke @vitek-karas

**Comment by vitek-karas** [comment]
Can you please share the exact version - ideally run `dotnet --info`?
Can you please look at the `app.dll` (the name of your application) produced in the binaries if it has version information?
Can you please try to just build the app (`dotnet build`) and look if the generated `exe` has version information?

I tried this locally on a simple `dotnet new console` and everything seems to work correctly.

**Comment by Scordo** [comment]
> Can you please share the exact version - ideally run `dotnet --info`? Can you please look at the `app.dll` (the name of your application) produced in the binaries if it has version information? Can you please try to just build the app (`dotnet build`) and look if the generated `exe` has version information?
> 
> I tried this locally on a simple `dotnet new console` and everything seems to work correctly.

We're using the latest. Net 6 rc2 preview sdk docker image in a kubernetes build.

There is no app.dll, because its published as a single executable - maybe you missed that. I can tell you tomorrow which image we're exactly using.

**Comment by vitek-karas** [comment]
The app.dll is there even when you publish, just not in the publish output directory (for win-x64 it would be in something like `bin/Release/net6.0/win-x64`). But you can also get to it by just running `dotnet build` and look at the output of that (that should have both the `.dll` and the `.exe`).

Please note that the product version/file version will only be written to the `.exe` if the `dotnet publish` is running on Windows. It's a known current limitation (as the publish uses Win32 APIs to set these values, and those are obviously not available on non-Windows). This limitation existed in .NET 5 as well.. so if you're using the same infra to build/publish that should not make a difference.

**Comment by Scordo** [comment]
> Please note that the product version/file version will only be written to the `.exe` if the `dotnet publish` is running on Windows. It's a known current limitation (as the publish uses Win32 APIs to set these values, and those are obviously not available on non-Windows). This limitation existed in .NET 5 as well.. so if you're using the same infra to build/publish that should not make a difference.

I think this is the problem. .Net 5 was build on windows machines. Can you point me to the documentation of that limitation? :)

**Comment by vitek-karas** [comment]
I actually don't know if this is documented - could very well be a missing bit in the docs. Just curious (to make sure we fix it in the right place) - where did you go to look this up? (if anywhere).

**Comment by Scordo** [comment]
> I actually don't know if this is documented - could very well be a missing bit in the docs. Just curious (to make sure we fix it in the right place) - where did you go to look this up? (if anywhere).

Nowhere, googelt for it but did not find anything - Did not expect this to be an expected limitation. In my opinion this is a bug :(

**Comment by vitek-karas** [comment]
I agree it's a "bug" - in fact it's an old one: https://github.com/dotnet/runtime/issues/3828

**Comment by Scordo** [comment]
Your google-foo is much stronger than mine :-D
Any chance this will get fixed? :-s

**Comment by vitek-karas** [comment]
> Your google-foo is much stronger than mine :-D

Not really - this is not a new question - so I know that there's a bug for it... and I know which area it belongs to. (I would never have found it via web search).

I don't know if/when this will get fixed. It's actually not that simple to fix and so far the priority has never been high enough.

**Comment by marcpopMSFT** [comment]
Seems like dotnet/runtime#3828 is already tracking this issue so I suggest moving the discussion there and closing out this issue.  Thanks.
