### ISSUE TITLE
`workload install android` fails on Ubuntu (works on Win/Mac)

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/sdk#22411]
`dotnet workload install android` works on `windows-latest`, `macos-latest` but is failing on `ubuntu-latest` on GitHub actions.

.NET SDK installed `6.0.100-rc.2.21505.57`. [Installation is part of the workflow](https://github.com/getsentry/sentry-dotnet/pull/1288/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721).

```
  dotnet workload install android
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_11.0.13_x64: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.13/x64
    JAVA_HOME_11_0_13_X64: /opt/hostedtoolcache/jdk/11.0.13/x64
    DOTNET_ROOT: /home/runner/.dotnet

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Installing workload manifest microsoft.net.sdk.maui version 6.0.101-preview.9.1843…
Installing pack Microsoft.Android.Sdk version 31.0.101-preview.9.16...
Workload installation failed. Rolling back installed packs...
Installing workload manifest microsoft.net.sdk.maui version 6.0.101-preview.9.1805…
Installation rollback failed: Failed to install manifest microsoft.net.sdk.maui version 6.0.101-preview.9.1805: The transaction has aborted..
Rolling back pack Microsoft.Android.Sdk installation...
Workload installation failed: microsoft.android.sdk.linux::31.0.101-preview.9.16 is not found in NuGet feeds api.nuget.org/v3/index.json".
```

GitHub actions: https://github.com/getsentry/sentry-dotnet/runs/4061658135?check_suite_focus=true

**Comment by marcpopMSFT** [comment]
The wasm-tools workload is the only one supported on Linux today.  Maui workloads are only supported on macOS and windows. @Redth for any details as to when Linux might be supported.

**Comment by bruno-garcia** [comment]
I'm only interested on Android at this point. Shouldn't I be running `workload install android`?
What would be the advise to get only Android working on Win/Mac/Linux?

**Comment by davidortinau** [comment]
@bruno-garcia since we don't currently support Linux as either a development platform or a runtime target, we don't publish Linux installers. 

Your best option is to build from source. This resource may be helpful:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/building/unix/instructions.md

**Comment by KyleC69** [comment]
An Android project can be created on a Linux platform but the Workload required to use it cannot? And there is no indication of this limitation anywhere during the process. Perhaps the dotnet workload search command can check the OS and not list the workloads that are not valid. Some sort of helpful message would seem prudent.

**Comment by akoeplinger** [comment]
Interesting, I wonder what GitHub Actions is doing with /tmp that causes this

**Comment by mattjohnsonpint** [comment]
Not sure exactly, but I stumbled upon several issues on other repos with the same problem and solution, such as https://github.com/actions/setup-elixir/issues/24 and https://github.com/StackStorm/st2/issues/3876.  (I couldn't locate a main issue for this with GitHub.)
