### ISSUE TITLE
Shared OutputPath for whole solution is causing build failure

### ISSUE THREAD

**Issue by simonjstanford** [dotnet/sdk#22438]
Hi,

Please try the attached example and try to rebuild the whole solution. I'm getting three errors - missing runtimeconfig.dev.json, deps.json and  runtimeconfig.json files.

It contains two projects, one referencing the other. The issue seems to be that both projects are set to use the same OutputPath and both have an OutputType of `Exe`.

```
<OutputPath>..\bin\Debug\</OutputPath>
<OutputType>Exe</OutputType>
```

I'm using Visual Studio 16.11.5 and .NET 5.0.402.

I found that with this zip file the first rebuild seems to be successful and then subsequent builds fail.

[OutputPathTest.zip](https://github.com/dotnet/core/files/7454265/OutputPathTest.zip)

**Comment by sfoslund** [comment]
@simonjstanford we usually recommend against sending multiple projects to the same output path. Are you able to change your solution so that each project has its own output directory?

**Comment by simonjstanford** [comment]
Hi, yes I've got round this issue by having separate bin directories for each project and then publishing into a single directory. I think this probably makes more sense for our build process anyway.

**Comment by sfoslund** [comment]
Great, I'll close this issue then, thanks!
