### ISSUE TITLE
dotnet 5.0.402 doesnt install sdks but only runtimes

### ISSUE THREAD

**Issue by kevkanae** [dotnet/sdk#22432]
### Installation seems to have bugged out by installing only the runtimes
Followed the steps on the official website for .NET 5.0, downloaded the x64 SDK, installed it and tried running the commands mentioned on the website

### To Reproduce
--> dotnet --version
```
It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```
### Further technical details
--> dotnet --info
```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.20
  Commit:  2833dab8c3

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### I'm on windows 11, if thats important just in case

**Comment by KalleOlaviNiemitalo** [comment]
> ```
> Host (useful for support):
>   Version: 3.1.20
> ```

Perhaps you're using an older dotnet.exe. From which directory was it loaded? Try `where dotnet`.

**Comment by kevkanae** [comment]
Ive downloaded the exe straight from https://dotnet.microsoft.com/download

```where dotnet``` gives an empty response
![image](https://user-images.githubusercontent.com/64493268/139836181-8214cb27-4458-43be-b4d1-e5cd94d8c542.png)

**Comment by kevkanae** [comment]
For anyone else who faces this issue on an x64 system,
Edit your System Variables Path, and make sure C:\Program Files\dotnet\ is **ABOVE** C:\Program Files (x86)\dotnet\

Found the solution on stackoverflow

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps caused by the bug <https://github.com/dotnet/sdk/issues/22047> then.

**Comment by KalleOlaviNiemitalo** [comment]
> `where dotnet` gives an empty response

The `where dotnet` command is for the `cmd.exe` command interpreter.
A similar command for PowerShell is `Get-Command dotnet`.

**Comment by kevkanae** [comment]
I see, thanks did not know that. :)
