### ISSUE TITLE
no basic auth header when using proxy v2.1.300-preview1-62608--07 

### ISSUE THREAD

**Issue by mpluhar** [dotnet/sdk#2248]
In the version v2.1.300-preview1-62608--07 a http_proxy environment variable with the format

http://user:pass@host:port

is not being picked up correctly. Only the host and port is actually being used when running a dotnet restore or dotnet build
I ran a tcpdump to confirm this.

Same set up works fine in v2.1.100

**Comment by livarcocc** [comment]
I am sorry, I don't quite follow what you mean by this. Can you give us more details? What are you trying to do here? Is this for a restore feed?

**Comment by mpluhar** [comment]
Sorry, I was a bit busy yesterday and I thought I get the request logged.

Here is some more detail:
I  am using an vsts-agent docker image with .NET Core SDK 2.1.101 (runtime 2.0.6) for building .net Core projects. When executing a 'dotnet build' we restore the dependencies for the project (one feed pointing to api.nuget.org). We have to use an HTTP proxy with basic authentication  to connect to the Internet.
I use  environment variables (http_proxy and https_proxy) to pass on the proxy settings to dotnet. This works fine in the SDK 2.1.101.

We installed the SDK 2.1.300-preview1 on the same build agent to build for .NET Core 2.1 following the same setup using environment variables.. While I can confirm that the proxy is being used when executing a dotnet build, I cannot see any basic auth headers in the network traffic. The result is that fetching the dependencies fails.

**Comment by livarcocc** [comment]
Got it. Thanks for the extra details. Given that restore is the piece that should be using the headers with the proxy, I am going to move this issue to NuGet.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6939
