### ISSUE TITLE
Build net46 version of SDK using framework assembly nuget packages

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2249]
See https://github.com/dotnet/source-build/issues/125#issuecomment-389646958

There are framework reference assemblies that are useable x-plat and in source builds.

This will fix VS Code / omnisharp running with a source-built SDK.

It will also enable more build & test validation x-plat in non source-builds.

**Comment by leecow** [comment]
Nick / @livarcocc - any reason why this shouldn't be done in a 2.1.3xx update?

**Comment by nguerrera** [comment]
@leecow Good question. Let me see if the change is easy and low risk. I think it is.

**Comment by leecow** [comment]
@nguerrera - were you able to have a look at what this fix might entail?

**Comment by nguerrera** [comment]
@leecow Not yet, but I'll check today.

**Comment by nguerrera** [comment]
@leecow OK, so it turns out the code change is trivial thanks to repo toolset: #2249 I think the risk is low too. :)

If indeed this just works with source-build as @weshaggard suggested it would, this might even be something RedHat would want to patch in to their source build without even waiting for servicing.

**Comment by nguerrera** [comment]
Sorry, wrong link above: #2264. Deleting this message and editing the previous one.

**Comment by nguerrera** [comment]
Fixed by #2264
