### ISSUE TITLE
It was not possible to find any installed .NET SDKs.

### ISSUE THREAD

**Issue by arivoir** [dotnet/sdk#22508]
After installing Visual Studio 2022 Preview Version 17.1.0 Preview 1.0, it installed Net6, but now the sdk's can not be found

> C:\Program Files\Microsoft Visual Studio\2022\Preview>dotnet --version
> Could not execute because the application was not found or a compatible .NET SDK is not installed.
> Possible reasons for this include:
>   * You intended to execute a .NET program:
>       The application '--version' does not exist.
>   * You intended to execute a .NET SDK command:
>       It was not possible to find any installed .NET SDKs.
>       Install a .NET SDK from:
>         https://aka.ms/dotnet-download
> 

But it is installed there

![image](https://user-images.githubusercontent.com/17496741/140793907-3c0fdd1d-0dd0-49f7-af78-b569da07c39a.png)

**Comment by markhewett** [comment]
I had a similar "where did all my SDKs go" issue after installing VS2022 today.  It seems like my path is picking up the 32-bit version of dotnet.exe instead of the 64-bit version, and I only have 64-bit SDKs installed now.  Not sure what changed exactly, but try...

    "C:\Program Files\dotnet\dotnet" --version

And see what that shows.

**Comment by arivoir** [comment]
That works. 

> "C:\Program Files\dotnet\dotnet" --version
> 6.0.100
> 

I wonder what is broken

**Comment by InKahootz** [comment]
Was facing the same problem when I installed VS2022. @markhewett comment led me to a fix.

My fix. Make sure x86 dotnet is below x64 dotnet on System PATH

![image](https://user-images.githubusercontent.com/1909698/140804269-91fa3408-0e82-447d-87cb-8b43a852e1fa.png)

**Comment by Silvenga** [comment]
We ran into it upgrading from VS2022 RC to VS2022 GA. This is going to trip up a lot of people.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows

Looks like there's a bug in the upgrade code that is uninstalling the old host first (removing the path) and then installing the new host. We fixed an iteration of this between preview 5 and GA but apparently missed a specific instance. We're investigating.

**Comment by tbolon** [comment]
I can confirm that I was impacted by this.

In my case, the dotnet x64 was at the end of the system environment path variable, and I had to move the x86 entry below for the dotnet.exe x64 to be picked up again.

![image](https://user-images.githubusercontent.com/127185/140893057-d330d813-82b5-4de7-abdc-b572e8885149.png)

**Comment by marcpopMSFT** [comment]
To close the loop here, we released a fix with VS that removes the bad x86 path and we've made a change to improve the error message. That's our solution for this issue at this time.
