### ISSUE TITLE
Binaries for v3.1.415 unavailable

### ISSUE THREAD

**Issue by joancafom** [dotnet/sdk#22504]
Hi! 

Recently, a new version of Dotnet SDK (v3.1.415) has been [tagged](https://github.com/dotnet/sdk/releases/tag/v3.1.415) and made available. Past tags included some release notes, the source code and some compiled binaries (also available on the official Microsoft [page](https://dotnet.microsoft.com/download/dotnet/3.1)). For instance, see [v3.1.414](https://github.com/dotnet/sdk/releases/tag/v3.1.414).

 This does not seem to be the case for [v3.1.415](https://github.com/dotnet/sdk/releases/tag/v3.1.415). Will you be publishing the binaries for this version any time soon?

**Comment by KalleOlaviNiemitalo** [comment]
SDK 3.1.415 seems to be available from <https://dotnet.microsoft.com/download/dotnet/3.1> now.

**Comment by joancafom** [comment]
Thanks! Closing this then
