### ISSUE TITLE
dotnet sln [solution] add [project] creates debug only configuration

### ISSUE THREAD

**Issue by kepeter** [dotnet/sdk#22507]
Hi,

As msbuild build significantly faster my 160+ projects if I have a solution for them I decided to create the solution dynamically.
```
dotnet new sln --name build
dotnet sln build.sln add (ls -r **/*.csproj)
```
This code creates the solution in 10 seconds, however all the configurations of the projects bounded to the Debug|Any CPU, and for that all the build will be a debug build...
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TlmBhnShln_S", "Reports\tlm\TlmBhnShln_S\TlmBhnShln_S.csproj", "{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}"
EndProject
```
```
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|Any CPU.Build.0 = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|x64.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|x64.Build.0 = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|x86.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Debug|x86.Build.0 = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|Any CPU.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|Any CPU.Build.0 = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|x64.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|x64.Build.0 = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|x86.ActiveCfg = Debug|Any CPU
{7B3330E5-8D8B-42FD-8FBF-9AED595AF9A2}.Release|x86.Build.0 = Debug|Any CPU
```
I pick the Release|Any CPU build from the command line, but of course it will be actually a debug build...

**dotnet --version** returns 5.0.202

**Comment by KalleOlaviNiemitalo** [comment]
As a workaround, you could try [slngen](https://microsoft.github.io/slngen/).

**Comment by kepeter** [comment]
@KalleOlaviNiemitalo 
Thank you for the idea - I'm checking it...

**Comment by teebeast** [comment]
We also use it to generate dynamically solutions, depending on nuget packages or missing references and we also get wrong configurations in Release. We have to manually change the configuration of the added project from Debug to Release.

![image](https://user-images.githubusercontent.com/20777572/153133797-f5eea3fd-cb5a-4949-a04b-036e936441b3.png)

The problem only occures when you add a project with an old project format. You can reproduce it by adding a windows forms project for .Net Framework.

**Comment by wilstoff** [comment]
As a temporary work around until this pull request gets merged you can add

`<Configurations>Debug;Release</Configurations>`

to the base PropertyGroup of the project before running dotnet sln add.  We had to alter our older templated projects to include this in the mean time.  It becomes a bit more clear if you look at the main fixed file [ProjectInstanceExtensions.cs](https://github.com/dotnet/sdk/pull/26329/files#diff-cfc212f702a727b5bbe834bcc0c12b11d82cebb92a3f4a442bf53e86a53b07da) the rest of the change is just test data to confirm the fix.
