### ISSUE TITLE
Using Remove in Directory.Build.props is ignored

### ISSUE THREAD

**Issue by Abrynos** [dotnet/sdk#22515]
### Describe the bug

Having `<Using Remove="..." />` directive in `Directory.Build.props` does not work.

#### Step 1: Create Project

Project.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>
</Project>
```
Program.cs:
```csharp
namespace Project;

public static class Program {
	public static void Main() { }
}
```

#### Step 2: Create Directory.Build.props
Directory.Build.props:
```xml
<Project>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Using Remove="System.Net.Http"/>
	</ItemGroup>
</Project>
```

#### Step 3: Build and look at the generated global usings
```bash
dotnet build
```
generated obj/Debug/Project.GlobalUsings.g.cs:
```csharp
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

Notice: There is still a global using for `System.Net.Http`.

### Further technical details

`dotnet --version` yields `6.0.100`

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#import-order>, Directory.Build.props is imported very early. If the global using System.Net.Http is added by some file that is imported later, then the Remove in Directory.Build.props cannot affect the item that does not exist yet. Perhaps it'd work better in Directory.Build.targets.

**Comment by dsplaisted** [comment]
Yes, you would need to put this in a `Directory.Build.targets` file for it to work.
