### ISSUE TITLE
ResolvePackageAssets time offset error on Ubuntu 16.04/18.04

### ISSUE THREAD

**Issue by jmacato** [dotnet/sdk#2251]
The following exception is thrown on debug/release:
```
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018: System.ArgumentOutOfRangeException: Offset must be within plus or minus 14 hours. [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018: Parameter name: offset [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.DateTimeOffset.ValidateOffset(TimeSpan offset) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.DateTimeOffset..ctor(DateTime dateTime) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.DateTimeOffset.FromFileTime(Int64 fileTime) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.IO.FileStatus.GetLastWriteTime(ReadOnlySpan`1 path, Boolean continueOnError) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.IO.FileSystem.GetLastWriteTime(String fullPath) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at System.IO.File.GetLastWriteTimeUtc(String path) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [<redacted>.csproj]
/usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [<redacted>.csproj]
```
I was using an older version `dotnet-sdk-2.1.200` then purged that and installed 2.1 RC1. i also cleared /usr/share/dotnet & $HOME/.nuget prior to upgrade.

I encountered this bug while compiling an [Avalonia](https://github.com/AvaloniaUI/Avalonia) app. This also occurs  on the console app 'Hello World' template and on `dotnet clean`.

Update : The build works when i set my timezone to UTC (Had it set to UTC+8 before). it's quite a pain to go back and forth timezones however..

**Comment by livarcocc** [comment]
@nguerrera

**Comment by nguerrera** [comment]
This looks like a bug in corefx. cc @jeremykunhe @Petermarcu 

We're getting `ArgumentOutOfRangeException` calling `File.GetLastWriteTimeUtc(string path)`.

**Comment by nguerrera** [comment]
@JeremyKuhne

**Comment by nguerrera** [comment]
@jmacato Which operating system are you using. Can you provide `dotnet --info` output?

**Comment by nguerrera** [comment]
**Workaround**: disable package assets cache in project file

``` xml
<PropertyGroup>
  <DisablePackageAssetsCache>true</DisablePackageAssetsCache>
</PropertyGroup>
```

**Comment by nguerrera** [comment]
@jmacato Can you try this to (hopefully) nail down a simpler repro for corefx?

1. Switch back to your original timezone
2. Write a simple console app that uses `FIle.GetLastWriteTimeUtc` 
3. Build the console app using the DisablePackageAssetsCache workaround above.
4. Run the program

**Comment by JeremyKuhne** [comment]
@tarekgh can you posit how this might happen?

**Comment by nguerrera** [comment]
@tarekgh Do you agree from the stack that this is not an issue at our call site, but rather in the BCL? Should I move this to dotnet/coreclr or dotnet/corefx?

**Comment by tarekgh** [comment]
@nguerrera yes, this is most likely is an environmental issue or a corefx issue. I don't think this is SDK issue. @JeremyKuhne please advise if you disagree.

**Comment by jmacato** [comment]
@nguerrera Sorry i can't provide the guilty `dotnet --info` since i changed my sdk but it was Ubuntu 18.04 and it is newly reformatted machine. I installed RC1 after `apt purge`'ing `dotnet-sdk-2.1.200`. then after installation, the bug occurs. but when i set my timezone from `UTC+8:00` to `GMT` and back, the issue no longer occurs.

**Comment by jmacato** [comment]
I will try to repro using live usb of Ubuntu 18.04.

**Comment by jmacato** [comment]
@tarekgh `DateTimeOffset.FromFileTime(0)` output is `01/01/1601 6:58:00 AM +06:58`

**Comment by jmacato** [comment]
Okay the bug returned when i deleted `bin` and `obj` folders, then doing `dotnet build`

**Comment by jmacato** [comment]
@nguerrera i tried that simple repro and it returned this: 
`18/05/2018 11:04:40 AM` is the original timestamp
`18/05/2018 3:04:40 AM` is the repro's output

**Comment by nguerrera** [comment]
> Okay the bug returned when i deleted bin and obj folders, then doing dotnet build

@JeremyKuhne, @tarekgh This means we are getting this on `File.GetLastWriteTimeUtc("any/File/That/Does/Not/Exist")`.

@jmacato Can you adjust your repro program to do that?

**Comment by jmacato** [comment]
I can only do restore/clean/run/debug when i set my any timezone except Asia/Manila.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/corefx#29820
