### ISSUE TITLE
dotnet restore: support RestoreConfigFile from csproj or Directory.Build.props

### ISSUE THREAD

**Issue by mc0re** [dotnet/sdk#22517]
### Is your feature request related to a problem? Please describe.
I currently have to define the location of my `nuget.config` for use in `dotnet restore` in two places:

-  In `Directory.Build.props` as `RestoreConfigFile` property for VS builds;
-  In `azure-pipeline.yml` as `nugetConfigPath` argument for CI builds.

### Describe the solution you'd like
Would be nice to only do it once - preferrably as the first bullet point describes.

### Additional context
Azure has .NET 5.0.400 installed.

**Comment by KalleOlaviNiemitalo** [comment]
Does your pipeline run `script: dotnet restore` as shon in [Package: NuGet Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops), or does it use `task: DotNetCoreCLI@2` with `command: restore` as in [Restore NuGet packages in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/packages/nuget-restore?view=azure-devops#restore-packages-with-the-net-core-cli-task) and [.NET Core CLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)?

**Comment by mc0re** [comment]
@KalleOlaviNiemitalo The second one, task.

**Comment by KalleOlaviNiemitalo** [comment]
The task seems to be defined in <https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreCLIV2/restorecommand.ts>, which always passes a `--configfile` option to `dotnet restore`. Perhaps this issue should be transferred to that repository.

**Comment by KalleOlaviNiemitalo** [comment]
On the other hand, the [.NET Core CLI task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops) page has a note saying:

> The restore and push commands of this task no longer take new features and only critical bugs are addressed.

I think Microsoft won't consider this a critical bug. It might then be best to switch to `script: dotnet restore`.

**Comment by mc0re** [comment]
Figured that whole thing out. Unfortunately, I cannot use the standard `**\*.sln` marking from YAML in that `script` command. But thanks anyway.
