### ISSUE TITLE
Unable to run net6.0 apps built with snap package on ubuntu 21.10

### ISSUE THREAD

**Issue by Gigas002** [dotnet/sdk#22529]
### Describe the bug

As title says, I'm unable to run net6.0 programs on Ubuntu 21.10, built using official snap package. The programs builds fine, but when trying to run it says:

```text
user@user-pc:~/test$ dotnet run
/home/user/test/bin/Debug/net6.0/test: relocation error: /home/user/test/bin/Debug/net6.0/test: symbol __pthread_key_create version GLIBC_2.2.5 not defined in file libpthread.so.0 with link time reference
```

To be sure it's not my os's configuration error, I've also tested this behavior on clean Ubuntu 21.10 VM and got the same results as above. Sorry, if this issue doesn't belong to dotnet/sdk repo, I'm not sure, where to place it.

### To Reproduce

Following the official instructions (https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap):

```text
sudo snap install dotnet-sdk --classic
dotnet new console -o test && cd test
dotnet run
```

### Further technical details

`dotnet --info` output:

```text
user@user-pc:~$ dotnet --info
Пакет SDK для .NET (отражающий любой global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Среда выполнения:
 OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /snap/dotnet-sdk/150/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/snap/dotnet-sdk/150/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/snap/dotnet-sdk/150/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/snap/dotnet-sdk/150/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by tweing** [comment]
see https://youtrack.jetbrains.com/issue/RIDER-73736 for a workaround
