### ISSUE TITLE
Include `$(RootNamespace)` by default for a project with implicit usings enabled

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#22535]
### Is your feature request related to a problem? Please describe.

I used the implicit usings among many projects, each project, I would add `<Using Include="$(RootNamespace)"/>` to include the project default namespace, I'm wondering if we could make it included into the default usings if the project is enabled implicit usings.

``` xml
  <ItemGroup>
    <Using Include="$(RootNamespace)"/>
  </ItemGroup>
```

### Describe the solution you'd like

When the project is enabled the implicit usings, include the `$(RootNamespace)` into the usings also. 

### Additional context

It would be great for using the members inside the default namespace.

**Comment by vijayrkn** [comment]
@DamianEdwards for your feedback on this suggestion.

**Comment by WeihanLi** [comment]
I use the `Directory.Build.targets` to include the `$(RootNamespace)` by default
