### ISSUE TITLE
Reference metadata is not preserved by ImplicitlyExpandNETStandardFacades

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/sdk#2254]
For a project targeting .Net Framework 4.7.1 with a reference to netstandard libraries, the target `ImplicitlyExpandNETStandardFacades` replaces certain references with their Facades so netstandard based assemblies work as expected. This currently works great if the project does not associate metadata(like aliases) with any of these references, but when it does - those aren't honored breaking build. 

Filing this issue to ensure that the missing metadata is preserved when the replacement is done.

Adding few more details, here is the reference in question:
```
<ReferenceInclude="System.Net.Http">
     <HintPath>E:\SomeRandomProjectPath\bin\debug\System.Net.Http.dll</HintPath>
     <Aliases>snh</Aliases>
     <EmbedInteropTypes>False</EmbedInteropTypes>
   </Reference>
```
and here is what is passed on to csc:
```
E:\Program Files (x86)\Microsoft Visual Studio\15.7Prev\Enterprise\MSBuild\15.0\bin\Roslyn\csc.exe /noconfig /unsafe+ /nowarn:1587,1591,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+  /reference:"E:\Program Files (x86)\Microsoft Visual Studio\15.7Prev\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.Net.Http.dll ...."
```
Notice the missing alias to System.Net.http.

**Comment by AbhitejJohn** [comment]
Tagging @ericstj to help triage this into a milestone. Please do redirect if I should be tagging someone else on this.
More than a few folks [here](https://developercommunity.visualstudio.com/content/problem/162321/fakes-not-generated-using-net-471-after-updating-t.html) are running into this.

**Comment by ericstj** [comment]
Thanks for pointing this out.  @livarcocc can you assign a milestone?

/cc @joperezr @dsplaisted

Relevant portion of targets is here: https://github.com/dotnet/sdk/blob/935ac5fde8d917b1de3b18d038232f15527572aa/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L101-L107

I that pattern was copied from elsewhere in the SDK so it may not be the only instance of this issue.

**Comment by dsplaisted** [comment]
For reference, the workaround posted for the Fakes issue is to put the following in Directory.Build.targets:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <Target Name="PrivateFakesAfterFacadesSwitch"
            Condition="'$(ImplicitlyExpandNETStandardFacades)' == 'true' and $(AssemblyName.EndsWith('.Fakes'))"
            AfterTargets="ImplicitlyExpandNETStandardFacades" DependsOnTargets="ImplicitlyExpandNETStandardFacades">

    <ItemGroup Condition="'@(_NETStandardLibraryNETFrameworkLib)' != ''">
      <SnhReference Include = "@(_NETStandardLibraryNETFrameworkLib)" Condition="'%(_NETStandardLibraryNETFrameworkLib.FileName)' == 'System.Net.Http'" />
      
      <Reference Remove="%(SnhReference.FileName)" Condition="'@(SnhReference)' != ''"/>
      <Reference Include="%(SnhReference.FileName)" Condition="'@(SnhReference)' != ''">
        <HintPath>%(SnhReference.Identity)</HintPath>
        <Private>false</Private>
        <Aliases>snh</Aliases>
      </Reference>
    </ItemGroup>

  </Target>

</Project>
```

**Comment by dsplaisted** [comment]
#2250 is possibly related to this, and may actually drop the custom metadata from the `Reference` in more cases.  /cc @nguerrera

**Comment by ericstj** [comment]
Seems like aliased references should be preserved at compile time (or else at least consider alias in the conflict key), though I'm not sure what to do with an aliased copy local reference since they will still clash in output.

**Comment by Gladskih** [comment]
My problem on .Net 4.6.2 looks the same. And the workaround does nothing.
I can build my project sometimes (randomly) on my local machine, but Tfs Build fails permanently.
The build've been broken when I updated Polly package to 7.0. version, which is implemented only as .Net Standard.

**Comment by ericstj** [comment]
@livarcocc @dsplaisted is this issue still pending or has a fix been made?

**Comment by dsplaisted** [comment]
@ericstj No, this hasn't been fixed.  I started [work on a fix](https://github.com/dotnet/sdk/compare/master...dsplaisted:2254-preserve-reference-metadata) last year but it was never finished.

**Comment by entei-11** [comment]
I see that #3331 is merged now. This fix is presented only in 3.x.x tags of dotnet - [check commit tags here](https://github.com/dotnet/sdk/commit/4094dca1091f32f16b5756ef14e6e1f99d67bee3). So the issue is fixed in VS2019, am I right?

But originally this issue was shipped with VS2017 as mentioned at Developer Community Forum here - [Fakes Not Generated using .NET 4.7.1 after updating to VS2017 15.5](https://developercommunity.visualstudio.com/content/problem/162321/fakes-not-generated-using-net-471-after-updating-t.html). On the same page this issue was suggested to track by @AbhitejJohn - [see his comment](https://developercommunity.visualstudio.com/comments/260655/view.html).

Currently, I'm on VS2017 ver. 15.9.20 and can confirm that problem is still here. But the issue is closed. Which seems to be misleading. @dsplaisted Please, comment is the problem fixed only for VS2019 and wasn't it supposed to fix for VS2017 too?

**Comment by dsplaisted** [comment]
@entei-11 Yes, this fix is only available in the .NET Core SDK 3.0.100 and higher, which only works with VS 2019.
