### ISSUE TITLE
Regression in .NET SDK 6.0.100: Can no longer publish WinForms/WPF app for win-arm64 (NETSDK1082) 

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#22565]
#19991 strikes again, but for 6.0.100!

After upgrading from .NET SDK 5.0.401 to **6.0.100** we can no longer publish a `net5.0` WPF app for `win-arm64`.

The `dotnet publish` command fails with:

> error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win-arm64'

**Repro**
- With both 64-bit .NET SDK 5.0.401 and 6.0.100 installed on a Windows 10 x64 machine...
- Run `dotnet new wpf`
- Modify csproj to target `net5.0-windows`.
- Create a `global.json` file with this content
  ```json
  {
    "sdk": {
      "version": "5.0.401",
      "rollForward": "patch",
      "allowPrerelease": false
    }
  }
  ```
- Run `dotnet publish -r win-arm64`. It succeeds.
- Now replace `5.0.401` in the global.json file with `6.0.100`.
- Run `dotnet publish -r win-arm64`. It fails with:

```
> dotnet publish -r win-arm64
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\temp\wpfapp\wpfapp.csproj (in 95 ms).
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win-arm64'. [C:\temp\wpfapp\wpfapp.csproj]
```

[Repro solution](https://github.com/dotnet/sdk/files/7528442/wpfapp.zip)

**Comment by marcpopMSFT** [comment]
Fix should release tomorrow.

**Comment by riverar** [comment]
This still repros for me in 6.0.202. This is the third time now that this has returned. It may behoove the team to set up a test case and validate before closing.

**Comment by baronfel** [comment]
I just attempted the repro steps in the issue on 6.0.202 and the latest 6.0.300 nightly from the dotnet/installer. I was able to publish a win-arm64 binary on both of those.

Do you have a reproduction we could try, or a [binlog](https://aka.ms/binlog) of a failure on your system?

**Comment by riverar** [comment]
@baronfel Fair enough, will file a new issue with repro steps/etc.

**Comment by erikaemma** [comment]
6.0.402 x86&x64 still: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'. ---- This is a bug ?

**Comment by marcpopMSFT** [comment]
Do you mean this one: https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Runtime.win-arm64? I don't believe we've had specific windows forms versions of the runtime packs, only the WindowsDesktop one that includes windows forms.
