### ISSUE TITLE
Inconsistent error code for NETSDK1174

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#22639]
We are using the NETSDK1174 error code for two different things.

How this happened:

- In #18301 we added a new warning that comes from the CLI.  We wanted a warning code for it, but all of our other warning codes come from SDK tasks.  So we inserted a placeholder resource in the SDK tasks (`PlaceholderRunCommandProjectAbbreviationDeprecated`) to reserve the warning code (which ended up being NETSDK1174.
- Subsequently, we merged an earlier preview branch into the current 6.0 branch in #18519.  Other new error codes had been added in the earlier branch, so this pushed the `PlaceholderRunCommandProjectAbbreviationDeprecated` error code down to NETSDK1176.  However, we didn't notice this, and didn't update the resource in the CLI code that generates this (or in dotnet-watch, which does the same thing).

So now we use NETSDK1174 for two different errors:

- NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.
- NETSDK1174: Compression in a single file bundle is only supported when publishing a self-contained application.

The first instance is [already documented](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1174), while it looks like the second one may not be documented.  So probably we should change the error code for the second one (resource name `CompressionInSingleFileRequiresSelfContained`) to use a new error code.

FYI @AntonLapounov @vitek-karas @agocke

**Comment by marcpopMSFT** [comment]
@dsplaisted Yes as 6.0.100 is an LTS so will be in support a long while. Error number confusion can use up a bunch of customer's time.

**Comment by agocke** [comment]
@VSadov Can you bump the error code here for the compression error?

**Comment by VSadov** [comment]
Sure!

**Comment by VSadov** [comment]
I assume this would need to be fixed in 6.0 (and then matched in 7.0). Right?

**Comment by agocke** [comment]
@marcpopMSFT Do you all do merge forward or port back for SDK?

**Comment by dsplaisted** [comment]
> @marcpopMSFT Do you all do merge forward or port back for SDK?

Normally we check into the oldest branch a change is going into, and then merge forward.

**Comment by marcpopMSFT** [comment]
Change is in 6.0.1xx-3xx so closing.
