### ISSUE TITLE
Latest dotnet sdk 3.1 doesn't build project with C#10

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/sdk#22662]
### Describe the bug
Latest dotnet sdk 3.1 doesn't build project with C#10

### To Reproduce
Take dotnet sdk 3.1 and try build project with C#10

![image](https://user-images.githubusercontent.com/2669927/142371436-115748f2-02f7-47b4-a92f-e5c8a0b4425b.png)

### Exceptions (if any)

CSC : error CS1617: Invalid option '10' for /langversion. Use '/langversion:?' to list supported values.

### Further technical details
- only dotnet sdk version 3.1.415 install
- Build Engine version 16.7.2+b60ddb6f4 for .NET

### P.S.
Will it be possible to builds such projects? It seems that due to the limitations of msbuild
https://github.com/dotnet/aspnetcore/issues/34292#issuecomment-880131290

**Comment by bmarinov** [comment]
According to https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version
> C# 9 is supported only on .NET 5 and newer versions.
> C# 10 is supported only on .NET 6 and newer versions.

Assuming that this is correct, you would have to migrate to .NET 6 in order to use the new language features.

**Comment by rstm-sf** [comment]
This does not apply to all features :) You can easily build a net461 project with C#9 (and maybe C#10, but I already doubt)

**Comment by rstm-sf** [comment]
Now it seems to me that this is normal. Was just confused since C#9 was previously supported
