### ISSUE TITLE
.NET 6 GzipStream.Flush method implementation questions

### ISSUE THREAD

**Issue by beetlex-io** [dotnet/sdk#22671]
NET 6 the gzip stream flush method automatically calls the inner stream flush method, but this was not the case in previous versions！
test code:
``` csharp
    internal class Program
    {
        static void Main(string[] args)
        {
            byte[] data = System.Text.Encoding.UTF8.GetBytes(Resource1.HTML);

            using (MemoryStream memory = new MyMemory())
            {
                using (Stream gzipStream = new GZipStream(memory, CompressionMode.Compress, true))
                {
                    gzipStream.Write(data, 0, data.Length);
                    gzipStream.Flush();
                    
                }

            }
        }
    }

    public class MyMemory : MemoryStream {

        public override void Flush()
        {
#if NET6_0
           Console.Write("net6 memory flush");
#else
            Console.Write("net memory flush");
#endif
            base.Flush();

        }
    }
```

**Comment by KalleOlaviNiemitalo** [comment]
Flushing of the inner stream was made unconditional [in #43834](https://github.com/dotnet/runtime/pull/43834/commits/af13fb940b6521e83c1551cb21442f1b116e2b5e#diff-a076647d6d5119e4e3b482835f098318b585fc7fd9cb16116c45395721c61c3dR531-R533) as a bug fix. It was not discussed in the PR. It is tested in [WrappingConnectedStreamConformanceTests.Flush_FlushesUnderlyingStream](https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs#L2699-L2729).
