### ISSUE TITLE
RuntimeIdentifier in CSproj causing the CLR exception while debugging.

### ISSUE THREAD

**Issue by davidborka** [dotnet/sdk#22709]
### Describe the bug
Given the VisualStudio2022 and .net 6 the target framework
When the CSproj file contains the Runtimindetifier property settings. 
Then the Visual studio can't run the application in debug mode, the error message: "Unable to attach to CoreCLR. Operation is not supported."

### To Reproduce
![NET6issue](https://user-images.githubusercontent.com/29485795/142820366-016a9ce4-c9c3-4ed7-8398-c39016dca5ac.gif)

**Comment by vijayrkn** [comment]
Visual Studio specific issues are reported and tracked via the Visual Studio developer community. The platform has additional support for collecting logs & traces. Please follow the instructions here & submit an issue through Visual Studio - https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-guidelines?view=vs-2022#before-submitting-an-issue
