### ISSUE TITLE
.NET 6.0 Can not publish with PublishReadyToRun on alpine-x64 without restore

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/sdk#22706]
### Describe the bug
If I publish my .NET Web Api with .NET 5.0 it worked fine. After the upgrade to .NET 6.0 this will not work anymore:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS publish
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1
WORKDIR /app
COPY ["Service/*.csproj", "./Service/"]
COPY ["nuget.config", "./"]
RUN dotnet restore Service --runtime alpine-x64
COPY . .
RUN dotnet publish Service \
    --configuration Release \
    --output /app/publish \
    --no-restore \
    --runtime alpine-x64 \
    --self-contained true \
    -p:PublishReadyToRun=true \
    -p:PublishTrimmed=true \
    -p:PublishSingleFile=true
```
If I remove the line `--no-restore \` from `dotnet publish` it works again with .NET 6.0.

### To Reproduce
This can be easily reproduced in e.g. WSL2 debian if you 
1. make a new web api `dotnet new webapi`
2. run `dotnet restore --runtime alpine-x64`
3. run `dotnet publish --configuration Release --no-restore --runtime alpine-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -p:PublishSingleFile=true`

### Exceptions (if any)
`Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/usr/share/dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(293,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.`

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [/usr/share/dotnet/sdk]
  5.0.403 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version > Command line

**Comment by Lonli-Lokli** [comment]
I believe it's documented
https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/publish-readytorun-requires-restore-change

**Comment by MarkusRodler** [comment]
Yes it is documented now, but it wasn't in November last year. Thanks for the link
