### ISSUE TITLE
Cannot exit while running an uninstalled dotnet tool

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#22749]
Environment: .NET 6 SDK: 6.0.200-preview.21573.3(runtime-6.0.0)

Repro steps: 
1. Install .NET 6: 6.0.200-preview.21573.3 on a clean windows OS.
2. Run below command:
	_dotnet tool install -g dotnetsay
	dotnet tool uninstall -g dotnetsay
	dotnet tool run dotnetsay -- 'hi'_
3. Observe

Expected Result:
It should display error.

Actual Result:
Cannot exit while running an uninstalled dotnet tool. 
![image](https://user-images.githubusercontent.com/87680983/143205258-91e0bad4-ae22-41a1-8a4a-c7c3b8b82869.png)

Dotnet info:
.NET SDK (reflecting any global.json):
Version: 6.0.200-preview.21573.3
Commit: a2bb0dde82

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.200-preview.21573.3\

Host (useful for support):
Version: 6.0.0
Commit: 4822e3c3aa

.NET SDKs installed:
6.0.200-preview.21573.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

Note:
This is not repro on 6.0.101.

**Comment by joeloff** [comment]
Tried this on 6.0.100, and it errors out immediately, so this looks like a possible regression

**Comment by joeloff** [comment]
I can repro this using the same build.

**Comment by Jiangpeng14** [comment]
Can be reproduced on VSM 17.0 Preview (17.0 build 6160) net6 channel.

**Comment by WenJunJi01** [comment]
There is a similar issue on VS 17.2.0 Preview 1.0 [32112.389.main] + .NET SDK 7.0.100-alpha.1.22062.5. Unable to exit when running uninstalled dotnet tool and getting error “.NET Host has stopped working”.
![image](https://user-images.githubusercontent.com/87680983/149440947-53d94f45-4d7e-4a1a-a94b-c37a9a141c59.png)
![image](https://user-images.githubusercontent.com/87680983/149440512-629375a0-c2b7-4a52-aa68-67fc64188bfc.png)

**Comment by WenJunJi01** [comment]
It can not repro on Val 17.2.0 Preview 1.0 [32208.120.d17.2] and Val 17.1.0 [32208.1.d17.1], which with inserted 6.0.200.

**Comment by WenJunJi01** [comment]
This issue can also repro with .NET SDK 7.0.100-preview.2.22115.2(runtime-7.0.0-preview.2.22103.2).
![image](https://user-images.githubusercontent.com/87680983/154427185-f0aafc34-2c1e-48c8-a3de-f572a7f5b549.png)

**Comment by WenJunJi01** [comment]
Also repro with .NET SDK 7.0.100-preview.3.22160.25(runtime-7.0.0-preview.3.22151.6)

**Comment by WenJunJi01** [comment]
This issue can not repro with .NET 7 Preview 4 SDK: 7.0.100-preview.4.22219.19 from main branch of https://github.com/dotnet/installer
![image](https://user-images.githubusercontent.com/87680983/164176187-f701b307-6edb-436c-a518-ba3944c382e2.png)

**Comment by WenJunJi01** [comment]
It can not repro on VS 17.2.0 Preview 5.0 [32421.268.d17.2] with inserted .NET SDK 6.0.300-preview.22204.3(runtime-6.0.3).
![image](https://user-images.githubusercontent.com/87680983/164672354-c769fe18-f02d-458d-8bc7-47210b77aded.png)

**Comment by baronfel** [comment]
This was probably solved by the changes to fix https://github.com/dotnet/sdk/issues/23034.
