### ISSUE TITLE
Update default package version for .NET Core 2.1 once the RTM package has shipped

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2275]
Once there is a 2.1.0 version of the Microsoft.NETCore.App package available, we need to update the [sdk logic](https://github.com/dotnet/sdk/blob/dc8eef4824cbc6ba23f51f8d09bb8af6d51a517b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L107-L116) that selects the package version to use.  Otherwise, when 2.1.1 ships, framework-dependent apps would roll forward to 2.1.1.

While we're add it, we should add test coverage that we get the right package version when targeting .NET Core 2.1.

- [x] https://github.com/dotnet/sdk/pull/2298
- [x] test it manually when there is a build out.
- [x] Add test to CLI that will catch portable not move forward that is similar to dotnet/cli#8919
- [x] CLI sets UseBundledVersionAsDefaultVersion based on patch version == 0 and is preview == true
- [x] Change SDK to use (4)

**Comment by wli3** [comment]
- [ ] https://github.com/dotnet/sdk/pull/2298
- [ ] test it manually when there is a build out.
- [ ] Add test to CLI that will catch portable not move forward that is similar to dotnet/cli#8919
- [ ] CLI sets UseBundledVersionAsDefaultVersion based on patch version == 0 and is preview == true
- [ ] Change SDK to use (4)

**Comment by wli3** [comment]
✅ Checked  2.1.400-preview-009006 with runtime Microsoft.NETCore.App 2.1.1-servicing-26605-02. The published self contain has runtime.config as following

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0"
    }
  }
}
```
