### ISSUE TITLE
GenerateAssemblyInfo + globbing cause nested csproj build failure

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#2278]
If you have a project structure like the following:

```
C:.
│   Program.cs
│   TestApp.csproj
│   TestApp.sln
│
└───src
    └───subdir
            Helper.cs
            subdir.csproj

```

subdir.csproj will generate AssemblyInfo.cs under subdir/obj. However the build of TestApp.csproj will glob the AssemblyInfo.cs into its build. The TestApp.csproj will fail with error like the following:

```
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(10,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(11,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(12,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
obj\Debug\netcoreapp1.1\TestApp.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\Users\wul\Downloads\download\PJAppWithSlnThatDoesNotRefCsproj\TestApp\TestApp.csproj]
```

**Comment by wli3** [comment]
Talked to @nguerrera the solution could be change the extension of AssemblyInfo
https://github.com/dotnet/sdk/blob/2e6c5933e0553c02a8b6bc97206ceb1abd10da9c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L22

So it will be free from globbing. It is ok for _AssemblyInfo_ since there is no symbol and no value to "go to definition" into this file. However, this solution might not be able to generalized due to the lack of wide editors support.

**Comment by dasMulli** [comment]
I've been recommending to exclude paths of other csproj files entirely using `DefaultItemExcludes`.

> Talked to @nguerrera the solution could be change the extension of AssemblyInfo

It will show up as `<None>` items then which may be even more confusing in editors.

Another problem will be everything else that generates cs files. This may be due to NuGet packages containing pp files that are generated into .cs files as well as the `Microsoft.NET.Test.Sdk` which generates an empty entry point so that they can change the compilation into an executable.

**Comment by dasMulli** [comment]
What's the goal anyway?

Having multiple csproj files in a directory hierarchy would be confusing anyway, even if all the .cs files of the sub-csproj are included as <None>, this is still confusing and needs user intervention..
https://github.com/SabotageAndi/NewCSProj/pull/1/files

**Comment by nguerrera** [comment]
> It will show up as <None> items then which may be even more confusing in editors.

Good point.
