### ISSUE TITLE
Reference items might contain dupes after running ConflictResolution when targeting 4.7.2

### ISSUE THREAD

**Issue by joperezr** [dotnet/sdk#2279]
We recently changed the way ConflictResolution works in order to make the task not assume that all of the platform assemblies are auto-referenced, and instead make sure to add a reference to the platform assembly in case it wins in conflict resolution against a reference coming from a package. These changes fixed several scenarios, but they seem to have to remaining issues:

 - They assume that the platform reference was removed by NuGet. This assumption is mostly true when using `<PackageReference ` since a NuGet target will run that will remove the single name reference, so adding it back during conflict resolution won't cause a duplicated reference. However, this assumption is not true in the case when users have `packages.config`. In this world, the NuGet target would not have removed the platform reference because it wouldn't run, but conflict resolution would still ad the reference, so there will be a dupe after running the task. For now, RAR would take care of that and unify the reference, but it might lead to issues in the future so we might as well fix it.

 - The changes add an extension to the added platform reference. After running the task of conlfict resolution, you'll see that all of the platform references are single-name and have no extension, but the one added by the task will contain the `.dll` on it. This might also cause issues in the future, so it's worth it to have the behavior mimic a regular platform reference.

cc: @dsplaisted @AlexGhiondea

**Comment by joperezr** [comment]
@ericstj as FYI

**Comment by MiYanni** [comment]
Old bug triage: If we still have problems with this change, we'll address them in other issues. For now, things *seem* to be working, so closing this for now.
