### ISSUE TITLE
dotnet new console target for platform specific runtime

### ISSUE THREAD

**Issue by sipsorcery** [dotnet/sdk#22804]
Previously in .NET 5 it was possible to reference a library that was calling WinRT APIs from an application that specified a target of `net5`.

With .NET 6 and the changed mechansim of calling WinRT APIs the library must now specify a platform specific target such as `net6.0-windows10.0.22000`.

Any application that needs to target the library also needs to use a Windows specific target of `net6.0-windows10.0.22000`.

How can `dotnet new console` be used to create a console application that can reference platform specific libraries? For example:

`dotnet new console --name CallWinRTConsole -f net6.0-windows10.0.22000`

**Comment by KalleOlaviNiemitalo** [comment]
`dotnet new console --name CallWinRTConsole --framework net6.0 --target-framework-override net6.0-windows10.0.22000` works for now. See <https://github.com/dotnet/templating/issues/3261>.
