### ISSUE TITLE
dotnet add: 'Value cannot be null. (Parameter 'path1')' error when package name conflicts with existing project reference

### ISSUE THREAD

**Issue by andy-mcdowall-ptml** [dotnet/sdk#22815]
When attempting to add a package via `dotnet add` if the target project has a project reference of the same name then the operation will fail with the error `error: Value cannot be null. (Parameter 'path1')`

### Steps to reproduce

```Powershell
# using CorrelationId package as a concrete example, though actual package doesn't matter
dotnet new classlib --name MainProject
dotnet new classlib --name CorrelationId
dotnet add .\MainProject reference .\CorrelationId
dotnet add .\MainProject package CorrelationId
```

**Expected:**

A warning message such as:
> warning: Project 'C:\Dev\nugetNameConflicts\MainProject\MainProject.csproj' already contains a project reference with the name 'CorrelationId'

**Actual:**
```
  Determining projects to restore...
  Writing C:\Users\XXXl\AppData\Local\Temp\tmpE05C.tmp
info : Adding PackageReference for package 'CorrelationId' into project 'C:\Dev\nugetNameConflicts\MainProject\MainProject.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/correlationid/index.json
info : Restoring packages for C:\Dev\nugetNameConflicts\MainProject\MainProject.csproj...
info : Package 'CorrelationId' is compatible with all the specified frameworks in project 'C:\Dev\nugetNameConflicts\MainProject\MainProject.csproj'.
error: Value cannot be null. (Parameter 'path1')
```

### Other notes

- This is related to, but not the same as, #15544
- In Visual Studio, under the same circumstances, package install will succeed but will display a warning triangle (with no other information) next to the package in the solution explorer
- This issue also affects indirect dependencies (package x depends on CorrelationId), in this situation package install will appear successful, solution will compile, but code may exhibit runtime errors due to missing assemblies

**Comment by erdembayar** [comment]
Considering below works I believe this is bug, I just changed 3rd and 4th line order. 

```
dotnet new classlib --name MainProject
dotnet new classlib --name CorrelationId
dotnet add .\MainProject package CorrelationId
dotnet add .\MainProject reference .\CorrelationId
```
@nkolev92 
Not sure, if this error is coming from dotnet or nuget?

**Comment by nkolev92** [comment]
dotnet add package is NuGet, dotnet add reference is dotnet. 

So I think this should be NuGet side.
