### ISSUE TITLE
Re-enable test ItShouldShowWarningMessageOnCollectCodeCoverageThatProfilerWasNotInitialized if appropriate

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#22865]
The `ItShouldShowWarningMessageOnCollectCodeCoverageThatProfilerWasNotInitialized` test is failing in #17260 when we switch to Ubuntu 18.  It's not generating the warning that code coverage isn't available.

Should this still be generating the warning, or does code coverage now work better on Ubuntu 18?

@dotnet/dotnet-test-templates-admin

**Comment by jakubch1** [comment]
Code coverage is supported on Ubuntu 18.04 and is not on 16.04. We now also support macOS x64. I will try to fix those tests.

**Comment by Haplois** [comment]
It was fixed by #23039.
