### ISSUE TITLE
[workload] Machine readable outputs should only output JSON

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/sdk#22887]
### Is your feature request related to a problem? Please describe.

Commands like `dotnet workload update --print-rollback` and `dotnet workload list --machine-readable` are very helpful, but they should print only JSON to stdout.

Right now I run `dotnet workload list --machine-readable` and this is what gets printed to stdout:

```
Failed to update the advertising manifest microsoft.net.sdk.tvos: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.sdk.android: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.sdk.maui: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.workload.emscripten: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.sdk.macos: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.sdk.ios: Unable to load the service index for source https://REDACTED/index.json..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Unable to load the service index for source https://REDACTED/index.json..
==workloadListJsonOutputStart==
{"installed":["macos","ios"],"updateAvailable":[{"existingManifestVersion":"12.0.101-preview.10.249","availableUpdateManifestVersion":"12.0.101-preview.10.251","description":".NET SDK Workload for building macOS applications.","workloadId":"macos"},{"existingManifestVersion":"15.0.101-preview.9.31","availableUpdateManifestVersion":"15.0.101-preview.10.251","description":".NET SDK Workload for building iOS applications.","workloadId":"ios"}]}
==workloadListJsonOutputEnd==
```

I have to process this and it complicates my tooling.

### Describe the solution you'd like

Commands like `rg`, `lsblk`, `losetup`, etc that offer JSON output modes _only_ print JSON to stdout. Everything else goes to stderr. `dotnet workload` commands that are intended to offer machine-readable output would be most useful if they functioned similarly.

This opens up much easier shell scripting workflows. In powershell you could pipe to `ConvertFrom-Json` without any other ceremony. In other shells you could pipe to `jq`.

### Additional context

I would imagine this would break compatibility with tools used to the current output, so unfortunately it would require another option, like `--really-machine-readable`.

**Comment by sandyarmstrong** [comment]
This may apply to other `dotnet` commands, I'm just experiencing this with `dotnet workload` subcommands right now.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/blob/957ae5ca599fdeaee425d23928d42da711373a5e/src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs#L145

**Comment by marcpopMSFT** [comment]
@gkulin will your fix for https://github.com/dotnet/sdk/issues/23446 hide the advertising manifest updates as mentioned in this one as well?

**Comment by gkulin** [comment]
@marcpopMSFT the fix for #23446 won't also hide the updates mentioned in this but it would be a similar change

**Comment by sandyarmstrong** [comment]
I should stress that the manifest updates are just part of the issue here. The start/end indicators the other problem.

**Comment by marcpopMSFT** [comment]
> I should stress that the manifest updates are just part of the issue here. The start/end indicators the other problem.

Good point. I think the only reason we have the start/end indicators is because there is other output beyond the json. We likely wouldn't need those if that output were hidden by default (and would only include the indicators when verbosity level is high).

**Comment by sandyarmstrong** [comment]
> We likely wouldn't need those if that output were hidden by default (and would only include the indicators when verbosity level is high).

Could also just output the manifest errors and other verbose items to stderr instead of stdout.

**Comment by baronfel** [comment]
Summary for anyone that picks this up:
* We should emit the verbose "failed to ..." output to stderr
* We should remove the boundary markers

**Comment by marcpopMSFT** [comment]
You were looking into cleaning up the output of workloads already

**Comment by MiYanni** [comment]
> Summary for anyone that picks this up:
> 
> * We should emit the verbose "failed to ..." output to stderr
> * We should remove the boundary markers

@baronfel A few q's/comments:
- This is definitely a *breaking change* issue as altering output intended for programmatic consumption will affect current programs using this information.
- I agree with both bullet points you mention for changes.
- Do you think we should spit out the JSON *prettified* instead of *minified*? It should be easy to fix. Or we could have an option for it too.
- There is [this issue](https://github.com/dotnet/sdk/issues/22882) describing adjustment of the content. I think we should adjust *both* output and content at the same time since they'd both be breaking.

Thoughts?

**Comment by baronfel** [comment]
Good comments!

* breaking change: yes, and as such we would have to punt this to 9 now. Still, the best time was yesterday and the next-best time is today!
* prettified vs minified: since the purpose here is machine-readable we should print minified json. if a user is using this interactively we'd point them to the powershell json printing commands, or to `jq` for easier rendering (including colorization)
* yeah, we should bundle both issues into one breaking change - we could implement them separately, but document them as a unit if we didn't want a giant PR for example.
