### ISSUE TITLE
Is Blazor Hot Report Supported for Visual Studio for Mac ?

### ISSUE THREAD

**Issue by chhinsras** [dotnet/sdk#22884]

**Comment by pranavkm** [comment]
FYI @LyalinDotCom

**Comment by LyalinDotCom** [comment]
.NET Hot Reload is not yet supported in Visual Studio for Mac (for any scenario). We don't have an ETA yet but we are actively working on it. Sorry I don't have more exact information at this time.

**Comment by chhinsras** [comment]
> .NET Hot Reload is not yet supported in Visual Studio for Mac (for any scenario). We don't have an ETA yet but we are actively working on it. Sorry I don't have more exact information at this time.

What about visual studio code

**Comment by LyalinDotCom** [comment]
You can use .NET Hot Reload with your favorite code editors using the CLI tool `dotnet watch` where Hot Reload is on by default for supported projects.
