### ISSUE TITLE
Custom project types do not import project extensions

### ISSUE THREAD

**Issue by jeffkl** [dotnet/sdk#2288]
When defining a custom project type, ie something that is not a `.csproj`, then the property `LanguageTargets` is not specified.  So the .NET Core SDK falls back to just importing `Microsoft.Common.CurrentVersion.targets`.  However, the import of `$(MSBuildProjectExtensionsPath)\$(MSBuildProjectName).*.g.targets` is in `Microsoft.Common.targets`.  This means build logic from NuGet packages is not imported correctly since the `.g.targets` is not imported.

https://github.com/dotnet/sdk/pull/539/files#diff-0f39add6afb079d5b2b9c0af850df7d7R35

If `LanguageTargets` is empty, I think we should import `Microsoft.Common.targets` which imports `Microsoft.Common.CurrentVersion.targets`.  I'm not sure why we decided on the latter.

I can send a PR if we agree on the fix.  @dsplaisted thoughts?

**Comment by dsplaisted** [comment]
Yes, this sounds like a good thing to do (but that's no guarantee it won't break something).  Any thoughts @nguerrera?

**Comment by nguerrera** [comment]
Sounds like the right thing to do indeed. I can't think of a realistic scenario that would break (famous last words). It seems like pure oversight that we have it this way now. I'm not seeing any reason for it describe in #539. Let's go ahead.
