### ISSUE TITLE
package.config and *.csproj tag warnning

### ISSUE THREAD

**Issue by kelicto** [dotnet/sdk#22907]
Warnning:
![image](https://user-images.githubusercontent.com/23723575/144784211-210a0716-0c21-45a4-84a6-ef7010a36acd.png)
![image](https://user-images.githubusercontent.com/23723575/144837728-d70abc4c-d367-44d4-871f-b2582743ec0f.png)

Suggestion:
![image](https://user-images.githubusercontent.com/23723575/144784171-61de29bf-3765-4245-b38a-f5ff11f63d11.png)

**Comment by baronfel** [comment]
This seems to be a request for better intellisense/validation for package.config files, is that correct? If so, which editor are you currently using?

**Comment by kelicto** [comment]
> This seems to be a request for better intellisense/validation for package.config files, is that correct? If so, which editor are you currently using?

Visual Studio 2019

**Comment by baronfel** [comment]
Thanks for confirming, @kelicto.  In that case I would suggest [reporting feedback](https://visualstudio.microsoft.com/vs/support/how-do-i-provide-feedback-or-report-an-issue-with-a-visual-studio-service/) with the product, mentioning this issue as well as perhaps the [matching NuGet issue for an XSD](https://github.com/NuGet/Home/issues/1836), as your request isn't really a fit for the SDK repo.  In addition, I expect you will be encouraged to use PackageReference as much as possible in your code, which lives inside MSBuild XML files. These files have better tooling support overall, as well as many other benefits that are outlined [in our documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#benefits-of-using-packagereference)

**Comment by kelicto** [comment]
> Thanks for confirming, @kelicto. In that case I would suggest [reporting feedback](https://visualstudio.microsoft.com/vs/support/how-do-i-provide-feedback-or-report-an-issue-with-a-visual-studio-service/) with the product, mentioning this issue as well as perhaps the [matching NuGet issue for an XSD](https://github.com/NuGet/Home/issues/1836), as your request isn't really a fit for the SDK repo. In addition, I expect you will be encouraged to use PackageReference as much as possible in your code, which lives inside MSBuild XML files. These files have better tooling support overall, as well as many other benefits that are outlined [in our documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#benefits-of-using-packagereference)

I found UI project use classic xml type can do better. I used MsBuild XML project type, It seems to be good for UI projects are not able to support, in particular, winform.
