### ISSUE TITLE
msbuild publish fails for runtime target win-x86

### ISSUE THREAD

**Issue by Envitec** [dotnet/sdk#22928]
When I publish a project from Visual Studio 2022 using **Publish** Option the publish works correctly.
The runtime target in this case is win-x86

When I try to build and publish from command line using:
**msbuild -m myproject.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml** 

I am getting this error **publish fails with error 'obj\project.assets.json' doesn't have a target for 'net6.0/win-x86'**

However **dotnet publish myproject.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml** works correctly

Has something changed with VS 2022 or am I missing something while building project with msbuild? 

The application that I am working on is .Net 6.0 console application.

**Comment by ryank425** [comment]
dotnet publish would call MSBuild according to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild

The bigger difference I see is that you are using myproject.csproj for one and myproject.sln for other. You should be able to use the project file to build the same as well (https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2022). 

Does the publish still fail with using same project file and not solution file?

**Comment by Envitec** [comment]
> dotnet publish would call MSBuild according to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild
> 
> The bigger difference I see is that you are using myproject.csproj for one and myproject.sln for other. You should be able to use the project file to build the same as well (https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2022).
> 
> Does the publish still fail with using same project file and not solution file?

When I do 
**msbuild -m myproject.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml"**

from VS 2022 Developer Command prompt the project builds but it ignores DeployOnBuild and PublishProfile parameters. It is just plain old build, bit it succeeds.

**Comment by baronfel** [comment]
Hello @Envitec, I agree that at a high level `dotnet publish` and `dotnet msbuild /t:Publish` should behave the same. Clearly that's not the case here once you're explicit about the project to publish. I think the easiest way to figure out the root cause for the differences here is for you to run both of the builds with the `-bl` flag added. This will create a MSBuild Binary Structured Log, which you can then view interactively in the [MSBuild Log Viewer](https://msbuildlog.com/) tool, either on your own system or in the web-based version of the tool.  This is the easiest way to:
* verify the targets, properties, and inputs to the builds are the same, and
* see all of the logic executed during the build

I would be especially interested in learning how the value of the PublishProfile property is used in your build in each case.

**Comment by Envitec** [comment]
> Hello @Envitec, I agree that at a high level `dotnet publish` and `dotnet msbuild /t:Publish` should behave the same. Clearly that's not the case here once you're explicit about the project to publish. I think the easiest way to figure out the root cause for the differences here is for you to run both of the builds with the `-bl` flag added. This will create a MSBuild Binary Structured Log, which you can then view interactively in the [MSBuild Log Viewer](https://msbuildlog.com/) tool, either on your own system or in the web-based version of the tool. This is the easiest way to:
> 
> * verify the targets, properties, and inputs to the builds are the same, and
> * see all of the logic executed during the build
> 
> I would be especially interested in learning how the value of the PublishProfile property is used in your build in each case.

Hello @baronfel 

I have a C++ / .Net Core CLR project in solution that the main project is dependent on and I get this error in publish:

error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.

When I use VS 2022 to publish from Publish page it seems to handle that successfully.

MSBuild Binary Structured Log will be too much for me to handle I guess. I will give it a try if possible.

**Comment by baronfel** [comment]
If you have a repository or sample project that shows this behavior, then I'd be happy to take a deeper look as well.

**Comment by Envitec** [comment]
My project is in a private in-house repository. 

Building managed C++ project separately and publishing the project with assembly reference rather than project reference seems to fix my issue for the moment. 

Thanks for comments and suggestions.
