### ISSUE TITLE
Embedded version of NuGet client does not respect "no_proxy" configuration

### ISSUE THREAD

**Issue by jbogard** [dotnet/sdk#22942]
### Describe the bug
This is the same issue as https://github.com/microsoft/vcpkg/issues/21057. I have a proxy setup script configured on a corporate laptop that does not apply for VPN connections (I'm on a VPN). However, NuGet will still use this configuration even though it does not apply. I then get errors trying to use any NuGet-related `dotnet` command, such as `dotnet add package` or `dotnet tool restore`. I will get an error:

```
Unable to load the service index for source https://api.nuget.org/v3/index.json
The proxy tunnel request to proxy '<the internal proxy server>' failed with status code '407'.
```

I can reach that URL via a browser, and I can restore using Visual Studio. Upgrading from NuGet version 5.10 to 5.11 allowed me to use `nuget install Foo`. 

### To Reproduce
Configure proxy to have:
- Automatically detect settings ON
- Use setup script ON
- A script address to a proxy server that requires authentication

### Further technical details
I validated on 6.0.100, 6.0.101, and 6.0.200-preview.21607.2.

**Comment by kosa-gyula-77** [comment]
Hi @jbogard , Have you been able to come across this issue pls? 
For me the Windows proxy credentials dialog always pops up when I try to browse a package source in Visual Studio for which I set `no_proxy` in `C:\Users\me\AppData\Roaming\NuGet\NuGet.Config`:

```
<configuration>
  <config>
    <add key="no_proxy" value="https://artifactory.mycompany.net" />
```
The package source 
- is hosted by Artifactory
- requires authentication
- `packageSourceCredentials` is set in NuGet.Config using an Identity Token for Artifactory as password.

Windows proxy settings:
- Automatically detect settings OFF
- Use setup script ON
- The script sets `DIRECT` for `*.mycompany.net`

Microsoft Visual Studio 
- Professional 2022 (64-bit)
- Version 17.8.6

**Comment by jbogard** [comment]
Nope, I changed clients and no longer have that laptop or VPN.
