### ISSUE TITLE
Get back old templates (console, mvc, etc) into dotnet new

### ISSUE THREAD

**Issue by arthrp** [dotnet/sdk#23029]
New app templates - the ones used when creating app via `dotnet new` - may look pythonish but they are not practical. IMO it'd be nice to add old ones back even under different name.

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of <https://github.com/dotnet/sdk/issues/19672>?

**Comment by arthrp** [comment]
@KalleOlaviNiemitalo yes and no. That issue is about asp.net template, this one is about console project template.

**Comment by vlada-shubina** [comment]
Related:
https://github.com/dotnet/templating/issues/3654
https://github.com/dotnet/templating/issues/3985

**Comment by JanKrivanek** [comment]
This topic is being captured by https://github.com/dotnet/docs/issues/27420
