### ISSUE TITLE
"Breakpoints set but not yet bound"

### ISSUE THREAD

**Issue by johnpankowicz** [dotnet/sdk#2305]
I create a project with "dotnet new angular". When a breakpoint is set on a Typescript instruction, it shows as a open red circle when run. The error message is "The breakpoint will not currently be hit. Breakpoints set but not yet bound."

I am currently using: VS Pro 15.7.2, .Net Core SDK 2.1.300 (x64) and .Net Core Runtime 2.1.0 (x64)

This problem started when I updated from .Net Core SDK 1.x.

I tried other SDK 2.x releases. It fails in v2.1.4 & v2.1.300. But breakpoints succeed in v2.0.0, 2.1.200 & 2.1.201. This difference is that, when it succeeds,  each of the SDKs generate the files webpack.config.js & webpack.config.vendor.js in the root of the project during the "dotnet new angular".
The other difference is that the working projects define the location of "ClientApp" in webpack.config.js. In those projects that fail, the ClientApp location is defined in startup.cs.

I wish that I could use one of the SDKs where debugging works. But for other reasons, I can't. So I am stuck until this issue is resolved.

Some more info:
Using sdk v2.1.201, the generated package.json contains:
	"typescript": "2.4.1",
	"webpack": "2.5.1",
    	"webpack-hot-middleware": "2.18.2",
	"webpack-merge": "4.1.0",

Using sdk v2.1.300,the generated package.json contains:
	"typescript": "~2.5.3"
   but does not contain entries for webpack.  In node_modules/.bin there is a "webpack.cmd" whose version is 3.11.0.

When I type "tsc -v" at in a VS2017 Developer Command window, I get:
	version 2.8.4

**Comment by livarcocc** [comment]
@natemcmaster is this an issue with the templates?

**Comment by natemcmaster** [comment]
Sounds like an issue with the JS/TS tooling in VS to me. But if you can identify that a fix should be made to aspnet templates, the code for `dotnet new angular` is here: https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp

**Comment by livarcocc** [comment]
I asked you this because of this:

```
Using sdk v2.1.300,the generated package.json contains:
"typescript": "~2.5.3"
but does not contain entries for webpack. In node_modules/.bin there is a "webpack.cmd" whose version is 3.11.0.
```

But I agree with you that this seems like a JS/TS tooling issue.

@johnpankowicz I am going to close this issue and this is not the right repo for this. I believe  the best way to get an answer to this problem is to file a VS Feedback item through VS itself. Comment here if yo need help with that.

**Comment by johnpankowicz** [comment]
@livarcocc If I am using the same version of VS in all my tests but only changing the version of the SDK, I don't understand why you think the problem is the JS/TS tooling in VS.

**Comment by livarcocc** [comment]
Because there may be changes there that they need to react to. Because there may be a runtime exception happening when attaching the debugger. Because I need them to investigate why their component breaks due to an SDK change. Unfortunately, my team does not have the necessary expertise on that part of the VS tooling to understand it.

**Comment by johnpankowicz** [comment]
@livarcocc Thanks for explaining. There was a VS Feedback item which may be describing the same issue. I added my comments to it: https://developercommunity.visualstudio.com/content/problem/252929/typescript-debugging-in-visual-studio-debugger-doe.html

**Comment by johnpankowicz** [comment]
@livarcocc @natemcmaster I filled a new VS feedback item: [VS Developers](https://developercommunity.visualstudio.com/content/problem/268468/typescript-breakpoints-not-hit-in-visual-studio-15.html) I was asked to check the value of SourceRoot in wwwroot/dist/main-client.js.map. But a "dist" folder is not created when I use .Net SDK 2.1.300.  The bundled files appear to be created and served from memory. When I was using 2.1.201, it DID create a dist folder containing the bundled files -- and breakpoints DID in fact work then.
