### ISSUE TITLE
Centos7 yum Install asp.net core runtime issue

### ISSUE THREAD

**Issue by suylem** [dotnet/sdk#2308]
Dear:

 i meet one issue for install dotnet core sdk on centos 7 via yum command  . i had try use to command "yum install aspnetcore-runtime-2.1", it reports  "https://packages.microsoft.com/rhel/7/prod/dotnet-runtime-deps-2.1.0-rc1-rhel.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found"
Error downloading packages:
  dotnet-host-2.1.0_rc1-1.x86_64: [Errno 256] No more mirrors to try.
  dotnet-runtime-deps-2.1.0-rc1-2.1.0_rc1-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by livarcocc** [comment]
It seems like you are trying to install the asp.net core runtime, not the asp.net core SDK.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/Home#3198
