### ISSUE TITLE
Appsettings environments don group in Microsoft.NET.Sdk.Worker

### ISSUE THREAD

**Issue by deinok** [dotnet/sdk#23106]
A `Microsoft.NET.Sdk.Worker` requires the following line in a `*proj` in order to join diferent environments of an appsettings.json

```xml
	<ItemGroup>
		<None Include="appsettings.*.json">
			<DependentUpon>appsettings.json</DependentUpon>
		</None>
	</ItemGroup>
```

In the case of `Microsoft.NET.Sdk.Web` this is not required

**Comment by vijayrkn** [comment]
The default nesting rules are different for web projects and worker projects. There is a preview feature to enable globing for all projects. Once you enable this, it should work. 

Also, you can create custom nesting rules as defined in the document : https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022

**Comment by deinok** [comment]
What is this preview feature? And why is it different in this case Worker vs Web in this case? It doesn't have too much sense

**Comment by vijayrkn** [comment]
For non-web projects, this feature is not enabled by default because of some performance considerations. You can track the status of the issue here : https://github.com/dotnet/project-system/issues/7161
