### ISSUE TITLE
Can't debug dotnet pack code from VS

### ISSUE THREAD

**Issue by erdembayar** [dotnet/sdk#23101]
### Exceptions (if any)

```
git checkout origin/release/6.0.1xx
build.cmd
eng\dogfood.cmd
.\artifacts\sdk-build-env.bat
devenv sdk.sln

```

When I start "dotnet pack" for simple console app from VS>>CLI project then 
![image](https://user-images.githubusercontent.com/8766776/146482490-a55a7024-9985-49ee-9fff-e8e0303dd56e.png)

<Project Sdk="Microsoft.NET.Sdk">

```
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net451</TargetFrameworks>
    <Version>1.2.3</Version>
    
  </PropertyGroup>

</Project>

```
### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
Are you running `dotnet pack` in the VS terminal or somewhere else?  You're mixing a few different things as the dogfood script is to enable the SDK you just built in your command window for you to test the SDK/CLI whereas the sdk-build-env.bat is to configure the SDK that you're using to build the SDK as we have a specific version listed in the global.json.

Try excluding dogfood.cmd from your steps and see if the action works.

**Comment by erdembayar** [comment]
Thank you for your response. I resolved another way.
