### ISSUE TITLE
SDK 6.0.1 (Hidden) Access Denied errors

### ISSUE THREAD

**Issue by glatzert** [dotnet/sdk#23138]
### Describe the bug
Installed SDK 6.0.1 on a machine where all other SDKs have been purged (the older ones by `Remove-Item`) so that no dotnet folder was left (this was after an automatic update failed to add the Runtime-Files itself).

Running via Azure-Devops-Build-Agent, I got this:
> C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1109: Runtime list file 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.1\data\RuntimeList.xml' was not found. Report this error to the .NET team here: https://aka.ms/dotnet-sdk-issue. [my.csproj]

### Solution

I traced with ProcMon and the problem is, that the ACL of many of the files is broken.
Instead of inheriting from the dotnet folder, it got ACLs only allowing access for admins.

```
Powershell saved the day:
PS C:\Program Files\dotnet> gci -Recurse | % { $acl = Get-ACL -Path $_.FullName; $acl.SetAccessRuleProtection($False,$True); Set-ACL -Path $_.FullName -AclObject $acl; }
```

**Comment by baronfel** [comment]
@joeloff have you seen this problem before with our installers?

**Comment by joeloff** [comment]
We are not touching the ACLs. The only exception is for the runtime breadcrumb store, which doesn't reside under Program Files. It should just be inheriting ACLs from Program Files.

Was this an App Services machine? Those images are created using a zip file of the SDK that's copied into Program Files, so not sure if that maybe cause this sort of issue.

**Comment by glatzert** [comment]
The machine is a windows server 2019.

We use it as Devops (on-prem) build machine.

I installed .net SDK manually via msi and my manager told me (somewhen around creating this issue) that Windows update failed. Then the issues started showing up as described.

We did not use dotnet from those "install dotnet" tasks.

**Comment by baronfel** [comment]
@glatzert have you seen this happen again since you reported it? If not I'm inclined to close this as a one-off since we haven't seen any other user reports.

**Comment by glatzert** [comment]
It did not occur again.
