### ISSUE TITLE
dotnet tool install --local takes .config/nuget.config instead of nuget.config in current working directory

### ISSUE THREAD

**Issue by tremblaysimon** [dotnet/sdk#23135]
### Describe the bug
When you try to install a dotnet tool from current working directory and there is a ~/my-dotnet-project/.config/nuget.config file present, it will not take ~/my-dotnet-project/nuget.config in priority even if the documentation says that it should take it. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#options 

### To Reproduce

1. Create a simple empty project in ~/my-dotnet-project
2. Create a tool manifest with `dotnet new tool-manifest`
3. Create a valid nuget.config in ~/my-dotnet-project/.config/ folder
4. Modify the packageSource URL of that .config/nuget.config file to something that will not work (to easily see that it will be that file that is taken in priority)
5. Create a valid nuget.config in the ~/my-dotnet-project/
6. Install a tool available on nuget.org like CycloneDX  `dotnet tool install --local CycloneDX` from ~/my-dotnet-project/ current working directory

Observe an error like this:

```
:~/workspace/test-dotnet-webapi-nuget$ dotnet tool install --local CycloneDX
/usr/share/dotnet/sdk/5.0.404/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3-bug/index.json. [/tmp/xdqilbl3.x2b/restore.csproj]
/usr/share/dotnet/sdk/5.0.404/NuGet.targets(131,5): error :   Response status code does not indicate success: 404 (Not Found). [/tmp/xdqilbl3.x2b/restore.csproj]
The tool package could not be restored.
Tool 'cyclonedx' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

### Further technical details
``` 
.NET SDK (reflecting any global.json):
 Version:   5.0.404
 Commit:    72c68b830a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.404/

Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  3.1.416 [/usr/share/dotnet/sdk]
  5.0.404 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment]
I agree @tremblaysimon. Currently the config file is being resolved from the location of the tools manifest, but I believe as you've stated here that it should be resolved from the working directory of the executed command. This incorrect path is being passed in [here](https://github.com/dotnet/sdk/blob/3015692c6c3748b7d13387cbecbb84604b633b77/src/Cli/dotnet/ToolPackage/ToolPackageInstaller.cs#L140), when we get around to tackling this.

**Comment by JiaqiWang18** [comment]
I would like to work on this if no one is currently working on it!

**Comment by baronfel** [comment]
That would be great! I left a comment above where I think any changes would need to go, but feel free to start a PR and ping the team if you have any questions :)

**Comment by tremblaysimon** [comment]
I did a pull request a couple of month ago https://github.com/dotnet/sdk/pull/24935

**Comment by baronfel** [comment]
Wow, I'm sorry I missed that. I'll try to respond to it with locations/patterns for making a test.

**Comment by dsplaisted** [comment]
The related PR has been merged, so I think we can close this.  Feel free to comment / re-open if that's not the case.
