### ISSUE TITLE
Provide a way to end a hot reload session when using Visual Studio but not using the debugger

### ISSUE THREAD

**Issue by dougwaldron** [dotnet/sdk#23143]
When I start an application in Visual Studio without using the debugger (for example using <kbd>CTRL-F5</kbd>), Hot Reload is enabled. Generally this is a good thing, but if I need to start making changes that aren't supported by Hot Reload, I start getting error messages in Visual Studio. The only way to end the Hot Reload session and avoid the error messages is to start the app *with* the debugger, then stop it again.

There needs to be a simple way to end a Hot Reload session. I suggest adding an option in the Hot Reload button dropdown, a menu item in the Debug menu, and the <kbd>Shift-F5</kbd> shortcut.

**Comment by pranavkm** [comment]
@dougwaldron could you use the [VS feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report this? Thanks!
