### ISSUE TITLE
Generate app.config for .NET Framework projects that indicated a minimum framework

### ISSUE THREAD

**Issue by Pilchie** [dotnet/sdk#2319]
When targeting .NET Framework, we should generate an `app.config` file as part of build if the project doesn't specify one.  Otherwise, an app targeting 4.x will run on older 4.x machines, and fail at runtime with strange missing method exceptions.

(It's probably okay to do this only for sdk-style projects, as traditional templates include an app.config)

**Comment by davkean** [comment]
We should do this regardless of whether it exists or not, similar to binding redirects.

**Comment by nguerrera** [comment]
@davkean Meaning if it exists, but has no `<supportedRuntime>` entry, then we add the entry? If so, I agree.

**Comment by davkean** [comment]
Yeah.

**Comment by wli3** [comment]
This is what I am thinking.

Add a task that will create yet another intermediate .config based on `GenerateBindingRedirects`'s output(`obj\Debug\net452\win7-x86\my.exe.config`). And if it is generated, kick bindingredirect's output out of `$(AppConfigWithTargetPath)` and replace it. PrepareForRun will copy AppConfigWithTargetPath to bin

So it will be `aftertargets=GenerateBindingRedirectsUpdateAppConfig` `beforeTargets=PrepareForRun`

OR

I will directly change the result of GenerateBindingRedirects's intermediate output.

They all have to override something

**Comment by wli3** [comment]
talked to Daniel, we need to verify, if there is no app.config, GenerateBindingRedirects might not create. So we should create app.config **before**  GenerateBindingRedirects

**Comment by wli3** [comment]
I tested, if there is no app.config, BindingRedirects will still be generated

**Comment by wli3** [comment]
@dsplaisted should I do the same thing for dll (full framework libraries)

![image](https://user-images.githubusercontent.com/6993335/43546290-1c732930-958d-11e8-822c-510a3e7fe98c.png)

**Comment by wli3** [comment]
if app.config is defined and if it is library then add supportedruntime. Sounds complicated. Maybe just do not generate it at all? full framework class library template won't have it

**Comment by wli3** [comment]
just skip the target if $(OutputType) != "Exe"

**Comment by nguerrera** [comment]
Careful with OutputType != Exe, there is also WinExe. We have another property to use for this, looking for its name.

**Comment by nguerrera** [comment]
`$(HasRuntimeOutput)`
