### ISSUE TITLE
Question: Is a M1 Mac required to build Mac-arm64 App? 

### ISSUE THREAD

**Issue by JvB94** [dotnet/sdk#23195]
Hello,

is a M1 Mac required to build a native m1 App of can i do it with a Intel Maschine as well without any issues?

**Comment by marcpopMSFT** [comment]
With some exceptions, you can use any SDK to target any other configuration. See the list of RIDs you can use for targeting: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog.  For M1 machines, you'll want to target osx.11.0-arm64 (or higher) and you'll need to sign the application before the M1 will allow it to run.  

Does that answer your questions?
