### ISSUE TITLE
dotnet watch not running on linux

### ISSUE THREAD

**Issue by jaseelpalle** [dotnet/sdk#23238]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by pranavkm** [comment]
`dotnet-watch` under hot reload intercepts Console.Input to listen for a user pressing `Ctrl+R` and restart the app. This really doesn't work very well in apps that are also trying to read console input. The PR adds an additional `--non-interactive` switch that prevents watch from intercepting Console.In. This should be available as part of the 7.0 SDK. For 6.0, you can run the app without hot reload `dotnet watch --no-hot-reload` as a workaround.
