### ISSUE TITLE
Properties and items aren't logged at evaluation for `dotnet build`

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#23248]
Unlike MSBuild, when you run `dotnet build`, something is preventing the new behavior of logging properties and items after evaluation. 

As a result we get legacy broken behavior where some properties and items are logged for some projects at ProjectStarted, but not others, and none at all are logged at evaluation.

This is very bad and we should fix this soon.

**Comment by KirillOsenkov** [comment]
I saw six loggers under debugger, any idea if there are more?

**Comment by rainersigwald** [comment]
AFAIK this is the only default addition:

https://github.com/dotnet/sdk/blob/cf37f14435841e58da10c125a0ee788ce7a59866/src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs#L36

I also pointed you to the wrong implementation of the logger offline--we pass both the distributed and central logger, but it seems only the central logger needs to opt in for everything to work.

**Comment by KirillOsenkov** [comment]
Yes, seems reasonable: I saw 3 loggers on the build parameters, I'm guessing those are: Console, BinaryLogger and this logger. I saw 6 loggers on the LoggingService, and it means one central, one forwarding for each of those??

So it adds up. When we have a build of dotnet with this change, a simple way to test is just build any project with console and /bl and see if the evaluations have properties and items:

![image](https://user-images.githubusercontent.com/679326/148134934-246448cd-2d41-442c-b0b8-03685083d3fa.png)

**Comment by rainersigwald** [comment]
Yup, that's what I see with my private build:

![image](https://user-images.githubusercontent.com/3347530/148135460-818b2405-4b75-4ef8-ae90-67c447a77877.png)

**Comment by KirillOsenkov** [comment]
Amazing!

I'm also thinking that currently if there are unenlightened loggers, there's no way to force the new behavior.

We should respect the environment variable if set, and force it to true regardless of which loggers. This would give us a way to turn it on via an environment variable as a workaround. Would have really saved my bacon right about now :)

**Comment by KirillOsenkov** [comment]
Something like this in the LoggingService.cs?

![image](https://user-images.githubusercontent.com/679326/148136166-93ec9a28-9dc1-4c25-9461-58b45b65d4cd.png)

**Comment by KirillOsenkov** [comment]
I can PR this in a sec

**Comment by rainersigwald** [comment]
Yeah, I'd be on board for that.

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/msbuild/pull/7217
