### ISSUE TITLE
Unable to install dotnet-sdk-2.1 in Ubuntu 16.04 

### ISSUE THREAD

**Issue by ponarunkumar** [dotnet/sdk#2326]
Followed the steps provided as per https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04
However, the package seems to be updated.

Reference steps to recreate the issue:
:~$ sudo wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
~$ sudo dpkg -i packages-microsoft-prod.deb
(Reading database ... 323159 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-3) over (1.0-3) ...
Setting up packages-microsoft-prod (1.0-3) ...
~$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.2.26).
The following packages were automatically installed and are no longer required:
  linux-headers-4.13.0-41 linux-headers-4.13.0-41-generic linux-image-4.13.0-41-generic linux-image-extra-4.13.0-41-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
~$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease                            
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease                          
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease       
Hit:5 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu xenial InRelease
Ign:6 https://storage.googleapis.com/download.dartlang.org/linux/debian stable InRelease
Hit:7 https://deb.nodesource.com/node_10.x xenial InRelease
Hit:8 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release
Hit:9 https://dl.yarnpkg.com/debian stable InRelease
Hit:10 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Reading package lists... Done 
:~$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'
$ 

sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'

**Comment by livarcocc** [comment]
I believe this may be the same as this one: https://github.com/dotnet/cli/issues/9370.

@leecow, this seems like another report of the same issue.

**Comment by leecow** [comment]
Yep, could be the same issue. I've started a thread with repo owners to see if there's something on their side.

**Comment by livarcocc** [comment]
@ponarunkumar can you check the issue that I linked to and validate if your situation is the same one there?

**Comment by ponarunkumar** [comment]
yes @livarcocc , it is the same as the linked issue dotnet/cli#9370. with the status of closed. But the issue still persists, looks like it is something related to the i686 32-bit or 64-bit related libraries as mentioned in that thread. I am still facing the exact same error after trying few alternatives.

**Comment by livarcocc** [comment]
The issue is closed because it is really external to us. Also note that we don't support the .NET Core SDK for 32 bit linux.
