### ISSUE TITLE
dotnet-install.sh fails because the download URL returns .

### ISSUE THREAD

**Issue by wheredia** [dotnet/sdk#23296]
### Step to reproduce 

1. Create a docker container using alpine 3.14
2. Get all dependencies informed in [https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine) 
3. Download using `wget ` comand the installer script [https://dot.net/v1/dotnet-install.sh](https://dot.net/v1/dotnet-install.sh) and change mode to this file.
4. Execute `./dotnet-install.sh -c 6.0`

### Expected behavior

Should be able to download the binaries

### Actual behavior

If supplied with -c parameter has 6.0. the installer script return fail with the following error message: 

`#11 0.806 dotnet-install: Download attempt #1 has failed:  Unable to download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0/latest.version. Returned HTTP status code: .`

annex evidences: 
![image](https://user-images.githubusercontent.com/15109469/148423832-96b74e74-b096-403e-a707-6b57e839a956.png)

### Enviroment data

Alpine 3.14

**Comment by KalleOlaviNiemitalo** [comment]
Apparently, the `wget` command in BusyBox does not support the `--waitretry 2` option that dotnet-install.sh uses. You might be able to work around the problem by installing `curl` so that dotnet-install.sh would then use that instead of BusyBox's `wget`.

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of <https://github.com/dotnet/install-scripts/issues/216>, which has been fixed already. I don't know whether the corrected version of dotnet-install.sh is available anywhere in <https://dot.net/>, but you could perhaps get it from <https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh>.

**Comment by wheredia** [comment]
Hi @KalleOlaviNiemitalo, I tried to use the dotnet-install.sh from github.com and it´s  also fails althought it'sdue to another fails. 
![image](https://user-images.githubusercontent.com/15109469/148428331-a80b4b3c-5fec-41a3-92c6-50ba8913f974.png)
On the other hand, the failure of waitretry is secondary. The original fail is generated when it trying to download from  [https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0/latest.version](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0/latest.version) this return a http status code has ".". Please look it at next imagen: 
![image](https://user-images.githubusercontent.com/15109469/148429213-e2851d1d-9bc0-4983-a48d-a4b32d9e7d36.png)

**Comment by wheredia** [comment]
@KalleOlaviNiemitalo I will try install curl

**Comment by KalleOlaviNiemitalo** [comment]
> I tried to use the dotnet-install.sh from github.com and it´s also fails althought it'sdue to another fails

Did you download the HTML page <https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh> or the raw script <https://github.com/dotnet/install-scripts/raw/main/src/dotnet-install.sh>?

**Comment by wheredia** [comment]
Hello again @KalleOlaviNiemitalo!! I think I finally struck gold.  I just reinstalled `wget` in the alpine 3.14 container and it worked. Thank very much for your help Mr. @KalleOlaviNiemitalo
