### ISSUE TITLE
`dotnet` command has been removed from openSuse Leap 15.3 `dotnet-host` package

### ISSUE THREAD

**Issue by n-t-roff** [dotnet/sdk#23304]
### Describe the bug
After an update of the openSuse Leap 15.3 `dotnet-host` package the `dotnet` command is not installed anymore.

### To Reproduce
The simplest way should be to analyse the packages from the source https://packages.microsoft.com/opensuse/15/prod/. There the dotnet-host-5.x packages contain a bin/dotnet file while the dotnet-host-6.x packages do not.

**Comment by KalleOlaviNiemitalo** [comment]
This issue was mislabelled with Area-NuGet. This is about RPM packages, not NuGet packages.
