### ISSUE TITLE
Solved by install this update from WU catalog:

### ISSUE THREAD

**Issue by Paresh98000** [dotnet/sdk#23314]
Solved by install this update from WU catalog:
https://www.catalog.update.microsoft.com/Search.aspx?q=.NET%205.0.12

_Originally posted by @sfc9982 in https://github.com/dotnet/sdk/issues/23307#issuecomment-1007218389_

Dotnet core 3.1.21 not installed cause by error that says newer version is already installed

Dotnet Framwork 5.0.21 is installed by this link

**Comment by marcpopMSFT** [comment]
Closing as the linked issue is closed and it's not clear if the issue still exists.
