### ISSUE TITLE
SDK workload improvements

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#23355]
- [x] https://github.com/dotnet/sdk/pull/22446
- [x] #23384
- [x] #23373
- [ ] #23369
- [x] #23370
- [ ] #23371
- [ ] #23372
- [x] #21741 
- [x] #23951

**Comment by AraHaan** [comment]
Will this be possible on 7.0.1xx still?

**Comment by jeromelaban** [comment]
@marcpopMSFT would you know if there another related aggregated issue with workloads improvements to track? Features like [workload pinning](https://github.com/dotnet/sdk/issues/27402) or [performance](https://github.com/dotnet/sdk/issues/24843), for instance?
