### ISSUE TITLE
Suggestion: Implement StyleCop file on SDK repo

### ISSUE THREAD

**Issue by JonKohler** [dotnet/sdk#2335]
Recently, upstream Microsoft PowerShell has implemented StyleCop on their primarily C# repo. Given that there is such a tight interaction between PowerShell core and dotnet SDK, I think it would be worth while to align the two projects on style guidance.

You can see the two relevant PR's for PowerShell master, here: 
https://github.com/PowerShell/PowerShell/pull/6930
https://github.com/PowerShell/PowerShell/pull/6986

Ultimately resulting in this file, here: 
https://github.com/PowerShell/PowerShell/blob/master/stylecop.json

We're aligning our latest C# PowerShell core project with this same guidance, and have seen great benefit.

This is one of those "one file" type of easy implementations; however, style guidance is always a hot topic. As such, check out the PR's I mentioned, where the PowerShell community went back and forth on exactly how to tune this. As a result, I think (honestly) we could just pull that single file from the PowerShell stream, and implement it here with ease.

This will ultimately result in similarly stylized code, which should help the overall community working in both code bases.

cc @TravisEz13 and @iSazonov and @SteveL-MSFT for context from the PoSh side.

**Comment by sharwell** [comment]
From https://github.com/dotnet/cli/issues/9490#issuecomment-397296728:

> I would suggest not adding a StyleCop.Settings file, and instead add only a stylecop.json file for use with StyleCop Analyzers. The two products do not have exact feature parity and are not meant to be used together.

**Comment by JonKohler** [comment]
from https://github.com/dotnet/cli/issues/9490#issuecomment-397303225

> @sharwell - I've amended both of the issues that I've filed to point to
> https://github.com/PowerShell/PowerShell/blob/master/stylecop.json
> 
> which came in the same aforementioned PR. Did this edit at the top level issue so that it doesn't get buried in comments

**Comment by TravisEz13** [comment]
cc @daxian-dbw

**Comment by livarcocc** [comment]
Same statement as from the CLI. We don't really have plans to do that at the moment.
