### ISSUE TITLE
SDK acquisition improvements

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#23356]
* [ ] #23374
* [ ] #23375
* [ ] #23376
* [ ] #23377
* [ ] Support Linux package manager based installations for workloads.

**Comment by anangaur** [comment]
Is there scope for some rationalization across winget on windows, apt on linux, dotnet install scripts and now this method?

**Comment by baronfel** [comment]
Closing this out by rolling it into https://github.com/dotnet/sdk/issues/14962
