### ISSUE TITLE
With .NET 7 x86 SDK, Testhost process exited with error: It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#23362]
**--Repro Steps---**
1. Install .NET 7 x86 SDK(https://github.com/dotnet/installer) on Win x64 OS
2. Create a UT project and run it

**--Expected Result --**
1. dotnet test works fine

**--Actual Result--**
1. Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '7.0.0-alpha.1.22059.2' (x64) was not found.
![image](https://user-images.githubusercontent.com/1578239/148919893-8af04dbe-0d56-47af-8b46-0a42adb088d1.png)

**--Note--**
It didnot repro with .NET 6 x86 SDK

**Dotnet info**
c:\6t>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   7.0.100-alpha.1.22060.7
 Commit:    4a2d57a652

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\7.0.100-alpha.1.22060.7\

Host (useful for support):
  Version: 7.0.0-alpha.1.22059.2
  Commit:  a2af629476

.NET SDKs installed:
  6.0.200-preview.22055.18 [C:\Program Files (x86)\dotnet\sdk]
  7.0.100-alpha.1.22060.7 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-alpha.1.22057.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.22059.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-alpha.1.22055.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nohwnd** [comment]
The testing works as expected. You have an AnyCPU dll that targets net7.0, that you somehow built (probably via the x86 SDK). You run dotnet test from x64 dotnet.exe. It inspects the dll and sees that it is AnyCPU, so the bitness of dotnet.exe is used to resolve the runtime = x64. You don’t have x64 net7.0 runtime so it fails. If the dll was targeting x86, or if you used x86 dotnet.exe, or if you forced x86 via dotnet test --arch=x86 the tests would run correctly.

**Comment by nohwnd** [comment]
It actually did not work as expected when calling from 32-bit dotnet. This is fixing that issue: https://github.com/dotnet/sdk/pull/23422

**Comment by WenJunJi01** [comment]
Environment: VS 17.2.0 Preview 1.0 [32118.273.main] + .NET 7 X86 SDK:7.0.100-alpha.1.22068.17(runtime-7.0.0-alpha.1.22066.4) 

CLI:
"Testhost process exited with error: It was not possible to find any compatible framework version..." is not displayed, instead the following info is shown:
![image](https://user-images.githubusercontent.com/87680983/150085079-3b0bb298-970c-469c-ba6b-28adf467aba0.png)
VS:
But the same issue occurred in Tests Output Pane when running a UT project in Test Explorer on VS. 
![image](https://user-images.githubusercontent.com/87680983/150083354-7c734d68-2ed3-4984-9749-4d73c27510e1.png)

**Comment by MarcoRossignoli** [comment]
@WenJunJi01 first issue with
```
x86/dotnet test
```
it's related to a problem with vstest packaging(I think it never worked in past). 
You should try to use sdk with the fix
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0-preview-20211130-02" />
```

For the VS issue looks like the sdk used to run the test doesn't have the fix @nohwnd reported here https://github.com/dotnet/sdk/issues/23362#issuecomment-1012871163

Can you enable verbose VS logging and attach the logs so we can verify the sdk version used.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/7894084/150121069-61b2aa68-f656-452e-8cfe-afd3c306b6a4.png">
You should find the path looking at Tests output after the failure.

**Comment by WenJunJi01** [comment]
@MarcoRossignoli  I followed your steps to enable verbose VS logging and got the logs. Log file attached.
[logs.txt](https://github.com/dotnet/sdk/files/7902809/logs.txt)

**Comment by MarcoRossignoli** [comment]
Looking at the log I don't see nothing strange from vstest runner, you're running a x64 app for 7.0 tfm inside VS, looks like you're missing the installation of 7.0 x64.

Install this one https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe should fix the issue

# Log anaylisis

<img width="951" alt="image" src="https://user-images.githubusercontent.com/7894084/150296427-780ea83d-69a1-4954-81e9-ef4287055659.png">

The runsetting doesn't have any platform specified
```xml
<RunSettings>
    <BoostTestInternalSettings xmlns:xsd= \"http://www.w3.org/2001/XMLSchema\" xmlns:xsi= \"http://www.w3.org/2001/XMLSchema-instance\">
        <VSProcessId>12712</VSProcessId>
    </BoostTestInternalSettings>    
    <RunConfiguration>
        <ResultsDirectory>C:\\Users\\v-wenjj\\source\\repos\\TestProject3\\TestResults</ResultsDirectory>
        <SolutionDirectory>C:\\Users\\v-wenjj\\source\\repos\\TestProject3\\</SolutionDirectory>
        <CollectSourceInformation>False</CollectSourceInformation>
    </RunConfiguration>
    <GoogleTestAdapterSettings xmlns:xsd= \"http://www.w3.org/2001/XMLSchema\" xmlns:xsi= \"http://www.w3.org/2001/XMLSchema-instance\">
        <SolutionSettings>
            <Settings />
        </SolutionSettings>
        <ProjectSettings />
    </GoogleTestAdapterSettings>
</RunSettings>
```
And we're processing an AnyCPU test lib so we infer the architecture from the context(x64 process).
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/7894084/150298020-119d906b-2dea-419f-9f5f-4299e8032e5a.png">
