### ISSUE TITLE
restore-toolset.* still referencing 6.0 RC2

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sdk#23383]
https://github.com/dotnet/sdk/blob/5ae51314f1d8602854c65550d4541ada686672e6/eng/restore-toolset.ps1#L24

and 

https://github.com/dotnet/sdk/blob/5ae51314f1d8602854c65550d4541ada686672e6/eng/restore-toolset.sh#L31

**Comment by dsplaisted** [comment]
@WingZer0123 We update the version in global.json periodically as needed.  Is there some sort of issue you are hitting?

**Comment by WingZer0123** [comment]
@dsplaisted it seems that these are no longer referencing `6.0.0-rc.2.21452.2` as listed in the list comment. The screenshot is the same version numbers I am seeing in both files referenced in the first comment.

**Comment by dsplaisted** [comment]
Yes, it looks like it has been updated since this issue was filed.
