### ISSUE TITLE
Since installing SDK 2.1.3, getting GenerateDepsFile error

### ISSUE THREAD

**Issue by jceddy** [dotnet/sdk#2338]
Since I installed the 2.1.3 SDK, I have started getting this error when building a solution that previously built correctly:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4018	The "GenerateDepsFile" task failed unexpectedly.
> System.ArgumentException: Can not add property Company.Product.Server.Core/3.1.2.0 to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
>    at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
>    at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
>    at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
>    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
>    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
>    at Newtonsoft.Json.Linq.JContainer.Add(Object content)
>    at Newtonsoft.Json.Linq.JObject..ctor(Object content)
>    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTarget(IReadOnlyList`1 libraries)
>    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTargets(DependencyContext context)
>    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context)
>    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context, Stream stream)
>    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
>    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	OATI.webVision.Server.Core	C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	128	

I've looked around the web and haven't been able to find any kind of solution. Is this a known issue?

**Comment by livarcocc** [comment]
Can you confirm the version of the SDK you have? 2.1.3 is an very old version of the SDK, I would first suggest installing the latest SDK available (2.1.300).

After that, could you provide a small repro of this issue for us? Something that we could try to repro ourselves?

**Comment by jceddy** [comment]
It's the version I downloaded here:
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300

So 2.1.300.

I'll see if I can do a small repro. It's a big solution, though, so might be tough.

Not sure if it's relevant, but the main project in the solution targets both net462 and notcoreapp2.0, while the project I'm getting the error on targets netstandard2.0

**Comment by jceddy** [comment]
I haven't been able to do a small repro. I cleared out my Nuget packages cache for the solution and re-built and it seems to be working now.
