### ISSUE TITLE
Package validation not working when PackageId is used

### ISSUE THREAD

**Issue by hudecekd** [dotnet/sdk#23393]
### Description
When I use `PackageId` in csproj to use different package name then package validation is not working but form build output diagnostics it seem it was executed without any problem.

### Steps to reproduce
1. Create project with some method
2. Set version of package to 0.1.0
2. Call `dotnet pack`
3. Make it avilable in some directory where nuget.config is targeted.
4. Add
```  <PropertyGroup>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>0.1.0</PackageValidationBaselineVersion>
  </PropertyGroup>
```
5. Add some parameter to method
6. Call `dotnet pack`
7. Packing will fail which is expected with information that method without parameters is not found anymore and is in base package.

Now do same steps but use `PackageId` to rename package from beginning. Then step 6 will not fail.

Example project is available at [PakcageValidationTestClassLibrary.zip](https://github.com/dotnet/sdk/files/7854992/PakcageValidationTestClassLibrary.zip).
Requires change in nuget.config to use local path of developer

**Comment by ericstj** [comment]
cc @joperezr @safern

**Comment by safern** [comment]
Thanks, @hudecekd, I'll see what's going on.

**Comment by joperezr** [comment]
As per the discussion offline, we should ensure that this works for cases where:
- Package ID changed between baseline and current, but the assembly name was kept the same.
- Package ID changed between baseline and current, and the assembly name was also changed.
- Package ID remained the same between baseline and current, but the assembly name changed.

**Comment by safern** [comment]
> and the assembly name was also changed.

Assembly names between package version is a binary breaking change, and if fact we would warn if that happens. 

The best scenario going forward is to support: https://github.com/dotnet/sdk/issues/17364

Then if an assembly name changed we will detect it and emit warnings for the assembly name rule.
