### ISSUE TITLE
.NET CLI - If a runtime ID is passed through OS flag, a non-descriptive error message is returned

### ISSUE THREAD

**Issue by ahattangadi** [dotnet/sdk#23433]
### Describe the bug
Using the .NET CLI, when someone would run `dotnet publish --os win10-x86` the error message would be, something like, "The Runtime Identifier win10-x86-x64 was not found"
It would be better if an error message like, "Runtime Identifier has been passed through OS flag", or something that indicates what the problem is.

### To Reproduce
Create a new winforms app and use the .NET CLI and run `dotnet publish --os win10-x86`

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2022 - V17.0.2

**Comment by BartoszKlonowski** [comment]
I would like to work on this item.
@baronfel @marcpopMSFT Please assign this to me.

**Comment by Markliniubility** [comment]
The current error message is "The specified RuntimeIdentifier 'win10-x86-arm64' is not recognized. [/Users/mark/Dotnet/sdk/src/Tests/Microsoft.NET.Clean.Tests/Microsoft.NET.Clean.Tests.csproj]" (arm64 as I run through a arm-64 device). Combined with the documentation on [RuntimeIdentifier](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog), the cause of the error are easily understandable, and therefore, this issue should be good to close?

**Comment by ahattangadi** [comment]
I agree!
