### ISSUE TITLE
When installing workloads, hide manifest updates from customers

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#23446]
We've had multiple customers get confused when installing workloads that we also update the manifests of unrelated workloads.  "Why did it install tvos?" and similar questions are ones we get.

Instead, perhaps we should hide that information behind the verbosity switch and instead report something like "Checking for updated workloads...".  Check with Chet on the exact design.

![image](https://user-images.githubusercontent.com/12663534/149597371-d9451cf4-c49e-46b0-bec3-11b1072efbcb.png)

**Comment by dsplaisted** [comment]
Probably this is the line where the output is coming from: https://github.com/dotnet/sdk/blob/642686c9a0da82f8f4bedf9d73335701959c3e40/src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs#L329

**Comment by baronfel** [comment]
Agree with @marcpopMSFT's initial assessment. 

* All the existing updates should only be written at `detailed` or `diagnostic` verbosity levels, 
* At all verbosity levels except `quiet` we should simply say `"Checking for updated workload manifests."`
  * This echoes the language used in the help text for the `--skip-manifest-update` option, so users should be able to make that connection.
