### ISSUE TITLE
dotnet restore with .net 6 SDK Build 101 Hangs for 5 minutes then exits with code 1.

### ISSUE THREAD

**Issue by matt-psaltis** [dotnet/sdk#23461]
### Describe the bug
Running a dotnet restore on a project which contains the following ProjectReference structure.

Project A -> Project B & Project C
Project B -> Project C

the dotnet restore hangs at `Determining projects to restore...`
The three files receive the following error message when verbosity is turned up to diag.

 1:3>Done Building Project "<csproj path>" (_GenerateRestoreProjectPathWalk target(s)) -- FAILED.

strace shows the following:

```
[pid 2232135] bind(8, {sa_family=AF_UNIX, sun_path="/tmp/dotnet-diagnostic-2232135-889863297-socket"}, 110) = 0
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2231826"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2718148"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
[pid 2232147] connect(123, {sa_family=AF_UNIX, sun_path="/tmp/MSBuild2232173"}, 22) = -1 ENOENT (No such file or directory)
```

This error just continues for about 5 minutes in the log before the process gives up.

What's interesting is all three projects perform a dotnet restore if I remove their project dependencies. So it seems its something internal within the internal restore process when a project has ProjectReferences.

### To Reproduce
I'm trying to reproduce this its happening on both of our Ubuntu 20.04 fully patched build servers.

### Exceptions (if any)
No exceptions logged.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.301 [/usr/share/dotnet/sdk]
  5.0.404 [/usr/share/dotnet/sdk]
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by matt-psaltis** [comment]
Update: msbuild -t:restore works fine

Effects dotnet build as well

**Comment by BretJohnson** [comment]
I'm also seeing a "dotnet restore" hang (on mac) on build 101. The root cause may or may not be the same.
@matt-psaltis - If you come up with any workarounds, please share.

**Comment by matt-psaltis** [comment]
We're moving the entire on prem azure devops system to k8s with container agents. I realise that probably doesn't help your scenario but we can't wait for this to be triaged.

**Comment by Rhywden** [comment]
I'm also seeing this same issue when trying to build an Blazor Server app.

By the way: It's also a lot of fun if "Strg-C" just yields the message that it tries to wait to the restore process to cancel on its own.
And then waits for several minutes for the process to do so. It seems someone forgot to include a proper timeout because `kill -9` from another terminal can't be the solution.

**Comment by fg-j** [comment]
I think I'm seeing the same issue with .NET SDK 6.0.200. Each of 3 projects restore on their own but `dotnet publish` fails to restore the project that has ProjectReferences to the other 3.
