### ISSUE TITLE
Suspicious use of $(MSBuildAllProjectFiles) in Microsoft.NET.DesignerSupport.targets

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/sdk#23480]
### Describe the bug

Two targets in Microsoft.NET.DesignerSupport.targets declare `$(MSBuildAllProjectFiles)` as inputs. I don't see where that property is ever set. Perhaps they should use `$(MSBuildAllProjects)` instead.

<https://github.com/dotnet/sdk/blob/36621631f5982fb9d23644aec68222015ba337a2/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets#L41-L46>
<https://github.com/dotnet/sdk/blob/36621631f5982fb9d23644aec68222015ba337a2/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets#L84-L89>

Those came from <https://github.com/dotnet/sdk/pull/2895>.  The property name `MSBuildAllProjectFiles` appears nowhere else in the dotnet/sdk or dotnet/msbuild repositories.

### To Reproduce

Unknown impact.  Perhaps this causes the `_GenerateDesignerDepsFile` and `_GenerateDesignerRuntimeConfigFile` targets not to run when they should. On the other hand, if a file in `$(MSBuildAllProjects)` has been modified, then perhaps that causes `$(ProjectAssetsFile)` to be regenerated, which would cause MSBuild not to skip the targets after all.

### Exceptions (if any)

None

### Further technical details
- Include the output of `dotnet --info`
  ```
  .NET SDK (reflecting any global.json):
   Version:   6.0.101
   Commit:    ef49f6213a

  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19044
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

  Host (useful for support):
    Version: 6.0.1
    Commit:  3a25a7f1cc

  .NET SDKs installed:
    2.1.526 [C:\Program Files\dotnet\sdk]
    6.0.101 [C:\Program Files\dotnet\sdk]

  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

  To install additional .NET runtimes or SDKs:
    https://aka.ms/dotnet-download
  ```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

  No IDE.

**Comment by marcpopMSFT** [comment]
@drewnoakes   this definitely looks wrong from searches I've done of dotnet and VS repos (ie the only instances are in this file). Does the project system set this or can we just flip it over? All GH references are just forks of this file.

**Comment by drewnoakes** [comment]
The project system does look at this property, but only at the first value in the semicolon delimited list. MSBuild prepends the first value during evaluation to be the most recently modified project file. Therefore the current guidance is to not explicitly modify this property, as was once done. As for why a target would need this as an input, I'm not sure.

**Comment by marcpopMSFT** [comment]
Let's just fix the typo in main in case there are any side effects
