### ISSUE TITLE
2.1.0 gives HTTP 404 errors for routes to class library controllers (and only when published)

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/sdk#2350]
I have just recently moved from 2.0 to 2.1 and everything seemed fine in my development environment, but as soon as I deployed the code, I got HTTP 404 errors for my routes to controllers in class libraries. This did not happen in 2.0 and I don't know how to solve it yet.

My solution is rather large, but I have extracted parts of it into a small-ish demo you can find here: https://github.com/gordon-matt/LibraryRoutesNotWorking. Instructions for setup are in the README.md.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/Home#3253
