### ISSUE TITLE
PRs occasionally failing with no obvious reason

### ISSUE THREAD

**Issue by mmitche** [dotnet/sdk#23500]
I've seen this a few times recently: https://dev.azure.com/dnceng/internal/_build/results?buildId=1559102&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd

There are no listed test failures, no errors in the binlog, etc. There is this in the text log:

```
Time Elapsed 00:46:34.66
Killing running build processes...
Build failed with exit code -1. Check errors above.
See log: D:\a\_work\1\s\artifacts\log\Release\Build.binlog
```

My hunch though is that this isn't a real failure and is just the return code from the kill command? It's not obvious.

**Comment by marcpopMSFT** [comment]
We made some fixes are part of this PR: https://github.com/dotnet/sdk/pull/23677 We are tracking additional bad code usage in this issue: https://github.com/dotnet/sdk/issues/23850
