### ISSUE TITLE
PackageValidation runs in no-op incremental builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#23517]
The PackageValidation SDK feature currently runs always, even if the package hasn't changed: https://github.com/dotnet/sdk/blob/69a8180583569bc64d7c5357ca64d13fc547ba77/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets#L10-L12

This is the case because the `RunPackageValidation` target is hooked onto the wrong target (maybe there's one that doesn't run in no-op incremental packaging builds) and because it doesn't define any Inputs and Outputs.

When incrementally building the libraries subset of dotnet/runtime for allconfigurations (`build.cmd libs -allconfigurations && build.cmd libs -allconfigurations /bl`), this adds **111 seconds** to the overall build.

![image](https://user-images.githubusercontent.com/7412651/150366037-ee333611-d297-4ffa-b26c-5b4bfb81575b.png)

cc @safern @joperezr @ericstj

**Comment by rainersigwald** [comment]
I suspect there is not a better target to hook, but this could be avoided with inputs + outputs. Right now it looks like the only output is MSBuild properties/items/warnings/errors, but the target or task can always touch a marker file to create a new timestamped output.

**Comment by ericstj** [comment]
Agree, inputs/outputs would be more resilient here.  We also need to rerun even if the package isn't rebuilt: for example, someone changes a suppression file or changes the left-hand-side package.

**Comment by ViktorHofer** [comment]
FWIW, here's another data point that I just collected from a libraries allconfigurations build:

![image](https://user-images.githubusercontent.com/7412651/152516063-dc7e4031-7eeb-447a-b428-3b269078453b.png)
