### ISSUE TITLE
Adding net6.0 target framework to existing library breaks project

### ISSUE THREAD

**Issue by timcassell** [dotnet/sdk#23520]
I am working on a library currently targeting netstandard 2.0 and C# 7.3. I want to add net6.0 to try some new runtime features, but when I do, I get compile errors.

```
<PropertyGroup>
  <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
  <LangVersion>7.3</LangVersion>
</PropertyGroup>
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8652	The feature 'global using directive' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.	ProtoPromise (net6.0)	C:\Users\Tim\Documents\git\ProtoPromise\ProtoPromise\obj\Debug\net6.0\ProtoPromise.ImplicitNamespaceImports.cs	2	Active
```

I saw that it auto generated a `<ProjectName>.ImplicitNamespaceImports.cs` file with global usings that I don't need that caused the errors. How can I target net6.0 and netstandard2.0 properly? I don't need the new language features, just the runtime features.

I'm using Visual Studio 2019 (16.11.9).

**Comment by KalleOlaviNiemitalo** [comment]
There is no .NET 6.0 SDK available for Visual Studio 2019. If you want Visual Studio, then it has to be Visual Studio 2022.

**Comment by timcassell** [comment]
Apparently I have a preview version of the .Net 6 SDK installed. I just installed the latest version and it works now.
