### ISSUE TITLE
reenable tests blocked by the install script bug

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#23531]
Install of 1.N runtimes on non-windows is currently broken.  See here: https://github.com/dotnet/install-scripts/pull/248

disabling a set of tests for that and we can renable later.

https://github.com/dotnet/sdk/pull/23525

**Comment by baronfel** [comment]
The updated scripts have been updated on the dotnet website, so we should take this and reenable the tests at will.

**Comment by marcpopMSFT** [comment]
Closing for now as the downlevel install is now unblocked.
