### ISSUE TITLE
[dotnet tool] Add ability to check if a tool is installed

### ISSUE THREAD

**Issue by decriptor** [dotnet/sdk#23549]
### Is your feature request related to a problem? Please describe.
Currently there is ability to run `dotnet tool list` and `dotnet tool list -g` which will list all your local and global tools. This is useful if you are looking at the list. My problem is that I'm trying to automate this check.
ie, I'm trying to check if `dotnet-trace` is installed on Linux. My current hack is `test -e "~/.dotnet/tools/dotnet-trace"` and then check the exit code. 

### Describe the solution you'd like
It'd be helpful if you could check for a specific tool. Maybe allow `list` to take specific tool?

ie,
`dotnet tool list dotnet-trace` or `dotnet tool list -g dotnet-trace`
and have an exit code of `0` for installed and `1` for missing?

**Comment by baronfel** [comment]
I've certainly automated this same check before, so from an automation perspective I understand the request.

`npm` for example lets you run `npm list <packagename>` and check the exit code to see if a particular tool is installed. it also goes one step further and allows for json output if you append `--json` to that request.  Examples from my machine:

```powershell
> npm list -g vsce; echo $?
C:\Users\chethusk\AppData\Roaming\npm
`-- vsce@2.2.0

True
> npm list -g not_installed; echo $?
C:\Users\chethusk\AppData\Roaming\npm
`-- (empty)

False
> npm list -g vsce --json
{
  "name": "npm",
  "dependencies": {
    "vsce": {
      "version": "2.2.0"
    }
  }
}
```

I think it makes sense to allow specifying an optional package id argument for `dotnet tool list` (note, _not_ the command name), so that users could do commands like:

```powershell
> dotnet tool list dotnet-suggest; exit $?
Package Id                 Version                 Commands
-----------------------------------------------------------------
dotnet-suggest             1.1.221601              dotnet-suggest
True
```

and 

```powershell
> dotnet tool list some.other.package; exit $?
Package Id                 Version                 Commands
-----------------------------------------------------------------
False
```

**Comment by JiaqiWang18** [comment]
Hi everyone, my name is Jacky and I am a CS student at JHU. I have talked with Elinor and I will be working on this feature through semesters of code.

**Comment by decriptor** [comment]
@JiaqiWang18 That is amazing! I'm sure you are all set up to tackle this, but feel free to reach out if you have any questions :)

**Comment by dsplaisted** [comment]
Looks like the related PRs have been merged, can we close this issue?  @baronfel

**Comment by baronfel** [comment]
Yep! Thanks for cleaning up.
