### ISSUE TITLE
Add ability to list .NET Framework info with `dotnet` CLI

### ISSUE THREAD

**Issue by derekantrican** [dotnet/sdk#23560]
.NET CLI has the great ability to list runtimes installed (`dotnet --list-runtimes`) but the process for finding the list of installed .NET Frameworks is much more cumbersome (checking registry is likely the best way, but that is cumbersome for the average user and the "verification" via the registry is different for different versions of .NET Framework). Could this be added into the .NET CLI? Something like `dotnet --list-framework-runtimes`?

**Comment by danmoseley** [comment]
@derekantrican could you say a little more about why you would want this? `dotnet` is part of .NET Core, .NET Framework is a different product entirely. It's also released its last version, back in 2019.

**Comment by derekantrican** [comment]
Yeah, I'm aware they're totally different products. But as people transition their applications from .NET Framework to .NET Core there will likely be an "in-between" time (as there is for me now) where the product is shipped for both. It is not a trivial process to determine which .NET Frameworks a user has installed (it requires a query of the registry at a minimum and Microsoft [seems to recommend 3rd-party applications](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) - which is another thing for users to install). I just think it'd be helpful if there was a very simple `dotnet` command that could help when supporting users on both (Framework & Core) while the transition is happening

**Comment by danmoseley** [comment]
Perhaps that could be a good [.NET tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools). As you say, the registry keys and values are documented; if someone writes such a tool, it would be easy to acquire and run through `dotnet`.

**Comment by derekantrican** [comment]
Good suggestion - thanks. I'll suggest that to the repos linked on the earlier Microsoft docs

**Comment by KalleOlaviNiemitalo** [comment]
It seems attempting to use RegistryKey in a .NET tool project causes either warning CA1416 if targeting net6.0, or error NETSDK1146 if targeting net6.0-windows. See <https://github.com/dotnet/sdk/issues/12055>.

**Comment by KalleOlaviNiemitalo** [comment]
Oh I can avoid the CA1416 by checking OperatingSystem.IsWindows() in code, or by adding `[assembly: SupportedOSPlatform("windows")]`. All right then.
