### ISSUE TITLE
dotnet cli doesn't seem to respect profile / launch file / command line arguments

### ISSUE THREAD

**Issue by Swiftly1** [dotnet/sdk#23565]
I added launchSettings via VS2022 GUI

![obraz](https://user-images.githubusercontent.com/77643169/150857552-2e58b770-f46e-4a2c-992f-70662fd34aa1.png)

it looks like that:

	{
	  "profiles": {
		"LaunchSettingsQuirks": {
		  "commandName": "Project",
		  "commandLineArgs": "--test"
		}
	  }
	}

when I run program via VS with that profile then it prints

	args:
	--test

but when I run it via 

`dotnet run` or 

`dotnet run --launch-profile LaunchSettingsQuirks` or

` dotnet run --launch-profile "LaunchSettingsQuirks"`

 then it doesn't, it just prints 

	args:

when I use name of the profile that does not exist, then the error is displayed correctly

	dotnet run --launch-profile test
	The launch profile "test" could not be applied.
	A profile with the specified name could not be found or is not a valid JSON object.

Repo: https://github.com/Swiftly1/LaunchSettingsQuirks

	dotnet --version
	6.0.101

**Comment by marcpopMSFT** [comment]
@pranavkm I was poking around the code and saw your change here that moves two of the launch settings into runcommand.cs: https://github.com/dotnet/sdk/pull/12581. However, I don't appear to see any of the other launch settings supported? Am I missing that somewhere? As far as I can tell, we get the settings and never actually do anything with them.

**Comment by pranavkm** [comment]
@marcpopMSFT it looks we read the launchSettings correctly, but don't apply the `commandLineArgs` to the executing command when applying other things like environment variables and the application url: https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L62-L75

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/issues/9619

**Comment by danroth27** [comment]
It makes sense to me that we would honor these settings in `dotnet run` and `dotnet watch` as much as we can, but I don't have much user data to support that this is a pressing need. @DamianEdwards ?

**Comment by DamianEdwards** [comment]
I definitely think command line arguments is a logical thing to do and we should do it in 7 given the amount of feedback on the other issue. I actually think that majority of the others are already supported now.

**Comment by marcpopMSFT** [comment]
Ok, I'll add in arguments with this issue. We're still missing LaunchBrowser and LaunchUrl but do have EnvironmentVariables and ApplicationUrl already included.

**Comment by DamianEdwards** [comment]
Yeah today `dotnet watch run` supports those I believe but not `dotnet run`. Doesn't seem like the kind of change we could make to `run` safely now, i.e. browsers suddenly start launching when they didn't before. We know lots of folks run `dotnet run` in CI builds for example.

**Comment by Swiftly1** [comment]
Wow, I thought that `dotnet run` not starting browsers like VS was feature/intended... that's pretty tricky scenerio now, haha.
