### ISSUE TITLE
dotnet tool init

### ISSUE THREAD

**Issue by nojaf** [dotnet/sdk#23561]
### Is your feature request related to a problem? Please describe.
When you want to install a local tool via `dotnet tool install x`, you first need a `tool manifest`.
Today you can do this using `dotnet new tool-manifest`.

### Describe the solution you'd like
How about an alias like `dotnet tool init`?
A bit easier to remember.

At the same time, I also wouldn't mind it if the manifest file was created automatically if absent.

**Comment by baronfel** [comment]
I do like the idea of having the `init`-style command co-located spatially with the rest of the tool commands.  However, I like even more automatically creating the tool-manifest at the point the user needs it.  For local tools, if no explicit manifest file was create, that could look like executing `NewCommandshim.Run("tool-manifest")` roughly [here](https://github.com/dotnet/sdk/blob/60aaae761755ecbff3971733150eb79d9f10427b/src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs#L89-L95). I'm not sure the team will have time for this, but it seems like an easy enhancement so I'll mark it good-first-issue and put it up for grabs if anyone would like to contribute.

**Comment by nojaf** [comment]
Hello, thank you for this feedback.
I might take a stab at this in the future.

**Comment by vrushalivartak** [comment]
https://github.com/dotnet/sdk/pull/31231 added --create-manifest-if-needed flag. It creates tool manifest automatically when installing a new local tool if the flag is on and no manifest exists.

@nojaf @baronfel Creating manifest automatically has been addressed in https://github.com/dotnet/sdk/pull/31231. From previous comments https://github.com/dotnet/sdk/issues/23561#issuecomment-1023638609, I understand dotnet tool init is not required. So, this ticket can be closed.
