### ISSUE TITLE
`%(TargetingPack.PackageDirectory)` blank when installed via .msi?

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#23562]
### Describe the bug

We recently made a change to use `%(TargetingPack.PackageDirectory)`: https://github.com/xamarin/xamarin-android/commit/a21d1a7d54e811c89e36969d1214f5e31fc4b63a

This was an attempt to get the path to `ref\Mono.Android.dll`. This works fine in most cases, unless you install the MAUI workload from the Visual Studio installer.

In this case, the metadata is blank:

![image](https://user-images.githubusercontent.com/840039/150855136-fe7476e8-5f0a-4899-8328-8ebab458ab44.png)

Which results in an error later in the build:

    error XA0002: Could not find mono.android.jar

To solve the issue, you can run `dotnet workload install maui`. And the missing metadata is found?

### To Reproduce

* Install VS main with Android workload version: `31.0.200-preview.13.29`.
* Create a MAUI project and build/deploy on Android.

### Further technical details

Log: [AndroidApp3_Debug_AnyCPU_Build_2022-01-24T13_45_13.2778587-06_00.binlog.zip](https://github.com/dotnet/sdk/files/7928490/AndroidApp3_Debug_AnyCPU_Build_2022-01-24T13_45_13.2778587-06_00.binlog.zip)

```
.NET 6.0.200-preview.22055.15
```

```
Microsoft Visual Studio Enterprise 2022 (64-bit) - main
Version 17.2.0 Preview 1.0 [32124.46.main]
```

**Comment by marcpopMSFT** [comment]
@jonathanpeppers are you able to use the ResolvedTargetingPack item?  We resolve the package directory at a later time in the ResolveFrameworkReferences Target if it's not already installed to the packs folder.

**Comment by marcpopMSFT** [comment]
Can you clarify, were the targeting packs installed with the initial VS install? I wonder if they were missing from VS install and so maybe that's why that value wasn't set initially.

**Comment by jonathanpeppers** [comment]
Yes, the targeting packs are in the workload and existed on disk when I got this `.binlog`. For some reason, I've found when they are installed from VS this metadata is blank, and just running `dotnet workload install` somehow fixes it?

`ProcessFrameworkReferences` seems to require NuGet restore to be completed. In some cases, the IDE (Xamarin extension) was calling a special `GetAndroidDependencies` target before NuGet restore. They use this to prompt the Android SDK manager to install things on demand if needed. For now, I think they have it running *after* NuGet restore; so things are working.

I thought it was worth filing, as this seems odd. Maybe using `@(TargetingPack)` should be avoided?

**Comment by marcpopMSFT** [comment]
Were you able to use ResolvedTargetingPack instead?

**Comment by dsplaisted** [comment]
Yes, whether `TargetingPack` items have a PackageDirectory depends on whether it finds them in the packs directory or not.  If you use `ResolvedTargetingPack` items, it should have the metadata set whether the pack was in the packs directory or was downloaded to the NuGet packages folder.

**Comment by jonathanpeppers** [comment]
Let me go through this again, and see if the other item group works. Thanks.

**Comment by jonathanpeppers** [comment]
The other item group seems to work:

![image](https://user-images.githubusercontent.com/840039/160931548-5b0ad0d3-a271-4a4f-8891-a84359fabbe8.png)

I'm not sure we even need to use this now anyway, so we can close this.
