### ISSUE TITLE
The user as nt authority is fail to upgrade to 6.0.102 with 17.0.5 pre-installed

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#23567]
**Repro steps:**
1. Install VS 17.0.5(6.0.101 inserted)
2. Install .NET 6.0.102 using user as nt authority
    1) Download and install https://docs.microsoft.com/en-us/sysinternals/downloads/psexec
    2) Open an admin command prompt and run: PSTools\PSExec.exe -sid cmd
    3) In the new command prompt, confirm that you are local SYSTEM by running whoami
3. Observe

**Expected Result**
1. .NET 6.0.102 is installed successfully

**Actual Result**
1. .NET 6.0.102 installation failed with error that " A newer version of Microsoft.NET.Sdk.Maui.Manifest-6.0.100 is alread installed"
2. .NET 6.0.101 is broken after 6.0.102 rolling back.
![image](https://user-images.githubusercontent.com/1578239/150922847-08cb2535-be6b-4f09-bc65-fbc402aff803.png)
![image](https://user-images.githubusercontent.com/1578239/150923766-89d2a527-4785-48e8-b852-074306f60847.png)

[Microsoft_.NET_SDK_6.0.102_(x64)_20220124221431.log](https://github.com/dotnet/sdk/files/7931124/Microsoft_.NET_SDK_6.0.102_.x64._20220124221431.log)

**Note:**
1. This issue is not repro if install .NET 6.0.102 using domain user on administrator group
2. This issue is not repro if pre-install 6.0.101 only

**Dotnet --info**

**Comment by marcpopMSFT** [comment]
@joeloff is this the MU manifest upgrade issue you fixed in arcade?

**Comment by joeloff** [comment]
It is. CTI picked this up last night with the new validation scenarios we gave them.

**Comment by joeloff** [comment]
@NicoleWang001 for the failed SDK, you will need to repair 6.0.101 because some parts would have partially been upgraded and then uninstalled from the rollback, e.g. the dotnet host always perform inplace updates. It effectively rollsback changes made by 6.0.102, but can't change anything from 6.0.101 that got removed.
