### ISSUE TITLE
Source-Only NuGet packages add <Compile Include="..." /> to csproj, resulting in build errors.

### ISSUE THREAD

**Issue by btodts** [dotnet/sdk#2356]
### Steps to reproduce
Install a source-only NuGet package, e.g. https://www.nuget.org/packages/TinyIoC/. Upon installation, this adds a file to your directory (in this case: `TinyIoC.cs`).

### Expected behavior
As per https://aka.ms/sdkimplicititems, I'd expect the SDK to pick this file up for compilation using the globs in the SDK properties, without modifying the csproj file.

### Actual behavior
A Compile element is added to the csproj file: <Compile Include="TinyIoC.cs" />, leading to a build error:
> Duplicate Compile items were included. The .NET SDK includes Compile items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file.

Manually removing the Compile element from the csproj everytime NuGet packages are installed, is less than desirable. Using `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` and `<Compile Include="**/*.cs" />` (again, as per https://aka.ms/sdkimplicititems), results in other build errors (e.g. `error MSB3105: The item "Foo.cs" was specified more than once in the "Sources" parameter).

**Comment by livarcocc** [comment]
I am going to move the bug to NuGet to see if it is possible to have some logic to detect and not add the compile item to the project due to globing.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7053
