### ISSUE TITLE
F# 'FSharpOverridesTargetsShim' imports wrong targets?

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/sdk#2359]
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharp.targets#L27

The targets file should be `Microsoft.FSharp.Overrides.NetSdk.targets` instead of `Microsoft.FSharp.NetSdk.targets`?

Is this a typo or intentional?

**Comment by livarcocc** [comment]
@KevinRansom to answer.

**Comment by Nirmal4G** [comment]
Fixed in #2538
