### ISSUE TITLE
Feed implementation assemblies instead of their directories to ApiCompat

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#23631]
When invoking ApiCompat directly (without msbuild) and the implementation assemblies aren't located in the same directory I would want to pass in the implementation assemblies directly instead of their directories. I assume that if I would pass in the implementation directories for each assembly, that would cause quite an overhead because of the `Directory.GetFiles` call per folder? Consider feeding 100+ assemblies in to it as an example.

Would it be possible to pass the implementation assemblies in directly? 

Question for @safern and @ericstj

**Comment by ericstj** [comment]
I took a look at how the underlying implementation in APICompat handles paths here and it seems better.  

Top-level comparisons must be specified through Assemblies.
https://github.com/dotnet/sdk/blob/116d828644f7fcb4e85316844e6ee86a943b4aec/src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs#L50

Dependencies are stored in a hash-table by assembly name and directories are only probed if an assembly wasn't explicitly specified.
https://github.com/dotnet/sdk/blob/116d828644f7fcb4e85316844e6ee86a943b4aec/src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs#L407-L436

So chances are we'll get better perf here once exposing the option for files.  I'll leave this issue open for the folks implementing #18677 to serve as a reminder.

**Comment by ViktorHofer** [comment]
Closing as completed in https://github.com/dotnet/sdk/issues/18677.
