### ISSUE TITLE
PackageValidation is causing unnecessary project evaluations which noticeably slows down a project's build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#23630]
When leveraging the new `PackageValidation` feature in projects I notice a lot additional project evaluations. I believe that is because PackageValidation invokes the project with the `BuildProjectReferences=false` switch to gather the ReferencePath: https://github.com/dotnet/sdk/blob/d5566994e06e3a50b44a65473961ff1f32c22b18/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets#L68

This is only noticeable when projects multi-target but when they do, the cost is quite high. As an example, let's consider a project "A" that multi-targets for `net6.0;net5.0;netstandard2.0;net48`. The evaluations because the described issue doubles from 5 to 10:

Before:
- Outer build `net6.0;net5.0;netstandard2.0;net48`
- Inner build `net6.0`
- Inner build `net5.0`
- Inner build `netstandard2.0`
- Inner build `net48`

After:
- Outer build `net6.0;net5.0;netstandard2.0;net48`
- Inner build `net6.0`
- Inner build `net5.0`
- Inner build `netstandard2.0`
- Inner build `net48`
- Outer build `net6.0;net5.0;netstandard2.0;net48` with additional `BuildProjectReferences` global property
- Inner build `net6.0` with additional `BuildProjectReferences` global property
- Inner build `net5.0` with additional `BuildProjectReferences` global property
- Inner build `netstandard2.0` with additional `BuildProjectReferences` global property
- Inner build `net48` with additional `BuildProjectReferences` global property

Wouldn't it be possible to avoid these extra evaluations by sequencing the gathering of the ReferencePath into the already running outer build without the `BuildProjectReferences` global property?

@ericstj @safern

**Comment by ViktorHofer** [comment]
Apparently NuGet already does the same: https://github.com/NuGet/NuGet.Client/blob/fd00d6dd248ed74c2fe006bbd4b8ca53d8ebdeac/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L333

Unfortunately changing this behavior in PackageValidation isn't sufficient to avoid the additional evaluations. If the Pack target is invoked, the evaluations are triggered. As a side note, [as PackageValidation currently doesn't define inputs and outputs](https://github.com/dotnet/sdk/issues/23517), these evaluations could at least be avoided in an incremental Pack either by fixing the linked issue or by addressing this one.

**Comment by ericstj** [comment]
There was an explicit goal to avoid additional evaluations over what NuGet already does, and also not to trigger any more builds than what NuGet already does.  If it's reusing the results from NuGet, that's what we expect.  https://github.com/dotnet/sdk/pull/19771  cc @joperezr 

I do agree that we should not cause any additional evaluations, so if there are scenarios where we are the cause of the additional evaluation (EG: if we're specifying that property when NuGet is not) then that's a concern.

If you want NuGet to change to then it would be good to start with that.

**Comment by ViktorHofer** [comment]
That makes sense. I just realized moments after opening this issue that the additional evaluations aren't initially triggered by PackageValidation but by NuGet. I opened https://github.com/NuGet/Home/issues/11530 to discuss with the NuGet team if these additional evaluations can be avoided in the common path. Let's meanwhile close this issue.
