### ISSUE TITLE
ObjectDisposedException when running dotnet workload uninstall

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#23667]
```
Unhandled exception.
System.ObjectDisposedException: The collection has been disposed.
Object name: 'BlockingCollection'.
   at System.Collections.Concurrent.BlockingCollection`1.get_IsCompleted()
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.WriteMessage(String message)
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.ProcessLogRequests(Object logPipeName)
   at System.Threading.Thread.StartCallback()
```

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22055.15
 Commit:    a3c3a2bf3b
```

Didn't prevent the operation, but it's odd to see the error being printed.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps TimestampedFileLogger.Dispose(bool) should join the ProcessLogRequests threads like it joins the WriteLog thread here:

<https://github.com/dotnet/sdk/blob/7c856e62f9f505996e67729ce74a57eb70df7387/src/Cli/dotnet/Installer/Windows/TimestampedFileLogger.cs#L112>

But then it might also have to explicitly ask the threads to exit. ProcessLogRequests checks dispatcher.IsConnected but I don't know whether that will become false reliably and quickly. [PipeStreamMessageDispatcherBase.ReadMessage()](https://github.com/dotnet/sdk/blob/7c856e62f9f505996e67729ce74a57eb70df7387/src/Cli/dotnet/Installer/Windows/PipeStreamMessageDispatcherBase.cs#L89-L98) and PipeStream.Read do not currently take a CancellationToken. Stream.ReadAsync would.

**Comment by dsplaisted** [comment]
Assigning to @joeloff

**Comment by marcpopMSFT** [comment]
From a year ago and haven't seen reports since so closing not repro.
