### ISSUE TITLE
2.1.301: SDK/Runtime Mismatch In Targets

### ISSUE THREAD

**Issue by paulquinn** [dotnet/sdk#2368]
## Steps to reproduce
a) Installed SDK 2.1.301
b) Open minimal project, .csproj is:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1.1</TargetFramework>
  </PropertyGroup>
</Project>
```
c) Build (`dotnet build`)

## Expected  behavior
The project should build without error.

## Actual behavior
Build error: 
_Microsoft.NET.TargetFrameworkInference.targets(137, 5): [null] The current .NET SDK does not support targeting .NET Core 2.1.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.1._

In C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets, line 130 states:  `<NETCoreAppMaximumVersion>2.1</NETCoreAppMaximumVersion>`

If I hack this value to 2.1.1 the project builds.

NB, I also have similar issue with an aspnet project (targetframework netcoreapp2.1.1) with the sdk: 

_Microsoft.AspNetCore.App.targets(14, 5): [null] This version of Microsoft.AspNetCore.App is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.App compatible with netcoreapp2.1.1_

In C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.app\2.1.1\build\netcoreapp2.1\Microsoft.AspNetCore.App.targets the error condition is:
```
<Target Name="EnsureTFMCompatibility" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
    <Error
      Text="This version of Microsoft.AspNetCore.App is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.App compatible with $(TargetFramework)."
      Condition="'$(TargetFramework)' != 'netcoreapp2.1'"/>
  </Target>
```
again, I think this should be 2.1.1?

## Environment data
dotnet --info output from proj dir:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
This should be netcoreapp2.1.

By setting that, we will imply the Microsoft.NETCore.App version of your application to be 2.1.0 for Framework Dependent Apps and 2.1.1 for self-contained apps. This happens automatically for you.

If you want to control that, you can set `RuntimeFrameworkVersion`.
