### ISSUE TITLE
`dotnet run` swallows Posix signals on Unix

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#23683]
### Describe the bug
Per [this recent blog post](https://carpenoctem.dev/blog/posix-signal-handling-in-dotnet-6/#:~:text=like%20progress%20bars.-,Limitations%20and%20Caveats,-It%27s%20fantastic%20that), `dotnet run` seemingly swallows signals sent to the terminal, which means signal handlers added as part of the application to be run cannot be used/tested interactively.

### To Reproduce
We would love to have some sample code here.

### Workarounds
You can manually `build` and run the build dll with the raw `dotnet` command

**Comment by tnishimura** [comment]
I'm the author of that article, unfortunately I cannot reproduce the error at the moment, please close this and I'll be sure to reopen it if I see it again, sorry for the confusion!

**Comment by baronfel** [comment]
No worries! Again thanks for taking the API out for a spin and writing about your experiences :)
