### ISSUE TITLE
Self-upgrade dotnet via CLI

### ISSUE THREAD

**Issue by iSeiryu** [dotnet/sdk#23700]
It'd be nice for the `dotnet` CLI to be able to upgrade itself and the current SDK.

Something like
```bash
dotnet upgrade [--preview]
```

There are some tools that can do it on different platforms
```bash
# Windows
winget install Microsoft.dotnet

# Ubuntu
apt-get upgrade dotnet-sdk-6.0
```

But a unified way would be preferable.

**Comment by marcpopMSFT** [comment]
We are tracking this work here: https://github.com/dotnet/sdk/issues/23356.  The tentative plan is to try to enable upgrade and install of the SDK from the SDK in .NET 7 assuming we can get signoff on a design by end of the month.
