### ISSUE TITLE
self-contained warning should be suppressed for iOS

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#23705]
### Describe the bug
When publishing for iOS you need to specify a RuntimeIdentifier. See https://github.com/xamarin/xamarin-macios/pull/13462 and https://github.com/xamarin/xamarin-macios/issues/12997.

However, when you try to publish for `-f net6.0-ios -r ios-arm64`, you get a warning:

```
/.../Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/Users/eerhardt/DotNetTest/MauiTest/NoHosting/NoHosting.csproj]
```

This doesn't make sense in an iOS app because you can only publish self-contained.

### To Reproduce
1. `dotnet workload install maui`
2. `dotnet new maui`
3. `dotnet publish -c Release -f net6.0-ios -r ios-arm64`

### Warnings
```
/.../Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/Users/eerhardt/DotNetTest/MauiTest/NoHosting/NoHosting.csproj]
```

### Further technical details
```
% dotnet --info                                                           
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22063.5
 Commit:    2d72e717b3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /Users/eerhardt/git/maui/bin/dotnet/sdk/6.0.200-preview.22063.5/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.200-preview.22063.5 [/Users/eerhardt/git/maui/bin/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/Users/eerhardt/git/maui/bin/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/Users/eerhardt/git/maui/bin/dotnet/shared/Microsoft.NETCore.App]
```

cc @dsplaisted @rolfbjarne

**Comment by marcpopMSFT** [comment]
We should check if self-contained is set at all rather than specifically the command line.

**Comment by dsplaisted** [comment]
Related links for reference:

- #18832
- #21405
- #19706
- https://github.com/dotnet/designs/blob/main/accepted/2021/architecture-targeting.md#enable-shorthand-rid-targeting-syntax

**Comment by jonathanpeppers** [comment]
We noticed this happens on Android as well. Mobile platforms define `$(SelfContained)` to be `true` by default in their MSBuild targets.

**Comment by dsplaisted** [comment]
@jonathanpeppers Yes, the fix applies to iOS and Android, as well as projects which explicitly set SelfContained to true.

**Comment by mattjohnsonpint** [comment]
FYI I'm on 6.0.400 latest and I'm still getting this warning.
