### ISSUE TITLE
Hot Reload make Linq Expressions code to fail with cached (static) reflection 

### ISSUE THREAD

**Issue by jhudler** [dotnet/sdk#23736]
### Describe the bug

When creating dynamic Linq expressions during runtime (that is, using the `System.Linq.Expressions` namespace), cached reflection state in static variables seems to become invalid.

In my sample case, a `Expression.Property(Expression, MethodInfo)` will throw a `System.ArgumentException` if the `MethodInfo` value is cached.

### To Reproduce

Here is a simple console app gist to be run:

https://gist.github.com/jhudler/614e0e16626bf4978d4ee86c7fbe78e6

When app is running, change the fixed string character in `Console.WriteLine` to trigger the Hot Reload.

### Exceptions (if any)

```
System.ArgumentException: 'The method 'MyClass.get_DummyProp' is not a property accessor (Parameter 'propertyAccessor')'

    System.Linq.Expressions.Expression.GetProperty(System.Reflection.MethodInfo, string, int)
    System.Linq.Expressions.Expression.Property(System.Linq.Expressions.Expression, System.Reflection.MethodInfo)
    MyClass.GetDummyValue() in Program.cs
    Program.<Main>$(string[]) in Program.cs
```

**Comment by pranavkm** [comment]
@tmat thoughts on this?

FYI @stephentoub

**Comment by jhudler** [comment]
Thanks @pranavkm for your direction. I've looked for something like this before and couldn't find in the docs at the time. I've just applied the annotation and it worked as expected - great!
I think changing the hot reload to preserve the reflection info pointers would be anything but a trivial task, so I agree this is the way to go.

As for my self, ticket can be closed - thanks once more!
