### ISSUE TITLE
dotnet nuget outdated

### ISSUE THREAD

**Issue by no1melman** [dotnet/sdk#23762]
Has there been any conversation about have an outdated nuget command, so that you can see your dependencies that need updating... then having something like `dotnet nuget update` - I don't know if nuget is the right place... maybe something like `dotnet update` and `dotnet outdated` or even `dotnet outdated` `dotnet outdated update`...

If this was wanted - and we agreed at command - i would happily do the work

https://github.com/dotnet/sdk/blob/40d6e475f48aa319c46905610ed1dae197608eb0/src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs#L29-L40

**Comment by KalleOlaviNiemitalo** [comment]
[dotnet list package](https://docs.microsoft.com/dotnet/core/tools/dotnet-list-package) already has `--outdated`.

**Comment by no1melman** [comment]
awesome, that is useful - now just need an updater...
