### ISSUE TITLE
Detect if the SDK is being run on a CI host machine

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#23795]
### Is your feature request related to a problem? Please describe.

Certain functionalities in the SDK could be toggled on or off more intelligently if we knew that the SDK was running on a Continuous Integration host, like a GitLab Runner agent, or a GitHub actions runner.  These systems typically expose environment variables that can be used to determine if a CI agent is active.

### Describe the solution you'd like
We should create a list of such variables, and synthesize a boolean `IsCI` (or similar) that is true if any of these environment variables are populated.  These variables are:

**Boolean values**
* TF_BUILD
* GITHUB_ACTIONS
* APPVEYOR
* CI
* TRAVIS
* CIRCLECI

**Non-null values**
* TEAMCITY_VERSION
* JB_SPACE_API_URL

**Complex checks**
* AWS CloudBuild - CODEBUILD_BUILD_ID != '' and AWS_REGION != ''
* GCP Cloud Build - BUILD_ID != '' and PROJECT_ID != ''

This is not an exhaustive list, but should be enough to get going.  We can/should also document the `CI` variable for user-hosted CI systems like an in-house build server farm.

**Comment by KalleOlaviNiemitalo** [comment]
In one repo, I had to stop our CI system from setting the CI variable because it triggered a warnings-as-errors mode in a nodejs build system and we weren't ready for that. The same repo included .NET code as well. So the CI variable alone would not be reliable for telemetry.

**Comment by baronfel** [comment]
Duly noted! This is definitely a heuristic, so we'll need that caveat when looking at the data. I do think it's a heuristic that's a reasonable approximation of the reality, though.

**Comment by baronfel** [comment]
Ah, changing from a short circuiting model, I see. That would definitely be more correct 👍

**Comment by baronfel** [comment]
Implemented by #24166
