### ISSUE TITLE
Can support environment variables first  in the feature？

### ISSUE THREAD

**Issue by lc273734858** [dotnet/sdk#2384]
In use docker scenes，we must write the code support  environment variables first，
hope support environment variables first  in the feature

**Comment by nguerrera** [comment]
@lc273734858 I don't understand the request. Can you provide more details. Which feature would you like to support environment variables?

**Comment by lc273734858** [comment]
when you run your app in docker or kubernetes， start your app with   "docker run -e configarg value",in java you need do nothing，but in dotnetcore you wirte it by yourself.

**Comment by nguerrera** [comment]
I'm not very familiar with docker, so I'm still having trouble understanding the request.

Paging @richlander who would have more context.

**Comment by lc273734858** [comment]
I'm so sorry to that my english so poor.
When use docker ,you make one image must run in all environment,example   dev/test/prd, you must set "docker run -e connectionstring  xxxxx"....

**Comment by nguerrera** [comment]
No problem at all! I've reached out to some people who work more regularly with Docker to see if they can help here.

**Comment by lc273734858** [comment]
@nguerrera Thank you very much!

**Comment by lc273734858** [comment]
Now I need close my issue?

**Comment by nguerrera** [comment]
No, the issue can stay open while we wait for some other people to respond.

**Comment by lc273734858** [comment]
OK

**Comment by richlander** [comment]
I believe you are talking about environment promotion. What specific way do you want to control the product in Docker with environment variables that isn’t possible today?

**Comment by nguerrera** [comment]
Are you using ASP.NET Core?

If so, it looks like https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration can make it easy to bind environment variables to a class.

**Comment by nguerrera** [comment]
I don't have personal experience with the API, but see where it shows adding environment variables in addition to the json via https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariablesextensions.addenvironmentvariables?view=aspnetcore-2.1#Microsoft_Extensions_Configuration_EnvironmentVariablesExtensions_AddEnvironmentVariables_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_String_

**Comment by andymac4182** [comment]
This article covers the configuration system and how overriding works. http://www.paraesthesia.com/archive/2018/06/20/microsoft-extensions-configuration-deep-dive/ If you search for `Environment variables:` there is some examples of how setting variables via environment variables works.

**Comment by lc273734858** [comment]
@andymac4182 Thanks for your help ,I will try  to use the article.

**Comment by benaadams** [comment]
If its an aspnetcore app using the default builder (e.g. `WebHost.CreateDefaultBuilder(args)`) then you would just need to prefix you environment variable with `ASPNETCORE_` e.g.

`docker run -e ASPNETCORE_connectionstring xxxxx`

This is so general environment variables don't accidentally overwrite your configuration.

You can also use it without the prefix by adding `.AddEnvironmentVariables()` e.g.

```csharp
WebHost.CreateDefaultBuilder(args)
  .AddEnvironmentVariables()
```
Then use `docker run -e connectionstring xxxxx`; but that risks accidentally overwriting some settings with environment variables that are set by something else (as there is no-prefix to filter them)

**Comment by andymac4182** [comment]
@lc273734858 How did you go?

**Comment by lc273734858** [comment]
@andymac4182 I'm so sorry, I'm busy in my project now ,have no enough time to try with the article.
I will answer to u when I try it finished.

**Comment by lc273734858** [comment]
@andymac4182 Thank you very much, It's wored !
`
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true)
            .AddEnvironmentVariables();
            Configuration = builder.Build();
        }
`

**Comment by lc273734858** [comment]
@benaadams Thank you very much
