### ISSUE TITLE
ComputeFilesToPublish finds files that only exist before clean

### ISSUE THREAD

**Issue by meoblast001** [dotnet/sdk#2385]
After creating `dotnet new angular -o AngularASPNet` to have a standard SPA project with webkit, I added the following code to the .csproj file:

```xml
    <Target Name="DeleteResources" BeforeTargets="Clean">
      <ItemGroup>
        <WwwRootDistFiles Include="wwwroot\dist\**\*" />
        <ClientAppDistFiles Include="ClientApp\dist\**\*" />
      </ItemGroup>
      <Delete Files="@(WwwRootDistFiles)" />
      <Delete Files="@(ClientAppDistFiles)" />
      <RemoveDir Directories="wwwroot\dist" />
      <RemoveDir Directories="ClientApp\dist" />
    </Target>
```

This should make sure that during a clean or rebuild, build directories are left clean so that files built from one build configuration don't get published in another build configuration (for example: files from a debug build should not be included in a release build).

Unfortunately, if I build once with a debug configuration, which builds source maps, and then build a release build with `MsBuild.exe ".\AngularASPNet.csproj" "/t:rebuild" "/v:m" "/p:DeployOnBuild=true" "/p:PublishProfile=Filesystem" "/p:PublishUrl=.\publish" "/p:Configuration=Release"` (which would first clean the resources because a rebuild is occurring), Microsoft.NET.Publish.targets fails, complaining that "main-client.js.map" (a file only created in debug configurations) does not exist.

If MsBuild is run twice: once with "/t:clean" and once with "/t:build", then this problem does not occur. This seems to only happen with rebuilds, when both the clean and build step are occurring in one execution.

This indicates to me that ComputeFilesToPublish is occurring before Clean is, or is in some way affected by the state of the project before cleaning, gathering files to publish that no longer exist when the build completes. I don't find this to be expected behaviour. Is there a reason for this or is it a bug?

**Comment by nguerrera** [comment]
This issue was moved to aspnet/websdk#382

**Comment by dwgray** [comment]
@nguerrera can you please provide an active reference to where this was moved, it looks like there was some kind of refactor of the aspnet git repos and the link you provided above is no longer a link and it's not obvious how to get to the place that you moved this.
