### ISSUE TITLE
[API Compat] add rule to make sure enum values match

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#23903]
We already cover that the members of an enum must exist via the [MembersMustExist rule](https://github.com/dotnet/sdk/blob/921dbcaa04265f86b4feefdffced9cfffc30378e/src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs) however we must make sure that the constant values are the same on both sides as it is a breaking change to change the underlying value of an enum member.

This rule needs that at least we are running with a reference to the core library so that the constant type and constant value is retrieved by Roslyn.

**Comment by smasher164** [comment]
As mentioned in https://github.com/dotnet/sdk/pull/25542#discussion_r878482260, the docs need to be updated with the new diagnostic.
