### ISSUE TITLE
[.NET 6.0] Hot Reload unexpected and unexplained behavior

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/sdk#23917]
### Describe the bug
I decided to create a new project to test out hot reloading. I used the latest version .NET 6.0.102 SDK downloaded directly from the microsoft website. I am on a windows 10 machine fully updated. So I was using the below file. I did a simple console project and threw this in to test it as others have done the same. When I was hotreloading by saving the file, executed by `dotnet watch run` the file says it was reloaded and the string kept saying the same thing. So I was wondering what was going on and I was at a loss after about an hour of google searching and testing and doing some basic troubleshooting like reinstall it and restart computer.

So I decided to download the .NET 5.0.405 SDK to see if it would work with that. Well it did. I created a new global.json file to switch the versions and updated the csproj accordingly. So I decided to also download the .NET 6.0.2 runtime. I swapped back to using .NET 6.0.102 SDK and well the issue resolved itself. Deleted the global.json (edited to 6.0.102) and issue persisted. I have no clue whether it was downloading the .NET 6.0.2 runtime or switching to .NET 5.0.405 SDK. I uninstalled it and the issue doesn't persist. There is some unexpected something going on. I tried to uninstall .NET 5.0.405 SDK to see if something was added. Well the issue is still fixed. Finally, I uninstalled .NET 6.0.102 SDK to reinstall it. After installing, the issue is still fixed. I deleted the build files and its still fixed.

My computer never before had any SDK installed to it, just all the runtimes shown except the .NET 6.0.2 runtime I showed above.

```csharp
using System;
using System.Threading;

namespace Entry
{
	
	class Program
	{
		public static void Main(string[] args)
		{
			var utils = new Utils();
			while (true)
			{
				utils.change();
			}
		}
	}
	
	class Utils
	{
		public void change()
		{
			Console.WriteLine("Hello world!"); // this is the string I am changing
			Thread.Sleep(1000);
		}
	}
	
}
```
![image](https://user-images.githubusercontent.com/7494772/153732010-2578ed36-1742-4ff3-aa1d-17cd20206b8f.png)
![image](https://user-images.githubusercontent.com/7494772/153732020-06703f92-bece-436e-b21a-202559491bb2.png)

Wait! Hold the phone!
[gbemulator.zip](https://github.com/dotnet/sdk/files/8054712/gbemulator.zip)
This is the tree I was trying to use out of C:\code. The issue persists. I have no idea what the heck is going on. I deleted the binaries and anything extra down to just the csproj and src folder. Issue persists.
![image](https://user-images.githubusercontent.com/7494772/153732506-ef3058ac-e89b-40f5-9e2f-cfcbe75eaecb.png)

I moved it to another folder. Issue persists.
I edited the while to be in the Main(string[] args). Issue resolved.

Why.
This means that the change was accepted by the code replacer but didnt detected it as something it couldnt replace.

### To Reproduce
1. mkdir example && cd example
2. dotnet new console
3. [modify Program.cs to include above]
4. dotnet watch run
5. [modify Program.cs + save]
6. repeat 5

### Exceptions (if any)
dotnet 5.0 works fine.
1. dotnet new globaljson
2. [edit global.json to target net5.0]
3. [edit example.csproj to target net5.0]

### Further technical details
(This was pulled as I was troubleshooting and writing this bug, so it shows 5.0.405)
```
.NET SDK (reflecting any global.json):
 Version:   5.0.405
 Commit:    63325e1c7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.405\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- VSCode or Notepad

**Comment by pranavkm** [comment]
@tilkinsc your zipped app is different from the sample you've shared above which works. Hot reload does not support on stack replacement. Methods need to be re-executed for hot reloaded changes to be picked up. In your sample, the `while` loop is within the method you're updating, which is why you don't see the change.

You can always switch back to the 5.0 behavior of dotnet-watch by passing `--no-hot-reload` switch, you don't need to uninstall the SDK. Hope this helps.
