### ISSUE TITLE
 .NET SDK 3.1 replaced the nampespace name with '_" where if ";" used

### ISSUE THREAD

**Issue by KRoy118** [dotnet/sdk#23916]
Saved a file with ";" but didn't work in .NET SDK 3.1.IT replaced the nampespace with '_"

_Originally posted by @KRoy118 in https://github.com/dotnet/sdk/issues/13954#issuecomment-1037361859_

**Comment by baronfel** [comment]
`;` isn't a valid namespace character - you can see the rules for these [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names). The SDK defaults namespaces to the project name, but if that name contains invalid characters those characters will be normalize.
