### ISSUE TITLE
After update to latest vs for mac and latest SDK 6 for .net getting Unable to find SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator'

### ISSUE THREAD

**Issue by mathis1337** [dotnet/sdk#23912]
### Describe the bug
After update to latest vs for mac and latest SDK 6 for .net getting Unable to find SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' I get this error whenever I try to open a project in VS or start a new one. 

### Further technical details
- Include the output of `dotnet --info`
- Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.406 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- VS 2022 Preview for MAC latest version

**Comment by mathis1337** [comment]
I should not doing a normal dotnet build and run from terminal loads the project, but I can no longer load any projects into visual studio for coding. Any insight would be appreciated.

**Comment by mathis1337** [comment]
after uninstall and reinstall and completely wiping out all .net stuff it is working. There is definitely an issue with the update process though.

**Comment by ramfattah** [comment]
Came across this same issue after downloading latest version of visual studio for mac 

#### Environment
* .NET SDK 6.0.403
* .NET Runtime 6.0.11
* Visual Studio 17.4 (build 2406)
* OS: macOS Ventura 13.0 (M1 chip) 



![image](https://user-images.githubusercontent.com/38049078/201204418-23f57c84-cda2-4151-9ec2-cfb0dfd6f541.png)


Investigating further on this...
