### ISSUE TITLE
Trying to get the packages for MAUI with MSVS 2022 preview did not download

### ISSUE THREAD

**Issue by Kings-Ohio** [dotnet/sdk#23921]
Installed: Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 6.0

$(TargetFrameworks);net6.0-windows10.0.19041

Visual Studio consistently shows the dependencies for MAUI did not download. 

When I open and build a new project the first thing in the error window is:

Build started...
Failed to download package 'Microsoft.WindowsDesktop.App.Runtime.win-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.windowsdesktop.app.runtime.win-arm64/6.0.1/microsoft.windowsdesktop.app.runtime.win-arm64.6.0.1.nupkg'.
Cannot access a disposed object.
Object name: 'SslStream'.
Failed to download package 'Microsoft.NETCore.App.Runtime.win-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg' has timed out after 100000ms.
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Error occurred while restoring NuGet packages: Central Directory corrupt.
Build has been canceled.

Apologies for ignorance, any help appreciated!

**Comment by Kings-Ohio** [comment]
Area label: Install

**Comment by Kings-Ohio** [comment]
I was able to clear the nuget cache and noted that my ``\,nuget\Packages was deleted, as you suggested (Had been there just before). After a clean and rebuild I do see this about central directory being corrupted:

Build started...
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Error occurred while restoring NuGet packages: Central Directory corrupt.
Build has been canceled.

The  ``\,nuget\Packages  had reappeared


 Directory of c:\Users\pekin\.nuget\Packages

02/16/2022  10:40 PM    <DIR>          .
02/16/2022  10:40 PM    <DIR>          ..
02/16/2022  10:33 PM    <DIR>          microsoft.aspnetcore.app.runtime.win-arm64
02/16/2022  10:33 PM    <DIR>          microsoft.aspnetcore.app.runtime.win-x64
02/16/2022  10:33 PM    <DIR>          microsoft.aspnetcore.app.runtime.win-x86
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.abstractions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.binder
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.commandline
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.environmentvariables
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.fileextensions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.json
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.configuration.usersecrets
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.dependencyinjection
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.dependencyinjection.abstractions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.fileproviders.abstractions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.fileproviders.physical
02/16/2022  10:34 PM    <DIR>          microsoft.extensions.filesystemglobbing
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.hosting
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.hosting.abstractions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.abstractions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.configuration
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.console
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.debug
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.eventlog
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.logging.eventsource
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.options
02/16/2022  10:34 PM    <DIR>          microsoft.extensions.options.configurationextensions
02/16/2022  10:33 PM    <DIR>          microsoft.extensions.primitives
02/16/2022  10:33 PM    <DIR>          microsoft.graphics.win2d
02/16/2022  10:33 PM    <DIR>          microsoft.maui.controls.build.tasks
02/16/2022  10:33 PM    <DIR>          microsoft.maui.dependencies
02/16/2022  10:33 PM    <DIR>          microsoft.maui.extensions
02/16/2022  10:33 PM    <DIR>          microsoft.maui.graphics
02/16/2022  10:33 PM    <DIR>          microsoft.maui.graphics.win2d.winui.desktop
02/16/2022  10:33 PM    <DIR>          microsoft.maui.resizetizer.sdk
02/16/2022  10:33 PM    <DIR>          microsoft.netcore.app.host.linux-arm
02/16/2022  10:33 PM    <DIR>          microsoft.netcore.app.host.linux-arm64
02/16/2022  10:33 PM    <DIR>          microsoft.netcore.app.host.linux-x64
02/16/2022  10:40 PM    <DIR>          microsoft.netcore.app.runtime.win-arm64
02/16/2022  10:33 PM    <DIR>          microsoft.netcore.app.runtime.win-x64
02/16/2022  10:33 PM    <DIR>          microsoft.netcore.app.runtime.win-x86
02/16/2022  10:33 PM    <DIR>          microsoft.windows.sdk.net.ref
02/16/2022  10:33 PM    <DIR>          microsoft.windowsappsdk
02/16/2022  10:33 PM    <DIR>          microsoft.windowsdesktop.app.runtime.win-arm64
02/16/2022  10:33 PM    <DIR>          microsoft.windowsdesktop.app.runtime.win-x64
02/16/2022  10:33 PM    <DIR>          microsoft.windowsdesktop.app.runtime.win-x86
02/16/2022  10:33 PM    <DIR>          system.diagnostics.diagnosticsource
02/16/2022  10:34 PM    <DIR>          system.diagnostics.eventlog
02/16/2022  10:33 PM    <DIR>          system.runtime.compilerservices.unsafe
02/16/2022  10:34 PM    <DIR>          system.text.encodings.web
02/16/2022  10:34 PM    <DIR>          system.text.json
02/16/2022  10:33 PM    <DIR>          xamarin.android.glide
02/16/2022  10:33 PM    <DIR>          xamarin.android.glide.disklrucache
02/16/2022  10:33 PM    <DIR>          xamarin.android.glide.gifdecoder
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.activity
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.annotation
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.annotation.experimental
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.appcompat
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.appcompat.appcompatresources
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.arch.core.common
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.arch.core.runtime
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.asynclayoutinflater
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.browser
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.cardview
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.collection
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.concurrent.futures
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.constraintlayout
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.constraintlayout.core
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.coordinatorlayout
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.core
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.cursoradapter
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.customview
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.documentfile
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.drawerlayout
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.dynamicanimation
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.exifinterface
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.fragment
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.interpolator
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.legacy.support.core.ui
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.legacy.support.core.utils
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.legacy.support.v4
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.lifecycle.common
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.lifecycle.livedata
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.lifecycle.livedata.core
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.lifecycle.runtime
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.lifecycle.viewmodel
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.lifecycle.viewmodelsavedstate
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.loader
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.localbroadcastmanager
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.media
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.navigation.common
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.navigation.fragment
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.navigation.runtime
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.navigation.ui
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.print
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.recyclerview
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.savedstate
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.slidingpanelayout
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.swiperefreshlayout
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.tracing.tracing
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.transition
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.vectordrawable
02/16/2022  10:33 PM    <DIR>          xamarin.androidx.vectordrawable.animated
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.versionedparcelable
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.viewpager
02/16/2022  10:34 PM    <DIR>          xamarin.androidx.viewpager2
02/16/2022  10:33 PM    <DIR>          xamarin.google.android.material
02/16/2022  10:33 PM    <DIR>          xamarin.google.guava.listenablefuture
               0 File(s)              0 bytes
             110 Dir(s)  868,839,415,808 bytes free

Any suggestions appreciated!

**Comment by Kings-Ohio** [comment]
I am  in a perfect storm of confusion as I said after clean/rebuild I see this error in VS 2022 Preview:

Error		Error occurred while restoring NuGet packages: Central Directory corrupt.	

One other thing in the output tab, showing output from the Package Manager - file transfer timing out after 100 seconds. This could be something on my side? It ends with the issue of the corrupted central directory.

After every clean of the cache the packages folder goes away, but comes back on the build. 

Failed to download package 'Microsoft.NETCore.App.Runtime.win-x64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/6.0.1/microsoft.netcore.app.runtime.win-x64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/6.0.1/microsoft.netcore.app.runtime.win-x64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Host.linux-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm64/6.0.1/microsoft.netcore.app.host.linux-arm64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm64/6.0.1/microsoft.netcore.app.host.linux-arm64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Host.linux-arm.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm/6.0.1/microsoft.netcore.app.host.linux-arm.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm/6.0.1/microsoft.netcore.app.host.linux-arm.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Runtime.win-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.AspNetCore.App.Runtime.win-x64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/6.0.1/microsoft.aspnetcore.app.runtime.win-x64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/6.0.1/microsoft.aspnetcore.app.runtime.win-x64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Runtime.win-x64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/6.0.1/microsoft.netcore.app.runtime.win-x64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/6.0.1/microsoft.netcore.app.runtime.win-x64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Runtime.win-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-arm64/6.0.1/microsoft.netcore.app.runtime.win-arm64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.AspNetCore.App.Runtime.win-x64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/6.0.1/microsoft.aspnetcore.app.runtime.win-x64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/6.0.1/microsoft.aspnetcore.app.runtime.win-x64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Host.linux-arm64.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm64/6.0.1/microsoft.netcore.app.host.linux-arm64.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm64/6.0.1/microsoft.netcore.app.host.linux-arm64.6.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.NETCore.App.Host.linux-arm.6.0.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm/6.0.1/microsoft.netcore.app.host.linux-arm.6.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.host.linux-arm/6.0.1/microsoft.netcore.app.host.linux-arm.6.0.1.nupkg' has timed out after 100000ms.
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:07:08.7775267
========== Finished ==========


Error occurred while restoring NuGet packages: Central Directory corrupt.

**Comment by Kings-Ohio** [comment]
Hey thanks for the good initial suggestion - my bad - I should check with Nuget. I've never had a problem with Github.

**Comment by mattleibow** [comment]
Yeah, stacks of the negative timeout error these days

>  Workload installation failed: The request was canceled due to the configured HttpClient.Timeout of -0.001 seconds elapsing.

**Comment by mattleibow** [comment]
Just adding that this sis still happening and we are using the `6.0.300-preview.22168.1` SDK. Pretty much a consistent failure so we added a retry and then it works the second time around...

**Comment by marcpopMSFT** [comment]
Both the original issue and the comments from Maui appear to be nuget related. It could be an issue with the local cache or the feeds or nuget but I'd ask them.

@mattleibow are you seeing you see nuget timeouts the first time you try it even today?

CC @aortiz-msft

**Comment by marcpopMSFT** [comment]
If you're still seeing workload installation failures, please open a separate issue.
