### ISSUE TITLE
NuGet package documentation files are not published with project

### ISSUE THREAD

**Issue by vaindil** [dotnet/sdk#2393]
I'm using VS 2017 15.8 Preview 4, so .NET SDK 2.1.400-preview-009063. I have a NuGet package that includes XML documentation, I've verified that the XML file does exist with the package. I have these three properties explicitly specified:

```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
<PublishDocumentationFile>true</PublishDocumentationFile>
<PublishReferencesDocumentationFiles>true</PublishReferencesDocumentationFiles>
```

Despite this, the XML file that came with the NuGet package is not included in the build output, either when building or publishing. An doc file is generated for the project itself, but the bundled one from the NuGet package is not included.

**Comment by nguerrera** [comment]
What TargetFramework(s) does your project have?

**Comment by vaindil** [comment]
Both the NuGet package and the consuming project are targeting `netcoreapp2.1`.
