### ISSUE TITLE
IIS Virtual directory app hosting

### ISSUE THREAD

**Issue by popraducj** [dotnet/sdk#2396]
I have been trying to make the .net core 2.1 work with  virtual directories.

I have the default site from iis and I want to add a virtual directory lets say "vd"
I have set the clr to no managed, I have add the same project published files into the C:\inetpub\wwwroot so the project will start.

The app that I want to deploy is a simple generated webapi solution. 

The link localhost/api/values returns values
The link localhost/vd/api/values returns 404.

my config file for the sub-app is 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <aspNetCore processPath="dotnet" arguments=".\test.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

and my config file for the main directory is
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\stash.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

I am sure it hits the virtual directory somehow  because if I do not set correctly the sub-app config it yell duplicate aspnetCore module.

How can I make the virtual directory work?

Ps. I only use  the same ddls on the root of the website because I need to provide something on the no manged app clr.

**Comment by nguerrera** [comment]
This issue was moved to aspnet/websdk#384
