### ISSUE TITLE
DPAPI error messages since updating VS to 17.1.0

### ISSUE THREAD

**Issue by UweKeim** [dotnet/sdk#23989]
Since we updated VS 2022 to 17.1.0 yesterday, running this command:

```cmd
dotnet tool update dotnet-outdated-tool -g
```

Results in this error message:

```
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error : Der Dienstindex für die Quelle "https://nuget.telerik.com/v3/index.json" konnte nicht geladen werden. [C:\Users\ukeim\AppData\Local\Temp\p1eijxar.5tx\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error :   Kennwortentschlüsselung wird für .NET Core für diese Plattform nicht unterstützt. Der folgende Feed verwendet ein verschlüsseltes Kennwort: "nuget.telerik.com". Sie können ein Klartextkennwort als Problemumgehung verwenden. [C:\Users\ukeim\AppData\Local\Temp\p1eijxar.5tx\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.200\NuGet.targets(130,5): error :   Windows Data Protection API (DPAPI) is not supported on this platform. [C:\Users\ukeim\AppData\Local\Temp\p1eijxar.5tx\restore.csproj]
Fehler beim Update des Tools "dotnet-outdated-tool". Ursache:
Das Toolpaket konnte nicht wiederhergestellt werden.
Fehler bei der Installation des Tools "dotnet-outdated-tool". Dieser Fehler kann folgende Ursachen haben:

* Sie versuchen, eine Vorschauversion zu installieren und haben nicht die Option "--version" verwendet, um die Version anzugeben.
* Ein Paket mit diesem Namen wurde gefunden, aber es handelte sich nicht um ein .NET-Tool.
* Auf den erforderlichen NuGet-Feed kann nicht zugegriffen werden, möglicherweise aufgrund eines Problems mit der Internetverbindung.
* Sie haben den Namen des Tools falsch eingegeben.

Weitere Gründe sowie Informationen zum Erzwingen der Paketbenennung finden Sie unter https://aka.ms/failure-installing-tool.
```
(German error message, sorry).

Translated to English the error messages read:

> The service index for source "`https://nuget.telerik.com/v3/index.json`" could not be loaded. [C:\Users\ukeim\AppData\Local\Temp\p1eijxar.5tx\restore.csproj]
> 
> Password decryption is not supported for .NET Core for this platform. The following feed uses an encrypted password: nuget.telerik.com. You can use a clear text password as a workaround.
> 
> Windows Data Protection API (DPAPI) is not supported on this platform. 

On the PC of one of my co-workers the error occurs on a different NuGet feed, so I do think this is not related to the feed itself. And I also doubt that this is related to the [dotnet-outdated](https://github.com/dotnet-outdated/dotnet-outdated) tool itself.

### My question

Is this a known issue? Are there any workaround?

**Comment by UweKeim** [comment]
Could be related to this SO question:

https://stackoverflow.com/q/64341361/107625

**Comment by UweKeim** [comment]
A workaround, based on [this comment](https://stackoverflow.com/questions/64341361/password-decryption-not-supported-on-net-core-for-windows/71101968#comment113776552_64341361):

1. Remove any custom NuGet sources that have a password set with the command `dotnet nuget remove source "Name Of My Source"`.
1. Add the sources again, specifying the `--store-password-in-clear-text` option.

Example:

```cmd
dotnet nuget add source "https://example.com/index.json" -n "Example" -u Xyz -p Abc --store-password-in-clear-text
```
(With `Xyz` being the actual user name and `Abc` being the actual password).

This workaround seems to work well, but I still don't know why this happens, all of a sudden after updating VS 2022 to 17.1.0.

**Comment by baronfel** [comment]
Correct, this is a duplicate. Thank you for reporting, but I'll close this in favor of #23498.

**Comment by norgie** [comment]
We had no problems building/restoring using the .Net 6.0.2. SDK. After upgrading our build server to v. 6.0.3 we get the same error message as in the initial message in this thread.
