### ISSUE TITLE
MSBuild AvailablePlatforms property should include arm64

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#23994]
Adding an arm64 target platform for a project cannot be done within VS today. And in fact doing it manually in msbuild causes the VS Configuration Manager to malfunction because the MSBuild project's `AvailablePlatforms` property does not include arm64. In fact it is set to this:

AvailablePlatforms = Any CPU,x86,x64

By adding `arm64` to this list, VS lights up to allow users to intentionally target arm64.
See also #15434, which completes the story.

**Comment by marcpopMSFT** [comment]
My fix already went in so closing.
