### ISSUE TITLE
Add --configfile switch to dotnet list package

### ISSUE THREAD

**Issue by roryprimrose** [dotnet/sdk#24004]
### Is your feature request related to a problem? Please describe.
I am cloning repositories in an Azure DevOps pipeline from multiple organisations to search for package issues (deprecated, outdated and vulnerable dependencies). I determine the possible Azure Artifact feeds that may be involved in running `dotnet` CLI commands against that repository and dynamically generate a nuget.config file.

Running `dotnet restore '{csprojpath}' --configfile '{temppath}/nuget.config' --ignore-failed-sources` works completely fine. Part of the log output of the restore includes this:

```
  NuGet Config files used:
      /agent/_work/_temp/feedconfig/{someorg}/{someproject}/nuget.config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
      https://pkgs.dev.azure.com/{someorg}/{someprojectid}/_packaging/{projectfeedid}/nuget/v3/index.json
      https://pkgs.dev.azure.com/{someorg}/_packaging/{orgfeedid}/nuget/v3/index.json
```

The `dotnet list {csprojpath} package` CLI commands do not support a `--configfile` switch and I cannot get it to consult those feeds. For example, I run `dotnet list {csprojpath} --outdated` and I get the following in the output:

```
The following sources were used:
   https://api.nuget.org/v3/index.json

  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.extensions.http/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.extensions.storage/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.sdk/index.json
  GET https://api.nuget.org/v3/registration5-gz-semver2/{myinternalpackage}/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/system.text.regularexpressions/index.json
  NotFound https://api.nuget.org/v3/registration5-gz-semver2/{myinternalpackage}/index.json 401ms
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.extensions.http/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.extensions.storage/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.functions.worker.sdk/index.json
  GET https://api.nuget.org/v3/registration5-gz-semver2/{myinternalpackage}/index.json
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/system.text.regularexpressions/index.json
  NotFound https://api.nuget.org/v3/registration5-gz-semver2/{myinternalpackage}/index.json 280ms
Project `{MyProject}` has the following updates to its packages
   [net6.0]: 
   Top-level Package                  Requested   Resolved   Latest                  
   > {MyInternalPackage}      1.0.0       1.0.0      Not found at the sources
```

### Describe the solution you'd like
`dotnet list` supports the `--configfile` switch so that we can be explicit on the CLI regarding which feeds to consume for that operation.

### Additional context
I have tried running the dotnet CLI commands with the working directory that contains nuget.config. I have also tried installing the artifacts credential provider and building the `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable. Nothing I have done will get `dotnet list package` to check the feeds in my custom nuget.config.

**Comment by baronfel** [comment]
This looks like something we should do, and because we chose the [`--configfile` syntax for restore](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs#L115-L121) we should keep it here for consistency.

This should be a simple pass-through, because the [`dotnet nuget package list` command](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs#L45-L60) that we forward to already supports a `--config` parameter.

**Comment by baronfel** [comment]
@roryprimrose would you be interested in contributing this?  It looks to be fairly straightforward as these things go, and we'd be happy to help you through the process if you desired.

**Comment by roryprimrose** [comment]
@baronfel For sure, I can sort it out.

**Comment by baronfel** [comment]
hey @roryprimrose, can you check if the `--config` argument works for this? it looks like we [have this already](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs#L43-L46).  If that works for you, we possibly should consider adding aliases to the option names to help guide users towards a unified name for the NuGet config file.

**Comment by roryprimrose** [comment]
@baronfel Ah, yes. I see that in the CLI help. I don't see any doco for either `dotnet nuget package list` or the `-config` switch on dotnet list package.

I'll test it out.

**Comment by roryprimrose** [comment]
@baronfel I don't think an alias is required so much as documentation should be updated to reflect the capabilities of the CLI.

**Comment by roryprimrose** [comment]
The `-config` switch works as expected. My scanning is now consulting our internal AzDO feeds.

**Comment by roryprimrose** [comment]
@baronfel thanks for the help. Another semi-related potential issue is that it looks like `dotnet add package` does not support any config file switch at all. This may be an issue with upgrading a package version where a custom config is in play.

```
 dotnet add package

Required argument missing for command: package
Description:
  Add a NuGet package reference to the project.

Usage:
  dotnet [options] add [<PROJECT>] package [<PACKAGE_NAME>]

Arguments:
  <PROJECT>       The project file to operate on. If a file is not specified, the command will search the current directory for one. [default: C:\Repos\{snip}\]
  <PACKAGE_NAME>  The package reference to add.

Options:
  -v, --version <VERSION>            The version of the package to add.
  -f, --framework <FRAMEWORK>        Add the reference only when targeting a specific framework.
  -n, --no-restore                   Add the reference without performing restore preview and compatibility check.
  -s, --source <SOURCE>              The NuGet package source to use during the restore.
  --package-directory <PACKAGE_DIR>  The directory to restore packages to.
  --interactive                      Allows the command to stop and wait for user input or action (for example to complete authentication).
  --prerelease                       Allows prerelease packages to be installed.
  -?, -h, --help                     Show command line help.
```

**Comment by baronfel** [comment]
For that issue in particular, we're limited to what the NuGet CLI supports, since the `dotnet add package` is just a front for that (for consistency purposes). 

```
23:19:45 ❯ dotnet nuget package add --help


Usage: NuGet.CommandLine.XPlat.dll package add [options]

Options:
  -h|--help               Show help information
  --force-english-output  Forces the application to run using an invariant, English-based culture.
  --package               Id of the package to be added.
  --version               Version of the package to be added.
  -d|--dg-file            Path to the dependency graph file to be used to restore preview and compatibility check.
  -p|--project            Path to the project file.
  -f|--framework          Frameworks for which the package reference should be added.
  -n|--no-restore         Do not perform restore preview and compatibility check. The added package reference will be unconditional.
  -s|--source             Specifies NuGet package sources to use during the restore.
  --package-directory     Directory to restore packages in.
  --interactive           Allow the command to block and require manual action for operations like authentication.
  --prerelease            Allows prerelease packages to be installed.
```

There may be another way to approach it, but if so I'm not aware of it.

**Comment by baronfel** [comment]
Reopening and re-categorizing because this one is firmly in the CLI's area - we need to unify the naming for this parameter and make sure it's honored during any CLI commands that manage packages.
