### ISSUE TITLE
Unlisted packages are still installed via `dotnet tool install` without `--version` despite correctly not showing up in `dotnet tool search`

### ISSUE THREAD

**Issue by zentron** [dotnet/sdk#24037]
### Describe the bug
A tool that was incorrectly versioned was pushed to NuGet.org and had to be unlisted. 
The version is correctly hidden from searches both via nuget.org and via `dotnet tool search` but `dotnet tool install` seems to ignore this and just locate the version via the provided [v3-flatcontainer list](https://api.nuget.org/v3-flatcontainer/octopus.dotnet.cli/index.json) 
![image](https://user-images.githubusercontent.com/1830666/154891229-ed9b6f73-f151-43ec-b9e8-177d95aee926.png)

I can vaguely get on board with argument that if there are dependencies on that version then it shouldn't break them by being completely inacessable, but shouldn't that really only apply in that case if that specific version is requested via `--version` rather than by default?
What's the point of hiding it in the search if its still the one that is installed by default, that feels a little unexpected for the end user and potentially less safe.

It's worth noting this also [existed and since been fixed](https://github.com/NuGet/Home/issues/7466) in `NuGet.exe`

### To Reproduce
1. Publish two versions of a tool to nuget.org
2. [Unlist](https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package) the latest version
3. Run `dotnet tool search <TOOLNAME>` and validate that the unlisted version does not show up
3. run `dotnet tool install --global <TOOLNAME>`
**Result**
The later but, _unlisted_ version is installed
**Expected**
The latest _listed_ result is installed

### Further technical details
This can be reproduced through the dotnet sdk container
```
> run --rm -it mcr.microsoft.com/dotnet/sdk:6.0 bash
> dotnet tool install --global Octopus.DotNet.Cli
```
using dotnet version `6.0.200`

**Update: 25 Feb** I have since had to contact the NuGet team directly to get the package properly "deleted" so the specific package in this example is no longer a problem but the fundamental issue still remains.

**Comment by baronfel** [comment]
This is because we use nuget restore to install the tool's associated nuget package, and if no version is specified we use a range of `*`. This range opts NuGet into the latest stable version.  We should probably do an actual NuGet query for the latest _listed_ version, as you suggest, before performing the install.  This version range assignment happens [here](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs#L99).

**Comment by clairernovotny** [comment]
We should ensure the semantics for this are the same as `dotnet nuget add ... `

**Comment by JiaqiWang18** [comment]
Hi everyone, my name is Jacky and I am a CS student at JHU. I would like to work on this issue if possible.

**Comment by elinor-fung** [comment]
@JiaqiWang18 that sounds great - thanks! I have assigned the issue to you.

**Comment by JiaqiWang18** [comment]
PR is up for this issue: https://github.com/dotnet/sdk/pull/28951
