### ISSUE TITLE
Can't reference net461 project from netcoreapp.

### ISSUE THREAD

**Issue by mfilippov** [dotnet/sdk#2405]
I try to reference a net461 project based on new csproj from a netcoreapp project. It doesn't work. But I can reference net461 project with classic csproj.
Repro solution:
[ReferenceTester.zip](https://github.com/dotnet/sdk/files/2202631/ReferenceTester.zip)
``` 
#dotnet --version
2.1.301
```
What I'm doing wrong?

**Comment by nguerrera** [comment]
The change I was talking about was this one: https://github.com/Microsoft/msbuild/issues/2934

It is in MSBuild 15.8 which is not part of 2.1.301 SDK. It should be possible with a 2.1.400 Preview  SDK. You can obtain that either by installing VS 15.8 Preview and the .NET Core workload or using the links at https://github.com/dotnet/cli/tree/release/2.1.4xx

**Comment by mfilippov** [comment]
@nguerrera Thank you for the information. I checked repro project build on 2.1.4xx SDK. It works correctly.
