### ISSUE TITLE
Remove Legacy `--` behavior and use of UnparsedTokens

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#24068]
### Is your feature request related to a problem? Please describe.
As part of cleaning up the CLI, we should remove our use of the LegacyDoubleDashHandling logic in System.CommandLine, and instead be explicit about argument forwarding as described [here](https://github.com/dotnet/sdk/pull/23889#issuecomment-1043117342).  We are the main user of LegacyDoubleDashHandling, and System.CommandLine wants to remove that API entirely (see https://github.com/dotnet/command-line-api/issues/1653).

### Describe the solution you'd like
In places where we use the double-dash behavior and UnparsedTokens to forward arguments along, we should instead create an explicit `string[]` Argument and forward the value of that argument along. This also leads to more useful help displays for the user.

#### Direct use of `UnparsedTokens`

* [RunCommand](https://github.com/dotnet/sdk/blob/957ae5ca599fdeaee425d23928d42da711373a5e/src/Cli/dotnet/commands/dotnet-run/Program.cs#L41)
* [ToolRunCommand](https://github.com/dotnet/sdk/blob/511db743f63fd394383f5549412f80a4dbab318b/src/Cli/dotnet/commands/dotnet-tool/run/ToolRunCommand.cs#L25)

These are straightforward, and in the 'new world' would simply be removed, as the `UnmatchedTokens` + a new `string[]` argument should cover all use cases

#### ParseResult.GetArguments()/ParseResult.GetSubArguments()

Definition is [here](https://github.com/dotnet/sdk/blob/44b6557850a51858ef0b7c21f2161de5563cf460/src/Cli/dotnet/ParseResultExtensions.cs#L85-L107).  The `GetArguments()` extension method is commonly used to grab all of the tokens in a command and delegate them to some non-bundled command. Adding a `string[]` argument may make this easier/not necessary to do for some forwarding applications.

`GetSubArguments()` is the more concerning one to me - it actually modifies the token stream. This may not be necessary after the change to the `--` handling, but the custom logic about removing the `dotnet` command if it is prepended, as well as the 'top-level` command, may still be required.  

#### Direct use of `--` in command processors

* [dotnet test](https://github.com/dotnet/sdk/blob/aa8d851ebed09ac7b3d123fead79f2ca72106359/src/Cli/dotnet/commands/dotnet-test/Program.cs#L48)

#### Specific commands/scenarios to verify

* dotnet build
* dotnet msbuild
* dotnet test
* dotnet vstest
* dotnet run
* dotnet publish
* any nuget command

**Comment by Tunduk** [comment]
@baronfel Hi! 
I want try to fix this. 
I didn't find any contributors guide, can I just start work on issue? Or some special actions required?

**Comment by baronfel** [comment]
Hi @Tunduk, thanks for your interest in this! There's a _lot_ to uncover here, and I just fleshed out the description with some of my specific concerns.  This will be a _very high touch_ operation, so it's important that we're thorough. At the same time, it's the kind of work that's hard to do part-way.  I would say since no one has picked it up, if you wanted to start working on it I can assign it to you and you can open a draft PR when you're ready.

**Comment by Tunduk** [comment]
Thanks for your update, its realy useful!
I thought this issue is about removing `UnparsedToken`. Now the issue seems harder, but I'll try.
Could I ask you in case if I need help?

**Comment by baronfel** [comment]
Yes, of course! The problem with removing `UnparsedToken` is that it's currently being populated by the `LegacyDoubleDashHandling` setting we have configured. So if we want to remove use of `UnparsedToken` we have to change the value of this setting, and _that_ means that we have to fix the semantics of all of these call-sites.  It's definitely a puzzle :)

**Comment by Tunduk** [comment]
@baronfel Hi! I am trying to run tests locally but some of them fail.
For example, `GivenThatWeHaveErrorCodes.ResxIsCommentedWithCorrectStrBegin` fail but it's correct behavior, because in `Strings.resx` missed comment tag for `ILLinkRunning`.
Should I just ignore failed tests? Or I just run test in wrong way?
I am using latest main branch and run tests with `build.cmd --test`

**Comment by Tunduk** [comment]
@marcpopMSFT I think you can close this issue. [PR](https://github.com/dotnet/sdk/pull/26761) fixed it.
@baronfel I'll create a separate issue for custom parsers, so we won't forget about it.
