### ISSUE TITLE
short URL for "what's new" still pointing to .NET 5 docs

### ISSUE THREAD

**Issue by alefranz** [dotnet/sdk#24081]
### Describe the bug
When running the .NET 6 SDK for the first time, the splash screen (splash text?) report some useful links, but the "what's new" one still points to the .NET 5 docs `https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-5`
Not sure if the `aka.ms` short URL should have been updated or it needs a new link.

```
Find out what's new: https://aka.ms/dotnet-whats-new
```

### To Reproduce
Install the .NET 6 SDK on a brand new machine and run any `dotnet` command.

**Comment by baronfel** [comment]
@alefranz thanks for pointing this out!

@leecow you're mentioned as the link owner in aka.ms - can you help with updating this link?

**Comment by leecow** [comment]
Updated!
