### ISSUE TITLE
CS0234 'Http' does not exist in the namespace 'System.Net' when targeting .NET Fx 4.x with implicit usings

### ISSUE THREAD

**Issue by chucker** [dotnet/sdk#24146]
### Describe the bug
C# 10 introduces global usings. The .NET 6 SDK ships with a default template for implicit usings. For the regular SDK (e.g., non-Web), this generated C# looks like:

```csharp
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

However, System.Net.Http is a namespace that does not exist in .NET Framework 4.x. Therefore, this namespace should not be imported implicitly.

### To Reproduce
A `csproj` like this will suffice:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

This will fail to build with:

    Error | CS0234 | The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)

**Comment by chucker** [comment]
(As a workaround, you can put `namespace System.Net.Http { }` somewhere in a C# file.)

**Comment by pranavkm** [comment]
> Therefore, this namespace should not be imported implicitly.

The default list of usings are primarily tailored for .NET 6 and newer apps, and aren't enabled by default. You can use the `Using` itemgroup to specify a custom list of global usings to be used for your app, or use MSBuild to remove ones added by `ImplicitUsings=Enable` e.g. `<Using Remove="System.Net.Http" />`.

**Comment by aprillove2858** [comment]
FUCK YOU STOP BY

**Comment by xiaoxstz** [comment]
Which node to put `<Using Remove="System.Net.Http" />` ?

**Comment by xiaoxstz** [comment]
I solved it by installing the nuget package "System.Net.Http"

**Comment by hrumhurum** [comment]
An automatic workaround for the whole solution is to put near `.sln` file a `Directory.Build.targets` file with the following content:

```xml
<Project>

  <!-- Workaround for https://github.com/dotnet/sdk/issues/24146 -->
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
    <Using Remove="System.Net.Http" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' AND $([MSBuild]::VersionLessThan($(TargetFrameworkVersion), '4.0')) ">
    <Using Remove="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' AND $([MSBuild]::VersionLessThan($(TargetFrameworkVersion), '3.5')) ">
    <Using Remove="System.Linq" />
  </ItemGroup>

</Project>
```

**Comment by Tyler-H** [comment]
> An automatic workaround for the whole solution is to put near `.sln` file a `Directory.Build.targets` file with the following content:
> 
> ```
> <Project>
> 
>   
>   <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
>     <Using Remove="System.Net.Http" />
>   </ItemGroup>
>   <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' AND $([MSBuild]::VersionLessThan($(TargetFrameworkVersion), '4.0')) ">
>     <Using Remove="System.Threading.Tasks" />
>   </ItemGroup>
>   <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' AND $([MSBuild]::VersionLessThan($(TargetFrameworkVersion), '3.5')) ">
>     <Using Remove="System.Linq" />
>   </ItemGroup>
> 
> </Project>
> ```

Put "near" it? What does that mean? Do you mean put that content _in_ the .sln file?
