### ISSUE TITLE
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	IDADOS Decompiler

### ISSUE THREAD

**Issue by rcamp48** [dotnet/sdk#2419]
I am trying to compile IDADOS with Visual Studio 2017 and when I run dosbox.cpp as the main project I get the error in the title above. How do I compile this program with Visual Studio 2017, I am totally new to this and would like to get IDADOS version of Dosbox compiled to an EXE file so I can recover the source code from my program, LOTTO54B,.EXE (compiled with QB45 20 years ago, source is long gone). Any help would be appreciated.  Russ Campbell
[idados_dosbox-master.zip](https://github.com/dotnet/sdk/files/2211594/idados_dosbox-master.zip)

**Comment by dsplaisted** [comment]
Unfortunately this isn't the place to ask this question, and I'm not familiar enough with C++ in VS 2017 to help with this.

I'd suggest asking for help on the IDADOS or dosbox pages, or on http://stackoverflow.com.
