### ISSUE TITLE
dotnet sdk problem with running Azure Function project in Mac M1 in Rider

### ISSUE THREAD

**Issue by malyszdev** [dotnet/sdk#24215]
Hi guys,

I have a big problem with dotnet sdk when I want running Azure Function project in Mac with M1 in Rider. I see this error:

/JetBrains/Rider2021.3/azure-functions-coretools/4.0.3971/func host start --pause-on-error
dotnet sdk is required for dotnet based functions. Please install 

but this problem is not recognized in other projects - I can run typical .NET Core app with dotnet sdk, and no error is displayed.

I am looking for Google, but all proposals etc. can not help.

ps. I'm using .NET 6

**Comment by dsplaisted** [comment]
This sounds like an issue with the Azure Functions tooling.  It looks like the right repo to file this issue would be https://github.com/Azure/azure-functions-core-tools.  Some related issues there:

https://github.com/Azure/azure-functions-core-tools/issues/2303
https://github.com/Azure/azure-functions-core-tools/issues/2834
