### ISSUE TITLE
Publish should not depend on RunResolvePackageDependencies

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2421]
Based on investigating https://github.com/dotnet/core-sdk/pull/34#pullrequestreview-139145867 and comparing to the [2.1.4xx code](https://github.com/dotnet/cli/blob/6f5d38734b15f78a96446717dcd54ba78bc9934f/src/redist/redist.csproj#L217), it looks like the `Publish` target depends on `RunResolvePackageDependencies`, which should not be necessary anymore (`ResolvePackageAssets` replaces it, and is faster).

Assigning to 3.0 since this could be a breaking change for targets that use the MSBuild items created by `RunResolvePackageDependencies`.

**Comment by nguerrera** [comment]
Publish does not actually depend on RunResolvePackageDependencies. I checked 2.2.301 and 3.0 preview8 binlogs and studied the code. I don't think it ever has.

It looks like something else reordered the targets in the build, which already depended on RunResolvePackageDependencies elsewhere: https://github.com/dotnet/cli/blob/6f5d38734b15f78a96446717dcd54ba78bc9934f/build/MSBuildExtensions.targets#L90
