### ISSUE TITLE
Make .NET Framework fallback open-ended

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#2425]
When a developer references a NuGet package that doesn't provide any assets for the current .NET platform, the SDK will fallback to try .NET Framework assets, provided the current .NET platform supports at least .NET Standard 2.0.

The [fallback works](https://github.com/dotnet/sdk/blob/581f5371dac022ad2b3e5bcdbb2e576bd73b5c4a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L145) by telling the NuGet selection algorithm "pretend I'm .NET Framework **4.6.1** so select me assets for that". We [determined that to be unfortunate](https://github.com/dotnet/standard/issues/724) and would like to change that to .NET Framework **5.0**.

The rationale being:

* It will automatically work for all current and future 4.x releases
* We don't plan on shipping another side-by-side release of the .NET Framework
* Given that this mapping is best effort and one way only, even if we do ship a 5.0.0, nothing bad would happen. Worst case, we have to bump the mapping to an even higher version.

**Update**

@nguerrera [raised concerns](https://github.com/dotnet/sdk/issues/2425#issuecomment-412209026) regarding breaking people. So we generally want an algorithm that picks the "smallest" .NET Framework as that wouldn't change the behavior from today or we add new versions of .NET Framework. So I propose instead of mapping it straight to **5.0** we do this:

```
AssetTargetFallback = net461;net462;net47;net471;net472;net48
```

/cc @weshaggard @ericstj @davidfowl @Petermarcu @dsplaisted @nguerrera

**Comment by nguerrera** [comment]
Not strictly related, but 15.8 added P2P refs based on AssetTargetFallback, but failed to match the warning of package refs. While I've got interested people's attention: https://github.com/NuGet/Home/issues/713

**Comment by nguerrera** [comment]
Sorry, 7137

**Comment by joperezr** [comment]
[Copying comment I made on the original issue]

Joining a bit late this conversation, but wouldn't it be best if we first try net461 in case there is one? For example, there is a package with a net47 and a net461 implementation. Previously we would have used the net461 one, but if we make that change I believe we will now grab the net47 one, when we know that the net461 is more likely to be compatible. Should we add some special logic for that case?

**Comment by nguerrera** [comment]
@joperezr That is a very interesting point! It could turn this into a breaking change when different assets are resolved. The whole episode of retroactively making things compatible with netstandard 1.5+, and thereby changing assets resolved with an sdk upgrade, still gives me nightmares... 

I believe we can make the default `net461;net50` to make in non-breaking, but that would still prefer net48 over net47 for example. If we want assets for "lowest version of .NET Framework that succeeds" in general, then I think we need nuget changes, and that it would be expensive to implement, but I'm not 100% sure I have the AssetTargetFallback behavior exactly right in this analysis. 

cc @rrelyea

**Comment by ericstj** [comment]
That's what I was getting at with this comment: https://github.com/dotnet/standard/issues/724#issuecomment-406638425.  IMHO one of the goals of this issue is to make the compat mapping easier to understand.  Having a tiered fallback feels more complicated.  Having an inverse fallback also feels wrong as it is counter to all other nuget behavior.

The retroactive netstandard compatibility break was a lot harder to deal with because it happened inside nuget and there was no way to undo it once someone updated nuget.  Here we have a more flexibility since this is in msbuild and property can be overridden.

**Comment by nguerrera** [comment]
We need to be much more careful about saying "you can tweak your project to get unbroken" IMHO. There are times when it's the right call, but I see us defaulting to it too often.

We can't make things easier to understand when we change the nuget graph of your app from one sdk version to another because that change is very hard to understand. This is not like adding a warning, which is at least in your face as a new behavior with an obvious remedy. It's incredibly subtle if you just start getting net47 binaries in your bin folder where previously you had net46. The break could be discovered well after the sdk upgrade.

Maybe we can make net50 the default fallback for netcoreapp2.1/netstandard2.1. If you want to get it earlier than that, then you can put net50 in your project.

cc @DustinCampbell @Pilchie

**Comment by terrajobst** [comment]
@joperezr 

That's a very good point and I'm glad you pointed this out. As @nguerrera said:

> The whole episode of retroactively making things compatible with netstandard 1.5+, and thereby changing assets resolved with an sdk upgrade, still gives me nightmares...

👍 😱 

@nguerrera 

>  If we want assets for "lowest version of .NET Framework that succeeds" in general, then I think we need nuget changes, and that it would be expensive to implement, but I'm not 100% sure I have the AssetTargetFallback behavior exactly right in this analysis.

Couldn't we just do this:

```
AssetTargetFallback = net461;net462;net47;net471;net472;net48
```

I understand that this is less ideal than implementing the actual logic, but given how often .NET Framework ships, this might be a good compromise.

Thoughts?

**Comment by joperezr** [comment]
I know that this would make the logic more complex which goes against what @ericstj would want (from what I read on this thread) but seems like setting it to that value would at least give us the behavior that we want.

**Comment by nguerrera** [comment]
I think that is a little ugly, but actually totally addresses the concern, so 👍

**Comment by terrajobst** [comment]
@livarcocc @nguerrera can we get this done for .NET Core 3.0?

**Comment by nguerrera** [comment]
@nkolev92 @jainaashish @rrelyea Do you see a problem with this proposal:

```
AssetTargetFallback = net461;net462;net47;net471;net472;net48
```

See Eric's comment just above about perf. Obviously, we can and should measure that, but do you have any concerns (perf or otherwise) from the outset?

**Comment by onovotny** [comment]
I was just bitten by this...packages updated to net472 and it broke me until I added the AssetTargetFallback.

Bump on getting this in for 3.0.

**Comment by nguerrera** [comment]
@nkolev92 @rrelyea Ping on whether you see any issues (perf or otherwise) with:

```
AssetTargetFallback = net461;net462;net47;net471;net472;net48
```

**Comment by nkolev92** [comment]
That will definitely carry a performance overhead when ATF is actually hit. I don't expect it to spiral out of control, but it will be noticeable. We'd need to investigate some more and do some testing to confirm this. 

Another concern is ATF related deficiencies in the implementation. 
https://github.com/NuGet/Home/issues/5957

**Comment by nguerrera** [comment]
cc @terrajobst. We're getting pressure to implement this by preview 4, but I'm not changing the code without NuGet's blessing.

**Comment by nguerrera** [comment]
> That will definitely carry a performance overhead when ATF is actually h

Is it proportional to where the matching TFM appears in the list or proportional to the number of TFMs regardless of which one matches?

In other words, if a package has net461 compatible assets, will there be any slow down to resolve them between AssetTargetFallback=net461 and AssetTargetFallback=net461;net462;net47;net471;net472;net48 ?

**Comment by nkolev92** [comment]
It's proportional to the number of tfm until it matches.

 So the answer to the question should be no. 
`
In other words, if a package has net461 compatible assets, will there be any slow down to resolve them between AssetTargetFallback=net461 and AssetTargetFallback=net461;net462;net47;net471;net472;net48 ?
`

**Comment by nguerrera** [comment]
So it sounds like it would only slow down cases that fail today, in which case I think it is OK. How can we verify that?

**Comment by livarcocc** [comment]
I agree. Makes sense then.

**Comment by nguerrera** [comment]
> Another concern is ATF related deficiencies in the implementation. NuGet/Home#5957

Aside: Hadn't seen that before. It instantly explained https://github.com/dotnet/core-sdk/issues/78 (now closed as duplicate). :) I think we're going to see a lot of people hit this with .NET Core 3.0 bringing up classic desktop UI. It's separate, though.

**Comment by Pilchie** [comment]
Should the ordering go the other way? If an asset exists for both net48 and net461, should we actually prefer the net48 one?

**Comment by nguerrera** [comment]
@Pilchie We are keeping net461 first for compat. See whole discussion above about how suddenly getting different assets is the subtest of breaks. Recall the whole change in  what can use netstandard2.0 between nuget versions.

If we want to prefer newer over the rest, then this might as well be net461;net48. Anything lower than net48 after net48 doesn't serve any purpose. If you can't resolve for net48, you can't resolve for net472 either, etc.

It makes some sense to me to try to pick the earlier TFMs when crossing streams.

To be completely honest, though, I dislike this whole feature being implicit and having to decide what magic to use. I wish it were just explicit.

**Comment by nguerrera** [comment]
We can change it to net48 by default for new TFMs. netstandard2.1, netcoreapp3.0. 

And maybe we change netcoreapp2.0/netstandard2.0 to `net461;net48`

That would probably reduce the perf risk.

**Comment by terrajobst** [comment]
> Should the ordering go the other way? If an asset exists for both net48 and net461, should we actually prefer the net48 one?

@nguerrera already addressed the compat angle. But more importantly, the .NET Framework compat mode is best effort. If a package overs 4.6.1 and 4.8, presumably that's because it uses more features in the 4.8 binary. The 4.6.1 binary has a higher chance of working in .NET Standard compliant implementations though, which is why it still makes sense to prefer them over the later assets.

As far as the perf riks goes: assuming the perf hit only slows down error cases, then I'm OK with that, unless the result is unbearable.

**Comment by nguerrera** [comment]
Putting this in now and verifying perf.

One quirk, the warning now looks like this (all the frameworks are listed). It's correct, just a little long.

```
Package 'atf48_1 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project
```

**Comment by nkolev92** [comment]
We can improve/fix that message in the latest clients for sure. 
https://github.com/NuGet/Home/issues/8084

At the least we sohuld call out the exact version selected. 

Also I thought it was supposed to be `net461;net48`?

**Comment by nguerrera** [comment]
I don't think that was decided. My reading was that we should go with what is in the proposal unless there's a perf issue. I have tested and cannot find a perf issue. With refs to 10 packages that have only net48 assets, the full list restores in the same time as just net48 in ATF.

**Comment by nguerrera** [comment]
net461;net48 is rather random. I think it's easier to explain the feature as the earliest available asset for >= net461.
