### ISSUE TITLE
Allow `dotnet workload list --machine-readable` to work with prior SDK versions

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#24254]
Right now, the `--machine-readable` parameter for `dotnet workload list` [generates an error](https://github.com/dotnet/sdk/blob/b5affdab42a44d796dd830d6d189f0be9f107d35/src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs#L100-L104) if a previous SDK version is specified.

The VS for Mac installer needs to be able to list the workloads which were installed for a previous SDK version, in order to install the same workloads for a new SDK.  So, we should remove the code that generates the error and allow workloads to be listed for previous bands.

It would also be a good idea to audit the difference in usage between `_targetSdkVersion` and `_currentSdkFeatureBand` in the `WorkloadListCommand` class.  It's possible that there are bugs where we're using one over the other.

**Comment by marcpopMSFT** [comment]
@gourikumari is this one of the ones we determined was no longer needed for VSMac?
