### ISSUE TITLE
Confusing error message for circular project dependency

### ISSUE THREAD

**Issue by svick** [dotnet/sdk#2428]
I created a project with project reference to itself by accident. When I tried to build it, it produced a confusing error message. I think that error message should be improved.

Tor reproduce this, you can follow these steps.

```powershell
> cd (mkdir cycle)
> dotnet new console
> dotnet add reference ../cycle
> dotnet restore
C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(913,5): error MSB4006: There is a circular
dependency in the target dependency graph involving target "_GenerateRestoreProjectPathWalk".
```

I think that especially the mention of `_GenerateRestoreProjectPathWalk` should not be in the error message, since it doesn't help to the user in any way.

**Comment by dsplaisted** [comment]
This issue was moved to NuGet/Home#7162
