### ISSUE TITLE
VB console app is emitting incorrect Assembly and Module name in metadata

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#243]
Repro: New project, VB Console App (.NET Core), Build, ildasm and look at manifest:

Expected:

```
.assembly ConsoleApplicationN { ... }
.module ConsoleApplicationN.dll
```

Actual:

```
.assembly ConsoleApplicationN.dll { ... }
.module ConsoleApplication.N.dll.exe
```

This has at least two repercussions:
1. Can't load the app as a lib, e.g. Assembly.Load(new AssemblyName("ConsoleApplicationN") fails because the manifest doesn't match the file name. 
2. F5 is broken because debugger is looking for ConsoleApplicationN.dll.pdb

**Comment by srivatsn** [comment]
This is now fixed with https://github.com/dotnet/sdk/pull/652
