### ISSUE TITLE
“TargetPath” is missing from runtimeconfig.json 

### ISSUE THREAD

**Issue by v-yuwzh** [dotnet/sdk#2430]
Apex call OutputGroups interface to get the built files collection by FileNames:
OutputGroups.Item(“built”). FileNames, this method return 2 filenames:
First file name is “”, second one is “***.dll”
Obviously, first item is not expect and verify is fail. 
. We have a debug and get fileUrl By FileURLs:
OutputGroups.Item(“built”). FileURLs, then get url collection:
1)	file:///C:\school\ApexSolutions\TestCase49\Prj_ieGjvnnaZupo\bin\Debug\netcoreapp2.1\Prj_ieGjvnnaZupo.runtimeconfig.json.
2)	file:///C:\school\ApexSolutions\TestCase49\Prj_ieGjvnnaZupo\obj\Debug\netcoreapp2.1\Prj_ieGjvnnaZupo.dll.

I think first file name at first step should be “***.json”.

**Comment by livarcocc** [comment]
@nguerrera can you take a look?

**Comment by nguerrera** [comment]
Sure thing.

**Comment by nguerrera** [comment]
@davkean @rainersigwald 

There seems to be the convention for these items that:

* Identity is full path to the file in intermediate output directory
* FinalOutputPath is the full path to the item in the 
* TargetPath is relative path from intermediate/ directory (generally just file name)

Do I have that right? 

A few complications here:
 * We don't ever write runtimeconfig.json to intermediate directory, just straight to final output, but maybe we shouldn't do it that way?
 * We actually allow you to put the runtimeconfig.json anywhere (including outside output directory) by setting the property, but I doubt anyone does this in practice.

**Comment by nguerrera** [comment]
#2548 is out with the simple fix that ignores these edge cases.

**Comment by nguerrera** [comment]
Fixed by #2548
