### ISSUE TITLE
SDK 6.0.3 (6.0.201) is released, but https://aka.ms/dotnet/6.0/dotnet-sdk-linux-x64.tar.gz points to  6.0.103

### ISSUE THREAD

**Issue by zcsizmadia** [dotnet/sdk#24317]
6.0.201 is released however `curl -I -sSL https://aka.ms/dotnet/6.0/dotnet-sdk-linux-x64.tar.gz` still redirects to 6.0.103.

Similarly, `curl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version` shows `6.0.103`

The side effect of this is that dotnet-install script installs the wrong version if  not a specific version is requested. `./dotnet-install.sh --channel 6.0` installs `6.0.103`

What is the proper place to report this issue?

**Comment by zcsizmadia** [comment]
I just validated again. And it seems 2 hours after posting the ticket, the issue is resolved half way :)

1. `curl -I -sSL https://aka.ms/dotnet/6.0/dotnet-sdk-linux-x64.tar.gz` is correct and points to `6.0.201`
2. `curl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version` still returns `6.0.103`

At least dotnet-install.sh using the redirect link from the `aka.ms` link as a first try, so it will install the very latest `6.0.201`

**Comment by dcwhittaker** [comment]
We've validated that both methods resolve to return 6.0.201.
