### ISSUE TITLE
[Idea] Shorthand project reference by convention

### ISSUE THREAD

**Issue by faniereynders** [dotnet/sdk#2432]
Given the following `ItemGroup` in a project file:
```
<ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <ProjectReference Include="..\Foo\Foo.csproj" />
</ItemGroup>
```
Just like package references are resolved by ID, it would be cool to introduce a shorthand for project references. Instead of referencing a project by path, reference it by name:
```
<ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <ProjectReference Include="Foo" />
</ItemGroup>
```
The example above will try to resolve `Foo.csproj` or `Foo.fsproj` etc. from folders within the solution scope. This will allow one to specify a project reference by name instead of path.

What are your thoughts about this?

**Comment by dsplaisted** [comment]
@dotnet/msbuild Thoughts on a shorthand for project references where you don't have to specify the full relative path?

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#3575
