### ISSUE TITLE
Allow "dotnet workload update --print-download-link-only --sdk-version" to work with prior SDK versions

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#24335]
### Describe the bug
User has 6.0.100 installed. 
Updater offers 6.0.201 update.
User do not have 6.0.201  installed. 
Updater executes "dotnet workload update --print-download-link-only --sdk-version 6.0.201.

Expected Behaviour:
dotnet command from prior SDK version should able to read the workload manifest offered with  6.0.201 and list the nuget package urls from latest SDK. This allows updater to parse the urls and download the packages to cache along with 6.0.201 SDK update. 

Actual Behaviour:
"No manifests exist for SDK version 6.0.201" message is returned.

Why is this needed?
This feature is required for VS For Mac Updater to do a cross band .NET6 Workload Update without a two step process. This support avoids, updater downloading and installing the SDK 6.0.201 and then requesting for workload updates again.

**Comment by marcpopMSFT** [comment]
This appears to be broken even with the latest fix, will send mail.

**Comment by marcpopMSFT** [comment]
This should be fixed now with the later fix that went into 6.0.401 I believe.
