### ISSUE TITLE
Allow dotnet workload list to return version and checksum of packages

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#24340]
`dotnet workload list --machine-readable or dotnet workload` list do not return any versions or checksum of installed workloads. 

- This makes it hard for vs for mac installer and updater to verify if the correct versions with a given .NET6SDK is installed

- Without a checksum, updater cannot verify if a nuget package is already downloaded and can re-download the same package multiple times resulting in updater bug.

**Comment by GouriKumari** [comment]
@marcpopMSFT  @dsplaisted : This is a good to have feature with dotnet workload but not necessary for VS For Mac updater at the moment.  

Updater had a couple of improvements to workaround these issues in the last  couple of months.
1. Updater uses http ContentLength header of NetWorkload Url instead of checksums
2. An on demand install of workloads  feature was added with loading of MAUI solution, if there is any issue with VS For Mac updater workload installation, this will be fixed when solution is loaded by user from VS For Mac.

**Comment by kdubau** [comment]
Per discussion, we'll close this since we use ContentLength now and https://github.com/dotnet/sdk/pull/26362 will bring in versions information. If the version info there is insufficient, we'll open a new issue.

**Comment by kdubau** [comment]
(I don't have permission to close it, JFYI)
