### ISSUE TITLE
Allow --skip-manifest-update with dotnet update

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#24341]
Steps

- User has a workload (wasm-tools) from .NET6.0.200 installed, using VS For Mac Installer
- User re-executes the installer, .NET version included is 6.0.201 with a new update to wasm-tools. 
- VS For Mac installer uses `dotnet workload list --machine-readable` to check if workload is installed, which returns `true` since there is no version returned with `dotnet workload list`
- In this case, VS For Mac Installer UI will mark the workload as installed.

To avoid the above scenario, `dotnet workload update --skip-manifest  and  dotnet workload update --skip-manifest --from-previous-sdk` can be used.

**Comment by kdubau** [comment]
> To avoid the above scenario, dotnet workload update --skip-manifest and dotnet workload update --skip-manifest --from-previous-sdk can be used.

I understand the scenario, but am missing how that ^ solves the problem.
