### ISSUE TITLE
Add --force-english-output switch to dotnet list package

### ISSUE THREAD

**Issue by opheoHeidrich** [dotnet/sdk#24356]
### Is your feature request related to a problem? Please describe.
I am trying to use the output of dotnet for a Unit-Test, but as I am working from germany my local output (german) is different from the output on the build-server (running on english culture). I would like to force the english output for consisten parsing results.

### Describe the solution you'd like
NuGet supports the --force-english-output switch, it just needs to be forwarded.

### Additional context
As --force-english-output is checked at the start of XPlat [MainInternal](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs), all commands forwarded from dotnet to it should implement a ForwardedOption for this switch.

**Comment by baronfel** [comment]
You're right - the SDK should mirror the command line arguments that NuGet.exe itself allows.

In the meantime, have you tried setting the [DOTNET_CLI_UI_LANGUAGE](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_cli_ui_language) environment variable to `en-us` as a workaround? This variable provides a way to consistently set the UI locale for any dotnet command.
