### ISSUE TITLE
Form designer keep loading when targeting to .NET 7.0

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/sdk#24389]
### Description

When creating a Winforms .Net core application and targeting to .NET 7.0, Form designer keep loading and an error dialog pops out, WSOD page is shown after few minutes.

### Reproduction Steps

1.	Create a Winforms .NET Core application
2.	Observe Form designer that opens automatically

### Expected behavior

Forms designer can displayed successfully.

### Actual behavior

Form designer keeps loading. WSOD page is shown after few minutes.
![image](https://user-images.githubusercontent.com/54019172/157617256-1eeb38a2-0b22-4b8e-9751-e557cfba1d4e.png)
![image](https://user-images.githubusercontent.com/54019172/157615899-c4753ed2-5ec9-4887-8c71-dae084af825c.png)

### Regression?

Yes, it's a regression issue and cannot repro in 7.0.100-preview.3.22153.22.

### Configuration
.Net 7.0.100-preview.3.22159.27

### Other information

This issue also occurs in WPF project.
![image](https://user-images.githubusercontent.com/54019172/157617922-4a331f7f-208c-4a8e-a509-0f5cbb8eddb8.png)

**Comment by dreddy-work** [comment]
This is currently blocking both WinForms and WPF.

**Comment by dreddy-work** [comment]
expected runtimeconfig.json should have following content

{
  "runtimeOptions": {
    "tfm": "net7.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "7.0.0-preview.3.22151.6"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "7.0.0-preview.3.22128.8"
      }
    ],
    "additionalProbingPaths": [
      "C:\\Users\\dreddy\\.dotnet\\store\\|arch|\\|tfm|",
      "C:\\Users\\dreddy\\.nuget\\packages",
      "C:\\temp\\fallback"
    ],
    "configProperties": {
      "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true
    }
  }
}

**Comment by marcpopMSFT** [comment]
The current installer build is incoherent as runtime is blocked: https://github.com/dotnet/installer/pull/13376

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 SDK build 7.0.100-preview.4.22173.7 from main branch: https://github.com/dotnet/installer, it is fixed: form designer can be loaded successfully, build and run app successfully.
![image](https://user-images.githubusercontent.com/26474449/159835645-027e4afd-4db7-449a-a4f7-c816cec66786.png)
