### ISSUE TITLE
error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized when doing source building package for Ubuntu Jammy 22.04

### ISSUE THREAD

**Issue by mirespace** [dotnet/sdk#24425]
Hi,

I'm packaging dotNet for Ubuntu 22.04. trying to build .Net 6 from source using sbuild in Ubuntu to generate deb packages. The tarball used by sbuild was builder with boostrap (./build.sh /p:ArcadeBuildTarball=true /p:TarballDir=../dotnet6-6.0.102 ; ./prep.sh --bootstrap ) , tag v6.0.103-source-build.

I'm finding the title's error, relationed portion of the log is:

> Build:
[10:54:38.59] Building 'runtime in tarball'
Running command:
/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663//build.sh  --ci --configuration Release --restore --build --pack --publish -bl /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath="/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props" /p:AdditionalSourceBuiltNupkgCacheDir="/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/blob-feed/packages/" /p:ReferencePackageNupkgCacheDir="/<<PKGBUILDDIR>>/packages/reference/packages/" /p:PreviouslySourceBuiltNupkgCacheDir="/<<PKGBUILDDIR>>/packages/previously-source-built/" /p:TargetRid=ubuntu.22.04-x64 /p:SourceBuildNonPortable=true  /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props /p:DotNetRestoreSourcePropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/RestoreSources.props /p:DotNetBuildOffline=true
Log: /<<PKGBUILDDIR>>/artifacts/logs/runtime.log
With Environment Variables:
DotNetBuildFromSource=true
DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props
DotNetRestorePackagesPath=/<<PKGBUILDDIR>>/packages/restored/
DotNetBuildOffline=true
AddDotnetfeedProjectSource=false
DOTNET_INSTALL_DIR=/<<PKGBUILDDIR>>/.dotnet/
DOTNET_PATH=/<<PKGBUILDDIR>>/.dotnet/
DOTNET_HOST_PATH=/<<PKGBUILDDIR>>/.dotnet/dotnet
_InitializeDotNetCli=/<<PKGBUILDDIR>>/.dotnet/
_DotNetInstallDir=/<<PKGBUILDDIR>>/.dotnet/
_InitializeToolset=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
_OverrideArcadeInitializeBuildToolFramework=net6.0
DotNetUseShippingVersions=true
PreReleaseVersionLabel=
PackageVersionStamp=
PB_VersionStamp=
ContinuousIntegrationBuild=true
MSBUILDDISABLENODEREUSE=1
OfficialBuildId=20220314.1
BUILD_BUILDNUMBER=20220314.1
GitCommitCount=
GitCommitHash=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
GitInfoCommitHash=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
SourceRevisionId=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
RepositoryCommit=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
COMMIT_SHA=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
GIT_COMMIT=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
RepositoryType=Git
DeterministicSourcePaths=true
SourceRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/
BuildInParallel=false
LatestCommit=c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
SOURCE_BUILT_SDK_ID_ARCADE=Microsoft.DotNet.Arcade.Sdk
SOURCE_BUILT_SDK_ID_ARCADE_PACKAGING=Microsoft.DotNet.Build.Tasks.Packaging
SOURCE_BUILT_SDK_ID_ARCADE_TGT_FX_SDK=Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk
SOURCE_BUILT_SDK_ID_ARCADE_SHARED_FX_SDK=Microsoft.DotNet.SharedFramework.Sdk
SOURCE_BUILT_SDK_VERSION_ARCADE=6.0.0-beta.22107.2
SOURCE_BUILT_SDK_VERSION_ARCADE_PACKAGING=6.0.0-beta.22107.2
SOURCE_BUILT_SDK_VERSION_ARCADE_TGT_FX_SDK=6.0.0-beta.22107.2
SOURCE_BUILT_SDK_VERSION_ARCADE_SHARED_FX_SDK=6.0.0-beta.22107.2
SOURCE_BUILT_SDK_DIR_ARCADE=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/
SOURCE_BUILT_SDK_DIR_ARCADE_PACKAGING=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.Packaging/
SOURCE_BUILT_SDK_DIR_ARCADE_TGT_FX_SDK=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/
SOURCE_BUILT_SDK_DIR_ARCADE_SHARED_FX_SDK=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.SharedFramework.Sdk/
RepoBuild:
/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663//build.sh  --ci --configuration Release --restore --build --pack --publish -bl /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath="/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props" /p:AdditionalSourceBuiltNupkgCacheDir="/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/blob-feed/packages/" /p:ReferencePackageNupkgCacheDir="/<<PKGBUILDDIR>>/packages/reference/packages/" /p:PreviouslySourceBuiltNupkgCacheDir="/<<PKGBUILDDIR>>/packages/previously-source-built/" /p:TargetRid=ubuntu.22.04-x64 /p:SourceBuildNonPortable=true  /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props /p:DotNetRestoreSourcePropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/RestoreSources.props /p:DotNetBuildOffline=true
__DistroRid: linux-x64
##vso[task.setvariable variable=Artifacts;isSecret=false;isOutput=true]/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts
##vso[task.setvariable variable=Artifacts.Toolset;isSecret=false;isOutput=true]/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/toolset
##vso[task.setvariable variable=Artifacts.Log;isSecret=false;isOutput=true]/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/log/Release
##vso[task.setvariable variable=Temp;isSecret=false;isOutput=true]/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/tmp/Release
##vso[task.setvariable variable=TMP;isSecret=false;isOutput=true]/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/tmp/Release
##vso[task.setvariable variable=NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS;isSecret=false;isOutput=true]20
##vso[task.setvariable variable=NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS;isSecret=false;isOutput=true]20
##vso[task.setvariable variable=NUGET_ENABLE_EXPERIMENTAL_HTTP_RETRY;isSecret=false;isOutput=true]true
##vso[task.setvariable variable=NUGET_EXPERIMENTAL_MAX_NETWORK_TRY_COUNT;isSecret=false;isOutput=true]6
##vso[task.setvariable variable=NUGET_EXPERIMENTAL_NETWORK_RETRY_DELAY_MILLISECONDS;isSecret=false;isOutput=true]1000
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/MSBuild.dll /nologo -logger:/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/net6.0/Microsoft.DotNet.ArcadeLogging.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/log/Release/Build.binlog /clp:Summary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:Configuration=Release /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663// /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=true /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=true /p:TargetArchitecture=x64 /p:BuildArchitecture=x64 /p:CMakeArgs= /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props /p:AdditionalSourceBuiltNupkgCacheDir=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/blob-feed/packages/ /p:ReferencePackageNupkgCacheDir=/<<PKGBUILDDIR>>/packages/reference/packages/ /p:PreviouslySourceBuiltNupkgCacheDir=/<<PKGBUILDDIR>>/packages/previously-source-built/ /p:TargetRid=ubuntu.22.04-x64 /p:SourceBuildNonPortable=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props /p:DotNetRestoreSourcePropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/RestoreSources.props /p:DotNetBuildOffline=true /warnaserror /<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
__DistroRid: linux-x64
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/sourcebuild.binlog /clp:Summary /nr:false /p:TreatWarningsAsErrors=false /p:ContinuousIntegrationBuild=false /p:Configuration=Release /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src// /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:BuildAllConfigurations=true /p:TargetArchitecture=x64 /p:BuildArchitecture=x64 /p:CMakeArgs= /p:MicrosoftNetFrameworkReferenceAssembliesVersion=1.0.2 /p:PackageRid=ubuntu.22.04-x64 /p:NoPgoOptimize=true /p:KeepNativeSymbols=true /p:RuntimeOS=ubuntu.22.04 /p:PortableBuild=false /p:BuildDebPackage=false /p:ArcadeInnerBuildFromSource=true /p:DotNetBuildFromSource=true /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/ /p:ArtifactsDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/ /p:ContinuousIntegrationBuild=true /p:SourceBuildOutputDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/ /p:SourceBuiltBlobFeedDir= /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false /p:DeterministicSourcePaths=false /p:DotNetBuildOffline=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props /<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj
Determining projects to restore...
Restored /<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj (in 1.14 sec).
[SourceBuiltSdkResolver] Looking for SDK Microsoft.Build.Traversal. Detected config(s) in env:
'ARCADE_TGT_FX_SDK' for 'Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/'
'ARCADE_SHARED_FX_SDK' for 'Microsoft.DotNet.SharedFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.SharedFramework.Sdk/'
'ARCADE' for 'Microsoft.DotNet.Arcade.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/'
'ARCADE_PACKAGING' for 'Microsoft.DotNet.Build.Tasks.Packaging/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.Packaging/'
[SourceBuiltSdkResolver] Looking for SDK Microsoft.NET.Sdk. Detected config(s) in env:
'ARCADE_TGT_FX_SDK' for 'Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/'
'ARCADE_SHARED_FX_SDK' for 'Microsoft.DotNet.SharedFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.SharedFramework.Sdk/'
'ARCADE' for 'Microsoft.DotNet.Arcade.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/'
'ARCADE_PACKAGING' for 'Microsoft.DotNet.Build.Tasks.Packaging/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.Packaging/'
[SourceBuiltSdkResolver] Looking for SDK Microsoft.DotNet.Arcade.Sdk. Detected config(s) in env:
'ARCADE_TGT_FX_SDK' for 'Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/'
'ARCADE_SHARED_FX_SDK' for 'Microsoft.DotNet.SharedFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.SharedFramework.Sdk/'
'ARCADE' for 'Microsoft.DotNet.Arcade.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/'
'ARCADE_PACKAGING' for 'Microsoft.DotNet.Build.Tasks.Packaging/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.Packaging/'
[SourceBuiltSdkResolver] Overriding Microsoft.DotNet.Arcade.Sdk with 'ARCADE'
[SourceBuiltSdkResolver] Looking for SDK Microsoft.NET.ILLink.Tasks. Detected config(s) in env:
'ARCADE_TGT_FX_SDK' for 'Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/'
'ARCADE_SHARED_FX_SDK' for 'Microsoft.DotNet.SharedFramework.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.SharedFramework.Sdk/'
'ARCADE' for 'Microsoft.DotNet.Arcade.Sdk/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/'
'ARCADE_PACKAGING' for 'Microsoft.DotNet.Build.Tasks.Packaging/6.0.0-beta.22107.2' at '/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Build.Tasks.Packaging/'
Determining projects to restore...
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
Build FAILED.
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.22.04-x64' is not recognized. [/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/Build.proj]
    0 Warning(s)
    4 Error(s)
Time Elapsed 00:00:09.44
Build failed with exit code 1. Check errors above.
/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcadeBuild.targets(194,5): error MSB3073: The command "./build.sh  --arch x64 --configuration Release --allconfigurations --verbosity minimal --nodereuse false --warnAsError false /p:MicrosoftNetFrameworkReferenceAssembliesVersion=1.0.2 /p:PackageRid=ubuntu.22.04-x64 /p:NoPgoOptimize=true /p:KeepNativeSymbols=true /p:RuntimeOS=ubuntu.22.04 /p:PortableBuild=false /p:BuildDebPackage=false /p:ArcadeInnerBuildFromSource=true /p:DotNetBuildFromSource=true /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/ /p:ArtifactsDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/ /bl:/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/sourcebuild.binlog /p:ContinuousIntegrationBuild=true /p:SourceBuildOutputDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/ /p:SourceBuiltBlobFeedDir= /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false /p:DeterministicSourcePaths=false /p:DotNetBuildOffline=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props" exited with code 1. [/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##vso[task.logissue type=error;sourcepath=/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcadeBuild.targets;linenumber=194;columnnumber=5;code=MSB3073;]The command "./build.sh  --arch x64 --configuration Release --allconfigurations --verbosity minimal --nodereuse false --warnAsError false /p:MicrosoftNetFrameworkReferenceAssembliesVersion=1.0.2 /p:PackageRid=ubuntu.22.04-x64 /p:NoPgoOptimize=true /p:KeepNativeSymbols=true /p:RuntimeOS=ubuntu.22.04 /p:PortableBuild=false /p:BuildDebPackage=false /p:ArcadeInnerBuildFromSource=true /p:DotNetBuildFromSource=true /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/ /p:ArtifactsDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/ /bl:/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/sourcebuild.binlog /p:ContinuousIntegrationBuild=true /p:SourceBuildOutputDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/ /p:SourceBuiltBlobFeedDir= /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false /p:DeterministicSourcePaths=false /p:DotNetBuildOffline=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props" exited with code 1.
Build FAILED.
/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuild/SourceBuildArcadeBuild.targets(194,5): error MSB3073: The command "./build.sh  --arch x64 --configuration Release --allconfigurations --verbosity minimal --nodereuse false --warnAsError false /p:MicrosoftNetFrameworkReferenceAssembliesVersion=1.0.2 /p:PackageRid=ubuntu.22.04-x64 /p:NoPgoOptimize=true /p:KeepNativeSymbols=true /p:RuntimeOS=ubuntu.22.04 /p:PortableBuild=false /p:BuildDebPackage=false /p:ArcadeInnerBuildFromSource=true /p:DotNetBuildFromSource=true /p:RepoRoot=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/ /p:ArtifactsDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/ /bl:/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/sourcebuild.binlog /p:ContinuousIntegrationBuild=true /p:SourceBuildOutputDir=/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/ /p:SourceBuiltBlobFeedDir= /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false /p:DeterministicSourcePaths=false /p:DotNetBuildOffline=true /p:DotNetPackageVersionPropsPath=/<<PKGBUILDDIR>>/artifacts/obj/x64/Release/PackageVersions.props" exited with code 1. [/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
0 Warning(s)
1 Error(s)

As I got a successful built on 20.04, comparing both (apart from the ubuntu.20.04-x64 versus ubuntu.22.04-x64 targetRid and PackageRid)  I see in the attempt for 22.04 `__DistroRid: linux-x64` and in 20.04 appears this also `__DistroRid: ubuntu.20.04-x64`.

Also, I checked into the source code the references to 20.04 and maybe other changes on other repos has to be done as well:
![Not22 04](https://user-images.githubusercontent.com/35487509/158813660-6ba26cc8-cafe-491d-8614-aab65f35fbdc.png)

but I reported here as the error I see is a NETSDK error type (sorry if this can be reported somewhere else more general). 

Could you please take a look at this? I can't advance with the packaging due to this.

Thanks a lot!

Miriam

**Comment by marcpopMSFT** [comment]
Closing since the runtime issue is merged.
