### ISSUE TITLE
global.json version mismatch warning is not actionable

### ISSUE THREAD

**Issue by sharwell** [dotnet/sdk#24429]
Today I opened dotnet/roslyn@3ffd52c976d63f6a0464f934d1dce7e961db95ec and received the following:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1408396/158850859-7cc37dc9-c4ea-4aae-ab1a-8226bc19d673.png)

This warning is problematic for the following reasons:

1. The warning does not tell the user which version of the .NET SDK is needed
2. The warning does not tell the user where to get that version of the .NET SDK
3. Despite listing an explicit version of the .NET SDK in **global.json**, the IDE fails to automatically obtain and use this version

This bug makes "clone and go" configuration for a user-friendly open source repository impossible.

**Comment by CyrusNajmabadi** [comment]
Getting this as well. :(

**Comment by richlander** [comment]
This looks like a dupe of https://github.com/dotnet/sdk/issues/24480. Can we close this one?

**Comment by sharwell** [comment]
@richlander Looks like this one is the OG 😄

**Comment by sharwell** [comment]
Duplicate of #24480

**Comment by richlander** [comment]
Thanks, Sam. The other one seems to have more action on it. Thanks for filing this issue. It remains part of the "evidence" that we have a problem.
