### ISSUE TITLE
runtimesettings.dev.json is gone ; surprising breakage

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/sdk#24427]
### Describe the bug

runtimesettings.dev.json is gone: can't detect running from the dev output directory (as opposed to publish) and can't find location of nuget stores at runtime

### To Reproduce

Build any executable project ; check for bin\Debug\net6.0\%PROJECT%.runtimesettings.dev.json

### Exceptions (if any)

Throws Missing RID win10-x64; but that's a complete red herring.

What's actually going on is in development, the transitive dependencies of the reflection-load binaries aren't copied to the build output directory (as it should be). At runtime, trying to load them with reflection does not work because their dependencies can't be loaded because the location of the nuget stores has not been set because runtimesettings.dev.json is missing.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/issues/16818

Is setting GenerateRuntimeConfigDevFile to true not sufficient?

**Comment by jhudsoncedaron** [comment]
@marcpopMSFT : Indeed it does work placing that property alone, but I'm convinced I'm in straight up undocumented territory that way. All I got in a search was one stackoverflow <A HREF="https://stackoverflow.com/questions/69810056/how-to-get-rid-of-appname-runtimeconfig-dev-json-files-in-release-for-net-5">post</A> and links into Microsoft.NET.Sdk.targets itself.

**Comment by marcpopMSFT** [comment]
I went ahead and filed a breaking change issue in our docs repo so hopefully we can get that added to the breaking change list. Thanks for noticing the missing documentation and sorry about that. We typically label issues/PRs for breaking change notices but missed this one: https://github.com/dotnet/docs/issues/28810

**Comment by jhudsoncedaron** [comment]
@marcpopMSFT : Ok, so there's the documentation issue with this pathway becoming a properly documented pathway. I'm going to close this now.
