### ISSUE TITLE
`dotnet sdk update` support

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#24461]
### Is your feature request related to a problem? Please describe.

Currently, we had the `dotnet sdk check` command for checking if there's update, could we add support for `dotnet sdk update` support to update to the latest sdk, it could reduce the complexity for updating the sdk

### Describe the solution you'd like

Add a new command `dotnet sdk update`, update the sdk automatically if there's update available.

**Comment by marcpopMSFT** [comment]
Good suggestion. This is actually already part of our planned work for the future though the work is not yet planned. We'll update this item with more details as we get further along in the planning process: https://github.com/dotnet/sdk/issues/23376
