### ISSUE TITLE
Opt out of sending telemetry data by default for non-Microsoft builds

### ISSUE THREAD

**Issue by omajid** [dotnet/sdk#24474]
### Is your feature request related to a problem? Please describe.

.NET is now being built from source by a number of distributors. For example, it's built from source and packaged by [Alpine Linux](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/dotnet6-runtime), [Arch Linux](https://archlinux.org/packages/community/x86_64/dotnet-runtime/), [Fedora](https://koji.fedoraproject.org/koji/buildinfo?buildID=1932561) as well as [Homebrew for macOS and Linux](https://formulae.brew.sh/formula/dotnet).

A large number of these distributors are carrying local patches to disable telemetry by default, and make it an opt-in experience for users. [Example 1](https://src.fedoraproject.org/rpms/dotnet6.0/blob/rawhide/f/sdk-telemetry-optout.patch). [Example 2](https://github.com/archlinux/svntogit-community/blob/packages/dotnet-core/trunk/dotnet-core-sdk-telemetry-optout.patch). If there's any underlying change in telemetry, all of these consumers will have to find a separate fix and then merge that in.

The way telemetry is set up right now, the data is only sent to Microsoft. It doesn't seem like anyone in the community would benefit from this (aside from the benefits of sharing this data with Microsoft to inform Microsoft's decision making, planning and resource allocation).

### Describe the solution you'd like

Would it be possible to switch this model around? That is, anyone building from source gets a build of .NET where telemetry is opt-in. Microsoft (or anyone else for that matter) could set some sort of build flag to get telemetry to be opt-out again.

Alternatively, could there be a single build-time switch (preferably exposed via a source-build build flag) to make the telemetry behaviour opt-in again?

### Additional context

We could stick to the status quo, but it makes us look slightly bad compared to other open source projects that keep telemetry off or make it opt-in. It also makes the lives of .NET community maintainers harder since they each have to figure out how to deal with telemetry.

Related:
- https://github.com/dotnet/sdk/issues/14556

**Comment by richlander** [comment]
Thanks for taking the time to describe this request in so much detail. We didn't have all that context. It makes sense. Let's do it.

Feel free to start a PR or we can.

**Comment by omajid** [comment]
IIRC @tmds wrote up the Fedora/RHEL/CentOS patch: https://git.centos.org/rpms/dotnet/blob/c8s/f/SOURCES/cli-telemetry-optout.patch

IIRC @alucryd wrote up the Arch Linux patch: https://github.com/archlinux/svntogit-community/blob/packages/dotnet-core/trunk/dotnet-core-sdk-telemetry-optout.patch

would one of you be interested in cleaning it up (if needed) and posting it as a PR against the `main` branch?

**Comment by tmds** [comment]
These patches introduce the desired behavior on our end. To add it to this repo, it needs to be a toggle. Some input is needed from maintainers on where to store the default value. Should it be in `Microsoft.NETCoreSdk.BundledVersions.props`? Or some other place?

**Comment by richlander** [comment]
I was thinking we'd handle this via conditional compilation, in C#, and not need to interact with MSBuild. Fair?

**Comment by baronfel** [comment]
@richlander what are you thinking here? Conditional compilation would require some defines in the csproj, so either way we're into MSBuild territory, no?

**Comment by richlander** [comment]
I don't see why. The current patches (that Omair shared) are not in MSBuild/CSProj. Right?

**Comment by jkotas** [comment]
> The current patches (that Omair shared) are not in MSBuild/CSProj. Right?

These patches are hardcoded to disable the telemetry by default. We do not want to hardcode the default in upstream. Instead, we want to be able to control the default using a switch that gets passed to the repo `build.sh`. We need to figure out how to propagate the value of `build.sh`/`build.cmd` switch to the .cs file.

The simplest option that I can think of is to enable the telemetry by default by passing `/p:DefineConstants=ENABLE_MICROSOFT_TELEMETRY` to `build.sh` and then use `ENABLE_MICROSOFT_TELEMETRY` for the conditional compilation of the default value in .cs file. @baronfel Would that work?

**Comment by richlander** [comment]
> These patches are hardcoded to disable the telemetry by default. We do not want to hardcode the default in upstream.

Right. I just meant that we could invert the polarity of the behavior, still all in that same file. I think your point might be that relying on an ENVs for that purpose is bad (which I agree with now that I think about it). We need to disable telemetry at a much more basic level.
