### ISSUE TITLE
Multiple framework target and binding redirect problem

### ISSUE THREAD

**Issue by bobuva** [dotnet/sdk#2451]
Please let me know if this is not the right place for this type of issue.

### Description
* Multiple-targeted DLL for `net472` and `netstandard2.0`
* The .NET Framework version of the dll is put in the GAC. It has to be since it is called from code that I injected into other assemblies via the .NET Profiler API.
* After building (either in VS or msbuild command line), there is a `System.Interactive.Async.dll` in the binaries directory (e.g., `bin\debug\net471`). It is the `3.0.3000.0` version.
* I then go through my automated steps to install my assemblies into a folder from which I add all of them to the GAC (this is just for the `net471` , not the `netcore2.1`, target).
* I reset IIS, then run a .NET Framework-based web application (it was built against .NET Framework 4.6.1)
* My profiler instruments the app, and when there is a call to my assembly, an exception occurs:

```
Exception Could not load file or assembly 'System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
```

* Notice that it is *not* the same version as the one that was in my `net471` binaries folder.

* I discovered that `Grpc.Core`, one of my dependent assemblies, relies on version `3.0.1000.0` of `System.Interactive.Async`. 

* I've tried adding a binding redirect both from `3.0.1000.0` to `3.0.3000.0` (and the other way, from `3.0.3000.0` to `3.0.1000.0`) in my assembly's `app.config`. But it doesn't seem to work. 

* I even tried putting the binding redirect in a file named `Grpc.Core.dll.config` in the same directory as the dlls (not in the GAC though), but that didn't help.

* Finally, I have no idea why the newer version of `System.Interactive.Async.dll` is even being put in my `net471` binaries folder. I walked through all of the assemblies I include in ILSpy and none of them pull that in. 

Any help deciphering what is going on would be fantastic. Thanks in advance!

Bob

**Comment by livarcocc** [comment]
Does this happen if you don't multi-target or if you use a non-sdk based project?

**Comment by bobuva** [comment]
I was originally just targeting `netstandard2.0` and it was happening. I'm not sure what you mean by a `non-sdk based project`.

**Comment by livarcocc** [comment]
I mean VS -> New Project -> Windows Projects -> Class Library.

Note that this project will not work with dotnet.exe, but it will tell us if this is something that we are doing for core or if there is something else wrong here.

**Comment by bobuva** [comment]
Ok, it may take a little time to move it all into such a project, but I'll give it a try.

**Comment by livarcocc** [comment]
I see. @nguerrera can you think of an easy way for us to analyze and help with what is going on here?

**Comment by bobuva** [comment]
I've just copied all of my source files over, installed nuget packages and added dependencies. It all built. Now I just need to modify my installer script a bit to pull this one in. I'll let you know how it goes when I run it.

**Comment by bobuva** [comment]
I got the same exception:
```
Exception Could not load file or assembly 'System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
```
This is with a Windows Desktop -> Class Library project.

**Comment by bobuva** [comment]
Here's something interesting. As I said earlier, I add my assemblies to the GAC, and that includes adding `Grpc.Core.dll`. When I use ILSpy to inspect the `Grpc.Core` assembly that is in the GAC, and dbl-click on `References` and then on `System.Interactive.Async` it cannot find it! Here is the output in ILSpy:

```
// Detected Target-Framework-Id: .NETFramework,Version=v4.5

// Referenced assemblies (in metadata order):
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263
	// Assembly reference loading information:
	// There were some problems during assembly reference load, see below for more information!
	// Error: Could not find reference: System.Interactive.Async, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263

// System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// __Internal
// grpc_csharp_ext
// libc
// kernel32.dll
// libdl.so
// libSystem.dylib
// libcoreclr.so
```

Now, if I instead load the `Grpc.Core.dll` from my folder where I run my stuff, and this is the same folder from which I run `gacutil /i` to put the assembly into the GAC`, then I get a different story in ILSpy!!! When I click on `References` and then on `System.Interactive.Async, it finds the `System.Interactive.Async.dll`, namely the one with a version `3.0.3000.0`. 

I'm attaching a couple of screen shots that show this.
<img width="138" alt="grpccore_in_my_folder" src="https://user-images.githubusercontent.com/60141/43659510-1def20cc-9711-11e8-8f74-161972387aa0.PNG">
<img width="511" alt="grpccore_in_my_folder_details" src="https://user-images.githubusercontent.com/60141/43659511-1e146bc0-9711-11e8-8d53-e1c66ec6e6e9.PNG">

How weird is this!?

**Comment by bobuva** [comment]
@livarcocc @nguerrera I was wondering if you had any idea given what I posted above. There seems to have been others who ran into a problem with `Grpc.Core` and `System.Interactive.Async`: 

* In [this](https://groups.google.com/forum/#!topic/grpc-io/hDkc8KXMZMQ) thread, the problem was resolved by providing assembly redirection instructions in the `AssemblyInfo.cs` for a VSIX package. But he was able to rely on the fact that he was writing an extension to Visual Studio, so he could reference `ProvideBindingRedirection` in `Microsoft.VisualStudio.Shell`. In my case, the .NET app could be anything, so this isn't a solution.

* [Here](https://github.com/grpc/grpc/issues/16244) is an issue that I created in the Grpc repository to see if I can get any traction on this from their end. My issue refers to some other issues that Jon Skeet was involved in that might be worth reading.

**Comment by nguerrera** [comment]
This looks like the usual .NET Framework issue of requiring binding redirects because there's a mix of assembly versions referenced (in this case System.Interactive.Async.

If you want this redirect to happen for any app on the machine, there are ways to do that documented here: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

Namely, publisher policy and machine.config.

**Comment by bobuva** [comment]
I've tried using binding redirect, as shown here for my framework dll:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="System.Interactive.Async"
                          publicKeyToken="94bc3704cddfc263"
                          culture="neutral" />
          <bindingRedirect oldVersion="0.0.0.0-3.0.3000.0"
                           newVersion="3.2.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

In the most recent test, I added the `3.2.0.0` version of the `System.Interactive.Async` package to my dll. But even with that, `Grpc.Core` ignores it completely. Seems very odd that it doesn't work. Are you saying that 'yeah it might not work' and I should make the change in `machine.config`? That seems a little drastic given that I would have to do that on my customers' machines.

**Comment by nguerrera** [comment]
You can't add binding redirects with a config file for a dll. It will either be in the the app config, publisher policy, or machine config. 

I agree machine.config drastic. On some level the requirements are drastic:  "the .NET app could be anything", "my profiler instruments the app". Another approach would be for your instrumentation to wire a handler to AppDomain.CurrentDomain.AssemblyResolve. This will at least only affect apps that are instrumented, but beware that there can be competing assembly resolve events called in order of their registration, so that is not risk free either.

This is one of the big pain points of .NET framework when there are version conflicts in the assembly reference graph. The usual way around it is for apps to see the conflicts in their graph at build time and msbuild can generate binding redirects based on that. But here you're hijacking the graph of arbitrary apps.

**Comment by bobuva** [comment]
Ok, thanks. I may look into the AssemblyResolve option you mentioned but I know that's a bear. Well, thanks for thinking about this. If I come up with something I'll post it.

**Comment by Green7** [comment]
I have this same problem. AssemblyResolve works:

```
    AppDomain.CurrentDomain.AssemblyResolve += EmbeddedAssemblyResolver;

    private static Assembly EmbeddedAssemblyResolver(object sender, ResolveEventArgs args)
    {
      if (args.Name.StartsWith("System.Interactive.Async"))
      {
        return Assembly.LoadFile(AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "System.Interactive.Async.dll");
      }
      return null;
    }
```
