### ISSUE TITLE
Ability to view System.Diagnostics.Process memory usage and cpu time after exit

### ISSUE THREAD

**Issue by kjpgit** [dotnet/sdk#24531]
I am trying to launch and supervise 100s of (non-dotnet) concurrent processes on linux and record their CPU time (user+system) and peak memory usage.

### Describe the solution you'd like
```
    await process.WaitForExitAsync();
    Console.WriteLine($"  User processor time       : {process.UserProcessorTime}");
    Console.WriteLine($"  Privileged processor time : {process.PrivilegedProcessorTime}");
    Console.WriteLine($"  Total processor time      : {process.TotalProcessorTime}");
    Console.WriteLine($"  Max memory size         : {process.PeakWorkingSet64}");
```
Those can be captured via `wait4()` and similar, getting the "struct rusage" of the process.  

Relying on polling, [as this shows](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.peakworkingset64?view=net-6.0), is inaccurate and inefficient.

### Additional context
I will probably have to use c++ for this :(
I need to write a shim in c++ anyway to set `prctl(PR_SET_DEATHSIG, SIGKILL)` for the child processes,  because c# Process class doesn't support that either.

I realize C# isn't a systems language but these two features (seeing rusage after exit, and prctl deathsig) are fairly general quality of life features for launching processes.

**Comment by kjpgit** [comment]
This is my workaround https://gist.github.com/kjpgit/0e6d91f0b27cd31f081c62602e32e156
Native C code library, called from P/Invoke.  Also using Tmds.Libc for epoll.

**Comment by baronfel** [comment]
Hello @kjpgit, this sounds like you are requesting new APIs for the System.Diagnostics.Process namespace. Is that the case? If so, I'll transfer this issue to the dotnet/runtime repository, where those APIs live.

**Comment by kjpgit** [comment]
@baronfel  I didn't realize that was the repo to use... I can create a ticket there myself.
