### ISSUE TITLE
THIRD-PARTY-NOTICES.TXT needed for SDK repo?

### ISSUE THREAD

**Issue by leecow** [dotnet/sdk#24542]
If third-party components are used in a .NET repo, a THIRD-PARTY-NOTICES.TXT detailing any third-party source code included in final built artifacts, along with the controlling license information must be included and maintained at the root of the affected repo ([dotnet/runtime example](https://github.com/dotnet/runtime/blob/main/THIRD-PARTY-NOTICES.TXT)). 

During product build, these files are used to create a unified TPN file and included in the final installer builds ([example](https://github.com/dotnet/runtime/blob/main/src/installer/pkg/THIRD-PARTY-NOTICES.TXT)) and source-build offerings. 

Some repos will not need this notice as no third-party code is included in the final build artifacts.

Tracking issue: https://github.com/dotnet/runtime/issues/61466

**Comment by marcpopMSFT** [comment]
@leecow is the one in installer not sufficient? https://github.com/dotnet/installer/blob/8c476b58df6032c6713c69535d2679632abac9ba/THIRD-PARTY-NOTICES

**Comment by leecow** [comment]
If that already covers everything from /sdk then, yes.

**Comment by leecow** [comment]
@marcpopMSFT - can you confirm the Installer TPN covers the SDK as well? If so, I'll close this issue and make a note of it.

**Comment by marcpopMSFT** [comment]
@leecow I assumed it did but I haven't done an analysis as I don't know what other dependencies other teams might have added into the SDK. Does the SBOM provide that?

**Comment by leecow** [comment]
I don't know @mmitche , do you know if SBOM include 3rd party info?

**Comment by mmitche** [comment]
The SBOM will include some level of third party info for the installer official build pipeline (since those third party dependencies are restored in the build). But it doesn't necessarily know what is third party, what is not, what is used in the build vs. redistributed, etc.

**Comment by marcpopMSFT** [comment]
@leecow so is the ask then to look through the SBOM, compare with installer 3rd party notices, and add anything that's missing?

@mmitche where in the CI build drop is the SBOM produced?

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1693335&view=artifacts&pathAsName=false&type=publishedArtifacts

See `build_Windows_NT_Release_SBOM`

**Comment by leecow** [comment]
@marcpopMSFT, yes, that should satisfy the requirement.

**Comment by marcpopMSFT** [comment]
Analysis has been done and shared with @leecow offline for follow-up.

**Comment by leecow** [comment]
Looks like SDK is good to go. Closing this tracking issue.
