### ISSUE TITLE
Net472 projects referencing netstandard via a netstandard library not recognized as NETStandard dependent

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/sdk#24559]
### Describe the bug
In VS 2022, when a net472 WPF project depends on a netstandard library, the net472 referencing netstandard types via a reference to the library are not resolved correctly. This seems to work in VS 2019. Looking at the bin logs between the two for ResolveAssemblyReferencesDesignTime, it points to a difference in the resolution of the target ImplicitlyExpandNETStandardFacades flow in VS 2022. Are there differences in the 2022 SDK that would prevent .NET standard dependency detection in such cases?

### To Reproduce
Repro solution -
[DataContextBrokenRef.zip](https://github.com/dotnet/sdk/files/8352684/DataContextBrokenRef.zip)

The startup project DataContextBroken resolution should show differences in how the netstandard types are resolved. From VS you can also open the MainWindow.Xaml to observe exceptions. 

### Exceptions (if any)
The downstream impact of this is in VS where opening MainWindow.Xaml throws errors because VSLangProj.VSProject.References object could not find netstandard.

### Further technical details
Internal bugs are as below:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1464677
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1499566

**Comment by baronfel** [comment]
Both linked bugs have been closed as designed, so closing this one as well.
