### ISSUE TITLE
A question about System.Numerics.

### ISSUE THREAD

**Issue by CeSun** [dotnet/sdk#24574]
I don't know if I should ask this question here, I really can't find any other place to communicate.

How to get the displacement, rotation, and scale components from the Matrix4x4x4 separately, I did not find the corresponding functions from the structure of the Matrix4x4x4.
```CSharp
var scaleMat4 = Matrix4x4.CreateScale(RelativeScale);
var rotationMat4 = Matrix4x4.CreateFromQuaternion(RelativeRotation);
var translateMat4 = Matrix4x4.CreateTranslation(RelativeLocation);
var RelativeTransform = scaleMat4 * rotationMat4 * translateMat4;

var translate = RelativeTransform.Translation; // Is this correct?
```

**Comment by baronfel** [comment]
Hi @CeSun - can you open this as a Discussion on [dotnet/runtime](https://github.com/dotnet/runtime/discussions) instead?
