### ISSUE TITLE
We need "XXX.DesignTime.props" per TFM

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#246]
In the new project system, there is a handshake between projects and tooling called [project capabilities](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/about_project_capabilities.md). 

We've run into the first situation [where we need a capability](https://github.com/dotnet/sdk/issues/245) just for a specific TFM. In the past, we've always had a capability turned on regardless of TFMs.

This presents a little bit of engineering work as we do not have a targets/props file that is per TFM, today it's one file with TFM checks inside of it.  

Given we want capabilities in props - we can't do TFM checks because in the single TFM case it's hasn't been set yet.

**Comment by dsplaisted** [comment]
We've had per-TFM project capabilities for a while: https://github.com/dotnet/sdk/blob/1b04d83fe4b5b50e0cb5240c72739c99f645a4b2/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L406-L414
