### ISSUE TITLE
"https://aka.ms/sdkimplicititems" should point to updated location

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#2460]
https://aka.ms/sdkimplicititems points to https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-default-compile-items.md when it really should point to https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects.

The former doesn't talk about how to opt out of any of the default items except for Compile.

**Comment by mairaw** [comment]
@davkean is one of the owners 😄 I'm not. Go to http://aka.ms to update it.

**Comment by dsplaisted** [comment]
I've updated the target, and added @mairaw and a few others as additional owners to the link.
