### ISSUE TITLE
Bad exception when rollback file has invalid version

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#24680]
Run `dotnet workload update --from-rollback-file rollback.json` where rollback.json has the following contents:

json
```
{
    "microsoft.net.sdk.android": "31.0.300-rc.1.35/6.0.300",
    "microsoft.net.sdk.ios": "15.4.100-rc.1.104/6.0.300",
    "microsoft.net.sdk.maccatalyst": "15.4.100-rc.1.104/6.0.300",
    "microsoft.net.sdk.macos": "12.3.100-rc.1.104/6.0.300",
    "microsoft.net.sdk.maui": "6.0.300-rc.1.5299/6.0.300",
    "microsoft.net.sdk.tvos": "15.4.100-rc.1.104/6.0.300",
    "microsoft.net.workload.mono.toolchain": "6.0.0.15/6.0.100",
    "microsoft.net.workload.emscripten": "6.0.0/6.0.100"
}
```

Expected: Message that 6.0.0.15 isn't a valid version number
Actual:

> Workload update failed: Value cannot be null. (Parameter 'version')

The problem is the error handling in the `ManifestVersion` constructor.

**Comment by baronfel** [comment]
For bonus usability points it would be ideal if the _key_ that failed parsing was also mentioned in the message, for ease of use. In this case something like

```
Workload update failed: Error parsing version for workload "microsoft.net.workload.mono.toolchain": Invalid version "6.0.0.15"
```
