### ISSUE TITLE
How to let MSBuildLocator.RegisterDefaults find a local SDK installation (not on PATH)

### ISSUE THREAD

**Issue by matkoch** [dotnet/sdk#24691]
My library provides a [bootstrapping script](https://github.com/nuke-build/nuke/blob/develop/build.sh#L43-L68) that should check whether a suitable .NET SDK installation is available, if not, the appropriate version will be installed in a local directory. This should support the following scenarios:

- SDK is installed and matches
- SDK is installed, but doesn't match => install locally
- SDK is not installed => install locally

This works nicely so far, but I'm having issues integrating [MSBuildLocator](https://github.com/microsoft/MSBuildLocator). More specifically, in the third case, it [can't register MSBuild](https://github.com/nuke-build/nuke/issues/892). In my previous solution, I was calling `dotnet --info` from the subdirectory, but it all feels a bit sluggish.

I'm posting here hoping to find a better solution (and because [Kirill told me so](https://twitter.com/KirillOsenkov/status/1509676457773076496) :)).

**Comment by KalleOlaviNiemitalo** [comment]
Would it work if the script added the directory to PATH before it runs the dotnet executable?

**Comment by marcpopMSFT** [comment]
@rainersigwald , should this get moved to the msbuildlocator repo?

**Comment by rainersigwald** [comment]
Yes.

**Comment by marcpopMSFT** [comment]
Doesn't look like the mover app is working for me. Can you reopen this issue in the https://github.com/microsoft/msbuildlocator repo?
