### ISSUE TITLE
need an option for output referenced assembly files to destination directory when build or publish a .netstandard project

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/sdk#2472]
_From @jinujoseph on August 14, 2018 16:42_

_From @chenyj796 on August 9, 2018 1:20_

**Version Used**: 
Visual Studio 2017 15.7.4
**Steps to Reproduce**:

1. Create a .Net Standard project
2. Add Some NuGet package, such as Newtonsoft.Json
3. Publish the project, and will generate only a .nupkg file

**Expected Behavior**:
Output all referenced assembly files like .net core project, and a .nupkg file
**Actual Behavior**:
Only a .nupkg file. 

_Copied from original issue: dotnet/roslyn#29175_

_Copied from original issue: dotnet/roslyn-sdk#134_

**Comment by jinujoseph** [comment]
_From @sharwell on August 14, 2018 16:37_

@jinujoseph Can you move this to SDK?

**Comment by livarcocc** [comment]
@chenyj796 it is not clear to me what you are asking for here.

Running `dotnet publish` on a class library will actually publish its dll and its dependencies.

If you run `dotnet pack`, then a nupkg for the library will be produced and this nupkg will contain only the library's dll by default. And it will contain references to its dependencies in its nuspec. This is all expected.

**Comment by chenyj796** [comment]
I am writing a .netstandard class library which will used in powershell or pwsh (with import-module cmdlet).
I hope visual studio will copy all referenced assembly files to the $(outdir), so I can I upload
the whole directory to servers and execute them in .ps1 scripts.

**Comment by livarcocc** [comment]
In .net core, outdir is the build output, which contains a limited set of assemblies, given that we run against the nuget cache, during build/run time. Like I suggested above, I recommend using `dotnet publish`.
