### ISSUE TITLE
macOS arm64 vs. x64: improve PEBKAC handling

### ISSUE THREAD

**Issue by jonpryor** [dotnet/sdk#24737]
### Describe the bug

If you install the [x64 installer](https://download.visualstudio.microsoft.com/download/pr/a5e0f5da-6088-451c-a341-b751c0d418c7/9fe3a31273888fe23cbe71cac32fa35c/dotnet-sdk-6.0.201-osx-x64.pkg) on an arm64 macOS machine, the installation is *successful* -- no error message is presented -- but the installation is "wrong": `dotnet` isn't in `$PATH`.

Thus, if you follow along with the [Hello World Tutorial](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install), the "Check everything installed correctly" step fails:

```zsh
% dotnet
zsh: command not found: dotnet
```

This is a problem on my end: I installed the wrong SDK onto my machine.

The problem is that it wasn't at all obvious that the problem was on my end.

### To Reproduce

1. Obtain a macOS+arm64 device.
2. Install the dotnet x64 installer
3. Open a **Terminal.app** window, then run `dotnet`.

**Actual results**: it fails:

```zsh
% dotnet
zsh: command not found: dotnet
```

**Expected results**: one of:

 * Step (2) errors out because the host OS architecture (arm64) doesn't match the installer's architecture (x64)
 * Step (2) *warns* about the architecture mismatch *before* installing anything, *and* notes that the SDK will be installed into `/usr/local/share/dotnet/x64`
 * Previous bullet point, *and* `/usr/local/share/dotnet/x64` is added to `$PATH`, so that `dotnet` works.
 * The dotnet SDK contains universal binaries, so that there is only one macOS installer, thus preventing the possibility of my downloading the wrong architecture.

### Further technical details
- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.1.404 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment]
@jonpryor - what ended up in PATH after the install? 
@joeloff what _should_ we be setting PATH to for x64/arm64 installs on MacOS?

**Comment by joeloff** [comment]
As I recall, we give priority to the native installer that matches the machine architecture. arm64 .NET on arm64 machine will set the path, x64 on arm64 won't.

**Comment by marcpopMSFT** [comment]
I'm not sure how we can improve this. If the x64 SDK was installed, we specifically don't want to mess with the path so there's no dotnet that can be found and so no way to provide a better error. I'm open to suggestions. Maybe the installer should do a better job of warning you (not sure if OSX installers can do that).

**Comment by baronfel** [comment]
`dotnet --info` now gives a lot more information about the architecture of the SDK vs the architecture of the host, and improvements to the dotnet website might help with the sad-path we currently experience here where architecture doesn't influence which installer we choose for the user by default.

**Comment by baronfel** [comment]
In the meantime, the dotnet website (https://dotnet.microsoft.com/en-us/download) has been updated to use the standard way of communicating the host architecture (the[ Sec-CH-UA-Arch](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Arch) header) and if that header is specified provides the best option. 

![image](https://github.com/dotnet/sdk/assets/573979/4bce57b2-b7c6-4e07-8b54-c0acf8834b86)

At this time Firefox and Safari aren't supported, which is unfortunate.
