### ISSUE TITLE
NuGet reference to System.IO.Compression is added and causes a conflict

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#2474]
\\kirillo7\public\Bugs\sdk2474
1.binlog - failure case
2.binlog - success case

Open both binlogs, go to this location:
![image](https://user-images.githubusercontent.com/679326/44121250-1dae803c-9fd4-11e8-9c48-ded94ab563d5.png)

We see conflicts for System.IO.Compression in the failure case, which is not present in the success case.

Failure conflicts:
```
_ConflictPackageFiles
    C:\Users\toddgrun\.nuget\packages\system.io.compression\4.3.0\ref\net46\System.IO.Compression.dll
        ConflictItemType = Reference
    E:\dd\WTE\Main\assets\references\VS.WebTools.References\Dev16\System.IO.Compression.dll
    E:\dd\WTE\Main\assets\references\VS.WebTools.References\Dev16\System.IO.Compression.dll
    System.IO.Compression.dll
```

Success conflicts:
```
System.IO.Compression.dll
```

We see that in the failure case an additional NuGet reference is present, which creates a conflicts and results in the System.IO.Compression reference being removed altogether.

We see that the additional reference (`C:\Users\toddgrun\.nuget\packages\system.io.compression\4.3.0\ref\net46\System.IO.Compression.dll`) is coming from ResolveNuGetPackageAssets (_ReferencesFromNuGetPackages).

**Comment by KirillOsenkov** [comment]
We will need to diff these two files:

Todd’s machine:
E:\dd\WTE\Main\obj\dev16\Microsoft.VisualStudio.JSON.Package\project.assets.json

Alex’s machine:
E:\WTE\obj\dev16\Microsoft.VisualStudio.JSON.Package\project.assets.json

On Todd’s machine, there’s an extra reference to 

C:\Users\toddgrun\.nuget\packages\system.io.compression\4.3.0\ref\net46\System.IO.Compression.dll
    NuGetIsFrameworkReference = false
    NuGetPackageId = System.IO.Compression
    NuGetPackageVersion = 4.3.0
    NuGetSourceType = Package
    Private = false

@toddgrun

**Comment by nguerrera** [comment]
cc @dsplaisted

**Comment by KirillOsenkov** [comment]
Closing as it doesn't repro after clearing the NuGet cache. @ToddGrun is reporting that after clearing the NuGet cache and restoring again the file size in System.IO.Compression.dll folder changed from 111,984 to 111,992.
