### ISSUE TITLE
Linux and Mac OSX terminal input is not rendered after `Ctrl+C` is used to terminate `dotnet run` whilst calling `Console.ReadLine` or `Console.ReadKey` or `Console.Read`

### ISSUE THREAD

**Issue by xan1000** [dotnet/sdk#24740]
### Describe the bug
After terminating a program executed with `dotnet run` using `Ctrl+C` in Linux or Mac OSX the input entered into the terminal is no longer rendered - this results in the terminal becoming difficult to use and must be closed and re-opened for it to be fixed.

This issue occurred with OSX, Linux running within WSL on Windows and with Linux running natively. This issue does **not** occur running `dotnet run` on Windows.

This issue is demonstrated in the screenshots below.

**Windows-WSL-Ubuntu**

![Windows-WSL-Ubuntu](https://user-images.githubusercontent.com/39327504/162170423-3c40fd04-5b8d-475e-9127-2b7f7a57e5f4.png)

**Linux-Native-Mint**

![Linux-Native-Mint](https://user-images.githubusercontent.com/39327504/162170522-0ab8278a-5546-4166-a1f5-8d921ac3368d.png)

**Mac-OSX**

![Mac-OSX](https://user-images.githubusercontent.com/39327504/162170565-6e5965ee-c796-4d59-966d-da9191404b45.png)

The code used to demonstrate this issue is as follows.

**Program.cs**

```
Console.Write("Press enter to end the program. ");
Console.ReadLine();
```

**HelloWorld.csproj**

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

**EDIT:** I have noted that this issue only occurs when `Ctrl+C` is used to terminate `dotnet run` whilst the program is calling `Console.ReadLine` or `Console.ReadKey` or `Console.Read`.

### To Reproduce
Run a console application and terminate it with `Ctrl+C` on Linux or Mac. Then input entered into the terminal is no longer displayed.

**EDIT:** As noted in the above EDIT the issues occurs when `Ctrl+C` is used to terminate `dotnet run` whilst the program is calling `Console.ReadLine` or `Console.ReadKey` or `Console.Read`.

### Further technical details

Windows WSL Ubuntu output for `dotnet --info`:

xan@M2-PC:/mnt/c/Users/M2/Desktop/HelloWorld$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

The other screenshots shown were taken from a natively running Linux Mint 20.3 and a Mac running OSX Catalina version 10.15.7.

Kind Regards, Matthew

**Comment by KalleOlaviNiemitalo** [comment]
If you run `stty sane`, does that make the tty echo the input again?

**Comment by xan1000** [comment]
@KalleOlaviNiemitalo Yes, running `stty sane` fixes the issue, at least on WSL. Although I suspect it fixes it for Linux native and Mac as well. 😄

**Comment by baronfel** [comment]
Interesting - `dotnet run` starts a command without `UseShellExecute`, doesn't redirect stdin/stdout/stderr, and completely stops handling any Ctrl-C at the .NET CLI layer:

```csharp
// Ignore Ctrl-C for the remainder of the command's execution
Console.CancelKeyPress += (sender, e) => { e.Cancel = true; };
```

I wonder if we're dropping something here with the way that we spawn the child process?

**Comment by baronfel** [comment]
I'm not able to repro on Ubuntu 23.10 on WSL using .NET SDK 8.0.101. I wonder if the changes to `run` in the interim have fixed this? @xan1000 please reopen if this continues to be an issue for you on more recent .NET versions.
