### ISSUE TITLE
Can not install on Ubuntu 22.04 (jammy) due to libssl1.1 dependency

### ISSUE THREAD

**Issue by emmenlau** [dotnet/sdk#24759]
### Describe the bug
Thanks a lot for providing out-of-the-box Ubuntu images, they are great! We are getting ready for Ubuntu 22.04 (jammy) that will be released in a few days, but found that the current dotnet packages can currently not be installed. It seems that the problem is due to dotnet linking `libssl1.1` whereas Ubuntu jammy now ships only `libssl3`.

Here is the error I get. It does not 
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-5.0 : Depends: libssl1.0.0 but it is not installable or
                                    libssl1.0.2 but it is not installable or
                                    libssl1.1 but it is not installable
 dotnet-sdk-5.0 : Depends: netstandard-targeting-pack-2.1 (>= 2.1.0) but it is not installable
                  Depends: dotnet-targeting-pack-5.0 (>= 5.0.0) but it is not installable
                  Depends: aspnetcore-targeting-pack-5.0 (>= 5.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### To Reproduce

 - Run Ubuntu 22.04 x86_64 current latest (for example from docker)
 - Execute `apt-get --quiet --assume-yes --no-install-recommends --purge install "dotnet-sdk-5.0" "dotnet-runtime-5.0"`

**Comment by jason-persson** [comment]
I have the same issue. I tried using the snap package of the sdk instead, but this segfaults when doing a `dotnet restore`. I'm not sure why the snap segfaults considering snap packages are meant to be self contained.

**Comment by emmenlau** [comment]
Jep, that seems to be the same issue. Should we close this one here?

**Comment by emmenlau** [comment]
> What worked for me here is to `export CLR_OPENSSL_VERSION_OVERRIDE=1.0.0`.

I guess that can work as a hack to get the package installed, but I doubt its a good idea to gamble with encryption in this way....

**Comment by sunsided** [comment]
> I guess that can work as a hack to get the package installed, but I doubt its a good idea to gamble with encryption in this way....

I mean, we're talking prerelease OS version anyways, so there's that. 🙂

It's a runtime workaround to get `dotnet restore` going; mentioned in https://github.com/dotnet/core/issues/7038#issuecomment-1080787342. The `apt` installation fails regardless, only `snap` worked for me.

**Comment by jucinaldo** [comment]
Dear, encounter the similar problem, when trying to install PHP7.4 packages, look for someone for a workaround.

sudo cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
 
Kernel 5.15.0-41-generic x86_64 GNU/Linux
PHP7.4 for install DokuWiki

sudo apt install php7.4 php7.4-fpm php7.4-cli -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.4-cli : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.4-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.4-fpm : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by danmoseley** [comment]
Maybe @bartonjs  can advise.

**Comment by emmenlau** [comment]
Dear @jucinaldo , your problem is related to PHP, while the problems in this thread are related to dotnet SDK. Even though the underlying cause may be related, nobody here can help you. You need to go to the people that compiled the version of PHP that you are trying to install. Good luck!

**Comment by feisalramar** [comment]
For all that still face the same problem

1. Go tohttp://archive.ubuntu.com/ubuntu/pool/main/o/openssl
2. find the exact version of libssl for example libssl1.1.1 
3. wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1\~18.04.20_amd64.deb
4. Then install 
5. sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1\~18.04.20_amd64.deb 

The problem should be fixed

**Comment by SMitchells** [comment]
> For all that still face the same problem
> 
> 1. Go tohttp://archive.ubuntu.com/ubuntu/pool/main/o/openssl
> 2. find the exact version of libssl for example libssl1.1.1
> 3. wget [http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1\~18.04.20_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1%5C~18.04.20_amd64.deb)
> 4. Then install
> 5. sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
> 
> The problem should be fixed

Sep 3 and 5 work best for me! 
*Only Copy and Past

**Comment by bkp31415** [comment]
> For all that still face the same problem
> 
>     1. Go tohttp://archive.ubuntu.com/ubuntu/pool/main/o/openssl
> 
>     2. find the exact version of libssl for example libssl1.1.1
> 
>     3. wget [http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1\~18.04.20_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1%5C~18.04.20_amd64.deb)
> 
>     4. Then install
> 
>     5. sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
> 
> 
> The problem should be fixed

I was facing the libssl1.1 issue when trying to install **mongo-db** in Pop!_OS 22.04 LTS (or Ubuntu 22.04 LTS). 
The above mentioned solution solved my problem.
Hope this helps others who are trying to do the same. 
Thank you @feisalramar !

**Comment by CryptoSailors** [comment]
Can't instal a node due to error
```
The following packages have unmet dependencies:
 chainflip-cli : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 chainflip-engine : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by tirelibirefe** [comment]
```
$ sudo dpkg -i libssl3_3.0.2-0ubuntu1.7_amd64.deb
Selecting previously unselected package libssl3:amd64.
(Reading database ... 112311 files and directories currently installed.)
Preparing to unpack libssl3_3.0.2-0ubuntu1.7_amd64.deb ...
Unpacking libssl3:amd64 (3.0.2-0ubuntu1.7) ...
dpkg: dependency problems prevent configuration of libssl3:amd64:
 libssl3:amd64 depends on libc6 (>= 2.34); however:
  Version of libc6:amd64 on system is 2.31-0ubuntu9.9.

dpkg: error processing package libssl3:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Errors were encountered while processing:
 libssl3:amd64
```

**Comment by yaaagy** [comment]
That should help you sail you through :)
echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
sudo apt-get update
sudo apt-get install libssl1.1

**Comment by Ahmard** [comment]
> For all that still face the same problem
> 
> 1. Go to http://archive.ubuntu.com/ubuntu/pool/main/o/openssl
> 2. find the exact version of libssl for example libssl1.1.1
> 3. wget [http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1\~18.04.20_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1%5C~18.04.20_amd64.deb)
> 4. Then install
> 5. sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
> 
> The problem should be fixed

Above deb file is missing, using "http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb" instead

**Comment by ningyile** [comment]
> > For all that still face the same problem
> > 
> > 1. Go to http://archive.ubuntu.com/ubuntu/pool/main/o/openssl
> > 2. find the exact version of libssl for example libssl1.1.1
> > 3. wget [http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb](http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1%5C~18.04.20_amd64.deb)
> > 4. Then install
> > 5. sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
> > 
> > The problem should be fixed
> 
> Above deb file is missing, use "http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb" instead

Thx! It worked! But the link of libssl1.1 has been updated.

**Comment by bobcoin98** [comment]
@feisalramar 
https://github.com/dotnet/sdk/issues/24759#issuecomment-1214190207
There is no package for arm64 arch
```
 package architecture (amd64) does not match system (arm64)
```

**Comment by feisalramar** [comment]
@bobcoin98 

I managed to find the link for arm64 

Page Link : https://launchpad.net/ubuntu/bionic/arm64/libssl-dev/1.1.0g-2ubuntu4

Package link : http://launchpadlibrarian.net/367327966/libssl-dev_1.1.0g-2ubuntu4_arm64.deb

I hope that will work for you.
Regards.

**Comment by tsiq-rickc** [comment]
> That should help you sail you through :) echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list sudo apt-get update sudo apt-get install libssl1.1

Thank you - confirmed working on Linux Mint 21.3
