### ISSUE TITLE
mac arm64 vscode unable to find path.  Unable to locate the .NET SDK. Check that it is installed and that the version specified in global.json

### ISSUE THREAD

**Issue by elminino21** [dotnet/sdk#24753]
### Describe the bug
I am able to install run, build , and create templates using the dotnet core cli. However, when using vscode I get: 
The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.
### so far
I have installed different version, 
rebooted my machine. 
I also install the brew version. 
exported the path

### Further technical details
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by baronfel** [comment]
@elminino21 DevKit should help a lot more with this kind of scenario - please reopen if you still experience installation errors in more recent .NET SDKs.
