### ISSUE TITLE
[Loc]With .NET 7 Preview 3 SDK installed on local OS, "Installation Source" is not localized after running "dotnet workload list"

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#24762]
**Environment:** .NET SDK 7.0.100-preview.3.22179.4(runtime-7.0.0-preview.3.22175.4)

**Repro steps:**
1. Set up a clean local OS machine with .NET SDK 7.0.100-preview.3.22179.4 
2. Run dotnet workload list

**Expected Result:**
Strings should be localized well.

**Actual Result:**
"Installation Source" is not localized.
SC:
![image](https://user-images.githubusercontent.com/87680983/162414404-877aa922-3757-4100-b37a-809be6e9c720.png)
DE:
![image](https://user-images.githubusercontent.com/87680983/162416992-fc03ab48-ec9a-4b11-a25d-e5fa93c260db.png)
JP:
![image](https://user-images.githubusercontent.com/87680983/162416055-10f2f36e-da54-4fa8-8aa8-9b610e354505.png)

**Note:**
Strings are localized well with .NET 6.
![image](https://user-images.githubusercontent.com/87680983/162416346-c31c7e65-94d4-4b1a-9294-e749a8c78f6d.png)

**Dotnet info:**
.NET SDK (gemäß "global.json"):
Version: 7.0.100-preview.3.22179.4
Commit: c48f2c30ee

Laufzeitumgebung:
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\tt\sdk\7.0.100-preview.3.22179.4\

Host (useful for support):
Version: 7.0.0-preview.3.22175.4
Commit: 162f83657c

.NET SDKs installed:
7.0.100-preview.3.22179.4 [C:\tt\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 7.0.0-preview.3.22178.4 [C:\tt\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0-preview.3.22175.4 [C:\tt\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 7.0.0-preview.3.22177.1 [C:\tt\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by marcpopMSFT** [comment]
.NET 7 SDK has not been localized yet and won't be for a few months. Please try this again in August or September. https://github.com/dotnet/sdk/blob/8d1e1e4f39afc2e8338933b9eb014d6a30bc7282/src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx#L132

**Comment by vdanche** [comment]
The issue is fixed on NET7 RC2 SDK-7.0.100-rc.2.22471.15
E.g SC
![image](https://user-images.githubusercontent.com/65637796/192207295-a4fa03fd-f24c-4bf7-9029-f96bdbeace8e.png)

TK
![image](https://user-images.githubusercontent.com/65637796/192207338-a888714c-7027-4914-b88e-1c7120644d7e.png)
