### ISSUE TITLE
IncludeAllContentForSelfExtract and pre-publish tasks

### ISSUE THREAD

**Issue by ALIENQuake** [dotnet/sdk#24763]
### Describe the bug
I'm trying to use IncludeAllContentForSelfExtract but I can't make it respect my custom build actions, which are required for fixing library/NuGet limitations.

1. It's a c# app using PowerShell SDK. After the build step, the library is producing a directory 'runtimes\win\lib\net7.0\Modules' inside the output directory. This is a know limitation and needs to be corrected. This directory is not part of the solution so I can't use 'CopyAllways' for them.
2. My custom after-build step moves 'Modules' directory from runtimes\win\lib\net7.0\' into $(BuildDir)  via simple xcopy cmd.
3. Then, I'm trying to Publish my app using `dotnet publish` + 'IncludeAllContentForSelfExtract'
4. Generated exe works, all files are extracted into `C:\Users\user\AppData\Local\Temp\.net\AppName\HvMvvKN+KAOI2f3u6KICq3APrz3_6Jw=\` but the extracted folder structure is without applied custom after-build step.

I've tried every After/Before Targets: 
```
AfterTargets="AfterBuild"
AfterTargets="Build"
BeforeTargets="Publish"
BeforeTargets="BeforePublish"
```
but nothing works: extracted app content is as I would run 'build' without custom fix step. It's like the `dotnet publish` action didn't include all custom build steps by default.

### Further technical details
```
dotnet --info
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   7.0.100-preview.2.22153.17
 Commit:    9c52c56c13

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.22579
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.2.22153.17\

Host (useful for support):
  Version: 7.0.0-preview.2.22152.2
  Commit:  e24f66dff0

.NET SDKs installed:
  6.0.103 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.2.22153.17 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.2.22153.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.2.22152.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.2.22153.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ALIENQuake** [comment]
@dsplaisted Hi, could you lease take a look at this? Maybe it's a limitation of dotnet publish/csproj and a new feature is needed?
Repo: https://github.com/ALIENQuake/ConsolePowerShellSDKApp
Related:
https://github.com/dotnet/sdk/issues/19322#issuecomment-1445294950
https://stackoverflow.com/questions/75570788/how-to-exclude-files-when-includeallcontentforselfextract-is-used

**Comment by dsplaisted** [comment]
@agocke @vitek-karas @joeloff Could you point to guidance on how to customize the files that are included in a single-file app?

**Comment by vitek-karas** [comment]
@VSadov @elinor-fung @sbomer (not sure who actually worked on this)

There should be a target extension point which was designed to support signing files before single-file bundling. It might be possible to tweak the input to bundling to achieve the above there.

**Comment by agocke** [comment]
I've created a PR for this docs work: https://github.com/dotnet/docs/pull/34445

**Comment by ALIENQuake** [comment]
I did it! Thanks a million for pointing me in the right direction! Even if I can't include `\`, `\\`, or `%5C` for `Contains` to make it safer, it works! @elinor-fung @VSadov @vitek-karas  Thanks for all your support, you guys are great! 

This is the 'Target' definition:
```
  <Target Name="Custom_Before_GenerateSingleFileBundle_DependsOn_PrepareForBundle" BeforeTargets="GenerateSingleFileBundle" DependsOnTargets="PrepareForBundle">
      <ItemGroup>
      <FilesToBundle 
            Remove="@(_FilesToBundle)"

            Condition=
            "
            $([System.String]::Copy(%(_FilesToBundle.RelativePath)).Contains('ref')) 
            OR
            $([System.String]::Copy(%(_FilesToBundle.RelativePath)).Contains('runtimes'))
            "
            />
    </ItemGroup>
    <Message Importance="High" Text="@(FilesToBundle)"/>
  </Target>
```
