### ISSUE TITLE
Package validation Baseline Package Validator should optionally check semantic versioning rules

### ISSUE THREAD

**Issue by PainElemental** [dotnet/sdk#24781]
When enabling Package Validation against a baseline version like this:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PackageVersion>1.0.1</PackageVersion>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>1.0.0</PackageValidationBaselineVersion>
  </PropertyGroup>
</Project>`

Validation should not only report breaking changes but (optionally) say if the new package complies to semantic versioning rules.
E.g.:
- If there are breaking changes it should recommend that major version has to be incremented.
- If there are non breaking changes it should recommend that minor version has to be incremented.

**Comment by ericstj** [comment]
cc @terrajobst @ViktorHofer @joperezr 

There is not enough information to ever recommend a smaller change than what the package is already doing.  For instance, a functional breaking change could require a major verion change even when no API is changed, or a functional (non-API) feature might require a minor change with no API change.

Something the tool could do is report what sort of changes it saw:
1. Any breaking change (supporessed or not) -> breaking changes
2. Any API addition -> feature changes
3. No API change at all -> patch/bugfix

I think it's reasonable to have an opt-in feature that enforces a minimum package version change based on these observations. Major/Minor/Patch for each respectively.

**Comment by PainElemental** [comment]
@ericstj Have a look at https://github.com/pushpay-labs/semantic-versioning-analyzer

This library actually does what I was expecting from the package validation feature

**Comment by ViktorHofer** [comment]
In the aspect of not reinventing the wheel, what speaks against continuing to use the semantic-versioning-analyzer together with the in-built package validation? The analyzer provides package version suggestions vs. package validation validates compatibility of your packaged assets.

**Comment by PainElemental** [comment]
@ViktorHofer semantic-versioning-analyzer is an external tool that needs to be called. package validation is perfectly integrated in Visual Studio.
Our current plan is to run semantic-versioning-analyzer in the build pipeline and make the build fail, if the version is not correct.
It would be cool to have a solution that is integrated in Visual Studio, so developers see that a version change is required, before the build pipeline gets triggered.

**Comment by ViktorHofer** [comment]
That sounds like a good feature request for https://github.com/pushpay-labs/semantic-versioning-analyzer. What you are asking for is achievable by adding an msbuild task and making sure that it runs after the Pack target. In your project you would then just need to add a PackageReference to that msbuild task and optionally set a few properties to control its behavior:

```
<ItemGroup>
    <PackageReference Include="SemVerAnalyzer.Task" Version="..." />
</ItemGroup>
```

**Comment by ViktorHofer** [comment]
Closing as not planned.
