### ISSUE TITLE
Download and install .Net 7.0.100-preview.4.22211.9 SDK, the global.json file not found.

### ISSUE THREAD

**Issue by v-mikedu** [dotnet/sdk#24807]
### To Reproduce
1. Download and install .NET 7.0 Preview 4 SDK from: https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
2. Run dotnet --info in command prompt.

### Actual 
![image](https://user-images.githubusercontent.com/85597901/162906396-eec3a8ba-ee6f-491f-b2eb-85b2c0dc7dc2.png)

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
Did you create a global.json file? That's not included in the SDK install by default. You can create one with `dotnet new globaljson`
