### ISSUE TITLE
[workloads] Confusing errors during installation

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/sdk#24815]
Using SDK `6.0.200` on macOS 12.3.1.

**I'm not looking for help getting past these errors. I'm simply reporting that the error messages themselves are problematic.**

I am trying to install the `macos` workload from MAUI Preview 14:

> sudo dotnet workload install macos --from-rollback-file rollback.json --ignore-failed-sources --source https://aka.ms/dotnet6/nuget/index.json --source REDACTED.json

My rollback file (based on https://maui.blob.core.windows.net/metadata/rollbacks/preview.14.json) looks like this:

```json
{
  "microsoft.net.sdk.macos":"12.1.302-preview.14.117",
  "microsoft.net.workload.mono.toolchain":"6.0.3",
  "microsoft.net.workload.emscripten":"6.0.2"
}
```

I see the following error:

> Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.2' is lower than version '6.0.1' required by manifest 'microsoft.net.workload.mono.toolchain'

This error is confusing and not exactly actionable.

1. 6.0.2 is _not_, in fact, lower than 6.0.1.
2. Even if I change my rollback file to use emscripten 6.0.1, I get the exact same error, with no indication of why installation is trying to use 6.0.2.
3. There is no feedback about what, if anything, I can do to fix the problem.

**Comment by akoeplinger** [comment]
The version numbers are switched in the message, this was fixed in https://github.com/dotnet/sdk/pull/23748
