### ISSUE TITLE
Using Central Package Management with SDK 6.0.4

### ISSUE THREAD

**Issue by MarounMaroun** [dotnet/sdk#24861]
### Describe the bug

I'm following [this post](https://devblogs.microsoft.com/nuget/introducing-central-package-management/) that introduces the Central Package Management. My current SDK version is 6.0.2, but I have the `.NETCore.App 6.0.4` listed in my runtimes.

I downloaded the 6.0.4 SDK from [this link](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), however, I can still see:

```
> dotnet --version
6.0.202
```

And looks like the central package management is still unavailable to me, since my `nuget` version is older than the expected one:

```
> dotnet nuget --version
NuGet Command Line
6.1.0.103
```

### To Reproduce

Download the new SDK and check the nuget version.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.104 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment]
I think this is expected behavior. Taking a bit from the blog post:

> The feature is available across all NuGet integrated tooling.
>
>    [Visual Studio 2022 17.2 and later](https://visualstudio.microsoft.com/downloads/)
>    [.NET SDK 6.0.300 and later](https://dotnet.microsoft.com/download/dotnet/6.0)
>    [nuget.exe 6.2.0 and later](https://www.nuget.org/downloads)

And you're on 6.0.2xx. Can you try with one of the 6.0.3xx previews (available from the dotnet/installer repository) and see if you have the same behavior?

**Comment by MarounMaroun** [comment]
@baronfel Thanks for the reply. The installed keeps installing 6.0.2 for some reason. I'm downloading from [here](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.4/6.0.4.md).
