### ISSUE TITLE
Error Installing dotnet-sdk on Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by katychou** [dotnet/sdk#24877]
$ ##  https://docs.microsoft.com/zh-tw/dotnet/core/install/linux-ubuntu#apt-troubleshooting
$ 
$ sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
(Reading database ... 233850 files and directories currently installed.)
Removing packages-microsoft-prod (1.0-ubuntu18.04.2) ...
Purging configuration files for packages-microsoft-prod (1.0-ubuntu18.04.2) ...
dpkg: error: cannot access archive 'packages-microsoft-prod.deb': No such file or directory
user01@PC01:/Data/DL_2022/python/C#$ sudo apt-get update
Hit:1 http://tw.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://tw.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                             
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                   
Hit:4 http://tw.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                           
Hit:5 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                
Get:6 https://repo.skype.com/deb stable InRelease [4502 B]                                                                                                                     
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease                                                                                                             
Hit:8 https://cli.github.com/packages bionic InRelease                                                                                                 
Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                     
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                  
Err:6 https://repo.skype.com/deb stable InRelease                                                            
  The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
Ign:11 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic InRelease      
Hit:12 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic InRelease             
Err:13 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release                  
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.skype.com/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
E: The repository 'http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
user01@PC01:/Data/DL_2022/python/C#$ sudo apt-get install -y gpg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.4-1ubuntu1.4).
The following packages were automatically installed and are no longer required:
  libdca0 libdirectfb-1.7-7 libenca0 libfaad2 libllvm7 libllvm9 libllvm9:i386 libmad0 libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440 libnvidia-compute-440:i386
  libnvidia-decode-440 libnvidia-decode-440:i386 libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-extra-440 libnvidia-fbc1-440 libnvidia-fbc1-440:i386
  libnvidia-gl-440 libnvidia-gl-440:i386 libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libopenal-data libopenal1 libsdl1.2debian libvorbisidec1 mplayer-skins
  nvidia-compute-utils-440 nvidia-dkms-440 nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-utils-440 shim xserver-xorg-video-nvidia-440
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 177 not upgraded.
user01@PC01:/Data/DL_2022/python/C#$ wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
--2022-04-15 17:18:16--  https://packages.microsoft.com/keys/microsoft.asc
Resolving packages.microsoft.com (packages.microsoft.com)... 65.52.183.205
Connecting to packages.microsoft.com (packages.microsoft.com)|65.52.183.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 983 [application/octet-stream]
Saving to: ‘STDOUT’

-                                           100%[===========================================================================================>]     983  --.-KB/s    in 0s      

2022-04-15 17:18:17 (38.7 MB/s) - written to stdout [983/983]

user01@PC01:/Data/DL_2022/python/C#$ sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
user01@PC01:/Data/DL_2022/python/C#$ wget https://packages.microsoft.com/config/ubuntu/{os-version}/prod.list
--2022-04-15 17:18:17--  https://packages.microsoft.com/config/ubuntu/%7Bos-version%7D/prod.list
Resolving packages.microsoft.com (packages.microsoft.com)... 65.52.183.205
Connecting to packages.microsoft.com (packages.microsoft.com)|65.52.183.205|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-15 17:18:17 ERROR 404: Not Found.

user01@PC01:/Data/DL_2022/python/C#$ sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
mv: cannot stat 'prod.list': No such file or directory
user01@PC01:/Data/DL_2022/python/C#$ sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
user01@PC01:/Data/DL_2022/python/C#$ sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
chown: cannot access '/etc/apt/sources.list.d/microsoft-prod.list': No such file or directory
user01@PC01:/Data/DL_2022/python/C#$ sudo apt-get update; \
>   sudo apt-get install -y apt-transport-https && \
>   sudo apt-get update && \
>   sudo apt-get install -y {dotnet-package}
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://tw.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                     
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                
Hit:4 http://tw.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                             
Hit:5 http://tw.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                           
Get:6 https://repo.skype.com/deb stable InRelease [4502 B]                                                                                                                     
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease                                                                                                             
Hit:8 https://cli.github.com/packages bionic InRelease                                                                                                                         
Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                    
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Err:6 https://repo.skype.com/deb stable InRelease                                                                          
  The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
Ign:11 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic InRelease                                          
Hit:12 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic InRelease                                        
Err:13 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release                                               
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.skype.com/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
E: The repository 'http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.6.14).
The following packages were automatically installed and are no longer required:
  libdca0 libdirectfb-1.7-7 libenca0 libfaad2 libllvm7 libllvm9 libllvm9:i386 libmad0 libnvidia-cfg1-440 libnvidia-common-440 libnvidia-compute-440 libnvidia-compute-440:i386
  libnvidia-decode-440 libnvidia-decode-440:i386 libnvidia-encode-440 libnvidia-encode-440:i386 libnvidia-extra-440 libnvidia-fbc1-440 libnvidia-fbc1-440:i386
  libnvidia-gl-440 libnvidia-gl-440:i386 libnvidia-ifr1-440 libnvidia-ifr1-440:i386 libopenal-data libopenal1 libsdl1.2debian libvorbisidec1 mplayer-skins
  nvidia-compute-utils-440 nvidia-dkms-440 nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-utils-440 shim xserver-xorg-video-nvidia-440
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 177 not upgraded.
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://tw.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                     
Hit:3 http://tw.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                             
Hit:4 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                
Hit:5 http://tw.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                           
Get:6 https://repo.skype.com/deb stable InRelease [4502 B]                                                                                                                     
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease                                                                                                             
Hit:8 https://cli.github.com/packages bionic InRelease                                                                                                                         
Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                                                
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Err:6 https://repo.skype.com/deb stable InRelease                                                                          
  The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
Ign:11 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic InRelease                                          
Hit:12 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic InRelease                                        
Err:13 http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done                                
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.skype.com/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 1F3045A5DF7587C3 Skype Linux Client Repository <se-um@microsoft.com>
E: The repository 'http://ppa.launchpad.net/kazam-team/stable-series/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
user01@PC01:/Data/DL_2022/python/C#$ dotnet info
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'info' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
user01@PC01:/Data/DL_2022/python/C#$ dotnet 

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
user01@PC01:/Data/DL_2022/python/C#$ dotnet list-sdks
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'list-sdks' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
user01@PC01:/Data/DL_2022/python/C#$ dotnet --list-runtimes
Microsoft.NETCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
user01@PC01:/Data/DL_2022/python/C#$ code --version
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
user01@PC01:/Data/DL_2022/python/C#$
user01@PC01:/Data/DL_2022/python/C#$ dotnet net console -n test01
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'net' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
user01@PC01:/Data/DL_2022/python/C#$

**Comment by katychou** [comment]
Error Installing dotnet-sdk on Ubuntu 18.04.6 LTS.
Help,thank you.

**Comment by baronfel** [comment]
I expect this was a point-in-time problem - can you try again and see if the feeds are good to go now? Please reopen if you're having problems installing still.
