### ISSUE TITLE
With .NET 6.0.105, restoring project failed on Mariner 2.0 x64

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#24875]
**Environment**
.NET 6.0.105(runtime-6.0.5)

**Steps To Reproduce**
1. Prepare Mariner 2.0 x64 in docker
2. Installed the 6.0.105 SDK using rpm installer
3. Create a new project and run restore
4. Observe

**Expected Behavior**
The project can be created successfully.

**Actual Behavior**
Restoring project failed.
![image](https://user-images.githubusercontent.com/1578239/163542039-d65a58ca-09e1-487e-ad2c-3255ef52bd39.png)

**Dotnet info**
.NET SDK (reflecting any global.json):
Version:   6.0.105
Commit:    6a6481d51e

Runtime Environment:
OS Name:     mariner
OS Version:  2.0
OS Platform: Linux
RID:         linux-x64
Base Path:   /usr/share/dotnet/sdk/6.0.105/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.105 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  [https://aka.ms/dotnet-download](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fdotnet-download&data=05%7C01%7Cv-huwang%40microsoft.com%7Cffca9d99cbdd4fe360cc08da1eac8c83%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637856023702356965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MFkoGEPpHxw1U5LwnZs%2BebOSpLYgnKRYFI2274je%2FVg%3D&reserved=0)

**Comment by mthalman** [comment]
Step 1 needs more detail. How was the container prepared? Do you have the `ca-certificates-microsoft` package installed?

**Comment by NicoleWang001** [comment]
Thanks @mthalman Dotnet restore works fine after installing ca-certificates-microsoft package, so close it.
