### ISSUE TITLE
Reference to project with Nuget packet lead to deploying packet assembly into destination folder even if set Private and CopyLocalSatelliteAssemblies.

### ISSUE THREAD

**Issue by evgeny-burmakov** [dotnet/sdk#2491]
Reference to project with Nuget packet lead to deploying packet assembly into destination folder even if set Private and CopyLocalSatelliteAssemblies. Using CopyLocalLockFileAssemblies=false not an option due to it is block all dependencies, but I need to block only some of them.

**Repro:**

Due to project specific we need to publish each project separately and deliver only direct 3rd party assemblies.
There are 2 project:
- A reference to Autofac packet
- B reference A (copy local - false)

_Expected:_
A/bin/A.dll
A/bin/Autofac.dll
B/bin/B.dll

_Actual:_
A/bin/A.dll
A/bin/Autofac.dll
B/bin/B.dll
B/bin/Autofac.dll

```
A.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.8.1"/>
  </ItemGroup>
</Project>

B.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\A\A.csproj">
      <Private>false</Private>
      <CopyLocalSatelliteAssemblies>false</CopyLocalSatelliteAssemblies>
    </ProjectReference>
  </ItemGroup>
</Project>
```

**Comment by livarcocc** [comment]
You need to set PrivateAssets="All" as a property on the PackageReference in AutoFac in project A. This means that this package won't show up on A's nuspec if you create a nupkg for it using dotnet pack.

And projects referencing it won't have it appear on their output either.

Could you try that?

**Comment by evgeny-burmakov** [comment]
I tried, but in this case project A doesn't able to access to the Autofac namespace.
My goal is deliver assembly without copying all references implicitly.

**Comment by livarcocc** [comment]
@rohit21agrawal who may know the answer here.

@evgeny-burmakov have you tried the suggestion on your other issue: excludeassets?

**Comment by evgeny-burmakov** [comment]
Another curious thing I have met with next setup:
A.dll - is netstandard 1.4 SDK style
B.dll - is net462 SDK style refer A.dll
C.dll - is net462 classic project style refer A.dll

When compile solution B.dll output directory contains System... libraries, but C.dll output doesn't.
There are compatibility assemblies which theoretically shouldn't be depended on project style. Or have I missed something?
