### ISSUE TITLE
SDK tests end up modifying the SDK manifests

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#24923]
Maui checked in a breaking change to the Maui manifests before later reverting it. Any test runs during that time failed because some test ended up updating the manifests. The SDK tests should not mess with the test sdk manifests. We should track down what test was the problematic test and change it's behavior.

https://github.com/dotnet/sdk/pull/24883 had this failure but after rerun it passed.
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Could not find workload 'tizen' extended by workload 'maui-tizen' in manifest 'microsoft.net.sdk.maui' [D:\a\work\1\s\artifacts\bin\redist\Debug\dotnet\sdk-manifests\6.0.300\microsoft.net.sdk.maui\WorkloadManifest.json]\r\n at

**Comment by nohwnd** [comment]
@marcpopMSFT I don't think this is related to dotnet test specifically. I don't know what exactly you mean by manifests, but test platform or test framework don't modify the files under test (except for instrumenting the binaries when you have code coverage enabled). Should this be rather Infrastructure or some other tag?

**Comment by marcpopMSFT** [comment]
Looks like a bad bot labeler. Sorry about that. We'll track that as this issue anyway as we figure out which tests were causing the issue (we think): https://github.com/dotnet/sdk/issues/25175

**Comment by nohwnd** [comment]
This is fine, I was just trying to say that I have no idea what to do with it, and if it stays tagged as dotnet test area then no-one else will touch it than me or my team :)
