### ISSUE TITLE
No possibility to set CopyLocal=false for nuget package referenced by PackageReference into project targeted net462

### ISSUE THREAD

**Issue by evgeny-burmakov** [dotnet/sdk#2492]
PackageReference doesn't contains possibility to set copy local = false for net462 projects.
Package assemblies always copied till it isn't blocked by private assets. But in this case transitive possibility is switched off,

With packages.config was possibility to configure it for assembly individually :
```
<Reference Include="...">
        <HintPath>...</HintPath>
        <Private>false</Private>
</Reference>
```

**Comment by livarcocc** [comment]
@rohit21agrawal @nkolev92 @dsplaisted any ideas on how to do this?

**Comment by rohit21agrawal** [comment]
wouldn't ``` ExcludeAssets=compile``` do the trick? (If i am understanding the question correctly).

**Comment by rohit21agrawal** [comment]
my bad, yes it is safe to use as long as you don't want any assemblies from the lib folder of the package to not be copied to the bin folder of your project.

**Comment by livarcocc** [comment]
Closing this issue as it seems ExcludeAssets=runtime seems to have solved the issue.
