### ISSUE TITLE
AppHost cannot embed a custom app manifest 

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#2493]
The logic in `AppHost` and its associated `CreateAppHost` MSBuild task, has no mechanism today to provide a custom application manifest file. It has a default one embedded. That means we cannot provide an external one either because [embedded manifests win over an external one](https://blogs.msdn.microsoft.com/patricka/2009/12/09/answers-to-several-application-manifest-mysteries-and-questions/). That means we have to remove the embedded one since embedded manifests in a post build step before providing our own, which is nasty.

**Comment by nguerrera** [comment]
This is fixed. We copy manifest to apphost now from managed dll.
