### ISSUE TITLE
PackageValidation with --no-build when project has ProjectReference causes NETSDK1085

### ISSUE THREAD

**Issue by canton7** [dotnet/sdk#24943]
### Describe the bug

I have two projects, A and B, where B depends on A using a `<ProjectReference Include="A.csproj"/>`.

Project B has `<EnablePackageValidation>true</EnablePackageValidation>`.

If I run `dotnet pack --no-build B.csproj`, I get the error:

> C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(136,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. [C:\Path\To\A.csproj]

It seems that package validation is trying to build the target's dependencies, which then conflicts with the `--no-build` passed to `dotnet pack`.

### To Reproduce

`A/A.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

`B/B.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../A/A.csproj"/>
  </ItemGroup>

</Project>
```

Run:

```
dotnet build B
dotnet pack --no-build B
```

### Further technical details

`dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ericstj** [comment]
That's interesting.  There must be an inconsistency between how PackageValidation gets dependencies vs Nuget.

Most likely calling `ResolveReferences` in B triggers a `Build` of A when resolving the project reference.  We should inspect what we missed copying from the Pack task to make that consistent.

It's trying to fetch references in a similar way to other targets nuget calls:
https://github.com/dotnet/sdk/blob/e8ff845afddb6e2c62b6e4caa9768de391d36cee/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets#L53-L74

Most likely calling `ResolveReferences` in B triggers a `Build` of A when resolving the project reference.  We should inspect what we missed copying from the Pack task to make that consistent.


I see that it's missing setting `BuildProjectReferences=false` like NuGet is doing here https://github.com/NuGet/NuGet.Client/blob/93bb3921490e9d499be1fb48d6cb9dcaff734db1/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L389

This is related to https://github.com/dotnet/sdk/issues/23630 we should be careful not to regress any perf when fixing this.

cc @ViktorHofer @joperezr
