### ISSUE TITLE
UAP10 class dll CopyLocalLockFileAssemblies equivalent

### ISSUE THREAD

**Issue by jmroyb** [dotnet/sdk#2496]
Hi folks,

in a netstandard project CopyLocalLockFileAssemblies copied all NuGet references in output folder.

How can I get all referenced NuGet dlls being copied in the output folder? I tried next line but did not worked. 

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

Cheers

**Comment by livarcocc** [comment]
UAP10 projects are not supported by SDK style projects. At least, not out of the box. If you are using the sdk.extras SDK with your project, I would ask this question on that SDK's repo.
