### ISSUE TITLE
CoreCLR failed to build with error NETSDK1182 with MSVC on windows amd64.

### ISSUE THREAD

**Issue by Vincent9802** [dotnet/sdk#25005]
Hi All,

Environment:
VS 2019 + Windows Server 2019

CoreCLR failed to build with error NETSDK1182 with MSVC on windows amd64. for example: error NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported. [F:\gitP\dotnet\runtime\src\tasks\WasmAppBuilder\WasmAppBuilder.csproj]. 
In the old commit, use the .net sdk version is "6.0.100-rc.1.21411.28", no problems with the project build. In the latest commit, .net sdk version is "6.0.100", even if we change version back to "6.0.100-rc.1.21411.28", there will be other version issues. 
Could you please help with this ?

**Repro steps:**
1. git clone https://github.com/dotnet/runtime.git
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
3. cd F:\gitP\dotnet\runtime
4. .\build.cmd -subset clr+libs -c release -arch x64

log: [build.zip](https://github.com/dotnet/sdk/files/8539747/build.zip)

**Error info:**
F:\gitP\dotnet\runtime\src\coreclr\tools\aot\ILCompiler\ILCompiler.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 6.0.0-rc.1.21411.2) [F:\gitP\dotnet\runtime\Build.proj]
F:\gitP\dotnet\runtime\src\coreclr\tools\aot\ILCompiler\ILCompiler.csproj : error NU1102:   - Found 970 version(s) in dotnet7 [ Nearest version: 7.0.0-alpha.1.21417.28 ] [F:\gitP\dotnet\runtime\Build.proj]
F:\gitP\dotnet\runtime\src\coreclr\tools\aot\ILCompiler\ILCompiler.csproj : error NU1102:   - Found 82 version(s) in dotnet-public [ Nearest version: 6.0.0-rc.1.21451.13 ] [F:\gitP\dotnet\runtime\Build.proj]
F:\gitP\dotnet\runtime\src\coreclr\tools\aot\ILCompiler\ILCompiler.csproj : error NU1102:   - Found 1 version(s) in dotnet-eng [ Nearest version: 5.0.0-alpha.1.19618.1 ] [F:\gitP\dotnet\runtime\Build.proj]
F:\gitP\dotnet\runtime\src\coreclr\tools\aot\ILCompiler\ILCompiler.csproj : error NU1102:   - Found 0 version(s) in richnav [F:\gitP\dotnet\runtime\Build.proj]

**Comment by danmoseley** [comment]
Can you try VS2022?

**Comment by Vincent9802** [comment]
Sorry, if there is a way to solve it, we use VS2019 more. Thanks.

**Comment by Vincent9802** [comment]
> Can you try VS2022?

Sorry, if there is a way to solve it, we use VS2019 more. Thanks.

**Comment by marcpopMSFT** [comment]
We do not support targeting net6.0 using VS 2019. Starting in 6.0.300, the SDK will not even load in VS 2019 but we allowed the 6.0.100 SDK to load in VS 2019 to give some customers time to transition.

This is included in our documentation here: https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle
