### ISSUE TITLE
Possible build time regression on empty macOS (Arm64) projects

### ISSUE THREAD

**Issue by Kopkako** [dotnet/sdk#25037]
### Describe the bug
- I was starting a new .NET 6 console project on a MacBook Pro (M1 Max, 10 Cores) via the CLI: `dotnet new console`
- When building the empty project, the build time is almost 3 seconds, but the real time it takes all in all is closer to **4-5 seconds**.
- I felt a build of a new "Hello, world" console project *should **not** take that long*, so I made a thread in the .NET subreddit about it: https://www.reddit.com/r/dotnet/comments/u6axwd/net_6_compilation_speed_on_macos_monterey_am_i/
- In this thread, `u/andyayers` (@AndyAyersMS) pointed me towards this repository, suggesting this might be a performance bug: https://www.reddit.com/r/dotnet/comments/u6axwd/net_6_compilation_speed_on_macos_monterey_am_i/i5cy23x/

### To Reproduce

- Download and install the latest .NET 6 SDK on macOS Monterey 12.3.1 (my machine is a MacBook Pro (14-inch, 2021) M1 Max)
- Create a new .NET console application via `dotnet new console`
- Build the application via `dotnet build`

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

No IDE necessary for this, but I'm using VSCode 1.66.2

**Comment by marcpopMSFT** [comment]
@richlander seen or experienced any reports of slow build times on Mac?

**Comment by richlander** [comment]
This is what I see on my machine (with a bunch of lines elided for the report).

```bash
rich@MacBook-Air ~ % dotnet new console -o test
rich@MacBook-Air ~ % cd test
rich@MacBook-Air test % time dotnet build
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.77
dotnet build  2.39s user 0.39s system 122% cpu 2.278 total
rich@MacBook-Air test % time dotnet build

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.35
dotnet build  2.16s user 0.33s system 133% cpu 1.867 total
rich@MacBook-Air test % dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

rich@MacBook-Air test % 
```

This looks better than your report. I'm on an "original" M1 MBA.

**Comment by kopkako** [comment]
@richlander @marcpopMSFT Thanks for looking into it, much appreciated!

I think I found the root cause of the issue: I downloaded the dotnet SDK via [homebrew (brew.sh)](https://formulae.brew.sh/cask/dotnet#default)

This, however, only seems to install the x86-64 version of the SDK, not the newest ARM64 version.
Thus, I would assume that my Mac uses Rosetta translation for the `dotnet build` command, explaining the slow build times.

I uninstalled the homebrew-installed SDK, and manually installed the latest SDK from the Microsoft website.

I am now getting much improved build times:
- ~3 seconds for the first build,
- between 1.2 and 1.4 seconds for subsequent builds

**Comment by richlander** [comment]
That fits. Thanks for figuring that out.

Looks like the Arm64 version is available as a formula (as opposed to a cask): https://formulae.brew.sh/formula/dotnet

/cc @asbjornu

**Comment by AndyAyersMS** [comment]
I've found it very easy to get confused on the M1 and run the "wrong" binary.

**Comment by asbjornu** [comment]
`brew install --formula dotnet` should ensure that the formula is installed and not the cask. Although I don't have an M1 Mac myself so I haven't actually tested, the `dotnet` formula should install the build for the appropriate architecture.

**Comment by kopkako** [comment]
While we're at it, what I also find very confusing is that there are three ways to install `dotnet` via brew.sh right now:

- The `dotnet` formula: https://formulae.brew.sh/formula/dotnet
- The `dotnet` cask: https://formulae.brew.sh/cask/dotnet
- The `dotnet-sdk` cask: https://formulae.brew.sh/cask/dotnet-sdk

To be honest, I don't even understand the purpose behind the `dotnet-sdk` cask, why is it there?
Would be great if this was reduced to one, correct way to install `dotnet` via homebrew, as is the case with 99% of the other things I install via brew.

**Comment by asbjornu** [comment]
I agree such a cleanup would be sensible, @kopkako. I wasn't even aware of the `dotnet-sdk` cask. The most important difference between the `dotnet` and `dotnet-sdk` casks seems to be `dotnet-runtime` vs. `dotnet-sdk`:

```diff
- url "https://download.visualstudio.microsoft.com/download/pr/#{version.csv.second}/#{version.csv.third}/dotnet-runtime-#{version.csv.first}-osx-#{arch}.pkg"
+ url "https://download.visualstudio.microsoft.com/download/pr/#{version.csv.second}/#{version.csv.third}/dotnet-sdk-#{version.csv.first}-osx-#{arch}.pkg"
```

The `dotnet` formula installs the SDK, not the runtime. As such, it's easy to argue that `dotnet-sdk` would have been a better name for the formula. Either way, we could petition for the deletion of the `dotnet-sdk` cask, since the `dotnet` formula is a source-built, and thus more portable, alternative.

**Comment by marcpopMSFT** [comment]
@rbhanda @MichaelSimons do we have any way of getting the brew versions cleaned up?

**Comment by richlander** [comment]
What do you mean @marcpopMSFT? We don't any of the brew packages. Or are you suggesting something more specific?

**Comment by marcpopMSFT** [comment]
@richlander I was wondering if we have a process for getting something like this cleaned up or do we just rely on the community to do it?

**Comment by richlander** [comment]
The latter. Folks can open an issue on the appropriate community project. 

We can close this issue now.
