### ISSUE TITLE
Process.Start() is not supported on Windows in dotnet SDK 6.0.202

### ISSUE THREAD

**Issue by linaelf** [dotnet/sdk#25063]
### Describe the bug
Process.Start() on Windows violates CA1416 as below: 
CA1416	'Process.Start(ProcessStartInfo)' is supported on 'maccatalyst'

### To Reproduce
Visual studio 17.1.5
dotnet SDK version: 6.0.202

### Further technical details
dotnet SDK 6.0.200 doesn't have this issue. But in 6.0.202 Process.start() is marked as below:
        [UnsupportedOSPlatform("ios")]
        [UnsupportedOSPlatform("tvos")]
        [SupportedOSPlatform("maccatalyst")]
        public bool Start()

Is it suggested not to use this method on Windows?

**Comment by baronfel** [comment]
Do you have a sample project, or a set of instructions to create one, that we could use to investigate the behavior you're mentioning? There's not enough to go on here to dig deeper.

**Comment by linaelf** [comment]
[ProcessTest.zip](https://github.com/dotnet/sdk/files/8577995/ProcessTest.zip)
Please check out the zip file for sample. Thanks!

**Comment by linaelf** [comment]
After I upgrade Microsoft.NetCore.Analyzers from 3.3.1 to 3.3.2, the error becomes more clear:
![image](https://user-images.githubusercontent.com/4425285/165637003-436f4597-4702-4028-b9d7-71c92e5bbc5d.png)

So it's stating that this is not supported on MacOS before maccatalyst, but supported by all other platforms, right? If so, I think I can close the issue.

**Comment by kasperk81** [comment]
you can read about this warning here: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416. you can suppress this warning in project file if you don't plan to support your assembly on maccatalyst platform

> So it's stating that this is not supported on MacOS before maccatalyst

no. mac or osx, maccatalyst, ios, tvos, watchos are different platforms: https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=net-6.0#methods

**Comment by linaelf** [comment]
Thanks for the clarification, closing now.
