### ISSUE TITLE
How to install dotnet sdk in centos ?

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/sdk#2506]
Hi

We want to install dotnet sdk 2.0.3 in centos. 

(1) Official [documentation](https://www.microsoft.com/net/download/linux-package-manager/centos/sdk-2.0.3) says to follow : 

```
Add the dotnet product feed
Before installing .NET, you'll need to register the Microsoft key, register the product repository, and install required dependencies. This only needs to be done once per machine.
Open a command prompt and run the following commands:
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
Install the .NET SDK
Update the products available for installation, then install the .NET SDK. 
In your command prompt, run the following commands: 
sudo yum update
sudo yum install libunwind libicu
sudo yum install dotnet-sdk-2.0.3
``` 

(2) There are other ways to install dotnet in centos as :
```
yum install centos-release-dotnet
yum install rh-dotnet20
```

People usually refer `(2)` method in redhat distros. So, there is some confustion.
Can you please tell if `(2)` is supported way ? 
Can we install a particular version of dotnet like 2.0.3 using `(2)` method ?

**Comment by livarcocc** [comment]
Please follow the official documentation. RedHat produces their own distribution of .NET Core, which is why instructions differ for RedHat's distro.
