### ISSUE TITLE
How does workload versioning work?

### ISSUE THREAD

**Issue by cosminstirbu** [dotnet/sdk#25089]
I'm trying to understand how versioning works in the new "workload" world in .NET.

Can 'maui' workload be updated independently of .NET? Based on the docs https://docs.microsoft.com/en-US/dotnet/core/tools/dotnet-workload-install#results-vary-by-sdk-version it seems that workloads are "bundled" with .NET releases (major and minor versions).

And if they are indeed "bundled" together, does this mean that if `maui` needs to ship a hot fix, then it will be done by releasing a new .NET version (e.g., a minor version)?

Since `dotnet workload list` command doesn't output any workload version, it leads me to believe that the workloads and .NET versions are indeed "bundled" together.

**Comment by baronfel** [comment]
They historically have been, but they can version independently. There are special packages called 'manifest' packages that advertise specific versions of the individual workloads that the SDK checks for updates to on a periodic basis. Those manifests then are used when installing/updating workloads.

However, you are right that the vast majority of the time the workloads are shipped with the SDK and any mid-ship-cycle updates just roll into the next monthly servicing release.
