### ISSUE TITLE
`dotnet list package --outdated` exit code

### ISSUE THREAD

**Issue by cosminstirbu** [dotnet/sdk#25091]
Hello,

We'd like to check for outdated packages as part of our PR pipeline.
We would like to use `dotnet list package --outdated`, however there is no way to tell (without parsing the output), if there are any outdated packages.

Would it be possible to opt into returning a non-zero exit code if there are outdated packages, so we can then fail our pipeline / report on it?

We're currently using https://github.com/dotnet-outdated/dotnet-outdated, however sometimes it is a hit or miss, because it fails to load the .sln.

Thank you,
Cosmin

**Comment by KalleOlaviNiemitalo** [comment]
This is somewhat related to <https://github.com/NuGet/Home/issues/8087> (exit code for vulnerable packages) and <https://github.com/NuGet/Home/issues/7752> (machine-readable `dotnet list package` so you'd at least be able to parse it more easily).
