### ISSUE TITLE
Add native aot test with EnableAotAnalyzer set to false

### ISSUE THREAD

**Issue by LakshanF** [dotnet/sdk#25125]
The analyzer, `EnableAotAnalyzer`, is set to true when publishing native AOT form factor (`PublishAot`=true) and generates warnings, which is the default and the expected case. Need to add a test case when publishing native aot with EnableAotAnalyzer set to false to check that warnings are not generated in this case.

**Comment by KinkyTekK** [comment]
``

**Comment by vrushalivartak** [comment]
@LakshanF - PR was merged. The ticket can be closed now, right?
