### ISSUE TITLE
different build result between dotnet cli and visual studio 2022

### ISSUE THREAD

**Issue by ianzhang366** [dotnet/sdk#25165]
### Describe the bug
Hi there, I'm trying use dotnet cli more in my daily workflow instead of using VS2022 for everything.

Doing so, I noticed some difference between dotnet cli and VS2022. For example, if I clone and build this [project ](https://github.com/lukaszbanasiak/YAPA).

On VS2022, it would work and generate a '.exe' file.

However, if I run `dotnet build ./YAPA/YAPA.csproj` it would complain:
```
dotnet build .\YAPA.csproj
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Nothing to do. None of the projects specified contain packages to restore.
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(3261,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "NET" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\6.0.202\MSBuild.dll" exists and can be run. [C:\source\repos\YAPA-1.2.0\YAPA\YAPA.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(3283,7): error MSB4028: The "GenerateResource" task's outputs could not be retrieved from the "FilesWritten" parameter. Object does not match target type. [C:\source\repos\YAPA-1.2.0\YAPA\YAPA.csproj]

Build FAILED.
```

I wonder if I'm setting something wrong, can you please help out? Or is there any document that explains how to make sure the dotnet cli can be configured in a way that would produce consistent behaviour as VS2022?

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by ianzhang366** [comment]
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\Microsoft Visual Studio\2022\Enterprise\dotnet\runtime\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by marcpopMSFT** [comment]
Taking a look at the yapa project, the csproj file is an old-style project and not an [sdk-style project ](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview). As such, it's not supported to build it with dotnet commands. You'll need to use msbuild.exe from the VS command prompt.

**Comment by ianzhang366** [comment]
Hi @marcpopMSFT thanks for the input, is there way to convert the project to the sdk-style? if so, can you please point to me the document for doing so?

**Comment by marcpopMSFT** [comment]
I know this tool can help: https://github.com/dotnet/try-convert  @mairaw, do you know of any documentation we have on migrating?

**Comment by mairaw** [comment]
If this is a .NET Framework project, I think the recommended tool now is the upgrade assistant, no?
For that, the documentation is located at https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview

/cc @cathysull

**Comment by cathysull** [comment]
@ianzhang366 - Yes, we recommend using the .NET Upgrade Assistant https://aka.ms/dotnet-upgrade-assistant to assist in converting your projects to the sdk-style. The tool also helps with a lot of the other heavy lifting when upgrading to .NET 6+. Let us know if you have any other questions!
