### ISSUE TITLE
Confusing error message when invalid target frameworks are specified

### ISSUE THREAD

**Issue by ap0llo** [dotnet/sdk#25191]
### Describe the bug

In a multi-targeting project, I accidentally used commas instead of semicolons to separate the target frameworks.

In that case, the SDKs seems to be able to parse the TFMs and the build fails with an error that indicates missing reference assemblies.

### Expected Behavior

I would have expected the build to fail with an error indicating that the value of the `TargetFrameworks` property is invalid.

### Actual Behavior

Build fails with error `error MSB3644: The reference assemblies for net6.0,Version=v0.0 were not found.`

Full Error Message:

```txt
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for net6.0,Version=v0.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\projects\tmp\tmp.csproj]
```

### To Reproduce

- Create a new console project using `dotnet new console`
- Set the `TargetFrameworks` to e.g.  `net6.0,net5.0,netcoreapp3.1`
 
  ```xml
  <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFrameworks>net6.0,net5.0,netcoreapp3.1</TargetFrameworks>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
    </PropertyGroup>

  </Project>
  ```
- Run `dotnet build`

### Further technical details

- .NET SDK version: `6.0.202`

**Comment by marcpopMSFT** [comment]
Marking for the new hire to potentially pick up. We would just detect commas and specifically catch those as we can't catch every possible bad format. Discuss other options of things we could catch with Daniel.

**Comment by nagilson** [comment]
Thank you for opening the issue. The error would ideally be caught in NuGet or MSBuild, not as far down as the SDK. For now we're adding a change to the error documentation for this case.
