### ISSUE TITLE
What is the intended way to target a specific version of the .NET Runtime?

### ISSUE THREAD

**Issue by handerss-tibco** [dotnet/sdk#25220]
As far as I can tell the runtime version required to run a .NET application has to be greater or equal to the version of the .NET SDK which built the application [1]. E.g. if I build a net6.0-window Forms project using .NET SDK 6.0.202 then the dll will have references to "System.Windows.Forms (6.0.2)" making it unable to run (or be built as a referenced package) by an older version.

The way to solve this seems to either be to force the .NET SDK version via global.json [2], or add FrameworkReference [3] attributes for each of the referenced frameworks. 

Adding a global.json which prohibits rollForward doesn't work well since the installed version of the SDK changes all the time. E.g. if I install .NET SDK 6.0.100 (which corresponds to 6.0.0 runtime) it will eventually be updated by Windows to some newer or patched version like 6.0.100-rc.1.21458.32 or 6.0.104. This breaks builds since these are not compatible with the global.json. Using the dotnet-install script also does not seem to work well since neither 6.0.0 or 6.0.100 are resolved.

It is also very unclear how the .NET SDK version corresponds to the runtime version used. E.g. .NET SDK 6.0.202 (and 6.0.104) installs the 6.0.4 runtime [4]. This means that I can't set rollForward to "patch" since that may result in a newer runtime. As far I can tell there is no way to look at the SDK version and know what runtime version I will get.

Using FrameworkReference is poorly documented and seems to require that each referenced framework is explicitly added.

Since .NET is backwards compatible within MAJOR version I want to target the lowest possible runtime, and then allow the person running my application to select whichever is the most appropriate runtime for them. I also don't want to force projects which depend on my package to use a newer SDK version than what is necessary.

How is this problem meant to be solved?

[1]: https://github.com/dotnet/winforms/issues/6663#issuecomment-1039910644, https://github.com/dotnet/winforms/issues/6663#issuecomment-1040990481, https://github.com/dotnet/winforms/issues/6663#issuecomment-1041002991
[2]: https://github.com/dotnet/winforms/issues/6663#issuecomment-1034371295
[3]: https://github.com/dotnet/core/issues/7176#issue-1129301729
[4]: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by jhudsoncedaron** [comment]
I don't understand. Is there a reason <RuntimeFrameworkVersion> doesn't work?

**Comment by handerss-tibco** [comment]
As far as I understand it the minimum required runtime version is determined by the SDK version used to compile a project. So if I am not paying attention then my application may change the required runtime version despite my TargetFramework not changing. A customer could be using 6.0.0 to run my application and then after an update it may require them to use 6.0.2 or higher despite my project not changing in any way outside of which SDK was used to build it.

This is problematic since Windows automatically updates the .NET SDK making this scenario very likely.

**Comment by marcpopMSFT** [comment]
Normally the SDK will use the minimum possible runtime version in the runtimeconfig (aka 6.0.0). Please see [this known issue](https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#issues-running-applications-with-windows-desktop-602) which discusses what happened with the 6.0.2 Windows Desktop runtime release. It looks like you've already seen some of the issues around this but that document should include the summary of what happened and workaround in that particular case.

Normally customers should not have to configure a specific runtime version.

**Comment by handerss-tibco** [comment]
@marcpopMSFT So [this comment](https://github.com/dotnet/winforms/issues/6663#issuecomment-1039910644) is only in reference to the Windows Desktop issue? Because the way it is worded seems to indicate that it is a general property.

> Normally the SDK will use the minimum possible runtime version in the runtimeconfig (aka 6.0.0).

So setting `RuntimeFrameworkVersion` should be enough then (this property is buried under ["Self-contained deployments include the selected runtime"](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#self-contained-deployments-include-the-selected-runtime) despite also applying to non self-contained applications)?
