### ISSUE TITLE
Setting EnableDefaultCompileItems to False doesn't remove the F# files from solution Explorer 

### ISSUE THREAD

**Issue by Mizux** [dotnet/sdk#2524]
For http://github.com/google/or-tools we have some [examples](https://github.com/google/or-tools/tree/master/examples/dotnet) in F# and C#.

* While using it in a [.fsproj](https://github.com/google/or-tools/blob/master/examples/dotnet/fsProgram.fsproj) file `.fs` and `.cs` are correctly hidden
* While using it in a [.csproj](https://github.com/google/or-tools/blob/master/examples/dotnet/tsp.csproj) file `.fs` are **not** hidden.

![2018-09-11-130412_3840x1200_scrot](https://user-images.githubusercontent.com/4030234/45356471-9baf3080-b5c3-11e8-9e44-1161bc3566dc.png)
note: This one follow the #1157 since it is not completely fixed IMHO.

**Comment by livarcocc** [comment]
@KevinRansom I think F# has its own set of default items, right? should I move this issue somewhere else?

**Comment by Mizux** [comment]
I think it is the C# globe for None ressources which catch them while in fsproj all .cs and .fs are hidden...
-> should it be possible to exclude .fs from the glob

i.e. in this patch https://github.com/dsplaisted/sdk/commit/eb08bd18c3c3e41288f8652ca537edd1550119d5
don't use
```xml
 <None Remove="**/*$(DefaultLanguageSourceExtension)" />
```
but something like
```xml
<None Remove="**/*.fs" />
<None Remove="**/*.cs" />
```

**Comment by Mizux** [comment]
EDIT: I use `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` instead of 
`<EnableDefaultItems>false</EnableDefaultItems>`

Since Condition check `EnableDefaultItems` it may fix my issue src: https://github.com/dotnet/sdk/blob/7308d9776506c87e4d1f8bf72f28ba7fdfc3e9f0/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L29

I'll try it tomorrow and report ASAP, sorry for the inconvenience...

**Comment by Mizux** [comment]
Replace `EnableDefaultCompileItems` by `EnableDefaultItems` Fix my issue !
