### ISSUE TITLE
AnsiConsole should support NO_COLOR

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#25264]
The AnsiConsole used by the CLI doesn't seem to support the  [NO_CONSOLE](https://no-color.org/) mechanism for opting out of shell coloration. We should do so. 

Longer term this is something that a shared IConsole implementation should handle, but that's still a while out, so it makes sense for us to make this small change in the interim.

**Comment by Marusyk** [comment]
Do you mean something like
`AnsiEnabled = string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("NO_COLOR"));`

```
private void SetColor(ConsoleColor color)
{
    if (!AnsiEnabled)
    {
          return;
    }
    ...
}
```
and the same for `SetBold`
