### ISSUE TITLE
Unable to build debian package of .NET Core app as non-root user

### ISSUE THREAD

**Issue by gcraciun** [dotnet/sdk#2526]
Running dotnet clean using debian/ubuntu fakeroot consumes all available memory and runs extremely slow. The machine used was a VM with 4GB RAM and 4 CPU cores.
Runnning on the same VM but with just 1 CPU core it works.

Steps to reproduce:
$ git clone https://github.com/ArduPilot/MissionPlanner.git
$ cd MissionPlanner
$ fakeroot dotnet clean

System used
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by livarcocc** [comment]
@rainersigwald is this something that msbuild is doing wrong?

**Comment by gcraciun** [comment]
This is affecting us in production. Can I get a status update?

**Comment by livarcocc** [comment]
Can you disable parallel builds and see if that fixes it for you? You can disable it with something like this `MSBUILDDISABLENODEREUSE=1`.

**Comment by gcraciun** [comment]
I tried setting that as an env variable and also changing the csproj file. Still no luck.

**Comment by rainersigwald** [comment]
From the `MSBUILDDEBUGCOMM=1` traces, the attempts to connect to a just-launched child all say something like

```
 (TID 10) 636765934727938712 +    0.1147ms: Starting to acquire a new or existing node to establish node ID 2...
 (TID 10) 636765934727942646 +    0.3934ms: Could not connect to existing process, now creating a process...
 (TID 10) 636765934727946399 +    0.3753ms: Launching node from /usr/share/dotnet/sdk/2.1.403/MSBuild.dll
 (TID 10) 636765934728017683 +    7.1284ms: Successfully launched msbuild.exe node with PID 30166
 (TID 10) 636765934728032798 +    1.5115ms: Attempting connect to PID 30166 with pipe MSBuild30166 with timeout 30000 ms
 (TID 10) 636765934729218261 +  118.5463ms: Failed to connect to pipe MSBuild30166. Could not connect to the pipe because it was not owned by the current user.
```

That makes me suspect that `fakeroot` is faking only one side of the connection, not both. The pipe is owned by my user:

```ShellSession
$ ls -lah /tmp/CoreFxPipe_MSBuild30166
srwxrwxr-x 1 raines raines 0 Oct 31 09:37 /tmp/CoreFxPipe_MSBuild30166
```

but presumably `fakeroot` is telling the parent process it's uid `0`.

I don't know if this is a bug in fakeroot or corefx (MSBuild creates the pipe with `PipeOptions.CurrentUserOnly`, which is pretty straightforward from the calling side).

@gcraciun, do you know of a channel to ask for `fakeroot` support?

**Comment by rainersigwald** [comment]
Best workaround I can think of is passing `-maxcpucount:1` to disable multiproc build.
