### ISSUE TITLE
KnownFrameworkReferences need to be specific to a target framework version

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2527]
Right now, we have `KnownFrameworkReference` items that look something like this in Microsoft.NETCoreSdk.BundledVersions.props:

```xml
    <KnownFrameworkReference Include="Microsoft.DesktopUI"
                              RuntimeFrameworkName="Microsoft.DesktopUI.App"
                              DefaultRuntimeFrameworkVersion="3.0.0-alpha-26829-8"
                              LatestRuntimeFrameworkVersion="3.0.0-alpha-26829-8"
                              TargetingPackName="Microsoft.DesktopUI.App"
                              TargetingPackVersion="3.0.0-alpha-26829-8"
                              />

    <KnownFrameworkReference Include="Microsoft.AspNetCore"
                              RuntimeFrameworkName="Microsoft.AspNetCore.App"
                              DefaultRuntimeFrameworkVersion="3.0.0-alpha1-10062"
                              LatestRuntimeFrameworkVersion="3.0.0-alpha1-10062"
                              TargetingPackName="Microsoft.AspNetCore.App"
                              TargetingPackVersion="3.0.0-alpha1-10062"
                              />
```

These are not specific to the version of .NET Core targeted.  So if you were targeting .NET Core 2.x, you could still add a `FrameworkReference` to Microsoft.DesktopUI, and we would try to add the package reference to the targeting pack.

The `KnownFrameworkReference` items should include a `TargetFrameworkVersion` on them to which they apply, and the `ResolveFrameworkReferences` task should filter them to only look at the ones that apply to the current target framework version.  (We might also want a nice error message if you have a FrameworkReference to something that's available in a different version of .NET Core).

**Comment by nkolev92** [comment]
I'm curious how the FrameworkReference to TFM mapping will affect NuGet and https://github.com/NuGet/Home/issues/7342.
