### ISSUE TITLE
[dotnet-sdk-7.0.100-preview.5.22257.3] All WPF apps launch failed with black screen or with exception about loading dlls

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/sdk#25289]
**Application Name:**  All WPF apps
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number**: dotnet-sdk-7.0.100-preview.5.22257.3

**Also can check the details at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1537132

**Verify Scenarios**:
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22257.3: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22258.1: Fail
3). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.4.22252.9: Pass

**Minimal Repro steps:**
The machine only has 7.0 installed.

1. Open command prompt window.
2. Run "dotnet new wpf" command to create a default WPF project.
3. Run "dotnet run" command to launch the default WPF project, it will show a black screen.

**Expected Result**: 
It will show the blank mainwindow.

**Actual Result**:
It shows a black screen as below shows:
![Actual](https://user-images.githubusercontent.com/83067197/167363072-68fd4765-c746-47d5-8c0a-475eff84017d.png)

**Findings:**
Different WPF apps has different behaviours when launching failed. Some of them have black screenshot as the minimal repro app. Some of them throw exception message as below shows:
![error1](https://user-images.githubusercontent.com/83067197/167363256-6a5cf623-f335-4ac7-992e-30020d39263a.png)
![error2](https://user-images.githubusercontent.com/83067197/167363291-bd28e6b0-254c-4ba5-9ed1-fcc30cacf072.png)

But when using windbg to launch these apps, they display the same dlls load exceptions as below shows:
```
ModLoad: 00007ffe`51540000 00007ffe`515ae000   C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.0-preview.5.22255.12\PresentationFramework.Aero2.dll
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): CLR exception - code e0434352 (first chance)
ModLoad: 00007ffe`6e230000 00007ffe`6e270000   C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.0-preview.5.22255.12\PresentationFramework.Classic.dll
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): C++ EH exception - code e06d7363 (first chance)
(2bf0.10b4): CLR exception - code e0434352 (first chance)
ModLoad: 00007ffe`8d8f0000 00007ffe`8d904000   C:\Windows\SYSTEM32\wtsapi32.dll

```
@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@marcpopMSFT We verified it on the latest build 7.0.100-preview.5.22262.12, it still repro. Please help us move it to the right area if it is incorrect. Thanks.

**Comment by marcpopMSFT** [comment]
It probably needs [this PR](https://github.com/dotnet/installer/pull/13811) but daily builds during development can be unreliable.

**Comment by singhashish-wpf** [comment]
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
The latest preview 5 build fixes it.

**Comment by Junjun-zhao** [comment]
We have verified it on the latest build dotnet-sdk-7.0.100-preview.5.22267.10, this issue has been fixed. Hence closing this bug.
