### ISSUE TITLE
[API Compat] Provide a strict option for package-validation baseline checks

### ISSUE THREAD

**Issue by dougbu** [dotnet/sdk#25302]
### Is your feature request related to a problem? Please describe.

We are hitting issues using Microsoft.CodeAnalysis.PublicApiAnalyzers to verify **no** public API changes in our servicing branches. This feature would enable us to use `package-validation` instead.

### Describe the solution you'd like

Quoting me:
> 2.	It checks for breaking changes, not meeting our “no public API changes” requirement at all.

Quoting @ericstj:
> 2.	We do have a “strict” mode that means no changes – this is how we make sure all API is exposed in our reference assemblies.  Probably we don’t expose this option for baseline comparisons but we could.  That’s an easy feature to add. 

### Additional context

If it matters, we already enable package validation in dotnet/aspnetcore and we leave `$(DisablePackageBaselineValidation)` alone in servicing branches release/6.0. We'd use package validation in release/5.0 as well with this feature in place.

**Comment by ericstj** [comment]
As Doug mentions he would like to use package validation to ensure that a release is making zero change over the baseline.  I think we can make that work if we plumb a parameter for it.  @joperezr @ViktorHofer
