### ISSUE TITLE
PostBuildEvent skipped when set to Always in .csproj

### ISSUE THREAD

**Issue by timanderson** [dotnet/sdk#25316]
I have a .NET 6 ASP.NET Core project which was created in Visual Studio but is now developed mostly in VS Code. On an M1 Mac I noticed that the post build events are being skipped. In the .csproj I have:

```
 <PropertyGroup>
   <TargetFramework>net6.0</TargetFramework>
   <RunPostBuildEvent>Always</RunPostBuildEvent>
 </PropertyGroup>
```

However in the diagnostic output from dotnet build I get:

`Target "PostBuildEvent" skipped, due to false condition; ('$(PostBuildEvent)' != '' and ('$(RunPostBuildEvent)' != 'OnOutputUpdated' or '$(_AssemblyTimestampBeforeCompile)' != '$(_AssemblyTimestampAfterCompile)')) was evaluated as ('' != '' and ('Always' != 'OnOutputUpdated' or '' != '')).
`

This does not look right to me: Always should mean Always, or is there a different way this should be expressed?

**Comment by KalleOlaviNiemitalo** [comment]
[PostBuildEvent target is the MSBuild repository](https://github.com/dotnet/msbuild/blob/a02f73656613e752c73ff442cdd72540f4b09f57/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5701-L5708)

Your diagnostic output looks like the PostBuildEvent property is empty, i.e. there would be nothing for the PostBuildEvent target to do.

**Comment by timanderson** [comment]
Hmm, it is not empty, it runs a JavaScript minifier and copies some files. It is because this wasn't running that I noticed the problem.

**Comment by timanderson** [comment]
Apologies, I am probably misunderstanding the problem here. My PostBuild tasks are defined as:

`<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=`

and I have three of these with different conditions for different platforms.

On Windows the log still says PostBuildEvent skipped. However it goes on to run the "PostBuild" target:

```
  Target "PostBuildEvent" skipped, due to false condition; ('$(PostBuildEvent)' != '' and ('$(RunPostBuildEvent)' != 'OnOutputUpdated' or '$(_AssemblyTimestampBeforeCompile)' != '$(_AssemblyTimestampAfterCompile)')) was evaluated as ('' != '' and ('Always' != 'OnOutputUpdated' or '' != '')).
13:54:45.736   6:7>Target "PostBuild: (TargetId:217)" in project "....csproj" (target "CoreBuild" depends on it):
                   Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Exec" (TaskId:153)
```

But on the M1 Mac it (correctly) skips the first PostBuild target due to false condition but then does not look at the next PostBuild target at all.

I recall when I set this up that it wasn't clear to me whether multiple PostBuild targets are allowed and I may have observed some inconsistent behaviour here.

**Comment by KalleOlaviNiemitalo** [comment]
If you have multiple targets with the same name, then the last one should win.

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Number>1</Number>
  </PropertyGroup>

  <Target Name="A" Condition="$(Number) == 1">
    <Message Importance="high" Text="A 1"/>
  </Target>
  <Target Name="A" Condition="$(Number) == 2">
    <Message Importance="high" Text="A 2"/>
  </Target>
  <Target Name="A" Condition="$(Number) == 3">
    <Message Importance="high" Text="A 3"/>
  </Target>

</Project>
```

`dotnet msbuild -target:A` considers only the last target named `A`, and then skips it because of the condition.

According to <https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2019#determine-the-target-build-order>, the Condition of the PostBuildEvent target does not affect whether MSBuild executes targets that have `AfterTargets="PostBuildEvent"`.

I think you'd better just give unique names to your PostBuild targets, or move them to separate files that are then imported conditionally so that there is no way for them to override each other.
