### ISSUE TITLE
How to add resource files to netstandard project

### ISSUE THREAD

**Issue by Pilchie** [dotnet/sdk#2532]
_From @ramsubbaraoc on September 12, 2018 2:44_

In .NET Framework, while adding resource files,the files can be added either as an EmbeddedResource or Resource.In netstandard class library project,there is only "EmbeddedResource" property.How to add a file as "Resource" instead of "EmbeddedResource" ?

I have language specific .resources file. If i add it as "EmbeddedResource" each file will be converted to a satellite assembly which i don't want. I want all the .resources file to be embedded into same class library rather than a new library.

csc.exe command line has that option, if we use -res option all the resource files get embedded into the same class library where the source code resides. 

Is there a way to do the same for netstandard class library project as well?

_Copied from original issue: dotnet/project-system#3987_

**Comment by Pilchie** [comment]
@livarcocc / @nguerrera / @dsplaisted ?

**Comment by Pilchie** [comment]
_From @nguerrera on September 12, 2018 20:25_

The handling of `@(Resource)` items in .NET Framework comes from Microsoft.WinFX.targets, which mainly handles Xaml, and is never imported to a .NET Standard project. I wasn't familiar with them until now, to be honest.

It is possible to force an EmbeddedResource into the main assembly with a custom target:

``` xml
<Target Name="_ForceAllResourcesToMainAssembly" AfterTargets="SplitResourcesByCulture">
  <ItemGroup>
    <EmbeddedResource>
      <Culture />
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
  </ItemGroup>
</Target>
```

There is some related discussion in https://github.com/Microsoft/msbuild/issues/1454#issuecomment-265621913 about allowing Culture/WithCulture to be set outside a target and respected. cc @cdmihai

**Comment by Pilchie** [comment]
Also somewhat related to https://github.com/dotnet/project-system/issues/3620...

**Comment by Pilchie** [comment]
> The handling of @(Resource) items in .NET Framework comes from Microsoft.WinFX.targets, which mainly handles Xaml, and is never imported to a .NET Standard project

@cdmihai @nguerrera @dsplaisted does changing this as part of .NET Core 3 make sense?

**Comment by Pilchie** [comment]
_From @ramsubbaraoc on September 13, 2018 3:58_

@Pilchie @nguerrera : Thank you.That worked.But the ResourceManager class doesn't pick the resources based on the Thread  culture. Should i be hardcoding the "basename" based on the culture?

**Comment by Pilchie** [comment]
_From @nguerrera on September 13, 2018 18:1_

Indeed, ResourceManager does not support finding localized resources in the main assembly. 

Changing the base name like that doesn't seem right. I looked briefly at extending ResourceManager or ResourceSet, but there doesn't seem to be an easy hook. cc @tarekgh

**Comment by Pilchie** [comment]
_From @nguerrera on September 13, 2018 19:5_

> @cdmihai @nguerrera @dsplaisted does changing this as part of .NET Core 3 make sense?

I think it does. I'm going to look more closely at these targets.

**Comment by Pilchie** [comment]
@nguerrera Should I move this to dotnet/sdk repo?

**Comment by Pilchie** [comment]
_From @nguerrera on September 13, 2018 20:33_

OK. It might need to move again to msbuild, but that's ok for now.

**Comment by davidwengier** [comment]
Ran into this today, stuck between the rock-and-a-hard-place of having to implement behaviour like `System.Resources.ResourceFallbackManager` with `EmbeddedResource` items. I can either use the workaround @nguerrera posted (thank you!) or I can use satellite assemblies which means repeatedly calling `assembly.GetSatelliteAssembly` with different cultures until one doesn't throw, which is not great.

**Comment by xrkolovos** [comment]
is this done?

**Comment by dsplaisted** [comment]
I believe this is supported with WPF projects targeting .NET Core 3.0 or higher.  I don't think this is supported in .NET Standard.
