### ISSUE TITLE
The target "VerifyTargetVersion" does not exist in the project.

### ISSUE THREAD

**Issue by grokys** [dotnet/sdk#2535]
Ever since upgrading https://github.com/github/VisualStudio to use new the SDK project files (for all projects except VSSDK projects) we're getting the following error when building in Visual Studio:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(841,7): error MSB4057: The target "VerifyTargetVersion" does not exist in the project.
```

Everything works fine when building from the command line. The error goes away after multiple builds in Visual Studio, but comes back on a `git clean -xdf`.

I'm not even sure if this is an SDK issue, but posting here first because it arose after the conversion to SDK project files.

Repro:

- `git clone https://github.com/github/VisualStudio`
- `cd VisualStudio`
- `git submodule init`
- `git submodule deinit script`
- `git submodule update`
- Open `GitHubVS.sln` in Visual Studio 15.8.4
- Build solution

Sometimes the `VerifyTargetVersion` error doesn't show up in the Error List, but it's present in the msbuild logs.

**Comment by grokys** [comment]
Updating to https://github.com/onovotny/MSBuildSdkExtras/releases/tag/v1.6.55 seems to fix the problem. Sorry for the noise!

**Comment by livarcocc** [comment]
What was the last version on which this worked?

**Comment by grokys** [comment]
I think that would be the commit before we migrated to SDK csproj: https://github.com/github/VisualStudio/commit/afb8d2d148b963325f3e95ef28fb7acca2c4d462

**Comment by grokys** [comment]
A little more info: if you continue to build, eventually it will work.

**Comment by livarcocc** [comment]
I meant what was the last version of the SDK/VS on which this worked. Or did this never worked on the new csproj format?

**Comment by grokys** [comment]
Ah apologies, I don't think it ever worked properly on the new csproj format.

We weren't aware of that immediately though because it passes on CI (MSBuild from command line) and after 3 or 4 tries it works, meaning that we never saw the error until we started from a clean repository.

**Comment by livarcocc** [comment]
I don't believe that `VerifyTargetVersion` is target defined by us. At least it is not in the .NET Core SDK. I don't believe it is in MSBuild's core targets either.

Do you know where that comes from?

@rrelyea @Pilchie any ideas why this would sometimes work in VS and sometimes fail? I wonder if maybe this target is coming from some package, if that could cause issues.

**Comment by livarcocc** [comment]
The only place where I found a reference for this was in a Microsoft.VSSDK.BuildTools, which I am not familiar with.

**Comment by grokys** [comment]
Yes this is a VSSDK project, I wasn't sure where to route this, so this was my first port of call due to the fact it was caused by the SDK csproj migration. Any idea where I did route this to given that the problem originates there?

**Comment by livarcocc** [comment]
@grokys we reached out to the owners of the VSSdk inside MS and asked them to engage here to help investigate this issue.

**Comment by Michael-Eng** [comment]
@grokys - VerifyTargetVersion is defined in Microsoft.vssdk.targets and is part of the build of a vsix project. Are you saying this fails on a clean build but succeeds on an incremental build?

What version of the VS SDK Build Tools are you using to build? Is there more than one vsix project being built?

Can you attach the diagnostic level build output? In VS, go to Tools|Options, Projects and Solutions, Build and Run, and set MSBuild project build output verbosity to Diagnostic first before you build. Thanks!

**Comment by AArnott** [comment]
The missing VerifyTargetVersion issue is one I've never seen myself. I use .NET SDK style projects all the time, [including with VSIX projects](https://github.com/AArnott/VSIXProjectWithPackageReferences/blob/netsdk/VSIXProject11/VSIXProject11.csproj). .NET SDK style for VSIX projects isn't officially supported and some of the IDE experiences are degraded (e.g. no vsixmanifest designer). But we also have plenty of VSIX projects that aren't .NET SDK style but reference projects that are, and haven't seen this problem.

The fact that with enough builds it eventually works tells me you've probably customized your build somehow and you have an incremental build problem. I may be able to look into this today. I'll try.

**Comment by AArnott** [comment]
Well, your solution definitely has package restore issues. When I follow these steps:

```ps1
git clone https://github.com/github/VisualStudio github4vs
cd .\github4vs\
git submodule init
git submodule deinit script
git submodule update
msbuild .\GitHubVS.sln /restore
```

The _restore_ fails with this error:

> D:\git\github4vs\src\GitHub.InlineReviews\GitHub.InlineReviews.csproj(491,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Microsoft.VSSDK.BuildTools.14.3.25407\build\Microsoft.VSSDK.BuildTools.props.

I'm pretty sure what this means is your design-time build that is performing the restore is executing too much of the build (have you customized it?) which triggers projects to build that have not yet been restored. This causes restore itself to fail. I imagine after enough attempts to restore packages, it will eventually succeeds since each time it restores it gets a little bit more done before the failure. Eventually, it would work. This sounds similar to your explanation that a missing target eventually works. My guess is the missing target, once present, is one that was restored from a package reference / packages.config file.

Someone should review your package restore logs to find out which target got a little out of control and started executing projects that hadn't been restored yet. That needs to be fixed.

**Comment by AArnott** [comment]
I see you're still using packages.config with your .NET SDK style projects. Don't do that. You need to merge all your packages.config files into your .NET SDK style projects. For your old-style projects you can keep the packages.config files if you want to, but I recommend a full migration to PackageReference for _all_ your projects (old and new style).

**Comment by grokys** [comment]
We did migrate to `PackageReference` for SDK projects but looks like I forgot to delete some `packages.config` files. From what I understood they would be ignored when you have `<PackageReferences>` though?

Your restore error has given me something to go on, I will take a look there. I'll also get the diagnostic build output shortly.

**Comment by AArnott** [comment]
I don't know if packages.config is ignored automatically given the presence of a `PackageReference` in your project.

I observe that you're using packages.config style references for your VS SDK projects. And in particular, you're getting your VS SDK itself via that reference:

```xml
  <Import Project="..\..\packages\Microsoft.VSSDK.BuildTools.14.3.25407\build\Microsoft.VSSDK.BuildTools.props" Condition="Exists('..\..\packages\Microsoft.VSSDK.BuildTools.14.3.25407\build\Microsoft.VSSDK.BuildTools.props')" />
```

So you'll be missing targets until you do a package restore that restores packages.config packages. 
If you had a reference from a .NET SDK style project to one of these VS SDK projects, you may end up failing if the packages.config packages haven't restored by the time the .NET SDK style project's restore build had called into its P2Ps. I don't know if that happens. I don't ever have .NET SDK style projects reference older style ones -- I'm not sure whether that's supported. You *may* need to script a restore step that explicitly runs (in effect) `nuget restore **\packages.config` *before* allowing the regular restore to take care of everything else.

**Comment by jcansdale** [comment]
It appears that updating from `Microsoft.VSSDK.BuildTools.15.0.26201` to `15.8.3252` has resolved the issue. The following PR branch seems to build consistently: https://github.com/github/VisualStudio/pull/1929.
