### ISSUE TITLE
[Question] Use of custom compiler in new csproj format

### ISSUE THREAD

**Issue by CheloXL** [dotnet/sdk#2536]
Hi,
I'm trying to move several solutions where I'm using a custom compiler instead of csc. Right now, I have the following settings in my csproj (old version)
```
...
<NoStdLib>true</NoStdLib>
<AddAdditionalExplicitAssemblyReferences>false</AddAdditionalExplicitAssemblyReferences>
<AdditionalExplicitAssemblyReferences />
<SkipCopyBuildProduct>true</SkipCopyBuildProduct>
<NoCompilerStandardLib>true</NoCompilerStandardLib>
<ImportByWildcardAfterMicrosoftCSharpTargets>false</ImportByWildcardAfterMicrosoftCSharpTargets>
<CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
<CopyOutputSymbolsToOutputDirectory>false</CopyOutputSymbolsToOutputDirectory>
<UseHostCompilerIfAvailable>false</UseHostCompilerIfAvailable>
...
<UsingTask TaskName="CsCompilerTaskImplementation" AssemblyFile="$(CsCompilerPathExecutable)" />
<Import Project="$(MSBuildBinPath)\Microsoft.Common.targets" />
<Target Name="CoreCompile">
<CsCompilerTaskImplementation [settings]></CsCompilerTaskImplementation>
</Target>
...
```
All of that because I do not want csc to take part of the compilation, nor I do need the generation of any .dlls/obj, etc. The above was created by trial and error and by looking at the default implementation.

Now, I'm trying to move all my projects to the new csproj format and I really don't know where to start. The above of course not only doesn't work, but some of the settings there are specific to the old implementation.

Please note that I'm also referencing a custom mscorlib (that's why the NoStdLib) and I really don't remember well why right now, but some of the settings above were needed because the old csc had issues with that too...

Any directions on how to achieve this? Thanks in advance.

**Comment by livarcocc** [comment]
This is not something that I believe we have really tried out or considered, so, I don't believe we will have much ready help in this case.

cc @jaredpar  in case he has any insights in how to achieve this.

**Comment by jaredpar** [comment]
The supported way of using a custom compiler is to define `$(CscToolPath)`  and / or `$(CscToolExe)` to point to the alternate compiler you would like to use. That works equally well on classic or new SDK projects. Is there a reason that you didn't go with that approach? 

CC @agocke, @chsienki

**Comment by CheloXL** [comment]
Probably because at the time I created this there were not that much information. These projects are almost 7 years old. Also, I'm using a custom task, not an exe. In the example above I'm not showing additional properties I'm feeding the tool with (like EmbeddedResource, ReferencePath, DocumentationFile, etc). Another issue is with msbuild generating additional .cs files that includes references that don't exists on my library (for example, the file '.NETFramework,Version=v4.6.2.AssemblyAttributes.cs' created automatically by the build subsystem).

I don't know about the new system (used by dotnet) but the old msbuild was hardcoded to use csc and nothing else. It expects the compiler to generate .dlls for libraries (mine doesn't, as it is really a transpiler, so I'm converting c# source code to js source code), expects to be working with the shipped mscorlib (even if my library complies 100% with the c#/ECMA specification), etc.

I need this to be able to build my solution from inside VS. My compiler already handles solutions/projects on its own, so maybe the best approach is not to replace csc, but to simply have a way to disable it completely and let me hang in the **build** action.

**Comment by CheloXL** [comment]
@chsienki Yes!, that looks like what I'm after. It is basically what I did with the old msbuild (but I did using a sledge hammer... by overriding existing targets to nullify what they were intended to do).
I guess that I can still register custom tasks and call them from the AfterTargets, right? If that's the case, I think it is all I need.
Will try this and see how it works. Thanks!

**Comment by chsienki** [comment]
No problems. If you run into issues, I suggest opening a new thread in the MSBuildSdks repo going forward.

One gotcha that took me a long time to figure out and the docs don't make very clear: when you reference the SDK you need to explicitly specify the version as part of the sdk name, or MSBuild will fail to resolve the SDK. Here's a working example:

```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.40">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="RunTool" AfterTargets="Build">
    <Message Importance="high" Text="This is the actual build" />
  </Target>
</Project>
```

**Comment by CheloXL** [comment]
Thanks!

**Comment by livarcocc** [comment]
Seems like this questions has been addressed. Closing the issue for now.
