### ISSUE TITLE
Single EXE build takes minutes to launch, self contained build launches in seconds

### ISSUE THREAD

**Issue by mike-ward** [dotnet/sdk#25371]
### Describe the bug
Links two different builds of the same program:

- Self contained, ready to run, win-x86 - [selfcontained.zip](https://drive.google.com/file/d/1ePBlypgj5QspcndbHw412vRMgWtbPDwo/view?usp=sharing)
- Single EXE, ready to run, win-86  - [singleexe.zip](https://drive.google.com/file/d/1VGUauy-8Q4G4_9qJq05cXaMJNxnCO_yk/view?usp=sharing)

Both programs run, however the single EXE version takes over two minutes to display the first screen. The self-contained version launches in seconds.

Builds are NOT trimmed.

Code can be found at https://github.com/mike-ward/Loon

### Further technical details
- Include the output of `dotnet --info`

```
► dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\
Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c
.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
JetBrains Rider 2022.1.1
Build #RD-221.5591.20, built on April 28, 2022
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    com.intellij.resharper.HeapAllocationsViewer (2022.1.0)
    com.intellij.javafx (1.0.4)
    com.intellij.ideolog (203.0.28.1)
    avalonia-rider (1.0.0.2140933513)
    com.jetbrains.rider.android (221.5591.20)
```

**Comment by vitek-karas** [comment]
How do you publish the single-file? Do you allow it to extract something, or you use the default (load everything from memory)?

We've seen similar behavior caused by some AV software. The single-file reports all loaded code to the AV system. Most AVs will be able to cache the results of these scans, but some don't. The difference is that non-single file load everything from files, so the AV can cache its results based on the file, but single-file loads most assemblies from "random" memory regions, and so the caching has to be done differently.
Can you try to run it on a different machine with different AV - or disable AV temporarily?
You could also look through something like task manager if the AV process is consuming lot of CPU while the program is starting.

**Comment by mike-ward** [comment]
dotnet publish Loon.Desktop.csproj -c Release --runtime win-x86 --self-contained -p:PublishSingleFile=true p:IncludeNativeLibrariesForSelfExtract=true

Excluded the `exe` from AV and it works fast now.

**Comment by vitek-karas** [comment]
Thanks for the confirmation - that's unfortunate. There's little we can do about this - the runtime MUST report the code to the AV subsystem (for security reasons), and the rest is out of our hands.

**Comment by mike-ward** [comment]
Would native AOT avoid this issue?

**Comment by vitek-karas** [comment]
Yes - it would - there all the code is properly part of the executable, so the AV will scan it as any other native executable. It has no embedded code files (managed code), unlike bundle which is mostly embedded code files.
