### ISSUE TITLE
Dotnet list command does not find custom obj path

### ISSUE THREAD

**Issue by ZenwalkerD** [dotnet/sdk#25378]
### Describe the bug
In my project; the output bin and obj paths have been customized to point to one common location for all projects via Directory.Build.props file in the root level (solution level) and its content is as shown:

```
<Project>
	<PropertyGroup>		
		<BaseIntermediateOutputPath>$(SolutionDir).build\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
		<BaseOutputPath>$(SolutionDir).build\bin\$(MSBuildProjectName)</BaseOutputPath>
		<IntermediateOutputPath>$(SolutionDir).build\obj\$(MSBuildProjectName)</IntermediateOutputPath>	
	</PropertyGroup>
</Project>
```

### To Reproduce
With above settings when projects get compiled; it creats folders under .build/obj.  When i run, dotnet restore; it is successful. I can compile the code fine, it runs fine as well.

Now when i run $ dotnet list package --deprecated or any --options for this command; i get the following error:

_No assets file was found for `D:\Projects\Src\API.csproj`. Please run restore before running this command._

I understand here that the dotnet list is unable to find the obj path which is configured to different location.

### Further technical details
- Include the output of `dotnet --info`
 
> dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   6.0.300
>  Commit:    8473146e7d
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.300\
> 
> Host (useful for support):
>   Version: 6.0.5
>   Commit:  70ae3df4a6
> 
> .NET SDKs installed:
>   5.0.407 [C:\Program Files\dotnet\sdk]
>   6.0.202 [C:\Program Files\dotnet\sdk]
>   6.0.300 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

> Microsoft Visual Studio Enterprise 2022
> Version 17.2.0
> VisualStudio.17.Release/17.2.0+32505.173
> Microsoft .NET Framework
> Version 4.8.04084

Additional References:
Similar issue; but following the same solution does not provide any help. https://github.com/dotnet/msbuild/issues/2070

**Comment by KalleOlaviNiemitalo** [comment]
Does it work if you use MSBuildThisFileDirectory instead of SolutionDir?
