### ISSUE TITLE
.NET CLI: Allow to specify multiple packages at once `dotnet add package <package1> <package2> <package3> ..`

### ISSUE THREAD

**Issue by soundaranbu** [dotnet/sdk#25396]
### Is your feature request related to a problem? Please describe.
CLIs that I know like `apt`, `npm` allow to install multiple packages in the same command like below

```sh
npm i package1 package2
```

But, as far as I now it's not possible in .NET CLI (Correct me if I'm wrong). 

Today, I was writing a blog post where I literally typed a command like this with multiple packages to install in the same command & later realized that it's not possible.
```sh
dotnet add package package1 package2 package3
```

### Describe the solution you'd like
The solution is to allow to specify multiple package names in the same command
```sh
dotnet add package package1 package2 package3
```

### Additional context
- Nil

**Comment by JamesSkemp** [comment]
Since this ranks pretty high in search results, https://github.com/NuGet/Home/issues/9412 is an outstanding issue from 2020 that covers the above ask.

If you're using PowerShell, leveraging arrays works okay:

```powershell
'Microsoft.Extensions.Configuration', 'Microsoft.Extensions.Configuration.Binder', 'Microsoft.Extensions.Configuration.Json', 'Microsoft.Extensions.Hosting' | ForEach-Object { dotnet package add $_ }
```
