### ISSUE TITLE
Unable to access the MVC App after published onto Azure

### ISSUE THREAD

**Issue by jitendriyag2** [dotnet/sdk#2540]
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
Application: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
Application:    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
Application:    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
Application:    at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
Application:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
Application:    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
Application:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
Application:    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
Application:    at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
Application:    at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
Application:    at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
Application:    at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
Application:    at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
Application:    at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
Application: --- End of stack trace from previous location where exception was thrown ---
Application:    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
Application:    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
Application:    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
Application:    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
Application:    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
Application:    at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
Application:    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
Application:    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Application:    at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Application:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Application:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Application:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Application:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Application:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

```
> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>netcoreapp2.1</TargetFramework>
>     <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
>     <LangVersion>latest</LangVersion>
>     <!--<PreserveCompilationContext>true</PreserveCompilationContext>
>     <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>-->
>   </PropertyGroup>
>   <ItemGroup>
>     <Content Remove="Views\Index.cshtml" />
>   </ItemGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
>   </ItemGroup>
>  
>   <ItemGroup>
>     <Content Update="Views\Home\Index - Copy.cshtml">
>       <Pack>$(IncludeRazorContentInPack)</Pack>
>     </Content>
>     <Content Update="Views\Shared\_Layout - Copy.cshtml">
>       <Pack>$(IncludeRazorContentInPack)</Pack>
>     </Content>
>   </ItemGroup>
> </Project>
> 
```

**Comment by jitendriyag2** [comment]
As per different solutions i put all the config still it is not resolved

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <LangVersion>latest</LangVersion>
    <UserSecretsId>a6ccfad5-6395-45d7-87e7-d75c56e7ee02</UserSecretsId>
    
  </PropertyGroup>
  
  <ItemGroup>
    <Content Remove="Views\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
  </ItemGroup>
 
  <ItemGroup>
    <Content Update="Views\Home\Index - Copy.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Views\Shared\_Layout - Copy.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
</Project>

**Comment by livarcocc** [comment]
@vijayrkn @rynowak can one of you take a look?

**Comment by rynowak** [comment]
`MvcRazorExcludeRefAssembliesFromPublish` should be true or omitted if you're using runtime compilation. This error says that the reference assemblies aren't present, but you're trying to do compilation at runtime.
