### ISSUE TITLE
`dotnet test` fails to launch `DumpMinitool*.exe` because it is a DLL - doesn't produce dump for process of different architecture

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/sdk#25421]
### Describe the bug
Running `dotnet test` with hang dumps enabled does not create a dump for (child) processes that do not match the current architecture (for example, 64-bit testhost, test launches a 32-bit process).

### To Reproduce

On Windows x64:

1. `dotnet new xunit`
2. Add a test that launches a 32-bit process that will stay running:
```csharp
[Fact]
public void LaunchX86()
{
    using (Process p = Process.Start(@"C:\Windows\SysWOW64\notepad.exe"))
    {
        p.WaitForExit();
    }
}
```
4. `dotnet test --blame-hang-timeout 10s --diag:log.txt;tracelevel=verbose`

#### Expected
Dump to be produced for both `testhost` and `notepad`

#### Actual
No dump for `notepad`

From [log.datacollector](https://github.com/dotnet/sdk/files/8691652/log.datacollector.22-05-13_15-45-10_81383_5.txt):
```
TpTrace Error: 0 : 19220, 12, 2022/05/13, 15:45:21.877, 2157168736492, datacollector.dll, WindowsHangDumper.Dump: Error dumping process 21596 - notepad: System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\Program Files\dotnet\sdk\7.0.100-preview.3.22179.4\Extensions\DumpMinitool.x86.exe' with working directory 'C:\Users\elfung\AppData\Local\Temp\dd4a4675-188b-417e-9a1d-5c4dc0bf6729'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.<>c__DisplayClass1_0.<LaunchProcess>g__InitializeAndStart|0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack, Action`2 outputCallBack)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.WindowsHangDumper.CollectDump(Process process, String outputFile, DumpTypeOption type)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.WindowsHangDumper.Dump(Int32 processId, String outputDirectory, DumpTypeOption type).
```

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.3.22179.4
 Commit:    c48f2c30ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.3.22179.4\
```

Apparently the `DumpMinitool.x86.exe` that is installed is not an executable?
```
>dumpbin "C:\Program Files\dotnet\sdk\7.0.100-preview.3.22179.4\Extensions\DumpMinitool.x86.exe"
Microsoft (R) COFF/PE Dumper Version 14.33.31424.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file C:\Program Files\dotnet\sdk\7.0.100-preview.3.22179.4\Extensions\DumpMinitool.x86.exe

File Type: DLL
```

**Comment by elinor-fung** [comment]
Checked Preview 4 too:
```
Dump of file C:\Program Files\dotnet\sdk\7.0.100-preview.4.22252.9\Extensions\dump\DumpMinitool.x86.exe

File Type: DLL
```

However, if I download the TestPlatforms.visx from https://github.com/microsoft/vstest-docs/blob/main/docs/releases.md#1720, it seems to be an executable as expected:
```
Dump of file C:\Downloads\TestPlatform.vsix\Extensions\DumpMinitool.x86.exe

File Type: EXECUTABLE IMAGE
```

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/runtime-infrastructure for visibility.

**Comment by ViktorHofer** [comment]
Should this issue be moved into microsoft/vstest?

**Comment by AaronRobinsonMSFT** [comment]
> Should this issue be moved into microsoft/vstest?

I believe @elinor-fung considered this but opted to report it here because when pulling down the assets from microsoft/vstest the binary is correct. Mentioned in https://github.com/dotnet/sdk/issues/25421#issuecomment-1126565424.

**Comment by nohwnd** [comment]
Uuuf. Belongs to me, will have a look.

**Comment by nohwnd** [comment]
@elinor-fung I tried this, and found few bugs that I am fixing. I am on preview4 unlike you so my experience might be different. 

1. The way we detect process bitness is wrong, and on my system I see all processes being marked as x64. The version you use is using the older logic before my broken change, so that is why you are able to trigger MiniDumpTool.x86. 
2. Even with the logic broken a dump is still created, but it is a 64-bit dump of 32-bit process, which is useless and was the whole point of having dumpMinitool added. 
3. In your repro you start 32-notepad from the correct path, but on my system (windows 11 insiders) that starts a 64-bit notepad process. I replaced the path with powershell executable @"C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe"). And with a fix for 1. I can see a correct 32-bit dump being created.
4. I could not repro the issue with the image not being a valid executable. You are not running on arm64 or anything right?

**Comment by nohwnd** [comment]
I can actually repro 4. in preview 3 and preview 4, the shipped executable cannot be run, looking at it I can see that it has the correct attributes, but ilspy says that it contains native code.

**Comment by nohwnd** [comment]
This should fix the other half where our executables are made unusable. https://github.com/dotnet/installer/pull/13939

**Comment by nohwnd** [comment]
Fixed in both net7 and net6.0.400.
