### ISSUE TITLE
build macOS (Arm64)  Run:  segmentation fault

### ISSUE THREAD

**Issue by Mossimos** [dotnet/sdk#25440]
### Describe the bug
I was starting a new .NET 6 console project on a MacBook mini (M1) via the CLI: `dotnet new console`
build complete 
SDK 6.0.300 :  run app  segmentation fault
SDK 6.0.202 : Normal output` "Hello, world"`

### Exceptions (if any)

Download and install the latest .NET 6 SDK on macOS Monterey 12.3.1 (my machine is a MacBook mini  M1 )
Create a new .NET console application via dotnet new console
Build the application 
`dotnet publish "/Users/moxiansheng/Desktop/testdotnet/testdotnet.csproj" -c Release -p:PublishProfile=osx-arm64 -p:DeployOnBuild=true -p:ExtraDefineConstants=osx-arm64 --nologo
`
PublishProfile=osx-arm64 File
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DefineConstants>MAC;PUBLISH;$(DefineConstants)</DefineConstants>
    <Configuration>Release</Configuration>
    <Platform>ARM64</Platform>
    <PublishDir>bin\Release\Publish\osx-arm64</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <RuntimeIdentifier>osx.11.0-arm64</RuntimeIdentifier>
    <TargetFramework>net6.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
![截屏2022-05-15 20 51 35](https://user-images.githubusercontent.com/26396340/168474922-b30bb9ac-edd4-4a66-97a3-46ff4c95bda6.png)

projcet
[testdotnet.zip](https://github.com/dotnet/sdk/files/8695022/testdotnet.zip)

**Comment by AntonLapounov** [comment]
@VSadov Do you think this is a dup of dotnet/runtime#69010?

**Comment by Mossimos** [comment]
this pr fix https://github.com/dotnet/runtime/pull/68845
