### ISSUE TITLE
Running a SCD Windows .NET Core application fails when the assembly name is longer than 64 characters.

### ISSUE THREAD

**Issue by alexdrl** [dotnet/sdk#2544]
Having an ASP.NET Core Application which a assembly name longer than 64 characters like `LongerThan64CharactersAssemblyNameLongerThan64CharactersAssemblyName`.
If it is published self-contained with `dotnet publish -r win10-x64`, the generated exe has the correct name `LongerThan64CharactersAssemblyNameLongerThan64CharactersAssemblyName.exe`, but when executing the exe, the loading fails with this error.
```
The managed DLL bound to this executable: 'LongerThan64CharactersAssemblyNameLongerThan64CharactersAssembly', did not match own name 'LongerThan64CharactersAssemblyNameLongerThan64CharactersAssemblyName.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.
```
As it says `LongerThan64CharactersAssemblyNameLongerThan64CharactersAssembly` is 64 characters, so it does not read more than that.

I am using the SDK version 2.1.400. Tested with older versions of the SDK without luck.

**Comment by livarcocc** [comment]
This seems like an issue in the host, so moving this issue to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#4593
