### ISSUE TITLE
mongodb-org-server depends on libssl1.1 (>= 1.1.1); however:   Package libssl1.1 is not installed.

### ISSUE THREAD

**Issue by forinda** [dotnet/sdk#25441]
### Describe the bug
I have just installed `Ubuntu 22.04` and I quite can't get through to install mongodb in my system

### To Reproduce

```diff
- $ curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
$ wget -o https://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/5.0/main/binary-amd64/mongodb-org-server_5.0.8_amd64.deb
$ sudo dpkg -i mongo-org-server-*-*
$
```
Output
```sh
Selecting previously unselected package mongodb-org-server.
(Reading database ... 206194 files and directories currently installed.)
Preparing to unpack mongodb-org-server_5.0.8_amd64.deb ...
Unpacking mongodb-org-server (5.0.8) ...
dpkg: dependency problems prevent configuration of mongodb-org-server:
 mongodb-org-server depends on libssl1.1 (>= 1.1.1); however:
  Package libssl1.1 is not installed.

dpkg: error processing package mongodb-org-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 mongodb-org-server
```
Trying to install the missing package
`sudo apt install libssl1.1`
Output
```sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libssl1.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.1' has no installation candidate
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by der-eismann** [comment]
What exactly does this issue have to do with the dotnet SDK? Did you post this in the wrong repository?

**Comment by Erik-EFL** [comment]
1 - Download libssl1.1_1.1.1f-1ubuntu2_amd64.deb from official repository:

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb

2 - Install it:

sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

3 - Proceed with the installation of MongoDB:

sudo apt-get install -y mongodb-org

**Comment by marceloaborges** [comment]
It's works for me on debian 12
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb, then execute with de program installer. 
make download the installer .deb of mongodb on website and execute too.
