### ISSUE TITLE
Workloads: Feed authentication during install doesn't seem to work at all on macOS

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/sdk#25458]
dotnet SDK 6.0.300
Azure Artifacts Credential Provider 1.0.0 (.NET 6 build)

1. Configure https://github.com/Microsoft/artifacts-credprovider with a valid Azure DevOps package read/write token (confirmed by doing a restore from private feed).
2. Run `sudo dotnet workload install macos --source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json`

### Expected results

SDK coordinates with https://github.com/Microsoft/artifacts-credprovider to authenticate to https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json and requests workload packages from the feed (which may in turn pull them from any configured upstreams).

### Actual results

```
Failed to update the advertising manifest microsoft.net.sdk.tvos: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.sdk.android: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.sdk.maui: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.sdk.macos: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.workload.emscripten: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.sdk.ios: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
Installing workload manifest microsoft.net.sdk.tvos version 15.4.303…
Workload installation failed. Rolling back installed packs...
Workload installation failed: Failed to install manifest microsoft.net.sdk.tvos version 15.4.303: Unable to load the service index for source https://pkgs.dev.azure.com/MY_PROJECT/nuget/v3/index.json..
```

Unless there is some way to work around this, this should be considered a critical security issue. Projects should not have to use nuget.org (or other public feeds) directly to install workloads.

**Comment by marcpopMSFT** [comment]
@joeloff can you try this on the Mac?  Grace was about to start a bunch of Mac work so maybe she can try this out as well.

**Comment by joeloff** [comment]
Yeah, I can take a look, I only have terminal access to a Mac right now

**Comment by sandyarmstrong** [comment]
Any news on this?

**Comment by sandyarmstrong** [comment]
@marcpopMSFT This continues to be a problem, forcing a violation of Microsoft's guidance on using multiple nuget feeds.

**Comment by nagilson** [comment]
There's a workaround for this, let me know if this doesn't work:
```
Do not provide the --source option. Instead, add the source in a nuget.config at the project level. You do not need to provide the key name in the configfile option either.
```

```xml
<configuration>
  <packageSources>
    <clear />
    <add key="source_name" value="https://pkgs.dev.azure.com/org/source/_packaging/source_name/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

But at the same time, this may not actually be how `--source` was intended to work with `workload install`, which is confusing as it's not how the other commands work. The documentation says it accepts a URI but @joeloff and I took a look and this may only actually work if you have the packages installed locally and provide `--source` a path to those local packages. We should look into this further to discuss.

**Comment by sandyarmstrong** [comment]
I believe at the time I filed this, we were seeing basically the same problems using your suggested approach. The command complained that the packages couldn't be found in the feed, even though upstreams were configured correctly. Which is why we took the approach of specifying feeds explicitly using `--source`.

I'll retest later this week to see if it's still a problem.

**Comment by nagilson** [comment]
That happened for me while trying to reproduce the issue but didn't occur when `--source` was removed. It seems like it was ``--source` looking for an updated semantic version of the workload that didn't exist. We will probably talk about this as a team tomorrow with people who have more workloads expertise and historical knowledge and try to get back to you.

**Comment by nagilson** [comment]
Update: `--source` worked for me on 7.0.200. though the code in the SDK here could use a LOT of love it does seem to do the trick. I had to append `--interactive` to the end of the command the first time as the guide in https://github.com/Microsoft/artifacts-credprovider stated to get it to work, without that I get your error. 

```go
$ dotnet workload install macos --source [REDACTED] --interactive

[REDACTED] 
Advertising manifest not updated. Manifest package for microsoft.net.sdk.testworkload doesn't exist.
Skipping NuGet package signature verification.
Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.android version 33.0.0-rc.1.151…
[REDACTED]
Garbage collecting for SDK feature band(s) 7.0.200...
Successfully installed workload(s) macos.
```

In addition, the point of failure for `Unable to load the service index for source` doesn't appear to be in the SDK. I am willing to work with them to discuss if you are able to reproduce this error still. But I will move this to artifacts/credprovider. Thank you @sandyarmstrong for being patient with us.

**Comment by nagilson** [comment]
Also though, perhaps this is a sign we need to improve the error handling for `--source` as it is currently rather confusing... I will create an issue for that.

**Comment by sandyarmstrong** [comment]
For what it's worth, our team configures `VSS_NUGET_ACCESSTOKEN` and `VSS_NUGET_URI_PREFIXES` environment variables for the credential provider, so `--interactive` is not required in our workflow (which is good since we wouldn't want that for CI anyway).

I have moved our tooling to use `--configfile` and it seems to be working for people now. I can reopen this or open a new issue if we run into problems down the line (perhaps when we inevitably start consuming private workload builds again in the future).

**Comment by nagilson** [comment]
Makes sense, I wonder if the environment variables are related. I'm glad to hear you got something working and appreciate your responsiveness. I'll close this; if you end up making an issue in https://github.com/microsoft/artifacts-credprovider feel free to cc myself and Marc.
