### ISSUE TITLE
Send Hot Reload message from C# in own app to browser reload script

### ISSUE THREAD

**Issue by krompaco** [dotnet/sdk#25466]
### Is your feature request related to a problem? Please describe.
I have a use case where the developer workflow would be much improved if I could send a signal to the browser to reload the current URL in the same way as it does on a change in a .cshtml-file.

For example I could have a FileSystemWatcher monitoring some folder outside of the solution directory and I want to reload the current URL in the browser when a file is changed.

### Describe the solution you'd like
I've browsed around the code a little bit but hard for me to see an appropriate API design. Something public under `Microsoft.AspNetCore.Components.HotReload` or a service could have an `InvokeReloadMessage()` or similar.

Of course the developer could do some null checking and be inside a debug condition but it would be nice if the method could do all needed context checks internally.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mkArtakMSFT** [comment]
Note, that you can have your own endpoint within your app to achieve the same (essentially similar logic to what hot reload does today)
