### ISSUE TITLE
Publishing netcoreapp classlib as self-contained produces broken apphost

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#2550]
Repro (SDK 2.1.500):
```
mkdir cl2
cd cl2
dotnet new classlib -f netcoreapp2.1
dotnet publish --self-contained -r win-x64
```

The above will produce an output folder which looks basically like a standalone app. It will have the runtime, the framework, everything in one folder. This alone is somewhat weird, as it's unclear what a stand-alone classlib should actually look like.

On top of that the SDK will also produce `apphost.exe` into the output. Please note that the file is always called `apphost.exe` regardless of the name of the project. Trying to run it produces:
```
This executable is not bound to a managed DLL to execute. The binding value is: 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2'
```

I would expect the SDK to fail with these options, as there doesn't seem to be a good way to produce a self-contained classlib.

This is related (at least on the behavior side) with #2549 .

**Comment by livarcocc** [comment]
Closing this issue in favor of https://github.com/dotnet/sdk/issues/2549 as both share the same proposed solution. Fail to publish with self-contained for a library.
