### ISSUE TITLE
Decide when an apphost should be created

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#2553]
Framework-dependent apphost via `/p:UseAppHost=true` was implemented in https://github.com/dotnet/sdk/pull/2282, and https://github.com/dotnet/sdk/pull/2462 made `UseAppHost=true` by default. The result is that `dotnet publish --self-contained false --rid win-x64`, for example, produces a framework-dependent app with an apphost. See some related discussion in https://github.com/dotnet/cli/pull/9460 about exposing this via a --mode option. AFAIK the conclusion was that `--self-contained false --rid win-x64` will be the way to get a framework-dependent apphost.

The remaining question is:
- Should we ever generate an apphost when no rid was specified? This was suggested in https://github.com/dotnet/sdk/issues/1899#issuecomment-418901033.

This might reduce to
- Should we set the RID implicitly in some circumstances (wpf/winforms for example)?

**Comment by peterhuene** [comment]
I'm currently tracking the work to enable this feature in https://github.com/dotnet/cli/issues/10043.

**Comment by nguerrera** [comment]
I believe this is done. We picked defaults.
