### ISSUE TITLE
Make apphost generation work correctly during incremental build

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#2554]
The apphost generation currently will not overwrite an existing apphost. The result is that changing properties that influence the apphost (setting the target to WinExe/Exe, or adding resources to the managed dll that get copied over to the apphost via https://github.com/dotnet/sdk/pull/2545) won't result in a new apphost being created for incremental builds, which seems incorrect.

See the discussion in https://github.com/dotnet/sdk/pull/2467 and the related issue https://github.com/dotnet/sdk/issues/2473.

**Comment by nguerrera** [comment]
I wonder if we can actually solve this on top of #2545 with just use  `Inputs="$(IntermediateAssembly)" Outputs="$(ApphostDestinationPath)"` on _CreateAppHost + removing the File.Exists check. If the output type changes, the managed assembly will also change. Are there other properties that can impact the apphost? 

cc @peterhuene

**Comment by rainersigwald** [comment]
If there are additional properties or items that matter beyond the assembly, you can use a pattern like we do for C#: collect all relevant properties into an item and write its hash to a file with `WriteOnlyWhenDifferent="True"`.

See https://github.com/Microsoft/msbuild/blob/90506c8f6c5e4b82a09bafa6ae62a41e9e7367bb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3404-L3431 (right now that only does items but you could add properties too.

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/2413/files#diff-fc9ca72fce3be7d1f0119f6666a307bdR148

I think genshim's incremental build is correct. Normal apphost should be similar to that

**Comment by nguerrera** [comment]
It should be similar to that if necessary, but I think the standard apphost might be a pure function of the managed assembly.
