### ISSUE TITLE
AppHost intermediate path should use $(IntermediateOutputPath)

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2555]
See https://github.com/dotnet/sdk/pull/2545/files#r220762612

> We should use $(IntermediateOutputPath), not $(BaseIntermediateOutputPath)\$(TargetFramework)\$(RuntimeIdentifier).
>
> Also, do we need the host sub-folder.
> 
> $(IntermediateOutputPath) also has logic to ensure a trailing slash and it is recommended to use $(IntermediateOutputPath)something and not $(IntermediateOutputPath)\something. This avoids ugly looking paths with > double and mixed slashes and it also prevents the case where you a misspelled variable during development ends up writing to the root of your drive instead of relative to CWD.

**Comment by sbomer** [comment]
Fixed by https://github.com/dotnet/sdk/commit/9e5b84ba1438d28f7affb81e312268f20e070eae
