### ISSUE TITLE
NETSDK1060 Error when build in linux 

### ISSUE THREAD

**Issue by Genuineh** [dotnet/sdk#25605]
### Describe the bug
I got NETSDK1060 error when i build in wsl2(arch linux)
![image](https://user-images.githubusercontent.com/38518057/170021249-e9e54c6d-2486-47ad-a2e3-b6b248209492.png)
But I fix it by updating error row 'home/jerry/TL.CodeReView/WiqunAnalyzer/WiqunAnalyzer.csproj*/1.0.0' to 'WiqunAnalyzer/1.0.0'.

### To Reproduce
[solution.zip](https://github.com/dotnet/sdk/files/8762278/solution.zip)
unzip "solution.zip" and run "dotnet build TL.CodeReView/WiqunAnalyzer.CLI/WiqunAnalyzer.CLI.csproj"

### Exceptions (if any)
/usr/share/dotnet/sdk/6.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1060: Error reading assets file: Error loading lock file '/home/jerry/TL.CodeReView/WiqunAnalyzer.CLI/obj/project.assets.json' : 'home/jerry/TL.CodeReView/WiqunAnalyzer/WiqunAnalyzer.csproj*/1.0.0' is not a valid version string. (Parameter 'value') [/home/jerry/TL.CodeReView/WiqunAnalyzer.CLI/WiqunAnalyzer.CLI.csproj

#### linux version
cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo

#### dotnet info
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    49861cb924

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.100 [/usr/share/dotnet/sdk]
  6.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by gao-artur** [comment]
Any update here? Getting the same error.

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn-sdk/issues/718
