### ISSUE TITLE
VisualStudioWorkloads is not source-build compatible

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#25616]
VisualStudioWorkloads requires a reference to Microsoft.VisualStudio.Setup.Configuration.Interop which is not something currently source-built therefore it is considered a prebuilt.  Looking at the [PR that introduce the reference](https://github.com/dotnet/sdk/commit/7e0c4280a712ce68ab2105c07a0ceb6a05609725), it looks like this code path is only used on Windows.  Is is possible to conditionally compile this code for Windows?

cc @joeloff

**Comment by MichaelSimons** [comment]
@joeloff - is this something that could get fixed for preview 7?  We are trying to get to zero source-build prebuilts by then.

**Comment by joeloff** [comment]
Oh, yes, we should try and get this done for preview7

**Comment by joeloff** [comment]
Originally this code was fairly isolated, but it's now becoming more integrated inside other commands and other SDK pieces like templates. Most of this is happening in 6.0 and slowly flowing into main, but I'll keep you posted.

**Comment by MichaelSimons** [comment]
This issue has been resolved.  Closing
