### ISSUE TITLE
project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'

### ISSUE THREAD

**Issue by andriysavin** [dotnet/sdk#2563]
I have a .Net Core console app (meaning it's built using .NET Core SDK) which targets `net471`, and references a `netstandard2.0` library project. I'm trying to publish it to an Azure WebJob using VS Publish command from project context menu, and getting error like this after publish starts:

> `
> C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1005: Assets file 'C:\Code\Temp\TestAzureDeployBug\ClassLibrary\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. [C:\Code\Temp\TestAzureDeployBug\ClassLibrary\ClassLibrary.csproj]
> `

If I change target framework to `netcoreapp2.1` the error doesn't happen.

NuGet version: 4.6.0
dotnet.exe --version: 2.1.402
VS version: 15.8.5
OS version: win10 1803

Link to the sample project: [https://1drv.ms/u/s!AuaAKPMkiTEAxrB3CJOUHMFvz2cq2Q](https://1drv.ms/u/s!AuaAKPMkiTEAxrB3CJOUHMFvz2cq2Q) 
Note that I removed publish profile, and you need to create one for you Azure AppService.

**Comment by livarcocc** [comment]
Does this work if you publish from the command line using `dotnet publish`?

**Comment by andriysavin** [comment]
@livarcocc Yes, it works for `dotnet publish`, and for publish to folder from VS.
