### ISSUE TITLE
"warning NETSDK1179" shows up even though `--self-contained` is specified along with `--runtime` with .NET 7.3-preview.4

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/sdk#25644]
### Describe the bug

"warning NETSDK1179" shows up even though `--self-contained` is specified along with `--runtime` with .NET 7.3-preview.4

### To Reproduce

1. Clone the PowerShell repo: https://github.com/PowerShell/PowerShell
2. Make sure the .NET SDK 7.0.100-preview.4.22252.9 is installed an available in `PATH` env variable.
3. Run `cd src\powershell-win-core` from the repo top directory
4. run `dotnet publish /property:GenerateFullPaths=true /property:ErrorOnDuplicatePublishOutputFiles=false /property:IsWindows=true --configuration Debug --framework net7.0 --runtime win7-x64 --self-contained /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop` to build

You will see the warnings as shown in the below screenshot, even though the `dotnet publish` command has `--runtime win7-x64 --self-contained` specified.

![image](https://user-images.githubusercontent.com/127450/170333518-21cd1bf3-96f3-4228-acdd-7b6222155ac1.png)

**Comment by baronfel** [comment]
This should be fixed in the next 6.0.3xx release, and flow into 7.0.100-preview.5. It was fixed [here](https://github.com/dotnet/sdk/pull/25367).
