### ISSUE TITLE
Error "Unable to find package about 5.0.18" when creating 5.0 project on VS 17.0/17.2 VAL build which carries 5.0.17 runtime

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#25672]
Affected Branch: D17.0.11/d17.2
Affected Build: VS 17.0.11/17.2 VAL build
Affected Product Language:

Steps to reproduce:

1.  File -> New -> Project-> Console App(.Net) and then select .NET5.0 on Additional information dialog to create.

2. Check the error list displaying after project is created.

Expected Result:
No error displays

Actual Result:
"Unable to find package about 5.0.18" display in error list.
![image](https://user-images.githubusercontent.com/65637796/170665414-0b269cc0-1659-42a1-9090-fdce782609c5.png)

In CLI,  issue also happen
![image](https://user-images.githubusercontent.com/65637796/170665264-dbe88be4-7768-46c1-84da-1343cf64db0c.png)

dotnet --info
![image](https://user-images.githubusercontent.com/65637796/170665340-dd1f0458-16bc-4f98-bcbe-09912c32fafe.png)

**Comment by Jiangpeng14** [comment]
repro on VS Mac 17.0.1
![Screen Shot 2022-05-27 at 16 42 23](https://user-images.githubusercontent.com/84758135/170666373-3325f7bf-6f16-44e4-b90e-22c4da07eac4.png)

**Comment by yinjiehe01** [comment]
Not repro on Windows, but repro on Mac.

**Comment by WenJunJi01** [comment]
Today we test some Setup scenarios, and the details result as bellow:
1) Val 16.11+ Val 17.0 -> Repro 
2) Val 16.11 + 17.3 P2(main) -> Repro in CLI, not repro on VS
3) Val 16.11 + Val 17.2 + 17.3 P2(main) -> Not repro
4) Val 17.0 + 17.3 P2(main) -> Repro

The timestamp of file: **dotnet\sdk\6.0.301\Microsoft.NETCoreSdk.BundledVersions.prop**
![image](https://user-images.githubusercontent.com/87680983/171127925-c255e388-35ee-4373-a525-3e1c0564254f.png)

**Comment by mrward** [comment]
@marcpopMSFT VS Mac 17.0 and 17.1 are currently inserting the .NET 6.0.300 sdk.

**Comment by marcpopMSFT** [comment]
Thanks so I'm still confused as to how this reproed for the vendors with the newer build as it should be fixed in that build. I even installed new VAL build and couldn't repro though I didn't do the exact config above.

**Comment by yinjiehe01** [comment]
@marcpopMSFT I installed VS for Mac, 5.0.408 and 6.0.301 were installed stand-alone. The issue repro, when I created NET5.0 projects.
![Screen Shot 2022-06-01 at 09 30 17](https://user-images.githubusercontent.com/106043488/171310114-69c31c31-89fa-4427-85f5-71736607624e.png)

**Comment by yinjiehe01** [comment]
@marcpopMSFT I checked this issue  on VSM 17.0.1 with latest 6.0.301 build, it is not repro.
