### ISSUE TITLE
With .NET 6.0.301 installed, the sdk version for Maui/wasm-tools is displayed as "6.0.300" in dotnet workload list.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#25673]
Clean OS, Win10-x64 

1. Install the standalone .NET 6.0.301 x64 SDK 

2. Execute: dotnet workload install wasm-tools --skip-manifest-update
3. dotnet workload install maui --skip-manifest-update
4. Execute: dotnet workload list 
5. Check the contents in workload list

Actual Result:
SDK version display 6.0.300
![image](https://user-images.githubusercontent.com/65637796/170673676-e1de1c61-ee08-49af-8669-119a5af3d441.png)

**Comment by marcpopMSFT** [comment]
This is by design. We install the workloads by feature band rather than specific SDK version as workloads can version outside of the SDK (for example, maui shipped GA and RC2 in May with no corresponding SDK release so they were just 6.0.300 releases of the workloads).
