### ISSUE TITLE
Add fallback root certificate bundle

### ISSUE THREAD

**Issue by dtivel** [dotnet/sdk#25686]
A root certificate bundle valid for code signing and timestamping needs to be added to the .NET SDK so that related features have a valid root store on platforms that do not have a root store valid for general-purpose code signing and timestamping.

The relevant specifications are:
*  [Re-enabling signed NuGet package verification](https://github.com/dotnet/designs/blob/main/accepted/2021/signed-package-verification/re-enable-signed-package-verification.md)
*  [Re-enabling Cross-Platform NuGet Signed Package Verification Technical Specification](https://github.com/dotnet/designs/blob/main/accepted/2021/signed-package-verification/re-enable-signed-package-verification-technical.md)

CC @richlander, @marcpopMSFT, @joeloff

**Comment by richlander** [comment]
@omajid @wiswaud

FYI: We're about to add the code signing bundle to the SDK, as I previously told you. As I also said, we'll be sharing the same content at another -- more official -- location (microsoft org) very shortly.
