### ISSUE TITLE
PublishTrimmed is set too late when AOT publishing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/sdk#25740]
```
dotnet new console
dotnet publish -r win-x64 -c Release /p:PublishAot=true
```

Running the above will produce following warning:

```
/_/src/libraries/System.Private.CoreLib/src/System/Resources/ManifestBasedResourceGroveler.cs(239): Trim analysis warni
ng IL2026: System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(Stream,Assembly): Using member 'System.Reso
urces.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData(Stream,String,String,ResourceManagerMediat
or)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The CustomRe
sourceTypesSupport feature switch has been enabled for this app which is being trimmed. Custom readers as well as custo
m objects on the resources file are not observable by the trimmer and so required assemblies, types and members may be
removed. [C:\publishaot2\publishaot2.csproj]
```

The ILCompiler targets set PublishTrimmed to true, but I assume they get included too late from the SDK to affect feature switches. We should do this propagation very early.

If I instead publish as `dotnet publish -r win-x64 -c Release /p:PublishAot=true /p:PublishTrimmed=true` there's no warning, but I shouldn't have to do that.

Cc @dotnet/ilc-contrib

**Comment by agocke** [comment]
FYI @LakshanF, looks like hello world is generating warnings due to feature switch issues

**Comment by MichalStrehovsky** [comment]
> This seems to be due to the fact we set the feature switch, [EnableUnsafeBinaryFormatterSerialization](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L49), to false in the native targets file instead of the `CustomResourceTypesSupport` feature switch being set to false.


This is set in Microsoft.NET.ILLink.targets:

https://github.com/dotnet/sdk/blob/b15a88fb330548bf447d2df4936c4367db346a1a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L38

The default is always false when trimming. We do not want to be duplicating trimming defaults in these targets.

I think the actual problem here (and the reason why the warning disappears if one sets `PublishTrimmed` to true in the project file) is that ILCompiler.targets (that set PublishTrimmed to true) are included after ILLink.targets. Can we reorder them (or do something else that makes sure PublishTrimmed is set when PublishAot is set)?

https://github.com/dotnet/sdk/blob/ad1ca90ad286288970a4ae1ec77e85848fef5a24/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L1157-L1158
