### ISSUE TITLE
[ApiCompat] Enable nullable reference types

### ISSUE THREAD

**Issue by smasher164** [dotnet/sdk#25760]
Enabling it library-wide currently shows some errors, so we should work towards this as a goal.
We can at least start with enabling it for the rules.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/sdk/pull/25765 enables nullability for the other layers (PackageValidation and Compatibility). I agree that we should start with the ApiCompatibility rules and then enable it for the other types as well.
