### ISSUE TITLE
dotnet workload update --print-download-link-only --sdk-version  with 6.0.400 do not return results for previous sdk band

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#25774]
### Describe the bug
`dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10  --temp-dir ~/Library/Caches/VisualStudio/17.0/TempDownload/  --configfile ~/.nuget/NuGet/NuGet.Config` is used by vsmac updater to get new urls to download updates to .NET6 workloads
The metadata of workloads installed with 6.0.300 is in /usr/local/share/dotnet/metadata/workloads/6.0.300/InstalledWorkloads/maui  and this is not recognized when the command is executed using 6.0.400. 
Refer https://github.com/dotnet/sdk/issues/25772
Log: https://gist.github.com/GouriKumari/e6174a7281eabf760b374a24ef72d628
User is asked to run the command with "--from-previous-sdk" and this throws an exception. 
Log: https://gist.github.com/GouriKumari/05f5ec093ffdf2422b9d84805783e534
Also, this argument isn't supported by vsmac since it downloads and installs updates at the same time 

### To Reproduce
Env: Apple Silicon
Install 6.0.300 and install maui 6.0.300 rc2 bits using
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.2.json
Install 6.0.400-preview.22301.10
Execute 
` dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10  --temp-dir ~/Library/Caches/VisualStudio/17.0/TempDownload/  --configfile ~/.nuget/NuGet/NuGet.Config `
and
` dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10  --temp-dir ~/Library/Caches/VisualStudio/17.0/TempDownload/  --configfile ~/.nuget/NuGet/NuGet.Config --from-previous-sdk`

### Exceptions (if any)

(https://gist.github.com/GouriKumari/05f5ec093ffdf2422b9d84805783e534)

### Further technical details
dotnet info ->https://gist.github.com/GouriKumari/b339127cb6649a829ffc9955b50ce809
This command is initially used by VSMac updater to get manifest url to download new NET6 updates. The command will return no result since there is no workload installed within 6.0.400. 
CrossBand update do not work and there is a different bug already reported on this.

**Comment by marcpopMSFT** [comment]
@GouriKumari how does this differ from https://github.com/dotnet/sdk/issues/24335?

**Comment by GouriKumari** [comment]
This is same as  https://github.com/dotnet/sdk/issues/24335.  You can close it as a duplicate.
