### ISSUE TITLE
dotnet workload list --machine-readable  with 6.0.400 preview do not list installed workloads from previous sdk band

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#25772]
### Describe the bug
The .NET6 workloads installed with 6.0.300 is not recognized while executing `dotnet workload list --machine-readable --sdk-version 6.0.400-preview.22301.3` since the metadata to check whether the workloads are installed in the 6.0.300 path and not in the 6.0.400 path, 
eg: /usr/local/share/dotnet/metadata/workloads/6.0.300/InstalledWorkloads/maui

For vsmac updater,  since workloads installed by 6.0.300 is not detected by 6.0.400,  the next command to get the manifest urls won't be called.

### To Reproduce
Env: Apple Silicon 
Install 6.0.300 and install maui 6.0.300 rc2 bits using 
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.2.json  
Install 6.0.400-preview.22301.10  
Execute /usr/local/share/dotnet/dotnet workload list --machine-readable --sdk-version 6.0.400-preview.22301.3

Expected Result:  NET6 workloads listed in user machine should be listed
Actual Result: Since .NET6 workloads installed are within  /usr/local/share/dotnet/metadata/workloads/6.0.300/InstalledWorkloads/maui and  this is not recognized by 6.0.400. Workloads installed are not listed.
Log: https://gist.github.com/GouriKumari/a62c85f989a187d7f0ad48c38ccc441a
### Further technical details
- dotnet info ->https://gist.github.com/GouriKumari/b339127cb6649a829ffc9955b50ce809
-  This command is initially used by VSMac updater to check if any .NET workloads are installed and then offer updates. The command will return no result since there is workload installed within 6.0.400.

**Comment by marcpopMSFT** [comment]
@gkulin will your changes for https://github.com/dotnet/sdk/issues/24335 help here or is this going to require additional changes?

**Comment by dsplaisted** [comment]
Per discussion, it sounds like what we should support is the `--from-previous-sdk` option (or similar), so that the VS for Mac updater doesn't need to know which previous SDK band had workloads installed.

**Comment by marcpopMSFT** [comment]
@GouriKumari is this still needed?

**Comment by GouriKumari** [comment]
yes, this is needed.

**Comment by marcpopMSFT** [comment]
Can someone join the workloads meeting next Monday to talk us through why this is still needed? I thought VSMac was moving towards a rollback file install mechanism.  Is that not coming in soon?

**Comment by GouriKumari** [comment]
I checked this with Kyle and our current decision is to move to .NET Workload insertion process. Closing this bug on that plan.
