### ISSUE TITLE
dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#25773]
<!--

### Describe the bug
VSMac updater uses `dotnet workload update --print-download-link-only --sdk-version` to return .NET workload manifest urls to be downloaded.  However if users have .NET6 6.0.300 workloads installed, any updates to it won't be downloaded by 
`dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10` since  update of a previous band is supported only by passing --from-previous-sdk      which vsmac  updater do not support.

### To Reproduce
Install 6.0.300 and install maui 6.0.300 rc2 bits using
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300/rc.2.json
Install 6.0.400-preview.22301.10
Execute `dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10  --temp-dir ~/Library/Caches/VisualStudio/17.0/TempDownload/  --configfile ~/.nuget/NuGet/NuGet.Config`   will return 

No results are returned and user is asked to execute with `--from-previous-sdk `.
Log: https://gist.github.com/GouriKumari/e6174a7281eabf760b374a24ef72d628

Execute `dotnet workload update --print-download-link-only --sdk-version 6.0.400-preview.22301.10  --temp-dir ~/Library/Caches/VisualStudio/17.0/TempDownload/  --configfile ~/.nuget/NuGet/NuGet.Config --from-previous-sdk`

An expection is thrown. 
Log : https://gist.github.com/GouriKumari/05f5ec093ffdf2422b9d84805783e534

### Further technical details
dotnet info ->https://gist.github.com/GouriKumari/b339127cb6649a829ffc9955b50ce809
This command is initially used by VSMac updater to download workloads that have updates .The command will return no result since there is workload installed within 6.0.400.

**Comment by marcpopMSFT** [comment]
@GouriKumari Did you hit submit too soon? This looks like you started to write up https://github.com/dotnet/sdk/issues/25774?

**Comment by GouriKumari** [comment]
yes, I will close this.
