### ISSUE TITLE
The --launch-profile option of `dotnet run` and `dotnet watch run` should fallback to a case-insensitive match if a case-sensitive match isn't found

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#25868]
Today, `dotnet run --launch-profile profilename` and `dotnet watch run --launch-profile profilename` are case-sensitive and if a matching profile is not found in `launchSettings.json` an error message is displayed but the project is run anyway, e.g.:

**launchSettings.json**

```json
{
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5130",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "HTTPS": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:7175;http://localhost:5130",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

```console
$ dotnet run --launch-profile https
The launch profile "https" could not be applied.
A profile with the specified name could not be found or is not a valid JSON object.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
```

It would be more user-friendly in cases like this to simply fallback to a case-insensitive match if a case-sensitive match is not found first.

**Comment by DamianEdwards** [comment]
VS shows them as distinct profiles 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/249088/173685152-fe7c0a4d-de71-415e-bbe7-32361e2ab0a2.png">

**Comment by baronfel** [comment]
What about something like this:
* if the name is case-insensitively unique (i.e. `http` in your image above), then accept any case
* if the name has case-sensitive variants, require case-sensitive matches or else error
* completions always suggest the user-entered spellings exactly

**Comment by DamianEdwards** [comment]
Yep that's inline with what I was thinking (fallback to case-insensitive if case-sensitive is not found).

**Comment by nagilson** [comment]
>  I do think this would be a good area for @nagilson after he tackles the various Release configuration/RID inference changes for 7 if nothing else crazy pops up.

Ah yes, something crazy  _definitely_ did NOT pop up. This was a good suggestion and while I'm sorry for the delay, glad I finally had time to work on this.

**Comment by nagilson** [comment]
This should be resolved by https://github.com/dotnet/sdk/pull/28908, lmk if you have any feedback!
