### ISSUE TITLE
For .Net Core 3.0, in "Application" tab of project properties page, the highest optional "Target framework" is “.NET Core 2.2”, not ".NET Core 3.0". 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/sdk#2593]
_From @YunWeiaa on October 18, 2018 6:51_

### Description:
1. After installing .net core SDK 3.0.100-alpha1-009676 with Runtime 3.0.0-preview1-27016-04 against d16.0stg
2. I create a new .net core project via VS and open property pages, the default TFM is ".NET Core 2.1". 
3. If I want to change the higher target fx, it only has “.NET Core 2.2”, not ".NET Core 3.0". 
![default netcore](https://user-images.githubusercontent.com/33921754/47135902-8cb74e80-d2e4-11e8-9038-1059d7a90726.jpg)
4. When I manually change the target fx to 2.2, it shows the error `NU1103: Unable to find a stable package Microsoft.NETCore.App with version (>= 2.2.0)` as below:
![net30](https://user-images.githubusercontent.com/33921754/47136247-b15ff600-d2e5-11e8-899e-0d02c3700df9.png)

### Test Environment:
D16.0stg/28216.3001 (16.0 preview 1.0) + CLI/SDK [3.0.100-alpha1-009676](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe)
dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009676
 Commit:    e5ae52d155

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009676\

Host (useful for support):
  Version: 3.0.0-preview1-27016-04
  Commit:  3b8753ee45

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009676 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27006-1 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-27016-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


```

_Copied from original issue: dotnet/project-system#4137_

**Comment by Pilchie** [comment]
@livarcocc  - the list of supported TFMS needs to be updated.

**Comment by livarcocc** [comment]
@Pilchie roger that.

**Comment by livarcocc** [comment]
@nguerrera can you take care of this?

**Comment by nguerrera** [comment]
Yes. I thought I added test coverage to prevent this. But it must not be working as I expected or I'm remembering something different but similar. I'll close the test gap.

**Comment by nguerrera** [comment]
The code flow still hasn't happened, but @dsplaisted is working on it.

I am closing this since the bug is fixed and just needs to flow to core-sdk.
