### ISSUE TITLE
Inconsistent perms on some directories SDK writes into /tmp

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#26022]
Repro.
1. Create Ubuntu 20.04 WSL2 instance.
2. Install .NET 6.0 SDK per the online instructions. 
3. Create a project with `dotnet new console`

Result:
```sh
root@danmoseL:~/proj/2# ll /tmp | grep dotnet
drwxrwxrwx  3 root root 4096 Jun 14 08:15 .dotnet/
drwxr-xr-x  3 root root 4096 Jun 14 08:07 dotnet-installer/
drwxr-xr-x  3 root root 4096 Jun 14 08:16 dotnet-sdk-advertising-temp/
```

I believe some or all of these come from the SDK. Can these be limited to just the current user? That would likely mean perms of 0700. The perms above are 0755 and 0777.

I didn't look at anything within the folders.

Context: we are inconsistent with the perms we apply to files and folder we write to /tmp. @agocke [made](https://github.com/dotnet/runtime/pull/70585) a first start at writing down [guidance](https://github.com/dotnet/runtime/blob/main/docs/design/security/unix-tmp.md) and I'm opening a couple of bugs to see whether this guidance makes sense. We can modify it if necessary.

**Comment by marcpopMSFT** [comment]
These should be fixed now with the October release.
