### ISSUE TITLE
WebAssembly workload should check if `python` is available, when installing on Linux

### ISSUE THREAD

**Issue by radical** [dotnet/sdk#26050]
- `wasm-tools` workload does not have a Python pack for linux, and instead depends on system installed python. The reason for this is how `emscripten` sdk is structured. Also, we need a minimum python3.6 to be available.
- Users run into this often when using the workload in a docker container, for example. They expect that installing `wasm-tools` would get all the dependencies.
- We don't have to install it, but the sdk should emit a warning if python is missing when installing the workload with `dotnet workload install wasm-tools`.

cc @lewing

**Comment by lewing** [comment]
This can happen in WorkloadManifest.targets
