### ISSUE TITLE
Allow Runtime/Ref packs to contain multiple Target Platforms

### ISSUE THREAD

**Issue by Redth** [dotnet/sdk#26069]
### Is your feature request related to a problem? Please describe.
Currently MAUI has a number of different Runtime and Ref packs (Controls, Core, Essentials) with variants for each target platform (any, ios, maccatalyst, android, tizen, win).

This results in some 36 different packages:

```
Microsoft.Maui.Controls.Ref.android
Microsoft.Maui.Controls.Ref.any
Microsoft.Maui.Controls.Ref.ios
Microsoft.Maui.Controls.Ref.maccatalyst
Microsoft.Maui.Controls.Ref.tizen
Microsoft.Maui.Controls.Ref.win
Microsoft.Maui.Controls.Runtime.android
Microsoft.Maui.Controls.Runtime.any
Microsoft.Maui.Controls.Runtime.ios
Microsoft.Maui.Controls.Runtime.maccatalyst
Microsoft.Maui.Controls.Runtime.tizen
Microsoft.Maui.Controls.Runtime.win
Microsoft.Maui.Core.Ref.android
Microsoft.Maui.Core.Ref.any
Microsoft.Maui.Core.Ref.ios
Microsoft.Maui.Core.Ref.maccatalyst
Microsoft.Maui.Core.Ref.tizen
Microsoft.Maui.Core.Ref.win
Microsoft.Maui.Core.Runtime.android
Microsoft.Maui.Core.Runtime.any
Microsoft.Maui.Core.Runtime.ios
Microsoft.Maui.Core.Runtime.maccatalyst
Microsoft.Maui.Core.Runtime.tizen
Microsoft.Maui.Core.Runtime.win
Microsoft.Maui.Essentials.Ref.android
Microsoft.Maui.Essentials.Ref.any
Microsoft.Maui.Essentials.Ref.ios
Microsoft.Maui.Essentials.Ref.maccatalyst
Microsoft.Maui.Essentials.Ref.tizen
Microsoft.Maui.Essentials.Ref.win
Microsoft.Maui.Essentials.Runtime.android
Microsoft.Maui.Essentials.Runtime.any
Microsoft.Maui.Essentials.Runtime.ios
Microsoft.Maui.Essentials.Runtime.maccatalyst
Microsoft.Maui.Essentials.Runtime.tizen
Microsoft.Maui.Essentials.Runtime.win
```

Now each of these packages gets turned into 3 separate MSI's and MSI nuget packages.

This results in a grand total of `108 (MSI) + 36 (NuGet) = 144` **144** nuget packages.

This is not ideal for a variety of reasons:
1. It's just a LOT of packages on NuGet - any time we need to do anything like delist a series, publish, etc, it's just a more expensive operation, and I'm sure NuGet wouldn't be sad if we didn't have so many packages being published.
2. Install time is greater, it's just more packages and msi's to process
3. Cognitive load is higher in terms of understanding what these things are, debugging issues, and overall complexity this creates for users and troubleshooting. It might look the same after install but it makes it much harder for users to conceptually understand how things fit together and where they come from.

### Describe the solution you'd like

I know pack groups are in the works, and this should at least reduce the number of .msi's produced which is a great improvement, but I think it is still worth solving for at least a couple of the aforementioned reasons.

Ideally, a single nuget package for each of these three areas (Controls.Runtime, Controls.Ref, Core.Runtime, Core.Ref, Essentials.Runtime, Essentials.Ref) could support all of the target platforms within it.

Even better would be the ability to have Ref/Runtime in the same pack as well.

In our packs, we already use `ref`, `libs`, and `runtimes` folders with TFM subfolders just like a normal nuget (ie: `ref/net6.0-android31.0`), however it seems there's no metadata in the `data/FrameworkList.xml` file to specify the target platforms for these files.  Perhaps this file format could be enhanced to support this.

### Additional context

I think the original intent here was to ship smaller individual packages to save on installation size for when you don't need to pull down all of the different target platforms.  This is still potentially true in some cases, however for MAUI's 3 sets of ref/runtime packs, we're talking around **47mb** for _all_ target platforms for Core/Controls/Essentials combined.  We _could_ keep split this up but I suspect the savings are minimal and most people will opt for enough platforms for diminishing returns here.  Currently we don't support picking individual platforms at acquisition time anyway.

Interestingly Android is actually impacted negatively by this currently.  Take for instance their API 32 runtime packs:

```
Microsoft.Android.Runtime.32.android-arm
Microsoft.Android.Runtime.32.android-arm64
Microsoft.Android.Runtime.32.android-x64
Microsoft.Android.Runtime.32.android-x86
```

While there are some binaries that are specific to each of these architectures, they are < 1MB per architecture.  On the other hand, this structure (and maybe there's a better way to do this?) currently means we are duplicating the managed binaries which do not differ at all between these platforms for each, and _those_ happen to be **45MB**, so we have an extra **135MB** of otherwise unnecessary binaries here.

**Comment by akoeplinger** [comment]
Possibly related issue: https://github.com/dotnet/sdk/issues/24077

**Comment by marcpopMSFT** [comment]
@dsplaisted @jonathanpeppers @Redth what's the priority of this look like today?

**Comment by jonathanpeppers** [comment]
Since MAUI moved to NuGet packages, they are no longer using `FrameworkReference`, targeting/ref packs, etc. I think we can close this one.

However, I think this one is still relevant for the iOS/Android workloads: https://github.com/dotnet/sdk/issues/24077
