### ISSUE TITLE
Issue falling back to 6.0.300 manifests with 6.0.400 SDK

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#26112]
### Describe the bug

I have a pipeline I'm testing here: https://github.com/jonathanpeppers/maui-profiling/pull/17

A MAUI service release went out last week, such as:

* https://www.nuget.org/packages/Microsoft.NET.Sdk.Android.Manifest-6.0.300/32.0.415
* https://www.nuget.org/packages/Microsoft.NET.Sdk.Maui.Manifest-6.0.300/6.0.400
* https://www.nuget.org/packages/Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300/6.0.6
* https://www.nuget.org/packages/Microsoft.NET.Sdk.iOS.Manifest-6.0.400/15.4.414

Note that the iOS team went to 6.0.400, while all the other packs did not.

When I use the 6.0.400-preview.22316.6 .NET SDK, and `dotnet workload install maui --verbosity diag`, I see:

```
Advertising manifest not updated. Manifest package for microsoft.net.sdk.android doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.maui doesn't exist.
Advertising manifest not updated. Manifest package for microsoft.net.workload.mono.toolchain doesn't exist.
```

Then the actual packs installed are not the latest:

```
Installing pack Microsoft.Android.Sdk version 32.0.301...
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.312...
Installing pack Microsoft.NETCore.App.Runtime.Mono.android-arm version 6.0.5...
```

I can workaround the problem using a rollback file, like:

```json
{
  "microsoft.net.sdk.android": "32.0.415/6.0.300",
  "microsoft.net.sdk.ios": "15.4.414/6.0.400",
  "microsoft.net.sdk.maccatalyst": "15.4.414/6.0.400",
  "microsoft.net.sdk.macos": "12.3.414/6.0.400",
  "microsoft.net.sdk.maui": "6.0.400/6.0.300",
  "microsoft.net.sdk.tvos": "15.4.414/6.0.400",
  "microsoft.net.workload.mono.toolchain": "6.0.6/6.0.300",
  "microsoft.net.workload.emscripten": "6.0.4/6.0.300"
}
```

### To Reproduce

I would try the `dotnet-install.sh` script like I'm using here:

https://github.com/jonathanpeppers/maui-profiling/blob/dd0e9fedbfa2efc37521f92154b8be635f0f0fcd/azure-pipelines.yml#L103-L115

Then `dotnet workload install maui --verbosity diag` and compare the versions that it prints out.

### Further technical details

My example above is running on the AzDO hosted mac pool.

View a full build log at:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6308108&view=logs&j=96c3d711-2288-532e-87f7-1a666089720f&t=6ddd8843-495d-522d-23ae-e467869540a2&l=15

**Comment by ebariche** [comment]
We've been experiencing something very similar in GitHub actions on Windows using dotnet SDK 6.0.400-preview.22330.6, we're installing the SDK with `dotnet-install.ps1`, the only difference is that the rollback file doesn't help, it still fails.

The rollback file :
{
    "microsoft.net.sdk.android": "32.0.424/6.0.300",
    "microsoft.net.sdk.ios": "15.4.430/6.0.400",
    "microsoft.net.sdk.maccatalyst": "15.4.430/6.0.400",
    "microsoft.net.sdk.macos": "12.3.430/6.0.400"
}

The command :
dotnet workload install --from-rollback-file rollback.json android ios maccatalyst macos --source "https://api.nuget.org/v3/index.json"

Everything installs correctly but the android workload which falls back to 32.0.301

I printed the download urls out of curiosity and saw this :

Resolving package URLs for workload(s) android, ios, maccatalyst, macos...
Failed to resolve manifest package URL microsoft.net.sdk.android.

and then

![image](https://user-images.githubusercontent.com/33458222/180249152-49a3b30e-2cf2-48ee-ba31-8577e13896df.png)

Going out on a limb here but it looks like a problem with the FileBasedInstaller and SDK bands.

The NetSdkMsiInstallerClient doesn't behave exactly the same way. Printing the urls gives this :

Resolving package URLs for workload(s) android, ios, maccatalyst, macos...
Failed to resolve manifest package URL microsoft.net.sdk.android.

But the correct packs end up being installed.

Hopefully it's the same issue and doesn't add to the confusion

I'm attaching some evidence here, if it helps :

[log-issue-26112-ci.txt](https://github.com/dotnet/sdk/files/9160674/log-issue-26112-ci.txt)

[log-issue-26112-win10.txt](https://github.com/dotnet/sdk/files/9160681/log-issue-26112-win10.txt)

**Comment by jonathanpeppers** [comment]
I heard that a newer 6.0.400 SDK might have a fix, can you install a nightly `6.0.400-rtm.22364.21`?

**Comment by ebariche** [comment]
@[jonathanpeppers](https://github.com/jonathanpeppers), Thanks for the tip !

Ideally I wanted to mirror what is shipped in VS 17.3 Pre 3/4 ! But I'm willing to sell a kidney at this point so I'll give it a try :)

As an aside, are you guys moving out of 3xx soon ? Both for the Android SDK and MAUI ?

**Comment by jonathanpeppers** [comment]
Yes, the latest few builds on our release branch: 

https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet6/NuGet/Microsoft.NET.Sdk.Android.Manifest-6.0.400/versions/32.0.445%20sha.8d5cd7f

**Comment by ebariche** [comment]
@jonathanpeppers, 6.0.400-rtm.22364.21 works ! Thank you !

**Comment by gkulin** [comment]
> I heard that a newer 6.0.400 SDK might have a fix, can you install a nightly `6.0.400-rtm.22364.21`?

Does this address your originally filed issue then? Or would you still like for me to look into this? @jonathanpeppers

**Comment by jonathanpeppers** [comment]
I tried my PR again: https://github.com/jonathanpeppers/maui-profiling/pull/17

The issue now is we've shipped a 6.0.400 manifest package:
```
Installing workload manifest microsoft.net.sdk.android version 32.0.447…
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.android.manifest-6.0.400/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.android.manifest-6.0.400/index.json 93ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.android.manifest-6.0.400/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.android.manifest-6.0.400/index.json 91ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.android.manifest-6.0.400/32.0.447/microsoft.net.sdk.android.manifest-6.0.400.32.0.447.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.android.manifest-6.0.400/32.0.447/microsoft.net.sdk.android.manifest-6.0.400.32.0.447.nupkg 7ms
```
So I don't know if it will repro anymore...

If you know of a PR/fix that solved this issue, we can probably close this.

**Comment by marcpopMSFT** [comment]
@jonathanpeppers was this with a file-based install? Could this be related to when the file-based install was putting .300 manifests in a .400 folder and so couldn't successfully update them on install?

**Comment by jonathanpeppers** [comment]
Yes, this was a file-based install on macOS.

**Comment by marcpopMSFT** [comment]
If this was the file-based install, I am going to assume then that it was the bug that this PR fixed and it's now resolved and close it: https://github.com/dotnet/installer/pull/14134  Feel free to reactivate if you don't believe this is accurate.
