### ISSUE TITLE
Error when restore .Net Core 2.2 Console application via VS #26 

### ISSUE THREAD

**Issue by richaverma1** [dotnet/sdk#2617]
_From YunWeiaa on 10/23_ 

### **Steps to reproduce**

Create a new .net core console application via VS,
Restore

### **Expected behavior**

Restore succeeded with no warnings and no errors.

### **Actual behavior**

Error NETSDK1065 Cannot find app host for win-x64. win-x64 could be an invalid runtime identifier (RID). For more information about RID, see https://aka.ms/rid-catalog. 

![47351468-9a0c7880-d6ea-11e8-91af-5187ed30d329](https://user-images.githubusercontent.com/19596695/47449218-f3ba8480-d776-11e8-88e3-96bcac42bd92.png)

Note: When I modify the TargetFramework in .csproj file from netcoreapp3.0 to netcoreapp2.2 via CLI, it does not appear the error NETSDK1065, but dotnet restore failed with error NU1103: #10193

Environment data
CLI/SDK - 3.0.100-alpha1-009697 against d16.0stg
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009697
 Commit:    7365786612

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\

Host (useful for support):
  Version: 3.0.0-preview1-27018-05
  Commit:  7a7ca06512

.NET Core SDKs installed:
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009431 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009697 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27017-4 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27001-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-27018-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
@YunWeiaa I believe this has been addressed with more recent .NET Core SDK builds relating to apphost changes.  I'm going to close.  Please re-open if you're still able to reproduce.
