### ISSUE TITLE
undefined symbol: _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by sensiki** [dotnet/sdk#26260]
.net6 and .net7
dotnet publish -c Release -r linux-arm64 -o ../build -p:PublishSingleFile=true --self-contained true

root@OpenWrt:~# uname -a
Linux OpenWrt 5.4.188 #0 SMP PREEMPT Sat Apr 16 12:59:34 2022 aarch64 GNU/Linux

but run app get error
./ConsoleApp2: symbol lookup error: ./ConsoleApp2: undefined symbol: _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21

**Comment by sensiki** [comment]
ldd ./ConsoleApp2
linux-vdso.so.1 (0x0000ffffa7428000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x0000ffffa6a0e000)
	libdl.so.2 => /lib/libdl.so.2 (0x0000ffffa69fa000)
	libz.so.1 => /usr/lib/libz.so.1 (0x0000ffffa69d5000)
	librt.so.1 => /lib/librt.so.1 (0x0000ffffa69bd000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0000ffffa699a000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000ffffa688b000)
	libm.so.6 => /lib/libm.so.6 (0x0000ffffa67e0000)
	libc.so.6 => /lib/libc.so.6 (0x0000ffffa6669000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffa73f5000)

**Comment by sensiki** [comment]
已解决，更换了工具链

**Comment by xuyuxiu83** [comment]
能告诉我怎么解决的吗哥们
