### ISSUE TITLE
All invalid p2p references should result in warnings/errors

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#264]
We're moving to a model where builds via the command-line and Visual Studio are exactly the same, no different validation, no different warnings, etc.

The first step of this, is to push P2P validation to MSBuild indirectly via ResolveProjectReferences. The project system will then pick up these warnings/errors during builds and design-time builds and push them to the Error List and [stop blocking you from adding a reference](https://github.com/dotnet/roslyn-project-system/pull/595).

We already do some validating in the multi-TFM case, this bug is representing the work to do similar validation in the single-TFM case, and to make sure that we're erroring/warning in the right cases.

**Comment by dsplaisted** [comment]
The current behavior for invalid references between non-multitargeted projects using the .NET Sdk is that NuGet restore will fail, with a message like the following:

>One or more projects are incompatible with .NETStandard,Version=v1.4.
Project Dependency is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Project Dependency supports: netstandard1.5 (.NETStandard,Version=v1.5)

If you then do a build, you will not get a build error, but you will get this warning:
> Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3277	Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	SdkRefNetStandard	C:\Program Files (x86)\Microsoft Visual Studio\VS15_d15rel_25903.02\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1909	

The build should probably fail in this situation in addition to the restore, and shouldn't give a confusing warning about binding redirects.
