### ISSUE TITLE
Unify SDK & Runtime versions

### ISSUE THREAD

**Issue by rohith** [dotnet/sdk#2640]
I understand SDK & Runtime are two different things but the versioning among these when using dotnet core is a bit confusing for people. So, can there be a unified version of dotnet core?

![image](https://user-images.githubusercontent.com/5032439/47869486-1448a580-de2d-11e8-8718-65487e905a27.png)

When 2.2.0 is released can the version be applied to both SDK & Runtime as v2.2.0 rather than SDK having a different version of 2.2.100?

**Comment by livarcocc** [comment]
No. That's not possible. We have discussed this extensively. There is a write up of the reasons somewhere (@KathleenDollard do you have a pointer to the write up?).

We want to versions to match only on major.minor and never on patch, exactly not to give people the impression that the full version will ever align, as that is not a feasible reality.

**Comment by dasMulli** [comment]
There is https://github.com/dotnet/designs/blob/master/accepted/sdk-version-scheme.md

> When 2.2.0 is released can the version be applied to both SDK & Runtime as v2.2.0 rather than SDK having a different version of 2.2.100?

Say it was 2.2.0, and then a new set of tooling releases are done updating the C# compiler, NuGet and MSBuild but the runtime doesn't increment. `2.2.1` would be quite confusing if there wasn't yet a `2.2.1` runtime version. And then incrementing again to `2.2.2` SDK when a `2.2.1` runtime is released isn't making it better. Until then, think of the SDK as a 4-part version squeezed into a 3-part scheme, starting at `100`, which helps distinguish SDK and runtime versions. They don't necessarily release in the same cycle.

**Comment by rohith** [comment]
Totally makes sense 👍 & I'm glad I now have a much better understanding of the SDK & Runtime versions. https://github.com/dotnet/designs/blob/master/accepted/sdk-version-scheme.md really helped me a lot & this should be the first thing that comes up on google when someone searches for **.Net Core SDK vs Runtime versions**

Thank you @dasMulli for explaining this, I really appreciate the effort 👌 👍 🤝
