### ISSUE TITLE
Enable publishing a self-contained app with `PublishSelfContained`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#26445]
We call self-contained apps as "SCD" or "self-contained deployment". It's clearly primarily intended as a publishing tasks not inner-loop, yet we don't have a `Publish*` property for it. We should create `PublishSelfContained` property.

This is also mentioned in https://github.com/dotnet/sdk/issues/26028 and is logically the same as #26444.

**Comment by nagilson** [comment]
Closing this as resolved by https://github.com/dotnet/sdk/pull/28714 
Also ucr shorthand is https://github.com/dotnet/sdk/pull/27971
