### ISSUE TITLE
dotnet [packagename] not working

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/sdk#26490]
### Describe the bug
After installing a package (dotnet tool install [package] --global, the command dotnet [package] does not work

### To Reproduce

- dotnet tool install fantomas --global
- dotnet fantomas --recurse .
- Result: 
  "Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-fantomas does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the "

I have tested with other packages with the same result

### Workaround
I have found that renaming the package in %USERPROFILE%\.dotnet\tools as "dotnet-fantomas", the command "dotnet fantomas --recurse ." starts working as expected

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by baronfel** [comment]
Global installed use the tool name without the 'dotnet' prefix. Can you try just executing 'fantomas'?

Local tool installs (drop the --global option) would use the 'dotnet TOOLNAME' syntax.

For fantomas, I would suggest using a local tool - it's still very easy to acquire the tool using 'dotnet tool restore' and it helps prevent implicit global system state.

**Comment by mauriciomagni** [comment]
hello @baronfel 
Yes, I tried these ones
dotnet fantomas
dotnet femto
and 
dotnet paket

in all the cases the result was the same. dotnet was not able to resolve the command. 
after renaming fantomas as dotnet-fantomas it started working.

I will try installing locally and let you know my results.

**Comment by baronfel** [comment]
I think you misunderstood me @mauriciomagni:

```terminal
$ dotnet tool install -g fantomas
Skipping NuGet package signature verification.
You can invoke the tool using the following command: fantomas
Tool 'fantomas' (version '6.2.3') was successfully installed.
$ fantomas
USAGE: dotnet fantomas [--help] [--force] [--profile] [--out <string>] [--check] [--daemon] [--version] [--verbosity <string>] [<string>...]

INPUT:

    <string>...           Input paths: can be multiple folders or files with *.fs,*.fsi,*.fsx,*.ml,*.mli extension.

OPTIONS:

    --force               Print the output even if it is not valid F# code. For debugging purposes only.
    --profile             Print performance profiling information.
    --out <string>        Give a valid path for files/folders. Files should have .fs, .fsx, .fsi, .ml or .mli extension only. Multiple files/folders are not supported.
    --check               Don't format files, just check if they have changed. Exits with 0 if it's formatted correctly, with 1 if some files need formatting and 99 if there was an
                          internal error
    --daemon              Daemon mode, launches an LSP-like server to can be used by editor tooling.
    --version             Displays the version of Fantomas
    --verbosity, -v <string>
                          Set the verbosity level. Allowed values are n[ormal] and d[etailed].
    --help                display this list of options.
```

As I said, _global_ tools do not have the `dotnet` prefix - you call them with only their names. _Local_ tools would require the `dotnet fantomas` version.
