### ISSUE TITLE
[Megathread] Engineering Status of RID Improvements and Publish UX Changes

### ISSUE THREAD

**Issue by nagilson** [dotnet/sdk#26503]
This is to help me keep organized on what I still need to implement for the issues specified here by @richlander and resolves https://github.com/dotnet/sdk/issues/26446 and so others can see the progress on those issues. I will be closing them out as well, but this may be helpful. 

PR 1) https://github.com/dotnet/sdk/pull/26143
- [x] 0) Use implicit RID in the following situations:
	- For any publish property that requires a rid, use the default RID, just like if --use-current-runtime is specified.
		That means:
		- [x] SelfContained
		- [x] PublishAot
		- [x] PublishReadyToRun
		- [x] PublishSingleFile
		- [x] PublishTrimmed
		- [x] PublishSelfContained

- [x] 1) Add PublishSelfContained property.
	- [x] Set self contained to true automatically when we're publishing
	- [x] Make sure it takes precedence over self-contained=false

Remaining:
- [x] Make sure this doesn't break rid agnostic projects.

PR 2) _____
- [x] 0) Add RuntimeSpecific property.
	-> Sets self contained to false
	-> Uses the implicit RID (portable one)

	Verify:
	- [ ] Make sure you can still specify -r runtime without it being overriden.
	- [ ] Make sure you can still specify self-contained to true even if you do /p:SelfContained=true.

PR 3) ______
- [x] 0) Add --ucr shorthand for use-current-runtime. 

PR 4) ______
- [x] Add PublishRuntimeIdentifier property.

**Comment by richlander** [comment]
Looks good!

I'd say that the `--ucr` request is lowest on the list.

**Comment by nagilson** [comment]
All of these are done except `RuntimeSpecific`, which is here https://github.com/dotnet/sdk/pull/28412 and waiting for 8.0 SDK Build changes.  Going to close this!
