### ISSUE TITLE
Implicit selection of `Microsoft.AspNetCore.App` broken in new SDK

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/sdk#2651]
When we upgraded to the new SDK (3.0.100-preview-009730) we started experiencing the following errors in our templating tests:

```
C:\Users\rybrande\.nuget\packages\microsoft.aspnetcore.app\2.1.0\build\netcoreapp2.1\Microsoft.AspNetCore.App.targets(14,5): error : This version of Microsoft.AspNetCore.App is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.App compatible with netcoreapp3.0.
```

I've created a minimal repro of this issue [here](https://github.com/ryanbrandenburg/ImplicitSDKDemo). You can work around this by explicitly giving the version of `Microsoft.AspNetCore.App` as ` Version="3.0.0-alpha1-10653"`, but it's my understanding that the implicit scenario is not only supported, but the recommended path.

If you'd like to see it in the "real" environment the repro steps against Templating are as follows:

1. Acquire SDK version 3.0.100-preview-009730.
1. `git clone https://github.com/aspnet/Templating`
2. `./run.ps1 -update upgrade deps`
3. `./build.cmd` Observe the test failures.

dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009730
 Commit:    6a33a587e8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\rybrande\.dotnet\x64\sdk\3.0.100-preview-009730\

Host (useful for support):
  Version: 3.0.0-preview1-26907-05
  Commit:  96537a8f64

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009398 [C:\Program Files\dotnet\sdk]
  2.2.100-preview2-009404 [C:\Users\rybrande\.dotnet\x64\sdk]
  2.2.200-preview-009431 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009730 [C:\Users\rybrande\.dotnet\x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0-preview2-35157 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10620 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10663 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0-preview2-35157 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35364 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10620 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10663 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10706 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27030-3 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 2.2.0-preview2-26905-02 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27001-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27104-01 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-26907-05 [C:\Users\rybrande\.dotnet\x64\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

CC @livarcocc @mkArtakMSFT

**Comment by dsplaisted** [comment]
@ryanbrandenburg The issue here is that we don't currently support a versionless `PackageReference` for ASP.NET Core 3.0.  Use a `FrameworkReference` instead.  The demo .csproj should be able to just be this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="3.0.0-alpha1-10653" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

Here's the work item tracking making `PackageReference` work: https://github.com/dotnet/cli/issues/10124

Also, we are planning to make the `FrameworkReference` implicit if you are using the Web SDK: https://github.com/aspnet/websdk/issues/424, https://github.com/dotnet/cli/issues/10107

**Comment by livarcocc** [comment]
@ryanbrandenburg will @dsplaisted's suggestion above work for you?

**Comment by ryanbrandenburg** [comment]
Possibly with some adjustments. Firstly it seems that it's actually `<FrameworkReference Include="Microsoft.AspNetCore" />` not `Microsoft.AspNetCore.App`. Secondly we get a bunch of problems related to selecting the Razor Language version. The Razor language version thing is on our side (a fix had been merged), I'll get back to you if there's anything more after this.

**Comment by dsplaisted** [comment]
@ryanbrandenburg The `FrameworkReference` name will change to include the `.App` in this PR (which I just merged): https://github.com/dotnet/core-sdk/pull/142

**Comment by ryanbrandenburg** [comment]
We're still having trouble with 3.0.100-preview-009750. The message we get now is:
```
The specified framework 'Microsoft.NETCore.App', version '2.0.9' was not found.
- Check application dependencies and target a framework version installed at:
/Users/vsts/agent/2.141.2/work/.dotnet/
- Installing .NET Core prerequisites might help resolve this problem:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
- The .NET Core framework and SDK can be installed from:
https://aka.ms/dotnet-download
- The following versions are installed:
3.0.0-preview-27113-06 at [/Users/vsts/agent/2.141.2/work/.dotnet/shared/Microsoft.NETCore.App]
3.0.0-preview1-26907-05 at [/Users/vsts/agent/2.141.2/work/.dotnet/shared/Microsoft.NETCore.App]
```

It seems like `BundledAspNetCoreAppPackageVersion` which we have previously used in this area to force framework version isn't being consulted. Is there a new variable? Is this one just broken?

**Comment by dsplaisted** [comment]
@ryanbrandenburg Yes, the way this works has changed.  It also is likely to change again as we move to targeting and runtime packs.

For now, here's how it's defined (in Microsoft.NETCoreSdk.BundledVersions.props):

```xml
    <KnownFrameworkReference Include="Microsoft.AspNetCore.App"
                              TargetFramework="netcoreapp3.0"
                              RuntimeFrameworkName="Microsoft.AspNetCore.App"
                              DefaultRuntimeFrameworkVersion="<version>"
                              LatestRuntimeFrameworkVersion="<version>"
                              TargetingPackName="Microsoft.AspNetCore.App"
                              TargetingPackVersion="<version>"
                              />
```

You should be able to update the versions with something like this in your .targets:

```xml
<KnownFrameworkReference Update="Microsoft.AspNetCore.App"
                              DefaultRuntimeFrameworkVersion="<testversion>"
                              LatestRuntimeFrameworkVersion="<testversion>"
                              TargetingPackVersion="<testversion>"
                              />
```

**Comment by ryanbrandenburg** [comment]
Can we get an issue filed against us at aspnet/AspNetCore or be otherwise notified when this kind of change is coming? It's a real pain to find out about these things piecemeal when they start breaking us, and it can server as semi-documentation for anyone who's doing their own templates or otherwise operating outside of the "normal" workflow (that is, aren't using preview or RTM builds with full installers).

I'll try that against my broken Templating branch and let you know how it turns out.

**Comment by ryanbrandenburg** [comment]
This was solved by KnownFrameworkReference. I've run into a different problem, but I'll file it as its own issue.
