### ISSUE TITLE
.net6 Ambiguous reference in rider, but build success.

### ISSUE THREAD

**Issue by annpeter** [dotnet/sdk#26522]
![image](https://user-images.githubusercontent.com/7344217/178501938-e5c8f154-44d7-460c-baf5-8157c8bfb53e.png)

**Comment by baronfel** [comment]
This is Rider-based, you'll have to talk to them about their intellisense suggestions. You can do that at [their issue tracker](https://youtrack.jetbrains.com/issues/RIDER).
