### ISSUE TITLE
Update of Visual Studio (17.6.2) and SDK (6.0.302) prevents the use of source generators for Microsoft.Toolkit.MVVM

### ISSUE THREAD

**Issue by MarcoSpoenemann** [dotnet/sdk#26542]
### Describe the bug
After installing the updates, it is no longer possible to compile WPF projects using Microsoft.Toolkit.MVVM. Errors are thrown during the build process: 

- The type <TypeName> already contains a definition for <Property>.
- Duplicate 'global::System.CodeDom.Compiler.GeneratedCode' attribute 

and so on.

It looks like code generators are executed twice.

### To Reproduce
Use the sample project in this repository with Visual Studio 17.2.6 and the latest .NET 6 SDK and try to build: https://github.com/MarcoSpoenemann/dotnet6-mvvm 

### Exceptions (if any)
- CS0101
- CS0579
- CS0102

### Further technical details

.NET SDK (gemäß "global.json"):
 Version:   6.0.302
 Commit:    c857713418

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

**Comment by Tum4ik** [comment]
A workaround is here https://github.com/dotnet/roslyn/issues/62582#issuecomment-1183251686.

**Comment by Keboo** [comment]
Running into a similar problem on [Material Desing in XAML Toolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit). It uses some source generators from [XAMLTest](https://github.com/Keboo/XAMLTest) which appear to be getting executed twice (or the output included twice). Rolling back the SDK with the global.json appears to fix the issue for now.

**Comment by marcpopMSFT** [comment]
This is the issue tracking the fix. https://github.com/dotnet/wpf/issues/6792
