### ISSUE TITLE
CppUnitTestFramework is being included in linux .NET SDK

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#26590]
### Describe the bug
The Linux .NET SDK is including a bunch of native Windows `.dll` files:

![image](https://user-images.githubusercontent.com/8291187/179034472-8c945050-8008-4eb0-91cc-a6ea983672d7.png)

These assemblies all have the Product Name of `Microsoft Windows Operating System`, which is a weird product name for assemblies we are installing onto Linux machines.

I'm also not sure what the license is for these assemblies. I'm not sure if they meet the MIT License that we ship the linux .NET SDK under.

### To Reproduce
Download and extract the latest .NET linux-x64 SDK. Look at the files being included. It shouldn't contain native assemblies that are compiled for Windows.

cc @dsplaisted @marcpopMSFT @richlander 

### Further technical details
I'm not sure if or how this affects source-build. These assemblies don't show where they are built from, so I don't know if we are building these assemblies during source-build or not. cc @MichaelSimons

**Comment by crummel** [comment]
Source-build doesn't currently ship 6.0.3xx but this would definitely be a problem if we do so in the future.  Poisoning should catch this problem after we start building 6.0.3xx but it's good to know in advance.

**Comment by eerhardt** [comment]
I looked back and these assemblies weren't present in `6.0.100` but are in `6.0.300`, and are in `main`/`7.0`.

**Comment by richlander** [comment]
It seems like we should enable source-build for newer SDK versions even if we no-one is consuming them. These dependencies look bad. We need a way to avoid that. Sourcebuild seems like our best tool for that.

>  it's good to know in advance

It'd say it is necessary. This is a P1 problem, not P3.

@MichaelSimons -- can you get this on the schedule for .NET Tactics?

**Comment by marcpopMSFT** [comment]
@pavelhorak @nohwnd as these come from the vstest repo.
