### ISSUE TITLE
Get three warnings when you add an incompatible project reference from a legacy project system -> new project system

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#266]
Add a reference from a legacy csproj targeting .NET Framework 4.5.2 -> .NET Core project, and you get the following warnings:

```
Warning     The project 'ConsoleApplication37' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)   ConsoleApp1         
Warning     Project has no no target framework compatible with '.NETFramework,Version=v4.5.2'   ConsoleApp1         
Warning     The target "GetTargetPath" does not exist in the project.   ConsoleApp1 C:\Users\davkean\Documents\Visual Studio 15\Projects\ConsoleApplication37\ConsoleApplication37\ConsoleApplication37.csproj      
```

**Comment by srivatsn** [comment]
This is done.

**Comment by StingyJack** [comment]
Does "This is done" mean the problem is fixed? Because its happening in the RTW for VS2017. Adding a HintPath for the project reference helps it sometimes.

**Comment by OlegKleyman** [comment]
yep same here. I'm just getting one warning though. "cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)" The library appears to be working though.

**Comment by StingyJack** [comment]
@srivatsn - "Done" means :still not working" or "wont fix"?

I cant project reference a POCO library thats multi targeted from a framework app. I have to assembly reference its compiled location to make this work, but that's not going to work again once I change the solution configuration.

![image](https://cloud.githubusercontent.com/assets/15381181/24834718/8dde9042-1cbb-11e7-8940-0cdf9b340092.png)

**Comment by srivatsn** [comment]
What frameworks does your library target? From the screenshot it sounds like atleast one of the targets is netcore which cannot be referenced by a framework app. You need to target netstandard to be able to reference the library from a framework project.

**Comment by gulbanana** [comment]
you could also target net itself rather than netstandard
either way though it should be fine to target *both* using something like
<TargetFrameworks>netcoreapp1.1;net461</TargetFrameworks>
in that case the old-style project should pick up the net461 build product and ignore the netcoreapp one, and if it doesn't it's a bug

**Comment by StingyJack** [comment]
I had it targeting netcoreapp1.1 (because it does that out-of-the-box). I changed it to this and had to restart VS a few times to get it to load properly.  I still have to restart VS periodically when this gets "stuck" like the above image..
```
<PropertyGroup>
    <TargetFrameworks>netstandard1.6;net462</TargetFrameworks>
    <RuntimeIdentifiers>win10;ubuntu.16.04-x64</RuntimeIdentifiers>
    <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by srivatsn** [comment]
Needing to reload the project (I don't think you need a full VS reload) is a race condition in MSBuild\CPS that are tracking down. If you close and reopen the solution and if it still fails then it's a bug that we should investigate.

**Comment by srivatsn** [comment]
Also as for the default TFM in VS there are two templates  a .NET Core one and a .NET Standard one  - see the discussion here for reasons - https://github.com/dotnet/project-system/issues/1909
