### ISSUE TITLE
AutoGenerateBindingRedirects should be on by default for desktop projects

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#267]
This should be turned on by default, similar to what we do in the legacy templates.

**Comment by dsplaisted** [comment]
@nguerrera 

> I suspect the best defaults would be designtimeunify always, unify all class libs and autogeneratebindingredirects for desktop exes.

What about unit test projects running on desktop?  They aren't exes, but they may need binding redirects.  Should the test framework NuGet packages have a `.props` file which sets `AutoGenerateBindingRedirects` to true?  Is there some better way to handle it?

**Comment by nguerrera** [comment]
> What about unit test projects running on desktop? They aren't exes, but they may need binding redirects. Should the test framework NuGet packages have a .props file which sets AutoGenerateBindingRedirects to true? Is there some better way to handle it?

Good point. IIRC, msbuild targets won't even attempt binding redirect generation unless output type is exe or winexe. If so, we'll need msbuild changes. We also have to think about whether this would be breaking. Perhaps, we need yet another property to trigger a new behavior.

**Comment by dsplaisted** [comment]
Fixed with #319
