### ISSUE TITLE
"AfterPublish" doesn't invoked

### ISSUE THREAD

**Issue by liesauer** [dotnet/sdk#26710]
### Describe the bug
![image](https://user-images.githubusercontent.com/8676741/179887200-1a5f5a47-90bc-42e1-bf22-5258087c5fbd.png)

ASP.Net Core project

![image](https://user-images.githubusercontent.com/8676741/179888742-b77e3512-2637-422c-a2bf-2021e76284ec.png)

### To Reproduce
1. download [the Avalonia Gallery](https://github.com/AvaloniaUI/xamlcontrolsgallery)
2. create a task that depends on "AfterPublish" task
3. `dotnet publish`
4. "AfterPublish" and custom task doesn't not invoked
5. if it is a ASP.Net Core project, "AfterPublish" does be invoked.

### Exceptions (if any)
both of the two tasks should be invoked

### Further technical details
sdk: `6.0.300`

**Comment by baronfel** [comment]
This appears to be because `BeforePublish` and `AfterPublish` are only defined for Web SDK projects, not the .NET SDK itself. They are defined [here](https://github.com/dotnet/sdk/blob/a4431a389bbea6b1126c004368cd61c9d16a4c49/src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets#L41-L43).

We probably should pull this down to the base Microsoft.NET.Publish.targets as well, but that has the potential to be very disruptive. We'll need to bring down the targets themselves, as well as the Property-based extension points. Would likely need @dsplaisted to weigh in on the complexity.

I _do_ think this is a thing we should do, however - publishing isn't something that only Web projects can/should do.

**Comment by A9G-Data-Droid** [comment]
In the current version (SDK 6.0.401) the only way to get a single file app on the desktop is through publish. If you then want access to that final EXE in an automation, you need an `AfterPublish` event. I was unable to get this working, I found this issue. Seems to be the same. Being able to publish to a single file is a huge reason why I'm upgrading my desktop projects from Framework. As we go through this process of migrating away from Framework we are all going to need this feature on the Desktop.

**Comment by liesauer** [comment]
> In the current version (SDK 6.0.401) the only way to get a single file app on the desktop is through publish. If you then want access to that final EXE in an automation, you need an `AfterPublish` event. I was unable to get this working, I found this issue. Seems to be the same. Being able to publish to a single file is a huge reason why I'm upgrading my desktop projects from Framework. As we go through this process of migrating away from Framework we are all going to need this feature on the Desktop.

the last stage of non-web project is `Publish`, so for now, the following workaround works for me.
```xml
<PropertyGroup>
    <_TaskDependsOn Condition="'$(_IsAspNetCoreProject)' == 'true'">AfterPublish</_TaskDependsOn>
    <_TaskDependsOn Condition="'$(_IsAspNetCoreProject)' != 'true'">Publish</_TaskDependsOn>
</PropertyGroup>

<Target Name="CustomTask" AfterTargets="$(_TaskDependsOn)">
    <Message Text="Hello" Importance="High" />
</Target>
```

**Comment by A9G-Data-Droid** [comment]
> ```
> <PropertyGroup>
>     <_TaskDependsOn Condition="'$(_IsAspNetCoreProject)' == 'true'">AfterPublish</_TaskDependsOn>
>     <_TaskDependsOn Condition="'$(_IsAspNetCoreProject)' != 'true'">Publish</_TaskDependsOn>
> </PropertyGroup>
> 
> <Target Name="CustomTask" AfterTargets="$(_TaskDependsOn)">
>     <Message Text="Hello" Importance="High" />
> </Target>
> ```

Thank you so much! I tried so many permutations of Publish/AfterPublish. I wasn't able to get anything to fire before. Using this snippet I was able to get my published artifact in a final event!

**Comment by oskarb** [comment]
This snippet provided about does not seem to work if the project really is web-project. See https://github.com/dotnet/sdk/pull/36850#issuecomment-2676884372
