### ISSUE TITLE
Editor and Compiler doesn't handle preprocessor symbols for target frameworks with Visual Basic .Net Core/.Net Standard

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#2671]
@jing8956 commented on [Mon Nov 12 2018](https://github.com/dotnet/project-system/issues/4263)

Create a simple multiple target frameworks .Net Standard or .Net Core project
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```
and put this code in the class:
```
#If NETSTANDARD1_0 Then
    Public is1_0 As Integer
#ElseIf NETSTANDARD2_0 Then
    Public is2_0 As Integer
#Else
    Public other As Integer
#End If
```
Expected(C#) and Actual(Visual Basic):
![2018-11-12](https://user-images.githubusercontent.com/20148769/48337474-fa655900-e69d-11e8-8e34-17a9c39370ec.png)
![2018-11-12 1](https://user-images.githubusercontent.com/20148769/48337493-05b88480-e69e-11e8-844a-c9b2a9ff4875.png)

These symbols are like they don't exist at all. In compilation, too.
Although I can use C #, but it makes me sad for Visual Basic.

By the way,#2733 also appears in the Visual Basic project and behaves exactly the same.

Version 15.8.9

---

@Pilchie commented on [Thu Nov 15 2018](https://github.com/dotnet/project-system/issues/4263#issuecomment-439181160)

@livarcocc - given "In compilation, too." is this something that should be on SDK?  I'm surprised there would be a language difference here?

---

@livarcocc commented on [Thu Nov 15 2018](https://github.com/dotnet/project-system/issues/4263#issuecomment-439183256)

Yes. They should be available in VS as well. I believe they are actually set in the SDK. So, I am going to move the issue there.

**Comment by MiYanni** [comment]
Old bug triage: If this is still an issue, please reopen.
