### ISSUE TITLE
 Could not copy Error in docker linux container

### ISSUE THREAD

**Issue by sfoslund** [dotnet/sdk#26711]
---
**Issue moved from dotnet/sdk#12611**
- Please respond to @aortiz-msft.

---

_From @aortiz-msft on Thursday, July 23, 2020 5:50:04 PM_

---
**Issue moved from NuGet/Home#9787**
- Please respond to @ZergRushJoe.

---

_From @ZergRushJoe on Monday, July 13, 2020 12:56:23 AM_

## Details about Problem
I keep getting this error from my 'docker build .'. I'm getting the error with this .net core microsoft.analysisservices.adomdclient.netcore.retail.amd64. The Error that comes from it:

/usr/share/dotnet/sdk/3.1.301/Microsoft.Common.CurrentVersion.targets(4360,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.analysisservices.adomdclient.netcore.retail.amd64/19.4.0.2-preview/lib/netcoreapp3.0/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll" to "bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll". Could not find a part of the path '/app/Processor/bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll'

Don't know why it can't find that package. it restores just fine. I know it builds on windows which more then likly means I can never get it to work. The project it is in is an F# project.

Docker File
From node:12 AS web-build

COPY ./Web.UI ./

RUN npm i
RUN npm run test
RUN npm run buildProd

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS backend-build

WORKDIR /app
COPY . ./
COPY --from=web-build /Processor/wwwroot ./Processor/wwwroot
RUN dotnet test
RUN dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=backend-build /app/publish .
EXPOSE 80

**Comment by dsplaisted** [comment]
OK, well I've moved this back to the SDK then, as it seems like that's where we could fix the instance of this issue that most people seem to be hitting (culture casing in NuGet packages).

**Comment by StevenJV** [comment]
> Hopefully this helps some you guys.
> 
> This also happened to us on Linux since it is Case Sensitive, if your application doesn't need all those localizations, you might choose not to build them by adding the following tags in your ".CSProj" file under "PropertyGroup" element:
> 
> `<SatelliteResourceLanguages>en</SatelliteResourceLanguages>`
> 
> **Note:** In our case we only needed the "en" localization.

just a point of info; I'm not sure what's different, but this isn't helping in my case.

**Comment by richlander** [comment]
FYI: @mthalman @MichaelSimons

**Comment by benjamin-yayon** [comment]
Setting the dotnet cli ui language did the trick for me.
`set DOTNET_CLI_UI_LANGUAGE=en`

Not sure why, but once setting this value the folder is copied with the correct casing.
It may be related to the comment above: https://github.com/dotnet/sdk/issues/26711#issuecomment-1189773241
