### ISSUE TITLE
run wpf on linux

### ISSUE THREAD

**Issue by ghost1372** [dotnet/sdk#2676]
dotnet --version = 3.0.100-preview-009756
hi i want run my wpf app on linux so:
1 - Create WPF app dotnet new wpf
2 - dotnet publish -c release -r ubuntu.16.04-x64
3 - Copy Publish folder on linux
4 - chmod 777 ./wpfapp
5 - ./wpfapp
but i get this error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

**Comment by davidfowl** [comment]
There are no plans to make WPF applications run on non windows OSes
