### ISSUE TITLE
Unable to install workloads that do not have their folder name listed in IncludedWorkloadManifests.txt

### ISSUE THREAD

**Issue by pjcollins** [dotnet/sdk#26787]
### Describe the bug
We recently updated our SDK dependency to https://github.com/dotnet/installer/commit/a9c056c - 7.0.100-rc.1.22368.2 and have hit some potential changes in workload installation behavior. Attempting to install a workload that is "unknown" to the .NET SDK is now failing. I'm not sure if this was a supported scenario to begin with however.

### To Reproduce
1. Install the latest .NET SDK preview
2. Create the file `dotnet\sdk-manifests\7.0.100\microsoft.net.workload.test\WorkloadManifest.json` with the following content:

```json
{
  "version": "0.0.1",
  "workloads": {
    "android-deps": {
        "extends" : [ "microsoft-net-runtime-android", "microsoft-net-runtime-android-aot" ]
      }
  }
}

```
3. Run `dotnet workload install android-deps`, or `dotnet workload search`.
4. Installation attempts fail with `Workload ID android-deps is not recognized.`.

I'm able to work around this easily enough by adding the workload folder name `microsoft.net.workload.test` to the `dotnet\sdk\*\IncludedWorkloadManifests.txt` file, but am wondering if something has changed here recently that would cause this to stop working. As of rc.1 we are no longer using a `7.0.100-preview.*` manifest folder, maybe this would continue to work as before if we try to use a `7.0.100-rc.1` manifest folder.

**Comment by pjcollins** [comment]
It looks like the issue was a result of us starting to use a `dotnet\sdk-manifests\7.0.100` manifest folder name in rc.1, rather than continuing to use a "preview" branded folder name (e.g. `dotnet\sdk-manifests\7.0.100-rc.1`)

**Comment by joeloff** [comment]
In 7.0, we treat manifest version as SxS when they are semantically different. Example, if you have a 7.0.100 manfiest and a 7.0.100-foo manifest, we'll allow both to be installed side-by-side, so rc.1 will look like another version to it.

**Comment by pjcollins** [comment]
@joeloff I'm assuming the `7.0.100` folder is treated as fallback, and `7.0.100-rc.1` is the "current" sdk feature band? Presumably we wouldn't expect `7.0.100` to be the sdk feature band until we get rtw branded builds or something like that?
