### ISSUE TITLE
Baseline package validator doesn't report renamed arguments

### ISSUE THREAD

**Issue by Alex-Sob** [dotnet/sdk#26797]
Baseline package validator does not validate renamed arguments which is a breaking change. Optional arguments are commonly passed using named arguments, also latest C# versions allow using named arguments for fixed parameters as well.

**Comment by ViktorHofer** [comment]
This feature [was added just recently](https://github.com/dotnet/sdk/commit/d78f4b42fd8f8ef4516455435f8e62316020571c) and is off by default. You can turn the rule on by:
- setting the following property (in msbuild) `/p:ApiCompatEnableRuleCannotChangeParameterName=true` or
- when invoking the CLI (global tool) by passing in the following parameter: `--enable-rule-cannot-change-parameter-name`.

This is already part of the latest packages produced in main and will also be part of .NET 7.

**Comment by ViktorHofer** [comment]
cc @smasher164
