### ISSUE TITLE
Hot reload erases captured local variables in async function

### ISSUE THREAD

**Issue by Ghost4Man** [dotnet/sdk#26803]
### Describe the bug
**Captured local variables in an async function are erased** (set to zero/null/default) **after hot-reload** (instead of keeping the same value). This can of course also cause unexpected null reference exceptions etc.

The debugger (at least in VS 2022) shows the correct (unchanged) values, but the program actually prints the incorrect (zeroed) values.

### To Reproduce
1. `dotnet new console`
2. replace `Program.cs` content with the following code (or open [this replit](https://replit.com/@Ghost4Man/dotnet-hot-reload-weird-behavior#main.cs)):

	  ```cs
	  static class Program
	  {
	      static async Task Main()
	      {
	          string str = "Lorem ipsum";
	          int num = 42;
	  
	          while (true)
	          {
	              Console.WriteLine($"foo {str ?? "null"} {num}");
	  
	              await Task.Delay(2000);
	          }
	  
	          // removing/commenting out this function "deactivates" the bug
	          string DummyFunction() => str + num;
	      }
	  }
	  ```

3. start `dotnet watch` and change for example `foo` to `bar` (on line 10). Actual output:
	```
	dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
	  💡 Press "Ctrl + R" to restart.
	dotnet watch 🔧 Building...
	  Determining projects to restore...
	  All projects are up-to-date for restore.
	T:\test\DotnetHotreloadBug\Program.cs(16,16): warning CS8321: The local function 'DummyFunction' is declared but never used [T:\test\DotnetHotreloadBug\DotnetHotreloadBug.csproj]
	  DotnetHotreloadBug -> T:\test\DotnetHotreloadBug\bin\Debug\net6.0\DotnetHotreloadBug.dll
	dotnet watch 🚀 Started
	foo Lorem ipsum 42
	foo Lorem ipsum 42
	foo Lorem ipsum 42
	dotnet watch ⌚ File changed: .\Program.cs.
	foo Lorem ipsum 42
	dotnet watch 🔥 Hot reload of changes succeeded.
	bar null 0
	bar null 0
	bar null 0
	dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
	```
	Expected output (after the hot reload):
	```
	dotnet watch 🔥 Hot reload of changes succeeded.
	bar Lorem ipsum 42
	bar Lorem ipsum 42
	bar Lorem ipsum 42
	dotnet watch 🛑 Shutdown requested. Press Ctrl+C again to force exit.
	```

### Further technical details
* output of `dotnet --info`
	<details>
	<summary>output</summary>

	  .NET SDK (reflecting any global.json):
	   Version:   6.0.302
	   Commit:    c857713418
	  
	  Runtime Environment:
	   OS Name:     Windows
	   OS Version:  10.0.19044
	   OS Platform: Windows
	   RID:         win10-x64
	   Base Path:   C:\Program Files\dotnet\sdk\6.0.302\
	  
	  global.json file:
	    Not found
	  
	  Host:
	    Version:      6.0.7
	    Architecture: x64
	    Commit:       0ec02c8c96
	  
	  .NET SDKs installed:
	    3.1.402 [C:\Program Files\dotnet\sdk]
	    3.1.421 [C:\Program Files\dotnet\sdk]
	    5.0.406 [C:\Program Files\dotnet\sdk]
	    5.0.408 [C:\Program Files\dotnet\sdk]
	    6.0.203 [C:\Program Files\dotnet\sdk]
	    6.0.302 [C:\Program Files\dotnet\sdk]
	  
	  .NET runtimes installed:
	    Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	    Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	    Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	    Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	  
	  Download .NET:
	    https://aka.ms/dotnet-download
	  
	  Learn about .NET Runtimes and SDKs:
	    https://aka.ms/dotnet/runtimes-sdk-info  
	</details>

* also happens on Replit with dotnet sdk version 6.0.100

* happens both when using the hot-reload in VS Enterprise 2022 (64-bit) 17.2.6 and in dotnet CLI `dotnet watch` (including the linked replit)

**Comment by carlosmachina** [comment]
Is it possible that this issue relates to the following issue on developercommunity?

[Hot Reload Not Working on aspnet core applications VS2022 v17.3 preview 4](https://developercommunity.visualstudio.com/t/Hot-Reload-Not-Working-on-aspnet-core-ap/10101450)

I've been trying to pinpoint this issue and managed to narrow it to something going wrong in the 

[Razor TagHelper Runner](https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Razor.Runtime/src/Runtime/TagHelpers/TagHelperRunner.cs)

Somewhere around line 42, when it calls for the ProcessAsync for the tag helpers

`var task = tagHelpers[i].ProcessAsync(tagHelperContext, tagHelperOutput);`

Eventually calling it for a [FormTagHelper](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Mvc/Mvc.TagHelpers/src/FormTagHelper.cs)



At line 247 the debugger actually goes into the if, even while showing the _routeValues as null

![image](https://user-images.githubusercontent.com/8450363/182620295-cafc4b6d-6c7f-4e25-9ce5-0c853a3152e8.png)

As the final effect, it causes an exception in the [MulticastDelegate](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/multicastdelegate.cs) lib, line 613, because target will be null into the CtorClosed method.

Don't know if the issues are related, but hope it helps someone with more knowledge than me to figure it out as it totally breaks hotreload on Aspnet for VS2022 17.3.0 Preview-4 onwards

**Comment by mkArtakMSFT** [comment]
@tmat can you please look into this? Thanks!

**Comment by tmat** [comment]
This is a bug in the compiler: https://github.com/dotnet/roslyn/issues/63294
