### ISSUE TITLE
Roslyn no longer builds if I install .NET Core 3 SDK

### ISSUE THREAD

**Issue by jcouv** [dotnet/sdk#2680]
I installed a preview of .NET Core  3 (from https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries ).
When I build I get the error below.

Uninstalling it fixes the issue.

```C#
D:\repos\roslyn>Restore.cmd
…
D:\repos\roslyn>msbuild /v:m /m Compilers.sln
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  RunTests -> D:\repos\roslyn\Binaries\Debug\Exes\RunTests\RunTests.exe
  Microsoft.CodeAnalysis -> D:\repos\roslyn\Binaries\Debug\Dlls\Microsoft.CodeAnalysis\Microsoft.CodeAnalysis.dll
  CSharpSyntaxGenerator -> D:\repos\roslyn\Binaries\Debug\Exes\CSharpSyntaxGenerator\CSharpSyntaxGenerator.dll
  CSharpErrorFactsGenerator -> D:\repos\roslyn\Binaries\Debug\Exes\CSharpErrorFactsGenerator\CSharpErrorFactsGenerator.dll
  VisualBasicErrorFactsGenerator -> D:\repos\roslyn\Binaries\Debug\Exes\VisualBasicErrorFactsGenerator\VBErrorFactsGenerator.dll
  CompilersBoundTreeGenerator -> D:\repos\roslyn\Binaries\Debug\Exes\CompilersBoundTreeGenerator\BoundTreeGenerator.dll
  VisualBasicSyntaxGenerator -> D:\repos\roslyn\Binaries\Debug\Exes\VisualBasicSyntaxGenerator\VBSyntaxGenerator.dll
  Microsoft.Build.Tasks.CodeAnalysis -> D:\repos\roslyn\Binaries\Debug\Dlls\Microsoft.Build.Tasks.CodeAnalysis\net472\Microsoft.Build.Tasks.CodeAnalysis.dll
  Microsoft.CodeAnalysis.CodeStyle -> D:\repos\roslyn\Binaries\Debug\Dlls\Microsoft.CodeAnalysis.CodeStyle\Microsoft.CodeAnalysis.CodeStyle.dll

C:\Program Files\dotnet\sdk\3.0.100-preview-009762\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(220,5): error NETSDK1047: Assets file 'D:\repos\roslyn\Binaries\Obj\CompilerBenchmarks\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.1/win-
x64'. Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers. [D:\repos\roslyn\src\Tools\CompilerBenchmarks\CompilerBenchmarks.csproj]
  
…
```

**Comment by peterhuene** [comment]
This may be related to the default apphost feature for the 3.0 .NET Core SDK (depending on what `restore.cmd` is doing).

Does setting `UseAppHost` to `false` in `CompilerBenchmarks.csproj` fix the problem?

If it does, could you share with me a binlog from the restore and a binlog for the failing build so I can determine why it's not working?  Thanks!

**Comment by jcouv** [comment]
Setting `<UseAppHost>false</UseAppHost>` in `CompilerBenchmarks.csproj` did fix the problem.

I'll send you binary logs by mail.

**Comment by peterhuene** [comment]
From the mail, it looks like the restore occurred with an 2.1.403 SDK, which might explain the problem.  Could we ensure the restore also uses a 3.0 SDK?

**Comment by jcouv** [comment]
Following your observation and from discussion with @jaredpar, we're clear what is the proper way of restoring and building :-S
To restore, we use 2.1 explicitly, but then we build using `msbuild` (because `dotnet build` cannot handle some of projects with desktop dependencies, vssdk, winforms, ...).

**Comment by peterhuene** [comment]
I don't think we can guarantee that a 2.1 restore would work with a 3.0 build.  The apphost feature is expecting consistency and I assume that we're likely to have additional dependencies on the restore being 3.0 (such as the upcoming "download only packages" NuGet feature which may be used for 3.0 SDK features).

Do you need the explicit 2.1-based restore vs. using `msbuild /restore` with a 3.0 SDK?

@livarcocc @dsplaisted thoughts on this mismatch between SDK versions with restore and build?

**Comment by jaredpar** [comment]
> I don't think we can guarantee that a 2.1 restore would work with a 3.0 build.

What is the golden path for customers to take here then? We're in a situation where we have to deal with the following:

- Must have 2.1 installed for the foreseeable future.
- Must install builds of 3.0 on some machines for dogfooding. Will not necessarily be consistent across all of our developers
- Must continue to build on developer machines where there will be both 2.1 and 3.0 installs

How do we integrate this into our build?

**Comment by peterhuene** [comment]
I think using `global.json` to specify a matching SDK version used for the restore is the best option.

**Comment by jcouv** [comment]
I didn't follow. We already use a `global.json`:
```
D:\repos\roslyn>more global.json
{
  "tools": {
    "dotnet": "2.1.401"
  }
}
```

**Comment by peterhuene** [comment]
For the SDK resolver, we use the `sdk.version` setting:

```json
{
  "sdk": {
    "version": "2.1.401"
  }
}
```

**Comment by jaredpar** [comment]
Okay will do. That was deleted by @tmat as part of the arcade work. We can add it back for now but should probably sync up on why that was removed in the first place. Based on this thread it appears it's still  necessary.

**Comment by jcouv** [comment]
Confirmed that fixes the problem. I'll close the issue. Thanks!

**Comment by dsplaisted** [comment]
The global.json was changed specifically so that you wouldn't get pinned to a specific version of the tools.  You should be able to use a newer version of MSBuild, the SDK, etc.

I think the issue here is that Restore.cmd was using one SDK while the build was trying to use a different version.  Could Restore.cmd be changed to use the same toolset/SDK as the MSBuild call uses?

**Comment by jaredpar** [comment]
> Could Restore.cmd be changed to use the same toolset/SDK as the MSBuild call uses?

Correct me if i'm wrong but there isn't a way to do this. It appears, based on this thread, that `dotnet build` and `msbuild` have different rules for picking the SDK to use. How are we supposed to know which `dotnet` msbuild is going to pick? That doesn't seem actionable (or maybe I'm just missing it).

**Comment by dsplaisted** [comment]
@jaredpar They should have the same rules to select the SDK.  I suspect what's happening is that Restore.cmd is using the dotnet.exe that arcade downloads locally, instead of the globally installed version.

**Comment by jaredpar** [comment]
> I suspect what's happening is that Restore.cmd is using the dotnet.exe that arcade downloads locally, instead of the globally installed version.

Indeed because we can't depend on one being installed globally. And if there is one installed globally how can we correctly validate it meets our minimum version requirements?

**Comment by dsplaisted** [comment]
When you run `msbuild` you are relying on the globally installed MSBuild and .NET Core SDK.  So in that case you should be able to run the restore with the same globally-installed SDK as you're going to be using for build.

**Comment by peterhuene** [comment]
Thus my original question regarding the need for restoring with a 2.1 SDK vs let the 3.0 SDK do it (via `msbuild /restore` in this case).

If you do, then I think you need to also build with the same 2.1 SDK and not what's installed globally.  Setting `DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR` to point at `.dotnet` (assuming this is where the 2.1 `dotnet` you're using to restore is) should override how the SDK is resolved when using MSBuild (@dsplaisted can correct me if I'm wrong since I'm not terribly familiar with the resolver).

**Comment by rainersigwald** [comment]
Nit: you'd want to use `msbuild /t:Restore`, not `/restore` in this case since there's a distinct `restore.cmd` operation separate from build. `/restore` means "run the Restore target _and then_ run as you would have".

**Comment by peterhuene** [comment]
Agreed, if you want to maintain the `restore.cmd` behavior of a single restore and then a bunch of no-restore builds.
