### ISSUE TITLE
Ambiguous dotnet tool --global error message

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/sdk#26813]
Would it help for `dotnet tool` to show the full command line that is recommended to avoid repeat errors like below?

```
C:\>dotnet tool install upgrade-assistant
 Cannot find a manifest file. For a list of locations searched, specify the "-d" option before the tool name. 
If you intended to install a global tool, add `--global` to the command.
 If you would like to create a manifest, use `dotnet new tool-manifest`, usually in the repo root directory.  

C:\>dotnet tool -g install upgrade-assistant 
Unrecognized command or argument '-g'
```

**Comment by WeihanLi** [comment]
@lutzroeder , try this 
```
dotnet tool install -g upgrade-assistant
```

**Comment by baronfel** [comment]
This is more of a suggestion about how to format suggested commands to the user.

The templating engine has a really nice infrastructure for customizing command examples that we should expand on when it merges into this repo.
