### ISSUE TITLE
runtime-options (--roll-forward) for local tools

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/sdk#26824]
### Is your feature request related to a problem? Please describe.
If a .NET tool does not allow [major-version runtime roll forward](https://docs.microsoft.com/dotnet/core/whats-new/dotnet-core-3-0#major-version-runtime-roll-forward) and is run without any of the runtimes that it targets, it will fail. I would like a `dotnet` command-line option that overrides this setting.

### Describe the solution you'd like
Allow <var>runtime-options</var> in `dotnet` commands that run local tools. For example, `dotnet --fx-version 6.0.7 sarif` or `dotnet tool run --roll-forward Major sarif`.

A similar effect can already be achieved by setting the [`DOTNET_ROLL_FORWARD` environment variable](https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_roll_forward), which works with both global and local tools, as well as other .NET applications. However, that would be inherited by child processes too, unlike the command-line option. Inheritance is a good thing if the child process runs an executable that belongs to the same tool, but perhaps not if the child process runs an executable whose path the user specifies as an argument of the tool.

### Additional context
`sarif` in the previous examples refers to [Sarif.Multitool 2.4.16](https://www.nuget.org/packages/Sarif.Multitool/2.4.16), which does not allow major-version runtime roll forward.  I filed <https://github.com/microsoft/sarif-sdk/issues/2511> about fixing it.  <https://github.com/dotnet/sdk/issues/26417#issuecomment-1172672371> suggests a build warning for tools like that.

If a future version of .NET SDK allows an unmanaged executable to be packaged and run as a .NET tool (i.e. without `Command/@Runner="dotnet"` in `DotnetToolSettings.xml`), then it will not be possible to support <var>runtime-options</var> for that.

This is starting to look like a bad idea overall.

**Comment by baronfel** [comment]
System.CommandLine also hit this with their dotnet-suggest tool, as logged in https://github.com/dotnet/command-line-api/issues/2014

**Comment by marcpopMSFT** [comment]
Rather than default to rollforward like #30336 says, we plan on adding an option so it allows opting in at install time.

**Comment by JL03-Yue** [comment]
Close as merged in #37231
