### ISSUE TITLE
ImplicitlyExpandNETStandardFacades does not run when using full framework MSBuild and 3.0 .NET Core SDK

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2695]
As part of unifying publish and build (https://github.com/dotnet/sdk/commit/1936ebd7307cebd6c5d1d8d699b9844f73b8fb2c#diff-037688beff60348f7a74e33446cb6131), we split _HandlePackageFileConflicts into two targets: _HandlePackageFileConflictsForBuild and _HandlePackageFileConflictsForPublish.

This required updating the `BeforeTargets` declaration of the ImplicitlyExpandNETStandardFacades target in Microsoft.NET.Build.Extensions.NETFramework.targets.

Unfortunately, that targets file ships separately for the .NET Core SDK and full Framework MSBuild.  So if you have a 3.0 SDK but are building with full-framework MSBuild, you will get the old copy of Microsoft.NET.Build.Extensions.NETFramework.targets, which expects there to be a _HandlePackageFileConflicts target instead of _HandlePackageFileConflictsForBuild.

Probably the way to fix this is to rename _HandlePackageFileConflictsForBuild to _HandlePackageFileConflicts, and _HandlePackageFileConflictsForPublish can still be a separate target (at least for now).

@peterhuene, thoughts?

**Comment by peterhuene** [comment]
I think that approach makes sense.
