### ISSUE TITLE
Automatic Link generation from LinkBase does not work for Page, Resource items

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2697]
(Filing bugs from my notes after customer visit exploring porting large WPF app to .NET core 3)

This:
``` xml
<ItemGroup>
  <Page Include="..\X\**\*.xaml"  LinkBase="Y" />
</ItemGroup>
```

Does not work as it does for Compile, EmbeddedResource, AdditionalFiles, EmbeddedResource:

https://github.com/dotnet/sdk/blob/9543229b2d30f4c712846540e725014754229919/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L201-L246

This has two consequences:

1. It prevents the easy way of getting these files outside project cone to show in sln explorer
2. Xaml interpretation can actually change based on the Link so the impact of not generating a Link as expected can change the application behavior. I forget the details here, but I observed this in customer app.

I'm unsure if the WindowsDesktop SDK should be handling it or if we should add to above. We probably need to do this for Resource items as well.

cc @dsplaisted @vatsan-madhavan

**Comment by mjrousos** [comment]
Regarding consequence #2 above, I've seen this cause functional differences when trying to load XAML as a resource. The resource path changes based on the link path of the XAML so previously working code can break without <Link>

**Comment by vatsan-madhavan** [comment]
Is there documentation for `LinkBase` besides https://github.com/dotnet/sdk/pull/1246? 

When `EnableDefaultItems=false`, does it imply `SetLinkMetadataAutomatically==false` ?
