### ISSUE TITLE
PresentationFramework.Aero not included by default when compiling against .NET Framework

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/sdk#2703]
I'm porting an app that relies on `PresentationFramework.Aero` for `ButtonChrome` and found I need to include the following in the csproj to get it to compile when building for .NET Framework 4.7.1:

```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'net471'">
    <Reference Include="PresentationFramework.Aero" />
  </ItemGroup
```

Is there a reason this isn't automatically included when setting `<UseWindowsForms>true</UseWindowsForms>`?

**Comment by livarcocc** [comment]
From talking to @rladuca it seems like this is not added by default for non-sdk based projects either. So, it seems like we are keeping with the current behavior.

Also, this is a WPF theme, so I am not sure how it relates to `UseWindowsForms` flag, as that is for WinForms and not WPF.

**Comment by rladuca** [comment]
That's correct, the set of binaries that are referenced when you make a new desktop framework WPF application do not include PresentationFramework.Aero.  This is also not referenced from a new Windows Forms application.

Adding the reference manually seems to be entirely appropriate.

@twsouthwick Are you saying that compiling for netcoreapp3.0 does automatically reference PresentationFramework.Aero?

**Comment by twsouthwick** [comment]
Sorry for the confusion - I meant `<UseWPF>true</UseWPF>`. The project has both of them and copied the first one I have.

@rladuca The project compiles fine for netcoreapp3.0, but now that I'm looking at it, it doesn't reference `PresentationFramework.Aero`. The file that references the aero library is here: https://github.com/twsouthwick/HandBrake/blob/netcore/win/CS/HandBrakeWPF/Themes/Generic.xaml.

**Comment by livarcocc** [comment]
Issue moved to [dotnet/wpf #219](https://github.com/dotnet/wpf/issues/219) via [**ZenHub**](https://www.zenhub.com/)
