### ISSUE TITLE
Need "Designer.RuntimeConfig.Json" at design-time compilation for the designers (WPF and Winforms) to work 

### ISSUE THREAD

**Issue by chabiss** [dotnet/sdk#2707]
The surface processes for WPF and Winforms will be shipped as part of VS, but they will not include the generated runtimeconfig.Json in the setup. 

When a new project is created, we need the designer process to know which framework the surface process needs to bind to. For this, a design-time build needs to provide the runtime config for the process to use in order to launch the surface process. 

The flow is as follow: 

1.	Generating Designer.RuntimeConfig.Json (Designer.Deps.Json) and at design-time. 

- Those design file should be generated under the obj directory
- "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true” needs to be included in the config file.

2.	New OutputGroups "DesignerOutput"?  that gives us all the files that need to be copied into ShadowCache. This would include the generated Designer.RuntimeConfig.Json 

- Project.ConfigurationManager.Configurations.Item.OutputGroups("DesignerOutput")

**Comment by nguerrera** [comment]
I'm going to move this to dotnet/cli to track on our ZenHub board.

**Comment by nguerrera** [comment]
Scratch that, all of our repos are linked to ZenHub. No need to move.

**Comment by nguerrera** [comment]
I've hit a snag with this.

The plan we established calls for generating .deps.json to intermediate directory in design-time builds.

However, the correct generation of the .deps.json depends on @(ReferenceSatellitePaths) and @(ReferenceDependencyPaths)

https://github.com/dotnet/sdk/blob/549597f4fbdfea526a1022cb1c81ed754888ee36/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L137-L138

And these are not populated by RAR when $(BuildingProject) is false:
https://github.com/Microsoft/msbuild/blob/b2db71bebaae4f54f7236ca303e2b0a14aca1a0d/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2088
https://github.com/Microsoft/msbuild/blob/b2db71bebaae4f54f7236ca303e2b0a14aca1a0d/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2130

Now, at the moment, there's a bug causing FindDependencies to happen in CPS design time builds:
https://github.com/Microsoft/msbuild/issues/2417

But we can't depend on this bug or we'll block fixing it and it's a known performance problem.

I think we could consider running the designer project without a .deps.json, but that would have some subtly different behaviors from the project under design. It will also require that we include nuget package dependencies in the shadow copy set.

cc @davkean @rainersigwald @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
That is unfortuante.  I believe we can make this work without a deps.json (as it is optional).  For simple apps (eg. all the dependencies live in the root directory) it will just work.

For more complex apps (eg. ones with native dependencies or with platform specific dependencies) WPF designer will need to probe to find the right ones and load it.  This is not impossible, but will have a tail of oddness and in some cases it will just be a guess.   The good thing is that simple apps are by far the most common, then most common are apps with 'typical' native dependencies, and finally rare are those apps with exotic dependencies where probing will have to guess.

cc @vitek-karas @sdmaclea

**Comment by chabiss** [comment]
We need to be careful about asking WPF designer of getting into the business of "figuring out" the probing path.  We are not going got into that business if a given team already had solved that problem..  Don't forget that we need to load fast, and minimizing any shadow copying of files as much as possible is necessary.  Also in the case where the project is built, we dot want the WPFSurface.exe to reuse the built  .deps.json.  So having WPFSurface.exe using deps file or not needs to be configurable.

**Comment by sdmaclea** [comment]
@nguerrera Can you set `_ResolveReferenceDependencies = true` at design time to keep the behavior after Microsoft/msbuild#2417 is fixed?

**Comment by nguerrera** [comment]
That would undo the fix. The point is that it's expensive to walk all the friends l dependencies and design time build isn't supposed to do that. Also, I think the results will vary depending on what's on disk during the design time build.

**Comment by davkean** [comment]
@nguerrera Perhaps we should sync up on this this? I agree on @chabiss statement, but am very mindful of the performance impact of this. It's also not clear to me the exact implications of this:

> but that would have some subtly different behaviors from the project under design. It will also require that we include nuget package dependencies in the shadow copy set.

**Comment by vitek-karas** [comment]
Just curious, why do we need to set the `Microsoft.NETCore.DotNetHostPolicy.SetAppPaths` property? Is this so that the designer doesn't have to tweak the `.deps.json` to get some of the assemblies it needs?

**Comment by nguerrera** [comment]
@vitek-karas, yes, I believe that was exactly why.

**Comment by nguerrera** [comment]
@chabiss Thinking about this some more, what is the expected behavior when there's a project reference to an assembly that either hasn't been built yet? What about when the project reference code is modified since last build?

> @nguerrera Perhaps we should sync up on this this?

Yes. I'll set something up.

**Comment by nguerrera** [comment]
Tagging @lutzroeder to get everyone from the meeting onto this thread.

**Comment by nguerrera** [comment]
I guess the renaming point is moot since designer has to rename anyway to match surface process.

**Comment by nguerrera** [comment]
Tagging @DustinCampbell

**Comment by chabiss** [comment]
LGTM.
