### ISSUE TITLE
C# Console App template doesn't use namespace for Program class, but adding classes will have a namespace

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#271]
The .NET Core Console application template doesn't use a namespace in [Program.cs](https://github.com/dotnet/sdk/blob/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpConsoleApplication/Program.cs).  That is simpler and cleaner, but if you add a class to the project from Visual Studio, the new class will be inside the default namespace for the project.  This means you'll have to add a using statement to `Program.cs` to use any additional classes.

Possible fixes I can think of:
- Do nothing, let people rely on quick fixes to add the using statement if they need it
- Add `using $safeprojectname$;` to the `Program.cs` template
- Update the `Program.cs` template to put the `Program` class inside the default namespace for the project
- Get rid of default namespace for console apps in the SDK altogether.  This would probably mean a condition in the targets that only sets the default namespace for class libraries (or some similar criteria).  The new class template in VS (and maybe all code templates) would need to be updated so that it doesn't try to put the class in a namespace if the default namespace is empty.

**Comment by davidfowl** [comment]
Why isn't this fixed yet? There should be a namespace.

**Comment by davkean** [comment]
It wasn't fixed because you never submitted a PR. :)

The namespace was removed just to simplify the Hello World, we can add it back.
