### ISSUE TITLE
SNK is not considered when determining if a re-build is required

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/sdk#2710]
1. Build a project which has InternalsVisibleTo into another project using any given StrongNameKey.
2. Build the project again, with a different StrongNameKey.
3. See an error like:
```
Friend access was granted by 'Microsoft.Extensions.Configuration.UserSecrets, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35', but the public key of the output assembly ('0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.
```
The base project wasn't rebuilt with the new key.

**Comment by natemcmaster** [comment]
It appears to be the result of MSBuild incremental builds. If both StrongNameKey1.snk and StrongNameKey2.snk have a modified timestamp older than compiled output, the "CoreCompile" target will be skipped because "all output files are up-to-date with respect to the input files".

**Comment by dasMulli** [comment]
Did the name of the file change via some build property or did the key file change?

**Comment by natemcmaster** [comment]
There were multiple snk files already on disk and we just changed the AssemblyOriginatorKeyFile property.

**Comment by dasMulli** [comment]
In the project file itself or an imported target that didn't add itself to `MSBuildAllProjects`? This is what would have previously caught such a change.
It could be fixed with a change similar to https://github.com/Microsoft/msbuild/pull/3978

**Comment by natemcmaster** [comment]
> In the project file itself or an imported target that didn't add itself to MSBuildAllProjects?

I was under the impression MSBuild did that automatically now... @ryanbrandenburg which version of MSbuild/dotnet were you using?

**Comment by ryanbrandenburg** [comment]
15.9.19.36755

**Comment by rainersigwald** [comment]
> I was under the impression MSBuild did that automatically now...

In 16.0 builds it does now.
