### ISSUE TITLE
2.2.100 final release can be installed side-by-side with the 2.2.100 from 2.2.1xx latest feed

### ISSUE THREAD

**Issue by poke** [dotnet/sdk#2711]
I downloaded the 2.2.100 SDK earlier today from [dotnet/core-sdk](https://github.com/dotnet/core-sdk#installers-and-binaries) which gave me a `dotnet-sdk-latest-win-x64.exe`. That SDK has been versioned as 2.2.100 for a while already and when installing it, it _is_ a 2.2.100 SDK that is being installed.

Now, on [dotnet.microsoft.com](https://dotnet.microsoft.com/download), the 2.2 release is now official and a final release for 2.2.100 is available.

Upon comparing the `dotnet-sdk-2.2.100-win-x64.exe` with the installer downloaded earlier showed that it is actually a different file, although both are expected to contain 2.2.100. What’s worse, I can install both versions side-by-side so I actually get two entries in Windows:

![Two identical SDKs in programs & settings](https://user-images.githubusercontent.com/132240/49457558-5594f200-f7eb-11e8-9231-1629d6bb7b65.png)

Of course, since both SDKs have the same version, they both installed into the same folder, so the `dotnet` CLI will only see one SDK. But ideally, the previously released 2.2.100 SDK should have either be the identical version as the now-released final 2.2.100, or it should have been a different version.

**Comment by livarcocc** [comment]
@mmitche another side effect of prodcon. Though, it is not clear to me why latest would have been updated and how.

**Comment by livarcocc** [comment]
Closing this issue as we have moved to build 2.2.101 which moved the latest link on the page.
