### ISSUE TITLE
Build should raise a good error if the project hasn't been restored

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#272]
I know this can't be fixed wholly in the `dotnet/sdk`, but this SDK owns this experience, so logging here to track the full end-to-end experience.
## Repro:

```
dotnet new -t msbuild
dotnet build3
```
## Expected results:

I expect to get a decent error message that says my project hasn't been restored.

Even better - if it could restore my project for me and build correctly that would be great.  But I'll settle for a good error message.
## Actual results:

The project builds for `[assembly: TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]` which is not what is specified in my `<TargetFramework>` property.  No error, no warning.  Just a successful, incorrect build.

**Comment by srivatsn** [comment]
This will be resolved with #415 since the SDK will always be there before a build.
