### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the Specified RuntimeIdentifier'browser-wasm'

### ISSUE THREAD

**Issue by tomsummerfield** [dotnet/sdk#27238]
### Describe the bug
Hi,

I'm getting this bug all of sudden There was no runtime pack for Microsoft.AspNetCore.App available for the Specified RuntimeIdentifier'browser-wasm'.

Iv update my SDK, made sure the client and web Project SDK are correct and it still wont load the application. 

The WebAPI runs and the code compiles, itsthe client side where i am having the issue of loading my webapp.

<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseBlazorWebAssembly>true</UseBlazorWebAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.7" />    
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />    
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.8">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UdemyClone.Api\UdemyClone.Api.csproj" />
    <ProjectReference Include="..\UdemyClone.Models\UdemyClone.Models.csproj" />
  </ItemGroup>

</Project>

Visual Studio 2022

**Comment by marcpopMSFT** [comment]
Can you provide the details of what SDK you're using that this started in (dotnet --info), what's the full message you're seeing, and potentially the https://aka.ms/binlog?
