### ISSUE TITLE
How to debug msbuild?

### ISSUE THREAD

**Issue by xoofx** [dotnet/sdk#2723]
Hey,

So I would like to investigate a problem related to [slow RAR in msbuild](https://github.com/Microsoft/msbuild/issues/2015) and while I have been able to initially hack something to debug msbuild, that was very convoluted, copying files around from regular Sdk...etc.

So I would like to do this more cleanly and follow a more deterministic procedure to debug directly MsBuild project from MsBuild.sln solution  (so it is issuing a dotnet msbuild.dll or msbuild.exe)  for 
1.  new csproj with .NET Sdk
2.  regular old csproj 

Which repository should I build, variable that I should set...etc.? (Or I could avoid building by reusing maybe an installed dotnet folder?)

## For new csproj

Let's try just on the new csproj format for now, starting with a plain `dotnet new --name Helloworld`

Assuming that I built this repository, and I'm setting the MSBuildSDKsPath to point to the `artifacts\Debug\bin\Sdks`

I'm getting the following error:

![image](https://user-images.githubusercontent.com/715038/49525579-5a6eaa00-f8ae-11e8-9220-1c9166120934.png)

```
Project "C:\Work\tmp\HelloWorld\Helloworld.csproj" on node 1 (default targets).
C:\Code\dotnet\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props(33,11): error MSB4226: The imported project
 "C:\Code\msbuild\artifacts\Debug\bin\MSBuild\net472\Current\Microsoft.Common.props" was not found. Also, tried to find
 "Current\Microsoft.Common.props" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)
\MSBuild" . These search paths are defined in "C:\Code\msbuild\artifacts\Debug\bin\MSBuild\net472\MSBuild.exe.Config".
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search pat
hs. [C:\Work\tmp\HelloWorld\Helloworld.csproj]
Done Building Project "C:\Work\tmp\HelloWorld\Helloworld.csproj" (default targets) -- FAILED.
```

It is trying to resolve `artifacts\Debug\bin\MSBuild\net472\Current\Microsoft.Common.props` which is not in this folder.
Not sure why it is trying `Current` by default, while the solution seems to build in this file in `artifacts\Debug\bin\15.0\Microsoft.Common.props` , so assume that the tooling version should be 15.0... but still, can I setup a MsBuild special variable path for pointing to this folder?

So likely after that, it will complain about missing NuGet resolver or similar. How do I pass them through?

cc: @davkean @nguerrera

**Comment by nguerrera** [comment]
Not at a work computer yet, but IIRC there should be a bootstrap copy of msbuild with your bits and more supporting files from elsewhere in a different output folder after a successful command line build.

cc @rainersigwald

**Comment by nguerrera** [comment]
You can run `eng\dogfood.cmd` to get an environment where all msbuilds should use your freshly built dotnet/sdk bits. 

https://github.com/dotnet/sdk/blob/7bb277dbfdfe52a71b9decc88897510cc8d6be42/eng/dogfood.ps1#L36-L41

**Comment by nguerrera** [comment]
(But I need to check if that script survived recent infrastructure changes.)

**Comment by xoofx** [comment]
By default from VS, it is running `C:\Code\msbuild\artifacts\Debug\bin\MSBuild\net472\msbuild.exe` which doesn't have the `Current` folder, while the `netcoreapp2.1` folder has it (don't remember how to force to run `netcoreapp2.1` actually) which is adding to the confusion

**Comment by xoofx** [comment]
> You're trying to run a just-built MSBuild (in the MSBuild repo) from VS? That doesn't work. You can build from the command line and run the bootstrapped MSBuild from 

Ouch, ok, so you do that even if you want to quickly iterate on msbuild? (building bootstrap takes 20s even if there are no changes typically)

**Comment by rainersigwald** [comment]
Yes. There's definitely room for improvement, but IIRC we ran into a lot of problems integrating the bootstrap process with the msbuild.exe project, because we produce NuGet packages from the project and must not pollute them with a bunch of extra files.

**Comment by xoofx** [comment]
> Yes. There's definitely room for improvement, but IIRC we ran into a lot of problems integrating the bootstrap process with the msbuild.exe project, because we produce NuGet packages from the project and must not pollute them with a bunch of extra files.

Ok, it seems to work and better than all the fragile hacks to setup the correct env variables I was previously using....
I will try to workaround the iteration maybe by adding a task to copy of the relevant assemblies directly to the output folder. 
Thanks!
