### ISSUE TITLE
Uninstalling may be not enough

### ISSUE THREAD

**Issue by zawor** [dotnet/sdk#2725]
@KathleenDollard asked me to post dotnet/docs#9412 here so here we go:

Had a lot of runtimes and sdks accumulated over time on my dev machine. At some point i decided to do the cleanup and uninstalled quite a few from under appwiz.cpl (or add/remove programs). Unfortunately after running `dotnet --list-sdks` or `dotnet --list-runtimes` i still saw those which were uninstalled... Interestingly enough i discovered that installers have left a lot of empty dirs under `C:\Program Files\dotnet\sdk`, `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All` and `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`. Removing those made `--list-sdks` and `--list-runtimes` to no longer list uninstalled runtimes/sdks.

**Comment by johnbeisner** [comment]
Duplicate issue as: https://github.com/dotnet/cli/issues/9222
