### ISSUE TITLE
Which one is latest version of .NET Core 2.2.100 or 2.2.200-preview-009648

### ISSUE THREAD

**Issue by sarbjithanjra** [dotnet/sdk#2726]
Hi on 5 Dec 2018, I downloaded the .NET Core SDK with version 2.2.100 and after install on my sytem, i checked that there is an existing 2.2.200-preview-009648 version is installed. Please let me know which one latest? it seem 2.2.100 is latest as per download page but from version number it seem 2.2.200 is latest.

**Comment by livarcocc** [comment]
2.2.100 is the latest release for 2.2.

We have a new release that is in preview, called 2.2.200, so that the latest for that version. The big difference between them is that 2.2.200 contains new versions of roslyn, fsharp, msbuild and nuget.
