### ISSUE TITLE
Not getting the output code that I expected: 'dotnet new console'

### ISSUE THREAD

**Issue by MojoMoe** [dotnet/sdk#27323]
My PC Setup:
Windows 11 (all current/latest updates installed)
.NET SDK 6.04
PowerShell v7.2.6
Visual Studio Code 2022 v1.70.2

I am just starting out my dotnet journey and started a course on LinkedIn Learning today. When the instructor uses this command in Windows CMD (in Windows 10?) with dotnet version 5.0:  
`dotnet new console`

For the instructor the generated Program.cs file contains the following code:
******************************
using System;

namespace HelloWorld
{
    
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
} 
******************************************
When I run the same code in VS Code Terminal: 
`dotnet new console`

The generated Program.cs file contains this code:
****************************************
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
***************************************
I was expecting to see the same code generated for me as it was for the instructor (see above code). Am I doing anything wrong? I am not sure if it's a template issue (I currently don't know anything about dotnet templates as I've only just started out learning dotnet/C# today!) or if this is the normal expected behaviour of dotnet 6.0.4. Not sure if this is a dotnet issue or something not right on my Windows 11 build. 

PS. I have added lines to make the code clearer because GitHub is messing up the code.

**Comment by baronfel** [comment]
Hello, and welcome! The different template outputs are in fact because of the different versions of .Net - in .Net 6 we changed the console template to use several newer C# features like 'file scoped namespaces' and 'top level statements'. 

In C# 6 you can get closer to the C# 5 template style if you use 'dotnet new console --use-program-main', or you can use the old template content entirely - it all still works in .Net 6.

**Comment by MojoMoe** [comment]
> Hello, and welcome! The different template outputs are in fact because of the different versions of .Net - in .Net 6 we changed the console template to use several newer C# features like 'file scoped namespaces' and 'top level statements'.
> 
> In . Net 6 you can get closer to the .Net 5 template style if you use 'dotnet new console --use-program-main', or you can use the old template content entirely - it all still works in .Net 6.

Hi baronfel. Thanks very much for the super quick response. I have tried this as suggested:

dotnet new console --use-program-main

However the generated code is still slightly different when compared to the output the instructor is getting:

*********************************************************
namespace HelloWorld;
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
    }
}
*****************************************************

You mentioned I can use the 'old template content entirely', can you please tell me how I can go about configuring this on my system? Or point me to a link/info somewhere? 

Because I'd like to get the same output as the instructor so I can follow along on the tutorials and a because I am still new to dotnet and C#, I'd prefer to get the same output as his so I don't get lost/confused. Thanks.

**Comment by baronfel** [comment]
If your instructor is using .net SDK 5 for the class, I would highly suggest using a global.json file ('dotnet new globaljson --sdk-version 5.0.xxx', where 'xxx' is whatever your instructor wants to use). This file tells the .NET SDK which version to use when multiple versions are available (as in your case). This should keep you aligned to what your instructor expects.

I might mention to your instructor that .Net 5  is out of support now (https://dotnet.microsoft.com/platform/support/policy/dotnet-core) so they might want to consider updating.

**Comment by danmoseley** [comment]
@MojoMoe  as @baronfel says, welcome to the dotnet ecosystem. Do let us know if you run into other problems. (A Discussion might be better than an Issue.) feel free to tag me.

**Comment by MojoMoe** [comment]
@baronfel @danmoseley  Hi guys, thank you both for the responses, it is very much appreciated. Since this is not a bug, please feel free to close this 'issue'. Thanks very much :)
