### ISSUE TITLE
Incorrect "repository" element in Microsoft.NET.Sdk's nuspec

### ISSUE THREAD

**Issue by dagood** [dotnet/sdk#2733]
In this nupkg from a recent build:
https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.net.sdk/3.0.100-preview.18603.1/microsoft.net.sdk.3.0.100-preview.18603.1.nupkg

The nuspec contains this line:

```
<repository type="git" url="https://github.com//" commit="7bb277dbfdfe52a71b9decc88897510cc8d6be42" />
```

`https://github.com//` should be `https://github.com/dotnet/sdk`

This might be an Arcade issue, failure to detect the source? I'm not familiar enough with how packaging works now to quickly find where this is happening.

(I was only looking for the commit, but figured I should file this issue for the wrong url anyway.)

**Comment by livarcocc** [comment]
cc @tmat @chcosta

**Comment by livarcocc** [comment]
How import is it to fix this though, given that it is a transport package only?

**Comment by tmat** [comment]
This has been fixed recently: https://github.com/dotnet/arcade/pull/1489

**Comment by livarcocc** [comment]
Closing it here then since arcade will flow into dotnet/sdk with DARC.
