### ISSUE TITLE
`dotnet restore` doesn't restore dependencies included in a `.props` file from a referenced package

### ISSUE THREAD

**Issue by gtbuchanan** [dotnet/sdk#27383]
### Describe the bug
`dotnet restore` doesn't restore dependencies included in a `.props` file from a referenced package's `build` folder. The expected `obj/*.nuget.g.props` is generated when the project is loaded in Visual Studio, but it is promptly overwritten when running either `dotnet restore` or `dotnet build`.

### To Reproduce

Build the attached reproduction solution, `ConsumingPackage/ConsumingPackage.sln`, in Visual Studio and take a look at the `obj/ConsumingPackage.csproj.nuget.g.props` file. Then, run `dotnet build` on the same solution to see the build fail and modify the aforementioned `.props` file to exclude the referenced package, `JetBrains.Annotations`.

[NuGetPropsBug.zip](https://github.com/dotnet/sdk/files/9410798/NuGetPropsBug.zip)

### Exceptions

```text
NuGetPropsBug\ConsumingPackage\Class1.cs(5,6): error CS0246: The type or namespace name 'PublicAPIAttribute' could not be found (are you missing a using directive or an assembly reference?)
```

### Further technical details
```text
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Visual Studio 17.3.1

**Comment by baronfel** [comment]
Did this work in previous versions of the SDK?

**Comment by gtbuchanan** [comment]
@baronfel I'm not quite sure. This was the first time I've tried it. I got through setting everything up and then found out this scenario only seems to work in Visual Studio. That's the only reason I marked it as a bug. I couldn't figure out why the NuGet Package Manager in VS works fine but not when using `dotnet restore` or `nuget restore` directly. VS seems to go through multiple restores in this situation but I couldn't emulate what VS is doing via CLI.

**Comment by baronfel** [comment]
I'm glad to hear you say that, actually. I did not expect this to work from command line restores at all. I don't believe that nested PackageReferences like you describe are supported, though I'd like confirmation/backup from someone on the NuGet side (@nkolev92?) about that.

Can you talk more about the package that you're using that provides these props? I'm curious why it's exposing package references instead of using the more standard dependencies inside the nuspec file.

**Comment by nkolev92** [comment]
That is correct, PackageReference (and in general NuGet restore affecting props/items) are not supported in the props/targets of packages. 

https://docs.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets#guidance-for-the-content-of-msbuild-props-and-targets

**Comment by gtbuchanan** [comment]
@baronfel I appreciate you taking a look at this. It's essentially a meta package. We have many repositories that share a common configuration and I was trying to have a single package that intelligently references necessary analyzers and common packages based on convention (e.g. the assembly does/doesn't end with `.Test`, uses certain target frameworks). I should be able to move most of the references directly into the project as you suggested and use multi-targeting. Doesn't sound like the conditional logic based on assembly naming will work, though.

@nkolev92 Thank you for the reference! I can't believe I didn't come across that page in my research...

**Comment by shivanshsr-hub** [comment]
@nkolev92 @baronfel Can we use the MsBuild package (PackageType>MSBuildSdk</PackageType>) and include the dependent references inside Sdk.props? I believe nuget restore would work for it. Is it advisable to do so?
