### ISSUE TITLE
TargetFrameworkMoniker is not available until first restore

### ISSUE THREAD

**Issue by natidea** [dotnet/sdk#274]
Since the TargetFrameworkInference targets live in this SDK, they are not available until after a project is restored. Some scenarios require this sooner (e.g. to generate a TargetFrameworkMoniker to send to NuGet's nominate restore API), especially to enable using the full framework name as the canonical handshake everywhere.

**Comment by srivatsn** [comment]
Since the SDK is now guaranteed to be present, this is no longer an issue.
