### ISSUE TITLE
web.config processPath is different when using --runtime argument with dotnet publish

### ISSUE THREAD

**Issue by peeveen** [dotnet/sdk#27408]
### Describe the bug
Running `dotnet publish` on an ASP.NET Core project generates a `web.config` file.
But if you specify a `--runtime` argument, the `web.config` contains a different value for `processPath`.

### To Reproduce
On (for example) Windows, with any simple ASP.NET Core project, running `dotnet publish` will generate a `web.config` file with this content:

```
<aspNetCore processPath="dotnet" arguments=".\myProject.dll" ... />
```

But running `dotnet publish --runtime win10-x64 --no-self-contained` creates a `web.config` that contains this:

```
<aspNetCore processPath=".\myProject.exe" ... />
```

I wouldn't mind, but attempting to host the app with the "exe" config in IIS (with the ASP.NET Hosting Bundle installed) yields [this problem](https://github.com/dotnet/aspnetcore/issues/11738), whereas the "dotnet + dll" config works great. (I think it's something to do with hosting the webservice in a subfolder of my IIS site? But I digress ...)

I've tried supplying my own `web.config` and using `IsTransformWebConfigDisabled`, but annoyingly, it _still_ overwrites the `processPath` property.

We're running automated builds for Windows & Linux in a Linux image, so using the `--runtime` argument is important. I'm just don't understand why it's so keen to change `processPath`.

**Comment by baronfel** [comment]
That's happening because specifying a runtime value by default creates an AppHost - a shim executable that launches your application dll. You can control this behavior by setting UseAppHost to false in your project file (or directly on the build/publish command). Can you try this and see if it solves your issue?
