### ISSUE TITLE
Incorrect translation for WorkloadUpdatesAvailable for some languages

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#27424]
The [WorkloadUpdatesAvailable](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx#L297-L299) resource is incorrectly translated for some languages:

```xml
  <data name="WorkloadUpdatesAvailable" xml:space="preserve">
    <value>Workload updates are available. Run `dotnet workload list` for more information.</value>
  </data>
```

For some languages, "dotnet workload list" is being translated, when it should be untranslated as it is a command to be typed in.  For example, [French](https://github.com/dotnet/sdk/blob/cae591210531dc36615f9cd78fc79af9834e1084/src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf#L365-L369):

```xml
      <trans-unit id="WorkloadUpdatesAvailable">
        <source>Workload updates are available. Run `dotnet workload list` for more information.</source>
        <target state="translated">Des mises à jour de la charge de travail sont disponibles. Exécutez « liste des charges de travail dotnet » pour plus d’informations.</target>
        <note />
      </trans-unit>
```

And [Portuguese](https://github.com/dotnet/sdk/blob/cae591210531dc36615f9cd78fc79af9834e1084/src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf#L365-L369):

```xml
      <trans-unit id="WorkloadUpdatesAvailable">
        <source>Workload updates are available. Run `dotnet workload list` for more information.</source>
        <target state="translated">As atualizações de carga de trabalho estão disponíveis. Execute ' lista de cargas de trabalho dotnet ' para obter mais informações.</target>
        <note />
      </trans-unit>
```

Some languages are translated correctly, and I haven't checked each one.

**Comment by marcpopMSFT** [comment]
Filed an internal translation request as if we take the linked PR, the internal flow will just overwrite that.
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/699988

**Comment by marcpopMSFT** [comment]
I believe this should be fixed now as the linked loc issue is resolved.
