### ISSUE TITLE
Option to treat NETSDK warnings as errors

### ISSUE THREAD

**Issue by nphmuller** [dotnet/sdk#2748]
While updating to 2.2.100 I noticed a couple of warnings were added. Like `NETSDK1071`.
In my CI I build using the `TreatWarningsAsErrors` flag (`dotnet build /p:TreatWarningsAsErrors="true"`)`.

The build still completed succesfully, while `NETSDK1071` was thrown.

What is the recommended way to force a build to fail if any of these warnings are thrown from the SDK?
The most user friendly way would be to use the same flag as msbuild. But that doesn't seem to be supported atm.

**Comment by rainersigwald** [comment]
You can use the universal MSBuild flag with `dotnet build /warnaserror`. Confusingly, the `TreatWarningsAsErrors` is fairly specifically scoped down to compiler warnings (though other tasks have the option of opting in to it as well). That property was added before MSBuild added support for `msbuild.exe /warnaserror`.

**Comment by nphmuller** [comment]
Thanks for the quick response!

**Comment by Crono1981** [comment]
This still causes the build to exit with a success code when warnings occurs. :(

**Comment by nphmuller** [comment]
@Crono1981 Might be better to open a new issue for that. Would probably give you a proper response faster.

**Comment by Crono1981** [comment]
@nphmuller https://github.com/dotnet/core-sdk/issues/1708
