### ISSUE TITLE
dotnet clean requires a RID if SelfContained=true in project file but no RID is set

### ISSUE THREAD

**Issue by jtschuster** [dotnet/sdk#27488]
### Describe the bug
Running dotnet clean with <SelfContained>true</SelfContained> in the project file will fail and return an error.

```
error NETSDK1031: It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier. You must either specify a RuntimeIdentifier or set SelfContained to false.
```

It doesn't seem like it should be necessary to set a RID for `dotnet clean`.

### To Reproduce
Create a project file with SelfContained
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
</Project>
```

Run `dotnet clean`.

### Further technical details
dotnet --info:
.NET SDK:
 Version:   7.0.100-rc.2.22417.1
 Commit:    f3da421a6e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22417.1\

Host:
  Version:      7.0.0-rc.1.22411.12
  Architecture: x64
  Commit:       f52d8c59bb

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22417.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22415.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22411.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22379.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by nagilson** [comment]
Not surprised this happens, though this is an interesting scenario. Thanks for reporting it @jtschuster. Verified that this is fixed already by https://github.com/dotnet/sdk/pull/26143 for rc-2. Except, we will be making `clean` rid-specific here. Going to ask if we care about that or not, I don't think we do.

**Comment by marcpopMSFT** [comment]
If folks want a dotnet clean --all, we should track as a separate issue and come up with a design as that's not as easy as it sounds.

**Comment by baronfel** [comment]
Would appreciate any feedback on `dotnet clean --all` here: https://github.com/dotnet/sdk/issues/22692

**Comment by rkm** [comment]
Just stumbled onto this same issue. Could the solution be as simple as adding the `--use-current-runtime` option to `dotnet clean` like we have for the other commands?

**Comment by baronfel** [comment]
@rkm it doesn't look like `clean` supports `--use-current-runtime`: https://github.com/dotnet/sdk/blob/f65053d80604949ed62c663e3e6975bc75273ba6/src/Cli/dotnet/commands/dotnet-clean/CleanCommandParser.cs#L48-L56

We'd need to add `command.Options.Add(CommonOptions.CurrentRuntimeOption(LocalizableStrings.CmdCurrentRuntimeOptionDescription))` to this list to enable it - would you be interested in sending that PR?

**Comment by rkm** [comment]
Definitely! I will send a PR
