### ISSUE TITLE
[NetSDKE2E]With NET7 RC1 VAL build installed, install Maui workload in CLI failed with error "microsoft.maui.core.ref.android not found in Nuget feeds...".

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#27582]
Install .net7 RC1 VAL build: 7.0.100-rc.1.22429.3 on windows x64 OS.

Execute below command in CLI to install maui workload
dotnet workload install maui --skip-manifest-update

below error occurred
![image](https://user-images.githubusercontent.com/65637796/187592170-a9a3c7d5-dd6b-4f1f-8bb8-ccee8ff8fd7a.png)

Same issue when dotnet workload install android --skip-manifest-update

**Comment by yinjiehe01** [comment]
This issue reproes on Mac OS
![Screenshot 2022-08-31 at 14 06 37 1](https://user-images.githubusercontent.com/106043488/187606460-ee83569d-3e0e-4520-93a3-837358cbf2a8.png)

**Comment by marcpopMSFT** [comment]
Try using the public feeds from this link: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25763/MAUI?anchor=d17.4-branch-/-pr  I think all maui builds end up on the .net public feeds.
