### ISSUE TITLE
 [NetSDKE2E]With .NET 7 RC2 SDK, run failed for .NET 7 winforms/wpf.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#27685]
Repro steps:
Install .NET 7.0.100-rc.2.22454.1from https://github.com/dotnet/installer
Create winforms or wpf(.NET) in CLI.
dotnet build and run

Expected Result
dotnet run successfully

Actual Result:
Below error occurred
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/106054229/188538610-ecc55cd3-0c2a-47f5-ad25-9c2aad0d4760.png)

note:The same happens in vs
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/106054229/188538943-c5a7ec53-1428-4092-890a-0bb92cf76b03.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/106054229/188538983-bd3bb277-dd94-4052-b77b-0883de20a135.png)

Dotnet --info:
C:\Users\v-ainigao>dotnet --info
.NET SDK:
 Version:   7.0.100-rc.2.22454.1
 Commit:    330dee39e5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22454.1\

Host:
  Version:      7.0.0-rc.1.22422.12
  Architecture: x64
  Commit:       ef077d0b58

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.7.22377.5 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22454.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.7.22376.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22426.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22422.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.7.22377.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22426.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by WenJunJi01** [comment]
With .NET 7 RC2 SDK, it can also repro on windows arm64.
![image](https://user-images.githubusercontent.com/87680983/188558595-01833635-0e34-4587-9ed1-9dd89824c4bd.png)

**Comment by v-ainigao** [comment]
This bug does not reproduce .net 7.0.100-rc.2.22466.28(runtime-7..0.0-rc.2.22464.1) SDK
