### ISSUE TITLE
Make sure all projects add themselves to MSBuildAllProjects

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#277]
Reminded by #276 that we're not doing this everywhere.

**Comment by dsplaisted** [comment]
Should .props and .targets files that ship as part of MSBuild, as well as the ones NuGet generates in the obj folder, be added to `MSBuildAllProjects`?

@nguerrera @rainersigwald

**Comment by nguerrera** [comment]
I think they should. I wish MSBuildAllProjects was magic.

**Comment by rainersigwald** [comment]
@dsplaisted yes they should

@nguerrera that'd be pretty nice, wouldn't it. File a bug on us?

**Comment by dsplaisted** [comment]
OK, I've filed Microsoft/MSBuild#1298, dotnet/roslyn#14870, NuGet/Home#3851, and dotnet/cli#4571 for the imports I found that weren't adding themselves during a build of a .NET Standard library using the .NET SDK.
