### ISSUE TITLE
 The library 'libhostpolicy.so' required to execute the application was not found in

### ISSUE THREAD

**Issue by vitlav** [dotnet/sdk#2772]
## Steps to reproduce
* get the latest SDK binaries (2.1.6, f.i.) and put them on the path (on /usr/lib64/dotnet-bootstrap/ dir actually in my case)
* create empty dir with some old version:
  mkdir /usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App/2.0.5
* `dotnet new console`
* `dotnet run`

## Expected behavior
Program runs and prints hello world.

## Actual behavior
```
/usr/lib64/dotnet-bootstrap/sdk/2.1.500/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App/2.0.5'.

The build failed. Please fix the build errors and run again.
```

 $ ls /usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App/
 2.0.5  2.1.6

Why it selected random 2.0.5 as preffered version?

## Environment data
```
$ /usr/lib64/dotnet-bootstrap/dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     altlinux
 OS Version:  20170925
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/lib64/dotnet-bootstrap/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/lib64/dotnet-bootstrap/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/lib64/dotnet-bootstrap/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/lib64/dotnet-bootstrap/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App]

```

**Comment by livarcocc** [comment]
Can you be exact on the SDK that you are installing? We don't have a 2.2.2 SDK. Where did you acquire it?

If you should get 2.2.101 from https://get.dot.net if you want to work with .NE Core 2.2.

Also, you claim to be installing the 2.2.2 SDK, but you are using the 2.1.500, from the `dotnet --info` output above. Did you do anything special to your machine to be in this situation?

**Comment by vitlav** [comment]
> Can you be exact on the SDK that you are installing? We don't have a 2.2.2 SDK. Where did you acquire it?
> 
> If you should get 2.2.101 from https://get.dot.net if you want to work with .NE Core 2.2.
> 
> Also, you claim to be installing the 2.2.2 SDK, but you are using the 2.1.500, from the `dotnet --info` output above. Did you do anything special to your machine to be in this situation?
I was wrong, I used .NET Core 2.1.6 (2.1.500 SDK) — the latest 2.1.x downloaded package.
No special changes for this case: just downloaded, unpacked, do mkdir and voila.

**Comment by livarcocc** [comment]
Oh, wait, I missed this step:
> mkdir /usr/lib64/dotnet-bootstrap/shared/Microsoft.NETCore.App/2.0.5

Why are you doing this? It won't work. The host will try to use that version simply based on the presence of the folder, we don't check for the files inside of it for perf reasons.

If you remove that folder, does everything work?

**Comment by vitlav** [comment]
...
> Why are you doing this? It won't work. The host will try to use that version simply based on the presence of the folder, we don't check for the files inside of it for perf reasons.
Simply based? I guess there is a strange logic in a folder selection.


> If you remove that folder, does everything work?
Yes, it does. But why does it behave in this way when the folder is present?

**Comment by livarcocc** [comment]
Given that this is not really supported and akin to you messing up with the installation of the SDK, I am going to close this issue.

If you want to learn more about the host selection logic for runtimes, I suggest either looking through the code at dotnet/core-setup or maybe filling an issue there for more information either. That logic does not live on the dotnet/sdk repo.
