### ISSUE TITLE
`dotnet new` should suggest approximate matches for templates when no matching template is found

### ISSUE THREAD

**Issue by danroth27** [dotnet/sdk#27765]
If I try to run `dotnet new blazor`, no matching template is found, so I get this error:

```
C:\Users\daroth> dotnet new blazor
No templates found matching: 'blazor'.

To list installed templates, run:
   dotnet new list
To search for the templates on NuGet.org, run:
   dotnet new search blazor
```

It would be nice if the CLI suggested approximate matches for the template, something like: `Did you mean one of the templates?: blazorserver, blazorwasm, maui-blazor`.

**Comment by baronfel** [comment]
We actually just did this a week ago! https://github.com/dotnet/sdk/pull/27265
