### ISSUE TITLE
.NET Global Tools publish broken

### ISSUE THREAD

**Issue by jp2masa** [dotnet/sdk#2777]
.NET Global Tools publish uses the `PublishDepsFilePath` property to include the deps file, but it no longer exists (.NET Core 3.0 Preview 1).

This bug was introduced here: https://github.com/dotnet/sdk/commit/1936ebd7307cebd6c5d1d8d699b9844f73b8fb2c#diff-7dc833d02f198e5a9f0ab88e229db18aL520.

I believe that the property shouldn't have been removed.

**Comment by livarcocc** [comment]
@wli3 and @peterhuene to comment.

**Comment by peterhuene** [comment]
It does look like I accidentally removed this property during the big refactoring of the publishing code.

Thanks for finding this.  I think the linked PR is the right fix.
