### ISSUE TITLE
cli:  dotnet --latest

### ISSUE THREAD

**Issue by vbjay** [dotnet/sdk#27801]
### Is your feature request related to a problem? Please describe.
Being able to determine latest sdk version tied to x runtime version or runtime version from sdk version in the cli would be helpful.  

### Describe the solution you'd like

- ```dotnet --version``` could provide sdk and runtime version info together providing x runtime to sdk mappings so it would say you have sdk version and the tied runtime is x runtime.  
- ```dotnet --latest {major.minor}``` so like ```dotnet --latest 6.0``` or ```dotnet --latest lts``` would provide the same info as if you were to  go to https://dotnet.microsoft.com/en-us/download/dotnet/6.0  and see 
![image](https://user-images.githubusercontent.com/3629489/189456438-3bce07c7-7653-4f2c-bb52-1720e286a318.png)
so I would be able to say sdk 6.0.400 is tied to runtime 6..0.8.  

dotnet --latest lts would use the current major.minor LTS version of .net.

Could parse 
![image](https://user-images.githubusercontent.com/3629489/189457535-92b49522-5482-4852-b067-93e772b8e95c.png)
https://raw.githubusercontent.com/dotnet/core/main/release-notes/6.0/releases.json of course getting the correct versioned json file and  getting 

- "latest-release"
-  "latest-release-date"
-  "latest-runtime"
-  "latest-sdk"

 and any other fields needed.

**Comment by vbjay** [comment]
```powershell
$R= Invoke-WebRequest -Uri https://raw.githubusercontent.com/dotnet/core/main/release-notes/6.0/releases.json -ContentType "application/json"   -Method Get -UseBasicParsing
$x = $R.Content | Out-String | ConvertFrom-Json 
$x |Select-Object -Property latest-sdk,latest-runtime

```


Example using powershell.

**Comment by vbjay** [comment]
gitextensions/gitextensions/pull/10191 Shows the idea but using the release notes  json file.  I would love for the dotnet cli to provide this kind of info.

**Comment by baronfel** [comment]
We're working on improving .NET SDK acquisition, and one aspect of that story will be notifications/checks for what the latest up-to-date versions are. Thanks for the request!
