### ISSUE TITLE
SSR with .net6 and angular template

### ISSUE THREAD

**Issue by AssetSara** [dotnet/sdk#27839]
### Describe the bug
I'm trying to run SSR with .net6 and angular template and deploy the solution on azure app service, but can't do that is this not supported or what ?

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by baronfel** [comment]
Closing because the angular template is no longer part of the product starting in .NET 8.
