### ISSUE TITLE
net6.0-macos publishes a .pkg file

### ISSUE THREAD

**Issue by natan-abolafya** [dotnet/sdk#27841]
### Describe the bug
We have a net6.0-macos project that we currently run `dotnet build` to create an `.app` file and distribute. I wanted to try to enable trimming on the project which requires running `dotnet publish`. However, this creates a `<project-name>-1.0.1..pkg` under the publish folder. Yes double dots at the end. 

I would like an either `.app` file or all the files that we can package ourselves.

I came across a documentation that mentions `/p:CreatePackage=false` parameter but that didn't help.

Bonus: `<PublishTrimmed>true</PublishTrimmed>` doesn't do anything on the pkg file either but that's probably another issue when this one is resolved. Or maybe it's not even supported on net6.0-macos; just not documented.

### To Reproduce
Here is a small csproj file where you can create a file with Main function and try out.

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0-macos</TargetFramework>
        <ApplicationId>com.example.app</ApplicationId>
        <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
        <SupportedOSPlatformVersion>10.15</SupportedOSPlatformVersion>
    </PropertyGroup>
</Project>
```

And run
```
dotnet publish -c Release Example.csproj
```
### Further technical details
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.302 [/usr/local/share/dotnet/sdk]
  6.0.400-preview.22330.6 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by rolfbjarne** [comment]
> We have a net6.0-macos project that we currently run `dotnet build` to create an `.app` file and distribute.

The usual way of distributing macOS apps is to produce a .pkg.

> I wanted to try to enable trimming on the project which requires running `dotnet publish`.

You can trim any build (in fact for macOS projects the trimmer is always executed, but by default it doesn't trim away anything).

You can either set the `TrimMode` property (https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-6-0), or use the older `LinkMode` property used in Xamarin projects (and set it to `Full` (link everything), `LinkSdk` (link the BCL) or  `None` (the default - trim away nothing)).

> However, this creates a `<project-name>-1.0.1..pkg` under the publish folder. Yes double dots at the end.

The double dots looks like a bug.

> I would like an either `.app` file or all the files that we can package ourselves.

You can find the `.app` directory inside the bin/Release/net6.0-macos\[/\<RuntimeIdentifier\>\] directory.

Alternatively you can unpack the pkg using [`pkgutil --expand-full [pkg] [dir]`](https://stackoverflow.com/a/50835954/183422) and pick out what you want from there.


> Bonus: `<PublishTrimmed>true</PublishTrimmed>` doesn't do anything on the pkg file either but that's probably another issue when this one is resolved.

That's because `PublishTrimmed=true` is the default for net6.0-macos (you can't actually disable it), so enabling it again has no effect.

**Comment by rolfbjarne** [comment]
> > However, this creates a `<project-name>-1.0.1..pkg` under the publish folder. Yes double dots at the end.
> 
> The double dots looks like a bug.

I can't reproduce this with just a .cs file and your example for a project file. Do you have an `Info.plist` file as well in your project directory?

**Comment by natan-abolafya** [comment]
Hi, thank you.

> The usual way of distributing macOS apps is to produce a .pkg.

ok. We do packaging ourselves with other files. So I take it there is no way to disable this when publishing?

> That's because PublishTrimmed=true is the default for net6.0-macos (you can't actually disable it), so enabling it again has no effect.

OK, thanks for the info. Having worked with trimming on Windows and a bit of Linux, it seems a bit inconsistent. There the `<TrimMode>Link</TrimMode>` is default but not `PublishTrimmed`. It's also documented so here https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained. But I suppose there are reasons for that.

> You can find the .app directory inside the bin/Release/net6.0-macos[/<RuntimeIdentifier>] directory.

Will it be trimmed if it's enabled? Then I guess .pkg file is not that important to me in that case.

> I can't reproduce this with just a .cs file and your example for a project file. Do you have an Info.plist file as well in your project directory?

Yep, looks like it's our fault.
```
	<key>CFBundleShortVersionString</key>
	<string>1.0.1.</string>
```
Though not sure if it's us who put this there or it was visual studio.

**Comment by rolfbjarne** [comment]
> > The usual way of distributing macOS apps is to produce a .pkg.
> 
> ok. We do packaging ourselves with other files. So I take it there is no way to disable this when publishing?

`/p:CreatePackage=false` should prevent the creation of the .pkg - but that's all it does too (we're still going to build the .app that goes into the .pkg).

> > You can find the .app directory inside the bin/Release/net6.0-macos[/] directory.
> 
> Will it be trimmed if it's enabled? Then I guess .pkg file is not that important to me in that case.

Yes, it will be trimmed if you set  `TrimMode=...`  or `LinkMode=...`

**Comment by natan-abolafya** [comment]
> /p:CreatePackage=false should prevent the creation of the .pkg - but that's all it does too (we're still going to build the .app that goes into the .pkg).

I had tried that and it still created the .pkg file.

**Comment by natan-abolafya** [comment]
ok, now that I think about it, `/p:CreatePackage=false` would basically make `dotnet publish` the same as `dotnet build`, since `dotnet build` does the trimming already and creates all the files including the `.app` file. I believe you were already trying to explain that to me already :).

At the risk of repeating myself, I do think this is inconsistent with the regular dotnet trimming and the documentation https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained. But assuming there are reasons to that, like how things just work differently in the macOS world, I think at least it should be documented. But that's not really in the scope of this issue I guess, so I'll close this issue. Thanks again for the clarifications.

**Comment by rolfbjarne** [comment]
> > /p:CreatePackage=false should prevent the creation of the .pkg - but that's all it does too (we're still going to build the .app that goes into the .pkg).
> 
> I had tried that and it still created the .pkg file.

Just for the record: this is a bug that we already fixed (https://github.com/xamarin/xamarin-macios/issues/15696). It will be fixed for .NET 7.
