### ISSUE TITLE
[APICompat] Document newly added features

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#27857]
TODO:
- [x] Document the msbuild properties that are expected to be set and are passed onto the `ValidatePackage` task.
- [x] Document the `ValidateAssemblies` task and its parameters
- [x] Document the Microsoft.DotNet.ApiCompat.Tool global tool and its parameters
- [x] Document the added rules // cc @smasher164
- [x] Consider grouping the existing PackageValidation documentation under a new APICompat section

**Comment by ViktorHofer** [comment]
The target date for this is October 10th, to make sure that documentation is in place when RC2 releases publicly.

**Comment by ericstj** [comment]
Dropping some notes: https://github.com/dotnet/docs/tree/main/docs/fundamentals/package-validation is a place to put the docs.

**Comment by carlossanlop** [comment]
I opened https://github.com/dotnet/docs/issues/36235 so the Docs Content Team can update the page.

**Comment by gewarren** [comment]
Can you give me any more info that I can use to make these documentation updates - e.g. what are the new MSBuild properties?

For the diagnostic IDs, I'm not seeing any [here](https://github.com/dotnet/sdk/tree/main/src/Compatibility/ApiCompat) that haven't already been [documented](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/diagnostic-ids).

**Comment by ViktorHofer** [comment]
Sure. All the properties/items that don't start with an underscore are "public" and should be documented:
- https://github.com/dotnet/sdk/blob/5cea8bc6d610c62f57320599954c6eeae52c077e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets#L28-L30
- https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets#L39-L59

We shouldn't document the following ones:
- `RunApiCompat`
- `RuntimeIdentifierGraphPath`

We should mention that individual diagnostic ids can be suppressed via suppression files or via `NoWarn` either per package or globally.

**Comment by gewarren** [comment]
I think this issue can be closed now.
