### ISSUE TITLE
Changes to runtime config options in .csproj are not reflected in .runtimeconfig.json on partial build

### ISSUE THREAD

**Issue by kouvel** [dotnet/sdk#2787]
Repro:

```
dotnet new console
dotnet build -c Release
```

The `.runtimeconfig.json` file in `bin` has the following contents:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.0.0-preview-27218-01"
    }
  }
}
```

Edit the `.csproj` file and add the following into the `PropertyGroup` element:
```xml
<TieredCompilation>false</TieredCompilation>
```

```
dotnet build -c Release
```

The `.runtimeconfig.json` file in `bin` has the same contents as above.

Expected contents:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.0.0-preview-27218-01"
    },
    "configProperties": {
      "System.Runtime.TieredCompilation": false
    }
  }
}
```

Workaround is to delete `bin` and `obj` folders after updating the `.csproj` and before building. The same issue exists the other way around, if the runtime config option is removed from the `.csproj`, the `.runtimeconfig.json` is not updated until a clean build.

My versions:
```
.NET Core SDKs installed:
  3.0.100-preview-009825

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.0-preview-27206-02
```

**Comment by Tragetaschen** [comment]
Even changing the SDK's .targets files doesn't have any effect

**Comment by nguerrera** [comment]
We should add a $(MSBuildAllProjects) input. This isn't perfect. It doesn't work with /p:ServerGarbageCollection changed between builds, but it fixes the repro here and many targets in msbuild use this heuristic. A few hash things to get more correcness, but that is painful.

**Comment by davidfowl** [comment]
I had no idea there was a known issue here, I see it all the time and I have to force a rebuild.

**Comment by nguerrera** [comment]
I didn't know about it until 7 days ago. :)

**Comment by dsplaisted** [comment]
@johnbeisner  Let's try to add a test for this when we fix it.
