### ISSUE TITLE
Result of chr() cannot be used as initial value of a Const in .Net Core 3 Preview 1

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/sdk#2793]
Version: 3.0.100-preview-009812
Commit: e3abf6e935

Runtime Environment:
OS Name: Windows
OS Version: 10.0.17763
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
Version: 3.0.0-preview-27122-01
Commit: 00c5c8bc40

Have you experienced this same bug with .NET Framework?: No

In the .Net Framework using VB.Net you can compile this Line:

``` vb
Private Const TabChar As Char = Chr(9)
``` 

In .Net Core 3 Preview 1 it failes with:
error BC30059: Constant expression is required.

**Comment by nguerrera** [comment]
I'm not sure about the exact fix needed here.

First, I don't know the history of the defaulting VBRuntime=Embed in the SDK. If you follow renames it goes all the way back to the [very first PR that supported VB at all](https://github.com/dotnet/sdk/pull/130): 

> Using VBCore (VBRuntime=Embed) to not introduce new dependencies.

@srivatsn @davkean Do you remember more details on this?

@jaredpar @AlekseyTs @333fred What is the precise condition where VBRuntime should not be Embed? Is it really TargetFrameworkIdentifier == .NETCoreApp and TargetFrameworkVersion >= 3.0? What about .NETStandard or even .NETFramework? 

Also, when not setting it to Embed, should we leave it empty, set VBRuntime=Default, or something else?

See https://github.com/dotnet/roslyn/blob/9e012fe3596974e5e208b556f87891c5b0d0e331/src/Compilers/Core/MSBuildTask/Vbc.cs#L443-L466

A little bit aside, but another annoyance is that this is set in .props before we can check things like the TFM today. To base it on TFM or any other property, the defaulting has to move to targets, but that's technically a a breaking change as the default value of the property would no longer be observable in the body of the .vbproj. 

Final question: is there any VS UI that corresponds to the VBRuntime setting. I didn't find any, but moving defaults around can break that.

cc @KathleenDollard

**Comment by AlekseyTs** [comment]
> What is the precise condition where VBRuntime should not be Embed?

I think this condition should be - if a Microsoft.VisualBasic.Dll is going to be passed as a reference, VB runtime should not be embedded. Otherwise, we end up with two different implementations of VB runtime at the same time.

**Comment by Lohnegrim** [comment]
Hi,
Any Update on this?
I just tried to convert a VB.Net Project from the Old Project Format into the SDK Project Format and noticed that I ran into the Very same problem.

**Comment by Lohnegrim** [comment]
Still in Preview 5

**Comment by 333fred** [comment]
@nguerrera did we make changes to the targets to support this scenario?

**Comment by nguerrera** [comment]
No. The bug is still open.

**Comment by DualBrain** [comment]
@nguerrera So what does the outlook for finding a solution to this appear to be?

**Comment by 333fred** [comment]
@DualBrain as a workaround, you can set the `VBRuntime` property to `default` in your vbproj file and the embedded VB runtime will not be used, allowing the referenced MS.VB.dll to be used instead.

**Comment by nguerrera** [comment]
When I set VBRuntime to default, I get

```
vbc : error BC2017: could not find library 'Microsoft.VisualBasic.dll' [D:\Temp\vb\vb.vbproj]
```

However, there is a Microsoft.VisualBasic.dll passed via /r.

**Comment by nguerrera** [comment]
Seems we have to set VBRuntimePath: https://github.com/dotnet/sdk/issues/3387#issuecomment-506560645

**Comment by nguerrera** [comment]
This works

``` xml
  <Target Name="SetVBRuntimePath" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
       <_VBRuntimeReferencePath Include="@(ReferencePath)" Condition="'%(ReferencePath.Filename)' == 'Microsoft.VisualBasic'" />
    </ItemGroup>
    <PropertyGroup Condition="'@(_VBRuntimeReferencePath)' != ''">
      <VBRuntime>@(_VBRuntimeReferencePath)</VBRuntime>
    </PropertyGroup>
  </Target>
```

It is basically doing what @AlekseyTs [said](https://github.com/dotnet/sdk/issues/2793#issuecomment-510288440): if there's an microsoft.visualbasic.dll in the references, use that. I will base the real fix around this.
