### ISSUE TITLE
dotnet sdk 6.0.400 issue during "dotnet pack" - it changes variable and then ignores it during build

### ISSUE THREAD

**Issue by jacekcendrzak** [dotnet/sdk#28000]
Hello.

In AzureDevOps pipeline we pack a .net 6 C# library into a nuget package.
With dotnet sdk 6.0.400 we noticed that our nuget package is missing version number.

We use MSBuild properties like /p:Configuration=Release;Version="1.0.0.48"
It looks like dotnet sdk 6.0.400 is changing version variable value from 1.0.0.48 to 1_0_0_48
` Property reassignment: $(ImplicitConfigurationDefine)="RELEASE;VERSION=1_0_0_48" (previous value: "RELEASE;VERSION=1.0.0.48") at /usr/share/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.CSharp.targets (29,5)
`

and then it ignores it during build
`/usr/share/dotnet/sdk/6.0.400/Roslyn/Microsoft.CSharp.Core.targets(75,5): warning MSB3052: The parameter to the compiler is invalid, '/define:VERSION=1_0_0_48' will be ignored.`

**Comment by baronfel** [comment]
Can you try with 6.0.401? I believe we fixed this issue inhttps://github.com/dotnet/sdk/issues/27059

**Comment by jacekcendrzak** [comment]
It works with 6.0.401, thank you :)
