### ISSUE TITLE
Remove old sdk can't remove all old runtime

### ISSUE THREAD

**Issue by Xarkam** [dotnet/sdk#2804]
Hello,

Today, I removed old sdk from my machine.
But, I have two old runtime not removed:
![image](https://user-images.githubusercontent.com/331816/50906063-93a5b700-1424-11e9-88e6-5e40f2bf028e.png)
![image](https://user-images.githubusercontent.com/331816/50906249-fa2ad500-1424-11e9-976f-a190e4af12a4.png)
![image](https://user-images.githubusercontent.com/331816/50906311-1c245780-1425-11e9-964d-7b4c466a66e7.png)
Is there a reason for these two versions to still be present?
Why folders 2.1.0 and 2.1.2 in `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App` are not empty and is not listed as installed ?

How to delete them?

My sdk :
![image](https://user-images.githubusercontent.com/331816/50906146-c485ec00-1424-11e9-9e06-87cf022b91cf.png)

I do not have a runtime installed outside of those installed by the sdk.

Thanks

**Comment by livarcocc** [comment]
Not sure why 2.1.0 and 2.1.2 were not removed. You can remove them, at least according to the version of the SDK that you have installed. Do you happen to have logs for the unsinstalls? Otherwise, I don't see much we can do to address this and I will just close the issue.

**Comment by livarcocc** [comment]
We would need logs for the MSI uninstall process. @johnbeisner would you know where to find those?

> If I remove 2.1.0 and 2.1.1 folders, a dotnet --info give me is always installed.

I don't know what you mean by those. Are you saying you removed the folders and dotnet --info is still reporting them?

**Comment by Xarkam** [comment]
If I delete `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.0` and `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.2 folders`, a `dotnet --info` displays in the list that they are still installed.

**Comment by livarcocc** [comment]
Can you please paste the contents of `dotnet --info` after removing the folders?

**Comment by Xarkam** [comment]
This the content after reset my powershell session **and** after deleted folder.
```
SDK .NET Core (reflétant tous les global.json) :
 Version:   2.2.102
 Commit:    96ff75a873

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

So, if you remove folder and you have cmd/powershell opened, the deletion is is not taken into account.
You must restart cmd/powershell session.

I suppose, I can make same for 2.1.202 sdk ? (not present in previous uninstaller list screenshot)

**Comment by livarcocc** [comment]
I am going to move this issue to core-setup, where the code to list the runtimes exists. I am not sure why you would have to restart powershell for this to work. It should pretty much just list folder relative to dotnet.exe itself.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#4951
