### ISSUE TITLE
[NetSDKE2E][Loc]With version17.4.0 preview 3.0  + .net7 rc2 SDK installed on locale OS, some template names are unlocalized after running "dotnet new --list" in CLI .

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#28068]
Steps:
1.install it on locale OS Version 17.4.0 preview 3.0[32920.363.main] + .net7 rc2 SDK
2.Below workloads are installed in vs:

- .NET desktop development

- ASP.NET and web development

- Universal Windows Platform development

- Visual Studio extension development

- .NET Multi-platform App Ul development--check Xamarin

3.Run “dotnet new --list” in CLI

4.Check if output contents are localized well.

Expected result:
Template names are localized.
Actual Result:
Some template names are not localized.

e.g
TK:
![Unbenannt](https://user-images.githubusercontent.com/106054229/191471708-b2914e06-3b84-466f-98a8-58c692c31e18.png)

SC：
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/106054229/191472400-dd4874e9-5268-4b5c-9a50-0925a090c3e4.png)

**Comment by vlada-shubina** [comment]
@pjcollins @jonathanpeppers I see https://github.com/xamarin/xamarin-android/pull/7248 was merged, is it expected to have the templates localized in the version mentioned? Or they come later?

**Comment by jonathanpeppers** [comment]
We have these localized in main: https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates/android-layout/.template.config/localize

The change from OneLocBuild seems like it came in 3 days ago, so should be fixed in next release?

**Comment by vlada-shubina** [comment]
@v-ainigao could you please retest it with the next release and see if is fixed?
@dotnet/dotnet-cli could you please advise when the changes above from `main` in workloads will be inserted?

**Comment by marcpopMSFT** [comment]
@jonathanpeppers is the main branch being used for 7.0 releases? Should we expect the loc descriptions in rc2 or GA?

**Comment by pjcollins** [comment]
These loc related changes were also backported to our 7.0.1xx release branches, they should be in both RC2 and GA.

**Comment by v-ainigao** [comment]
@vlada-shubina Thanks for the heads-up,I will retest it with the next release

**Comment by JanKrivanek** [comment]
@v-ainigao have you been able to verify if the localizations were propagated properly?

**Comment by vdanche** [comment]
@JanKrivanek checked on Turkish(17.4.0 [33027.288.d17.4] GA), the related strings in bug has been fixed. Thanks
![image](https://user-images.githubusercontent.com/65637796/199199599-c617beac-30e5-490a-88dd-2b017bb18cb2.png)
