### ISSUE TITLE
Support for .NET Framework TFM tools

### ISSUE THREAD

**Issue by am11** [dotnet/sdk#2811]
`dotnet pack /p:PackAsTool=true` and `dotnet-tool` provide a nice mechanism to create and deliver utility tools in a uniform manner. Unfortunately, it only supports .NET Core (PackTool targets has [explicit check](https://github.com/dotnet/sdk/blob/f0a1246be1ebe11a88097ac3dd5736f0ad15b855/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets#L75-L76)).

For utilities written with .NET Framework TFMs, we are left with quite inconvenient option: manually collect all dependencies of console app's closure and deliver as a zip file (would be nice to know if there is an easy workaround available meanwhile, by NuGet or MSBuild?)

If it is feasible, please consider enabling .NET Framework support in PackTool targets.

Steps to repro:

```pwsh
#!/usr/bin/env pwsh

pushd /temp
dotnet new console -n mydntool
pushd mydntool
# replace TFM to net471 (system has C:\Program Files\git\usr\bin\ in PATH containing sed etc.)
sed -i '/<\/TargetFramework\>/c\    <TargetFramework\>net471\<\/TargetFramework\>' mydntool.csproj
dotnet pack /p:PackAsTool=true
dotnet tool install mydntool --add-source bin/Debug --tool-path mydir
```

Expected:

> You can invoke the tool using the following command: mydntool
Tool 'mydntool' (version '1.0.0') was successfully installed.

Actual:

> C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.PackTool.targets(32,5): error NETSDK1054: only supports .NET Core. [C:\temp\mydntool\mydntool.csproj]

**Comment by livarcocc** [comment]
@wli3 don't we have an issue for this already? If so, could you close this one as a dup?

**Comment by wli3** [comment]
@livarcocc you are right. There is one on CLI https://github.com/dotnet/cli/issues/9269 closing
