### ISSUE TITLE
Passing properties with multiple values stops woring with net7 RC1 - 7.0.100-rc.1.22431.12

### ISSUE THREAD

**Issue by noxe** [dotnet/sdk#28131]
### Issue Description

Hi - in our csproj files use use custom properties for additional AssemblySearchPaths, see below where we added $(ReferencePath).

<AssemblySearchPaths>$(AssemblySearchPaths);**$(ReferencePath)**;$(OutputPath);$(OutputPath)\Server</AssemblySearchPaths>

Now we start a build an pass in the ReferencePath:

dotnet.exe build test.sln --configuration Release /property:ReferencePath=\"C:\123;C:\456\"

with NET6 - when doing an verbose build - we get this:

         SearchPaths:
             {CandidateAssemblyFiles}
             {HintPathFromItem}
             {TargetFrameworkDirectory}
             {RawFileName}
             C:\123
             C:\456

now with NET7 RC1 SDK - we get this:

         SearchPaths:
             {CandidateAssemblyFiles}
             {HintPathFromItem}
             {TargetFrameworkDirectory}
             {RawFileName}
             C:\123;C:\456

See the values are not split anymore - and the paths are not working? Any info about this behaviour?

thx

**Comment by baronfel** [comment]
Apologies for this @noxe - we've got a PR up for this that we will work on including in a servicing fix for this series of SDKs and onwards.

**Comment by noxe** [comment]
thx you for the Update!

**Comment by baronfel** [comment]
closing as the linked PRs are in.
