### ISSUE TITLE
Error with dotnet publish 

### ISSUE THREAD

**Issue by himalpatel81** [dotnet/sdk#2817]
I'm trying to publish an ASP.NET Core .NET Framework project using CLI and it fails with the error message "error CS0246: The type or namespace name 'Leadtools' could not be found (are you missing a using directive or an assembly reference?) [WebApplication1.csproj] " 

LeadTools is .net Framework nuget. I read few articles saying that dotnet cli doesnt support it. I also tried to use msbuild but getting the same error. 

Here is the command that i use

CLI:
`dotnet publish /nologo /p:PublishProfile=Release  /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /maxcpucount:1 /p:platform="Any CPU" /p:configuration="Release" /p:DesktopBuildPackageLocation="output.zip"`

MSBuild:

`msbuild "WebApplication1.csproj" publish /nologo /p:PublishProfile=Release  /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /maxcpucount:1 /p:platform="Any CPU" /p:configuration="Release" /p:DesktopBuildPackageLocation="output.zip"
`
and Here is the repro project
[Repro](https://github.com/himalpatel81/DotNETCLIIssue)

**Comment by livarcocc** [comment]
I could not reproduce this issue. I ran a `dotnet restore` followed by the `dotnet publish` command you have above and the project was published successfully.

I would try clearing your NuGet cache just to make sure you don't have a stale package or something like that and I would retry to publish the project.
