### ISSUE TITLE
dotnet build fails without any warning or error

### ISSUE THREAD

**Issue by havarnov** [dotnet/sdk#28226]
### Describe the bug
`dotnet build` fails on an empty new csharp project.

dotnet version: 7-rc1
os: macos m1

### To Reproduce
```sh
uname -a                                                                    
>Darwin havarnov 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

dotnet --version
> 7.0.100-rc.1.22431.12

dotnet new console -n fails
cd fails

dotnet build                                                                
> MSBuild version 17.4.0-preview-22428-01+14c24b2d3 for .NET
>
> Build FAILED.
>     0 Warning(s)
>     0 Error(s)
>
> Time Elapsed 00:00:00.00
```
fails.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

Program.cs
```csharp
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

**Comment by nagilson** [comment]
Will try this out once I have access to the mac, seems pretty bad. Thanks for raising this with us

**Comment by baronfel** [comment]
@havarnov in the meantime, could you try setting the environment variable `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER` to `1` and see if that clears the issue up?

**Comment by ravndaa** [comment]
This also happens on Intel Mac with RC-2, and by using this command it works for a short time: `dotnet build-server shutdown --msbuild`
but the environment variable mentioned seems like a better workaround. thanks :)

**Comment by havarnov** [comment]
I had to remove 7-RC1 because of this issue, and now I'm not immediately able to reproduce with RC2. I'll report back if it happens again, and if the environment variable solves the issue.

**Comment by jonathan-caddy** [comment]
I can confirm dotnet build fails on Intel Mac with 7.0.100-rc.2.22477.23. The workaround suggested by @baronfel fixes the issue for me.   The other workaround was to add a global.json to my aspnet projects targetting dotnet6.  However, I kept getting fails when using tye.  Setting DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER=1 fixed this too.

**Comment by nagilson** [comment]
Moving to @rokonec For MSBuildServer failures.

**Comment by rokonec** [comment]
@havarnov There is a know [bug](https://github.com/dotnet/msbuild/pull/8006) which will be released in RTM. CTRL+C caused MSBuild server process to reject subsequent builds. The symptoms you have reported shows it is most likely this bug.
I am closing this issue as fixed. Please feel free to reopen it if you experience it after RTM/GA.
Thank very much for excellent bug report.
