### ISSUE TITLE
Massive workflow problems

### ISSUE THREAD

**Issue by kfrancis** [dotnet/sdk#28237]
### Description

I've been working on migrating a Xamarin app to Maui, but I've also been curious about net7.0 so I installed VS2022 Preview (v17.4.0 Preview 2.1) and everything is bonkers on my system now.

In VS2022 (17.3.5) I created a new maui app and immediately have issues:
![czrb9_2022-09-28](https://user-images.githubusercontent.com/67574/192829293-2915901c-af41-4086-80f3-8b3c266556fb.png)

Ok, so I should be able to do a `dotnet workload restore` right? No.
![xpyen_2022-09-28](https://user-images.githubusercontent.com/67574/192829506-a111eb89-92cf-458a-809b-6c6a50813b91.png)

Tizen isn't even a default here, why is this coming up?

Why am I getting this back and forth? First I get that xcode 14 isn't supported, use Xcodes.app (thanks @jamesmontemagno) to switch and then I'm getting that it doesn't want that version now.
![wwioh_2022-09-28](https://user-images.githubusercontent.com/67574/192830349-e8b87d99-05c5-41e6-92ec-8da854112c79.png)

I select net6.0 when creating the project, ran `dotnet new globaljson` and it populates with `7.0.100-rc.1.22431.12`. Had to manually change it back.

`dotnet --list-sdks`
6.0.401 [C:\Program Files\dotnet\sdk]
7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]

### Steps to Reproduce

1. Install VS 2022 17.3.5
2. Open VS2022, Create Maui project1, build, run
3. Install VS 2022 Preview 17.4.0 Preview 2.1
4. Open VS 2022 Preview, Create Maui project2, build, run
5. Open VS2022 project1, try and build? try and run?

### Link to public reproduction project repository

https://

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.408

### Affected platforms

iOS, Windows, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

ios 15

### Did you find any workaround?

No, I'm uninstalling VS2022 Preview in the hopes that this mess is reverted. Next would be formatting my machine.

**Comment by kfrancis** [comment]
@marcpopMSFT 

### dotnet --info

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### program files\dotnet\sdk-manifests
![ey7vy_2022-09-29](https://user-images.githubusercontent.com/67574/193045951-8700effb-8a56-4135-b4d4-3253565553c2.png)

**Comment by AsPaper** [comment]
I have the same issue.
See also here [Issue#28217](https://github.com/dotnet/sdk/issues/28217)

**Comment by marcpopMSFT** [comment]
In the initial screenshot from VS in the original description, were you using the 7.0 SDK within 17.3 or had you already set up a global.json to point at 6.0.400?

**Comment by dsplaisted** [comment]
This will be fix in the GA release of .NET 7.  For workarounds in the meantime, see https://github.com/dotnet/sdk/issues/28217
