### ISSUE TITLE
dotnet new should have a --force-english-output switch

### ISSUE THREAD

**Issue by taori** [dotnet/sdk#28287]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
I am trying to unit test dotnet new template creation for custom templates, but on my machine the output is german while on CI is english. 

### Describe the solution you'd like
If there was a switch like that i would not have to install an english language pack to force english output through the IDE

### Additional context
for dotnet nuget delete there is a --force-english-output switch, which does exactly that

**Comment by baronfel** [comment]
Hello! We've implemented this feature via an environment variable so that it remains consistent across all dotnet commands. You can read more about the environment variable at our docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_cli_ui_language

**Comment by taori** [comment]
Good to know that there is a workaround to make it print the content in english

**Comment by vlada-shubina** [comment]
Closing, already possible.
