### ISSUE TITLE
dotnet publish profile silently continues even if you give an invalid publish profile path

### ISSUE THREAD

**Issue by nagilson** [dotnet/sdk#28370]
When using a publish profile, there is no warning or error message for using an incorrect publish profile that doesn't exist.
Current behavior:
`dotnet new console` `dotnet publish -p:PublishProfile=TotallyNonexistentButRadPublishProfileFile -bl`. Will silently publish, binlog shows `PublishProfileImported=false` and `PublishProfile=TotallyNonexistentButRadPublishProfileFile `. 
Expected / Desired Behavior: 
MSBuild produces a warning akin to `A publish profile was provided with the name TotallyNonexistentButRadPublishProfileFile but could not be found in ./Properties/PublishProfiles/. `

**Comment by HughWarrington** [comment]
I would add to the original comment, this should absolutely be a terminal error and not just a warning. According to [these docs](https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022#build-net-clickonce-applications-from-the-command-line):

> For .NET Core 3.1 and .NET 5 and later [...] you **need to** provide an additional property for the publish profile on the MSBuild command line

At the moment, if you specify a non-existent publish profile, the publish 'succeeds' but I have no idea what on earth it's doing, presumably it is using some undocumented defaults?

**Comment by nagilson** [comment]
Closing this as resolved, thanks Vijay!
