### ISSUE TITLE
[NetSDKE2E][Loc] Overtranslated string"dotnet workload search"occurs is displayed when running "dotnet workload list"

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#28417]
**Environment:** .NET 7.0.100 RC2 or .NET 6.0

**Repro steps:**

1. Set up a clean local OS machine with .NET .NET 7.0.100 RC2 or .NET 6.0.402 installed
2. Run dotnet workload list and Observe 

**Expected Result:**
String"dotnet workload search" should not be translated

**Actual Result:**
String"dotnet workload search" is overtranslated.
Simple Chinese:
![image](https://user-images.githubusercontent.com/1578239/194745823-ca39d250-33a8-4abe-b459-360e5fd29857.png)
Japanese:
![image](https://user-images.githubusercontent.com/1578239/194746995-2c41cbbd-4e78-41c5-82a8-8fd6341ecc9d.png)
EN for referrence:
![image](https://user-images.githubusercontent.com/1578239/194746918-1c0025e1-7038-4d5f-8858-8406e803e9ab.png)

**Note:**
1. This issue is repro both on .NET7 and .NET 6 SDK
2. This issue is not repro on German
![image](https://user-images.githubusercontent.com/1578239/194746495-34a341d1-bfcd-40fe-9071-da7ac0eb36fd.png)

**Dotnet --info**
C:\Users\vhuwang>dotnet --info
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
Filed internally: https://dev.azure.com/ceapex/CEINTL/_workitems/edit/721957/

**Comment by marcpopMSFT** [comment]
This should be fixed now and checking a few of the languages, it appears to be.
