### ISSUE TITLE
Strange issue with ef 5 on windows 11 dotnet ef stoped working,

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/sdk#28452]
I seem to have an odd bug in windows 11 I have the various runtimes installed but when i try to run 

dotnet ef migrations add newfieldstestdb -p TheHockeyLabMn.Dal  -c TheHockeyLabMnDBContext

Which worked before the lattest version in windows 11 I am getting this pop up

![image](https://user-images.githubusercontent.com/5619229/194669696-7bc031a3-2979-4a0a-a983-31576cee87be.png)

You will see on the left screen the windows 11 open with dialog is comming up and I dont no how to fix this please help

**Comment by ajcvickers** [comment]
Moving this issue to the SDK repo, since it is not directly related to EF Core.

**Comment by davidbuckleyni** [comment]
I can do a full video walk through @marcpopMSFT  but the issue is i have tried all existing work arounds and re installed the tools at present.

**Comment by joeloff** [comment]
sounds like it thinks dotnet is perhaps just an ordinary file and not an executable. Is the EXE installed in `Program Files\dotnet`? what happens if you directly run the command directly using the full path to the executable, e.g. `Program File\dotnet\dotnet.exe ef migrations add newfieldstestdb -p TheHockeyLabMn.Dal -c TheHockeyLabMnDBContext` ?

**Comment by davidbuckleyni** [comment]
![image](https://user-images.githubusercontent.com/5619229/195642290-5cecb0ea-97e7-4f08-9956-73c979c200f6.png)

![image](https://user-images.githubusercontent.com/5619229/195642391-c173ca85-2c84-4a30-b397-c9b4da4d144d.png)
![image](https://user-images.githubusercontent.com/5619229/195642461-a9feb6a0-2be6-4ac5-a828-d55b56f10afd.png)


It only reports version 7 installed but i have 6 and 5 installed as well this is infruatiating it work the last two visual studios ago I have 2022 stable and 2019 installed as well but have had that for  a long time @joeloff

**Comment by davidbuckleyni** [comment]
Also system vars 

![image](https://user-images.githubusercontent.com/5619229/195645817-20282058-5cac-4a4c-8fec-1e0c7c25fd2d.png)

**Comment by davidbuckleyni** [comment]
Im really lost on this as this is now really hurting a project of mine? @joeloff

**Comment by danmoseley** [comment]
> I can do a full video walk through

That might not be a bad idea. Can you show using cmd.exe instead of powershell ? And in VS. Also "dotnet build"

**Comment by danmoseley** [comment]
> I can do a full video walk through

That might not be a bad idea. Can you show using cmd.exe instead of powershell ? And in VS. Also "dotnet build"

**Comment by davidbuckleyni** [comment]
@danmoseley dotnet build is not the issue here only ef the project builds fine and ef says all tools are installed

**Comment by davidbuckleyni** [comment]
https://screenrec.com/share/BIb2Kr56x9 @danmoseley and @joeloff

**Comment by davidbuckleyni** [comment]
> @davidbuckleyni Try re-installing the .NET SDK.

see video below @ajcvickers  ive treied everything short of re installing windows 11

**Comment by davidbuckleyni** [comment]
Reinstalled with a full use of installclean and still same issue this is gettter very bloody annoying that these bugs creep into visual studio 22

**Comment by davidbuckleyni** [comment]
@joeloff @ajcvickers  @danmoseley 
I managed to fix it buy complety re installing windows 11 so it def must be something to do with concurent updateds through out the versions might happen again to someone else

**Comment by danmoseley** [comment]
Glad to hear it you can probably close this then.
