### ISSUE TITLE
Formatting with multi-line raw literals indents with `dotnet run`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#28478]
This code prints differently via `dotnet run` and direct execution.

https://github.com/richlander/lucky/blob/d496e810682b3c9c153d0c6f0123b86315eed2ce/src/Lucky/Program.cs#L310-L322

![image](https://user-images.githubusercontent.com/2608468/195200634-dcb3f3a5-4ac8-41ff-bda7-056989ccf85a.png)

**Comment by baronfel** [comment]
What 7.0 build is this?  This appears to be a duplicate of https://github.com/dotnet/msbuild/issues/8008 but I'm not sure if that made it into RC2.

**Comment by richlander** [comment]
This appears to be resolved.
