### ISSUE TITLE
NETSDK1138 should not be raised for libraries

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#28518]
### Is your feature request related to a problem? Please describe.

This is more of a DCR. 
NETSDK1138 is raised to notify users of EOL frameworks being targeted. This is too noisy for libraries.

### Describe the solution you'd like

When I am targeting a library, the TFM decision is usually the lowest version of the framework that meets my needs, as I want as many users as possible to use my library. 

The NETSDK1138 warning can be misleading when I'm building a library. 
Notifying EOL when the project is likely to run on that runtime is great, and valuable, but only for executables.

**Comment by baronfel** [comment]
Definitely agree that the guidance is muddled. We talked about this in triage today and while initially we thought it would be easy to condition the warning off of `OutputType = Library`, but it's not - for example test projects are typically (though not always) libraries as well. If we could figure out a good enough heuristic it might be worth it to do this, but that feels error prone.

**Comment by baronfel** [comment]
We discussed this again and should emit this warning only on `OutputType != 'Library'`.

**Comment by JL03-Yue** [comment]
The issue was updated in pr #30612
