### ISSUE TITLE
Would it be possible to pick a fix for https://github.com/microsoft/ApplicationInsights-dotnet/pull/2671?

### ISSUE THREAD

**Issue by omajid** [dotnet/sdk#28547]
Would it be possible to pick a fix for https://github.com/microsoft/ApplicationInsights-dotnet/pull/2671 as well?

**Comment by MichaelSimons** [comment]
@marcpopMSFT - thoughts?

**Comment by marcpopMSFT** [comment]
The last AI release on nuget.org is from 3 months ago. Not sure what action I can take yet on this as that change doesn't appear to be available for consumption yet.

**Comment by marcpopMSFT** [comment]
2.21.0 is still the latest AI version available.

**Comment by marcpopMSFT** [comment]
We updated to 2.22 in Main. Is that sufficient or do you need a backport to 8.0.1xx?
