### ISSUE TITLE
WorkloadManifest.targets should be imported in a pre-determined order for `7.0`

### ISSUE THREAD

**Issue by radical** [dotnet/sdk#28607]
With the latest `7.0.0` sdk, the `WorkloadManifest.targets` for the `wasm-tools*` packs are imported in a different order from earlier which breaks the wasm workloads. We started hitting this with the [stable branding change](https://github.com/dotnet/runtime/pull/76849) in `dotnet/runtime`.

In the working case:
- `microsoft.net.workload.mono.toolchain.net6`, `microsoft.net.workload.mono.toolchain.net7`, `microsoft.net.workload.emscripten.net6`, `microsoft.net.workload.emscripten.net7`

In the broken case:
- `microsoft.net.workload.emscripten.net7`,`microsoft.net.workload.emscripten.net6`, `microsoft.net.workload.mono.toolchain.net7`, `microsoft.net.workload.mono.toolchain.net6`

Mono.Toolchain.net*, and Emscripten*'s  WorkloadManifest.targets are sensitive to the order, so we have a correct order specified in `IncludedWorkloadManifests.txt`.

We have been trying to fix this since the issue was discovered, but the solutions are non-trivial, and require a lot of non-trivial testing. It would be preferable to enforce the order in `IncludedWorkloadManifests.txt`. This would mean that all the testing that has been done, till we switched to stable branding, would still be relevant.
This change can be restricted to `7.0` .

cc @lewing @steveisok @marcpopMSFT @jonathanpeppers

**Comment by lewing** [comment]
I think this is much like the intent of https://github.com/dotnet/sdk/issues/22358
