### ISSUE TITLE
Make classes sealed by default

### ISSUE THREAD

**Issue by mostmand** [dotnet/sdk#28610]
In C# each class in inheritable unless it is defined as sealed. Is it possible to make classes sealed as default unless defined as inheritable? Maybe a feature flag in csproj file to opt in could do the trick.

### Additional context
[Jon Skeet's response to a related question](https://stackoverflow.com/a/252738)
[Sealed classes are more performant than normal classes](https://www.youtube.com/watch?v=d76WWAD99Yo)

**Comment by martincostello** [comment]
Looks like this analyzer landed in 7.0.101, which causes false positives for top-level programs.

See https://github.com/dotnet/sdk/issues/29164#issuecomment-1349425823.

**Comment by baronfel** [comment]
Closing this as the language change was rejected and an analyzer is available for users that want it.
