### ISSUE TITLE
dotnet tool install should implicitly do dotnet tool update (same for dotnet workload install/update)

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#28664]
If I want to give instructions for someone to get the latest tool X, I have to tell them to do both install and update. That way, if they already have it installed, they get the latest.

For example,
```
dotnet tool install --global dotnet-sos
dotnet tool update --global dotnet-sos
```
```
C:\Program Files\Microsoft Visual Studio\2022\Preview>dotnet tool install --global dotnet-sos
Tool 'dotnet-sos' is already installed.

C:\Program Files\Microsoft Visual Studio\2022\Preview>dotnet tool update --global dotnet-sos
Tool 'dotnet-sos' was reinstalled with the latest stable version (version '6.0.328102').
```

IMO it's implicit if I issue the command dotnet tool install that I want the latest version.

**Comment by danmoseley** [comment]
@marcpopMSFT would this be something we can mark 'help wanted' or does it need more design/agreement?

**Comment by danmoseley** [comment]
exact same for `dotnet workload install` which should implicitly do `dotnet workload update` if it's already installed.

**Comment by marcpopMSFT** [comment]
We don't use the help wanted flag. We mostly use the milestones for tracking. Annie is starting to go through some of tools bugs for triage though this didn't get caught in our first pass. We're tracking tools bugs to prioritize in #29436. A workloads request would be a separate item entirely.

CC @dsplaisted @baronfel @JL03-Yue

**Comment by dsplaisted** [comment]
> exact same for `dotnet workload install` which should implicitly do `dotnet workload update` if it's already installed.

For workloads, this is already what happens by default.  You can specify `--skip-manifest-update` if you don't want it to update the workloads.

**Comment by JL03-Yue** [comment]
For tools, a change involving automatically upgrade and downgrade is currently being worked on

**Comment by JL03-Yue** [comment]
#37311 addresses this issue.
