### ISSUE TITLE
Update roslyn-analyzers version and remove false-positive suppressions

### ISSUE THREAD

**Issue by 333fred** [dotnet/sdk#28672]
https://github.com/dotnet/sdk/pull/28520 and https://github.com/dotnet/sdk/pull/28519 brought a new roslyn compiler that needs an update for roslyn-analyzers to avoid false positives in a few analyzers. See https://github.com/dotnet/sdk/pull/28520#issuecomment-1282835046.

**Comment by marcpopMSFT** [comment]
@333fred is anything still needed to complete and close this issue?  This was from a year ago and listed for 8.0.1xx

**Comment by 333fred** [comment]
@marcpopMSFT have the false positive suppressions I had to add in the linked pr been removed?

**Comment by marcpopMSFT** [comment]
@333fred oh, you filed this because those needed to be removed later. I thought this was tracking that an upstream change was needed as I had misread your phrasing in the original issue. Created a PR to remove all those pragma statements
