### ISSUE TITLE
Cannot force ResolveFrameworkReference to avoid downloading targeting packs

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2875]
Feature request: for the sake of things like source-build and building your own targeting pack (e.g. https://github.com/aspnet/AspNetCore), I'd like to be able to force the SDK into an "offline mode" which fails instead of attempting to download targeting packs. The current code only checks for `Directory.Exists`

https://github.com/dotnet/sdk/blob/915adb77cc3763f88aca3da622961abd54f100f2/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs#L112-L126

**Options I've considered:**

* Add a global property, like `DisableTargetingPackAcquisition`
* Add something to `KnownFrameworkReference` or `<FrameworkReference>` as metadata

cc @dsplaisted @nguerrera

**Comment by nguerrera** [comment]
> Add a global property, like DisableTargetingPackAcquisition

I like this. Nice and simple :)

> Add something to KnownFrameworkReference or <FrameworkReference> as metadata

Do you have a scenario for controlling it at this level of granularity?

**Comment by natemcmaster** [comment]
>> Add something to KnownFrameworkReference or as metadata

> Do you have a scenario for controlling it at this level of granularity?

The only scenario I could think of is for the AspNetCore repo. I want the repo to use the SDK as much as possible for targeting pack resolution, but I also want to make sure that projects in the repo with a `<FrameworkReference Include="Microsoft.AspNetCore.App" />` are resolved to a locally build version of the targeting pack, not some remote version. But for other frameworks, like WindowsDesktop.App and NETCore.App, I wouldn't mind if the SDK fetched those automatically.

**Comment by dsplaisted** [comment]
This is fixed with #2887.  You can set the `EnableTargetingPackDownload` to false to disable targeting pack download.

It doesn't support specifying this separately per `FrameworkReference`.  If you want to do that, I would suggest running a target after `ResolveFrameworkReferences` that modifies its output.

**Comment by natemcmaster** [comment]
Thanks @dsplaisted !
