### ISSUE TITLE
Mac OS .NET Incompatible Architecture Need ARM4e

### ISSUE THREAD

**Issue by Onam-Ensono** [dotnet/sdk#28792]
I currently have a Mac OS running on the M1 chip and when I attempt to create an azure function I get the error stating 

_Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37, 5): Metadata generation failed. Exit code: '130' Error: 'Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.3/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.3/libhostpolicy.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.3/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.3]'_

Steps to reproduce this is to install the Azure Function Tools, then use `func new` command to create the azure function (isolated or normal) both have the same issue targeting .NET 6. 

I thought it was a bad version of .NET installed so I removed all versions using the `dotnet-core-uninstall` tool and when I run the output now I get..

```
.NET Core SDKs:
  6.0.402  (arm64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]

.NET Core Runtimes:
  6.0.10  (arm64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  6.0.10  (x64)                                                                                          
  3.0.3   (arm64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  3.0.3   (x64)  
```

Running `dotnet --info` gives me 

```
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: arm64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

Bit lost what to do here now. Is there a fix or something I need to install to get this working?

**Comment by baronfel** [comment]
This should be resolved at this point. Please chime in if that's not the case and we'll reopen.
