### ISSUE TITLE
Don't reuse the https://aka.ms/sdkimplicitrefs link to indicate version should not be indicated

### ISSUE THREAD

**Issue by mairaw** [dotnet/sdk#2879]
This comes from a discussion at https://github.com/dotnet/docs/issues/8691 and my proposal can be found at https://github.com/dotnet/docs/issues/8691#issuecomment-448343752

Customers are getting the following error:
NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.All' specified a Version of 2.2.0-preview3-35497. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs. However, this document does not cover how Microsoft.AspNetCore.All should actually be referenced in this situation.

However, specifying the version of a package has nothing to do with implicit package references, so I don't think we should be using that same link for this error message. 
We should create a new aka.ms link for that error and that link would point to a different location in the ASP.NET docs TBD.

/cc @Rick-Anderson

**Comment by jzabroski** [comment]
@Mairaw Not only that, but this warning does not seem to be disable-able.  I tried adding `<NoWarn>1071</NoWarn>` to my csproj build configuration, but it doesn't stop the warning.

In my case, there is a further issue I will submit a ticket for: If you have a WebApi.Tests project (e.g., that references a different project type with a different target framework moniker), then you won't be able to build your WebApi.Tests if you follow the advice to omit the Version.

IMPLICIT VERSIONS DO NOT WORK!  THEY ARE A BAD IDEA.

**Comment by dsplaisted** [comment]
I do not think that we should recommend setting AllowExplicitVersion.  See my comments [here](https://github.com/dotnet/sdk/issues/3046#issuecomment-477336223) and [here](https://github.com/aspnet/Docs/pull/11688#pullrequestreview-219719090)

**Comment by jzabroski** [comment]
@dsplaisted  Based on my repro in https://github.com/dotnet/sdk/issues/3046#issuecomment-477336223 I now think that you should reconsider this non-recommendation.

**Comment by Bartolomeus-649** [comment]
If relevant, please consider the scenario where your project targets the `.NET Core SDK`, but you also need to reference and use `Microsoft.AspNetCore.App`, like in a console application where you self-host the web server.

**Comment by MiYanni** [comment]
Old bug triage: It *seems* most of the issues were addressed in the relevant links. If we still desire the change to docs for this, please reopen.
