### ISSUE TITLE
Investigate whether we need to set/default AssemblyTitle

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#288]
Do we need to set the AssemblyTitle to AssemblyName if the user hasn't explicitly set AssemblyTitle?  Is this a valuable assembly attribute to always generate into a .dll?

/cc @nguerrera

**Comment by srivatsn** [comment]
Did we do this in project.json? I don't see why AssemblyTitle is important but I guess giving it a default is fine too.

**Comment by dsplaisted** [comment]
It looks like this is already done, probably by @nguerrera.  You can use the `AssemblyTitle` MSBuild property to specify what goes in the AssemblyTitleAttribute, and if you don't it will default to the `AssemblyName`.
