### ISSUE TITLE
"salt" MSBuild handshake in test / dogfood environment

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2880]
Right now for our tests (and in the dogfood script) we override the MSBuildSDKsPath to point MSBuild to the SDK under test.  However, this doesn't seem to prevent sharing MSBuild nodes that didn't have this set, which can end up causing assembly loading or other issues.

Ideally in our test environment we would add a "salt" to the node connection handshake, so that MSBuild would only be able to connect to nodes that come from the same test environment.

This would probably require a change in MSBuild to allow us to provide such a "salt".

@rainersigwald, thoughts?

**Comment by rainersigwald** [comment]
I'd be on board with adding the value of a `MSBUILDNODEHANDSHAKESALT` environment variable to the handshake. I don't think it's generally useful, but for internal development and especially tests that require multiple invocations and need node reuse to be enabled it'd be nice.

**Comment by rainersigwald** [comment]
This issue was moved to Microsoft/msbuild#4308

**Comment by rainersigwald** [comment]
Reopening to track _adopting_ Microsoft/msbuild#4308 once it's available.

**Comment by dsplaisted** [comment]
Now that we've merged the cli and toolset repos into the sdk repo, we don't handle the dogfood environment the same way and this isn't necessary.
