### ISSUE TITLE
Inconsistent handling of Microsoft.Extensions.* 6.0.0 and 6.0.1 dependencies

### ISSUE THREAD

**Issue by gaborposz** [dotnet/sdk#28856]
### Describe the bug
If I create a new .NET 6 console application, add `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to the project file (because I'm using [Framework Dependent Deployment](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent) hence the [ASP.NET Core Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) is installed anyway) and add a dependency to [Microsoft.Extensions.Hosting.WindowsServices 6.0.0](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices/6.0.0#dependencies-body-tab), then in my output bin folder only the **Microsoft.Extensions.Hosting.WindowsServices.dll** is present (besides my application), as expected.

However, if upgrade to [Microsoft.Extensions.Hosting.WindowsServices 6.0.1](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices/6.0.1#dependencies-body-tab), then some additional framework (!) assemblies are also deployed to my bin folder:
- Microsoft.Extensions.Configuration.EnvironmentVariables.dll
- Microsoft.Extensions.Configuration.UserSecrets.dll
- Microsoft.Extensions.Hosting.dll

These are unexpected, because they are part of the ASP.NET Core Runtime.

I had a similar issue previously (#10831), but the current problem is more concrete:
Let's assume that the 6.0.1 assembly versions are delivered with my application, and later a new ASP.NET Core Runtime security fix is released that affects one of these assemblies. Despite that the latest ASP.NET Core patch is installed, the local, older assembly version will be used by my application, thus it remains vulnerable.

### To Reproduce
- Create .NET 6 console application
- Add `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to the project file
- Add `<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.0" />` to the project file -> Only Microsoft.Extensions.Hosting.WindowsServices.dll is deployed to the bin folder
- Upgrade Microsoft.Extensions.Hosting.WindowsServices to 6.0.1 -> Other Microsoft.Extensions.* assemblies are also deployed to the bin folder

### Exceptions (if any)
n.a.

### Further technical details
I have the latest Visual Studio (17.3.6) and SDK (6.0.402) installed.

**Comment by dsplaisted** [comment]
This is happening because the 6.0.1 package depends on the 6.0.1 version of those assemblies.  The framework-dependent app may run on the 6.0.0 framework, so the 6.0.1 assemblies need to be included in the app.

When we were designing .NET Core 3.0 we talked about having a way to avoid this by specifying a minimum patch version of the framework, but we didn't come up with a good way to do this and never implemented anything.

The best you can do is excluding each individual DLL that you don't need, though this is pretty brittle:

```xml
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" ExcludeAssets="All"/>
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" ExcludeAssets="All"/>
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.1" ExcludeAssets="All"/>
```

FYI @ericstj @DamianEdwards

**Comment by ericstj** [comment]
@dsplaisted is correct that this is expected.  When you build a 6.0 application there is nothing that says you'll run on a 6.0.0 framework or a 6.0.1 framework.  The SDK doesn't have any assumptions about what runtime will be used and it makes it so the application will work on the GA runtime.  You can see this in the runtimeconfig that's generated:
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    }
  }
}
```

> Let's assume that the 6.0.1 assembly versions are delivered with my application, and later a new ASP.NET Core Runtime security fix is released that affects one of these assemblies. Despite that the latest ASP.NET Core patch is installed, the local, older assembly version will be used by my application, thus it remains vulnerable.

This is not the case.  If the version of an assembly in the framework is newer, it will be preferred over the version in the application.  The host makes this determination at runtime based on versions.
https://github.com/dotnet/runtime/blob/9d6396deb02161f5ee47af72ccac52c2e1bae458/docs/design/features/sharedfx-lookup.md#probing-for-assemblies

> When we were designing .NET Core 3.0 we talked about having a way to avoid this by specifying a minimum patch version of the framework, but we didn't come up with a good way to do this and never implemented anything.

The runtimeconfig of an application can specify this, but the data needed to represent the runtime (platform manfiest) does not have a way to distinguish it.  One thing we could do (breaking change) would be to make it so a serviced version of the SDK would only work on a serviced runtime.  Then we could just version all that data in place.  This would mean a serviced SDK would start building applications with a runtimeconfig like:
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.10"
    }
  }
}
```

**Comment by DamianEdwards** [comment]
>One thing we could do (breaking change) would be to make it so a serviced version of the SDK would only work on a serviced runtime. Then we could just version all that data in place. This would mean a serviced SDK would start building applications with a runtimeconfig like:

The reason we've not done this in the past is that the environment an app is built on (i.e. where the SDK is) is often on a different patch/update cycle to where the app is running, and if we made that change then apps published from where the SDK has been updated would not run on the environments that have not yet been updated.

What we have right now (like so many things) is a tradeoff whereby one can end up with assemblies in the app output directory that might not be needed at runtime, but the app will be able to run on all patch-levels of the targeted runtime.

**Comment by gaborposz** [comment]
@dsplaisted @ericstj @DamianEdwards: Thanks for the detailed explanation.

One additional question:

> This is happening because the 6.0.1 package depends on the 6.0.1 version of those assemblies. The framework-dependent app may run on the 6.0.0 framework, so the 6.0.1 assemblies need to be included in the app.

Is it decided by the NuGet package versions, or by the AssemblyVersions?

**Comment by dsplaisted** [comment]
It's decided by the package dependency versions.  You can [see](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices/6.0.1#dependencies-body-tab) that Microsoft.Extensions.Hosting.WindowsServices 6.0.1 depends on version 6.0.1 of [Microsoft.Extensions.Hosting](https://www.nuget.org/packages/Microsoft.Extensions.Hosting/), but 6.0.0 of other packages.

There are times when the assembly versions matter, but the package dependencies are what determine which packages you get.
