### ISSUE TITLE
Warn when publishing in Debug configuration

### ISSUE THREAD

**Issue by jtschuster** [dotnet/sdk#28927]
I've heard of people publishing and distributing software in debug mode, expecting that running "publish" will automatically build in release mode. I don't think that's an unreasonable assumption to make, and that was actually my initial expectation when starting with dotnet. The sdk probably can't change the default without breaking a lot of people, but I think a warning or info message that they are publishing with a debug configuration would be helpful.

**Comment by nagilson** [comment]
This is a very good idea and something we have been discussing for a while now with @richlander. We are making the breaking change in 8 to publish as release by default: https://github.com/dotnet/sdk/issues/27066

Btw, there is `PublishRelease` which you can currently use set to default the publish configuration to `Release`. Going to close this as a duplicate, thanks!
