### ISSUE TITLE
dotnet test -r does not fallback on --results-directory anymore

### ISSUE THREAD

**Issue by aling93** [dotnet/sdk#28986]
### Describe the bug
It appears that .NET 6 did not have an issue executing the following command:
` dotnet test -l trx -r /app/coverage`

where `-r` is actually `--results-directory` 

However, after upgrading to NET 7 this generates the following error:

```
error NETSDK1083: The specified RuntimeIdentifier '/app/coverage' is not recognized.
```

which makes sense but it's surprising compared to .NET 6 or older versions.

### To Reproduce
Execute the same command ( `dotnet test -l trx -r /app/coverage` ) with .NET 6 and .NET 7

### Further technical details
- Output of `dotnet --info`
```
> dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4
```

**Comment by nagilson** [comment]
cc @Evangelink

**Comment by baronfel** [comment]
This change was likely done to bring `dotnet test` in line with the common shorthands for other .NET CLI commands. The full set of 'common' CLI short identifiers is [here](https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax#short-form-aliases), and we should be fairly aggressive about keeping those meanings reserved for the CLI commands.

**Comment by Evangelink** [comment]
Hi @aling93,

@baronfel is right, we did a breaking change to unify shorthand across the other .NET CLI commands. If you look at the documentation you can see the change of behavior being described:

> --results-directory <RESULTS_DIR>
> The directory where the test results are going to be placed. If the specified directory doesn't exist, it's created. The default is TestResults in the directory that contains the project file. **Short form -r available in .NET SDK versions earlier than 7.**
>
> -r|--runtime <RUNTIME_IDENTIFIER>
> The target runtime to test for. **Short form -r available starting in .NET SDK 7.**

I agree that the change is a bit hidden and I will take on myself to improve the doc page to add warning box for these changes.

**Comment by aling93** [comment]
understood, thank you!

**Comment by Evangelink** [comment]
@aling93 Link to the doc update PR: https://github.com/dotnet/docs/pull/32527

**Comment by Evangelink** [comment]
I am closing the issue now. Thanks for your feedback.
