### ISSUE TITLE
[NetSDKE2E][Loc]With VS 17.5 preview 2 + .NET 7.0.200-preview.22558.7 installed on Loc OS, the template names for IOS and Mac are unlocalized after running "dotnet new --list" in CLI .

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#28997]
Steps:
1.install it on locale OS Version 17.5.0 preview 2.0[33109.214.main] from https://ddweb/Dashboard/vsbuild + .net 7.0.200-preview.22558.7(runtime-7.0.0-rtm.22505.15) from https://github.com/dotnet/installer

2.Below workloads are installed in vs:

- .NET desktop development
- ASP.NET and web development
- Universal Windows Platform development
- Visual Studio extension development
- .NET Multi-platform App Ul development--check Xamarin
- Mobile development with C++

3.Run “dotnet new --list” in CLI

4.Check if output contents are localized well.

Expected result:
Template names are localized.

Actual Result:
Some template names are not localized.

e.g
EN:
<img width="556" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/106054229/201056578-f5b89905-41ba-45ef-8f3f-1ea29bc4e06f.png">

SC:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/106054229/201054857-a7289697-4f45-453a-90ee-c34f937902dd.png)
DE:
![Untitled](https://user-images.githubusercontent.com/106054229/201055364-e1f91178-dca6-403e-bf9f-ea2506e2c2be.png)

note：
The same is reproduced in vs.
![1](https://user-images.githubusercontent.com/106054229/202595443-ed6e74eb-c260-46fe-a757-8135bbe5a490.png)

dotnet info:
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/106054229/201057219-a759dc64-6633-4eed-a62d-c843628517dc.png)

**Comment by nagilson** [comment]
@dotnet/templating-engine-maintainers Where should we go to, to get these translated?

**Comment by vlada-shubina** [comment]
This looks like Xamarin templates.
https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates
https://github.com/xamarin/xamarin-macios/tree/main/dotnet/package

both were actually localized, it might be some packaging issues:
https://github.com/xamarin/xamarin-macios/pull/14213
https://github.com/xamarin/xamarin-android/pull/7248

**Comment by nagilson** [comment]
@marcpopMSFT  who do we go to for packaging issues, Matt?

**Comment by marcpopMSFT** [comment]
Wouldn't we go to the Xamarin folks to see how these flow in?  @jonathanpeppers do you know who to talk to about these?

**Comment by jonathanpeppers** [comment]
Ok, I don't understand how the same templates in VS are translated, but not at the command-line?

Look at "iOS Binding Library", for example. @v-ainigao are some of the templates in your screenshot Xamarin.iOS projects, or are all of them .NET 6+ iOS templates?

**Comment by v-ainigao** [comment]
All IOS and MacOS template in CLI are not localized, and in VS, these templates are also untranslated. @jonathanpeppers

**Comment by jonathanpeppers** [comment]
Ok, so it is the titles?

![image](https://user-images.githubusercontent.com/840039/202735654-67678ec6-7afb-4ce7-aa93-8f8dd46928bc.png)

And then some of the descriptions aren't translated:

![image](https://user-images.githubusercontent.com/840039/202735829-9689a215-1279-49d0-bbe6-78db66433b27.png)

It's not a packaging issue, if some things are localized -- I think everything would be English if that were the case?

/cc @rolfbjarne

**Comment by rolfbjarne** [comment]
Looks like the MAUI and the Android ones are OK, so moving to xamarin-macios.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#16830
