### ISSUE TITLE
Building a project with OutputType = Exe and implicit fx reference disabled causes build to fail.

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#2906]
## Repro steps

1. dotnet new console
2. Edit the project file to disable implicit fx reference and instead add an explicit reference to `Microsoft.NETCore.App`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" />
  </ItemGroup>

</Project>
```
3. `dotnet build`

Build fails saying it was unable to copy the AssemblyName.exe file

> C:\Users\Pranav\.dotnet\x64\sdk\3.0.100-preview-010184\Microsoft.Common.CurrentVersion.targets(4560,5): error MSB3030: Could not copy the file "D:\temp\test1\obj\Debug\netcoreapp3.0\test1.exe" because it was not found. [D:\temp\test1\test1.csproj]

Setting `<UseAppHost>false</UseAppHost>` in the project file fixes things.

*Background*:
The RazorSdk builds in a separate repo that's an arcade dependency to AspNetCore. The Sdk's test applications build against test shims rather than the actual AspNetCore fx to avoid cyclical dependencies. To do so, they set `DisableImplicitFrameworkReferences = true`.

**Comment by livarcocc** [comment]
@peterhuene @dsplaisted

**Comment by peterhuene** [comment]
I think we should predicate the default apphost feature on whether or not implicit framework references are being used.  If not, you won't get an apphost.

Additionally, if we're building for a particular RID, we should pull the apphost from assets if implicit framework references are disabled.

**Comment by dsplaisted** [comment]
The explicit `PackageReference` to Microsoft.NETCore.App is not valid for .NET Core 3.0:

```
<ItemGroup> 
    <PackageReference Include="Microsoft.NETCore.App" />
</ItemGroup>
```

It may partially work right now, but I wouldn't expect it to continue to do so (eventually we probably won't be publishing the Microsoft.NETCore.App NuGet package at all.

If you do want an explicit reference, you need to do it via a `FrameworkReference`:

```
<ItemGroup> 
    <FrameworkReference Include="Microsoft.NETCore.App" />
</ItemGroup>
```
