### ISSUE TITLE
Sdk tooling target framework should be net8.0

### ISSUE THREAD

**Issue by mmitche** [dotnet/sdk#29087]
SDK tooling TFM is currently net7.0. This should be updated to net8.0.

While the SDK does use a property for this in Directory.Build.Props, it does not appear to be used in all places that should (e.g. test assets).

**Comment by marcpopMSFT** [comment]
The SDK is now targeting net8.0 other than the resolver and our tests. Is that what you had in mind for this issue?
https://github.com/dotnet/sdk/pull/28563

Active one for tests:
https://github.com/dotnet/sdk/pull/29316
