### ISSUE TITLE
[NETE2ESDK]With .NET 8 SDK installed, Warning "Workload garbage collection failed with error: An item with the same key has already been added. Key: (Microsoft.NETCore.App.Runtime.Mono.android-arm, 6.0.10) displayed when installing andriod workload in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#29082]
Repro steps:
1.installed .NET8.0 SDK from https://github.com/dotnet/installer.
2.In CLI, execute: dotnet workload install android --skip-manifest-update

**Expected Result:** 
workload should be installed successfully, and no warnings should be displayed in the output. 

**Actual Result:** 
Warning "Workload garbage collection failed with error: An item with the same key has already been added. Key: (Microsoft.NETCore.App.Runtime.Mono.android-arm, 6.0.10) displayed

![image](https://user-images.githubusercontent.com/65637796/202138061-b2608b3e-aa48-40e5-a871-a67210a6a169.png)

dotnet --info:
.NET SDK:
 Version:   8.0.100-alpha.1.22565.7
 Commit:    03c15d0900

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-alpha.1.22565.7\

Host:
  Version:      8.0.0-alpha.1.22559.2
  Architecture: x64
  Commit:       dd7fdb723d

.NET SDKs installed:
  8.0.100-alpha.1.22565.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.22558.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.22559.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.22552.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/29508

**Comment by vdanche** [comment]
We met below similar error, will check it again once the bug is fixed
![image](https://user-images.githubusercontent.com/65637796/210526035-26fbf496-9b8f-4046-a7f7-7a07a4fc2e75.png)

**Comment by vdanche** [comment]
This issue not repro on today's builld: 8.0.100-alpha.1.23059.8(runtime-8.0.0-alpha.1.23058.2 )
![image](https://user-images.githubusercontent.com/65637796/211471012-8f472742-7870-48fa-ba17-63d6c5ae64a4.png)
