### ISSUE TITLE
Why Platform Target?

### ISSUE THREAD

**Issue by wasabii** [dotnet/sdk#29129]
I've run up against an issue with PlatformTarget being set to ARM64 when building for a RID of linux-arm64. The specific issue is an issue of mine: I have a custom compiler, custom language, etc, and haven't yet implemented generating ARM64 PEs.

But what I'm trying to understand is the rational of having PlatformTarget set to ARM64 when building for linux-arm64. Since the apphost is the actual entry point anyways: shouldn't PlatformTarget for non-Framework not be set to AnyCPU? What purpose does generating a ARM64 DLL file serve here, for example?

**Comment by marcpopMSFT** [comment]
We try to keep them in sync as they roughly track the same thing. As far as I can tell it's always been like this as well: https://github.com/dotnet/sdk/pull/326
