### ISSUE TITLE
`dotnet store` does not work in 3.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2914]
The [runtime package store feature](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store) was used for ASP.NET Core in .NET Core 2.0, but was replaced by a shared framework for ASP.NET Core in 2.1.

Using the `dotnet store` command, it's also possible to create your own runtime store.  However, this has been a bit of a bug farm in .NET Core 3.0 (with all of the framework composition changes).  So we may want to remove support for creating a runtime store in the .NET Core 3 SDK.

**Comment by nguerrera** [comment]
We're not dropping this. I will work on fixing it.

**Comment by nguerrera** [comment]
Fixed by #3345
