### ISSUE TITLE
`dotnet publish` shows garbled characters when running on PMC on OS with Traditional Chinese language

### ISSUE THREAD

**Issue by dominoFire** [dotnet/sdk#29151]
Bug transferred from VS Feedback

### Describe the bug

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/程序包管理器控制台主机版本-640111-乱码/10203703)._

---
程序包管理器控制台主机版本 6.4.0.111 乱码

dotnet publish 命令乱码

![2022-11-16 22 08 50.png](https://aka.ms/dc/image?name=Bd157fd5af3e24cdd90128823fb39370c638042046055504960_2022-11-16_22_08_50.png&tid=d157fd5af3e24cdd90128823fb39370c638042046055504960)

---
#### Feedback Bot on 11/16/2022, 06:37 PM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2022, 00:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### To Reproduce

1. Set Windows language to Traiditional Chinese
1. Set Visual Studio Language to same as OS system.
1. Create a New Console project
1. Open Package Manager Console in the recently created Console App
1. Run "dotnet publish" in Package Manager Console.

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/1192347/203138288-92d9699f-232a-41ec-a834-185f182fda6a.png)

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by luantian-terark** [comment]
I got same problem.
it happends in dotnet tools version 7 and my projects sdk versions are dotnet 6（run **dotnet publish**）.  My codepage in powershell is 936(GBK), found garbled characters and got correct characters in code page 65001(UTF8).
note: i got correct characters in `dotnet --info` but garbage in `dotnet build` with code page 936

```
PS D:\> dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by erdembayar** [comment]
@marcpopMSFT 
I encountered duplicate for this issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1698495

**Comment by nagilson** [comment]
This looks like the same as https://github.com/dotnet/sdk/issues/24757, though its manifesting in a different way.

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-7.0#net-core-notes @LeaFrock Do you happen to know if the culture / OS contains English as its primary language pack? 

![image](https://user-images.githubusercontent.com/23152278/210623197-15257920-3f4c-49a3-a962-1c66e54e3afa.png)

**Comment by LeaFrock** [comment]
@nagilson The lang setting of my OS only contains Simplified Chinese.

![1672882620434](https://user-images.githubusercontent.com/20787265/210681914-7a2fe18f-65b8-48ac-a236-3a9012a721e8.png)

> there is a component of .NET which will set the CHCP / language page to US English

So is there any wordaround now? Even though I change the code page with `chcp 65001` in PMC, I still get garbled CN chars.

**Comment by nagilson** [comment]
Hi @LeaFrock, here is a workaround for now:

![image](https://user-images.githubusercontent.com/23152278/210866084-5360dea0-1d6b-48d1-9feb-cb9129b73fe4.png)

The difference is that PMC is a powershell console, to change chcp in powershell console you need not only to run chcp but to run the following:
```
$OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001
```

**Comment by LeaFrock** [comment]
Aha, it works! Thanks a lot.

**Comment by nagilson** [comment]
Thanks for reporting back, glad to hear it worked. 😄 Now let's hope that the fix I wrote works without breaking any legacy scenarios.

**Comment by LeaFrock** [comment]
After upgrading VS to 17.4.4, the problem comes back 😢 . I have to execute the commands above again.

**Comment by nagilson** [comment]
Ya, that's not surprising. Waiting for this PR to be merged and hopefully fix all of the loc issues: https://github.com/dotnet/sdk/pull/29755

**Comment by nagilson** [comment]
Cool, that got merged. I expect this to be fixed in the first .NET 8 preview. Please let me know how it goes if you try it out ;)
