### ISSUE TITLE
Installing .net 7 on 20.04 should give error instead of silently install and not worked.

### ISSUE THREAD

**Issue by anirugu** [dotnet/sdk#29184]
I was checking this yesterday https://github.com/dotnet/sdk/issues/28995 the default codespace doesn't work with .net 7 because it's based on 20.04 which is not supported 7.0

Out of curiosity I install and I only see 6.0 is installed. It would be better if it's fail with error that 7.0 is not supported on ubuntu 20.04

**Comment by marcpopMSFT** [comment]
@rbhanda Who drives our relationship with codespaces as it sounds like there's a mismatch there with .net 7.

**Comment by rbhanda** [comment]
Adding if @leecow can help here

**Comment by leecow** [comment]
Unfortunately, I don't know anything about codespaces. .NET 7 does install and works fine on Ubuntu 20.04. The instructions in the [.NET Docs](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004) mention .NET 6 but just replace '6.0' with '7.0'. After doing this on a new 20.04 VM `dotnet --info` returns the following for me. 

```
root@1c0a39c85d4c:/test# dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info
```

Here's my VM OS info for reference. 

```
root@1c0a39c85d4c:/test# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
