### ISSUE TITLE
Adjust `CommonTemplatesTests` to net8 changes in templates

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/sdk#29197]
https://github.com/dotnet/sdk/pull/27486
https://github.com/dotnet/sdk/pull/28707

`CommonTemplatesTests` will need to accomodate changes - specifically:
* net8.0 TFM needs to be added to test matrix
* add tests for new item templates synonyms: .gitignore, global.json, nuget.config, .editorconfig (ideally while sharing snapshots with existing shortnames to verify identity of output)

Related work: adding C# 12 to test matrix: https://github.com/dotnet/sdk/issues/29195

**Comment by JanKrivanek** [comment]
Adressed by https://github.com/dotnet/sdk/pull/28707/commits/3ccb7ba69035c82c99a5d290848dd9032d56cfdc

**Comment by JanKrivanek** [comment]
.net6.0 X C# >= 11.0 and default cases are removed from the new test matrix temporarily (https://github.com/dotnet/templating/issues/5668)

**Comment by vlada-shubina** [comment]
Already addressed.
