### ISSUE TITLE
Attributing arbitrary identifiers/values to a project's package and project references

### ISSUE THREAD

**Issue by aodl** [dotnet/sdk#2926]
Relates to [NuGet#7776](https://github.com/NuGet/Home/issues/7776)   

Is there a facility available for assigning arbitrary attributes to the project and package references of a particular project, in a way that the information becomes available at runtime? i.e.
```
  <ItemGroup>
    <PackageReference Include="some.random.package1"  CustomAttribute="banana"/>
    <PackageReference Include="some.random.package2"  CustomAttribute="flowers" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\project1\project1.csproj" CustomAttribute="0" />
      <ProjectReference Include="..\project1\project2.csproj" CustomAttribute="1"/>
    </ItemGroup>
```
I'm aware that this customAttribute information couldn't be made available on the package reference **assemblies** as they will already be built; and in the case of project references I expect it's either not possible or would require adding a task info the csproj. of the referenced projects themselves (to pick up a custom property passed in by msbuild and embedded it into an assembly attribute).

In the case of the package reference, I have control over how they are built, but they are built before knowing what custom attribute might be assigned to it from a referencing project.

The only way I can think of doing this for both project and package references is to have a build task that retrieves the `PackageReference` and `ProjectReference` ItemGroups, checks for the presence of `CustomAttribute` and in each case writes the package/project name and custom attribute value to a file for lookup at runtime.

Are there built in ways to do this sort of thing?

**Comment by livarcocc** [comment]
I don't believe there are built-in ways for this now. You suggestion above sounds like what I would suggest though.
