### ISSUE TITLE
Setting PublishSingleFile in the project can affect output assembly type

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#29263]
From https://github.com/dotnet/sdk/issues/29164

> # PublishSingleFile

> This was a head scratcher. The solution in question will build an AnyCPU exe that works and runs on both x86 and x64. However, when switching to .NET SDK 7.0.100 this would not work. Either tests would simply not run with issues around bad format for the exe assembly or similar. Or if trying to run the exe project e.g. using F5 in visual studio this would simply crash upon start before anything with something like The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core."... code 2147516546 (0x80008082). As far as I can tell it turns out behavior has changed (silently) for PublishSingleFile so this now forces a RuntimeIdentifier (RID) to be set without any warning or similar. This causes the "format" of the output assembly to become platform specific e.g. win-x64 and hence trying to run x86 tests based on it will fail. Changing this definition to:

    <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
> resolved the issue. Guessing you should simply not define these options in csproj in the future if you have project that you want to build as Any CPU but instead do that only on command line when actually doing publish. Which means these often become redundantly defined.

I'm not quite sure what's going on here. If it's as simple as making sure that PublishSingleFile doesn't affect the output during build, I think that's a reasonable goal.

**Comment by nietras** [comment]
👀

**Comment by nagilson** [comment]
If by this
> This causes the "format" of the output assembly to become platform specific e.g. win-x64 and hence trying to run x86 tests based on it will fail. 

@nietras means that the RID is now in the output path of the assembly, like `output-assembly/win-x64/foo.txt`, then this is caused by and a duplicate of https://github.com/dotnet/sdk/pull/29031. But even with that PR, `PublishSingleFile` will still affect the output path if doing a publish. 

# 
I don't know how their system was working before, wouldn't they have encountered this error:
```go
It is not supported to publish an application to a single-file without specifying a RuntimeIdentifier. 
Please either specify a RuntimeIdentifier or set PublishSingleFile to false.
```
# 

Also, `UseCurrentRuntimeIdentifier = false` should disable this behavior. 
Another option may be: `AppendRuntimeIdentifierToOutputPath = false `.

**Comment by agocke** [comment]
Yeah I think this is a duplicate of https://github.com/dotnet/sdk/pull/29031, but we should have a test to make sure that the behavior is fixed. We have a bunch of single file tests already, so this seems like a simple one to add.

**Comment by vijayrkn** [comment]
@agocke - The related issue (https://github.com/dotnet/sdk/pull/29031) is merged and closed. Is there any additional work required for this? 

This is currently in the websdk path. If there is additional work needed, happy to move it to the NetSDK path. 

/cc @nagilson

**Comment by agocke** [comment]
I think we can close this out.

**Comment by agocke** [comment]
Just to confirm -- did we add a test for the case mentioned in the bug? This issue was mainly tracking adding a regression test.

**Comment by nagilson** [comment]
@agocke https://github.com/dotnet/sdk/pull/29031/files#diff-5a4996ff9ea877663c9d1d6f22df892cf664b291211d8aee6a0e6ccde3822f24R412
