### ISSUE TITLE
Possible dead code handling null resolver, which doesn't appear to be possible

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2928]
We create a resolver here:

https://github.com/dotnet/sdk/blob/f0a1246be1ebe11a88097ac3dd5736f0ad15b855/src/Tasks/Microsoft.NET.Build.Tasks/GetPackageDirectory.cs#L30

Which doesn't look like it can return null:

https://github.com/dotnet/sdk/blob/f0a1246be1ebe11a88097ac3dd5736f0ad15b855/src/Tasks/Microsoft.NET.Build.Tasks/NuGetPackageResolver.cs#L71-L82

But we check for null here:

https://github.com/dotnet/sdk/blob/f0a1246be1ebe11a88097ac3dd5736f0ad15b855/src/Tasks/Microsoft.NET.Build.Tasks/GetPackageDirectory.cs#L43-L45

@dsplaisted What's the origin of this comment. How can this be null in design time builds?

Is there something else we are supposed to be handling?

**Comment by dsplaisted** [comment]
I think this is probably a dead check left over from a refactoring.  I think what happened is `GetPackageDirectory` used to take an assets file path instead of a list of PackageFolders, and the assets file might not exist for a design-time build.

**Comment by nguerrera** [comment]
Makes sense, can you review #2929 that fixes this, among other things.
