### ISSUE TITLE
ClickOnce Publish fails if two referenced projects have the same file, despite being Excluded from the publish

### ISSUE THREAD

**Issue by MrZander** [dotnet/sdk#29368]
### Describe the bug
When using the ClickOnce publish option, if two *excluded* projects both have the same file in the same relative path, the publish will fail.  
I believe this is a bug, the two projects don't get copied to the output of the publish, so none of their files should be considered when checking for pathing conflicts.

### To Reproduce
See repro here:
https://github.com/MrZander/ClickOncePublishRepro

1. Create a project with two class libraries (ProjectA, ProjectB)
2. Reference ProjectA and ProjectB from the main project
3. Add a file DO_NOT_PUBLISH.txt to the root of both ProjectA and ProjectB and set the build action to "Copy if newer"
4. Create a ClickOnce publish for the main project and set the `PublishState` for ProjectA and ProjectB to `Exclude `
5. Publish

### Exceptions (if any)
`Found multiple publish output files with the same relative path: C:\Users\user\source\repos\ClickOnceRepro\ProjectA\DO_NOT_PUBLISH.txt, C:\Users\user\source\repos\ClickOnceRepro\ProjectB\DO_NOT_PUBLISH.txt.`

### Further technical details
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.425 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

I am using Visual Studio Professional 2022 version 17.4.1
I can't test it using the command line `dotnet publish -p:PublishProfile=ClickOnceProfile` because of this outstanding Issue: https://github.com/dotnet/sdk/issues/28403

**Comment by vijayrkn** [comment]
@John-Hart - Is this something the click-once team can look at? If the projects are excluded, they shouldn't be part of the computed files and hence the warning should not have been generated.

**Comment by John-Hart** [comment]
@sujitnayak can you please take a look at this?

**Comment by sujitnayak** [comment]
@MrZander 
The Clickonce exclusions are file based. When you have ProjectA and ProjectB exclded, the exclusion only applies to ProjectA.dll and ProjectB.dll.

**Comment by MrZander** [comment]
@sujitnayak
![image](https://user-images.githubusercontent.com/1673352/217971768-4e681c7b-45f8-4a56-98c7-20504bc646bd.png)
This clearly shows it should be excluding `DO_NOT_PUBLISH.txt`, but it still throws the exception.  And this window only shows one of the two txt files, that also seems problematic.  Is this just a Visual Studio UI issue?
What would a proper pubxml file look like to publish ClickOnceRepro without ProjectA or ProjectB?

**Comment by sujitnayak** [comment]
@MrZander 

ClickOnce publish for apps targeting .NET 5.0 and higher is built as an extension to Folder Publish. 

Although ClickOnce publish is set up to ignore both the DO_NOT_PUBLISH.txt files in this case, the failure you are seeing is because a target called as a dependency of Folder Publish (_ComputeCopyToPublishDirectoryItems) resolves both the DO_NOT_PUBLISH.txt as publishable artifacts for folder publish.

If you create a Folder Publish profile, you will see the same error when you publish with that profile.

The workaround is to mark one of the files in conflict as 'Do not copy' in the build actions.

Thanks.

**Comment by MrZander** [comment]
Very well, not an ideal user experience from Visual Studios point of view.   I've already moved on to using folder publish with some custom MSBuild targets anyways.  
Thank you.
