### ISSUE TITLE
CPPCLI package reference support doesn't enable packagedownload without an additional reference

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#29370]
I was working on fixing https://github.com/dotnet/sdk/blob/main/src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs#L28 by enabling PackageReference support. Without it, I need the expected apphost and targeting packs to be installed on the test machine (which they are not).  However, I find that if I just add -p:EnableManagedpackageReferenceSupport=true, the build still fails.

`error NETSDK1004: Assets file 'C:\repos\sdk\artifacts\tmp\Debug\It_builds_and---EC320CDD\NETCoreCppCliTest\obj\proje
ct.assets.json' not found. Run a NuGet package restore to generate this file.`

If I then add a package reference into the vcxproj file, when I build it both downloads that package reference and enables the packagedownloads for apphost and targeting pack.

**Comment by marcpopMSFT** [comment]
@nkolev92 @dsplaisted any ideas how we have the package reference support in cppcli enable the package download of the implicit version of the apphost/targeting pack without needing a package reference? I haven't traced through why setting that property to true also then expects an assets file (presumably it's turning on nuget restore and telling us to expect a restore to have happened)

**Comment by nkolev92** [comment]
> @nkolev92 @dsplaisted any ideas how we have the package reference support in cppcli enable the package download of the implicit version of the apphost/targeting pack without needing a package reference? I haven't traced through why setting that property to true also then expects an assets file (presumably it's turning on nuget restore and telling us to expect a restore to have happened)

I'd expect RestoreProjectStyle to be set to `PackageReference` somewhere in the targets and that should enable it.
