### ISSUE TITLE
project.assets.json not found. Run nuget package to restore

### ISSUE THREAD

**Issue by pawarvikaskwd** [dotnet/sdk#2941]
I am trying to build MS Unit test project with .Net standard class library project on VSTS. Locally solution is working fine but when I am trying to build using VSTS it's failing. **project.assets.json' not found. Run a NuGet package restore to generate this file.** I am getting this error.

I am using Nuget Restore in VSTS build before building the application. Nuget restore step is succeeded, but after that Build solution step is failing.  How to fix this?

**Comment by livarcocc** [comment]
How are you building the project in your VSTS definition? What versions of the .NET Core SDK are you installing? What does your project look like?

**Comment by pawarvikaskwd** [comment]
Hey, issue got fixed. I used  Nuget restore and Dot net build both to restore Nuget packages which helped me in creating project.assets.json file. Thanks for you time
