### ISSUE TITLE
"MSBuildExtensionsPath" in "Sdk.props" is empty

### ISSUE THREAD

**Issue by baruchiro** [dotnet/sdk#2955]
https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props#L31

I create an object of [`Microsoft.Build.Evaluation.Project`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project?view=netframework-4.7.2&viewFallbackFrom=netcore-2.1) with existing `.csproj` file path.
When I compile it in `net471` everything works fine.

If I compile it in `netcoreapp2.1`, the file `Sdk.props` throw an error because he search the file `Microsoft.Common.props` in current working directory (the folder of my executable dll) instead of in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.props`.
I think it is because the `$(MSBuildExtensionsPath)` is empty.

If you think to answer that "this is not soppurted in *.net core*", I will happy to know how to evulate `.csproj` files in *.net core*.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#4184
