### ISSUE TITLE
dotnet run command not listening on https

### ISSUE THREAD

**Issue by Xarkam** [dotnet/sdk#29569]
### Describe the bug
I am running a simple webapi program on Windows and when I try to run the 'dotnet run' cli command, I can see it's listening only on http but not on https. I have also executed 'dotnet dev-certs https --trust' command to trust the development certificate, but still it's not listening on https. Could you please let me know if I am missing any other settings ?

### To Reproduce
1. Create folder
2. Into new folder execute : `dotnet new webapi`
3. Execute `dotnet run` (or `dotnet watch run`)

### Further technical details
dotnet --info:
```
SDK .NET :
 Version:   7.0.101
 Commit:    bb24aafa11

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

IDE: VSCode
```
Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
launchSettings.json
```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:6300",
      "sslPort": 44378
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5207",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7151;http://localhost:5207",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/331816/207830796-d46a2c20-54cd-48fc-a3d8-6863380c6f7e.png)

**Note**: if I use VisualStudio (2022) or Rider (2022.3) then the application listens on the https.
![image](https://user-images.githubusercontent.com/331816/207832196-94c13b2f-02f2-45a3-b800-1cea7949d0a8.png)

**Comment by pedrior** [comment]
I am also facing this. Anything new about this issue?

**Comment by yonog1** [comment]
same here, could it be an issue with the new .net 7?

**Comment by LemonZero** [comment]
Documentation Says,"As the first profile listed, this profile is used by default",the value of 'applicationUrl' in 'http' do not config https, so,if you copy and paste the value of 'applicationUrl' in 'https' to 'http', then,it will listen on https. Here is the documentation link:https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-7.0#development-and-launchsettingsjson

**Comment by vijayrkn** [comment]
This was an intentional change made in .NET 7.0. The new templates in ASP.NET Core 7.0 contains a http and a separate https profile. `dotnet run` will default to the first profile in the list which is the http profile in this case. 

You can see the details of the change here: 
https://github.com/dotnet/aspnetcore/pull/42027

As mentioned in the above PR description, you can pass the profile that you would like to use to `dotnet run` using the `--launch-profile` property.

`dotnet run --launch-profile https`.

Hope this clarified. I am going to close this issue. If you still have open questions with this, feel free to re-open. Thanks!

/cc @DamianEdwards

**Comment by t1noo7** [comment]
> This was an intentional change made in .NET 7.0. The new templates in ASP.NET Core 7.0 contains a http and a separate https profile. `dotnet run` will default to the first profile in the list which is the http profile in this case.
> 
> You can see the details of the change here: [dotnet/aspnetcore#42027](https://github.com/dotnet/aspnetcore/pull/42027)
> 
> As mentioned in the above PR description, you can pass the profile that you would like to use to `dotnet run` using the `--launch-profile` property.
> 
> `dotnet run --launch-profile https`.
> 
> Hope this clarified. I am going to close this issue. If you still have open questions with this, feel free to re-open. Thanks!
> 
> /cc @DamianEdwards

thanks so much for your help, but how to set it always run default together with others info?

**Comment by DamianEdwards** [comment]
You can change the order.of the launch profiles in the launchSettings.json file so that the https profile is first. Then it will be the default profile for dotnet run.

**Comment by jose2007kj** [comment]
> You can change the order.of the launch profiles in the launchSettings.json file so that the https profile is first. Then it will be the default profile for dotnet run.

this worked for me
