### ISSUE TITLE
NETSDK1109 \

### ISSUE THREAD

**Issue by hendrykuo** [dotnet/sdk#29600]
To Whom It may Concern,

when i tried to run debug on dot net MAUI project
it shows me this error on Error List Window:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1109	Runtime list file 'C:\Users\hendr\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.28\
data\RuntimeList.xml' was not found. Report this error to the .NET team here: https://aka.ms/dotnet-sdk-issue.	MauiApp2	C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	
![VisualStudio sc 0](https://user-images.githubusercontent.com/9103293/208229001-aa66c236-a155-48cf-807e-487424c72b6b.jpg)

**Comment by nagilson** [comment]
@jonathanpeppers  @mattleibow Is this something you've encountered before? 

Not sure what `RuntimeList.xml` is for. We'll discuss it a bit in SDK triage too.

**Comment by marcpopMSFT** [comment]
That is coming from the windows SDK so pinging @j0shuams @manodasanW to take a look.

@hendrykuo can you try deleting that package from your nuget cache (C:\Users\hendr.nuget\packages\microsoft.windows.sdk.net.ref) and try again. I see the runtimelist.xml in the [nuget.org](https://nuget.info/packages/Microsoft.Windows.SDK.NET.Ref/10.0.19041.28) version of the package so it doesn't make sense that we're not finding it. Maybe it got deleted from the package cache somehow.

**Comment by hendrykuo** [comment]
hi @marcpopMSFT i deleted the file, and rebuild the solution and it works again.
Thank you very much for the help everyone.
have a good one.

**Comment by marcpopMSFT** [comment]
Thanks. I'll go ahead and close it since you got unblocked and I'm not sure how you would have gotten into this state.
