### ISSUE TITLE
docker-compose dotnet restore goes forever on M1 mac

### ISSUE THREAD

**Issue by tpitman** [dotnet/sdk#29610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I execute the command docker-compose on an asp.net core solution, the dotnet restore step in the build process runs without completing until I ctrl-c the process to stop it.

### Expected Behavior

dotnet restore should complete normally

### Steps To Reproduce

Create an asp.net core project based on net7 release code.

Add docker support that includes a docker compose file.

Execute docker-compose at the command line.

Notice that the dotnet restore operation runs without completing.

### Exceptions (if any)

none

### .NET Version

7.0.1

### Anything else?

VS4Mac on M1 MacBook pro

This works fine on my Intel MacBook pro for 2016.

**Comment by tpitman** [comment]
I created a new issue on the Nuget repository. Thank you for your help so far.

**Comment by AndreaDabrowskiWillowTree** [comment]
To follow this issue: https://github.com/NuGet/Home/issues/12329
