### ISSUE TITLE
Issue occurred when running dotnet clean command on console

### ISSUE THREAD

**Issue by saipavanbhanu** [dotnet/sdk#29641]
### Describe the bug
dotnet clean command throwing error.
system: mac m1 pro
os: 13.1
dotnet installed version: 3.1.414
### To Reproduce
try running dotnet clean.

### Exceptions (if any)
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20]

### Further technical details
- Include the output of `dotnet --info`
Host:
  Version:      7.0.1
  Architecture: arm64
  Commit:       97203d38ba

.NET SDKs installed:
  3.1.414 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  /Users/bhanu.pothuri/Documents/Work/Git-Repos/CargoRunner/global.json

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS Code

**Comment by baronfel** [comment]
I expect this to be an artifact of the 3.1 multi-arch jankiness - 3.1 is out of support and 5.0+ SDKs shouldn't exhibit the same problems. Please reopen if the problem persists on 5.0+ SDKs.
