### ISSUE TITLE
warning NETSDK1004: Assets file '/root/.nuget/packages/system.threaing.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.xml not found

### ISSUE THREAD

**Issue by barruka** [dotnet/sdk#29659]
### Describe the bug
When containarizing a aspnet 7 project, when docker is building with the command:
```RUN dotnet build "myproject.csproj" -c Release -o /app/build```
two warnings are showed:

```/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.threaing.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.xml' not found.```

```/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/yamldotnet/8.1.2/lib/netstandard2.1/YamlDotNet.xml' not found.```
 

### Further technical details
SDK DE .NET:
 Version:   7.0.101
 Commit:    bb24aafa11

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19045       
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by dkoerner85** [comment]
I have recently migrated an app from dotnet 6 to dotnet 7 and seeing similar warnings. I use a standard Dockerfile to build the project:

```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src
COPY ["LicenceServer/LicenceServer.csproj", "LicenceServer/"]
RUN dotnet restore "LicenceServer/LicenceServer.csproj"

COPY . .
WORKDIR "/src/LicenceServer"
RUN dotnet build "LicenceServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LicenceServer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .


ENTRYPOINT ["dotnet", "LicenceServer.dll"]
```

Both the dotnet restore as well as dotnet build should take care of restoring the Nuget packages. However, I'm seeing many warnings referring to missing .xml files:

```
...
/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.runtime.compilerservices.unsafe/6.0.0/lib/net6.0/System.Runtime.CompilerServices.Unsafe.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.security.accesscontrol/4.5.0/ref/netstandard2.0/System.Security.AccessControl.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.security.permissions/4.5.0/ref/netstandard2.0/System.Security.Permissions.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.security.principal.windows/4.5.0/ref/netstandard2.0/System.Security.Principal.Windows.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.text.encodings.web/7.0.0/lib/net7.0/System.Text.Encodings.Web.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/system.text.json/7.0.0/lib/net7.0/System.Text.Json.xml' not found. Run a NuGet package restore to generate this file. [/src/LicenceServerShared/LicenceServerShared.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/automapper/12.0.0/lib/netstandard2.1/AutoMapper.xml' not found. Run a NuGet package restore to generate this file. [/src/ApplicationCore/ApplicationCore.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/mediatr/11.0.0/lib/netstandard2.1/MediatR.xml' not found. Run a NuGet package restore to generate this file. [/src/ApplicationCore/ApplicationCore.csproj]

/usr/share/dotnet/sdk/7.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/mediatr.contracts/1.0.1/lib/netstandard2.0/MediatR.Contracts.xml' not found. Run a NuGet package restore to generate this file. [/src/ApplicationCore/ApplicationCore.csproj]

    205 Warning(s)
    0 Error(s)
```

I use dotnet 7 on Ubuntu 20.04:

```
$ dotnet --version
7.0.101
```

```
$ dotnet --list-sdks
6.0.404 [/usr/share/dotnet/sdk]
7.0.101 [/usr/share/dotnet/sdk]
```

I can provide further information to help debug this issue if necessary.

**Comment by barruka** [comment]
@dkoerner85  off topic: 
If you are not consuming something specific from Debian 11, you can try to change the line:
```FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base``` 
to
```FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base``` 
You will notice how the docker image shrinks!
