### ISSUE TITLE
Linux builds fail if CPS project factory GUID is used in solution file

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#297]
Updating `sdk.sln` to use CPS project factory GUIDs (`{13B669BE-BB05-4DDF-9536-439F39A36129}` instead of `{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}`) caused the Linux CI builds to fail for PR #292.  Cross platform builds using these GUIDs should succeed.

@eerhardt

**Comment by srivatsn** [comment]
Should this bug move to the msbuild repo?

**Comment by rainersigwald** [comment]
@srivatsn Yes please. Can you let us know the new GUID? @cdmihai's assessment sounds right to me.

Sadly I think MSBuild's solution parser is the closest thing we have to a portable implementation of that. The original is in the closed VS repo and is in C++, so not much use to us.

**Comment by srivatsn** [comment]
Filed https://github.com/Microsoft/msbuild/issues/1237
