### ISSUE TITLE
All packages targeting netcoreapp3.0 have a 'Microsoft.NETCore.Platforms' dependency in nuspec

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2976]
https://github.com/dotnet/sdk/blob/0690b28e426f5b7e6dfe7ab4200b83ce3c96bc95/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L81-L87

This should probably have been 'PrivateAssets=All'. 

All aspnet 3.0 Preview 3 packages which target netcoreapp3.0 have this dependency in their nuspec. cc @Eilon @livarcocc 

![image](https://user-images.githubusercontent.com/2696087/53213059-4e1c0280-35fc-11e9-9591-32f81f33502c.png)

**Comment by livarcocc** [comment]
@dsplaisted to take a look.
