### ISSUE TITLE
dotnet cli does not handle arguments with quotes from PowerShell correctly

### ISSUE THREAD

**Issue by zivkan** [dotnet/sdk#29770]
### Description

Imagine a program that takes a password as a command line argument. This password has a quote character in it. So, we need to pass a string with an embedded quote.

Here are a bunch of ways, with PowerShell escaping syntax, that the program can be invoked:

```
.\bin\Debug\net7.0\cliParsing.exe "StringWith`"Quote`""
dotnet .\bin\Debug\net7.0\cliParsing.dll "StringWith`"Quote`""
.\bin\Debug\net48\cliParsing.exe "StringWith`"Quote`""
dotnet run -f net48 -- "StringWith`"Quote`""
dotnet run -f net7.0 -- "StringWith`"Quote`""
```

None of these outputs are what I, as a user of the `cliParsing` app, would expect. Of these, only the .NET Framework 4.8 exe had the quotes in the `Environment.CommandLine` output, but even then the `arg[0]` no longer had the quote characters.

Trying the same command lines in `cmd.exe` and changing the escape character to `\"`, all the outputs are what I, as a user, would expect.

### Reproduction Steps

```cs
Console.WriteLine("Number of arguments: " + args.Length);
for (int i = 0; i < args.Length; i++)
{
    Console.WriteLine("Arg " + i + ": " + args[i]);
}
Console.WriteLine("Original args: " + Environment.CommandLine);
```

Try the command lines I provided in the description above

### Expected behavior

The output from the PowerShell commands, should match the output from the cmd.exe commands, in the "Actual behavior" section below (Both `arg[0]` and `Envionrment.CommandLine` should contain the `"` characters in the "string with quotes").

### Actual behavior

In powershell:

```text
PS C:\src\test\cliParsing> .\bin\Debug\net7.0\cliParsing.exe "StringWith`"Quote`""
Number of arguments: 1
Arg 0: StringWithQuote
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll StringWithQuote
PS C:\src\test\cliParsing> dotnet .\bin\Debug\net7.0\cliParsing.dll "StringWith`"Quote`""
Number of arguments: 1
Arg 0: StringWithQuote
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll StringWithQuote
PS C:\src\test\cliParsing> .\bin\Debug\net48\cliParsing.exe "StringWith`"Quote`""
Number of arguments: 1
Arg 0: StringWithQuote
Original args: "C:\src\test\cliParsing\bin\Debug\net48\cliParsing.exe" StringWith"Quote"
PS C:\src\test\cliParsing> dotnet run -f net48 -- "StringWith`"Quote`""
Number of arguments: 1
Arg 0: StringWithQuote
Original args: "C:\src\test\cliParsing\bin\Debug\net48\cliParsing.exe"  StringWithQuote
PS C:\src\test\cliParsing> dotnet run -f net7.0 -- "StringWith`"Quote`""
Number of arguments: 1
Arg 0: StringWithQuote
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll StringWithQuote
```

in cmd.exe:

```text
C:\src\test\cliParsing>.\bin\Debug\net7.0\cliParsing.exe "StringWith\"Quote\""
Number of arguments: 1
Arg 0: StringWith"Quote"
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll "StringWith\"Quote\""

C:\src\test\cliParsing>dotnet .\bin\Debug\net7.0\cliParsing.dll "StringWith\"Quote\""
Number of arguments: 1
Arg 0: StringWith"Quote"
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll "StringWith\"Quote\""

C:\src\test\cliParsing>.\bin\Debug\net48\cliParsing.exe "StringWith\"Quote\""
Number of arguments: 1
Arg 0: StringWith"Quote"
Original args: .\bin\Debug\net48\cliParsing.exe  "StringWith\"Quote\""

C:\src\test\cliParsing>dotnet run -f net48 -- "StringWith\"Quote\""
Number of arguments: 1
Arg 0: StringWith"Quote"
Original args: "C:\src\test\cliParsing\bin\Debug\net48\cliParsing.exe"  StringWith\"Quote\"

C:\src\test\cliParsing>dotnet run -f net7.0 -- "StringWith\"Quote\""
Number of arguments: 1
Arg 0: StringWith"Quote"
Original args: C:\src\test\cliParsing\bin\Debug\net7.0\cliParsing.dll "StringWith\"Quote\""
```

**Comment by baronfel** [comment]
I don't think we can feasibly work around all of the different handlings here. We are pretty insulated from the parsing by the time the arguments are provided to the CLI - the runtime has already gotten a hold of them. Then we give the arleady-split tokens to System.CommandLine. If anything this feels like a runtime request to me.

**Comment by zivkan** [comment]
I did create the issue in dotnet/runtime. Someone moved it here :(

At the very least, I think the `"` characters should be visible in `Environment.CommandLine`, like they are for .NET Framework apps. In my opinion, this is a regression vs .NET Framework

**Comment by baronfel** [comment]
I'm going to close this one - we can't support both modes, and .NET is a cross-platform framework that must ensure compatibility across platforms first and foremost.
