### ISSUE TITLE
[NETSDKE2E][Regression]With .Net 8 SDK installed, publish blazorwasm project failed with error "error NETSDK1144: Optimizing assemblies for size failed..."

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#29792]
**Repro steps:**
1. Install .NTE8 SDK(dotnet-sdk-8.0.100-alpha.1.23055.18-win-x64.exe) on windows from https://github.com/dotnet/installer.
2. Install wasm-tools 
dotnet workload install wasm-tools --skip-manifest-update 
3.New blazorWasm 
dotnet new blazorwasm 
4.dotnet publish

**Expected Result:**
publish successfully

**Actual Result:**
Publish failed
![image](https://user-images.githubusercontent.com/65637796/210965545-4bf431c6-83db-4eb7-969e-bcea4168328a.png)

ILLink : error IL1015: Unrecognized command-line option: 'Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.0-alpha.1.23054.18\Sdk\/ILLink.Substitutions.NoWasmIntrinsics.xml'. [C:\Users\v-danche\wasmp
ro\wasmpro.csproj]
C:\Users\v-danche\.nuget\packages\microsoft.net.illink.tasks\8.0.100-1.22619.1\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by s
etting the PublishTrimmed property to false. [C:\Users\v-danche\wasmpro\wasmpro.csproj]

**Note:**
Not repro on previous build: 8.0.100-alpha.1.23054.7(runtime-8.0.0-alpha.1.23053.7 )

dotnet --info:
.NET SDK:
 Version:   8.0.100-alpha.1.23055.18
 Commit:    4e7acfa274

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-alpha.1.23055.18\

Host:
  Version:      8.0.0-alpha.1.23054.18
  Architecture: x64
  Commit:       a224371892

.NET SDKs installed:
  8.0.100-alpha.1.23055.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23055.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23054.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.23054.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by WenJunJi01** [comment]
This issue also reproduced on Win ARM64 with NET 8 SDK from https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-win-arm64.exe.
Build info: 8.0.100-alpha.1.23055.16(runtime-8.0.0-alpha.1.23054.18)

**Comment by marek-safar** [comment]
@sbomer could you please update the target due to ILLink .net8 P1 breaking change

/cc @vitek-karas

**Comment by vdanche** [comment]
Checked on today's net8 sdk build:8.0.100-alpha.1.23067.30(runtime- 8.0.0-alpha.1.23067.2) on wndows and win ARM64, this issue is fixed, hence close it.
![image](https://user-images.githubusercontent.com/65637796/213091514-720ae1b2-cae4-4a6c-8307-f54e536502b4.png)
