### ISSUE TITLE
If PublishSingleFile=true is set in the project file it changes the behavior of dotnet build and similar

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#29795]
Setting `PublishSingleFile=true` in the project file has implication on how `dotnet build` and `dotnet run` operates which are unexpected.

It will:
* Build as self-contained - this makes the build slower - it requires the RID specific runtime pack (which is not part of the default SDK install) and it copies all of the runtime into output (lot of files and quite large)
* Build for a specific RID (so not portable which is the default without `PublishSingleFile=true` - the effect of this is that the output is in a different location (the output directory has the RID subdirectory appended to it)
* Use single-file host even for the `dotnet build` output, but without appending anything to it. Honestly it's surprising this even works at all. It's definitely not intended as the right behavior.

I assume some of this is related to the "RID defaulting" behavior introduced in 7.0, but it's questionable if it's a good behavior or not.
The single-file host is just a bug - we should NOT be doing that under any circumstances.

Note that this has effect on `dotnet run` which will use the wrong host to run the app. It seems to mostly work, but it's unclear if there are corner cases where it will break.

**Comment by vitek-karas** [comment]
This is likely one of the reasons why `dotnet run` sometimes just doesn't work at all - see https://github.com/dotnet/sdk/issues/29658.

**Comment by elinor-fung** [comment]
> I assume some of this is related to the "RID defaulting" behavior introduced in 7.0

Maybe fixed by https://github.com/dotnet/sdk/pull/29031? I have a recent 8.0 installed and didn't see the building as self-contained behaviour.

> Use single-file host even for the dotnet build output, but without appending anything to it. Honestly it's surprising this even works at all. It's definitely not intended as the right behavior.

Wow. Looking at the code, it is working (ish?) because the bundle marker/placeholder doesn't get updated - `singlefilehost` determines it is not single-file, so tries to run like normal `apphost`.

**Comment by elinor-fung** [comment]
Apparently we explicitly check that you can use `singlefilehost` - updated to embed the managed dll to run, but not marked as a bundle - to run on app:
https://github.com/dotnet/runtime/blob/3f5210dca709def1e1253916e4244c82b2177e9c/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/StaticHost.cs#L21-L35

I can't think of the scenario for this behaviour (aside from this issue - where `singlefilehost` is being used, but we don't want it to be).

@VSadov @vitek-karas do either of you know if there is an scenario for this / why we seem have some attempt at enabling it?

**Comment by vitek-karas** [comment]
I think this is just history. The test was added when we first build a "static host" which was just apphost with hostfxr and parts of hostpolicy linked in. https://github.com/dotnet/runtime/pull/36230. Since such a host did not have the runtime in it, it made sense to allow it to load the runtime from disk - we basically had to anyway since single-file back then simply unpacked the runtime to disk. Later on we switch to superhost and this behavior makes little sense anymore...

**Comment by marcpopMSFT** [comment]
We changed a bunch of the default self-contained behavior in 8. Is this still an issue needing investigation? (@vitek-karas  @agocke  @elinor-fung @dsplaisted )

**Comment by elinor-fung** [comment]
This is still an issue. The changes to default self-contained made it a bit less egregious (since just setting `PublishSingleFile=true` won't make it self-contained - users have to actually specify self-contained), but the single-file host is still incorrectly being used for build instead of just publish.

**Comment by vitek-karas** [comment]
Maybe a bigger change (for 9 only) would be to decouple apphost creation for build from single-file apphost creation. Basically the "publish single file" step would start over with the executable. Completely independent of the build stuff.  Although I don't know how complex it will be to wire it up with restore (since we need to download the right singlefile host).
