### ISSUE TITLE
[NetSDKE2E][Regression]With .Net 8 SDK installed, the single-file app run failed on Mac with error "Unable to load shared library..."

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#29823]
Repro Steps:

1.Install net 8 SDK: 8.0.100-alpha.1.23056.11 on windows
2.Run “dotnet new console” in CLI to create the project.
3.Run “dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true"to publish the project via CLI.
4.will only generate the single-file app and *.pdb file.
5.Run the output on a Mac machine. (Mac machine doesn't need the SDK installed).
**Expected Result:**
app should run successfully
**Actual Result:**
App run failed with below error
![image](https://user-images.githubusercontent.com/65637796/211274614-bbdb60c3-5321-4031-ad0e-3851d1077f5f.png)

dotnet --info

C:\Users\v-weiwzhang>dotnet --info
.NET SDK:
Version:   8.0.100-alpha.1.23056.11
Commit:    7bea0af7fe Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.100-alpha.1.23056.11\ Host:
  Version:      8.0.0-alpha.1.23055.3
  Architecture: x64
  Commit:       9197fd5551 .NET SDKs installed:
  8.0.100-alpha.1.23056.11 [C:\Program Files\dotnet\sdk] .NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23055.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23055.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.23055.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] Other architectures found:
  None Environment variables:
  Not set global.json file:
  Not found Learn more:https://aka.ms/dotnet/info Download .NET:https://aka.ms/dotnet/download

**Comment by vitek-karas** [comment]
This has been fixed in https://github.com/dotnet/runtime/pull/80294.
@janvorli FYI

**Comment by marcpopMSFT** [comment]
@vdanche Please try with a new build of installer and reactivate if this is not resolved. Runtime with that fix should have flowed already.

**Comment by vdanche** [comment]
> @vdanche Please try with a new build of installer and reactivate if this is not resolved. Runtime with that fix should have flowed already.

This issue has been fixed on today's build: 8.0.100-alpha.1.23059.8(runtime-8.0.0-alpha.1.23058.2 ), thanks
![image](https://user-images.githubusercontent.com/65637796/211512174-d9059da1-c158-40a3-87cf-7e0925084ef9.png)
