### ISSUE TITLE
dotnet.exe steals -d option from dotnet-* tools starting in .NET 6

### ISSUE THREAD

**Issue by bricelam** [dotnet/sdk#29839]
### Describe the bug
After investigating https://github.com/dotnet/efcore/issues/26687, it appears that, starting in .NET 6, `dotnet` is stealing the `-d` option preventing it from being passed to the `dotnet-ef` tool.

### To Reproduce

```cmd
dotnet new console
dotnet add package Microsoft.EntityFrameworkCore.Design

dotnet tool install -g dotnet-ef
dotnet ef dbcontext scaffold X X -d --verbose
```

The verbose output shows that the option has been stripped when invoking the "inner" tool:

> dotnet exec ...ef.dll dbcontext scaffold X X ...

If I invoke the tool using the stub instead, it works:

```cmd
dotnet-ef dbcontext scaffold X X -d --verbose
```

> dotnet exec ...ef.dll dbcontext scaffold X X -d ...

### Further technical details
- Repros using both the .NET 6 and 7 SDKs (via global.json)
- Works using the .NET 5 SDK
- I suspect it was broken by 938a4048e534fb5abad2ba0b901c1884c202b917

**Comment by baronfel** [comment]
I think you're right - specifically [this line](https://github.com/dotnet/sdk/blob/be8529b23ca7d3748343df9f2e699b401abcd9ea/src/Cli/dotnet/Program.cs#L238) I think has removed all aliases of the Diagnostics option.

Normally we want this for other SDK-bundled commands, but for tools we should have an alternative mechanism that doesn't mutate the args array.

**Comment by Forgind** [comment]
This was fixed, though it didn't meet the bar for servicing, so it's in 8.0.2xx
