### ISSUE TITLE
.NET 6 SDK latest version endpoint returns incorrect version

### ISSUE THREAD

**Issue by Freakazoid182** [dotnet/sdk#29878]
My apologies if this isn't the correct place to raise this issue.

### Describe the bug
[.NET 6 SDK latest version endpoint](https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version) isn't outputting the correct version

### To Reproduce

Go to https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version

Currently shows `6.0.113`. The latest version should be `6.0.405` (at time of writing).

We use this endpoint to keep our own custom build containers up to date with the latest SDK patches through nightly updates. This came to light because we configured a minimal version of `6.0.201` on our project's `global.json`

**Comment by baronfel** [comment]
@leecow do you know who we can talk to about the latest SDK version URL?

**Comment by leecow** [comment]
[dotnet/Sdk/6.0/latest.version](https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version) is different from what's presented in the releases.json. 

@rbhanda or @dcwhittaker - can you please take a look?

**Comment by rbhanda** [comment]
I have updated the https://dotnetcli.azureedge.net/dotnet/Sdk/6.0/latest.version to 6.0.405.
