### ISSUE TITLE
.NET 7.0: Arm64 Docker build fails with NullReferenceException for TargetOutputs on restore step

### ISSUE THREAD

**Issue by DrEsteban** [dotnet/sdk#29892]
I have a project that I'm trying to upgrade from .NET 6.0 -> .NET 7.0. I run this project as a container on a Raspberry Pi, so I run my `docker build`s with `--platform arm64`. I don't build _on_ the Pi, but on my Windows 11 machine.

Here is a direct link to a branch in my project where I'm attempting to upgrade to .NET 7.0: https://github.com/DrEsteban/SolarGateway_PrometheusProxy/tree/net7.0

**Repro steps**
The following _works_:
1. Checkout repository
2. Open command prompt to repo root
3. `docker build .`
4. **Produces an image as expected**

The following _does not work_:
1. Checkout repository
2. Open command prompt to repo root
3. `docker build --platform arm64 .`
4. **Fails at the `restore` step with:**
```
> [build 4/6] RUN dotnet restore "SolarGateway_PrometheusProxy.csproj":
#10 7.132   Determining projects to restore...
#10 7.187 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1235,7): error MSB4018: The "MSBuild" task failed unexpectedly. [/src/SolarGateway_PrometheusProxy.csproj]
#10 7.187 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1235,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/src/SolarGateway_PrometheusProxy.csproj]
#10 7.187 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1235,7): error MSB4018:    at InvokeStub_MSBuild.get_TargetOutputs(Object, Object, IntPtr*) [/src/SolarGateway_PrometheusProxy.csproj]
#10 7.187 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1235,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/src/SolarGateway_PrometheusProxy.csproj]
#10 7.188 /usr/share/dotnet/sdk/7.0.102/NuGet.targets(1235,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutputs" parameter. Object reference not set to an instance of an object. [/src/SolarGateway_PrometheusProxy.csproj]
```

**Comment by alexrosenfeld10** [comment]
I'm having the same issue.

**Comment by alexrosenfeld10** [comment]
seems like a duplicate of https://github.com/dotnet/sdk/issues/28971 ?

**Comment by DrEsteban** [comment]
@alexrosenfeld10 The root cause could very well be the same, but note the error messages in those 2 issues are much different than what I'm seeing. Same step in the process, but a very different error.

**Comment by DrEsteban** [comment]
Also, here's an update. I just pulled the latest versions of `mcr.microsoft.com/dotnet/sdk:7.0` and `mcr.microsoft.com/dotnet/aspnet:7.0` and tried the build again, and the error message is _slightly_ different now:

```
 > [build 4/6] RUN dotnet restore "SolarGateway_PrometheusProxy.csproj":
#11 8.090   Determining projects to restore...
#11 8.256 /usr/share/dotnet/sdk/7.0.103/NuGet.targets(1109,7): error MSB4018: The "RemoveDuplicates" task failed unexpectedly. [/src/SolarGateway_PrometheusProxy.csproj]
#11 8.256 /usr/share/dotnet/sdk/7.0.103/NuGet.targets(1109,7): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/src/SolarGateway_PrometheusProxy.csproj]
#11 8.256 /usr/share/dotnet/sdk/7.0.103/NuGet.targets(1109,7): error MSB4018:    at InvokeStub_RemoveDuplicates.get_Filtered(Object, Object, IntPtr*) [/src/SolarGateway_PrometheusProxy.csproj]
#11 8.256 /usr/share/dotnet/sdk/7.0.103/NuGet.targets(1109,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [/src/SolarGateway_PrometheusProxy.csproj]
#11 8.257 /usr/share/dotnet/sdk/7.0.103/NuGet.targets(1109,7): error MSB4028: The "RemoveDuplicates" task's outputs could not be retrieved from the "Filtered" parameter. Object reference not set to an instance of an object. [/src/SolarGateway_PrometheusProxy.csproj]
```

**Comment by DrEsteban** [comment]
And just to clarify, this issue doesn't repro at all when I use the .NET 6 SDK & images.

**Comment by alexrosenfeld10** [comment]
yep I downgraded to `net6.0` today because of similar stuff.

**Comment by marcpopMSFT** [comment]
Adding @richlander who's been doing a lot of docker scenarios similar to this one to take a look.

**Comment by Jesn** [comment]
```
#50 29.03 /usr/share/dotnet/sdk/7.0.400/NuGet.targets(1244,7): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) [**/HttpApi.Host.csproj]

#50 29.03 /usr/share/dotnet/sdk/7.0.400/NuGet.targets(1244,7): error MSB4028: The "MSBuild" task's outputs could not be retrieved from the "TargetOutputs" parameter. Object reference not set to an instance of an object. [**/Rich.MagicNetWork.HttpApi.Host.csproj]

```
I have also encountered similar problems. I have succeeded several times, but 99% have failed

**Comment by Jesn** [comment]
```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS build
```
add `--platform=$BUILDPLATFORM ` 


<img width="1087" alt="image" src="https://github.com/dotnet/sdk/assets/5728274/3d6c48ad-d97d-46f5-9c72-3a4c3de8adb9">

**Comment by DrEsteban** [comment]
Hmm I tried adding the `--platform` flag to the Dockerfile itself as described above, but continue to see the same issues during package restore.

**Comment by DrEsteban** [comment]
This article, and .NET 8.0 in general, has helped me greatly!!

https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/

**Comment by DrEsteban** [comment]
Marking as closed due to improvements in .NET 8.0 container support.

**Comment by yabood** [comment]
> ```
> FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS build
> ```
> 
> add `--platform=$BUILDPLATFORM `
> <img alt="image" width="1087" src="https://private-user-images.githubusercontent.com/5728274/262961854-3d6c48ad-d97d-46f5-9c72-3a4c3de8adb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzM0NDksIm5iZiI6MTcxMDczMzE0OSwicGF0aCI6Ii81NzI4Mjc0LzI2Mjk2MTg1NC0zZDZjNDhhZC1kOTdkLTQ2ZjUtOWM3Mi0zYTRjM2RlOGFkYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDMzOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk1YWFjNTg2MzU4Y2RlZDNhMzZhMzNiMjA1MmQ5MmFjNjZkYzYyMWI5MTliYWI5ZTI2OGMwNjhjNTAxYjhjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YDF_z9BbZfTnoE9IlOXMdTN6Q4Imoh7zuB3n79BkWmo">

This worked, thanks!
