### ISSUE TITLE
Cannot reference WindowsAppSdk and a WPF library in the same project: There was no runtime pack available for win10-arm

### ISSUE THREAD

**Issue by JaykeBird** [dotnet/sdk#29913]
### Describe the bug
I'm trying to build a class library that references both another class library (with `useWPF` set to true), and the NuGet package [Microsoft.WindowsAppSdk](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1). The combination of these two references in this one project seems to be incompatible, as I immediately start seeing these errors, and so far, nothing I've tried has resolved it.

```
There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win10-arm'.		C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448
There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win10-arm-aot'.		C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	
```

Even after making sure I have the latest .NET SDKs and Visual Studio 2022 updates, this occurs. I'm not specifically targeting ARM64 in any way; my build configuration is set to "Any CPU".

I created this issue here as there's been issues about this error brought up here in the past (#22565), but if there's a different/better place I should bring this up instead, let me know.

### To Reproduce
I created a minimum reproduction of the issue I'm facing here: https://github.com/JaykeBird/RuntimePackErrorRepro

To create this on your own:
1. In a new solution, create a WPF class library.
2. In this library's csproj file, reference multiple .NET runtimes in the `<TargetFrameworks>`, such as `net6.0-windows;net7.0-windows`. I don't think referencing multiple runtimes is actually necessary, but I've done it as it reflects my larger library where I first encountered my issue. Also make sure the line `<UseWPF>true</UseWPF>` is present.
3. In this same solution, create another WPF class library.
4. In this second library's csproj file, set the `<TargetFramework>` to `net6.0-windows10.0.19041.0`.
5. Also with this second library, add a project reference to the first library and also add the NuGet package [Microsoft.WindowsAppSdk](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1).
6. Try building the second project.

### Further technical details
- Using Visual Studio 2022 17.4.4 (I also have Visual Studio 2019 installed, but I'm not using it in this scenario)
- Output of `dotnet --info` (I know there's a lot of runtimes, I can't seem to figure out how to remove the older ones):
```
C:\Users\jacob>dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by JaykeBird** [comment]
I tried adding in a <Platforms> line to both projects as suggested elsewhere (https://github.com/microsoft/WindowsAppSDK/issues/3336) but it didn't make a difference.

I'm open to admitting there might be something on my computer that needs to be reset/reinstalled/cleaned out, but I've made sure I'm on the latest stable version available of .NET 7, Visual Studio 2022, and Windows. Trying to clean the solution (either via Visual Studio or dotnet cli) fails with the same error, and deleting the .vs folder in the solution doesn't make a difference.

**Comment by ianeuman** [comment]
I'm also experiencing this same issue in a local repository, I've tried multiple configurations and all of them fail.

1. non-WPF library that depends on a WPF library and Windows SDK
2. WPF library that depends on a library that depends on windows SDK.

The only way that I've found to make it work for my purposes is with a WPF application that depends on both a WPF library and a windows SDK library, and the WPF application needs to target the win10-x64 runtime.

**Comment by JaykeBird** [comment]
Oh my goodness, that's actually what I needed!

By adding the RuntimeIdentifiers line, not the Platforms line as was suggested earlier, I got it to build properly.

`<RuntimeIdentifiers>win10-x64;win10-x86;win10-arm64</RuntimeIdentifiers>`

The Windows App SDK doesn't support all the runtime identifiers that .NET supports out of the box, so that's why the line is needed, to limit the library's runtimes to the same ones that the Windows App SDK supports.

**Comment by ianeuman** [comment]
I'm still having issues even if the library targets the specific runtime identifiers, (I'll probably create a new issue for my use case) but my WPF library has `<Resource>` definitions of assets (images), and when my WPF application tries to build, it tries to copy those assets from the build directory to the WPF application, resulting in:
```
Error	MSB3030	Could not copy the file "...\bin\x64\Debug\net6.0-windows10.0.19041.0\TestLibrary\Resources\image.png" because it was not found.	TestApp	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5150	
```

**Comment by JaykeBird** [comment]
@ianeuman it sounds like the issue you're facing is definitely a different type of thing, but I did just [create an issue](https://github.com/microsoft/WindowsAppSDK/issues/3410) for a problem I was having with getting resource images to display/load.

**Comment by HppZ** [comment]
> I'm still having issues even if the library targets the specific runtime identifiers, (I'll probably create a new issue for my use case) but my WPF library has `<Resource>` definitions of assets (images), and when my WPF application tries to build, it tries to copy those assets from the build directory to the WPF application, resulting in:
> 
> ```
> Error	MSB3030	Could not copy the file "...\bin\x64\Debug\net6.0-windows10.0.19041.0\TestLibrary\Resources\image.png" because it was not found.	TestApp	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5150	
> ```

same!

**Comment by RabidCrab** [comment]
> Oh my goodness, that's actually what I needed!
> 
> By adding the RuntimeIdentifiers line, not the Platforms line as was suggested earlier, I got it to build properly.
> 
> `<RuntimeIdentifiers>win10-x64;win10-x86;win10-arm64</RuntimeIdentifiers>`
> 
> The Windows App SDK doesn't support all the runtime identifiers that .NET supports out of the box, so that's why the line is needed, to limit the library's runtimes to the same ones that the Windows App SDK supports.

This is an old issue that shows up in search results when looking for a solution to this problem, so I would like to clarify that you absolutely must use <RuntimeIdentifiers></RuntimeIdentifiers> and NOT <RuntimeIdentifier></RuntimeIdentifier>, even if you are only using a single runtime identifier.

When I attempted to use <RuntimeIdentifier>win10-x64</RuntimeIdentifier> it would fail, claiming I did not have ARM installed, but  replacing it with<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers> succeeds.
