### ISSUE TITLE
dotnet build/pack generates no executable in NuGet Package

### ISSUE THREAD

**Issue by huaxing-yuan** [dotnet/sdk#29935]
### Describe the bug
We have built a test framework including different components and executable "webrunner.exe".
The framework targets multi-framework, including .NET 4.8 and .NET 6.0/7.0
We configured the project to generate NuGet Packages during `dotnet build`

After dotnet build, in `bin/debug/net6.0` folder, we can find everything include the runner as `executable`
![image](https://user-images.githubusercontent.com/37816968/212330709-02193f5a-5086-4f91-a109-846504a1ef37.png)

but inside the NuGet Package, we can only find the dll without the exe.
![image](https://user-images.githubusercontent.com/37816968/212330875-2a3d9029-13cc-470a-bd32-c1749ac12398.png)

Inside the same NuGet Package, webrunner.exe can be found under .NET 4.8

### which does not work:
When a user adopts the framework and starts test project on .NET 6/7 (a class library), after installing the NuGet package, there is no runner executable and .deps.json in output folder. even we want to launch via dotnet.exe there will be an error:

```
Cannot use file stream for t\bin\Debug\net6.0\WebRunner.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '\bin\Debug\net6.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '\bin\Debug\net6.0\WebRunner.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '\bin\Debug\net6.0\WebRunner.runtimeconfig.json' file and specify the appropriate framework.
```

For now we have to stick on .net 4.8 or we have to copy the executable from bin folder if they wants .net core/6.0
Is this a bug for dotnet build/pack?
As we are using SDK style project, we can't use nuget.exe any more.

**Comment by cjvaland** [comment]
> ### Describe the bug
> We have built a test framework including different components and executable "webrunner.exe". The framework targets multi-framework, including .NET 4.8 and .NET 6.0/7.0 We configured the project to generate NuGet Packages during `dotnet build`
> 
> After dotnet build, in `bin/debug/net6.0` folder, we can find everything include the runner as `executable` ![image](https://user-images.githubusercontent.com/37816968/212330709-02193f5a-5086-4f91-a109-846504a1ef37.png)
> 
> but inside the NuGet Package, we can only find the dll without the exe. ![image](https://user-images.githubusercontent.com/37816968/212330875-2a3d9029-13cc-470a-bd32-c1749ac12398.png)
> 
> Inside the same NuGet Package, webrunner.exe can be found under .NET 4.8
> 
> ### which does not work:
> When a user adopts the framework and starts test project on .NET 6/7 (a class library), after installing the NuGet package, there is no runner executable and .deps.json in output folder. even we want to launch via dotnet.exe there will be an error:
> 
> ```
> Cannot use file stream for t\bin\Debug\net6.0\WebRunner.deps.json]: No such file or directory
> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '\bin\Debug\net6.0\'.
> Failed to run as a self-contained app.
>   - The application was run as a self-contained app because '\bin\Debug\net6.0\WebRunner.runtimeconfig.json' was not found.
>   - If this should be a framework-dependent app, add the '\bin\Debug\net6.0\WebRunner.runtimeconfig.json' file and specify the appropriate framework.
> ```
> 
> For now we have to stick on .net 4.8 or we have to copy the executable from bin folder if they wants .net core/6.0 Is this a bug for dotnet build/pack? As we are using SDK style project, we can't use nuget.exe any more.

Hi @huaxing-yuan, did you manage to get the exe file in the nuget package?
