### ISSUE TITLE
Unable to build macos binaries on linux

### ISSUE THREAD

**Issue by hellozyemlya** [dotnet/sdk#29955]
### Describe the bug
When I have `<TargetFrameworks>net6.0-macos12;net6.0-windows7</TargetFrameworks>` in my project, in official docker image of dotnet sdk I can execute `dotnet workload restore`, but later build failed with(sdk 6.0).
```
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018: The "FindItemWithLogicalName" task failed unexpectedly. [/project/MyProject/MyProject.csproj]
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018: System.DllNotFoundException: Unable to load shared library '/usr/lib/libc.dylib' or one of its dependencies. In order to help di
agnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/libc.dylib: cannot open shared object file: No such file or directory [/project/MyProject/MyProject.csproj]
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018:    at Xamarin.Utils.PathUtils.realpath(String path, IntPtr buffer) [/project/MyProject/MyProject.csproj]
```

### To Reproduce
- add mac target framework
- run `dotnet workload restore` in official dotnet sdk image
- run `dotnet build`

### Exceptions (if any)
```
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018: The "FindItemWithLogicalName" task failed unexpectedly. [/project/MyProject/MyProject.csproj]
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018: System.DllNotFoundException: Unable to load shared library '/usr/lib/libc.dylib' or one of its dependencies. In order to help di
agnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/libc.dylib: cannot open shared object file: No such file or directory [/project/MyProject/MyProject.csproj]
/usr/share/dotnet/packs/Microsoft.macOS.Sdk/13.0.784/tools/msbuild/macOS/Xamarin.Shared.targets(1400,3): error MSB4018:    at Xamarin.Utils.PathUtils.realpath(String path, IntPtr buffer) [/project/MyProject/MyProject.csproj]
```

**Comment by baronfel** [comment]
Hi, is there a sample project that could be used to investigate this scenario? Is adding the TargetFrameworks to a `dotnet new console` project enough to trigger it?

**Comment by baronfel** [comment]
I was able to reproduce this, I've attached a binlog (with .zip added, remove that before use) detailing the scenario for later triage.

[macos-tfm.binlog.zip](https://github.com/dotnet/sdk/files/10451232/macos-tfm.binlog.zip)

**Comment by rolfbjarne** [comment]
Building any Apple-related target framework (netX.Y-ios, netX.Y-macos, netX.Y-tvos, netX.Y-maccatalyst) is only supported on Mac and Windows (and on Windows the build is done remotely on a Mac - in other words you'll always need a Mac). Building on Linux will not work (as you've found out).

We have an issue open to show a better error message (https://github.com/xamarin/xamarin-macios/issues/17289), so I'm closing this issue.
