### ISSUE TITLE
`dotnet pack -o` does not seem to work

### ISSUE THREAD

**Issue by nagilson** [dotnet/sdk#29979]
![image](https://user-images.githubusercontent.com/23152278/213021035-480f40a8-7951-45ac-af4a-6eb16c75c3d6.png)

The documentation says `dotnet pack -o` or `--output` should work, and it appears to be forwarded as an OutputPath option, `PackageOutputPath.` But the above image shows the output directory is not used. 

I know there were some changes to `-o` recently: fb98b97081505a39ba288d0c0cff7f4b4bc80f42 But maybe this just never worked, or I'm doing something wrong. Doesn't work if the path is quoted either. 

```
Host:
  Version:      8.0.0-alpha.1.23065.5
  Architecture: x64
  Commit:       2908445dae

```

**Comment by baronfel** [comment]
I couldn't repro on one of my OSS projects just now using `eng/dogfood.ps1` from main at commit be8529b23c. The MSBuild command line that results for me is:

```
"D:\Code\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\sdk\8.0.100-dev\MSBuild.dll
  -maxcpucount
  -verbosity:m
  -restore
  -target:pack
  --property:_IsPacking=true
  -property:PackageOutputPath=D:\Code\LanguageServerProtocol\local
  -property:_CommandLineDefinedOutputPath=true
  .\src\Ionide.LanguageServerProtocol.fsproj
  -bl"
```

And the package did end up in the `local` path as I expected. can you try again when you get a moment to see if it was a one-off?

**Comment by nagilson** [comment]
Doesn't repro now, closing.
