### ISSUE TITLE
Create a Nuget package for the full SDK

### ISSUE THREAD

**Issue by Sarabeth-Jaffe-Microsoft** [dotnet/sdk#300]
Microsoft.Build.Runtime only puts together MSBuild, it is not a full build environment. To be usable as a library, a package containing MSBuild, Nuget, C# compilers, compiler targets must exist.

We think the SDK is the right place to put this issue so that this package can be consumed by users & the CLI repo.

https://github.com/Microsoft/msbuild/issues/1096

**Comment by Forgind** [comment]
Old bug triage:
I think that's basically what the SDK is at this point, or alternatively BuildTools. Since this issue is 7 years old, it seems to have been resolved in the interim without closing this issue.
