### ISSUE TITLE
[ARM64]After installing the .NET 8.0 SDK and running "dotnet workload install wasm-tools-net6" using the command line will meet: "workload ID wasm-tools-net6 is not supported on this platform".

### ISSUE THREAD

**Issue by v-wenkecheng** [dotnet/sdk#30019]
**Azure DevOps work item**:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1726188

**Version used:**
1. Install .NET 6.0 SDK [sdk-6.0.405-windows-arm64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.405-windows-arm64-installer).
2. Install .NET 8.0 SDK from [GitHub - dotnet/installer](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgithub.com%2fdotnet%2finstaller&data=04%7c01%7cv-meli4%40microsoft.com%7c7c321d6fae484b57ce0e08d9d41dde24%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637774047037391238%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=rVMCLxHkTMTRGwoiIwqnfihpuVCUMhuPn0KmnbnDKPQ%3D&reserved=0), main (8.0.x Runtime)
Feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

**Testcases Affected**
[[7.0/6.0] 6.0_BlazorWebassemblyAot.md](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.3/E2EWalkthroughs/VS/AspNetCore60/6.0_BlazorWebassemblyAot.md)

**Platform**
- [x] Windows
- [ ] Linux
- [ ] Mac

**Repro Steps**

Run the following command from command prompt:

     `dotnet workload install wasm-tools-net6`

**Note:**
This issue does not repro on 7.0/6.0 project without 8.0 installed.
This issue is not repro on x64 machine.
This issue only repro on arm64.
Creating a Blazor WebAssembly App project using VS and checking the "User ahead-of-time (AOT)" option will meet the following error: The SDK 'Microsoft.NETCore.App.Runtime.AOT.Cross.net6.browser-wasm' specified could not be found. 
![67adffaf-1fa7-45aa-867c-0c1d85707324](https://user-images.githubusercontent.com/69494255/213401868-923acd5f-bf2b-4a7e-a680-41506b6145ff.png)

**Actual Result**
Run ’dotnet workload install wasm-tools-net6‘ using command line will meet:’Workload ID wasm-tools-net6 isn't supported on this platform’.
![7b10dab5-dc12-4abd-a2bf-882338ec9ae3](https://user-images.githubusercontent.com/69494255/213413079-bd04cb28-71a8-403b-8f8b-92be4c111cd7.jpg)
**Expected Result**
The workload wasm-tools-net6 can be installed successfully.

**Comment by v-wenkecheng** [comment]
Verify this issue with Dev17.6 preview 1([d17.6-33403.233]+8.0 SDK([8.0.100-preview.1.23106.1), this issue also repro.

**Comment by Andy-Win** [comment]
I am able to reproduce this issue on 8.0 Preview 1 and Preview 2

**Comment by Zhanglirong-Winnie** [comment]
I can repro this issue on ARM machine when I want to install MAUI workload: 17.6 Preview2 + .NET SDK 8.0.100-preview.2.23153.6.
Display: "workload ID maui isn't supported on this platform."
![image](https://user-images.githubusercontent.com/77434865/223372423-fcd18fb9-8dfd-46e4-9e1c-ec1ce8b34ecb.png)

**Comment by marcpopMSFT** [comment]
@lewing @steveisok it looks like the arm64 authoring isn't in main (I see win-arm64 in the 7.0 branch for net6): https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/WorkloadManifest.json.in#L15

Can ya'll get that updated in runtime and double check emsdk as well?  Looks like it's only the .net6 one that's missing as both current and .net7 have win-arm64 platforms listed.

**Comment by v-wenkecheng** [comment]
Verified with Dev17.6 Preview 3 + SDK 8.0.100-preview.3 on arm machine, this issue doesn't repro.
