### ISSUE TITLE
Microsoft.NET.Sdk.Web should default to TrimMode=full

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#30059]
Today, we are defaulting `TrimMode=partial` in `Microsoft.NET.Sdk.Web`:

https://github.com/dotnet/sdk/blob/67b59150e3407428c4114c8c39ade5170b98c3ad/src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets#L89-L90

```xml
    <!-- If TrimMode has not already been set, default to partial trimming, as AspNet is not currently fully trim-compatible -->
    <TrimMode Condition="'$(PublishTrimmed)' == 'true' and '$(TrimMode)' == ''">partial</TrimMode>
```

In the "api" template being added in https://github.com/dotnet/aspnetcore/pull/46064, we are explicitly setting TrimMode=full.

Instead, we should do one of the following:

1. Remove the above code, and just let the `TrimMode=full` default from the runtime be applied to Microsoft.NET.Sdk.Web projects.
2. Change the default to `partial` only if we aren't also publishing for NativeAOT. Basically adding `and '$(PublishAot)' != 'true'` above.

My goal would be we do (1). For places in ASP.NET that aren't fully trim-compatible, the app developer should get a warning (even from within ASP.NET code) to tell them what are things that aren't going to work.

We may consider just doing (2) in .NET 8, until things like MVC and Razor pages work correctly in fully trimmed apps.

cc @JamesNK @DamianEdwards @davidfowl

**Comment by halter73** [comment]
> We should think about defaulting to full with `PublishTrimmed` true as well 

https://github.com/dotnet/sdk/pull/29984#discussion_r1080813282

There's some debate one whether we'll be ready in .NET 8, but we will keep this issue open to track changing the TrimMode default from "partial" to "full" like the Microsoft.NET.Sdk default.

**Comment by mkArtakMSFT** [comment]
@adityamandaleeka assigning this to you as this is `minimal` related.

**Comment by eerhardt** [comment]
> as this is minimal related.

Note that this issue applies to "all" ASP.NET server app models - minimal APIs, MVC, Razor Pages, etc.

**Comment by agocke** [comment]
I would go for (1) as well.

That code was specifically meant to provide compatibility for Blazor WASM, which was a pre-existing trimming scenario. Having it apply to all of ASP.NET wasn't really intentional on my part.

`partial` isn't really intended for new trimming scenarios. It has no effect on trim warnings, so it doesn't really help in the task of making things trim compatible, and our current goal for trimming is to give users a very clear statement on whether or not their app works, based on the warning behavior.

**Comment by adityamandaleeka** [comment]
@eerhardt Can this be closed now?

**Comment by eerhardt** [comment]
Yes, this was fixed with https://github.com/dotnet/sdk/pull/33962 and https://github.com/dotnet/sdk/pull/34030.
