### ISSUE TITLE
[GenAPI] missing `new` keyword on return types

### ISSUE THREAD

**Issue by smasher164** [dotnet/sdk#30082]
From https://github.com/dotnet/roslyn/issues/66376

> 
> Examples:
> 
>     new bool Add(T item);
>     public static new int Default { get { throw null; } }
> 
> After roundtrip: source -> ISymbol-> SyntaxGenerator -> source:
> 
>     bool Add(T item);
>     public static int Default { get { throw null; } }

According to @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/66376#issuecomment-1385982576, `new` is a source-only construct that's not in the metadata, and needs to be handled in GenAPI.

**Comment by oleksandr-didyk** [comment]
Adding here an example of this issue occurring during SBRP flow:

  - generated reference packages for `NuGet.ProjectModel: 6.2.2`
  - reference package for its dependency `NuGet.Configuration: 6.2.2` was also generated
  - build of the dependency package would fail with the exception `error CS0114: 'RepositoryItem.Name' hides inherited member 'TrustedSignerItem.Name'.`

The generated code:
```csharp
public string Name { get { throw null; } set { } }
```

The [actual implementation](https://github.com/NuGet/NuGet.Client/blob/b4c0a7c9134082d4f495a49dd644e4e0f8d9c95f/src/NuGet.Core/NuGet.Configuration/Settings/Items/RepositoryItem.cs#L19):
```csharp
public new string Name
{
    get => base.Name;
    set => SetName(value);
}
```
