### ISSUE TITLE
Trouble moving bin/ and obj/ to .bin/ and .obj/

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3009]
*Moved from https://github.com/dotnet/project-system/issues/1437#issuecomment-469568035*

@dzmitry-lahoda wrote:

Not sure if right thread - but some tooling is wrong...

See the line with `ProjectAssetsFile`? If I remove it - my `csproj` fails to build. 
Why I ever need it? My task for to build from VS 2017 and VS Code and from `dotnet` command line into `.bin` and `.obj` because of Unity:(. So I did it. But when VS 2017 opens solution - it generates `obj`. So I did fix which kinda should work.  But got issues - I followed the path, and got into `C:\Program Files\dotnet\sdk\2.2.102\Sdks\Microsoft.NET.Sdk\targets\` folder and into `ProjectAssetsFile`. So here is fix:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <!-- fixing VS 2017 bug which makes it output directory which is not requested -->
  <PropertyGroup>
    <ProjectAssetsFile>$(MSBuildProjectDirectory)\.obj\project.assets.json</ProjectAssetsFile>
  </PropertyGroup>
  <PropertyGroup>
      <PreBuildEvent>
       IF EXIST "$(MSBuildProjectDirectory)\.obj\obj" (
         rmdir "$(MSBuildProjectDirectory)\.obj\obj" /s /q
       )
       IF EXIST "$(MSBuildProjectDirectory)\obj" (
         move  "$(MSBuildProjectDirectory)\obj" "$(MSBuildProjectDirectory)\.obj"
       )
      </PreBuildEvent>
      
      <PostBuildEvent>
       IF EXIST "$(MSBuildProjectDirectory)\.obj\obj" (
         rmdir "$(MSBuildProjectDirectory)\.obj\obj" /s /q
       )
       IF EXIST "$(MSBuildProjectDirectory)\obj" (
         move  "$(MSBuildProjectDirectory)\obj" "$(MSBuildProjectDirectory)\.obj"
       )
      </PostBuildEvent>      
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>.bin\Debug\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Debug\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Debug\</IntermediateOutputPath>
    <BaseOutputPath>.bin\Debug\</BaseOutputPath>
    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>.bin\Release\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Release\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Release\</IntermediateOutputPath>
    <BaseOutputPath>.bin\Release\</BaseOutputPath>
    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="$(xUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(xUnitVersion)" />
  </ItemGroup>
  </ItemGroup>  
</Project>
````

There is other workaround. Very weird - depends on order of and some hacky `Import` declarations, but it breaks `xunit` runner and VS Code. Ssee lines with `Microsoft.NET.Sdk`:
```xml
<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>.bin\Debug\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Debug\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Debug\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>.bin\Release\</OutputPath>
    <BaseIntermediateOutputPath>.obj\Release\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>.obj\Release\</IntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <ItemGroup>
    <None Remove=".gitignore" />

    <None Remove="**/*.meta" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.0" />
    <PackageReference Include="System.IO.Pipelines" Version="4.5.3" />
    <PackageReference Include="System.Memory" Version="4.5.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```
Does next relates dotnet/project-system#1438? 

I was not able to find solution on SO. 

Should I create separate issue with that with steps:
1. Build into `.bin` and `.obj`
2. Ensure there are no `bin` and `obj` created.
3. Check VS Code, VS 2017, dotnet.exe

Or my case is relevant for `respecting`?

**Comment by nguerrera** [comment]
You need to set BaseIntermediateOutputPath before common props are imported as in the second example. This can be simplified to the following:

``` xml
<Project>
  <PropertyGroup>
    <BaseOutputPath>.bin</BaseOutputPath>
    <BaseIntermediateOutputPath>.obj</BaseIntermediateOutputPath>
 </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="**/*.meta" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.0" />
    <PackageReference Include="System.IO.Pipelines" Version="4.5.3" />
    <PackageReference Include="System.Memory" Version="4.5.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

You can further simplify this back to the standard `<Project Sdk=...` syntax by moving the top-most property group to a Directory.Build.props file. This file can be placed in a directory above all of the projects that you want to build to .obj/.bin. You may also want to put other common settings like the `LangVersion` there. See 

### Directory.Build.props
``` xml
<Project>
  <PropertyGroup>
    <BaseOutputPath>.bin</BaseOutputPath>
    <BaseIntermediateOutputPath>.obj</BaseIntermediateOutputPath>
 </PropertyGroup>
</Project>
```

### Project.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="**/*.meta" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.0" />
    <PackageReference Include="System.IO.Pipelines" Version="4.5.3" />
    <PackageReference Include="System.Memory" Version="4.5.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
  </ItemGroup>
</Project>
``` 

This should work in VS, VS Code, and dotnet, but so should your second example before the simplifications above, so I will double check that I'm not missing something...

See https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

**Comment by nguerrera** [comment]
Ah, I think I see the issue with your second example outside VS: it is relying on the Configuration property being set, which will not happen until the Sdk.props import if you `dotnet build `the csproj instead of a sln  that contains it. Likewise and likewise if your VS Code build is operation on the csproj and not a sln.

Can you try one of my two examples?  They use only BaseOutputPath and BaseItermediateOutputPath and do not need to spell out different directories for Debug and Release. These will be appended to to BaseXxx as appropriate.

I am able to build this in VS, VS Code, and dotnet.

Make sure to delete any leftover obj\ and bin\ folders from failed attempts as stale assembly info in the old intermediate directory can cause duplicate assembly attribute errors.

**Comment by dzmitry-lahoda** [comment]
My second case https://gitlab.com/dzmitry-lahoda/dotnet-sdk-custom-output-folder/tree/master/act1

Suggested fix without configuration https://gitlab.com/dzmitry-lahoda/dotnet-sdk-custom-output-folder/tree/master/act2 - no bin or obj created, but tests do not run

Will continue with directory props.

**Comment by dzmitry-lahoda** [comment]
Thanks for good issue handling. 

I have tried various approaches in isolated manner https://gitlab.com/dzmitry-lahoda/dotnet-sdk-custom-output-folder/  . 

As of now `Directory.Build.props` looks as most viable approach for our repository and I will try it soon.

**Comment by dzmitry-lahoda** [comment]
`Directory.Build.props` works on our whole product (Unity, VS Code, VS). 
Not sure why bin and obj folders are generated by VS code, and why VS Code and VS are different in behaviour. But should it be some fix into VS code? Or some guideline... Or just close story (still can be searched) for.

**Comment by nguerrera** [comment]
The differences in behavior have to do with referencing `$(Configuration)` before Microsoft.NET.Sdk.props is imported. When you build a sln or from VS the $(Configuration) will always be set, when you build a csproj directly, it will get set in that import.

It is rare to reference Configuration before the props are imported, but that is what you had in your second example:

``` xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  ...
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
```

**Comment by nguerrera** [comment]
I'm going to go ahead and close this since there isn't a defect, but the guidelines are:

1. Do not set BaseIntermediateOutputPath after Sdk props import (or in the body of the csproj with `<Project Sdk=...>` (This is what your first example has wrong, there should have been a warning in the build about it.)
2. Do not reference Configuration before the Sdk props import` (This is what your second example has wrong.

A reasonable simplification is to always set BaseIntermediateOutputPath in Directory.Build.props. That works, keeps your project files clean and does not require subtle analysis like above to reason about.
