### ISSUE TITLE
Unable to publish two Blazor projects in a solution

### ISSUE THREAD

**Issue by bamdad-b** [dotnet/sdk#30092]
I'm trying to publish an ASP.NET Core MVC project, referencing a Blazor wasm application. The Blazor wasm project is referencing another Blazor project  (a component library)
I get the following error on publish:

> Conflicting assets with the same target path 'DemoComponents/_framework/System.ComponentModel.dll.br'. For 'Publish' assets 'Identity: C:\repos\DemoWASM\DemoWASM.Components\obj\Release\net7.0\compress\+cPOdMqm.br, SourceType: Project, SourceId: DemoWASM.Components, ContentRoot: C:\repos\DemoWASM\DemoWASM.Components\bin\Release\net7.0\publish\wwwroot\, BasePath: DemoComponents, RelativePath: _framework/System.ComponentModel.dll.br, AssetKind: Publish, AssetMode: All, AssetRole: Alternative, RelatedAsset: C:\repos\DemoWASM\DemoWASM.Components\obj\Release\net7.0\linked\System.ComponentModel.dll, AssetTraitName: Content-Encoding, AssetTraitValue: br, CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: C:\repos\DemoWASM\DemoWASM.Components\obj\Release\net7.0\linked\System.ComponentModel.dll'
> and
> 'Identity: C:\repos\DemoWASM\DemoWASM\Client\obj\Release\net7.0\compress\+cPOdMqm.br, SourceType: Project, SourceId: DemoWASM.Components, ContentRoot: C:\repos\DemoWASM\DemoWASM.Components\bin\Release\net7.0\publish\wwwroot\, BasePath: DemoComponents, RelativePath: _framework/System.ComponentModel.dll.br, AssetKind: Publish, AssetMode: All, AssetRole: Alternative, RelatedAsset: C:\repos\DemoWASM\DemoWASM.Components\obj\Release\net7.0\linked\System.ComponentModel.dll, AssetTraitName: Content-Encoding, AssetTraitValue: br, CopyToOutputDirectory: Never, CopyToPublishDirectory: PreserveNewest, OriginalItemSpec: C:\repos\DemoWASM\DemoWASM.Components\obj\Release\net7.0\linked\System.ComponentModel.dll'.
> 

To reproduce the problem, please visit [this repository](https://github.com/bamdad-b/DemoWASM) and publish the **DemoWASM.Server** project with default settings.

I'm using
- Visual Studio 2022 Version 17.4.4
- .NET SDK 7.0.102

**Comment by MahdiAmini98** [comment]
I have this problem too. I need to publish my project and deploy it for my customers. Please take action.

**Comment by rogihee** [comment]
You have defined your component library as another Blazor WebAssembly project, while it should be of type Microsoft.NET.Sdk.Razor

**Comment by bamdad-b** [comment]
Hadn't figured it out. It's now working as expected, thank you.
