### ISSUE TITLE
[net7] Creating a cross-targeted `net7.0-ios` + `net6.0-ios` packages forces consumers to build with net7 workloads

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/sdk#30103]
_From @jeromelaban on Mon, 31 Oct 2022 14:18:39 GMT_

Creating a cross-targeted `net7.0-ios` + `net6.0-ios` packages forces consumers to build with net7 workloads, causing dependents on net6.0 to fail building with the following message:

```
CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
uses 'Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which 
has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.300.0, 
Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
```

This means that any library author currently cannot build packages for net6.0 and net7.0 without resorting to manual package authoring and multi-builds with `global.json` modifications.

### Steps to Reproduce

1. Install .NET 6.0.40x with ios workload
1. Install .NET 7 RC2 with ios workload
2. Create an empty library
3. Pack for `<TargetFrameworks>net6.0-ios;net7.0-ios</TargetFramework>`

### Expected Behavior

`net6.0-ios` binaries reference `Microsoft.iOS` 15.4.300.x

### Actual Behavior

The `net6.0-ios` binaries reference `Microsoft.iOS` 16.0.x

### Environment

.NET 7.0 RC2 with workloads (VS 17.4 Preview 5)

### Build Logs

I can provide those as needed.

As needed.

### Example Project (If Possible)

_Copied from original issue xamarin/xamarin-macios#16524_

**Comment by lewing** [comment]
to me this looks like the problem is coming from the manifest

```
		"Microsoft.iOS.Sdk.net7": {
			"kind": "sdk",
			"version": "16.0.1478",
			"alias-to": {
				"any": "Microsoft.iOS.Sdk"
			}
		},
		"Microsoft.iOS.Sdk.net6": {
			"kind": "sdk",
			"version": "16.0.527",
			"alias-to": {
				"any": "Microsoft.iOS.Sdk"
			}
		},
```

**Comment by steveisok** [comment]
If I'm understanding what @rolfbjarne was saying, for iOS or any platform that plays fast and loose with compat, some/all of the older workload versions should hang around so that we can reference it.  

Yeah, I agree with @lewing, the only way I know how to pull it off is to add however many 15.x variants you need.

**Comment by lewing** [comment]
my understanding is if you add net6.0-ios15 packs and aliases and import those by checking TargetPlatformVersion in the targets file you will get what you for the Micrsoft.iOS reference, if we need ios15 specific builds of runtime we'll have to add those and the version check to the runtime manifest

cc @dsplaisted

**Comment by lewing** [comment]
this would potentially lead to very large workloads even if you split them along the platform version.  I really feel like we keep running into places it where being tied to the manifest versions and forcing everything to be bundled limits things

**Comment by dsplaisted** [comment]
> It seems that specifying the OS version in the TargetFramework could be a way to express this:
> 
> ```
> <TargetFrameworks>net6.0-ios15.4;net7.0-ios16.0</TargetFrameworks>
> ```
> 
> but that doesn't work (the `net6.0-ios15.4` target framework still builds with newer reference assembly from the workload for iOS 16.0, and not the older for iOS 15.4).

As far as I'm understanding it, this is the main problem.

You don't necessarily need to split into separate workloads.  If you want, you can have a single workload that handles multiple versions, and will use the appropriate targeting and runtime packs.  That's essentially what we do in the base SDK, we have a mapping from the target framework to the targeting and runtime pack versions.  You don't have to include all those assets in the workload either, you can have it so if they are not installed they will be downloaded during NuGet restore.

**Comment by rolfbjarne** [comment]
OK, thanks for the ideas how to implement this in the workload, I'll give it a try and see if I can make it work somehow.

**Comment by Youssef1313** [comment]
@rolfbjarne Any updates for this?

**Comment by rolfbjarne** [comment]
> @rolfbjarne Any updates for this?

No updates yet, and it will likely take a little while.

**Comment by yunusefendi52** [comment]
If I were to use `net7.0-ios` in library project now (today) is it going take 16.2 instead of 16.0? Is it the same case for dotnet android also?

Here is an example of MAUI package taken from https://dev.azure.com/xamarin/public/_build/results?buildId=78627&view=artifacts&pathAsName=false&type=publishedArtifacts
![Screen Shot 2023-02-08 at 7 47 38 AM](https://user-images.githubusercontent.com/19399214/217400330-eb8b6bbf-cd2c-42fb-9ae5-2c303b52a818.png)

From Xamarin.Forms:
![Screen Shot 2023-02-08 at 7 50 37 AM](https://user-images.githubusercontent.com/19399214/217400798-03ab40bf-1a08-45a0-9c05-62cc2d079fef.png)

I still don't understand I this work in dotnet and xamarin. Does `net7.0-ios` should implicitly uses the latest version or the minimum version (like 16.2, 16.0 or just 0.0) to avoid this confusion?

**Comment by rolfbjarne** [comment]
> If I were to use `net7.0-ios` in library project now (today) is it going take 16.2 instead of 16.0?

Yes.

> Does `net7.0-ios` should implicitly uses the latest version or the minimum version (like 16.2, 16.0 or just 0.0) to avoid this confusion?

I believe there will be confusion no matter what we do, because if we don't implicitly use the latest version, people will have to opt in to any updates we ship whenever Apple releases OS updates.

**Comment by jeromelaban** [comment]
@rolfbjarne @lewing would you know if there's another SDK or runtime related issue that can be followed about a progress on this issue? Thanks!

**Comment by rolfbjarne** [comment]
@jeromelaban this is the correct issue to follow

**Comment by mattleibow** [comment]
This same thing happens when you have a net8 SDK installed and you build for net7. Is there any hacks we can do to make it work for now?

**Comment by rolfbjarne** [comment]
> This same thing happens when you have a net8 SDK installed and you build for net7. Is there any hacks we can do to make it work for now?

I don't know of any good/easy ones, there's the obvious rather cumbersome workaround of: install workload 7, build, install workload 8, build, merge the results somehow.

**Comment by jeromelaban** [comment]
> I don't know of any good/easy ones, there's the obvious rather cumbersome workaround of: install workload 7, build, install workload 8, build, merge the results somehow.

This is close to what we're doing in Uno, which is building each target framework in its own job, then use a separate job that bundles all together using a nuspec. It's cumbersome, definitely :)

Somehow related, I wonder, was it considered to build some sorts of a lightweight version of the workloads, with reference assemblies only so that installation would go faster? This would be something to improve  https://github.com/dotnet/sdk/issues/24843.

**Comment by rolfbjarne** [comment]
Current plan: https://github.com/xamarin/xamarin-macios/pull/18523

**Comment by rolfbjarne** [comment]
This has been fixed (https://github.com/xamarin/xamarin-macios/pull/18931), and should be in .NET 8 RC 2.

Contrary to other platforms, library authors will have to be explicit about the target platform version if they want the earliest:

```xml
<TargetFrameworks>net7.0-ios16.0;net7.0-ios16.4;net8.0-ios-17.0</TargetFrameworks>
```

This will create a library for three different iOS versions.

Also note that we won't support all released OS versions, it'll typically be the first release for a given .NET version (which was iOS 16.0 for .NET 7), and the latest (currently iOS 16.4). If Apple releases iOS 16.5, we won't support using `net7.0-ios16.4` anymore when using the latest stable workload.

**Comment by jeromelaban** [comment]
Thanks a lot for the update!

**Comment by rolfbjarne** [comment]
> This has been fixed ([xamarin/xamarin-macios#18931](https://github.com/xamarin/xamarin-macios/pull/18931)), and should be in .NET 8 RC 2.

Unfortunately we ran into some problems, so we had to pull this for .NET 8, and I'm reopening until we can get it in (in a .NET 8 service releae).

**Comment by rolfbjarne** [comment]
I've made another attempt at implementing this, but I'm not entirely sure when we'll be able to release it. At this point it might be released in our Xcode 15.3 release, but it's not certain yet. It's also planned for .NET 9 preview 3, but once again, we might run into trouble and have to back it out until we iron out some more issues.

**Comment by rolfbjarne** [comment]
> I've made another attempt at implementing this, but I'm not entirely sure when we'll be able to release it. At this point it might be released in our Xcode 15.3 release, but it's not certain yet. It's also planned for .NET 9 preview 3, but once again, we might run into trouble and have to back it out until we iron out some more issues.

Nobody found any issues, so it ended up released in .NET 9 preview 3.

This should now work in an iOS library project when using .NET 9 preview 3:

```xml
<TargetFrameworks>net9.0-ios17.2;net8.0-ios17.0</TargetFrameworks>
```

For now, the .NET 9 preview release supports only two OS targets: iOS 17.2 for .NET 9 and iOS 17.0 for .NET 8.

The idea is to eventually support the earliest and latest OS version for each .NET version, so when .NET 9 becomes stable in the fall, that will be iOS 18.0 for .NET 9, and iOS 17.0 + iOS 17.5 (assuming this is the latest iOS 17 minor version at the time) for .NET 8. Then in subsequent versions of .NET 9, we'll always keep iOS 18.0 as supported, while also supporting the latest iOS version as well.

You can also choose a TargetFramework without an OS version, and it will default to the latest. So this is equivalent to the above:


```xml
<TargetFrameworks>net9.0-ios;net8.0-ios17.0</TargetFrameworks>
```

The general recommendation would be:

* Use a specific iOS X.0 OS version if you need the earliest bindings for a given .NET release.
* Use the default (no OS version) if you want the latest bindings.

Please test and let me know if there are any issues!

**Comment by Youssef1313** [comment]
@rolfbjarne I think it would be great if there is a way to opt-in a warning when the specified version isn't supported by the current .NET SDK, e.g, doing `net9.0-ios16.4` is likely unsupported. Would it warn me?

**Comment by rolfbjarne** [comment]
> @rolfbjarne I think it would be great if there is a way to opt-in a warning when the specified version isn't supported by the current .NET SDK, e.g, doing `net9.0-ios16.4` is likely unsupported. Would it warn me?

That will be an error in .NET 9, and (eventually, once the code has been released in a service update) a warning in .NET 8.

**Comment by jeromelaban** [comment]
@rolfbjarne We've validated that this works for us. Thanks for all the fixes!

**Comment by rolfbjarne** [comment]
> @rolfbjarne We've validated that this works for us. Thanks for all the fixes!

That's great, thanks for confirming!
