### ISSUE TITLE
GenerateDepsFile no longer respects FilesToSkip from runtime packs

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#3010]
- Runtime pack dependencies in deps.json and in the DependencyContext model have a "runtimepack." prefix prependend to the nuget package id (see https://github.com/dotnet/sdk/commit/16eddf3d635133c35f42974dcd491c8263066b37#diff-0723634e548f98293eebe3970b71e0ddR328).
- The heuristic in `GetPackageParts` gets the package id from the name of a nuspec in a parent directory:
 https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Common/NuGetUtils.cs#L48-L52

`GenerateDepsFile` uses `GetPackageParts` to build the list of packages with dependencies to remove. When it looks for files to trim from the dependency model, it doesn't match any of the dependencies that have the "runtimepack." prefix, so those files don't get skipped.

**Comment by livarcocc** [comment]
@dsplaisted

**Comment by sbomer** [comment]
Another note:
- The runtime pack asset files get a `DestinationSubPath` that is just the filename: https://github.com/dotnet/sdk/pull/2822/files#diff-197903d15a36fe470248949977e07aa5R49.
- They are given to the DependencyModel with a `"./"` prefix in https://github.com/dotnet/sdk/pull/2822/files#diff-0723634e548f98293eebe3970b71e0ddR370 (this is the behavior of the latest preview).

Together this results in the logic in `GenerateDepsFile.TrimRuntimeFiles` missing the runtime pack assets (even if `GetPackageParts` is fixed): https://github.com/dotnet/sdk/blob/49a6842940a884f2a06860fa9173c2f11963618d/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs#L294

That's the behavior I'm seeing in the latest preview. However, I believe that with https://github.com/dsplaisted/sdk/commit/6aa930689729b966b4fe184d07363f6e36fa1b79, `TrimRuntimeFiles` will correctly match the path of the runtime files even for runtime packs.

Generally I think it's a bit strange that the DependencyModel `RuntimeFile.Path` has a different meaning depending on the "library" type (package vs runtimepack).

**Comment by dsplaisted** [comment]
@sbomer Do you have an example of a failure caused by this?  That would make it a lot easier to write a test case covering this.

**Comment by sbomer** [comment]
@dsplaisted any updates on this? This is important for the linker to be able to trim applications (without any unfortunate workarounds like shipping with a custom replacement for the GenerateDepsFile task).

**Comment by dsplaisted** [comment]
@sbomer I am currently working on this.  I have written test cases that fail due to this bug.
