### ISSUE TITLE
The SDK should error if a FrameworkReference is not supported for a certain TFM

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#3011]
Came up during the design discussion for FrameworkReference + NuGet. 
https://github.com/NuGet/Home/issues/7342

The SDK should error if a FrameworkReference is not supported for a certain TFM. 

* In the project author case, clearly call out that this is an authoring mistake. 
* In the transitive (project/package) case, clearly blame the package/project. 

It's worth considering how we handle bad framework assemblies. 

//cc @nguerrera

**Comment by dsplaisted** [comment]
I believe this is done
