### ISSUE TITLE
dotnet new list ... - searchs project template tags

### ISSUE THREAD

**Issue by bjhogan** [dotnet/sdk#30127]
### Is your feature request related to a problem? Please describe.
The `dotnet new list web` command doesn't list all templates that are tagged with "Web"

Compare the output to `dotnet new list | grep -i web`. Many more templates will be returned. 

This issue affects AWS Lambda templates too. 

`dotnet new list lambda` doesn't return templates tagged with "Lambda" 

I know the command `dotnet new list --tag web` or `dotnet new list --tag lambda` will work. But this is likely a less known command.

### Describe the solution you'd like
`dotnet new list ...` searches Template Name, Short Name **and** Tags.

**Comment by YuliiaKovalova** [comment]
Hi @baronfel,

What is your consideration for this feature?
Thanks!

**Comment by baronfel** [comment]
@bjhogan are you trying to discover new templates, or find local templates that you've already installed?

@YuliiaKovalova we should document what areas of the templates are 'indexed' for local and remote search and (re)consider the fields and weights we're using in that search. This is likely to be highly-variable though based on the installed templates, and we should be careful changing ordering and weight.

**Comment by bjhogan** [comment]
Hi @baronfel, 

I am trying to find templates that are already on my computer. I tend to use VS Code in Linux, so I find templates at the command line using simple searches like - `dotnet new list something`. 

But these simple searches often miss templates because the relevant text is in the Tag, and not the Template Name or Short Name.

**Comment by baronfel** [comment]
Hi @bjhogan - the ordering of results in list is something that we've gone back and forth on several times before. In .NET 5 we had the behavior you suggest, but we got user feedback that the results were so verbose as to be overwhelming. There's definitely some revisions that we could make to the list experience, but we're not prepared to make significant changes at this time without a bit more feedback.  Some things we'll need to consider the next time we take a pass at this is:

* telling users about flags they can use to control their queries
* giving users ways to filter _out_ items from queries
* leaning into an interactive experience to help the users filter through what could be a large list of templates.

**Comment by bjhogan** [comment]
@baronfel. Thanks for the update.
