### ISSUE TITLE
Installing JRE in microsoft/dotnet:sdk container

### ISSUE THREAD

**Issue by saxenark** [dotnet/sdk#3014]
Hi,

I need JRE to run dependencies for my .NET core sdk 2.2 unit tests in Visual Studio 2017. I would like to know how to install JRE into my windows docker container. Through the docker environment, I tried to run java.exe but it does not run.

So, my question is how do I install JRE on my container?

```
FROM microsoft/dotnet:sdk

WORKDIR C:/Temp
COPY jre-8u202-windows-x64.exe ./Java.exe

WORKDIR C:/P4Source

I am using Windows Server 2016 1607 with Docker basic EE

Thanks,

**Comment by livarcocc** [comment]
This is not the right repo for this question.

I would maybe file this in a docker repo or maybe a java repo?
