### ISSUE TITLE
We need a workload team/alias

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#30176]
There should be a workload team in sdk and installer. Many changes to the resolution and install process have made it in to the sdk without effective review from workload authors.  While creating a team won't resolve this issue it may help ensure that the interested parties at least have a chance to familiarize themselves with incoming changes.

**Comment by lewing** [comment]
cc @marcpopMSFT @Redth @jonathanpeppers @rolfbjarne @marek-safar

**Comment by marek-safar** [comment]
I agree and although many problems are mostly technical I think PM involvement should be considered for some of them too.

**Comment by joeloff** [comment]
And it would be useful to help review the Arcade changes around the build tasks too.

**Comment by marcpopMSFT** [comment]
I created @dotnet/net-sdk-workload-contributors Feel free to add folks who should be included.

**Comment by joeloff** [comment]
Shortly after you created it I received a bot notification that it's not being used and should be deleted.
