### ISSUE TITLE
[NETSDKE2E]With .NET 8 SDK installed, the default publish path is "/bin/Release/..." not "/bin/Debug/..." when running "dotnet publish" in CLI

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#30245]
**Repro steps:**

1.Install .NET 8 SDK (8.0.100-preview.2.23081.11) from main branch of https://github.com/dotnet/installer
2.In CLI
dotnet new console -o consoletest
dotnet publish
3. Check publish path

**Expected Result:**
The publish path should be "/bin/**Debug**/..."

In CLI, run "dotnet publish --help", we can see that the default configuration is "Debug" 
![image](https://user-images.githubusercontent.com/65637796/215978181-d88026fd-e5fc-4056-9177-f80e70709690.png)

**Actual Result:**
The publish path is "/bin/**Release**/..."
![image](https://user-images.githubusercontent.com/65637796/215977192-ef937698-1e15-4aae-9a36-4bad562107fe.png)

dotnet --info:
.NET SDK:
 Version:   8.0.100-preview.2.23081.11
 Commit:    440dd9bfc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.2.23081.11\

Host:
  Version:      8.0.0-alpha.1.23080.2
  Architecture: x64
  Commit:       9529803ae2

.NET SDKs installed:
  8.0.100-preview.2.23081.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23079.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23080.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.23078.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by vdanche** [comment]
Also repro for "dotnet pack"
![image](https://user-images.githubusercontent.com/65637796/215984781-202eff01-dacb-419b-8969-3bbd3475be92.png)

**Comment by vdanche** [comment]
Also repro on 8.0.100-preview.1.23081.10

**Comment by nagilson** [comment]
Seems like I should change that string though.

**Comment by vdanche** [comment]
> Seems like I should change that string though. Let me go do that...

You mean the default for --c option should be changed as "Release", right?

**Comment by nagilson** [comment]
Ya, snuck that into this PR https://github.com/dotnet/sdk/pull/30265

**Comment by vdanche** [comment]
The issue has been fixed on 8.0.100-preview.2.23121.12(runtime-8.0.0-preview.2.23116.1)
![image](https://user-images.githubusercontent.com/65637796/220567807-3064d9c0-ad33-4731-b5c2-551007ecba68.png)
