### ISSUE TITLE
Microsoft.AspNetCore.Watch.BrowserRefresh causes Microsoft.NETCore.App.Ref 6.0 prebuilts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#30272]
The Microsoft.AspNetCore.Watch.BrowserRefresh's [net6.0 TFM](https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj#L4) is causing Microsoft.NETCore.App.Ref and Microsoft.AspNetCore.App.Ref source-build prebuilts in .NET 8.0.

.NET 8.0 source-build only produces the .NET8.0 targeting pack.  All projects must reference a net standard or the net current TFM.

I am not familiar with this tool.  Can someone help me understand why this needs to be pinned to the older supported net tfm?

cc @mmitche, @pranavkm

**Comment by MichaelSimons** [comment]
Friendly ping.

**Comment by pranavkm** [comment]
> Can someone help me understand why this needs to be pinned to the older supported net tfm?

The binary is injected into arbitrary .NET Core projects as a startup assembly. Since the SDK is backwards compatible with runtime versions, the assembly's TFM was pinned to .NET 6, the earlier version that supports this feature. Perhaps a workaround is to unpin the tfm during source build?

**Comment by mmitche** [comment]
@pranavkm If we unpinned this during source build, does that mean that downlevel targeting in RH built SDKs would no longer be supported (in cases where this feature would be used?)

**Comment by mmitche** [comment]
> @pranavkm If we unpinned this during source build, does that mean that downlevel targeting in RH built SDKs would no longer be supported (in cases where this feature would be used?)

@pranavkm Any comments on this?

**Comment by MichaelSimons** [comment]
Gentle ping - this is affecting source-build prebuilts and I would like to see this resolved.

**Comment by mmitche** [comment]
@mkArtakMSFT @MackinnonBuck In case they have any input here.

**Comment by MichaelSimons** [comment]
@captainsafia - Do you have any input on this?  TIA

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck assigning this to you to have a look at after you're back next week.

**Comment by MichaelSimons** [comment]
Is there an expected timeframe on when this will be fixed?  Source-build is carrying a patch to workaround this which will need to be removed prior to 8.0 GA.
