### ISSUE TITLE
Duplicate "_PackageReferenceToAdd" item name breaks builds in VS

### ISSUE THREAD

**Issue by davidwengier** [dotnet/sdk#3027]
Looks like this was introduced here:
https://github.com/dotnet/sdk/commit/63d7cdec5041a9a97b002b1e81d3d1f835cad871

`_PackageReferenceToAdd` is used twice.
It's used in: https://github.com/dotnet/sdk/blob/afae0615d5cbb16c058c5ce1fd65215d07df24d9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.TargetingPackResolution.targets#L124

and:

https://github.com/dotnet/sdk/blob/f217153b0a1624a012041a4de375faf76ddfdc07/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L278

This is breaking the https://github.com/dotnet/project-system build in VS for me (we have duplicate nuget references)

**Comment by nguerrera** [comment]
Can you share a binlog. We need to fix the collision, but staring at this, it's hard to see how the second remove doesn't cancel out the first add.

Do you have a package reference include of an implicit package ref? Removing that might be a workaround.

**Comment by nguerrera** [comment]
Nevermind, the second one doesn't have a remove. Editing previous comment.

**Comment by davidwengier** [comment]
> Removing that might be a workaround.

We had a few duplicate references, and removing the duplicates does work around the issue.

I'll send you the binlog on Teams, it has one env var that I'm not sure is 100% okay to share :)

**Comment by davidwengier** [comment]
Binlog linked above (in case you didn't see the notification)

**Comment by davkean** [comment]
Ran into it here: https://twitter.com/scottisafool/status/1130750989705912321.
