### ISSUE TITLE
[Questions] How to know the latest installed dotnet sdk version on a non sdk style project file like .vcxproj

### ISSUE THREAD

**Issue by anchurcn** [dotnet/sdk#30289]
I want to include the nethost.h file in the dotnet distribution path.
If I get the latest dotnet sdk version, I can get Microsoft.NETCoreSdk.BundledVersion.props, and the info about navigating to nethost.h is define there.

A more question: Can msbuild get registry data easy? Must I implement a custom `ITask`? 

Thanks.

**Comment by anchurcn** [comment]
@KalleOlaviNiemitalo And do you know how to run a console app and assign the console output to a property? I want to define a property in project file with value of cmd 'dotnet --version'.

**Comment by anchurcn** [comment]
@KalleOlaviNiemitalo Is it possible to execute target/task on Visual Studio load?

**Comment by baronfel** [comment]
Closing as @KalleOlaviNiemitalo has answered the questions. Thank you again, @KalleOlaviNiemitalo!
