### ISSUE TITLE
Ability to produce universal macos binaries (x64+arm)

### ISSUE THREAD

**Issue by hellozyemlya** [dotnet/sdk#30342]
### Is your feature request related to a problem? Please describe.
Mac os support universal binaries, that contains native code for arm64 and x64 architectures in single binary.
It will be great if dotnet publish will be able to produce such self-contained binaries.

### Describe the solution you'd like
Add osx universal runtime identifier?

**Comment by nagilson** [comment]
There already is an `osx` runtime identifier which is a generic OSX runtime. There is also the `any` runtime that you can specify. Do either of these meet your conditions and if not, why?
