### ISSUE TITLE
`dotnet test` CLI accepts neither SOLUTION nor PROJECT arguments anymore

### ISSUE THREAD

**Issue by oliverzick** [dotnet/sdk#30368]
### Describe the bug
Since change [https://github.com/dotnet/sdk/commit/cdd5f3b9465e07babb6c1ba54e4d8887c7b9c28b](https://github.com/dotnet/sdk/commit/cdd5f3b9465e07babb6c1ba54e4d8887c7b9c28b) the `dotnet test` CLI does not support any `SOLUTION` or `PROJECT` passed as argument.

In the change the following is mentioned:

```
// We are on purpose not capturing the solution, project or directory here. We want to pass it to the
// MSBuild command so we are letting it flow.
```

### To Reproduce
Take any repository that can be tested with `dotnet test` and try to run `dotnet test` CLI by passing `SOLUTION` or `PROJECT` like

```
dotnet test <PathToSolutionFile.sln>
```

You will receive a message that `SOLUTION` or `PROJECT` argument cannot be recognized.

### Further technical details
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

**Comment by IT-VBFK** [comment]
https://github.com/dotnet/sdk/issues/29543#issuecomment-1379499334

**Comment by nagilson** [comment]
This should be fixed in 7.0.103, update this month when available. Report back if it still happens. And thanks @IT-VBFK for sharing that this is a duplicate.

**Comment by baronfel** [comment]
It's available now!

**Comment by oliverzick** [comment]
Thanks, haven't seen the already existing bug report because I have only searched for dotnet test together with solution.
