### ISSUE TITLE
TargetFramework is (incorrectly) passed to its dependencies

### ISSUE THREAD

**Issue by jgoshi** [dotnet/sdk#304]
The following branch contains the repro:
https://github.com/dotnet/cli/tree/dev/jgoshi/switchToCsproj

If you try to run:
dotnet restore3 Microsoft.DotNet.Cli.Utils.csproj
dotnet build3 Microsoft.DotNet.Cli.Utils.csproj

It fails because Microsoft.DotNet.Cli.Utils is built with netstandard1.5 but its dependent project Microsoft.DotNet.ProjectModel is supposed to be built with netstandard1.3 (and TargetFramework is incorrectly passed as netstandard1.5).

**Comment by nguerrera** [comment]
Investiagating now

**Comment by nguerrera** [comment]
It looks like you're using an old version of the SDK. The repro is pulling down 1.0.0-alpha-20161012-3, which is a week old and doesn't have this fix: https://github.com/dotnet/sdk/pull/260
