### ISSUE TITLE
I have c# please send me solution

### ISSUE THREAD

**Issue by Bomb12206** [dotnet/sdk#30445]
PS C:\Users\Admin\Documents\project> cd "c:\Users\Admin\Documents\project\"; dotnet run CR7.cs
C:\Users\Admin\Documents\project\Program.cs(8,9): error CS1519: Invalid token '{' in clas
s, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\proj 
ect.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,30): error CS1519: Invalid token '(' in cla
ss, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\pro 
ject.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1031: Type expected [C:\Users\ 
Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS8124: Tuple must contain at le 
in\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1519: Invalid token '"Hello Wo 
rld!"' in class, record, struct, or interface member declaration [C:\Users\Admin\Document 
s\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(12,1): error CS1022: Type or namespace defini 
tion, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\tempCodeRunnerFile.cs(1,1): error CS1022: Type or namesp 
ace definition, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj] 

The build failed. Fix the build errors and run again.
PS C:\Users\Admin\Documents\project> cd "c:\Users\Admin\Documents\project\"; dotnet run CR7.cs
C:\Users\Admin\Documents\project\Program.cs(8,9): error CS1519: Invalid token '{' in clas
s, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\proj 
ect.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,30): error CS1519: Invalid token '(' in cla
ss, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\pro 
ject.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1031: Type expected [C:\Users\ 
Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS8124: Tuple must contain at le 
in\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1519: Invalid token '"Hello Wo 
rld!"' in class, record, struct, or interface member declaration [C:\Users\Admin\Document 
s\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(12,1): error CS1022: Type or namespace defini 
tion, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\tempCodeRunnerFile.cs(1,1): error CS1022: Type or namesp 
ace definition, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj] 

The build failed. Fix the build errors and run again.
PS C:\Users\Admin\Documents\project> cd "c:\Users\Admin\Documents\project\"; dotnet run CR7.cs
C:\Users\Admin\Documents\project\tempCodeRunnerFile.cs(1,1): error CS1022: Type or namesp
ace definition, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj] 
C:\Users\Admin\Documents\project\Program.cs(8,9): error CS1519: Invalid token '{' in clas
s, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\proj 
ect.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,30): error CS1519: Invalid token '(' in cla 
ss, record, struct, or interface member declaration [C:\Users\Admin\Documents\project\pro 
ject.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1031: Type expected [C:\Users\ 
Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS8124: Tuple must contain at le 
ast two elements. [C:\Users\Admin\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1026: ) expected [C:\Users\Adm 
in\Documents\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(9,31): error CS1519: Invalid token '"Hello Wo 
rld!"' in class, record, struct, or interface member declaration [C:\Users\Admin\Document 
s\project\project.csproj]
C:\Users\Admin\Documents\project\Program.cs(12,1): error CS1022: Type or namespace defini 
tion, or end-of-file expected [C:\Users\Admin\Documents\project\project.csproj]

The build failed. Fix the build errors and run again. this is error

**Comment by marcpopMSFT** [comment]
Can you share the source for your application?  Seems likely a typo somewhere in there that has created a malformed c# file.

**Comment by toverbay** [comment]
I've seen these errors before. It's not recognizing file-scoped namespaces, top-level statements, or simplified using statements. You're probably not targeting the right framework or language version.

**Comment by marcpopMSFT** [comment]
See the suggestion above and reopen if you have more details to share.
