### ISSUE TITLE
dotnet tools occasionally hang 

### ISSUE THREAD

**Issue by akindle** [dotnet/sdk#30455]
### Describe the bug
Running normal dotnet commands (e.g. `dotnet add package Newtonsoft.Json`) occasionally hangs indefinitely at a random point in execution. `.NET Host` is left as an idle subprocess and cannot be killed except by closing the parent process.

![image](https://user-images.githubusercontent.com/2405627/217663663-f77d92dc-a02f-43f1-8e45-00032684d624.png)
![image](https://user-images.githubusercontent.com/2405627/217663704-cd382092-9be4-41b6-8e9e-57e28051c9af.png)

### To Reproduce
This is likely specific to something about my environment, but I am struggling mightily to narrow it down. Situations where I have encountered it:

* Running from Windows Terminal
* Running from Powershell 7
* Running from Powershell 5
* Running from VS Code integrated terminal

I recognize that under the hood several of these are the same execution environment.

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  5.0.414 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by marcpopMSFT** [comment]
Are there specific commands that are hanging or is it any dotnet command? In this case, you did a dotnet add package and it appears to be stuck in the restore after having added the package. Do you know if the restore actually finished and it's something after the restore?  Is it only operations that trigger a restore (and thereby trigger a call to your network) that are potentially hanging?  I'm wondering if it's network or related to one of your feeds.

**Comment by marcpopMSFT** [comment]
We don't have diagnostics within the SDK itself to know where it's getting stuck. You could try /v:diag to see if the verbose logging gives more clues as to where it stopped.  CC @baronfel for any ideas.

**Comment by baronfel** [comment]
My initial response would be to get a dump from the hung process (you can do this by right-clicking on the .NET Host entry in your screenshots) and then open that dump in [PerfView](https://github.com/microsoft/perfview) - that should give you a stack trace of all the threads - if you could provide that data here it might help us figure out what's going on.

**Comment by marcpopMSFT** [comment]
If this is still happening and you can get a dump of the hang, please send it our way. We can reactivate the issue then.

**Comment by rubin55** [comment]
I think I'm experiencing the same issue, exact same symptoms; dotnet hangs with most/various sub-commands. I made a core dump:

**Comment by vgarousi** [comment]
I have the same issue today. I am running test automation in VSCode using this plug-in: https://github.com/getgauge/gauge-vscode

It used to work with no issues since the last 1.5 years, and only today, the .Net is getting stuck. So annoying!

![image](https://github.com/dotnet/sdk/assets/25739397/a5d08958-7567-4592-8824-44fe66700e25)
