### ISSUE TITLE
ClickOnce EV code sign with USB HSM - This certificate does not contain a private key

### ISSUE THREAD

**Issue by RhomGit** [dotnet/sdk#30534]
### Describe the bug
I am manually signing application manifest via mage.exe or mageui.exe.
I have an EVCS from a CA issued on a USB HSM (Yubikey).
signtool.exe has signed the executable correctly using the HSM.
mage.exe is reporting "This certificate does not contain a private key"
mageui.exe is asking for a Certificate file which I don't have.
![image](https://user-images.githubusercontent.com/25700833/218288126-586bdad6-e54f-4b1d-9a20-fd000d7cffc2.png)

### To Reproduce
```
Try and sign a manifest file using a USB HSM.
.\mage.exe -Sign "C:\my_app.exe.manifest" -csp "Microsoft Smart Card Key Storage Provider" -kc "9b5…" -CertHash "c15…"
```

### Exceptions (if any)
 "This certificate does not contain a private key"

### Further technical details
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools> 
This might be relevant also: https://github.com/dotnet/sdk/issues/26170

**Comment by RhomGit** [comment]
People reverse engineering mage.exe to get this to work?!
- https://stackoverflow.com/questions/54752638/mage-exe-manifest-signing-with-certificate-stored-in-aws-cloudhsm
- https://github.com/Microsoft/dotnet/issues/986

**Comment by RhomGit** [comment]
Another reference to a person experiencing this bug:
https://stackoverflow.com/questions/73592672/singing-clickonce-application-with-ev-code-siging

**Comment by joeloff** [comment]
Hi @RhomGit 

The SDK repo is only tracking .NET issues, not .NET Framework. .NET Framework SDK related issues should be filed using a VS feedback ticket. Could you please open a new ticket [here](https://developercommunity.visualstudio.com/dotnet/report) as that is used to track .NET Framework issues.

My understanding is that not all USB stores are fully supported by Mage.

@Tanya-Solyanik as an FYI.

**Comment by RhomGit** [comment]
@joeloff @Tanya-Solyanik Thanks and apologies for filing here, 
For anyone else following this trail, the issue has been re-filed here: https://developercommunity.visualstudio.com/t/ClickOnce-EV-Signing-with-HSM/10278648
