### ISSUE TITLE
[NETSDKE2E][Regression]With VS 17.6 preview 1 + NET8 preview 1 SDK installed, Maui template is missing.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#30576]
Repro steps:

1.Install .NET 8 SDK ( 8.0.100-preview.1.23108.10) from [Pipelines - Run 20230213.2-8.0.100-preview.1.23112.5-166715 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2112520&view=artifacts&pathAsName=false&type=publishedArtifacts) + VS 17.6 preview 1 [Pipelines - Run rel.d17.6-33414.285 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D7332141%26view%3Dresults&data=05%7C01%7Cv-danche%40microsoft.com%7C9b2d94f17b2841a1e8bf08db0ee98b50%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638120168763106836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o16RJnqNH3CV4KtyOL6I71fFWz6Mw1%2FZ6PQ%2FuDnZet4%3D&reserved=0) with ".NET multi platform App UI development" workload installed.
2. In VS, Check if maui project can be displayed on Create a new project.
3. in CLI, run "dotnet new list" to check if Maui template can be displayed.

Expected Result:
In VS and CLI, Maui template canbe displayed.

Actual Result:
Maui template is missing.
In VS, ![image](https://user-images.githubusercontent.com/65637796/218943517-bdd675f9-0a8c-4083-8c12-33fdd02a2f69.png)

In CLI,
![image](https://user-images.githubusercontent.com/65637796/218629930-17cf7930-2b9f-4967-8a02-3eb437f1e242.png)

Note:
**Only install VS 17.6 preview 1, Maui template can be displayed well.**
![image](https://user-images.githubusercontent.com/65637796/218944163-0d82e5a1-71ee-411a-8978-8e6d07199414.png)

dotnet --info:
.NET SDK:
 Version:   8.0.100-preview.1.23112.5
 Commit:    938fd76cc6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.1.23112.5\

Host:
  Version:      8.0.0-preview.1.23110.8
  Architecture: x64
  Commit:       7deac7d6da

.NET SDKs installed:
  7.0.200 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.1.23112.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.1.23112.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23110.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.1.23112.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by vdanche** [comment]
Not repro on yesterday's build from [Run 20230209.1-8.0.100-preview.1.23108.10-166172 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2109269&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by WenJunJi01** [comment]
Also repro on win arm64 with the same build installed.

**Comment by jonathanpeppers** [comment]
For the repro steps:

![image](https://user-images.githubusercontent.com/840039/218805719-91442d22-94de-4e51-8243-1f3ddeb0a43a.png)

Wouldn't you need to install the `maui` workload?

**Comment by Gitty-3ps** [comment]
1. Added an appropriate global.json to my project `dotnet new globaljson --sdk-version 7.0.102`
2. Installed .Net Maui Templates `dotnet new install Microsoft.Maui.Templates`
3. I installed .Net 8 
4. Did `dotnet workload install maui` and got sdk not found or installed errors.
5. Then I tried `dotnet maui update` and now I have no errors. 
_Hope this works._

**Comment by vdanche** [comment]
> 1. Added an appropriate global.json to my project `dotnet new globaljson --sdk-version 7.0.102`
> 2. Installed .Net Maui Templates `dotnet new install Microsoft.Maui.Templates`
> 3. I installed .Net 8
> 4. Did `dotnet workload install maui` and got sdk not found or installed errors.
> 5. Then I tried `dotnet maui update` and now I have no errors.
>    _Hope this works._

Sorry for my incorrect repro steps. Maui template missing happens on VS 17.6 preview 1 [Pipelines - Run rel.d17.6-33414.285 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D7332141%26view%3Dresults&data=05%7C01%7Cv-danche%40microsoft.com%7C9b2d94f17b2841a1e8bf08db0ee98b50%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638120168763106836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o16RJnqNH3CV4KtyOL6I71fFWz6Mw1%2FZ6PQ%2FuDnZet4%3D&reserved=0) + [Pipelines - Run 20230213.2-8.0.100-preview.1.23112.5-166715 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2112520&view=artifacts&pathAsName=false&type=publishedArtifacts)
![image](https://user-images.githubusercontent.com/65637796/218942294-9290cbe1-b607-4844-ace6-258fce7f30c1.png)


![image](https://user-images.githubusercontent.com/65637796/218942390-53366ab4-7a9c-4dd7-8a10-e7b504ec2589.png)

Note:
Not happens on VS 17.6 preview 1 [Pipelines - Run rel.d17.6-33414.285 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D7332141%26view%3Dresults&data=05%7C01%7Cv-danche%40microsoft.com%7C9b2d94f17b2841a1e8bf08db0ee98b50%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638120168763106836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o16RJnqNH3CV4KtyOL6I71fFWz6Mw1%2FZ6PQ%2FuDnZet4%3D&reserved=0) + previous net 8 preview 1 sdk [Run 20230209.1-8.0.100-preview.1.23108.10-166172 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2109269&view=artifacts&pathAsName=false&type=publishedArtifacts)

![image](https://user-images.githubusercontent.com/65637796/218942907-e094cb24-d3d2-4684-9bb7-267ab4230d0e.png)

**Comment by jonathanpeppers** [comment]
@vdanche what do I install to repro this? VS 17.6 and then a .NET 8 preview "standalone SDK" on top?

I think only the following would work:

1. Any version of VS - installs .NET 7 and the .NET 7 MAUI workloads
2. Install a .NET 8 standalone SDK
3. Run `dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json --verbosity diag`

(Or if you have other `dotnet workload` instructions, use those)

Otherwise, you have a .NET 8 SDK and no .NET 8 MAUI installed. We don't have .NET 8 MAUI in Visual Studio yet.

A reason this could break with a newer .NET 8 SDK, because it now knows about the .NET 8 MAUI workload. Previously, it was still using the .NET 7 MAUI workload.

**Comment by richaverma1** [comment]
@jonathanpeppers I think what Dan means is that when VS 17.6 is installed, Maui templates show up in VS create new project dialog. Then, install .NET 8 Preview 1 standalone SDK and those templates disappear. Is this expected?

**Comment by jonathanpeppers** [comment]
I think it works for me:

![image](https://user-images.githubusercontent.com/840039/219176616-a5f6b6a4-0055-400a-bf88-c94ded8cfa88.png)

![image](https://user-images.githubusercontent.com/840039/219176853-ff2b929b-2dd3-4bcf-8da8-384add355629.png)

But I followed these steps:

https://gist.github.com/jonathanpeppers/99961b4639823206c2537c03c856b097

(I will try a newer .NET SDK to see if that changes anything)

**Comment by richaverma1** [comment]
@jonathanpeppers did you also install Maui workload through CLI? The repro steps are install VS with ".NET multi platform App UI development" workload, then install .NET 8 Preview 1 SDK. There is no workload install through CLI.

**Comment by jonathanpeppers** [comment]
Yes, I don't see how it would work unless you run at least some `dotnet workload` command at the CLI. VS will pick up the .NET 8 SDK, and won't have MAUI installed.

@marcpopMSFT is there anything I'm missing here? Thanks.

**Comment by marcpopMSFT** [comment]
I assume the original install of VS had the maui VS workloads checked. installing any .NET SDK stand-alone on top of VS will likely have similar behavior (if there is a mismatch in baseline manifests) but it's especially true going across feature bands. So this is expected behavior at the moment as once you install .net 8 SDK, you use that SDK and it's workloads which aren't installed yet.

**Comment by vdanche** [comment]
As it's expected behavior, hence close it.
