### ISSUE TITLE
DOTNET CLI - dotnet test --Filter throws unknown switch error, filter options currently appears to be case sensitive

### ISSUE THREAD

**Issue by manoj-choudhari-git** [dotnet/sdk#30629]
The command given below throws an error.  But if we type "filter" instead of "Filter" it works. 

`dotnet test --Filter FullyQualifiedName~SomeText`

`DOTNET `vs `dotnet `yields same result on command prompt.   But DOTNET -H does not work because filters appear to be case sensitive as shown in snapshot given below.

I assume it is not a bug probably, but commands are supposed to be case insensitive for convenience.  Thoughts ?

![image](https://user-images.githubusercontent.com/46196232/219035270-83caeb54-c30b-4286-82ab-09e13dab626e.png)

**Comment by baronfel** [comment]
Options are case sensitive in the .Net CLI, we mostly try to follow POSIX conventions in that regard. it's only in PowerShell that case insensitivity is common.
