### ISSUE TITLE
[GenAPI] Add unsafe keyword if the calls of the base constructor is unsafe 

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#30640]
The CCI based Roslyn handled this case: https://github.com/dotnet/arcade/blob/638dca732fd9f09fe9c0a2d6b02e9417d961e662/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Methods.cs#L384-L387

We should support this in Roslyn's GenAPI. Blocked on https://github.com/dotnet/arcade/issues/12578 to be fixed as it will make implementing this change easier.

**Comment by andriipatsula** [comment]
The use case

```C#
public class Bar
{
    public unsafe Bar(char* f) { }
}

public class Foo : Bar
{
    public unsafe Foo(char* f) : base(f) { }
}
```

works well:

```C#
public partial class Bar
{
    public unsafe Bar(char* f) { }
}

public partial class Foo : Bar
{
    public unsafe Foo(char* f) : base(default) { }
}
```

**Comment by ViktorHofer** [comment]
Nice so I guess we can close the issues then. Thanks for double checking.

**Comment by andriipatsula** [comment]
Ok. Found a scenario, when the current logic fails:

```C#
public class Bar
{
    public unsafe Bar(char* f) { }
}

public class Foo : Bar
{
/// unsafe in not generated here as a result compilation error.
    public unsafe Foo() : base(default) { }
}
```

Will fix today and write couple of tests.
