### ISSUE TITLE
Workload experience for out-of-tree workloads poor, especially on upgrades

### ISSUE THREAD

**Issue by directhex** [dotnet/sdk#30661]
On Monday, I installed the Tizen workload on my desktop via the Visual Studio Code Tizen extension. This works by dropping a `samsung.net.sdk.tizen/` folder in `/usr/share/dotnet/sdk-manifests/7.0.100/` to define the existence of the `tizen` workload, then installing that workload via `dotnet workload install`.

Today, I went through routine package updates on my system. And now a) the workload has vanished from `dotnet workload search` and `dotnet workload list`, and b) it is no longer available via `dotnet workload install`

It's gone, because https://github.com/dotnet/sdk/blob/main/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs#L19-L20 uses a hardcoded list of permitted "out of date" manifests - and manifests we aren't bundling ourselves aren't in the list. So whilst everything still exists on disk (`/usr/share/dotnet/metadata/workloads/7.0.100/InstalledWorkloads/tizen` and friends), it's effectively orphaned unless I manually move files around on disk to corresponding 7.0.200 folders.

Clearly we have a process breakdown here for how third parties are supposed to distribute workloads, resulting in a pretty awful user experience full of surprises. This is an edge case which the outdated-manifest code wasn't intended to cope with.

Like it or not, third party runtimes are a thing users need, and workloads are the most sane way to ingest them - meaning we need an improved story for how to ingest them without orphaning them between releases the way we did in 7.0.100->7.0.200. I have a few more examples I can discuss on Teams if needed.

**Comment by marcpopMSFT** [comment]
7.0.4xx will ship with improved upgrade support for the Tizen workload in particular. We do not have official support for 3rd party workloads and Tizen is working as expected here. Since Tizen went through the official process to require support for their TFM with NuGet, we got approval to add their workload to the KnownWorkloadManifest list.
