### ISSUE TITLE
dotnet SDK 6.0.405 and 406 still requires dependencies after installing SDK+runtime in CBL-Mariner

### ISSUE THREAD

**Issue by jackj-msft** [dotnet/sdk#30694]
### Describe the bug
`dotnet` still requires additional dependencies to be downloaded when performing `restore`

### To Reproduce

1. Install dotnet SDK 6.0.405 and the associated runtime 6.0.13
2. Create a nuget.config and clearing out all the NuGet feeds
3. Use `dotnet new console` to create a new C# project and restore it (it should automatically do this)

Expected:
4. The restore succeeds as this new project does not have any dependencies.

### Exceptions (if any)

```
Determining projects to restore...
/root/Overlake/Scripts/testapp/testapp.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Ref (= 6.0.14)' for 'net6.0'.
/root/Overlake/Scripts/testapp/testapp.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Ref (= 6.0.14)' for 'net6.0'.
/root/Overlake/Scripts/testapp/testapp.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Host.linux-x64 (= 6.0.14)' for 'net6.0'.
```

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.406
 Commit:    2988897946

Runtime Environment:
 OS Name:     mariner
 OS Version:  2.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.406/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by marcpopMSFT** [comment]
Not sure how you acquired the SDK but you got 6.0.406 which assumes 6.0.14. Those packages should be fetchable from nuget.org if not available locally though. Can you confirm your nuget.config settings include nuget.org or install the matching 6.0.14 runtime?

**Comment by jackj-msft** [comment]
I'm building a container with the dotnet SDK installed and running a dotnet build inside the container without network.
Does the dotnet SDK installation not include all necessary dependencies?

I was installing the dotnet SDK from TDNF.
http://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/aarch64/Packages/d/

However, I take my comment back about version 406
After I reinstalled the SDK it successfully built the project.

I will reopen this issue if I see this problem again in the future.
