### ISSUE TITLE
ASP.NET MVC - view component fails to render via vc tag helper when build with .NET SDK 7.0.200

### ISSUE THREAD

**Issue by VasiliyNovikov** [dotnet/sdk#30703]
When adding a view component via "vc" tag helper to the view it stops working when it is built with .NET SDK 7.0.200 while it still works on the same runtime (7.0.3) but when it is built with .NET SDK 7.0.103

Here is sample code that reproduces the issue: https://github.com/VasiliyNovikov/ViewComponentBug
I tried to build it and run it on Windows 11 & Ubuntu Linux 18 with .NET SDK 7.0.103 and .NET SDK 7.0.200 with Kestrel http server

**Comment by recumbented** [comment]
May be same issue:
ViewComponents called with the vc taghelper are broken on 7.0.3
 https://github.com/dotnet/razor/issues/8281

**Comment by VasiliyNovikov** [comment]
It sounds like the same issue

**Comment by baronfel** [comment]
@VasiliyNovikov .NET Runtime 7.0.4 is out now which should have solved your issue. Can you take a look and let me know?

**Comment by VasiliyNovikov** [comment]
@baronfel , yes - it fixes the issue. Thanks!
