### ISSUE TITLE
What is the difference between dotnet SDK 7.0.103 and dotnet SDK 7.0.200

### ISSUE THREAD

**Issue by VAllens** [dotnet/sdk#30727]
What is the difference between dotnet SDK `7.0.103` and dotnet SDK `7.0.200` ?
Is dotnet SDK `7.0.103` the correct version ?

![image](https://user-images.githubusercontent.com/5094922/219988328-383c6b67-8651-429a-831d-0025b45bf8cc.png)

**Comment by baronfel** [comment]
We've got some docs about this [here](https://learn.microsoft.com/en-us/dotnet/core/versions/), can you check that out and see if it answers your question?

**Comment by VAllens** [comment]
@baronfel 
Thank you. 👍 💯 
It's useful to me. It solved my question.
![image](https://user-images.githubusercontent.com/5094922/221459457-30a250d3-c21b-41d7-8f8a-b64392c50eef.png)
