### ISSUE TITLE
Build fails when using sdk version 7.0.100.

### ISSUE THREAD

**Issue by v-mikedu** [dotnet/sdk#30735]
Repro steps:

1. Install 7.0.100 SDK from: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.100-macos-x64-installer
2. Run the following command in Terminal: 
mkdir Razor
cd Razor
dotnet new sln
mkdir Razor70
cd Razor70
dotnet new razor
cd ..
dotnet sln add Razor70/Razor70.csproj
dotnet build "Razor.sln" -c Release -o /app/build --no-restore

Expected Result:
Solutions can be successfully built.

Actual Result:
Some warnings and errors appear when building solution.
![image](https://user-images.githubusercontent.com/85597901/220281328-191290a2-ecbe-430f-89bc-1da884148c5d.png)

dotnet --info:

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/
Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4
.NET SDKs installed:
  7.0.100 [/usr/local/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Other architectures found: None
Environment variables: Not set
global.json file: Not foun
Learn more: https://aka.ms/dotnet/info
Download .NET: https://aka.ms/dotnet/download

**Comment by dsplaisted** [comment]
Some questions:

- Do you have access to `/app/build`?
- Does this fail if you build the project with an output path instead of the solution?
- Does this fail in 7.0.100?
- Can you attach a [binlog](https://aka.ms/binlog) of the failure?

Thanks

**Comment by dsplaisted** [comment]
The error message says "read-only file system", so I think the issue is that you don't have write access to the output folder, and isn't related to this version of the .NET SDK.

**Comment by v-mikedu** [comment]
Here's information about the error. [errorinfo.docx](https://github.com/dotnet/sdk/files/10788800/errorinfo.docx)

**Comment by v-mikedu** [comment]
- I tried to enter the path: "/app/build/Mvc.staticwebassets.runtime.json", but I didn't seem to have permission to enter. Here's information about path:[accessinfo.rtfd.zip](https://github.com/dotnet/sdk/files/10788914/accessinfo.rtfd.zip)

- I tried running the command: "dotnet build -c Release -o /app/build --no-restore" still reproduces the issue.

- Also fails in sdk 7.0.100, reproducing this issue.

**Comment by v-qushi** [comment]
@dsplaisted 
I tried to get binlog according to the document [binlog](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) you provided, but I'm not able to figure out exactly how to do it.

For this issue, I tried to use other path as the output path, such as ‘/users/XXX’, build can succeed.
![Build](https://user-images.githubusercontent.com/63572730/220306786-4141a18a-484c-4e8f-8f59-f76f838b54a5.PNG)

The reason I use /app/build as the output path is because I'm just trying to reproduce the original bug #30625.

**Comment by dsplaisted** [comment]
To create a binlog, you just add the `-bl` parameter to the MSBuild command line, and it will create a file called msbuild.binlog.

I imagine the machine environment for the original repro was different somehow, and `/app/build` was write-accessible.
