### ISSUE TITLE
Dotnet format fails with EnforceCodeStyleInBuild enabled in 7.0.200

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dotnet/sdk#30742]
### Describe the bug
When running `dotnet format` with .NET SDK 7.0.200 and [EnforceCodeStyleInBuild](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild), I get an error of Microsoft.CodeAnalysis 4.5.0.0 not being found. This works however on .NET SDK 7.0.103. It looks like the version of the Microsoft.CodeAnalysis within dotnet-format is incorrect (shipped with 4.4.0 while the SDK is expected 4.5.0), and additionally 4.5.0 is yet to be released on nuget. 

###  To Reproduce

A new project with the csproj modified to have the property `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>`. Here is a sample:

[CodeAnalysisBug.zip](https://github.com/dotnet/sdk/files/10788081/CodeAnalysisBug.zip)

### Exceptions (if any)

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.CodeAnalysis.DefaultAnalyzerAssemblyLoader.DirectoryLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

### Further technical details
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.103 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

**Comment by brminnick** [comment]
The fix is to install the [`Microsoft.CodeAnalysis.CSharp` NuGet Package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/) to v4.5.0.0.

However, the Roslyn team hasn't yet published Microsoft.CodeAnalysis.CSharp v4.5.0.0.

Is there a timeline for how soon v4.5.0.0 will be published to NuGet? This is a blocker for libraries that use Source Generators. 

My team, the [.NET MAUI Community Toolkit team](https://github.com/Communitytoolkit.Maui.Markup) cannot merge any PRs and publish any new releases until v4.5.0.0 is released.

**Comment by BenjaminMichaelis** [comment]
> The fix is to install the NuGet Package [`Microsoft.CodeAnalysis.CSharp` v4.5.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/).
> 
> However, the Roslyn team hasn't yet published Microsoft.CodeAnalysis.CSharp v4.5.0.0.
> 
> Is there a timeline for how soon v4.5.0.0 will be published to NuGet? This is a blocker for libraries that use Source Generators.
> 
> My team, the [.NET MAUI Community Toolkit team](https://github.com/Communitytoolkit.Maui.Markup) cannot merge any PRs and publish any new releases until v4.5.0.0 is released.

The other fix if it is possible for any project you work on is to pin the sdk to 7.0.103 in the global.json and disable rollForward which is the approach I have taken on a few of my projects for the time being till this gets fixed.

**Comment by genlu** [comment]
Roslyn [4.5.0 packages](https://www.nuget.org/packages/Microsoft.CodeAnalysis) are published today. Apologized for the delay.

**Comment by hennys** [comment]
> The fix is to install the NuGet Package [`Microsoft.CodeAnalysis.CSharp` v4.5.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/).

Did this solve the issue for you? I'm having the exact same issue, but was unable to resolve it by installing the `Microsoft.CodeAnalysis.CSharp` v4.5.0 package as suggested. The only solution so far has been to pin the SDK to 7.0.103.

**Comment by pziezio** [comment]
> Did this solve the issue for you? I'm having the exact same issue, but was unable to resolve it by installing the `Microsoft.CodeAnalysis.CSharp` v4.5.0 package as suggested. The only solution so far has been to pin the SDK to 7.0.103.

I'm also stuck at 7.0.103 at the moment. Installing [Microsoft.CodeAnalysis.CSharp v4.5.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/) in every project is not a valid solution. At 7.0.103 dotnet format works without that.

**Comment by herebebeasties** [comment]
See:
 * dotnet/format#1782
 * dotnet/format#1800

**Comment by BenjaminMichaelis** [comment]
Looks resolved as of 12/14/2023
