### ISSUE TITLE
Pound Sign/Hashtag in Response File Breaks Deployments

### ISSUE THREAD

**Issue by coridn** [dotnet/sdk#30759]
I'm using TeamCity to perform a publish of an application to IIS.

The password is set up in TeamCity as a system parameter, which gets passed to dotnet publish through a response file.

I've checked the response file, and it has the entry:
-p:Password=Password123#

When I check the diagnostic logs to see why my command keeps failing, I see that the password when passed to the command line is missing the #.

After quite a lot of digging, I've found the culprit.

https://github.com/dotnet/sdk/blob/1c3c95edfbd68bc0aff05d9c16bee25a24179dba/src/Cli/dotnet/Parser.cs#L123

It seems that this here will strip out the pound sign/hashtag.  I'm assuming this is attempting to remove comments?

I can fix the issue manually by specifying the property outside of the system parameters of TeamCity, and putting it directly in the build step, but this is the wrong approach.

Any way we can escape pound signs/hashtags somehow when in a response file?

**Comment by joeloff** [comment]
`#` is treated as the start of a comment in response files. We would either need to implement some sort of escaping mechanism or limit comments to the start of lines. The latter will likely impact a much larger group of users relying on this.

Another option would be to allow it if it's inside a quoted string perhaps

**Comment by marcpopMSFT** [comment]
Triage: Check the behavior of msbuild and potentially modify the code to check for the line starting with a # rather than having one. This was added relatively recently though so if people have added inline comments, that change could break them

**Comment by joeloff** [comment]
MSBuild honors it. A response file with `/t:Foo /p:XYZ=#HELLO` and a target like

```xml
<Target Name="Foo">
  <Message Text="XYZ=$(XYZ)" />
</Target>
```
prints the expected output that include the `#`
