### ISSUE TITLE
`dotnet --info` should also show workload info

### ISSUE THREAD

**Issue by Eilon** [dotnet/sdk#30784]
## Background

The `dotnet` CLI tool has many command line options for showing info about what is installed:

```
sdk-options:
   ...
  --info            Display .NET information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET SDK version in use.
```

The most detailed of those options is `--info`, which includes the details of all the other top-level options, and looks like this:

```
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  ...
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

But wait, there's even more info for workloads! The versions of workloads are fundamental regarding what is installed. Info on it is available via the `dotnet workload list` command:

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                16.2.1035/7.0.100      VS 17.6.33417.168
runtimes-windows           7.0.3/7.0.100          VS 17.6.33417.168
maui-ios                   52.1.0/7.0.100         VS 17.6.33417.168
maui-windows               52.1.0/7.0.100         VS 17.6.33417.168
maui-maccatalyst           52.1.0/7.0.100         VS 17.6.33417.168
android                    33.0.39/7.0.100        VS 17.6.33417.168
ios                        16.2.1035/7.0.100      VS 17.6.33417.168
maui-android               52.1.0/7.0.100         VS 17.6.33417.168
```

## Problem

Quite often when Microsoft receives bug reports we ask users to provide the output of `dotnet --info`, but for some scenarios that is incomplete information because of the lack of workload details. Then there is a back-and-forth between the customer and Microsoft to get additional details on workloads.

## Proposed solution

I propose that `dotnet --info` _also_ include the list of installed workloads.

The output could look something like this:

```
.NET SDK:
   ... various stuff ...

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  ...
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

.NET workloads installed: <-------------------------------------------------------------------- THIS IS THE NEW PART
  Installed Workload Id      Manifest Version       Installation Source
  ---------------------------------------------------------------------
  maccatalyst                16.2.1035/7.0.100      VS 17.6.33417.168
  runtimes-windows           7.0.3/7.0.100          VS 17.6.33417.168
  maui-ios                   52.1.0/7.0.100         VS 17.6.33417.168
  maui-windows               52.1.0/7.0.100         VS 17.6.33417.168
  maui-maccatalyst           52.1.0/7.0.100         VS 17.6.33417.168
  android                    33.0.39/7.0.100        VS 17.6.33417.168
  ios                        16.2.1035/7.0.100      VS 17.6.33417.168
  maui-android               52.1.0/7.0.100         VS 17.6.33417.168

Other architectures found:
  ... [more stuff]
```

**Comment by baronfel** [comment]
See https://github.com/dotnet/sdk/issues/30723 for a similar request - I think these all are pointing at the `dotnet` CLI needing to provide something more holistic than `dotnet --info`, which only carries the Runtime's view of the world.

**Comment by Eilon** [comment]
Interesting. I supposed what I want is an easy command line option that "has everything we could possibly need for the purposes of a bug report or debugging". Right now it's already pretty good, but certainly it could be better.

**Comment by baronfel** [comment]
Thanks for the pointer @vitek-karas - I now see the `CommandLineInfo` type that does what you're mentioning. It's not part of the rest of the CLI's command parser so I missed it. I agree that this is where we should put SDK-specific information like workloads and SDK-specific environment variables :+1:

**Comment by nagilson** [comment]
Something to keep in mind... `dotnet workload --info` shows more info that `dotnet workload list`. Maybe you want that?

example:
```
PS C:\Users\noahgilson\sdk> dotnet workload --info
 [wasm-tools]
   Installation Source: SDK 7.0.300
   Manifest Version:    7.0.3/7.0.100
   Manifest Path:       C:\Users\noahgilson\sdk\artifacts\bin\redist\Debug\dotnet\sdk-manifests\7.0.100\microsoft.net.workload.mono.toolchain.net7\WorkloadManifest.json
   Install Type:        FileBased
```

**Comment by baronfel** [comment]
@nagilson I was actually thinking this morning that we should inline the content from `dotnet workload --info` into `dotnet --info` as well, now that I know about the SDK-reserved section of `dotnet --info`. Thoughts on that?

**Comment by nagilson** [comment]
Sounds like a good idea to me ;)

**Comment by nagilson** [comment]
This would likely be a good first issue. Not a good 'introduction to workloads' because it doesn't really require workload concepts... but maybe that's a good thing. cc @dsplaisted since you were looking for good first issues

**Comment by JL03-Yue** [comment]
@baronfel @nagilson if I understand correctly, if adding the content from `dotnet workload --info` into the SDK-reserved section, it will not be in the same order the customer proposed(`dotnet SDKs installed`, then `dotnet runtimes installed`, then `dotnet  workloads installed`). In fact, workload information will be added right after `base path` before `Host`. Did i miss something? or it this ok?

**Comment by nagilson** [comment]
@JL03-Yue
That's a very good question. I have no idea where that output is coming from, it doesn't look like it's coming from the SDK codebase. https://github.com/dotnet/sdk/blob/c5f9057c89000cd078ab3f528ce340ca71a430c7/src/Cli/dotnet/CommandLineInfo.cs#L21
When running dogfood `dotnet --info` it shows SDK information but when it's under debug it only runs the above function. I thought maybe it'd be in installer but I don't see it there either. 

What's happening here / where is the code which prints `dotnet SDKs installed`? @baronfel @dsplaisted

**Comment by baronfel** [comment]
That's all coming from the native host, and we don't have control over that. Lack of control of the layout is one of the reasons I mentioned doing our own, completely separate info command. I _think_ we can get most of the same information the host is emitting via the native APIs, and we could reformat it however we wanted.

**Comment by baronfel** [comment]
Here's the current code in host that handles printing this: https://cs.github.com/dotnet/runtime/blob/52bdf6c3842e957f53fc2b68354c3d031f05acfc/src/native/corehost/fxr/command_line.cpp#L283-L334

**Comment by vitek-karas** [comment]
While I appreciate the advantages of controlling this fully from SDK, there's also some value to consistency. Note that we support `dotnet --info` even if there's no SDK installed, in which case the entire output comes from the host. Would be nice if the two outputs were somewhat consistent.

**Comment by nagilson** [comment]
Sorry @JL03-Yue, this turned out to be not what I thought it was.
I think the custom `dotnet info` command is an interesting idea but it might be confusing as to why is there `dotnet --info` and `dotnet info` and they give vaguely different things? 

Since the host has the dotnet root and bands, theoretically we can just invoke the latest band dotnet.exe if it exists and capture the stdout of `dotnet workload --info` on top of it, yeah? I'm glad to help with that, but it wasn't really where I was thinking this issue would go.

**Comment by baronfel** [comment]
I get that, but I also don't think the current model lets us have a seamless layout of the runtime-provided parts, and the SDK-provided parts. I'm worried that if the SDK fills the screen with workload (and maybe CLI-environment-variable in the future?) related output, the useful output from the runtime will be pushed to the bottom and the overall layout won't make sense to the user. 

_For now_ I think it's ok for us to just add installed workload information to the SDK's layout, but we should consider what better way of laying out/handshaking between the runtime and the SDK information here might look like.

**Comment by nagilson** [comment]
> Since the host has the dotnet root and bands, theoretically we can just invoke the latest band dotnet.exe if it exists and capture the stdout of dotnet workload --info on top of it in the host, yeah? 

+1 to making `dotnet list` / info feature band agnostic in this case.

**Comment by vitek-karas** [comment]
+ @elinor-fung 

For flexibility I agree that it would make sense to do as much as possible from the SDK side of things. And we can just make sure that the layout looks very similar with the no-SDK case which would be fully handled by the host.

For context - I'm pretty sure that at the time this was originally designed and implemented, we didn't have the necessary exports from the host to be able to enumerate installed runtimes and SDKs from the managed code, so the native/managed split was basically forced by that.

**Comment by nagilson** [comment]
@baronfel, @JL03-Yue and I discussed and we are just going to put workload info in the SDK around where the host is at. We can evaluate in the future if we want to invest time into cleaning up the output and moving it from the runtime to the SDK.

**Comment by marcpopMSFT** [comment]
Resolving for now as it is fixed as requested but there may be a better design in the future but we'll wait to get feedback.
