### ISSUE TITLE
[blazor][net7] dotnet..js file name is missing version info

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/sdk#30802]
### Actual behavior
The file name of `dotnet..8wdpaewqyh.js` generated by blazor app is missing version info.

![image](https://user-images.githubusercontent.com/271576/220920177-e201acb6-9763-43b0-9ffa-bf3beb2ffb96.png)

### Expected behavior
dotnet.7.0.3.pe05f8nz0f.js

### To Reproduce
- SDK 7.0.103
- install wasm-tools 7.0.3
- create simpla blazor wasm app from template
- add `<WasmBuildNative>true</WasmBuildNative>` to client project file
- `dotnet run -bl -c Release`

### Notes
`DotNetJsVersion` is used to build the name in `_ResolveBlazorWasmOutputs`, but it is set much later in the `ProcessPublishFilesForBlazor`

**Comment by pavelsavara** [comment]
cc @lewing @maraf @TanayParikh @javiercn

**Comment by mkArtakMSFT** [comment]
Ping @pavelsavara

**Comment by pavelsavara** [comment]
It doesn't reproduce for you ?

**Comment by pavelsavara** [comment]
I tested again with 7.0.400-preview.23224.17 and wasm-tools 7.0.5/7.0.100 (SDK 7.0.400-preview.23224).

`dotnet run -c Release` will indeed produce wrong file name `dotnet..o2qge3ran4.js`.

![image](https://user-images.githubusercontent.com/271576/234294719-70d4ff09-c5ee-4be4-8e35-11f3d45a88af.png)

![image](https://user-images.githubusercontent.com/271576/234294867-0ac0455d-d5cc-4c89-aa9c-e635072920c1.png)

It works well with `publish`
![image](https://user-images.githubusercontent.com/271576/234292338-4924d506-eb8b-4675-af7e-1a437c1a57f8.png)

**Comment by lewing** [comment]
is this with an 8.0.1xx sdk?

**Comment by pavelsavara** [comment]
no, this is Net7

**Comment by pavelsavara** [comment]
it's just bad file name but the app works fine
