### ISSUE TITLE
Cannot start clean .Net Maui project in Visual Studio for Mac

### ISSUE THREAD

**Issue by zurtox** [dotnet/sdk#30817]
### Description

After creating a new fresh project of .Net MAUI, I receive the following error:

```
Getting restore information for project X
The operation failed due to an internal error: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

### Steps to Reproduce

1. Create a new MAUI Project.
2. Wait until the packages _try_ to restore.
3. Expect the error

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS, Windows and Android

### Did you find any workaround?

None

### Relevant log output

```shell
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
wasm-tools                 7.0.2/7.0.100          SDK 7.0.100        
macos                      13.1.1024/7.0.100      SDK 7.0.100        
maui-maccatalyst           7.0.59/7.0.100         SDK 7.0.100        
maui-ios                   7.0.59/7.0.100         SDK 7.0.100        
maui-android               7.0.59/7.0.100         SDK 7.0.100        
maui-mobile                7.0.59/7.0.100         SDK 7.0.100        
maui                       7.0.59/7.0.100         SDK 7.0.100        
tvos                       16.1.1521/7.0.100      SDK 7.0.100        
maui-desktop               7.0.59/7.0.100         SDK 7.0.100        
wasm-tools-net6            7.0.2/7.0.100          SDK 7.0.100

Visual Studio Community 2022 for Mac
Version 17.4.4 (build 12)
```

**Comment by marcpopMSFT** [comment]
Error NETSDK1013 above looks like it's coming from a mono targets file. Are you on the latest VSMac and can you disable the mono build engine as I'm not sure that workloads and Maui scenarios support the mono build engine as that hasn't been updated in VSMac in a while iirc.

**Comment by marcpopMSFT** [comment]
closing old issues. We can reactivate if more information is provided.
