### ISSUE TITLE
dotnet tool restore doesn't make command available

### ISSUE THREAD

**Issue by CoenraadS** [dotnet/sdk#30880]
### Describe the bug
Libman is not available after dotnet tool restore

### To Reproduce
`.config/dotnet-tools.json`

```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "microsoft.web.librarymanager.cli": {
      "version": "2.1.175",
      "commands": [
        "libman"
      ]
    }
  }
}
```

1. Run `dotnet tool restore`
2. Run `dotnet libman` => Output: `Run "dotnet tool restore" to make the "libman" command available.`

### Further technical details
- I attached log file, seems like it used sdk `7.0.102`
[log.txt](https://github.com/dotnet/sdk/files/10833351/log.txt)

**Comment by marcpopMSFT** [comment]
Unfortunately, there's no tracing available in tool execution. Do you know where libman was installed to locally and does dotnet have access to that path? You can try running `dotnet <path to tool>` or try `dotnet tool run libman` as well.

**Comment by baronfel** [comment]
Also, the `dotnet -d tool run libman` command will echo out what libman DLL is launched and what the process ID is:

15:19:57 ❯ dotnet -d tool run libman
Telemetry is: Enabled
Running C:\Program Files\dotnet\dotnet.exe C:\Users\chusk\.nuget\packages\microsoft.web.librarymanager.cli\2.1.175\tools/netcoreapp2.1/any/libman.dll
Process ID: 25820
 2.1.175+29a28921bd.RR

Usage: libman [options] [command]

Options:
  --help|-h  Show help information
  --version  Show version information

Commands:
  cache      List or clean libman cache contents
  clean      Deletes all library files defined in libman.json from the project
  config     Gets or sets configuration settings
  init       Create a new libman.json
  install    Add a library definition to the libman.json file, and download the library to the specified location
  restore    Downloads all files from provider and saves them to specified destination
  uninstall  Deletes all files for the specified library from their specified destination, then removes the specified library definition from libman.json
  update     Updates the specified library

Use "libman [command] --help" for more information about a command.
```

**Comment by marcpopMSFT** [comment]
closing old issues that we don't have enough information for next steps on. We can reactivate if more details are provided.
