### ISSUE TITLE
WindowsBase NETCoreApp vs WindowsDesktopApp

### ISSUE THREAD

**Issue by miloush** [dotnet/sdk#30953]
I am starting this as a question, if there is a bug I am not quite sure who it belongs to.

It appears that _WindowsBase_ assembly is both part of _Microsoft.WindowsDesktop.App_ as well as _Microsoft.NETCore.App_. However, they have different assembly version (4.0.0.0 vs 6.0.2.0):

```
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\WindowsBase.dll
WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

vs

```
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.14\WindowsBase.dll
WindowsBase, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

My question is why do they have different versions?

(Obviously I do have an issue for context, when you compile C++/CLI assembly targeting net6.0, it uses references from _Microsoft.WindowsDesktop.App_. When you then add the C++/CLI assembly as a reference to a normal net6.0 project, you get a MSB3277 conflict between WindowsBase 4.0.0.0 coming from a _Microsoft.NETCore.App.Ref_ and WindowsBase 6.0.2.0 coming from the C++/CLI reference.)

/cc @vatsan-madhavan @pchaurasia14

**Comment by dsplaisted** [comment]
I suspect that the version in WindowsDesktop has more APIs and hence a higher version.  Or perhaps the version in Microsoft.NETCore.App is just a facade to enable code compiled against .NET Framework to work.

Also adding @joperezr and @terrajobst

**Comment by joperezr** [comment]
> Or perhaps the version in Microsoft.NETCore.App is just a facade to enable code compiled against .NET Framework to work.

I believe this is why.

**Comment by miloush** [comment]
OK so going back to my original issue, is the correct resolution to ask anyone who is referencing a C++/CLI assembly to set `<UseWPF>true</UseWPF>` in their project? If so, shouldn't that be enforced, either by SDK, or in case the reference is distributed by NuGet, perhaps the NuGet can somehow enforce it on the project?

**Comment by miloush** [comment]
It feels a lot like
```
error CS0012: The type '...' is defined in an assembly that is not referenced. You must add a reference 
to assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```
except that MSB3277 conflict is much less clear on what the developer should do, and setting UseWPF is far from intuitive.

**Comment by ericstj** [comment]
As @joperezr mentioned the small one in Microsoft.NETCore.App is just a facade for types moved into other assemblies that are part of .NET(Core). 

The one in WindowsDesktop is a superset of what's in Microsoft.NETCore.App and meant to add in all the WPF types.  It's assembly version is higher so that it "wins".

> (Obviously I do have an issue for context, when you compile C++/CLI assembly targeting net6.0, it uses references from Microsoft.WindowsDesktop.App. When you then add the C++/CLI assembly as a reference to a normal net6.0 project, you get a MSB3277 conflict between WindowsBase 4.0.0.0 coming from a Microsoft.NETCore.App.Ref and WindowsBase 6.0.2.0 coming from the C++/CLI reference.)

That's busted -- WindowsDesktop.App is an added FrameworkReference on top of Microsoft.NETCore.App.  When you produce a library with it, consumers need that reference.  WindowsBase is just a special case -- there are plenty of types in other assemblies which simply won't exist without the FrameworkReference.

> , is the correct resolution to ask anyone who is referencing a C++/CLI assembly to set <UseWPF>true</UseWPF> in their project? If so, shouldn't that be enforced, either by SDK, or in case the reference is distributed by NuGet, perhaps the NuGet can somehow enforce it on the project?

The way this works for CSProj is that the .NET SDK represents the FrameworkReference and flows that across ProjectReferences and NuGetPackages.  If you reference some other project that uses a FrameworkReference that gets added to your project even if you didn't directly reference (similar to transitive package and project references). It sounds like that piece might be missing from C++/CLI or at least from your specific scenario.

**Comment by miloush** [comment]
Indeed, that framework reference is missing:

![image](https://user-images.githubusercontent.com/10546952/222296101-71755805-bbcf-418f-a5d7-2ca5356587e3.png)

This could still be an issue with the reference though. How does the SDK know that given assembly reference requires a FrameworkReference to be added? Is the assembly file itself enough, or does it need some metadata around?

I don't really see in the C++/CLI properties any way to influence which FrameworkReference should the assembly be associated with.

**Comment by dsplaisted** [comment]
>  How does the SDK know that given assembly reference requires a FrameworkReference to be added?

Normally NuGet restore flows that information, either for project or package references.

If you're referencing a DLL directly, then that information doesn't flow and you need to know to add the FrameworkReference.

**Comment by miloush** [comment]
Thanks everyone, I believe my questions were answered. The MSB3277 is quite unhelpful for people who don't know what's going on, but I imagine there isn't many users trying to reference DLL directly in the new SDK.
