### ISSUE TITLE
dotnet list return code changed

### ISSUE THREAD

**Issue by groogiam** [dotnet/sdk#30975]
### Describe the bug
It appears the return codes for `dotnet list` have been changed to return 1 instead of 0 if there is a failure to list packages for an project in a solution. Previously this was not the case. The behavior change is breaking and has implications for build automation using `dotnet list`.

 src/AppPotion.sln package --vulnerable --include-transitive

### To Reproduce

1. Create a dotnet solution with a csproj and a docker compose project. 
1. Run `dotnet list MySln.sln package --vulnerable --include-transitive`

### Exceptions (if any)

Previously the command would return a 0 exit node. It would print something like `The project `DockerCompose\docker-compose.dcproj` uses package.config for NuGet packages, while the command works only with package reference projects.` for any projects it could not list. Recently it has been changed to return a non zero exit code which is breaking existing build automation logic.

**Comment by baronfel** [comment]
`list package` is provided by NuGet and so should be triaged by them, but I believe that had a spec for this. We may need a breaking change doc or CLI command documentation updates.
