### ISSUE TITLE
Wrong version number under "Installed Apps"

### ISSUE THREAD

**Issue by CanePlayz** [dotnet/sdk#30993]
### Describe the bug
I have the latest .NET 6 and 7 SDKs installed, but Windows shows weird version numbers under "Installed Apps"

![image](https://user-images.githubusercontent.com/81419612/222915066-f8c47b07-3e6d-4a4f-8198-23af2564ae36.png)

### To Reproduce

Have a .NET SDK installed and check the version number in Windows settings.

### Further technical details

![image](https://user-images.githubusercontent.com/81419612/222915100-19c46a8f-1598-47f4-ad46-d174b051420d.png)

**Comment by nagilson** [comment]
Those are the internal build numbers, and that is expected. Something you can ignore.

**Comment by CanePlayz** [comment]
> Those are the internal build numbers, and that is expected. Something you can ignore.

Thanks. Then something else is messing with winget not being able to detect the version numbers on older .NET SDKs.

![image](https://user-images.githubusercontent.com/81419612/223877606-fc6bf65e-613c-44e5-8f3d-a68aafcf8f5a.png)

**Comment by nagilson** [comment]
Ah, that does seem like an authoring issue. Thanks for reporting it :)

**Comment by CanePlayz** [comment]
> Ah, that does seem like an authoring issue. Thanks for reporting it :) 

Sure 👍

**Comment by CanePlayz** [comment]
I will close this issue now, because winget usually grabs the version numbers from the same source as the Apps & Features window, so winget not detecting the build numbers must be an issue on their side.
