### ISSUE TITLE
Allow for the disablement of ResolveAppHosts

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/sdk#3104]
**Repro steps:**
Build win-arm [all arm* RIDs have this failure] @ commit 0606a12720f0eace5af77c545d0d91b96ec92e27

**Error:**
error NU1605: Detected package downgrade: runtime.win-arm.Microsoft.NETCore.DotNetAppHost from 3.0.0-preview5-27607-08 to 3.0.0-preview4-27501-7. Reference the package directly from the project to select a different version. 
 DownloadPackage -> Microsoft.NETCore.DotNetAppHost 3.0.0-preview5-27607-08 -> runtime.win-arm.Microsoft.NETCore.DotNetAppHost (>= 3.0.0-preview5-27607-08) 
 DownloadPackage -> runtime.win-arm.Microsoft.NETCore.DotNetAppHost (>= 3.0.0-preview4-27501-7)

**From Microsoft.NET.Sdk.TargetingPackResolution.targets:**
```
    <ResolveAppHosts TargetFrameworkIdentifier="$(TargetFrameworkIdentifier)"
                     TargetFrameworkVersion="$(_TargetFrameworkVersionWithoutV)"
                     TargetingPackRoot="$(NetCoreTargetingPackRoot)"
                     AppHostRuntimeIdentifier="$(AppHostRuntimeIdentifier)"
                     RuntimeFrameworkVersion="$(RuntimeFrameworkVersion)"
                     PackAsToolShimRuntimeIdentifiers="@(_PackAsToolShimRuntimeIdentifiers)"
                     DotNetAppHostExecutableNameWithoutExtension="$(_DotNetAppHostExecutableNameWithoutExtension)"
                     RuntimeGraphPath="$(BundledRuntimeIdentifierGraphFile)"
                     KnownAppHostPacks="@(KnownAppHostPack)">

      <Output TaskParameter="PackagesToDownload" ItemName="_PackageReferenceToAdd" />
      <Output TaskParameter="AppHost" ItemName="AppHostPack" />
      <Output TaskParameter="PackAsToolShimAppHostPacks" ItemName="PackAsToolShimAppHostPack" />

    </ResolveAppHosts>
```

_Work-around is to disable the 'ResolveFrameworkReferences' target._

The 'ResolveFrameworkReferences' step of the 'ResolveFrameworkReferences' target can be disabled by adding:
`<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>`

The 'ResolveAppHosts' step of the 'ResolveFrameworkReferences' target should have a similar mechanism.

**Comment by nguerrera** [comment]
There is a UseAppHost=false.

This is because of how we are downloading pacakges in the core-sdk build with a hack. We should be able to switch to PackageDownload now.
