### ISSUE TITLE
Add support for RazorLangVersion 8

### ISSUE THREAD

**Issue by jjonescz** [dotnet/sdk#31058]
In https://github.com/dotnet/razor/pull/8286 we introduce RazorLangVersion 8 which calls new method `RenderTreeBuilder.AddComponentParameter`. Looks like the SDK needs to be updated, for example here:

https://github.com/dotnet/sdk/blob/94ad56aa2c36b3020fef7536f3d55ec6b1cabdc6/src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets#L46-L91

**Comment by surayya-MS** [comment]
@mkArtakMSFT, could you please follow up?

**Comment by mkArtakMSFT** [comment]
@jjonescz shouldn't this be closed already?

**Comment by jjonescz** [comment]
Yes, thanks. Resolved by https://github.com/dotnet/sdk/pull/33756.
