### ISSUE TITLE
GenAPI outputs reference to internal type in assembly-level attribute

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#31098]
When targeting System.Text.Json 6.0.0, GenAPI includes the following in its output:

```csharp
[assembly: System.Reflection.Metadata.MetadataUpdateHandler(typeof(JsonSerializerOptionsUpdateHandler))]
```

This fails to compile because `JsonSerializerOptionsUpdateHandler` is an internal type and is not included in the generated code. Here's what the actual source looks like: https://github.com/dotnet/runtime/blob/5f94bffeff62f4b767a311a4505d6d40d86279d9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptionsUpdateHandler.cs#L11-L18

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@andriipatsula it looks like we aren't applying our filter when retrieving assembly attributes

**Comment by andriipatsula** [comment]
We are checking attribute type `System.Reflection.Metadata.MetadataUpdateHandler` and not `typeof(JsonSerializerOptionsUpdateHandler)`. We do not analyze attribute's value.

**Comment by andriipatsula** [comment]
That's an interesting task! and not trivial one.

**Comment by ViktorHofer** [comment]
> How about internal attributes that have EmbeddedAttribute? Like Roslyn can generate for nullability attributes when targeting a framework that does not define those. I think you'd want to include them in the reference assembly.

I think I know what you mean but can you please post an example? We currently only look at public attributes and I think we want to keep that characteristic but exclude the ones that use internal parameter types.

**Comment by ViktorHofer** [comment]
> I wonder about RefSafetyRulesAttribute though. If the rules changed between C# language versions then does that mean GenAPI has to use the same C# version as in the original assembly, in order to get the same ref safety rules?

I **think** you can pass in the LanguageVersion to Microsoft.CodeAnalysis to configure the rules accordingly. At least that's what we have done in the old CCI based GenAPI.

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/sdk/issues/31098 to fix this. As mentioned above, the change follows what we were doing in the CCI based GenAPI. Internal attributes are already filtered out today in main. If we want to change that, we should discuss that in a separate issue.
