### ISSUE TITLE
Resolve runtime pack assets for crossgen even if app is framework-dependent

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3110]
Crossgen operates on implementation assemblies only, even when passed as references to the compiler. To crossgen a framework-dependent app, we need all of the framework implementation assemblies to be passed to crossgen as references.

Note that crossgen requires picking a RID. The app can be framework-dependent, but it must be RID specific. (Crossgen generates native code, which can't be rid-agnostic, obviously.) We are guaranteed to have downloaded the runtime packs, we just need to resolve the framework assemblies from it as though the app was self-contained, but without putting them in deps.json or copying them, etc.

Today, crossgen tasks can find the base shared framework implementation assemblies next to it (it ships in the base runtime pack), but this doesn't work for the other frameworks like WindowsDesktop or ASP.NET. This also can't just blindly aggregate all the files in all the runtime packs, this list needs to account for conflict resolution (WindowsBase in WindowsDesktop wins over WindowsBase in NETCoreApp), etc.

**Comment by nguerrera** [comment]
cc @fadimounir @dsplaisted

**Comment by fadimounir** [comment]
@nguerrera Can we mark this issue as blocking to R2R/ILLinker scenarios to bump the priority?

**Comment by nguerrera** [comment]
I will look at this tomorrow. Feel free to keep nagging me about it on Teams. ;) I added the label, but I'm not sure how much that is being monitored these days.
