### ISSUE TITLE
Backport Docker `--platform` switch support to .NET 7.latest

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#31133]
The problem that this addresses was first encountered with .NET 7 users. We've addressed it (and proved it out) with .NET 8, and should backport it with the 7.0.3xx series. There is no need to backport it to the earlier feature bands.

There is no compelling reason to backport this change to .NET 6. For .NET 6 users that really want this experience (which I get), we'll recommend that they use the .NET 7 or 8 SDK. It's not perfect, but should be pretty workable.

Context: https://github.com/dotnet/sdk/issues/30369

**Comment by nagilson** [comment]
Closed by : https://github.com/dotnet/sdk/pull/31319
