### ISSUE TITLE
[NETSDKE2E][Regression] Publishing blazorwasm project is blocked by"Emscripten Deadlocked" warning.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#31209]
1. Install NET8 preview 3: 8.0.100-preview.3.23164.23 (runtime- 8.0.0-preview.3.23164.2 )
2. Install wasm-tools 
dotnet workload install wasm-tools --skip-manifest-update 
3. New blazorWasm:  dotnet new blazorwasm 
4. dotnet publish

**Expected Result:**
Publish successfully.

**Actual Result:**
Publish is blocked by below warning:
![image](https://user-images.githubusercontent.com/65637796/225232163-1b60d3f3-bc22-4bfb-89fc-79abca0a631b.png)

dotnet --info
.NET SDK:
Version:   8.0.100-preview.3.23164.23
Commit:    23e36ed23b Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.3.23164.23\ .NET workloads installed:
[wasm-tools]
   Installation Source: SDK 8.0.100-preview.3
   Manifest Version:    8.0.0-preview.3.23164.2/8.0.100-preview.3
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.3\microsoft.net.workload.mono.toolchain.current\WorkloadManifest.json
   Install Type:        FileBased Host:
  Version:      8.0.0-preview.3.23164.2
  Architecture: x64
  Commit:       d9f453924f .NET SDKs installed:
  8.0.100-preview.3.23164.23 [C:\Program Files\dotnet\sdk] .NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.3.23163.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23164.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23160.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] Other architectures found:
  None Environment variables:
  Not set global.json file:
  Not found Learn more:https://aka.ms/dotnet/info Download .NET:https://aka.ms/dotnet/download

**Comment by WenJunJi01** [comment]
Repro on Win ARM64 with the latest .NET 8 Preview 3 SDK (8.0.100-preview.3.23178.7) installed,
![image](https://user-images.githubusercontent.com/87680983/229408751-b4c60dbb-b09a-4814-9402-ba9d4c390a54.png)

**Comment by WenJunJi01** [comment]
Not repro with .NET 8 Preview 4 SDK: 8.0.100-preview.4.23205.4(runtime-8.0.0-preview.4.23181.2) installed on Win ARM64.
![image](https://user-images.githubusercontent.com/87680983/230351506-28780308-132c-420c-80d4-a2ed3e66e44c.png)

**Comment by vdanche** [comment]
This issue not repro on 8.0.100-preview.4.23207.7 (runtime- 8.0.0-preview.4.23181.2)
![image](https://user-images.githubusercontent.com/65637796/230840336-f9d6e04a-411f-4b5d-bbba-cc32a8f2abc9.png)
