### ISSUE TITLE
[NetSDKE2E][Loc][VS64] With .NET 8 preview 3 SDK installed on German OS, warning description is unlocalized when running "dotnet publish -r win10-x64" in CLI.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#31213]
1. Install NET8 preview 3: 8.0.100-preview.3.23164.23 (runtime- 8.0.0-preview.3.23164.2) from https://github.com/dotnet/installer on German OS.
2. dotnet new console -o myconsole
3. dotnet publish -r win10-x64

### Expected Result:
The warning description should be localized.

### Actual Result:
The warning description is unlocalized.
DE:
![image](https://user-images.githubusercontent.com/99376012/225271903-94de1e97-13d4-46d3-ae90-00d99ec4b548.png)

EN:
![image](https://user-images.githubusercontent.com/99376012/225266955-fa39cb0b-c312-4e21-bcc2-bf75f722244f.png)

dotnet --info:
.NET SDK:
Version:   8.0.100-preview.3.23164.23
Commit:    23e36ed23b
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.3.23164.23\
.NET workloads installed:
[wasm-tools]
   Installation Source: SDK 8.0.100-preview.3
   Manifest Version:    8.0.0-preview.3.23164.2/8.0.100-preview.3
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.3\microsoft.net.workload.mono.toolchain.current\WorkloadManifest.json
   Install Type:        FileBased
Host:
  Version:      8.0.0-preview.3.23164.2
  Architecture: x64
  Commit:       d9f453924f
.NET SDKs installed:
  8.0.100-preview.3.23164.23 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.3.23163.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23164.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23160.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Other architectures found:
  None
Environment variables:
  Not set
global.json file:
  Not found
Learn more:
https://aka.ms/dotnet/info 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
Also repro on .net8.0.100-preview.4.23206.10 (runtime-8.0.0-preview.4.23181.2) SDK on German OS
![image](https://user-images.githubusercontent.com/106054229/230547184-230f4726-2e77-4e8f-b010-e9d304893314.png)
