### ISSUE TITLE
Unable to resolve AppHost for the current runtime if it's not included in the SDK

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/sdk#3122]
I'm seeing broken behaviour when the app host is not bundled in the targeting pack of the SDK.

I discovered this as part of our dependency update in https://github.com/aspnet/AspNetCore-Tooling/pull/409. When we first ingested the changes, we saw errors such like:
```
(AspNetCore-Tooling) C:\Users\nimullen\AppData\Local\Temp\Razor\okum4oes.lay\MvcWithComponents> dotnet msbuild /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp30PackageVersion=3.0.0-preview5-27608-16 /p:_RazorBuildServerPipeName="bc0e5740-2362-4e4c-8244-64c38154f0d7" /t:Build /p:Configuration=Debug /p:_RazorForceBuildServer=true
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\GitHub\AspNetCore-Tooling\.dotnet\sdk\3.0.100-preview4-011136\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\nimullen\AppData\Local\Temp\Razor\okum4oes.lay\MvcWithComponents\MvcWithComponents.csproj]
C:\GitHub\AspNetCore-Tooling\.dotnet\sdk\3.0.100-preview4-011136\Microsoft.Common.CurrentVersion.targets(4552,5): error MSB3030: Could not copy the file "C:\Users\nimullen\AppData\Local\Temp\Razor\okum4oes.lay\MvcWithComponents\obj\Debug\netcoreapp3.0\MvcWithComponents.exe" because it was not found. [C:\Users\nimullen\AppData\Local\Temp\Razor\okum4oes.lay\MvcWithComponents\MvcWithComponents.csproj]
```
I have a binlog for the failing scenario:
[msbuild.zip](https://github.com/dotnet/sdk/files/3074987/msbuild.zip)

It seems like the issue is that the app host package could not be found in "\.dotnet\x64\packs\runtime.win-x64.Microsoft.NETCore.DotNetAppHost" since the version of the runtime we reference is ahead of the the version that's included in the SDK. In this case, sdk\3.0.100-preview4-011136 doesn't contain the targeting pack for runtime\3.0.0-preview5-27608-16. However, using a newer runtime than what's included in the SDK is a core scenario that we depend on so how should this work?

Can someone on the SDK team please advise on the expectation here and look through the binlog to see why the mechanism breaks in our scenario?

cc @nguerrera @dsplaisted 

cc @dougbu @natemcmaster

**Comment by dsplaisted** [comment]
@JunTaoLuo That binlog has the following failure:

> C:\gh\AspNetCore-Tooling\.dotnet\sdk\3.0.100-preview4-011136\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(233,5): error NETSDK1004: Assets file 'C:\Users\johluo\AppData\Local\Temp\Razor\2oi4yru1.lqx\SimpleMvc\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\johluo\AppData\Local\Temp\Razor\2oi4yru1.lqx\SimpleMvc\SimpleMvc.csproj]

That seems to be different than the AppHost issue you are describing here.  Did you include the right binlog?

I do think that we should make `RuntimeFrameworkVersion` apply to the AppHost selection.  We should also add an `AppHostVersion` that applies only to the AppHost.

In the meantime, the following should allow you to set the AppHost version:

```xml
<ItemGroup>
    <KnownAppHostPack Update="Microsoft.NETCore.App" AppHostPackVersion="$(RuntimeFrameworkVersion)" />
</ItemGroup>
```

**Comment by dsplaisted** [comment]
Also, note the different ways you can control the runtime versions described here: https://github.com/dotnet/sdk/pull/2887 (though currently there's nothing to control the AppHost version).

**Comment by JunTaoLuo** [comment]
Oops, yes I attached the wrong binlog file.
[msbuild.zip](https://github.com/dotnet/sdk/files/3075365/msbuild.zip)

**Comment by dsplaisted** [comment]
Looking at the correct binlog, `RuntimeFrameworkVersion` actually does apply to the AppHost.  It looks like it is looking for the AppHost in the NuGet packages folder (C:\Users\johluo\.nuget\packages\) and not finding it.  I would expect that package to be downloaded during Restore.  Did you run a restore on this project?

**Comment by JunTaoLuo** [comment]
Yes a restore was run, otherwise the error in the first binlog I attached (the wrong one) would appear. However, I don't see the package being restored in C:\Users\johluo.nuget\packages so maybe the restore step is the issue? I've attached the binlog of the restore. Though it was successful, maybe there's something in there worth checking:
[msbuild.zip](https://github.com/dotnet/sdk/files/3075443/msbuild.zip)

**Comment by JunTaoLuo** [comment]
Any updates on this @dsplaisted ?

**Comment by nguerrera** [comment]
Looking. First thing I see is the update of KnownAppHostPack is happening before RuntimeFrameworkVersion is set in Directory.Build.*targets*.

From above, it sounds like @dsplaisted doesn't think that workaround should be necessary after all, but if it is, move it after the setting of RuntimeFrameworkVersion.

**Comment by nguerrera** [comment]
This is working fine for me without any workaround:

I simplified the project a little bit (so it would build without warning and copying minimal files out of the binlog) and pulled in latest preview5 RuntimeFrameworkVersion from latest preview4 SDK. It worked fine and I can see it getting the preview5 apphost from nuget in the binlog.

```
C:\temp\SimpleMVc>dotnet nuget locals all --clear
info : Clearing NuGet HTTP cache: C:\Users\nicholg\AppData\Local\NuGet\v3-cache
info : Clearing NuGet global packages folder: C:\Users\nicholg\.nuget\packages\
info : Clearing NuGet Temp cache: C:\Users\nicholg\AppData\Local\Temp\NuGetScratch
info : Clearing NuGet plugins cache: C:\Users\nicholg\AppData\Local\NuGet\plugins-cache
info : Local resources cleared.

C:\temp\SimpleMVc>dotnet --version
3.0.100-preview4-011216

C:\temp\SimpleMVc>type Directory.Build.targets
<Project>
  <PropertyGroup>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">3.0.0-preview5-27615-08</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>

C:\temp\SimpleMVc>type SimpleMVc.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.NETCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RunningAsTest)' == ''">
    <!-- We don't want to run build server when not running as tests. -->
    <UseRazorBuildServer>false</UseRazorBuildServer>
  </PropertyGroup>

</Project>

C:\temp\SimpleMVc>rd /s /q bin obj

C:\temp\SimpleMVc>dotnet build
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 1.17 sec for C:\temp\SimpleMVc\SimpleMVc.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview4-011216\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\temp\SimpleMVc\SimpleMVc.csproj]
  SimpleMVc -> C:\temp\SimpleMVc\bin\Debug\netcoreapp3.0\SimpleMVc.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.61
```

```
C:\temp\SimpleMVc>dotnet nuget locals all --clear
info : Clearing NuGet HTTP cache: C:\Users\nicholg\AppData\Local\NuGet\v3-cache
info : Clearing NuGet global packages folder: C:\Users\nicholg\.nuget\packages\
info : Clearing NuGet Temp cache: C:\Users\nicholg\AppData\Local\Temp\NuGetScratch
info : Clearing NuGet plugins cache: C:\Users\nicholg\AppData\Local\NuGet\plugins-cache
info : Local resources cleared.
```

```



Directory.Build.targets
``` xml
<Project>
  <PropertyGroup>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">3.0.0-preview5-27615-08</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>
```

SimpleMvc.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.NETCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RunningAsTest)' == ''">
    <!-- We don't want to run build server when not running as tests. -->
    <UseRazorBuildServer>false</UseRazorBuildServer>
  </PropertyGroup>

</Project>
```

**Comment by JunTaoLuo** [comment]
Ah I found the issue in our setup. The tests were restoring without a runtime framework version but the build command was invoked with a specific runtime framework version. In this case, the build proceeded since the project.assets.json was present. However, since the restore was not invoked with the correct runtime framework version, the app host was missing.
