### ISSUE TITLE
Warn if project is missing both Desktop SDK and UseWPF/UseWinForms

### ISSUE THREAD

**Issue by cartermp** [dotnet/sdk#3126]
Even if we have cool tooling that adds the appropriate stuff to a project file based on various actions in the IDE, there will still be users who manually edit their WinForms/WPF project files.

We should emit a warning under the following conditions:

* `Microsoft.NET.Sdk.WindowsDesktop` is specified but there is no `UseWPF` or `UseWinForms`
* `UseWPF` or `UseWinForms` is specified but the SDK attribute is not `Microsoft.NET.Sdk.WindowsDesktop`

In the first case, it would be great if the warning could say something to the effect of:

"Microsoft.NET.Sdk.WindowsDesktop is specified, but no corresponding UseWPF or UseWinForms property was found."

In the latter case, using WPF as an example, something to the effect of:

"UseWPF was specified but the SDK attribute is not Microsoft.NET.Sdk.WindowsDesktop"

Not sure if this is an SDK concern or not, but I figured I'd log it somewhere.

**Comment by davkean** [comment]
This is an SDK concern and have moved it.

**Comment by dsplaisted** [comment]
I believe this is all done.  @vatsan-madhavan, let us know if that's not the case.

**Comment by vatsan-madhavan** [comment]
Yes, this is completed now - thanks for closing!
