### ISSUE TITLE
EnableAotAnalyzer=true should also default EnableSingleFileAnalyzer=true

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#31284]
There are almost no situations where I want to enable the AOT analyzer, but don't also want the Single File analyzer. We should set `EnableSingleFileAnalyzer=true` by default when someone sets `EnableAotAnalyzer=true`.

In dotnet/aspnetcore we enabled the AOT analyzer, thinking that would be enough to catch NativeAOT warnings. But we didn't remember to enable the SingleFile analyzer, and thus warnings slipped through.

@vitek-karas @agocke @sbomer @MichalStrehovsky

**Comment by eerhardt** [comment]
I almost wonder if `EnableAotAnalyzer` should also imply `EnableTrimAnalyzer` as well... If I want to AOT my library, I will also need to get trimming warnings.

**Comment by agocke** [comment]
> (especially lacking a higher-level switch for AOT-compatible libraries

Yeah, I think this is the problem. Maybe we should just add a new property for this. `IsAotCompatible=true`?

**Comment by eerhardt** [comment]
Would `IsAotCompatible=true` mean:

* EnableTrimAnalzyer defaults to true
* EnableSingleFileAnalyzer defaults to true
* EnableAotAnalyzer defaults to true
* IsTrimmable defaults to true

?

**Comment by vitek-karas** [comment]
I think that makes sense.
(Rant: I would love to replace IsTrimmable with IsTrimCompatible and it not having any effect on the trimmer, but that ship has sailed :-))

**Comment by eerhardt** [comment]
> (Rant: I would love to replace IsTrimmable with IsTrimCompatible and it not having any effect on the trimmer, but that ship has sailed :-)

Yeah, as long as we support Blazor WASM and Maui trimming models, we need something that affects the trimmer.

**Comment by agocke** [comment]
OK, one last question here,

Should it be `IsAotCompatible` or `CheckAotCompatible`?

"Check" is slightly more accurate but also more verbose.

**Comment by agocke** [comment]
OK, thought about it some more. `IsAotCompatible` implying `IsTrimmable` makes sense. `CheckAotCompatible` less so.
