### ISSUE TITLE
.NET developers have an improved containerization experience

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#31281]
With dotnet/sdk-container-builds .NET developers have a great story for containerizing their apps without needing a container engine.  We can continue investment in this space to make this pathway even smoother by

* focusing on integrations with existing container tooling in editors (like debug)
* integrating with other tools like `azd`
* reducing the steps required for the user to activate the functionality

This epic contains the following User Stories:
* [x] https://github.com/dotnet/sdk/issues/30369
* [x] https://github.com/dotnet/sdk/issues/24216

~~* [ ] Integrate with `azd`~~
~~* [ ] https://github.com/dotnet/sdk/issues/26161~~
~~* [ ] https://github.com/dotnet/sdk/pull/29817~~
~~* [ ] https://github.com/dotnet/sdk-container-builds/issues/87~~

**Comment by marcpopMSFT** [comment]
@baronfel there are two open issues and an open PR (targeting 7.0.3xx!). Should I move this to a different milestone and which one?

**Comment by baronfel** [comment]
The remaining items (and more) have been moved to https://github.com/dotnet/sdk/issues/35552 for future efforts.
