### ISSUE TITLE
No package for Ubuntu 19.04 (Disco Dingo)

### ISSUE THREAD

**Issue by vidarw** [dotnet/sdk#3128]
Ubuntu is officially releasing version 19.04 (Disco Dingo) within a week.
There is currently no `dotnet-sdk-2.2` available for the newset version of Ubuntu in the Microsoft repository.

Solution would be to add a disco compatible release package or as a temporary fix provide a standalone .deb package to install with `dpkg`.

**Comment by wli3** [comment]
@leecow

**Comment by leecow** [comment]
We'll also need 2.1 and 3.0

**Comment by gtonic** [comment]
+1

**Comment by jradxl** [comment]
Well as of today there is a directory, but no packages
https://packages.microsoft.com/ubuntu/19.04/
So I guess we just have to be patient.

There is a Snap package for 2.2, 
# snap search dotnet
dotnet-sdk         2.2.203  dotnetcore✓  classic

But Rider doesn't detect it's presence.
Hence looking for .deb

**Comment by Stijn98s** [comment]
This is because the snap cannot create syslinks. dotnet is available under dotnet-sdk.dotnet in the snap.
