### ISSUE TITLE
SDK doesn't honor TargetingPackVersion on FrameworkReference

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#3129]
SDK permits specifying TargetingPackVersion metdata on FrameworkReference:
https://github.com/dotnet/sdk/blob/7d6b26df6cc873e07816a098bb66a6bde2640b06/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs#L99-L103

But then it constructs the path to the targeting pack based on KnownFrameworkReference: 
https://github.com/dotnet/sdk/blob/7d6b26df6cc873e07816a098bb66a6bde2640b06/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs#L112-L122

Also, is this really the way we should be specifying which framework to build against?  I had expected `RuntimeFrameworkVersion` to work, but it looks like that only controls the runtime and not ref-pack.

/cc @dsplaisted

**Comment by dsplaisted** [comment]
I've added a fix for this to #3111.

It is intentional that the targeting pack versions separately from the runtime version.  Once we ship an RTM, the runtime will continue to be patched, but we expect to keep using the 3.0.0 version (for example) of the targeting pack unless there is a bug we need to fix with the targeting pack.

**Comment by ericstj** [comment]
I see.  Did you consider a property for this, or is that not so interesting in light of multiple frameworks?  /cc @natemcmaster @zsd4yr @vatsan-madhavan

**Comment by ericstj** [comment]
Looks like RuntimeFrameworkVersion alone should have  been enough, so there might be another bug here since that stopped working for us (at least on Preview3 bits).

**Comment by livarcocc** [comment]
@dsplaisted is this still an issue?

**Comment by dsplaisted** [comment]
This should be fixed.  RuntimeFrameworkVersion doesn't affect the targeting pack version, as once we release the runtime and the targeting packs will be patched independently.
