### ISSUE TITLE
_WriteAppConfigWithSupportedRuntime target shouldn't depend on RAR $(ResolveAssemblyReferencesStateFile) as an input

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#3131]
See https://github.com/Microsoft/msbuild/issues/4313

https://github.com/dotnet/sdk/blob/8cb31b0fd0bb5d36b9781442865f2e26cf6fbedc/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateSupportedRuntime.targets#L44

We should find another way to invalidate. I'm seeing RAR cache written to every time even during rebuilds where nothing has changed. This in turn triggers rebuild of WriteAppConfig, even though the app config is the same.

**Comment by livarcocc** [comment]
@wli3 this seems like something that you added, can you take a look at it?

@nguerrera could this be related to that RAR cache bug I assigned to you?

**Comment by nguerrera** [comment]
> @nguerrera could this be related to that RAR cache bug I assigned to you?

The unexpected dirtiness of the cache could be related, but I don't know until I dig on that.

I don't know why the RAR state file is an input to this target, though, regardless.

**Comment by nguerrera** [comment]
```
Inputs="$(MSBuildAllProjects);@(AppConfigWithTargetPath)"
```

seems sufficient to me.

**Comment by wli3** [comment]
@KirillOsenkov how to repro this rewrite of WriteAppConfig? We have [existing test ](https://github.com/dotnet/sdk/pull/2447/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.targets#diff-5791e28781860b8d88a502b3de5f2682R594) to build it twice and ensure no rebuild of the file. I think it is fine to make the change but I'd to have a test to the prevent future regression

**Comment by KirillOsenkov** [comment]
@wli3 I've e-mailed you the repro steps, thanks!
