### ISSUE TITLE
[NETSDKE2E][ARM64][Regression] Publishing blazorwasm project failed with error MSB3073: The command "embuilder.bat build MINIMAL" exited with code 1.

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#31330]
**Steps to reproduce:**
1. Install .NET 8 Preview 3 SDK from https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-win-arm64.exe
2. Install wasm-tools 
`dotnet workload install wasm-tools --skip-manifest-update`
3. New blazorWasm: `dotnet new blazorwasm`
4. Run `dotnet publish`

**Expected Result:**
Publish should be successfully.

**Actual Result:**
Publishing blazorwasm project failed with error MSB3073: The command "embuilder.bat build MINIMAL" exited with code 1.
![image](https://user-images.githubusercontent.com/87680983/226539647-1d74d321-ed32-42bd-b021-239f891adbca.png)

**dotnet **info:****
.NET SDK:
 Version:   8.0.100-preview.3.23170.22
 Commit:    37b628ca32

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   D:\Program Files\dotnet\sdk\8.0.100-preview.3.23170.22\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.3.23170.7
  Architecture: arm64
  Commit:       059898f8c0

.NET SDKs installed:
  8.0.100-preview.3.23170.22 [D:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.3.23170.11 [D:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23170.7 [D:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23169.1 [D:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [D:\Program Files\dotnet\x64]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
  x86   [D:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by danroth27** [comment]
@lewing Looks like this issue might be specific to wasm-tools on ARM.

**Comment by lewing** [comment]
I think the lastest builds shouldn't have this problem but @radekdoulik would know for sure

**Comment by v-jieyan2** [comment]
@lewing @radekdoulik This issue still exists with the latest build(.net8.0.100-preview.3.23177.13) installed on Win ARM64.
![image](https://user-images.githubusercontent.com/106043919/228125092-c67f2532-d413-4d74-96e5-721c1aaca411.png)

**Comment by radekdoulik** [comment]
> I think the lastest builds shouldn't have this problem but @radekdoulik would know for sure

this should be fixed by https://github.com/dotnet/runtime/pull/83475. @lewing do we need to backport it to preview3?

**Comment by WenJunJi01** [comment]
Hi @radekdoulik, with the latest .NET 8 Preview 3 SDK (8.0.100-preview.3.23178.7) installed, error MSB3073 no longer occurs. 
But publishing is blocked by"Emscripten Deadlocked" warning. This problem also occurs on win-x64, and there is a existing bug(https://github.com/dotnet/sdk/issues/31209) tracking it.
![image](https://user-images.githubusercontent.com/87680983/229407951-a616eabf-7b2c-47c1-b3f6-2d107250240c.png)

**Comment by WenJunJi01** [comment]
Not repro with .NET 8 Preview 4 SDK: 8.0.100-preview.4.23205.4(runtime-8.0.0-preview.4.23181.2) installed on Win ARM64.
![image](https://user-images.githubusercontent.com/87680983/230351713-e18caae1-b809-4821-a872-f14be99d1c6c.png)

**Comment by radekdoulik** [comment]
the cache locking problem should be fixed with https://github.com/dotnet/runtime/pull/84356

**Comment by WenJunJi01** [comment]
This issue is also not repro with 8.0.100-preview.4.23207.7 (runtime- 8.0.0-preview.4.23181.2) installed. Close it as fixed.

**Comment by MichaelVach** [comment]
Facing ths issue and would like to know if its possible to download preview4 somewhere.
