### ISSUE TITLE
[preview][tizen] 8 and 7 both preview build tizen not works

### ISSUE THREAD

**Issue by OurIslam** [dotnet/sdk#31366]
tested on 7.0.300-preview.23122.5
![image](https://user-images.githubusercontent.com/3030547/226890711-5303e9ff-27ce-435b-9234-d3c88459d812.png)

tasted
and 8.0.100-preview.1.23115.2
same error
![image](https://user-images.githubusercontent.com/3030547/226890806-cfaedd02-b543-411d-8805-529a2def0bbc.png)

but work at non preview 
![image](https://user-images.githubusercontent.com/3030547/226891610-619c6e39-911d-4951-839d-e2c9fdd61712.png)

anyway i have a question that when my pc installed .net 8.0.100-preview.1.23115.2 and 7.0.4 full
how i can set default sdk as 7.0.4 => vs studio project analyzer then i dont have to uninstall preview build to use tizen  .

i mean is there a way to change the default sdk 8 to 7.0.4 without uninstall preview

**Comment by marcpopMSFT** [comment]
Use [global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) to pin your project to an older version of the SDK.

CC @jonathanpeppers on when Tizen will have new versions of those workloads. We're having internal discussions on ways of making it so Tizen doesn't have to release a new version with each SDK band.

**Comment by jonathanpeppers** [comment]
/cc @JoonghyunCho @shyunMin @rookiejava

Are we able to make a 7.0.300 version of this package?

https://www.nuget.org/packages/Samsung.NET.Sdk.Tizen.Manifest-7.0.200

I believe 7.0.300 is still in preview, but I think you'll have to release a manifest for now.

**Comment by OurIslam** [comment]
in my os tizen now works at .net 8 and .net 7 non preview 
![image](https://user-images.githubusercontent.com/3030547/227106016-dddcfbee-14b6-4959-9f25-9d8a4cc467ae.png)

also .net 6.0.407 -tizen not work at my pc 
![image](https://user-images.githubusercontent.com/3030547/227106621-59c50c78-1217-4d95-9817-c2c94d21c8b4.png)
