### ISSUE TITLE
Long delay or hang at restore

### ISSUE THREAD

**Issue by ygoe** [dotnet/sdk#31374]
### Describe the bug
Running `dotnet publish` (or maybe also `dotnet restore`) may hang for a very long time with no output at all.

### To Reproduce
`dotnet publish -c Release -r win-x64 --self-contained -nologo`

### Output
>   Wiederherzustellende Projekte werden ermittelt...

The cursor then stays in the first column of the next line. Nothing happens.

Oh, something happened while I'm writing this:

>  Fehler beim Herunterladen von Paket "Microsoft.WindowsDesktop.App.Runtime.win-x64.7.0.4" von "https://api.nuget.org/v
  3-flatcontainer/microsoft.windowsdesktop.app.runtime.win-x64/7.0.4/microsoft.windowsdesktop.app.runtime.win-x64.7.0.4
  .nupkg".
>  Timeout beim Download von "https://api.nuget.org/v3-flatcontainer/microsoft.windowsdesktop.app.runtime.win-x64/7.0.4/
  microsoft.windowsdesktop.app.runtime.win-x64.7.0.4.nupkg", weil seit 60000 ms keine Daten empfangen wurden.
    Exception of type 'System.TimeoutException' was thrown.
>  "C:\Source\CMyApp.csproj" wiederhergestellt (in "4,55 min").

Sometimes, when the internet connection is slow, it takes one or two minutes to download some new versions of a package. I don't see what's going on or if it will ever continue.

### Suggested fix
There should be some kind of progress warning if something takes longer than a few seconds.

### Further technical details
- Include the output of `dotnet --info`

```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

Visual Studio 2022 17.5.2 on Windows 10

**Comment by baronfel** [comment]
I think at least part of this request (being aware that the process _is_ working and that something is happening) will be addressed with the changes to MSBuild logging we're prototyping with the LiveLogger. In that case there will be a live-updated section with a timer letting you know how much time is being spent on each target being worked, so you'd see something like

```
...
app.csproj: Restore (12.5s)
...
```

where the timer would be live-updating as the Restore progresses.  It's hard to report progress bar progress in MSBuild overall because the amount of work to be done (e.g. the number of Targets to execute) is very dynamic, but we do want to extend the logging interfaces of MSBuild to allow Tasks to report progress for specific units of work. When that happens then the LiveLogger would interpret and show that progress reporting as a bar.

**Comment by ygoe** [comment]
Sounds great!
