### ISSUE TITLE
Disclosed vulnerability in dotnet 6.0: GHSA-5crp-9r3c-p9vr (Newtonsoft.Json)

### ISSUE THREAD

**Issue by linaelf** [dotnet/sdk#31382]
### Describe the bug
Below Vulnerability found for dotnet/sdk 6.0.407
https://github.com/advisories/GHSA-5crp-9r3c-p9vr

Package	Installed_Version	Required_Version
Newtonsoft.Json	9.0.1	13.0.1

dotnet/sdk 7.0 already fixed it. Should dotnet 6.0 do the same?

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
This should be resolved with the 6.0.116 and 6.0.311 releases that went out today and the 6.0.409 release that will go out in May. Note that the component usage was previously reviewed and determined not to be a risk but we are cleaning this up anyway to help mitigate scanning tools.

**Comment by marcpopMSFT** [comment]
May release was delayed till June but this should be resolved now.
