### ISSUE TITLE
GenAPI filters out generic interfaces for implementations

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/sdk#31484]
Affected version - `8.0.100-preview.3.23170.2`

Steps to reproduce:
  - generate `System.Collections.Immutable: 6.0.0` using [SBRP](https://github.com/dotnet/source-build-reference-packages/blob/main/generate.sh)
  - build the resulting project (`./build.sh --projects <path_to_csproj> `)

Several classes will be generated incorrectly. For example:
```
    public sealed partial class ImmutableHashSet<T> : IEnumerable, ICollection
    {
        ... 
        bool Generic.ICollection<T>.IsReadOnly { get { throw null; } }
		...
    }
```

with the exception:
```
'ImmutableHashSet<T>.ICollection<T>.IsReadOnly': containing type does not implement interface 'ICollection<T>'
```

where `ICollection` is a public type ([source](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ICollection.cs#L8)):
```
	public interface ICollection<T> : IEnumerable<T>
	{
		...
	}
```

Adding the generic manually to the interface list eliminates the issue.

CC: @andriipatsula

**Comment by oleksandr-didyk** [comment]
A few side notes

The generator output seems to be clean of any errors:
```
  PackageSourceGenerator -> Generating package source for System.Collections.Immutable (v6.0.0)...
  Determining projects to restore...
  Restored /datadrive/source/source-build-reference-packages/artifacts/bin/PackageSourceGenerator/system.collections.immutable/6.0.0/system.collections.immutable.6.0.0.csproj (in 3.47 sec).
  Generated reference assembly source code: /datadrive/source/source-build-reference-packages/tmp/system.collections.immutable/6.0.0/lib/net6.0
  Generated reference assembly source code: /datadrive/source/source-build-reference-packages/tmp/system.collections.immutable/6.0.0/lib/netstandard2.0
  Generated reference assembly source code: /datadrive/source/source-build-reference-packages/tmp/system.collections.immutable/6.0.0/lib/net461
  PackageSourceGenerator -> /datadrive/source/source-build-reference-packages/tmp/system.collections.immutable/6.0.0/System.Collections.Immutable.6.0.0.csproj
  PackageSourceGenerator -> /datadrive/source/source-build-reference-packages/tmp/system.collections.immutable/6.0.0/system.collections.immutable.nuspec
  PackageSourceGenerator -> Package source successfully generated for System.Collections.Immutable (v6.0.0).
```

Some members of the filtered out interfaces are also generated incorrectly. Example:
```
    public readonly partial struct ImmutableArray<T> : ..., IList, ...
	{
		...
		T Generic.IList<T>.Item { get { throw null; } set { } }
		...
	}
```
would result in:
```
'ImmutableArray<T>.Item' in explicit interface declaration is not found among members of the interface that can be implemented
```

**Comment by ViktorHofer** [comment]
@andriipatsula can you please take a look at this issue? I will be out the next two weeks starting on Thursday and I won't have time to root cause this. I'm not sure why this didn't show in the initial testing as implementing generic interfaces isn't uncommon in .NET.
