### ISSUE TITLE
.NET Core 3 does not load pdbs from NuGet packages

### ISSUE THREAD

**Issue by JamesNK** [dotnet/sdk#3161]
Source Link does not work when a NuGet package has its PDB files in the primary nupkg package because the symbols are never loaded. It works in .NET Core 2.2.

Repo: [ConsoleApp20.zip](https://github.com/dotnet/sdk/files/3101009/ConsoleApp20.zip)

Success:

1. View csproj and note that the version target framework is `netcoreapp2.2`
2. Launch console with debugging and step into JsonConvert.SerializeObject
3. Source Link downloads and opens source code file

Failure:

1. Change csproj target framework to `netcoreapp3.0`
2. Launch console with debugging and step into JsonConvert.SerializeObject
3. Visual Studio steps over the Newtonsoft.Json API.

VS 2019 16.1 Preview 1
.NET Core 3.0.100-preview5-011367

**Comment by livarcocc** [comment]
@tmat any idea from the top of your head on what might be wrong here?

**Comment by tmat** [comment]
Seems like dup of https://github.com/dotnet/sdk/issues/1458

**Comment by bording** [comment]
@tmat I'm not sure this is a dupe. #1458 is about .NET Framework targets not copying the PDBs to to the bin folder. 

.NET Core up to 3.x used to successfully reference the PDB from the NuGet package folder, but now it's not doing that.

**Comment by tmat** [comment]
I believe the underlying issue is the same. .NET core never copied the PDBs. IIRC the difference is that prior to 3.x DLLs were loaded directly from the nuget cache while in 3.x they are loaded from the output dir.

**Comment by bording** [comment]
Given that the original issue has been open for almost 3 years after I opened it, do you think pointing out that it now impacts .NET Core and not just .NET Framework would alter the urgency in fixing it?
