### ISSUE TITLE
Add support for `--disable-build-servers` to more MSBuild-driven commands 

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#31651]
### Is your feature request related to a problem? Please describe.

In .NET 7 we added the `--disable-build-servers` option to build, restore, and publish to make it easier for developers to have complete control over the use of build servers of all kinds in their builds. Some commands that are still driven by MSBuild are missing in that set, so we should add support to ensure that there is a consistent set of behaviors across all MSBuild-driven commands.

### Describe the solution you'd like
We should add the `--disable-build-servers` option to the following commands:

* clean
* test
* run
* pack
* msbuild

**Comment by MiYanni** [comment]
Just FYI, here are the current commands using this feature:
![image](https://github.com/dotnet/sdk/assets/17788297/daebf2cd-19b2-489e-b8b2-a5ccb67fc7d4)

**Comment by MiYanni** [comment]
Looks like `dotnet list reference` uses the MSBuild SDK to get the list of project-to-project references. It doesn't run MSBuild either.

Based on what I've investigated, I'm adding the option to both `run` and `store`. Going to make some unit tests right now for it.
