### ISSUE TITLE
GenAPI can generate ambiguous call to base constructor

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#31655]
When GenAPI defines arguments to a base constructor, it uses `default!` but this can lead to an ambiguous call when the base type has constructor overloads with the same number of parameters but different types.

An example of this is the generated code for NuGet.Protocol.6.5.0:

```c#
public partial class SourcePackageDependencyInfo : Packaging.Core.PackageDependencyInfo
{
    public SourcePackageDependencyInfo(Packaging.Core.PackageIdentity identity, System.Collections.Generic.IEnumerable<Packaging.Core.PackageDependency> dependencies, bool listed, SourceRepository source, System.Uri downloadUri, string packageHash) : base(default!, default!) { }
```

This leads to the following compiler error:

```
error CS0121: The call is ambiguous between the following methods or properties: 'PackageDependencyInfo.PackageDependencyInfo(PackageIdentity, IEnumerable<PackageDependency>)' and 'PackageDependencyInfo.PackageDependencyInfo(string, NuGetVersion)
```

This can be solved by explicitly casting `default` to the desired type:

```c#
: base((Packaging.Core.PackageIdentity)default!, (System.Collections.Generic.IEnumerable<Packaging.Core.PackageDependency>)default!) { }
```

cc @andriipatsula @ViktorHofer

**Comment by ericstj** [comment]
This could not be fixed completely.   It was still broken for the case reported originally due to https://github.com/dotnet/roslyn/issues/67867

**Comment by ericstj** [comment]
And @CyrusNajmabadi already has a fix 🎉  
https://github.com/dotnet/roslyn/pull/67893

We could also workaround this with an options setting: https://github.com/dotnet/roslyn/blob/7c82cb8b2b22f239359e6183cafeed0b72b694b2/src/Workspaces/CSharp/Portable/Simplification/Reducers/CSharpDefaultExpressionReducer.Rewriter.cs#L36

But I couldn't determine how to pass that in to our use of Roslyn.  Might be interesting follow up to see about allowing users to specify an editorconfig to GenAPI for this.

**Comment by ericstj** [comment]
Fix is in https://github.com/dotnet/roslyn/pull/67893.  Once we can get a new build of roslyn with this fix in SDK we can resolve this (and re-enable the test).

**Comment by ViktorHofer** [comment]
I verified that today's dependency flow includes the necessary commit: https://github.com/dotnet/sdk/commit/8945b552db82ce8d4c3ead319d3a593c4819167f.

We should be able to enable any tests for that use-case.

**Comment by ViktorHofer** [comment]
> and re-enable the test

@ericstj which test?

**Comment by ericstj** [comment]
https://github.com/dotnet/sdk/blob/dabb52e63c2a171bdf519d2123470a260d6d1cb4/src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs#L1466

**Comment by ViktorHofer** [comment]
Cool. Do you want to send a PR to re-enable it? The roslyn change is already in the sdk.

**Comment by ericstj** [comment]
Sure, let me pull and validate and I'll put up the PR.
