### ISSUE TITLE
`dotnet workload uninstall` does not support verbosity flag

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#31684]
## Describe the bug

We were trying to figure out the underlying issue for something like:

![image](https://user-images.githubusercontent.com/840039/230915826-17ec8004-0c7e-4131-add7-02d5f0027960.png)

But you can't add `--verbosity diag` to the `uninstall` command:

    dotnet workload uninstall maui --verbosity diag
    Workload uninstallation failed: Couldn't find workload ID(s): --verbosity diag

### To Reproduce

    dotnet workload uninstall maui --verbosity diag

### Further technical details

.NET 7.0.202

**Comment by nagilson** [comment]
That's a good point and something I'm not surprised by as I didn't add any custom logging for it. We can certainly do that in another issue but it would be lower priority for us right now.
