### ISSUE TITLE
Unexpected compile error

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#31691]
**Version Used**: 

4.5.0

**Steps to Reproduce**:

There's a sample for it: 

https://github.com/WeihanLi/SamplesInPractice/blob/f1c577cb099ceec0eab09e14725a78e8c6ae579c/RoslynSample/Program.cs

.NET 8 preview SDk is required to run the sample, and just run `dotnet run` when .NET 8 SDK had been setup

The code I'm going to compile is as follows:

``` csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using WeihanLi.Common.Logging.Serilog;

var serviceCollection = new ServiceCollection()
        .AddLogging(builder => builder.AddSerilog())
    ;
await using var provider = serviceCollection.BuildServiceProvider();
provider.GetRequiredService<ILoggerFactory>()
    .CreateLogger("test")
    .LogInformation("Hello 1234");
```

it succeeds when I compile with `WeihanLi.Common.Logging.Serilog` NuGet package reference(https://github.com/WeihanLi/SamplesInPractice/blob/ca270af2db89898c26fb5b972ca38637f63bdc79/RoslynSample/Program.cs), while when I compile with additional NuGet package `Microsoft.Extensions.Http` with version `8.0.0-preview.2.23128.3`, it produces errors like follows:

![](https://user-images.githubusercontent.com/7604648/230728634-b8c9fa67-2e70-429f-b1a5-fd6b567cc6a5.png)

while the `dotnet build` works, is there some config I missed?

**Diagnostic Id**: CS1929

Seemed the main issue is I need to supply a runtime policy? The error message is really misleading.

And could I supply a runtime policy for the compile process?

**Comment by WeihanLi** [comment]
Any update for this, thanks in advance

**Comment by huoyaoyuan** [comment]
You can try to use the [structured log viewer](https://msbuildlog.com/) to diagnose. Just add the `/binlog:` switch in `dotnet run` or `dotnet build` command.

**Comment by WeihanLi** [comment]
@huoyaoyuan sure, thanks

**Comment by WeihanLi** [comment]
think this is related to the `runtime.config.json`, not related to the compiler and SDK, closing now
