### ISSUE TITLE
dotnet test without shared runtime

### ISSUE THREAD

**Issue by Rast1234** [dotnet/sdk#3170]
Currently we run our apps with heavily customized corporate docker image. We publish self-contained apps, because we deemed it too time consuming and potentially problematic to get shared runtime to run in there.
So basically we do this (extra stuff omitted) in microsoft's SDK image:
```dockerfile
RUN dotnet restore "Foo.csproj" --runtime linux-x64
RUN dotnet build "Foo.csproj" --runtime linux-x64 --no-restore 
RUN dotnet publish "Foo.csproj" --runtime linux-x64 --no-restore --self-contained
```
Then we copy results to our image and just run the binary.

Is it possible to publish and run tests the same way? I am aware that test project is not executable by itself and requires a test runner. Test runner relies on shared runtime AFAIK. Can we get a self-contained test runner somehow? Or integrate it into test project maybe?

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2013
