### ISSUE TITLE
Move Version calculation to targets

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#3173]
Currently, the .NET Core SDK initializes `Version` property during evaluation phase in `Microsoft.NET.DefaultAssemblyInfo.targets` based on the values of `VersionPrefix` and `VersionSuffix` properties. 

Consider a NuGet package that provides a optional feature that generates version based on some property set by the project. The package targets do not have the opportunity to set `VersionPrefix` since there is no extension point in between the import of .NET Core `Sdk.targets` and `Microsoft.NET.DefaultAssemblyInfo.targets`. The first available extension point is an import of "BeforeMicrosoftCommonTargets".

**Proposal**
 
Move the `Version` initialization to a target and update all usages to depend on that target. This would be a breaking change, but would also allow more complex version calculation to be performed than can be done by just evaluation. E.g. version based on git commit depth, etc.

**Alterantive**

Initialize `Version` after common targets are imported.
This would also be breaking, since the version wouldn't be initialized where it would have been before.

**Non-breaking alternative**

Add `ImportBeforeDotNetSdkTargets` property that contains a list of files to be imported from `Sdk.targets` before the rest of the SDK targets are imported. The SDK package could then add its targets file to the list in its `.props` file and set the `VersionPrefix` and `VersionSuffix` in that file. 

**Workaround**
Until one of the options above is available, we work around this in Arcade by hooking up BeforeCommonTargets and overriding all properties that were set based on `VersionPrefix` to that point.

**Comment by rainersigwald** [comment]
Is the request "I want to customize versioning, but not completely", that is, you want to use the existing logic that takes `VersionPrefix` and `VersionSuffix` and assembles version strings, but with a customized prefix/suffix?

**Comment by tmat** [comment]
@rainersigwald I don't really need to use the existing logic, but something else might before I have a chance to overwrite it might and then there will be `Version` in the system that is different from the one that I set.

**Comment by Forgind** [comment]
Old bug triage:
If you want to reset version, you can do that in your target without it needing to be set by the SDK.

If you're worried about things that rely on VersionPrefix, you can change VersionPrefix yourself as well.

If you see some scenario between these two that you think merits SDK-side changes, feel free to comment and reopen it, but since no one has commented for years, this doesn't seem like a pressing customer need.
