### ISSUE TITLE
GenAPI drops internal ctor

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#31776]
Repro: `generate.cmd -p System.Data.SqlClient,4.8.5 -x`. Look at the generated source file under ref/netcoreapp2.1:

```C#
    public sealed partial class SqlBulkCopyColumnMappingCollection : Collections.CollectionBase
    {
        public SqlBulkCopyColumnMapping this[int index] { get { throw null; } }

        public SqlBulkCopyColumnMapping Add(SqlBulkCopyColumnMapping bulkCopyColumnMapping) { throw null; }

        public SqlBulkCopyColumnMapping Add(int sourceColumnIndex, int destinationColumnIndex) { throw null; }

        public SqlBulkCopyColumnMapping Add(int sourceColumnIndex, string destinationColumn) { throw null; }

        public SqlBulkCopyColumnMapping Add(string sourceColumn, int destinationColumnIndex) { throw null; }

        public SqlBulkCopyColumnMapping Add(string sourceColumn, string destinationColumn) { throw null; }

        public new void Clear() { }

        public bool Contains(SqlBulkCopyColumnMapping value) { throw null; }

        public void CopyTo(SqlBulkCopyColumnMapping[] array, int index) { }

        public int IndexOf(SqlBulkCopyColumnMapping value) { throw null; }

        public void Insert(int index, SqlBulkCopyColumnMapping value) { }

        public void Remove(SqlBulkCopyColumnMapping value) { }

        public new void RemoveAt(int index) { }
    }
```

The internal ctor from the reference source is missing: https://github.com/dotnet/corefx/blob/b86ce69c316b4b088356b89bab80f7fa79ff799c/src/System.Data.SqlClient/ref/System.Data.SqlClient.cs#L313

Without the internal ctor the object is instantiable and with that exposes more public API than defined by the actual assembly.

**Comment by ericstj** [comment]
Looks like the old GenAPI did this here: https://github.com/dotnet/arcade/blob/aa90e21c63248b4d6d61e8de14a0d8e7a9275130/src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs#L168-L176

Which would correspond to a special case here in the new GenAPI:
https://github.com/dotnet/sdk/blob/9df7afaa2363f06c1bf9fbf464473c13a4860bef/src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs#L211

**Comment by ericstj** [comment]
Related: https://github.com/dotnet/sdk/pull/30594, https://github.com/dotnet/arcade/issues/12578

The fix for that didn't consider other cases.  Here are a few test cases that demonstrate the gap: https://github.com/dotnet/sdk/pull/31843
