### ISSUE TITLE
`dotnet tool update --install <tool>`

### ISSUE THREAD

**Issue by alexrp** [dotnet/sdk#31824]
For scripting purposes, it would be convenient to have a single way to install or update a package, such as an `--install` option for `dotnet tool update`.

As it stands, `dotnet tool install` will just fail if the package is already installed, as will `dotnet tool update` if the package isn't installed.

**Comment by WeihanLi** [comment]
I filed an issue before https://github.com/dotnet/sdk/issues/24692
And I found it works for me just use `dotnet tool update`, `dotnet tool update` would also install if the dotnet had not been installed

**Comment by alexrp** [comment]
Good catch. I misread the error from `dotnet tool update -g <tool>` (missing `--prerelease` flag). Looks like that should work. Thanks!
