### ISSUE TITLE
net472 to netstandard1.3 -> extra diagnostics dll 

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3194]
Repro steps:

* Extract [ds.zip](https://github.com/dotnet/sdk/files/3136412/ds.zip) somewhere
* `dotnet build` the `app` project
* Look at bin\Debug\net472, notice extra S.D.DiagnosticSource.dll

![image](https://user-images.githubusercontent.com/75470/57051775-f622fd00-6c37-11e9-8144-d382f6a2511d.png)

This is coming transitively from the netstandard.library 1.6.1 implicit ref in lib.csproj. Recall that netstandard1.x projects don't get privateassets="all" applied to that.

But, regardless, why does this assembly survive conflict resolution, etc. net472 should be able to consume netstandard1.x without app-local framework assemblies.

I'm not sure if this is a regression, but I'm very surprised that I haven't heard about it before, so it may well have crept in.

cc @dsplaisted @ericstj

**Comment by nguerrera** [comment]
cc @sbomer

**Comment by ericstj** [comment]
DiagnosticSource is not part of NETStandard.Library.  It is an implementation dependency of one of the libraries in NETStandard (Net.Http, I believe).

One of the things that we specified when building NS2.0 was that frameworks supporting it should bring in a reference to the NS.L 2.x library to avoid this.  @terrajobst 

Do you recall why the implicit reference is for 1.6.1 and not latest?

**Comment by nguerrera** [comment]
> One of the things that we specified when building NS2.0 was that frameworks supporting it should bring in a reference to the NS.L 2.x library to avoid this.

I'm not sure I follow. How should .NET 4.7.2, which supports NS 2.0, bring in NS.L 2.x library?

**Comment by nguerrera** [comment]
> Do you recall why the implicit reference is for 1.6.1 and not latest?

We strive to keep implicit references a deterministic function of the project (with the exception of preview-to-preview sdk builds). In the early days, bumping the NS 1.x implicit ref with SDK projects ended up breaking projects. But generally, we don't want non-determinism of the dependency graph when only the SDK changes.

**Comment by terrajobst** [comment]
@ericstj is this still something we need to fix?

**Comment by ericstj** [comment]
> How should .NET 4.7.2, which supports NS 2.0, bring in NS.L 2.x library?

Reference the package NETStandard.Library 2.x.x to upgrade the old 1.x package which removes all the dependencies.

Alternatively we go back and service NETStandard.Library 1.x packages so that they know about netstandard2.0, then have the SDK reference a new 1.x package instead.  I'm not sure how that would be better, and in fact it requires more work (including servicing).

> we don't want non-determinism of the dependency graph when only the SDK changes.

Then how do you *ever* service the implicit package reference?  Suppose we had a gnarly security bug in the closure of the reference: would that warrant updating it?

> @ericstj is this still something we need to fix?

It'd be nice to fix it, but there's an easy workaround: manually reference a newer NETStandard.Library package.  If we heard about this impacting a customer and could quantify that impact against the risk that Nick suggests I'd push harder.

**Comment by nguerrera** [comment]
> Suppose we had a gnarly security bug in the closure of the reference: would that warrant updating it?

Yes.

The move from 1.6.0 to 1.6.1 was quite painful. I can believe that going to 2.0 doesn't have the same class of issues, but that's why I'm reluctant.

**Comment by nguerrera** [comment]
(Maybe unpopular opinion, but I regret all implicit versioning. I wish that project files specified all versions and that we relied on features to tell you if you had insecure versions in your project files, and prompted you to upgrade. Even for self-contained apps.)

**Comment by nguerrera** [comment]
>  but there's an easy workaround: manually reference a newer NETStandard.Library package. If we heard about this impacting a customer and could quantify that impact against the risk that Nick suggests I'd push harder.

I agree here. I'm closing this since I haven't seen other reports and we can reopen if there are any. There are other more severe issues with the 1.6.1 reference, though. https://github.com/dotnet/sdk/issues/2261

It seems that fixing that would fix this, so I'll close and let the discussion of risk reward focus on the more severe issue.

Also, in past discussions, it seems we're ok bumping 2.0.x to latest for 2.0+ projects, but not 1.6.x -> latest for 1.x projects as 1.x projects manifest their dependency. I am actually averse to all implicit bumps in principle, but that is not what I see recorded as the policy in past issues. It also seems that 2.0.x won't actually bring substantially different dependencies to 1.x projects like 1.6.1 did over 1.6.0 so I may be overindexing on that.
