### ISSUE TITLE
dotnet watch cli command throw route ambiguity (multiple routes available)

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/sdk#31976]
When I use `dotnet watch` command to do hot reload automatically, in some cases it consider different version of one action as multiple route and It needs to restart manually. I just want to report it to get considered by other people and It can be closed if it is not an interesting case.

**Comment by abdollahkahne** [comment]
As an example to see this behaviour, consider we have an MVC application and have an action which has signature as below:
`public IActionResult GetStudents(SearchViewModel model) {} `and try to use this endpoint from an ajax request on the client side. Then due to some problem you may consider that the argument here should be bind FromBody and change the signature as below:
`public IActionResult GetStudents([FromBody] SearchViewModel model) {} `
This time it consider the action as new route in route table and thrown an error due to route ambiguity.

**Comment by tmat** [comment]
Tracked by https://github.com/dotnet/runtime/issues/75154
