### ISSUE TITLE
Internal error: new deps file generation did not produce the same result as the old logic

### ISSUE THREAD

**Issue by imsmart-tech** [dotnet/sdk#3204]
Got this error which said to file issue here. So here it goes.

[ImSmart.deps.json.txt](https://github.com/dotnet/sdk/files/3146159/ImSmart.deps.json.txt)

[ImSmart.deps.new.json.txt](https://github.com/dotnet/sdk/files/3146160/ImSmart.deps.new.json.txt)

**Comment by livarcocc** [comment]
Dupe of https://github.com/dotnet/sdk/issues/3146
