### ISSUE TITLE
GenAPI drops internal ctor which results in compilation errors

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#32119]
Microsoft.DotNet.GenAPI.Task/8.0.100-preview.5.23228.4 drops the following API: https://github.com/dotnet/runtime/blob/e6f9af1361030fca92abe58efed1ea45d2eb552c/src/libraries/System.IO.Packaging/ref/System.IO.Packaging.cs#L180

I verified that the latest changes are part of the used GenAPI version. A repro in the source-build-reference-packages repo:
```sh
./generate.sh --package "System.IO.Packaging,7.0.0" --excludeDependencies
./build.sh
# The above command failed for me at some point so I then built the generated project manually:
.dotnet/dotnet build /home/vihofer/git/source-build-reference-packages/src/referencePackages/src/system.io.packaging/7.0.0/System.IO.Packaging.7.0.0.csproj
```

Parameters used for invoking the GenAPI task:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/7412651/235175403-28079698-82eb-4de6-9c64-67480d02ecf0.png">

cc @ericstj @andriipatsula

**Comment by ericstj** [comment]
GenAPI is loads assemblies with MetadataImportOptions.Public (the default) so it only sees public API.  All the GenAPI tests, however, are getting metadata from a compilation, so they see all API.  For this reason tests are passing but this case still fails.

This also means that our support for `IncludeVisibleOutsideOfAssembly` was completely broken.
