### ISSUE TITLE
Restore doesn't warn when restoring older pre 3.0 aspnet dependencies on netcore 3.0 resulting in TypeLoadExceptions

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/sdk#3213]
Running on dotnet core 3.0.100-preview5 sdk while firing off a first request to aspnetcore 3.0.

`dotnet restore` issues zero warnings when you try to restore projects with dependencies that reference older AspNetCore (sdk backed PackageReference) versions. Ran across this while updating one of our solutions where we have a dependency on `FluentValidation.AspNetCore` which depends on `Microsoft.AspNetCore.Mvc 2.2.0`

This is what's referenced in the deps.json of a succesfully built preview5 project:
```
      "FluentValidation.AspNetCore/8.3.0": {
        "dependencies": {
          "FluentValidation": "8.3.0",
          "FluentValidation.DependencyInjectionExtensions": "8.3.0",
          "Microsoft.AspNetCore.Mvc": "2.2.0"
        },
```

Stacktrace snippet 
```
      Connection id "0HLMJBP255QDV", Request id "0HLMJBP255QDV:00000001": An unhandled exception was thrown by the application.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' from assembly 'FluentValidation.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
```

I don't think this is what you want to RTM with right?

**Comment by NinoFloris** [comment]
Not to be rude but the blunt answer would be:

"That's your problem, you got yourselves in this mess with those fake 2.x AspNetCore packages and now that it's fixed properly it'll come back and bite you some more."

Since `FrameworkReference` is a thing now, meaning it won't participate in package resolution at all, you're going to see a long tail of package issues where those still reference parts of asp.net core 2.x (if only for compatibility with those versions). 

The least the sdk can do is special case these fake packages for 3.0 TFMs and warn that it'll probably not do what you expect.

**Comment by NinoFloris** [comment]
Github is showing comments from the future and rearranging answers, cool!
<img width="836" alt="Screenshot 2019-05-08 at 16 27 52" src="https://user-images.githubusercontent.com/4218809/57382978-40fbc200-71ae-11e9-8009-fb6c2c253c61.png">

**Comment by rrelyea** [comment]
Ok, so you think the sdk might be able to detect these kind of cases?

From nuget, all we understand is TFMs.
And I don’t think this is breaking any TFM rules.
Unless there is another clue we should pay attention to?

On phone now, but should probably port to sdk repo.

**Comment by NinoFloris** [comment]
@rrelyea this is the sdk repo ^_^ 

Changed the title earlier accordingly, it's indeed not entirely the responsibility of nuget (and cannot even be due to FrameworkReference) but I believe fundamentally an msbuild target in the restore process should be able to take a look at the final situation and warn on these cases. Possibly, and I'm no expert on all the sdk targets, if project TFM hierarchies are a problem it could even only be done during netcoreapp3.0 Microsoft.NET.Sdk.Web sdk projects. This is definitely a case where anything, however constrained by the need for zero false positives, is better than nothing.

**Comment by NinoFloris** [comment]
P.S. would you mind deleting your first comment when Github experienced that time glitch? It keeps popping below newer comments.

**Comment by livarcocc** [comment]
I am not sure this is something that we should absolutely do, as in, not sure we will have enough context to really understand this is the situation that is happening here.

cc @dsplaisted who may have some idea or may confirm that this is the way things are.

**Comment by dsplaisted** [comment]
This looks to me like a breaking change in the MVC APIs.  @natemcmaster do you know if this is the case?

We have dotnet/cli#10105 which could trim out the MVC package reference, but even without that we expect that the 2.x DLLs would go through conflict resolution and lose to the same DLLs from the 3.0 shared framework.

**Comment by natemcmaster** [comment]
@NinoFloris I don't have code to reproduce your issue, but based on a cursory inspection of https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore, it looks like this might be the cause: https://github.com/aspnet/Announcements/issues/326.

To test my theory out, try updating FluentValidation.AspNetCore to compile for netcoreapp3.0 with a `<FrameworkReference>` to Microsoft.AspNetCore.App

```xml
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netcoreapp3.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0' ">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0" />
  </ItemGroup>
```

**Comment by NinoFloris** [comment]
@natemcmaster in the name of science I might try this in a bit but would it matter though? 
I'm just a consumer of his package running on netcoreapp3.0. Therefore shouldn't I get a warning or error when I try to consume a package that references `Microsoft.AspNetCore.Mvc` < 3.0?

**Comment by rrelyea** [comment]
How should nuget detect this problem?

**Comment by natemcmaster** [comment]
> Therefore shouldn't I get a warning or error when I try to consume a package that references Microsoft.AspNetCore.Mvc < 3.0?

This idea came up a few weeks ago when chatting with @DamianEdwards. We don't have plans for issuing warnings or errors at the moment. The SDK has some conflict resolution built-in which will automatically hoist you to the right version of MVC.

That said, there is certainly an opportunity here for the SDK or NuGet to tell you when a PackageReference is unnecessary to keep in your .csproj file. This feature could apply to more than just the MVC package. In .NET Core 1.x days, there were dozens of System.* packages. Since .NET Standard 2.0 and .NET Core 2.0, those packages are almost always unnecessary to reference directly. The SDK and NuGet just silently ignore those package refs. AspNetCore 3.0 is going through the same transition now as we consolidate hundreds of Microsoft.AspNetCore.* packages into a single `<FrameworkReference>` .

But even if we did something like issue a warning about using a 2.1 MVC reference in a 3.0 package, you would still have runtime errors due to https://github.com/aspnet/Announcements/issues/326 unless you recompile for .NET Core 3.0.

**Comment by NinoFloris** [comment]
@natemcmaster I'm afraid I don't quite follow or that we're talking past each other. 
Mind you I'm not the author of the package, just a consumer of it on netcoreapp3.0.

>The SDK has some conflict resolution built-in which will automatically hoist you to the right version of MVC.

I read a bit of this doc before writing this https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/framework-version-resolution.md#scenarios-with-known-issues I hope it still reflects the current state of the world. 

The conclusion I essentially came to was the following:
- FrameworkReferences are subject to specific, configurable, runtime resolution as laid out in the documented I linked to.
- FrameworkReferences have some sdk design time/build time conflict resolution as you explained.

What surprises me is that these defaults don't seem to match in the compatibility level they provide.
Let's look at the default runtime roll-forward resolution, "Minor" being defined as: 
>Minor (default) -- Roll forward to the lowest higher minor version, if requested minor version is missing. If the requested minor version is present, then the LatestPatch policy is used. 
`Microsoft.AspNetCore.App` provides no setting, and so uses this default policy.

During build time however the sdk is happily unifying the 2.x reference that was pulled in by `FluentValidations` with my own 3.x reference pulled in via `Sdk.Web`. A major roll forward from the perspective of the compiled FluentValidation dependency I included.
 
As you stated ASP.NET Core 3.0 broke compatibility with 2.x quite some places. Binary and source compatibility is broken for some public surface, and I would say not unsurprising considering it's a major version release.
https://github.com/aspnet/Announcements/issues?q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22

How is it that the runtime resolution policy defaults in place are stricter than what we have during build time today? Arguably the former — especially considering container use being popular with .net core — won't even be used all that much.
 
_I understand that runtime resolution has stricter compatibility requirements than build time, mainly around binary compatibility. That doesn't change the binary compatibility needs of my dependencies, like FluentValidation requiring 2.x during build time though. (One of the biggest perks hybrid source builds like nix have)_

It could be reasoned the right build time requirements aren't all that different from runtime requirements.

Why then are their successful resolution tolerances so dissimilar?

This is the situation as I'm understanding it and why I'm confused. Now I might very well not understand or know certain details and rationale. If so please tell me, it would be much appreciated.

**Comment by natemcmaster** [comment]
> I'm afraid I don't quite follow or that we're talking past each other.

What is confusing you? Your latest comment went in an unexpected direction, and I'm not sure what you are asking for. 

The situation here, as I understand it, is that you are trying to use FluentValidation.AspNetCore 8.3.0. This was compiled to use an ASP.NET Core 2.1 API which was removed in ASP.NET Core 3.0. As a result, FluentValidation.AspNetCore does not work on when used in an ASP.NET Core 3.0 project, and FluentValidation.AspNetCore will need to be recompiled to use the replacement APIs.

**Comment by NinoFloris** [comment]
This would be my main question then

How is it that the runtime resolution policy defaults in place are stricter than what we have during build time today? Arguably the former — especially considering container use being popular with .net core — won't even be used all that much.

**Comment by natemcmaster** [comment]
I don’t know how to answer your question. I’m interested in helping, but the behavior you’ve just commented on is a fundamental behavior of .NET and dynamic linking.

The way I see it, the origin of this thread was a breaking change that ASP.NET Core made in 3.0. My team is reviewing all of our breaking changes right now and looking to see if we can make PRs to the top community projects affected by our breaking changes. FluentValidator.AspNetCore appeared in the list of these top packages. No promises that we’ll fix this for people, but we’re aware breaking changes have an impact and are trying to mitigate them.
