### ISSUE TITLE
GenAPI emits default constructors when reading from metadata

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#32165]
### Describe the bug
GenAPI emits default constructors when they are not needed.

### To Reproduce
```c#
public partial class Class1 { }
```
Compile this and point GenAPI to it.

Expect: no constructor emitted since it isn't required.
Actual:
```c#
    public partial class Class1
    {
        public Class1() { }
    }
```

### Further technical details
The problem appears to be that when reading from metadata the roslyn API doesn't set the `IsImplicitlyDeclared` flag.  This could be because it cannot determine if the default constructor was implicit or explicit from metadata alone.

If we wanted to fix this, we might be able to filter the constructor ourselves, if we see that it is parameter-less, has expected visibility (public, protected for abstract classes, etc), and calls the default base constructor.

**Comment by ViktorHofer** [comment]
Should this issue have been closed with https://github.com/dotnet/sdk/pull/32276?

**Comment by ericstj** [comment]
No the tool still emits the constructor when reading from metadata.  I think we may just want to keep that behavior though.

**Comment by ViktorHofer** [comment]
Agreed and we just recently talked about this. Let's close the issue as not planned.
