### ISSUE TITLE
Razor Component onClick with arguments

### ISSUE THREAD

**Issue by genifycom** [dotnet/sdk#3216]
In the sample FetchData.razor how does one call the onclick event with an object.

e.g.

  <tbody>
        @foreach (var forecast in forecasts)
        {
            <tr>
                <td onclick="@EditForecast(forecast)">@forecast.Date.ToShortDateString()</td>
                <td>@forecast.TemperatureC</td>
                <td>@forecast.TemperatureF</td>
                <td>@forecast.Summary</td>
            </tr>
        }
    </tbody>
...

@functions {
  private void EditForecast(WeatherForecast forecast)
  {
    //Do something with forecast
  }
}

**Comment by livarcocc** [comment]
This is not the right repo for this. Please, file a new issue on aspnet/home for it.
