### ISSUE TITLE
Internal Error: new deps file generation logic did not produce the same result as the old logic.

### ISSUE THREAD

**Issue by jdavidbambrick** [dotnet/sdk#3220]
Added an new publishing profile - a new folder, under the existing one ... and go this error asking me to post it back to git hub... so here ya go...

[netcoreapp3.0.zip](https://github.com/dotnet/sdk/files/3163329/netcoreapp3.0.zip)

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/sdk/issues/3146.
