### ISSUE TITLE
.NET SDK first run experience should be OS-specific

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#32322]
From first-run.

```bash
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
```

This is from Linux. We should use `#if` for these cases. There should be no need to get the user to say "oh, does this message apply to me on my current OS." We can do that for them.

I'm also assuming this is wrong. We don't auto install an HTTPS dev cert on Linux, do we?

**Comment by marcpopMSFT** [comment]
This is in the first run code and since I asked you to take on the first run workload work, this might be a good intro bug for that code.

**Comment by MiYanni** [comment]
@richlander I checked the code. This message is baked in, independent if the cert actually gets installed or not. Also, looked into the cert mechanism and if you're *not* on Windows or Mac, it defaults to using a Unix installer for the cert:
https://github.com/dotnet/aspnetcore/blob/2fbeeafbafd44d4e44dcc1f676dfcba642a5314e/src/Shared/CertificateGeneration/CertificateManager.cs#L33-L39

Technically, if you follow the "Learn about HTTPS" link, it tells you what you need to run for Linux: https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?#trust-https-certificate-on-linux

I think the part of the message that says "(Windows and macOS only)" applies to the `--trust` argument. The steps for Linux still use `dotnet dev-certs https` and the separate steps after that.

@baronfel Any suggestions on how to message this better to avoid confusion?

**Comment by baronfel** [comment]
@MiYanni good find. The message is hard coded, and I think it should be factored out and printed out in a more granular fashion.  Here's the message string today:

```shell
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
```

I think we should split this into two sections - an ASP.NET section (with a variable 'command' portion in the middle that may or may not ask the user to trust a cert) and a 'getting started' section. The code that prints this should get a bit more specific as well. The current logic is

```
if print_first_time
then
  run_nuget_migrations
  print_welcome_message
  print_telemetry_message
  print_more_information
fi

if generate_aspnet_cert
then
  generate_and_trust_cert
fi
```

This should change to cache the result of the `print_first_time` check, then use it to 

* run nuget migration
* print telemetry messages

Then, separately check if the aspnet certificate should be generated, and if so generate that cert. After cert generation, if `print_first_time` was true, then print an OS-specific trust command. Finally the 'more information' section should be printed if `print_first_time` was true
