### ISSUE TITLE
dotnet publish --runtime RID should print a good error message if the RID hasn't been restored

### ISSUE THREAD

**Issue by jgoshi** [dotnet/sdk#324]
If the RID hasn't been restored, we should raise an error is raised telling you to add the RID to the .csproj and run restore again.

See the following issue for more context:
https://github.com/NuGet/Home/issues/3768#issuecomment-256164196

**Comment by livarcocc** [comment]
This also happens if you pass an invalid rid. It simply fails with a restore hasn't happened error.

```
dotnet publish -r "non_existent_rid"
```
