### ISSUE TITLE
GenAPI produces TupleElementNamesAttribute reference in addition to the tuple itself

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#32458]
When using GenAPI on the Microsoft.CodeAnalysis.Common.4.5.0, it produces the following code snippet for the `IncrementalGeneratorRunStep` class:

```C#
[System.Runtime.CompilerServices.TupleElementNames(new[] { "Source", "OutputIndex" })]
public System.Collections.Immutable.ImmutableArray<(IncrementalGeneratorRunStep Source, int OutputIndex)> Inputs { get { throw null; } }
```

This produces the following compiler error:

```
error CS8138: Cannot reference 'System.Runtime.CompilerServices.TupleElementNamesAttribute' explicitly. Use the tuple syntax to define tuple names.
```

Removal of the generated attribute corrects the problem.

Related: https://github.com/dotnet/arcade/issues/2028

**Comment by ViktorHofer** [comment]
@ericstj should this be closed now?

**Comment by ViktorHofer** [comment]
Fixed via https://github.com/dotnet/sdk/pull/33888
