### ISSUE TITLE
AOT compiling/publishing from Visual Studio post build event create endless loop of dotnet calls

### ISSUE THREAD

**Issue by Scavanger** [dotnet/sdk#32512]
### Describe the bug
When ```dotnet publish```, to compile a project as native binary (AOT), is called from a Visual Studio post build event, it produces an endless loop of dotnet calls.
Seems like the same behaviour as in #6735, but the option  ```--no-build``` is useless in this case
 
### To Reproduce
Create a .net project with AOT enabled, and set dotet publish as post build event, for example
```dotnet publish /p:NativeLib=Shared -r win-x64 -c Debug```

### Further technical details
.NET 8 Preview 3
Visual Studio 2022

**Comment by marcpopMSFT** [comment]
Running dotnet in a post-build step is not supported. Unfortunately, it sounds like you want AOT publish as part of the build in VS and I don't know of a supported way to do this. --no-build works for pack as it doesn't end up needing to rerun anything from the build but publish more heavily relies on an exactly matching build and so it probably triggering a build anyway.
