### ISSUE TITLE
Project with PackAsTool and GeneratePackageOnBuild set to true fails to build

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#3253]
Tests in `GivenThatWeWantToPackAToolProjectWithGeneratePackageOnBuild` are failing with:

> C:\git\dotnet-sdk\artifacts\bin\Debug\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(337,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "_WalkEachTargetPerFramework". [C:\git\dotnet-sdk\artifacts\tmp\Debug\It_builds_suc---81F3C59C\App\consoledemo.csproj]

This regressed with a recent NuGet insertion.

**Comment by dsplaisted** [comment]
We need to make sure to re-enable these tests once we fix the bug.

**Comment by wli3** [comment]
regressed due to NuGet/NuGet.Client#2822

cc @nkolev92 @peterhuene
