### ISSUE TITLE
$(TargetVersionFramework) is empty when using <TargetVersionFrameworks>

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#32536]
My builds started failing on 5/11 with this error message:

```
sdk\8.0.100-preview.5.23261.2\Containers\build\Microsoft.NET.Build.Containers.targets(14,5): error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals('', 8.0)" cannot be evaluated. Version string was not in a correct format.
```

When the .csproj contains `<TargetFrameworks>net8.0</TargetFrameworks>` it fails. With `<TargetFramework>net8.0</TargetFramework>` it works.

It worked fine with `8.0.100-preview.5.23260.3` and previous versions, and started failing with `8.0.100-preview.5.23261.2`.

**Comment by baronfel** [comment]
Closing as duplicate, fixed already inhttps://github.com/dotnet/sdk/pull/32456. This is available in 7.0.4xx nightlies and should be merged into main today.
