### ISSUE TITLE
[NETSDKE2E]With .NET 8 preview 5 SDK installed, the help description for "--sc, --self-contained" option should be updated as the default is 'false' now if a runtime identifier is specified.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#32549]
1.Install .NET 8 SDK (8.0.100-preview.5.23265.7) from main branch of https://github.com/dotnet/installer
2.In CLI
dotnet new console -o 80console
dotnet publish -r win-x64
3. Check publish path
4.dotnet publish --help

**Expected Result:**
Steps 3: the files in publish path can be displayed well.
Step4: the help description can be displayed well.

**Actual Result**
Steps 3: the files in publish path can be displayed well. **it's framework dependent publishing**. But in dotnet publish --help(Step4), the help description for "--sc, --self-contained" option is the default is '**true**' if a runtime identifier is specified.

![image](https://github.com/dotnet/sdk/assets/65637796/64af4d48-ac36-4c7e-a4f8-50583db099c8)

**Comment by dsplaisted** [comment]
@nagilson, can you take this?

**Comment by nagilson** [comment]
Definitely!

**Comment by nagilson** [comment]
Good catch, thanks @vdanche !

**Comment by vdanche** [comment]
This issue has been fixed on 8.0.100-preview.5.23272.48(runtime-8.0.0-preview.5.23272.3) SDK
![image](https://github.com/dotnet/sdk/assets/65637796/564ef457-1432-488a-b1a8-ca1d3590b083)
