### ISSUE TITLE
Dotnet publish command fails after updating to dotnet SDK 7.0.302

### ISSUE THREAD

**Issue by mfisher214** [dotnet/sdk#32648]
After upgrading from dotnet SDK version 7.0.203 to 7.0.302, out Azure pipeline builds have started failing on dotnet publish command with message "Could not copy the file <Project name>.deps.json". Looks like those deps.json files are not getting copied during the build phase

For the moment we have fixed our builds by changing the SDK version from 7.0.x to 7.0.203

We have also started seeing this issue locally after installing the latest Visual Studio update 17.6.0, which pulls in the 7.0.302 SDK version as well. Any suggestions as to why deps.json files may not be copied to output directory during build?

**Comment by mfisher214** [comment]
One additional detail here: as part of our build process we run the build and publish as separate steps. Ex. run "dotnet build -c Release" and then "dotnet publish -c Release --no-build"

But if I just run "dotnet publish -c Release" as one step without the --no-build option, this command runs fine

**Comment by mfisher214** [comment]
No, after running a "dotnet build -c Release", one of our projects is missing a deps.json file.

If it helps, some details about the project structure are we have 3 projects such that project A and B both have a reference to project C, project C is the one missing a deps.json file, and all 3 projects are being output to the same directory.

**Comment by vitek-karas** [comment]
How do you reference project C? Anything special about it?

> all 3 projects are being output to the same directory.

You do this by changing `OutputPath`, or it just so happens because of the references?

**Comment by mfisher214** [comment]
Looks like the error I was running into has been resolved by dotnet SDK version 7.0.304 - I am going to go ahead and mark this as resolved.
