### ISSUE TITLE
Verbiage of success message on 32bit .NET Core 2.2 SDK has wrong folder location

### ISSUE THREAD

**Issue by run1206** [dotnet/sdk#3267]
After the 32-bit .NET Core 2.2 SDK finishes installing, the success message reads:
"The following were installed at C:\Program Files\dotnet..."
The SDK files are correctly saved in the 32-bit location, but the folder location in the message is for the 64-bit SDK location.

Please see attached image for reference.
![20190525_192301](https://user-images.githubusercontent.com/16143658/58375537-50576b00-7f23-11e9-8ea4-762ea46fa727.jpg)

Success message should point to "C:\Program Files (x86)\dotnet\" for the 32bit installer.

**Comment by livarcocc** [comment]
cc @johnbeisner

**Comment by johnbeisner** [comment]
Checking 3.0:
![image](https://user-images.githubusercontent.com/24683167/58737622-30a6c380-83b7-11e9-909a-a0df382be702.png)

**Comment by johnbeisner** [comment]
Checking 2.2:
![image](https://user-images.githubusercontent.com/24683167/58737777-bb87be00-83b7-11e9-92e3-f43affc4f041.png)
