### ISSUE TITLE
`wasi-experimental` doesn't support Linux Arm64

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#32686]
My experience (on Mac M1).

```bash
% docker run --rm -it mcr.microsoft.com/dotnet/sdk:8.0-preview
$ uname -a
Linux d99826f096b5 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux
$ dotnet workload install wasi-experimental
Workload ID wasi-experimental isn't supported on this platform.
```

Linux Arm64 is required in order to use the `wasi-experimental` workload within Docker on Mac M1.

Separately, it looks like this [Dockerfile](https://github.com/SteveSandersonMS/spiderlightning-dotnet/blob/main/docker/Dockerfile) won't work on Mac M1 even if the workload is supported because:

- Slight doesn't have a Linux Arm64 build: https://github.com/deislabs/spiderlightning/releases
- Wasi-sdk doesn't have a Linux Arm64 build: https://github.com/WebAssembly/wasi-sdk/releases

In terms of scenarios, getting slight supported on Arm64 seems the most important since that enables runtime scenarios as well.

**Comment by dsplaisted** [comment]
@richlander @steveisok @lewing Is this still an issue?

**Comment by steveisok** [comment]
Yes, it is still an issue.  Although we are officially building wasi for linux-arm64, we have yet to produce wasi packs.  If we're able to work through CI issues, that may still happen in .NET 8.

**Comment by lewing** [comment]
this was fixed in https://github.com/dotnet/runtime/pull/89068 in July
