### ISSUE TITLE
platform version is not present for one or more target frameworks

### ISSUE THREAD

**Issue by Mikerad1** [dotnet/sdk#32720]
### Description
I was running SDK 7.0.202 and then my Blazor Hybrid project started to fail because of some iOS package version error in Microsoft.Identity.Client so I updated all my nuget packages. Still had the issue and so i upgraded my dotnet SDK to the latest and now I am getting the error in the title

### Configuration
Which version of .NET is the code running on?
7.0.302

Also it is a Blazor Hybrid app

### Regression?
My project didnt get this error until I upgraded my SDK, but dont know if it is a regression or not

### Other information
The info from the troubleshooting step from: https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70#it-was-not-possible-to-find-any-installed-net-core-sdks
![image](https://github.com/dotnet/core/assets/9799136/6977c050-bd72-4f7a-be04-5b8fbad977b4)

The error specifically is: 
NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-android, net7.0-ios, net7.0-maccatalyst

**Comment by nagilson** [comment]
May you post `dotnet --info`? If you are able to get back into the state where the iOS package version exists and share the error, that'd also be helpful information. Is that the full NU1012 error? It'd be helpful if you can share what command you're running that's failing as well.

**Comment by Mikerad1** [comment]
Hi @nagilson,

Sorry for the delay. Here is the information as requested, though the issue seems to not exist anymore. I'm not getting this error and I'm not sure what changed

`.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download`

Cant remember what the full error is anymore, sorry. but it mentioned something about not finding something for iOS and mac-catalyst.

**Comment by nagilson** [comment]
No worries! I mean, if we've fixed it then that's the best scenario really... if it comes back again please let us know the error and we can re open this!
