### ISSUE TITLE
[NETSDKE2E][Loc]With .NET 8 preview 5 SDK installed, the help description for "--sc, --self-contained" option is not consistent with EN.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#32753]
1.Install .NET 8 SDK (8.0.100-preview.5.23272.48(runtime-8.0.0-preview.5.23272.3)) from main branch of https://github.com/dotnet/installer on Loc OS
2.In CLI, dotnet publish --help
3.Check the help description for "--sc, --self-contained" option

**Expected Result:**
The help description for "--sc, --self-contained" option should be consistent with EN

**Actual Result;**
The help description for "--sc, --self-contained" option is not consistent with EN.
 
EN:
![image](https://github.com/dotnet/sdk/assets/65637796/709f27bb-0b64-4058-bc04-e35bbd250468)

Chinese:
![image](https://github.com/dotnet/sdk/assets/65637796/b766ef09-9f20-4549-acd9-1f9f2e37a14f)

Turkish:
![image](https://github.com/dotnet/sdk/assets/65637796/5ce8330c-e9c3-4c69-9b8a-25c98c84ae60)

**Comment by marcpopMSFT** [comment]
.NET 8 localization will come in ~August

**Comment by vdanche** [comment]
This issue has been fixed on 8.0.100-rc.2.23456.6(runtime- 8.0.0-rc.2.23431.9) 
Chinese:
![image](https://github.com/dotnet/sdk/assets/65637796/7ce32af6-029d-43b3-9814-5a16d23e623f)
German:
![image](https://github.com/dotnet/sdk/assets/65637796/ffaf1139-b380-4a35-90a3-ca1a95f82dbc)
