### ISSUE TITLE
SatelliteResourceLanguages doesn't filter resources from Publish output when targeting .NET Core 3.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#3277]
Publish the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <SatelliteResourceLanguages>en;de;pt</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer" Version="2.6.2" />
  </ItemGroup>
</Project>
```

## Expected

Publish folder should only have resource subfolders for `de` and `pt`.

## Actual

The publish folder will include the Humanizer resources for all languages the package supports:

![image](https://user-images.githubusercontent.com/145043/58606671-4f8b4580-8251-11e9-9e22-593e29ceab4d.png)

## Notes

When targeting .NET Core 2.2, the publish output is correctly filtered.  Also, when targeting .NET Core 3.0, the build output is correctly filtered, but the publish output is not.

FYI @peterhuene @livarcocc, we should fix this for 3.0

**Comment by peterhuene** [comment]
Weird, I'm pretty sure we had existing tests to cover this so that the publishing changes wouldn't regress it.

I'll look into this.

**Comment by peterhuene** [comment]
I have a fix, but now I need to figure out why the test that should cover this hasn't been failing.

**Comment by peterhuene** [comment]
Note that once we can finally eliminate the old publish logic we can remove all this unpleasantness.
