### ISSUE TITLE
Downlevel wasm tests fail on net6.0.x runtime pack download

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#32864]
Now that we are testing the workload version that matches the runtime update we hit the problem that updating the downlevel runtime packs ahead of release breaks some wasm tests.  There aren't any really good ways to make it work but we could potentially work around it by doing something something like setting the downlevel KnownRuntimePack back to the sdk implicit version for the tests, it isn't correct but it is unlikely to fail in practice.

The specific problem in this case is that 6.0.18 has not been released and as such is not available in the nuget feeds used here

**it is fine to merge on red `release/8.0-preview5` wasm failures that match this issue**

You can verify that all the failures match this issue by looking at the build analysis tab in the CI results (e.g. https://github.com/dotnet/sdk/pull/32862/checks?check_run_id=13800675240)

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=287873
Build error leg or test failing: Microsoft.NET.Sdk.BlazorWebAssembly.Tests.BlazorLegacyIntegrationTest60.Build60Hosted_Works
Pull request: https://github.com/dotnet/sdk/pull/32862

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to find package Microsoft.NETCore.App.Runtime.Mono.browser-wasm with version (= 6.0",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[326538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326538)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326538&view=ms.vss-test-web.build-test-results-tab&runId=6721532&resultId=103406)|dotnet/sdk#33733|
|[326539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326539)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326539&view=ms.vss-test-web.build-test-results-tab&runId=6721446&resultId=103406)||
|[326004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326004)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=326004&view=ms.vss-test-web.build-test-results-tab&runId=6707712&resultId=103406)||
|[325964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325964)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325964&view=ms.vss-test-web.build-test-results-tab&runId=6707076&resultId=103406)|dotnet/sdk#33712|
|[325958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325958)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325958&view=ms.vss-test-web.build-test-results-tab&runId=6706998&resultId=103406)||
|[325935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325935)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325935&view=ms.vss-test-web.build-test-results-tab&runId=6706156&resultId=103406)|dotnet/sdk#33710|
|[325932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325932)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325932&view=ms.vss-test-web.build-test-results-tab&runId=6705994&resultId=103406)||
|[325893](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325893)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325893&view=ms.vss-test-web.build-test-results-tab&runId=6705012&resultId=103406)||
|[325821](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325821)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325821&view=ms.vss-test-web.build-test-results-tab&runId=6703844&resultId=103406)|dotnet/sdk#33707|
|[325723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325723)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=325723&view=ms.vss-test-web.build-test-results-tab&runId=6700422&resultId=103406)|dotnet/sdk#33706|
|[324976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324976)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324976&view=ms.vss-test-web.build-test-results-tab&runId=6678712&resultId=103406)|dotnet/sdk#33673|
|[324836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324836)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324836&view=ms.vss-test-web.build-test-results-tab&runId=6675930&resultId=103406)|dotnet/sdk#33633|
|[324525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324525)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324525&view=ms.vss-test-web.build-test-results-tab&runId=6669796&resultId=103386)|dotnet/sdk#33673|
|[324459](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324459)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324459&view=ms.vss-test-web.build-test-results-tab&runId=6667662&resultId=103406)||
|[324380](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324380)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324380&view=ms.vss-test-web.build-test-results-tab&runId=6666050&resultId=103406)|dotnet/sdk#33640|
|[324309](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324309)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324309&view=ms.vss-test-web.build-test-results-tab&runId=6664068&resultId=103406)||
|[324292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324292)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324292&view=ms.vss-test-web.build-test-results-tab&runId=6663344&resultId=103406)|dotnet/sdk#33633|
|[324165](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324165)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324165&view=ms.vss-test-web.build-test-results-tab&runId=6660430&resultId=103406)|dotnet/sdk#33633|
|[324011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324011)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=324011&view=ms.vss-test-web.build-test-results-tab&runId=6657368&resultId=103406)|dotnet/sdk#33640|
|[323861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323861)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323861&view=ms.vss-test-web.build-test-results-tab&runId=6654168&resultId=103406)|dotnet/sdk#33640|
|[323848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323848)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323848&view=ms.vss-test-web.build-test-results-tab&runId=6654022&resultId=103406)|dotnet/sdk#33660|
|[323805](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323805)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323805&view=ms.vss-test-web.build-test-results-tab&runId=6652880&resultId=103406)|dotnet/sdk#33656|
|[323475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323475)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323475&view=ms.vss-test-web.build-test-results-tab&runId=6644040&resultId=103406)|dotnet/sdk#33641|
|[323335](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323335)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323335&view=ms.vss-test-web.build-test-results-tab&runId=6640934&resultId=103406)|dotnet/sdk#33633|
|[323320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323320)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323320&view=ms.vss-test-web.build-test-results-tab&runId=6640694&resultId=103406)|dotnet/sdk#33640|
|[323259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323259)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323259&view=ms.vss-test-web.build-test-results-tab&runId=6639148&resultId=103406)|dotnet/sdk#33641|
|[323211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323211)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323211&view=ms.vss-test-web.build-test-results-tab&runId=6637786&resultId=103406)|dotnet/sdk#33640|
|[323188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323188)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323188&view=ms.vss-test-web.build-test-results-tab&runId=6636762&resultId=103406)||
|[323078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323078)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323078&view=ms.vss-test-web.build-test-results-tab&runId=6633722&resultId=103406)|dotnet/sdk#33640|
|[323074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323074)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323074&view=ms.vss-test-web.build-test-results-tab&runId=6633682&resultId=103406)||
|[323050](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323050)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323050&view=ms.vss-test-web.build-test-results-tab&runId=6633412&resultId=103406)|dotnet/sdk#33633|
|[323016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323016)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323016&view=ms.vss-test-web.build-test-results-tab&runId=6632340&resultId=103406)|dotnet/sdk#33639|
|[322826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322826)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322826&view=ms.vss-test-web.build-test-results-tab&runId=6628020&resultId=103383)|dotnet/sdk#33636|
|[322696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322696)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322696&view=ms.vss-test-web.build-test-results-tab&runId=6631358&resultId=103406)|dotnet/sdk#33629|
|[322782](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322782)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322782&view=ms.vss-test-web.build-test-results-tab&runId=6629562&resultId=103406)|dotnet/sdk#33633|
|[322820](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322820)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322820&view=ms.vss-test-web.build-test-results-tab&runId=6627744&resultId=103406)||
|[322557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322557)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=322557&view=ms.vss-test-web.build-test-results-tab&runId=6621264&resultId=103406)|dotnet/sdk#33597|
|[321926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321926)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321926&view=ms.vss-test-web.build-test-results-tab&runId=6606688&resultId=103406)|dotnet/sdk#33597|
|[321753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321753)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.1.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321753&view=ms.vss-test-web.build-test-results-tab&runId=6602626&resultId=103406)|dotnet/sdk#33597|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|39|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=324165
**Error message validated:** `Unable to find package Microsoft.NETCore.App.Runtime.Mono.browser-wasm with version (= 6.0`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 9:03:03 PM UTC

**Comment by lewing** [comment]
cc @mmitche @dkurepa @dotnet/domestic-cat

**Comment by marcpopMSFT** [comment]
@lewing did this get fixed? I thought I saw something about this but can't find it now.

**Comment by radical** [comment]
I think this is relevant - https://github.com/dotnet/emsdk/pull/351 . It changed the version to 6.0.16 .

**Comment by steveisok** [comment]
> @lewing did this get fixed? I thought I saw something about this but can't find it now.

I could be wrong, but I don't believe it has been fixed.
