### ISSUE TITLE
Getting package assets cache messages on build with the latest master bits

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/sdk#3287]
@nguerrera, @dsplaisted: I started getting loads of messages during build in the winforms-designer repo after updating to the most recent SDK:

```
C:\Program Files\dotnet\sdk\3.0.100-preview6-012135\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5):
message NETSDK1062: Unable to use package assets cache due to I/O error . This can occur when the
same project is built more than once in parallel. Performance may be degraded,  but the build result will 
not be impacted. [D:\Projects\winforms-designer\src\WinFormsSurface\WinFormsS urface.csproj]
```

Are these messages possibly related to https://github.com/dotnet/sdk/pull/3268? It looks like this error comes from ResolvePackageAssets.cs and those are the most recent changes around the code that triggers this message. Setting `<DisablePackageAssetsCache>true</DisablePackageAssetsCache>` makes the messages go away, but it doesn't seem like the right fix.

**Comment by nguerrera** [comment]
Yes, #3284 is in PR with a proper fix.

**Comment by DustinCampbell** [comment]
Great!
