### ISSUE TITLE
`Microsoft.VisualStudio.JavaScript.Sdk` is not working outside of Windows (but it can)

### ISSUE THREAD

**Issue by seclerp** [dotnet/sdk#32891]
### Describe the bug
JavaScript MSBuild projects (`.esproj`) are not working outside Windows. But it is possible to get it to work with a workaround (see below) 

### To Reproduce
1. On Windows, follow [the tutorial](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022) to create a new ASP.NET Core + RactJS (Preview) solution, as it seems that creating of such a project is impossible outside VS.
2. Copy the resulting solution on the MacOS/Linux environment.
3. Run dotnet build inside the solution folder.

### Expected behavior
Build succeeded.

### Actual behavior
```
/usr/local/share/dotnet/sdk/8.0.100-preview.4.23260.5/Microsoft.Common.CurrentVersion.targets(1229,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/seclerp/Downloads/AspNetCoreReactPreview/reactapp/reactapp.esproj]
    0 Warning(s)
    1 Error(s)
```

### Workaround
Adding such a property group to a `.esproj` file:
```
<PropertyGroup Condition=" '$(OS)' == 'Unix' " >
    <FrameworkPathOverride>/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/mscorlib.dll</FrameworkPathOverride>
</PropertyGroup>
```

Fixes the issue.

### Further technical details
The issue reproduces on both 8.0 preview and 7.0 SDK.

Seems like the root cause of the issue is using the default full-framework toolset for `.esproj` projects which is absolutely fine on Windows environment for .NET SDK but not the case for Mac OS and Linux.

I'm interested in making PR to fix that but can't find the sources (does JavaScript.Sdk is even open-sourced?)

Thanks.

#### .NET info
```
➜ dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-preview.4.23260.5/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: arm64
  Commit:       84a3d0e37e

.NET SDKs installed:
  7.0.203 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.4.23260.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
@joj for comment here as an owner of that MSBuild SDK.

**Comment by joj** [comment]
I'll move this to our internal tracking systems. It aligns with the revamp we're doing now on dotnet and esproj, so we can add it to that. Thanks! J

**Comment by marcpopMSFT** [comment]
Per the above comment, I assume this has been moved to a separate system for tracking so closing.

**Comment by abl-jakev** [comment]
> I'll move this to our internal tracking systems. It aligns with the revamp we're doing now on dotnet and esproj, so we can add it to that. Thanks! J

Was this ever moved? If so, is there a link to where? I am running into the same issue and wanted to see if a fix was still planned.

**Comment by joj** [comment]
This was moved to internal tracking (the JavaScript SDK is tracked there). We're testing at the moment on both Linux and Mac and will probably have support in a preview of VS soon.

**Comment by cuongwf1711** [comment]
I am facing a similar issue. Please help me and provide a solution.

![f36ac5ab-e1b8-435c-9f94-f58dd214c3c2](https://github.com/dotnet/sdk/assets/128906983/c4073607-2b37-4c87-a391-37a35d33d629)

**Comment by mcl-sz** [comment]
> I am facing a similar issue. Please help me and provide a solution.
> 
> ![f36ac5ab-e1b8-435c-9f94-f58dd214c3c2](https://private-user-images.githubusercontent.com/128906983/341970432-c4073607-2b37-4c87-a391-37a35d33d629.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjM3MjYsIm5iZiI6MTcyMTgyMzQyNiwicGF0aCI6Ii8xMjg5MDY5ODMvMzQxOTcwNDMyLWM0MDczNjA3LTJiMzctNGM4Ny1hMzkxLTM3YTM1ZDMzZDYyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzE3NGQwODhlYzA3ZDQwNzhhZWE1M2E5NjM2ZGRkOGQ2YjQzZDMzMTAyZGYyZjlmOTYyZmZlZjUyMTdlYTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_GKl6GI5Lsl_Uvpf2wMP3pWXNipONwmeZNNEiJHtTM)

@cuongwf1711 I have the same errormessage. Did you find a solution?

**Comment by VGib** [comment]
Same problem, please when you add new template in visual studio , check it can run on linux build, thanks.

**Comment by robertmclaws** [comment]
Is there any word on this? I'm STILL facing this issue on a brand new React project building on Linux in GitLab. Should not be rocket science.

**Comment by Myster** [comment]
I was getting this issue in github actions & codeQL autobuilds 
because my esproj had an old version number:
`<Project Sdk="Microsoft.VisualStudio.JavaScript.Sdk/0.5.74-alpha">`
this works:
`<Project Sdk="Microsoft.VisualStudio.JavaScript.Sdk/1.0.5581896">`
