### ISSUE TITLE
DotNetAppHost's version info and icon

### ISSUE THREAD

**Issue by AntonPlotnikov** [dotnet/sdk#3291]
Hello. I need to add a version info and custom icon for DotNetAppHost? We use potable mode (Framework-dependent deployment), and there are some branding and security requirements. Unfortunately, I can add version info only to application's main assembly file (dll), not to exe file (we use RID win7-x64) during building in Visual Studio 2019. Is it any way to do this during MSBuild process?
![2019-06-01_23-57-09](https://user-images.githubusercontent.com/18666703/58753548-558b5b80-84c9-11e9-9deb-c51f6890484b.png)

**Comment by jkotas** [comment]
This was fixed for .NET Core 3.0 by #1899. Is using / waiting for .NET Core 3.0 an option for you?

**Comment by AntonPlotnikov** [comment]
I suppose .NET Core 3.0 will be a good option. Thanks!

**Comment by livarcocc** [comment]
Closing as fixed.
