### ISSUE TITLE
BinaryFormatter is disabled in WinForms or WPF projects in preview6

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/sdk#32941]
### Describe the bug
The intent behind this change - https://github.com/dotnet/sdk/commit/ccfcbe828cda905f1f995f63f26485dd9a7a7dd5 was that projects with these properties
```
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
```
Have BinaryFormatter.Serialize/Deserialize methods enabled in .NET8. However in SDK Preview6, we are getting a `NotSupportedException` 
### To Reproduce

1.	Install the [latest SDK](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Finstaller%23installers-and-binaries&data=05%7C01%7CTatiana.Solyanik%40microsoft.com%7C813bfb40a3cb4b89886708db621395ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211608480348989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bb6tzFSBYYLdP%2FIGGwZkE5LV%2Fz0TwURa7H8CLSwBJy0%3D&reserved=0)
2.	Create a winforms application targeting .NET 8 in the VS (app is here [https://github.com/Tanya-Solyanik/Repro](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTanya-Solyanik%2FRepro&data=05%7C01%7CTatiana.Solyanik%40microsoft.com%7C813bfb40a3cb4b89886708db621395ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211608480348989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LfZq%2FblGC0ldwEvVhsOC7FmXKsMcUl8mSmxmJvtVktI%3D&reserved=0))
3.	Add `<NoWarn>SYSLIB0011</NoWarn>` to the project file
4.	Add a call to BinaryFormatter.Serialize()
5.	Run that code
 
**Result**: _System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See [https://aka.ms/binaryformatter](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fbinaryformatter&data=05%7C01%7CTatiana.Solyanik%40microsoft.com%7C813bfb40a3cb4b89886708db621395ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211608480348989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BHG2WuS1NzS5%2FDUJqWSsPaQtBACgCG9HNi513bfu1eY%3D&reserved=0) for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at WinFormsApp29.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\tanyaso\source\repos\WinFormsApp29\WinFormsApp29\Form1.cs:line 17_

### Further technical details
- Repros both in the VS and on the command line, as long as SDK preview 6.23280 is installed
- If I add a switch
```
            AppContext.SetSwitch(
                "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization",
                isEnabled: true);
```
or 
`<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`
BinaryFormatter serializes successfully.

**Comment by Tanya-Solyanik** [comment]
This is blocking WinForms out of process designer from using resources and controls, such as ImageList

**Comment by GrabYourPitchforks** [comment]
This appears to be a regression from 8.0 Preview 4, where the scenario worked correctly. I'm trying to narrow down the change.

**Comment by GrabYourPitchforks** [comment]
Some initial assessment of various file contents follow. Note the unintentional inclusion of _EnableUnsafeBinaryFormatterSerialization = false_ by default in the coreapp's runtimeconfig.json for P5 and the WindowsDesktop's runtimeconfig.json for P6. I'll ask around to see if anybody knows how these settings got added to these files.

## Preview 4 (BF works by default in WinForms)

**C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.4.23259.5\Microsoft.NETCore.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

**C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0-preview.4.23260.1\Microsoft.WindowsDesktop.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "rollForward": "LatestPatch",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-preview.4.23259.5"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

## Preview 5 (BF fails in WinForms)

**C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.5.23280.8\Microsoft.NETCore.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

**C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0-preview.5.23281.1\Microsoft.WindowsDesktop.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "rollForward": "LatestPatch",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-preview.5.23280.8"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

## Preview 6 (BF fails in WinForms)

**C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-preview.6.23280.5\Microsoft.NETCore.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

**C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0-preview.6.23280.3\Microsoft.WindowsDesktop.App.runtimeconfig.json**

```json
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "rollForward": "LatestPatch",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-preview.5.23276.1"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

**Comment by GrabYourPitchforks** [comment]
The root cause of this bug seems to be https://github.com/dotnet/sdk/issues/32969.

**Comment by Amy-Li03** [comment]
Verified issue https://github.com/microsoft/winforms-designer/issues/5233 on .NET SDK 8.0.100-preview.5.23301.12 test pass build, it was fixed, in winforms VB project, 'Explorer Form' template form designer can be loaded successfully.
![Fixed](https://github.com/dotnet/sdk/assets/62929087/c33829a1-41a7-463d-84c1-6785a0bd8118)

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/33004
