### ISSUE TITLE
Add Resource file to Microsoft.DotNet.Core.Build.Tasks

### ISSUE THREAD

**Issue by natidea** [dotnet/sdk#33]
Currently seeing a couple of errors when introducing a resx file:
- Opening up the file: Could not resolve mscorlib for target framework '.NETStandard,Version=v1.3'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.
- From the designer: 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by srivatsn** [comment]
This is now done I believe?

**Comment by nguerrera** [comment]
Fixed by #398
