### ISSUE TITLE
dotnet tool run <TOOL_NAME> doesn't work on Linux

### ISSUE THREAD

**Issue by marcin-krystianc** [dotnet/sdk#33030]
### Describe the bug
A `dotnet tool run <TOOL_NAME>` seems to be broken on Linux.
_"Cannot find a tool in the manifest file that has a command named '<TOOL_NAME>'"_

### To Reproduce

Reproducing using clean "ubuntu-latest" image via Docker:
- `docker.exe run -t -i --rm ubuntu`
- `apt-get update && apt-get install -y dotnet-sdk-7.0 ca-certificates`
- `export PATH="$PATH:/root/.dotnet/tools"`
- `dotnet -d tool install -g dotnet-trace`
- `dotnet tool run dotnet-trace`

### Exceptions (if any)

<img width="840" alt="image" src="https://github.com/dotnet/sdk/assets/2308005/b5743cc5-ba78-40f1-af41-e772c3118e7c">

### Further technical details
```
dotnet --info
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.105 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
PS:
Tried with latest daily build (https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-linux-x64.tar.gz), but the problem remains the same.

**Comment by nagilson** [comment]
@baronfel @JL03-Yue Is there already an issue for this that you're aware of? It seems familiar.

**Comment by JL03-Yue** [comment]
This might be a RID related issue addressed in #30762. Does it still occur @marcin-krystianc

**Comment by marcin-krystianc** [comment]
> This might be a RID related issue addressed in #30762. Does it still occur @marcin-krystianc

Yes unfortunately, I tried `v8.0.100-rc.2` and it still doesn't work:
```
docker.exe run -t -i --rm ubuntu
```
```
mkdir dotnet \
&& apt-get update && apt-get install -y wget ca-certificates \
&& wget https://download.visualstudio.microsoft.com/download/pr/9144f37e-b370-41ee-a86f-2d2a69251652/bc1d544112ec134184a5aec7f7a1eaf9/dotnet-sdk-8.0.100-rc.2.23502.2-linux-x64.tar.gz \
&& tar -C dotnet -xvzf dotnet-sdk-8.0.100-rc.2.23502.2-linux-x64.tar.gz \
&& export DOTNET_ROOT=/dotnet \
&& export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 \
&& export PATH=$PATH:/dotnet:$HOME/.dotnet/tools
```
```
dotnet -d tool install -g dotnet-trace
```

<img width="562" alt="image" src="https://github.com/dotnet/sdk/assets/2308005/e3341393-8ff4-49f0-8455-881a0c4afd2d">

**Comment by ohadbitt** [comment]
Same in my Hyper -v Ubuntu 22.04 and .Net SDK 8.0.1

**Comment by marcpopMSFT** [comment]
Triage: `dotnet tool run` is limited to locally installed tools. Can you use `dotnet-trace` to run your globally installed tool (or `dotnet trace`)? 

Assigning to get the help text updated to say that it doesn't work for global tools. We could potentially add the support but that doesn't seem immediately necessary.

**Comment by JL03-Yue** [comment]
close as updated help text for dotnet tool run in #39827
