### ISSUE TITLE
Add support for podman credentials by using Valleysoft.DockerCredsProvider 2.2.0

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#33034]
@baronfel @mthalman what should we do to use the newer version in this repo?
The version is not found in the NuGet feeds used by this repository.

We probably need do do something for source-build too?

**Comment by baronfel** [comment]
For the immediate term we need to add the new package to the mirrored internal feeds, I can work on that this morning. For source build I expect https://github.com/dotnet/source-build-externals/blob/main/repo-projects/docker-creds-provider.proj will need updating, but @mthalman would know for sure.

**Comment by mthalman** [comment]
The mirrored feed should now be updated to include the 2.2.0 version.

I'll prep the change for SB and get that merged once the corresponding update in the SDK exists.

**Comment by baronfel** [comment]
@mthalman you rock, thank you!

Are there any implications for source-build if we try to update to this version for the 7.0.4xx SDKs? I wouldn't think there would be, since source-build only takes the 1xx-series of 7 SDKs, right?

**Comment by mthalman** [comment]
> Are there any implications for source-build if we try to update to this version for the 7.0.4xx SDKs? I wouldn't think there would be, since source-build only takes the 1xx-series of 7 SDKs, right?

Correct. No impact to SB for 7.0.4xx.

**Comment by baronfel** [comment]
SDK Codeflow automation will take care of forward merging from release/7.0.4xx to 8.0.1xx.
