### ISSUE TITLE
Duplicate error code found

### ISSUE THREAD

**Issue by v-wuzhai** [dotnet/sdk#33133]
In 7.0.3、7.0.4、main branch src/Tasks/Common/Resources/Strings. resx file found repetitive error code NETSDK1080, I submitted a [pr](https://github.com/dotnet/sdk/pull/33102) to repair it for the time being.

 Problems such as duplicate error codes can be difficult to avoid due to lack of checks. In order to solve this problem, we may need a strategy to check for duplicate code.

cc @marcpopMSFT @dotnet/domestic-cat

**Comment by marcpopMSFT** [comment]
I think we fixed up all of the existing error codes and with the merge of https://github.com/dotnet/sdk/pull/33184, we are now validating this going forward.
