### ISSUE TITLE
Regression in build times for Travis CI using 2.2.300 SDK

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#3314]
I've noticed across several different projects I maintain that since the SDK was updated from 2.2.1xx or 2.2.2xx to 2.2.300, the time to build the projects in Travis CI has regressed by up to an order of magnitude on both Linux and macOS.

However I'm not seeing the same regression in Azure DevOps pipelines for Linux, macOS or Windows, or AppVeyor for Windows.

Below are a selection of projects that show a build time regression immediately after merging a PR that contains a commit that updates the SDK to 2.2.300:

| History | Build time pre-update | Build time post-update | Delta | PR with SDK update | Commit with SDK update |
|:-:|:-:|:-:|:-:|:-:|:-:|
| [project-euler](https://travis-ci.org/martincostello/project-euler/builds) | 3 min 40 sec | 37 min 13 sec | +1,015% | [#33](https://github.com/martincostello/project-euler/pull/33) | [b2c7ed3](https://github.com/martincostello/project-euler/commit/b2c7ed39e539201c6625f0d06787de42cb50abaa) |
| [JustEat.StatsD](https://travis-ci.org/justeat/JustEat.StatsD/builds) |  2 min 33 sec | 12 min 19 sec | +483% | [#177](https://github.com/justeat/JustEat.StatsD/pull/177) | [4f4ac55](https://github.com/justeat/JustEat.StatsD/commit/4f4ac5505f2953efa09eef8cc304aad514e49099) |
| [sqllocaldb](https://travis-ci.org/martincostello/sqllocaldb/builds) | 3 min 31 sec | 16 min 28 sec | +468% | [#88](https://github.com/martincostello/sqllocaldb/pull/88) | [671307a](https://github.com/martincostello/sqllocaldb/commit/671307a1fc216d1514f32c787aff547570408e37) |
| [adventofcode](https://travis-ci.org/martincostello/adventofcode/builds) | 7 min 4 sec | 31 min 51 sec | +450% | [#72](https://github.com/martincostello/adventofcode/pull/72) | [8ecc3a7](https://github.com/martincostello/adventofcode/commit/8ecc3a77b5696e5eae735826ef510ef3599447b1) |
| [JustSaying](https://travis-ci.org/justeat/JustSaying/builds) | 6 min 49 sec | 25 min 55 sec | +380% | [#545](https://github.com/justeat/JustSaying/pull/545) | [88f241c](https://github.com/justeat/JustSaying/commit/88f241c8a6bcb5768e2d57fae4aef906aacad53a) |
| [httpclient-interception](https://travis-ci.org/justeat/httpclient-interception/builds) | 6 min 26 sec | 16 min 26 sec | +255% | [#85](https://github.com/justeat/httpclient-interception/pull/85) | [065c722](https://github.com/justeat/httpclient-interception/commit/065c7222669c291baf1fc75f20ce7c6f4863568c) |
| [alexa-london-travel-site](https://travis-ci.org/martincostello/alexa-london-travel-site/builds) | 5 min 34 sec | 11 min 31 sec | +206% | [#267](https://github.com/martincostello/alexa-london-travel-site/pull/267) | [48b47a5](https://github.com/martincostello/alexa-london-travel-site/commit/48b47a5497e9e824fe3ba0d41ef4d9ef299773e0) |
| [api](https://travis-ci.org/martincostello/api/builds) | 5 min 54 sec | 9 min 46 sec | +165% | [#112](https://github.com/martincostello/api/pull/112) | [40c1dee](https://github.com/martincostello/api/commit/40c1dee042f02e18f64c68fcdac7c4500559f907) |
| [website](https://travis-ci.org/martincostello/website/builds) | 4 min 26 sec | 7 min 13 sec | +162% | [#263](https://github.com/martincostello/website/pull/263) | [3a43580](https://github.com/martincostello/website/commit/3a4358008c7022d0abf667774a26505ad9892a47) |

My hunch is that it is related to the new "progress bar" when running `dotnet test` which is causing the Travis agents to waste a lot of time trying to "draw" it because the actual test run times printed in the build output are equivalent:

  * [Build before](https://travis-ci.org/martincostello/project-euler/jobs/513808297#L560) - `Time Elapsed 00:00:10.86`
  * [Build after](https://travis-ci.org/martincostello/project-euler/jobs/537916269#L556) - `Time Elapsed 00:00:15.31`
  * [Test before](https://travis-ci.org/martincostello/project-euler/jobs/513808297#L706) - `Test execution time: 46.8778 Seconds`
  * [Test after](https://travis-ci.org/martincostello/project-euler/jobs/537916269#L700) - `Total time: 46.5308 Seconds`

**Comment by martincostello** [comment]
Maybe requires integration of https://github.com/microsoft/vstest/pull/2024?

**Comment by martincostello** [comment]
Related fix: https://github.com/dotnet/cli/pull/11497

**Comment by livarcocc** [comment]
Just to confirm further this is potentially a regression on vstest, would it be possible for you to gather these numbers if you turned off tests on your CI, just to collect data?

cc @singhsarab

**Comment by singhsarab** [comment]
@martincostello 
Progress indicator would not come into play if Console.IsOutputRedirected is set, which I am guessing should be true.

I looked at logs of one of the PRs, https://travis-ci.org/justeat/JustEat.StatsD/jobs/541122616, the total time reported for test run is 10 seconds, let's add some start and cleanup time, even then it should not call for printing the progress bar more than 20 times as it is called after an interval of 1 sec.

Can you please enable logging and share the logs with me?

**Comment by martincostello** [comment]
@singhsarab Can you let me know exactly what logging parameters you need setting through `dotnet test` (info, verbose, debug?), and I'll do a PR to add them to the slowest run and see what happens.

**Comment by singhsarab** [comment]
@martincostello You can use --diag:log.txt argument
https://github.com/microsoft/vstest-docs/blob/master/docs/diagnose.md#dotnet-test

**Comment by martincostello** [comment]
There's a [test running now](https://travis-ci.org/martincostello/project-euler/jobs/544164410), it hasn't gotten as far as printing out anything yet, but it seems like whatever is slow is running after the last test finishes before the process exits.

**Comment by martincostello** [comment]
There appears to be a 17 minute gap between [these two log messages](https://travis-ci.org/martincostello/project-euler/jobs/544203317#L1080-L1081):

```sh
TpTrace Verbose: 0 : 5334, 9, 2019/06/11, 12:37:13.427, 134005118760, vstest.console.dll, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 1, Run complete = True, Run canceled: False.
TpTrace Verbose: 0 : 5334, 9, 2019/06/11, 12:54:14.143, 1154721904773, vstest.console.dll, TestRunRequest:TestRunComplete: Starting. IsAborted:False IsCanceled:False.
```

**Comment by livarcocc** [comment]
@singhsarab is @martincostello's lastest reply and logs enough for you to make headway on this?

**Comment by singhsarab** [comment]
@martincostello Thanks for the logs. I am not able to come up with a hypothesis right away. There seems to be some issue while clean up.

Is this issue happening only on travis CI ? I am trying to see if I can get a local repro to debug this one.

**Comment by singhsarab** [comment]
Let's transfer this to microsoft/vstest, will help us track this better

**Comment by martincostello** [comment]
@singhsarab Yes, only Travis CI. Locally, AppVeyor and Azure DevOps Pipelines are all fine.

**Comment by martincostello** [comment]
@singhsarab This issue does not seem to affect .NET Core 3.0 preview 6: https://travis-ci.org/martincostello/project-euler/builds/545376053

**Comment by martincostello** [comment]
One thing I've noticed that's different in Travis CI compared to Azure Dev Ops is that `Test run in progress..` gets printed to the console a lot in Travis, but not in Azure.

Could _something_ different be making vstest think it should be printing progress to an interactive console, rather than say not because `$(CI)` is true in the environment?

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2078
