### ISSUE TITLE
Source-build patch removal for SDK.

### ISSUE THREAD

**Issue by crummel** [dotnet/sdk#3317]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/sdk.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
sdk/0001-Upgrade-to-netcoreapp2.1.patch | ToolCompat | Incorporate | Repo | 
sdk/0002-Add-missing-PlatformAbstractions-reference.patch | Bug | Incorporate | source-build |  
sdk/0003-Consolidate-versions.patch | Coherence | Incorporate | source-build |

**Comment by nguerrera** [comment]
> sdk/0002-Add-missing-PlatformAbstractions-reference.patch

Not really sure why this is necessary. It is a transitive dependency. If the packs coming in are source built, they should point to the right source built version as a dependency. But it's harmless, so I'll accept it.

**Comment by nguerrera** [comment]
> sdk/0003-Consolidate-versions.patch

This has to be done carefully, the version used by other components must match. Particularly Microsoft.NET.HostModel.

**Comment by nguerrera** [comment]
> But it's harmless, so I'll accept it.

I take that back, picking a specific version adds more binding redirect risk for netfx build. Also, it would need to be changed to prevent copying for netcoreapp case. I don't think it is necessary.

@crummel Can you give me steps to validate these changes. I want to understand why these were done better. The comments in the patches do not tell the whole story.

**Comment by crummel** [comment]
0003 I'll switch to our responsibility, it was a coherence issue so I'll look into that further.  If 0002 is a transitive dependency then it's probably a similar issue - should we be using the built version of PlatformAbstractions or is that something that should be constant?

**Comment by nguerrera** [comment]
It needs to be the built version because it appears in the output of the build for net4x case. I would expect that the source-built DependencyModel would pull in the source-build PlatformAbstractions transitively. S.R.M also needs to be source built and we need to make sure that core-setup and the web sdk(s) get pushed the same version.

**Comment by crummel** [comment]
Ok, I will check on what DependencyModel and S.R.M are doing, I'll probably be pestering you about this shortly.  I'll move this issue to source-build since these are all our patches now.

**Comment by crummel** [comment]
Issue moved to [dotnet/source-build #1107](https://github.com/dotnet/source-build/issues/1107) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nguerrera** [comment]
Reopening for patch 0001 while #1107 is still open.
