### ISSUE TITLE
Issues with conflict resolution logging

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3319]
1. At normal verbosity, there are unactionable messages about things that happen in very common cases. For example, every core WPF project has a conflict between WindowsBase in netcore app. Importance should be lowered so that you can still see in binlog/diag, but not otherwise. We regularly get questions about what to do about a conflict, when there is nothing to do.

2. It is quite noisy to have codes associated with non-error, non-warnings. We should refactor to not bother having codes for messages. Related: https://github.com/dotnet/sdk/issues/2468

3. We are concatenating strings, so we end up with a code inside a code. NETSDKXXXX: Encountered conflict yada, yada.  NETSDKYYYY. Choosing Foo.

**Comment by peterhuene** [comment]
Thanks for filing this.  The verbosity from this task always bugged me a little.
