### ISSUE TITLE
[SBRP] Generated artifacts have a mixture of line endings

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#33289]
1. delete ./src/referencePackages/src/microsoft.bcl.asyncinterfaces/1.1.0
2. run ./generate.sh -x -p microsoft.bcl.asyncinterfaces,1.1.0
3. Inspect the line endings used across the generated artifacts

Expected Results:
1. Artifacts would use the same line ending formats
2. line ending format would be the default for the environment (e.g. Linux/Windows).

Actual Results in a Linux environment:
1. csproj - LF
2. nuspec - CRLF
3. netstandard 2.0 code - CRLF
4. netstandard 2.1 code - LF

**Comment by ericstj** [comment]
Bug is here: https://github.com/dotnet/sdk/blob/aa48c6c9ddfe99418420dc748bc55a208a16b1ca/src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs#L84-L91C43

NormalizeWhitespace has a default parameter value for eol:
https://github.com/dotnet/roslyn/blob/fcfb85983ac231b870ed737d4be669b50d627b64/src/Compilers/CSharp/Portable/Syntax/SyntaxExtensions.cs#L91
That's defined as `internal const string DefaultEOL = "\r\n";`
https://github.com/dotnet/roslyn/blob/fcfb85983ac231b870ed737d4be669b50d627b64/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions.cs#L288

All attributes are later appended and [use](https://github.com/dotnet/sdk/blob/aa48c6c9ddfe99418420dc748bc55a208a16b1ca/src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs#L286) SyntaxFactory.LineFeed which [ends up](https://github.com/dotnet/roslyn/blob/fcfb85983ac231b870ed737d4be669b50d627b64/src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxFactory.cs#L19) being just `\n`.

Probably that call to `NormalizeWhitespace` should be moved after we write all the attributes, then we might want to specify the `eol` character.

**Comment by ViktorHofer** [comment]
The next sdk --> SBRP dependency update will bring the fix into SBRP.
