### ISSUE TITLE
NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized

### ISSUE THREAD

**Issue by amh1979** [dotnet/sdk#3329]
SDK: 3.0.0-preview6-27804-01
Microsoft.NET.Sdk.TargetingPackResolution.targets(185,5): error NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized

**Comment by livarcocc** [comment]
Can you please tell us more about your repro? How are your projects setup? Could you create a small set of projects and push them to a repo on github that we can checkout and use to reproduce this issue?

I don't believe the information you provided here is enough for us to help you out or investigate this further.

**Comment by tomrus88** [comment]
Same bug was fixed recently. Are you building from VS or command line? Have you updated your VS if you are using it?

**Comment by amh1979** [comment]
Two projects:
 the first "<TargetFramework>netstandard2.1</TargetFramework>"
the second <TargetFramework>netcoreapp3.0</TargetFramework>
when build the second project, then show error NETSDK1073

**Comment by livarcocc** [comment]
Like @tomrus88 said, where are you building this from? This bug was recently fixed for preview6 on the command line. And it was recently fixed in VS 16.2 as well?

I see you mentioning
> SDK: 3.0.0-preview6-27804-01

Which is not really a SDK version number. Can you run dotnet --version from the command line and let us know what is that version? Also, what version of VS you are using?

**Comment by amh1979** [comment]
VS 16.1.3

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by amh1979** [comment]
Fixed use &gt;GenerateErrorForMissingTargetingPacks&lt;false&gt;/GenerateErrorForMissingTargetingPacks&lt;

**Comment by zhosn** [comment]
> Fixed use <GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>
@ amh1979 Hi，What is the position of the above conditions to Microsoft.NET.Sdk.TargetingPackResolution.targets? Thanks!

**Comment by StanislavChankovSellerCloud** [comment]
> Fixed use <GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>

3.0.0-preview7 - Same issue, same Fix

**Comment by StanislavChankovSellerCloud** [comment]
> Fixed use <GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>

3.0.0-preview7 - Same issue, same Fix

**Comment by amh1979** [comment]
> > Fixed use false
> > @ amh1979 Hi，What is the position of the above conditions to Microsoft.NET.Sdk.TargetingPackResolution.targets? Thanks!

your project file, such as: .csproj, .vbproj
