### ISSUE TITLE
Version of Microsoft.NET.Sdk package used by "dotnet new" does not match the version in offline package installer 

### ISSUE THREAD

**Issue by balachir** [dotnet/sdk#333]
INSTALL STEPS
1. Run preinstall.cmd
2. Install Dev15 RC build d15rel.25827.01 (.NET Core workload)
 
REPRO STEPS
1. Run "dotnet new" from command-line

ACTUAL
Version of Microsoft.NET.Sdk package used by "dotnet new" does not match the version in offline package installer. Version used by "dotnet new" is 1.0.0-alpha-20161019-1 but the one from offline package installer is 1.0.0-alpha-20161027-2

I'd expect the versions to be in-sync. Impact is probably that if you do 'dotnet new' and then open the project in VS, then it's using an old package and things might not behave correctly.

![image](https://cloud.githubusercontent.com/assets/8246794/19783171/bddc1f72-9c45-11e6-9912-fa3c3cb3ba7a.png)

**Comment by srivatsn** [comment]
Please file this in the CLI repo. When a new CLI gets inserted that will increment the SDK version. Since the VS insertion scehdules are different between CLI and the package cache installer, I expect this will remain the case until we ship.
