### ISSUE TITLE
Unable to use ReadyToRun on Debian 8 due to incorrect runtime bits resolution by SDK

### ISSUE THREAD

**Issue by fadimounir** [dotnet/sdk#3336]
Original bug: https://github.com/dotnet/coreclr/issues/24565

Repro app is here: https://github.com/wieslawsoltes/Draw2D. To repro:
1) clone
2) Edit Draw2D.csproj and add netcoreapp3.0 to the list of target frameworks
3) run this command:
``` console
dotnet publish ./src/Draw2D/Draw2D.csproj -f netcoreapp3.0 -c Release -r debian.8-x64 -o Draw2D_netcoreapp3.0_debian.8-x64
```

Running the application throws a `Failed to initialize CoreCLR,, HRESULT: 0x80131500` error.

Looking at the msbuild verbose logs, you can see that the SDK is copying the runtime bits from the runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64 package, which is incorrect.

On Debian9 targets, the runtime bits are copied correctly (version 3). On Debian8, the SDK doesn't resolve correctly. Here's an example error I got: 

``` console
/home/fadi/dotnet_preview5/sdk/3.0.100-preview5-011569/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(39,5): message NETSDK1041: Encountered conflict between 'CopyLocal:/home/fadi/.nuget/packages/runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64/native/libcoreclr.so' and 'CopyLocal:/home/fadi/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/3.0.0-preview5-27709-08/runtimes/linux-x64/native/libcoreclr.so'.  NETSDK1037: Could not determine winner due to equal file and assembly versions. [/home/fadi/git/Draw2D/src/Draw2D/Draw2D.csproj]
```

Also, it ends up copying the runtime bits from the 1.0.7 runtime package. Example:

``` console
Copying file from "/home/fadi/.nuget/packages/runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64/native/libcoreclr.so" to "/home/fadi/git/Draw2D/src/Draw2D/bin/Release/netcoreapp3.0/debian.8-x64/libcoreclr.so".
```

**Comment by fadimounir** [comment]
cc @wieslawsoltes @nguerrera

**Comment by nguerrera** [comment]
@dsplaisted Related to issues with 1.x packages in graph?

**Comment by dsplaisted** [comment]
Can you [provide a binary log](https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b) of the build exhibiting the incorrect behavior?

**Comment by livarcocc** [comment]
Pinging @fadimounir to give us a binlog. Without further information we can't make progress on this issue.

**Comment by fadimounir** [comment]
@livarcocc @dsplaisted Ok i'll get a binlog. Just curious, did you guys try to repro this and couldn't, and that why you need the binlog?

**Comment by fadimounir** [comment]
Ok this is more broken with the preview 7 bits. The runtime bits are not getting published to the output folder. The _CopyResolvedFilesToPublishAlways task didn't copy anything. I attached the binlog (just rename and remove the .zip)
[msbuild.binlog.zip](https://github.com/dotnet/sdk/files/3335804/msbuild.binlog.zip)

**Comment by fadimounir** [comment]
Even with PublishReadyToRun=false, the publish behavior seems to be similar to a framework-dependent publishing (no runtime bits in the output publish folder). I would have expected to see libcoreclr.so for instance.
Using `--self-contained true` in the command line seems to copy the runtime bits, but still no apphost exe entry point

**Comment by fadimounir** [comment]
Ok looks like the app got refactored, and the Draw2D project became a library. Trying to build the Draw2D.Desktop project instead to see if the bug still repros

**Comment by fadimounir** [comment]
Verified. The bug seems to have been fixed in P7. Closing issue

**Comment by nguerrera** [comment]
Should we block R2R on library project publishes? Publish on library is a strange case already and trips people up a lot.

**Comment by fadimounir** [comment]
@nguerrera Yes that would be a good thing to do. It could be a source of problems if some lib developer publishes R2R for a certain platform/arch, and another app developer uses that lib on a different target

**Comment by nguerrera** [comment]
Can you open an issue for that?

**Comment by fadimounir** [comment]
Filed #3364

**Comment by dsplaisted** [comment]
> Just curious, did you guys try to repro this and couldn't, and that why you need the binlog?

Yes, I tried to repro this and wasn't able to.
