### ISSUE TITLE
SatelliteResourceLanguages property doesn't filter all resources when publishing test projects

### ISSUE THREAD

**Issue by lzganec** [dotnet/sdk#3338]
Having a dependency to Microsoft.CodeCoverage (which comes from Microsoft.NET.Test.Sdk) leaves Microsoft.VisualStudio.TraceDataCollector.resources.dll localized resource satellite assembly in the publish output using .NET Core version 2.2.

**Comment by livarcocc** [comment]
@nguerrera can you take a look?

**Comment by nguerrera** [comment]
Thanks for the report. I can repro this and it's due to a custom target in test sdk that copies these. They aren't normal nuget assets,

I moved this to https://github.com/microsoft/vstest/issues/2057 where the root cause is.
