### ISSUE TITLE
NETSDK1139 should suggest enabling the workload resolver when disabled

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#33395]
### Is your feature request related to a problem? Please describe.
The NETSDK1139 diagnostic is fired when a Target Platform Identifier (windows, android, ios, linux) isn't recognized by the TargetFrameworkInference targets. It's technically correct, but it doesn't help the user know what to do to solve the underlying issue:

> The target platform identifier {0} was not recognized.

### Describe the solution you'd like
One common cause of this (for android, ios, wasm platforms especially) is workloads being disabled on the system, often by the `MSBuildEnableWorkloadResolver` MSBuild property being set to `false`. 

If the `MSBuildEnableWorkloadResolver` is `false`, we should provide additional context in the message guiding the user towards removing the `false` assignment.

> The target platform identifier {0} was not recognized. This target platform may be provided by workloads, which are currently disabled. Set the MSBuildEnableWorkloadResolver property to true, or remove where this property is set to false, to enable workloads on this system.

### Additional context
<img width="936" alt="image" src="https://github.com/dotnet/sdk/assets/573979/f4c03403-6a1b-4b2f-a409-9ee3bfbaa73d">

**Comment by dsplaisted** [comment]
Thinking a bit more about this and looking at the code, we might want to generate a new error message (with a new code), but only generate it if NETSDK1139 is already being generated.  IE we'd add an additional error to the `_CheckForUnsupportedTargetPlatformIdentifier` target.
