### ISSUE TITLE
Incorrect warning about WindowsDesktop SDK

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sdk#3341]
I have a project that has some libraries/exe that use WPF and some that don't. The ones that do use the WindowsDesktop SDK. The ones that don't use the default SDK to prevent accidental WPF references.

I have a directory.build.props file that sets `UseWPF` to `true` so that I don't need them in all places.

In Preview 7, I now get this warning:

```
1>C:\Program Files\dotnet\sdk\3.0.100-preview7-012503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(340,5): warning NETSDK1107: Microsoft.NET.Sdk.WindowsDesktop is required to build Windows desktop applications. 'UseWpf' and 'UseWindowsForms' are not supported by the current SDK.
```

That's coming from `Microsoft.NET.Sdk.DefaultItems.targets`. The check is being too aggressive.

**Comment by vatsan-madhavan** [comment]
We have seen two kinds of problem reports:

  i. Failing to change `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.WindowsDesktop`, setting `UseWpf` (or `UseWindowsForms`) to `true`, and attempting to build/port a WPF app (which, unsurprisingly, fails to build as expected)
  
  ii. Using `Microsoft.NET.Sdk.WindowsDesktop`, but failing to set `UseWpf` or `UseWindowsForms` to `true`. Again, fails to build as expected. 

We wanted to add _suppressible_ warnings to help with both scenarios. This addresses the first one.

**Comment by onovotny** [comment]
@vatsan-madhavan the warning as it's defined does not appear to be suppressible https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L337-L342

**Comment by vatsan-madhavan** [comment]
```XML
<PropertyGroup> 
 <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);NETSDK1107</MSBuildWarningsAsMessages>
</PropertyGroup>
```

That should do it, I think.

**Comment by onovotny** [comment]
I'll give that a try. Any chance the check can determine if it's coming from a props/targets file and skip? Like if people are using props/targets, then they're an advanced user.

**Comment by dsplaisted** [comment]
No, there's not a way in MSBuild for a target to check where a property was set.

**Comment by vatsan-madhavan** [comment]
I'm open to ideas. @nugerra/@dplaisted, thoughts on how we may be able to improve this to have less friction? 

We had a [similar discussion](https://github.com/dotnet/wpf/issues/327) about problems around multi-targeting when using WindowsDesktop SDK, where the discussion centered around the best implementation approach that would help those who need these sorts of warnings, vs. not creating friction for complex codebases.

**Comment by nguerrera** [comment]
I'm putting this in discussion milestone because this was a deliberate change. I think it's reasonable to put a suppression as shown above for the advanced cases.

**Comment by AArnott** [comment]
In my case I'm seeing the warning in a project the multi-targets. I only set `UseWPF` when targeting netcoreapp3.0 since of course that's the only TFM to which it applies. But I'm seeing the warning in other TFMs because the Sdk is of course not conditioned on the TFM.

**Comment by AArnott** [comment]
I'm using this to hide the warnings:
```xml
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);NETSDK1105</MSBuildWarningsAsMessages>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);NETSDK1106</MSBuildWarningsAsMessages>
```

**Comment by sommmen** [comment]
NOTE as of now i use the following line to disable the warning:

``` xml
<!-- Disable the warning useWpf gives. -->
<MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);NETSDK1107</MSBuildWarningsAsMessages>
 ```

**Comment by marcpopMSFT** [comment]
@clairernovotny since WindowsDesktop is no longer required starting in 5.0-windows, can this issue be closed? I doubt we'd fix it for downlevel targeting at this point.

**Comment by clairernovotny** [comment]
Closing as no longer applicable.
