### ISSUE TITLE
The URL for downloading the .NET runtime when starting a fx-dependent app is incorrect

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/sdk#33435]
### Describe the bug

When running a fx-dependent application (depending on .NET 7.0), if the .NET Runtime is missing on the system, the following message will be printed out:

```
You must install .NET to run this application.

App: D:\PowerShell\pwsh.exe
Architecture: x64
App host version: 7.0.0
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.0
```

However, the download link points to ASP.NET Core download instead of the .NET Runtime download.
So, after the fx-dependent app still cannot run after a user installs it by following instruction in the message.

### To Reproduce

See https://github.com/PowerShell/PowerShell/issues/19823 for repro steps.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by vitek-karas** [comment]
@richlander  @mairaw 
The redirection service is probably pointing to the wrong place.

**Comment by richlander** [comment]
Thanks for the report. In the process of resolving.

**Comment by 4cq2** [comment]
is this fixed? otherwise can you please reopen the issue?

**Comment by richlander** [comment]
Yes. Try the link in the OP above.
