### ISSUE TITLE
"dotnet run" not correctly handling Chinese characters input via Console.ReadLine() in Debug mode

### ISSUE THREAD

**Issue by sd797994** [dotnet/sdk#33575]
I'm developing a simple console application in C# (.NET 6.0) that accepts Chinese character input from the user via Console.ReadLine(). The program runs fine when executed directly as an executable or with dotnet xxx.dll from the build output. However, when I use dotnet run in Debug mode, the Chinese characters I input appear as garbled text.

Here's a sample of my code:
`
Console.InputEncoding = Encoding.UTF8;
Console.OutputEncoding = Encoding.UTF8;

Console.WriteLine("请输入中文字符：");
string input = Console.ReadLine();
Console.WriteLine(input);
`
The garbled text issue only happens with Chinese characters; English and numeric inputs display just fine. I've checked the input and output encoding of my console, and both are set to Unicode (UTF-8).

Interestingly, when I run the same code in a virtual machine environment, dotnet run correctly processes and outputs the Chinese characters. This suggests the issue might be specific to my main development environment. I've tried reinstalling .NET SDK and Visual Studio, but the problem persists.

Any ideas on how I might resolve this? Is there something specific with the dotnet run command in Debug mode that could be causing this behavior?

**Comment by baronfel** [comment]
What version of the SDK are you using here? In .NET 8 we made some changes to console encoding detection and handling - can you check with .NET 8.0.100 preview 7 (the latest release as of this writing) and let us know what you see?

**Comment by sd797994** [comment]
Due to not receiving a response for a long time, I have reinstalled my operating system and reinstalled the .net 6.0 SDK. The issue can no longer be reproduced. @baronfel
