### ISSUE TITLE
Testing out new targets' interaction with solution (SLN) files

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/sdk#336]
We are creating a new set of targets as part of this repo and overall move to MSBuild. We need to make sure that all of the new core targets work properly with SLN files. That means that for targets that do `test`, `pack`, `publish`, `restore` we need to make sure that they work properly with SLN files. 

Some careful consideration needs to be done for `run`. At this point, I would say that run is the one command that does not work on SLN files and that requires a single project to be present. 

This is related to Microsoft/msbuild#1275.

/cc @nguerrera @srivatsn @piotrpMSFT @jeffkl @rainersigwald

**Comment by rainersigwald** [comment]
Note that if we do https://github.com/Microsoft/msbuild/issues/1275 by accepting any target there's not much we could do about `run` being hard to define at the solution level.

**Comment by nguerrera** [comment]
Does `run` even have a corresponding msbuild target?

**Comment by piotrpMSFT** [comment]
no. run invokes some target that generates a PSI for it, but msbuild doesn't actually invoke <exec>

**Comment by blackdwarf** [comment]
My comment about run was more in the spirit of completeness and exact speccing. :)
