### ISSUE TITLE
Dotnet publish for project with P2P references fails when GeneratePackageOnBuild is true

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#3365]
Based on https://github.com/aspnet/AspNetCore/issues/11636.

https://github.com/dotnet/sdk/pull/3255 causes publish to fail when a project has project references. Treating `NoBuild` and `GeneratePackageOnBuild` as equivalent causes project references to [stop building](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L74-L78).

Repro steps:

* Clone https://github.com/pranavkm/repro/tree/publish-p2p/
* Call `dotnet publish` on mvcapp

**Comment by pranavkm** [comment]
cc @dsplaisted \ @wli3

**Comment by livarcocc** [comment]
@wli3 this looks similar to the other one I just assigned to you.

**Comment by iAmBipinPaul** [comment]
[Blazor] Preview 6 blazorhosted project publish is broken
https://github.com/aspnet/AspNetCore/issues/11185

**Comment by wli3** [comment]
@pranavkm could you try again with the latest SDK. https://github.com/dotnet/sdk/pull/3255 is fixed.

I am using preview 7. I can no longer repro

![image](https://user-images.githubusercontent.com/6993335/61917900-17784a00-af04-11e9-8c4a-a0208bd9d41f.png)

**Comment by wli3** [comment]
hm... seems like I need to run build first. Or it will fail

**Comment by wli3** [comment]
duplicated. prefer https://github.com/dotnet/sdk/issues/3367
