### ISSUE TITLE
Preview 7 still requires a private feed

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#3366]
In tactics @livarcocc said that Preview 7 shouldn't require a private feed. However, you can't build `xunit` right now:

> $ dotnet new xunit -o xunit30
> The template "xUnit Test Project" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on xunit30\xunit30.csproj...
> T:\xunit30\xunit30.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 3.0.0-preview7-27826-04)
> T:\xunit30\xunit30.csproj : error NU1102:   - Found 70 version(s) in nuget.org [ Nearest version: 3.0.0-preview6-27804-01 ]
> T:\xunit30\xunit30.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
> T:\xunit30\xunit30.csproj : error NU1102:   - Found 0 version(s) in dotnet.myget.org roslyn
> Restore failed in 952.45 ms for T:\xunit30\xunit30.csproj.
> 
> Restore failed.
> Post action failed.
> Description: Restore NuGet packages required by this project.
> Manual instructions: Run 'dotnet restore'

That seems like a bug, right?

Note, these templates work:

* Restore completed in 32.51 ms for T:\netcore3\console\console.csproj.
* Restore completed in 40.65 ms for T:\netcore3\classlib\classlib.csproj.
* Restore completed in 32.51 ms for T:\netcore3\winforms\winforms.csproj.
* Restore completed in 32.48 ms for T:\netcore3\wpf\wpf.csproj.
* Restore completed in 32.49 ms for T:\netcore3\mvc\mvc.csproj.

<details>
<summary>dotnet --info</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012650
 Commit:    b959696aad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18912
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012650\

Host (useful for support):
  Version: 3.0.0-preview7-27826-04
  Commit:  5c4d829254

.NET Core SDKs installed:
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012650 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19326.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27826-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27826-04 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by livarcocc** [comment]
@dsplaisted to look.

**Comment by dsplaisted** [comment]
Yes, you will still need the private feed if you have any package references.  That requirement will go away as part of https://github.com/dotnet/sdk/issues/3325

**Comment by dsplaisted** [comment]
This should be fixed for the latest preview 8 builds
