### ISSUE TITLE
VB.NET 'End' not available and odd error message.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/sdk#3379]
Start with a .NET Core 3.0 Console app and simply modify Sub Main.

Module Program
  Sub Main(args As String())
     End '<--- I added this.
  End Sub
End Module

By all appearance, Visual Studio thinks things are just fine (no squiggles).  When I build, the build fails with the following error:

"BC37234: Unstructured exception handling is not supported in current project type."

Huh?  How is 'End' part of unstructured exception handling?  Also, why wouldn't 'End' be supported for a console application on .NET Core?

Thanks.

CC: @KathleenDollard, @cston

**Comment by livarcocc** [comment]
I don't quite follow. Why do we need anything special here? Shouldn't this just work out of the box?

**Comment by nguerrera** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/2793
