### ISSUE TITLE
Windows Update repeatedly reinstalls .NET version 5.0.17

### ISSUE THREAD

**Issue by cabuck** [dotnet/sdk#33887]
Description:
I have been facing an issue with Windows Update continuously reinstalling the .NET SDK version 5.0.17, even after uninstalling it multiple times and deleting the SDK folders. I have verified that .NET 5 is unchecked in Visual Studio, indicating that it should not be installed. However, every time Windows Update runs, the SDK is reinstalled on my system.

Steps to Reproduce:

Uninstall .NET SDK version 5.0.408 using the standard Windows uninstallation process.
Uninstall Asp.Net Core 5.0.17 Shared Framework using Windows uninstallation process.
Delete any remaining SDK folders and files from the system.
Open Visual Studio and ensure that .NET 5 is unchecked under the installed components.
Wait for Windows Update to run and install available updates.
Notice that .NET SDK version 5.0.17 is reinstalled, despite being previously uninstalled.
Expected Behavior:
After uninstalling .NET SDK version 5.0.17 and ensuring it is unchecked in Visual Studio, Windows Update should not reinstall the SDK during the update process.

Actual Behavior:
Windows Update keeps reinstalling .NET version 5.0.17, even though it has been uninstalled and .NET 5 is unchecked in Visual Studio.

Additional Information:

Operating System: Windows Server 2019
Visual Studio Version: 2019 Community Edition

I would appreciate any assistance in resolving this issue and preventing the unwanted reinstallation of .NET version 5.0.17 during Windows Update. Thank you for your attention to this matter.

**Comment by cabuck** [comment]
@joeloff I saw your comment on similar post and wanted to see if you had any suggestions.

**Comment by cabuck** [comment]
Ran query reg query HKLM\SOFTWARE\Microsoft\Windows\currentversion\uninstall /s /d /f "5.0.17" :

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{38CA215A-103C-4C37-A86E-57E49C2220AD}
    DisplayName    REG_SZ    Microsoft .NET AppHost Pack - 5.0.17 (x64_arm)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{3C31CBA1-A0D9-4B95-A807-AD2313D12F47}
    DisplayName    REG_SZ    Microsoft Windows Desktop Runtime - 5.0.17 (x64)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{5A66E598-37BD-4C8A-A7CB-A71C32ABCD78}
    DisplayName    REG_SZ    Microsoft .NET Runtime - 5.0.17 (x64)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{83EE22D9-C7B3-4CBC-9956-9DF0D4D0FF46}
    DisplayName    REG_SZ    Microsoft .NET AppHost Pack - 5.0.17 (x64)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{8BA25391-0BE6-443A-8EBF-86A29BAFC479}
    DisplayName    REG_SZ    Microsoft .NET Host FX Resolver - 5.0.17 (x64)



HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{A95FEF96-3FF2-4387-9301-792B6721F648}
    DisplayName    REG_SZ    Microsoft .NET AppHost Pack - 5.0.17 (x64_x86)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{C1FF10EF-6BCB-3B08-AE1A-0D237C9F9F30}
    DisplayVersion    REG_SZ    5.0.17.22215
    InstallSource    REG_SZ    C:\ProgramData\Package Cache\{C1FF10EF-6BCB-3B08-AE1A-0D237C9F9F30}v5.0.17.22215\
    DisplayName    REG_SZ    Microsoft ASP.NET Core 5.0.17 Shared Framework (x64)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{E61152B0-06C3-4EA3-AE31-13BCB874406A}
    DisplayName    REG_SZ    Microsoft .NET AppHost Pack - 5.0.17 (x64_arm64)


I also ran the query for 5.0.408: 

C:\Users\cabuck>reg query HKLM\SOFTWARE\Microsoft\Windows\currentversion\uninstall /s /d /f "5.0.408"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{20631FA6-D978-41DE-98D0-AFCC1ECA4D4D}
    DisplayName    REG_SZ    Microsoft .NET Toolset 5.0.408 (x64)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\currentversion\uninstall\{AA05EFF3-3AB6-47B9-941B-6E5E72C74A6D}
    DisplayName    REG_SZ    Microsoft .NET Core 5.0 Templates 5.0.408 (x64)

End of search: 2 match(es) found.

**Comment by cabuck** [comment]
I ran msiexec /x {GUID} IGNOREDEPENDENCIES=ALL ALLOWMSIUNINSTALL=1 for each of the guids. Verified all files were removed. Had Windows check for update and it has 5.0.17 listed as a pending install.

![image](https://github.com/dotnet/sdk/assets/55509373/2b0570e0-b03f-476a-ac2d-5f3e8468171a)

**Comment by nagilson** [comment]
Do you have a DELL machine, as DELL has added software which automatically reinstalls this version of the .NET SDK even if you uninstall it. DELL software relies on it, so it will continue to reinstall it and there may not be much you can do. We can collect more logs from you and @/joeloff will reach out about that soon.

**Comment by cabuck** [comment]
It is a virtual machine running Server 2019.

**Comment by nagilson** [comment]
Ok, FYI I deleted the personal information from your comment that your email sent :+1: and updated a link with the problem from DELL

**Comment by cabuck** [comment]
Are there any logs that I can share that may help with troubleshooting this issue?

**Comment by cabuck** [comment]
I still have not been able to resolve this issue. Is there any suggestions on what else I could try on the server?

**Comment by nagilson** [comment]
We did dig into this a long time back and our suspicion is still that this is a problem with DELL software, let me check with the team to see if there is something we can gather from you to further assist.

**Comment by baronfel** [comment]
@nagilson is right here - any OEM, vendor, or other application that redistributes the .NET Runtime can trigger this kind of circular re-installation. We can only suggest that you contact your system vendors and see if they have any troubleshooting steps or updates that move on from these out-of-support runtime versions.
