### ISSUE TITLE
When run a dotnet background service as a unix service is always show "Error: No space left on device"

### ISSUE THREAD

**Issue by 1009058470** [dotnet/sdk#33899]
### Describe the bug
I am follow [this](https://blog.maartenballiauw.be/post/2021/05/25/running-a-net-application-as-a-service-on-linux-with-systemd.html) to build a unix service, but when i to kill them and start them sometimes, it also give a error like this `Error: No space left on device`, and then i try to increase the fs.inotify to a bigger number, it not show that error, but another thing appear that is the very slowly to exec  `Host.CreateDefaultBuilder(args)
                            .ConfigureServices((hostContext, services) =>
                            {
                                services.AddHostedService<T>();
                            }).UseSystemd().StartAsync()`
I wirte a timer in StartAsync like this
```
        public override Task StartAsync(CancellationToken cancellationToken)
        {
            Console.WriteLine("call image worker start");
            Task.Factory.StartNew(CallImageAction, cancellationToken, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            return base.StartAsync(cancellationToken);
        }
CallImageAction is a function to run a timer
```

### Exceptions (if any)
has no that error and the speed for start up app can be normal

### Further technical details
dotnet version : 5.0
os : rhat 7.9 x86_64

**Comment by nagilson** [comment]
Are you able to provide an https://aka.ms//binlog for us to investigate of the process?

**Comment by 1009058470** [comment]
i open another issus [here](https://github.com/dotnet/runtime/issues/99406), this issus has a wrong desc
