### ISSUE TITLE
`-a` sets app to framework-dependent when `SelfContained` is `true`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#34026]
I'm working on some samples and following the excellent guidance at https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/. The guidance doesn't work as intended when I target SCD.

My project file.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSelfContained>true</PublishSelfContained>
  </PropertyGroup>

</Project>
```

In Dockerfile:

```Dockerfile
# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore -a $TARGETARCH

# copy and publish app and libraries
COPY . .
RUN dotnet publish -a $TARGETARCH -o /app
```

This fails.

```bash
5.453 /root/.nuget/packages/microsoft.net.illink.tasks/8.0.0-preview.6.23329.7/build/Microsoft.NET.ILLink.targets(193,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/source/releases.csproj]
```

Works if I do:

```Dockerfile
RUN dotnet publish -a $TARGETARCH -o /app --self-contained
```

We should fix `-a` to be less strong. It should not override `SelfContained` or `PublishSelfContained` if set.

**Comment by nagilson** [comment]
Interesting, yeah it looks like the RID Short-Hand Resolution is called by the Architecture Flag, and if you haven't specified SelfContained then it will inject this: 

`properties = properties.Append("-property:SelfContained=false").ToArray();
`, and since it's injected as a global property it would override your selfcontained or publishselfcontained value.

Not great, good catch! We should fix this.

**Comment by richlander** [comment]
`-property:SelfContained=false")` ... That shouldn't be needed anymore, right?

**Comment by nagilson** [comment]
Ya, that really shouldn't be there anymore. It is definitely going to break people when we fix it (yay) but it should be fixed.

**Comment by nagilson** [comment]
Fix is targeted for rc1 as its too late to fix this for the last preview now

**Comment by richlander** [comment]
What is the PR for this change @nagilson?

**Comment by mthalman** [comment]
@nagilson - Is this fixed in RC1 yet?

**Comment by baronfel** [comment]
No, we haven't done it yet. I'll bring it up at standup today and we'll get it prioritized. Noah's been doing a lot of work on the VSCode extension to support DevKit, and this got lost in the shuffle.

**Comment by nagilson** [comment]
This has been solved by @MiYanni for RC-2. Sorry for forgetting this one, it got put down a continuously growing list for CDK :smile: Thanks again @MiYanni for taking this one up, a document has also been made which @baronfel  attached.
