### ISSUE TITLE
New repo with list of workloads in a .props file

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#34031]
Check compliance for the new repo (SBOM creation)
 Onboard to arcade changes above to produce the package
 Figure out branching structure (presumably by feature band but what about previews)
 Enable darc codeflow from runtime
 enable darc codeflow from maui
 enable insertion pipeline flow into VS for workload set
 investigate whether we need an internal version of the branches/repo

**Comment by MiYanni** [comment]
## Progress
- [ ] Check compliance for the new repo (SBOM creation)
- [ ] Onboard to arcade changes above to produce the package
  - *In-progress*: Set up repo to build using Arcade. Build produces the workloadset.json and basic NuGet package. No MSI package yet until later Arcade changes are present.
- [ ] Figure out branching structure (presumably by feature band but what about previews)
- [ ] Enable darc codeflow from runtime
- [ ] enable darc codeflow from maui
- [ ] enable insertion pipeline flow into VS for workload set
- [x] investigate whether we need an internal version of the branches/repo
  - Configured an internal mirror as it is necessary for producing official builds. Internal pipelines in DNCEng cannot target public GitHub repos.

**Comment by MiYanni** [comment]
Marked as Done three weeks ago. Closing.
