### ISSUE TITLE
Let `dotnet new mstest` can take argument to support os-specific framework

### ISSUE THREAD

**Issue by mingpepe** [dotnet/sdk#34086]
Take Windows as an example, I create a WPF project and it's target framework is `net6.0-windows`. To test it I create a mstest project but according to [this](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#test), `net6.0-windows` is not supported, hence the target framework is `net6.0` which can not reference assembly target with `net6.0-windows`. I can only modify it manually from project file.

### Describe the solution you'd like
Add arguments support for os-specific framework support.

**Comment by marcpopMSFT** [comment]
CC @pavelhorak @nohwnd in case they have a recommendation here as they own that particular template.

**Comment by pavelhorak** [comment]
CC @Evangelink for visibility

**Comment by nohwnd** [comment]
I am up for this improvement. Given that we can actually execute those tests, because there have been some problems with that in the past.
