### ISSUE TITLE
Changing RID to one that hasn't been used before can cause design-time build failure

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3409]
I believe this regressed with #3394 

If you do not have the runtime pack in your nuget cache yet, and you change the RID of your project, the design time build will fail. Unfortunately the test that is specifically designed to test this case of changing RIDs is not reliable because dependening on state of nuget cache (say due to tests that have already run), it may pass even though the bug is present.

We need a better approach than just skipping ResolveRuntimePackAssets always in design-time builds as was done before #3394, but we can't have it fail as this will block the nomination that would restore the runtime pack.

**Comment by nguerrera** [comment]
Re-enable DesignTimeBuildSucceedsAfterRuntimeIdentifierIsChanged when fixing this, and consider finding a way to make it insensitive to what's already in nuget cache.

**Comment by dsplaisted** [comment]
To avoid the test flakiness where the package is already downloaded to the NuGet packages folder, some tests override the packages folder to be local to the test project.  Of course, the more tests that do this the slower the tests will run and the bigger the test folder will get.
