### ISSUE TITLE
Native AOT doesn't work with Windows Forms

### ISSUE THREAD

**Issue by mikola-akbal** [dotnet/sdk#34129]
I add to the .NET 7 .csproj file following:

```
<PublishAot>true</PublishAot>
<_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
```

When I try to publish, I get unknown error.

Could you, please, make Windows Forms compatible with trimming? I love Windows Forms. I would prefer compile my applications to native code.

Can you estimate **when** Native AOT will support Windows Forms?

Can I compile Windows Forms assemblies **without** trimming? Is there some option to manage it? This option can be fast solution of this problem. The executable will be big, but it will be. When trimming of Windows Forms will be realized, executable will become small.

**Comment by vitek-karas** [comment]
The tracking issue for WinForms trim compatibility is here: https://github.com/dotnet/winforms/issues/4649
Trimming is necessary for AOT, so that's the first step.

**Comment by nagilson** [comment]
I'm glad to see there is demand for the feature :) You'll have to ask about the time estimates for the work on that issue, though I would imagine there are 'goals' set more so than a firm date we would be able to give you yet. I am not involved with that effort or their timeline.
