### ISSUE TITLE
Convert remaining project.json to PackageReference

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#342]
Templates\ and Dependencies\ projects still use project.json

The templates now fail to fully restore with `dotnet nuget restore` and have been switched to use nuget.exe v3.4.4 since we only build templates on Windows. This can remain, but we probably want to just switch everything the packageref for consistency.

The dependencies are still using `dotnet nuget restore` since we need to build them xplat, but I am told that project.json restore via `dotnet nuget restore` is not supported and so these MUST be changed to PackageReference.

**Comment by dsplaisted** [comment]
Dependencies\ now uses `PackageReference`, and the templates are no longer part of this repo.
