### ISSUE TITLE
Generate runtimeconfig.json with rollForwardOnNoCandidateFx value from csproj?

### ISSUE THREAD

**Issue by tlmii** [dotnet/sdk#3426]
Is it possible to specify the value of [rollForwardOnNoCandidateFx ](https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md#runtimeoptions-section-runtimeconfigjson)that will be in the output `[AppName].runtimeconfig.json` from the .csproj file (or otherwise within the source code)? Or does it have to be added after the fact?

**Comment by livarcocc** [comment]
You can set `<RollForward>Disable</RollForward>` in your csproj. It will have that same effect.
