### ISSUE TITLE
Append TargetFramework to *OutputPaths only when MultiTargeting

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/sdk#3432]
Rleated issues: #844 #550 #1376 (those github found out)

For single targeting projects, we don't need to appened the `*OutputPath`s properties with `TargetFramework` since, we are only targeting single framework. This is also the behavior of the old projects before sdks were introduced.

1. All the large winforms and wpf projects have custom targets that rely on hard coded paths based on the defaults set by the old project files. It'll be easy to migrate those projects if those paths were the same. 😌

2. It'll reduce a directory overhead in the directory tree. One less dir to navigate! 😌

We can update the targets to preserve the old behavior that only appends the `TargetFramework` property only when it's multi-targeting.

I can do a PR if you guys are ok with this!

**Comment by Nirmal4G** [comment]
I'm aware of `AppendTargetFrameworkToOutputPath` property, what I suggest is that we make it default.

**Comment by 0xd4d** [comment]
It would be a breaking change to change it now. Use the above property instead. If you have many projects you can use a [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) file.

**Comment by Nirmal4G** [comment]
.NET Core 3, is a major revision, This might not be that big of a breaking change when you take the old projects into account!

**Comment by nguerrera** [comment]
It was discussed early on pre-1.0 and a deliberate decision was made to make the directories consistent irrespective of one or many target frameworks.

It is also too late in .NET 3 cycle to take a substantial breaking change here. Further,more we aim not to break existing projects on major versions. You can end up crossing an SDK major boundary in a minor VS update, so there is never really a clear indication of when you can expect a break to something as fundamental as where your dll ends up. Even if there were such a point in time, we would not use it lightly.

There would be significant fallout from this. Not only would it break users, it would introduce new issues when switching between TargetFramework and TargetFrameworks, and building incrementally, etc.

I don't think we should do this, but we can discuss it as part of .NET 5 timeframe, no sooner.

**Comment by nguerrera** [comment]
> This might not be that big of a breaking change when you take the old projects into account!

We do not consider issues porting to .NET Core breaking. We have talked about some features to make getting classic settings easier.

A breaking change in the context of the SDK is when you get a new SDK, do not change anything in your project, and something breaks. The proposal is very much that.

**Comment by Nirmal4G** [comment]
> A breaking change in the context of the SDK is when you get a new SDK, do not change anything in your project, and something breaks.

I understand. Still this should be the natural outcome considering the old projects.

> It is also too late in .NET 3 cycle ...

It's true, I was a bit late!

But can we add it to the `Microsoft.NET.Sdk.WindowsDesktop`?

**Comment by Nirmal4G** [comment]
> There would be significant fallout from this. Not only would it break users, it would introduce new issues when switching between TargetFramework and TargetFrameworks, and building incrementally, etc.

We can use `AppendTargetFrameworkToOutputPath` to revert to older behavior! In any case if any project breaks, we can use the above property to revert to the older behavior.

I did this change in my installation, yes directly on the files, It did break some of my new projects (where the path was hardcoded), but was able to fix them all with just simple property change. It also worked for my older projects without messing with the paths.

**Comment by Nirmal4G** [comment]
I can send you a diff of my change if you want to look at it.

**Comment by livarcocc** [comment]
I disagree in making this breaking change for one kind of project but not for others. I believe differences like that make reasoning about the different project types harder.

There is a property to opt-out of this behavior if someone wants to, but at that point they made that decision explicitly.

Other than that, when you are moving to .net core, this is one of the differences you will have to learn/deal with.

**Comment by Nirmal4G** [comment]
It's okay, but to me understanding this change was natural and easy.

You have been targeting one framework (.NET or Silverlight), so you know there was no subfolder under which the build outputs. Then you begin to multi-target, it becomes clear, you need a subfolder with each framework you're targeting.

This was similar to AnyCPU vs CPU specific (x86, x64, etc...) subfolders. If it was CPU specific, you add those subfolders, if it's not you don't.

Whatever we target specifically, we can add subfolders for that target, whether it is `RuntimeIdentifier`, `Platform` and `TargetFramework`. That was my understanding.

Hope I'm not too late for .NET 5.

**Comment by livarcocc** [comment]
This is not just a matter of where in the release you filled the issue. I disagree with the proposed change as a principal. I believe there is more value in having all projects, irrespective of type, behave the same in this regards rather than have to say how each one behaves differently. One is simply much easier to explain as there is a clear pattern than the other. Even though I appreciate it is a departure for those coming from full framework.

**Comment by Nirmal4G** [comment]
So, will you be looking to change the behavior of appending the `Platform` and `RuntimeIdentifier` to the `*OutputPath` in the future, to align more closely with the behavior of appending the `TargetFramework`?

And what happens if there were no framework to target? Will it replaced with `TargetRuntime` or `RuntimeIdentifier` or just a default string (say `dotnet`)?

**Comment by livarcocc** [comment]
The `RuntimeIdentifier` is already appended to the `OutputPath` when one is specified. Note though that this is only true when `RuntimeIdentifier` is specified, not the plural version of it. When the plural version is used, it is used by restore to make all the packages you need available during one single restore, but during build you need to specify one to trigger the build to happen for that RID. There is no inner/outer loop for RIDs.

'Platform' is also appended to the `OutputPath` when it is specified. So, at this point it is not exactly clear to me what your ask is regarding those two properties.

Lastly, for .NET Core projects (or rather sdk style projects), a `TargetFramework` is necessary, so your last condition does not apply.

**Comment by Nirmal4G** [comment]
I'm sorry, I meant `RuntimeIdentifier` to `PublishDir`. Anyway I understand what you mean.

**Comment by Nirmal4G** [comment]
> `Platform` is also appended to the `OutputPath` when it is specified. So, at this point it is not exactly clear to me what your ask is regarding those two properties.

https://github.com/dotnet/sdk/blob/3078929ecbe4df57dbb8fe30b875c6d524334970/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets#L33-L34

https://github.com/dotnet/sdk/blob/3078929ecbe4df57dbb8fe30b875c6d524334970/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets#L39-L40

As you can see, the `Platform` is ignored when it's `AnyCPU` but appeneded for any other case.

**Comment by Nirmal4G** [comment]
> `Platform` is also appended to the `OutputPath` when it is specified. So, at this point it is not exactly clear to me what your ask is regarding those two properties.

https://github.com/dotnet/sdk/blob/3078929ecbe4df57dbb8fe30b875c6d524334970/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets#L33-L34

https://github.com/dotnet/sdk/blob/3078929ecbe4df57dbb8fe30b875c6d524334970/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets#L39-L40

As you can see, the `Platform` is ignored when it's `AnyCPU` but not for any other case.

**Comment by Nirmal4G** [comment]
> Lastly, for .NET Core projects (or rather sdk style projects), a TargetFramework is necessary, so your last condition does not apply.

#### [Introducing .NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/)

> Moving to a single .NET implementation raises important questions. **What will the target framework be?** Will NuGet package compatibility rules be the same? .......

The only reason `TargetFramework` was there because of the set of libs we need to target, ensuring lock-in with the Framework and Runtime implementation so that a library targets a particualar framework (along with a particluar runtime) does not run on the other implementations.

#### [With .NET 5](https://www.youtube.com/watch?v=ZlO1utbB2GQ&t=3150s)

> Defined a minimal layer that defines the runtime <-> managed code layer, with the goal making >99% of CoreFX common code.

We target the `Runtime` (a combination of System and Architecture) and except the native libs, the managed ones will be almost same. Then there's the concept of `FrameworkReference`. So, with all that I'm thinking maybe `TargetFramework` will be there, implicitly.

**Comment by livarcocc** [comment]
If `TargetFramework` becomes optional, we would consider changing how things work for `OutputPath`. But we will not look into changing `OutputPath` at this point based on the possibility that `TargetFramework` will change.

Based on that and the other discussions on this issue, we have no plans to change how `AppendTargetFramework` works today or the defaults to `OutputPath`. Again, if something does change in NET 5 that would interact with it, we will consider it, but we will do so as part of that other change rather than on isolation.

Given that, I am going to close this issue.

Thank you for bringing it up and discussing it with us.

**Comment by Nirmal4G** [comment]
That I got it, breaking change and all. I thought you would be willing to change it for the Desktop SDK, since it is for windows only and the path would match older projects. That would lead to confusion as well.

**Anyway, thanks for listening**. I also found that Desktop SDK is in WPF repo. It's just that changing some _bad_ behaviors and keeping my own changes is in separate SDKs is a major pain.

**Comment by Nirmal4G** [comment]
> Again, if something does change in NET 5 that would interact with it, we will consider it, but we will do so as part of that other change rather than on isolation.

Then, Can you keep it open until .NET 5 SDK design is made final?

**Comment by livarcocc** [comment]
I would rather not. Like I said, we would look into this if TargetFrameworks change anyways and we would change this for that. We would not change this independently.

**Comment by robinrodricks** [comment]
Just adding this comment to help others who might wanna do this.

I can confirm this IS supported in .NET 7 onwards, using this `csproj` declaration:

```xml
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>C:\Target\Folder\</OutputPath>
  </PropertyGroup>`
```

This will cause your project binaries to be outputted directly into `C:\Target\Folder\` without the `net7.0` or `Release` subfolders.

Hope it helps!

**Comment by Nirmal4G** [comment]
@robinrodricks I knew it already but thanks for posting it.

Also, do note that the point of this issue is to do this automatically, since when we use single target, we don't need to distinguish, since there's nothing to distinguish.

Anyway, MS will always be afraid of making changes like this. I attempted but as you can see, no avail.
