### ISSUE TITLE
Non-descriptive error on .NET Microsoft.NET.Build.Containers deploy DN8.P6

### ISSUE THREAD

**Issue by johnW-ret** [dotnet/sdk#34329]
### Describe the bug
When publishing an app to Azure Container Apps (Linux) using .NET 8 Preview 6 with Visual Studio, the task fails with `Error MSB4018: The "CreateNewImage" task failed unexpectedly.
System.InvalidOperationException: CONTAINER4002: Required 'Entrypoint' items were not set.`.

I believe that the intended behavior is that the entrypoint should be set if omitted and that the task should succeed because that is what happens when targeting `net7.0`, that [the csproj](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/tutorials/scalable-razor-apps/start/ScalableRazor.csproj) from [Deploying and scaling an ASP.NET Core app on Azure Container Apps](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps) does not set [`ContainerEntrypoint`](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container#containerentrypoint), and that there is nothing I have found to lead me to believe the intended behavior changed in `net8.0`.

Setting the `ContainerEntrypoint` with
```csproj
<ItemGroup Label="Entrypoint Assignment">
	<ContainerEntrypoint Include="dotnet;ApiTestAzureContainerApp.dll" />
</ItemGroup>
```
causes the error to go away (though it does not on my .NET 8 new Blazor Web App project, exact same error - perhaps for different reasons, I still need to investigate and perhaps is an issue for dotnet/aspnetcore).

### To Reproduce
A custom repro is absent because this behavior can be observed when publishing from the default templates (specific versions on my machine posted below). For example
> Visual Studio 2022 Preview > New Project > ASP.NET Core API > (default settings) > .NET 8.0 (Preview), Enable Docker off > Build > Publish [app name] > Target: Azure > Specific target: Azure Container Apps (Linux) > set Container App and Registry > Container build: .NET SDK > Finish and Close > click Publish on new `pubxml`

[Publishing the app as a container via `dotnet publish`](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container#publish-net-app) does not fail, only when doing so as part of the Azure Container App `pubxml` publish process.

### Exceptions (if any)
```
C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Containers\build\Microsoft.NET.Build.Containers.targets(201,5): Error MSB4018: The "CreateNewImage" task failed unexpectedly.
System.InvalidOperationException: CONTAINER4002: Required 'Entrypoint' items were not set.
   at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.GenerateCommandLineCommandsInt() in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs:line 77
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Further technical details
- `dotnet --info`
  ```
  .NET SDK:
   Version:   8.0.100-preview.6.23330.14
   Commit:    ba97796b8f
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.22621
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\
  
  .NET workloads installed:
  There are no installed workloads to display.
  
  Host:
    Version:      8.0.0-preview.6.23329.7
    Architecture: x64
    Commit:       5340be2ccc
  
  .NET SDKs installed:
    7.0.300-preview.23179.2 [C:\Program Files\dotnet\sdk]
    7.0.302 [C:\Program Files\dotnet\sdk]
    7.0.306 [C:\Program Files\dotnet\sdk]
    7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
    8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  Other architectures found:
    x86   [C:\Program Files (x86)\dotnet]
      registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
  
  Environment variables:
    Not set
  
  global.json file:
    Not found
  ``` 
- ```
  Microsoft Visual Studio Community 2022 (64-bit) - Preview
  Version 17.7.0 Preview 3.0
  ```

**Comment by baronfel** [comment]
Hi @johnW-ret - this should be fixed with https://github.com/dotnet/sdk/pull/34311, but this likely won't be available until .NET SDK 8.0.100-rc1 due to scheduling.  As a workaround, you should be able to set your own `ContainerEntrypoint` items like we did in previous versions of the tool as you noted in your issue.

**Comment by johnW-ret** [comment]
Thanks for your help 😀

---
To follow up on this, 

> ...causes the error to go away (though it does not on my .NET 8 new Blazor Web App project, exact same error - perhaps for different reasons, I still need to investigate and perhaps is an issue for dotnet/aspnetcore).

I tried creating a new Blazor Web App project from the template, setting the `ContainerEntrypoint` manually, and immediately publishing - and while the prior error goes away, viewing the `/app` directory in the Console on Azure shows that the app did not actually publish and failed with no error.

On my non-from-scratch new Blazor project, the fix for the `CreateNewImage task fails` error was fixing the `ContainerEntrypoint` dll path since my app wasn't located at sln root. However upon publishing, almost immediately after `Waiting for container app to be ready...`, the task fails with the following error:
> Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details.

Yet no errors are printed into the output log and the publish finishes with `Container app is ready.`. Checking the Console on Azure again shows that the app did not actually publish.

---

Because a clean API project succeeds with the fix we discussed, I imagine this is an issue for dotnet/aspnetcore, but I thought it was worth mentioning here since I mentioned it above and hopefully someone has a crumb to get me on the right breadcrumb trail.

**Comment by baronfel** [comment]
Do  you have access to an https://aka.ms/binlog for your failing Blazor scenario @johnW-ret? That might help us figure out what's going on here faster.

**Comment by johnW-ret** [comment]
> Do you have access to an https://aka.ms/binlog for your failing Blazor scenario @johnW-ret? That might help us figure out what's going on here faster.

I followed these steps to capture logs for [all MSBuild invocations through VS](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md#capturing-binary-logs-through-visual-studio). I immediately clicked Publish for each project using the existing pubxml then captured the logs upon finish.

> ℹ️ NOTE: I am very new to this (and appreciative of the resources! never knew this was out there!), and would be happy to narrow down the scope if this is information overload. There aren't any sensitive env vars, so I thought I'd just capture everything.

[These](https://github.com/dotnet/sdk/files/12210349/BlazorApp9.zip) are the `MSBUILDDEBUGPATH` outputs for the clean repro that doesn't error but fails to publish. [These](https://github.com/dotnet/sdk/files/12210357/RetruateWeb.zip) are the outputs for my personal project that gives a non-specific error (`Publish has encountered an error. We were...`) in the editor with nothing additional in the out logs.

**Comment by johnW-ret** [comment]
I was able to eliminate / diagnose one of the cases.

> [These](https://github.com/dotnet/sdk/files/12210349/BlazorApp9.zip) are the `MSBUILDDEBUGPATH` outputs for the clean repro that doesn't error but fails to publish.

The issue in the clean repro is that the ASP.NET Core defaults to port `8080` (and `8081` for https) and the Ingress settings on Azure defaults to port `80`. Visual Studio immediately health pings the container after pushing the container image, which succeeds because Container apps come with a hello world container but the new one has not finished provisioning. Due to the port issue, the container stays "Provisioning" for several minutes until it timeouts and is given "Degraded" status, where the app defaults back to the previous running container.

Changing the Ingress Target Port to `8080` resolves this issue. In retrospect, this should have been obvious, and I swear I tried changing it among a bunch of other changes like setting `ASPNETCORE_URLS` and generating and exposing customer ports on a manual Dockerfile, but I must have not tried it or made some other change that caused an additional issue.

---

> [These](https://github.com/dotnet/sdk/files/12210357/RetruateWeb.zip) are the outputs for my personal project that gives a non-specific error (`Publish has encountered an error. We were...`) in the editor with nothing additional in the out logs.

This project still encounters the same error, however, I was able to successfully deploy it using the default generated Dockerfile (Add > Docker Support...).

**Comment by baronfel** [comment]
I think we've addressed the two things you reported here, right?

* Entrypoint messed up, fixed in rc1
* ASP.NET ports changed between p4 and p6, which folks just have to adjust to - that's been logged as a breaking change for the [.Net Containers](https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port)

Given that, I'm going to close this issue. Please let me know if I've missed something and we need to reopen.
