### ISSUE TITLE
Breaking change due to default setting of certain properties

### ISSUE THREAD

**Issue by mavasani** [dotnet/sdk#3433]
PR https://github.com/dotnet/sdk/pull/511/ added default values for certain build related properties to fix https://github.com/dotnet/roslyn-project-system/issues/437 - indeterminate setting of corresponding check boxes in properties page.

However, this causes breaking issues when moving from old project system to new project system. The C# targets do not set any default for these properties, which means that if my repo on old project system had the following conditional property after importing the common targets, then this condition will evaluate to true for old targets imports, but false for the new SDK imports:

`<SignAssembly Condition="'$(SignAssembly)' == ''">true</SignAssembly>`

For example see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/build/Targets/Analyzers.Settings.targets#L18). This led me to spend half a day investigating IVT failures after porting the analyzers repo to new project system due to the fact that this breaking change silently turned off `/keyfile` command line argument.

Given that the above SDK change was only done to satisfy the property pages, we should find a different workaround.

**Comment by davkean** [comment]
Move this over to SDK. This is SDK-driven property any changes here would be up to them.

**Comment by nguerrera** [comment]
Closing as the prior break occured in 2016 when we had a lot fewer users. Changing this now would just break more things.
