### ISSUE TITLE
`dotnet run` help doesn't show help about `--urls`

### ISSUE THREAD

**Issue by timheuer** [dotnet/sdk#34386]
When discussing with some new .NET devs working on microservices they were trying to find how to start an app with a 'host' rather than any defaults (so they could configure the IP/port).  The correct answer is `dotnet run --urls=http://localhost:12345` but in `dotnet run --help` this argument is not shown anywhere.

**Comment by MiYanni** [comment]
I searched for `--urls` in the code for this repo and there's no results. Did some more research, and it seems to be a [configuration override for an ASP.NET web host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-7.0#override-configuration). I'm not ramped up on the CLI (yet) but briefly looking at the code, it looks like it automatically forwards any arguments it can't process as native `dotnet run` arguments. Therefore, it is sending `--urls=something` to the application. Also AFAIK, the dotnet CLI doesn't have any options that use the `=` syntax to separate the keyword from the value. There is always a ` ` (space) between them. The documentation I linked also seems to suggest using a space.

![image](https://github.com/dotnet/sdk/assets/17788297/f6441ec0-467b-4990-8e13-913a8406914b)

Let me know if there is any confusion about this, @timheuer

**Comment by baronfel** [comment]
+1 to what @MiYanni said - we just forward any tokens along to the underlying app (that aren't tokens that `run` understands), and the default ASP.NET web host builder doesn't provide anything useful for `--help` in this case. One thing that may also help here is that `run` can use a specific Launch Profile via the `--lp` option, and it's a nice way to 'name' different ports. Finally in .NET 8 there's a great new environment variable that makes this even easier: `ASPNETCORE_HTTP_PORTS=12345 dotnet run` would start the app on `http://+:12345`, which I think is going to be my preferred way going forward.

**Comment by marcpopMSFT** [comment]
Per above comments, we pass through parameters to the running app and aspnet is parsing this parameter.  We have no knowledge of this or other web arguments so we can't include it in help as we don't have help that's different depending on your type of application. Aspnet should implement as command line help so a customer could do `dotnet run -- --help` to get the help from there.
