### ISSUE TITLE
remove EnableWindowsTargeting

### ISSUE THREAD

**Issue by anatawa12** [dotnet/sdk#34495]
I think `EnableWindowsTargeting` guard for non-windows is a little annoying.

I don't know exactly why `EnableWindowsTargeting` property is exists, but I think one big reason is that apphost generation for windows GUI app requires windows.

In dotnet/runtime#89303, apphost generation for windows GUI app is now compatible with non-windows.
If there are no other reasons for `EnableWindowsTargeting`, I think it can be good to remove `EnableWindowsTargeting` guard for non-windows platform.

I'm sorry if there are some other reason why `EnableWindowsTargeting` is exists. However, I think it's better to have some documentation why `EnableWindowsTargeting` is exists.

**Comment by marcpopMSFT** [comment]
There is more details on why this flag was added in [this documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1100). The flag is there for targeting pack downloads on non-windows platforms rather than related to the apphost.
