### ISSUE TITLE
WPF for VB build failed with error BC2017: could not find library 'Microsoft.VisualBasic.dll'

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/sdk#3450]
@YunWeiaa commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1346)

* .NET Core Version: 3.0.100-preview8-013392
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013392
 Commit:    37875bfd17

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013392\

Host (useful for support):
  Version: 3.0.0-preview8-27919-09
  Commit:  3fcf1dac55

.NET Core SDKs installed:
  3.0.100-preview8-013377 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013392 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19371.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19372.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-27919-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-27919-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-27919-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-27919-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Windows version: windows 10 1809 17763.437

 
 
 **Problem description:**
 Create a WPF app via CLI. Build 
```
dotnet new wpf -o vbwpf -lang vb
cd vbwpf
dotnet build 
```

 **Actual behavior:** 
 Dotnet build failed with error BC2017: could not find library 'Microsoft.VisualBasic.dll'
![image](https://user-images.githubusercontent.com/33921754/61700175-dac71a00-ad6e-11e9-8055-a7d4872940ce.png)

 **Expected behavior:**
 Build succeeded.

 

---

@YunWeiaa commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1346#issuecomment-514141226)

Note: WPF for c# build and run successfully.

---

@grubioe commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1346#issuecomment-514330319)

This will succeed with build 3.0.100-preview7-012821.  Can you try with this build?  Thanks

---

@vatsan-madhavan commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1346#issuecomment-514428977)

Create a `global.json` for your app using `dotnet new globaljson --sdk-version 3.0.100-preview7-012821` and build against that. 

If you don't have that SDK, you can install it using the scripts at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script.

**Comment by vatsan-madhavan** [comment]
@KathleenDollard, @jmarolf and I noticed this while onboarding WPF project templates for user-control and custom-control. Now we also have a customer report. 

Looks like the latest preview8 SDK generates errors while building, whereas earlier preview7 builds worked ok.

**Comment by livarcocc** [comment]
@nguerrera can you take a look?

**Comment by nguerrera** [comment]
Yes, I'll take a look

**Comment by nguerrera** [comment]
The issue is with the WPF temporary project compilation. It doesn't run ResolveAssemblyReferences, it generates a list of hard-coded ReferencePath in the temporary project. My target that finds the VB runtime among ReferencePath doesn't run and so the /vbruntime argument is not passed to the compiler. I will have to tweak how that target is scheduled.
