### ISSUE TITLE
Bring Tye features into the SDK

### ISSUE THREAD

**Issue by AndrewBabbitt97** [dotnet/sdk#34535]
### Is your feature request related to a problem? Please describe.
Tye is an existing dotnet tool for developing, testing, and deploying microservices / distributed applications. It is operated under the .NET GitHub organization [here](https://github.com/dotnet/tye).

It is a wonderful tool, one that has actually become highly used and desired in the .NET ecosystem. However as of recently it has become neglected and deserves more love. To many of us it feels abandoned.

### Describe the solution you'd like
I raised an issue on the project around a year ago asking about the state of the tool and it was well received. I feel like Tye as a whole deserves more attention or for its functionality to be brought into the SDK.

The issue I opened may be found here: dotnet/tye#1459

Seeing as container building and cloud native tooling has become a bigger focus on the SDK, it feels like a natural next step for orchestration to make its way to the SDK.

In general some of the biggest things people want include:

- Running multiple .NET services with one command (tye run)
- Hot reloading and watching services as source code changes (tye run --watch)
- Use dependent service containers (ex. Postgres database)
- Ingress
- Service discovery
- Built in tracing through Zipkin
- Built in logging aggregation through Elastic and Seq
- Built in Dapr support
- Built in Azure Functions support

Tye also includes tooling to generate Kubernetes manifests, however I as well as others have agreed that Tye is not currently flexible enough to satisfy most peoples needs on the deployment side. Most opt to build out their own helm charts and manifests for deployment. For most this is perfectly acceptable.

The developer inner loop is where Tye really shines and is what would be really beneficial to have in the SDK.

### Additional context
I am making this issue as starting point for a real discussion over the future of Tye as well as cloud native tooling in the SDK, as even though we got responses from devs in the org on that issue, we don't actually have any concrete plans. My goal is for actionable items to come out of this conversation.

**Comment by onionhammer** [comment]
Yes please, something more is needed

**Comment by timheuer** [comment]
Can we close this? https://github.com/dotnet/tye/issues/1622 /cc @davidfowl

**Comment by davidfowl** [comment]
Yep

**Comment by AndrewBabbitt97** [comment]
You all did more than I was expecting, so yes this issue can now be closed. Thanks for all the work on the Aspire team 😄
