### ISSUE TITLE
Add flag for --workload-state when installing/update workloads for the old install behavior

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#34561]
`dotnet workload update --workload-state global` state saved into programdata on whether to use workload sets or not

**Comment by marcpopMSFT** [comment]
@baronfel we need to confirm the parameter name here

**Comment by baronfel** [comment]
The flag we use should be `--mode`, and it should have 
* `auto`,
* `workloadSet`, and
* `looseManifest` options 

For the initial release, `auto` will default to `looseManifest`. Once we have a certain amount of stability/feedback/confidence in the mechanism, `auto`'s semantics can be changed to `workloadSet`.
