### ISSUE TITLE
Dotnet SDK Installed via Snap is not working with Entity Framework Tool

### ISSUE THREAD

**Issue by shakeelansari63** [dotnet/sdk#34590]
### Describe the bug
Dotnet EF installed via Dotnet Snap Package. But When running `dotnet ef` command it is not able to find Dotnet command location.

### To Reproduce

1. Install Dotnet SDK from Snap Store - 
```
sudo snap install dotnet-sdk --classic
```

2. Set a location where we can install Dotnet Tool and add it to Path. 
```
mkdir ~/.dotnet-tool
export PATH=$PATH:${HOME}/.dotnet-tool
```

3. Install Dotnet Entity Framework to this path
```
dotnet tool install --tool-path=${HOME}/.dotnet-tool dotnet-ef
```

4. Now run Dotnet Ef
```
dotnet ef --help
```
### Exceptions (if any)

```
$ dotnet ef --help
You must install .NET to run this application.

App: /home/freak/Freak/Apps/DotnetTools/dotnet-ef
Architecture: x64
App host version: 7.0.9
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=endeavouros-x64&apphost_version=7.0.9
```
  
### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
$ dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     endeavouros
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /var/lib/snapd/snap/dotnet-sdk/216/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/var/lib/snapd/snap/dotnet-sdk/216/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/var/lib/snapd/snap/dotnet-sdk/216/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/var/lib/snapd/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by joeloff** [comment]
Can you try setting `DOTNET_ROOT` to `/var/lib/snapd/snap/dotnet-sdk/216/` where the dotnet host is located?

**Comment by shakeelansari63** [comment]
> Can you try setting `DOTNET_ROOT` to `/var/lib/snapd/snap/dotnet-sdk/216/` where the dotnet host is located?

Setting DOTNET_ROOT variable does nothing. I still can't install an older version of SDK inside same snap.

**Comment by shakeelansari63** [comment]
> Can you try setting `DOTNET_ROOT` to `/var/lib/snapd/snap/dotnet-sdk/216/` where the dotnet host is located?

Yeah, setting the DOTNET_ROOT to snap SDK path does the trick. And I set it to current path i.e. `/var/lib/snapd/snap/dotnet-sdk/current/` which should work even after the snap package is updated.

**Comment by shakeelansari63** [comment]
Setting DOTNET_ROOT to `/var/lib/snapd/snap/dotnet-sdk/current/` resolves the issue. Good to close this.

**Comment by programmersEmperor** [comment]
> Can you try setting `DOTNET_ROOT` to `/var/lib/snapd/snap/dotnet-sdk/216/` where the dotnet host is located?

can you show me how to do so in Ubuntu 22.04 terminal?

**Comment by akhakpouri** [comment]
@shakeelansari63 this solution doesn't work when both `.net` and `dotnet-ef` have been upgraded to the latest version.

```
dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/233/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/snap/dotnet-sdk/233/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/snap/dotnet-sdk/233/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/snap/dotnet-sdk/233/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/snap/dotnet-sdk/233/]

global.json file:
  Not found
```
You can see that I have the `DOTNET_ROOT` set to `/snap/dotnet-sdk/233/` but when I run `dotnet ef`, I'll get the following exception:
```
You must install or update .NET to run this application.

App: /home/akhakpouri_linux/.nuget/packages/dotnet-ef/8.0.1/tools/net8.0/any/dotnet-ef.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.1' (x64)
.NET location: /snap/dotnet-sdk/233/

The following frameworks were found:
  8.0.0 at [/snap/dotnet-sdk/233/shared/Microsoft.NETCore.App]

```

**Comment by akhakpouri** [comment]
For the record, if you're installing `dotnet-sdk-8.0.xx` using snap, you'll run into this issue no matter what you've set the `DOTNET_ROOT` to. The problem is that snap installs the sdk in `/snap/dotnet-sdk` instead of `$home/.dotnet/sdk`. 

The only way I've been able to get both `.net-sdk` and `dotnet-ef` to work is to perform the followings:

- remove `dotnet-sdk` by `snap remove dotnet-sdk`
- remove `.dotnet` directory by `rm ~/.dotnet`
- remove `rm /snap/dotnet` or `/rm /snap/dotnet-sdk` if they exist.

You want to install the `dotnet-sdk` using script installation mentioned on microsfot's [documentation](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install). After running through the installation, make sure to follow the steps in **Set environment variables system-wide** [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#set-environment-variables-system-wide).
