### ISSUE TITLE
dotnet nuget trust command doesn't work in 8.0.0-preview.7

### ISSUE THREAD

**Issue by heng-liu** [dotnet/sdk#34610]
### Describe the bug
dotnet nuget trust command doesn't work in the latest 8.0.0-preview.7 ( 8.0.100-preview.7.23376.3)

### To Reproduce
Run `dotnet nuget trust certificate MyCompanyCert 788D94235338D9395DA5804905C0B5F20F2AE4D527B5FE356D4E0C1DCF809ABC` command, the output is:
```
Unrecognized command or argument 'MyCompanyCert'.
Unrecognized command or argument '788D94235338D9395DA5804905C0B5F20F2AE4D527B5FE356D4E0C1DCF809ABC'.
```
But this command works well in an older version.

### Further technical details
There is a related change in dotnet/sdk repo: https://github.com/dotnet/sdk/pull/33157, updating the src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs  file. It might be the reason why this command is broken.

**Comment by baronfel** [comment]
Looks like the definition of the trust command only defines a grammar up to the `dotnet nuget trust certificate` level - there's no grammar for tokens/arguments past that. My guess is that this has been 'broken' for a while now, and some other handling (the `Tokens` list on `parseResult.GetArguments()` ?)  that was recovering from this grammar.

My suggestion for `trust` would be to model the subcommands for the different kinds of entity to trust, or to do a 'catch all' by adding an `Argument<IEnumerable<string>> OtherArguments` argument to the trust command to allow it to gather all other unknown tokens. We do this for other commands that need to capture tokens to forward along, like `dotnet run` or `dotnet build`.

**Comment by marcpopMSFT** [comment]
linked PR was merged
