### ISSUE TITLE
[NETSDKE2E] [Regression]With 8.0.100-rc.1.23414.11 installed, the RID shows incorrectly on Linux Alpine3.18 Arm64

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#34627]
### Environment:
Alpine3.18 Arm64 in docker
.NET 8.0.100-rc.1.23414.11(runtime-8.0.0-rc.1.23414.4)

### To Reproduce
Repro steps:

1. Prepare Alpine3.18 Arm64 in docker

2. Extract dotnet-sdk-8.0.100-rc.1.23414.11-linux-musl-arm64.tar.gz, and use the export command to set DOTNET_ROOT to the extracted folder's location and then ensure .NET is in PATH

3. Run 'dotnet --info' and observe

### Expected behavior
RID shows "alpine.3.18-arm64".

 ### Actual behavior
RID shows "linux-musl-arm64"
![alpinearm641](https://github.com/dotnet/sdk/assets/99376012/569f4ab2-b056-49c6-8345-f32b81a7939f)
### Regression?
This issue not repro on 8.0.100-rc.1.23407.2(runtime- 8.0.0-rc.1.23381.3)
![alpinearm642](https://github.com/dotnet/sdk/assets/99376012/c2be425f-428d-40d8-9340-8dfc81933b2f)

**Comment by martincostello** [comment]
I've noticed a similar issue just now with Windows too.

The RID has changed from `win10-x64` to `win-x64`.

This is then causing `dotnet publish --self-contained --runtime win10-x64` to fail with this error:

```
Error: /usr/share/dotnet/sdk/8.0.100-rc.1.23414.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'win10-x64' is not recognized.
```

### `8.0.100-rc.1.23412.1`

```
❯ dotnet --info
.NET SDK:
 Version:   8.0.100-rc.1.23412.1
 Commit:    e9e2e45de3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Coding\martincostello\website\.dotnetcli\sdk\8.0.100-rc.1.23412.1\
```

### `8.0.100-rc.1.23414.11`

```
❯ dotnet --info
.NET SDK:
 Version:   8.0.100-rc.1.23414.11
 Commit:    1c0b692a4e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Coding\martincostello\api\.dotnet\sdk\8.0.100-rc.1.23414.11\
```

**Comment by marcpopMSFT** [comment]
@dsplaisted @elinor-fung is this fallout of the simplified ridgraph changes?  @v-xiaofchen @martincostello  Does seting UseRidGraph to true fix this?

See this for more details:
https://github.com/dotnet/sdk/pull/34279

**Comment by martincostello** [comment]
I wasn't sure if this was an intentional change or not (I did do a quick Google search for something but I didn't find anything). I realise that ingesting daily builds means that I'm probably getting intentional things _before_ they're officially communicated to users.

If this is intended and the end-result behaviour is the same, then I can update my testing branch to publish for `win-x64` instead.

**Comment by dsplaisted** [comment]
Yes, this is an expected result of the RID graph changes.
