### ISSUE TITLE
The directory structure of `sdk-manifests` is changed on .Net8 Preview 7 

### ISSUE THREAD

**Issue by wanmyj** [dotnet/sdk#34706]
### Describe the bug
|                    |                                                                                                     |
|--------------------|-----------------------------------------------------------------------------------------------------|
| Before Preview 7  | "C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.workload.emscripten.current\WorkloadManifest.json" |
| After Preview 7   | "C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\8.0.0-preview.7.23375.2\WorkloadManifest.json"  |

### To Reproduce
Install .Net8 Preview 7 SDK from **Windows x64** installer from the [official link](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

### Exceptions (if any)
```log
 xxxxxxx.aget.projects\project.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'.
```
Wrapped up
`
 xxxxxxx.aget.projects\project.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'.
`

**Comment by mjsb212** [comment]
Cant get any projects to open the properties editor window:
Microsoft.VisualStudio.ProjectSystem.Query.QueryExecutionException: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'.
File name: 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'

**Comment by baronfel** [comment]
@wanmyj / @mjsb212 - are you using the CLI here, or VS or some other IDE? We did make changes to the workload resolver to support workload installations being side-by-side, so that could be what's happening here.

**Comment by mjsb212** [comment]
Trying to open project properties in VS 2022 17.6.X

An error occurred while loading the project properties editor:
Microsoft.VisualStudio.ProjectSystem.Query.QueryExecutionException: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'.
File name: 'C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.7\microsoft.net.workload.emscripten.current\WorkloadManifest.json'

**Comment by baronfel** [comment]
@mjsb212 - can you try with 17.7? I'd expect it to work there.

**Comment by mjsb212** [comment]
Ok thanks, I will try updating to 17.7.X.  I figured it might be a VS version problem, but I didn't want to update because a few months ago the exact same thing happened in the VS Preview 17.7 I had installed side by side and I had to uninstall all my preview versions to get things working again - I will try again with a new 17.7 release version, hoping that its stable and fixes this.

**Comment by baronfel** [comment]
What's happening here is that preview7 included a change for Workload in .NET 8 that allows side-by-side installation of workloads. This required changes to the Workload Resolver, which have gone into VS 17.7 and onwards, but not 17.6. We may have some messaging somewhere saying that preview7+ is only compatible with VS 17.7+, but I don't have it quickly at hand.

**Comment by mjsb212** [comment]
Now I get this error after upgrading VS to 17.7.2 with a brand new solution using standard VS MAUI template. I also Installed .Net8 Preview 7 SDK from Windows x64 installer from the [official link](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net8.0-android	MauiApp1	C:\Users\Administrator\source\repos\deletenow\MauiApp1\MauiApp1\MauiApp1.csproj	1
