### ISSUE TITLE
DOTNET_GENERATE_ASPNET_CERTIFICATE environment variable ignored in dotnet CLI first-time use flow

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [dotnet/sdk#34779]
### Describe the bug
During first-time use of the `dotnet` CLI, the `DOTNET_GENERATE_ASPNET_CERTIFICATE` environment variable [is documented][var-docs] as disabling ASP.NET certificate generation when set to `0`, `false`, or `no`:

> ## `DOTNET_GENERATE_ASPNET_CERTIFICATE`
>
> Specifies whether to generate an ASP.NET Core certificate. The default value is `true`, but this can be overridden by setting this environment variable to either `0`, `false`, or `no`.

However, if the `DOTNET_GENERATE_ASPNET_CERTIFICATE` environment variable is set to `0`, the first-time use flow still creates and installs an ASP.NET development certificate.

  [var-docs]: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_generate_aspnet_certificate

### To Reproduce

1. Using an Apple Silicon computer where .NET has not previously been installed…
2. Download and unpack the .NET 7.0.400 binaries from https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.400-macos-arm64-binaries. Add the directory to your `PATH`.
3. In your shell, run:
    ```zsh
    export DOTNET_CLI_TELEMETRY_OPTOUT=1
    export DOTNET_GENERATE_ASPNET_CERTIFICATE=0
    export DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=0
    ```
4. Run `dotnet --help`.

The output I got included these lines:

```
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
```

<details>
<summary>Full output, for reference</summary>

```
% dotnet --help

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.400

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET application.

runtime-options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
  --additional-deps <path>         Path to additional deps.json file.
  --depsfile                       Path to <application>.deps.json file.
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --roll-forward <setting>         Roll forward to framework version  (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable).
  --runtimeconfig                  Path to <application>.runtimeconfig.json file.

path-to-application:
  The path to an application .dll file to execute.

Usage: dotnet [sdk-options] [command] [command-options] [arguments]

Execute a .NET SDK command.

sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET SDK version in use.

SDK commands:
  add               Add a package or reference to a .NET project.
  build             Build a .NET project.
  build-server      Interact with servers started by a build.
  clean             Clean build outputs of a .NET project.
  format            Apply style preferences to a project or solution.
  help              Show command line help.
  list              List project references of a .NET project.
  msbuild           Run Microsoft Build Engine (MSBuild) commands.
  new               Create a new .NET project or file.
  nuget             Provides additional NuGet commands.
  pack              Create a NuGet package.
  publish           Publish a .NET project for deployment.
  remove            Remove a package or reference from a .NET project.
  restore           Restore dependencies specified in a .NET project.
  run               Build and run a .NET project output.
  sdk               Manage .NET SDK installation.
  sln               Modify Visual Studio solution files.
  store             Store the specified assemblies in the runtime package store.
  test              Run unit tests using the test runner specified in a .NET project.
  tool              Install or manage tools that extend the .NET experience.
  vstest            Run Microsoft Test Engine (VSTest) commands.
  workload          Manage optional workloads.

Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  user-jwts         Manage JSON Web Tokens in development.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

Run 'dotnet [command] --help' for more information on a command.
```

</details>

Keychain Access also showed a new certificate had been installed.

I believe this can also be reproduced on a computer where the `dotnet` CLI has previously been used by deleting the `~/.dotnet` directory (which contains the first-use sentinel files) and (with the appropriate environment variables set) re-running `dotnet --help`. In this case, I do not see a new certificate installed in Keychain Access, but I do still see the "Installed an ASP.NET Core HTTPS development certificate." message in the output.

### Exceptions (if any)

N/A

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /Users/removed/.local/dotnet-sdk-7.0.400-osx-arm64/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/Users/removed/.local/dotnet-sdk-7.0.400-osx-arm64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/Users/removed/.local/dotnet-sdk-7.0.400-osx-arm64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/Users/removed/.local/dotnet-sdk-7.0.400-osx-arm64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Not using an IDE at this time

**Comment by KoltesDigital** [comment]
Same when `DOTNET_GENERATE_ASPNET_CERTIFICATE` is `false`.

**Comment by MiYanni** [comment]
@sometimes-i-send-pull-requests @KoltesDigital Can you try this on the latest [.NET 8 preview](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)? I recently [cleaned up this code](https://github.com/dotnet/sdk/pull/33935/files#diff-dfcad2bdee275dc4fd410996fb0f2faa889ad9a08c8c0ed830817e24aef06cccR83) and want to see if the problem still exists before I investigate further.

**Comment by sometimes-i-send-pull-requests** [comment]
> @sometimes-i-send-pull-requests @KoltesDigital Can you try this on the latest [.NET 8 preview](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)? I recently [cleaned up this code](https://github.com/dotnet/sdk/pull/33935/files#diff-dfcad2bdee275dc4fd410996fb0f2faa889ad9a08c8c0ed830817e24aef06cccR83) and want to see if the problem still exists before I investigate further.

The .NET 8 Preview does seem at first glance to obey the environment variable.

1. I downloaded the preview linked above -- `dotnet-sdk-8.0.100-preview.7.23376.3-osx-arm64.tar.gz`
2. I removed the quarantine bit and untarred it
3. I added it to the `PATH` and used `dotnet --version` to verify that the right one was being executed
4. I renamed `~/.dotnet` so it would not be found
5. I ran `dotnet --help`

The resulting output:

```
% dotnet --version
8.0.100-preview.7.23376.3
% dotnet --help

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.100-preview.7.23376.3

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET application.

(...)
```

So, it does seem like `DOTNET_GENERATE_ASPNET_CERTIFICATE` is adhered to and is no longer ignored on .NET 8 Preview.

**Comment by MiYanni** [comment]
Awesome! Let me know if you have any issues with it going forward. We can always reopen the issue. For now, I'll close it.
