### ISSUE TITLE
Pack when referencing Microsoft.CodeAnalysis.CSharp generates exclude="Build,Analyzers"

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/sdk#3489]
Repro steps:

1. New project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.1.0-dev</Version>
    <Authors>Author</Authors>
    <Description>Descriptor</Description>
    <NeutralLanguage>en</NeutralLanguage>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" />
  </ItemGroup>
</Project>
```

2. Build in VS
3. Check created package.

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>PackRepro</id>
    <version>0.1.0-dev</version>
    <authors>Author</authors>
    <owners>Author</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <description>Descriptor</description>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

I tried `<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" PrivateAssets="none"/>` but it did not have any effect.

Is there a way to pack this so that analyzers are not excluded?
Is there documentation about this?

**Comment by livarcocc** [comment]
@nkolev92

**Comment by nkolev92** [comment]
Hmm, I just tested your scenario and it worked for me. 

This is the nuspec generated (note I used the project template for dotnet new classlib)

```xml
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" include="All" />
      </group>
    </dependencies>
```

Also note that there's some issues with analyzers and transitive flow (the fact that you can't prevent them to flow). https://github.com/NuGet/Home/issues/6279

**Comment by JohanLarsson** [comment]
I'm using VS latest. Not sure about sdk version, ist that `dotnet --version`?.

> I used the project template for dotnet new classlib
Why not use the included sample?

> Also note that there's some issues with analyzers and transitive flow
This is for a helper library for writing analyzers.

**Comment by jnm2** [comment]
@nkolev92 Your nuspec has `.NETStandard2.0` and Johan's has `.NETStandard1.3`

**Comment by nkolev92** [comment]
The exact repro didn't matter in my case: 

Here's the generated nuspec. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>3489-repro</id>
    <version>0.1.0-dev</version>
    <authors>Author</authors>
    <owners>Author</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <description>Descriptor</description>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" include="All" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

I'll do some digging to see if I can figure out the scenario in which it ends up not working.

It'd be helpful if you can provide us the assets file right before you pack.

**Comment by JohanLarsson** [comment]
[Here is the full sln](https://github.com/GuOrg/Gu.Roslyn.Asserts/tree/3f940b6bfbe3febc30e40e1cf91d6dadd1fbdee7)

**Comment by JohanLarsson** [comment]
```
PM> dotnet --version
2.2.101
```

**Comment by jnm2** [comment]
Could there be a difference where `<GeneratePackageOnBuild>` and building from VS does something different than `dotnet pack`?

**Comment by JohanLarsson** [comment]
Is there a commandline way of `dotnet pack` and specifying langversion?

**Comment by nkolev92** [comment]
I downloaded the repro from @JohanLarsson and I added the reference to Gu.Roslyn.Asserts.Analyzers. 

You are using paket in that project. So when you run dotnet pack you are actually invoking their pack, so not sure what's happening there.

Am I missing something maybe?

**Comment by JohanLarsson** [comment]
Oh, is paket still around, maybe that explains it then. Converted to nuget a couple of commits ago but maybe I dumbed it.

**Comment by JohanLarsson** [comment]
But I still got what is in the original issue when creating a new project that should not have traces of paket.

**Comment by nkolev92** [comment]
I tried in VS and I didn't see any issues. 

Do you have restore enabled in Visual Studio?
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting#quick-solution-for-visual-studio-users

**Comment by JohanLarsson** [comment]
How does restore settings affect pack?

**Comment by jnm2** [comment]
I get the same result as Johan. Create a csproj with the contents he specified above (or extract this if it's easier: 
[repro.zip](https://github.com/dotnet/sdk/files/3448921/repro.zip)), double-click the csproj to open in VS 16.2.0, build the solution in VS, open `bin\Debug\repro.0.1.0-dev.nupkg` in 7-zip or equivalent, and see this in the nuspec:

```cs
        <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
```

```
Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
```

**Comment by jnm2** [comment]
`dotnet pack` also produces identical nuspec dependencies with this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" />
  </ItemGroup>

</Project>
```

**Comment by jnm2** [comment]
I used `dotnet new globaljson --sdk-version 2.1.801` and still get the same `exclude="Build,Analyzers"`

**Comment by nkolev92** [comment]
@jnm2 

If this is the project spec: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" />
  </ItemGroup>

</Project>
``` 
then the following nuspec: 

```xml
 <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" exclude="Build,
<dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
```
is expected. 

The PrivateAssets default value is build analyzers and contentfiles see: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

You need to put PrivateAssets="None" to make it pack as intended.

**Comment by jnm2** [comment]
Aha, that's where it's documented! I was trying to find something at https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets. This seems fine so long as it can be overridden.

**Comment by jnm2** [comment]
@JohanLarsson So if I follow the steps with `<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" PrivateAssets="none"/>`, I get the proper `<dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" include="All" />`.

Can you try again?

**Comment by JohanLarsson** [comment]
I still get
```xml
<dependency id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="2.3.1" exclude="Build,Analyzers" />
```

Using:
```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.3.1" PrivateAssets="None" />
```

Maybe I need to do close VS & `git clean -dxf`?
Testing in an empty project first.

**Comment by JohanLarsson** [comment]
Worked as expected when creating a new project.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.1.0-dev</Version>
    <Authors>Author</Authors>
    <Description>Descriptor</Description>
    <NeutralLanguage>en</NeutralLanguage>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.3.1" PrivateAssets="none" />
  </ItemGroup>
</Project>
```

Produced:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>PackRepro</id>
    <version>0.1.0-dev</version>
    <authors>Author</authors>
    <owners>Author</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <description>Descriptor</description>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CodeAnalysis.CSharp" version="2.3.1" include="All" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by JohanLarsson** [comment]
Worked for real project after close VS and git clean.

**Comment by JohanLarsson** [comment]
Confirmed it using empty project
- Adding or removing `PrivateAssets="none"` does not change the produced package.
-  `dotnet restore` does not change the produced package.
- Deleting `obj` makes change in ` PrivateAssets="none"` take effect.

**Comment by jnm2** [comment]
MSBuild pack target incremental build probably isn't taking the csproj file date into account? I'm pretty sure I've seen that myself.

**Comment by nkolev92** [comment]
The pack target depends on restore, but it wouldn't run restore if it's out of date.

**Comment by jnm2** [comment]
Could anything be done to improve the situation though, repeated csproj edits + pack?

**Comment by JohanLarsson** [comment]
Yes, it would be preferable if `pack` uses what is currently in the `csproj`. So easy to forget a git clean.

**Comment by nkolev92** [comment]
Pack burns in the restored versions of packages, not the requested ones. 
So it's by design right now. 

Pack also doesn't run build if it's out of date. I see restore as the same thing. 

Note that even if pack were to do an up to date restore check, it'd then need to run an up to date build check. 

I'm not saying it'll never ever change or something like that, I just don't see any immediate changes happening :)
