### ISSUE TITLE
Inclusion of runtime graph for all TFMs causes existing .NET Framework projects to turn x86

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3495]
So, it seems that giving the runtime graph to nuget for all TFMs is actually a pretty severe breaking change for .NET Framework in some cases.

Roslyn builds with preview 8 (maybe 7, not sure when the rid graph change landed) will switch the .NET Framework csc.exe, vbc.exe, VBCSCompiler.exe to x86 from Any CPU.

This happens because they have a ref to Microsoft.DiasymReader.Native which has runtimes/win-x86 assets. The design for .NET Framework is that when we find RID-specific assets AND there is no explicit AnyCPU and no explicit RID, then we take the win7-x86 assets and use PlatformTarget=x86. 

(I regret this design, but that is the design since 1.0 SDK. It was done so that .NET Framework ASP.NET Core projects could consume libuv without setting a RID or PlatformTarget. Project.json just picked the RID of the current machine, which was worse as you get different apps on different machines. We tried to make it an error and say you had to pick a PlatformTarget or RID on .NET Framework exes, but there was a ton of complaints about it and we landed on the design described above by compromise.)

The thing is that we use win7-x86, but without a RID graph, we/NuGet don't know that win-x86 assets are applicable to win7-x86. Now that we have the RID graph always, we discover these win-x86 assets for the first time and the (regrettable) design actually kicks in.

My suggestion to avoid a breaking change here is to not pass the RID graph by default for TFMs that are not .NET Core 3.0+ or .NET Standard 2.1+. We can put it behind an opt-in for other TFMs.

Separately, roslyn should explicitly set Any CPU defensively so that they are not sensitive to which SDK is used to build them.

cc @jaredpar @dsplaisted

**Comment by nguerrera** [comment]
Change in behavior came with https://github.com/dotnet/sdk/pull/3406

**Comment by dsplaisted** [comment]
@nguerrera @livarcocc Are we planning to fix this for 3.0?

**Comment by nguerrera** [comment]
I think we should if at all possible.

**Comment by livarcocc** [comment]
Do we have a fix in mind? If so, let's try to get this in.
