### ISSUE TITLE
ResolveAssemblyReference returns 3.0 assemblies when 5.0 is requested

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#3496]
I have a project where I try to use the latest 5.0 branded aspnet core. I use a `FrameworkReference` update to do so. The machine has the latest sdk (5.0.x) and the latest aspnet core shared runtimes 3.0.x and 5.0.x.

At compilation I get this:

```
Startup.cs(188,21): error CS1705: Assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson' with identity 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Mvc.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Mvc.Core' with identity 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [/tmp/BenchmarksServer/43sztvs0.trd/benchmarks/src/Benchmarks/Benchmarks.csproj]
Program.cs(117,21): error CS1705: Assembly 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv' with identity 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Hosting.Abstractions' with identity 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [/tmp/BenchmarksServer/43sztvs0.trd/benchmarks/src/Benchmarks/Benchmarks.csproj]
```

The .binlog shows that `ResolveAssemblyReference` is returning these conflicting assemblies where it should instead pick them from the 5.0.x folder.

[msbuild.binlog.zip](https://github.com/dotnet/sdk/files/3454241/msbuild.binlog.zip)

Rename the file by removing the .zip extension, don't extract it (GH limitation)

**Comment by livarcocc** [comment]
Support for 5.0 is really limited right now. We are still trying to wrap up 3.0.

Having said that, @dsplaisted can you help @sebastienros in manually targeting his project to 5.0?

**Comment by nguerrera** [comment]
Look at what I did here: https://github.com/aspnet/EntityFramework6/pull/1109

Also, I've started fixing the lowest hanging fruits to getting proper 5.0 support here: https://github.com/dotnet/core-sdk/pull/3741

As Livar said, this isn't high priority right now as 3.0 is still wrapping up. I've done both of these things after hours. I'm going to close this. The project attached is not expected to work, and you and look at EF for workarounds that would actually work or wait a bit longer for a 5.0 SDK.

**Comment by nguerrera** [comment]
> Rename the file by removing the .zip extension, don't extract it (GH limitation)

Ugh, this seems new. I've had binlogs attached fine without shenanigans like this in the past. I missed these instructions at first.

**Comment by sebastienros** [comment]
@nguerrera 

![image](https://user-images.githubusercontent.com/1165805/62484604-65484a00-b76f-11e9-9de9-16033a0e8eff.png)

I will try to blindly use a `netcoreapp5.0` and see if that helps. I already have `<NETCoreAppMaximumVersion>99.9</NETCoreAppMaximumVersion>` in my project to prevent the sdk from validating it. It might solve my issue. And I will take a look at your example too.
