### ISSUE TITLE
ContainerHttpException contains request instead of response

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#34979]
I'm hitting this exception:

https://github.com/dotnet/sdk/blob/0a6f8335c92725de0e65df952f6940d3f7fadaf1/src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs#L42-L45

The exception was meant to include the response from the server as its last argument, but currently the request json is being passed.

Side-note about the request: the JSON has its plus signs escaped. The server should still accept this as it is valid JSON.
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2\u002Bjson",
"config": {
"mediaType": "application/vnd.docker.container.image.v1\u002Bjson",
...
```

cc @baronfel

**Comment by baronfel** [comment]
Definitely a bug, would accept a PR that fixes this if I can't get around to sending one myself.

The escaped JSON I'd seen before, but it doesn't seem to have any impact on the registries I've been testing against. If it does end up being a problem we'd need to scour our uses of the STJ json serializer and use a consistent set of options that forbid this encoding.

**Comment by tmds** [comment]
Fixed by https://github.com/dotnet/sdk/pull/35040.
