### ISSUE TITLE
Redundant PackageName and NuGetPackageId metadata

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#3499]
There's a mix of checking PackageName and NuGetPackageId in the targets and now we seem to be setting both all the time in ResolvePackageAssets.

I actually trimmed down the metadata in 2.1 to stop doing this, but it crept back in c7549ffe

**Comment by dsplaisted** [comment]
We should also try to settle on one or the other of `NuGetPackageVersion` or `PackageVersion`: https://github.com/dotnet/sdk/pull/3850#discussion_r348723727

**Comment by nguerrera** [comment]
I think we should settle on the matching one with ID
