### ISSUE TITLE
ASP.NET Core 3.1 get slow build on SDK 7.0.400

### ISSUE THREAD

**Issue by supershowwei** [dotnet/sdk#35200]
### Describe the bug
I am using Visual Studio 2017 version 17.7.3 with SDK version 7.0.400. When building an ASP.NET Core 3.1 MVC project, it takes more than 40 seconds, even if I create a completely new ASP.NET Core 3.1 MVC project.

In the detailed output messages, I receive an error: 'Server execution failed with response Rejected. For more info, check the server log file in the location specified by the RAZORBUILDSERVER_LOG environment variable. Fallback to in-process execution.'

### To Reproduce
Using Visual Studio 2017 version 17.7.3 with SDK version 7.0.400, create a new ASP.NET Core 3.1 MVC project and perform a rebuild.

I've attached my GitHub repository at https://github.com/supershowwei/there-are-some-issues-building-aspnetcore-3_1-on-sdk-7_0_400.

### Exceptions (if any)
In the detailed output messages, I receive an error: 'Server execution failed with response Rejected. For more info, check the server log file in the location specified by the RAZORBUILDSERVER_LOG environment variable. Fallback to in-process execution.'

### Further technical details
- Outpub of `dotnet --info`:

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

執行階段環境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.316 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

Visual Studio 17.7.3

**Comment by marcpopMSFT** [comment]
@Forgind is this the same as your issue: https://github.com/dotnet/sdk/pull/35409

**Comment by Forgind** [comment]
Very likely.

@supershowwei, can you try setting the `RAZORBUILDSERVER_LOG` variable and copying the logs here to confirm?

**Comment by Plasma** [comment]
@Forgind I can reproduce this issue today (suddenly started occurring for me), setting that variable shows me a timeout for 20s (VS 17.7.4):

```
--- PID=15272 TID=13 Ticks=-1995853390: Attempting to create process 'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe'
--- PID=15272 TID=13 Ticks=-1995853390: Successfully created process with process id 46988
--- PID=15272 TID=13 Ticks=-1995853390: Attempt to open named pipe 'XXX.JxQlbNvh5RouON68iwZxUK6u5'
--- PID=15272 TID=13 Ticks=-1995853390: Attempt to connect named pipe 'XXX.JxQlbNvh5RouON68iwZxUK6u5'
--- PID=15272 TID=31 Ticks=-1995833390: Connecting to server timed out after 20000 ms
...
```

If I explicitly set `DOTNET_HOST_PATH` env to `C:\Program Files\dotnet\dotnet.exe` the timeout/delay disappears:

```
--- PID=52412 TID=30 Ticks=-1995476156: Attempting to create process 'C:\Program Files\dotnet\dotnet.exe'
--- PID=52412 TID=30 Ticks=-1995476156: Successfully created process with process id 18468
--- PID=52412 TID=30 Ticks=-1995476140: Attempt to open named pipe 'XXX.JxQlbNvh5RouON68iwZxUK6u5'
--- PID=52412 TID=30 Ticks=-1995476140: Attempt to connect named pipe 'XXX.JxQlbNvh5RouON68iwZxUK6u5'
--- PID=52412 TID=11 Ticks=-1995476046: Named pipe 'XXX.JxQlbNvh5RouON68iwZxUK6u5' connected
--- PID=52412 TID=43 Ticks=-1995476046: Creating ServerRequest
....
```

**Comment by Forgind** [comment]
@Plasma,

Thanks for confirming that! Other than your workaround, my fix for this issue should already be merged, though I don't remember off-hand when it's expected to be released. Know that a fix is coming soon!
