### ISSUE TITLE
`dotnet --info` includes two RID values with .NET 8

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#35237]
Previous versions of .NET list RID under _Runtime Environment_, and .NET 8 includes it also under _Host_.

```
.NET SDK:
 Version:   8.0.100-preview.7.23376.1
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/8.0.100-preview.7.23376.1/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          fedora.37-x64

.NET SDKs installed:
  7.0.110 [/usr/lib64/dotnet/sdk]
  8.0.100-preview.7.23376.1 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Afaik, these RID values will be the same, so it can be confusing to list them twice.

This change can break scripts that try to extract the rid using `dotnet --info | grep RID` because they now get two lines instead of one.

cc @richlander @elinor-fung

**Comment by tmds** [comment]
> I understand that people might have scripts using it, but I can't see us making the format "rigid"

The `--json` option proposed in https://github.com/dotnet/sdk/issues/33697 would solve this.

Without another way to get this information, people do try to get it from `dotnet --info`: https://grep.app/search?q=dotnet%20--info%20%7C%20grep%20.

When do the two rids that get output now differ in value?

**Comment by elinor-fung** [comment]
This is from having `dotnet --info` coming from both the sdk and the host. As mentioned, https://github.com/dotnet/sdk/issues/33697 where the sdk can provide all the info would provide the machine-readable format (when an sdk is installed). But meanwhile, we could probably make the output cleaner by having the host skip printing information it 'knows' the sdk output has when there is an sdk.

**Comment by tmds** [comment]
> we could probably make the output cleaner by having the host skip printing information it 'knows' the sdk output has when there is an sdk.

Yes, please do.

Printing the same value may be confusing, and it will break scripts that try to parse the value.

**Comment by ptr727** [comment]
I used `dotnet --info` to get the RID so that I can download [single file tools](https://github.com/dotnet/diagnostics/blob/main/documentation/single-file-tools.md), in .NET 9 this no longer works as the RID returned includes the OS, e.g. I get `RID: ubuntu.24.10-x64` and I expect `linux-x64`.

I see the JSON option does not yet exist, what other options do I have to get the "normalized" RID?
