### ISSUE TITLE
dotnet templating: Condition on csproj ItemGroup item removes entire line from output 

### ISSUE THREAD

**Issue by krjone01** [dotnet/sdk#35312]
### Describe the bug

When using a condition on a msbuild ItemGroup item in a template csproj file, the entire line is removed from the output csproj file.

This is a "Microsoft.NET.Sdk.Web" project file.

The fragment from the template csproj file

```
  <!-- main app -->
  <ItemGroup>
    <NgAppInput Include="$(SpaRoot)\src\**" />
    <NgAppOutput Include="$(SpaRoot)\dist\main\**" Exclude="$(SpaRoot)\dist\main\favicon.ico" />
         <!-- Item group can't be empty, but the file does not have to exist. Use fake file for no output files -->
         <!--
      For some unknown reason, the line below is being removed from the template output
      You may have to copy and paste it back into the project file.
      <NgAppOutput Include="$(SpaRoot)\fake.file" Condition="@(NgAppOuput->Count()) == 0" />
     -->
    <NgAppOutput Include="$(SpaRoot)\fake.file" Condition="@(NgAppOuput->Count()) == 0" />
  </ItemGroup>
```

This is the fragment from the csproj file after dot net new
```
 <!-- main app -->
  <ItemGroup>
    <NgAppInput Include="$(SpaRoot)\src\**" />
    <NgAppOutput Include="$(SpaRoot)\dist\main\**" Exclude="$(SpaRoot)\dist\main\favicon.ico" />
         <!-- Item group can't be empty, but the file does not have to exist. Use fake file for no output files -->
         <!--
      For some unknown reason the line below is being removed from the template output
      You may have to copy and paste it back into the project file.
     -->
  </ItemGroup>
```
Note that not only is the line removed from the project file, but it's also removed from the XML comment so it seems like some sort of parsing issue.

I have messed around with the condition and the only reliable way to get the line to come out is to remove any kind of comparison from the condition. Of course, this is not valid as the result of the expression is no longer a boolean.

```
  <!-- main app -->
  <ItemGroup>
    <NgAppInput Include="$(SpaRoot)\src\**" />
    <NgAppOutput Include="$(SpaRoot)\dist\main\**" Exclude="$(SpaRoot)\dist\main\favicon.ico" />
                  <!-- Item group can't be empty, but the file does not have to exist. Use fake file for no output files -->
                  <!--
      For some unknown reason, the line below is being removed from the template output
      You may have to copy and paste it back into the project file.
      <NgAppOutput Include="$(SpaRoot)\fake.file" Condition="@(NgAppOuput->Count())" />
     -->
    <NgAppOutput Include="$(SpaRoot)\fake.file" Condition="@(NgAppOuput->Count())" />
  </ItemGroup>
```
### To Reproduce

[Gist link]https://gist.github.com/krjone01/b4f898504ee87c301e5982f4b09bf1e5

Create the dir structure to house the template. Using d:\temp here as root, but it can be anything.
> cd d:\temp
D:\temp> mkdir template
d:\temp> cd template
d:\temp\template> mkdir .template.config
 
Copy the files from the gist
ModuleTemplate.Ng.csproj -> d:\temp\template\
template.json -> d:\temp\template\.template.config\

 Go back up to the root
d:\temp\template>cd \temp

Load the template
d:\temp> dotnet new install d:\temp\template\ --force

Run the template
d:\temp> dotnet new esmodule --verbosity diag -n TestProj99 --moduleNameKebab test-module

This should create a TestProj99 directory below the current dir, with the output TestProj99.Ng.csprog file.

Open the TestProj99.Ng.csproj file and note the missing lines around 43, 72 and 74

### Further technical details
- Include the output of `dotnet --info`

  NET SDK:
Version:   7.0.400
Commit:    73bf45718d

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 3.1.32 [C:\Program Files\dotnet\shared\[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 5.0.17 [C:\Program Files\dotnet\shared\[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 6.0.21 [C:\Program Files\dotnet\shared\[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 3.1.32 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]
  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 5.0.17 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]

  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 6.0.15 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]

  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 6.0.21 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]

  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.NETCore.App](http://microsoft.netcore.app/)]

  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 3.1.32 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 5.0.17 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 6.0.15 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 6.0.21 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

  [Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/) 7.0.10 [C:\Program Files\dotnet\shared\[Microsoft.WindowsDesktop.App](http://microsoft.windowsdesktop.app/)]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
   VS 2022 Pro 17.7

**Comment by marcpopMSFT** [comment]
This is likely because the condition is actually being evaluated and found not to be true so excluded as the template engine recognizes msbuild code. I would try replacing the double quotes around the Condition with a `&quot;` as that should be the escaped form of double quotes and hopefully make it so it doesn't evaluate that msbuild string.

**Comment by marcpopMSFT** [comment]
We found the official template engine documentation so take a look here as well: https://github.com/dotnet/templating/blob/main/docs/Conditional-processing-and-comment-syntax.md#ignore-conditions-expressions-in-msbuild-files
