### ISSUE TITLE
Specifying a framework for multi-targeted dependencies that include a .NET Framework target does not work.

### ISSUE THREAD

**Issue by orehmane** [dotnet/sdk#35341]
### Describe the bug
We have some projects that reference projects that are multi-targeted, including both 472 and 6.0. We're attempting to build them on Ubuntu, and so are specifying `--framework net6.0` on the command line.

However, unless the reference is removed entirely, the dependency fails to build, with an error message saying that a 472 project is not compatible with 6.0.

### To Reproduce

Build a project that has multitargeted dependencies, included as `ProjectReference`s, on Ubuntu, specifying net6.0 as the target framework.

### Further technical details
- Include the output of `dotnet --info`
```.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.413/

global.json file:
  snip

Host:
  Version:      6.0.21
  Architecture: x64
  Commit:       e40b3abf1b

.NET SDKs installed:
  6.0.413 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  [Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/) 6.0.21 [/usr/share/dotnet/shared/[Microsoft.AspNetCore.App](http://microsoft.aspnetcore.app/)]
  [Microsoft.NETCore.App](http://microsoft.netcore.app/) 6.0.21 [/usr/share/dotnet/shared/[Microsoft.NETCore.App](http://microsoft.netcore.app/)]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info```

**Comment by marcpopMSFT** [comment]
@orehmane are you building a solution that has all the projects or building the project that references the other project?

**Comment by orehmane** [comment]
It has been a while, and we went through several iterations, but I believe it was when building the project.

**Comment by marcpopMSFT** [comment]
@orehmane were you able to find a workaround then? If you still have the project and can provide an https://aka.ms/binlog we can investigate further but without a repro project or the binlog, we'd be guessing at how to reproduce your exact issue. Let me know

**Comment by orehmane** [comment]
We were able to eliminate all 472 references, so there was no need to specify a framework, if that counts as a workaround.

**Comment by marcpopMSFT** [comment]
Sounds like you were able to get unblocked even if not an ideal solution. If this comes up again, please feel free to provide a binlog and we can dig into this further.
