### ISSUE TITLE
Unsafe.AsRef<ReadOnlyStruct>(in ReadOnlyStructInstance) missing in .NET 8 RC1, No documentation regarding the breaking change

### ISSUE THREAD

**Issue by Aniobodo** [dotnet/sdk#35427]
### Describe the bug
In .NET 7, there is the method _ref T AsRef<T>(in T source);_ in the Unsafe class. I use this method basically for large readonly structs.
Now in .NET 8 RC1, that method is missing and instead there is _ref T AsRef<T>(scoped ref readonly T source);_
This new method in .NET 8 is empty and throws _PlatformNotSupportedException_  exception.

In VS, the compiler displays Error CS1620 when the new method in .NET is used like this: 
Unsafe.AsRef<ReadOnlyStruct>(ref ReadOnlyStructInstance)

I did not find any information regarding this change, so:
1. Is this an intentional change? If yes what are the reasons?
2. What is the replacement for the missing method?

### Further technical details
VS 2022 Version 17.7.4

**Comment by Aniobodo** [comment]
@KalleOlaviNiemitalo thanks for the citations. 
Now with VS 2022 17.8.0 Preview: I did not get an exception at runtime. Also, the compiler Error CS1620 does not show up.
So I hope that the final release of .NET 8/VS 2022 17.8.0 will be okay.

**Comment by baronfel** [comment]
Going to close this as it's fixed when using a supported VS version for the SDK in use.
