### ISSUE TITLE
SDK shouldn't upload manifest separately when uploading tags.

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#35431]
I'm investigating an issue where the SDK tooling fails to upload an image to the internal OpenShift container image registry.

The internal image registry is integrated with OpenShift and for images pushed to it, matching Kubernetes resources are created.

The push fails when the image is trying to upload the manifest under its digest here:

https://github.com/dotnet/sdk/blob/f8a9e2866134d9d04805da55fcb3984c8b94e008/src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs#L428

That digest has no known tag, and the OpenShift registry doesn't like it.

CLI tools (like `podman`) work well with the registry.
They are behaving slightly different from the SDK.
This is the log from `podman` when pushing an image to quay.io:
```
Writing manifest to image destination
time="2023-09-15T10:07:48+02:00" level=debug msg="PUT https://quay.io/v2/tmds/my-image/manifests/my-tag"
time="2023-09-15T10:07:49+02:00" level=debug msg="Called push.PersistentPostRunE(podman push --log-level trace quay.io/tmds/my-image:my-tag)"
time="2023-09-15T10:07:49+02:00" level=debug msg="Shutting down engines"
```

As seen in the log, `podman` doesn't upload the manifest under its digest, and it only uploads it as the tag.

Uploading the manifest digests is only needed when tags refer to a manifest list.
The manifest list for the tags can then refer to the image manifests using that digest.

To fix the issue with the OpenShift, we can make the SDK behave like the CLI tools and only upload the manifest separately when needed for a manifest list upload.

cc @baronfel

**Comment by baronfel** [comment]
Closing as we did this in #35437 - should be part of RC2.

**Comment by tmds** [comment]
I imagine these get auto closed when those changes are merged to the main branch? Or doesn't that auto close happen?
