### ISSUE TITLE
NETDSK1005 Error when building solution with two projects

### ISSUE THREAD

**Issue by mhsimkin** [dotnet/sdk#3545]
I'm receiving the infamous:

>  NETSDK1005: Assets file '...\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. 

when I try to build a solution that contains two projects.  One project is targeting .Net 472 and the other .Net Standard 2.  Both projects use the same physical folder since they are building the same code. 

`Aside: As much as I would like to multi-target in one file, I needed two nupkgs because of the order of precedence of when matching which to my target.`

I get the same issue whether I use MSBuild, or dotnet from the command line or Visual Studio 2019.  Deleting the projects.assets.json file doesn't resolve the issue.

I was able to work around the build issue by doing either of the following:

1. having MSBuild restore and build each project individually.
2. giving each project it's own project folder and then adding all the code as a link in one project. (not feasible- 200+ files/folders involved).

I have attached a msbuild.log with diagnostics, Solution and Project Files.

[renapi.zip](https://github.com/dotnet/sdk/files/3510159/renapi.zip)

[msbuild-build.log](https://github.com/dotnet/sdk/files/3510153/msbuild-build.log)
.

I would like to get this resolved so that I don't need to use a 4 step process on the build server.

**Build Environment:**
Windows 10 Pro Build 1809
Visual Studio 2019 Enterprise 16.2.2
.NET Framework 4.7.2 and 4.8 

**Also Installed, but not used for this build**
Visual Studio 2019 Enterprise Preview 16.3.0 Preview 2
.NET Core 2.2.401 and 3.0.100-preview8-013656

Thanks

-marc

**Comment by livarcocc** [comment]
Can you confirm that the project.assets.json is being generated in a folder specific to your project instead of the common one?

This is not a really common scenario and short of a workaround, this will not be at the top of our priority list. Sorry.

**Comment by mhsimkin** [comment]
@livarcocc both projects are compiling into the same $(ProjectDir)\obj folder. They are not unique to each.

Understood about priority.  I have already figured out a work around by calling MSBuild 4 times.

Do you know anything about the Visual Studio Shared Project template?  Would that resolve the issue?

**Comment by livarcocc** [comment]
It is possible the problem is because you are restoring/compiling to the same folder. Maybe I don't understand your scenario enough, but I would recommend not doing that.

About the shared project, sorry, I am not super familiar with it.

**Comment by mhsimkin** [comment]
@livarcocc, yes I suspect that is the issue.

It looks like the Shared Project template will resolve my issue.

For those that come later. Read the "[Shared Projects code sharing](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/shared-projects?tabs=windows)" document under the Xamarin Cross Platform section.

Instead of using Android and iOS projects, you can use .NET Standard and .NET  Full Framework Library projects.

-marc
