### ISSUE TITLE
$(IntermediateOutputPath) and $(TargetName) evaluates blank while setting up a PropertyGroup in CSproj SDK-format

### ISSUE THREAD

**Issue by largwid** [dotnet/sdk#3551]
**Visual Studio Version**: v15.9.15

**Summary**:
Trying to migrate csproj's to the New SKD project-format, in a complex .NET solution with multiple target files called during the build. The targets calling $(IntermediateOutputPath) and $(TargetName) works, but after migration the macro returns empty

**Steps to Reproduce**:

1. In Csproj file add a PropertyGroup with the following:

```
 <PropertyGroup>
    <ProjectIntermediateOutput>$(IntermediateOutputPath)</ProjectIntermediateOutput>
 </PropertyGroup>

<Target Name="MyProp" AfterTarget="CoreCompile">
   <Message Text="Project intermediate path : $(ProjectIntermediateOutput)" />
<Target

```
The run msbuild on project(solution). 
 

In the build output I expected to see a line:
`
Project intermediate path : obj\debug\net472
`
but gets:
`
Project intermediate path :
`

If I create new projects via the "New Project" wizard I get the same behavior in both Old-style projects and .NET SDK projects.

Looking forward to your inputs.

**Comment by davkean** [comment]
I've moved this to the SDK repo.

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by dsplaisted** [comment]
The `IntermediateOutputPath` property is set in .targets files which are evaluated after the body of the project file.  So this property is not set when the body of the project file is evaluated.  If you were to move the `PropertyGroup` inside the `MyProp` target, then you would get the value of the property (as targets run after evaluation).

The difference with non sdk-style projects is that the targets are explicitly imported in the project file:

```
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
```

In a non sdk-style project, if the `PropertyGroup` were before this import, then I would not expect the `IntermediateOutputPath` property to be set.  If the `PropertyGroup` is after the targets import, then the property should be set.

**Comment by largwid** [comment]
@dsplaisted

Thank you for the response, but the `MyProp` target ? 

Sorry for my ignorance.

I can't find any documentation around that. And if I just add a target with that name I can't see that it is running. 

Could you please elaborate a little further?

**Comment by dsplaisted** [comment]
In your steps to reproduce you have a `MyProp` target:

```xml
<Target Name="MyProp" AfterTarget="CoreCompile">
   <Message Text="Project intermediate path : $(ProjectIntermediateOutput)" />
<Target
```

That's what I was referring to.  But it's not specific to that Target, the property will be set inside any Target that runs.

**Comment by largwid** [comment]
@dsplaisted  Thanks

**Comment by rcdailey** [comment]
I'm still not seeing a reasonable workaround for this. I have the following `.targets` file contents, which is intended to allow me to introduce a common target to all my `csproj` files:

```xml
<Project>

  <PropertyGroup>
    <TlbExpPath>c:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\tlbexp</TlbExpPath>
    <TlbOutPath>$(OutDir)..\TLB\$(TargetName).tlb</TlbOutPath>
  </PropertyGroup>

  <Target Name="TlbExp" AfterTargets="CopyFilesToOutputDirectory" Inputs="$(TargetPath)" Outputs="$(TlbOutPath)">
    <Exec Command='"$(TlbExpPath)" "$(TargetPath)" /nologo /win64 /out:"$(TlbOutPath)" /verbose' />
  </Target>

</Project>
```

I can't move the `PropertyGroup` into the `Target` because the attributes of that target require them. This is a catch 22 situation. I could abuse `ItemGroup` for this, but I'd like to see what the developers recommend.

Thanks in advance @dsplaisted

**Comment by dsplaisted** [comment]
@rcdailey Try creating a separate target to compute the properties, and depending on that target in your other target:

```xml
<Target Name="CalculateTlbPaths">
  <PropertyGroup>
    <TlbExpPath>c:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\tlbexp</TlbExpPath>
    <TlbOutPath>$(OutDir)..\TLB\$(TargetName).tlb</TlbOutPath>
  </PropertyGroup>
</Target>

<Target Name="TlbExp" AfterTargets="CopyFilesToOutputDirectory"
                      DependsOnTargets="CalculateTlbPaths"
                      Inputs="$(TargetPath)" Outputs="$(TlbOutPath)">
  <Exec Command='"$(TlbExpPath)" "$(TargetPath)" /nologo /win64 /out:"$(TlbOutPath)" /verbose' />
</Target>
```

**Comment by rcdailey** [comment]
Thanks that definitely worked. Does this introduce significant overhead into the build process? Having a boilerplate target that really doesn't do anything?

**Comment by dsplaisted** [comment]
No, it should not introduce significant overhead.  There are many built-in targets that run as part of the build.  Check out http://msbuildlog.com/ if you want to browse through the targets in a build.

**Comment by abatishchev** [comment]
@dsplaisted can you help me understand more how this (doesn't) works?

How come this::

```xml
  <PropertyGroup>
    <output-dir>$(IntermediateOutputPath)</output-dir>
  </PropertyGroup>

  <Target Name="Trace" AfterTargets="Build">
    <Message Importance="High" Text="IntermediateOutputPath=$(IntermediateOutputPath)" />
    <Message Importance="High" Text="output-dir=$(output-dir)" />
  </Target>
```

Outputs this:

```
1>IntermediateOutputPath=obj\Debug\net6.0\
1>output-dir=
```

But this:

```xml
  <PropertyGroup>
     <output-dir>obj\$(Configuration)\$(TargetFramework)\</output-dir>
  </PropertyGroup>

  <Target Name="Trace" AfterTargets="Build">
    <Message Importance="High" Text="IntermediateOutputPath=$(IntermediateOutputPath)" />
    <Message Importance="High" Text="output-dir=$(output-dir)" />
  </Target>
```

Works just fine:

```
1>IntermediateOutputPath=obj\Debug\net6.0\
1>output-dir=obj\Debug\net6.0\
```

**Comment by abatishchev** [comment]
hi @dsplaisted thanks for the details. given

```
<PropertyGroup>
    <output-dir>$(IntermediateOutputPath)</output-dir>
  </PropertyGroup>

  <Target Name="Trace" AfterTargets="Build">
    <Message Importance="High" Text="IntermediateOutputPath=$(IntermediateOutputPath)" />
    <Message Importance="High" Text="output-dir=$(output-dir)" />
  </Target>
```

and that the first message works fine.

Do I understand correctly that `$(IntermediateOutputPath)` itself is somehow available but _projections_, i.e. other properties that use it aren't?

And another question: can you confirm this behavior has changed recently? Because it's what has changed for me (I guess) when it stopped working (and it was working just fine as early as last week; then I've updated to ASP.NET Core 7 on .NET 6).

**Comment by dsplaisted** [comment]
The reason is that anything inside a `<Target>` runs after evaluation.  So Targets generally get to see the "final" evaluated value of a property, though targets can also change property values and the order targets run in depends on the dependencies between them.

None of this has changed recently.  If you recently updated to sdk-style projects you might see some apparent changes because of where the common targets are imported, as mentioned earlier in this issue.
