### ISSUE TITLE
`dotnet watch` silently fails when `launchSettings.json` contains comments

### ISSUE THREAD

**Issue by peabnuts123** [dotnet/sdk#35558]
### Describe the bug
When running an application that uses `launchSettings.json`, `dotnet watch run` cannot use a launch profile if the file `launchSettings.json` contains any kind of comment. This is inconsistent with `dotnet run` which does support this (Added in [PR #11860](https://github.com/dotnet/cli/pull/11860)). Furthermore, no errors or warnings are logged to indicate that the file `launchSettings.json` is "invalid" in the eyes of `dotnet watch`. 

This has been reported by at least one other user as reported in [this](https://github.com/dotnet/sdk/issues/10368#issuecomment-1643247985) old (closed) issue.

### To Reproduce

I have created a simple reproduction project here: https://github.com/peabnuts123/dotnet-watch-launch-profiles

You can easily reproduce this in any project, however, by simply adding a comment to `launchSettings.json` and then running `dotnet watch run`. Even if you specify `dotnet watch run --launch-profile <profile_name>`, the profile specified will not be used. 

### Exceptions (if any)

No exceptions or errors of any kind, which would have improved the UX of this issue.

### Further technical details
<details>
<summary>output of `dotnet --info`</summary>

```
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.201/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  2.1.818 [/usr/local/share/dotnet/sdk]
  3.1.408 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.408 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.410 [/usr/local/share/dotnet/sdk]
  6.0.411 [/usr/local/share/dotnet/sdk]
  6.0.412 [/usr/local/share/dotnet/sdk]
  6.0.413 [/usr/local/share/dotnet/sdk]
  6.0.414 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

</details>

- Reproducible from any CLI, including integrated terminal within Vscode (Version: 1.82.2)

**Comment by baronfel** [comment]
We should update watch's json (de)serialization code to support comments - this is a built in capability of System.Text.Json. Really, run and watch should be using the same launch settings parsing logic, but for historical reasons they are separate.

**Comment by Vrajs16** [comment]
Spent so many hours on this :(

**Comment by baronfel** [comment]
@Vrajs16 what version of the SDK are you using that still exhibits the problem?

**Comment by peabnuts123** [comment]
@martincostello What release did that fix go out in? I'd be happy to close this with a "Upgrade to .NET XX" disclaimer if it has been fixed.

**Comment by martincostello** [comment]
It should be in the latest preview release of .NET 9.

**Comment by baronfel** [comment]
Probably an early .NET 9 preview - 8 months ago our main branch would have already been targeting 9. Any fixes for 8 would have needed cherry-picking back to the release/8.0.xxx branches.

**Comment by peabnuts123** [comment]
Will this fix be backported once 9 is stable? Not sure how .NET project runs.

**Comment by baronfel** [comment]
We don't as a policy backport every bugfix to the existing stable versions - especially for tooling layer bugs (like the SDK) where users can use newer SDKs while targeting older TFMs. 

If a bug is requested by enough users or otherwise impactful then we'd be more likely to backport, but even then we would probably only backport to the 8.x SDK.

**Comment by peabnuts123** [comment]
True, fair shout about using the newest SDK CLI to resolve the issue even for older projects. I'm going to close issue as the issue is fixed (albeit not yet released to stable). Others: feel free to raise a new issue to backport to older versions, or request this issue be re-opened.
