### ISSUE TITLE
Use `packages.lock.json` instead of `project.assets.json`, if available

### ISSUE THREAD

**Issue by gtbuchanan** [dotnet/sdk#35556]
### Is your feature request related to a problem? Please describe.
NuGet restore is required to generate `project.assets.json` even when a project-level lock file (e.g. `packages.lock.json`) already exists. When using the Cache task in Azure Pipelines, the [recommendation](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops#restore-cache) is to add a condition to your NuGet restore task to prevent it from running. However, I've found this doesn't actually work in practice because the build process always expects `project.assets.json` to exist (the aforementioned link even mentions this like it _might_ not happen).

Running a NuGet restore adds at least 30 seconds to our build time even when disabling all remote NuGet sources. I would expect the lock file to contain all the necessary information to build.

### Describe the solution you'd like
The build process should detect and use `packages.lock.json`, if available, in place of `project.assets.json` instead of triggering [NETSDK1004](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1004).

### Additional context

See also: https://github.com/NuGet/Home/issues/11770, https://github.com/NuGet/Home/issues/12409#issuecomment-1726528809

**Comment by marcpopMSFT** [comment]
@nkolev92 and @zivkan is this a nuget suggestion or sdk suggestion?  Not sure there is a lot of investment around lock files these days. CC @baronfel

**Comment by nkolev92** [comment]
It's a NuGet suggestion. 

The lock file does not contain enough information to setup the build.

* It does not have the compatibility checks. The asset selection is not part of it, so you don't know which assemblies from the package to pass to the compiler. 
* It does not contain anything related to props/targets files from packages. When packages carry props/targets, the author's expectation is that these packages get imported at build time.
* It doesn't contain information about the global packages folder. Restore ensures that all packages are in the global packages folder, so the build can complete. 

I don't see us adding these to the lock file at this point. The lock file is pretty large as is, and readability is a key aspect of it.

**Comment by zivkan** [comment]
> It's a NuGet suggestion.

To be pedantic, if this suggestion was feasible, it'd probably require a code change in the SDK repo, not NuGet.  However, as discussed the lock file doesn't contain all the information that the `ResolvePackageAssets` task needs, so it's not feasible, and NuGet really does need to run a restore. There's more stuff going on behind the scenes than what most customers expect.

It could be interesting to capture a PerfView trace to see what's taking "so long", and therefore get ideas for what perf improvements might be possible.

**Comment by marcpopMSFT** [comment]
Leaving it in the SDK for now but assigning to nkolev92 and zivkan if they want to engage. Moved it to the discussion milestone. I can't mark it for nuget as we have a bot that will close the issue and route people to the nuget repo.

**Comment by zivkan** [comment]
I'm closing this issue, as previous comments explain information that the SDK needs from the assets file that is missing from the lock file. Unfortunately, it's just not feasible to avoid restore to generate the additional intermediate files.

> The 30+ seconds (39s at the moment) I mentioned are not a huge deal in the scheme of things. However, I noticed much of the time is spent upfront:

`_GetAllRestoreProjectPathItems` is Nuget's MSBuild code to get information about all projects in the solution, before running the restore task, that actually downloads packages, creates intermediate files, etc. A while ago MSBuild created different APIs, in attempt to make it more efficient, called static graph. Nuget has an opt-in mode to use these APIs, rather than getting project information via MSBuild script. You could try it out to see if it reduces the overall time: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-with-msbuild-static-graph-evaluation

**Comment by gtbuchanan** [comment]
Thanks for the reference. Static graph evaluation did not improve our restore times, but our restore times are not that bad to begin with.
