### ISSUE TITLE
.NET Core SDK 2.2.108 does not work with Visual Studio 2017 version 15.9.13

### ISSUE THREAD

**Issue by kapilepatel** [dotnet/sdk#3563]
.NET Core SDK 2.2.108 does not work with Visual Studio 2017 version 15.9.13

Solved the issue by uninstalling all .NET Core versions and fresh install of .NET Core SDK Version 2.2.107
Find all versions here
https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by livarcocc** [comment]
How is it failing for you? Could you provide some more details?
