### ISSUE TITLE
Container tooling doesn't understand the rtm channel

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#35647]
The .NET 8 CI builds have moved to use `rtm` instead of `rc` in their version.

The code that determines the base image tag doesn't understand `rtm`:

https://github.com/dotnet/sdk/blob/bdfa7a19282caf2673dd1c59758543e6f286f006/src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs#L97-L119

This causes publishing container images to fail with CI built SDKs: 

```
error : CONTAINER2018: Invalid SDK prerelease version 'rtm' - only 'rc' and 'preview' are supported.
```

It's not possible to work around the failure by explicitly setting `ContainerBaseImage` because the base image tag is always calculated.

@baronfel the fix is to add `rtm`. I don't know what branch to target.

**Comment by baronfel** [comment]
I'd expect that to need to target release/8.0.1xx - I believe that branch has moved to release branding.

**Comment by baronfel** [comment]
Versioning label logic is [here](https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L20C1-L22) - we may need to add both `rtm` and `servicing` so that we don't have unexpected failures in the future.

**Comment by baronfel** [comment]
Closing this - we got this fixed for GA!
