### ISSUE TITLE
restore failing on Alpine arm32

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#35676]
See PR: https://github.com/dotnet/dotnet-docker/pull/4907

```
8.243 /usr/share/dotnet/sdk/8.0.100-rc.1.23463.5/Microsoft.Common.CurrentVersion.targets(5167,5): error MSB3030: Could not copy the file "/source/obj/Release/net8.0/linux-musl-arm/apphost" because it was not found. [/source/aspnetapp.csproj]
```

Only failed on `linux-musl-arm`.

**Comment by mthalman** [comment]
@richlander - This must be a regression in 8.0, right? I believe we were successfully using this command for the 7.0 samples.

**Comment by richlander** [comment]
Right.

**Comment by baronfel** [comment]
Reopened this - it's not a NuGet bug. Users should be able to restore for a particular architecture and the publish for that architecture without having to do an implicit restore.

**Comment by baronfel** [comment]
I'm having a hard time reproducing this one, and it looks like the `--no-restore` was added back in https://github.com/dotnet/dotnet-docker/pull/4958 - is this still a problem?

**Comment by marcpopMSFT** [comment]
Old issue triage: likely a point in time problem. Holler if still happening.
