### ISSUE TITLE
Using aspnetcore3.0 in WindowsDesktop SDK

### ISSUE THREAD

**Issue by Sodoshi** [dotnet/sdk#3568]
Because of the changes to the HostBuilder in aspnetcore3 I want to update my embedded Kestrel, but if I switch to the WindowsDesktop SDK its not available, only aspnetcore 2.2. Is there any way to reference aspnetcore 3? (I'm using Kestrel as a TCP server in my Windows forms app)

**Comment by dasMulli** [comment]
You should be able to add a framework reference to asp.net core in your csproj file:

```xml
<ItemGroup>
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```

**Comment by livarcocc** [comment]
@Sodoshi @dasMulli's suggestion is the recommended way to do that.
