### ISSUE TITLE
CheckForDuplicateItems case sensitive

### ISSUE THREAD

**Issue by stan-sz** [dotnet/sdk#35693]
The task CheckForDuplicateItems is case sensitive, potentially missing some duplicates that differ in case.

The fix would be on this line to pass a comparer:
https://github.com/dotnet/sdk/blob/c382c93f8dcad09417409799595a88da407e7e6d/src/Tasks/Microsoft.NET.Build.Tasks/CheckForDuplicateItems.cs#L38

MSBuild's [RemoveDuplicates](https://learn.microsoft.com/en-us/visualstudio/msbuild/removeduplicates-task?view=vs-2022) task is case insensitive, so this would align with MSBuild standard processing

**Comment by marcpopMSFT** [comment]
After offline discussion, we're ok taking this change as long as the comment about the test is resolved.
