### ISSUE TITLE
`ProjectReference` does not import build.props/build.targets to  like `PackageReference` does

### ISSUE THREAD

**Issue by dameng324** [dotnet/sdk#35704]
I'm working on NativeAOT with reflection using `Rd.xml`.
I create a library project named `Plugin` . in the project I create build directory and Plugin.props and Plugin.Rd.xml in it and pack it in to package like this:
Plugin.csproj
```xml
<ItemGroup>
  <Content Include="build\*.*">
	  <Pack>true</Pack>
	  <PackagePath>build;</PackagePath>
  </Content>
</ItemGroup>
```
build/Plugin.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup>
	  <RdXmlFile Include="$(MSBuildThisFileDirectory)Plugin.Rd.xml"/>
  </ItemGroup>
</Project>
```
build/Plugin.Rd.xml
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
	<Application>
		<Assembly Name="Plugin">
			<Type Name="Plugin.UseReflectionClass" Dynamic="Required All"/>
		</Assembly>
	</Application>
</Directives>
```
If I pack Plugin to a nuget package, and use `<ProjectReference Include="..\Plugin\Plugin.csproj" />` to reference it, It works correctly, I can publish my exe to native aot and use the RdXmlFile what `Plugin` project specified with no more configuration.
But when I directly use ProjectReference like `<ProjectReference Include="..\Plugin\Plugin.csproj" />` in my exe project, It does not work. It looks like does not import the `build/Plugin.props` to my exe project. 

Create a new nuget package every time library project changed code is too much trouble, how to use `ProjectReference` behave like `PackageReference`?

**Comment by ViktorHofer** [comment]
Could also be moved into the NuGet or msbuild repository.

**Comment by dameng324** [comment]
I found a similar issue In Nuget repo https://github.com/NuGet/Home/issues/6624 but it's 5 years before and not solved. I think feedback should not helpful there.

**Comment by ViktorHofer** [comment]
Yes, we have several issues requesting this type of feature: https://github.com/NuGet/Home/issues/6624, https://github.com/dotnet/msbuild/issues/5797

As mentioned [here](https://github.com/dotnet/msbuild/issues/5797#issuecomment-1780615714) I believe this could work as we already require an addition evaluation pass just for restore which could then dynamically add these files to subsequent evaluations. It's probably a matter of priority, cost and the potential of breaking existing customers.

I would love to see such a feature.

**Comment by dameng324** [comment]
Hope to see such a feature too. I have already use `DynamicDependencyAttribute`  to solve my nativeAOT problem. so this issue does not affect me now. You can close this issue as you want.
