### ISSUE TITLE
Container tooling creates many HTTP connections

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#35753]
I've been testing the SDK container tooling against various registries over the past two weeks.
As part of my test registries, I have 3 OpenShift test clusters available.

On two of the clusters I haven't seen issues. One the other one however, the tooling is failing more than it is succeeding.

I looked at the cluster configuration with a registry expert, and the conclusion is: this registry is configured with two backing pods and the the way they shared storage can cause consistency issues.

So the root cause for this issue isn't with the .NET implementation, but it is the registry storage configuration.

I have used this cluster before with the built-in tooling and in contrast to the .NET tooling, I have never seen it fail.
So the .NET tooling is somehow causing the consistency issues to appear more than the built-in container tooling.

After investigating further, I learned that the main difference is that the .NET client is using much more HTTP connections than the built-in client. Because it uses more connection, it's more likely to be using both backend pods while pushing an image.

The reason it's using many connection is that, connections are configured to be used no longer than 10ms:

https://github.com/dotnet/sdk/blob/2b89a6a1e70bb07f8c437e018de3056cbaf9d0f1/src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs#L35

I don't think there's a reason to set the connection lifetime.
Sometimes this is set to avoid stale DNS information, but that is not expected for the duration of the registry operations.
Also, the value used here is very low and it will expire multiple times during a push.

Another (unexpected) source of an additional connection is in the auth handler:

https://github.com/dotnet/sdk/blob/2b89a6a1e70bb07f8c437e018de3056cbaf9d0f1/src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs#L323-L329

When the request that caused the Unauthorized response wasn't fully read, that keeps the connection "in-use".
Then when the new request is made for authentication, it's forced to create a new HTTP connection.

Every new connection comes at the cost of some round-trips for the tls handshake, and it can rapidly account for tens of milliseconds (per connection made).

cc @baronfel

**Comment by baronfel** [comment]
Closed because the linked PR fixed this
