### ISSUE TITLE
Redistribute the portable RID graph from the Microsoft.NETCore.Platforms transport package

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#35750]
Runtime now publishes the portable and non portable RID graphs into the MIcrosoft.NETCore.Platforms transport package. The sdk repository should delete their copy of the portable RID graph and pick it up from the transport package instead.

In addition, the build task to manipulate the RID graph was moved over to runtime. Presumably, that task can now be deleted from the sdk repo.

@dsplaisted @elinor-fung @tmds

**Comment by marcpopMSFT** [comment]
Per all of the linked PRs, I believe this was completed.
