### ISSUE TITLE
dotnet run requires framework to be specified when multiple are present

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/sdk#358]
Given a project with multiple Target Frameworks, i.e. `net451;netcoreapp1.1` dotnet run should behave like it used to in project.json land. At a glance it looks like the old world prioritizes the netcoreapp tfm.

This is how it behaves today:
```
dotnet run
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Exe'.
```

**Comment by dsplaisted** [comment]
The `dotnet run` command evaluates the MSBuild project and [gets the value of the `RunCommand` property](https://github.com/dotnet/cli/blob/b354e1a3c65e21e64d288ec6f5bda11841b07465/src/dotnet/commands/dotnet-run/RunCommand.cs#L87).  For a cross-targeting project, this property will only be set in the inner build, not the outer build.  I don't think there's a good way for us to have the run properties set to reasonable values at evaluation time in the .NET SDK.

Could the `dotnet run` command instead read the value of the `TargetFrameworks` property if `RunCommand` is not set and the framework wasn't specified on the command line?  Then it could choose from the available target frameworks and re-query the value of the `RunCommand` property when `TargetFramework` is set to the one it chooses.

**Comment by piotrpMSFT** [comment]
Moved to CLI repo
