### ISSUE TITLE
symbols packages being generated empty

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#3581]
We have turned off symbols package generation for now on this repo.

They were generating empty nupkgs and conflicting with the actual nupkgs when the sign tool was repackaging signing assemblies.

The fact that symbols are empty here are causing symbol checks to fail on VS insertions.

**Comment by livarcocc** [comment]
This is now fixed right @dsplaisted ?

**Comment by dsplaisted** [comment]
It should be fixed.  I don't know if we validated it end-to-end.
