### ISSUE TITLE
Microsoft.NET.Build.Extensions.Tasks.dll	should not be loaded in devenv projecc during reference resolution for native vc projects

### ISSUE THREAD

**Issue by olgaark** [dotnet/sdk#3585]
The problem is found while investigating 
VS Bug 973252: Perf: CPlusPlus_DDRIT.0900.Close Solution regressed VM_AdjustedImagesInMemory_Total_devenv by 2.000 Count (0.5%). Baseline 29226.70

Microsoft.NET.Build.Extensions.Tasks.dll is loaded by _HandlePackageFileConflicts target during

Target Name=ResolveAssemblyReferences Project=ConsoleApplication1.vcxproj  note that there is no assembly references in the native vc project
            …
            Target Name=_HandlePackageFileConflicts Project=ConsoleApplication1.vcxproj

The target is implemented here:

f:\Visual Studio 16 Master\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets
============================================================================================================================================
-->
  <UsingTask TaskName="ResolvePackageFileConflicts" AssemblyFile="$(MicrosoftNETBuildExtensionsTasksAssembly)" />
  <Target Name="_HandlePackageFileConflicts" BeforeTargets="$(_HandlePackageFileConflictsBefore)" AfterTargets="$(_HandlePackageFileConflictsAfter)"  
DependsOnTargets="GetReferenceAssemblyPaths">
    <ResolvePackageFileConflicts References="@(Reference)" ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)" PlatformManifests="@(PackageConflictPlatformManifests)" TargetFrameworkDirectories="$(TargetFrameworkDirectory)" PackageOverrides="@(PackageConflictOverrides)" PreferredPackages="$(PackageConflictPreferredPackages)">
      <Output TaskParameter="ReferencesWithoutConflicts" ItemName="_ReferencesWithoutConflicts" />
      <Output TaskParameter="ReferenceCopyLocalPathsWithoutConflicts" ItemName="_ReferenceCopyLocalPathsWithoutConflicts" />
      <Output TaskParameter="Conflicts" ItemName="_ConflictPackageFiles" />
    </ResolvePackageFileConflicts>

Is this target doing something applicable to vc projects? If not, please either disable it for vcxproj or add a condition so cpp targets can disable it.
At least, please add a condition there for empty @(Reference) so the task dll is not loaded in this case.

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by dsplaisted** [comment]
@olgaark Can you provide a sample VC project where this is occurring?  Thanks.
