### ISSUE TITLE
MSBuild doesn’t define variables for .NET core?

### ISSUE THREAD

**Issue by Const-me** [dotnet/sdk#3588]
Using VS2017 15.9.5, building a class library for .NET core 2.2. Here’s the relevant XML from my .csproj file:

	<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
			<TargetFramework>netcoreapp2.2</TargetFramework>
			
		</PropertyGroup>
		<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
			<DocumentationFile>$(OutputPath)doc.xml</DocumentationFile>
		</PropertyGroup>
		<ItemGroup>
			<Reference Include="System">
				<HintPath>System</HintPath>
			</Reference>
		</ItemGroup>
	</Project>

The setting is used, but the doc.xml is produced in the root of the project instead of $(OutputPath).

Same XML expression for `<DocumentationFile>` works OK for desktop .NET, i.e. the problem is specific to .NET Core projects.

Tried `$(OutDir)` and `$(qwer123)` got same result. Why $(OutputPath) is not defined? Maybe it has different name?

**Comment by livarcocc** [comment]
@dsplaisted can you help out?

**Comment by dsplaisted** [comment]
The `OutputPath` property isn't defined until after the body of your project is evaluated.  It's not possible to set it beforehand, as the output path depends on properties defined in your project file (such as the target framework).

It may have worked in non Sdk-style projects if you were putting the DocumentationFile after Microsoft.CSharp.targets was imported.

For Sdk-style projects, you can simply set `GenerateDocumentationFile` to true, and it will create the documentation file with the right name in your project's output:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```

**Comment by Const-me** [comment]
@dsplaisted Thanks, appears to work OK. I’m happy with the default name + location of that XML. Here’s the project, BTW: https://github.com/Const-me/ComLightInterop
