### ISSUE TITLE
Merge .net format repo into SDK or roslyn repos

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#35915]
Reasons for this effort

- Most if not all of the changes in the past 6 months into .net format have been codeflow related. Merging into another repo would get those changes by default
- format broke in 7.0.3xx because it wasn't taking roslyn flows actively #32598
- Source build has reported issues with format
- Format repo has a runtime dependency which adds to the codeflow graph: 
    https://github.com/dotnet/format/blob/main/eng/Version.Details.xml#L33

**Comment by arkalyanms** [comment]
Marked for 9.0.1, but likely will come in the middle of .net9 after some of our committed investments are complete.
