### ISSUE TITLE
[NETSDKE2E]Duplicate workload version info displays in dotnet --info of NET8 RTM SDK

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#35920]
Reproduction Steps
1.install 8.0.100-rtm.23506.1 RTM SDK 
2. In CLI, run "dotnet --info"
Expected behavior
The contents display correctly in dotnet --info
Actual behavior
Duplicate workload version info displays in dotnet --info.
![image](https://github.com/dotnet/sdk/assets/65637796/f889b5de-f818-4428-b5ce-d08f1a852ee0)

**Comment by v-jieyan2** [comment]
This problem is also reproduced on Win ARM64.

**Comment by ChenhuiYuan01** [comment]
This problem is also reproduced on 9.0.100-alpha.1.23564.26
![info](https://github.com/dotnet/sdk/assets/92560562/3a5bab7d-f228-4113-a67e-bfe1f435f13f)

**Comment by vdanche** [comment]
This issue has been fixed on  9.0.100-alpha.1.24053.14
![image](https://github.com/dotnet/sdk/assets/65637796/7a88e3ef-bb3a-407c-ac6a-9e4430ac5270)

**Comment by Forgind** [comment]
Thanks for the confirmation @vdanche!
