### ISSUE TITLE
`dotnet test --blame` does not 

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#3593]
dotnet SDK version: 2.2.401

`dotnet test -f netcoreapp2.1 --no-build --blame`  should produce a `Sequence.xml` file while running tests so we can know what test was running at the time of a crash or hang. But it doesn't create this file.

```
  --blame                                  Run the tests in blame mode. This option is helpful in isolating a problematic test causing the test host to crash.
                                           Outputs a 'Sequence.xml' file in the current directory that captures the order of execution of test before the crash.
```

Without this file, for async tests on linux it's impossible to know which test was running when the test runner hung.

**Comment by livarcocc** [comment]
This issue should be moved to microsoft/vstest.

Unfortunately, my mover is not working right now.

**Comment by AArnott** [comment]
OK, I'll move it.

**Comment by AArnott** [comment]
Moved to https://github.com/microsoft/vstest/issues/2154
