### ISSUE TITLE
Provide well defined bahvior for `--`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#35952]
Here's my .NET 8 app:

```csharp
foreach (var arg in args)
{
    Console.WriteLine(arg);
}
```

Here's the behavior:

```bash
$ dotnet run blah -- foo bar
blah
foo
bar
```

That doesn't strike me as well-defined behavior.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run

**Comment by baronfel** [comment]
What part feels not-well-defined to you?  I'm guessing the inclusion of `blah`?

**Comment by baronfel** [comment]
The `--` syntax as implemented by System.CommandLine follows the guidelines set in the [GNU Program Argument Syntax Conventions](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) document, specifically

>  The argument -- terminates all options; any following arguments are treated as non-option arguments, even if they begin with a hyphen. 

And also generally [The Open Group's Utility Conventions, Guideline 10](https://pubs.opengroup.org/onlinepubs/7908799/xbd/utilconv.html):

> The argument `--` should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the "-" character. The `--` argument should not be used as an option or as an operand. Applications calling any utility with a first operand starting with `-` should usually specify `--`, as indicated by Guideline 10, to mark the end of the options. This is true even if the SYNOPSIS in the XCU specification does not specify any options; implementations may provide options as extensions to the XCU specification. The standard utilities that do not support Guideline 10 indicate that fact in the OPTIONS section of the utility description. 

This means that anything _after_ the `--` will definitely be forwarded to the app, but that's not exclusively the case. `dotnet run` has a grammar with a specific set of options, and any unrecognized tokens in that grammar are interpreted as being forwarded to the underlying application. This means that `--` is only necessary to disambiguate tokens that exist in `run`s grammar and the forwarded application. This is like the `time` command - it forwards along any tokens it doesn't explicitly know about to the running command.

**Comment by richlander** [comment]
OK. I didn't know that. Good to know. Thanks for explanation.

Yes, it was "blah" I was focussed on.
