### ISSUE TITLE
Unable to publish to Alpine image, executable not found or runtime identifier 'linux-musl-x64' not supported

### ISSUE THREAD

**Issue by chingucoding** [dotnet/sdk#35981]
### Description

I'm trying to package an app using the container publishing option, however when trying to publish using an Alpine image I'm running into this issue:

exec /app/alpine-test: no such file or directory

After some research, I found out that this might be caused by Alpine using linux-musl-x64, however when trying to publish using linux-musl-x64, I'm getting the following errors:

```
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018: The "CreateNewImage" task failed unexpectedl
y. [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018: Microsoft.NET.Build.Containers.BaseImageNotF
oundException: The RuntimeIdentifier 'linux-musl-x64' is not supported by dotnet/runtime:7.0-alpine. The supported RuntimeIdentifiers are linux-x64,linux,unix,any,base,unix-x64,linux-
arm,unix-arm,linux-arm64,unix-arm64 [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Containers.Registr
y.PickBestImageFromManifestListAsync(String repositoryName, String reference, ManifestListV2 manifestList, String runtimeIdentifier, String runtimeIdentifierGraphPath, CancellationTok
en cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Registry.cs:line 183 [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Containers.Registr
y.GetImageManifestAsync(String repositoryName, String reference, String runtimeIdentifier, String runtimeIdentifierGraphPath, CancellationToken cancellationToken) in /_/src/Containers
/Microsoft.NET.Build.Containers/Registry.cs:line 134 [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.C
reateNewImage.ExecuteAsync(CancellationToken cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 49 [E:\Projects\alpine-test\alpine-tes
t.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.C
reateNewImage.Execute() in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 32 [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionH
ost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [E:\Projects\alpine-test\alpine-test.csproj]
C:\Users\Marcel\.nuget\packages\microsoft.net.build.containers\7.0.306\build\Microsoft.NET.Build.Containers.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.Ex
ecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [E:\Projec
ts\alpine-test\alpine-test.csproj]
```

### Reproduction Steps

1. Run `dotnet new webapi`
1. Add the following to the first property group:
```
<ContainerImageName>alpine_test</ContainerImageName>
<ContaineRuntimeIdentifier>linux-x64</ContaineRuntimeIdentifier> <!-- or use linux-musl-x64 for build error
<ContainerBaseImage>mcr.microsoft.com/dotnet/runtime:7.0-alpine</ContainerBaseImage>
<EnableSdkContainerSupport>true</EnableSdkContainerSupport>
```
3. Run `dotnet restore` and run `dotnet publish -c Release --no-self-contained -r linux-x64 /t:PublishContainer` or `dotnet publish -c Release --no-self-contained -r linux-musl-x64 /t:PublishContainer`depending on what is used in the first property group
4. Start docker container if it can be build and observe the container immediately crashing because it can't find the app

### Expected behavior

We should be able to build an alpine image and run the project inside it

### Actual behavior

The container either fails to find the application despite it being inside the image or it cannot be build.

### Configuration

dotnet --version: 7.0.306
OS: Windows 11 22H2 Build 22621.2361

### Other information

I've also found https://github.com/dotnet/runtime/issues/62219 which seems to be in the same area but hits different issues surrounding the RID linux-musl-x64

**Comment by chingucoding** [comment]
Sorry for using the wrong repository and thank you for transfering @baronfel and @vitek-karas !

While I wasn't able to get it working with 7.0.12, I was able to get it working with .NET 8 RC2. The issue with linux-musl-x64 not existing is definitely fixed with 8.0.

The only issue was that using the runtime image (mcr.microsoft.com/dotnet/runtime:8.0.0-rc.2-alpine3.18-amd64), I got the following error when starting the image:
```
You must install or update .NET to run this application.

App: /app/alpine-test.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '8.0.0-rc.2.23480.2' (x64)
.NET location: /usr/share/dotnet/

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0-rc.2.23480.2&arch=x64&rid=linux-musl-x64&os=alpine.3.18
```

Using the SDK image got it working, however this seems like a regression to me 🤔

**Comment by baronfel** [comment]
You used the runtime image but are building an ASP.NET app - you should use the dotnet/aspnet image instead for this scenario.

The tooling should infer this correctly for you if you remove the explicit use of ContainerBaseImage and use ContainerFamily instead to specify the alpine family of base images:

```xml
<ContainerFamily>alpine3.18<ContainerFamily>
```

**Comment by chingucoding** [comment]
Oh you are right, that does indeed work. And also thank you for mentioning the `ContainerFamily` property, that makes life a lot easier. Since the problem is not present in .NET 8 (assuming it doesn't regress until release), should this issue be closed?

**Comment by baronfel** [comment]
I'm happy to close this, and even happier that the ContainerFamily work is useful :) Thanks for reporting and trying the newer versions to verify!
