### ISSUE TITLE
8.0.100-rc.1 dotnet tool update fails

### ISSUE THREAD

**Issue by jcoburn** [dotnet/sdk#36015]
dotnet tool update -g dotnet-reportgenerator-globaltool
Fails for NEt8, works for Net6 (added global.json)

NET 8
dotnet --version
8.0.100-rc.1.23463.5
dotnet tool list -g
Package Id                             Version      Commands
-------------------------------------------------------------------
dotnet-reportgenerator-globaltool      5.1.25       reportgenerator
dotnet tool update -g dotnet-reportgenerator-globaltool
C:\Users\jcoburn\AppData\Local\Temp\159c8377-33a3-4e7f-9045-a43e2951a593\restore.csproj : error NU1102: Unable to find
package dotnet-reportgenerator-globaltool with version (>= 5.1.26)
C:\Users\jcoburn\AppData\Local\Temp\159c8377-33a3-4e7f-9045-a43e2951a593\restore.csproj : error NU1102:   - Found 17 ve
rsion(s) in BaGetServer [ Nearest version: 5.1.25 ]
C:\Users\jcoburn\AppData\Local\Temp\159c8377-33a3-4e7f-9045-a43e2951a593\restore.csproj : error NU1102:   - Found 0 ver
sion(s) in Microsoft Visual Studio Offline Packages
C:\Users\jcoburn\AppData\Local\Temp\159c8377-33a3-4e7f-9045-a43e2951a593\restore.csproj : error NU1102:   - Found 0 ver
sion(s) in C:\Program Files\dotnet\library-packs
Tool 'dotnet-reportgenerator-globaltool' failed to update due to the following:
The tool package could not be restored.
Tool 'dotnet-reportgenerator-globaltool' failed to install. This failure may have been caused by:

NET 6
dotnet --version
6.0.414
dotnet tool list -g
Package Id                             Version      Commands
-------------------------------------------------------------------
dotnet-reportgenerator-globaltool      5.1.25       reportgenerator
dotnet tool update -g dotnet-reportgenerator-globaltool
Tool 'dotnet-reportgenerator-globaltool' was reinstalled with the latest stable version (version '5.1.25').

**Comment by JL03-Yue** [comment]
Could you upload the result of `dotnet --info`?

**Comment by jcoburn** [comment]
Have update to 8.0.100-rc.2.23502.2 and unable to reproduce.

**Comment by JL03-Yue** [comment]
Thanks
