### ISSUE TITLE
In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to atleast AspNetCoreModuleV2.

### ISSUE THREAD

**Issue by RoyalMugu** [dotnet/sdk#3606]
I have created a Asp.net core web application. I am able to rebuild successfully but when I try to publish the solution to Azure App Service, I am getting the below error,
============================================================
The "TransformWebConfig" task failed unexpectedly.
System.Exception: In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to atleast AspNetCoreModuleV2.
   at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.TransformAspNetCore(XElement aspNetCoreElement, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModel)
   at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.Transform(XDocument webConfig, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModel, String environmentName)
   at Microsoft.NET.Sdk.Publish.Tasks.TransformWebConfig.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

============================================================
Environment:
.Net Core 2.2
.Net Core runtime 2.2.6 (x64)
Asp.Net core 2.2.6 - Shared Framework

How do I change the AspNetCoreModule to atleast AspNetCoreModuleV2 in the appsettings.json file? 
Also I dont want to change it to out of process hosting.

I am not sure if I will be able to publish even after making this change. Any of your inputs will be helpful.

**Comment by livarcocc** [comment]
@vijayrkn this seems like a web sdk issue. Can you move it to the web sdk repo?

**Comment by mkArtakMSFT** [comment]
@shirhatti is this ours? Should this move to `AspNetCore`?

**Comment by vijayrkn** [comment]
@RoyalMugu Do you have a property by name `AspNetCoreModuleName` in your csproj or local web.config?  If it is present, is it set to `AspNetCoreModule` ?

To fix this you need to change this to target AspNetCoreModuleV2 depending on whether it is defined in the csproj or web.config. 

`<AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>`

**Comment by Dunnymeister** [comment]
We're experiencing the same issue and am happy to help others try reproduce.

@vijayrkn We don't have any properties called AspNetCoreModuleName in our web.config or csproj

**Comment by vijayrkn** [comment]
@dunnymeister- does adding this property to the csproj fix the issue?

**Comment by Dunnymeister** [comment]
Yes it did, thanks!

The full XML excerpt that needs to be added is:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
  </PropertyGroup>
```

I didn't add the suggested line as it wasn't part of the document I was following https://weblog.west-wind.com/posts/2019/Mar/16/ASPNET-Core-Hosting-on-IIS-with-ASPNET-Core-22 (included in case others find their way here)

**Comment by livarcocc** [comment]
I am going to close this issue as @vijayrkn's guidance solved the issue.

**Comment by mikelazelle** [comment]
This solved my issue. Thank you

**Comment by markentingh** [comment]
I was getting the same error after upgrading from 2.1 to .Net Core 3.0. I had to download the Runtime & Hosting Bundle For Windows: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-hosting-bundle-installer

**Comment by thiagosrios** [comment]
> 
> 
> I was getting the same error after upgrading from 2.1 to .Net Core 3.0. I had to download the Runtime & Hosting Bundle For Windows: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-hosting-bundle-installer. Also, I had to change my web.config `modules` attribute
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <system.webServer>
>     <handlers>
>       <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
>     </handlers>
>     <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
>   </system.webServer>
> </configuration>
> ```

Thanks, this answer solved my problem!

**Comment by yhnavein** [comment]
Alternatively you can just remove `web.config`

**Comment by Gonen09** [comment]
My project is an API and I am going to publish it in a Lambda function in AWS. In my case I moved my project from Net Core 2.2 to 3.1 and at the time of publishing I got the following error: In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to at least AspNetCoreModuleV2. Then change in the web.config file this modules="AspNetCoreModule" to this modules="AspNetCoreModuleV2". Without installing anything else. thank you @markentingh

**Comment by conorfoley** [comment]
> @RoyalMugu Do you have a property by name `AspNetCoreModuleName` in your csproj or local web.config? If it is present, is it set to `AspNetCoreModule` ?
> 
> To fix this you need to change this to target AspNetCoreModuleV2 depending on whether it is defined in the csproj or web.config.
> 
> `<AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>`

This worked for me, thank you!

**Comment by RaphHaddad** [comment]
**My Situation** A broken publish build on Azure DevOps hosted build agents with an F# netcore3.0 web project.

**The Fix** Using @markentingh 's web.config changes above. Thank you. 🙏

**Comment by codejq** [comment]
just edit the project file and add 

```
 <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```

**Comment by RichieRunner** [comment]
> I was getting the same error after upgrading from 2.1 to .Net Core 3.0. I had to download the Runtime & Hosting Bundle For Windows: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-hosting-bundle-installer. Also, I had to change my web.config `modules` attribute
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <system.webServer>
>     <handlers>
>       <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
>     </handlers>
>     <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
>   </system.webServer>
> </configuration>
> ```

This is the answer for anyone who *doesn't* have `<AspNetCoreHostingModel>` in their `.csproj`. Thank you for this!

**Comment by anandtpatel** [comment]
> Yes it did, thanks!
> 
> The full XML excerpt that needs to be added is:
> 
> ```
>   <PropertyGroup>
>     <TargetFramework>netcoreapp2.2</TargetFramework>
>     <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
>     <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
>   </PropertyGroup>
> ```
> 
> I didn't add the suggested line as it wasn't part of the document I was following https://weblog.west-wind.com/posts/2019/Mar/16/ASPNET-Core-Hosting-on-IIS-with-ASPNET-Core-22 (included in case others find their way here)


Adding this help solve my issue

`<PropertyGroup>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>`

**Comment by vijayrkn** [comment]
@anandtpatel - Do you already have a web.config file in your project that you want to use for the deployed app? Then setting the property is fine. To be clear, when you set this property, the sdk will not do any transform operations on the web.config. So, it will be up to the developer to make sure that the web.config in the projects is up to date. 

For developers who don't have a web.config file locally, please don't add this property. Adding this property will signal the SDK to not generate the web.config
