### ISSUE TITLE
Way to make `dotnet run` as `Release`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#36072]
I often use `dotnet run`. It's great! It's a very convenient one-liner for running my console or web app. It wouldn't say I "use it for scripting" but it's headed in that direction.

I'd like a way to make it run as `-c Release` by default. If I run `dotnet build` then I want things to work the way they do now. The idea that `dotnet run` should be a wrapper over `dotnet build -c Debug` and only ever that seems quite limiting.

I'm proposing this as an opt-in feature, like `RunConfiguration`.

A good example of where this would be useful: https://benchmarkdotnet.org/articles/guides/how-to-run.html

**Comment by DamianEdwards** [comment]
Seems like yet another candidate for having configurable CLI defaults similar to git @baronfel

**Comment by baronfel** [comment]
Definitely, this would be part of https://github.com/dotnet/sdk/issues/9344 IMO. I'll close as a default there, but I think we have a few good use cases:

* configuration defaults
* framework defaults for dotnet new
* command aliases

And this would be hierarchical at least to two levels:
* user profile
* repo/cwd profile

I'll close this as a dupe and link it to the canonical issue.

**Comment by richlander** [comment]
@agocke
