### ISSUE TITLE
Swixbuild task is now failing against .NET 8 RC 2

### ISSUE THREAD

**Issue by pjcollins** [dotnet/sdk#36081]
### Describe the bug
Some MAUI workload builds recently started failing after build machines were upgraded to build with 8.0.100-rc.2.23502.2.

I've created a smaller repro with an empty project that uses a `MicroBuild.Plugins.SwixBuild.Dotnet` package reference and the problematic `SetBulkPayloadInfo` task that will hopefully make diagnosis easier. The task is no longer able to load `System.Security.Permissions`. The RC 2 SDK is missing the following files as compared to RC 1, though I am not sure if this was an intentional change?

```diff
-Microsoft.Win32.SystemEvents.dll*
-System.Drawing.Common.dll*
-System.Security.Permissions.dll*
-System.Windows.Extensions.dll*
```

This repro may be somewhat isolated, but these changes may have some impact on other folks.

### To Reproduce
The following repro builds against RC 1 and fails to build with RC 2. Download rc2repro.zip, and build:

    dotnet build -v:n rc2repro\test2.csproj

[rc2repro.zip](https://github.com/dotnet/sdk/files/12885981/rc2repro.zip)

### Exceptions (if any)

         test2.csproj(24,5): error : Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### Further technical details
```
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\
```

**Comment by pjcollins** [comment]
cc @rmarinho @joeloff

**Comment by joeloff** [comment]
That's a transitive dependency that used to be part of the SDK. Best option is to pin yourself to the 6.0.4xx SDK using a global JSON.

**Comment by pjcollins** [comment]
I'm going to mark this as resolved as we've worked around this in a few places, and this appears to be a corner case specific to us.
