### ISSUE TITLE
We're seeing timeouts in some of the package install tests

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#36089]
I think the tools PR introduced a test timeout in the ubuntu leg. Some test in the below set of 7 tests is timing out. We'll want to investigate and solve. Filing this and we can potentially disable those tests until we can track down the issue.
 
[Pipelines - Run 20231012.74 (azure.com)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436626&view=results)
[Pipelines - Run 20231012.73 (azure.com)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=436602&view=results)
dotnet exec Microsoft.DotNet.PackageInstall.Tests.dll -testExecutionDirectory /datadisks/disk1/work/A9770942/w/B717096B/e/testExecutionDirectory -xml testResults.xml -class Microsoft.DotNet.PackageInstall.Tests.ToolPackageInstallToManagedLocationInstaller -class Microsoft.DotNet.PackageInstall.Tests.ToolPackageUninstallerTests -class Microsoft.DotNet.PackageInstall.Tests.UnixFilePermissionsTests

<img width="551" alt="image" src="https://github.com/dotnet/sdk/assets/12663534/1b76fb9a-83f8-406d-bef1-c2ec73126693">

**Comment by JL03-Yue** [comment]
Closed as #36192 closed
