### ISSUE TITLE
SDK defined properties overwrites WarningsAsErrors on solution level

### ISSUE THREAD

**Issue by lg2de** [dotnet/sdk#3613]
The following statement is intended to define WarningsAsErrors for "NU1605" if not defined.

https://github.com/dotnet/sdk/blob/87f00dbd00e72ca5e3e42b2e1f7b553c2e2f4f32/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L19

But defining `<WarningsAsErrors />` at solution level (Directory.Build.props) may cause unexpected overwrite, e.g. in server (TFS) build:

```
2019-09-09T13:32:15.6813986Z                    Property reassignment: $(WarningsAsErrors)="NU1605" (previous value: "") at C:\build\_work\_tool\dncs\3.0.100-preview6-012264\x64\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CSharp.props (19,5)
```

Instead of getting "all warnings as errors" only NU1605 will be trait as error.

**Comment by lg2de** [comment]
#1329 introduced this problem assuming that only an existing list of warnings is used.
It is not working for "all warnings as error".

The only work-around I found so far is: Specify `<WarningsAsErrors />` in each project explicitly. But I would like to ensure enabling it in ALL projects.

**Comment by dsplaisted** [comment]
@lg2de Can you put `<WarningsAsErrors />` in the Directory.Build.targets file instead of the .props?  Then it would set it after the default values from the .props.

I also think it would make sense to change the relevant line in the props to this::

```xml
<WarningsAsErrors>$(WarningsAsErrors);NU1605</WarningsAsErrors> 
```

**Comment by lg2de** [comment]
Hey @dsplaisted. That's exactly what I thought. I did a PR for it right away.
