### ISSUE TITLE
PackageInstall.Tests timeout known build error

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#36192]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=441319
Build error leg or test failing: Microsoft.DotNet.PackageInstall.Tests.dll.3.WorkItemExecution
Pull request: https://github.com/dotnet/sdk.git/pull/36182

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Microsoft.DotNet.PackageInstall.Tests.dll.3' END OF WORK ITEM LOG: Command timed out, and was killed",
  "ErrorPattern": "",
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=441319
**Error message validated:** `Microsoft.DotNet.PackageInstall.Tests.dll.3' END OF WORK ITEM LOG: Command timed out, and was killed`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/17/2023 9:54:36 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
@marcpopMSFT I added this so CI runs will retry (and so that the stats are clear)

**Comment by marcpopMSFT** [comment]
Thanks. Remind me what the process is for generating issues like this that arcade can track?

I had filed this issue manually to track the timeout. Annie is doing some investigation but is considering just disabling the tests on the ubuntu leg for now.
https://github.com/dotnet/sdk/issues/36089

**Comment by JL03-Yue** [comment]
Investigating

**Comment by lewing** [comment]
> Thanks. Remind me what the process is for generating issues like this that arcade can track?
> 

https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#when-and-how-to-report-a-known-issue

> I had filed this issue manually to track the timeout. Annie is doing some investigation but is considering just disabling the tests on the ubuntu leg for now. #36089

**Comment by lewing** [comment]
closing
