### ISSUE TITLE
SDK needs newer version of format

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#36219]
The main branch currently has a dependency on an older version of dotnet/format. That older version has a dependency on Microsoft.Build.Locator.1.5.5 which is causing a source build failure: https://github.com/dotnet/installer/pull/17524#issuecomment-1768956716. This needs to be updated to the latest version of format so that it can point to 1.6.10 instead (https://github.com/dotnet/format/pull/1957).

**Comment by arkalyanms** [comment]
@jjonescz was working with Matt to get this code flow going I believe.

**Comment by jjonescz** [comment]
There seems to be the latest format version in SDK. Most recent flow: https://github.com/dotnet/sdk/pull/36250

**Comment by jjonescz** [comment]
And the mentioned installer PR seems to be completed, so I guess this is also done.

**Comment by mthalman** [comment]
Yep, all good here.
