### ISSUE TITLE
# I have a fix !

### ISSUE THREAD

**Issue by gwitus** [dotnet/sdk#36286]
# I have a fix !

1. Run `sudo apt remove --purge --autoremove *dotnet*`
1. **create** or **modify** `/etc/apt/preferences` and **add** (you'll need `sudo`)

    ```
    Package: *net*
    Pin: origin packages.microsoft.com
    Pin-Priority: 1001
    ```

    Run `man apt_preferences` for more info about this config.
1. Run `sudo apt install dotnet-sdk-6.0`
1. Enjoy !

---

Output of `cat /etc/*release`:

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21
DISTRIB_CODENAME=vanessa
DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
```

_Originally posted by @olfek in https://github.com/dotnet/sdk/issues/27129#issuecomment-1214358108_

**Comment by gwitus** [comment]
OMG, Thanks!

**Comment by adegeo** [comment]
This looks like spam, it's just copying a reply in another issue...

**Comment by danmoseley** [comment]
I'm going to close this. If there is a real issue please open a new one that is clear about the problem.
