### ISSUE TITLE
Retarget task in dotnet/sdk to net5.0 when ready to insert nuget bits targetinig net5.0

### ISSUE THREAD

**Issue by heng-liu** [dotnet/sdk#3629]
When it's ready to insert nuget bits targeting net5.0,
please remember to go to the dotnet/SDK repository , change sdk/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj to retarget net5.0.

So that SDK will resolve the NuGet.Packaging targeting net5.0.

**Comment by nkolev92** [comment]
Example retargeting PR: https://github.com/dotnet/sdk/pull/3353
