### ISSUE TITLE
SDK ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#36323]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=441578

### Build leg reported

Build / Ubuntu_20_04_TemplateEngine / Ubuntu_20_04_TemplateEngine Build_Release / Set skipComponentGovernanceDetection variable

### Pull Request

https://github.com/dotnet/sdk/pull/36162

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "ENOSPC: no space left on device, write",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=441578
**Error message validated:** `ENOSPC: no space left on device, write`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 10/20/2023 4:07:13 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[452484](https://dev.azure.com/dnceng-public/public/_build/results?buildId=452484)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/452484/logs/89)|dotnet/sdk#36432|
|[452265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=452265)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/452265/logs/97)|dotnet/sdk#36432|
|[451838](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451838)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451838/logs/81)|dotnet/sdk#36452|
|[450748](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450748)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450748/logs/311)|dotnet/sdk#36452|
|[451638](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451638)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451638/logs/207)|dotnet/sdk#36476|
|[451548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451548)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451548/logs/221)|dotnet/sdk#36432|
|[451535](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451535)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451535/logs/97)|dotnet/sdk#36476|
|[451467](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451467)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451467/logs/90)|dotnet/sdk#36432|
|[451339](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451339)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451339/logs/97)|dotnet/sdk#36432|
|[451064](https://dev.azure.com/dnceng-public/public/_build/results?buildId=451064)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/451064/logs/169)|dotnet/sdk#36432|
|[450961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450961)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450961/logs/89)|dotnet/sdk#36432|
|[450931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450931)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450931/logs/89)|dotnet/sdk#36454|
|[450780](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450780)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450780/logs/81)|dotnet/sdk#36432|
|[450148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450148)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450148/logs/221)|dotnet/sdk#36432|
|[450393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450393)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450393/logs/165)|dotnet/sdk#36430|
|[450018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450018)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450018/logs/165)|dotnet/sdk#36438|
|[450183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450183)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450183/logs/89)|dotnet/sdk#34946|
|[450087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=450087)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/450087/logs/89)|dotnet/sdk#36410|
|[449323](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449323)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449323/logs/165)|dotnet/sdk#36419|
|[449310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449310)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449310/logs/165)|dotnet/sdk#36418|
|[449865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449865)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449865/logs/97)|dotnet/sdk#36432|
|[449632](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449632)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449632/logs/89)|dotnet/sdk#36432|
|[449473](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449473)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449473/logs/179)|dotnet/sdk#36432|
|[449139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449139)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449139/logs/179)|dotnet/sdk#36412|
|[449528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449528)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449528/logs/89)|dotnet/sdk#36410|
|[449462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449462)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449462/logs/81)|dotnet/sdk#36410|
|[449420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449420)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449420/logs/81)|dotnet/sdk#36430|
|[449163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449163)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449163/logs/97)|dotnet/sdk#36414|
|[449109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449109)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449109/logs/97)|dotnet/sdk#36410|
|[449048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449048)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449048/logs/97)|dotnet/sdk#36396|
|[449044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=449044)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/449044/logs/81)|dotnet/sdk#36407|
|[448933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448933)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448933/logs/169)|dotnet/sdk#36398|
|[448615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448615)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448615/logs/165)|dotnet/sdk#36289|
|[448634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448634)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448634/logs/165)|dotnet/sdk#36398|
|[448699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448699)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448699/logs/89)|dotnet/sdk#36399|
|[448577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448577)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448577/logs/89)|dotnet/sdk#36384|
|[448483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448483)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/448483/logs/81)|dotnet/sdk#36395|
|[447968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447968)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/447968/logs/97)|dotnet/sdk#36384|
|[447851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447851)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/447851/logs/57)|dotnet/sdk#36365|
|[445147](https://dev.azure.com/dnceng-public/public/_build/results?buildId=445147)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/445147/logs/235)|dotnet/sdk#36276|
|[444583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444583)|dotnet/sdk|Set skipComponentGovernanceDetection variable|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/444583/logs/81)|dotnet/sdk#36276|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|40|41|

**Comment by lewing** [comment]
Did the count reset when the issue was moved?

**Comment by marcpopMSFT** [comment]
@dotnet/dnceng I'm going to need help understanding why the images are running out of space. How does one investigate this type of issue? Is the cause from the SDK tests or something else? What's using up all the space?
