### ISSUE TITLE
Referencing a .net7.0-windows project from a net7.0 project when ReferenceOutputAssembly == false results in build error

### ISSUE THREAD

**Issue by nick-beer** [dotnet/sdk#36352]
### Describe the bug
I'm working on a project that spans WSL and its Windows host.  Specifically, I have a dotnet process that I run on WSL (targets `net7.0`), and it starts a process on the Windows host that is built from a project in my current `.sln` (targets `net7.0-windows`).  I've validated that this works (from my wsl process, I call `Process.Start` on `dotnet.exe`, and pass it the Windows process' .dll file).

However, I would like to enforce build ordering of these two projects such that that Windows project is always built before the Linux process.  This ensures the local development workflow (on WSL) is always using the latest windows project changes when running the wsl project. Historically, I've done this by using a `ProjectReference` with `ReferenceOutputAssembly=false`.  However, when I do this, I get the following error:

```
dotnet/sdk/7.0.304/Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '...' targets 'net7.0-windows10.0.17763.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v7.0'.
```

I understand the intent of the error, but it's blocking what I believe is a valid (though admittedly specific...) use case.

### To Reproduce
1. Create a project that targets `net7.0`
2. Create another project that targets `net7.0-windows`
3. Add a `ProjectReference` from the `net7.0` project to the `net7.0-windows` project
4. Build - see the error listed above
5. Update the project reference to contain `ReferenceOutputAssembly="false"`
6. Build - still see the error.  I would argue we should not - or it should at least be configurable.

**Comment by ViktorHofer** [comment]
Please try also adding the `SkipGetTargetFrameworkProperties=true` metadata to the ProjectReference item.

**Comment by nick-beer** [comment]
Thanks @ViktorHofer! That's just what I was looking for - works great.

**Comment by ViktorHofer** [comment]
@dsplaisted should we document that behavior?
