### ISSUE TITLE
Multiple RC versions listed in sdk-manifests

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#36385]
A [recent build of 8.0.100 SDK](https://dotnetbuilds.azureedge.net/public/Sdk/8.0.100-rtm.23522.1/dotnet-sdk-8.0.100-rtm.23522.1-linux-x64.tar.gz) for GA release shows that the `sdk-manifests` directory has multiple RC versions listed. It contains the following directories:

* 8.0.100-rc.1
* 8.0.100-rc.2
* 8.0.100-rtm

Is this intentional? I also saw that the official RC2 release of the SDK included the `sdk-manifests/8.0.100-rc.1` directory.

/cc @marcpopMSFT in case this is something that needs to be addressed for GA

**Comment by marcpopMSFT** [comment]
This is expected. Non-runtime workloads churn even after the runtime has locked down so we don't have the ability to get those into the baseline manifest versions. We will update those all to GA versions with 8.0.101 and leave them at that version (they'll be on a stable band at that point so everything will be the 8.0.100 folder with specific version subfolders at that point). I believe the RC1 one will get updated before GA but that work is tracked separately.
