### ISSUE TITLE
Package restore can't find runtime packs when explicit RID specified

### ISSUE THREAD

**Issue by wjk** [dotnet/sdk#3638]
When I try to restore a project that contains one or more RIDs specified in the project file `RuntimeIdentifiers` property, it cannot find a matching version of the following packages:

* `Microsoft.NETCore.App.Runtime.<rid>`
* `Microsoft.AspNetCore.App.Runtime.<rid>`
* `Microsoft.NETCore.WindowsDesktop.Runtime.<rid>`

It says that there are other versions of these packages available on NuGet.org, but no matter what I try I cannot get the package restore to use the versions that actually exist. I've tried numerous SDK versions in the `global.json` file, to no avail. The only way I can get my project to restore (and, therefore, build) is to remove the `RuntimeIdentifiers` property from the csproj file. This can break other parts of my build, so it isn't a good solution overall.

This problem started occurring at roughly the time I installed Preview 9/RC 2 of .NET Core 3. Thanks for looking into this for me!

**Comment by livarcocc** [comment]
Can you share what your project looks like? How did you acquire that preview 9/rc 2 build?

What build do you have exactly?

**Comment by wjk** [comment]
A sample csproj that reproduces the problem is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>

    <AssemblyName>Sunburst.SharingManager</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <AssemblyTitle>Sunburst Sharing Manager</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PresentationTheme.Aero" Version="0.5.0" />
  </ItemGroup>
</Project>
```

And my `dotnet --info` output is this:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc1-014185
 Commit:    23643eeb2c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-rc1-014185\

Host (useful for support):
  Version: 3.0.0-rc1-19455-02
  Commit:  caa8d3b1ed

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014185 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19453.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19455-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19455-02 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I installed this build using the links in the core-sdk README file. Thanks!

**Comment by livarcocc** [comment]
Because this is a nightly build, you need to add package feeds to be able to find packages. runtime packs do not ship with the SDK and are not available offline.

You can find the feeds listed in the readme of the core-sdk repo before the download links.

Can you give that a try and let us know how it goes?

**Comment by wjk** [comment]
@livarcocc Works great. I'm going to close this issue now. Thanks so much!
