### ISSUE TITLE
dotnet ef cannot find sdk on Ubuntu 23.04 

### ISSUE THREAD

**Issue by wgrs** [dotnet/sdk#36380]
I am struggling to get dotnet ef tool to work. It has been installed globally, but it cannot find the sdk. Is this a PATH issue? What must be added to PATH?

```C#
dotnet tool install --global dotnet-ef

dotnet ef
You must install .NET to run this application.

dotnet --version
7.0.112

whereis dotnet
dotnet: /usr/bin/dotnet /usr/lib/dotnet /etc/dotnet /usr/share/man/man1/dotnet.1.gz

export PATH=$PATH:$HOME/.dotnet/tools

```

I have done a complete removal of .Net 7.0.12 SDK  files on my system and re-installed using apt. 
I removed the ef core tools and re-installed. The result is the same. EF Core tools do not see the SDK

**Comment by ajcvickers** [comment]
Transferring, since there is nothing specific here to the EF tool.

**Comment by dusda** [comment]
Is there a workaround for this?

**Comment by wgrs** [comment]
Upgraded to 8
