### ISSUE TITLE
Duplicated dependency via project reference and nuget leads to GenerateDepsFile crash

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#364]
**Repro steps**
* Have a PackageReference to Foo.nupkg
* Also have a ProjectReference to Foo.csproj producing the same dll as nupkg

**Expected behavior**
* Project reference wins and build succeeds

**Actual behavior**
* Package reference wins for compilation input, GenerateDepsFile throws and aborts build.

**Comment by nguerrera** [comment]
Workaround:

``` XML
  <Target Name="WorkAroundPackageAndProjectReferenceConflict" 
                BeforeTargets="ResolveLockFileReferences">
    <ItemGroup>
       <ResolvedCompileFileDefinitions 
           Remove="@(ResolvedCompileFileDefinitions)" 
           Condition="'%(ResolvedCompileFileDefinitions.Filename)' == 'Foo'" />
    </ItemGroup>
  </Target>
```

**Comment by mattwar** [comment]
I'm not able to repro this crash in the current VS build d15rel 26129.0.  It is actually working as expected.  No exception, no crash.
