### ISSUE TITLE
Warn on publishing solutions / path forward for publishing solutions

### ISSUE THREAD

**Issue by dasMulli** [dotnet/sdk#3650]
There are many issues with doing a publish on solution files.

I suggest emitting a Warning when trying to do so. I think this may be possible through solution extension points.

so `dotnet publish the.sln` would emit something like `NETSDK999: Publishing whole solutions can lead to unintended side-effects`.
This could then be disabled with `dotnet publish the.sln -p:WarnOnPublishingSolutions=False`.

While there are suggestions of allowing base paths for solution publishing to create folders for each project are possible, it has a few edge cases (same csproj names in different solution folders etc.).

**Comment by rainersigwald** [comment]
dotnet/sdk#863 is related (and maybe sufficient?).

**Comment by dasMulli** [comment]
It's one of the things that can go wrong. Another thing would be dependency trimming of things that ship in both Nuget packages and shared frameworks. If I have a library referencing e.g. Microsoft.Extensions.DependencyInjection and reference that from an asp.net core app, the app will not have the DLL in its output dir but if I publish the solution, the library publish output does have the DLL so the mixed output will have it and users could miss security patches if they deployed it.

**Comment by baronfel** [comment]
Closing as this was fixed with #29065
