### ISSUE TITLE
Reenable Helix perf on 3.0.1xx 

### ISSUE THREAD

**Issue by mmitche** [dotnet/sdk#3655]
Re-enable helix perf on 3.0.1xx. Removed at: https://github.com/dotnet/sdk/pull/3654

**Comment by nguerrera** [comment]
@livarcocc

**Comment by nguerrera** [comment]
@johnbeisner

**Comment by livarcocc** [comment]
Yes. Revert. This was done just to speed up our builds at 2 in the morning. Though, I would probably like to find a way for these to run out of band. No reason to hold the official build on these.

**Comment by nguerrera** [comment]
> Though, I would probably like to find a way for these to run out of band. No reason to hold the official build on these.

Agreed.

**Comment by wli3** [comment]
helix perf tests are no longer needed. We run perf tests in perf lab now
