### ISSUE TITLE
Reenable CanRunDsicoveryTool test after rc2 runtime codeflow from templating

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#36587]
https://github.com/dotnet/templating/pull/7223

**Comment by MiYanni** [comment]
This test seems to be enabled in both the SDK and Templating repo.
- https://github.com/dotnet/sdk/blob/de4f12b8ab6692b01776d362f4fa609fd3f1154a/test/dotnet-new.Tests/TemplateDiscoveryTests.cs#L20
- https://github.com/dotnet/templating/blob/975effdbb5f18d37b2151c7002ee2a8c9853af0a/test/Microsoft.TemplateSearch.TemplateDiscovery.IntegrationTests/TemplateDiscoveryTests.cs#L23
