### ISSUE TITLE
SDK 3.0 RC1 installer doesn't uninstall 3.0 preview 7

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/sdk#3659]
As I understand it, .NET Core 3 SDK installer is supposed to uninstall previous versions.
However, I had preview7 and just installed RC1, and preview7 wasn't removed:

```
> dotnet --info
...
    .NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
```

Is this expected?

Also, preview7 no longer appears in "Apps and features", so I'm not sure how to remove it...

**Comment by johnbeisner** [comment]
@thomaslevesque 
Do you have Visual Studio installed? It is entirely possible that the preview 7 SDK is installed and managed by VS.

**Comment by thomaslevesque** [comment]
Ah, maybe that's it.
However, I had a VS Preview installed, but uninstalling it didn't removed the preview7 SDK

**Comment by johnbeisner** [comment]
@joeloff 
Can you assist @thomaslevesque in removing the left-behind preview7 SDK

**Comment by joeloff** [comment]
The simplest thing to pull the installers from the registry.

1. Open regedit
2. Expand HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall
3. Search for "preview7", "preview-7" and "preview 7". Some installers have used different naming conventions
4. If you find an entry that looks like it's .NET Core related, grab the UninstallString value, it should be something like "msiexec /X {GUID}".
5. Copy those commands out and then add IGNOREDEPENDENCIES=ALL to each string and run them from an elevated command prompt.
6. If you have both x86 and x64 installed, make sure to also search the 32-bit hive under HKLM\SOFTWARE\Wow3264Node\Microsoft\Windows\CurrentVersion\Uninstall

**Comment by thomaslevesque** [comment]
Thanks @joeloff!

I was able to uninstall all the components. One of them had an incorrect UninstallString:

    MsiExec.exe /I{1A9C4CE3-DA05-4969-AA9F-FA372306713A}

Replacing `/I` with `/X` did the trick, though
