### ISSUE TITLE
No frameworks were found but actually installed 

### ISSUE THREAD

**Issue by li-zheng-hao** [dotnet/sdk#36594]
### Describe the bug
I build my asp.net core webapi project with .net 7 on Machine A , and copy output files to Machine B . 

when i run this application on MachineB, it gives me this error:

![image](https://github.com/dotnet/sdk/assets/22129824/55232c2d-51f3-4629-adc3-563491472b43)

you can see that .net 7 sdk is installed ,but when i run this app, it seems cannot found the correct path of .net sdk

### To Reproduce

1.  use machine A (Windows 10) with these .net sdks/ runtimes

![image](https://github.com/dotnet/sdk/assets/22129824/02e9af48-fa4c-4d46-8ff2-cb5de8df682a)

2. run command `dotnet build [ProjectName].csproj --configuration release` to build the project
3. copy the output files to MachineB (Windows 10)
4. run command `[ProjectName].exe` 

> maybe it's hard to reproduce, this problem is really weird

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

dotnet --info on MachineA:

![image](https://github.com/dotnet/sdk/assets/22129824/0940e36f-70ec-4f16-bef5-cd8cc11dea0b)

dotnet --info on MachineB:

![image](https://github.com/dotnet/sdk/assets/22129824/8e3001ca-c6f9-40c1-814d-dfc29e3208f3)

**Comment by vitek-karas** [comment]
Can you please try host tracing? https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#corehost_trace

The detailed trace should list the locations it looked and why it rejected whatever it found there.

If you want to share the trace, please be aware that the trace contains information about machine you run it on.

**Comment by li-zheng-hao** [comment]
> Can you please try host tracing? https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#corehost_trace
> 
> The detailed trace should list the locations it looked and why it rejected whatever it found there.
> 
> If you want to share the trace, please be aware that the trace contains information about machine you run it on.

i tried this , and here is trace log:

```
Tracing enabled @ Thu Nov  2 00:35:11 2023 GMT
--- Invoked apphost [version: 7.0.12, commit hash: 4a824ef37caa51072221584c64cbf15455f406ca] main = {
FB.AppSrv.exe
}
Redirecting errors to custom writer.
The managed DLL bound to this executable is: 'FB.AppSrv.dll'
Resolved fxr [D:\EnterpriseQuoting\Demo\hostfxr.dll]...
Loaded library from D:\EnterpriseQuoting\Demo\hostfxr.dll
Invoking fx resolver [D:\EnterpriseQuoting\Demo\hostfxr.dll] hostfxr_main_startupinfo
Host path: [D:\EnterpriseQuoting\Demo\FB.AppSrv.exe]
Dotnet path: [D:\EnterpriseQuoting\Demo\]
App path: [D:\EnterpriseQuoting\Demo\FB.AppSrv.dll]
Tracing enabled @ Thu Nov  2 00:35:11 2023 GMT
--- Invoked hostfxr_main_startupinfo [commit hash: 4a824ef37caa51072221584c64cbf15455f406ca]
Checking if CoreCLR path exists=[D:\EnterpriseQuoting\Demo\coreclr.dll]
Detecting mode... CoreCLR present in dotnet root [D:\EnterpriseQuoting\Demo\] and checking if [FB.AppSrv.deps.json] file present=[1]
--- Executing in a native executable mode...
Using dotnet root path [D:\EnterpriseQuoting\Demo\]
App runtimeconfig.json from [D:\EnterpriseQuoting\Demo\FB.AppSrv.dll]
Runtime config is cfg=D:\EnterpriseQuoting\Demo\FB.AppSrv.runtimeconfig.json dev=D:\EnterpriseQuoting\Demo\FB.AppSrv.runtimeconfig.dev.json
Attempting to read runtime config: D:\EnterpriseQuoting\Demo\FB.AppSrv.runtimeconfig.json
Attempting to read dev runtime config: D:\EnterpriseQuoting\Demo\FB.AppSrv.runtimeconfig.dev.json
Runtime config [D:\EnterpriseQuoting\Demo\FB.AppSrv.runtimeconfig.json] is valid=[1]
--- The specified framework 'Microsoft.NETCore.App', version '7.0.0', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '7.0.0'.
--- Resolving FX directory, name 'Microsoft.NETCore.App' version '7.0.0'
Searching FX directory in [D:\EnterpriseQuoting\Demo]
Attempting FX roll forward starting from version='[7.0.0]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=1
'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release greater than or equal version to [7.0.0]
No match greater than or equal to [7.0.0] found.
'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release/pre-release greater than or equal version to [7.0.0]
No match greater than or equal to [7.0.0] found.
Framework reference didn't resolve to any available version.
It was not possible to find any compatible framework version
You must install or update .NET to run this application.

App: D:\EnterpriseQuoting\Demo\FB.AppSrv.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: D:\EnterpriseQuoting\Demo\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=win10-x64
```

**Comment by li-zheng-hao** [comment]
here is `FB.AppSrv.runtimeconfig.json` :

```json
{
  "runtimeOptions": {
    "tfm": "net7.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "7.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "7.0.0"
      }
    ],
    "configProperties": {
      "System.GC.Server": true,
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Reflection.NullabilityInfoContext.IsSupported": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

**Comment by li-zheng-hao** [comment]
I noticed a detail: there was no environment variable `DOTNET_ROOT` on MachineA. After I added this environment variable, recompiled the program (`dotnet build -c Release`), and copied the compiled files to MachineB, it was able to run properly.

Is there any magic involved in this?  or maybe i should use `dotnet publish` rather than `dotnet build -c Relase`

**Comment by vitek-karas** [comment]
Setting `DOTNET_ROOT` on the machine where you build it should not make a difference. 

In general, the output of `dotnet build` is meant to run on the "local machine". If you want to deploy the app to a different machine you should use `dotnet publish`. For simple things it will work either way, but there are differences and depending on the configuration they may be important.

I assume the value of `DOTNET_ROOT` on machine B is set to `D:\EnterpriseQuoting\Demo\`. But based on the other stuff in the log, that's also where the application is located. That is pretty weird. `DOTNET_ROOT` should be used if you have a private install of the runtime (so typically just from a zip). If you want the app to use globally installed runtime (from a real installer), you should not set it. If your app is self-contained, then you should not set it either.

Based on the `.runtimeconfig.json` your app is not self-contained, but then it finds CoreCLR right next to the app - this is really weird. Did you build the app as self-contained at one point, then changed that and build "incrementally" as non-self-contained? The SDK may sometime not correctly cleanup everything on incremental builds for changes like this. I would try cleaning the `obj` and `bin` directories, and build again. If you're building as framework dependent (not self-contained), then you should not have `coreclr.dll` in the same directory as your app. If you do, something is broken or misconfigured.

**Comment by li-zheng-hao** [comment]
thanks , I think I need to test if the cause of the problem is `self-contained`
