### ISSUE TITLE
dotnet watch doesn't respect configuration arg

### ISSUE THREAD

**Issue by Santas** [dotnet/sdk#36611]
### Describe the bug
When using dotnet watch, the build doesn't respect the `configuration` argument. This worked in .NET 7.

### To Reproduce
$ dotnet watch run -- -c **_abc_**
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
...
Website -> /Users/[redacted]/Website/bin/**_Debug_**/net7.0/Website.dll
dotnet watch 🚀 Started
...

### Further technical details
```
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/
```

**Comment by bjarketrux** [comment]
Any workaround for this. Right now we have to run out project with `dotnet run` instead of `watch` which is not ideal...
