### ISSUE TITLE
NuGet Package can't find "latest" version

### ISSUE THREAD

**Issue by jsquire** [dotnet/sdk#36637]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#39716](https://github.com/Azure/azure-sdk-for-net/issues/39716).

### Library name and version

Azure.AI.OpenAI 1.0.0-beta.8

### Describe the bug

About 2 days ago something changed so that when running:

dotnet list package --outdated

on a project that contains any package reference to the OpenAI nuget (I've tried all betas at this point):

    <PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.8" />

you get the following "not found at the sources" error:

```console
Project `xxx` has the following updates to its packages
   [net7.0]: 
   Top-level Package      Requested      Resolved       Latest                  
   > Azure.AI.OpenAI      1.0.0-beta.8   1.0.0-beta.8   Not found at the sources
```

### Expected behavior

Since 1.0.0-beta.8  is the latest version, I would expect nothing to come back from :

dotnet list package --outdated

for this package.

### Actual behavior

```console
Project `xxx` has the following updates to its packages
   [net7.0]: 
   Top-level Package      Requested      Resolved       Latest                  
   > Azure.AI.OpenAI      1.0.0-beta.8   1.0.0-beta.8   Not found at the sources
```

### Reproduction Steps

create a sample project with this project reference:

<PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.8" />

and then run:

dotnet list package --outdated

### Environment

all MacOS command line, tried with 7.x .net sdk's, most recently tried with latest 8.x .net sdk:

dotnet --info
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: arm64
  Commit:       0b25e38ad3

.NET SDKs installed:
  7.0.100-rc.2.22477.23 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  7.0.305 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]
  7.0.401 [/usr/local/share/dotnet/sdk]
  7.0.402 [/usr/local/share/dotnet/sdk]
  7.0.403 [/usr/local/share/dotnet/sdk]
  8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Forgind** [comment]
@jaz2038

Are you only seeing this issue on macOS? I tried:
dotnet new console
<added the package reference you mentioned>
dotnet list package --outdated

And it had output more like this:
```
The following sources were used:
   https://api.nuget.org/v3/index.json

The given project `36637` has no updates given the current sources.
```

I tried it on windows and in wsl and got the same result. (I don't have a mac, unfortunately; though I can spin up a VM, I wanted to check if I was doing something wrong first.)

Thanks!

**Comment by jaz2038** [comment]
@Forgind I tried on windows and see same result as you - so seems macOS specific.  I tried updating to newer nuget for that package but still getting same:

   [net7.0]: 
   Top-level Package      Requested      Resolved       Latest                  
   > Azure.AI.OpenAI      1.0.0-beta.9   1.0.0-beta.9   Not found at the sources

whereas other projects with no updates get:

The given project `xxxx` has no updates given the current sources.

some mix of macOS and a beta package version?

**Comment by Forgind** [comment]
@baronfel, you mentioned having a mac; let me know what you think here.

**Comment by jaz2038** [comment]
@baronfel @Forgind any updates on this one - seeing same with latest Azure.AI.OpenAI 1.0.0-beta.12

**Comment by baronfel** [comment]
I haven't made time to try and repro on my mac - I'll try and get to it soon.

**Comment by baronfel** [comment]
Oh, I repro'd this easily, but the key thing here is that `list package` is provided by the NuGet team and merely surfaced in the .NET CLI in this repo. Sorry for the delay in actually looking at this and making that determination. I'll add the NuGet label to signal this.
