### ISSUE TITLE
[NETSDKE2E][VS64][Unstable][Regression]"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..."  error happens during publish project in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#36643]
Affected Branch: D17.7
17.7.7:[ Pipelines - Run rel.d17.7-34302.85 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D8632531%26view%3Dresults&data=05%7C01%7Cv-danche%40microsoft.com%7C00e415c4eaaf44df077e08dbdbf19b33%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638345603292588788%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bde5r8lsZVnrojQVr4eMBaR2Kyn241GuK2t5njkwXYk%3D&reserved=0)

Repro steps:
1.in CLI, dotnet new console
2.dotnet publish -r win-x86 or dotnet publish -r win-x64

**Expected Result:**
publish successfully.

**Actual Result**
publish successfully but, some exception display during publishing.

![image](https://github.com/dotnet/sdk/assets/65637796/2fc395cc-71e1-4254-a0c0-911b80505139)

dotnet --info:
![image](https://github.com/dotnet/sdk/assets/65637796/38e410ed-c6a6-49b8-bc30-96f35abb867b)

**Comment by vdanche** [comment]
we also met it in today's 17.2/17.4/17.6 and 17.8 preview 7 sign-off build, we did not met it on VAL build.
E.g. on 17.8 preview 7 as below
![image](https://github.com/dotnet/sdk/assets/65637796/233ac001-d3c9-4526-93e7-26157e7cbbb3)

**Comment by vdanche** [comment]
we also meet it when adding a Nuget package in VS.
![image](https://github.com/dotnet/sdk/assets/65637796/52ce46f1-e5ad-4998-a4c1-aba76b8e012a)

**Comment by ChenhuiYuan01** [comment]
This issue also repro's on Linux.
![Screenshot 2023-11-03 163953](https://github.com/dotnet/sdk/assets/92560562/3fd85c88-e16e-40b3-97ee-f9a667dea4cb)

**Comment by marcpopMSFT** [comment]
@aortiz-msft @nkolev92 @JonDouglas From the error, that looks like a network error during nuget download from nuget.org. Do you know if there was a nuget.org outage last night maybe that would explain this?

**Comment by vdanche** [comment]
The same error displays when installing the workload for the first time, try to installing workload again, it will succeed.
![image](https://github.com/dotnet/sdk/assets/65637796/592f478b-0e34-49e0-af17-86c420c9431d)
![image](https://github.com/dotnet/sdk/assets/65637796/9fa2c05c-7fff-473b-94be-ec1403c7f785)

**Comment by vdanche** [comment]
today we did not met this issue now. this issue should be fixed now
