### ISSUE TITLE
Unable to find a stable package Microsoft.TemplateEngine.Authoring.Tasks with version (>= 8.0.100)

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#36659]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=458966
Build error leg or test failing: Build / Windows_NT / Windows_NT Build_Release / Build
Pull request: https://github.com/dotnet/sdk/pull/36639

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to find a stable package Microsoft.TemplateEngine.Authoring.Tasks with version (>= 8.0.100)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=458966
**Error message validated:** `Unable to find a stable package Microsoft.TemplateEngine.Authoring.Tasks with version (>= 8.0.100)`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/4/2023 11:50:09 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[461417](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461417)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461417/logs/136)|dotnet/sdk#36623|
|[461407](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461407)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461407/logs/139)|dotnet/sdk#36635|
|[461398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461398)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461398/logs/145)|dotnet/sdk#36623|
|[461361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461361)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461361/logs/144)|dotnet/sdk#36633|
|[461308](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461308)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461308/logs/127)|dotnet/sdk#36634|
|[461293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461293)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461293/logs/122)|dotnet/sdk#36624|
|[461256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461256)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461256/logs/145)|dotnet/sdk#36633|
|[461220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461220)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461220/logs/145)|dotnet/sdk#36635|
|[461215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461215)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461215/logs/146)|dotnet/sdk#36624|
|[461151](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461151)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461151/logs/127)|dotnet/sdk#36634|
|[461097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461097)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461097/logs/145)|dotnet/sdk#36631|
|[461092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461092)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461092/logs/145)|dotnet/sdk#36634|
|[461061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461061)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461061/logs/259)|dotnet/sdk#36635|
|[461019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461019)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/461019/logs/129)|dotnet/sdk#36634|
|[460805](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460805)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460805/logs/146)|dotnet/sdk#36644|
|[460814](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460814)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460814/logs/129)|dotnet/sdk#36662|
|[460788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460788)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460788/logs/145)|dotnet/sdk#36626|
|[460785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460785)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460785/logs/145)|dotnet/sdk#36625|
|[460750](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460750)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460750/logs/145)|dotnet/sdk#36624|
|[460636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460636)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460636/logs/137)|dotnet/sdk#36623|
|[460635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460635)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460635/logs/142)|dotnet/sdk#36635|
|[460527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460527)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460527/logs/145)|dotnet/sdk#36635|
|[460479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460479)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460479/logs/131)|dotnet/sdk#36623|
|[460396](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460396)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460396/logs/127)|dotnet/sdk#36635|
|[460310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460310)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460310/logs/127)|dotnet/sdk#36644|
|[460305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460305)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460305/logs/127)|dotnet/sdk#36626|
|[460304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460304)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460304/logs/127)|dotnet/sdk#36625|
|[460288](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460288)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460288/logs/136)|dotnet/sdk#36624|
|[460201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460201)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460201/logs/145)|dotnet/sdk#36635|
|[460181](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460181)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460181/logs/131)|dotnet/sdk#36635|
|[460153](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460153)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460153/logs/145)|dotnet/sdk#36635|
|[460150](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460150)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460150/logs/145)|dotnet/sdk#36633|
|[460146](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460146)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460146/logs/145)|dotnet/sdk#36633|
|[460068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460068)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460068/logs/139)|dotnet/sdk#36631|
|[460067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460067)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460067/logs/145)|dotnet/sdk#36632|
|[460056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460056)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460056/logs/145)|dotnet/sdk#36631|
|[460020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460020)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460020/logs/127)|dotnet/sdk#36644|
|[460013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460013)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460013/logs/130)|dotnet/sdk#36626|
|[460010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460010)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/460010/logs/138)|dotnet/sdk#36625|
|[459993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459993)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459993/logs/145)|dotnet/sdk#36624|
|[459917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459917)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459917/logs/139)|dotnet/sdk#36623|
|[459911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459911)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459911/logs/145)|dotnet/sdk#36633|
|[459870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459870)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459870/logs/145)|dotnet/sdk#36623|
|[459864](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459864)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459864/logs/142)|dotnet/sdk#36631|
|[459858](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459858)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459858/logs/136)|dotnet/sdk#36633|
|[459836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459836)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459836/logs/145)|dotnet/sdk#36623|
|[459816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459816)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/459816/logs/145)|dotnet/sdk#36633|
|[458966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=458966)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/458966/logs/127)|dotnet/sdk#36639|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|48|48|

**Comment by lewing** [comment]
All the flow is broken because of this issue @dotnet/domestic-cat

**Comment by lewing** [comment]
The dependency made it into main wit https://github.com/dotnet/sdk/pull/36567 but it looks like a transitive dependency on a stable package version which should not be happening at all in main.

**Comment by marcpopMSFT** [comment]
fixed in arcade so teams will need no flows.
