### ISSUE TITLE
Upgrading to 8.0.0-rc.2.9511 breaks the app. Loses references to MauiUIApplicationDelegate

### ISSUE THREAD

**Issue by fady-intelligencex** [dotnet/sdk#36667]
### Description

Once I upgraded to 8.0.0-rc.2.9511, the app stopped building with the Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) (CS0246). To validate, I created a new project. It works fine with the a previous version, but once I upgrade, it has the same problem.

### Steps to Reproduce

1. Create new project in maui .net 8.0
2. Run the project
3. Update Microsoft.Maui.Controls to 8.0.0-rc-2.9511
4. Attempt to run project
5. see error in the build output.

under Platforms/iOS/ in the file AppDelegate.cs 

using Foundation;

namespace newtest4;

[Register("AppDelegate")]
public class AppDelegate : MauiUIApplicationDelegate
{
	protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
}

It cannot find: MauiUIApplicationDelegate

I shared a video link where I demo it happening on a new project.

### Link to public reproduction project repository

https://youtu.be/aBUKjdeMXz8

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

iOS

### Did you find any workaround?

N/A

### Relevant log output

```shell
Projects/newtest4/newtest4/Platforms/iOS/AppDelegate.cs(28,28): Error CS0246: The type or namespace name 'MauiUIApplicationDelegate' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (newtest4)
```

**Comment by DDHSchmidt** [comment]
Discord advised me to provide a binlog.
Here is the 
result of `dotnet build VanillaMauiApp.sln /bl:msbuild.binlog` : [msbuild.binlog.zip](https://github.com/dotnet/sdk/files/13268888/msbuild.binlog.zip)
I also provide the sources of the vanilla app I used to trigger the faulty result: 
[VanillaMauiApp.zip](https://github.com/dotnet/sdk/files/13268906/VanillaMauiApp.zip)

**Comment by AndreasBreuninger** [comment]
> > I had the same issue actually, so I have done the following steps to fix it:
> > 
> > 1. run `dotnet workload update`
> > 2. It should update your workloads to the latest workloads that the 8.0.0-RC.2.9511 uses.
> > 3. Close VS and reopen it again then you should see your issue is fixed.
> > 
> > I actually use the latest SDK RC2 8 Core (8.0.100-rc.2.23502.2) https://dotnet.microsoft.com/en-us/download/dotnet/8.0
> 
> I have the same problem as the original poster and this did **not** fix my problem.
> 
> dotnet --list-runtimes contains `Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]`
> 
> dotnet --list-sdks contains `8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]`
> 
> dotnet workload list displays:
> 
> ```
> Installed Workload Id      Manifest Version                     Installation Source
> -----------------------------------------------------------------------------------
> maui-ios                   8.0.0-rc.1.9171/8.0.100-rc.1         SDK 8.0.100-rc.2   
> ios                        16.4.8825-net8-rc1/8.0.100-rc.1      SDK 8.0.100-rc.2   
> maui                       8.0.0-rc.1.9171/8.0.100-rc.1         SDK 8.0.100-rc.2
> ```
> 
> This is _after_ I ran `sudo dotnet workload update --include-previews`
> 
> I'm using Visual Studio for Mac 17.6.6 with XCode 15.0.1
> 
> If you need more advice, don't hesitate too ask **quickly**. I'm deeply concerned about this dependency mixup in an addendum to a Release Candidate this close before GA :(

Had the same issue. For me it was fixed with these steps:

1. dotnet workload update 
2. Close Visual Studio
3. Delete bin and obj folder

**Comment by Forgind** [comment]
This issue was moved to dotnet/maui#18739

**Comment by Forgind** [comment]
Since updating all workloads outside VS for Mac was one resolution that worked, this seems like an issue with different version of workloads not cooperating with each other properly. Since those are all owned by MAUI, moving this to them.
