### ISSUE TITLE
[Bug]: Error when using MSBuild.exe to publish a .NET 6.0 C# project for Windows and Linux x64 with /p:NoBuild=true

### ISSUE THREAD

**Issue by mbalous** [dotnet/sdk#36693]
### Issue Description

I have a plain .csproj C# project targeting .NET 6.0, and I'm trying to streamline the process of building and publishing it for both win-x64 and linux-x64 runtimes. To avoid building the project twice, I'm using MSBuild.exe with the /p:NoBuild=true flag. However, I'm encountering the following error:

`
C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(296,5): error MSB3030: Could not copy the file C:\Users\john.doe\source\repos\ConsoleApp9\ConsoleApp9\obj\x64\Release\apphost" because it was not found.
`

Here are the commands I'm using:

1. First, I run a regular build command:  `dotnet build -c Release`
2. Then, I attempt to publish the project for `win-x64` using MSBuild.exe with `/p:NoBuild=true`: 
```
MSBuild.exe ConsoleApp9.csproj /p:Platform=x64 /p:TargetFramework=net6.0 /p:Configuration=Release /t:publish /p:NoBuild=true /p:RuntimeIdentifier=win-x64
```
3. Finally, I run the same `MSBuild.exe` command again for `linux-x64`, but it fails with the error mentioned above. I noticed that the apphost file is not being generated in the obj directory during the build process for the `linux-x64` target, whereas `apphost.exe` is generated for Windows. <br> How can I resolve this error and successfully publish my project for both `win-x64` and `linux-x64` runtimes using MSBuild.exe with the `/p:NoBuild=true` option while ensuring that apphost is generated for the `linux-x64` target during the build process?
```
MSBuild.exe ConsoleApp9.csproj /p:Platform=x64 /p:TargetFramework=net6.0 /p:Configuration=Release /t:publish /p:NoBuild=true /p:RuntimeIdentifier=linux-x64
```

I believe this should be possible, because Visual Studio can already do this (see at the bottom, it says 1 project up-to-date):

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/PPWaU.png

<hr/>
side note: I need to use `msbuild.exe` instead of `dotnet publish`, because I reference a C++/CLI project.

### Steps to Reproduce

Reproducible sample: https://gist.github.com/mbalous/8f0b3108da60b4d4176bf7ec3fb4b108

Create a project directory, place contents inside and run `build.bat`

### Expected Behavior

apphost is created and no errors are present

### Actual Behavior

Error is present:
`C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(296,5): error MSB3030: Could not copy the file C:\Users\john.doe\source\repos\ConsoleApp9\ConsoleApp9\obj\x64\Release\apphost" because it was not found.`

### Analysis

I can mitigate this problem by using
`msbuild.exe /t:ResolveFrameworkReferences;_CreateAppHost;publish`

but then I ran into problems with broken `.deps.json` file.

### Versions & Configurations

```
PS C:\Users\mb\source\repos> msbuild.exe -version
MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605
```

**Comment by YuliiaKovalova** [comment]
Triage: based on missed apphost file, it sounds like an sdk issue.

**Comment by hilari0n** [comment]
The issue might be (just a speculation) that the build you are doing the publish for, is not targeted at a specific runtime (or runtimes), so the build result is not complete enough to satisfy the publish operation targeted at it/them (e.g. `ResolveFrameworkReferences` did not have specific runtime information) and by stating that publish can't build, it can't address this.
You could try adding this to your `*.csproj` file to inform the build process about the target runtime(s):
```xml
  <PropertyGroup>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
```

PS.: Is there a reason why you are using `msbuild.exe` instead of `dotnet.exe`? E.g.:
```bat
dotnet publish ConsoleApp9.csproj --framework net6.0 --configuration Release --no-build --runtime win-x64 --no-self-contained
```

**Comment by mbalous** [comment]
> PS.: Is there a reason why you are using msbuild.exe instead of dotnet.exe? E.g.:

@hilari0n:  I'm mentioning that at the start:
> side note: I need to use `msbuild.exe` instead of `dotnet publish`, because I reference a C++/CLI project.

**Comment by hilari0n** [comment]
> > PS.: Is there a reason why you are using msbuild.exe instead of dotnet.exe? E.g.:
> 
> @hilari0n: I'm mentioning that at the start:
> 
> > side note: I need to use `msbuild.exe` instead of `dotnet publish`, because I reference a C++/CLI project.

Thanks and sorry for missing it in the first place!

**Comment by mbalous** [comment]
Any updates here? Thank you!

**Comment by marcpopMSFT** [comment]
Triage: There is not automatic multi-targeting support for RuntimeIdentifiers today so this scenario is not supported. We are discussing ways to enable this in the future through TargetFramework aliasing but today, there is no way to do a build for multiple OSes in a single command. Instead you have to build for each and then publish for each.
