### ISSUE TITLE
Microsoft.NET.Sdk imports CustomBeforeDirectoryBuildProps after DirectoryBuildPropsPath

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#36749]
`Microsoft.Common.props` (from dotnet/msbuild) has these imports surrounding `DirectoryBuildPropsPath`:

```xml
  <Import Project="$(CustomBeforeDirectoryBuildProps)" Condition="'$(CustomBeforeDirectoryBuildProps)' != ''" />

  <Import Project="$(DirectoryBuildPropsPath)" Condition="'$(ImportDirectoryBuildProps)' == 'true' and exists('$(DirectoryBuildPropsPath)')"/>

  <Import Project="$(CustomAfterDirectoryBuildProps)" Condition="'$(CustomAfterDirectoryBuildProps)' != ''" />
```

`Sdk.props` handles `DirectoryBuildPropsPath` early:

https://github.com/dotnet/sdk/blob/82444e07cf1727fa9bf2785e7c866cedc6b84058/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props#L54-L58

This doesn't consider `CustomBeforeDirectoryBuildProps`, which causes `DirectoryBuildPropsPath` to get imported before `CustomBeforeDirectoryBuildProps`.

cc @dsplaisted

**Comment by dsplaisted** [comment]
We [added those custom properties](https://github.com/dotnet/msbuild/pull/8877) as a hook for the SDK to use (so the SDK itself wouldn't have to dupicate the Directory.Build.props import logic), but never updated the SDK itself to take advantage of the hook.

@forgind, would you be able to take a look at this sometime?

FYI @marcpopMSFT

**Comment by Forgind** [comment]
Good catch @tmds. I can make a PR into MSBuild to add the same logic around that location.

**Comment by Forgind** [comment]
https://github.com/dotnet/sdk/pull/36777
