### ISSUE TITLE
How can I replicate a VS "Publish" operation in the command line, when COM components are involved

### ISSUE THREAD

**Issue by joedemax** [dotnet/sdk#36778]
I have create a simple WinForms .NET 7 project that includes a few COM+ dependencies. I wish to publish it to a self contained, single file. I can do this no problem when I utilise the Publish option in Visual Studio. However, this is not at all convinient for the publish process. I need to be able to run this from the command line.

Using dotnet publish is not an option, because it does not support COM references. How might I find out exactly the parameters that Visual Studio passes to MsBuild when I click Publish? I have already looking at the command line flags and found nothing of real interest.

`/nologo /nodemode:1 /nodeReuse:true /low:false
`

**Comment by mbalous** [comment]
You have to use binary logs from msbuild to see that.

https://github.com/dotnet/project-system-tools#getting-higher-fidelity-logs-from-vs-vs2022-onwards

Afterwards use _MSBuild Structured Log Viewer_ to view the logs.

**Comment by Forgind** [comment]
You can also get binlogs slightly more easily if you set MSBuildDebugEngine to 1 and MSBUILDDEBUGPATH to a folder you can write to, then open VS from that terminal.

I'd imagine some of this might be easier if you use a developer command prompt, as that will try to recreate an environment similar to that in VS.

I don't think this is an SDK issue. I'll come back to it when I've had a chance to try to figure out how to route it properly.

**Comment by Forgind** [comment]
Apparently we have [documentation](https://learn.microsoft.com/visualstudio/deployment/building-dotnet-clickonce-applications-from-the-command-line) on how to publish from the command line. Hope that helps!
