### ISSUE TITLE
Upgraded projects which compile to NS 2.1, didn't compile, downgrade, now compile fails as well

### ISSUE THREAD

**Issue by taori** [dotnet/sdk#3679]
I was trying to update an application to netcore3 to fix some issues, which spawned other issues (RazorTagHelper requiring some Configuration to operate). To attempt resolve those issues i figured i may try to update the libraries to netstandard 2.1 - that didn't fix it either, so i downgraded my projects back to 2.0.

Oddly enough now those libraries won't compile either even if i clean the solution + delete bin/obj manually.

Fehler: Es wurde versucht, einen numerischen Vergleich für "$(_TargetFrameworkVersionWithoutV)" auszuführen, der zu "**.2.0**" anstatt zu einer Zahl in Bedingung " '$(TargetFrameworkIdentifier)' == '.NETCoreApp' and '$(_TargetFrameworkVersionWithoutV)' < '**2.0**' " ausgewertet wird.  C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.NuGetOfflineCache.targets

**Comment by taori** [comment]
@eerhardt Hello - could you perhaps tell me if this is the right place to report this issue? I'd imagine that is a pretty severe issue who should be affecting everyone who tried to build with rc1?

**Comment by dasMulli** [comment]
Maybe you're hitting an issue because ASP.NET Core now targets netcoreapp3.0 so you can no longer write components in netstandard libraries so you have to change them to netcoreapp3.0 and add a framework reference to ASP.NET Core?

https://stackoverflow.com/questions/57760356/how-do-i-use-asp-net-core-3-0-types-from-a-library-project-for-shared-controller

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

**Comment by taori** [comment]
After a while of trying to get it work by building my solution from scratch i came to the same conclusion. That made me spawn this issue. aspnet/AspNetCore/issues/14499 Feels weird that creating a razorclasslib can spawn different kinds of projects who then cannot be referenced anymore. 

Your answer fixed my problem though essentially. Thanks.

**Comment by livarcocc** [comment]
Closing this issue.

I understanding trying to migrate and then back out of it wasn't great, but this particular question has been addressed. Also, migrating asp.net apps always require special steps and I believe those are documented by the asp.net team.
