### ISSUE TITLE
NETSDK1204 error during dotnet clean on macOS when AoT enabled

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#36960]
### Describe the bug

Running `dotnet clean` as part of the Polly CI fails on macOS when `PublishAot=true` is specified in a project file.

### To Reproduce

Run `build.ps1` on macOS after cloning this commit: https://github.com/App-vNext/Polly/pull/1800/commits/58c807e5ec44fe3ead51c08961706eca3953146

I haven't been able to reproduce this in a simpler project: https://github.com/martincostello/dotnet-8-samples/pull/10

I also don't have access to a macOS computer (I have a Windows laptop), so I can't test this out locally to try and get a more minimal repro.

### Exceptions (if any)

[Workflow error logs](https://github.com/App-vNext/Polly/actions/runs/6880981184/job/18716366049?pr=1800#step:5:44) from https://github.com/App-vNext/Polly/pull/1800:

```
Error: /Users/runner/.dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1204: Ahead-of-time compilation is not supported on the current platform 'osx-x64'. [/Users/runner/work/Polly/Polly/test/Polly.AotTest/Polly.AotTest.csproj]
```

### Further technical details

.NET 8.1.00 SDK running on GitHub Action's `macos-latest` runner.

**Comment by eerhardt** [comment]
FYI- @sbomer @agocke

**Comment by martincostello** [comment]
I'm quite confused because we've updated our SDK to 8.0 and added `net8.0` targets. Did we miss a 7.0 reference somewhere?

**Comment by martincostello** [comment]
Ah. That project was added subsequent to the initial .NET 8 PR being opened so it must have missed our 7.0 find and replace sweep 🤦🏻‍♂️
