### ISSUE TITLE
React template for 8.0 seems to be missing

### ISSUE THREAD

**Issue by codegax** [dotnet/sdk#36969]
### Describe the bug
Trying to create a new project on the new .NET 8 using react template doesn't work

### To Reproduce
`
dotnet new react -f net8.0
`
```
Error: Invalid option(s):
-f net8.0
   'net8.0' is not a valid value for -f. The possible values are:
      net5.0   - Target net5.0
      net6.0   - Target net6.0
      net7.0   - Target net7.0

For more information, run:
   dotnet new react -h

For details on the exit code, refer to https://aka.ms/templating-exit-codes#127
```

But console and webapiaot works fine
`
dotnet new console -f net8.0
`
```
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring **REDACTED**\test8net.csproj:
  Determining projects to restore...
  **REDACTED**\test8net.csproj (in 96 ms).
Restore succeeded.
```

`
dotnet new webapiaot -f net8.0
`
```
The template "ASP.NET Core Web API (native AOT)" was created successfully.

Processing post-creation actions...
Restoring **REDACTED**\test8net.csproj:
  Determining projects to restore...
  **REDACTED**\test8net.csproj (in 4.35 min).
Restore succeeded.
```

### Further technical details
- Running in Windows Terminal using pwsh
`
dotnet --info:
`
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
 [maui-windows]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [maui-maccatalyst]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [maui-ios]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\16.4.8968-net8-rc2\WorkloadManifest.json
   Install Type:              Msi

 [maui-android]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.3.32804.467
   Manifest Version:    34.0.0-rc.2.468/8.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.468\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.317 [C:\Program Files\dotnet\sdk]
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.111 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
cc @danroth27 - I think these were explicitly removed, right?

**Comment by codegax** [comment]
I thought the new reactapp .NET 8.0 template even included Vite.js

**Comment by danroth27** [comment]
@codegax The new templates for Angular, React, and Vue are provided by Visual Studio, so we no longer ship our older SPA templates in the .NET SDK. You can find them in Visual Studio by filtering on JavaScript/TypeScript in the new project dialog. And yes, the new React and Vue templates are based on Vite.

@sayedihashimi

**Comment by mbj79** [comment]
And for people who don't use Visual Studio? Is there any stand-alone template package we can install?

**Comment by codegax** [comment]
Is the issue the 2 separated projects and a solution? Are PR's being accepted to change this?

**Comment by danroth27** [comment]
> Is the issue the 2 separated projects and a solution? Are PR's being accepted to change this?

@mbj79 Currently the new JavaScript templates are only available in Visual Studio. But once they are created you can build and run them cross-platform from the .NET CLI. If you're interested in these templates also being available from the .NET CLI, could you please open a Visual Studio feedback ticket for that?

**Comment by codegax** [comment]
Thanks @danroth27 I open the ticket on [Visual Studio](developercommunity.visualstudio.com) under the category .NET
Here's the [link](https://developercommunity.visualstudio.com/t/NET-8-CLI-Templates-for-React-Angular/10523527) if anybody want to continue the conversation on the feedback platform.

**Comment by agdgb** [comment]
I tried creating `AspNet Core React app using` the visual studio template on `visual studio 2022 version 17.8` but I get `Illegal character in path` error message.
What do I do now?

**Comment by danroth27** [comment]
> I tried creating `AspNet Core React app using` the visual studio template on `visual studio 2022 version 17.8` but I get `Illegal character in path` error message. What do I do now?

@agdgb I recommend opening a Visual Studio feedback ticket for the problem you are seeing: Help > Send Feedback > Report a Problem.

**Comment by Moazzem-Hossain-pixel** [comment]
> ### Describe the bug
> Trying to create a new project on the new .NET 8 using react template doesn't work
> 
> ### To Reproduce
> `dotnet new react -f net8.0`
> 
> ```
> Error: Invalid option(s):
> -f net8.0
>    'net8.0' is not a valid value for -f. The possible values are:
>       net5.0   - Target net5.0
>       net6.0   - Target net6.0
>       net7.0   - Target net7.0
> 
> For more information, run:
>    dotnet new react -h
> 
> For details on the exit code, refer to https://aka.ms/templating-exit-codes#127
> ```
> 
> But console and webapiaot works fine `dotnet new console -f net8.0`
> 
> ```
> The template "Console App" was created successfully.
> 
> Processing post-creation actions...
> Restoring **REDACTED**\test8net.csproj:
>   Determining projects to restore...
>   **REDACTED**\test8net.csproj (in 96 ms).
> Restore succeeded.
> ```
> 
> `dotnet new webapiaot -f net8.0`
> 
> ```
> The template "ASP.NET Core Web API (native AOT)" was created successfully.
> 
> Processing post-creation actions...
> Restoring **REDACTED**\test8net.csproj:
>   Determining projects to restore...
>   **REDACTED**\test8net.csproj (in 4.35 min).
> Restore succeeded.
> ```
> 
> ### Further technical details
> * Running in Windows Terminal using pwsh
>   `dotnet --info:`
> 
> ```
> .NET SDK:
>  Version:           8.0.100
>  Commit:            57efcf1350
>  Workload version:  8.0.100-manifests.6c33ef20
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win-x64
>  Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
> 
> .NET workloads installed:
>  Workload version: 8.0.100-manifests.6c33ef20
>  [maui-windows]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maui-maccatalyst]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maccatalyst]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maccatalyst\16.4.8968-net8-rc2\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maui-ios]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [ios]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    16.4.8968-net8-rc2/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.ios\16.4.8968-net8-rc2\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [maui-android]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    8.0.0-rc.2.9373/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.maui\8.0.0-rc.2.9373\WorkloadManifest.json
>    Install Type:              Msi
> 
>  [android]
>    Installation Source: VS 17.3.32804.467
>    Manifest Version:    34.0.0-rc.2.468/8.0.100-rc.2
>    Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.2\microsoft.net.sdk.android\34.0.0-rc.2.468\WorkloadManifest.json
>    Install Type:              Msi
> 
> 
> Host:
>   Version:      8.0.0
>   Architecture: x64
>   Commit:       5535e31a71
> 
> .NET SDKs installed:
>   5.0.408 [C:\Program Files\dotnet\sdk]
>   6.0.317 [C:\Program Files\dotnet\sdk]
>   6.0.414 [C:\Program Files\dotnet\sdk]
>   7.0.111 [C:\Program Files\dotnet\sdk]
>   7.0.203 [C:\Program Files\dotnet\sdk]
>   7.0.404 [C:\Program Files\dotnet\sdk]
>   8.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
> ```

Need help

**Comment by antoniotavares1985** [comment]
Hi all. So, let me just see if I understand correctly, if we want to create an asp net with react FE, we need either to use Windows and VisualStudio or in other OSs use SDK of dotnet lower than 8 to create the app?

**Comment by flier268** [comment]
I use Rider

**Comment by codegax** [comment]
For anyone still looking for this, here's the response from Hanna Oshlang on the Developer community platform:

> The dotnet new templates for ASP.NET + React / Vue / Angular are now available in a preview release here: https://www.nuget.org/packages/microsoft.javascript.templates/
>
>The current version is “0.1.9-preview”. Once we validate the preview version, we will release an official 1.0 version. If the template doesn’t work for you, please let us know so we can address any issues we missed.
>
>Thank you for your patience, your feedback, and your continued contributions to improving this ecosystem.

So good news! JS Framework templates are **back!**
