### ISSUE TITLE
Make multilanguage project builds

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/sdk#3696]
I propose that dotnet build allows multilanguage .NET projects.

Currently, a .NET project needs to be language exclusive, that is, only F#, or only C#, or only VB.NET.

But, this could change to allow .fs, .cs and .vb files to be compiled together in a same project.

The existing way of approaching this problem in F# is separate F# files in F# projects, C# files in C# projects, and VB.NET files in VB.NET projects.

I originally created a discussion [here](https://github.com/fsharp/fslang-suggestions/issues/788).

**Comment by 0xd4d** [comment]
Try https://github.com/dotnet/ILMerge

**Comment by livarcocc** [comment]
This is not something that we are going to be looking at, so I am going to close this issue for now.
