### ISSUE TITLE
Publish need user to download .NET runtime after upgrading from .NET 7 to 8

### ISSUE THREAD

**Issue by cnSchwarzer** [dotnet/sdk#37005]
### Describe the bug
My ASP.NET 7 project use self contained publish. After upgrading to ASP.NET 8, the self contained app still requires some user (runs on Windows 10) to download the .NET runtime. While the v7 works just fine.

### To Reproduce
Create a ASP.NET project targeting .NET 8 and win-x64, dotnet publish with self contained on. Deploy the publish folder to Windows 10 machine and run the application.

### Exceptions (if any)
My Windows 11 machine occurs this from time to time. But my Windows 10 PC is where it cannot run.

**Comment by vitek-karas** [comment]
What is the error the user gets when running the app?

**Comment by cnSchwarzer** [comment]
> What is the error the user gets when running the app?

I don't recall it well, but I think it is the common dialog that directs users to install .NET Runtime, the message is something like:

.NET 8.0 runtime need to be installed 

View Details

→ Download

**Comment by vitek-karas** [comment]
There are two things which are weird:
* If the app is an ASP.NET service, then it should typically be a console app, in which case it should not produce a dialog. It should just print out the error to the console output.
* If it's really a self-contained app, then getting the "runtime needs to be installed" message is really weird.

I honestly don't know what's wrong here, what would help is capturing a host trace. https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#corehost_trace
(Set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=trace.txt` and run the failing app).
Please note that the trace will contain information like directory names, and environment variables from the machine, so make sure you're OK with sharing it.

**Comment by timheuer** [comment]
> OK, I will try to make a reproducible project.
> 
> About ASP.NET, my project is not a console app because I added the Avalonia as UI framework. So it might also related to that.

If you have a pointer to any similar repro with Avalonia that may help us see what the publish target is actually executing on. Could be the Avalonia shell not being marked self-contained?

**Comment by cnSchwarzer** [comment]
Sorry, it seems an JetBrain Rider bug (2023.3) that even set self-contained in publish task, it will not pass --self-contained.

**Comment by vitek-karas** [comment]
@cnSchwarzer based on the host trace: the host is confused. There's a `coreclr.dll` in the same directory as the app - this is normally used as a sign for a self-contained application. But then the `.runtimeconfig.json` has a framework reference, so it's not self-contained. The failure more here is a bit weird, but you can see the confusion here:
```
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: C:\Users\User\Downloads\???-win\???\action\
```

It's looking for the framework in the app's directory, not in your program files.

This can happen if you changed the publish options and SDK didn't fully clean the output directory for example. I would suggest to delete the output directory and try again. Depending on what you want, you can check that:
* For self-contained, there should be `coreclr.dll` in the app's directory and the `.runtimeconfig.json` should only contained `includedFrameworks` element, and no `framework`/`frameworks` element.
* For framework dependent there should not be `coreclr.dll` and the `.runtimeconfig.json` should contain `frameworks` element.

**Comment by cnSchwarzer** [comment]
Thanks, that should be the reason because I didn't clean the publish directory. I'll try it
