### ISSUE TITLE
dotnet gloabl tool  can not be start after uprade to dotnet sdk 8.0 on Ubuntu(WSL)

### ISSUE THREAD

**Issue by John0King** [dotnet/sdk#37017]
### Describe the bug

1.  locate the dotnet executable 
```
PS /home/std> gcm dotnet

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     dotnet                                             0.0.0.0    /usr/bin/dotnet
```
2. dotnet info 

```
PS /home/std> dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
3. run dotnet global tools
```
PS /home/std> csharprepl
You must install .NET to run this application.

App: /home/std/.dotnet/tools/csharprepl
Architecture: x64
App host version: 8.0.0
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.0
```

I also tried `dotnet-counters` , and it faild with same erro ".Net location: Not found"

### To Reproduce

remove dotnet-sdk-7.0
install dotnet-sdk-8.0

### Exceptions (if any)

dotnet global tool can not find dotnet runtime

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by John0King** [comment]
can anyone verify that  it happend not just my  WSL Ubuntu 22 ?

**Comment by cropland-bv** [comment]
> can anyone verify that it happend not just my WSL Ubuntu 22 ?

Happened here also, but not on WSL Ubuntu. On plain Ubuntu 22.

**Comment by John0King** [comment]
@dsplaisted @marcpopMSFT  any progress on this ?

**Comment by dsplaisted** [comment]
This is probably happening because the tools need .NET 6 or .NET 7, and won't run on .NET 8.  By default .NET tools [do not roll forward to newer major versions of .NET](https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues#runtime-not-found).

CSharpRepl version 0.6.5 targets .NET 7.  There is a 0.6.6 release that targets .NET 8 which should work.  dotnet-counters targets .NET 6.  So you could update to the latest release of CSharpRepl, but you would need to install the .NET 6 runtime for dotnet-counters.

We are working on options to allow rolling forward to newer runtimes when installing tools: https://github.com/dotnet/sdk/issues/30336 and https://github.com/dotnet/sdk/pull/37231

**Comment by John0King** [comment]
@dsplaisted   have you try it , 
this is my tool version 
```
~$ dotnet tool list -g
Package Id           Version         Commands
----------------------------------------------------
csharprepl           0.6.6           csharprepl
dotnet-counters      8.0.452401      dotnet-counters
```

and I can confirm that the dll is running fine 
```
PS /home/<username>/.dotnet/tools/.store/csharprepl/0.6.6/csharprepl/0.6.6/tools/net8.0/any> dotnet ./CSharpRepl.dll
```

**Comment by dsplaisted** [comment]
> the problem is that the tool can not find dotnet runtime not rolling forward issue !!!

I'm not following.  When you uninstall the .NET 7 SDK, that uninstalls the .NET 7 runtime.  So it is expected that the tool would not be able to find the .NET 7 runtime.  You could either reinstall the runtime the tool needs, or we are working on a feature so you can allow the tool to roll forward to a newer runtime if you want.

Does that make sense?

**Comment by John0King** [comment]
I'm confused ,   CSharpRepl 0.6.6  is build on .net 8 
![image](https://github.com/dotnet/sdk/assets/13639146/2c1f0577-3abc-4037-ade1-a6cc0d8ca505)

to provoe that I also install `dotnet-ef`  8.0.0 
![image](https://github.com/dotnet/sdk/assets/13639146/024d73cc-f774-4078-aa9b-af16da67e79b)
