### ISSUE TITLE
Microsoft.VisualStudio.JavaScript.Sdk project is not running as startup project if it resides inside of a solution folder

### ISSUE THREAD

**Issue by hugufc** [dotnet/sdk#37024]
### Describe the bug
Microsoft.VisualStudio.JavaScript.Sdk projects that are located in a solution folder dot not run. 

### To Reproduce
I created this [repo](https://github.com/hugufc/StandaloneJavascriptReact) that have two projects with identical contents. The only difference is that one is located in a solution folder and the other is on solution root folder.

The problem is reproducible just changing the startup project.

**Comment by jaelys** [comment]
I have the same problem, SDK 0.5.74-Alpha ~ 0.5.126-Alpha is the same. I suspect that this problem occurs after the VS2022 version is updated. There was no problem before.

**Comment by jaelys** [comment]
https://developercommunity.visualstudio.com/t/esproj-will-not-launch-StartupCommand-i/10516578
is vs2022 v17.8.3 fixed

**Comment by hugufc** [comment]
Thank you @jaelys. The problem was not reproducible more after update VS.
