### ISSUE TITLE
[NETSDKE2E][ARM64] With .NET 9 Preview SDK installed, installing wasm-tools workload or maui workload option failed with error.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#37035]
**Repro steps:**

1.Install the latest .Net 9.0 arm64 SDK from https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-arm64.exe.
2.Install wasm-tools workload using below command in CLI
dotnet workload install wasm-tools

**Expected Result:**
Workload can be installed successfully.

**Actual Result:**
It failed with the following error:
![image](https://github.com/dotnet/sdk/assets/106054229/7572430a-151a-4dc5-955b-a20374a59821)

--Error Log--
Workload installation failed: One or more errors occurred. (microsoft.netcore.app.runtime.aot.win-arm64.cross.browser-wasm.msi.arm64::9.0.0-alpha.1.23569.2 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json".)

**Comment by vdanche** [comment]
on win-x64, we also meet the same error when runing dotnet workload install wasi-experimental
![image](https://github.com/dotnet/sdk/assets/65637796/4c48eac0-e10d-412d-8efe-d68310abe89e)

**Comment by v-ainigao** [comment]
Today on ARM64, we also meet the same error when running dotnet workload install maui, but wasm-tools and wasi-experimental can be installed successfully.
CLI running:
dotnet workload install wasi-experimental
![image](https://github.com/dotnet/sdk/assets/106054229/987ca92d-7a2f-4193-9d5f-5b70d35f3075)
dotnet workload install wasm-tools
![image](https://github.com/dotnet/sdk/assets/106054229/edd716ef-055b-456d-b710-dd1820fd4697)
dotnet workload install maui
![image](https://github.com/dotnet/sdk/assets/106054229/cb11b40e-a74d-4143-bc9b-9708fc949c92)
**Note:**
We found that the new version of the .net9 SDK .zip package can be installed successfully all workloads, but the version number of .exe is inconsistent with .zip package.
![image](https://github.com/dotnet/sdk/assets/106054229/4fcd0fc4-dcde-45ab-aa27-e856e097a0dd)

**Comment by lewing** [comment]
Fixed in https://github.com/dotnet/runtime/pull/95170

**Comment by v-ainigao** [comment]
Today on ARM64, we also meet the same error when running dotnet workload install android.
![image](https://github.com/dotnet/sdk/assets/106054229/206ca543-498e-4edf-a42b-128031a42e9f)

**Comment by vdanche** [comment]
with 9.0.100-alpha.1.23607.4(runtime- 9.0.0-alpha.1.23577.7) SDK installed, below errors happen after installing android or maui in CLI,
![image](https://github.com/dotnet/sdk/assets/65637796/4729dbd0-a3ea-427f-a0de-7cfb340c7f67)

**Comment by v-ainigao** [comment]
On ARM64, we also meet the same error when running dotnet workload restore and dotnet workload install android. Can you help me take a look again?
![image](https://github.com/dotnet/sdk/assets/106054229/2d8910ae-f290-4ffa-90bd-fa004f1ebb9c)
![image](https://github.com/dotnet/sdk/assets/106054229/fcdd0e7d-52e2-471e-afa4-9b23d08f495d)
@lewing

**Comment by richaverma1** [comment]
@v-ainigao is this still repro'ng? If so, file a new bug.

**Comment by v-ainigao** [comment]
It still reappears on the latest .NET 9.0 arm64 SDK, so I re-reported a new bug.
https://github.com/dotnet/sdk/issues/38095
@richaverma1
