### ISSUE TITLE
Support ability for FrameworkReference to import analyzers

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#3706]
Request came out of https://github.com/aspnet/AspNetCore/issues/14675

ASP.NET Core app projects today target the Web SDK which auto-imports a set of "default" analyzers. There are scenarios however where parts of an ASP.NET Core app are split into class libraries and then referenced from the main app project, but these class libraries use the base SDK, and manually add a `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to indicate their reliance on ASP.NET Core features. This, however, results in none of the default analyzers. And given the analyzers are only available via the Web SDK (they literally ship only as part of it) there is no first-class way to enable them.

The proposal here is to allow the base SDK to support a `FrameworkReference` declaring it also imports some analyzers, so that class libraries can use them.

**Comment by dsplaisted** [comment]
It looks like we are going to support analyzers in targeting packs, which will address this: https://github.com/dotnet/designs/pull/181

**Comment by eatdrinksleepcode** [comment]
@dsplaisted This would only be addressed in 6.0, correct? So if I am on 3.1 today, and I am writing controllers in a library for modularity, do I understand correctly from this issue (and dotnet/aspnetcore#14675) that there is _no way_ to turn on API analyzers for my library?
