### ISSUE TITLE
[NETE2ESDK] With .NET 9 SDK installed, it should not be an unhandled exception when intalling tools that don't exist.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#37123]
### Describe the bug
With .NET 9 SDK installed,It should not be an unhandled exception when intalling tools that don't exist

**Reproduction Steps**
1. Install .NET 9: 9.0.100-alpha.1.23564.26 on a clean windows OS from https://github.com/dotnet/installer.
2. Run `dotnet tool install -g non-exist-package-id`
3. Observe

**Expected behavior**
It should fail on windows saying something like: error NU1101: Unable to find package non-exist-package-id.
![nu1101](https://github.com/dotnet/sdk/assets/99376012/29d50cd4-8568-4a79-ab54-bdf681c1f5b6)

**Actual Result:**
It actually fail saying something like: 
Unhandled exception: Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageNotFoundException: non-exist-package-id::[*, ) is not found in NuGet feeds https://api.nuget.org/v3/index.json".
![Unhandled exception1](https://github.com/dotnet/sdk/assets/99376012/77824ab3-87ed-4d7e-a65a-68393449bea5)

Note:
It is also repro on Linux and mac.

**Comment by JL03-Yue** [comment]
#36641 should be fixing it. It is expected in 8.0.2xx release. Please let us know if you experience the same problem.

**Comment by JL03-Yue** [comment]
> @JL03-Yue We verified with latest build 9.0.100-alpha.1.23579.15，it shows like bellow, could you please help confirm if it is expected? ![fix](https://private-user-images.githubusercontent.com/99376012/286872362-73a78932-3cd0-4b5e-91d0-19ff6e148ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjgwMTIsIm5iZiI6MTcwMTM2NzcxMiwicGF0aCI6Ii85OTM3NjAxMi8yODY4NzIzNjItNzNhNzg5MzItM2NkMC00YjVlLTkxZDAtMTlmZjZlMTQ4ZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE4MDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZTNkM2M3NWQ0OWZkYTY3MjFhOGMxN2YwZmFkYWE3ZDUyYjRlNzIxZGM0NzI4Nzk3NzQyYmE5NzkzOWU0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kw8fVLMBvOFiVvUWcMCLBkQtnkmz5joN8-3oK_JPjSA)

Yes, it is an explanation of the package could not be found in the source.

**Comment by v-xiaofchen** [comment]
Closed it as fixed.
