### ISSUE TITLE
Assembly InformationalVersion now includes GUID suffix

### ISSUE THREAD

**Issue by snakefoot** [dotnet/sdk#37142]
### Description

Have library-project with the following setting:
```xml
<InformationalVersion>2.0.0.2</InformationalVersion>
```

New Azure DevOps has updated to VisualStudio 2022 v17.8 (With NET8 support), then the following value is returned: `2.0.0.2+0fb16b11f9936e0374948c64e8c3b18db25b6fbf`

Before when resolving the `InformationalVersion` from `AssemblyInformationalVersionAttribute`, then would have the expected value: `2.0.0.2`

### Reproduction Steps

Create library-project with the following setting:
```xml
<InformationalVersion>2.0.0.2</InformationalVersion>
```

### Expected behavior

`InformationalVersion` from `AssemblyInformationalVersionAttribute` should return the specified value. Ex `2.0.0.2`

### Actual behavior

`InformationalVersion` from `AssemblyInformationalVersionAttribute` adds GUID-suffix to the value. Ex `2.0.0.2+0fb16b11f9936e0374948c64e8c3b18db25b6fbf`

The GUID-suffix seems to change on every new build.

### Regression?

It worked as expected before Azure DevOps was updated to VisualStudio 2022 v17.8 (With NET8 support)
```
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.231.0
```

### Known Workarounds

Rollback to older version:
```
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.229.0
```

### Configuration

```
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az516-895'
Current agent version: '3.230.0'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20231115.2.0

Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.231.0
```

**Comment by baronfel** [comment]
I'm going to close this as we've made and documented this as a [breaking change in .NET 8](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link).
