### ISSUE TITLE
dotnet build --help failing due to sdk version

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/sdk#3718]
When I attempt a command with the `--help` argument, it fails due to mismatch of SDK version 

Would making it work disregarding potential mismatch be more user friendly / sensible?

Currently:

```console
C:\tmp\testdotnetnew>dotnet build --help
A compatible installed .NET Core SDK for global.json version [4.2.100] from [C:\tmp\testdotnetnew\global.json] was not found
Install the [4.2.100] .NET Core SDK or update [C:\tmp\testdotnetnew\global.json] with an installed .NET Core SDK:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
```

Also, is there a way to force the sdk to "go ahead"? if so, it would be good to be pointed at that in the mismatch error message (with a bit of caution).

**Comment by livarcocc** [comment]
This is not something we will tackle.

By the time this error happens, there is no .NET Core SDK involved. This is handled entirely by dotnet.exe and it has limited code. We would not want to make that part of the code more complicated to allow for certain commands (or options) to by pass the global.json.

We do have new options to global.json that might be more interesting and work for you in this scenario. There is a rollforward option that lets you choose between patch, minor, major etc.
