### ISSUE TITLE
[APICompat] CP0004 arguments are swapped

### ISSUE THREAD

**Issue by gewarren** [dotnet/sdk#37199]
### Describe the bug
On [this line](https://github.com/dotnet/sdk/blob/d6509c90ef8f05a5971e699f2d3dcdfa5dca84f8/src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs#L37), the arguments to String.Format seem to be switched.

### To Reproduce
Run the apicompat tool on two folder paths where the assembly name isn't the same.

`apicompat -l "C:\Users\gewarren\source\repos\artifacts\bin\LibApp5\debug_net8.0" -r "C:\Users\gewarren\source\repos\artifacts\bin\ConsoleApp5\debug_net8.0"`

**Result**:

Assembly with name 'left' does not exist at ConsoleApp5.
...
CP0004: Assembly with name 'right' does not exist at LibApp5.

**Expected Result**:

Assembly with name 'ConsoleApp5' does not exist at left.
...
CP0004: Assembly with name 'LibApp5' does not exist at right.

### Further technical details
- Include the output of `dotnet --info`

```
C:\>dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.82cf81db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.82cf81db
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.320 [C:\Program Files\dotnet\sdk]
  7.0.114 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.311 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by ViktorHofer** [comment]
Thanks for reporting. Here's the fix: https://github.com/dotnet/sdk/pull/37207
