### ISSUE TITLE
Winget isn't listing .NET 8 for me

### ISSUE THREAD

**Issue by neilejgreen** [dotnet/sdk#37201]
### _Transferred from dotnet/docs_

According to the docs [here](https://github.com/dotnet/docs/blob/ab1180a899035bbd20d67aa6b5ecdeb23f2a5b1f/docs/core/install/windows.md?plain=1#L49) the dotnet 8 SDK can be installed via winget.

```powershell
winget install Microsoft.DotNet.SDK.8
```
However `winget` cannot find that package: 

```powershell
~❯winget install Microsoft.DotNet.SDK.8
No package found matching input criteria.
```

The package does not appear visible to this [winget search site](https://winget.run/search?query=DotNet%20SDK) either.

**Comment by neilejgreen** [comment]
Thanks @adegeo.

I seem to have resolved the issue.   I was looking through the logs you mentioned and decided to try adding the `winget` source under a new alias and asking it to try downloading from that source.

**Comment by adegeo** [comment]
I did look into the github repos for those search sites and a few people have been reporting XYZ packages missing for a while. https://github.com/winget-run/wingetdotrun/issues/43 and I think those sites are actually their own thing that reflect packages, by some sort of manual process perhaps. For example, this issue in their github:

![image](https://github.com/dotnet/sdk/assets/67293991/6ea79068-091a-4cce-afc3-1e72a9504362)
