### ISSUE TITLE
add output format support for dotnet tool list command

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#37239]
> I drafted a dotnet-tool `dotnet-update-all-tools` according to the dotnet tool list output

The exact format of the `dotnet tool list` output is not documented at <https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-list>.  "The command lists the package name, version installed, and the tool command", but this does not say anything about column headers, or about the "Manifest" column when listing local tools.  I suspect a future version of .NET SDK may change the format and break any software that parses it.  `dotnet tool list` doesn't yet support a `--format json` option like in `dotnet list package`.

_Originally posted by @KalleOlaviNiemitalo in https://github.com/dotnet/sdk/issues/19650#issuecomment-1833280431_

It would help us have an expected output consistently and also benefit the developers who want to use the output.

Currently, I drafted a dotnet tool to update all the dotnet tools installed according to the console output, while when the console output format changed, it would break, it would be better to support a consistent output such as json format, and keep using console as the default format

Usage:

``` sh
# global tools
dotnet tool list --global --format json

# local tools
dotnet tool list --local --format json
```

possible `--format` option values:

- `console`, default format as now
- `json`, output json text
- `csv`

possible JSON output details

```json
{
    "packageId": "dotnet-counters",
    "version": "8.0.0",
    "commands": "dotnet-counters"
}
```

(intended for better readability?)

possible CSV output details

```csv
packageId,version,commands
dotnet-counters,8.0.0,dotnet-counters
```

**Comment by WeihanLi** [comment]
maybe I can help with this, does the output format proposed look good?

**Comment by WeihanLi** [comment]
Hi @KalleOlaviNiemitalo , is there a tool for generating the translation or could I add the new translation manually?

**Comment by WeihanLi** [comment]
Another thought, maybe we could add version info in case we change the schema in the future

for example:
version 1:

```json
{
    "version": 1,
    "tools": [
        {
            "packageId": "dotnet-execute",
            "version": "0.15.0",
            "commands": [
                "dotnet-exec"
            ]
        }
    ]
}
```

version 2:

```json
{
    "version": 2,
    "tools": [
        {
            "packageId": "dotnet-execute",
            "packageVersion": "0.15.0",
            "commands": [
                "dotnet-exec"
            ]
        }
    ]
}
```

**Comment by WeihanLi** [comment]
@KalleOlaviNiemitalo could you please review the PR when you have time, thanks very much.
I have no idea why the test timeout, seemed not relate to the changes

**Comment by nagilson** [comment]
Kalle does not work on the SDK team specifically, they are more like a community-member ninja who helps us from the shadows and seems to know a lot about dotnet ;)
