### ISSUE TITLE
Published ConsoleApp with AOT throws error /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [dotnet/sdk#37240]
### Describe the bug
When I publish a console app, it does not run in Ubuntu 18.04 and gives the following error message: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 

### To Reproduce
dotnew new console -n TestAot
Add the follwoing to the csproj file:
```csharp
<RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>partial</TrimMode>
<PublishAot>true</PublishAot>
```

Publish the project using the folowing command:
`dotnet publish --configuration release -r linux-x64 --self-contained true /p:EnableCompressionInSingleFile=true -o ./linux-x64`

Run the published assembly in an Ubuntu fresh installation.

### Further technical details
I tried to publish it with my WSL2 Ubuntu 22.04 installed on a Windows 10 Pro and also in the azure pipeline with Ubuntu 20.04. Both had the same result.

- Include the output of `dotnet --info`
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk]
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by Forgind** [comment]
Are you using clang or gcc? I have gcc, and I tried making a new console app, adding the lines you mentioned to its opening PropertyGroup, and publishing with your command line, and it failed:

```
dotnet publish --configuration release -r linux-x64 --self-contained true /p:EnableCompressionInSingleFile=true -o ./linux-x64
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  37240 -> /home/forgind/bugs/37240/bin/release/net8.0/linux-x64/37240.dll
  Generating native code
  /usr/bin/ld.bfd: cannot find -lz: No such file or directory
collect2 : error : ld returned 1 exit status [/home/forgind/bugs/37240/37240.csproj]
/home/forgind/.nuget/packages/microsoft.dotnet.ilcompiler/8.0.0/build/Microsoft.NETCore.Native.targets(364,5): error MSB3073: The command ""gcc" "obj/release/net8.0/linux-x64/native/37240.o" -o "bin/release/net8.0/linux-x64/native/37240" -gz=zlib -fuse-ld=bfd /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/sdk/libbootstrapper.o /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/sdk/libRuntime.WorkstationGC.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/sdk/libeventpipe-disabled.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/sdk/libstdc++compat.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/framework/libSystem.Native.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/framework/libSystem.Globalization.Native.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/framework/libSystem.IO.Compression.Native.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/framework/libSystem.Net.Security.Native.a /home/forgind/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.0/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -ldl -lz -lrt -lm -pie -Wl,-pie -Wl,-z,relro -Wl,-z,now -Wl,--eh-frame-hdr -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/home/forgind/bugs/37240/37240.csproj]
```

Did I do something wrong?

**Comment by mahdighorbanpourptw** [comment]
I installed clang. 
```
 clang --version
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Could you please retry without the  -o ./linux-x64

**Comment by tmds** [comment]
> cannot find -lz: No such file or directory

You need the zlib development files.

> it does not run in Ubuntu 18.04 and gives the following error message: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

Your app was compiled on an OS with a more recent version of glibc. This causes it to not find a specific symbol when ran on the older Ubuntu 18.04.

Microsoft are providing some aot sdk images in the [nightly sdk repository](https://hub.docker.com/_/microsoft-dotnet-nightly-sdk/). Unfortunately, I assume they won't fix your issue as they are based on Ubuntu 22.04.

cc @richlander @baronfel @mthalman

**Comment by mahdighorbanpourptw** [comment]
> Your app was compiled on an OS with a more recent version of glibc. This causes it to not find a specific symbol when ran on the older Ubuntu 18.04.

Thanks a lot. That clears the problem. I would try the published assembly on an Ubuntu 22.04. 
By the way, if I publish the file on Ubuntu 18.04, would it then work for both 18.04 and 22.04?

**Comment by tmds** [comment]
Yes, if you publish on Ubuntu 18.04, it is expected to work on 22.04.

**Comment by mahdighorbanpourptw** [comment]
@tmds I tested as you suggested and it is now working fine. Thank you.
However, I encountered another issue, comparing the published file using AOT and without AOT (but singleFile), I see a major difference in the size. In this bare example the difference is just about 3 MB, but in our production app is much more!
Publish SingleFile without AOT: 17MB
Publish with AOT: 38 MB
What could be the reason for this and how I can achieve the same level of size?

![image](https://github.com/dotnet/sdk/assets/97948692/f61c6f35-fb95-4684-90bd-4baa76e7fdfd)

By the way, here is how I publish without AOT:
- replace the <PublishAot>true</PublishAot> with <PublishSingleFile>true</PublishSingleFile> in the csproj file and use the same publish command.

**Comment by marcpopMSFT** [comment]
Adding @agocke We believe that in the AOT case, the much larger native symbols get embedded in the binary and that's the reason for the larger side but we'd need Andy to confirm this behavior.

**Comment by mahdighorbanpourptw** [comment]
@marcpopMSFT 
Is there any update on this after discussion on Jan 2? 
Would that be better I create a new issue for this?
Thank you

**Comment by mahdighorbanpourptw** [comment]
I created a new bug #39012
