### ISSUE TITLE
Can only build 2.2 Tests with 3.0 installed with RuntimeIdentifier specified

### ISSUE THREAD

**Issue by Codex-** [dotnet/sdk#3725]
I came across this issue today when Visual Studio updated to 16.3 and forced the installation of .NetCore 3.0

When 3.0 is installed I found I was unable to build 2.2 apps/test projects as they resulted in the error `System.BadImageFormatException : Bad IL format.`. Removing 3.0 'resolved' this. 

With 3.0 being forcibly installed now I've managed to find that adding `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to the project configuration I was then able to build again, but this seems wrong too.

the config is:
```
<PropertyGroup>
	<TargetFramework>netcoreapp2.2</TargetFramework>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<IsPackable>false</IsPackable>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>
```

I suspect that this framework target with the use of `CopyLocalLockFileAssemblies` results in the problem, but in my case I can't build without it (and historically this has worked until now).

Removing `RuntimeIdentifier` brings back the original error, rolling back to VS 16.2 without 3.0 installed works as expected.

I feel like I'm missing something, unless this is a bug. 

Any ideas/thoughts are appreciated

**Comment by livarcocc** [comment]
Is this the entirety of your project? does it work if you run dotnet test from the command line?

**Comment by Codex-** [comment]
Interesting, the cli gives a proper trace which is nice (VS just gave nothing but the one liner, could be a config thing thought)

```
TearDown failed for test fixture ...TestFixtureSetup
                                                                                                                                                                                                                                      System.BadImageFormatException : Bad IL format.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
                                                                                                                                                                                                                                         at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   ...
   at MqaCommon.External.BrowserStackHelper.GetProviders()
   at MqaCommon.External.BrowserStackHelper.UsingBrowserStack()
   ...
                                                                                                                                                                                                                                        X TestTest [< 1ms]
  Error Message:
   OneTimeSetUp: System.BadImageFormatException : Bad IL format.
```

Have had to omit a few lines due to rules etc.

**Comment by Codex-** [comment]
Tracked it down to the usage of `Assembly.LoadFrom`.
