### ISSUE TITLE
disabling vulnerability checking in version 8 of dotnet

### ISSUE THREAD

**Issue by codename00047** [dotnet/sdk#37265]
hi,

how to disable vulnerability checking by URL https://api.nuget.org/v3/vulnerabilities/index.json when running dotnet pack, dotnet restore, dotnet test in mcr.microsoft.com/dotnet/sdk:8.0?
since this URL is not accessible and it cannot be proxyed through the nexus, the builds in gitlab-ci take a very long time - more than 20 minutes
in the 7th version of dotnet there were no such problems
help, please!

**Comment by danmoseley** [comment]
Cc @JonDouglas

**Comment by JonDouglas** [comment]
@codename00047 Docs here:

https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages#disabling-security-auditing

**Comment by JonDouglas** [comment]
hmm seems odd. is <nugetaudit> defined in each of the projects? maybe use a msbuild evaluator i.e. https://msbuildlog.com/ to ensure it is being respected for every project? you can also file feedback to nuget/home but i will /cc @zivkan who may know more here.

**Comment by zivkan** [comment]
In @codename00047 examples, the first csproj did not disable NuGetAudit, only the second csproj did. If there's even a single project in a solution (or project graph) that doesn't disable NuGetAudit, then NuGet will try to get the vulnerability database, so it can run audit on the projects where it's not disabled.

The easiest way to disable it across all projects is to use Directory.Build.props: https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022#directorybuildprops-and-directorybuildtargets

**Comment by codename00047** [comment]
project structure, as in the documentation:
```
\
  MySolution.sln
  Directory.Build.props     (1)
  \src
    Directory.Build.props   (2-src)
    \Project1
    \Project2
  \tests
    Directory.Build.props   (2-tests)
    \Project1Tests
    \Project2Tests
```
after I placed the Directory.Build.props files according to the documentation I get the following error:
`error: The imported project file "/builds/project/tests/Unit.Tests/Directory.Build.props" could not be loaded. There are multiple root elements. Line 7, position 2.  /usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props`

in the project directory I placed the next Directory.Build.props (1) file:
```
<Project>
 <PropertyGroup>
   <NuGetAudit>false</NuGetAudit>
 </PropertyGroup>
</Project>
```
and in the src and tests directories there are files Directory.Build.props (2-src, 2-tests) with the following contents:
```
<Project>
 <PropertyGroup>
   <NuGetAudit>false</NuGetAudit>
 </PropertyGroup>
</Project>

<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
```

**Comment by codename00047** [comment]
if I delete audit information for example in tests directory, the error changes:
`error: The element <Import> is unrecognized, or not supported in this context.  /builds/.../project/tests/Directory.Build.props`

cat tests/Directory.Build.props:
`<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />`

**Comment by baronfel** [comment]
You have a syntax error in your props file - Imports go inside the parent Project element, not outside.

**Comment by codename00047** [comment]
the Directory.Build.props file helped disable auditing, there are no entries in the logs that the URL https://api.nuget.org/v3/vulnerabilities/index.json is not accessible, but unfortunately this did not affect the build speed in any way:
`19 minutes in version 8 versus 40 seconds in version 7`

**Comment by mcanzerini** [comment]
Same problem for me: 

- Artifactory as private repository
- Docker Dotnet 8.0 in Gitlab CI runner
- NuGetAudit disabled

Around 40 seconds in .NET 7 versus 45 min in .NET 8

My own issue here: https://github.com/NuGet/Home/issues/13062

**Comment by codename00047** [comment]
What is the reason for the long build if auditing is disabled?

**Comment by zivkan** [comment]
SDK team, my suggestion is that this can be closed as a duplicate of https://github.com/NuGet/Home/issues/13062

@codename00047 similar to [my request in the NuGet issue](https://github.com/NuGet/Home/issues/13062#issuecomment-1838519952), I need more information in order to investigate. Please reply over there with any information that can help. Here are some ways that can help:

* Create a sample solution that reproduces the problem, using only nuget.org as a package source, so I can run restore myself
* use `dotnet-trace` to capture what restore is doing during the slow restore. It would be ideal if you could also capture the same, fast, restore using the .NET 7 SDK, so we can compare the .NET 7 and .NET 8 traces to see why they're different

**Comment by baronfel** [comment]
Thank you for the analysis @zivkan - I agree we can close this, I wanted to give you all a chance to sanity-check us though :)
