### ISSUE TITLE
[NETSDKE2E]The directory "C:\Program Files\dotnet\sdk-manifests" could not be deleted after uninstalling 6.0.312 SDK.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#37374]
1. install 6.0.321 SDK on win11-x64
2. install workload: dotnet workload install wasm-tools
3. Uninstall 6.0.321 SDK in control panel.
4. After uninstall is done, check the installation directory in C disk

Expected Result:
the installation directory should be removed

Actual Result:
The directory "C:\Program Files\dotnet\sdk-manifests" still display.
![image](https://github.com/dotnet/sdk/assets/65637796/14782dd7-d09b-428c-92c4-fd7d67194831)

Note:
1.It not repro on 6.0.418 SDK
2.It also repro on 6.0.320
2.if we dotnet workload install wasm-tools --skip-manifest-update, this issue will not repro.

**Comment by Forgind** [comment]
The 6.0.3xx SDK is out-of-support, and you said this problem does not repro on 6.0.4xx. Can you upgrade to 4xx?

**Comment by vdanche** [comment]
@Forgind 6.0.3xx and 6.0.4xx can co-exist. not support upgrade from 6.0.3xx to 6.0.4xx
![image](https://github.com/dotnet/sdk/assets/65637796/0a521db6-8a71-4cd6-a363-ed1f1b84e2ff)

**Comment by Forgind** [comment]
You're right that they can coexist, but we have a fixed time before we stop servicing old versions, and 6.0.3xx is out of support.
