### ISSUE TITLE
`dotnet list package` command options should support shorter names. For example, -f for --framework. Have to specify the long name every time.

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/sdk#37385]
### Is your feature request related to a problem? Please describe.
`dotnet list package` command options should support shorter parameter names. For example, `-f` for `--framework` and so on. Have to specify the long name every time.

### Describe the solution you'd like
Standard shorter parameter names as supported in all other commands.

### Additional context
Nope.

**Comment by egvijayanand** [comment]
Certain options are standard across almost all the commands:

--help / -h
--verbosity / -v
--configuration / -c
--framework / -f
--source / -s
--runtime / -r

These are expected to be supported when newer commands are introduced so that adapting to them will be quite easy.

**Comment by baronfel** [comment]
Reopening because this issue isn't just about `-f`.

**Comment by joegoldman2** [comment]
> Reopening because this issue isn't just about `-f`.

Good catch! Looks like I missed a part of this issue. I'll try to have a look and identify the other commands that may need to be updated.

**Comment by nagilson** [comment]
Should we set a milestone for this?

**Comment by marcpopMSFT** [comment]
Framework was already added as is verbosity. Configuration could be added as well as source.

@aortiz-msft this command is owned by nuget but lives in the sdk so if I label it, it'll get closed. What action did you want to take here?

**Comment by aortiz-msft** [comment]
@Nigusu-Allehu  -  Any chance you can take a look in the last week of the month?

**Comment by Nigusu-Allehu** [comment]
I will look into this.

**Comment by Nigusu-Allehu** [comment]
> Certain options are standard across almost all the commands:
> 
> --help / -h --verbosity / -v --configuration / -c --framework / -f --source / -s --runtime / -r
> 
> These are expected to be supported when newer commands are introduced so that adapting to them will be quite easy.

--help / -h                      :  The following is already supported
--verbosity / -v               : We will add the following as it is also supported by our other commands as well
--configuration / -c        : Other NuGet commands in dotnet do not support a short version of --configfile option. For consistency reasons, adding it to `dotnet list package` might not be a good idea.
--framework / -f             : Already adopted
--source / -s                   : We will add the following as it is also supported by our other commands as well
--runtime / -r                 : Not supported by `dotnet list package`
