### ISSUE TITLE
error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found.

### ISSUE THREAD

**Issue by gokulrajmariyappan** [dotnet/sdk#37436]
I have created a new dotnet webapi project and am trying to build a docker image with that. However while running the build am getting the following error. 

**1.186 /usr/share/dotnet/sdk/3.1.426/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/app/weatherapi.csproj]**

VS Coder version: Version: 1.85.0 (Universal)

dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.2d90560f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet/8.0.0/libexec/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2d90560f
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/opt/homebrew/Cellar/dotnet/8.0.0/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/opt/homebrew/Cellar/dotnet/8.0.0/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/Cellar/dotnet/8.0.0/libexec]

global.json file:
  Not found

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Forgind** [comment]
Ok, so the first thing I notice is that it's looking for .NET _Framework_ 8.0. That doesn't exist, and that's presumably why we're failing to find it.

That most often happens if you have something that checks if something contains "Core" and uses that to decide framework vs. .NET Core. .NET 8 doesn't have Core or Framework, but of note, the version of Microsoft.Common.CurrentVersion.targets you found is apparently from the 3.1.426 SDK.

In your dotnet --info spew, it doesn't mention there being a 3.1.426 SDK on your machine. What command(s) are you executing to get you this error message? Are you running them from the same terminal you used to call dotnet --info?

**Comment by Hideman85** [comment]
I have the exact same issue on Ubuntu 23.10 (mantic), I have a brand new install from this doc but it doesnt seem to work.
I do  not understand what I should install, right now when I search for dotnet core I do have the following:

```
apt search dotnet core                                                                                                                                                                                                         ─╯
Sorting... Done
Full Text Search... Done
aspnetcore-runtime-6.0/mantic-updates,mantic-security 6.0.126-0ubuntu1~23.10.1 amd64
  ASP dotNET Core runtime

aspnetcore-runtime-7.0/mantic-updates,mantic-security 7.0.115-0ubuntu1~23.10.1 amd64
  ASP dotNET Core runtime

dotnet-apphost-pack-6.0/mantic-updates,mantic-security 6.0.126-0ubuntu1~23.10.1 amd64
  Internal - targeting pack for Microsoft.NETCore.App 6.0

dotnet-apphost-pack-7.0/mantic-updates,mantic-security 7.0.115-0ubuntu1~23.10.1 amd64
  Internal - targeting pack for Microsoft.NETCore.App 7.0

dotnet-apphost-pack-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
  Internal - targeting pack for Microsoft.NETCore.App 8.0

dotnet-targeting-pack-6.0/mantic-updates,mantic-security 6.0.126-0ubuntu1~23.10.1 amd64
  Internal - targeting pack for Microsoft.NETCore.App 6.0

dotnet-targeting-pack-7.0/mantic-updates,mantic-security 7.0.115-0ubuntu1~23.10.1 amd64
  Internal - targeting pack for Microsoft.NETCore.App 7.0

dotnet-targeting-pack-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
  Internal - targeting pack for Microsoft.NETCore.App 8.0
  ```
  
  In addition what I have from dotnet that is installed on my system:
  
  ```
dotnet-apphost-pack-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-host-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-hostfxr-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-runtime-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-sdk-8.0/mantic-updates,mantic-security,now 8.0.101-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-targeting-pack-8.0/mantic-updates,mantic-security,now 8.0.1-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet-templates-8.0/mantic-updates,mantic-security,now 8.0.101-0ubuntu1~23.10.1 amd64 [installed,automatic]
dotnet8/mantic-updates,mantic-security,now 8.0.101-8.0.1-0ubuntu1~23.10.1 amd64 [installed]
```
  
  How to go forward?
  
  Thanks in advance for your help.

**Comment by Forgind** [comment]
@Hideman85, I don't see an error in what you shared. Can you share the exact error you saw when you tried to build?

Do you have an older (pre-.NET 5.0) SDK on your computer anywhere?

**Comment by Forgind** [comment]
It doesn't seem like I'm getting responses on this, so closing for now.

**Comment by davispuh** [comment]
I'm getting this same error when trying to build a project.

```
$ msbuild
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
```

```
$ dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.2fd734c4

Runtime Environment:
 OS Name:     arch
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2fd734c4
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

I was executing `msbuild` which failed but running `dotnet build` worked fine.

Also `msbuild`  comes from https://github.com/mono/linux-packaging-msbuild so seems Mono bug?

**Comment by baronfel** [comment]
The mono MSBuild is very, very old and likely will not build recent .NET SDK projects.

**Comment by abdi2000** [comment]
I am also getting similar error----

**/root/.dotnet/sdk/3.1.426/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v8.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.**

So I am trying to upgrade my project to .Net 8.0 and I have checked that the required SDK is installed on my machine by the command dotnet --list-sdks.

I also can build solution locally after upgrading my project to .Net 8.0. Now when I am doing Octopus Deploy, the deployment is failing with the above error.

**Comment by drewdelano** [comment]
![image](https://github.com/dotnet/sdk/assets/22156330/1487e2ce-67a2-43a6-b881-8b0b14f190dd)

**Comment by baronfel** [comment]
@drewdelano the `"dotnet8" value for `--framework` isn't valid - `--framework` values must be valid Target Framework Moniker values, like netstandard2.0, net8.0, or net472. Please see the [TFM docs](https://learn.microsoft.com/dotnet/standard/frameworks#latest-versions) for more examples.

**Comment by marlon-tucker** [comment]
If anyone gets here via a google search, a global.json file in the folder tree was specifying a sdk version 3.1 and that was causing the error message referenced in this issue. 

Deleting / updating that global.json fixed it in my case.

**Comment by anandvsingh** [comment]
I ran into this issue on a shared build system and the root cause of that was that in the environment variables someone had hardcoded the MSBuildSDKsPath, deleting the enviornment variable fixed the issue for me.

` MSBuildSDKsPath: C:\Program Files\dotnet\sdk\3.1.405\Sdk`

**Comment by Myriad4Link** [comment]
For anyone who decompiles and exports through dotPeek, try change `<TargetFrameworkVersion>v8.0</TargetFrameworkVersion>` to `<TargetFramework>net8.0</TargetFramework>`.
Although this is not really related to the original issue but lots of people seems to redirect from Google to here, so sorry about that🫡

**Comment by DmitryLukyanov** [comment]
@Forgind  I see the same error without any reason for this:

>Error	MSB3971	The reference assemblies for ".NETFramework,Version=v9.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.	MyApp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1177	

The steps I take:
1. Create a new project / solution with .net9.0
2. Work sometime without any issues
3. At some point after restarting Visual Studio, I starts to see this error. No changes anywhere (project file/.net sdks/anything else) are applied

         dotnet --list-sdks
         3.1.418 [C:\Program Files\dotnet\sdk]
         9.0.107 [C:\Program Files\dotnet\sdk]
         9.0.301 [C:\Program Files\dotnet\sdk]

started to happen approximately after I upgraded VS to latest version few days ago

Project file:

    <Project Sdk="Microsoft.NET.Sdk">

       <PropertyGroup>
       <OutputType>Exe</OutputType>
       <TargetFramework>net9.0</TargetFramework>
       <ImplicitUsings>enable</ImplicitUsings>
       <Nullable>enable</Nullable>
       <UserSecretsId>some_value</UserSecretsId>
    </PropertyGroup>
    ...

Some workaround I see is to recreate a sln file (not sure why it helps):


		Microsoft Visual Studio Solution File, Format Version 12.00
		# Visual Studio Version 17
		VisualStudioVersion = 17.14.36212.18 d17.14
		MinimumVisualStudioVersion = 10.0.40219.1
		Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyApp", "MyApp\MyApp.csproj", "{A5FC3EC3-DB80-03F9-5D5B-7656E905D1CF}"
		EndProject
		Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyApp.Tests", "MyApp.Tests\MyApp.Tests.csproj", "{CDC93A9A-7AD8-7B2F-85AC-EA99EDB228A4}"
		EndProject
		Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Mcp.Client", "Mcp\Mcp.Client\Mcp.Client.csproj", "{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A}"
		EndProject
		Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Mcp.Server", "Mcp\Mcp.Server\Mcp.Server.csproj", "{77F8DC55-EFD4-9273-7C28-2B8848137597}"
		EndProject
		Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Mcp", "Mcp", "{02EA681E-C7D8-13C7-8484-4AC65E1B71E8}"
		EndProject
		Global
			GlobalSection(SolutionConfigurationPlatforms) = preSolution
				Debug|Any CPU = Debug|Any CPU
				Release|Any CPU = Release|Any CPU
			EndGlobalSection
			GlobalSection(ProjectConfigurationPlatforms) = postSolution
				{A5FC3EC3-DB80-03F9-5D5B-7656E905D1CF}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
				{A5FC3EC3-DB80-03F9-5D5B-7656E905D1CF}.Debug|Any CPU.Build.0 = Debug|Any CPU
				{A5FC3EC3-DB80-03F9-5D5B-7656E905D1CF}.Release|Any CPU.ActiveCfg = Release|Any CPU
				{A5FC3EC3-DB80-03F9-5D5B-7656E905D1CF}.Release|Any CPU.Build.0 = Release|Any CPU
				{CDC93A9A-7AD8-7B2F-85AC-EA99EDB228A4}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
				{CDC93A9A-7AD8-7B2F-85AC-EA99EDB228A4}.Debug|Any CPU.Build.0 = Debug|Any CPU
				{CDC93A9A-7AD8-7B2F-85AC-EA99EDB228A4}.Release|Any CPU.ActiveCfg = Release|Any CPU
				{CDC93A9A-7AD8-7B2F-85AC-EA99EDB228A4}.Release|Any CPU.Build.0 = Release|Any CPU
				{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
				{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A}.Debug|Any CPU.Build.0 = Debug|Any CPU
				{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A}.Release|Any CPU.ActiveCfg = Release|Any CPU
				{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A}.Release|Any CPU.Build.0 = Release|Any CPU
				{77F8DC55-EFD4-9273-7C28-2B8848137597}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
				{77F8DC55-EFD4-9273-7C28-2B8848137597}.Debug|Any CPU.Build.0 = Debug|Any CPU
				{77F8DC55-EFD4-9273-7C28-2B8848137597}.Release|Any CPU.ActiveCfg = Release|Any CPU
				{77F8DC55-EFD4-9273-7C28-2B8848137597}.Release|Any CPU.Build.0 = Release|Any CPU
			EndGlobalSection
			GlobalSection(SolutionProperties) = preSolution
				HideSolutionNode = FALSE
			EndGlobalSection
			GlobalSection(NestedProjects) = preSolution
				{D47F47F8-BC1E-3E0F-D6D0-CF009E876D3A} = {02EA681E-C7D8-13C7-8484-4AC65E1B71E8}
				{77F8DC55-EFD4-9273-7C28-2B8848137597} = {02EA681E-C7D8-13C7-8484-4AC65E1B71E8}
			EndGlobalSection
			GlobalSection(ExtensibilityGlobals) = postSolution
				SolutionGuid = {92DB3302-09D9-4A8A-9C1F-128DA101F54E}
			EndGlobalSection
		EndGlobal

**Comment by bluebaroncanada** [comment]
Had this problem in Rider/Mac.  I just had to switch the MSBUILD version to the latest.  It was set explicitly in the settings to a lower version.  Setting it to Auto Detect fixed everything.
Somehow check your MSBUILD version. 15 was no good.  17 worked.
