### ISSUE TITLE
[NETE2ESDK] [Regression] With .NET 9 SDK installed, it should return that the tool was successfully installed when the tool was installed globally.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#37501]
### Describe the bug
With .NET 9 SDK installed, it should return that the tool was successfully installed when the tool was installed globally.

**Reproduction Steps**
1. Install .NET 9: 9.0.100-alpha.1.23613.9 on a clean windows OS from https://github.com/dotnet/installer.
2. Run dotnet tool install -g dotnet-ef
3. Observe

**Expected behavior**
It should return Tool was successfully installed.
![DOTNET tool](https://github.com/dotnet/sdk/assets/99376012/beddee4d-6655-4ad0-8037-ccfd34abc81f)

**Actual Result:**
No successful installation information was returned
![dotnettool2](https://github.com/dotnet/sdk/assets/99376012/6d479fe2-1b14-4d72-a1dc-4999d17c43f8)

**Note:**
It is also repro on Linux and mac.

**Comment by vdanche** [comment]
Also repro on the latest 8.0.200-preview.23612.10 (runtime-8.0.0) SDK

**Comment by NicoleWang001** [comment]
This issue is also repro on dotnet-sdk-9.0.100-alpha.1.23613.1, but not repro on dotnet-sdk-9.0.100-alpha.1.23612.7.

**Comment by marcpopMSFT** [comment]
@JL03-Yue it'd be good to investigate by Feb in case there's a 9.0 regression.

**Comment by richaverma1** [comment]
@marcpopMSFT it also repros on newer builds of 8.0.200-preview. Should this be looked at sooner then though 8.0.200-preview is not going to be released standalone?

**Comment by baronfel** [comment]
Potentially a regression from https://github.com/dotnet/sdk/pull/36505?

**Comment by marcpopMSFT** [comment]
Ahh, I didn't notice it was reported in 2xx as well. @JL03-Yue , do you think you'll have time to investigate by Jan 5th for a 2xx fix? That's when VS starts locking down.

**Comment by JL03-Yue** [comment]
This is caused by the recent merge of #35173

**Comment by baronfel** [comment]
There should be a documented change, yes - we also need to fix the fact that the `Skipping NuGet package signature verification` message was emitted in `quiet` mode.

**Comment by v-xiaofchen** [comment]
@baronfel The _**Skipping NuGet package signature verification**_ message still show on build  9.0.100-alpha.1.24067.14 (runtime- 9.0.0-alpha.1.24061.26), please help to take a look.
![dotnettool](https://github.com/dotnet/sdk/assets/99376012/89483c7c-3dbc-4b21-97e5-0a36c654396c)

**Comment by baronfel** [comment]
I don't think we've quite fixed the nuget message yet - @JL03-Yue and I figured out a plan for it a day or so ago and she's going to implement it.

**Comment by JL03-Yue** [comment]
Thank you @baronfel. No, we haven't implement the change yet @v-xiaofchen

**Comment by NicoleWang001** [comment]
This issue is still repro on 9.0.100-preview.1.24079.6 .

**Comment by vdanche** [comment]
This issue not repro on  9.0.100-preview.3.24165.20
![image](https://github.com/dotnet/sdk/assets/65637796/34850f21-9352-43dc-9c54-b3f3dc4778af)
