### ISSUE TITLE
[NETSDKE2E]Publishing blazorwasm project failed with AOT compilation = true with .net9 SDK

### ISSUE THREAD

**Issue by v-jieyan2** [dotnet/sdk#37524]
Repro steps:

1.On a clean OS: Install SDK 9.0.100-alpha.1.23614.10 from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)

2.Install wasm-tools
    dotnet workload install wasm-tools --skip-manifest-update

3.New blazorWasm
     dotnet new blazorwasm

4.add below code to csproj file to use AOT compilation
     `<RunAOTCompilation>true</RunAOTCompilation>`

5.dotnet publish

Expected Result:
publish successfully

Actual Result:
Publish failed
![image](https://github.com/dotnet/sdk/assets/106043919/b0895977-a9b7-4e2f-acc1-21e52e1b21c0)

error: C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : Failed to compile C:\code\obj\Release\net9.0\wasm\for-publish\Microsoft.AspNetCore.Components.WebAssembl
y.dll.bc -> C:\code\obj\Release\net9.0\wasm\for-publish\Microsoft.AspNetCore.Components.WebAssembly.dll.o [C:\code\code
.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : C:\code>C:\Windows\System32\chcp.com 65001 1>nul  [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : C:\code>setlocal [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : C:\code>set errorlevel=dummy  [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : C:\code>set errorlevel=  [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : C:\code>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-arm64\9.0.0-alpha.
1.23613.1\Sdk\..\tools\emscripten\emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\
9.0.0-alpha.1.23614.10\runtimes\browser-wasm\native\src\emcc-default.rsp" -msimd128 "@C:\code\obj\Release\net9.0\wasm\f
or-publish\emcc-compile-bc.rsp" -c -o "C:\Users\v-jieyan2\AppData\Local\Temp\3\tmpwpcisz.tmp" "C:\code\obj\Release\net9
.0\wasm\for-publish\Microsoft.AspNetCore.Components.WebAssembly.dll.bc"  [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : 'C:\Program' is not recognized as an internal or external command, [C:\code\code.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\9.0.0-alpha.1.23614.10\Sdk\WasmApp.Common.targets(8
19,5): error : operable program or batch file. [took 0.14s] [C:\code\code.csproj]

dotnet --info:
.NET SDK:
Version:           9.0.100-alpha.1.23614.10
Commit:            cef8ba01cc
Workload version:  9.0.100-manifests.28136379
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22621
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.23614.10\
 
.NET workloads installed:
Workload version: 9.0.100-manifests.28136379
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-alpha.1.23612.13
  Architecture: x64
  Commit:       ab1a8224cd
 
.NET SDKs installed:
  9.0.100-alpha.1.23614.10 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.23612.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.23612.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.23612.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This problem is also reproduced on Win ARM64.

**Comment by vdanche** [comment]
This issue also happens with AOT compilation disabled.
![image](https://github.com/dotnet/sdk/assets/65637796/10d79843-6dda-4254-8b4d-19d357c9b018)

**Comment by v-jieyan2** [comment]
This issue has been fixed on net 9.0.100-preview.1.24079.6 SDK.
![image](https://github.com/dotnet/sdk/assets/106043919/f1d31e63-138f-4aa5-9301-da2eb4047e9e)

**Comment by v-jieyan2** [comment]
This issue has been fixed on net 9.0.100-preview.1.24079.6 SDK.
![image](https://github.com/dotnet/sdk/assets/106043919/36c7c10b-0e90-4fb5-9290-0f06d1866cc0)
