### ISSUE TITLE
Code-style analysis rules not included with `AnalysisLevel` = `latest`

### ISSUE THREAD

**Issue by joegoldman2** [dotnet/sdk#37569]
### Describe the bug

Using a non-stable version (like `9.0.100-alpha.1.23615.9` in my case) of the SDK and with `AnalysisLevel` sets to `latest`, analysislevel_\*.globalconfig is included but not analysislevelstyle_\*.editorconfig.

Target `AddGlobalAnalyzerConfigForPackage_MicrosoftCodeAnalysisNetAnalyzers`:

![net_analyzers](https://github.com/dotnet/sdk/assets/147369450/ca1b5fd4-76cb-4937-80d3-922993bd57e1)

Target `AddGlobalAnalyzerConfigForPackage_MicrosoftCodeAnalysisCSharpCodeStyle`:

![code_style](https://github.com/dotnet/sdk/assets/147369450/9181f044-93d5-4eca-a1b1-5709e58a88f9)

### To Reproduce
1 - Run `dotnet new console --framework net9.0`
2 - Edit the csproj and program.cs:
```diff
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
+   <AnalysisLevel>latest</AnalysisLevel>
+   <AnalysisMode>All</AnalysisMode>
+   <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
```
```diff
Console.WriteLine("Hello, World!");

// 👇 IDE0040 'Accessibility modifiers required' should be normally raised here
+ class Test
+ {
+ }
```
3 - Run `dotnet build`

### Expected

It seems a little odd that the editorconfig for `Microsoft.CodeAnalysis.NetAnalyzers` package is included but not the one for `Microsoft.CodeAnalysis.CSharp.CodeStyle` which is only included when `AnalysisLevel` is set to `preview` in this case. I expect both to be included (for rules <= .NET 8).

cc @mavasani

**Comment by mavasani** [comment]
Below properties need to be bumped up by one version: https://github.com/dotnet/sdk/blob/91a440681da35b13a1528bd6dcf35c64a2c221ab/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L24-L26

**Comment by mavasani** [comment]
@joegoldman2 We should also fix up the naming in Roslyn repo for the generated `AnalysisLevelStyle_xxx.editorconfig` to be `AnalysisLevelStyle_xxx.globalconfig` for both consistency and also the fact that the contents of the file are indeed for a globalconfig, not an editorconfig. Can you file a separate issue on Roslyn repo OR send a fix? Thanks!

**Comment by joegoldman2** [comment]
> Below properties need to be bumped up by one version:

Would you want me to send a PR or do you have a dedicated process for this bump?

> Can you file a separate issue on Roslyn repo OR send a fix? Thanks!

I can send a PR for the name of the generated file!

**Comment by joegoldman2** [comment]
I don't see any automatic process in place to update `_LatestAnalysisLevel`, `_PreviewAnalysisLevel` and

https://github.com/dotnet/sdk/blob/91a440681da35b13a1528bd6dcf35c64a2c221ab/test/Microsoft.NET.TestFramework/ToolsetInfo.cs#L11-L14

I can create a PR if you want.
