### ISSUE TITLE
<PrivateAssets>All</PrivateAssets> still puts dll into publish directory

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#376]
Related to https://github.com/dotnet/cli/issues/2024
Related to https://github.com/dotnet/sdk/issues/42

[r2024.tar.gz](https://github.com/dotnet/sdk/files/582430/r2024.tar.gz)

Repro attached.

In this project NewtonSoft.json is included with the reference:

```
    <PackageReference Include="NewtonSoft.Json">
      <Version>9.0.1</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```

However, publish still puts the dll into the publish directory.

/CC @davidfowl who opened the original issue against CLI

**Comment by dsplaisted** [comment]
I'm still investigating, but it looks like this is an issue where we're not correctly ignoring the casing.  Change `NewtonSoft.Json` to `Newtonsoft.Json` and it should be correctly excluded from publish.
