### ISSUE TITLE
Containers: extend environment variables for passing registry credentials

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#37606]
### Is your feature request related to a problem?

Currently, the container tooling allows to pass a single username/password for registry authentication. This proposal is for enabling separate credentials for the pull and push registry.

### Describe the solution you'd like

Use the existing variables `SDK_CONTAINER_REGISTRY_UNAME`, `SDK_CONTAINER_REGISTRY_PWORD` for the registry the application image is pushed to.

Add new `SDK_CONTAINER_PULL_REGISTRY_UNAME`, `SDK_CONTAINER_PULL_REGISTRY_PWORD` for registry the base images are pulled from.

For backwards compatibility, the pull registry environment variables default to the push registry environment variables when the push and pull registries are the same.

cc @baronfel @richlander

**Comment by baronfel** [comment]
This is a reasonable change (though my own preference is to not use the environment variables as much as possible).

**Comment by richlander** [comment]
`PULL_REGISTRY` feels a bit odd to me. I wonder if `SOURCE` is better than `PULL`.

I'm fine with ENVs. A more general config system would be a nice alternative. Is that something we can consider for this release?

**Comment by baronfel** [comment]
+1 To Rich's naming comment - if we could use 'source' and 'target' names for the registries that would be great.

@richlander Re: a general config system, what kind/scope of configuration are you thinking here? Other tools have yaml/ini style files for describing the modifications necessary, but we've been leaning into MSBuild for at least the project-centric side of those container modifications.

**Comment by richlander** [comment]
Here's an example to consider for a config system: https://github.com/dotnet/sdk/issues/36072

**Comment by richlander** [comment]
Haven't relied more on registry PATs since my last comment, I do see that `PUSH` and `PULL` show up quite prominently.

**Comment by MichalPavlik** [comment]
@tmds, I believe we resolved it some time ago and we forgot about this issue. Please reopen if I'm mistaken.
