### ISSUE TITLE
The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#3762]
_From @DataTables on Thursday, October 17, 2019 10:16:11 AM_

### Describe the bug

When adding .NET Core 3.0 to a multi-targeted project I'm getting the error:

> error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

I've followed the [porting guide here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio) but have been unable to resolve the issue. It looks like this also also been raised in [other issues](https://github.com/aspnet/AspNetCore/issues/4490), but the indications there are that this was an issue during the previews and should now be resolved.

### To Reproduce
1) Clone into [this repo](https://github.com/DataTables/Editor-NET) which is the one I'm trying to add .NET Core 3.0 build support to.
2) Update the DataTables-Editor-Server.csproj file to target .NET Core 3.0:

```
<TargetFrameworks>netcoreapp2.1;netcoreapp3.0;net45;net46;net47</TargetFrameworks>
```

and add:

```
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.CSharp">
      <Version>4.6.0</Version>
    </PackageReference>
  </ItemGroup>
```

3) Run `msbuild DataTables.sln` - observe errors for .NET Core 3.0 build.

The [documentation here](https://docs.microsoft.com/en-gb/dotnet/core/tools/csproj#implicit-package-references) notes that `Microsoft.AspNetCore.App"` is implicit and doesn't need to be included, but the migration guide says it should if the SDK is `Microsoft.NET.Sdk` which I've been using.

### Expected behavior
dll targeting .NET Core 3.0 will be build along with the others.

### Additional context

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     fedora
 OS Version:  27
 OS Platform: Linux
 RID:         fedora.27-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.505 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Installation for .NET Core (and Framework via mono) build in Fedora was:

```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
wget -q https://packages.microsoft.com/config/fedora/27/prod.repo
sudo mv prod.repo /etc/yum.repos.d/microsoft-prod.repo
sudo chown root:root /etc/yum.repos.d/microsoft-prod.repo

sudo dnf install -y aspnetcore-runtime-2.1
sudo dnf install -y dotnet-sdk-2.1-2.1.505

sudo dnf install -y aspnetcore-runtime-3.0
sudo dnf install -y dotnet-sdk-3.0

# .NET Framework via Mono
sudo rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
sudo curl https://download.mono-project.com/repo/centos7-stable.repo | sudo tee /etc/yum.repos.d/mono-centos7-stable.repo
sudo dnf install -y mono-devel mono-complete xsp msbuild
```

_Copied from original issue: aspnet/AspNetCore#15107_

**Comment by pranavkm** [comment]
_From @pranavkm on Thursday, October 17, 2019 4:34:38 PM_

@nguerrera \ @dsplaisted any guesses what could be wrong?

@DataTables could you attach the binary build logs? You can get them by running `msbuild /bl` which produces an `msbuild.binlog` file

**Comment by pranavkm** [comment]
_From @DataTables on Thursday, October 17, 2019 8:30:09 PM_

Sure thing - attached is the the requested file.

[msbuild.binlog.zip](https://github.com/aspnet/AspNetCore/files/3741190/msbuild.binlog.zip)

**Comment by pranavkm** [comment]
Screenshot if it helps navigating this quicker:

![image](https://user-images.githubusercontent.com/174281/67048030-50315500-f0e8-11e9-8530-cada9d06d081.png)

**Comment by dsplaisted** [comment]
@DataTables I don't get that failure when I build.  I do get failures for what look like APIs that aren't part of the `FrameworkReference` in 3.0.

I see that you're building with Mono's version of MSBuild.  It's possible you need a more recent version.

What happens if you build with `dotnet build` (ie the .NET Core version of MSBuild that comes with the .NET Core SDK) instead of Mono's MSBuild?

**Comment by DataTables** [comment]
I was using Mono's version so I could compile the .NET Framework dll's as well. I've just tried `dotnet build` and if I update the preprocessor conditions from `NETCOREAPP2_1` to just `NETCOREAPP` it will build for both .NET Core 2.1 and 3.0.

I can script around needing to use Mono for the .NET Framework builds and `dotnet build` for the .NET Core ones. But is this a Mono bug then?

I've got:

```
$ msbuild -version
Microsoft (R) Build Engine version 16.3.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.300.19.41901
```

Which is the latest to install from `dnf` in Fedora.

**Comment by dsplaisted** [comment]
@KathleenDollard @mhutch Can you help clarify what version of Mono is needed to support the 3.0 SDK?

@DataTables You can use this package to support building projects targeting .NET Framework: https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/1.0.0-preview.2

**Comment by DataTables** [comment]
@dsplaisted That package is brilliant! Thank you for putting me on to that!

**Comment by mhutch** [comment]
+@radical

**Comment by livarcocc** [comment]
giving that things are working here now and it does seem like the issue was using an older version of Mono, I am going to close this issue.
