### ISSUE TITLE
[NETSDKE2E]With net9 sdk inserted, Running winforms/wpf failed in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#37657]
Repro steps:
1.install net9 alpha SDK(9.0.100-alpha.1.23625.1)
1.in CLI, dotnet new winforms or dotnet new wpf
2.dotnet run

Expected Result:
Run successfully

Actual Result
Run failed with below dialog.
![image](https://github.com/dotnet/sdk/assets/65637796/825cb642-d574-4183-b63c-cf94b286b04d)

dotnet --info:

**Comment by v-jieyan2** [comment]
This problem is also reproduced on Win ARM64.

**Comment by v-wuzhai** [comment]
This probably requires this PR: #37656

**Comment by vdanche** [comment]
This issue not repro on 9.0.100-alpha.1.23628.3(runtime-9.0.0-alpha.1.23621.6)
![image](https://github.com/dotnet/sdk/assets/65637796/fec24fe5-3f80-4caa-93f8-42c2d129ce24)
