### ISSUE TITLE
PublishSingleFile=true does not include Content files

### ISSUE THREAD

**Issue by pinkfloydx33** [dotnet/sdk#3765]
I am working with a (non-web) .NET Core 3.0 console application and I am trying to use `PublishSingleFile=true`. While the single-file aspect does indeed work (I get one executable file), my application always crashes due to missing appsettings.json files. I've tried setting the files to Content/None, Copy Always/Newest. I also tried adding `<CopyToPublishDirectory>true</CopyToPublishDirectory>` and yet nothing seems to work.

If I create a brand new fresh _Web_-SDK project, the single file publish works and the content files are dropped right next to the published executable. I tried comparing the starter web project to my console application and I don't see a difference.  

The easiest reproduction I have is to create a blank console application project, add a text file to the project (as content or `none`) and then publish with the PublishSingleFile=true. The output does not contain the content files. 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="MyContentFile.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
```

Is this supposed to work for non-Web projects?

> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100
>  Commit:    04339c3a26
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
> 
> Host (useful for support):
>   Version: 3.0.0
>   Commit:  95a0a61858
> 
> .NET Core SDKs installed:
>   3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
>   3.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by swaroop-sridhar** [comment]
Hi @pinkfloydx33  for in the case of `PublishSingleFile` all published content is bundled into the single-file. If we need files to be left behind in the publish directory, we need to set the `ExcludeFromSingleFile` property. In your example: 

```
    <Content Include="MyContentFile.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
     <ExcludeFromSingleFile>true</ExcludeFromSingleFile> 
    </Content>
```

For more details, please see: https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface

Dup of https://github.com/dotnet/core-setup/issues/7738

**Comment by livarcocc** [comment]
Closing as a dup.

**Comment by pinkfloydx33** [comment]
Thanks, I'm not sure how I missed that. Looking at the dupe I assume that the Web.SDK is automatically doing that (excluding) for AppSettings files? 

Based on the link and your comment above it also seems like *if* the file is bundled inside it should be extracted to a temp directory and then be available to the app. Is that correct? If so, the behavior I was encountering was a `FileNotFoundException` when attempting to read the bundled AppSettings file. Would that not be a bug? 

The [related links](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#related-work) list Costura and I know that project was only used for embedding (and accessing) referenced DLLs (via Assembly Load event handlers applied in the module initializer) so I would normally guess that text-based resources wouldn't apply except vitek's response on the dupe seems to imply otherwise.

**Comment by swaroop-sridhar** [comment]
>  I assume that the Web.SDK is automatically doing that (excluding) for AppSettings files?

Yes I believe this is true. 

> Based on the link and your comment above it also seems like if the file is bundled inside it should be extracted to a temp directory and then be available to the app. Is that correct? If so, the behavior I was encountering was a FileNotFoundException when attempting to read the bundled AppSettings file. Would that not be a bug?

 The app's project file/build dictates where files end up (bundled or not). Consequently, apps need to load the files from the correct location -- If bundled, from the extraction directory (accessibly via `AppContext.BaseDirectory`) ; otherwise typically next to the host binary. I don't think this is a host bug.

> The related links list Costura and I know that project was only used for embedding (and accessing) referenced DLLs (via Assembly Load event handlers applied in the module initializer) so I would normally guess that text-based resources wouldn't apply except vitek's response on the dupe seems to imply otherwise.

I'm not sure which comment you're referring to here. My understanding is that Costura embeds only binaries (managed and unmanaged).

**Comment by mohamedhamza7** [comment]
Dears,
Is there is a way to excluded Package Reference DLLs from being bundled in single file application? 
I am working on WPF application .NET 5.0
