### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80070008

### ISSUE THREAD

**Issue by tonyctp** [dotnet/sdk#37661]
### Describe the bug
Docker file as below -- as simple as possible
```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN dotnet --version
```
will throw exception like
Failed to create CoreCLR, HRESULT: 0x80070008

### To Reproduce
Docker version:  Docker version 20.10.22, build 3a2c30b
SDK : mcr.microsoft.com/dotnet/sdk                       8.0               8c5c87a41139   7 days ago      836MB

using the docker file mentioned up 

### Exceptions (if any)
```
Digest: sha256:0b4b20f78ab869a9fa6a8496053b4e2cb7339b8f748775c8c502f8eb7f2d8576
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:8.0
 ---> 8c5c87a41139
Step 2/7 : WORKDIR /src
 ---> Running in 8c2515e20ae8
Removing intermediate container 8c2515e20ae8
 ---> 7af77ccbe27a
Step 3/7 : RUN dotnet --version
 ---> Running in 9fe5236f5913
Failed to create CoreCLR, HRESULT: 0x80070008
The command '/bin/sh -c dotnet --version' returned a non-zero code: 137
exit status 137
```

### Further technical details
the same docker file works fine in sdk:7.0 but when i udpate to sdk:8.0 it failed.
![Screenshot 2023-12-26 235811](https://github.com/dotnet/sdk/assets/28466130/f6afa2c1-cad9-4c64-9c41-2cbc7204e197)

**Comment by qzwzqty** [comment]
@tonyctp  Hello, I have the same problem,  How did you fix it?

**Comment by jkanamar** [comment]
> @tonyctp Hello, I have the same problem, How did you fix it?

I have the same problem as well. Are you able to fix it?
