### ISSUE TITLE
Question: State of C++/CLI with dotnet

### ISSUE THREAD

**Issue by cdecompilador** [dotnet/sdk#37667]
As I currently understand even though **dotnet cli** works very well with CLR family languages, when it comes to C++ its tightly bound to Visual Studio still, mainly because `.vcxproj` doesn't have all the default built-in behaviour, props and targets that `.csproj` and `.fsproj` have. 

My question is about the current planning of C++ (and C, MASM by extension) on the open source space, and if it will be included as a main part of the SDK in the future and not as an optional extension that only works with Visual Studio.

**Comment by marcpopMSFT** [comment]
I'm not aware of any planned investments in improving the dotnet CLI experience for c++ or C++/cli projects. Including
@olgaark @lukka to commnet.

**Comment by cdecompilador** [comment]
thanks for your time
