### ISSUE TITLE
maybe just leave it as is as it's fine on 12. The only reason we moved some to 13 is that there wasn't enough infrastructure on branding day to support all branches on 12.

### ISSUE THREAD

**Issue by TacoLoverTacoKing** [dotnet/sdk#37698]
maybe just leave it as is as it's fine on 12. The only reason we moved some to 13 is that there wasn't enough infrastructure on branding day to support all branches on 12.

_Originally posted by @marcpopMSFT in https://github.com/dotnet/sdk/issues/33783#issuecomment-1644540189_

**Comment by baronfel** [comment]
Closing this as it's not actionable.
