### ISSUE TITLE
Port remove signature on MAC host to 2.x SDK

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#3773]
https://github.com/dotnet/core-setup/pull/8543#event-2725838361

get it in January train

- [x] 2.1.5xx SDK(dotnet build create apphost)
- [x] 2.1.5xx CLI (global tools)
- [x] Insert CLI to SDK 2.1.5xx https://github.com/dotnet/cli/pull/13027
- [x] 2.1.6xx SDK https://github.com/dotnet/sdk/pull/3861
- [x] 2.1.6xx CLI https://github.com/dotnet/cli/pull/13028
- [x] Insert CLI to SDK 2.1.6xx https://github.com/dotnet/cli/pull/13031

**Comment by wli3** [comment]
I realize in 2.x, the writing apphost code is duplicated in SDK and CLI repo (which is fixed by the Microsoft.NET.HostModel in 3.0.100) that means the [macoutils](https://github.com/swaroop-sridhar/core-setup/blob/3943391a8a9e7d9718199f44f8d399f69d5dcaa1/src/managed/Microsoft.NET.HostModel/AppHost/MachOUtils.cs) will be duplicated in 2 repo.

Alternative is to port the class to 2.x core-setup as well and let both SDK and CLI reference HostModel. However that would require making MachOUtils public instead of internal.

I prefer just duplicate it in 2 places considering it is unlikely to have more activity. @nguerrera @swaroop-sridhar

**Comment by nguerrera** [comment]
Yeah we already agreed we’d just copy to all places in 2.x

**Comment by wli3** [comment]
all done! close
