### ISSUE TITLE
Question: is there a way to get the CLR runtime info

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#37813]
Could I get whether I'm running on Mono or the CoreCLR in C# code?

**Comment by ViktorHofer** [comment]
Here's what we do in runtime: https://github.com/dotnet/runtime/blob/abffa8fd7c9a9eaaaba70ca8052d605b85918bd4/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L30

**Comment by WeihanLi** [comment]
thanks very much
