### ISSUE TITLE
[Workload Sets] ensure that users can get a full listing of all installed workloads (including multiple versions)

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#37828]
### Is your feature request related to a problem? Please describe.

When running `dotnet workload list`/`dotnet workload --info` we need to ensure that users can see

* the version of workloads installed in the current context (which is dictated by global.json)
  * if influenced by a global.json we should show that
* the version(s) of workloads installed for all 'contexts' (essentially a view of the install state)

Currently, users only see the latest installed workloads based on the global.json:

![image](https://github.com/dotnet/sdk/assets/573979/ee0a2dcf-e23f-4437-9058-ecb92527798c)

### Describe the solution you'd like
A flag on `workload list`/`workload --info` that provides all versions of each workload installed across the install state, and clarifies where global.json has influenced the selection of some of those versions.

**Comment by Forgind** [comment]
For clarity, when you say "across the install state," are you talking about the literal install state file, or are you talking about the state of all workloads installed? The install state file doesn't itself list out all possible sets of manifests the user might care about; in fact, it often wouldn't have anything interesting on that front at all unless something is pinned.

How are you thinking this information should be organized?
