### ISSUE TITLE
Remove workarounds for files not adding themselves to MSBuildAllProjects property

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#380]
Once the following bugs are fixed, we should remove the workarounds for them in the `GivenThatWeWantToBuildALibrary.All_props_and_targets_add_themselves_to_MSBuildAllTargets` test:

- NuGet/Home#3851
- Microsoft/msbuild#1298
- dotnet/cli#4571
- dotnet/roslyn#14870

**Comment by jeffkl** [comment]
In MSBuild 16.0, this won't be necessary any more.

Microsoft/msbuild#3605

Will the latest .NET Core SDK have to work with older versions of MSBuild?  If not, I can send a PR to remove all the places where MSBuildAllProjects is set to reduce memory use during evaluation.

**Comment by jeffkl** [comment]
Gentle ping...

**Comment by nguerrera** [comment]
This is obsolete. We no longer need to put things in msbuildallprojects, and in fact, we shouldn’t.
