### ISSUE TITLE
dotnet-install SDK scripts on Alpine 3.8 Powershell image "Architecture not supported" 

### ISSUE THREAD

**Issue by lantrix** [dotnet/sdk#3800]
## Steps to reproduce

```bash
$ docker run -it mcr.microsoft.com/powershell:6.2.3-alpine-3.8
PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS /> &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel LTS
Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/cli/issues
At line:169 char:19
+ CategoryInfo          : OperationStopped: (Architecture not su\u2026m/dotnet/cli/issues:String) [], RuntimeException
+ FullyQualifiedErrorId : Architecture not supported. If you think this is a bug, report it at https://github.com/dotnet/cli/issues

PS />
```

## Expected behavior

I can use the official [dotnet-install script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) to install dotnet SDK LTS in the official powershell6 alpine container.

The [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore21#supported-linux-versions) lists Alpine 3.7+ as supported for .NET core 2.1.

## Actual behavior

`Architecture not supported.`

## Environment data

Docker image tag `6.2.3-alpine-3.8` or `alpine-3.8` for the official [PowerShell Docker image](https://hub.docker.com/_/microsoft-powershell).

```Powershell
PS /> cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.4
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by johnbeisner** [comment]
The Linux and MacOS install-script can be found here: https://dot.net/v1/dotnet-install.sh

**Comment by lantrix** [comment]
That's what I'm using. The top of the page you referenced states:

> Name
`dotnet-install.ps1` | `dotnet-install.sh` - Script used to install the .NET Core CLI tools and the shared runtime.

I invoked `https://dot.net/v1/dotnet-install.ps1` in one of the official PowerShell 6 docker containers, Alpine 3.8

The supported OS versions for .NET Core [2.1](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md) still lists Alpine 3.7+ but clearly doesn't work.

**Comment by lantrix** [comment]
In the end it was easier to do a docker build with the [Dockerfile](https://gist.github.com/lantrix/1c0b23813213973857c276392eee74d1) building upon the Powershell alpine base image and installing the latest DotNet Core 2.1.

I then get a valid runtime of Dotnet Core 2.1 on Alpin Linux of the official PowerShell image.

This worked for a perfect build environment for publishing PowerShell 6 on AWS Lambda.
