### ISSUE TITLE
[Regression] APICompat / PackageValidation runs without a runtime graph

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#38013]
When invoking APICompat's `ValidatePackageTask` msbuild task, the runtime graph is expected to be passed in so that the nearest runtime specific package asset can be resolved. I just noticed that since https://github.com/dotnet/sdk/commit/1df8f4f2ea2f23e479e6bb8bcc994da12d402222 this is no longer the case since the `RuntimeIdentifierGraphPath` property isn't defined in cross-targeting builds anymore (as it got moved into Microsoft.NET.Sdk.targets). 

https://github.com/dotnet/sdk/blob/bfd2919bc446cad68d11de90cec4025d3683591c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets#L41

<img width="517" alt="image" src="https://github.com/dotnet/sdk/assets/7412651/f15d054f-b22a-4978-ad98-33910c8aba1a">

Apparently there aren't any package validation tests running in CI that exercise this code path / behavior.

cc @ericstj @dsplaisted

**Comment by ericstj** [comment]
Could we use `BundledRuntimeIdentifierGraphFile` here instead?

**Comment by ViktorHofer** [comment]
Yes that would be possible but it would bypass the new RID graph selection that got added with https://github.com/dotnet/sdk/commit/1df8f4f2ea2f23e479e6bb8bcc994da12d402222 and always choose the non portable one. I don't think APICompat should stays on the old one without a good reason. Also, we plan to remove the non portable RID graph with either .NET 9 or .NET 10.

@dsplaisted Can we move the `RuntimeIdentifierGraphPath` property back to a location that is available in the outer build? PackageValidation runs in that mode when multi-targeting (as it runs after the `Pack` task) and needs access to that property.

**Comment by dsplaisted** [comment]
The `RuntimeIdentifierGraphPath` depends on the `TargetFramework` value to determine whether it should use the "portable" RID graph or the older, bigger one.  Would it be OK to default to the portable one in the outer build where the TargetFramework isn't set?

**Comment by ViktorHofer** [comment]
Yes, that should be fine. I would expect us to move that currently TFM specific logic to that location as well when we remove the legacy RID graph. Does that make sense?
