### ISSUE TITLE
Error when working directory is drive root

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#38050]
We have seen multiple cases where `dotnet restore` times out with an unrecoverable error when the user places an app at OS root. This is easy to do in containers/Dockerfile and is hard to diagnose. It's also not a useful pattern.

`dotnet build` and friends (`restore`, `publish`, `test`, ...) should fail when run at drive root. We can offer a `--force` command to override this case, however, that may not be necessary.

Context: https://github.com/NuGet/Home/issues/13131

**Comment by Forgind** [comment]
Thanks for the report @richlander. From what you've seen, is this "common" (fix soon; real customer pain) or "uncommon" (try to get around to it, but it isn't a top priority)?

**Comment by Forgind** [comment]
I imagine the priority is a big higher than it otherwise would be since containers are a growing area, but I haven't seen any of the user data myself.

**Comment by richlander** [comment]
It is common enough. I've done this multiple times. It is very easy to do with Dockerfiles.

This isn't a rush. It would be great to get the fix into  8.0.400 (and 9.0), for example.

**Comment by Forgind** [comment]
Sounds good!

**Comment by richlander** [comment]
If you want to try this yourself, make a Dockerfile and `COPY` source into an `sdk` container, build, but forget to set `WORKDIR`. That's the bad pattern.

**Comment by richlander** [comment]
Thanks! I look forward to trying this. I should be able to work this into a container related blog post.
