### ISSUE TITLE
error when using dotnet tool install

### ISSUE THREAD

**Issue by bigworld12** [dotnet/sdk#3806]
I get this error when running `dotnet tool install -g dotnet-ef`
dotnet version : 3.1.100-preview1-014459
```
Failed to install tool package 'dotnet-ef': Could not find a part of the path 'C:\Users\UserName\.dotnet\tools\.store\.stage\32ksqkap.ndq\dotnet-ef'.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
Note : this works perfectly in 3.0.100

**Comment by wli3** [comment]
Thank you for the issue.

What happens if you try again? And could you make sure the folder C:\Users\UserName\.dotnet is accessible?

**Comment by bigworld12** [comment]
the folder itself is accessible, since I managed to install the same package on 3.0.100

**Comment by wli3** [comment]
Could you retry it?

**Comment by bigworld12** [comment]
if by retry it, you mean tried executing the same command on 3.1.100 multiple times, then yes

**Comment by wli3** [comment]
I cannot repro this issue. Does the error message contain the same "32ksqkap.ndq" part? it should be different every time. And could you try to delete your `C:\Users\UserName\.dotnet\tools\.store\.stage` folder and see if the error persists?

**Comment by bigworld12** [comment]
yes it's indeed a different part every time, 
i tried deleting it, and the error still persists

**Comment by wli3** [comment]
Could you try to use the latest dotnet core sdk from https://github.com/dotnet/core-sdk  ?

This code did not change from 3.0.100 to 3.1.100, but it fails on later. It also does not fail on my current version "3.1.100-preview2-014531". So I suspect there is a change in runtime, and might has already been fixed.

**Comment by bigworld12** [comment]
i can confirm it works on `5.0.100-alpha1-015462` sdk

**Comment by wli3** [comment]
Thanks! so it should be fixed in the next preview
