### ISSUE TITLE
[NETSDKE2E][ARM64] With .NET 9 alpha SDK installed, installing android workload or workload restore failed with error.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#38095]
Repro steps:

1.Install the latest .NET 9 arm64 SDK from https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-arm64.exe
2.Install android workload using below command in CLI
`dotnet workload install android`

Expected Result:
Workload can be installed successfully.

Actual Result:
It failed with the following error:
![image](https://github.com/dotnet/sdk/assets/106054229/9f91ea6a-ac19-4cd9-8854-f4349b7f2431)

Note:
already add feed:
```
<add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
<add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
```

--Error Log--
Workload installation failed: One or more errors occurred. (Version 9.0.0-alpha.1.24066.33 of package microsoft.netcore.app.runtime.aot.win-arm64.cross.android-x86.msi.arm64 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json".)

**Comment by v-ainigao** [comment]
with .net9.0.100-preview.1.24101.2 (runtime-9.0.0-preview.1.24080.9)SDK installed, below errors happen after installing android or maui in CLI.
<img width="481" alt="image" src="https://github.com/dotnet/sdk/assets/106054229/d18dc31b-9c49-4fc7-98f7-55f27a1204cc">

**Comment by marcpopMSFT** [comment]
@lewing to look for that particular package. I know the Maui team is testing their scenarios with p1 so something seems off here. Maybe there's a bad pack dependency on arm64? @jonathanpeppers

**Comment by lewing** [comment]
the fix for the dailies is stuck i. sdk->installer flow

**Comment by lewing** [comment]
> the fix for the dailies is stuck in sdk->installer flow

oh wait, different issue.  @steveisok are we producing those arm64 packs? are they new?

**Comment by steveisok** [comment]
@joeloff I am not seeing corresponding msi's for `win-arm64.cross.android-<arch>` packs. Is there something wrong with the workload build in picking these up?

**Comment by lewing** [comment]
I suspect https://github.com/dotnet/runtime/pull/98061 is the problem

**Comment by lewing** [comment]
> I suspect [dotnet/runtime#98061](https://github.com/dotnet/runtime/pull/98061) is the problem

This has merged so we this should be resolved in preview 2

**Comment by lewing** [comment]
https://github.com/dotnet/installer/pull/18457 needs to merge before the daily build will include this fix

**Comment by v-ainigao** [comment]
This issue has been fixed on .net9.0.100-preview.2.24116.21 (runtime- 9.0.0-preview.2.24115.1), thanks.
![image](https://github.com/dotnet/sdk/assets/106054229/ed629cd6-4d85-4159-978a-0cf5493c90e2)
