### ISSUE TITLE
GenAPI drops ref keyword when generating reference source for System.Memory/4.5.5

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#38166]
![image](https://github.com/dotnet/sdk/assets/7412651/e795a5d5-3153-4e93-bfcf-ba8a58324683)

Repro: `./generate.sh --package System.Memory,4.5.5
Observe changes in src/referencePackages/src/system.memory/4.5.5/lib/netstandard2.0/System.Memory.cs

GenAPI drops the `ref` keyword from structs like `ReadOnlySpan<T>`.

cc @ericstj

**Comment by ericstj** [comment]
That's odd - it should treat it as ref - though in this case it looks like the assembly defined `IsByRefLikeAttribute` internally so that could be causing things to get tripped up.

**Comment by ericstj** [comment]
Hmm, I see plenty of evidence that this never worked, but I'm at a loss for why not.  I see the bug in roslyn that we need to fix to support it, so I'll give that a try and see if I run into any problems.

**Comment by ericstj** [comment]
This was fixed in https://github.com/dotnet/sdk/pull/38179.  We'll be able to remove the workaround that added when we ingest the new roslyn with the fix.

**Comment by ViktorHofer** [comment]
Source-build might be building against the very latest roslyn. Do we need to adjust the code path for source-build only?

**Comment by ViktorHofer** [comment]
Actually disregard. For GenAPI, source-build and non source-build both use the very latest roslyn so we shouldn't get into an inconsistent state between build variants.

**Comment by ericstj** [comment]
I made this work so that it's OK if a newer roslyn meets up before we remove the assert, the assert should only pop during testing.
