### ISSUE TITLE
Manage and Build multiple projects without Visual Studio File (SLN)

### ISSUE THREAD

**Issue by jtillman** [dotnet/sdk#3816]
I propose that we provide a builtin way to run dotnet cli commands on multiple projects without having to share Visual Studio (Sln) files across users.

Issues: The solution file (.sln) is controlled and managed by Visual Studio IDE. It's format isn't DRY and editable by hand. All users do not use or desire to use Visual Studio to develop dotnet applications. You currently have to use the dotnet cli to update it. 

Proposals:
- `dotnet cli` commands which take solution files. `dotnet pack **/*.csproj'
- Add `dotnet projects` command which internally creates a solution file on the fly to execute the desired commands in the background. 
This would be a convention-based command which discovers all .csproj in the directory recursively. This is my favorite because it has automatic project discovery just like new SDK projects discover all `.cs` files.

**Comment by livarcocc** [comment]
This is not something that we plan to do at the moment. We take deviations from other parts of the tooling very carefully because we do have a huge customer base that uses both CLI/VS/VSM, etc that get very confused when the experiences break.

**Comment by jtillman** [comment]
I don't think this takes away from those who do use the VS experience. It just seems like an antipattern to force all teams to adopt it. Can this be thought of as another pattern where those dependencies are hidden/removed? I think the second option actually sticks within the same tooling but doesn't expose it to the user.

**Comment by jtillman** [comment]
I just found the Traversal SDK in the MSBuild project. I think this should be the default in how we advertise the build system.

https://github.com/microsoft/MSBuildSdks/tree/master/src/Traversal

**Comment by buvinghausen** [comment]
@jtillman thanks for sharing the link that is perfect for my use case.   In the event someone else winds up here it's not real clear from the Traversal [README.md](https://github.com/microsoft/MSBuildSdks/blob/main/src/Traversal/README.md) but you need to add a global.json with the following payload and then dotnet build will use the SDK build the proj files as described in the readme.

```json
{
  "msbuild-sdks": {
    "Microsoft.Build.Traversal": "3.0.23"
  }
}
```
