### ISSUE TITLE
Don't add NeutralResourcesLanguageAttribute to AssemblyInfo when no embedded resources are used

### ISSUE THREAD

**Issue by dasMulli** [dotnet/sdk#382]
Currently, the generated AssemblyInfo will always include a `NeutralResourcesLanguageAttribute` by default. This is an issue when creating a minimum dependency package without using embedded resources (e.g. just referencing `System.Runtime` for `netstandard1.0` - see attached example). The approach of building packages/libraries with minimum dependencies is still recommended for targeting `netstandard` < 2.0.

Although it is totally possible to set the `GenerateNeutralResourcesLanguageAttribute` property to false, it isn't (yet) documented very visibly and not immediately obvious.

I feel that no dependency on `System.Resources.ResourceManager` should be required by default so I propose to not emit the attribute if no `EmbeddedResource` item exists. The `project.json` tooling also did not emit the attribute.

[example.zip](https://github.com/dotnet/sdk/files/585100/example.zip)

**Comment by nguerrera** [comment]
With #466, you'll only get an attribute if you set NeutralLanguage explicit. I think this is sufficient to fix this. 

@dasMulli Would you agree?

**Comment by dasMulli** [comment]
Absolutely!
