### ISSUE TITLE
.NET Core SDK 3.0.100 does not have 2.2.8 or 2.1.14 patch.

### ISSUE THREAD

**Issue by Jepson109** [dotnet/sdk#3825]
Use [16.3.7](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvsdrop.corp.microsoft.com%2Ffile%2Fv1%2FProducts%2FDevDiv%2FVS%2F25bf803db756771ac937046faacdbec8278347ff%2F4c2b3062-352a-8f22-0b64-8a1bb9b21401%253bchannels%2Finternal%2FRelease%2Fbootstrappers%2Ffixed%2FEnterprise%2Fvs_Enterprise.exe&data=02%7C01%7Cv-pejian%40microsoft.com%7C564144298f6a4146a3ad08d75d1647d4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637080222644789581&sdata=MJNpQBnniMAGpWiPZfl4dkFjjNpTTh9QaKZ0mQ7BMMo%3D&reserved=0) [29429.51.d16.3] (SDK 3.0.100 with 2.2.8 and 2.1.14  runtime inserted)

**Repro Steps**:
1.	dotnet new global.json
2.	edit global.json, check the SDK version is "3.0.100"
3.	mkdir test
4.	cd test
5.	dotnet new console
6.	edit test.csproj and set TargetFramework from netcoreapp3.0 to netcoreapp2.2
7.	dotnet publish -r win10-x64
8.	check the contents of bin\Debug\netcoreapp2.2\win10-x64\publish, search for “Microsoft.NETCore.App/” 

**Expected**: That version is 2.2.8.

**Actual**: The version is **2.2.7**.

Note: Using SDK 3.0.100, retarget app to netcoreapp2.1 and look for the version for “Microsoft.NETCore.App” is 2.1.13, not 2.1.14.

**dotnet --info**:
.NET Core SDK (reflecting any global.json):
Version:   3.0.100
Commit:    04339c3a26

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.17763
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
@nguerrera can you address this for our next servicing release?

**Comment by nguerrera** [comment]
This was fixed.
