### ISSUE TITLE
Unable to Publish .NET7 & .NET8 windows Azure Function App in windows 2022 server

### ISSUE THREAD

**Issue by NAVEENNL** [dotnet/sdk#38281]
Steps to reproduce:

Create .NET8 Azure function App and try to publish hitting below error.

Error Details:

Unable to move file "C:\<UserName>AppData\Local\Temp\4uom52pi.odd\publishout\Microsoft.AspNetCore.Authentication.Abstractions.dll" to "C:\<UserName>\AppData\Local\Temp\4uom52pi.odd\publishout\bin\Microsoft.AspNetCore.Authentication.Abstractions.dll". Cannot create a file when that file already exists.

**Comment by baronfel** [comment]
@NAVEENNL are you using the azure functions dotnet worker?  if so, there's a preview version of that SDK that the Azure functions teams things should solve this issue: https://github.com/Azure/azure-functions-dotnet-worker/pull/1946

**Comment by NAVEENNL** [comment]
Thanks @baronfel

Its working with preview version. Hence closing this.
