### ISSUE TITLE
赶快把还原到.Net6 版本的支持！！！！！！！！你们和他妈傻逼一样，老子用.Net6 写了项目上线正式环境，你们更新把.net6 强制移除了，必须更新.net8.老子他妈的项目，现在出问题了，打不开。换到.net8 打包好了，客户机器上又打不开。

### ISSUE THREAD

**Issue by blackcatpolice** [dotnet/sdk#38285]
你们和他妈傻逼一样，老子用.Net6 写了项目上线正式环境，你们更新把.net6 强制移除了，必须更新.net8.老子他妈的项目，现在出问题了，打不开。换到.net8 打包好了，客户机器上又打不开。

赶快把还原到.Net6 版本的支持！！！！！！！！

**Comment by blackcatpolice** [comment]
![image](https://github.com/dotnet/sdk/assets/4312114/eb53d287-4afd-4268-9b2e-9ea0b77e293e)

**Comment by blackcatpolice** [comment]
![image](https://github.com/dotnet/sdk/assets/4312114/676aed0c-4a13-485a-9449-148f2cc3c002)

**Comment by blackcatpolice** [comment]
你们vs 团队 连个客服都没有，打个客服电话全是你妈的机器人，机器人我要你电话干嘛，傻逼，白瞎了那么高市值

**Comment by blackcatpolice** [comment]
你更新到.net 8 了你决定你们牛逼了，vs 在客户机器上 启动项目都启动不了，也他妈不报错。真觉得你一个破项目写两年就完善了？ 就尼玛的强制更新到.net8 ? 谁给你们的勇气。草泥马的

**Comment by blackcatpolice** [comment]
你他妈的当别人用你们的框架在那写测试代码呢？ 随随便便就大改动。 文档都是测试文档，连怎么申请证书都没有。

**Comment by KieranFoot** [comment]
Surely this violates the code of conduct?!

**Comment by baronfel** [comment]
I've translated the messages and I agree. I'll close this.
