### ISSUE TITLE
[WebToolsE2E][Aspire] After installing .NET SDK 9.0, the 'microsoft.net.sdk.aspire' folder is not included by default and needs to be manually updated workload using CLI to appear.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/sdk#38284]
**REGRESSION INFO**: Not repro on SDK 8.0

**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU
Install the latest .NET SDK 9.0 Preview 1

**REPRO STEPS**

1. Go to 'C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1', no 'microsoft.net.sdk.aspire' folder

**Notes:**

1. If I only install the .NET 8 SDK, which includes the 'microsoft.net.sdk.aspire' folder by default
2. After installing .NET SDK 9.0, there are two folders in 'sdk-manifests' folder. The 'microsoft.net.sdk.aspire' is included by default under the 9.0.100-alpha.1 folder, but not under 9.0.100-preview.1
![image](https://github.com/dotnet/sdk/assets/71361488/0e1ed9e1-0ab0-4f02-a195-4923565abfe9)
3. For this issue, if I update workload using CLI, the 'microsoft.net.sdk.aspire' folder will show up in the 9.0.100-preview.1 folder

**ACTUAL**

No 'microsoft.net.sdk.aspire' folder in 9.0.100-preview.1 folder
![image](https://github.com/dotnet/sdk/assets/71361488/e59af3c0-9e54-48b5-a266-ff3a89156e6e)

**EXPECTED**

![image](https://github.com/dotnet/sdk/assets/71361488/16cbc656-d6a7-43a0-8ba5-6981da013567)

**Comment by joperezr** [comment]
Yes, thanks for reporting. This is expected, and shouldn't be an issue. Our Aspire 9.0 workload is still shipping alpha.1 versions but that has now been fixed in the dev branch, and that change will soon be ingested in installer, which will make this go away.

**Comment by v-sherryfan** [comment]
Closed this issue as expected.

**Comment by v-elenafeng** [comment]
Verified on SDK 9.0 P2: The 9.0.0-preview.2 manifest is in 9.0.0-preview.1 folder which is expected.
