### ISSUE TITLE
dotnet-ef 8.0.1 fails to work on .NET 8.0.0

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#38334]
The `dotnet-ef` package that is published for 8.0.1 requires the runtime version to be at least 8.0.1.

On some environments, like distros where .NET is source-built, it may take some days(/weeks) for that runtime version to become available.

This makes the `dotnet install -g dotnet-ef` command work, but subsequently invoking `dotnet ef` fail (due to the runtime version). The user can work around by explicitly specify the older version that matches the runtime version.

Could we relax the required runtime version for the global tools that are shipped in tandem with .NET through NuGet to not depend on a particular patch version?

cc @baronfel @richlander

**Comment by baronfel** [comment]
cc @ajcvickers this has come up a few times since the 8.0.1 release (see https://github.com/dotnet/sdk/issues/38114 for another instance). 

This is possibly something we could detect at tool-install time now too, now that we are no longer using the implicit NuGet Restore to acquire tools.

**Comment by ajcvickers** [comment]
@baronfel This looks like https://github.com/dotnet/efcore/pull/32869, which is already approved for 8.0.3.

**Comment by tmds** [comment]
Great! I'll close this then.
