### ISSUE TITLE
visualstudio code support for Microsoft.VisualStudio.JavaScript.Sdk

### ISSUE THREAD

**Issue by lucadistefano** [dotnet/sdk#38377]
I use visualstudio on windows with a solution that use .net core projects and a node with react-native project.
This project uses Microsoft.VisualStudio.JavaScript.Sdk . 
On Visual Studio Code this kind of project is not supported.

Support Microsoft.VisualStudio.JavaScript.Sdk in visualstudio code in order to be able to develop this kind of project/solution on macos.

### Additional context
<img width="337" alt="image" src="https://github.com/dotnet/sdk/assets/1080723/e540ef35-9820-41ef-8cf9-da6230774895">

**Comment by baronfel** [comment]
@lucadistefano please reopen this at https://github.com/microsoft/vscode-dotnettools, where the Dev Kit extension is managed.
