### ISSUE TITLE
Generating satellite assemblies causes a lot of unnecessary work 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#38478]
### Describe the bug

The `GenerateSatelliteAssembliesForCore` task works today by using the C# compiler to produce satellite images. There is a small amount of code associated with this, mostly a single file with a number of assembly attributes. Because there is code though the compiler must be provided with a set of references and the build simply passes along the reference set for the original project. 

As an individual decision that is quite reasonable but when it's applied to projects of scale it produces a lot of unnecessary work. Consider that even the simplest of .NET Core projects has in excess of 100 references. The average is in the neighborhood of 200 references. That means to compile a satellite assembly the compiler typically parsing 200+ references of which it needs one: corelib. 

This is exacerbated by a number of factors: 

- The satellite assemblies are generated for every target framework 
- Projects typically support 10+ languages 

This can very quickly lead to an incredible amount of unnecessary work in the compiler. 

Consider [dotnet/roslyn][dotnet-roslyn] as an example. The process of generating satellite assemblies causes us to process 172,068 references. The entire build uses 227,765 references so 75% of all references passed to the compiler, and processed by the compiler, are completely unnecessary. Yes the VBCSCompilerServer heavily caches references but it still causes a non-trivial amount of work in the compilr while also polluting the LRU cache with items that aren't actually used. That likely leads to cache inefficiency in later compilations in the build. 

Roslyn is getting here by having a very reasonable setup. There are about ~70 projects (when you iterate through project and their TF) and we support 14 localizations. That quickly adds up to ~1,000 satellite assemblies and with an average of just below 200 references per assembly we get to this incredible number. 

I really think we should reconsider how satellite assembly generation works. We must pass some reference to satellite assemblies for them to build but it does not need to be the full set provided to the parent. It really only needs to be a minimally viable corelib with common assembly level attributes. The `netstandard.dll` alone is more than enough. 

### To Reproduce

Build Roslyn.sln from the [dotnet/roslyn][dotnet-roslyn] repository: 

```cmd
> .\Build.cmd -restore -bl
```

Then examine the binary log and you can track through the csc invocations and their associated reference counts. 

[dotnet-roslyn]: https://github.com/dotnet/roslyn

**Comment by baronfel** [comment]
What's compiled for these resource files are the lines for the specific `SatelliteAssemblyAttribute` MSBuild Items, which are themselves primarily made via the `_GetAssemblyInfoFromTemplateFile` target. This target takes the primary dll for a project and scrapes the version, product, etc information from that to create these Satellite-specific attributes. As far as I can tell by searching GitHub, _no one_ is manually adding their own `SatelliteAssemblyAttribute` Items, we are in complete control here.

So I think we could massively trim down the set of reference passed here pretty safely.

**Comment by rainersigwald** [comment]
Does the SDK already have an item for "the core library"? It'd be nice to pass that, though filtering `@(ReferencePath)` down to "whichever one is corelib-esque" would probably work.

**Comment by baronfel** [comment]
@rainersigwald I was looking for that, but may need a smaller repro set than Roslyn, because it's impossible to search that binlog effectively :D

**Comment by jaredpar** [comment]
@agocke 

> The netstandard.dll alone is more than enough ...

That is a point in time assertion. Essentially the `netstandard.dll` from `netstandard2.0` is sufficient on its own to compile satellite assemblies today. It's meant to emphasize the inefficacy in our current approach. I am not confident, or honestly qualified, to state if it's a correct solution due to my lack of understanding of satellite assemblies at runtime.

> Is there anything more that runtime/libraries could do to help?

Give guidance on what a correct minimal solution is here. For example are there any perf concerns if we suddenly flip all satellite assembly to compile against `netstandard.dll` from `netstandard2.0`? That will certainly compile but will it cause any runtime performance issues? Suddenly the transitive set of assemblies for an app are not `net8.0` pure anymore because a `netstandard2.0` DLL got dropped into the mix. 

Is there a better DLL we could use here?

**Comment by agocke** [comment]
It seems reasonable to pick "just" the corelib DLL for the TFM of the project -- meaning `System.Runtime.dll` for Core, `netstandard.dll` for NETStandard 2.x, and `mscorlib` for Framework.

@AaronRobinsonMSFT @elinor-fung Any problems here you can think of? In each of these cases it still seems like we are compiling against ref assemblies, not impl-only assemblies, so there shouldn't be any implementation-specific dependency. The version should match the version used in the TFM of the app, so hopefully there wouldn't be any version-SKU.

At worst, the satellite assembly could try to use something not in corlib, but that doesn't seem like a likely scenario, and it would break immediately (we would know it).

**Comment by davidwrighton** [comment]
@jaredpar Yes, there is a small but measurable runtime perf impact to compiling against netstandard.dll however, that impact will only really hit if the application looks at the attributes in some way, so it is likely a negligible impact on CoreCLR runtime performance. However, it has a nastier impact on the ability to trim away assemblies from a build, and likely some impact on single file applications, etc. So, I prefer the design where we compile against the "corelib" assembly only for satellite assembly generation. I would suspect that we should have some sort of escape hatch in the project system to pass the full set of assemblies along to satellite assembly generation in case there is some extremely unusual scenario, but in general, I think we'd be safe to pass only 1 reference by default.

**Comment by baronfel** [comment]
What you all are proposing is where I ended up in my linked PR. There are measurements there, but I haven't been able to geet back to it to get it over the finish line.

**Comment by jaredpar** [comment]
> So, I prefer the design where we compile against the "corelib" assembly only for satellite assembly generation

How does MSBuild decide what the corelib assembly is though? The runtime team has historically redefined corelib several times over the years. How can corelib reliably identify the correct one for the current TFM?

**Comment by davidwrighton** [comment]
@jaredpar That is an interesting question to be sure. My suspicion is that we could take the approach that @baronfel took in his PR, which is to just hard-code a list to work with that works for the current situation. Either that, or we could build some scheme where the TFM or something could control what we think of as the "Core" lib in the SDK. Seems like a lot of work to avoid poking a hard-coded thing that historically changes about once every 10 years. But that is why I would want to have some sort of property to ... fallback to passing everything along, so when we do change CoreLib, we can do that for the year or so until we can cleanup the problem of hardcoded stuff in the SDK.

**Comment by jaredpar** [comment]
Could we drop a props / target file in Microsoft.NetCore.App.Ref which outlines which of the assemblies is corelib? That would put the burden on runtime to define it correctly. MSBuild could then fall back to the existing logic if that is not set. 

Note: I'm not sure if we have a extensibility point where we could import a props / target file from a pack but geussing there is.

**Comment by davidwrighton** [comment]
I have no idea. I have very little exposure to how that works, or how the SDK is really setup. Maybe @baronfel or @agocke would know.

**Comment by agocke** [comment]
I don't see a reason why we couldn't drop some info into the refpack. There's already a few files in the `data` directory.

That said, I'm not saying that we've completely learned our lesson on changing the name of corlib... but we don't have any plans to change it any time soon.

**Comment by jaredpar** [comment]
> ... but we don't have any plans to change it any time soon.

... so far 😉 

>  There's already a few files in the data directory.

If that is the case I'd say we should put a property or item metadata there to keep corlib in control of the decision.

**Comment by agocke** [comment]
I think we could put this info in subsequent packs, but it probably wouldn't meet a servicing bar for earlier ones. It seems reasonable to do two things: hard code the list of corlibs for the older packs, and use a tag for corlib for newer ones.

I'm also a little unclear on how we actually ship the netfx packs. That will need some investigation.

**Comment by jaredpar** [comment]
>  It seems reasonable to do two things: hard code the list of corlibs for the older packs, and use a tag for corlib for newer ones.

I agree. That is what I was trying to suggest [here](https://github.com/dotnet/sdk/issues/38478#issuecomment-2140701814). 

> I'm also a little unclear on how we actually ship the netfx packs. That will need some investigation.

Think the other piece we need here is guidance from @baronfel, @rainersigwald on the best way to identify corelib. I honestly don't know a bunch about how packs elements are used in build so I'm just going off intuition looking through the files in there. The one that stands out to me is `data\FrameworkList.xml` as that has a lot of metadata about the assemblies. Should we just an XML attribute that denotes which item is corelib and then let MSbuild turn that into MSBuild props / item metadata? 

Example: 

```xml
<!-- old --> 
<File
  Type="Managed" 
  Path="ref/net8.0/System.Runtime.dll"
  AssemblyName="System.Runtime"
  PublicKeyToken="b03f5f7f11d50a3a"
  AssemblyVersion="8.0.0.0"
  FileVersion="8.0.624.26715" />

<!-- new -->
<File
  Type="Managed" 
  Path="ref/net8.0/System.Runtime.dll"
  AssemblyName="System.Runtime"
  PublicKeyToken="b03f5f7f11d50a3a"
  AssemblyVersion="8.0.0.0"
  FileVersion="8.0.624.26715" 
  IsCorLib="true" />
```

**Comment by agocke** [comment]
> Should we just an XML attribute that denotes which item is corelib and then let MSbuild turn that into MSBuild props / item metadata?

This was precisely my thinking as well.

**Comment by jaredpar** [comment]
Maybe we should split this work into two streams: 

1. This work has no chance of meeting the servicing bar. That means to solve this for `net8.0` and earlier we essentially need to hard code the identity of corlib into the satellite generation process. PR #38504 is already moving in that direction. Let's push that PR to conclusion along these lines.
2. Going forward there is general agreement that giving runtime control over identifying corlib is the better plan. Let's keep hashing out the best way to do that. Then we can follow up with an adjustment to this code based on what we agree.

**Comment by jkotas** [comment]
> Going forward there is general agreement that giving runtime control over identifying corlib is the better plan.

It is a better plan if we ever need to change the corelib name again that is fairly unlikely at this point. I think we should do just (1) and call it a day.

**Comment by jkotas** [comment]
If we wanted to be a future proof against disruptive changes, (2) is not enough. I think it is more likely for the satellite assemblies to pick up a dependency on more than just corelib than corelib name change.

**Comment by mstefarov** [comment]
The improvement is massive.  Please consider backporting this to 8.0, for those of us stuck targeting the LTS release for two more years 🙏

**Comment by baronfel** [comment]
@dotmorten asked for similar, I'm poking to see if it would meet our backport bar. In the meantime, please continue leaving feedback/comments when you'd like specific things backported!

**Comment by jaredpar** [comment]
@mstefarov do you have any data you can share to help us with a back porting argument: a before / after binlog, profile, etc ... ?

**Comment by rainersigwald** [comment]
Also note that you can continue to _target_ `net8.0` while using the .NET 9.0 SDK, which should get you this performance improvement.
