### ISSUE TITLE
mcr.microsoft.com/dotnet/sdk:8.0 does not exists for windows containers 

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/sdk#38502]
This is the output of trying to run a net8 sdk windows container (it does not exists):

PS d:\>docker run -it mcr.microsoft.com/dotnet/sdk:8.0
Unable to find image 'mcr.microsoft.com/dotnet/sdk:8.0' locally
8.0: Pulling from dotnet/sdk
docker: no matching manifest for windows/amd64 10.0.22631 in the manifest list entries.
See 'docker run --help'.

PS D:> docker run -it mcr.microsoft.com/dotnet/sdk:7.0
Unable to find image 'mcr.microsoft.com/dotnet/sdk:7.0' locally
7.0: Pulling from dotnet/sdk
37cbb0a6bd5a: Pull complete
32bc261a9fc2: Pull complete
093ec2dbe8b2: Pull complete
06acc1234188: Pull complete
8eeb9e257586: Pull complete
725b5033e233: Pull complete
dd2373e3ec96: Pull complete
5bb58b2dd6de: Pull complete
513fe7034f4f: Pull complete
da30d722a5c2: Pull complete
ee302ab6496e: Pull complete
24befb094ea2: Pull complete
a383f0731a96: Pull complete
b1968cb61560: Pull complete
3a8988f30833: Pull complete
6db878e3a106: Pull complete
Digest: sha256:582abbba951d2e8095e7f509178527683ed58a98fc61d08ce3825aa5f1c2f8bc
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:7.0
Microsoft Windows [Version 10.0.17763.5329]
(c) 2018 Microsoft Corporation. All rights reserved.

**Comment by baronfel** [comment]
This is a breaking change for the .NET base images that the dotnet-docker team announced a [few months ago](https://github.com/dotnet/dotnet-docker/discussions/4549). You can specify a 'full' image name to use a Windows-based container, for example `mcr.microsoft.com/dotnet/runtime:8.0-windowsservercore-ltsc2022`.

**Comment by JensNordenbro** [comment]
ok, thanks!
