### ISSUE TITLE
Update Application-Insights dependency to 2.22

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#38513]
This is needed to pickup a non-OSS licensing fix -https://github.com/microsoft/ApplicationInsights-dotnet/pull/2671

**Comment by ellahathaway** [comment]
SDK is currently on 2.21: https://github.com/dotnet/sdk/blob/1f35377fc0520a7e3cd4b952ab6a0f69dbc3cc10/eng/Versions.props#L30

The latest version is 2.22. Is that what we want?

**Comment by MichaelSimons** [comment]
Yes 2.22.0 is the version we need to get the patch fix.
