### ISSUE TITLE
`dotnet tool install/update` installs unlisted package

### ISSUE THREAD

**Issue by johnkors** [dotnet/sdk#3853]
Hi,

I unlisted a .NET Core global tool nuget package (latest version) I own on nuget.org, and when I run `dotnet tool install` or `dotnet tool update` it still installs the unlisted/deprecated latest version. Is this by design? I tried to mark it as deprecated as well, but no effect.

**Comment by credfeto** [comment]
I've just run into this -> did you find a way around it?

**Comment by johnkors** [comment]
Nope. Had to push a newer version.
