### ISSUE TITLE
Dotnet list solution.sln package fails in sdk 8.0.101 

### ISSUE THREAD

**Issue by BruceRigg2** [dotnet/sdk#38634]
### Describe the bug
On sdk 8.0.101
`dotnet list solution.sln package`
gives error
MSB0001: Internal MSBuild Error: solution.sln unexpectedly not a rooted path

This works in sdk 7.0.405.

On sdk 8.0.101
`dotnet list c:\path\to\sln\solution.sln package`
does work.  
However this is very inconvenient.

Paths to .csproj files do not seem to need to be rooted.
### To Reproduce
Create a project and a solution  
build it
`dotnet list solution.sln package` 
gives error
MSB0001: Internal MSBuild Error: solution.sln unexpectedly not a rooted path

`dotnet list subfolder\proj.csproj package`
does not give any error

### Exceptions (if any)
MSB0001: Internal MSBuild Error: solution.sln unexpectedly not a rooted path

### Further technical details
```
dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.30fce108

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.30fce108
 [maccatalyst]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34511.84
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  7.0.405 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by Forgind** [comment]
/cc: @rainersigwald for awareness of an internal MSBuild error. I intend to do some digging first because I think it's very plausible we're passing MSBuild something invalid, but users should still never see an internal MSBuild error.

**Comment by Forgind** [comment]
Also, excellent repro. Took me two minutes to successfully reproduce this (using 8.0.106 in my case):
![image](https://github.com/dotnet/sdk/assets/12969783/a7ade16e-37fd-446e-ab25-8a6fe7506439)

Surprisingly, it did _not_ reproduce with my 9.0.100 preview SDK:
![image](https://github.com/dotnet/sdk/assets/12969783/f1c94a55-9911-4416-8a80-169b76da3389)

I'm curious if we regressed something in servicing or fixed it?

**Comment by Forgind** [comment]
Ah, perfect. Thanks @KalleOlaviNiemitalo!

I did look over at solution parsing in MSBuild and found this comment:
https://github.com/dotnet/msbuild/blob/main/src/Build/Construction/Solution/SolutionFile.cs#L205

I was a bit confused because this (public) factory method seems to just pass whatever the user gave it to FullPath's setter:
https://github.com/dotnet/msbuild/blob/4a45d56330882a5e596e97d05ba568ec32e0603c/src/Build/Construction/Solution/SolutionFile.cs#L258

Maybe I'm missing something, but isn't the comment wrong? Regardless, sounds like this bug should be closed. I'll leave it to rainersigwald to decide if he wants to open a new one for an internal MSBuild error.
