### ISSUE TITLE
DOTNET_CLI_TELEMETRY_OPTOUT  through csproj

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/sdk#38646]
It should be possible to disable telemetry inside a csproj.

Many developers are moving their projects through containers, VMs,  cloud machines, local machines, stationaries and laptops and it is just too easy to forget setting up the environment.

**Comment by baronfel** [comment]
This is not feasible IMO - not all telemetry-triggering operations even interact with a project file. And in the cases where we _are_ interacting with a project file the SDK would have to evaluate the project entirely separately from MSBuild, which would cause many perf implications. 

We have talked off and on about a .NET CLI config system a-la git config, this is where opt-in should be defined IMO to be cross-cutting. With such a system users could run a single command like `git config set telemetry.enabled false` or something.

**Comment by Forgind** [comment]
Per baronfel's comment, this isn't really possible. Since there was no action for the month since then, I'm closing this. Let us know if you want the git config option to opt out of telemetry 🙂

**Comment by JensNordenbro** [comment]
@Forgind, Not sure dotnet config is what I am looking for since I do not want to change the system, just my session hence the request for csproj that is always the common ground. We already have the system option through the en variabler.
The reason for session is that our app uses dotnet cli and we do not want to affect the clients whole system, neither should he need to care about the usage of dotnet cli...

**Comment by Forgind** [comment]
Part of baronfel's point is that we don't read the csproj early enough to properly suppress telemetry, and if we send back a bunch of telemetry then find out we shouldn't have done that, it's too late.

I'm a bit unclear on to what extent you want this to persist. Environment variables are system-wide, but they don't persist across sessions, so the next user won't know that you'd set the environment variable. csproj changes do persist across users as long as they use the same csproj. I don't believe dotnet config exists yet, so to some extent, how it works still needs design. I'm only speaking for myself here, not the team, but one option I could feasibly imagine would be to write arbitrary values into a global.json and read them as soon as the CLI starts up, so:
`dotnet config --environment DOTNET_CLI_TELEMETRY_OPTOUT=1`
would make a little section in the global.json for environment variables and set that very early on, disabling our telemetry.
`dotnet config --property DebugSymbols=false`
would make a different section in the global.json for MSBuild properties. If you then do `dotnet build`, it would effectively be like doing `dotnet build -p:DebugSymbols=false`.

I imagine that when you move your csproj file, you'd move everything else with it, including this modified global.json file, so it would obviate the need to separately set the environment before building, but it would also fit better with how the CLI currently does things.

What do you think?

**Comment by JensNordenbro** [comment]
Global.json might work. 
So I am invoking dotnet from Process.Start. Maybe I can inject the environment variable there? Meaning each operation will ovrrride what is on the user?

**Comment by Forgind** [comment]
@JensNordenbro, that might actually make things easier. If you're using Process.Start, I assume you have a ProcessStartInfo ahead of time? That should have an [EnvironmentVariables property](https://learn.microsoft.com/dotnet/api/system.diagnostics.processstartinfo.environmentvariables) that you can use to modify its environment before you launch it. That would probably be the easiest solution for your case.

**Comment by JensNordenbro** [comment]
@Forgind, I will try that.
What is the easiest say to detect telemetry is activated?

**Comment by Forgind** [comment]
I roughly know how to access telemetry from our end, but I have no idea from your end. @baronfel, is there a way?

**Comment by baronfel** [comment]
The CLI/SDK doesn't provide any external user-discoverable way to tell what the configuration is - the only externally-visible knob here is the `DOTNET_CLI_TELEMETRY_OPTOUT` environment variable's value (true/1/yes/false/0/no), but that may not always be set. If it is not set by a user, then if the SDK is an MS-authored SDK then telemetry is sent. If the SDK is an OSS-authored SDK then telemetry is _not_ sent.

**Comment by JensNordenbro** [comment]
If it is https/tcp telemetry to a fix dns then I can scan the network for
signs of telemetry.

Den mån 24 juni 2024 19:40Chet Husk ***@***.***> skrev:

**Comment by JensNordenbro** [comment]
What of it is an sdk from the zip bundle?

Den tors 27 juni 2024 08:48Jens Nordenbro ***@***.***> skrev:

**Comment by baronfel** [comment]
> What of it is an sdk from the zip bundle?

Same behavior, depending on if the zip is an MS authored SDK zip or a Source-Build authored zip. Anything you download off of the MS .NET download page is going to have telemetry enabled by default.

**Comment by JensNordenbro** [comment]
How about detecting telemetry requests?

**Comment by baronfel** [comment]
I'm not quite sure what you mean, can you elaborate?

**Comment by JensNordenbro** [comment]
Using what protocol and port is the telemetry sent on? Knowing this I can ensure my app has disable telemetry on all dotnet cli invocations
