### ISSUE TITLE
Opt into explicit transitive content-copying in 5.0 SDK

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#3864]
With microsoft/msbuild#4865, MSBuild will start respecting properties that allow configurability of whether content from transitive project references is copied to the current project (right now it depends confusingly on implementation details of the projects and what's up to date). The SDK could opt into one of the new, reasonable behaviors.

**Comment by sfoslund** [comment]
@dsplaisted which behavior should the SDK have by default (`MSBuildCopyContentTransitively` true or false)?

**Comment by dsplaisted** [comment]
I think it should be true.  @rainersigwald, what do you think?

**Comment by rainersigwald** [comment]
Yeah, `true` is closer to the older default ("sometimes true but often false in VS incremental builds") so is probably a less-surprising choice.
