### ISSUE TITLE
NETSDK1073 for .NET Core 2.2 | Builds Fail 

### ISSUE THREAD

**Issue by w5922xd** [dotnet/sdk#3873]
## Preface
I am reporting this here based on this comment from a (possibly) related issue.
_Originally posted by @dsplaisted in https://github.com/dotnet/cli/issues/11378#issuecomment-539583642_

>@robborden Can you open a new issue for the failures you're encountering? The error message is the same but I don't believe the root cause is the same as this issue which has been fixed. Thanks!

This is from the dotnet/CLI repo but when you go to create a new issue there the text reads: 
> PLEASE DO NOT FILE ISSUES IN THIS REPO
> File them in https://github.com/dotnet/sdk instead.

If this is the wrong location let me know. 

## Problem Description

I am using Visual Studio 2019 version 16.3.8. I have a solution with these frameworks:
- Project1 targets netcoreapp2.2
- Project2 targets netstandard2.0
- Project3 targets netcoreapp2.2
- Project4 targets netcoreapp2.2

When I rebuilt the solution I am now getting an unexpected error from each project: 
> "The FrameworkReference '.NETStandard,Version=v2.0' was not recognized"
The file referenced is Microsoft.NET.Sdk.FrameworkReferenceResolution.Targets on line 236. 
This points to: 
```xml
<ResolveTargetingPackAssets FrameworkReferences="@(FrameworkReference)"
                                ResolvedTargetingPacks="@(ResolvedTargetingPack)"
                                RuntimeFrameworks="@(RuntimeFramework)"
                                GenerateErrorForMissingTargetingPacks="$(GenerateErrorForMissingTargetingPacks)">
```
Trying this with `dotnet build` produces the same error: 
```xml
λ dotnet build
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 819.77 ms for C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Models\MyNamespace.Models.csproj.
  Restore completed in 7.7 sec for C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Endpoint\MyNamespace.Endpoint.csproj.
  Restore completed in 7.81 sec for C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Tests\MyNamespace.Tests.csproj.
  Restore completed in 12.02 sec for C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Proxy\MyNamespace.Proxy.csproj.
  
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(263,5): error NETSDK1073: The FrameworkReference '.NETStandard,Version=v2.0' was not recognized [C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Models\MyNamespace.Models.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(263,5): error NETSDK1073: The FrameworkReference '.NETStandard,Version=v2.0' was not recognized [C:\Users\<my username>\dev\projects\<My Project>\MyNamespace.Models\MyNamespace.Models.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:23.39
```

## Workaround
Open the project in Visual Studio 2017 and I am able to produce builds without error. 

## Expected behavior
The project would not report errors and could be built. 

## Environment Data
λ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by livarcocc** [comment]
@dsplaisted please take a look.

**Comment by dsplaisted** [comment]
What does the `netstandard2.0` .csproj look like?  Does it declare any `FrameworkReference` items?

The best way for me to investigate this would be if you can [share a binlog](http://aka.ms/binlog) of a failing build.  Note all the information that this will include though, including your project files, environment variables, etc.

**Comment by w5922xd** [comment]
Hey @dsplaisted thanks for taking a look. The .netstandard2.0 project doesn't seem to declare any `FrameworkReference` items that I am aware of. It has two package references. 

Attaching a binlog. 
[msbuild_issue3873.zip](https://github.com/dotnet/sdk/files/3833024/msbuild_issue3873.zip)

I tried to reproduce this in a new project but am not having much luck. I'm afraid this is something dumb on my end that is present in VS2019 and the dotnet.exe but does not exist in VS2017 for some reason.  I only ran into this error after updating to VS2019 16.3.8.

**Comment by dsplaisted** [comment]
@w5922xd It looks like your project is consuming a package that was produced with a preview version of the .NET Core 3.0 SDK, which created invalid packages.

If you can share the project.assets.json file for CloudAPI.Models I can probably tell you which package it is, but you may just want to rebuild all your packages.

Thanks.

**Comment by w5922xd** [comment]
@dsplaisted I see. I appreciate your offer to take a look. Adding it here. 
[project.assets.zip](https://github.com/dotnet/sdk/files/3833391/project.assets.zip)

I would assume it's a package I built called BMSBackup.Models. That package targets `netstandard1.2;netstandard1.6;netstandard2.0`. I rebuilt the nuget package and updated my main project but the errors persist. Sorry, don't meant to take up your time with it. If you spot something I'm missing in the project.assets.json file I'll gladly take a look.

**Comment by dsplaisted** [comment]
@w5922xd Yes, it does seem to be an issue with the BMSBackup.Models project.  Could you share a binlog of packing that project?

**Comment by w5922xd** [comment]
@dsplaisted You bet. Attached it here. 
[msbuild_3873_bmsbackup_models.zip](https://github.com/dotnet/sdk/files/3833454/msbuild_3873_bmsbackup_models.zip)

**Comment by dsplaisted** [comment]
@nkolev92 Can you take a look at this?  The package being generated has a frameworkReference for `.NETStandard,Version=v2.0`, which isn't valid.  Looking at the PackTask parameters in the .binlog, I don't see how that frameworkReference is making it into the package.  However, I tried packing a WinForms project, and I also don't see how the `Microsoft.WindowsDesktop.App.WindowsForms` frameworkReference makes it into the package.  So I'm not sure how to further investigate this.

**Comment by nkolev92** [comment]
The framework references are read from the assets file, so getting the restore output would help determine that. 
Getting the binlog for the restore of that package would also be helpful.

**Comment by w5922xd** [comment]
@nkolev92 

Forgive my ignorance. How can I get you the restore output for the assets file? I previously attached a binlog of the bmsbackup.models project, how would I produce a binlog of the restore of the package?

**Comment by nkolev92** [comment]
Oh no worries. 

The assets file is the output for restore and it's usually found on the `MSBuildProjectExtensionsPath` location. 

To put it simply, unless you override things, it'll be in your obj folder.

**Comment by w5922xd** [comment]
@nkolev92 

I'm unsure which project I should be getting the output for. Since this spans two solutions, I'm including a file here with the project.assets.json file for projects that have a obj/project.assets.json. Hopefully one of these will be useful though please let me know if I'm missing something. 

Also including binlogs of both solutions. 

[assets_files.zip](https://github.com/dotnet/sdk/files/3859285/assets_files.zip)

**Comment by nkolev92** [comment]
We need the assets file for the project getting packed, specifically BMSBackup.Models. 

Looking at the project's assets file, I do not see any framework references.
When you pack that project, does the nuspec still show a framework reference? 

It's possible that the package is installed in the global packages folder and if you are building a package with the exact same version then it will not get copied at all.

**Comment by w5922xd** [comment]
@nkolev92 

> We need the assets file for the project getting packed, specifically BMSBackup.Models.

Was that not included in my attachment at `assets_files\BMSBackup\BMSBackup.Models\project.assets.json`? 

One thing to mention, I've been using an open-sourced 3rd party UI tool to create my nuspec and nuget packages called [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer). 

Here's my previous Nuspec file:
```xml
<?xml version="1.0" encoding="utf-8"?>                                                                                                      
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">                                                                 
  <metadata>                                                                                                                                
    <id>BMSBackup.Models</id>                                                                                                               
    <version>1.0.0</version>                                                                                                                
    <title>BMSBackup.Models</title>                                                                                                         
    <authors>removed</authors>                                                                                         
    <owners>removed</owners>                                                                                           
    <requireLicenseAcceptance>false</requireLicenseAcceptance>                                                                              
    <projectUrl>removed</projectUrl>                                                                         
    <iconUrl>file:///C:/Users/removed/dev/projects/BMSBackup/bms.ico</iconUrl>                                                               
    <description>Models for the BMSBackup library.</description>                                                                            
    <copyright>2019</copyright>                                                                                                             
    <frameworkReferences>                                                                                                                   
      <group targetFramework=".NETStandard1.2">                                                                                             
        <frameworkReference name=".NETStandard,Version=v1.2" />                                                                             
      </group>                                                                                                                              
      <group targetFramework=".NETStandard1.6">                                                                                             
        <frameworkReference name=".NETStandard,Version=v1.6" />                                                                             
      </group>                                                                                                                              
      <group targetFramework=".NETStandard2.0">                                                                                             
        <frameworkReference name=".NETStandard,Version=v2.0" />                                                                             
      </group>                                                                                                                              
    </frameworkReferences>                                                                                                                  
  </metadata>                                                                                                                               
  <files>                                                                                                                                   
    <file src="lib\netstandard1.2\BMSBackup.Models.deps.json" target="lib\netstandard1.2\BMSBackup.Models.deps.json" />                     
    <file src="lib\netstandard1.2\BMSBackup.Models.dll" target="lib\netstandard1.2\BMSBackup.Models.dll" />                                 
    <file src="lib\netstandard1.2\BMSBackup.Models.pdb" target="lib\netstandard1.2\BMSBackup.Models.pdb" />                                 
    <file src="lib\netstandard1.2\BMSBackup.Models.xml" target="lib\netstandard1.2\BMSBackup.Models.xml" />                                 
    <file src="lib\netstandard1.6\BMSBackup.Models.deps.json" target="lib\netstandard1.6\BMSBackup.Models.deps.json" />                     
    <file src="lib\netstandard1.6\BMSBackup.Models.dll" target="lib\netstandard1.6\BMSBackup.Models.dll" />                                 
    <file src="lib\netstandard1.6\BMSBackup.Models.pdb" target="lib\netstandard1.6\BMSBackup.Models.pdb" />                                 
    <file src="lib\netstandard1.6\BMSBackup.Models.xml" target="lib\netstandard1.6\BMSBackup.Models.xml" />                                 
    <file src="lib\netstandard2.0\BMSBackup.Models.deps.json" target="lib\netstandard2.0\BMSBackup.Models.deps.json" />                     
    <file src="lib\netstandard2.0\BMSBackup.Models.dll" target="lib\netstandard2.0\BMSBackup.Models.dll" />                                 
    <file src="lib\netstandard2.0\BMSBackup.Models.pdb" target="lib\netstandard2.0\BMSBackup.Models.pdb" />                                 
    <file src="lib\netstandard2.0\BMSBackup.Models.xml" target="lib\netstandard2.0\BMSBackup.Models.xml" />                                 
  </files>                                                                                                                                  
</package>
```

Using the `dotnet pack` command with debug symbols:
```
λ dotnet pack --output nupkgs --include-source --include-symbols
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 41.76 ms for C:\Users\removed\dev\projects\BMSBackup\BMSBackup.Models\BMSBackup.Models.csproj.
  Successfully created package 'C:\Users\removed\dev\projects\BMSBackup\BMSBackup.Models\nupkgs\BMSBackup.Models.1.0.1.nupkg'.
C:\Program Files\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [C:\Users\removed\dev\projects\BMSBackup\BMSBackup.Models\BMSBackup.Models.csproj]
  Successfully created package 'C:\Users\removed\dev\projects\BMSBackup\BMSBackup.Models\nupkgs\BMSBackup.Models.1.0.1.symbols.nupkg'.
```

Here's the nuspec file from `dotnet pack`: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>BMSBackup.Models</id>
    <version>1.0.1</version>
    <authors>BMSBackup.Models</authors>
    <owners>BMSBackup.Models</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectUrl>removed</projectUrl>
    <iconUrl>removed</iconUrl>
    <description>The model for creating BMS Backups.</description>
    <copyright>2019</copyright>
    <repository type="git" url="removed" />
    <dependencies>
      <group targetFramework=".NETStandard1.2">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard1.6">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
  </metadata>
</package>
```
I updated my project with the new nuget package from `dotnet pack` and clean/rebuild solution. The results are the same: 
![image](https://user-images.githubusercontent.com/52291083/69250185-34085400-0b7d-11ea-9adf-9a1fdd12c68c.png)

I have updated VS2019 to 16.3.9 and the problem persists. It continues to work on VS2017. 

Thanks for looking.

**Comment by dsplaisted** [comment]
Delete all the frameworkReferences from the .nuspec:

```xml
    <frameworkReferences>                                                                                                                   
      <group targetFramework=".NETStandard1.2">                                                                                             
        <frameworkReference name=".NETStandard,Version=v1.2" />                                                                             
      </group>                                                                                                                              
      <group targetFramework=".NETStandard1.6">                                                                                             
        <frameworkReference name=".NETStandard,Version=v1.6" />                                                                             
      </group>                                                                                                                              
      <group targetFramework=".NETStandard2.0">                                                                                             
        <frameworkReference name=".NETStandard,Version=v2.0" />                                                                             
      </group>                                                                                                                              
    </frameworkReferences>    
```

If you've done this and are still getting the error, make sure to bump the package version so you're sure you're not getting an older version, and you can open up the .nupkg in NuGet Package Explorer to ensure that the frameworkReferences aren't still in the package.

**Comment by w5922xd** [comment]
Removed the frameworkReferences, incremented my version, then ran `dotnet pack`. I upgrade the packages in my solution and it is now functioning. Thank you! 

The frameworkReferences were my problem? Really appreciate your help @dsplaisted  and @nkolev92
