### ISSUE TITLE
dotnet workload restore doesn't restore required SDKs since 8.0.200

### ISSUE THREAD

**Issue by evgenyvalavin** [dotnet/sdk#38769]
### Describe the bug
I use Microsoft-Hosted Azure DevOps agents.
Seems like there's something with `dotnet workload restore` command. Everything worked fine yesterday before .NET 8.0.200 release.
iOS project uses .NET 8

### Behaviour on .NET 8.0.101
`/Users/runner/hostedtoolcache/dotnet/dotnet workload restore /Users/runner/work/1/s/src/iOS.csproj`

Output:
```
Installing workloads: ios

Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.android version 34.0.52...
Installing workload manifest microsoft.net.sdk.ios version 17.2.8004...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.2.8004...
Installing workload manifest microsoft.net.sdk.macos version 14.2.8004...
Installing workload manifest microsoft.net.sdk.tvos version 17.2.8004...
Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.2.23619.3...
Installing pack Microsoft.iOS.Sdk version 17.2.8004...
Writing workload pack installation record for Microsoft.iOS.Sdk.net8 version 17.2.8004...
Installing pack Microsoft.iOS.Sdk version 16.4.7129...
Writing workload pack installation record for Microsoft.iOS.Sdk.net7 version 16.4.7129...
```

### Behaviour on .NET 8.0.200
`/Users/runner/hostedtoolcache/dotnet/dotnet workload restore /Users/runner/work/1/s/src/iOS.csproj`

```
Installing workloads: ios

Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.3.24105.21...
Installing pack Microsoft.iOS.Sdk version 16.4.8825-net8-rc1...
Writing workload pack installation record for Microsoft.iOS.Sdk.net8 version 16.4.8825-net8-rc1...
Installing pack Microsoft.iOS.Sdk version 16.4.7099...
Writing workload pack installation record for Microsoft.iOS.Sdk.net7 version 16.4.7099...
Installing pack Microsoft.iOS.Ref version 16.4.8825-net8-rc1...
```

There's no sign of installing Microsoft.iOS.Sdk version 17.2 in the second case when using .NET 8.0.200.
It leads to this issue when a build starts: `error CS0117: 'Platform' does not contain a definition for 'GetCurrentUIViewController'`

**Comment by evgenyvalavin** [comment]
I had to specify .NET 8.0.101 in UseDotNet the Azure Pipelines task as a work around.
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.101'
```

**Comment by hileyj** [comment]
Also seeing this issue. It seems that the sdk-manifests installed with .NET 8.0.2 are versioned 8.0.100-rc1. These include references for Microsoft.iOS.Sdk 16.4.8825-net8-rc1. Where .NET 8.0.1x referenced Microsoft.iOS.Sdk 17.0.8490.

SDK manifests added with .NET 8.0.2:
![image](https://github.com/dotnet/sdk/assets/17505192/b3ccf87f-4fb9-404e-9d87-0c6d11a1470a)
 
 SDK manifests from .NET 8.0.1
![image](https://github.com/dotnet/sdk/assets/17505192/f96017d7-09a0-4449-a39f-9df76cb1557c)

This is causing a MAUI iOS restore error for my app due to package dependencies on net8-ios17.
Like @evgenyvalavin I also had to use 8.0.101 explicitly as a workaround.

**Comment by marcpopMSFT** [comment]
The baseline manifests for maui were updated in 8.0.100 but somehow missed in the codeflow to 8.0.200. The logic for installing workloads looks for the current feature band first (8.0.200 in this case) and then falls back to looking for a version matching the baseline manifest (rc.1 in this case). It skips over 8.0.100 as we didn't want to have to search every possible fallback.

Not sure how our testing didn't catch this so we'll need to dig into that.

https://github.com/dotnet/installer/pull/18666 will fix this going forward. Discussing other options.

**Comment by RDI-Blake** [comment]
Does this require waiting for a new installer or will the NuGet manifest be updated? I use the .NET SDK installer on macOS arm64 and installing the workload results in the findings above.

**Comment by gabsamples6** [comment]
Encounted this issue too and for clarity as a temp workaround are we saying we can 

- Install the latest visual studio
- Update Maui to use - 8.0.7  
- but  use below as indicated by @evgenyvalavin  

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.101'

will the above work?  many thanks

**Comment by evgenyvalavin** [comment]
Closing as completed.
Thanks everyone!
