### ISSUE TITLE
excluding files from publish

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#388]
moved from https://github.com/dotnet/cli/4004 on behalf of @deathrowe.

publishOptions include/exclude turn into modifiers on <Content> items. @deathrowe is suggesting they also apply to build outptu, allowing selective filtering. This seems like a decent thing to discuss in the context of the sdk.

----

## Steps to reproduce

`dotnet publish`

`"publishOptions": {
    "include": [ "**/*.json" ],
    "exclude": ["bin", "**/*.pdb"]
  }`
## Expected  behavior

Files of type pdb will not be included in the publish directory output
## Actual behavior

Files of type pdb are included in the publish directory. I'm mostly focused on the pdb file of the current project being included in the output directory.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by dsplaisted** [comment]
This should be possible to do with .csproj.
