### ISSUE TITLE
Dotnet CLI support for C++/CLI projects

### ISSUE THREAD

**Issue by alexvaluyskiy** [dotnet/sdk#3885]
.NET Core 3.1 added support for C++/CLI, but still, we have to use completely different ecosystem to build and publish packages.

Are there any plans to support `dotnet CLI` for C++/CLI projects to restore/build/pack/etc tasks? It would be great to have SDK based projects files for C++/CLI.

**Comment by livarcocc** [comment]
I don't believe the C++ team has plans to add such support.
