### ISSUE TITLE
[NETSDKE2E]NET9.0 release notes hyperlink on installation wizard cannot be opened.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#38885]
Repro steps:
1. install net9 preview 2 sdk:9.0.100-preview.2.24119.3
2. after installation is done, click the release notes hyperlink:
https://aka.ms/dotnet9-release-notes

Expected Result:
it should be directed to https://github.com/dotnet/core/tree/main/release-notes/9.0
![image](https://github.com/dotnet/sdk/assets/65637796/2376696c-621b-46ca-8992-8f6685568229)

Actual Result:
![image](https://github.com/dotnet/sdk/assets/65637796/87bc681f-e86a-4f31-8bc7-4538fbd06eb8)

**Comment by baronfel** [comment]
@leecow is this redirect managed by y'all?

**Comment by v-ainigao** [comment]
This issue also repro on arm64 OS.

**Comment by leecow** [comment]
https://aka.ms/dotnet9-release-notes created and confirmed working.

**Comment by vdanche** [comment]
This has been fixed on 9.0.100-preview.2.24127.11 SDK.
![image](https://github.com/dotnet/sdk/assets/65637796/9dcfe6f5-9896-43ac-9149-cf6975795a0d)
