### ISSUE TITLE
Unexpected Build Cache Invalidation

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/sdk#38935]
### Describe the bug

This bug was initially reported here:
https://github.com/dotnet/efcore/issues/25878

### To Reproduce

1. Get the code from here: https://github.com/DragonSpark/Framework/tree/issues/reported/efcore/25878
2. Run `dotnet build`
3. Run `dotnet build .\DragonSpark.Schema\DragonSpark.Schema.csproj`
4. Run `dotnet build`

After the fourth step you should see the following output:

```
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  Restored ...\Framework\DragonSpark.Diagnostics\DragonSpark.Diagnostics.csproj (in 332 ms).
  Restored ...\Framework\DragonSpark\DragonSpark.csproj (in 332 ms).
  Restored ...\Framework\DragonSpark.Composition\DragonSpark.Composition.csproj (in 332 ms).
  Restored ...\Framework\DragonSpark.Application\DragonSpark.Application.csproj (in 358 ms).
  Restored ...\Framework\DragonSpark.Schema\DragonSpark.Schema.csproj (in 358 ms).
```

This is unexpected and seems to suggest the build cache has been invalidated somehow

### Exceptions (if any)
N/A
### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version -- `dotnet`

```
> dotnet --info
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.5638171e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.1 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21470.37 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21470.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21470.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by Mike-E-angelo** [comment]
For reference, I run into this problem anytime there is an `efcore` model change, which happens pretty frequently.  Builds take up to two minutes thereafter and it's quite a drag, especially when there are several changes/modifications/fixes that have to occur.

Please let me know if there is any further information I can provide in addressing this issue and I will assist you.

**Comment by Mike-E-angelo** [comment]
Hi @baronfel is there anything I can do to assist in getting this issue triaged?  Thank you for any consideration.

**Comment by baronfel** [comment]
The missing area label was a problem, I've added one now. The best thing you could do is collect and inspect https://aka.ms/binlog logs when this becomes a problem - without seeing _why_ the Restore task thought it needed to re-run we can't really speculate.

**Comment by Mike-E-angelo** [comment]
Great!  Thank you for that @baronfel I am attaching binlogs for the three steps outlined above.  Please let me know if there is anything I misunderstood or if there is any further information I can provide to assist.
[binlogs.zip](https://github.com/dotnet/sdk/files/14864273/binlogs.zip)

I am currently enduring EFCore migrations and each model change no matter how small is costing me about 5 minutes of time because I need to remove the previous migration, add the new migration, and then optimize the model.  Each one of those three steps incurs a build that ranges between 1-2 minutes a piece. 😢

**Comment by Mike-E-angelo** [comment]
Thank you @baronfel for any update you can provide. 🙏  In particular it would be valuable to know if the binlogs I provided were valid as they are the first I have ever produced.

**Comment by Mike-E-angelo** [comment]
HI @baronfel please don't forget about me. 👋  I have not heard from you after following your directions and providing you the requested information.  Is there anything else required of me to continue?  Thank you for your continued assistance.

**Comment by baronfel** [comment]
@nkolev92 is there any guidance for investigating when the restore inputs for a project have changed? Looking at the binlogs above, in the second 'bare' `dotnet build` the RestoreTask shows that for 5 projects (the ones modified by the previous project-specific build) the inputs changed, but I'm not sure which inputs changed:

![image](https://github.com/dotnet/sdk/assets/573979/a55bc9b0-92d3-4277-962e-720f8ebc8d44)

**Comment by nkolev92** [comment]
The obj folder will have a dgspec.json. 

The before/after show what inputs have changed.

**Comment by baronfel** [comment]
@Mike-E-angelo there are some questionable lines in your Directory.Build.props. This file is imported very early, before many properties are set, and so conditions in it may not work the way you are expecting. The suspicious lines are https://github.com/DragonSpark/Framework/blob/89fdf5484f6485d00fa7c669c3c308cdbb21a70a/Directory.Build.props#L15-L20.

Consider setting these nowarns in some other way, perhaps in a Directory.Build.targets file. I believe these missing nowarns are why the restore is being invalidated. If you look at binlog 2 and 3, comparing the assets.json for the DragonSpark project, you can see the nowarns are missing:

![image](https://github.com/dotnet/sdk/assets/573979/93c29473-2217-405d-b4ca-705531dd2198)

@nkolev92 I don't see that file in the binlog, but the project.assets.json was enough to point out the diff.

**Comment by Mike-E-angelo** [comment]
Oh my goodness @baronfel thank you so much for taking the time to explore that!  I am embarrassed that this had to do with my configuration and that it's not a bug, but so very happy that this is now addressed and I no longer have to worry about it!  I was able to do what you suggested and everything now builds expected.  THANK YOU!  It is greatly greatly appreciated. 🙏🙏🙏
