### ISSUE TITLE
Razor references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'

### ISSUE THREAD

**Issue by jjonescz** [dotnet/sdk#38942]
Tracking for currently failing "dotnet-sdk-public-ci (Build Windows_NT_FullFramework Build_Debug)" leg across many PRs.

<samp>
Microsoft.NET.Sdk.Razor.Tests.BuildWithComponentsIntegrationTest.Build_Components_WithDesktopMSBuild_Works [FAIL]
</samp>
<p><p>
<samp>
CSC : warning CS9057: The analyzer assembly 'C:\h\w\A0F10869\p\d\sdk\9.0.100-ci\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'. [C:\h\w\A0F10869\t\dotnetSdkTests\tnt4d4xs.bzw\Build_Compone---03622867\MvcWithComponents.csproj]
</samp>

**Comment by v-wuzhai** [comment]
Have a fix in #38940.
