### ISSUE TITLE
dotnet pack --ouput directory no longer relative to current directory

### ISSUE THREAD

**Issue by frankkilcommins** [dotnet/sdk#3894]
As of yesterday, I get issues with dotnet pack where the output directory was created at the root working directory rather than relative to the current directory. This caused subsequent pack command to fail as the expected pattern was no longer matching.

sdk version: 2.1.500

Output:
`[command]C:\hostedtoolcache\windows\dncs\2.1.500\x64\dotnet.exe pack d:\a\1\s\DUPSCore\DigitalUserProvisioningService.Data.Core\DigitalUserProvisioningService.Data.Core.csproj --configuration release --version-suffix 96713 --output nupkgs
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.`

Package was created in the following directory:
`Successfully created package 'd:\a\1\s\nupkgs\DigitalUserProvisioningService.Data.Core.1.3.0-ci-96713.nupkg'.`

Expected directory:
`d:\a\1\s\DUPSCore\DigitalUserProvisioningService.Data.Core\nupkgs\DigitalUserProvisioningService.Data.Core.1.3.0-ci-96713.nupkg`

I've worked around the issue by prefixing the _current_ directory to the `output` command:
`--configuration $(BuildConfiguration) --version-suffix $(Build.BuildId) --output DUPSCore/DigitalUserProvisioningService.Data.Core/nupkgs`

Just wondering why/when this changed and can I expect my builds to break again if/when it's reverted or resolved.

**Comment by bruno-brant** [comment]
I'm getting the same behavior. SDK version is `2.2.108`.

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#9034
