### ISSUE TITLE
Introduce "bint" as a new keyword for BigInteger

### ISSUE THREAD

**Issue by korayustundag** [dotnet/sdk#38979]
## Description:
This feature request proposes the introduction of a new keyword, "bint", for the BigInteger data type in C#. The "bint" keyword aims to provide a more concise and intuitive way to declare and use BigInteger variables.

## Motivation:
Currently, developers use the "BigInteger" keyword to declare variables of type BigInteger. While descriptive, the length of the keyword can make code less readable, especially when dealing with BigInteger extensively. Introducing a shorter keyword like "bint" would enhance code readability and reduce verbosity, leading to more concise and maintainable code.

## Example Usage:
```c#
bint num1 = 1234567890123456789012345678901234567890;
bint num2 = 9876543210987654321098765432109876543210;
bint result = num1 * num2;
``` 
## Implementation Details:
- Update the C# language specification to recognize "bint" as a keyword for BigInteger.
- Modify the compiler to handle the "bint" keyword appropriately.
- Update documentation and relevant resources to reflect the addition of the "bint" keyword.
## Benefits:
- Improved code readability and maintainability.
- Reduction in verbosity, leading to more concise code.
- Consistency with other languages that use shorter keywords for BigInteger-like types.
## Drawbacks:
- Potential confusion for developers accustomed to using "BigInteger".
- Requires updates to existing codebases to adopt the new keyword.
- Ensuring backward compatibility with existing code that uses "BigInteger".
## Alternatives Considered:
- Different keyword: Explore other options for a shorter keyword, such as "big" or "bigint".
## Conclusion:
Introducing the "bint" keyword offers tangible benefits in terms of code readability and conciseness without sacrificing clarity. While there may be challenges in transitioning existing codebases, the long-term advantages justify the implementation of this feature.

**Comment by marcpopMSFT** [comment]
Closing in favor of 805 per above as this makes more sense in the csharplang repo.
