### ISSUE TITLE
dotnet test html logger throws execption when using special characters in DataRow attributes.

### ISSUE THREAD

**Issue by crone66** [dotnet/sdk#38983]
### Describe the bug
When using DataRow attribute in a unit-test such as `[DataRow((char)8)]` causes an exception in the dotnet test logger when using html logs. It is a pain to figure out what the actual root cause is in bigger projects :).

I configured the test logger by using `Directory.Build.props` file. But I guess the same issue should occur when using `dotnet test --logger html`

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <SignAssembly>false</SignAssembly>
    </PropertyGroup>
    <PropertyGroup>
        <VSTestLogger>html%3BLogFileName=$(MSBuildProjectName).html</VSTestLogger>
    </PropertyGroup>
</Project>
```

```c#
    [TestClass]
    public class MyTestClass
    {
        [DataRow((char)8)] //html logger prints an error and the test result file is empty.
        [DataRow((char)122)]
        [TestMethod]
        public void UselessTestMethod(char key)
        {
            Assert.IsTrue(key > 0);
        }
    }
```

### To Reproduce
The output of the last executed github action run shows the error in the `Test` step
https://github.com/crone66/bug-dotnet-test/tree/main

### Exceptions (if any)
> Html Logger Error : '', hexadecimal value 0x08, is an invalid character.

### Further technical details
- Error can be seen when using github actions

**Comment by nohwnd** [comment]
Moved to vstest, Will see how we can escape it better.
