### ISSUE TITLE
`dotnet list package --vulnerable` should return non-zero exit code when vulnerabilities found

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/sdk#38994]
### Is your feature request related to a problem? Please describe.
Currently, we can run `dotnet list package --vulnerable` to find vulnerable packages in the project or solution.
While using it in the CI/CD pipeline is nice, it falls short if there are vulnerable packages as it does still return a 0 exit code.

### Describe the solution you'd like
If there are vulnerable found in a given project, the command should exit with a non-zero exit code to indicate errors to the caller.

### Additional context
Debatable if `--deprecated` should return a non-zero exit code if deprecated packages were found.

**Comment by ricardoboss** [comment]
I was looking for issues asking for this and found this in the NuGet repo: https://github.com/NuGet/Home/issues/11315
