### ISSUE TITLE
`dotnet tool install` ignores $DOTNET_ROOT and defaults to $HOME/.dotnet

### ISSUE THREAD

**Issue by d3jv** [dotnet/sdk#39019]
### Describe the bug
Despite setting the $DOTNET_ROOT environment variable to a different location, `dotnet tool install --global` always installs tools to `~/.dotnet/tools` and then prints out a message that I should at it to the PATH. 

### Further technical details
`dotnet --info` clearly shows that everything is installed in `/opt/dotnet`
```
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     void
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.201 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/opt/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/opt/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
DOTNET_ROOT is not used by tools in any way by design - it only applies to the .NET AppHost (dotnet binary) and the .NET Runtime.

If you want to install tools to a custom location, you should use the --tool-path option of `dotnet tool install` to do so.

**Comment by d3jv** [comment]
If so, has it always been that way? The [guide for installing dotnet on linux](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#example) says to as `$DOTNET_ROOT/tools` to the PATH, implying that the tools should be installed there.

**Comment by baronfel** [comment]
> If so, has it always been that way? The [guide for installing dotnet on linux](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#example) says to as `$DOTNET_ROOT/tools` to the PATH, implying that the tools should be installed there.

Good spot - the guidance on that page is just wrong in that case. I'll work with the team to get it corrected.

**Comment by JL03-Yue** [comment]
Thanks for reporting.

**Comment by JL03-Yue** [comment]
@d3jv Thank you for reporting. Are there any other problems?

**Comment by d3jv** [comment]
@JL03-Yue Haven't noticed anything else yet.

**Comment by nickpreston24** [comment]
I'm having a similar issue, but on Windows 10 and my `dotnet --info` prints something different.

My tools will install to `~./dotnet/tools`, but when I try to run them, I get ".Net not found" error.

The following is my info:

``` dotnet --info
.NET SDK:
 Version:           9.0.200
 Commit:            90e8b202f2
 Workload version:  9.0.200-manifests.c4f6226a
 MSBuild version:   17.13.8+cbc39bea8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.200\

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.2
  Architecture: x64
  Commit:       80aa709f5d

.NET SDKs installed:
  8.0.405 [C:\Program Files\dotnet\sdk]
  9.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocat
ion]

Environment variables:
  DOTNET_ROOT       [C:/Users/Test Account/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by kazenshi** [comment]
@d3jv 

Setting the dotnet tool location is almost possible with:
```bash
DOTNET_ROOT="$HOME/.local/share/dotnet"
DOTNET_CLI_HOME="$DOTNET_ROOT"
PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/.dotnet/tools
```

`DOTNET_ROOT` - The location of the dotnet runtime
`DOTNET_CLI_HOME` - The location of the dotnet tools (https://github.com/dotnet/sdk/blob/main/src/Common/CliFolderPathCalculatorCore.cs#L8)

If you use the above shell env variables from the example I gave above it will install your dotnet tools in: `$HOME/.local/share/dotnet/.dotnet/tools` My only complaint is that we cannot change the prefix so it will always add a `.dotnet/tools` folder but you can change where that folder gets created with `DOTNET_CLI_HOME`
