### ISSUE TITLE
Publish AOT increases the assembly file size!

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [dotnet/sdk#39012]
Comparing the published file using AOT and without AOT (but singleFile), I see a major difference in the size. In this bare example the difference is just about 3 MB, but in our production app is much more!
Publish SingleFile without AOT: 17MB
Publish with AOT: 38 MB
What could be the reason for this and how I can achieve the same level of size?

![image](https://github.com/dotnet/sdk/assets/97948692/c14b741b-7dda-4dc1-a709-3655deed58e6)

### To Reproduce
dotnew new console -n TestAot
Add the follwoing to the csproj file:
```
<RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>partial</TrimMode>
<PublishAot>true</PublishAot>
```
Publish the project using the folowing command:
`dotnet publish --configuration release -r linux-x64 --self-contained true /p:EnableCompressionInSingleFile=true -o ./linux-x64
`

### Further technical details
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk]
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by MichalStrehovsky** [comment]
You are comparing a __compressed__ single file executable (`EnableCompressionInSingleFile`) with an __uncompressed__ AOT compiled executable. If you want to have a meaningful comparison, you should also compress the AOT version: e.g. with [PublishAotCompressed](https://www.nuget.org/packages/publishaotcompressed).

Also, if you want good size, you need to remove `<TrimMode>partial</TrimMode>` from the project. AOT can only efficiently generate outputs with full trimming. Partial trimming inhibits many optimizations and you'll never get good size outputs with it.

**Comment by mahdighorbanpourptw** [comment]
> You are comparing a **compressed** single file executable (`EnableCompressionInSingleFile`) with an **uncompressed** AOT compiled executable. If you want to have a meaningful comparison, you should also compress the AOT version: e.g. with [PublishAotCompressed](https://www.nuget.org/packages/publishaotcompressed).
> 
> Also, if you want good size, you need to remove `<TrimMode>partial</TrimMode>` from the project. AOT can only efficiently generate outputs with full trimming. Partial trimming inhibits many optimizations and you'll never get good size outputs with it.

Thanks a lot @MichalStrehovsky
I tried it and it works! How come dotnet team don't have an official solution for this?

**Comment by MichalStrehovsky** [comment]
> I tried it and it works! How come dotnet team don't have an official solution for this?

The compression makes startup time worse and uses more memory. Startup time and memory use are the main reasons why someone would choose native AOT in the first place. Compression negates all that and doesn't make much sense in general. There might be special circumstance where it makes sense, but third party tools can be used to do that and an official solution wouldn't be any different from them. We have no plans to add official solution for this.
