### ISSUE TITLE
dotnet publish R2R single file fails only on Windows

### ISSUE THREAD

**Issue by johnnyasantoss** [dotnet/sdk#3901]
Hello!
I have been trying to set up an Azure pipelines and noticed that my `dotnet publish` command is only failing on Windows (works perfectly on Linux and Mac).

It seems to fail when parsing the arguments but the error message does not clarify or help in any way. _(Also, I'm not sure if this issue should be filled here or on msbuild repo)_
I have only one `.csproj` file in the folder and I'm receiving this error message
```log
MSBUILD : error MSB1008: Only one project can be specified.
Switch: p:PublishTrimmed=True
```

Here's the pipeline logs: https://dev.azure.com/johnnyasantoss/ExchangeSharp/_build/results?buildId=18&view=logs&j=022b0a5d-2698-5f72-7610-a845972a8b4c&t=91b18868-140c-5865-f893-165dc330423f
Here's the fork in the exact commit: https://github.com/johnnyasantoss/ExchangeSharp/blob/test13/azure-pipelines.yml

**Comment by johnnyasantoss** [comment]
In the end I changed my workflow to use the dotnet task on Azure pipelines, but I believe there's something wrong in the way the args are parsed on Windows.

I can't reproduce it because I don't have a machine with Windows but I believe the problem is the line jump in the bash script that I was using.

https://github.com/johnnyasantoss/ExchangeSharp/blob/aa70d0b87e15bb602075868814c6df281936157e/azure-pipelines.yml#L47-L52

**Comment by swaroop-sridhar** [comment]
Yes, looks like the dotnet CLI recieved `p:PublishTrimmed=True` in place of `/p:PublishTrimmed=True` and therefore interpreted it as a different project, rather than a switch. 

Not sure if there's anything else to do in this issue.
@fadimounir

**Comment by fadimounir** [comment]
Agreed with @swaroop-sridhar. Seems like the dotnet command line was not formed correctly.

**Comment by johnnyasantoss** [comment]
I was using a multiline bash script when this happened. It should support the `/` character, right? As far as I know there are some limitations with the `\` character on cmd :thinking:

**Comment by fadimounir** [comment]
> I was using a multiline bash script

Can you try single line instead? I'm not too familiar with all the quirks related to batch scripts unfortunately.

**Comment by swaroop-sridhar** [comment]
@jamesmontemagno  I only know of '\' used to write multi-line commands in bash. 
I don't know of using `/` for breaking up lines, and clearly it's not working for you in this case.

@lpereira  may know more.

**Comment by swaroop-sridhar** [comment]
@wli3  I think we've agreed that this is not an SDK problem, and this issue can be closed.

**Comment by lpereira** [comment]
`/` is not, as far as I know, treated as a escape sequence or any other special character as far as a normal Unix shell understands it.  `\` on the other hand can be used for both escaping (if in the middle of a line), or to continue a line (if at the end of a line).
