### ISSUE TITLE
[NETE2ESDK] [Regression] Debug test failed on vscode with 9.0.100-preview.2.24128.5(runtime-9.0.0-preview.2.24127.9) installed.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#39114]
**Description**
Debug test failed on vscode with 9.0.100-preview.2.24128.5(runtime-9.0.0-preview.2.24127.9) installed.

### To Reproduce
![image](https://github.com/dotnet/sdk/assets/99376012/1820c40b-f11b-4d9c-a82b-df74e51ffb0e)
4. Create a .NetStandard Class library with a referenced test project(xunit/nunit/mstest). 
Add a passing, failing and inconclusive test. 
5.  Open it on VS Code.
6. Build and debug the project.

**Expected:**
Tests can debug successfully.
![test debug failedexpected1](https://github.com/dotnet/sdk/assets/99376012/96fbdeec-8edb-4138-947c-40cd3d9760c6)

### Exceptions (if any)
Debug test failed, but can run successfully.
![test debug failed2](https://github.com/dotnet/sdk/assets/99376012/feaa4ecc-7d96-4e64-b5ca-3457d0d845d4)

### Note: 
not repro on 9.0.100-preview.2.24127.10  (runtime- 9.0.0-preview.2.24126.6)

**Comment by AbhitejJohn** [comment]
@v-xiaofchen : Could you share a few more details please:
- What are the contents of the "Ouput->Test*" pane?
- Does running of tests work?

I'm wondering if this is related to an existing issue with Test Platform here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1979661/
/cc: @drognanar

**Comment by v-xiaofchen** [comment]
@AbhitejJohn Thanks for your point, the https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1979661/ seems about Mstest,  about mstest I have noticed and track with the bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1974677

  I try again on nunit test alone with below steps also can repro the bug I opened, can you help to take a look
1. Install C# extension v2.19.13 (latest pre-release from the marketplace)
2. Install C# DevKit extension v1.4.2  (latest pre-release from the marketplace)
3.Install Intellicode for C# DevKit extension v0.1.26  (latest release from the marketplace)
4.Install  SDK 9.0.100-preview.2.24128.5(runtime-9.0.0-preview.2.24127.9) from https://aka.ms/dotnet/9.0.1xx-preview2/daily/dotnet-sdk-win-arm64.exe
5. dotnet new nunit -o mynunit and open it with VSCode
6. Add a passing and failing test. such as :
   
![image](https://github.com/dotnet/sdk/assets/99376012/2ab4b3c0-9eda-4311-aa89-1e7049f2993c)

7.Then build and debug the test
8.observer that test can run successfully but debug failed like below
![test debug failedactualmununittest](https://github.com/dotnet/sdk/assets/99376012/4a96e8c6-e868-40a5-b748-f3601ae82ccf)

**The Output**
![image](https://github.com/dotnet/sdk/assets/99376012/62ead657-6996-4b28-9af0-0b8d9f176894)

**Comment by AbhitejJohn** [comment]
@v-xiaofchen : Thanks for the update. Let's keep an eye out if this does repro on later versions again. If it does, it would be great if you could capture and post the contents of the pane "Output ->  C# Dev Kit - Test Explorer"
![image](https://github.com/dotnet/sdk/assets/18014426/c2e85c44-6fe7-4132-8303-ff83619b32e3)

**Comment by v-xiaofchen** [comment]
Not repro on 9.0.100-preview.3.24165.20 (runtime- 9.0.0-preview.3.24162.31). Closed it as fixed.
