### ISSUE TITLE
Microsoft.VisualStudio.JavaScript.SDK Has reference to non existent Target

### ISSUE THREAD

**Issue by asafcyclops** [dotnet/sdk#39148]
### Describe the bug
Within the Microsoft.VisualStudio.JavaScript.SDK Package the _RunNpmCommandForPublishAssets target is dependent on GenerateNPMCommandProps however this task does not exists which results in a compilation error

### To Reproduce
1. Create an esproj based on the Microsoft.VisualStudio.JavaScript.Sdk/1.0.586930 SDK.
2. reference it from a Microsoft.NET.Sdk.StaticWebAssets based project
3. publish the Microsoft.NET.Sdk.StaticWebAssets based project
4. receive the error

### Exceptions (if any)
```
/Users/asaf/.nuget/packages/microsoft.visualstudio.javascript.sdk/1.0.586930/Sdk/Sdk.targets(291,49): error MSB4057: The target "GenerateNPMCommandProps" does not exist in the project. [/Users/asaf/dev/Cyclops/src/ClientApplication/ClientApplication.esproj]
```

### P.S

I guess this is a rename error to the GeneratePackageJsonProps target.
as a workaround I have created the following target in my project

```
<Target Name="GenerateNPMCommandProps" DependsOnTargets="GeneratePackageJsonProps"/>
```

**Comment by baronfel** [comment]
@joj is this up your alley?

**Comment by baronfel** [comment]
Glad to hear it :) Is there some issue link we can track here? Or is it all on internal trackers at this point?

**Comment by asafcyclops** [comment]
Hey, I saw there a new version of the SDK was released but without the fix.

Any ETA for a fix?

I don't mind contributing this myself if possible

**Comment by asafcyclops** [comment]
This seems to be resolved in the latest version of the package.

Would be nicer to have better communication on this.
