### ISSUE TITLE
error NETSDK1094 when using PublishReadyToRun to publish a library

### ISSUE THREAD

**Issue by al0rid4l** [dotnet/sdk#39141]
### Describe the bug
I am trying to publish a library using `<PublishReadyToRun>true</PublishReadyToRun>` with `<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>` and got error
```shell
error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. When targeting .NET 6 or higher, make sure to restore packa
ges with the PublishReadyToRun property set to true.
```

### To Reproduce
Here is the `csproj` file I'm using:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>

		<!-- It's ok. -->
		<!-- <RuntimeIdentifier>win-x64</RuntimeIdentifier> -->
		<!-- It's ok. -->
		<!-- <RuntimeIdentifier>linux-x64</RuntimeIdentifier> -->
		<!-- error NETSDK1094 -->
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>

		<!-- R2R -->
		<PublishReadyToRun>true</PublishReadyToRun>
	</PropertyGroup>
</Project>
```

### Exceptions
no errors.

### System Info & Version
Windows 10 Pro N 22H2 19045.4046
.NET 8.0.101
Processor	13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz

### Also see
https://github.com/dotnet/sdk/issues/14169#issuecomment-749754489

**Comment by baronfel** [comment]
Are you specifying a single RuntimeIdentifier when you call publish? That's required because the . NET SDK will not publish for each specific RID in RuntimeIdentifiers.

**Comment by al0rid4l** [comment]
> Are you specifying a single RuntimeIdentifier when you call publish? That's required because the . NET SDK will not publish for each specific RID in RuntimeIdentifiers.

Thank you for explaining. So, if I want to build a library in PublishReadyToRun mode to support as many platforms as possible, do I need to specify a single RuntimeIdentifier and then manually execute 'dotnet publish -c Release' for each RID?

**Comment by baronfel** [comment]
yes, this is a core limitation of the SDK for now - it doesn't 'multi-target' across RIDs like it does for TargetFrameworks.

**Comment by al0rid4l** [comment]
Thank you.
