### ISSUE TITLE
RuntimeFrameworkVersion partially ignored

### ISSUE THREAD

**Issue by MCollins434** [dotnet/sdk#39151]
### Describe the bug
The Dotnet 8 SDK (version 8.0.102) is not fully respecting the RuntimeFrameworkVersion project attribute in projects targeting net6.0.

### To Reproduce
Given a csproj file with the following attributes:
```
    <TargetFramework>net6.0-windows</TargetFramework>
    <RuntimeFrameworkVersion>6.0.16</RuntimeFrameworkVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

And a global.json file targeting Dotnet 8 SDK:
```
    "sdk": {
        "version": "8.0.100",
        "rollForward": "latestMinor"
    }
```

When “dotnet build” is run for this project

Then unexpected package versions are resolved

(project.assets.json)
```
        "downloadDependencies": [
          {
            "name": "Microsoft.AspNetCore.App.Ref",
            "version": "[6.0.27, 6.0.27]"
          },
          {
            "name": "Microsoft.NETCore.App.Host.win-x64",
            "version": "[6.0.16, 6.0.16]"
          },
          {
            "name": "Microsoft.NETCore.App.Ref",
            "version": "[6.0.27, 6.0.27]"
          },
          {
            "name": "Microsoft.WindowsDesktop.App.Ref",
            "version": "[6.0.27, 6.0.27]"
          }
        ]
```

I would expect all of these implicit dependencies to be version 6.0.16, aligned with the given RuntimeFrameworkVersion.
However, only one of the dependencies is respecting this version. The rest are unexpectedly looking for latest.

**Comment by Forgind** [comment]
@MCollins434,

Thanks for the bug report! That does look like unexpected behavior. I'm curious why exactly one of the dependencies managed to find 6.0.16. What makes it special?

I noticed that you specified `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` in your project file, and then I noticed that of all the names it found, only one ended in win-x64. I suspect that it tried to find packages that fit your exact specifications but only found the one, so for the rest, it fell back to the latest.

As I'm guessing you're aware, we introduced a breaking change to shrink our rid graph. It looks like you're using the updated version of that but targeting an old net6.0 runtime, which was released over a year ago (and I think is now technically out of support?) If I were to guess, I suspect the other three packages didn't spin out new versions mixing the older runtime with a newer rid.

Is there any reason you can't use 6.0.27?

**Comment by Forgind** [comment]
Since it's been a bit, I'm assuming this hasn't been causing trouble for you lately. Let me know if it is, and I can reopen it.
