### ISSUE TITLE
Run a 3.0 project with SDK 3.1.100-rtm-014727, restore failed with error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 3.0.1) and package Microsoft.NETCore.App.Host.win-x64 with version (= 3.0.1).

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/sdk#3924]
### Repro Steps:
1. Only install SDK [3.1.100-rtm-014727](\\vsufile\patches\sign\NET\CORE_BUILDS\3.1.X\3.1.0\final\3.1.100-rtm-014727)
2. Run a 3.0 project

### Expected: 
Restore and build successfully.

### Actual: 
Restore failed with error NU1102:
![image](https://user-images.githubusercontent.com/57380211/69036546-17efa000-0a21-11ea-8b6c-35116aaad1f9.png)
error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 3.0.1)
error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 3.1.0-preview1.19508.20 ]
error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 3.0.1)
error NU1102:   - Found 10 version(s) in nuget.org [ Nearest version: 3.1.0-preview1.19506.1 ]
error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

Note: 
1. If run a 2.x project, restore and build successfully, run shows as below:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64
```
2. If install .net core 3.0 Runtime, it also failed with error NU1102 as above.
3.  For VS Master 29517.7(16.5.0 Preview 2.0), install or uninstall .net core 3.0 Runtime, it can restore and build successfully.

### Dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nguerrera** [comment]
This is because 3.0.1 has not shipped to nuget.org yet. This is happening one or two days before 3.1.1100 ships.

You will need to add the same feed being used for 3.0.1 testing to test the latest 3.1.100 builds.

**Comment by predatorian3** [comment]
What if this is still happening on fresh 3.1.100 installs of dotNet Core SDK?

**Comment by mschnide** [comment]
My fault was, that i hadn't installed 'aspnetcore runtime'.
The error message was too close to 'Microsoft.NETCore.App' : 'Microsoft.AspNetCore.App'

**Comment by nguerrera** [comment]
> What if this is still happening on fresh 3.1.100 installs of dotNet Core SDK?

Then it is likely to be a similar error for different reasons. Open a fresh bug with repro steps.

**Comment by nguerrera** [comment]
Also make sure you are using the official releases from https://dot.net or from VS. If this is happening from the dotnet-install script, I think it may be because we are incorrectly updating the channel latest with interim builds. If that's happening, we should track it with a different bug as well.

**Comment by predatorian3** [comment]
This is my issue.

https://github.com/dotnet/sdk/issues/4156
