### ISSUE TITLE
PublishSingleFile=true does not work correctly in a multi project build

### ISSUE THREAD

**Issue by schmitch** [dotnet/sdk#3925]
Currently when having the following project structure:

1. ProjectWinService
2. ProjectWinService.Base (TargetFrameworks: `netcoreapp3.0;netstandard2.0`, OT: EXE)
3. ProjectWinService.Api (TargetFrameworks: `netstandard2.0;netstandard2.1`, OT: Library)
4. ProjectOtherExe

While Project 1. is the main build and has a dependency on 2. and 3. it will always fail with the following:

```
error NETSDK1097: Das Veröffentlichen einer Anwendung in einer einzelnen Datei ohne Angabe eines RuntimeIdentifier wird nicht unterstützt. Geben Sie entweder einen RuntimeIdentifier an, oder legen Sie PublishSingleFile auf FALSE fest. [ProjectWinService.Base]
```

the only solution we have now is to actually split the project further and make the Base project a full Api project while having another Exe Project.

wouldn't it be possible to infer the runtime identifier or better have multiple OutputTypes so that it better works in that scenario?

**Comment by dasMulli** [comment]
What exactly did you execute? did you try to publish the main project or call publish on the solution (which isn't really supported)

**Comment by schmitch** [comment]
tried both

**Comment by dasMulli** [comment]
Yeah executable projects referencing other executable projects do have some issues like these because a CLI argument is a global argument that applies to all projects. Some special ones are filtered out explicitly from that but new ones like `PublishSingleFile` not (yet).
You could put it into the csproj file for now..

**Comment by schmitch** [comment]
no useful anymore
