### ISSUE TITLE
Run GivenThatWeWantToVerifyPCLProjectReferenceCompat in helix

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#3928]
The current work around is to run this test in build machine. And run everything else in helix.

This test uses _profile_, so even when `Microsoft.NETFramework.ReferenceAssemblies` is reference, it still asks for 4.5 and 4.6 developer pack.

https://github.com/dotnet/sdk/blob/07618e7bb55b2c1c4e93b08f4f327fe765af93e1/src/Tests/Microsoft.NET.Build.NonHelix.Tests/GivenThatWeWantToVerifyPCLProjectReferenceCompat.cs#L22

**Comment by wli3** [comment]
@dsplaisted @nguerrera any idea about this issue? Why Microsoft.NETFramework.ReferenceAssemblies is not enough? When I remove the profile, it is fine

**Comment by dsplaisted** [comment]
This is testing Portable Class Libraries.  We don't have reference assembly packages for those.

I don't know that these tests are especially valuable anymore.

**Comment by wli3** [comment]
nice :D @dotnet/dotnet-cli if no one compiles I will just remove it

**Comment by nguerrera** [comment]
That's OK with me.

**Comment by wli3** [comment]
Great! removing
