### ISSUE TITLE
Exception at startup with latest SDK

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#3929]
Starting an ASP.NET application targeting netcoreapp5.0 with recent SDKs (since last week between Wednesday 13th and Thursday 14th) triggers:

```
Job failed at runtime:
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Latest known version to work for me is:

```
e6edf2d93f8491a21aa4b0b32e2a55dacb8ef9c2
5.0.100-alpha1-015721
```

Could repro with at least `5.0.100-alpha1-015731` but I don't have the list of versions in between to be more precise.

**Comment by JunTaoLuo** [comment]
cc @jkotalik this is the issue we are seeing in the dependency updates.

**Comment by sebastienros** [comment]
Should there be a functional test as part of the SDK to ensure you can build and run a simple ASP.NET app? Maybe it's already done with other types of applications but for me it's the second week in a raw that it breaks them. Is it something I could do as a PR if you point me to where you would want it to be added?

**Comment by sebastienros** [comment]
I can repro when a custom runtime reference is defined in the project like this:

```
<FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="$(MicrosoftNETCoreAppPackageVersion)" />
```

**Comment by sebastienros** [comment]
In case it would help to solve this, I shared the application deployed as self-contained for windows, and the corehost_trace.log file at this location: "\\scratch2\scratch\sebros\repro.zip"

Just run `PlatformBenchmarks.exe` to repro the issue.

**Comment by joshpearce** [comment]
Any update on this?

**Comment by sebastienros** [comment]
Fixed in current version as dotnet/runtime is now used
