### ISSUE TITLE
`--create-manifest-if-needed` should be mentioned if no manifest exists

### ISSUE THREAD

**Issue by nojaf** [dotnet/sdk#39329]
### Is your feature request related to a problem? Please describe.

I tried to install a local tool without having a manifest:

![image](https://github.com/dotnet/sdk/assets/2621499/9b5a9ff4-8888-4e1b-995f-47c9742bea55)

### Describe the solution you'd like

Using `--create-manifest-if-needed` is what I need to add in this case.
The error message should mention this.

### Additional context

SDK `8.0.201`

**Comment by JL03-Yue** [comment]
Closes as completed in #39827

**Comment by nojaf** [comment]
Thanks @JL03-Yue !
