### ISSUE TITLE
sdk 8.0.201-1 not in ubuntu feed

### ISSUE THREAD

**Issue by KnicKnic** [dotnet/sdk#39352]
### Describe the bug
I am trying to install dotnet sdk 8.0.201-1 using the ubuntu feed for ubuntu-22.04. 

### To Reproduce

The instructions are the same as https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

``` bash
# Launch docker for an 22.04 ubuntu
docker run --rm -it mcr.microsoft.com/powershell:ubuntu-22.04 
```

``` bash
# execute the following commands inside the container, that are the same as the install instructions
bash
apt-get update
apt-get install -y wget

# Get Ubuntu version
declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)

# Download Microsoft signing key and repository
wget https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb

# Install Microsoft signing key and repository
dpkg -i packages-microsoft-prod.deb

# Clean up
rm packages-microsoft-prod.deb

# Update packages
apt update
```

### Further technical details
Do not see dotnet-sdk 8.0.201-1

```
root@c9f7442a5cc5:/# apt-cache madison dotnet-sdk-8.0
dotnet-sdk-8.0 |  8.0.200-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages

dotnet-sdk-8.0 |  8.0.102-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages

dotnet-sdk-8.0 | 8.0.102-0ubuntu1~22.04.1 | http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
dotnet-sdk-8.0 | 8.0.102-0ubuntu1~22.04.1 | http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
dotnet-sdk-8.0 |  8.0.101-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages

dotnet-sdk-8.0 |  8.0.100-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
```

**Comment by Forgind** [comment]
It looks like 8.0.201-1 might not have been published properly, but we do have 8.0.202-1 and 8.0.203-1:

dotnet-sdk-8.0 |  8.0.203-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
dotnet-sdk-8.0 |  8.0.202-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
dotnet-sdk-8.0 |  8.0.200-1 | https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages

I think this was a valid bug, but it isn't really worth pushing old versions of the feature band now that 202 and 203 are out. Sorry we got it wrong for 201.
