### ISSUE TITLE
PrivateAssets=all has different behavior than PrivateAssets=compile;build;buildTransitive....

### ISSUE THREAD

**Issue by donnie-msft** [dotnet/sdk#39465]
@EdLichtman commented on [Wed, 06 Mar 2024 18:23:21 GMT](https://github.com/NuGet/Home/issues/13303)
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK:  Version:           8.0.101  Commit:            6eceda187b  Workload version:  8.0.100-manifests.30fce108  Runtime Environment:  OS Name:     Windows  OS Version:  10.0.17763  OS Platform: Windows  RID:         win-x64  Base Path:   C:\Program Files\dotnet\sdk\8.0.101\  .NET workloads installed:  Workload version: 8.0.100-manifests.30fce108 There are no installed workloads to display.  Host:   Version:      8.0.1   Architecture: x64   Commit:       bf5e279d92  .NET SDKs installed:   1.1.14 [C:\Program Files\dotnet\sdk]   6.0.408 [C:\Program Files\dotnet\sdk]   7.0.400 [C:\Program Files\dotnet\sdk]   8.0.101 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Other architectures found:   x86   [C:\Program Files (x86)\dotnet]     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]  Environment variables:   Not set  global.json file:   C:\Source\nia\core-team-deployment-solutions\src\Microservices\Nx.Etl\global.json  Learn more:   https://aka.ms/dotnet/info  Download .NET:   https://aka.ms/dotnet/download

### Worked before?

Not certain

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Open up my sample code (PrivateAssetsDemonstration - Final) and you'll see 3 libraries:

PrivateAssetsDemonstration
PrivateAssetsDemonstration.Abstractions
Consumer

PrivateAssetsDemonstration.Abstractions contains an Attribute that's used to annotate the Consumer Assembly.
PrivateAssetsDemonstration actually applies the attribute to the ConsumerAssembly

If you change open "Consumer.csproj" and modify the "TestingWithAll" property from true to false, and publish it, you'll be able to run the publish exe with no issue. 

However, if you keep the "TestingWithAll" property as "true", and you publish it, and run the publish exe, you'll see the following error:

       ---> System.IO.FileNotFoundException: Could not load file or assembly 'PrivateAssetsDemonstration.Abstractions, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'PrivateAssetsDemonstration.Abstractions, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null'
         at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
         at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
         at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
         at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
         at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
         at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
         at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
         at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](Assembly element)
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
         --- End of inner exception stack trace ---

https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
This document specifies that setting PrivateAssets="all" is equal to setting PrivateAssets to "compile;runtime;contentFiles;build;buildMultitargeting;buildTransitive;analyzers;native"

However, it seems there is a side effect that setting PrivateAssets="all" also sets the transitive runtime dependencies to private I guess?

[PrivateAssetsDemonstration - Final.zip](https://github.com/NuGet/Home/files/14514014/PrivateAssetsDemonstration.-.Final.zip)

**Comment by donnie-msft** [comment]
@EdLichtman commented on [Thu, 07 Mar 2024 23:15:46 GMT](https://github.com/NuGet/Home/issues/13303#issuecomment-1984763075)
I say it "makes it more difficult to do my work" because I put in a <Warning> (As Error) that I shouldn't ever use "all", due to this inconsistency. My workaround is to not use it. However, I lost a lot of time and published internal versions of packages that I thought worked all the way up until they were published, since you don't find out that it doesn't work until after the NuGet package has been published.

**Comment by donnie-msft** [comment]
@donnie-msft commented on [Tue, 12 Mar 2024 20:46:09 GMT](https://github.com/NuGet/Home/issues/13303#issuecomment-1992547046)
Hi - I reproduced this, and since publish is a behavior of the .NET SDK behavior, I'll transfer to that repo.
I found a (closed) similar discussion here: https://github.com/dotnet/sdk/issues/8991.

**Comment by donnie-msft** [comment]
@baronfel commented on [Tue, 12 Mar 2024 21:05:49 GMT](https://github.com/NuGet/Home/issues/13303#issuecomment-1992588776)
I _think_ the way that ask users to opt into this behavior is via the `CopyLocalLockFileAssemblies` property, which has its defaults logic here: https://github.com/dotnet/sdk/blob/3c469a85beb7af36178e4f34c4a14df51aed5c60/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L31-L42

The assumption of the SDK is that most libraries do not need to bundle their dependencies. Of course, this is not true for all libraries, especially those that work like plugins (like MSBuild Tasks for example). For those projects, this single property should ensure you publish the way you need.

**Comment by marcpopMSFT** [comment]
@donnie-msft can you try setting Publish=true on the packagereference? It looks like all does a little bit more than just the sum of all of those private assets values in that it assumes you didn't want to publish either:
https://github.com/dotnet/sdk/blob/0fc45759da050b5bd6e1f05a0049eebebd1035b9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Shared.targets#L53-L55

We should document this behavior but I don't think we should change this because it would be a breaking change. @Forgind, can you file a doc issue? I think it should be in the package reference documentation even though it appears to be an SDK specific behavior change for all.

**Comment by donnie-msft** [comment]
@marcpopMSFT sorry for any confusion - this is a transferred issue so the customer's username is in the description. If you think NuGet Client has action items here, let me know. thanks!

**Comment by EdLichtman** [comment]
Oh I see.  I'll try that out.  And if we could publish one specific
dependency and not require all or nothing that would be great. I'd just
like to see it documented in the documentation found here:
https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
.

I'll double check your solution works when I get home tonight.

**Comment by Forgind** [comment]
Sounds good! For what it's worth, I tried out your repro and was successfully confused initially, but I tried adding `Publish="true"`, and it started working.

I'm going to close this in lieu of https://github.com/NuGet/docs.microsoft.com-nuget/issues/3270

Thanks for the report!
