### ISSUE TITLE
Ensure NuGet.Localization is updated as part of the NuGet code flow

### ISSUE THREAD

**Issue by nkolev92** [dotnet/sdk#39559]
https://github.com/dotnet/sdk/blob/d6d51df25f85dfee1e04752ac8ac104e38d2667f/eng/Versions.props#L65

NuGet does publish NuGet.Localization to BAR, so ideally this should only require an SDK side change.

**Comment by nkolev92** [comment]
cc @marcpopMSFT 

Can someone on the SDK side handle this. 
I'm guessing it'd be easier to handle for someone who better understands the construction.

**Comment by nkolev92** [comment]
I think the fix is to just add the version in https://github.com/dotnet/sdk/blob/5fa06be7a7bc00c572db72180eb440e094b69ac5/eng/Version.Details.xml, but I'm really doing guesswork here, so probably not the authority on this topic :D

**Comment by marcpopMSFT** [comment]
I added PRs for all active branches:
#39602 
#39584 
#39588 
#39589 
#39590 
#39591 
#39593 
#39594 
#39595

**Comment by marcpopMSFT** [comment]
Should be fixed now.
