### ISSUE TITLE
Wildcard in "dotnet nuget push" (Windows/Ubuntu)

### ISSUE THREAD

**Issue by carsten-riedel** [dotnet/sdk#39569]
### Describe the bug
On Windows and Linux, the behavior of using wildcards with the dotnet nuget push [source] command differs.

#### Ubuntu
Works on ubuntu 22.04 dotnet version 8.0.203
```
dotnet nuget push "src/Projects/PackageName/bin/Pack/PackageName.*.nupkg" --api-key $SECRET --source https://api.nuget.org/v3/index.json
```
```
Pushing PackageName.0.1.8842.15630.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 636ms
Your package was pushed.
```

#### Windows
Does not work on windows10 dotnet version 8.0.203
```
dotnet nuget push "src/Projects/PackageName/bin/Pack/PackageName.*.nupkg" --api-key $SECRET --source https://api.nuget.org/v3/index.json
```
Results in error
```
error: File does not exist (src/Projects/PackageName/bin/Pack/PackageName.*.nupkg).
```

### Note
I had one package in the directory src/Projects/PackageName/bin/Pack/

**Comment by Kebechet** [comment]
https://github.com/NuGet/Home/issues/9390

**Comment by Kebechet** [comment]
**Workaround for windows**
You must use Windows-like slashes `\` instead of linux-like `/`
`nuget push` seems to be very sensitive to this

So in your case
```
dotnet nuget push "src\Projects\PackageName\bin\Pack\PackageName.*.nupkg" --api-key $SECRET --source https://api.nuget.org/v3/index.json
```
