### ISSUE TITLE
[NETSDKE2E][ARM64]Download .net9preview3 x86sdk on ARM64OS access is denied for dotnet.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#39649]
Repro steps:

1.Install .net9preview3 X86 SDK from https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x86.exe.
2.Modify the environment variable path to x86 "C:\Program Files(x86)\dotnet".
3.using CLI running `dotnet --info`.

Expected Result:
`dotnet --info` can be displayed normally.

Actual Result:
Access is denied on ARM64OS for dotnet.
![image](https://github.com/dotnet/sdk/assets/106054229/6f3e5c4b-bd51-4e22-a3a8-c97a8efff6c9)
![image](https://github.com/dotnet/sdk/assets/106054229/4917bdfe-7ebb-4f74-b621-f34d1887666d)
![image](https://github.com/dotnet/sdk/assets/106054229/4079671a-e8c1-4bdd-82c7-162a2ba8dfdd)

**Comment by v-ainigao** [comment]
This issue not repor's on .net8.0.300preview SDK and .net9preview2 SDK.
![image](https://github.com/dotnet/sdk/assets/106054229/e5da3781-00f2-4460-971d-b680cc161ffd)
![image](https://github.com/dotnet/sdk/assets/106054229/b7ad2acf-c72e-4c78-8fa9-5b37431e1753)

**Comment by marcpopMSFT** [comment]
I believe the OS keeps a record somewhere of blocked applications. I've seen this before myself being blocked by MSIT and it was always temporary in the past.

**Comment by v-ainigao** [comment]
> I believe the OS keeps a record somewhere of blocked applications. I've seen this before myself being blocked by MSIT and it was always temporary in the past.

Thanks for the explanation, tried x86sdk on ARM64OS again today and it works fine.
I will close this bug next time it doesn't appear again.
![image](https://github.com/dotnet/sdk/assets/106054229/e6b41366-bdb9-4c25-986c-9cb77a056218)
![image](https://github.com/dotnet/sdk/assets/106054229/a6fdd8b4-04c3-4bfa-a83d-1dcc72490c46)

**Comment by v-ainigao** [comment]
As suggested, I found the blocked dotnet.exe in the protection history. This issue has not repro for the time being, so closed it.

**Comment by marcpopMSFT** [comment]
Is it only the x86 SDK/dotnet that gets blocked and the x64/arm64 versions are fine?

**Comment by v-ainigao** [comment]
1.Today I encountered the same problem when installing x86sdk on ARM64OS, but it still didn't work after I added it to the allowed application list and clicked Allow pop-ups.
2.Here is the reproduce VM for reference:172.20.30.186 (I have added your account)
3.This issue only x86 SDK/dotnet is blocked on ARM64OS.
![image](https://github.com/dotnet/sdk/assets/106054229/6b70accb-6916-4572-a0fc-c7cfbeeb698d)
![image](https://github.com/dotnet/sdk/assets/106054229/a7c1b25c-da0f-43da-ae15-f703bc0843c5)
![image](https://github.com/dotnet/sdk/assets/106054229/763023c9-da43-4e62-b76e-076efacade7f)
![image](https://github.com/dotnet/sdk/assets/106054229/2744aa04-1911-48fe-a99c-bf897d06f0f8)
@marcpopMSFT
