### ISSUE TITLE
segmentation fault ubuntu 16.04

### ISSUE THREAD

**Issue by ceka** [dotnet/sdk#3965]
i've got strange results after upgrading to dotnet-3.0 sdk.

1) dotnet run never finish
2) dotnet build works as usual
3) dotnet run --no-build runs after step 2)
4) dotnet run --no-build sometimes DEFUNCT
5) dotnet run --no-build sometimes goes into segmentation fault

tested on new console project.
```bash
ck@poznan:~/src/test2$ ls
Program.cs  test2.csproj
```

**Comment by ceka** [comment]
`ck@poznan:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  2.1.4 [/usr/share/dotnet/sdk]
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`

**Comment by ceka** [comment]
``ck@poznan:~$ dotnet --version
3.0.101

**Comment by ceka** [comment]
also ^C never finish:

```bash
ck@poznan:~/src/test2$ dotnet run
^C
Attempting to cancel the build...
```

**Comment by wli3** [comment]
This issue was moved to dotnet/runtime#460
