### ISSUE TITLE
8.0.203 for Ubuntu not published on Microsoft repo 

### ISSUE THREAD

**Issue by scrocquesel-ml150** [dotnet/sdk#39664]
### Describe the bug

https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-8.0/ does not list 8.0.203 yet.

![image](https://github.com/dotnet/sdk/assets/140494032/61657594-86cb-4183-8143-372ff63c5760)

It is the same for Ubuntu `23.04` and `23.10`. Does Microsoft stopped supporting Ubuntu or feeds changed ?

**Comment by harryVQ** [comment]
Is this related to https://api.github.com/repos/dotnet/sdk/releases not displaying 8.0.203

I don't see a release for the 8.0.203 sdk only .net 8.0.3 with a 8.0.202 tag

**Comment by scrocquesel-ml150** [comment]
Yes it may be related. The fact is that my `global.json` is pointing to `8.0.203` and azure hosted agent are able to install this version of the sdk using zipped binairies but we cannot build locally when on Ubuntu and using package manager with Microsoft source.

**Comment by deyanp** [comment]
Is this going to be fixed soonish? I am holding my team from upgrading (rest are on Windows or MacOS), and I used to be the first one to upgrade before ... 
And no, I do not want to install directly manually/from a script ...

**Comment by baronfel** [comment]
@rbhanda looks like we may be missing Ubuntu packages for the latest servicing release - can you take a look?

**Comment by rbhanda** [comment]
@leecow FYI

**Comment by leecow** [comment]
Sorry for that - packages.microsoft.com is updated now. 

![image](https://github.com/dotnet/sdk/assets/2212879/cb107b36-4737-4603-a546-ebc9c289f37c)

```
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-host amd64 8.0.3-1 [37.7 kB]
Get:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-hostfxr-8.0 amd64 8.0.3-1 [108 kB]
Get:3 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-runtime-deps-8.0 amd64 8.0.3-1 [2886 B]
Get:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-runtime-8.0 amd64 8.0.3-1 [23.0 MB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libicu70 amd64 70.1-2 [10.6 MB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 aspnetcore-runtime-8.0 amd64 8.0.3-1 [7668 kB]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-targeting-pack-8.0 amd64 8.0.3-1 [2804 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 aspnetcore-targeting-pack-8.0 amd64 8.0.3-1 [1916 kB]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-apphost-pack-8.0 amd64 8.0.3-1 [3516 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 netstandard-targeting-pack-2.1 amd64 2.1.0-1 [1476 kB]
Get:11 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 dotnet-sdk-8.0 amd64 8.0.203-1 [110 MB]
```

**Comment by baronfel** [comment]
Thank you @leecow!
