### ISSUE TITLE
[Question] Is there a component that drives how to update csproj files?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/sdk#3967]
There are some interesting quirks in Visual Studio when using the new csproj SDK file format.  I am not clear if this is a Visual Studio component, or a general re-usable component that might be shared between Visual Studio and Visual Studio Code.  If there is a general re-usable component, I'd like to contribute test cases to improve its behavior.

As a brief example of annoyances:

```xml
    <Content Include="App.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="App.*.config">
      <DependentUpon>App.config</DependentUpon>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
```

Right clicking on App.config and doing copy-paste results in a new file.  Then you re-name that file App.Production.config and get an additional entry (as well as an error message box from Visual Studio).

This produces spurious entries in my csproj SDK file:

```xml
  <ItemGroup>
    <None Remove="App - Copy.config" />
    <None Remove="App.Production.config" />
```

Further, creating an App.Beta.config on top of App.config and App.Production.config produces even more spruious behavior that is truly unexpected.  Copying and renaming App.config to App.Beta.Config generates a spurious App - Copy.Production.config!

If this is not a first class component, I think it's worth considering.  Benefits include fewer merge conflicts and cleaner csproj SDK projects.

**Comment by jzabroski** [comment]
Here is the error I get in Visual Studio, indicating there may be some incongruences between SDK components and the IDE consuming those components:

![image](https://user-images.githubusercontent.com/447485/69551043-0b5fd000-0f6a-11ea-9462-5b4b30ff3c29.png)

**Comment by huoyaoyuan** [comment]
This should belongs to the project-system repo, which reflects project files in IDE.

**Comment by jzabroski** [comment]
Makes sense.  After thinking about it a bit, I wonder if the behavior I am seeing is a "glitch" due to a Brock-Ackerman Anomaly within the project-system code base.  To remove the "glitch" might be computationally expensive.

**Comment by jzabroski** [comment]
https://github.com/dotnet/project-system/issues/5661
