### ISSUE TITLE
Referencing the Microsoft.NET.Test.Sdk NuGet package did NOT fix this issue for `dotnet test` commands. They are still failing in build environments.

### ISSUE THREAD

**Issue by nohwnd** [dotnet/sdk#39814]
Referencing the Microsoft.NET.Test.Sdk NuGet package did NOT fix this issue for `dotnet test` commands. They are still failing in build environments.

Still experiencing the issue on .NET 8.0.203 when referencing the following packages in test projects:
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*-*" />
<PackageReference Include="Microsoft.TestPlatform" Version="17.*-*" />
```

_Originally posted by @robertmclaws in https://github.com/dotnet/sdk/issues/38473#issuecomment-2021810559_

**Comment by nohwnd** [comment]
Do you have a simple repro of the problem please? Are you referencing the full TestPlatform package because you need to find the runner afterwards? How exactly are you running your tests? Is it via `dotnet test` of through vstest.console.exe from the referenced package?

**Comment by robertmclaws** [comment]
Here's a repro branch and build where the error happens:
https://github.com/simple-odata-client/Simple.OData.Client/actions/runs/8462294502/job/23183433497?pr=929#step:6:31

Of note, the project `Simple.OData.Tests.Shared.NorthwindService` is NOT a unit test project. However, the only way to make this issue go away is to add those two test packages to this non-test project, as I did here: https://github.com/simple-odata-client/Simple.OData.Client/actions/runs/8447531397/job/23138040282.

Then the build will execute properly.

The codebase in question uses Directory.Build.props to pull the two packages above into the other test projects.

Lemme know if you have any questions. Thanks!

**Comment by nohwnd** [comment]
Your directory build props mark the project as `IsTestProject` which is used by the VSTest build target to either run or skip tests. This is normally used to suppress running test projects when they have all the dependencies (like Microsoft.NET.Test.SDK) but don't hold any tests. You are facing the problem from the other side.
