### ISSUE TITLE
.net core 3.0 use WIA com faild

### ISSUE THREAD

**Issue by John0King** [dotnet/sdk#3981]
I'm follow this article to create a scanner app (save file),
but it failed with `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Interop.WIA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'Interop.WIA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at WinScanner.Program.Main(String[] args)`

this is the `project file` and the `main.cs`
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="WIA.dll">
      <Guid>94a0e92d-43c0-494e-ac29-fd45948a5221</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
  </ItemGroup>

</Project>

```

```C#
using System;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using WIA;

namespace WinScanner
{
    class Program
    {
        static void Main(string[] args)
        {
            
            try
            {
                var deviceManager = new WIA.DeviceManagerClass();
                var x = deviceManager.DeviceInfos.OfType<IDeviceInfo>()
                    .FirstOrDefault(g => g.Type == WiaDeviceType.ScannerDeviceType);
                if (x != null)
                {
                    Console.WriteLine("scanner found:" + x.Properties["Name"].get_Value());
                    var device = x.Connect();
                    var scannerItem = device.Items[1];
                    var imagefile = (ImageFile)scannerItem.Transfer(FormatID.wiaFormatJPEG);
                    Console.WriteLine(imagefile.ARGBData.String);
                }

            }
            catch(COMException comEx)
            {
                Console.WriteLine(comEx.ErrorCode);
            }

            Console.WriteLine("Hello World!");
        }
    }
}

```

**Comment by kotcmm** [comment]
`    <COMReference Include="WIA.dll">
      <Guid>94a0e92d-43c0-494e-ac29-fd45948a5221</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>`

> <EmbedInteropTypes>true</EmbedInteropTypes>

**Comment by John0King** [comment]
@kotcmm if I add that  ，  the build will fail,  due to many Enumerated can not be used

**Comment by kotcmm** [comment]
@John0King  try switch to netcoreapp3.1

**Comment by 0xd4d** [comment]
This is a regression in SDK 3.1, it works perfectly with SDK 3.0. Possibly related to this PR https://github.com/dotnet/sdk/pull/3539

My issue which I closed since it seems to be a dupe of this issue: https://github.com/dotnet/sdk/issues/3993

**Comment by John0King** [comment]
@0xd4d I'm using . net core 3. 0 not  3. 1,   it may  not be the same issue

**Comment by John0King** [comment]
after I update to vs 2019.4  now it can run now (both .net core 3.0 and .net core 3.1)

**Comment by John0King** [comment]
I'm closing this , since now I can run my app nomally.
