### ISSUE TITLE
ASP.NET templates should be grouped together

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#399]
![image](https://cloud.githubusercontent.com/assets/1103906/20374030/d924a666-acc9-11e6-8a57-aa01da81fc1c.png)

These templates should be grouped together

**Comment by abpiskunov** [comment]
Created bug 298790 to track that on web tooling side.

**Comment by davkean** [comment]
Oh, for some reason I thought these were being built in this repo, what database is that?

**Comment by abpiskunov** [comment]
TFS devdiv2

**Comment by srivatsn** [comment]
Closing since it's tracked in TFS.
