### ISSUE TITLE
Microsoft.VisualStudio.JavaScript.Sdk - error MSB3073 (tsc: not found)

### ISSUE THREAD

**Issue by t-rosa** [dotnet/sdk#39906]
### Describe the bug

I wanted to update the SDK from 0.5.58794-alpha to 1.0.751930  but when building my container the following error appears :

![image](https://github.com/dotnet/sdk/assets/56064543/31ad8f91-a7ca-49f6-b0f8-278627a490a8)

**Comment by baronfel** [comment]
@joj looks like maybe a precondition check for tsc is needed?

**Comment by t-rosa** [comment]
> ### Describe the bug
> I wanted to update the SDK from 0.5.58794-alpha to 1.0.751930 but when building my container the following error appears :
> 
> ![image](https://private-user-images.githubusercontent.com/56064543/318205065-31ad8f91-a7ca-49f6-b0f8-278627a490a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTI5NDMsIm5iZiI6MTcxMTgxMjY0MywicGF0aCI6Ii81NjA2NDU0My8zMTgyMDUwNjUtMzFhZDhmOTEtYTdjYS00OWY2LWIwZjgtMjc4NjI3YTQ5MGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE1MzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjliMWRmNDkwMjg2YTY4ZThhNmQyNTYyYzNmYWE1Mzk5ZDc2NjBhMDk3MjRmMDg0ZGU0NDE0NDQ1NTJjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJw03quPRxbKqpBfd7TcPpuo_FCqJiaHZHrKW4Zj-Ek)

Same without tsc but with vite
![image](https://github.com/dotnet/sdk/assets/56064543/013ba99b-ee9d-41cf-b5ff-9ce967803862)

**Comment by joj** [comment]
We run whatever is in the build command. Vite and tsc should exist as npm packages in that project, but we don't decide to run them, that's all configuration. What I mean is that I think this is the symptom of another problem but it's difficult to tell without understanding the environment, packages in packages.json and contents of esproj.

**Comment by t-rosa** [comment]
Same problem with a fresh project using Visual Studio 2022 preview with the React and ASP.NET Core typescript template.

![image](https://github.com/dotnet/sdk/assets/56064543/758aa3f6-9c05-4a05-b1b4-09973dab9986)
![image](https://github.com/dotnet/sdk/assets/56064543/67ef28a5-127a-447c-9670-ad98f6630915)

**Comment by t-rosa** [comment]
Ok I found that I have to provide <BuildCommand>npm run build</BuildCommand> to the .esproj for it to work again. 
Unlike to what it says in the [docs](https://learn.microsoft.com/en-US/visualstudio/javascript/javascript-project-system-msbuild-reference?view=vs-2022#buildcommand) I had to specify it.

**Comment by joj** [comment]
You shouldn't have to do that, though. What version of the SDK are you in? (You can see that in the first line of the esproj).

**Comment by joj** [comment]
Oh, nvm, it's in your screenshot. ShouldRunBuildScript being false will prevent npm run build from running. We do that because most users don't need to build unless they are publishing. By default, you should be running npm run build in your configuration if you don't set that.

**Comment by joj** [comment]
Ok, found the bug :) Fixing it.

**Comment by t-rosa** [comment]
Nice, thanks ! :)

**Comment by t-rosa** [comment]
Fixed with the 1.0.784122, well done
