### ISSUE TITLE
`Microsoft.NET.Build.Containers` version '8.0.202' warning is incorrect on `8.0.1xx` SDK

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#39931]
I'm using .NET 8 from the Ubuntu archive on Ubuntu 24.04.

```bash
$ dotnet --version
8.0.102
$ dotnet add package Microsoft.NET.Build.Containers
$ dotnet publish -t:PublishContainer -p:EnableSdkContainerSupport=true
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  dotnetapp -> /home/rich/git/dotnet-docker/samples/dotnetapp/bin/Release/net8.0/dotnetapp.dll
/home/rich/.nuget/packages/microsoft.net.build.containers/8.0.202/build/Microsoft.NET.Build.Containers.targets(194,5): warning : Microsoft.NET.Build.Containers NuGet package is explicitly referenced. Consider removing the package reference to Microsoft.NET.Build.Containers as it is now part of .NET SDK. [/home/rich/git/dotnet-docker/samples/dotnetapp/dotnetapp.csproj]
  dotnetapp -> /home/rich/git/dotnet-docker/samples/dotnetapp/bin/Release/net8.0/publish/
  Building image 'dotnetapp' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/runtime:8.0'.
  Pushed image 'dotnetapp:latest' to local registry via 'docker'.
```

That's not the best, right? So, either the package should only emit that warning with `8.0.200`+ or we should have guidance to use an `8.0.1xx` package for an `8.0.1xx` SDK (AKA "matching").

**Comment by baronfel** [comment]
We made this message back in 7.0.300 when we first added native-SDK support for WebApps and it hasn't been updated to account for the versioning relationship for the newly supported project types. We should take another pass at it, especially because 8.0 is LTS and 8.0.100 will be the most easily-accessible version for our Linux users.

**Comment by baronfel** [comment]
Going to close this as we've updated the message and initiated backports to the relevant branches.
