### ISSUE TITLE
Machine-readable `dotnet test --list-tests` output

### ISSUE THREAD

**Issue by Smaug123** [dotnet/sdk#39957]
### Is your feature request related to a problem? Please describe.

`dotnet test --list-tests` outputs a human-readable list of tests, but not a machine-readable list. (For example, it's trivial to break any attempt to parse its output: e.g. by creating test cases with newlines, or tests whose names contain newlines.) This means it effectively can't be used except interactively by a human.

### Describe the solution you'd like
An additional flag, such as `--json`, to produce a machine-readable list of tests.

**Comment by nohwnd** [comment]
We won't implement this for vstest, but we might implement for the new testing platform and surface it via dotnet test, once we have the new dotnet test experience ready for the new plaform. See the linked issue for updates.

**Comment by craigminihan** [comment]
IMHO this is an essential feature of a test runner. Without it my options are:
- parse the 'human readable' output and hope the format doesn't change
- load all the assemblies in the build directory, enumerate all the types and methods looking for test attributes and output JSON that my CI can use
- find another test runner that will do this
