### ISSUE TITLE
New file in watch

### ISSUE THREAD

**Issue by khusroohayat** [dotnet/sdk#3997]
while running dotnet watch run command in console. when i add file in one of the dependencies project, the run command didn't compiles the code, i have to stop this and run the same command again

**Comment by vicky1408** [comment]
By default, dotnet-watch tracks all files matching the following glob patterns:
**/*.cs
*.csproj
**/*.resx

More items can be added to the watch list by editing the .csproj file. Items can be specified individually or by using glob patterns.
<ItemGroup>
    
    <Watch Include="**\*.js" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
</ItemGroup>

**Comment by livarcocc** [comment]
@khusroohayat does this address your issue? If not, I suggest filling an issue on aspnet/aspnetcore, where the code for watch lives.
