### ISSUE TITLE
API HttpWebRequest.GetSystemWebProxy not real time

### ISSUE THREAD

**Issue by dotecxy** [dotnet/sdk#40062]
Open the program first, then open Fiddler, and use this API to obtain the HttpNoProxy

Open Fiddler first, then open the program, and use this API to obtain the HttpSystemProxy

Same situation, no problem with. net4.8

**Comment by dotecxy** [comment]
> 这属于 https://github.com/dotnet/runtime/issues/ 因为 WebRequest.GetSystemWebProxy（） 是在那里定义的。
> 
> 在 .NET Framework 上，WebRequest.GetSystemWebProxy（） 在每次调用时返回一个新实例：https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System/net/System/Net/WebRequest.cs#L1086-L1098
> 
> 在 .NET 上，WebRequest.GetSystemWebProxy（） 只读取 HttpClient.DefaultProxy 属性，该属性缓存结果，从不清除缓存： https://github.com/dotnet/runtime/blob/bc2bd2bd77ecd7a7979a3ef815e3ff36881a1b94/src/libraries/System.Net.Requests/src/System/Net/WebRequest.cs#L546 https://github.com/dotnet/runtime/blob/bc2bd2bd77ecd7a7979a3ef815e3ff36881a1b94/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L39-L47
> 
> 在 .NET 上，它使用 SystemProxyInfo.ConstructSystemProxy（），它首先检查环境变量，然后检查 Windows 代理设置。如果两者都没有指定代理，那么它会创建一个 HttpNoProxy 实例，我认为它最终会被永久缓存。https://github.com/dotnet/runtime/blob/bc2bd2bd77ecd7a7979a3ef815e3ff36881a1b94/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SystemProxyInfo.Windows.cs#L8-L17
> 
> .NET Framework 参考源中的注释提到了“当前模拟用户的代理设置”。我想知道该功能是否在 .NET 实现中被故意省略;我不明白如果同一个进程在不同时间冒充不同的用户，它是如何工作的。

typeof(System.Net.Http.HttpClient).Assembly.GetTypeFromAssembly("SystemProxyInfo")?.GetMethod("ConstructSystemProxy").Invoke(null,new object[0])

Currently solved my problem with reflection

**Comment by ahdung** [comment]
seems .net 9.0 fixed.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps fixed in https://github.com/dotnet/runtime/pull/103364 in which case this is a duplicate of https://github.com/dotnet/runtime/issues/46910
