### ISSUE TITLE
I was struggling with omnisharp not resolving the dotnet-sdk snap on 20.04 until I discovered that a simple

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [dotnet/sdk#40068]
I was struggling with omnisharp not resolving the dotnet-sdk snap on 20.04 until I discovered that a simple

`ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet`

did the trick. No need for msbuild path exports or an omnisharp json legacy resolver.

_Originally posted by @mattiaswerner in https://github.com/dotnet/sdk/issues/10403#issuecomment-621463370_

**Comment by nagilson** [comment]
We will take another look at that issue.
