### ISSUE TITLE
Some tests failed, but ERRORLEVEL is 0

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/sdk#4008]
Hi,

I'm using `xUnit`, after running `dotnet test MyApp.Tests.csproj`, I got:

```
Test Run Failed.
Total tests: 8
     Passed: 5
     Failed: 3
 Total time: 1.3661 Seconds
```

But the value of `%ERRORLEVEL%` is 0.

`dotnet --version` -> `3.0.100`

**Comment by dehghani-mehdi** [comment]
Ignore this, it was my fault.

**Comment by Joe4evr** [comment]
Having the same issue. @dehghani-mehdi How did you solve this?
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by dehghani-mehdi** [comment]
@Joe4evr I don't work v3.x anymore and I have no idea what was the solution. I'm sorry.
