### ISSUE TITLE
Automatically reference .NET Framework reference assembly packages if needed

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#4009]
We've recently released [Microsoft.NETFramework.ReferenceAssemblies packages](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/) which support building projects targeting .NET Framework on systems without the corresponding reference assembly packages installed globally (for example on a non-Windows machine).

Now that the packages are available, we should update the SDK to automatically include the reference when needed.

Related: #335, dotnet/designs#33

**Comment by dsplaisted** [comment]
@sfoslund Here's an issue you could consider picking up.

**Comment by sfoslund** [comment]
@dsplaisted I don't have bandwidth at the moment, but I'll keep it in mind.

**Comment by dsplaisted** [comment]
@sfoslund Yeah it's not an immediate priority, I would very much like to get it in .NET Core 5.0 though.

**Comment by 0xced** [comment]
For the record, this feature has been implemented in the .NET 5 SDK (since v5.0.100-preview.3.20216.1 to be exact).
