### ISSUE TITLE
[NETSDKE2E]The winforms application which is generated by self-contained publish cannot run successfully.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#40173]
Build:
9.0.100-preview.4.24214.1(runtime-9.0.0-preview.4.24211.4)

Repro:
1.dotnet new winforms
2.dotnet publish -r win-x64 --self-contained
3.in publish directory, double-click exe file

**Expected:**
exe file can run successfully
**Actual Result:**
There is no any response after double-click exe file
![image](https://github.com/dotnet/sdk/assets/65637796/c3780b69-36d7-4f20-a586-8b42558213b9)
run dll file, file crash
![image](https://github.com/dotnet/sdk/assets/65637796/99c78906-6fc1-46c3-adbf-41d2b92c8793)
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at win1.Program.Main()

dotnet --info:
![image](https://github.com/dotnet/sdk/assets/65637796/575491ec-d364-4eb9-b159-d6e6ba7c3a5a)

Note:
running WinForms successfully.
![image](https://github.com/dotnet/sdk/assets/65637796/55c3b700-ae2b-4616-921e-46299738a108)

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.
build: .net9.0.100-preview.4.24215.10(runtime-9.0.0-preview.4.24211.4)
![image](https://github.com/dotnet/sdk/assets/106054229/8c88235e-2202-48ba-9b7d-0d5b5af43969)

**Comment by marcpopMSFT** [comment]
@agocke @elinor-fung is there an issue with the host or with our publish?

**Comment by agocke** [comment]
I think that depends on whether or not there is in fact a `System.Private.Windows.Core` in the output directory. If there isn't, I think this is just a bug in publish in gathering output assemblies.

**Comment by v-ainigao** [comment]
> I think that depends on whether or not there is in fact a `System.Private.Windows.Core` in the output directory. If there isn't, I think this is just a bug in publish in gathering output assemblies.

`System.Private.Windows.Core` does not exist in the publish output directory.
![image](https://github.com/dotnet/sdk/assets/106054229/f7941d22-9a4d-4f80-85c8-cd8507eab49a)
![image](https://github.com/dotnet/sdk/assets/106054229/37f6d74d-4e71-4d2d-b6eb-9086f20ad370)

**Comment by richaverma1** [comment]
This is a blocker. Who should look at it @agocke @marcpopMSFT ?

**Comment by marcpopMSFT** [comment]
@dsplaisted Any ideas here? In 8.0, we had no reference to System.Private.Windows.Core but now in 9, I see it showing up in ResolveTargetingPackAssets so we consider it a reference but not needed at runtime.

**Comment by dsplaisted** [comment]
Sounds like this may be the same as https://github.com/dotnet/winforms/issues/11282

**Comment by marcpopMSFT** [comment]
@LakshanF @lonitra were you planning on merging [this](https://github.com/dotnet/windowsdesktop/pull/4366) to your preview 4 branch as it's blocking winforms self-contained scenarios?

**Comment by vdanche** [comment]
This issue has been fixed on 9.0.100-preview.4.24258.4(runtime-9.0.0-preview.4.24252.19)
![image](https://github.com/dotnet/sdk/assets/65637796/c6f8143c-74fc-4c7b-8048-31077d80b328)

FYI @richaverma1
