### ISSUE TITLE
[NETE2ESDK][MAC]Fail to test xunit/mstest project with NET 9 preview.4 SDK installed.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#40194]
**To Reproduce**
1.Prepare a clean Mac M1.
2.install 9.0.100-preview.4.24215.10 (runtime-9.0.0-preview.4.24211.4) from [GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer?tab=readme-ov-file)
3.Create a C# xunit project, add a passing and failing test.
4."dotnet build/test" and observer

**Expected Result:**
Test successfully .

![image](https://github.com/dotnet/sdk/assets/99376012/5f97e974-0459-4364-86c4-b47152bb6c13)

**Actual Result:**
Fail to test xunit/mstest project with NET 9 preview.4 SDK installed.
![image](https://github.com/dotnet/sdk/assets/99376012/05d38f82-9f11-4f92-bd04-f10166dc9adb)

**dotnet --info**
![image](https://github.com/dotnet/sdk/assets/99376012/2452589a-e04c-4254-81ea-60777bc8d4b1)

**Note:**
1.This issue not repro on Mac-x64
2.This issue not repro on nunit.

**Comment by v-xiaofchen** [comment]
This issue still repro's with 9.0.100-preview.4.24253.11(runtime-9.0.0-preview.4.24252.19) installed from [Pipelines - Run 20240503.1-9.0.100-preview.4.24253.6,9.0.100-preview.4.24253.11-224565 artifacts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2444634%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C02%7Cv-huwang%40microsoft.com%7Ccf5239ffc9ec47abc71808dc6e1b86db%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638506311991109266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=oxwQ5IqYeKjZ4nt%2BROhgP3uim5csD5YTRExUYcGpifw%3D&reserved=0) .
![image](https://github.com/dotnet/sdk/assets/99376012/93a44995-14e5-49fc-a4ed-424d613c77db)
@richaverma1 Hi Richa, can you help me take a look?

**Comment by v-xiaofchen** [comment]
This issue also repro's with 9.0.100-preview.5.24258.3(runtime-9.0.0-preview.5.24256.1) from [GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer?tab=readme-ov-file)
![image](https://github.com/dotnet/sdk/assets/99376012/5c52ab05-9cdc-44a4-a4e9-2c2d7a86edbc)

**Comment by v-xiaofchen** [comment]
Still repro on 9.0.100-preview.4.24260.3(runtime-9.0.0-preview.4.24260.3) from [GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer?tab=readme-ov-file)
![image](https://github.com/dotnet/sdk/assets/99376012/db06cf93-eb65-4c69-b455-d075c750cc99)

**Comment by nohwnd** [comment]
@v-xiaofchen  can you please try again on preview5? We tried to repro on M1 mac but the tests pass.

**Comment by v-xiaofchen** [comment]
> @v-xiaofchen can you please try again on preview5? We tried to repro on M1 mac but the tests pass.

@nohwnd 
yeah, this issue does not repro on 9.0.100-preview.5.24274.11(runtime- 9.0.0-preview.5.24272.2) from [GitHub - dotnet/installer: .NET SDK Installer](https://github.com/dotnet/installer?tab=readme-ov-file)
it works fine.
![image](https://github.com/dotnet/sdk/assets/99376012/f00093ae-83db-4fef-b51d-40286c639506)

**Comment by nohwnd** [comment]
closing because it does not repro anymore. Everty time we see issue like this it was runtime issue, not testing issue.
