### ISSUE TITLE
Rename "Unit Test Project" to be better describe it

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#402]
It's confusing that there's a project called "Unit Test Project" and "xUnit Test Project" - can we rename the former to better indicate that it's MSTest based:

![image](https://cloud.githubusercontent.com/assets/1103906/20377349/ba3ee9d2-ace2-11e6-8004-73cf1bff44c5.png)

**Comment by pvlakshm** [comment]
This is a convention that has been in use across various app platforms, and over multiple releases of VS. Therefore, recommend retaining it as-is.

**Comment by davkean** [comment]
The difference between this release and last, is that there is another unit test project with the same name barring one letter.

**Comment by singhsarab** [comment]
@codito Please share your thoughts ?

**Comment by dsplaisted** [comment]
In VS 2017 we are renaming the templates that were "Class Library" and "Console Application" to "Class Library (.NET Framework)" and "Console Application (.NET Framework)".  So I think it makes sense to also rename the unit test templates to disambiguate them too.

**Comment by singhsarab** [comment]
I agree with @dsplaisted, we should make them consistent.
Regarding the other concern, I guess changing the icon for Xunit template should help. 
@bradwilson Can you please help us with icon for Xunit template.

**Comment by dsplaisted** [comment]
This issue was moved to dotnet/templating#799
