### ISSUE TITLE
.NET 6.0.28 unable find pkg Microsoft.NETCore.App.Host.ubuntu.22.04-x64 

### ISSUE THREAD

**Issue by Pmca96** [dotnet/sdk#40217]
Hi everyone. 

I'm having the following issue with the new version of .NET 6.0. 

Ubuntu 22.04 
 .NET version 6.0  (6.0.28)  (With version 6.0.27 build with success)
Latest version, instaled with the following comand: 

```sudo apt-get install -y dotnet-sdk-6.0```

![image](https://github.com/dotnet/sdk/assets/43204551/f9edda19-bd22-4e8c-99c2-804193a80c52)

When creating a project and building it, gives the following error. 

error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.22.04-x64. No packages exist with this id in source(s): nuget.org

And yet i just created the project...

![image](https://github.com/dotnet/sdk/assets/43204551/a7597367-d909-40cf-b69d-b8cb1bfb1927)

Always the same error.

Any ideas?

**Comment by Pmca96** [comment]
Resolved by doing 

sudo apt-get update 
sudo apt-get upgrade

**Comment by habbes** [comment]
I have a similar issue on .NET 8 but running the update and upgrade commands did not help: https://github.com/dotnet/sdk/issues/40676

**Comment by manolis-ct** [comment]
I have exactly the same problem after upgrading OS from 22.04 to 24.04. Has anyone figured it out cause it's a blocking issue. 

error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.24.04-x64. No packages exist with this id in source(s): nuget.org

manolis@manolis:~/dotnet_install$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.133
 Commit:    48ad8f7176

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         ubuntu.24.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.133/

global.json file:
  Not found

Host:
  Version:      6.0.33
  Architecture: x64
  Commit:       6c636980f7

.NET SDKs installed:
  6.0.133 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by robob4him** [comment]
> I have exactly the same problem after upgrading OS from 22.04 to 24.04. Has anyone figured it out cause it's a blocking issue.
> 
> error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.24.04-x64. No packages exist with this id in source(s): nuget.org
> 
> manolis@manolis:~/dotnet_install$ dotnet --info .NET SDK (reflecting any global.json): Version: 6.0.133 Commit: 48ad8f7176
> 
> Runtime Environment: OS Name: ubuntu OS Version: 24.04 OS Platform: Linux RID: ubuntu.24.04-x64 Base Path: /usr/lib/dotnet/sdk/6.0.133/
> 
> global.json file: Not found
> 
> Host: Version: 6.0.33 Architecture: x64 Commit: 6c636980f7
> 
> .NET SDKs installed: 6.0.133 [/usr/lib/dotnet/sdk]
> 
> .NET runtimes installed: Microsoft.AspNetCore.App 6.0.33 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App] Microsoft.NETCore.App 6.0.33 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
> 
> Download .NET: https://aka.ms/dotnet-download
> 
> Learn about .NET Runtimes and SDKs: https://aka.ms/dotnet/runtimes-sdk-info

I had to follow the instructions here: https://github.com/dotnet/sdk/issues/40676#issuecomment-2102017357

`sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'`
`sudo apt install dotnet8`

Must have been some conflicting references to the microsoft installs.
