### ISSUE TITLE
.NET 3.1 Installer Questions

### ISSUE THREAD

**Issue by eat-sleep-code** [dotnet/sdk#4029]
Installing this:  https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.0-windows-x64-installer    appears to install _Microsoft.NET Core Runtime - 3.1.0 Preview 3 (x86)_

**Also executing dotnet --info on Windows is unable to see that Microsoft .NET Core SDK 3.1.100 (x64) is installed.**

> PS C:\Windows\system32> . "C:\Program Files\dotnet\dotnet.exe" --info
>   It was not possible to find any installed .NET Core SDKs
>   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
>       https://aka.ms/dotnet-download
> 
> Host (useful for support):
>   Version: 3.1.0
>   Commit:  157910edee
> 
> .NET Core SDKs installed:
>   No SDKs were found.
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> PS C:\Windows\system32>

**Comment by dagood** [comment]
This was documented as a known issue for 3.1.0, and 3.1.1 fixed it: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#310

> * **[RESOLVED] The 3.1.0 Hosting Bundle for Windows installs a .NET Core Runtime incorrectly branded "3.1.0 Preview 3".**
> 
> This is a cosmetic bug: the hosting bundle is expected to function normally.
> 
> This is fixed with 3.1.1. More information at [dotnet/core#3962](https://github.com/dotnet/core/issues/3962).
> 
> The Hosting Bundle briefly shows that it is installing "Microsoft .NET Core Runtime - 3.1.0 Preview 3". That string is also visible in Add/Remove Programs after the install completes. This is **not** the old November 2019 3.1.0 Preview 3 Runtime. The Hosting Bundle is installing a more recent build of 3.1.0 that has incorrect branding.

---

> Also executing dotnet --info on Windows is unable to see that Microsoft .NET Core SDK 3.1.100 (x64) is installed.

The link you posted is to the ASP.NET Core Runtime installer, so it's expected that it doesn't install the SDK. You can get the SDK by starting from https://dotnet.microsoft.com/download
