### ISSUE TITLE
dotnet publish doesn't copy appsettings.json on the default template with Asp.Net Core 1.1.0

### ISSUE THREAD

**Issue by jeffpapp** [dotnet/sdk#403]
I created an Asp.Net Core 1.1.0 App with VS 2017 RC on Windows.

After cloning the repo (https://github.com/jeffpapp/AspNetCore1_1_0/tree/master/src/AspNetCore1_1_0) on macOS and then running `dotnet publish` I see it creates a `bin/Debug/netcoreapp1.0/publish` directory but doesn't publish the appsettings.json file.  

I don't know if this is an issue with `dotnet publish` or the template included in VS 2017 RC

**Comment by davidfowl** [comment]
This is a known issue. You can work around it by adding this to your csproj:

```XML
    <Content Include="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
```

**Comment by davidfowl** [comment]
You also have to close and reopen the solution after making this change...

**Comment by dsplaisted** [comment]
@davidfowl Do we have an issue filed somewhere for this known issue?

**Comment by davidfowl** [comment]
Our repo is private right now, going to make it public....

**Comment by srivatsn** [comment]
Closing since this seems to tracked in the web repo.

**Comment by ygoe** [comment]
@srivatsn Where is it tracked? The above workaround produces an error.

**Comment by srivatsn** [comment]
@davidfowl was talking about the https://github.com/aspnet/websdk repo. @mlorbetske is this tracked there?

**Comment by mlorbetske** [comment]
@vijayrkn I thought we had an issue for this, not seeing it at the moment, could you link it here please?

**Comment by vijayrkn** [comment]
@ygoe All the json files are included by default, so the above work-around shouldn't be needed 

https://github.com/aspnet/websdk/blob/master/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L32

**Comment by TCGV** [comment]
For those using .NET Core 2.0 the configuration has changed to:

```
  <ItemGroup>
    <None Include="appsettings.json" CopyToPublishDirectory="Always" />
  </ItemGroup>
```

**Comment by shanmukhig** [comment]
> For those using .NET Core 2.0 the configuration has changed to:
> 
> ```
>   <ItemGroup>
>     <None Include="appsettings.json" CopyToPublishDirectory="Always" />
>   </ItemGroup>
> ```

This is the solution to the issue. Thank you.
