### ISSUE TITLE
Source Build fails CI for SDK @ release/6.0.1xx

### ISSUE THREAD

**Issue by vseanreesermsft** [dotnet/sdk#40320]
### Describe the Bug

Source-Build fails CI in sdk 6.0.1xx.

### Steps to Reproduce

See latest servicing builds for sdk internal/release/6.0.1xx.
eg: 
https://dev.azure.com/dnceng/internal/_build/results?buildId=2432775&view=results

### Other Information

There was recently a switch in the ci yml from `templates/source-build.yml` to `templates-official/source-build.yml `
The last working build used the same pool with this:
```
 demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
```
The official template is now failing with this:
```
image: 1es-mariner-2
os: linux
```
It was getting a centos-x64 tarball before when it couldn't find one for linux-x64, now it just tries the linux url twice.

**Comment by Forgind** [comment]
Assigning to @dsplaisted because he did the templates --> templates-official migration for the SDK repo. This is likely fallout from that.

**Comment by dsplaisted** [comment]
@marcpopMSFT @MiYanni Is this still an issue, or did it get fixed?

**Comment by MiYanni** [comment]
This was fixed. Looking at the builds for the branch, they've been passing since the build after this one. This one was on April 17th, and the next one on April 22nd passed, and all subsequent builds have passed. Closing.
