### ISSUE TITLE
[NETSDKE2E][ARM64]x64 sdk gets stuck during installation and cannot be installed normally on ARM64.

### ISSUE THREAD

**Issue by v-jieyan2** [dotnet/sdk#40346]
Build:
9.0.100-preview.4.24221.1(runtime-9.0.0-preview.4.24218.7)

Repro steps:
Install .net9 preview4 X64 SDK on arm64.

Expected Result:
    SDK can be downloaded successfully.

Actual Result:
    It's stucking and unable to be installed.
![image](https://github.com/dotnet/sdk/assets/106043919/3d6972a1-53c8-4659-a4b1-c7f4a6649530)

Note:
1.This memory dump file has been placed in this path.
\\mlangfs1\public\v-aini\dump x64.zip
2.Close the background host and the SDK can be installed successfully.
![image](https://github.com/dotnet/sdk/assets/106043919/a72c56ce-f730-431e-a7e7-52f3d6131d67)

**Comment by v-ainigao** [comment]
> @v-jieyan2 what do you mean when you say that closing the background host lets you install successfully? Is this only x64 on arm64 on windows that impacted?
> 
> CC @joeloff

Hi marc
1.what do you mean when you say that closing the background host lets you install successfully?
This means that when ARM64OS is stuck downloading x64SDK, the background program will generate a 'host'. When I end task it or click on it, the x64SDK will be downloaded successfully.
![Untitled](https://github.com/dotnet/sdk/assets/106054229/b72bdb9e-e88e-4329-8681-0f722330cc77)

2.Is this only x64 on arm64 on windows that impacted?
Yes, only x64 on arm64 on windows that impacted.

**Comment by v-ainigao** [comment]
This issue does not repro on .net9preview5 x64sdk.
![image](https://github.com/dotnet/sdk/assets/106054229/11e561c1-bcf9-425a-9939-529f59ea6049)

**Comment by v-jieyan2** [comment]
Today .net9preview4 x64sdk can be downloaded successfully on arm64OS.
![image](https://github.com/dotnet/sdk/assets/106043919/89a46dc7-a669-4b90-a7f2-bccc06ed47e3)
