### ISSUE TITLE
Disable .NET Core artifact generation for ASP.NET Core projects on .NET Framework

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#404]
![image](https://cloud.githubusercontent.com/assets/95136/20384287/1dbad212-ac68-11e6-9fe8-12aaceb20166.png)

- There should be an app.config in the output folder with the .NET Framework version.
- There should be no deps file (unless preserve compilation context is true?) This might be the case today but I think we used to embed it.
- There should be no runtimeconfig.json

Comparing this to xproj and vs2015 today:

![image](https://cloud.githubusercontent.com/assets/95136/20384434/ad6c904e-ac68-11e6-8f4d-585e659d9bc4.png)

**Comment by eerhardt** [comment]
We deliberately changed PreserveCompliationContext to always generate a .deps.json file and no longer embed it in the assembly. 2 reasons:

1. Consistency -.deps.json being a separate file next to the assembly. 
2. There are differences between build and publish in .deps.json. For example PrivateAssets=All dependencies are included during build, but excluded during publish. You can't do both if you embed the file as a resource in the assembly.

**Comment by davidfowl** [comment]
That sounds fine to me. We still need to fix the runtimeconfig.json.

**Comment by eerhardt** [comment]
Fixed by #1307
