### ISSUE TITLE
Unable to run sdk solution in Visual Studio. Wrong compiler version referenced.

### ISSUE THREAD

**Issue by Banner-Keith** [dotnet/sdk#40423]
I don't know if this is a bug, missing documentation, or just plain user error. I have been following the Developer Guide.

I have cloned the repo to my machine, pulled down the master branch and followed the steps.

I have enabled previews of the SDK in Visual Studio. I am using Visual Studio 2022 17.9.6.

In command prompt I took the following steps:

1. Ran `build.cmd`
2. Ran `.\artifacts\sdk-build-env.bat`
3. Ran `devenv sdk.sln`

Also have tried launching VS using the "VS with sdk.sln" shortcut from the artifacts folder.

I can build using `dotnet build` from command line, but building in Visual Studio does not work.

I get a whole bunch of these type of errors:

>The analyzer assembly 'C:\Git\GitHub\sdk\.dotnet\sdk\9.0.100-preview.3.24204.13\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'

When I run `dotnet --info` I get this:

```
.NET SDK:
 Version:           9.0.100-preview.3.24204.13
 Commit:            81f61d8290
 Workload version:  9.0.100-manifests.77bb7ba9
 MSBuild version:   17.11.0-preview-24178-16+7ca3c98fa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Git\GitHub\sdk\.dotnet\sdk\9.0.100-preview.3.24204.13\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.4.24223.6
  Architecture: x64
  Commit:       d688ac290c

.NET SDKs installed:
  9.0.100-preview.3.24204.13 [C:\Git\GitHub\sdk\.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24172.13 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24219.8 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24223.1 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24219.1 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24219.3 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24223.6 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.3.24175.3 [C:\Git\GitHub\sdk\.dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [C:\Git\GitHub\sdk\.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

If I run `dotnet --list-sdks` I get this:
```
9.0.100-preview.3.24204.13 [C:\Git\GitHub\sdk\.dotnet\sdk]
```

Everything seems to be set up exactly according to the guide but just doesn't work in VS.

Can someone tell me what I'm doing wrong?

**Comment by marcpopMSFT** [comment]
The SDK used to build the SDK was updated to a version that has a dependency on the 4.10 version of Roslyn. As such, you'll need to install a 17.10 preview of Visual Studio which should include an updated Roslyn. Alternatively, you could try setting BuildWithNetFrameworkHostedCompiler to true in your local directory.build.props. We're exploring enabling that by default in our infrastructure and then later for customers but it should try to download the Roslyn that matches the SDK rather than using the one from Visual Studio.

**Comment by Banner-Keith** [comment]
@marcpopMSFT Thank you for helping me with that. With the latest preview it builds. Could that be added to the developer guide? Using a preview version of VS isn't mentioned anywhere on the page.

**Comment by marcpopMSFT** [comment]
@Banner-Keith glad you got unblocked. How does this look? https://github.com/dotnet/sdk/pull/40542

**Comment by Banner-Keith** [comment]
Looks good to me.
