### ISSUE TITLE
App behavior is different with PublishTrimmed=true (PublishSingleFile=true) on linux

### ISSUE THREAD

**Issue by NitzanEgozy** [dotnet/sdk#4042]
When packing with both PublishTrimmed=true and PublishSingleFile=true, I see that the application behaves different. I've attached a sample of ILSpy Console application (ICSharp.Code.Console, originally from https://github.com/icsharpcode/ILSpy). This is a slightly modified version of 5.0.1 - removed all non-used project files and changed sdk to 3.1. I've also attached an input .exe files for the application which has different outputs if the application is published with/without PublishTrimmed=true.
Note that it only happens when I publish it on linux - windows works perfect.

You can find the replication here:
https://github.com/NitzanEgozy/dotnet/tree/master/testers/dotnet_trimmed_bug
1. cd dotnet_trimmed_bug
2. run.sh
3. Compare the outputs of ILSpyInconsistentExe/decompile_output_trimmed and ILSpyInconsistentExe/decompile_output_non_trimmed (more specifically - look at the decompiled DynamicClass.cs - you'll see many errors in the decompilation after trimming)

**Comment by 0xd4d** [comment]
What is different? And can you post the diff?

**Comment by NitzanEgozy** [comment]
For example, look at this method:
non-trimmed
`		public override bool TrySetMember(SetMemberBinder binder, object value)
		{
			if (_fields.ContainsKey(binder.Name))
			{
				Type type = _fields[binder.Name].Key;
				if (value.GetType() == type)
				{
					_fields[binder.Name] = new KeyValuePair<Type, object>(type, value);
					return true;
				}
				throw new Exception("Value " + value?.ToString() + " is not of type " + type.Name);
			}
			return false;
		}`
trimmed
`		public override bool TrySetMember(SetMemberBinder binder, object value)
		{
			//IL_0023: Unknown result type (might be due to invalid IL or missing references)
			//IL_0028: Unknown result type (might be due to invalid IL or missing references)
			//IL_0050: Unknown result type (might be due to invalid IL or missing references)
			if (_fields.ContainsKey(binder.get_Name()))
			{
				global::System.Type type = _fields.get_Item(binder.get_Name()).get_Key();
				if (value.GetType() == type)
				{
					_fields.set_Item(binder.get_Name(), new KeyValuePair<global::System.Type, object>(type, value));
					return true;
				}
				throw new global::System.Exception("Value " + value?.ToString() + " is not of type " + ((MemberInfo)type).get_Name());
			}
			return false;
		}`
(Also - this is just a small replication. On more complicated logic this gives unreadable decompilation results)
I don't think the output itself gives any good information - this is merely a hint that something in the packaging has gone wrong (some missing reference maybe?)

**Comment by 0xd4d** [comment]
Both do the same thing. The trimmer removed all properties so ILSpy shows get_XXX instead of XXX since the XXX property isn't part of the metadata.

**Comment by NitzanEgozy** [comment]
Can you elaborate more on the "removed all properties"? Which properties were removed?
I'm talking mostly about the //IL_0023: Unknown result type errors. For System.Exception, yea, it shows global:: too before, but for complicated classes (with other dependencies) it shows completely unreadable generated classes/method names.

**Comment by 0xd4d** [comment]
FIle an issue: https://github.com/icsharpcode/ILSpy
