### ISSUE TITLE
Workload packages that are unlisted can't be installed

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#40440]
It looks like right now we fail to download any workload packages if they are unlisted in the feed: https://github.com/dotnet/aspire/issues/3941

The behavior I would expect would be that when we're looking for the latest manifest or workload set, we would not include unlisted packages in that search.  However, if we have a workload set that refers to a manifest, or a manifest that refers to a workload pack, then we have a specific version to download and should do so whether it's unlisted or not.

So we should audit the calls to `NuGetPackageDownloader.DownloadPackageAsync` and set `includeUnlisted` to true if the `packageVersion` is specified.  Or, we could change the `includeUnlisted` parameter to be a nullable boolean, and if it's null (ie not specified), then it would default to true if the `packageVersion` was specified, otherwise it would default to false.

**Comment by Forgind** [comment]
Do you think we should do something similar for includePreview? That is, includePreview ?? packageVersion is not null
