### ISSUE TITLE
Adding a reference to certain assemblies causes a hint path to be burnt into ASP.NET Core projects on .NET Framework

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#405]
![image](https://cloud.githubusercontent.com/assets/95136/20384587/2d6497b0-ac69-11e6-93ae-6624e2e19b39.png)

Added System.Net.Http and this happened.

Doesn't seem to happen in plain old csproj:

![image](https://cloud.githubusercontent.com/assets/95136/20384660/7e70b760-ac69-11e6-9d69-23bd2116299e.png)

**Comment by dsplaisted** [comment]
System.Net.Http is now referenced by default, but I tried this with System.Net.Http.WebRequest and the reference was added correctly (without the HintPath).
