### ISSUE TITLE
CONTAINER2005 error raised by containing publishing if project name is all capital letters

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#40501]
### Describe the bug

If a project whose name is all capital letters is published as a container, publishing fails with an `CONTAINER2005` error.

Looking at the comments in the code, the logic is incorrect:

https://github.com/dotnet/sdk/blob/2f9f08dea57e16c7edf2c916b30b6b0d1801773b/src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs#L306-L312

It appears the intention is that a warning is logged for this case instead:

https://github.com/dotnet/sdk/blob/2f9f08dea57e16c7edf2c916b30b6b0d1801773b/src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs#L314-L319

### To Reproduce

1. Create a new ASP.NET Core project with the name `API`.
2. Run `dotnet publish --arch x64 --os linux -p:PublishProfile=DefaultContainer`

### Exceptions (if any)

```
C:\Program Files\dotnet\sdk\8.0.204\Containers\build\Microsoft.NET.Build.Containers.targets(112,5): error CONTAINER2005: The inferred image name 'API' contains entirely invalid characters. The valid characters for an image name are alphanumeric characters, -, /, or _, and the image name must start with an alphanumeric character. [API.csproj]
```

### Further technical details

.NET SDK 8.0.204

**Comment by baronfel** [comment]
This is indeed just a bug - for the case when we normalize casing only (so there are some non-'-' characters in the normalized string) we should just be warning here. We'd love any contribution + test here if you're interested @martincostello, otherwise we'll try to get it done for 8.0.400.
