### ISSUE TITLE
`dotnet new list` locks up terminals

### ISSUE THREAD

**Issue by dsschnau** [dotnet/sdk#40523]
### Describe the bug
When I run `dotnet new list` in a terminal, my console locks up and I can't do anything but open a new terminal window. `dotnet new list` isn't the only dotnet command that creates this behavior, but it reliably reproduces it without writing any code.

### To Reproduce

* run in cmd `dotnet new list`
* see list of dotnet templates available
* terminal locks up, no input is read, CTRL-C doesnt' work, etc.

![image](https://github.com/dotnet/sdk/assets/1373329/55e1468e-9990-44d5-83ec-4c5a7726495e)
<img width="481" alt="image" src="https://github.com/dotnet/sdk/assets/1373329/ad2d1e3f-05a4-4282-a921-a3d39db7c10a">

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
C:\Users\dssch>dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f
```
```
Microsoft Windows [Version 10.0.22631.3447]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dssch>dotnet new list
These templates matched your input:....
```

**Comment by marcpopMSFT** [comment]
@dsschnau does this reproduce with 8.0.300? If it's hung, are you able to attach a debugger and save a dump to provide for us to investigate?

**Comment by marcpopMSFT** [comment]
Triage: closing for now and waiting for a reply on later repros.
