### ISSUE TITLE
Disappearing MAUI templates and dotnet new install Microsoft.Maui.Templates does not work

### ISSUE THREAD

**Issue by ChiefInnovator** [dotnet/sdk#40599]
### Discussed in https://github.com/dotnet/maui/discussions/22113

<div type='discussions-op-text'>

<sup>Originally posted by **ChiefInnovator** April 29, 2024</sup>
I setup a new machine for some MAUI development and installed the latest Visual Studio a few weeks back.  Everything was fine until I updated Visual Studio recently and my MAUI project templates disappeared.  Unfortunately using **dotnet new install Microsoft.Maui.Templates** does not solve the issue.  In fact, it makes it worse because it installs MAUI templates targeting .NET 6 which is not on my machine.

![image](https://github.com/dotnet/maui/assets/15870558/90ad73b0-1161-41fe-91d6-145b0615f92e)

![image](https://github.com/dotnet/maui/assets/15870558/9e4aa1c6-20bc-4200-bee3-d32de1ed8183)

Please help us understand the following:

1) Why did the MAUI project templates get removed?
2) How do we get the latest project templates back?
</div>

**Comment by marcpopMSFT** [comment]
Can you report the output of dotnet --info and dotnet workload --info? Somehow your maui install is in a torn state and so not detecting the installed templates.
