### ISSUE TITLE
Possibility of access denied when running PublishSingleFile=true app on Unix

### ISSUE THREAD

**Issue by JustArchi** [dotnet/sdk#4066]
Hey,

The default behaviour of the `PublishSingleFile=true` on Unix (OS X / Linux) is to create `/var/tmp/.net/<project>/<version>` directory for file extraction, with last 3 directories created if needed.

For some reason, at least on Debian, likely in majority of other configurations, folders created by `dotnet` within that `/var/tmp` come with `700` permission, making them accessible only by the owner. This is not the case with the files that are following traditional `644` permission, but all subdirectories within `/var/tmp/.net` also follow `700`. Folders created manually result in default permission of `755`.

`700` access means that if two or more distinct users try to run one or more `PublishSingleFile=true` applications, everybody but the first guy will receive a fatal error:

```
Failure processing application bundle.
Failed to create directory [/var/tmp/.net/<project>/] for extracting bundled files
A fatal error was encountered. Could not extract contents of the bundle
```

This is a severe problem since it makes running `PublishSingleFile=true` apps impossible if we consider two or more distinct users on the operating system, and it's even more severe considering that `/var/tmp` is preserved across reboots, since if one user creates `/var/tmp/.net` folder with that `700` permission, then no other user will have access to it until it's deleted. This is what `dotnet` is currently doing.

To make it worse, we also need to realize that `.net` is a special subdirectory that everybody should have write access to, as otherwise we could have the same problem if other user will try to run some other app, as `dotnet` won't be able to access the directory. Similar case is with `<project>`, just for running two or more versions of the same project.

Potential solution to the problem:
- Make `/var/tmp/.net` folder follow `777` permission. like `/tmp` and `/var/tmp` does, since it's an extension of temporary directory, just for `dotnet`.
- Make `/var/tmp/.net/<project>` folder follow `777` permission as well, since you may have a case where two or more users run different versions of the same software, leading to them both needing access to `/var/tmp/.net/<project>`.
- Up to your own judgment, make `/var/tmp/.net/<project>/<version>` at least `755` so other users can re-use already extracted structures. `755` should be enough in this case considering that we won't need to do any manual modifications inside after extraction (as I read from the design docs), so read access for other users is more than enough.

Alternative solution to the problem:
- Make use of other solutions available on unixes, such as making use of the groups or ACLs, probably overkill for this use case but you're deciding here.

Reproduction steps:
- Publish `PublishSingleFile=true` application.
- `adduser testuser1` and `adduser testuser2`.
- Run your software as `testuser1`, then as `testuser2`. Second user will not be able to run the application, unless he is the first user, `root` or has some special permission to access those `700` directories created by `testuser1`.

In any case thank you for your time looking into this problem.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee
```

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/core-setup/issues/8882

**Comment by livarcocc** [comment]
Closing as a dup.
