### ISSUE TITLE
.NET 8.0  error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.22.04-x64. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by habbes** [dotnet/sdk#40676]
### Describe the bug
I'm having an issue build and running a dotnet app on my Ubuntu 22.04 (running on Azure VM). The following error appears when I run `dotnet run` or `dotnet restore` against my project:

```
error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.22.04-x64. No packages exist with this id in source(s): nuget.org
```

I used to build and run the project without any issues. I haven't updated the codebase since the last time I ran it successfully on the same VM. The VM was off for a while, and I turned it to run the project and I got this error.

I have seen a similar issue reported here: https://github.com/dotnet/sdk/issues/40217

I tried the proposed solution
```
sudo apt-get update
sudo apt-get upgrade
```

But that has not worked for me. I still get the same issue.

I have tried to uninstall and reinstall dotnet 8 sdk with:

```
sudo apt-get update &&   sudo apt-get install -y dotnet-sdk-8.0
```

But now I get the following error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netstandard-targeting-pack-2.1-8.0 : Conflicts: netstandard-targeting-pack-2.1
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

### To Reproduce

I get an error when I run `dotnet restore` or `dotnet run` against my CLI project.

### Exceptions (if any)

Here's the error I get:

```c#
error NU1101: Unable to find package Microsoft.NETCore.App.Host.ubuntu.22.04-x64. No packages exist with this id in source(s): nuget.org
```

### Further technical details

Here's some info about my .NET installation:
```
dotnet --info
.NET SDK:
 Version:           8.0.103
 Commit:            6a90b4b4bc
 Workload version:  8.0.100-manifests.e99a2be4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.103/

.NET workloads installed:
 Workload version: 8.0.100-manifests.e99a2be4
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.103 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/downloa
```

**Comment by areriklq** [comment]
Seeing the exact same thing here on the same platform. This appeared after I did a `apt update/upgrade`  today.

@habbes Did you solve it?

**Comment by areriklq** [comment]
Follow up, I noticed some packages were held back and did a `dist-upgrade`, however that resulted in a complete loss of SDKs. 

What is going on?

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  aspnetcore-runtime-8.0 dotnet-hostfxr-8.0 dotnet-runtime-8.0 dotnet-sdk-7.0 dotnet-sdk-8.0 python3-update-manager
  snapd update-manager-core
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.


$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  aspnetcore-runtime-8.0 aspnetcore-targeting-pack-8.0 dotnet-apphost-pack-8.0 dotnet-hostfxr-8.0 dotnet-runtime-8.0
  dotnet-targeting-pack-8.0 dotnet-templates-7.0 dotnet-templates-8.0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  dotnet-sdk-8.0 netstandard-targeting-pack-2.1-8.0
The following NEW packages will be installed:
  netstandard-targeting-pack-2.1
The following packages have been kept back:
  aspnetcore-runtime-8.0 dotnet-hostfxr-8.0 dotnet-runtime-8.0 python3-update-manager snapd update-manager-core
The following packages will be upgraded:
  dotnet-sdk-7.0
1 upgraded, 1 newly installed, 2 to remove and 6 not upgraded.
Need to get 110 MB of archives.
After this operation, 209 MB disk space will be freed.
Do you want to continue? [Y/n]
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 netstandard-targeting-pack-2.1 amd64 6.0.128-0ubuntu1~22.04.2 [1398 kB]
Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-sdk-7.0 amd64 7.0.408-1 [108 MB]
Fetched 110 MB in 21s (5273 kB/s)
(Reading database ... 99372 files and directories currently installed.)
Removing dotnet-sdk-8.0 (8.0.103-0ubuntu1~22.04.2) ...
(Reading database ... 96355 files and directories currently installed.)
Preparing to unpack .../dotnet-sdk-7.0_7.0.408-1_amd64.deb ...
Unpacking dotnet-sdk-7.0 (7.0.408-1) over (7.0.117-0ubuntu1~22.04.2) ...
dpkg: netstandard-targeting-pack-2.1-8.0: dependency problems, but removing anyway as you requested:
 dotnet-sdk-7.0 depends on netstandard-targeting-pack-2.1 (>= 2.1.0); however:
  Package netstandard-targeting-pack-2.1 is not installed.
  Package netstandard-targeting-pack-2.1-8.0 which provides netstandard-targeting-pack-2.1 is to be removed.

(Reading database ... 97620 files and directories currently installed.)
Removing netstandard-targeting-pack-2.1-8.0 (8.0.103-0ubuntu1~22.04.2) ...
Selecting previously unselected package netstandard-targeting-pack-2.1.
(Reading database ... 97488 files and directories currently installed.)
Preparing to unpack .../netstandard-targeting-pack-2.1_6.0.128-0ubuntu1~22.04.2_amd64.deb ...
Unpacking netstandard-targeting-pack-2.1 (6.0.128-0ubuntu1~22.04.2) ...
Setting up netstandard-targeting-pack-2.1 (6.0.128-0ubuntu1~22.04.2) ...
Setting up dotnet-sdk-7.0 (7.0.408-1) ...

$ dotnet restore
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

**Comment by areriklq** [comment]
I have solved the issue for me now.

There must have been some mismatch between Ubuntu feed and Microsoft feed, and I was running dotnet 7 and 8 in parallell. Probably not supported.

After running `apt autoremove` and then reinstalling dotnet 8 `apt install dotnet-sdk-8.0 dotnet-runtime-8.0` I now have the SDKs back and `dotnet restore` works as expected.

**Comment by Forgind** [comment]
I'm glad you were able to find a solution! I suspect you may have collided with one of our (intentional) breaking changes between .NET 7 and .NET 8:
https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph

Microsoft.NETCore.App.Host.ubuntu.22.04-x64 doesn't exist anymore and was replaced by Microsoft.NETCore.App.Host.linux-x64. I'm guessing that's also how we ended up with a mismatch between the Microsoft feed and the Ubuntu feed: if one of them was using .NET 7 still, it would look for .ubuntu.22.04, and if the other was for .NET 8, it would only have and know about .linux.

I'm not entirely sure what the best next step should be. It sounds like you're unblocked, which is good. Perhaps we should look at our feeds to see where there might be a lingering reference to ubuntu.22.04 and clean that up?

@baronfel, is there a nice command for seeing that?

**Comment by areriklq** [comment]
@Forgind Should I be able to have .NET 8 and 7 installed in parallell on Ubuntu from feeds?

**Comment by inalelub** [comment]
> @areriklq thanks for sharing. I solved it after running `sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'` then reinstalling the sdk. Initially I had not used the wildcards in the remove command and was only removing _some_ components while leaving others on the system, which seemed to cause issues when trying to reinstall.

Thank you for this, it really helped because I didn't know what was the problem.

**Comment by areriklq** [comment]
For those, like me, that need to run .NET 7 and 8 in parallell on Ubuntu, I can instead recommend the `dotnet-install` scripts.

I uninstalled all dotnet packages from PPAs and used this script intead: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

I then made sure `.bashrc` appends the `PATH` with the path to the `dotnet` binary (so it survives when new shells are spawned).

**Comment by baronfel** [comment]
Thanks for the good discussion here folks. Summarizing:

* different versions of Ubuntu have different versions of .NET available in the distro feeds
* different versions of Ubuntu have different versions of .NET available in the Microsoft feeds
* mixing up distro and Microsoft feeds leads to failure
* if you need multiple SDK major versions on a distro that doesn't a) have all of those versions in the distro feeds, or b) have access to the Microsoft feeds, then the recommended approach is to use the dontet-install scripts to manage multiple side-by-side local SDK installations

**Comment by raddevus** [comment]
> sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'

Thanks so much for that solution.  I just upgraded to 24.04.1 and thought I was toast & might have to downgrade or something.  
So glad that worked.  Thanks again!

**Comment by BrandonLozada** [comment]
> [@areriklq](https://github.com/areriklq) thanks for sharing. I solved it after running `sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'`

Neat. bless you guys!

**Comment by Tim-Pas** [comment]
If someone comes across this issue while trying to run dotnet in docker (i.e. multistage build)

I have fixed it for myself by explicitly setting the RuntimeIdentifier like so:

```csproj
<PropertyGroup>
    <!-- ... -->
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <!-- ... -->
</PropertyGroup>
```

**Comment by mauro-codes** [comment]
> [@areriklq](https://github.com/areriklq) thanks for sharing. I solved it after running `sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'` then reinstalling the sdk. Initially I had not used the wildcards in the remove command and was only removing _some_ components while leaving others on the system, which seemed to cause issues when trying to reinstall.

You saved my day!

**Comment by e-tang** [comment]
Just did the "apt upgrade", I encountered this error as it worked fine before.

### With just .net 9 installed

Welcome to .NET 9.0!
---------------------
SDK Version: 9.0.111

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
   collector.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Ref. No packages exist with this id in source(s): /usr/lib/dotnet/library-packs
    collector/datacollector.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.App.Ref. No packages exist with this id in source(s): /usr/lib/dotnet/library-packs
    collector/datacollector.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-x64. No packages exist with this id in source(s): /usr/lib/dotnet/library-packs

Restore failed with 3 error(s) in 0.7s

### After having .net 8 installed, three errors reduced to one
collector/datacollector.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-x64. No packages exist with this id in source(s): /usr/lib/dotnet/library-packs

**Comment by e-tang** [comment]
Alright after creating a `global.json` to use .net 8 only, it worked.

```json
{
  "sdk": {
    "version": "8.0.121"
  }
}
```

**Comment by Forgind** [comment]
@e-tang, did you see [baronfel's comment](https://github.com/dotnet/sdk/issues/40676#issuecomment-2110857039)?

**Comment by e-tang** [comment]
I did, but it didn't work for me

**Comment by Ryan-000** [comment]
I had to remove my `~/.dotnet` folder in order to fix this
