### ISSUE TITLE
`dotnet workload` always installs maui workload as root. This is making it impossible to build a project as a regular user on Manjaro/Arch Linux

### ISSUE THREAD

**Issue by v1k7-992** [dotnet/sdk#40692]
Hi, recently I installed am trying to build a Maui app, and it seems all my projects when I either use VSCode, Rider or even `dotnet build` as a regular user, fail with this error:

```/usr/share/dotnet/sdk/8.0.204/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-android```

Running `dotnet workload list`, gives me this output:
```
dotnet workload list

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------

Use `dotnet workload list` to find additional workloads to install.
```

But running the same command as sudo I can see that I have all the workloads installed:
```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-tizen                 8.0.7/8.0.100         SDK 8.0.200        
wasi-experimental          8.0.4/8.0.100         SDK 8.0.200        
android                    34.0.95/8.0.100       SDK 8.0.200        
maui-android               8.0.7/8.0.100         SDK 8.0.200        
wasm-tools                 8.0.4/8.0.100         SDK 8.0.200       
```

What could be causing this? Could it be some odd permission problem I might have stumbled on?

More info:
I am using Manjaro Linux using dotnet version 8.0.204. The SDK, runtime and targeting tools are from the AUR.

**Comment by Forgind** [comment]
Interesting...I tried this out with 8.0.100 on ubuntu, and it didn't seem to repro even when I switched to a new user after installing a workload. I'm curious what the differences are between ubuntu and monjaro or if we have a regression between 100 and 204

**Comment by v1k7-992** [comment]
What I am using, in case of manjaro, is the AUR package for dotnet sdk. This package to be specific: https://aur.archlinux.org/packages/dotnet-sdk-bin. Could it be possible that the PKGBUILD is to blame?

**Comment by Forgind** [comment]
I downloaded the 8.0.204 package for x64 from that link, extracted the contents, and copied them into my dotnet folder. I ran dotnet workload list (empty as expected), then install maui-android (failed: need admin rights), then sudo dotnet workload install maui-android (succeeded).

Then I ran dotnet workload list again (without sudo), and it showed maui-android as installed.

It's possible there's something special with the manjaro file system where it fakes a path at some point or prevents non-admin processes from accessing things in protected directories?

**Comment by v1k7-992** [comment]
@Forgind thank you for investigating into this.

I managed to find the reason why it is not working. It seems that manjaro (and arch linux does this as well), have given incorrect permissions to the folders `/usr/share/dotnet/packs' and '/usr/share/dotnet/sdk-manifests'. What is missing is the execution permission. Without that, `dotnet build` cannot use the Maui workload pkgs, and that is why I couldn't build. It gave an error saying that the packages were not downloaded and installed in my original comment, but it's valid, although confusing abit. Setting the folders using `sudo chmod go+x sdk-manifests packs` have solved the problem. 

The solution for the future might lie in contacting the person maintaining the AUR package, that the PKGBUILD should create those two directories, and assign execution privileges for the folder. This is a little dangerous, so there probably exists a much better solution to this. Probably using groups, idk for now.

Should we close the issue here?

**Comment by Forgind** [comment]
Thanks for your help with the investigation! I asked my PM where we should go from here, and he suggested transferring this issue to another dotnet repo that is a more central location for issues related to building dotnet from source, as in this case. They should be able to help us find the optimal solution here.

**Comment by Forgind** [comment]
This issue was moved to dotnet/source-build#4397

**Comment by MichaelSimons** [comment]
Looking at the packages at https://aur.archlinux.org/packages/dotnet-sdk-bin, the source is the Microsoft produced tarballs

https://download.visualstudio.microsoft.com/download/pr/0a1b3cbd-b4af-4d0d-9ed7-0054f0e200b4/4bcc533c66379caaa91770236667aacb/dotnet-sdk-8.0.204-linux-x64.tar.gz
https://download.visualstudio.microsoft.com/download/pr/1e449990-2934-47ee-97fb-b78f0e587c98/1c92c33593932f7a86efa5aff18960ed/dotnet-sdk-8.0.204-linux-arm64.tar.gz
https://download.visualstudio.microsoft.com/download/pr/ac99d114-0422-475c-b75b-8279ff9f9a68/19efacb0358aaf945f0a8ad62a8ca718/dotnet-sdk-8.0.204-linux-arm.tar.gz

@Forgind, this should be investigated on the SDK side to ensure the correct permissions in the Microsoft tarballs first.

**Comment by marcpopMSFT** [comment]
@Forgind can you try again on ubuntu installing the workloads as sudo?

@v1k7-992 is there a reason you installed the workloads using sudo? Was your sdk installed using sudo? One option if you need to install workloads into a protected sdk is to use user local workloads. @tmds is there documentation on how to do this that ya'll put together user local workloads when you did this work originally?

**Comment by v1k7-992** [comment]
@marcpopMSFT The installation was done via `yay` utility, used for installing AUR packages. Even if I installed it via regular `makepkg` command, the installation will still put all the executable files in `/usr/bin`. I think the problem is what kind of permissions are expected by the workload utility. If I understand, the general practice is installing binaries as regular user

**Comment by marcpopMSFT** [comment]
Triage: we think the `yay` install should lay down the userlocal file but probably isn't. There is the potential for a permissions issue here as well but specifically for `yay` installs, userlocal is probably the way to go.

**Comment by marcpopMSFT** [comment]
Triage: closing as we believe the fix should be done in the yay install.
