### ISSUE TITLE
AppCommand Assignment for self-contained apps duplicate entrypoint (both self-contained and non-self-contained variants)

### ISSUE THREAD

**Issue by erikbra** [dotnet/sdk#40690]
When using `dotnet publish -t:PublishContainer --self-contained true` for a command-line app, the entrypoint includes _both_ the  `dotnet`, `<appname>.dll` and `/app/appname` commands.

Snippet below from `Microsoft.NET.Build.Containers.targets` (permalink further below). 

```xml
    <ItemGroup Label="AppCommand Assignment" Condition="'$(ContainerAppCommandInstruction)' != 'None'">
      <!-- For self-contained, invoke the native executable as a single arg -->
      <ContainerAppCommand Condition="'$(ContainerAppCommand)' == '' and '$(_ContainerIsSelfContained)' == 'true' and !$(_ContainerIsTargetingWindows)" Include="$(ContainerWorkingDirectory)/$(AssemblyName)$(_NativeExecutableExtension)" />
      <ContainerAppCommand Condition="'$(ContainerAppCommand)' == '' and '$(_ContainerIsSelfContained)' == 'true' and $(_ContainerIsTargetingWindows)" Include="$(AssemblyName)$(_NativeExecutableExtension)" />
      <!-- For non self-contained, invoke `dotnet` `app.dll` as separate args -->
      <ContainerAppCommand Condition="'$(ContainerAppCommand)' == ''" Include="dotnet;$(TargetFileName)" />
    </ItemGroup>
```
Permalink: https://github.com/dotnet/sdk/blob/5e9972aa47f3ac7a81b4d98a1ded799c750a743c/src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets#L100C1-L106C17

I **think** we should add ` and '$(_ContainerIsSelfContained)' != 'true'` to the condition, and lines 104-105 should be:

```xml
      <!-- For non self-contained, invoke `dotnet` `app.dll` as separate args -->
      <ContainerAppCommand Condition="'$(ContainerAppCommand)' == '' and '$(_ContainerIsSelfContained)' != 'true'" Include="dotnet;$(TargetFileName)" />
  ```
  
I _might_ of course be holding it wrong, but I'm trying to follow the documentation, and in my app `grate`, I get the following when I inspect the image:

```bash
dotnet publish \                                    
      -r linux-arm64 \
      -c Release \
      --self-contained true \
      -t:PublishContainer \
      -p:SelfContained=true \
      -p:PublishTrimmed=true \
      -p:PublishSingleFile=true
```

```
docker image inspect grate | jq -r '.[0].Config.Entrypoint'
[
  "/app/grate",
  "dotnet",
  "grate.dll"
]
```

I would expect this to be only `["/app/grate"]` (as I'm publishing self-contained), and `["dotnet", "grate.dll"]` if I was publishing non-self-contained. But never both variants.

**Comment by baronfel** [comment]
Good analysis @erikbra - we've been discussing this over in https://github.com/dotnet/sdk-container-builds/issues/559 and came to the same conclusion. I'm going to close this as a duplicate, but please do contribute to the conversation on the other issue.

**Comment by erikbra** [comment]
Aha, thanks a lot, @baronfel . I didn't see that one (as it was in another repo). I'll add my $.02 there instead (if it's not already said there 😄  )
