### ISSUE TITLE
Clean-up CODEOWNERS file

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#40739]
Some groups in it aren't public or don't have write permissions in the sdk repo.

https://github.com/dotnet/sdk/blob/main/CODEOWNERS shows errors

<img width="1013" alt="image" src="https://github.com/dotnet/sdk/assets/1376924/da6edfa2-e66c-4c5a-b387-7c44d34fda01">

**Comment by marcpopMSFT** [comment]
should probably be dotnet/dotnet-testing-admin
