### ISSUE TITLE
Create a `solution` alias for the existing `sln` command

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk#40817]
### Is your feature request related to a problem? Please describe.

We should add a `solution` alias to the existing `sln` command. The current implementation of the `sln` command interacts with `.sln` files, but the new `.slnx` file format logically supports many of the same commands. Some [quick](https://twitter.com/ChetHusk/status/1786454596463841600) [surveys](https://hachyderm.io/deck/@chethusk/112378449237699210) suggest that most users want the current `sln` command to interact with `.slnx` files, but the `sln` name could present some confusion. Adding a `solution` command

* uses the name of the logical concept instead of tying the command to a particular file format
* can be done in a lossless and back-compatible way
* opens up design space for a sibling `dotnet project` command
* can be tab-completed to mitigate the additional typing

**Comment by kunalshokeen051** [comment]
Hi @baronfel I am new to Open-Source Can i work on this issue.

**Comment by baronfel** [comment]
Awesome @kunalshokeen051 - I want to check with the rest of the team to make sure we want to do this, but once we chat about it and agree I'd love to accept a PR from you!

**Comment by baronfel** [comment]
@kunalshokeen051 Ok, I've taken this to the team and we're all on board with the change. If you'd like to submit a PR we'd be happy to review and help get it merged.

**Comment by Nirmal4G** [comment]
Why not the other way around?

Instead of just adding a `solution` alias to the `sln` command, can we rename the `sln` to `solution` command and make the command `sln` as a short-hand alias?

**Comment by baronfel** [comment]
That'd be fine - there's no huge functional difference.

**Comment by Nirmal4G** [comment]
@kunalshokeen051 If you still want to do it, please confirm.

**Comment by nagilson** [comment]
@marcpopMSFT Assigning this to @edvilme since the open source contributor hasn't had time to get to this one.

**Comment by mariuszbyahoo** [comment]
Hi, due to [this commit](https://github.com/dotnet/sdk/commit/8ea8db8e4927003467c6315289898afce099442a) can we close this issue?

**Comment by nagilson** [comment]
We can! Thanks!
