### ISSUE TITLE
Unable to build on new system

### ISSUE THREAD

**Issue by FroggieFrog** [dotnet/sdk#40840]
### Description

I have a new computer and tried to build my app, but I'm unable to do so.
Those messages are not helpful, because they do not work.

![maui_workload](https://github.com/dotnet/maui/assets/6222752/39428886-ae30-4894-bb2a-13f943490083)

A `dotnet workload update` also does nothing.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Android, Windows

**Comment by marcpopMSFT** [comment]
@FroggieFrog can you provide the output of `dotnet workload --info` and provide a binlog for the failure?  Thanks. The binlog should point to which pack is missing and the --info command should give us details on what state your workloads are in.

**Comment by marcpopMSFT** [comment]
Per triage, having a diag output of the workload failure that list the specific missing packs would help us avoid having to ask for a binlog.

**Comment by marcpopMSFT** [comment]
`dotnet build -getItem:MissingWorkloadPack` collects the missing pack info and is fairly easy so going with that for now.

**Comment by FroggieFrog** [comment]
After an (automatic) update the issue is gone and I can't reproduce it.

![grafik](https://github.com/dotnet/sdk/assets/6222752/c670b25d-2c3c-4fba-aae5-9a8f0779dbec)

**Comment by marcpopMSFT** [comment]
Triage: Glad to hear you're unblocked though I'm sorry we weren't able to collect enough information to determined what happened. Closing for now but ping us if it happens again.
