### ISSUE TITLE
Download cmake failure when running restore.cmd

### ISSUE THREAD

**Issue by v-wuzhai** [dotnet/sdk#40859]
### Describe the bug
I encountered an issue when running restore.cmd in the sdk folder after cloning the https://github.com/dotnet/sdk repo. Here's the error message I received:
```
Processing C:\Users\AzureTest\Desktop\ww\sdk\global.json
WARNING: Download failed, 4 attempts remaining, will retry in 30 seconds
WARNING: Download failed, 3 attempts remaining, will retry in 30 seconds
WARNING: Download failed, 2 attempts remaining, will retry in 30 seconds
WARNING: Download failed, 1 attempts remaining, will retry in 30 seconds
CommonLibrary\Get-File : BlobNotFoundThe specified blob does not exist.
RequestId:93e4cfc6-301e-001b-41e8-a55b63000000
Time:2024-05-14T10:21:11.6832169Z
At C:\Users\AzureTest\Desktop\ww\sdk\eng\common\native\CommonLibrary.psm1:43 char:21
+   $DownloadStatus = CommonLibrary\Get-File -Uri $Uri `
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-File

CommonLibrary\Get-File : System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Users\AzureTest\Desktop\ww\sdk\eng\common\native\CommonLibrary.psm1:43 char:21
+   $DownloadStatus = CommonLibrary\Get-File -Uri $Uri `
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-File

CommonLibrary\DownloadAndExtract : Download failed from
https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/cmake/cmake-latest-win64-x64.zip
At C:\Users\AzureTest\Desktop\ww\sdk\eng\common\native\install-tool.ps1:90 char:22
+     $InstallStatus = CommonLibrary\DownloadAndExtract -Uri $Uri `
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DownloadAndExtract

Installation failed
cmake installation failed
```

### To Reproduce
- Clone the repo: git clone https://github.com/dotnet/sdk.git
- Navigate to the sdk folder: cd sdk
- Run restore.cmd

### Exceptions (if any)
N/A

### Further technical details
- `dotnet --info`

.NET SDK:
 Version:           9.0.100-preview.5.24262.2
 Commit:            1741345c63
 Workload version:  9.0.100-manifests.bfee6d9b
 MSBuild version:   17.11.0-preview-24256-01+66dcc32c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.5.24262.2\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.34902.84
   Manifest Version:    9.0.0-preview.4.24229.9/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.4.24229.9\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.0-preview.5.24256.1
  Architecture: x64
  Commit:       84b3339505

.NET SDKs installed:
  8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.5.24262.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.5.24256.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24256.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.5.24256.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
@joeloff @MiYanni with the repo merge, we need to update developer guidance on cmake. Can that be excluded on the default build so we don't require VS for that?
