### ISSUE TITLE
[NETSDKE2E][ARM64]After installing net9preview4SDK on the arm64OS, create the MStest project and run dotnet test. The generated log is x64.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#40857]
Build:
9.0.100-preview.4.24260.3

Repro steps:
1.Install .net9 preview4 SDK on arm64.
2.Create a MStest project in CLI.
`dotnet new mstest`
3.Add test code in UnitTest1.cs
`notepad UnitTest1.cs`
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace TestProject3
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.AreEqual(11, 11);
        }
        [TestMethod]
        public void TestMethod2()
        {
            Assert.AreEqual(1, 11);
        }
        [TestMethod]
        public void TestMethod3()
        {
            Assert.Inconclusive();
        }
    }
}
```
4.run `dotnet build`
5.run `dotnet test`

Expected Result:
The generated log should default to arm64.

Actual Result:
The generated log is x64.
![1](https://github.com/dotnet/sdk/assets/106054229/6a7e1fec-46a0-4ff8-a845-96600c756592)
note:
In `dotnet test --help`, I did not see the prompt that the default generated log is x64.
![image](https://github.com/dotnet/sdk/assets/106054229/84f275c1-9fa3-468d-bf76-55765c58b5b1)
![image](https://github.com/dotnet/sdk/assets/106054229/2261e8c8-dd28-4248-9e39-7dda6456bc43)
![image](https://github.com/dotnet/sdk/assets/106054229/ad736443-a502-4787-b003-ad4143a4ad91)

**Comment by v-xiaofchen** [comment]
This issue also repro on Mac-arm64 OS.
![image](https://github.com/dotnet/sdk/assets/99376012/4b755f20-e57e-4ec5-9b4e-4d050387057f)

**Comment by v-ainigao** [comment]
@MarcoRossignoli This issue is still repro in .net9preview4, I want to know the reason for the close and can we ignore it?
![image](https://github.com/dotnet/sdk/assets/106054229/04773744-8c5b-436d-b2f0-bc6b57674c74)

**Comment by MarcoRossignoli** [comment]
Sorry for the confusion this issue is not related to the SDK self but to the testing platform where the core sources resides here https://github.com/microsoft/testfx

The issue is inside the package https://www.nuget.org/packages/Microsoft.Testing.Platform.MSBuild that's closed source. We fixed it and will be soon shipped.

cc: @Evangelink @nohwnd

**Comment by v-ainigao** [comment]
> Sorry for the confusion this issue is not related to the SDK self but to the testing platform where the core sources resides here https://github.com/microsoft/testfx/tree/main/src/Platform/Microsoft.Testing.Platform
> 
> The issue is inside the package https://www.nuget.org/packages/Microsoft.Testing.Platform.MSBuild that's closed source. We fixed it and will be soon shipped.
> 
> Also it's a UX/filename issue the application will run with the correct architecture.
> 
> cc: @Evangelink @nohwnd

Okay, thank you for your explanation, I'll keep checking until the right platform shows up.

**Comment by MarcoRossignoli** [comment]
Most likely will be fixed in the next patch version of MSTest, @Evangelink can you confirm or give some ETA?

**Comment by Evangelink** [comment]
I will be releasing a fix tomorrow or on Wednesday.

**Comment by v-ainigao** [comment]
This issue also repro's in .net9preview5.Is it still under fixed?
![image](https://github.com/dotnet/sdk/assets/106054229/9d57fc80-cbfa-49cd-8777-055eb66de0f0)

**Comment by Evangelink** [comment]
Sorry @v-ainigao, we got a couple of other bug fixes to include. I have just done the release and will update the test-template now.

**Comment by v-ainigao** [comment]
> Sorry @v-ainigao, we got a couple of other bug fixes to include. I have just done the release and will update the test-template now.

That's all right, I will keep tracking. thank you.

**Comment by v-xiaofchen** [comment]
@Evangelink 
This issue is still repro on 9.0.100-preview.5.24303.21 (runtime-9.0.0-preview.5.24280.5), could you help to take a look.
![image](https://github.com/dotnet/sdk/assets/99376012/c6c99c25-5aa6-4036-bd9d-9fe9c55fb01c)

**Comment by v-ainigao** [comment]
> @v-xiaofchen sorry for the delay I was off last week. The templates have been updated as part of preview 6.

This issue has been fixed on ARM64OS with .net9.0.100-preview.6.24311.1SDK, thanks.
![image](https://github.com/dotnet/sdk/assets/106054229/6af50f48-8cfe-49c4-97d2-ea5a68b3f885)
