### ISSUE TITLE
Trivy scanning of dotnet-sdk 8.0

### ISSUE THREAD

**Issue by AshwinSridharan0410** [dotnet/sdk#40894]
Hi. My requirement is to install dotnet-sdk 8.0 in my docker image through Dockerfile. After building it , when I use trivy to scan the image, I get the following errors:-

![image](https://github.com/dotnet/sdk/assets/113506379/b7fcbc63-a3d2-48ff-b747-e19e4fac9bde)
Command used:- trivy image --severity HIGH,CRITICAL --ignore-unfixed image_name

Dockerfile
FROM polarisci-tempered-docker-virtual.jfrog-prod.debsreplatform.cloud/base/dependencies/stable:2.0.2
RUN apt-get update && apt-get install -y dotnet-sdk-8.0

**Comment by baronfel** [comment]
That's a pretty old SDK image - can you use a newer version of the SDK image (may need to re-pull to refresh the image) and check again? We've done work here recently to clean up all of these false positives from Trivy and other scanning tools.

**Comment by AshwinSridharan0410** [comment]
Thanks @baronfel . Will look up to it
