### ISSUE TITLE
Slow Ping

### ISSUE THREAD

**Issue by aliajboy** [dotnet/sdk#40989]
### Describe the bug
I want to ping about 180 IPs that most of them, say about 175 of them are disconnected from local network and respond timeout. I know about this and I set timeout in `Ping` Command to 10ms so It shouldn't take a lot of time! BUT It takes 110 seconds to complete that is about 600ms. I tested `async/await` and without that, I used `foreach` and `await Task.WhenAll` but non of them seem to work, It is really weird. when I have them connected, I can say that this process takes about 1 sec to complete! I assume that this `timeout` setting in `Ping` command is just Ridiculous and doesn't do a thing. If this works, assume that all the IPs are dead, It should take 1.8 seconds to complete.

one of my codes:

            string data = "aaaaaaaaaaaaaaaa";
            byte[] byteBuffer = Encoding.ASCII.GetBytes(data);
            var list = new List<Task<PingReply>>();
            foreach (var item in model)
            {
                list.Add(new Ping().SendPingAsync(item.DevIPWIFI,10,byteBuffer));  // no await here
            }
            var replies = await Task.WhenAll(list);`

the other one:

            foreach (var item in model)
            {
                PingReply reply = new Ping().Send(item.DevIPWIFI,10);
            }`

and tested this one either:
`PingReply reply = await new Ping().SendPingAsync(item.DevIPWIFI,10); // And this one with await`

### To Reproduce
make a list of 180 IPs that are disconnected and respond with timeout. Use `SendPingAsync()` or `Send()` Method to get respond.

### Exceptions (if any)
NONE

### Further technical details
- Dotnet 8.0.5
- VS 17.9.7
- Windows 10

**Comment by baronfel** [comment]
Hello - this is a question about using the libraries or C# language, not a question or problem with the .NET SDK or tooling. I'm going to close this as a result, but you should consider asking your questions on places like [StackOverflow ](https://stackoverflow.com/questions/tagged/c%23) or the [.NET Discord](https://aka.ms/dotnet-discord).

**Comment by aliajboy** [comment]
I have asked in StackOverflow but no one knows about it. thay all help me with await Task.WhenAll() but the problem exist. 
I ask you @baronfel a question because of your reaction to my question and closing this issue. The `Ping` Class is in Dotnet SDK and not in any other library, `Async/Await` too! so why did you respond like that? does stackoverflow is the developer of dotnet? I asked here because `timeout` doesn't work as I expected! If you are a developer of dotnet, you should know these.

**Comment by baronfel** [comment]
The SDK is the tooling - not the base class library. I didn't realize Ping was in the base class libraries - in that case I'd suggest opening this issue on dotnet/runtime, where the libraries are developed.
