### ISSUE TITLE
Bring in Perf Fixes to Deps.Json exclusion List logic.

### ISSUE THREAD

**Issue by brthor** [dotnet/sdk#41]
Deps.json exclusion list building uses inefficient graph walking algorithms that unnecessarily re-walk nodes in the dependency graph wasting .5+ second each graph walk.

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.DotNet.Core.Build.Tasks/DependencyContextBuilder.cs

Port the fixes from https://github.com/dotnet/cli/pull/3942

@eerhardt

**Comment by eerhardt** [comment]
This has been fixed.

See
https://github.com/dotnet/sdk/pull/212/files#diff-4990a65adbd037c1439e2a45a9989596R78
