### ISSUE TITLE
[NETSDKE2E]Runing project failed with net9 preview 4 sdk after allowEnforceSignCI policy enabled.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41010]
1.	Create a windows11 VM 
2.	Copy the CIP file
[allowEnforceSignCI.zip](https://github.com/dotnet/sdk/files/15373457/allowEnforceSignCI.zip)

3.	Open an admin prompt and run citool --update-policy allowEnforceSignCI.cip
4.	Restart the machine
5.	Try to install the latest build 9.0.100-preview.4.24267.66. after installation is done, create a project, build and run

**Expected Result:**
net9 preview 4 sdk can be installed successfully and Project can be created and build and run successfully

**Actual Result:**
net9 preview 4 sdk can be installed successfully and Project can be created, build successfully, but **run failed with below error**
![image](https://github.com/dotnet/sdk/assets/65637796/ff24bbfa-90a1-44e1-b5bb-2c021202f28f)

dotnet --info
.NET SDK:
Version:           9.0.100-preview.4.24267.66
Commit:            26d3d259e4
Workload version:  9.0.100-manifests.9cd308e3
MSBuild version:   17.11.0-preview-24225-01+bd0b1e466
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.4.24267.66\
 
.NET workloads installed:
[wasm-tools]
   Installation Source: SDK 9.0.100-preview.4
   Manifest Version:    9.0.0-preview.4.24266.19/9.0.100-preview.4
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.4.24266.19\WorkloadManifest.json
   Install Type:              Msi
 
 
Host:
  Version:      9.0.0-preview.4.24266.19
  Architecture: x64
  Commit:       d0d6fed6c0
 
.NET SDKs installed:
  9.0.100-preview.4.24267.66 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.4.24267.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by joeloff** [comment]
This is by design. Once you have the CI policy configured, only applications signed with the designated PCA publisher certificates can be executed. You'll need to remove the policy, restart and then continue with normal testing.
