### ISSUE TITLE
VMR Unified Linux Build Failing

### ISSUE THREAD

**Issue by nagilson** [dotnet/sdk#41030]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=681196
Build error leg or test failing: VMR Vertical Build / Ubuntu2404_x64 / Build
Pull request: https://github.com/dotnet/sdk/pull/41015

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "/vmr/repo-projects/Directory.Build.targets(430,5): error MSB3073",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
error MSB3073: The command "/vmr/src/nuget-client/eng/dotnet-build/build.sh  --ci --configuration Release -bl /p:DotNetBuildRepo=true /p:DotNetBuildOrchestrator=true /p:RestoreConfigFile=/vmr/artifacts/obj/nuget-client/NuGet.Config /p:SourceBuiltAssetsDir=/vmr/artifacts/assets/Release/ /p:SourceBuiltAssetManifestsDir=/vmr/artifacts/obj/AssetManifests/nuget-client/ /p:GenerateResourceUsePreserializedResources=true /p:SourceBuiltShippingPackagesDir=/vmr/artifacts/packages/Release/Shipping/nuget-client/ /p:SourceBuiltNonShippingPackagesDir=/vmr/artifacts/packages/Release/NonShipping/nuget-client/ /v:minimal > /vmr/artifacts/log/Release/nuget-client.log 2>&1" exited with code 1
```

```
CSC : error AD0001: Analyzer 'Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/vmr/src/nuget-client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj::TargetFramework=netstandard2.0]
  /vmr/src/nuget-client/build/build.proj(176,5): error MSB4181: The "MSBuild" task returned false but did not log an error.
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=681196
**Error message validated:** `[/vmr/repo-projects/Directory.Build.targets(430,5): error MSB3073`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/20/2024 8:39:37 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ViktorHofer** [comment]
Related: https://github.com/dotnet/roslyn-analyzers/issues/7315
