### ISSUE TITLE
User secret value can't have a dash (-) as a prefix

### ISSUE THREAD

**Issue by tuscen** [dotnet/sdk#4106]
When trying to add a secret with a value prefixed with a dash I get the following error

```
$ dotnet user-secrets set KEY "-1234567" 
Specify --help for a list of available options and commands.
Unrecognized option '-1234567'
```

dotnet sdk version: 3.1.100

**Comment by livarcocc** [comment]
@anurse @mkArtakMSFT should this be moved to asp.net?

**Comment by anurse** [comment]
This issue was moved to aspnet/AspNetCore#18095

**Comment by anurse** [comment]
Done. Probably a bug in the tool rather than the runtime stuff, but that tool lives in aspnet/AspNetCore as well ;).
