### ISSUE TITLE
Is Microsoft.NET.Test.Sdk open source?

### ISSUE THREAD

**Issue by gulbanana** [dotnet/sdk#411]
I can't find code for it in this repository, and `dotnet test` doesn't seem to work without it.

**Comment by srivatsn** [comment]
Tagging @sbaid @codito @singhsarab for comments.

**Comment by GuardRex** [comment]
I guess this comment is relevant: https://github.com/dotnet/sdk/issues/403#issuecomment-261178679

**Comment by srivatsn** [comment]
I think that comment refers to the Web SDK repo which is another repo that needs to be made public.

**Comment by codito** [comment]
@gulbanana Microsoft.NET.Test.Sdk source is in another repository. We are working on a plan to open it up shortly.

**Comment by gulbanana** [comment]
OK, I iso look forward to it. I'd like the source to look into some issues such as net461 tests not working well and rightclick-> go to test not finding sources,

**Comment by gulbanana** [comment]
ping - still having problems with the new test code as of RC2 and in the absence of docs it'd be great to at least look at the source.

**Comment by codito** [comment]
@gulbanana sorry, this work is still in progress. Can you please file an issue for the problems you're facing? We will work with you to find a solution.

**Comment by gulbanana** [comment]
Thanks, but I've already filed issues for the individual problems. Here are some:
https://github.com/dotnet/roslyn-project-system/issues/826
https://github.com/dotnet/roslyn-project-system/issues/827
https://github.com/dotnet/roslyn-project-system/issues/975
https://github.com/dotnet/roslyn-project-system/issues/976

The cases where I'm finding go to test broken are xUnit-based. I'd be happy to contribute some work towards that support if source or docs were available!

**Comment by gulbanana** [comment]
Happy new year, how is this going? It'd be great to be able to verify some of these testing scenarios *before* RTM. My org is highly dependent on automated testing and I want to help ensure that VS2017 will be a successful update for us.

**Comment by pvlakshm** [comment]
@gulbanana Yes, we are now open source! https://github.com/Microsoft/vstest
Please keep the feedback coming!

**Comment by gulbanana** [comment]
fantastic news, thank you!
