### ISSUE TITLE
dotnet/sdk README links point to dotnet/installer which points back to dotnet/sdk

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/sdk#41118]
dotnet/sdk's Latest Builds link points to dotnet/installer:
![image](https://github.com/dotnet/sdk/assets/203839/b8657927-d96e-420c-a1c2-d8bbafe50a3e)

Which points back to dotnet/sdk:
![image](https://github.com/dotnet/sdk/assets/203839/74d763dd-78f1-4d87-8332-8a48ff4f5dcf)

Where can I find the nightly builds? cc @MiYanni

**Comment by MiYanni** [comment]
https://github.com/dotnet/sdk/pull/41098
