### ISSUE TITLE
Repository consolidation

### ISSUE THREAD

**Issue by filipnavara** [dotnet/sdk#41127]
So, someone decided to consolidate https://github.com/dotnet/installer and https://github.com/dotnet/sdk. That's fine. There was no advanced warning and now there's no access to nightly builds. The dotnet/sdk repo points to dotnet/installer which in turn points back to dotnet/sdk. This is not how the migrations should be handled, please fix this and reinstate the access to nightly builds.

**Comment by baronfel** [comment]
PR here: https://github.com/dotnet/sdk/pull/41098
