### ISSUE TITLE
How to integrate dotnet/installer into SDK and download the latest unpublished preview version, such as SDK release 9.0.100-preview6.xxxx for macOS's pkg file?

### ISSUE THREAD

**Issue by ajw333** [dotnet/sdk#41137]
How to integrate dotnet/installer into SDK and download the latest unpublished preview version, such as SDK release 9.0.100-preview6.xxxx for macOS's pkg file?

**Comment by nagilson** [comment]
The installer table has been moved over to https://github.com/dotnet/sdk/blob/main/documentation/package-table.md
Let me know if that helps! Preview 6 is not out yet, preview 5 is in the works but we mainly just have the branch atm.

**Comment by nagilson** [comment]
Let us know if you have further questions.
