### ISSUE TITLE
Figure out which package other repos should use to subscribe to the sdk version

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/sdk#41156]
Microsoft.Dotnet.Sdk.Internal is used by a bunch of repos to pick up the latest SDK version:

- dotnet org: https://github.com/search?q=org%3Adotnet+MicrosoftDotnetSdkInternal+-repo%3Adotnet%2Fdotnet&type=code
- xamarin org: https://github.com/search?q=org%3Axamarin+MicrosoftDotnetSdkInternal 

We should figure out what the right replacement package is and move all existing users to that, then delete this project again.

**Comment by marcpopMSFT** [comment]
Using any of the VS transport packages should be sufficient. I think this is solved now.
