### ISSUE TITLE
global.json file SDK version is "9.0.100-preview.5.24269.5" but I dont see that SDK version anywhere

### ISSUE THREAD

**Issue by Anusha531** [dotnet/sdk#41176]
In the global.json file on the [dotnet/aspnetcore GitHub repository](https://github.com/dotnet/aspnetcore/blob/main/global.json), line 1 specifies the SDK version as "9.0.100-preview.5.24269.5". However, I couldn't find this SDK version in the [dotnet/core release notes for version 9.0](https://github.com/dotnet/core/tree/main/release-notes/9.0). Is the "9.0.100-preview.5.24269.5" version not publicly available?

**Comment by nagilson** [comment]
Thank you @kasperk81, this is the correct answer and a very thorough one. Let us know if you have further questions.
