### ISSUE TITLE
Unable to compile a cs file

### ISSUE THREAD

**Issue by prasanth-G24** [dotnet/sdk#4118]
I want to compile only one .cs file and generate a .exe
I tried so many ways but it looks like I cannot do it unless I create a project.
Is there a way to compile a .cs file similar to compiling a .java file? (Eg: javac File.java)
I am using dotnet sdk for ubuntu

**Comment by vicky1408** [comment]
Did you try 'dotnet new console' ? It basically creates single cs file 'Program.cs' and when you run it, exe will be created for the same. It does have associated files which are created to hold the meta details, but the programming logic can be implemented in 'Program.cs' only.

**Comment by livarcocc** [comment]
@vicky1408's suggestion is the best approach.

We don't support compiling a single file through dotnet.exe. In theory, you could use dotnet to invoke csc (the csharp compiler) and pass the arguments to it directly to compile just your file, but it would be much easier to have the simple project file where everything gets taken care of for you.
