### ISSUE TITLE
Incremental build skips from command line every time

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#412]
(Moved from: https://github.com/dotnet/roslyn-project-system/issues/781)

After creating a "Console App (.NET Core)" project, edit it so it multi-targets:

```xml
<Project ToolsVersion="15.0">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" Condition="'$(TargetFramework)' == 'netcoreapp1.0'"/>
    <PackageReference Include="Microsoft.NET.Sdk" Version="1.0.0-alpha-20161116-2">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Now from the command line, build it once:

    msbuild /t:restore,rebuild

Now change program.cs (or the project file) and build again:

    msbuild

**Expected**
An incremental build will recompile the source file for each target framework.

**Actual**
No build occurs. It skips.

```
msbuild
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/20/2016 1:23:04 PM.
Project "C:\Users\andarno\Documents\Visual Studio 2017\Projects\ConsoleApp4\ConsoleApp4.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Done Building Project "C:\Users\andarno\Documents\Visual Studio 2017\Projects\ConsoleApp4\ConsoleApp4.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.14
```

Dev15: d15prerel 25917.2

**Comment by nguerrera** [comment]
@AArnott I notice this is a solution build. Does it repro if you pass in the .csproj instead to msbuild?

**Comment by AArnott** [comment]
@nguerrera Yes. It repros either way.

**Comment by nguerrera** [comment]
@AArnott Thanks for reporting this. I found the issue. Microsoft.Common.CrossTargeting.targets that replaces Microsoft.Common.CurrentVersion.targets for cross-targeting projects does not specify `DefaultTargets="Build"` as `Microsoft.Common.CurrentVersion.targets` does. Without that, plain `msbuild` is running the first target it finds, which happens to next to nothing.

The workarounds are to add `DefaultTargets="Build"` to the root `Project` element of your project or explicitly run `msbuild /t:build`. For the real fix, I will move this over to the msbuild repo where Microsoft.Common.CrossTargeting.targets lives.

**Comment by nguerrera** [comment]
Moved to Microsoft/msbuild#1364

**Comment by AArnott** [comment]
Thanks!
