### ISSUE TITLE
[NetSDKE2E][ARM64]Although we installed the .netcoreapp 3.1 runtime, Test still executed failed and show "You must install or update .NET to run this application...". 

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#41258]
Test build: 
dotnet-sdk-9.0.100-preview.5.24279.9-win-arm64
dotnet-sdk-9.0.100-preview.5.24279.9-win-x64
dotnet-sdk-9.0.100-preview.5.24279.9-win-x86
dotnet-runtime-3.1.32-win-x64
 
Note: It's regression issue. It doesn't repro on dotnet-sdk-9.0.100-preview.4.24215.10.
 
Steps:
1.Install above sdk and runtime
2.Open Powershell, execution below commands:
`dotnet new mstest`
3.Add negative method in UnitTest1.cs file
4.update below info in *.csproj file
`<TargetFrameworks>net9.0;netcoreapp3.1</TargetFrameworks>`
`<IsPackable>false</IsPackable>`
`<LangVersion>latest</LangVersion>`
5.Go to Powershell, execution below commands:
`dotnet restore`
`dotnet build`
`dotnet test --framework net9.0 --diag:log1.txt`
`dotnet test --framework netcoreapp3.1 --diag:log2.txt`

Expected Results:
Test should be run normally. 
![image](https://github.com/dotnet/sdk/assets/106054229/5fbf4508-37d0-4fbd-9286-b7f3299be576)
 
Actual Results:
Test executed failed and show "You must install or update .NET to run this application..."
![image](https://github.com/dotnet/sdk/assets/106054229/9c28070c-d787-4c92-ae3f-b9d4be0157c7)
PS C:\tmp\mststhl> dotnet test --framework netcoreapp3.1 --diag:log10.txt
C:\Program Files\dotnet\sdk\9.0.100-preview.5.24279.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(32,5): warning NETSDK1138: The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  mststhl netcoreapp3.1 succeeded with 3 warning(s) (2.4s) → bin\Debug\netcoreapp3.1\mststhl.dll
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24279.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(32,5): warning NETSDK1138: The target framework 'netcoreapp3.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
    C:\tmp\mststhl\UnitTest1.cs(19,38): warning CS8605: Unboxing a possibly null value.
    C:\tmp\mststhl\UnitTest1.cs(21,20): warning CS8602: Dereference of a possibly null reference.
  mststhl netcoreapp3.1 failed with 2 error(s) (0.1s)
    C:\Users\v-hozha1\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error :
      Tests failed: You must install or update .NET to run this application.
 
      App: C:\tmp\mststhl\bin\Debug\netcoreapp3.1\mststhl.dll
      Architecture: arm64
      Framework: 'Microsoft.NETCore.App', version '3.1.0' (arm64)
      .NET location: C:\Program Files\dotnet\
 
      The following frameworks were found:
        9.0.0-preview.5.24279.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 
      Learn more:
https://aka.ms/dotnet/app-launch-failed
 
      To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=arm64&rid=win-ar
      m64&os=win10
 
      === COMMAND LINE ===
      C:\Program Files\dotnet\dotnet.exe exec C:\tmp\mststhl\bin\Debug\netcoreapp3.1\mststhl.dll --internal-msbuild-node
       testingplatform.pipe.87e6e9e55565422690ee4a9709c6a1db
 
 
    C:\Users\v-hozha1\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error MSB4018:
      The "InvokeTestingPlatformTask" task failed unexpectedly.
      System.ArgumentNullException: Value cannot be null. (Parameter '_outputFileStream')
         at Microsoft.Testing.Platform.Helpers.ArgumentGuard.IsNotNull(Object argument, String paramName) in /_/src/Plat
      form/Microsoft.Testing.Platform/Helpers/ArgumentGuard.cs:line 16
         at Microsoft.Testing.Platform.MSBuild.InvokeTestingPlatformTask.Execute() in /_/src/Microsoft.Testing.Platform.
      MSBuild/Tasks/TestTask.cs:line 234
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLogging
      Context taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
 
Build failed with 2 error(s) and 3 warning(s) in 2.8s

dotnet --info:
![image](https://github.com/dotnet/sdk/assets/106054229/aa2bb54b-1430-47f2-bca0-5dd9d1e5802e)
![image](https://github.com/dotnet/sdk/assets/106054229/cdfe4937-233d-49ad-880d-e081b34f2330)

**Comment by MarcoRossignoli** [comment]
Fix will be shipped in MSTest 3.5/1.3 @Evangelink bump the template when you'll ship so we can give it a try.

For now @v-ainigao you can test with xunit or with the same workaround explained here https://github.com/dotnet/sdk/issues/41256

**Comment by MarcoRossignoli** [comment]
Also arm64 version for netcoreapp3.1 in Windows is not supported https://dotnet.microsoft.com/en-us/download/dotnet/3.1 for what I know, @vitek-karas can you confirm?

**Comment by vitek-karas** [comment]
> Also arm64 version for netcoreapp3.1 in Windows is not supported https://dotnet.microsoft.com/en-us/download/dotnet/3.1 for what I know, @vitek-karas can you confirm?

Correct

**Comment by v-ainigao** [comment]
> Fix will be shipped in MSTest 3.5/1.3 @Evangelink bump the template when you'll ship so we can give it a try.
> 
> For now @v-ainigao you can test with xunit or with the same workaround explained here #41256
> 
> Also the new MSTest template is using the new MSTest runner so the argument `--diag` is no more available
> 
> You can read information about the new runner here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro

fine, thanks.

**Comment by v-hozha1** [comment]
> Fix will be shipped in MSTest 3.5/1.3 @Evangelink bump the template when you'll ship so we can give it a try.
> 
> For now @v-ainigao you can test with xunit or with the same workaround explained here #41256
> 
> Also the new MSTest template is using the new MSTest runner so the argument `--diag` is no more available
> 
> You can read information about the new runner here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro

If we add the parameter "TestingPlatformDotnetTestSupport" in property, this issue will be resolved on Win ARM. Details please refer to below screenshot.
![image](https://github.com/dotnet/sdk/assets/100275240/7195bba9-aec2-4ddd-8bc0-2294911f0838)
