### ISSUE TITLE
[NETSDKE2E]"Unhandled exception. System.IO.FileLoadException: Could not load file or assembly..." show in Output after running "dotnet test --arch x86."

### ISSUE THREAD

**Issue by v-ivyzuo** [dotnet/sdk#41256]
Test build: 
dotnet-sdk-9.0.100-preview.5.24279.5-win-x86
dotnet-sdk-9.0.100-preview.5.24279.5-win-x64
 
Test build link: 
https://aka.ms/dotnet/9.0.1xx-preview5/daily/dotnet-sdk-win-x64.exe
https://aka.ms/dotnet/9.0.1xx-preview5/daily/dotnet-sdk-win-x86.exe
 
Steps:
Install .net9
2. Open Powershell, execution below commands:
dotnet new mstest
add negative method in UnitTest1.cs file
dotnet restore
dotnet test
dotnet test --arch x86  Or "C:\Program Files (x86)\dotnet\dotnet.exe" test --arch x64
Expected Results:
![image](https://github.com/dotnet/sdk/assets/165889884/75f90b95-4454-4ebd-95f8-2a0db1a234ec)

 

Actual Results:
![image](https://github.com/dotnet/sdk/assets/165889884/47f35d78-915f-44b5-bf02-b65c66805156)
![image](https://github.com/dotnet/sdk/assets/165889884/bfb75437-47ba-4ea1-9bac-851eb5d01865)

"Unhandled exception. System.IO.FileLoadException: Could not load file or assembly..." show in Output. 
PS C:\tmp\mstestnew1> dotnet test --arch x86
Restore complete (0.8s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  mstestnew1 succeeded (1.0s) → bin\Debug\net9.0\win-x86\mstestnew1.dll
  mstestnew1 failed with 2 error(s) (2.7s)
    C:\Users\v-hozha1\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error :
      Tests failed: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\tmp\mstestnew1\bin\Debug\net9.0\win-x86\mstestnew1.dll'. The assembly architecture is not compatible with the current process archi
      tecture.
      File name: 'C:\tmp\mstestnew1\bin\Debug\net9.0\win-x86\mstestnew1.dll'
 
      === COMMAND LINE ===
      C:\Program Files\dotnet\dotnet.exe exec C:\tmp\mstestnew1\bin\Debug\net9.0\win-x86\mstestnew1.dll --internal-msbuild-node testingplatform.pipe.1d2f5b10e7244462adf39344c85d7f39
 
 
    C:\Users\v-hozha1\.nuget\packages\microsoft.testing.platform.msbuild\1.1.0\buildMultiTargeting\Microsoft.Testing.Platform.MSBuild.targets(228,5): error MSB4018:
      The "InvokeTestingPlatformTask" task failed unexpectedly.
      System.ArgumentNullException: Value cannot be null. (Parameter '_outputFileStream')
         at Microsoft.Testing.Platform.Helpers.ArgumentGuard.IsNotNull(Object argument, String paramName) in /_/src/Platform/Microsoft.Testing.Platform/Helpers/ArgumentGuard.cs:line 16
         at Microsoft.Testing.Platform.MSBuild.InvokeTestingPlatformTask.Execute() in /_/src/Microsoft.Testing.Platform.MSBuild/Tasks/TestTask.cs:line 234
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
 
Build failed with 2 error(s) in 5.1s

dotnet --info:
![image](https://github.com/dotnet/sdk/assets/165889884/ec2abf68-c75e-44bc-8ca2-3044dfda7f89)
![image](https://github.com/dotnet/sdk/assets/165889884/5d345303-e5b6-4b82-aab6-61089d388585)

**Comment by richaverma1** [comment]
@pavelhorak , @Evangelink can you take a look?

**Comment by pavelhorak** [comment]
@MarcoRossignoli can you look at this?

**Comment by MarcoRossignoli** [comment]
Yep I got the issue the integration of the new testing platform with dotnet test doesn't support the `--arch` switch at the moment. I'll investigate on how to add the support.

**Comment by richaverma1** [comment]
@MarcoRossignoli can .NET 9 Preview 5 ship with this bug?

**Comment by MarcoRossignoli** [comment]
I think so it will affect only the new template of mstest.

@v-ivyzuo can you add this property to the test project and retry?

`<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>`

**Comment by v-hozha1** [comment]
> I think so it will affect only the new template of mstest for .NET 9 and we have a workaround. We want to ship .NET 9 with the new runner as default for mstest template(https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro) but we're missing one piece from the `dotnet test` implementation side.
> 
> @v-ivyzuo can you add this property to the test project and retry?
> 
> `<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>`
> 
> @v-ivyzuo it should not happen if you use xunit instead of mstest `dotnet new xunit`
> 
> It's also affecting only the scenario where users run with `--arch` not so frequent to not say rare from my experience.
> 
> cc: @Evangelink

1. If we add "<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>" in property, this issue will be resolved. Details please refer to below screenshot.
![image](https://github.com/dotnet/sdk/assets/100275240/29550137-75ad-45e0-a016-730dbb383adc)

2. I tried the case by using xunit. This issue doesn't repro for xunit project.
![image](https://github.com/dotnet/sdk/assets/100275240/725f6d68-5f1c-486f-b96d-4bcfa3ee8284)

**Comment by MarcoRossignoli** [comment]
Fix will be shipped in MSTest 3.5/1.3 @Evangelink bump the template when you'll ship so we can give it a try.

For now @v-ainigao you can test with xunit or with the same workaround explained here https://github.com/dotnet/sdk/issues/41256

Also the new MSTest template is using the new MSTest runner so the argument `--diag` is no more available

You can read information about the new runner here https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro
