### ISSUE TITLE
Container tests started failing with the runtime insertion

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#41272]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=691159
Build error leg or test failing: Microsoft.NET.Build.Containers.IntegrationTests.DockerRegistryTests.GetFromRegistry
Pull request: https://github.com/dotnet/sdk/pull/41096

## Error Message

System.InvalidOperationException : The registry was not loaded after 5 retries. Spawn registry attempt #1 failed, System.ApplicationException: CONTAINER1001: Failed to upload blob using PUT http://localhost:5010/v2/dotnet/runtime/blobs/uploads/57f87bc6-59e4-4a01-9a3b-6e34ebded2c5?_state=k9ejIPvrcEDUlEQu7SFVjAgYn6BWli4vqsE0fLT1aVJ7Ik5hbWUiOiJkb3RuZXQvcnVudGltZSIsIlVVSUQiOiI1N2Y4N2JjNi01OWU0LTRhMDEtOWEzYi02ZTM0ZWJkZWQyYzUiLCJPZmZzZXQiOjE0OTY3MzEzLCJTdGFydGVkQXQiOiIyMDI0LTA1LTI5VDE0OjU2OjA5WiJ9&digest=sha256%3Aaff7a9c037c8fa6f1c4f3fbbf33d19a638633b2d47eaece0411fed15cb3e10c6; received status code 'BadRequest'.
   

```json
{
  "ErrorMessage": "The registry was not loaded after 5 retries",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=691159
**Error message validated:** `[The registry was not loaded after 5 retries`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/30/2024 4:30:19 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[691159](https://dev.azure.com/dnceng-public/public/_build/results?buildId=691159)|dotnet/sdk|[Microsoft.NET.Build.Containers.Tasks.IntegrationTests.CreateNewImageTests.Tasks_EndToEnd_With_EnvironmentVariable_Validation](https://dev.azure.com/dnceng-public/public/_build/results?buildId=691159&view=ms.vss-test-web.build-test-results-tab&runId=17168316&resultId=103088)|dotnet/sdk#41096|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by MichalPavlik** [comment]
Closing this issue as the dependencies PR was merged and tests are green.
