### ISSUE TITLE
Add `dotnet nuget push --skip-duplicates` synonym for `--skip-duplicate`

### ISSUE THREAD

**Issue by Smaug123** [dotnet/sdk#41289]
### Is your feature request related to a problem? Please describe.

For at least two reasons, there is a strong basin of attraction leading users to `--skip-duplicates` rather than the (correct) `--skip-duplicate`:

* "Skip duplicate" is ungrammatical; "skip duplicates" is grammatically correct.
* `dotnet nuget push` is capable of pushing multiple packages in the same invocation.

In fact over the past year or so I have incorrectly spelled the argument `--skip-duplicates` twice (to the best of my recollection).

### Describe the solution you'd like
Add a synonym `--skip-duplicates` for `--skip-duplicate`.

**Comment by baronfel** [comment]
Seems super reasonable, but I'm actually more interested in why you didn't get any sort of 'unrecognized flag' error from nuget push here. I think if you got a parse error from the CLI that would have fixed things up clearly and quickly.

**Comment by Smaug123** [comment]
Oh, I did get a decent error when I ran it - the context is an automated pipeline pushing in a privileged environment, so I didn't attempt to run the command until its specification was already committed to `main`. (It's not the kind of command that one runs until you actually intend to perform a push! cf https://github.com/dotnet/sdk/issues/41284)
