### ISSUE TITLE
Failed to create a 6.0 project with error "error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.32)" After installing the June service .net 8.0 sdk

### ISSUE THREAD

**Issue by jamesbaldwintan** [dotnet/sdk#41297]
**INSTALL STEPS**
 
1. Clean machine: Win11 x64 ENU 23H2 
2. Install 17.8(latest-released-build) from https://aka.ms/vs/17/release.ltsc.17.8/vs_enterprise.exe

   * Web workload
   * 8.0 SDK (included by default)
   * Check 6.0 runtime

4. Install Jun Servicing .NET 8.0.107 SDK
5. Apply 8.0 feed and do feed workaround.
 
**Repro Steps**
1. Create a Razor app:
`dotnet new razor -f net6.0`

**Note**
1. This issue reproduces even with 6.0.32 feed added
2. This issue reproduces even if the project was created in VS
![image](https://github.com/dotnet/sdk/assets/159000508/4b661f64-53de-4bc0-a569-4aeeb53e97ac)

**Actual Result**
Project could not be created with 6.0
![image](https://github.com/dotnet/sdk/assets/159000508/0441e9e5-e679-4485-8a58-a4a9daeab494)

**Error Log**
C:\Users\v-jametan\v-jametan.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.
0.32)
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 116 version(s) in nuget.org [ Nearest version: 7.0.0-prev
iew.1.22076.8 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 1 version(s) in net8 [ Nearest version: 8.0.7 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in net6
C:\Users\v-jametan\v-jametan.csproj : error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Ref with versio
n (= 6.0.32)
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 112 version(s) in nuget.org [ Nearest version: 7.0.0-prev
iew.1.22077.5 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 1 version(s) in net8 [ Nearest version: 8.0.7 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in net6
C:\Users\v-jametan\v-jametan.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with vers
ion (= 6.0.32)
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 165 version(s) in nuget.org [ Nearest version: 7.0.0-prev
iew.1.22076.8 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 1 version(s) in net8 [ Nearest version: 8.0.7 ]
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\v-jametan\v-jametan.csproj : error NU1102:   - Found 0 version(s) in net6

**Test Environment**
```
Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       63d80966a9

.NET SDKs installed:
  8.0.105 [C:\Program Files\dotnet\sdk]
  8.0.107 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by marcpopMSFT** [comment]
You added the private net6 feed from dnceng/internal? 6.0.424-servicing.24271.15-shipping?

**Comment by jamesbaldwintan** [comment]
@marcpopMSFT yes, I added that feed to see if it would work.

**Comment by jamesbaldwintan** [comment]
@marcpopMSFT This issue does not reproduce with latest Jun Servicing .NET 8.0 SDK (runtime: 8.0.6).

**Test Environment**
```
Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]
  8.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by marcpopMSFT** [comment]
We plan on rebuilding the original builds flagged by this issue for July and don't plan on shipping them so I'm going to close out this issue. We should keep an eye on it as we test the July release. The 8.0.302 hotfix build is the only one shipping (not sure if that's the version of 302 you tested above or if that was the original June build).
