### ISSUE TITLE
[NETSDKE2E]With net9 preview 5 SDK isntalled, install wasm-toos/maui failed with error "Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-preview.5.24273.1' is lower than version '9.0.0-preview.6.24272.2' required by manifest 'microsoft.net.workload.mono.toolchain.current' ..."

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41304]
1. install net9 preview 5 sdk(9.0.100-preview.5.24274.11) on win11-x64
2. install wasm-tools/maui in CLI:
dotnet new wasm-tools --skip-sign-check
or donet workload install maui --skip-sign-check

**Expected Result:**
workload installd successfully.

**Actual Result:**
workload installs failed with below error.
![image](https://github.com/dotnet/installer/assets/65637796/87afd9d4-a529-45a0-9a1a-67ca78115e38)
Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-preview.5.24273.1' is lower than version '9.0.0-preview.6.24272.2' required by manifest 'microsoft.net.workload.mono.toolchain.current' [C:\Users\v-damu\Downloads\dotnet-sdk-9\sdk-manifests\9.0.100-preview.5\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.5.24275.1\WorkloadManifest.json]

![image](https://github.com/dotnet/installer/assets/65637796/4e18a37c-e7c0-40b9-9335-a7f68732ffaf)

dotnet --info:
.NET SDK:
Version:           9.0.100-preview.5.24274.11
Commit:            2fde5ca13c
Workload version:  9.0.100-manifests.b2a38daf
MSBuild version:   17.11.0-preview-24274-04+72f42c415
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Users\v-damu\Downloads\dotnet-sdk-9\sdk\9.0.100-preview.5.24274.11\
 
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-preview.5.24272.2
  Architecture: x64
  Commit:       5c06e5d01f
 
.NET SDKs installed:
  9.0.100-preview.5.24274.11 [C:\Users\v-damu\Downloads\dotnet-sdk-9\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.5.24271.5 [C:\Users\v-damu\Downloads\dotnet-sdk-9\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24272.2 [C:\Users\v-damu\Downloads\dotnet-sdk-9\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.5.24271.5 [C:\Users\v-damu\Downloads\dotnet-sdk-9\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by vdanche** [comment]
install android workload
![image](https://github.com/dotnet/sdk/assets/65637796/b59f9137-f766-4fc1-a3cc-9d598bd0accf)

**Comment by vdanche** [comment]
in today's candidate build(9.0.100-preview.5.24304.3(runtime-9.0.0-preview.5.24280.5)) with exe installer, install maui workload still failed.
![image](https://github.com/dotnet/sdk/assets/65637796/8df67a50-f747-404c-bd9e-171575beec57)

note:
with zip installer on win11-x64, maui workload can be installed successfully.
![image](https://github.com/dotnet/sdk/assets/65637796/7d1e1e6a-16df-410b-baa7-6af8711722b2)

**Comment by vdanche** [comment]
@joeloff on the latest net9 p5 candidate build-9.0.100-preview.5.24305.12(runtime-9.0.0-preview.5.24304.9), install maui workload still failed as lacking 8.0.40 microsoft.maui.sdk.msi.x64 package. Can you help to take a look?Thanks.
![image](https://github.com/dotnet/sdk/assets/65637796/596b5c92-37a3-4ef4-8ca6-4775de6dba73)

FYI @richaverma1

**Comment by vdanche** [comment]
Today install maui successfully(dotnet workload install maui --skip-sign-check)
![image](https://github.com/dotnet/sdk/assets/65637796/99d2c58a-f834-4fdb-80ab-751cacb7029d)

@joeloff  For manifest version is correct, right?

**Comment by vdanche** [comment]
maui/wasm-tools workloads can be installed successfully on 9.0.100-preview.5.24307.3(runtime-9.0.0-preview.5.24306.7). and we think below manifest version is correct which is pointing xxxx/9.0.100-preview.5, hence close it
![image](https://github.com/dotnet/sdk/assets/65637796/06ee7dc6-415c-41cd-9770-fdc5efb88f56)

**Comment by ChenhuiYuan01** [comment]
This issue also reproduces in 9.0.100-preview.6.24321.1 on Linux.
![image](https://github.com/dotnet/sdk/assets/92560562/0999b1fa-aa6a-400e-a8ef-f539902cd44b)
![image](https://github.com/dotnet/sdk/assets/92560562/a37bf5d2-7895-4ad1-ae16-1edaa0b88e7b)

**Comment by v-xiaofchen** [comment]
This issue also reproduces in 9.0.100-preview.6.24324.8 (runtime-9.0.0-preview.6.24321.8) on Mac OS, keep tracking until coherent preview 6 build come out.
![image](https://github.com/dotnet/sdk/assets/99376012/4bd97764-bc94-4503-bf1a-8f0b688bf9d5)

**Comment by vdanche** [comment]
This issue still repro on today's coherent preview 6 (9.0.100-preview.6.24325.8)
dotnet workload install maui --skip-sign-check
![image](https://github.com/dotnet/sdk/assets/65637796/4729f549-d7ed-4b10-b157-a0c2bb8f9e05)
![image](https://github.com/dotnet/sdk/assets/65637796/4a4f0125-2634-4cfc-9c01-19928b396390)

**Comment by vdanche** [comment]
This issue not repro on new net9 p6 candidate build(9.0.100-preview.6.24328.19):
![image](https://github.com/dotnet/sdk/assets/65637796/bd752dbc-5fbd-4daf-a24f-910fed65b18e)
