### ISSUE TITLE
The Runtime version of “ASP.NET Core Runtime” and “.NET Windows Desktop Runtime” in .NET 9.0 Preview 5 SDK are 9.0.0-preview.6.xxx.

### ISSUE THREAD

**Issue by Rita003** [dotnet/sdk#41303]
**Describe the bug**

The Runtime version of “ASP.NET Core Runtime” and “.NET Windows Desktop Runtime” in .NET 9.0 Preview 5 SDK are 9.0.0-preview.6.xxx.

The following products were installed:
    • .NET SDK 9.0.100-preview.5.24273.5
    • .NET Runtime 9.0.0-preview.5.24272.2
    • ASP.NET Core Runtime 9.0.0-preview.6.24272.7
    • .NET Windows Desktop Runtime 9.0.0-preview.6.24273.2

**To Reproduce**
![Screenshot 2024-05-24 154043](https://github.com/dotnet/installer/assets/88122107/8d3d8d5a-74d1-4ded-9c60-82f5f9daf217)

**Exceptions**
The runtime version should be 9.0.0-preview.5

**Further technical details**
.NET SDK:
 Version:           9.0.100-preview.5.24273.5
 Commit:            3b23672629
 Workload version:  9.0.100-manifests.b2a38daf
 MSBuild version:   17.11.0-preview-24271-01+9e21c71e9

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.5.24273.5\

Cargas de trabalho do .NET instaladas:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Origem da Instalação: VS 17.11.34923.219
   Versão do Manifesto:    9.0.0-preview.4.24229.9/9.0.100-preview.1
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.4.24229.9\WorkloadManifest.json
   Tipo de Instalação:              Msi

Host:
  Version:      9.0.0-preview.5.24272.2
  Architecture: x64
  Commit:       5c06e5d01f

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.5.24273.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24272.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24272.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24273.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
Should be resolved with newer preview 5 builds
