### ISSUE TITLE
dotnet [application].dll fails on linux

### ISSUE THREAD

**Issue by sewalsh** [dotnet/sdk#4134]
This is an asp.net core api application built on OS X using the latest (3.1.0) .NET Core SDK. It runs as expected on OS X.

When I try running it on Ubuntu (I've used both 18.04 and 19.04), I get the following error:

Any ideas what may be the problem?

```
**dotnet --diagnostics ScorBoard.dll**
Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = /usr/share/dotnet/sdk/3.1.100/MSBuild.dll
projectfactory: MSBuild project path =
projecttoolscommandresolver: ProjectFactory did not find Project.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ScorBoard.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by sewalsh** [comment]
Closing this as it turned out to be a (careless) problem (on my part) with the endpoints specified in the appsettings.production.json.

**Comment by nealef** [comment]
Would you explain what your solution was or what you had mis-specified? I am seeing the same.

**Comment by sewalsh** [comment]
Oh jeez! My memory is failing me as to what it was exactly but I'd recommend checking the appsettings.[Dev/Prod].json to see the port that the endpoint is running under. Check if there's already an instance of the app running with that port number (if you're using PM2 to manage the app process, it might already be running in the background). You could remove the reference to the port number in the appsettings.json and let dotnet choose the default (5000 / 5001).

**Comment by nealef** [comment]
Thanks! I'll check it out.

**Comment by sewalsh** [comment]
Let me give you some files of a working example I have of a .net 5 core api project.

appsettings.production.json

`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ConnectionStrings": {
    "Default": "Host=localhost;Port=5432;Database=DB;Username=username;Password=password"
  }
}`

I mentioned PM2 for managing dotnet processes, that's incorrect. Use Supervisor to manage the start/stop/recover of dotnet process on linux. Here's a Supervisor configuration file for running this api.

```
[program:myapi]
command=/usr/bin/dotnet "/usr/share/nginx/myapi/MyApi.Api.dll"
directory=/usr/share/nginx/myapi
autostart=true
autorestart=true
stderr_logfile=/var/log/MyApi.err.log
stdout_logfile=/var/log/MyApi.out.log
environment=ASPNETCORE__ENVIRONMENT=Production
user=root
stopsignal=INT
```

Check the logs in /var/log for any errors (or successful startups).

**Comment by nealef** [comment]
Nice, thanks again!

**Comment by khurshid-alam** [comment]
@sewalsh How to enable debug log file on linux ? stderr_logfile not working with systemd. Also running with -d gives me same error ? Any idea ?
