### ISSUE TITLE
SDK 8.0.1xx mixes Docker and OCI formats

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#41370]
The 8.0.105 SDK fails to push into a registry when using an OCI base image.

After digging to the logging, the issue is that the SDK is mixing OCI and Docker formats.
```json
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.manifest.v1\u002Bjson",
    "config": {
        "mediaType": "application/vnd.oci.image.config.v1\u002Bjson",
        "size": 4073,
        "digest": "sha256:3053a06256f99ebb87f7329d751891b447c76c93615f8be1e63ca5b5bb98a7ef"
    },
    "layers": [
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar\u002Bgzip",
            "size": 76194709,
            "digest": "sha256:f6e7c82c6b343d25883116dc05a7d6b64399dde7cb93282379d33496cffef39e",
            "urls": null
        },
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": 1667453,
            "digest": "sha256:a2f96c62ab72b9d849dedbee9bf9df654d97bee2236524f44ecd916380bc74e2",
            "urls": null
        }
    ]
}
```

This was fixed by https://github.com/dotnet/sdk/pull/35609, which went into release/8.0.1xx-rc2.

The PR was merged to main here: https://github.com/dotnet/sdk/pull/38882, and backported to 8.0.3xx here: https://github.com/dotnet/sdk/pull/38960.

However, the PR didn't find its way into `8.0.1xx`.

Can you backport this to `8.0.1xx` so it also works for source-built SDKs?

cc @baronfel @omajid

**Comment by baronfel** [comment]
Thanks for the ping - I agree this should have been backported to 8.0.1xx as well. It looks like we have a number of these 'bugfixes but were treated as features' kind of things - please keep raising flags as you see them!

**Comment by tmds** [comment]
Thanks @baronfel!

**Comment by baronfel** [comment]
Closing as we've merged the backport - should be in a servicing release soon.
