### ISSUE TITLE
dotnet add package --source not imperative

### ISSUE THREAD

**Issue by iamalexmang** [dotnet/sdk#4137]
I strongly believe that if I explicitly mention a --source parameter for the package, especially in the format of a file system path, the CLI should not try validate the package's existence on any other sources. 
As of right now, when I specify the source parameter as a FS path, if either of the sources specified at the solution level, user global level (in %AppData%/NuGet) or computer level (Program Files (x86)), are unauthenticated, the package installation will fail. Regretfully, the error is completely unspecific as it complains which source returns a 401 Unauthorized error, though the package exists on the file system at the specified location.

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#9033
