### ISSUE TITLE
[NETSDKE2E]With NET9 preview 6 SDK installed, run wpf/winforms failed with error "You must install or update .NET to run this application"

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41395]
1. install net9 p6 sdk-9.0.100-preview.6.24304.23 on windows11
2. dotnet new wpf in CLI
3. dotnet build
4. dotnet run

Expected Result:
Run successfully
Actual Result:
Run failed with below error.
![image](https://github.com/dotnet/sdk/assets/65637796/25254b4c-ecf0-4543-9723-1f13516e70a5)

dotnet --info
.NET SDK:
 Version:           9.0.100-preview.6.24304.23
 Commit:            5cb86ded78
 Workload version:  9.0.100-manifests.ac65f6db
 MSBuild version:   17.11.0-preview-24281-02+db79545e5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24304.23\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.6.24281.1
  Architecture: x64
  Commit:       3750ac5161

.NET SDKs installed:
  9.0.100-preview.6.24304.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24303.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24281.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24304.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
This should get caught once we have the installer tests running again. @MiYanni do we have a wpf/winforms dotnet run E2E test from installer as that's what would catch this sort of incoherency (I know we have web ones)?

**Comment by vdanche** [comment]
This issue not repro on 9.0.100-preview.6.24309.2(runtime-9.0.0-preview.6.24307.2)
![image](https://github.com/dotnet/sdk/assets/65637796/9a29558d-ff6d-4b40-87cb-b327c6b914ff)
