### ISSUE TITLE
After installing .NET SDK 9.0 Preview 5,  Creating 6.0/8.0 Blazor WASM requires July Servicing (8.0.7/6.0.32) feeds.

### ISSUE THREAD

**Issue by Allinylatoza** [dotnet/sdk#41432]
**Testcases Affected**
[[8.0/6.0] SignalRwithBlazorWebAssembly](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.4/E2EWalkthroughs/VS/AspNetCore60/60_SignalRwithBlazorWebAssembly.md)

**Install Steps**
1. Clean machine: Win 11 x64 22h2 ENU
2. Install 8.0.300 sdk on win11-x64
3. Install net9 preview 5 sdk(9.0.100-preview.5.24304.3) on win11-x64

**Repro Steps**
1. Create a Blazor Web App for WebAssembly via Terminal Emulator
 ` dotnet new blazor -int WebAssembly -o Blazortest -f net8.0`

**Note:** 
1. This issue does not repro on Blazor web for server project.
2. This issue does not repro on 9.0 Blazor web for webAssembly project.

**EXPECTED**
The project should create successfully

**ACTUAL**
![image](https://github.com/dotnet/sdk/assets/156404305/016e8eb0-fdb0-403f-ba88-6f1be0e0aafb)

**Dotnet info**
**SDK**
![image](https://github.com/dotnet/sdk/assets/156404305/94f26194-5fa0-41d5-a447-662042519945)

**Runtime**
![image](https://github.com/dotnet/sdk/assets/156404305/90d6da31-fecc-4ceb-89f4-0610afa98d1f)

**Template**
![image](https://github.com/dotnet/sdk/assets/156404305/944b68ad-6250-4119-8e06-6d20ad69443e)

**Comment by maitan11** [comment]
I tested it using 9.0 coherent build[9.0.100-preview.5.24307.3] and it doesn't repro. So we can close this now.
