### ISSUE TITLE
Strange warning about android version

### ISSUE THREAD

**Issue by hypdeb** [dotnet/sdk#41444]
### Description

A strange warning appears when building a MAUI app in Visual Studio:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning	CA1416	This call site is reachable on: 'Android
            ' 34.0 and later. 'MauiApp.CreateBuilder(bool)' is only supported on: 'Android' 21.0 and later.	WeirdWarning (net8.0-android)	D:\repro\WeirdWarning\MauiProgram.cs	7	Active	

```

As you can see, the warning is at least strange, as `Android 34.0` is in fact, a later version than `Android 21.0`.

In the command line, we see:

```
warning CA1416: This call site is reachable on: 'Android [D:\repro\WeirdWarning\WeirdWarning.csproj::TargetFramework=net8.0-android]
```

Which is at best not useful.

### Steps to Reproduce

1. Clone repro repository repository
2. Run `dotnet build -f net8.0-android`

### Link to public reproduction project repository

https://github.com/hypdeb/repros/tree/master/WeirdWarning

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by baronfel** [comment]
We don't do this for the vast majority of our properties - this would be a special exception unless we did an all-up audit of the entire props/targets infrastructure.

@hypdeb Xml values are whitespace-sensitive and so the formatting that the xml formatter is applying is changing the semantics meaningfully. Personally, I disable formatting for all MSBuild logic explicitly for this reason.

**Comment by hypdeb** [comment]
Just for my understanding, what value does `SupportedOSPlatformVersion` end up having with the white space when `CA1416` is evaluated?

**Comment by baronfel** [comment]
Based on the snippet above it would have a value something like `\n            34.0`. Of course we can call `.Trim()` on that in MSBuild code when used, and some Task implementations may do this on their inputs to be defensive, but there's nothing in MSBuild-the-language to defend against this. In fact, some properties like the NuGet-package-facing PackageReleaseNotes property may even rely on such capabilities.

**Comment by hypdeb** [comment]
@baronfel yeah, I'll increase the max line length and be done with it 😆.

I googled around a bit, and yeah the standards don't specify what to do with that kind of white space. They say that it's the application's responsibility to decide what to do with them.

**Comment by nagilson** [comment]
I think that's a confusing behavior that's tempting to fix, but I would want all of msbuild to behave in the same way (either the whitespace trim matters or it doesnt.) If this would break NuGet package facing properties this is something I don't think we would do, it would definitely impact other people's code as well at a pretty large scale. It looks like you got the help you needed so far, (thank you to everyone for helping), so I'm going to close this for now. But feel free to ask us to re-open it!

**Comment by nagilson** [comment]
Project files are technicall defined in MSBuild which is an XML based build language, so not to my knowledge!

**Comment by baronfel** [comment]
It is technically possible to use another language to define the declarative parts of a project file (properties, items, some small conditions), but the programmatic parts (Targets, Task dependencies, etc) cannot easily be created by anything but the engine itself, which only understands XML.

In my view the 'frontend' of a project file isn't actually complicated - instead it's the semantics of MSBuild that are difficult - reasoning about when Targets run, data dependencies between them, good incrementality, etc.

**Comment by hypdeb** [comment]
> Project files are technically defined in MSBuild which is an XML based build language, so not to my knowledge!

But theoretically MSBuild could be made to read one of these other formats right? I was simply wondering whether there's something that XML can express but that the other ones can't.
