### ISSUE TITLE
Please give users a choice to disable implicit usings and nullable before code is generated

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/sdk#41528]
When a user generate a new project they do not get the choice to disable implicit usings and nullables before the code is generated. Neither feature is something I am interested and every time I generate I have to remove them and then add the using statements. 

I would rather disable them with a check box than need to remove and then add usings.
I want to know what is being used in each file. This is very similar to the arguments that went on around top-level statements and being able to disable them.

Allow the developer to make the choice of removing them please.

**Comment by baronfel** [comment]
This has been talked about several times prior - we believe these have value and will continue to use them in the default templates. Users are always free to create their own customized templates for any project type and use those - .NET Template Engine templates are available from the CLI, VS, and soon VS Code via Dev Kit. This is how users should express their opinions about project style and architecture.

**Comment by dgxhubbard** [comment]
And when things change in the template, then we have to change our template.
Giving users the choice of having nullables and global usings seems like a better option rather than hoping a template does not change, and needing to remove things manually.

**Comment by bzd3y** [comment]
> This exists. If you have global usings, we show you this:

@CyrusNajmabadi Excellent. I hadn't noticed that before so thanks for pointing it out.
