### ISSUE TITLE
[NETSDKE2E]With NET9 preview 6 sdk installed, create blazorwasm project failed with error "Could not resolve SDK "Microsoft.NET.Runtime.Emscripten.Python.${NetVersion}". Exactly one of the probing messages bel..."

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41538]
1. install net9 preview 6 sdk(9.0.100-preview.6.24311.13(runtime-9.0.0-preview.6.24307.2) on windows11
2.dotnet workload install wasm-tools
3.dotnet new blazorwasm

**Expected Result:**
Create project successfully

**Actual Result:**
Create project failed with below error
![image](https://github.com/dotnet/sdk/assets/65637796/979d0a70-90d3-41ce-8002-fffc841eb3be)

Processing post-creation actions...

Restoring C:\Users\v-ainigao\Desktop\22\22.csproj:

C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.emscripten.current\9.0.0-preview.6.24311.1\WorkloadManifest.targets(24,5): error :

  Could not resolve SDK "Microsoft.NET.Runtime.Emscripten.Python.${NetVersion}". Exactly one of the probing messages bel

  ow indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.

    SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.

    The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.

C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.emscripten.current\9.0.0-preview.6.24311.1\WorkloadManifest.targets(24,33): error MSB4236: The SDK 'Microsoft.NET.Runtime.Emscripten.Python.${NetVersion}' specified could not be found.

Restore failed.

Post action failed.

Manual instructions: Run 'dotnet restore'

dotnet --info
.NET SDK:
Version:           9.0.100-preview.6.24311.13
Commit:            2bdacb80ab
Workload version:  9.0.100-manifests.b19d6709
MSBuild version:   17.11.0-preview-24310-01+74e23a98d
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.20348
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24311.13\
 
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
[wasm-tools]
   Installation Source: SDK 9.0.100-preview.6
   Manifest Version:    9.0.0-preview.6.24307.2/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.6.24307.2\WorkloadManifest.json
   Install Type:              Msi
 
 
Host:
  Version:      9.0.0-preview.6.24307.2
  Architecture: x64
  Commit:       static
 
.NET SDKs installed:
  9.0.100-preview.6.24311.13 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24309.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24307.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24311.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-xiaofchen** [comment]
This issue also repro's on Mac OS.
![image](https://github.com/dotnet/sdk/assets/99376012/f363a424-f116-4152-9259-862d62b9626e)

**Comment by marcpopMSFT** [comment]
@lewing the property didn't get replaced during construction of the manifest targets file.

**Comment by v-ainigao** [comment]
This issue does not repro on net9.0.100-preview.6.24317.13SDK.
![image](https://github.com/dotnet/sdk/assets/106054229/57615a5b-4d00-4848-845f-bc1226c0fd42)
