### ISSUE TITLE
Framework dependent deployment for AnyCPU

### ISSUE THREAD

**Issue by Tyrrrz** [dotnet/sdk#4157]
Hi there.

Sorry in advance if this is not the right repository for this issue/question but I'm not sure where to look for an answer.

I'm currently building and deploying a WPF application. The deployment is framework-dependent, i.e. not self-contained.

It appears when some of my users, who are using 32bit OS, download and install the 32bit version of the .NET Core runtime, they fail to run the application with the following error:

![image](https://user-images.githubusercontent.com/1935960/72207382-4b8afb80-34a1-11ea-83a2-c1e6b96cce62.png)

It seems that the application is attempting to run in 64bit mode despite being built for AnyCPU.

Does anyone know what can cause this and how to fix this issue?

**Comment by wli3** [comment]
Duplicated with https://github.com/dotnet/sdk/issues/1912
