### ISSUE TITLE
The "GetNearestTargetFramework" task was not given a value for the required parameter "ReferringTargetFramework".

### ISSUE THREAD

**Issue by weidazhao** [dotnet/sdk#416]
This is a scenario of Service Fabric application with an ASP.NET Core web service targeting .NET Framework.

In Visual Studio, Service Fabric Application project (similar to a Deployment project) adds project references to the service projects. With https://github.com/dotnet/sdk/pull/363, the SDK will check if referencing project and referenced project are compatible in terms of the target frameworks. However, Service Fabric Application project is not a managed code project, so it doesn't have any target framework moniker. In this case, the SDK reports an error on the referenced service project (ASP.NET Core on .NET FX)because of ReferringTargetFramework being empty.

As a tactical fix for RC.2, I suggest this:  If ReferringTargetFramework is empty, GetNearestTargetFramework returns the only TFM if the project only has one. Otherwise, it throws error. In this case, the semantic of ReferringTargetFramework being empty is that the referencing project can accept any TFM.

**Comment by mgwalm** [comment]
I have the latest version of VS2017 - Version 15.0.26206.0 D15REL.

I'm still getting this error as of today feb 27.

**Comment by dsplaisted** [comment]
@mgwalm Could you open a new issue with repro steps and a description of what you're seeing?

**Comment by pksorensen** [comment]
I also just saw the error, trying to figure out why. could possible be that the service project targets both netcoreapp1.1 and net462.

**Comment by fleed** [comment]
I'm getting the same error when targeting both netcoreapp1.1 and net461. Is there a way to for ServiceFabric to get the net461 version?

**Comment by mani0070** [comment]
im getting same error

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73, 5): error MSB4044: The "GetNearestTargetFramework" task was not given a value for the required parameter "ReferringTargetFramework".
