### ISSUE TITLE
_NetFrameworkHostedCompilersVersion is empty in Microsoft.NETCoreSdk.BundledVersions.props in 9.0-preview5

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/sdk#41652]
In the generated file this property is empty: https://github.com/dotnet/sdk/blob/dad19767321297ae8b3c168a3815ac56bf5b6465/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L515

Most likely due to the installer->sdk repo consolidation.

This causes issues with this target since we set an empty version: https://github.com/dotnet/sdk/blob/dad19767321297ae8b3c168a3815ac56bf5b6465/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L237-L239

/cc @MiYanni @marcpopMSFT

**Comment by akoeplinger** [comment]
I'm a bit confused why this test didn't catch this: https://github.com/dotnet/sdk/blob/dad19767321297ae8b3c168a3815ac56bf5b6465/test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs#L13

**Comment by akoeplinger** [comment]
> I'm a bit confused why this test didn't catch this

Looks like full framework tests weren't actually running: https://github.com/dotnet/sdk/pull/41656

**Comment by jaredpar** [comment]
@baronfel this make u think of any other scenarios that may have gotten missed?

**Comment by baronfel** [comment]
No, that's a huge amount of egg on face - excellent catch @akoeplinger @ViktorHofer!
