### ISSUE TITLE
RuntimeHostConfigurationOption changes are not applied without a rebuild

### ISSUE THREAD

**Issue by sharwell** [dotnet/sdk#4166]
### Steps to reproduce

1. Build a C# solution targeting netcoreapp3.0
2. Add `<ServerGarbageCollection>true</ServerGarbageCollection>` to the project file
4. Build the project again (`/t:Build`)

### Expected results

The output contains `"System.GC.Server": true`.

### Actual results

The output does not contain `"System.GC.Server": true`.

### Additional information

This was also observed with the `<TieredCompilation>` setting.

**Comment by gewarren** [comment]
I think this is the same as #2787.

**Comment by sharwell** [comment]
Duplicate of #2787
