### ISSUE TITLE
Why is there no Linux version of MAUI? It is possible to do this with Rider or Andiroid studion or visual studio code, but since it is not available in the sdk,

### ISSUE THREAD

**Issue by zuhriddinzayniddinov** [dotnet/sdk#41688]
Why is there no Linux version of MAUI? It is possible to do this with Rider or Andiroid studion or visual studio code, but since it is not available in the sdk. I propose to release MAUI for Linux. After all, if it is cross platform. and another suggestion that MAUI develop software for Linux as well.

**Comment by baronfel** [comment]
Hello! Questions around MAUI functionality should be raised at the dotnet/maui repo. I don't have permissions there, otherwise I'd transfer this issue for you.
