### ISSUE TITLE
[Mac/Linux]After installing SDK 8.0.303 (July Update), wasm tools workload installation failed: Version 8.0.7 of package microsoft.net.runtime.webassembly.sdk is not found in NuGet feeds.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/sdk#41715]
**REGRESSION INFO**: Worked in SDK 8.0.302 + wasm tools

**REPRO STEPS**
1. Install SDK 8.0.303 (July Update)
2. Add Feed
3. Open command line and install wasm-tools workload
`sudo dotnet workload install wasm-tools`

**ACTUAL**
Workload installation failed: Version 8.0.7 of package microsoft.net.runtime.webassembly.sdk is not found in NuGet feeds
[https://api.nuget.org/v3/index.json".](https://api.nuget.org/v3/index.json%22.)
![image](https://github.com/dotnet/sdk/assets/71361488/f2b51e3e-35c0-45b3-a022-77e15fba422b)

**NOTE:**
- This issue reproduces both MacOS and Linux, but not on windows.
- Based on error message, running 'sudo dotnet workload install wasm-tools --source https://api.nuget.org/v3/index.json' still reproduces.

**EXPECTED**
The wasm tools workload installed successfully.

**Comment by joeloff** [comment]
You probably need to configure the internal feed - these packages are not public yet.

**Comment by v-sherryfan** [comment]
Running "sudo dotnet workload install wasm-tools --configfile ~/.nuget/NuGet/NuGet.Config" can successfully install wasm-tools workload. Closing this issue.
