### ISSUE TITLE
dotnet build hangs on RHEL 7

### ISSUE THREAD

**Issue by RKopczynski** [dotnet/sdk#4173]
Hi,
I'm trying to run dotnet build on my machine.
Sadly it's some corpo-dunno-build of RHEL and I couldn't use "legit" RHEL repositories. .NET SDK is then installed using official binaries (dotnet-sdk-3.1.100-linux-x64.tar.gz).

We are trying to build some app (just simple NetStandard2.0 with little to no deps) on Jenkins with version 2.190.3.

I cannot build this app because it hangs indefinitely in some point giving me lot of headache. I tried to make ```/tmp/NuGetScratch/lock``` public for all processes but that didn't help.

All info I have gathered:

## jenkins pipeline thingy
``` yaml
pipeline {
    agent any

    environment {
        DOTNET_ROOT = "/opt/dotnet"
        PATH = "/opt/dotnet:$PATH"
        dotnet = "$DOTNET_ROOT/dotnet"
        COMPlus_EnableDiagnostics = 0
    }

    stages {
        stage('Preparation') {
            steps {
                  sh "dotnet build Project.sln -c Release -v Diagnostic"
            }
        }
    }
}
```

## dotnet --info
``` shell
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /opt/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## cat /etc/os-release
```shell
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

dotnet build log: [gist](https://gist.github.com/RKopczynski/37c247ef8ed53c286aba5d9b5e9e3434)

**Comment by limup** [comment]
Hi!
I had the same error and I fixed this with commands below:

`export TMPDIR=/tmp/NuGetScratch/`
`mkdir -p ${TMPDIR}`

See ya!

**Comment by RKopczynski** [comment]
I'll just close issue. Cannot remember what exactly did we do with coworker to make this work.
Too many problems, mostly with proxy.
