### ISSUE TITLE
Updating 3.1.100 to 3.1.101 breaks on global.json

### ISSUE THREAD

**Issue by rducom** [dotnet/sdk#4174]
Hello,

We are building our code on Jenkins slaves with 3.1.100 sdk installed, and our projects have a global.json with 3.1.100 specified.
While installing the 3.1.101 sdk, it's removing the previous 3.1.100 sdk. Building the same project with 3.1.100 in global.json throws the following error 

`Found .NET Core SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\3.1.100\dotnet.dll] `

So we can't have a progressive 3.1.101 version update on multiple projects, using the sames Jenkins slaves.

What is the best practice in this case ? removing the global.json in 3.1 projects ? is there a new "wildcard" feature on global json to specify 3.1.* ?

Thanks in advance

**Comment by rducom** [comment]
answer is : [RTFM](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#examples)

```
{
  "sdk": {
    "version": "3.1.100",
    "rollForward": "latestPatch"
  }
}
```

**Comment by chris1248** [comment]
What does this answer mean? What file is that, and where do I put it?

**Comment by cmwendwa** [comment]
@chris1248 `global.json`  you can create one by running `dotnet new globaljson`  in the root of your project.
