### ISSUE TITLE
After installing the .NET 9.0 Preview 6 SDK, failed to install wasm-experimental/wasm-tools workload with error "Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-preview.6.24319.1' is lower"

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/sdk#41777]
### To Reproduce
1. Install .NET 9.0 preview 6 SDK(9.0.100-preview.6.24324.9) on win11-x64
2. Install wasm-experimental/wasm-tools workload 
`dotnet workload install wasm-experimental --skip-sign-check`
`dotnet workload install wasm-tools --skip-sign-check`

### Actual Result
workload installs failed with below error.
![image](https://github.com/dotnet/sdk/assets/66412474/c00e93a7-602c-4676-8959-67ae42242a21)

### Error Log
Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-preview.6.24319.1' is lower than version '9.0.0-preview.7.24319.4' required by manifest 'microsoft.net.workload.mono.toolchain.current' [C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.6.24324.3\WorkloadManifest.json]

### Further technical details
- Include the output of `dotnet --info`
```
Host:
  Version:      9.0.0-preview.6.24321.8
  Architecture: x64
  Commit:       static
  RID:          win-x64

.NET SDKs installed:
  8.0.400-preview.0.24312.1 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.6.24324.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24324.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24321.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24322.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by v-elenafeng** [comment]
With SDK 9.0 P6 installed
1. Running "dotnet workload install wasm-tools --skip-sign-check" reproes this issue.
2. After then, creating a web app in VS is blocked.

![image](https://github.com/dotnet/sdk/assets/78580199/fb14d120-5a85-4ec8-bc7b-225d46e9b9c8)

**Comment by EmilyFeng97** [comment]
Verify this bug on the latest build of .NET 9.0 preview 6(9.0.100-preview.6.24325.8) and it does not repro. So close it as fixed.
