### ISSUE TITLE
SDK installer did not remove previous patch versions

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sdk#4183]
According to the [announcement](https://github.com/dotnet/announcements/issues/102), the SDK installer will remove previous patch versions but did not work

![image](https://user-images.githubusercontent.com/5714438/72483926-99a35480-383d-11ea-8b56-3c0c007377b2.png)

```bash
dotnet --info

.NET Core SDK（反映任何 global.json）:
 Version:   3.1.101
 Commit:    b377529961

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Varorbc** [comment]
@leecow Can you help to see why?

**Comment by leecow** [comment]
Were 3.1.100 and 3.1.101 installed in the same way? ie both through Visual Studio or both with the standalone installer? 

@dsplaisted , could you have someone take a look?

**Comment by dsplaisted** [comment]
@wli3 @joeloff Could one of you help investigate this?  Thanks

**Comment by joeloff** [comment]
The two entries in ARP come from the SDK placeholder MSI we placed in VS. 

@Varorbc do you have the setup log from VS? 

Do you have more than one instance of VS2019, e.g. both a preview and a release channel install?

**Comment by Varorbc** [comment]
@joeloff Yes, I installed preview and release instances

**Comment by joeloff** [comment]
Thanks for confirming. If possible I'd like to look at the primary VS setup log. That should indicate why VS chose to leave something behind. For example, it's possible both instances shipped with the same version, but the release channel updated, but not the preview channel, in which case the old version would remain. But the logs should shed some light as to why it wasn't removed.

**Comment by Varorbc** [comment]
OK, can you tell me the directory where the logs are located? I'll email you later

**Comment by joeloff** [comment]
They are usually kept in the %temp% folder of the user that performed the install. The primary log should be named something like **dd_setup_20190809084015.log** This is the primary log for the overall setup process.

**Comment by Varorbc** [comment]
@joeloff Can you give me your email address? I send you the file by email

**Comment by joeloff** [comment]
I've been going through the logs. The logs do show that 3.0.2/3.0.1 was being removed and 3.1.1 was being added. I don't see anything referencing the files that would have gone into the 3.1.100 SDK folders yet. I'll keep you posted as I discover any new items

**Comment by joeloff** [comment]
Based on the logs, all the package detection entries report the 3.1.1 is already present on the machine and VS marked them as no-ops. I don't see anything in the log indicating the 3.1.0 was being removed

The excerpt below is just from one SDK related package. Detection is reported as *Present*, meaning the system believes it is already installed.

```
[2948:000d][2020-02-13T10:04:04] Package: Microsoft.NetCore.AppHostPack.3.1.3.1.1.x64,version=16.4.29708.42,chip=x64, CurrentState: Present, RequestedState: Present, DetectionState: Present, PlannedAction: None.
[2948:000d][2020-02-13T10:04:04] Dependency action plan - PackageExecuteAction: None, PlannedActionForDependency: Add.
```

**Comment by Varorbc** [comment]
After updating to 16.5, the previous version has been removed
