### ISSUE TITLE
dotnet download page unavailable

### ISSUE THREAD

**Issue by lukewis** [dotnet/sdk#41875]
Wasn't sure where else to report this.  Unable to visit [https://dotnet.microsoft.com/download/dotnet](https://dotnet.microsoft.com/download/dotnet)
![image](https://github.com/dotnet/sdk/assets/29690546/2d7038ab-94b2-4c3e-b253-6a3d3ac4aba8)

**Comment by baronfel** [comment]
Thanks, we're aware of this and have an internal incident going to resolve it.

**Comment by mairaw** [comment]
The issue should now be resolved. Apologies for the inconvenience. Let us know if you're still having issues.
