### ISSUE TITLE
 [NETE2ESDK][Azure Linux 3.0] Installing .NET 9 Preview SDK in Azure Linux X64 3.0 Preview should not depend on package netstandard-targeting-pack-2.1 

### ISSUE THREAD

**Issue by ChenhuiYuan01** [dotnet/sdk#41898]
**Repro steps:**
1. Prepare Azure Linux X64 3.0 Preview in Dokcer via running
    `sudo docker run -it -v ~/tmp:/root/workspace azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0 sh`
2. Try to install 9.0.100-preview.6.24328.19 SDK via installer *.cm.2-x64.rpm 

**Expected:**
  SDK installed successfully.

**Actual result:**
  SDK install failed as depending on package netstandard-targeting-pack-2.1 
![Screenshot 2024-07-02 165536](https://github.com/dotnet/sdk/assets/92560562/ba0e7e80-eb0b-49b2-8116-5d0ca8fed8d8)

**Note:**
  1. This SDK could be installed successfully in Azure Linux Arm64 3.0 Preview
  ![image](https://github.com/dotnet/sdk/assets/92560562/1ac3820a-24d9-4d46-9e97-1c9fe08e55e3)

 2. This SDK could be installed successfully in Mariner 2 X64 2.0.
  ![image](https://github.com/dotnet/sdk/assets/92560562/c55ee92e-3708-4f1b-9464-c261f2ff9c14)

**Comment by leecow** [comment]
azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0 does not include feed registration for (ms-oss)[https://packages.microsoft.com/azurelinux/3.0/preview/ms-oss/x86_64/Packages/] packages. Running `ls etc/yum.repos.d/` only shows `azurelinux-ms-non-oss-preview.repo  azurelinux-official-preview.repo`.  The easiest thing to do is copy the non-oss repo definition and update it to include the oss repo. 

First install nano: `tdnf install -y nano`

```
cd /etc/yum.repos.d
cp azurelinux-ms-non-oss-preview.repo azurelinux-ms-oss-preview.repo
nano azurelinux-ms-oss-preview.repo
```

Update all references to 'non-oss' just 'oss'. Save the file and should be good to go.

**Comment by NicoleWang001** [comment]
@leecow Thanks! This workaround works fine.
![image](https://github.com/dotnet/sdk/assets/1578239/f6ed3d25-fa01-4104-a5d0-211bc0a43ccd)
