### ISSUE TITLE
error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized

### ISSUE THREAD

**Issue by mb720** [dotnet/sdk#4190]
Steps to reproduce on Arch Linux 5.4.6:

    dotnet new console -o TestProj

This produces:

    The template "Console Application" was created successfully.

    Processing post-creation actions...
    Running 'dotnet restore' on TestProject/TestProject.csproj...
    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]
    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]
    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]

    Restore failed.
    Post action failed.
    Description: Restore NuGet packages required by this project.
    Manual instructions: Run 'dotnet restore'

Running `dotnet restore` or `dotnet run Program.cs` inside the project:

    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]
    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]
    /usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(88,5): error NETSDK1083: The specified RuntimeIdentifier 'arch-x64' is not recognized. [/home/mb/experiments/TestProject/TestProject.csproj]

    dotnet --info

    .NET Core SDK (reflecting any global.json):
    Version:   3.1.100
    Commit:    cd82f021f4

    Runtime Environment:
    OS Name:     arch
    OS Version:  
    OS Platform: Linux
    RID:         arch-x64
    Base Path:   /usr/share/dotnet/sdk/3.1.100/

    Host (useful for support):
      Version: 3.1.0
      Commit:  4e9ce2915b

    .NET Core SDKs installed:
      3.1.100 [/usr/share/dotnet/sdk]

    .NET Core runtimes installed:
      Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download

    dotnet --version
    3.1.100

    dotnet --list-sdks
    3.1.100 [/usr/share/dotnet/sdk]

    dotnet --list-runtimes
    Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Creating and running a project used to work in previous versions.

Is there something I can do to fix this?

Thanks for looking into this.

**Comment by metya** [comment]
confirm. the same issue.
I thiink it is problem with arch repository

**Comment by maciakon** [comment]
The issue has been fixed in dotnet-sdk-3.1.0.sdk100-2 package.
Please perform system update to have it fixed.
The issue can be closed now.

**Comment by metya** [comment]
yeah. it is fixed. confirm.

**Comment by mb720** [comment]
Thanks for solving this so quickly!
