### ISSUE TITLE
'appsettings.json' files are optional by convention - publish .csproj in Preview 4 fails with MSB3030 error

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#420]
Moved from https://github.com/dotnet/cli/issues/4791 on behalf of @peterblazejewicz

@nguerrera pointed out that this is an SDK issue.

----

I have set of projects, including one in the  production at my company. I've migrated sample project to .csproj and now I found it fails to publish with '1.0.0-preview4-004107' because of missing file:

> dotnet publish
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
  PolymerShopDotnet.Client -> /Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/bin/Debug/netcoreapp1.0/PolymerShopDotnet.Client.dll
/Users/piotrblazejewicz/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161104-2/build/Microsoft.NET.Publish.targets(98,5): error MSB3030: Could not copy the file "/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/appsettings.json" __because it was not found.__ [/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/PolymerShopDotnet.Client.csproj]

This behavior is different from tools behavior based on `project.json` I believe. 

```xml
<Content Include="appsettings.json;appsettings.Production.json;dist;Dockerfile;hosting.json;web.config">
```

How I'm supposed to use optional, configuration based files when publish will fail instead of logging warnings?

Output using detailed verbosity:
```bash
 Task "Copy"
     1>/Users/piotrblazejewicz/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161104-2/build/Microsoft.NET.Publish.targets(98,5): error MSB3030: Could not copy the file "/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/appsettings.json" because it was not found. [/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/PolymerShopDotnet.Client.csproj]
       Done executing task "Copy" -- FAILED.
     1>Done building target "_CopyResolvedFilesToPublishPreserveNewest" in project "PolymerShopDotnet.Client.csproj" -- FAILED.
     1>Done Building Project "/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/PolymerShopDotnet.Client.csproj" (Publish target(s)) -- FAILED.

Build FAILED.

       "/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/PolymerShopDotnet.Client.csproj" (Publish target) (1) ->
       (_CopyResolvedFilesToPublishPreserveNewest target) -> 
         /Users/piotrblazejewicz/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161104-2/build/Microsoft.NET.Publish.targets(98,5): error MSB3030: Could not copy the file "/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/appsettings.json" because it was not found. [/Users/piotrblazejewicz/git/polymer-shop-dotnet/PolymerShopDotnet/src/PolymerShopDotnet.Client/PolymerShopDotnet.Client.csproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by nguerrera** [comment]
Moving back to CLI repo, this is not an SDK issue after all.
