### ISSUE TITLE
[Bug] Failed to download Cpp2IL

### ISSUE THREAD

**Issue by RebelHvHProWoW** [dotnet/sdk#42003]
All of the following criteria must be met
 All [Requirements](https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements) must be installed.
 Full Latest.log file included. If no file exists then leave this unchecked and state so.
All of the following are optional to answer
 Tried reinstalling the Game.
 Tried reinstalling MelonLoader.
 Tried restarting PC.
 Was able to see the Start Screen.
Describe the issue.
i tried to use melonloader 0.6.0 and it said "failed to download cpp2il". i download the cpp2il netframework zip thing and put it in C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator
opened btd6 and got same error

[log file](https://github.com/LavaGang/MelonLoader/files/11032462/Latest.log)

Did you attach your log file?
 Yes, I attached my log file to the text box above.
 No, I could not find a log file at {Game_Directory}\MelonLoader\Latest.log

**Comment by marcpopMSFT** [comment]
Kalle is correct. I would recommend filing an issue with MelonLoader.
