### ISSUE TITLE
[NETSDKE2E]With net9 preview 7 sdk installed, Running winforms/wpf failed in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#42012]
Repro steps:
1.install net9 preview 7 SDK(9.0.100-preview.7.24357.2(runtime-9.0.0-preview.7.24352.15))
1.in CLI, dotnet new winforms or dotnet new wpf
2.dotnet run

**Expected Result:**
Run successfully

**Actual Result**
Run failed with below dialog.
![image](https://github.com/dotnet/sdk/assets/65637796/2b277cec-1053-4be2-927c-fb19bdb7b4a0)

dotnet --info:
.NET SDK:
Version:           9.0.100-preview.7.24357.2
Commit:            9cf65a030c
Workload version:  9.0.100-manifests.4ffd17c4
MSBuild version:   17.12.0-preview-24354-03+07be3a17b
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.20348
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24357.2\
 
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-preview.7.24352.15
  Architecture: x64
  Commit:       static
 
.NET SDKs installed:
  9.0.100-preview.7.24357.2 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.7.24355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24352.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24356.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS with .net9.0.100-preview.7.24357.2sdk installed.
![image](https://github.com/dotnet/sdk/assets/106054229/f2c7418c-6064-47d5-a94c-a8814c1eb779)

**Comment by marcpopMSFT** [comment]
This is a coherency issue. We're still working on getting our tests updated to catch this type of issue. More codeflow will resolve it.

**Comment by v-ainigao** [comment]
> This is a coherency issue. We're still working on getting our tests updated to catch this type of issue. More codeflow will resolve it.

Thanks Marc, I will keep tracking.

**Comment by vdanche** [comment]
Repro again on 9.0.100-preview.7.24357.2 (runtime-9.0.0-preview.7.24352.15) SDK, hence re-open it to keep tracking
![image](https://github.com/user-attachments/assets/548cbec7-e5f1-42bb-8605-87f43e6dadf3)

**Comment by marcpopMSFT** [comment]
Until we get a test in place to stop it, this will happen every time that windows desktop (or aspnet) inserts into SDK before runtime does. You can potentially check this by searching for active runtime codeflows and seeing how old they are: https://github.com/dotnet/sdk/pulls?q=is%3Apr+is%3Aopen+cedddd63-79f5-4e7e-6d46-08dc434c4948

**Comment by vdanche** [comment]
not repro on 9.0.100-preview.7.24365.17. hence close it.
![image](https://github.com/user-attachments/assets/d4f618ca-065c-414f-a5c7-51fe7bc5c3c6)
