### ISSUE TITLE
Update version of MSTest used in tests

### ISSUE THREAD

**Issue by Evangelink** [dotnet/sdk#42015]
### Is your feature request related to a problem? Please describe.

Multiple test asset projects are using `MSTestVersion` property defined by arcade. The problem is that arcade is bringing by default version `2.0.0` which is 5y old. I would like to suggest updating to a newer version or at least agreeing to bump to newer version. This agreement would allow me to start back request of update of version in arcade (https://github.com/dotnet/arcade/issues/12095).

Impacted projects/files: https://github.com/search?q=repo%3Adotnet%2Fsdk+MSTestVersion&type=code

### Describe the solution you'd like

Use latest released version of MSTest for the tests and potentially setup some darc or dependabot subscriptions to stay up-to-date.

### Additional context

Upon approval, I'll work on a PR updating the versions.

**Comment by nohwnd** [comment]
Let's try it so we have a happy build and can raise that with others.
