### ISSUE TITLE
RAR resolves incorrect WindowsBase.dll in .vcxproj with FrameworkReference to Microsoft.WindowsDesktop.App.WPF

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/sdk#4204]
I think there may be a problem in RAR (or an adjacent target) failing to resolve WindowsBase correctly. 

Rather than resolving WindowsBase.dll from Microsoft.WindowsDesktop.App.Ref, the build seems to allow WindowsBase.dll from Microsoft.NetCore.App.Ref to win during reference resolution. 

Project: [ApngImage.zip](https://github.com/dotnet/wpf/files/4074581/ApngImage.zip)
Build logs: [msbuild.zip](https://github.com/dotnet/wpf/files/4074572/msbuild.zip)

There is an active discussion about this in the Developer Community at https://developercommunity.visualstudio.com/content/problem/856860/ccli-net-core-unable-to-reference-wpf-classes.html. 

In a simple .NET Core project with `<FrameworkReferenceInclude="Microsoft.WindowsDesktop.App.WPF" />`,  we get build orchestration like this: 

- Build
  - CoreBuild
    - GenerateBuildDependencyFile
      - _HandlePackageFileConflicts
        - Encountered conflict between 'Reference:C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1\WindowsBase.dll' and 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\3.1.0\ref\netcoreapp3.1\WindowsBase.dll'. Choosing 'Reference:C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\3.1.0\ref\netcoreapp3.1\WindowsBase.dll' because file version '4.800.119.56501' is greater than '4.700.19.56404'.

Simple .NET Core project with FrameworkReference to WPF: [ClassLibrary1.zip](https://github.com/dotnet/wpf/files/4074627/ClassLibrary1.zip)
Logs showing correct WindowsBase resolution: [msbuild-good.zip](https://github.com/dotnet/wpf/files/4074625/msbuild-good.zip)

In the `vcxproj` build orchestration, nobody seems to be chaining into `_HandlePackageFileConflicts`. 

/cc @nguerrera, @amit-kabra

_Originally posted by @vatsan-madhavan in https://github.com/dotnet/wpf/issues/2117#issuecomment-575424746_

**Comment by nguerrera** [comment]
*Copying https://github.com/dotnet/wpf/issues/2117#issuecomment-575681477*

Maybe a casualty of not supporting PackageReference in C++

cc @wli3

**Comment by wli3** [comment]
status update

Thank you, yes. It is the exactly the missing target. It was unintentionally disabled as part of workaround for C++/CLI not supporting nuget package reference. I am investigating a proper fix

**Comment by wli3** [comment]
Fixed in https://github.com/dotnet/sdk/issues/4204

Workaround
append the following to the end of the project file
```xml
  <Target Name="_WorkaroundHandlePackageFileConflicts"
          BeforeTargets="ClCompile"
          AfterTargets="ResolveTargetingPackAssets"
          DependsOnTargets="_HandlePackageFileConflicts">
  </Target>

```
