### ISSUE TITLE
AzureDevops pipeline issue when trying to install .NET 8 Sdk 

### ISSUE THREAD

**Issue by dpenciucdhv** [dotnet/sdk#42093]
Yaml code:
  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: "8.0.101"
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
This was working until 9th of July 3PM. Didn't have any issue with it then suddenly it started to fail.

However after that I encountered this error almost every time:
**##[error]Failed to download or parse releases-index.json with error: {}**

Tried to change version to 8.0.x and 8.x but didn't had any effect.

**Comment by dpenciucdhv** [comment]
Linked to https://github.com/microsoft/azure-pipelines-tasks/issues/10969

**Comment by marcpopMSFT** [comment]
Any formatting issues with releases.json? @leecow @baronfel

**Comment by leecow** [comment]
We added a "supported-os.json" field to the file.
