### ISSUE TITLE
Allow dotnet nuget why command to take the project in the current folder as its input

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/sdk#42123]
### Is your feature request related to a problem? Please describe.

The `dotnet nuget why` command requires the project file or the folder name as a mandatory input

### Describe the solution you'd like

Like other dotnet commands, if nothing is specified, why doesn't it take the current folder name as its input and look for the project file?

### Additional context

Familiarity and the same UX across all the commands.

**Comment by baronfel** [comment]
Sorry, I know it's annoying to have to pick and choose the correct repo :( If I could I'd transfer issues over, but because NuGet is in a different GitHub org it's not possible with the native GitHub tooling.

**Comment by egvijayanand** [comment]
> Sorry, I know it's annoying to have to pick and choose the correct repo :( If I could I'd transfer issues over, but because NuGet is in a different GitHub org it's not possible with the native GitHub tooling.

That's fine. Since it's a **dotnet** command, thought that SDK would be the right repo to report.

And it seems users are on the same page as it's already reported over there.
