### ISSUE TITLE
3.1.200 runtime preview?

### ISSUE THREAD

**Issue by Logerfo** [dotnet/sdk#4214]
Where can I download the runtime binaries for the 3.1.200 preview (SDK shipped with VS 16.5 P2)? I've only found 3.1.100 and 5.0 preview...
Thanks!

**Comment by sfoslund** [comment]
Sorry for the delay, links to download the most recent builds of all active SDK branches can be found in the README of [dotnet/installer](https://github.com/dotnet/installer).
