### ISSUE TITLE
AssemblyVersion and FileVersion is not affected by VersionPrefix

### ISSUE THREAD

**Issue by djanosik** [dotnet/sdk#422]
I have migrated my .NET Core project to .csproj. The resulting project file contains a `<VersionPrefix>` element. AFAIK it should work that way:

1. `VersionPrefix` is used as a prefix (= 1.2.3 in my .csproj)
2. `VersionSuffix` is used as a suffix (not defined in my project)
3. `Version` is computed as `$(VersionPrefix)-$(VersionSuffix)` if not defined in .csproj
4. `AssemblyVersion` and `FileVersion` is based on `Version`

When I build the project, the `AssemblyVersion` and `FileVersion` are set to 1.0.0 instead of 1.2.3. When I explicitly set `Version` in my .csproj, everything works. There is something wrong.

Am I missing something?

**Comment by dsplaisted** [comment]
This looks like it's related to #93.

@djanosik To make it clearer what's happening, can you copy the relevant parts of your `project.json` and converted `.csproj` here?

**Comment by djanosik** [comment]
I don't have the original `project.json` anymore, but it was very simple. The `.csproj` after some manual edits looks like this:
```xml
<Project ToolsVersion="15.0">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <AssemblyName>Moon.Contracts</AssemblyName>
    <TargetFrameworks>net46;netstandard1.3</TargetFrameworks>
    <Description>Simple Guard (or DbC) implementation.</Description>
    <PackageTags>moon;contracts;guard</PackageTags>
    <VersionPrefix>1.2.3</VersionPrefix>
    <Company>Dušan Janošík</Company>
    <Copyright>Copyright © 2016 Dušan Janošík</Copyright>
    <Product>Moon.Libraries</Product>
    <PackageIconUrl>https://djanosik.gitlab.io/moon.png</PackageIconUrl>
    <PackageProjectUrl>https://gitlab.com/djanosik/moon-libraries</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
    <PackageReference Include="NETStandard.Library">
      <Version>1.6</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```
No I see that versions are only incorrect in binaries for `net46`. They are correct in binaries for `netstandard1.3`.

**Comment by dsplaisted** [comment]
Is `VersionSuffix` getting set anywhere?  What do you expect to happen if it isn't?

**Comment by djanosik** [comment]
No it doesn't or I don't know about it. `Version`, `AssemblyVersion` and `FileVersion` should be equal to `VersionPrefix`.

**Comment by dsplaisted** [comment]
This is fixed.  The VersionPrefix will be used for the Version, the FileVersion, and the AssemblyVersion.  For the file version it will be converted to a 4-part version, so it would be 1.2.3.0.

There is a related bug where if you edit a version property in Visual Studio, it won't be reflected until a rebuild is performed: https://github.com/dotnet/roslyn-project-system/issues/1436

**Comment by nguerrera** [comment]
It is broken for net4x.
