### ISSUE TITLE
System.Text.Json 8.0.4 is not added in the parent library like azure.identity and etc

### ISSUE THREAD

**Issue by v-spandian** [dotnet/sdk#42294]
### Exceptions (if any)

Since latest version of the system.Text.Json 8.0.4 is not added in the parent library like Azure.identity not able to use the parent library for solving issue related to Text.Json.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
I assume this is related to the STJ CVE. You can use Azure.Identity and add a direct reference to the 8.0.4 STJ to ensure you're building against and using the latest version of a transitive assembly. @ericstj as more confusion around transitive libraries and CVEs.

**Comment by ericstj** [comment]
This should be opened in the `Azure.Identity` repo to ask them to update it.  In the mean time you're free to reference JSON yourself, or even use [central package management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management). @JonDouglas and @zivkan also have an excellent blog on the topic: https://devblogs.microsoft.com/nuget/nugetaudit-2-0-elevating-security-and-trust-in-package-management/
