### ISSUE TITLE
[NETSDKE2E]With 8.0.400 SDK zip installed, Warning: "Workload garbage collection failed with error: Workload version 8.0.400-baseline.24372.6 was not found.." happens when installing maui workload.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#42358]
Build:
8.0.400 SDK .zip on win11-x64

1.Set up clean machine with .NET SDK zip installation
2.In CLI, run dotnet workload install maui --skip-manifest-update 

**Expected Result:**
No error or warnings happen

**Actual Result:**
Warning: "Workload garbage collection failed with error: Workload version 8.0.400-baseline.24372.6 was not found.." displays
![image](https://github.com/user-attachments/assets/48aba4e1-1fd2-413d-ae5d-b9052c50b678)

Note:
Also failed to uninstall maui workload
![image](https://github.com/user-attachments/assets/d333632a-35bc-4253-9545-4f9d297ff21c)

dotnet --info:
.NET SDK:
 Version:           8.0.400
 Commit:            6f7e622bb6
 Workload version:  8.0.400-manifests.c13962dc
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\v-danche\Downloads\dotnet-sdk-8.0.400-win-x64\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.400-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.400-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.400-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.400-win-x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by vdanche** [comment]
This issue not happens on exe installed

**Comment by marcpopMSFT** [comment]
@Forgind seems like the baseline manifest is leaking into uninstall and garbage collection. Does your other fix need to be expanded to more scenarios? Are either blockers in your opinion (uninstall isn't great)?

**Comment by v-xiaofchen** [comment]
This issue also repro on MacOS.
![image](https://github.com/user-attachments/assets/d25eb3bc-ec62-4c77-b3fa-0dcc6ad5b9b2)

**Comment by ChenhuiYuan01** [comment]
This issue also repro on Linux.
![image](https://github.com/user-attachments/assets/468054b2-7083-4d26-93af-8e68a8b518cb)

**Comment by marcpopMSFT** [comment]
Similar to https://github.com/dotnet/sdk/issues/42357. The garbage collector warning is not a blocker. It's too late to fix the uninstall for August but we should investigate what the fix would be.

**Comment by vdanche** [comment]
also happens on 8.0.401 zip installed.
![image](https://github.com/user-attachments/assets/2d8a5893-04ff-4f14-b2b1-88ab4472fee7)

**Comment by Forgind** [comment]
@vdanche, can you check what commit the 8.0.401 SDK you tested was on?

**Comment by baronfel** [comment]
@Forgind don't bother - this one will continue to fail because 401 is just the containers hotfix. I think we've got this fixed in the 402 builds.

**Comment by Forgind** [comment]
> @Forgind don't bother - this one will continue to fail because 401 is just the containers hotfix. I think we've got this fixed in the 402 builds.

Oh, ok. I thought we were working on 401 right now and just released 400, so I thought vdanche was talking about a preview 401 version. Sounds good then 🙂

**Comment by xPaw** [comment]
Getting similar issues on 8.0.400, I got a message to run workload update, but it's failing:

I am using linux, not using maui or anything.

```
$ dotnet workload update
[...]

No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Warning: Workload garbage collection failed with error: Workload version 8.0.400-baseline.24375.2 was not found..

Successfully updated workload(s): .

$ dotnet workload clean
--------------------------------------------------------------------------------------
Unhandled exception: System.IO.FileNotFoundException: Workload version 8.0.400-baseline.24375.2 was not found.
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()

$ dotnet workload list
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by v-elenafeng** [comment]
This should be fixed in SDK 8.0.402, @vdanche can we check and close this? Thanks!

**Comment by esrahat** [comment]
I fixed the problem by downloading .net 9 preview version of the .net sdk , uninstalled the 8.0.402 version and installed the new one.

**Comment by Westat-Transportation** [comment]
I fixed this by uninstalling 8.0.401.

**Comment by vdanche** [comment]
It has been fixed with 8.0.402 zip install on win-x64, hence close it.
![image](https://github.com/user-attachments/assets/9e72258c-bbcb-490b-be69-d75d51f011a7)

**Comment by vdanche** [comment]
@marcpopMSFT @richaverma1 This bug repro again on today's 8.0.402 zip install(a Nuget hotfix build).
![image](https://github.com/user-attachments/assets/f880c37e-ca88-490a-b786-199c36fc3f85)

**Comment by aflext** [comment]
So, when will the fixed version `SDK build 8.0.402` be released?
![image](https://github.com/user-attachments/assets/28b45157-615c-4973-b68a-2ea377fa95a7)

**Comment by marcelo-g-simas** [comment]
Any updates on this?  I am about to get our Mac build node updated and wanted to know if I can get it on the latest SDK version.

**Comment by vdanche** [comment]
@marcelo-g-simas this issue no longer repro on the latest SDK 8.0.403.

**Comment by marcelo-g-simas** [comment]
Awesome!  Thanks for the quick response.
