### ISSUE TITLE
dotnet-install fails with windowsdesktop shared runtime

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#4237]
As per the documentation, I should be able to download a specific windows desktop runtime version using this command:

```
.\dotnet-install.ps1 -Version 5.0.0-alpha.1.20078.1 -Runtime windowsdesktop -NoPath -SkipNonVersionedFiles -InstallDir C:\Users\Administrator\AppData\Local\Temp\benchmarks-server-2516\wemfckkl.hgg 
```

An error occurs:

```
[07:10:56.520] dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha.1.20078.1/windowsdesktop-runtime-5.0.0-alpha.1.20078.1-win-x64.zip
[07:10:58.738] dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-alpha.1.20078.1/windowsdesktop-runtime-5.0.0-alpha.1.20078.1-win-x64.zip
[07:10:58.790] Could not find/download: ".NET Core Windows Desktop Runtime" with version = 5.0.0-alpha.1.20078.1
[07:10:58.790] Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
[07:10:58.790] At C:\Users\Administrator\AppData\Local\Temp\benchmarks-server-2516\jw0125sx.zuz\dotnet-install.ps1:660 char:5
[07:10:58.790] +     throw "Could not find/download: `"$assetName`" with version = $Sp ...
[07:10:58.790] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[07:10:58.790]     + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
[07:10:58.790]     + FullyQualifiedErrorId : Could not find/download: ".NET Core Windows Desktop Runtime" with version = 5.0.0-alpha.
[07:10:58.790]    1.20078.1
[07:10:58.790] Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

And I verified that the version exists from the feed:
https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.windowsdesktop.app/index.json

This is blocking aspnet benchmarks on Windows

**Comment by sebastienros** [comment]
On a related note, I am deploying the apps as self-contained, and I override the runtime version with `    <FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="$(MicrosoftNETCoreAppPackageVersion)" />
`. At first I had not tried to also reset the value for `WindowsDesktop` and the build failed with a message stating it couldn't resolve the `WindowsDesktop` runtime with the version I had specified.

Example when setting `/p:MicrosoftNETCoreAppPackageVersion=5.0.0-alpha.1.20075.5`: 

```
C:\Users\Administrator\AppData\Local\Temp\benchmarks-server-7552\1i0eke2e.fzl\benchmarks\src\Benchmarks\Benchmarks.csproj : error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Runtime.win-x64 with version (= 5.0.0-alpha.1.20075.5)
C:\Users\Administrator\AppData\Local\Temp\benchmarks-server-7552\1i0eke2e.fzl\benchmarks\src\Benchmarks\Benchmarks.csproj : error NU1102:   - Found 1446 version(s) in dotnet-core [ Nearest version: 5.0.0-alpha.1.20076.1 ]
```

Which is weird as I only set this value for NETCoreApp and not WindowsDesktop.

**Comment by nguerrera** [comment]
@wli3 @dsplaisted any ideas here?

**Comment by nguerrera** [comment]
Do you get the same error for WindowsDesktop without changing the Microsoft.NETCore.App version?

**Comment by nguerrera** [comment]
Is that Update inside a Target?

**Comment by nguerrera** [comment]
@dagood, for the original issue, is it that windowsdesktop builds now have their own hive in blob storage but dotnet-install hasn’t been updated to handle it?

**Comment by dagood** [comment]
> for the original issue, is it that windowsdesktop builds now have their own hive in blob storage but dotnet-install hasn’t been updated to handle it?

Yep, e.g. https://dotnetcli.blob.core.windows.net/dotnet/WindowsDesktop/master/windowsdesktop-runtime-latest-win-x64.zip (https://github.com/dotnet/windowsdesktop#daily-builds). Only for 5.0+.

I thought there was a conversation about this somewhere but I can't find it. 😕 The base url picking code here has a hint of it but that's all: https://github.com/dotnet/cli/blob/ba194e4e6fe356af1e82abdca03e9cfbb2e3ca28/scripts/obtain/dotnet-install.ps1#L272-L275.

**Comment by wli3** [comment]
@dagood could someone from runtime contribute to this change? It should be able to condition on before and after 5.0. The url is the only contract we know. I think it is better for the team who is in charge of the publishing end point also maintain how to download it

**Comment by dagood** [comment]
> could someone from runtime contribute to this change?

Perhaps, @NikolaMilosavljevic @vatsan-madhavan @RussKie? The publishing infra is in https://github.com/dotnet/windowsdesktop.

@dleeapho would our team owning the dotnet-install scripts make sense on an ongoing basis?

> It should be able to condition on before and after 5.0.

This seems reasonable. The repo split happened specifically on 5.0, so if it's feasible to parse the version, this should be a good way to do it.

Another approach is to have the script check the WindowsDesktop path first, then as a fallback check the Runtime path.

**Comment by dleeapho** [comment]
> @dleeapho would our team owning the dotnet-install scripts make sense on an ongoing basis?
I think that makes sense, @nguerrera what do you think? We can chat offline about this too.

**Comment by wli3** [comment]
@dleeapho @nguerrera I do like this idea. At the same time would anyone (@NikolaMilosavljevic @vatsan-madhavan @RussKie) edit the download path accordingly?

**Comment by sebastienros** [comment]
I created a PR, maybe I am lucky and the change is trivial. At least to fix the download url ...

**Comment by dagood** [comment]
Unfortunately not that trivial... in 3.0/3.1, WindowsDesktop is under `Runtime`. In 5.0, it's under `WindowsDesktop`. This corresponds to the WD assets being moved into its own [windowsdesktop](https://github.com/dotnet/windowsdesktop) repo.

**Comment by nguerrera** [comment]
I wonder if it wouldn't be easier to copy the WindowsDesktop builds from 3.0/3.1 from Runtime to WindowsDesktop instead of making this script ever more complicated?

**Comment by sebastienros** [comment]
@nguerrera I am trying to create a repro for the second issue ... but a 'dotnet new' template with small changes don't trigger it, so I am adding more to it until I can repro.

**Comment by sebastienros** [comment]
@nguerrera Found the reason, I am setting `<RuntimeFrameworkVersion>$(MicrosoftNETCoreAppPackageVersion)</RuntimeFrameworkVersion>` for older versions to use a custom runtime. I assume that since a recent SDK version this is conflicting now. I made it conditional to not use it if the TFM is netcoreapp5.0 as a mitigation. I don't know if you will want to treat it as an issue though.

**Comment by nguerrera** [comment]
That’s redundant with the FrameworkReference Update and has the semantic of updating all frameworks. It’s not really usable in previews where the runtimes have different versions

**Comment by nguerrera** [comment]
On the other had I don’t know how that ever worked for you unless you were using stable 3.x version before?

**Comment by sebastienros** [comment]
I needed that for a previous version, before FrameworkReference was created, but until now it never conflicted so I just kept it as my app target all TFMs.
