### ISSUE TITLE
After updating .NET 8.0.304 SDK to .NET 8.0.400 SDK, running dotnet workload update failed to update workload manifests

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/sdk#42390]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.303 from: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.303-windows-x64-installer
3. Install .NET 8.0.400 SDK from [Pipelines - Run 20240723.2-8.0.400-rtm.24372.6,8.0.304-servicing.24372.2,8.0.108-servicing.24372.8-232548,232498,232515 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2500960&view=artifacts&pathAsName=false&type=publishedArtifacts)
4. Install Aspire 8.1.0
    `dotnet workload update `

**ACTUAL**
Running 'dotnet workload update' shows below errors
![image (5)](https://github.com/user-attachments/assets/39d5d407-a1a0-4994-b4a6-1b468ab4eaad)

**EXPECTED**
Can successfully run 'dotnet workload update' without errors
![image (6)](https://github.com/user-attachments/assets/1620502f-1b46-46a9-895f-294754aafb51)

**Comment by marcpopMSFT** [comment]
did you install the credential provider and run with --interactive? It looks like you have the release feed configured for nuget but don't have access to it.

**Comment by balachir** [comment]
@vmykagapuz @v-elenafeng let's chat more about this issue on Monday.

**Comment by v-elenafeng** [comment]
Doesn't repro this issue with the correct SDK / Feed and packageSourceCredentials.
