### ISSUE TITLE
"The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\3.1.1\hostfxr.dll failed"

### ISSUE THREAD

**Issue by johndaintree** [dotnet/sdk#4240]
```
> >dotnet --list-sdks
> Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\3.1.1\hostfxr.dll], HRESULT: 0x800700C1
> The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\3.1.1\hostfxr.dll failed
> 
> Installing .NET Core prerequisites might help resolve this problem.
>      https://go.microsoft.com/fwlink/?linkid=798306
```
 
 
I've just installed both 64 and 32 bit version of 3.1.101 from https://dotnet.microsoft.com/download/dotnet-core/3.1

The 64 bit version is fine, however the 32 bit version gives the above message. 

I'm on Windows 10 (1909, 18363.592), so I think I have all the pre-requisites (that is to say there are none).

How can  fix this?

**Comment by ClearScriptLib** [comment]
We're seeing the same issue on Windows 10 1903, affecting only the 32-bit version of .NET Core.

Strangely, it worked yesterday, but last night's Patch Tuesday reboot seems to have broken it.

**Comment by johndaintree** [comment]
Seems to be ok now in 3.1.102.

**Comment by hasmMarques** [comment]
Hi, 
@johndaintree I'm not quit sure that this problem is fixed...

I am using:
![image](https://user-images.githubusercontent.com/16259170/75977428-4ca23d00-5ed4-11ea-93ef-35c47c603a47.png)
and when I debug I get this:
![image](https://user-images.githubusercontent.com/16259170/75978081-a6efcd80-5ed5-11ea-874a-62a886d968ab.png)
This was previously working.
I tried the AnyCPU then x86 and for last x64 and the result is always the same.
Can you help me solve this issue?
Thanks in advanced!

**Comment by szszoke** [comment]
I have this issue as well. I am running Windows 10 1903 Build 18362.239.

I tried both with 3.1.200 and 3.1.201.

**Comment by minan61** [comment]
Same issue here, worked 10 mins ago, but got stuck on whatever reason

**Comment by adambarath** [comment]
By installing KB2533623 update will solve the problem for Windows 7 deployments: https://support.microsoft.com/en-gb/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

**Comment by doghappy** [comment]
> By installing KB2533623 update will solve the problem for Windows 7 deployments: https://support.microsoft.com/en-gb/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

Today, I could not download it and got a 404 page.

**Comment by doghappy** [comment]
KB3063858 fixed the problem for me!

32-bit: https://www.microsoft.com/en-us/download/details.aspx?id=47409
64-bit: https://www.microsoft.com/en-us/download/details.aspx?id=47442

—— https://www.reddit.com/r/windows/comments/ik7sp7/does_anybody_have_the_kb2533623_update_for/

**Comment by aolszowka** [comment]
Getting burned by this in Windows Server 2019 (1809) Updates didn't seem to do much for me, did anyone figure out what the actual root cause for this is?

**Comment by ccornici** [comment]
Getting the same exact thing when creating a WPF APPX bundle, installing it and running it, the app just exits and in Event Viewer I got

```
Description: A .NET Core application failed.
Application: myapp.exe
Path:  C:\Program Files\WindowsApps\myapp\myapp.exe
Message: Failed to load the dll from [C:\Program Files\WindowsApp\myapp\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\WindowsApp\myapp\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```

When I try building, installing & running a different app, which is also build on .NET Core 3.1 and uses similar nugets etc it runs without any issues

I tested on a different machine and the same issue happens.....

**Comment by ccornici** [comment]
I deleted the `bin` & `obj` folders from the projects and now it works, so I assume it's yet another VS 2019 bug....

**Comment by ccornici** [comment]
Now it doesn't work anymore again even after I delete the folders above :)

**Comment by confessore** [comment]
I get unexpected behaviors with hostfxr compiled for x86 but everything for x64 works like a dream!

there's something nutty going on with x86

**Comment by KirillOsenkov** [comment]
This is most definitely still an issue:

* install .NET SDK 64-bit
* install .NET SDK 32-bit
* run an app targeting netcoreapp3.1 and compiled with PublishSingleFile

```
Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\6.0.0-rc.2.21480.5\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\6.0.0-rc.2.21480.5\hostfxr.dll failed
```

Why is it trying to load the x86 hostfxr? Shouldn't it be trying the 64-bit one?

**Comment by RaulSebastian** [comment]
got the same issue, this should be adressed

**Comment by NCLnclNCL** [comment]
> > This is most definitely still an issue:
> > ```
> > * install .NET SDK 64-bit
> > 
> > * install .NET SDK 32-bit
> > 
> > * run an app targeting netcoreapp3.1 and compiled with PublishSingleFile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Failed to load the dll from [C:\Program Files (x86)\dotnet\host\fxr\6.0.0-rc.2.21480.5\hostfxr.dll], HRESULT: 0x800700C1
> > The library hostfxr.dll was found, but loading it from C:\Program Files (x86)\dotnet\host\fxr\6.0.0-rc.2.21480.5\hostfxr.dll failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why is it trying to load the x86 hostfxr? Shouldn't it be trying the 64-bit one?
> 
> got the same issue, this should be adressed

yes it will errors if dotnet run -a x86 in  dotnet runtime 64 bit
