### ISSUE TITLE
CORS policy.AllowAnyHeader() does not appear to work

### ISSUE THREAD

**Issue by catmanjan** [dotnet/sdk#42424]
I have the following Program.cs as part of a dotnet 8 web API project:

```
var builder = WebApplication.CreateBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddConsole();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(
        policy =>
        {
            policy.AllowAnyHeader();
            policy.AllowAnyMethod();
            policy.AllowAnyOrigin();
        });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseCors();
app.UseAuthorization();
app.MapControllers();

app.Run();
```

Notice `policy.AllowAnyHeader();`. If I browse to my API in the latest Google Chrome I get the following headers, but no Access-Control-Allow-Headers. 
![image](https://github.com/user-attachments/assets/5b43e5da-2d1e-4306-8c5a-178ba39e6ac8)

I would expect to be receiving an Access-Control-Allow-Headers value of *

**Comment by martincostello** [comment]
This issue should be filed in the [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) repository as that's where the CORS functionality lives.
