### ISSUE TITLE
Support ValueTuple in `<Using />` element

### ISSUE THREAD

**Issue by just-ero** [dotnet/sdk#42479]
### Summary

It is not possible to add a global using statement for a ValueTuple using the `<Using />` element.

```xml
<ItemGroup>
  <Using Alias="Foo" Include="(string Bar, int Baz)" />
</ItemGroup>
```

The above generates the following code:
```cs
global using Foo = global::(string Bar, int Baz);
//                         ^~~~~~~~~~~~~~~~~~~~~
// CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
// CS8805: Program using top-level statements must be an executable.
// CS8185: A declaration is not allowed in this context.
// CS0165: Use of unassigned local variable 'Bar'
```

It would be great if a case like this could be handled.

For completion's sake, the below code does compile:
```cs
global using Foo = (string Bar, int Baz);
```

**Comment by just-ero** [comment]
Perhaps it would be possible to talk to the Roslyn team about moving the generation of the file there. It could do the validation and transformation instead.

**Comment by marcpopMSFT** [comment]
Triage: @DamianEdwards I believe aspnet originally implemented implicit usings. Do you know who from that side owns it now that the original authors have moved? 

CC @jaredpar we don't think the types in a tuple can be globally namespaced as well so I'm not sure it's even possible to support Tuples in the global usings.

**Comment by DamianEdwards** [comment]
It was indeed an engineer on the ASP.NET Core team who implemented this originally but they've since left MS. Adding @adityamandaleeka @joperezr to speak to ownership moving forward.

**Comment by jaredpar** [comment]
> we don't think the types in a tuple can be globally namespaced as well so I'm not sure it's even possible to support Tuples in the global usings.

Can you elaborate on what you mean here? Using tuples in a `global using` is supported. 

```csharp
global using T = (int X, int Y);

T t = (0, 1);
System.Console.WriteLine(t.Y);
```

Note: guessing that you will hit the same bug if you're attempting to use `dynamic`. Basically any type that doesn't support `global::` prefixing.

**Comment by baronfel** [comment]
`global using T = (global::int X, global::int Y)` doesn't compile for me, and because this is intended to be 100% precise I figured that using raw type names for the tuple members would be incorrect.

**Comment by baronfel** [comment]
But yes, we need some way to take a user-provided signature and break it down into parts that need to be annotated in a way that isn't horrifically error-prone. Is there some Roslyn facility for this?

**Comment by jaredpar** [comment]
> global using T = (global::int X, global::int Y) doesn't compile for me, ...

That is expected though. The `global::` prefix is about name disambiguation and there is no ambiguity for `int` (or any other lower case type name) hence the language disallows it.

> Is there some Roslyn facility for this?

Are you all using Roslyn to generate these names?

**Comment by baronfel** [comment]
> That is expected though. The `global::` prefix is about name disambiguation and there is no ambiguity for `int` (or any other lower case type name) hence the language disallows it.

Oh duh, of course. You'd have the same problem with user-utterable names though.
 
> Are you all using Roslyn to generate these names?

We're not at the moment (implementation [here](https://github.com/dotnet/sdk/blob/5433bc4745265d7c16611f2b389b780e834eacc0/src/Tasks/Microsoft.NET.Build.Tasks/GenerateGlobalUsings.cs#L36-L51)) but since this is pretty naieve string manipulation going on, for anything more complex like tuples we'd want to use something with knowledge of the language. That's why I asked.

**Comment by jaredpar** [comment]
> You'd have the same problem with user-utterable names though.

Not following. You can use `global::` to qualify user-utterable names. Can even use nullable annotations on them.

```csharp
global using T = (global::C? X, int Y);

T t = (null, 1);
System.Console.WriteLine(t.Y);
class C { }
```

> We're not at the moment (implementation [here](https://github.com/dotnet/sdk/blob/5433bc4745265d7c16611f2b389b780e834eacc0/src/Tasks/Microsoft.NET.Build.Tasks/GenerateGlobalUsings.cs#L36-L51)) but since this is pretty naieve string manipulation going on, for anything more complex like tuples we'd want to use something with knowledge of the language. That's why I asked.

Razor has a similar problem space where there is desire to `global::` escape when possible. Possible we should look at these two cases as reason to add a better API for others to use. At the same time though, if we put that into MS.CA then you'd need a ref to that pretty low in the msbuild layer. Not sure if that's a great idea or not. 

@chsienki, @333fred, @jjonescz

**Comment by jjonescz** [comment]
Roslyn already has an API that can be used for this: SymbolDisplayFormat. In razor where we have access to `ITypeSymbol`, we do `.ToDisplayString` with [options](https://github.com/dotnet/razor/blob/062682d3219ef06d0f9ff4c4581455deb733b072/src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/CSharp/ComponentTagHelperDescriptorProvider.cs#L19-L22) that enable the `global::` qualifier.

(Razor also has a [TypeNameHelper](https://github.com/dotnet/razor/blob/062682d3219ef06d0f9ff4c4581455deb733b072/src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/TypeNameHelper.cs#L10) which attempts to do `global::`-prefixing on plain strings without roslyn but it's probably very broken.)

**Comment by peteraritchie** [comment]
Did you encounter this when working on [Refactor your code using alias any type](https://devblogs.microsoft.com/dotnet/refactor-your-code-using-alias-any-type/) @IEvangelist ?

**Comment by peteraritchie** [comment]
> I think the task should simply be changed to never add `global::`, unless someone can explain why it's needed.

`global::` is necessary, especially in the context of aliases, to ensure you're referencing the named type you think you're referencing. `(string Bar, int Baz)` or `(string, Bar, Baz)` aren't named types and shouldn't have `global::` prepended to them.

**Comment by jjonescz** [comment]
> It isn't clear to me why .NET SDK adds this `global::` to `global using` directives at all; what scenario does that enable?

Good point, the generated global usings file shouldn't need `global::` prefixes.

**Comment by SeanFeldman** [comment]
What SDK version is it going to be released in?
