### ISSUE TITLE
[NETSDKE2E]With Net9 preview 7 zip installed, maui workload update failed: Version 9.0.0-preview.7.24405.1 of package microsoft.maui.core is not found...

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#42525]
Build info:
9.0.100-preview.7.24402.8 (runtime-9.0.0-preview.7.24401.8)

Repro steps:
1.Download the NET9 preview 7 SDK zip package.
2.Modify environment variables
3.Install workload with commands.
dotnet workload install maui --skip-manifest-update
dotnet workload update

**Expected:**
maui workload update successfully
**Actual Result:**
maui workload update failed: Version 9.0.0-preview.7.24405.1 of package microsoft.maui.core is not found...
![image](https://github.com/user-attachments/assets/9f3d3e77-0fa1-4cef-95e3-da242e445e2d)
but workload versions is still updated successfully.
![image](https://github.com/user-attachments/assets/b1064a86-1041-4ba1-a9ca-a962af2d3ae4)

note: not repro on exe install
![image](https://github.com/user-attachments/assets/91575811-2fbd-4492-85ee-82c7679bb8ba)

.NET SDK:
Version:           9.0.100-preview.7.24402.8
Commit:            afec422ea7
Workload version:  9.0.100-manifests.799dfc64
MSBuild version:   17.12.0-preview-24374-02+48e81c6f1
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Users\v-haren\Downloads\dotnet-sdk-9.0.100-preview.7\sdk\9.0.100-preview.7.24402.8\
 
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-preview.7.24401.8
  Architecture: x64
  Commit:       static
 
.NET SDKs installed:
  9.0.100-preview.7.24402.8 [C:\Users\v-haren\Downloads\dotnet-sdk-9.0.100-preview.7\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.7.24402.2 [C:\Users\v-haren\Downloads\dotnet-sdk-9.0.100-preview.7\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24401.8 [C:\Users\v-haren\Downloads\dotnet-sdk-9.0.100-preview.7\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24402.3 [C:\Users\v-haren\Downloads\dotnet-sdk-9.0.100-preview.7\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.
Build info: .net9.0.100-preview.7.24402.8(runtime-9.0.0-preview.7.24401.8)sdk
![image](https://github.com/user-attachments/assets/170b9203-b065-4e21-96fe-d494da8c017d)

**Comment by ChenhuiYuan01** [comment]
This issue also reproduces on Linux.
![image](https://github.com/user-attachments/assets/6ffc9e6e-a3df-4cd9-b2b1-7a3ad8190112)
![image](https://github.com/user-attachments/assets/c03aed4c-0019-41ce-a60c-14c54cc59d86)

**Comment by marcpopMSFT** [comment]
Did you include the dotnet9 feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

Maui isn't included in the coherency feed and we haven't completed our process for getting it into the dotnet9 workloads release feed.  So for now, it's still on the dotnet9 feed.

This is not a blocker assuming getting the right feed solves it.

**Comment by vdanche** [comment]
@marcpopMSFT Yesterday we had included the dotnet9 feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json, we lack the coherency feed as it did not come out yesterday. Fortunately, this issue not happens on today's candidate build: 9.0.100-preview.7.24402.8 (runtime-9.0.0-preview.7.24401.8). Thanks
![image](https://github.com/user-attachments/assets/1ab28ae4-d77a-45a7-ab67-03dc4caea0fe)
![image](https://github.com/user-attachments/assets/57bfa641-162d-4971-b873-9a4d7316fb3f)

FYI @richaverma1
