### ISSUE TITLE
[NETSDKE2E]With NET9 p7 zip installed, the prompt message "update are available for the..." should be displayed after running "dotnet workload install maui --skip-manifest-update".

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#42526]
Build info:
.net9.0.100-preview.7.24402.8(runtime-9.0.0-preview.7.24401.8)sdk

Repro steps:
1.Download the NET9 preview 7 SDK zip package.
2.Modify environment variables
3.Install workload with commands.
`dotnet workload install maui --skip-manifest-update`
4.Check the workload list
`dotnet workload list`

Expected:
The workload list should display normally and prompt to update.
![image](https://github.com/user-attachments/assets/6ec05f98-7200-4253-9cde-f0bbceed4bae)

Actual Result:
After installing maui --skip-manifest-update, there is no prompt "Update available for...".
![image](https://github.com/user-attachments/assets/fae747c2-f4a9-4646-aa6e-5a84a51c00e1)

dotnet --info
.NET SDK:
Version:           9.0.100-preview.7.24402.8
Commit:            afec422ea7
Workload version:  9.0.100-manifests.1a228730
MSBuild version:   17.12.0-preview-24374-02+48e81c6f1
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win-arm64
Base Path:   C:\dotnet-sdk-9.0.100-preview.7.24402.8-win-arm64\sdk\9.0.100-preview.7.24402.8\
 
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.
 
Host:
  Version:      9.0.0-preview.7.24401.8
  Architecture: arm64
  Commit:       static
 
.NET SDKs installed:
  9.0.100-preview.7.24402.8 [C:\dotnet-sdk-9.0.100-preview.7.24402.8-win-arm64\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.7.24402.2 [C:\dotnet-sdk-9.0.100-preview.7.24402.8-win-arm64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24401.8 [C:\dotnet-sdk-9.0.100-preview.7.24402.8-win-arm64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24402.3 [C:\dotnet-sdk-9.0.100-preview.7.24402.8-win-arm64\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue does not repro on winx64OS.
![image](https://github.com/user-attachments/assets/05f71c5c-eaad-4ebe-af89-11126ea7340e)

**Comment by ChenhuiYuan01** [comment]
This issue also reproduces on Linux.
![image](https://github.com/user-attachments/assets/bde7ba5c-9dbc-422a-a1e6-b51969419021)

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.
![image](https://github.com/user-attachments/assets/183e796c-1241-42a8-948a-4f9dd1d5fbdf)

**Comment by marcpopMSFT** [comment]
Do you have the preview 7 feed configured? Note that we don't check for workload updates on every single command as that requires a network hit. I'd have to check but I think we do it only on build commands and limit to once a day in the background. This is not a blocker fwiw.

**Comment by v-ainigao** [comment]
> Do you have the preview 7 feed configured? Note that we don't check for workload updates on every single command as that requires a network hit. I'd have to check but I think we do it only on build commands and limit to once a day in the background. This is not a blocker fwiw.

we have been added 9.0public feed.`<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />`

**Comment by v-ainigao** [comment]
> Do you have the preview 7 feed configured? Note that we don't check for workload updates on every single command as that requires a network hit. I'd have to check but I think we do it only on build commands and limit to once a day in the background. This is not a blocker fwiw.

We have been added 9.0public feed yesterday.
`<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />`
Today we tested with the provided net9 preview 7 feed and the issue still repro.
![image](https://github.com/user-attachments/assets/65472bd6-b21b-463c-a7c6-87e58cb3e6af)
`dotnet workload install maui --skip-manifest-update `
![image](https://github.com/user-attachments/assets/d226dd93-b518-40d9-ab4b-1682d0461ec8)

**Comment by v-xiaofchen** [comment]
This issue also repro on Mac-ARM64.
![image](https://github.com/user-attachments/assets/401f171e-35b3-41fa-9da2-ca12e838a38a)

**Comment by marcpopMSFT** [comment]
@v-ainigao can you try running a build in between installing maui and running list? If that doesn't cause the list to show the prompt, can you try `dotnet workload update --advertising-manifests-only`?

**Comment by v-ainigao** [comment]
> @v-ainigao can you try running a build in between installing maui and running list? If that doesn't cause the list to show the prompt, can you try `dotnet workload update --advertising-manifests-only`?

I tried the first method, and it showed the upgrade prompt.
build info: .net9.0.100-rc.2.24420.21sdk
![image](https://github.com/user-attachments/assets/bdf94f2a-e1e3-424f-82dd-3688b165098f)
![image](https://github.com/user-attachments/assets/d46f9b51-50e8-4f89-817c-a1c49119a7fd)

**Comment by baronfel** [comment]
Thanks for doing that @v-ainigao - that confirms that we did to run the background updater mechanism to get the advertising manifest updates, like we thought. This is as designed, so we'll close this issue.
