### ISSUE TITLE
Applications published as single file fail if extracted contents are not complete

### ISSUE THREAD

**Issue by lunim** [dotnet/sdk#4257]
When using the "PublishSingleFile=true", upon first run the application runtime is extracted to a path like this: %temp%/.net/(application)/<guid>.

If some of the contents are removed, the application fails with an error like so:

`An assembly specified in the application dependencies manifest (app.deps.json) was not found:
    package: 'YamlDotNet', version: '5.0.1'
    path: 'lib/netstandard1.3/YamlDotNet.dll'`

The primary issue is that the single-file application makes no attempt to correct or restore the environment.  The end-user must manually navigate to the temporary path and clear the entire directory before the application will run again.

Version: .Net core 3.1
OS: Windows/Linux

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/3778

**Comment by swaroop-sridhar** [comment]
@wli3  this is a runtime issue, and should be resolved as a dup of dotnet/runtime#3778
