### ISSUE TITLE
Don't reference Microsoft.Windows.SDK.NET.Ref for C++/CLI projects

### ISSUE THREAD

**Issue by lukka** [dotnet/sdk#42599]
Regression identical to https://github.com/dotnet/sdk/issues/26203

The packages 
- Microsoft.NET.Sdk.Ref
- Microsoft.Net.Compilers.Toolset.Framework
are not needed for Visual Studio  C++ managed project such as "CLR .NET Projects."

A PR similar to would fix the problem: https://github.com/dotnet/sdk/pull/42515/files

FYI @marcpopMSFT @dsplaisted @jaredpar

**Comment by marcpopMSFT** [comment]
#42605
