### ISSUE TITLE
`build.cmd` should have a flag like `-s` or `--sdk-only` to skip installer build

### ISSUE THREAD

**Issue by nagilson** [dotnet/sdk#42627]
We should also have some sort of banner in the build that shows all components of the .NET SDK are done building.

The installer is failing to build a lot of the time for me. I would love to be able to cancel the build mid-build. Having some sort of header for the build components like 

====
SDK
====

====
Installer
==== 

etc would be great, since the installer doesn't need to be built to actually run the SDK. Sometimes my laptop takes 30+ minutes per build and totally freezes it up (I literally can't see this sentence on my screen as I type it because it's too laggy...) so having this would be great.

cc @MiYanni

**Comment by marcpopMSFT** [comment]
@nagilson was my -pack addition not enough? It still builds redist-installer but just skips all of the zip/exe bundles which should save most of the time that was installer.

**Comment by nagilson** [comment]
I forgot that existed, so I think that is enough.
