### ISSUE TITLE
[Linux]There are some warnings "Warning: Workload garbage collection failed with error: Workload pack 'Microsoft.NET.Runtime.Emscripten.Node.net8' in manifest ..." when running "dotnet workload update" in CMD after installing SDK 8.0.400 and SDK 9.0.100-preview.7

### ISSUE THREAD

**Issue by Rita003** [dotnet/sdk#42667]
**REGRESSION INFO**: Work in SDK 8.0.303+SDK 9.0 Preview 6

**REPRO STEPS**
1. Repro OS: Linux OS
2. Install SDK 8.0.400
    - Apply August Servicing 8.0 feed and PAT
3. Install SDK 9.0.100-preview.7.24407.12
   - Apply 9.0 Preview 7 feed
4. Open command line and run the following command
`sudo dotnet workload update`

**ACTUAL**
There are some warnings when running `dotnet workload update` in CMD
![Screenshot 2024-08-12 142220](https://github.com/user-attachments/assets/ded11de3-f229-43a0-8015-3acb213aa5fe)

**EXPECTED**
Running `dotnet workload update` successfully without any warning.

**Error Log**
`Warning: Workload garbage collection failed with error: Workload pack 'Microsoft.NET.Runtime.Emscripten.Node.net8' in manifest 'microsoft.net.workload.emscripten.net8' [/home/parallels/dotnet/sdk-manifests/9.0.100-preview.7/microsoft.net.workload.emscripten.net8/9.0.0-preview.7.24373.5/WorkloadManifest.json] conflicts with manifest 'microsoft.net.workload.emscripten.current' [/home/parallels/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.emscripten.current/8.0.8/WorkloadManifest.json].`

**Comment by v-sherryfan** [comment]
This issue also repro on Mac arm64.

**Comment by v-elenafeng** [comment]
[Mac/Linux] This issue is still reproducible with SDK 8.0.402 (pre-release) + SDK 9.0 RC1 (pre-release) and also reproduced with the latest released SDK 8.0.401 + SDK 9.0 P7. 

@baronfel, could you please help investigate this? Thanks!
