### ISSUE TITLE
Unable to install maui-android workload on Archlinux

### ISSUE THREAD

**Issue by danielAyerra** [dotnet/sdk#42676]
### Describe the bug
I am unable to install .Net maui on ArchLinux

### To Reproduce

```bash
  sudo dotnet workload install maui-android
```

### Exceptions (if any)

```
   No se reconoce el id. de carga de trabajo maui-android.
```
```
  Unrecognized workload id
```

#### Dotnet info
>SDK DE .NET:
> Version:           8.0.107
> Commit:            1bdaef7265
> Workload version:  8.0.100-manifests.d10aeb72
>
> Entorno de tiempo de ejecución:
>
>  OS Name:     arch
>  OS Version:  
>  OS Platform: Linux
>  RID:         arch-x64
>  Base Path:   /usr/share/dotnet/sdk/8.0.107/
> 
> Cargas de trabajo de .NET instaladas:
>  Workload version: 8.0.100-manifests.d10aeb72
>  [wasi-experimental]
>    Origen de la instalación: SDK 8.0.100
>    Versión del manifiesto:    8.0.7/8.0.100
>    Ruta de acceso del manifiesto:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.7/WorkloadManifest.json
>    Tipo de instalación:        FileBased
> 
>  [wasm-tools-net7]
>    Origen de la instalación: SDK 8.0.100
>    Versión del manifiesto:    8.0.7/8.0.100
>    Ruta de acceso del manifiesto:       /usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net7/8.0.7/WorkloadManifest.json
>    Tipo de instalación:        FileBased
> 
> 
> Host:
>   Version:      8.0.7
>   Architecture: x64
>   Commit:       2aade6beb0
> 
> .NET SDKs installed:
>   6.0.132 [/usr/share/dotnet/sdk]
>   7.0.406 [/usr/share/dotnet/sdk]
>   8.0.107 [/usr/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.32 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   DOTNET_ROOT       [/home/Weinman/.dotnet]
> 
> global.json file:
>   Not found

VS CODE ID: 
1.92.1                                                                                                        
eaa41d57266683296de7d118f574d0c2652e1fc4                                                                      
x64

**Comment by baronfel** [comment]
Hi @danielAyerra - this is a known issue for the source-built versions of the SDK. Please see https://github.com/dotnet/source-build/issues/3242 for the status of this issue.
