### ISSUE TITLE
Default for "Description" should indicate that it's also an assembly description

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#427]
This is both an assembly and package description - so the default should indicate that:

![image](https://cloud.githubusercontent.com/assets/1103906/20612260/21cd701c-b30c-11e6-920b-0b034c3cc323.png)

**Comment by Bartmax** [comment]
Isn't the title of that window "Assembly Information" ? From that screenshot I infer is the Assembly Description (not package description)

**Comment by davkean** [comment]
Description is shared between assembly and the package - but the default calls it "Package Description"

**Comment by davkean** [comment]
The UI is going to change/be updated to include package information and make it clear that they are shared in some cases.

**Comment by srivatsn** [comment]
As part of https://github.com/dotnet/roslyn-project-system/issues/758 a new package-specific page is being created.
