### ISSUE TITLE
Dotnet publish container regression in 8.0.400

### ISSUE THREAD

**Issue by Vhab** [dotnet/sdk#42719]
### Describe the bug

Cross-posting a [bug report](https://github.com/dotnet/sdk-container-builds/issues/587) here for extra visibility, as I suspect this can be affecting many users.

`dotnet publish /t:PublishContainer` throws a ` System.ArgumentNullException` when using a specific hierarchy of `ProjectReference`.

### To Reproduce

Code to reproduce:

https://github.com/Vhab/DotnetContainerPublish8-0-400-Repro/tree/main

Contains 3 projects.
`Test` depends on `Test2` and `Test3`
`Test3` depends on `Test2`

We try to publish `Test`

This hierarchy is sufficient to trigger the crash.

### Exceptions (if any)

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  Test2 -> D:\private-github\DotnetContainerPublish8-0-400-Repro\Test2\bin\Release\net8.0\Test2.dll
  Test3 -> D:\private-github\DotnetContainerPublish8-0-400-Repro\Test3\bin\Release\net8.0\Test3.dll
  Test -> D:\private-github\DotnetContainerPublish8-0-400-Repro\Test\bin\Release\net8.0\Test.dll
  Test -> D:\private-github\DotnetContainerPublish8-0-400-Repro\Test\bin\Release\net8.0\publish\
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\RemcovanOosterhout\AppData\Local\Temp\MSBuildTemp\" and
will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\RemcovanOosterhout\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-30864_86a9c20c09c04d99b1f1231a65f21341.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 30864:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 8/14/2024 10:10:31 AM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent
localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
```

### Further technical details

.NET SDK version 8.0.400
Reproduced on both Windows 11 and Ubuntu 22.04.

**Comment by snailcatcher** [comment]
We have exactly the same problem in our build pipelines.
Explicitly using *.NET 8.0.304* can be used as workaround, but is not a really good solution!

**Comment by snailcatcher** [comment]
I think this is the same issue as https://github.com/actions/runner-images/issues/10437

**Comment by Vhab** [comment]
`DOTNET_CLI_TELEMETRY_OPTOUT=1` appears to be a valid workaround.

This means the issue is localized to the telemetry code.

**Comment by baronfel** [comment]
This is indeed a hard crash in the MSBuild telemetry subsystem - we have a 401 hotfix SDK that we plan to release tomorrow to fix this regression. 

Notably the CLI telemetry output did not seem to work consistently in our testing, so your mileage may vary.

**Comment by baronfel** [comment]
(nit: moved to a separate issue for authoritative purposes: https://github.com/dotnet/sdk/issues/42731).

**Comment by baronfel** [comment]
The [8.0.401](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) hotfix SDK has been released on all channels and contains a fix for this issue.
