### ISSUE TITLE
[iOS] Net 9 Preview 7, iOS app in Release will crash when UseInterpreter is set to true

### ISSUE THREAD

**Issue by DominicGenetec** [dotnet/sdk#42752]
### Describe the bug
Net 9 Preview 7, On iOS trying to use <UseInterpreter> in release on a real ios device will prevent the app from launching.

### To Reproduce
I'm running everything on a M1 mac.
Install net 9 preview 7
Create an iOS sample using the maui template. (or use the one i've included, see below)
Connect a real phone (not a simulator)
Compile in release and make sure the app is working.

Add this line in the csproj
```
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
          <UseInterpreter>true</UseInterpreter>
    </PropertyGroup>
```
Notice the app will crash on launch.

### Exceptions (if any)
There are no crash log available in the mac Console,  the app start and immediately exit.

### Further technical details
It work fine on Net 8.
In dot net 9 preview 5, launching in debug on a iphone would also crash the application, but that seems to be fixed in preview 7.

I've made a sample app with the UseInterpreter already added. Open the MauiApp1.sln and launch it in release on a real iOS device.
[MauiApp1.zip](https://github.com/user-attachments/files/16625082/MauiApp1.zip)

**Comment by baronfel** [comment]
Cc @dotnet/macios

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21061
