### ISSUE TITLE
dotnet run doesn't work with netstandard 2.0

### ISSUE THREAD

**Issue by SLaks** [dotnet/sdk#428]
In VS 2017 RC, I changed a Console App (core) to ` <TargetFramework>netstandard2.0</TargetFramework>`.

`dotnet run` gives

>Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Exe'.

**Comment by davidfowl** [comment]
NetStandard 2.0 doesn't exist for anyone in the real world yet.

/cc @terrajobst

**Comment by SLaks** [comment]
Why don't I get a more-useful error if I specify a `netstandardX.X` target framework that doesn't exist?

**Comment by davidfowl** [comment]
Because the tooling is alpha at this point. There's *tons* of bugs.

**Comment by davidfowl** [comment]
Also, you shouldn't have a netstandard application, you should have a netstandard library... Your application should target a specific platform (.NET Core, .NET Framework, UWP etc).

**Comment by srivatsn** [comment]
@livarcocc @piotrpMSFT do we emit a better error from the CLI now?

**Comment by piotrpMSFT** [comment]
This bug belongs in CLI repo.

We're not doing any work towards the netcoreapp2.0 scenario until the current 1.x train is out the door.

As @davidfowl says, the message here is correct. netstandard2.0 is not a runnable tfm. If you target netcoreapp2.0 along with appropriate Microsoft.NetCore.App version you should get a nice message telling you what versions of netcoreapp are installed. 

It would be nice if @SLaks can open an issue to track improving the message when a project file targets a non-runnable tfm and non-runnable package and still expects to be run. We can probably provide a hint like "A runnable project must reference a runnable TFM and Metapackage. These are typically `netcoreapp1.0` and `Microsoft.NetCore.App`" or something along those lines. Seems like a nice fit-n-finish feature.

**Comment by srivatsn** [comment]
Moved to https://github.com/dotnet/cli/issues/5111

**Comment by cristian-eriomenco** [comment]
Is the tooling still in alpha today? 
P.S.
`dotnet --version
2.2.105
`
