### ISSUE TITLE
CopyDocumentationFilesFromPackages behave different in docker

### ISSUE THREAD

**Issue by yangon99** [dotnet/sdk#42825]
### Describe the bug
When I try to build my project with docker image `mcr.microsoft.com/dotnet/sdk:8.0-alpine-amd64` or `mcr.microsoft.com/dotnet/sdk:8.0`, I notice a difference in the behavior of the CopyDocumentationFilesFromPackages feature compared to my host system (Debian 12). On my host, after I run `dotnet build` , all of the xml document of the packagesare are correctly placed in the `bin/Debug/net8.0` directory. However, when I build the project in Docker, these XML documentation files are missing.

### To Reproduce
```shell
docker run -it /bin/bash mcr.microsoft.com/dotnet/sdk:8.0
dotnet new console
dotnet add package Newtonsoft.Json
```
and then i add `<CopyDocumentationFilesFromPackages>True</CopyDocumentationFilesFromPackages>` in csproj.
After that, i run `dotnet build`. there's no xml document found in folder `bin/Debug/net8.0`.

```shell
# ls bin/Debug/net8.0/
Newtonsoft.Json.dll  temp  temp.deps.json  temp.dll  temp.pdb  temp.runtimeconfig.json
```

### Exceptions (if any)
none

### Further technical details
- log of `dotnet build -v n`: https://fars.ee/InlR

- `dotnet --info` in `mcr.microsoft.com/dotnet/sdk:8.0`
```
# dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
This is due to a decision made in the .NET SDK base images produced at [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker/issues/2790). If you use the MIcrosoft .NET SDK base images, use `ENV NUGET_XMLDOC_MODE=` to remove this setting and restore the behavior you get from your local host.
