### ISSUE TITLE
`dotnet restore -v:n` doesn't show the log

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/sdk#42835]
`dotnet restore -v:n` doesn't show the log.

If I disable the terminal logger is fine:

`dotnet restore -v:n -tl:off`

.NET SDK:
Version:           9.0.100-dev
Commit:            b31edff014
Workload version:  9.0.100-manifests.89dac32e
MSBuild version:   17.12.0-preview-24407-03+6bc91d5e2

cc: @mariam-abdulla

**Comment by tmds** [comment]
@baronfel @rainersigwald it's very unexpected that setting the verbosity flag does not actually cause the CLI to be more verbose.

**Comment by tmds** [comment]
@marcpopMSFT @baronfel @rainersigwald can we try to address this UX regression in the 9.0.1xx SDK?

**Comment by tmds** [comment]
> Try with -v detailed or -v diag and see if that shows the message you want

See https://github.com/dotnet/sdk/issues/43069#issuecomment-2340892513.

**Comment by baronfel** [comment]
Closing as we've made TL respect verbosity (at a detailed or diagnostic level).
