### ISSUE TITLE
Track signature errors

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#42870]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=781861
Build error leg or test failing: Microsoft.NET.Publish.Tests.GivenThatWeWantToPublishASingleFileApp.PublishSingleFile_fails_for_unsupported_target_framework
Pull request: https://github.com/dotnet/sdk.git/pull/42864

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "The package signature is invalid or cannot be verified on this platform.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=781861
**Error message validated:** `[The package signature is invalid or cannot be verified on this platform.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/20/2024 8:13:29 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
https://github.com/dotnet/aspnetcore/issues/57416 was happening on the same prs in sdk sometimes

**Comment by lewing** [comment]
https://github.com/dotnet/sdk/pull/42858 has both

**Comment by lewing** [comment]
the nuget code in question is: https://github.com/NuGet/NuGet.Client/blob/11d7ba57371b61c8167a956cd7b97e0cd355e88b/src/NuGet.Core/NuGet.Packaging/Signing/Verification/PackageSignatureVerifier.cs#L75-L77

**Comment by marcpopMSFT** [comment]
Zero recent failures reported and no tests linked to this issue.
