### ISSUE TITLE
Dotnet test always fails with "strong name validation failed" when discovering tests

### ISSUE THREAD

**Issue by gmartinezsan** [dotnet/sdk#429]
We have a multitarget project for net451 and netcore. Dotnet tests always fails the discovery tests in the net451 builds saying that the assembly does not have a strong name. Even that the assemblies are signed.

I noticed that dotnet tests always says that it needs to compile again even though we have just compiled the project.
Message:
```
Project MySql.Data.Tests (.NETFramework,Version=v4.5.1) will be compiled because Input items removed from last build
```
Same process works fine for netcore. 

Is this a known issue?

Dependencies:
```
"dotnet-test-xunit": "2.2.0-*",
"xunit": "2.2.0-*",
```

dotnet --info
```
.NET Command Line Tools (1.0.0-preview2-003133)
Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c
```

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by srivatsn** [comment]
Tagging @codito. Should this be moved to the CLI repo or the vstest repo?

**Comment by srivatsn** [comment]
@dotnet/vstest

**Comment by codito** [comment]
It is related to project.json based test experience. May be cli repo is the right place.

@gmartinezsan does this issue show up for csproj based project on preview3+ tooling? `dotnet test --nobuild` shouldn't attempt a build on the project.

**Comment by srivatsn** [comment]
Moved to https://github.com/dotnet/cli/issues/5113

**Comment by gmartinezsan** [comment]
@codito Thanks a lot the --no-build option worked for our case.
