### ISSUE TITLE
[NETE2ESDK]With NET 9 RC1 SDK installed, “Android-35” is missing in the output of "dotnet workload search" after installing workload.

### ISSUE THREAD

**Issue by ChenhuiYuan01** [dotnet/sdk#43051]
**Describe the bug**
With NET 9 RC1 SDK installed, “Android-35” is missing in the output of "dotnet workload search" after installing workload.

**To Reproduce**

1.Prepare clean Windows machine.
2.Install .NET 9 rc1 SDK 9.0.100-rc.1.24422.10
3.dotnet workload search as below
![search1](https://github.com/user-attachments/assets/07e9e0c7-810c-408d-acc2-1926dc5b6b37)
4.dotnet workload install android (currently package missing)
![image (6)](https://github.com/user-attachments/assets/d5ea7b41-503f-4982-a336-13cba99a2945)
5.dotnet workload search

**Expected:**
Step5: The contents in output of search should be the same with step3

**Exceptions (if any)**
“Android-35” is missing in the output of "dotnet workload search" after installing workload.
![image (4)](https://github.com/user-attachments/assets/a14050b1-86e9-408a-b024-ea6143d48bdf)

**Dotnet --info**
![image (5)](https://github.com/user-attachments/assets/5047a363-1a44-43fe-848a-f591746c87ba)

**Comment by ChenhuiYuan01** [comment]
This issue is also repro on windows.
![image](https://github.com/user-attachments/assets/92551c15-5e53-41f9-813d-1de8010485d7)
![image (1)](https://github.com/user-attachments/assets/14c37b03-9a51-4861-ab54-cb7be4c00dc4)
![image (2)](https://github.com/user-attachments/assets/284c206c-2188-45ce-8289-c823d5ecf908)

**Comment by vdanche** [comment]
This issue also happens on net9 preview 7 SDK

**Comment by ChenhuiYuan01** [comment]
This issue also happens on net9 rc2 SDK
![search11](https://github.com/user-attachments/assets/b75b8a33-497c-4b8f-9b0c-7f79d66a1ace)
![Screenshot 2024-08-28 170436](https://github.com/user-attachments/assets/9a1bf186-c8e3-4ff1-ba5c-f4f4ad1d6685)

**Comment by v-xiaofchen** [comment]
This issue is also repro on Mac.

**Comment by jonathanpeppers** [comment]
@ChenhuiYuan01 `android-35` is only present for a period of time when API 35 is in preview.

It is removed now, because API 35 is stable and the default for .NET 9:

* https://github.com/dotnet/android/pull/9043

As for the error:
```
Version 34.0.137 of microsoft.android.* not found.
```

You would need this feed for 34.0.137
```xml
<add key="darc-pub-dotnet-android-b0fd011" value="
https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-android-b0fd0113/nuget/v3/index.json
" />
```

This package is shipping same day as next .NET 9 release.

**Comment by marcpopMSFT** [comment]
Sounds like from Jonathan that that workload vanishing on update is expected and I'll go ahead and close out this issue.
