### ISSUE TITLE
Cleanup unnecessary branches

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#43106]
There're some stale branches, could we get them removed to keep the repo clean

![image](https://github.com/user-attachments/assets/88bc05b2-9b1f-4abe-94fc-b979d0c432a0)

**Comment by marcpopMSFT** [comment]
I started deleting any branches older than a year that weren't associated with an active PR (besides release branches). I did another pass today and cleaned up about a dozen or so. I think that should cover this and I'll do another pass in 6 months probably.
