### ISSUE TITLE
[NETSDKE2E] With 9.0.100-rc.2.24429.8 SDK exe installed, "Warning: Workload garbage collection failed with error: Failed to get global.json GC roots Value cannot be null. (Parameter 'key')" is shown after installing wasm-tools workload.

### ISSUE THREAD

**Issue by darrenarvin123** [dotnet/sdk#43114]
Build:
9.0.100-rc.2.24429.8 SDK on win10-x64

1.Set up a clean machine with .NET SDK exe installed
2.In CLI, run dotnet workload install wasm-tools 

Expected Result:
wasm-tools installs successfully without any warnings or errors

Actual Result:
Warning: Workload garbage collection failed with error: Failed to get global.json GC roots Value cannot be null. (Parameter 'key') is shown
![image](https://github.com/user-attachments/assets/66d3671c-8baf-4274-96ce-911130deba5e)

Note:
Also seen when installing android workload 
![image](https://github.com/user-attachments/assets/65b8e94f-fe89-441f-b402-0de5e024b1ca)

dotnet --info
.NET SDK:
 Version:           9.0.100-rc.2.24429.8
 Commit:            6ccac5fda3
 Workload version:  9.0.100-manifests.839ab7ed
 MSBuild version:   17.12.0-preview-24427-01+c256bcca0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24429.8\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 9.0.100-rc.2
   Manifest Version:    35.0.0-rc.2.89/9.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.2\microsoft.net.sdk.android\35.0.0-rc.2.89\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: SDK 9.0.100-rc.2
   Manifest Version:    9.0.0-rc.2.24429.5/9.0.100-rc.2
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.2\microsoft.net.workload.mono.toolchain.current\9.0.0-rc.2.24429.5\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.0-rc.2.24427.10
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-rc.2.24429.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rc.2.24426.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24427.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24428.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
@dsplaisted workload garbage collection error. Please take a look.

**Comment by v-ainigao** [comment]
A similar error occurs when running `dotnet workload clean --all` with .net9.0.100-rc.2.24460.10sdk on ARM64OS.
![image](https://github.com/user-attachments/assets/ced26dad-02e7-4f68-8e1c-bdc8f527088d)
Unhandled exception: Microsoft.DotNet.Workloads.Workload.WorkloadException: Failed to get global.json GC roots Value cannot be null. (Parameter 'key')
   at Microsoft.DotNet.Installer.Windows.InstallerBase.ExitOnFailure(InstallResponseMessage response, String message)
   at Microsoft.DotNet.Installer.Windows.MsiInstallerBase.GetGlobalJsonWorkloadSetVersions(SdkFeatureBand sdkFeatureBand)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
   at Microsoft.DotNet.Workloads.Workload.Clean.WorkloadCleanCommand.ExecuteGarbageCollection()
   at Microsoft.DotNet.Cli.WorkloadCleanCommandParser.<>c.<ConstructCommand>b__3_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

**Comment by vdanche** [comment]
not repro on SDK:9.0.100-rc.2.24474.11(runtime-9.0.0-rc.2.24473.5) 
![image](https://github.com/user-attachments/assets/4ba8cb25-7a2d-4ea0-bc98-84d6ed5c4fd3)

**Comment by marcpopMSFT** [comment]
Marking closed since it's fixed in the shipping RC2 build
