### ISSUE TITLE
Unable to load projects after dotnet migrate

### ISSUE THREAD

**Issue by ctaggart** [dotnet/sdk#432]
`dotnet migrate` didn't update the `sln` files. I attempted to replace `xproj with `csproj` in the `sln` files. See #431 for bigger picture.

``` sh
bash -c "find . -type f -name '*.sln' -print0 | xargs -0 sed -i 's/.xproj/.csproj/g'"
```

but that obviously didn't work:
![image](https://cloud.githubusercontent.com/assets/80104/20642488/fc5bd5f8-b3c4-11e6-9fc7-16567c71e5c4.png)

The new `csproj` files do not have ProjectGuid elements like `<ProjectGuid>{2BE58BD9-41A9-48A2-A2E0-A3B33BB79AFE}</ProjectGuid>`, which is awesome. The `sln` files still do, but how do I match them up? Can I generate on from the filename or something?

**Comment by ctaggart** [comment]
The ProjectGuids don't appear to be the issue. I'm able to change them in working sln files.

**Comment by ctaggart** [comment]
When I try reloading a project in Visual Studio 2017 RC, I just get the unhelpful:

```
---------------------------
Microsoft Visual Studio
---------------------------
The operation could not be completed. Unspecified error 
---------------------------
OK   
---------------------------
```

![image](https://cloud.githubusercontent.com/assets/80104/20642701/9c767ff2-b3ca-11e6-95d4-db2050f08b1b.png)

**Comment by srivatsn** [comment]
This is tracked by https://github.com/dotnet/cli/issues/4632
