### ISSUE TITLE
v9 SDK doesn't print nupkg path on `dotnet pack`

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#43248]
### Describe the bug

All prior versions of the .NET SDK printed the path of a built .nupkg. But the v9 preview hides this, favoring to only print the path to the built .dll.

### To Reproduce

```
dotnet new classlib -o tst
cd tst
dotnet pack
```

### Actual output

```
Restore complete (0.3s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  tst succeeded (2.2s) → bin\Release\net9.0\tst.dll

Build succeeded in 2.9s

Workload updates are available. Run `dotnet workload list` for more information.
```

### Expected output

Since this was a `dotnet pack` command, I expect to see the path to the *package*.

```
Restore complete (0.3s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  tst succeeded (2.2s) → artifacts\Debug\packages\tst.1.0.0.nupkg

Build succeeded in 2.9s

Workload updates are available. Run `dotnet workload list` for more information.
```

### Further technical details
9.0.100-preview.7.24407.12

**Comment by baronfel** [comment]
This is a gap in terminal logger. We're tracking an issue in Ms. Build about generalizing. The quote output detection" mechanism that tasks can use. We could potentially try to special case pack here in the short term, but we were hoping to have something generalized before too much longer. 

@rainersigwald

**Comment by rainersigwald** [comment]
We should special-case it for 9 IMO

**Comment by marcpopMSFT** [comment]
looks like there's already a tracking issue in msbuild so closing here.
