### ISSUE TITLE
`dotnet build` support export warnings/errors to json

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#43269]
### Is your feature request related to a problem? Please describe.

When I want to do some refactoring on a legacy project, there're so many warnings, want to propose a feature that could export the build warnings/errors into a JSON so that we could analyze the warnings/errors easily and refactor according to the analyzed result

### Describe the solution you'd like

Maybe a `--format` parameter like other commands, outputs to the console by default and could output as JSON when needed

**Comment by WeihanLi** [comment]
@KalleOlaviNiemitalo thanks very much, it helps, while seemed there's only C# compile error, nuget audit warning not reported when I treat those warning as an error, but would get error when dotnet build, maybe it's better to support from dotnet build level

![image](https://github.com/user-attachments/assets/70da21b6-0697-4003-9bc7-7d36379b2f6d)

**Comment by baronfel** [comment]
@WeihanLi you can do this today by writing a custom MSBuild logger and passing it to MSBuild via the --logger parameter to any 'dotnet' build invocation. This same mechanism is how Terminal Logger, Binary Logger, and all other custom loggers work. Why don't you try prototyping that and seeing if it works for you? You'd basically just need to handle warnings and errors in your logger and emit them in whatever format you like.

**Comment by WeihanLi** [comment]
@baronfel thanks very much for the info, finding sample from docs, would have a try, thanks again for the help

https://learn.microsoft.com/en-us/visualstudio/msbuild/build-loggers?view=vs-2022

**Comment by baronfel** [comment]
I'm very interested in seeing how it works for you - if you make one could you link it here?

**Comment by WeihanLi** [comment]
@baronfel  a simple logger example, code source: https://github.com/WeihanLi/SamplesInPractice/blob/main/MSBuildLoggerSample/MSBuildJsonLogger/JsonLogger.cs

```csharp
using Microsoft.Build.Framework;
using System.Text.Encodings.Web;
using System.Text.Json;

namespace MSBuildJsonLogger;

public sealed class JsonErrorLogger : ILogger
{
    private const string ErrorLogFileName = "json-error-logger.json";
    private static readonly JsonSerializerOptions JsonSerializerOptions = new()
    {
        WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };
    
    private readonly List<BuildError> _errors = new();
    public void Initialize(IEventSource eventSource)
    {
        eventSource.ErrorRaised += EventSourceOnErrorRaised;
    }

    private void EventSourceOnErrorRaised(object sender, BuildErrorEventArgs e)
    {
        _errors.Add(new BuildError(e.Subcategory, e.Code, e.File, e.LineNumber, e.ColumnNumber, e.EndLineNumber, e.EndColumnNumber, e.Message, e.HelpKeyword, e.SenderName));
    }

    public void Shutdown()
    {
        using var fs = File.Create(ErrorLogFileName);
        JsonSerializer.Serialize(fs, _errors, JsonSerializerOptions);
        
        _errors.Clear();
    }

    public LoggerVerbosity Verbosity { get; set; }
    public string? Parameters { get; set; }
}


public sealed record BuildError(
    string Subcategory,
    string Code,
    string File,
    int LineNumber,
    int ColumnNumber,
    int EndLineNumber,
    int EndColumnNumber,
    string? Message,
    string? HelpKeyword,
    string? SenderName);
```

And when to use it, use the customized logger type and assembly

```sh
dotnet build -logger:"JsonErrorLogger,C:\projects\source\SamplesInPractice\MSBuildLoggerSample\MSBuildJsonLogger\bin\Debug\net8.0\MSBuildJsonLogger.dll"
```

output sample:

```json
[
  {
    "Subcategory": "",
    "Code": "CS0103",
    "File": "C:\\projects\\source\\SamplesInPractice\\SemanticKernelSamples\\GetStarted\\MemorySample.cs",
    "LineNumber": 29,
    "ColumnNumber": 9,
    "EndLineNumber": 0,
    "EndColumnNumber": 0,
    "Message": "The name 'memoryBuilder' does not exist in the current context",
    "HelpKeyword": null,
    "SenderName": "Csc"
  },
  {
    "Subcategory": "",
    "Code": "CS0103",
    "File": "C:\\projects\\source\\SamplesInPractice\\SemanticKernelSamples\\GetStarted\\MemorySample.cs",
    "LineNumber": 30,
    "ColumnNumber": 9,
    "EndLineNumber": 0,
    "EndColumnNumber": 0,
    "Message": "The name 'memoryBuilder' does not exist in the current context",
    "HelpKeyword": null,
    "SenderName": "Csc"
  },
  {
    "Subcategory": "",
    "Code": "CS0103",
    "File": "C:\\projects\\source\\SamplesInPractice\\SemanticKernelSamples\\GetStarted\\MemorySample.cs",
    "LineNumber": 34,
    "ColumnNumber": 22,
    "EndLineNumber": 0,
    "EndColumnNumber": 0,
    "Message": "The name 'memoryBuilder' does not exist in the current context",
    "HelpKeyword": null,
    "SenderName": "Csc"
  }
]
```

**Comment by WeihanLi** [comment]
@KalleOlaviNiemitalo not for this, for this scenario, I only focus on the logs when `dotnet build`

**Comment by baronfel** [comment]
FWIW if we do do something here for JSON output, it likely wouldn't be SARIF by default. SARIF is a specific kind of formatted JSON, so we'd likely do something simple like this for JSON, and have a dedicated format name for SARIF separate from JSON.
