### ISSUE TITLE
After installing .NET SDK 9.0 RC2, creating 6.0/8.0 Blazor WASM project requires September Servicing (we canceled the ship) feeds

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/sdk#43300]
**Testcases Affected**
[[8.0]IdentityWithBlazorWASMIndAuth](https://github.com/dotnet/AspNetCore-ManualTests/blob/release/8.0/AspNetCore80/IdentityWithBlazorWASMIndAuth.md)
[[6.0] IdentityWithBlazorWASMIndAuth](https://github.com/aspnet/AspNetCore-ManualTests/blob/release/6.0/AspNetCore60/IdentityWithBlazorWASMIndAuth.md)

Affected 8.0 Blazor Web App for WebAssembly app and 6.0 Blazor WebAssembly app

**Install Steps**

1. Clean machine: Win 11 x64 23h2 ENU
1. Install Dev17.12 Preview 3 [[main-35309.242](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10193216)], Preview channel

    -   Web workload + .NET Desktop workload
    -   Check 6.0 runtime under IC tab

1. Install .Net 9.0 RC2: https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.exe
1. Apply feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

**Repro Steps**

1. Create a Blazor Web App for WebAssembly via Terminal Emulator
` dotnet new blazor -int WebAssembly -o Blazortest -f net8.0`

**Note:**
1. This issue does not repro on Blazor web for server project.
1. This issue does not repro on 9.0 Blazor web for WebAssembly project.
1. This issue does not repro without install .NET 9.0 RC2 SDK.

**EXPECTED**
The project should be created successfully.

**ACTUAL**
![image](https://github.com/user-attachments/assets/78e37490-599e-41dc-ad24-1e8b5a225387)
For 6.0:
![image](https://github.com/user-attachments/assets/283fcc40-4867-4e61-ad14-41307b1b3b00)

**Error log**
```
Processing post-creation actions...
Restoring C:\Users\xxx\Blazortest\Blazortest.sln:
C:\Users\xxx\Blazortest\Blazortest.Client\Blazortest.Client.csproj : error NU1102:
  Unable to find package Microsoft.NETCore.App.Runtime.Mono.browser-wasm with version (= 8.0.9)
    - Found 1372 version(s) in dotnet9 [ Nearest version: 9.0.0-alpha.1.23423.2 ]
    - Found 95 version(s) in nuget.org [ Nearest version: 9.0.0-preview.1.24080.9 ]
    - Found 0 version(s) in Microsoft Visual Studio Offline Packages
C:\Users\xxx\Blazortest\Blazortest.Client\Blazortest.Client.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
C:\Users\xxx\Blazortest\Blazortest\Blazortest.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
Restore failed.
Post action failed.
Manual instructions: Run 'dotnet restore'
```
**Dotnet info**
```
.NET SDK:
 Version:           9.0.100-rc.2.24459.26
 Commit:            65dbcdbc51
 Workload version:  9.0.100-manifests.c199c07d
 MSBuild version:   17.12.0-preview-24456-02+2206a054f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24459.26\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.12.35309.242
   Manifest Version:    9.0.0-preview.4.24456.4/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\9.0.0-preview.4.24456.4\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-rc.2.24456.9
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24459.26 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24455.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24456.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24458.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by MackinnonBuck** [comment]
@lewing FYI

**Comment by lewing** [comment]
uh.. that is not the version it should be referencing... cc @marcpopMSFT

**Comment by lewing** [comment]
wait this is rc2, yeah rc2 will not work atm

**Comment by marcpopMSFT** [comment]
@lewing given that the versions in the error message aren't going to ship, should this get updated or were you waiting for the rc2 snap to do that? https://github.com/dotnet/runtime/blob/release/9.0/eng/Versions.props#L10

Basically, I would think that at snap time, the GA branch would still be 8.0.8 and the RC2 branch would be 8.0.10. 8.0.9 seems wrong since that won't ship.

**Comment by EmilyFeng97** [comment]
The versions in the error messages have been updated to unreleased 6.0.35 and 8.0.10, tracked by bug https://github.com/dotnet/sdk/issues/43465. Closed this issue now.
