### ISSUE TITLE
SDK 9.0 rc2 carries microsoft.net.sdk.aspire 9.0.0-preview4 which causes aspire workloads and templates to disappear.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/sdk#43301]
**REPRO STEPS**

1. With SDK 9.0 rc1 and Aspire 8.2.0 installed, everything worked fine.
![image](https://github.com/user-attachments/assets/5b9f5058-6cb2-4d9f-8b82-207aa2ee658e)
![image](https://github.com/user-attachments/assets/eb36eda5-db69-40d3-90a6-870b9f5e378d)
![image](https://github.com/user-attachments/assets/a3e404a8-27f3-4c91-8f60-1a9539dd7efd)
![image](https://github.com/user-attachments/assets/d72f4a3d-f78f-4740-9529-75b0cc1c979e)

2. Installing SDK 9.0 rc2 which carries microsoft.net.sdk.aspire 9.0.0-preview4 caused the aspire workload and templates to disappear, I had to apply the dotnet9 feed and run "dotnet workload update" to install aspire 9.0 P4.
![image](https://github.com/user-attachments/assets/35788fab-3460-4ef9-8788-6f9dce7aaeca)
![image](https://github.com/user-attachments/assets/46ae140f-75d9-4a91-b9d7-a0963bf86d57)
![image](https://github.com/user-attachments/assets/d3d41dd7-c75d-45bb-8346-3cb5f96ef73f)
![image](https://github.com/user-attachments/assets/d8ef1a00-499a-4849-a38e-036b7974ffb3)
![image](https://github.com/user-attachments/assets/31cc4fc0-c33b-4e90-b0e3-df022d4d7fc4)
![image](https://github.com/user-attachments/assets/d4374cc1-94d4-4d53-a6ca-b5081e226978)

**EXPECTED**
microsoft.net.sdk.aspire 9.0.0-preview4 needs to be unbundled from SDK 9.0 RC2.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/43321
