### ISSUE TITLE
Hope that the future can in Nuget package management page through the UI update Microsoft.Windows.SDK.NET.Ref package

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/sdk#43335]
### Description

Hope that the future can in Nuget package management page through the UI update Microsoft.Windows.SDK.NET.Ref package
希望未来能在 Nuget 包管理页面中通过 UI 更新 Microsoft.Windows.SDK.NET.Ref 包

After updating to CsWinRT 2.1.X, we found that the Microsoft.Windows.SDK.NET.Ref framework package will also be updated with the version of CsWinRT, however if we want to know the latest version of Microsoft.Windows.SDK.NET.Ref, we need to manually search and modify the <WindowsSdkPackageVersion>10.0.26100.45</WindowsSdkPackageVersion> property value, which is no longer very convenient. I hope that the .NET Team,CsWinRT team can communicate with the Visual Studio team, and you can add a separate display of the content of the framework package on the Nuget package management page, and you can follow the ordinary Nuget package to update it on the Nuget package management page
在更新到 CsWinRT 2.1.X 后，我们发现Microsoft.Windows.SDK.NET.Ref 框架包也会随着 CsWinRT 的版本进行更新，然而如果我们想了解 Microsoft.Windows.SDK.NET.Ref 的最新版本，需要手动搜索并修改 csproj 下的     <WindowsSdkPackageVersion>10.0.26100.45</WindowsSdkPackageVersion> 属性值，这已操作不太方便。希望 .NET 团队、 CsWinRT 团队能和 Visual Studio 团队能沟通一下，可以在 Nuget 包的管理页面添加一个单独显示框架包的内容，可以跟随普通的 Nuget 包在 Nuget 包管理页面进行更新

![{EBF3DAA8-6081-4C4A-BCC9-C563AB6A4468}](https://github.com/user-attachments/assets/e5ccc491-b35e-4b6c-880b-d25ad5fadd3e)
![{F171FB57-9F50-4924-8FE6-B8148E97BB46}](https://github.com/user-attachments/assets/fc7c74ee-0375-43ff-bb82-bbaabaf0ca70)
![{50741803-8602-4BB5-A92F-7CF40B256985}](https://github.com/user-attachments/assets/cb3a5336-cf8d-4b6c-8cb1-ece6c7098612)

### Reproduction Steps

See Description

### Expected behavior

Can add a separate display of the content of the framework package on the Nuget package management page, and you can follow the ordinary Nuget package to update it on the Nuget package management page
可以在 Nuget 包的管理页面添加一个单独显示框架包的内容，可以跟随普通的 Nuget 包在 Nuget 包管理页面进行更新

### Actual behavior

Manually search for the Microsoft.Windows.SDK.NET.Ref package and manually modify the <WindowsSdkPackageVersion>10.0.26100.45</WindowsSdkPackageVersion> property in csproj
手动搜索 Microsoft.Windows.SDK.NET.Ref 包，并在 csproj 中手动修改 <WindowsSdkPackageVersion>10.0.26100.45</WindowsSdkPackageVersion> 属性

### Regression?

None

### Known Workarounds

None

### Configuration

.NET 9 Preview 7
Windows 11 26100
X64
None

### Other information

None

**Comment by Gaoyifei1011** [comment]
> Thanks for creating this issue! We believe this issue is related to NuGet tooling, which is maintained by the NuGet team. Thus, we closed this one and encourage you to raise this issue in the [NuGet repository](https://github.com/NuGet/Home) instead. Don’t forget to check out [NuGet’s contributing guide](https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#before-submitting-an-issue) before submitting an issue!
> 
> If you believe this issue was closed out of error, please comment to let us know.
> 
> Happy Coding!

However, I don't think this issue should be closed, and the VS team, the CsWinRT team, and the .NET team should be contacted to deal with this tricky problem and work together to improve the developer experience
然而我认为这个问题不应该被关掉，应该联系 VS 团队，CsWinRT 团队，.NET 团队一块处理一下这个棘手的问题，共同优化一下开发者的体验

**Comment by huoyaoyuan** [comment]
This is not quite actionable. It's an expected corner case with specialized workaround. Building more support for this corner case will add very little value, with even more effort than regular case.
