### ISSUE TITLE
Can no longer compile any project after upgrading from .NET 9.0 Preview 7 to .NET 9.0 RC1

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [dotnet/sdk#43339]
The steps I took:

- Uninstall .NET 9.0 Preview 7
- Install .NET 9.0 RC1
- Upgrade Visual Studio 2022 to the latest version

Every project I try compiling I'm getting this error even though it's not referencing System.Text.Json, even transitively.

C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1060: Error reading assets file: Error loading lock file 'C:\[....]\obj\project.assets.json' : Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

I tried redownloading and reinstalling, repairing, deleted the NuGet package cache, manually deleted the bin and obj folders, rebooted the PC... basically everything I could think of

**Comment by Youssef1313** [comment]
We are encountering this in Uno Platform as well once we updated to RC1

**Comment by MarkCiliaVincenti** [comment]
What I find strange is the version number. Should it really be 8.0.0.4? The latest stable version is 8.0.4

**Comment by Youssef1313** [comment]
It shouldn't be specific to Uno Platform, just mentioning that we are also unable to upgrade to RC1 due to this issue

**Comment by Youssef1313** [comment]
This may be related to https://github.com/dotnet/sdk/pull/40645 ?

cc @Forgind

**Comment by MarkCiliaVincenti** [comment]
Quite likely, possibly this commit: https://github.com/dotnet/sdk/pull/40645/commits/337965f81944cd96597ba0c4ab8ebd92c7d5633f

In my SDK folder I have 8 files called System.Text.Json.dll

Four are file version 9.0.24.43107
Two are file version 8.0.724.31311 with a file size of 628 KB
Two are also file version 8.0.724.31311 but have a file size of 566 KB

None of them are 8.0.0.4

**Comment by MarkCiliaVincenti** [comment]
> I meet this problem too! to avoid this Exception, you can place a global.json to specify the version sdk 8.0.401

But then you wouldn't be able to compile .NET 9 projects, no?

**Comment by wanggangzero** [comment]
> > I meet this problem too! to avoid this Exception, you can place a global.json to specify the version sdk 8.0.401
> 
> But then you wouldn't be able to compile .NET 9 projects, no?

Yes! I think you can down grade it to preview7 first.

**Comment by Youssef1313** [comment]
Looks like it's a known issue: https://github.com/dotnet/core/pull/9489/files

**Comment by MarkCiliaVincenti** [comment]
I hoped this App.config would help but it really didn't. Maybe I am missing something.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" />
				<bindingRedirect oldVersion="8.0.0.4" newVersion="9.0.0.0" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>
```

**Comment by MarkCiliaVincenti** [comment]
I confirm that this is a Visual Studio issue. I was able to `dotnet pack` the same project that Visual Studio 2022 couldn't.

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti, which App.config file did you modify? It might need to be `devenv.exe.config` of Visual Studio but I'm not sure.

Interesting, but I'm not sure what I'm supposed to do here.

I tried this but it didn't work:

```
        <dependentAssembly>
          <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
          <bindingRedirect oldVersion="4.0.0.0-8.0.0.3" newVersion="8.0.0.3" />
          <codeBase version="8.0.0.3" href="PublicAssemblies\System.Text.Json.dll" />
        </dependentAssembly>
```

to:

```
        <dependentAssembly>
          <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
          <bindingRedirect oldVersion="4.0.0.0-8.0.0.4" newVersion="8.0.0.3" />
          <codeBase version="8.0.0.3" href="PublicAssemblies\System.Text.Json.dll" />
        </dependentAssembly>
```

**Comment by rainersigwald** [comment]
This is a [known issue with the combination of Visual Studio 17.11 and .NET SDK 9.0.100-rc.1](https://github.com/dotnet/core/blob/main/release-notes/9.0/known-issues.md#net-90100-rc1-will-fail-when-used-with-1711). It will be addressed in a future Visual Studio 17.11.x release.

Per the [.NET SDK support matrix](https://learn.microsoft.com/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules), you must use Visual Studio 17.12-preview to target .NET 9 from within Visual Studio. That’s the best way to get things working today.

To target .NET 8 or lower, there are a couple of workaround options while you wait for the fix (https://github.com/dotnet/msbuild/pull/10650) to be available:

1. Use a `global.json` to continue using the 8.0 SDK even when .NET 9.0.100-rc.1 is installed.
2. an ugly workaround I'll post in a minute after I double-check it.

**Comment by rainersigwald** [comment]
@leppie please file a separate issue, that doesn't sound like this one.

**Comment by leppie** [comment]
> @leppie please file a separate issue, that doesn't sound like this one.

Done #43356 

And funny enough, I just ran into THIS issue now (msbuild and net9.0) due to not having VS preview. Was working before.

**Comment by rainersigwald** [comment]
# Workaround

This workaround can be checked into any affected repo, but should be **removed** as soon as possible.

Add the following to a `Directory.Build.targets` or another file that's imported into every project in your repo:

```xml
  <!-- BEGIN workaround for https://github.com/dotnet/sdk/issues/43339; remove after updated to VS 17.12 or a future 17.11 patch -->
  <Target Name="WorkaroundDotnetSdk43339" BeforeTargets="ResolvePackageAssets" Condition=" '$(MSBuildRuntimeType)' == 'Full' and $([MSBuild]::VersionLessThan($(MSBuildVersion), 17.12.0))">
    <PrimeSystemTextJson804 />
  </Target>
  <UsingTask
    TaskName="PrimeSystemTextJson804"
    TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <Task>
      <Code Type="Fragment" Language="cs">
<![CDATA[
try
{
    System.Reflection.Assembly.LoadFrom(@"$(MicrosoftNETBuildTasksDirectoryRoot)\..\..\..\DotnetTools\dotnet-format\BuildHost-net472\System.Text.Json.dll");
}
catch
{
    // Best effort: if something moves in the SDK don't break the build.
}
]]>
      </Code>
    </Task>
  </UsingTask>
  <!-- END workaround for https://github.com/dotnet/sdk/issues/43339 -->
```

It's working for the MSBuild repo; see https://github.com/dotnet/msbuild/pull/10643.

**Comment by jeromelaban** [comment]
@rainersigwald this workaround is working for us as well! Thanks for the help!

**Comment by rainersigwald** [comment]
If all goes well, a VS-side fix will be released with release 17.11.4 (we just checked in to VS).

**Comment by Saplonily** [comment]
A possible workaround for those who don't want to add that targets file to every project is maybe replacing every `8.0.0.4` to `8.0.4` in `dotnet\sdk\9.0.100-rc.1.24452.12\DotnetTools\**`.

**Comment by Saplonily** [comment]
> I don't believe that will work - that directory contains tools like format, watch, etc., not the build logic that is causing the crash. I strongly encourage users to not go spelunking and modifying the SDK's installed layout.
yeah it won't, I got something wrong

**Comment by MarkCiliaVincenti** [comment]
There are 4 solutions:

- Build from the command line (dotnet build)
- Install Visual Studio 2022 Preview
- Apply the workaround described at https://github.com/dotnet/sdk/issues/43339#issuecomment-2344233994
- Wait for Visual Studio 2022 17.11.4 to be released

**Comment by mfeemster** [comment]
Can confirm. I was eager to try .NET 9 RC 1 but nothing will build in Visual Studio 2022 Community edition now.

**Comment by MarkCiliaVincenti** [comment]
Since Visual Studio 2022 v17.11.4 is out, this problem is fixed.

**Comment by skyslide22** [comment]
Still occours on azure using a .net8 web app which used msbuild .net9 for compiling on **AZURE**
Deleted obj & bin folders, global.json, env DOTNET_VERSION 8.0, nuget cache clearing - nothing helped.

### Solution
Deleting the dev slot on the azure portal and deploying on a brand new slot solved the issue.

_For the ones who might end up here having the same issue ^^_

**Comment by codethisio** [comment]
> Still occours on azure using a .net8 web app which used msbuild .net9 for compiling on **AZURE** Deleted obj & bin folders, global.json, env DOTNET_VERSION 8.0, nuget cache clearing - nothing helped.
> 
> ### Solution
> Deleting the dev slot on the azure portal and deploying on a brand new slot solved the issue.
> 
> _For the ones who might end up here having the same issue ^^_

Unfortunately, we still got the same error on a brand new slot. I'm hoping the Azure/.NET folks eventually get this sorted. We normally stay on LTS versions but wanted to observe the performance improvements of .NET 9 in a test environment.

**Comment by mdgibbons** [comment]
Also getting the same error on a .net6 MVC azure webapp.  Yesterday, I added some minor code and pushed it to my Devops repository which is linked via Pipeline to a staging slot on my Webapp (via Deployment Center section). This has all been working fine for many months but yesterday, it started failing.

```
C:\Program Files (x86)\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1060: Error reading assets file: 
Error loading lock file 'C:\home\site\repository\obj\project.assets.json' : 
Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. 
The system cannot find the file specified. [C:\home\site\repository\[MyApp].csproj]
    Done Building Project "C:\home\site\repository\[MyApp].csproj" (default targets) -- FAILED.
``` 

I was able to deploy directly from local to a brand new slot on azure like skyslide recommended

**Comment by skyslide22** [comment]
Either deploying directly from my machine or making a brand new slot with a *new different name than before* worked for me on azure

**Comment by vedantpatel1997** [comment]
@mdgibbons assuming this is a Windows Web App, the error message indicates that your application is using **SDK version 9.0.100**. You can specify an earlier SDK version for the web app manually. 

To do this, follow these steps:

1. Create a file named `global.json` and include the following content:
`{
    "sdk": {
        "version": "8.0.400"
    }
}`
2. Add this file to your web app's **site** folder.

By doing this, the Azure Web App will use the specified .NET SDK version (8.0.400).
This might help you resolved the issue.

**Comment by han-so1omon** [comment]
I am getting this same issue when deploying to an Azure Function App. We are upgrading from net6.0 to net8.0 with the isolated worker model. The function app is configured to use .NET 8 Isolated. `dotnet list package --outdated` shows no outdated packages. When I try to add `global.json` with `{ "sdk": { "version": "8.0.400" } }` at project root, I get an error stating `A compatible .NET SDK was not found.`

Anyone else with this issue in an Azure Function App?

**Comment by alkampfergit** [comment]
After I compiled the first project with .NET 9 in our build servers (Azure DevOps Pipeline) the code starts failing with that error. Using a global.json fixed everything that still uses .NET 8, but we are unable to compile anything that target .NET 9. Everything runs fine locally to all developers of the team. I've tried putting the workaround in the Directory.Build.targets, but it does not work. 



```
C:\fast\_work\_tool\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1060: Error reading assets file: Error loading lock file 'C:\fast\_work\517\s\src\Common\Jarvis.DocumentStore2.Host.FullFw\obj\project.assets.json' : Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. [C:\fast\_work\517\s\src\Common\Jarvis.DocumentStore2.Host.FullFw\Jarvis.DocumentStore2.Host.FullFw.csproj]
Unable to build solution Jarvis.DocumentStore2.Host.FullFw.cspro
```

**Comment by scottfavre** [comment]
Just updated to latest VS (v17.12.3) and am now seeing this error for any project targeting .NET 8:

```
error NETSDK1060: Error reading assets file: Error loading lock file 'C:\path\to\project\obj\project.assets.json' : Could not load file or assembly 'System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

**Comment by IS4Code** [comment]
Just in case someone finds it useful for whichever inconceivable use case, I had to change the workaround code because the one posted above did not work for me:
```cs
System.AppDomain.CurrentDomain.AssemblyResolve += delegate(object sender, ResolveEventArgs args) {
  if(args.Name != "System.Text.Json, Version=8.0.0.4, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51")
  {
    return null;
  }
  return System.Reflection.Assembly.LoadFrom(@"$(MicrosoftNETBuildTasksDirectoryRoot)\..\..\..\DotnetTools\dotnet-format\BuildHost-net472\System.Text.Json.dll");
};
```
A slightly more general solution that works even for .NET 10:
```cs
System.AppDomain.CurrentDomain.AssemblyResolve += delegate(object sender, ResolveEventArgs args) {
  var name = new System.Reflection.AssemblyName(args.Name);
  var path = @"C:\Program Files\dotnet\sdk\9.0.303\Sdks\Microsoft.NET.Sdk\tools\net472\" + name.Name + ".dll";
  if(!System.IO.File.Exists(path)) return null;
  return System.Reflection.Assembly.LoadFrom(path);
};
```
(The 9.0.303 SDK version is hardcoded because 10's assemblies did not work for some reason, complaining about <code>Void System.Text.Json.Utf8JsonReader..ctor(System.ReadOnlySpan`1<Byte>, Boolean, System.Text.Json.JsonReaderState)</code>. I did not investigate why.)
