### ISSUE TITLE
During the installation of .NET 9.0 RC2 SDK, some MAUI manifests still remain 9.0 Preview 6

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/sdk#43447]
### Describe the bug
During the installation of .NET 9.0 RC2 SDK, some MAUI manifests still remain in 9.0 Preview 6 

```
Microsoft.NET.Sdk.Androis.Manifest-9.0.100-preview.6(x64)
Microsoft.NET.Sdk.iOS.Manifest-9.0.100-preview.6(x64)
Microsoft.NET.Sdk.MacCatalyst.Manifest-9.0.100-preview.6(x64)
Microsoft.NET.Sdk.macOS.Manifest-9.0.100-preview.6(x64)
Microsoft.NET.Sdk.Maui.Manifest-9.0.100-preview.6(x64)
Microsoft.NET.Sdk.tvOS.Manifest-9.0.100-preview.6(x64)
```

### Reproduce Step
1. Clean machine: Win11 x64 23h2 ENU
1. Install .Net 9.0 RC2 SDK from [GitHub - dotnet/installer](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md), main (9.0.x Runtime)

### Actual Result
![maui](https://github.com/user-attachments/assets/9f400398-2560-457a-9a67-16643f0ee40a)

### Expected Result
All components should be updated to latest public releases version(**9.0 RC1**) that are currently on NuGet.org .

###  Further technical details
```
.NET SDK:
 Version:           9.0.100-rc.2.24463.42
 Commit:            ad6c88162f
 Workload version:  9.0.100-manifests.5da9a5d4
 MSBuild version:   17.12.0-preview-24463-04+8500d97af

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24463.42\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-rc.2.24462.10
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-rc.2.24463.42 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rc.2.24463.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24462.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24463.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by EmilyFeng97** [comment]
This issue still repro in the coherent build of .NET 9.0 RC2 SDK[9.0.100-rc.2.24474.11].

**Comment by balachir** [comment]
@marcpopMSFT will this be fixed for 9.0 GA? I don't see a milestone set for this issue, so I just want to double-check. Thanks!

**Comment by marcpopMSFT** [comment]
@balachir the maui baseline manifest will lag the release always. For 9.0.100, we can probably get @jonathanpeppers  to update the baselines to the RC2 versions. Then for 9.0.101, we'll update to the GA versions and leave them at that for the rest of 9.

**Comment by jonathanpeppers** [comment]
@marcpopMSFT I opened a PR for .NET 9 GA:
* https://github.com/dotnet/sdk/pull/44162

**Comment by v-elenafeng** [comment]
@EmilyFeng97 Could you please check if this issue has been fixed in 9.0.0?

**Comment by v-elenafeng** [comment]
Checked with the latest 9.0.100, the baselines has been updated to rc2. @EmilyFeng97 We can now close this as fixed.

**Comment by EmilyFeng97** [comment]
Close this issue as it is fixed
