### ISSUE TITLE
Web, Console and Library templates should agree if they get created inside a "src" directory or not

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#435]
The templates are inconsistent, the web template creates under a src directory, where as the Console/Library don't. We should be consistent across all of them.

**Comment by BillHiebert** [comment]
Yes. There has been discussion about removing the src directory from web projects for consistency.  There is an internal bug tracking this
@sayedihashimi

**Comment by srivatsn** [comment]
Closing this out then since the web template are being updated.
