### ISSUE TITLE
Props/Targets files from nuget are not imported during Pack execution when multiple frameworks are targetted

### ISSUE THREAD

**Issue by amaltinsky** [dotnet/sdk#43512]
.net SDK 8.0.400 on Win 10-x64.

I'm creating a packages custom MSBuild task following the guidance in [this tutorial](https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022).

This custom task includes custom props+targets files which are meant to be imported by the consuming project. On Build, this import works as expected. However, the custom props/targets files aren't being imported as part of the `Pack` execution when the `TargetFrameworks` (plural) are used as opposed to `TargetFramework` (singular).

I tracked this down to the way in which `dotnet restore` creates the `.csproj.nuget.g.props` file in `/obj`. 

With `TargetFrameworks` (plural) the import of custom targets looks like this:

```
<ImportGroup Condition=" '$(TargetFramework)' == 'net48' AND '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="$(NuGetPackageRoot)foo\0.1.4\build\foo.props" Condition="Exists('$(NuGetPackageRoot)foo\0.1.4\build\foo.props')" />
</ImportGroup>
```

The above condition is false when `TargetFrameworks` (plural) is specified since `Pack` doesn't set `TargetFramework` (singular) based on `TargetFrameworks` (plural) like Build does. So, `TargetFrameworks` (plural) is `net48`, but `TargetFramework` (singular) is empty.

If the consuming project uses `TargetFramework` (singular), then the import condition is different, and doesn't check the `TargetFramework`. In this case, the import works as expected and the custom props/targets are available:

```
<ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="$(NuGetPackageRoot)foo\0.1.4\build\foo.props" Condition="Exists('$(NuGetPackageRoot)foo\0.1.4\build\foo.props')" />
</ImportGroup>
```

**Comment by baronfel** [comment]
I believe this is by design. 

See this table for a reference: https://learn.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets#build-folders

In general, the props in the build/ directory of a package are imported for each individual TFM of a project. A project with multiple TFMs that needs to orchestrate at the outer level should use the buildMultitargeting/ folder for that scenario. 

There are many aspects of the build that drastically change when you go from a single TFM to multiple TFMs, this is just one aspect.

**Comment by amaltinsky** [comment]
@baronfel Looks like you're right. Packing the custom targets into `buildMultiTargeting` makes them available. Thanks for the quick response!
