### ISSUE TITLE
[NETSDKE2E]With 8.0.402 SDK zip installed, Warning: "Workload garbage collection failed with error: Workload version 8.0.402-baseline.24467.1 was not found.." happens when installing maui workload.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#43537]
Build:
8.0.402 SDK .zip on win11-x64

1.Set up clean machine with .NET SDK zip installation
2.In CLI, run dotnet workload install maui

Expected Result:
No error or warnings happen

Actual Result:
Warning: "Workload garbage collection failed with error: Workload version 8.0.400-baseline.24467.1 was not found.." displays
![image](https://github.com/user-attachments/assets/e845ba04-65f1-45e2-9b0c-be720c1ac7c8)

Note:
This issue not repro with exe install

dotnet --info:
.NET SDK:
 Version:           8.0.402
 Commit:            70aa751718
 Workload version:  8.0.400-manifests.f51a3a6b
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\sdk\8.0.402\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.402 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Users\v-danche\Downloads\dotnet-sdk-8.0.402-win-x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS
Build info:8.0.402(runtime-8.0.8)
![image](https://github.com/user-attachments/assets/7fddd67d-53d8-4364-bbe2-2a20e925b947)

**Comment by v-xiaofchen** [comment]
This issue also repro's on MAC OS
![image](https://github.com/user-attachments/assets/496f23cd-35ed-4369-a582-e779dd3a254f)

**Comment by ChenhuiYuan01** [comment]
This issue also repro's on Linux.
![image](https://github.com/user-attachments/assets/49d9dac7-b34a-472b-9e73-d3bf1346fd4b)

**Comment by vdanche** [comment]
This bug should have be fixed on previous 8.0.402(runtime:8.0.9), not today's 8.0.402(runtime:8.0.8), so we can close it
