### ISSUE TITLE
[NETSDKE2E][WIX]The installer UI could't pop out after double-clicking NET RC2 application in control panel if setting policy RemovePreviousVersion to a invalid value

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#43589]
OS: windows11-x64
Repro steps:
1.Install 9.0.100-rc.2.24469.13 SDK
2.setpolicy RemovePreviousVersion to a invalid value
`REG ADD HKLM\SOFTWARE\Microsoft\.NET /t REG_SZ /v RemovePreviousVersion /d next`
3.double-clicking NET RC2 application in control panel 

**Expected Result:**
The installer UI can pop out 
![image](https://github.com/user-attachments/assets/6cb9f79b-b376-441a-af14-0bd1d4ab5581)

**Actual Result**
The installer UI could't pop out 
![image](https://github.com/user-attachments/assets/eb80ec39-eac6-4c5e-b0b9-8a1e63560a5f)

**Comment by v-ainigao** [comment]
This issue also repro's on arm64OS.
![image](https://github.com/user-attachments/assets/fef4ea38-8e5e-45d8-b37d-3dc73e789216)

**Comment by joeloff** [comment]
This has been fixed for GA. Please verify once we have an official build to test
