### ISSUE TITLE
[dotnet-sdk-9.0.100-rc.2.24474.11] paint.netcore build with errors about elements from Microsoft.Windows.SDK.NET are not found

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/sdk#43707]
**Application Name**: paint.netcore
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-rc.2.24474.11
**App & Source Location checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2261861

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.300: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-rc.1.24452.12: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-rc.2.24470.13: Fail
4). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-rc.2.24474.11: Fail

**Description :**
When build the 3rd party application paint.net with the latest .NET 9 sdk, it failed with errors: 

```
CS0103  The name 'DispatcherQueueController' does not exist in the current context
CS0103  The name 'DispatcherQueue' does not exist in the current context
CS0103  The name 'DispatcherQueuePriority' does not exist in the current context
CS0103  The name 'DisplayInformationInterop' does not exist in the current context
CS0234  The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
CS0234  The type or namespace name 'System' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
CS0234  The type or namespace name 'Foundation' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
CS0246  The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
CS0246  The type or namespace name 'DispatcherQueue' could not be found (are you missing a using directive or an assembly reference?)
CS0246  The type or namespace name 'TypedEventHandler<,>' could not be found (are you missing a using directive or an assembly reference?)
CS0246  The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
CS1660  Cannot convert anonymous method to type 'TypedEventHandler<Graphics.Display.DisplayInformation, object>?' because it is not a delegate type

```

**Minimal Repro Steps: (Demo attached:[ConsoleDemo.zip](https://github.com/user-attachments/files/17145423/ConsoleDemo.3.zip))**
The machine has dotnet-sdk-9.0.100-rc.2.24474.11 installed.
1.Create a .NET 8 Console application.
2. Update the csproj file with following changes:

```
<PropertyGroup>
<OutputType>Exe</OutputType>
<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
<UseWPF>true</UseWPF>
<WindowsSdkPackageVersion>10.0.26100.1</WindowsSdkPackageVersion>
</PropertyGroup>

```
4. Add a AdvancedColorKind.cs file with following code:

```
using System;
using Windows.System;
using Windows.Foundation;
using Windows.Graphics.Display;
using Windows.Media.Miracast;
 
namespace ConsoleApp1
{
    using DisplayInformationWinRT = global::Windows.Graphics.Display.DisplayInformation;
    public class Test
    {
        private readonly DispatcherQueue dispatcherQueue;
        DispatcherQueuePriority dqp = DispatcherQueuePriority.Low;
        private static readonly ThreadLocal<DispatcherQueueController> perThreadController;
        public void TestMethod()
        {
            TypedEventHandler<DisplayInformationWinRT, object>? advancedColorInfoChangedHandler = null;
            advancedColorInfoChangedHandler =
                delegate (DisplayInformationWinRT displayInformation, object _)
                {  };
        }
    }

    internal enum AdvancedColorKind
    {
        HighDynamicRange = global::Windows.Graphics.Display.AdvancedColorKind.HighDynamicRange,
        StandardDynamicRange = global::Windows.Graphics.Display.AdvancedColorKind.StandardDynamicRange,
        WideColorGamut = global::Windows.Graphics.Display.AdvancedColorKind.WideColorGamut
    }
}

```
6. Open command prompt window and navigate to .sln file folder.
7. Run "dotnet new globaljson" and make sure the SDK version assigned in global.json file is 9.0.100-rc.2.24474.11.

```
{
  "sdk": {
"version": "9.0.100-rc.2.24474.11"
  }
}
```
9. Build the project.
 
**Expected Result:**
Build Successful.
 
**Actual Result:**
Build with following errors:   

Please refer to Binlog and Compiler log from [msbuild_binlog complog.zip](https://github.com/user-attachments/files/17146146/msbuild_binlog.complog.zip)

```
CS0246 

The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
CS0103 The name 'DispatcherQueuePriority' does not exist in the current context
CS0246 The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'DispatcherQueue' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'DispatcherQueuePriority' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
CS0246 The type or namespace name 'TypedEventHandler<,>' could not be found (are you missing a using directive or an assembly reference?)
CS0400 The type or namespace name 'Windows' could not be found in the global namespace (are you missing an assembly reference?)
CS0400 The type or namespace name 'Windows' could not be found in the global namespace (are you missing an assembly reference?)
CS0400 The type or namespace name 'Windows' could not be found in the global namespace (are you missing an assembly reference?)
CS0400 The type or namespace name 'Windows' could not be found in the global namespace (are you missing an assembly reference?)
CS1660 Cannot convert anonymous method to type 'TypedEventHandler<Windows.Graphics.Display.DisplayInformation, object>?' because it is not a delegate type

```
**Findings:**
We found all the namespaces/types in errors come from Microsoft.Windows.SDK.NET. When using dotnet-sdk-9.0.100-rc.2.24474.11 to build the app, the "Windows" namespace is not be recognized by compiler and the elements from "Windows" namespaces are also cannot be recognized.

**App Repro Steps on repro machine:(dotnet-sdk-9.0.100-rc.2.24474.11 installed)**

Please get the repro machine information from [DevDiv bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2261861):
1. Run command "```dotnet build```" in C:\Users\Test01\Desktop\paint.net\PaintDotNet. 

**Expected Result:**
Build successfully.

**Actual Result:**
Build failed with errors:

```
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The name 'DispatcherQueue' does not exist in the current context
The name 'DispatcherQueuePriority' does not exist in the current context
The name 'DisplayInformationInterop' does not exist in the current context
The name 'DispatcherQueueController' does not exist in the current context
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'System' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Foundation' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Graphics' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'System' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'System' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueue' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'TypedEventHandler<,>' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'TypedEventHandler<,>' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'DispatcherQueueController' could not be found (are you missing a using directive or an assembly reference?)
Cannot convert anonymous method to type 'TypedEventHandler<Graphics.Display.DisplayInformation, object>?' because it is not a delegate type

```
**Dotnet Info:**

```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.82e6a096
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  10.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Hi @jaredpar and @arkalyanms, this issue was also found during source compat testing, could you please take a look at it and confirm if this RC2 blocker? Thanks.

CC: @marcpopMSFT

**Comment by jaredpar** [comment]
This is similar to the other issue. Can you grab a compiler log for this too? 

Again though, this is very very unlikely to be a compiler bug. It's much more likely to be either a codegen bug in the generator or a bug in the SDK for including the generator. We should be getting the owner of that generator into the conversation so we can figure out what is happening here. 

@baronfel

**Comment by baronfel** [comment]
@merriemcgaw do you know anything about the source generators that are part of the Windows SDK, and/or who we could pull in to take a look here?

**Comment by baronfel** [comment]
and maybe @Sergio0694 knows if there's something we should be looking at

**Comment by Sergio0694** [comment]
Does that source explicitly have `<WindowsSdkPackageVersion>` set to an old version (ie. < .39) by any chance?

**Comment by baronfel** [comment]
@Sergio0694 the repro sample has `<WindowsSdkPackageVersion>10.0.26100.1</WindowsSdkPackageVersion>`.

**Comment by baronfel** [comment]
@Sergio0694 Did this requirement change between rc1 and rc2? Is there a breaking change notice to track the behavior different in .NET 8 and .NET 9? Basically how to we help users either not get broken or guide them through the upgrade.  This kind of hard-to-diagnose error is something we _really_ try to avoid in the SDK because it harms adoption of new versions.

**Comment by Sergio0694** [comment]
> "Did this requirement change between rc1 and rc2?"

Yeah, I merged https://github.com/dotnet/sdk/pull/41936 which added support for profiles. We needed this for UWP on .NET 9.

> "Is there a breaking change notice to track the behavior different in .NET 8 and .NET 9?"

I believe we might not have diagnostics in the specific scenario where you're not using UWP nor WinAppSDK. Worth noting though that manually setting that property is explicitly not recommended and only meant to be used in advanced scenarios by users wanting to test preview bits. If they explicitly set an old version and forget to update it, that's kinda on them. If you don't set that and just let the .NET SDK select the right package version for you, things will just work as expected. Not saying we can't or shouldn't potentially improve the diagnostics here, but worth pointing out that this is not the normal scenario.

cc. @manodasanW thoughts on this?

**Comment by jaredpar** [comment]
Is there a way to raise a diagnostic here? It seems reasonable, given this example, that customers will get into this problem. Can we proactively add a diagnostic here to warn them? Diagnostics are easy to attach to README, FAQ, etc ... compilation errors are not. 

Basically how do we give customers an easy path forward.

**Comment by baronfel** [comment]
I'm imagining something like a 'known minimum version bound' property in the Windows SDK or something that the targets could use to warn the user if they are using a version of the WindowsSdkPackageVersion that is not supported by the targets. Something as simple as that linking to documentation about how to properly set up your project can go a very long way towards helping users upgrade and reducing user frustration with cheese-moving.

**Comment by manodasanW** [comment]
I agree it would make sense to provide a warning where we detect that they are explicitly using an older version of the Windows SDK projection package with the .NET 9 SDK that is expecting a version that has profiles.  The check should have an opt-out in case they are intentionally doing it while trying to fix other dependencies.

**Comment by Redth** [comment]
In the case of .NET MAUI, _not_ setting the `WindowsSdkPackageVersion` is a problem for us if we are using newer .NET SDK versions which update the projections here but an older version of WindowsAppSDK.

We observed a similar issue with .NET 9 RC2 builds where MAUI apps started failing building with a 1.5 version of WindowsAppSDK suggesting setting an explicit `WindowsSdkPackageVersion` to fix the issue.  This does seem to 'work around' the issue for us, but implies that having no explicit version set isn't always 'safe'.

Our choices seem to be explicitly setting `WindowsSdkPackageVersion` (and risking incompatibilities the longer we leave that set), or upgrading to WindowsAppSDK 1.6 which we are still in the process of validating against and carries its own set of risks.

**Comment by Junjun-zhao** [comment]
Thanks all for helping look into this issue.

After setting ```WindowsSdkPackageVersion``` to the latest version ```10.0.26100.45```，the errors mentioned in this bug are all gone. 

But a new issue occurs during build with error "```Missing partial modifier on declaration of type 'AffineTransform2DEffect3'; another partial declaration of this type exists```,  possibly codegen issue in the generator same as https://github.com/dotnet/sdk/issues/43680.  We filed a new issue https://github.com/dotnet/sdk/issues/43746.  Could you please also take look at that one? Thanks.

**Comment by baronfel** [comment]
cc @Sergio0694 and @manodasanW here as well

**Comment by PriyaPurkayastha** [comment]
We have repro machines available. My team(Junjun) is based in China and it is already weekend there, so it might be better to look at the repro machines to further investigate. Repro machine details are in the DevDiv bug(https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2261861) and VPN is needed to connect to the VMs.

**Comment by Junjun-zhao** [comment]
> @Junjun-zhao That one seems a valid error with two declarations, one in source code and one in the generated from the SDK. Is it not a test setup issue?

It is not a test setup issue,@jaredpar and @manodasanW have investigated and https://github.com/dotnet/sdk/issues/43746 is an issue with the WinRT source generator https://github.com/microsoft/CsWinRT/issues/1799

**Comment by Junjun-zhao** [comment]
@jaredpar Any decision solution made for this issue? As we are going to sign off RC validation, could you help confirm if it is a RC2 blocker?

**Comment by PriyaPurkayastha** [comment]
@Junjun-zhao Jared's team doesn't own these fixes. There are discussions going on about these fixes and associated timelines in Teams. Richa and others are aware of these issues. We need to wait for decision/update. I will let you know once an update is available in the RC2 Teams chat.

**Comment by Junjun-zhao** [comment]
@manodasanW  We verified this issue with the latest build dotnet-sdk-9.0.100-rtm.24515.15, it has been fixed. Thanks.
