### ISSUE TITLE
Typo in german installer

### ISSUE THREAD

**Issue by Suchiman** [dotnet/sdk#43725]
In this commit https://github.com/dotnet/sdk/commit/e1a2d1ce9a76371ed3c4c5875bceff2bca1bc05a#diff-0bd1ae3beef5353d824fe0e0d201114468dac62c633f1213ae1936df72259cce
![image](https://github.com/user-attachments/assets/6fa47708-62ce-4020-9519-b79d9123ae85)
`"Installieren"` was accidentally changed to `„Installieren2` so someone forgot to press the shift key while hitting `2`.

**Comment by baronfel** [comment]
I've raised [an internal localization bug](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/1001774) to track this since we cannot take external localization changes per [our docs](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/Localization.md).
