### ISSUE TITLE
[NETSDKE2E] With 9.0.100-rtm SDK installed, Warning: "Workload garbage collection failed with error: Workload version 9.0.100-rtm.24477.19 was not found.." happens when installing maui workload. 

### ISSUE THREAD

**Issue by ChenhuiYuan01** [dotnet/sdk#43777]
Build:
9.0.100-rtm SDK .zip on win11-x64

1.Set up clean machine with .NET SDK zip installation
2.In CLI, run dotnet workload install maui

Expected Result:
No error or warnings happen

Actual Result:
Warning: "Workload garbage collection failed with error: Workload version 9.0.100-rtm.24477.19 was not found.." displays  
![image](https://github.com/user-attachments/assets/2a7fa113-b47f-432d-b527-8b58adf054c1)

Note:
This issue not repro with exe install

dotnet --info:
.NET SDK:
 Version:           9.0.100-rtm.24477.19
 Commit:            34aa341135
 Workload version:  9.0.100-manifests.cf9c1ca4
 MSBuild version:   17.12.0+95c7bf011

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\dotnet-sdk-9.0.100-rtm.24477.19-win-x64\sdk\9.0.100-rtm.24477.19\

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rtm.24475.3
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-rtm.24477.19 [C:\dotnet-sdk-9.0.100-rtm.24477.19-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rtm.24476.2 [C:\dotnet-sdk-9.0.100-rtm.24477.19-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rtm.24475.3 [C:\dotnet-sdk-9.0.100-rtm.24477.19-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rtm.24476.4 [C:\dotnet-sdk-9.0.100-rtm.24477.19-win-x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by ChenhuiYuan01** [comment]
This issue also reproduces on Linux.
![image](https://github.com/user-attachments/assets/d8a5b802-05c1-44eb-9418-5f7561416d29)

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.
build info:9.0.100-rtm.24478.4(runtime- 9.0.0-rtm.24476.4)
![image](https://github.com/user-attachments/assets/e0050d95-3d31-4f07-91ad-b79bbd2eb856)

**Comment by v-xiaofchen** [comment]
This issue also reproduces on Mac.
![image](https://github.com/user-attachments/assets/62a07c77-de4c-4691-9104-f68923dc36a5)

**Comment by marcpopMSFT** [comment]
@dsplaisted to take a look. This might be from the -rtm branding and fixed by your PR.

**Comment by dsplaisted** [comment]
Yes, this should be fixed by #43737

**Comment by ChenhuiYuan01** [comment]
This issue does not repro on 9.0.100-rtm.24508.40 (runtime-9.0.0-rtm.24503.8).
![Image](https://github.com/user-attachments/assets/254e599d-cb6e-4860-8adf-decdbdebd567)
