### ISSUE TITLE
When trying to install dotnet-ef tool, we get error saying that dotnet-ef is not a .NET tool

### ISSUE THREAD

**Issue by balachir** [dotnet/sdk#43844]
### Describe the bug
Unable to install dotnet-ef tool using 'dotnet tool install'. We get error saying that dotnet-ef is not a .NET tool

![image](https://github.com/user-attachments/assets/bbeb59a9-4010-4968-9a97-4b30cfcac74c)

### To Reproduce

INSTALL STEPS
1. Clean Win11 machine
1. Install VS 17.12 P3 (Web workload includes 9.0 SDK and check 8.0, uncheck 6.0 runtime, latest from main
	- Includes SDK 9.0.100-rc.2.24474.11 (with runtime 9.0.0-rc.2.24473.5) and runtimes 8.0.10
	-  Apply feeds for 9.0 rc2 and 8.0.10

REPRO STEPS
1. Open Command Prompt, and try to install dotnet-ef tool

ACTUAL
We get the error saying that dotnet-ef is not a tool

EXPECTED
The dotnet-ef tool should be installed.

### Further technical details
- Include the output of `dotnet --info`

![image](https://github.com/user-attachments/assets/a92643a8-dd9e-4804-9e66-aa0896448f5f)

**Comment by balachir** [comment]
@marcpopMSFT is this a known issue with 9.0 rc2 SDK? Am I missing something?

@richaverma1

**Comment by marcpopMSFT** [comment]
This is new functionality in RC2 that is not included in GA and no plans to add because of a separate issue we found in the code wrt other feed technologies: https://github.com/dotnet/sdk/issues/43651

This particular issue is unknown though. is dotnet-ef not correctly marked as a tool somehow? CC @joeloff who is going to be doing this for 9.0.2xx and @baronfel for visibility.

Do we need to relnote this?

**Comment by joeloff** [comment]
We should relnote this. I checked the nuspec and it definitely has the correct package type - most of the original change was around local tools and I wonder whether this is because the tool is being installed globally.

**Comment by balachir** [comment]
I can reproduce it when installing the tool locally too, so I don't think it's only due to the global install. Is there a workaround for this?

**Comment by joeloff** [comment]
Undoing the change in #43872

**Comment by joeloff** [comment]
Merged for 9.0 GA, closing

**Comment by gdhuper** [comment]
I am still running into this error. Here is my environment info:

```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.4872d5d5
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.135 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.427 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.317 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]
```

Do I need to install a specific version of dotnet runtime to resolve this?

**Comment by martincostello** [comment]
You need to wait for the stable .NET 9 release next month.

**Comment by gdhuper** [comment]
> You need to wait for the stable .NET 9 release next month.

Is there a workaround in the meantime?

**Comment by v-elenafeng** [comment]
Checked with 17.12.0 VAL (contains 9.0.0), this is fixed.
