### ISSUE TITLE
Improve preview handling for `dotnet workload search version`

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#43890]
Currently, when searching for workload sets, the SDK will include preview versions if the .NET SDK itself is branded as preview:

https://github.com/dotnet/sdk/blob/54abeefe0422dd45d3a0e6697c38563bfe66c526/src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommand.cs#L79

Probably there should be a command-line parameter that controls this (ie `--include-previews`).

Additionally, checking `_sdkVersion.Prerelease` may not be the best option for the default behavior. A better option may be to base it on whether the SDK Feature band is a prerelease band.  That way the behavior of stabilized and non-stabilized RTM-branded SDKs would be the same, where today it isn't.

Finally, currently if you run `dotnet workload search version --include-previews`, you get an `IndexOutOfRangeException`, instead of an error that `--include-previews` is unrecognized.

**Comment by Forgind** [comment]
I can add support for --include-previews. (I think we'd originally discussed it as 'if people ask, we can add it' rather than building it in by default, but I think it's a pretty reasonable ask.) Why is having a non-stabilized RTM-branded SDK acting like a stable SDK a good thing?
