### ISSUE TITLE
Expand platform/architecture coverage for tests running in PR builds

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/sdk#43916]
The SDK tests currently only run in x64 macOS, Ubuntu, and Windows. This means we are missing coverage for things like arm64.

With SDK being the place where many various features come together as part of build/publish, this seems like the natural place for cross-feature integration tests. Ideally, we'd have more platform coverage for such tests.

At least adding osx-arm64 would be a solid improvement. Per @marcpopMSFT, osx-arm64 usage is already significantly higher than osx-x64.

**Comment by marcpopMSFT** [comment]
I don't know how well the existing tests will run in this config so lets target 9.0.2xx rather than 1xx in case a lot of changes are needed. It'll still get us coverage of net9 after Feb so that should be sufficient.

**Comment by MiYanni** [comment]
The current PR jobs are defined here, split up between Windows, macOS, and Linux.
https://github.com/dotnet/sdk/blob/5b943e320b9a3e2952e060d66607c63e9d41c4a5/eng/pipelines/templates/jobs/sdk-job-matrix.yml#L5-L81

If you'd want to add another, it takes some domain knowledge to figure it out. As it stands, we "bind" the build agent and test Helix test agent together:
https://github.com/dotnet/sdk/blob/5b943e320b9a3e2952e060d66607c63e9d41c4a5/eng/pipelines/templates/jobs/sdk-job-matrix.yml#L5-L81

To do different testing platform, we also use containers on Linux. I think the list of containers comes from here:
https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json

In the job definitions, the `helixTargetContainer` sets the test container to run Helix tests. I forget who manages the container stuff off the top of my head. But if you could provide which containers seem to fit your need, then I can add the jobs and give them a try.
