### ISSUE TITLE
Error: The type or namespace name 'HttpClient' could not be found in projects using net472 when net8 is installed.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/sdk#43932]
using vs 2022 , in a project reference net472 and net6 while net6 sdk only  is installed in machine, it  is compiled fine.
When installing net8 (8.0.400) i get many compilation errors in projects in net472 and using HttpClient, some of them::
```
Error (active)	CS0246	The type or namespace name 'HttpRequestMessage' could not be found 
CS0246	The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)
```

My workaround solution to resolve the issue is adding `global.json` in solution folder to use net6 like:
```
{
  "sdk": {
    "version": "6.0.425",
    "rollForward": "latestFeature"
  }
}

```

Is there a breaking change in net8 w.r.t. HttpClient using net472?
What is the official way to resolve this issue and continue using net8?

**Comment by moh-hassan** [comment]
Thanks @KalleOlaviNiemitalo  for the quick reply.
Yes, the Implicit using for System.Net.Http is no longer added since ```net8 preview 6``` and it was the cause of the issue.
I did the Recommended action by adding to the global file: 
```
//add to the global using in the project
global using System.Net.Http;

```
>Recommended action
>Add a [global using directive](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using->directive#global-modifier) to one of your source files.
>Add a using directive to each source code file that uses APIs from System.Net.Http.

Now,  I can use net8 with net472 projects and dropped the global.json.

**Comment by MiYanni** [comment]
@moh-hassan Is there anything else that needs to be addressed here or was @KalleOlaviNiemitalo able to help resolve your issue?

**Comment by moh-hassan** [comment]
Thanks @MiYanni 

@KalleOlaviNiemitalo  helped me to fix the issue.
you can close it.
