### ISSUE TITLE
Installation Failure: ".NET SDK 8.0.403" on Windows 11 with Error "This app can't run on your PC"

### ISSUE THREAD

**Issue by Rachiid007** [dotnet/sdk#43994]
### Describe the bug
When attempting to install the .NET SDK 8.0.403 on a Windows 11 64-bit, the installer fails with the error message "**This app can't run on your PC**".

### To Reproduce

1. Download the dotnet-sdk-8.0.403-win-x64.exe from the official [.NET website](https://dotnet.microsoft.com/en-us/download/dotnet/8.0).
2. Run the installer on a Windows machine with a 64-bit architecture.
3. Observe the error message: "This app can't run on your PC".

### Further technical details
- Output of dotnet --info: Unable to run because the SDK fails to install.
- System:
  - OS Name: Microsoft Windows 11 Pro
  - OS Version: 10.0.22631 N/A Build 22631
  - System Type: x64-based PC

**Comment by Rachiid007** [comment]
I used winget as instructed in the [official documentation](https://learn.microsoft.com/en-us/dotnet/core/install/windows?WT.mc_id=dotnet-35129-website#install-the-sdk), and **it successfully installed the .NET SDK**. However, it installed version 8.0.402 instead of 8.0.403.

**Comment by bart-vmware** [comment]
I'm experiencing the same issue. Install fails because the downloaded file is 0 bytes. Download link used: https://download.visualstudio.microsoft.com/download/pr/6224f00f-08da-4e7f-85b1-00d42c2bb3d3/b775de636b91e023574a0bbc291f705a/dotnet-sdk-8.0.403-win-x64.exe

**Comment by AnnaJagtmanBL** [comment]
Same error message here: "This app can't run on your PC". 
Trying to install dotnet-sdk-8.0.403-win-x64.exe on Windows 11.
Download link: https://download.visualstudio.microsoft.com/download/pr/6224f00f-08da-4e7f-85b1-00d42c2bb3d3/b775de636b91e023574a0bbc291f705a/dotnet-sdk-8.0.403-win-x64.exe

**Comment by Rachiid007** [comment]
> I'm experiencing the same issue. Install fails because the downloaded file is 0 bytes. Download link used: https://download.visualstudio.microsoft.com/download/pr/6224f00f-08da-4e7f-85b1-00d42c2bb3d3/b775de636b91e023574a0bbc291f705a/dotnet-sdk-8.0.403-win-x64.exe

Oh, I see.
The file I downloaded was 256 KB

**Comment by bart-vmware** [comment]
The download link works for me now.

**Comment by AnnaJagtmanBL** [comment]
Indeed: the link that did not work yesterday is working today. Nice. :-)

**Comment by Syzuna** [comment]
The download link is still broken for me.
I still get a 0 Byte file

**Comment by Bram1903** [comment]
I just encountered the same issue when trying to install .NET 9, where the download kept resulting in a 0KB file. However, after refreshing and trying a few more times, it eventually started downloading the installer correctly.

**Comment by tort32** [comment]
Can't download it by Firefox, file is 0 bytes. But Edge can ... smh
Also possible to install by winget: `winget install --id=Microsoft.DotNet.SDK.8 -e`

**Comment by marcpopMSFT** [comment]
@rbhanda @leecow is there an issue with our downloads?

**Comment by camillewoodthorpe** [comment]
Using Microsoft Edge it kept downloading 0kb files. It worked when downloading them using Chrome.

**Comment by endrelovas** [comment]
Curl: no success. Wget: no success. Firefox: no success. Edge: no success.
All downloads are 0 bytes or 250k.

**Comment by marcpopMSFT** [comment]
This was identified as an issue with the CDN for the download center. My understanding is that they pulled that particular CDN out of rotation and notified the owners as of earlier today so the issue should now be resolved. Please let us know if it's not.

**Comment by glektarssza** [comment]
Looks like it's happening again.

```
 > scoop install dotnet-sdk-lts
WARN  Purging previous failed installation of dotnet-sdk-lts.
ERROR 'dotnet-sdk-lts' isn't installed correctly.
Removing older version (8.0.410).
'dotnet-sdk-lts' was uninstalled.
Installing 'dotnet-sdk-lts' (8.0.410) [64bit] from 'versions' bucket
dotnet-sdk-8.0.410-win-x64.zip (271.7 MB) [===========================>                                                                                                                                                                           ]  14%
The response ended prematurely, with at least 242985017 additional bytes expected. (ResponseEnded)
URL https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.410/dotnet-sdk-8.0.410-win-x64.zip is not valid
```
