### ISSUE TITLE
[NETSDKE2E]After installing NET 9 RTM SDK and downloading wasm-tools, uninstalling the SDK does not completely clear the contents under the dotnet directory.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#44052]
Build info:
9.0.100-rtm.24509.30(runtime-9.0.0-rtm.24503.8)

Repro steps:
1.Download the NET9 RTM SDK.
2.Install workload with commands.
`dotnet workload install wasm-tools --skip-manifest-update `
3.Uninstall the SDK

Expected:
The SDK has been uninstalled and everything under dotnet is cleaned up. 

Actual Result:
Uninstalling the SDK does not completely clear the contents under the dotnet directory.
![Image](https://github.com/user-attachments/assets/5600aa0b-90b8-4dbf-b885-8daa22bd24ad)
![Image](https://github.com/user-attachments/assets/55b018ad-dfe8-4027-837d-e6ef3dee2a3d)

dotnet --info
.NET SDK:
 Version:           9.0.100-rtm.24509.30
 Commit:            2d0b3f7934
 Workload version:  9.0.100-manifests.c5c38474
 MSBuild version:   17.12.3+4ae11fa8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rtm.24509.30\

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0-rtm.24503.8/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.current\9.0.0-rtm.24503.8\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rtm.24503.8
  Architecture: x64
  Commit:       3429fee9ed

.NET SDKs installed:
  9.0.100-rtm.24509.30 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rtm.24508.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rtm.24503.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rtm.24508.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64 OS.

**Comment by vdanche** [comment]
Not repro on yesterday's build:9.0.100-rtm.24508.33 (runtime-9.0.0-rtm.24503.8

**Comment by marcpopMSFT** [comment]
It didn't repro yesterday but repros today? I'm not sure what would have gone in to impact this. This is the finalizer but could also be related to garbage collection and feature bands so @dsplaisted and @joeloff

**Comment by dsplaisted** [comment]
If this repros again, there are some log files that would be useful for investigation.  They are in the %TEMP% directory and the filenames start with Microsoft.NET.Workload.

**Comment by v-ainigao** [comment]
> If this repros again, there are some log files that would be useful for investigation. They are in the %TEMP% directory and the filenames start with Microsoft.NET.Workload.

This issue also repro's on .net9.0.100-rtm.24515.15(runtime-9.0.0-rtm.24511.16)SDK.
The log files I found are as follows and it has about 149 items
![Image](https://github.com/user-attachments/assets/93365ad7-b26b-4044-b586-d3bc54aeff6c)
![Image](https://github.com/user-attachments/assets/ada2be16-1e53-4539-9e2c-03f379497406)
![Image](https://github.com/user-attachments/assets/1d8577b7-3ad6-4cae-9919-fa05fa2e2c5e)
![Image](https://github.com/user-attachments/assets/30926f3b-6786-4179-8da3-7b820fdf7044)

**Comment by v-ainigao** [comment]
This issue also repro's on .net9.0.100SDK
![Image](https://github.com/user-attachments/assets/4cdfcec7-7daf-4df8-a894-2dec1050c690)
