### ISSUE TITLE
Offline dotnet new console

### ISSUE THREAD

**Issue by hmrguez** [dotnet/sdk#44122]
From .NET 8.0 forward the new console template now requires dotnet restore because there are new nuggets in the template. This makes it inconvenient for computing at the edge for testing some features and overall starting with the language in low internet access areas.

Can you regress back to what it used to be or offer some kind of feature for those required nuggets to be included in the .net sdk and the console project wouldn't need the dotnet restore command upon creation?

**Comment by baronfel** [comment]
@hmrguez can you give an example? the template itself has no PackageReferences in it at all: https://github.com/dotnet/sdk/blob/release/8.0.1xx/template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj

**Comment by hmrguez** [comment]
@baronfel Don't worry about it, my mistake. This issue was already solved in older versions of .NET 8. Sorry to bother you, thank you for your time
