### ISSUE TITLE
After installing .NET SDK 9.0 GA creating 8.0/6.0 project requires November Servicing (8.0.11/6.0.36) feeds.

### ISSUE THREAD

**Issue by JoelleMarcChua** [dotnet/sdk#44142]
**Install Steps**

1. Clean machine: Win 11 x64 24h2 ENU
2. Install Dev17.13 Preview 1 [main-35413.36](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10381524&view=results), Preview channel
3. Install .NET 9.0 GA: [https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.exe](https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.exe)
4. Apply feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

**Repro Steps**

1. Create a Console App > Build

**EXPECTED**
The project should be built successfully without error.

**ACTUAL**
The project requires November Servicing feeds.
![Image](https://github.com/user-attachments/assets/83b162a0-7269-4aa2-a10c-70784424a89c)

**Error Log**

Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 8.0.11)
  - Found 596 version(s) in dotnet9 [ Nearest version: 9.0.0-alpha.1.23418.2 ]
  - Found 123 version(s) in nuget.org [ Nearest version: 9.0.0-preview.1.24081.3 ]
  - Found 1 version(s) in dotnet8 [ Nearest version: 8.0.10 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Dotnet info**

.NET SDK:
 Version:           9.0.100-rtm.24512.1
 Commit:            5b9d9d4677
 Workload version:  9.0.100-manifests.87287131
 MSBuild version:   17.12.3+4ae11fa8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rtm.24512.1\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.13.35413.36
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.1\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rtm.24510.3
  Architecture: x64
  Commit:       226c0347b9

.NET SDKs installed:
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]
  9.0.100-rtm.24512.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rtm.24511.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rtm.24510.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rtm.24511.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by marcpopMSFT** [comment]
This is expected. We have to switch to the final versions before we ship and that has now been done: https://github.com/dotnet/sdk/pull/43523

I guess I could have waited until the last minute to allow for more dogfooding of daily builds but that adds risk to the schedule.
