### ISSUE TITLE
The framework [.../onnxruntime.framework] is a framework of static libraries, and will not be copied to the app

### ISSUE THREAD

**Issue by fdevillard** [dotnet/sdk#44161]
### Describe the bug
I've created a toy MAUI project and everything build and run well until I add and use the following dependencies:
```
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.19.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.19.2" />
```

Whenever I try to use a resource from the dependency, the app crashes (exception below).

The build generates the following warning that I assume is directly related:
```
warning MT7091: The framework obj/Debug/net8.0-ios/iossimulator-arm64/onnxruntime.xcframework.zip/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework is a framework of static libraries, and will not be copied to the app.
```

I don't understand why, and I'm running out of ideas to fix this.

Thank you in advance for any help 🙌

(Note: this was first briefly mentioned here https://github.com/dotnet/sdk/issues/36527)

### To Reproduce
I've created repo with the code: https://github.com/fdevillard/maui-onnx-crash

To reproduce:
- run the app
- click/press the "click me" button

Expected: "model loaded" is rendered in the button, showing the it has indeed been loaded

Behavior: the app crashes.

### Exceptions
```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

 ---> System.DllNotFoundException: __Internal
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()
   --- End of inner exception stack trace ---

   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
```

### Further technical details
- Include the output of `dotnet --info`: `8.0.403`
- The IDE: VSCode `1.94.2`
- macOS: 14.7
- iPhone simulator: version 16, iOS 18

**Comment by nagilson** [comment]
Not sure if this should be directed towards Maui or the Runtime team, but probably Maui?

**Comment by marcpopMSFT** [comment]
@Redth @jonathanpeppers should this go to the Maui team and which repo should we route it to? That MT error code I think is from the simulator, right?

**Comment by jonathanpeppers** [comment]
Do we have a way to move this to https://github.com/xamarin/xamarin-macios?

**Comment by nagilson** [comment]
You cant unless you use some sort of bot to duplicate the issue.

**Comment by jonathanpeppers** [comment]
Maybe @dalexsoto @rolfbjarne have a github issue mover tool to move it?

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21450

**Comment by rafaelparenza** [comment]
**Solution add in csproj :**

```xml
<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
	<PropertyGroup>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
	</PropertyGroup>
	<ItemGroup>
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="/usr/lib/swift" />
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
		<_CustomLinkFlags Include="-Wl,-rpath" />
		<_CustomLinkFlags Include="-Wl,/usr/lib/swift" />
	</ItemGroup>
</Target> 

<PropertyGroup Condition="'$(TargetFramework)'=='net8.0-ios'">
	<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	<MtouchEnableBitcode>false</MtouchEnableBitcode>
	<MtouchExtraArgs>--optimize=-remove-dynamic-registrar --gcc_flags="-lswiftCore -lswiftCompatibility50 -lswiftCompatibility51 -lswiftCompatibility56 -lswiftCompatibilityDynamicReplacements -lswiftCompatibilityConcurrency -ObjC -lc++"</MtouchExtraArgs>
	<_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>

	<CodesignKey>YourCode</CodesignKey>
	<CodesignProvision>Yourcode</CodesignProvision>
</PropertyGroup>
```
