### ISSUE TITLE
[WebToolsE2E] Install .NET SDK 9.0 RC2 +.NET SDK 9.0 RTM, the templates version is not replaced by higher versions.

### ISSUE THREAD

**Issue by Yangfanyue** [dotnet/sdk#44180]
**Repro steps**

1. Download and install .NET SDK 9.0 RC2
2. Download and install .NET SDK 9.0 RTM

**Note**
1. The SDK version and Runtime version are replaced by higher versions.

**Actual result**
The templates version is not replaced by higher versions.
![Image](https://github.com/user-attachments/assets/2a1cfd8a-7224-44f6-85c9-f6442247433b)

**Expected result**
![Image](https://github.com/user-attachments/assets/b08c4e4e-950a-49cc-ba81-f4fb55b47527)

**Comment by balachir** [comment]
@Yangfanyue can you look into the rc.2 and rtm folders and share whether there are particular templates that are not getting updated? Please share the screenshots of the contents of the folders in your 'Actual result'. 

cc: @richaverma1 @joeloff

**Comment by Yangfanyue** [comment]
@balachir Today I verified it using 9.0 RC2 + 9.0 GA. This issue doesn't repro. So I closed it.
