### ISSUE TITLE
ProjectDesignTimeAssemblyResolutionSearchPaths does not match AssemblySearchPaths and DesignTimeAssemblySearchPaths

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#443]
These should match to have consistent behavior between design-time and build time.

ProjectDesignTimeAssemblyResolutionSearchPaths is used for "project design-time assembly resolution (DTAR)", basically anytime a component calls through IVsDesignTimeAssemblyResolution.ResolveAssemblyPathInTargetFx.

```
1>ProjectDesignTimeAssemblyResolutionSearchPaths = 
1>      {CandidateAssemblyFiles};
1>      ;
1>      {HintPathFromItem};
1>      {TargetFrameworkDirectory};
1>      {Registry:Software\Microsoft\.NETCoreApp,v1.0,AssemblyFoldersEx};
1>      {RawFileName};
1>      c:\users\davkean\documents\visual studio 2017\Projects\ConsoleApp35\ConsoleApp35\bin\Debug\netcoreapp1.0\
```

```
1>AssemblySearchPaths            = {CandidateAssemblyFiles};{HintPathFromItem};{TargetFrameworkDirectory};{RawFileName}
1>DesignTimeAssemblySearchPaths  = {CandidateAssemblyFiles};{HintPathFromItem};TargetFrameworkDirectory};{RawFileName}
```

**Comment by nguerrera** [comment]
Ugh, why are there 3 different search paths to begin with?

The missing `{` before TargetFrameworkDirectory in DesignTimeAssemblySearchPaths is a typo, not a product bug, right?

The fix is to add below [here](https://github.com/dotnet/sdk/blob/efe61125cf64688156961cbf4d3893cfef7f097a/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L68-L70), right?

``` XML
<ProjectDesignTimeAssemblyResolutionSearchPaths>$(AssemblySearchPaths)</ProjectDesignTimeAssemblyResolutionSearchPaths>
```

**Comment by dsplaisted** [comment]
@davkean Are you still going to use this property with your roslyn-project-system version of DTAR?

**Comment by davkean** [comment]
We don't use this property anymore - so do with what you want.
