### ISSUE TITLE
[Aspire]: Dashboard does not show logs when using dotnet watch

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#44319]
When using the IDE protocol dotnet watch is responsible to capturing and reporting logs via the DCP protocol. This doesn't work today and as a result the logs are empty for any project launched via watch.

https://github.com/user-attachments/assets/51f94d0b-f85a-4992-bf88-2b7ec17b370d

cc @karolz-ms here for IDE protocol guidance.

**Comment by karolz-ms** [comment]
The notification to deliver logs to DCP is described here https://github.com/dotnet/aspire/blob/main/docs/specs/IDE-execution.md#log-notification

**Comment by davidfowl** [comment]
Fixed by #44348
