### ISSUE TITLE
[Aspire]: dotnet watch IDE protocol doesn't update any process state

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#44318]
When running under watch the PID is 0

![Image](https://github.com/user-attachments/assets/66533237-ceab-44ee-ba54-f94a88ff4e61)

When the process is stopped, the state is not updated to Exited and there's no exit code.

https://github.com/user-attachments/assets/a6814439-4908-4537-b64f-c055c19d9732

cc @karolz-ms here for IDE protocol guidance.

**Comment by karolz-ms** [comment]
When IDE execution is used, DCP relies on the IDE to inform DCP about start/restart of the main process associated with the run session, run session termination, and logs emitted by the main process. It is all described here https://github.com/dotnet/aspire/blob/main/docs/specs/IDE-execution.md#run-session-change-notifications

Looks like none of these notifications are currently implemented by `dotnet watch`.

**Comment by davidfowl** [comment]
Fixed by #44348
