### ISSUE TITLE
When i use "dotnet publish" to generate osx-arm64 binary file on my win-x64 pc. I get an incorrect format file.

### ISSUE THREAD

**Issue by github0null** [dotnet/sdk#44359]
Hello, everyone.

I am working on a cross-platform project and distributing binaries to various platforms.

I work on Windows 10 x64,  and this is the publish script i'm using:

https://github.com/github0null/eide_tools/blob/master/publish.bat

this is my project:

https://github.com/github0null/eide_tools/blob/master/eide_tools.sln

It will publish osx-arm64 platform dll files by following command:

```bat
:: for osx-arm64
echo.
echo --- publish for osx-arm64 ---
echo.
dotnet publish ./eide_tools.sln -o %DIST_DIR%/darwin/unify_builder/arm64^
               -c Release --no-self-contained^
               -r osx-arm64^
               --framework net6.0^
               /property:GenerateFullPaths=true^
               /consoleloggerparameters:NoSummary
```

But my users tell me that they can't execute that binary on their mac book m1, using dotnet xxx.dll to execute it, and it prompts an error:

```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/zhangqi/.vscode/extensions/cl.eide-3.20.0/res/tools/darwin/unify_builder/arm64/unify_builder.dll'. An attempt was made to load a program with an incorrect format.
```

In addition, my user told me that if he compile the [repository](https://github.com/github0null/eide_tools) on his mac book and then overwrite the dll files, the program worked without error.

I want to know what I'm missing and what should I do ?

**Comment by baronfel** [comment]
I downloaded your extension and took at look at the dlls themselves to spot-check that they were having correct architectures set:

```
chethusk@Chet-Desktop:/mnt/c/Users/chusk/.vscode/extensions/cl.eide-3.20.0/res/tools/darwin/unify_builder$ file arm64/unify_builder.dll
arm64/unify_builder.dll: PE32+ executable (console) Aarch64 Mono/.Net assembly, for MS Windows, 2 sections
chethusk@Chet-Desktop:/mnt/c/Users/chusk/.vscode/extensions/cl.eide-3.20.0/res/tools/darwin/unify_builder$ file x86_64/unify_builder.dll
x86_64/unify_builder.dll: PE32+ executable (console) x86-64 Mono/.Net assembly, for MS Windows, 2 sections
```

So that seems correct. Do you have a mac to reproduce with at all? If not, can the user provide their `dotnet --info` information so we can verify they are using the correct architecture of the .NET tooling?

**Comment by github0null** [comment]
Thanks for your reply.

I don't have any mac book here, i've told the users to run some tests, they'll get back to me later.

**Comment by github0null** [comment]
Sorry for such a late reply.

My user uses something called "Rosetta" to convert x64 programs to arm64

So he installed the wrong version of dotnet

However, the application I provided was already arm64, which led to this error

![Image](https://github.com/user-attachments/assets/1e9b0b58-150f-4e14-8ef0-b69f1c856c92)

I've asked him to switch to the arm64 version of the runtime and now the program works.

Thanks for your help.
