### ISSUE TITLE
Move test templates to SDK repo

### ISSUE THREAD

**Issue by Evangelink** [dotnet/sdk#44416]
As of today, the [test-templates](https://github.com/dotnet/test-templates/tree/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0) repository is hosting test related templates.

I would like to suggest to move these templates directly to the SDK repository for the following benefits:

- these templates are only inserted into SDK
- simplify codeflow graph (reduce need for insertions and intermediate packages)
- help us moving towarded archivig this repo
- simplify handling the versions (we currently have -rtm suffix as we don't do any special final build before insertion)

I also think this is aligned with the idea of having test as core feature of the SDK.

Note that the test team is already working on SDK repo (for issues related to `dotnet test`, insertion of `test-templates` and `vstest`) so this would not complexify handling on our side.

I have already discussed offline with @marcpopMSFT about this idea.

cc @nohwnd @mariam-abdulla @pavelhorak @baronfel

**Comment by Evangelink** [comment]
cc 
@bradwilson for xUnit
@OsirisTerje and @rprouse for NUnit

@thomhurst for TUnit (linked to https://github.com/dotnet/test-templates/issues/518)

**Comment by rprouse** [comment]
Thanks for the heads up
