### ISSUE TITLE
[Aspire]: dotnet watch changing files in a leaf node project causes the entire project hierarchy to process to exit

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#44543]
Using the aspire starter project changing the WeatherForecast class should only cause changes to the ApiService but it triggers changes in the entire project graph.

https://github.com/user-attachments/assets/49bb4d43-1c76-429b-a401-1a687dfcbff3

**Comment by tmat** [comment]
The problem is that there is a build error. Still shouldn't behave like it does.

**Comment by tmat** [comment]
Fixed by  https://github.com/dotnet/sdk/issues/44543

**Comment by davidfowl** [comment]
@tmat that link is another issue, did you mean to link a pull request?

**Comment by tmat** [comment]
@davidfowl Updated link
