### ISSUE TITLE
Why does dotnet publish include files like Microsoft.CodeAnalysis.dll?

### ISSUE THREAD

**Issue by TheRealQuantam** [dotnet/sdk#44579]
Not sure if this is an issue, but as there is no discussion to ask, I'll post it here.

Specific configuration:
Visual Studio 2022
A solution of 5 different projects: 3 class libraries, 1 application, and 1 test project
All projects C# and set to trimmable
Release | Any CPU
net8.0
Framework-dependent
win-x64
Folder output

dotnet publish includes analyzers like Microsoft.CodeAnalysis.dll in the published output. If I understand correctly, these are only used during the build, and have no place in the published output to be shipped. And these analyzers have a substantial impact on the size of the result - assemblies in the Microsoft.CodeAnalysis family alone use up a full 12.5 MB of space in the output.

Changing the deployment type to self-contained and enabling publish trimmed appears to eliminate some of these files (the code assemblies for Microsoft.CodeAnalysis are gone, but the resource files for Microsoft.CodeAnalysis in 13 different languages are still there), but this is a moot point as the inclusion of .NET in the self-contained deployment increases the output size well beyond the size gained from eliminating these files.

**Comment by huoyaoyuan** [comment]
Microsoft.CodeAnalysis.dll is *the* C#/VB compiler. It can be used by applications or packages to compile code or scripts.

Are you using any package that transitively references the NuGet package?

**Comment by TheRealQuantam** [comment]
HMMM. Now that you mention it, it appears Avalonia.Diagnostics references it. Thanks.
