### ISSUE TITLE
http://schemas.microsoft.com/developer/msbuild/2003 should be fixed

### ISSUE THREAD

**Issue by rogersachan** [dotnet/sdk#446]
Why does the url link to nowhere?

**Comment by rainersigwald** [comment]
This is really an MSBuild issue, discussed in https://github.com/Microsoft/msbuild/issues/699 but I'll answer it here.

This is a remnant of a much earlier time, when a combination of the ideas "we need a unique string" and "URLs in our domain are an easy way to make unique strings" held sway. As far as I know it has literally never been a resolvable web address.

This is definitely unfortunate, but we don't plan to fix it. On the plus side, after https://github.com/Microsoft/msbuild/pull/1089, this string is no longer required in project files, and https://github.com/dotnet/sdk/pull/394 in this repo removed it from the default templates for new projects targeting .NET Core.
