### ISSUE TITLE
The error "Unable to find package Microsoft.Net.Sdk.Compilers.Toolset with version (= 10.0.100-alpha.1.24556.12)" appeared when creating the .NET project based on latest .NET SDK 10.0 with 17.12.0 Preview 5.0

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/sdk#44703]
**Version:**
.NET SDK 10.0.100-alpha.1.24556.12

### Describe the bug
The error "Unable to find package Microsoft.Net.Sdk.Compilers.Toolset with version (= 10.0.100-alpha.1.24556.12)" appeared when creating the .NET project based on latest .NET SDK 10.0 with 17.12.0 Preview 5.0

### To Reproduce
1. Installed the lasted .NET SDK 10.0 from https://github.com/dotnet/sdk/blob/main/documentation/package-table.md
2. Installed the Dev17 17.12.0 Preview 5.0 from https://visualstudio.microsoft.com/vs/preview/#download-preview
3. Create the .NET project targeting .NET 9.0, such as winforms/wpf/Console projects.

### Expected Result:
No error "Unable to find package Microsoft.Net.Sdk.Compilers.Toolset with version (= 10.0.100-alpha.1.24556.12)" appeared when creating .NET project

### Actual Result:
The error "Unable to find package Microsoft.Net.Sdk.Compilers.Toolset with version (= 10.0.100-alpha.1.24556.12)" appeared.
![Image](https://github.com/user-attachments/assets/4be78bb3-08b6-43d0-9c2b-a99ec2699f41)
![Image](https://github.com/user-attachments/assets/48c5093b-bb21-4706-8861-f1d9286cc473)

**More info:**
The issue cannot reproduce after uninstalled the latest .NET 10.0.

**Comment by MagicAndre1981** [comment]
try adding the dotnet 10 feeds to your local nuget.config:

    <add key="dotnet10" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/nuget/v3/index.json" />
    <add key="dotnet10-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10-transport/nuget/v3/index.json" />

**Comment by Zheng-Li01** [comment]
@MagicAndre1981m, thanks for your response, the error disappeared after added below configuration in the local nuget.config. closed this issue.

```
<add key="dotnet10" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/nuget/v3/index.json" />
<add key="dotnet10-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10-transport/nuget/v3/index.json" />
```

![Image](https://github.com/user-attachments/assets/f75691f8-4dc8-43f6-80a2-5e5aa31819ca)
