### ISSUE TITLE
Generate an error message if LanguageTargets property is not set and cannot be inferred

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#448]
`Sdk.targets` will import the CSharp or VisualBasic targets files depending on whether the project file extension is `.csproj` or `.vbproj`.  The `LanguageTargets` property can also be set to specify the targets file to import.

If `LanguageTargets` isn't set and the project file extension is neither `.csproj` nor `.vbproj`, then the build should fail with a helpful error.  This could happen if someone didn't specify the F# SDK for an `.fsproj`, for example.

**Comment by enricosada** [comment]
Hi @dsplaisted i think is good to have an error there.
But how can add a remote sdk (not bundled in cli?) with `Sdk` attribute? i want to populate `LanguageTargets` BEFORE Microsoft.NET.Sdk, so f# will work using `Sdk` attribute style

**Comment by enricosada** [comment]
NVM, i see for current msbuild RC, the sdk packages are just simulated (so expected to work from sdk directory), right @dsplaisted ? If like that i'll wait for next RC2 when sdk packages can be downloaded from nuget

**Comment by rainersigwald** [comment]
@enricosada That's correct, there's no acquisition story for Sdks yet. https://github.com/Microsoft/msbuild/issues/1436 tracks that.
