### ISSUE TITLE
dotnet restore on a solution file only restores one project

### ISSUE THREAD

**Issue by Pollyfun** [dotnet/sdk#44884]
This command fails to restore all the nugets to C:\Users\<user>\.nuget\packages.

dotnet restore MySolution.sln

In my use case, there's 4 projects in a solution. When running the command only one of the projects are restoring nugets. Which one seems random. Running the command several times eventually restores all of the nugets.

Using NET 8.0.400.

[Packages.zip](https://github.com/user-attachments/files/17775941/Packages.zip)

**Comment by JensNordenbro** [comment]
I get the same with .NET SDK 8.0.400

**Comment by Pollyfun** [comment]
This behaviour doesn't occur in all situations, so I've added a solution where it's easily reproducable.

Restoring nugets for the solution (in Visual Studio, or on the command line with dotnet restore) will seemingly randomly restore the nugets from one of the projects, but not for the other. Illustration added.

![Image](https://github.com/user-attachments/assets/7312cd38-453c-4e56-945e-61d65c8dcf16)
