### ISSUE TITLE
Microsoft.NET.Publish.Tests.dll.5 is timing out a lot, imbalance with other partitions

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/sdk#44895]
This workitem is one of the most frequent to time out: https://github.com/dotnet/sdk/issues/40074

A quick Kusto query shows that we're already pretty close to the default 45mins timeout for a lot of _passing_ runs:

<img width="487" alt="image" src="https://github.com/user-attachments/assets/8720c716-a237-4e10-a13c-e90bd377bd45">

This is Windows runs in the last 14 days with the x axis being the execution time. Note that the bucket on the left are runs which had test failures which still count as Status==Pass in Helix terms.

The other partitions of Microsoft.NET.Publish.Tests.dll are all in the 10-15mins range so we probably got unlucky and the long running tests are all in the .5 partition.

Bumping the timeout would be an option or increasing the number of partitions, are there other things we could do?

/cc @marcpopMSFT @baronfel

**Comment by marcpopMSFT** [comment]
FWIW, we could also go delete all of the net 5/6/7 targeting versions of the linker tests as well and make them all 8+.

**Comment by akoeplinger** [comment]
I ran some more queries and it looks like only the ILLink tests are approaching problematic durations.

Here's the query I used, note that `Microsoft.NET.Publish.Tests.dll.7` contains the ILLink tests for macOS/Linux and `Microsoft.NET.Publish.Tests.dll.5` for Windows

```kql
Jobs
| where Repository == "dotnet/sdk" and Queued > ago(14d)
| project JobId
| join kind=inner WorkItems on JobId
| where Status == "Pass"
| extend Duration=Finished-Started
| summarize MedianDuration=percentile(Duration, 50) by FriendlyName,QueueName
| order by MedianDuration desc
```
![Image](https://github.com/user-attachments/assets/c8e669ec-53ae-435c-b475-f895a3d60122)

I opened https://github.com/dotnet/sdk/pull/44973 to split up GivenThatWeWantToRunILLink
