### ISSUE TITLE
publishsinglefile causes runtime failure of hostpolicy.dll not found for dotnet 9.0.100

### ISSUE THREAD

**Issue by jsahaj** [dotnet/sdk#44992]
[HelloWorldExample1.zip](https://github.com/user-attachments/files/17847365/HelloWorldExample1.zip)
When doing publishsinglefile=true and running resulting exe we get a runtime failure of hostpolicy.dll not found for dotnet 9.0.100.  This is a regression from net8, where it builds and runs fine.

With C# project file is defined as:
`<Project` Sdk="Microsoft.NET.Sdk">
  `<PropertyGroup>`
 `<OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>`

  `<Target` Name="PostBuild" AfterTargets="PostBuildEvent">
`    <Exec Command="dotnet publish --configuration $(Configuration) --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --no-build --output=$(EXEOUT) HelloWorldExample1.csproj" />
`  
`</Target>`
`</Project>`

Set EXEOUT to some directory and build the project.  Go to exeout directory at command prompt and run the executable and to get error:

c:\Temp\exeout>HelloWorldExample1.exe
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'c:\Temp\exeout\HelloWorldExample1.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'c:\Temp\exeout\HelloWorldExample1.runtimeconfig.json' file and specify the appropriate framework.

Removing the publishsinglefile allows program to run without error.

Versions: 
dotnet 9.0.100
VS 17.12.1
csc 4.12.0-3.24558.5

**Comment by jsahaj** [comment]
"<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet publish --configuration $(Configuration) --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --no-build --output=$(EXEOUT) HelloWorldExample1.csproj" />
  </Target>
</Project> "

**Comment by bording** [comment]
I was just about to file an issue for this problem but saw that it was reported already.

The thing I'll add is that it seems to be related to the use of `--no-build` with the publish command.

If you let `dotnet publish` also build then it seems to work properly.

**Comment by Hoaas** [comment]
Also experienced this with a buid pipeline like this:
`dotnet restore --runtime win-x64`
`dotnet build --configuration release --runtime win-x64 --self-contained -p:PublishSingleFileTrue --no-restore`
`dotnet publish --configuration release --runtime win-x64 --self-contained  --no-build`

Worked when removing `--no-build` on publish, but would rather now have to do that :/

**Comment by Forgind** [comment]
> Looks like https://github.com/dotnet/sdk/pull/45159 is the fix for this.

Sounds like this should be fixed 🙂
