### ISSUE TITLE
Solution build always fail with CS2012 "Cannot open dll for writing" errors

### ISSUE THREAD

**Issue by WindingWinter** [dotnet/sdk#45034]
Related to #9964 and #11593, but this time, it seems that I can always **always**  reproduce it with the below solution and csprojects.

The solution file:

```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.11.35312.102
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CSProjectMultiConstants", "CSProjectMultiConstants\CSProjectMultiConstants.csproj", "{9AA1B407-BD5F-486D-BE56-CBCD639B8A23}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MultipleConstantTest", "MultipleConstantTest\MultipleConstantTest.csproj", "{90C599A9-4DD3-4B22-95EB-D70F514E76DB}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{9AA1B407-BD5F-486D-BE56-CBCD639B8A23}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{9AA1B407-BD5F-486D-BE56-CBCD639B8A23}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{9AA1B407-BD5F-486D-BE56-CBCD639B8A23}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{9AA1B407-BD5F-486D-BE56-CBCD639B8A23}.Release|Any CPU.Build.0 = Release|Any CPU
		{90C599A9-4DD3-4B22-95EB-D70F514E76DB}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{90C599A9-4DD3-4B22-95EB-D70F514E76DB}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{90C599A9-4DD3-4B22-95EB-D70F514E76DB}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{90C599A9-4DD3-4B22-95EB-D70F514E76DB}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {21D359E2-E91A-4F4F-B54B-5B41A82BCF88}
	EndGlobalSection
EndGlobal


```

The `CSProjectMultiConstants.csproj`

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<C3DVersion>Ver2023</C3DVersion>
		 <PublishDir>bin\Publish\$(C3DVersion)</PublishDir>
	</PropertyGroup>
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath> 
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>
		<OutputPath>bin\Debug\$(C3DVersion)\</OutputPath>
		<DefineConstants>DEBUG;Trace;$(C3DVersion)</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<OutputPath>bin\Release\$(C3DVersion)\</OutputPath>
		<Prefer32Bit>false</Prefer32Bit>
		<DebugType>none</DebugType>
		<DefineConstants>Trace;$(C3DVersion)</DefineConstants>
		<IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(C3DVersion)</IntermediateOutputPath>
	</PropertyGroup>
	
    <Target Name="BuildVer2023">
    <Exec Command="dotnet build -p:C3DVersion=Ver2023 -c $(Configuration)"/>
	 </Target>

</Project>


```

The `MultipleConstantTest.csproj`

```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>  

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSProjectMultiConstants\CSProjectMultiConstants.csproj" />
  </ItemGroup>
  <Target Name="BuildVer2023">
    <Exec Command="dotnet build -p:C3DVersion=Ver2023 -c $(Configuration)"/>
  </Target>
  
</Project>

```

The actual content of the cs files doesn't seem to matter.

And now, this is how I write my batch script

```

set slnFile=%~dp0CSProjectMultiConstants.sln

dotnet clean "%slnFile%" --configuration Debug  REM comment the dotnet clean line out will make the error disappears
dotnet build "%slnFile%" -t:BuildVer2023 -c Debug


```

If I run the above `.bat` file, then I will **surely** get crash as such:

```

E:\>dotnet clean "D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants.sln" --configuration Debug

Build succeeded in 0.4s

E:\>dotnet build "D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants.sln" -t:BuildVer2023 -c Debug
  MultipleConstantTest net8.0 failed with 3 error(s) (1.2s)
    CSC : error CS2012: Cannot open 'D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\obj\Debug\CSProjectMultiConstants.dll' for writing -- 'The process cannot access the file 'D\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\obj\Debug\CSProjectMultiConstants.dll' because it is being used by another process.' [D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\CSProjectMultiConstants_dfx0esc2_wpftmp.csproj]
    CSC : error CS2012: Cannot open 'D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\obj\Debug\CSProjectMultiConstants.dll' for writing -- 'The process cannot access the file 'D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\obj\Debug\CSProjectMultiConstants.dll' because it is being used by another process.' [D:\.Net Plain\CSProjectMultiConstants\CSProjectMultiConstants\CSProjectMultiConstants_dfx0esc2_wpftmp.csproj]
    D:\.Net Plain\CSProjectMultiConstants\MultipleConstantTest\MultipleConstantTest.csproj(15,5): error MSB3073: The command "dotnet build -p:C3DVersion=Ver2023 -c Debug" exited with code 1.

Build failed with 3 error(s) in 1.5s

```

The crash can be reproduced even after I restart my machine. And consistently, every single time.  Regardless of whether VS 2022 is opened at that time or not.

**Comment by WindingWinter** [comment]
And I can avoid the problem if either I

1. Don't `dotnet clean` before `dotnet build`
2. Remove `MultipleConstantTest.csproj`, and effective make the solution a one project solution.

**Comment by dsplaisted** [comment]
This is what is causing problems:

```xml
  <Target Name="BuildVer2023">
    <Exec Command="dotnet build -p:C3DVersion=Ver2023 -c $(Configuration)"/>
  </Target>
```

Doing an `Exec` of "dotnet build" is something you should avoid.  This creates an entirely separate build process.  In this case, you end up with two separate builds of the same project running at the same time, one from the solution file, and one by following the project reference from the other project.  Both these builds try to write to the same output file, and when they do that concurrently, one of them fails.

I'm not sure exactly why you have the special targets, but you may be able to simply remove them and change the top level invocation to something like `dotnet build "%slnFile%" -p:C3DVersion=Ver2023 -c Debug`

**Comment by WindingWinter** [comment]
@dsplaisted , the reason why I'm using `Target` is because I want to build multiple versions with different compilation constants ( the original description unfortunately didn't reflect this point well enough, leading to the confusion).  

In my actual project this is how the `targets` files look like:

```
   <!-- Custom targets for building/publishing all versions -->
  <Target Name="BuildAll" DependsOnTargets="BuildVer2022;BuildVer2023;BuildVer2024" />
  
  <Target Name="BuildVer2022">
    <Exec Command="dotnet build -p:C3DVersion=Ver2022 -c $(Configuration)"/>
  </Target>

  <Target Name="BuildVer2023">
    <Exec Command="dotnet build -p:C3DVersion=Ver2023 -c $(Configuration)"/>
  </Target>

  <Target Name="BuildVer2024">
    <Exec Command="dotnet build -p:C3DVersion=Ver2024 -c $(Configuration)"/>
  </Target>
```

So when I call from my batch script that's all I have to do

```
rem dotnet build "%slnFile%" -t:BuildAll -c Debug
```

In order to build everything.

**Comment by WindingWinter** [comment]
But wouldn't MSBuild also have the same problem?

After all dotnet build is just a wrapper on top of MSBuild

**Comment by dsplaisted** [comment]
When you use the `MSBuild` task, then you are building the project as part of the same overall build.  So MSBuild knows about the different versions of the project building, and it won't build the same project twice with the same global properties.  When you shell out into a completely new process then you have separate builds going on at the same time which are entirely unrelated from MSBuild's perspective.

In this case I think the main thing is that you need different output and intermediate paths for the different C3DVersion values.

**Comment by WindingWinter** [comment]
@dsplaisted , I would like to note that using `Exec` doesn't fail always-- somehow if I do a `publish` instead of `build` command, then I won't have this `CS2012` problem.

So does that mean that I can continue to use `Exec` for `dotnet publish`?

**Comment by dsplaisted** [comment]
It is better to avoid using `Exec` for any `dotnet` commands invoke a build.  That includes publish.  It may not specifically be causing a problem here, but it could in the future, or it might depend on timing so it could cause sporadic failures.

**Comment by WindingWinter** [comment]
But `MSBuild` doesn't have a built-in equivalent of `dotnet publish`. Or is there an implementation of `dotnet publish` using `MSBuild`  that I can refer to?

**Comment by marcpopMSFT** [comment]
Publish is a bit of a special case and is not recommended to do this way. However, we think you should be able to call the Publish target, ensure the RID you are targeting is in your project RuntimeIdentifiers list, AND set _IsPublishing=true which we think should be sufficient.

Here's a sample from baronfel got working: https://github.com/baronfel/sdk-container-demo/blob/main/src/solution-level-example/Directory.Solution.targets#L20

There will definitely be cases that this solution doesn't work but we think this works most of the time.

**Comment by Forgind** [comment]
I agree with what dsplaisted posted above. Hope it helped!
