### ISSUE TITLE
PublishDir foldername cannot containt comma

### ISSUE THREAD

**Issue by BWWIT** [dotnet/sdk#45079]
### Describe the bug
If I publish to a folder named `C:\temp\W_WinPS 1.00 (net6, CS)` I get the error "MSB1006: Property is not valid."
I can publish to `C:\temp\W_WinPS 1.00 (net6 CS)` (no comma)

### To Reproduce
``` CMD
set PrjDir=C:\DATA\Development\LIBRARIES WIT\Windows utils\Win-Powershell\W_WinPS 1.00 (net6, CS)\
set PubDir=C:\temp\W_WinPS 1.00 (net6, CS)
dotnet publish "%PrjDir%W_WinPS.csproj" --runtime win-x64 --configuration "Release_x64_Windows" --framework net6.0-windows /p:PublishReadyToRun=true /p:PublishDir="%PubDir%"
```

### Further technical details
.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.8cf8de6d

(Just a general note: I also see strange errors in many places if a folder and/or file contain "#" and "~"...please, in general, get your folder-name and file-name handling in order. I have seen these stupid errors in dotnet forever, we should be passed that in 2024! If the filesystem accept a character, you should  expect dotnet support it too, especially on Windows)

**Comment by Forgind** [comment]
I haven't tried them, but I suspect KalleOlaviNiemitalo's workarounds should work. This functionality is built pretty deep in MSBuild, and it isn't changing any time soon, so I don't think there's any more action that can be taken for it.
