### ISSUE TITLE
Change PrivateAssets to be an attribute instead of an element

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#452]
The new templates still have PrivateAssets as an element when attributes work and are more succinct. I haven't heard a good reason why this is.

**Comment by dsplaisted** [comment]
Which templates?  I think all of the `PackageReferences` with PrivateAssets on them will change to MSBuild Sdks.

**Comment by davidfowl** [comment]
Wonderful, did that change already happen? If not where is the bug and who is doing the work?
