### ISSUE TITLE
Self-contained single-file program, published with --no-build option, needs .NET to be installed

### ISSUE THREAD

**Issue by andygjp** [dotnet/sdk#45230]
I've created a repo and a README.md detailing some investigation here: https://github.com/andygjp/MustInstalDotNetSelfContainedNoBuild

In short, I can build a self-contained project and then package it up, with the `--no-build` option, like so:

```powershell
$configuration = "Release"
$runtime = "win-x64"
$framework = "net9.0"

# project built in a previous step
dotnet publish MyProject.csproj `
--configuration $configuration `
--runtime $runtime `
--framework $framework `
--no-restore `
--no-build
```

That works fine.

If I repeat that, but publish a single file, like so:

```powershell
dotnet publish MyProject.csproj `
--configuration $configuration `
--runtime $runtime `
--framework $framework `
--no-restore `
--no-build `
--property:PublishSingleFile=$true `
--property:IncludeNativeLibrariesForSelfExtract=$true
```

It fails with: "You must install .NET to run this application."

If I repeat the last command, but remove the `--no-build` option, it works again. 

Why must I have to build it again or remove `--property:PublishSingleFile` option to make it work?

**Comment by bording** [comment]
Looks like https://github.com/dotnet/sdk/pull/45159 is the fix for this.

**Comment by andygjp** [comment]
@bording I think you're right.

I just added:

```xml
<Target Name="_WorkaroundIncorrectAppHost" BeforeTargets="_GetComHostPaths">
  <CallTarget Targets="_GetAppHostCreationConfiguration" />
</Target>
```

To the `csproj` in the repo, as suggested here: https://github.com/dotnet/sdk/pull/45159#issuecomment-2502044354, and the `--no-build` exe is the same size as the exe built without the `--no-build` option.

**Comment by marcpopMSFT** [comment]
This should release in 9.0.103 in February as it missed the cutoff for Jan.
