### ISSUE TITLE
net9 cli timestamp problem

### ISSUE THREAD

**Issue by tkefauver** [dotnet/sdk#45386]
After updating to net9 I've noticed a change in the cli where it auto updates the output and leaves an on going timestamp in the corner. Is there a way to turn this off??

It intercedes and/or replaces actual log output as it updates which is problematic maybe its just me cause I haven't found anyone else mentioning this but it would be good if I could turn it off somehow.

**Comment by jkotas** [comment]
You can go back to the old CLI output behavior by setting `MSBUILDTERMINALLOGGER=off` in your environment.

**Comment by baronfel** [comment]
This is the new 'Terminal Logger' feature in MSBuild - you can see the [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/9.0/terminal-logger) notice for more details, including how to disable it temporarily or permanently.
