### ISSUE TITLE
When creating a 6.0 project, there isn't any warning say that 6.0 is out of support.

### ISSUE THREAD

**Issue by v-yuannie** [dotnet/sdk#45390]
### Describe the bug
When creating a 6.0 project, there isn't any warning say that 6.0 is out of support. 

### To Reproduce

INSTALL STEP
1. Clean machine: Win11 x64 24h2 ENU 
2. Install Dev17.10 VAL build PR 596196 for making 6.0 out of support in VS, LTSC channel

- Web workload
- .NET Core 6.0 Runtime (Out of support)

REPRO STEPS
1. Open VS > New project > Any template > Choose 6.0 runtime
2. After creating the 6.0 project, there isn't any warning say that 6.0 is out of support. 
![Image](https://github.com/user-attachments/assets/05ff189b-67ae-43d0-825e-a60270d14b97)

Note:
1. This issue also repro on 17.8/17.12/17.13 P3 PR builds for making 6.0 out of support in VS
### Expected
It should have a warning that informs the user that 6.0 is out of support. For example, after creating 7.0 project, users see the following warning
![Image](https://github.com/user-attachments/assets/371f7ee1-583d-4c54-9416-1544d6f05cd8)

### Further technical details
.NET SDK:
 Version:           8.0.307
 Commit:            353be46607
 Workload version:  8.0.300-manifests.1c2a2fce
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.307\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35606.61
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3

.NET SDKs installed:
  8.0.307 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-yuannie** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

I have not the write-permissions. It should be Area-NetSDK label.

**Comment by v-qushi** [comment]
It's a dup of [Bug 2319092](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2319092): [NETSDKE2E][VS64]There is no oos warning after building NET6.0 project on VS 17.10/17.8/17.12/17.13 preview 3.
