### ISSUE TITLE
Single Portable File Configuration

### ISSUE THREAD

**Issue by DWishR** [dotnet/sdk#45401]
I am working in an environment where I can expect certain SDKs (like dotnet) to be installed on the host machine. I have a version control system (Perforce) that can run a specified command on the host machine when certain events happen ([triggers](https://help.perforce.com/helix-core/server-apps/p4sag/current/Content/P4SAG/scripting.triggers.basics.html)). The command can reference files within version control, and the version control system will grab the latest version of that file to run the command. I'd love to write the trigger in C#, but I can't find a portable configuration that works with a single file. My choices seem to be:

- Publish a portable DLL which requires extra configuration files to run (e.g. `trigger.deps.json`)
- Publish a platform-specific single binary ("SelfContained" and "PublishSingleFile")

### Describe the solution you'd like
I'd love to either:
- Run a single csharp script directly as a console app (i.e. `dotnet simpleScript.cs`) -- mostly this
- Have a single file _portable_ publish configuration that still requires the runtime installed but works with just one file

### Additional context
This is basically a "let me use a dotnet/csharp script instead of python" in situations that expect a single file to be functional. I can imagine extending this to #! style console scripts, which I for one would enjoy writing in csharp instead of other languages. Granted compilation will require some amount of startup time, but plenty of systems are compiling python today anyway. This seems like a natural extension of the Top-Level Statements mindset.

**Comment by DWishR** [comment]
This might be a dupe of #43086 (if so sorry)

**Comment by WeihanLi** [comment]
I'm drafting a dotnet tool, maybe you can have a try https://github.com/WeihanLi/dotnet-exec

Install the dotnet-tool

```sh
dotnet tool update -g dotnet-execute
```

then you could try `dotnet-exec simpleScript.cs`

**Comment by marcpopMSFT** [comment]
Let's use 43086 as the tracking issue for this. It is something we are having discussions over.
