### ISSUE TITLE
[Feature Request]: dotnet CLI - Install SDK(s)

### ISSUE THREAD

**Issue by rwoll** [dotnet/sdk#45403]
### Is your feature request related to a problem? Please describe.

When working on different projects, they sometimes require me to install different versions of the SDK. Often this means finding it on the dotnet website (https://dotnet.microsoft.com/en-us/download/dotnet/8.0) and downloading it and installing it via GUI.

Other times I'm working in a mostly headless environment (like a GitHub Codespace or machine workstation over SSH) and then when I want to download different SDK versions, I have to look up a different method for installation which usually includes running some shell scripts.

### Describe the solution you'd like

Assuming the machine already has one SDK/cli version installed, I'd love to be able to install different versions of dotnet SDKs directly via the dotnet CLI: `dotnet install sdk --version=foo`.

**Comment by baronfel** [comment]
Thanks for logging this - here's our canonical tracking issue for this request: https://github.com/dotnet/sdk/issues/7549.
