### ISSUE TITLE
[NETSDKE2E]Warning "Workload garbage collection failed with error: The specified version does not contain a valid major, minor, and patch version: '9.0.100.1'.." displays after installing the workload set from global.json.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#45424]
Build: 9.0.102

1.install 9.0.102 sdk on win-x64
2.dotnet workload install maui
3.Dotnet workload config --update-mode workload-set
4.Dotnet workload update
5.mkdir test
cd test
dotnet new globaljson and add update it with below contents
{
  "sdk": {
    "workloadVersion": "9.0.100"
  }
}
6.dotnet workload update
**Expected Result:**
Step4 and Step6: Update successfully without any warnings.

**Actual Result:**
Step4:Update successfully 
But for step6: Update successfully but below warning displays
![Image](https://github.com/user-attachments/assets/392979b6-645b-4c3a-821b-d5d2508620e2)

dotnet workload --info:
![Image](https://github.com/user-attachments/assets/cb31c5b0-daf3-4f80-93b9-1e97b5739a1c)

dotnet --info
.NET SDK:
 Version:           9.0.102
 Commit:            cb83cd4923
 Workload version:  9.0.101
 MSBuild version:   17.12.18+ed8c6aec5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.102\

.NET workloads installed:
 [maui]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maui\9.0.0\WorkloadManifest.json
   Install Type:              Msi

Configured to use workload sets when installing new manifests.

Host:
  Version:      9.0.1
  Architecture: x64
  Commit:       c8acea2262

.NET SDKs installed:
  9.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on arm64OS.
![Image](https://github.com/user-attachments/assets/fd53ce0e-a535-4331-b6f5-b0280f8b2cff)

**Comment by marcpopMSFT** [comment]
Fixed in 9.0.200. I don't think we have plans to backport it as it's non-blocking and only applies to hotfix workload set versions which should be fairly infrequent. https://github.com/dotnet/sdk/pull/45263
