### ISSUE TITLE
Clear Communication regarding Servicing Releases

### ISSUE THREAD

**Issue by lFDMjqXepr6Dv1fYzaERJPhdOvst4joK** [dotnet/sdk#45426]
Dear Sir or Madam,

Microsoft releases security patches each month on the second Tuesday.

Also, the dotnet SDK PR Guide, ref. (https://github.com/dotnet/sdk/blob/main/documentation/project-docs/SDK-PR-guide.md#servicing-releases) defines a monthly release.

But sometimes, the servicing release is released a couple of days after Microsofts Patch-Tuesday, sometimes it is released a couple of weeks later and in rare cases it is skipped.

Due to the fact that companies have to plan updating their software, a reliable communication about the schedule of servicing release should be available at the beginning of each month at the latest.

Kind regards

**Comment by marcpopMSFT** [comment]
We ship servicing updates monthly and they should all go out on patch Tuesday. December was skipped to avoid risk before the holidays.
