### ISSUE TITLE
Custom Dockerfile support in `PublishContainer` target

### ISSUE THREAD

**Issue by dombrovsky** [dotnet/sdk#45491]
We are using custom Dockerfiles for building container images for our csprojs. We are also using .NET Aspire, and we would like to use [Aspire8](https://github.com/prom3theu5/aspirational-manifests) project to generate helm yamls.
Aspir8 project relies on `dotnet publish -t:PublishContainer` to build images for csprojs, which ignores existing custom Dockerfile.

A feature request is to make `PublishContainer` target respect `DockerfileFile` property, so that when it is specified `dotnet publish -t:PublishContainer`  command would build image using specified Dockerfile.

Alternative solution would be to add support to Apire8 for calling `docker build` instead of `dotnet publish`. However it feels that having it in dotnet sdk could be useful in other scenarios as well.

**Comment by baronfel** [comment]
Hello - we track feature requests for containers over at https://github.com/dotnet/sdk-container-builds - specifically this request is [/issues/125](https://github.com/dotnet/sdk-container-builds/issues/125). If you want to bring up this use case there we can talk through some of the details.
