### ISSUE TITLE
[NETE2ESDK] [Azure Linux ARM64] Installing .NET 10 alpha SDK in Mariner2 ARM64 2.0 or Azure Linux ARM64 3.0 should not depend on package netstandard-targeting-pack-2.1

### ISSUE THREAD

**Issue by ChenhuiYuan01** [dotnet/sdk#45499]
**Repro steps:**

1. Prepare Mariner2 ARM64 2.0 or Azure Linux ARM64 3.0 in Dokcer via running
`sudo docker run -it -v ~/tmp:/root/workspace mcr.microsoft.com/cbl-mariner/base/core:2.0 sh`
or
`sudo docker run -it -v ~/tmp:/root/workspace mcr.microsoft.com/azurelinux/base/core:3.0 sh`

2.  Try to install 10.0.100-alpha.1.24616.9 SDK via installer *.cm.2-aarch64.rpm

**Expected:**
SDK installed successfully.

**Actual result:**
SDK install failed as depending on package netstandard-targeting-pack-2.1
![Image](https://github.com/user-attachments/assets/40df7c2a-bb9e-47f6-b427-9018b0b40c94)

**Note:**
1. This SDK could be installed successfully in Mariner2 X64 2.0 and Azure Linux X64 3.0 
![Image](https://github.com/user-attachments/assets/ca7d6330-8b85-4d5a-acfb-b2dbaf3586ae)
![Image](https://github.com/user-attachments/assets/a7ada625-619a-4461-89b5-55a0e8b5bb2c)

2.  Net9.0 could be installed successfully in Mariner2 ARM64 2.0 and Azure Linux ARM64 3.0

**Comment by marcpopMSFT** [comment]
@dsplaisted @dotnet/source-build-triage to see if others are more knowledgeable about how this worked in 8/9 versus 10 for those platforms.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic for input.

**Comment by NikolaMilosavljevic** [comment]
We have modified the RPM build recently, this might be one of the side-effects. I believe arm64 SDK should not have a dependency on `netstandard-targetingpack-2.1`.

Will take a look and prepare a fix.

**Comment by ChenhuiYuan01** [comment]
This issue does not repro on 10.0.100-alpha.1.24623.3(runtime-10.0.0-alpha.1.24620.10)
