### ISSUE TITLE
Need a way to specify RID-specific dependencies

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#4552]
Folks often need to cross compile and use an OS-specific package.  Today the only way they can do this is to fork their project.json.

I think we need a "dependencies" section under the RID entry in runtimes.

This is related to https://github.com/NuGet/Home/issues/1660.

**Comment by baronfel** [comment]
NuGet packages support RID-specific assets now. Closing this as a result.

**Comment by PathogenDavid** [comment]
@baronfel This isn't about RID-specific assets, it's about RID-specific dependencies.

Unless I missed something in .NET 8, I don't think the latter is supported.

(That being said, maybe https://github.com/NuGet/Home/issues/1660 or https://github.com/NuGet/Home/issues/10571 is a better place to track this anyway?)

**Comment by baronfel** [comment]
Ah, good call on both counts. NuGet will need to understand/define something structure for describing these, then probably the SDK's ResolvePackageAssets task will need updating to follow that structure.
