### ISSUE TITLE
Difficult to diagnose RC2 csproj that references RC1 csproj

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#456]
Consider a solution wherein Rc2Proj depends on Rc1Lib. Rc2Proj uses the `Sdk` attribute while Rc1Lib uses an SDK `PackageReference`.  When building Rc2Proj we see:

```
C:\dotnet\cli\sdk\1.0.0-preview4\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.targets(82,5): error MSB4062: The "GenerateDepsFile" task could not be loaded from the assembly C:\dotnet\cli\sdk\1.0.0-preview4\Sdks\Microsoft.Net.Sdk\build\..\tools\netcoreapp1.0/Microsoft.NET.Build.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\myproject\bin\Release\netcoreapp1.0\Rc2Proj\Rc2Proj.csproj]
C:\dotnet\cli\sdk\1.0.0-preview4\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.targets(82,5): error : Cannot find project info for 'C:\myproject\bin\Release\netcoreapp1.0\Rc1Lib\Rc1Lib.csproj'. This can indicate a missing project reference. [C:\myproject\bin\Release\netcoreapp1.0\ProjectC\ProjectC.csproj]
C:\dotnet\cli\sdk\1.0.0-preview4\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.targets(82,5): error : Cannot find project info for 'C:\myproject\bin\Release\netcoreapp1.0\Rc1Lib\Rc1Lib.csproj'. This can indicate a missing project reference. [C:\myproject\bin\Release\netcoreapp1.0\ProjectB\ProjectB.csproj]
C:\dotnet\cli\sdk\1.0.0-preview4\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.targets(82,5): error : Cannot find project info for 'C:\myproject\bin\Release\netcoreapp1.0\Rc1Lib\Rc1Lib.csproj'. This can indicate a missing project reference. [C:\myproject\bin\Release\netcoreapp1.0\ProjectA\ProjectA.csproj]
```

This is not indicative of the actual failure, nor does it lead users to a solution. The Sdk should detect and report on this state. As a minimum, this issue should exist to help folks find a workaround.

### Workaround
Anyone in the scenario described above should fix their Rc1Lib.csproj by:
1. Remove the Sdk Package Reference. This will typically be:
```
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>{some version}</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```
2. On the first line of the Rc1Lib.csproj add an attribute `Sdk="Microsoft.Net.Sdk"`. It should look like this: `<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0"> `
3. Remove the first and last imports, these two:
```
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" /> 
...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" /> 
```

**Comment by davidfowl** [comment]
Maybe VS should automigrate RC1 -> RC2 to cut down on the number of people that will hit this. Similarly dotnet-migrate could do it as well...

**Comment by dsplaisted** [comment]
This is one of the reasons we want to force all projects in the build to use the same version of the SDK.

@nguerrera @rainersigwald @cdmihai @AndyGerlicher Can you think of a way that we could detect that a project we're referencing is using the RC1 SDK (via a `PackageReference`) and generate an error *without* calling any of our custom tasks?

**Comment by rainersigwald** [comment]
Ideas:

* Set something to override `$(CustomAfterMicrosoftCommonTargets)` and import a file with an InitialTargets that does the check. (This would override any use of that property by the customer which is unfortunate, but netcore csproj may be new enough that there's not much use. Though NuGet does use it--but I think only at restore time.)
* Add a target using one of the wildcard-import extensibility mechanisms to do the same.

Neither is very satisfying.

**Comment by srivatsn** [comment]
This is unfortunate but it is unlikely we will do anything here. This issue can serve as the documentation for migrating such projects.
