### ISSUE TITLE
dotnet watch crashes with fsproj is not associated with a language

### ISSUE THREAD

**Issue by halcwb** [dotnet/sdk#45610]
> I installed the sdk for the fix:
> 
> dotnet --info
> .NET SDK:
>  Version:           9.0.101
>  Commit:            eedb237549
>  Workload version:  9.0.100-manifests.3068a692
>  MSBuild version:   17.12.12+1cce77968
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  14.6
>  OS Platform: Darwin
>  RID:         osx-arm64
>  Base Path:   /usr/local/share/dotnet/sdk/9.0.101/
> 
> Unfortunately, I stil run into the **'fsproj' is not associated with a language error:** 
> 
> ```
> dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
>   💡 Press "Ctrl + R" to restart.
> Hello from F#!
> dotnet watch ⌚ [Server (net9.0)] Exited
> dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
> dotnet watch ❌ System.InvalidOperationException: Cannot open project '/Users/halcwb/Development/halcwb/apps/PICEDashboard/src/Server/Server.fsproj' because the file extension '.fsproj' is not associated with a language.
>    at Microsoft.CodeAnalysis.MSBuild.DiagnosticReporter.Report(DiagnosticReportingMode mode, String message, Func`2 createException)
>    at Microsoft.CodeAnalysis.MSBuild.ProjectFileExtensionRegistry.TryGetLanguageNameFromProjectPath(String projectFilePath, DiagnosticReportingMode mode, String& languageName)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadProjectFileInfosAsync(String projectPath, DiagnosticReportingOptions reportingOptions, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadProjectInfosFromPathAsync(String projectPath, DiagnosticReportingOptions reportingOptions, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadProjectInfoAsync(String projectFilePath, ProjectMap projectMap, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadProjectInfoAsync(String projectFilePath, ProjectMap projectMap, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
>    at Microsoft.DotNet.Watcher.Tools.IncrementalMSBuildWorkspace.UpdateProjectConeAsync(String rootProjectPath, CancellationToken cancellationToken)
>    at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
>    at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
>    at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
>    at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
>    at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
>    at Microsoft.DotNet.Watcher.Program.RunAsync()
> dotnet watch ❌ An unexpected error occurred
> ```
> 
>  

 _Originally posted by @halcwb in [#44908](https://github.com/dotnet/sdk/issues/44908#issuecomment-2558543089)_

**Comment by baronfel** [comment]
Closing due to my comments on the other issue - this is just a timing thing and should be cleared up in January.
