### ISSUE TITLE
Provide useful error when user targets Shared Framework that is not installed

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/sdk#458]
Repro:
Install Shared Framework 1.0.1.
Create new csproj that targets Shared Framework 1.1
`dotnet run` from CLI, `run` from VS

Expected:
A useful message telling the developer that their app is designed to run on a shared framework which has not been installed yet, along with installation help.

Actual:
Host complains about missing Shared Framework

We have some experience here via the host, but that experience is very end-user focused. In scenarios where the SDK is in play [CLI, VS] we should provide a dev-centric experience. This should mean good messaging for the time being, and eventually may even mean acquiring new Dev components for them. Opening in SDK repo as this needs to be unified for VS and CLI and others.

Related to https://github.com/dotnet/cli/issues/2454

**Comment by davidfowl** [comment]
This should be done as part of https://github.com/dotnet/sdk/issues/26 

/cc @natidea
