### ISSUE TITLE
Build/run/publish etc should use project.assets.json to determine the packages folder.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#459]
See https://github.com/dotnet/cli/issues/4649.

The project.assets.json has a packagesFolders that can be used for this.

```
"packageFolders": {
    "/Users/livarcocc/Documents/git/cli/.nuget/packages": {}
  }
```

**Comment by natidea** [comment]
@livarcocc is the ask here to simply raise this information to MSBuild so downstream tasks can use it? We already use package folders to resolve paths, as of this PR: https://github.com/dotnet/sdk/pull/368

**Comment by natidea** [comment]
The underlying `--packages` bug is fixed according to @livarcocc and kwicher
