### ISSUE TITLE
.NetCore Console App : Build behaviour is inconsistent

### ISSUE THREAD

**Issue by singhsarab** [dotnet/sdk#464]
For a .NetCore Console Application, Build solution always builds the project even if nothing has changed in the project.
This is not consistent with the existing behavior for a normal Desktop Console Application.

For consecutive build (if no changes are made in the project)
Expected: 
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
Actual:
1>------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
1>ConsoleApp1 -> [PathToFile]ConsoleApp1.dll
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

Impact:
For Unit Test project (.Net Core), since the test container is being updated every time build is called, discovery gets triggered every time, which is certainly unnecessary if no changes were made.

**Comment by srivatsn** [comment]
Is up-to-date check broken?

**Comment by gulbanana** [comment]
yes, it is- see https://github.com/dotnet/roslyn-project-system/issues/62

**Comment by dsplaisted** [comment]
I think dotnet/roslyn-project-system#1334 fixes this

**Comment by davkean** [comment]
The issue where we rebuild the dll even when nothing is changed is fixed by https://github.com/dotnet/roslyn-project-system/issues/825.

The issue where we always call MSBuild, is being tracked by https://github.com/dotnet/roslyn-project-system/issues/62.

**Comment by davkean** [comment]
@morrisjoe This was fixed in RC3 - should it be actually marked as RC3 Known Issue?

**Comment by srivatsn** [comment]
This wasn't fixed for RC3. It was merged into master.

**Comment by davkean** [comment]
Yeah, my mistake I just came back to write that.
