### ISSUE TITLE
Bash completion for `dotnet`

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/sdk#4674]
It would be nice to have completions for various `dotnet` commands/options.

**Comment by jasonkarns** [comment]
It looks like the homebrew cask for the SDK is also lacking the completion registration for homebrew.

https://github.com/Homebrew/homebrew-cask/blob/d79bc9f88fc8028ca03343c70dfc03582fe5aa03/Casks/dotnet-sdk.rb

**Comment by jasonkarns** [comment]
I have a larger concern that I just discovered: the completion scripts are not present in the tagged releases on github:

current master: https://github.com/dotnet/sdk/tree/e80cf181f715697b88f18845d095bb9b623f325a/scripts
latest tagged release: https://github.com/dotnet/sdk/tree/v3.1.401/scripts

So it's not presently possible to safely install the scripts as associated with the corresponding dotnet release.

**Comment by omajid** [comment]
This is caused by the repo consolidation/move that moved a ton of code around, not just the scripts.

In 3.1 the scripts were in cli: https://github.com/dotnet/cli/blob/release/3.1.1xx/scripts/register-completions.bash

**Comment by baronfel** [comment]
The scripts are in a well-known place, and I believe our source-build partners actually bundle them in the linux packages now! Happy tab-completing!
