### ISSUE TITLE
Incremental build deletes *.runtimeconfig.*.json if there is a runtimeconfig.template.json in the project

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#471]
The issue is that the fix made for deps.json (https://github.com/dotnet/sdk/pull/424) was not made for runtimeconfig.json.

This causes every other F5 of a .NET Core App that has a runtimconfig.template.json to fail.

It turns out that the issue is less common for runtimeconfig.json because we have and Inputs=runtimeconfig.template.json which causes the task to run always if the file does not exist (and it commonly doesn't). However, if the file does exist then we get the same bad behavior for runtimeconfig.json that was seen with deps.json.

When fixing this, we should also:

* Make sure to actually skip the generation if it's up to date but there is no template file
* Audit all other uses of FileWrites for other possible latent issues here.

**Comment by DamianEdwards** [comment]
Seeing this in [aspnet/live.asp.net](https://github.com/aspnet/live.asp.net) after migration
