### ISSUE TITLE
runtimeconfig.json file is not added to BuiltProjectOutputGroupOutput in inner build

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#472]
For any app targeting netcoreapp1.0 , a runtimeconfig.json file is generated in the bin folder, but pack fails to include it in the nupkg because this is not included in the list of files given by BuiltProjectOutputGroup target.

Talked to @rainersigwald about this, the bug lies in 
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L119-L128 

This issue is being tracked on the NuGet side by : https://github.com/NuGet/Home/issues/3878

CLI : https://github.com/dotnet/cli/issues/2432

**Comment by rainersigwald** [comment]
This should be as easy as adding

```xml
  <ItemGroup>
   <BuiltProjectOutputGroupOutput Include="$(ProjectRuntimeConfigFilePath)">
     <FinalOutputPath>$(ProjectRuntimeConfigFilePath)</FinalOutputPath>
   </BuiltProjectOutputGroupOutput>
  </ItemGroup>
```

somewhere in `Microsoft.NET.Sdk.targets`.

**Comment by davidfowl** [comment]
This file also needs to be renamed to {app}.runtimeconfig.json and merged with the generated one. We need to have a default runtimeconfig.json file in web projects so that we can turn on ServerGC.

/cc @BillHiebert

**Comment by eerhardt** [comment]
AFAIK, The dotnet host executable only knows how to read a single "runtimeconfig.json" file.

Maybe the task that generates the single file can accept multiple json files to merge into one:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs

And maybe there is metadata associated with the file for priority. Where the users file in their project has the highest priority (overrides all properties set by SDKs).

This way other extensions can default runtimeconfig properties as well.

Thoughts?

**Comment by davidfowl** [comment]
YES! Like app.config turns into MyAppName.config.

**Comment by rohit21agrawal** [comment]
any updates or eta on this? 

@srivatsn

**Comment by srivatsn** [comment]
@dsplaisted can you take a look?

**Comment by rrelyea** [comment]
assume this is RTM now?

**Comment by danroth27** [comment]
@srivatsn @dsplaisted Is there no way to get this in for RTM? You should be able to just create a .NET Core Console app and pack it to build a .NET Core tool.

**Comment by blackdwarf** [comment]
I would like to echo what @danroth27 said above. Is there no chance to get in this for RTM? Will it not pass the bar?

**Comment by srivatsn** [comment]
I see. Do we expect packing a console app would be a common scenario? When you say .NET Core tool, do you mean something that can be included by the DotnetCliToolsReference tag? Is this the only thing preventing that from working? 

The fix is simple and we can pull this back into 1.0 but i'm just trying to understand the justification.

**Comment by danroth27** [comment]
> Do we expect packing a console app would be a common scenario? 

Yes! Building and distributing a .NET Core project tool should be as simple as creating  console app,  packing it, and publishing to nuget.org. In the future we will also support global .NET Core tools where these tools can be used from anywhere, not just from within a project. This is just like what Node.js has with `npm install -g`.

**Comment by srivatsn** [comment]
@dsplaisted given the change seems straightforward, let's prepare a PR and bring to shiproom.

**Comment by dsplaisted** [comment]
@rainersigwald @rohit21agrawal I tried adding the runtimeconfig.json file to BuiltProjectOutputGroupOutput, but this didn't cause it to be included in the generated NuGet package.  Looking at the pack targets, I'm not seeing how something from BuiltProjectOutputGroup is supposed to flow into the NuGet package.  Can you clarify?

**Comment by rohit21agrawal** [comment]
@dsplaisted we look at the ```FinalOutputPath``` metadata of all the items in the BuiltProjectOutputGroup.. make sure that is set when you include it

**Comment by rohit21agrawal** [comment]
Relevant part of nuget code : https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L119

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L165-L175

**Comment by mynkow** [comment]
Is it normal to have this error today with `netcoreapp2.1`?

**Comment by livarcocc** [comment]
Not really.

**Comment by mynkow** [comment]
If interested, checkout https://github.com/Elders/Cronus.Api/tree/Cronus.Api%405.0.0-beta0014

Run `build.cmd`

**Comment by daveaglick** [comment]
I'm also seeing problems with missing `runtimeconfig.json` files on `netcoreapp2.1` (at least I think I am). Here's what I see immediately after running `dotnet clean` followed by `dotnet build`:

```
c:\Code\Wyam>dotnet src\clients\Wyam\bin\Debug\netcoreapp2.1\Wyam.dll
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'c:\Code\Wyam\src\clients\Wyam\bin\Debug\netcoreapp2.1\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the c:\Code\Wyam\src\clients\Wyam\bin\Debug\netcoreapp2.1\Wyam.runtimeconfig.json file specifying the appropriate framework.

c:\Code\Wyam>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

c:\Code\Wyam>
```

It's also worth noting I was able to get this to run on the very first build, but haven't been able to since. I assume it created the necessary file in the absence of any sort of build cache, but now it's not outputting it again (I also tried clearing the `bin` and `obj` directories).

**Comment by livarcocc** [comment]
@daveaglick I would suggest filling a new issue with repro steps for your issue above.

**Comment by daveaglick** [comment]
@livarcocc Planning on it, working up a from-scratch repro now and will file once I have a bit more info. Just wanted to drop it in here first since the post above looks related.
