### ISSUE TITLE
Non-deterministic concurrency issues in solutions with multiple projects

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#475]
I'm seeing concurrency issues that occurs when calling `dotnet build SomeProject.sln`. The errors I see do not occur on every build, nor does there seem to be any pattern to when they occur. The errors can occur on first builds after a fresh clone as much as they will occur on second and third builds.

The only thing that seems to be consistent is that it occurs in projects with multiple project references.

The project: [DotNetTools.zip](https://github.com/dotnet/sdk/files/643472/DotNetTools.zip)

Versions:
dotnet-cli 1.0.0-preview4-004215
Windows 10

Detailed log: [msbuild.log.txt](https://github.com/dotnet/sdk/files/643477/msbuild.log.txt)

The errors:

> CSC : error CS2012: Cannot open 'C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\obj\Debug\netcoreapp1.0\Microsoft.DotNet.Watcher.Tools.Tests.dll' for writing -- 'The process cannot access the file 'C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\obj\Debug\netcoreapp1.0\Microsoft.DotNet.Watcher.Tools.Tests.dll' because it is being used by another process.' [C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\Microsoft.DotNet.Watcher.Tools.Tests.csproj]

> C:\dev\Universe\DotNetTools\.dotnet\sdk\1.0.0-preview4-004215\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(119,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.\r [C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\Microsoft.DotNet.Watcher.Tools.Tests.csproj]
C:\dev\Universe\DotNetTools\.dotnet\sdk\1.0.0-preview4-004215\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(119,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\bin\Debug\netcoreapp1.0\Microsoft.DotNet.Watcher.Tools.Tests.runtimeconfig.json' because it is being used by another process.\r [C:\dev\Universe\DotNetTools\test\Microsoft.DotNet.Watcher.Tools.Tests\Microsoft.DotNet.Watcher.Tools.Tests.csproj]

**Comment by fearthecowboy** [comment]
We're seeing this too-a lot. 

It looks like it's rebuilding the same dependent project if multiple projects depend on it. 

Ie, if `A` depends on `B` , `C` , `D`, `E`, `F` and `C` and  `D` and `E` depend on `G` ... we see conflicts.

**Comment by Eilon** [comment]
Hi folks, I was talking to @natemcmaster today and he tried a newer build and this issue didn't repro.

Is this issue officially resolved? Or maybe we just got "lucky" in our build and it happened to succeed?

**Comment by srivatsn** [comment]
No we haven't been able to figure out the root cause. Unless something changed in msbuild - @AndyGerlicher @rainersigwald, you may have just gotten lucky.

**Comment by natidea** [comment]
I'm not able to repro this on new builds either. Will keep a lookout for any similar failures.

**Comment by natemcmaster** [comment]
Same here. Haven't been able to repro in rc3 bits. We can probably close this

**Comment by srivatsn** [comment]
Closing this. Please reopen if you see this again.

**Comment by jaredpar** [comment]
Re-opening. We are seeing this on a virtually daily basis with dotnet/roslyn right now. This issue is tracking it on our side 

https://github.com/dotnet/roslyn/issues/21421

**Comment by jaredpar** [comment]
Ping. This continues to fail a non-trivial number of builds in dotnet/roslyn.

**Comment by nguerrera** [comment]
@jaredpar Is it still the case that you see this only on Mac?

**Comment by nguerrera** [comment]
@jaredpar do roslyn builds save a .binlog? Would it be possible to see one in the failed case? Also, @rainersigwald used https://github.com/rainersigwald/ParallelBuildDebuggingLogger to diagnose the issue that was fixed in #739. A log with that on in the failed case would also help.

**Comment by jaredpar** [comment]
No. I will try and change it to generate binary logs.

**Comment by nguerrera** [comment]
Thanks, that will help a lot.

**Comment by nguerrera** [comment]
Closing this again as the cause of the issues in Roslyn is different than what was fixed for #739, which was almost certainly a dupe of this.

https://github.com/dotnet/roslyn/pull/22232 will fix things for Roslyn

https://github.com/dotnet/sdk/issues/1599 tracks better diagnostics/experience in this explicit-documentation-file-vs-multi-targeting case.
