### ISSUE TITLE
Auto add all reference assemblies for PCL targets

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/sdk#476]
Moving from https://github.com/dotnet/cli/issues/1413

For PCL targets, the user should never have to add a reference assembly and is more consistent with what MSBUILD does for these types of projects.

**Comment by piotrpMSFT** [comment]
See the CLI issue for context. The context was spread across many comments.

**Comment by marcpopMSFT** [comment]
PCLs aren't supported anymore so closing.
