### ISSUE TITLE
ResolvePackageDependencies produces incorrect Resolved paths for project references

### ISSUE THREAD

**Issue by natidea** [dotnet/sdk#479]
ResolvePackageDependencies resolves paths for project references were computed based on the project root, which was originally [based on the location of the project lock file](https://github.com/dotnet/sdk/blob/39b7aba65043f9cb3cb7fce1b7466b5985d3b960/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageDependencies.cs#L429). This needs to be updated or removed since the assets file has moved, and the assets file may contain more appropriate root folder information.

The resolved path for project references is not actually used anywhere currently, so this bug does not cause any problems, but should be fixed anyway.

**Comment by BrunoJuchli** [comment]
Also see #1435 (duplicate) for an example of invalid data.

@natidea could you please update the issue description to include what the actual content of `ResolvedPath` should be? Unless it's being fixed by #1442 already.

**Comment by BrunoJuchli** [comment]
Usages of `ResolvedPath` (not including tests):

- [`Target` _ComputeLockFilesReferences](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L388)
- [`Target` _HandlePackageFileConflicts](https://github.com/dotnet/sdk/blob/a4bceb67b160c72318a581d87d52796e4fa31794/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.ConflictResolution.targets#L40)
-[`Target` ComputeRefAssembliesToPublish](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.PreserveCompilationContext.targets#L67)
-[`Task` ProduceContentAssets](https://github.com/dotnet/sdk/blob/2c5dd65f7314d80a6db98a80078fdcee88286301/src/Tasks/Microsoft.NET.Build.Tasks/ProduceContentAssets.cs#L141)
-[`Task` PreprocessPackageDependenciesDesignTime](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/PreprocessPackageDependenciesDesignTime.cs#L448)

**Comment by nguerrera** [comment]
Fixed by https://github.com/dotnet/sdk/pull/1442
