### ISSUE TITLE
Facades from desktop framework targeting pack are not emitted to .deps.json for PreserveCompilationContext

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#480]
See: https://github.com/dotnet/sdk/issues/111#issuecomment-266103143

After some investigation, the .deps.json file does not list framework references for System.Runtime and friends that do get resolved from .NETFramework\v4.5.2\Facades during build.

This appears to be the root cause of:
* aspnet/Home#1866
* aspnet/Razor#890

@NTaylorMullen

**Comment by nguerrera** [comment]
I tried just editing the deps.json to add these, but I only got so far as getting MVC to dislike my .deps.json. Make sure to actually test the repros listed before declaring this fixed.

**Comment by srivatsn** [comment]
Fixed by #642
