### ISSUE TITLE
"dotnet build" should show build result and timing information at default verbosity level

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#483]
It seems that `dotnet build` is running at a quieter than normal/default MSBUILD verbosity level, meaning usual output like the build result and timing information (like below) isn't shown:

![image](https://cloud.githubusercontent.com/assets/249088/21129189/f0069f20-c0b4-11e6-856c-2ab6309882f7.png)

I think it would be better to stick to the defaults or if possible tune the output to display the information we want for a great default CLI experience.

**Comment by rainersigwald** [comment]
Note that this is independently controllable from overall verbosity via `/consoleloggerparameters:Summary`.

**Comment by srivatsn** [comment]
Moved to https://github.com/dotnet/cli/issues/5110
