### ISSUE TITLE
$(Language) property should be declared in outer build

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#485]
Currently , $(Language) property to detect the compile language of the project is declared in Microsoft.CSharp.CurrentVersion.Targets , and as such is only available in inner build.

Projects shouldn't change languages per TFM, so this property should ideally be available in the outer build.

**Comment by rohit21agrawal** [comment]
@srivatsn could you triage this as appropriate? we need this before RTM too

**Comment by rrelyea** [comment]
I assume this will be RTM now?

**Comment by dsplaisted** [comment]
This would be best handled in the language-specific targets, which live in the MSBuild repo for C# and VB.  So I'm going to move this issue.

**Comment by dsplaisted** [comment]
This issue was moved to Microsoft/msbuild#2101
