### ISSUE TITLE
Rename "cross-targeting" to "multi-targeting"

### ISSUE THREAD

**Issue by mhutch** [dotnet/sdk#486]
Per internal discussion, rename the "cross-targeting" feature to "multi-targeting".

**Rationale**

*Cross-targeting* is easily confused with *[cross-compilation](https://en.wikipedia.org/wiki/Cross_compiler)* which has a well-defined and quite different meaning.

*Multi-targeting* describes the feature very well - the ability for a project to compile for multiple target frameworks. Although it has an existing meaning in MSBuild (the ability for a project to target different frameworks), using it this way this is an expansion of scope, not a redefinition.

**Comment by livarcocc** [comment]
Currently, we have this in a few comments and in a folder of the SDK. As such, I am going to go ahead and close this issue. If we believe that there is still value in updating these, specially the folder, please re-activate.
