### ISSUE TITLE
Add the capability for dotnet-publish to generate a folder structure corresponding to what nuget restore does + corresponding .deps file 

### ISSUE THREAD

**Issue by johanste** [dotnet/sdk#4872]
Today, when running publish, all output ends up smashed flat in the output directory. Given the number of assemblies you typically end up with (assuming you are not doing native compilation), the output ends up being pretty crowded. In addition to making it very hard to find the actual executable, installing two applications in the same directory leads to them violently stomping on each others depedencies.

If you instead could tell publish to produce an output that would mirror the output from a nuget restore of the package and produce a corresponding deps file, you would get avoid the problems listed above with the added bonus of participating in the servicing cache.

**Comment by Forgind** [comment]
Old bug triage:
I don't think this is true anymore? And if I'm wrong, and it still reproduces, let us know, and we can reopen it.
