### ISSUE TITLE
PackageReference to contentFiles pkg breaks compilation of 'net45x' tfms

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#495]
Microsoft.CSharp.Core.targets is picking up a file the contentFiles section of a nuget package and causing the build to fail with this error.

> C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft.CSharp.Core.targets(71,5): error MSB3105: The item "obj\Debug\net45\NuGet\B61134ECB5E801948C09D13980B4CFE1141BB877\Microsoft.Extensions.HashCodeCombiner.Sources\1.2.0-preview1-22911" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [C:\dev\Universe\FileSystem\src\Microsoft.Extensions.FileSystemGlobbing\Microsoft.Extensions.FileSystemGlobbing.csproj]

**Repro:**
Use this feed to get the NuGet package in question: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFrameworks>net45;netstandard1.3</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.HashCodeCombiner.Sources" Version="1.2.0-preview1-22911" PrivateAssets="All" />
    <PackageReference Include="NETStandard.Library" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

I'm using 1.0.0-preview4-004233.

Possibly related to https://github.com/NuGet/Home/issues/3683

**Comment by srivatsn** [comment]
@emgarten is this because we are now generating content file includes statically and we need to stop raising them from the lock file?

**Comment by emgarten** [comment]
I don't think the NuGet change has been integrated into the CLI yet. And I didn't think the current build task was generating the includes for contentFiles. I'm not sure how this is showing up at all.

**Comment by onovotny** [comment]
Not sure if this is related, but `contentFiles` in source-only packages aren't working for me at all right now in RC2. I filed a bug here https://github.com/NuGet/Home/issues/4143

**Comment by natemcmaster** [comment]
@emgarten there was no generated obj/*.nuget.g.props file, but here is the project.assets.json file:

[project.assets.json.txt](https://github.com/dotnet/sdk/files/682821/project.assets.json.txt)

**Comment by natidea** [comment]
The problem was that ProduceContentAssets was not filtering to the active TFM leading to duplicate files in cross targeting projects. Note that since this scenario is now handled by NuGet, this bug will actually be addressed by @emgarten's implementation.
