### ISSUE TITLE
Skip generation of RuntimeConfig.json if it's up to date and there is not runtimeconfig.template.json file

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#496]
See #471 

The target generating RuntimeConfig.json has an Inputs which includes runtimeconfig.template.json, which is often not present, causing the target to always execute.  The file should only be included as an input if it exists, to fix incremental compilation.

**Comment by rainersigwald** [comment]
Including the target name `GenerateBuildRuntimeConfigurationFiles` in this issue since that's what I searched for when I failed to find this and duplicated it as #944.
