### ISSUE TITLE
Remove "SDK" from the name of the SDK

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#498]
Our SDK is called "Microsoft.NET.Sdk" which is restating the obvious in the following:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

</Project>
```

Can we remove Sdk from the name of the Sdk so that we end up with?

``` XML
<Project Sdk="Microsoft.NET">

</Project>
```

**Comment by dsplaisted** [comment]
This is similar to what I proposed in #436.

The thing is, when we support third-party SDKs, they will probably end up being NuGet packages that are acquired via a different mechanism than the normal restore (and possibly placed in a different location).  So it doesn't make sense to publish a NuGet package named "Microsoft.NET" for the SDK.

My suggestion is to prepend "MSBuildSDK" or something similar to the SDK name specified in the attribute to get the corresponding folder name on disk and package name.

**Comment by dasMulli** [comment]
A naming convention would be great to begin with.
The current names are:
```
Microsoft.NET.Sdk
Microsoft.NET.Test.Sdk
Microsoft.NET.Sdk.Web
Microsoft.NET.Sdk.Publish
Microsoft.NET.Sdk.Web.ProjectSystem
NuGet.Build.Tasks.Pack
```

**Comment by srivatsn** [comment]
We are not going to do this at this point.
