### ISSUE TITLE
Import NuGet pack tasks after Microsoft.Common.targets

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#502]
Currently, `Sdk.targets` imports NuGet's pack targets as the very last import in the chain, after Microsoft.Common.targets. (See [Sdk.targets:48-49](https://github.com/dotnet/sdk/blob/d8e9a98dafd629010c13c622a00f72a4343a839e/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets#L48-L49)). This makes more difficult to extend the pack target by using [`PackDependsOn`](https://github.com/NuGet/NuGet.Client/blob/6d9962e541f8b72671e36647dbec097db64e813a/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L43). It also means files specified in `CustomAfterMicrosoftCommonTargets` are applied before NuGet imports pack tasks, as these targets are imported by Microsoft.Common.targets.

**Comment by dsplaisted** [comment]
What if we go back to using a `PackageReference` to get the NuGet pack task?  Then we wouldn't have to lay it out in the CLI and VS, we would acquire it via restore, and the targets would be imported in the right place by NuGet's existing infrastructure.

Are there any downsides to this?

**Comment by natemcmaster** [comment]
I'm going to close this as something we don't need anymore. NuGet made changes to avoid stomping on *DependsOn properties. https://github.com/NuGet/NuGet.Client/pull/1064.
