### ISSUE TITLE
Community edition of NuGet.Build.Tasks.Pack fails to load

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#503]
I got the following error while trying to call /t:pack on AppVeyor:

```
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(73,5): error MSB4062: The "NuGet.Build.Tasks.Pack.PackTask" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\..\Desktop\NuGet.Build.Tasks.Pack.dll. Could not load file or assembly 'NuGet.Build.Tasks.Pack, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\projects\zeroconf\Zeroconf\Zeroconf.csproj]
```

Looking at the error, it says "Could not load file or assembly 'NuGet.Build.Tasks.Pack, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)"

They have the Community edition installed. It seems to work for me locally with Enterprise.

Full build log here:
https://ci.appveyor.com/project/onovotny/zeroconf/build/2.8.1-vs2017.1+26.build.141

Also mentioned it to the @FeodorFitsner at AppVeyor, not sure if there's a corrupt install? Is that error possible? Known issue somewhere?
https://github.com/appveyor/ci/issues/1179#issuecomment-267224670

**Comment by xwipeoutx** [comment]
I'm getting the same issue on Professional 2017.  My 2015 version was Enterprise, FWIW.

I checked the token on that DLL, and it matches
```
>sn -T "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\NuGet.Build.Tasks.Pack\Desktop\NuGet.Build.Tasks.Pack.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key token is 31bf3856ad364e35
```

**Comment by rrelyea** [comment]
@rohit21agrawal - can you please port this issue to NuGet/home/issues as an RC3 issue. Do we have a signing problem?

**Comment by rohit21agrawal** [comment]
someone already filed a related issue on NuGet : https://github.com/NuGet/Home/issues/4122

closing this , move all discussions to the nuget issue.

**Comment by rohit21agrawal** [comment]
temporary workaround can be found as part of comment : https://github.com/NuGet/Home/issues/4122#issuecomment-268135666
