### ISSUE TITLE
CLI tools help md files should be more discoverable

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/sdk#5076]
The .NET CLI repro offers pretty details help in its .md pages. However, the help from the tool itself neither points people to the .md file or gives a detailed version with similar content. For example look at 'dotnet publish --help' vs. [https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-publish](https://github.com/dotnet/cli/tree/rel/1.0.0/src/dotnet/commands/dotnet-publish).

The dotnet tools should either have a '--help:full', or they should provide a link to the online documentation.

**Comment by baronfel** [comment]
You can get detailed online help with the `dotnet help <COMMAND>` command now.
