### ISSUE TITLE
Pack target misses .pri files for Windows targets

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#508]
When using msbuild /t:pack to generate a NuPkg on a multi-targeted project that includes Windows outputs (uap10.0, win8, wpa81, etc) that also contain a `.pri` file, the generated NuSpec used to create the package does not include the `.pri` file. That will lead to errors loading resources.

To repro:
Check out this commit from Zeroconf:
https://github.com/onovotny/Zeroconf/tree/39d47e8fea22a1eb19938392e0bc8f903181cf02

Run the following command `msbuild /t:pack /p:Configuration=Release`

Look at the NuSpec, it's missing the `.pri` files.

**Comment by srivatsn** [comment]
Moved to the NuGet repo.
