### ISSUE TITLE
Pack from csproj does not include the minClientVersion attribute

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#509]
When using the pack command to create a NuPkg from a csproj, the `MinClientVersion` attribute is not written to the generated NuSpec despite being present in the csproj.

**Comment by davidfowl** [comment]
This should be moved to nuget.

**Comment by srivatsn** [comment]
Yes, please file this in https://github.com/NuGet/Home/issues

**Comment by srivatsn** [comment]
I just filed https://github.com/NuGet/Home/issues/4135
