### ISSUE TITLE
Include conflicting dependencies in the warning message

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#517]
At the moment, building a project with Microsoft.NET.Test.Sdk and xunit produces this compiler warning:

> warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

The name of the conflicting assemblies should be included in the error message as it is difficult (1) for beginner users to know how to change the logging verbosity and (2) even for MSBuild pros, digging through **thousands of lines** is onerous.

**Comment by natemcmaster** [comment]
Side note:
In this particular case, the warning appears to be caused by xunit.runner.visualstudio, which requires "Microsoft.Extensions.DependencyModel" 1.0.0 and microsoft.testplatform.testhost which requires 1.0.1, even though that package is not available on NuGet.org.

**Comment by srivatsn** [comment]
That warning is reported by MSBuild and so this should likely be in the msbuild repo. @AndyGerlicher

**Comment by srivatsn** [comment]
Please move this bug to the MSBuild repo.

**Comment by natemcmaster** [comment]
https://github.com/Microsoft/msbuild/issues/608
