### ISSUE TITLE
How to build this repo from scratch on Banana Unix?

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#5171]
Suppose there exists a Banana Unix OS (e.g. some BSD or Solaris like).

On such an OS, how do we build this project fully offline, such that it does not rely on anything from the internet during the build?

```
git clone https://github.com/dotnet/cli
cli/build.sh <what goes here?>
```

Are there required components to build CLI project, which haven't been open sourced yet to accomplish this task? If there are, can we expect them to land on GitHub soon?

---

Before dotnet/cli (in dnx days), we were able to build most of the CoreFX assemblies on FreeBSD and even configured the test runner to work for the successfully built assemblies. Now CLI is a required dependency, we can't build it on FreeBSD nor NetBSD.

Refs: https://github.com/dotnet/corefx/issues/1626, https://github.com/dotnet/coreclr/issues/1633 and https://github.com/dotnet/coreclr/issues/3178

cc @ghuntley, @josteink, @krytarowski and @akoeplinger

**Comment by trungnt2910** [comment]
I am currently working on https://github.com/dotnet/runtime/issues/55803 to add .NET support to Haiku and facing the same problem.

The process to cross-compile CoreCLR (dotnet/runtime) is quite straightforward, but it is not for this repo.

I did manage to get a working .NET SDK on Haiku, but it involves manually editing the RID (from `linux-x64` to `haiku-x64`) in the generated artifact and changing a few version numbers in `Microsoft.NETCoreSdk.BundledVersions.props`.

What is the correct way to cross-compile this repo? It is not clearly documented in the [developer guide](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md).

**Comment by omajid** [comment]
@uweigand @janani66 : can you share your cross-build scripts publicly? Maybe @trungnt2910 can use them to cross-building the entire SDK for this new platform?

**Comment by Sapana-Khemkar** [comment]
> I am currently working on [dotnet/runtime#55803](https://github.com/dotnet/runtime/issues/55803) to add .NET support to Haiku and facing the same problem.
> 
> The process to cross-compile CoreCLR (dotnet/runtime) is quite straightforward, but it is not for this repo.
> 
> I did manage to get a working .NET SDK on Haiku, but it involves manually editing the RID (from `linux-x64` to `haiku-x64`) in the generated artifact and changing a few version numbers in `Microsoft.NETCoreSdk.BundledVersions.props`.
> 
> What is the correct way to cross-compile this repo? It is not clearly documented in the [developer guide](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md).

@trungnt2910 [Here ](https://community.ibm.com/community/user/powerdeveloper/blogs/sapana-khemkar/2023/01/13/cross-build-dotnet7-on-x86-ibm-power) is blog describing how we cross build dotnet on x86 for power and [here ](https://github.com/ppc64le/build-scripts/tree/master/d/dotnet7 )are scripts uploaded. Check if this helps you

**Comment by trungnt2910** [comment]
> > I am currently working on [dotnet/runtime#55803](https://github.com/dotnet/runtime/issues/55803) to add .NET support to Haiku and facing the same problem.
> > The process to cross-compile CoreCLR (dotnet/runtime) is quite straightforward, but it is not for this repo.
> > I did manage to get a working .NET SDK on Haiku, but it involves manually editing the RID (from `linux-x64` to `haiku-x64`) in the generated artifact and changing a few version numbers in `Microsoft.NETCoreSdk.BundledVersions.props`.
> > What is the correct way to cross-compile this repo? It is not clearly documented in the [developer guide](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md).
> 
> @trungnt2910 [Here ](https://community.ibm.com/community/user/powerdeveloper/blogs/sapana-khemkar/2023/01/13/cross-build-dotnet7-on-x86-ibm-power) is blog describing how we cross build dotnet on x86 for power and [here ](https://github.com/ppc64le/build-scripts/tree/master/d/dotnet7)are scripts uploaded. Check if this helps you

Thanks for the guide, but the problem I'm dealing with is entirely different (different OS, same architecture, instead of same OS (Linux), different architecture).

I tried:
```
 ./build.sh --pack /p:OSName=haiku
```

because of this: https://github.com/dotnet/sdk/blob/86db944afd9699903751a860de819a01c77b176c/src/Layout/redist/targets/GetRuntimeInformation.targets#L6-L9

but still got `linux-x64` instead of `haiku-x64`.

**Comment by Sapana-Khemkar** [comment]
> > > I am currently working on [dotnet/runtime#55803](https://github.com/dotnet/runtime/issues/55803) to add .NET support to Haiku and facing the same problem.
> > > The process to cross-compile CoreCLR (dotnet/runtime) is quite straightforward, but it is not for this repo.
> > > I did manage to get a working .NET SDK on Haiku, but it involves manually editing the RID (from `linux-x64` to `haiku-x64`) in the generated artifact and changing a few version numbers in `Microsoft.NETCoreSdk.BundledVersions.props`.
> > > What is the correct way to cross-compile this repo? It is not clearly documented in the [developer guide](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md).
> > 
> > 
> > @trungnt2910 [Here ](https://community.ibm.com/community/user/powerdeveloper/blogs/sapana-khemkar/2023/01/13/cross-build-dotnet7-on-x86-ibm-power) is blog describing how we cross build dotnet on x86 for power and [here ](https://github.com/ppc64le/build-scripts/tree/master/d/dotnet7)are scripts uploaded. Check if this helps you
> 
> Thanks for the guide, but the problem I'm dealing with is entirely different (different OS, same architecture, instead of same OS (Linux), different architecture).
> 
> I tried:
> 
> ```
>  ./build.sh --pack /p:OSName=haiku
> ```
> 
> because of this:
> 
> https://github.com/dotnet/sdk/blob/86db944afd9699903751a860de819a01c77b176c/src/Layout/redist/targets/GetRuntimeInformation.targets#L6-L9
> 
> but still got `linux-x64` instead of `haiku-x64`.

ohh.. seems some other issue. I did not face this.

**Comment by trungnt2910** [comment]
The current .NET SDK build procedure uses some files, namely `Microsoft.NETCoreSdk.BundledVersions.props`, from the old SDK and then [patches](https://github.com/dotnet/sdk/blob/010f7ef42fc8e05f17f8137fb3605936887fe990/src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs) the files. The patch replaces the existing versions with a [hard coded](https://github.com/dotnet/sdk/blob/010f7ef42fc8e05f17f8137fb3605936887fe990/eng/Versions.props#L48) one and uses the existing runtime identifier of the host SDK.

To cross compile the SDK for Haiku, I had to replace the hard coded .NET runtime version with the one I recently built. I also had to replace the runtime identifier from `linux-x64` to `haiku-x64`. The full code for this process is [here](https://github.com/trungnt2910/dotnet-builds/blob/5ef063d6049a1b26686c007d93bf16b219b6626f/.github/workflows/build.yml#LL104C1-L135C1).

It would be nice if `Versions.props` could be overridden, and also nice if `OverrideAndCreateBundeldNETCoreAppPackageVersion` could override the RID based on the `OSName` property.

**Comment by trungnt2910** [comment]
There is also a scarcely documented [source-build](https://github.com/dotnet/sdk/blob/010f7ef42fc8e05f17f8137fb3605936887fe990/eng/common/build.sh#LL22C3-L22C3) mode, but this mode does not seem to create enough files for the SDK to function. It seems to be related to the source build feature, which currently only supports Linux.

**Comment by baronfel** [comment]
Most actual building of an SDK for any OS should happen in the dotnet/installer repo, or in the dotnet/dotnet repo for .NET 9+.  That's where all of the actual bundle construction occurs - this repo is focused on the _logic_ of the SDK specifically.
