### ISSUE TITLE
Project only builds on command line if first built in VS 2017 RC.2

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#518]
In some projects, executing 'dotnet build' succeeds only if if the project is first built from within VS 2017 RC.2.

Error on command line:

> C:\Users\namc\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(211,5): error MSB4018: The "GenerateSatelliteAssemblies" task failed unexpectedly.\r [C:\dev\Universe\Razor\test\Microsoft.AspNetCore.Razor.Runtime.Test\Microsoft.AspNetCore.Razor.Runtime.Test.csproj]
C:\Users\namc\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(211,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\dev\Universe\Razor\test\Microsoft.AspNetCore.Razor.Runtime.Test\System.Runtime'.\r [C:\dev\Universe\Razor\test\Microsoft.AspNetCore.Razor.Runtime.Test\Microsoft.AspNetCore.Razor.Runtime.Test.csproj]

**Repro:**
https://github.com/aspnet/Razor/blob/namc/sdk-issue-518/test/Microsoft.AspNetCore.Razor.Runtime.Test/Microsoft.AspNetCore.Razor.Runtime.Test.csproj

[Razor-namc-sdk-issue-518.zip](https://github.com/dotnet/sdk/files/657901/Razor-namc-sdk-issue-518.zip)

`dotnet msbuild /t:Build /fl /flp:LogFile=msbuild.log`
Full log with error: [msbuild.log.txt](https://github.com/dotnet/sdk/files/657913/msbuild.log.txt)

Full log after building with VS 2017: [msbuild.log.txt](https://github.com/dotnet/sdk/files/657920/msbuild.log.txt)

**Details**

Using VS 2017 15.0.26009.0, dotnet-CLI 1.0.0-preview4-004233

**Comment by natemcmaster** [comment]
Investigating further: it appears it has something to do with embedding files in this folder: https://github.com/aspnet/Razor/blob/namc/sdk-issue-518/test/Microsoft.AspNetCore.Razor.Runtime.Test/TestFiles/

Still weird that it builds in VS, but not dotnet-CLI.

**Comment by srivatsn** [comment]
Is this a case of the x-plat msbuild not supporting something that the desktop msbuild does? @rainersigwald @cdmihai?

**Comment by cdmihai** [comment]
AFAIK, `GenerateSatelliteAssemblies` is implemented via `AL.exe` on full framework and is overwritten on .net core sdk with a managed implementation. Maybe the resources contain some feature supported only by `AL.exe`?

**Comment by Faizan2304** [comment]
+1

**Comment by Faizan2304** [comment]
Is there any workaround for this issue??

**Comment by nguerrera** [comment]
See also https://github.com/dotnet/cli/issues/5171 for more repro steps.

**Comment by nguerrera** [comment]
This was already fixed as part #507. I have verified that by overlaying latest .NET SDK in to the CLI Sdks folder that the build of the repro project succeeds. However, the CLI needs to take a new SDK in order for this fix to flow. VS already has the fix but CLI does not. I'm going to close this and reopen dotnet/cli#5171 to track getting the SDK updated in the CLI.

**Comment by Faizan2304** [comment]
I am seeing this issue repro on latest dotnet
.NET Command Line Tools (1.0.0-preview5-004478)
Product Information:
Version: 1.0.0-preview5-004478
Commit SHA-1 hash: 4d3e287
Runtime Environment:
OS Name: Windows
OS Version: 10.0.14393
OS Platform: Windows
RID: win10-x64
Base Path: C:\Users\faahmad\Desktop\dotnet-dev-win-x64.latest\sdk\1.0.0-preview5-004478

**Comment by Faizan2304** [comment]
Ignore last comment: My bad. Things are working fine. I was using old Microsoft.Net.sdk
