### ISSUE TITLE
SDK target for dotnet pack

### ISSUE THREAD

**Issue by mavasani** [dotnet/sdk#524]
We set `GeneratePackageOnBuild = true` in the project system when user wants to generate package on build. Additionally, we have a new command "Pack", which should invoke dotnet pack. We should define a new SDK target that performs dotnet pack and invoke this target when this property is set to true.

**Comment by srivatsn** [comment]
There's already a pack target that's brought in by the NuGet Pack package. I think that package already makes Pack run after build. It should make that happen always if GeneratePackageOnBuild=true. Can you move this bug to the NuGet repo?
