### ISSUE TITLE
PackageReference should support DevelopmentDependency metadata

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#529]
`msbuild /t:pack` fails when building a stable versioned package that depends on an unstable one, even though that unstable one is a DevelopmentDependency:

1. Create .NET Core console app
1. Add this package reference
   ```xml
   <PackageReference Include="Nerdbank.GitVersioning" Version="1.5.28-rc" developmentDependency="true" />`
   ```
1. Pack the project with `msbuild /t:pack`

Build fails with a crashed MSBuild task with this message:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(73,5): error MSB4018:
 The "PackTask" task failed unexpectedly.\r [C:\Users\andre\OneDrive\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(73,5): error MSB4018: System.IO.InvalidDataException: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Nerdbank.GitVersionin
g [1.5.61-ga5f362ccc1, )" or update the version field in the nuspec.\r [C:\Users\andre\OneDrive\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]

In fact I shouldn't even have to specify `DevelopmentDependency="true"` in my reference because the nuspec of the referenced package itself has that property set.

**Comment by nguerrera** [comment]
@emgarten @rrelyea I think this should move to https://github.com/nuget/home. The pack target is not implemented in this repo.

**Comment by AArnott** [comment]
Sounds good to me. I've migrated it to: https://github.com/NuGet/Home/issues/4125
