### ISSUE TITLE
Multi-targeting build does not surface inner errors when tasks fail

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#531]
In the attached project, I'm trying to build it with `msbuild /t:restore;build` on Windows (with all of the Xamarin stuff installed). The problem is that the Xamarin targets are reporting warnings (for some reason?) and while they appear to build ok and produce output dll's, the Sdk build reports it as failed and thus fails the build.

[Microsoft.Identity.Client.zip](https://github.com/dotnet/sdk/files/659535/Microsoft.Identity.Client.zip)

```
Done Building Project "C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (Build target(s)) --
 FAILED.

Done Building Project "C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (build target(s)) --
 FAILED.


Build FAILED.

"C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (build target) (1) ->
"C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (Build target) (1:8) ->
(_GetPrimaryCpuAbi target) ->
  C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(308,2): warning : One or more
 errors occurred. [C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj]


"C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (build target) (1) ->
"C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity.Client.csproj" (Build target) (1:9) ->
(_SayHello target) ->
  C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(63,5): warning VSX1000: The project Micr
osoft.Identity.Client was built while disconnected from a Mac agent, so only the main assembly was compiled. Connect to
 a Xamarin Mac build agent to build the full application. [C:\dev\msal\src\Microsoft.Identity.Client\Microsoft.Identity
.Client.csproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.01
```

**Comment by onovotny** [comment]
Dug some more. The underlying issue is that the ConvertPdb2Mdb task failed on the inner loop. There's no errors from there surfaced to the top-level build.

This happens on the iOS target. You can see this more directly by removing `TargetFrameworks` and just setting `<TargetFramework>Xamarin.iOS</TargetFramework>`. When you run that build, MSBuild.exe crashes with an OOM due to the task failing. This error should be surfaced to the main build when run as part of the `DispatchToInnterBuilds` task.

Beyond that, the actual error was caused by the ConvertPdb2Mdb task not supporting Portable PDB's. Setting `<DebugType>full</DebugType>` in the iOS property group solved the issue. Not sure where that bug should go.

**Comment by rrelyea** [comment]
FYI - don't think that msbuild /t:restore;build is supported.
we need to restore first. then build.
because the restore can bring in the props/targets from packages, we need to build with a newly evaluated project - that now includes these props/targets.

msbuild /t:restore
msbuild /t:build

/cc @emgarten

**Comment by onovotny** [comment]
@rrelyea makes sense, but I wonder if that combo can be detected and a new msbuild task/instance/whatever can be spun out for the build target so things get re-evaluated?

**Comment by emgarten** [comment]
It would need to be re-evaluated, this has been discussed but I'm not sure if it has happened yet.

**Comment by srivatsn** [comment]
@onovotny can you file a separate bug for allowing restore;build?

**Comment by dsplaisted** [comment]
I think the issue here was that the inner build was getting an out of memory exception, which wasn't being reported cleanly.  I believe "normal" errors from the inner builds should be reported correctly.
