### ISSUE TITLE
Single-targeting net20 results in MSB4086

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#533]
_From @jnm2 on December 17, 2016 21:0_

With `<TargetFramework>net20</TargetFramework>`, you get MSB4086:

> A numeric comparison was attempted on "$(_TargetFrameworkVersionWithoutV)" that evaluates to "" instead of a number, in condition " '$(_TargetFrameworkVersionWithoutV)' >= '4.5' ".
>
> _(C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.BeforeCommon.targets, line 86)_

With `<TargetFrameworks>net20</TargetFrameworks>` all is well.

Build 15.0.26014.0

_Copied from original issue: dotnet/roslyn-project-system#989_

**Comment by nguerrera** [comment]
@jnm2 Can you please provide the full contents of the csproj that triggers this?

I do not see a repro using this:
``` xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net20</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
</Project>
```

**Comment by jnm2** [comment]
@nguerrera Figured out the repro. Create a .csproj with:

```c#
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFrameworks>net20</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
</Project>
```

Open in Visual Studio and build the project. While Visual Studio is open, change the .csproj to `<TargetFramework>net20</TargetFramework>` in an external editor and save. Come back to Visual Studio and build again. The error shows up.

**Comment by srivatsn** [comment]
This sounds like a VS issue in refreshing the project. @natidea

**Comment by srivatsn** [comment]
Switching from a TF to TFs or vice versa causes the project system to get into a bad state. https://github.com/dotnet/roslyn-project-system/issues/1226 tracks the issue. Closing in favor of that.
