### ISSUE TITLE
Verify Publish when DisableImplicitFrameworkReferences and DisableLockFileFrameworks are false

### ISSUE THREAD

**Issue by natidea** [dotnet/sdk#536]
Currently we [disable getting framework references](https://github.com/dotnet/sdk/blob/658d35f488bce364e13e4146bab558cf8b5a4f13/test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPreserveCompilationContext.cs#L37) implicitly or from lock file in publish tests targeting .NET framework. This is pending https://github.com/Microsoft/msbuild/issues/1345 . But even when the MSBuild issue is fixed, we may still observe the same error if there is a reference to the same framework assembly coming both from a NuGet FrameworkReference and the implicit framework references from the SDK.

One solution may be to disable the implicit framework references if targeting .NET 4.5 or greater (which is the lowest thing supported by .NET Standard),

**Comment by dsplaisted** [comment]
It looks like the workaround for this was already removed.
