### ISSUE TITLE
Set RestoreProjectStyle property to PackageReference in the SDK

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#537]
With the fix to https://github.com/NuGet/Home/issues/4046, we can set the `RestoreProjectStyle` property to `PackageReference` instead of our [current workaround](https://github.com/dotnet/sdk/blob/8204b6b1f3ff2f9717c5d66ab903795271de2e9c/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L225-L231).  We should make this change once that update flows into MSBuild and the .NET CLI that we use.

**Comment by emgarten** [comment]
It would be nice to get this in for RC3
