### ISSUE TITLE
Support msbuild /t:restore;build gesture

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#541]
Splitting from https://github.com/dotnet/sdk/issues/531

Today you have to explicitly do two commands for a proper build:
- `msbuild /t:restore`
- `msbuild /t:build`

It would be easier and more intuitive if the SDK could combine those to enable:
`msbuild /t:restore;build`, `msbuild /t:restore;pack` or even simply implicitly call restore (unless opted out with a variable?). 

It's true that the build may have to re-evaluate itself after the restore since additional props/targets may be imported, but somehow this should be made to work.

**Comment by davidfowl** [comment]
We've been discussing what it would take to treat restore like a build dependency so that it's fully incremental and does everything at the required times. That would eliminate the need for running more than a single command.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4329
