### ISSUE TITLE
For Migrate solutions, switching to specific project in Debug options in Tool bar, will cause error when clicking "Debug" button 

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/sdk#542]
Clone repo from https://github.com/balaTest/ProjectKTestProjects to your machine and extract it.
Testing solutions under: ProjectKTestProjects-master\Dev14_K101\Tooling20
1)	test "AspNetCoreWeb_IndAuth_WithAI_1"
- Double click the .sln file and see migration log 
- Auto restore succeeded with no error or warning;
- Click the down list of debug and change "IIS Express" to "AspNetCoreWeb_IndAuth_WithAI_1";
**Actual Result:**
- click the debug icon on tools bar and prompt up an error "Object reference not  set to an instance of an object"
![clickdebugiconpromptobjectreferenceerror](https://cloud.githubusercontent.com/assets/22901391/21375572/69ebdd40-c769-11e6-85b1-fe76a6f30506.jpg)
**Expected Result:** 
    Click the debug icon and run passed with no error.

- The issue also happens in the following 6 solutions under ProjectKTestProjects-master\Dev14_K101\Tooling20:  
2)	AspNetCoreWebApp_NoAuth_1
3)	AspNetCoreWebApp_OnCore_Empty_1
4)	ClassLibraryOnNetStd16_1
5)	ConsoleAppOnCore_1
6)	EFGetStarted.AspNetCore.NewDb
7)	MvcMovie
and 1 solution under \ProjectKTestProjects-mast\Dev14_KRtw\KRTW-final:
8)	SimpleTypeScriptSample1

**Product Version**
- VS : VisualStudio/15.0.0-RC.2+26017.1.d15prerel 
- CLI: 1.0.0-preview4-004233

**Comment by srivatsn** [comment]
Sounds like an issue in the web tooling. @MiaomiaoHuangfu can you open in the web tooling database? /cc @mlorbetske

**Comment by MiaomiaoHuangfu** [comment]
close the issue and filed this on the web team in the internal database: https://devdiv.visualstudio.com/DevDiv/_workitems?id=362101&fullScreen=false&_a=edit
