### ISSUE TITLE
Test targets need to be part of main SDK

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#546]
Right now, it seems the only way to invoke unit test projects via the test platform is to use `dotnet test` on the project file. The problem is that forces the CoreCLR version of the Build tasks and not all tasks work on CoreCLR.

For example:
https://github.com/Reactive-Extensions/Rx.NET/blob/f339ba7c0821d00f9c0cb29186c97713765a6d03/Rx.NET/Source/Tests.System.Reactive/Tests.System.Reactive.csproj

I cannot simply run `dotnet test` on that because the GitVersionTask is .NET Desktop only. That's fine for building, but I then need a way to invoke the test platform once per target framework with the right parameters.

It should do whatever dotnet test is...I think it's going to vstest.console /Framework: ... with the supported frameworks.

It seems that `Microsoft.TestPlatform.targets` is in the CLI build but not in the main SDK. It should be in the main SDK for use with msbuild.

**Comment by jaredpar** [comment]
Related issue https://github.com/Microsoft/msbuild/issues/1499

**Comment by srivatsn** [comment]
@dotnet/vstest This is a request for running tests using the desktop msbuild - a msbuild /t:Test.

**Comment by pvlakshm** [comment]
We've added this ask to backlog. However we will likely get to it post RTM.

**Comment by onovotny** [comment]
This really needs to be in 1.0...otherwise, given that these targets are distributed with VS 2017 and not via NuGet, it'll need to wait for Update 1, wont' it?. We need a coherent unit test strategy out-of-the-box.

**Comment by codito** [comment]
We're considering the option to pull the target/task into a nuget package or use the existing `Microsoft.NET.Test.Sdk`.

**Comment by gulbanana** [comment]
It really is not good enough if we get to RTM with the test sdk still closed source and semi-functional (yet not third-party extensible!). The testing story isn't an optional part of a modern platform.

**Comment by srivatsn** [comment]
This issue was moved to Microsoft/vstest#387
