### ISSUE TITLE
ASP.NET core project build requires transitive project references.

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/sdk#547]
This is with the latest VS2017RC update as of Dec 22.

1. Create a new empty solution.
2. Add an "Empty" ASP.NET Core Web Application (.net framework) project "WebApp".
3. Add a new Class Library (.NET Frameworkd) "LibA".
4. Add a new Class Library (.NET Frameworkd) "LibB".
5. Add a reference from WebApp to LibA.
6. Add a reference from LibA to LibB.

Building WebApp results in the following error message:

> Cannot find project info for 'c:\users\...\Solution1\LibB\LibB.csproj'. This can indicate a missing project reference.	WebApp	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	82	

If I add a reference from WebApp to LibB it builds without error.

In my real-world scenario I want to have my WebApp reference one specific project and not add the dozen other transitive project references that exist in my solution. I specifically want to avoid accidentally referencing types in those assemblies.

This scenario worked before, if that helps argue the point.

**Comment by srivatsn** [comment]
This should now be fixed with https://github.com/dotnet/sdk/pull/478
