### ISSUE TITLE
Signing does not work on non-Windows

### ISSUE THREAD

**Issue by 333fred** [dotnet/sdk#55]
When signing on non-Windows platforms, we get output something like:
`error CS7027: Error signing output with public key from file '/Users/livarcocc/Documents/git/core-sdk/build/Targets/../Strong Name Keys/RoslynInternalKey.Private.snk' -- Assembly signing not supported.`
Once signing is supported on non-Windows, remove the condition in Common.props.

**Comment by nguerrera** [comment]
This is tracked by dotnet/roslyn#8210. There's no work required in the SDK. Once csc works with the flag x-plat, we will automatically work too.

**Comment by nguerrera** [comment]
(I'm fixing our own use to public-sign on *nix, which is good enough.)

**Comment by Jonathan34** [comment]
I believe this is related to: https://github.com/dotnet/cli/issues/6911 but i fail to see the workaround or resolution for that.
