### ISSUE TITLE
Discussion: CLI tools vs Build Dependencies

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sdk#553]
Taking this convo to GitHub from  https://twitter.com/terrajobst/status/813923762961674240

Seems to be a bit of confusion over what a CLI tool is, what its intent is and how it might be different from a build-only dependency. 

Many tools may need to be called as part of the build pipeline or be standalone. For example what is xunit? It maybe a standalone command that can run unit tests for a project. But it may also want to override/augment the /t:Test target and need a way to get in the pipeline.

@terrajobst and @bradwilson can add more...

/cc @yishaigalatzer @natemcmaster

**Comment by yishaigalatzer** [comment]
Tools are a way to make an executable available. That's the start and end of it, it can be a global or a project specific thing. Targets can consume it, the concept for introducing targets exists it's the good old regular package. 

Let's not keep mixing up concepts and end up with a soup of everything is the same (or at that point remove the concept of tools all together because they are the same).

There is an issue of how does one support tools inside a build target (i.e. how do I guarantee a tool is available for my target to run). I think that is a valid but separate concern.

**Comment by bradwilson** [comment]
Let's pretend "dotnet test" doesn't exist. What is the xUnit runner for .NET CLI in this world? Tool or package? How do users run it, passing in command line arguments? He sure it know about the test projects in the solution? Target frameworks?

**Comment by bradwilson** [comment]
Or to put it another way: How do I implement "dotnet test", without baking myself into dotnet.exe?

**Comment by yishaigalatzer** [comment]
Just my opinion on the matter: it's a regular package that runs by msbuild /t:test.

It may bring a tool using the tools section (or install it globally, or if the feature is supported adds a tool ref)

**Comment by yishaigalatzer** [comment]
I'd love to hear other opinions on this though...

**Comment by natemcmaster** [comment]
@bradwilson lots of good questions. As @yishaigalatzer suggests, you could implement a test runner as an MSBuild target that is installed via `PackageReference`. 

This isn't the only option, though. You could also build an xunit test runner as a CLI tool that would be installed via `DotNetCliToolReference`. For an example of the basic pieces of this implementation, see https://github.com/natemcmaster/dotnet-xunit.

And, thirdly, you could also implement something in between that requires both CLI tool reference and package references. (Example: dotnet-ef and dotnet-test itself.) 

There are pros and cons of each approach, so it is hard to prescribe general advice. But as a starting point, consider this: is the desired command line UX `dotnet msbuild /t:XunitTest` or `dotnet xunit`?

**Comment by bradwilson** [comment]
Thanks! I'll take a closer look this weekend, but this sounds like exactly what I was after. :)
