### ISSUE TITLE
Implement dotnet cache

### ISSUE THREAD

**Issue by ramarag** [dotnet/sdk#554]
### `dotnet cache` Implementation steps
- [x] Enable [`dotnet cache` shim](https://github.com/dotnet/cli/issues/5161) for the `cache` target and the command line switch in the CLI
- [x] Implement the `cache` build target. i.e., allow  target to be `restore`-ed into output directory 
- [x] Layout the files into the appropriate output folder 
- [x] Integrate the feature with crossgen with appropriate error codes
- [x] Parse and filter the appropriate assets (*a la* `publish`) for the input packages and the target RID
     - [x] Native assets
     - [x] Resource assets  
- [x] Enable an end to end test
- [x] Clean up temp directories and files
- [x] Allow multiple packages.proj file to be specified on the command line

**Comment by gkhanna79** [comment]
CC @schellap
