### ISSUE TITLE
Pacman package for Arch based distros

### ISSUE THREAD

**Issue by TurkeyMan** [dotnet/sdk#5543]
Please consider a PKGBUILD to package for pacman/Arch based Linux distros.
Many developers prefer Arch, the package repository is typically much better than *buntu, and more up-to-date.

**Comment by baronfel** [comment]
Closing with great joy as there are now a number of dotnet packages in AUR: https://aur.archlinux.org/packages?O=0&SeB=nd&K=dotnet&outdated=&SB=p&SO=d&PP=50&submit=Go
