### ISSUE TITLE
Create a new ASP.NET Core Web Application (.NET Core) project, build the solution succeeded but not generate "[projectName].runtimeconfig.dev.json" and "[projectName].runtimeconfig.json"

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/sdk#557]
Create a new ASP.NET Core Web Application (.NET Core) project, build the solution succeeded but not generate "[projectName].runtimeconfig.dev.json" and "[projectName].runtimeconfig.json".

Repro build: d15prerel.26022.05 & d15prerel.26027.00

**Comment by nguerrera** [comment]
This should be fixed by https://github.com/aspnet/websdk/pull/87 and https://github.com/aspnet/Templates/pull/774
