### ISSUE TITLE
Fat Portable apps not publishing native assets.

### ISSUE THREAD

**Issue by ramarag** [dotnet/sdk#559]
If we publish a fat portable app, we expect the rids specified in the project to be published under  rid split folders in the app bin directory.

This bug is present in both project.json based cli and msbuild based cli

dotnet --info
```
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```
cc @schellap @gkhanna79 @livarcocc @nguerrera @dsplaisted @eerhardt  @piotrpMSFT @srivatsn 

Sample project.json : 
```{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": { 
      "Microsoft.NETCore.CoreDisTools": "1.0.1-prerelease-00001",
  "System.Runtime.Serialization.Json": "4.4.0-beta-24821-02"},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  },
"runtimes": {
    "win7-x86": {},
    "win7-x64": {},
    "ubuntu.14.04-x64": {},
    "osx.10.10-x64": {},
    "centos.7-x64": {},
    "rhel.7-x64": {},
    "debian.8-x64": {}
  }
```

**Comment by nguerrera** [comment]
@ramarag Please clarify with full repro steps and spell out which files you expect to be somewhere that aren't.

**Comment by ramarag** [comment]
when the app is published:

bin\debug\<tfm>\publish\<managed_assets>
bin\debug\<tfm>\publish\<rid>\<native_assets>

that is 
bin\debug\<tfm>\publish\win7-x64\coredistools.dll
bin\debug\<tfm>\publish\ubuntu.14.04-x64\libcoredistool.so
bin\debug\<tfm>\publish\osx.10.10-x64\libcoredistool.dylib
bin\debug\<tfm>\publish\centos.7-x64\libcoredistool.so
bin\debug\<tfm>\publish\rhel.7-x64\libcoredistool.so
bin\debug\<tfm>\publish\debian.8-x64\libcoredistool.so

**Comment by nguerrera** [comment]
This works already. Native assets go to `publish\<rid>\native\`
