### ISSUE TITLE
Use apphost.exe for app-base application activations

### ISSUE THREAD

**Issue by schellap** [dotnet/sdk#562]
This is a port of the CLI issue: https://github.com/dotnet/cli/issues/3850

## Steps to reproduce

```
dotnet new
# Edit project manifest to be standalone
dotnet build
dotnet publish
```
## Expected  behavior
1. The executable should instead instead be apphost.exe
2. Replace the below string bytes in apphost.exe to `"appname.dll\0"`, (this can be done in managed code as well)

`c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2`

Sample code that replaces the string is present in this commit: dotnet/core-setup@b391644

## Actual behavior

The binary executable is dotnet.exe host.
## Environment data

`dotnet --info` output:

**Comment by schellap** [comment]
After PR https://github.com/dotnet/core-setup/pull/711 goes in, for standalone applications apphost.exe needs to be used. Sample code that replaces the string is present in this commit: https://github.com/dotnet/core-setup/pull/711/commits/b391644b5832dbd507ee2a97c24ffb9fe4aca3cd

**Comment by schellap** [comment]
Cc @gkhanna79 @piotrpMSFT @livarcocc @nguerrera @dsplaisted

**Comment by schellap** [comment]
When doing so, I would suggest that the SDK be backwards compatible something along the lines of: when `dotnet.exe` is present, then use `dotnet.exe`. When absent, look for `apphost.exe`. This is because when https://github.com/dotnet/core-setup/issues/217 is fixed, `dotnet.exe` will no longer be present in the closure.

**Comment by gkhanna79** [comment]
@ramarag I take it this is complete with your recent feature work?

C @eerhardt

**Comment by ramarag** [comment]
fixed by https://github.com/dotnet/sdk/pull/978

we first look for apphost.exe and if we do not  find it, we default to dotnet.exe
