### ISSUE TITLE
ResolvePackageDependencies doesn't set same metadata as ResolveNuGetPackageAssets

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#567]
ResolveNuGetPackageAssets set `NuGetPackageId` and `NuGetPackageVersion` metadata but ResolvePackageDependencies does not.  Seems like it should if it is replacing it.  I know of a few folks that depend on this metadata being set.

/cc @jasonmalinowski @natidea 

See https://github.com/NuGet/NuGet.BuildTasks/blob/4a57a0ef4bee31f122d50a39fe3dddd4ca03fb07/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L851-L852

**Comment by natidea** [comment]
See my comment in https://github.com/dotnet/sdk/issues/568#issuecomment-270223099 . This metadata can be set downstream as needed. The package name and version are currently set as metadata on the `PackageDefinitions` item. (We avoided using NuGet-specific metadata names so this could be extended to other packaging systems.)

**Comment by ericstj** [comment]
I need that metadata for doing conflict resolution.  See https://github.com/dotnet/standard/blob/4392c75933f08108615699038b057389a37c7c4c/netstandard/tools/HandlePackageFileConflicts.cs#L140.  For now I just parsed out `ParentPackage` metadata, but I want to make sure I'm depending on something explicit and public that will not break in the future.

I don't think it makes sense for this metadata to be added downstream since `ResolvePackageDependencies` already has this data (Id & Version) and is in fact the source of it.  That's different than #568 where one might argue that its adding data on top of the items through an independent algo.

**Comment by ericstj** [comment]
Actually you aren't even preserving the ParentPackage metdata in the Reference items so the code I pointed to is broken.  The only way we can get this information back out is to try and parse the path.  That's not acceptable.  Please preserve package ID and version on Reference and ReferenceCopyLocalPaths.  This is not a "feature" it is a regression from NuGet 3.

**Comment by natidea** [comment]
I see. Yes when we create Reference items, we copy data from FileDefinitions into a temporary item to make resolved path the itemspec, but we are not copying those fields. I can add those fields.

**Comment by ericstj** [comment]
Thank you for fixing this @natidea.  This will help the perf of our build tasks since they'll no longer need to enumerate the filesystem to find the nuspec.
