### ISSUE TITLE
Customized BaseIntermediateOutputPath led to compilation error

### ISSUE THREAD

**Issue by lextm** [dotnet/sdk#570]
I checked #329 and #246 but they do not show what might be the solution for this issue.

I was able to compile a .NET Standard project and its unit test project successfully,

This is an open source project at https://github.com/lextm/sharpsnmplib

1. Clone and check out master.
1. Launch SharpSnmpLib.NetStandard.sln to compile the .NET Standard 1.3 project first in Visual Studio 2017 RC.

But since I met another issue https://github.com/NuGet/Home/issues/4154 which some Microsoft guy suggested I use a customized value of `BaseIntermediateOutputPath` in csproj as workaround.

I can see that by adding `<BaseIntermediateOutputPath>obj1\</BaseIntermediateOutputPath>` to the .NET Standard project it stores (`dotnet restore`) and compiles (`dotnet build`) without any problem.

However, for the unit test project (which is a .NET Core console project), adding this line leads to a compilation error in `dotnet build`,
```
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\Users\lextm\Downloads\sharpsnmplib\Tests\Tests.NetStandard.csproj]
```
It seems that some part of the compilation does not honor the customized value, and hope it can be fixed.

**Comment by srivatsn** [comment]
@codito @singhsarab @dotnet/vstest - I believe the Test SDK generates a file with the main method in the baseintemeridateoutputpath. Are you using the property to do that?

**Comment by pvlakshm** [comment]
Unable to reproduce this in a simple hello world app with `BaseIntermediateOutputPath` set. By the way, Test Sdk uses `IntermediatePath` for generated entrypoint.

@lextm can you share a verbose log if possible?

**Comment by srivatsn** [comment]
This issue was moved to Microsoft/vstest#388
