### ISSUE TITLE
Deleted files in webroot are not removed on publish

### ISSUE THREAD

**Issue by GuardRex** [dotnet/sdk#573]
## Steps
1. Use any project with a webroot (`wwwroot`)
2. Place a file in the content root `wwwroot` folder (e.g., `dummy.txt`)
3. `dotnet publish` the app
4. Note `dummy.txt` is in the `wwwroot` folder of the published output
5. Delete the `dummy.txt` file from the content root `wwwroot` folder
6. Republish the app

## Expected Behvaior
* The `dummy.txt` file is removed from the published `wwwroot` folder.

## Actual Behavior
* The `dummy.txt` file remains in the published `wwwroot` folder.

```
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

**Comment by davidfowl** [comment]
`dotnet publish` is stateless, and doesn't have any logic to propagate deletes. You could use https://github.com/projectkudu/KuduSync.NET
