### ISSUE TITLE
Convert "GetAssemblyVersion" target into static computation

### ISSUE THREAD

**Issue by mavasani** [dotnet/sdk#574]
[GetAssemblyVersion](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets#L119) is currently a Target, which means that it won't be executed as part of Evaluations in the project system trying to get the default value for AssemblyVersion/FileVersion. This forced us to clone this target implementation in the project system.

@davkean and @srivatsn recommended that we convert this target into static parsing property function that just performs string manipulation, which will allow us to get rid of the cloned functionality in the property provider and get the correct default value from evaluations.

**Comment by onovotny** [comment]
What impact would this have on targets that want to manipulate the version used for AssemblyVersion? I'm thinking of GetVersionTask and Nerdbank.Versioning.

**Comment by dsplaisted** [comment]
@srivatsn @davkean Do we still need this or does the project system now call the target to get the value?

**Comment by davkean** [comment]
We can't call the target to get the value, we're inside a project lock when we need this.

**Comment by livarcocc** [comment]
This does not seem doable, so closing. If I got it wrong, please re-activate.
