### ISSUE TITLE
dotnet [build|publish] not persisting serviceable attribute for packages in deps file

### ISSUE THREAD

**Issue by schellap** [dotnet/sdk#5761]
## Tasks
- [ ] Fix bug
- [x] Undo dotnet/cli#2491 **EDIT** was never merged, so nothing to undo.
- [ ] Verify and Close issue
## Steps to reproduce

dotnet new
dotnet restore
dotnet publish
## Expected  behavior

CoreCLR and other assemblies are marked serviceable in the libraries section in the `project.lock.json`
## Actual behavior

CoreCLR package and other serviceable assembly packages are marked as `"serviceable": false`
## Environment data

`dotnet --info` output:
1.0.0-rc2-002374

**Comment by eerhardt** [comment]
Closing this issue as it is obviously not going to happen any time soon. We can re-open it if the underlying NuGet change ever makes it into the product.
