### ISSUE TITLE
Build task support for .pp files

### ISSUE THREAD

**Issue by emgarten** [dotnet/sdk#577]
The build task for PackageReference projects should: 
1. Continue to process ``.pp`` files and reference the output file as part of the build
1. Skip all non-pp contentFiles from ``project.assets.json``

NuGet restore now writes contentFile assets to the ``projectName.ext.nuget.g.props`` file with the exception of ``.pp`` files. ``.pp`` files cannot be handled at restore time since they require evaluating additional properties which could be populated differently post-restore.

Original NuGet issue: https://github.com/NuGet/Home/issues/3683

//cc @natidea

**Comment by natidea** [comment]
@emgarten is the correct filter to look for files with `*.pp` extension, or to focus on entries with the `ppOutputPath` metadata. The latter is the current approach of the build task and the old [ResolveNuGetPackageAssets](https://github.com/NuGet/NuGet.BuildTasks/blob/4a57a0ef4bee31f122d50a39fe3dddd4ca03fb07/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L623) task. They expect files that need to be preprocessed to be called out in the lock file. E.g. 

```json
      "SharedContentA/1.0.0": {
        "type": "package",
        "contentFiles": {
          "contentFiles/text/sample.pp": {
            "buildAction": "None",
            "ppOutputPath": "contentFiles/text/sample.txt",
            "codeLanguage": "any",
            "copyToOutput": false
          },
          "contentFiles/images/ui_any.png": {
            "buildAction": "EmbeddedResource",
            "codeLanguage": "any",
            "copyToOutput": false
          }
        }
      },
```

**Comment by emgarten** [comment]
Going by the ``ppOutputPath`` property is the best approach in my opinion. It would make it easier to control this behavior in the future.

NuGet checks the extension and will always write that property if the file ext is ``.pp``, so you can expect it to be there if the transform is needed.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs#L204-L205

**Comment by damianh** [comment]
Hi @emgarten does this really work? I'm attempting to get this working with LibLog (https://github.com/damianh/LibLog/pull/125) and not having any success. 

I've opened an issue over at nuget too (https://github.com/NuGet/Home/issues/4803 ). Honestly I don't know if its a nuget problem, and SDK one, or an MSBuild one.

Any pointers would be great.
