### ISSUE TITLE
RID-specific targets section from assets file is being used for compile assets.

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#592]
When compiling a project that sets a RuntimeIdentifier we should select the compile assets from the RID-less target in the assets.json, but select the runtime assets from the RID-specific target.  It seems that this is not happening.

Repro:
https://gist.github.com/ericstj/452c243859cdc5f88da084d205bc73e9

dotnet restore
dotnet build

notice conflict errors.  There are various other errors later on which may or not be related, but I'd expect this to build (not run) as is.

The relevant code in the old task that did this was https://github.com/NuGet/NuGet.BuildTasks/blob/4a57a0ef4bee31f122d50a39fe3dddd4ca03fb07/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L303.

/cc @natidea @jasonmalinowski

**Comment by dsplaisted** [comment]
What do the conflict errors look like?  Could this be the cause of #514?
