### ISSUE TITLE
Add more windows installer tests

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/sdk#5923]
We are lacking windows installer tests which does various combinations of installing,uninstalling,SxS,upgrading the product.

Issues we have been seeing:
dotnet/sdk#5906
dotnet/sdk#5899
dotnet/sdk#5889

**Comment by Forgind** [comment]
Old bug triage:
All those issues seem to be resolved. More tests are always good, but I don't know that we need an open issue for it.
