### ISSUE TITLE
Add System.Net.Http and System.IO.Compression back to .NET Framework implicit references once MSBuild bug is fixed

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#594]
Once https://github.com/Microsoft/msbuild/issues/1329 is fixed, we should remove our workaround of [commenting out](https://github.com/dotnet/sdk/blob/7eb264f9cc5153b24793878307c4c410bd03ff68/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L100-L102) the implicit references to System.Net.Http and System.IO.Compression in Microsoft.NET.Sdk.BeforeCommon.targets.

**Comment by srivatsn** [comment]
Also add Microsoft.CSharp to the set of implicit references.

**Comment by davkean** [comment]
Making sure you don't add for VB.
