### ISSUE TITLE
Copy Package Reference assemblies to output directory for .NET Standard libraries

### ISSUE THREAD

**Issue by Snipx** [dotnet/sdk#598]
Hi,
I am using VS2017RC to create a .NET Standard library.
When I do that and build the binaries, the package reference assemblies (System.Linq.dll, System.Net.dll etc etc) are not copied to the output path.
I can't seem to find any configurations for whether or not to copy the dependencies to output neither in VS2017RC nor via the .csproj file directly.

Is there any way to achieve copying of all the package references to output?
I specifically need this to run unit tests via NUnit.

I have [asked](https://github.com/Microsoft/msbuild/issues/1515) this question to MSBuild team, but they redirected me to you. They also mentioned a workaround of creating a dummy executable so that the dependencies are copied, but I wonder if there is a more elegant solution to this.

**Comment by eerhardt** [comment]
@Snipx - have you tried using the new `dotnet test` command to run your unit tests?  That verb doesn't need the assemblies in the output directory, as they are loaded from the NuGet cache, just like during `dotnet run`.  I would recommend trying this out, and seeing how it works for you.

**Comment by Snipx** [comment]
I have tried `dotnet test`, no success so far, the tests are not executed I'm getting `Starting test execution, please wait...` message and that's all. I have submitted a request to the NUnit team, but I'm not sure the problem is on their side.

Meanwhile, @eerhardt, do you happen to have an idea on what might be wrong?

I have described my problem [here](https://github.com/nunit/dotnet-test-nunit/issues/98)

**Comment by Snipx** [comment]
Closing the issue. The NUnit team explained that `dotnet test` doesn't currently work for .NET Core after moving to `.csproj` back from json.
