### ISSUE TITLE
Generate a more helpful error message if Compile (or other implicit items) are specified multiple times

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#600]
If the implicit items are enabled and also explicitly added to the project file, the compiler will generate an error saying that the source file was specified multiple times.  We should detect this situation earlier and provide an error message which tells how to disable the implicit items if desired.

**Comment by srivatsn** [comment]
We should do something here for RC3 or else all existing projects are going to run into this when they upgrade to RC3.

**Comment by dsplaisted** [comment]
This should also handle duplicate `PackageReference` items.

**Comment by srivatsn** [comment]
Fixed by #624
