### ISSUE TITLE
Duplicate output files for net452

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#6013]
## Steps to reproduce

Install latest cli build.

```
mkdir test
cd test
dotnet new
notepad project.json
```

Replace the content with (adding net452 and inlining netcore deps):

``` json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "frameworks": {
    "net452": {},
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
          "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0-rc2-3002677"
          }
      },
    }
  }
}
```

Now run `tree /F bin` to find out what we got in `bin\Debug\net452` versus `bin\Debug\netcoreapp1.0`.
## Expected  behavior

Both output framework folders should have same structure and there shouldn't be duplicated exe+pdb in case of net452.

```
└───Debug
    ├───net452
    │       test.exe
    │       test.pdb
    │
    └───netcoreapp1.0
            test.deps.json
            test.dll
            test.pdb
            test.runtimeconfig.dev.json
            test.runtimeconfig.json
```
## Actual behavior

netcoreapp1.0 :white_check_mark:  (no duplicates)
net452 :x: (duplicates)

```
└───Debug
    ├───net452
    │   │   test.exe
    │   │   test.pdb
    │   │
    │   └───win7-x64
    │           test.exe
    │           test.pdb
    │
    └───netcoreapp1.0
            test.deps.json
            test.dll
            test.pdb
            test.runtimeconfig.dev.json
            test.runtimeconfig.json
```
## Environment data

`dotnet --info` output:

Product Information:
 Version:     1.0.0-rc2-002677
 Commit Sha:  d9d8bb2f03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Forgind** [comment]
Old bug triage:
Closing as by-design
