### ISSUE TITLE
Pre-requisite SDK version from Packages?

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#606]
NETCoreApp 2.0 is going to require both a NuGet update (for NETStandard2.0 support) and a host change (for flat NETCoreApp package support).

How do we message to users that they need a new SDK to use the new NETCoreApp TFM & package?

One thing we could do is put targets in our NETCoreApp that checks the SDK version somehow and fails if it is too low.  If we do this, how should we detect the SDK version?

An alternative is to have the SDK "know" about this in its first version and tell folks to get a new SDK before it even tries to download/restore a new NETCore.App package.

/cc @schellap @eerhardt @terrajobst

**Comment by dsplaisted** [comment]
I think #534 would fix this (by defining a property that you could check for in the targets)

**Comment by srivatsn** [comment]
Closing in favor of #534
