### ISSUE TITLE
dotnet pack fails on xplat for applications targeting desktop

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#607]
1. Create a project that cross compiles to `net451` and `netcoreapp1.1` on a machine without mono \ reference assemblies installed.
2. Run `dotnet build -f netcoreapp1.1`
3. Run `dotnet pack --no-build`

Expected:
Pack succeeds

Actual: 
Pack fails with `~/.dotnet/sdk/1.0.0-preview4-004233/Microsoft.Common.CurrentVersion.targets(1107,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.`

**Comment by srivatsn** [comment]
Pack is not implemented in this repo - Can you please move this to http://github.com/NuGet/Home/issues?

**Comment by pranavkm** [comment]
Done.
