### ISSUE TITLE
Fix warnings about double imports in Dependencies projects

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#611]
As of #601, the Dependencies projects (xUnit and SignTool) now build using the .NET Sdk.  They need to override various core targets to be no-ops, so the projects import the language-specific targets and then re-define the targets.  This causes MSBuild to generate a warning when Sdk.targets tries to import the same language-specific targets file again.  We should clean up this warning.

**Comment by nguerrera** [comment]
This was fixed a while ago.
