### ISSUE TITLE
Cross-targetting apps get wrong version of NETStandard.Library on .NETFramework

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#614]
When packing a project that targets .NETStandard and .NETFramework, the package can easily end up with different version of NETStandard.Library based on TFM.

Repro:
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFrameworks>net451;netstandard1.3</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="1.6.2-*"/>
  </ItemGroup>

</Project>
```

`dotnet pack` produces the following dependencies:
```xml
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="NETStandard.Library" version="1.6.2-beta-24903-02" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard1.3">
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

Using CLI 1.0.0-preview5-004468.

**Comment by Eilon** [comment]
Adding Blocking Partner label because this is blocking ASP.NET.

**Comment by dsplaisted** [comment]
Can you add the following to the `PropertyGroup`?

```xml
<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
```

Then it should use the version specified in your project file.

With #600, we are planning to generate error messages if the same item is specified multiple times which will tell you how to disable the implicit items if you want.

**Comment by natemcmaster** [comment]
Yes using DisableImplicitFrameworkReferences does the trick. I'm closing at it appears to be a duplicate of #596 and #600
