### ISSUE TITLE
netci.groovy uses internal imports

### ISSUE THREAD

**Issue by 333fred** [dotnet/sdk#619]
When we were a private repo, we used the internal version of the netci.groovy utilities. We need to move the public versions of all of those so we can move the sdk pr build definitions to the public dotnet-ci repolist.

**Comment by srivatsn** [comment]
Fixed by #632?

**Comment by 333fred** [comment]
Yeah, I'll update that and get it merged in.

**Comment by dsplaisted** [comment]
Looks like this is fixed
