### ISSUE TITLE
MulticoreJit Optimization Data Location should be configurable

### ISSUE THREAD

**Issue by brthor** [dotnet/sdk#6242]
dotnet/sdk#6136 For reference.

Optimization data is dropped in `~/.dotnet/...`

We should add some option to configure this so we don't need to populate the home directory during our builds.

cc @piotrpMSFT @troydai

**Comment by Forgind** [comment]
Old bug triage:
I don't know if the modern scenario that uses optimization data is the same as the scenario referenced here, but regardless, my .dotnet folder doesn't have optimization data in it (at least not at the root level), so I don't think this is an issue anymore.

**Comment by Forgind** [comment]
Thanks for confirming @KalleOlaviNiemitalo!
