### ISSUE TITLE
Web project publishes .vscode directory

### ISSUE THREAD

**Issue by dasMulli** [dotnet/sdk#631]
Since websdk repo is private, opening an issue here..

The glob patterns in sdk/websdk publish folders that should be considered "hidden" like `.vscode`.
This probably also applies to files/folders that one would expect to be hidden.. Maybe every file/folder starting with a dot?

@guardrex also discovered that the `Properties` folder is deployed as well thus deploying publish profiles.

Steps to reproduce:
* `dotnet new -t web1.1`
* `dotnet restore`
* `code .`
* Omnisharp-VSCode asks to add "required assets" > klick "yes"
* `dotnet publish -c Release`
* `ls -la bin/Release/netcoreapp1.1/publish/.vscode/`
```
-rw-r--r--    1 martin  staff  1262 Jan 11 21:44 launch.json
-rw-r--r--    1 martin  staff   332 Jan 11 21:44 tasks.json
```

`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview5-004478
```

cc @dsplaisted @mlorbetske

**Comment by GuardRex** [comment]
Yes, I'm seeing this behavior here ...

![capture](https://cloud.githubusercontent.com/assets/1622880/21865845/653f25f4-d80d-11e6-86b5-b5acea0851ed.PNG)

`dotnet publish -c Release -r win10-x64`

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyTitle>Test Self-contained Application</AssemblyTitle>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>testselfcontained</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
    <Optimize Condition="'$(Configuration)'!='Debug'">true</Optimize>
  </PropertyGroup>

  <!--<ItemGroup>
    <Content Include="testfile.txt" CopyToPublishDirectory="Always" CopyToOutputDirectory="Always" /> 
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.0" />
  </ItemGroup>

  <Target Name="CreateLogsFolder" AfterTargets="AfterPublish">
    <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
  </Target>

</Project>
```

```
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004478
```

**Comment by mlorbetske** [comment]
cc @vijayrkn

**Comment by dsplaisted** [comment]
I think the .vscode folder is being included because the Web SDK [`Content` include](https://github.com/aspnet/websdk/blob/75184cba7a7a59c580caf60a74fac247a29d807b/src/Web/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L25) isn't excluding [DefaultExcludesInProjectFolder](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L41).  I think this PR there will fix this: https://github.com/aspnet/websdk/pull/94/files

I'm not sure why the properties folder is being published, perhaps the `AppDesignerFolder` folder property isn't set?

**Comment by GuardRex** [comment]
Hard to see the PR when the source is closed. :trollface: :smile: ... We've been told they're working on opening the `websdk` repo up. Any status on that?

**Comment by GuardRex** [comment]
Yes, I can confirm that using ...
```
<AppDesignerFolder>Properties</AppDesignerFolder>
```
prevents the `Properties` folder from being published.

**Comment by dsplaisted** [comment]
Looks like I thought that were were defaulting the `AppDesignerFolder` property in the SDK, but we currently aren't.  @davkean @natidea @srivatsn @333fred Did we change how the AppDesignerFolder property works?

**Comment by srivatsn** [comment]
This has now been fixed.

**Comment by GuardRex** [comment]
@srivatsn The PR referenced seems to address the `Properties` folder but not the `.vscode` folder. It's still showing up here as of this morning ...

![capture](https://cloud.githubusercontent.com/assets/1622880/22601349/1a225ccc-ea04-11e6-966a-13e584e5f4f7.PNG)

Should we be using some other approach to keep that folder out of published assets?

```
.NET Command Line Tools (1.0.0-rc4-004757)

Product Information:
 Version:            1.0.0-rc4-004757
 Commit SHA-1 hash:  f69f0ed266

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004757
```

**Comment by srivatsn** [comment]
@dsplaisted mentioned that .vscode should be getting excluded with https://github.com/aspnet/websdk/pull/94. @dsplaisted can you make sure it's fixed?
