### ISSUE TITLE
Error for missing attribute doesn't state what is missing

### ISSUE THREAD

**Issue by billwert** [dotnet/sdk#639]
Had a typo in a PackageReference, like so:
`<PackageReference Name="System.Configuration" Version="4.4.0-*"/>`

Name is incorrect; it should be Include.

The error I got:
error MSB4035: The required attribute "" is empty or missing from the element <PackageReference>.

It should tell me what it thinks I am missing.

**Comment by rainersigwald** [comment]
This is tracked as https://github.com/Microsoft/msbuild/issues/1555. Thanks for the report.
