### ISSUE TITLE
[netstandard2.0] Integrate conflict resolution task into SDK

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#643]
We need a task that looks at package references, identifies file conflicts, and drops them.

I have a prototype version here: https://github.com/dotnet/standard/blob/58e8043f8474a5e88308c7697d19be2245bb2403/netstandard/tools/ConflictItem.cs

We also need to ship this downlevel for NuGet 3 & NuGet 2 so we'll need something similar here.

In .NET SDK this needs to impact the references to the compiler, files in output directory, generated deps file, and files published.

/cc @eerhardt @weshaggard @terrajobst

**Comment by dsplaisted** [comment]
Closing this in favor of #974
