### ISSUE TITLE
We are not shipping all our dependencies 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/sdk#644]
- Create a console application
- Right click publish 
- Create a profile 

**Expected**
It publishes the file

**Actual**

1>------ Build started: Project: ConsoleApp7, Configuration: Debug Any CPU ------
1>ConsoleApp7 -> c:\users\jinuj\documents\visual studio 2017\Projects\ConsoleApp7\ConsoleApp7\bin\Debug\netcoreapp1.0\ConsoleApp7.dll
2>------ Publish started: Project: ConsoleApp7, Configuration: Debug Any CPU ------
2>ConsoleApp7 -> c:\users\jinuj\documents\visual studio 2017\Projects\ConsoleApp7\ConsoleApp7\bin\Debug\netcoreapp1.0\ConsoleApp7.dll
2>The "GenerateDepsFile" task failed unexpectedly.
2>System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.DependencyModel.FileSystemWrapper' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>   at Microsoft.Extensions.DependencyModel.FileSystemWrapper..ctor()
2>   at Microsoft.Extensions.DependencyModel.FileSystemWrapper..cctor()
2>   --- End of inner exception stack trace ---
2>   at Microsoft.Extensions.DependencyModel.FileSystemWrapper.get_Default()
2>   at Microsoft.NET.Build.Tasks.FrameworkReferenceResolver.GetDefaultReferenceAssembliesPath()
2>   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
2>   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Object reference not set to an instance of an object.
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Build Info** 
26112.1.d15rel (with just .Net cross-platform workload)

**Comment by jinujoseph** [comment]
Publish on .NetStandard Class library throws 

2>The "PackTask" task failed unexpectedly.
2>System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
2>File name: 'System.IO.Compression, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
2>   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
2>   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath)
2>   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
2>   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
2>   at NuGet.Commands.PackCommandRunner.BuildPackage()
2>   at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner)
2>   at NuGet.Build.Tasks.Pack.PackTask.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by piotrpMSFT** [comment]
@jinujoseph I tried the following:
- `dotnet new` [creates new console app from template
- `dotnet restore`
- `dotnet publish` [succeeded]
- `dotnet pack` [succeeded]

I'm not sure what it means in the repro to `create a profile`. Perhaps I'm missing an important step?

**Comment by srivatsn** [comment]
This is fixed with #646
