### ISSUE TITLE
PackageReference warnings post-migration do not link to project file

### ISSUE THREAD

**Issue by ardalis** [dotnet/sdk#654]
After migrating a project with package references to NETStandard.Library, running the project in Visual Studio will generate warnings saying the line is probably no longer needed. Double-clicking on this warning should take you to the project file in question, ideally to the line where the package reference is, so that the developer can decide whether to remove it. Instead, double-clicking takes you to the .targets file (see screenshot):

![image](https://cloud.githubusercontent.com/assets/782127/21995727/688eeec0-dbf4-11e6-9f7f-447c35cea04c.png)

**Comment by ardalis** [comment]
If the user is unfamiliar with working in XML project files, they may mistakenly think that line 101 shown is the package referenced by the warning text and that "you do not typically need to reference it from your project" so they can safely delete it. Which would be bad.

**Comment by srivatsn** [comment]
@dsplaisted looked into this and the problem is that even if the error listed the correct filename, opening the project file from the error list is currently not possible until https://github.com/dotnet/roslyn-project-system/issues/780 is fixed.

**Comment by dsplaisted** [comment]
Migrate should no longer be creating projects that will generate this warning.
