### ISSUE TITLE
Implicit PackageReference Warning leads to broken link.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/sdk#655]
1>------ Build started: Project: ClassLibrary7, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(101,5): warning : A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see [https://aka.ms/sdkimplicitrefs](https://aka.ms/sdkimplicitrefs)
1>ClassLibrary7 -> c:\users\jinuj\documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7\bin\Debug\netstandard1.4\ClassLibrary7.dll
1>Done building project "ClassLibrary7.csproj".
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

**Expected**
https://aka.ms/sdkimplicitrefs should lead to a correct information.

**Comment by srivatsn** [comment]
@blackdwarf you've authored this page already right?

**Comment by blackdwarf** [comment]
Yes, it is not checked in. I'm going to do that today.

**Comment by srivatsn** [comment]
This is fixed.
