### ISSUE TITLE
Error message missing data: The required attribute "" is empty or missing from the element <Compile>.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/sdk#658]
When trying a `<Compile Exclude="<pattern>" />` to fix a SDK vs `.csproj` issue, an error is properly thrown. The `Include="..."` attribute is missing. The error message presented is:

> The required attribute "" is empty or missing from the element <Compile>.

What it should say is:

> The required attribute "**Include**" is empty or missing from the element <Compile>.

**Comment by srivatsn** [comment]
@cdmihai @AndyGerlicher @rainersigwald - I seem to remember seeing a msbuild issue around this?

**Comment by rainersigwald** [comment]
This is tracked by https://github.com/Microsoft/msbuild/issues/1555
