### ISSUE TITLE
Unresolvable warnings due to NETStandard.Library versions

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#666]
[Upgrading my package reference](https://github.com/AArnott/MoneyMan/commit/68a41e14d5d43a48aa6ece11cc35ea277266c895) to sqlite-net-pcl 1.3.1 (the first one to officially support netstandard1.1) caused my build to emit this warning:

> C:\Program Files\dotnet\sdk\1.0.0-rc3-004504\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3243: No way to resolve conflict between "System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.1.0.0,
 Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. 

I figured this was because my library is now trying to reference both NETStandard.Library 1.6.0 and 1.6.1. So I [added a direct reference to NETStandard.Library 1.6.1](https://github.com/AArnott/MoneyMan/commit/cbde46af18812f669ea17c78fd06676c1d5b903c) to resolve that warning. Which worked, except that now I get this warning on package restore:

> C:\Program Files\dotnet\sdk\1.0.0-rc3-004504\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(101,5): warning : A PackageReference for 'NETStandard.Library' was in
cluded in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.m
s/sdkimplicitrefs 

How am I supposed to resolve this to not have any build warnings?

Repro steps:

```
git clone https://github.com/AArnott/MoneyMan.git
cd MoneyMan\src\Nerdbank.MoneyManagement
git checkout 68a41e1
dotnet restore
dotnet build
# first warning
git checkout cbde46a
dotnet restore
# second warning
```

Possibly similar to #514

**Comment by AArnott** [comment]
CC: @dsplaisted since he's familiar with how a possibly related issue was fixed.

**Comment by natemcmaster** [comment]
Furthermore, it seems https://aka.ms/sdkimplicitrefs is a broken link. It redirects to https://github.com/dotnet/core/blob/master/release-notes/sdk-implicit-refs.md which hasn't been added yet.

**Comment by dsplaisted** [comment]
The implicit package reference is to version 1.6.1 of NETStandard.Library, so the conflict warning shouldn't be related to this.  Once doc is written that the link will point to it should explain how to disable the implicit package references, but that you should not need to do so.

I think that the warning you are getting about System.Net.Http should be fixed by #662 and #671

**Comment by srivatsn** [comment]
Closing since this does look to be the same as #514 which is fixed in latest RC3 builds. Please reactivate if this still repros.

**Comment by AArnott** [comment]
I can confirm on latest d15rel the warning is gone. Thanks.
