### ISSUE TITLE
The item "Class1.cs" was specified more than once in the "Sources" parameter

### ISSUE THREAD

**Issue by aL3891** [dotnet/sdk#668]
Hello, 
While reproing nuget/home#4059 I ran into a strange issue with the latest cli, all the details are over there but basically, for a previously created class library I get 

```
    1>Target "_GenerateCompileDependencyCache" in file "C:\Program Files\dotnet\sdk\1.0.0-rc4-004527\Microsoft.Common.CurrentVersion.targets" from project "C:\Users\Allan\Documents\Visual Studio 2017\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj" (target "Compile" depends on it):
       Added Item(s): CustomAdditionalCompileInputs=obj\Debug\netstandard1.6\CoreCompileInputs.cache
       Added Item(s): 
           CoreCompileCache=
               C:\Users\Allan\Documents\Visual Studio 2017\Projects\ClassLibrary1\ClassLibrary1\Class1.cs
               C:\Users\Allan\Documents\Visual Studio 2017\Projects\ClassLibrary1\ClassLibrary1\Class1.cs
               C:\Users\Allan\AppData\Local\Temp\.NETStandard,Version=v1.6.AssemblyAttributes.cs
       Added Item(s):  ...
```

and then

```
       (CoreCompile target) -> 
         C:\Program Files\dotnet\sdk\1.0.0-rc4-004527\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB3105: The item "Class1.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [C:\Users\Allan\Documents\Visual Studio 2017\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
```

Even though there is only one cs file in that project. Am I missing something obvious?

**Comment by aL3891** [comment]
ah, removing 
```
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
```
fixes the issue.

still, feels like this should be handled somehow or a lot of projects are going to break :)

**Comment by dsplaisted** [comment]
There is supposed to be a different error message that tells you that you don't need the Compile include in your file.  It's not showing up in the intellisense build: #664

**Comment by dsplaisted** [comment]
Thinking more about it, it's possible that the reason you didn't get the right error message is because the CLI you are using doesn't have the changes from #624 which added it.

**Comment by aL3891** [comment]
Aha allright, that's what living on the edge gets ya :D 
no worries, just wanted to make you aware of it :)

**Comment by enricforn** [comment]
@aL38891 which version of sdk contains the fix to this issue ?

@dsplaisted if I remove these lines, Visual Studio 2017 do not recognize the class as added to the project

**Comment by aL3891** [comment]
i'm using version 1.0.0-preview4-004233

**Comment by dsplaisted** [comment]
> @dsplaisted if I remove these lines, Visual Studio 2017 do not recognize the class as added to the project

@enricforn We haven't released a version of Visual Studio with these changes yet.  So right now what your .NET CLI supports and what your version of Visual Studio supports is out of sync.

**Comment by enricforn** [comment]
@dsplaisted ok, as a workaround we'll only compile through command line. It will be supported on the next RC ?

**Comment by bangonkali** [comment]
After removing all occurrences of
```
<Compile Include="**\*.cs" />
```
it works on VS 2017 RC3.

Then I also installed the following debs on our Linux Ubuntu Server so that it can build from the Linux Server:
```
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-sdk-ubuntu-x64.latest.deb
```

I used this call
```
wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb && \
wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb && \
wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb && \
wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-sdk-ubuntu-x64.latest.deb && \
sudo dpkg -i "dotnet-host-ubuntu-x64.latest.deb" && sudo apt-get install -f && \
sudo dpkg -i "dotnet-hostfxr-ubuntu-x64.latest.deb" && sudo apt-get install -f && \
sudo dpkg -i "dotnet-sharedframework-ubuntu-x64.latest.deb" && sudo apt-get install -f && \
sudo dpkg -i "dotnet-sdk-ubuntu-x64.latest.deb" && sudo apt-get install -f
```
