### ISSUE TITLE
An item with the same key has already been added. Key: K2Innovators.BizMovAutomation.Core

### ISSUE THREAD

**Issue by gunpal5** [dotnet/sdk#6733]
Hi,

I have a multi layered project. There's a core library which has common codes for top layers. there are many dependent modules which finally converge in a Web API project. Now I am getting this error:
An item with the same key has already been added. Key: K2Innovators.BizMovAutomation.Core
## Steps to reproduce

1) Create a web project.
2) Add 3 libraries: Core, EntityframeworkCore, Dtos. Add a web project "Web"
3) Add references as shown in following screenshot:

![image](https://cloud.githubusercontent.com/assets/10114874/17581245/0e6a5302-5fc2-11e6-8843-f3946380997e.png)
## Expected  behavior

1) Should compile successfully.
## Actual behavior

Error: An item with the same key has already been added. Key: K2Innovators.BizMovAutomation.Core
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Forgind** [comment]
Old bug triage:
Nothing was provided. If you have one, let us know, and we can reopen this issue.
