### ISSUE TITLE
Clarify build output when a build happens as part of another command

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#682]
Moving from https://github.com/dotnet/cli/issues/5376 on behalf of @danroth27 

----

The output of `dotnet build` tells you which projects are being built and their output:

```
C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool [master ≡ +0 ~1 -0 !]> dotnet build
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

  dotnet-package-versions -> C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool\src\dotnet-package-versions\bin\Debug\netcoreapp1.0\dotnet-package-versions.dll
  supported-package-graph-generator -> C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool\src\supported-package-graph-generator\bin\Debug\netcoreapp1.0\supported-package-graph-generator.dll 
```

In the context of a build, this makes sense. But sometimes you see the build output as part of another command, like pack, in which case it's not as clear what is going on:

```
C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool [master ≡ +0 ~1 -0 !]> dotnet pack --version-suffix alpha-0000
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

  supported-package-graph-generator -> C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool\src\supported-package-graph-generator\bin\Debug\netcoreapp1.0\supported-package-graph-generator.dll
  dotnet-package-versions -> C:\Users\danroth27\Documents\GitHub\danroth27\DotNetVersioningTool\src\dotnet-package-versions\bin\Debug\netcoreapp1.0\dotnet-package-versions.dll 
```

It might be nice to say something like `Building <project> -> <output path>` to make the fact that this is build output clearer.

**Comment by nguerrera** [comment]
This message is authored in msbuild common targets and we can't override the message alone.

**Comment by livarcocc** [comment]
We could change this, it would look like something like this:
```
Built sample.webapi -> /sample.webapi/bin/Debug/netcoreapp2.0/sample.webapi.dll
Published sample.webapi -> /sample.webapi/bin/Debug/netcoreapp2.0/publish/
```

For pack:
```
Built sample.webapi -> /sample.webapi/bin/Debug/netcoreapp2.0/sample.webapi.dll
Successfully created package '/sample.webapi/bin/Debug/sample.webapi.1.0.0.nupkg'
```

We would also have to localize the targets and the build change would have to happen in MSBuild. I don't see much gain from this change and from our github issues it does not seem to be something that confuses our customers, so I will close the issue. Please, re-activate if you have seen customers complaining about this.
