### ISSUE TITLE
Empty TargetFramework Crashes VS 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/sdk#684]
Create Core console application 
Edit the project and change 
` <TargetFramework>netcoreapp1.0</TargetFramework>`
to 
` <TargetFramework></TargetFramework>`

Actual
you will see below error couple of times and then VS crashes.
![image](https://cloud.githubusercontent.com/assets/12449387/22084555/6df39496-dd85-11e6-98f0-696eefc30a11.png)

Followed by crash., if it doesn't crash right away , close the csproj and edit again.

Build: 
26118.0.d15rel

**Comment by srivatsn** [comment]
Fixed by #725
