### ISSUE TITLE
System.Net.Http/Microsoft.CSharp is missing from the set of implicit references

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#688]
For example, System.IO.Compression.FileSystem is a part of the implicit set, but not System.Net.Http. How was this set decided?

**Comment by srivatsn** [comment]
See https://github.com/dotnet/sdk/issues/714#issuecomment-274640485. What's you real question?

**Comment by davkean** [comment]
System.Net.Http and Microsoft.CSharp are missing...

**Comment by srivatsn** [comment]
Readding System.Net.Http is tracked by https://github.com/dotnet/sdk/issues/594. Added a note there to include Microsoft.CSharp as well.
