### ISSUE TITLE
Include files in the SDK authoring swr by wildcard instead of individually listing files.

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#689]
https://github.com/dotnet/sdk/blob/master/src/VsixV3/Microsoft.Net.Sdk.swr lists the files that go into VS, which should be all the files in the PackagesLayout folder in the output.  We should add a test to verify this, so that we don't think we've added a new file but forget to add it to the swr authoring.

**Comment by srivatsn** [comment]
The way we have authored the swr is not good. We should instead just include everything from the packagelayout folder into the swr. This requires some custom msbuild task since the swr file itself doesn't support wildcards.

**Comment by nguerrera** [comment]
This is mostly done, though it would be better in a C# task that that can just have a nested loop instead of the brain melting batching in msbuild xml that still requires code chages when a directory is added or removed.

**Comment by dsplaisted** [comment]
Closing, as we aren't using .swr files anymore in 2.0.
