### ISSUE TITLE
Should we add validation of the RIDs?

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/sdk#690]
## Repro

1. Install latest CLI from dotnet/cli
2. `mkdir app && cd app`
3. `dotnet new`
4. Open up the project and change the target framework to be `net451`.
5. Add `<RuntimeIdentifiers>win10-x64;win19-x12</RuntimeIdentifiers>` to the project.
6. Run `dotnet restore`.
7. Run `dotnet publish -r win19-x12`.

I would expect the operation to fail since the RID is obviously not valid. However, it succeeds and the output folder is created with the bits in it.

**Comment by dsplaisted** [comment]
@ericstj @eerhardt Should we be checking whether RuntimeIdentifiers are valid?  If so, how would we do so?

**Comment by ericstj** [comment]
I recently added some validation to NETCore.App for this.  I suspect this is a no-repro now.  See https://github.com/dotnet/core-setup/pull/2369.
