### ISSUE TITLE
dotnet restore does not capture transitive framework assemblies from project references

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/sdk#691]
Trying to utilize a transitive project references framework assembly results in build errors. This looks to be the result of `dotnet restore` not capturing project references framework assemblies (doesn't exist in assets.json).

Note: This used to work in project.json land (built the repro in project.json then migrated).

See the simple repro here:
[TransitiveProjectFrameworkRefs.zip](https://github.com/dotnet/sdk/files/717684/TransitiveProjectFrameworkRefs.zip)

Go into ConsoleApp12 and `dotnet restore; dotnet build`

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4412
