### ISSUE TITLE
DocumentationFile cannot be set in project file

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#703]
1. Create a new .NET Core netstandard class library
1. In project designer, check the box to generate a documentation file

The value set for the path is `\projectname.xml`, so the build fails because it tries to write to the root directory.

Trying to fix this manually in the project file fails all around:

1. "projectname.xml" writes to the project directory
1. "bin\$(Configuration)\$(TargetFramework)\projectname.xml" fails because $(TargetFramework) isn't set at that point in the project.
1. "$(TargetDir)\..." or $(OutDir) fails for the same reason: not defined yet.

In fact more generally, how on earth are we supposed to write properties in our project file that depend on these properties that are only defined in an imported .targets file that is implicitly defined, as is the case with the Sdk import?

Using d15rel 26119.0

**Comment by nguerrera** [comment]
@AArnott You can now also set only GenerateDocumentationFile=true and it will pick the appropriate path. (Like pdb.). It looks like the property pages were not updated to account for this. There was supposed to be a capability to drive this.

Cc @dsplaisted who worked on it

Also, I don't understand (2). TargetFramework is either set in the project for single targeting or passed in as global property for multi targeting. So you shouldn't have problems referencing it. Is the issue that the project system is saving DocumentationFile above TargetFramework?

**Comment by nguerrera** [comment]
I see dotnet/roslyn-project-system#368 is still open for handling the boolean case.

**Comment by nguerrera** [comment]
There's nothing to change in the SDK here. Project system work is underway.

**Comment by AArnott** [comment]
You're right about (2). It works when I hand author it. Thanks.
