### ISSUE TITLE
Bring back the aka.ms link in the error for duplicated items

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/sdk#704]
We should do this for RTM. 

/cc @dsplaisted

**Comment by dsplaisted** [comment]
Unfortunately, this would require changing strings and the loc deadline is passed.  So I think we can't do this for RTM unless perhaps we just put the URL at the end of the message without the "For more information, see" text, or unless we want to do the translation some other way.

@nguerrera, thoughts?

**Comment by blackdwarf** [comment]
@dsplaisted I am fine with just putting ([link]) in there as well.

**Comment by davkean** [comment]
I disagree on this - let's walk through this:

1. We do nothing.  Both English and other languages have a bad error.
2. We change the English string. Other languages have a bad error.

What's the problem here? We can at least make English better, and pick up the other languages when we next loc.

**Comment by nguerrera** [comment]
You can add a sentence to the existing string if you don't reduce the placeholder count. Other languages just won't change until next loc and I agree with Dave that's ok.
