### ISSUE TITLE
dotnet restore can't handle package that references an LKG of itself

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#705]
Nerdbank.GitVersioning is a package that is built with an LKG of itself since this package is a build authoring extension. But in trying to convert this repo to use the .NET Core projects, I find there seems to be an inability of the SDK to support referencing a published version of oneself. 

**Repro steps**

```
git clone https://github.com/AArnott/Nerdbank.GitVersioning.git 
cd Nerdbank.GitVersioning
git checkout 5754df2e36db3c823feebdf5bc5a2ef827e18639
cd src\Nerdbank.GitVersioning
dotnet restore
```

Then add this package reference to the Nerdbank.GitVersioning.csproj project file:

```xml
<PackageReference Include="Nerdbank.GitVersioning" Version="1.5.62" />
```

Then run `dotnet restore` again.

**Expected**

Nerdbank.GitVersioning can build with the aid of an LKG build of itself.

**Actual**

Package restore fails in a really big way, producing dozens of package version conflict errors, even though this package I'm referencing is very simple, has no dependencies, and should have been restored cleanly.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4356
