### ISSUE TITLE
Can't reference netstandard project from UWP app

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#707]
After creating a .NET Core project in VS2017 that targets netstandard1.6 and net46, I reference it from a UWP project. This appears to work, but then the build fails with the error that "[.netstandard library] has no target framework compatible with '.NETCore,Version=v5.0'."

Full build output below:

```
1>------ Build started: Project: Nerdbank.MoneyManagement, Configuration: Debug x86 ------
1>Nerdbank.MoneyManagement -> C:\git\MoneyMan\src\Nerdbank.MoneyManagement\bin\x86\Debug\netstandard1.6\Nerdbank.MoneyManagement.dll
1>Nerdbank.MoneyManagement -> C:\git\MoneyMan\src\Nerdbank.MoneyManagement\bin\x86\Debug\net46\Nerdbank.MoneyManagement.dll
2>------ Build started: Project: Nerdbank.MoneyManagement.Tests, Configuration: Debug x86 ------
3>------ Build started: Project: MoneyMan.UWP, Configuration: Debug x86 ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\d15prerel\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(69,5): error : Project 'C:\git\MoneyMan\src\Nerdbank.MoneyManagement\Nerdbank.MoneyManagement.csproj' has no target framework compatible with '.NETCore,Version=v5.0'.
2>Nerdbank.MoneyManagement.Tests -> C:\git\MoneyMan\src\Nerdbank.MoneyManagement.Tests\bin\x86\Debug\net46\Nerdbank.MoneyManagement.Tests.dll
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Using: d15prerel 26121.5

**Comment by nguerrera** [comment]
I have a fix ready for this.

**Comment by srivatsn** [comment]
This should now be fixed.

**Comment by jinujoseph** [comment]
Just tried this 

with Class library pointing to below 
```
<PropertyGroup>
    <TargetFrameworks>netstandard1.4;net46</TargetFrameworks>
  </PropertyGroup>
```

and being referenced by UWP app 

I get this error 
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: ClassLibrary1, Configuration: Debug x86 ------
1>ClassLibrary1 -> C:\Users\jinuj\documents\visual studio 2017\Projects\App1\ClassLibrary1\bin\x86\Debug\netstandard1.4\ClassLibrary1.dll
1>ClassLibrary1 -> C:\Users\jinuj\documents\visual studio 2017\Projects\App1\ClassLibrary1\bin\x86\Debug\net46\ClassLibrary1.dll
2>------ Build started: Project: App1, Configuration: Debug x86 ------
2>  App1 -> C:\Users\jinuj\documents\visual studio 2017\Projects\App1\App1\bin\x86\Debug\App1.exe
2>C:\Users\jinuj\documents\visual studio 2017\Projects\App1\ClassLibrary1\ClassLibrary1.csproj : error MSB4057: The target "GetPackagingOutputs" does not exist in the project.
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

note build says success

**Comment by nguerrera** [comment]
This is a separate issue from the earlier error that didn't let it get this far. 

I'll be working on an E2E test covering this P2P matrix:

(iOS | Xamarin | UWP | PCL | Desktop) -> (Sdk single-targeted, Sdk multi-targeted)

**Comment by jinujoseph** [comment]
the error we were seeing in my machine disappeared after i closed and reopened the sln , so it might be related to this bug #1503

**Comment by nguerrera** [comment]
The reason it succeeded with an error disappeared when you reopened is that it only affects clean builds and not incremental builds as it is continue-on-error and the incremental build skips it altogether as up-to-date.

**Comment by nguerrera** [comment]
#908 fixes the remaining error here (that did not stop build from succeeding nor trigger on incremental build). 

Internal bug [387770](https://devdiv.visualstudio.com/DevDiv/_workitems?id=387770) tracks the larger issue of actually dispatching to inner GetPackagingOutputs.
