### ISSUE TITLE
Compile up-to-date check is broken

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#708]
1. File -> New Class Library (.NET Standard)
4. Build
--Note the timestamp--
5. Wait 1 minute
6. Build

Expected: For the dll not be updated
Actual: The dll is regenerated

**Comment by davkean** [comment]
This looks like the cause of this: https://github.com/dotnet/sdk/issues/708.

**Comment by rainersigwald** [comment]
Next step for investigation is probably a diag level msbuild log, which should have the "X is newer than Y so running target Z" information.

**Comment by nguerrera** [comment]
Appears to repro only when building from VS and not command line.

**Comment by nguerrera** [comment]
Using diag log in VS, I see:
>  `Le fichier de sortie "__NonExistentSubDir__\__NonExistentFile__" n'existe pas`.
Translation: the output file "_NonExistentSubDir__\__NonExistentFile__" does not exist.


Which leads me to believe it's something gone wrong with https://github.com/Microsoft/msbuild/blob/765376a043d081569629998867d03e4a5eb9a256/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L3216-L3233

@rainersigwald

**Comment by davkean** [comment]
Oh interesting, I wonder if the legacy project system gets away with this because it does it's own update-to-date check and won't even call MSBuild. In our case, we don't - so we call into MSBuild expected it do the work for update-to-date.

**Comment by davkean** [comment]
ie The behavior might have always been this - we just never hit it in legacy csproj.

**Comment by rainersigwald** [comment]
@nguerrera can you find the part of the log where it reported on the condition evaluation for _ComputeNonExistentFileProperty? I'm wondering if we're getting a bogus value for `UseHostCompilerIfAvailable`.

@davkean MSBuild should do the right thing even without fast up to date, but that would mask problems here. Worth looking at.

**Comment by nguerrera** [comment]
In initial environment:
1>UseHostCompilerIfAvailable     = true

**Comment by nguerrera** [comment]
I don't think the fix for this will go in the sdk. Where should we move it?

**Comment by davkean** [comment]
Who even sets this property?

**Comment by davkean** [comment]
Oh, looks like it defaults to true: https://github.com/Microsoft/msbuild/blob/9fb136160ab2f828e2350227dc06ac8cf1d1695d/src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets#L151.

Unsure whom should set this - maybe we need to override it when our language service is turned on?

**Comment by davkean** [comment]
Yeah, I've tried this and it's fixed the issue. Going reopen the project-system one and dup this against it:

https://github.com/dotnet/roslyn-project-system/issues/825

**Comment by davkean** [comment]
Thanks folks!
