### ISSUE TITLE
Template Localization Issues

### ISSUE THREAD

**Issue by singhsarab** [dotnet/sdk#710]
- Class Library (.Net Core) Template
The description for the Class Library template is not localized as expected.
Please find the snapshot below:
![locissueclasslib](https://cloud.githubusercontent.com/assets/18569990/22199174/ceddcf44-e17f-11e6-9d86-9254d6804f42.png)

- xUnit Test (.Net Core) Template
The name and description for the xUnit Test (.Net Core) template is not getting localized.
Note: The name and description for this template are hardcoded in the vstemplate. It should be consumed from package (which takes care of localization of these strings).
Please find the snapshot below:
![xunitlocissue](https://cloud.githubusercontent.com/assets/18569990/22199034/3143d67a-e17f-11e6-8538-8c72c215d56a.png)

**Comment by jinujoseph** [comment]
Class library not picked for translation ? [link](https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.resx#L124)

**Comment by nguerrera** [comment]
The first one is fixed. The string was added late and only recently handed back: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/VSPackage.fr.resx#L148

For "xUnit Test Project" is the project system the right place for these strings?

**Comment by srivatsn** [comment]
@singhsarab for the xunit test project, can you include the string in the same package as the unit test project and update #709?

**Comment by sbaid** [comment]
@srivatsn unit test templates strings are coming from the legacy tuippackage (not public in vs repo) and does not look right place. Where can we author xunit template strings? It can be done in a separate PR. suggest merge this PR.
