### ISSUE TITLE
dogfooding core project system  solution projects don't receive resolved packages after restore complete 

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/sdk#713]
1. open this https://github.com/srivatsn/roslyn-project-system/tree/dogfood (switch to dogfood branch), 
2. wait for full restore
3. See some projects (like Composition.csproj -0 the very first project on top) have yellow nuget packages. 

i debugged that and DT build sends 0 resolved packages. Restore had some issues there , but assets file was created and i am not sure why there no resolved packages found.

**Comment by abpiskunov** [comment]
@natidea @srivatsn

**Comment by srivatsn** [comment]
This looks like an issue in the project itself - not the product.

**Comment by dsplaisted** [comment]
@srivatsn Is this still an issue?

**Comment by srivatsn** [comment]
No this was something odd about the dependency projects that was fixed in the repo itself.
