### ISSUE TITLE
Should RuntimeIdentifier be influencing PlatformTarget?

### ISSUE THREAD

**Issue by bricelam** [dotnet/sdk#715]
They feel orthogonal to me. `RuntimeIdentifier` is about NuGet package artifacts and `PlatformTarget` is about assembly architecture.

Today, to get an AnyCPU exe, you need to do something like this.

```XML
<PropertyGroup>
  <TargetFramework>net451</TargetFramework>
  <RuntimeIdentifier>win7-x64</RuntimeIdentifier>

  <!-- Don't let RuntimeIdentifier influence PlatformTarget -->
  <PlatformTarget>$(Platform)</PlatformTarget>
</PropertyGroup>
```

This also lets you specify the platform using the standard `Platform` property:

```
dotnet build /p:Platform=x86
```

**Comment by dsplaisted** [comment]
What's the point of building a .NET Framework app for AnyCPU if it has NuGet dependencies that are specific to the processor architecture?

I think the background to this was that LibUV has x86 and x64 native libraries, but on .NET Framework we don't support deploying both of them with the app and choosing the right one to load at runtime.

**Comment by bricelam** [comment]
On `Microsoft.Data.Sqlite` (and other packages I've seen), we author our NuGet package to put both the x86 and x64 artifacts on disk for AnyCPU and call `LoadLibraryEx` at runtime to load the appropriate assembly.

But I think you're right. The correct solution is to use the `win7-any` RID. If any libraries like LibUV don't support the runtime loading, they would need to be updated to enable AnyCPU projects.

```XML
<PropertyGroup>
  <TargetFramework>net451</TargetFramework>
  <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win7-any</RuntimeIdentifier>
  <RuntimeIdentifiers>win7-x86</RuntimeIdentifiers>
</PropertyGroup>
```

```
dotnet build /p:RuntimeIdentifier=win7-x86
```

**Comment by bricelam** [comment]
Closing since I believe the current behavior is the correct one.
