### ISSUE TITLE
CopyFilesToOutputDirectory should be skipped if output files are up to date

### ISSUE THREAD

**Issue by billwert** [dotnet/sdk#716]
I noticed this working in VS, but it happens on the console too.

If all the other targets skip because output files are up to date, CopyFilesToOutputDirectory should also be skipped.

Full diag build log attached.

```console 
D:\work\scratch\comp2>dotnet build /v:normal
Microsoft (R) Build Engine version 15.1.503.52602
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/23/2017 8:33:41 PM.
     1>Project "D:\work\scratch\comp2\comp2.csproj" on node 1 (Build target(s)).
     1>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreGenerateAssemblyInfo:
       Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       GenerateBuildDependencyFile:
       Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         comp2 -> D:\work\scratch\comp2\bin\Debug\netcoreapp1.0\comp2.dll
     1>Done Building Project "D:\work\scratch\comp2\comp2.csproj" (Build target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.82
```
```console
D:\work\scratch\comp2>dotnet --version
1.0.0-preview5-004468
```

[build.txt](https://github.com/dotnet/sdk/files/725654/build.txt)

**Comment by rainersigwald** [comment]
This is confusing but I think the right thing is happening.

The [`CopyFilesToOutputDirectory` target](https://github.com/Microsoft/msbuild/blob/765376a043d081569629998867d03e4a5eb9a256/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L3913-L3922) doesn't define `Inputs` and `Outputs`, so it won't be skipped by the MSBuild engine when it's up to date. But the `Copy` task internally implements don't-copy-if-up-to-date functionality, which is observable in your diag log (line 35575):

> Did not copy from file "obj\Debug\netcoreapp1.0\comp2.dll" to file "bin\Debug\netcoreapp1.0\comp2.dll" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match. (TaskId:20)

I don't know why this target was implemented this way long ago. I speculate that it's somewhat more convenient to always have the output of a project in the not-that-verbose log for copy/paste purposes. I use it that way often.

**Comment by billwert** [comment]
Ah, cool. I didn’t dig deeply into the diag log. I also use the output path in the way you say; on (default) minimal verbosity it doesn’t look weird. I only noticed it because I’d kicked verbosity up doing something else. Thanks for taking a look.
