### ISSUE TITLE
resolved nuget packages are not sent, when csproj depends on another csproj with some broken reference

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/sdk#717]
1. Open this solution \\vwdbuild01\Temp\antonpis\repro\MultipleIssues.zip and wait for all restores to happen if any
2. see WebAppllication1 has yellow nuget packages.

Actual:

What is happening is dependencies tree does not receive resolved package references for WebApplication1 at all. Assets file contains them. Notice, that if i remove a reference on ConsoleApp1 , everything starts to work and we receive resolved references for WebApplication1. What makes ConsoleApp1 special is that it has some unknown project reference "MyProject1" and some unknown assembly references. So somehow it affects data that is sent from DT build. 

Expected behavior would be to send resolved data for what ever was successfully resolved and unresolved data for what is unresolved. Otherwise whole tree is yellow and user would not know what dependency was not resolved.

**Comment by abpiskunov** [comment]
@natidea @srivatsn  fyi

**Comment by natidea** [comment]
The problem here is [this line](https://github.com/dotnet/sdk/blob/048acf4121da75b0e8b317c2c3aa54d2c955407c/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageDependencies.cs#L344):
```csharp
Log.LogError(Strings.UnexpectedDependencyWithNoVersionNumber, deps.Id);
```
The error is ending the task prematurely so no outputs are available to downstream tasks. Changing to `LogWarning` fixed this.

**Comment by rainersigwald** [comment]
@natidea You could also set `ContinueOnError="ErrorAndContinue"` [here](https://github.com/dotnet/sdk/blob/42de009e12a80d2ee09e2ec13d6d30e430e1368d/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L154-L157) to still get a fatal error but allow the build to proceed with best-available-information.

I prefer to avoid moving errors to warnings--see the "failed to resolve reference" warning that often is the real problem causing a thousand red compiler errors, but seems less important.
