### ISSUE TITLE
Using the SDK

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#729]
What is the best way to consume the SDK from a non-CLI build? 

Can it be installed / used on a MSBuild 14.0 environment or must I use 15.0?  If it's 15.0 only is it guaranteed to be installed with all builds or is it a modular component?

**Comment by srivatsn** [comment]
Currently there's no acquisition story outside of MSBuild 15.0. It's guaranteed to be installed in the MSBuild that comes with VS. I don't know if MSBuild has any other installer and if they do then it wont be in that one.

**Comment by jaredpar** [comment]
My understanding is that MSBuild is intended to have a more flexible installation in 15.0.  There is not even a guarantee that the C# compiler is installed.  😢 

I'm mainly curious about how we can get this installed in other installations like xcopy installations.

**Comment by dsplaisted** [comment]
The SDK uses lots of new features in MSBuild 15, so apart from acquisition there's still no way it would work on MSBuild 14.

Microsoft/MSBuild#1493 tracks a generic acquisition story for SDKs.  Until that's available, you can set the MSBuildSDKsPath environment variable to point to somewhere you copy the Microsoft.NET.Sdk folder.

**Comment by rainersigwald** [comment]
@jaredpar The only supported installation mechanisms for 15.0 are the VS/Willow installer and the CLI. Those are much closer to xcopy than ever before but we're not going to get all the way for RTW.

**Comment by jaredpar** [comment]
@rainersigwald  Gotcha.  Is there a specific item in MSBuild / here which tracks having this is a bit of an independent component?  I know @dsplaisted linked to one but that's a giant uber issue.  Doesn't track the specific issue.

This is interesting to me because this extension /task bears a lot of similarities to the NuGet asset resolution task in MSBuild.  It's a necessary component to build the majority of .Net repos out there.  But it's only available when you do a full install via Visual Studio (or in this case also CLI).

There are a lot of build environments out there though which simply do not, and will not, do this.  Installing VS / CLI violates their basic build machine guidelines.  The only option for such systems is to hackily install the NuGet asset resolution task.  Not fun for anyone and as you would expect difficult to maintain.  

Would like to avoid this if possible for the SDK.  Should be easy / supported to deploy SDK in these environments.

**Comment by jaredpar** [comment]
For context / inspiration consider the [installation instructions for Maven](https://maven.apache.org/run.html).  It's really as simple as it gets:

- Download
- Unzip
- Go
