### ISSUE TITLE
VS generates documentation file in root of the drive the project is on by default

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#738]
VS sets xml file location to \ClassLibrary1.xml by default (note the slash in beginning) and that caused build to fail because of Access denied to root of drive C: 

$(OutputPath) wasn't being set somehow
Changing to bin\$(Configuration)\$(TargetFramework) worked

**Comment by rrelyea** [comment]
This appeared to be breaking pack. If xml intellisense file creation is badly broken in rtm, should consider fix.

**Comment by davkean** [comment]
A couple of things:

1. What exactly was your repro on this? I think you're hitting this: https://github.com/dotnet/roslyn-project-system/issues/1135.

2. Secondly, what's the partner blocking on this? There's a workaround for it.

3. Thirdly, the UI doesn't respect this yet - but the easiest way to generate documentation file is via: `<GenerateDocumentationFile>true</GenerateDocumentationFile>`

**Comment by davkean** [comment]
I'm going to dup this against #1135, unless your setting this other than via the UI.
