### ISSUE TITLE
PackageReference assembly is not included in the bin dir of a .NET standard project

### ISSUE THREAD

**Issue by ridomin** [dotnet/sdk#747]
Create a .NET standard library project (d15prerel 26127)
Add a NuGet Reference to Json.Net (using PackageReference in the csproj)
Build

Observed:
Newtonsoft.Json.dll is not copied to output

/cc; @rrelyea

**Comment by rrelyea** [comment]
@srivatsn  --- known issue. unni and team feel like this is critical.

**Comment by dsplaisted** [comment]
@rrelyea Isn't this the intended behavior?  My understanding is that generally library projects targeting .NET Standard or .NET Core will not have their dependencies copied to the output folder, and that .NET Core apps generally won't either, and the dependencies will generally be loaded from the packages folder via the deps.json file.

**Comment by ridomin** [comment]
We dont' have a deps.json in .NET Desktop apps. What this means is that a .NET Desktop app that references a .NET Standard Library with some dependencies, will fail at runtime with FileNotFoundException.

**Comment by dsplaisted** [comment]
> We dont' have a deps.json in .NET Desktop apps. What this means is that a .NET Desktop app that references a .NET Standard Library with some dependencies, will fail at runtime with FileNotFoundException.

That sounds like #757

**Comment by srivatsn** [comment]
Duping this against https://github.com/NuGet/Home/issues/4488

**Comment by dasMulli** [comment]
@GreatFireWall what's your issue? a part of it is "by design". you can also open a new issue if something isn't covered.

**Comment by GreatFireWall** [comment]
sorry, resolved.
add <RestoreProjectStyle>PackageReference</RestoreProjectStyle> in project file.

**Comment by christiantinauer** [comment]
@mhingston Did you find a solution to this problem?

**Comment by Sonkkorh** [comment]
add to csproj 
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
after 
<TargetFramework>netstandard2.0</TargetFramework>
may be it hepls

or try change
<TargetFramework>netstandard2.0</TargetFramework>
to 
<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
net472 = .NET Framework 4.7.2 change to your .NET Framework version

**Comment by tastimur** [comment]
> add to csproj
> ` <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`
> after
> `<TargetFramework>netstandard2.0</TargetFramework>`
> may be it hepls
> 
> or try change
> `<TargetFramework>netstandard2.0</TargetFramework>`
> to
> `<TargetFrameworks>netstandard2.0;net472</TargetFrameworks>`
> net472 = .NET Framework 4.7.2 change to your .NET Framework version

It worked for me.

**Comment by gimmi** [comment]
My case:

- Main: `net462` project using `packages.config`
- Lib: `netstandard2.0` project using `<PackageReference>`

Resolve by adding this in the Main project file:

```
<PropertyGroup>
  <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  <RuntimeIdentifier>win</RuntimeIdentifier>
</PropertyGroup>
```

and adding `net462` in the Lib like so:

```
<TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
```
