### ISSUE TITLE
German translation issue with NU1007

### ISSUE THREAD

**Issue by dasMulli** [dotnet/sdk#750]
Looking over the German translations, I find the [translation of NU1007](https://github.com/dotnet/sdk/blob/890e56ee6f0355f0bf0f1971ed85ba8b8629095a/src/Tasks/Microsoft.NET.Build.Tasks/Resources/xlf/Strings.de.xlf#L156-L160) peculiar:
```xml
<source>Dependency specified was '{0}' but ended up with '{1}'.</source>
<target state="new">Die angegebene Abhängigkeit war „{0}“, aber es endete mit „{1}“.</target>
```
I think there are two issues about this. First, the German translation is a bit off - translated back, the second half of the sentence means `but it ended with '{1}'.`. However, I'm unable to come up with a good translation myself without completely rephrasing the sentence and focusing on the meaning - e.g. `Die angeforderte Abhängigkeit war "{0}", bekam jedoch "{1}".`

This message is very similar to NU1012 (`Dependency conflict. '{0}' expected '{1}' but received '{2}'`) which is imho more clearly understandable.

I'd suggest the english version of NU1007 should be replaced with a simpler message or at least the German translation should be updated.
Suggestions: `The requested dependency was "{0}", but has been resolved to '{1}'.`, `…, but received '{1}'`

cc @natidea @janbaltus

**Comment by akoeplinger** [comment]
I think a translation of your last suggestion would still be better, even if the English one isn't updated: `Die angegebene Abhängigkeit war „{0}“, wurde aber mit „{1}“ aufgelöst.`

**Comment by nguerrera** [comment]
@janbaltus

**Comment by janbaltus** [comment]
Fixed translation:
https://github.com/dotnet/sdk/pull/937
