### ISSUE TITLE
Package does not get warning symbol even though it fails to install

### ISSUE THREAD

**Issue by srivatsn** [dotnet/sdk#755]
_From @davkean on January 19, 2017 10:11_

1. Create .NET Core Console App
2. Right-click project, choose Edit ConsoleApp1
3. Add:

``` XML 
  <ItemGroup>
    <PackageReference Include="System"  Version="1.0.0" />    
  </ItemGroup>
```

4. Save

After package restore a bunch of errors in the Error List about how package is isn't compatible, such as:
```
Error		Package System 4.1.311.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System 4.1.311.2 supports: net451 (.NETFramework,Version=v4.5.1)			0	
```

Expected: For dependency to have warning symbol
![image](https://cloud.githubusercontent.com/assets/1103906/22102421/8683e464-de8b-11e6-8786-5753a4534d8c.png)

Actual: The dependency does not have a warning symbol
![image](https://cloud.githubusercontent.com/assets/1103906/22102393/729897e2-de8b-11e6-9fd8-f6521f6fab67.png)

For a brief moment, it also appeared to be passed to the compiler, because the type from a package it references (JSON.NET) was colorized:

![image](https://cloud.githubusercontent.com/assets/1103906/22102512/d156d0c8-de8b-11e6-8a16-ac2c991d43b4.png)

_Copied from original issue: dotnet/roslyn-project-system#1254_

**Comment by srivatsn** [comment]
_From @abpiskunov on January 19, 2017 19:58_

why is this project system issue but not SDK? we display data that comes from SDK. could you please open it in SDK repo instead?

**Comment by srivatsn** [comment]
_From @davkean on January 20, 2017 2:36_

> why is this project system issue but not SDK?

Because I didn't write the code and don't know how this works.

What in particular should we be changing in the SDK? Can you point me a starter so that I can provide a more informed bug when I file over in the SDK?

**Comment by srivatsn** [comment]
_From @abpiskunov on January 20, 2017 18:7_

Sure. All data that you see in the tree , package names, versions and resolution state (except first load where we get evaluation and can get all direct references with unresolved state) we get from the sdk task. So project system just displays data and knows nothing about what version is right or wrong. In this case you would expect "unresolved" package reference, but sdk sends resolved with version 4.1.xxx. Btw, sdk currently does not send unresolved packages at all - it was known but i don't know if there is an issue tracking that. Sri or Nat would know.

**Comment by srivatsn** [comment]
Tried this on the latest build. If a packageref fails to install restore because of wrong version then there's a warning icon. If it restores but is not compatible then it shows the node but shows the diagnostics when the node is expanded. I guess whenever there's a diagnostic it should probably have the warning icon.

**Comment by abpiskunov** [comment]
Why was it resolved then if it is incompatible with current framework? It is bug in nuget and is different behavior comparing to Dev14. I don't mind to add extra logic and check for that, but would prefer to rely on actual data.

**Comment by abpiskunov** [comment]
Found a place here this logic lived , yes we did it in project system indeed, will apply similar logic here.

**Comment by natidea** [comment]
NuGet now emits appropriate warnings on missing packages to error list, and also adds them to the dependencies node.

![image](https://user-images.githubusercontent.com/7732033/27663248-47e37252-5c16-11e7-9169-82824a8a17f6.png)
