### ISSUE TITLE
PreserveCompilationContext targets incorrectly uses WarningsAsErrors

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#756]
dotnet-migrate (since corrected) and PreserveCompilationContext targets use the property `WarningsAsErrors`. The correct property is `TreatWarningsAsErrors`. PreserveCompilationContext needs to be updated

**Comment by pranavkm** [comment]
Related work item: https://github.com/dotnet/cli/issues/5487

**Comment by natemcmaster** [comment]
Ok, looks like TreatWarningsAsErrors is correct then. PreserveCompilationContext targets should be updated to reflect this.
