### ISSUE TITLE
project.asset.json file name causing compile errors for solutions where multiple projects share the same intermediate output folder

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/sdk#760]
The [ApplicationInsights-logging repo](https://github.com/Microsoft/ApplicationInsights-dotnet-logging) uses a directory structure where all intermediate output files from all projects in the repo end up in the parent folder file. This is how it looks on disk, conceptually

RootFolder
 --bin
 --obj
 ---- source-repo-folder
--------project1
--------project2
   …
--------projectN

and is described in more detail in [Global.props](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/Global.props)

To achieve that Global.props redefines BaseIntermediateOutputPath and IntermediateOutputPath.

Right now all projects in the repo use msbuild14/csproj tooling, but when I tried to add a couple of projects that produce netstandard13 assemblies and uses msbuild15 tooling, I run into an issue. I noticed is that “dotnet restore” produces a file called “project.asset.json”, with the same name regarding of the project name. This file is written into obj directory (actually obj\$(Configuration), but it does not matter). This file also seems to be used during build. The result is that whatever project got its packages restored last, that project.assets.json will be used for building all projects in the repo. Result is a bunch of “String is not defined” and the like errors from projects were restore earlier (and their project.asset.json was overwritten).

Not sure what the right fix is but one option would be to add a prefix to the project.asset.json file that is derived from the project name.

Right now I worked around this by redefining BaseItermediateOutputPath in my projects that use the new tooling. This way the project.assets.json ends up in the obj folder under the project folder and everything seems to work, but that is not what the repo owners intended.

**Comment by karolz-ms** [comment]
@eerhardt suggested the following definition for BaseIntermediateOutputPath

<BaseIntermediateOutputPath>$(RootFolder)\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>

which is probably a better solution than mine. But he also suggested to open an issue about this, so I did

**Comment by onovotny** [comment]
This has always been an issue with build artifacts as each project assumes its own `BaseIntermediateOutputPath`. In other projects where we put multiple csproj files in a directory, we had to override that to include per-project subdirectories to the `BaseIntermediateOutputPath`. 

I don't think this a NuGet specific issue.

**Comment by karolz-ms** [comment]
OK, thanks Oren. I tested Eric's suggestion and it seems to work well. I am going to close this for now.

**Comment by ulrichb** [comment]
The workaround above (setting the `BaseIntermediateOutputPath` property) does not work out for me in a project, where I reference a NuGet package with an MSBuild .targets with adds an assembly references. The concerned package is `JetBrains.ReSharper.SDK`.

Repro sample:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>

    <!-- Doesn't work (see 'Class' below): -->
    <BaseIntermediateOutputPath>obj\XXX\</BaseIntermediateOutputPath> 
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="2016.3.20170126.124206" />
  </ItemGroup>

</Project>
```

```C#
using System;

public class Class
{
    public Class()
    {
        // Works fine:
        Console.WriteLine(typeof(JetBrains.Annotations.NotNullAttribute));

        // Resolve error when using the overridden "BaseIntermediateOutputPath":
        Console.WriteLine(typeof(JetBrains.ReSharper.Psi.IDeclaredElement));
    }
}
```

Note that the `BaseIntermediateOutputPath` workaround worked fine with non .NET Core projects (see [ImplicitNullability.Plugin.R20163.csproj](https://github.com/ulrichb/ImplicitNullability/blob/8d8ef6f73980542b8f7ca983d17a30c8a6a74097/Src/ImplicitNullability.Plugin/ImplicitNullability.Plugin.R20163.csproj#L14)).

**Comment by dsplaisted** [comment]
I suspect it is something else in the targets file from the package that is causing problems. Can you open a separate issue for this?

**Comment by ulrichb** [comment]
@dsplaisted OK. Created #980.
