### ISSUE TITLE
Implicit metapackage package reference: need more documentation

### ISSUE THREAD

**Issue by BladeWise** [dotnet/sdk#764]
As requested by @livarcocc  [here](https://github.com/dotnet/cli/issues/5346#issuecomment-276176808) I am filing this issue regarding implicit metadata package reference and the fact that there are few and sparse information regarding this feature and how to opt-out or customize its behavior.
The [most promising reference page](https://aka.ms/sdkimplicitrefs) does not talk about `DisableImplicitFrameworkReferences`, `NetStandardImplicitPackageVersion` and `NetCoreAppImplicitPackageVersion` properties, moreover it does not mention (as shown in [this issue](https://github.com/dotnet/sdk/issues/686#issuecomment-276094320)) the need to specify `RuntimeFrameworkVersion` when targeting a specific `NetAppCore.Libray` package.

Another point to notice is that the following warning
> A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs

at least in my case, would appear consistently in projects created with RC2, but never appeared in new projects created with RC3 having an explicit reference to the `NETStandard.Library` package.

**Comment by srivatsn** [comment]
@morrisjoe @blackdwarf - can you look into improving the docs here?

**Comment by blackdwarf** [comment]
@srivatsn not a problem. However, can we see about this last bit:

> at least in my case, would appear consistently in projects created with RC2, but never appeared in new projects created with RC3 having an explicit reference to the NETStandard.Library package.

This could indicate a potential product issue...

**Comment by dsplaisted** [comment]
@BladeWise Can you share a project created with RC3 where you've added an explicit PackageReference for NETStandard.Library but it's not showing you the warning?

**Comment by blackdwarf** [comment]
@dsplaisted I just did this: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="NetStandard.Library" Version="1.6.0" />
  </ItemGroup>

</Project>
```

No warning on build.

**Comment by dsplaisted** [comment]
@blackdwarf The issue there is that the capitalization doesn't match, which was fixed by #733.  So I would expect the error to show up in a version of VS that has that fix (and in my testing it does).

**Comment by blackdwarf** [comment]
@dsplaisted okaaay...so what is the capitalization I need to use? Of course, @BladeWise should add his own repro to see if it is the same issue...

**Comment by dsplaisted** [comment]
@blackdwarf `NETStandard.Library` - not exactly something that most people are going to get correct when manually typing this into the project 😬

**Comment by blackdwarf** [comment]
@dsplaisted ok, that worked. That is not intuitive. :(

@BladeWise I don't understand your final comment. The document on that link does specify the usage of `<RuntimeFrameworkVersion>`. Is there more information that it is not covering?

**Comment by BladeWise** [comment]
@blackdwarf Regarding `<RuntimeFrameworkVersion>`, it is not clear that it is a requirement when targeting a specific `NETStandard.Library` version, and does not give you enough information regarding when you have to use it.
The docs say that
> If you need a specific version of the runtime , you should use the `<RuntimeFrameworkVersion>` property in your project.

but I, for one, don't know if I need a specific version of runtime or not. In my case I simply referenced a library that targeted a specific version of `NETStandard.Linbary`, and NuGet raised a warning regarding a package downgrade.  The information I lack, reading at the docs, is how can I know if a specific version of `NETStandard.Library` requires a specific version of the runtime? Should they always match?
Regarding `<NetStandardImplicitPackageVersion>`, I one of the referenced issues that the runtime is automatically resolved if you use a specific version, but the property supports floating version, and in that case the `<RuntimeFrameworkVersion>` is not deduced. This is another bit of information that could be relevant, I suppose.

@dsplaisted In my case the casing was correct, but I tried to replicate the issue and was not able to while editing the project by hand. Then, I noticed that the issue is caused by the NuGet update operation.
Consider this:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.2.0-*" />
  </ItemGroup>
</Project>
```
VS2017 complains about package downgrade. If you go to the `Manage NuGet Packages` window and perform an update of the `NETStandard.Library`, this is the result:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.2.0-*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="NETStandard.Library" Version="1.6.2-beta-24913-01" />
  </ItemGroup>
</Project>
```
Notice the `Update="NETStandard.Library"`. In this case, no compiler warning is issued, but to be honest, I don't even know if the PackageReference definition is legal, so...
