### ISSUE TITLE
Ability to generate backward compatible packages

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#769]
I tried to use packaging task from the SDK for [Microsoft.DiaSymReader.Portable](https://www.nuget.org/packages/Microsoft.DiaSymReader.PortablePdb/) package, but couldn't figure out how to add backward-compatible target frameworks in the package. Currently the package has the following structure:

```
    <dependencies>
      <group targetFramework="portable-net45+win8">
       ...
      </group>
      <group targetFramework="netstandard1.1">
       ...
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\portable-net45+win8" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\portable-net45+win8" />
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\net45" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\net45" />
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\netstandard1.1" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\netstandard1.1" />
  </files>
```

```Microsoft.DiaSymReader.Portable.csproj``` only builds once (targeting ```netstandard1.1```) and the same DLL is then packaged to ```lib\portable-net45+win8``` and ```lib\net45``` and ```lib\netstandard1.1```. 
The package produced by the SDK task only contains ```netstandard1.1```. Is there a way to fill in the other targets without writing the entire .nuspec by hand?

**Comment by srivatsn** [comment]
The pack SDK is built out of the NuGet repo. Moving this issue there.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4461
