### ISSUE TITLE
Add AutoReferenced attribute to implicit package references

### ISSUE THREAD

**Issue by emgarten** [dotnet/sdk#771]
PackageReferences in the NETCore SDK should add ``AutoReferenced`` to mark them as implicit references. NuGet will disable options to uninstall or update these packages in the Package Manager UI.

Example
```xml
<PackageReference Include="NuGet.Versioning" Version="3.5.0">
  <AutoReferenced>true</AutoReferenced>
</PackageReference>
```

NuGet issue: https://github.com/NuGet/Home/issues/4044

**Comment by abpiskunov** [comment]
Note: when this is changed CollectSDKReferencesDesignTime and PreprocessPackageDependenciesDesignTime need to be updated to detect implicit packages correctly.

**Comment by dsplaisted** [comment]
What does the `AutoReferenced` property do?  Does it hide these packages from the Package Manager UI entirely, or just from the Updates pane, or does it show them in the update pane but not allow them to be upgraded, or what?

We are already setting the `IsImplicitlyDefined` property on our implicit package references.  `AutoReferenced` seems like it would mean the same thing but here it would have a different effect.  Should we consider either unifying on one term, or using a name that's more explicit about what the effect is on the NuGet UI, such as `HideFromUI` or `HideUpdatesFromUI`?

**Comment by emgarten** [comment]
With ``AutoReferenced`` it is still shown in the UI but read only essentially, no updates are shown and the package cannot be modified. They seem like similar attributes.

**Comment by emgarten** [comment]
> Should we consider either unifying on one term, or using a name that's more explicit about what the effect is on the NuGet UI, such as HideFromUI or HideUpdatesFromUI?

We've had a few discussions on the name from the NuGet side already and settled on ``AutoReferenced``,  would it be possible to change ``IsImplicitlyDefined`` to ``AutoReferenced``? How many places is this set already?

//cc @rrelyea @davkean

**Comment by rrelyea** [comment]
Sounds like at this stage, we should use IsImplicitlyDefined as the metadata in the csproj -- to avoid having to take 3 changes. Instead, we'll adapt a bit and only need our change.
We'll close this then.
