### ISSUE TITLE
Aspnet core application build failed "Error Duplicate 'Content' items were included"

### ISSUE THREAD

**Issue by shibut12** [dotnet/sdk#773]
I updated my Visual studio Community edition to RC 3 26127.0 version. I modified my csproject file to accommodate new changes. But for some reason, while building the application, I'm getting following error. 

`Error		Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. The duplicate items were: 'web.config'; 'Views\Home\Error404.cshtml'; 'Views\Home\Index.cshtml'; 'Views\Post\Add.cshtml'; 'Views\Post\disqusCommentsPartialView.cshtml'; 'Views\Post\Get.cshtml'; 'Views\Shared\_Footer.cshtml'; 'Views\Shared\_GoogleAnalytics.cshtml'; 'Views\Shared\_Layout.cshtml'; 'Views\Shared\_Navbar.cshtml'; 'Views\_ViewImports.cshtml'; 'Views\_ViewStart.cshtml'; 'appSettings.json'; 'hosting.json'; 'Properties\launchSettings.json'	MightyBlog	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets	188`	

Here is my csproject file
```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version=" 1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0-preview4-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.0" />
    <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Web" Version="1.0.0-alpha-20161104-2-112" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
</Project>
```

Anybody faced similar issue?

**Comment by dasMulli** [comment]
You still have a package reference to `Microsoft.NET.Sdk.Web` which is no longer needed since the Sdk is now included via the `<Project Sdk="…">` attribute. (btw, you can also remove the reference to `Microsoft.NETCore.App` which is not inferred from the `TargetFramework`)

**Comment by shibut12** [comment]
That worked, I'm marking this issue closed. Thanks

**Comment by 5arif** [comment]
i get the same error when try to deploy to heroku 

`remote:   NuGet Config files used:
remote:       /app/.nuget/NuGet/NuGet.Config
remote:
remote:   Feeds used:
remote:       https://api.nuget.org/v3/index.json
remote:
remote:   Installed:
remote:       187 package(s) to /tmp/tmp.gFsb85wxmy/app/AutoCore.Service/AutoCore.Service.csproj
remote:       211 package(s) to /tmp/tmp.gFsb85wxmy/app/AutoCore.Entity/AutoCore.Entity.csproj
remote:       789 package(s) to /tmp/tmp.gFsb85wxmy/app/AutoCore.Web/AutoCore.Web.csproj
remote: dotnet publish /tmp/tmp.gFsb85wxmy/app/AutoCore.Web --output /tmp/build_77b733fd6a0e0faffa735382e9ff6398
remote: Microsoft (R) Build Engine version 15.1.545.13942
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote: /app/tmp/cache/dotnet/1.0.0-rc4-004771/sdk/sdk/1.0.0-rc4-004771/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.DefaultItems.targets(188,5): error : Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'wwwroot/css/app/site.css'; 'wwwroot/css/app/style-based.css'; 'wwwroot/css/app/stylish-portfolio.css'; 'wwwroot/css/libs/animate.css'; 'wwwroot/css/libs/bootstrap/css/bootstrap.css'; 'wwwroot/css/libs/bootstrap/css/bootstrap.css.map'; 'wwwroot/css/libs/bootstrap/css/bootstrap.min.css'; 'wwwroot/css/libs/bootstrap/css/bootstrap.min.css.map'; 'wwwroot/css/libs/bootstrap/fonts/glyphicons-halflings-regular.eot'; 'wwwroot/css/libs/bootstrap/fonts/glyphicons-halflings-regular.svg'; 'wwwroot/css/libs/bootstrap/fonts/glyphicons-halflings-regular.ttf'; 'wwwroot/css/libs/bootstrap/fonts/glyphicons-halflings-regular.woff'; ]
remote:  !     Push rejected, failed to compile .NET Core app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to autologistic.
remote:`

my .csproj file 

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
    <UserSecretsId>d21d51a2-1f0b-4a4c-9919-980c2d216c28</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />

  <ItemGroup>
    <Content Remove="wwwroot/js\libs\bootstrap\bootstrap.js" />
    <Content Remove="wwwroot/js\libs\bootstrap\bootstrap.min.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\css\app\site.css" />
    <Content Include="wwwroot\css\app\style-based.css" />
    <Content Include="wwwroot\css\app\stylish-portfolio.css" />
    <Content Include="wwwroot\css\libs\animate.css" />
    <Content Include="wwwroot\css\libs\bootstrap\css\bootstrap.css" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="WebMarkupMin.AspNetCore1" Version="2.3.0" />
    <PackageReference Include="WebMarkupMin.NUglify" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\Receiving\" />
    <Folder Include="wwwroot\css\bundle\" />
    <Folder Include="wwwroot\js\bundle\" />
    <Folder Include="wwwroot\js\libs\requirejs\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoCore.Entity\AutoCore.Entity.csproj" />
    <ProjectReference Include="..\AutoCore.Service\AutoCore.Service.csproj" />
  </ItemGroup>
</Project>
`
