### ISSUE TITLE
“dotnet-osx-x64.latest.pkg” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by vlad0** [dotnet/sdk#7735]
## Steps to reproduce
Download .NET Core Installer for Mac OS X

## Expected  behavior
No security issues.

## Actual behavior
When I am trying to install the package I get this error: 
“dotnet-osx-x64.latest.pkg” can’t be opened because it is from an unidentified developer.
Your security preferences allow installation of only apps from the App Store and identified developers

## Environment data
`dotnet --info` output:

 $ dotnet --info                                                                                                           [ruby-2.0.0p648]
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

**Comment by daveyostcom** [comment]
It’s happening again for 6.0.2, still, after being released for a few days.
![image](https://user-images.githubusercontent.com/8748/153740345-40ea61e0-0ad6-4925-8cab-7925e1868ec7.png)

**Comment by halcwb** [comment]
And happened again: https://github.com/dotnet/sdk/issues/45523
