### ISSUE TITLE
Allow disabling of copying resource assemblies from NuGet packages during publish

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/sdk#774]
Many NuGet packages (including [those](https://www.nuget.org/packages/microsoft.Data.edm) [shipped](https://www.nuget.org/packages/microsoft.Data.odata) [by](https://www.nuget.org/packages/Microsoft.Data.Services.Client) [Microsoft](https://www.nuget.org/packages/System.Spatial)) include localized resource satellite assemblies in the main package. This can greatly inflate the publish output size of a typical ASP.NET Core application (like https://github.com/aspnet/live.asp.net) for no benefit in the cases where localized resources from such packages aren't desired or needed.

In this case, the publish output size grows from 12 MB to 26 MB due to the resource assemblies.

It would be great to have an MSBUILD property that could be set in the application's project file to disable copying of satellite assemblies from NuGet references to the publish folder.

**Comment by DamianEdwards** [comment]
Potential workaround for now:
``` xml
<Target Name="RemoveSatellitesFromPublish" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ReferenceSatellitePaths)" />
    </ItemGroup>
  </Target>
```

**Comment by DamianEdwards** [comment]
Workaround doesn't seem to work as the host fails if any assemblies listed in the deps.json aren't present:
```
Error: assembly specified in the dependencies manifest was not found -- package: 'microsoft.data.edm', version: '5.6.4',
path: 'lib/portable-net45+wp8+win8+wpa/de/Microsoft.Data.Edm.resources.dll'
```

**Comment by DamianEdwards** [comment]
@kieranmo suggested having a property to set the desired language outputs (like ClickOnce), so that only resources for those languages would be included. I like that idea.
e.g.

``` xml
<PropertyGroup>
  <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
</PropertyGroup>
```

**Comment by DamianEdwards** [comment]
Yay!!!

**Comment by Flithor** [comment]
Can it support wildcards to match the same parent culture?
Such as "en-*" to match all child culture of "en" such as "en-AU, en-CA, en-US".
