### ISSUE TITLE
Runtimeconfig.dev.json and runtimeconfig.json are always generated regardless of the project being up-to-date

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#777]
The runtimeconfig.dev.json and runtimeconfig.json files are rebuilt regardless of whether the project is update to date:

1. Build
2. Wait 1 minute
3. Build

Expected: No files in the output to be updated
Actual: Runtimeconfig.dev.json and runtimeconfig.json are updated.

**Comment by srivatsn** [comment]
Dupe of #496
