### ISSUE TITLE
AssemblyInfo gets regenerated every design-time build regardless of whether anything has changed

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#778]
Not sure if this a good way to handle this - but the AssemblyInfo gets regenerated every single design-time build, regardless of whether anything has changed. It would be nice to avoid that.

**Comment by nguerrera** [comment]
@davkean how did this not prevent the fix we just made to pass the host compiler flag from being validated?

**Comment by dsplaisted** [comment]
This would probably be fixed by #1007

**Comment by nguerrera** [comment]
Indeed, this no longer repros. Turned on design-time build pane. I can see design-time builds running without timestamp on assembly info changing. This was fixed.
