### ISSUE TITLE
non-existent .bowerrc appearing in VS2017

### ISSUE THREAD

**Issue by Jabbersii** [dotnet/sdk#780]
(Not sure if this is correct place to report this)

I'm using VS2017 RC3, with an ASP.NET Core 1.1 project.
A `.bowerrc` file is appearing in my solution explorer. This file does not exist on my computer. I'm not using bower, or any frontend tools/frameworks in my project.
The icon for the file is the generic file icon, with a yellow warning sign in the corner. VS reports no error when I try to open the file.
I can delete the file without error, but it will reappear the next time VS is opened.

**Comment by srivatsn** [comment]
This issue was moved to aspnet/websdk#112
