### ISSUE TITLE
Unresolved packages data format should be consistent with resolved ones

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/sdk#790]
See this issue for context https://github.com/dotnet/sdk/issues/451 

Proposal: return unresolved and resolved package sin the same dataset and discover them from assets.json file.

**Comment by abpiskunov** [comment]
FYI @natidea @srivatsn

**Comment by natidea** [comment]
Closing in favor of https://github.com/dotnet/project-system/issues/2515
