### ISSUE TITLE
dotnet publish does not copy the documentation file with csproj

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#795]
## Steps to reproduce
Have a solution with multiple projects
The main "web" project has the GenerateDocumentationFile set to true

## Expected  behavior
When I run dotnet publish of the main "web" project, I expect that the XML documentation file is copied into the publishing folder. (Note the build will generate the file as it should.)

## Actual behavior
When I run dotnet publish of the main "web" project, it does not copy the XML documentation file to the psublish folder.

## My workaround
My current workaround is to update the csproj of the main web project and manually copy the file:
`
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
		<ItemGroup>
			<DocFile Include="bin\**\**\PROJECT_XYZ.xml" />
		</ItemGroup>
		<Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false"  />
  </Target>
`

## Environment data
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

This issue has been copied over from https://github.com/dotnet/cli/issues/5562.

**Comment by davkean** [comment]
@masterjs What's the expectation around this? Why do you expect the XML file to be published - it's a dev artifact?

**Comment by masterjs** [comment]
Hello @davkean ,
My project is a big WebAPI netcore and like many API, I'm using Swagger whom needs the XML documentation file if I want to have a good documentation of my API. Also, it use to work when I was using .xproj.

Also, another of my project (solution with multiple projects) has the flag GenerateDocumentationFile turned On and somehow that one is copied over. 

So in a nutshell, it use to work and now I see two different things contradicting themselves.

thank you,
JS

**Comment by eerhardt** [comment]
Do you also expect that P2P references' doc files are published?  What about doc files from NuGet packages?

I think since documentation files aren't typically used at runtime, they shouldn't be published by default.

Projects that need this behavior can add their own target that runs during publish and adds the documentation file to the @(ResolvedFileToPublish) item, which will copy the xml file to the publish directory.  It isn't necessarily behavior that the core SDK has to provide.

**Comment by masterjs** [comment]
For my case, since I'm a web api I only care about the generated documentation. I dont mind and understand if it needs a little bit more work like I did for my work-around. The main problem was that it was a different behavior from xproj when I migrated to csproj and the documentation file of other projects was still copied.

**Comment by dasMulli** [comment]
Documentation files are what Swashbuckle can use at runtime to enrich the generated Swagger API description. It's nice for Web API projects because you just need to write a documentation once that works for IntelliSense, doc generation tools AND runtime Swagger generation, making it more than just a dev artifact. So it does make sense to publish it with the application in some scenarios.

**Comment by filipw** [comment]
I agree, it's necessary for situations like auto-generated Swagger.
It also worked for `project.json` so it's really a breaking change for folks migrating to `csproj`

**Comment by dasMulli** [comment]
using xml comments for swagger is already [documented on docs.microsoft.com](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger#xml-comments) by @spboyer so maybe the doc would need to be updated that this won't work with the 1.0 tooling when published?

**Comment by spboyer** [comment]
The swagger doc has been updated in the csproj branch, will be pushing that to live when RTM is released approx Mar 7

**Comment by spboyer** [comment]
You can modify the csproj file to add the necessary files to pipeline that MSBuild needs to package up for the publish process.  To add the Swagger files add the following snippet to the end of you *.csproj file before `</Project>`

```xml
  <Target Name="SwaggerFile">
    <ItemGroup>
      <_CustomFiles Include="bin\(Configuration)\(Platform)\*.xml" />
      <FilesForPackagingFromProject Include="%(_CustomFiles.Identity)">
        <DestinationRelativePath>%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>

  <PropertyGroup>
      <CopyAllFilesToSingleFolderForPackageDependsOn>
        SwaggerFile;
        $(CopyAllFilesToSingleFolderForPackageDependsOn);
      </CopyAllFilesToSingleFolderForPackageDependsOn>
  </PropertyGroup>
```

This copies the documentation file to the root of the project prior to the MSBUILD process running . `dotnet publish` will place the file in whatever output location you specify and configuration.

cc:/ @sayedihashimi

**Comment by spboyer** [comment]
@natemcmaster Is this something that needs to be added to the convert doc?
http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/
and/or
https://github.com/mairaw/docs/blob/9aa20043b5840d98813b083dee4c26eba3451d6b/docs/core/tools/project-json-to-csproj.md

**Comment by natemcmaster** [comment]
@spboyer probably not. Those docs are focused on converting project.json to MSBuild. When I wrote the docs, I only included the breaking changes between PJ and csproj that were relevant to the format of the file. I made a [followup post](http://www.natemcmaster.com/blog/2017/02/01/project-json-to-csproj-part2/) to address breaking changes. It might be worth added an official doc with similar content.

**Comment by eerhardt** [comment]
IMO - this highlights the main advantage of moving from project.json to MSBuild.  No longer does the core build logic need to take care of _every_ scenario.  If the core build logic doesn't work for your scenario, you have the full power to make it work.

What is even better, is someone can make a "SwaggerTools" NuGet package that will inject this MSBuild logic into a project.  Then all app projects need to do is add a `<PackageReference>` to that new package, and they get this functionality.

**Comment by natemcmaster** [comment]
> this highlights the main advantage of moving from project.json to MSBuild

+1. MSBuild extensibility is awesome.

But back to the main point of this issue. Should the SDK include xml docs in the published output by default?

**Comment by sayedihashimi** [comment]
Sometimes the xml files can be large. Do we have any numbers on the size/time impact for publishing if we did this?

**Comment by dasMulli** [comment]
@spboyer, cc @GuardRex: another workaround would be to use the `$(DocumentationFile)` property to emit items that are respected during publish like this:

```xml
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>

<Target Name="IncludeDocFile" BeforeTargets="PrepareForPublish">
  <ItemGroup Condition=" '$(DocumentationFile)' != '' ">
    <_DocumentationFile Include="$(DocumentationFile)" />
    <ContentWithTargetPath Include="@(_DocumentationFile->'%(FullPath)')"
                           RelativePath="%(_DocumentationFile.Identity)"
                           TargetPath="%(_DocumentationFile.Filename)%(_DocumentationFile.Extension)"
                           CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Target>
```

If more files are needed, more `_DocumentationFile` items using a pattern could be used.

**Comment by billpratt** [comment]
Is this bug actively being worked on? For now we are using csproj work arounds listed above but not ideal.

**Comment by livarcocc** [comment]
I am not sure about turning this on by default, though maybe we should have a more accessible way to have this on during publish.

**Comment by billpratt** [comment]
Having a way to enable it would be ideal considering Swashbuckle has a dependency on using this for swagger documentation.

**Comment by spboyer** [comment]
In Visual Studio, we should have the option either in the *Properties* of the project where you enable the xml documentation file and/or right click action to include the file in the output or publish location which then creates the entry in .csproj like @dasMulli put above.

For non-VS users, documentation noting how to do this or simplifying the entry in .csproj via a flag maybe a good/better solution.

_Proposed_ : requires change to tooling 
```xml
<PropertyGroup>
  <GenerateDocumentationFile
        CopyToPublishDirectory="PreserveNewest" 
        Option="true" />
</PropertyGroup>
```

cc:/ @sayedihashimi

**Comment by dasMulli** [comment]
I'd like to see a more built-in solution like building SDK support for:
```xml
<PropertyGroup>
  <PublishDocumentationFile>true</PublishDocumentationFile>
  <!-- Next one is a nice to have -->
  <PublishDependencyDocumentationFiles>true</PublishDependencyDocumentationFiles>
</PropertyGroup>
``` 

This would be easy for tooling (=> checkbox) and hand-editing `csproj` files. Defaults could also be set easily via the SDK, WebSDK or NuGet packages (Swashbuckle).

**Comment by jchadwick** [comment]
@spboyer For what it's worth, your workaround above (CopyAllFilesToSingleFolderForPackageDependsOn) is not working for me - the xml file does not get copied.  Are you sure that's correct?

**Comment by jbegithub** [comment]
@jchadwick +1 
CopyAllFilesToSingleFolderForPackageDependsOn doesn't work for me either, is it platform independet?

**Comment by dasMulli** [comment]
afaik, `CopyAllFilesToSingleFolderForPackageDependsOn` is a thing of the (now "old") webdepoy target files, the .net sdk now uses a different publishing process.

**Comment by jbegithub** [comment]
Ok, but I guess there's still no build in way to get the xml-documentation file copied to the published dir.?
Any other workaround to accomplish this?

**Comment by spboyer** [comment]
@jchadwick it does work - make sure you are doing this one -> https://github.com/dotnet/sdk/issues/795#issuecomment-284029372 and not the [proposed one](https://github.com/dotnet/sdk/issues/795#issuecomment-288414461)

**Comment by jbegithub** [comment]
doesn't work for me on ubuntu, ended up using a python oneliner:
`<Target Name="MyPostCompileTarget" AfterTargets="Publish">
    <Exec Command="python -c %22from shutil import copyfile; copyfile('$(OutDir)/doc.xml', '$(PublishDir)/doc.xml')%22 " />
  </Target>`

**Comment by billpratt** [comment]
This works for me. Verified on Windows, macOS and Ubuntu

```
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\$(Configuration)\$(TargetFramework)\*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>
```

**Comment by eerhardt** [comment]
This Target will work on all platforms and in web and console apps:

```XML
  <Target Name="CopyDocumentationFile"
          AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Include="@(FinalDocFile)"
                             RelativePath="@(FinalDocFile->'%(Filename)%(Extension)')" />
    </ItemGroup>
  </Target>
```

`ResolvedFileToPublish` is the Item that publish uses to know which files to put in the publish folder.  The `Include` is the file's source, and the `RelativePath` is where inside the publish folder the file should be placed.
`ComputeFilesToPublish` is exactly as its name implies - it is the Target that gathers all the files to be published.

**Comment by spboyer** [comment]
@eerhardt has the best option. Created sample project for ref https://github.com/spboyer/copydocfile-example

**Comment by thoean** [comment]
That's our version, which works on Linux, Windows and Mac - similar what @eerhardt provided.

In the main section, ensure the documentation file gets generated:

```xml
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
```

Then a separate target with the copy process:

```xml
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\*\*\MyProject.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>
```

**Comment by RehanSaeed** [comment]
What about if you want to include documentation files for other package referenced assemblies. My scenario is that I have moved a shared controller to a NuGet package and want to include it's documentation file in my Swagger page.

**Comment by jchadwick** [comment]
@spboyer @eerhardt Thanks for the solution and the demo code.  This works great.  Eager to see this built in!

**Comment by vdevappa** [comment]
For those having issues with this and service fabric, there is a slight tweak to the .csproj change you need to make to get it to work:

`<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\x64\$(Configuration)\$(TargetFramework)\win7-x64\*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>`

Also remember that sometimes the property group is not completely changed by Visual Studio. Ensure the below lines are present:

`<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net462\win7-x64\WebApiSwagger.XML</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DocumentationFile>bin\Debug\net462\win7-x64\WebApiSwagger.XML</DocumentationFile>
  </PropertyGroup>`

I have verified this works.

**Comment by nukec** [comment]
Nothing here suggested works for me. I've tried to use @eerhardt 's answer, nothing is happening. If I click manual publish on project, xml document is added into the publish list.

I am not sure what am I doing wrong this is my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
	<PreserveCompilationContext>true</PreserveCompilationContext>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp1.1\Api.xml</DocumentationFile>
  </PropertyGroup>
 
  
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\*\*\Api.xml" />
    </ItemGroup>

    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>

  <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="identityserver4_log.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Api.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.0.2" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="2.0.1" />
    <PackageReference Include="Carable.Swashbuckle.AspNetCore.DocumentWithCode" Version="0.0.4" />
    <PackageReference Include="Castle.Core" Version="4.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.0.2" />
    <PackageReference Include="IdentityServer4" Version="1.5.2" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="1.2.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="1.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging.ApplicationInsights" Version="1.1.0" />
    <PackageReference Include="StructureMap.Microsoft.DependencyInjection" Version="1.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
	<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\Default\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Api.Business\Api.Business.csproj" />
  </ItemGroup>


</Project>
```

**Comment by ravetroll** [comment]
I found the file was being created on my desktop from VS2017 in the 'Release' Configuration but was not being created in VSTS on release configuration

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp1.1\Host.xml</DocumentationFile>
  </PropertyGroup>`

I wondered if perhaps the 'AnyCPU' Platform was not being applied in VSTS so I removed that part from my csproj file and it built properly including my documentation file in VSTS in 'Release' so I guess AnyCPU is not the right platform setting or default platform setting in VSTS

  `<PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DocumentationFile>bin\Release\netcoreapp1.1\Host.xml</DocumentationFile>
  </PropertyGroup>`

**Comment by pgmolloy** [comment]
I would like to vote for adding the swagger xml file to the build. My opinion is that the swagger xml file is NOT a doc file but a "necessary component" similar to a web config or an app settings file required by my Azure API to run. When deploying to Azure, my API will not start without the file. Just two cents worth :)

**Comment by dasMulli** [comment]
@pgmolloy does anything not work in your publish scenario? This has been implemented.

For those having trouble getting `DocumentationFile` to work, I recommend deleting it and letting MSBuild autogenerate a correct path by setting `GenerateDocumentationFile` instead:

```xml
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```

**Comment by pgmolloy** [comment]
Hi Martin, I have finally got this to work. I really don't know what fixed my issue as I decided to delete all swagger tooling and files. Redeployed the API without swagger and made sure all worked fine. I then added swagger tooling and let MSBuild do everything again and wullah all is fine. Thanks Martin for your help. Cheers Peter

**Comment by aeroson** [comment]
None of the above worked for me, ended up including the ,xml file into project with Properties: "Build Action": Content, "Copy to Output Directory": Copy always

**Comment by peterneave** [comment]
Realised that I was calling msbuild with Release configuration (the same way the build agents were). I solved my problem by simply including the Documentation file in my project.

`  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    
    <DocumentationFile>bin\Api.XML</DocumentationFile>
  </PropertyGroup>`

**Comment by djarvis** [comment]
None of any of the entire vastness of suggestions above worked for me.  Is there some sort of updated solution that everyone else knows about except for me?

**Comment by dsplaisted** [comment]
@djarvis With the latest SDK, you should simply be able to set the GenerateDocumentationFile property to true, and the XML files will be published by default

**Comment by djarvis** [comment]
@dsplaisted Where do I set this setting?  .csproj?  .pubxml?  Still can't get it to both generate and publish it.

**Comment by livarcocc** [comment]
It is a MSBuild property that you can set in your csproj.

```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```

**Comment by scottaddie** [comment]
@livarcocc Which version of the .NET Core SDK is required to use this MSBuild property?

**Comment by livarcocc** [comment]
I don't remember exactly, but I always recommend installing the latest one, 2.1.300. Otherwise, 2.1.201 should also be a good one, without all the 2.1 changes.

**Comment by dasMulli** [comment]
`GenerateDocumentationFIle`: 1.0.0
But has since had a bug for VB projects.

`PublishDocumentationFile`, `PublishReferencesDocumentationFiles`: 2.0.0
These both default to `true` to match the behavior of project references - `dotnet publish` would copy the xml of `<ProjectReference>`es but not of the published application. Now copies all documentation by default and introduces these to properties to allow opting out of documentation publishing through these properties - https://github.com/dotnet/sdk/pull/1062

2.1.300 fixed the VB issue - https://github.com/dotnet/sdk/pull/1848

**Comment by louislewis2** [comment]
Hi guys,

Been working on a project where i am required to include xml documentation. 
This works as expected, when adding the GenerateDocumentationFile tag.

The problem is, that I need to be able to include the xml documentation of
packages that come from nuget. I see this question was asked before, but did not see it 
get addressed.

How would one go around this?

My use case is specifically for swagger / swashbuckle.
We have common projects, which have extensive documentation, we would like to have this included.

Thanks

**Comment by dsplaisted** [comment]
@louislewis2 This is being tracked in #1458.  [This comment](https://github.com/dotnet/sdk/issues/1458#issuecomment-420456386) specifically has links to workarounds you can apply.  Thanks!

**Comment by Vaccano** [comment]
This is still an issue in .Net Core 3.1.

Made a new project.  Added Swashbuckle and turned on the documentation option in properties.

Makes the file fine when I run from Visual Studio.  But my Swagger page errors out when I run what the build server makes.

**How is it not a runtime file when one of my pages fails at runtime because it is missing?**

Please consider adding an option in the options page to make this work with Publish.

**Comment by OliverRC** [comment]
Why is this closed?

I don't get why we have to add extra Targets and hack around something that should be natively supported or at least be a configurable option. 

XML Comments are no longer a development artifact with the rise of Swagger for example.
To produced self documenting swagger documentation at runtime all the XML comments must be included in the application.

What is the rationale for not copying XML documentation?
The documentation is already included in the nuget package on a build or publish?

**Comment by dsplaisted** [comment]
@OliverRC This issue is closed because we are using another issue to track it: #1458

**Comment by mtreske** [comment]
this worked for me with swagger in NetCore 3.1
` 
<PropertyGroup>
    
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishDocumentationFile>true</PublishDocumentationFile>
    <DocumentationFile>$(MSBuildThisFileDirectory)\bin\$(Configuration)\$(TargetFramework)\AnyFile.xml</DocumentationFile>
   
  </PropertyGroup>
`

**Comment by hamidpp** [comment]
you can change the existing condition:

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU' OR '$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>ProjectName.xml</DocumentationFile>
  </PropertyGroup>
```
