### ISSUE TITLE
Publishing self-contained app fails if it has a project reference

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#796]
**Repro**
```xml
<!-- App.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win7-x64;osx.10.10-x64</RuntimeIdentifiers>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lib\Lib.csproj" />
  </ItemGroup>
</Project>
```
```xml
<!-- Lib.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
  </PropertyGroup>
</Project>
```

dotnet restore App.csproj
dotnet publish App.csproj -r win7-x64

**Expected**
Publishes App.csproj for win7-x64 as a self-contained app.

**Actual**

Lib.csproj fails to compile.

<details>

![image](https://cloud.githubusercontent.com/assets/2696087/22571814/4a2ea5a0-e956-11e6-9d42-e1cabca5e813.png)

</details>

**Notes**

Repros in dotnet-CLI 1.0.0-rc3-004350 (public RC) and 1.0.0-rc4-004755 (nightlies)

**Comment by natemcmaster** [comment]
cc @Eilon can you add to your tracking list? We need this for our tests to pass on MusicStore, Entropy, IISIntegration, and ServerTests.

**Comment by dsplaisted** [comment]
I believe that this is the same as #696

**Comment by natemcmaster** [comment]
Yup, same issue. Closing as a dup.
