### ISSUE TITLE
We should not infer ".NETFramework, Version=v0.0" when we encounter a unrecognized Target Framework

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#798]
1. Project:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>foobar</TargetFramework>
  </PropertyGroup>

</Project>
```

2. Build:

```
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	ConsoleApp160	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111	
Error	MSB3645	.NET Framework v3.5 Service Pack 1 was not found. In order to target ".NETFramework,Version=v0.0", .NET Framework v3.5 Service Pack 1 or later must be installed.	ConsoleApp160	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111	
```

**Comment by davkean** [comment]
Looks like I should be getting:

```
Error		Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='foobar'. They must be specified explicitly.
```

But we're not.

**Comment by nguerrera** [comment]
I get the cannot infer error and the others.

```
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Impossible de déduire TargetFrameworkIdentifier et/ou TargetFrameworkVersion à partir de TargetFramework='foo'. Ils doivent être spécifiés explicitement.	ConsoleApp128	C:\Program Files (x86)\Microsoft Visual 
Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	84	
Erreur	MSB3644	Les assemblys de référence pour le Framework ".NETFramework,Version=v0.0" sont introuvables. Pour résoudre ce problème, installez le SDK ou le Targeting Pack pour cette version de Framework, ou reciblez votre application vers une version du Framework pour laquelle le SDK ou le Targeting Pack est installé. Les assemblys seront résolus à partir du Global Assembly Cache (GAC) et seront utilisés à la place des assemblys de référence. C'est pourquoi votre assembly peut ne pas cibler correctement le Framework souhaité.	ConsoleApp128	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111	
Erreur		Le fichier de composant 'c:\users\nicholg\documents\visual studio 2017\Projects\ConsoleApp128\ConsoleApp128\obj\project.assets.json' n'a pas de cible pour '.NETFramework,Version=v0.0'. Vérifiez que vous avez restauré ce projet pour TargetFramework='net' et RuntimeIdentifier=''.	ConsoleApp128	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	113	

```

**Comment by nguerrera** [comment]
The first one above is cannot infer in French

**Comment by nguerrera** [comment]
I think before my crash fix, we would have found the .NET 4 reference assemblies so you would only have gotten the cannot infer error.

**Comment by nguerrera** [comment]
@davkean Are you sure you're not also getting the cannot infer error?

**Comment by nguerrera** [comment]
I just saw an issue on @jinujoseph's machine where not all errors in output window showed up in error list. I suspect that's why you didn't see the cannot infer error. I do see it in the error list.

**Comment by jinujoseph** [comment]
output says this 

```
1>------ Build started: Project: WebApplication1, Configuration: Debug Any CPU ------
1>WebApplication1 -> C:\Users\jinuj\documents\visual studio 2017\Projects\WebApplication1\WebApplication1\bin\Debug\netcoreapp1.1\WebApplication1.dll
2>------ Build started: Project: UnitTestProject2, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(69,5): error : Project 'C:\Users\jinuj\documents\visual studio 2017\Projects\WebApplication1\WebApplication1\WebApplication1.csproj' targets '.NETCoreApp,Version=v1.1'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v1.0'.
2>Done building project "WebApplication1.csproj" -- FAILED.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(76,5): error : Cannot find project info for 'C:\Users\jinuj\documents\visual studio 2017\Projects\WebApplication1\WebApplication1\WebApplication1.csproj'. This can indicate a missing project reference.
2>Done building project "UnitTestProject2.csproj" -- FAILED.
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

ErrorList shows doesn't show not compatibility error 

![image](https://cloud.githubusercontent.com/assets/12449387/22607304/2b1e8caa-ea0c-11e6-9c31-85610e5cf36f.png)

**Comment by dsplaisted** [comment]
Looking into this, I think we currently have two issues:

### Design-time builds

The design-time build doesn't run the `_CheckForInvalidConfigurationAndPlatform` target, and hence doesn't run our SDK `_CheckForUnsupportedTargetFramework` target which generates the error we want to see.  Adding `_CheckCompileDesignTimePrerequisite` to the `BeforeTargets` of the SDK `_CheckForUnsupportedTargetFramework` fixes the VS experience.

@davkean How should we make sure this type of target runs in the design time build?  Would it make sense for `CompileDesignTime` to depend on `_CheckForInvalidConfigurationAndPlatform`, or are the rest of the checks that target does not applicable to design-time builds

### Command-line build

For command-line builds, the issue is that the `_CheckForUnsupportedTargetFramework` target is generating an error, but the build keeps on building the `GetReferenceAssemblyPaths` and `GenerateBuildRuntimeConfigurationFiles` targets.  I'm not sure why it's continuing to run other targets once it hits an error, and I also haven't been able to create a minimal repro of this behavior yet.

@rainersigwald @AndyGerlicher @cdmihai Any idea what could be going on here?

**Comment by davkean** [comment]
_CheckForInvalidConfigurationAndPlatform is an initial target right? Wonder if we run initial targets during design-time builds - we probably should.

**Comment by dsplaisted** [comment]
It's not an initial target. If it were, I doubt you could avoid running it.

**Comment by davkean** [comment]
Oh, it used to be a initial target: http://index/?leftProject=MSBuild%20files&leftSymbol=v6cziojswy7j&rightProject=CBA(Repo)&file=src%5Ctools%5Cx86%5Cmanaged%5Cv4.5%5Cmicrosoft.common.currentversion.targets&line=17.

**Comment by rainersigwald** [comment]
It's no longer an InitialTarget because that caused problems with Restore: https://github.com/Microsoft/msbuild/pull/1280.

Nothing springs to mind for the command-line situation--is there a non-minimal repro @dsplaisted?

**Comment by dsplaisted** [comment]
@rainersigwald OK, I've narrowed down a repro (or rather two of them).

When I try to build a .NET SDK project with an invalid `TargetFramework`, I get three errors where would like to get only one (the first):

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(84,5): error : Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='foobar'. They must be specified explicitly. [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp30\ConsoleApp30\ConsoleApp30.csproj]

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp30\ConsoleApp30\ConsoleApp30.csproj]

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(129,5): error : Assets file 'C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp30\ConsoleApp30\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ConsoleApp30\ConsoleApp30\ConsoleApp30.csproj]

For the reference assembly error, here's the minimal repro:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
  
  <Target Name="_CheckForUnsupportedTargetFramework"
      BeforeTargets="_CheckForInvalidConfigurationAndPlatform;_CheckCompileDesignTimePrerequisite;GetFrameworkPaths;GetReferenceAssemblyPaths;GenerateBuildRuntimeConfigurationFiles">
    <Error Text="Error in _CheckForUnsupportedTargetFramework" />
  </Target>

  <Target Name="_CheckForInvalidConfigurationAndPlatform" BeforeTargets="$(BuildDependsOn);Build" />
  
  <PropertyGroup>
    <BuildDependsOn>
      EntityDeploy;
      CoreBuild;
    </BuildDependsOn>
  </PropertyGroup>
  
  <Target Name="Build" DependsOnTargets="$(BuildDependsOn)" Returns="$(TargetPath)" />

  <Target Name="CoreBuild" DependsOnTargets="PrepareForBuild;GenerateBuildRuntimeConfigurationFiles"/>

  <Target Name="PrepareForBuild" DependsOnTargets="GetReferenceAssemblyPaths"/>
  
  <Target Name="GetReferenceAssemblyPaths">
    <Error Text="GetReferenceAssemblyPaths Error" />
  </Target>

  <Target Name="EntityDeploy" Condition="'@(EntityDeploy)' != ''" />
</Project>
```

In this repro, I would hope that the error in `_CheckForUnsupportedTargetFramework` would prevent subsequent targets from being run.  Something about the `EntityDeploy` target being added to the start of `BuildDependsOn`, and possibly the fact that `BuildDependsOn` is being used both in `Build` as `DependsOnTargets` and in `_CheckForInvalidConfigurationAndPlatform` as `BeforeTargets` is causing `GetReferenceAssemblyPaths` to run even after a previous target has failed.

Here's the minimal repro for the assets file not error:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
  
  <Target Name="_CheckForUnsupportedTargetFramework"
      BeforeTargets="_CheckForInvalidConfigurationAndPlatform;_CheckCompileDesignTimePrerequisite;GetFrameworkPaths;GetReferenceAssemblyPaths;GenerateBuildRuntimeConfigurationFiles">
    <Error Text="Error in _CheckForUnsupportedTargetFramework" />
  </Target>

  <Target Name="_CheckForInvalidConfigurationAndPlatform" BeforeTargets="$(BuildDependsOn);Build" />
  
  <PropertyGroup>
    <BuildDependsOn>
      CoreBuild;
    </BuildDependsOn>
  </PropertyGroup>
  
  <Target Name="Build" DependsOnTargets="$(BuildDependsOn)" Returns="$(TargetPath)" />

  <Target Name="CoreBuild" DependsOnTargets="PrepareForBuild;GenerateBuildRuntimeConfigurationFiles">
    <OnError ExecuteTargets="_CleanRecordFileWrites" />
  </Target>

  <Target Name="PrepareForBuild" DependsOnTargets="GetReferenceAssemblyPaths"/>
  
  <Target Name="GetReferenceAssemblyPaths">
    <Error Text="GetReferenceAssemblyPaths Error" />
  </Target>

  <Target Name="_CheckForCompileOutputs"/>
  <Target Name="_CleanGetCurrentAndPriorFileWrites" DependsOnTargets="_CheckForCompileOutputs" />
  <Target Name="_CleanRecordFileWrites" DependsOnTargets="_CleanGetCurrentAndPriorFileWrites"/>

  <Target Name="GenerateBuildRuntimeConfigurationFiles" BeforeTargets="_CheckForCompileOutputs">
    <Error Text="GenerateBuildRuntimeConfigurationFiles Error" />
  </Target>
  
</Project>
```

This is more straightforward, it looks like the `OnError` task in `CoreBuild` is causing `_CleanRecordFileWrites` and its dependencies to run after an error is encountered.  I'm not sure exactly how to fix this yet though.

**Comment by davkean** [comment]
I think we should check that the removal of `_CheckForInvalidConfigurationAndPlatform` from initial targets doesn't break the legacy project system, this is such a massive change - and it is it even relevant anymore?

**Comment by dsplaisted** [comment]
#1274, together with https://github.com/Microsoft/msbuild/pull/2133, should fix this

**Comment by livarcocc** [comment]
This is working now:
```
sdk/2.0.0-preview2-006449/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(87,5): error : The TargetFramework value 'foobar' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
```
