### ISSUE TITLE
In SDK build, set BaseIntermediateOutputPath before it is used for MSBuildProjectExtensionsPath

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#802]
We're overriding BaseIntermediateOutputPath in our Common.props file, but this is after it's used to calculate the MSBuildProjectExtensionsPath, which means we aren't getting any of the NuGet generated props or targets files (and hence the props or targets from packages) as part of our build.

To fix this, we can use Directory.Import.targets, which will get imported before the MSBuildProjectExtensionsPath is evaluated.  We can put a Directory.Import.targets in the src/ and test/ folders which imports our Common.props, and then remove the explicit Common.props import from all of our projects.

**Comment by rainersigwald** [comment]
Directory.**Build**.targets

**Comment by nguerrera** [comment]
Directory.Build.props?

**Comment by rainersigwald** [comment]
😞 yes.

**Comment by piotrpMSFT** [comment]
Note, this issue will block the sdk repo from moving to `dotnet test` and thereby from all of us being able to use VS to run tests... should we try to load-balance the work?

**Comment by nguerrera** [comment]
Whoever fixes tests in VS will be my hero. Feel free to grab this. I think we can say it's an infrastructure only change and dogfooding aid get permission to merge without ship room.

**Comment by piotrpMSFT** [comment]
@jonsequitur thought he could pursue this for us. Let's see if he can!

**Comment by nguerrera** [comment]
This is done.
