### ISSUE TITLE
Building a project from VS without a source file leads to Build never completing

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#807]
Attached repro project - try opening in VS -> Restore -> Build.

Build never completes.

CC: @dsplaisted @srivatsn 
[1602-test.zip](https://github.com/dotnet/sdk/files/751395/1602-test.zip)

**Comment by srivatsn** [comment]
I'm not able to repro this with the latest builds.

**Comment by srivatsn** [comment]
Tried on today's build as well. Closing this out. Rohit, please reopen if you can see this on latest builds.

**Comment by rohit21agrawal** [comment]
doesn't repro.
