### ISSUE TITLE
Ensure same version for multi-targeting scenarios from innerbuilds

### ISSUE THREAD

**Issue by rrelyea** [dotnet/sdk#814]
Per phone discussion and these scenarios..
https://github.com/NuGet/Home/issues/4487
https://github.com/NuGet/Home/issues/4496

**Comment by srivatsn** [comment]
@nguerrera can you take a look at putting in the hack you mention in https://github.com/NuGet/Home/issues/4496?

**Comment by nguerrera** [comment]
Yep

**Comment by nguerrera** [comment]
PR is out: #819
