### ISSUE TITLE
Using CoreClr specific types in new SDK

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#816]
Looking to do some experiments with `AssemblyLoadContext`.  This is a type specific to CoreClr and I'm having trouble accessing it using the new SDK format.  

I have a standard project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

I've manually verified that a NuGet reference to System.Runtime.Loader exists in Solution Explorer.  Yet references to System.Runtime.Loader do not resolve when compiling my code.

``` txt
1>Program.cs(2,22,2,28): error CS0234: The type or namespace name 'Loader' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
```

Feel like I'm missing something basic here.

**Comment by nguerrera** [comment]
The nuspec for Microsoft.NETCore.App has exclude="Compile" for the System.Runtime.Loader, which prevents the reference being seen by users of Microsoft.NETCore.App. So this would be expected based on how the package is defined. I don't know why it is defined that way. @ericstj?

You can add a direct package reference to System.Runtime.Loader to get the ref and use the API.

It's unfortunate that there is no indication in the solution explorer of the dependencies tree for this case. cc @abpiskunov @natidea @srivatsn

**Comment by jaredpar** [comment]
@nguerrera that does seem to be the issue.  Once I added an explicit reference everything lit up as expected.

I do want to second your notion that there is no obvious way for a developer to understand that is the case.  I spent a bit of time digging through solution explorer and the lock file to try and understand the problem here.  Nothing obvious popped out.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/corefx#17325

**Comment by livarcocc** [comment]
Moved this to corefx for now, though I am not sure if/how applicable this may be for 2.0.
