### ISSUE TITLE
Suggestion: Add custom MSBuild targets to the command resolver, i.e. `dotnet mytarget`

### ISSUE THREAD

**Issue by g0t4** [dotnet/sdk#8185]
**TLDR**: `dotnet mytarget` could trigger `dotnet msbuild /t:mytarget`

Let's say I have a custom target in my project file: `<Target Name="mytarget" ...`

To execute this I can run `dotnet msbuild /t:mytarget` which is rather verbose. 

Now that MSBuild is an integral part of the `dotnet` CLI, why not have a command resolver that checks for custom targets? We could add this to the end of the current list of resolvers so as not to break existing resolution strategies.

This would make it possible to type `dotnet mytarget` instead of `dotnet msbuild /t:mytarget` and any arguments I pass could be forwarded to msbuild just like `dotnet build` does. 

This would simplify tool development to just needing a NuGet package with MSBuild targets and getting `dotnet mytarget` for free. We'd no longer need a console app that wraps the call to `dotnet msbuild.` This is a pattern discussed in the extensibility docs: 

> However, if you want to provide a better user experience, you can combine per-project tools and custom targets. In this scenario, the per-project tool would essentially just accept whatever needed parameters and would translate that into the required dotnet msbuild invocation that would execute the target. You can see a sample of this kind of synergy on the MVP Summit 2016 Hackathon samples repo in the dotnet-packer project.
> -- https://github.com/dotnet/docs/commit/049bc39d50f149b5ffb173f157ff6ff47182477b#diff-f3b0783a35a3fc75fe4e57558a221194R154

This could be opt-in/out perhaps by setting an attribute on the custom target(s). Especially if at some point there will be a command to list custom tools. i.e.: `<Target Name="MyTool" ExtendDotNetCli="true" />`

Perhaps also alias the sub command while we're at it: `<Target Name=MyTool" ExtendDotNetCliAlias="mytoolalias" />` which would map the target to `dotnet mytoolalias` instead of `dotnet mytool`.

**Comment by stan-sz** [comment]
See related https://github.com/NuGet/Home/issues/4781

**Comment by jzabroski** [comment]
Propose close. I think the right suggestion here is that, when dotnet.exe cannot find a task `mytarget` to run, it suggests to the user they may have meant `dotnet.exe msbuild t:mytarget` instead, in addition to the existing error message.

**Comment by baronfel** [comment]
We're definitely not going to do this for the reasons that @jzabroski mentions and more.  The CLI is an opinionated layer that hides/is on top of MSBuild. The recent CLI usability survey we did this summer made it _overwhelmingly clear_ that users want the CLI to insulate them from MSBuild semantics.

**Comment by g0t4** [comment]
Good enough to just warn, if that is feasible to do.
