### ISSUE TITLE
Don't say "this can indicate a missing project reference" for unresolved project reference

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#829]
https://github.com/dotnet/roslyn-project-system/issues/1470#issuecomment-277900822

**Comment by piotrpMSFT** [comment]
The 'long file path' assertion in `TestAssetsManager` could use a similar treatment.

**Comment by livarcocc** [comment]
@nguerrera Take a look and see if this has been fixed already. Otherwise, just move it back.

**Comment by nguerrera** [comment]
This no longer repros with the work that was done in 2.0 to prevent continuing on errors. It is fixed.
