### ISSUE TITLE
Make dot net cache and dot net publish --filter accept multiple files as input

### ISSUE THREAD

**Issue by ramarag** [dotnet/sdk#830]
cc @gkhanna79

**Comment by piotrpMSFT** [comment]
Should we be translating the intent into MSBuild terms for the SDK tracking issue? CLI is not involved for most SDK usages [VS, VS for Mac, MSBuild.exe, etc...]

**Comment by gkhanna79** [comment]
Did you mean "dotnet publish" in the title @ramarag ? Also, are you referring to accepting multiple json files or individual packages?
