### ISSUE TITLE
Improve default RID selection for .NETFramework exes

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#840]
We currently pick win7-x86 or win7-x64 (depending on PlatformTarget) when building on Windows. We should make this more dynamic based on host OS, particularly when we support building net4x applications for non-Windows using Mono. 

There are too many uses of $(RuntimeIdentifier) and $(RuntimeIdentifers) in static evaluation context for us to simply run some code to pick a RID. 

Possible fixes:
1. msbuild sets the host rid
2. nuget uses/returns host rid as part of restore data
3. things are refactored such that the rid is not needed statically

**Comment by dsplaisted** [comment]
@livarcocc This shouldn't be directly related to making reference assemblies available as NuGet packages.  You can move it out.

**Comment by nguerrera** [comment]
I don't think we should do this. I think we can leave .NET Framework alone. The RID inference is complicated enough there.
