### ISSUE TITLE
Consider generating .NETCoreApp,Version=v1.0.AssemblyAttributes.cs into *.AssemblyInfo.cs

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#842]
Currently for the simplest C# project two temp files are generated:
```
"C:\Users\kirillo\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs"
obj\Debug\netcoreapp1.0\NETCoreConsoleApp1.AssemblyInfo.cs
```
The former contains the `TargetFrameworkAttribute(".NETCoreApp,Version=v1.0",...` and the latter contains `AssemblyVersion`, `AssemblyTitle`, etc.

The problem with generating into Temp is that it often breaks incrementality when other projects touch that file your project sees that and wants to rebuild even if nothing else about your project changed. Additionally, the Temp directory is volatile in Remote Desktop scenarios and it may change from \Temp\1\ to \Temp\2 etc. All of these impact build incrementality.

Consider either generating the first file into the obj directory, or maybe even merge both files to only write a single file to disk? At a minimum, generating into Temp feels bad (should go to obj instead).

**Comment by nguerrera** [comment]
@KirillOsenkov I think that to get the maximum benefit for all project types, the code in msbuild common targets that's generating this to TEMP should be changed to put in in obj.

**Comment by livarcocc** [comment]
Closing this in favor of https://github.com/Microsoft/msbuild/issues/2188.
