### ISSUE TITLE
Preserve OutputPath for single-framework

### ISSUE THREAD

**Issue by iskiselev** [dotnet/sdk#844]
I need to redirect project output to some predefined folder. Even if my project specify only on target framework (e.g. `<TargetFramework>net45</TargetFramework>`), my project output goes into $(OutputPath)\$(TargetFramework), instead just $(OutputPath). I'm not sure how should it work with multiple frameworks.

It is also incorrectly works in Visual Studio project properties - Build\Output path shows $(OutputPath)\$(TargetFramework), but write value back into $(OutputPath), so framework name will be added again.

**Comment by nguerrera** [comment]
You can now set `<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>` to make this work as you want.

**Comment by robinrodricks** [comment]
Just adding this comment to help others who might wanna do this.

I can confirm this IS supported in .NET 7 onwards, using this `csproj` declaration:

```xml
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>C:\Target\Folder\</OutputPath>
  </PropertyGroup>`
```

This will cause your project binaries to be outputted directly into `C:\Target\Folder\` without the `net7.0` or `Release` subfolders.

Hope it helps!
