### ISSUE TITLE
[Templates] Class library template is generating netcoreapp project instead of netstandard

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/sdk#853]
After the latest updates to RC4, on both Visual Studio and dotnet CLI tooling, if you create a new class library project, it will create a new console app instead:

## To reproduce

- File > New > .Net Core > Class Library; or 
- `dotnet new`

In both cases the project created is targeting `netcoreapp1.0` instead of `netstandard1.4` as usual.

It is probably a bug into the templates.

```
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004597)

Product Information:
 Version:            1.0.0-rc4-004597
 Commit SHA-1 hash:  0a62481cc0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004597
``` 

Note that it happen on OSX and Windows on Visual Studio as well. The same release are installed in both.

**Comment by srivatsn** [comment]
You are creating a .NET Core class library - hence it's targeting netcoreapp1.0. If you create File->New->.NET Standard->Class Library then it will target netstandard. .NET Core is a platform like desktop and this class library is for usages specific to that platform. .NET Standard is mean to the be for libraries that need to be shared across platforms.
