### ISSUE TITLE
package not compatible with net46

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/sdk#856]
dotnet --version
1.0.0-rc4-004771
Visual Studio 2017 this weeks release

Based on document here: https://github.com/dotnet/standard/blob/master/docs/versions.md I beleive that my projects should build.
My library project builds fine and nuget package is created.
When I attempt to add package to my test project I receive this error:
Package MyPackage 1.7.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package MyPackage 1.7.0 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)
Would you guys take a quick look and tell me what I'm doing wrong?  

Library project:

	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		<TargetFrameworks>net46;netstandard1.6</TargetFrameworks>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>

	  </PropertyGroup>
	  <ItemGroup>
		<PackageReference Include="Autofac" Version="4.2.1" />
		<PackageReference Include="NETStandard.Library" Version="1.6.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="1.1.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.3.0" />
		<PackageReference Include="System.Net.NetworkInformation" Version="4.3.0" />
		<PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
		<PackageReference Include="System.ServiceModel" Version="1.0.0" />
		<PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
		<PackageReference Include="System.ServiceModel.Primitives" Version="4.3.0" />
		<PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
	  </ItemGroup>
	</Project>

Application (unit tests)

	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		<TargetFrameworks>net46;netcoreapp1.1</TargetFrameworks>
	  </PropertyGroup>
	  <ItemGroup>
		
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
		<PackageReference Include="MSTest.TestAdapter" Version="1.1.10-rc2" />
		<PackageReference Include="MSTest.TestFramework" Version="1.0.8-rc2" />
		<PackageReference Include="NETStandard.Library" Version="1.6.1" />
		<PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
		
		<PackageReference Include="Moq" Version="4.6.38-alpha" />
		<PackageReference Include="Autofac" Version="4.2.1" />
		
	  </ItemGroup>
	  <ItemGroup>
		<Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
	  </ItemGroup>
	</Project>

**Comment by srivatsn** [comment]
@nguerrera does netstandard1.6 support netcoreapp1.1? Does the compat check return false here?

**Comment by leaderanalytics** [comment]
@srivatsn  I rely on the official doc here:
https://github.com/dotnet/standard/blob/master/docs/versions.md
What does it say that relates to my question?

**Comment by srivatsn** [comment]
That doesn't say anything about netcoreapp1.1.  Hence my question to @nguerrera. @terrajobst should that doc be updated to reflect 1.1?

**Comment by nguerrera** [comment]
Anything compatible with netcoreapp1.0 should be compatible with netcoreapp1.1.

The error is coming from nuget and claiming the package only supports netcoreapp1.1, which is indeed not compatible with net46.

@leaderanalytics are you saying that the library csproj listed produced the nupkg that cannot install to the test project? The error suggests that the package restore found is quite different. Is it possible there's a competing nupkg in your package sources?

**Comment by nguerrera** [comment]
If it's another package that targets netcoreapp only, then you need to condition the package reference on a compatible TFM:

``` xml
<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.1'">
  <PackageReference Include="ThingThatWorksOnNetCoreAppOnly" Version="1.0.0" />
</ItemGroup>
```

**Comment by nguerrera** [comment]
Without the condition, the package ref would apply to both the net46 build and the netcoreapp1.1 build.

**Comment by sam-wheat** [comment]
@nguerrera  thank you - please respond to @srivatsn:

That doesn't say anything about netcoreapp1.1. Hence my question to @nguerrera. @terrajobst should that doc be updated to reflect 1.1?

**Comment by nguerrera** [comment]
Yes, the doc should be updated, @terrajobst can you drive that. 

Still as I've said above:

Anything compatible with netcoreapp1.0 is compatible with 1.1 and therefore netstandard1.6 is compatible with netcoreapp1.1

The error message is unrelated to that question. It is saying there's a package ref to a package that targets only netcoreapp1.1 from a project that targets net46, which is correct.

**Comment by nguerrera** [comment]
@sam-wheat I am still looking for the answer to this:
> are you saying that the library csproj listed produced the nupkg that cannot install to the test project? The error suggests that the package restore found is quite different. Is it possible there's a competing nupkg in your package sources?

Or is MyPackage something else, which targets only netcoreapp1.1. If so, then you need to condition the references to MyPackage in the project that targets net46 and netcoreapp1.1 as I showed above.

**Comment by leaderanalytics** [comment]
>are you saying that the library csproj listed produced the nupkg that cannot install to the test project? 
Yes.

>Or is MyPackage something else, which targets only netcoreapp1.1?
No - the csproj for for the library and app are shown.

These two statements appear to conflict:

"Anything compatible with netcoreapp1.0 is compatible with 1.1 and therefore netstandard1.6 is compatible with netcoreapp1.1"

"The error is coming from nuget and claiming the package only supports netcoreapp1.1, which is indeed not compatible with net46."

Per link referenced in my question, net46 is compatible with netstandard1.6 and should therefore be usable by my app, correct?

**Comment by nguerrera** [comment]
There are two separate compatibility concerns in the error message and discussion:

* netstandard1.6 **is** compatible with netcoreapp1.1
* netcoreapp1.1 *is not** compatible with net46

Error message is saying the second thing, which has nothing to do with the first.

The library project that supports net46 and netstandard1.6 should indeed work with the app that targets net46 and netcoreapp1.1. And if you pack the library, you should be able to PackageReference it from the app.

However, the error is indicating that the package is targeting only netcoreapp1.1, which does not match the csproj listing. One of the following must be true:

1. `MyPackage` is something different than library csproj
2.  An earlier build of MyPackage.nupkg is being used and when that one was packed, it only targeted netcoreapp1.1
3. Pack of library csproj produced an incorrect package from library csproj
4. nuget restore is misinterpreting the packed output of library csproj

If you could give me more detailed repro steps of how you go from csproj -> package -> package reference, I can dig in to which it is.

**Comment by nguerrera** [comment]
Scratch 1, I see you answered the questions eliminating that.

**Comment by leaderanalytics** [comment]
@nguerrera based on your responses I uninstalled and reinstalled Visual Studio and it works.
I also think (but am not 100% sure) that this package was a problem:
     
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />


I don't think 2.) was the case because I targeted net46 since day 1.  
Big thanks for your help @srivatsn  also.  

I look forward to seeing netcoreapp on the compatibility matrix. The fact that it is such an important component of dotnet and it is missing from the matrix is itself confusing to those of us who receive info on a trickle-down basis.  Please do not close this ticket until the matrix is updated.  Thanks!

**Comment by dsplaisted** [comment]
@leaderanalytics .NET Core is on the compatibility matrix.  A `netcoreapp` target framework means .NET Core.  .NET Core 1.1 isn't listed because they both support the same versions of .NET Standard.

Does that help?  What would you like to see clarified in the matrix?

**Comment by leaderanalytics** [comment]
Thank you Daniel, here is why I dont understand:

"A  netcoreapp  target framework means .NET Core."

Why then are there two monikers? What is the differece between this:

         <TargetFrameworks>netcoreapp1.1</TargetFrameworks>

and this:
        
		<TargetFrameworks>netstandard1.6</TargetFrameworks>

		
Using David Fowlers interface analogy I dont understand why using netstandard as a TargetFramework makes sense.  It seems like doing this:

        var x = new IEnumerable();    // not gonna happen
		
		
Also, from [this post on stackoverflow](http://stackoverflow.com/questions/38165411/why-doesnt-microsoft-netcore-app-support-netstandard1-6):
"If you are building a library (to be consumed by another library or application), you'll target netstandard1.X"
"If you are building an application (console, UWP, ASP.NET Core web app), you'll target netcoreapp1.0"

However when I create new .net core class library project in Visual Studio 2017 I see this:

      <TargetFramework>netcoreapp1.0</TargetFramework>
	  
Why does a class library target netcoreapp?

**Comment by dsplaisted** [comment]
A library can target .NET Standard in order to support multiple .NET platforms (such as .NET Framework, .NET Core, Xamarin, UWP).  But a library may also be platform-specific, so just like you might have a class library for .NET Framework or for Xamarin.Android, you can have a class library for .NET Core.  Currently, there are not many APIs in .NET Core that are not in .NET Standard, so there's generally not yet much of a reason to create a library targeting .NET Core.

> However when I create new .net core class library project in Visual Studio 2017 I see this:

There's a .NET Core class library project template under the .NET Core node in the new project dialog.  There's a .NET Standard class library template under the .NET Standard node:

![image](https://cloud.githubusercontent.com/assets/145043/23003171/ba81f9c2-f3a3-11e6-8698-72128ca316ef.png)

More links for .NET Standard

- [.NET Standard repo](https://github.com/dotnet/standard)
- [.NET Standard FAQ](https://github.com/dotnet/standard/blob/master/docs/faq.md)
- [.NET Standard blog post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/)

**Comment by livarcocc** [comment]
This issue seems resolved to me. If there is anything else here that needs to be addressed. Please, re-activate.

**Comment by saineshwar** [comment]
I resolved issue by adding Class library of Windows Classic Desktop but my application only target windows only.
