### ISSUE TITLE
Build Error on Macos Sierra

### ISSUE THREAD

**Issue by twurm** [dotnet/sdk#858]
We have a project that was created on a Windows machine and builds and runs fine when, we move it to one of our Mac's the build fails with the following error.

/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for '/Users/twurm/Documents/Projects/dotNet/ParentSolution/ProjectA/ProjectA.csproj'. This can indicate a missing project reference.  

This is because the project isn't in the root folder of ParentSolution it's in /Users/twurm/Documents/Projects/dotNet/ParentSolution/**src**/ folder.

dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771

# To Reproduce 
Create a project with the following structure (if required I can provide one, you I just didn't have access to a Windows machine at the moment and VS for Mac doesn't allow a structure like this):

- ParentSoution
&nbsp;&nbsp;&nbsp;src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ProjectA
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ProjectB
&nbsp;&nbsp;&nbsp;tests
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ProjectA.Tests
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ProjectB.Tests

Then have ProjectB Reference ProjectB when you run a build you should see the error above.

**Comment by piotrpMSFT** [comment]
@twurm a repro would be useful. Project should have `<ProjectReference` elements that will find referenced projects even in this sort of layout. You should be able to set this up using the CLI from the command line on a mac:

- cd src/ProjectA
- dotnet add reference ../ProjectB/ProjectB.csproj
- cd ../../test/ProjectA.Tests
- dotnet add reference ../../src/ProjectA/ProjectA.csproj

Of course, I'm guessing at the references you actually want, but this should be a decent start.

I'm also curious what TFM you are using. Sierra didn't get support until `netcoreapp1.1`.

**Comment by twurm** [comment]
@piotrpMSFT take a look at the attached example project.  Its a quick and dirty example.  It compiles fine on Windows, on the Mac is throws the following:
/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(5,5): Error: Cannot find project info for '/Users/wurmthoj/Documents/Projects/dotNet/CliBug/ProjectA/ProjectA.csproj'. This can indicate a missing project reference. (ProjectB)
[CliBug.zip](https://github.com/dotnet/sdk/files/770016/CliBug.zip)

**Comment by piotrpMSFT** [comment]
What tools are you using on Mac? I just downloaded the repro and was able to restore & build on the cmd line with no issues. Are you using CLI? if so, `dotnet --info`?

**Comment by twurm** [comment]
I tried it with Visual Studio for Mac Preview 3 as well as the command line tools.  Below is the command line results:

Thomass-MBP:CliBug wurmthoj$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771
Thomass-MBP:CliBug twurm$ dotnet build
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

  ProjectA -> /Users/twurm/Documents/Projects/dotNet/CliBug/src/ProjectA/bin/Debug/netcoreapp1.1/ProjectA.dll
/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for '/Users/twurm/Documents/Projects/dotNet/CliBug/ProjectA/ProjectA.csproj'. This can indicate a missing project reference. [/Users/twurm/Documents/Projects/dotNet/CliBug/src/ProjectB/ProjectB.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for '/Users/twurm/Documents/Projects/dotNet/CliBug/ProjectA/ProjectA.csproj'. This can indicate a missing project reference. [/Users/twurm/Documents/Projects/dotNet/CliBug/src/ProjectB/ProjectB.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.73

**Comment by piotrpMSFT** [comment]
with cmd line, did you `dotnet restore` before building?

**Comment by twurm** [comment]
Interestingly enough, a dotnet clean then dotnet restore seems to work from the command line.  However in VS Preview 3 if I run a restore then a build it fails with the same message any ideas?

**Comment by piotrpMSFT** [comment]
@twurm lots of bugs got fixed between preview3 and today... does it work on latest RC4 bits?

**Comment by Jonathan34** [comment]
i had the same issue and doing a dotnet restore fixed it from the command line or vscode.
however from visual studio preview 3, the build fails.

**Comment by livarcocc** [comment]
I am closing this issue since we have had a report of this reproing on RTM VS 2017. If that's the case, please, re-activate.
