### ISSUE TITLE
Spurious `dotnet pack` warnings

### ISSUE THREAD

**Issue by wjk** [dotnet/sdk#859]
When I run `dotnet pack` on a project on Windows, I get a number of NuGet warnings regarding misplaced assemblies. Apart from one file that was placed inside `contentFiles/win/any` (because it is a native DLL and not a C# assembly), the warnings are all complaining about a path that looks something like this:

```
lib/netcoreapp1.1\Win32UI.Support.dll
```

Notice the mixed slash/backslash in the above path. Inspection of the output nupkg file indicates that the files were added correctly. Changing the path in the csproj to use all backslashes resolves this warning. Seeing as how the actual zip-based nupkg file does not care what kind of slash is used, the validation process should not care either.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4596
