### ISSUE TITLE
dotnet run of hello world takes way too long

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#8697]
Reported by @migueldeicaza

## Steps to reproduce
1. dotnet new console
2. dotnet build
3. dotnet run

## Expected  behavior
`dotnet run` executes fast, nearly the same as calling `dotnet <pathToDll>`

## Actual behavior
`dotnet run` is slow, about 3 seconds on my machine.  It's consistently this slow, even when it doesn't need to rebuild.

It appears that run is calling msbuild twice before actually running the app:
![image](https://user-images.githubusercontent.com/8918108/30175472-7c9a1c10-93b3-11e7-8a41-d983671ad25f.png)

Can't we have a fast-path here that bypasses MSBuild?  It seems like we've optimized for incremental build via the run command which I'm not sure is really the primary workflow for run (but I may be wrong).

**Comment by SrMordred** [comment]
Just started learning C#, i'm on a low end machine atm, and i´m already here. 
I´m very surprised that `dotnet run` is that slow. Since most of other programming languagues that i work with, that are compile to binary have way faster 'hello world' compilation times. 

One thing that i noticed is that build and run the exe is faster than just the run command, which is odd:
( Not the very first build, runned multiple times make sure its cached ) 

```timecmd dotnet run```
`00:00:03.38`

```timecmd dotnet build && bin\Debug\netcoreapp3.1\cs.exe```
` 00:00:01.44`

I´m very confused.

**Comment by mattgreen** [comment]
Find myself in the same boat here. Used C# with VS back in the 2006 era or so and loved the rapid development experience coupled with the IDE. I suspect VS was background compiling files as I changed them.

Now I find myself enjoying C# + dotnet while using MonoGame, but the dev experience is definitely hindered by the slow compile + launch even on very recent hardware.

**Comment by bailZszsz** [comment]
> Just started learning C#, i'm on a low end machine atm, and i´m already here.
> I´m very surprised that `dotnet run` is that slow. Since most of other programming languagues that i work with, that are compile to binary have way faster 'hello world' compilation times.
> 
I'm in the exact same position as you and had the same thought! Can this issue be resolved, or is it just something we must get used to?

**Comment by kayzweller** [comment]
```
D:\C#Project\_learn\myApp>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

here command test run:
**1st run**
```
PS D:\C#project\_learn\myApp> Measure-Command { dotnet run }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 497
Ticks             : 54977913
TotalDays         : 6,363184375E-05
TotalHours        : 0,00152716425
TotalMinutes      : 0,091629855
TotalSeconds      : 5,4977913
TotalMilliseconds : 5497,7913
```

**2nd run**
```
PS D:\C#project\_learn\myApp> Measure-Command { dotnet run }          
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 635
Ticks             : 36351620
TotalDays         : 4,20736342592593E-05
TotalHours        : 0,00100976722222222
TotalMinutes      : 0,0605860333333333
TotalSeconds      : 3,635162
TotalMilliseconds : 3635,162
```

**3rd run**
```
PS D:\C#project\_learn\myApp> Measure-Command { dotnet run }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 895
Ticks             : 38953122
TotalDays         : 4,50846319444444E-05
TotalHours        : 0,00108203116666667
TotalMinutes      : 0,06492187
TotalSeconds      : 3,8953122
TotalMilliseconds : 3895,3122
```

Code using Java before, I consider this as a slow run.

**Comment by eiva** [comment]
> The two times above are non-comparable. They are not meant to be equivalent.
> 
> `dotnet <path_to_dll>` is the expected way to run FDD apps and does not require the SDK. It does very little.
> 
> Meanwhile, `dotnet run` is a developer tool equivalent to F5 in VS or some other IDE. It does a bunch of things, like restore and build your project and then, it evaluates it to find the necessary commands to run your app and then finally, using this information, kicks off that process.
> 
> While it could, potentially be faster, it will never have the same perf as `dotnet <path_to_dll>` and that is very much expected.

Especially when whole windows start in ~20 seconds, and cold run of winword taking 3 seconds. That 4seconds to start the empty app is... a little bit too much...
Mostly looks like it dumping the whole HDD to the cloud...

**Comment by marcpopMSFT** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
We're investigating CLI performance for the commands frequently used during development as part of .NET 6 and we definitely expect to get improvements to this very common scenario of running a simple app via `dotnet run`. 

As it stands today, using a nightly build of .NET 6.0-preview.3, a `dotnet run` on a "Hello, World!" console app takes about 1.3-1.4 seconds on my machine, after a warm-up run or two. Running the app directly takes ~60ms, so the `dotnet run` overhead is practically the entire time, which is mostly spent in the the execution of the restore and build itself.

Progress on this work can be followed at https://github.com/dotnet/msbuild/issues/5876

**Comment by burnchar** [comment]
Same problem here. I just started using Core after using Framework for years. Imagine a new developer, evaluating which language to use and looking up a "Hello, World!" tutorial for each.

DotNet Core 5.0 is extremely noticeably slow compared than any other language. What does that new developer likely do?

**Comment by RUSshy** [comment]
4 years old issue, that is what happen when people bet on bloat, when people bet on JIT for tooling, and when people are stubborn when confronted with problems

if AOT was a thing 4 years ago, and more when designing dotnet core, at that time GO was starting to become relevant already, cold start would have been eliminated already

**Comment by ericstj** [comment]
Original poster here.  Just sharing my opinion in why I originally opened this.

Dotnet run does a full incremental build and I didn’t expect that. I wanted something faster, if even just a hueristic like “has any build been done” rather than a full incremental.

I expect a full incremental build to take time, and I think the time it takes is reasonable.

I also think the time for a direct run of the output is reasonable.

AOT is great, and did exist before .NETCore did (UWP: .NETNative) but that’s not really going to have an impact here. The bottle neck is not JIT it’s IO for the incremental build.

If folks don’t feel like changing dotnet run to use a lighter weight hueristic is something we want to do then I suggest closing this issue and opening other issues more focused on specific perf issues they are facing.

**Comment by DamianEdwards** [comment]
Worth pointing out there's already `dotnet run --no-build` too as a quick way to just run the last compilation. Perhaps a short alias could be introduced for that if folks feel that scenario is common enough to warrant it, e.g. `dotnet run -nb`

**Comment by DamianEdwards** [comment]
As [stated by @ericstj](https://github.com/dotnet/sdk/issues/8697#issuecomment-858217057) I think this issue is best closed now and specific issues can be opened to track specific perf issues or ask for specific features.
