### ISSUE TITLE
Error with Common targets 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/sdk#872]
Reported through VS Feedback - https://developercommunity.visualstudio.com/content/problem/19220/error-with-common-targets.html

@onovotny says:
With certain targets file, I get an error saying "The expression [Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraryies()...cannot be avaludated. Input string was not in a correct format.
Nothing in my targets should have affected that.
To repro:
clone: https://github.com/onovotny/MSBuildSdkExtras Open in VS 2017. Edit the TestLibrary to set the TargetFramework to netstandard1.0 and hit save. The error occurs.

**Comment by onovotny** [comment]
This can be closed out -- it was an error in my code in generating an invalid `TargetFrameworkVersion` property. That said, a better error message could help.
