### ISSUE TITLE
.net core version of System.Net.Mail is used when targeting .net461

### ISSUE THREAD

**Issue by theimowski** [dotnet/sdk#8797]
## Steps to reproduce

Reproduce repository:
* https://github.com/theimowski/repro-paket-system.net.mail/tree/csharp for C# branch
* https://github.com/theimowski/repro-paket-system.net.mail/tree/fsharp_nopaket for F# branch

(repository contains 'paket' in name cuz I initially though it was related to [paket](https://github.com/fsprojects/Paket/issues/2829), but is not)

Both branches contain single console project created with `dotnet new console` and `dotnet new console --language f#`, then adding a nuget reference to `Suave.Experimental`.

`Suave.Experimental` is a package that in its 2.2.1 nuspec contains: 

```xml
<dependencies>
      ...
      <group targetFramework=".NETStandard1.6">
        ...
        <dependency id="System.Net.Mail" version="1.0.0-rtm-00002" exclude="Build,Analyzers"></dependency>
        ...
      </group>
    </dependencies>
```

So it should include `System.Net.Mail` but for .NETStandard1.6 target framework.
Note that both F# and C# project in repro repo target .net461

Repro steps:

1. `dotnet restore`
2. `dotnet build`
3. `dotnet run`

## Expected  behavior

Both branches should print:

```
System.Net.Mail.MailAddress, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

## Actual behavior

* F# branch prints:

```
System.Net.Mail.MailAddress, System.Net.Mail, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

* C# branch fails in 2nd step (`dotnet build`) with:

```
Program.cs(9,54): error CS0433: The type 'MailAddress' exists in both 'System.Net.Mail, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by dsplaisted** [comment]
It looks like this is a bug in the unofficial (and old) [System.Net.Mail package](https://www.nuget.org/packages/System.Net.Mail/1.0.0-rtm-00002).  The .NET Framework version of it should have type-forwarded to `System.dll` instead of having an actual implementation.

It looks like newer versions of the Suave packages don't depend on this and don't have this problem.
