### ISSUE TITLE
SDK PR Validation CI and Signed Build CI should use same OS's

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/sdk#885]
Now that we have RID-specific tests it's important to have RID consistency across both sets of CI's. Otherwise, PR's which are green on the front-end CI may still cause build failures on the back-end CI. This affected #696

**Comment by dsplaisted** [comment]
Is this still an issue?  Do front-end and back-end refer to Jenkins and VSO, or to the SDK and CLI repo, or what?
