### ISSUE TITLE
Support for read only source trees

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#887]
The dotnet sdk projects seem to assume the obj directory under a project as the intermediate directory. This is very unpopular for advocates of read only source trees. The [ReadOnlySourceTree NuGet package](https://www.nuget.org/packages/ReadOnlySourceTree) fixes this for VS2015 style projects just by installing the package. But this needs to be revamped for .NET SDK projects, and in fact I wonder if it can even be effective since package restore itself creates the obj directory at the old location, so once the package is restored and diverts the obj directory to another place, the project.assets.json file won't be where it is expected to be.

So what is the plan for supporting read only source trees?

**Comment by dsplaisted** [comment]
> So what is the plan for supporting read only source trees?

Put a `Directory.Build.props` file in the root of your source tree that sets `BaseIntermediateOutputPath` and other relevant properties.

For more info, see #802, #803, #867, and https://github.com/Microsoft/msbuild/issues/1603.

**Comment by AArnott** [comment]
Love it. Thanks!
