### ISSUE TITLE
Microsoft.DotNet.MSBuildSdkResolver symbols are not archived

### ISSUE THREAD

**Issue by jmarolf** [dotnet/sdk#8872]
## Steps to reproduce
1. Debug Visual Studio
2. Look at loaded modules window

## Expected  behavior
Microsoft.DotNet.MSBuildSdkResolver symbols are loaded

## Actual behavior
Microsoft.DotNet.MSBuildSdkResolver symbols are not loaded

**Comment by joeloff** [comment]
I opened a project in VS2019, opened a second instance of VS and attached it to the first, then enabled the Microsoft Symbol Server under the Debugger Options. I right clicked on the load symbols and see this

![image](https://user-images.githubusercontent.com/7409981/84943003-920c0400-b098-11ea-890c-e287143d88d4.png)

@jmarolf Are you still seeing issues with the symbols?

**Comment by jmarolf** [comment]
this looks like it was fixed at some point. I see symbols loading now locally.
