### ISSUE TITLE
Attempting to migrate tells me I haven't installed dotnet SDK

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#891]
_From @davkean on February 20, 2017 1:11_

VS RC4 (26206.00):

1. Attempt to migrate https://github.com/ncarandini/VS2017RC4-issue

```
src\AspNetCoreLocalization.WebApp\AspNetCoreLocalization.WebApp.xproj: Could not read post-migration report at 'C:\Users\davkean\AppData\Local\Temp\e43ybmod.ktm'.
src\AspNetCoreLocalization.WebApp\AspNetCoreLocalization.WebApp.xproj: Failed to migrate XProj project AspNetCoreLocalization.WebApp. 'dotnet migrate --skip-backup -s -x "D:\VS2017RC4-issue\src\AspNetCoreLocalization.WebApp\AspNetCoreLocalization.WebApp.xproj" "D:\VS2017RC4-issue\src\AspNetCoreLocalization.WebApp" -r "C:\Users\davkean\AppData\Local\Temp\e43ybmod.ktm" --format-report-file-json' exited with error code -2147450735.
src\AspNetCoreLocalization.WebApp\AspNetCoreLocalization.WebApp.xproj: Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Show 3 additional messages
```

I'm not sure what the behavior is supposed to be. Note that this is not a clean machine, it's had various versions of dotnet SDK installed.

_Copied from original issue: dotnet/roslyn-project-system#1593_

**Comment by davkean** [comment]
I just installed 26217.2 D15Rel and it's telling the same thing. Doesn't the SDK come with VS?

**Comment by davkean** [comment]
What's the expectation here @livarcocc @333fred?

**Comment by livarcocc** [comment]
@davkean I just migrated this project without an issue through the command line. I add to add a NuGet.Config pointing the a myget feed for the new tools packages that are not on Nuget yet.

I don't have a windows box right now to try this on VS. I will try that once I am back in the office.

Other than that, everything is working.

@333fred Any ideas where that SDK message comes from in VS?

**Comment by 333fred** [comment]
@davkean could you post the other 3 messages? I can't find that message in the project system, sdk, or cli repos, so I'm not really sure where it's coming from.

**Comment by srivatsn** [comment]
The project has a global.json requiring the preview2 CLI - the message is likely that preview2 isn't installed?

**Comment by 333fred** [comment]
It should be removing the sdk element from the global.json though, so that shouldn't be it. I'll try to repro locally in a bit.

**Comment by livarcocc** [comment]
If this still reproes, please file a new issue for it in the CLI repo. Closing it here though.
