### ISSUE TITLE
Symbols for Microsoft.Net.Build.Tasks.dll are not be published

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#897]
The symbols for Microsoft.Net.Build.Tasks.dll are not being published to symweb - making it hard to debug them.

**Comment by nguerrera** [comment]
@srivatsn I think we should get this fixed for RTM.

@333fred Is there something missing from build definition for this?

I think we may be building with portable PDBs (SDK default, haven't confirmed we inherit it yet) which wouldn't be  compatible with symweb.

**Comment by 333fred** [comment]
Yeah, looks like we're missing the symbol step in our build definition. @nguerrera, if you can confirm whether our symbols will work with symweb, I'll add publishing.

**Comment by nguerrera** [comment]
Symbols are being fixed to work with symweb in #911

**Comment by 333fred** [comment]
Build has been updated an publish succeeded. We should start seeing symbols within the next 48 hours.
