### ISSUE TITLE
Update-Package - Error

### ISSUE THREAD

**Issue by lfscoelho** [dotnet/sdk#900]
Visual Studio 2015 Update3.

Migration` from .net core 1.0 to 1.1.

Steps to reproduce error:
1 - update global.json to 1.0.0-preview2-1-003177
2 -  project.json modified Microsoft.NETCore.App version:

> "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    }

3 - project.json modified netcoreapp version to 1.1:

> "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }

4 - Run `Update-Package `in Package manager console.

The result s a malformed project.json causing error in Dependencies.

**Comment by nguerrera** [comment]
Moved to nuget/home#4690
