### ISSUE TITLE
Explicit RID still required for .NET Framework test projects 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#909]
RID inference for .NET Framework is conditioned on 'OutputType=exe'. Test projects, however, may still be "executable" even if compile as a library. 

This means test projects for .NET Framework with native assets will fail. Either need a RID or users need to set OutputType=exe, which is not the default template setting.

**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```
```c#
using Microsoft.Data.Sqlite;
using Xunit;

public class SqliteConnectionTest
{
    [Fact]
    public void OpensConnection()
    {
        new SqliteConnection("Data Source=:memory:").Open();
    }
}
```
dotnet restore
dotnet test

**Expected**
Infers RID to win7-x86/x64 and test work :)

**Actual**
Tests build, but fail because the native component "sqlite3.dll" is missing from build output.

```
[xUnit.net 00:00:00.8776695]     SqliteConnectionTest.OpensConnection [FAIL]
[xUnit.net 00:00:00.8784311]       System.DllNotFoundException : Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Details**
dotnet --version: 1.0.0-rc4-004883

**Workarounds**
Add a `<RuntimeIdentifier>` or set `<OutputType>exe</OutputType>`.

**Comment by eerhardt** [comment]
Adding Blocking Partner since I just "closed as duplicate" an issue that was Blocking Partner.

**Comment by livarcocc** [comment]
@nguerrera this is the issue we chatted about before. Take a look when you have time.

**Comment by nguerrera** [comment]
This will be fixed by #1178 once the test project sets HasRuntimeOutput to true, which is now tracked by https://github.com/Microsoft/vstest/issues/792

**Comment by natemcmaster** [comment]
This is not fixed by #1178. Even if you add `HasRuntimeOutput` to the test project, you still need the explicit RID.

**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <HasRuntimeOutput>true</HasRuntimeOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-*" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```
```c#
using Microsoft.Data.Sqlite;
using Xunit;

public class SqliteConnectionTest
{
    [Fact]
    public void OpensConnection()
    {
        new SqliteConnection("Data Source=:memory:").Open();
    }
}
```
dotnet SDK 2.0.0-preview2-006082

**Result**
```
System.DllNotFoundException : Unable to load DLL 'sqlite3':
```

**Workdaround**
add explicit rid
```xml
<RuntimeIdentifier>win7-x64</RuntimeIdentifier>
```

**Comment by natemcmaster** [comment]
@nguerrera is this just because latest CLI hasn't ingested the SDK?

**Comment by nguerrera** [comment]
I think so. I'll check.

**Comment by nguerrera** [comment]
Yes, that was it. https://github.com/dotnet/cli/pull/6665 is out to update the SDK in the CLI.

**Comment by natemcmaster** [comment]
Thanks @nguerrera
