### ISSUE TITLE
Referencing a higher framework project shows different errors in error list and output window

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#910]
_From @BillHiebert on February 23, 2017 17:58_

1. New Class Libary (DotNet core)
2. Add New Console application (DotNet core)
3. Reference the class library from the console application
4. Edit the console applications project file and change the TFM from .netcoreapp1.1 to .netcoreapp1.0
5. Build the console applicatoin
Output window shows two errors, the first one is useful, then 2nd is confusing
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'c:\users\billhie\documents\visual studio 2017\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj' targets '.NETCoreApp,Version=v1.1'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v1.0'.
Done building project "ClassLibrary1.csproj" -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'c:\users\billhie\documents\visual studio 2017\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj'. This can indicate a missing project reference.
Done building project "ConsoleApp1.csproj" -- FAILED.
```
The error list only shows one error and unfortunately it is the 2nd one.

![image](https://cloud.githubusercontent.com/assets/1553785/23272029/9081bc00-f9ae-11e6-855e-81a68dfb3f27.png)

_Copied from original issue: dotnet/roslyn-project-system#1606_

**Comment by davkean** [comment]
This is similar to: https://github.com/dotnet/sdk/issues/798, but I'm sure whether it is tracking the second error.

**Comment by nguerrera** [comment]
#829 tracks not issuing the 2nd confusing error in the case where the project reference failed to bind.

The fact that not all errors are in the error list would not be due to the sdk right? This is the same symptom as https://github.com/dotnet/roslyn-project-system/issues/1470, which I will reopen.
