### ISSUE TITLE
[dotnet-cache]: Cache command does not use NuGet.config from the packages.xml directory

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#927]
1. Create a directory with packages.xml + NuGet.config that points to custom feeds (in this case the `dotnet-core` feed)
2. Run `dotnet cache --entries packages.xml --framework netcoreapp2.0 --runtime win7-x64 /p:FX_VERSION=2.0.0-*` (using /p:FX_VERSION since --fx-version doesn't exist as yet).

Expected:
The 2.0.0-* package is resolved and restored from the dotnet-core feed.

Actual:
`_RestoreCrossgen` fails to find the package. 

The issue is that the generated project is written and restored from to a temp directory and doesn't know about the NuGet.config in the PWD.

**Comment by pranavkm** [comment]
cc @eerhardt

**Comment by ramarag** [comment]
@pranavkm I don't think cache should be in the business of managing nugetisms
The way for it to work is provide is to provide -w option like -w workingdir

also for fx_version the option to use is **--framework-version**
```
dotnet cache -h
.NET Cache

Usage: dotnet cache [options] [[--] <additional arguments>...]]
```
Options:
  -h|--help                                   Show help information
  -e|--entries <ProjectEntries>               The XML file that contains the list of packages to be cached.
  -f|--framework <FRAMEWORK>                  Target framework for which to cache for.
  -r|--runtime <RUNTIME_IDENTIFIER>           Target runtime to cache for.
  -o|--output <OUTPUT_DIR>                    Output directory in which to cache the given assemblies.
  **--framework-version <FrameworkVersion>      The Microsoft.NETCore.App package version that will be used to run the assemblies.**
  --skip-optimization                         Skips the optimization phase.
  **-w |--working-dir <IntermediateWorkingDir>  The directory used by the command to execute.**
  --preserve-working-dir                      Preserves the intermediate working directory.
  -v|--verbosity                              Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

**Comment by pranavkm** [comment]
I think the Restore task uses the project directory and not the working directory to discover the NuGet.config hierarchy. If you're able to get it to use the right config files using the `-w` option, that would work. 

I missed the `--framework-version` option. I think the docs had it documented as `--fx-version`

**Comment by eerhardt** [comment]
I think the spirit of this bug is that the working directory should be under the current directory by default.  That way by default all of the things that use the current directory (like finding NuGet.config hierarhcy) work by default.

**Comment by ramarag** [comment]
We should make a call on the default. Right now the default does not touch users current working directory. To make this scenario by default then the --working-dir should be set to something like <current_working_dir>/obj by default

@livarcocc @gkhanna79

**Comment by gkhanna79** [comment]
Is having nuget.config in the current working directory, where a command like _dotnet cache_  or _dotnet restore_ is executed from, the expected semantic for consuming the additional feeds to use for restore @eerhardt ?

**Comment by pranavkm** [comment]
One of the scenarios @rynowak was trying out was to run the command on a working application. At the very least, those are meant to have NuGet.config files attached to them.

**Comment by gkhanna79** [comment]
> trying out was to run the command on a working application

Can you please elaborate on this? Were you trying to use _cache_ command on an app project? 

Please do keep in mind that while dotnet cache uses, as an input, an artifact that looks similar to a project file, the artifact needs to be intentionally created by the author to ensure that complete closure of the referenced packages is available for some source - this is the supported scenario.

**Comment by eerhardt** [comment]
> Is having nuget.config in the current working directory, where a command like dotnet cache or dotnet restore is executed from, the expected semantic for consuming the additional feeds to use for restore

Yes, totally.  I do this every day to point to myget feeds.  I never change my nuget.config that's in `%USERPROFILE%`.

It is also extremely common to have a NuGet.config at the root of a repo, so a developer or build machine can just pull the repo and run "dotnet XXX" commands.  The intended packages should be picked up from the specified feeds.

Note: NuGet.configs are hierarchical.  It combines the current working tree on up, and combines the %USERPROFILE% and the machine-wide configs.

See https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior for more info.

**Comment by gkhanna79** [comment]
Thanks @eerhardt. 

@ramarag In that case, I would presume that SDK should have infrastructure to locate and consume nuget.config that _cache_ command implementation should be able to consume, right?

**Comment by pranavkm** [comment]
@gkhanna79 the simpler solution would be to generate the project file and restore it in the working directory (rather than in a temp dir). I don't think users of the tool would particularly mind if running the tool produced intermediate artifacts.

**Comment by gkhanna79** [comment]
> working directory

Do you mean the obj folder or where the sources are? The former is fine but not the latter - we should not pollute source dir if not required.

I will let @ramarag figure out the specifics on how to get the right thing done.

**Comment by pranavkm** [comment]
The obj folder. It's still sort of polluting the working dir, but it's easily remedied by a `.gitignore`.
