### ISSUE TITLE
[dotnet-cache] Better error message is needed when more than one copy of coreclr.dll is found

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#930]
Ran in to this when I ran the tool with incorrect arguments: `.dotnet cache --entries .\packages.xml --framework netcoreapp1.1 --output .\bin --runtime win7-x64 /p:FX_Version=2.0.0-beta-001607-00`

The tool failed, however the error message `Microsoft.NET.CrossGen.targets(43,5): error : More than one file found for coreclr [\package-cache\packages.xml]` isn't particularly helpful.

**Comment by ramarag** [comment]
The issue no longer repros
