### ISSUE TITLE
Can`t add reference to System.XML

### ISSUE THREAD

**Issue by tarekgh** [dotnet/sdk#931]
@jokerosky commented on [Thu Sep 08 2016](https://github.com/dotnet/corefx/issues/11531)

I`ve created new solution for .net core (asp.net + class library) i need to add reference to System.XML but it fails with error, same time references to other libraries works well (for example System.Xml.Linq). I checked it on 3 different computers and got this error.

![image](https://cloud.githubusercontent.com/assets/6726130/18344350/187d0fa8-75e1-11e6-8164-bb65c6c40ffc.png)

---

@benaadams commented on [Fri Sep 09 2016](https://github.com/dotnet/corefx/issues/11531#issuecomment-245549302)

You need to either use the full framework System.Xml and add to `frameworkAssemblies` e.g.

``` json
"net452": {
  "frameworkAssemblies": {
    "System.Xml": {}
  }
}
```

Or to use the corefx you need to add the specific component you require as there is no System.XML and its is more modular. See: [System.Xml packages on nuget](https://www.nuget.org/packages?q=system.xml)

So for example if you want to use XmlDocument add a reference to [System.Xml.XmlDocument 4.0.1](https://www.nuget.org/packages/System.Xml.XmlDocument/)

---

@jokerosky commented on [Thu Sep 08 2016](https://github.com/dotnet/corefx/issues/11531#issuecomment-245627305)

oh, @benaadams  i found out what is wrong. I have added this direct links to framework assemblies, but it have not worked, because of case sensitive name. The problem is in Visual Studio 2015, which adds **System.XML** instead of **System.Xml**. so it is not dotnet issue. 

Can someone from MS team add this issue for VS guys and close this topic?

![image](https://cloud.githubusercontent.com/assets/6726130/18354503/03442368-7610-11e6-8260-98bbf7f6fdae.png)

---

@karelz commented on [Fri Sep 09 2016](https://github.com/dotnet/corefx/issues/11531#issuecomment-246006025)

@terrajobst any idea how/where in VS to route it?

**Comment by nguerrera** [comment]
This appears to have been an issue in the VS 2015 / project.json tooling. I will check that it is fixed in VS 2017 / csproj tooling, but I have strong reason to believe that it is.
