### ISSUE TITLE
VS and CLI use a different copy of the SDK

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#932]
I understand that VS needs to use the desktop MSBuild but you should unify the targets at some point to avoid the nonsense duplication that's going on.

At least at the .net SDK level by having it use the copy that's inside the CLI.

**Comment by ericstj** [comment]
Naievely it seems that the SDK.props & targets you put in the machine-wide MSBuild\Sdks should point to the dotnet sdk props & targets.

**Comment by srivatsn** [comment]
There is no machine-wide MSBuild anymore. Each copy of VS brings it's own copy of MSBuild installed inside the VS Install dir.

**Comment by srivatsn** [comment]
MSBuild is tracking building an acquisition story for SDKs and then VS and CLI won'r need to carry their own copies of the SDK - https://github.com/Microsoft/msbuild/issues/1493

**Comment by nguerrera** [comment]
SDK acquisition is the path forward. In the meantime, it's more complicated than "nonsense duplication"

**Comment by nguerrera** [comment]
Consider, for example, that the CLI sdk directory changes build-to-build (includes full version). There is no easy way to locate the correct CLI from a desktop msbuild context. This would be introducing a new and fragile dependency to just do as this issue suggests.

**Comment by ericstj** [comment]
So it's not OK for VS's MSBuild to locate the version specific SDK directory but it is OK for the dotnet CLI to locate it?  That seems silly.  They should behave the same way....

I can see how the SDK acquisition story will help but until that's available it seems that we should at least get VS and CLI using the same thing.

**Comment by nguerrera** [comment]
It's not silly. dotnet is locating its own assets deployed by its own installed. VS MSBuild does not depend on dotnet assets.

**Comment by nguerrera** [comment]
Duplicating how dotnet.exe picks an SDK in our Sdk.props/targets would be quite involved and we'd need to respect global.json, etc. Perhaps shelling out to something like `dotnet which-sdk` could work, but that would be bad for perf. 

Also, there are more SDKs than just this repo (also have to handle Pack and Web, etc.). We shouldn't put a band-aid hack in our targets.

Yes, they should behave the same, but there are other blockers to truly guaranteeing that. CLI also duplicates all of msbuild, compilers, and common targets.

**Comment by nguerrera** [comment]
Suppose there's a latest, greatest dotnet and the targets in there use an msbuild feature that doesn't exist in VS's version. Then installing that would break VS if VS just used latest as dotnet.exe would. So VS would really need to use the version of the CLI that it deployed as part of VS installation, but user can go and uninstall that in Programs and Features. Also, that version changes with each VS build, so we'd need to make our targets pick that up from somewhere. 

This is complicated enough to me that we shouldn't work on it because it will be superseded by the  SDK acquisition feature.

**Comment by ericstj** [comment]
> dotnet is locating its own assets deployed by its own installer. VS MSBuild does not depend on dotnet assets.

That's part of the problem.  On windows I think there should be a single thing responsible for installing them and the other thing just has the right hook to use it.

You don't shell out to get the SDK you burn it in and upgrade the file that has the burned in version so long as you're doing upgrades that you want VS to pick up.

I don't think it's all that complicated.  You just need the right layer of redirection and the right responsibility for asset installation.  I'll prototype something and share it.

**Comment by nguerrera** [comment]
Not interested in more prototypes pitched over the fence.

**Comment by nguerrera** [comment]
There is a clear conflict between what you're proposing and the feature msbuild is working on. We should pick one direction and work together on it. I think time would be better spent helping with the msbuild feature than prototyping a replacement that is a subset.

**Comment by ericstj** [comment]
Not really a conflict.  What I'm suggesting is just a different way to do what we have now without some side effects.  Once MSBuild feature comes along we switch to using that.

I'm not intending to generate more work here.  I'll also look into the msbuild feature and help where I can.
