### ISSUE TITLE
Filtering CopyLocalLockFileAssemblies

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#933]
When you use CopyLocalLockFileAssemblies with a netcoreapp project, it copies shared framework assets too.

While you can use publish instead to copy without those assemblies, there are circumstances where its more practical and efficient to just have the single build step. In particular pack is driven by build output not publish output. Consider the case where I want to flatten dependencies in a nupkg (e.g. as currently required to package msbuild tasks).

One way to address this would be to just have a flag to apply the same filtering as publish to CopyLocalLockFileAssemblies.

Alternatively, I find myself wishing that I could just slap metadata on my package references to exclude their full closure from CopyLocal. ExcludeAssets=Runtime almost works, but if I have another sibling package that pulls in overlapping assets in its closure, they get re-included.

In the msbuild task scenario, I really want to say "copy everything that is not in the closure of Microsoft.NETCore.App, Microsoft.Build.Framework, or Microsoft.Build.Utilities.Core"

I managed to get close enough to that with this workaround:

``` XML  
<PropertyGroup>
  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="Microsoft.Build.Framework" Version="15.1.548" ExcludeAssets="Runtime" />
  <PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.1.548" ExcludeAssets="Runtime" />
</ItemGroup>

<!-- Remove files from copy local that would not be published as they are provided by the platform package -->
<Target Name="FilterCopyLocal" DependsOnTargets="RunResolvePublishAssemblies" BeforeTargets="ResolveLockFileCopyLocalProjectDeps">
  <ItemGroup>
    <_CopyLocalButNotPublished Include="@(AllCopyLocalItems)" Exclude="@(ResolvedAssembliesToPublish)" />
    <AllCopyLocalItems Remove="@(_CopyLocalButNotPublished)" />
  </ItemGroup>
</Target>
```

**Comment by dsplaisted** [comment]
As noted in https://github.com/dsplaisted/sdk/commit/13989f17233b152716959cd5c81dacb446c1c24a, it is now necessary for `FilterCopyLocal` to depend on `PrepareForBuild;RunResolvePublishAssemblies`.

The reason for this is that with #1618, conflict resolution now depends on TargetFrameworkDirectory property, and the GetReferenceAssemblyPaths target to set it.  However, the custom FilterCopyLocal target in our projects was causing GetReferenceAssemblyPaths to run before GetFrameworkPaths, and when GetFrameworkPaths was subsequently run, it reset the TargetFrameworkDirectory property to v4.0.30319.

**Comment by jzabroski** [comment]
@peterhuene Is the milestone on this issue correct? When/how can I take advantage of this?

**Comment by peterhuene** [comment]
With a 3.0 SDK (including preview7 that came out today), we're now copying the assets locally for build like we would for a publish.  It should happen automatically (can be opted out of with setting `CopyLocalLockFileAssemblies` to `false`).

**Comment by nguerrera** [comment]
@Seabizkit I haven't worked on this in a long time and I've forgotten all the details. I think you might be better off filing a new issue describing what you want to achieve and what is stopping you so that the current team can help you.
