### ISSUE TITLE
Warnings about being unable to remove directories in cache test

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#940]
```
D:\Src\sdk\bin\Debug\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ComposeCache.targets(148,5): warning MSB3231: Unable to remove directory "D:\Src\sdk\bin\Debug\Tests\compose_with_fxfiles\SimpleCache\w". The process cannot access the file '\\?\D:\Src\sdk\bin\Debug\Tests\compose_with_fxfiles\SimpleCache\w' because it is being used by another process. [D:\Src\sdk\bin\Debug\Tests\compose_with_fxfiles\SimpleCache\SimpleCache.xml] [D:\Src\sdk\build\build.proj]
```

@ramarag Have you seen this?

**Comment by ramarag** [comment]
yes i have seen this. I believe this is a race condition within msbuild, have never been able to root cause it though!

**Comment by dsplaisted** [comment]
This might be caused by multiple tests (or different parameter sets for a theory) using the same output path.

**Comment by nguerrera** [comment]
@dsplaisted I don't think that's what happening from a quick scan of the tests in question. Also, it seems to happen on every build for me, so it isn't much of a race.
