### ISSUE TITLE
Update dotnet-sdk .deb/.rpm versioning to match dotnet-runtime

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#9456]
Deb and rpm packages for dotnet-runtime-2.1 and dotnet-sdk-2.1 are using different patterns for versioning. Per discussion with @rakeshsinghranchi and @leecow, let's update dotnet-sdk to follow what dotnet-runtime is doing.

For comparison, this is what the packages currently look like.

**Deb**
```
$ dpkg --info ./dotnet-runtime-2.1.1-rtm-26530-02-x64.deb
Version: 2.1.1~rtm-26530-02-1
 
$ dpkg --info ./dotnet-sdk-2.1.301-preview-008887-x64.deb
Version: 2.1.301-preview-008887-1
```

**Rpm**
```
$ rpm -qpiR ./dotnet-runtime-2.1.1-rtm-26530-02-x64.rpm
Version     : 2.1.1
Release     : 0.1.rtm_26530_02
 
$ rpm -qpiR ./dotnet-sdk-2.1.301-preview-008887-x64.rpm
Version     : 2.1.301_preview_008887
Release     : 1
```

cref https://github.com/dotnet/core-setup/issues/3850

**Comment by marcpopMSFT** [comment]
Given Lee's comment, I'm going to assume this was fixed in later versions. Also 2.1 is now out of support.
