### ISSUE TITLE
Add build parameter to specify default TargetLatestAspNetCoreRuntimePatch value (source-build)

### ISSUE THREAD

**Issue by dagood** [dotnet/sdk#9493]
Helps fix https://github.com/dotnet/source-build/issues/586. (Read the description for why we need to be able to set a default specific to source-build.)

A way I saw to do this is: https://github.com/dagood/cli/commit/4b89017b6640430e6d60217c4043f798c1d3d50c (using `Microsoft.NETCoreSdk.BundledVersions.props` to carry a source-build default value for `TargetLatestAspNetCoreRuntimePatch`). I don't know if it fits what the file's for.

@livarcocc does that look reasonable, or would you suggest something else?

/cc @tmds @natemcmaster

**Comment by marcpopMSFT** [comment]
Create a new bug if we hit issues during the 5.0 pass for source build.
