### ISSUE TITLE
Publish project to Ubuntu - File required after publication

### ISSUE THREAD

**Issue by ghost** [dotnet/sdk#9495]
## Steps to reproduce
I have a project called "MyProject, under Ubuntu machine".
Command: dotnet publish --runtime ubuntu-x64 --self-contained --configuration Debug
create folder MyProject/bin/Debug/netcoreapp2.0/publish/.
Now i can use command dotnet bin/configuration/netcoreapp2.0/publish/myproject.dll to run my app.

## Expected  behavior
I can delete all *.cs files, folder wwwroot and file appsettings.json under MyProject folder.
A copy of wwwroot and appsettings.json is also under MyProject/bin/Debug/netcoreapp2.0/publish

## Actual behavior
I can delete only all *.cs files, because app doesn't work without wwwroot and appsettings.json located under MyProject path.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Thanks for help

**Comment by MiYanni** [comment]
Old bug triage: We've changed self-contained over the years since this was reported. Also, the user for this issue no longer exists.
