### ISSUE TITLE
dotnet tool install should return exit code 0 if tool is already installed

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#9500]
I'm trying to write a script that will install global tools if necessary. I would like to just run "dotnet tool install", but this returns exit code 0 if the tool is already present, so I have to first execute `dotnet tool list` and grep the output.

## Expected  behavior
Calling `dotnet tool install` should no-op AND exit code 0 if the tool is already installed

## Actual behavior
Running dotnet tool install twice fails scripts because the second time it runs it will exit code 0
```
PS> & dotnet tool install --tool-path "$(pwd)/.tools" sleet --version 2.3.25 --add-source https://api.nuget.org/v3/index.json
You can invoke the tool using the following command: sleet
Tool 'sleet' (version '2.3.25') was successfully installed.
PS> $lastexitcode
0
PS>  & dotnet tool install --tool-path "$(pwd)/.tools" sleet --version 2.3.25 --add-source https://api.nuget.org/v3/index.json
Tool 'sleet' is already installed.
PS>  $lastexitcode
1
```

The result of this is that I have write more complicate code like this:

```ps1
if (& $dotnet tool list --tool-path "$PSScriptRoot/.tools" | Select-String "sleet") {
    Write-Host -f Yellow 'Skipping install of sleet. It''s already installed'
}
else {
    Invoke-Block { & $dotnet tool install --tool-path "$PSScriptRoot/.tools" sleet --version 2.3.25 --add-source https://api.nuget.org/v3/index.json }
}
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\dev\aspnet\Universe20\.dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\dev\aspnet\Universe20\.dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\dev\aspnet\Universe20\.dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\dev\aspnet\Universe20\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\dev\aspnet\Universe20\.dotnet\shared\Microsoft.NETCore.App]
```

**Comment by rmsy** [comment]
Is there no chance this is going to be re-visited, or at least a flag added to return `0` when the tool is already installed? It is a little ridiculous that `dotnet tool install` returns `1` when the tool already exists. At the very least, would you consider adding a flag as proposed in #10242? This is inconsistent with the behavior of every other package manager out there, that I know of at least.

**Comment by gravufo** [comment]
How many people will have to complain here for Microsoft to stop burying its head in the ground and scream that everything is fine?

**Comment by kylecooleylba** [comment]
Posting here because I agree with above comments should at least have a flag to return 0 if installed

**Comment by zoechi** [comment]
Makes it a pain in ansible

**Comment by rmsy** [comment]
@gravufo The `dotnet tool update` command "uninstalls and reinstalls a tool, effectively updating it." That is quite a joke and definitely not what an idempotent `install` command should do. The reality is that `dotnet tool install` should be a graceful no-op if the tool is already installed (as everyone here seems to agree, except for MSFT), and `dotnet tool update` should only update if there is a newer version determined to be available (but that's a different issue for a different thread). All of this is just Package Manager 101....

**Comment by eocern** [comment]
Excuse me @wli3 did I miss a statement why "dotnet install" can not return 0 if tool is already installed ?

**Comment by gojanpaolo** [comment]
We just hit into this issue with a GitHub Actions self-hoster runner.

**Comment by andersjonsson** [comment]
I agree with everyone that this is a weird and unexpected behavior.
Using ```dotnet update``` works and solves the problem but it's not an obvious thing. It sure isn't a "pit of success".

I just encountered this error on our CI-machine and had to google for a solution.

**Comment by Servellia** [comment]
I've written a small bash script, to check if something is installed. You can easily inline this in your azure-pipelines or whereever you need it:

```
gen=$(dotnet tool list --global | grep 'dotnet-reportgenerator-globaltool')
if [ -z "$gen" ]
then
    echo "Installing dotnet-reportgenerator-globaltool globally"
    echo "-----------------------------------------------------"
    dotnet tool install --global dotnet-reportgenerator-globaltool
else
    echo "dotnet-reportgenerator-globaltool is already installed. Skipping."
fi
```

Simply amend the grep-pattern to your needs.

**Comment by cliffchapmanrbx** [comment]
Echoing previous discussion, I just now was trying to set up a CI for a dotnet tool and ran into this. Seems like the better UX would be to introduce what Invoke-WebRequest has with `-SkipHttpErrorCheck`, which doesn't throw an exception if you get a 4xx or 5xx response code.

`dotnet tool install -g <tool> -SkipInstalledError` would be a more acceptable workaround for me.

**Comment by augustoproiete** [comment]
@cliffchapmanrbx and others participating in this issue, you should upvote the issue https://github.com/dotnet/sdk/issues/10310 which is similar and is currently open.

Using .NET Tools in a CI pipeline is currently painful and requires a lot of scripting to handle errors, which should be handled by `dotnet tool` directly.

I suggested a couple of different approaches that could help. Adding a flag would improve the UX by a lot:

```
dotnet tool install toolname --ignore-if-installed
```

If changing the `install` command is breaking and not possible, creating a dedicated `ensure` command could work:

```
dotnet tool ensure --local toolname --version toolversion
```

Expectations:

- If the command does not specify version, the latest version is installed. Exit code = 0
- If the command specify version 2.0.0 and tool 2.0.0 is already installed, do nothing. Exit code = 0
- If the command specify version 2.0.0 and tool 1.0.0 is already installed, upgrade to 2.0.0. Exit code = 0
- If the command specify version 2.0.0 and tool 3.0.0 is already installed, downgrade to 2.0.0. Exit code = 0

---

More details:
- https://github.com/dotnet/sdk/issues/10310#issuecomment-757602576
- https://github.com/dotnet/sdk/issues/15254#issuecomment-780309601

**Comment by bsolovij-ebsco** [comment]
Any movement on this?

**Comment by riverar** [comment]
Chiming in here, `update` does not appear to be a valid workaround for preview versions, which require an explicit version be specified.

**Comment by NaZaRKIN123** [comment]
A typical Microsoft way of doing things.

**Comment by RDavis3000** [comment]
This is unintuitive
This is also undocumented (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
This is universally rejected by MS customers in this thread
This is telling you that we don't need separate install/update commands
This is telling you that in CI/CD world we want UPSERT everywhere and parameters for version targeting etc

**Comment by cyril265** [comment]
How to annoy customers 101

**Comment by isidore** [comment]
```bash
dotnet tool install -g <tool> | echo "already installed"
```

**Comment by juescuder** [comment]
@isidore solution works as a charm. Thanks.

**Comment by dsplaisted** [comment]
As an update, we're thinking of changing the install behavior so that it will not fail if the tool is already installed.  This will mean that `dotnet tool install` will pretty much work the same way `dotnet tool update` already does.  Because of that, over time we might deprecate `dotnet tool update`.

We would likely add options to allow the old behavior, for example something like `--fail-if-already-installed` and `--update-only`.

**Comment by dsplaisted** [comment]
@augustoproiete I'm not sure what the behavior should be if the new version is a downgrade.  If a higher version is already installed maybe something depends on the higher version and would fail with the downgrade.  Maybe we should error on downgrades by default and have an `--allow-downgrade` option which would allow it to succeed.

**Comment by riverar** [comment]
I do not agree with the proposed downgrade behavior. I agree, with `--version` present, a downgrade should be considered an error without a `--force`.

**Comment by augustoproiete** [comment]
@dsplaisted @riverar Following the principle of deterministic builds, if the `--version` is present it means my process expects that particular version every time it runs, consistently.

Thus, I'd argue that should be the other way around e.g. A `--do-not-downgrade` option, which would prevent a downgrade when a higher version is already installed.

**Comment by LevYas** [comment]
This is still a needed feature

**Comment by baronfel** [comment]
This sounds be released in 8.0.200 next month!

**Comment by nagilson** [comment]
Closing this as completed by @JL03-Yue, let us know if you have any feedback! 🥳

**Comment by ronymeyer** [comment]
> > As an update, we're thinking of changing the install behavior so that it will not fail if the tool is already installed. This will mean that `dotnet tool install` will pretty much work the same way `dotnet tool update` already does. Because of that, over time we might deprecate `dotnet tool update`.
> > We would likely add options to allow the old behavior, for example something like `--fail-if-already-installed` and `--update-only`.
> 
> If I understand correctly, and based on what I'm seeing with on 8.0.402, the package is just reinstalled every time, even if the version is the same? It would've been nice to have it be idempotent like the issue author was requesting. Don't suppose this will change things now but current behavior feels wasteful of bandwidth and cpu when all we're doing is checking versions.

I agree with that. We have to use other workarounds as other parallel running processes which depend on dotnet tools fail when the update reinstalls the tools.

**Comment by pf-uvonceumer** [comment]
Here I am running into the same issue in 2025... I am trying to install a tool via ansible on a Ubuntu based build machine:
```
    - name: Install SonarQube scanner tool (dotnet-sonarscanner)
      shell: dotnet tool install --global dotnet-sonarscanner
```
And I get an error from ansible when the tool is already installed.
```
TASK [Install SonarQube scanner tool (dotnet-sonarscanner)] ***********************************************************************************************************************************
fatal: [my-machine]: FAILED! => {"changed": true, "cmd": "dotnet tool install --global dotnet-sonarscanner", "delta": "0:00:00.267661", "end": "2025-02-11 10:47:02.203748", "msg": "non-zero return code", "rc": 1, "start": "2025-02-11 10:47:01.936087", "stderr": "Tool 'dotnet-sonarscanner' is already installed.", "stderr_lines": ["Tool 'dotnet-sonarscanner' is already installed."], "stdout": "", "stdout_lines": []}
```
What is the proposed fix for this?

**Comment by akoeplinger** [comment]
@pf-uvonceumer make sure you're using a recent dotnet sdk, it works here:
```bash
root@049c72e13efa:/# dotnet --version
9.0.102

root@049c72e13efa:/# dotnet tool install --global dotnet-sonarscanner
You can invoke the tool using the following command: dotnet-sonarscanner
Tool 'dotnet-sonarscanner' (version '9.1.0') was successfully installed.

root@049c72e13efa:/# dotnet tool install --global dotnet-sonarscanner
Tool 'dotnet-sonarscanner' is already installed.

root@049c72e13efa:/# echo $?
0
```

**Comment by pf-uvonceumer** [comment]
Since I am on Ubuntu 22.04 LTS and required to use dotnet 8, this is unfortunately not an option for me.

**Comment by akoeplinger** [comment]
It also works with dotnet 8.0.405 here. You likely have dotnet installed from the Ubuntu/Canonical package repo which only provides the .1xx dotnet SDK feature band and this fix was done in 8.0.200.

On Ubuntu 22.04 you can install the Microsoft build by following https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

**Comment by pf-uvonceumer** [comment]
> It also works with dotnet 8.0.405 here. You likely have dotnet installed from the Ubuntu/Canonical package repo which only provides the .1xx dotnet SDK feature band and this fix was done in 8.0.200.
> 
> On Ubuntu 22.04 you can install the Microsoft build by following https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

Actually I am installing dotnet-sdk-8.0 via the MS repositories (talen from https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository). Here is my ansible snippet:

```
# Install SonarQube Support
    - name: Register Microsoft package repository
      shell: |
        source /etc/os-release
        wget https://packages.microsoft.com/config/$ID/$VERSION_ID/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
      args:
        chdir: /tmp  # Optional: define a working directory, if needed

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install .NET SDK 8.0
      apt:
        name: dotnet-sdk-8.0
        state: present

    - name: Install SonarQube scanner tool (dotnet-sonarscanner) as github-runner
      shell: dotnet tool install --global dotnet-sonarscanner
      args:
        creates: "/root/.dotnet/tools/dotnet-sonarscanner"
```

I added `creates: "/root/.dotnet/tools/dotnet-sonarscanner"` to prevent errors when the playbook is run a second time after dotnet-sonarscanner was installed.

**Comment by marcpopMSFT** [comment]
> We could consider backporting this fix to 8.0.100 based on user feedback [@marcpopMSFT](https://github.com/marcpopMSFT).

@baronfel you're thinking of our source build partner versions of the SDK? I assume we generally take those fixes so they don't have to backport themselves, correct? @MichaelSimons for an opinion on this.

**Comment by MichaelSimons** [comment]
> @baronfel you're thinking of our source build partner versions of the SDK? I assume we generally take those fixes so they don't have to backport themselves, correct? @MichaelSimons for an opinion on this.

Yes, it is best for upstream to backport these fixes for the greater good of all distros source-building .NET.

**Comment by pf-uvonceumer** [comment]
> [@pf-uvonceumer](https://github.com/pf-uvonceumer) I ran these commands on Ubuntu 22.04 and I get dotnet SDK 8.0.405 and installing tools twice works as expected without error. Check whether you really get the packages from MS repositories in the "Install .NET SDK 8.0" step.

Interesting. Thanks for checking. I will look into that.

**Comment by pf-uvonceumer** [comment]
Okay, I did some digging and it turns out that
- I am on Ubuntu 24.04.1
- the Microsoft package repositories were not properly added
- but: I still get 8.0.112-0ubuntu1~24.04.1 when I try to install / update dotnet-sdk-8.0
- and: the microsoft repositories don't list a dotnet-sdk-8.0 package
Weird...
