### ISSUE TITLE
Revert OS check when corefx FileVersionInfo bug is fixed

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#96]
We can revert 129a84130b154df895d5336972f517a7edfc6c2f when dotnet/corefx#11163 is fixed

**Comment by dsplaisted** [comment]
I tried fixing this in #1202, but it turns out that our unit tests still target .NET Core 1.0 so they aren't getting a version of FileVersionInfo with the fix.  So we need to untangle that before re-enabling this check on non-Windows.
