### ISSUE TITLE
"dotnet cache" --framework-version option should default from <RuntimeFrameworkVersion> in the proj file

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#961]
Create a project file that has the Packages you want to cache.  For example:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001682-00</RuntimeFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="1.3.0" />
    <PackageReference Include="Libuv" Version="1.9.1" />
  </ItemGroup>
</Project>
```

`dotnet cache --entries CacheStuff.csproj -r win10-x64`

### Expected Results

The command succeeds

### Actual Results

The `RuntimeFrameworkVersion` (which is used for all other commands to specify the `Microsoft.NETCore.App` version) is not respected.

```
Restoring packages for C:\Users\eerhardt\AppData\Local\Temp\owyfsgzn.y2x\Optimize\OptimizeCrossgen_win10-x64_netcoreapp2.0.csproj...
F:\dotnet\sdk\2.0.0-preview1-005383\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'. [C:\Users\eerhardt\AppData\Local\Temp\owyfsgzn.y2x\Optimize\OptimizeCrossgen_win10-x64_netcoreapp2.0.csproj]
F:\dotnet\sdk\2.0.0-preview1-005383\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0 (win10-x64)'. [C:\Users\eerhardt\AppData\Local\Temp\owyfsgzn.y2x\Optimize\OptimizeCrossgen_win10-x64_netcoreapp2.0.csproj]
````

### Notes

If I repeat myself on the command line by passing in `--framework-version 2.0.0-beta-001682-00`, it works.

/cc @gkhanna79 @blackdwarf

**Comment by nguerrera** [comment]
Are we keeping --framework-version and mapping it to RuntimeFrameworkVersion?

**Comment by eerhardt** [comment]
@nguerrera - as far as I know, yes.  Today we have `--framework-version` on the command line, which maps to `FX_Version` inside the project that is being cached, which maps to `RuntimeFrameworkVersion` in the temporary project that is actually restored.  My hope is that we completely remove `FX_Version`, and just map `--framework-version` to `RuntimeFrameworkVersion`.

@blackdwarf - can you comment on the naming of the options?

**Comment by ramarag** [comment]
We already went through the cache options once, anyway please open a bug in cli if the option names need to be changed

**Comment by livarcocc** [comment]
@ramarag My understanding of Eric's bug is not that he wants a new option, but rather that he wants the default implied from the values in the csproj.

Is this something we don't want to do?

**Comment by ramarag** [comment]
We are doing exactly that in https://github.com/dotnet/sdk/blob/91ff2017b3ac427ea13f7f5f5ad66d93a7ddba82/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets#L195

and also allow CLI to override the option in the project using -framework-version

Am i missing something else here ?

**Comment by livarcocc** [comment]
No. I wasn't aware that we were doing that already. Your previous answer did not indicated that. Indicated only that you discussed the options and didn't seem like we wanted to change that. I wanted to make sure we are doing the right thing for defaults, which seems we are.

**Comment by ramarag** [comment]
@livarcocc my bad, i though the referred PR was good enough, will be explicit from next time

**Comment by nguerrera** [comment]
>  My hope is that we completely remove FX_Version, and just map --framework-version to RuntimeFrameworkVersion.

Is this done?

**Comment by eerhardt** [comment]
Yes.  See 
https://github.com/dotnet/sdk/commit/91ff2017b3ac427ea13f7f5f5ad66d93a7ddba82
https://github.com/dotnet/cli/commit/a48f3a6bbff4a818f13255b739d67ce2684d10bf
