### ISSUE TITLE
Unable to reference net46 EF Library project from Core project targeting net46 also

### ISSUE THREAD

**Issue by mjnorman** [dotnet/sdk#963]
In VS2015 -- Upon attempting to include an EF 6 project as a reference to a .net core project targeting net46, receive the following error on build--

project 1 MVCCore (.net core targeting 46)
project 2 MOM-Data (.net 46, class library proj)

This is the same scenario as the given sample for VS2017 given [here](https://github.com/aspnet/Docs/tree/master/aspnetcore/data/entity-framework-6/sample) but am attempting in VS2015.

`
Failed to make the following project runnable: MVCCore (.NETFramework,Version=v4.6) reason: Could not find a part of the path 'C:\Users\mnorma001\Documents\git repositories\repos\TestAppCore\packages\Microsoft.AspNet.Mvc.5.2.3\lib\net45\System.Web.Mvc.dll'.	MVCCore	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	`

Oddly enough this is not the correct path for my project.  Both projects exist in my local git repo at `<documents>\repos\iis\<project>`, but notice in the error listed above, the path is `<documents>\repos\<project>` it does not include the repo name of iis, so the path is incorrect.

If I remove the second project reference, the project builds and runs.

project.json snippet for dependency--

`  "frameworks": {
    "net46": {
      "dependencies": {
        "MOM-Data": {
          "target": "project"
        }
      }
    }
  }`

**Comment by livarcocc** [comment]
It seems like you are following a sample for VS2017 using VS2015.

VS2015 tooling uses project.json and the last update for it was preview2. This is a no longer supported tooling and it has been superseded by the msbuild based tooling that ships with VS2017.

The projects are not compatible between one and another. I suggest that if you have xproj/project.json based projects that you migrate them to csproj and that you use the new VS2017 tooling.

**Comment by mjnorman** [comment]
I was afraid of such.  Thanks for confirming!
