### ISSUE TITLE
Add more logging to msbuild sdk resolver

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#9655]
- [ ] Adapt error messages to global.json / non-global.json cases
  - [ ] Log dotnet.exe path
  - [ ] Log global.json path
  - [ ] Log hostfxr calls, results, error codes
  - [ ] Log fallback
  - [ ] Log any and all environment overrides
  - [ ] Log VS settings path and all reads of VS settings file
  - [ ] Check that there is no perf degradation from this low importance logging in case where verbosity < diag

**Comment by MiYanni** [comment]
Old bug triage: We've added a bit more error logging but other logging endeavors would be addressed as separate issues. Closing.
