### ISSUE TITLE
System.Management unavailable when targeting net46

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/sdk#966]
I have a multi-targeting project with `<TargetFrameworks>netstandard1.3;net46</TargetFrameworks>` set.

I have some code which does a WMI query. I'd like to conditionally compile it for `NET46`, and do something else for `NETSTANDARD1_3`, but apparently I can't use `System.Management.ManagementObjectSearcher`, `System.Management.ManagementObject` and friends in either framework.

Am I missing something?

**Comment by davidfowl** [comment]
I don't think the SDK supports GAC references.

**Comment by livarcocc** [comment]
Can you try setting this `<AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>` in your project?

**Comment by yaakov-h** [comment]
@livarcocc That doesn't seem to have any effect.

**Comment by dsplaisted** [comment]
@yaakov-h Do you also have a referennce to System.Management?  A basic project would look something like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;net46</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <Reference Include="System.Management" />
  </ItemGroup>

</Project>
```

**Comment by yaakov-h** [comment]
@dsplaisted a-ha, that's what I was missing. I wasn't sure how to add a reference like that, the IDE provides nothing for that.

That works, thanks.
