### ISSUE TITLE
Remove --disable-parallel from CLI restore tests

### ISSUE THREAD

**Issue by dagood** [dotnet/sdk#9673]
https://github.com/NuGet/Home/issues/6742 and perhaps a http sockets issue make the CLI official builds flaky, so to work around it, `--disable-parallel` was added to `dotnet restore`s run during the CLI build/tests:

* https://github.com/dotnet/cli/pull/4516 "Use --disable-parallel during xplat restores"
* https://github.com/dotnet/cli/pull/9854 "[release/2.2.1xx] Add --disable-parallel to dotnet-new.Test"

Once the issue is fixed, those `dotnet restore` calls should be changed so they don't pass `--disable-parallel`.

**Comment by sfoslund** [comment]
Closing, no longer relevant.
