### ISSUE TITLE
Portable RID cache generation should validate asset presence

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/sdk#969]
When generating cache for a Portable RID (eg. linux-x64), if we encounter a package (as part of the transitive closure of the cache packages) that has native assets for RIDs other than portable, we should emit a warning indicating so to enable cache generators (or package authors) to identify possible breaks in cache. 

Otherwise, cache for distro specific RID will work, as expected since all native assets are restored but will fail for Portable RID.

CC @eerhardt @ramarag

**Comment by eerhardt** [comment]
@gkhanna79 - @ramarag and I think that this isn't necessary for 2.0.  I'm going to move it to 2.1.  Please move back to 2.0 if you disagree.

**Comment by gkhanna79** [comment]
I am fine with the move.

**Comment by nguerrera** [comment]
We are only making minimal investments in dotnet store from here on.
