### ISSUE TITLE
Add test coverage for targeting .NET Core 2.0 and .NET Standard 2.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#973]

**Comment by johnbeisner** [comment]
Completed - 1. Add coverage for P2P with .NET Standard/.NET Framework/.NET Core 1.x
In progress - 2. Add coverage for NuGet with .NET Standard/.NET Framework/.NET Core 1.x
Researching - 3. Add coverage for P2P with .NET Core 2.0
4. Add coverage for NuGet with .NET Core 2.0
Researching - 5. Add coverage for P2P with Mono/Xamarin/UWP
6. Add coverage for NuGet with Mono/Xamarin/UWP
7. Add coverage for P2P with 11 PCL profiles
8. Add coverage for NuGet with 11 PCL profiles

**Comment by johnbeisner** [comment]
[SDK-Compat.xlsx](https://github.com/dotnet/sdk/files/856246/SDK-Compat.xlsx)
