### ISSUE TITLE
Where did the Templates come from?

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#975]
They are not correctly attributed in this repo.

They are Apache 2 while the repo is MIT.

See: https://github.com/dotnet/sdk/blob/master/src/Templates/CSharpTemplatesSetup/CSharpTemplatesSetup.csproj

**Comment by nguerrera** [comment]
@natidea

**Comment by davkean** [comment]
They came from http://github.com/dotnet/roslyn-project-system.

**Comment by livarcocc** [comment]
Any particular reason they are apache @davkean? Can we update them to MIT?

**Comment by davkean** [comment]
They came from project system, hence the Apache license. I don't know of a reason.

**Comment by richlander** [comment]
We shouldn't just arbitrarily re-write licenses even if they are within the .NET Core project. It's arbitrary in nature. 

The correct thing to do is make a 3PN for RPS from the SDK repo.

**Comment by nguerrera** [comment]
@richlander Can you spell out those acronyms? Bing did not help me out.

**Comment by omajid** [comment]
My understanding:

3PN: Third Party Notice
RPS: Roslyn Project System
SDK: github.com/dotnet/sdk

We should create a ThirdPartyNotices file that points out that dotnet/sdk includes code that's originally from dotnet/roslyn-project-system and is licensed under a different license than the rest of dotnet/sdk. For example, dotnet/core-setup includes a third party notice [for sources](https://github.com/dotnet/core-setup/blob/master/THIRD-PARTY-NOTICES) and another one [for binaries](https://github.com/dotnet/core-setup/blob/master/resources/ThirdPartyNotices.txt).

**Comment by nguerrera** [comment]
There's no genuine third party here. We wrote all the code on the same Microsoft team. I don't think it's arbitrary to re-license in this case.

**Comment by livarcocc** [comment]
Templates no longer live in this repo.
