### ISSUE TITLE
EmbeddedResources that end with *.cs are compiled into project.

### ISSUE THREAD

**Issue by conniey** [dotnet/sdk#977]
**Repro Steps:**

1. Create a .NET Core Application (netcore.csproj)
2. Create a .cs file, lets call it: `test.cs` with a `public static void Main(string args[]) {}`
3. In netcore.csproj, add the cs file as an <EmbeddedResource>

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
      <EmbeddedResource Include="test.cs" />
  </ItemGroup>
```

4. Try to build the application.

**Expected:**  It does not try to compile `test.cs` because it notices that it is an embedded resource.  This worked before.
**Actual:** It produces this error and when I check msbuild at diagnostic level, I notice it is being passed as a compile item.

```
"D:\git\conniey\dotnet-apiport\tests\Microsoft.Fx.Portability.Cci.Tests\Microsoft.Fx.Portability.Cci.Tests.csproj" (default target) (1) ->
(CoreCompile target) ->
  Tests\EmptyProject.cs(5,28): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [D:\git\conniey\dotnet-apiport\tests\Microsoft.Fx.Portability.Cci.Tests\Microsoft.Fx.Portability.Cci.Tests.csproj]
```

As a workaround, I had to add a target to manually remove this target:
```xml
  <Target Name="RemoveEmbeddedResources"
          BeforeTargets="CoreCompile">
    <ItemGroup>
        <Compile Remove="@(EmbeddedResource-> '%(Identity)')" />
    </ItemGroup>
  </Target>
```

**Comment by dsplaisted** [comment]
> **Expected:** It does not try to compile test.cs because it notices that it is an embedded resource. This worked before.

When you say it worked before, are you referring to one of the RC releases, or VS 2015?  We went through several iterations on how we include items by default, and the current behavior is where we landed.

You don't need a target to remove the embedded resources from `Compile`, you can just do it directly in an ItemGroup.

There's some documentation on this here: https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-default-compile-items.md

**Comment by conniey** [comment]
It worked in VS2015, is what I meant.  

> You don't need a target to remove the embedded resources from Compile, you can just do it directly in an ItemGroup.

I thought about it but its not maintainable.  It would require double the work because I would have to add the .cs file in the EmbeddedResource ItemGroup and then remove it as well from the Compile ItemGroup.

> We went through several iterations on how we include items by default, and the current behavior is where we landed.

I am not sure the current behaviour is ideal.  I expected that if I explicitly specified some items, the build system would not override the behaviour.

**Comment by nguerrera** [comment]
>  I expected that if I explicitly specified some items, the build system would not override the behaviour.

Your example is relying on the implicit items to compile the real Main. If you want total control, you can set EnableDefaultItems=false and then list all items of all kinds explicitly.

It is not workable to have some hybrid where we remove any item of a different kind from every implicit item. For what it's worth, I'm personally not a fan of implicit items at all. But it was debated a ton and I lost on it. I think as long as we have implicit items as the default, the current behavior is much simpler than what is proposed here.
