### ISSUE TITLE
Add test that each template builds correctly in core-sdk

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#9859]
In https://github.com/dotnet/cli/pull/10158/commits/a2896af8a92ad6ec9672e66963b4b2077e58ce9f, I removed a test which tested that none of the new project templates used the Microsoft.DotNet.Cli.Utils NuGet package.  We shouldn't need to test that the package isn't used anymore, but it would be good to have coverage that each of the templates create projects that build successfully.  However, this coverage should be in the core-sdk repo.

It's possible that we already have coverage of this in core-sdk, but we should add it if we don't.

**Comment by marcpopMSFT** [comment]
No longer a priority.
