### ISSUE TITLE
Exposing Windows.Foundation.UniversalApiContract and other contracts as NuGet package

### ISSUE THREAD

**Issue by Reza1024** [dotnet/sdk#986]
Hi,

I am trying to create a netcore library to be consumed in a Windows 10 app (UAP)
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="5.3.1" />
  </ItemGroup>
</Project>
```
But a big part of the API is not present in `Microsoft.NETCore.UniversalWindowsPlatform` and instead they are some contracts (`Windows.Foundation.UniversalApiContract`, ...) which cannot be added as a reference to the project. So none of the [UWP Apis](https://docs.microsoft.com/en-us/uwp/api/) can be consumed. It seems that these apis are internally available as [target packing](https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Runtime.WindowsRuntime/src/project.json#L12). Should not these apis be exposed externally as a nuget package so we could do:
```
<PackageReference Include="Windows.Foundation.UniversalApiContract" Version="[SDK Version]" />
```
Or is there any alternative way of doing that?

**Comment by livarcocc** [comment]
@richlander @terrajobst do you guys know what is the right way to track or ask for UWP apis to be exposed as nuget packages.

I am closing this issue in the SDK as I don't believe it belongs here.

**Comment by richlander** [comment]
This wouldn't work. You need to target netstandard1.4.
