### ISSUE TITLE
AssemblyInfo.cs how to generate with BOM?

### ISSUE THREAD

**Issue by Looooopy** [dotnet/sdk#989]
Is it possible to generate a AssemblyInfo.cs with BOM?

I have stylecop analyzers that complain on the generated AssemblyInfo.cs and do not want to turn it of.
For now i have set it to down from error to a warning so i can compile the project.

**Comment by codito** [comment]
In VS, the generated assemblyinfo has this header, static analysis tools skip it because of this header. Can such a header added in CLI build as well?

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

**Comment by dasMulli** [comment]
Suggest moving this to MSBuild where the responsible Task comes from
(https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/WriteCodeFragment.cs)

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#1912
