### ISSUE TITLE
Don't require MyGet feeds to be set up in order to target .NET Core 2.0 / .NET Standard 2.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#991]
The 2.0 templates currently include a packages.config [in the project folder](https://github.com/dotnet/templating/blob/bfe0d9d6ba85cdaa17a81ef4cafe635a41ae2ac6/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ConsoleApplication-CSharp/NuGet.config) in order to add the dotnet-core MyGet feed which is where the preview packages for .NET Standard 2.0 and .NET Core 2.0 are published.

We should try to remove this requirement.  Possibilities for doing this could include:

- Including the necessary packages in the preinstalled package cache in the .NET CLI and VS
- Adding an additional restore source via the .NET SDK (ie setting an item that the restore task consumes)

**Comment by dsplaisted** [comment]
> - Adding an additional restore source via the .NET SDK (ie setting an item that the restore task consumes)

I chatted with @emgarten about this.  There is a `RestoreSources` property which might work for this, however, it may not work in all scenarios.  For example:

- It may not flow correctly across different projects in a solution
- Restore in Visual Studio probably doesn't respect this property
- Restore on a .sln file may not respect this property

**Comment by livarcocc** [comment]
We worked through 1.0 like this and the NuGet.Config files are already being dropped with the templates to make this work. We won't address this for 2.0.

**Comment by dsplaisted** [comment]
The VS templates don't have this. Also retargeting to 2.0 won't work in preview versions of the tools.

If we put these packages in the local package store does that mean we wouldn't need the feeds set up?

**Comment by livarcocc** [comment]
VS will likely carry the packages in its own offline cache.

For the CLI, correct, we will also carry them in our own offline cache.

**Comment by dsplaisted** [comment]
In that case could we remove the packages.config file from the templates?  Or if not do we need to add it to the project templates that Visual Studio uses?

**Comment by davidfowl** [comment]
So dogfooing will still suck?

**Comment by nguerrera** [comment]
In 3.0 you can use the templates with no package references offline on any build. And the feeds are only needed for self-contained or things that need a daily build package reference. This has been the agreed upon plan so I'm closing this.
