### ISSUE TITLE
Support for "classic" ASP.NET

### ISSUE THREAD

**Issue by Kralizek** [dotnet/sdk#997]
I was planning to migrate a couple of classic ASP.NET projects to the new csproj format but [this article](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) says it's not supported.

Is it actually true? If so, it would be a pity since statistically the web project file is where most of our conflicts happen.

Also, current file size: 267 KB...

**Comment by livarcocc** [comment]
Do you mean ASP.NET 4 projects? If that's the case, that's correct, it is not currently supported.

**Comment by Kralizek** [comment]
Yes, I meant those. Is there a timeline for this kind of support?

I was trying hacking and slashing and one of the biggest stopper is that there are few NuGet packages that offer some MSBuild props or targets files but it's hard to reference them from the project file since there is no explicit Packages folder anymore.

**Comment by livarcocc** [comment]
We do support full framework on windows, but I don't know about tools or other things that a ASP.NET 4 project might depend on. You will get a better answer to this question at the aspnet/home repo, I think.

I am closing this issue. Please feel free to ask the question at the repo I mentioned above.

**Comment by Kralizek** [comment]
Thanks! reposted here: https://github.com/aspnet/Home/issues/1978
