### ISSUE TITLE
IConfigurationRoot and Debug

### ISSUE THREAD

**Issue by weshaggard** [dotnet/sdk#998]
@dpedrelli commented on [Thu Mar 16 2017](https://github.com/dotnet/standard/issues/244)

Hi,

I have two issues and I am not sure what is the most appropriate forum to post this.  If it should be posted in one or more other forums, please advise.  I, recently, upgraded to VS 2017.  

I have VS 2017 RC4 running on Windows Server 2012.  I have a .NET Standard 1.4 class library project that is referenced by a .NET 4.6.1 WinForms project.  I have an appsettings.json and I am using ConfigurationBuilder and IConfigurationRoot to read the appesttings.json and bind it to a model.  Everything works fine.

I have VS 2017 RTW running on Windows 7 Professional.  I cloned the above class library to the Windows 7 machine.  I am referencing the project by a WPF app and a WinForms app, both targeting .NET 4.6.1.

I am having two issues:
1)  When I run the WinForms project on Windows Server 2012, in debug mode, all of the Nuget libraries are copied to the Debug directory.  When I run either project on Windows 7, none of the Nuget libraries are copied to the Debug directory and I get errors that the library DLL's cannot be found to load.  All the Nuget packages are downloaded to a combination of my <user>\.nuget\packages and <project>\packages directories.  If I, manually, copy the DLLs to the Debug directory, they load and the program runs.

2)  On Windows Server 2012, the ConfigurationBuilder builds, instantiating an IConfigurationRoot, which binds the appsettings.json to the model.  On Windows 7, Configuration = builder.Build(); returns null.  It is the exact same project that works on Windows Server 2012 and I can confirm that the appsettings.json exists, using File.Exists().

Thanks.

---

@dpedrelli commented on [Thu Mar 16 2017](https://github.com/dotnet/standard/issues/244#issuecomment-287160126)

Apparently, there were some more Nuget dlls that had to be copied.  I, also, had problems between selecting .netstandard and .net4x dlls.  I ended-up copying all of the Nuget dlls from the Windows Server 2012, Debug directory.  Now, I can bind appsettings.json to the model.  

It appears the entire problem has to do with VS 2017 not coping or not locating the appropriate Nuget dlls.  How do I resolve this issue with Visual Studio?  Is that specific to Visual Studio or is that part of the VS project template?

**Comment by dpedrelli** [comment]
Is there a resolution to VS not copying the required DLLs?  I copy the DLLs manually and I get inconsistent and sketchy results.  It, also, takes considerable time to do so.  Is there a way to ensure that VS copies the required DLLs?

**Comment by livarcocc** [comment]
This is a really old issue without any new activity. I am going to close it. If this still repros, please file a new issue with repro steps on it for us to investigate further.
